### ISSUE TITLE
group_vars variables not getting picked up in playbook

### ISSUE THREAD

**Issue by gisundar** [ansible/ansible#42926]
##### SUMMARY

```
Inventory Dir structure -> C:\Users\111111\devrepo\ansible\inventory
C:\Users\111111\devrepo\ansible\inventory>dir
 Volume in drive C is SOE
 Volume Serial Number is BAC7-2240

 Directory of C:\Users\111111\devrepo\ansible\inventory

07/18/2018  12:45 PM    <DIR>          .
07/18/2018  12:45 PM    <DIR>          ..
07/18/2018  12:45 PM    <DIR>          ALL
07/18/2018  12:20 PM    <DIR>          DEV
07/18/2018  12:20 PM    <DIR>          PROD
07/18/2018  12:20 PM    <DIR>          SIT
07/18/2018  12:20 PM    <DIR>          UAT

C:\Users\111111\devrepo\ansible\inventory\DEV>dir
 Volume in drive C is SOE
 Volume Serial Number is BAC7-2240

 Directory of C:\Users\111111\devrepo\ansible\inventory\DEV

07/18/2018  12:20 PM    <DIR>          .
07/18/2018  12:20 PM    <DIR>          ..
07/18/2018  02:46 PM    <DIR>          group_vars
```
hosts files->
```ini
[DEV]
10.23.139.14
10.23.139.15
10.23.139.16
```
group_vars folder has a file named DEV.yml
Which has variables defined as follows
```
---
env_vars:
  cred:
    username: cdadmin  
    kibanauser: kibanauser
    kibanapasswd: xxxxxxxx
    elasticuser: elastic
    elasticpasswd: xxxxxx
  elastic:
    elkServerName: 10.111.111.22
    elkServerPort: 9200  
  package:
    packageUrl: https://artifactory.global.abc.com/artifactory/generic-release/ERR/EDMp-RB-RA-UA/packetbeat-5.4.3-x86_64.rpm
    dashboardsPackUrl: https://artifactory.global.abc.com/artifactory/generic-release/ERR/EDMp-RB-RA-UA/beats-dashboards-5.4.3.zip 
    instPackUrl: https://artifactory.global.abc.com/artifactory/generic-release/ERR/EDMp-RB-RA-UA/rpms_07092018.tar 
    pkgVersion:  5.4.3-x86_64
    dashboardVersion: 5.4.3
    rpmUplVersion: 07092018
    download_dir: /tmp/beats_download 
  config:
    configFilesUrl: https://artifactory.global.abc.com/artifactory/generic-release/ERR/EDMp-RB-RA-UA/yml_07092018.tar 
    configVersion: 07092018
    config_dirPB: /etc/packetbeat 
    config_dirFB: /etc/filebeat
    config_dirMB: /etc/metricbeat
  kafka:
    kafkaserver: hklpadrad01.global.abc.com
    kafkaport: 6667
  zookeeper:
    zookeeper1: hklpadrad01.global.abc.com
    zookeeper2: hklpadrad02.global.abc.com
    zookeeper3: hklpadrad03.global.abc.com
    zookport: 2181
```
In my playbook I am referencing it like this
```yaml
---
- 
  hosts: "{{ target_server }}"

  tasks:
  

  - name: Set tvars
    set_fact:
      elkServerName: "{{ env_vars.elastic.elkServerName }}"
      elkServerPort: "{{ env_vars.elastic.elkServerPort }}"
      kibanauser: "{{ env_vars.cred.kibanauser }}"
      kibanapasswd: "{{ env_vars.cred.kibanapasswd }}"
      elasticuser: "{{ env_vars.cred.elasticuser }}"
      elasticpasswd: "{{ env_vars.cred.elasticpasswd }}"
      kafkaserver: "{{ env_vars.kafka.kafkaserver }}"
      kafkaport: "{{ env_vars.kafka.kafkaport }}"
      zookeeper1: "{{ env_vars.zookeeper.zookeeper1 }}"
      zookeeper2: "{{ env_vars.zookeeper.zookeeper2 }}"
      zookeeper3: "{{ env_vars.zookeeper.zookeeper3 }}"
      zookport: "{{ env_vars.zookeeper.zookport }}"

```
It fails with error message saying
```
[Ansible_2.1] $ sh -e /apps/jenkins/build/tools/org.jenkinsci.plugins.ansible.AnsibleInstallation/Ansible_2.1/hudson1559227427372627104.sh
ansible-playbook 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[AnsibleDeploy] $ sshpass ******** /usr/bin/ansible-playbook ansible/beatsDeploy.yml -i ansible/inventory/ -u cdadmin -k -e target_server=DEV

PLAY [DEV] *********************************************************************

TASK [setup] *******************************************************************

ok: [10.23.139.14]

ok: [10.23.139.15]

ok: [10.23.139.16]

TASK [Set tvars] ***************************************************************
fatal: [10.23.139.14]: FAILED! => {"failed": true, "msg": "'env_vars' is undefined"}
fatal: [10.23.139.16]: FAILED! => {"failed": true, "msg": "'env_vars' is undefined"}
fatal: [10.23.139.15]: FAILED! => {"failed": true, "msg": "'env_vars' is undefined"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @ansible/beatsDeploy.retry

PLAY RECAP *********************************************************************
10.23.139.14               : ok=1    changed=0    unreachable=0    failed=1   
10.111.111.22              : ok=1    changed=0    unreachable=0    failed=1   
10.23.139.16               : ok=1    changed=0    unreachable=0    failed=1   


```

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```
[Ansible_2.1] $ sh -e /apps/jenkins/build/tools/org.jenkinsci.plugins.ansible.AnsibleInstallation/Ansible_2.1/hudson1559227427372627104.sh
ansible-playbook 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[AnsibleDeploy] $ sshpass ******** /usr/bin/ansible-playbook ansible/beatsDeploy.yml -i ansible/inventory/ -u cdadmin -k -e target_server=DEV

PLAY [DEV] *********************************************************************

TASK [setup] *******************************************************************

ok: [10.23.139.14]

ok: [10.23.139.15]

ok: [10.23.139.16]

TASK [Set tvars] ***************************************************************
fatal: [10.23.139.14]: FAILED! => {"failed": true, "msg": "'env_vars' is undefined"}
fatal: [10.23.139.16]: FAILED! => {"failed": true, "msg": "'env_vars' is undefined"}
fatal: [10.23.139.15]: FAILED! => {"failed": true, "msg": "'env_vars' is undefined"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @ansible/beatsDeploy.retry

PLAY RECAP *********************************************************************
10.23.139.14               : ok=1    changed=0    unreachable=0    failed=1   
10.23.139.15               : ok=1    changed=0    unreachable=0    failed=1   
10.23.139.16               : ok=1    changed=0    unreachable=0    failed=1   

```
