### ISSUE TITLE
get_url module does not work ansible 2.6.1

### ISSUE THREAD

**Issue by yamada-k-ts** [ansible/ansible#42930]
##### SUMMARY
get_url module does not work

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
get_url module

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /Users/yamada_k/.ansible.cfg
  configured module search path = ['/Users/yamada_k/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/yamada_k/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ansible
  executable location = /Users/yamada_k/.pyenv/versions/3.6.5/bin/ansible
  python version = 3.6.5 (default, May  9 2018, 15:56:13) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/Users/yamada_k/.ansible.cfg) = -o UserKnownHostsFile=/dev/null -F /Users/yamada_k/.
DEFAULT_HOST_LIST(/Users/yamada_k/.ansible.cfg) = ['/Users/yamada_k/.ansible/ec2.py']
HOST_KEY_CHECKING(/Users/yamada_k/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
macOS High Sierra
10.13.5（17F77）

##### STEPS TO REPRODUCE
it doesn't work
```
- name: Download nvm
  get_url:
    url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
    dest: "/home/{{ deploy_user }}/install.sh"
    mode: 0755
  become_user: "{{ deploy_user }}"
  when: current_nvm_version.stdout != "{{ nvm_version }}"
```

##### EXPECTED RESULTS
get_url module should work correctly

##### ACTUAL RESULTS
```
fatal: [10.108.0.124]: FAILED! => {"changed": false, "dest": "/home/deploy/install.sh", "msg": "An unknown error occurred: [Errno 13] Permission denied: '/var/tmp/ansible-tmp-1531903854.747469-68457095877183/tmpnuBvZa'", "state": "absent", "url": "https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh"}
```

**Comment by yamada-k-ts** [comment]
when ansible 2.6.0, 2.5x , it worked.

my environment below.
```
pip list | grep pip
pip             10.0.1
``` 
```
pip list | grep boto
boto            2.49.0
boto3           1.7.59
botocore        1.10.59
``` 
```
python -V
Python 3.6.5
```

**Comment by yamada-k-ts** [comment]
and it works below.
without get_url module
```
- name: Download nvm
  shell: "wget https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
  args:
    chdir: "/home/{{ deploy_user }}"
  become_user: "{{ deploy_user }}"
  when: current_nvm_version.stdout != "{{ nvm_version }}"

- name: chmod 755 install.sh
  file:
    path: "/home/{{ deploy_user }}/install.sh"
    mode: 0755
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
```
