### ISSUE TITLE
Need assistance with Post provisioning tasks in AWS EC2

### ISSUE THREAD

**Issue by Zorrom** [ansible/ansible#42935]
##### SUMMARY

Using Ansible playbook I am able to spin up a Windows instance in AWS Ec2 and I want to perform post tasks like adding that windows machine to a domain. I need assistance with the next set of codes, and attaching my current working code below as follows

My code is spinning up the windows vm successfully and I have an Administrator user there. So my post tasks is to run another play that will accept the Admin user , password and initiate a winrm connection and then perform win_domain tasks
##### ISSUE TYPE

None
##### COMPONENT NAME

ec2
##### ANSIBLE VERSION

```
2.4.5.0
```

##### OS / ENVIRONMENT

Rhel 7.5
##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Provision an instance
      ec2:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         key_name: "{{ key_name }}"
         instance_type: "{{ instance_type }}"
         instance_profile_name: "{{ instance_profile_name }}"
         image: "{{ image }}"
         wait: yes
         wait_timeout: 500
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         group_id: "{{ group_id }}"
         assign_public_ip: yes
         count: 1
         count_tag: "{{ count_tag }}"
         instance_tags: 
            Name: "{{ instance_tags }}"
         region: "{{ region }}"
      register: ec2
   
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

#What code do I have to use here so that Ansible next play can start performing post tasks on the VM that just spun

```

##### ACTUAL RESULTS

```
Code is working fine and just need assistance with the next set of code for post tasks. Windows machine is already running winrm service and my next play should perform a windows domain tasks as winrm
```
