### ISSUE TITLE
Flatpak module throws when installing Kdenlive via Flathub

### ISSUE THREAD

**Issue by egeexyz** [ansible/ansible#42966]
##### SUMMARY
The new Flatpak module throws a `TypeError: a bytes-like object is required, not 'str'` when attempting to install Kdenlive from Flathub.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
flatpak

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/egee/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 13:11:40) [GCC 8.1.1 20180531]
```

##### CONFIGURATION
Default - nothing changed

##### OS / ENVIRONMENT
Running on Manjaro (Arch Linux)

##### STEPS TO REPRODUCE
Run a playbook that attempts to install Flatpak from Flathub

```yaml
---
- hosts: localhost
  become: true
  tasks:
  - name: Install the Kdenlive flatpak
    flatpak:
      name:  https://flathub.org/repo/appstream/org.kde.kdenlive.flatpakref
      state: present
      remote: flathub
```

##### EXPECTED RESULTS
Kdenlive should be installed from Flathub

##### ACTUAL RESULTS
A TypeError is thrown and Kdenlive is not installed.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_r24u1r03/ansible_module_flatpak.py\", line 249, in <module>\nmain()\n  File \"/tmp/ansible_r24u1r03/ansible_module_flatpak.py\", line 240, in main\n    if state == 'present' and not flatpak_exists(module, binary, name, method):\n  File \"/tmp/ansible_r24u1r03/ansible_module_flatpak.py\", line 157, in flatpak_exists\n    if name in output.lower():\nTypeError: a bytes-like object is required, not 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
