### ISSUE TITLE
Allow per host and per group vairable assignment

### ISSUE THREAD

**Issue by tszming** [ansible/ansible#4296]
site.yml

```
- hosts: db
  user: ubuntu
  sudo: True
  tasks:
    ..
```

hosts

```
[db]
localhost max_mem=100

[web]
localhost max_mem=200
```

Under 1.3.2, the later variable of the same host always override any previous value, even they are in a wrong group, i.e., even I am targeting `db` in my site.yml above, I still incorrectly get  `max_mem=200` in my templates.
