### ISSUE TITLE
Should not modify the registered variable if a task has been skipped

### ISSUE THREAD

**Issue by tszming** [ansible/ansible#4297]
Similar to this issue: https://github.com/ansible/ansible/pull/1616

When a task is skipped, it should not update the registered variable, e.g

```
- hosts: all
  user: ubuntu
  sudo: True
  vars:
    var1: True
  tasks:
   - name: one
     command: /bin/echo one
     when: var1
     register: var2

   - name: two
     command: /bin/echo two
     when: not var1
     register: var2

   - name: three
     command: /bin/echo three
     when: var2.changed
```

I expect task three should not be skipped.

If I change task two to register other variable then task three will not be skipped -  but as it is skipped, it should not affect the running state.

**Comment by srgvg** [comment]
On skipped tasks, variables are overwritten with a value of {'skipped': True}.

When you register the same variable multiple times, and some of those tasks are conditional, when you check on the registered var later, you have to check if it was not skipped:

your last conditional should hence be:
`when: not var2.skipped and var2.changed`

**Comment by mpdehaan** [comment]
Yep, what Serge says is correct.

This way when iterating over them in hostvars (and elsewhere) we have a record of those that were skipped.

when: not var2|skipped and var2.changed

(or you could also consider just using a handler, and the "force handlers" trick)

```
- name: two
  command: /bin/echo one
  when:  whatever_as_needed_could_go_here
  notify:
      - three

- meta: flush_handlers
```

And then in handlers:

```
  name: three
  command: /bin/echo three
```

**Comment by tszming** [comment]
`when: not var2.skipped and var2.changed` will not work as in my example above, task3 should always be executed since either task1 or task2 will register `var2` anyway (under my original assumption, of course which is not valid under the current implementation)

The reason of keeping history is weak since it only keep the last result, but it will override as many times as I use the same variables name.

Of course, using handlers should works.

**Comment by solomongifford** [comment]
If anyone comes accross this while searching:
- name: taskA
  register: resultA
  when: conditionA
- name: taskB
  register: resultB
  when: conditionB
- name: combine A and B variables
  set_fact:
      combined_result: "{{ resultA if  conditionA else resultB }}"

**Comment by jasonpaige** [comment]
This seems rather nasty. When faced with 20 registers for example, you end up with 20 different variables which you then combine in one way or another.

Seems very strange behaviour.

**Comment by extremeshok** [comment]
This needs a better solution.
name: 64
register: monit_release_download_file
when: ansible_userspace_bits == "64"

name: 32
register: monit_release_download_file
when: ansible_userspace_bits == "32"

monit_release_download_file will always be overwritten by the last task, even when it evaluates to false.

**Comment by aioue** [comment]
+1 is there a another way of dealing with this requirement? Something like

```
- shell: echo foo
  register:  registered_variable
      set_on_skipped_task: false
  when: false
```

(allow register module to accept a skip argument)

**Comment by thegalexc** [comment]
+1 - is there a reason this was closed, is there a resolution other than the `combined_result` method?

**Comment by davealbert** [comment]
+1 - This seems quite counter intuitive. Why was this closed?

**Comment by aioue** [comment]
would a patch for `set_when_task_skipped` on the register module be accepted, so the behaviour could be modified?

**Comment by leseb** [comment]
+1 such an unexpected behaviour :(
Registering different variable names is duplicating a lot of task in the end...

**Comment by guits** [comment]
+1 i think this is not the expected behaviour

**Comment by srgvg** [comment]
Hey everybody. This is really an old issue. Commenting on closed issues is rarely being picked up by the core developers. I'd like to encourage you to bring this topic on the mailing list, and possibly reopen a new ticket.

**Comment by leseb** [comment]
@srvg I understand your concern, but can't we simply re-open this issue?

**Comment by tszming** [comment]
As the original poster, feel free to copy my text and open as a new issue :)

**Comment by solomongifford** [comment]
I know this isnt the right place to discuss, but for anyone that reads this thread, I want to throw out that I dissagree with the proposal not to edit the registered value.  Any further tests against "changed" "failed" or similar will be indeterminate on which task is being tested.

set_fact (see my example above) is the right solution imo.  What would be nice is to allow set_fact to also be on another task in addition to it being its own task.

**Comment by srgvg** [comment]
@leseb "We" simply cannot reopen this ticket, only a core contributor can.

**Comment by ham-360** [comment]
A solution that worked for me was to wrap each task that should only update a variable if it executes inside a 'block' with the condition associated to the block rather than the task.  To use the first example...
```yaml
- block:
    - name: one
      command: /bin/echo one
      register: var2
  when: var1
  
- block:
    - name: two
      command: /bin/echo two
      register: var2
  when: not var1
```
