### ISSUE TITLE
elb_network_lb doesn't work correctly with subnet_mappings, preventing EIP support from working

### ISSUE THREAD

**Issue by briantist** [ansible/ansible#42977]
##### SUMMARY
The `elb_network_lb` module documentation shows support for using either `subnets` which is a list of subnets, or `subnet_mappings` which is a list of dicts containing a `SubnetId` key, and optionally an `AllocationId` key to specify an EIP to use for that subnet.

Trying to use subnet mappings on a new NLB fails saying that subnets is a required parameter.

If the NLB exists and is in the desired state, subnet mappings works, but if the mappings contain allocation IDs, they are ignored.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`lib/ansible/module_utils/aws/elbv2.py`

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

`DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15`

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
  - elb_network_lb:
      subnet_mappings:
        - SubnetId: subnet-1234abcd
          AllocationId: eipalloc-abcd1234
        - SubnetId: subnet-5678efab
          AllocationId: eipalloc-efab-5678
    delegate_to: localhost
```

##### EXPECTED RESULTS

Create or validate an NLB with EIPs attached

##### ACTUAL RESULTS

```
An error occurred (ValidationError) when calling the CreateLoadBalancer operation: At least one subnet must be specified
```
