### ISSUE TITLE
lambda_event module fails to create SQS based events

### ISSUE THREAD

**Issue by kylerisse** [ansible/ansible#42982]
##### SUMMARY

lambda_events module cannot properly create SQS based events due to incompatibility with starting_position source parameter.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lambda_event
##### ANSIBLE VERSION

2.5.4
```

```

##### STEPS TO REPRODUCE

```yaml
<these are the contents of bug_report.yml>
---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    ansible_python_interpreter: /usr/local/bin/python
    bucket: <omitted from bug report>
    key: <omitted from bug report>
    role: <omitted from bug report>
    handler: <omitted from bug report>
    aws_account: <omitted from bug report>

  tasks:
  - name: create SQS topic testme
    sqs_queue:
      name: testme
      region: us-west-2
      default_visibility_timeout: 30
      message_retention_period: 345600
      maximum_message_size: 256000
      delivery_delay: 0
      receive_message_wait_time: 0

  - name: create test lambdas
    lambda:
      name: testHandler
      region: us-west-2
      state: present
      s3_bucket: "{{ bucket }}"
      s3_key: "{{ key }}" 
      runtime: java8
      role: "{{ role }}"
      handler: "{{ handler }}"

  - name: create lambda sqs event mapping
    lambda_event:
      state: present
      region: us-west-2
      event_source: stream
      lambda_function_arn: testHandler
      source_params:
        source_arn: "arn:aws:sqs:us-west-2:{{ aws_account }}:testme"
        enabled: True
        batch_size: 1

```

##### EXPECTED RESULTS

create lambda sqs event mapping task to correctly create the lambda sqs mapping
##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "alias": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "ec2_url": null,
            "event_source": "stream",
            "lambda_function_arn": "arn:aws:lambda:us-west-2:<omitted from bug report>:function:testHandler",
            "profile": null,
            "region": "us-west-2",
            "security_token": null,
            "source_params": {
                "batch_size": 1,
                "enabled": true,
                "source_arn": "arn:aws:sqs:us-west-2:<omitted from bug report>:testme"
            },
            "state": "present",
            "validate_certs": true,
            "version": 0
        }
    },
    "msg": "Source parameter 'starting_position' is required for stream event notification."
}

```
ansible-playbook bug_report.yml -vvv
```
