### ISSUE TITLE
vmware_drs_rule_facts does not list VMs for vm-to-host type rules

### ISSUE THREAD

**Issue by seifer44** [ansible/ansible#42980]
##### SUMMARY
`vmware_drs_rule_facts` module does is only showing the `rule_vms` section for vm-to-vm type rules. This section is omitted with the vm-to-host type rules.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_drs_rule_facts

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /home/XXXXXXXX/tmp/ansible.cfg
  configured module search path = [u'/home/XXXXXXXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

```
[defaults]
host_key_checking=False
remote_tmp=/tmp
```

##### OS / ENVIRONMENT

RHEL 7.5

##### STEPS TO REPRODUCE

```yaml
---

- hosts: local
  gather_facts: false
  vars:
    vsphere:
      fqdn: xyz.example.com
      instance: xxx
      port: 443
      resource_pool: xxx
      network_name: "xyz_network"
      datacenter: "XXX Datacenter"
      cluster: "XXX Cluster"
    vsphere_username: 'admin_user'
    vsphere_password: 'xxxxx'
  tasks:
    - name: Discover existing DRS rules
      vmware_drs_rule_facts:
        hostname: "{{ vsphere.fqdn }}"
        port: "{{ vsphere.port }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        cluster_name: "{{ vsphere.cluster }}"
        validate_certs: no
      register: vmware_cluster
```

##### EXPECTED RESULTS

A listing of virtual machines under `rule_vms` for the `"rule_type": "vm_vm_rule"`

##### ACTUAL RESULTS

```
[XXXXXXXXX@xyz tmp]$ ansible-playbook -i temp.ini test.yml -vvv --step
ansible-playbook 2.6.0
  config file = /home/XXXXXXXXX/tmp/ansible.cfg
  configured module search path = [u'/home/XXXXXXXXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /home/XXXXXXXXX/tmp/ansible.cfg as config file
Parsed /home/XXXXXXXXX/tmp/temp.ini inventory source with ini plugin

PLAYBOOK: test.yml ***********************************************************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [local] *****************************************************************************************************************************************************************************************************************************
META: ran handlers
Perform task: TASK: Discover existing DRS rules (N)o/(y)es/(c)ontinue: y

Perform task: TASK: Discover existing DRS rules (N)o/(y)es/(c)ontinue: *******************************************************************************************************************************************************************

TASK [Discover existing DRS rules] *******************************************************************************************************************************************************************************************************
task path: /home/XXXXXXXXX/tmp/test.yml:50
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: XXXXXXXXX
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1531948306.66-69911848731356 `" && echo ansible-tmp-1531948306.66-69911848731356="` echo /tmp/ansible-tmp-1531948306.66-69911848731356 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_drs_rule_facts.py
<localhost> PUT /home/XXXXXXXXX/.ansible/tmp/ansible-local-22576brjVoG/tmpBRwpPf TO /tmp/ansible-tmp-1531948306.66-69911848731356/vmware_drs_rule_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1531948306.66-69911848731356/ /tmp/ansible-tmp-1531948306.66-69911848731356/vmware_drs_rule_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1531948306.66-69911848731356/vmware_drs_rule_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1531948306.66-69911848731356/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "drs_rule_facts": {
        "XXX Cluster": [
            {
                "rule_enabled": true,
                "rule_key": 1302,
                "rule_mandatory": null,
                "rule_name": "IdM Test Servers",
                "rule_type": "vm_vm_rule",
                "rule_uuid": "GUID-ID-GOES-HERE",
                "rule_vms": [
                    "idm02",
                    "idm01"
                ]
            },
            {
                "rule_affine_host_group_name": "Red_Hat_Licensing_Hosts",
                "rule_anti_affine_host_group_name": null,
                "rule_enabled": true,
                "rule_key": 1505,
                "rule_mandatory": false,
                "rule_name": "Red_Hat_Licensing",
                "rule_type": "vm_host_rule",
                "rule_uuid": "GUID-ID-GOES-HERE",
                "rule_vm_group_name": "Red_Hat_Licensing"
            }
        ]
    },
    "invocation": {
        "module_args": {
            "cluster_name": "XXX Cluster",
            "datacenter": null,
            "hostname": "xyz.example.com",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "username": "admin_user",
            "validate_certs": false
        }
    }
}
```
