### ISSUE TITLE
azure_rm_aks: support get_access_profile

### ISSUE THREAD

**Issue by yuwzho** [ansible/ansible#42987]
##### SUMMARY

Get the kubeconfig from AKS.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

azure_rm_aks

##### ANSIBLE VERSION

```
2.6.0
```

##### EXPECTED RESULTS

```yaml
- name: get kubeconfig
  azure_rm_aks:
      resource_group: foo
      name: bar
      get_access_file: yes
      isAdmin: yes
```
Download kubeconfig from aks with this play.

##### ACTUAL RESULTS

```

```
