### ISSUE TITLE
postgresql_ext has no (clear) parameter to specify a non-default unix_socket_dir

### ISSUE THREAD

**Issue by zswanson** [ansible/ansible#42988]
##### SUMMARY

The postgresql_ext module doesn't have a clear way to set the login_unix_socket; it can be done in an odd way, but there's no documentation on this. Using the 'as documented' configuration of the module, it will fail if the postgresql installation was configured to use a unix_socket_directory that is not located at /tmp/. 

##### ISSUE TYPE
 - Bug Report
 - Documentation

##### COMPONENT NAME

postgresql_ext
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### OS / ENVIRONMENT

CentOS 7.4

##### STEPS TO REPRODUCE

Assuming that postgres 9.x is installed and configured so that 'unix_socket_directories' is set to a location other than /tmp, the following task will fail with an error from psycopg2 stating that it cannot talk to the server. The python module is looking for the socket in /tmp and the ansible module provides no login_unix_socket like the other postgresql modules do.

```yaml
  - name: Enable postgis extension
    postgresql_ext:
      name: postgis
      db: '{{sde_db_name}}'
      state: present
      login_user: '{{postgresql_user}}'
```
A very old stackoverflow answer finally gave me the info on what's going on here.
https://stackoverflow.com/questions/5500332/cant-connect-the-postgresql-with-psycopg2

psycopg2 apparently defaults to using /tmp to look for the local unix socket; however it can accept a directory in it's 'host' connection parameter. Trying this out with the ansible, the following modifcation successfully works:

```yaml
  - name: Enable postgis extension
    postgresql_ext:
      name: postgis
      db: '{{sde_db_name}}'
      state: present
      login_user: '{{postgresql_user}}'
      login_host: '/var/run/postgres'
```

This is pretty confusing though because the documentation doesn't make any mention that this field can  be a filesystem path rather than a hostname, and it also differs wildly from the pattern of the other postgresql modules that all have a specific parameter for setting the login_unix_socket.

This could be resolved either by a parameter addition (my preference) of login_unix_socket that would override the login_host parameter if the remote host is the host of the targeted postgresql; or alternatively add this use-case to the documentation for the login_host param on postgresql_ext's module description, and include an example use.

##### EXPECTED RESULTS

Command executes succesfully
##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
fatal: [dbhost]: FAILED! => changed=false
  msg: |-
    unable to connect to database: could not connect to server: No such file or directory
            Is the server running locally and accepting
            connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
