### ISSUE TITLE
Request adding support for CD/DVD ROM attach to SATA controller

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#42995]
##### SUMMARY
Found that the created new VM, CD/DVD drive attach to the IDE controller, and this can not be configured to SATA controller. Most of our VMs deployed manually using SATA controller, we want to schedule our test in this case.  

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vmware/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
ide device in the module: vim.vm.device.VirtualIDEController()
sata device can be add to support: vim.vm.device.VirtualAHCIController()

```yaml
cdrom:
- type: iso
   attach_to: sata
   iso_file: [datastore1] install.iso
- type: iso
   attach_to: sata
   iso_file: [datastore1] test.iso
```

##### EXPECTED RESULTS
I want to through specify CD/DVD ROM controller type in the playbook to create a VM with CD/DVD ROM attaching to the specified controller, e.g. SATA.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@Tomorrow9 Thanks for reporting this issue. Could you please try this https://github.com/ansible/ansible/pull/39285 and let me know if it works for you ? 

Without patch vmware_guest adds all devices to IDE controller and if multiple disks and CD rom is attached. With patch it will add it SCSI controller.

needs_info

**Comment by Tomorrow9** [comment]
Hi,
Sorry for the late response. I tried apply this patch and created new VM with 1, 2, 3 disks, they are all set to SCSI controller (lsilogicsas), and CD/DVD ROM attach to IDE controller.
According to the result:
(1) thin/thick type can be set correctly.
(2) SCSI node set correctly.
(3) the 3rd disk datastore is not the specified one. (I assume there is another bug for this?)

Thanks.

**Comment by Tomorrow9** [comment]
Oh, as to above (3) multiple datastores of disks, I applied patch #33230, it works well now.
Here is my test playbook:
```yaml
- vars_files: 
    - ../67GA.yml
  hosts: 67vc
  gather_facts: no
  tasks:
  - name: Create a virtual machine on {{esxi_hostname}}
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: 6.7GA
      folder: ""
      name: test_auto_deploy_win10_64_efi
      state: poweredon
      guest_id: windows9_64Guest
      esxi_hostname: "{{ esxi_hostname }}"
      disk:
      - size_gb: 40
        type: thin
        datastore: datastore1
      - size_gb: 2
        type: thin
        datastore: datastore1
      - size_gb: 4
        type: thick
        datastore: datastore2
      hardware:
        version: 14
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: lsilogicsas
        boot_firmware: efi
      networks:
      - name: VM Network
        device_type: vmxnet3
        type: dhcp
      cdrom:
        type: client
    delegate_to: localhost
    register: deploy_vm
```
