### ISSUE TITLE
grafana_datasource - Failed to create prometheus datasource

### ISSUE THREAD

**Issue by liyaka** [ansible/ansible#42998]
##### SUMMARY
Failed to create prometheus datasource

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
grafana_datasource

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /data/jenkins/ttt/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/data/jenkins/ttt/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_PLUGIN_PATH(/data/jenkins/ttt/ansible.cfg) = [u'/data/jenkins/ttt/plugins']
DEFAULT_FORKS(/data/jenkins/ttt/ansible.cfg) = 50
DEFAULT_LOG_PATH(/data/jenkins/ttt/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/data/jenkins/ttt/ansible.cfg) = [u'/data/jenkins/ttt/roles']
DEFAULT_TIMEOUT(/data/jenkins/ttt/ansible.cfg) = 4
DEPRECATION_WARNINGS(/data/jenkins/ttt/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/data/jenkins/ttt/ansible.cfg) = False
HOST_KEY_CHECKING(/data/jenkins/ttt/ansible.cfg) = False
RETRY_FILES_ENABLED(/data/jenkins/ttt/ansible.cfg) = False
```
##### OS / ENVIRONMENT
Ubuntu 16.04

##### STEPS TO REPRODUCE
My call:
```
- name: Create prometheus datasource
  grafana_datasource:
    name: "Prometheus"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    ds_type: "prometheus"
    is_default: "yes"
    url: "http://prometheus:9090"
    state: present

```
**Creating datasource with the same parameter from UI works fine.**

##### EXPECTED RESULTS
Datasource is created

##### ACTUAL RESULTS
I get this error:
```
TASK [prometheus : Create prometheus datasource] *****************************************************************************************************************************************************************************************************************************
fatal: [vs-liyatest]: FAILED! => {"changed": false, "msg": "error <class '__main__.GrafanaAPIException'> : Unable to switch to organization 1 : {'url': 'http://localhost:3000/api/user/using/1', 'status': -1, 'msg': 'Connection failure: [Errno 104] Connection reset by peer'} "}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/grafana_datasource.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/grafana_datasource.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @seuf
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by seuf** [comment]
HI. The error message is about a connection problem : `Connection failure: [Errno 104] Connection reset by peer`.
Are you sure your grafana server is started and listening on localhost (not only the public ip) ?
Do you have iptables configured ?

**Comment by liyaka** [comment]
Same error running grafana_dashboard:
```
- name: Create list of dashboards files
  find:
    paths: "{{ prometheus_installation_path }}/grafana/dashboards/"
    patterns: "*.json"
  register: dashboards_list

- name: Import Grafana dashboards
  grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    state: present
    message: "Initial import"
    overwrite: "yes"
    path: "{{ item.path }}"
  with_items:
    - "{{ dashboards_list.files }}"
```
The error for each dashboard:
```
failed: [vs-liyatest] (item={u'uid': 1000, u'woth': False, u'mtime': 1531922447.9629328, u'inode': 259278, u'isgid': False, u'size': 30831, u'roth': True, u'isuid': False, u'isreg': True, u'pw_name': u'csr_admin', u'gid': 1000, u'ischr': False, u'wusr': True, u'xoth': True, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'csr_admin', u'path': u'/opt/csr/prometheus/grafana/dashboards/Postgres_Overview.json', u'xusr': True, u'atime': 1531922541.9672682, u'isdir': False, u'ctime': 1531922538.3912559, u'isblk': False, u'xgrp': True, u'dev': 2049, u'wgrp': False, u'isfifo': False, u'mode': u'0755', u'islnk': False}) => {"changed": false, "item": {"atime": 1531922541.9672682, "ctime": 1531922538.3912559, "dev": 2049, "gid": 1000, "gr_name": "csr_admin", "inode": 259278, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0755", "mtime": 1531922447.9629328, "nlink": 1, "path": "/opt/csr/prometheus/grafana/dashboards/Postgres_Overview.json", "pw_name": "csr_admin", "rgrp": true, "roth": true, "rusr": true, "size": 30831, "uid": 1000, "wgrp": false, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}, "msg": "error : Unable to switch to organization 1 : {'url': 'http://localhost:3000/api/user/using/1', 'status': -1, 'msg': 'Connection failure: [Errno 104] Connection reset by peer'}"}
```
**Unable to switch to organization 1**
