### ISSUE TITLE
Request for NVMe controller support

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#43000]
##### SUMMARY
From ESXi 6.5, NVMe controller is supported. We want to create new VM with disk controller set to NVMe.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vmware/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
ESXi 6.5 and later.

##### STEPS TO REPRODUCE
Add support "vim.vm.device.VirtualNVMEController()" virtual device for hardware version >= 13.
```yaml
      hardware:
        version: 13
        memory_mb: 4096
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: lsilogicsas
        nvme: true
      disk:
      - size_gb: 40
         type: thin
         controller: nvme
         datastore: datastore1
      - size_gb: 4
         type: thin
         controller: scsi
         datastore: datastore1
```

##### EXPECTED RESULTS
NVMe controller can be added in the hardware list, and disk in the list can specify attaching to which controller.

##### ACTUAL RESULTS
N/A
