### ISSUE TITLE
[rabbitmq_parameter] JSON value not parsed correctly

### ISSUE THREAD

**Issue by luca-drf** [ansible/ansible#43027]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

rabbitmq_parameter
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/radome/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/radome/homebrew/lib/python2.7/site-packages/ansible
  executable location = /Users/radome/homebrew/bin/ansible
  python version = 2.7.15 (default, Jun 18 2018, 12:10:34) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

Host: macOS 10.12.6
Target: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-130-generic x86_64)
RabbitMQ 3.7.6

##### STEPS TO REPRODUCE

```yaml
vars:
  shovels:
    - name: my_shovel
      vhost: /
      value: '{ "src-protocol": "amqp091", "src-uri": "amqp://user:pass@/", "src-queue": "my_src_queue", "src-prefetch-count": 10, "dest-protocol": "amqp091", "dest-uri": "amqp://user:pass@target/", "dest-queue": "my_dest_queue" }'
tasks:
  - name: create shovels
    rabbitmq_parameter:
      component: shovel
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      vhost: "{{ item.vhost }}"
    with_items: "{{ shovels }}"
```

##### EXPECTED RESULTS

Shovel created correctly

##### ACTUAL RESULTS

```
failed: [target_host] (item={u'vhost': u'/', u'name': u'my_shovel', u'value': u'{ "src-protocol": "amqp091", "src-uri": "amqp://user:pass@/", "src-queue": "my_src_queue", "src-prefetch-count": 10, "dest-protocol": "amqp091", "dest-uri": "amqp://user:pass@target/", "dest-queue": "my_dest_queue" }'}) => {
    "changed": false,
    "item": {
        "name": "my_shovel",
        "value": "{ \"src-protocol\": \"amqp091\", \"src-uri\": \"amqp://user:pass@/\", \"src-queue\": \"my_src_queue\", \"src-prefetch-count\": 10, \"dest-protocol\": \"amqp091\", \"dest-uri\": \"amqp://user:pass@target/\", \"dest-queue\": \"my_dest_queue\" }",
        "vhost": "/"
    },
...
    "module_stdout": 
"Traceback (most recent call last):
      File \"/tmp/ansible__NXJeX/ansible_module_rabbitmq_parameter.py\", line 155, in <module>
          main()
      File \"/tmp/ansible__NXJeX/ansible_module_rabbitmq_parameter.py\", line 128, in main
           value = json.loads(value)
      File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads
           return _default_decoder.decode(s)
      File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File \"/usr/lib/python2.7/json/decoder.py\", line 380, in raw_decode
            obj, end = self.scan_once(s, idx)
      ValueError: Expecting property name: line 1 column 2 (char 1)",
```

I suspect the problem lies in the fact that `value` gets somehow converted into a Python dictionary then to a string before it gets loaded by `json.loads`.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/messaging/rabbitmq_parameter.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/messaging/rabbitmq_parameter.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrishoffman @hyperized @manuel-sousa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/messaging/rabbitmq/rabbitmq_parameter.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/messaging/rabbitmq/rabbitmq_parameter.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pezzak** [comment]
It is because python (or ansible?) converts
{ "src-protocol": "amqp091", "src-uri": "amqp://user:pass@/", "src-queue": "my_src_queue", "src-prefetch-count": 10, "dest-protocol": "amqp091", "dest-uri": "amqp://user:pass@target/", "dest-queue": "my_dest_queue" }
to
{ 'src-protocol': 'amqp091', 'src-uri': 'amqp://user:pass@/', 'src-queue': 'my_src_queue', 'src-prefetch-count': 10, 'dest-protocol': 'amqp091', 'dest-uri': 'amqp://user:pass@target/', 'dest-queue': 'my_dest_queue' }
and it isn't valid json
for workaround you can add empty space at the beginning of the string:
value: ' { "src-protocol": "amqp091", "src-uri": "amqp://user:pass@/", "src-queue": "my_src_queue", "src-prefetch-count": 10, "dest-protocol": "amqp091", "dest-uri": "amqp://user:pass@target/", "dest-queue": "my_dest_queue" }'

**Comment by radome** [comment]
Thanks @pezzak! In the end I've fixed it as suggested in https://github.com/ansible/ansible/issues/59013#issuecomment-512569200

```yaml
vars:
  shovels:
    - name: my_shovel
      vhost: /
      parameters:
        src-protocol: amqp091
        src-uri: amqp://user:pass@/
        src-queue: my_src_queue
        src-prefetch-count: 10
        dest-protocol: amqp091
        dest-uri: amqp://user:pass@target/
        dest-queue: my_dest_queue
tasks:
  - name: create shovels
    rabbitmq_parameter:
      component: shovel
      name: "{{ item.name }}"
      value: "{{ item.parameters | to_json }}"
      vhost: "{{ item.vhost }}"
    with_items: "{{ shovels }}"
```
