### ISSUE TITLE
win_acl enumeration issues for InheritanceFlags

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#43049]
##### SUMMARY
When trying to use win_acl it will fail with an error that it cannot cast `$null` to `InheritanceFlags`. This most likely due to https://github.com/ansible/ansible/commit/f2acc97b843781c363f170099391f87535e459e2 but further investigation is needed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_acl

##### ANSIBLE VERSION
```
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Windows

##### STEPS TO REPRODUCE
My example that fails is

```
- win_acl:
    path: 'C:\tools\chocolatey.server'
    user: 'IIS_IUSRS'  # can be any user
    type: allow
    state: present
    rights: Read
```

##### EXPECTED RESULTS
Success

##### ACTUAL RESULTS

```
failed: [choco-server] (item=IIS_IUSRS) => {
    "changed": false,
    "item": "IIS_IUSRS",
    "msg": "an error occurred when attempting to present Read permission(s) on C:\\tools\\chocolatey.server for IIS_IUSRS - Cannot convert null to type \"System.Security.AccessControl.InheritanceFlags\" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are \"None,ContainerInherit,ObjectInherit\"."
}
```
