### ISSUE TITLE
with_items indirect variable reference: construct variable and fetch result

### ISSUE THREAD

**Issue by moocan** [ansible/ansible#43058]
##### SUMMARY
Impossible to construct variable and retrieve related indirect values as defined in imported var file for each item at each loop using with_item.

I don't find any relevant documentation about indirect variable manipulation or examples.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sysadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION
Nothing changed

##### OS / ENVIRONMENT
Ubuntu 17.10 & 18.04

##### STEPS TO REPRODUCE

roles/test/vars/{{ ansible_distribution|lower }}/apt-packages.yml
```yaml
  packages:
    required:
      - htop
      - aptitude

  package:
    htop:
      allow_unauthenticated: no
      autoclean: no
      autoremove: no
      cache_valid_time: 0
#    default_release:
      force: no
      force_apt_get: no
      install_recommends: yes
      only_upgrade: no
      purge: no 
      state: latest
      update_cache: yes
      upgrade: no
    aptitude:
      allow_unauthenticated: "no"
      autoclean: no
      autoremove: no
      cache_valid_time: 3600
#      default_release:
      force: no
      force_apt_get: no
      install_recommends: yes
      only_upgrade: no
      purge: no 
      state: latest
      update_cache: yes
      upgrade: no

```

roles/test/tasks/main.yml
```yaml
- name: "Register variable"
  include_vars:
    file: "vars/{{ ansible_distribution|lower }}/apt-packages.yml"
    name: apt_install

- name: "This a test"
  apt:
    name: "{{item}}"
    cache_valid_time: "{{ apt_install.package[item].cache_valid_time }}"
    state: "{{ apt_install.package[item].state }}"
    update_cache: "{{ apt_install.package[item].update_cache }}"
  with_items: "{{ apt_install.packages.required }}"
```

##### EXPECTED RESULTS

Retrieve related indirect values as defined in imported var file for each item at each loop.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: dict object has no element [u'htop', u'aptitude']\n\nThe error appears to have been in '/home/sysadmin/Documents/Ubuntu=Package=Template-v2/dev-ansible/roles/package/htop/tasks/apt-install.yml': line 37, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"{{ __tasks.header }} => [{{ __labels.tasks.step }}={{ step }}] {{ ansible_pkg_mgr|upper }} install ...\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}

```

**Comment by moocan** [comment]
Hello,

I apologize so much.

using a loop / loop_control instead of with_items, it is working as expected

```
- name: "This a test"
  apt:
    name: "{{item}}"
    cache_valid_time: "{{ apt_install.package[item].cache_valid_time }}"
    state: "{{ apt_install.package[item].state }}"
    update_cache: "{{ apt_install.package[item].update_cache }}"
  loop: "{{ apt_install.packages.required|flatten(levels=1) }}"
  loop_control:
    index_var: index
```
Documentation is not always easy to understand :(

Kind Regards
