### ISSUE TITLE
`no_log: {{varname}}` always results true if `when` clause refers undefined variable

### ISSUE THREAD

**Issue by fumiyas** [ansible/ansible#43064]
##### SUMMARY
`no_log: {{varname}}` always results true if `when` clause refers an undefined variable.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.6.1.post0 (stable-2.6 8c829778d1) last updated 2018/07/20 12:22:18 (GMT +900)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fumiyas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fumiyas/git/ansible/ansible/lib/ansible
  executable location = /home/fumiyas/git/ansible/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 05:55:50) [GCC 7.3.0]
```

##### STEPS TO REPRODUCE

```console
$ ansible-playbook playbook.yml
```

`playbook.yml`:

```yaml
- hosts: localhost
  tasks:
    - set_fact:
        no_log_flag: false
    - debug:
        var: no_log_flag
    - name: "Command 1 (OK)"
      command: "true"
      no_log: "{{no_log_flag}}"
    - name: "Command 2 (NG with 'undefined_var' is undefined error)"
      command: "true"
      no_log: "{{no_log_flag}}"
      when: undefined_var == true

```

##### EXPECTED RESULTS

```
...
TASK [debug] ***************************************************************************************
ok: [localhost] => {
    "no_log_flag": false
}

TASK [Command 1 (OK)] ******************************************************************************
changed: [localhost]

TASK [Command 2 (NG with 'undefined_var' is undefined error)] **************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'undefined_var == true' failed. The error was: error while evaluating conditional (undefined_var == true): 'undefined_var' is undefined\n\nThe error appears to have been in '/home/alice/ansible-harness/inventory/staging/d/playbook.yml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      no_log: \"{{no_log_flag}}\"\n    - name: \"Command 2 (NG with 'undefined_var' is undefined error)\"\n      ^ here\n"}
```

##### ACTUAL RESULTS

```
...
TASK [Command 1 (OK)] ******************************************************************************
changed: [localhost]

TASK [Command 2 (NG with 'undefined_var' is undefined error)] **************************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```
