### ISSUE TITLE
nxos_logging not idempotent

### ISSUE THREAD

**Issue by dmurarasu** [ansible/ansible#43072]
##### SUMMARY

nxos_logging is not idempotent for "monitor level 5" and "console level 2". It seems to work for other levels just not these ones which are the device defaults.

Another issue is if you try to set console level 3-7, ansible returns changed but the command actually fails on the device. If you'd enter the command on the CLI the following error is returned: "Baud rate of console should be 38400 to increase severity level." 
So when trying to set the console level between 3-7 the module should first check that under "line console" speed is configured to be higher or equal to 38400.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_logging

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

Ansible Server: CentOS Linux release 7.5.1804
Device: N9K running NXOS: version 7.0(3)I6(1)

##### STEPS TO REPRODUCE

```yaml
- name: configure device
  hosts: sw
  connection: network_cli
  tasks:
    - nxos_logging:
        state: present
        dest: monitor
        dest_level: 5
    - nxos_logging:
        state: present
        dest: console
        dest_level: 2
```

##### EXPECTED RESULTS

ok: [192.168.16.3] => {"changed": false, "commands": []}

##### ACTUAL RESULTS

changed: [192.168.16.3] => {"changed": true, "commands": ["logging monitor 5"]}
changed: [192.168.16.3] => {"changed": true, "commands": ["logging console 2"]}

```

```
