### ISSUE TITLE
nxos_ospf_vrf - auto-cost not idempotent and check mode not supported

### ISSUE THREAD

**Issue by dmurarasu** [ansible/ansible#43081]
##### SUMMARY

auto_cost parameter is not idempotent.

module does not support check mode.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

Ansible Server: CentOS Linux release 7.5.1804
Device: N9K running NXOS: version 7.0(3)I6(1)

##### STEPS TO REPRODUCE

```yaml
---
- name: configure device
  hosts: sw
  connection: network_cli
  tasks:
    - nxos_ospf_vrf:
        auto_cost: 100000
        state: present
        ospf: ospf_test
        vrf: test

```

##### EXPECTED RESULTS

on second run:
TASK [nxos_ospf_vrf] ***************************************************************************************************************************************************************************
ok: [192.168.16.3] => {"changed": false, "commands": []}

##### ACTUAL RESULTS

on second run:
TASK [nxos_ospf_vrf] ***************************************************************************************************************************************************************************
changed: [192.168.16.3] => {"changed": true, "commands": ["router ospf ospf_test", "auto-cost reference-bandwidth 100 Gbps"]}

```

```
