### ISSUE TITLE
service action plugin and set_fact do not play together as documented

### ISSUE THREAD

**Issue by betelgeuse** [ansible/ansible#43083]
##### SUMMARY
The service action plugin has the following code for automatic lookup:

https://github.com/ansible/ansible/blob/cadbd6ea9ccb7ad047dd717509598e3c551667e0/lib/ansible/plugins/action/service.py#L49

This does not allow intuitive override with the set_facts task.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

!component =lib/ansible/plugins/action/service.py

##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### CONFIGURATION

ANSIBLE_PIPELINING=true

##### OS / ENVIRONMENT

N/A, Linux

##### STEPS TO REPRODUCE

```yaml
- name: 'debug before'
  debug:
    msg:
      - "service_mgr: {{ lookup('vars', 'service_mgr', default='undefined') }}"
      - "ansible_service_mgr: {{ansible_service_mgr}}"
      - "ansible_facts.service_mgr: {{ansible_facts.service_mgr}}"
- name: set ansible_service_mgr
  set_fact:
    ansible_service_mgr: 'somethingelse'
- debug:
    msg:
      - "service_mgr: {{ lookup('vars', 'service_mgr', default='undefined') }}"
      - "ansible_service_mgr: {{ansible_service_mgr}}"
      - "ansible_facts.service_mgr: {{ansible_facts.service_mgr}}"
- name: set service_mgr
  set_fact:
    service_mgr: 'somethingelse'
- debug:
    msg:
      - "service_mgr: {{ lookup('vars', 'service_mgr', default='undefined') }}"
      - "ansible_service_mgr: {{ansible_service_mgr}}"
      - "ansible_facts.service_mgr: {{ansible_facts.service_mgr}}"
- name: set ansible_facts.service_mgr
  set_fact:
    ansible_facts:
      service_mgr: 'somethingelse'
- debug:
    msg:
      - "service_mgr: {{ lookup('vars', 'service_mgr', default='undefined') }}"
      - "ansible_service_mgr: {{ansible_service_mgr}}"
      - "ansible_facts.service_mgr: {{ansible_facts.service_mgr}}"
```

##### EXPECTED RESULTS

The documentation for the task says in the use argument:
```
The service module actually uses system specific modules, normally through auto detection, this setting can force a specific module.
Normally it uses the value of the 'ansible_service_mgr' fact and falls back to the old 'service' module when none matching is found.
```

set_fact on ansible_service_mgr should change how the plugin behaves.

##### ACTUAL RESULTS

```
TASK [sshd_chroot : debug before] ***********************************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:32
ok: [ip] => {
    "msg": [
        "service_mgr: undefined", 
        "ansible_service_mgr: systemd", 
        "ansible_facts.service_mgr: systemd"
    ]
}

TASK [sshd_chroot : set ansible_service_mgr] ************************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:38
ok: [ip] => {"ansible_facts": {"ansible_service_mgr": "somethingelse"}, "changed": false}

TASK [sshd_chroot : debug] ******************************************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:41
ok: [ip] => {
    "msg": [
        "service_mgr: undefined", 
        "ansible_service_mgr: somethingelse", 
        "ansible_facts.service_mgr: systemd"
    ]
}

TASK [sshd_chroot : set service_mgr] ********************************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:46
ok: [ip] => {"ansible_facts": {"service_mgr": "somethingelse"}, "changed": false}

TASK [sshd_chroot : debug] ******************************************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:49
ok: [ip] => {
    "msg": [
        "service_mgr: somethingelse", 
        "ansible_service_mgr: somethingelse", 
        "ansible_facts.service_mgr: systemd"
    ]
}

TASK [sshd_chroot : set ansible_facts.service_mgr] ******************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:54
ok: [ip] => {"ansible_facts": {"ansible_facts": {"service_mgr": "somethingelse"}}, "changed": false}

TASK [sshd_chroot : debug] ******************************************************************************************************************************************************************************************************************************
task path: roles/sshd_chroot/tasks/main.yml:58
ok: [ip] => {
    "msg": [
        "service_mgr: somethingelse", 
        "ansible_service_mgr: somethingelse", 
        "ansible_facts.service_mgr: somethingelse"
    ]
}
```
