### ISSUE TITLE
VMware: vmware_guest returning to early

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#43082]
##### SUMMARY

The VMware module fails to wait for all guest customization's to complete before returning control to ansible e.g. ansible continues to process the playbook before the vm deployment has fully finished.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/user/Git/Create_Infrastrukture_Windows/plays/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 13:11:40) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/user/Git/testProject/plays/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/Git/testProject/plays/ansible.cfg) = -o ForwardAgent=no
COMMAND_WARNINGS(/home/user/Git/testProject/plays/ansible.cfg) = True
DEFAULT_BECOME(/home/user/Git/testProject/plays/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(/home/user/Git/testProject/plays/ansible.cfg) = True
DEFAULT_FORKS(/home/user/Git/testProject/plays/ansible.cfg) = 50
DEFAULT_MANAGED_STR(/home/user/Git/testProject/plays/ansible.cfg) = This file is managed by ansible - local changes will be lost
DEFAULT_REMOTE_USER(/home/user/Git/testProject/plays/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/user/Git/testProject/plays/ansible.cfg) = ['/home/user/Git/testProject/roles/internal', '/home/user/Git/testProject/roles/external']
DEFAULT_TRANSPORT(/home/user/Git/testProject/plays/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/home/user/Git/testProject/plays/ansible.cfg) = /home/user/Git/testProject/.vpass
DEPRECATION_WARNINGS(/home/user/Git/testProject/plays/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/user/Git/testProject/plays/ansible.cfg) = True
SYSTEM_WARNINGS(/home/user/Git/testProject/plays/ansible.cfg) = True
```

##### OS / ENVIRONMENT

ArchLinux

##### STEPS TO REPRODUCE

```yaml
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template using the vmware_guest module
- name: VM from template
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: vcenter.example.com
    esxhost: esxi01.example.com
    datastore: devDatastore
    network: Customer001
    vmtemplate: Win Server 2016 Template GUI (german)
    vmcluster: myCluster
    notes: Created by Ansible
    dumpfacts: False
    vcdatacenter: myDatacenter
    vmfolder: /myVMs
    vmname: DEV-TTTTTTTTTTT
    vcenter_user: myUser
    vcenter_pass: myPassword
  tasks:
      
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: "{{ vcdatacenter }}"
        name: "{{ vmname }}"
        guest_id: windows9Server64Guest
        template: "{{ vmtemplate }}"
        folder: "{{ vmfolder }}"
        disk:
          - size_gb: 80
            type: thin
            datastore: "{{ datastore }}"
        networks:
          - device_type: vmxnet3
            name: "{{ network }}"
            start_connected: True
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        customization:
          autologon: yes
          dns_servers:
          - 1.1.1.1
          - 9.9.9.9
          password: newPa$$w0rd
          runonce:
          - powershell.exe -ExecutionPolicy ByPass -Command "New-Item -Path C:\testfile.txt"
        state: poweredon
      register: newvm
      
    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ vmname }}"
```

##### EXPECTED RESULTS

The vmware_guest task should only continue after the vm is fully provisioned (all customizations are applied, sysprep is performed and the vm performed it's final reboot).

##### ACTUAL RESULTS

The task finishes just after the template is copied into a new vm and started. It does not wait until vmware set the specified password.
The image in question is a Windows Server 2016 one with installed vmware guest tools. There are no network routes from the deployment host to the final vm. The deployment host is only able to talk to the esxi and vcenter servers.

There is also another bug, the vmware_guest module is not idempotent, if run twike just right after the first invokation finished, it still is listed as "changed: True"

@Akasurde Has the corresponding logfile, as I don't want to disclose it publicly.
