### ISSUE TITLE
[rabbitmq_binding] Bindings gets created with empty source and destination as routing key

### ISSUE THREAD

**Issue by luca-drf** [ansible/ansible#43085]
##### SUMMARY

The binding gets created but the source results empty and the destination is used also as routing key.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

rabbitmq_binding

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/radome/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/radome/homebrew/lib/python2.7/site-packages/ansible
  executable location = /Users/radome/homebrew/bin/ansible
  python version = 2.7.15 (default, Jun 18 2018, 12:10:34) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

Host: macOS 10.12.6
Target: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-130-generic x86_64)
RabbitMQ 3.7.6

##### STEPS TO REPRODUCE

```yaml
vars:
  bindings:
    - src: my_exchange
      dest: my_queue
      dest_type: queue
      routing_key: '#'
      vhost: test
      login_user: test
      login_password: test
    - src: my_exchange
      dest: my_other_queue
      dest_type: queue
      routing_key: '#'
      vhost: test
      login_user: test
      login_password: test

tasks:
  - name: create bindings
    rabbitmq_binding:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      dest_type: "{{ item.dest_type }}"
      routing_key: "{{ item.routing_key }}"
      vhost: "{{ item.vhost }}"
      login_user: "{{ item.login_user }}"
      login_password: "{{ item.login_password }}"
    with_items: "{{ bindings }}"
```

##### EXPECTED RESULTS

Bindings gets created correctly

##### ACTUAL RESULTS

The bindings gets created but with wrong parameters

This is the plugin result:
```
ok: [target] => (item={u'src': u'my_exchange', u'dest': u'my_queue', u'login_user': u'test', u'routing_key': u'#', u'vhost': u'test', u'login_password': u'test', u'dest_type': u'queue'})
ok: [target] => (item={u'src': u'my_exchange', u'dest': u'my_other_queue', u'login_user': u'test', u'routing_key': u'#', u'vhost': u'test', u'login_password': u'test', u'dest_type': u'queue'})
```

But on the target actually:

```
radome@target:~$ sudo rabbitmqctl list_bindings -p test source_name source_kind destination_name destination_kind routing_key
Listing bindings for vhost test...
	exchange	my_other_queue	queue	my_other_queue
	exchange	my_queue	queue	my_queue
```

Note that the source is empty and the destination name is used for both the destination queue and the routing key.
