### ISSUE TITLE
Add support of workspaces in terraform module

### ISSUE THREAD

**Issue by rrey** [ansible/ansible#43134]
##### SUMMARY

From Terraform documentation: 
```
Certain backends support multiple named workspaces, allowing multiple states to be associated with a single configuration.
```

The module currently does not support the notion of workspace. Adding it would be helpful.
The default workspace would be "default" and would not break the current usage of the module.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
terraform

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /Users/remirey/dev/grtgas/avignon/ansible.cfg
  configured module search path = [u'/Users/remirey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/remirey/.virtualenvs/avignon/lib/python2.7/site-packages/ansible
  executable location = /Users/remirey/.virtualenvs/avignon/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
# Basic deploy of a service with workspace
- terraform:
    project_path: '{{ project_dir }}'
    state: present
    workspace: staging
```
