### ISSUE TITLE
maven_artifact checksum error when downloading from archiva repository

### ISSUE THREAD

**Issue by bonzi316** [ansible/ansible#43149]
##### SUMMARY
When we use maven_artifact to download from an archiva repository the md5sum always fail.  The issue is when it check for the md5 the .md5 generated by archiva does not only contail the md5, but the md5 and the filename.  So when the module check the computed md5 of the local file it compare the localmd5 with a string composed "md5  <filename>".  Since ansible 2.6 in order to workaround this issue we add the `verify_checksum: always` which is very bad.  This was not the case in version 2.5.x.   This behavior start with ansible 2.6.0.  

I've also tested with the maven_artifact.py from the devel branch and I was having the same behavior.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

maven_artifact

##### ANSIBLE VERSION

```
2.6.1
```

##### CONFIGURATION

Default install from EPEL

##### OS / ENVIRONMENT

CentOS 7.5
CentOS 6.x

##### STEPS TO REPRODUCE

```yaml
- name: Download Maven artifact
  maven_artifact:
    artifact_id: mymodule
    dest: "/tmp/mymodule/"
    group_id: com/ciename/module
    state: present
    version: "latest"
    extension: jar
    repository_url: "http://archiva.corp.net/archiva/repository/internal/"
    verify_checksum: always
  environment:
    no_proxy: "localhost,127.0.0.1,.corp.net"
```

##### EXPECTED RESULTS

I'm expecting to have a valid md5sum 

##### ACTUAL RESULTS

Actually the content of remote_md5 is the whole content of the md5 file downloaded from archiva and the remote_url should

```
TASK [myrole: Download Maven MyModule jar] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Cannot retrieve the artifact to destination: Checksum does not match: we computed c3a749e2c090e6ef6b99c2b3268ace5bbut the repository states c3a749e2c090e6ef6b99c2b3268ace5b  my-module-1.0.0.war"}
```
