### ISSUE TITLE
file - unable to modify hard links

### ISSUE THREAD

**Issue by rndmh3ro** [ansible/ansible#43166]
##### SUMMARY
When running the `file`-module without `state` on hardlinks, it will fail.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

file

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /tmp/kitchen/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_MANAGED_STR(/tmp/kitchen/ansible.cfg) = Ansible managed: {file} modified by {uid} on {host}
DEFAULT_ROLES_PATH(/tmp/kitchen/ansible.cfg) = [u'/tmp']
DEFAULT_SCP_IF_SSH(/tmp/kitchen/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### STEPS TO REPRODUCE

This does not work:
```yaml
---
- hosts: localhost
  tasks:
    - name: create file
      file:
        dest: "/tmp/file"
        state: touch
        mode: "0777"

    - name: create hardlink
      shell: "ln /tmp/file /tmp/hardlink"

    - name: change hardlink
      file:
        path: "/tmp/hardlink"
        mode: "go-w"

```

This does work:
```yaml
---
- hosts: localhost
  tasks:
    - name: create file
      file:
        dest: "/tmp/file"
        state: touch
        mode: "0777"

    - name: create hardlink
      shell: "ln /tmp/file /tmp/hardlink"

    - name: change hardlink
      file:
        path: "/tmp/hardlink"
        mode: "go-w"
        state: file                    # that is changed

```

##### EXPECTED RESULTS
Both commands should execute sucessfully.

##### ACTUAL RESULTS

```ansible-playbook -i hosts default.yml 

PLAY [localhost] *****************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [create file] ***************************************************************************************************************************************************************************
changed: [localhost]

TASK [create hardlink] ***********************************************************************************************************************************************************************

changed: [localhost]

TASK [change hardlink] ***********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "src must be an absolute path"}


PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1   

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rndmh3ro** [comment]
Still happens with 2.9.1.

**Comment by Shrews** [comment]
With current devel (`core 2.12.0.dev0`), this error occurs with the reproducer playbook:

```
TASK [change hardlink] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "src is required for creating new hardlinks"}
```

The `file` module detects you are attempt to modify an existing hard link, effectively setting `state: hard` for you. Adding `src` to point to the original file would produce a new error about the hard link already existing. In short, modifying hard links is not directly supported by `file`, only creation of them. You should instead modify the source file, `/tmp/file` in this example, since the change would be applied to the hard link automatically.

**Comment by Shrews** [comment]
Ugh, so, for my test, it wasn't `file` that was actually failing, it was the `ln /tmp/file /tmp/hardlink` line when running the playbook more than once. The following playbook works as expected for a single run:

```
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: create file
      file:
        dest: "/tmp/file"
        state: touch
        mode: "0777"

    - name: create hardlink
      shell: "ln /tmp/file /tmp/hardlink"

    - name: change hardlink
      file:
        path: "/tmp/hardlink"
        mode: "go-w"
        src: "/tmp/file"
```

Sorry for the unnecessary noise. Closing yet again.... and grabbing some caffeine.
