### ISSUE TITLE
docker_container binds to 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by LucidOne** [ansible/ansible#43177]
##### SUMMARY

docker_container binds to 0.0.0.0 instead of localhost

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible-playbook 2.6.1
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.5/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

```yaml
- name: "Start Docker Registry Server"
  docker_container:
    name: "registry"
    recreate: yes
    image: registry:2
    ports:
      - "localhost:5000:5000"
      - "localhost:5001:5001"
    restart: yes
    restart_policy: "always"
```

##### EXPECTED RESULTS
registry container should be bound to localhost

##### ACTUAL RESULTS

`ps -ef` shows registry container bound to 0.0.0.0 and `nc` confirms this.

```
root      3720  2147  0 23:20 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5001 -contain
root      3734  2147  0 23:20 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5000 -contain
```

##### WHAT WORKS
This configuration correctly binds to localhost
```yaml
- name: "Start Docker Registry Server"
  docker_container:
    name: "registry"
    recreate: yes
    image: registry:2
    init: yes
    network_mode: "bridge"
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
    restart: yes
    restart_policy: "always"
```

```
root      4914  2147  0 23:25 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 5001 -conta
root      4927  2147  0 23:25 ?        00:00:00 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 5000 -conta
```
