### ISSUE TITLE
echo in playbooks

### ISSUE THREAD

**Issue by cleonte** [ansible/ansible#4317]
Hi Guys,

i found this on the mailing list

https://groups.google.com/d/msg/ansible-project/JoOGuDsSKgs/TJygI-cCd5gJ 
do you know if its fixed?

I'm trying to run this playbook

```
  ---
  - hosts: g2
    user: root
    gather_facts: no
    tasks:
    - shell: echo 'test'
```

and i don't get the output of echo command, if i run only via ansible  with

```
ansible -i g2.inv g2 -m shell -a 'echo test' -u root
```

i see the output

I'm using ansible 1.3.2

Cheers,
