### ISSUE TITLE
VMware: vmware_host_facts not gathering all data

### ISSUE THREAD

**Issue by DrMxxxxx** [ansible/ansible#43187]
##### SUMMARY

The Module vmware_host_facts is not gathering all data from a vCenter Server. Only from one server the data is pulled.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_host_facts

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

##### OS / ENVIRONMENT

Debian 4.9.51-1 (2017-09-28) x86_64

##### STEPS TO REPRODUCE

```
I created a playbook as it is described in the example.

- name: Gather vmware host facts
    vmware_host_facts:
      validate_certs: no
      hostname: ip
      username: username
      password: password
    register: host_facts
    delegate_to: localhost
```

##### EXPECTED RESULTS

A list of all vmware hosts with the facts of the host. This vCenter has about 30 hosts.

##### ACTUAL RESULTS

The facts are only pulled from one host.

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_host_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9 @woshihaoren
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi DrMxxxxx,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@DrMxxxxx Thanks for reporting this issue. Currently, it returns the first ESXi hostsystem which it finds from given vCenter - see here [docs](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_facts.py#L23)
As workaround, you can use `with_items` and iterate over all ESXi system from given vCenter.

```yaml
       - name: Gather vmware host facts
          vmware_host_facts:
             hostname: "{{ item.esxi_hostname }}"
             username: "{{ item.esxi_user }}"
             password: "{{ item.esxi_pass }}"
             validate_certs: no
          register: host_facts
          delegate_to: localhost
          with_items:
             - {esxi_hostname: hostname_1, esxi_user: username_host_1, esxi_pass: pass_host_1}
             - {esxi_hostname: hostname_2, esxi_user: username_host_2, esxi_pass: pass_host_2}

```
@woshihaoren What do you think ?
