### ISSUE TITLE
Customize option in vmware_guest module doesn't work for FreeBSD

### ISSUE THREAD

**Issue by karthik120** [ansible/ansible#43189]
##### SUMMARY

When I attempt to clone a FreeBSD 10.1 VM (openvm tools already installed in it) to new one e.x cloning B from A where A being source and B being the destination. The play ends with the error 
**Customize option in vmware_guest module doesn't work for FreeBSD** . However, new VM B is created. When you turn on the machine B, you would notice the IP address and hostname of the source A in it instead of the one that I set using customize option in vmware_guest. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/builders/ansible_scripts/ansible.cfg
  configured module search path = [u'/home/builders/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_FORKS(/home/builders/ansible_scripts/ansible.cfg) = 25
DEFAULT_GATHERING(/home/builders/ansible_scripts/ansible.cfg) = explicit
DEFAULT_MODULE_NAME(/home/builders/ansible_scripts/ansible.cfg) = shell

##### OS / ENVIRONMENT

CentOS 7.2

##### STEPS TO REPRODUCE

1. Have a source VM as FreeBSD 10.1 with OpenVm tools installed 
2. Run the playbook with the hosts as localhost 

```yaml
---
- name: Clone VM from one to another
  vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ validate_certs }}'
    name: '{{ vm_name }}'
    state: '{{ state }}'
    template: '{{ vm_template }}'
    datacenter: '{{ cluster_name }}'
    folder: '{{ folder_name }}'
    cluster: '{{ cluster }}'
    hardware:
      memory_mb: '{{ ram }}'
      num_cpus: '{{ cpu }}'
      scsi: '{{ scsi }}'
    customization:
      hostname: '{{ vm_name }}'
    networks:
    - name: VM-NETWORK
      ip: '{{ ip_address }}'
      netmask: '{{ netmask }}'
      gateway: '{{ gateway }}'
      type: '{{ type }}'
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy
```

##### EXPECTED RESULTS

New VM gets created with the hostname provided in the customize section

##### ACTUAL RESULTS

New VM is created with the hostname and IP address of the Source VM instead of a new name provided in customization section. Also, the play ends in the error with the message below
**Customize option in vmware_guest module doesn't work for FreeBSD**

```

```
