### ISSUE TITLE
azure_rm_virtualmachine new feature request (Custom Name for Managed Disks)

### ISSUE THREAD

**Issue by rdtechie** [ansible/ansible#43195]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A, out-of-the-box experience.
##### OS / ENVIRONMENT

Running Ansible on Ubuntu Server 16.04 LTS, managing Windows/Linux VMs in Azure
##### STEPS TO REPRODUCE

When creating a new vm, if using the parameter **managed_disk_type** or the parameter section **data_disks**, new managed disk(s) will be created for the Operating System or Data disks. Currently I don't see an option to give these disks a custom name. Especially for environments where strict naming conventions are being used, this is a problem. It would be really useful to have an specific parameter available. This is the code that I'm currently using:

```yaml
- name: Ensure Virtual Machine Exists
  azure_rm_virtualmachine:
    resource_group: rg1
    name: vm1
    vm_size: Standard_DS3_v2
    managed_disk_type: Standard_LRS
    admin_username: vmadmin
    admin_password: fakepassword
    image:
     offer: RHEL
     publisher: RedHat
     sku: 7-RAW
     version: latest
    network_interfaces: nic01
    data_disks:
      - lun: 0
        disk_size_gb: 64
        managed_disk_type: Standard_LRS
      - lun: 1
        disk_size_gb: 128
        managed_disk_type: Premium_LRS
```

##### EXPECTED RESULTS

I would like to see it implemented as something like this:
```yaml
- name: Ensure Virtual Machine Exists
  azure_rm_virtualmachine:
    resource_group: rg1
    name: vm1
    vm_size: Standard_DS3_v2
    managed_disk_type: Standard_LRS
    managed_os_disk_name: vm1-os-disk
    admin_username: vmadmin
    admin_password: fakepassword
    image:
     offer: RHEL
     publisher: RedHat
     sku: 7-RAW
     version: latest
    network_interfaces: nic01
    data_disks:
      - lun: 0
        disk_size_gb: 64
        managed_disk_type: Standard_LRS
        managed_data_disk_name: vm1-data-01
      - lun: 1
        disk_size_gb: 128
        managed_disk_type: Premium_LRS
        managed_data_disk_name: vm1-data-02
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi rdtechie,

Thank you for the issue, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in #ansible-azure on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
Hi @rdtechie , Every VM only allowed to be attached on of data disk, so you need to set on disk on this VM. As you said, it need to add a way to set the data disk name( because it always named by vm_name-datadisk-0) , Thanks!

**Comment by yuwzho** [comment]
@rdtechie When creating a VM, we recommend using the simplest configuration to configure the VM. That means, if you want to have more complicate configuration for the sub-resources, you can use other resource modules to do the management. For your scenario, you can use [`azure_rm_managed_disk`](https://docs.ansible.com/ansible/latest/modules/azure_rm_managed_disk_module.html) to create some data disks, then attach them to VM. You plakbook can be written as this:

```yaml
- name: Ensure Virtual Machine Exists
  azure_rm_virtualmachine:
    resource_group: rg1
    name: vm1
    vm_size: Standard_DS3_v2
    managed_disk_type: Standard_LRS
    managed_os_disk_name: vm1-os-disk
    admin_username: vmadmin
    admin_password: fakepassword
    image:
     offer: RHEL
     publisher: RedHat
     sku: 7-RAW
     version: latest
    network_interfaces: nic01

- name: create disk
  azure_rm_managed_disk:
        disk_size_gb: 64
        resource_group: rg1
        name: "{{ item }}"
        managed_by: vm1
  with_items:
  - my_disk_1
  - my_disk_2
```
