### ISSUE TITLE
mysql_user to set root password not working right after install

### ISSUE THREAD

**Issue by antonioribeiro** [ansible/ansible#4320]
Distribution version: Ubuntu 12.04

I tried it many times doing this, to completely purge mysq-server:

```
sudo apt-get --yes --purge remove mysql-server mysql-common mysql-client
```

And then installing via ansible:

```
- name: MySQL | Install server
  action: apt pkg=$item state=installed
  with_items:
    - mysql-server
  register: last_result
  tags: mysql

- name: MySQL | Install client and libs
  action: apt pkg=$item state=installed
  with_items:
    - mysql-client
    - python-mysqldb
    - php5-mysql
  tags: mysql
```

If after the install action I added:

```
- name: update mysql root password for all root accounts
  mysql_user: name=root host=$item password=$mysql_root_password
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
```

And I got a bunch of errors like this

```
failed: [172.17.0.120] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
```

And trying to connect to mysql using my password fails:

```
mysql -u root -p
```

And if I try to set root password, using:

```
sudo mysqladmin -u root password password
```

mysqladmin says access is denied:

```
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
```

But in the very you run this, after installing MySQL, you shouldn't need a root password, because there is no password yet.

To fix it I had to add those actions BEFORE the install action:

```
- name: MySQL | Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password $mysql_root_password | sudo /usr/bin/debconf-set-selections
  tags: mysql

- name: MySQL | Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password_again password $mysql_root_password | sudo /usr/bin/debconf-set-selections
  tags: mysql
```

And now everything is fine.

Looks like the unnatended mysql install on Debian based distros (DEBIAN_FRONTEND=noninteractive ?) is answering to apt questions and setting a wrong password to root user.

**Comment by jimi-c** [comment]
This doesn't seem to be an ansible issue then, does it? If the password is non-blank for root after an install, you'll either need to set the login_user/password or reset the configuration as you did above.

**Comment by antonioribeiro** [comment]
If I just apt install mysql-server, I should, at least, to be able to use mysqladmin to set the root password:

```
sudo mysqladmin -u root password password
```

But it gives me this error:

```
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
```

If, in the very first time after mysql-server install you do that, you don't have to have a password, because there is no password yet. So ansible is somehow setting a password for root on install.

**Comment by mpdehaan** [comment]
This seems to be an issue of the mysql modules needing better docs.

Changing this to a docs ticket.

**Comment by drcongo** [comment]
Can you confirm that Ansible is actually setting a password for root on install? If so, what is it? I can't find any mention of this in the documentation and it strikes me as very unexpected behaviour, as @antonioribeiro mentioned the behaviour we're seeing in Ansible doesn't match the behaviour of a manual install.

**Comment by mpdehaan** [comment]
So to clarify, ansible didn't install mysql, the package manager did.   It is not setting an initial password.

So I don't see why it should be expected to set a password.

In most cases people handle this my installing a my.cnf.

**Comment by antonioribeiro** [comment]
The problem is that the package manager will ask for a password while installing interactively. But ansible git module does it noninteractively and, somehow, it is giving some answers to those questions, bad ones, wich makes package manager set something (blank? null?) as a password.

But if we previously give the right ones:

```
echo mysql-server mysql-server/root_password password $mysql_root_password | sudo /usr/bin/debconf-set-selections
```

It works.

**Comment by drcongo** [comment]
Thanks for the explanation Antonio.

**Comment by cedjar** [comment]
Hello all ,

I got the same issue but i'm on centos 6.5 and i'm trying to install / configure mysql55

the ansible module seems not corrected for this, i tried with an .my.cnf (without result) and debconf-set-selections doesnt' exist on centos :) 

Maybe someone have the solution ? thanks 

Here is my code : 
- name: should provide .my.cnf file
  sudo: true
  template: src=secret_my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
- name: should provide my.cnf file
  sudo: true
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysqld
- name: start mysqld service
  sudo: true
  service: name=mysqld state=started enabled=yes
- name: MySQL-python must be installed
  yum: name=MySQL-python state=present
  sudo: true
- name: update mysql root password for all root accounts
  sudo: true
  mysql_user:
    login_user=root
    login_password={{ db_password }}
    name=root
    password={{ db_password }}
    priv=_._:ALL,GRANT
    host={{ item }}
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

**Comment by vijayranker** [comment]
I had the same issue,  but the mistake i was doing is, i copied the .my.cnf file to  /root before i set the password.
- name: MySQL | Configure MySql for easy access as root user
  template:
    src: root_dot_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
- name: MySQL | Set the root password.
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_db_pass}}"
  with_items:
  - "{{ansible_hostname}}"
  - 127.0.0.1
  - ::1
  - localhost
    when: ansible_hostname != 'localhost'
- name: MySQL | Set the root password.
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_db_pass}}"
  with_items:
  - 127.0.0.1
  - ::1
  - localhost
    when: ansible_hostname == 'localhost'

**Comment by biroeng** [comment]
@vijayranker  any luck , I am facing same problem ..

**Comment by zacker330** [comment]
I have same problem too..

**Comment by rparsi** [comment]
@biroeng 
I ran into same problem.
As long as I did the following tasks before any mysql related tasks, provisioning works:

(Sorry for the formatting, I can't get it to look right in this comment box)

` - name: Set MySQL root password before installing`
`    debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_pass | quote }}' vtype='password'`

`  - name: Confirm MySQL root password before installing`
`    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_pass | quote }}' vtype='password'`

If it helps, I have the fully working task file (mysql role) in my repository:
[https://github.com/rparsi/ansible/blob/master/roles/mysql/tasks/main.yml](https://github.com/rparsi/ansible/blob/master/roles/mysql/tasks/main.yml)

**Comment by biroeng** [comment]
@Thanks Rparsi , I was able to get beyond this step in Centos 6.8 and Centos 7 

     - name: install MySQL Database Items
       yum: name={{item}} state=present enablerepo=MySQL5.6CommunityServer  update_cache=yes
       with_items:
           - mysql*
           - mysql-server
           - mysql-bench
           - mysql-devel
           - mysql-libs
           - mysql-connector-java
           #- mysql-connector-odbc
           #- mysql-embedded
           - mysql-embedded-devel
           - MySQL-python
           #- mysql++*
     - name: ensure mysql started
       service: name=mysqld state=started enabled=yes
     - name: update mysql root password for all root accounts from local servers
       mysql_user: name=root
                   host="{{item}}"
                   password="xxxxxxxxxxx"
                   priv=*.*:ALL,GRANT
                   login_user=root
                   login_password=""
                   state=present

       with_items:
           - localhost
           - 127.0.0.1
           - ::1
           - localhost
     - name :  ensure mysql started
       service: name=mysqld state=started enabled=yes
     - name: copy .cnf file to root
       copy: src=../files/.my.cnf dest=/root/ owner=root mode=600
     - name: Change Root password
       mysql_user: name=root password="xxxxxxxx" update_password=always

**Comment by vaibhavjpr** [comment]
@biroeng 

I have tried this but it's failing. Is there a way that we can preseed mysql root password in centos/redhat machines like debian/ubuntu

name: MySQL | Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password password $mysql_root_password | sudo /usr/bin/debconf-set-selections
  tags: mysql

- name: MySQL | Set debconf vars
  action: raw sudo echo mysql-server mysql-server/root_password_again password $mysql_root_password | sudo /usr/bin/debconf-set-selections
  tags: mysql

**Comment by biroeng** [comment]
@vaibhavjpr 
We run it on Centos 6.7 & Centos 7
It works fine   
---
  - hosts :  localhost
    tags: ['mysql']
    vars_files: 
      - ../vars/vars.yml
    tasks:

     - name: "MySQL: yum_repository: el6: MySQL 5.6 Community Server"
       yum_repository:
          name: MySQL5.6CommunityServer
          description: MySQL5.6CommunityServer
          baseurl: "{{mysql_el6_url}}"
          gpgcheck: 0
          enabled : true
       when:
       - ansible_distribution == "CentOS"
       - ansible_distribution_major_version == "6"

     - name: "MySQL: yum_repository: el7: MySQL 5.6 Community Server"
       yum_repository:
          name: MySQL5.6CommunityServer
          description: MySQL5.6CommunityServer
          baseurl: "{{mysql_el7_url}}"
          gpgcheck: 0
          enabled : true
       when:
       - ansible_distribution == "CentOS"
       - ansible_distribution_major_version == "7"

     - name: "MySQL: yum: packages: MySQL5.6CommunityServer"
       yum:
         name: "{{item}}"
         state: present
         enablerepo: MySQL5.6CommunityServer
         update_cache: yes
       with_items:
           - mysql*
           - mysql-server
           - mysql-libs
           - mysql-connector-java
           - MySQL-python
           - mysql-devel

     - name: "MySQL: service: ensure mysql started"
       service:
         name: mysqld
         state: started
         enabled: yes

     - name: "MySQL: mysql_user: update mysql root password for all root accounts"
       mysql_user:
         name: root
         host: "{{item}}"
         password: "{{default_password}}"
         priv: "*.*:ALL,GRANT"
         login_user: root
         login_password: ""
         state: present
       with_items:
           - "{{default_fqdn}}"
           - 127.0.0.1
           - ::1
           - localhost
       ignore_errors: true

     - name :  "MySQL: service: ensure mysql started"
       service:
         name: mysqld
         state: started
         enabled: yes

     - name: "MySQL: template: .my.cnf file to /root"
       template:
         src: ../templates/.my.cnf
         dest: "/root"
         owner: "{{linux_admin_id}}"
         mode: 0600

     - name: "MySQL: template: .my.cnf file to /home/{{linux_user}}"
       template:
         src: ../templates/.my.cnf
         dest: "/home/{{linux_user}}"
         owner: "{{linux_user}}"
         group: "{{linux_group}}"
         mode: 0600

     - name: "MySQL: mysql_user: Change Root password"
       mysql_user:
         name: root
         password: "{{default_password}}"
         update_password: always

**Comment by vaibhavjpr** [comment]
@biroeng thx a ton.. it worked..  👍

**Comment by macskay** [comment]
I can't get this to work. I tried setting `debconf` via the ansible built-in `debconf` module and also by trying the `shell` module and piping the echo to `debconf-set-selections`. I also found a solution where the `DEBIAN_FRONTEND` variable was set to `noninteractive` with no success either.
This is my main.yml:
```
- name: debconf
  shell: echo "mysql-server-5.7 mysql-server/root_password password root" | debconf-set-selections

- name: debconf
  shell: echo "mysql-server-5.7 mysql-server/root_password_again password root" | debconf-set-selections

- name: "Installation on MySQL"
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - mysql-server-5.7

- name: "Installation on libmysqlclient-dev"
  apt: name={{ item }} state=present
  with_items:
   - libmysqlclient-dev

- name: "Install Python MySQL Module"
  pip:
   name: MySQL-python
    
- name: "Set root password"
  mysql_user: login_user=root 
              login_password=root 
              check_implicit_admin=yes 
              name=root 
              host={{ item }} 
              password={{ password }} 
              state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: "Set /root/.my.cnf"
  shell: printf '[mysql]\n
    user\t\t= root\n
    password\t= {{ password }}\n' >> /root/.my.cnf 
- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Set validate password policy to medium
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - SET GLOBAL validate_password_policy='MEDIUM'
  changed_when: False

- name: "Copying MySQL Configuration to remote host"
  template: src=../files/mysqld.cnf dest=/etc/mysql/mysql.conf.d owner=root group=root mode=0644

- name: "Restarting MySQL Service"
  systemd:
   name: mysqld
   enabled: yes
   state: restarted


- file: 
   path: /root/.my.cnf
   mode: "go-rwx" 

- name: "Removing Python MySQL Module"
  pip: 
   name: MySQL-python
   state: absent
```

It crashes at `"Set root password"` with an `Access denied`. Why is this not working? Also when restarting the script (after purging MySQL again) it the debconf always gives me a "changed" state, although I always set the same root password in the beginning.
