### ISSUE TITLE
k8s module: when patching a configmap old data entries are not removed

### ISSUE THREAD

**Issue by zioproto** [ansible/ansible#43206]
##### SUMMARY

When patching an existing configmap, new data entries are added, but old data entries are not removed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
k8s_raw module.

##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### STEPS TO REPRODUCE
If you create a config map running this task:

```
- name: Create configmap
  k8s:
    context: "{{ k8s_context }}"
    state: present
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: config
        namespace: "myns"
      data:
        file.conf: "data"
```

and later you patch your code changing the file name in file2.conf:

```
- name: Create configmap
  k8s:
    context: "{{ k8s_context }}"
    state: present
    definition:
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: config
        namespace: "myns"
      data:
        file2.conf: "data"
```
after running again this code you will have a config map called `config` that has both `file.conf` and `file2.conf`.

##### EXPECTED RESULTS
The correct behaviour would be to delete `file.conf` from the configmap.
