### ISSUE TITLE
ec2_vpc_net not returning vpc id

### ISSUE THREAD

**Issue by jandy33** [ansible/ansible#43229]
##### SUMMARY

ec2_vpc_net not returning vpc_id for new create VPC

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ec2_vpc_net

##### ANSIBLE VERSION

```
ansible 2.6.0
   config file = /home/jim/ansible/config/ansbile.cfg
   configured module search path = [u'/home/jim/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jim/ansible/lib/python2.7/site-packages
  executable location = /home/jim/ansible/bin/ansible
  python version = 2.7.5 (default, Aug 4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Head 4.8.5-16)]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/home/jim/ansible/config/ansible.cfg = [u'/home/jim/ansible/inventory/hosts.ini
DEFAULT_LOG_PATY(/home/jim/ansible/config/ansible.cfg = /home/jim/ansible/log/ansible.log
DEFAULT_TIMEOUT(/home/jim/ansible/config/ansible.cfg) = 5
HOST_KEY_CHECKING(/home/jim/ansible/config/ansible.cfg) = False

##### OS / ENVIRONMENT

Centos7

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ec2_name_prefix: testvpc
    ec2_vpc_subnet: "172.16.0.0/24"
    ec2_region: us-east-1

  tasks:
    - name: Create AWS VPC SEAN-MAY9-vpc
      ec2_vpc_net:
        name: "{{ ec2_name_prefix }}-vpc"
        cidr_block: "{{ ec2_vpc_subnet }}"
        region: "{{ ec2_region }}"
        state: present
        tags:
          Name: "{{ ec2_name_prefix }}"
          Request_ID: "REQXXXXXX"
      register: create_vpc
   - name: Checking vpc id
      debug:
          msg: "{{ create_vpc.vpc.id }}"
```

##### EXPECTED RESULTS

The vpc id is returned

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
     File "/tmp/ansible_3CMWLo/ansible_module_ec2_vpc_net.py", line 444. in main
       Filters=[{'Name':'cidr-block-association.cidr-block', 'Values':expected_cidrs}"
     File "/usr/share/awscli/lib/python2.7/site-packages/botocore/waiter.py", lime 53 in wait
        Waiter.wait(self, **kwargs)
     File "/usr/share/awscli/lib/python2.7/site-package/botocore/waiter.py",
 line 329, in wait
        last_response=response

fatal: [localhost]: FAILED! => {
     "boto3_version":"1.4.6"
     "botocore_version": "1.10.28"
     "changed" : false,
     "invocation" : {
           "module_args" : {
                 "cidr_block":[
                       "172.16.0.0/24" 
                   ],
                 "region" : "us-east-1",
                 "name" : "testvpc-vpc",
                 "tags" : {
                      "Name:" "testvpc"
                      "Request_ID": "REQXXXXXX"
                  }
                 "tenancy": "default",
           }
    },
    "msg" : "Failed to wat for CIDR's to update: Waiter VpcAvailable failed: Max attempts exceeded"
```
