### ISSUE TITLE
ipa_vault does not report a change if user is added to vault

### ISSUE THREAD

**Issue by schegi** [ansible/ansible#43239]
##### SUMMARY

The ipa_vault module does not report a 'change' if an user is added to an existing vault.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT

Linux 3.10.0-862.2.3.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
    - name: Add standard vault
      ipa_vault:
        name: standard_vault03
        vault_type: standard
        ipa_host: "{{ ipa_credentials.ipa_host }}"
        ipa_user: "{{ ipa_credentials.ipa_user }}"
        ipa_pass: "{{ ipa_credentials.ipa_pass }}"
        validate_certs: false

    - name: Add standard vault
      ipa_vault:
        name: standard_vault03
        vault_type: standard
        user: test01
        ipa_host: "{{ ipa_credentials.ipa_host }}"
        ipa_user: "{{ ipa_credentials.ipa_user }}"
        ipa_pass: "{{ ipa_credentials.ipa_pass }}"
        validate_certs: false
```

##### EXPECTED RESULTS

The second call of ipa_vault should report 'change': true on the vault but it just adds the user and reports 'changed': false

##### ACTUAL RESULTS

```
    changed: [iw-ipa-test-01] => {
        "changed": true,
        "invocation": {
            "module_args": {
                "cn": "standard_vault03",
                "description": null,
                "ipa_host": "iw-ipa-test-01.example.de",
                "ipa_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "ipa_port": 443,
                "ipa_prot": "https",
                "ipa_user": "admin",
                "ipavaultpublickey": null,
                "ipavaultsalt": null,
                "ipavaulttype": "standard",
                "name": "standard_vault03",
                "replace": false,
                "service": null,
                "state": "present",
                "username": null,
                "validate_certs": false,
                "vault_type": "standard"
            }
        },
        "vault": {
            "cn": [
                "standard_vault03"
            ],
            "dn": "cn=standard_vault03,cn=admin,cn=users,cn=vaults,cn=kra,dc=uf0,dc=de",
            "ipavaulttype": [
                "standard"
            ],
            "objectclass": [
                "ipaVault",
                "top"
            ],
            "owner_user": [
                "admin"
            ],
            "username": "admin"
        }
    }

    ok: [iw-ipa-test-01] => {
        "changed": false,
        "invocation": {
            "module_args": {
                "cn": "standard_vault03",
                "description": null,
                "ipa_host": "iw-ipa-test-01.example.de",
                "ipa_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "ipa_port": 443,
                "ipa_prot": "https",
                "ipa_user": "admin",
                "ipavaultpublickey": null,
                "ipavaultsalt": null,
                "ipavaulttype": "standard",
                "name": "standard_vault03",
                "replace": false,
                "service": null,
                "state": "present",
                "user": "test01",
                "username": [
                    "test01"
                ],
                "validate_certs": false,
                "vault_type": "standard"
            }
        },
        "vault": {
            "cn": [
                "standard_vault03"
            ],
            "dn": "cn=standard_vault03,cn=admin,cn=users,cn=vaults,cn=kra,dc=uf0,dc=de",
            "ipavaulttype": [
                "standard"
            ],
            "objectclass": [
                "ipaVault",
                "top"
            ],
            "owner_user": [
                "admin"
            ],
            "username": "admin"
        }
    }
```
