### ISSUE TITLE
java_cert module does not check the certificate checksum only alias

### ISSUE THREAD

**Issue by jojo221119** [ansible/ansible#43249]
##### SUMMARY

When importing a new certificate into java keystore the java_certs module only checks if the alias is already used in the java_keystore. When an alias is already used it the task outcome states OK.
Even when the certificate which should be imported is different to the certificate using this alias.

I would expect that the SHA1 hash is checked also. If then the alias is present and the SHA1 hashes match everything is OK. But if there is a mismatch with the hashes, the module should at least state failure or provide a possibility to force overwriting the certificate.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

java_cert
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /net/fe0vmc1667/fs0/develop/htj8fe/ops_tools/ansible_scripts/ansible.cfg
  configured module search path = [u'/local/home/axway_topo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

DEFAULT_HOST_LIST
DEFAULT_VAULT_PASSWORD_FILE

##### OS / ENVIRONMENT

"N/A"
##### STEPS TO REPRODUCE

In the below example "cert_alias" being an alias already used in the keystore and "cert_path" pointing to a certificate different than the certificate stored in the keystore with the alias.
```yaml
    - name: import CA certificates into java keystore
      java_cert:
        executable: "/platform/jre/bin/keytool"
        state: present
        keystore_create: yes
        keystore_path: "{{ item.keystorePath }}"
        keystore_pass: "{{ item.keystorePass }}"
        cert_path: "{{ item.cert_path }}"
        cert_alias: "{{ item.cert_alias }}"


```

##### EXPECTED RESULTS

Failure or certificate being overwritten.
##### ACTUAL RESULTS

Module states OK

```

```
