### ISSUE TITLE
mysql_user not idempotent for mariadb 10.2 root user due to authentication_string column instead of password

### ISSUE THREAD

**Issue by NielsH** [ansible/ansible#43255]
<!---
Verify first that your issue/request is not already reported on GitHub.
THIS FORM WILL BE READ BY A MACHINE, COMPLETE ALL SECTIONS AS DESCRIBED.
Also test if the latest release, and devel branch are affected too.
ALWAYS add information AFTER (OUTSIDE) these html comments.
Otherwise it may end up being automatically closed by our bot. -->

##### SUMMARY
<!--- Explain the problem briefly -->
Using MariaDB 10.2.16 from the MariaDB repo (http://ams2.mirrors.digitalocean.com/mariadb/repo/10.2/debian/) on Debian jessie. Updating the password for the user "root" is not idempotent. This is because the password set for the root user during installation is saved in the `authentication_string` column in the `mysql` database. However, ansible checks the `password` column. When I enabled query logging I see the following:

                 1408 Query     SET autocommit=0
                 1408 Query     SELECT @@GLOBAL.sql_mode
                 1408 Query     SELECT count(*) FROM user WHERE user = 'root' AND host = '127.0.0.1'
                 1408 Query     SELECT VERSION()
                 1408 Query     SELECT password FROM user WHERE user = 'root' AND host = '127.0.0.1'
                 1408 Query     SELECT PASSWORD('MYPASSWORD')
                 1408 Query     SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('MYPASSWORD')

While this *does* change the password, it is saved in the `authentication_string` column so Ansible doesn't know the correct password has already been set and keeps updating it.
New users created through Ansible have the `password` column filled and not the `authentication_string` column so things work correctly there. But the root user is set up automatically during installation and uses `authentication_string` instead of `password`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
<!--- Insert, BELOW THIS COMMENT, the name of the module, plugin, task or feature.
Do not include extra details here, e.g. "vyos_command" not "the network module vyos_command" or the full path-->
mysql_user
##### ANSIBLE VERSION
<!--- Paste, BELOW THIS COMMENT, verbatim output from "ansible --version" between quotes below -->
```
ansible 2.4.6.0
  config file = None
  configured module search path = [u'/home/niels/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.6.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```
Fwiw I also tried with the devel branch but same issue there.

##### CONFIGURATION
<!--- If using Ansible 2.4 or above, paste, BELOW THIS COMMENT, the results of "ansible-config dump --only-changed"
Otherwise, mention any settings you have changed/added/removed in ansible.cfg
(or using the ANSIBLE_* environment variables).-->
N/A
##### OS / ENVIRONMENT
<!--- Mention, BELOW THIS COMMENT, the OS you are running Ansible from, and the OS you are
managing, or say "N/A" for anything that is not platform-specific.
Also mention the specific version of what you are trying to control,
e.g. if this is a network bug the version of firmware on the network device.-->
N/A
Dependant on MariaDB 10.2 from MariaDB repo.

##### STEPS TO REPRODUCE
<!--- For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used. -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: update mariadb root password for server hostname                                                                                                                                                           
  mysql_user:                                                                                                                                                                                                      
    name: "{{ mariadb_root_username }}"                                                                                                                                                                            
    host: "{{ item }}"                                                                                                                                                                                             
    password: "{{ mariadb_root_password }}"                                                                                                                                                                        
    priv: "*.*:ALL,GRANT"                                                                                                                                                                                          
    check_implicit_admin: yes                                                                                                                                                                                      
    config_file: "{{ mariadb_mysql_root_credentials_file_path }}"                                                                                                                                                  
  with_items:                                                                                                                                                                                                      
    - 127.0.0.1                                                                                                                                                                                                    
    - ::1                                                                                                                                                                                                          
    - localhost        

```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->
Changing root password to be an idempotent action

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
Ansible keeps reporting "changed" for changing root password.

<!--- Paste verbatim command output between quotes below -->
```

```
