### ISSUE TITLE
pip umask parameter does not work with octal (int) umask values

### ISSUE THREAD

**Issue by pillarsdotnet** [ansible/ansible#43256]
##### SUMMARY

Documentation for the [`pip`](https://docs.ansible.com/ansible/latest/modules/pip_module.html#parameters) module `umask` parameter says that the desired umask mode should be specified in octal, with a leading zero.  However, a test install of the `test-utils` pip using ansible-playbook version 2.6.1 and python version 2.7.15rc1 reveals that leading zeros, unless quoted, cause the umask to be misinterpreted.  This seems to be a case where the octal-to-decimal conversion is applied twice, once by ansible and once by the underlying umask implementation.

umask | result | MSG | details
------|--------|-----|--------
`0022` | failed | umask must be an octal integer | invalid literal for int() with base 8: '18' ... "umask": "18" ...
`022` | failed | umask must be an octal integer | invalid literal for int() with base 8: '18' ... "umask": "18" ...
`22` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "22" ... 
`'0022'` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "0022" ... 
`'022'` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "022" ... 
`'22'` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "22" ... 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

pip

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/bobvin/test/ansible.cfg
  configured module search path = [u'/home/bobvin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

ANSIBLE_FORCE_COLOR(/home/bobvin/test/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/bobvin/test/ansible.cfg) = ['debug']
DEFAULT_DEBUG(/home/bobvin/test/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/bobvin/test/ansible.cfg) = debug
DEFAULT_TRANSPORT(/home/bobvin/test/ansible.cfg) = local
INVENTORY_ENABLED(/home/bobvin/test/ansible.cfg) = ['yaml']
LOCALHOST_WARNING(/home/bobvin/test/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS (Bionic Beaver)

##### STEPS TO REPRODUCE

I created a shell script and playbooks (See attached [test.zip](https://github.com/ansible/ansible/files/2228094/test.zip)) and ran them as:
```sh
sudo -H test-umask.sh
```

Here are the test files, inline:

`test-umask.sh`
```sh
#!/bin/bash
id -u | grep -q '^0$' || exit 1
SETUP_SH=$(readlink -f $0)
SETUP_DIR=$(dirname $SETUP_SH)
cd $SETUP_DIR
umask 0027
ls -lR /usr/local/lib/python2.7/dist-packages >before.ls-LR
for testcase in pip-umask-*.yml
do
  ANSIBLE_DISPLAY_ARGS_TO_STDOUT=True ansible-playbook -i localhost.yml -vvvvv $testcase >$testcase.log 2>&1
  ls -lR /usr/local/lib/python2.7/dist-packages >$testcase.ls-LR
  pip uninstall -y test-utils >/dev/null 2>&1
done
ls -lR /usr/local/lib/python2.7/dist-packages >after.ls-LR
```

`localhost.yml`
```yaml
all:
  hosts:
    localhost:
```

`pip-umask-quoted-0022.yml`
```yaml
---
- hosts: localhost
  tasks:
  - pip:
      name: test-utils
      umask: '0022'
```

`pip-umask-quoted-022.yml`
```yaml
---
- hosts: localhost
  tasks:
  - pip:
      name: test-utils
      umask: '022'
```

`pip-umask-quoted-22.yml`
```yaml
---
- hosts: localhost
  tasks:
  - pip:
      name: test-utils
      umask: '22'
```

`pip-umask-unquoted-0022.yml`
```yaml
---
- hosts: localhost
  tasks:
  - pip:
      name: test-utils
      umask: 0022
```

`pip-umask-unquoted-022.yml`
```yaml
---
- hosts: localhost
  tasks:
  - pip:
      name: test-utils
      umask: 022
```

`pip-umask-unquoted-22.yml`
```yaml
---
- hosts: localhost
  tasks:
  - pip:
      name: test-utils
      umask: 22
```

##### EXPECTED RESULTS

I expected that specifying a umask of `22` or `'22'` would fail, while `022`, `0022`, `'022'`, and `'0022'` would succeed, as follows:

umask | result 
------|--------
`0022` | ok
`022` | ok
`22` | failed
`'0022'` | ok
`'022'` | ok
`'22'` | failed

##### ACTUAL RESULTS

Specifying the umask as an unquoted octal with leading zero fails, whereas all other possible formats succeed.

umask | result | MSG | details
------|--------|-----|--------
`0022` | failed | umask must be an octal integer | invalid literal for int() with base 8: '18' ... "umask": "18" ...
`022` | failed | umask must be an octal integer | invalid literal for int() with base 8: '18' ... "umask": "18" ...
`22` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "22" ... 
`'0022'` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "0022" ... 
`'022'` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "022" ... 
`'22'` | ok | Successfully installed test-utils-0.1.0 | ... "umask" : "22" ... 

The relevant output from the first failure is as follows:
```
The full traceback is:
  File "/tmp/ansible_n3i9Vt/ansible_module_pip.py", line 437, in main
    umask = int(umask, 8)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "details": "invalid literal for int() with base 8: '18'",
    "invocation": {
        "module_args": {
            "chdir": null,
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "test-utils"
            ],
            "requirements": null,
            "state": "present",
            "umask": "18",
            "use_mirrors": true,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    }
}

MSG:

umask must be an octal integer
```

The complete debug output is in [pip-umask-unquoted-0022.yml.log](https://github.com/ansible/ansible/files/2228153/pip-umask-unquoted-0022.yml.log).
