### ISSUE TITLE
win_iis_webapppool environemnt varible atributes doesn't work

### ISSUE THREAD

**Issue by flomedja** [ansible/ansible#43265]
##### SUMMARY

I have an IIS app pool for a asp.net core 2.0 web service that i launch with ansible task like that 

```
win_iis_webapppool:
 name: test_app
 state:started
 attributes:
   managedRuntimeVersion:
   processModel.idleTimeout: 0
   environmentVariables:
    -TestVar: UoXDtpQbcyDFzaXX
```

The output of my task look like that:
```
changed: [webserver] => {
    "attributes": {
        "environmentVariables": [
            {
                "TestVar": "UoXDtpQbcyDFzaXX"
            }
        ],
        "managedRuntimeVersion": null,
        "processModel.idleTimeout": 0
}...

```
According to [documentation ](https://docs.microsoft.com/en-us/iis/configuration/system.applicationHost/applicationPools/add/environmentvariables/index#overview) the environement variable must be set for the process but when i print the appool process environment variables i don't see the environment variable "TestVar" that I set previously.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_iis_webapppool

##### ANSIBLE VERSION

```
ansible 2.5.3
```

##### CONFIGURATION

IIS 10.0
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_iis_webapppool.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_iis_webapppool.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @henrikwallstrom @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @if-meaton
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
looking at the examples here https://docs.microsoft.com/en-us/iis/configuration/system.applicationHost/applicationPools/add/environmentvariables/index#overview
there seem to be add and remove child elements under envirnomentVariables element 

```xml
<applicationPools>
   <add name="Contoso" managedRuntimeVersion="v4.0" managedPipelineMode="Classic">
      <environmentVariables>
         <add name="foo" value="bar" />
      </environmentVariables>
   </add>
</applicationPools>
```

so I wonder if you need to do the same with this module.
```yaml
win_iis_webapppool:
 name: test_app
 state:started
 attributes:
   managedRuntimeVersion:
   processModel.idleTimeout: 0
   environmentVariables:
     add:
      - TestVar: UoXDtpQbcyDFzaXX
```

Its possible this needs a code change to work though, as I think this module was created before IIS 10 was released.

@FloMedja please can you try the above suggestion and report back if this works or not? (I don't have an IIS 10 to test against at the moment).

needs_info
