### ISSUE TITLE
Role inclusion to be skipped by condition fails on non-presence of subelement

### ISSUE THREAD

**Issue by zjpeterson** [ansible/ansible#43264]
##### SUMMARY

Occurs when conditionally including a role, and the role contains a with_subelements loop (or loop with subelements filter). Ansible looks for the subelement and fails if it's not defined, or if it is defined but is not a list. The problem is that this occurs even when the role inclusion condition is false and the role will not be included. One should not have to needlessly define a variable that will not be used, or use subelements when otherwise unneeded.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

with_subelements

##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### STEPS TO REPRODUCE

Playbook:
```yaml
- name: "test"
  hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - role: condition-2
      when: var4 is search("2")
    - role: condition-1
      when: var4 is search("1")
```
roles/condition-2/tasks/main.yml:
```yaml
---
- loop:
    - "{{ var1|subelements('var3') }}"
  debug: msg="{{ item.1 }}"
```
roles/condition-1/tasks/main.yml:
```yaml
---
- loop: "{{ var1 }}"
  debug: msg="{{ item.var2 }}"
```
Variables used during condition 1:
```yaml
var1:
  - var2: test
var4: condition-1
```
Variables used during condition 2:
```yaml
var1:
  - var3:
    - item1
    - item2
var4: condition-2
```

##### EXPECTED RESULTS

When using condition 1 variables, skip past the inclusion of role 'condition-2' and include 'condition-1' successfully.

##### ACTUAL RESULTS

```
PLAY [test] ********************************************************************

TASK [condition-2 : debug] **************************************************
fatal: [localhost]: FAILED! => {"msg": "could not find 'var3' key in iterated item {u'var2': u'test'}"}
```
Additionally, even if one were to use the same variable name across conditions, but not as a list, this still produces a failure:
```
PLAY [test] ********************************************************************

TASK [condition-2 : debug] **************************************************
fatal: [localhost]: FAILED! => {"msg": "the key 'var3' should point to a list, got u'test'"}
```
At this point, you are forced to write all conditions to use subelements, or include an unused list in the variables to pass the list check.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Roles inside the `roles` directive are statically imported, which means all tasks inside them are evaluated at run time, not at execution time.

To get the behavior you want, use `include_role`. This will only load the role if the condition is true and avoid evaluating conditionals on tasks in those roles.

```yaml
tasks:
  - include_role:
      name: condition-2
    when: var4 is search("1")

  - include_role:
      name: condition-1
    when: var4 is search("2")
```

For further help with the issue, please reach out on IRC or the mailing:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
