### ISSUE TITLE
script module with become prepends stdout with \r\n

### ISSUE THREAD

**Issue by rwagnergit** [ansible/ansible#43274]
##### SUMMARY
script module prepends stdout with \r\n when used with become=yes

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

script
ssh

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/rowagn/ansible.cfg
  configured module search path = [u'/home/rowagn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

ALLOW_WORLD_READABLE_TMPFILES(/home/rowagn/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/rowagn/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/rowagn/ansible.cfg) = -o ControlMaster=no
DEFAULT_EXECUTABLE(/home/rowagn/ansible.cfg) = /etc/ansible-wrapper
DEFAULT_HOST_LIST(/home/rowagn/ansible.cfg) = [u'/home/rowagn/hosts']
RETRY_FILES_ENABLED(/home/rowagn/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
rowagn@dbatower01:~#> cat hosts
[all]
localhost

rowagn@dbatower01:~#> cat a.sh
#!/bin/sh

echo "line 1"
echo "line 2"

rowagn@dbatower01:~#> cat a.yml
---
- hosts: all
#  become: yes
#  become_user: root
  tasks:
  - script: "{{ playbook_dir }}/a.sh"
    register: A
  - debug:
      msg="{{ A }}"

rowagn@dbatower01:~#> cat b.yml
---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - script: "{{ playbook_dir }}/a.sh"
    register: A
  - debug:
      msg="{{ A }}"

rowagn@dbatower01:~#> ansible-playbook a.yml -k
rowagn@dbatower01:~#> ansible-playbook b.yml -k -K

```

##### EXPECTED RESULTS

stdout should be identical between the two playbooks.

##### ACTUAL RESULTS

stdout is prepended with \r\n when running b.yml (i.e., when including become: yes)

```
rowagn@dbatower01:~#> ansible-playbook a.yml -k
SSH password:

PLAY [all] ***************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************
ok: [localhost]

TASK [script] ************************************************************************************************************************************************************
changed: [localhost]

TASK [debug] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "rc": 0,
        "stderr": "Connection to localhost closed.\r\n",
        "stderr_lines": [
            "Connection to localhost closed."
        ],
        "stdout": "line 1\r\nline 2\r\n",
        "stdout_lines": [
            "line 1",
            "line 2"
        ]
    }
}

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0

rowagn@dbatower01:~#> ansible-playbook b.yml -k -K
SSH password:
SUDO password[defaults to SSH password]:

PLAY [all] ***************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************
ok: [localhost]

TASK [script] ************************************************************************************************************************************************************
changed: [localhost]

TASK [debug] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "failed": false,
        "rc": 0,
        "stderr": "Connection to localhost closed.\r\n",
        "stderr_lines": [
            "Connection to localhost closed."
        ],
        "stdout": "\r\nline 1\r\nline 2\r\n",
        "stdout_lines": [
            "",
            "line 1",
            "line 2"
        ]
    }
}

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0


```
