### ISSUE TITLE
no_log is not dynamic in loops

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#43294]
##### SUMMARY
when no_log is set to a variable,  the variable is not expanded if the task is in a loop (but works fine if the task is not in a loop)

##### ISSUE TYPE
 - Bug  Report

##### COMPONENT NAME
task_executor

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel 72f1a6cc1f) last updated 2018/07/26 14:37:42 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/opensource/ansible/lib/ansible
  executable location = /Users/will/src/opensource/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
No output to `ansible-config dump --only-changed`

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: no loop, task fails, dynamic no_log works 
      debug:
        msg: "{{ var_does_not_exist }}"
      no_log: "{{ not (unsafe_show_logs|bool) }}"

    - name: loop, task succeeds, dynamic no_log does not work
      debug:
        msg: "{{ item }}"
      loop:
        - a
        - b
        - c
      no_log: "{{ not (unsafe_show_logs|bool) }}"

    - name: loop, task fails, dynamic no_log does not work 
      debug:
        msg: "{{ var_does_not_exist }}"
      loop:
        - a
        - b
        - c
      no_log: "{{ not (unsafe_show_logs|bool) }}"
```

##### EXPECTED RESULTS
When run with `ansible-playbook -e unsafe_show_logs=yes -vv play.yml`, I would expect all tasks to show output

##### ACTUAL RESULTS
```
$ ansible-playbook play.yml -e unsafe_show_logs=yes -vv
ansible-playbook 2.7.0.dev0 (devel 72f1a6cc1f) last updated 2018/07/26 14:37:42 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/opensource/ansible/lib/ansible
  executable location = /Users/will/src/opensource/ansible/bin/ansible-playbook
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
No config file found; using defaults
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: play.yml ****************************************************************************************************************
1 plays in play.yml

PLAY [localhost] ******************************************************************************************************************
META: ran handlers

TASK [no loop, task fails, dynamic no_log works] **********************************************************************************
task path: /Users/will/tmp/ansible/no_log/play.yml:6
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'var_does_not_exist' is undefined\n\nThe error appears to have been in '/Users/will/tmp/ansible/no_log/play.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: no loop, task fails, dynamic no_log works\n      ^ here\n"}
...ignoring

TASK [loop, task succeeds, dynamic no_log works] **********************************************************************************
task path: /Users/will/tmp/ansible/no_log/play.yml:12
ok: [localhost] => (item=a) => {
    "msg": "a"
}
ok: [localhost] => (item=b) => {
    "msg": "b"
}
ok: [localhost] => (item=c) => {
    "msg": "c"
}
ok: [localhost] => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

TASK [loop, task fails, dynamic no_log does not work] *****************************************************************************
task path: /Users/will/tmp/ansible/no_log/play.yml:21
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
	to retry, use: --limit @/Users/will/tmp/ansible/no_log/play.retry

PLAY RECAP ************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

##### ADDITIONAL INFORMATION

The reason this is failing is because at https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_result.py#L116-L117, `self._task.no_log` is effectively `'{{ not (unsafe_show_logs|bool) }}'` (and thus converts to a boolean as `True`) rather than the variable expansion of `False`. I haven't been able to ascertain why that might be and hope someone more familiar with that bit of the codebase can solve the issue more readily.
