### ISSUE TITLE
Cannot restrict kernel capabilities in the docker_container module

### ISSUE THREAD

**Issue by archmangler** [ansible/ansible#43293]
##### SUMMARY

Cannot restrict kernel capabilities in the docker_container module using the "capabilities" parameter.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.5.2, ansible 2.4.0,ansible 2.4.1, ansible 2.4.2
```

##### STEPS TO REPRODUCE

```yaml
- name: Create a ubuntu container
  docker_container:
    name: ubuntu
    image: ubuntu:16:04
    memory: 512m
    published_ports: 22:22
    capabilities:
      - CHOWN
    security_opts:
      - no-new-privileges
```

##### EXPECTED RESULTS

Some means of specifying caps removed from the container 
##### ACTUAL RESULTS

No means of specifying caps removed from the container 

```
N/A
```
