### ISSUE TITLE
docker_container always recreate container when use remote docker host (vmware virtual container host)

### ISSUE THREAD

**Issue by fRzzy** [ansible/ansible#43304]
I rarely report bugs so if there is anything missing please tell me and I'll try to provide more info. Thank you.

##### SUMMARY

when use with local connection to manage a remote docker host (in my case vmware virtual container host) docker_container recreate containers everytime it run, regardless of container configuration changed or not, result in unnecessary (small) downtime of containers.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/frzzy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
nothing changed

##### OS / ENVIRONMENT
MacOS High Sierra 10.13.5

##### STEPS TO REPRODUCE

```yaml
- name: run adminer
  docker_container:
    docker_host: tcp://vch04:2376
    tls: yes
    ssl_version: TLSv1_2
    name: adminer
    image: adminer:latest
    pull: yes
    restart_policy: always
    env:
      ADMINER_DESIGN: '{{ docker.containers.adminer.design }}'
    ports:
      - 8080:8080/tcp
    state: started
```

##### EXPECTED RESULTS
```
TASK [vic : run adminer] ***************************************************************************************************************
ok: [localhost]
```
##### ACTUAL RESULTS
```
TASK [vic : run adminer] ***************************************************************************************************************
changed: [localhost]
```
