### ISSUE TITLE
Nexus error after completing job 

### ISSUE THREAD

**Issue by feisa** [ansible/ansible#43333]
##### SUMMARY
We are pushing a config file to nexus switches 

##### ISSUE TYPE
The role runs and pushes the correct config but throws an error at the end causing the job to say fail 

##### COMPONENT NAME
`nxos_config`
##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
##### CONFIGURATION
```
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry
```

##### OS / ENVIRONMENT
Centos 7.5

##### STEPS TO REPRODUCE
run the playbook

```yaml
---
- name: Radius Configuration
  hosts: nexus_devices
  gather_facts: no
  tasks:
    - name: Configure Global Radius Values
      nxos_aaa_server:
         server_type: radius 
         server_timeout: 8
         deadtime: 10
         directed_request: enabled
         encrypt_type: 7
         global_key**************************
    - name: Configure Radius Hosts
      nxos_config:
         lines:
                - radius-server host 10.9.15.72 authentication accounting 
                - radius-server host 10.5.15.72 authentication accounting 
                - radius-server host 10.3.15.72 authentication accounting 
                - radius-server host 10.15.15.72 authentication accounting
                - radius-server host 10.16.15.72 authentication accounting 
    - name: Configure Radius Group
      nxos_config:
        src: /home/feisa/git/network/roles/templates/nxos_radius_group

     #        lines: 
     #           - server 10.5.15.72
     #           - server 10.9.15.72
     #           - server 10.3.15.72
     #           - server 10.15.15.72
     #           - server 10.16.15.72
     # parents: aaa group server radius RADIUS
     # before: aaa group server radius RADIUS
```

*************************
src file below

```
conf t
aaa group server radius RADIUS
    server 10.5.15.72
    server 10.9.15.72
    server 10.3.15.72
    server 10.15.15.72
    server 10.16.15.72
end
~
```

##### EXPECTED RESULTS
The playbook pushes the config but throws this error 

##### ACTUAL RESULTS
```
<test-switch.local> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1532640595.2-95024486308758/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_Oen03O/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 162, in load_config
    responses = connection.edit_config(config)
  File "/tmp/ansible_Oen03O/ansible_modlib.zip/ansible/module_utils/connection.py", line 149, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [test-switch.local]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": false, 
            "before": null, 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": null, 
            "intended_config": null, 
            "lines": null, 
            "match": "line", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": {
                "auth_pass": null, 
                "authorize": null, 
                "host": null, 
                "password": null, 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_proxy": true, 
                "use_ssl": null, 
                "username": null, 
                "validate_certs": null
            }, 
            "replace": "line", 
            "replace_src": null, 
            "running_config": null, 
            "save": false, 
            "save_when": "never", 
            "src": "conf t\naaa group server radius RADIUS\n    server 10.5.15.72\n    server 10.9.15.72\n    server 10.3.15.72\n    server 10.15.15.72\n    server 10.16.15.72\nend\n~\n", 
            "ssh_keyfile": null, 
            "timeout": null, 
            "transport": "cli", 
            "use_proxy": true, 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }, 
    "msg": "~\r\r\n              ^\r\n% Invalid command at '^' marker.\r\n\rtest-switch# "
```
