### ISSUE TITLE
Task name is overridden by include_role, and is not evaluated in output

### ISSUE THREAD

**Issue by zjpeterson** [ansible/ansible#43332]
##### SUMMARY

When using `include_role`, the `name` parameter given to it appears to override the `name` parameter given to the task itself. Additionally, if jinja2 was being used to determine which role to include, that is not evaluated and is printed raw, which is not useful to an observer.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```
ansible 2.6.1
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### STEPS TO REPRODUCE

Playbook
```yaml
- name: "test"
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    role_type: a

  tasks:
    - name: Role inclusion test
      include_role:
        name: "role-{{ role_type }}"
```
roles/role-a/tasks/main.yml
```yaml
---
- debug: msg="This is Role A"
```

##### EXPECTED RESULTS
```
PLAY [test] ********************************************************************

TASK [Role inclusion test] *****************************************************

TASK [role-a : debug] **********************************************************
[...]
```
Or, less preferably:
```
PLAY [test] ********************************************************************

TASK [include_role : role-a *************************************

TASK [role-a : debug] **********************************************************
[...]
```
##### ACTUAL RESULTS
```
PLAY [test] ********************************************************************

TASK [include_role : role-{{ role_type }}] *************************************

TASK [role-a : debug] **********************************************************
[...]
```
