### ISSUE TITLE
Unable to create lxd profile, general lxd ansible support

### ISSUE THREAD

**Issue by tokiwinter** [ansible/ansible#43347]
##### SUMMARY

Attempting to create LXD profile results in error

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lxd_profile

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.6.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/virtualenvs/ansible/lib/python3.5/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
No changes
```

##### OS / ENVIRONMENT

```
Ubuntu 16.04.4 - acting against localhost
```
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:
  - name: create test profile
    lxd_profile:
      url: https://127.0.0.1:8443
      name: testpr0
      state: present
      config:
        boot.autostart: "true"
        linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
        raw.lxc: |
          lxc.apparmor.profile=unconfined
          lxc.mount.auto=proc:rw sys:rw
          lxc.cgroup.devices.allow=a *.* rwm
          lxc.cap.drop=
        security.nesting: "true"
        security.privileged: "true"
      description: a test profile
      devices:
        eth0:
          nictype: bridged
          parent: testbr0
          name: eth0
          type: nic
```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_o3lyx6r2/ansible_module_lxd_profile.py", line 373, in <module>
    main()
  File "/tmp/ansible_o3lyx6r2/ansible_module_lxd_profile.py", line 368, in main
    lxd_manage = LXDProfileManagement(module=module)
  File "/tmp/ansible_o3lyx6r2/ansible_module_lxd_profile.py", line 209, in __init__
    debug=self.debug
  File "/tmp/ansible_o3lyx6r2/ansible_modlib.zip/ansible/module_utils/lxd.py", line 86, in __init__
FileNotFoundError: [Errno 2] No such file or directory

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_o3lyx6r2/ansible_module_lxd_profile.py\", line 373, in <module>\n    main()\n  File \"/tmp/ansible_o3lyx6r2/ansible_module_lxd_profile.py\", line 368, in main\n    lxd_manage = LXDProfileManagement(module=module)\n  File \"/tmp/ansible_o3lyx6r2/ansible_module_lxd_profile.py\", line 209, in __init__\n    debug=self.debug\n  File \"/tmp/ansible_o3lyx6r2/ansible_modlib.zip/ansible/module_utils/lxd.py\", line 86, in __init__\nFileNotFoundError: [Errno 2] No such file or directory\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

I am probably doing something incorrect. I also tried installing the module directly with
```
 ansible-galaxy install hispanico.lxd
```

In essence, I want a robust way to create LXD networks, profiles and containers with ansible, rather than relying on the custom tooling that I currently use (which works well, but I'd rather use ansible for all tasks).

Even if I strip things back to a very simple profile, as per the documentation (https://docs.ansible.com/ansible/latest/modules/lxd_profile_module.html)
```
- hosts: localhost
  connection: local
  tasks:
  - name: create test profile
    lxd_profile:
      url: https://127.0.0.1:8443
      name: testpr0
      state: present
      config: {}
      description: a test profile
      devices:
        eth0:
          nictype: bridged
          parent: testbr0
          name: eth0
          type: nic
```
I receive the same result.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/lxd/lxd_profile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/lxd/lxd_profile.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @hnakamur
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tokiwinter** [comment]
If it helps, I am running `lxd` 3.0.0:
```
# lxd --version
3.0.0
```

**Comment by bjonnh** [comment]
I have the same issue, did you find a solution?

**Comment by karlmiles** [comment]
I hit the same resulting error message this evening albeit with Ubuntu 18.10 and for creating a container rather than a profile.  By getting Ansible to not tidy-up its temporary files and then running the troubled script:
`python3 AnsiballZ_lxd_container.py explode`
That created a set of files in a `debug_dir` subdirectory which can be executed in there with `python __main__.py < args`, that then pointed me in the direction of the module trying to use a certificate & key file, which seems to be necessary when using a https:// url.

Anyway, here's my task that points the certificate & key file into my Snap config files:

```
- name: Create containers
  lxd_container:
    name: "{{ item }}"
    state: "started"
    trust_password: "removed"
    url: "https://127.0.0.1:8443"
    wait_for_ipv4_addresses: "yes"
    cert_file: "{{ lookup('env', 'HOME') }}/snap/lxd/10102/.config/lxc/client.crt"
    key_file: "{{ lookup('env', 'HOME') }}/snap/lxd/10102/.config/lxc/client.key"
    source:
      type: "image"
      mode: "pull"
      server: "https://images.linuxcontainers.org"
      protocol: "simplestreams"
      alias: "debian/9"
  loop: "{{ groups['containers'] }}"
```
I need to improve the links to the client certificate & key, as I'm guessing its volatile given that I have a few subdirectories with them in, but, the 10102 value was from executing `snap list`, which gave me:
```
Name                  Version         Rev    Tracking  Publisher   Notes
core                  16-2.37.1       6350   stable    canonical✓  core
gnome-3-26-1604       3.26.0          74     stable/…  canonical✓  -
gnome-calculator      3.30.1          260    stable/…  canonical✓  -
gnome-characters      3.30.0          139    stable/…  canonical✓  -
gnome-logs            3.30.0          45     stable/…  canonical✓  -
gnome-system-monitor  3.30.0          57     stable/…  canonical✓  -
gtk-common-themes     0.1-7-g1feddba  1122   stable/…  canonical✓  -
lxd                   3.10            10102  stable/…  canonical✓  -
```
Anyway, I hope this helps you guys out.
