### ISSUE TITLE
Direct VMKernel Adapter Creation on a dvSwitch portgroup

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#43351]
##### SUMMARY
I'm unable to create VMKernel adapters directly on a dvSwitch portgroup using vmware_vmkernel.

To get a VMKernel adapter created on a dvSwitch I have to do the following;

1. Create a temporary vSwitch using **vmware_vswitch** on the target ESXi host
2. Create a temporary portgroup created using **vmware_portgroup** on the target ESXi host
3. A VMKernel adapter on the temporary portgroup using **vmware_vmkernel** on the taget ESXi host
4. Migrate the VMKernel to the dvSwitch using **vmware_migrate_vmk** 

Deployment and checks will be simplified if vmware_vmkernel can accomodate both switch types as I will be deploying to large clusters of ESXi servers

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_vmkernel.py

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /root/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

DEFAULT_MANAGED_STR(/root/code/vmware-ansible/ansible.cfg) = This file is managed by Ansible
HOST_KEY_CHECKING(/root/code/vmware-ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/root/code/vmware-ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Target is vSphere 6.7, ESXi and vCenter

##### STEPS TO REPRODUCE
The ESXi host is already attached to the dvSwitch "dvs_vmotion" which has the portgroup "vmotion"

```
- name: 'Create a test vmk1'
  vmware_vmkernel:
    hostname: '{{ client_vcenter }}'
    username: '{{ client_vcenter_username }}'
    password: '{{ client_vcenter_password }}'
    esxi_hostname: '{{ ansible_host }}'
    vswitch_name: 'dvs_vmotion'
    portgroup_name: 'vmotion'
    enable_vmotion: True
    vlan_id: 0
    mtu: 9000
    network:
      type: 'static'
      ip_address: '192.168.1.2'
      subnet_mask: '255.255.255.0'
    state: 'present'
    validate_certs: '{{ validate_certs }}'
```

##### EXPECTED RESULTS
The VMKernel adapter would be created on the portgroup on the dvSwitch

##### ACTUAL RESULTS

```
<<ESXI HOSTNAME>> EXEC /bin/sh -c 'echo ~root && sleep 0'
<<ESXI HOSTNAME>> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681 `" && echo ansible-tmp-1532688960.84-255685453744681="` echo /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_vmkernel.py
<<ESXI HOSTNAME>> PUT /root/.ansible/tmp/ansible-local-2808hFnlDs/tmp3damAu TO /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681/vmware_vmkernel.py
<<ESXI HOSTNAME>> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681/ /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681/vmware_vmkernel.py && sleep 0'
<<ESXI HOSTNAME>> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681/vmware_vmkernel.py && sleep 0'
<<ESXI HOSTNAME>> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1532688960.84-255685453744681/ > /dev/null 2>&1 && sleep 0'
fatal: [<HOSTNAME>]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "enable_ft": null,
            "enable_mgmt": null,
            "enable_vmotion": true,
            "enable_vsan": null,
            "esxi_hostname": "<ESXI HOSTNAME>",
            "hostname": "<VCENTER HOSTNAME>",
            "ip_address": null,
            "mtu": 9000,
            "network": {
                "ip_address": "192.168.1.2",
                "subnet_mask": "255.255.255.0",
                "type": "static"
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "portgroup_name": "vmotion",
            "state": "present",
            "subnet_mask": null,
            "username": "<ACCOUNT NAME>",
            "validate_certs": false,
            "vlan_id": 0,
            "vswitch_name": "dvs_vmotion"
        }
    },

```
