### ISSUE TITLE
with_lines using with when given error

### ISSUE THREAD

**Issue by grb247** [ansible/ansible#43357]
##### SUMMARY

```
 - set_fact:
     existing_roles_file: "{{item}}"
   when: item | search("{{something}}")
   with_lines:  cat "{{path}}/to/file"
   ignore_errors: yes
```

Output is:

cat: /path/to/file: No such file or directory
fatal: [host_name]: FAILED! => {"failed": true, "msg": "lookup_plugin.lines(cat \"/path/to/filr\") returned 1"}

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

with_lines and when 

##### ANSIBLE VERSION

```
"Ansible 2.4.0.0 "
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
