### ISSUE TITLE
"msg": "proxmoxer required for this module" Ansible+virtualenv

### ISSUE THREAD

**Issue by s2504s** [ansible/ansible#43360]
##### SUMMARY

Get this issue if use ansible-playbook inside virtualenv
(I think issue with required modules for the ansible module proxmox_kvm)
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```
ansible==2.4.2.0
asn1crypto==0.24.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
cryptography==2.3
docker-py==1.10.6
docker-pycreds==0.3.0
enum34==1.1.6
idna==2.7
ipaddress==1.0.22
Jinja2==2.10
MarkupSafe==1.0
paramiko==2.4.1
passlib==1.6.5
proxmoxer==1.0.2
pyasn1==0.4.4
pycparser==2.18
PyNaCl==1.2.1
PyYAML==3.13
requests==2.19.1
six==1.11.0
urllib3==1.23
websocket-client==0.48.0
```
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /opt/1/infrastructure/ansible.cfg
  configured module search path = [u'/home/vs/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/1/infrastructure/venv/local/lib/python2.7/site-packages/ansible
  executable location = /opt/1/infrastructure/venv/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
DEFAULT_HASH_BEHAVIOUR(/opt/1/infrastructure/ansible.cfg) = merge
DEFAULT_HOST_LIST(/opt/1/infrastructure/ansible.cfg) = [u'/opt/1/infrastructure/inventory']
DEFAULT_ROLES_PATH(/opt/1/infrastructure/ansible.cfg) = [u'/opt/1/infrastructure/roles']
DEFAULT_TIMEOUT(/opt/1/infrastructure/ansible.cfg) = 60
HOST_KEY_CHECKING(/opt/1/infrastructure/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/1/infrastructure/ansible.cfg) = False
```
##### STEPS TO REPRODUCE

```bash
echo "passlib==1.6.5
proxmoxer==1.0.2
ansible==2.4.2.0
docker-py==1.10.6" > requirements.txt

mkdir -p venv
virtualenv -p python2 venv
source venv/bin/activate
pip install -r requirements.txt
source venv/bin/activate
(venv)  ansible-playbook -vvv playbook.yml
```

```yaml
- name: Test
  hosts: localhost
  gather_facts: False

  tasks:

  - name: Clone VM from template
    become: False
    local_action:
      module: proxmox_kvm
      api_user: test
      api_password: test
      api_host: test
      node: test
      name: test
      pool: test
      clone: true
      full: false
      vmid: 1
      timeout: 600
    register: output
```

##### EXPECTED RESULTS

Should works
##### ACTUAL RESULTS

```yaml
(venv) vs@hope:/opt/1/infrastructure(create_build)$ ansible-playbook -vvv playbooks/ps1.yml
ansible-playbook 2.4.2.0
  config file = /opt/1/infrastructure/ansible.cfg
  configured module search path = [u'/home/vs/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/1/infrastructure/venv/local/lib/python2.7/site-packages/ansible
  executable location = /opt/1/infrastructure/venv/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /opt/1/infrastructure/ansible.cfg as config file
Parsed /opt/1/infrastructure/inventory/inventory inventory source with ini plugin
 [WARNING]: Found both group and host with same name: localhost


PLAYBOOK: ps1.yml ********************************************************************************************************************************************************************
1 plays in playbooks/ps1.yml

PLAY [VARs preparation] **************************************************************************************************************************************************************
META: ran handlers

TASK [Clone VM from template] ********************************************************************************************************************************************************
task path: /opt/1/infrastructure/playbooks/ps1.yml:13
Using module file /opt/1/infrastructure/venv/local/lib/python2.7/site-packages/ansible/modules/cloud/misc/proxmox_kvm.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: vs
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461 `" && echo ansible-tmp-1532699921.94-257164652030461="` echo /home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461 `" ) && sleep 0'
<localhost> PUT /tmp/tmpQdWU5U TO /home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461/proxmox_kvm.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461/ /home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461/proxmox_kvm.py && sleep 0'
<localhost> EXEC /bin/sh -c '/opt/1/infrastructure/venv/bin/python /home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461/proxmox_kvm.py; rm -rf "/home/vs/.ansible/tmp/ansible-tmp-1532699921.94-257164652030461/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_cwKAFo/ansible_module_proxmox_kvm.py", line 703, in <module>
    from proxmoxer import ProxmoxAPI

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "acpi": true,
            "agent": null,
            "api_host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "args": null,
            "autostart": false,
            "balloon": 0,
            "bios": null,
            "boot": "cnd",
            "bootdisk": null,
            "clone": "True",
            "cores": 1,
            "cpu": "kvm64",
            "cpulimit": null,
            "cpuunits": 1000,
            "delete": null,
            "description": null,
            "digest": null,
            "force": null,
            "format": "qcow2",
            "freeze": null,
            "full": false,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": null,
            "keyboard": null,
            "kvm": true,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 512,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "net": null,
            "newid": null,
            "node": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "numa": null,
            "numa_enabled": null,
            "onboot": true,
            "ostype": "l26",
            "parallel": null,
            "pool": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protection": null,
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": null,
            "scsihw": null,
            "serial": null,
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": null,
            "tablet": false,
            "target": null,
            "tdf": null,
            "template": false,
            "timeout": 600,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "std",
            "virtio": null,
            "vmid": 1,
            "watchdog": null
        }
    },
    "msg": "proxmoxer required for this module"
}

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

```

```
