### ISSUE TITLE
mysql_user user creation fails on MariaDB 10.3 when using host: localhost

### ISSUE THREAD

**Issue by dwagelaar** [ansible/ansible#43361]
##### SUMMARY

When creating a new user ("zabbix_monitor") with mysql_user on MariaDB 10.3 (MariaDB-server-10.3.7-1.el7.centos.x86_64), it fails under specific conditions with the error message included below.

We've traced it back to the following change in MariaDB: https://github.com/MariaDB/server/commit/84e14bff4a

Apparently, the Ansible mysql_user role already picks this up, EXCEPT when setting the host to "localhost" instead of "%". In other words, the following fails:
```
  mysql_user:
    login_user: "root"
    login_password: "***"
    name: "zabbix_monitor"
    host: "localhost"
    password: "***"
    priv: "*.*:PROCESS,SHOW DATABASES,EXECUTE,SELECT,SHOW VIEW,REPLICATION CLIENT,SUPER"
    state: present
```
...but this works:
```
  mysql_user:
    login_user: "root"
    login_password: "***"
    name: "zabbix_monitor"
    host: "%"
    password: "***"
    priv: "*.*:PROCESS,SHOW DATABASES,EXECUTE,SELECT,SHOW VIEW,REPLICATION CLIENT,SUPER"
    state: present
```
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hcadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -i /home/hcadmin/.ssh/id_rsa_ansible
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE

Run the task below:

```yaml
  mysql_user:
    login_user: "root"
    login_password: "***"
    name: "zabbix_monitor"
    host: "localhost"
    password: "***"
    priv: "*.*:PROCESS,SHOW DATABASES,EXECUTE,SELECT,SHOW VIEW,REPLICATION CLIENT,SUPER"
    state: present
```

##### EXPECTED RESULTS

mariadb user created/updated

##### ACTUAL RESULTS

error message:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'VERSIONING ROWS ON *.* FROM 'zabbix_monitor'@'localhost'' at line 1")
failed: [phrdb01.qa.careconnect.be] (item=zabbix_monitor) => {"changed": false, "item": {"host": "localhost", "name": "zabbix_monitor", "password": "***", "priv": "*.*:PROCESS,SHOW DATABASES,EXECUTE,SELECT,SHOW VIEW,REPLICATION CLIENT,SUPER"}, "msg": "(1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'VERSIONING ROWS ON *.* FROM 'zabbix_monitor'@'localhost'' at line 1\")"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/mysql/mysql_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Jmainguy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bmalynovytch** [comment]
@dwagelaar feel free to review & test #45355

**Comment by bmalynovytch** [comment]
@dwagelaar there's something strange in your example: the module doesn't contain any string with "VERSIONING ROWS", and privileges you're trying to apply don't either.

Could you double check that ?
@ansibot needs_info

**Comment by dwagelaar** [comment]
@bmalynovytch this error is the same as the initial report, and yes, we're not using that privilege anywhere; this is what lead us to https://github.com/MariaDB/server/commit/84e14bff4a : `grant delete versioning rows on...` became `grant delete history on...`. Is mysql_user.py first trying to remove all privileges before applying the specified privileges? Or does mysql_user.py only issue `GRANT DELETE VERSIONING ROWS ON *.* FROM 'zabbix_monitor'@'localhost'` when using host `localhost` (and not `%`)?

**Comment by bmalynovytch** [comment]
@dwagelaar tried with `MariaDB 10.3.9` on `Debian stretch`, with the fix included in #45355 and it worked just fine:

```
- mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_secrets.users.root.passwd }}"
    name: "zabbix_monitor"
    host: "localhost"
    password: "super strong password"
    priv: "*.*:PROCESS,SHOW DATABASES,EXECUTE,SELECT,SHOW VIEW,REPLICATION CLIENT,SUPER"
    state: present
```

```
TASK [mariadb-server : mysql_user] ***************************************************************************************************************************
task path: roles/mariadb-server/tasks/config.yml:40
ok: [xxx1] => {"changed": false, "user": "zabbix_monitor"}
changed: [xxx3] => {"changed": true, "user": "zabbix_monitor"}
ok: [xxx2] => {"changed": false, "user": "zabbix_monitor"}
```
Nodes are running in cluster, that's why there is only one "changed" task.

As said earlier, the module doesn't even include the privilege string that is mentioned in your error message.
Could you check yours ?
`grep -Ri VERSIONING /home/hcadmin/.ansible/plugins/modules /usr/share/ansible/plugins/modules /usr/lib/python2.7/site-packages/ansible | egrep '/mysql_'`
