### ISSUE TITLE
nsupdate handling record values with spaces

### ISSUE THREAD

**Issue by Nothing4You** [ansible/ansible#43380]
##### SUMMARY
When adding a record with values with spaces, for example a TXT record with SPF data like `"v=spf1 mx -all"` it will currently be added as `"v=spf1" "mx" "-all"`. This results in being finally parsed as  `v=spf1mx-all`, breaks the syntax of the record and I wouldn't consider this intuitive behavior.
As I found on https://stackoverflow.com/a/17255241 when double-quoting the record value like `'"v=spf1 mx -all"'` it will properly create the record.

If this is expected behavior it should be documented. Otherwise we should probably wrap it in the nsupdate module.

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION
```
2.7
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
- name: "create spf txt record for {{ record }}"
  nsupdate:
    key_name: "{{ nsupdate_key_name }}"
    key_secret: "{{ nsupdate_key_secret }}"
    key_algorithm: "{{ nsupdate_key_algorithm }}"

    server: "{{ nsupdate_server | default('localhost') }}"
    state: "present"

    record: "{{ record }}"
    type: "txt"
    value: "v=spf1 mx -all"
    ttl: 300
```

##### EXPECTED RESULTS
TXT record with value `"v=spf1 mx -all"`

##### ACTUAL RESULTS
TXT record with value `"v=spf1" "mx" "-all"`
