### ISSUE TITLE
terraform module ignores state_file when doing state present

### ISSUE THREAD

**Issue by Titerote** [ansible/ansible#43407]
##### SUMMARY

When doing a task for state: present in the terraform module , the state_file I provide get's ignored and it's not used at all. If the file does not exist, the task errors indicating that the file does not exist, but if it exists, a new state file is created in the project_path under the name terraform.tfstate

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

terraform
##### ANSIBLE VERSION

```
[tite@localhost terraform.bug]$ ansible --version
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tite/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION

[tite@localhost terraform.bug]$ ansible-config dump --only-changed | grep -v "" | wc -l
0

##### OS / ENVIRONMENT

Fedora 28
##### STEPS TO REPRODUCE

1. Create a .tf file under a path. doesn't matter the path name nor the content of the file
2. Create an infra directory where to point plan and state files using absolute paths
3. Create the  play with 2 tasks. One to plan, and the other to apply the plan
4. run play

```yaml
[tite@localhost terraform.bug]$ cat <<EOF> src/test.tf
resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "echo say hello world"
  }
}
EOF

[tite@localhost terraform.bug]$ cat <<EOF> test-play.yml
---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Planning terraform 
      terraform:
        binary_path: "/home/tite/bin/terraform"
        plan_file: "/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfplan"
        project_path: "src/"
        state: planned
        force_init: yes

    - name: Applying terraform 
      terraform:
        binary_path: "/home/tite/bin/terraform"
        plan_file: "/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfplan"
        state_file: "/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfstate"
        project_path: "src/"
        state: present
EOF


```

##### EXPECTED RESULTS

A new state file within the infra directory created

##### ACTUAL RESULTS

The state file was created with a different name, and an error happened

```
[tite@localhost terraform.bug]$ ansible-playbook test-play.yml -vvvv
ansible-playbook 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tite/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test-play.yml *********************************************************************************************************************************************************************
1 plays in test-play.yml

PLAY [localhost] ****************************************************************************************************************************************************************************
META: ran handlers

TASK [Planning terraform] *******************************************************************************************************************************************************************
task path: /home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/test-play.yml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tite
<127.0.0.1> EXEC /bin/sh -c 'echo ~tite && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683 `" && echo ansible-tmp-1532899680.52-130701866309683="` echo /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/misc/terraform.py
<127.0.0.1> PUT /home/tite/.ansible/tmp/ansible-local-31104X0vmjp/tmpkcLk7y TO /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683/terraform.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683/ /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683/terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683/terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/tite/.ansible/tmp/ansible-tmp-1532899680.52-130701866309683/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: Could not get Terraform outputs. This usually means none have been defined. stdout:  stderr: The module root could not be found. There is nothing to output.

ok: [localhost] => {
    "changed": false, 
    "command": "/home/tite/bin/terraform -lock=true /home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfplan", 
    "invocation": {
        "module_args": {
            "binary_path": "/home/tite/bin/terraform", 
            "force_init": true, 
            "lock": true, 
            "lock_timeout": null, 
            "plan_file": "/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfplan", 
            "project_path": "src/", 
            "state": "planned", 
            "state_file": null, 
            "targets": [], 
            "variables": null, 
            "variables_file": null
        }
    }, 
    "outputs": {}, 
    "state": "planned", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}

TASK [Applying terraform] *******************************************************************************************************************************************************************
task path: /home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/test-play.yml:15
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tite
<127.0.0.1> EXEC /bin/sh -c 'echo ~tite && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118 `" && echo ansible-tmp-1532899683.66-87800517313118="` echo /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/misc/terraform.py
<127.0.0.1> PUT /home/tite/.ansible/tmp/ansible-local-31104X0vmjp/tmpvnTKzd TO /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118/terraform.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118/ /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118/terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118/terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/tite/.ansible/tmp/ansible-tmp-1532899683.66-87800517313118/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "binary_path": "/home/tite/bin/terraform", 
            "force_init": false, 
            "lock": true, 
            "lock_timeout": null, 
            "plan_file": "/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfplan", 
            "project_path": "src/", 
            "state": "present", 
            "state_file": "/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfstate", 
            "targets": [], 
            "variables": null, 
            "variables_file": null
        }
    }, 
    "msg": "Could not find state_file \"/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/infra/ansible-terraform.tfstate\", check the path and try again."
}
	to retry, use: --limit @/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/test-play.retry

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   


```
