### ISSUE TITLE
terraform module errors out when using relative path in plan_file

### ISSUE THREAD

**Issue by Titerote** [ansible/ansible#43405]
##### SUMMARY

While using the terraform module, with a state of planned. If I set up a relative path for the plan_file, a new plan file gets created in the project_path directory , but the task fails with an error message. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

terraform
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/tite/Proyectos/h.tite.as/inmutable-infra/opennebula/ansible.cfg
  configured module search path = [u'/home/tite/Proyectos/h.tite.as/inmutable-infra/opennebula/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION

[tite@localhost terraform.bug]$ ansible-config dump --only-changed | grep -v "" | wc -l
0

##### OS / ENVIRONMENT

Fedora 28

##### STEPS TO REPRODUCE

1. Create a .tf file under a path. doesn't matter the path name nor the content of the file
2. Create the following play with a task to plan that file, using a relative plan_file  
3. run play

```yaml

[tite@localhost terraform.bug]$ cat <<EOF> src/test.tf
resource "null_resource" "test" {


  provisioner "local-exec" {
    command = "echo say hello world"
  }
}
EOF  

[tite@localhost terraform.bug]$ cat <<EOF> my-test.yml
---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Planning terraform 
      terraform:
        binary_path: "/home/tite/bin/terraform"
        plan_file: "ansible-terraform.tfplan"
        project_path: "src/"
        state: planned
        force_init: yes
EOF

[tite@localhost terraform.bug]$ ansible-playbook my-test.yml 

```

##### EXPECTED RESULTS

plan file to be created with the name I provided, and no errors issued

##### ACTUAL RESULTS

the task finished in error complaining about the plan_file

```
[tite@localhost terraform.bug]$ ansible-playbook my-test.yml -vvvv
ansible-playbook 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tite/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: my-test.yml ***********************************************************************************************************************************************************************
1 plays in my-test.yml

PLAY [localhost] ****************************************************************************************************************************************************************************
META: ran handlers

TASK [Planning terraform] *******************************************************************************************************************************************************************
task path: /home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/my-test.yml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tite
<127.0.0.1> EXEC /bin/sh -c 'echo ~tite && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674 `" && echo ansible-tmp-1532898229.5-235169003776674="` echo /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/misc/terraform.py
<127.0.0.1> PUT /home/tite/.ansible/tmp/ansible-local-29096zoOtC_/tmpB0Puzf TO /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674/terraform.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674/ /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674/terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674/terraform.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/tite/.ansible/tmp/ansible-tmp-1532898229.5-235169003776674/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "binary_path": "/home/tite/bin/terraform", 
            "force_init": true, 
            "lock": true, 
            "lock_timeout": null, 
            "plan_file": "ansible-terraform.tfplan", 
            "project_path": "src/", 
            "state": "planned", 
            "state_file": null, 
            "targets": [], 
            "variables": null, 
            "variables_file": null
        }
    }, 
    "msg": "Could not find plan_file \"ansible-terraform.tfplan\", check the path and try again."
}
	to retry, use: --limit @/home/tite/Proyectos/h.tite.as/inmutable-infra/terraform.bug/my-test.retry

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```
