### ISSUE TITLE
aci_switch_policy_vpc_protection_group reports "changed" everytime it runs

### ISSUE THREAD

**Issue by smnmtzgr** [ansible/ansible#43412]
##### SUMMARY
aci_switch_policy_vpc_protection_group reports "changed" status back everytime it runs. It makes no difference if the protection_group already exists on APIC or not. The ansible module status shows changed permanently after every run.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aci_switch_policy_vpc_protection_group

##### ANSIBLE VERSION
Ansible 2.6.1
```
$ ansible --version
ansible 2.6.1
```
##### STEPS TO REPRODUCE
```yaml
- name: Set login credentials
  set_fact:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'

- name: Create virtual port channels
  aci_switch_policy_vpc_protection_group:
    <<: *aci_login
    protection_group: VPC_LEAF-ACI-101-102
    protection_group_id: 102
    switch_1_id: 101
    switch_2_id: 102
    state: present
```
##### EXPECTED RESULTS
The expected result would be a "changed" status at first run (if protection group was not already there). After creating the status should be "ok" in following ansible-playbook runs.

##### ACTUAL RESULTS
Status of the module shows changed every time.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/aci/aci_switch_policy_vpc_protection_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/aci/aci_switch_policy_vpc_protection_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @brunocalogero @dagwieers @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @smnmtzgr,

Thank you for the issue, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in #ansible-network on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@jmcgill298 After debugging this, it seems what we send is only one switch, not both. I think that's where comparing both seem to go wrong.
```yaml
changed: [localhost] => {
    "changed": true, 
    "current": [
        {
            "fabricExplicitGEp": {
                "attributes": {
                    "dn": "uni/fabric/protpol/expgep-VPC_LEAF-ACI-101-102", 
                    "id": "102", 
                    "name": "VPC_LEAF-ACI-101-102"
                }, 
                "children": [
                    {
                        "fabricNodePEp": {
                            "attributes": {
                                "descr": "", 
                                "id": "902", 
                                "name": "", 
                                "nameAlias": "", 
                                "podId": "1"
                            }
                        }
                    }, 
                    {
                        "fabricNodePEp": {
                            "attributes": {
                                "descr": "", 
                                "id": "901", 
                                "name": "", 
                                "nameAlias": "", 
                                "podId": "1"
                            }
                        }
                    }, 
                    {
                        "fabricRsVpcInstPol": {
                            "attributes": {
                                "tnVpcInstPolName": ""
                            }
                        }
                    }
                ]
            }
        }
    ], 
    "filter_string": "?rsp-prop-include=config-only&rsp-subtree-class=fabricRsVpcInstPol,fabricNodePEp&rsp-subtree=full", 
    "invocation": {
        "module_args": {
            "certificate_name": null, 
            "host": "sandboxapicdc.cisco.com", 
            "output_level": "debug", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "private_key": null, 
            "protection_group": "VPC_LEAF-ACI-101-102", 
            "protection_group_id": 102, 
            "protocol": "https", 
            "state": "present", 
            "switch_1_id": 901, 
            "switch_2_id": 902, 
            "timeout": 30, 
            "use_proxy": false, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false, 
            "vpc_domain_policy": null
        }
    }, 
    "method": "POST", 
    "previous": [
        {
            "fabricExplicitGEp": {
                "attributes": {
                    "dn": "uni/fabric/protpol/expgep-VPC_LEAF-ACI-101-102", 
                    "id": "102", 
                    "name": "VPC_LEAF-ACI-101-102"
                }, 
                "children": [
                    {
                        "fabricNodePEp": {
                            "attributes": {
                                "descr": "", 
                                "id": "902", 
                                "name": "", 
                                "nameAlias": "", 
                                "podId": "1"
                            }
                        }
                    }, 
                    {
                        "fabricNodePEp": {
                            "attributes": {
                                "descr": "", 
                                "id": "901", 
                                "name": "", 
                                "nameAlias": "", 
                                "podId": "1"
                            }
                        }
                    }, 
                    {
                        "fabricRsVpcInstPol": {
                            "attributes": {
                                "tnVpcInstPolName": ""
                            }
                        }
                    }
                ]
            }
        }
    ], 
    "proposed": {
        "fabricExplicitGEp": {
            "attributes": {
                "id": "102", 
                "name": "VPC_LEAF-ACI-101-102", 
                "rn": "expgep-VPC_LEAF-ACI-101-102"
            }, 
            "children": [
                {
                    "fabricNodePEp": {
                        "attributes": {
                            "id": "901", 
                            "podId": "1"
                        }
                    }
                }, 
                {
                    "fabricNodePEp": {
                        "attributes": {
                            "id": "902", 
                            "podId": "1"
                        }
                    }
                }
            ]
        }
    }, 
    "response": "OK (30 bytes)", 
    "sent": {
        "fabricExplicitGEp": {
            "attributes": {
                "rn": "expgep-VPC_LEAF-ACI-101-102"
            }, 
            "children": [
                {
                    "fabricNodePEp": {
                        "attributes": {
                            "id": "901"
                        }
                    }
                }
            ]
        }
    }, 
    "status": 200, 
    "url": "https://sandboxapicdc.cisco.com/api/mo/uni/fabric/protpol/expgep-VPC_LEAF-ACI-101-102.json"
}
```
In contrast to using **aci_rest** which does not compare, but simply trusts the APIC's idempotency.
```yaml
ok: [localhost] => {
    "changed": false, 
    "imdata": [], 
    "invocation": {
        "module_args": {
            "certificate_name": null, 
            "content": {
                "fabricExplicitGEp": {
                    "attributes": {
                        "rn": "expgep-VPC_LEAF-ACI-101-102"
                    }, 
                    "children": [
                        {
                            "fabricNodePEp": {
                                "attributes": {
                                    "id": "901", 
                                    "rn": "nodepep-901"
                                }
                            }
                        }, 
                        {
                            "fabricNodePEp": {
                                "attributes": {
                                    "id": "902", 
                                    "rn": "nodepep-902"
                                }
                            }
                        }
                    ]
                }
            }, 
            "host": "sandboxapicdc.cisco.com", 
            "method": "post", 
            "output_level": "debug", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "path": "api/mo/uni/fabric/protpol/expgep-VPC_LEAF-ACI-101-102.json", 
            "port": null, 
            "private_key": null, 
            "protocol": "https", 
            "src": null, 
            "timeout": 30, 
            "use_proxy": false, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "method": "POST", 
    "response": "OK (30 bytes)", 
    "status": -1, 
    "totalCount": 0, 
    "url": "https://sandboxapicdc.cisco.com/api/mo/uni/fabric/protpol/expgep-VPC_LEAF-ACI-101-102.json?rsp-subtree=modified"
}
```
Here is the playbook I have been using to test the above:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create virtual port channels
    aci_switch_policy_vpc_protection_group:
      host: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: '{{ aci_validate_certs | default(false) }}'
      use_ssl: '{{ aci_use_ssl | default(true) }}'
      use_proxy: '{{ aci_use_proxy | default(true) }}'
      output_level: debug
      protection_group: VPC_LEAF-ACI-101-102
      protection_group_id: 102
      switch_1_id: 901
      switch_2_id: 902
      state: present

  - name: Create virtual port channels
    aci_rest:
      host: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: '{{ aci_validate_certs | default(false) }}'
      use_ssl: '{{ aci_use_ssl | default(true) }}'
      use_proxy: '{{ aci_use_proxy | default(true) }}'
      output_level: debug
      method: post
      path: /api/mo/uni/fabric/protpol/expgep-VPC_LEAF-ACI-101-102.json
      content:
        "fabricExplicitGEp": {
            "attributes": {
                "rn": "expgep-VPC_LEAF-ACI-101-102"
            },·
            "children": [
                {
                    "fabricNodePEp": {
                        "attributes": {
                            "id": "901",·
                            "rn": "nodepep-901"
                        }
                    }
                },·
                {
                    "fabricNodePEp": {
                        "attributes": {
                            "id": "902",·
                            "rn": "nodepep-902"
                        }
                    }
            ]
        }
```
