### ISSUE TITLE
with_lines fires before when

### ISSUE THREAD

**Issue by grb247** [ansible/ansible#43411]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
I am running using Anisble Tower above 4.0.0
```

##### STEPS TO REPRODUCE

```yaml
hosts: localhost
tasks:
action: debug msg={{ foo }}
when: foo is defined
with_lines:
cat /this/path/to/file
```

##### EXPECTED RESULTS

Should run line by line file exists

##### ACTUAL RESULTS

It's work fine when i run on local server but come up with error while running using ansible tower
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug msg={{foo}}] *****************************************************
cat: /this/doesnt/exist: No such file or directory
fatal: [localhost] => lookup_plugin.lines(cat /this/path/to/filet) returned 1

```

```
