### ISSUE TITLE
dellos6_config sends too many characters in answer to prompt causing failure

### ISSUE THREAD

**Issue by jaapie** [ansible/ansible#43410]
##### SUMMARY
When using the option in dellos6_config to save the configuration changes, the word "yes" is passed as an answer to the prompt "Are you sure you want to save? (y/n)". The first character is read by the prompt handler and although the command succeeds on the switch (as per the output below), Ansible returns a failure because the "es" is not read and is instead interpreted as another command.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
dellos6_config

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jacob/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### OS / ENVIRONMENT

OS: Ubuntu 18.04
Device: Dell N2000 Series switch on 6.3.3.9 firmware

##### STEPS TO REPRODUCE

1. Configure your Ansible inventory with a group called `switches` within which is a Dell N2000 Series switch.
2. Run the playbook below. Note: specifying `save: yes` or `save: y` has the same effect.

```yaml
---
- hosts: switches
  name: set-default-config
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "setting switch default configuration"
    dellos6_config:
      backup: yes
      save: yes
      src: default-switch-configuration.conf
    register: updates

  - debug: msg={{updates}}
```
3. Observe the error listed below.

NB:
Running the following playbook works when specifying `answer: "y"` but fails with the same error as before when one specifies `answer: "yes"`.
```yaml
---
- hosts: switches
  connection: network_cli
  gather_facts: no

  tasks:
  - name: "Copy running-config to startup-config for the Dell EMC OS6 Device"
    dellos6_config:
      commands:
        - command: do copy running-config startup-config
          prompt: '\(y/n\)\s?$'
          answer: "y"
    register: handle_prompt

  - debug: var=handle_prompt
```

##### EXPECTED RESULTS

Expected result was a successful run

##### ACTUAL RESULTS

`fatal: [switch01]: FAILED! => {"changed": false, "msg": "\r\nThis operation may take few minutes.\r\nManagement interfaces will not be available during this time.\r\n\r\nAre you sure you want to save? (y/n) y\r\n\r\nConfiguration Saved!\r\nswitch01#es\r\n             ^\r\n% Invalid input detected at '^' marker.\r\n\r\nswitch01#", "rc": -32603}`
