### ISSUE TITLE
parse json inside command?

### ISSUE THREAD

**Issue by cloudbluedigital** [ansible/ansible#43413]
##### SUMMARY
I am trying to trigger a command and one of the parameters require json

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/Users/arthur/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arthur/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/arthur/Library/Python/2.7/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

Mac sierraOS

##### STEPS TO REPRODUCE

```yaml
    - name: Create Route53
      command: aws route53 change-resource-record-sets --hosted-zone-id idhere --change-batch '{ "Comment": "Testing creating a record set", "Changes": [ { "Action": "CREATE", "ResourceRecordSet": { "Name": "{{ loadbalancer.stdout }}", "Type": "A", "AliasTarget": { "HosterZoneId": "{{ loadbalancer.stdout }}", "DNSName": "Hello" }}}]}'
      register: name
```

##### EXPECTED RESULTS

Command to execute
##### ACTUAL RESULTS

```
➜  scripts git:(develop) ✗ ansible-playbook ./init-playbook.yml -i hostsERROR! Syntax Error while loading YAML.  mapping values are not allowed here

The error appears to have been in '/Users/arthur/Sites/incase-api2.0/scripts/init-playbook.yml': line 237, column 115, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Create Route53
      command: aws route53 change-resource-record-sets --hosted-zone-id Z2JR0UJM8JL7N5 --change-batch '{ "Comment": "Testing creating a record set", "Changes": [ { "Action": "CREATE", "ResourceRecordSet": { "Name": "{{ loadbalancer.stdout }}", "Type": "A", "AliasTarget": { "HosterZoneId": "{{ loadbalancer.stdout }}", "DNSName": "Hello" }}}]}'
                                                                                                                  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```
