### ISSUE TITLE
Create a VMware connection plugin

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#43428]
##### SUMMARY
Nowadays we are moving towards connection plugins and inventory-based connection information.

This would have a few benefits:
- Connection information is stored in the inventory (cleaner)
- Modules no longer require repeated connection-parameters when called (cleaner)
- The connection is made to persist over tasks (more efficient)
- The connection can survive network-related issues without affecting playbook run (reliable)
- Facts gathering would be supported (so a set of standard facts could be exposed to playbooks)
- Additional connection-related features (e.g. proxy-support) could be supported #42221

PS This is not the same as the VMware VM connection plugin discussed in #38648

The inventory would look like:
```yaml
all:
    vcenter01:
        ansible_host: 10.1.2.1
        ansible_connection: vmware
        ansible_user: admin
        ansible_password: SuperSecret
        proxy_env:
          http_proxy: http://proxy.example.com:8080
```

And a typical playbook would be like:
```yaml
- hosts: vcenter01
  tasks:
  - vmware_datacenter:
      datacenter: dc01
      state: present

  - vmware_cluster:
      datacenter: dc01
      cluster: cl01
      enable_ha: yes
      enable_drs: yes
      enable_vsan: yes
      state: present
```

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
VMware modules

##### ANSIBLE VERSION
v2.8
