### ISSUE TITLE
aci_interface_policy_leaf_policy_group query with lag_type "link" returns "link" and "node" policy_groups

### ISSUE THREAD

**Issue by smnmtzgr** [ansible/ansible#43422]
##### SUMMARY
When using the ansible module aci_interface_policy_leaf_policy_group and doing a query against APIC with lag_type set to "link" the module returns policy groups with lagT=link and also with lagT=node. The correct behaviour would be only to return lagT=link, like specified with the module parameter lag_type.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aci_interface_policy_leaf_policy_group

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.6.1
```

##### STEPS TO REPRODUCE
```yaml
- name: query all Leaf Port-Channel Port Policy Groups of type leaf
  aci_interface_policy_leaf_policy_group:
    <<: *aci_login
    lag_type: link
    state: query
  register: pg_link_apic

- debug:
     msg: '{{ pg_link_apic }}'
```

##### EXPECTED RESULTS
The correct behaviour would be to return only lagT=link, like specified with the module parameter lag_type.

##### ACTUAL RESULTS
Policy groups with lagT=link and/or lagT=node are returned.

**Comment by smnmtzgr** [comment]
I also noticed that the other way round the same "bug" exists: when setting lag_type: node a query returns also both types: link and node.

**Comment by ansibot** [comment]
cc @brunocalogero @dagwieers @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@smnmtzgr You are right. I think when it was implemented querying by lag_type was simply not considered, but since the lag_type is now required for determining what ACI class to use, we would need to take it into account for filtering by type. Can you test #43441 for me ?

BTW Currently there's also no support for the lag_type **not-aggregated**, do you think that makes sense to support as well ? See: https://pubhub.devnetcloud.com/media/apic-mim-ref-321/docs/MO-infraAccBndlGrp.html#lagT

cc @brunocalogero @jmcgill298 @rsmeyers

**Comment by smnmtzgr** [comment]
I have tested [https://github.com/ansible/ansible/pull/43441](url), but still notice the same problem.

**Comment by dagwieers** [comment]
@smnmtzgr Ok, I found the problem and it seems the current framework did not support filtering when no object was specified. It simply didn't support that use-case. I have rewritten the framework, but I will have to update all modules to bring them in line with the required changes :-/

This will take some time, as also all integration tests have to be revisited...

**Comment by dagwieers** [comment]
@jmcgill298 Can you review these changes ? I haven't updated all integration tests yet, but most will work out of the box.

**Comment by dagwieers** [comment]
@smnmtzgr I merged my rewrite of the construct_url framework. It should implement what's needed for filtering out the correct nodes. I identified a few areas where the code could be improved further, but it doesn't affect any of the current modules. Feedback appreciated!

**Comment by smnmtzgr** [comment]
@dagwieers So which PR/Branch should I install to test your change?

**Comment by dagwieers** [comment]
Now that it is merged, that would be the **devel** branch.

**Comment by smnmtzgr** [comment]
I installed the ansible-devel branch and tested it but still get lagT: node also returned when doing this:

```yaml
# Policy Groups (type=link -> Port-Channel)
- name: query all Leaf Port-Channel Port Policy Groups of type link
  aci_interface_policy_leaf_policy_group:
    <<: *aci_login
    lag_type: link
    state: query
  register: pg_link_apic
```

And i also still get back lagT: link when doing this:
```yaml
# Policy Groups (type=link -> virtual Port-Channel)
- name: query all Leaf virtual Port-Channel Port Policy Groups of type node
  aci_interface_policy_leaf_policy_group:
    <<: *aci_login
    lag_type: node
    state: query
  register: pg_node_apic
```

For me it looks like the issue isnt fixed.
