### ISSUE TITLE
VMware: new module: vmware_guest_attribute_defs

### ISSUE THREAD

**Issue by jwebb1125** [ansible/ansible#43443]
##### SUMMARY

Module does not list custom attributes as stated in the module code

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest_custom_attribute_defs

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/jtwebb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jtwebb/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = [u'/Users/jtwebb/hosts']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False

##### OS / ENVIRONMENT

Mac High Sierra 10.13.6 

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: List Custom Attribute Definitions
      vmware_guest_custom_attribute_defs:
        hostname: csc-p-vsphere
        username: ansibleauth
        password: "{{ vmware_password }}"
        validate_certs: False
        state: list
      register: ca

    - debug: var=ca
```

##### EXPECTED RESULTS

The task to succeed as written in the module description to add, remove and list custom attributes definitions for the given virtual machine from VMWare.

##### ACTUAL RESULTS

```
CSCC02V300MHTDD:personal_playbooks jtwebb$ ansible-playbook list_vm_custom_attribute.yml
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a
list of hosts and/or paths to inventory sources , use ANSIBLE_INVENTORY instead. This
feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'


PLAY [localhost] **************************************************************************

TASK [List Custom Attribute Definitions] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, present, got: list"}
	to retry, use: --limit @/Users/jtwebb/personal_playbooks/list_vm_custom_attribute.retry

PLAY RECAP ********************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
