### ISSUE TITLE
parted ignores warnings about too long GPT partition names

### ISSUE THREAD

**Issue by betelgeuse** [ansible/ansible#43476]
##### SUMMARY
The parted module happily accepts and ignores warnings about GPT partition names that are longer than 36 characters.

"Each partition can also be given a descriptive name consisting of 36 characters."

https://www.thomas-krenn.com/en/wiki/GUID_Partition_Table

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### CONFIGURATION

No changed configs.

##### OS / ENVIRONMENT

N/A, Linux

##### STEPS TO REPRODUCE

```yaml
- name: setup grub boot
  parted:
    device: /dev/disk
    number: 1
    part_start: 1MiB
    part_end: 3MiB
    label: gpt
    name: "248842ec98e74f0604f716401518cdc248842ec98e74f0604f716401518cdc"
    flags: [ bios_grub ]
    state: present
```

##### EXPECTED RESULTS

The command should fail because the name is too long. When you run parted directly, you will you see this warning on too long names:

```
(parted) mkpart primary 1MiB 3MiB unit KiB name 1 '248842ec98e74f0604f716401518cdc248842ec98e74f0604f716401518cdc' set 1 bios_grub on
Warning: failed to translate partition name
```
##### ACTUAL RESULTS

```
changed: [ip] => {
    "changed": true, 
    "disk": {
        "dev": "/dev/disk", 
        "logical_block": 512, 
        "model": "Unknown", 
        "physical_block": 512, 
        "size": 500107608.0, 
        "table": "gpt", 
        "unit": "kib"
    }, 
    "invocation": {
        "module_args": {
            "align": "optimal", 
            "device": "/dev/disk", 
            "flags": [
                "bios_grub"
            ], 
            "label": "gpt", 
            "name": "248842ec98e74f0604f716401518cdc248842ec98e74f0604f716401518cdc", 
            "number": 1, 
            "part_end": "3MiB", 
            "part_start": "1MiB", 
            "part_type": "primary", 
            "state": "present", 
            "unit": "KiB"
        }
    }, 
    "partitions": [
        {
            "begin": 1024.0, 
            "end": 3072.0, 
            "flags": [
                "bios_grub"
            ], 
            "fstype": "", 
            "name": "248842ec98e74f0604f716401518cdc24884", 
            "num": 1, 
            "size": 2048.0, 
            "unit": "kib"
        }
    ], 
    "script": "unit KiB mkpart primary 1MiB 3MiB unit KiB name 1 '\"248842ec98e74f0604f716401518cdc248842ec98e74f0604f716401518cdc\"' set 1 bios_grub on"
}
```
