### ISSUE TITLE
Variables in tree inventory doesn't set propertly

### ISSUE THREAD

**Issue by Kamapcuc** [ansible/ansible#43484]
### ISSUE TYPE
 - Bug Report

### COMPONENT NAME
Playbook variables

### ANSIBLE VERSION
2.5.1

### STEPS TO REPRODUCE
My `inventory.yml` looks like:
```yaml
all:
  children:
    dev:
#.......................................
    prod:
      children:
#.......................................
        europe:
          children:
            funnel:
              hosts:
                server11:
                server12:
            game:
              hosts:
                server13:
                server14:
        singapore:
          children:
            funnel:
              hosts:
                server21:
                server22:
            game:
              hosts:
                server23:
                server24:
        usa:
          children:
            funnel:
              hosts:
                server31:
                server32:
            game:
              hosts:
                server33:
                server34:
```
In my variables directory i have such configuration:
```
+ group_vars
    + prod
        - europe.yml
        - singapore.yml
        - usa.yml
```
In each file i have only one variable `region: EU`, `region: SG` and `region: US`

I have simple playbook with one task:
```yaml
- debug:
    msg: "region is: {{ region }}"
```

So, when i run my playbook, i expect to see:
```
TASK [regional_dc : debug] ********************************************************************************************
ok: [server11] => {
    "msg": "region is: EU"
}
ok: [server21] => {
    "msg": "region is: SG"
}
ok: [server31] => {
    "msg": "region is: US"
}
```

But actual results is:
```
TASK [regional_dc : debug] ********************************************************************************************
ok: [server11] => {
    "msg": "region is: US"
}
ok: [server21] => {
    "msg": "region is: US"
}
ok: [server31] => {
    "msg": "region is: US"
}
```

Can you fix it, please?
