### ISSUE TITLE
Add support for redirect and fixed-response actions to elb_application_lb

### ISSUE THREAD

**Issue by jeffhunter** [ansible/ansible#43506]
##### SUMMARY

Add support for redirect and fixed-response actions to elb_application_lb

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

elb_application_lb

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Amazon has added support for redirect and fixed-response action to Application Load Balancers:

https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/

The ability to redirect HTTP to HTTPS directly in the load balancer is very useful, and elb_application_lb should support creating these actions.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/elb_application_lb.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/elb_application_lb.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @jeffhunter,

Thank you for the issue, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in #ansible-aws on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by randlet** [comment]
Quick workaround using command/awscli in case anyone else lands on this page wondering how to redirect http to https traffic with an application load balancer:

```yaml

    - name: "Create application load balancer"
      register: elb
      elb_application_lb:
        name: "{{ elb_name }}
        subnets: "{{ subnets }}"
        security_groups:
          - "{{ security_group }}"
        scheme: internet-facing
        listeners:
          - Protocol: HTTPS 
            Port: 443 
            DefaultActions:
                - Type: forward 
                  TargetGroupName: "{{ target_group.target_group_name }}"
            Certificates:
                - CertificateArn: "{{ ssl_cert_arn }}"
            SslPolicy: ELBSecurityPolicy-2015-05
        state: present

    - name: "Add http to https redirect listener to ALB"
      command: >
        aws elbv2 create-listener
        --load-balancer-arn {{ elb.load_balancer_arn }}
        --protocol HTTP
        --port 80
        --default-actions 'Type=redirect,RedirectConfig={Protocol=HTTPS,Port=443,Host="#{host}",Path="/#{path}",Query="#{query}",StatusCode=HTTP_301}'

```

**Comment by ewascent** [comment]
> - name: "Add http to https redirect listener to ALB" command: > aws elbv2 create-listener --load-balancer-arn {{ elb.load_balancer_arn }} --protocol HTTP --port 80 --default-actions 'Type=redirect,RedirectConfig={Protocol=HTTPS,Port=443,Host="#{host}",Path="/#{path}",Query="#{query}",StatusCode=HTTP_301}'

Eric copies the nice man's code.

**Comment by levisbakalinsky** [comment]
Any plans to add this functionality in future versions?

**Comment by emanuele-leopardi** [comment]
I was able to create Redirect from 80 to 443 with the following code:

```yaml
###Var Declaration

 application_load_balancers:
  - name: test-alb
    state: present
    security_groups:
      - test-lb
    subnets:
      - sub-a-pub
      - sub-b-pub
    listeners:
      - Protocol: HTTPS
        Port: 443
        DefaultActions:
          - Type: forward
            TargetGroupName: group-https-dev
        Certificates: 
          - CertificateArn: arn:aws:acm:eu-west-1:432791473407:certificate/92bb37f0-1f81-4b0e-bbec-f14326fdf666
        SslPolicy: ELBSecurityPolicy-2016-08
        Rules:
          - Conditions:
              - Field: host-header
                Values:
                  - 'auth-test.cloud.foo.bar.it'
            Priority: '2'
            Actions:
              - TargetGroupName: group-https-test
                Type: forward
          - Conditions:
              - Field: host-header
                Values:
                  - 'test.cloud.foo.bar.it'
            Priority: '1'
            Actions:
              - TargetGroupName: group-https-dev
                Type: forward
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: "443"
              Host: "#{host}"
              Path: "/#{path}"
              Query: "#{query}"
              StatusCode: "HTTP_301"
```

```yaml
#Playbook task

- name: create application load balancer
  elb_application_lb:
    name: "{{ application_load_balancer.name }}"
    security_groups: "{{ security_group_id_list }}"
    subnets: "{{ subnet_id_list }}"
    listeners: "{{ application_load_balancer.listeners }}"
    deletion_protection: yes
    state: present
```

the catch here is to pass the whole object completely described to the module.
Hope this helps others.

**Comment by mortalius** [comment]
And for fixed-response it work same way.
```
  DefaultActions:
    - Type: fixed-response
      FixedResponseConfig:
        ContentType: 'text/html'
        MessageBody: '<b>Nothing There</b>'
        StatusCode: '200'
```
And actually for any other type should work too. Just make Config block according to https://docs.aws.amazon.com/en_us/elasticloadbalancing/latest/APIReference/API_Action.html
