### ISSUE TITLE
Bug when Two blockinfile tasks have the same marker

### ISSUE THREAD

**Issue by whojes** [ansible/ansible#43523]
##### SUMMARY

If two blockinfile tasks have the same 'marker', second blockinfile's 'insertafter' does not work properly. The second blockinfile task ignores its noted 'insertafter' and assumes the first one's marker(end) as its insertafter.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

blockinfile

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

nothing special

##### STEPS TO REPRODUCE

```yaml
---
- name: test
  hosts: master
  gather_facts: false
  become: true
  tasks: 
    - name: copy template
      copy:
        src: "/root/installer/test.xml"
        dest: "/root"
    
    - name: template change 1
      blockinfile:
        path: "/root/test.xml"
        insertafter: "<!-- MARKER -->"
        marker: "<!-- insert here -->"
        block: |
          <test>test1</test>

    - name: template change 2
      blockinfile:
        path: "/root/test.xml"
        insertafter: "<!-- SECOND MARKER -->"
        marker: "<!-- insert here -->"
        block: |
          <test>test2</test>

# test.xml
#<!-- MARKER -->
#<p3>hello world</p3>
#<!-- SECOND MARKER -->
```

##### EXPECTED RESULTS

```
<!-- MARKER -->
<!-- insert here -->
<test>test1</test>
<!-- insert here -->
<p3>hello world</p3>
<!-- SECOND MARKER -->
<!-- insert here -->
<test>test2</test>
<!-- insert here -->
```
##### ACTUAL RESULTS

```
<!-- MARKER -->
<!-- insert here -->
<test>test1</test>
<!-- insert here -->
<test>test2</test>
<!-- insert here -->
<p3>hello world</p3>
<!-- SECOND MARKER -->
```
