### ISSUE TITLE
gcp_compute_disk lacks a field to specify 'disk type'

### ISSUE THREAD

**Issue by mmolinac** [ansible/ansible#43541]
##### SUMMARY
The module gcp_compute_disk doesn't have a field to specify the disk type we want a new disk to be, like `pd-standard` or `pd-ssd`.

However, `type` is a return value you get on success.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

gcp_compute_disk

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/mmolinac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

[defaults]
callback_whitelist = profile_roles
allow_world_readable_tmpfiles=True
host_key_checking = False
retry_files_enabled = False

[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
control_path_dir = /tmp/.ansible/cp

[diff]
always = yes
context = 6

##### OS / ENVIRONMENT

macOS High Sierra Version 10.13.6

##### STEPS TO REPRODUCE

```yaml
    - name: Launch samplehost persistent disk
      gcp_compute_disk:
        name:          samplehost01
        size_gb:       10
        source_image:  "projects/{{ image_project }}/global/images/family/{{ image }}"
        zone:          "{{ zone }}"
        project:       "{{ project_id }}"
        auth_kind:     'serviceaccount'
        service_account_file:  "{{ credentials_file }}"
        type:          'pd-ssd'
        scopes:
          - 'https://www.googleapis.com/auth/compute'
```

##### EXPECTED RESULTS

The disk should be created.

##### ACTUAL RESULTS

The disk failed to be created.

```
TASK [Launch samplehost persistent disk] ***********************************************************************************************************
Wednesday 01 August 2018  15:49:18 +0200 (0:00:02.583)       0:00:02.694 ****** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (gcp_compute_disk) module: type Supported parameters include: auth_kind, description, disk_encryption_key, licenses, name, project, scopes, service_account_email, service_account_file, size_gb, source_image, source_image_encryption_key, source_snapshot, source_snapshot_encryption_key, state, zone"}

```
