### ISSUE TITLE
validate can't be used while changing a syslog-ng include file

### ISSUE THREAD

**Issue by vossenjp** [ansible/ansible#43564]
##### SUMMARY

I'm editing a Syslog-NG `@include` file with "blockinfile" and I want to use `validate`.  That *requires* `%s` but running `syslog-ng -s -f %s` will and should FAIL, because the include file `/etc/syslog-ng/syslog-ng.local.conf` (note `.local`) is...an *include* file, it's really not valid by itself.  What I need to run is `syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf` but if I do that I get the error about requiring `%s`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

verify

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/.../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Using 2.3 (due to CentOS-5)

##### OS / ENVIRONMENT

Linux Mint 18, with a Python virtenv for Ansible, via PIP

##### STEPS TO REPRODUCE

```yaml
  - name: Turn off MyThing in syslog-ng.local.conf
    blockinfile:
      path:     '/etc/syslog-ng/syslog-ng.local.conf'
      state:    absent
      validate: "syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf #%s"
      marker:   "# {mark} ANSIBLE MANAGED BLOCK for MyThing"
      content:  ""
    notify: Restart syslog-ng
```

##### EXPECTED RESULTS

Validate should be able to run a valid command to validate the change.

##### ACTUAL RESULTS

What I need to run is `syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf` but if I do that I get:
```
FAILED! => {"changed": false, "failed": true, "msg": "validate must contain %s: syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf"}
```

However, if I try `validate: "syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf #%s"` or `validate: "syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf : %s"` or variations I get:
```
FAILED! => {"changed": false, "failed": true, "msg": "failed to validate: rc:1 error:Excess number of arguments\n"}
```

The `Excess number of arguments` error is coming from Syslog-NG itself, but the command works when I run it manually with comments.  I suspect the `validate` anti-injection features are messing with my `#` or `:` and confusing `syslog-ng -s -f`.

Running manually works:
```
$ sudo syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf # /etc/syslog-ng/syslog-ng.local.conf
$ echo $?
0

$ sudo syslog-ng -s -f /etc/syslog-ng/syslog-ng.conf /etc/syslog-ng/syslog-ng.local.conf
Excess number of arguments

$ echo $?
1
```
