### ISSUE TITLE
nxos_config - invalid command - error

### ISSUE THREAD

**Issue by drewk132** [ansible/ansible#43579]
##### SUMMARY

I am using the nxos_config module to push a bgp evpn vxlan configuration to multiple devices, and the playbook errors, specifying an invalid command.  I can manually copy and paste the file, and this works without issue.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_config

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/drew/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### CONFIGURATION

I modified the path for the inventory file, and moved the ansible.cfg file to the directory in which I am running my playbooks.

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS

##### STEPS TO REPRODUCE

```yaml
---
- name: APPLY CONFIGURATION TO NEXUS 92304 VTEP DEVICES
  hosts: vtep_92304s
  gather_facts: no
  connection: local

  tasks:
    - name: APPLY CONFIGURATION
      nxos_config:
        src: "/etc/ansible/drew/configs/{{inventory_hostname}}.cfg"
```

##### EXPECTED RESULTS

I expected the configuration file to be pushed to network devices.

##### ACTUAL RESULTS

the playbook fails and the logs show the following,

FAILED! => {"changed": false, "msg": "vn-segment 100100\r\r\n                                ^\r\n% Invalid command at '^' marker.\r\n\r

```

```
