### ISSUE TITLE
ec2_ami_facts should take nonstrings as filter arguments

### ISSUE THREAD

**Issue by tedder** [ansible/ansible#43570]
##### SUMMARY
Booleans or numbers passed to most AWS APIs need to be cast to strings or they die. (this *might* be better fixed in `ansible_dict_to_boto3_filter_list` than in `_facts`)

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_ami_facts

##### ANSIBLE VERSION

```
2.6.0
```

##### CONFIGURATION

not relevant

##### OS / ENVIRONMENT

not relevant

##### STEPS TO REPRODUCE

```yaml
- name: find
  ec2_ami_facts:
    region: "{{region}}"
    filters:
      architecture: x86_64
      is-public: true
      name: "amzn-ami-2018.03.c-amazon-ecs-optimized"
      owner-id: 591542846629 # amazon's id
```

The second and fourth lines are 'bad'- one is a number, one is a bool, both fail.

##### EXPECTED RESULTS

results to be returned.
I expected it to work.

##### ACTUAL RESULTS

It died.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Filters[2].Values, value: True, type: <class 'bool'>, valid types: <class 'list'>, <class 'tuple'>
fatal: [localhost]: FAILED! => {"changed": false, "msg": "error describing images: Parameter validation failed:\nInvalid type for parameter Filters[1].Values, value: 591542846629, type: <class 'int'>, valid types: <class 'list'>, <class 'tuple'>\nInvalid type for parameter Filters[2].Values, value: True, type: <class 'bool'>, valid types: <class 'list'>, <class 'tuple'>"}
```

(after fixing the bool)

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Filters[6].Values, value: 591542846629, type: <class 'int'>, valid types: <class 'list'>, <class 'tuple'>
fatal: [localhost]: FAILED! => {"changed": false, "msg": "error describing images: Parameter validation failed:\nInvalid type for parameter Filters[6].Values, value: 591542846629, type: <class 'int'>, valid types: <class 'list'>, <class 'tuple'>"}

```
