### ISSUE TITLE
Provide official snaps of latest releases

### ISSUE THREAD

**Issue by hifi** [ansible/ansible#43585]
##### SUMMARY
Ansible is not officially distributed as a snap and distribution packages lag behind the stable releases. It would be very helpful to have it directly packaged by the Ansible developers.

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

packaging

##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Any Linux distribution with `snapd` available.

##### STEPS TO REPRODUCE

The UX here would be `snap install ansible` rather than adding custom repositories etc.

##### EXPECTED RESULTS
Easier installation of latest Ansible.

##### ACTUAL RESULTS
Old releases available from package managers or adding custom repositories.

I do understand a PPA is available for Ubuntu and there are multiple other ways to install the latest Ansible but I would like to hear if it has been considered since searching didn't yield any results regarding snap packaging.

**Comment by ansibot** [comment]
@hifi Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Start of a `snapcraft.yaml`:

```yaml
name: ansible
version: 2.6.2
summary: Ansible
description: |
  SSH-based application deployment, configuration management, and IT orchestration platform

grade: stable
confinement: classic

apps:
  ansible:
    command: bin/ansible
  ansible-playbook:
    command: bin/ansible-playbook
  ansible-pull:
    command: bin/ansible-pull
  ansible-doc:
    command: bin/ansible-doc
  ansible-galaxy:
    command: bin/ansible-galaxy
  ansible-console:
    command: bin/ansible-console
  ansible-connection:
    command: bin/ansible-connection
  ansible-vault:
    command: bin/ansible-vault
  ansible-config:
    command: bin/ansible-config
  ansible-inventory:
    command: bin/ansible-inventory

parts:
  ansible:
    plugin: python
    source: https://releases.ansible.com/ansible/ansible-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - libc6
```

Build with `snapcraft`, install with `snap install --dangerous --classic ansible_2.6.2_amd64.snap`
