### ISSUE TITLE
module ios_l2_interface does not work on FastEthernet, TenGigabitEthernet & FortyGigabitEthernet interfaces

### ISSUE THREAD

**Issue by geertn444** [ansible/ansible#43582]
##### SUMMARY

When trying to configure a TenGigabit interface in trunk or access mode, you get the rather "strange" message:

"msg": "Ensure interface is configured to be a L2 port first before using this module. You can use the ios_interface module for this."

and this while the interface is in access or trunk mode.....

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_l2_interface.py
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/sha
re/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (R
ed Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

ansible tower
Linux ansible-tower 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018
 x86_64 x86_64 x86_64 GNU/Linux
##### STEPS TO REPRODUCE

```yaml
   - name: Ensure uplinks are trunk ports and ensure the vlan is allowed
      ios_l2_interface:
       name: TenGigabitEthernet1/0/1
       mode: trunk
       native_vlan: 999
       trunk_vlans: "{{ target_vlan_id }}"
```

##### EXPECTED RESULTS

interface is configured
##### ACTUAL RESULTS

playbook stops with message above

```

```__
