### ISSUE TITLE
Failure to insert rule when priority slot on existing NSG not taken

### ISSUE THREAD

**Issue by alexbaltman** [ansible/ansible#43622]
##### SUMMARY
Module does not insert new rules when purge left to default (which is 'no') or explicitly set.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_securitygroup

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### STEPS TO REPRODUCE

Create new sec group w/ default ruless plus one rule. I added this one manually in the portal:
priority 110, name: myNSGrule, port 5432, protocol any, src any, src port any, dest any dest port any, allow

The first example does not add a role, the second does, but cleans out existing rules, which is undesirable. 

```yaml

- azure_rm_securitygroup:
    name: "mysecgrp"
    resource_group: "myrsg"
    purge_rules: **no**
    rules:
      - name: "Postgresql_543"
        access: Allow
        priority: 120
        direction: Inbound
        destination_port_range: 543
        source_address_prefix: 192.168.0.20/32
        destination_address_prefix: 192.168.0.21/32

- azure_rm_securitygroup:
    name: "mysecgrp"
    resource_group: "myrsg"
    purge_rules: **yes**
    rules:
      - name: "Postgresql_543"
        access: Allow
        priority: 120
        direction: Inbound
        destination_port_range: 543
        source_address_prefix: 192.168.0.20/32
        destination_address_prefix: 192.168.0.21/32
```

##### EXPECTED RESULTS

I expect if the priority is not taken that a rule would be inserted into the existing security group.

##### ACTUAL RESULTS

Runs as normal, but it says changed=false and ok=1.

```

```
