### ISSUE TITLE
k8s_raw module shows openshift missing Python client even all dependencies are satisfied

### ISSUE THREAD

**Issue by aparedero** [ansible/ansible#43637]
##### SUMMARY
Trying to creating a configmap trough k8s_raw module it shows the following error, even satisfying dependencies and Python version:
```
fatal: [ansible_master]: FAILED! => {"changed": false, "msg": "This module requires the OpenShift Python client. Try `pip install openshift`"}
```
Dependencies in docs are openshift==0.4.3 , PyYAML>=3.11 and Python>=2.7
https://docs.ansible.com/ansible/2.5/modules/k8s_raw_module.html
This is my current libraries version:
```
$ pip freeze | grep openshift
openshift==0.4.3
$ pip freeze | grep PyYAML
PyYAML==3.13
```

```
- name: Loading Configmap
  k8s_raw:
    kubeconfig: "{{ KUBECONFIG_PATH | default(lookup('env', 'KUBECONFIG'), true) }}"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: consul-default-config
        namespace: '{{ K8S_NAMESPACE }}'
      data:
        consul_defaults.json: |-
          "{{ lookup('file', 'files/k8s_configmap_consul-defaults.json') }}"
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
k8s_raw

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /home/ec2-user/git/consul/deployK8s/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 16 2018, 18:20:07) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/ec2-user/git/consul/deployK8s/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/ec2-user/git/consul/deployK8s/ansible.cfg) = [u'/home/ec2-user/git/consul/deployK8s/inventory']
DEFAULT_LOG_PATH(/home/ec2-user/git/consul/deployK8s/ansible.cfg) = /home/ec2-user/git/consul/deployK8s/ansible.log
HOST_KEY_CHECKING(/home/ec2-user/git/consul/deployK8s/ansible.cfg) = False
```
##### OS / ENVIRONMENT
```
Amazon Linux 2 - 4.14.47-64.38.amzn2.x86_64
```
##### STEPS TO REPRODUCE
Execute k8s_raw module with any configuration. It seems does not launch

```yaml
- name: Loading Configmap
  k8s_raw:
    kubeconfig: "{{ KUBECONFIG_PATH | default(lookup('env', 'KUBECONFIG'), true) }}"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: consul-default-config
        namespace: '{{ K8S_NAMESPACE }}'
      data:
        consul_defaults.json: |-
          "{{ lookup('file', 'files/k8s_configmap_consul-defaults.json') }}"

```
##### EXPECTED RESULTS
Configmap was loaded into the cluster

##### ACTUAL RESULTS
```
File lookup using /home/ec2-user/git/consul/deployK8s/output/k8s_configmap_consul-defaults.json as file
Using module file /usr/lib/python2.7/site-packages/ansible/modules/clustering/k8s/_k8s_raw.py
<ansible_master> ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
<ansible_master> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [ansible_master]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_key": null, 
            "api_version": "v1", 
            "cert_file": null, 
            "context": null, 
            "definition": {
                "apiVersion": "v1", 
                "data": {
                    "consul_defaults.json": "\"{ \n  #Este configMap se cargará en K8s y es el que MENOS priroridad tiene.\n  acl_datacenter: \"\",\n  acl_down_policy: \"extend-cache\",\n  acl_ttl: 30,\n  acl_master_token: \"30657f6d-2222-3333-1111-000000000000\",\n  bootstrap_expect: 5\n}\""
                }, 
                "kind": "ConfigMap", 
                "metadata": {
                    "name": "consul-default-config", 
                    "namespace": "default"
                }
            }, 
            "force": false, 
            "host": null, 
            "key_file": null, 
            "kind": null, 
            "kubeconfig": "/aplicaciones/config/kubeconfigs/config-test", 
            "name": null, 
            "namespace": null, 
            "password": null, 
            "resource_definition": {
                "apiVersion": "v1", 
                "data": {
                    "consul_defaults.json": "\"{ \n  #Este configMap se cargará en K8s y es el que MENOS priroridad tiene.\n  acl_datacenter: \"\",\n  acl_down_policy: \"extend-cache\",\n  acl_ttl: 30,\n  acl_master_token: \"30657f6d-2222-3333-1111-000000000000\",\n  bootstrap_expect: 5\n}\""
                }, 
                "kind": "ConfigMap", 
                "metadata": {
                    "name": "consul-default-config", 
                    "namespace": "default"
                }
            }, 
            "src": null, 
            "ssl_ca_cert": null, 
            "state": "present", 
            "username": null, 
            "verify_ssl": null
        }
    }, 
    "msg": "This module requires the OpenShift Python client. Try `pip install openshift`"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/_k8s_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_k8s_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aparedero** [comment]
This is not deprecated module for managing kubernetes cluster

**Comment by fabianvf** [comment]
Are dependencies for other modules being picked up properly?

**Comment by fabianvf** [comment]
Also the deprecated tag is because k8s_raw was renamed to k8s in 2.6

**Comment by sahkaa** [comment]
same for me.
```
---
- name: Test
  strategy: free
  hosts:
  - k8s-deployment-group
  gather_facts: yes
  tasks:
  - name: Get a list of all service objects
    k8s:
      api_version: v1
      kind: ServiceList
      namespace: example-namespace
    register: output
```

**Comment by willthames** [comment]
This is usually because a different python is being run by ansible than expected (see also http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html)

Please run using `-vvv` so that we can see the python commands being executed

**Comment by aparedero** [comment]
@fabianvf I'm pretty sure I have all dependencies listed on docs.

Also, good to know the new name of the module. I'm still using v2.5 in some environments and also quich searching k8s_raw on google returns 2.5 version: 
 https://docs.ansible.com/ansible/2.5/modules/k8s_raw_module.html

**Comment by fabianvf** [comment]
@aparedero k8s_raw was aliased to k8s in 2.6 and the arguments to the module remain almost the same, so the transition should be painless, it will just emit warnings letting you know the alias might go away some day (not before 2.9 I think). All your existing tasks should work without modification, unless they are already working around a bug that was fixed.

**Comment by gomker** [comment]
@fabianvf  I am seeing this same error with Ansible 2.6.3 with `k8s` and `k8s_raw` ( I am attempting to migrate to the new `k8s` module)

```
TASK [ras-awx : install ingress] ***********************************************
task path: /var/lib/awx/projects/_189__ras_awx_dlane/ansible/roles/ras-awx/tasks/azure_ingress.yml:4
looking for "templates/ingress.yml.j2" at "/var/lib/awx/projects/_189__ras_awx_dlane/ansible/roles/ras-awx/templates/ingress.yml.j2"
File lookup using /var/lib/awx/projects/_189__ras_awx_dlane/ansible/roles/ras-awx/templates/ingress.yml.j2 as file
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453 `" && echo ansible-tmp-1535388051.74-177132428721453="` echo /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453 `" ) && sleep 0'
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/k8s/raw.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/k8s/__init__.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/k8s/common.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module file /var/lib/awx/venv/azure_env/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-955fbZIVX/tmpjky8_w TO /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453/k8s.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453/ /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453/k8s.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453/k8s.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1535388051.74-177132428721453/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => { ....

    "msg": "This module requires the OpenShift Python client. Try `pip install openshift`"
```

Playbook Task

```
- name: install ingress
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/ingress.yml.j2') | from_yaml }}"
```

Environment build (Docker Image for AWX with custom venv)

```
# Azure venv
RUN virtualenv /var/lib/awx/venv/azure_env
RUN /var/lib/awx/venv/azure_env/bin/pip install python-memcached psutil
RUN /var/lib/awx/venv/azure_env/bin/pip install requests[socks]
RUN /var/lib/awx/venv/azure_env/bin/pip install packaging
RUN /var/lib/awx/venv/azure_env/bin/pip install openshift==0.6
RUN /var/lib/awx/venv/azure_env/bin/pip install msrest==0.5.0
RUN /var/lib/awx/venv/azure_env/bin/pip install msrestazure==0.4.34
RUN /var/lib/awx/venv/azure_env/bin/pip install azure-cli
RUN /var/lib/awx/venv/azure_env/bin/pip install ansible==2.6.3
```

Checking the `venv` shows OpenShift installed

```
[root@awx azure_env]# source bin/activate
(azure_env) [root@awx azure_env]# pip list | grep openshift
openshift                             0.6.0
```
