### ISSUE TITLE
Ansible git action does not fetch the newest repo after rebasing

### ISSUE THREAD

**Issue by kanes115** [ansible/ansible#43640]
##### SUMMARY

ansible `git` action does not fetch the newest repo after rebasing.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

git

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/Kanes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

MacOS
##### STEPS TO REPRODUCE

ansible task is as follows:
```
- name: "fetch the XXX code"
      git:
        repo: "{{ repo }}"
        dest: "{{ repo_dir }}"
        version: "test_branch"
        accept_hostkey: yes
        force: yes
        depth: 1
```

- create branch `test_branch` and add some commits
- run ansible script (look above) - we've got repo in `repo_dir` on branch `test_branch`
- create branch `test_branch2` and add some commits
- on test_branch: `git rebase test_branch2`
- run ansible script - nothing changed - we don't have changes from `test_branch2`

```yaml
- name: "fetch the XXX code"
      git:
        repo: "{{ repo }}"
        dest: "{{ repo_dir }}"
        version: "test_branch"
        accept_hostkey: yes
        force: yes
        depth: 1
```

##### EXPECTED RESULTS

Expected result is cloned repo with the changes from branch we rebased
##### ACTUAL RESULTS

The changes were not there

```

```
