### ISSUE TITLE
nios_network: Option vendor-encapsulated-options can not have a use_option flag

### ISSUE THREAD

**Issue by badnetmask** [ansible/ansible#43657]
##### SUMMARY

While using the nios_network module, defining option 43 (vendor-encapsulated-options) on a given network, the following error is shown:

"msg": "Option vendor-encapsulated-options can not have a use_option flag", "operation": "update_object", "type": "AdmConProtoError"

I was able to temporarily workaround by defining an exception on the NIOS code. It's possible that there are other options which may give the same error, but I can't find any direct references to them on the NIOS API documentation.

```
# diff -u nios_network.py.bak nios_network.py
--- nios_network.py.bak	2018-08-04 09:55:37.189714555 -0400
+++ nios_network.py	2018-08-04 09:58:16.971858009 -0400
@@ -163,7 +163,8 @@
         opt = dict([(k, v) for k, v in iteritems(item) if v is not None])
         if 'name' not in opt and 'num' not in opt:
             module.fail_json(msg='one of `name` or `num` is required for option value')
-        options.append(opt)
+        if opt['num'] != 43:
+            options.append(opt)
     return options
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nios_network

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /home/mteixeir/.ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### OS / ENVIRONMENT

Fedora 28

##### STEPS TO REPRODUCE

```yaml
tasks:
    - name: modify option43
      nios_network:
        network: 10.10.10.0/24
        provider:
          host: "{{ nios_provider }}"
          username: "{{ username }}"
          password: "{{ password }}"
        options:
          - num: 43
            value: aa:bb:cc:dd:ee:ff:gg
```

##### EXPECTED RESULTS

ok: [localhost]

##### ACTUAL RESULTS

```
failed: [localhost] (item={u'cidr': u'10.10.10.0/24', u'option43': u'aa:bb:cc:dd:ee:ff:gg'}) => {"changed": false, "code": "Client.Ibap.Proto", "item": {"cidr": "10.10.10.0/24", "option43": "aa:bb:cc:dd:ee:ff:gg"}, "msg": "Option vendor-encapsulated-options can not have a use_option flag", "operation": "update_object", "type": "AdmConProtoError"}
```
