### ISSUE TITLE
with_nested with list of lists is appending list when it shouldn't

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#43652]
##### SUMMARY

When using with_nested with a nested list of lists the nested list is appended to the first item.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

with_nested
##### ANSIBLE VERSION

```
ansible 2.4.4.0
  python version = 2.7.14 (default, Mar 21 2018, 16:45:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

Run the following playbook

```yaml
---
- name: testing things
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - set_fact:
        list_1:
          - "one"
          - "two"
        list_2:
          - [ 1a, 1b ]
          - [ 2a, 2b ]
    - name: testing nested
      debug:
        msg: "{{ item }}"
      with_nested:
        - "{{ list_1 }}"
        - "{{ list_2 }}"
```

##### EXPECTED RESULTS

```
PLAY [testing things] **************************************************************************************************************************************************************************

TASK [set_fact] ********************************************************************************************************************************************************************************
Friday 03 August 2018  13:24:50 -0700 (0:00:00.043)       0:00:00.043 *********
ok: [localhost]

TASK [testing nested] **************************************************************************************************************************************************************************
Friday 03 August 2018  13:24:50 -0700 (0:00:00.033)       0:00:00.076 *********
ok: [localhost] => (item=None) => {
    "msg": [
        "one",
        [ "1a", "1b" ]
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "one",
        [ "2a", "2b" ]
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "two",
        [ "1a", "1b" ]
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "two",
        [ "2a", "2b" ]
    ]
}
```
##### ACTUAL RESULTS

```
PLAY [testing things] **************************************************************************************************************************************************************************

TASK [set_fact] ********************************************************************************************************************************************************************************
Friday 03 August 2018  13:24:50 -0700 (0:00:00.043)       0:00:00.043 *********
ok: [localhost]

TASK [testing nested] **************************************************************************************************************************************************************************
Friday 03 August 2018  13:24:50 -0700 (0:00:00.033)       0:00:00.076 *********
ok: [localhost] => (item=None) => {
    "msg": [
        "one",
        "1a",
        "1b"
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "one",
        "2a",
        "2b"
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "two",
        "1a",
        "1b"
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "two",
        "2a",
        "2b"
    ]
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by orderedchaosdev** [comment]
also if you do something like
```yaml
- name: testing things
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - set_fact:
        list_1:
          - [ "one", "oneone" ]
          - [ "two", "twotwo" ]
        list_2:
          - [ 1a, 1b ]
          - [ 2a, 2b ]
    - name: testing nested
      debug:
        msg: "{{ item }}"
      with_nested:
        - "{{ list_1 }}"
        - "{{ list_2 }}"
```
Then you get 
```
ok: [localhost] => (item=None) => {
    "msg": [
        "one",
        "oneone",
        "1a",
        "1b"
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "one",
        "oneone",
        "2a",
        "2b"
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "two",
        "twotwo",
        "1a",
        "1b"
    ]
}
ok: [localhost] => (item=None) => {
    "msg": [
        "two",
        "twotwo",
        "2a",
        "2b"
    ]
}
```
