### ISSUE TITLE
include_role doesn't work under local_action

### ISSUE THREAD

**Issue by lyz-code** [ansible/ansible#43663]
##### SUMMARY

`include_role` doesn't work under `local_action`, the role get's executed on the remote host.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role
local_action

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = ~/.ansible.cfg
  configured module search path = [u'~/.ansible/library']
  ansible python module location = ~/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```
DEFAULT_CALLBACK_PLUGIN_PATH(~/.ansible.cfg) = [u'~/.local/share/ansible/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(~/.ansible.cfg) = ['profile_tasks']
DEFAULT_MODULE_PATH(~/.ansible.cfg) = [u'~/.ansible/library']
DEFAULT_STDOUT_CALLBACK(~/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(~/.ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Debian Stretch

##### STEPS TO REPRODUCE

Create the following playbook structure

```
├── hosts
├── main.yml
└── roles
    └── touch-file
        └── tasks
            └── main.yml
```
Being the playbook `main.yml`:

```yaml
- name: Test local_action with include_role
  hosts: all
  tasks: 
    - name: test local_action
      local_action:
        module: include_role
        args:
          name: touch-file
             
    - name: test local_action
      delegate_to: 127.0.0.1 
      include_role: 
        name: touch-file
```

Being the `touch-file` role `tasks/main.yml`:

```yaml
- name: Touch temp file
  file:
    path: /tmp/test
    state: touch
```

Execute `ansible-playbook -i hosts main.yml`

##### EXPECTED RESULTS

Touches the file `/tmp/test` in the machine launching ansible

##### ACTUAL RESULTS

Touches the file `/tmp/test` in the remote sever

###### Notes

* I've included the delegate_to task to test that the fix proposed https://github.com/ansible/ansible/issues/28822 doesn't work
* If the `local_action` is inside the role it works
