### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xac in position 783: invalid start byte

### ISSUE THREAD

**Issue by saneejmc1** [ansible/ansible#43667]
##### SUMMARY
Error "UnicodeDecodeError: 'utf8' codec can't decode byte 0xac in position 783: invalid start byte" on Ansible copy module to copy

```
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ("quoteChar" = "\"","escapeChar" = "¬")
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

**Comment by ansibot** [comment]
@saneejmc1 Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Can you please provide us with the task that is failing and the output of `ansible-playbook` using `-vvv`?

needs_info

**Comment by saneejmc1** [comment]
17:46:02 failed: [xxxxxxx] (item={u'name': u'xxxxxxxxxxxx_DDL'}) => {
17:46:02     "changed": false, 
17:46:02     "item": {
17:46:02         "name": "xxxxxxxxxxxx_DDL"
17:46:02     }, 
17:46:02     "msg": "UnicodeDecodeError: 'utf8' codec can't decode byte 0xac in position 783: invalid start byte"
17:46:02 }

**Comment by sivel** [comment]
Please provide the task definition as well.  Without a way to reproduce this, I'm unsure how feasible it will be to actually resolve.

If possible please create a minimal reproducer that showcases this issue that we can run.

needs_info

**Comment by saneejmc1** [comment]
TASK [config : Create scripts from templates] ****************************************************************************************************************
task path: /home/raul45/acv/provisioning/roles/config/tasks/copy_files.yml:3
<10.45.21.31> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.45.21.31> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/raul45/deployment/cluster.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/raul45/.ansible/cp/aa55ef2af6 10.45.21.31 '/bin/sh -c '"'"'echo ~ec2-user && sleep 0'"'"''
<10.45.21.31> (0, '/home/ec2-user\n', '')
<10.45.21.31> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.45.21.31> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/raul45/deployment/cluster.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/raul45/.ansible/cp/aa55ef2af6 10.45.21.31 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /var/tmp/ansible-tmp-1533772404.95-51134343715779 `" && echo ansible-tmp-1533772404.95-51134343715779="` echo /var/tmp/ansible-tmp-1533772404.95-51134343715779 `" ) && sleep 0'"'"''
<10.45.21.31> (0, 'ansible-tmp-1533772404.95-51134343715779=/var/tmp/ansible-tmp-1533772404.95-51134343715779\n', '')
<10.45.21.31> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.45.21.31> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/raul45/deployment/cluster.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 -o ControlPath=/home/raul45/.ansible/cp/aa55ef2af6 10.45.21.31 '/bin/sh -c '"'"'rm -f -r /var/tmp/ansible-tmp-1533772404.95-51134343715779/ > /dev/null 2>&1 && sleep 0'"'"''
<10.45.21.31> (0, '', '')
failed: [10-64-24-131.simpleaws.com] (item={u'name': u'test_table'}) => {
    "changed": false,
    "item": {
        "name": "test_table"
    },
    "msg": "UnicodeDecodeError: 'utf8' codec can't decode byte 0xac in position 783: invalid start byte"
}
        to retry, use: --limit @/home/raul45/acv/provisioning/site.retry

**Comment by saneejmc1** [comment]
```
---

- name: Create scripts from templates
  become: yes
  become_user: '{{ application_user }}'
  template:
    src: '{{ playbook_dir }}/roles/config/templates/{{ item.name }}.j2'
    dest: '{{ local_fs_dir.ddl.path }}/{{ item.name }}.ddl'
    owner: '{{ application_user }}'
    group: '{{ application_user_group }}'
    mode: '0770'
  with_items:
    - { name: 'test_table' }
```


test_table.j2 is below....
```
------------------------------------------------
-- DDL Statements for alert
------------------------------------------------

drop table if exists alert;
CREATE EXTERNAL TABLE alert
(
name string,
address varchar(1000)
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ("quoteChar" = "\"","escapeChar" = "¬")
STORED as TEXTFILE
LOCATION 'hdfs:///ALERT/';

------------------------------------------------------------------------
```
issue is due to symbol "¬",

**Comment by abadger** [comment]
Is test_table.j2 valid utf8?

**Comment by jborean93** [comment]
Sounds like `test_table.j2` is ~~ASCII~~ Latin-1/Windows-1252 encoded, `¬` is `0xAC` in "extended" ASCII and `0xC2 0xAC` in UTF-8. Because of the missing byte it is seen as a malformed unicode char.

**Comment by abadger** [comment]
I'm going to close this.  The template needs to be encoded in valid utf-8.

However, if you need to output something other than utf-8, you can do that in ansible-2.7 or later using the output_encoding parameter: https://docs.ansible.com/ansible/devel/modules/template_module.html#parameters

here's an example of modifying your playbook to use output_encoding.  Remember that you also have to re-encode your template to utf-8 (on Linux, the iconv command can do that: ```iconv -f latin1 -t utf8 test_table.j2```)
```
---
- name: Create scripts from templates
  become: yes
  become_user: '{{ application_user }}'
  template:
    src: '{{ playbook_dir }}/roles/config/templates/{{ item.name }}.j2'
    dest: '{{ local_fs_dir.ddl.path }}/{{ item.name }}.ddl'
    owner: '{{ application_user }}'
    group: '{{ application_user_group }}'
    mode: '0770'
    output_encoding: 'latin-1'
  with_items:
    - { name: 'test_table' }
```
