### ISSUE TITLE
ansible 2.6.2 vmware_guest problem with  clone a virtual machine from template and customize

### ISSUE THREAD

**Issue by grzesart1978** [ansible/ansible#43712]
##### SUMMARY
 I have problem after update ansible from 2.5.2 to 2.6.2 with vmware_guest module. I can't clone virtual machine from template. I get error. 

  On ansible 2.5.2 everything works fine.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
2.6.2
```

##### OS / ENVIRONMENT
OS CentOS Linux release 7.4.1708 ;VMWARE 6,5

##### STEPS TO REPRODUCE

 tasks:

  - name: Clone template and customize
    vmware_guest:
      hostname: '{{hostname_dc}}'
      username: '{{vcenter_user}}'
      password: '{{vcenter_pass}}'
      validate_certs: no

      datacenter: "{{ vcenter_datacenter}}"
      cluster: "{{item['vcenter_cluster']}}"
      folder: "{{item['folder_vm']}}"
      name: '{{ item.name }}'
      annotation: Created by Ansible

      template: "{{ vmtemplate }}"
      disk:
      - size_gb: "{{item['disk1_size']}}"
        type: "thin"
        datastore: "{{item['datastore_1']}}"
      - size_gb: "{{item['disk2_size']}}"
        type: "thin"
        datastore: "{{item['datastore_2']}}"
      - size_gb: "{{item['disk3_size']}}"
        type: "thin"
        datastore: "{{item['datastore_3']}}"


      hardware:

         num_cpus: "{{item['cpu_count']}}"
         memory_mb: "{{item['vm_memory']}}"

      networks:

       -  vlan: "{{item['vlan']}}"

          ip: "{{item['ip']}}"
          netmask: "{{item['mask']}}"
          gateway: "{{item['gateway']}}"

      customization:
       dns_servers:
         - "{{dns1}}"
         - "{{dns2}}"
       domain: "{{domain_name}}"

    with_items:
      - "{{server_list}}"
    delegate_to: localhost
    register: deploy
~                      

```

##### ACTUAL RESULTS
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py", line 2274, in <module>
    main()
  File "/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py", line 2263, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py", line 1917, in deploy_vm
    self.configure_network(vm_obj=vm_obj)
  File "/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py", line 1131, in configure_network
    network_devices = self.sanitize_network_params()
  File "/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py", line 1078, in sanitize_network_params
    dvp.config.defaultPortConfig.vlan.vlanId == int(network['vlan']):
ValueError: invalid literal for int() with base 10: 'lan-100-TEST'

failed: [localhost -> localhost] (item=
 "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py\", line 2274, in <module>\n    main()\n  File \"/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py\", line 2263, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py\", line 1917, in deploy_vm\n    self.configure_network(vm_obj=vm_obj)\n  File \"/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py\", line 1131, in configure_network\n    network_devices = self.sanitize_network_params()\n  File \"/tmp/ansible_AMc7DF/ansible_module_vmware_guest.py\", line 1078, in sanitize_network_params\n    dvp.config.defaultPortConfig.vlan.vlanId == int(network['vlan']):\nValueError: invalid literal for int() with 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @grzesart1978,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@grzesart1978 Thanks for reporting this issue. What is value of `vlan: "{{item['vlan']}}"` in playbook.

**Comment by grzesart1978** [comment]
@Akasurde I have define in vars something like that

vars/kafka-prep.yml

```yaml
server_list:
  - name: test-kafka
    vcenter_cluster: ESX-LAN
    folder_vm: /ESX-LAN/ESX-LAN/DATA
    cpu_count: 1
    vm_memory: 4096
    disk1_size: 8
    datastore_1: ESX-LAN-D01
    disk2_size: 10
    datastore_2: ESX-LAN-D01
    disk3_size: 30
    datastore_3: ESX-LAN-D01
    vlan: pg-LAN-100-TEST
    ip: 10.10.1.51
    mask: 255.255.255.0
    gateway: 10.10.1.1
```
in playbook I have define vars_files 

```
- hosts: local
  gather_facts: true
  connection: local
  vars_files:
     - vault_pass.yml
     - vars/kafka-prep.yml
```
