### ISSUE TITLE
ios_vrf slow with big config

### ISSUE THREAD

**Issue by denngie** [ansible/ansible#43718]
##### SUMMARY

When using ios_vrf, the function parse_interfaces increases the time for the task from ~20 seconds to ~120 seconds which causes connection timeouts with default values and a config of ~12k lines, 200 VRFs and 500 interfaces
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_vrf
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/e600790/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
##### OS / ENVIRONMENT

Debian 9.5 managing Cisco 15.5(3)S6b/03.16.06b.S
##### STEPS TO REPRODUCE

```yaml
ios_vrf:
  name: "{{ vrf_name }}"
  rd: "{{ vrf_route_target }}"
  description: "{{ vrf_description }}"
  route_export: '{{ vrf_route_target }}'
  route_import: '{{ vrf_route_target }}'
  state: present
```

##### EXPECTED RESULTS

real    0m16,741s
user    0m8,664s
sys     0m0,856s
##### ACTUAL RESULTS

real    1m52,279s
user    1m41,468s
sys     0m1,788s
