### ISSUE TITLE
jenkins_plugin with state=present updates every plugin with new version available.

### ISSUE THREAD

**Issue by mmolinac** [ansible/ansible#43728]
##### SUMMARY

I have a list of plugins that have to be present, and I mean it: Only their presence is to be verified.
It happens that `jenkins_plugin` *updates* the plugin even when you specify `state=present`, when this should only happen when you specify `state=latest` or you specify `version=X.Y.Z`, being it a different version that the current one.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

jenkins_plugin

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/mmolinac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

[defaults]
callback_whitelist = profile_roles
allow_world_readable_tmpfiles=True
host_key_checking = False
retry_files_enabled = False

[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
control_path_dir = /tmp/.ansible/cp

[diff]
always = yes
context = 6

##### OS / ENVIRONMENT

macOS High Sierra Version 10.13.6
Jenkins 2.121.2

##### STEPS TO REPRODUCE

Having the plugin `ant` installed already on the system, and there are updates available that we aren't willing to install:

```yaml
- name: Jenkins plugin installation
  jenkins_plugin:
    name:    "{{ item.name }}"
    url_username: admin
    url_password: "{{ jenkins_password }}"
    state:   present
  with_items:
    - 'ant'
  loop_control: 
    label: "{{ item.name }}"
```

##### EXPECTED RESULTS

No action taken, because the plugin is already there.

```
TASK [profile_jenkins : Jenkins plugin installation] ****************************************************************************************************************************************
ok: [deployment01] => (item=ant)
```

##### ACTUAL RESULTS

The plugin was updated and thus, reported as changed.

```
TASK [profile_jenkins : Jenkins plugin installation] ****************************************************************************************************************************************
changed: [deployment01] => (item=ant)
```
