### ISSUE TITLE
[gluster_volume] Enable configuration of global volume options

### ISSUE THREAD

**Issue by Nirkus** [ansible/ansible#43726]
##### SUMMARY
Enable configuration of global volume options

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
module gluster_volume

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/******/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/******/somedir/ansible/lib/ansible
  executable location = /home/******/somedir/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Controller is Debian 9 ("stretch").
Servers configured for glusterfs are CentOS 7.5 using glusterfs 3.12.

##### STEPS TO REPRODUCE
```yaml
- name: set global options for all gluster volumes
  run_once: yes
  gluster_volume:
    name: all
    options: "{{ gfs_global_options_defaults | combine(gfs_global_options) }}"
    state: present
```

##### EXPECTED RESULTS
Configure global colume options (`gluster volume set all ...`).

##### ACTUAL RESULTS
Module `gluster_volume`  tries to create gluster volume named `all`.

```
fatal: [somehost.example.invalid]: FAILED! => {"changed": false, "msg": "error running gluster (/usr/sbin/gluster --mode=script volume create all transport tcp) command (rc=1): \"all\" cannot be the name of a volume.\n\nUsage:\nvolume create <NEW-VOLNAME> [stripe <COUNT>] [replica <COUNT> [arbiter <COUNT>]] [disperse [<COUNT>]] [disperse-data <COUNT>] [redundancy <COUNT>] [transport <tcp|rdma|tcp,rdma>] <NEW-BRICK>?<vg_name>... [force]\n\n"}
```
