### ISSUE TITLE
Unarchive module ignores some zip archives

### ISSUE THREAD

**Issue by syswipe** [ansible/ansible#43777]
##### SUMMARY
I'm trying to deploy files from zip archive to some hosts using unarchive module, but ansible ignores some archives.

##### ISSUE TYPE
- Bug Report
- Not expected behavior

##### COMPONENT NAME
unarchive module

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/deploy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
##### CONFIGURATION
```
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/deploy/.vault_password
```
##### OS / ENVIRONMENT

OS i'm runing ansible from: Ubuntu 16.04.4
OS i'm managing: Solaris 11.3, with Python 2.7.14

##### STEPS TO REPRODUCE
```yaml
 ansible -v -b -m unarchive deploy.host -a 'src=/var/tmp/artifacts.zip dest=/var/tmp/TEMP/ remote_src=yes'
Using /etc/ansible/ansible.cfg as config file
deploy.host | SUCCESS => {
    "changed": false, 
    "dest": "/var/tmp/TEMP/", 
    "gid": 10, 
    "group": "staff", 
    "handler": "ZipArchive", 
    "mode": "0755", 
    "owner": "admin", 
    "size": 2, 
    "src": "/var/tmp/artifacts.zip", 
    "state": "directory", 
    "uid": 11006
}

```
##### EXPECTED RESULTS
/var/tmp/TEMP/ dir with a lot of files from artifacts.zip

##### ACTUAL RESULTS
/var/tmp/TEMP/ is empty

When i try to unzip artifacts.zip manually on dest host - all files extracts fine.
Also, not all zip archives affected. Some zip archives also extracted with the same ad hoc command as expected.
