### ISSUE TITLE
"When" Condition help for Mail Module within Playbook, Ansible

### ISSUE THREAD

**Issue by riyadali1** [ansible/ansible#43780]
##### SUMMARY
Hi,

I have created a yaml to update my Linux servers via yum and I want to send an email but only if the server has been changed/updated.

This is the yamI made:
```yaml
---

- name: yum update for all hosts
   hosts: linux-servers
   become: yes
   become_method: su

  tasks:
     -name: yum update
       yum: > 
           update_cache=yes
           name=*
           state=latest
           update_cache=yes
     
          name: Send Mail
          mail: 
            host: xxx.xxx.xx.xx
            port: xxxx
            sender: (my email)
            to: (my secondary email)
            subject: Yum Update for {( ansible_hostname )}
            body: 'system updated'
           delegate_to: localhost
           when: update_cache=updated.std

```
Any help would be appreciated!

Thanks,
Riyad

##### ANSIBLE VERSION
Ansible 2.4.2.0

##### COMPONENT NAME

Ansible

##### ISSUE TYPE
   - Bug Report
