### ISSUE TITLE
gluster_volume fails on non-string values in options

### ISSUE THREAD

**Issue by Nirkus** [ansible/ansible#43787]
##### SUMMARY
Module `gluster_volume` fails on non-string values (int, bool, ..?) in `options`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module gluster_volume

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/******/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/******/somedir/ansible/lib/ansible
  executable location = /home/******/somedir/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Controller is Debian 9 ("stretch").
Servers configured for glusterfs are CentOS 7.5 using glusterfs 3.12.

##### STEPS TO REPRODUCE

defaultls
```yaml
gfs_volume_options_defaults:
  cluster.shd-max-threads: 8
  performance.io-cache: off
```

task
```yaml
## FIXME: this requires linear execution strategy for all previous tasks to be completed on all servers
- name: create gluster volume
  gluster_volume:
    arbiters: "{{ gfs_volume.arbiters | default(0) }}"
    bricks: "/gluster-bricks/{{ gfs_volume.name }}/{{ gfs_volume.name }}"
    cluster: "{{ ansible_play_hosts }}"
    force: no
    name: "{{ gfs_volume.name }}"
    options: "{{ gfs_volume_options_defaults | combine(gfs_volume.options | default( {} )) }}"
    rebalance: "{{ gfs_volume.rebalance | default('no') }}"
    replicas: "{{ gfs_volume.replicas | default(ansible_play_hosts | length) }}"
    start_on_create: yes
    state: present
  when: inventory_hostname == ansible_play_hosts[0]
```

##### EXPECTED RESULTS
All options and values passed to gluster command as strings.

##### ACTUAL RESULTS
At least option values parsed as int and bool values are not converted to strings before being passed to `module.run_command`.

```
fatal: [host1.example.invalid]: FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to host1.example.invalid closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 526, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 495, in main\r\n    set_volume_option(volume_name, option, options[option])\r\n  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 339, in set_volume_option\r\n    run_gluster(['volume', 'set', name, option, parameter])\r\n  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 179, in run_gluster\r\n    module.fail_json(msg='error running gluster (%s) command: %s' % (' '.join(args),\r\nTypeError: sequence item 6: expected string, bool found\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

```
Traceback (most recent call last):
  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 526, in <module>
    main()
  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 495, in main
    set_volume_option(volume_name, option, options[option])
  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 339, in set_volume_option
    run_gluster(['volume', 'set', name, option, parameter])
  File \"/tmp/ansible_Kd8hph/ansible_module_gluster_volume.py\", line 179, in run_gluster
    module.fail_json(msg='error running gluster (%s) command: %s' % (' '.join(args),
TypeError: sequence item 6: expected string, bool found
```
