### ISSUE TITLE
azure_rm_securitygroup does not recognize ASGs

### ISSUE THREAD

**Issue by dancs85** [ansible/ansible#43802]
##### SUMMARY

The azure_rm_securitygroup module does not recognize Application Security Groups. There is no way to provision NSGs with rules that contain ASG destinations/sources, and if a NSG rule is manually edited via the Portal with a rule containing a reference to an ASG, then re-running the azure_rm_securitygroup module causes an error.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_securitygroup

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/#####/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/#####/.local/lib/python2.7/site-packages/ansible
  executable location = /home/#####/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

Ubuntu on Windows 10 (WSL)

##### STEPS TO REPRODUCE

```yaml
azure_rm_securitygroup:
  resource_group: rsg01
  name: nsg01
  rules:
    - name: "HTTPS_WebServers"
      protocol: Tcp
      source_address_prefix: "Internet"
      destination_address_prefix: "asg-web"
      destination_port_range: 443
        access: Allow
        priority: 101
        direction: Inbound
```

##### EXPECTED RESULTS

NSG created with rule that references an ASG

##### ACTUAL RESULTS

If re-running the module with a manually created NSG rule referencing an ASG:

```
Error creating/updating security group nsg01 - Azure Error: SecurityRuleParametersMissing\nMessage: Required security rule parameters are missing for security rule with Id: /subscriptions/#####/resourceGroups/rsg01/providers/Microsoft.Network/networkSecurityGroups/nsg01/securityRules/HTTPS_WebServers. Security rule must specify DestinationAddressPrefixes, DestinationAddressPrefix, or DestinationApplicationSecurityGroups.
```
