### ISSUE TITLE
fortios_ipv4_policy unusable with SSL Interfaces

### ISSUE THREAD

**Issue by jg159357** [ansible/ansible#43800]
##### SUMMARY

When using fortios_ipv4_policy module to create a firewall policy, if the source interface is an ssl.XXX interface, the firewall will require you to set a group, but src_addr does not appear to parse that.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

fortios_ipv4_policy

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python2.7/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

 I am using the update in pyFG from https://github.com/spotify/pyfg/pull/25 for ordereddict to resolve the src interface/addr order issue.

##### OS / ENVIRONMENT

Linux DESKTOP-UJLJBHV 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04 from windows store

##### STEPS TO REPRODUCE

```yaml
  - name: Allow RDP and ICMP to VM in os1-edge-fw-1/COLO_WAN->VPN-1
    fortios_ipv4_policy:
      host: <redacted>
      username: <redacted>
      vdom: COLO_WAN
      password: <redacted>
      state: present
      id: 100010
      comment: "SSLVPN to Engineering Workstation: Remote Desktop and Ping (created by Ansible)"
      src_intf: ssl.<redacted>
      src_addr:
        - VPN_SRC_ADDR
        - sslGH
      dst_intf: Remote Site Primary
      dst_addr: kum-eng-ws-1
      services:
        - ALL_ICMP
        - RDP
      nat: False
      policy_action: accept
      logtraffic: all
      logtraffic_start: yes
    delegate_to: localhost
```

##### EXPECTED RESULTS

policy 100010 to be created with appropriate source/destinations

##### ACTUAL RESULTS

Policy creation or update fails.  If using just an address, the module is successful, but the rule does not match connections/firewall indicates error.

```
task path: /mnt/c/development/ansible/eWS/pb-kum-engWS.yml:316
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~user&& sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378 `" && echo ansible-tmp-1533684503.58-180057536873378="` echo /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378 `" ) && sleep 0'
Using module file /home/user/.local/lib/python2.7/site-packages/ansible/modules/network/fortios/fortios_ipv4_policy.py
<localhost> PUT /home/user/.ansible/tmp/ansible-local-2762ZM9Jon/tmpkr6_ym TO /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378/fortios_ipv4_policy.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378/ /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378/fortios_ipv4_policy.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378/fortios_ipv4_policy.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1533684503.58-180057536873378/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_yEexP_/ansible_modlib.zip/ansible/module_utils/network/fortios/fortios.py", line 172, in apply_changes
    self.forti_device.commit()
  File "/usr/local/lib/python2.7/dist-packages/pyFG/fortios.py", line 274, in commit
    self._commit(config_text, force)
  File "/usr/local/lib/python2.7/dist-packages/pyFG/fortios.py", line 329, in _commit
    raise exceptions.FailedCommit(wrong_commands)

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "application_list": null,
            "av_profile": null,
            "backup": false,
            "backup_filename": null,
            "backup_path": null,
            "comment": "SSLVPN to Engineering Workstation: Remote Desktop and Ping (created by Ansible)",
            "config_file": null,
            "dst_addr": [
                "kum-eng-ws-1"
            ],
            "dst_addr_negate": false,
            "dst_intf": [
                "Remote Site Primary"
            ],
            "file_mode": false,
            "fixedport": false,
            "host": "<redacted>",
            "id": 100010,
            "ips_sensor": null,
            "logtraffic": "all",
            "logtraffic_start": true,
            "nat": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "policy_action": "accept",
            "poolname": null,
            "schedule": "always",
            "service": [
                "ALL_ICMP",
                "RDP"
            ],
            "service_negate": false,
            "services": [
                "ALL_ICMP",
                "RDP"
            ],
            "src_addr": [
                "VPN_SRC_ADDR",
                "sslGH"
            ],
            "src_addr_negate": false,
            "src_intf": [
                "ssl.<redacted>"
            ],
            "state": "present",
            "timeout": 60,
            "username": "<redacted>",
            "vdom": "<redacted>",
            "webfilter_profile": null
        }
    },
    "msg": "Unable to commit change, check your args, the error was [(u'-3', u'set srcaddr \"VPN_SRC_ADDR\" \"sslGH\"')]",
    "msg_error_list": [
        {
            "error_code": "-3",
            "error_string": "set srcaddr \"VPN_SRC_ADDR\" \"sslGH\"",
            "error_type": "Object not found"
        }
    ]
}
        to retry, use: --limit @/mnt/c/development/ansible/eWS/pb-kum-engWS.retry

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
