### ISSUE TITLE
account_name DOMAIN\xxxx[+20 characters long name] is not a valid account {win_group_membership}

### ISSUE THREAD

**Issue by virtuoz75** [ansible/ansible#43815]
##### SUMMARY
Using win_group_membership to add an user or group with more than 20 characters does not work

##### ISSUE TYPE
 - Feature request

##### COMPONENT NAME
win_group_membership

##### ANSIBLE VERSION
```
ansible 2.6.2
```

##### OS / ENVIRONMENT

Windows Server 2016

##### STEPS TO REPRODUCE

Try simply to add a domain account more than 20 character long into a local group in the target machine

```yaml
- name: Adding a domain user to a local group
  win_group_membership:
    name: Remote Desktop Users
    members:
     - DOMAIN\this_is_an_example_account
    state: present
```

##### EXPECTED RESULTS

I wanted that the module add the domain account into local group
##### ACTUAL RESULTS

The play return that the account name is not valid

```
{
    "msg": "account_name DOMAIN\\this_is_an_example_account is not a valid account, cannot get SID: Exception calling \"Translate\" with \"1\" argument(s): \"Some or all identity references could not be translated.\"",
    "_ansible_parsed": true,
    "changed": false,
    "_ansible_no_log": false
}
```

I already have look for the error and found this
https://msdn.microsoft.com/en-us/library/bb223127(v=office.12).aspx

So to make my playbook work, I were constraint to use this script (this perhaps can help you):

https://gallery.technet.microsoft.com/scriptcenter/Add-AD-UserGroup-to-RDP-c17b24a4

Do you know if this module will support long names in the future?
