### ISSUE TITLE
Privileged mode failure for second task when first task doesn't need privilege mode

### ISSUE THREAD

**Issue by ganchandrasekaran** [ansible/ansible#43813]
##### SUMMARY

Privileged mode failure happens for second task when first task doesn't need privilege mode specified. 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### STEPS TO REPRODUCE

Say the following is a playbook task content:
1st part with module eos_command doesn't need privilege access, where as eos_vlan module will need privilege access so the 'authorize=true' is specified. 

```yaml
  tasks:			  
  - name: show version
    eos_command:
    args: {commands: '{{ item }}' }
    with_items:
          - show version
          - show lldp neighbors
    register: eos_command_output
  - debug: var=eos_command_output

  - name: create vlan 100
    eos_vlan: vlan_id=100
              name=vlan100
              state=present
              auth_pass=***
              authorize=true
```

##### EXPECTED RESULTS

All 2 tasks should be completed successfully. 

##### ACTUAL RESULTS

```
fatal: [arista.sw2]: FAILED! => {"changed": false, "data": "configure session ansible_1533715097\r\n% Invalid input (privileged mode required)\r\nlocalhost>", "msg": "Error on executing commands ['vlan 100', 'name vlan100']"}
        to retry, use: --limit @/home/admin/working/play.retry

PLAY RECAP ******************************************************************************************************************************************************************************************************
arista.sw2                 : ok=2    changed=0    unreachable=0    failed=1

```

However when you reverse the playbook like:
```yaml
  tasks:
  - name: create vlan 100
    eos_vlan: vlan_id=100
              name=vlan100
              state=present
              auth_pass=samsung
              authorize=true
			  
  - name: show version
    eos_command:
    args: {commands: '{{ item }}' }
    with_items:
          - show version
          - show lldp neighbors
    register: eos_command_output
  - debug: var=eos_command_output
``` 

All success:
```
PLAY RECAP ******************************************************************************************************************************************************************************************************
arista.sw2                 : ok=3    changed=1    unreachable=0    failed=0
```
