### ISSUE TITLE
In nxos_interface, configuring mode: layer2 in portchannel forces to change always

### ISSUE THREAD

**Issue by mundofer** [ansible/ansible#43824]
##### SUMMARY
When using the nxos_interface to configure a port-channel, if I add  "mode: layer2", on every past the interface is changed, although nothing changes in the configuration. Removing that parameter make it work correctly, with changed = false. 
This problem doesn't happen with Ethernet interfaces. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_interface

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm_ansible/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION

DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = False
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/napalm
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Mac OS X version 10.13.4
Nexus NXOS: version 7.0(3)I5(1)
##### STEPS TO REPRODUCE

```yaml
- name: configure physical interfaces
  connection: network_cli
  nxos_interface:
    name: "{{ item.key }}"
    description: "{{ item.value.description | default(omit) }}"
    state: "{{ item.value.state | default('present') }}"
    admin_state: "{{ item.value.admin_state | default('down' )}}"
    mode: layer2
  with_dict: "{{ interfaces }}"

interfaces:
  port-channel47:
    description: swcore1/2:Po9
    admin_state: up
    mode: trunk
    channel_id: 47
    members:
      - Eth1/47
      - Eth1/48
    vpc: 47
    vlans:
      - 821
      - 822
      - 825
      - 831
```

##### EXPECTED RESULTS

ok: [nex10009.oob.es.novumproject.com] => (item={'value': {u'description': u'swcore1/2:Po9', u'members': [u'Eth1/47', u'Eth1/48'], u'channel_id': 47, u'admin_state': u'up', u'vpc': 47, u'vlans': [821, 822, 825, 831], u'swmode': u'trunk'}, 'key': u'port-channel47'})

##### ACTUAL RESULTS

```
changed: [nex10009.oob.es.novumproject.com] => (item={'value': {u'description': u'swcore1/2:Po9', u'members': [u'Eth1/47', u'Eth1/48'], u'channel_id': 47, u'admin_state': u'up', u'vpc': 47, u'vlans': [821, 822, 825, 831], u'swmode': u'trunk'}, 'key': u'port-channel47'}) => {
    "changed": true,
    "commands": [
        "interface port-channel47",
        "switchport"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "auth_pass": null,
            "authorize": null,
            "delay": 10,
            "description": "swcore1/2:Po9",
            "duplex": null,
            "fabric_forwarding_anycast_gateway": null,
            "host": null,
            "interface_type": null,
            "ip_forward": null,
            "mode": "layer2",
            "mtu": null,
            "name": "port-channel47",
            "neighbors": null,
            "password": null,
            "port": null,
            "provider": null,
            "rx_rate": null,
            "speed": null,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": null,
            "tx_rate": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "key": "port-channel47",
        "value": {
            "admin_state": "up",
            "channel_id": 47,
            "description": "swcore1/2:Po9",
            "members": [
                "Eth1/47",
                "Eth1/48"
            ],
            "swmode": "trunk",
            "vlans": [
                821,
                822,
                825,
                831
            ],
            "vpc": 47
        }
    }
}
```
