### ISSUE TITLE
how to access the playbook_dir variable in python source code without declaring in play.yml

### ISSUE THREAD

**Issue by anis016** [ansible/ansible#43826]
##### SUMMARY

Ansible has a variable `"{{ playbook_dir }}"` that gives the playbook directory path. This can be accessed via the play.yml as an options and could be passed to the task. However, I need to access the playbook directory path `"{{ playbook_dir }}"` in the python source code without using in play.yml

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/python_workspace/ansible-hive/venv_hive/lib/python2.6/site-packages/ansible
  executable location = /root/python_workspace/ansible-hive/venv_hive/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### OS / ENVIRONMENT

Linux sandbox.hortonworks.com 4.11.0-1.el7.elrepo.x86_64 #1 SMP Mon May 1 09:01:59 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

I am using this example: [python-api-example](https://docs.ansible.com/ansible/2.6/dev_guide/developing_api.html#python-api-example) and modified the `play_source` as below.

    play_source = dict(
        name="Ansible Play",
        hosts='localhost',
        gather_facts='no',
        tasks=[
            dict(action=dict(module='debug', args=dict(msg='{{ playbook_dir }}')))
        ]
    )

When I am running this directly using `python hive.py` I am able to get the correct `playbook_dir` path, however, when I am running this using `ansible-playbook` command then the output is showing `/root`.

Is there some other way to get the `{{ playbook_dir }}` path directly to python source code through some API? 

Show below is how play.yml is run.

```yaml
---
- name: Demo playbook
  hosts: yum_hosts
  tasks:
  - name: execute a file in playbook_dir
    hive:
      operation: file
      parameters: "--outputformat=csv2 --showHeader=false -f sample.hql --hivevar environment=default"
      quorum: "sandbox.hortonworks.com:2181"
    register: result_execute

  - name: dump
    debug:
      msg: '{{ result_execute }}'
```

##### EXPECTED RESULTS

Should able to access full path of `playbook_dir`. for example `/root/workspace/hive-ansible/..`

##### ACTUAL RESULTS

Currently the output only shows `/root/`

```

```
