### ISSUE TITLE
Allow user to break out of pause-prompt

### ISSUE THREAD

**Issue by eric-b-hymowitz** [ansible/ansible#43822]
##### SUMMARY
A pause configured with a specific time allows the user to abort a playbook. A pause with no specific time, waiting instead for user to hit RETURN, only allows a user to hit RETURN and proceed.  A prompted pause should also allow the user to abort a playbook.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

pause

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ehymowitz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Workstation release 6.10 (Santiago)
Linux 2.6.32-754.el6.x86_64

##### STEPS TO REPRODUCE

```
- hosts: localhost
  gather_facts: no
  tasks:
  - name: pause for input
    pause:
      prompt: "Hit RETURN when you're ready for the next task"
  - fail:
    msg: "This task is going to fail, so I should break out of the playbook at the pause"
```

##### EXPECTED RESULTS

I would like to be able to hit Ctrl-C to abort the playbook.

##### ACTUAL RESULTS

Ansible traps the Ctrl-C and takes no action.  My only option is to hit RETURN and proceed with the next task.
