### ISSUE TITLE
Cannot change MTU of vSwitch with devel version

### ISSUE THREAD

**Issue by Straevaras** [ansible/ansible#43821]
##### SUMMARY

Using a recent PR https://github.com/ansible/ansible/pull/43414 to fix an error (reference https://github.com/ansible/ansible/issues/42619) with vSwitch configuration, I noticed that I'm not able to update the MTU of a vSwitch if it has no NICs listed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_vswitch

##### ANSIBLE VERSION

```
ansible 2.6.2
```
With changes made in https://github.com/ansible/ansible/pull/43414/files/7ab62b1a0866ef37cf856dc8bb2f53757f4f152c

##### OS / ENVIRONMENT

CentOS 7 3.10.0-862.9.1.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: no
  vars:
    - hypervisor_username: <user>
    - hypervisor_password: <pass>
    - esx_hostname: <ip>
  tasks:
    - name: Add/Update vSwitch
      vmware_vswitch:
        hostname: "{{esx_hostname}"
        username: "{{hypervisor_username}}"
        password: "{{hypervisor_password}}"
        validate_certs: no
        switch: "{{item.name}}"
        nics: "{{item.nics}}"
        mtu: "{{item.mtu}}"
        state: present
      delegate_to: localhost
      with_items:
        - {name: INTERNAL, mtu: 9000, nics: []}
```

##### EXPECTED RESULTS

Expected the MTU of an existing vSwitch named INTERNAL to change to 9000.  The MTU before was at 1500.

##### ACTUAL RESULTS

MTU did not change to 9000, instead stayed at 1500.
