### ISSUE TITLE
skip doesn't work with first_found lookup

### ISSUE THREAD

**Issue by emonty** [ansible/ansible#43833]
##### SUMMARY
Attempts to replace with_first_found with lookup('first_found') fail when skip: True is needed

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
first_found

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### CONFIGURATION
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/callback
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts/openstack.yam
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/invento
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['openstack', 'constructed', 'yaml
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /etc/ansible

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

This fails:
```yaml
- name: Include OS-specific tasks
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.lsb.codename }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.yaml"
        - "{{ ansible_facts.os_family }}.yaml"
      skip: true
```

##### EXPECTED RESULTS

This succeeds:
```yaml
- name: Include OS-specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.lsb.codename }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.yaml"
        - "{{ ansible_facts.os_family }}.yaml"
      skip: true
```

##### ACTUAL RESULTS
```
fatal: [bridge.openstack.org]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/lookup/first_found.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/first_found.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by emonty** [comment]
Tried again with:

```yaml
- name: Include OS-specific tasks
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.lsb.codename }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.yaml"
        - "{{ ansible_facts.os_family }}.yaml"
      skip: true
```

and now get:

fatal: [bridge.openstack.org]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/root/system-config/playbooks/[]' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}


fatal: [bridge.openstack.org]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/root/system-config/playbooks/[]' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

**Comment by emonty** [comment]
This works:

```yaml
- name: Include OS-specific tasks
  include_tasks: "{{ files }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.lsb.codename }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.{{ ansible_facts.architecture }}.yaml"
        - "{{ ansible_facts.distribution }}.yaml"
        - "{{ ansible_facts.os_family }}.yaml"
      skip: true
    files: "{{ lookup('first_found', params) }}"
  when: files
```
