### ISSUE TITLE
openvswitch_db: ovs-vsctl: "True" is not a valid boolean (use "true" or "false") 

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#43858]
##### SUMMARY
`test/integration/targets/openvswitch_db/tests/basic.yaml:68`

```yaml
{
"changed": false, 
"cmd": "/usr/bin/ovs-vsctl -t 5 set Bridge br-test stp_enable=True", 
"msg": "ovs-vsctl: \"True\" is not a valid boolean (use \"true\" or \"false\")", 
"rc": 1, 
"stderr": "ovs-vsctl: \"True\" is not a valid boolean (use \"true\" or \"false\")\n", 
"stderr_lines": [
"ovs-vsctl: \"True\" is not a valid boolean (use \"true\" or \"false\")"
], 
"stdout": "", 
"stdout_lines": []
}
```

Possibly caused by https://github.com/ansible/ansible/pull/42110
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openvswitch_db

##### ANSIBLE VERSION
```
2.7
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
