### ISSUE TITLE
mount module inserts duplicate filesystem into /etc/fstab

### ISSUE THREAD

**Issue by jikquantopian** [ansible/ansible#43855]
##### SUMMARY
I have a filesystem listed in /etc/fstab. When I create a `mount` play to change the parameters for that filesystem and run it, the play adds a new line to fstab that conflicts with the old line there, rather than replacing the old line.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`mount`

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /home/jik/src/family-orchestration/ansible.cfg
  configured module search path = [u'/home/jik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/jik/src/family-orchestration/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/jik/src/family-orchestration/ansible.cfg) = [u'/home/jik/src/family-orchestration/inventory']
DEFAULT_REMOTE_USER(/home/jik/src/family-orchestration/ansible.cfg) = root
```

##### OS / ENVIRONMENT
Both source and target system are Ubuntu 18.04 64-bit.

##### STEPS TO REPRODUCE
I had this line in /etc/fstab, which was previously put there by hand.
```
//nas/photo /home/jik/pictures cifs defaults,credentials=/etc/security/nas.creds,uid=jik,gid=users,forceuid,forcegid,noserverino,_netdev
```
I ran the play shown below. After which, the line shown above was _still_ in /etc/fstab, but this new line was added to the bottom.
```
//nas/photo /home/jik/pictures cifs defaults,credentials=/etc/security/nas.creds,uid=jik,gid=users,forceuid,forcegid,noserverino,_netdev,x-systemd.mount-timeout=0 0 0
```
So now there were two, conflicting lines for the same filesystem in /etc/fstab. That's no good!

```yaml
  - name: mount /home/jik/pictures
    mount:
      src: '//nas/photo'
      path: '/home/jik/pictures'
      fstype: cifs
      opts: 'defaults,credentials=/etc/security/nas.creds,uid=jik,gid=users,forceuid,forcegid,noserverino,_netdev,x-systemd.mount-timeout=0'
      state: mounted
```

##### EXPECTED RESULTS
I expect the `mount` module to notice that the fstab entry it is trying to create has src and path parameters matching an existing filesystem and replace the old entry in fstab with the new one rather than adding a new conflicting entry.

##### ACTUAL RESULTS
The `mount` ansible module corrupted my fstab by adding a conflicting entry to the file.
