### ISSUE TITLE
Fetch module loses connection when pipelining is true

### ISSUE THREAD

**Issue by tomtastic** [ansible/ansible#43880]
##### SUMMARY
Fetch module reports failure despite success when pipelining is true.
"msg": "Failed to connect to the host via ssh: ", "unreachable": true.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
fetch

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /development/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
RHEL7.5 running Ansible, managing AIX6.1.

##### STEPS TO REPRODUCE
Enable `pipelining=true` in ansible.cfg

```yaml
- name: Fetch to storage
  fetch:
    src: '{{ item.path }}'
    dest: '/development/ansible/output/{{ inventory_hostname }}/'
    flat: yes
  with_items: '{{ agent_log.files }}
```

##### EXPECTED RESULTS
Files fetched over {SFTP/SCP/piped} successfully.

##### ACTUAL RESULTS
Ansible warns that SFTP and SCP both failed (despite me having manually tested both can work), then FAILs the play due to host unreachable. Despite this, the files _are_ in fact fetched.

[ansible_fetch_problem.txt](https://github.com/ansible/ansible/files/2273866/ansible_fetch_problem.txt)

Running without pipelining=true works as expected and files are transferred via sftp.
