### ISSUE TITLE
Change of variable_start_string/variable_end_string for template module breaks ansbile variables

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#43886]
##### SUMMARY
When `template` module is used with custom values for  `variable_start_string`/`variable_end_string`, any variable set to the value of another variable is left non-evaluated.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Jinja2, template module

##### ANSIBLE VERSION
I believe it affects all versions of ansible since variable_start_string/variable_end_string appearance.

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
Irrelevant, but was tested on Ubuntu 18.04

##### STEPS TO REPRODUCE

play.yaml
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - template:
       src: test.j2
       dest: /tmp/result.txt
       variable_start_string: '<<'
       variable_end_string: '>>'
  vars:
    foo: '{{ inventory_hostname }}'
```
test.j2:
```
<<foo>>
```

Execution:  `ansible-playbook play.yaml`
##### EXPECTED RESULTS
`cat /tmp/result.txt` should show `localhost`.

##### ACTUAL RESULTS
```
$ cat /tmp/result.txt 
{{ inventory_hostname }}
```
##### Notes
I believe this bug cause issues with current variable system of ansible. User of some role could not possibly predicts that her/his variables won't be evaluated, and creator or the role have trouble to predict which variable would be 'mustached' inside.

Ideas for fix:
1. Give users ability to force variable evaluation prior to template execution
2. Evaluate nested mustaches based on default ansible mustache symbols ({{}}).
