### ISSUE TITLE
cannot create symbolic link

### ISSUE THREAD

**Issue by SurajGupta** [ansible/ansible#439]
This issue occurs with master .4

repro:
create director ~./config/deluge/
create file  ~./machine/laptop/files/deluge.conf
create playbook (below) in ~/machine/laptop/setup.yml
create hosts file in ~/machine/laptop/files/hosts
source  hacking/env-setup
ansible-playbook setup.yml --connection=local -i ./files/hosts --debug

playbook:

```

---
- hosts: 127.0.0.1
  user: YOU
  sudo: True
  tasks:
   - name: copy  config
     action: file src=~/machine/laptop/files/deluge.conf dest=~/.config/deluge/core.conf owner=YOU group=YOU     state=link
```

hosts:

[localhost]
127.0.0.1

error:

 TASK: [copy  config] *********

failed: [127.0.0.1] => file src=~/machine/laptop/files/deluge.conf dest=~/.config/deluge/core.conf owner=YOU group=YOU state=link => {"failed": true, "msg": "", "parsed": false}

err: [127.0.0.1] => Traceback (most recent call last):
  File "//home/YOU/.ansible/tmp/ansible.KbNmIC/file", line 340, in <module>
    old_src = os.readlink(dest)
OSError: [Errno 2] No such file or directory: '~/.config/deluge/core.conf'
