### ISSUE TITLE
datadog_monitor does not interpret the silenced parameter (both scope and timestamp)

### ISSUE THREAD

**Issue by b00tsy** [ansible/ansible#43918]
##### SUMMARY

Populating the `silenced` parameter does not have any effect on the to be muted monitor. E.g. I want to mute the monitor for 5 minutes (for a given scope) and have it unmute itself after the set duration, which can be set via the posix timestamp (and scope) given with the `silenced` parameter.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

datadog_monitor

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/bootsy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

~
inventory = ./xxx/hosts
vault_password_file = ./ansible-vault-pass

##### OS / ENVIRONMENT

macOS 10.13.6

##### STEPS TO REPRODUCE

Run the playbook mentioned below, e.g. ansible-playbook muteMonitor.yml -i inventories/asd/hosts

```yaml
---
- hosts: asd
  tasks:
    - name: mute datadog_monitor
      datadog_monitor:
        name: "DOCKER DIE"
        state: "mute"
        silenced: {"*", 1533837600}
        api_key: '123456789'
        app_key: '123456789'
      ignore_errors: yes
      delegate_to: localhost
```

##### EXPECTED RESULTS

The named monitor should be muted until the posix timestamp given in the silenced dictionary.

##### ACTUAL RESULTS

The named monitor is muted forever (indicated in mute details of app.datadog.com with a ∞ symbol).
Changing the scope from "*" to a certain named host has no effect either.

I also tried `silenced: {"*", "1533837600"}`, same result and silenced: `'{"*", 1533837600}'` (as indicated in the incomplete sample code) results in an ansible error `FAILED! => {"changed": false, "msg": "argument silenced is of type <type 'str'> and we were unable to convert to dict: unable to evaluate string as dictionary”}`

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/datadog_monitor.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/datadog_monitor.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @skornehl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tomek-cz** [comment]
Your dictionary does not look valid: 
`silenced: {"*", 1533837600}`
should be
`silenced: {"*":1533837600}`
Having said that, I have tested that with ansible 2.5 and 2.6 and I can see that silenced is not working correctly even with valid dictionary.
Despite requesting silencing on a particular item or adding a POSIX timestamp, it mutes on the `"*":null`
I request
```
    - name: "Muting Datadog alarms for nginx-router group {{ my_nginx_router_group }}"
      datadog_monitor:
        id: "6090000"
        name: "route 53 monitor tomek"
        state: "mute"
        silenced: '{ "*":1536831948 }'
        api_key: "{{ datadog_api_key }}"  
        app_key: "{{ datadog_app_key }}"
      with_items: "{{ nginx_router_r53_healthchecks[my_nginx_router_group] }}"
```

The ansible responds
```
    "msg": {
        "created": "2018-08-24T07:25:01.902899+00:00",
        "created_at": 1535095501000,
        "deleted": null,
        "id": 6090000,
        "message": "blah (...)",
        "modified": "2018-08-24T07:30:00.983546+00:00",
        "multi": true,
        "name": "Route53 Health Check for \"{{name.name}}\" is triggered",
        "options": {
            "escalation_message": "",
            "include_tags": false,
            "locked": false,
            "new_host_delay": 300,
            "no_data_timeframe": null,
            "notify_audit": false,
            "notify_no_data": false,
            "renotify_interval": 0,
            "require_full_window": false,
            "silenced": {
                "*": null
            },
            "thresholds": {
                "critical": 0.5,
                "critical_recovery": 0.6
            },
            "timeout_h": 0
        },
        "org_id": 16306,
        "overall_state": "OK",
        "overall_state_modified": "2018-09-13T01:41:02.971783+00:00",
        "query": "avg(last_5m):avg:aws.route53.health_check_status{*} by {name,healthcheckid} < 0.5",
        "tags": [],
        "type": "query alert"
    }
}
```

**Comment by b00tsy** [comment]
`Your dictionary does not look valid` excellent eye! That explains my ansible error msg regarding the dict... Unfortunately the monitor does ignore the scope and mute duration with a valid dict.

**Comment by tomek-cz** [comment]
Getting deeper into that, the bug is in the ansible module `datadog_monitor.py`, where we pass a body like this:
`{'silenced': "{'healthcheckid:1aaf9740-aff8-4565-9980-703c8602e60c': 1539507717}"}`
down to a class method defined in datadog's `api/monitors.py`.

The datadog's module does not validate whether the body is valid and uses it to POST the query to datadog's API. But, the API expects  is a body like:
`{'scope': 'healthcheckid:1aaf9740-aff8-4565-9980-703c8602e60c', 'end': '1539507717'}`. 

Since the body is invalid, API treats the scope as '*' and with no end date.

See dd API requirements: https://docs.datadoghq.com/api/?lang=python#mute-a-monitor

I have an experimental ansible `datadog_monitor.py` module with a fix and will propose a fix later on here.

**Comment by b00tsy** [comment]
Awesome, thanks!

**Comment by tomek-cz** [comment]
Hey b00tsy, I've submitted PR for that, https://github.com/ansible/ansible/pull/45722. Now, let the maintainers review that and hopefully the fix will make it into a future version of Ansible.
In a meantime, you can use a workaround I use, which is sending raw requests straight into DD's API, but use 'monitor downtime' API, where you can interact with multiple scopes and a single end time. 
This API is more powerful than 'monitor' API in terms of muting requests. See https://docs.datadoghq.com/api/?lang=python#cancel-monitor-downtimes-by-scope vs https://docs.datadoghq.com/api/?lang=python#mute-a-monitor .

Take a look at this example,just define API keys and this should work for you:
```
    - name: "Muting Datadog alarms for ..."
      vars:
        healthchecks: "healthcheckid:1aaf9740-aff8-4565-9980-703c8602e60c"
        end: "1539762498"
      uri:
        body: '{"scope":"{{ healthchecks }}", "end":"{{ end }}"}'
        url: "https://api.datadoghq.com/api/v1/downtime?api_key={{ datadog_api_key }}&application_key={{ datadog_app_key }}"
        body_format: json
        method: POST
```
to unmute, follow the API documentation, and amend the above body and url as documented:
https://docs.datadoghq.com/api/?lang=python#cancel-monitor-downtimes-by-scope .
