### ISSUE TITLE
Copy of Symbolic Linked Folder Creates Subfolder in destination

### ISSUE THREAD

**Issue by brandonkal** [ansible/ansible#43910]
##### SUMMARY

Ansible is failing to merge symbolicly linked folders with destination. It looks like the code is assuming the symbolic linked folder is a normal file, as this creates a subfolder at the destination rather than merging the contents of the source folder and destination folder.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

copy

##### ANSIBLE VERSION

```
ansible 2.6.2
python version = 3.7.0 
```

##### STEPS TO REPRODUCE

```yaml
- name: Copy symbolic link (filter.d-symbolic) into filter.d
  copy:
    src: filter.d-smybolic
    dest: /etc/fail2ban/filter.d/
  become: true
```

##### EXPECTED RESULTS

`/etc/fail2ban/filter.d/file.conf`

##### ACTUAL RESULTS

`/etc/fail2ban/filter.d/filter.d-symbolic/file.conf`

```

```
