### ISSUE TITLE
set_fact with_dict/with_items outputs an line for every input item, even with no_log

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#43935]
##### SUMMARY

A set_fact task that iterates over a dictionary (with_dict) outputs a line for every item in the dictionary. This is excessively noisy (especially as the input dictionary can be very large) and it cannot be suppressed even with no_log nor with loop_control: label. The same happens when iterating with with_items.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /media/sf_work/lops/ansible.cfg
  configured module search path = [u'/home/em/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
  - set_fact:
      new_dict: "{{ { item.key: item.value } }}"
    with_dict:
    - { "one": 1 }
    - { "two": 2 }
    no_log: yes # => (item=None)
    #loop_control:
    #  label: "" # => (item=)
```

##### EXPECTED RESULTS

Output:

```
TASK [set_fact] ****************************************************************
ok: [ansible-test]
```

##### ACTUAL RESULTS

Output:

```
TASK [set_fact] ****************************************************************
ok: [ansible-test] => (item=None)
ok: [ansible-test] => (item=None)
ok: [ansible-test]
```
