### ISSUE TITLE
 ec2_vpc_route_table on AWS does not allow to add a new route to the existing route table.

### ISSUE THREAD

**Issue by stalinstepin** [ansible/ansible#43932]
##### SUMMARY

 ec2_vpc_route_table on AWS does not allow to add a new route to the existing route table even after specifically mentioning the vpc-id and the route-table-id in the Ansible playbook. It creates a new route entry which is not the requirement.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ec2_vpc_route_table

##### ANSIBLE VERSION

```
  16:44:10 as root on devbox in /opt/work/github/ at master(?)
→ ansible --version
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/opt/work/github/Project_NetWorker/Ansible_4_NetWorker/hosts']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
  17:06:45 as root on devbox in /opt/work/github/ at master(?)
→ hostnamectl 
   Static hostname: devbox
         Icon name: computer-desktop
           Chassis: desktop
           Boot ID: 07a4cb5523644a5f801cff7bd54b2b9e
  Operating System: Ubuntu 14.04.5 LTS
            Kernel: Linux 4.4.0-131-generic
      Architecture: x86_64

```

##### STEPS TO REPRODUCE

+ Create a VPC which also creates a route table along with it.
+ Use the VPC id and the route_table_id to add a entry to the existing table.

```
- name: Setting up custom route table.
      ec2_vpc_route_table:
          vpc_id: "{{ myvpc.vpc.id }}"
          region: us-west-1
          route_table_id: "{{my_route_tb.route_tables[0].associations[0].route_table_id}}"
          # tags:
          #   Name: Custom_Subnet
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ my_igw.gateway_id }}"
```

##### EXPECTED RESULTS

Expected Ansible to add a route to the existing route table using the provided reference of vpc-id and the route_table_id.

##### ACTUAL RESULTS

It creates an new route table instead of adding the route to the existing route table.

```
TASK [cf : ec2_vpc_route_table_facts] *************************************************************************************************************
ok: [localhost]

TASK [cf : Printing the routing table facts.] *****************************************************************************************************
ok: [localhost] => {
    "my_route_tb.route_tables[0].associations[0].route_table_id": "rtb-b4885bd2" ==> Ansible should use this route id to add route to this table.
}

TASK [cf : Setting up custom route table.] ********************************************************************************************************
changed: [localhost]

TASK [cf : Printing my custome route table variables] *********************************************************************************************
ok: [localhost] => {
    "my_custom_route": {
        "changed": true, 
        "failed": false, 
        "route_table": {
            "associations": [], 
            "id": "rtb-9d895afb", 
            "propagating_vgws": [], 
            "route_table_id": "rtb-9d895afb",   ==> creates a new route table.
            "routes": [
                {
                    "destination_cidr_block": "10.0.0.0/16", 
                    "gateway_id": "local", 
                    "origin": "CreateRouteTable", 
                    "state": "active"
                }, 
                {
                    "destination_cidr_block": "0.0.0.0/0", 
                    "gateway_id": "igw-fadc869e", 
                    "origin": "CreateRoute", 
                    "state": "active"
                }
            ], 
            "tags": {}, 
            "vpc_id": "vpc-e3e4c084" ==> To the existing VPC
        }
    }
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @stalinstepin,

Thank you for the issue, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in #ansible-aws on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by stalinstepin** [comment]
File: lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py is up to date in my system.  Ran a diff command for the script in the above link with the one on my system and they both are the same.

```  15:41:45 as root on devbox in /tmp/Sybase_11857712 
→ diff ec2_vpc_route_table.py /usr/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/ec2_vpc_route_table.py

**Comment by ZuZuD** [comment]
Seems like the lookup argument is missing, try with the below update:
```
- name: Setting up custom route table.
      ec2_vpc_route_table:
          vpc_id: "{{ myvpc.vpc.id }}"
          region: us-west-1
          route_table_id: "{{my_route_tb.route_tables[0].associations[0].route_table_id}}"
          # tags:
          #   Name: Custom_Subnet
          routes:
            - dest: 0.0.0.0/0
              gateway_id: "{{ my_igw.gateway_id }}"
          lookup: id
```
More information on the [module documentation](https://docs.ansible.com/ansible/2.6/modules/ec2_vpc_route_table_module.html)
