### ISSUE TITLE
strange behavior with duplication in templates?

### ISSUE THREAD

**Issue by gregkare** [ansible/ansible#4397]
Wow, that issue title is a mouthful, but that's the best description I could come up with.

My variable is turned into a string, so when I iterate over it in a template it iterates over the characters (including brackets and quotes).

Here's a [Gist with just enough yml to reproduce it](https://gist.github.com/gkarekinian/2944f54fe85dbb359a91)

I'm seeing this behavior on ansible 1.3.2.

**Comment by mpdehaan** [comment]
Oh, I didn't catch this earlier.

This is an include combined with a "with_items".

The solution is to NOT attach an include to a with_items, as this is unsupported and consequently undocumented.

The solution is instead to loop over on this task:

template: src=job_generic_config_test.xml.j2
dest=/var/lib/jenkins/{{ name }}.xml
owner=jenkins group=nogroup mode=0755

include + with_items will be removed in a future release because it doesn't do what people think it does.

The underlying problem here is probably due to the reuse of the variable "item".

In any event, since this is include + with_items related and we've been telling folks to not do this for a couple of releases or more, I don't think we are going to fix this particular issue.

If you have questions about how to convert away from this to just passing the variable to a role, etc, happy to help, but I would suggest asking on the mailing list.

I have considered making include + with_items just attach "items" to every task inside but that's not always going to be the right thing to do.

**Comment by gregkare** [comment]
**EDIT**: I misunderstood what `delegate_to` was supposed to do, I've removed the first part.

I can't find anything helpful in the documentation and it doesn't seem to be organized in a logical way. The doc website doesn't have a search field so I'm using a local clone of the ansible repo to try to find information on templates. For instance it looks like passing variables directly to the template does absolutely nothing:

``` yml
- name: create job template {{ item.name }}
  template: src=jenkins/job_generic_config.xml.j2
            dest=/var/lib/jenkins/{{ item.name }}.xml
            owner=jenkins group=nogroup mode=0755
            job_name={{ item.name }}
  with_items: jenkins_jobs
```

Do you have any pointer, or should I try the mailing list?

**Comment by gregkare** [comment]
I managed to make my template work (I'm using `item.variable_name` everywhere), but I still have a problem. The reason why I wanted to pass variables to the template was to be able to have some variables with default values.

I want something like this:

``` yml
- name: create job template {{ item.name }}
  template: src=jenkins/job_generic_config.xml.j2
            dest=/var/lib/jenkins/{{ item.name }}.xml
            owner=jenkins group=nogroup mode=0755
            my_extra_option={{ item.my_extra_option|default(False) }}
  with_items: jenkins_jobs
```

However I don't have access to `my_extra_option` in the template. I really don't want to deal with logic in my template.

**Edit:**

I looked at the [source code](https://github.com/ansible/ansible/blob/bd20d3c9be69394eca12596610c4d617b9fe7fe1/library/files/template), it looks like you can't pass variables to templates, I'll try to pass them to the task instead to set  defaults on some of them.

**Another edit:**

I found the documentation to the template: http://www.ansibleworks.com/docs/modules.html#template
