### ISSUE TITLE
Handle literal SYN and ? in ios_config lines

### ISSUE THREAD

**Issue by yaplej** [ansible/ansible#43996]
##### SUMMARY

If you need to use a literal SYN and ? in the ios_config line the only way I found to work is by using the HEX value.  There was no way to represent the '^V' character to escape '?'.  Without '^V' first IOS will just assume your using the help system '?'.  When you use those HEX values the difference() always detects it as changed.

Originally reported here https://github.com/ansible/ansible/issues/30562.  That issue focused on the 'ignore_diff_lines:' not working correctly and is fixed in a pending PR.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Run playbook with lines that require being escaped.

```yaml
---

- hosts: access_switches

  tasks:

  - name: EEM Applet detect-mac
    ios_config:
      provider:
        timeout: 60
      lines:
        - 'event mat mac-address ^.*$ type add'
        - 'action 01.00 if $_mat_notification eq "add"'
        - 'action 01.01  cli command "enable"'
        - 'action 01.02  cli command "show int $_mat_intf_name switchport | inc Administrative Mode:"'
        - 'action 01.03  string match "*trunk*" "$_cli_result"'
        - 'action 01.04  syslog msg "Interface: $_mat_intf_name Result: $_cli_result"'
        - 'action 02.00  if $_string_result eq "0"'
        - 'action 02.01   cli command "show ver | i ^Copyright.*by"'
        - 'action 02.02   set i "0"'
        - 'action 03.00   foreach line "$_cli_result" "\n"'
        - 'action 04.00    if $i eq "0"'
        - 'action 04.01     regexp "^Copyright.*by\s*(.*)$" "$line" match manufacturer'
        - 'action 04.02     string trim "$manufacturer"'
        - 'action 04.03     set manufacturer "$_string_result"'
        - 'action 04.04    end'
        - 'action 04.05    increment i 1'
        - 'action 04.06   end'
        - 'action 05.00   foreach line "$manufacturer" " "'
        - 'action 05.01    append newmanufacturer "$line"'
        - 'action 05.02    append newmanufacturer "%20"'
        - 'action 05.03   end'
        - 'action 05.04   string trimright "$newmanufacturer" "%20"'
        - 'action 05.05   set manufacturer "$_string_result"'
        - 'action 05.06   cli command "show ver | i ^Model [Nn]umber"'
        - 'action 05.07   set i "0"'
        - 'action 06.00   foreach line "$_cli_result" "\n"'
        - 'action 07.00    if $i eq "0"'
        - 'action 07.01     regexp "^Model [Nn]umber\s*:\s*(.*)" "$line" match model_num'
        - 'action 07.02     string trim "$model_num"'
        - 'action 07.03     set model_num "$_string_result"'
        - 'action 07.04    end'
        - 'action 07.05    increment i 1'
        - 'action 07.06   end'
        - 'action 07.07   cli command "show ver | i ^System [Ss]erial [Nn]umber"'
        - 'action 07.08   set i "0"'
        - 'action 08.00   foreach line "$_cli_result" "\n"'
        - 'action 09.00    if $i eq "0"'
        - 'action 09.01     regexp "^System [Ss]erial [Nn]umber\s*:\s*(.*)" "$line" match serial_num'
        - 'action 09.02     string trim "$serial_num"'
        - 'action 09.03     set serial_num "$_string_result"'
        - 'action 09.04    end'
        - 'action 09.05    increment i 1'
        - 'action 09.06   end'
        # Cisco IOS still needs special character ? escaped.
        # Typically this is CTRL+V or also SYN character.
        # HEX ASCII value \x16 is used for SYN.
        # HEX ASCII value \x3f is used for ?.
        - 'action 09.07   cli command "more $identityserver/\x16\x3fman=$manufacturer&mod=$model_num"'
        - 'action 09.08   cli command "more $identityserver/\x16\x3fmod=$model_num&sn=$serial_num"'
        - 'action 09.09   cli command "more $identityserver/\x16\x3fmac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num"'
        - 'action 09.10   string match "*(I/O error)*" "$_cli_result"'
        - 'action 10.00   if $_string_result eq "0"'
        - 'action 10.01    syslog msg "$_cli_result"'
        - 'action 10.02    foreach line "$_cli_result" " "'
        - 'action 10.03     string match "*http*" "$line"'
        - 'action 11.00     if $_string_result eq "0"'
        - 'action 11.01      regexp "(.*:.*)" "$line" match response'
        - 'action 12.00      if $_regexp_result eq "1"'
        - 'action 12.01       syslog msg "Regexp Result: $_regexp_result Regexp Match: $match Regexp Response: $response"'
        - 'action 12.02       regexp "(.*):" "$response" match macro'
        - 'action 12.03       regexp ":(.*)" "$response" match description'
        - 'action 12.04      end'
        - 'action 12.05     end'
        - 'action 12.06    end'
        - 'action 13.00   else'
        - 'action 13.01    syslog msg "Call to identity server failed! Result: $_cli_result"'
        - 'action 13.02    cli command "exit"'
        - 'action 13.03    exit 1'
        - 'action 13.04   end'
        - 'action 13.05   cli command "show run | i macro name $macro"'
        - 'action 13.06   string match "*$macro*" "$_cli_result"'
        - 'action 14.00   if $_string_result eq "1"'
        - 'action 14.01    cli command "config t"'
        - 'action 14.02    cli command "interface $_mat_intf_name"'
        - 'action 14.03    cli command "macro apply $macro DESCRIPTION $description"'
        - 'action 14.04    syslog msg "Apply $macro Macro Result: $_cli_result"'
        - 'action 14.05    cli command "end"'
        - 'action 14.06    syslog msg "Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro"'
        - 'action 15.00   else'
        - 'action 15.01    cli command "show run | i macro name $defaultmacro"'
        - 'action 15.02    string match "*$defaultmacro*" "$_cli_result"'
        - 'action 16.00    if $_string_result eq "1"'
        - 'action 16.01     cli command "config t"'
        - 'action 16.02     cli command "interface $_mat_intf_name"'
        - 'action 16.03     cli command "macro apply $defaultmacro DESCRIPTION $description"'
        - 'action 16.04     cli command "end"'
        - 'action 16.05    end'
        - 'action 16.06   end'
        - 'action 16.07  end'
        - 'action 16.08  cli command "exit"'
        - 'action 16.09 end'
      parents: event manager applet detect-mac
      before: no event manager applet detect-mac
      after: exit
      match: line
      replace: block
```

##### EXPECTED RESULTS

playbook run once on subsequent runs difference() would see HEX value and literal values the same.

##### ACTUAL RESULTS

```

```
