### ISSUE TITLE
the templates module dest dir bugs

### ISSUE THREAD

**Issue by zhangguanzhang** [ansible/ansible#43999]
ansible_version: ansible 2.5.4

```yaml
- name: 分发非HA资源文件模板到每台Master
  template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
    - { src: '10-kubelet.conf.j2', dest: '/etc/systemd/system/kubelet.service.d' }

- name: 分发HA资源文件模板到每台Master
  template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}
  with_items:
    - { src: 'haproxy.cfg.j2', dest: "{{ haproxy_path }}" }
  when: (groups['Master'] | length)  != 1
- name: debug
  debug: msg="{{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}"
  with_items:
    - { src: 'haproxy.cfg.j2', dest: "{{ haproxy_path }}" }
```
there is the output
```
TASK [test : 分发HA资源文件模板到每台Master] ******************************************************************************************************************************************
skipping: [192.168.126.114] => (item={u'dest': u'/etc/haproxy', u'src': u'haproxy.cfg.j2'}) 
changed: [192.168.126.112] => (item={u'dest': u'/etc/haproxy', u'src': u'haproxy.cfg.j2'})
changed: [192.168.126.113] => (item={u'dest': u'/etc/haproxy', u'src': u'haproxy.cfg.j2'})

TASK [test : debug] ********************************************************************************************************************************************************
ok: [192.168.126.112] => (item=None) => {
    "msg": "/etc/haproxy/haproxy.cfg"
}
skipping: [192.168.126.114] => (item=None) 
ok: [192.168.126.113] => (item=None) => {
    "msg": "/etc/haproxy/haproxy.cfg"
}

```

there is the infact
```bash
[root@k8s-m1 ~]# ll /etc/haproxy/haproxy.cfg/haproxy.cfg.j2 
-rw-r--r-- 1 root root 629 Aug 11 22:28 /etc/haproxy/haproxy.cfg/haproxy.cfg.j2
[root@k8s-m1 ~]# grep haproxy_path group_vars/all.yml 
haproxy_path: /etc/haproxy
[root@k8s-m1 ~]# ll /etc/systemd/system/kubelet.service.d
total 4
-rw-r--r-- 1 root root 1108 Aug 11 22:01 10-kubelet.conf
```
it added a layer of "haproxy.cfg" directory when i used the when
