### ISSUE TITLE
docker_image module doen't update image on private registry

### ISSUE THREAD

**Issue by erolg** [ansible/ansible#44077]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/...../ansible/library', u'/...../ansible/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### STEPS TO REPRODUCE
Trying to push an image to a private registry with the above code:

```yaml
- name: pushing spesific image to private registry
  docker_image:
     name: "image"
     repository: "{{ docker_registry }}/user/image"
     state: present
     pull: no
     push: yes
     force: yes
```

##### EXPECTED RESULTS
When the image is already present in private registry, the code should update image from local.

##### ACTUAL RESULTS
Because of force and state values, ansible trying to pull image from docker hub (while pull attribute says no)

```
The full traceback is:
  File "/tmp/ansible_8V8r6f/ansible_modlib.zip/ansible/module_utils/docker_common.py", line 467, in pull_image
    for line in self.pull(name, tag=tag, stream=True, decode=True):
  File "/usr/lib/python2.7/dist-packages/docker/api/image.py", line 200, in pull
    self._raise_for_status(response)
  File "/usr/lib/python2.7/dist-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "archive_path": null, 
            "buildargs": null, 
            "cacert_path": null, 
            "cert_path": null, 
            "container_limits": null, 
            "debug": false, 
            "docker_host": null, 
            "dockerfile": null, 
            "filter_logger": false, 
            "force": true, 
            "http_timeout": null, 
            "key_path": null, 
            "load_path": null, 
            "name": "image", 
            "nocache": false, 
            "path": null, 
            "pull": false, 
            "push": true, 
            "repository": "repository/user/image", 
            "rm": true, 
            "ssl_version": null, 
            "state": "present", 
            "tag": "latest", 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "use_tls": "no"
        }
    }, 
    "msg": "Error pulling image image:latest - 404 Client Error: Not Found (\"{\"message\":\"pull access denied for image, repository does not exist or may require 'docker login'\"}\")"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_image.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_image.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @softzilla
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by LucidOne** [comment]
I might be having a similar issue.

I think there can be a race that fails silently if you restart the registry immediately before trying to push to it. It looks like the image gets tagged but the image itself doesn't pushed.

I put in a sleep but it probably just needs a `wait_for`

**Comment by LucidOne** [comment]
So I have "fixed" my issue, though I'm not sure I understand it. I think it is related to this issue but :alien: .

The private registry is started with
```yaml
- name: "Start Docker Registry"
  docker_container:
    name: "registry"
    recreate: yes
    image: registry:2
    init: yes
    network_mode: "bridge"
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
    restart: yes
    restart_policy: "always"
```

This does not push the image to the registry
```yaml
- name: "Pull Debian Stretch image"
  docker_image:
    name: "debian:stretch"
- name: "Push Debian Stretch image"
  docker_image:
    name: "debian:stretch"
    repository: "localhost:5000/debian:stretch"
    tag: "debian:stretch"
    push: yes
```

It looks to me like tagging succeeds but the push operation is failing.
```bash
$ sudo docker image pull localhost:5000/debian:stretch
Error response from daemon: manifest for localhost:5000/debian:stretch not found
```

The issue can be fixed by manually running
```bash
$ sudo docker image push localhost:5000/debian:stretch
```

or with `force: yes`
```yaml
- name: "Push Debian Stretch image"
  docker_image:
    name: "debian:stretch"
    repository: "localhost:5000/debian:stretch"
    tag: "debian:stretch"
    push: yes
    force: yes
```

I have tried `-vvvvv` and a few other options but I still can't figure out why. I'm giving up and implementing HTTPS on the registry before looking into this more.

**Comment by ansibot** [comment]
cc @felixfontein
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by geerlingguy** [comment]
I've also run into this when pushing images to AWS ECR.

**Comment by Chrislevi** [comment]
I've hit the same wall, currently trying to populate a private registry with local images.

with these arguments I get an unexpected behavior.  Still pulls even though its stated as no.
`pull: no`
` push: yes`
`force: yes`

any news?

**Comment by felixfontein** [comment]
The module's interface is kind of strange. Anyway, the behavior is not surprising when looking at the code:
```.py
        if not image or self.force:
            if self.path:
                # Build the image
                [...]
            elif self.load_path:
                # Load the image from an archive
                [...]
            else:
                # pull the image
                [...]
```
If you specify `force`, it will always try to build, load, or pull the image. (Also see the documentation for `force`, which exactly says that.) So don't specify `force` if you don't want to pull.

For tagging and pushing, the code looks as follows:
```.py
        if self.push and not self.repository:
            self.push_image(self.name, self.tag)
        elif self.repository:
            self.tag_image(self.name, self.tag, self.repository, force=self.force, push=self.push)
```
This looks strange, because `push` is only used then `repository` is not set, but that's because `tag_image()` will also do pushing if requested. (A clarifying comment would definitely help.) Interestingly, the `tag_image()` also uses the `force` parameter in ways that are **not** documented (namely: force tagging, even if image with that name already exists).

So if `repository` is NOT specified and `push` is `true`, it will push. Otherwise, if `repository` is given, it will tag. This is something which is **not** clean from the documentation to me, because the documentation for `push` explicitly says `Specify the registry as part of the I(name) or I(repository) parameter.`.

And even worse: if the image is found (i.e. it has been tagged before, might be a totally different image but who cares...), and `force` is not specified, it won't push. It will only push if it tags the image.

**Comment by ansibot** [comment]
cc @WojciechowskiPiotr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
resolved_by_pr #52894

**Comment by lucasbasquerotto** [comment]
Thanks @felixfontein!

While version 2.8 isn't released, your other post helped me to solve this issue for my use case.

Instead of:

```yaml
- name: "tag and push to docker registry"
  docker_image:
    name: "local-image:tagname"
    repository: "reponame:tagname"
    push: yes
```

**I split in 2 steps**, so that push and repository aren't both defined in the same task:

```yaml
# create a local image with the same repository and tag that will be in the remote registry
- name: "tag the image"
  docker_image:
    name: "local-image:tagname"
    repository: "reponame:tagname"

- name: "push to docker registry"
  docker_image:
    name: "reponame:tagname"
    push: yes
```

Which is equivalent to:

```sh
docker tag local-image:tagname reponame:tagname
docker push reponame:tagname
```
