### ISSUE TITLE
win_nssm : extra space added in AppParameters

### ISSUE THREAD

**Issue by ksubileau** [ansible/ansible#44079]
##### SUMMARY
Under certain circumstance, the command line parameters passed to the `app_parameters_free_form` module parameter (and maybe with `app_parameters` too) may be corrupted with the addition of an extra space.
This seems to happen only when a parameter start with a dash and is followed by a period (e.g. `-Dcom.test` or `param1 -Dcom.test param2`).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_nssm

##### ANSIBLE VERSION

```
devel
```

##### OS / ENVIRONMENT

From Ubuntu 16.04.3
Managing Windows Server 2016

##### STEPS TO REPRODUCE

```yaml
---
- hosts: adirec01-rob001
  gather_facts: true
  tasks:
    - name: Install service
      win_nssm:
        name: nssm_test
        application: 'C:\Windows\System32\cmd.exe'
        app_parameters_free_form: '-Dcom.test.string=value'
        state: present
```

##### EXPECTED RESULTS
```
C:\Windows\system32> nssm get service_test AppParameters
-Dcom.test.string=value
```

##### ACTUAL RESULTS
```
C:\Windows\system32> nssm get service_test AppParameters
-Dcom .test.string=value
```
Remark the space added between '-Dcom' and '.test'.
We can also inspect the actual result by looking at the registry value `AppParameters` under `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\nssm_test\Parameters`.
