### ISSUE TITLE
"Failed to find required executable emerge in [...]"

### ISSUE THREAD

**Issue by gkroon** [ansible/ansible#44097]
##### SUMMARY

When using Ansible to install packages on a Gentoo system, Ansible complains that `emerge` is not found on the target system and installation cannot proceed.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

portage

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/gkroon/git/ansible/ansible.cfg
  configured module search path = ['/home/gkroon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.6/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.6/ansible
  python version = 3.6.5 (default, May 18 2018, 06:29:02) [GCC 6.4.0]

```

##### CONFIGURATION

DEFAULT_HOST_LIST(/home/gkroon/git/ansible/ansible.cfg) = ['/home/gkroon/git/ansible/.ansible_hosts']

##### OS / ENVIRONMENT

Gentoo

##### STEPS TO REPRODUCE

Example task, followed by running: `ansible-playbook play.yml --tags portage`

```yaml
- name: Install portage packages
  portage:
    name: eclean-kernel
    state: latest
  when: inventory_hostname == "gentoo.lan"
  tags: portage
  become: true
```

##### EXPECTED RESULTS

I was expecting Ansible to find `emerge` on the system.

##### ACTUAL RESULTS

Ansible did not find 'emerge' on the system and installation could not proceed.

```
fatal: [gentoo.lan]: FAILED! => {"changed": false, "msg": "Failed to find required executable emerge in paths: /usr/local/sbin:/usr/local/bin:/usr/bin:/sbin:/usr/sbin"}
```
