### ISSUE TITLE
Return cluster name as value in returned dict, if vm is within a a cluster 

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#44101]
##### SUMMARY

cluster value not present in response data.

##### ISSUE TYPE
 - Feature Idea
add value "cluster" to response dict, 
if the vm resides within a cluster

##### COMPONENT NAME

vmware_vm_facts

##### ANSIBLE VERSION

```
ansible 2.7.0dev
```

##### STEPS TO REPRODUCE

```yaml
- name: Gather all registered virtual machines
  vmware_vm_facts:
    hostname: esxi_or_vcenter_ip_or_hostname
    username: username
    password: password
    uuid: 2341234123412341234123
  delegate_to: localhost
  register: vmfacts
```

##### EXPECTED RESULTS

return cluster in the response data

##### ACTUAL RESULTS

cluster information is not apart of the response data

```

```
