### ISSUE TITLE
Expand the "cluster" option for configuration management, not just provisioning

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#44100]
##### SUMMARY

cluster option limited to provisioning, would like it expanded to config management.

##### ISSUE TYPE
 - Feature Idea
im looking at a use case where i specify clusters and the configuration is applied to all hosts in that cluster, host in this sense being a network host.

The "vmware_host_config_mangement" module, provides capacity to do this for hypervisors,
as this module seems to be the one used for modifying VM configurations, 
would it be possible to expand the "cluster" option so that all vm's in that given cluster receive the specified configuration.

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.7.dev0
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- name: Synchronize vm configuration
  vmware_guest:
    hostname: "{{ vcenter }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    cluster: "{{ targetcluster }}"
    customvalues:
      - key: tools.setinfo.sizelimit
        value: "11111"
  delegate_to: localhost
  register: factxyz
```

##### EXPECTED RESULTS

apply the configuration to all vm's in that cluster.

##### ACTUAL RESULTS

applies configuration to all vm's in the vCenter with no scope limitations.

```

```
