### ISSUE TITLE
ios_config always reruns "clock summer-time" command

### ISSUE THREAD

**Issue by geertn444** [ansible/ansible#44111]
##### SUMMARY

Ansible always reruns the command (changed) although the line is present literally in the config.
I don't know why. Is it because the line contains "-" or ":" characters ?
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'
/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (R
ed Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

Ansible Tower vagrant
##### STEPS TO REPRODUCE

sh run | i summer-time

Switch#sh run | i summer-time
clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00

```yaml
- hosts: all
  gather_facts: no
  connection: network_cli
  
  tasks: 
  
  - name: configure summertime
    become: yes
    ios_config:
     lines:
      - clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00
     match: exact (or match:line, it is the same effect)
```

##### EXPECTED RESULTS

Skip config as "not changed"
##### ACTUAL RESULTS

{
    "_ansible_parsed": true,
    "commands": [
        "clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00"
    ],
    "_ansible_no_log": false,
    **"changed": true,**
    "updates": [
        "clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00"
    ],
    "invocation": {
        "module_args": {
            "multiline_delimiter": "@",
            "authorize": null,
            "force": false,
            "diff_against": null,
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "port": null,
            "before": null,
            "auth_pass": null,
            "parents": null,
            "provider": null,
            "save": false,
            "match": "exact",
            "username": null,
            "defaults": false,
            "after": null,
            "host": null,
            "password": null,
            "diff_ignore_lines": null,
            "src": null,
            "ssh_keyfile": null,
            "lines": [
                "clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00"
            ],
            "intended_config": null,
            "timeout": null,
            "backup": false
        }
    },
    "banners": {}
}

```

```
