### ISSUE TITLE
Mikrotik - "paramiko.transport"

### ISSUE THREAD

**Issue by AnthonyShahine21** [ansible/ansible#44117]
##### SUMMARY

I'm trying to re-create a Bridge interface on Mikrotik router using the "raw"
I tried the command directly on Mikrotik and i got this output 
"failure: already have device with such name"

However, using the "raw"  i saw the below
"No handlers could be found for logger "paramiko.transport" "
without any output

##### ISSUE TYPE
 - Bug Report
 - no output
##### COMPONENT NAME
raw
##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### OS / ENVIRONMENT

Debian 9
python version = 2.7.13

##### STEPS TO REPRODUCE

```yaml
---
- name: Tests
  hosts: mikrotik
  gather_facts: no
  connection: paramiko

  tasks:
    - name: Bridge Name
      raw: ' interface bridge add name="LAN Bridge" arp=enabled mtu=1500; quit'
      register: Bridge
   - debug: "{{ Bridge.changed }}"

```

##### EXPECTED RESULTS

This Bridge interface already exists, so i was expected to receive the same output as on Mikrotik
"failure: already have device with such name"
##### ACTUAL RESULTS

```
PLAYBOOK: bonding.yml ***********************************************************************************************************************************
1 plays in bonding.yml

PLAY [Tests] ********************************************************************************************************************************************
META: ran handlers

TASK [Bridge Name] **************************************************************************************************************************************
task path: /etc/ansible/roles/ansible-mikrotik-master/tests/integration/bonding.yml:9
<192.168.139.174> ESTABLISH CONNECTION FOR USER: None on PORT 22 TO 192.168.139.174
<192.168.139.174> EXEC interface bridge add name="LAN Bridge" arp=enabled mtu=1500; quit
No handlers could be found for logger "paramiko.transport"
```
