### ISSUE TITLE
netapp_e_lun_mapping "Module Failure"

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#44124]
##### SUMMARY
i tried to run the above mentioned module and i get "MODULE FAILURE" with return code 1 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

storage/netapp/netapp_e_lun_mapping.py

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0

```

##### CONFIGURATION

using the module provided by netapp ansible forked branch

##### OS / ENVIRONMENT

linux

##### STEPS TO REPRODUCE

run the module

```yaml
- name: Mappings
  netapp_e_lun_mapping:
    ssid: "{{ ssid }}"
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    validate_certs: "{{ validate_certs }}"
    target: "{{ item.0.target }}"   
    state: "{{ item.1.state }}"
    volume_name: "{{ item.1.volume_name }}"
  loop: "{{ mappings|subelements('volumes') }}"
  when: mappings is defined

# mappings
mappings:
  - target: tvdwnode-203
    volumes: 
      - volume_name: vol_01
        state: present
```

##### EXPECTED RESULTS

mapping successfull
##### ACTUAL RESULTS

```
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1

```
