### ISSUE TITLE
ansible task using include_tasks and with_dict

### ISSUE THREAD

**Issue by jackalsin** [ansible/ansible#44136]
##### SUMMARY

ansible include_tasks seems not working with_dict correctly.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible include_tasks with_dict

##### ANSIBLE VERSION

```
ansible-playbook 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### CONFIGURATION

Nothing 

##### OS / ENVIRONMENT

Redhat 7, using localhost

##### STEPS TO REPRODUCE

```yaml
# tasks/main.yml
- name: Set Big Dict
  set_fact:
    big_dict: {"key_1": {"value_key_1": "value_value_1","value_key_2": "value_value_2" }}

  # This works
- name: Call sub_task_big_dict.yml with include
  include: sub_task_big_dict.yml
    var1={{ item.key }}
    var2={{ item.value.value_key_1 }}
    var3={{ item.value.value_key_2 }}
  with_dict: "{{ big_dict }}"
```

```yaml
# tasks/sub_task_big_dict.yml
---
- name: print undefined var in sub_task.yml
  debug:
    msg: "{{ var1 }} {{ var2 }} {{ var3 }}"
```
Above works, but if we change the `tasks/main.yml` to the following content
```yaml
- name: Set Big Dict
  set_fact:
    big_dict: {"key_1": {"value_key_1": "value_value_1","value_key_2": "value_value_2" }}

# This doesn't work
- name: Call sub_task.yml with include_tasks
  include_tasks: sub_task_big_dict.yml
  var:
    var1: "{{ item.key }}"
    var2: "{{ item.value.value_key_1 }}"
    var3: "{{ item.value.value_key_2 }}"
  with_dict: "{{ big_dict }}"
```
it won't will think `var1` is undefined.

##### EXPECTED RESULTS

The above 2 version of tasks/main.yml should generate the same result

##### ACTUAL RESULTS

it will throw the following error:
```bash
[root@8b2686c8e760 ansible]# ansible-playbook -vvv block_condition.yml
ansible-playbook 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see: http://docs.ansible.com/ansible/playbooks_roles.html#task-
include-files-and-encouraging-reuse   for currently supported syntax regarding included files and variables. This feature will be removed in version 2.7. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAYBOOK: block_condition.yml *******************************************************************************************************************************************
1 plays in block_condition.yml

PLAY [localhost] ********************************************************************************************************************************************************
META: ran handlers

TASK [block_condition : Set Big Dict] ***********************************************************************************************************************************
task path: /mnt/ansible-test/opt/IMAppliance/ansible/roles/block_condition/tasks/main.yml:92
ok: [localhost] => {
    "ansible_facts": {
        "big_dict": {
            "key_1": {
                "value_key_1": "value_value_1",
                "value_key_2": "value_value_2"
            }
        }
    },
    "changed": false
}

TASK [block_condition : Call sub_task.yml with include_tasks] ***********************************************************************************************************
task path: /mnt/ansible-test/opt/IMAppliance/ansible/roles/block_condition/tasks/main.yml:107
included: /mnt/ansible-test/opt/IMAppliance/ansible/roles/block_condition/tasks/sub_task_big_dict.yml for localhost

TASK [block_condition : print undefined var in sub_task.yml] ************************************************************************************************************
task path: /mnt/ansible-test/opt/IMAppliance/ansible/roles/block_condition/tasks/sub_task_big_dict.yml:2
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'var1' is undefined\n\nThe error appears to have been in '/mnt/ansible-test/opt/IMAppl
iance/ansible/roles/block_condition/tasks/sub_task_big_dict.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offen
ding line appears to be:\n\n---\n- name: print undefined var in sub_task.yml\n  ^ here\n"
}
        to retry, use: --limit @/mnt/ansible-test/opt/IMAppliance/ansible/block_condition.retry

PLAY RECAP **************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Your issue is in using the wrong task argument.  You used `var`, the correct argument is `vars`.

You actually received a warning about specifying include variables at the top-level, and it applies to both `include` and `include_tasks`, and was squashed into a single warning.

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see: http://docs.ansible.com/ansible/playbooks_roles.html#task-
include-files-and-encouraging-reuse   for currently supported syntax regarding included files and variables. This feature will be removed in version 2.7. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

```
- name: Call sub_task.yml with include_tasks
  include_tasks: sub_task_big_dict.yml
  vars:
    var1: "{{ item.key }}"
    var2: "{{ item.value.value_key_1 }}"
    var3: "{{ item.value.value_key_2 }}"
  with_dict: "{{ big_dict }}"
```

Updating as such, produces the following output:

```
ok: [localhost] => {
    "msg": "key_1 value_value_1 value_value_2"
}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jackalsin** [comment]
Okay. Thanks.
May I ask what's the intention of doing like this?
```yaml
# calling with with_dict should use `vars`
- name: Call sub_task.yml with include_tasks
  include_tasks: sub_task_big_dict.yml
  vars:
    var1: "{{ item.key }}"
    var2: "{{ item.value.value_key_1 }}"
    var3: "{{ item.value.value_key_2 }}"
  with_dict: "{{ big_dict }}"

# Directly citing the variable should use `var`
- name: Call sub_task.yml with include_tasks
  include_tasks: sub_task_big_dict.yml
  var:
    var1: "{{ var1 }}"
    var2: "{{ var2 }}"
    var3: "{{ var3 }}"
```
