### ISSUE TITLE
include_tasks vars doesn't work with `when` with duplicated variable name. 

### ISSUE THREAD

**Issue by jackalsin** [ansible/ansible#44145]
##### SUMMARY

In the `vars` in the `include_tasks`, if we use the same variable name in the `when`, it will skip the task.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`include_tasks`

##### ANSIBLE VERSION

```bash
[root@8b2686c8e760 ansible]# ansible --version
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION

`N/A`

##### OS / ENVIRONMENT

`N/A`

##### STEPS TO REPRODUCE

```yaml
# tasks/main.yml
- name: Set Big Dict
  set_fact:
    big_dict: {"key_1": {"value_key_1": "value_value_1","value_key_2": "value_value_2" }}

- name: Call sub_task.yml with include_tasks
  include_tasks: sub_task_big_dict.yml
  vars:
    var1: "{{ item.key }}"
    var2: "{{ item.value.value_key_1 }}"
    var3: "{{ item.value.value_key_2 }}"
  with_dict: "{{ big_dict }}"
  when:
    # - abac is not defined
    - var1 is not defined
```

```yaml
# tasks/sub_task_big_dict.yml
---
- name: print undefined var in sub_task.yml
  debug:
    msg: "{{ var1 }} {{ var2 }} {{ var3 }}"
```

this will skip the task `Call sub_task.yml with include_tasks`

However, if we replace `var1 is not defined` to `abac is not defined`, it will execute the task

##### EXPECTED RESULTS

It should execute the task since `var1` is not defined.

##### ACTUAL RESULTS

```bash
[root@8b2686c8e760 ansible]# ansible-playbook -vvvv block_condition.yml
ansible-playbook 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: block_condition.yml ********************************************************************************************************************************
1 plays in block_condition.yml

PLAY [localhost] *********************************************************************************************************************************************
META: ran handlers

TASK [block_condition : Set Big Dict] ************************************************************************************************************************
task path: /mnt/ansible-test/opt/IMAppliance/ansible/roles/block_condition/tasks/main.yml:110
ok: [localhost] => {
    "ansible_facts": {
        "big_dict": {
            "key_1": {
                "value_key_1": "value_value_1",
                "value_key_2": "value_value_2"
            }
        }
    },
    "changed": false
}

TASK [block_condition : Call sub_task.yml with include_tasks] ************************************************************************************************
task path: /mnt/ansible-test/opt/IMAppliance/ansible/roles/block_condition/tasks/main.yml:161
skipping: [localhost] => (item={'value': {u'value_key_1': u'value_value_1', u'value_key_2': u'value_value_2'}, 'key': u'key_1'})  => {
    "changed": false,
    "item": {
        "key": "key_1",
        "value": {
            "value_key_1": "value_value_1",
            "value_key_2": "value_value_2"
        }
    },
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

```
