### ISSUE TITLE
copy content= with_password: leaks password in result status

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#4414]
I have following snippet in playbook:

```
  - name: Create Frontend/Jenkins auth password
    copy: content={{item}} dest=/var/lib/jenkins-password
    with_password:
        - $cred_store/jenkins/frontend
```

Executing that leads to:

```
ok: [localhost] => (item=KS,RUhxMDKsLxsO29BYB)
```

which is password leak and thus security issue.
