### ISSUE TITLE
user "expires: -1" sets an expiry date if not set, so the account cannot log in

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#44155]
##### SUMMARY

When creating a new user with the "user" module setting "expires: -1" (or any other negative value) creates an expired account (so it cannot log in).

The [doc](https://docs.ansible.com/ansible/2.6/modules/user_module.html) for expires says "Since version 2.6 you can remove the expiry time specify a negative value. Currently supported on GNU/Linux and FreeBSD." Technically, it does what it says: it *removes* an expiry time if one is set. However, if an expiry time is not set I would expect this to leave it unset (i.e. leave the account able to log in).

The use case is that I want to ensure a user exists and is not expired (whether or not it existed or was expired before).

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

user

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /media/sf_work/lops/ansible.cfg
  configured module search path = [u'/home/em/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

Ubuntu 16.04 control machine, Ubuntu 18.04 target

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  become: yes
  gather_facts: false
  tasks:

  # Create a new user with a negative "expires" value
  - user:
      name: "ansible-expires-test"
      state: absent
  - user:
      name: "ansible-expires-test"
      state: present
      # This sets the account expiry to 1970-Jan-01 instead of creating an account that doesn't expire
      expires: -1
  - raw: "chage -l ansible-expires-test |grep -C 0 Account"
    register: expiry_new

  # Expire the account and unexpire it    
  - user:
      name: "ansible-expires-test"
      state: present
      expires: 1234567890
  - user:
      name: "ansible-expires-test"
      state: present
      # This removes the expiry date set above, as expected
      expires: -1
  - raw: "chage -l ansible-expires-test |grep -C 0 Account"
    register: expiry_unexpired
    
  - debug:
      msg: "New account: {{ expiry_new.stdout }}, expired and unexpired account: {{ expiry_unexpired.stdout }}"
```

##### EXPECTED RESULTS

```
user:
  state: present
  expires: -1
```
ensure that the user account exists and never expires.

##### ACTUAL RESULTS

When an account has no expiry date an expiry date of 1970-Jan-01 is set, however when it has a (non-negative) expiry date the exact same task removes that expiry date.

```
New account: Account expires : Jan 01, 1970
expired and unexpired account: Account expires : never
```
