### ISSUE TITLE
Error when used Grafana datasource name with spaces

### ISSUE THREAD

**Issue by nikolaev-rd** [ansible/ansible#44154]
##### SUMMARY

Error from Garafan API when used datasource name with space(s).

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

grafana_datasource

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

DEFAULT_ASK_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_SSH_TRANSFER_METHOD(/etc/ansible/ansible.cfg) = piped
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

ansible host: CentOS 7 (3.10.0-693.5.2.el7.x86_64)
remote host: CentOS 7 (3.10.0-693.5.2.el7.x86_64)
Grafana version: 4.6.2-1 x86_64

##### STEPS TO REPRODUCE

Just use Grafana datasource name with space(s) in grafana_datasource module.

```yaml
---
- hosts: all

  tasks:
    - name: "Create Grafana datasource (PostgreSQL)"
      grafana_datasource:
        name: "name with spaces"
        grafana_url: "http://grafana-host:3000/"
        grafana_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        org_id: "1"
        ds_type: "postgres"
        url: "postgres-host:5432"
        database: "postgres"
        user: "postgres"
        password: "******"
        sslmode: "disable"
        state: "present"
      register: grafana_datasource_create
      failed_when:
        - "'Datasource added' not in grafana_datasource_create.msg"
        - "'already exists' not in grafana_datasource_create.msg"
```

##### EXPECTED RESULTS

Grafana datasource added.

##### ACTUAL RESULTS

HTTP Error 400: Bad Request

```
PLAY [all] ****************************************************************************************************************************************


TASK [Gathering Facts] ****************************************************************************************************************************

ok: [localhost]

TASK [Create Grafana datasource (PostgreSQL)] ****************************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "error <class '__main__.GrafanaAPIException'> : Unable to get datasource name with spaces : {'body': '<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>400 Bad Request</title>\\n</head><body>\\n<h1>Bad Request</h1>\\n<p>Your browser sent a request that this server could not understand.<br />\\n</p>\\n</body></html>\\n', 'date': 'Tue, 14 Aug 2018 13:50:47 GMT', 'content-length': '226', 'status': 400, 'msg': 'HTTP Error 400: Bad Request', 'url': 'http://grafana-host:3000/api/datasources/name/name with spaces', 'content-type': 'text/html; charset=iso-8859-1', 'connection': 'close', 'server': 'Apache/2.4.6 (CentOS) PHP/5.4.16'} "}
        to retry, use: --limit @/opt/ansible/grafana-datasource.retry

PLAY RECAP ****************************************************************************************************************************************
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/grafana_datasource.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/grafana_datasource.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @seuf
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nikolaev-rd** [comment]
The only workaround that I found is using `uri` module instead of `grafana_datasource`:
```yaml
---
- hosts: all
  
  - vars:
    - grafana_url: "http://grafana-host:3000"
    - grafana_data_source: {
        name: "datasource name with spaces",
        database: "postgres",
        type: "postgres",
        url: "postgres-host:5432",
        user: "postgres",
        password: "******",
        access: "proxy",
        sslmode: "disable"
      }
    - grafana_api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  
  tasks:
    - name: "Create Grafana datasource (PostgreSQL)"
      uri:
        headers: 
          Content-Type: "application/json"
          Authorization: "Bearer {{grafana_api_key}}"
        url: "{{ grafana_url }}/api/datasources"
        method: POST
        body: "{{ grafana_data_source | to_json }}"
        body_format: json
      tags: 
        - grafana
      register: grafana_datasource_create_result
      changed_when: grafana_datasource_create_result.status == 200
```
