### ISSUE TITLE
Wrong win_feature example in documentation

### ISSUE THREAD

**Issue by dermeister0** [ansible/ansible#44167]
##### SUMMARY
win_feature does not support list to specify multiple features. Need to use comma-separated string instead. However, documentation has a wrong example.

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

win_feature
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/anton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/anton/.local/lib/python2.7/site-packages/ansible
  executable location = /home/anton/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Running on Ubuntu 16.04. Managing Windows Server 2012 R2.

##### STEPS TO REPRODUCE

Works fine:

```yaml
- hosts: webservers
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server, Web-Asp-Net45
```

Returns error:

```yaml
- hosts: webservers
  tasks:
    - name: Install IIS
      win_feature:
        name:
          - Web-Server
          - Web-Asp-Net45
```

##### EXPECTED RESULTS

https://docs.ansible.com/ansible/latest/modules/win_feature_module.html page contains correct example.

##### ACTUAL RESULTS

```
fatal: [web.example.local]: FAILED! => {
    "changed": false,
    "exitcode": "InvalidArgs",
    "feature_result": [],
    "msg": "Failed to add feature",
    "reboot_required": false,
    "restart_needed": false,
    "success": false
}
```
