### ISSUE TITLE
When we delete one or more nsg security group rule(s) on azure and rerun our ansible playbook, it does not create them on azure.

### ISSUE THREAD

**Issue by gurdipedos** [ansible/ansible#44160]
##### SUMMARY

When we delete one or more nsg security group rule(s) on azure and rerun our ansible playbook, it does not create them on azure.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_securitygroup

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Aug  9 2018, 11:59:02) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

Using standard ansible.cfg file with all settings commented out.  Have included the pip list below.
PS I also upgraded all the pip's to the latest version and still have the same issue.

```
Package                      Version
---------------------------- ---------
adal                         1.0.2
ansible                      2.6.2
applicationinsights          0.11.6
argcomplete                  1.9.4
asn1crypto                   0.24.0
azure-cli-core               2.0.44
azure-cli-nspkg              3.0.3
azure-cli-telemetry          1.0.0
azure-common                 1.1.14
azure-mgmt-batch             5.0.1
azure-mgmt-compute           4.0.1
azure-mgmt-containerinstance 1.0.0
azure-mgmt-containerregistry 2.1.0
azure-mgmt-containerservice  4.2.2
azure-mgmt-dns               2.0.0
azure-mgmt-keyvault          1.1.0
azure-mgmt-network           2.0.1
azure-mgmt-nspkg             2.0.0
azure-mgmt-rdbms             1.2.0
azure-mgmt-resource          2.0.0
azure-mgmt-sql               0.9.1
azure-mgmt-storage           2.0.0
azure-mgmt-web               0.35.0
azure-nspkg                  2.0.0
azure-storage                0.36.0
bcrypt                       3.1.4
certifi                      2018.8.13
cffi                         1.11.5
chardet                      3.0.4
colorama                     0.3.9
cryptography                 2.3.1
entrypoints                  0.2.3
et-xmlfile                   1.0.1
humanfriendly                4.16.1
idna                         2.7
isodate                      0.6.0
jdcal                        1.4
jeepney                      0.3.1
Jinja2                       2.10
jmespath                     0.9.3
keyring                      13.2.1
knack                        0.4.2
MarkupSafe                   1.0
msrest                       0.5.4
msrestazure                  0.5.0
oauthlib                     2.1.0
openpyxl                     2.5.5
packaging                    17.1
paramiko                     2.4.1
pip                          18.0
pip-review                   1.0
portalocker                  1.2.1
pyasn1                       0.4.4
pycparser                    2.18
Pygments                     2.2.0
PyJWT                        1.6.4
PyNaCl                       1.2.1
pyOpenSSL                    18.0.0
pyparsing                    2.2.0
python-dateutil              2.7.3
PyYAML                       3.13
requests                     2.19.1
requests-oauthlib            1.0.0
SecretStorage                3.0.1
setuptools                   40.0.0
six                          1.11.0
tabulate                     0.8.2
urllib3                      1.23
wheel                        0.31.1
```

##### OS / ENVIRONMENT

```
hostnamectl
   Static hostname: xxxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: xxxxx
           Boot ID: xxxx
    Virtualization: microsoft
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-862.9.1.el7.x86_64
      Architecture: x86-64
```

##### STEPS TO REPRODUCE

```yaml

# Create a security group
- name: NSG - Create Security Group {{ security_group.name }}
  azure_rm_securitygroup:
     api_profile: 2017-03-09-profile
     client_id: "{{ az_platform_compute_client  }}"
     secret: "{{  az_platform_compute_secret  }}"
     subscription_id: "{{  az_subscription  }}"
     tenant: "{{  az_tenant  }}"
     resource_group: "{{ az_rg_for_vnet }}"
     name: "{{ security_group.name }}"
     purge_rules: yes
     location: "{{ location }}"
     rules: "{{ security_group['rules'] }}"
  no_log: false


1. remove two security group rules on azure.
2. Rerun our ansible playbook to create the missing two security group rules on azure
3. When we check azure the two security group rules are not created
```

##### EXPECTED RESULTS

The security group rules that are deleted on azure are recreated on azure when we rerun our ansible playbook.

##### ACTUAL RESULTS

The security group rules that are deleted on azure are not recreated on azure when we rerun our ansible playbook.

The rules deleted both had a priority 1795 and from the ansible output below they are displayed in the rules output.

```
....
            "rules": [
                {
                    "access": "Allow",
                    "description": "*",
                    "destination_address_prefix": "xxxx",
                    "destination_port_range": 22,
                    "direction": "Inbound",
                    "name": "xxx_in",
                    "priority": 101,
                    "protocol": "Tcp",
                    "source_address_prefix": "1xxx",
                    "source_port_range": "*"
                },
...
```
