### ISSUE TITLE
ovirt: cannot create VM from template when template name exists in several data centers

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#44162]
##### SUMMARY

If the same template name exists in several datacenters, it is only possible to use it in the first one in alphabetical order. Others fail as the playbook tries to use the wrong template ID.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```
2.6.2
```

##### STEPS TO REPRODUCE

```yaml
- name: Create VM from template
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: present
        name: test1
        template: centos7
        stateless: no
        cluster: dc2
```

##### ACTUAL RESULTS

```

```
