### ISSUE TITLE
win_nssm needs to support more parameters.

### ISSUE THREAD

**Issue by rpiskule** [ansible/ansible#44176]
##### SUMMARY

I installed a service on windows using win_nssm. The default installation of win_nssm is to keep restarting failed services, as well as truncate and rewrite any log files.

This becomes an issue if the service keeps failing. I was unable to determine why my service was failing because the logs kept getting truncated.

##### ISSUE TYPE
 - Feature Idea
win_nssm should support additional parameters for log rotation. This could be handled by providing additional parameters on the module.

##### COMPONENT NAME

win_nssm

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /retry

##### OS / ENVIRONMENT

Ansible Client: Ubuntu 18.04 
Ansible Target: Windows 2016 Base

##### STEPS TO REPRODUCE

```yaml
- win_nssm:
    name: foo
    application: C:\windows\foo.exe
    #don't replace log files on restart
    log_replace: false
    #rotate logs every 3600 seconds
    log_rotation: 3600
    app_parameters:
      bar: true
```

##### ACTUAL RESULTS

```

```
