### ISSUE TITLE
NTP configuration of ESXi servers in a cluster

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#44183]
##### SUMMARY
It appears that an empty list item is included in the list of ntp servers when using vmware_host_ntp.

Once vmware_host_ntp has configured a cluster of ESXi servers the **NTP Servers:** field contains the following:

, time1.test.local, time2.test.local

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_host_ntp

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /root/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```
##### CONFIGURATION
```
[defaults]
host_key_checking = False
#remote_user = root
ansible_managed = This file is managed by Ansible
retry_files_enabled = False
#ask_vault_pass = True

#gathering = smart
#fact_caching = jsonfile
#fact_caching_connection = /tmp/facts_cache
#fact_caching_timeout = 3600
```
##### OS / ENVIRONMENT
Source Ansible environment CentOS 7
Target vCenter 6.7
Target ESXi hosts 6.7

##### STEPS TO REPRODUCE

```
- name: 'Configure ESXi NTP settings'
  vmware_host_ntp:
    hostname: '{{ ansible_host }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster_name: '{{ cluster_name }}'
    state: 'present'
    validate_certs: '{{ validate_certs }}'
    ntp_servers:
      - 'time1.test.local'
      - 'time2.test.local'
```

##### EXPECTED RESULTS
The list of NTP servers in the NTP Servers field should be
```
time1.test.local, time2.test.local
```

##### ACTUAL RESULTS
The list of NTP servers in the NTP Servers contains a preceeding comma implying an emtpy list item
```
, time1.test.local, time2.test.local
```
