### ISSUE TITLE
[vmware_guest_file_operation] Failed to Copy file to VM VMware Exception...

### ISSUE THREAD

**Issue by shibumi** [ansible/ansible#44264]
##### ISSUE TYPE
*   Bug Report

##### COMPONENT NAME
**vmware_guest_file_operation**

##### ANSIBLE VERSION
ansible 2.5.3
  config file = /root/ansible-vxlan/ansible.cfg
  configured module search path = ['/root/ansible-vxlan/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]

##### CONFIGURATION
ANSIBLE_PIPELINING(/root/ansible-vxlan/ansible.cfg) = True
DEFAULT_HOST_LIST(/root/ansible-vxlan/ansible.cfg) = ['/root/ansible-vxlan/hosts']
DEFAULT_MODULE_PATH(/root/ansible-vxlan/ansible.cfg) = ['/root/ansible-vxlan/library']
DEFAULT_ROLES_PATH(/root/ansible-vxlan/ansible.cfg) = ['/root/ansible-vxlan/roles']
DEFAULT_SCP_IF_SSH(/root/ansible-vxlan/ansible.cfg) = True
RETRY_FILES_ENABLED(/root/ansible-vxlan/ansible.cfg) = False

##### OS / ENVIRONMENT
Host Running Ansible: Arch Linux
Target Host: VMWare ESXI Hosts with Ubuntu 18.04 Template
Target VM: CentOS 7 with open-vm-tools 10.1.10 Release: 3.el7_5.1

##### STEPS TO REPRODUCE
```
- name: copy generated files to vm
  vmware_guest_file_operation:
    hostname: "{{ vmware_general.hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    datacenter: "{{ vmware_general.datacenter }}"
    validate_certs: "{{ vmware_general.validate_certs }}"
    vm_id: "{{ inventory_hostname }}"
    vm_username: root
    vm_password: "{{ template_password }}"
    copy:
        src: "{{ inventory_dir }}/cache/{{ inventory_hostname }}.network"
        dest: "/etc/systemd/network/ens160.network"
        overwrite: False
  delegate_to: localhost
```

with right variables of course. This task works fine with Ubuntu 18.04 and official vmware tools.

##### EXPECTED RESULTS
**vmware_guest_file_operations** should copy the specified file to the host

##### ACTUAL RESULTS
**vmware_guest_file_operations** will fail with the following trace:
```

TASK [vmware : copy generated files to vm] ************************************************************************************************************************************************************************************************************************************************************************************
task path: /root/ansible-infrastructure/roles/vmware/tasks/network.yml:11
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/urls.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/vmware.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python3.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module file /usr/lib/python3.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_file_operation.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_mz75l0nv/ansible_module_vmware_guest_file_operation.py", line 345, in copy
    fileSize=file_size)
  File "/root/.local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/root/.local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/root/.local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [testvm1.XXX -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cluster": null,
            "copy": {
                "dest": "/etc/systemd/network/ens160.network",
                "overwrite": false,
                "src": "/root/ansible-infrastructure/cache/testvm1.XXX.network"
            },
            "datacenter": "XXX-Test",
            "directory": null,
            "fetch": null,
            "folder": null,
            "hostname": "vcsa-testing.XXX",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "username": "cre13",
            "validate_certs": false,
            "vm_id": "testvm1.XXX",
            "vm_id_type": "vm_name",
            "vm_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vm_username": "root"
        }
    },
    "msg": "Failed to Copy file to Vm VMware exception : (vmodl.fault.InvalidArgument) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'A specified parameter was not correct: ',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   invalidProperty = <unset>\n}",
    "uuid": "4230385d-4cd7-7386-0918-432f0f491f9f"
}

```
