### ISSUE TITLE
Setting a variable to default(omit) sets it to a string placeholder instead of undefined

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#44261]
##### SUMMARY
When I set a variable to `anothervariable | default(omit)` and `anothervariable` is undefined I expect the result to be undefined, but instead it's set to a string placeholder ("__omit_place_holder__SOMEGUID").

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Jinja2 expressions?

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /media/sf_work/lops/ansible.cfg
  configured module search path = [u'/home/em/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: false
  connection: local
  vars:
    stillmissing: "{{ missingvar | default(omit) }}"
  tasks:
  - debug:
      msg: "stillmissing = {{ stillmissing | default('still not defined') }}"
```

##### EXPECTED RESULTS

```
"msg": "stillmissing = still not defined"
```

##### ACTUAL RESULTS

```
"msg": "stillmissing = __omit_place_holder__5ebe2a97fd59a2b8a8f0f9772e8e675496a74faa"
```
