### ISSUE TITLE
pamd module does not support control rule "definitive"

### ISSUE THREAD

**Issue by Protista** [ansible/ansible#44278]
##### SUMMARY
Ansible pamd module does not support control rule "definitive".

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

pamd

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
  config file = /home/parnell/ansible/ansible.cfg
  configured module search path = [u'/home/parnell/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/parnell/.local/lib/python2.7/site-packages/ansible
  executable location = /home/parnell/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/parnell/ansible/ansible.cfg) = [u'/home/parnell/ansible/hosts']
DEFAULT_ROLES_PATH(/home/parnell/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles', u'/home/parnell/ansible/roles']
```

##### OS / ENVIRONMENT

Ansible control: WSL Ubuntu 18.04 LTS
Target node: Solaris 11.3
Target files: /etc/pam.d/login, /etc/pam.d/other
##### STEPS TO REPRODUCE

```yaml
- name: Add winbind to PAM login auth
  pamd:
    name: login
    type: auth
    control: requisite
    module_path: pam_authtok_get.so.1
    new_type: auth
    new_control: sufficient
    new_module_path: pam_winbind.so.1
    module_arguments: 'try_first_pass'
    state: after

- name: Add winbind to PAM other auth
  pamd:
    name: other
    type: auth
    control: requisite
    module_path: pam_authtok_get.so.1
    new_type: auth
    new_control: sufficient
    new_module_path: pam_winbind.so.1
    module_arguments: 'try_first_pass'
    state: after

- name: Add winbind to PAM other account
  pamd:
    name: other
    type: account
    control: requisite
    module_path:  pam_roles.so.1
    new_type: account
    new_control: sufficient
    new_module_path: pam_winbind.so.1
    module_arguments: 'try_first_pass'
    state: after

- name: Add winbind to PAM other session
  pamd:
    name: other
    type: session
    control: definitive
    module_path:  pam_user_policy.so.1
    new_type: session
    new_control: sufficient
    new_module_path: pam_winbind.so.1
    module_arguments: 'try_first_pass'
    state: after
```

##### EXPECTED RESULTS

New Lines to be added where indicated with --> in /etc/pam.d/login
auth definitive         pam_user_policy.so.1
auth requisite          pam_authtok_get.so.1
-- >auth sufficient         pam_winbind.so.1        try_first_pass
auth required           pam_dhkeys.so.1
auth required           pam_unix_auth.so.1
auth required           pam_unix_cred.so.1
auth required           pam_dial_auth.so.1

New Lines to be added where indicated with --> in /etc/pam.d/other

auth definitive         pam_user_policy.so.1
auth requisite          pam_authtok_get.so.1
-->auth sufficient         pam_winbind.so.1        try_first_pass
auth required           pam_dhkeys.so.1
auth required           pam_unix_auth.so.1
auth required           pam_unix_cred.so.1

account requisite       pam_roles.so.1
-->account sufficient      pam_winbind.so.1        try_first_pass
account definitive      pam_user_policy.so.1
account required        pam_unix_account.so.1
account required        pam_tsol_account.so.1

session definitive      pam_user_policy.so.1
-->session sufficient      pam_winbind.so.1        try_first_pass
session required        pam_unix_session.so.1

##### ACTUAL RESULTS

```
FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "backup": false, 
            "control": "requisite", 
            "module_arguments": [
                "try_first_pass"
            ], 
            "module_path": "pam_authtok_get.so.1", 
            "name": "login", 
            "new_control": "sufficient", 
            "new_module_path": "pam_winbind.so.1", 
            "new_type": "auth", 
            "path": "/etc/pam.d", 
            "state": "after", 
            "type": "auth"
        }
    }, 
    "msg": "Rule control, definitive, is not valid in rule auth       definitive pam_user_policy.so.1 "
}
```
