### ISSUE TITLE
[vmware_guest] Disks create as IDE device, Cannot Specify Otherwise

### ISSUE THREAD

**Issue by aguynamedjoetoo** [ansible/ansible#44288]
##### SUMMARY
Based off the documentation for the `vmware_guest` module, it doesn't look like we can specify the type of Virtual Device Node, and it is somehow choosing IDE by default. By choosing an IDE device, we cannot online resize drives.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/joe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/joe/Envs/ansible-2.6/lib/python3.6/site-packages/ansible
  executable location = /Users/joe/Envs/ansible-2.6/bin/ansible
  python version = 3.6.4 (default, Mar 22 2018, 13:54:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart

##### OS / ENVIRONMENT
MacOS in a python virtualenv.

##### STEPS TO REPRODUCE
Here's our present play:

```yaml
- name: Create the VM instance
  vmware_guest:
    cdrom:
      iso_path: "{{ iso_path }}"
      type: iso
    cluster: "{{ cluster }}"
    customization:
      hostname: "{{ vm_name }}"
    datacenter: "{{ datacenter }}"
    disk:
      - size_gb: "{{ storage_gb }}"
        type: thin
        datastore: "{{ datastore }}"
    folder: "{{ vm_folder }}"
    guest_id: "ubuntu64Guest"
    hardware:
      memory_mb: "{{ memory }}"
      num_cpus: "{{ num_cpus }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ vm_name }}"
    networks:
      - name: "PG-VM"
        device_type: "vmxnet3"
    password: "{{ ad_password }}"
    state: present
    username: {{ ad_username }}
    validate_certs: no
    wait_for_ip_address: yes
```

I tried adding under the hardware section `scsi: lsilogic` but that simply changes the default controller, which we'd like to remain paravirtualized. The disk that gets created still comes out of type IDE.

##### EXPECTED RESULTS
A VM that comes online with a drive that can be configured of type SCSI

e.g.:
<img width="708" alt="vm_good" src="https://user-images.githubusercontent.com/4296375/44240619-ed56cd80-a173-11e8-83b4-f217111e2b38.png">

##### ACTUAL RESULTS
A VM that comes online with a drive that is only IDE ):

e.g.:
<img width="708" alt="vm_bad" src="https://user-images.githubusercontent.com/4296375/44240632-ff387080-a173-11e8-987f-b89b7a0c4aa3.png">

Happy to provide any additional info if needed!

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @Joeskyyy,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@Joeskyyy Thanks for reporting this issue. Could you please check this PR https://github.com/ansible/ansible/pull/39285/ and let me know if it works for you ? Thanks.

**Comment by aguynamedjoetoo** [comment]
@Akasurde it does indeed (: any chance that is gonna make it into a patch release for 2.6? Or at least for 2.7?

**Comment by toxicvengeance** [comment]
Would be really great if this would make the next patch release. I have the same problem as @Joeskyyy At the moment I have to patch our ansible installation with PR #39285 after every update to be able deploy virtual machines with scsi drives. I stumbled over this when I tried to resize hard drives and got an error from vcenter as IDE drives can not be resized while the the vm is running.

**Comment by sarvarahmed** [comment]
Faced same issue, Workaround is we can create new VM with SCSI disk but we have to drop CDROM

**Comment by Akasurde** [comment]
@Joeskyyy @toxicvengeance @sarvarahmed #39285 is merged. Could you please check with latest patch and let me know ?

**Comment by toxicvengeance** [comment]
@Akasurde Have no problem with #39285. 

Tested the following points successfully:
* adding multiple SCSI disks
* adding a cdrom drive
* disks are now attached to SCSI controller when a SCSI controller is specified if not they appear as IDE disks as it should be

I used this playbook to test

```yaml
---
- hosts: localhost
  vars:
   vsphere_user: redacted
   vsphere_password: redacted
   vcenter: redacted
   vm_cluster: redacted
   vm_datacenter: redacted

  tasks:
   - name: creating virtual machine
     vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ vsphere_user }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      cluster: "{{ vm_cluster }}"
      name: "test"
      state: poweredon
      folder: redacted
      datacenter: redacted
      hardware:
        hotadd_cpu: true
        hotremove_cpu: true
        hotadd_memory: true
        memory_mb: "1024"
        num_cpus: "1"
        scsi: "paravirtual"
      disk:
      - size_gb: "10"
        type: "thin"
        datastore: redacted
      - size_gb: "10"
        type: "thin"
        datastore: redacted
      - size_gb: "10"
        type: "thin"
        datastore: redacted
      networks:
      - name: redacted
        device_type: "vmxnet3"
      cdrom:
        type: "iso"
        iso_path: "[redacted]/ISO/Ubuntu1804kickstart.iso"
      guest_id: "ubuntu64Guest"
```
