### ISSUE TITLE
Archive module fails for large file size

### ISSUE THREAD

**Issue by navedrizv** [ansible/ansible#44296]
##### SUMMARY

Archive module breaks for large file sizes

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

archive

##### ANSIBLE VERSION

```
ansible 2.5.5
```

##### CONFIGURATION

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

centos7

##### STEPS TO REPRODUCE

When archiving a folder on target server, if the folder size is large (> 6 GB), the archive module throws error, Failed to connect to the host via ssh : Shared connection to XXXXXXX closed 

```yaml
- name: Create backup
      archive:
        path: "{{ project_root }}"
        dest: "{{ project_backup }}/deployment_backup_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.tar"
      register: backupgen
```

##### EXPECTED RESULTS

Create a backup folder 

##### ACTUAL RESULTS

TASK [Create backup] ******************************************************
fatal: [XX.XXX.XXX.XX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to XX.XXX.XXX.XX closed.\r\n", "unreachable": true}
	to retry, use: --limit @XYZ

```
TASK [Create backup] ******************************************************
fatal: [XX.XXX.XXX.XX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to XX.XXX.XXX.XX closed.\r\n", "unreachable": true}
	to retry, use: --limit @XYZ

```
