### ISSUE TITLE
[proxmox_kvm] 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'node'

### ISSUE THREAD

**Issue by shibumi** [ansible/ansible#44307]
##### SUMMARY
The `proxmox_kvm` module fails with the following error message:
```
TASK [proxmox_vm : Clone VMs from template on Proxmox] ************************************************************************************************************************************************************************************************************************************************************************
task path: /root/ansible-infrastructure/roles/proxmox_vm/tasks/main.yml:3
fatal: [graytest]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'node'\n\nThe error appears to have been in '/root/ansible-infrastructure/roles/proxmox_vm/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Clone VMs from template on Proxmox\n  ^ here\n"
}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

**proxmox_kvm**

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /root/ansible-infrastructure/ansible.cfg
  configured module search path = ['/root/ansible-infrastructure/library']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/root/ansible-infrastructure/ansible.cfg) = True
DEFAULT_HOST_LIST(/root/ansible-infrastructure/ansible.cfg) = ['/root/ansible-infrastructure/hosts']
DEFAULT_MODULE_PATH(/root/ansible-infrastructure/ansible.cfg) = ['/root/ansible-infrastructure/library']
DEFAULT_ROLES_PATH(/root/ansible-infrastructure/ansible.cfg) = ['/root/ansible-infrastructure/roles']
DEFAULT_SCP_IF_SSH(/root/ansible-infrastructure/ansible.cfg) = True
RETRY_FILES_ENABLED(/root/ansible-infrastructure/ansible.cfg) = False

```
##### OS / ENVIRONMENT

Host Running Ansible: Arch Linux
Target Host: Proxmox 5.2

##### STEPS TO REPRODUCE

```yaml
---

- name: Clone VMs from template on Proxmox
  proxmox_kvm:
    api_user: root@pam
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_general.api_host }}"
    validate_certs: "{{ proxmox_general.validate_certs }}"
    name: "{{ inventory_hostname }}"
    node: "{{ item.node }}"
    clone: "{{ item.template }}"
    storage: "{{ item.storage }}"
    cores: "{{ item.cores }}"
    sockets: "{{ item.sockets }}"
    memory: "{{ item.memory }}"
    state: "{{ item.state }}"
    update: yes
  with_items: "{{ proxmox_infrastructure }}"
  delegate_to: localhost
```

with defaults file:
```
---

proxmox_general:
  api_host: "cloud-1.XXX"
  validate_certs: no

proxmox_infrastructure: {}
```

and host_vars:
```
---

proxmox_infrastructure:
  node: "cloud-5"
  clone: ubuntu18.04
  storage: "local-lvm"
  cores: 2
  sockets: 2
  memory: 1024
  state: started
```

##### EXPECTED RESULTS
The task should work as expected and clone a VM

##### ACTUAL RESULTS

The VM will not get created and ansible throws the following error message:
```yaml
TASK [proxmox_vm : Clone VMs from template on Proxmox] ************************************************************************************************************************************************************************************************************************************************************************
task path: /root/ansible-infrastructure/roles/proxmox_vm/tasks/main.yml:3
fatal: [graytest]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'node'\n\nThe error appears to have been in '/root/ansible-infrastructure/roles/proxmox_vm/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Clone VMs from template on Proxmox\n  ^ here\n"
}
```
