### ISSUE TITLE
VMware: vmware_portgroup incorrectly handles "false" values in security policy

### ISSUE THREAD

**Issue by Straevaras** [ansible/ansible#44326]
##### SUMMARY

If you pass `false` to the network security policy in vmware_portgroup, that element of of the policy is actually not defined.  This compounds on an [already existing bug in vmpyomi](https://github.com/vmware/pyvmomi/issues/712) where null/undefined values are not handled properly and depending on which value is null, none of the security policy is set or the parts that are null are in an undefined/indeterminable state.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_portgroup

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### CONFIGURATION

Nothing changed

##### OS / ENVIRONMENT

CentOS 7 (3.10.0-693.17.1.el7x86_64)

##### STEPS TO REPRODUCE

```yaml
- name: Add/Update Port Groups
  vmware_portgroup:
    hostname: "{{vcenter_hostname}}"
    hosts: "{{esx_hostname}}"
    username: "{{vcenter_username}}"
    password: "{{vcenter_password}}"
    validate_certs: no
    switch_name: TESTSWITCH
    portgroup_name: "{{item.name}}"
    vlan_id: "{{item.vlan_id}}"
    state: present
    network_policy:
      promiscuous_mode: "{{item.promiscuous_mode}}"
      forged_transmits: "{{item.forged_transmits}}"
      mac_changes: "{{item.mac_changes}}"
  delegate_to: localhost
  with_items:
    - {name: TEST1, vlan_id: 4095, promiscuous_mode: false, forged_transmits: true, mac_changes: true}
    - {name: TEST2, vlan_id: 4095, promiscuous_mode: true, forged_transmits: false, mac_changes: false}
    - {name: TEST3, vlan_id: 4095, promiscuous_mode: true, forged_transmits: false, mac_changes: true}
```

##### EXPECTED RESULTS

**TEST1**
- Promiscuous Mode: "Reject" on edit menu and "No" on info page
- Allow Forged Transmits: "Accept" on edit menu and "Yes" on info page
- Allow MAC changes: "Accept" on edit menu and "Yes" on info page

**TEST2**
- Promiscuous Mode: "Accept" on edit menu and "Yes" on info page
- Allow Forged Transmits: "Reject" on edit menu and "No" on info page
- Allow MAC changes: "Reject" on edit menu and "No" on info page

**TEST3**
- Promiscuous Mode: "Accept" on edit menu and "Yes" on info page
- Allow Forged Transmits: "Reject" on edit menu and "No" on info page
- Allow MAC changes: "Accept" on edit menu and "Yes" on info page

##### ACTUAL RESULTS

**TEST1**
- Promiscuous Mode: "Inherit from vSwitch" on edit menu and "No" on info page
- Allow Forged Transmits: "Inherit from vSwitch" on edit menu and "Yes" on info page
- Allow MAC changes: "Inherit from vSwitch" on edit menu and "Yes" on info page

**TEST2**
- Promiscuous Mode: "Accept" on edit menu and "Yes" on info page
- Allow Forged Transmits: <no option> on edit menu and "Yes" on info page
- Allow MAC changes: <no option> on edit menu and "Yes" on info page

**TEST3**
- Promiscuous Mode: "Accept" on edit menu and "Yes" on info page
- Allow Forged Transmits: <no option> on edit menu and "Yes" on info page
- Allow MAC changes: "Accept" on edit menu and "Yes" on info page

##### ADDITIONAL NOTES

While some of the problem here does reside in PyVmomi, that is only in regard to null or undefined values.  Both `true` and `false` values should be getting assigned to the network security policy, when only `true` values are.

I believe the problem is on Lines 363-368: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_portgroup.py#L363.  In seems the intention is the values are being checked for if they exist, but if the values are `false` (which is still a valid value), then the `if` statement still doesn't fire.  My recommendation to this code is as follows.

```
        if self.promiscuous_mode != None: 
            security_policy.allowPromiscuous = self.promiscuous_mode
        if self.forged_transmits != None:
            security_policy.forgedTransmits = self.forged_transmits
        if self.mac_changes != None:
            security_policy.macChanges = self.mac_changes
```

If I perform this change, I get all my expected results.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_portgroup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_portgroup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @Straevaras,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by adamdonahue** [comment]
:+1: here.  We encountered this issue as well, and applied a patch to set the true or false value specifically.  I believe otherwise it picks up the vSwitch response.

**Comment by ckotte** [comment]
@Straevaras @adamdonahue Can you check https://github.com/ansible/ansible/pull/47052? Overrides should be handled properly now.

needs_info
resolved_by_pr #47052

@Straevaras There's no bug in PyVmoni. You have to set the value to `None` if you want to use the switch values. Override is configured if you set the value to anything else.

**Comment by Akasurde** [comment]
@Straevaras Could you please provide your feedback, it will be helpful for us to merge this PR ? Thanks.

**Comment by ansibot** [comment]
@Straevaras This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Straevaras** [comment]
Apologies for the delay, currently going over the PR and its changes, will get back to you within a day or so.

**Comment by Straevaras** [comment]
I added a review on the PR, new steps to reproduce based on the changes made in the PR.

```
- name: Add/Update Port Groups
  vmware_portgroup:
    hostname: "{{vcenter_hostname}}"
    hosts: "{{esx_hostname}}"
    username: "{{vcenter_username}}"
    password: "{{vcenter_password}}"
    validate_certs: no
    switch_name: TESTSWITCH
    portgroup_name: "{{item.name}}"
    vlan_id: "{{item.vlan_id}}"
    state: present
    security:
      promiscuous_mode: "{{item.promiscuous_mode}}"
      forged_transmits: "{{item.forged_transmits}}"
      mac_changes: "{{item.mac_changes}}"
  delegate_to: localhost
  with_items:
    - {name: TEST1, vlan_id: 4095, promiscuous_mode: false, forged_transmits: true, mac_changes: true}
    - {name: TEST2, vlan_id: 4095, promiscuous_mode: true, forged_transmits: false, mac_changes: false}
    - {name: TEST3, vlan_id: 4095, promiscuous_mode: true, forged_transmits: false, mac_changes: true}
```

I have to comment out lines 295-296 to make the portgroup module in the PR work for my test cases.  They're assuming a teaming config is included.

```
        # NOTE: the following options are deprecated and should be removed in 2.11
        self.teaming_inbound_policy = self.module.params['teaming']['inbound_policy']
        self.teaming_rolling_order = self.module.params['teaming']['rolling_order']
```
