### ISSUE TITLE
`flatten` filter does not flatten lists when chained to other filters

### ISSUE THREAD

**Issue by techraf** [ansible/ansible#44327]
##### SUMMARY

`flatten` filter does not flatten lists when chained to filters producing lists of tuples.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`flatten` filter

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/macraf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/macraf/anaconda2/lib/python2.7/site-packages/ansible
  executable location = /Users/macraf/anaconda2/bin/ansible
  python version = 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```
(also previous versions)

##### CONFIGURATION

```
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    my_list1: [[1,2],[3,4]]
    my_list2: "{{ [1,3] | zip([2,4]) | list }}"
    # or:
    #   my_list2: "{{ {1: 2, 3: 4} | dictsort | list }}"

  tasks:
    - set_fact:
        my_list3: "{{ my_list2 }}"
    - name: "[[1,2],[3,4]] | flatten"
      debug:
        msg: "{{ my_list1 | flatten }}"
    - name: "[1,3] | zip([2,4]) | list | flatten"
      debug:
        msg: "{{ my_list2 | flatten }}"
    - name: "[1,3] | zip([2,4]) | list <--- set_fact ---> | flatten"
      debug:
        msg: "{{ my_list3 | flatten }}"
```

##### EXPECTED RESULTS

All debug tasks returning the same flattened list.

##### ACTUAL RESULTS

```
TASK [set_fact] ********************************************************************************************************************************************************
ok: [localhost]

TASK [[[1,2],[3,4]] | flatten] *****************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        1,
        2,
        3,
        4
    ]
}

TASK [[1,3] | zip([2,4]) | list | flatten] *****************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            1,
            2
        ],
        [
            3,
            4
        ]
    ]
}

TASK [[1,3] | zip([2,4]) | list <--- set_fact ---> | flatten] **********************************************************************************************************
ok: [localhost] => {
    "msg": [
        1,
        2,
        3,
        4
    ]
}
```
