### ISSUE TITLE
The status codes coming back from the uri module should be integers

### ISSUE THREAD

**Issue by gregkare** [ansible/ansible#4433]
I'm using the latest git revision and I'm experimenting with the `until` feature. I realized the problem with this code was that `result.status` returns a string, so the comparison always failed.

``` yml
- name: wait for jenkins api to be up
  uri: url=http://localhost:{{ jenkins.port }}/cli
  register: result
  until: result.status == 200
  retries: 5
  delay: 30
```

Here's the error:

```
"status": "200", ... }
msg: Task failed as maximum retries was encountered
```

At this point I realized status was a string and things worked as expected after this change:

``` yml
- name: wait for jenkins api to be up
  uri: url=http://localhost:{{ jenkins.port }}/cli
  register: result
  until: result.status == "200"
  retries: 5
  delay: 30
```

The documentation for `until` could contain a warning about uri's `status` being a string, or integers could be automatically turned into strings, or the status and status_code could be changed to be integers.

What do you think?
