### ISSUE TITLE
Update "ec2_vpc_nat_gateway" module to support AWS tags

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#44339]
##### SUMMARY
Update the "ec2_vpc_nat_gateway" module to support AWS tags like the other AWS modules including, to name a few, the "ec2_vpc_net" module, "ec2_vpc_igw" module, and "ec2_vpc_subnet" module.  We have an internal requirement within our company to tag everything and I am not seeing that option for Ansible created NAT Gateways, even though the functionality is provided on every other AWS module I have used so far.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_vpc_nat_gateway

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE
Attempt to run the following task using the "ec2_vpc_nat_gateway" module with included "tags" key/value pairs.

```yaml
- name: Create NAT Gateway, allocate new EIP, in VPC
  ec2_vpc_nat_gateway:
    state: present
    # NAT Gateways being deployed in DMZ subnets
    subnet_id: "{{ subnet_dmz_id[item.subnet_name] }}"
    region: "{{ vpc_region }}"
    wait: yes
    if_exist_do_not_create: true
    tags:
      Name: "{{ item.name }}"
      Role: "{{ role_tag }}"
      Team: "{{ team_tag }}"
      Product Area: "{{ product_area_tag }}"
      Portfolio: "{{ portfolio_tag }}"
      Created By: "{{ created_by }}"
  with_items: "{{ nat_gateway }}"
  register: new_nat_gateway
```

##### EXPECTED RESULTS
AWS NAT Gateways are created and their tags are updated with the provided "tags" key/value pairs included under the "ec2_vpc_nat_gateway" module.

##### ACTUAL RESULTS
The "ec2_vpc_nat_gateway" module does not support the "tags" parameters as shown below.
```
{
    "_ansible_parsed": true,
    "changed": false,
    "_ansible_no_log": false,
    "_ansible_item_result": true,
    "item": {
        "subnet_name": "DMZ_Subnet_A",
        "name": "NAT_Gateway_A"
    },
    "_ansible_item_label": {
        "subnet_name": "DMZ_Subnet_A",
        "name": "NAT_Gateway_A"
    },
    "invocation": {
        "module_args": {
            "tags": {
                "Name": "NAT_Gateway_A",
                "Role": "splunk-proof-of-concept",
                "Created By": "ansible",
                "Team": "Engineering Tools",
                "Product Area": "Engineering Tools",
                "Portfolio": "Shared Platform and Operations"
            },
            "subnet_id": "subnet-XXXX",
            "region": "us-east-1",
            "if_exist_do_not_create": true,
            "state": "present",
            "wait": true
        }
    },
    "_ansible_ignore_errors": null,
    "msg": "Unsupported parameters for (ec2_vpc_nat_gateway) module: tags Supported parameters include: allocation_id, aws_access_key, aws_secret_key, client_token, ec2_url, eip_address, if_exist_do_not_create, nat_gateway_id, profile, region, release_eip, security_token, state, subnet_id, validate_certs, wait, wait_timeout"
}
```
