### ISSUE TITLE
cloudformation_facts ignores profile when boto is installed

### ISSUE THREAD

**Issue by jonatcorus** [ansible/ansible#44334]
##### SUMMARY
Using cloudformation_facts with the profile attribute set to something other than default fails when boto(not boto3) is installed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudformation_facts

##### ANSIBLE VERSION
```
2.6.2
```

##### CONFIGURATION
ANSIBLE_NOCOWS($HOME/labs/ansible/aws/cloudformation/orchestration/ansible.cfg) = True

##### OS / ENVIRONMENT
ubuntu 16.04
python 2.7.12
boto            2.49.0 
boto3           1.7.75 
botocore        1.10.75

##### STEPS TO REPRODUCE
Locally, create an aws profile called account1 pointing to a different account than in the default profile.

Install boto/boto3:
```shell
pip install boto boto3
```

Execute playbook:
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: facts
      cloudformation_facts:
        profile: account1
        region: us-east-1
      register: facts
    - debug: msg="{{ facts }}"
```

##### EXPECTED RESULTS
Should show facts from account defined by profile account1.

##### ACTUAL RESULTS
Shows facts from account defined by default profile.

Uninstalling boto, produces the proper behavior.
