### ISSUE TITLE
NPM install neither install modules, neither throw an error.

### ISSUE THREAD

**Issue by ArseniiPetrovich** [ansible/ansible#44346]
##### SUMMARY
When I'm trying to install dependencies for this => https://github.com/poanetwork/poa-scripts-validator/tree/master/transferRewardToPayoutKey script it doesn't install them and, as well, don't throw any error. Referenced to this => https://github.com/poanetwork/deployment-playbooks/issues/162 issue.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
NPM

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /home/ubuntu/deployment-terraform/azure/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
`HOST_KEY_CHECKING(/home/ubuntu/deployment-terraform/azure/ansible.cfg) = False`

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Download the repo `https://github.com/poanetwork/poa-scripts-validator`. Due to technical requirements we need to use `become: true` in the whole module and `become_user={{ username }}` in this particular step. You can view full module here => https://github.com/poanetwork/deployment-playbooks/blob/master/roles/validator/tasks/main.yml . The affected `npm install` play is this one:
```
- name: install npm transferRewardToPayoutKey
  npm:
    path: "{{ home }}/poa-scripts-validator/transferRewardToPayoutKey"
  become: true
  become_user: "{{ username }}"
  notify:
    - restart poa-netstats
```
If we replace this play with the next one everything works just as expected:
```
- name: install npm transferRewardToPayoutKey
  shell: npm install
  args:
    chdir: "{{ home }}/poa-scripts-validator/transferRewardToPayoutKey"
    creates: "{{ home }}/poa-scripts-validator/transferRewardToPayoutKey/node_modules"
  become: true
  become_user: "{{ username }}"
```

##### EXPECTED RESULTS
`node_modules` folder is being created, as well as `package-lock.json`

##### ACTUAL RESULTS
```
TASK [/root/deployment-terraform/azure/deployment-playbooks/roles/validator : install npm transferRewardToPayoutKey] ***
ok: [104.209.184.45]
```
