### ISSUE TITLE
unarchive does not take dummy tarballs

### ISSUE THREAD

**Issue by hangxie** [ansible/ansible#44340]
##### SUMMARY
`unarchive` module failed on dummy tarball, i.e. there is no file in the tarball.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
unarchive

##### ANSIBLE VERSION
```
2.4.2.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create dummy tarball
      command: tar cf /tmp/dummy.tar -T /dev/null
    - name: Verify the dummy tarball is valid
      command: tar tf /tmp/dummy.tar
    - name: Try the dummy tarball with unarchive module
      unarchive:
        src: /tmp/dummy.tar
        dest: /tmp/
```

##### EXPECTED RESULTS
`unarchive` module extract the dummy tarball without error, though no file will be created under target directory. Or `unarchive` module mentions that "archive without any file is not currently supported"

##### ACTUAL RESULTS
On Debian (without gtar):
```
fatal: [******]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/******/.ansible/tmp/ansible-tmp-1534547003.16-226621121379745/source\". Make sure the required command to extract the file is installed. Command \"/bin/tar\" could not handle archive. Command \"unzip\" not found. Command \"/bin/tar\" found no files in archive."}
```
On CentOS (gtar symlink to tar):
```
fatal: [******]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/******/.ansible/tmp/ansible-tmp-1534547241.59-182978487733144/source\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" found no files in archive. Command \"unzip\" not found. Command \"/bin/gtar\" could not handle archive."}
```
