### ISSUE TITLE
tower_* modules can not access variables set with loop_var

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#44344]
##### SUMMARY
To configure Ansible Tower, Ansible runs `include` multiple times. From the second include onward fails to find a variable passed with `loop_control` and `loop_var`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_team
tower_credential
tower_project
tower_inventory
tower_job_template

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
No output from `ansible-config dump --only-changed`.

##### OS / ENVIRONMENT
Control-node: Fedora-28
Managed-node: CentOS-7

##### STEPS TO REPRODUCE
My usecase is [this Ansible role](https://github.com/robertdebock/ansible-role-awx/tree/517c8311641617ec9000b6f2de9098bc63115820)

The minimum steps: (Sorry, I know is quite long.)
```yaml
---
# playbook.yml
---
- name: configure AWX
  hosts: centos7

  vars:
    awx_organizations:
      - name: demo
        description: Demo organization
        users:
          - name: demo
            password: demo
            email: demo@example.com
            first_name: De
            last_name: Mo
            superuser: true
        teams:
          - name: demo
            description: Demo team
            members:
              - name: demo
        credentials:
          - name: demo_ssh
            description: demo ssh credentials
            kind: ssh
            username: demo
            password: demo
          - name: demo_scm
            description: demo scm credentials
            kind: scm
            username: Null
            password: Null
        projects:
          - name: demo
            description: demo project
            scm_credential: demo_scm
            scm_type: git
            scl_url: "https://github.com/ansible/awx-example"
        inventories:
          - name: demo
            description: demo inventory
        job_templates:
          - name: demo
            description: demo_job_template
            project: demo
            playbook: demo.yml
            inventory: demo
            machine_credential: demo_ssh

  tasks:
    - name: configure organizations
      include: organization.yml
      with_items: "{{ awx_organizations }}"
      loop_control:
        loop_var: organization
```

This works:
```yaml
---
# organization.yml
- name: create organization
  tower_organization:
    name: "{{ organization.name }}"
    description: "{{ organization.description }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no

- name: create users in organization
  include_tasks: user.yml
  loop: "{{ organization.users }}"
  loop_control:
    loop_var: user

- name: create teams in organization
  include_tasks: team.yml
  loop: "{{ organization.teams }}"
  loop_control:
    loop_var: team

- name: create credentials in organization
  include_tasks: credential.yml
  loop: "{{ organization.credentials }}"
  loop_control:
    loop_var: credential

- name: create projects in organization
  include_tasks: project.yml
  loop: "{{ organization.projects }}"
  loop_control:
    loop_var: project

- name: create inventory in organization
  include_tasks: inventory.yml
  loop: "{{ organization.inventories }}"
  loop_control:
    loop_var: inventory

- name: create job_templates in organization
  include_tasks: job_template.yml
  loop: "{{ organization.job_templates }}"
  loop_control:
    loop_var: job_template
```

This one works too:
```yaml
---
# user.yml
- name: create user
  tower_user:
    username: "{{ user.name }}"
    password: "{{ user.password }}"
    email: "{{ user.email }}"
    first_name: "{{ user.first_name }}"
    last_name: "{{ user.last_name  }}"
    superuser: "{{ user.superuser | default(omit) }}"
    auditor: "{{ user.auditor| default(omit) }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no
```

This one fails:
```yaml
---
# team.yml
- name: create team
  tower_team:
    name: "{{ team.name }}"
    description: "{{ team.description }}"
    organization: "{{ awx_organizations.name }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no
```

This one fails:
```yaml
---
# credential.yml
- name: create credential
  tower_credential:
    name: "{{ credential.name }}"
    description: "{{ credential.description }}"
    organization: "{{ awx_organizations.name }}"
    kind: "{{ credential.kind }}"
    username: "{{ credential.username }}"
    password: "{{ credential.password }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no
```

This one fails:
```yaml
---
# project.yml
- name: create project
  tower_project:
    name: "{{ project.name }}"
    description: "{{ project.description }}"
    organization: "{{ awx_organizations.name }}"
    scm_credential: "{{ project.scm_credential }}"
    scm_type: "{{ project.scm_type }}"
    scm_url: "{{ project.scm_url }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no
```

This one fails:
```yaml
---
# inventory.yml
- name: create inventory
  tower_inventory:
    name: "{{ inventory.name }}"
    description: "{{ inventory.description }}"
    organization: "{{ awx_organizations.name }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no
```

And finally this one fails:
```yaml
---
# job_template.yml
- name: create job_templates
  tower_job_template:
    name: "{{ job_template.name }}"
    description: "{{ job_template.description }}"
    organization: "{{ awx_organizations.name }}"
    project: "{{ job_template.project }}"
    playbook: "{{ job_template.playbook }}"
    inventory: "{{ job_template.inventory }}"
    machine_credential: "{{ job_template.machine_credential }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: no
```

##### EXPECTED RESULTS
I was expecting to pass parts of the `awx_configuration` to the included tasks.

##### ACTUAL RESULTS
I've added `ignore_errors` and `debug` steps to understand the issue a bit better.
```
TASK [robertdebock.awx : configure organizations] *****************************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/organization.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo

TASK [robertdebock.awx : create organization] *********************************************************************************************************************************************************************
ok: [centos7]

TASK [robertdebock.awx : create users in organization] ************************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/user.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo

TASK [robertdebock.awx : create user] *****************************************************************************************************************************************************************************
changed: [centos7]

TASK [robertdebock.awx : create teams in organization] ************************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/team.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo

TASK [robertdebock.awx : create team] *****************************************************************************************************************************************************************************
fatal: [centos7]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'name'
  
    The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/team.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: create team
      ^ here
...ignoring

TASK [robertdebock.awx : create credentials in organization] ******************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/credential.yml for centos7
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/credential.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo_ssh

TASK [robertdebock.awx : create credential] ***********************************************************************************************************************************************************************
fatal: [centos7]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'name'
  
    The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/credential.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: create credential
      ^ here
...ignoring

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo_scm

TASK [robertdebock.awx : create credential] ***********************************************************************************************************************************************************************
fatal: [centos7]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'name'
  
    The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/credential.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: create credential
      ^ here
...ignoring

TASK [robertdebock.awx : create projects in organization] *********************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/project.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo

TASK [robertdebock.awx : create project] **************************************************************************************************************************************************************************
fatal: [centos7]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'scm_url'
  
    The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/project.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: create project
      ^ here
...ignoring

TASK [robertdebock.awx : create inventory in organization] ********************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/inventory.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo

TASK [robertdebock.awx : create inventory] ************************************************************************************************************************************************************************
fatal: [centos7]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'name'
  
    The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/inventory.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: create inventory
      ^ here
...ignoring

TASK [robertdebock.awx : create job_templates in organization] ****************************************************************************************************************************************************
included: /home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/job_template.yml for centos7

TASK [robertdebock.awx : show details] ****************************************************************************************************************************************************************************
ok: [centos7] => 
  msg: demo

TASK [robertdebock.awx : create job_templates] ********************************************************************************************************************************************************************
fatal: [centos7]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'name'
  
    The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/job_template.yml': line 6, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: create job_templates
      ^ here
...ignoring

PLAY RECAP ********************************************************************************************************************************************************************************************************
centos7                    : ok=50   changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py)
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_inventory.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_inventory.py)
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_job_template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_job_template.py)
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_project.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_project.py)
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_team.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_team.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AlanCoding @ghjm @jlaska @matburt @rooftopcellist @ryanpetrello @simfarm @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I'll call out a few things here:

```
The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'name'

The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/team.yml': line 6, column 3, but may
```

If we look at `team.yml`, we see that you are referring to:

```
organization: "{{ awx_organizations.name }}"
```

`aws_organizations` is a list.  You likely wanted `organization.name`.

Next:

``` 
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'scm_url'
  
The error appears to have been in '/home/robertdb/Documents/ansible/roles/ansible-role-awx/tasks/project.yml': line 6, column 3, but may
```

If we look at `project.yml`, we see that you are referring to:

```
"{{ project.scm_url }}"
```

However, what you have defined is `scl_url`:

```
        projects:
          - name: demo
            description: demo project
            scm_credential: demo_scm
            scm_type: git
            scl_url: "https://github.com/ansible/awx-example"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
