### ISSUE TITLE
mysql_db import fails if there is no "connection: local"  (RDS)

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#4435]
Hi,

I'm having this issue when running the bellow playbook to import a database in an Amazon RDS instance, if the playbook has the connection: local as you can see bellow then there are no problems, the schema is successfully imported to the RDS, if I don't have the "connection: local" like it gives me an error.
# Error message :

```
TASK: [import DB] *******************************************************
<localhost> ESTABLISH CONNECTION FOR USER: use on PORT 22 TO localhost
<localhost> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1381426711.31-102029754557703 && chmod a+rx $HOME/.ansible/tmp/ansible-1381426711.31-102029754557703 && echo $HOME/.ansible/tmp/ansible-1381426711.31-102029754557703'
<localhost> REMOTE_MODULE mysql_db login_host=x.y.z login_user=user login_password=password name=dbtest state=import target=testdb.sql
<localhost> PUT /tmp/tmp9qZs_2 TO /home/ops/.ansible/tmp/ansible-1381426711.31-102029754557703/mysql_db
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ops/.ansible/tmp/ansible-1381426711.31-102029754557703/mysql_db; rm -rf /home/ops/.ansible/tmp/ansible-1381426711.31-102029754557703/ >/dev/null 2>&1'
failed: [localhost] => {"failed": true}
msg: import failed!

FATAL: all hosts have already failed -- aborting
```
# Playbook  :

```
- hosts: localhost  
  connection: local # <-- problem if this line is not present !
  gather_facts: false 

  tasks:

  - name: make sure DB schemas is present
    mysql_db: login_host=x.y.z login_user=user login_password=password name=dbtest state=present

  - name: import DB
    mysql_db: login_host=x.y.z login_user=user login_password=password name=dbtest state=import target=testdb.sql
```
# System version :

```
ansible 1.4 (19386c43a7cedf611672887c7d469d0c5521a039)

CentOS 5
Linux 2.6.34.7-56.40.amzn1.x86_64 #1 SMP Fri Oct 22 18:48:49 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

boto version: 2.13.3
```
