### ISSUE TITLE
one_vm wait for ready=yes possible?

### ISSUE THREAD

**Issue by ulide4** [ansible/ansible#44378]
##### SUMMARY

It would be useful to have an option to wait before the instantiated vm reports ready=yes

At this moment I can be sure that Ansible can take over configuration.
wait_for_connection is not enough in my opinion because ssh is available before init scripts have finished. 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

one_vm

##### ANSIBLE VERSION

```
2.6
```

##### OS / ENVIRONMENT

Centos 7

##### STEPS TO REPRODUCE

```yaml

```

Add an option like wait_force_ready_yes

##### EXPECTED RESULTS

The task is finished as soon as the VM reports ready=yes

##### ACTUAL RESULTS

```
not yet implemented
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/opennebula/one_vm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/opennebula/one_vm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ilicmilan @kustodian
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ilicmilan** [comment]
Hi @ulide4 .
Try with this:
```
# Deploy an new instance with a network
- one_vm:
    template_id: 53
    networks:
      - NETWORK_ID: 27
  register: vm

# Wait for SSH to come up
- wait_for_connection:
  delegate_to: '{{ vm.instances[0].networks[0].ip }}'

# Create /www directory
- file:
    path: /www
    state: directory
  delegate_to: '{{ vm.instances[0].networks[0].ip }}'
```
