### ISSUE TITLE
ovirt_disk Can't Update Disk Name Independently 

### ISSUE THREAD

**Issue by nasx** [ansible/ansible#44371]
##### SUMMARY

When updating only the name of a disk with the ovirt_disk module, the play succeeds (ok, not changed) but the disk name does not get updated.
 
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ovirt_disk
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /home/chris/git/boxes/ansible.cfg
  configured module search path = [u'/home/chris/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION

DEFAULT_FORKS(/home/chris/git/boxes/ansible.cfg) = 20
HOST_KEY_CHECKING(/home/chris/git/boxes/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/chris/git/boxes/ansible.cfg) = False

##### OS / ENVIRONMENT

Running locally on Fedora 28 managing RHV 4.2.5.2-0.1.el7ev 

##### STEPS TO REPRODUCE

```yaml
- name: Change Disk Name
  ovirt_disk:
  auth:
    username: "{{ rhv_username }}"
    password: "{{ rhv_password }}"
    url: "https://{{ rhv_hostname }}/ovirt-engine/api"
    insecure: true
  id: "{{ disk_id }}"
  storage_domain: "{{ rhv_storage_domain }}"
  name: "new disk name here"
  vm_name: "{{ vm_name }}"
```

##### EXPECTED RESULTS

Expect the module to show changed with updated disk name.

##### ACTUAL RESULTS

Module shows ok (not changed). Dumping the results shows:

```
ok: [localhost] => {
    "change": {
        "changed": false, 
        "diff": {
            "after": {}, 
            "before": {}
        }, 
        ...
        "failed": false, 
        ...
    }
}
```
