### ISSUE TITLE
ansible.module_utils.connection.ConnectionError: timeout trying to send command:

### ISSUE THREAD

**Issue by Wo0dsi3** [ansible/ansible#44389]
##### SUMMARY
New to using Ansible. Hope I am logging this issue to the right place.  If not , apologies.
Running a playbook so as to update configutations on network devices.
Playbook references a jinga file so as to load modules which are blocks of IOS code
This playbook fails intermittely at different points with the error included above. 
The playbook runs succesfully the very odd time.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_config

- name: Security Configurations
  hosts: MPLS
  gather_facts: no
  connection: local
  tasks:
    - name: Push to MPLS
      ios_config:
        src: "./templates/MPLS-main.conf"
        save_when: modified

##### ANSIBLE VERSION

```
btadmin@STLPBTDC0693:/etc/ansible$ ansible --version
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/btadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.6.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]


```

##### CONFIGURATION

btadmin@STLPBTDC0693:/etc/ansible$ ansible-config dump --only-changed
DEFAULT_ASK_PASS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

btadmin@STLPBTDC0693:/etc/ansible$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

##### STEPS TO REPRODUCE

```yaml
---
- name: Security Audit - Gather facts
  hosts: all
  gather_facts: no
  connection: local
  tasks:
   - name: Create Output Directory
     file:
      path: ./Output/{{ sitecode }}
      state: directory
     run_once: true
   - name: Get Device Facts
     register: iosfacts_out
     ios_facts:
      gather_subset: all
   - copy: content="{{ iosfacts_out | to_nice_json }}" dest="./Output/{{ sitecode }}/{{ inventory_hostname }}.fct"
- name: Security Configurations
  hosts: MPLS
  gather_facts: no
  connection: local
  tasks:
    - name: Push to MPLS
      ios_config:
        src: "./templates/MPLS-main.conf"
        save_when: modified
- name: Push to DMVPN
  hosts: DMVPN
  gather_facts: no
  connection: local
  tasks:
     - name: Push to DMVPN
       ios_config:
         src: "./templates/DMVPN-main.conf"
         save_when: modified
- name: Push to SW
  hosts: CORE
  gather_facts: no
  connection: local
  tasks:
     - name: Push to SW
       ios_config:
        src: "./templates/SW-main.conf"
        save_when: modified

```

##### EXPECTED RESULTS

The following modules to be run succesfully
btadmin@STLPBTDC0693:/etc/ansible/templates$ more MPLS-main.conf
{% include 'Glan-SNMPv3.conf' %}
{% include 'RTR-SSH.conf' %}
{% include 'RTR-VTY.conf' %}

btadmin@STLPBTDC0693:/etc/ansible/templates$ more Glan-SNMPv3.conf
!
ip access-list standard BT-MGMT-ACL
 permit 10.106.110.10
 permit 10.160.2.184
 permit 10.24.160.164
 permit 10.20.136.181
 permit 10.160.2.141
 permit 10.106.102.79
 permit 10.160.15.254
 permit 10.20.150.10
 permit 10.167.2.225
 permit 10.254.111.0 0.0.0.255
 deny any log
!
snmp-server group BTSNMP-RO v3 auth read full-mib write none access BT-MGMT-ACL
snmp-server group BTSNMP-RW v3 priv read full-mib write full-mib access BT-MGMT-ACL
snmp-server user BTSNMP-USER BTSNMP-RW v3 auth sha c1sc0123 priv des c1sc0123
snmp-server user GLANSNMP-SMARTNET BTSNMP-RW v3 auth md5 **agTYh&6 priv aes 256 *%$#dftg1 access BT-MGMT-ACL
snmp-server view inventory-mib internet included
snmp-server view none iso excluded
snmp-server view full-mib internet included
snmp-server view v1default iso excluded
snmp-server enable traps snmp authentication linkdown linkup coldstart warmstart
snmp-server enable traps cpu threshold
btadmin@STLPBTDC0693:/etc/ansible/templates$ more RTR-SSH.conf
!
ip ssh version 2
!
ip access-list standard SSH-ACL
 remark ### VTY Access ###
 permit 10.0.0.0 0.255.255.255 log
 permit 192.168.0.0 0.0.255.255 log
 deny any log
!
line con 0
  login authentication default
!
btadmin@STLPBTDC0693:/etc/ansible/templates$ more RTR-VTY.conf
!
line vty 0 4
  transport input ssh
  transport output none
  access-class SSH-ACL in vrf-also
  login authentication default
  session-timeout 10
  exec-timeout 10 0
!
line vty 5 15
 transport input none
 transport output none

##### ACTUAL RESULTS

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_egeidy/ansible_module_ios_config.py", line 560, in <module>
    main()
  File "/tmp/ansible_egeidy/ansible_module_ios_config.py", line 489, in main
    load_config(module, commands)
  File "/tmp/ansible_egeidy/ansible_modlib.zip/ansible/module_utils/network/ios/ios.py", line 162, in load_config
  File "/tmp/ansible_egeidy/ansible_modlib.zip/ansible/module_utils/connection.py", line 149, in __rpc__
ansible.module_utils.connection.ConnectionError: timeout trying to send command: login authentication default

fatal: [MPLS]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_egeidy/ansible_module_ios_config.py\", line 560, in <module>\n    main()\n  File \"/tmp/ansible_egeidy/ansible_module_ios_config.py\", line 489, in main\n    load_config(module, commands)\n  File \"/tmp/ansible_egeidy/ansible_modlib.zip/ansible/module_utils/network/ios/ios.py\", line 162, in load_config\n  File \"/tmp/ansible_egeidy/ansible_modlib.zip/ansible/module_utils/connection.py\", line 149, in __rpc__\nansible.module_utils.connection.ConnectionError: timeout trying to send command: login authentication default\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1

```

```
