### ISSUE TITLE
vmware_local_role_manager - broken

### ISSUE THREAD

**Issue by uberjew666** [ansible/ansible#44391]
##### SUMMARY
vmware_local_role_manager module doesn't allow adding additional permissions if the role already exists. It doesn't take the original permissions, it only applies the single new permission.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_local_role_manager

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/shulme/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/shulme/vault/production.txt

##### OS / ENVIRONMENT
vCenter 6.5.0 Build 8024368

##### STEPS TO REPRODUCE
Create a role with a selection of permissions. Run the playbook and allow it to complete. Confirm the role has been created with correct permissions.
Now add a new permission to the original task and run the playbook. Role will be updated but only the new permission will be assigned.

```yaml
vmware_local_role_manager:
    hostname: "{{ ansible_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    local_role_name: "{{ packer_role_name }}"
    local_privilege_ids: [ 'VirtualMachine.Config.AdvancedConfig', 'VirtualMachine.Config.EditDevice', 'VirtualMachine.Config.ReloadFromPath', 'VirtualMachine.Config.Rename', 'VirtualMachine.Config.ResetGuestInfo', 'VirtualMachine.Inventory.Move', 'VirtualMachine.Inventory.Delete', 'VirtualMachine.Inventory.Register', 'VirtualMachine.Inventory.Unregister', 'VirtualMachine.Provisioning.CreateTemplateFromVM', 'VirtualMachine.Provisioning.MarkAsTemplate' ]
    state: present
```

##### EXPECTED RESULTS
The role should have the new permission appended to the original list.

##### ACTUAL RESULTS

```

```
