### ISSUE TITLE
Ansible applies unwanted ACL rules

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#44412]
##### SUMMARY

Ansible applies unwanted ACLs to copied files. This is a followup to #19779 

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /home/florian/dev/ansible_test/ansible.cfg
  configured module search path = ['/home/florian/dev/ansible_test/modules']
  ansible python module location = /home/florian/.local/venvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/florian/.local/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 14:44:17) [GCC 8.1.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### STEPS TO REPRODUCE

```yaml
---

- hosts: all
  gather_facts: no

  # connect as root and switch to any other user with a home dir (restic in this case)

  tasks:
    - block:
      - copy:
          content: "TEST"
          dest: /tmp/testing
      - acl:
          path: /tmp/testing
        register: acl_info
      - debug:
          var: acl_info

      become: yes
      become_user: restic
```

##### EXPECTED RESULTS

```
    "acl_info": {
        "acl": [
            "user::rw-",
            "group::r--",
            "other::r--"
        ],
        "changed": false,
        "failed": false,
        "msg": "current acl"
    }
```

##### ACTUAL RESULTS

```
    "acl_info": {
        "acl": [
            "user::rw-",
            "user:restic:r-x\t#effective:r--",
            "group::---",
            "mask::r--",
            "other::r--"
        ],
        "changed": false,
        "failed": false,
        "msg": "current acl"
    }
```

**Comment by webknjaz** [comment]
Could you please provide us with a clear STR here?

**Comment by apollo13** [comment]
@webknjaz what is an STR?

**Comment by ghost** [comment]
@apollo13 Seems STR stands for Steps To Reproduce.

**Comment by apollo13** [comment]
@webknjaz This is the simplest playbook (using docker so it's reproducible easily) that I could come up with:

```yaml
---

- hosts: localhost
  gather_facts: no

  tasks:
    - docker_container:  name=testing_acl state=started image=ubuntu:18.04 command="sleep infinity"
    - add_host: name=testing_acl ansible_connection=docker ansible_python_interpreter=python3

- hosts: testing_acl
  gather_facts: no

  tasks:
    - raw: apt-get -y update && apt-get -y install python3 sudo acl
      args:
        executable: /bin/bash
    - user: name=testing_acl createhome=yes
    - file: path=/home/testing_acl/test_file state=absent

    # full reproducer here

    - block:
        - copy:
            dest: /home/testing_acl/test_file
            content: test

        - acl:
            path: /home/testing_acl/test_file
          register: acl_info

        - debug:
            var: acl_info

        - assert:  # This is the issues, the acls shouldn't be there!
            that:
              - '"user:testing_acl:r-x\t#effective:r--" not in acl_info.acl'
              - '"mask::r--" not in acl_info.acl'

      become: yes
      become_user: testing_acl
```
