### ISSUE TITLE
iptables module builds the command incorrectly

### ISSUE THREAD

**Issue by egkelly** [ansible/ansible#44420]
##### SUMMARY
Pretty simple: the iptables module builds the command to add a rule incorrectly. Instead of -P for protocol, it puts lowercase -p, ultimately failing out.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
iptables

##### ANSIBLE VERSION
```
2.4.1.0
```

##### OS / ENVIRONMENT

Running from: RHEL 7
Target: RHEL 6

##### STEPS TO REPRODUCE

ansible-playbook /path/to/playbook.yml

```yaml
- name: open ports
  iptables:
     chain: INPUT
     protocol: tcp
     destination_port: 22
     policy: ACCEPT
  when: ansible_distribution_major_version == '6'
```

##### EXPECTED RESULTS

Playbook runs without issue

##### ACTUAL RESULTS

```json
failed: [xxx.xxx.xxx.xxx (item=22) => {"changed": false, "cmd": "/sbin/iptables -t filter -L INPUT -p tcp --destination-port 22", "failed": true, "item": 22, "msg": "iptables v1.4.7: Illegal option `-p' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.7: Illegal option `-p' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.\n", "stderr_lines": ["iptables v1.4.7: Illegal option `-p' with this command", "", "Try `iptables -h' or 'iptables --help' for more information."], "stdout": "", "stdout_lines": []}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/iptables.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/iptables.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @LinusU @sebastiendarocha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by webknjaz** [comment]
@egkelly could you please verify that it affects currently supported version of Ansible? (2.6/devel)

**Comment by egkelly** [comment]
@webknjaz Yes, it happens on 2.6 as well

**Comment by webknjaz** [comment]
Okay, so the assumption about `-P` *meaning* is wrong:
```
➜ iptables --help                                                             
iptables v1.8.0
...
Commands:                                                                                                                      
Either long or short options are allowed. 
  --policy  -P chain target                                                                                                   
                                Change policy on chain to target 
...
Options:
...
[!] --protocol  -p proto        protocol: by number or name, eg. `tcp'
...
```

My guess is that v1.4.7 just doesn't have this short alias for the long version of `--protocol` option.

**Comment by webknjaz** [comment]
No, it looks like the option is there: https://linux.die.net/man/8/iptables-1.4.7

**Comment by webknjaz** [comment]
Extracting the offending command:
```
$ iptables -t filter -L INPUT -p tcp --destination-port 22
iptables v1.4.7: Illegal option `-p' with this command

Try `iptables -h' or 'iptables --help' for more information.

```

Looking more closely it becomes obvious that entry listing (`-L`) is not compatible with protocol filter (`-p`), which is also reproducible with my verison of iptables.

**Comment by webknjaz** [comment]
It looks like the function `get_chain_policy()`, which aims to get a current policy has been introduced by @Solodkiy two years ago.
It gets triggered if there's `policy` option passed to the module from playbook.

**Comment by webknjaz** [comment]
@egkelly I've noticed that #30831 was solved by replacing `policy: ` with `jump: `. Could you try that?

**Comment by OlivierCuyp** [comment]
@webknjaz Thanks, I had the same issue with version `2.6.4`. Using `jump` instead of `policy` worked for me.
I still think this is a bug though... it shouldn't use `-L` but `-I`.

**Comment by solodkiy** [comment]
The real problem is quite confusing api. You just can't use policy and things like destination_port in the same rule. Because it applies to different objects (iptables rule and iptables chain).
Looks like it must be validated and show human error.
More invasive solution: split this commands to different modules, for example iptables, and iptables_chain

**Comment by solodkiy** [comment]
@egkelly just try to split rules
```
- name: open ports
  iptables:
     chain: INPUT
     protocol: tcp
     destination_port: 22
  when: ansible_distribution_major_version == '6'

- name: open policy
  iptables:
     chain: INPUT
     policy: ACCEPT
  when: ansible_distribution_major_version == '6'
```

But looks like you really need jump instead:
```
- name: open ports
  iptables:
     chain: INPUT
     protocol: tcp
     destination_port: 22
     jump: ACCEPT
  when: ansible_distribution_major_version == '6'
```

**Comment by webknjaz** [comment]
Yeah, or maybe at least use `mutually_exclusive` param in arg spec to make ansible yell at the user that those aren't compatible.
But in general, it's better to split out logical features into different modules.

**Comment by solodkiy** [comment]
@webknjaz If we decide to take this way we also can add some more useful functionality to new chain module. For example, you can't  create new chains with current module, so I wrote tiny implementation for my problem: https://github.com/Solodkiy/ansible-iptables-chain-module

**Comment by webknjaz** [comment]
Feel free to send a PR, but in general, it's up to @LinusU @sebastiendarocha to change things here. We can think about other options if they don't show up though.

**Comment by Richard-Foo** [comment]
-p option is correct (at least for Centos7 target) - the real issue is with the -L option.  -L is the command to list the chain contents, not add a rule.  -A (append) or -I (insert) are the proper options.

If the module needs to verify the chain listing, that needs to be done via a separate line, specifying only the table and chain.

This config:
```
- name: Firewall rule
  iptables:
    comment: Allow established TCP connections
    chain: INPUT
    policy: ACCEPT
    protocol: tcp
    ctstate: ESTABLISHED
    ip_version: ipv4
```
results in this invalid command on the target:
`/usr/sbin/iptables -t filter -L INPUT -p tcp -m comment --comment 'Allow established TCP connections' -m conntrack --ctstate ESTABLISHED`

which works if -L is changed to -A (the default action).

**Comment by Akasurde** [comment]
For posterity - 

To open a port -

```yaml
- name: open port 22
  iptables:
     chain: INPUT
     protocol: tcp
     destination_port: 22
     jump: ACCEPT
```

To apply default policy to the given chain - 

```yaml
- name: Apply default policy
  iptables:
	chain: INPUT
	policy: ACCEPT
```
