### ISSUE TITLE
mysql_user trigger changed if

### ISSUE THREAD

**Issue by jpjaatin** [ansible/ansible#44441]
##### SUMMARY

mysql_user trigger changed if:

priv: schema.*: SELECT,INSERT,UPDATE,DELETE,EXECUTE,SHOW VIEW,CREATE,ALTER,REFERENCES,INDEX,CREATE VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,DROP,TRIGGER,CREATE TEMPORARY TABLES

But ALL which is the same does not trigger:

priv: schema.*: ALL

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

2.6.3

```

```

##### OS / ENVIRONMENT

Ubuntu 18 , mysql 5.7.21

##### STEPS TO REPRODUCE

```yaml
- name: Setup MySQL users
  mysql_user:
    name: "{{item.name}}"
    host: "{{item.host}}"
    password: "{{item.password}}"
    login_user: "{{item.login_user}}"
    login_password: "{{item.login_password}}"
    state: "{{item.state}}"
    update_password: "{{item.update_password}}"
    priv: "{{item.priv}}"
  with_items:
    - "{{mysql_server_users}}"

mysql_server_users:
  - name: "asd"
    host: "localhost"
    password: "3453453453453453453"
    login_user: "root"
    login_password: "{{mysql_server_root_password}}"
    state: "present"
    update_password: "on_create"
    priv: |
      transactionlog.*:SELECT,INSERT,UPDATE,DELETE,EXECUTE,SHOW VIEW/
      invoicingsystem.*:SELECT,INSERT,UPDATE,DELETE,EXECUTE,SHOW VIEW,CREATE,ALTER,REFERENCES,INDEX,CREATE VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,DROP,TRIGGER,CREATE TEMPORARY TABLES
```

##### ACTUAL RESULTS

```

```
