### ISSUE TITLE
win_firewall_rule module indicates changed when this is not the case

### ISSUE THREAD

**Issue by JensVanDeynse1994** [ansible/ansible#44450]
##### SUMMARY
When using the win_firewall_rule module the ansible output indicates changed when this is not the case. This only happens when you have to escape a character such as a '\'.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_firewall_rule

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hcadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/hcadmin/.ssh/id_rsa_ansible
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
Ansible running from CentOS 7 (Core)
Managing Windows Server 2012 R2  Standard

##### STEPS TO REPRODUCE
To reproduce do the following:

1. Make a ansible role 'windows-firewall' as such:
```yaml
- name: "Configure Windows firewall rule where a localport, program and remoteIp are defined"
  win_firewall_rule:
    name: "{{ item.name }}"
    action: "{{ item.action }}"
    direction: "{{ item.direction }}"
    program: "{{ item.program }}"
    protocol: "{{ item.protocol }}"
    state: present
    enabled: yes
  with_items: "{{ firewall_rules }}"
```

2. Then create a ansible playbook as such:
```yaml
- name: Configure Ansible, Multicast DNS, RDP & Multicast DNS firewall rules
  hosts: windows
  vars:
    firewall_rules:
      - { name: "Test", action: "allow", direction: "in", program: "%SystemRoot%\\system32\\svchost.exe", protocol: "TCP" }
  roles:
    - windows-firewall
```

3. Run this playbook against a Windows machine twice

##### EXPECTED RESULTS
I expect the playbook to indicate the result as 'changed' the first time and as 'ok' the second time.

##### ACTUAL RESULTS
The playbook (no matter how many times this is executed) will always indicate that the firewall rule has been changed even when this is not the case.
