### ISSUE TITLE
Need to disable facts (gather_facts: false)

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#44457]
##### SUMMARY
The documentation shown here: https://docs.ansible.com/ansible/latest/network/getting_started/first_playbook.html#create-and-run-your-first-network-ansible-playbook

does not disable facts

```yaml
---
- name: Network Getting Started First Playbook
  connection: network_cli
  hosts: all
  tasks:
```

we need to change to->
```yaml
---
- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
```

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/network/getting_started/first_playbook.html#create-and-run-your-first-network-ansible-playbook

##### ANSIBLE VERSION

N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
