### ISSUE TITLE
Add doc to explain how to configure network connection options

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#44458]
##### SUMMARY

The configuration options supported by connection plugins are documented
in connection plugin document, however, in addition to this needs some more docs at a commonplace to explain ways to configure these options and that can be linked from [platform-specific docs](https://docs.ansible.com/ansible/devel/network/user_guide/platform_ios.html).

network_cli: https://docs.ansible.com/ansible/devel/plugins/connection/network_cli.html
netconf: https://docs.ansible.com/ansible/devel/plugins/connection/netconf.html
httapi: https://docs.ansible.com/ansible/devel/plugins/connection/httpapi.html

Example:
Using vars (per task):
```
- name: save running-config
  ios_command:
    commands: copy running-config startup-config
  vars:
    ansible_command_timeout: 30
```

Enviornment variable
```
$export ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=30
```
Global configuration (in ansible.cfg)
```
[persistent_connection ]
command_timeout = 30
```

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
2.7
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
