### ISSUE TITLE
add jinja2 support and example to ios_config page

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#44460]
##### SUMMARY
The page here: https://docs.ansible.com/ansible/latest/modules/ios_config_module.html

is missing any mention of jinja2 or j2 files

The src parameter should mention jinja2 is supported and we should add an easy example like this->

```yaml
- name: render jinja template onto IOS device
  ios_config:
    src: ios_template.j2
```

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

https://docs.ansible.com/ansible/latest/modules/ios_config_module.html

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
