### ISSUE TITLE
add example for jinja2 template for eos_config module

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#44461]
##### SUMMARY
There is no example with jinja2 for Arista

Add an example like this->

```yaml
- name: render jinja template onto Arista switch
  eos_config:
    src: eos_template.j2
```
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
N/A

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
