### ISSUE TITLE
add example for jinja2 to vyos_config module

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#44462]
##### SUMMARY
The documentation page has no example using j2
https://docs.ansible.com/ansible/latest/modules/vyos_config_module.html

add an example like this->

```yaml
- name: render jinja template onto VyOS router
  vyos_config:
    src: vyos_template.j2
```

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
vyos_config

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
