### ISSUE TITLE
ovirt_vms with state: suspended fails as trying to reference 'ref' variable before it's assigned

### ISSUE THREAD

**Issue by gramgit** [ansible/ansible#44466]
##### SUMMARY
Just trying to suspend my VM before shutting down so that I have a save state.  When I do this it fails with the following Traceback:
```
File "/tmp/ansible_in1VTM/ansible_module_ovirt_vms.py", line 2030, in main
    vms_module.post_present(ret['id'])
UnboundLocalError: local variable 'ret' referenced before assignment
```
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible_module_ovirt_vms.py

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/graeme/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

ansible-config dump returns nothing
##### OS / ENVIRONMENT

Ubuntu 18.04
##### STEPS TO REPRODUCE

```yaml
    - name: Hibernate the VM
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: suspended
        name: "{{ inventory_hostname }}"
        wait: true
```

##### EXPECTED RESULTS

was expecting the VM to be suspended
##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_MXry_8/ansible_module_ovirt_vms.py", line 2030, in main
    vms_module.post_present(ret['id'])
UnboundLocalError: local variable 'ret' referenced before assignment

fatal: [devops.escalus.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "affinity_group_mappings": [], 
            "affinity_label_mappings": [], 
            "allow_partial_import": null, 
            "ballooning_enabled": null, 
            "boot_devices": null, 
            "boot_menu": null, 
            "cd_iso": null, 
            "clone": false, 
            "clone_permissions": false, 
            "cloud_init": null, 
            "cloud_init_nics": [], 
            "cloud_init_persist": false, 
            "cluster": null, 
            "cluster_mappings": [], 
            "comment": null, 
            "cpu_cores": null, 
            "cpu_mode": null, 
            "cpu_pinning": null, 
            "cpu_shares": null, 
            "cpu_sockets": null, 
            "cpu_threads": null, 
            "custom_properties": null, 
            "delete_protected": null, 
            "description": null, 
            "disk_format": "cow", 
            "disks": [], 
            "domain_mappings": [], 
            "fetch_nested": false, 
            "force": false, 
            "graphical_console": null, 
            "high_availability": null, 
            "high_availability_priority": null, 
            "host": null, 
            "id": null, 
            "initrd_path": null, 
            "instance_type": null, 
            "io_threads": null, 
            "kernel_params": null, 
            "kernel_path": null, 
            "kvm": null, 
            "lease": null, 
            "lun_mappings": [], 
            "memory": null, 
            "memory_guaranteed": null, 
            "memory_max": null, 
            "name": "devops.escalus.com", 
            "nested_attributes": [], 
            "nics": [], 
            "numa_nodes": [], 
            "numa_tune_mode": null, 
            "operating_system": null, 
            "placement_policy": null, 
            "poll_interval": 3, 
            "quota_id": null, 
            "reassign_bad_macs": null, 
            "rng_device": null, 
            "role_mappings": [], 
            "serial_console": null, 
            "serial_policy": null, 
            "serial_policy_value": null, 
            "smartcard_enabled": null, 
            "soundcard_enabled": null, 
            "sso": null, 
            "state": "suspended", 
            "stateless": null, 
            "storage_domain": null, 
            "sysprep": null, 
            "template": null, 
            "template_version": null, 
            "timeout": 180, 
            "timezone": null, 
            "type": null, 
            "usb_support": null, 
            "use_latest_template_version": null, 
            "vmware": null, 
            "vnic_profile_mappings": [], 
            "wait": true, 
            "watchdog": null, 
            "xen": null
        }
    }, 
    "msg": "local variable 'ret' referenced before assignment"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/ovirt/ovirt_vms.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_vms.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @machacekondra @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gramgit** [comment]
Work around is to call the oVirt REST API direct

E.g.

```
- name: Suspend the VM
      uri:
        url: https://ovirt-engine.example.com/ovirt-engine/api/vms/{{ ovirt_vms[0].id }}/suspend
        method: POST
        user: admin@internal
        password: "{{ engine_password }}"
        force_basic_auth: yes
        status_code: 202
        validate_certs: False
        headers:
            Content-Type: application/xml
            Accept: application/xml
        body: "<action/>"
```
`ovirt_vms[0].id` being the return value grabbed from the `ovirt_vms_facts` module
