### ISSUE TITLE
postgresql_* commands hang

### ISSUE THREAD

**Issue by AlexTaran** [ansible/ansible#44485]
##### SUMMARY

all postgresql_* commands (postgresql_db, postgresql_user, postgresql_privs) hang permanently.
After Ctrl+C and restarting playbook again it proceeds to the next task each time. It means that the command eventually succeeded, but the task hanged. EXCEPT: postgresql_privs - just hangs each time.
```
Postgresql version: psql --version: psql (PostgreSQL) 10.5 (Ubuntu 10.5-1.pgdg16.04+1)
Running with -vvv results as command output (see below) and hangs permanently at EXEC /bin/sh -c 'sudo -H -S -n -u postgres /bin/sh -c '"'"'echo BECOME-SUCCESS-dbbtkthuhxnoggubgmyfgomvvssjfobd; /usr/bin/python /var/tmp/ansible-tmp-1534888446.04-257423723583508/postgresql_privs.py'"'"' && sleep 0'

```
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

postgresql_privs_module

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

Empty output

##### OS / ENVIRONMENT

Linux mint 19
Ansible is targeted to localhost

##### STEPS TO REPRODUCE

Install ansible 2.6.3, postgresql 10.5, run postgresql_* commands

```yaml
- name: Create database
  become: true
  become_user: postgres
  postgresql_db: name=somedb

- name: Create role
  become: true
  become_user: postgres
  postgresql_user:
    db: somedb
    name: someuser
    password: "somepassword"
    role_attr_flags: NOSUPERUSER
    encrypted: yes

- name: Grant user privs on db
  become: true
  become_user: postgres
  postgresql_privs:
    db: somedb
    role: someuser
    type: database
    privs: ALL
```

##### EXPECTED RESULTS

Ansible works

##### ACTUAL RESULTS

Ansible hangs

```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp/ansible-tmp-1534888446.04-257423723583508 `" && echo ansible-tmp-1534888446.04-257423723583508="` echo /var/tmp/ansible-tmp-1534888446.04-257423723583508 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/database/postgresql/postgresql_privs.py
<localhost> PUT /home/username/.ansible/tmp/ansible-local-284542NmFeX/tmpLpkjhU TO /var/tmp/ansible-tmp-1534888446.04-257423723583508/postgresql_privs.py
<localhost> EXEC /bin/sh -c 'setfacl -m u:postgres:r-x /var/tmp/ansible-tmp-1534888446.04-257423723583508/ /var/tmp/ansible-tmp-1534888446.04-257423723583508/postgresql_privs.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u postgres /bin/sh -c '"'"'echo BECOME-SUCCESS-dbbtkthuhxnoggubgmyfgomvvssjfobd; /usr/bin/python /var/tmp/ansible-tmp-1534888446.04-257423723583508/postgresql_privs.py'"'"' && sleep 0'
```
