### ISSUE TITLE
mode parameter of copy.py not work when copy recursively

### ISSUE THREAD

**Issue by ptux** [ansible/ansible#44494]
##### SUMMARY

When src is a dir, files are assigned the correct mode but sub dirs are not.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy.py

##### ANSIBLE VERSION

```
2.6
```

##### STEPS TO REPRODUCE

```
    - name: copy dir on localhost to a remote host
      copy:
        remote_src: False
        src: dir_on_local
        dest: /usr/local/src/new_remote_dir_dest
        mode: u=rwx,go-wx

    - name: copy dir on a remote host
      copy:
        remote_src: True
        src: /etc/httpd
        dest: /usr/local/src/new_remote_dir_dest
        mode: u=rwX,go-rwx

```
##### EXPECTED RESULTS
All files and sub dirs are assigned the specified mode.

##### ACTUAL RESULTS
Files are assigned the specified mode.
But, sub dirs are NOT assigned the specified mode
