### ISSUE TITLE
Playbook variables are not common to all tasks

### ISSUE THREAD

**Issue by hehe2** [ansible/ansible#44496]
##### SUMMARY

The variables are regenerated for every task in a playbook and not once at the start of the playbook as expected... Thus any variable including a randomly generated value is *not* common which is really cumbersome when you need to have a common random "token" in all your tasks.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -F /root/.ssh/config -o ControlMaster=auto -o ControlPersist=30m
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /root/.ssh/ansible-%%r@%%h:%%p
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ansible server and hosts:
cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

##### STEPS TO REPRODUCE

```yaml

Hi, let's suppose you have a simple playbook:

% cat ansible/cba/bug_vars.yaml
---
- hosts: all
  gather_facts: false

  vars:
    my_random_number: "{{ range(1, 65535) | random }}"

  tasks:

    - name: Printing my random number
      debug:
        msg: "My random number is {{ my_random_number }}."


    - name: Printing my random number (again)
      debug:
        msg: "My random number is {{ my_random_number }}."

Now, I assume after reading all the doc that the play variables are common to all tasks.

```

##### EXPECTED RESULTS

I expect to have the same displayed "my_random_number" value in both tasks.

##### ACTUAL RESULTS

```
Here is the result though:

% ansible-playbook ansible/cba/bug_vars.yaml -l vuhplabgtans001

PLAY [all] **********************************************************************************************************************************************************************************************************************************

TASK [Printing my random number] ************************************************************************************************************************************************************************************************************
ok: [vuhplabgtans001] => {
    "msg": "My random number is 5279."
}

TASK [Printing my random number (again)] ****************************************************************************************************************************************************************************************************
ok: [vuhplabgtans001] => {
    "msg": "My random number is 10239."
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
vuhplabgtans001            : ok=2    changed=0    unreachable=0    failed=0




```
