### ISSUE TITLE
k8s module ignores authorization parameters

### ISSUE THREAD

**Issue by megakoresh** [ansible/ansible#44504]
##### SUMMARY
`k8s` module seems to completely ignore whatever configuration is passed via `username` and `password` parameters and always use configuration from `~/.kube`. If `oc login` has not been performed before running the playbook, openshift returns an 403 and says that I was trying to run as `system:anonymous`. If I do perform `oc login` prior to running the playbook, the cluster I am authenticating against will be the only one the playbook will run on, even if it is set to run on multiple clusters.

Worse yet - it will run the same playbook multiple times on same cluster, using variables for different clusters every time, as if it was running properly - so the configuration in `~/.kube` overrides the url parameter as well, which can completely mess up the whole project(s).
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /Users/partypooper/.ansible.cfg
  configured module search path = ['/Users/partypooper/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/partypooper/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ansible
  executable location = /Users/partypooper/.pyenv/versions/3.6.4/bin/ansible
  python version = 3.6.4 (default, Feb  5 2018, 13:51:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
```

##### OS / ENVIRONMENT

MacOS 10.12 High Sierra

##### STEPS TO REPRODUCE

```yaml
- hosts: openshift
  connection: local
  gather_facts: false
  become: false
  serial: 1
  vars_prompt:
    - name: oc_user
      prompt: Openshift username
      private: false
    - name: oc_password
      prompt: Openshift password
      private: true
  tasks:
    - name: Create projects
      k8s:
        host: '{{ansible_host}}'
        username: '{{oc_user}}'
        password: '{{oc_password}}'
        definition:
          kind: Project
          apiVersion: v1
          metadata:
            name: '{{project_name}}'
            openshift.io/description: '{{project_description}}'
            openshift.io/display-name: '{{project_display_name}}'
            openshift.io/requester: '{{oc_user}}'
        state: "{{state|default('present')}}"
```

Inventory is something like this:
```
[openshift]
openshift1            ansible_host=https://my-amazing-openshift1.peruna.porkkana
openshift2            ansible_host=https://my-amazing-openshift2.peruna.porkkana
```

##### EXPECTED RESULTS
Project is provisioned to both openshift clusters

##### ACTUAL RESULTS
Forbidden: `system:anonymous` cannot create projectrequests in cluster scope or something like that.

```
//Forbidden: `system:anonymous` cannot create projectrequests in cluster scope or something like that. (I cant actually paste the whole output)
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
I have an open PR that should improve the reliability of the authorization overrides here: https://github.com/ansible/ansible/pull/44142

I think it may fix your issue, there were some problems related to the priority of certain authorization methods that caused some user provided values to be clobbered.

**Comment by fabianvf** [comment]
This should be fixed with https://github.com/ansible/ansible/pull/44142

**Comment by megakoresh** [comment]
@fabianvf 2.7 has just released, I saw your changes there and decided to test: no luck. Same situation
```yaml
- hosts: openshift-prod
  connection: local
  gather_facts: false
  become: false
  serial: 1
  tasks:
    - name: Create ci user
      k8s:
        host: '{{ansible_host}}'
        namespace: '{{project_name}}'
        username: '{{oc_user}}'
        password: '{{oc_password}}'
        definition: "{{lookup('template', 'templates/serviceaccount.yml.j2') | from_yaml}}"
        state: "{{state|default('present')}}"
```
And here is the output
```
fatal: [openshift-prod1]: FAILED! => {
    "changed": false,
    "error": 403,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": "https://openshift1.peruna",
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ssl_ca_cert": null,
            "state": "present",
            "username": "megakoresh@company.peruna",
            "verify_ssl": null
        }
    },
    "msg": "Failed to retrieve requested object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"serviceaccounts \\\\\"ci-user\\\\\" is forbidden: User \\\\\"system:anonymous\\\\\" cannot get serviceaccounts in the namespace \\\\\"project-name\\\\\": User \\\\\"system:anonymous\\\\\" cannot get serviceaccounts in project \\\\\"project-name\\\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"ci-user\",\"kind\":\"serviceaccounts\"},\"code\":403}\\n'",
    "reason": "Forbidden",
    "status": 403
}
```
How did you test it? This bug is causing a lot of problems for us, since we use many clusters its very disappointing that its not fixed.
Like before it works if I pre-emptively `oc login` to the cluster, but of course fails on every other cluster in the inventory, forcing me to run the playbook for each cluster individually logging into it beforehand.

**Comment by fabianvf** [comment]
Unfortunately I was testing it out with a focus on certificate verification and API key authorization and assumed user/pass was the same issue, but it looks like for basic auth the authentication headers aren't properly set. I'll see if I can get that fix into 2.7.1. My apologies for the false hope.

**Comment by megakoresh** [comment]
Updated bug description to mention that configuration in `~/.kube` also overrides the url and project parameters, just in case this is due to a different issue (shouldn't be). Far as I understand the intended behaviour is that parameters specified in playbook should always take precedence over anything in `~/.kube`

**Comment by fabianvf** [comment]
I think we fixed that in 2.7 with #44142, but it's not been backported to 2.6.

**Comment by megakoresh** [comment]
No, I have run the playbooks with 2.7 and the behaviour is still the same - if I do `oc login my-amazing-openshift1.peruna.porkkana`  then run the playbook without setting the `--limit` to openshift1 then it will run against openshift1 twice, using group_vars for openshift2 on the second run, regardless of what the `host` argument receives.

This can be demonstrated by brining up two instances of minishift with different admin credentials and then using those as targets for the playbook.

**Comment by willthames** [comment]
see also https://github.com/ansible/ansible/issues/46163

**Comment by fabianvf** [comment]
ah, good call @willthames. @megakoresh, if you set `host` + `api_key` rather than `host` + `username` + `password` do you see the same behavior? Wondering if the issue with password auth is confounding this. Though I'm still not sure how it's loading the kubeconfig at all when username, password and host are all set, it should be skipping the kubeconfig entirely in that case...

**Comment by megakoresh** [comment]
@fabianvf I dont know why it didnt notify me, but yes setting `host` + `api_key` does seem to work as expected so those issues may be linked.

UPD: After some research it seems like basic authentication to Kubernetes is a real sore spot. Problem is that since Openshift uses OAuth to issue tokens and K8S doesn't really have any such concepts I dont see any way to deal with authentication using kubernetes-only code. FYI if I run `kubectl` commands I get the exact same error:
```
Error from server (Forbidden): pods is forbidden: User "system:anonymous" cannot list pods in the namespace...
```
Despite passing in the username and password. I guess whoever decided to deprecate openshift modules in favor of the generic k8s module, didn't think about that, huh?

Read also: https://github.com/kubernetes-client/python/issues/430

**Comment by fabianvf** [comment]
>  I guess whoever decided to deprecate openshift modules in favor of the generic k8s module, didn't think about that, huh?

Actually the old openshift modules used the same authentication logic, relying on the auth described in the swagger API spec, so I think we likely would have hit this regardless. Kubernetes actually does support basic auth but they seem to have removed it from the spec due to an unresolved issue in swagger-codegen, which would have affected the openshift spec as well. We may be able to work around this by setting the headers for the request manually for basic auth though.

**Comment by megakoresh** [comment]
> We may be able to work around this by setting the headers for the request manually for basic auth though.

I have actually just tried that by simply editing the `ansible/module_utils/k8s/common.py` file and added

```python
setattr(configuration, 'api_key', {'authorization': urllib3.util.make_headers(basic_auth=auth.get('username') + ':' + auth.get('password')).get('authorization')})
```

just before `kubernetes.client.Configuration.set_default(configuration)`

to quickly test this hypothesis, to no effect. I think this is a problem with the kubernetes library, but even if that is solved, I am not exactly certain this problem will go away. Reason is what I outlined above - I cannot use basic auth to login with `kubectl` either, and my guess it that this is because `oc login` authenticates against the OAuth server that is built into Openshift and which provides LDAP integration among other things. Kubernetes has no apis like this, so I am not sure if authentication is really interoprable. You, of course, know this better than I, so I do hope you find some solution.

**Comment by mmazur** [comment]
So, for a full rundown of the current status of this. I'm running:
- ansible from today's devel branch
- minikube with apiserver started with `--basic-auth-file`
- `~/.kube/config` has been removed to make sure the config file does not in any way interfere with module parameters

I know basic auth is configured correctly, because:
- running `curl -H "Authorization: Basic $(echo -ne admin:zupa.8|base64)" https://192.168.39.183:8443/apis -k` gets me an APIGroupList
- running same thing with the wrong password gets me a `"status": "Failure", "message": "Unauthorized",`

Now when I try to do anything with `k8s` or `k8s_facts`, with the important bits looking like this:

```
      k8s:
       host: https://192.168.39.183:8443
       verify_ssl: no
       username: admin
       password: zupa.8
       (…)
```

I also end up with the same _user system:anonymous_ error:

```
    "msg": "Failed to retrieve requested object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"persistentvolumeclaims \\\\\"pvc-demo\\\\\" is forbidden: User \\\\\"system:anonymous\\\\\" cannot get resource \\\\\"persistentvolumeclaims\\\\\" in API group \\\\\"\\\\\" in the namespace \\\\\"default\\\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"pvc-demo\",\"kind\":\"persistentvolumeclaims\"},\"code\":403}\\n'",
    "reason": "Forbidden",
    "status": 403
```

I've tested previously that using an openshift token for this works correctly, so the type of auth that does not work is user+pwd.
