### ISSUE TITLE
a way to reference a variable inside the same hash

### ISSUE THREAD

**Issue by wu-lee** [ansible/ansible#4450]
An illustration:

```
--- # some vars.yml file
dan:
  user: dan
  group: staff
  home: /Users/{{ dan.user }}
```

This will cause an error in a task which attempts to use "{{ dan.home }}", such as:

```
 fatal: [osx] => recursive loop detected in template string: {{dan.home}}/.oh-my-zsh
```
