### ISSUE TITLE
win_lineinfile fails when path contains bracket

### ISSUE THREAD

**Issue by crossan007** [ansible/ansible#44508]
##### SUMMARY
When a path containing a bracket is used with `win_lineinefile`, the module always reports that the path does not exist.  This is consistent with #34168 and will share a fix with #37901 (https://github.com/ansible/ansible/pull/37901/files#diff-62fd6612943ccdb6cd026094c9d4763bR90)

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_lineinfile

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
  - name: Ensure line is not present
    win_lineinfile:
      path: "C:\\MyFiles\\MyCool[Sort-of]File.cshtml"
      line: "@using System.Web"
      state: absent
```

##### EXPECTED RESULTS
The line should have been removed

##### ACTUAL RESULTS

The command fails

```
"Path C:\\MyFiles\\MyCool[Sort-of]File.cshtm does not exist !"
```
