### ISSUE TITLE
Jinja2 None in Tasks file results in empty string instead on Null

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#44503]
##### SUMMARY

Currently it is not possible to produce the following line by using jinja2 filters inside a tasks file: ` foo: Null`. The equivalent of Null in jinja2 is None, so one would expect that this one is equal: `foo: '{{ None }}'` but it results in an empty string. This is a problem if one wants to conditionally include a property (foo in this example) into a task. Currently there is no way of doing this except minifying the yaml of the whole task and bilding that minified yaml by using jinja2, but that is not really readable and if many properties are involved not feasible.

Non working example:

```yaml
- name: Add/Update zones
  os_zone:
    auth: '{{ os_cloud_provider.auth }}'
    name: '{{ item.name }}'
    masters: '{% if item.nameserver is not None %}{{item.nameserver}}{%endif%}'
  with_items: '{{ os_zones }}'
```

Non readable example (but semi working):

```yaml
- name: TTTT
  os_zone: '{{ ''{"auth": '' + os_cloud_provider.auth + '', "name": "'' + item.name + ''", "masters": "'' + item.nameserver|default("Null") + ''"}'' }}'
  with_items: '{{ os_zones }}'
```
Why semi working? As you might know, the property auth is supposed to be of type dict and not str. so it cannot be provided by this jinja representative, it would require first being converted into a yaml string representative of that dict by using filters and such. But as you should already see, this is not usable.

So basically I consider this
`foo: '{{ None }}'` == `foo: ''` == `foo: {{ "" }}`
a bug, as it should be
`foo: '{{ None }}'` == `foo: Null`
and
`foo: '{{ "" }}'` == `foo: ''`
and of course
`foo: '{{ None }}'` != `foo: ''`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

jinja2 parsing in task files

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Put the following into a task file and observe there behavior differences

- `foo: '{{ None }}'`
- `foo: ''`
- `foo: {{ "" }}`

##### EXPECTED RESULTS

Putting `foo: '{{ None }}'` into a task file should be equivalent to `foo: Null`

##### ACTUAL RESULTS

`foo: '{{ None }}'` is equivalent to `foo: ''`, which results in the parameter not being dropped before passing it to the module. $module than throws an exception as no value has been supplied (if passing an empty string and not specifying at all has different meaning)

##### Ways to fix

This bug can be fixed by two different ways:

- Change tha jinja2 parsing inside a task file to differentiate between an empty string and none being returned
- Updating the module guideline to treat passing an empty string the same as Null and fix all official modules that currently don't.
