### ISSUE TITLE
URI register and json that return a key with a dot

### ISSUE THREAD

**Issue by Poil** [ansible/ansible#44516]
##### SUMMARY
When using the uri module and register the json result of a query, if the json have a key that contains a dot, json.return is empty

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/ansible_library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
```yaml
  - name: Get API token
    uri:
      method: POST
      url: http://salt.xxxxx:8000/login
      body: {
        "username": "test",
        "password": "xxxxx",
        "eauth": "pam"
      }
      body_format: json
      headers:
        Accept: "application/json"
    register: login_output

  - name: Deploy environment
    uri:
      method: POST
      url: http://salt.xxxxx:8000
      body: {
        "client": "runner_async",
        "fun": "state.orchestrate",
        "mods": "orch",
        "pillar": {
          "vcenter": "{{ vcenter }}",
          "env": "{{ env }}",
          "num": "{{ \"%02d\" | format(num) }}",
          "infos_sup": "{{ infos_sup }}",
          "domain": "{{ domain }}",
          "cluster": "{{ cluster }}",
          "datastore": "{{ datastore }}",
          "folder": "{{ folder }}",
          "datacenter": "{{ datacenter }}",
        }
      }
      return_content: 1
      body_format: json
      headers:
        Accept: "application/json"
        X-Auth-Token: "{{ login_output.x_auth_token }}"
    register: deployment_result

  - name: Check Deployment
    uri:
      method: POST
      url: http://salt.xxxxx:8000
      # timeout: 3600
      body: {
        "client": "runner",
        "fun": "jobs.lookup_jid",
        "jid": "{{ deployment_result['json']['return'][0]['jid'] }}",
      }
      return_content: 1
      body_format: json
      headers:
        Accept: "application/json"
        X-Auth-Token: "{{ login_output.x_auth_token }}"
    register: job_status
    #until: job_status.json.return.tlsslt\-p01\-mst.engsec_master.success == false
    #retries: 10
    #delay: 30
```

##### EXPECTED RESULTS
Json return should have the same result as this curl reply
```json
{"return": [{"tlsslt-p01-mst.xxxxxx_master": {"fun_args": [{"pillar": {"datacenter": "Datacenter", "domain": "team2.xxx.xxxx", "infos_sup": "tst", "cluster": "Cluster", "num": "06", "env": "d", "folder": "xxxxx", "vcenter": "tlssvc-p01-65u1", "datastore": "NAS"}, "mods": "orch"}], "jid": "20180822172413112449", "return": {"outputter": "highstate", "data": {"tlsslt-p01-mst.xxxxxx_master": {"salt_|-deploy_ccs_|-deploy_ccs_|-state": {"comment": "No minions returned", "name": "deploy_ccs", "start_time": "17:24:34.600813", "result": false, "duration": 149.693, "__run_num__": 3, "__sls__": "orch", "changes": {}, "__id__": "deploy_ccs"}, "salt_|-clone_backend_|-cloud.create_|-runner": {"comment": "Runner function 'cloud.create' executed.", "name": "cloud.create", "__orchestration__": true, "start_time": "17:24:31.324141", "result": true, "duration": 1582.507, "__run_num__": 0, "__jid__": "20180822172432646916", "__sls__": "orch", "changes": {"return": false}, "__id__": "clone_backend"}, "salt_|-clone_ccs_|-cloud.create_|-runner": {"comment": "Runner function 'cloud.create' executed.", "name": "cloud.create", "__orchestration__": true, "start_time": "17:24:32.908457", "result": true, "duration": 1536.675, "__run_num__": 1, "__jid__": "20180822172434215701", "__sls__": "orch", "changes": {"return": false}, "__id__": "clone_ccs"}, "salt_|-deploy_backend_|-deploy_backend_|-state": {"comment": "No minions returned", "name": "deploy_backend", "start_time": "17:24:34.446846", "result": false, "duration": 153.784, "__run_num__": 2, "__sls__": "orch", "changes": {}, "__id__": "deploy_backend"}}}, "retcode": 1}, "success": false, "_stamp": "2018-08-22T15:24:14.371908", "user": "test", "fun": "runner.state.orchestrate"}}]
```

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "job_status": {
        "access_control_allow_credentials": "true", 
        "access_control_allow_origin": "*", 
        "access_control_expose_headers": "GET, POST", 
        "allow": "GET, HEAD, POST", 
        "cache_control": "private", 
        "changed": false, 
        "connection": "close", 
        "content": "{\"return\": [{}]}", 
        "content_length": "16", 
        "content_type": "application/json", 
        "cookies": {
            "session_id": "1c516bef097d78f6a3f14116c0244e16a487e3ba"
        }, 
        "cookies_string": "session_id=1c516bef097d78f6a3f14116c0244e16a487e3ba", 
        "date": "Wed, 22 Aug 2018 15:41:22 GMT", 
        "failed": false, 
        "json": {
            "return": [
                {}
            ]
        }, 
        "msg": "OK (16 bytes)", 
        "redirected": false, 
        "server": "CherryPy/5.6.0", 
        "set_cookie": "session_id=1c516bef097d78f6a3f14116c0244e16a487e3ba; expires=Thu, 23 Aug 2018 01:41:22 GMT; Path=/", 
        "status": 200, 
        "url": "http://salt.engsec:8000", 
        "vary": "Accept-Encoding"
    }
}
```
