### ISSUE TITLE
Please add an option to resize Azure vm_size in module azure_rm_virtualmachine

### ISSUE THREAD

**Issue by myownhost** [ansible/ansible#44513]
##### SUMMARY
Please add an option to resize vm_size

##### ISSUE TYPE
If i run a playbook which has another vm_size than the vm has at the moment. The playbook returns OK at the moment.

##### COMPONENT NAME
 ansible/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py 

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/playbooks/switches/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
DEFAULT_FORKS(/etc/ansible/playbooks/switches/ansible.cfg) = 50
DEFAULT_HOST_LIST(/etc/ansible/playbooks/switches/ansible.cfg) = [u'/etc/ansible/playbooks/switches/hosts']
DEFAULT_LOG_PATH(/etc/ansible/playbooks/switches/ansible.cfg) = /var/log/ansible/network.log
HOST_KEY_CHECKING(/etc/ansible/playbooks/switches/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/playbooks/switches/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/playbooks/switches/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
    ---
    - name: Azure - Resize vm
      hosts: localhost
      connection: local
      gather_facts: no

      tasks:

      - name: resize VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          vm_size: "{{ vm_size }}"
```

##### EXPECTED RESULTS

Resize of Azure VM to new size

##### ACTUAL RESULTS

Nothing

```
PLAY [Azure - Resize vm] *******************************************************


TASK [resize VM] ***************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
