### ISSUE TITLE
lookup with skip_missing=True produces errors when key is missing

### ISSUE THREAD

**Issue by jarpit1** [ansible/ansible#44526]
##### SUMMARY
The key skip_missing=True does not skip missing keys during the lookup and produces an error.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

subelements

##### ANSIBLE VERSION

```
ansible --version
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/<user>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14
```

##### CONFIGURATION

ansible-config dump --only-changed
ANSIBLE_COW_SELECTION(/etc/ansible/ansible.cfg) = default
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = 
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
##### OS / ENVIRONMENT

macOS High Sierra version 10.13.6

##### STEPS TO REPRODUCE

```yaml
command run: ansible-playbook -i "localhost," lookup_test.yml --ask-pass

- name: show var structure as it is needed for example to make sense
  gather_facts: false
  hosts: all
  vars:
    users:
      - name: alice
        authorized:
          - /tmp/alice.pub
          - /tmp/mary.pub
        mysql:
            password: mysql-password
            hosts:
              - "%"
              - "127.0.0.1"
              - "::1"
              - "localhost"
            privs:
              - "*.*:SELECT"
              - "DB1.*:ALL"
        groups:
          - wheel
      - name: bob
        authorized:
          - /tmp/bob.pub
        mysql:
            password: other-mysql-password
            hosts:
              - "db1"
            privs:
              - "*.*:SELECT"
              - "DB2.*:ALL"
  tasks:
    - name: list groups for user that have them, dont error if they don't
      debug: var=item
      with_list: "{{lookup('subelements', users, 'groups', skip_missing=True)}}"
```

##### EXPECTED RESULTS

Lookup will list the users with groups and if a user has no group, no error will be produced.
##### ACTUAL RESULTS

Ansible errors because it cannot find the groups key

```
_________________________________________________________
/ PLAY [show var structure as it is needed for example to \
\ make sense]                                             /
 ---------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 __________________________________________________________
/ TASK [list groups for user that have them, dont error if \
\ they don't]                                              /
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while runningthe lookup plugin 'subelements'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not find 'groups' key in iterated item '{u'authorized': [u'/tmp/bob.pub'], u'name': u'bob', u'mysql': {u'password': u'other-mysql-password', u'hosts': [u'db1'], u'privs': [u'*.*:SELECT', u'DB2.*:ALL']}}'"}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
