### ISSUE TITLE
Module tower_user not idempotent

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#44530]
##### SUMMARY
The `tower_user` module is not idempotent, every time I run a play to create (the same) user, the module reports `changed`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_user

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/robertdb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
`ansible-config dump --only-changed` gives not output

##### OS / ENVIRONMENT
Control node: Fedora 28
Managed node: CentOS 7

##### STEPS TO REPRODUCE
Simplified, but please have a look at [the Ansible role](https://github.com/robertdebock/ansible-role-awx)

```yaml
- name: create user
  tower_user:
    username: test
    password: test
    email: test@example.com
    first_name: Test
    last_name: Test
```

##### EXPECTED RESULTS
Once a user is created, the module should return `ok` instead of `changed`.

##### ACTUAL RESULTS
```
TASK [robertdebock.awx : create user] ******************************************
changed: [centos7 -> localhost] => changed=true 
  id: 2
  state: present
  username: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
```
