### ISSUE TITLE
gitlab_project module error bool object is not iterable

### ISSUE THREAD

**Issue by slayer01** [ansible/ansible#44564]
##### SUMMARY
While trying to create a new gitlab project with the ansible module gitlab_project it fails with an error message: 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'bool' object is not iterable
fatal: [10.100.2.107 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 395, in <module>\n    main()\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 368, in main\n    project_exists = project.existsProject(group_name, project_name)\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 199, in existsProject\n    if self.existsGroup(group_name):\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 220, in existsGroup\n    for data in user_data:\nTypeError: 'bool' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gitlab_project

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry
```

##### OS / ENVIRONMENT

```
Linux ansible.host.example 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
Linux ansible.target.host.example.com 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml
    - name: CREATE GIT REPO
      gitlab_project:
        server_url: "https://git.example.com/"
        login_token: "xxxxxxxxxxxxxxxxx"
        name: "{{ ansible_hostname }}"
        group: "etckeeper"
        state: present
      delegate_to: localhost
```

##### EXPECTED RESULTS

It should create a project in our git instance named with the targets hostname

##### ACTUAL RESULTS

It stops with this error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'bool' object is not iterable
fatal: [10.100.2.107 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 395, in <module>\n    main()\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 368, in main\n    project_exists = project.existsProject(group_name, project_name)\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 199, in existsProject\n    if self.existsGroup(group_name):\n  File \"/tmp/ansible_L6tvt3/ansible_module_gitlab_project.py\", line 220, in existsGroup\n    for data in user_data:\nTypeError: 'bool' object is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/source_control/gitlab_project.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab_project.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dj-wasabi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by slayer01** [comment]
Hi again,

am I the only one faceing this problem?
Can´t believe it, unfortunately I found no solution for this up to now :(

**Comment by whizz0** [comment]
Hi, I have the same issue after upgrading Gitlab recently. I guess that they have changed someting in their APIs :/

**Comment by aoyawale** [comment]
do you guys have `pyapi-gitlab` installed?

**Comment by whizz0** [comment]
@jlozadad - I hadn't, but after installing the error is still the same.

**Comment by slayer01** [comment]
since the pyapi-gitlab page says git version 9.1.X is still under development: https://github.com/pyapi-gitlab/pyapi-gitlab
I see no chance to get this ansible module running again with pyapi-gitlab.

Any ideas on how to create, edit, etc git projects with ansible and an up-to-date version of gitlab?

Btw: python-gitlab doesn´t work neither, see my issue here (solution was using pyapi-gitlab :(): https://github.com/ansible/ansible/issues/40154 maybe @sivel has any more ideas?

Thanks to all.

**Comment by missnebun** [comment]
+1
I got the same problem.

**Comment by missnebun** [comment]
@dj-wasabi any idea about this ... ?

**Comment by svavassori** [comment]
It could be a credential problem.

I did a quick-and-dirty patch to make gitlab_project work with v4 and I face this error if the authentication fails (wrong token or user for instance): instead of throwing an exception it simply returns false and that value is used in a for loop, like here: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab_project.py#L219

To see the actual error that is returned by the server, you can save the temporary files created by ansible by set  to true ANSIBLE_KEEP_REMOTE_FILES  variable and then manually debug it.

**Comment by BartJoris** [comment]
Hi, are there any updates on this? 
Thanks!

**Comment by mihai-satmarean** [comment]
Same thing here.
Ansible 2.7.1
Same call with URI module works.
Would be great to have it working again.
Thanks!

**Comment by whizz0** [comment]
@mihai-satmarean 
Can you paste an example of doing such call with URI module?

**Comment by mihai-satmarean** [comment]
@whizz0 
here you are:
```
   - name: "create the gitlab {{ myproject_name }} uri method"
     uri:
       url: "https://{{ gitlab_repository_host_name }}.{{ gitlab_repository_host_domanin }}/api/v4/projects?name={{ myproject_name }}&namespace_id={{ mynamespace_id }}&initialize_with_readme=true"
       merge_requests_enabled: true
       headers:
         PRIVATE-TOKEN: "{{ my_token }}"
         name: "{{ myproject_name }}"
         namespace_id: "{{ mynamespace_id }}"
       method: POST
       validate_certs: false
       group: mygroup
       status_code: 201
```
