### ISSUE TITLE
VMware: When using vmware_vswitch, allow removing NICs

### ISSUE THREAD

**Issue by dandunckelman** [ansible/ansible#44589]
##### SUMMARY

I can't remove a NIC when configuring a vswitch.  I can only add.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_vswitch

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel aa07da21a3) last updated 2018/08/23 11:28:31 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
```yaml
- name: Add host to a standard vSwitch
  delegate_to: localhost
  vmware_vswitch:
    hostname: '{{ ansible_nodename }}'
    mtu: '{{ vswitch.mtu }}'
    nics: '{{ vswitch.vmnics }}'
    password: '{{ esx_password }}'
    state: '{{ vswitch.state }}'
    switch: '{{ vswitch.name }}'
    username: '{{ esx_user }}'
    validate_certs: '{{ validate_certs }}'
```

1. Run the above where `vswitch.vmnics` is this:

        vswitch:
          vmnics:
            - vmnic0
            - vmnic1
            - vmnic2
1. Run it again, but remove one of the nics to look like this:

        vswitch:
          vmnics:
            - vmnic0
            - vmnic2
1. You'll see success / no change.

##### EXPECTED RESULTS

I'd expect `vmnic1` to be removed from the switch.

##### ACTUAL RESULTS

Nothing changes.  This is because [the vmware_vswitch module](https://github.com/ansible/ansible/blob/e6f0f8073df923ca879e62a9e38a9599638f512c/lib/ansible/modules/cloud/vmware/vmware_vswitch.py#L288) only adds NICs that aren't already on the switch.  It doesn't remove a NIC from the switch.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_vswitch.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vswitch.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @dandunckelman,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@dandunckelman Thanks for reporting this feature request.

**Comment by ckotte** [comment]
I'm working on it. Will create a PR soon.

**Comment by ckotte** [comment]
@dandunckelman Could you check this PR: https://github.com/ansible/ansible/pull/47015?

needs_info
resolved_by_pr #47015

**Comment by Akasurde** [comment]
@dandunckelman Could you please check if above mentioned PR works for you and let us know so that we can merge this PR ?

Thanks

**Comment by dandunckelman** [comment]
@ckotte @Akasurde Thanks.

I'll test it this week (hopefully tomorrow).

**Comment by ansibot** [comment]
cc @lparkes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Tomorrow9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @goneri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pgbidkar
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dandunckelman** [comment]
@ckotte @Akasurde I'm sorry for never testing this!

Unfortunately, I won't be able to dedicate time to this. Hopefully, someone else can fillin for me.

**Comment by Deepak7b** [comment]
Redundancy adding a second NIC works!

**Comment by dandunckelman** [comment]
Hi @ckotte & @Akasurde I'm back to trying the [pull request](https://github.com/ansible/ansible/pull/47015).

Hooray! 🎊 🍰 It did work for me when removing a vmnic from a vswitch. Thank you! 🙏 

However, when I use the pull request for my other tasks, I get this error:

```
The full traceback is:                                                                 
  File "/tmp/ansible_vmware_dns_config_payload_y8zuqz_4/__main__.py", line 111, in main
    host_system = host.keys()[0]                                                       
                                                                                       
fatal: [esx-hostname -> localhost]: FAILED! => {                                 
    "changed": false,                                                                  
    "invocation": {                                                                    
        "module_args": {                                                               
            "change_hostname_to": "esx-hostname",                                
            "dns_servers": [                                                           
                "8.8.8.8",                                                          
                "8.8.4.4"                                                           
            ],                                                                         
            "domainname": "domain.local",                                                  
            "hostname": "esx-hostname",                                          
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",                         
            "port": 443,                                                               
            "username": "root",                                                        
            "validate_certs": false                                                    
        }                                                                              
    },                                                                                 
    "msg": "'dict_keys' object does not support indexing"                              
}                                                                                      
```

This is happening on this task:

```
- name: Configure ESXi hostname and DNS servers
  delegate_to: localhost
  vmware_dns_config:
    change_hostname_to: '{{ ansible_hostname }}'
    domainname: '{{ domain_name }}'
    dns_servers:
      - '{{ dns.primary }}'
      - '{{ dns.secondary }}'
    hostname: '{{ ansible_hostname }}'
    password: '{{ esx_password }}'
    username: '{{ esx_user }}'
    validate_certs: false
```

I found that this was fixed here: https://github.com/ansible/ansible/commit/cf2f13e05d1248debc278d4a687bc72898365968#diff-edb13760c39202a68db0bf74db789965

So, I think the pull request would just need a rebase.

Thanks again!
