### ISSUE TITLE
role vars unexpected behaviour

### ISSUE THREAD

**Issue by jonatcorus** [ansible/ansible#44603]
##### SUMMARY
When passing vars to roles using the vars: key and multiple roles use the same key name the last value wins.

This might be the intended behaviour but it tripped me up.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
2.6.3
```

##### CONFIGURATION
ANSIBLE_NOCOWS($HOME/ansible/roles/dependencies/lab1/ansible.cfg) = True

##### OS / ENVIRONMENT
ubuntu 16.04

##### STEPS TO REPRODUCE
play.yaml
```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: a
      var1: playrolea
      vars:
        var2: playrolea
      tags: ['a']
    - role: b
      var1: playroleb
      vars:
        var2: playroleb
      tags: ['b']
```

roles/a/meta/main.yaml
```yaml
---
dependencies:
  - role: common
    var3: metarolea
    tags: ['common']
```

roles/b/meta/main.yaml
```yaml
---
dependencies:
  - role: common
    var3: metaroleb
    tags: ['common']
```

roles/common/tasks/main.yaml
```yaml
- debug:
    msg: "{{var1}} {{var2}} {{var3}}"
```

##### EXPECTED RESULTS
"msg": "playrolea playrolea metarolea"

##### ACTUAL RESULTS
"msg": "playrolea playroleb metarolea"

```

```
$ ansible-playbook play2.yaml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [localhost] ******************************************************************************************************

TASK [common : debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "playrolea playroleb metarolea"
}

TASK [common : debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "playroleb playroleb metaroleb"
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
