### ISSUE TITLE
vmware_guest_snapshot:Unable to manage snapshots for non-existing VM

### ISSUE THREAD

**Issue by shinux85** [ansible/ansible#44606]
##### SUMMARY
unable to take vmsnaphot using vmware_guest_snapshot module.Always getting error-Unable to manage snapshots for non-existing VM"

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest_snapshot

##### ANSIBLE VERSION
```
[isopsxa@atwr01 RHEL_Patching]$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/isopsxa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
[isopsxa@atwr01 RHEL_Patching]$
```

##### CONFIGURATION
```
[isopsxa@atwr01 RHEL_Patching]$ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
[isopsxa@atwr01 RHEL_Patching]$
```

##### OS / ENVIRONMENT
Control Node:
```
[isopsxa@atwr01 RHEL_Patching]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[isopsxa@atwr01 RHEL_Patching]$ uname -a
Linux atwr01 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
[isopsxa@atwr01 RHEL_Patching]$
```
Managed Node:
VmWare Vcenter Server 6.0.0

##### STEPS TO REPRODUCE

```
[isopsxa@atwr01 RHEL_Patching]$ cat vmsnapshot.yml
---
- name: To Take VM Snapshot
  hosts: localhost
  gather_facts: no
  become: yes
  roles:
  - role: vmsnapshot

[isopsxa@atwr01 RHEL_Patching]$ cat roles/vmsnapshot/
defaults/  files/     handlers/  meta/      tasks/     templates/ vars/
[isopsxa@atwr01 RHEL_Patching]$ cat roles/vmsnapshot/tasks/main.yml
---
- name: Take snapshot
  vmware_guest_snapshot:
    datacenter: M1-MOC-DC
    hostname: mocvcms11.m1.local
    username: administrator@vsphere.local
    validate_certs: false
    password: " {{ ventre_pass }} "
    folder: /Testing
    name: psgrs01
    state: present
    snapshot_name: Test
    quiesce: True
    memory_dump: True
  delegate_to: localhost

[isopsxa@atwr01 RHEL_Patching]$

```

##### EXPECTED RESULTS
should be able to take vm snapshot

##### ACTUAL RESULTS

```
[isopsxa@atwr01 RHEL_Patching]$ ansible-playbook -vvvv vmsnapshot.yml
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/isopsxa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: vmsnapshot.yml ******************************************************************************************************************************************************************************************************************************************************
1 plays in vmsnapshot.yml

PLAY [To Take VM Snapshot] ****************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [vmsnapshot : Take snapshot] *********************************************************************************************************************************************************************************************************************************************
task path: /home/isopsxa/SHINU/RHEL_Patching/roles/vmsnapshot/tasks/main.yml:2
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: isopsxa
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628 `" && echo ansible-tmp-1535073676.98-194238015864628="` echo /home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628 `" ) && sleep 0'
<localhost> PUT /tmp/tmpyhk7Dh TO /home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628/vmware_guest_snapshot.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628/ /home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628/vmware_guest_snapshot.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hzpmnciflvmpnslnyaowgantfjuzvwlz; /usr/bin/python2 /home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628/vmware_guest_snapshot.py; rm -rf "/home/isopsxa/.ansible/tmp/ansible-tmp-1535073676.98-194238015864628/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "M1-MOC-DC",
            "description": "",
            "folder": "/Testing",
            "hostname": "mocvcms11.m1.local",
            "memory_dump": true,
            "name": "psgrs01",
            "name_match": "first",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "quiesce": true,
            "remove_children": false,
            "snapshot_name": "Test",
            "state": "present",
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false
        }
    },
    "msg": "Unable to manage snapshots for non-existing VM psgrs01"
}
        to retry, use: --limit @/home/isopsxa/SHINU/RHEL_Patching/vmsnapshot.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

[isopsxa@atwr01 RHEL_Patching]$ 
```
