### ISSUE TITLE
azure_rm_virtualmachine module - no storage account

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#44620]
##### SUMMARY
azure_rm_virtualmachine module always creates a storage account. When creating a VM manually it is possible to chose "Use managed disks" which does not create a storage account. This should also be supported in this module.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nbm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No env variables

##### OS / ENVIRONMENT
Ubuntu 16.04 and Centos 7.4

##### STEPS TO REPRODUCE

```yaml
- name: Create PCA MASTER
  azure_rm_virtualmachine:
    subscription_id: '{{ az_customer_subscription_id }}'
    resource_group: '{{ customer_prefix}}-pca-master'
    name: '{{ customer_prefix}}-pca-master'
    short_hostname: '{{ customer_prefix}}'
    ad_user: '{{ ad_user_login_var }}'
    password: '{{ ad_password_var }}'
    os_type: Linux
    vm_size: Standard_DS11_v2
    admin_username: awx-user
    virtual_network_name: "{{aio_vnet}}"
    subnet_name: '{{pca_subnet}}'
    ssh_password_enabled: false
    ssh_public_keys:
    - path: /home/awx-user/.ssh/authorized_keys
      key_data: '{{ key_data }}'
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.3'
      version: latest
```

##### EXPECTED RESULTS
There is no option to just choose managed disks without storage account.
