### ISSUE TITLE
j2 parsing with map filter

### ISSUE THREAD

**Issue by gudron** [ansible/ansible#44633]
##### SUMMARY
value of variable not parsed if contains map | list filter

##### ISSUE TYPE
 - Bug Report

##### component name
map and list filters

##### ANSIBLE VERSION
ansible 2.5.5
  config file = /tmp/ansible_test/ansible.cfg
  configured module search path = [u'/home/gudron/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

##### CONFIGURATION
ANSIBLE_PIPELINING(/tmp/ansible_test/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/tmp/ansible_test/ansible.cfg) = -F ssh.cfg
DEFAULT_HOST_LIST(/tmp/ansible_test/ansible.cfg) = [u'/tmp/ansible_test/inventories']
DEFAULT_LOG_PATH(/tmp/ansible_test/ansible.cfg) = /tmp/ansible_test/logfile
DEFAULT_ROLES_PATH(/tmp/ansible_test/ansible.cfg) = [u'/tmp/ansible_test/roles']
DEFAULT_VAULT_PASSWORD_FILE(/tmp/ansible_test/ansible.cfg) = /tmp/ansible_test/password
HOST_KEY_CHECKING(/tmp/ansible_test/ansible.cfg) = False

##### OS / ENVIRONMENT
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

localhost

##### STEPS TO REPRODUCE
Create yaml file in group_vars dir
```yaml
provider:
  internals_hosts: "{{ groups['group_name'] | intersect( groups['internals'] ) }}"

tmp:
  internal_ip_addrs: "{{ provider.internals_hosts | map('extract', hostvars, 'ansible_default_ipv4')|list }}"
```

Create playbook with
``` yaml
- hosts:
    - provider_name:&bastions
  become: yes
  gather_facts: yes
  strategy: free
  tasks:
  - debug: msg="{{ hostvars[inventory_hostname].tmp.internal_ip_addrs }}"
```
##### EXPECTED RESULTS
TASK [debug] ****************************************************************************************
task path: /home/gudron/projects/personal/gdrn_cloud/main/playbook.yaml:23
ok: [hostname] => {
    "msg": [
        "10.16.17.145", 
        "10.16.162.139", 
        "10.16.61.3"
    ]
}

##### ACTUAL RESULTS
TASK [debug] ****************************************************************************************
task path: /home/gudron/projects/personal/gdrn_cloud/main/playbook.yaml:23
ok: [hostname] => {
    "msg": "{{ provider.internals_hosts | map('extract', hostvars, 'ansible_default_ipv4')|list }}"
}

**Comment by ansibot** [comment]
@gudron Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I am able to reproduce this with `devel`, though I'm not sure if it's by design or not. 

A few things:

1) Is there a reason for using `hostvars[inventory_hostname]`? That is only necessary if you're looking up variables from other hosts.

2) An additional `map()` filter is needed to get the desired result.

This works:

```yaml
# group_vars/all.yml
provider:
  internal_hosts: "{{ groups['lab'] | intersect(groups['group1']) }}"

tmp:
  internal_ip_addrs: "{{ provider.internal_hosts | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
```

```yaml
# playbook
- hosts: "{{ target_hosts | default('lab-centos6,lab-centos7') }}"

  tasks:
    - debug:
        msg: "{{ tmp.internal_ip_addrs }}"
```

```
> ansible-playbook test.yml

PLAY [lab-centos6,lab-centos7] **********************************************************************

TASK [Gathering Facts] ******************************************************************************
ok: [lab-centos6]
ok: [lab-centos7]

TASK [debug] ****************************************************************************************
ok: [lab-centos6] => {}

MSG:

['10.11.0.108', '10.0.2.15']

ok: [lab-centos7] => {}

MSG:

['10.11.0.108', '10.0.2.15']


PLAY RECAP ******************************************************************************************
lab-centos6                : ok=2    changed=0    unreachable=0    failed=0
lab-centos7                : ok=2    changed=0    unreachable=0    failed=0
```

Using `hostvars` does not work:

```yaml
# playbook
- hosts: "{{ target_hosts | default('lab-centos6,lab-centos7') }}"

  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname].tmp.internal_ip_addrs }}"
```

```
> ansible-playbook test.yml

PLAY [lab-centos6,lab-centos7] **********************************************************************

TASK [Gathering Facts] ******************************************************************************
ok: [lab-centos7]
ok: [lab-centos6]

TASK [debug] ****************************************************************************************
ok: [lab-centos6] => {}

MSG:

{{ provider.internal_hosts | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}

ok: [lab-centos7] => {}

MSG:

{{ provider.internal_hosts | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}


PLAY RECAP ******************************************************************************************
lab-centos6                : ok=2    changed=0    unreachable=0    failed=0
lab-centos7                : ok=2    changed=0    unreachable=0    failed=0
```
