### ISSUE TITLE
Module: vmware_cluster sets various default configurations that are not changeable via Ansible. 

### ISSUE THREAD

**Issue by mfish82** [ansible/ansible#44662]
##### SUMMARY

The vmware_cluster module allows you to set a bool for DRS, HA, and VSAN. Even with these values, false, it appears that the module sets some values in the background. This was discovered via vmware_cluster_facts.  For this request, we're specifically looking at the HA settings. Some of these settings, in some infrastructures, may cause issues. Being able to set these values at creation will avoid the need for manual intervention after configuring via Ansible.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

vmware_cluster

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/home/mfisher30/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

no changes

##### OS / ENVIRONMENT

vCenter 6.5
RHEL 7.4

##### STEPS TO REPRODUCE

The thought process for our deployments is to leave HA off, add hosts and other configuration items, then enable HA later after the cluster is HA ready. 

```yaml

  - name: Create Cluster in vCenter
    vmware_cluster:
      hostname: '{{ vCenter }}'
      username: '{{ vCenter_user }}'
      password: '{{ vCenter_pass }}'
      datacenter_name: '{{ datacenter }}'
      cluster_name: '{{ cluster }}'
      enable_ha: no
      enable_drs: no
      enable_vsan: no
      state: absent
      validate_certs: False
```

##### EXPECTED RESULTS

Results were expected, until we ran vmware_cluster_facts and saw that Ansible was setting HA values in the background. After looking at the vmware_cluster.py file, it was noticed that those values are hard coded. 

```python
    def configure_ha(self):
        das_config = vim.cluster.DasConfigInfo()
        das_config.enabled = self.enable_ha
        das_config.admissionControlPolicy = vim.cluster.FailoverLevelAdmissionControlPolicy()
        das_config.admissionControlPolicy.failoverLevel = 2
        return das_config

```

We would like to be able to set the following items via Ansible and not manually. 

```
"ha_admission_control_enabled": (default is true)
"ha_failover_level":  (default is 2)
"ha_vm_max_failure_window":  (default is [-1])
```
##### ACTUAL RESULTS

```
               "ha_admission_control_enabled": true,
               "ha_failover_level": 2,
               "ha_host_monitoring": "enabled",
               "ha_restart_priority": [
                   "medium"
               ],
               "ha_vm_failure_interval": [
                   30
               ],
               "ha_vm_max_failure_window": [
                   -1
               ],
               "ha_vm_max_failures": [
                   3
               ],
               "ha_vm_min_up_time": [
                   120
               ],
               "ha_vm_monitoring": "vmMonitoringDisabled",
               "ha_vm_tools_monitoring": [
                   "vmMonitoringDisabled"

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_cluster.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_cluster.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @mfisher30,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@mfisher30 Thanks for this feature request. Could you please check this PR https://github.com/ansible/ansible/pull/37072 and let me know if it works for you ?

**Comment by mfish82** [comment]
@Akasurde Thanks for the follow up! After digging through it, it definitely looks like it would take care of my original concerns, and then some! Sorry, I searched ahead of time and didn't see this first time around.

Do you happen to know when this will get pulled in? And will it be pulled in with a later version of 2.6 or with the 2.7 RC?

**Comment by Akasurde** [comment]
@mfisher30 We will try to merge this is 2.7 release cycle if you can add your testing report and feedback on the PR. Thanks.

**Comment by mfish82** [comment]
@Akasurde Absolutely. Would you like me to post my notes on this PR or the other one, #37072? I'm hoping we can start giving you some beta feedback next week.

**Comment by Akasurde** [comment]
@mfisher30 Yes. Your comments and feedback will definitely expedite the process.

**Comment by jomardimac** [comment]
@Akasurde I was testing this module out with @mfisher30 and it seems like there is a bug with actually configuring the settings. I changed the module_utils/vmware.py to be what it is in the PR and I also changed the /modules/cloud/vmware/vmware_cluster.py.

Here are my outputs: 

The output when I run the create cluster module with debug: 

```
changed: [VC] => {
    "changed": true,
    "invocation": {
		"module_args": {
			"cluster_name": "cluster1",
			"datacenter": "dc1",
			"datacenter_name": "dc1",
			"drs_default_vm_behavior": "fullyAutomated",
			"drs_enable_vm_behavior_overrides": true,
			"drs_vmotion_rate": 3,
			"enable_drs": true,
			"enable_ha": true,
			"enable_vsan": false,
			"ha_admission_control_enabled": false,
			"ha_failover_level": 1,
			"ha_host_monitoring": "enabled",
			"ha_restart_priority": "medium",
			"ha_vm_failure_interval": 30,
			"ha_vm_max_failure_window": 3600,
			"ha_vm_max_failures": 3,
			"ha_vm_min_up_time": 120,
			"ha_vm_monitoring": "vmMonitoringDisabled",
			"hostname": "c5mblv01.t-mobile.lab",
			"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
			"port": 443,
			"state": "present",
			"username": "administrator@vsphere.local",
			"validate_certs": false,
			"vsan_auto_claim_storage": false
		}
    }
}
```
	
Yet, when I run the facts gathering module for clusters and got this:

```
ok: [VC] => {
    "cluster_facts": {
        "changed": false,
        "clusters": {
            "Ans_clust_test": {
                "drs_default_vm_behavior": "fullyAutomated",
                "drs_enable_vm_behavior_overrides": true,
                "drs_vmotion_rate": 3,
                "enable_ha": true,
                "enabled_drs": true,
                "enabled_vsan": false,
                "ha_admission_control_enabled": false,
                "ha_failover_level": 1,
                "ha_host_monitoring": "enabled",
                "ha_restart_priority": [
                    "medium"
                ],
                "ha_vm_failure_interval": [
                    30
                ],
                "ha_vm_max_failure_window": [
                    -1
                ],
                "ha_vm_max_failures": [
                    3
                ],
                "ha_vm_min_up_time": [
                    120
                ],
                "ha_vm_monitoring": "vmMonitoringDisabled",
                "ha_vm_tools_monitoring": [
                    "vmMonitoringDisabled"
                ],
                "vsan_auto_claim_storage": false
            }
        },
        "failed": false
    }
}
```

My playbook looks like this: 
```
- name: Create Empty VM Cluster
    vmware_cluster:
      hostname: '{{ vCenter }}'
      username: '{{ vCenter_user }}'
      password: '{{ vCenter_pass }}'
      datacenter_name: '{{ datacenter }}'
      cluster_name: '{{ cluster }}'
      drs_default_vm_behavior: fullyAutomated

      enable_ha: True
      enable_drs: True
      enable_vsan: no
      ha_admission_control_enabled: False
      ha_failover_level: 1
      ha_vm_failure_interval: 30
      ha_vm_max_failure_window: 3600
      ha_vm_max_failures: 3
      state: present
      validate_certs: False
```

**Comment by jomardimac** [comment]
@Akasurde I was testing this module out with @mfisher30 and it seems like there is a bug with actually configuring the settings. I changed the module_utils/vmware.py to be what it is in the PR and I also changed the /modules/cloud/vmware/vmware_cluster.py.

Here are my outputs: 

The output when I run the create cluster module with debug: 

```
changed: [VC] => {
    "changed": true,
    "invocation": {
		"module_args": {
			"cluster_name": "cluster1",
			"datacenter": "dc1",
			"datacenter_name": "dc1",
			"drs_default_vm_behavior": "fullyAutomated",
			"drs_enable_vm_behavior_overrides": true,
			"drs_vmotion_rate": 3,
			"enable_drs": true,
			"enable_ha": true,
			"enable_vsan": false,
			"ha_admission_control_enabled": false,
			"ha_failover_level": 1,
			"ha_host_monitoring": "enabled",
			"ha_restart_priority": "medium",
			"ha_vm_failure_interval": 30,
			"ha_vm_max_failure_window": 3600,
			"ha_vm_max_failures": 3,
			"ha_vm_min_up_time": 120,
			"ha_vm_monitoring": "vmMonitoringDisabled",
			"hostname": "x",
			"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
			"port": 443,
			"state": "present",
			"username": "administrator@vsphere.local",
			"validate_certs": false,
			"vsan_auto_claim_storage": false
		}
    }
}
```
	
Yet, when I run the facts gathering module for clusters and got this:

```
ok: [VC] => {
    "cluster_facts": {
        "changed": false,
        "clusters": {
            "Ans_clust_test": {
                "drs_default_vm_behavior": "fullyAutomated",
                "drs_enable_vm_behavior_overrides": true,
                "drs_vmotion_rate": 3,
                "enable_ha": true,
                "enabled_drs": true,
                "enabled_vsan": false,
                "ha_admission_control_enabled": false,
                "ha_failover_level": 1,
                "ha_host_monitoring": "enabled",
                "ha_restart_priority": [
                    "medium"
                ],
                "ha_vm_failure_interval": [
                    30
                ],
                "ha_vm_max_failure_window": [
                    -1
                ],
                "ha_vm_max_failures": [
                    3
                ],
                "ha_vm_min_up_time": [
                    120
                ],
                "ha_vm_monitoring": "vmMonitoringDisabled",
                "ha_vm_tools_monitoring": [
                    "vmMonitoringDisabled"
                ],
                "vsan_auto_claim_storage": false
            }
        },
        "failed": false
    }
}
```

My playbook looks like this: 
```
- name: Create Empty VM Cluster
    vmware_cluster:
      hostname: '{{ vCenter }}'
      username: '{{ vCenter_user }}'
      password: '{{ vCenter_pass }}'
      datacenter_name: '{{ datacenter }}'
      cluster_name: '{{ cluster }}'
      drs_default_vm_behavior: fullyAutomated

      enable_ha: True
      enable_drs: True
      enable_vsan: no
      ha_admission_control_enabled: False
      ha_failover_level: 1
      ha_vm_failure_interval: 30
      ha_vm_max_failure_window: 3600
      ha_vm_max_failures: 3
      state: present
      validate_certs: False
```

**Comment by jomardimac** [comment]
@Akasurde I was testing this module out with @mfisher30 and it seems like there is a bug with actually keeping the configurations in the settings. I changed the module_utils/vmware.py and I also changed the /modules/cloud/vmware/vmware_cluster.py to be what it is in the PR.

Here are my outputs: 

The output when I run the create cluster module with debug: 

```
changed: [VC] => {
    "changed": true,
    "invocation": {
	module_args": {
		"cluster_name": "cluster1",
		"datacenter": "dc1",
		"datacenter_name": "dc1",
		"drs_default_vm_behavior": "fullyAutomated",
		"drs_enable_vm_behavior_overrides": true,
		"drs_vmotion_rate": 3,
		"enable_drs": true,
		"enable_ha": true,
		"enable_vsan": false,
		"ha_admission_control_enabled": false,
		"ha_failover_level": 1,
		"ha_host_monitoring": "enabled",
		"ha_restart_priority": "medium",
		"ha_vm_failure_interval": 30,
		"ha_vm_max_failure_window": 3600,
		"ha_vm_max_failures": 3,
		"ha_vm_min_up_time": 120,
		"ha_vm_monitoring": "vmMonitoringDisabled",
		"hostname": "valid_hostname",
		"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
		"port": 443,
		"state": "present",
		"username": "valid_username",
		"validate_certs": false,
		"vsan_auto_claim_storage": false
	}
    }
}
```
	
Yet, when I run the facts gathering module for clusters and got this:

```
ok: [VC] => {
    "cluster_facts": {
        "changed": false,
        "clusters": {
            "cluster1": {
                "drs_default_vm_behavior": "fullyAutomated",
                "drs_enable_vm_behavior_overrides": true,
                "drs_vmotion_rate": 3,
                "enable_ha": true,
                "enabled_drs": true,
                "enabled_vsan": false,
                **"ha_admission_control_enabled": false,**
                **"ha_failover_level": 1,**
                "ha_host_monitoring": "enabled",
                "ha_restart_priority": [
                    "medium"
                ],
                "ha_vm_failure_interval": [
                    30
                ],
                "ha_vm_max_failure_window": [
                    **-1**
                ],
                "ha_vm_max_failures": [
                    3
                ],
                "ha_vm_min_up_time": [
                    120
                ],
                "ha_vm_monitoring": "vmMonitoringDisabled",
                "ha_vm_tools_monitoring": [
                    "vmMonitoringDisabled"
                ],
                "vsan_auto_claim_storage": false
            }
        },
        "failed": false
    }
}
```

My playbook looks like this: 
```
- name: Create Empty VM Cluster
    vmware_cluster:
      hostname: '{{ vCenter }}'
      username: '{{ vCenter_user }}'
      password: '{{ vCenter_pass }}'
      datacenter_name: '{{ datacenter }}'
      cluster_name: '{{ cluster }}'
      drs_default_vm_behavior: fullyAutomated

      enable_ha: True
      enable_drs: True
      enable_vsan: no
      ha_admission_control_enabled: False
      ha_failover_level: 1
      ha_vm_failure_interval: 30
      ha_vm_max_failure_window: 3600
      ha_vm_max_failures: 3
      state: present
      validate_certs: False
```

Update: It successfully updated 2/3 of the changes that we needed. It might be a VMware side option that we need enabled in order to change the ha_vm_max_failure_window section.
