### ISSUE TITLE
add the possibility to add a context via sefcontext module

### ISSUE THREAD

**Issue by flatterlight** [ansible/ansible#44684]
##### SUMMARY

In the current form it is not possible to add a setype to a file/directory.
##### ISSUE TYPE
 - Feature Idea
add an option to add the in "setype" given context to the target
##### COMPONENT NAME

sefcontext
##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

no changes
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
- name: tag directory with selinux contexts
  become: yes
  sefcontext:
   target: '{{ item.target }}(/.*)?'
   setype: "{{ item.setype }}"
   reload: yes
   state: present
  register: filecontext
  with_items:
  - { target: '/mnt/dir1/logs', setype: 'httpd_sys_content_t' }
  - { target: '/mnt/dir1/logs', setype: 'httpd_sys_rw_content_t' }
```

##### EXPECTED RESULTS

set both contexts
##### ACTUAL RESULTS

just the last context was set

```

```
