### ISSUE TITLE
Allow evaluation of variables from the contents of other variables

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#44687]
##### SUMMARY
I am looking for sth like `eval()`.

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel 24a379f0b7) last updated 2018/08/25 10:39:54 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### OS / ENVIRONMENT

Arch linux latest 

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost                   
  vars:                              
    t: r                            
    r: 2                            
  tasks:                            
    - debug:                          
        msg: qqq                      
      when: "{{ t }}" == 2
```

##### EXPECTED RESULTS

I would like to see the task succeed.

##### ACTUAL RESULTS

The conditional fails complaining about quotes.

```
ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to have been in '/home/nikos/Projects/ansible-demo/play1.yml': line 13, column 21, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      msg: qqq
    when: "{{ t }}" is undefined
                    ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

```

Another example where I needed this functionality was in order to make some tasks really compact. For instance:

```yaml
- set_fact:
    "{{ item }}": "{{ eval('__' + item) }}"
  when: item is not defined
  loop: "{{ huge_list }}"
```

This would need many separate tasks in the form of:

```yaml
- set_fact:
    var1: "{{ var1 }}"
  when: var1 is not defined
```
