### ISSUE TITLE
ini_file module backup pattern breaks on vfat filesystem(s)

### ISSUE THREAD

**Issue by FredrikWendt** [ansible/ansible#44689]
##### SUMMARY
When using the `ini_file` module on a file on a vfat filesystem, with `backup=true`, ansible fails (fatal) with msg: `"Could not make backup of path_to_ini_file_that_is_changed to backup_file_path: [Errno 22]: invalid mode ('rb') or filename: backup_file_path"`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ini_file

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]
```

##### CONFIGURATION
none:
```
root@touch-pi:/home/ceda/gitlab/infrastructure# ansible-config dump --only-changed
root@touch-pi:/home/ceda/gitlab/infrastructure# 
```

##### OS / ENVIRONMENT
Raspbian, based on Debian 8.0, on a Raspberry Pi 3B.
Output from `mount` command, showing how the filesystem is mounted:
```
/dev/mmcblk0p1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
```

##### STEPS TO REPRODUCE

```
ANSIBLE_PLAYBOOK_FILE=/tmp/touchpi-play.yml
cat > $ANSIBLE_PLAYBOOK_FILE <<EOF
```

```yaml
---
- hosts: all
  become: True
  tasks:

    - name: Install supervisord
      apt:
        name: supervisor
        state: latest

    - name: Configuring amount of available GPU memory
      ini_file:
        path: /boot/config.txt
        section: null
        option: gpu_mem
        value: 32
        backup: yes

    - name: Configuring rotation of LCD screen
      ini_file:
        path: /boot/config.txt
        section: null
        option: lcd_rotate
        value: 2
        backup: yes
EOF
```
`ansible-playbook -i localhost, -c local $ANSIBLE_PLAYBOOK_FILE`

##### EXPECTED RESULTS
The Ini file is updated.

##### ACTUAL RESULTS
Backup of ini file failed, no change to the file.

```
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Install supervisord] *****************************************************
changed: [localhost]

TASK [Configuring amount of available GPU memory] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not make backup of /boot/config.txt to /boot/config.txt.28147.2018-08-26@08:36:35~: [Errno 22] invalid mode ('wb') or filename: '/boot/config.txt.28147.2018-08-26@08:36:35~'"}
	to retry, use: --limit @/tmp/touchpi-play.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/ini_file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/ini_file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @noseka1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by giovannisciortino** [comment]
I reproduced the problem also on the latest ansible devel branch.

The problem is caused by the characters ":" in the backup file time format because the character ":" is invalid in vfat filesystem ( https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file ). 

Also other module supporting backup parameter should be affected by this problem ( replace module is affected)

Based on my knowledge of ansible, the backup file format is [hard coded](https://github.com/ansible/ansible/blob/5c9241fa7c60f3aa731368971d4e0a481bbf63d6/lib/ansible/module_utils/basic.py#L2437).

**Comment by neuroticnerd** [comment]
Still running into this problem on newer releases. I have included information below about my specific use, but the problem extends to any module with the backup option when operating on a FAT32 or VFAT filesystem; I would guess that these are not the only filesystems where the backup file pattern contains invalid characters.

Host
```
macOS Mojave version: 10.14.6
ansible 2.9.9
python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```
Raspberry Pi 2B
```
Raspbian GNU/Linux 10 (buster)
Kernel: 4.19.118-v7+

$ sudo lsblk -o NAME,TYPE,SIZE,MOUNTPOINT,PARTLABEL,FSTYPE,LABEL
NAME        TYPE  SIZE MOUNTPOINT PARTLABEL FSTYPE LABEL
mmcblk0     disk  7.4G                             
├─mmcblk0p1 part  256M /boot                vfat   boot
└─mmcblk0p2 part  7.2G /                    ext4   rootfs
```

For managing things like Raspberry Pi OS devices which place the /boot directory on a VFAT partition it seems I can either forego the backup, or work around it by manually creating a backup using something like:
```
- name: "Backup /boot/cmdline.txt"
  become: yes
  become_user: root
  copy:
    src: /boot/cmdline.txt
    remote_src: yes
    dest: '/home/{{ ansible_user }}/cmdline.txt'
    owner: "{{ ansible_user }}"
    mode: 0644
  changed_when: false
```
