### ISSUE TITLE
vmware_dvs_portgroup - Modify Uplink LAG

### ISSUE THREAD

**Issue by vmjordan** [ansible/ansible#44704]
##### SUMMARY

Requesting to add a variable in that allows the user to specify what Uplink LAG you want the the DVS portgroup in. Currently it sets it to the first one in your list but if you have multiple you have to go in and manually go in and change it 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

vmware_dvs_portgroup

##### ANSIBLE VERSION

```
2.6
```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

RHEL 7.4
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_dvs_portgroup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_dvs_portgroup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @vmjordan,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ckotte** [comment]
@vmjordan Do you mean the failover order? Something like this?

```
- name: Add Portgroup
  vmware_dvs_portgroup:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    switch: dvSwitch
    portgroup_name: Test
    teaming:
        load_balancing: failover_explicit
        network_failure_detection: link_status_only
        notify_switches: true
        failback: true
        failover_order:
            active_nics:
                - lag1
  delegate_to: localhost
```
