### ISSUE TITLE
Cannot add several for a role with na_ontap_user_role

### ISSUE THREAD

**Issue by laurent-perrin** [ansible/ansible#44710]
##### SUMMARY
When using the `na_ontap_user_role` to create role, it's not possible to add several command to one role.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

na_ontap_user

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/fgzx6022/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fgzx6022/Work/python-env/ansible2.6/local/lib/python2.7/site-packages/ansible
  executable location = /home/fgzx6022/Work/python-env/ansible2.6/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

OS: Ubuntu 18.04
Netapp: AFF200 with cdot 9.3

##### STEPS TO REPRODUCE

Run the playbook

```yaml
- name: create netapp-harvest role
  na_ontap_user_role:
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    hostname: "{{ inventory_hostname }}"
    vserver: "{{ cluster_svm_name }}"
    name: netapp-harvest-role
    command_directory_name: "version"
    access_level: readonly
    state: present
  tags: netapp-harvest,netapp-harvest-role

- name: create netapp-harvest role
  na_ontap_user_role:
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    hostname: "{{ inventory_hostname }}"
    vserver: "{{ cluster_svm_name }}"
    name: netapp-harvest-role
    command_directory_name: "cluster show"
    access_level: readonly
    state: present
  tags: netapp-harvest,netapp-harvest-role
```

##### EXPECTED RESULTS

It should be possible to add several command to one role.

##### ACTUAL RESULTS

```
TASK [netapp-harvest : create netapp-harvest role] ****************************************************************************************************************************************************************
task path: /home/fgzx6022/Work/ansible-netapp/roles/netapp-harvest/tasks/main.yml:1
<cloud-nas-y00n-prd.cloud.620nm.net> ESTABLISH LOCAL CONNECTION FOR USER: fgzx6022
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c 'echo ~fgzx6022 && sleep 0'
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276 `" && echo ansible-tmp-1535362394.52-21167383070276="` echo /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276 `" ) && sleep 0'
Using module file /home/fgzx6022/Work/python-env/ansible2.6/local/lib/python2.7/site-packages/ansible/modules/storage/netapp/na_ontap_user_role.py
<cloud-nas-y00n-prd.cloud.620nm.net> PUT /home/fgzx6022/.ansible/tmp/ansible-local-3296usaqdW/tmpaQ7WL3 TO /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276/na_ontap_user_role.py
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c 'chmod u+x /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276/ /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276/na_ontap_user_role.py && sleep 0'
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c '/home/fgzx6022/Work/python-env/ansible2.6/bin/python /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276/na_ontap_user_role.py && sleep 0'
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c 'rm -f -r /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362394.52-21167383070276/ > /dev/null 2>&1 && sleep 0'
ok: [cloud-nas-y00n-prd.cloud.620nm.net] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "access_level": "readonly", 
            "command_directory_name": "version", 
            "hostname": "cloud-nas-y00n-prd.cloud.620nm.net", 
            "https": false, 
            "name": "netapp-harvest-role", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "username": "ansible", 
            "vserver": "cloud-nas-y00n-prd"
        }
    }
}

TASK [netapp-harvest : create netapp-harvest role] ****************************************************************************************************************************************************************
task path: /home/fgzx6022/Work/ansible-netapp/roles/netapp-harvest/tasks/main.yml:13
<cloud-nas-y00n-prd.cloud.620nm.net> ESTABLISH LOCAL CONNECTION FOR USER: fgzx6022
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c 'echo ~fgzx6022 && sleep 0'
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886 `" && echo ansible-tmp-1535362395.76-208968869931886="` echo /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886 `" ) && sleep 0'
Using module file /home/fgzx6022/Work/python-env/ansible2.6/local/lib/python2.7/site-packages/ansible/modules/storage/netapp/na_ontap_user_role.py
<cloud-nas-y00n-prd.cloud.620nm.net> PUT /home/fgzx6022/.ansible/tmp/ansible-local-3296usaqdW/tmpdIE2Y5 TO /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886/na_ontap_user_role.py
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c 'chmod u+x /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886/ /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886/na_ontap_user_role.py && sleep 0'
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c '/home/fgzx6022/Work/python-env/ansible2.6/bin/python /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886/na_ontap_user_role.py && sleep 0'
<cloud-nas-y00n-prd.cloud.620nm.net> EXEC /bin/sh -c 'rm -f -r /home/fgzx6022/.ansible/tmp/ansible-tmp-1535362395.76-208968869931886/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_jXn7J9/ansible_module_na_ontap_user_role.py", line 140, in get_role
    security_login_role_get_iter, enable_tunneling=False)
  File "/home/fgzx6022/Work/python-env/ansible2.6/local/lib/python2.7/site-packages/netapp_lib/api/zapi/zapi.py", line 294, in invoke_successfully
    raise NaApiError(code, msg)
NaApiError: NetApp API failed. Reason - 16039:Command directory not found

fatal: [cloud-nas-y00n-prd.cloud.620nm.net]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "access_level": "readonly", 
            "command_directory_name": "cluster show", 
            "hostname": "cloud-nas-y00n-prd.cloud.620nm.net", 
            "https": false, 
            "name": "netapp-harvest-role", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "username": "ansible", 
            "vserver": "cloud-nas-y00n-prd"
        }
    }, 
    "msg": "Error getting role netapp-harvest-role: NetApp API failed. Reason - 16039:Command directory not found"
}
	to retry, use: --limit @/home/fgzx6022/Work/ansible-netapp/config.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
cloud-nas-y00n-prd.cloud.620nm.net : ok=4    changed=1    unreachable=0    failed=1   
```
