### ISSUE TITLE
asa_config pushes config when config already exists

### ISSUE THREAD

**Issue by jvanderaa** [ansible/ansible#44731]
##### SUMMARY
When setting up asa_config with the parents of `DNS server-group DefaultDNS` (or any other server group), Ansible will still attempt to deploy the configuration, even though it is already configured.
```ansible
parents: ['DNS server-group DefaultDNS']
```

```
TASK [ASA>> Set DNS Servers on context firewalls] **********************************************************************************************************************************************************************
fatal: [fw08-1]: FAILED! => {"changed": false, "msg": "name-server 8.8.8.8\r\nERROR: DNS Duplicate server address 8.8.8.8\r\n\rfw08-1/admin/act(config-dns-server-group)# "
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

asa_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.6.2
  config file = /Users/jvanderaa/Documents/Ansible/ansible.cfg
  configured module search path = [u'/Users/jvanderaa/Documents/Ansible/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

MacOS, ASA 9.1

##### STEPS TO REPRODUCE

```yaml
---
- name: Verify DNS setup
  hosts: fw08-1
  connection: network_cli
  become: yes
  become_method: enable
  gather_facts: no

  tasks:
    - name: ASA>> Set DNS Servers on context firewalls
      asa_config:
        lines:
          - name-server 8.8.8.8
        parents: ['DNS server-group DefaultDNS']
        context: admin
        save: yes
```

##### EXPECTED RESULTS

Expect that the module would skip over the task as it is already configured.

##### ACTUAL RESULTS

```
The full traceback is:
  File "/var/folders/dq/_tjy3jfn0j98n6j590nyr24jpxb_7r/T/ansible_Jxnlor/ansible_modlib.zip/ansible/module_utils/network/asa/asa.py", line 154, in load_config
    conn.edit_config(config)
  File "/var/folders/dq/_tjy3jfn0j98n6j590nyr24jpxb_7r/T/ansible_Jxnlor/ansible_modlib.zip/ansible/module_utils/connection.py", line 149, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

fatal: [fw08-1]: FAILED! => {
    "changed": false,Ï
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "config": null,
            "context": "admin",
            "defaults": false,
            "host": null,
            "lines": [
                "name-server 8.8.8.8"
            ],
            "match": "line",
            "parents": [
                "DNS server-group DefaultDNS"
            ],
            "password": null,
            "passwords": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "save": true,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "name-server 8.8.8.8\r\nERROR: DNS Duplicate server address 8.8.8.8\r\n\rfw08-1/admin/act(config-dns-server-group)# "
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/asa/asa_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/asa/asa_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ogenstad @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @jvanderaa,

Thank you for the issue, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in #ansible-network on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gdpak** [comment]
@jvanderaa . config lines given in 'parent' option should exactly match (case-sensitive) the line present in running-config for ansible to identify diff with old configuration.
In running-config, dns server config appears as below 
```
dns server-group DefaultDNS
 name-server 8.8.8.8
```
so your parent argument should be - ['dns server-group DefaultDNS']
I tried below playbook and it works as expected
```
- hosts: asa01                                                                                                                                                                     
  tasks:                                                                                                                                                                           
    - name: config dns server                                                                                                                                                      
      asa_config:                                                                                                                                                                  
          lines:                                                                                                                                                                   
              - name-server 8.8.8.8                                                                                                                                                
          parents: ['dns server-group DefaultDNS']                                                                                                                                 
          save: yes                                                                                                                                                                
      register: result                
```

Please note here ansible would return 'change=True' even if you run it multiple times because of 'save: yes'.
save option would cause always writing running config to startup-config even if there was no change in running -config or there was no difference between running-config and startup-config.
