### ISSUE TITLE
file link not work

### ISSUE THREAD

**Issue by jasstionzyf** [ansible/ansible#44748]
##### SUMMARY

simply want to create a symbol link for a path

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

module name: file

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /Volumes/external1/data/projects/mywork/single-node-hadoop/ansible.cfg
  configured module search path = ['/Users/jasstion/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jasstion/anaconda/lib/python3.5/site-packages/ansible
  executable location = /Users/jasstion/anaconda/bin/ansible
  python version = 3.5.4 |Anaconda custom (x86_64)| (default, Aug 14 2017, 12:43:10) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

##### OS / ENVIRONMENT

os: Ubuntu 14.04.5 LTS

##### STEPS TO REPRODUCE

```
 - name: create link jdk
    file:
      path: /opt/java
      src: /opt/jdk1.8.0_71
      state: link
      force: yes
      owner: root
      group: root

```

##### EXPECTED RESULTS

create symal link /opt/java for /opt/jdk1.8.0_71

##### ACTUAL RESULTS

```
error:
TASK [create link jdk] *********************************************************
fatal: [default]: FAILED! => {"changed": false, "msg": "Error while linking: [Errno 2] No such file or directory", "path": "/opt/java/", "state": "absent"}
```
