### ISSUE TITLE
Is it possible to have `until` with `loop`?

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#44741]
##### SUMMARY

I have a `get_url` task that downloads a list of files. Sometimes the server is busy and a download might fail. I would like to use `until` to retry the download.

##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel 79a020e312) last updated 2018/08/27 12:47:42 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### OS / ENVIRONMENT

Arch linux

##### STEPS TO REPRODUCE

I would imagine sth like this:

```yaml
- get_url:
    url: "{{ item }}"
    dest: 'dest'
  register: download
  until: download.results | map('success')
  loop: "{{ files }}"
```

But this obviously does not work.

**Comment by webknjaz** [comment]
> But this obviously does not work.

I've just tried this locally (just replaced files with real urls) and it works for me:
```yaml
---
- hosts: localhost
  tasks:
  - get_url:
      url: "{{ item }}"
      dest: .
    register: download
    until: download.results | map('success')
    delay: 3
    loop:
    - https://github.com/file/file/archive/FILE5_34.tar.gz
    - https://github.com/file/file/archive/FILE5_33.tar.gz
```


_Then_, I tried it disconnected from the Internet and got this:
```python-traceback
➜ ansible-playbook playbook.yml -vvv
...
The full traceback is:                                                                                                         
  File "/tmp/ansible_spcoeuub/ansible_modlib.zip/ansible/module_utils/urls.py", line 1055, in fetch_url
    client_key=client_key, cookies=cookies)
  File "/tmp/ansible_spcoeuub/ansible_modlib.zip/ansible/module_utils/urls.py", line 958, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/home/wk/.pyenv/versions/3.7.0/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/wk/.pyenv/versions/3.7.0/lib/python3.7/urllib/request.py", line 523, in open
    req = meth(req)
  File "/tmp/ansible_spcoeuub/ansible_modlib.zip/ansible/module_utils/urls.py", line 775, in http_request
    raise ConnectionError('Failed to connect to %s at port %s: %s' % (self.hostname, self.port, to_native(e)))

failed: [localhost] (item=https://github.com/file/file/archive/FILE5_34.tar.gz) => {
    "attempts": 1,                                                                                                             
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": ".",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://github.com/file/file/archive/FILE5_34.tar.gz",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "item": "https://github.com/file/file/archive/FILE5_34.tar.gz",
    "msg": "Failed to connect to github.com at port 443: [Errno -3] Temporary failure in name resolution"
}
...
```

**Comment by webknjaz** [comment]
I went further and narrowed it to this task, not using `loop`:
```yaml
---
- hosts: localhost
  tasks:
  - get_url:
      url: https://github.com/file/file/archive/FILE5_34.tar.gz
      dest: .
    register: download
    until: download.results | map('success')
    delay: 3
```

And it still fails like that. Suspecting bug in `get_url` module.

**Comment by webknjaz** [comment]
So I've finally realized that you try to access a list of results, but `until` works with every separate task run. This works:
```yaml
---
- hosts: localhost
  tasks:
  - get_url:
      url: https://github.com/file/file/archive/FILE5_34.tar.gz
      dest: .
    register: download
    until: download.results | map('success')
    delay: 3
```

Under each `loop`, the `until` is bound to the task within/inside that loop, not to the set of results after loop evaluation. This is what you're supposed to do:
```yaml
---
- hosts: localhost
  tasks:
  - get_url:
      url: "{{ item }}"
      dest: .
    register: download
    until: download is succeeded
    delay: 3
    loop:
    - https://github.com/file/file/archive/FILE5_34.tar.gz
    - https://github.com/file/file/archive/FILE5_33.tar.gz
```

It'll retry each of downloads separately.
