### ISSUE TITLE
Ansible is not publishing the docker_container ports if network_mode=host

### ISSUE THREAD

**Issue by atedja-em** [ansible/ansible#44742]
##### SUMMARY
Ansible (when executing using `ansible-playbook`) is not publishing the ports as specified when `network_mode: "host"`. Removing `network_mode: "host"` confirms the ports are mapped as expected.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### OS / ENVIRONMENT
Ubuntu 18.04 (docker container)

##### STEPS TO REPRODUCE

```yaml
hosts: sample_app
remote_user: "{{ remote_user }}"
become: true
vars_files:
  - vars
tasks:
  - name: "pulling image"
    docker_image:
      name: "{{ image_name }}"
      tag: "{{ revision }}"
  - name: "deploying new version"
    docker_container:
      name: "{{ app }}"
      image: "{{ image_name }}:{{ revision }}"
      state: "started"
      network_mode: "host"
      restart_policy: "always"
      published_ports:
        - "7777:7777"
```

##### EXPECTED RESULTS
Container ports should be mapped even when `network_mode: "host"` is specified.

##### ACTUAL RESULTS
```
CONTAINER ID        IMAGE                                                   COMMAND             CREATED             STATUS              PORTS               NAMES               SIZE
123456789012        domain/sample_app:12345   "./cmd"             4 minutes ago       Up 4 minutes                            sample_app                 0B (virtual 150MB)
```
