### ISSUE TITLE
vmware_host: Module exits if re-run when host is not in a cluster and just in a datacenter

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#44772]
##### SUMMARY
If a ESXi host is configured to be just in a datacenter in the vCenter inventory and not a cluster the module will add the ESXi host with a status of ok.  When the module is re-run it exits rather than returns a state of Ok.

When preparing additional ESXi hosts we need to do the configuration outside of a production cluster at the datacenter level. Once configured then it is moved into a production cluster where NSX will auto-configure things like VXLAN vmkernel ports.

There maybe occasions where the playbook needs to be re-run during configuration and having the playbook continue is required for this.

FYI when the ESXi host is configured to be in a cluster the module will add the host with a status of Ok. When the module is re-run then the module will return a state of Ok and the playbook continues.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_host.py

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /root/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Ansible run environment: CentOS7
Target vCenter: 6.7
Target ESXi 6.7

##### STEPS TO REPRODUCE
```yaml
- name: 'Add ESXi host to vCenter'
  connection: 'local'
  vmware_host:
    hostname: '{{ vcenter }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    datacenter_name: '{{ pod_name }}'
    folder: '{{ dc_name }}/host'
    esxi_hostname: '{{ ansible_host }}'
    esxi_username: '{{ esxi_root_account }}'
    esxi_password: '{{ esxi_password }}'
    state: 'present'
    validate_certs: '{{ validate_certs }}'
```

##### EXPECTED RESULTS
Module returns a status of Ok and playbook continues

##### ACTUAL RESULTS
```
TASK [add_esxi_to_vcenter_datacenter : Add ESXi host to vCenter] ******************************************************************************************************************************************************************************************************************
fatal: [<ESXI HOSTNAME>]: FAILED! => {"changed": false, "msg": "Failed to add host <ESXI HOSTNAME> to vCenter: The name '<ESXI HOSTNAME>' already exists."}
```
