### ISSUE TITLE
nios_zone could have a field to specify a Name Server Group for Grid membership

### ISSUE THREAD

**Issue by bpleines** [ansible/ansible#44780]
##### SUMMARY

[Name Server Groups](https://docs.infoblox.com/display/NAG8/About+Name+Server+Groups) are an alternative to manually managing Grid membership for zones. You specify a name server group for automatically assigning a group of DNS (name) servers to DNS zone(s). In our example, we tag one system as Primary.  You can actually have a mix - all Primaries, some Primaries and some Secondaries, or one Primary and some number of Secondaries.

It is worth noting that if implemented this module option should probably be mutually exclusive with grid_primary and grid_secondaries definitions.
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

nios_zone
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /home/bret/ansible-infoblox/ansible.cfg
  configured module search path = [u'/home/bret/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

The nios_zone module does not have a option to specify a Name Server Group. The below playbook shows how to create a Name Server Group and have a zone use that created Name Server Group in a two task playbook using the WAPI API.

```yaml
- name: "Create a name server group called {{ name_server_group }}"
  uri:
    url: "https://{{ nios_provider.host }}/wapi/{{ wapi_version }}/nsgroup"
    method: POST
    user: "{{ nios_provider.username }}"
    password: "{{ nios_provider.password }}"
    body: "{{ nsgroup_yml|to_json }}"
    #201 signifies successful creation
    #400 signifies existing entry
    #both should signify a successful WAPI call
    status_code: 201,400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: ns_group_create
  changed_when: ns_group_create.status == 201
  vars:
    nsgroup_yml:
      name: "{{ name_server_group }}"
      grid_primary:
        - name: "{{ gridmaster_fqdn }}"

- name: "Update the forward zone {{ ansible_zone }} to reflect its new Grid primary as name server group {{ name_server_group }}"
  uri:
    url: "https://{{ nios_provider.host }}/wapi/{{ wapi_version }}/zone_auth"
    method: POST
    user: "{{ nios_provider.username }}" 
    password: "{{ nios_provider.password }}" 
    body: "{{ forward_zone_yml|to_json }}" 
    #201 signifies successful creation
    #400 signifies existing entry
    #both should signify a successful WAPI call
    status_code: 201,400
    headers:
      Content-Type: "application/json"
    validate_certs: no
  register: forward_zone_create
  changed_when: forward_zone_create.status == 201 
  vars:
    forward_zone_yml:
      fqdn: "{{ ansible_zone }}" 
      ns_group: "{{ name_server_group }}" 
      view: "default"
```

##### EXPECTED RESULTS

The above playbook creates a zone using a Name Server Group.
##### ACTUAL RESULTS

The module currently does not support this functionality.

```
TASK [dynamicInfoblox : Create a name server group called ansibleNsGroup] ******
task path: /home/bret/ansible-infoblox/roles/dynamicInfoblox/tasks/name_server_group.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: bret
<localhost> EXEC /bin/sh -c 'echo ~bret && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345 `" && echo ansible-tmp-1535483780.3-151361742420345="` echo /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/basics/uri.py
<localhost> PUT /home/bret/.ansible/tmp/ansible-local-5563HQx8Zs/tmpmA5Qiq TO /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345/uri.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345/ /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345/uri.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345/uri.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/bret/.ansible/tmp/ansible-tmp-1535483780.3-151361742420345/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "cache_control": "no-cache, no-store", 
    "changed": false, 
    "connection": "close", 
    "content_type": "application/json", 
    "date": "Tue, 28 Aug 2018 14:06:43 GMT", 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "body": "{\"name\": \"ansibleNsGroup\", \"grid_primary\": [{\"name\": \"gm.ansible.local\"}]}", 
            "body_format": "raw", 
            "client_cert": null, 
            "client_key": null, 
            "content": null, 
            "creates": null, 
            "delimiter": null, 
            "dest": null, 
            "directory_mode": null, 
            "follow": false, 
            "follow_redirects": "safe", 
            "force": false, 
            "force_basic_auth": false, 
            "group": null, 
            "headers": {
                "Content-Type": "application/json"
            }, 
            "http_agent": "ansible-httpget", 
            "method": "POST", 
            "mode": null, 
            "owner": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "regexp": null, 
            "remote_src": null, 
            "removes": null, 
            "return_content": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "status_code": [
                "201", 
                "400"
            ], 
            "timeout": 30, 
            "unsafe_writes": null, 
            "url": "https://192.168.1.2/wapi/v2.6/nsgroup", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "admin", 
            "use_proxy": true, 
            "user": "admin", 
            "validate_certs": false
        }
    }, 
    "json": {
        "Error": "AdmConDataError: None (IBDataConflictError: IB.Data.Conflict:The NS group 'ansibleNsGroup' already exists)", 
        "code": "Client.Ibap.Data.Conflict", 
        "text": "The NS group 'ansibleNsGroup' already exists"
    }, 
    "msg": "HTTP Error 400: Bad Request", 
    "pragma": "no-cache", 
    "redirected": false, 
    "set_cookie": "ibapauth=\"ip=192.168.1.113,client=API,group=admin-group,ctime=1535465203,timeout=600,mtime=1535465203,su=1,auth=LOCAL,user=admin,yYRkB3Y5yOJYBmew7sEWJYeSUMMTaYgD0Dw\"; httponly; Path=/; secure", 
    "status": 400, 
    "transfer_encoding": "chunked", 
    "url": "https://192.168.1.2/wapi/v2.6/nsgroup"
}

TASK [dynamicInfoblox : Update the forward zone ansible.local to reflect its new Grid primary as name server group ansibleNsGroup] ***
task path: /home/bret/ansible-infoblox/roles/dynamicInfoblox/tasks/name_server_group.yml:33
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: bret
<localhost> EXEC /bin/sh -c 'echo ~bret && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210 `" && echo ansible-tmp-1535483868.0-21423356596210="` echo /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/basics/uri.py
<localhost> PUT /home/bret/.ansible/tmp/ansible-local-5718OhpUoI/tmp4jJ6C_ TO /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210/uri.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210/ /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210/uri.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210/uri.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/bret/.ansible/tmp/ansible-tmp-1535483868.0-21423356596210/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "cache_control": "no-cache, no-store", 
    "changed": true, 
    "connection": "close", 
    "content_type": "application/json", 
    "cookies": {
        "ibapauth": "\"ip=192.168.1.113,client=API,group=admin-group,ctime=1535465291,timeout=600,mtime=1535465291,su=1,auth=LOCAL,user=admin,bjudMyrlBojRIMQKOWuIFWjPoSLIINz9QYk\""
    }, 
    "cookies_string": "ibapauth=\"ip=192.168.1.113,client=API,group=admin-group,ctime=1535465291,timeout=600,mtime=1535465291,su=1,auth=LOCAL,user=admin,bjudMyrlBojRIMQKOWuIFWjPoSLIINz9QYk\"", 
    "date": "Tue, 28 Aug 2018 14:08:11 GMT", 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "body": "{\"fqdn\": \"ansible.local\", \"ns_group\": \"ansibleNsGroup\", \"view\": \"default\"}", 
            "body_format": "raw", 
            "client_cert": null, 
            "client_key": null, 
            "content": null, 
            "creates": null, 
            "delimiter": null, 
            "dest": null, 
            "directory_mode": null, 
            "follow": false, 
            "follow_redirects": "safe", 
            "force": false, 
            "force_basic_auth": false, 
            "group": null, 
            "headers": {
                "Content-Type": "application/json"
            }, 
            "http_agent": "ansible-httpget", 
            "method": "POST", 
            "mode": null, 
            "owner": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "regexp": null, 
            "remote_src": null, 
            "removes": null, 
            "return_content": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "status_code": [
                "201", 
                "400"
            ], 
            "timeout": 30, 
            "unsafe_writes": null, 
            "url": "https://192.168.1.2/wapi/v2.6/zone_auth", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "admin", 
            "use_proxy": true, 
            "user": "admin", 
            "validate_certs": false
        }
    }, 
    "json": "zone_auth/ZG5zLnpvbmUkLl9kZWZhdWx0LmxvY2FsLmFuc2libGU:ansible.local/default", 
    "msg": "OK (unknown bytes)", 
    "pragma": "no-cache", 
    "redirected": false, 
    "set_cookie": "ibapauth=\"ip=192.168.1.113,client=API,group=admin-group,ctime=1535465291,timeout=600,mtime=1535465291,su=1,auth=LOCAL,user=admin,bjudMyrlBojRIMQKOWuIFWjPoSLIINz9QYk\"; httponly; Path=/; secure", 
    "status": 201, 
    "transfer_encoding": "chunked", 
    "url": "https://192.168.1.2/wapi/v2.6/zone_auth"
}
```
