### ISSUE TITLE
ovirt_vms RHEV kernel_params doesn't seem to work

### ISSUE THREAD

**Issue by srjayep** [ansible/ansible#44791]
#####  ISSUE TYPE
```
Bug Report
```
##### SUMMARY
I am using ovirt_vms module to create a template from ISO. I am able to attach cd but not able to populate kernel_parameters at boot time, stopping from unattended installation from ISO. Any help is greatly appreciated.

I have tried setting kernel parameters in both ways  , as below. Not seem to work. 

kernel_params:  initrd=initrd.img inst.stage2=cdrom inst.ks=ftp://10.0.1.2/pub/ks.cfg net.ifnames=0 biosdevname=0 BOOT_IMAGE=vmlinuz

 kernel_params:
          - initrd=initrd.img
          - inst.stage2=cdrom
          - inst.ks=http://10.0.1.2/pub/ks.cfg
          - net.ifnames=0
          - biosdevname=0
          - BOOT_IMAGE=vmlinuz  

##### COMPONENT NAME
```
ovirt_vms
```

##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### CONFIGURATION
```
Default ansible configuration
```

##### OS / ENVIRONMENT
Redhat 7.4

##### STEPS TO REPRODUCE

```yaml
- name: RHV-M Host | Building "{{vm_name}}"
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ cluster }}"
        cluster: Default
        storage_domain: nfs
        operating_system: rhel_7x64
        disk_format: raw
        disks:
          - name: test
        cd_iso: "rhel-server-7.4-x86_64-boot.iso"
        boot_devices:
         - cdrom
        nics:
          - name: nic1
        state: running
        initrd_path: iso://initrd.img
        kernel_path: iso://vmlinuz
        kernel_params:
          - initrd=initrd.img
          - inst.stage2=cdrom
          - inst.ks=http://10.0.1.2/pub/ks.cfg
          - net.ifnames=0
          - biosdevname=0
          - BOOT_IMAGE=vmlinuz
        cloud_init:
          custom_script: |
            -file:
              src: /root/.ssh
              state: directory
              owner: root
              group: root
              mode: 0700
            -file:
              src: /root/.ssh/authorized_keys
              state: file
              owner: root
              group: root
              mode: 0600
            runcmd:
              - hostnamectl set-hostname "testtempl"
              - touch /etc/cloud/cloud-init.disabled
```

##### EXPECTED RESULTS
Expect to see kernel parameters in RHEV management console boot_options of the VM.

##### ACTUAL RESULTS
```
changed: [localhost] => {
    "changed": true,
    "diff": {
        "after": {},
        "before": {}
    },
    "id": "5a47ea0c-aef2-40b4-9698-d12b1c69214b",
    "invocation": {
        "module_args": {
            "affinity_group_mappings": [],
            "affinity_label_mappings": [],
            "allow_partial_import": null,
            "ballooning_enabled": null,
            "boot_devices": [
                "cdrom"
            ],
            "boot_menu": null,
            "cd_iso": "rhel-server-7.4-x86_64-boot.iso",
            "clone": false,
            "clone_permissions": false,
            "cloud_init": {
                "custom_script": "-file:\n  src: /root/.ssh\n  state: directory\n  owner: root\n  group: root\n  mode: 0700\n-file:\n  src: /root/.ssh/authorized_keys\n  state: file\n  owner: root\n  group: root\n  mode: 0600\nruncmd:\n  - hostnamectl set-hostname \"testtempl.\"\n  - touch /etc/cloud/cloud-init.disabled\n"
            },
            "cloud_init_nics": [],
            "cloud_init_persist": false,
            "cluster": "Default",
            "cluster_mappings": [],
            "comment": null,
            "cpu_cores": null,
            "cpu_mode": null,
            "cpu_pinning": null,
            "cpu_shares": null,
            "cpu_sockets": null,
            "cpu_threads": null,
            "custom_properties": null,
            "delete_protected": null,
            "description": null,
            "disk_format": "raw",
            "disks": [
                {
                    "name": "test"
                }
            ],
            "domain_mappings": [],
            "fetch_nested": false,
            "force": false,
            "graphical_console": null,
            "high_availability": null,
            "high_availability_priority": null,
            "host": null,
            "id": null,
            "initrd_path": "iso://initrd.img",
            "instance_type": null,
            "io_threads": null,
            "kernel_params": "['initrd=initrd.img', 'inst.stage2=cdrom', 'inst.ks=http://10.0.1.2/pub/ks.cfg', 'net.ifnames=0', 'biosdevname=0', 'BOOT_IMAGE=vmlinuz']",
            "kernel_path": "iso://vmlinuz",
            "kvm": null,
            "lease": null,
            "lun_mappings": [],
            "memory": null,
            "memory_guaranteed": null,
            "memory_max": null,
            "name": "testtempl",
            "nested_attributes": [],
            "nics": [
                {
                    "name": "nic1"
                }
            ],
            "numa_nodes": [],
            "numa_tune_mode": null,
            "operating_system": "rhel_7x64",
            "placement_policy": null,
            "poll_interval": 3,
            "quota_id": null,
            "reassign_bad_macs": null,
            "rng_device": null,
            "role_mappings": [],
            "serial_console": null,
            "serial_policy": null,
            "serial_policy_value": null,
            "smartcard_enabled": null,
            "soundcard_enabled": null,
            "sso": null,
            "state": "running",
            "stateless": null,
            "storage_domain": "NFS",
            "sysprep": null,
            "template": null,
            "template_version": null,
            "timeout": 180,
            "timezone": null,
            "type": null,
            "usb_support": null,
            "use_latest_template_version": null,
            "vmware": null,
            "vnic_profile_mappings": [],
            "wait": true,
            "watchdog": null,
            "xen": null
        }
    },
    "vm": {
        "affinity_labels": [],
        "applications": [],
        "bios": {
            "boot_menu": {
                "enabled": false
            }
        },
        "cdroms": [],
        "cluster": {
            "href": "/ovirt-engine/api/clusters/00000002-0002-0002-0002-00000000017a",
            "id": "00000002-0002-0002-0002-00000000017a"
        },
        "cpu": {
            "architecture": "x86_64",
            "topology": {
                "cores": 1,
                "sockets": 1,
                "threads": 1
            }
        },
        "cpu_profile": {
            "href": "/ovirt-engine/api/cpuprofiles/5964ec14-001a-0022-028d-000000000157",
            "id": "5964ec14-001a-0022-028d-000000000157"
        },
        "cpu_shares": 0,
        "creation_time": "2018-08-28 15:12:34.963000-05:00",
        "delete_protected": false,
        "disk_attachments": [],
        "display": {
            "allow_override": false,
            "copy_paste_enabled": true,
            "disconnect_action": "LOCK_SCREEN",
            "file_transfer_enabled": true,
            "monitors": 1,
            "single_qxl_pci": false,
            "smartcard_enabled": false,
            "type": "spice"
        },
        "graphics_consoles": [],
        "high_availability": {
            "enabled": false,
            "priority": 0
        },
        "host_devices": [],
        "href": "/ovirt-engine/api/vms/5a47ea0c-aef2-40b4-9698-d12b1c69214b",
        "id": "5a47ea0c-aef2-40b4-9698-d12b1c69214b",
        "io": {
            "threads": 1
        },
        "katello_errata": [],
        "large_icon": {
            "href": "/ovirt-engine/api/icons/508a3205-edca-cee0-862b-c5f6d60a1e6f",
            "id": "508a3205-edca-cee0-862b-c5f6d60a1e6f"
        },
        "memory": 1073741824,
        "memory_policy": {
            "ballooning": true,
            "guaranteed": 1073741824,
            "max": 4294967296
        },
        "migration": {
            "auto_converge": "inherit",
            "compressed": "inherit"
        },
        "migration_downtime": -1,
        "name": "testtempl",
        "next_run_configuration_exists": false,
        "nics": [],
        "numa_nodes": [],
        "numa_tune_mode": "interleave",
        "origin": "ovirt",
        "original_template": {
            "href": "/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000000",
            "id": "00000000-0000-0000-0000-000000000000"
        },
        "os": {
            "boot": {
                "devices": [
                    "cdrom"
                ]
            },
            "type": "rhel_7x64"
        },
        "permissions": [],
        "placement_policy": {
            "affinity": "migratable"
        },
        "quota": {
            "id": "5964ec2e-01c3-0352-003b-000000000245"
        },
        "reported_devices": [],
        "sessions": [],
        "small_icon": {
            "href": "/ovirt-engine/api/icons/83af03cb-064e-d718-4345-fc16e2cc1e24",
            "id": "83af03cb-064e-d718-4345-fc16e2cc1e24"
        },
        "snapshots": [],
        "sso": {
            "methods": []
        },
        "start_paused": false,
        "stateless": false,
        "statistics": [],
        "status": "down",
        "stop_time": "2018-08-28 15:12:34.967000-05:00",
        "storage_error_resume_behaviour": "auto_resume",
        "tags": [],
        "template": {
            "href": "/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000000",
            "id": "00000000-0000-0000-0000-000000000000"
        },
        "time_zone": {
            "name": "Etc/GMT"
        },
        "type": "desktop",
        "usb": {
            "enabled": false
        },
        "watchdogs": []
    }
}

```
