### ISSUE TITLE
sensu_silence.py needs to support API authentication

### ISSUE THREAD

**Issue by naioja** [ansible/ansible#44840]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

sensu_silence
##### ANSIBLE VERSION

```
ansible 2.6.2
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
  - name: Silence server1.example.dev
    sensu_silence:
      subscription: client:server1.example.dev
      creator: "admin"
      reason: Performing maintenance
      expire_on_resolve: yes
      state: present
      url: "http://admin:{{password}}@127.0.0.1:4567"
```

##### EXPECTED RESULTS

I expect to have a way to use authentication for sensu API
##### ACTUAL RESULTS

FAILED! => {"changed": false, "msg": "Failed to silence client:server1.example.dev. Reason: HTTP Error 401: basic auth failed"}

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/sensu_silence.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/sensu_silence.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @smbambling
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sstaszkiewicz-copperleaf** [comment]
Workaround:
```
- name: Silence sensu
  uri:
    url: https://sensu-server.com:4567/silenced
    method: POST
    user: user
    password: password
    body: "{{ {'subscription': 'client:whatever', 'expire': 120} | to_json }}"
    force_basic_auth: yes
    status_code: 201
    body_format: json
```
