### ISSUE TITLE
azure_rm_securitygroup - remove individual rules

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#44900]
##### SUMMARY
According to azure_rm_securitygroup module documentation there is no option to remove individual rules.
Azure Cli has functions for this action. Please add remove rule functionality. 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_securitygroup

##### ANSIBLE VERSION
```
2.6.2
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_securitygroup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_securitygroup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @nicolaibaralmueller,

Thank you for the issue, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in #ansible-azure on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
notabug

@nicolaibaralmueller Hi, from Ansible perspective, using Ansible module is not to on demand adding/deleting, even creation for a resource. But to define a state to check whether the resources is in the defined state or update it to the state. This is why there is no single command for adding/removing a single rule for NSG. If you want to remove a one, you can use the `azure_rm_securitygroup_facts` module to query what rules it has, and then configure the new rule list for your `azure_rm_securitygroup` module.

**Comment by nicolaibaralmueller** [comment]
@yuwzho Hi. I'm a bit confused about that logic. Using azure_rm_securitygroup_facts will get me current rules. That will not allow me to remove a specific rule from the output. 
Although not pretty code wise, I went with using a simple az cli command to delete specific rules.
Still think the module should allow to remove single rules.

**Comment by yuwzho** [comment]
Hi @nicolaibaralmueller , IMO, when you use az cli to delete a rule, you will delete the rule once you running the command, and the command will run into failure if you run it again since there is no such rule now. But for Ansible Playbook, we don't suggest you run it only once. You can configure which rules the NSG should have, and run the playbook as many times as you can and whenever you want, Ansible will update the NSG to the state as you want or keep silent if your NSG already meet your state.

I would write the playbook like this logic (may have some typo mistake):

```yaml

- name: query current status
  azure_rm_securitygroup_facts:
       resource_group: foo
       name: bar
   register: nsgs

- set_fact:
        rules: "{{ rules | default([]) | combine({ item.key: item.value }) }}"
   with_items: nsgs['ansible_facts']['azure_securitygroups'][0]['properties']['securityRules']
   when: item.key != your_want_to_remove

- name: set the new rule
   azure_rm_securitygroup:
        resource_group: foo
        name: bar
        rules: rules
        ......
```
