### ISSUE TITLE
k8s ansible module issue with apiVersion: monitoring.coreos.com/v1

### ISSUE THREAD

**Issue by jdamata** [ansible/ansible#44914]
##### SUMMARY
The k8 module src parameter doesn't seem to allow for using the monitoring.coreos.com/v1 apiversion. Attempted different kubernetes manifest files with apiVersion: monitoring.coreos.com/v1. All of which fail.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = None
  configured module search path = [u'/Users/damatj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 16:36:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### OS / ENVIRONMENT

macOS High Sierra 10.13.6

##### STEPS TO REPRODUCE

```yaml
PLAYBOOK:
- name: "Deploy all {{ application }} manifests"
  k8s:
    host: .....
    api_key: "{{ vault_token }}"
    verify_ssl: no
    state: present
    src: "{{ item }}"
  with_fileglob:
    - "files/manifests/{{ application }}/*"

MANIFEST:
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      alertmanager: main
<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->
ok: [localhost] => (item=/opt/git/stratus-prometheus/ansible/files/manifests/kubestate/kube-state-metrics-serviceMonitor.yaml)

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
```
failed: [localhost] (item=/opt/git/stratus-prometheus/ansible/files/manifests/kubestate/kube-state-metrics-serviceMonitor.yaml) => {"changed": false, "error": 500, "item": "/opt/git/stratus-prometheus/ansible/files/manifests/kubestate/kube-state-metrics-serviceMonitor.yaml", "msg": "Failed to patch object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"unable to find api field in struct Unstructured for the json field \\\"apiVersion\\\"\",\"code\":500}\n", "reason": "Internal Server Error", "status": 500}

```
