### ISSUE TITLE
Squash facts from loops to lists

### ISSUE THREAD

**Issue by stawii** [ansible/ansible#44933]
##### SUMMARY
When using loops (or with_* magic) with actions that generates facts (with `set_fact` at the forefront) only last returned facts are exposed to host. It would be nice feature to have option to squash them into list with simple parameter. By default this should be off, so current behavior is kept for backward compatibility.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ActionBase (?)

##### CURRENT SITUATION
```yaml
    - set_fact:
        say_hello: "hello {{ item }}"
        say_byebye: "byebye {{ item }}"
      with_list: ["foo", "bar", "not you", "baz"]
      when: (item != "not you")

    - debug: var=say_hello
    - debug: var=say_byebye
```
results in:
```
ok: [localhost] => {
    "say_hello": "hello baz"
}
ok: [localhost] => {
    "say_byebye": "byebye baz"
}
```
Only last loop iteration facts are returned, previous ones are overwritten.

##### PROPOSED SOLUTION
```yaml
    - set_fact:
        say_hello: "hello {{ item }}"
        say_byebye: "byebye {{ item }}"
      with_list: ["foo", "bar", "not you", "baz"]
      when: (item != "not you")
      squash_facts: yes  # new feature!

    - debug: var=say_hello
    - debug: var=say_byebye
```
results in:
```
ok: [localhost] => {
    "say_hello": [
        "hello foo",
        "hello bar",
        "hello baz"
    ]
}
ok: [localhost] => {
    "say_byebye": [
        "byebye foo",
        "byebye bar",
        "byebye baz"
    ]
}
```
I know this can be achieved in at least 3 different ways:
1. you need to do additional tasks to get all facts as a list (register to var first, filter out skipped, map each fact, save to new fact..) it's a boilerplate code boating everywhere. 
2. change it to something like `text: "{{ text|default([]) + ['hello ' + item] }}"` to workaround.. this looks awful and output looks like stair case.
3. also you can refactor this to use some kind of Jinja-voodoo magic to generate this on-the-fly but this hard to read/debug for complex vars.

None of this (and at other solutions like this) is simple one-liner additional parameter so I believe I've made my point.

Behavior of skipped loop iterations is open for discussion. I suggest another parameter which defines default values for facts from skipped items. By default it should omit them from output like in the sample above. I believe this is most wanted solution. If one wants to have some kind of value one must define it. Simple :)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/module_utils/facts](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts)
* [lib/ansible/modules/net_tools/dnsimple.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/dnsimple.py)
* [lib/ansible/modules/utilities/logic/set_fact.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/set_fact.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/plugins/filter](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @drcapulet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
You can already do that w/o having a special feature:
```yaml
    - set_fact:
        say_hello: "{{say_hello|default([]) + ['hello ' ~ item] }}"
        say_byebye: "{{say_byebye|default([]) + ['byebye ' ~ item] }}"
      with_list: ["foo", "bar", "not you", "baz"]
      when: (item != "not you")
```

**Comment by stawii** [comment]
> 
> 
> You can already do that w/o having a special feature:
> 
> ```yaml
>     - set_fact:
>         say_hello: "{{say_hello|default([]) + ['hello ' ~ item] }}"
>         say_byebye: "{{say_byebye|default([]) + ['byebye ' ~ item] }}"
>       with_list: ["foo", "bar", "not you", "baz"]
>       when: (item != "not you")
> ```

Yes, this is working, but this is workaround (2nd solution). And if your list have a lot of items each one gives you `n` items in output constructing staircase debug spam. Also imagine how this should looks like if each element of target fact is not a simple string but complex structure. For some situation one can use json query but not for all cases.

**Comment by bcoca** [comment]
You can deal with the display by using select/reject/map, you also have filters like `combine` to deal with complex merges

```yaml
    - set_fact:
        say_hello: "{{say_hello|default([]) + ["foo", "bar", "not you", "baz"]|reject('equals', 'not_you)|map('regex_replace', '^', 'hello ')|list }}"
      when: (item != "not you")
```

**Comment by stawii** [comment]
Come on, last one was not even close to maintainable code ;)
In simple cases I have something close to:
```
- set_fact:
    register_domains:
      name: "{{ item.service_name }}.{{ root_domain_zone }}"
      addr: "{{ item.backends | map(attribute='addr') | uniq | sort }}"
      type: "{{ item.dns_record_type | default('A') }}"
      ttl: "{{ item.dns_record_ttl | default(60) }}"
  with_items: "{{ service_lists | intersect(default_service_list) }}"
  when: (item.setup_dns is defined) and (item.setup_dns)
  ```
Hard ones are just more complex structures, domain-specific - cannot paste them here.
