### ISSUE TITLE
set_fact not adhearing to when

### ISSUE THREAD

**Issue by csnyder78** [ansible/ansible#44930]
##### SUMMARY

When using set_fact with when, it is not adhering to the condition properly, and is overwriting it in a not so great way.
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```yaml
- stat:
   path: /home/user/thisfile
   register: foo
- set_fact:
    bob: "{{ some_var }}
  when: foo.stat.exists == False
- set_fact:
    bob: "{{ someothervar }}"
  when: foo.stat.exists == True
```

##### EXPECTED RESULTS

Set bob as some_var
##### ACTUAL RESULTS

Set bob as someothervar.  

```
I can't copy, but it sys that it skips the True Step but the var bob becomes {'skip_reason': u'Conditional result was False', 'skipped': True, 'changed': False}:
```

**Comment by mkrizek** [comment]
Works as expected for me:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - stat:
        path: /home/mkrizek/.vimrc
      register: vimrc_stat
    - set_fact:
        vimrc: missing
      when: vimrc_stat.stat.exists == False
    - set_fact:
        vimrc: exists
      when: vimrc_stat.stat.exists == True
    - debug:
        var: vimrc
```
gives me:
```bash
PLAY [localhost] ****************************************************************************************

TASK [stat] *********************************************************************************************
ok: [localhost]

TASK [set_fact] *****************************************************************************************
skipping: [localhost]

TASK [set_fact] *****************************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "vimrc": "exists"
}

PLAY RECAP **********************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

What am I doing differently?

needs_info
