### ISSUE TITLE
vmware_guest: Configure a VM with multiple vSCSI controllers

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#44957]
##### SUMMARY
As per;

https://blogs.vmware.com/vsphere/2014/02/vscsi-controller-choose-performance.html

To provide the best performance, one should also distribute virtual disk across as many vSCSI adapters as possible.  This configuration provides the capability to process more IO simultaneously and benefit from additional queues if necessary.

This is something we do in product for our internal infrastructure and it would be very useful to be able to 
create new VMs with this level of detail

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /root/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
vSphere 6.0 and above

##### STEPS TO REPRODUCE
I've got some code in this Repo which creates VMs and can add multiple scsi adapaters with multiple disks on each based on a yaml file

https://github.com/nicholasrodriguez/create-vsphere-vm-from-yaml.git

Perhaps add a top level key in vmware_guest **diskcontrollers** (to preserve backwards compatabillity) with the following contents :
```
 diskcontrollers:
  - diskcontroller: 'paravirtual'
    disks:
    - size_gb: 50
      type: 'thin'
      datastore: 'datastore-1'
    - size_gb: 250
      type: 'thin'
      datastore: 'datastore-1'
  - diskcontroller: 'paravirtual'
    disks:
    - size_gb: 100
      type: 'thin'
      datastore: 'datastore-2'
```

##### EXPECTED RESULTS
In the above example the VM would be created with 2 vSCSI controllers with two disks attached to the first vSCSI  and one disk attached to the second vSCSI
