### ISSUE TITLE
Proxmox_kvm VMs not correctly converting to template

### ISSUE THREAD

**Issue by olaldiko** [ansible/ansible#44950]
##### SUMMARY
The Proxmox_kvm module does not correctly convert VMs to templates, it only sets the template flag in the VM, but the disks are left without preparation, as the API endpoint POST /api2/json/nodes/{node}/qemu/{vmid}/template is not called. This causes to not be able to create linked clones from the newly created template. Giving the following error: "Linked clone feature is not supported for drive 'scsi0'."
Machines created from the GUI using the same process work properly and can be linked cloned. Storage is local LVM. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Proxmox_kvm

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /<project_folder>/ansible.cfg
  configured module search path = [u'/Users/<user>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

CACHE_PLUGIN= jsonfile
CACHE_PLUGIN_CONNECTION= ./facts_cache/
CACHE_PLUGIN_TIMEOUT= 86400
DEFAULT_HOST_LIST = [u'/<folder>/hosts.yml']
DEFAULT_REMOTE_USER = <remote_user>
DEFAULT_VAULT_PASSWORD_FILE = <vault_file>
HOST_KEY_CHECKING = False

##### OS / ENVIRONMENT

Launching from OSX 10.13, managing Debian 9.5, ProxmoxVE 5.2-1
##### STEPS TO REPRODUCE

Convert VM to template via Ansible Playbook

```yaml
    - name: Convert VMs to templates
      proxmox_kvm:
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        api_host: '{{ api_host }}'
        validate_certs: '{{ validate_certs }}'
        node: '{{ node }}'
        vmid: '{{ item.template_vmid }}'
        name: '{{ item.name }}-template'
        cores: '{{ item.cores }}'
        memory: '{{ item.ram }}'
        net: '{"net0": "virtio,bridge=vmbr1000"}'
        template: yes
        update: yes
        state: present
      loop: '{{ vm_data }}'
```

##### EXPECTED RESULTS

The disk conversion should be done correctly and Linked clone should be able to be done from the template.
##### ACTUAL RESULTS

Only template flag is set and no disk preparation is done. Thus not letting create linked clones from the resulting template.

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/misc/proxmox_kvm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @helldorado
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tobiasmcnulty** [comment]
I can confirm this; I found this ticket Googling the error "Linked clone feature is not supported for drive 'scsi0'.", and when I switch to running `qm template <vmid>` on the command line (instead of using `template: yes` in `proxmox_kvm`), this error goes away and I can create a linked clone successfully.

**Comment by helldorado** [comment]
@tobiasmcnulty your issue related to creating template from VM or creating linked clone ? 

If you can't create linked clone like this issue #41940, can you test this fix https://github.com/ansible/ansible/pull/42313 ?

@olaldiko i confirm i can reproduce. I would make a fix in the current PR.

**Comment by helldorado** [comment]
@olaldiko i fix it, please see the PR #44950 for more info see diff https://github.com/helldorado/ansible/commit/9037507fff23eb13b25877005a2c73d5c98e045d

Example:

* CONVERT

```yaml
- hosts: localhost
  remote_user: root
  gather_facts: False
  tasks:
    - name: Convert VMs to templates
      proxmox_kvm:
        api_host   : lahyp1.helldorado.info
        node       : labhyp1
        api_user   : root@pam
        template   : yes
        name       : ikora
        update     : yes
        #disk       : scsi0
        #vmid       : 112
      register: qemu

    - name: Debug QEMU
      debug: var=qemu
```

```yaml
ansible@sabrewulf:/usr/local/ansible/orchestrator$ ansible-playbook convert.yml

PLAY [localhost] ******************************************************************

TASK [Convert VMs to templates] ************************************************
changed: [localhost]

TASK [Debug QEMU] **************************************************************
ok: [localhost] => {
    "qemu": {
        "changed": true,
        "msg": "VM ikora with vmid 112 updated. It's also converted to template."
    }
}

PLAY RECAP ************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

* CLONE

```yaml
- hosts: localhost
  remote_user: root
  gather_facts: False
  tasks:
    - name: Clone Image
      proxmox_kvm:
        api_host   : lahyp1.helldorado.info
        node         : lahyp1
        api_user   : root@pam
        clone: ikora
        name: cloned-ikora-link
        full: no
        #newid: 1000
        #format: raw
      register: qemu

    - name: Debug QEMU
      debug: var=qemu
```

```yaml
ansible@sabrewulf:/usr/local/ansible/orchestrator$ ansible-playbook clone.yml

PLAY [localhost] *******************************************************************
TASK [Clone Image] ***************************************************************
changed: [localhost]

TASK [Debug QEMU] **************************************************************
ok: [localhost] => {
    "qemu": {
        "changed": true,
        "devices": {
            "ide2": "none",
            "scsi0": "VMs_labhyp1:116/vm-116-disk-1.qcow2",
            "virtio1": "ZSF_labhyp1:vm-116-disk-1"
        },
        "mac": {
            "net0": "A2:DC:0A:EE:17:AD"
        },
        "msg": "VM cloned-ikora-link with newid 116 cloned from vm with vmid 112",
        "vmid": 116
    }
}
```
## NOTE
Set `disk` param If you want to convert only 1 disk to base image. 

You can pull this version in your `playbooks/library/` If this fix your issue please feel free to leave comment with **shipit** keyword.

**Comment by tobiasmcnulty** [comment]
@helldorado It's both...the template "appeared" to create successfully with `proxmox_kvm`, but it could not be used to create a linked clone. The only way to create a template that could be used to create a linked clone was to do so from the command line with the `qm template` command.

Happy to test but not entirely sure how...are there docs somewhere on this?

**Comment by helldorado** [comment]
@tobiasmcnulty 
1 - Pull the raw file in your `playbooks/library/` from https://raw.githubusercontent.com/helldorado/ansible/9037507fff23eb13b25877005a2c73d5c98e045d/lib/ansible/modules/cloud/misc/proxmox_kvm.py

The module doc is here => https://docs.ansible.com/ansible/2.5/modules/proxmox_kvm_module.html

**Comment by olaldiko** [comment]
Hi @helldorado, thank you very much, now the template is correctly converted, tested it.
However, I think that we have created another bug on the process. When attempting to update the network interface and specs of the VM, after converting it to template, I get the following error:
```shell
failed: {"changed": false, "item": {"base_vm_ip": "<ip>/24", "base_vmid": <vm_id>, "cores": 2, "disk": "20G", "name": "<vm_name>", "ram": 2048, "template_vmid": 1234}, "msg": "Unable to update vm None with vimd 1234=local variable 'template_msg' referenced before assignment"}
```
The configuration for the task used is the following:
```yaml
    - name: Update template VM network bridge & specs
      proxmox_kvm:
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        api_host: '{{ api_host }}'
        validate_certs: '{{ validate_certs }}'
        node: '{{ node }}'
        vmid: '{{ item.template_vmid }}'
        cores: '{{ item.cores }}'
        memory: '{{ item.ram }}'
        net: '{"net0":"virtio,bridge=vmbr1"}'
        agent: yes
        update: yes
        state: present
```
Thank you very much!
