### ISSUE TITLE
one_vm memory parameter not working

### ISSUE THREAD

**Issue by ulide4** [ansible/ansible#44961]
##### SUMMARY

when instantiating a new vm the memory parameter is not used. The memory size from the template is used instead.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

one_vm
##### ANSIBLE VERSION

```
2.6
```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```yaml
- one_vm:
    template_id: 2
    disk_size: 40 GB
    memory: 4 GB
    vcpu: 2
    count: 1


OR

- one_vm:
    template_id: 2
    disk_size: 40 GB
    memory: 4096 MB
    vcpu: 2
    count: 1


```

##### EXPECTED RESULTS

A VM with 4GB of Memory

##### ACTUAL RESULTS

```
A VM with 2 GB Memory (as defined in the template)

Additional Info:  I can create a VM with Sunstone with 4 GB memory from the same template just fine...
```
