### ISSUE TITLE
VMware: vmware_guest not resizing hardware

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#44962]
##### SUMMARY

The VMware module does not reflect changes after the initial deployment, e.g. Disk/Memory size changed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/user/Git/testProject/plays/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/Git/testProject/plays/ansible.cfg) = -o ForwardAgent=no
COMMAND_WARNINGS(/home/user/Git/testProject/plays/ansible.cfg) = True
DEFAULT_BECOME(/home/user/Git/testProject/plays/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(/home/user/Git/testProject/plays/ansible.cfg) = True
DEFAULT_FORKS(/home/user/Git/testProject/plays/ansible.cfg) = 50
DEFAULT_MANAGED_STR(/home/user/Git/testProject/plays/ansible.cfg) = This file is managed by ansible - local changes will be lost
DEFAULT_REMOTE_USER(/home/user/Git/testProject/plays/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/user/Git/testProject/plays/ansible.cfg) = ['/home/user/Git/testProject/roles/internal', '/home/user/Git/testProject/roles/external']
DEFAULT_TRANSPORT(/home/user/Git/testProject/plays/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/home/user/Git/testProject/plays/ansible.cfg) = /home/user/Git/testProject/.vpass
DEPRECATION_WARNINGS(/home/user/Git/testProject/plays/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/user/Git/testProject/plays/ansible.cfg) = True
SYSTEM_WARNINGS(/home/user/Git/testProject/plays/ansible.cfg) = True
```

##### OS / ENVIRONMENT

ArchLinux

##### STEPS TO REPRODUCE

```yaml
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template using the vmware_guest module
- name: VM from template
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: vcenter.example.com
    esxhost: esxi01.example.com
    datastore: devDatastore
    network: Customer001
    vmtemplate: Win Server 2016 Template GUI (german)
    vmcluster: myCluster
    notes: Created by Ansible
    dumpfacts: False
    vcdatacenter: myDatacenter
    vmfolder: /myVMs
    vmname: DEV-TTTTTTTTTTT
    vcenter_user: myUser
    vcenter_pass: myPassword
  tasks:
      
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: "{{ vcdatacenter }}"
        name: "{{ vmname }}"
        guest_id: windows9Server64Guest
        template: "{{ vmtemplate }}"
        folder: "{{ vmfolder }}"
        disk:
          - size_gb: 80
            type: thin
            datastore: "{{ datastore }}"
        networks:
          - device_type: vmxnet3
            name: "{{ network }}"
            start_connected: True
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        customization:
          autologon: yes
          dns_servers:
          - 1.1.1.1
          - 9.9.9.9
          password: newPa$$w0rd
        state: poweredon
```

and after you have run Ansible once, change something like the disk or memory size and run it again.

##### EXPECTED RESULTS

The module should update the vm accordingly.
If the vm is powered on when calling this it will fail (as the vmware api does so) if one requests to set a lower value for memory or cpu. If increasing succeeds is determined if memory and cpu hotplug is enabled.
If the vm is not powered on, the only change that will fail is shrinking the virtual disk. But removing cpu cores and memory will succeed.

Basically this module should update all properties if the vm already exists in an best effort way. And fail if it is not possible in the current state (e. g. shrinking allocated memory while the vm is running) with an error that reflects this, so that users of that module can handle it (stop the software inside of the vm and turning it off)

##### ACTUAL RESULTS

The ansible module does not check for changes and returns it being in the desired state.
