### ISSUE TITLE
[aws] cloudfront distribution giving `KeyError: 'Distribution'` traceback

### ISSUE THREAD

**Issue by avocadojesus** [ansible/ansible#45043]
##### SUMMARY
No matter, what my cloudfront distribution config reads, all i seem to get is this error:

```
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/cloud/amazon/cloudfront_distribution.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: avojeez0
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python3.7 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py", line 1988, in <module>
    main()
  File "/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py", line 1918, in main
    config = distribution['Distribution']['DistributionConfig']
KeyError: 'Distribution'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py\", line 1988, in <module>\n    main()\n  File \"/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py\", line 1918, in main\n    config = distribution['Distribution']['DistributionConfig']\nKeyError: 'Distribution'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

cloudfront_distribution

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/avojeez0/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jul 23 2018, 20:22:55) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it can also be a list of hosts, a directory or a list of paths , use [defaults] 
inventory=/path/to/file|dir instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/ec2.py']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ubuntu
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Macbook Pro 2012 OSX High Sierra

##### STEPS TO REPRODUCE

the cloudfront distribution config i am using:

```yaml
cloudfront_distribution:
        comment: "LOD (Ansible) {{ server_environment }} public"
        state: present
        caller_reference: "{{ cloudfront_caller_ref }}"
        price_class: "{{ s3_web_price_class }}"
        enabled: true
        origins:
            - id: "LOD-S3-{{ s3_web_bucket_name }}"
              origin_path: ""
              custom_origin_config:
                origin_protocol_policy: http-only
                http_port: 80
                https_port: 443
              domain_name: "{{ s3_web_bucket_name }}.s3-website-{{ ec2_region }}.amazonaws.com"
        default_cache_behavior:
          target_origin_id: "LOD-S3-{{ s3_web_bucket_name }}"
          viewer_protocol_policy: redirect-to-https
          trusted_signers:
            enabled: false
          forwarded_values:
            query_string: false
            cookies:
              forward: none
          max_ttl: 300
          min_ttl: 0
          default_ttl: 300
          smooth_streaming: false
          compress: true
          allowed_methods:
            items:
              - GET
              - HEAD
            cached_methods:
              - GET
              - HEAD
          lambda_function_associations:
            - event_type: viewer-response
              lambda_function_arn: "{{ cloudfront_lambda_arn }}"
        viewer_certificate:
          ssl_support_method: sni-only
          acm_certificate_arn: "{{ cloudfront_ssl_certificate_arn }}"
          minimum_protocol_version: TLSv1.1_2016
          certificate: "{{ cloudfront_ssl_certificate_arn }}"
          certificate_source: acm
        custom_error_responses:
          - error_code: 403
            response_page_path: /index.html
            response_code: 200
            error_caching_min_ttl: 300
          - error_code: 404
            response_page_path: /index.html
            response_code: 200
            error_caching_min_ttl: 300
        http_version: http2
        aliases:
          - "{{ web_endpoint }}"
      # when: has_cloudfront_instance==false
      register: cloudfront_public_distribution
```

##### EXPECTED RESULTS

I was hoping to get a cloudfront distribution who's viewer response was bound to a lambda function that binds security headers to my requests

##### ACTUAL RESULTS

```
TASK [Ensure that cloudfront public distribution exists] *****************************************************************************************************
task path: /Users/avojeez0/Sites/lod-planner-ops/ansible/deploy-infrastructure.yml:607
Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/cloud/amazon/cloudfront_distribution.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: avojeez0
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python3.7 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py", line 1988, in <module>
    main()
  File "/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py", line 1918, in main
    config = distribution['Distribution']['DistributionConfig']
KeyError: 'Distribution'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py\", line 1988, in <module>\n    main()\n  File \"/var/folders/sl/twl1b5l52s9_c4gg0f5jx6m00000gn/T/ansible_cjmalv1o/ansible_module_cloudfront_distribution.py\", line 1918, in main\n    config = distribution['Distribution']['DistributionConfig']\nKeyError: 'Distribution'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
	to retry, use: --limit @/Users/avojeez0/Sites/lod-planner-ops/ansible/deploy-infrastructure.retry
```
