### ISSUE TITLE
k8s: Failed to patch object

### ISSUE THREAD

**Issue by davidwneary** [ansible/ansible#45111]
##### SUMMARY
Get error `Failed to patch object` when using the `k8s` command for a resource that already exists. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s
##### ANSIBLE VERSION

```
ansible 2.7.0b1
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/envs/devops/lib/python3.6/site-packages/ansible
  executable location = ~/envs/devops/bin/ansible
  python version = 3.6.4 (default, Mar  9 2018, 23:15:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Local machine: macOS Sierra [Version 10.12.6 (16G29)] 
Remote Cluster: Azure AKS, Kubernetes version: 1.11.2

##### STEPS TO REPRODUCE

```yaml
name: Provision AI AKS Cluster
hosts: localhost
connection: local
gather_facts: False
vars:
    kubeconfig: "{{playbook_dir}}/output/kubeconfig.yml"
    letsencrypt_env: staging
    letsencrypt_name: "letsencrypt-{{letsencrypt_env}}"
    letsencrypt_urls:
      staging: https://acme-staging-v02.api.letsencrypt.org/directory
      prod: https://acme-v02.api.letsencrypt.org/directory
tasks:
- name: ensure cluster issuer exists
   k8s:
     kubeconfig: "{{kubeconfig}}"
     state: present
     definition: "{{ lookup('template', './templates/cluster-issuer.yml.j2') | from_yaml }}"
```
**cluster-issuer.yml.j2**
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: "{{letsencrypt_name}}"
spec:
  acme:
    server: "{{letsencrypt_urls[letsencrypt_env]}}"
    email: dave.neary@example.com
    privateKeySecretRef:
      name: "{{letsencrypt_name}}"
    http01: {}
```

I run the playbook with:
```
ansible-playbook -i "127.0.0.1," playbook-for-aks-provisioning.yml -e 'ansible_python_interpreter=~/envs/devops/bin/python' -vvv
```

##### EXPECTED RESULTS

I would expect this resource to become present on the AKS cluster. If it is already there, it will be updated, if not, it will be created. The result should be the same as if I had run `kubectl apply -f cluster-issuer.yml`. 

##### ACTUAL RESULTS

If the resource is **not** there already, it will be created as expected.
If it **is** there already, I get the following error:
```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "error": 415,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": "~/dev/devops/ansible/output/kubeconfig.yml",
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json\",\"reason\":\"UnsupportedMediaType\",\"code\":415}\\n'",
    "reason": "Unsupported Media Type",
    "status": 415
}
```

The full output using `-vvvv` is:
```
File lookup using ~/dev/devops/ansible/./templates/cluster-issuer.yml.j2 as file
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: daveneary
<127.0.0.1> EXEC /bin/sh -c 'echo ~daveneary && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265 `" && echo ansible-tmp-1535977156.287988-123487823862265="` echo ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265 `" ) && sleep 0'
Using module file ~/envs/devops/lib/python3.6/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT ~/.ansible/tmp/ansible-local-121657wyr9hqj/tmp0r4wlkek TO ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265/ ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '~/envs/devops/bin/python ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r ~/.ansible/tmp/ansible-tmp-1535977156.287988-123487823862265/ > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "error": 415,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": "~/dev/devops/ansible/output/kubeconfig.yml",
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json\",\"reason\":\"UnsupportedMediaType\",\"code\":415}\\n'",
    "reason": "Unsupported Media Type",
    "status": 415
}
```

Let me know if you need any more details, thanks a lot!
