### ISSUE TITLE
VMware: Duplicate Ethernet Entry | Cloning through vmware_guest

### ISSUE THREAD

**Issue by pratikkava1189** [ansible/ansible#45129]
##### SUMMARY
Cloning virtual machine and assigning IP address, it create duplicate entry on OS level.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

##### CONFIGURATION
[root@atlvmrhans01$]ansible-config dump --only-changed
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /opt/playbooks/.vault/.confidential

##### OS / ENVIRONMENT
Red Hat Enterprise Linux 7.5

##### STEPS TO REPRODUCE
```yaml
---
- hosts: testserver
  gather_facts: false
  connection: local
  vars_prompt:
   - name: "vsphere_hst"
     prompt: "vSphere host"
     private: no
   - name: "vsphere_user"
     prompt: "vsphere_user"
     private: no
   - name: "vsphere_password"
     prompt: "vSphere Password"
   - name: "guest_name"
     prompt: "guest_name"
     private: no
   - name: "guest_ip"
     prompt: "guest_ip"
     private: no
   - name: "guest_gw"
     prompt: "guest_gw"
     private: no
   - name: "guest_cpu"
     prompt: "guest_cpu"
     private: no
   - name: "guest_mem"
     prompt: "guest_mem"
     private: no
   - name: "guest_hostname"
     prompt: "guest_hostname"
     private: no
   - name: "notes"
     prompt: "VM notes"
     private: no
     default: "Deployed with ansible"
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: '{{ vsphere_hst }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      cluster: DC
      datacenter: 'DC01'
      folder: Folder/LINUX/
      name: '{{ guest_name }}'
      state: poweredon
      annotation: "{{ notes }} - {{ creationdate }}"
      hardware:
        memory_mb: '{{ guest_mem }}'
        num_cpus: '{{ guest_cpu }}'
      disk:
       - size_gb: 60
         type: thin
         datastore: Datastore01
       - size_gb: 300
         type: thin
         datastore: Datastore01
      networks:
      - name: VLAN
        type: static
        ip: '{{ guest_ip }}'
        netmask: 255.255.254.0
        gateway: '{{ guest_gw }}'
        dns_servers:
        - 192.168.2.23
        - 192.168.2.24
        start_connected: true
      customization:
        dns_servers:
        - 192.168.2.24
        - 192.168.2.23
        domain : test.domain.com
        hostname: '{{ guest_name }}'
      template: templateserver
      wait_for_ip_address: yes
```
##### EXPECTED RESULTS
If ethernet is assigned to VM template, cloning vm should not assigned duplicate ethernet on OS level.

##### ACTUAL RESULTS
NA
