### ISSUE TITLE
na_ontap_gather_facts fails on NetApp MetroCluster systems

### ISSUE THREAD

**Issue by Matthias-Beck** [ansible/ansible#45136]
##### SUMMARY

When gathering system information from a MetroCluster System, the module fails. On non MetroCluster systems it works.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

na_ontap_gather_facts
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/ansible2.6/lib/python2.7/site-packages/ansible
  executable location = /home/centos/ansible2.6/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

Ontap 9.3P6

##### STEPS TO REPRODUCE

Run the module against a NetApp MetroCluster system

```yaml
---

- name: Get Aggregates
  hosts: localhost
  connection: local


  vars:
      netapp_username: admin
      netapp_cluster: <fqdn_of_netapp_cluster>

  vars_prompt:
   - name: "netapp_password"
     prompt: "Cluster Password"


  tasks:
  - name: Test_gather
    na_ontap_gather_facts:
      state: "info"
      https: true
      validate_certs: false
      hostname: "{{ netapp_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - debug:
       msg: "{{ ontap_facts | dict2items }}"
```

##### EXPECTED RESULTS

Gather all facts from the system like from a non metrocluster system

##### ACTUAL RESULTS

```
TASK [Test_gather] **************************************************************************************************************************************************************************************************************************
task path: /git/devel/gather_system.yml:21
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936 `" && echo ansible-tmp-1536039256.01-6248969617936="` echo /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936 `" ) && sleep 0'
Using module file /home/centos/ansible2.6/lib/python2.7/site-packages/ansible/modules/storage/netapp/na_ontap_gather_facts.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-26695H5a1l7/tmpw3CAow TO /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936/na_ontap_gather_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936/ /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936/na_ontap_gather_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/centos/ansible2.6/bin/python /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936/na_ontap_gather_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1536039256.01-6248969617936/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py", line 295, in <module>
    main()
  File "/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py", line 289, in main
    g = v.get_all()
  File "/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py", line 199, in get_all
    query={'max-records': '1024'}
  File "/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py", line 156, in get_generic_get_iter
    unique_key = ':'.join([_finditem(d, el) for el in field])
TypeError: sequence item 1: expected string or Unicode, NoneType found

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py\", line 295, in <module>\n    main()\n  File \"/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py\", line 289, in main\n    g = v.get_all()\n  File \"/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py\", line 199, in get_all\n    query={'max-records': '1024'}\n  File \"/tmp/ansible_eHzOnQ/ansible_module_na_ontap_gather_facts.py\", line 156, in get_generic_get_iter\n    unique_key = ':'.join([_finditem(d, el) for el in field])\nTypeError: sequence item 1: expected string or Unicode, NoneType found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```
