### ISSUE TITLE
vmware_guest_disk_facts.py queryUUID

### ISSUE THREAD

**Issue by unkaputtbar112** [ansible/ansible#45149]
##### SUMMARY
An old problem related to VMware is identifying the disks accurately.
The SCSI-Controller/Device-ID in the vCenter doesn't match 1:1 to the scsi-address at OS-level.
I figured out, the only solid solution is to work with UUID's (set the disk.enableUUID=true in the VM-options to propagate them into OS).
But now there is the Issue, I can see the UUID on OS-Level, but to see it from vSphere/ESX-Site I would need access directly to the esx/vcenter-hosts via ssh, so I can use the powercli to run "vmkfstools -J getuuid...", unfortunately, that's not possible. 
The Rest-API from the vCenter doesn't provide me with the UUID of a *.vmdk-File either.
The only way over API is presented here:
https://code.vmware.com/docs/5722/vsphere-web-services-api-reference#/doc/vim.VirtualDiskManager.html#queryVirtualDiskUuid
And as I've seen in https://raw.githubusercontent.com/vmware/pyvmomi/master/pyVmomi/ServerObjects.py
vim.VirtualDiskManager is as object already available in pyvmomi.

So I was wondering, if it could be added within the vmware_guest_disk_facts-module, to show the UUIDs of the disks?

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/scis-taabara8/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:6379:0
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 21600
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/opt/ansible/sdiaf-ansible/inventory/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
---
- name: blah
  hosts: localhost
  gather_facts: no
  tasks:
    - name: vmfacts
      vmware_guest_disk_facts:
        datacenter: exampleDC
        name: somevm.example.com
        hostname: "somevcenter.example.com"
        username: "someuser"
        password: "somepassword"
        validate_certs: no
      register: facts

    - debug:
        var: facts
...

```

##### EXPECTED RESULTS

```
    "facts": {
        "changed": false, 
        "failed": false, 
        "guest_disk_facts": {
            "0": {
                "backing_datastore": "someDC", 
                "backing_disk_mode": "persistent", 
                "backing_eagerlyscrub": false, 
                "backing_filename": [someDC] somevm.example.com/somevm.example.com.vmdk", 
                "backing_thinprovisioned": true, 
                "backing_writethrough": false, 
                "backing_UUID": "6000c29b351af5c9c082423ade65f63e",
                "capacity_in_bytes": 34359738368, 
                "capacity_in_kb": 33554432, 
                "controller_key": 1000, 
                "key": 2000, 
                "label": "Hard disk 1", 
                "summary": "33,554,432 KB", 
                "unit_number": 0
            }, 
            "1": {
                "backing_datastore": "someDC", 
                "backing_disk_mode": "persistent", 
                "backing_eagerlyscrub": false, 
                "backing_filename": "[someDC] somevm.example.com/somevm.example.com_1.vmdk", 
                "backing_thinprovisioned": true, 
                "backing_writethrough": false, 
                "backing_UUID": "6000c29563b8b1c0c9249ac54c6c76c9",
                "capacity_in_bytes": 21474836480, 
                "capacity_in_kb": 20971520, 
                "controller_key": 1000, 
                "key": 2001, 
                "label": "Hard disk 2", 
                "summary": "20,971,520 KB", 
                "unit_number": 1
            }, 
...
```
##### ACTUAL RESULTS

```
    "facts": {
        "changed": false, 
        "failed": false, 
        "guest_disk_facts": {
            "0": {
                "backing_datastore": "someDC", 
                "backing_disk_mode": "persistent", 
                "backing_eagerlyscrub": false, 
                "backing_filename": [someDC] somevm.example.com/somevm.example.com.vmdk", 
                "backing_thinprovisioned": true, 
                "backing_writethrough": false, 
                "capacity_in_bytes": 34359738368, 
                "capacity_in_kb": 33554432, 
                "controller_key": 1000, 
                "key": 2000, 
                "label": "Hard disk 1", 
                "summary": "33,554,432 KB", 
                "unit_number": 0
            }, 
            "1": {
                "backing_datastore": "someDC", 
                "backing_disk_mode": "persistent", 
                "backing_eagerlyscrub": false, 
                "backing_filename": "[someDC] somevm.example.com/somevm.example.com_1.vmdk", 
                "backing_thinprovisioned": true, 
                "backing_writethrough": false, 
                "capacity_in_bytes": 21474836480, 
                "capacity_in_kb": 20971520, 
                "controller_key": 1000, 
                "key": 2001, 
                "label": "Hard disk 2", 
                "summary": "20,971,520 KB", 
                "unit_number": 1
            }, 
...
```

**Comment by Akasurde** [comment]
@unkaputtbar112 Thanks for reporting this feature request.

**Comment by Akasurde** [comment]
resolved_by_pr #45157

**Comment by Akasurde** [comment]
@unkaputtbar112 Could you please check above PR and let me know if it works for you ? Thanks. 

needs_info

**Comment by unkaputtbar112** [comment]
@Akasurde 
```yaml
           "0": {
                "backing_datastore": "someDC", 
                "backing_disk_mode": "persistent", 
                "backing_eagerlyscrub": false, 
                "backing_filename": "[someDC] somevm.example.com/somevm.example.com.vmdk", 
                "backing_thinprovisioned": true, 
                "backing_uuid": "6000C29b-351a-f5c9-c082-423ade65f63e", 
                "backing_writethrough": false, 
                "capacity_in_bytes": 34359738368, 
                "capacity_in_kb": 33554432, 
                "controller_key": 1000, 
                "key": 2000, 
                "label": "Hard disk 1", 
                "summary": "33,554,432 KB", 
                "unit_number": 0
            }, 
```

Works fine for me, although it's kind of strange, that he writes the "C" capital in the first block of the uuid, but I can deal with that by my own.

Thanks a lot for the quick solve, much appreciated 👍
