### ISSUE TITLE
nxos_command module truncates output of show interface status command

### ISSUE THREAD

**Issue by b0urn3** [ansible/ansible#45171]
##### SUMMARY
nxos_command module returns truncated output when running `show interface status | xml | no-more` command. Running directly from CLI results in complete output.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_command

##### ANSIBLE VERSION
```
ansible-playbook 2.6.3
  config file = /var/lib/awx/projects/_35__nxos_show/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
```
Cisco Nexus Operating System (NX-OS) Software 6.x
```

##### STEPS TO REPRODUCE

```yaml
- name: Dump interface status to XML file
  hosts: all
  gather_facts: true
  connection: local
  vars:
    show_filename: "interface_status"

  tasks:
  - name: Get the Interface status
    nxos_command:
      commands:
        -  command: "terminal length 0"
        -  command: "show interface status | xml | no-more"
           output: text
      transport: cli
      timeout: 15
    register: print_output

  - debug: var=print_output.stdout
  - name: save output to a file
    copy: content="{{ print_output.stdout[0] }}" dest="/var/tmp/ansible-working/output/interface-status/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}_{{ inventory_hostname_short }}_{{ show_filename }}.xml"
```

##### EXPECTED RESULTS
Get full output of the `show interface status | xml | no-more` command.

##### ACTUAL RESULTS
Output gets truncated to 13 lines. Example is below

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<nf:rpc-reply xmlns:nf="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="http://www.cisco.com/nxos:1.0:if_manager">
 <nf:data>
  <show>
   <interface>
    <status>
     <__XML__OPT_Cmd_show_interface_status_down>
      <__XML__OPT_Cmd_show_interface_status___readonly__>
       <__readonly__>
        <TABLE_interface>
         <ROW_interface>
          <interface>mgmt0</interface>
          <state>connected</state>%
```
