### ISSUE TITLE
tower_credential misses URL parameter for satellite6 credentials

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/ansible#45172]
##### SUMMARY

See title, the URL of the satellite server is a required field.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

tower_credential

##### ANSIBLE VERSION

```
ansible 2.7.0b1
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Being able to set/add/edit a Satellite 6 credential in Tower/AWX using the upstream module.

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AlanCoding @ghjm @jlaska @matburt @rooftopcellist @ryanpetrello @simfarm @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by AlanCoding** [comment]
Could you show the YAML for the task you're running, with passwords obfuscated?

**Comment by MarkusTeufelberger** [comment]
Sure:

```
- name: Add Foo credential
  tower_credential:
    name: Foo credential
    description: Some random credential
    kind: satellite6
    organization: Foo
    username: JohnDoe
    password: supersecret
    # satellite_6_url: https://satellite.example.com <-- this mandatory parameter is not sent to Tower!
    tower_config_file: "~/tower_cli.cfg"
```
