### ISSUE TITLE
aireos_config Does not handle `config ap group` prompts

### ISSUE THREAD

**Issue by jvanderaa** [ansible/ansible#45184]
##### SUMMARY

When attempting to set an AP group for an access point the controller will prompt are you sure that you want to reboot? (y/n). There is not a method to handle this prompt.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aireos_config

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.6.2
  config file = /Users/jvanderaa/Documents/allianz-field/ansible.cfg
  configured module search path = [u'/Users/jvanderaa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MacOS

##### STEPS TO REPRODUCE

Setup a task with aireos_config for ap group command.

```yaml
    - name: Configure access points names
      aireos_config:
        lines:
          - ap group-name <groupname> {{ item }}
      with_items: "{{ accesspoints }}"

```

##### EXPECTED RESULTS

I would expect that there is a prompt handling capability like ios_command has. I

##### ACTUAL RESULTS

The function errors and does nothing. Below is the actual prompt from the controller.

```paste below
Changing the AP's group name will cause the AP to reboot.
Are you sure you want to continue? (y/n)
```
