### ISSUE TITLE
Delegated loops do not short-circuit variable evaluation with false conditional

### ISSUE THREAD

**Issue by doubleplush** [ansible/ansible#45189]
Ordinarily, Ansible is able to short-circuit evaluation of a loop variable when the conditional associated with the task is false; however, when delegation of a loop is performed, this behavior changes; the loop variable is evaluated regardless of the conditional.  This also represents a behavior change from the older with_list loop, where the short-circuiting still occurs with delegation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
loop

##### ANSIBLE VERSION
```
ansible 2.6.3
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

also affects

```
ansible 2.8.0.dev0 (998badbda55e69413ee8b70349d782a177ddee73)
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING = True
ANSIBLE_SSH_RETRIES = 2
CACHE_PLUGIN = jsonfile
CACHE_PLUGIN_CONNECTION = ~/.ansible/tmp/facts
CACHE_PLUGIN_TIMEOUT = 1800
DEFAULT_CALLBACK_WHITELIST = ['profile_roles', 'profile_tasks', 'yaml']
DEFAULT_FORKS = 20
DEFAULT_GATHERING = smart
DEFAULT_STDOUT_CALLBACK = yaml
DEFAULT_SUDO_FLAGS = -HSn -i
DEFAULT_TIMEOUT = 4
HOST_KEY_CHECKING = False
RETRY_FILES_ENABLED = False
```

##### STEPS TO REPRODUCE
```yaml
- name: loop with false conditional
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "loop"
      when: false
      loop: "{{ fake_var }}"

- name: with_list with delegation and false conditional
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "loop"
      when: false
      delegate_to: localhost
      with_list: "{{ fake_var }}"

- name: loop with delegation and false conditional
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "loop"
      when: false
      delegate_to: localhost
      loop: "{{ fake_var }}"

```

##### EXPECTED RESULTS

In the first two plays, Ansible is able to evaluate the `when:` conditional for the block as false and short-circuits evaluation of the loop variable.  One would expect the same behavior to persist if the task is delegated to another host.  However, in the third play where the task is delegated, the short circuiting does not take place; the loop variable is evaluated, resulting in a task failure due to a non-existent variable.

##### ACTUAL RESULTS
```
PLAY [loop with false conditional] *********************************************

TASK [debug] *******************************************************************
skipping: [localhost] => 

PLAY [with_list with delegation and false conditional] *************************

TASK [debug] *******************************************************************
skipping: [localhost] => 

PLAY [loop with delegation and false conditional] ******************************
ERROR! 'fake_var' is undefined
```
