### ISSUE TITLE
`from_yaml` Parsing is problematic with datetime type

### ISSUE THREAD

**Issue by huyqut** [ansible/ansible#45199]
##### SUMMARY
`from_yaml` behavior is to convert a string of YAML format into a dictionary. However, if a value in YAML follows format of ISO Datetime, it returns an `AnsibleUnsafeText` object.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Filter `from_yaml`.

##### ANSIBLE VERSION

```paste below
2.6.3
```

##### OS / ENVIRONMENT

Fedora 28.
Ansible is insatlled via `pip`.

##### STEPS TO REPRODUCE

Playbook:
```yaml
- name: Input
  set_fact:
    yaml_content: |
      bug: ansible
      metadata:
        creationTimestamp: 2018-09-05T03:19:37Z # This line causes the problem.
        hello: world

- name: Parse
  set_fact:
    dict_var: "{{ yaml_content | from_yaml }}"

- name: Dictionary
  debug: var=dict_var

- name: Content of Dictionary
  debug: var=dict_var['metadata']
```

##### EXPECTED RESULTS

```
TASK [Input] *******************************************************************
ok: [k8s-master-1]

TASK [Parse] *******************************************************************
ok: [k8s-master-1]

TASK [Dictionary] **************************************************************
ok: [k8s-master-1] => {
    "dict_var": {
        "bug": "ansible", 
        "metadata": {
            "creationTimestamp": "2018-09-05T03:19:37Z", 
            "hello": "world"
        }
    }
}

TASK [Content of Dictionary] ***************************************************
ok: [k8s-master-1] => {
    "dict_var['metadata']": {
        "creationTimestamp": "2018-09-05T03:19:37Z", 
        "hello": "world"
    }
}
```

##### ACTUAL RESULTS

As we can see, `creationTimestamp` is converted to `datetime.datetime` type, not a `string`.

```
TASK [Input] *******************************************************************
ok: [k8s-master-1]

TASK [Parse] *******************************************************************
ok: [k8s-master-1]

TASK [Dictionary] **************************************************************
ok: [k8s-master-1] => {
    "dict_var": "{'bug': 'ansible', 'metadata': {'creationTimestamp': datetime.datetime(2018, 9, 5, 3, 19, 37), 'hello': 'world'}}"
}

TASK [Content of Dictionary] ***************************************************
ok: [k8s-master-1] => {
    "dict_var['metadata']": "VARIABLE IS NOT DEFINED!"
}
```

#### INVESTIGATION

Put a string on, it work as expected (note that sometimes I retrieve the file/content from a 3-rd party so it's not always possible to escape datetime with string double quotes):
```yaml
- name: Input
  set_fact:
    yaml_content: |
      bug: ansible
      metadata:
        creationTimestamp: "2018-09-05T03:19:37Z"
        hello: world

- name: Parse
  set_fact:
    dict_var: "{{ yaml_content | from_yaml }}"

- name: Dictionary
  debug: var=dict_var

- name: Content of Dictionary
  debug: var=dict_var['metadata']
```

Current work around is to convert to JSON and then convert back to dictionary:

```yaml
- name: Parse
  set_fact:
    dict_var: "{{ yaml_content | from_yaml | to_json | from_json }}"
```
