### ISSUE TITLE
Variables in dependencies wins precedent in play

### ISSUE THREAD

**Issue by ephracis** [ansible/ansible#45192]
##### SUMMARY

When a play includes a role that is also included via a dependency, the variables are overwritten by the dependent role.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
ansible 2.5.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE

```yaml
# roles/role1/tasks/main.yml
- debug: var=myvar

# roles/role2/tasks/main.yml
dependencies:
  - role: role1
    vars:
      myvar: set by role2

# roles/role2/meta/main.yml
- debug: var=myvar

# playbook.yml
- hosts: localhost
   connection: local
   gather_facts: no
   vars:
     myvar: set by playbook
   roles:
   - role1
   - role2
```

##### EXPECTED RESULTS

```
TASK [role1 : debug] ***************************************************
Tuesday 04 September 2018  21:36:27 +0200 (0:00:00.149)       0:00:00.149 ***** 
ok: [localhost] => {
    "myvar": "set by playbook"
}

TASK [role1 : debug] ***************************************************
Tuesday 04 September 2018  21:36:28 +0200 (0:00:00.061)       0:00:00.210 ***** 
ok: [localhost] => {
    "myvar": "set by role2"
}

TASK [role2 : debug] ***************************************************
Tuesday 04 September 2018  21:36:28 +0200 (0:00:00.054)       0:00:00.265 ***** 
ok: [localhost] => {
    "myvar": "set by playbook"
}
```

##### ACTUAL RESULTS

```
TASK [role1 : debug] ***************************************************
Tuesday 04 September 2018  21:36:27 +0200 (0:00:00.149)       0:00:00.149 ***** 
ok: [localhost] => {
    "myvar": "set by role2"
}

TASK [role1 : debug] ***************************************************
Tuesday 04 September 2018  21:36:28 +0200 (0:00:00.061)       0:00:00.210 ***** 
ok: [localhost] => {
    "myvar": "set by role2"
}

TASK [role2 : debug] ***************************************************
Tuesday 04 September 2018  21:36:28 +0200 (0:00:00.054)       0:00:00.265 ***** 
ok: [localhost] => {
    "myvar": "set by role2"
}
```
