### ISSUE TITLE
mysql_user does not set empty passwords

### ISSUE THREAD

**Issue by jadbaz** [ansible/ansible#45207]
##### SUMMARY
`mysql_user` module does not set empty passwords (tried with both root and non-root users).
This should have been solved in [ansible-modules-core/pull/3445](https://github.com/ansible/ansible-modules-core/pull/3445) (though the exact wording of the PR is "when adding a **new** MySQL user"
The module works with any other password, except the empty password.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = /home/vagrant/vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/vagrant/vagrant/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/vagrant/vagrant/ansible.cfg) = -o ControlMaster=no -o UserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -o IdentitiesOnly=yes
DEFAULT_HOST_LIST(/home/vagrant/vagrant/ansible.cfg) = [u'/home/vagrant/vagrant/env/aws']
DEFAULT_TIMEOUT(/home/vagrant/vagrant/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/vagrant/vagrant/ansible.cfg) = False
```

##### OS / ENVIRONMENT

- OS: Red Hat Enterprise Linux Server release 6.9 (Santiago)
- Python: 2.6.6
- MySQL: Ver 14.14 Distrib 5.5.37, for Linux (x86_64) using readline 5.1
- MySQL-python: MySQL-python-1.2.3-0.3.c1.1.el6.x86_64

##### STEPS TO REPRODUCE

playbook.yml
```yaml
- hosts: all
  tasks:
  - name: Changing default root password
    become: true
    mysql_user:
      name: root
      host: "localhost"
      password: ""
      check_implicit_admin: yes
      login_user: "root"
      login_password: "{{mysql_old_root_pass}}"
      state: present
```

Run:
```ansible-playbook playbook.yml```

##### EXPECTED RESULTS

Guest command: `echo "select 1" | mysql -u root | head -n1`
Result: `1`

##### ACTUAL RESULTS

The Ansible step runs with no errors:
```
TASK [playbook: Changing default root password] *******************************************************************
ok: [all]
```

However, nothing is actually changed on the server

Guest command: `echo "select 1" | mysql -u root | head -n1`
Result:
```paste below
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/mysql/mysql_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Jmainguy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jadbaz** [comment]
While waiting for this to be resolved, I used a simple shell command instead:
```yaml
- name: Changing default root password
  become: true
  shell: "echo \"SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');\" | mysql -u root -p{{mysql_old_root_pass}}"
```
