### ISSUE TITLE
NIOS race condition with next available iP

### ISSUE THREAD

**Issue by michaelhajjar** [ansible/ansible#45218]
##### SUMMARY

We are using the NIOS module for provisioning ip adresses in Infoblox. We have a race condition when multiple users try to provision a ip adres, both A/host records get registered on the same ip adres.  Issue is the same as: https://community.infoblox.com/t5/DNS-DHCP-IPAM/Simultaneous-requests-for-next-available-IP/td-p/6617

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios
##### ANSIBLE VERSION

```paste below
ansible 2.6.3
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

```yaml
- name: Register host record in infoblox
  nios_host_record:
    name: "{{ fqdn }}"
    ipv4addrs:
      - ipv4addr: "{{ lookup('nios_next_ip',  192.168.2.0/24, provider={'host': infoblox_host, 'username': infoblox_username, 'password': infoblox_password, 'wapi_version': infoblox_wapi_version, 'http_request_timeout': 30})[0] }}"
    provider:
      host: "{{ infoblox_host }}"
      username: "{{ infoblox_username }}"
      password: "{{ infoblox_password }}"
      wapi_version: "{{ infoblox_wapi_version }}"
    comment: Created with Ansible
    view: "{{ infoblox_view }}"
    state: present
  when: fqdn is defined

```

##### EXPECTED RESULTS

Each host record gets its own ip adres

##### ACTUAL RESULTS

host records get registered on the same ip adres

```paste below

```
