### ISSUE TITLE
vmware_guest.py adding option to modify the advanced vm-options

### ISSUE THREAD

**Issue by unkaputtbar112** [ansible/ansible#45213]
##### SUMMARY
Adding option to modify VM-advanced-options/*.vmx-File.
At the moment it's only possible to modify the "customvalues", it would be great to be able to modify the advanced vm-options as well.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest

##### ADDITIONAL INFORMATION

It should be possible with pyVmomi using vim.VirtualMachine.ReconfigVM_Task.
[https://imgur.com/a/KbU5fTC]
I don't know how hard it is to implement that for a already existing VM, but if not for that, it would already be great for VM creation.

```yaml

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @unkaputtbar112,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@unkaputtbar112 Thanks for reporting this issue. I am not sure if I understand this correctly. As per my understanding you want to update configuration which can be done using `customvalues`, like following - 

```yaml
    - name: Deploy VM with custom value
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        state: present
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
        networks:
          - name: "{{ network }}"
        disk:
          - size: 10mb
            datastore: "{{ datastore }}"
        guest_id: "{{ guest_id }}"
        hardware:
          num_cpus: 1
          memory_mb: 512
        customvalues:
          - key: hpet0.present
            value: 'FALSE'
```

Correct me if I am wrong. Thanks. 

needs_info
