### ISSUE TITLE
Ansible Vault should be able to specify the vault password in an environment variable

### ISSUE THREAD

**Issue by gtmtech** [ansible/ansible#45214]
##### SUMMARY

Allow an environment variable to be set, e.g. ANSIBLE_VAULT_PASSWORD which if set will be tried to unlock any vault-encrypted secrets

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Ansible Vault / vault password environment variable

##### ADDITIONAL INFORMATION
Currently vault encrypted secrets require that:

*  `--ask-vault-password` be specified which makes it interactive and non-automatable without using something like expect OR
* `--vault-password-file` be used which violates compliance (Most security compliance require that passwords are not written down in files in plaintext anywhere, even temporarily).

Of the three other (simple) ways of getting information into a system, STDIN (through a pipe), commandline args, and environment variables:

* STDIN abstracts the problem to another tool, but is a horrible solution an you only get one STDIN to play with.
* Commandline args are visible in the process tree so is no good for security purposes
* Environment variables are secure (can only be read by user and root, like the memory itself), and provide an ideal mechanism for setting a password for automatation purposes. 

It would be great if ansible vault could therefore support an env var such as ANSIBLE_VAULT_PASSWORD which a user could set through whatever means they choose, to supply ansible with the vault password to decrypt the secrets at runtime.

I'm not sure why the file methods was chosen as this undoes the work of ansible-vault in encrypting data at rest, by providing the password in data at rest. If therefore my disk is accessed or my machine is stolen, someone gains the passwords anyway. 

See for example "Passwords or pass phrases must not be written down or stored in readable format." in the wikipedia version of https://en.wikipedia.org/wiki/ISO/IEC_27002

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)
* [lib/ansible/parsing/vault](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MarkusTeufelberger** [comment]
`--vault-password-file` can also be a script (that would also be able to read environment variables).

**Comment by zasca** [comment]
> `--vault-password-file` can also be a script (that would also be able to read environment variables).

Yes, but passing a password without wrapper script is a more elegant and simple way.

**Comment by MarkusTeufelberger** [comment]
I agree. Accessing the environment variable via a script however is an easy workaround that you can use in the meantime (see the commit above) until someone implements this.

**Comment by zimmertr** [comment]
This would be a nice feature to have.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/parsing/vault](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hidekuro** [comment]
LGTM.
For better security, the secrets should not be written out to the file system.

**Comment by geerlingguy** [comment]
I'd also like to see this—for example, when you need to run a playbook in a quick container that's built in a Kubernetes environment, it's super easy to toss in an environment variable for the vault password, and a little more annoying to have to mount a file from a K8s secret.

**Comment by bcoca** [comment]
just create a script:

```
!#/bin/bash
echo ${MY_SECRET}
```
And point to it with `--vault-password-file `

**Comment by geerlingguy** [comment]
But then I have to store the script somewhere, and modify the way I call the playbook. If ansible evaluates the script then that solution is nice... but still not as elegant in making Ansible more “12-factor”-ish

**Comment by hidekuro** [comment]
@geerlingguy There is no problem.

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
type: Opaque
data:
  vault-password: c3VwZXJzZWNyZXQ= # "supersecret"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-cfg
data:
  ansible.cfg: |
    [defaults]
    vault_password_file=/mnt/vault-secret/vault-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: vault-secret-volume
          secret:
            secretName: vault-secret
        - name: ansible-cfg-volume
          configMap:
            name: ansible-cfg
      containers:
      - name: myapp
        image: alpine
        command: ["cat", "/mnt/vault-secret/vault-password"] # shown "supersecret"
        env:
          - name: ANSIBLE_CONFIG
            value: /mnt/ansible-cfg/ansible.cfg
        volumeMounts:
          - name: vault-secret-volume
            mountPath: /mnt/vault-secret
          - name: ansible-cfg-volume
            mountPath: /mnt/ansible-cfg
```

First of all, running Playbook in the k8s environment is a very special purpose. normally, containerized apps is running on immutable infrastructures.

**Comment by geerlingguy** [comment]
@hidekuro - There are a number of valid use cases for running Ansible playbooks inside k8s, including applications which may be immutable but can be used to change other resources outside the cluster—or even inside (e.g. updating deployments via other applications running playbooks in Jobs or CronJobs, that kind of thing).

Also, there is a problem—using your code I need to create and manage an ansible.cfg, and configure an additional volume, _and_ the extra env var (unless I mount into /etc/ansible/ansible.cfg... which can also be difficult or unwanted for a variety of reasons).

If Ansible would just check if `ANSIBLE_VAULT_PASSWORD` and use that if set... that would save a _ton_ of wasted/annoying boilerplate. And not just in Kubernetes clusters, but pretty much anywhere you'd want to one-shot an Ansible playbook in a container.

**Comment by pjxiao** [comment]
+1

I tried process substitution (`--vault-password-file=<(echo ${MY_PASSWORD})`) instead of `ANSIBLE_VAULT_PASSWORD`, but this didn't work (because Ansible calls `os.path.realpath()` to resolve an absolute path).

**Comment by spawnia** [comment]
A PR for this was attempted and rejected, see https://github.com/ansible/ansible/pull/64383#issuecomment-549878478

@bcoca can you elaborate on why you think using environment variables for secrets is a bad idea?

Many people in this thread (including myself) seem to think it is fine and would like the convenience of it. Many CI systems run Ansible in a temporary/short-lived environment and use environment variables as the primary method to inject secrets.

**Comment by decentral1se** [comment]
Oh god not another one of these intractable ansible core hell feature blocks...

**Comment by pySilver** [comment]
Solution proposed in PR refusal message is pretty good. Just grab example from @bcoca posted few messages above and you are good to go. Feel free to store this small executable in your repo.

**Comment by cmason3** [comment]
Storing passwords on the file system is a bad idea. I was looking for this feature so I could store the password using a GitLab Secure Variable within my CI/CD pipeline. Looking into the script option, but using a variable like ANSIBLE_VAULT_PASSWORD would be much more efficient and allow it to be stored securely.

**Comment by artis3n** [comment]
I have also come here from a GitHub Actions workflow wanting to put a secret into GitHub for CI.

Here is what I ended up doing in my Actions workflow file:

```yaml
- name: Test
      run: echo "${{ secrets.VAULT_PASS }}" > /home/runner/work/_temp/.vault-ci-pass && ANSIBLE_VAULT_PASSWORD_FILE=/home/runner/work/_temp/.vault-ci-pass pipenv run molecule test

- name: Clean up
      if: always()
      run: rm /home/runner/work/_temp/.vault-ci-pass; docker logout $DOCKER_SERVER
```

Which seems super dumb and completely unnecessary, but works. I see https://github.com/ansible/ansible/pull/64383#issuecomment-549878478 was closed  due to security concerns with having a secret in an environment variable. I would argue writing a secret to a file is worse... At the very least equivalent. `ANSIBLE_VAULT_PASSWORD` would be a good addition.
