### ISSUE TITLE
vmware_guest ignores "wait_for_ip_address" when powering on a VM

### ISSUE THREAD

**Issue by albers** [ansible/ansible#45223]
##### SUMMARY
The `vmware_guest` module can be used to power on existing, stopped virtual machines on VMware.
The module has a `wait_for_ip_address: true` option that ensures that the task does not return before an IP is allocated, allowing subsequent tasks to extract the IP from the return value and use it to connect to the machine.

This setting does not work properly. Occasionally the task returns with an undefined IP. This seems to be a timing issue: The issue occurs more likely under load conditions, e.g. when 10 vms are turned on simultaneously.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /home/user/devops/ansible/vmware/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/user/devops/ansible/vmware/ansible.cfg) = [u'/home/user/devops/ansible/vmware/inventory']
RETRY_FILES_ENABLED(/home/user/devops/ansible/vmware/ansible.cfg) = False
```

##### OS / ENVIRONMENT
vSphere Version 6.7.0, Build 8546293
VMware ESXi, 6.7.0, 8169922
VMs deployed on a ProLiant DL360 Gen9 with HDs (no SSDs)

##### STEPS TO REPRODUCE
This is flaky behaviour. Several tries might be required.

- create ten stopped VMs
- start the VMs in parallel:

```shell
$ ansible-playbook --forks=10 start-vms.yml

PLAY [Illustrate Wait For IP Issue] *******************************************************

TASK [start vm] ***************************************************************************
changed: [host-02 -> localhost]
changed: [host-09 -> localhost]
changed: [host-08 -> localhost]
changed: [host-03 -> localhost]
changed: [host-06 -> localhost]
changed: [host-04 -> localhost]
changed: [host-07 -> localhost]
changed: [host-05 -> localhost]
changed: [host-01 -> localhost]
changed: [host-00 -> localhost]

TASK [fail if ip is not available] ********************************************************
skipping: [host-00]
skipping: [host-01]
skipping: [host-03]
skipping: [host-04]
skipping: [host-05]
skipping: [host-06]
fatal: [host-02]: FAILED! => {"changed": false, "msg": "IP is not available"}
skipping: [host-09]
fatal: [host-07]: FAILED! => {"changed": false, "msg": "IP is not available"}
fatal: [host-08]: FAILED! => {"changed": false, "msg": "IP is not available"}

PLAY RECAP ********************************************************************************
host-00                    : ok=1    changed=1    unreachable=0    failed=0
host-01                    : ok=1    changed=1    unreachable=0    failed=0
host-02                    : ok=1    changed=1    unreachable=0    failed=1
host-03                    : ok=1    changed=1    unreachable=0    failed=0
host-04                    : ok=1    changed=1    unreachable=0    failed=0
host-05                    : ok=1    changed=1    unreachable=0    failed=0
host-06                    : ok=1    changed=1    unreachable=0    failed=0
host-07                    : ok=1    changed=1    unreachable=0    failed=1
host-08                    : ok=1    changed=1    unreachable=0    failed=1
host-09                    : ok=1    changed=1    unreachable=0    failed=0
```

##### start-vms.yml
```yaml
- name: Illustrate Wait For IP Issue
  hosts: all
  gather_facts: no

  tasks:
    - name: start vm
      vmware_guest:
        datacenter: your-datacenter
        name: "{{ inventory_hostname }}"
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost
      register: started

    - name: fail if ip is not available
      fail: msg="IP is not available"
      when: started.instance.ipv4 is none
```
##### inventory
```ini
[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
```
##### ansible.cfg (project level)
```ini
[defaults]
inventory = inventory
retry_files_enabled = False
ssh_extra_args = -o ForwardAgent=yes
```
Credentials and vcenter connection are configured via environment variables VMWARE_{HOST,USER,PASSWORD,VALIDATE_CERTS}

The sample vms were create with this snippet (this step requires Ansible 2.7)

##### create-vms.yml
```yaml
# Requires Ansible 2.7
# Assumes that the ova file was downloaded from
#   https://cloud-images.ubuntu.com/releases/18.04/release/ubuntu-18.04-server-cloudimg-amd64.ova
- name: Create Sample VMs
  hosts: all
  gather_facts: no
  tasks:
    - name: deploy OVA file
      vmware_deploy_ovf:
        datacenter: your-datacenter
        datastore: some-datastore
        allow_duplicates: no
        ova: ubuntu-18.04-server-cloudimg-amd64.ova
        name: "{{ inventory_hostname }}"
        power_on: no
      delegate_to: localhost
```
##### EXPECTED RESULTS
All task should succeed.

##### ACTUAL RESULTS
A varying percentage of failed tasks due to an unpopulated `instance.ipv4`.

##### WORKAROUND
You can work around this issue by inserting a loop that polls the module facts until the IP is populated:
##### workaround.yml
```yaml
- name: Workaround For Wait For IP Issue
  hosts: all
  gather_facts: no

  tasks:
    - name: start vm
      vmware_guest:
        datacenter: your-datacenter
        name: "{{ inventory_hostname }}"
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost

    - name: wait for ip _really_ being available
      vmware_guest_facts:
        datacenter: your-datacenter
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: facts
      until: facts.instance.ipv4 is not none
      retries: 30
      delay: 2
```
