### ISSUE TITLE
lxc_container.py container_config appends. Doens't seem to replace.

### ISSUE THREAD

**Issue by cocampbe** [ansible/ansible#45230]
##### SUMMARY
For lxc_container.py I would request that the container_config parameter would replace an existing line. In my current testing, my config file has lxc.utsname = test1. If I add this to the config:

```
container_config:
          - "lxc.utsname = test2"
```

It does not rewrite the line, It just appends after a matching entry. 

##### ISSUE TYPE
Parse the config and change/replace the existing parameter. Don't append after the match. By doing this, if you make changes over time, you just get useless lines in your config. Possibly, it might make sense to have another parameter called modify_config. This parameter could be used to modify existing config lines. 

##### COMPONENT NAME
lxc_container.py 

##### ADDITIONAL INFORMATION
The container_config  =parameter should change existing config parameters. For instance, I switchover containers to run from a DR site. I need to change the IP and gateway. If I do this multiple times over a year, I will end up with quite a few extra lines in my config. 

```
---
- hosts: container_host
  gather_facts: no
  become: yes
  tasks:
    - name: modify container
      lxc_container:
        name: test99
        state: stopped
        container_config:
          - "lxc.utsname = test_newname"
          - "lxc.network.link = bond2"
```
