### ISSUE TITLE
ios_facts config causing next task to fail

### ISSUE THREAD

**Issue by Bciecko** [ansible/ansible#45247]
##### SUMMARY

Running playbook ios_facts: gather_subset: config is causing the next task to run to fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/239298/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Running Ansible from Terminal of MacBook Pro running High Sierra 10.13.6 
Target device is Cisco 4331 Router:
Cisco IOS XE Software, Version 03.15.03.S - Standard Support Release
isr4300-universalk9.03.15.03.S.155-2.S3-std.SPA.bin

##### STEPS TO REPRODUCE

Run the playbook below targeting a Cisco 4331 Router.
TASK [IOS facts collection] completes "ok", but TASK [Misc Task 2] then hangs indefinitely. (even though this is only a debug message that completed fine before ios_facts) Changing the ios_facts gather_subset to interfaces or hardware executes as expected.

```yaml
---

- name: Get IOS Facts
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:

    - name: Misc Task 1
      debug:
        msg: "Some text."

    - name: IOS facts collection 
      ios_facts:
        gather_subset:
          config
 
    - name: Misc Task 2
      debug:
        msg: "Some text."
 
```

##### EXPECTED RESULTS

Display "Some text.", gather ios_facts, display "Some text."

##### ACTUAL RESULTS

Displayed "Some text.", gathered ios_fatcs, hangs indefinitely on next TASK (let run for 15+ minutes before breaking with ctrl+z)

```paste below
LC02VF234G8WL:~ 239298$ ansible-playbook -i hosts.ini -u admin -k print_ios_facts_config.yaml 
SSH password: 

PLAY [Get IOS Facts] ****************************************************************************************************************************************

TASK [Misc Task 1] ******************************************************************************************************************************************
ok: [10.130.62.2] => {
    "msg": "Some text."
}

TASK [IOS facts collection] *********************************************************************************************************************************
ok: [10.130.62.2]

TASK [Misc Task 2] ******************************************************************************************************************************************
^Z
[1]+  Stopped                 ansible-playbook -i hosts.ini -u admin -k print_ios_facts_config.yaml
```
