### ISSUE TITLE
Ansible `unique` filter shadows Jinja2 `unique` filter

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#45286]
##### SUMMARY
[Ansible `unique` filter](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_filters.html#set-theory-filters) shadows [Jinja2 `unique` filter](http://jinja.pocoo.org/docs/2.10/templates/#unique).

This is pretty annoying because the Jinja2 filter offers useful options (`case_sensitive=False, attribute=None`) not offered by the Ansible filter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unique filter

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
- template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ custom_templates + default_templates | unique(attribute='dest') }}"
```

##### EXPECTED RESULTS
No error.

##### ACTUAL RESULTS
> `An unhandled exception occurred while templating '{{ (custom_templates + default_templates) | unique(attribute='dest') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ (custom_templates + default_templates) | unique(attribute='dest') }}): unique() got an unexpected keyword argument 'attribute'`
