### ISSUE TITLE
junos_* state: present not idempotent 

### ISSUE THREAD

**Issue by AngelFreak** [ansible/ansible#45289]
##### SUMMARY
When running my role to setup a Juniper device, in this case EX2300, the play always reports Changed when using connection: netconf, and the end result state is present.

If the end result state is absent, it works grat.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/lib/ansible/modules/network/junos

##### ANSIBLE VERSION

```paste below
ansible 2.6.3
python version = 2.7.15 (default, Jul 16 2018, 08:54:52) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_ASK_VAULT_PASS(/home/angelfreak/gitworld/jix/infra/ansible/network/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/angelfreak/gitworld/jix/infra/ansible/network/ansible.cfg) = [u'/home/angelfreak/gitworld/jix/infra/ansible/network/jix_junos_inv']
DEFAULT_ROLES_PATH(/home/angelfreak/gitworld/jix/infra/ansible/network/ansible.cfg) = [u'/home/angelfreak/gitworld/jix/infra/ansible/network/roles']
HOST_KEY_CHECKING(/home/angelfreak/gitworld/jix/infra/ansible/network/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/angelfreak/gitworld/jix/infra/ansible/network/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Model: ex2300-48p
Junos: 15.1X53-D58.3
JUNOS OS Kernel 32-bit  [20180119.e26d166_builder_master]
JUNOS OS libs [20180119.e26d166_builder_master]
JUNOS OS runtime [20180119.e26d166_builder_master]
JUNOS OS time zone information [20180119.e26d166_builder_master]
JUNOS py extensions [20180204.044726_builder_junos_151_x53_d58]
JUNOS py base [20180204.044726_builder_junos_151_x53_d58]
JUNOS OS crypto [20180119.e26d166_builder_master]
JUNOS network stack and utilities [20180204.044726_builder_junos_151_x53_d58]
JUNOS libs [20180204.044726_builder_junos_151_x53_d58]
JUNOS runtime [20180204.044726_builder_junos_151_x53_d58]
JUNOS Web Management Platform Package [20180204.044726_builder_junos_151_x53_d58]
JUNOS ex libs [20180204.044726_builder_junos_151_x53_d58]
JUNOS ex runtime [20180204.044726_builder_junos_151_x53_d58]
JUNOS ex platform support [20180204.044726_builder_junos_151_x53_d58]
JUNOS modules [20180204.044726_builder_junos_151_x53_d58]
JUNOS ex modules [20180204.044726_builder_junos_151_x53_d58]
JUNOS Data Plane Crypto Support [20180204.044726_builder_junos_151_x53_d58]
JUNOS mtx Data Plane Crypto Support [20180204.044726_builder_junos_151_x53_d58]
JUNOS daemons [20180204.044726_builder_junos_151_x53_d58]
JUNOS Packet Forwarding Engine Support (EX34XX) [20180204.044726_builder_junos_151_x53_d58]
JUNOS jdocs ex [20180204.044726_builder_junos_151_x53_d58]
JUNOS jail runtime [20180119.e26d166_builder_master]
JUNOS FIPS mode utilities [20180204.044726_builder_junos_151_x53_d58]

##### STEPS TO REPRODUCE

Run a role from a role like shows below, on the described hardware.

```yaml
setup_ex.yml
---
- name: Create and apply EX configuration
  hosts: ux-ji-nfv-4-10
  connection: netconf
  gather_facts: no

  roles:
    - jix.junos

roles/jix.junos/tasks/main.yml
- name: Collect default set of facts and configuration
  junos_facts:
    gather_subset: config

- name: Configure the login banner
  junos_banner:
   banner: login
   text: |
     --------------------------------------------------
     WARNING: Unauthorized access is prohibited.
     This switch is managed and owned by COMPANY.
     Authorized personnel only!.
     --------------------------------------------------
   state: present
```

##### EXPECTED RESULTS

On the second run i expect all OK's

TASK [jix.junos : Collect default set of facts and configuration] *******************************************************************************************
ok: [sw1a4-nfv]

TASK [jix.junos : Configure the login banner] ***************************************************************************************************************
ok: [sw1a4-nfv]

##### ACTUAL RESULTS

On the second run i get Changed

Role run with --diff

```paste below
TASK [jix.junos : Collect default set of facts and configuration] *******************************************************************************************
ok: [sw1a4-nfv]

TASK [jix.junos : Configure the login banner] ***************************************************************************************************************
[edit system login]
-   message "--------------------------------------------------\nWARNING: Unauthorized access is prohibited.\nThis switch is managed and owned by COMPANY.\nAuthorized personnel only!.\n--------------------------------------------------";
+   message "--------------------------------------------------\nWARNING: Unauthorized access is prohibited.\nThis switch is managed and owned by COMPANY.\nAuthorized personnel only!.\n--------------------------------------------------";
changed: [sw1a4-nfv]

```
