### ISSUE TITLE
win_iss* modules don't work well in parallel

### ISSUE THREAD

**Issue by crossan007** [ansible/ansible#45291]
##### SUMMARY
When configuring multiple IIS sites and app pools on the same server, these actions fail when attempted in parallel.

the `win_iis_website` and `win_iis_webapppool` will fail when run in parallel with this error:

> Cannot commit configuration changes because the file has changed on disk

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_iis_website
win_iis_webapppool

##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### STEPS TO REPRODUCE

```yaml
hosts:
  apphost1-instance1:
    ansible_host: "host1.local"
    app-name: "app1.apphost.com"
  apphost1-instance2:
    ansible_host: "host1.local"
    app-name: "app2.apphost.org"

tasks:
  - name: "Ensure IIS Application Pool exists"
    win_iis_webapppool:
    name: "{{ app-name}}"
    state: present
    attributes:
      managedRuntimeVersion: v4.0
      autoStart: true
      processModel.identityType: SpecificUser
      processModel.userName: 'SomeUsername'
      processModel.password: 'SomePassword''
      processModel.loadUserProfile: False
      processModel.idleTimeout: 300
      enable32BitAppOnWin64: false
      managedPipelineMode: 'Integrated'

```

##### EXPECTED RESULTS

I expect two IIS web app pools to  be created on `host1.local` with different names

##### ACTUAL RESULTS

Whichever "application host instance" is executed "second" in parallel execution mode will fail, since the first one to execute wins a lock/update on the IIS config.  The second "application host instance" will fail, since it was started _slightly after_ the first, and is unable to commit the changes to the IIS config:
```
"msg": "Failed to create new Web App Pool app1.apphost.com: Filename: \\\\?\\C:\\windows\\system32\\inetsrv\\config\\applicationHost.config\r\nError: Cannot commit configuration changes because the file has changed on disk\r\n\r\n",
```
