### ISSUE TITLE
azure_rm_containerregistry idempotence bug

### ISSUE THREAD

**Issue by yungezz** [ansible/ansible#45330]
##### SUMMARY

azure_rm_containerregistry not idemptotence.

run sample task such as below, always showed 'changed'
```
    - name: Create Azure Container Registry
      azure_rm_containerregistry:
        resource_group: "{{ resource_group }}"
        name: "{{ registry_name}}"
        admin_user_enabled: True
        sku: Standard
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.6.3
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
