### ISSUE TITLE
Virtual Machine module - images not idempotent

### ISSUE THREAD

**Issue by zikalino** [ansible/ansible#45335]
##### SUMMARY
When executing following playbook:

```
- hosts: localhost
  tasks:
    - name: Create a VM with a custom image from a particular resource group
      azure_rm_virtualmachine:
        resource_group: ansiblefestrg
        name: vmfromimagexxxx
        vm_size: Standard_DS1_v2
        admin_username: adminUser
        admin_password: paSSword01!!
        image:
          name: ansiblefestvmimage
        tags:
          aaaa: bbbb
       
    - name: Idempotence test #1
      azure_rm_virtualmachine:
        resource_group: ansiblefestrg
        name: vmfromimagexxxx
        vm_size: Standard_DS1_v2
        admin_username: adminUser
        admin_password: paSSword01!!
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest
        tags:
          aaaa: bbbb
       ```

Second task will not cause any change.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
2.7

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
Second task causes VM to be updated

##### ACTUAL RESULTS
No update recorded
