### ISSUE TITLE
Async : "async task did not complete within the requested time"

### ISSUE THREAD

**Issue by Ankur012** [ansible/ansible#45336]
##### SUMMARY
 I have a task, where I need to run shell command which takes 22-25 min to execute after that it reboots the system. when playbook runs a command, successfully reboot the system but after some time its gives the error " async task did not complete within the requested time"
Note: Target system is SUSE 11.3

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
async

##### ANSIBLE VERSION

```paste below
ansible 2.6.3
  config file = /root/ankur/upaas-ansible-ag186091-pre-install/upaas/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

DEFAULT_CALLBACK_WHITELIST(/root/ankur/upaas-ansible-ag186091-pre-install/upaas/ansible.cfg) = ['timer', 'profile_tasks', 'skippy', 'full_skip']
DEFAULT_STDOUT_CALLBACK(/root/ankur/upaas-ansible-ag186091-pre-install/upaas/ansible.cfg) = skippy
DEPRECATION_WARNINGS(/root/ankur/upaas-ansible-ag186091-pre-install/upaas/ansible.cfg) = False
HOST_KEY_CHECKING(/root/ankur/upaas-ansible-ag186091-pre-install/upaas/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Ubuntu 16.10

##### STEPS TO REPRODUCE

```yaml
- name: Task | swupgrade execution started on new {{ component_name }} system
  command:  sudo -i  /opt/bin/swupgrade -U {{ component_name }}-{{ to_version }}.tar
  async: 1800
  poll: 5
  ignore_errors: yes


- name: Wait for SSH to come up
  local_action:
    module: wait_for
    host: "{{ inventory_hostname  }}"
    port: 22
    delay: 5
    timeout: 720
    state: started
  register: ssh_up
  ignore_errors: yes
```

##### ACTUAL RESULTS

TASK [install-application-bg : Task | swupgrade execution started on new DSC] ***********************************************************************************************************************************
Friday 07 September 2018  05:50:59 +0000 (0:00:00.032)       0:01:54.859 ******
fatal: [10.52.2.71]: FAILED! => {"changed": false, "msg": "async task did not complete within the requested time"}
...ignoring

TASK [install-application-bg : Wait for SSH to come up] *********************************************************************************************************************************************************
Friday 07 September 2018  07:15:32 +0000 (1:24:32.357)       1:26:27.217 ******
ok: [10.52.2.71 -> localhost]

```paste below

```
