### ISSUE TITLE
nxos_interface_ospf issues 

### ISSUE THREAD

**Issue by dmurarasu** [ansible/ansible#45343]
##### SUMMARY

1. Check mode does not work and the module pushes the changes.  

2. When using passive_interface parameter it does not work to add "no ip ospf passive-interface" unless you first configure the interface with "ip ospf passive-interface". 
If you are trying to just have "passive-interface default" under the ospf process and just do a "no ip ospf passive-interface" under the interfaces using this module that doesn't work as you'd need to first need to add "ip ospf passive-interface" for each interface.  
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_interface_ospf

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 3034709df0) last updated 2018/09/04 16:05:07 (GMT +000)
  config file = /home/vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/lib/ansible
  executable location = /home/vagrant/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ansible Server: Ubuntu 5.4.0-6ubuntu1~16.04.10
Device: N9K running NXOS: version 7.0(3)I6(1)
##### STEPS TO REPRODUCE

```yaml
- hosts: sws
  name: Configure sw
  connection: network_cli
  tasks:
    - name: ospf passive test
      nxos_interface_ospf:
        interface: Ethernet1/30
        ospf: prod
        area: 0.0.0.0
        state: present
        passive_interface: no
```

##### EXPECTED RESULTS

Expected to "no ip ospf passive-interface" to be configured on the interface.
Expected no config if playbook run in check mode. 

##### ACTUAL RESULTS

PLAY [Configure sw] **********************************************************************************************

TASK [ospf passive test] ***********************************************************************************************
changed: [sw1] => {"changed": true, "commands": ["interface Ethernet1/30", "ip router ospf prod area 0.0.0.0"]}

PLAY RECAP *************************************************************************************************************
sw1           : ok=1    changed=1    unreachable=0    failed=0

```paste below

```
