### ISSUE TITLE
github_release: Allow anonymous access

### ISSUE THREAD

**Issue by adamantike** [ansible/ansible#45391]
##### SUMMARY
The current `github_release` module implementation takes either a GitHub token or user/password to authenticate with GitHub.

However, a common scenario is to retrieve the latest release tag for a public repository, and use it to build the GitHub URL to the installer/executable for that release. In these scenarios, authenticating with GitHub shouldn't be required at all.

The library used by the `github_release` module already [supports anonymous access](https://github3.readthedocs.io/en/master/api-reference/api.html#anonymous-functions).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
github_release

##### ADDITIONAL INFORMATION
The following example doesn't work as currently it requires an authentication method to be provided:

```yaml
- name: Get latest release tag for ansible/ansible
  github_release:
    user: ansible
    repo: ansible
    action: latest_release
```
```
FAILED! => {"changed": false, "msg": "one of the following is required: password, token"}
```

However, this code snippet in Python works as intended for an anonymous caller, and uses the same Python library as the `github_release` module:

```python
>>> import github3
>>> gh_obj = github3.GitHub()
>>> repository = gh_obj.repository('ansible', 'ansible')
>>> repository.latest_release().tag_name
'v2.2.1.0-0.3.rc3'
```

We need to decide if anonymous access must be specified explicitly or implicitly. If we go with explicit anonymous usage, we could allow a notation like:
```yaml
- name: Get latest release tag for ansible/ansible
  github_release:
    user: ansible
    repo: ansible
    anonymous: yes
    action: latest_release
```
However, we can use anonymous usage when neither `token` nor `password` parameter is provided.
