### ISSUE TITLE
password_hash fails with passlib exception

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible#45392]
##### SUMMARY
Due to https://github.com/ansible/ansible/commit/7871027c9daa534517821509dfa0501b6df4dbc2 password_hash fails with following error : 

```
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ sample | password_hash('msdcc') }}): user must be unicode or bytes, not None"}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/utils/encrypt.py

##### ANSIBLE VERSION

```paste below
Stable-2.7
```

##### CONFIGURATION

Nothing specific

##### OS / ENVIRONMENT

RHEL7 

##### STEPS TO REPRODUCE

Run following playbook - 

```yaml
---
- name: Test Algorithm
  hosts: localhost
  vars:
    - sample: 'some'
  tasks:
    - debug:
        msg: "{{ sample | password_hash('msdcc') }}"
```

##### EXPECTED RESULTS

I am aware that 'msdcc' is not supported algorithm for password_hash function, but `_hash` function should raise warning rather than failing with passlib exception.

##### ACTUAL RESULTS
```
TASK [debug] *******************************************************************************************************************
task path: /Volumes/data/src/ansible/playbooks/vmware_related/algo.yml:7
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ sample | password_hash('msdcc') }}): user must be unicode or bytes, not None"
}

```
