### ISSUE TITLE
Docker swarm service network id lookup returns 'None'

### ISSUE THREAD

**Issue by FriedCircuits** [ansible/ansible#45408]
##### SUMMARY

On the dev branch using the docker_swarm_service module to create a docker service with a custom overlay network ansible returns "Exception: no docker networks named"

After hours of head scratching I figured out how to save the generated python and explode it.
 I did some debugging on the following line

https://github.com/ansible/ansible/blob/d6b0b61aa32450b34b9bbd99b957891b7d5a1c98/lib/ansible/modules/cloud/docker/docker_swarm_service.py#L841

Even though the contents of docker_networks has the network I am trying to set network_id is still set to None.

I found the network id and replaced the line with `network_id = "actual network id"`

and it worked as expected. 

This was with 2 different docker containers. 

My guess this also affects 2.7

https://github.com/ansible/ansible/blob/3e14a34744a271522e101024cdc285f2967acd08/lib/ansible/modules/cloud/docker/docker_swarm_service.py#L841

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_swarm_service
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 1891827dfa) last updated 2018/09/08 21:59:54 (GMT -700)
  config file = /home/username/.ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/ansible/lib/ansible
  executable location = /home/username/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/home/username/.ansible.cfg) = [u'/home/username/src/ansible/roles']
HOST_KEY_CHECKING(/home/username/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/username/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target OS is Ubuntu 18.04

##### STEPS TO REPRODUCE

Create a role/task with docker_swarm_service and add the network with a known valid already created network and it will fail with the above error.

```yaml
- name: Install traefik container
  docker_swarm_service:
    name:  traefik
    image: traefik
    restart_policy: any
    constraints:
      - node.role == manager
    args:
      - traefik
      - --api
      - --docker
      - --docker.swarmMode
    publish:
      - published_port: 80
        target_port: 80     # HTTP port
      - published_port: 8080
        target_port: 8080 # API Port
    mounts:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock:ro
      - source: /data/traefik/traefik.toml
        target: /etc/traefik/traefik.toml
      - source: /data/traefik/acme.json
        target: /acme.json
    networks:
      - network_overlay
```

##### EXPECTED RESULTS

It should create and start the service

##### ACTUAL RESULTS

Receive the error:  Exception: no docker networks named network_overlay

```paste below
TASK [docker_deploy : Install traefik container] *************************************************************************************************************************************************************************fatal: [destiny]: FAILED! => {"changed": false, "module_stderr": "Shared connection to server.domain.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/username/.ansible/tmp/ansible-tmp-1536542337.82-59700643386338/AnsiballZ_docker_swarm_service.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/username/.ansible/tmp/ansible-tmp-1536542337.82-59700643386338/AnsiballZ_docker_swarm_service.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/username/.ansible/tmp/ansible-tmp-1536542337.82-59700643386338/AnsiballZ_docker_swarm_service.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_docker_swarm_service_payload_hi5sm_rg/__main__.py\", line 1178, in <module>\r\n  File
\"/tmp/ansible_docker_swarm_service_payload_hi5sm_rg/__main__.py\", line 1172, in main\r\n  File \"/tmp/ansible_docker_swarm_service_payload_hi5sm_rg/__main__.py\", line 1107, in run\r\n  File \"/tmp/ansible_docker_swarm_service_payload_hi5sm_rg/__main__.py\", line 1000, in create_service\r\n  File \"/tmp/ansible_docker_swarm_service_payload_hi5sm_rg/__main__.py\", line 847, in generate_docker_py_service_description\r\nException: no docker networks named: network_overlay\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
