### ISSUE TITLE
vmware_guest module: Facing issues while resizing disk or restoring VM when using multiple scsi controller

### ISSUE THREAD

**Issue by sameerkasi200x** [ansible/ansible#45409]
##### SUMMARY
We have a playbook which uses vmware_guest module to create a VM. The VM is created using a VM template which has below disk layout:

SCSI0: disk1, disk2, disk3
SCSI1: disk4, disk5, disk6, disk7
SCSI2: disk8, disk9, disk10, disk11

When we restore this VM template as it is, we get a new VM as per our expectation i.e. a VM with 11 disk and disks are aligned with the above SCSI mapping as well.

But when we try to provide a custom size for each of the disks, we end up with a VM which has 12 disks as per below spec:

SCSI0: disk1, disk2, disk3, disk4
SCSI1: disk5, disk6, disk7, disk8
SCSI2: disk9, disk10, disk11, disk12

Disk4 above is added using the 8th disk from our disk list hash map that we pass to the vmware_guest module. 8th item in our disk list is passed to disk12, 9th item to disk8, 10th item to disk9, 11th item to disk10 and disk11 is left to its original size.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
Version 2.4

##### OS / ENVIRONMENT
Red Hat 7.3

##### STEPS TO REPRODUCE
```
Task calling vmware_guest module:

- name: Create a Virtual Machine
  vmware_guest:
    validate_certs: False
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    #cluster: "{{ cluster }}"         #### Commented because a bug in 2.4 does not allow us to use cluster
    esxi_hostname: "{{ esxi_host }}"
    datacenter: "{{ vmdatacenter }}"
    guest_id: "rhel7_64Guest"
    name: "{{ vmhost }}"
    template: "{{ vm_template }}"
    linked_clone: no
    folder: "{{ vmfolder }}"
    disk: "{{ vm_disk_list }}"
    networks:
      - name: "{{ vmnetwork }}"
        ip: "{{ vm_ipaddr }}"
        netmask: "{{ netmask }}"
        gateway: "{{ vmgateway }}"
        type: "static"
        start_connected: True
    hardware:
      memory_mb: 4096
      num_cpus: 2
      memory_reservation_lock: True
      hotadd_cpu: True
      hotadd_memory: True
      hotremove_cpu: True
      cpu_reservation: 2
    wait_for_ip_address: yes
    state: restarted
  register: vm_output
```

Variable:

```vm_disk_list:
      - size_gb: 55
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 10
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 10
        type: thin
        datastore: "{{ datastore }}"

#db data disk
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"

#db transaction log disks
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"

```
##### EXPECTED RESULTS
I expect that above would create a VM with 11 disks as per sizing specified by my variables in list specified for disk.

##### ACTUAL RESULTS
I end up with 12 disks and one of the original disks which was part of the VM template does not get storage allocated as per the size specified in list variable.
