### ISSUE TITLE
Unable to add ldap entry

### ISSUE THREAD

**Issue by Saloshp** [ansible/ansible#45417]
##### SUMMARY
ldap_entry module is unusable

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ldapobject.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0rc1.post0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
[root@ha01 ~]# uname -a
Linux ha01 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
  - name: "Create LDAP entry for Jack Sparrow"
    ldap_entry:
      dn: "uid=jacksp,ou=users,dc=munio,dc=io"
      state: present
      server_uri: "ldap://localhost"
      bind_dn: "cn=administrator,dc=munio,dc=io"
      bind_pw: "<no_log>"
      objectClass:
      - inetOrgPerson
      attributes:
        description:  "LDAP user for Jack Sparrow"
        uid:          "jacksp"
        loginShell: /bin/bash
        homeDirectory: "/home/jacksp"
```

##### EXPECTED RESULTS

Expected the entry to be created, first encountered bug on latest released Ansible 2.6.4, 
after viewing a [similar bug](https://github.com/ansible/ansible/issues/39569) #39569, upgraded to 2.7rc1 to include [this pr](https://github.com/ansible/ansible/pull/41248) #41248 but still fails, 
any attributes are causing this bug, and the order of appearance does not matter

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ldap_entry_payload_te62nmht/__main__.py", line 241, in main
    action()
  File "/tmp/ansible_ldap_entry_payload_te62nmht/__main__.py", line 157, in _add
    self.connection.add_s(self.dn, modlist)
  File "/usr/lib/python3.7/site-packages/ldap/ldapobject.py", line 428, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/usr/lib/python3.7/site-packages/ldap/ldapobject.py", line 413, in add_ext_s
    msgid = self.add_ext(dn,modlist,serverctrls,clientctrls)
  File "/usr/lib/python3.7/site-packages/ldap/ldapobject.py", line 410, in add_ext
    return self._ldap_call(self._l.add_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3.7/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
TypeError: ('Tuple_to_LDAPMod(): expected a byte string in the list', <map object at 0x7f79183d6400>)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "details": "('Tuple_to_LDAPMod(): expected a byte string in the list', <map object at 0x7f79183d6400>)",
    "invocation": {
        "module_args": {
            "attributes": {
                "description": "LDAP user for Jack Sparrow",
                "homeDirectory": "/home/jacksp",
                "loginShell": "/bin/bash",
                "objectClass": [
                    "inetOrgPerson"
                ],
                "uid": "jacksp"
            },
            "bind_dn": "cn=administrator,dc=munio,dc=io",
            "bind_pw": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "dn": "uid=jacksp,ou=users,dc=munio,dc=io",
            "objectClass": [
                "inetOrgPerson"
            ],
            "params": null,
            "server_uri": "ldap://localhost",
            "start_tls": false,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "Entry action failed."
}
```
