### ISSUE TITLE
Registered variable is not delegated as a fact

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#45411]
##### SUMMARY

In the docs, it mentions:

> Registered variables are valid on the host the remainder of the playbook run, which is the same as the lifetime of “facts” in Ansible. Effectively registered variables are just like facts.

But if `delegate_facts` is set to `yes` in task that registers a variable, then the variable is not available in the `hostvars` for the host that actually performed the task through delegation.

##### ISSUE TYPE
- ~Bug  Report~
- Docs Report

##### COMPONENT NAME

delegate_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 6110163f99) last updated 2018/09/10 08:39:48 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```paste below
Nothing
```

##### OS / ENVIRONMENT

Arch linux

##### STEPS TO REPRODUCE

```yaml
- hosts: server                         
  gather_facts: no                      
  tasks:                                
    - set_fact:                         
        qqq: 111                        
    - set_fact:                         
        ggg: 222                        
      delegate_to: localhost            
      delegate_facts: yes               
    - debug:                            
        var: qqq                        
      register: result                  
      delegate_to: localhost            
      delegate_facts: yes               
    - debug:                            
        var: ggg                        
      register: result                  
      delegate_to: localhost            
      delegate_facts: yes               
    - debug:                            
        var: hostvars['localhost']      
```

##### EXPECTED RESULTS

I expected to see the variable `result` in the output of the last debug.

##### ACTUAL RESULTS

```paste below
PLAY [server] ****************************************************************************************************************************************************************************************************

TASK [set_fact] **************************************************************************************************************************************************************************************************
ok: [server]

TASK [set_fact] **************************************************************************************************************************************************************************************************
ok: [server -> localhost]

TASK [debug] *****************************************************************************************************************************************************************************************************
ok: [server -> localhost] => {
    "qqq": 111
}

TASK [debug] *****************************************************************************************************************************************************************************************************
ok: [server -> localhost] => {
    "ggg": "VARIABLE IS NOT DEFINED!"
}

TASK [debug] *****************************************************************************************************************************************************************************************************
ok: [server] => {
    "hostvars['localhost']": {
        "ansible_check_mode": false,
        "ansible_connection": "local",
        "ansible_diff_mode": false,
        "ansible_facts": {},
        "ansible_forks": 5,
        "ansible_inventory_sources": [
            "/home/nikos/Projects/ansible-demo/inventory.yml"
        ],
        "ansible_playbook_python": "/usr/bin/python",
        "ansible_python_interpreter": "/usr/bin/python",
        "ansible_run_tags": [
            "all"
        ],
        "ansible_skip_tags": [],
        "ansible_verbosity": 0,
        "ansible_version": {
            "full": "2.8.0.dev0",
            "major": 2,
            "minor": 8,
            "revision": 0,
            "string": "2.8.0.dev0"
        },
        "ggg": 222,
        "group_names": [],
        "groups": {
            "all": [
                "server"
            ],
            "ungrouped": [
                "server"
            ]
        },
        "inventory_hostname": "localhost",
        "inventory_hostname_short": "localhost",
        "omit": "__omit_place_holder__76e3de3399ce73e0cef35372f695398c8b6d4c55",
        "playbook_dir": "/home/nikos/Projects/ansible-demo"
    }
}
```

Also, although I have noticed it before, it seems a bit unintuitive that `qqq` gets printed (although localhost does not know about it) and `ggg` does not (although localhost knows about it). But this seems like a design decision.
