### ISSUE TITLE
Sysctl module is undefined

### ISSUE THREAD

**Issue by guidoilbaldo** [ansible/ansible#45424]
##### SUMMARY

Trying to run a simple playbook against CentOS 7 with sysctl module, I get a "undefined error" on sysctl module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

sysctl.py

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = None
  configured module search path = [u'/Users/sguido/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Running Ansible on MacOS HighSierra, my targets are CentOS 7 servers running on oVirt. I was able to provision them and now I'm configuring them.

##### STEPS TO REPRODUCE

Running a very simple playbook with a role containing some tasks using sysctl module.

```yaml
---
- name: Tune sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: " {{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ sysctl-values }}"
  notify:
    - restart network

- name: Remove kernel.panic entry from /etc/sysctl.conf
  sysctl:
    name: kernel.panic
    state: absent
    sysctl_file: /etc/sysctl.conf
    reload: yes
  notify: restart network
```

##### EXPECTED RESULTS

No errors during the run of the playbook and sysctl.conf updated on my targets 

##### ACTUAL RESULTS

```paste below
TASK [common : Tune sysctl.conf] ***************************************************************************************************************************************************
task path: /Users/sguido/Work/git/infrastructure/ansible/playbooks/site/roles/common/tasks/sysctl.yml:4
fatal: [dns-1]: FAILED! => {
    "msg": "'sysctl' is undefined"
}
fatal: [dns-2]: FAILED! => {
    "msg": "'sysctl' is undefined"
}

```
