### ISSUE TITLE
requirements for azure modules incorrect

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#45435]
##### SUMMARY
https://docs.ansible.com/ansible/latest/scenario_guides/guide_azure.html

this->
```
$ pip install ansible[azure]
```

```
➜  $ sudo pip install ansible[azure]
zsh: no matches found: ansible[azure]
```

should be->

```
$ pip install azure
```
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/scenario_guides/guide_azure.html

##### ANSIBLE VERSION
```
N/A
```

##### CONFIGURATION
```
N/A
```

##### OS / ENVIRONMENT
```
N/A
```
##### ADDITIONAL INFORMATION
```
N/A
```

**Comment by IPvSean** [comment]
this is getting really confusing even when i install azure natively I get warnings on modules->

e.g.
```
    - name: Create resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: eastus
```

```
TASK [Create resource group] ***********************************************************************************************************
 [WARNING]: Installed azure-mgmt-resource client version is 2.0.0. The expected version is 1.2.2. Try `pip install ansible[azure]`
```
