### ISSUE TITLE
When no checksum is specified, get_url download the file even if destination exists

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#45491]
##### SUMMARY
When no checksum is specified, `get_url` download the file even if the destination already exists. This can be a problem with large files and low transfer rates.

It worked fine in Ansible 2.5.4.

It seems to be related to commit [c1a9f2](https://github.com/ansible/ansible/pull/43342/commits/c1a9f2cdfda320a334c2d90b6434665e2d21d4fc).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = None
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/share/ansible/lib/ansible
  executable location = /usr/share/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
  - file:
      path: /path/to/big-file
      state: touch

  - get_url:
      url: https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-9.5.0-amd64-DVD-2.iso
      dest: /path/to/big-file
```

##### EXPECTED RESULTS
The file is not downloaded.

##### ACTUAL RESULTS
The file is downloaded.
