### ISSUE TITLE
Azure load balancer crashes when running again the same playbook

### ISSUE THREAD

**Issue by zikalino** [ansible/ansible#45544]
##### SUMMARY
Tried to run sample playbook twice, crashed:
```
    - name: Create a load balancer
      azure_rm_loadbalancer:
        name: "{{ vmss_name }}lb"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        public_ip: "{{ vmss_name }}"
        probe_protocol: Tcp
        probe_port: 8065
        probe_interval: 10
        probe_fail_count: 3
        protocol: Tcp
        load_distribution: Default
        frontend_port: 80
        backend_port: 8065
        idle_timeout: 4
        natpool_frontend_port_start: 50000
        natpool_frontend_port_end: 50040
        natpool_backend_port: 22
        natpool_protocol: Tcp
```

Error looks as follows:

```
{
    "changed": false,
    "module_stderr": "No handlers could be found for logger \"msrestazure.azure_active_directory\"\nTraceback (most recent call last):\n  File \"/home/zim/.ansible/tmp/ansible-tmp-1536737761.53-9751627084068/AnsiballZ_azure_rm_loadbalancer.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/zim/.ansible/tmp/ansible-tmp-1536737761.53-9751627084068/AnsiballZ_azure_rm_loadbalancer.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/zim/.ansible/tmp/ansible-tmp-1536737761.53-9751627084068/AnsiballZ_azure_rm_loadbalancer.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_HpEZm2/__main__.py\", line 981, in <module>\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_HpEZm2/__main__.py\", line 977, in main\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_HpEZm2/__main__.py\", line 624, in __init__\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_HpEZm2/ansible_azure_rm_loadbalancer_payload.zip/ansible/module_utils/azure_rm_common.py\", line 313, in __init__\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_HpEZm2/__main__.py\", line 693, in exec_module\n  File \"/tmp/ansible_azure_rm_loadbalancer_payload_HpEZm2/__main__.py\", line 916, in load_balancer_to_dict\nAttributeError: 'InboundNatRule' object has no attribute 'enable_floating_point_ip'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loadbalancer

##### ANSIBLE VERSION
2.7

##### OS / ENVIRONMENT
Windows Bash on Ubuntu

##### STEPS TO REPRODUCE
Try to create LB with playbook as supplied, then execute playbook again.

##### EXPECTED RESULTS
Shouldn't crash, shouldn't make any changes to existing LB

##### ACTUAL RESULTS
Crashes, probably while checking idempotency.
