### ISSUE TITLE
rabbitmq_binding broken from ansible verison 2.6.0 and above

### ISSUE THREAD

**Issue by Ashok-Mishra** [ansible/ansible#45543]
##### SUMMARY
RabbitMQ argument binding is not working in ansible 2.6.0 and above. 

Refactoring of code at lib/ansible/modules/messaging/rabbitmq_binding.py in PR - https://github.com/ansible/ansible/pull/35651 actually broke the rabbitmq binding functionality.

**NOTE** - Reverting back to old code actually fixes the issue.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

rabbitmq_binding

##### OS / ENVIRONMENT

Centos 7.3 
Ansible 2.6.4

##### STEPS TO REPRODUCE
1. Create a playbook to install rabbitmq, create queues and exchanges.
2. Run the playbook that creates exchanges, queues and create bindings.
3. You will notice all the steps will pass but on rabbitmq GUI you won't be able to see any bindings on queues or exchanges.

##### EXPECTED RESULTS
The expected result is to see all bindings mentioned in playbook in rabbitmq GUI.

##### ACTUAL RESULTS
No bindings for queues and exchanges exist. 

##### ANSIBLE VERSION
```
Ansible version 2.5.9 works for rabbitmq binding. 
However ansible 2.6.0 and above are not able to bind queue with provided arguments. 
```

**Comment by ansibot** [comment]
@Ashok-Mishra Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrishoffman @hyperized @manuel-sousa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Im0** [comment]
@Ashok-Mishra any chance you could provide a bit of the playbook as per your steps to reproduce (2).  It will make it a bit quicker for others to test.

**Comment by Ashok-Mishra** [comment]
@Im0 
Playbook:

```
- name: Add Queues
  rabbitmq_queue:
    name: '{{ item.key }}'
    login_user: '{{ default_user }}'
    login_password: '{{ default_pass }}'
    vhost: '{{ item.value.vhost }}'
    auto_delete: false
  when: "'none' != item.key"
  with_dict: '{{ queues }}'

- name: Bind Queues
  rabbitmq_binding:
    name: '{{ item.value.exchange }}'
    arguments: '{{ item.value.arguments | default(omit) }}'
    destination: '{{ item.key }}'
    destination_type: queue
    routing_key: '{{ item.value.routing_key }}'
    login_user: '{{ default_user }}'
    login_password: '{{ default_pass }}'
    vhost: '{{ item.value.vhost }}'
  when: 
    - item.value.exchange is defined
  with_dict: '{{ queues }}'

```

Inventory:

```
queues:
    dev-log-queue:
      durable: true
      vhost: "dev-log"
      exchange: a-dev-log-exch
      routing_key: '#'
      mgmt_logs: true
    dev1-log-queue:
      durable: true
      vhost: "dev-log"
      exchange: a-dev-log-exch
      routing_key: '#'
      arguments:
        namespace: dev1
    dev2-log-queue:
      durable: true
      vhost: "dev-log"
      exchange: a-dev-log-exch
      routing_key: '#'
      arguments:
        namespace: dev2
```

If I use ansible 2.6.0 or above, using above playbook and inventory, I am not able to bind the queues. However, if I use ansible 2.5.9 or lower, queue binding works fine using the above playbook and inventory.
