### ISSUE TITLE
Combine() over hashes with lists take last list value in a recursive way

### ISSUE THREAD

**Issue by ag0n1k** [ansible/ansible#45556]
##### SUMMARY

`combine()` take last list value when accumulating items inside a `loop` or `with_items` loop.
However checks that value is list is present in `combine()` function and result of this code part is ok:
```python
for t in terms:
    if isinstance(t, MutableMapping):
        dicts.append(t)
    elif isinstance(t, list):
        dicts.append(combine(*t, **kwargs))
```
The problem is here:
```python
if recursive:
    return reduce(merge_hash, dicts)
```
`merge_hash()` does not check list values inside the hashes:
```python
if k in result:
    if isinstance(result[k], MutableMapping) and isinstance(v, MutableMapping):
        # merge those dicts recursively
        result[k] = merge_hash(result[k], v)
```

This happens both with Python 2.7.x and Python 3.6.x.
With ansible versions 2.6.2 and 2.6.4.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`utils/vars.py`
##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = None
  configured module search path = ['/home/ag0n1k/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/py_ansible/lib64/python3.6/site-packages/ansible
  executable location = /opt/py_ansible/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

- Ubuntu 16.04
- Fedora 28
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    - dict1:
        list_:
          - var: a
    - dict2:
        list_:
          - var: b
  tasks:
  - set_fact:
      _combined: >-
        {{
          _combined
          | default({})
          | combine(item, recursive=True)
        }}
    loop:
      - "{{ dict1 }}"
      - "{{ dict2 }}"
  - debug:
      var: _combined
```

##### EXPECTED RESULTS

```
TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "list_": [
            {
                "var": "a"
            },
            {
                "var": "b"
            }
        ]
    }
}
```

##### ACTUAL RESULTS

```
TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "_combined": {
        "list_": [
            {
                "var": "b"
            }
        ]
    }
}
```
