### ISSUE TITLE
win_iis_apppool; User set to literal string 'SpecificUser' when configuring pool to run as a domain user

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#45560]
##### SUMMARY

Module completes successfully, but instead of setting the identity to run as to the domain user it is set to a non-existent local user called 'SpecificUser'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_iis_apppool
##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.5.8
  config file = /home/SMCORP/jhawkesworth/ansible/ansible.cfg
  configured module search path = [u'/home/SMCORP/jhawkesworth/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```paste below
DEFAULT_ACTION_PLUGIN_PATH(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = [u'/
DEFAULT_CALLBACK_PLUGIN_PATH(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = [u
DEFAULT_CALLBACK_WHITELIST(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = ['pr
DEFAULT_FILTER_PLUGIN_PATH(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = [u'/
DEFAULT_GATHERING(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = implicit
DEFAULT_LOG_PATH(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = /home/SMCORP/j
DEFAULT_MODULE_PATH(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = [u'/home/SM
DEFAULT_ROLES_PATH(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = [u'/home/SMC
DEFAULT_STDOUT_CALLBACK(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = /ho
RETRY_FILES_ENABLED(/home/SMCORP/jhawkesworth/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

target OS: windows server 2012r2

##### STEPS TO REPRODUCE

create a pool and configure it to run as a domain user

```yaml
- name: configure listed integrated app pools to run as specified user
  win_iis_webapppool:
    name: "{{ item }}"
    state: started
    attributes:
      managedPipelineMode: Integrated
      processModel.identityType: SpecificUser
      processModel.username: '{{ win_domain }}\{{ win_pool_run_user }}'
      processModel.password: '{{ win_cred }}'
  with_items:
   - WebSite Integrated



```

##### EXPECTED RESULTS

pool is configured to run as 
'{{ win_domain }}\{{ win_pool_run_user }}'

##### ACTUAL RESULTS

pool is configured to run as 'SpecificUser' and fails to start (examine event logs)

```paste below

```
