### ISSUE TITLE
Uri module validate_certs parameter doesn't work with Python3.5

### ISSUE THREAD

**Issue by arzhr** [ansible/ansible#45573]
##### SUMMARY
While python is set to Python3 instead of Python2 for hosts, uri module fails owing to validate_certs parameter. With Python2, certificate validation is ignored as expected and request returns result. With Python3, module fails in python ssl library and requests never returns.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Uri module

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/beroot/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- hosts: rancher
  tasks:
  - name: Retrieve kubernetes cluster id
    uri:
      url: 'https://172.20.1.168/v3/cluster?&name=ansible'
      method: GET
      status_code: 200
      body_format: json
      headers:
        Authorization: "Bearer token-zmvvs:n8dbhxz66kwclqxw66n5gbhwn2k2bxc9nmbk4fx6mjhdvwxj4rqr64"
      validate_certs: False
    register: cluster_search_result
    changed_when: False
```

##### ACTUAL RESULTS
```
fatal: [172.20.1.184]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.20.1.184 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_9yw5qxmz/ansible_module_uri.py\", line 552, in <module>
    main()
	File \"/tmp/ansible_9yw5qxmz/ansible_module_uri.py\", line 493, in main
    dict_headers, socket_timeout)
	File \"/tmp/ansible_9yw5qxmz/ansible_module_uri.py\", line 400, in uri
    content = resp.read()
	File \"/usr/lib/python3.5/http/client.py\", line 455, in read
    return self._readall_chunked()\r\n  File \"/usr/lib/python3.5/http/client.py\", line 561, in _readall_chunked
    value.append(self._safe_read(chunk_left))\r\n  File \"/usr/lib/python3.5/http/client.py\", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))\r\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto
	
  return self._sock.recv_into(b)\r\n  File \"/usr/lib/python3.5/ssl.py\", line 929, in recv_into
  return self.read(nbytes, buffer)\r\n  File \"/usr/lib/python3.5/ssl.py\", line 791, in read
  return self._sslobj.read(len, buffer)\r\n  File \"/usr/lib/python3.5/ssl.py\", line 575, in read
  v = self._sslobj.read(len, buffer)\r\nConnectionResetError: [Errno 104] Connection reset by peer
  ", "msg": "MODULE FAILURE", "rc": 1}
```

```paste below

```
