### ISSUE TITLE
"template" and "file" directives don't change task's "changed" attribute on file ownership change

### ISSUE THREAD

**Issue by Kami** [ansible/ansible#4558]
## Environment details

Ansible version: HEAD (ansible-playbook 1.4 (devel 807e602228) last updated 2013/10/16 16:10:25 (GMT +200))
Python version: 2.7.3
Local and target OS: Ubuntu 12.04 x64
## Problem description

Currently, if a file user or group ownership is changed as a result of the `owner` or `group` attribute specified in the `template` or `file` directive, tasks `changed` attribute doesn't change. This means the `notify` handlers don't run and so on.

I don't know if this is a feature or a bug, but to me it seems like a bug. 

If other people can confirm that this is indeed a bug and that is not a desired behavior, I can look in creating a patch / fix.

**Comment by mpdehaan** [comment]
It's a bug!

I believe @jctanner (jtanner) is looking at this one currently, might want to coordinate with him on IRC.

Thanks!

**Comment by mscherer** [comment]
I cannot reproduce with file using latest git.
To test:

```
---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name:
    file: path=/tmp/foo owner=misc group=misc mode=0755 state=file
```

I create the file /tmp/foo, and each time I have it reset the permission, I see changed is properly set. Can you give a bit more information on how do you reproduce the problem exactly

**Comment by Kami** [comment]
I originally used `template` directive.

This should reproduce it:

``` yaml
- name: install config
  template: src=foo.cfg dest=/etc/foo.cfg mode=0777
  notify: restart foo
```

Change `mode`

``` yaml
- name: install config
  template: src=foo.cfg dest=/etc/foo.cfg mode=0400
  notify: restart foo
```
