### ISSUE TITLE
Disable SSH on Ansible for offline usage?

### ISSUE THREAD

**Issue by micyew** [ansible/ansible#45591]
##### SUMMARY

Hi, Is there a way to disable/preventing Ansible from SSH to devices(Cisco)? I'm writing a playbook to perform compliance checks on Cisco devices. I have downloaded the "show run" of all the devices. I got my desire output but the issue is everytime I run the playbook, Ansible will SSH to the devices (500+) which slowdown my playbook execution.
##### ISSUE TYPE
- Bug Report
Is this a bug or Ansible core functionality.
##### COMPONENT NAME

ios_config; running_config: ; intended_config: ; lookup
##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = /home/devops/ANSIBLE/Z_sh_run_nac_compliance/c3850_legacy_template/ansible.cfg
  configured module search path = [u'/home/devops/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cisco IOS 15.x
##### STEPS TO REPRODUCE

```yaml

 ---
- name: Compliance Report (Cisco Switch)
  hosts: cisco
  vars:
    creds:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
    one_space: " "

  tasks:
    - name: check the running-config against intended config
      ios_config:
        #running_config: "{{inventory_hostname}}.cfg"
        running_config: "{{ lookup('file', '{{inventory_hostname}}.cfg') }}"
        intended_config: "{{ lookup('file', 'intended_switch.cfg') }}"
        diff_against: intended
        #diff_ignore_lines:
      check_mode: yes
      register: test_diff 

```

```

[all:vars]
ansible_connection=network_cli
ansible_network_os=ios
ansible_user=cisco
ansible_ssh_pass=cisco123

[cisco]
SwitchA host=1.1.1.1
SwitchB host=1.1.1.1
SwitchC host=1.1.1.1
SwitchD host=1.1.1.1
SwitchE host=1.1.1.1
SwitchF host=1.1.1.1
SwitchF host=1.1.1.1

```

##### EXPECTED RESULTS

above is part of my playbook
It get my desire output. But Ansible keeps SSHing to the devices. As a workaround, I setup a lab switch (1.1.1.1) and put the same IP across all the devices.
##### ACTUAL RESULTS

It get my desire output. But Ansible keeps SSHing to the devices. Is there a way to tell Ansible to stop SSHing to device since I have all the 'runing config" in my folder.

```paste below

```
