### ISSUE TITLE
Create an 'ansible' module to manage ansible remote playbooks

### ISSUE THREAD

**Issue by ant31** [ansible/ansible#45596]
##### SUMMARY

Create a module 'ansible' to manage and invoke ansible-playbook cli via an ansible task.

There's module for every binaries and tools except 'ansible' itself !

What's the use case ? in short it would be the nearly the same as configuring a bastion but it would largely simplify the setup, especially in the case you need multiple ones and generated inventory from previous roles.  

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

Ansible module

```yaml
# previous tasks: 
# - name: copy ansible-playbook & roles
# - name: generate templated inventory
 
- name: Trigger ansible-playbook
  ansible: 
      inventory: deploy-custer/host.cfg
      playbook: deploy-custer/playbook.yml
      private-key: .ssh/vm-key.private
      extra_vars:
         toto: titi
      tags:
        - install
      become: true
      become-user: root
```
##### ADDITIONAL INFORMATION

If this is accepted as a feature, I can probably propose to work on that module.
