### ISSUE TITLE
--start-at-task does not work for tasks defined in roles

### ISSUE THREAD

**Issue by dmac** [ansible/ansible#4561]
Simple test case:

```
# file: playbook.yml

---
- hosts: 127.0.0.1
  connection: local
  roles:
    - test
```

```
# file: roles/test/tasks/main.yml

---
- name: foo
  debug: msg=foo
```

```
$ ansible-playbook playbook.yml --start-at-task='foo'
PLAY [127.0.0.1] *************************

GATHERING FACTS **************************
ok: [127.0.0.1]

PLAY RECAP *******************************
127.0.0.1    : ok=1    changed=0    unreachable=0    failed=0
```
