### ISSUE TITLE
pacman module fails to parse an empty list "New-style module did not handle its own exit"

### ISSUE THREAD

**Issue by Saloshp** [ansible/ansible#45638]
##### SUMMARY

`pacman` module is unable to parse an empty list,
I need this weird use-case because I use a variable for packages that I want installed, but that variable could be a clean list on some nodes that don't require intervention.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

modules/packaging/os/pacman.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0rc1.post0
  config file = /opt/munio.io/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

```bash
[root@localhost munio.io]# uname -a
Linux localhost 4.18.6-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 5 11:54:09 UTC 2018 x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
  - pacman:
      name: []
      state: installed
```

##### EXPECTED RESULTS

I expected the module to exit with success, like the `apt` module does, for the same use-case.

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ******************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
Thursday 13 September 2018  23:03:46 +0000 (0:00:00.078)       0:00:00.078 **** 
ok: [localhost]

TASK [pacman] ****************************************************************************************************************************************
Thursday 13 September 2018  23:03:47 +0000 (0:00:01.051)       0:00:01.130 **** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "New-style module did not handle its own exit"}

PLAY RECAP *******************************************************************************************************************************************
localhost                       : ok=1    changed=0    unreachable=0    failed=1   

Thursday 13 September 2018  23:03:47 +0000 (0:00:00.212)       0:00:01.342 **** 
=============================================================================== 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/pacman.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/pacman.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @indrajitr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by robertdebock** [comment]
Same issue for me. My use-case:

I'm reading packages from a variable:
```
cntlm_requirements:
  Debian:
    - apache2
  Fedora:
    - httpd
```

And try to install using:
```
- name: install requirements
  package:
    name: "{{ cntlm_requirements[ansible_distribution] | default (omit) }}"
    state: present
```

All distributions (actually ansible_pkg_mgr's) see to work, but pacman:
```
New-style module did not handle its own exit
```

**Comment by ansibot** [comment]
cc @tchernomax
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Afterburn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrey-pavlenko** [comment]
```
- name: Install Virtualbox
  package:
    name: 
      - virtualbox
      - virtualbox-host-dkms
      - virtualbox-guest-iso
    state: present
```
This works with pacman in my case.
