### ISSUE TITLE
host module does not work when only aliases have changed

### ISSUE THREAD

**Issue by dmac** [ansible/ansible#4563]
```
# file: /etc/hosts
127.0.0.1 localhost
```

```
# file: playbook.yml

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: add hostname aliases to /etc/hosts
      host: ip=127.0.0.1 hostname="localhost" aliases="foo"
      sudo: true
```

I would expect this playbook to ensure that the line:

```
127.0.0.1 localhost foo
```

is present in /etc/hosts, but in this example the file remains unchanged.
