### ISSUE TITLE
vault identifier is not exposed in tower_credential

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/ansible#45644]
##### SUMMARY

A vault identifier can be set in the AWX UI, but not not with the tower_credential module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

tower_credential

##### ADDITIONAL INFORMATION

```yaml
- name: Add Foo vault credential
  tower_credential:
    name: Foo credential
    description: Some random credential
    kind: vault
    organization: Foo
    vault_password: supersecret
    # vault_identifier: myvault <-- this parameter is missing!
    tower_config_file: "~/tower_cli.cfg"
```
