### ISSUE TITLE
ansible_connection: network_cli

### ISSUE THREAD

**Issue by nunoenpereira** [ansible/ansible#45681]
##### SUMMARY

I cannot find a way to make the variable "ansible_connection: network_cli" work in 2.6.4 and 2.7.0rc2. It works on 2.5.1 though. I verified this by calling ansible through python (upgraded and downgraded through pip3 to test).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible network variables.

##### ANSIBLE VERSION

```paste below
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<removed>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<removed>/.local/lib/python3.6/site-packages/ansible
  executable location = /home/<removed>/.local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
<empty output>
```

##### OS / ENVIRONMENT

ASAv on Azure cloud.

##### STEPS TO REPRODUCE

Copy the content below to files with the corresponding names. Place them all in the same folder, with the exception of the group vars file, which must be in the group_vars folder. Call main.py on the main folder.

```yaml
inventory.yml:
all:
    children:
        firewalls:
            hosts:
                <removed>:

firewalls.yml in group_vars folder:
---
ansible_connection: network_cli
ansible_network_os: asa
ansible_user: "{{username}}"
ansible_ssh_pass: "{{password}}"
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: "{{enpassword}}"
ansible_ssh_common_args: "-o KexAlgorithms=+diffie-hellman-group1-sha1"

playbook.yml:
---
- hosts: firewalls
  vars_prompt:
  - name: username
    prompt: "Username"
    private: no
  - name: password
    prompt: "Password"
    private: yes
  - name: enpassword
    prompt: "Enable password"
    private: yes
  tasks:
  - name: show hostname
    asa_command:
      commands:
        - show hostname
    register: sh_result
  - debug:
      var: sh_result.stdout_lines

main.py:
from ansible.cli.playbook import PlaybookCLI
inventory = 'inventory.yml'
playbook = 'playbook.yml'
cli = PlaybookCLI(args=['ansible-playbook', '-i', inventory, playbook])
cli.parse()
cli.run()
```

##### EXPECTED RESULTS

Fail on versions 2.6.4 and 2.7.0 with the message: "invalid literal for int() with base 10: '(dp1'".
Success on version 2.5.1.

##### ACTUAL RESULTS

I don't know how to do this in python. Tell me if it is really needed and I will try to do it.

```paste below
invalid literal for int() with base 10: '(dp1'
```
