### ISSUE TITLE
Could not find imported module support code for 'Ansible.ModuleUtils.PrivilegeUtil

### ISSUE THREAD

**Issue by ss6851** [ansible/ansible#45680]
##### SUMMARY

Could not Disable SMB signing with win_regedit

##### ISSUE TYPE
- Bug Report
`Could not find imported module support code for 'Ansible.ModuleUtils.PrivilegeUtil`

##### COMPONENT NAME

`win_regedit`

##### ANSIBLE VERSION

```paste below
  config file = /home/singh/windows_env/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules/windows']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/singh/windows_env/ansible.cfg) = [u'/home/singh/windows_env/hosts']
DEFAULT_MODULE_PATH(/home/singh/windows_env/ansible.cfg) = [u'/usr/share/ansible/modules/windows'
```

##### OS / ENVIRONMENT

`Target OS: Windows Server 2012 R2 Standard virtually installed using VMware Workstation 12 Pro`
##### STEPS TO REPRODUCE

I have the following file system: 
```
singh@ubuntu:~/windows_env$ tree
.
├── ansible.cfg
├── ansible.cfg.save
├── choco.yml
├── hosts
├── playbook.retry
├── playbook.yml
└── roles
    ├── active-directory
    │   └── tasks
    │       └── main.yml
    └── join-domain
        └── tasks
            ├── main.yml
            └── main.yml.save
```

```yaml
singh@ubuntu:~/windows_env$ cat roles/active-directory/tasks/main.yml
- name: Install AD-Domain-Services feature
  win_feature: >
    name=AD-Domain-Services
    include_management_tools=yes
    include_sub_features=yes
    state=present

- name: Setup Active Directory Controller
  win_domain: >
    dns_domain_name=safedomain.com
    safe_mode_password={{ ad_safe_mode_password }}
  register: active_directory_controllers

- name: reboot once DC created
  win_reboot:
  when: active_directory_controllers.reboot_required

- name: Promote to domain controller
  win_domain_controller: >
    dns_domain_name=safedomain.com
    domain_admin_user=administrator@safedomain.com
    domain_admin_password=XXXX
    read_only=no
    state=domain_controller
    safe_mode_password={{ ad_safe_mode_password }} 
  register: result

- name: Create computers in Active Directory
  win_domain_computer: >
    name=Client
    enabled=yes 
    state=present
    dns_hostname=Client.WORKGROUP
    ou="OU=Domain Controllers,DC=safedomain,DC=com"

- name: Disable SMB signing
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
    name: RequireSecuritySignature
    value: 0
    type: dword
    state: present
```
The playbook I am using:
```
singh@ubuntu:~/windows_env$ cat playbook.yml
- hosts: 192.168.106.131
  roles:
    - active-directory
  vars:
    ad_domain_name: safedomain.com
    ad_safe_mode_password: XXXX
  
- hosts: 192.168.106.159  
  roles:
    - join-domain
  vars:
    ad_domain_name: safedomain.com
    ad_safe_mode_password: XXXX
singh@ubuntu:~/windows_env$
```

##### EXPECTED RESULTS

Disabled SMB signing in Windows Server AD

##### ACTUAL RESULTS

```paste below
singh@ubuntu:~/windows_env$ ansible-playbook playbook.yml

PLAY [192.168.106.131] **************************************************************************

TASK [Gathering Facts] **************************************************************************
ok: [192.168.106.131]

TASK [active-directory : Install AD-Domain-Services feature] ************************************
ok: [192.168.106.131]

TASK [active-directory : Setup Active Directory Controller] *************************************
ok: [192.168.106.131]

TASK [active-directory : reboot once DC created] ************************************************
skipping: [192.168.106.131]

TASK [active-directory : Promote to domain controller] ******************************************
ok: [192.168.106.131]

TASK [active-directory : Create computers in Active Directory] **********************************
changed: [192.168.106.131]

TASK [active-directory : Disable SMB signing] ***************************************************
fatal: [192.168.106.131]: FAILED! => {"msg": "Could not find imported module support code for 'Ansible.ModuleUtils.PrivilegeUtil'."}
	to retry, use: --limit @/home/singh/windows_env/playbook.retry

PLAY RECAP **************************************************************************************
192.168.106.131            : ok=5    changed=1    unreachable=0    failed=1 
```
