### ISSUE TITLE
Cloudstack: Missing support for VPC service_capabilities

### ISSUE THREAD

**Issue by dpassante** [ansible/ansible#45729]
##### SUMMARY

The ```service_capabilities``` parameter is not used by the cs_vpc_offering module when creating a new VPC offer.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cs_vpc_offering

##### ANSIBLE VERSION

```paste below
2.5, 2.6, 2.7
```

##### STEPS TO REPRODUCE

```yaml
- name: test create enabled region level vpc offer with distrubuted router
  cs_vpc_offering:
    name: "{{ cs_resource_prefix }}_vpc_drl"
    display_text: "vpc offering description"
    supported_services: [ Dns, PortForwarding, Dhcp, SourceNat, UserData, StaticNat, Vpn, Lb ]
    service_providers:
      - { service: 'dns', provider: 'virtualrouter' }
      - { service: 'dhcp', provider: 'virtualrouter' }
    state: enabled
    service_capabilities:
      - {service: 'Connectivity', capabilitytype: 'DistributedRouter', capabilityvalue: true}
      - {service: 'Connectivity', capabilitytype: 'RegionLevelVPC', capabilityvalue: true}
```

##### EXPECTED RESULTS

Service capabilities are enabled in the service offering.

##### ACTUAL RESULTS

Service capabilities are ignored in the service offering.
