### ISSUE TITLE
Molecule idempotence test failed for openssl_privatekey

### ISSUE THREAD

**Issue by ViachaslauKabak** [ansible/ansible#45724]
##### SUMMARY
Molecule idempotence test failed for openssl_privatekey module even with force: True parameter
ansible 2.5.8
  config file = None
  configured module search path = [u'/home/gitlab-runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
$ molecule --version
molecule, version 2.17.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_privatekey

##### ANSIBLE VERSION
ansible 2.5.8

##### CONFIGURATION

```
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/gitlab-runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
```

##### OS / ENVIRONMENT
centos 7

##### STEPS TO REPRODUCE

```yaml
- name: "Create private certificate"
  openssl_privatekey:
    path: "{{ local_pkey_file_path }}/{{ local_pkey_file_name }}"
    size: 2048
    force: True
  become: True
  when: not keystore_file.stat.exists
```

##### EXPECTED RESULTS
idempotence test passed

##### ACTUAL RESULTS

```paste below
--> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
* [test-ansible-role-gitlab-runner-centos] => s: Create private certificate
```
