### ISSUE TITLE
Removing Vms in scaleway_compute with "absent" flag crashes the first time (during poweroff)

### ISSUE THREAD

**Issue by zwindler** [ansible/ansible#45740]
##### SUMMARY
When trying to remove a VM using "absent" flag in scaleway_compute on a running VM, module crashes with error 

```
failed: [localhost] (item=1) => {"changed": false, "item": "1", "msg": "Error during server poweroff: (400) {u'message': u'server should be running', u'type': u'invalid_request_error'}"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
scaleway_compute

##### ANSIBLE VERSION

```ansible 2.7.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.7.0.dev0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### CONFIGURATION

```
ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Linux Mint

##### STEPS TO REPRODUCE
create a VM

```
---
- hosts: localhost
  connection: local
  tasks:
  - name: "Create my servers"
    scaleway_compute:
      name: bdxio{{item}}
      state: running
      image: "e756fdb5-f586-4d9b-8585-817151749a96"
      organization: [REDACTED]
      region: par1
      commercial_type: ARM64-2GB
      wait: true
      tags: bdxio
    with_sequence: count=1
```
Check that VMs are up and running, then remove the VM

```
---
- hosts: localhost
  connection: local
  tasks:
  - name: "Remove my servers"
    scaleway_compute:
      name: bdxio{{item}}
      state: absent
      image: "e756fdb5-f586-4d9b-8585-817151749a96"
      organization: [REDACTED]
      region: par1
      commercial_type: ARM64-2GB
    with_sequence: count=1
```

Error message

```
TASK [Remove my servers] ********************************************************************************************************************************************************************************************************************
failed: [localhost] (item=1) => {"changed": false, "item": "1", "msg": "Error during server poweroff: (400) {u'message': u'server should be running', u'type': u'invalid_request_error'}"}
```

##### EXPECTED RESULTS
The module should first shutdown the VM if it is running, wait for shutdown, and then remove the VM. 

##### ACTUAL RESULTS
The VM is correctly shut down, but module doesn't wait for shutdown completion and cannot remove VM (and crashes).

Workaround : Running the playbook anther time, after manually checking that VM is completely shut down works
