### ISSUE TITLE
scaleway_compute : commercial_type and image shouldn't be required for absent state

### ISSUE THREAD

**Issue by zwindler** [ansible/ansible#45794]
##### SUMMARY
When trying to remove virtual machines, with "absent" flag, *commercial_type* and *image* shouldn't be required arguments (only needed when creating VMs)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
scaleway_compute

##### ADDITIONAL INFORMATION
This playbook will fail

```
---
- hosts: localhost
  connection: local
  tasks:
  - name: "Remove my server"
    scaleway_compute:
      name: vm1
      state: absent
      organization: [REDACTED]
      region: par1
```
with error 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: commercial_type, image"}
```

IMO, *name*, *region*, and perhaps *organization* should be more than enough to delete a VM with "absent" state
