### ISSUE TITLE
gcp_compute_instance is not idempotent

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#45799]
##### SUMMARY

Running `gcp_compute_instance` shows as changed always.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 53b230ca74) last updated 2018/09/18 10:16:27 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Arch linux 

##### STEPS TO REPRODUCE

A typical task perhaps like the examples.

The variables used below are static

```yaml
 - name: Create instances                                                                      
   gcp_compute_instance:                                                                       
     name: "{{ item.0.name }}"                                                                                                                    
     can_ip_forward: "{{ item.0.ip_forward }}"                                                 
     disks:                                                                                    
       - auto_delete: yes                                                                      
         boot: yes                                                                                                                                
         initialize_params:                                                                                                                       
           source_image: "{{ item.0.image | default(omit) }}"                                  
           source_image: "projects/{{ project_facts.gce.project }}/global/images/custom-ubuntu-image"
           disk_size_gb: 10                                                                    
     machine_type: >-                                                                          
       {{                                                                                      
         (lookup('env', 'lib_snapshot_disk_name') == '')                                       
         | ternary(                                                                                
             item.0.temp_machine_type,                                                         
             'f1-micro'                                                                        
           )                                                                                   
       }}                                                                                      
     network_interfaces:                                                                       
       - network:                                                                                                                                      
           selfLink: "projects/{{ project_facts.gce.project }}/global/networks/{{ project_facts.network.name }}"
         subnetwork:                                                                           
           selfLink: "projects/{{ project_facts.gce.project }}/regions/{{ project_facts.network.region }}/subnetworks/{{ item.0.interfaces.0.subnet }}"
         network_ip: "{{ item.0.interfaces.0.private_ip_real }}"                               
         access_configs:                                                                       
           - type: ONE_TO_ONE_NAT                                                              
             name: External NAT                                                                
             nat_ip:                                                                           
               address: "{{ item.1.address }}"                                                 
     project: "{{ project_facts.gce.project }}"                                                
     service_accounts:                                                                         
       - email: a@a.iam.gserviceaccount.com                                  
         scopes: https://www.googleapis.com/auth/cloud-platform                                
     metadata: {}                                                                              
     zone: "{{ item.0.zone }}"                                                                 
     tags:                                                                                     
       items: "{{ item.0.tags }}"                                                              
   register: gce_result                                     
   loop: "{{ instances | zip(addresses.results) | list }}"  
```

##### EXPECTED RESULTS

I would expect the second time the task is run to see no changes. Online the instance stays the same.

##### ACTUAL RESULTS

The tasks shows as changed always.

```paste below

```
