### ISSUE TITLE
Weird behaviour with expansion

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#4580]
I'm creating a playbook that :
- fetches directories sizes on a remote server
- sums the sizes
- writes the server name and the total size in a local file

I'm stumbling on a weird problem : everything is fine at the first run, but expansion doesn't happen on the second and subsequent runs (i.e. when the host information is already in the local file).

Here is the playbook :

``` yaml
 - hosts: all 

    tasks:

    # We first check if we already know the size so
    # we don't run 'du' if it's not necessary
    # For this we look in the local file containing one
    # server summed size per line with this format : 
    # www.example.org:123
    # We use bash+pipefail so we get an error if the file
    # doesn't exist

    - name: Check if I know your size
      shell: executable="/bin/bash" 
             set -o pipefail; 
             grep "^{{ ansible_fqdn }}" /tmp/sizes | 
             cut -f2 -d":"
      ignore_errors: true
      delegate_to: localhost
      register: size

    # If grepping this server size failed, 
    # we make a du on the server

    - name: Compute size if not known
      shell: du -sk /etc /usr/local | 
             awk '{ SUM += $1} END { print SUM/1024/1024 }'
      register: size
      when: size|failed

    # Now, we have the size in size.stdout
    # That has been set by either previous task

    - name: Add computed size to sizelist
      lineinfile: dest=/tmp/sizes regexp=^{{ ansible_fqdn }} 
                  line={{ ansible_fqdn }}:{{ size.stdout }} 
                  create=yes
      when: size|success
      delegate_to: localhost
```

When this playbook is run the first time, here is what happens :

```
$ ansible-playbook -l www.example.org testbook.yml 

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [www.example.org]

TASK: [Check if I know your size] ********************************************* 
failed: [www.example.org] => {"changed": true, "cmd": " set -o pipefail; grep \"^www4.erasme.org\" /tmp/sizes | cut -f2 -d\":\" ", "delta": "0:00:00.002870", "end": "2013-10-18 11:35:06.234500", "rc": 2, "start": "2013-10-18 11:35:06.231630"}
stderr: grep: /tmp/sizes: No such file or directory
...ignoring

TASK: [Compute size if not known] ********************************************* 
changed: [www.example.org]

TASK: [Add computed size to sizelist] ***************************************** 
changed: [www.example.org]

PLAY RECAP ******************************************************************** 
www.example.org            : ok=4    changed=3    unreachable=0    failed=0   

$ cat /tmp/sizes 
www.example.org:0.0151901
$
```

This is fine and is what's expected. However, on a second run, expansion doesn't work and plain variable names are written in `/tmp/sizes` :

```
$ ansible-playbook -l www.example.org testbook.yml -vvv

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<www.example.org> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO www.example.org
<www.example.org> EXEC /bin/sh -c 'mkdir -p /tmp/ansible-1382090055.08-245846583794670 && echo /tmp/ansible-1382090055.08-245846583794670'
<www.example.org> REMOTE_MODULE setup 
<www.example.org> PUT /tmp/tmpEUPzLg TO /tmp/ansible-1382090055.08-245846583794670/setup
<www.example.org> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-1382090055.08-245846583794670/setup; rm -rf /tmp/ansible-1382090055.08-245846583794670/ >/dev/null 2>&1'
ok: [www.example.org]

TASK: [Check if I know your size] ********************************************* 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-1382090057.28-55845320311557 && chmod a+rx /tmp/ansible-1382090057.28-55845320311557 && echo /tmp/ansible-1382090057.28-55845320311557']
<localhost> REMOTE_MODULE command executable="/bin/bash" set -o pipefail; grep "^www.example.org" /tmp/sizes | cut -f2 -d":" #USE_SHELL
<localhost> PUT /tmp/tmpg7ptw2 TO /tmp/ansible-1382090057.28-55845320311557/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python2 /tmp/ansible-1382090057.28-55845320311557/command; rm -rf /tmp/ansible-1382090057.28-55845320311557/ >/dev/null 2>&1']
changed: [www.example.org] => {"changed": true, "cmd": " set -o pipefail; grep \"^www.example.org\" /tmp/sizes | cut -f2 -d\":\" ", "delta": "0:00:00.003233", "end": "2013-10-18 11:54:17.393490", "rc": 0, "start": "2013-10-18 11:54:17.390257", "stderr": "", "stdout": "0.0151901"}

TASK: [Compute size if not known] ********************************************* 
skipping: [www.example.org]

TASK: [Add computed size to sizelist] ***************************************** 
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-1382090057.41-104015582607035 && chmod a+rx /tmp/ansible-1382090057.41-104015582607035 && echo /tmp/ansible-1382090057.41-104015582607035']
<localhost> REMOTE_MODULE lineinfile dest=/tmp/sizes regexp=^{{ansible_fqdn}} line={{ansible_fqdn}}:{{size.stdout}} create=yes
<localhost> PUT /tmp/tmp1Vxgzw TO /tmp/ansible-1382090057.41-104015582607035/lineinfile
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python2 /tmp/ansible-1382090057.41-104015582607035/lineinfile; rm -rf /tmp/ansible-1382090057.41-104015582607035/ >/dev/null 2>&1']
changed: [www.example.org] => {"changed": true, "msg": "line added"}

PLAY RECAP ******************************************************************** 
www.example.org            : ok=3    changed=2    unreachable=0    failed=0   

$ cat /tmp/sizes
www.example.org:0.0151901
{{ansible_fqdn}}:{{size.stdout}}
$
```

While size has been found and `size.stdout` has been set properly in task `Check if I know your size`, it doesn't get expanded in task `Add computed size to sizelist` (neither does `ansible_fqdn`).

I added the following to the playbook to get some insights :

``` yaml
  - name: debug
    debug: msg="{{ ansible_fqdn }}:{{ size.stdout }}"

  - name: debug
    debug: msg="{{ ansible_fqdn }}:{{ size.stdout }}"
    delegate_to: localhost
```

Which gives a correct output in the first run, and this on the second :

```
TASK: [debug] ***************************************************************** 
ok: [www.example.org] => {
    "msg": "{{ansible_fqdn}}:{{size.stdout}}"
}

TASK: [debug] ***************************************************************** 
ok: [www.example.org] => {
    "msg": "{{ansible_fqdn}}:{{size.stdout}}"
}

```

This is really puzzling me an looks like an issue. Any clue ?
