### ISSUE TITLE
vmware_guest module fails to customize vm built from template

### ISSUE THREAD

**Issue by Vaygh** [ansible/ansible#45817]
##### SUMMARY
vmware_guest module fails to customize vm built from template

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest module

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg
  configured module search path = [u'/Users/dmccaskey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Sep 18 2018, 14:37:45) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```
and
```
ansible 2.5.4
  config file = /home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg
  configured module search path = [u'/home/dmccaskey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = True
COMMAND_WARNINGS(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = False
DEFAULT_FORKS(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = [u'/Users/dmccaskey/
DEFAULT_LOG_PATH(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = /Users/dmccaskey/ansi
DEFAULT_TIMEOUT(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/dmccaskey/Git/AHSR-10893-ansible-vmware/ansible.cfg) = False
```
and
```
ANSIBLE_NOCOWS(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = True
COMMAND_WARNINGS(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = False
DEFAULT_FORKS(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = [u'/home/dmccaskey/AHSR-1
DEFAULT_LOG_PATH(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = /home/dmccaskey/ansible.lo
DEFAULT_TIMEOUT(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/dmccaskey/AHSR-10893-ansible-vmware/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible 2.6.4 running on Mac OS X High Sierra installed via pip
Ansible 2.5.4 running on Ubuntu 16.04 installed via pip
Target: vSphere 5.5 Standard

##### STEPS TO REPRODUCE
Run playbook with the following task:
```
- name: Create and power on stage virtual machines
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    validate_certs: False
    port: 443
    folder: "{{ client_code }}"
    name: "{{ hostname }}"
    state: poweredon
    template: "PXE Template"
    cluster: "{{ vmware_cluster }}"
    datacenter: "{{ vmware_datacenter }}"
    guest_id: "ubuntu64Guest"
    disk:
    - size_gb: 16
      type: thin
      datastore: AH-STG-SAN
      autoselect_datastore: yes
    hardware:
      memory_mb: "{{ vram }}"
      num_cpus: "{{ vcpus }}"
      num_cpu_cores_per_socket: 1
      scsi: paravirtual
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
      version: 10 # Hardware version of virtual machine
    cdrom:
      type: none
    networks:
    - name: "{{ client_code }}-{{ env_type }}-VLAN-{{ stg_vlan }}"
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy
  when:
    - env_type is match("DEV|STG")
```

##### EXPECTED RESULTS
VM is created and powered on with provided parameters

##### ACTUAL RESULTS
VM is created, but not powered on, due to fatal error below

```
fatal: [1.2.3.4 -> localhost]: FAILED! => {"changed": false, "msg": "Failed to create a virtual machine : Customization of the guest operating system 'ubuntu64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations."}
```

Removing the
```
    networks:
    - name: "{{ client_code }}-{{ env_type }}-VLAN-{{ stg_vlan }}"
```
section successfully creates and powers on the VM, but connected to the vSwitch port group defined in the template, which is not the expected behavior.

This appears to be the same problem as https://github.com/ansible/ansible/issues/24193
