### ISSUE TITLE
blockinfile keeps adding block 

### ISSUE THREAD

**Issue by flynn1973** [ansible/ansible#45848]
##### SUMMARY

blockinfile keeps adding blocks even if they are already there.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

blockinfile

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/aix/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:45:54) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/etc/ansible/aix/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/aix/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/aix/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/aix/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/etc/ansible/aix/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/aix/ansible.cfg) = localhost:6379:0
CACHE_PLUGIN_TIMEOUT(/etc/ansible/aix/ansible.cfg) = 0
DEFAULT_BECOME_METHOD(/etc/ansible/aix/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/aix/ansible.cfg) = root
DEFAULT_FORKS(/etc/ansible/aix/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/aix/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/aix/ansible.cfg) = [u'/etc/ansible/aix/dyninv/inventory.py']
DEFAULT_MANAGED_STR(/etc/ansible/aix/ansible.cfg) = Ansible managed: Manual interventions are a waste of time.
DEFAULT_REMOTE_USER(/etc/ansible/aix/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/aix/ansible.cfg) = [u'/etc/ansible/aix/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/aix/ansible.cfg) = debug
HOST_KEY_CHECKING(/etc/ansible/aix/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/aix/ansible.cfg) = 1800
RETRY_FILES_ENABLED(/etc/ansible/aix/ansible.cfg) = False

```

##### OS / ENVIRONMENT

RedHat EL 7.5

##### STEPS TO REPRODUCE

```
- name: enable sap users
         blockinfile:
                    dest: /etc/security/user
                    backup: no
                    marker: "\n*** {mark} ***"
                    marker_begin: "BEGIN - ADDED WITH ANSIBLE - {{ item.name }}"
                    marker_end: "END - ADDED WITH ANSIBLE - {{ item.name }}"
                    state: present
                    block: |
                         {{ item.name }}:
                                 SYSTEM = "LDAP"
                                 registry = LDAP
         with_items: "{{ sap_users }}"

```

##### EXPECTED RESULTS

block added one time

*** BEGIN - ADDED WITH ANSIBLE - 31300045 ***
31300045:
        SYSTEM = "LDAP"
        registry = LDAP

*** END - ADDED WITH ANSIBLE - 31300045 ***

##### ACTUAL RESULTS

block added multiple times. without the newline above the marker it works idempotent, but the
newline is required in this case.

bla:
        SYSTEM = "LDAP"
        registry = LDAP

*** BEGIN - ADDED WITH ANSIBLE - 31300045 ***
31300045:
        SYSTEM = "LDAP"
        registry = LDAP

*** END - ADDED WITH ANSIBLE - 31300045 ***

*** BEGIN - ADDED WITH ANSIBLE - 31300045 ***
31300045:
        SYSTEM = "LDAP"
        registry = LDAP

*** END - ADDED WITH ANSIBLE - 31300045 ***

```

TASK [manage_ldap_users : enable sap users] *******************************************************************************************************************************************************************
changed: [AIXWUKIT] => (item={u'comment': u'---', u'group': u'sap_staff', u'name': u'31300045'})
changed: [SAG0120_TESTLPAR] => (item={u'comment': u'---', u'group': u'sap_staff', u'name': u'31300045'})

TASK [manage_ldap_users : Add authorized keys] ****************************************************************************************************************************************************************
ok: [AIXWUKIT] => (item={u'comment': u'---', u'group': u'sap_staff', u'name': u'31300045'})
ok: [SAG0120_TESTLPAR] => (item={u'comment': u'---', u'group': u'sap_staff', u'name': u'31300045'})

PLAY RECAP ****************************************************************************************************************************************************************************************************
AIXWUKIT                   : ok=12   changed=3    unreachable=0    failed=0
SAG0120_TESTLPAR           : ok=11   changed=2    unreachable=0    failed=0

```
