### ISSUE TITLE
yum module install all packages when using wildcard in name

### ISSUE THREAD

**Issue by wnelso1** [ansible/ansible#45842]
##### SUMMARY

Using yum module to update python with: name:'python*' state: latest  and update_only: yes tries to install every python package available not just update the installed packages. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

yum module

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.6.3
  config file = /home/. . . /ansible.cfg
  configured module search path = [u'/home/. . . /ansible/common/library']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]


```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Local: CentOS 6
Remote: CentOS 7
##### STEPS TO REPRODUCE

```yaml


 name: update python packages
 yum:
    name: 'python*'
    state: latest
    update_only: yes
    update_cache: yes

```

##### EXPECTED RESULTS

Only currently install packages get updated. 

##### ACTUAL RESULTS

Every package available tries to get installed

```paste below

```
