### ISSUE TITLE
nxos_interface_ospf - add ospf network type option

### ISSUE THREAD

**Issue by dmurarasu** [ansible/ansible#45901]
##### SUMMARY

Add option to configure interface ospf network type when using nxos_interface_ospf module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_interface_ospf

##### ADDITIONAL INFORMATION

Adds the ability to configure ospf network type, ie point-to-point on interfaces.
This overrides the default categorization of ospf. ie ospf ignores configured prefix on loopbacks.
Also needed when DR/BDR not needed on p-t-p links.
 

```yaml
- hosts: sw
  name: Configure switch
  connection: network_cli
  tasks:
     - name: Configure ospf interface settings
       nxos_interface_ospf:
         interface: loopback0
         ospf: prod
         area: 0.0.0.0
         state: present
         network: point-to-point
```
