### ISSUE TITLE
ovirt_vms does not proceed cloud-init when state is running. Manual start works

### ISSUE THREAD

**Issue by marc-ledent** [ansible/ansible#45900]
##### SUMMARY
When I create a VM with cloud-init parameters, the cloud init is executed only if I start the VM manually:

In this example, if I set "state: running", the cloud-init part is not executed. I must set "state: present" and start the VM manually in the RHEV console.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```paste below
ansible 2.6.3                                                                                               
  config file = /etc/ansible/ansible.cfg                                                                    
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                 
  executable location = /usr/bin/ansible                                                                    
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]           

```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10                                                                      
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit                                                            
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all                                                             
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 10                                                             
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts.d']                                           
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/opt/ansible/roles']                     
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False                                                               
INVENTORY_IGNORE_EXTS(/etc/ansible/ansible.cfg) = ['~', '.orig', '.bak', '.ini', '.cfg', '.retry', '.pyc', '.pyo',
 '.dhl']                                                                                                          
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30                                                         

```

##### STEPS TO REPRODUCE

```yaml
- name: Create VM                               
  ovirt_vms:                                    
    state: present                              
    cluster: Default                            
    auth: '{{ ovirt_auth }}'                    
   type: server                                
    name: '{{ inventory_hostname }}'            
    comment: '{{ inv_tag.hostdesc }}'           
    description: '{{ inv_tag.hostdesc }}'       
    memory: "{{ inv_tag.mem | default('2')}}GiB"
    boot_menu: True                             
    disk_format: cow                            
    disks:                                      
    - name: '{{ inventory_hostname }}_OS'       
      interface: virtio                         
      bootable: True                            
      activate: True                            
    nics:                                       
    - name: eth0                                
      interface: virtio                         
      profile_name: ovirtmgmt                   
    cloud_init_persist: True                    
    cloud_init:                                 
      host_name: '{{ inventory_hostname }}'     
      timezone: "GMT+01:00"                     
      dns_servers: "xxxxxxxxxxxxxx"       
      dns_search: "{{ fqdn_name.split('.', 1)[1] }}"
      custom_script: |                              
        users:                                      
          - name: root                              
          - name: ansible                           
            groups: wheel                           
        chpasswd:                                   
          list: |                                   
            root:{{ root_pass }}                    
            ansible:{{ ansible_ssh_pass }}          
          expire: False                             
        ssh_pwauth: True                            
        runcmd:                                     
          - sed -i '/192.168/d' /etc/resolv.conf    
    cloud_init_nics:                                
    - nic_name: eth0                                
      nic_boot_protocol: static                     
      nic_ip_address: '{{ main_ip }}'               
      nic_netmask: 255.255.254.0                    
      nic_gateway: YYYYYYYYYYYY                      
      nic_on_boot: True                             

```
In this case, "state" must be "present" ans the VM must be started manually unless cloud-config will not be applied and the VM will not be accessible...

##### EXPECTED RESULTS

The cloud-config settings should be applied when state is "running"

##### ACTUAL RESULTS

The vm is started with no cloud-init settings. Even the hostname is not set.

```paste below

```
