### ISSUE TITLE
gcp_compute_instance: disk.source parameter cannot be omitted

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#45906]
##### SUMMARY

I have created a task to create a bunch of instances. Some have a disk that they will use, others will use an image to create the instance. For that purpose, I want to set disk source to omit, but this fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 5a3000af19) last updated 2018/09/20 10:29:12 (GMT +200)
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
```

##### CONFIGURATION

```paste below
None
```

##### STEPS TO REPRODUCE

```yaml
- gcp_compute_instance:
  name: "test_object"
      machine_type: n1-standard-1
      disks:
      - auto_delete: true
        boot: true
        source: "{{ instance_disk | default(omit) }}"
        initialize_params: # this gets precedence over "source" it seems
          source_image: source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20180911
        disk_size_gb: 10
      metadata:
        startup-script-url: gs:://graphite-playground/bootstrap.sh
        cost-center: '12345'
      network_interfaces:
      - network: "{{ network }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: us-central1-a
      project: "test_project"
      auth_kind: "service_account"
      service_account_file: "/tmp/auth.pem"
      state: present
```

##### EXPECTED RESULTS

I would expect the `disk.source` key to be omitted.

##### ACTUAL RESULTS

Ansible complains about `source.disk` not being a dict.

```paste below
- msg: argument source is of type <class 'str'> and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value
    - failed: True
    - exception:   File "/tmp/ansible_gcp_compute_instance_payload_zowsgdh9/ansible_gcp_compute_instance_payload.zip/ansible/module_utils/basic.py", line 2095, in _check_argument_types
      param[k] = type_checker(value)
    File "/tmp/ansible_gcp_compute_instance_payload_zowsgdh9/ansible_gcp_compute_instance_payload.zip/ansible/module_utils/basic.py", line 1940, in _check_type_dict
      raise TypeError("dictionary requested, could not parse JSON or key=value")
 
```
