### ISSUE TITLE
pipenv, pipenv_facts: new module request

### ISSUE THREAD

**Issue by decentral1se** [ansible/ansible#45911]
##### SUMMARY

https://pipenv.readthedocs.io/en/latest/ is quickly becoming a more and more way to manage Python dependencies and there is no module to support that need right now. I currently have a few tasks that do Pipenv based tasks but they require a lot of wrangling to ensure idempotency. 

The module would provide an idempotent way to install Pipenv managed projects like:

```yaml
- name: Run a Pipenv install.
  pipenv:
    cmd: install
    path: /path/to/Pipfile/containing/folder
```

That's probably all I'd do to start with. There are a number of other commands though. I am not quite sure about `pipenv run` since it is like a `command` module command and will be hard to show extra context for idempotency.

Then, for interacting with other modules, we normally just want to know where the virtual environment that Pipenv manages is located (from `pipenv --venv` in a folder with a `Pipfile`), For example, when using the `django_manage` module, you can pass `virtualenv: /foo/` and it knows how to find your dependencies. TBH, that could probably be split out into it's own 'facts' module which might look like:

```yaml
- name: Discover the Pipenv managed information.
  pipenv_facts:
    path: /path/to/Pipfile/containing/folder
  register: pipenv_facts
```

There is already https://github.com/kennethreitz/pipenvlib for programmatically inspecting/manipulating Pipenv projects.

I'll take a stab at implementing this if we're in agreement!

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

pipenv
pipenv_facts

##### ADDITIONAL INFORMATION

```yaml

```
