### ISSUE TITLE
win_domain_user: Reports server instance not found on the given port

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#45916]
##### SUMMARY
Since we updated our devel branch, we have seen this issue very frequently.
(Before we did not have this issue)

```yaml
- name: Ensure user 'sqlsvc' exists in group 'Administrators' in AD
  win_domain_user:
    name: sqlsvc
    upn: sqlsvc@{{ windows_domain }}.aci.lab
    description: SQL service account
    password: '{{ windows_admin_password }}'
    groups:
      - Administrators
      - Users
    account_locked: no
    enabled: yes
    password_never_expires: no
    state: present
```

Results in:
```
TASK [windows-mssql-server : Ensure user 'sqlsvc' exists in group 'Administrators' in AD] *****************************************************************
task path: /home/ccla/backend/roles/windows-mssql-server/tasks/main.yml:3
fatal: [bdsol-aci51-sql-01]: FAILED! => {
    "changed": false,
    "msg": "Server instance not found on the given port.",
    "password_updated": false
}
```

I don't know if anything has changed to **win_domain_user** that could explain this.
Not sure if adding more pause would make any difference.
Between the AD join and this failed AD task there are about 15 other tasks and 1 more reboot taking about 2 minutes. These are VM's so they are quick to boot.

We only have one AD being staged per POD in these scenarios.
Not sure if we want to test for the AD being up before attempting to use it.
Maybe the module could be made to retry on failure before giving up ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_user

##### ANSIBLE VERSION
v2.8
