### ISSUE TITLE
Netbox: Creating Ansible modules

### ISSUE THREAD

**Issue by FragmentedPacket** [ansible/ansible#45948]
##### SUMMARY

Netbox modules for Ansible and how to go about laying out the modules
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

netbox_device
netbox_ip_address
netbox_*
##### Module layout
I'm not quite sure how I should layout the modules for what they should do and if I should break them out to a granular level.

I will use a Netbox device as an example, but this can apply to ip addresses, prefixes, racks, etc.

- Add/Remove Device

- If the `state:` is defined as `present` and the data defined in the playbook differs from what is in Netbox, PUT/PATCH the diff into Netbox

- Gather facts (for example of a device, it would gather the config_context or possibly associated interfaces/IPs)

Should all those be in a single module? Or should they be broken out such as:
netbox_device (create/remove/patch device)
netbox_facts_device (gather facts of the device)
netbox_facts (and they specify the facts to be gathered, ex. device, ip, prefix, etc.)

Also,
I assume with all these different things to be accomplished, I'd also create a 'package' in `module_utils/net_tools/netbox/` to have most of the complicated logic outside of the modules themselves.

Is that structure fine or should I break it out further?
ex.
netbox_facts_device
netbox_device

##### Possible playbook for devices
```yaml
netbox_device:
  url: http://netbox.local/
  token: thisIsMyToken
  data:
    name: Test
    device_type: Cisco
    site: TestSite
    device_role: Core Switch
    status: Active
  state: present
  gather_facts: yes
```
