### ISSUE TITLE
route53: idempotency problems for multiple CAA entries for same record

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#45970]
##### SUMMARY
When using the `route53` module for CAA records with more than one entry, existing CAA records with the same value are sometimes re-created / overwritten even though the task should be idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
route53

##### ANSIBLE VERSION
```
2.7.0
```
(happens also with 2.6.x and 2.5.x)

##### STEPS TO REPRODUCE
Running the below task at least two times should result in no change after the first time. Sometimes, it will change on some later invocations, though.
```yaml
- route53:
  zone: example.com
  record: example.com
  type: CAA
  value:
  - 0 issue "letsencrypt.org;"
  - 0 issuewild "letsencrypt.org;"
  state: present
  overwrite: true
```

##### EXPECTED RESULTS
First iteration changes (if CAA wasn't set to this before), and other iterations all have no change.

##### ACTUAL RESULTS
Random iterations have changes, others have no changes.
