### ISSUE TITLE
`when` conditional should considered before evaluating `loop`

### ISSUE THREAD

**Issue by MichalTaratuta** [ansible/ansible#45976]
##### SUMMARY
`when` conditional should be considered/checked before `loop`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

when
loop
!component
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/lookups']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/modules']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Ubuntu 16.04.3 LTS
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost

  vars:
    null_var:

  tasks:
    - name: test loop
      debug:
        msg:  "{{item}}"
      loop: "{{null_var}}"
      when: 
        - null_var
```

##### EXPECTED RESULTS

Task should be **skipped**

##### ACTUAL RESULTS

`loop` is evaluated before `when`

```paste below
fatal: [localhost]: FAILED! => {
    "msg": "Invalid data passed to 'loop', it requires a list, got this instead: None. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."
}
```
