### ISSUE TITLE
specific tag not working from role using ansible-playbook 

### ISSUE THREAD

**Issue by thatsk** [ansible/ansible#45973]
##### SUMMARY
When i want to use specific tag in playbook from role it will run all task which is defined in role.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-core

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/playbooks/example/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ansible 2.6.1
  config file = /etc/ansible/playbooks/example/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE

```yaml
roles/common/tasks/main.yml
---
- name: running puppet on {{ansible_hostname}} and fail if anything goes wrong
  puppet:
  register: puppet_result
  changed_when: puppet_result == 2
  failed_when: puppet_result !=2 and puppet_result.rc != 0
  tags:
    - puppet

- name: Reloading Service on {{ansible_hostname}}
  service:
    name: "{{ item.name }}"
    state: reloaded
  with_items:
    - { name: 'httpd'}
    - { name: 'varnish'}
  tags:
    - reloadservice

- name: checking the service status {{ansible_hostname}}
  service:
    name: "{{item.name}}"
    state: started
  with_items:
    - { name: 'httpd' }
    - { name: 'varnish'}
  tags:
    - servicestatus

- name: Checking Healthcheck
  uri:
    url: "{{item.healthcheck}}"
    method: GET
    force_basic_auth: no
    status_code: 200
    return_content: yes
  register: uriresult
  until: ( 'OK' in uriresult.msg )
  retries: 5
  delay: 10
  with_items:
    - { healthcheck: 'http://localhost:80/varnish/monitoring/health' }
    - { healthcheck: 'http://localhost:80/check.txt' }
  tags:
    -  healthcheck
```

```YAML
playbook.yaml
- name: testing specific tag from role
  hosts: localhost
  vars_files:
    - /etc/ansible/inventories/mobitv/paytv.smf1.mobitv/group_vars/common.yaml
  serial: 1
  roles:
    - common
  tags:
    - reloadservice
```

##### EXPECTED RESULTS
it wants to just reload service

##### ACTUAL RESULTS

```
it will run whole role tasks like puppet reloadservice servicestatus healthcheck
Also it will run via command line if i am remove tag from playbook and give it in command line
```
