### ISSUE TITLE
Get error when using with_items and when condition

### ISSUE THREAD

**Issue by Alexhha** [ansible/ansible#45974]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.6.4
  config file = None
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
DISPLAY_SKIPPED_HOSTS(env: DISPLAY_SKIPPED_HOSTS) = False
```

##### OS / ENVIRONMENT
Alpine Linux 3.8

##### STEPS TO REPRODUCE
```
$ ansible-playbook main.yml -e stack_action=create
$ ansible-playbook main.yml -e stack_action=destroy
```

```yaml
- name: Create Google load balancer
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get load balancer health status
      shell: |
        echo "health status: line1"
        echo "health status: line2"
        echo "health status: line3"
      register: gce_lb_health_check_result
      when: stack_action == "create"

    - name: Print status without filter
      debug: msg="{{ item }}"
      with_items: "{{ gce_lb_health_check_result.stdout_lines }}"
      when: stack_action == "create"

    - name: Print status with filter
      debug: msg="{{ item }}"
      with_items: "{{ gce_lb_health_check_result.stdout_lines | to_nice_json }}"
      when: stack_action == "create"
```

##### EXPECTED RESULTS
When we use stack_action other than "create" both tasks should be skipped

##### ACTUAL RESULTS
```paste below
$ ansible-playbook main.yml -e stack_action=destroy

PLAY [Create Google load balancer] ***********************************************************************************

TASK [Get load balancer health status] *******************************************************************************
Friday 21 September 2018  15:08:57 +0300 (0:00:00.043)       0:00:00.043 ****** 
skipping: [localhost]

TASK [Print status without filter] ***********************************************************************************
Friday 21 September 2018  15:08:57 +0300 (0:00:00.019)       0:00:00.063 ****** 
skipping: [localhost]

TASK [Print status with filter] **************************************************************************************
Friday 21 September 2018  15:08:57 +0300 (0:00:00.018)       0:00:00.081 ****** 
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ gce_lb_health_check_result.stdout_lines | to_nice_json }}): Undefined is not JSON serializable"}
	to retry, use: --limit @/home/alex/sandbox/ansible/with-items-issue/main.retry

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

If we use just debug without with_items - everything working fine

```
$ ansible-playbook main2.yml -e stack_action=destroy

PLAY [Create Google load balancer] ***********************************************************************************

TASK [Get load balancer health status] *******************************************************************************
Friday 21 September 2018  15:17:43 +0300 (0:00:00.046)       0:00:00.046 ****** 
skipping: [localhost]

TASK [Print status without filter] ***********************************************************************************
Friday 21 September 2018  15:17:43 +0300 (0:00:00.015)       0:00:00.062 ****** 
skipping: [localhost]

TASK [Print status with filter] **************************************************************************************
Friday 21 September 2018  15:17:43 +0300 (0:00:00.015)       0:00:00.078 ****** 
skipping: [localhost]

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0
```
