### ISSUE TITLE
Docs: Create URL to search by reference

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#45985]
##### SUMMARY
At the moment `seealso` reference by rst `ref` do not translate into the reference title or link.
Especially the link is an issue, as we provide no way to access the document.

The current implementation results in:
```
SEE ALSO:
      * Ansible documentation [aci_guide]
           Detailed information on how to manage your ACI infrastructure using Ansible.
           https://docs.ansible.com/ansible/devel/#stq=aci_guide&stp=1
      * Ansible documentation [aci_dev_guide]
           Detailed guide on how to write your own Cisco ACI modules to contribute.
           https://docs.ansible.com/ansible/devel/#stq=aci_dev_guide&stp=1
```

from the following doc source:
```yaml
seealso:
- ref: aci_guide
  description: Detailed information on how to manage your ACI infrastructure using Ansible.
- ref: aci_dev_guide
  description: Detailed guide on how to write your own Cisco ACI modules to contribute.```
```
This relates to: https://github.com/ansible/ansible/pull/45949

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-doc

##### ADDITIONAL INFORMATION
We have three options here (in order of preference):
- Add a feature to Sphinx so that references become searchable (most efficient)
- Generate a list with all references and a link to the reference (easiest to implement)
  - So we can make a link to it: https://docs.ansible.com/ansible/devel/references.html#aci_dev_guide
- Let ansible-doc parse the RST documentation files to look up title and link (functionally best)
