### ISSUE TITLE
JIRA Module required params bug

### ISSUE THREAD

**Issue by stobias123** [ansible/ansible#46022]
##### SUMMARY
Description field is not available on issue create screen. Description is required for module to run create operation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
jira

##### ANSIBLE VERSION

```paste below
ansible 2.7.0.a1.post0
  config file = /home/repos/Ansible/playbooks/ansible.cfg
  configured module search path = ['/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Mar 29 2018, 18:20:46) [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]

```
##### OS / ENVIRONMENT
Fdora 28

##### STEPS TO REPRODUCE
Create an issue, disable the "description" field on the create screen. 
Try to create a ticket with below jira syntax.

```yaml
  - name: Create theTicket
    jira:
      timeout: 20
      uri: '{{ jira_server }}'
      username: '{{ jira_username }}'
      password: '{{ jira_password }}'
      validate_certs: false
      issuetype: "System Request"
      project: proj
      operation: create
      summary: "test"
```

##### EXPECTED RESULTS
I want to be able to create the issue even if description is not enabled.

##### ACTUAL RESULTS
Without description field set.
```
Operation create require the following missing parameters: description
```

Adding Description field returns 
```
HTTP Error 400: 
```

Debugging further shows the 400 returns the below
```
{"errorMessages":[],"errors":{"description":"Field 'description' cannot be set. It is not on the appropriate screen, or unknown."}}
```
