### ISSUE TITLE
aws_s3 module doesn't honor the overwrite directive (yes or different)

### ISSUE THREAD

**Issue by gator2003** [ansible/ansible#46040]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_s3

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = maintuser
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL 7.5, AWS, EPEL enabled, boto, boto3, botocore installed and at the latest versions as of 9/22/2018. SELinux is enabled (but turning it off had no effect). The interactions with AWS are based on an IAM role.

##### STEPS TO REPRODUCE
ansible-playbook test.yml -vvvv

(I tried putting "different" in double quotes and single quotes)

```
---
- name: Test stuff
  hosts: ops
  gather_facts: yes
  become: yes
  vars:
    aws_region: us-gov-west-1
  tasks:
    
  - name: Create the zips directory
    file:
      path: /tmp/zips
      state: directory

  - name: Get the latest JDK rpm from S3
    aws_s3:
      bucket: swbucket
      object:bin/jdk.rpm
      dest: /tmp/zips/jdk.rpm
      mode: get
      region: "{{ aws_region }}"
      overwrite: different
      retries: 2
```

##### EXPECTED RESULTS
Ansible checks the file in S3, overwrites it if the S3 version is newer or skips it if it's the same file.

##### ACTUAL RESULTS
Getting an error saying the file already exists. The overwrite option is not present in the debug output. (A workaround is to remove the file and re-get it from S3)

```
fatal: [mnpops]: FAILED! => {
    "changed": false, 
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\nFIPS mode initialized\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 11323\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to mnpops closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_TbMeKm/ansible_module_aws_s3.py\", line 908, in <module>\r\n    main()\r\n  File \"/tmp/ansible_TbMeKm/ansible_module_aws_s3.py\", line 754, in main\r\n    if keysum_compare(module, dest, s3, bucket, obj, version=version):\r\n  File \"/tmp/ansible_TbMeKm/ansible_module_aws_s3.py\", line 332, in keysum_compare\r\n    hash = hashlib.md5(data)\r\nValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

```
Traceback (most recent call last):
  File "/tmp/ansible_TbMeKm/ansible_module_aws_s3.py", line 908, in <module>
    main()
  File "/tmp/ansible_TbMeKm/ansible_module_aws_s3.py", line 754, in main
    if keysum_compare(module, dest, s3, bucket, obj, version=version):
  File "/tmp/ansible_TbMeKm/ansible_module_aws_s3.py", line 332, in keysum_compare
    hash = hashlib.md5(data)
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```
