### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by Vinutha-Garimella** [ansible/ansible#46054]
ISSUE TYPE
Documentation Report

COMPONENT NAME
apt_key

ANSIBLE VERSION
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/user1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

CONFIGURATION
 I was running the curl command to install docker 

OS / ENVIRONMENT
Mac OS

SUMMARY
The problem is as follows

YAML FILE
```yaml
---
# curl -sSL https://get.docker.com | sh

- name: install docker
  apt_key:
    url: https://get.docker.com
    state: present
...
```
ACTUAL RESULTS
```
 FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key add -", "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: no valid OpenPGP data found.", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: no valid OpenPGP data found.\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "gpg: no valid OpenPGP data found."], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/Users/user1/ovh-machine-setup/main.retry
```
docs 
nothing 

module 
ansible

template
no template used

**Comment by ansibot** [comment]
@Vinutha96 Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This error is indicating that your URL did not produce an APT key file.

That URL downloads a shell script which is incompatible with the `apt_key` module.

You will instead need to use a task such as:

```
- name: Add docker apt-key
  apt_key:
    id: '0EBFCD88'
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
```

See https://docs.docker.com/install/linux/docker-ce/debian/ for more information.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
