### ISSUE TITLE
group_module: Broken pipe\r\ndebug2 Shared connection to closed.\r\n

### ISSUE THREAD

**Issue by BananenKeks** [ansible/ansible#46057]
##### SUMMARY

SSH-Connection breaks during play with multiple hosts. I try to set up our system for inventory. While i go through my playbook, some servers just fail. This happens when i hit the part where i try to add a group for the necessary user. Though before that i issue a task to install python (see below) that doesn't break. Those two tasks are not in the same playbook. The Python part is in the common role while the group part is in the inventory role and the play executes both of them jumping from common to inventory.

I can't tell much about the target hosts. Though it happens to a lot of my targets.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

group

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below
nothing
```

##### OS / ENVIRONMENT

Ansible Server: CentOS Linux release 7.4.1708 (Core)
Target Server: CentOS release 5.8 (Final) Python 2.7.5

##### STEPS TO REPRODUCE

The first play installs Python on the machine which works perfectly fine.
The second play should create a group called inv. This doesn't work.
Both plays are separated in different roles and called by the same host.

```yaml

main.yml
- hosts: target-group
  gather_facts: false
  roles:
    - common
    - inventory
  remote_user: root

common/tasks/main.yml
- name: Install python2 for Ansible
  raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python)"
  register: output
  changed_when:
  - output.stdout != ""
  - output.stdout != "\r\n"

inventory/tasks/main.yml
- name: add inv group
  group:
    name: inv
```

##### EXPECTED RESULTS

the group inv should be added

##### ACTUAL RESULTS

```paste below
fatal: [host.domainname.tld]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 32554\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to host.domainname.tld closed.\r\n",
    "module_stdout": "  File \"/tmp/ansible_6fSBsr/ansible_module_group.py\", line 7\r\n    from __future__ import absolute_import, division, print_function\r\nSyntaxError: future feature absolute_import is not defined\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

```
