### ISSUE TITLE
apt_key fails to add new OpenPGP packets to existing keys

### ISSUE THREAD

**Issue by KellerFuchs** [ansible/ansible#46053]
##### SUMMARY
If a primary OpenPGP key already exists under `/etc/apt/trusted.gpg.d`, and `apt_key` is called with `data` containing new key packets (for instance, a new signing subkey, or a change in expiration date) it will simply return `ok` (no change) and fail to update the repository key.

This seems to be the root cause of another open bug against apt_key, #25070 (duplicated as #41020).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apt_key

##### ANSIBLE VERSION
```paste below
ansible 2.6.4
  config file = /tmp/apt-key_repro/ansible.cfg
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Aug 31 2018, 11:56:52) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/tmp/apt-key_repro/ansible.cfg) = True
ANSIBLE_PIPELINING(/tmp/apt-key_repro/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/tmp/apt-key_repro/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_GATHERING(/tmp/apt-key_repro/ansible.cfg) = smart
DEFAULT_HOST_LIST(/tmp/apt-key_repro/ansible.cfg) = [u'/tmp/apt-key_repro/.vagrant/provisioners/ansible/inventory']
DEFAULT_LOG_PATH(/tmp/apt-key_repro/ansible.cfg) = /tmp/apt-key_repro/log
```

##### OS / ENVIRONMENT
Debian buster “testing”, amd64

##### STEPS TO REPRODUCE
I have a standalone [reproducing example](https://gist.github.com/KellerFuchs/d60a46c4722e2d60eee7004f8b3d1f41), which mostly runs the following playbook on a fresh Debian system:

```yaml
---
- hosts: default
  become: yes
  pre_tasks:
    - name: Setup a pre-existing keyring
      copy:
        src: deb.torproject.org-keyring.gpg
        dest: /etc/apt/trusted.gpg.d/

  tasks:
    - # This is the buggy call:
      #  it will fail to update deb.torproject.org-keyring.gpg even though
      #  tor.asc contains a new signing subkey for the reposirory key.
      apt_key:
        data: "{{ lookup('file', 'tor.asc') }}"
        id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
        keyring: /etc/apt/trusted.gpg.d/deb.torproject.org-keyring.gpg
    
    - # Setup the repote repository
      # Fails due to the previous task failing to update the keyring
      apt_repository:
        repo: deb https://deb.torproject.org/torproject.org stretch main
        state: present
        filename: tor

    - # Now, apt update fails
      apt:
        update_cache: yes
```

##### EXPECTED RESULTS
The playbook runs through successfully.

##### ACTUAL RESULTS

```paste below
$ vagrant provision
==> default: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.6.4).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    default: Running ansible-playbook...

PLAY [default] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Setup a pre-existing keyring] ********************************************
ok: [default]

TASK [apt_key] *****************************************************************
ok: [default]

TASK [apt_repository] **********************************************************
ok: [default]

TASK [apt] *********************************************************************
fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: https://deb.torproject.org/torproject.org stretch InRelease: The following signatures were invalid: EXPKEYSIG 74A941BA219EC810 deb.torproject.org archive signing key, E:The repository 'https://deb.torproject.org/torproject.org stretch InRelease' is not signed."}
        to retry, use: --limit @/tmp/apt-key_repro/test.retry

PLAY RECAP *********************************************************************
default                    : ok=4    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
vagrant provision  5.81s user 1.48s system 24% cpu 29.813 total
```
