### ISSUE TITLE
postgresql_privs does not see already created group on remote host

### ISSUE THREAD

**Issue by grasum** [ansible/ansible#46069]
##### SUMMARY
I am trying to grant an existing group "support" new privilages on a schema using ansible. This group is not created using ansible. 
I have tried with existing users and the output is the same *username*/*groupname* does not exist.

I thought this was related to the connection, but I am able to drop and create schemas.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_privs

##### ANSIBLE VERSION
ansible 2.8.0.dev0

##### OS / ENVIRONMENT
amazon ami 1
Trying to execute on Redshift db.

##### STEPS TO REPRODUCE
```
- name: Grant privileges
  postgresql_privs:
    database: "{{ database }}"
    login_host: "{{ login_host }}"
    port: "{{ db_port }}"
    login_user: "{{ redshift_user }}"
    login_password: "{{ redshift_user_pass }}"
    grant_option: yes
    privs: usage
    type: schema
    obj: "{{ item }}" 
    role: support
    state: present
  with_items:
    - "{{ schemas }}"
```
##### EXPECTED RESULTS
Group ''support'' now has usage privilages on specified schemas

##### ACTUAL RESULTS
    "msg": "user \"support\" does not exist\n"
