### ISSUE TITLE
ansible module for keycloak realms

### ISSUE THREAD

**Issue by anotherthomas** [ansible/ansible#46061]
##### SUMMARY
There is an ansible module for keycloak clients and client templates, but none for realms.
To automate the whole setup, a module to manage realms would be really useful.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
keycloak_realm

##### ADDITIONAL INFORMATION

```yaml
- name: Create or update Keycloak realm
  local_action:
    module: keycloak_realm
    auth_client_id: admin-cli
    auth_keycloak_url: https://auth.example.com/auth
    auth_realm: master
    auth_username: USERNAME
    auth_password: PASSWORD
    realm_id: some_realm
    state: present

```
