### ISSUE TITLE
--start-at-task does not work with group-by groups, at least not for group-by ansible_os_family

### ISSUE THREAD

**Issue by darKoram** [ansible/ansible#4609]
--start-at-task does not work with group-by groups, at least not for group-by ansible_os_family

If hosts is one dynamically generated by group-by, --start-at-task="common | Task1" will skip all tasks.

$ ansible-playbook -i hosts site.yml  -u root --start-at-task="common | Task1"

PLAY [RedHat] ****************************************************************\* 
skipping: no hosts matched

if hosts is changed to something in hosts file, start-at-task works. 

see gist for details: 
https://gist.github.com/darKoram/7078413

```
- hosts: all
  tasks:
    - group_by: key={{ ansible_os_family }}

- hosts: group_defined_in_hosts_file
#- hosts: RedHat
   gather_facts: False
   vars_files:
      - "vars/{{ansible_os_family}}.yml"
   roles:
     - common
```
