### ISSUE TITLE
variables in group_vars and host_vars do not load when using inventory directory

### ISSUE THREAD

**Issue by programingnotes** [ansible/ansible#46096]
##### SUMMARY
When following a directory structure that [mimics the one in docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#alternative-directory-layout), variables in `group_vars` and `host-vars` are not loaded. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`user` module

##### ANSIBLE VERSION

```paste below
ansible 2.6.3
  config file = /Users/pnotes/.ansible.cfg
  configured module search path = ['/Users/pnotes/.ansible/plugins/modules, /usr/share/ansible/plugins/modules, /Users/pnotes/Code/Ansible']
  ansible python module location = /Users/pnotes/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ansible
  executable location = /Users/pnotes/.pyenv/versions/3.6.4/bin/ansible
  python version = 3.6.4 (default, Feb 26 2018, 21:07:35) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
DEFAULT_MODULE_PATH(/Users/pnotes/.ansible.cfg) = ['/Users/pnotes/.ansible/plugins/modules, /usr/share/ansible/plugin
```

##### OS / ENVIRONMENT

target OS version: Ubuntu 16.04

##### STEPS TO REPRODUCE

Given this directory structure:
```
├── ansible.cfg
├── inventories
│   └── test
│       ├── group_vars
│       │   └── all.yml
│       ├── host_vars
│       │   └── all.yml
│       └── hosts.ini
├── provision.yml
└── roles
    └── create-admin-user
        ├── handlers
        │   └── main.yml
        └── tasks
            └── main.yml
```

> Note that is directory layout follows that given in the [docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#alternative-directory-layout)

And `roles/create-admin-user/tasks/main.yml` defined like so:  
```
- name: Create the non-root user account 
  user:
    name: "{{ admin_user.name }}"
    password: "{{ admin_user.password | password_hash('sha512') }}"
    update_password: on_create
    group: sudo
    groups: sudo
    append: yes
    create_home: yes
    shell: /bin/bash
```

I expect the task, **create-admin-user**, defined above to pick variables defined in `inventories/test/group_vars/all.yml`  and `inventories/test/host_vars/all.yml`  but the error message which is returned when I run `ansible-playbook -i inventories/test/hosts.ini provision.yml` indicates that it does not: 
```
TASK [create-admin-user : Create the non-root user account] ********************
fatal: [415.791.30.131]: FAILED! => {"msg": "The task includes an option with an 
undefined variable. 
The error was: 'admin_user' is undefined\n\nThe error appears to have been in '/Users/pnotes/Code/terraform/pj1/ansi/roles/create-admin-user/tasks/main.yml':
 line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax 
problem.\n\nThe offending line appears to be:\n\n---\n- name: Task 1\n  ^ here\n"}
``` 

This doesn't make sense to me given that `inventories/test/group_vars/all.yml` && `inventories/test/host_vars/all.ym`l both follow this structure:
```
---
admin_user: 
  name: somename
  password: "somepassword"
  ssh_public_key: '/Users/pnotes/.ssh/path_to_priKey'
```

##### EXPECTED RESULTS
I expect admin_user.name to be picked up and evaluated correctly.
