### ISSUE TITLE
[k8s module] User cannot list all services in the cluster

### ISSUE THREAD

**Issue by jpopelka** [ansible/ansible#46125]
##### SUMMARY
When trying some examples from documentation I'm seeing errors about user not able to retrieve objects.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jpopelka/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
```
$ oc version
oc v3.9.0
kubernetes v1.9.1+cbc5b49
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

$ pip list | grep openshift
openshift           0.7.1    
$ pip list | grep kubernetes
kubernetes          7.0.0
```

##### STEPS TO REPRODUCE
Start local Openshift cluster with `oc cluster up`.
Run the following playbook:

```yaml
- name: testing playbook
  hosts: localhost
  tasks:
    - name: Get a list of all service objects
      k8s:
        api_version: v1
        kind: ServiceList
        host: https://127.0.0.1:8443
        api_key: my-api-key
        verify_ssl: false
      register: service_list
```

##### EXPECTED RESULTS
List of services is returned.

##### ACTUAL RESULTS
```
The full traceback is:
  File "/tmp/ansible_bZy7UF/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 121, in perform_action
    existing = resource.get(name=name, namespace=namespace)
  File "/home/jpopelka/.local/lib/python2.7/site-packages/openshift/dynamic/client.py", line 33, in inner
    raise api_exception(e)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "error": 403, 
    "invocation": {
        "module_args": {
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "cert_file": null, 
            "context": null, 
            "force": false, 
            "host": "https://127.0.0.1:8443", 
            "key_file": null, 
            "kubeconfig": null, 
            "password": null, 
            "ssl_ca_cert": null, 
            "state": "present", 
            "username": null, 
            "verify_ssl": false
        }
    }, 
    "msg": "Failed to retrieve requested object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"services is forbidden: User \\\"developer\\\" cannot list services at the cluster scope: User \\\"developer\\\" cannot list all services in the cluster\",\"reason\":\"Forbidden\",\"details\":{\"kind\":\"services\"},\"code\":403}\n", 
    "reason": "Forbidden", 
    "status": 403
}
```

Even the 'developer' is able to list the services:
```
$ oc whoami
developer
$ oc get services
NAME      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
redis     ClusterIP   172.30.200.9   <none>        6379/TCP   59m
```

I see the same when trying this against remote Openshift cluster.
And when I try to deploy the above listed service from a template (which is OK) with
```yaml
    - name: Deploy Redis
      k8s:
        state: present
        src: "../templates/redis.yml"
```
I see `User "developer" cannot get templates at the cluster scope`
