### ISSUE TITLE
synchronize fails --out-format not formatted properly

### ISSUE THREAD

**Issue by Mixer9** [ansible/ansible#46126]
##### SUMMARY
synchronize fails with connection refused, however if I take the rsync command out of the error and add single quotes around the value in --out-format and run it manually it works with no error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
synchronize module

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /home/v683653/development/ops/redhat/ansible/ansible.cfg
  configured module search path = [u'/home/v683653/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/v683653/development/ops/redhat/ansible/ansible.cfg) = [u'/home/v683653/development/ops/redhat/ansible/inventory/hosts.inv']
DEFAULT_TIMEOUT(/home/v683653/development/ops/redhat/ansible/ansible.cfg) = 120

```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE

Run the following and it should fail with the error in the actual results below.

```
- name: Send files to Webserver
  hosts: localhost
  gather_facts: no

  tasks:

    - name: copy reports to web server
      synchronize:
        src: /tmp/reports/
        dest: rsync://remotehost/var/www/html/pub/oscap/
        mode: push
      become_user: v683653

```

##### EXPECTED RESULTS

Expected to have directory synced to remote host

##### ACTUAL RESULTS

```
TASK [copy reports to web server] ****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /tmp/reports/ rsync://remotehost/var/www/html/pub/oscap/", "msg": "rsync: failed to connect to remotehost (172.16.100.31): Connection refused (111)\nrsync error: error in socket IO (code 10) at clientserver.c(125) [sender=3.1.2]\n", "rc": 10}

```
