### ISSUE TITLE
nsupdate module doesn't modify TTL on existing records

### ISSUE THREAD

**Issue by imcdona** [ansible/ansible#46136]
##### SUMMARY
The nsupdate module doesn't modify the TTL of existing records.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
CentOS Linux release 7.5.1804 (Core)
BIND 9.9.4

##### STEPS TO REPRODUCE

```yaml

- name: Set TTL of existing A record ansible.example.com to 300 seconds
  nsupdate:
    key_name: "nsupdate"
    key_secret: "+bFQtBCta7j2vWkjPkAFtgA=="
    server: "10.1.1.1"
    zone: "example.org"
    record: "ansible"
    value: "192.168.1.3"
    ttl: 300

```

##### EXPECTED RESULTS
The nsupdate module should update the TTL of the existing record with the TTL specified in the playbook

##### ACTUAL RESULTS

The TTL of the record in question isn't modified

```paste below

```
