### ISSUE TITLE
`when:` does not interpolate `item` from `with_items` in some cases

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#4614]
``` sh
$ ansible --version
ansible 1.3.2
```

My task is located in `./roles/php/tasks/main.yml`:

``` yaml
- name: Install {{ version }} package modules
  yum: pkg={{ version['modules'][item]['name'] }} state=present
  with_items: modules
  when: version['modules'][item]['source'] == 'rpm'
```

`modules` is a simple list set as a default:

``` yaml
# ./roles/php/defaults/main.yml
modules:
  - cli
  - gd
```

It is used to locate install mechanisms for various PHP modules, specified by a `version` variable:

``` yaml
php54:
  modules:
    cli:
      source: rpm
      name: php54-cli
    gd:
      source: rpm
      name: php54-gd
```

The idea is that a developer can use the role quite easily:

``` yaml
roles:
  - { role: php, modules: ['cli', 'gd'] }
```

In [all cases I've tried](https://gist.github.com/garethrees/d7ebb541dd4672962bb2), the current iteration of `with_items` is not interpolated in to the `when` conditional correctly:

``` sh
  # TASK: [Install {{version}} package modules] ***********************************
  # fatal: [192.168.33.11] => error while evaluating conditional:
  # {% if version['modules'][item]['source'] == 'rpm' %}
  #   True
  # {% else %}
  #   False
  # {% endif %}
```

A [similar task](https://gist.github.com/garethrees/d7ebb541dd4672962bb2#file-tasks-main-yml-L6-L19) is successful.
