### ISSUE TITLE
Cannot assign a static ip to a docker container using a network with configured subnet

### ISSUE THREAD

**Issue by jvenezia** [ansible/ansible#46144]
##### SUMMARY
Getting error "user specified IP address is supported only when connecting to networks with user configured subnets" while I am using a custom network with a configured subnet.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_network
docker_container

##### ANSIBLE VERSION
```paste below
ansible 2.6.3
  config file = /Users/jvenezia/Development/Personnal/Home/ansible.cfg
  configured module search path = ['/Users/jvenezia/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Mar 30 2018, 06:41:53) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```paste below
DEFAULT_STDOUT_CALLBACK(/Users/jvenezia/Development/Personnal/Home/ansible.cfg) = debug
```

##### STEPS TO REPRODUCE
Create a docker network with `docker_network`, with a name, a subnet and a gateway.
Create a docker container using the previously created network, and give it a static ip.

```yaml
- name: network
  become: yes
  docker_network:
    name: my_network
    ipam_options:
      subnet: '172.18.0.0/16'
      gateway: 172.18.0.1

- name: container
  become: yes
  docker_container:
    name: my_container
    image: my_container
    state: started
    restart: yes
    restart_policy: always
    networks:
    - name: my_network
      ipv4_address: 172.18.0.10
    capabilities:
    - NET_ADMIN
    devices:
    - /dev/net/tun
```

##### EXPECTED RESULTS
Creates the container with ip 172.18.0.10

##### ACTUAL RESULTS
```paste below
Error connecting container to network my_network - 400 Client Error: Bad Request ("user specified IP address is supported only when connecting to networks with user configured subnets")
```

If I dont specify `ipv4_address: 172.18.0.10` in the `docker_container`, the container is correctly attached to `my_network` and is given an ip correctly (but I can't choose it).
