### ISSUE TITLE
Grafana_dashboard - not creating new dashboards

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#46152]
##### SUMMARY
My goal is to create grafana dashboard and seems that latest changes are not allowing create new dashboard. When dashboard already exists - is updated, however when doesn't exists ansible report error: 
```
msg: 'error : Unable to create the new dashboard iMKVMFAmk : 404 - {''body'': ''{"message":"Dashboard not found","status":"not-found"}'', ''status'': 404, ''content-length'': ''54'', ''url'': ...
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_dashboard

##### ANSIBLE VERSION
```
ansible --version
ansible 2.6.4
```

##### OS / ENVIRONMENT
MacOS - runing with `hosts: localhost`

##### STEPS TO REPRODUCE
- Setup grafana instance (>=5.0)
- Create API Key in grafana GUI
- Create dashboard via grafana GUI
- Export dashboard to JSON
- Destroy dashboard via grafana GUI
- Run playbook to create grafana dashboard via Ansible (Read data from exported JSON)

```yaml
    - name: Test importing grafana dashboard
      grafana_dashboard_27:
        grafana_url: "http://grafana.test"
        grafana_api_key: "{{ api_key.grafana }}"
        state: present
        uid: "iMKVMFAmk"
        message: Updated by ansible
        overwrite: yes
        path: "{{ dashboard_file }}"
```

- `grafana_dashboard_27` - this is latest module from ansible-devel which is not released yet: installed locally on `library` folder: Based on issue: https://github.com/ansible/ansible/pull/41249 (will be released in ansible 2.7)

##### EXPECTED RESULTS
```yaml
changed: [localhost] => changed=true
  invocation:
    module_args:
      ...
```

##### ACTUAL RESULTS
```yaml
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
```

```
The full traceback is:
  File "/var/folders/vr/fw2t1ncd4lj7d4m9ng_8pfqr0000gn/T/ansible_N_8ZD6/ansible_module_grafana_dashboard_27.py", line 412, in main
    result = grafana_create_dashboard(module, module.params)
  File "/var/folders/vr/fw2t1ncd4lj7d4m9ng_8pfqr0000gn/T/ansible_N_8ZD6/ansible_module_grafana_dashboard_27.py", line 299, in grafana_create_dashboard
    raise GrafanaAPIException('Unable to create the new dashboard %s : %s - %s.' % (uid, info['status'], info))
```

##### Details about module:
```bash
# grafana_dashboard_27 - was created from Ansible Git branch
git lg -1
* f73996e6eb - (HEAD -> devel)
md5 grafana_dashboard.py
MD5 (grafana_dashboard.py) = 51bfdd7f6d550926fb25c29ee7468a82
# cp grafana_dashboard.py -> ansible_project_root/library/grafana_dashboard_27.py
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/grafana_dashboard.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/grafana_dashboard.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by marcinpraczko** [comment]
This is small fix which I've done locally and seems fixed issue (at least for creating grafana dashboard)
```diff
diff -u grafana_dashboard_orig.py grafana_dashboard_27.py
--- grafana_dashboard_orig.py   
+++ grafana_dashboard_27.py
@@ -277,9 +277,14 @@
                 body = json.loads(info['body'])
                 raise GrafanaAPIException('Unable to update the dashboard %s : %s' % (uid, body['message']))
     else:
-        # create
+        # create (During create ID and UID doesn't exists yet)
+        payload['id'] = None
+        payload['uid'] = None
         if 'dashboard' not in payload:
             payload = {'dashboard': payload}
         r, info = fetch_url(module, '%s/api/dashboards/db' % data['grafana_url'], data=json.dumps(payload), headers=headers, method='POST')
         if info['status'] == 200:
             result['msg'] = "Dashboard %s created" % uid
```

- Re-run my playbook returned
```yaml
changed: [localhost] => changed=true                                                                                                                                                               [44/1936]
  invocation:
    module_args:
      client_cert: null
      client_key: null
      grafana_api_key: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      grafana_url: http://grafana.test
      message: Updated by ansible
      org_id: 1
      overwrite: true
      ...
      slug: null
      state: present
      uid: iMKVMFAmk
      ...
      use_proxy: true
      validate_certs: true
  msg: Dashboard iMKVMFAmk created
  uid: QwrUAp0iz
```

Details about creating dashboard in grafana was taken from:
- http://docs.grafana.org/http_api/dashboard/   (Create / Update dashboard)

**Comment by s-hertel** [comment]
@marcinpraczko If you have a chance, please test that #46525 resolves the issue and give the PR a shipit.

**Comment by marcinpraczko** [comment]
Hi @s-hertel, Thank you for this work - I will review this in next 2 days and let you to know.

**Comment by jorijinnall** [comment]
@marcind Thanks. Can you review the PR ?

**Comment by jorijinnall** [comment]
@marcinpraczko  Thanks. Can you review the PR ?

**Comment by marcinpraczko** [comment]
Hi, 

I've re-run this and this is result: `grafana_dashboard_fix.py` is file from suggested branch here.

- Test01: Dashboard - not exists:
```yaml
# Ansible:
    - name: "Test importing grafana dashboard (1/2)"
      grafana_dashboard_fix:
        grafana_url: "http://g.10.0.65.201.xip.io"
        grafana_api_key: "{{ api_key.grafana }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        path: "{{ dashboard_file }}"
```

Ansible: Result
```
TASK [Test importing grafana dashboard (1/2)] *********
changed: [localhost]
```

- Test02: Dashboard - exists (re-run the same play): Expeted Changed YES - Got error instead.
The same ansible snippet

Ansible: Result
```
TASK [Test importing grafana dashboard (1/2)] *******
fatal: [localhost]: FAILED! => changed=false
  msg: 'error : Unable to create the new dashboard vnqmbpAiz : 412 - {''body'': ''{"message":"A dashboard with the same name in the folder already exists","status":"name-exists"}'', ''status'': 412, ''content-length'': ''96'', ''url'': ''http://g.10.0.65.201.xip.io/api/dashboards/db'', ''msg'': ''HTTP Error 412: Precondition Failed'', ...
```
Please note that in ansible snippet - there is settings to *overwrite* dashbord if exists: `overwrite: yes`. 
Hope that helps.

**Comment by marcinpraczko** [comment]
Hi @jorijinnall,

Also I think this more complicated and requires some intensive testing. 
I adjusted my playbook for this:
```yaml
    - name: "Test delete grafana dashboard"
      grafana_dashboard_fix:
        grafana_url: "http://g.10.0.65.201.xip.io"
        grafana_api_key: "{{ api_key.grafana }}"
        state: absent
        uid: "0VeSqSaik"
        message: Updated by ansible

    - name: "Test importing grafana dashboard (1/2)"
      grafana_dashboard_fix:
        grafana_url: "http://g.10.0.65.201.xip.io"
        grafana_api_key: "{{ api_key.grafana }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        uid: "0VeSqSaik"
        path: "{{ dashboard_file }}"
```

In short:
- During DELETE `state: absent` - UID is required. Which means that I need obtain UID before deleteing dashboard
- During CREATE `state: present` - UID exists but after creation - dashboard is getting new UID. Which means that ansible-playbook will not work to remove dashboard. So we are loosing all benefits from ansible point of view - allow automation of CREATE / UPDATE / DELETE.

I am not sure how grafana is working with this - what I would suggest is following logic:
1. Not sure if DELETE can be done on NAME - not on UID (if not UID is fine) as long as
2. During create UID can be provided and grafana will respect this UID - so ansible DELETE will work as well
3. Overwrite should allow overwrite - seems be not working at the moment.

Hope that helps.

**Comment by jorijinnall** [comment]
@marcinpraczko Thank you for your review.
I misunderstood how uid is used and works. I fixed the behaviour in the PR.

You can comment directly in https://github.com/ansible/ansible/pull/46525 and approve the change

**Comment by ansibot** [comment]
cc @seuf
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tecjam** [comment]
I tried the devel ansible branch to see if the issue persists, but overwrite still does not work for me. 
So the ansible script can not be run twice without causing this error:

```
- name: create grafana dashboard
  grafana_dashboard:
    grafana_url: "{{ monitioring_grafana_url }}"
    grafana_api_key: "{{ monitioring_grafana_token }}"
    state: present
    message: Updated by ansible
    overwrite: yes
    path: "/tmp/{{ inventory_hostname }}-grafana-panel-model.json"
```

```
fatal: [my-test-domain.com]: FAILED! => {"changed": false, "msg": "error : Unable to create the new dashboard None : 412 - {'status': 412, 'body': '{\"message\":\"A dashboard with the same name in the folder already exists\",\"status\":\"name-exists\"}', 'content-length': '96', 'url': 'https://my-grafana-domain.net/api/dashboards/db', 'expires': '-1', 'server': 'Apache/2.4.25 (Debian)', 'msg': 'HTTP Error 412: Precondition Failed', 'connection': 'close', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'date': 'Tue, 18 Jun 2019 11:42:47 GMT', 'x-frame-options': 'deny', 'content-type': 'application/json'}."}
```

**Comment by seuf** [comment]
Sorry, but I can't reproduce : 
```
---
- hosts: localhost
  tasks:
    - name: import grafana dashbaord
      grafana_dashboard:
        grafana_url: "{{ grafana_url }}
        grafana_api_key: "{{ grafana_api_key }}"
        uid: LsZ9-Gbmz
        state: present
        message: Updated by ansible
        path: /tmp/dev_servers.json
        overwrite: true
```
I can run it twice :
```
PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [import grafana dashbaord] ***********************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
If you want to overwrite an existing dashboard, you have to set the dashboard uid.
You can use the [grafana_dashboard lookup plugin](https://docs.ansible.com/ansible/latest/plugins/lookup/grafana_dashboard.html) to retrive existing dashboards.
