### ISSUE TITLE
Get the NFS Server details for datastore

### ISSUE THREAD

**Issue by Popyllol** [ansible/ansible#46156]
##### SUMMARY

It would be very nice to get more details about the VMWare datastore. In case of a NFS datastore I would love to get the NFS server and the path on the NFS server.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_datastore_facts.py

##### ADDITIONAL INFORMATION

I need the data about NFS source to select the right NetApp where I have to create a snapshot.

```yaml
  - name: "Gather guest facts"
    delegate_to: localhost
    become:      false
    vmware_guest_facts:
      hostname:       '{{ vcenter_hostname }}'
      username:       '{{ vcenter_username }}'
      password:       '{{ vcenter_password }}'
      datacenter:     '{{ vm_datacenter }}'
      validate_certs: no
      folder:         '{{ vm_folder.folders }}'
      name:           '{{ inventory_hostname }}'
    register: vm_facts

  - name: "Gather datastore facts"
    delegate_to: localhost
    become:      false
    vmware_datastore_facts:
      hostname:       '{{ vcenter_hostname }}'
      username:       '{{ vcenter_username }}'
      password:       '{{ vcenter_password }}'
      datacenter:     '{{ vm_datacenter }}'
      validate_certs: no
      name:           '{{ item }}'
    register: vm_datastore_facts
    with_items:
      - '{{ vm_facts.instance.hw_datastores }}'

  - debug:
      msg: '{{ vm_datastore_facts }}'
```
Now I get:
```
...
                    {
                        "accessible": true, 
                        "capacity": 429496729600, 
                        "datastore_cluster": "N/A", 
                        "freeSpace": 316892692480, 
                        "maintenanceMode": "normal", 
                        "multipleHostAccess": true, 
                        "name": "svm35_webapp1_web001", 
                        "provisioned": 1006747443200, 
                        "type": "NFS", 
                        "uncommitted": 894143406080, 
                        "url": "ds:///vmfs/volumes/6f8b2cfd-7de80f72/"
                    }
...
```
What I want to get:
```
...
                    {
                        "accessible": true, 
                        "capacity": 429496729600, 
                        "datastore_cluster": "N/A", 
                        "freeSpace": 316892692480, 
                        "maintenanceMode": "normal", 
                        "multipleHostAccess": true, 
                        "name": "svm35_webapp1_web001", 
                        "provisioned": 1006747443200, 
                        "type": "NFS", 
                        "nfs_server": "filer01",
                        "nfs_path": "/data",
                        "uncommitted": 894143406080, 
                        "url": "ds:///vmfs/volumes/6f8b2cfd-7de80f72/"
                    }
...
```
