### ISSUE TITLE
k8s, k8s_facts authentication via username&password does not work (unlike api_key)

### ISSUE THREAD

**Issue by jpopelka** [ansible/ansible#46163]
##### SUMMARY
When using `k8s` or `k8s_facts` modules, any time I try to authenticate via `username`/`password` it fails with `kubernetes.client.rest.ApiException: (403), Reason: Forbidden`. Authenticating via `api_key` works OK.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s, k8s_facts

##### ANSIBLE VERSION
```
ansible 2.7.0rc3
  config file = None
  configured module search path = ['/home/jpopelka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jpopelka/.virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/jpopelka/.virtualenvs/ansible/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
```
oc version
oc v3.9.0
kubernetes v1.9.1+cbc5b49
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://abc:443
openshift v3.9.40
kubernetes v1.9.1+a0ce1bc657
```
##### STEPS TO REPRODUCE
ansible-playbook -vvv the-following-yaml

```yaml
- name: testing playbook
  hosts: localhost
  tasks:
    - name: Get a list of all projects
      k8s_facts:
        kind: Project
        host: abc
        username: efg
        password: xyz
```

##### EXPECTED RESULTS
list of projects

##### ACTUAL RESULTS
```
  File "/home/jpopelka/.virtualenvs/ansible/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 26 Sep 2018 13:58:45 GMT', 'Content-Length': '301'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"projects is forbidden: User \\"system:anonymous\\" cannot list projects at the cluster scope: User \\"system:anonymous\\" cannot list all projects in the cluster","reason":"Forbidden","details":{"kind":"projects"},"code":403}\n'
```

The following works OK

```yaml
- name: testing playbook
  hosts: localhost
  tasks:
    - name: Get a list of all projects
      k8s_facts:
        kind: Project
        host: abc
        api_key: xyz
```
