### ISSUE TITLE
postgresql_user will fail if state: absent and user does not exist . 

### ISSUE THREAD

**Issue by coffee-driven** [ansible/ansible#46168]
##### SUMMARY
Ansible module postgresql_user will fail if the state of the user is absent and the user does not exist on the server. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION
```
ansible 2.6.3
  config file = /home/user/Pracovni/gitlab/devops/postgres/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Target db server: postgresql 9.5

##### STEPS TO REPRODUCE
- Create role/user in psql db 
- Set state: absent for role eq. remove user
- Run the play (remove user) 
- Run the again. Play will fail due to the non-existence of the user on the server.

```
- postgresql_user:
    db: "{{ item.db }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  with_items:
    "{{ users }}"

---

users:

 - { db: testdb, name: testuser, password: "{{ vault_passwd_testuseer }}", state: absent, ip: 1.2.3.4/24 }

```

##### EXPECTED RESULTS

Imho play should continue even if the user is not present on the server. It is similar to user module 
https://docs.ansible.com/ansible/latest/modules/user_module.html?highlight=user

_There is no problem with the user module when user state is absent and the user does not exist on the server._

##### ACTUAL RESULTS
Whole play will fail.

```
The full traceback is:
  File "/tmp/ansible_ljOJfU/ansible_module_postgresql_privs.py", line 623, in main
    schema_qualifier=p.schema
  File "/tmp/ansible_ljOJfU/ansible_module_postgresql_privs.py", line 512, in manipulate_privs
    self.cursor.execute(query % (set_what, for_whom))
failed: [testserver] (item={u'obj': None, u'option': False, u'privs': u'CONNECT', u'db': u'testdb', u'state': u'absent', u'role': u'testuser, u'type': u'database'}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "database": "testdb", 
            "grant_option": false, 
            "host": "", 
            "login": "postgres", 
            "obj": "", 
            "objs": "", 
            "password": "", 
            "port": 5432, 
            "privs": "CONNECT", 
            "role": "testuser", 
            "roles": "testuser", 
            "schema": null, 
            "ssl_mode": "prefer", 
            "ssl_rootcert": null, 
            "state": "absent", 
            "type": "database", 
            "unix_socket": ""
        }
    }, 
    "item": {
        "db": "testdb", 
        "obj": null, 
        "option": false, 
        "privs": "CONNECT", 
        "role": "testuser", 
        "state": "absent", 
        "type": "database"
    }, 
    "msg": "role \"testuser\" does not exist\n"
```

Thanks in advance.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/postgresql/postgresql_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/postgresql/postgresql_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @matburt @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andytom** [comment]
@gitm1993 Can you provide the full playbook and output that is causing this issue from looking at the traceback it seems to be the [postgresql_privs module](https://docs.ansible.com/ansible/latest/modules/postgresql_privs_module.html) that is failing not the user module.

**Comment by ansibot** [comment]
cc @Dorn- @kustodian
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gitm1993** [comment]
@andytom Hi! Thanks for the response. 

I've dug more into it and the problem is more in modules cooperation than in the module itself.

Easily described, role cannot be removed if it has some privileges, because roles and it's privs are dependent on each other. Exactly role-privs cannot be removed when a role is in the absent state.

I believe workaround for this situation will not so difficult but it is a little anoying. Anyway below is exact playbook and it's tasks.

playbook.yml

```
---
- hosts: db_test
  roles:
    - { role: postgresql, tags: postgresql}
```
tasks/main.yml

```
---
- name: install postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
    state: present
  become: true

- name: install postgresql server and related packages
  yum:
    name:
      - postgresql96-server
      - postgresql96-contrib
      - python-psycopg2
    state: present
  become: true

- block:
    - name: init postgresql db
      command: "/usr/pgsql-9.6/bin/postgresql96-setup initdb"
      args:
        creates: "/var/lib/pgsql/9.6/data/PG_VERSION"
      become: true

    - name: configure & start
      include_tasks: configure.yml

    - name: create defined users & dbs
      include_tasks: dbs_and_users.yml
```
tasks/dbs_and_users.yml

```
---
- name: create databases
  postgresql_db:
    name: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    owner: "{{ item.owner|default(omit) }}"
    template: "{{ item.template|default(omit) }}"
    encoding: "{{ item.encoding|default(omit) }}"
    lc_collate: "{{ item.lccollate|default(omit) }}"
    lc_ctype: "{{ item.lctype|default(omit) }}"
    target: "{{ item.target|default(omit) }}"
    port: "{{ item.port|default(5432) }}"
  with_items: "{{ pgsql_dbs }}"
  become: true
  become_user: postgres

- name: remove disabled privileges
  postgresql_privs:
    role: "{{ item.role }}"
    database: "{{ item.db }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type }}"
    obj: "{{ item.obj }}"
    state: "{{ item.state }}"
    grant_option: "{{ item.option }}"
    port: "{{ item.port|default(5432) }}"
  with_items: "{{ pgsql_privileges }}"
  when:
    - item.state is defined
    - item.state == "absent"
  become: true
  become_user: postgres

- name: create users
  postgresql_user:
    db: "{{ item.db|default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state|default('present') }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    port: "{{ item.port|default(5432) }}"
  with_items: "{{ pgsql_users }}"
  become: true
  become_user: postgres
  no_log: true

- name: set up privileges
  postgresql_privs:
    role: "{{ item.role }}"
    database: "{{ item.db }}"
    privs: "{{ item.privs }}"
    type: "{{ item.type|default('database') }}"
    obj: "{{ item.obj|default(omit) }}"
    state: "{{ item.state|default('present') }}"
    grant_option: "{{ item.option|default(false) }}"
    port: "{{ item.port|default(5432) }}"
  with_items: "{{ pgsql_privileges }}"
  become: true
  become_user: postgres

- name: remove public privileges from dbs
  postgresql_privs:
    database: "{{ item.name }}"
    grant_option: false
    type: database
    role: PUBLIC
    privs: connect
    state: absent
    port: "{{ item.port|default(5432) }}"
  with_items: "{{ pgsql_dbs }}"
  become: true
  become_user: postgres
```

tasks/configure.yml
```
---
- name: place postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "/var/lib/pgsql/9.6/data/postgresql.conf"
    owner: "postgres"
    group: "postgres"
  notify: restart postgresql
  become: true

- name: place pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/var/lib/pgsql/9.6/data/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
  notify: reload postgresql
  become: true

- name: start and enable postgresql
  service:
    name: "postgresql-9.6"
    state: started
    enabled: true
  become: true

- name: flush handers to reload config, so we can continue
  meta: flush_handlers
```

defaults/main.yml

```
pgsql_dbs:
  - { name: db_test, owner: null, encoding: null, lccollate: cs_CZ.UTF-8, lctype: cs_CZ.UTF-8, template: template0, target: null, state: present }
pgsql_privileges:
  - { role: r_test, db: db_test, privs: ALL, type: database, obj: null, state: present, option: false }
  - { role: user_2, db: db_test, privs: ALL, type: database, obj: null, state: present, option: false }
pgsql_users:
  - { db: db_test, name: r_test, password: "1234", state: present, ip: 1.2.3.4/24 }
  - { db: db_test, name: user_2, password: "4321", state: present, ip: 1.2.3.4/24 }
```

Failed part of playbok:

```
TASK [postgresql : set up privileges] *******************************************************************************************
ok: [test] => (item={u'state': u'present', u'obj': None, u'option': False, u'type': u'database', u'privs': u'ALL', u'role': u'r_test', u'db': u'db_test'})
failed: [test] (item={u'state': u'absent', u'obj': None, u'option': False, u'type': u'database', u'privs': u'ALL', u'role': u'user_2', u'db': u'db_test'}) => {"changed": false, "item": {"db": "db_test", "obj": null, "option": false, "privs": "ALL", "role": "user_2", "state": "absent", "type": "database"}, "msg": "role \"user_2\" does not exist\n"}
	to retry, use: --limit @/home/m/Documents/Vagrant/vagrant_centos/playbook.retry

PLAY RECAP **********************************************************************************************************************
test                       : ok=11   changed=3    unreachable=0    failed=1   
```
