### ISSUE TITLE
error: "unable to set terminal parameters" on IOS devices

### ISSUE THREAD

**Issue by skregas** [ansible/ansible#46185]
##### SUMMARY

Consistently encountering **AnsibleConnectionFailure: unable to set terminal parameters**
when changing from 
**connection: local**
 to 
**connection: network_cli**
and defining
`ansible_network_os: ios`
for the host.

Also tried adding
`become: true
become_method: enable
`
to the play with no effect
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /var/lib/awx/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```

ANSIBLE_COW_SELECTION(/var/lib/awx/ansible.cfg) = random
HOST_KEY_CHECKING(/var/lib/awx/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/var/lib/awx/ansible.cfg) = 30

```

##### OS / ENVIRONMENT

Ansbile controller: Red Hat 4.8.5
Target OS: C800, C3900 

##### STEPS TO REPRODUCE

Using **connection: network_cli**
issue a single command using the ios_command module

In inventory, define:
`ansible_network_os: ios`

```
hosts: <inventory>
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show version
    ios_command:
      commands: show run | inc logging host
    register: cmd_output
```
Also tried:
```
hosts: <inventory>
  gather_facts: no
  connection: network_cli
  **become: true** 
  **become_method: enable**

  tasks:
    - name: Run show version
    ios_command:
      commands: show run | inc logging host
    register: cmd_output
```

##### EXPECTED RESULTS

The task and playbook complete successfully

##### ACTUAL RESULTS

```
-bash-4.2$ ansible all -i _hostname_, -c network_cli -u fc.acsansible.ro -k -m ios_command -e ansible_network_os=ios -vvvv
ansible 2.6.4
  config file = /var/lib/awx/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /var/lib/awx/ansible.cfg as config file
SSH password:
setting up inventory plugins
Parsed _hostname_, inventory source with host_list plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/minimal.pyc
META: ran handlers
<_hostname_> attempting to start connection
<_hostname_> using connection plugin network_cli
<_hostname_> local domain socket does not exist, starting it
<_hostname_> control socket path is /var/lib/awx/.ansible/pc/39555cd441
<_hostname_>
The full traceback is:
Traceback (most recent call last):
  File "/bin/ansible-connection", line 105, in start
    self.connection._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 328, in _connect
    self._terminal.on_open_shell()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/terminal/ios.py", line 58, in on_open_shell
    raise AnsibleConnectionFailure('unable to set terminal parameters')
AnsibleConnectionFailure: unable to set terminal parameters

_hostname_ | FAILED! => {
    "msg": "unable to set terminal parameters"
}

```
