### ISSUE TITLE
os_quota unable to set injected_file_content_bytes

### ISSUE THREAD

**Issue by carstenkoester** [ansible/ansible#46187]
##### SUMMARY
OpenStack quota named "injected_file_content_bytes" and "injected_file_path_bytes" cannot be set using os_quota module.

Note that the os_quota module has a "injected_file_size" and "injected_path_size" parameter which are (presumably) supposed to replace these two, but several (most?) OpenStack environments seem to use the "injected_file_content_bytes" and "injected-file-path-bytes" naming. As of this writing, this applies OpenStack Rocky release (and all prior releases):

https://docs.openstack.org/nova/rocky/admin/quotas.html

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_quota

##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = /workspace/ckoester/180926_024639/0001-02228/ansible.cfg
  configured module search path = [u'/home/ckoester/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/virtualenv/ansible26/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/virtualenv/ansible26/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
No relevant changes made
```

##### OS / ENVIRONMENT

Tested with OpenStack Liberty

##### STEPS TO REPRODUCE

```yaml
---
- hosts: test
  tasks:
    - name: Get quotas before changing
      os_quota:
        cloud: "{{ test }}"
        name: "test_project"
      register: before
    - debug:
        var: before.openstack_quotas.compute.injected_file_content_bytes

    - name: Set quotas
      os_quota:
        cloud: "{{ test }}"
        state: present
        name: "test_project"

        injected_file_size: 888

    - name: Get quotas after changing
      os_quota:
        cloud: "{{ test }}"
        name: "test_project"
      register: after
    - debug:
        var: after.openstack_quotas.compute.injected_file_content_bytes
```

##### EXPECTED RESULTS

One of two options:

Option 1: The "injected_file_size" parameter, under the hood, updates "injected_file_content_bytes"

Option 2: Support a parameter named "injected_file_content_bytes", instead of or in addition to "injected_file_size". (Not sure whether or where "injected_file_size" is actually used -- I've never seen it used, but that doesn't mean much).

##### ACTUAL RESULTS

```paste below
TASK [Get quotas before changing] ******************************************************************
Wednesday 26 September 2018  22:43:23 -0400 (0:00:00.094)       0:00:00.094 ***
ok: [test]

TASK [debug] ***************************************************************************************
Wednesday 26 September 2018  22:43:33 -0400 (0:00:10.232)       0:00:10.327 ***
ok: [test] => {
    "before.openstack_quotas.compute.injected_file_content_bytes": "777"
}

TASK [Set quotas] **********************************************************************************
Wednesday 26 September 2018  22:43:33 -0400 (0:00:00.152)       0:00:10.480 ***
ok: [test]

TASK [Get quotas after changing] *******************************************************************
Wednesday 26 September 2018  22:43:40 -0400 (0:00:07.042)       0:00:17.523 ***
ok: [test]

TASK [debug] ***************************************************************************************
Wednesday 26 September 2018  22:43:48 -0400 (0:00:07.306)       0:00:24.829 ***
ok: [test] => {
    "after.openstack_quotas.compute.injected_file_content_bytes": "777"
}

PLAY RECAP *****************************************************************************************
test : ok=5    changed=0    unreachable=0    failed=0
```

Note that a simple search-and-replace, `sed -i os_quota.py -e 's/injected_file_size/injected_file_content_bytes/'`, makes the command work successful with `injected_file_content_bytes` parameter. If nothing else, this seems to suggest that the issue is due to naming mismatch.
