### ISSUE TITLE
gcp_* auth error even with google-auth library installed

### ISSUE THREAD

**Issue by arendej** [ansible/ansible#46181]
##### SUMMARY

Using any gcp_* module results in "Please install the google-auth library" error, regardless of satisfying the requirements.
OS = CentOS 7.5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = /home/me/.ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/me/.ansible.cfg) = [u'/home/me/anshosts']
DEFAULT_REMOTE_USER(/home/me/.ansible.cfg) = scotty
PERSISTENT_CONNECT_TIMEOUT(/home/me/.ansible.cfg) = 30
```

##### OS / ENVIRONMENT

$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)

$ pip list | grep google
google-api-python-client     1.7.4    
google-auth                  1.5.1    
google-auth-httplib2         0.0.3 

$ pip list | grep requests
requests                     2.18.4  

##### STEPS TO REPRODUCE

Based on pip items above installed, create a playbook that should create an instance and run it. 

```yaml
--- #deploy 1 instance
- hosts: localhost
  connection: local
  tasks:
  - name: 1 instance to buid
    gcp_compute_instance:
      auth_kind: serviceaccount
      service_account_email: "redacted-compute@developer.gserviceaccount.com"
      service_account_file:  ../redacted.json
      scopes:
        - www.googleapis.com/auth/compute
      project: my-project
      name: test-instance-1
      machine_type: f1-micro
      state: present
      zone: "northamerica-northeast1-b"
      #region: "northamerica-northeast1"
      disks:
        - initialize_params:
            source_image: centos-7-v20180911
```

##### EXPECTED RESULTS

Expect an instance to be created, along with the successful auth to GCloud.

##### ACTUAL RESULTS

I get the error as below:

```paste below
$ ansible-playbook deploy1instance.yml -vvvv
ansible-playbook 2.6.4
  config file = /home/me/.ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /home/me/.ansible.cfg as config file
setting up inventory plugins
Set default localhost to localhost
 [WARNING]: A duplicate localhost-like entry was found (127.0.0.1). First found localhost was localhost

Parsed /home/me/anshosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: deploy1instance.yml *****************************************************************************************************************
1 plays in deploy1instance.yml

PLAY [localhost] ******************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************
task path: /home/me/Github/t-openshift/gcp/ansible-ocp-3.7/test/deploy1instance.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: me
<localhost> EXEC /bin/sh -c 'echo ~me && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416 `" && echo ansible-tmp-1537988315.1-79655413921416="` echo /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> PUT /home/me/.ansible/tmp/ansible-local-20127XwDy2g/tmpXf7Ywh TO /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416/ /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/me/.ansible/tmp/ansible-tmp-1537988315.1-79655413921416/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [1 instance to buid] *********************************************************************************************************************
task path: /home/me/Github/t-openshift/gcp/ansible-ocp-3.7/test/deploy1instance.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: me
<localhost> EXEC /bin/sh -c 'echo ~me && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584 `" && echo ansible-tmp-1537988316.2-16490319727584="` echo /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/google/gcp_compute_instance.py
<localhost> PUT /home/me/.ansible/tmp/ansible-local-20127XwDy2g/tmpcsF6Lt TO /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584/gcp_compute_instance.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584/ /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584/gcp_compute_instance.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584/gcp_compute_instance.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/me/.ansible/tmp/ansible-tmp-1537988316.2-16490319727584/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_kind": null, 
            "can_ip_forward": null, 
            "disks": [
                {
                    "auto_delete": null, 
                    "boot": null, 
                    "device_name": null, 
                    "disk_encryption_key": null, 
                    "index": null, 
                    "initialize_params": {
                        "disk_name": null, 
                        "disk_size_gb": null, 
                        "disk_type": null, 
                        "source_image": "centos-7-v20180911", 
                        "source_image_encryption_key": null
                    }, 
                    "interface": null, 
                    "mode": null, 
                    "source": null, 
                    "type": null
                }
            ], 
            "guest_accelerators": null, 
            "label_fingerprint": null, 
            "machine_type": "f1-micro", 
            "metadata": null, 
            "min_cpu_platform": null, 
            "name": "test-instance-1", 
            "network_interfaces": null, 
            "project": "my-project", 
            "scheduling": null, 
            "scopes": [
                "www.googleapis.com/auth/compute"
            ], 
            "service_account_email": "redacted-compute@developer.gserviceaccount.com", 
            "service_account_file": "../redacted.json", 
            "service_accounts": null, 
            "state": "present", 
            "tags": null, 
            "zone": "northamerica-northeast1-b"
        }
    }, 
    "msg": "Please install the google-auth library"
}
	to retry, use: --limit @redacted/deploy1instance.retry

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/google/gcp_compute_instance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gcp_compute_instance.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @erjohnso @rambleraptor
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by arendej** [comment]
For reference, the similarly adapted playbook **works** completely fine with the 'gce' module.

```
--- #deploy 1 instance
- hosts: localhost
  connection: local
  tasks:
  - name: 1 instance to buid
    gce:
      #auth_kind: serviceaccount
      service_account_email: "redacted-compute@developer.gserviceaccount.com"
      credentials_file:  ../redacted.json
      project_id: my-project
      instance_names: test-instance-1,test-instance-2
      machine_type: f1-micro
      state: present
      zone: "northamerica-northeast1-b"
      #region: "northamerica-northeast1"
      image: centos-7-v20180911
      disk_size: 10
```

**Comment by rambleraptor** [comment]
Hello! Thanks for filing this issue.

My first guess is that Ansible is running a different version of Python than your local shell is. From your Ansible output, it looks like `/usr/bin/python` is the python environment being used. As a quick sanity check, can you make sure that `pip` is installing to the same location that `/usr/bin/python` is getting packages from?

**Comment by arendej** [comment]
Python34-pip was installed and conflicting with python2-pip.  
I cleaned up  both pip installs and python2-pip is the primary... allowing auth to happen, but a different problem now.. 

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py", line 1469, in <module>
    main()
  File "/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py", line 893, in main
    fetch = create(module, collection(module), kind)
  File "/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py", line 905, in create
    return wait_for_operation(module, auth.post(link, resource_to_request(module)))
  File "/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py", line 934, in resource_to_request
    request = encode_request(request, module)
  File "/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py", line 1081, in encode_request
    request['metadata'] = metadata_encoder(request['metadata'])
  File "/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py", line 1109, in metadata_encoder
    for key in metadata:
TypeError: 'NoneType' object is not iterable

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py\", line 1469, in <module>\n    main()\n  File \"/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py\", line 893, in main\n    fetch = create(module, collection(module), kind)\n  File \"/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py\", line 905, in create\n    return wait_for_operation(module, auth.post(link, resource_to_request(module)))\n  File \"/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py\", line 934, in resource_to_request\n    request = encode_request(request, module)\n  File \"/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py\", line 1081, in encode_request\n    request['metadata'] = metadata_encoder(request['metadata'])\n  File \"/tmp/ansible__b92TO/ansible_module_gcp_compute_instance.py\", line 1109, in metadata_encoder\n    for key in metadata:\nTypeError: 'NoneType' object is not iterable\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```

**Comment by rambleraptor** [comment]
That's a bug that we identified. You'll have to set metadata: {} on your
playbook. We've got a fix coming out for this!

**Comment by arendej** [comment]
Thanks for that...    
Another question if you don't mind...

here's my disks section for a single instance:

```
      disks:
        - boot: yes
        - initialize_params:
            source_image: 'gs://projects/centos-cloud/global/images/centos-7-v20180911'
```
but the error when running is:

```
   "msg": "GCP returned error: {u'error': {u'code': 400, u'message': u\"Invalid value for field 'resource.disks[1].initializeParams.sourceImage': 'gs://projects/centos-cloud/global/images/centos-7-v20180911'. The URL is malformed.\", u'errors': [{u'domain': u'global', u'message': u\"Invalid value for field 'resource.disks[1].initializeParams.sourceImage': 'gs://projects/centos-cloud/global/images/centos-7-v20180911'. The URL is malformed.\", u'reason': u'invalid'}]}}"
```

I have tried without `gs://`, with only `centos-7-v20180911` and all have the same error.

**Comment by rambleraptor** [comment]
Try `projects/centos-cloud/global/images/centos-7-v20180911`

(We're working on getting these docs better. I'll make a note about what format this should be in)

**Comment by dch** [comment]
> That's a bug that we identified. You'll have to set metadata: {} on your playbook. We've got a fix coming out for this!

@rambleraptor thanks for this fix suggestion! Can you tell me *where* the `metadata` field is supposed to go to address this?

**Comment by rambleraptor** [comment]
Yeah, no problem.

On your `gcp_compute_instance` play, you'll have to set `metadata` to an empty dictionary:

```yaml
  gcp_compute_instance:
     ...
     metadata: {}
     ...
```
Did that answer your question?

(This bug has been fixed in newer versions of the module)
