### ISSUE TITLE
 [WARNING]: Falling back to Ansible unique filter as Jinaj2 one failed: unhashable type: 'list'

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#46189]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible or Jinja2 filter or set_fact

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.0.dev0 (devel ac9d506a61) last updated 2018/09/26 23:17:20 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

Ansible host: MacOS 10.12.6
Target OS: Windows 7

##### STEPS TO REPRODUCE

```yaml
vars:
  corp_chocolatey_packages:
    - bluescreenview
    - cleanup
    - firefox
    - git
    - googlechrome
    - veeam-agent
    - virtualclonedrive
    - winscp
  
  chocolatey_packages: []

- name: set chocolate packages 
  set_fact: 
    chocolatey_packages: "{{ chocolatey_packages|union(query('vars', item)) }}"
  loop: "{{ hostvars[inventory_hostname]|select('match','.*chocolatey_packages$')|flatten(levels=1) }}"
```

##### EXPECTED RESULTS

chocolatey_packages would be a list of chocolatey packages to be installed

##### ACTUAL RESULTS

```paste below
TASK [win_chocolatey : set chocolate packages] *********************************
 [WARNING]: Falling back to Ansible unique filter as Jinaj2 one failed:
unhashable type: 'list'
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/filter](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Maybe we should compare the error to `TypeError` and only warn/error when the `jinja2` specific args are supplied.

**Comment by bcoca** [comment]
@basictheprogram so the task still worked? it is just the warning that worries you?

**Comment by basictheprogram** [comment]
It didn't work until I ....|flatten(levels=1) now it just gives a warning but still works. 

Is there something I should change in the task to not get a warning?

Oops, sorry about the comment and close.

**Comment by bcoca** [comment]
@basictheprogram the PR linked above should avoid giving you the warning in this case.

Instead of `|flatten(1)`, you could use `|list`, some Jinja2 filters are 'generators' which don't really work for us and they have to be forced into a list, which is what your flatten is doing.

**Comment by basictheprogram** [comment]
Switch to |list
```yaml
- name: set chocolate packages 
  set_fact: 
    chocolatey_packages: "{{ chocolatey_packages|union(query('vars', item)) }}"
  loop: "{{ hostvars[inventory_hostname]|select('match','.*chocolatey_packages$')|list }}"
```
```
TASK [win_chocolatey : set chocolate packages] *********************************
 [WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
unhashable type: 'list'

 [WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
unhashable type: 'list'

 [WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
unhashable type: 'list'

 [WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
unhashable type: 'list'

 [WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
unhashable type: 'list'
```
Still works.
