### ISSUE TITLE
Ansible apt state=absent calls apt-get update

### ISSUE THREAD

**Issue by encryptedfear** [ansible/ansible#46195]
##### SUMMARY

Running a playbook with an apt-get remove does not proceed with the intended action.
User is running state=absent, but throws an error instead.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible apt module
##### ANSIBLE VERSION

```paste below
2.4.1.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Debian 3.16.43
##### STEPS TO REPRODUCE

User is to run a playbook that will remove the indicated packages.

```yaml
---
- name: Uninstall unnecessary packages in Debian/Ubuntu
  apt:
    name:"{{ item }}"
    state:absent
  become: true
  with_items:
    - nis
    - rsh-client
    - rsh-reload-client
    - talk
    - xserver-xorg-core*

```

##### EXPECTED RESULTS

User expected the packages to have been removed using the apt module.

##### ACTUAL RESULTS

```paste below
failed: [xxx.xxx.xxx.xxx] (item=nis) => {
    "changed": false,
    "cmd": "apt-get update",
    "failed": true,
    "item": "nis",
    "rc": 100
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/apt.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I am unable to duplicate this with Ansible 2.4.1 and Debian 8. I do not have a Debian 3 instance to test with.

Could you try with a newer version of Ansible and/or Debian?

I'm not sure if it affects this bug or not, but the example playbook is missing spaces between the key and the value.

```yaml
- name: Uninstall unnecessary packages in Debian/Ubuntu
  apt:
    name: "{{ item }}"    # <= added space
    state: absent         # <= added space
  become: true
  with_items:
    - nis
    - rsh-client
    - rsh-reload-client
    - talk
    - xserver-xorg-core*
```

```
> ansible --version
ansible 2.4.1.0 (detached HEAD e946c4b3b7) last updated 2018/09/27 17:36:14 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = ['/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 3.6.4 (default, Mar 19 2018, 12:20:18) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

```
> ansible-playbook test.yml -v
Using /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg as config file

PLAY [lab-deb8] *****************************************************************************

TASK [Uninstall unnecessary packages in Debian/Ubuntu] **************************************
changed: [lab-deb8] => (item=['nis', 'rsh-client', 'rsh-reload-client', 'talk', 'xserver-xorg-core*']) => {
    "changed": true,
    "failed": false,
    "item": [
        "nis",
        "rsh-client",
        "rsh-reload-client",
        "talk",
        "xserver-xorg-core*"
    ]
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libdbus-glib-1-2 libglib2.0-0 libglib2.0-data libslp1 shared-mime-info
  xdg-user-dirs
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  nis
0 upgraded, 0 newly installed, 1 to remove and 39 not upgraded.
After this operation, 596 kB disk space will be freed.
(Reading database ... 28807 files and directories currently installed.)
Removing nis (3.17-33) ...
Processing triggers for man-db (2.7.0.2-5) ...



PLAY RECAP **********************************************************************************
lab-deb8                   : ok=1    changed=1    unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds

> ansible-playbook test.yml -v
Using /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg as config file

PLAY [lab-deb8] *****************************************************************************

TASK [Uninstall unnecessary packages in Debian/Ubuntu] **************************************
ok: [lab-deb8] => (item=['nis', 'rsh-client', 'rsh-reload-client', 'talk', 'xserver-xorg-core*']) => {
    "changed": false,
    "failed": false,
    "item": [
        "nis",
        "rsh-client",
        "rsh-reload-client",
        "talk",
        "xserver-xorg-core*"
    ]
}

PLAY RECAP **********************************************************************************
lab-deb8                   : ok=1    changed=0    unreachable=0    failed=0
```

needs_info
