### ISSUE TITLE
k8s module changes openshift-buildconfig consequently when build triggers are defined

### ISSUE THREAD

**Issue by pritho** [ansible/ansible#46206]
##### SUMMARY
We use the k8s module in order to create buildconfigs including build triggers upon imagechanges.
Problem is that when buildtriggers for imagechanges are defined, openshift is automatically adding the sha-sum, which in turn triggers a new build on every ansible run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s
##### ANSIBLE VERSION

```
ansible 2.4.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gitlab-runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.13 (default, May 23 2018, 14:21:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```
##### OS / ENVIRONMENT

running in container on openshift
##### STEPS TO REPRODUCE

create a simple openshift buildconfig and apply with k8s module, for example:
```
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: asdf
  namespace: image-mgmt
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'asdf'
      namespace: openshift
  source:
    dockerfile: >-
      FROM jenkins-agent-maven-35-rhel7:v3.10
      USER 1001
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'jenkins-agent-maven-35-rhel7:v3.10'
    type: Docker
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: 'jenkins-agent-maven-35-rhel7:v3.10'
      type: ImageChange
```
Openshift will then modify the trigger to include the shasum:
```
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: 'jenkins-agent-maven-35-rhel7:v3.10'
        lastTriggeredImageID: >-
          docker-registry.default.svc:5000/image-mgmt/jenkins-agent-maven-35-rhel7@sha256:30837127deea37e0afe9257407a89b77ee2e784c29bdd5a98aa65baeb0c1d155
      type: ImageChange
```

this will result in a change on the next apply of the ansible playbook, triggering another unnnecessary build

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
How are you pulling the k8s module in (and from what version of Ansible), and what version of the openshift client do you have installed?

**Comment by pritho** [comment]
Hey,

I'm installing latest ansible (2.6.4) and openshift (0.7.1) from pip.

For starting the taks I've defined a task:
```
- name: Create/Change OpenShift Buildconfig for RHEL-Base
  k8s:
    state: present
    verify_ssl: "yes"
    resource_definition: "{{ lookup('template', 'buildconfig_rhel7.yml.j2') | from_yaml }}"
```
which points to the template referenced above

**Comment by hlin** [comment]
I met similar issue in DeploymentConfig with ImageChange trigger

```
- name: Create deployment config
  k8s:
    api_key: "{{ token }}"
    host: "{{ host }}"
    verify_ssl: true
    state: present
    definition:
      apiVersion: v1
      kind: DeploymentConfig
      ...
      spec:
        ...
        triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            from:
              kind: ImageStreamTag
              name: "{{ image_stream_name }}:{{ image_tag }}"
```

ansible will always return changed even though the image is not change.

```
changed: [stage] => {
    "changed": true,
    "diff": [
        [
            "add",
            [
                "spec",
                "triggers",
                1,
                "imageChangeParams"
            ],
            [
                [
                    "lastTriggeredImage",
                    "quay.io/redhat/product-listings-manager@sha256:587640dae404657aa99bb9cef37daea82bd4aaec5d762b7ff95763b2cf5c36e0"
                ]
            ]
        ],
        [
            "change",
            "metadata.generation",
            [
                21,
                20
            ]
        ],
        [
            "change",
            "metadata.resourceVersion",
            [
                "83333295",
                "83333264"
            ]
        ]
    ],
```

ENV

```
python 2.7
ansible==2.7.10
openshift==0.8.7
```
