### ISSUE TITLE
vmware_guest Linux Netplan configuration is missing DNS servers and search domains

### ISSUE THREAD

**Issue by elvinasp** [ansible/ansible#46202]
##### SUMMARY
VMWare guest configuration module does not insert DNS resolution information into Linux guest, which uses Netplan for network configuration (Ubuntu 18.04). 

wmware_guest documentation also states the following:
```yaml
networks:
- dns_servers (string): DNS servers for this network interface (Windows).
```
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_guest

##### ADDITIONAL INFORMATION
Expected result is to have DNS resolution information in the generated NetPlan configuration file. Without it host is not able to do any hostname resolution not defined in static /etc/hosts file. 

However I am not sure whether this is only Ansible issue or OpenVM Tools is also missing something as guest cusomization only started to work after open-vm-tools were upgraded to 10.3. Older version 10.2 was causing issues like defined in #40564. 

```yaml
network:
  ethernets:
    ens160:
      addresses:
      - X.X.X.X/Y
      dhcp4: false
      dhcp6: false
      gateway4: X.X.X.X
      nameservers:
        addresses:
        - Y.Y.Y.Y
        - Y.Y.Y.Y
        search:
        - some.domain
        - another.domain
  renderer: networkd
  version: 2
```

Actual result:

```yaml
network:
  ethernets:
    ens160:
      addresses:
      - X.X.X.X/Y
      dhcp4: false
      dhcp6: false
      gateway4: X.X.X.X
  renderer: networkd
  version: 2
```

Example playbook. 
```yaml
- name: Create VCenter VM docker-nodes from template file ubuntu-18.04-minimal

  hosts:
    - docker-nodes
  gather_facts: no

  tasks:
    - set_fact:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_user : "{{ vcenter_user }}"
        vcenter_pass : "{{ vcenter_pass }}"
        vcenter_cluster: "{{ vcenter_cluster }}"
        esxi_hostname: "{{ esxi_hostname }}"

- hosts: docker-nodes
  gather_facts: no
  connection: local

  tasks:

    - name: Deploy docker node VMs
      vmware_guest:
        notes: 'Ansible VM deployment'
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        esxi_hostname: "{{ esxi_hostname }}"
        folder: "{{ vmware_folder }}"
        template: "{{ template_name }}" 
        name: "{{ inventory_hostname }}"
        datacenter: "{{ datacenter }}"
        state: poweredon
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          scsi: paravirtual
        disk:
          - type: thin
            datastore: autoselect_datastore
            size_gb: "{{ disk }}"
        networks:
          - name: "{{ network }}"
            ip: "{{ ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            device_type: "vmxnet3"
            domain: " {{ my_domain }} "
            dns_servers:
              - "{{ dns_server1 }}"
              - "{{ dns_server2 }}"
        customization:
          password: "{{ os_password }}"
          hostname: "{{ inventory_hostname }}"
        wait_for_ip_address: yes
```

Software versions:
```
$ ansible --version
ansible 2.6.4
  config file = None
  configured module search path = [u'/home/nlepi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Oct 31 2017, 21:12:13) [GCC 6.4.0]

dpkg -l | grep open-vm
ii  open-vm-tools                         2:10.3.0-0ubuntu1~18.04.1         amd64        Open VMware Tools for virtual machines hosted on VMware (CLI)
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @elvinasp,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ssahani** [comment]
I am working on the networkd module https://github.com/ansible/ansible/pull/46118

**Comment by ansibot** [comment]
cc @ckotte
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lparkes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Tomorrow9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @goneri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pgbidkar
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ngp-star** [comment]
hi @elvinasp 
i have some doubts on this issue,
like when netplan network type is mentioned in the playbook dns resolution information inserted into /etc/hosts file or is it going to create new configuration file inside the guest.? can you please explain this.?
one more thing like while mentioning network configurations form playbook using vmware_guest module there is no section like ethernets. but in the issue you mentioned about using the same can you please elaborate on this, to how to use this one?

apart form 'vmware_guest' module there is one more module 'vmware_guest_network' is it going to help you in any way?

regards
naveen

**Comment by goneri** [comment]
Hi @elvinasp,

This sounds like an issue with your version of open-vm-tools and/or cloud-init (https://github.com/vmware/open-vm-tools). Are you using an up to date version?

See:
- https://kb.vmware.com/s/article/54986
- https://github.com/vmware/open-vm-tools/issues?utf8=%E2%9C%93&q=is%3Aissue+netplan

needs_info

**Comment by elvinasp** [comment]
Problem is that more than a year have passed since. AFAIK I have written myself a custom workaround shell script to fix network init. However original project have moved on and Ansible deployment was abandoned completely somewhere half a year ago.  

> like when netplan network type is mentioned in the playbook dns resolution information inserted into /etc/hosts file or is it going to create new configuration file inside the guest.? can you please explain this.?
If I remember correctly by looking at my message, Ansible playbook was supposed to generate Netplan configuration file on the guest machine (if Netplan was using). Resulting was was missing the following section:

```
      nameservers:
        addresses:
        - Y.Y.Y.Y
        - Y.Y.Y.Y
        search:
        - some.domain
        - another.domain
```

> one more thing like while mentioning network configurations form playbook using vmware_guest module there is no section like ethernets. but in the issue you mentioned about using the same can you please elaborate on this, to how to use this one?

These examples are not playbooks or Ansible inventory/data files. These are expected and resultinf Netplan config files from _/etc/netplan/_ folder and they are in YAML format. 

> apart form 'vmware_guest' module there is one more module 'vmware_guest_network' is it going to help you in any way?

Well at the moment I am no longer using VMWare and Ansible combination anywhere, so cannot comment on that. Also cannot comment on versions now as I would expect they have been upgraded since.
