### ISSUE TITLE
Add a version of the combine-filter that merges in reversed order

### ISSUE THREAD

**Issue by mattiasb** [ansible/ansible#46215]
##### SUMMARY

I'd like to be able to use the combine-filter but merge in reverse order.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

No idea

##### ADDITIONAL INFORMATION

One common pattern that I return to when constructing Ansible roles is to have some variables for the role described (with defaults) in `defaults/main.yml` and then apply some defaults or transformations to that data inside `vars/main.yml` (prefixing the variable with `_` to make it clear that the variable is internal and manipulated).

**Example:**
*defaults/main.yml*
```yaml
# A list of objects containing a name and optionally an 
# admin boolean and a list of databases it can write to
db_users: []
```
*vars/main.yml*:
```yaml
_db_user_defaults:
  admin: false
  databases: []

_db_users: >-
  {%- result=[] -%}
  {%- for user in db_users -%}
  {%-     result.append(_db_user_defaults | combine(user)) -%}
  {%- endfor -%}
  {{ result | to_json | from_json }}
```

This allows me to define my variables in my inventory like this:

*inventory/development/group_vars/database/vars.yml*
```yaml
db_users:
  - name: charles
    databases:
      - sales
      - marketing
  - name: nina
  - name: root
    admin: true
```
…while not having to put lots of `default`-filters in my task files.

Now to my problem. See the `_db_users` definition above. If I could reverse the merge-order of combine I could define it like this instead:

*vars/main.yml*:
```yaml
_db_user_defaults:
  admin: false
  databases: []

_db_users: >-
  {{ db_users | map('combine', _db_user_defaults, reverse_merge=True) | list }}
```
Which reads *a lot* nicer.

I use the above approach when I want to **override** something in a list of objects (which comes up more seldomly):

`vars/main.yml`:
```yaml
_db_user_overrides:
  admin: false

_db_users: >-
  {{ db_users | map('combine', _db_user_overrides) | list }}
```

##### Solution(?)

Either a `reverse_combine`-filter or a new key to the `combine`-filter would do. Maybe `reverse_merge` or `ltr` (as in left-to-right merge).

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/inventory](https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory)
* [lib/ansible/modules/files/file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py)
* [lib/ansible/modules/packaging/os/apt.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/playbook/role](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role)
* [test/integration/targets/apt/defaults/main.yml](https://github.com/ansible/ansible/blob/devel/test/integration/targets/apt/defaults/main.yml)
* [test/integration/targets/binary/vars/main.yml](https://github.com/ansible/ansible/blob/devel/test/integration/targets/binary/vars/main.yml)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
soo, why not just switch the variables?
```
_db_users: >-
  {{ _db_user_defaults | map('combine', _db_users) | list }}
```
is the same as your example w/o requiring a new keyword

**Comment by mattiasb** [comment]
> [...]
> ```
> _db_users: >-
>   {{ _db_user_defaults | map('combine', _db_users) | list }}
> ```
> 
> is the same as your example w/o requiring a new keyword

Is it though? `_db_user_defaults` is a dict and not a list. Not sure what applying the `combine` filter on a dict would do.

**Comment by mattiasb** [comment]
@bcoca Here's a test of your suggestion:

**combine.yml:**
```yaml
---
- hosts: all
  vars:
    databases:
      - name: db1
        permissions:
          all:
            - olle
          read:
            - kalle
          write:
            - pelle
      - name: db2
        permissions:
          all:
            - olle
      - name: db3
        permissions: []
      - name: db3
    database_defaults:
      permissions:
        all: []
        read: []
        write: []
    _databases: >-
      {{ database_defaults
       | map('combine', databases)
       | list
      }}
  tasks:
    - debug:
        var: _databases
```

```shell
$ ansible-playbook -i 'localhost,' -c 'local' ./combine.yml

PLAY [all] *********************************************************************************************

TASK [Gathering Facts] *********************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ database_de
faults\n | map('combine', databases)\n | list\n}}'. Error was a <class 'ansible.errors.AnsibleFilterErro
r'>, original message: |combine expects dictionaries, got u'permissions'"}                             
        to retry, use: --limit @/home/mattiasb/Code/Test/ansible-vars/combine.retry

PLAY RECAP *********************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by mattiasb** [comment]
If there was a `replicate`-filter that took input and produced a stream of `n` copies of it I could do something like this:
```yaml
    _databases: >-
      {{ database_defaults 
       | replicate(databases | length)
       | map('combine', databases)
       | list
      }}
```

The replicate filter would work like this: `{{ ( 5 | replicate(5) ) == [5, 5, 5, 5, 5] }}`

So that's another solution to my problem. 

/Mattias — who's aware that he's very focused on his particular problem right now ;)

*EDIT: Just realized this wouldn't work either, since `databases` would be a list. What I really want is just a reverse argument order version of combine, like I asked for in the beginning. :)*

**Comment by mattiasb** [comment]
I'll try to implement this as a filter-plugin in my local repository and see if I can get it all to work. Would you be interested in a PR then later?

**Comment by mattiasb** [comment]
Added [a PR](https://github.com/ansible/ansible/pull/46255) for this.

**Comment by bcoca** [comment]
combine takes N dictionaries, all terms need to be dicts, it should not work if any is a list no matter the order.

The issue here is your use of map more than the issue with the combine filter itself

**Comment by mattiasb** [comment]
> combine takes N dictionaries, all terms need to be dicts, it should not work if any is a list no matter 
> the order.

[Well](https://github.com/ansible/ansible/pull/32686/commits/2f78e53a253fe4a0812d9315e9ce3bf1fd328486?utf8=%E2%9C%93&diff=unified)...

Also the code was based on *your* suggestion.

> The issue here is your use of map more than the issue with the combine filter itself

No it's not. One might add support for my use case by extending `map` instead of `combine`, but there really isn't an issue with *my use of map*. I'm not trying to split hairs here. Rather I'm trying to communicate an issue with the way you communicate. It really is unnecessarily provocative. Please try to drop the attitude.

**Comment by bcoca** [comment]
sorry, i might have phrased that better, its not that you are using map incorrectly, its that you are using map at all that is the issue here. This is a limitation of map, not combine.

**Comment by mattiasb** [comment]
Thanks! All good 😊 ❤️

I agree with your premise and I'll continue the discussion in the PR. I have some other ideas that might be helpful as well!

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hoesler** [comment]
I found a hacky solution for this use case:
First, combine each dict with the defaults (override with defaults). Then, zip these n "defaults" with each dict and finally map these tuples of dicts using combine.

Example:

```yaml
users:
  user_a:
    password: "foo"
  user_b:
    password: "bar"

user_defaults:
  password: "default"
```

This is how you create a new users dict, with defaults applied:
```python
dict(users.keys() | zip(users.values() | map('combine', user_defaults) | zip(users.values()) | map('list') | map('combine')))
```
