### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OpenStackCloudURINotFound'

### ISSUE THREAD

**Issue by kinvaris** [ansible/ansible#46261]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_quota

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/id850342/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /app/ansible/lib/python2.7/site-packages/ansible
  executable location = /app/ansible/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'redacted']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = redacted
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = This file is managed by Ansible, all changes will be lost.
DEFAULT_MODULE_LANG(/etc/ansible/ansible.cfg) = C
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 25
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_SUDO_EXE(/etc/ansible/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_SYSLOG_FACILITY(/etc/ansible/ansible.cfg) = LOG_LOCAL0
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Linux redacted 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

##### STEPS TO REPRODUCE
```
    - name: set quota
      os_quota:
        cloud: "{{ cluster_name }}"
        name: "{{ item }}"
        cores: "{{ quota_settings.cores }}"
        ram: "{{ quota_settings.ram }}"
        port: "{{ quota_settings.ports }}"
        network: "{{ quota_settings.networks }}"
        router: "{{ quota_settings.routers }}"
        instances: "{{ quota_settings.instances }}"
        rbac_policy: "{{ quota_settings.rbacpolicies }}"
      with_items:
        - "{{ projects }}"
```

##### EXPECTED RESULTS
To work

##### ACTUAL RESULTS
```
failed: [localhost] (item=redacted) => {
    "changed": false,
    "item": "redacted",
    "module_stderr": "No handlers could be found for logger \"keystoneauth.identity.generic.base\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_kDIJ6U/ansible_module_os_quota.py\", line 449, in <module>\n    main()\n  File \"/tmp/ansible_kDIJ6U/ansible_module_os_quota.py\", line 384, in main\n    sdk, module, cloud, cloud_params['name'])\n  File \"/tmp/ansible_kDIJ6U/ansible_module_os_quota.py\", line 252, in _get_quotas\n    except sdk.exceptions.OpenStackCloudURINotFound:\nAttributeError: 'module' object has no attribute 'OpenStackCloudURINotFound'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

That exception does not exists!
