### ISSUE TITLE
Archive module can managle filenames deleting first letter

### ISSUE THREAD

**Issue by mikedlr** [ansible/ansible#46277]
##### SUMMARY
The archive module, when run on a single file (say `demo.py`) puts it in an archive with a mangled filename (say `emo.py`).  This can be upsetting.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
archive module

##### ANSIBLE VERSION

```
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/michael-mbp/projects/ansible/ansible/library']
  ansible python module location = /Users/michael-mbp/projects/ansible/ansible/lib/ansible
  executable location = /Users/michael-mbp/projects/ansible/ansible/bin/ansible
  python version = 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

tested on MacOS 10.13 and reproduced on Fedora 28 by @maxamillion 

##### STEPS TO REPRODUCE

1. create an empty directory
2. copy yaml below to playbook
3. create fred.py in directory
4. run playbook
5. unzip -l ~/ansible_test/fred.zip

``` 
      - hosts: localhost
  vars:
    ansible_connection: local
    demo_file_name: fred.py
    output_dir: ~/ansible_testing

  tasks:

        - name: ensure that output dir exists
          file:
            path: "{{output_dir}}"
            state: directory
            mode: 0775

        - name: move demo file to output dir ready to zip
          copy:
            src: "{{demo_file_name}}"
            dest: "{{output_dir}}/{{demo_file_name}}"

        - name: put demo file into zip BROKEN
          archive:
            format: zip
            path: "{{demo_file_name}}"
            dest: "{{output_dir}}/{{demo_file_name}}.zip"
          register: set_zip_res
```

##### EXPECTED RESULTS

fred.py should be packed into a zip file as `fred.py`

##### ACTUAL RESULTS

fred is packed as `red.py`

_edited - remove some misleading comments and improve task naming for clarity_
