### ISSUE TITLE
Not able to set docker_container --stop-timeout

### ISSUE THREAD

**Issue by kpsajith** [ansible/ansible#46296]
##### SUMMARY

Not able to set docker_container stop_timeout option using ansible.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```paste below
ansible 2.6.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux

##### STEPS TO REPRODUCE

```yaml
- name: Deploy Axone Router Container
  docker_container:
        image: "{{docker_registry_path}}router:{{ router_version }}"
        name: "router{{ item }}"
        network_mode: host
        pid_mode: host
        pull: "{{ default_docker_pull }}"
        restart_policy: unless-stopped
        state: started
        tty: yes
        stop_timeout: 30
```

##### EXPECTED RESULTS

I can set the stop timeout by doing docker run --stop-timeout 30 ......
docker inspect containerUnderTest | grep -i stoptimeout
            "StopTimeout": 30

##### ACTUAL RESULTS

No result, when this is set using ansible.

```paste below

```
