### ISSUE TITLE
Add arrays support for xfconf module

### ISSUE THREAD

**Issue by nicovell3** [ansible/ansible#46308]
##### SUMMARY
Add arrays support for the xfconf module.

##### ISSUE TYPE
- xfconf-query command can set up arrays. I needed that feature to automatize my xfce4 panels creation, so I implemented it. I would like someone to add to this repo the modifications I made to the xfconf.py file.

##### COMPONENT NAME
xfconf

##### ADDITIONAL INFORMATION
With this modification, array values can be queried and set. Also, if someone wants to create a value and force it to be an array, it just requires to add the "force_array: yes" to the playbook.

Here comes an usage example:

```yaml
  - name: Configure xfconf arrays
    become_user: '{{ user }}'
    environment:
      DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ uid }}/bus"
    xfconf:
      channel: "{{ item.channel }}"
      property: "{{ item.property }}"
      value_type: "{{ item.type }}"
      value: "{{ item.value }}"
      force_array: yes
      state: present
    with_items:
      - { channel: 'xfce4-panel', property: '/panels', type: 'int', value: '1' }
      - { channel: 'xfce4-panel', property: '/panels/panel-1/plugin-ids', type: 'int,int,int,int,int,int', value: '1,2,3,4,5,6' }
```

The modified xfconf.py can be found here: https://gist.github.com/nicovell3/a32f3a144d037ed018ebccd8a94e979d

I've tested some playbooks (get information and so on) and everything is working as it should.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/xfconf.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/xfconf.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/playbook/loop_control.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/loop_control.py)
* [test/integration/targets/environment/aliases](https://github.com/ansible/ansible/blob/devel/test/integration/targets/environment/aliases)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jbenden
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jbenden** [comment]
Please submit a Pull Request with your change. Thanks!

**Comment by nicovell3** [comment]
@jbenden I'm not familiar with the Pull Request mechanism, so I prefer not to do it myself for this little modification.

**Comment by jbenden** [comment]
I've created a PR for you. Thanks for your contributions!

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/xfconf.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/xfconf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ParticleDecay** [comment]
I believe this breaks standard behavior, such as when strings naturally contain commas:
```yaml
- name: Set titlebar button layout
  xfconf:
    channel: xsettings
    property: /Gtk/DecorationLayout
    value_type: "string"
    value: "close,maximize,minimize,menu:"
```

However, since `value=dict(required=False, type='list')`, this will be interpreted as a list instead of as a string.
