### ISSUE TITLE
docker_container publishing ports fails when container is in network

### ISSUE THREAD

**Issue by BenjaminHae** [ansible/ansible#46316]
##### SUMMARY
When using the `docker_container` module's `network` parameter `publish_ports` fails as automatic determination of ip-addresses fails

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`docker_container`

##### ANSIBLE VERSION
```paste below
ansible 2.4.6.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 13:24:18) [GCC 6.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Host: `4.9.65-1-virthardened #2-Alpine SMP Mon Nov 27 15:53:30 GMT 2017 x86_64 Linux`
Remote machine: `4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Remote machine docker: `Docker version 18.06.1-ce, build e68fc7a`
##### STEPS TO REPRODUCE
Example playbook:

```yaml
---
- hosts: all
  gather_facts: yes
  vars:
    docker_network: test-network
  tasks:
      - name: create docker network {{ docker_network }}
        docker_network:
            name: "{{ docker_network }}"
      - name: create and start an alpine container, expose port 6600
        docker_container:
            name: test
            image: alpine
            ports: "6600:6600"
            networks:
              - name: "{{ docker_network }}"
```
##### EXPECTED RESULTS

I expected the container named test to be setup with the specified ports exposed.

##### ACTUAL RESULTS

Error when executing the last task. Obviously determining the default ip for exposing the ports fails.

```paste below
TASK [create and start an alpine container, expose port 6600] **********************************************************************************
fatal: [kodi]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.72.200.229 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_U_50S7/ansible_module_docker_container.py\", line 2136, in <module>\r\n    main()\r\n  File \"/tmp/ansible_U_50S7/ansible_module_docker_container.py\", line 2131, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_U_50S7/ansible_module_docker_container.py\", line 1760, in __init__\r\n    self.parameters = TaskParameters(client)\r\n  File \"/tmp/ansible_U_50S7/ansible_module_docker_container.py\", line 794, in __init__\r\n    self.published_ports = self._parse_publish_ports()\r\n  File \"/tmp/ansible_U_50S7/ansible_module_docker_container.py\", line 1023, in _parse_publish_ports\r\n    default_ip = self.default_host_ip\r\n  File \"/tmp/ansible_U_50S7/ansible_module_docker_container.py\", line 1006, in default_host_ip\r\n    network = self.client.inspect_network(net['name'])\r\n  File \"/home/benjaminh/.local/lib/python2.7/site-packages/docker/utils/decorators.py\", line 35, in wrapper\r\n    return f(self, *args, **kwargs)\r\n  File \"/home/benjaminh/.local/lib/python2.7/site-packages/docker/api/network.py\", line 72, in inspect_network\r\n    url = self._url(\"/networks/{0}\", net_id)\r\n  File \"/home/benjaminh/.local/lib/python2.7/site-packages/docker/client.py\", line 154, in _url\r\n    'instead'.format(arg, type(arg))\r\nValueError: Expected a string but found {'Ingress': False, 'Name': 'test-network', 'Created': '2018-09-30T09:17:16.857570837+02:00', 'IPAM': {'Driver': 'default', 'Config': [{'Subnet': '172.19.0.0/16', 'Gateway': '172.19.0.1'}], 'Options': None}, 'Labels': {}, 'EnableIPv6': False, 'Id': '6fbb7c40afdf0928979fdff7a783018fc273322c7d955f0dc97ca4212635be8d', 'ConfigOnly': False, 'Internal': False, 'ConfigFrom': {'Network': ''}, 'Options': {}, 'Driver': 'bridge', 'Scope': 'local', 'Attachable': False, 'Containers': {}} (<type 'dict'>) instead\r\n", "msg": "MODULE FAILURE", "rc": 0}
```
