### ISSUE TITLE
Inventory variables are not visible when targeting hosts in playbook

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#46339]
##### SUMMARY
Inventory variables are not visible when targeting hosts in playbook.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Variable substitution

##### ANSIBLE VERSION
```
2.6.5
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
In the inventory file I have:
```yaml
[all:vars]
project_name = sbx
environment_name = test
```
Inside playbook I would like to use those variables as such
```yaml
- name: init sbx iis server
  hosts: "{{ project_name }}_{{ environment_name }}_iis"
  gather_facts: true
  tasks:
  - include_role:
       name: sbx_iis
```

I am invoking the playbook as such:
`ansible-playbook /mnt/d/07_ansible/role_init/sbx_iis.yml -i /mnt/d/Repos/ansible_inventories/sbx_test_inventory -vvvv`

##### EXPECTED RESULTS
Role is executed against "sbx_test_iis" group

##### ACTUAL RESULTS

```paste below
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'project_name' is undefined

The error appears to have been in '/mnt/d/Repos/role_init/sbx_iis.yml': line 11, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: init sbx iis server
  ^ here
```

**Comment by ansibot** [comment]
@GitHubAre Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by GitHubAre** [comment]
Workaround for this:
`hosts: "{{ hostvars['localhost']['project_name'] }}_{{ hostvars['localhost']['environment_name'] }}_iis"`

**Comment by ghost** [comment]
There is some dark magic involved, it works if I use this:

```
---
- name: do nothing
  hosts: localhost
  gather_facts: false
  become: false


- name: init sbx iis server
  hosts: "{{ hostvars['localhost']['project_name'] }}_{{ hostvars['localhost']['environment_name'] }}_iis"
  gather_facts: true
  tasks:
  - include_role:
       name: sbx_iis
```

If I remove  the step "do nothing" it doesnt work even with this `hosts: "{{ hostvars['localhost']['project_name'] }}_{{ hostvars['localhost']['environment_name'] }}_iis"` syntax
