### ISSUE TITLE
redfish_config: SetBiosAttributes not idempotent

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#46338]
I haven't found another issue about this. Please forgive me if I open this and it turns out I was just too stupid to search.

##### SUMMARY
I have had a look at the new redfish modules. I know 2.7 isn't released yet and anyway these modules are flagged as preview, but I was somewhat irritated by the behavior of SetBiosAttributes in redfish_config. I've written a task to set the BIOS attribute EnergyPerformanceBias to MaxPower. Although the attribute already has this value, the action is executed and the task therefore says "changed". The other modules I have worked with so far are idempotent, they would discover that the value is already correct and report a status of (already) "OK". Would it be possible to make redfish_config idempotent?

##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
!component = lib/ansible/modules/remote_management/redfish/redfish_config.py

##### ANSIBLE VERSION
```
ansible 2.7.0rc4
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.13 (default, Oct 26 2017, 01:54:36) [GCC 6.3.0]
```

##### CONFIGURATION
```
```
##### OS / ENVIRONMENT
PowerEdge R740xd, iDRAC Firmware Version 3.15.17.15

##### STEPS TO REPRODUCE
```
- hosts: localhost
  connection: local
  tasks:
    - name: Set EnergyPerformanceBias to MaxPower
      redfish_config:
        category: Systems
        command: SetBiosAttributes
        bios_attr_name: EnergyPerformanceBias
        bios_attr_value: MaxPower
        baseuri: {{ baseuri }}
        user: "{{ user }}"
        password: "{{ password }}"
```

##### EXPECTED RESULTS
I expect that EnergyPerformanceBias isn't set to MaxPower if this is already its value:
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Set EnergyPerformanceBias to MaxPower] ***********************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Set EnergyPerformanceBias to MaxPower] ***********************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

##### ADDITIONAL INFORMATION
We are just starting using ansible for configurtion management. Therefore we still have a close look at the PLAY RECAP after running a playbook. Every task that changed something wants to be investigated, i.e. did we make a mistake in the playbook or was the system really configured wrong and ansible just did its job. When tasks announce changes that effectively didn't change anything, there is a lot of work to figure out what's going on. And anyway: It's such a good feeling when ansible reports everything as OK.
