### ISSUE TITLE
Can not contruct variable names progarmtically using Jinja2 and nested variables

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#46354]
##### SUMMARY

I am trying to contruct variable names progarmtically using Jinja2 and nested variables and with_sequence, but I am getting an error: The task includes an option with an undefined variable. The error was: 'item' is undefined
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cloud_init
##### ANSIBLE VERSION

```
2.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 7.5
##### STEPS TO REPRODUCE

I have a yaml file where I define different variables as follow (vmtemplate.yml):
```
#vmtest
vmtest_size: 105
vmtest_REF: Test
vmtest_memorysize: 40
vmtest_gmem: 40
vmtest_cpusockets: 8
vmtest_numnic: 3
vmtest_numeth: 2
vmtest_0_name: eth0
vmtest_0_nic: nic0
vmtest_0_state: plugged
vmtest_0_profile: oam
vmtest_0_ip: 10.10.10.2
vmtest_0_mask: 255.255.255.0
vmtest_0_gw: 10.10.10.1
vmtest_1_name: eth1
vmtest_1_nic: nic1
vmtest_1_state: plugged
vmtest_1_profile: prod
vmtest_1_ip: 10.10.20.2
vmtest_1_mask: 255.255.255.0
vmtest_1_gw:
vmtest_2_name: eth2
vmtest_2_nic: nic2
vmtest_2_state: plugged
vmtest_2_profile: prod01
vmtest_2_ip: 10.10.30.2
vmtest_2_mask: 255.255.255.0
vmtest_2_gw:
```
And I have the following playbook, where when executing the playbook I send via the extra variable the value of variable vmname which in this case is vmtest. Then I want to iterate from 0 to vmtest_numeth during this iteration I am trying to construct the following variables'names, and then the values of these variables are extracted from the variable file at the top (vmtemplate.yml): vmtest_x_ip, vmtest_x_mask, vmtest_x_gw, vmtest_x_name

where x ranges from 0 to vmtest_numeth :

```
---
- name: Playbook to deploy template with cloud_init
  hosts: localhost
  connection: local
  vars_files:
    - vars/vmtemplate.yml
  tasks:
    - name: Deploy VM from template
      ovirt_vms:
        name: "{{ vmname }}"
        template: rhel7.5-cloud_init
        cluster: Test
        storage_domain: Test
        clone: yes
        disk_format: raw
        state: running
        comment: "Created by Ansible"
        type: server
        cloud_init:
          host_name: "{{ vmname }}"
          user_name: root
          root_password: test12345
          dns_servers: 10.10.10.5
        cloud_init_nics:
        - nic_name:  "{{ vars[vmname + '_' + item  + '_name'] }}"
          nic_boot_protocol: static
          nic_ip_address: "{{ vars[vmname + '_' + item  + '_ip'] }}"
          nic_gateway: "{{ vars[vmname + '_' + item  + '_gw'] }}"
          nic_netmask:  "{{ vars[vmname + '_' + item  + '_mask'] }}"
          nic_on_boot: true
        with_sequence: start= 0 end= "{{ vars[vmname  + '_numeth'] }}"
```

##### EXPECTED RESULTS

It will create 3 ethernets with configs in the template file using the the following variables:
vmtest_0_ip, vmtest_0_mask, vmtest_0_gw, vmtest_0_name
vmtest_1_ip, vmtest_1_mask, vmtest_1_gw, vmtest_1_name
vmtest_2_ip, vmtest_2_mask, vmtest_2_gw, vmtest_2_name
##### ACTUAL RESULTS

 I am getting the following error: The task includes an option with an undefined variable. The error was: 'item' is undefined

```paste below

```
