### ISSUE TITLE
Add Support for Supplying Credentials to win_robocopy

### ISSUE THREAD

**Issue by mhunsber** [ansible/ansible#46355]
##### SUMMARY

Add `user_name` and `password` parameters to the `win_robocopy` module so that directories hosted on a password protected network share can be synchronized

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_robocopy
##### ADDITIONAL INFORMATION

robocopy can synchronize from a UNC path, but it doesn't provide network authentication by itself. This means you can't synchronize from a network share using `win_robocopy` if it has any authentication protecting it.
This could be solved by adding a PSDrive or a `net use` entry were added before running robocopy, like in [`win_package`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_package.ps1#L177).

##### EXAMPLE

```yaml
- name: Synchronize with MyFolder
  win_robocopy:
    src: '\\server1\MyProtectedShare\MyRemoteFolder'
    dest: 'C:\MyLocalFolder'
    user_name: DOMAIN\User
    user_password: Password
```
