### ISSUE TITLE
No-clobber parameter for ini_file module

### ISSUE THREAD

**Issue by ahayes** [ansible/ansible#46374]
##### SUMMARY

The ability to instruct the ini_file module to not overwrite an option if it is already set.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

lib/ansible/modules/files/ini_file.py

##### ADDITIONAL INFORMATION

Couple of of parameter options could be:

state: no-clobber
no-clobber: yes
overwrite: no

Sometimes a configuration file will need an option added during install but that option may be reconfigured in normal operation of the system. Indicating that an ini file option should not be overwritten would enable the task to remain in playbooks to ensure there is always a default for the option without changing it if it already exists.

An example would be an Apache CouchDB ini file where an administrator account is created by adding a line to an ini file with the format "username = plaintext-password". Soon after this line is observed by the couchdb process, the line is edited to replace the plaintext-password with an encrypted version.

```yaml
  - name: Set CouchDB admin user password to {{ host.couchdb.admin_password }}
    ini_file:
      path: /opt/couchdb/etc/local.d/myconf.ini
      section: admins
      option: admin
      value: "{{ host.couchdb.admin_password }}"
      owner: couchdb
      group: couchdb
      state: present
      overwrite: no
    notify:
      - restart couchdb
```
