### ISSUE TITLE
Onyx show facts module does not work for onyx version 3.6.6000 and higher

### ISSUE THREAD

**Issue by anasbadaha** [ansible/ansible#46410]
##### SUMMARY
failed to run onyx_show_facts module because of changed in json formmat.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/lib/ansible/modules/network/onyx/onyx_facts.py

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] 
```
##### STEPS TO REPRODUCE

```
- hosts: switch132
  gather_facts: no
  connection: network_cli
  become: yes
  vars: 
    ansible_network_os: onyx
  tasks:
    - onyx_facts:
         gather_subset:
         - all
     - onyx_facts:
         gather_subset:
           - "!modules"
     - onyx_facts:
         gather_subset:
           - interfaces
           - modules
```

##### EXPECTED RESULTS
attached yml file should be passed successfully when run it!

##### ACTUAL RESULTS
got unexpected exception
