### ISSUE TITLE
Using Jinja2 maths with default filter

### ISSUE THREAD

**Issue by uberjew666** [ansible/ansible#46434]
##### SUMMARY
I have set a variable that will be modified with math but may not always be defined so I've included the default filter. However, it appears Ansible tries to resolve the math first instead of checking if the variable is defined first, resulting in an error. It means I cannot use math with a default filter.
Tested on both devel and 2.6.5.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = /home/shulme/.ansible.cfg
  configured module search path = [u'/home/shulme/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/shulme/.ansible.cfg) = [u'/mnt/e/Code/source/scripts.ansible/environments/dev']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/shulme/vault/dev.txt
RETRY_FILES_ENABLED(/home/shulme/.ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/shulme/.ansible.cfg) = /home/shulme/"~/"
```

##### OS / ENVIRONMENT
Target OS: Ubuntu 16.04.5

##### STEPS TO REPRODUCE
Create a tasks using the template module.
Create a jinja2 template file with an undefined variable, modified with some form of math. Include the default filter with any output.

Task:
```
- name: Copy Zookeeper config
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_install_dir }}/conf/zoo.cfg"
    mode: 0664
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
  notify:
    - Restart Zookeeper
```

Template
```
{{ kafka_port + 1000 | default(3888) }}
```

##### EXPECTED RESULTS
It should check if the variable is defined first and on failure, use the default. Instead it tries to add 1000 to an undefined variable and errors.

##### ACTUAL RESULTS
It will just error on this step claiming variable is undefined.
```
{"changed": false, "msg": "AnsibleUndefinedVariable: 'kafka_port' is undefined"}
```
