### ISSUE TITLE
mongodb_user (pymongo 3.7.1, mongodb server 2.6.12) doesn't set default role

### ISSUE THREAD

**Issue by jikquantopian** [ansible/ansible#46443]
##### SUMMARY
The documentation for mongodb\_user claims that the default value for `roles` is `readWrite`, but when I ask it to create a user without specifying a role, the created user doesn't get any roles at all.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`mongodb_user`

##### ANSIBLE VERSION
```
ansible 2.6.4
  config file = /home/jik/src/family-orchestration/ansible.cfg
  configured module search path = [u'/home/jik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/jik/src/family-orchestration/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/jik/src/family-orchestration/ansible.cfg) = [u'/home/jik/src/family-orchestration/inventory']
DEFAULT_REMOTE_USER(/home/jik/src/family-orchestration/ansible.cfg) = root
```

##### OS / ENVIRONMENT
Source host is Ubuntu 18.04.1. Target host is CenOS 7.

##### STEPS TO REPRODUCE
See below.

```yaml
  - mongodb_user:
      database: coalmine
      login_database: admin
      login_password: '{{jik4_mongodb_admin_password}}'
      login_user: admin
      name: coalmine
      password: '{{coal_mine_mongodb_password}}'
      update_password: on_create
```

##### EXPECTED RESULTS
The creaed user should have the `readWrite` role in the `coalmine` database.

##### ACTUAL RESULTS
The created user has no roles, as evidenced by `db.getUser("coalmine")` in the mongo shell.

When I specify `roles: readWrite` explicitly, the expected behavior occurs.
