### ISSUE TITLE
With any_errors_fatal=True, playbook continues after handler failure

### ISSUE THREAD

**Issue by carstenkoester** [ansible/ansible#46447]
##### SUMMARY
When `any_errors_fatal` is set to True, a failure during handler execution does not cause the playbook to abort. Playbook continues to execute as if `any_errors_fatal` were set to False.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
any_errors_fatal

##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = /home/ckoester/.ansible.cfg
  configured module search path = [u'/home/ckoester/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/virtualenv/ansible26/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/virtualenv/ansible26/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/home/ckoester/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
No specific OS requirements

##### STEPS TO REPRODUCE

```
$ cat inventory.txt
host1 ansible_host=127.0.0.1 want=true
host2 ansible_host=127.0.0.1 want=false
```

```yaml
- hosts: all
  any_errors_fatal: True
  tasks:
    - name: Test task 1 - all succeed
      command: /bin/true
      notify: Test handler 1

    # Would expect playbook execution to stop here, since
    # the handler will fail...
    - meta: flush_handlers

    # However, we can observe that playbook execution
    # continues.
    - name: Test task 2 - should not get here
      command: /bin/true

  handlers:
    # This will fail for host 2
    - name: Test handler 1
      command: /bin/{{ want }}
```

##### EXPECTED RESULTS

Expecting playbook execution to stop after the `meta: flush_handlers` task and failed
handler execution

##### ACTUAL RESULTS

Playbook continued to run, executing task 2 on a single host only.

```paste below
$ ansible-playbook -i inventory.txt test.yml

PLAY [all] *****************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************
ok: [host1]
ok: [host2]

TASK [Test task 1 - all succeed] *******************************************************************************************************************************************************************************************
changed: [host2]
changed: [host1]

RUNNING HANDLER [Test handler 1] *******************************************************************************************************************************************************************************************
changed: [host1]
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001942", "end": "2018-10-03 14:39:46.107146", "msg": "non-zero return code", "rc": 1, "start": "2018-10-03 14:39:46.105204", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [Test task 2 - should not get here] ***********************************************************************************************************************************************************************************
changed: [host1]
	to retry, use: --limit @/home/ckoester/test/test.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************
host1                      : ok=4    changed=3    unreachable=0    failed=0
host2                      : ok=2    changed=1    unreachable=0    failed=1
```

For comparison, if the same code fails in a task (not in a handler),

``` yaml
- hosts: all
  any_errors_fatal: True
  tasks:
    - name: Test task 1 - all succeed
      command: /bin/true

    # This will fail for host 2
    - name: Test failure
      command: /bin/{{ want }}

    # Does NOT get here
    - name: Test task 2 - should not get here
      command: /bin/true
```

then execution aborts as expected:

```
$ ansible-playbook -i inventory.txt test2.yml

PLAY [all] *****************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************
ok: [host2]
ok: [host1]

TASK [Test task 1 - all succeed] *******************************************************************************************************************************************************************************************
changed: [host1]
changed: [host2]

TASK [Test failure] ********************************************************************************************************************************************************************************************************
changed: [host1]
fatal: [host2]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.002005", "end": "2018-10-03 14:42:16.689847", "msg": "non-zero return code", "rc": 1, "start": "2018-10-03 14:42:16.687842", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************************************
	to retry, use: --limit @/home/ckoester/test/test2.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************
host1                      : ok=3    changed=2    unreachable=0    failed=0
host2                      : ok=2    changed=1    unreachable=0    failed=1
```

Note: Saw issue #36772 but not sure if it is related. The force_handlers settings seems to make no difference in this case.

**Comment by carstenkoester** [comment]
To add:

Issue is not specific to invoking handlers using `meta: flush_handlers` either. Following playbook also continues post-failure:

``` yaml
- hosts: all
  any_errors_fatal: True
  tasks:
    - name: Test task 1 - all succeed
      command: /bin/true
      notify: Test handler 1

  handlers:
    # This handler will fail for host 2
    - name: Test handler 1
      command: /bin/{{ want }}

- hosts: all
  any_errors_fatal: True
  tasks:
    # Should not get here
    - name: Test task 2 - should not get here
      command: /bin/true
```
