### ISSUE TITLE
VMware: Return any Tags Assigned to Cluster as value in returned dict

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#46458]
##### SUMMARY

Tag assignment not present in response data.

##### ISSUE TYPE
- Feature Idea
Add "tags" key with all assigned tag names as value,
in return json

##### COMPONENT NAME

vmware_cluster_facts

##### ADDITIONAL INFORMATION

It would provide capacity to identify if cluster is to be included or excluded from automation,
for any given reason, eg generic configuration for a specific cluster may impact cluster operations, hence the requirement to have capacity to exclude it if possible.

```yaml
- name: Gather facts from datacenter about specific cluster
  vmware_cluster_facts:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    cluster_name: DC0_C0
    validate_certs: False
  delegate_to: localhost
  register: cluster_facts
```

##### EXPECTED RESULTS

Tags currently assigned to the cluster

##### ACTUAL RESULTS

Tag assignment not present in response data
