### ISSUE TITLE
Return any Tags Assigned to VM as value in returned dict

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#46460]
##### SUMMARY

Tag assignment not present in response data.

##### ISSUE TYPE
- Feature Idea
Add "tags" key with all assigned tag names as value,
in return json

##### COMPONENT NAME

vmware_vm_facts

##### ADDITIONAL INFORMATION

It would provide capacity to identify if a VM is to be included or excluded from automation,
for any given reason, eg generic configuration for a specific VM may impact the operations of a special case VM, hence the requirement to have capacity to exclude it if possible.

```yaml
- name: Gather all registered virtual machines
  vmware_vm_facts:
    hostname: esxi_or_vcenter_ip_or_hostname
    username: username
    password: password
    uuid: 2341234123412341234123
  delegate_to: localhost
  register: vmfacts
```

##### EXPECTED RESULTS

Tags currently assigned to the VM

##### ACTUAL RESULTS

Tag assignment not present in response data
