### ISSUE TITLE
VMware: Return any Tags Assigned to HOST as value in returned dict

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#46461]
##### SUMMARY

Tag assignment not present in response data.

##### ISSUE TYPE
- Feature Idea
Add "tags" key with all assigned tag names as value,
in return json

##### COMPONENT NAME

vmware_host_facts

##### ADDITIONAL INFORMATION

It would provide capacity to identify if a HOST is to be included or excluded from automation,
for any given reason, eg generic configuration for a specific HOST may impact the operations of a special case HOST, hence the requirement to have capacity to exclude it if possible.

```yaml
- name: Gather vmware host facts
  vmware_host_facts:
    hostname: "{{ esxi_server }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
  register: host_facts
  delegate_to: localhost
```

##### EXPECTED RESULTS

Tags currently assigned to the HOST

##### ACTUAL RESULTS

Tag assignment not present in response data
