### ISSUE TITLE
Bug: onyx_magp does not support onyx version 3.6.6000 or higher

### ISSUE THREAD

**Issue by anasbadaha** [ansible/ansible#46475]
##### SUMMARY
onyx_magp module failed on switches with os version higher than 3.6.6000 because of change in json output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/lib/ansible/modules/network/onyx/onyx_magp.py

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] 

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
- hosts: switch132
  gather_facts: no
  connection: network_cli
  become: yes
  vars: 
    ansible_network_os: onyx
  tasks:
    - onyx_magp:
         magp_id: 201
         router_ip: 192.168.8.2
         router_mac: AA:IB:2C:3D:4E:5F
        interface: vlan 1002

```

##### EXPECTED RESULTS
attached yml file should be passed successfully when run it! on inyx switch with os higher than 3.6.6000

##### ACTUAL RESULTS

```
fatal: [sn2410_leaf1_1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_2cIQBk/ansible_module_onyx_magp.py\", line 227, in <module>\n    main()\n  File \"/tmp/ansible_2cIQBk/ansible_module_onyx_magp.py\", line 223, in main\n    OnyxMagpModule.main()\n  File \"/tmp/ansible_2cIQBk/ansible_modlib.zip/ansible/module_utils/network/onyx/onyx.py\", line 240, in main\n  File \"/tmp/ansible_2cIQBk/ansible_modlib.zip/ansible/module_utils/network/onyx/onyx.py\", line 218, in run\n  File \"/tmp/ansible_2cIQBk/ansible_module_onyx_magp.py\", line 150, in load_current_config\n    self._update_magp_data(magp_data)\n  File \"/tmp/ansible_2cIQBk/ansible_module_onyx_magp.py\", line 137, in _update_magp_data\n    magp_id = self.get_magp_id(magp_item)\n  File \"/tmp/ansible_2cIQBk/ansible_module_onyx_magp.py\", line 123, in get_magp_id\n    return int(header.split()[1])\nAttributeError: 'NoneType' object has no attribute 'split'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}


```
