### ISSUE TITLE
Yum module reporting error when deleting package correctly

### ISSUE THREAD

**Issue by guidodobboletta** [ansible/ansible#46495]
##### SUMMARY
Yum module incorrectly reporting an error when removing packages succesfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /home/guido/finetune/infra/ansible.cfg
  configured module search path = [u'/home/guido/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/guido/.local/lib/python2.7/site-packages/ansible
  executable location = /home/guido/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/guido/finetune/infra/ansible.cfg) = [u'/home/guido/finetune/infra/inventory']
DEFAULT_ROLES_PATH(/home/guido/finetune/infra/ansible.cfg) = [u'/home/guido/finetune/infra/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/guido/finetune/infra/ansible.cfg) = /home/guido/finetune/infra/.vault_pass.txt
INVENTORY_ENABLED(/home/guido/finetune/infra/ansible.cfg) = [u'aws_ec2', u'host_list', u'script', u'yaml', u'ini']
RETRY_FILES_ENABLED(/home/guido/finetune/infra/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Linux ubuntu 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04.1 LTS 
Target OS: Amazon Linux latest version

##### STEPS TO REPRODUCE
Run the playbook several times, sometimes it will report the deletion as an error.

```yaml
- name: Delete MySQL packages
  become: yes
  yum:
    name: ['mysql', 'MySQL-python27']
    state: absent
```

##### EXPECTED RESULTS
It should always report as a success when deleting the yum package

##### ACTUAL RESULTS
It sometimes returns an error when deleting the package.

```
fatal: [ec2-18-205-250-119.compute-1.amazonaws.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_downgrade": false, 
            "autoremove": false, 
            "bugfix": false, 
            "conf_file": null, 
            "disable_excludes": null, 
            "disable_gpg_check": false, 
            "disable_plugin": [], 
            "disablerepo": [], 
            "download_only": false, 
            "enable_plugin": [], 
            "enablerepo": [], 
            "exclude": [], 
            "install_repoquery": true, 
            "installroot": "/", 
            "list": null, 
            "name": [
                "mysql", 
                "MySQL-python27"
            ], 
            "releasever": null, 
            "security": false, 
            "skip_broken": false, 
            "state": "absent", 
            "update_cache": false, 
            "update_only": false, 
            "use_backend": "auto", 
            "validate_certs": true
        }
    }, 
    "msg": "", 
    "rc": 0, 
    "results": [
        "Loaded plugins: priorities, update-motd, upgrade-helper\nResolving Dependencies\n--> Running transaction check\n---> Package MySQL-python27.x86_64 0:1.2.3-11.14.amzn1 will be erased\n---> Package mysql.noarch 0:5.5-1.6.amzn1 will be erased\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package             Arch        Version                  Repository       Size\n================================================================================\nRemoving:\n MySQL-python27      x86_64      1.2.3-11.14.amzn1        @amzn-main      229 k\n mysql               noarch      5.5-1.6.amzn1            @amzn-main      0.0  \n\nTransaction Summary\n================================================================================\nRemove  2 Packages\n\nInstalled size: 229 k\nDownloading packages:\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Erasing    : mysql-5.5-1.6.amzn1.noarch                                   1/2 \n  Erasing    : MySQL-python27-1.2.3-11.14.amzn1.x86_64                      2/2 \n  Verifying  : mysql-5.5-1.6.amzn1.noarch                                   1/2 \n  Verifying  : MySQL-python27-1.2.3-11.14.amzn1.x86_64                      2/2 \n\nRemoved:\n  MySQL-python27.x86_64 0:1.2.3-11.14.amzn1     mysql.noarch 0:5.5-1.6.amzn1    \n\nComplete!\n"
    ]
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/yum.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @kustodian @maxamillion @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by guidodobboletta** [comment]
Here's a more clear cut example of what I'm saying. Both of these runs were of the exact same playbook and code, nothing was altered between the two.

![screenshot from 2018-10-04 11-21-09](https://user-images.githubusercontent.com/24704808/46494885-9cf60680-c7d9-11e8-99dd-f7b0672fddf5.png)
![screenshot from 2018-10-04 11-40-19](https://user-images.githubusercontent.com/24704808/46494888-9ebfca00-c7d9-11e8-8fb3-2072533b5364.png)

**Comment by samdoran** [comment]
cc @maxamillion

**Comment by ghost** [comment]
Except that the mysql packages are not the same for what the playbook run reports. ~~Is this the same machine?~~
* Failed run: `mysql.noarch 0:5.5-1.6.amzn1`
* Successful run: `mysql55.x86_64 0:5.5.61-1.22.amzn1`
The build is different, it would be helpful to give more details in regards the context where you run the playbook.

**Comment by guidodobboletta** [comment]
This is the exact same EC2 Amazon Linux host on both runs. There were no changes or anything done to it between runs.

The plays that are run are:

```
- name: Install required MySQL packages
  become: yes
  yum:
    name: ['mysql', 'MySQL-python27']
    state: present

some other tasks

- name: Delete required MySQL packages
  become: yes
  yum:
    name: ['mysql', 'MySQL-python27']
    state: absent
```

**Comment by guidodobboletta** [comment]
If you look at the failed output you'll see that it still reports as "Complete!" without any errors so it still shouldn't report that task as failed.

**Comment by ghost** [comment]
This is not that helpful but neither is what we have documented so far. I was trying to reproduce but have no amazon 1 boxes, however, I'm **guessing** that your repositories take part of the blame here.
Have you tried troubleshooting this by using yum on its own?
```bash
yum list | grep -i mysql
yum install -y mysql
yum list installed | grep -i mysql
yum install -y mysql # should do nothing, you have it already
yum list installed | grep mysql # anything new here?
yum remove -y mysql
yum list installed | grep mysql # looking the same?
```

As I said, I could not reproduce using a more recent amazon image, so this is just guessing.

**Comment by guidodobboletta** [comment]
Ok so I did

`yum list installed | grep -i mysql`

And no packages came up. I then rerun the playbook on the host and it still has the same issue.
This are the plays that run:

```
- name: Install required MySQL packages
  become: yes
  yum:
    name: ['mysql', 'MySQL-python27']
    state: present

- name: Create application specific users
  mysql_user:
    name: "{{ item }}"
    password: "{{ lookup('vars', item + '_db_pwd') }}"
    priv: 'amerit.*:ALL'
    login_user: "root"
    login_host: "{{ hostvars.localhost.databases_stack.stack_outputs.mysqlAuroraEndpoint }}"
    login_password: "{{ vault_maria_db_password }}"
    host: "%"
    state: present
  with_items:
    - cb_svc_accounts
    - cb_svc_cbapi
    - cb_svc_fym
    - cb_svc_metadata
    - cb_svc_reporting

  # We define the MySQL for easy reuse and use custom commands to create IAM users as Ansible does not
  # support the option to define different authentication plugins such as 'AWSAuthenticationPlugin'
- name: Define MySQL command
  shell: echo "mysql -h {{ hostvars.localhost.databases_stack.stack_outputs.mysqlAuroraEndpoint }} -uroot -p{{ vault_maria_db_password }} -e "
  register: mysql

  # We find out if the iam users already exist, if they do we won't try to run the creation to avoid errors
- name: Find if IAM users are created
  shell: "{{ mysql.stdout }} \"SELECT USER FROM mysql.user where USER LIKE 'iam_dev%';\""
  register: mysql_user_output

- name: Create IAM users and set permissions
  block:
    - shell: "{{ mysql.stdout }} \"CREATE USER iam_dev_read IDENTIFIED WITH AWSAuthenticationPlugin AS 'RDS';\""
    - shell: "{{ mysql.stdout }} \"GRANT SELECT ON amerit.* TO iam_dev_read@'%';\""
    - shell: "{{ mysql.stdout }} \"CREATE USER iam_dev_write IDENTIFIED WITH AWSAuthenticationPlugin AS 'RDS';\""
    - shell: "{{ mysql.stdout }} \"GRANT ALL ON amerit.* TO iam_dev_write@'%';\""
  when: "'Empty set' is search(mysql_user_output.stdout)"

- name: Flush privileges
  shell: "{{ mysql.stdout }} \"FLUSH PRIVILEGES;\""

- name: Delete required MySQL packages
  become: yes
  yum:
    name: ['mysql', 'MySQL-python27']
    state: absent
```
