### ISSUE TITLE
import_role task with vars supplied per task change exposed vars

### ISSUE THREAD

**Issue by kmschl2** [ansible/ansible#46493]
##### SUMMARY
Ansible 2.7 makes default vars available for whole play when using import_role (see changelog)
But vars supplied via "vars:" on import_role task once also change exposed defaults vars. This behaviour makes it impossible to overwrite role defaults via vars when using a role more than once.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- lib/ansible/modules/utilities/logic/import_role.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/automation/ansible.cfg) = True
HOST_KEY_CHECKING(/home/automation/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/automation/ansible.cfg) = False
```

##### OS / ENVIRONMENT

not applicable

##### STEPS TO REPRODUCE

roles/apache-vhost/defaults/main.yml
```yaml
---
serveraliases: []
```

Run tasks:
```yaml
- import_role:
    name: apache-vhost
  vars:
    servername: "abc"
    serveraliases:
      - "foo"
- import_role:
    name: apache-vhost
  vars:
    servername: "def"
     # serveraliases not set here
```

##### EXPECTED RESULTS

Second task import_role uses var from role defaults making serveraliases equal to []

##### ACTUAL RESULTS

Second task import_role has serveraliases equal to ['foo']

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/import_role.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/import_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by guillemsola** [comment]
I just faced the same issue my playbooks was something like this

```
---
- hosts: wslbackends, wslfrontends, wsportals, SQL, sehosts
  gather_facts: true
  strategy: linear
  vars:
    component: "XYZ"
    workfolder: "c:\\ansible\\{{ component }}"
  tasks:
    - import_role:
        name: xyz
        tasks_from: install_backend

... more imports ...

    - import_role:
        name: appnew
        tasks_from: configure_xyz_azure
```

and then in the role `appnew`, vars/main.yml I have this

```
component: "appNew"
```

This import at the end is overwriting the whole playbook thus making it fail.

I understand this is not an expected behavior.
