### ISSUE TITLE
pip packager cannot accept multiple extras in the name field (assumes multiple packages)

### ISSUE THREAD

**Issue by sapphire-janrain** [ansible/ansible#46519]
##### SUMMARY
Essentially what we're trying to do is install a specific version of airflow with multiple extras through the pip module.

When Ansible 2.11 rolls out and removes the ability to do this in a loop, this will become a more serious bug I think.

The bug itself: One is not allowed to pass a name which contains multiple extras in a package name; that is `name:"apache-airflow[celery,crypto,postgres]"` The pip modules believes this is three packages with the names: "apache-airflow[celery" "crypto" and "postgres]"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pip

##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/sapphire/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

However, my coworkers are using 2.6.5 and 2.5.2 and I've read the code for the pip module and can see the issue still exists in the devel branch.

##### CONFIGURATION

```paste below
```

It was blank.

##### OS / ENVIRONMENT

Running from: macOS High Sierra  Version 10.13.6

Obviously it's provisioning a cloud instance, though, Ubuntu of some sort.

The pip version it installs and uses is 8.1.1

##### STEPS TO REPRODUCE

```yaml
- name: Airflow | Installing Airflow Extra Packages
  pip:
    executable: "pip3"
    name: "apache-airflow[celery,crypto,postgres]"
    version: "1.9.0"
```

##### EXPECTED RESULTS

Install the things as `pip3 apache-airflow[celery,crypto,postgres]==1.9.0` would.

##### ACTUAL RESULTS

```paste below
    airflow-ami: TASK [airflow : Airflow | Installing Airflow Extra Packages] *******************
    airflow-ami: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "'version' argument is ambiguous when installing multiple package distributions. Please specify version restrictions next to each package in 'name' argument."}
```

##### MORE INFORMATION
The split located [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py#L298) is too naive - it doesn't expect the possibility of a comma-separated list in the extras segment. I double-checked in pip and it is the only option as a separator, seen [here](https://github.com/pypa/pip/blob/master/src/pip/_vendor/packaging/requirements.py#L44).

Unfortunately, with three or more extras, a simple check in _is_package_name would not work. A simple option would be converting another separator, but a more complex option would be a regex operation something like this:

```python
>>> re.findall(r'[^,\[]+(?:\[[^\]]*\])?', 'apache-airflow[celery,crypto,postgres],boto3')
['apache-airflow[celery,crypto,postgres]', 'boto3']
>>> re.findall(r'[^,\[]+(?:\[[^\]]*\])?', 'apache-airflow[celery,crypto,postgres]')
['apache-airflow[celery,crypto,postgres]']
```

I don't have enough knowledge of this repo to feel comfortable contributing it myself.

This is a particular issue with the version being necessary, because of the version ambiguity error.

For others encountering this issue, this is the method I ended up with:

```yaml
- name: Airflow | Installing Airflow Extra Packages
  pip:
    executable: "pip3"
    name: "apache-airflow[{{ item }}]==1.9.0"
  with_items: "{{ airflow_extra_packages }}"
  when: airflow_extra_packages
```

Disabling squash_actions for pip should also be an option but according to the documentation, it's not a default to begin with. So I'm not sure the issue there.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/language/pip.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lujeni @mattupstate @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by goodspark** [comment]
I believe I'm seeing something similar. At least, I'm also using extras to install additional dependencies through the pip module.

Ubuntu 16.04
Ansible 2.7.0
Python 2.7.14

Ansible step
```
- name: install python requirements
  become_user: "{{ manage_user }}"
  pip:
    name:
      - "{{ application_path }}/[something,else,blah]"
    extra_args: --no-cache-dir -e
    virtualenv: "{{ application_root }}"
  environment:
    PIP_TRUSTED_HOST: "github.com"
    PIP_PROCESS_DEPENDENCY_LINKS: "1"
    PIP_NO_BINARY: "grpcio"
```

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": ["/path/to/app/bin/pip2", "install", "--no-cache-dir", "-e", "/path/to/app/[something", "else", "blah]"], "msg": "stdout: New python executable in /path/to/app/bin/python\nInstalling setuptools, pip, wheel...done.\n\n:stderr: Invalid requirement: 'development]'\nTraceback (most recent call last):\n  File \"/path/to/app/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py\", line 253, in from_line\n    req = Requirement(req)\n  File \"/path/to/app/local/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py\", line 97, in __init__\n    requirement_string[e.loc:e.loc + 8]))\nInvalidRequirement: Invalid requirement, parse error at \"']'\"\n\n"}
```
