### ISSUE TITLE
When using the "subnet_mappings" parameter on the elb_network_lb on ansible 2.6.3 the module print out that the "subnets" parameter is required.

### ISSUE THREAD

**Issue by sonegoh** [ansible/ansible#46513]
##### SUMMARY
When using the "subnet_mappings" parameter on the elb_network_lb on ansible 2.6.3 the module print out that the "subnets" parameter is required. 
When i add the "subnets" i get the error - "parameters are mutually exclusive: subnets, subnet_mappings" as i thought, this is what your docs say.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elb_network_lb

##### ANSIBLE VERSION

```paste below
 2.6.3 
```

##### OS / ENVIRONMENT
ubuntu 14.04.5
##### STEPS TO REPRODUCE

```yaml
- name: Create NLB
  elb_network_lb:
    region: "{{ region }}"
    name: "{{ nlb_name }}"
    cross_zone_load_balancing: "{{ load_balancing_cross_zone | default('yes') }}"
    deletion_protection: "{{ deletion_protection | default('no') }}"
    subnet_mappings: "{{ nlb_mappings.results | map(attribute='ansible_facts.nlb_mapping') | list }}"
    deletion_protection: "{{ termination_protection }}"
    listeners:
      - Protocol: TCP
        Port: "{{ nlb_port | default(443)}}"
        DefaultActions:
          - Type: forward 
            TargetGroupName: "{{ target_group_name }}" 
    state: present
  register: nlb
```

##### EXPECTED RESULTS

create an NLB

##### ACTUAL RESULTS

```paste below
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/elb_network_lb.py

ClientError: An error occurred (ValidationError) when calling the CreateLoadBalancer operation: At least one subnet must be specified
			fatal: [localhost]: FAILED! => {
			    "boto3_version": "1.9.11", 
			    "botocore_version": "1.12.11", 
			    "changed": false, 
			    "error": {
			        "code": "ValidationError", 
			        "message": "At least one subnet must be specified", 
			        "type": "Sender"
			    }, 
			    "invocation": {
			        "module_args": {
			            "aws_access_key": null, 
			            "aws_secret_key": null, 
			            "cross_zone_load_balancing": true, 
			            "deletion_protection": true, 
			            "ec2_url": null, 
			            "listeners": [
			                {
			                    "Certificates": null, 
			                    "DefaultActions": [
			                        {
			                            "TargetGroupName": " there is a string here", 
			                            "Type": "forward"
			                        }
			                    ], 
			                    "Port": 443, 
			                    "Protocol": "TCP", 
			                    "SslPolicy": null
			                }
			            ], 
			            "name": "there a string here", 
			            "profile": null, 
			            "purge_listeners": true, 
			            "purge_tags": true, 
			            "region": "us-east-1", 
			            "scheme": "internet-facing", 
			            "security_token": null, 
			            "state": "present", 
			            "subnet_mappings": [
			                {
			                    "AllocationId": "there is a string here", 
			                    "SubnetId": "there is a string here"
			                }, 
			                {
			                    "AllocationId": "there is a string here", 
			                    "SubnetId": "there is a string here"
			                }
			            ], 
			            "subnets": null, 
			            "tags": null, 
			            "validate_certs": true, 
			            "wait": null, 
			            "wait_timeout": null
			        }
			    },
```
