### ISSUE TITLE
[azure_rm_virtualmachine] add support for StandardSSD_LRS

### ISSUE THREAD

**Issue by rnsc** [ansible/ansible#46537]
##### SUMMARY

Azure announced the general availability of StandardSSD_LRS back in June.
Ansible 2.7 azure_rm_virtualmachine module isn't supporting those disk types.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine:
- managed_disk_type: StandardSSD_LRS

##### ADDITIONAL INFORMATION

```yaml
- name: "azure_rm_virtualmachine"
  azure_rm_virtualmachine:
    resource_group: "TEST-RG"
    name: "test"
    managed_disk_type: StandardSSD_LRS
    os_disk_caching: ReadWrite
    network_interfaces: "test-nic"
    virtual_network_name: "test-vnet"
    subnet_name: "test-subnet"
    vm_size: "Standard_F1s_v2"
    admin_username: "test"
    admin_password: "BlahBlahblah12345"
    os_type: Windows
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: "2012-R2-Datacenter"
      version: latest
```
