### ISSUE TITLE
copy module doesn't use same json value to store destination path

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#4653]
The field used to store the name of the destination file isn't consistent.  For the same values of "src" and "dest", the first call will return the destination path in an attribute called "dest".  On subsequent calls, the path is provided in an attribute called "path".  This makes it difficult to register the result of a `copy` task as a variable given that the variable attributes aren't consistent.

I'd like to propose that only `path` be used in both cases (similar to how the `file` module works).

To test ...

``` yaml
- hosts: local
  tasks:
   - copy: src={{lookup('env','HOME')}}/.bashrc dest=/tmp/somefile
     register: get_url_result
   - debug: var=get_url_result
   - copy: src={{lookup('env','HOME')}}/.bashrc dest=/tmp/somefile
     register: get_url_result
   - debug: var=get_url_result
```

``` yaml
PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [copy src=/Users/jlaska/.bashrc dest=/tmp/somefile] ********************* 
changed: [127.0.0.1]

TASK: [debug var=get_url_result] ********************************************** 
ok: [127.0.0.1] => {
    "get_url_result": {
        "changed": true, 
        "dest": "/tmp/somefile", 
        "gid": 20, 
        "group": "staff", 
        "invocation": {
            "module_args": "src=/Users/jlaska/.bashrc dest=/tmp/somefile", 
            "module_name": "copy"
        }, 
        "md5sum": "742cf5cdefe1c037abef30119cc76c7f", 
        "mode": "0644", 
        "owner": "jlaska", 
        "size": 8355, 
        "src": "/Users/jlaska/.ansible/tmp/ansible-1382553108.73-173127491482925/source", 
        "state": "file", 
        "uid": 501
    }
}

TASK: [copy src=/Users/jlaska/.bashrc dest=/tmp/somefile] ********************* 
ok: [127.0.0.1]

TASK: [debug var=get_url_result] ********************************************** 
ok: [127.0.0.1] => {
    "get_url_result": {
        "changed": false, 
        "gid": 20, 
        "group": "staff", 
        "invocation": {
            "module_args": "src=/Users/jlaska/.bashrc dest=/tmp/somefile", 
            "module_name": "copy"
        }, 
        "mode": "0644", 
        "owner": "jlaska", 
        "path": "/tmp/somefile", 
        "size": 8355, 
        "state": "file", 
        "uid": 501
    }
}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=5    changed=1    unreachable=0    failed=0   
```
