### ISSUE TITLE
win_acl to have /reset capability of icacls

### ISSUE THREAD

**Issue by SagarKodam** [ansible/ansible#46540]
##### SUMMARY

win_acl can be used to set ACL to files and folders, but cannot be used to reset the permissions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_acl

##### ADDITIONAL INFORMATION

```yaml
- name: Reset current to default permission for temp folder
  win_acl:
    path: C:\temp
    state: reset
```
