### ISSUE TITLE
Make the Redfish input parameters consistent with the Redfish property names

### ISSUE THREAD

**Issue by billdodd** [ansible/ansible#46549]
##### SUMMARY

Some of the Redfish module input parameters correspond to Redfish property names. For example,
in the redfish_command.py module there are input parameters `username`, `userpswd` and `userrole`. These parameters correspond to Redfish properties `UserName`, `Password` and `RoleId` respectively. (This is not a complete list of the impacted parameters. Will need to scan the parameters of all 3 Redfish modules to get a full list.)

To the degree possible within the constraints of the Ansible and Python coding guidelines (like PEP8), these parameters should match their corresponding Redfish property names. By maintaining this consistency users of the Redfish modules will have an easier and more intuitive experience.

Note that the example above has some inherent difficulty. There are 2 input parameters for username and password each. One set for the account being acted on (created, updated or deleted) and one set for the basic auth credentials being supplied for the operation. So an exception or compromise will have to be made for that particular set of parameters.

And as suggested above, the parameter names may not be able to match the case of the Redfish property names due to PEP8 guidelines.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_command.py
redfish_config.py
redfish_facts.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 693f3219d4) last updated 2018/09/20 12:07:29 (GMT -500)
  config file = None
  configured module search path = ['/Users/bdodd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bdodd/Development/git/ansible/lib/ansible
  executable location = /Users/bdodd/Development/git/ansible/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
[no output]
```

##### OS / ENVIRONMENT

Targets are Redfish hosts.

##### STEPS TO REPRODUCE

Run a playbook that has input parameters that correspond to Redfish properties and compare the parameter names used to the corresponding Redfish properties

```yaml
---
- hosts: myhosts
  connection: local
  name: Add User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/all

  tasks:

  # When adding a user, you must enable it afterwards
  - name: Add user
    redfish_command:
      category: Accounts
      command: AddUser
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
      username: "{{ username }}"
      userpswd: "{{ userpswd }}"
      userrole: "{{ userrole }}"
```

##### EXPECTED RESULTS

The parameter names used should match (as closely as possible) the Redfish property names.

##### ACTUAL RESULTS

Some of the parameter names used do not match the Redfish property names.

```paste below

```
