### ISSUE TITLE
include_tasks with variables in a loop fails

### ISSUE THREAD

**Issue by SimplySeth** [ansible/ansible#46550]
##### SUMMARY
Play errors out with a complain about quotes for include_tasks with variables

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/utilities/logic/include_tasks.py

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /home/reinose/ansible_onprem_deployments/ansible.cfg
  configured module search path = ['/home/reinose/ansible_onprem_deployments/venv/lib/python3.6/site-packages/ara/plugins/modules']
  ansible python module location = /home/reinose/ansible_onprem_deployments/venv/lib/python3.6/site-packages/ansible
  executable location = /home/reinose/ansible_onprem_deployments/venv/bin/ansible
  python version = 3.6.3 (default, Jan  4 2018, 16:40:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/reinose/ansible_onprem_deployments/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/reinose/ansible_onprem_deployments/ansible.cfg) = -o UserKnownHostsFile=/dev/null
DEFAULT_ACTION_PLUGIN_PATH(env: ANSIBLE_ACTION_PLUGINS) = ['/home/reinose/ansible_onprem_deployments/venv/lib/python3.6/site-pac
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = ['/home/reinose/ansible_onprem_deployments/venv/lib/python3.6/site
DEFAULT_HOST_LIST(/home/reinose/ansible_onprem_deployments/ansible.cfg) = ['/home/reinose/ansible_onprem_deployments/inventory']
DEFAULT_LOG_PATH(/home/reinose/ansible_onprem_deployments/ansible.cfg) = /home/reinose/ansible_onprem_deployments/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/reinose/ansible_onprem_deployments/ansible.cfg) = ['/home/reinose/ansible_onprem_deployments/pl
DEFAULT_MANAGED_STR(/home/reinose/ansible_onprem_deployments/ansible.cfg) = "#############################
***      Ansible      ***
Verizon Telematics Managed:
Modified on: %Y-%m-%d %H:%M:%S
By: {uid} on {host}
Using template: {file}
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/home/reinose/ansible_onprem_deployments/venv/lib/python3.6/site-packages/ara/plug
DEFAULT_ROLES_PATH(/home/reinose/ansible_onprem_deployments/ansible.cfg) = ['/home/reinose/ansible_onprem_deployments/roles']
DEFAULT_TIMEOUT(/home/reinose/ansible_onprem_deployments/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/reinose/ansible_onprem_deployments/ansible.cfg) = /etc/ansible/.vpw
HOST_KEY_CHECKING(/home/reinose/ansible_onprem_deployments/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/reinose/ansible_onprem_deployments/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Linux dallvdopap350m 3.10.0-862.6.3.el7.x86_64 #1 SMP Fri Jun 15 17:57:37 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
##### STEPS TO REPRODUCE

```yaml
- include_tasks: "upload.yml cfg_file={{ cfile }}"                                                                                
loop:                                                                                                                             
    - "{{ service_name }}.yml"                                                                                                      
    - "commons.yml"                                                                                                              
loop_control:
    loop_var: cfile
tags:
    - always
```

##### EXPECTED RESULTS
No errors

##### ACTUAL RESULTS

```
fatal: [10.254.10.167]: FAILED! => {"reason": "Invalid options for include_tasks: \"cfg_file\n\nThe error appears to have been in '/home/reinose/ansible_onprem_deployments/roles/deploy/tasks/configs.yml': line 28, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include_tasks: \"upload.yml cfg_file={{ cfile }}\"\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include_tasks.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_tasks.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by SimplySeth** [comment]
Reverted to 2.6.5 it works just fine ..

**Comment by s-hertel** [comment]
Looks like this stopped working in da4ff18406bb9e052a7e81796aed11e2dea1bfc9

**Comment by s-hertel** [comment]
@SimplySeth it looks like the problem is passing arbitrary vars to your include_tasks, rather than the loop that is the problem. It looks like it was a bug that anything could be arbitrarily passed in (@sivel correct me if I'm mistaken reading your commit message). @SimplySeth Your loop vars are available without adding them to the `include_tasks` line (this is true for Ansible 2.6 too).
For example try out:
playbook:
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: include some things
      include_tasks: "upload.yml"
      loop:
        - "commons.yml"
      loop_control:
        loop_var: cfile
```
a test upload.yml file:
```
---
- debug: var=cfile
```

Please reopen this if I've missed something!
