### ISSUE TITLE
Usermanagement play book error

### ISSUE THREAD

**Issue by thopuri** [ansible/ansible#46559]
```yaml

---
  -hosts: all
   become_root: yes
   
    #This task creates groups
    -name: add a group
       group:
       name: {{ item }}
       state:present 
       which_items:
          - demogroup
          - demogroup1
          - demogroup2
      tags: add_new_group
 
    #This task will create a users

     -name: add a users
       user:
        name: {{ item }}
        state:present
        shell=/bin/bash
        which_items:
           - demouser1
           - demouser2
           - demouser3
       tags: add_new_user
 
     #This task generate ssh keys

       -name: generate ssh keys
          user:
            generate_ssh_keys=yes
            ssh_key_bits=4096
            ssh_key_files=.ssh/id_rsa
           which_items:
              - demouser1
            tags: generate_ssh_keys

    
     #This task will copy the public key

        -name: update authorized keys for a user
           authorized_key:
              user: demouser1
              state: present
              key: "{{ lookup ('file', '/home/demouser1/.ssh/id_rsa.pub') }}"
           tags: copy_pub_key
         
```
--------------------------------------------------------------------

Error receiving is like below 

```
The error appears to have been in '/etc/ansible/y1.yml': line 3, column 17, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - hosts: all
     become_root: yes
                ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: mapping values are not allowed in this context
  in "<unicode string>", line 3, column 17
```
