### ISSUE TITLE
git module undefined behavior when 're-cloning'

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#4658]
My use case is that I'm cloning a git repository, then using the pip module to install a project if the git action has changed.  Because I would like to have the option of either deploying from mainline or my personal clone, the repo argument is a variable so that I might change the URL.  However, I have noticed that the git repo has some weird behavior when the repo URL changes.  I would expect one of the two behaviors:
1.  The new clone fails and ansible aborts because an existing repository already exists in the location.
2.  The existing clone is removed and a new one is created.

In the first case, the task would be marked as failed while in the second, the task would marked as changed.  What happens however, is that nothing happens!

Here is a sample playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  vars:
    clone_dest: '/tmp/ansible_clone'
    version: 'devel'
  tasks:

  - name: Clone the ansible canonical repo into {{ clone_dest }}
    git: repo=https://github.com/ansible/ansible.git
         dest={{ clone_dest }}
         version={{ version }}

  - name: Clone a NEW repository into the same {{ clone_dest }} location
    git: repo=https://github.com/SirScott/ansible.git
         dest={{ clone_dest }}
         version={{ version }}

  - name: Clean up {{ clone_dest }}
    command: rm -rf {{ clone_dest }}
```

The output of running this task:

```
$ ansible-playbook -i hosts -v git_test.yml

PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Clone the ansible canonical repo into /tmp/ansible_clone] ************** 
changed: [127.0.0.1] => {"after":     "e34cde6bef26309919eb4da21c58a38b61770577", "before": null, "changed": true}

TASK: [Clone a NEW repository into the same /tmp/ansible_clone location] ****** 
ok: [127.0.0.1] => {"after": "e34cde6bef26309919eb4da21c58a38b61770577",     "before": "e34cde6bef26309919eb4da21c58a38b61770577", "changed": false}

TASK: [Clean up /tmp/ansible_clone] ******************************************* 
changed: [127.0.0.1] => {"changed": true, "cmd": ["rm", "-rf", "/tmp/ansible_clone"], "delta": "0:00:00.017914", "end": "2013-10-23 13:38:47.240769", "rc": 0, "start": "2013-10-23 13:38:47.222855", "stderr": "", "stdout": ""}

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=4    changed=2    unreachable=0    failed=0   
```

Note that in the second task's output, the `changed` attribute is `False`.

Mostly, this is undefined behavior and at a minimum should be documented, but personally the actual behavior also seems incorrect and unintuitive.  If I had to vote for a desired behavior, I'd like to see option number 2 above, as it'd certainly make my role definition a lot simpler!

Finally, this behavior is observed on the following version of ansible:

`$ ansible --version
ansible 1.4 (devel e34cde6bef) last updated 2013/10/23 08:32:52 (GMT -600)`
