### ISSUE TITLE
Allow 'npm' to install top-level modules

### ISSUE THREAD

**Issue by dchancogne** [ansible/ansible#4659]
**Scenario**:

Trying to install `uglify-js` (globally) because I need the _uglifyjs_ executable. Unfortunately the `npm` Ansible module won't install it because it's already listed as a dependency of another nodejs package (this other package is installed earlier in my playbook and I can't really move it). But when installed as dependency, it didn't get installed with the executable.

**Possible solutions**:
- A 'force' option to install regardless. But that's against idempotency I suppose.
- Make the `npm` Ansible module aware if a package is installed at top-level or not and allow installation is the package to be installed is strictly a dependency.

**Comment by mpdehaan** [comment]
Perhaps we should just modify it so scripts are already installed.

**Comment by dchancogne** [comment]
That could work. But some nodejs module install a lot of dependencies. Not sure I'd want to the executable for all these dependencies to cloud my path.

**Comment by mpdehaan** [comment]
There's a global flag in the latest npm source (at least on the devel branch), so I think I can close this one.

Thanks!

**Comment by nokome** [comment]
I'm new to `ansible` and not all that familiar with `npm` so I could be missing something but `global=yes` does not seem to fix this issue. I have the same problem as @dchancogne. My relevant task is:

```
- name: ensure Node packages are present
  npm: name={{ item }} global=yes
  with_items:
    - bower 
    - uglify-js 
    - node-sass
```

Which provides uglify-js but not at the top level:

```
vagrant@precise64:~$ npm list -g | grep uglify-js   
│ │ └─┬ uglify-js@2.3.6
```

That uglify-js is under `bower > handlebars` .

So uglifyjs is not available:

```
vagrant@precise64:~$ uglifyjs
The program 'uglifyjs' is currently not installed.  You can install it by typing:
 sudo apt-get install node-uglify
```

In my case, I suspect changing the order of `with_items` so that `uglify-js` is first will fix things. But I'm not sure this bug should be closed.

**Comment by bartdag** [comment]
I have the same issue. I am trying to install coffee-script, but it is already installed as a dependency for another package (grunt) and the ansible npm module thus thinks that it has nothing else to do. If I place coffee-script first in the list of packages to install, it is correctly installed at the top level (and still installed as a dependency of the grunt package, which is the expected behavior).

Before (not working)

``` yaml
- name: npm global install
  npm: global=yes name={{item}}
  with_items:
    - node-sass
    - grunt-cli
    - grunt
    - bower
    - coffee-script
```

After (working)

``` yaml
- name: npm global install
  npm: global=yes name={{item}}
  with_items:
    - coffee-script
    - node-sass
    - grunt-cli
    - grunt
    - bower
```
