### ISSUE TITLE
influxdb_user can't change password or admin-status on user

### ISSUE THREAD

**Issue by mattiasb** [ansible/ansible#46617]
##### SUMMARY

`influxdb_user` doesn't update users, only adds them.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`influxdb_user`

##### ANSIBLE VERSION
```
ansible --version
ansible 2.7.0
  config file = /home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg
  configured module search path = ['/home/mattiasb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mattiasb/.local/share/virtualenvs/AnsiblePlaybooks-SMAs_4Xa/lib/python3.6/site-packages/ansible
  executable location = /home/mattiasb/.local/share/virtualenvs/AnsiblePlaybooks-SMAs_4Xa/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### CONFIGURATION
```
ALLOW_WORLD_READABLE_TMPFILES(/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg) = True
DEFAULT_JINJA2_EXTENSIONS(/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg) = jinja2.ext.do
DEFAULT_REMOTE_USER(/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg) = vagrant
DEFAULT_ROLES_PATH(/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg) = ['/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles']
DEFAULT_STDOUT_CALLBACK(/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/mattiasb/.local/bin/ansible-vault-lastpass
HOST_KEY_CHECKING(/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg) = False
```

##### OS / ENVIRONMENT

The influxdb running in a libvirt Vagrant machine (Ubuntu 18.04):
```shell
$ vagrant ssh -c "docker ps"
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                    NAMES
97e38fc757bb        influxdb:1.5.4-alpine   "/entrypoint.sh infl…"   20 minutes ago      Up 20 minutes       0.0.0.0:8086->8086/tcp   influxdb
```

##### STEPS TO REPRODUCE

Apply the following playbook to a Vagrant machine that runs Ubuntu 18.04, docker and influxdb as a docker service.
```yaml
---
- hosts: ansible_role-influxdb
  become: true
  tasks:
    - name: Add user
      influxdb_user:
        hostname: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
        user_name: my_user
        user_password: s3cr3t
        admin: false
        state: present
      delegate_to: localhost
      become: false

    - name: Make admin
      influxdb_user:
        hostname: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
        user_name: my_user
        user_password: s3cr3t
        admin: true
        state: present
      delegate_to: localhost
      become: false

    - name: Change password
      influxdb_user:
        hostname: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
        user_name: my_user
        user_password: secret
        admin: true
        state: present
      delegate_to: localhost
      become: false
```

##### EXPECTED RESULTS

I expected:
1. ☑ `my_user`to be created
1. ☒ `my_user` to be admin
1. ☑ `my_user` to have changed password

**_EDIT: Changing passwords works fine if http auth is turned on_**

##### ACTUAL RESULTS

Applying the playbook on the running Vagrant machine. As you can see making the user `admin` and changing its password is marked as no changes.
```shell
$ vagrant provision 
==> ansible_role-influxdb: Running provisioner: ansible...
    ansible_role-influxdb: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --limit="ansible_role-influxdb" --inventory-file=/home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/.vagrant/provisioners/ansible/inventory -v test.yml
Using /home/mattiasb/Code/git.company.se/SRE/AnsiblePlaybooks/roles/influxdb/tests/ansible.cfg as config file

PLAY [ansible_role-influxdb] ***************************************************

TASK [Gathering Facts] *********************************************************
ok: [ansible_role-influxdb]

TASK [Add user] ****************************************************************
changed: [ansible_role-influxdb -> localhost] => changed=true

TASK [Make admin] **************************************************************
ok: [ansible_role-influxdb -> localhost] => changed=false

TASK [Change password] *********************************************************
ok: [ansible_role-influxdb -> localhost] => changed=false

PLAY RECAP *********************************************************************
ansible_role-influxdb      : ok=4    changed=1    unreachable=0    failed=0   
```

These users are present. Note that `my_user` isn't `admin`.
```shell
$ vagrant ssh -c "docker exec -it 97 influx -execute 'show users'"
user    admin
----    -----
root    false
my_user false
```
