### ISSUE TITLE
"msg": "argument disk is of type <type 'dict'>

### ISSUE THREAD

**Issue by dilipsharma2005** [ansible/ansible#46615]
##### SUMMARY
I write the below code.
```
---
- hosts: aci-dc
  connection: local

  tasks:
    - vmware_guest:
        hostname: 192.168.1.30
        username: administrator@vsphere.local
        password: Admin@123
        validate_certs: no
        name: newvm001
        state: present
        datacenter: aci-dc
#        datastore: datastore1
        folder: /vm

        hardware:
           memory_mb: 2048
           num_cpus: 2
           osid: ubuntu64Guest
           scsi: paravirtual
        disk:
           size_gb: 10
           datastore: datastore1
        networks:
           - name: "local"
             device_type: vmxnet3
```
But getting error while running playbook.
```
####################
TASK [Gathering Facts] *****************************************************************************************
ok: [192.168.1.30]

TASK [vmware_guest] ********************************************************************************************
fatal: [192.168.1.30]: FAILED! => {"changed": false, "msg": "argument disk is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"}
        to retry, use: --limit @/etc/ansible/playboks/fifth.retry
```

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
PLAY [aci-dc] **************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************
ok: [192.168.1.30]

TASK [vmware_guest] ********************************************************************************************
fatal: [192.168.1.30]: FAILED! => {"changed": false, "msg": "argument disk is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"}
        to retry, use: --limit @/etc/ansible/playboks/fifth.retry

PLAY RECAP *****************************************************************************************************
192.168.1.30               : ok=1    changed=0    unreachable=0    failed=1


```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@dilipsharma2005: thank you for submitting this pull-request !

cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Hi @dilipsharma2005,

Thank you for the issue, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in #ansible-vmware on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@dilipsharma2005 Thanks for reporting this issue. You are specifying disk as dictionary where as `vmware_guest` requires disk as a list as follows - 

```yaml
...
disk:
   - size_gb: 10  # <--- Notice '-' here
     datastore: datastore1
...
```
