### ISSUE TITLE
lookup plugin adding an extra newline

### ISSUE THREAD

**Issue by candeira** [ansible/ansible#4661]
Though the topic says "with password lookup plugin", I suspect this is true of any other lookup, but I haven't checked it.

This is the result of git bisect:

```
(enso-test)kandinski@desire:~/.virtualenvs/enso-test/src/ansible$ git bisect bad
35cb9dc22fca1851a716917dff9d224ad4fa06f7 is the first bad commit
commit 35cb9dc22fca1851a716917dff9d224ad4fa06f7
Author: Michael DeHaan <michael@ansibleworks.com>
Date:   Sat Oct 19 10:42:56 2013 -0400

    Work in progress about cleaning up template code.

:040000 040000 685a091f1b864d2242af15f6661c94f7a928e35b cd953ed7a99a5a3ec227c682ee60b17a3a981d98 M  lib
:040000 040000 2e2617caed2c964e46fe20277606425d57a9e0e8 e489befbdfec52fcf5e370c0e1c61f73bf5b8aa0 M  test
```

This is a sample playbook:

```
- hosts: somehosts
  user: someuser
  vars:
    mysql_password: >
      {{ lookup("password", "credentials/enso_%s_%s_%s_mysql_password" % (customer, role, deploy))}}
    core_api_token: >
      {{ lookup("password", "credentials/%s/enso_%s_%s_core_api_token" % (customer, customer, deploy)) }}
  tasks: 

  - name: put enso coreapi token in the coreapi database
    shell: >
      create=/home/artpro/coreapitoken_inserted echo "update authtoken_token SET \`key\`='{{ core_api_token }}', created='2011-01-01 10:00:00' WHERE user_id=1;" | mysql -u artpro -p{{ mysql_password }} enso_{{ customer }}_{{ role }}_{{ deploy }}

```

The error Ansible prints out:

```
TASK: [put enso coreapi token in the cms database] **************************** 
failed: [a.cms.CLIENTHERE.artpro.co] => {"changed": true, "cmd": "create=/home/artpro/coreapitoken_inserted echo \"update authtoken_token SET \\`key\\`='TOKENHERE\n', created='2011-01-01 10:00:00' WHERE user_id=1;\" | mysql -u artpro -pPASSWORDHERE\n enso_CLIENThere_cms_a ", "delta": "0:00:00.017474", "end": "2013-10-24 01:09:50.566526", "rc": 127, "start": "2013-10-24 01:09:50.549052"}
stderr: ERROR 1046 (3D000) at line 1: No database selected
/bin/sh: 3: enso_CLIENTHERE_cms_a: not found

FATAL: all hosts have already failed -- aborting
```

As you see, the templating inserts an extraneous \n after the result of the password lookup. I haven't been able to find where in the code, and reverting wasn't very straightforward.

When I use the old style templating, it seems to work fine, as long as I quote every string: 

```
  vars:
    mysql_password: $PASSWORD("credentials/enso_${customer}_${role}_${deploy}_mysql_password")
    core_api_token: $PASSWORD("credentials/{{ customer }}/enso_${customer}_${deploy}_core_api_token")
```

When I check out the previous commit to 35cb9dc22fca, playbook works fine with either style of templating.

**Comment by mpdehaan** [comment]
Sounds like you're not quite running the latest bits

See https://github.com/ansible/ansible/commit/214b0b052c3d54b58a531b0f7fb401ec3c0229f5

and let me know if that doesn't work for you.

**Comment by candeira** [comment]
Thanks for the quick answer. 

The problem is not that plugins don't work, but that they insert an extra newline, which breaks interpolation in templates.

Apologies for not saying the exact commit I was testing at, but it's really recent, and I do have those bits you point out:

```
~/.virtualenvs/enso-test/src/ansible$ git log -1
commit b9dd514713044e9cc66ed88ad54e0ea9f3521df8
Author: James Cammarata <jimi@sngx.net>
Date:   Wed Oct 23 12:09:36 2013 -0700

    Minor fix for putting 0-length files over accelerated connections

    Fixes #4652

~/.virtualenvs/enso-test/src/ansible$ git branch --contains 214b0b0
* devel
```

**Comment by mpdehaan** [comment]
Thanks,

I've updated the defect description to more accurately describe the problem and will reopen this for investigation

**Comment by candeira** [comment]
Yeah, sorry for the overly generic description. I'll do better next time.

**Comment by jctanner** [comment]
@candeira I can not reproduce this. Please add some debugging statements so that we can validate the newline character ...

```
- shell: echo -ne {{ mysql_password }} | od -c
- shell: echo -ne {{ core_api_token }} | od -c
```

**Comment by candeira** [comment]
Ok, so the regression is in two places, and none of them seem to be the lookup plugin.:

a) when quoting a {{ jinja_stlyle_plugin_call }} via the > Character, a newline gets inserted at the end.
b) when interpolating in the ${old_style}, the newline gets stripped. The interpolation in {{ jinja_style }} preserves it.

I'm writing myself a couple of tests,  and then I'll try to find and fix the bug(s):
a) no newline should be inserted at the end of a {{ jinja_block }} when quoting a var assignment via the > character
b) I'm pretty sure that stripping newlines off strings before interpolating them with {{ jinja_syntax }} is the right thing to do.

If I can't find it, I'll do a pull request for the tests, so someone else can give it a try.

**Comment by candeira** [comment]
The playbook below confirms the above analysis. Run with -v to see it break only when creating a var by quoting a {{ jinka_style_interpolation }} via the ">" character, and interpolating it later also with {{ jinja_syntax }}.

Workarounds: using the old, deprecated syntax anywhere solves the problem. So does not using ">" quoting.

```
---

- hosts: localhost
  user: kandinski
  tasks:
    - name: First we put the string 'this should all be on' in a file 
      shell: echo -n 'this_should_all_be_on' > /tmp/this

- hosts: localhost
  user: kandinski
  vars:
    this_1: $PASSWORD("/tmp/this")
    this_2: "{{lookup('password', '/tmp/this')}}"
    this_3: >
        {{ lookup('password', '/tmp/this') }}

  tasks:
    - name: syntax - old for creating the var -- old for interpolating
      shell: echo ${this_1} one line

    - name: syntax - old for creating the var -- new for interpolating
      shell: echo {{ this_1 }} one line

    - name: syntax - new for creating the var --regular quoting -- old for interpolating
      shell: echo ${this_2} one line

    - name: syntax - new for creating the var --regular quoting -- new for interpolating
      shell: echo {{ this_2 }} one line

    - name: syntax - new for creating the var -- ">" quoting -- old for interpolating
      shell: echo ${this_3} one line

    # This is the one that breaks
    - name: syntax - new for creating the var -- ">" quoting -- new for interpolating
      shell: echo {{ this_3 }} one line
```
