### ISSUE TITLE
check_mode option is not referenced in ec2_instance

### ISSUE THREAD

**Issue by cahlchang** [ansible/ansible#46611]
##### SUMMARY
In the ec2_instance module, the instance also starts up when check_mode is enabled.
I am working on this problem and I am planning to release PR later.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_instance

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.0
  config file = None
  configured module search path = ['/home/cahlchang/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, May  3 2018, 10:08:28) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$
# no changed
```

##### OS / ENVIRONMENT

ubuntu16.04

##### STEPS TO REPRODUCE

```sh
$ ansible-playbook -C test.yml -vvv
```

```yaml
  - name: create ec2 instance
    ec2_instance:
      name: test-ec2-2
      state: present
      image_id: "{{ map_ami_param.image_id }}"
      profile: wheel-base-iamrole
      instance_type: "t2.micro"
      key_name: "base_keypair"
      vpc_subnet_id: "{{ list_subnets | selectattr ('name_subnet', 'equalto', 'wheel-public-1c') | map(attribute='id_subnet') | list | first }}"
      security_group: "default"
      volumes:
        - device_name: "/dev/sda1"
          ebs:
            volume_size: 16
            delete_on_termination: true
      profile: "test"
      region: "ap-northeast-1"
    check_mode: true # Just for sure
```

##### ACTUAL RESULTS

```paste below
TASK [create ec2 instance] ******************************************************************************************************************************************************************************************task path: /home/cahlchang/git/ansible_dev_work/test.yml:40
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: cahlchang
<127.0.0.1> EXEC /bin/sh -c 'echo ~cahlchang && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869 `" && echo ansible-tmp-1538977531.9534602-129065864925869="` echo /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/cloud/amazon/ec2_instance.py
<127.0.0.1> PUT /home/cahlchang/.ansible/tmp/ansible-local-3124x71lxgex/tmp0s1jvslh TO /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869/AnsiballZ_ec2_instance.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869/ /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.6 /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/cahlchang/.ansible/tmp/ansible-tmp-1538977531.9534602-129065864925869/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "instance_ids": [
        "i-xxxxxxxxxxxxxxxxxx"
    ],
    "instances": [
        {
```

When I actually checked the AWS console, I confirmed that an EC 2 instance was made.

#### ASSUMED LOCATION AS PROBLEM

https://github.com/ansible/ansible/blob/990e95eb5775ed71a1cc2a377c0de5d726bdaf95/lib/ansible/modules/cloud/amazon/ec2_instance.py#L1515
And there is no logic to use the check mode option in this code.
