### ISSUE TITLE
jinja2 filters no longer working after templating refactor

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#4662]
Hi ansible devs,

Since the refactor to the way the template system works https://github.com/ansible/ansible/compare/0568ab...503110 several of my templates no longer work as expected.  I have isolated it to these commits, where my setup worked before the commit, it no longer works after.

My particular usage where I am experiencing this error is rather complicated so I don't have a base case to share. (I would be willing to share the offending project as a tarball if interested).

The behavior I am witnessing is that certain things like string.replace('a', b') are replacing 0 or more times, instead of regularly like they did before. Other filters like |length are returning 0 where previously they returned 1+.  

Any help or input is appreciated,
Thank you,
Thomas Omans

**Comment by mpdehaan** [comment]
So, with no example actually shared, we can't reproduce this.

Please provide an example via gist or github that can help reproduce what you are seeing, and show what you would expect to see and what you get.

There's not enough info here to understand what you are describing unfortunately.

**Comment by darkone23** [comment]
I'm still working on creating a base case but I uncovered a bit more information. 

My role has a dependency that does something like:

```
- role: app
  home: ~/foo/bar
  command: ~/bin/command -c {{ home }}/conf
```

The template says something like
`{{ command|replace('~', '$HOME') }}`

I wind up with a result of:
`$HOME/bin/command -c ~/foo/bar/conf`

The first one gets replaced, but the one in {{ home }} does not.  So somehow the replace filter is happening before the templating gets exhausted on the string.

Will continue to research and update with my findings. Hopefully I can have a base case for this behavior.  For now my workaround is to change it so that:

`command: ~/bin/command -c ~/foo/bar/conf`

This way it does the replace as a single pass and works as expected.

**Comment by darkone23** [comment]
A-ha!

```
# site.yaml
- hosts: local
  connection: local

  vars:
    foo: 'a'
    bar: '{{ foo }} a {{ foo }}'

  tasks:
    - name: get pwd
      command: pwd
      register: pwd

    - template: src=template.j2 dest={{ pwd.stdout }}/output
```

```
# template.j2
{{ bar.replace('a', 'A') }}
```

The output will be:
a A a

Prior to the refactor the output was:
A A A

**Comment by mpdehaan** [comment]
Ok, think I get it now, somebody else was saying something similar:

```
vars:
   a: foo
   b: "{{ a }}
```

And in template

{{ b | upper }}

does not return FOO

Seems like we just need to pass a flag to let Jinja2 be recursive and it's not doing that.

**Comment by mpdehaan** [comment]
working on this now BTW

**Comment by mpdehaan** [comment]
The above should fix most occurrences, let us know if this works for you.

Thanks!

**Comment by darkone23** [comment]
Hey @mpdehaan, I'm still seeing the same behavior in the example you provided (the filter happens before the substitution), maybe I could write a test case for this?

**Comment by darkone23** [comment]
Here's the base case scenario that shows the strange behavior: 

site.yaml

```
- hosts: local
  connection: local

  vars:
    foo: 'foo'
    bar: '{{ foo }}'

  tasks:
    - template: src=template.j2 dest={{ playbook_dir }}/output
```

template.j2:

```
{{ bar|upper }}
```

cat output:

```
{{FOO}}
```

This bug basically means you can't use jinja filters if you reference other vars in your vars, right?
I'll try to help however I can.

-- Thomas Omans
