### ISSUE TITLE
`when:` does not interpolate `item` from `with_items`

### ISSUE THREAD

**Issue by garethrees** [ansible/ansible#4665]
I've raised two related issues (#4634, #4614), but I think what I'm trying to achieve has clouded the problem I'm trying to address.

``` yaml
- hosts: all
  tasks:
    - name: Install conditionally
      yum: pkg={{ item }} state=installed
      with_items:
        - git
        - tree
      when: item == 'git'
```

Output:

``` sh
TASK: [Install conditionally] *************************************************
skipping: [192.168.33.11] => (item=git,tree)
```

Shouldn't each iteration of `item` be passed in to `when`, rather than the full list?
