### ISSUE TITLE
Allow lineinfile to accept a list of paths

### ISSUE THREAD

**Issue by yamada-k-ts** [ansible/ansible#46668]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`lineinfile.py`

##### ADDITIONAL INFORMATION

I am using ansible 2.7.0.
The `yum` module accepts a list of packages and does not require the use of a loop in order to install multiple packages.
```
  yum:
    name:  ['gcc', 'gcc-c++', 'git', 'openssl-devel', 'libyaml-devel', 'readline-devel', 'zlib-devel', 'curl-devel', 'expat-devel', 'gettext-devel', 'perl-ExtUtils-MakeMaker', 'mysql-devel', '@Japanese-Support', 'libffi-devel', 'libselinux-python']
``` 

The `lineinfile` module only accepts one path and needs a loop in order to operate on multiple files. It would be nice if a list of paths could be passed to the module.
```
- name: change color
  lineinfile:
    path: ['/home/ec2-user/.bashrc', '/root/.bashrc']
    line: export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
``` 

Rather than having to use a loop like this today:
```
- name: change color
  lineinfile:
    path: "{{ item }}"
    line: export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
  with_items:
    - "/home/ec2-user/.bashrc"
    - "/root/.bashrc"
```
