### ISSUE TITLE
Optionally make not matching any hosts a fatal error

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#46661]
##### SUMMARY

Add the ability to specify that a play must match at least 1 host, or the playbook should terminate with an error
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

NO_HOSTS_MATCHED_FATAL
##### ADDITIONAL INFORMATION

My first thought is this could be a play level directive.

Its needed to stop deployments being missed simply because hosts were not added to inventory (or even that no hosts were added to a group defined in inventory).

```yaml
# possibly syntax for this feature

- hosts: database
  gather_facts: false
  any_errors_fatal: true
  no_hosts_matched_fatal: true
-

So instead of a warning 'no hosts matched found', ansible-playbook would fail with a non-zero exit code.

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/inventory](https://github.com/ansible/ansible/blob/devel/lib/ansible/inventory)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/playbook](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
Suggestion from irc user flowerysong that this can be achieved in a playbook like the following.  Not yet tested in my environment but the idea would be to have something more compact:
```

- hosts: Class_mx
  tasks:
    - set_fact:
        play_1_ran: true
      delegate_to: localhost
      delegate_facts: true

- hosts: localhost
  tasks:
    - assert:
        that: play_1_ran
```
