### ISSUE TITLE
Solaris - pkg5 module - Provide a boolean switch to enable/disable publisher refresh

### ISSUE THREAD

**Issue by danowar2k** [ansible/ansible#46682]
##### SUMMARY
The pkg5 module used for Solaris installs is missing an option to disable refreshing publishers. ("--no-refresh").

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
pkg5

##### ADDITIONAL INFORMATION
 At the moment I can't update or install packages on a Solaris Vagrant box because Solaris 11.4 is released and my system wants to update to 11.4 packages. The problem is it can't update because it's an unsupported Solaris and thus doesn't get a required update that should be downloaded before migrating to Solaris 11.4.

I want to be able to prevent publisher package refresh so that I don't run into this problem.

```yaml
    - name: install mutt MTA
      become: true
      pkg5:
        name: mail/mutt
        state: present
        refresh: false
```
