### ISSUE TITLE
Issue with required parameters in rds_instance module

### ISSUE THREAD

**Issue by sergey-trukhin** [ansible/ansible#46689]
##### SUMMARY
The **rds_instance** module doesn't allow to restore a DB instance to point in time. There is the error message instead. I guess there is something wrong in this part of code:
```python
def get_parameters(client, module, parameters, method_name):
    required_options = get_boto3_client_method_parameters(client, method_name, required=True)
    if any([parameters.get(k) is None for k in required_options]):
        module.fail_json(msg='To {0} requires the parameters: {1}'.format(
            get_rds_method_attribute(method_name, module).operation_description, required_options))
    options = get_boto3_client_method_parameters(client, method_name)
    parameters = dict((k, v) for k, v in parameters.items() if k in options and v is not None)

    if parameters.get('ProcessorFeatures') is not None:
        parameters['ProcessorFeatures'] = [{'Name': k, 'Value': to_text(v)} for k, v in parameters['ProcessorFeatures'].items()]

    # If this parameter is an empty list it can only be used with modify_db_instance (as the parameter UseDefaultProcessorFeatures)
    if parameters.get('ProcessorFeatures') == [] and not method_name == 'modify_db_instance':
        parameters.pop('ProcessorFeatures')

    if method_name == 'create_db_instance' and parameters.get('Tags'):
        parameters['Tags'] = ansible_dict_to_boto3_tag_list(parameters['Tags'])
    if method_name == 'modify_db_instance':
        parameters = get_options_with_changing_values(client, module, parameters)
    if method_name == 'restore_db_instance_to_point_in_time':
        parameters['TargetDBInstanceIdentifier'] = module.params['db_instance_identifier']

    return parameters
```
Firstly this function checks if we have all the required parameters and then it adds one missing parameter '**TargetDBInstanceIdentifier**'. I think this parameter should be added to the dictionary before checking the required parameters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rds_instance

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
Default configuration (empty output of "ansible-config dump --only-changed")
```

##### OS / ENVIRONMENT

Ubuntu 16.04.4 LTS in Docker container

##### STEPS TO REPRODUCE

Run the task below

```yaml
- name: Create temporary RDS instance
  rds_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    allocated_storage: 20
    allow_major_version_upgrade: no
    apply_immediately: yes
    auto_minor_version_upgrade: no
    backup_retention_period: 1
    character_set_name: "AL32UTF8"
    copy_tags_to_snapshot: no
    creation_source: "instance"
    db_instance_class: "db.t2.micro"
    db_instance_identifier: "{{ db_instance_identifier }}"
    db_parameter_group_name: "{{ db_parameter_group_name }}"
    db_subnet_group_name: "{{ db_subnet_group_name }}"
    enable_iam_database_authentication: no
    enable_performance_insights: no
    engine: "mysql"
    engine_version: "5.7.17"
    force_failover: no
    force_update_password: no
    license_model: "general-public-license"
    master_username: "{{ master_username }}"
    master_user_password: "{{ master_user_password }}"
    multi_az: no
    port: 3306
    publicly_accessible: yes
    read_replica: no
    restore_time: "{{ restore_time }}"
    skip_final_snapshot: no
    source_db_instance_identifier: "{{ source_db_instance_identifier }}"
    state: "present"
    storage_encrypted: no
    storage_type: "gp2"
    tags:
      ClientName: "{{ client_name }}"
    vpc_security_group_ids:
      - "{{ vpc_sg_id }}"
    wait: yes
```

##### EXPECTED RESULTS

New RDS instance is created with data as of the specific point in time

##### ACTUAL RESULTS

Module failed to create new RDS instance

```paste below
fatal: [localhost]: FAILED! => changed=false 
  invocation:
    module_args:
      allocated_storage: 20
      allow_major_version_upgrade: false
      apply_immediately: true
      auto_minor_version_upgrade: false
      availability_zone: null
      aws_access_key: XXXXXXXXXXXXXXXXXXXX
      aws_secret_key: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      backup_retention_period: 1
      ca_certificate_identifier: null
      character_set_name: AL32UTF8
      copy_tags_to_snapshot: false
      creation_source: instance
      db_cluster_identifier: null
      db_instance_class: db.t2.micro
      db_instance_identifier: XXXXXX
      db_name: XXXXXX
      db_parameter_group_name: XXXXXX
      db_security_groups: null
      db_snapshot_identifier: null
      db_subnet_group_name: XXXXXX
      domain: null
      domain_iam_role_name: null
      ec2_url: null
      enable_cloudwatch_logs_exports: null
      enable_iam_database_authentication: false
      enable_performance_insights: false
      engine: mysql
      engine_version: 5.7.17
      final_db_snapshot_identifier: null
      force_failover: false
      force_update_password: false
      iops: null
      kms_key_id: null
      license_model: general-public-license
      master_user_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      master_username: XXXXXX
      monitoring_interval: null
      monitoring_role_arn: null
      multi_az: false
      new_db_instance_identifier: null
      option_group_name: null
      performance_insights_kms_key_id: null
      performance_insights_retention_period: null
      port: 3306
      preferred_backup_window: null
      preferred_maintenance_window: null
      processor_features: null
      profile: null
      promotion_tier: null
      publicly_accessible: true
      purge_cloudwatch_logs_exports: true
      purge_tags: true
      read_replica: false
      region: eu-west-1
      restore_time: '2018-10-09T11:34:54Z'
      s3_bucket_name: null
      s3_ingestion_role_arn: null
      s3_prefix: null
      security_token: null
      skip_final_snapshot: false
      snapshot_identifier: null
      source_db_instance_identifier: XXXXXX
      source_engine: null
      source_engine_version: null
      source_region: null
      state: present
      storage_encrypted: false
      storage_type: gp2
      tags:
        ClientName: XXXXXX
      tde_credential_arn: null
      tde_credential_password: null
      timezone: null
      use_latest_restorable_time: null
      validate_certs: true
      vpc_security_group_ids:
      - XXXXXX
      wait: true
  msg: 'To restore DB instance to point in time requires the parameters: [u''SourceDBInstanceIdentifier'', u''TargetDBInstanceIdentifier'']'
```
