### ISSUE TITLE
[Bug report] About the path in 'copy' module when it begins with a 'variable' without a '/' before the variable

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [ansible/ansible#46691]
Hi,

Here is a issue report about a bug in 'copy' module.

##### SUMMARY
When you use the 'copy' module, if the 'src' begins with a 'variable' (or placeholder) (without a '/' (before the variable), the root path where Ansible is looking for the file is the folder where ansible-playbook is called - and this, even if in the variable/placeholder, a '/' is in the beginning, for exmaple with '$HOME'. See steps to reproduce for examples.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
The component name is 'copy'.
More detail about this module here : https://docs.ansible.com/ansible/devel/modules/copy_module.html

##### ANSIBLE VERSION
Debian versions tested :
```
- 2.6.5+dfsg-1 900
- 2.6.3+dfsg-1~bpo9+1
- 2.2.1.0-2
```
Ubuntu versions tested :
```
- 2.7.0-1ppa~bionic
- 2.6.4-1ppa~bionic
- 2.5.1+dfsg-1
- 2.4.2.0-1ppa~zesty
```
(Wasn't working on all currently tested versions)

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -F lb_terraform/prod/ssh/config
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 2
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = lb_terraform/prod/tmp/.ansible_cache
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 10800
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/lb_terraform/prod/tmp']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_NAME(/etc/ansible/ansible.cfg) = command
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = centos
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -E -H
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /etc/ansible/lb_terraform/prod/tmp/.ansible-retry
```

##### OS / ENVIRONMENT
Client :
- Debian Jessie
- Ubuntu zesty
- Ubuntu bionic

Server :
- CentOS 7
- Debian Jessie

##### STEPS TO REPRODUCE
You can find below a code snippet with the fix secondly to show you with and without the error how it will works.

```
---
- hosts: proback01, proback02
  become: no
  become_method: sudo
  vars_files:
    - "vars/{{ target_environment }}.yml"
    - "vars/env/{{ target_environment }}.yml"
    - "vars/vault_passwords_{{ target_environment }}.yml"
  vars:
    ROOT_PATH_BACK: $HOME/tmp/back
    ROOT_PATH: $HOME/tmp
  environment: "{{ proxy_env }}"

  tasks:

  - name: Remove 'back' folder locally
    local_action:
      module: file
      state: absent
      path: "{{ ROOT_PATH_BACK }}"
    register: "result"
    failed_when: "result.stdout is defined and 'Denied' in result.stdout"
    tags:
      - transfer

  - name: Remove 'back.zip' file on the remote host
    file:
      state: absent
      path: "{{ ROOT_PATH }}/back.zip"
    become: yes
    tags:
      - transfer

  - name: Create 'back' folder locally
    local_action:
      module: file
      state: directory
      path: "{{ ROOT_PATH_BACK }}"
    register: "result"
    failed_when: "result.stdout is defined and 'Denied' in result.stdout"
    tags:
      - transfer

  # ignore_errors: true if you already have locally the files
  - name: Get updated files from git 'back' repository
    ignore_errors: true
    local_action:
      module: git
      repo: "git@url.com:project/back.git"
      depth: 250
      dest: "{{ ROOT_PATH_BACK }}"
      remote: "{{ git_remote }}"
      version: "{{ git_version }}"
      accept_hostkey: yes
    environment: "{{ proxy_env }}"
    tags:
      - transfer

  - name: Create 'back' folder locally and ensure rights
    file:
      path: "{{ ROOT_PATH_BACK }}"
      state: directory
      recurse: yes
      mode: 0755
    tags:
      - transfer

  - name: Compress locally 'back' folder
    local_action:
      module: archive
      path: "{{ ROOT_PATH_BACK }}"
      dest: "{{ ROOT_PATH }}/back.zip"
    tags:
      - transfer

  - name: Transfer the locally 'back.zip' file to remote hosts
    become: yes
    copy:
      src: "{{ ROOT_PATH }}/back.zip"
      dest: "{{ ROOT_PATH }}/back.zip"
      owner: catalina
      group: tomcat
      mode: 0755
    tags:
      - transfer
```
Is this example above, the 'src' parameter of 'copy' module will look for a file in "/home/my_user/Documents/assettracking/smt-ops/files/$HOME/tmp/back.zip", and it's bad. copy should look for a file only in "$HOME/tmp/back.zip", not this full path with "/home/my_user/Documents/assettracking/smt-ops/files/" (<= that is the root path where i execute my ansible-playbook command)
The error message will be something like : 
```
fatal: [proback01]: FAILED! => {
    "changed": false,
    "msg": "Could not find or access '$HOME/tmp/back.zip'\nSearched in:\n\t/home/my_user/Documents/assettracking/smt-ops/files/$HOME/tmp/back.zip\n\t/home/my_user/Documents/assettracking/smt-ops/$HOME/tmp/back.zip\n\t/home/my_user/Documents/assettracking/smt-ops/files/$HOME/tmp/back.zip\n\t/home/my_user/Documents/assettracking/smt-ops/$HOME/tmp/back.zip on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
```
(the last comment from the failed return message is bad since I want to copy locally the file to the remote, if i want to do remote to local i will instead use the 'fetch' module)

The "Transfer the locally 'back.zip' file to remote hosts" task will work if it's replaced by :
```
  - name: Transfer the locally 'back.zip' file to remote hosts
    become: yes
    copy:
      src: "/{{ ROOT_PATH }}/back.zip"
      dest: "/{{ ROOT_PATH }}/back.zip"
      owner: catalina
      group: tomcat
      mode: 0755
    tags:
      - transfer
```

(PS : As you can imagine, $HOME already contain a '/' at the beginning, but we need to add another '/' for copy to take this absolute path and not a strange 'root' path...)

##### EXPECTED RESULTS
The expected result is for 'copy' module to take the absolute path, instead it takes a weird path with some concatenation between 2 paths (root path when we execute ansible-playbook + the given 'src' path).
I think it's a bug because '$HOME' already contain a '/' at the beginning, but the 'src' parameter of 'copy' can't apparently see it and request an additionnal '/'.

##### ACTUAL RESULTS
Crash because the path isn't correct. (see above explanations and playbook examples to understand better)

By the way, Ansible is a great tool, and I thank you for your work on this wonderful project. :)
thank you everyone for your reading.

(EDIT : Apparently this issue affect also other modules, I tested the 'fetch' and 'template' modules and it's the same behaviour. 'file' module apparently doesn't have this issue.)
