### ISSUE TITLE
vmware_guest module: can't deploy from template using standalone ESXi

### ISSUE THREAD

**Issue by sebastienbonami** [ansible/ansible#46700]
##### SUMMARY
Looking at https://docs.ansible.com/ansible/latest/vmware/scenario_clone_template.html, it says: 
* Hardware
    * At least one standalone ESXi server or
    * vCenter Server with at least one ESXi server

I'm using a standalone ESXi server (VMware vSphere 5.5 Standard) and I can't figured out how to deploy a new VM from a template. I have this error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find a template named template001"}
```

Using this playbook:
```
---
- hosts: localhost
  tasks:
  - name: deploy new vm from template
    vmware_guest:
      hostname: "{{ esxi_hostname }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      validate_certs: False
      name: newvm001
      template: template001
      folder: /
```

Someone told me vCenter is absolutely needed to do this. Is it true and the documentation is misleading or what?

##### ISSUE TYPE
- Documentation Report / Bug Report ?

##### COMPONENT NAME
- vmware_guest module

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
