### ISSUE TITLE
Not sure I understand why win_mapped_drive fails?

### ISSUE THREAD

**Issue by srjennings** [ansible/ansible#46713]
##### SUMMARY
I am unable to utilize win_mapped_drive for Azure Files. 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_mapped_drive

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Targeting Windows 2016 Datacenter

##### STEPS TO REPRODUCE

```yaml
- name: Azure VM | Ensure azurefilesuser user exists
  win_user:
    name: azurefilesuser
    password: "{{ azure_files_key }}"
    state: present
    groups:
      - Administrators

- name: Azure VM | Ensure LSA Linked Connections is in registry
# Source: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee844140(v=ws.10)#resolution
# This is mentioned as a solution using the Azure Files Troubleshooter (https://support.microsoft.com/help/4022301/troubleshooter-for-azure-files-shares)
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLinkedConnections
    data: 1
    type: dword
  register: lsalinkedconnections

- name: Azure VM | Reboot machine to enable LSA Linked Connections
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 120
  when: lsalinkedconnections.changed
  register: lsalinked_reboot

- name: Azure VM | Run Mapped Drive Command
  #when: lsalinked_reboot.changed
  win_shell: net use "Z:" "\\azurefilesuser.file.core.windows.net\webfiles" /USER:AZURE\azurefilesuser "secret-here" /PERSISTENT:YES
  register: mappeddrive
  become: yes
  become_method: runas
  become_user: azurefilesuser

- name: Azure VM | Reboot machine after mapping drive
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 120
  when: lsalinkedconnections.changed
  register: lsalinked_reboot

# Because we are trying anything to get this to work; both win_mapped_drive and win_shell exist in the playbook
- name: Azure VM | Map the Azure Files Drive
  win_mapped_drive:
    path: \\azurefilesuser.file.core.windows.net\webfiles\
    letter: Z
    state: present
    username: AZURE\azurefilesuser
    password: "{{ azure_files_key }}"
  become: yes
  become_method: runas
  become_user: azurefilesuser
  # have also attempted:
  # edit: this isn't  a valid task directive, need to set the variable ansible_become_pass under vars:
  become_password: "{{ azure_files_key }}"
```

##### EXPECTED RESULTS

Expectation is that win_mapped_drive actually maps the drive. 

##### ACTUAL RESULTS

```win_mapped_drive``` fails with: The network path was not found (Error 53).
```win_shell``` runs the command successfully but still doesn't appear in Explorer.

I've spent some time trying to understand this. But as far as 
 https://github.com/ansible/ansible/issues/33929 goes, this should work as I am bypassing WinRM restrictions and instead utilizing the ```become``` keywords to interactively map the drive. I am looking to actually have this drive mapped interactively, so that if I need to reach the drive via RDP Console, I can.

If I run the ```net use``` command manually, I run into no errors and the drive maps. I see that the ```win_mapped_drive``` module utilizes New-PSDrive as the command to run. So I've attempted that manually and it works:

```powershell
New-PSDrive -Name "Z" -PSProvider FileSystem -Root "\\azurefilesuser.file.core.windows.net\webfi
les" -Persist -Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential

Name           Used (GB)     Free (GB) Provider      Root                                               CurrentLocation
----           ---------     --------- --------      ----                                               ---------------
Z                   0.00       5120.00 FileSystem    \\azurefilesuser.file.core.windo...
```

We want the mapped drive to appear when logging into the VM via RDP.
I've attempted the [Azure Files Troubleshooter](https://support.microsoft.com/help/4022301/troubleshooter-for-azure-files-shares) and I have no issues.
Mapping the drive while actually logged in via RDP works fine.

```paste below
TASK [azure-iis : Azure VM | Ensure azurefilesuser user exists] ************************************************************ok: [vm1] => {"account_disabled": false, "account_locked": false, "changed": false, "description": "", "fullname": "azurefilesuser", "groups": [{"name": "Administrators", "path": "WinNT://WORKGROUP/vm1webvm/Administrators"}], "name": "azurefilesuser", "password_expired": false, "password_never_expires": false, "path": "WinNT://WORKGROUP/vm1webvm/azurefilesuser", "sid":
"S-1-5-21-2397622110-637681870-2144294262-1000", "state": "present", "user_cannot_change_password": false}
ok: [vm2] => {"account_disabled": false, "account_locked": false, "changed": false, "description": "", "fullname": "azurefilesuser", "groups": [{"name": "Administrators", "path": "WinNT://WORKGROUP/vm2webvm/Administrators"}], "name": "azurefilesuser", "password_expired": false, "password_never_expires": false, "path": "WinNT://WORKGROUP/vm2webvm/azurefilesuser", "sid":
"S-1-5-21-2262328796-3896354487-97647278-1000", "state": "present", "user_cannot_change_password": false}

TASK [azure-iis : Azure VM | Ensure LSA Linked Connections is in registry] *************************************************ok: [vm1] => {"changed": false, "data_changed": false, "data_type_changed": false}
ok: [vm2] => {"changed": false, "data_changed": false, "data_type_changed": false}

TASK [azure-iis : Azure VM | Reboot machine to enable LSA Linked Connections] **********************************************skipping: [vm1] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [vm2] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [azure-iis : Azure VM | Run Mapped Drive Command] *********************************************************************changed: [vm1] => {"changed": true, "cmd": "net use \"Z:\" \"\\\\azurefilesuser.file.core.windows.net\\webfiles\" /USER:AZURE\\azurefilesuser \"secret-here" /PERSISTENT:YES", "delta": "0:00:00.516545", "end": "2018-10-09 06:55:12.485306", "rc": 0, "start": "2018-10-09 06:55:11.968760", "stderr": "", "stderr_lines": [], "stdout": "The command completed successfully.\r\n\r\n", "stdout_lines": ["The command completed
successfully.", ""]}
changed: [vm2] => {"changed": true, "cmd": "net use \"Z:\" \"\\\\azurefilesuser.file.core.windows.net\\webfiles\" /USER:AZURE\\azurefilesuser \"secret-here" /PERSISTENT:YES", "delta": "0:00:02.920363", "end": "2018-10-09 06:55:15.020939", "rc": 0, "start": "2018-10-09 06:55:12.100576", "stderr": "", "stderr_lines": [], "stdout": "The command completed successfully.\r\n\r\n", "stdout_lines": ["The command completed
successfully.", ""]}

TASK [azure-iis : Azure VM | Reboot machine after supposedly mapping drive] ***********************************************************skipping: [vm1] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [vm2] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [azure-iis : Azure VM | Map the Azure Files Drive] ********************************************************************fatal: [vm1]: FAILED! => {"changed": false, "module_stderr": "\r\n", "module_stdout": "Z: was deleted successfully.  {\"changed\":true,\"msg\":\"failed to create mapped drive Z pointed to \\\\\\\\azurefilesuser.file.core.windows.net\\\\webfiles\\\\: The network path was not found\",\"failed\":true}\r\n", "msg": "MODULE FAILURE", "rc": 1}
fatal: [vm2]: FAILED! => {"changed": false, "module_stderr": "\r\n", "module_stdout": "Z: was deleted successfully.  {\"changed\":true,\"msg\":\"failed to create mapped drive Z pointed to \\\\\\\\azurefilesuser.file.core.windows.net\\\\webfiles\\\\: The network path was not found\",\"failed\":true}\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by jborean93** [comment]
Try without become, I found that become messes something even more up. I've seen a few reports of this not working recently so I'm planning on looking into the implementation and trying something different to see how it goes.

**Comment by ansibot** [comment]
@deyjcode: thank you for submitting this issue!

cc @dagwieers @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aurorawillow** [comment]
@jborean93 Thanks for the reply. Looks like it doesn't work either. I've tried without ``become`` (commenting out all ```become``` references, ```become_method``` et al.) and run into the same issue: 
```The network path was not found```

**Comment by dagwieers** [comment]
@deyjcode Did you use CredSSP or Kerberos for WinRM/PSRP authentication ? I think it is required in this case because of Credential Delegation: https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#authentication-options

You can also try to log on directly as the user you want to run this as:
```yaml
- name: Azure VM | Map the Azure Files Drive
  win_mapped_drive:
    path: \\azurefilesuser.file.core.windows.net\webfiles\
    letter: Z
  vars:
    ansible_user: AZURE\azurefilesuser
    ansible_password: "{{ azure_files_key }}"
```

This will add the mapped drive for user **AZURE\azurefilesuser** which I assume is what you wanted (since you were using **become**).
