### ISSUE TITLE
loop jinja2 expression is still evaluated inside a skipped block

### ISSUE THREAD

**Issue by plasticrake** [ansible/ansible#46718]
##### SUMMARY

The `loop` jinja2 template is being evaluated inside a block that should be skipped via a `when`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

block, loop

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  python version = 3.7.0 (default, Oct  2 2018, 09:18:58) [Clang 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/patrick/.ansible.cfg) = ['/Users/patrick/.ansible_hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/patrick/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/patrick/.ansible.cfg) = yaml
```

##### STEPS TO REPRODUCE

```yaml
- name: Loop Issue
  hosts: all
  gather_facts: no

  vars:
    storage:
      mykeys:

  tasks:
    - name: block with issue
      when: "'mykeys' in storage and storage.mykeys is mapping"
      block:
        - debug:
            var: item
          loop: "{{ storage.mykeys | dict2items }}"

    - name: block with workaround
      when: "'mykeys' in storage and storage.mykeys is mapping"
      block:
        - set_fact:
            storage_keys: "{{ storage.mykeys | dict2items }}"
        - debug:
            var: item
          loop: "{{ storage_keys }}"
```

My workaround is using a `set_fact` works as expected.

##### EXPECTED RESULTS

The block to be skipped without evaluating the `loop`

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! =>
  msg: dict2items requires a dictionary, got <class 'NoneType'> instead.
```
