### ISSUE TITLE
ec2_instance shows changed when desired state is stopped, instance is already stopped, and filters is defined

### ISSUE THREAD

**Issue by briantist** [ansible/ansible#46710]
##### SUMMARY
If all of the following conditions are true:

- The desired state of the instance is `stopped`
- The instance in question is already stopped
- The module is called with a `filters` defined 

then, the module will be `changed` as if it had changed the state of the instance (but it has not).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_instance

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
```

##### STEPS TO REPRODUCE

```yaml
  - name: "Ensure instances are launched and in the desired state"
    ec2_instance:
      state: "stopped"
      wait: yes
      wait_timeout: 500
      filters:        
        "instance-state-name":
          - "stopped"
   delegate_to: localhost
```

##### EXPECTED RESULTS

The module is `OK` because the instance is already in the desired state.

##### ACTUAL RESULTS

No changes are made to the instance, but the module is `Changed`.
