### ISSUE TITLE
Yum module not working 

### ISSUE THREAD

**Issue by Nithesh-b** [ansible/ansible#46726]
##### SUMMARY

Yum module is not working on some servers. Manual update of yum works. The servers are hosted in EC2. Verified the same configuration files redhat-rhui.repo,redhat-rhui-client-config.repo are being used with that of a working instance. Proxy is disabled as well. I am trying to disable the Redhat satellite server configuration and enable AWS provided RHUI update. The last play in the playbook fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Yum

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL 7.3 is the client

##### STEPS TO REPRODUCE

```
- hosts: all
  remote_user: evadmin
  become: yes
  become_method: sudo
  tasks:

    - name: Move repos from backup to yum.repos.d
      shell: mv -f /backup/* /etc/yum.repos.d/
      register: shell_result
      failed_when: '"No such file or directory" in shell_result.stderr_lines'

    - name: "Set proxy environment variables"
      set_fact:
        environment_vars:
          no_proxy: "**.**.**.**"

    - name: UnRegister with activationkey matching Red Hat Enterprise Server Version 7
      redhat_subscription:
        state: absent
        org_id: ******
        activationkey: *****

    - name: Remove redhat.repo
      shell: rm -f /etc/yum.repos.d/redhat.repo
      register: shell_result
      failed_when: '"No such file or directory" in shell_result.stderr_lines'

    - name: add line to yum.conf
      lineinfile:
        dest: /etc/yum.conf
        line: exclude=kernel* redhat-release*
        state: present
        create: yes

    - name: yum clean
      shell: yum make-cache
      register: shell_result
      failed_when: '"There are no enabled repos" in shell_result.stderr_lines'

    - name: install all security patches
      yum:
       name: '*'
       state: latest
       security: yes
       skip_broken: yes
       enablerepo: redhat-rhui.repo,redhat-rhui-client-config.repo

```

##### EXPECTED RESULTS

Yum update should have been completed succeessfully

##### ACTUAL RESULTS

```paste below
fatal: [172.29.146.159]: FAILED! => {"changed": true, "cmd": "yum update --security -y", "delta": "0:01:02.339320", "end": "2018-10-09 23:50:50.088292", "msg": "non-zero return code", "rc": 1, "start": "2018-10-09 23:49:47.748972", "stderr": "\n\nCould not contact any CDS load balancers: rhui2-cds01.us-east-1.aws.ce.redhat.com, rhui2-cds02.us-east-1.aws.ce.redhat.com.", "stderr_lines": ["", "", "Could not contact any CDS load balancers: rhui2-cds01.us-east-1.aws.ce.redhat.com, rhui2-cds02.us-east-1.aws.ce.redhat.com."], "stdout": "Loaded plugins: amazon-id, rhui-lb, search-disabled-repos\nCould not contact CDS load balancer rhui2-cds01.us-east-1.aws.ce.redhat.com, trying others.", "stdout_lines": ["Loaded plugins: amazon-id, rhui-lb, search-disabled-repos", "Could not contact CDS load balancer rhui2-cds01.us-east-1.aws.ce.redhat.com, trying others."]}

```
