### ISSUE TITLE
vmware_guest: DHCP hostname in vm customization

### ISSUE THREAD

**Issue by ralphie02** [ansible/ansible#46722]
##### SUMMARY

I am currently trying to utilize vmware_guest module in order to create a vm from a template. This is working perfectly fine except for one caveat, the dhcp client hostname is not set. I was under the impression that `hostname` under customization would set this but it doesn't. Am I correct to assume that this is not supported? If this is more of a bug or feature request, please let me know. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

module: vmware_guest 

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /home/ralphie02/.ansible.cfg
  configured module search path = [u'/home/ralphie02/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ralphie02/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1800s
ANSIBLE_SSH_CONTROL_PATH(/home/ralphie02/.ansible.cfg) = /tmp/ansible-ssh-%%h:%%p-%%r
DEFAULT_CALLBACK_WHITELIST(/home/ralphie02/.ansible.cfg) = [u'profile_tasks', u'log_plays_capture', u'actionable', u'skippy', u'task_timer', u'vers
DEFAULT_HASH_BEHAVIOUR(/home/ralphie02/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/staging']
DEFAULT_REMOTE_USER(/home/ralphie02/.ansible.cfg) = ralph_azucena
DEFAULT_ROLES_PATH(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/roles']
DEFAULT_TIMEOUT(/home/ralphie02/.ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/ralphie02/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Control Machine: Debian 9 Stretch
VMware vCenter Server: version 6.0.0 Build 36334793

##### ADDITIONAL INFORMATION

To elaborate on my issue, I am running the playbook below:
```
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: vcenter2
      username: razucena
      password: "{{ user_password }}"
      datacenter: datacenter
      esxi_hostname: vh.lighthouse.ad
      validate_certs: no
      folder: TeamVM/BambooVMs
      name: test
      state: poweredon
      template: test_centos5
      disk:
      - size_gb: 20
        type: thin
        datastore: datastore_vh18
      hardware:
        memory_mb: 2048
        memory_reservation_lock: True
        num_cpus: 2
        num_cpu_cores_per_socket: 1
      networks:
      - name: lighthouse.ad 10.3
        device_type: e1000
        type: dhcp
      wait_for_ip_address: yes
      guest_id: centos64Guest
      customization:
        hostname: test
        domain: lighthouse.ad
```
I expected `/etc/sysconfig/network` to be updated with
```
DHCP_HOSTNAME=hostname-from-customization
```
I expected this because using vmware powercli, `new-vm` tends to set this value for Centos 5 (from my understanding..). I might be wrong though
I hope someone can shed some light on this. 
Thanks!
