### ISSUE TITLE
using  "ec2_asg" and doing a rolling restart with "replace_all_instances" does not add new servers to target group

### ISSUE THREAD

**Issue by biohazd** [ansible/ansible#46757]
##### SUMMARY
Using the module "ec2_asg" and doing a rolling restart with "replace_all_instances". I am also using an NLB which has the servers in the target group. 
Its spinning up a new server and terminating old one. It removes them from the target group, but does not add the new servers to the target group. Should it add the new ones to the target group?

It is also terminating an old instance before the new instance has completed its "initializing" status in the console.

The playbook I'm using:
```
- name: find the group
  ec2_asg_facts:
    name: "{{ None | tagname(environ.key, HostsGroup, environ.region) }}"
  register: asg_maybe

- name: change launch config and do a rolling restart of servers
  ec2_asg:
    name: "{{ asg_maybe.results[0].auto_scaling_group_name }}"
    launch_config_name: "{{ asg_maybe.results[0].launch_config_name }}"
    min_size: "{{ asg_maybe.results[0].min_size | int }}"
    max_size: "{{ asg_maybe.results[0].max_size | int }}"
    desired_capacity: "{{ asg_maybe.results[0].desired_capacity | int }}"
    replace_all_instances: yes
    target_group_arns: "{{ asg_maybe.results[0].target_group_arns | default([]) }}"
    replace_batch_size: 1
    health_check_type: ELB
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION
```ansible 2.5.5
  config file = /home/username/git/ansible25/ansible.cfg
  configured module search path = [u'/home/username/git/ansible25/library', u'/usr/local/ansible25/local/lib/python2.7/site-packages/ara/plugins/modules']
  ansible python module location = /usr/local/ansible25/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/ansible25/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/username/git/ansible25/ansible.cfg) = True
CACHE_PLUGIN(/home/username/git/ansible25/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(env: ANSIBLE_ACTION_PLUGINS) = [u'/usr/share/ansible_plugins/action_plugins', u'/usr/local/ansible25/local/lib/python2.7/site-packages/ara/plugins/act
DEFAULT_ASK_VAULT_PASS(/home/username/git/ansible25/ansible.cfg) = True
DEFAULT_CACHE_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible/plugins/cache']
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = [u'/usr/share/ansible_plugins/callback_plugins', u'/usr/local/ansible25/local/lib/python2.7/site-packages/ara/plugi
DEFAULT_CONNECTION_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/home/username/git/ansible25/filter_plugins']
DEFAULT_FORKS(/home/username/git/ansible25/ansible.cfg) = 15
DEFAULT_GATHERING(/home/username/git/ansible25/ansible.cfg) = smart 
DEFAULT_HASH_BEHAVIOUR(/home/username/git/ansible25/ansible.cfg) = merge 
DEFAULT_HOST_LIST(/home/username/git/ansible25/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(/home/username/git/ansible25/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOOKUP_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/home/username/git/ansible25/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/username/git/ansible25/library', u'/usr/local/ansible25/local/lib/python2.7/site-packages/ara/plugins/modules']
DEFAULT_POLL_INTERVAL(/home/username/git/ansible25/ansible.cfg) = 15
DEFAULT_PRIVATE_KEY_FILE(/home/username/git/ansible25/ansible.cfg) = /usr/local/ansible25/id_rsa
DEFAULT_REMOTE_USER(/home/username/git/ansible25/ansible.cfg) = ec2-user
DEFAULT_ROLES_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/home/username/git/ansible25/roles']
DEFAULT_SCP_IF_SSH(/home/username/git/ansible25/ansible.cfg) = True
DEFAULT_STRATEGY_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible/plugins/strategy']
DEFAULT_TEST_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible/plugins/test']
DEFAULT_TIMEOUT(/home/username/git/ansible25/ansible.cfg) = 10
DEFAULT_TRANSPORT(/home/username/git/ansible25/ansible.cfg) = smart 
DEFAULT_VARS_PLUGIN_PATH(/home/username/git/ansible25/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
DISPLAY_SKIPPED_HOSTS(/home/username/git/ansible25/ansible.cfg) = False 
HOST_KEY_CHECKING(/home/username/git/ansible25/ansible.cfg) = False 
RETRY_FILES_ENABLED(/home/username/git/ansible25/ansible.cfg) = False 

```

##### OS / ENVIRONMENT
Amazon Linux 1 (CentOS 6)

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
