### ISSUE TITLE
ansible fails if target host does not have simplejson

### ISSUE THREAD

**Issue by cg-soft** [ansible/ansible#4675]
<pre>
GATHERING FACTS *************************************************************** 
failed: [172.16.143.129] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1382725603.42-55777648167588/setup", line 98, in ?
    import simplejson as json
ImportError: No module named simplejson
</pre>

It might be nice for that case to have a simplistic eval based json included in the remote script. Arguably, some minimum requirements for the target system must exist, and maybe it is enough to clearly document that "python 2.4 with simplejson" is that minimum requirment.

**Comment by srgvg** [comment]
As for documentation, that is mentioned on http://www.ansibleworks.com/docs/intro_installation.html#managed-node-requirements

**Comment by cg-soft** [comment]
The documentation mentions I can use the "raw" module to install
python-simplejson, but that doesn't work since simplejson is required at
the fact gathering stage... I guess I need to find out how to defer the
fact gathering...

**Comment by darkone23** [comment]
@cg-soft use ansible 'raw' directly.

like so:
`ansible all -i my-inventory.ini -U root -u ssh-user --ask-pass --ask-sudo-pass -m raw -a 'yum install python-simplejson -y'`

**Comment by jctanner** [comment]
http://www.ansibleworks.com/docs/glossary.html#gather-facts-boolean

```
- hosts: all
  gather_facts: False
  tasks:
      - name: <pkginstallcommand>
```

Please move this discussion to the mailing list.

**Comment by cg-soft** [comment]
Still not very pretty. The whole point of having a playbook is to have a one stop shop to configure my cluster. If I now have to do two separate steps...

**Comment by jctanner** [comment]
Playbooks can contain multiple plays:

```
- hosts: all
  gather_facts: False
  tasks:
     - name: nofact task1

- hosts: all
  gather_facts: True
  tasks:
     - name: facts task1
```
