### ISSUE TITLE
Incorrect work of openssl_privatekey module

### ISSUE THREAD

**Issue by Aeris126** [ansible/ansible#46758]
##### SUMMARY

I tried to automate creating ssl-certificates in my environment with mariadb master-slave configuration and found that openssl_privatekey module isn't creating RSA certificates therefore mariadb replication isn't working.
Actually exact certificate maybe RSA-type but the header is like this - 
-----BEGIN PRIVATE KEY-----
and that is unsupported by mariadb it says that
Last_IO_Error: error connecting to master 'replica@10.10.11.2:3306' - retry-time: 60  maximum-retries: 86400  message: SSL connection error: Unable to get private key
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssl_privatekey
##### ANSIBLE VERSION

```paste below
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/aeris/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = aeris
```

##### OS / ENVIRONMENT

Virtual machines with 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
##### STEPS TO REPRODUCE

two servers with Ubuntu 18.04, mariadb-server-10.1, master-slave replication with ssl between them
on first server (master of mariadb) I configured ansible-master that is going to slave and creates ssl-certificates

```yaml
---
- name: Packages for SSL
  hosts: localvms
  remote_user: ***
  become: true

  tasks:
  - name: Install list of packages
    apt: name={{item}} state=present
    with_items:
         - libffi-dev
         - python-pip
  - name: Install cryptography packahe through pip
    pip: name={{item}} state=present
    with_items:
         - cryptography
         - pyopenssl

  - name: Just ping
    ping:

  - name: Generate CSR
    openssl_csr:
      path: /etc/mysql/ssl/ansible-req.pem
      privatekey_path: /etc/mysql/ssl/ca-key.pem

  - name: Generate Private Key for Server
    openssl_privatekey:
      path: /etc/mysql/ssl/server-key.pem

  - name: Generate a Self Signed OpenSSL certificate for Server
    openssl_certificate:
      path: /etc/mysql/ssl/server-cert.pem
      privatekey_path: /etc/mysql/ssl/ca-key.pem
      csr_path: /etc/mysql/ssl/ansible-req.pem
      provider: selfsigned

```

##### EXPECTED RESULTS

That mariadb will work with this certificates generated by ansible's module correctly

##### ACTUAL RESULTS

see above

```paste below

```
