### ISSUE TITLE
synchronize module doesn't work with ansible sudo user

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#4676]
When you use the new synchronize module with a sudo user it syncs to the ssh user instead of the sudo user.

```
tasks:
  - name: sync
    sudo: yes
    sudo_user: sudo_user
    synchronize: src=foo/ dest=~/bar/
```

Instead of syncing to /home/sudo_user/bar it syncs to /home/ssh_user/bar
