### ISSUE TITLE
Reboot failed after Yum upgrade

### ISSUE THREAD

**Issue by dbsrv** [ansible/ansible#46788]
##### SUMMARY

Reboot module failed after Yum module used to upgrade all packages.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

reboot

##### ANSIBLE VERSION

```paste below
ansible 2.7.0b1
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/home/dbsrv/mongopatch/ansible.cfg) = /home/holee/mongopatch/ansible.log
HOST_KEY_CHECKING(/home/dbsrv/mongopatch/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/dbsrv/mongopatch/ansible.cfg) = False
```

##### OS / ENVIRONMENT

before yum upgrade:
CentOS Linux release 7.3.1611 (Core)
after yum upgrade:
CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: Perform yum upgrade
  yum: name="*" state=latest
- name: Reboot
  reboot:
  register: reboot_result
- debug:
    msg: rebooted? {{ reboot_result.rebooted }}; reboot took {{ reboot_result.elapsed }} seconds
```

##### EXPECTED RESULTS

Reboot completed

##### ACTUAL RESULTS

```
fatal: [host1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to host1 closed.\r\n", "unreachable": true}
```

```paste below

```
