### ISSUE TITLE
An exception occurred during task execution. 

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#46787]
##### SUMMARY

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 497
failed: [PC175] (item=[[u'bluescreenview', u'cleanup', u'firefox', u'git', u'googlechrome', u'veeam-agent', u'virtualclonedrive', u'winscp']]) => {"changed": false, "item": [["syspro7-client", "syspro7-reporting-components"], ["bluescreenview", "cleanup", "firefox", "git", "googlechrome", "veeam-agent", "virtualclonedrive", "winscp"]], "msg": "Unhandled exception while executing module: Cannot process argument transformation on parameter 'name'. Cannot convert value to type System.String."}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.0.dev0 (devel d3cc2f803a) last updated 2018/10/10 16:38:50 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT

Management host macOS 10.12.6
Managed host Windows 10

##### STEPS TO REPRODUCE

```yaml
var:
  chocolatey_packages:
    - bluescreenview
    - cleanup
    - firefox
    - git
    - googlechrome
    - veeam-agent
    - virtualclonedrive
    - winscp
```
```
- name: Install programs (choco)
  win_chocolatey:
    name: "{{ item }}"
    state: "present"
  when:
    - chocolatey_packages is defined
  loop:  "{{ chocolatey_packages|list }}"
```

##### EXPECTED RESULTS

Packages identified in chocolatey_packages would be installed.

##### ACTUAL RESULTS

```paste below
TASK [win_chocolatey : Install programs (choco)] *******************************
ok: [PC175] => (item=[u'bluescreenview', u'cleanup', u'firefox', u'git', u'googlechrome', u'veeam-agent', u'virtualclonedrive', u'winscp'])
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 497
failed: [PC175] (item=[[u'bluescreenview', u'cleanup', u'firefox', u'git', u'googlechrome', u'veeam-agent', u'virtualclonedrive', u'winscp']]) => {"changed": false, "item": [["bluescreenview", "cleanup", "firefox", "git", "googlechrome", "veeam-agent", "virtualclonedrive", "winscp"]], "msg": "Unhandled exception while executing module: Cannot process argument transformation on parameter 'name'. Cannot convert value to type System.String."}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_chocolatey.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_chocolatey.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
This issue is due to `{{ item }}` being a list of lists and then that being used in a place where it only expects strings. The only way I can replicate this is by having

```
---
- hosts: vagrant-windows
  gather_facts: no

  tasks:
  - win_chocolatey:
      name:
      -
        - chocolatey
        - vim
      state: present
```

It seems like either `chocolatey_packages` is being merged with another list or something happening in the transformation before the value is sent to the Windows host that causes it to contain multiple list values, the module outpuit for item even shows this as being a list within a list `{"changed": false, "item": [["bluescreenview", "cleanup", "firefox", "git", "googlechrome", "veeam-agent", "virtualclonedrive", "winscp"]]`.

You will have to track this down yourself and figure out why this value is like that. I'm going to close this issue as it's not a problem with Chocolatey itself.
