### ISSUE TITLE
mongodb_user fails when given a roles list of dicts

### ISSUE THREAD

**Issue by overhacked** [ansible/ansible#46791]
##### SUMMARY
When the `mongodb_user` module gets multiple, database-scoped roles specified as a list of dicts (see steps to reproduce), the module fails with the error:
```
Unable to add or update user: '<' not supported between instances of 'dict' and 'dict'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_user

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /Users/user/Dev/ansible-site/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ansible
  executable location = /opt/local/Library/Frameworks/Python.framework/Versions/3.6/bin/ansible
  python version = 3.6.6 (default, Jun 28 2018, 05:43:53) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```
DEFAULT_GATHERING(/Users/user/Dev/ansible-site/ansible.cfg) = smart
```

##### OS / ENVIRONMENT

Controller:
* MacOS 10.13.6
* Python 3.6.6

Target:
* FreeBSD 11.2-RELEASE
* Python 3.6.6
* MongoDB 3.4.16
* pyMongo 3.7.1

##### STEPS TO REPRODUCE
Run the `mongodb_user` module, specify more than one database-scoped role, and set the `update_password` parameter to `on_create`.

```yaml
- hosts: all
  tasks:
    mongodb_user:
      login_host: "mongo.example.com"
      login_database: admin
      login_user: admin
      login_password: "adminPassword"
      database: ansibleIssue
      name: ansibleIssueUser
      password: "ansibleIssuePassword"
      update_password: on_create
      roles:
        - { db: 'ansibleIssue', role: 'dbAdmin' }
        - { db: 'ansibleIssue', role: 'readWrite' }
```

##### EXPECTED RESULTS

```
TASK [mongodb_user] ***************************************************************************************************
changed: [target] => {"changed": true, "user": "ansibleIssueUser"}
```

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_473nuddf/ansible_module_mongodb_user.py", line 416, in main
    if not check_if_roles_changed(uinfo, roles, db_name):
  File "/tmp/ansible_473nuddf/ansible_module_mongodb_user.py", line 322, in check_if_roles_changed
    if sorted(roles_as_list_of_dict) == sorted(uinfo_roles):
TypeError: '<' not supported between instances of 'dict' and 'dict'

fatal: [target]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "database": "ansibleIssue",
            "login_database": "admin",
            "login_host": "mongo.example.com",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": "27017",
            "login_user": "admin",
            "name": "ansibleIssueUser",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "replica_set": null,
            "roles": [
                {
                    "db": "ansibleIssue",
                    "role": "dbAdmin"
                },
                {
                    "db": "ansibleIssue",
                    "role": "dbAdmin"
                }
            ],
            "ssl": false,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "state": "present",
            "update_password": "on_create"
        }
    },
    "msg": "Unable to add or update user: '<' not supported between instances of 'dict' and 'dict'"
}
        to retry, use: --limit @/Users/overhack/Dev/ansible-site/test_mongodb_user.retry
```
