### ISSUE TITLE
Ansible tower_group module is not idempotent

### ISSUE THREAD

**Issue by justjais** [ansible/ansible#46803]
##### SUMMARY

Ansible tower_group module is not idempotent, as it shows as changed as True every time the module runs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_group

##### ANSIBLE VERSION

```paste below
2.8.dev0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macos

##### STEPS TO REPRODUCE

On running the below playbook, tower_group modules shows changed=True every time the respective playbook runs.

```yaml
- hosts: localhost
  tasks:
    - name: Add group to test_inventory
      tower_group:
        name: iosxr
        description: "test iosxr_group"
        inventory: test_inventory
        variables: "ansible_network_os: iosxr"
        state: present
        tower_config_file: "~/Sumit/tower_cli.cfg"

```

##### EXPECTED RESULTS

On running the same play for the second time, module should be idempotent and should report **changed=False** if there is no change in play.

##### ACTUAL RESULTS

On running the same play for the second time, module is not idempotent and reports **changed=True**, even if there is no change in play.

```paste below

```
