### ISSUE TITLE
Ansible does not process set_fact correctly if var set in one expression is in another expression in the same set_fact

### ISSUE THREAD

**Issue by flybd5** [ansible/ansible#46802]
##### SUMMARY
Ansible does not process set_fact correctly if var set in one expression is in another expression in the same set_fact

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Basic playbook execution

##### ANSIBLE VERSION

```paste below
ansible 2.6.5
  config file = None
  configured module search path = [u'/Users/ext.juan.jimenez/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.5/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Sep 18 2018, 20:16:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OSX 10.14

##### STEPS TO REPRODUCE

1. Create a playbook.yml with example content.
2. Run playbook

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Test
      set_fact:
        var1: 'foo'
        var2: '"{{ var1 }}" not in "bar"'
```

##### EXPECTED RESULTS

No errors.

##### ACTUAL RESULTS

Error states var1 is undefined.

```paste below
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'var1' is undefined\n\nThe error appears to have been in '/Users/ext.juan.jimenez/flaconi/aws-lambda-es-cleanup/playbook2.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Test\n      ^ here\n"
}
}
```
