### ISSUE TITLE
Could not find imported module support code for nxos_command.  Looked for either *.py or shell.py

### ISSUE THREAD

**Issue by ro8harp** [ansible/ansible#46810]
##### SUMMARY

Upgraded Ansible from 2.4 to 2.5.5 and not NXOS playbooks no longer work. I see the connection: local has been deprecated and to use network_cli. Ive also tested this on Ansible 2.6.1 with same issue. It may be that I have something not set up right so it may not be a bug. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos

##### ANSIBLE VERSION

```paste below
ansible 2.6.1
  config file = /Users/testuser/.ansible.cfg
  configured module search path = [u'/Users/testuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/rharp/.ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_TIMEOUT(/Users/rharp/.ansible.cfg) = 60
HOST_KEY_CHECKING(/Users/rharp/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Nexus 7018 version 6.2(20) CLI

##### STEPS TO REPRODUCE

Create Ansible playbook listed below. Run playbook with username and password parameters.
testuser@OSX:/etc/ansible$ cat hosts
[nxos]
nxos-core-1 ansible_host=10.10.10.10

[nxos:vars]
ansible_network_os=nxos

```yaml
---

#NXOS Gathering Admin Local Users
- hosts: nxos-core-1
  connection: network_cli
  gather_facts: no

  tasks:

    - name: Importing Secret Variables
      include_vars: secrets.yml

    - name: NXOS Show Admin Local Users
      register: NXOSShowAdminLocalUsers
      nxos_command:
        commands:
          - "sh run | inc username"

    - debug: msg={{NXOSShowAdminLocalUsers.stdout_lines}}

    - name: NXOS Storing Admin Local Users
      copy:
        content: "{{ NXOSShowAdminLocalUsers.stdout[0] }}"
        dest: "/etc/ansible/configs/users/nxos-admin-local-users.cfg"
```

##### EXPECTED RESULTS

I would expect to see output of the usernames.

##### ACTUAL RESULTS

testuser@OSX:/etc/ansible$ sudo ansible-playbook nxos-test.yml -vvvv -u test_user -k
ansible-playbook 2.6.1
  config file = /Users/testuser/.ansible.cfg
  configured module search path = [u'/Users/testuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
Using /Users/testuser/.ansible.cfg as config file
SSH password:
setting up inventory plugins
Set default localhost to localhost
Parsed /etc/ansible/hosts inventory source with ini plugin

Loading callback plugin default of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: nxos-test.yml ****************************************************************************************************************
1 plays in nxos-test.yml

PLAY [nxos-core-1] *********************************************************************************************************
META: ran handlers

TASK [Importing Secret Variables] ******************************************************************************************************
task path: /private/etc/ansible/nxos-test.yml:10
<10.10.10.10> attempting to start connection
<10.10.10.10> using connection plugin network_cli
<10.10.10.10> local domain socket does not exist, starting it
<10.10.10.10> control socket path is /Users/testuser/.ansible/pc/baf5c39e3d
<10.10.10.10> <10.10.10.10> ESTABLISH CONNECTION FOR USER: test_user on PORT 22 TO 10.10.10.10
<10.10.10.10> <10.10.10.10> ssh connection done, setting terminal
<10.10.10.10> <10.10.10.10> loaded terminal plugin for network_os nxos
<10.10.10.10> <10.10.10.10> loaded cliconf plugin for network_os nxos
<10.10.10.10> <10.10.10.10> firing event: on_open_shell()
<10.10.10.10> <10.10.10.10> ssh connection has completed successfully
<10.10.10.10> connection to remote device started successfully
<10.10.10.10> local domain socket listeners started successfully
<10.10.10.10>
<10.10.10.10> local domain socket path is /Users/testuser/.ansible/pc/baf5c39e3d
ok: [nxos-core-1] => {
    "ansible_facts": {
        "password": "testing",
        "username": "test_user"
    },
    "ansible_included_var_files": [
        "/private/etc/ansible/secrets.yml"
    ],
    "changed": false
}

TASK [NXOS Show Admin Local Users] *****************************************************************************************************
task path: /private/etc/ansible/nxos-test.yml:13
<10.10.10.10> attempting to start connection
<10.10.10.10> using connection plugin network_cli
<10.10.10.10> found existing local domain socket, using it!
<10.10.10.10> updating play_context for connection
<10.10.10.10>
<10.10.10.10> local domain socket path is /Users/testuser/.ansible/pc/baf5c39e3d
<10.10.10.10> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.10.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/testuser/.ansible/tmp/ansible-local-66754KFKGrB/ansible-tmp-1539260805.6-67445272786497 `" && echo ansible-tmp-1539260805.6-67445272786497="` echo /Users/testuser/.ansible/tmp/ansible-local-66754KFKGrB/ansible-tmp-1539260805.6-67445272786497 `" ) && sleep 0'
fatal: [nxos-core-1]: FAILED! => {
    "msg": "Could not find imported module support code for nxos_command.  Looked for either *.py or shell.py"
}
	to retry, use: --limit @/private/etc/ansible/nxos-test.retry

PLAY RECAP *****************************************************************************************************************************
nxos-core-1    : ok=1    changed=0    unreachable=0    failed=1

```paste below
n/a
```
