### ISSUE TITLE
FAILURE-messages not informative enough

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#46829]
##### SUMMARY
I have a task, which downloads files from the Internet. Due to unavoidable network connectivity issues, I allow this task to try multiple times with a random delay. It works fine, but, when there is a transient delay, the failure-message is surprisingly brief:
```
TASK [native-package : Download package gcc] ***********************************************************************************************************************************************************************
skipping: [r0103zn00]
FAILED - RETRYING: Download package gcc (5 retries left).
changed: [r0104an20]
changed: [r0104an30]
changed: [r0104an60]
```
Because the download succeeded on the second attempt, I'll never know, what went wrong the first time -- only if all 5 download attempts fail, will I see the problem. Indeed, I don't even know, _which_ machine had this temporary problem!

As shown in the task-code below, I'm using the `get_url` module to affect the downloads. The module properly sets the `msg` field in the result dictionary. Why not output that, at least, when reporting a transient failure?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
!component

##### ADDITIONAL INFORMATION

```yaml
  - name: Download package {{ package.key }}
    get_url:
      url: "{{ _url }}"
      checksum: "{{ checksum }}"
      dest: "{{ dest }}"
      validate_certs: false	# We use checksums and don't need to encrypt
      mode: u=rw,g=r,o=r
    register: get_url
    until: get_url is success
    retries: 5
    delay: "{{ range(3, 17) | random }}"
```
