### ISSUE TITLE
Inventory ansible_ssh_user overrides play remote_user

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#4688]
I put ansible_ssh_user in inventory, to cope with the fact that new instances in our cloud demand login with different users, depending on distro (root, cirros, debian, etc.)  But this overrides remote_user in playbooks.

I mentioned this issue on #ansible, and @jctanner asked me to file a bug for it. Not a big deal for me, because I have a workaround (which is to use sudo_user instead of remote_user).
# How to repeat

``` bash
cat > ansible_hosts << EOF
[demo]
localhost

[demo:vars]
ansible_ssh_user=root
EOF

cat > demo-bug.yml << EOF

---
- hosts: demo
  remote_user: $LOGNAME
  tasks:
    - name: Echo remote user
      shell: echo \$LOGNAME
    - name: Prove that remote user is $LOGNAME
      shell: test \$LOGNAME = sheldonh
EOF

ansible-playbook -i ansible_hosts demo-bug.yml -v
```

Note that the second task fails, because the remote_user was ignored in favour of root (which you can see proven in the verbose output of the first task.

**Comment by mpdehaan** [comment]
Thanks for filing this.

I can see a use for it both ways so we'll need to consider things.

In this case, most people would leave off the "remote_user" line and just set it up in variables, and then pass in the default user with "-u".

**Comment by sheldonh** [comment]
Yeah, don't stress about pleasing everyone all the time. Those of us on the
fringe can live with easy work-arounds. :-)

**Comment by jctanner** [comment]
Reproduced:

```
jtanner@u1304:~/issues/4688-remote_user_scope/test$ ansible-playbook -vvvv -i ansible_hosts demo-bug.yml  2>&1 | egrep -e ^TASK -e "CONNECTION FOR USER" -e ^failed -e ^ok -e ^changed
<localhost> ESTABLISH CONNECTION FOR USER: root
ok: [localhost]
TASK: [Echo remote user] ****************************************************** 
<localhost> ESTABLISH CONNECTION FOR USER: root
changed: [localhost] => {"changed": true, "cmd": "echo $LOGNAME ", "delta": "0:00:00.001914", "end": "2013-10-29 15:11:07.481618", "rc": 0, "start": "2013-10-29 15:11:07.479704", "stderr": "", "stdout": "root"}
TASK: [Prove that remote user is jtanner] ************************************* 
<localhost> ESTABLISH CONNECTION FOR USER: root
failed: [localhost] => {"changed": true, "cmd": "test $LOGNAME = sheldonh ", "delta": "0:00:00.001849", "end": "2013-10-29 15:11:07.603068", "rc": 1, "start": "2013-10-29 15:11:07.601219"}
```

**Comment by jctanner** [comment]
@mpdehaan Can you confirm that we want to set the order of precedence for the connection user from ... 

inventory ansible_ssh_user > task remote_user > play remote_user > playbook remote_user > cli --user

to ...

 task remote_user > play remote_user > playbook remote_user > inventory ansible_ssh_user > cli --user

**Comment by mpdehaan** [comment]
I think the idea here is you are describing a fundamental property of the host, in this case, "the host needs to be connected to like so", and the value in the play is a default if none is set.

As such, I do not think this is a bug, and is in fact useful behavior.

Suppose 98% of your systems were in compliance and 2% were odd ducks, etc.

In this case I would choose to _not_ set this var in inventory if you didn't always want to connect as that user.

I view these special variables as properties of the system, more or less.

**Comment by malvim** [comment]
I too am on this seemingly not-too-oddball case where we need to connect to a host with some user MOST of the time, but when starting everything out we need to connect some other way.

This is my case:
I am using DigitalOcean, and they enable root login with public key authentication. What I want is to connect to the recently-created machine as root, CREATE a user that I will use to do everything else forever (namely, as it currently stands, `malvim`), disable root login and be done with it.

So the fundamental property of the server, as @mpdehaan puts it and I wholly agree, is that "this server needs to be connected to as `malvim`", except in the case where I am JUST starting and `malvim` isn't even there yet.

So I would happily leave "ansible_ssh_user=malvim", since this is what I want most of the time, but I'd like to have a way to overwrite it when I need to, either by setting `remote_user` on tasks I run the first time, or by setting `-u root` the first time I run, or whatever else works.

It seems to me that a change in the order of precedence (either the one @jctanner was talking about or some other that works) would make sense.

What do you guys think?

**Comment by sheldonh** [comment]
That's a great way of describing the issue, @malvim.

**Comment by bcoca** [comment]
you can  -e 'ansible_ssh_user=userthatoverridesinventory'

**Comment by sheldonh** [comment]
Brian, most of this stems from not wanting to special case the first (or
any) run from the perspective of the operator.

**Comment by malvim** [comment]
It seems to me, @bcoca, that this way I'd run ALL the tasks as root the first time (using `-e` as you said) and then switch to running as malvim. I can do pretty much the same using `-u root`, I think, right?

Even though it does work, this requires me to run things differently. If I could set a user for a group of tasks, I could use the initial set of tasks to test if I can login as root, if the user 'malvim' is there, then just set up (or don't) things the way I need them to be and THEN run my main tasks as malvim.

This way I could just describe which user does which set of tasks and run everything the same way every time.

**Comment by bcoca** [comment]
-u root does not override ansible_ssh_user.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by xcambar** [comment]
I'm jumping in to :+1: the Digital Ocean use case described by @malvim.

The workaround I'm using right now is to have a bootstrap playbook that does the basics:
- create a user
- set Authorized keys for this user
- Disable root
- some other little stuff

then one (or more) playbooks that almost exclusively use the created user.

**Comment by xcambar** [comment]
And for 2 more cents, my playbooks (for _my_ use cases in _my_ life, so nothing generic here) would really benefit from @jctanner's suggestion regarding the order of precedence.

**Comment by bratanon** [comment]
Same issue for me with Digital Ocean.

I'll try @xcambar trick to have a two different playbooks as it seems like the most "clean" solution right now.

**Comment by shilrobot** [comment]
For the use case being described above, I was able to get something with a single playbook going like this. Works in ansible 1.5.4 at least.

inventory file:

```
[all:vars]
ansible_ssh_user=standarduser

somebox initial_ssh_user=initialuser
```

playbook:

``` yaml
---

# run with ansible-playbook -v to see output

# Connect first time as initial_ssh_user (initialuser)
- hosts: all
  vars:
  - ansible_ssh_user: "{{initial_ssh_user}}"
  tasks:
  - name: Show user account
    shell: "echo $USER"

# Connect as standarduser from here on out
- hosts: all
  tasks:
  - name: Show user account
    shell: "echo $USER"
```

Making it so it always runs perfectly regardless of if it's the first or 100th time is tricky though. Like, say you connect initially as `root` then make the user `foo` & turn off `root` login. On first run you can't connect as `foo` to check if `root` login was disabled because the user doesn't exist. On subsequent runs you can't connect as `root` to check if `foo` was created. The playbook might have to just react to an ssh login failure to determine what to do then.

**Comment by bcoca** [comment]
I have something similar to this:

```yaml
# Connect first time as initial_ssh_user (initialuser)
- hosts: all
  gather_facts: false #important to avoid hosts dropped off from play
  vars:
  - ansible_ssh_user: "{{initial_ssh_user}}"
    tasks:
    - name: test user account
      action: ping
      ignore_errors: true
      register: initialuser
  
  # you can also use a group_by and another intermediate play that has
  
  hosts: initgroup
  - name: setup standard user
    user: ...
    when: initialuser|success

# Connect as standarduser from here on out
- hosts: all
  tasks:
  - name: Show user account
    shell: "echo $USER"use ignore errors and register

## 
```

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by shilrobot** [comment]
@bcoca Nice, I'll have to try that out! Thanks.

**Comment by MaximF** [comment]
@bcoca 
I'm trying to do an advanced version of your script where ansible running a role basing on a result of "when" condition. In my scenario ansible connects as root, creates ansible_bot user, grants him privilegies and denies access to root.
It all works on the first run, but it doesn't work on the second run, because ansible is unable to connect as a root on the first step.

I'm trying to omit that step by using the following logic, but it returns an error "error while evaluating conditional: root_connection.rc == 0". 

```yaml
- hosts: ansible-test
  gather_facts: false
  vars:
    - ansible_ssh_user: "{{ initial_ssh_user }}"
  tasks:
    - name: Test SSH connection for {{ initial_ssh_user }}
      local_action: shell ssh {{ initial_ssh_user }}@{{ inventory_hostname }} exit
      register: root_connection
      ignore_errors: True
  roles:
    - { role: add-ansible-bot, when: root_connection.rc == 0 }

- hosts: ansible-test
  sudo: yes
  roles:
    - common
```

Can you advice anything? 
Thanks!

**Comment by ghost** [comment]
I had a bright idea for how to do backups which ran up against this issue. Hopefully my comment is a useful data point.

I have a 'hosts' file in my infrastructure.git repo that describes each host. There are 3 OSes in use so I use groups like:

```ini
[fedora]
ansible_ssh_user=fedora

[ubuntu]
ansible_ssh_user=ubuntu

[baserock]
ansible_ssh_user=root
```

Then I added a 'backup' user to each of the machines I want to back up, and wrote a script that uses 'ansible' python modules to log into each host as 'backup' and run some commands to take a snapshot.

I want to reuse the existing 'hosts' file for the backup script so I don't have to duplicate info. I figured that this would be OK and I could do:

```
sudo -u backup ansible -i hosts --user=backup -m ping HOST
```

But this didn't work and I got pretty confused what was going on for a while. If I run a playbook, I can do this:

```
sudo -u backup ansible-playbook -i hosts testplay.yml -e 'ansible_ssh_user=backup'
```

I can work around this limitation fine, I'm just sharing this because I think if '--user' had overridden the configured 'ansible_ssh_user' I would have figured out the problem sooner. Also, it's a bit inconsistent that I can override 'ansible_ssh_user' when using `ansible-playbook`, but not when I'm using `ansible`.

**Comment by warvariuc** [comment]
+1 for `task remote_user > play remote_user > playbook remote_user > inventory ansible_ssh_user > cli --user`
I don't get the idea of having `remote_user` in a task which doesn't work.

Looks like this workaround worked for me:

```yaml
    - include: tasks_that_require_another_user.yml
      vars:
        ansible_ssh_user: "{{ another_user }}"
```

**Comment by davidfof13** [comment]
Hi all, 

I'm also trying to run a playbook which contains several tasks requiring different ansible users. The playbook is running on Windows hosts. I have tried overriding the users for my tasks using @warvariuc's suggestion above but my playbook seems to maintain the same user throughout the whole playbook. Can someone help me please?

**Comment by jcberthon** [comment]
The solution from @bcoca does not seem to work in Ansible 2.4.

I get:

```
TASK [init : Test for initial user availability] *****************************************************************************************************************************************************************************************************************************************
task path: /home/.../deployments/roles/init/tasks/main.yml:3
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/ping.py
<receiver01> ESTABLISH SSH CONNECTION FOR USER: root
<receiver01> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/home/.../.ansible/cp/bb94f209c1 receiver01 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<receiver01> (5, '', 'Permission denied, please try again.\r\n')
<receiver01> ESTABLISH SSH CONNECTION FOR USER: root
<receiver01> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/home/.../.ansible/cp/bb94f209c1 receiver01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1507544698.03-51626907341390 `" && echo ansible-tmp-1507544698.03-51626907341390="` echo ~/.ansible/tmp/ansible-tmp-1507544698.03-51626907341390 `" ) && sleep 0'"'"''
<receiver01> (5, '', 'Permission denied, please try again.\r\n')
fatal: [receiver01]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication failure.", 
    "unreachable": true
}
	to retry, use: --limit @/home/.../deployments/site.retry
```

This happens despite using `ignore_errors: true`. And as far as the documentation describes it, this is normal behaviour (see https://docs.ansible.com/ansible/latest/playbooks_error_handling.html). The ignore_errors is for failed return values, not host UNREACHABLE.

```
ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

I'm really wondering how you guys are all dealing with that. This is not limited to Digital Ocean. I have the same problem with another provider at work (here we use the cloud provider OVH). But at home this is a problem too where for example I want to change my Raspberry Pis from the default `pi` user to another one.

Ansible ought to address this use case. Even if it is only to document a way of doing this properly: bootstrapping the host with default provided user, creating a new user, locking/removing previous default user, going on with all the rest with the newly created user.

**Comment by jcberthon** [comment]
With the hint from @MaximF I got the following working:

```yaml
- name: Test for initial user availability
  local_action: shell sshpass -p{{ ansible_ssh_pass }} ssh {{ ansible_user }}@{{ inventory_hostname }} exit
  ignore_errors: yes
  register: initialuser

- name: Create Ansible user
  user:
    ...
  when: initialuser|success
```
