### ISSUE TITLE
Setting restricted variables in `set_fact`

### ISSUE THREAD

**Issue by jugglinmike** [ansible/ansible#46993]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```paste below
    ansible 2.7.0
      config file = None
      configured module search path = [u'/home/mike/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
      executable location = /usr/local/bin/ansible
      python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
```

(no output)

##### OS / ENVIRONMENT

Local: Ubuntu 16.04 x64
Remote: Ubuntu 18.04 x64

##### STEPS TO REPRODUCE

```yaml
- name: Locate Python interpreter on remote system
  raw: which python || which python3
  register: python_interpreter

- name: Set Python interpreter for use by subsequent tasks
  set_fact:
    ansible_python_interpreter: '{{python_interpreter.stdout}}'
```

##### EXPECTED RESULTS

I expect this to set the inventory variable `ansible_python_interpreter` without reporting any problem.

##### ACTUAL RESULTS

```paste below
    PLAY [all] *****************************************************************************************
    
    TASK [Locate Python interpreter on remote system] **************************************************
    changed: [test262.report]
    
    TASK [Set Python interpreter for use by subsequent tasks] ******************************************
     [WARNING]: Removed restricted key from module data: ansible_python_interpreter =   /usr/bin/python3
    
    ok: [example.com]
```

Despite the warning (and [the relevant source code](https://github.com/ansible/ansible/blob/9b2baebe64bf31eecec995af80c0501434b3c2fe/lib/ansible/vars/clean.py#L149-L150)), the definition appears to work. For example, a subsequent task:

```yaml
- name: After
  debug:
    msg: 'After: {{ansible_python_interpreter}}'
```

Produces the following output:

    TASK [After] ******************************
    ok: [example.com] => {
        "msg": "After: /usr/bin/python3\r\n"
    }

The discrepancy between the warning and the behavior is confusing. Should the variable be set? If so, then the warning ought to be removed. If not, then I'll find some other way to address my need (though [there's evidence that other people are relying on the behavior](https://stackoverflow.com/a/45720869)).

Ansible is an excellent tool; thanks for maintaining it!
