### ISSUE TITLE
lxd_container does not apply config options

### ISSUE THREAD

**Issue by dpantel** [ansible/ansible#47009]
##### SUMMARY
When passed a 'user.network-config' config option, it has no effect on the configuration of the created container.  There is no error message and the container is created as if that config option was never specified.

This does not happen when creating a container from the command line with the same config string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lxd_container

##### ANSIBLE VERSION
```
user@localhost:~$ ansible --version
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
- Linux Mint 19 (Ubuntu 18.04 LTS)
- LXD v. 3.0.1

##### STEPS TO REPRODUCE

The task run:

```yaml
- name: "LXD | Create and start container 'test'"
  lxd_container:
    name: test_ansible
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: ubuntu/bionic/amd64
    profiles: test
    config: { "user.network-config": '{"ethernets": {"eth0": {"addresses": ["10.0.0.115/24"], "gateway4": "10.0.0.1"}}, "version": 2}' }
    state: started
    wait_for_ipv4_addresses: true
```

Compared to the CLI command: (note the config lines is exactly the same)

```
user@localhost:~$ lxc launch ubuntu:bionic/amd64 test_cli -p test -c user.network-config="{\"ethernets\": {\"eth0\": {\"addresses\": [\"10.0.0.115/24\"], \"gateway4\": \"10.0.0.1\"}}, \"version\": 2}"
```

##### EXPECTED RESULTS

Expect a new container with a statically-set IP "10.0.0.115"

```
user@localhost:~$ lxc list
+--------------+---------+-------------------+------+------------+-----------+
| NAME         |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-------------------+------+------------+-----------+
| test_ansible | RUNNING | 10.0.0.115 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-------------------+------+------------+-----------+
```

##### ACTUAL RESULTS

New container created without requested static IP.

[Verbose ansible output here](https://gist.github.com/dpantel/c4b693fedd749feadc4f81117a217b52)

```
user@localhost:~$ lxc list
+--------------+---------+-------------------+------+------------+-----------+
| NAME         |  STATE  |       IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+--------------+---------+-------------------+------+------------+-----------+
| test_ansible | RUNNING | 10.0.0.187 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-------------------+------+------------+-----------+
| test_cli     | RUNNING | 10.0.0.115 (eth0) |      | PERSISTENT | 0         |
+--------------+---------+-------------------+------+------------+-----------+
```
