### ISSUE TITLE
Invalid options for assert: success_msg

### ISSUE THREAD

**Issue by quater** [ansible/ansible#47029]
##### SUMMARY

With Ansible 2.7, the assert module was enhanced with the success message. See module documentation at https://docs.ansible.com/ansible/2.7/modules/assert_module.html. The below example task fails with the error: **Invalid options for assert: success_msg**
```yaml
- name: after version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
  assert:
    that:
      - "my_param <= 100"
      - "my_param >= 0"
    fail_msg: "'my_param' must be between 0 and 100"
    success_msg: "'my_param' is between 0 and 100"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
assert

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
```

##### STEPS TO REPRODUCE

```yaml
- name: after version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
  assert:
    that:
      - "my_param <= 100"
      - "my_param >= 0"
    fail_msg: "'my_param' must be between 0 and 100"
    success_msg: "'my_param' is between 0 and 100"
```

##### EXPECTED RESULTS

It should accept the `success_msg` parameter

##### ACTUAL RESULTS

```paste below
fatal: [hostname]: FAILED! => changed=false 
  msg: 'Invalid options for assert: success_msg'
```
