### ISSUE TITLE
Ansible 2.7: Invalid options for reboot: reboot_timeout 

### ISSUE THREAD

**Issue by programingnotes** [ansible/ansible#47031]
##### SUMMARY
According to the [docs for reboot module in Ansible 2.7](https://docs.ansible.com/ansible/latest/modules/reboot_module.html), `reboot_timeout` is a valid option for the reboot module. Yet, this task: 
```
- name: Reboot a slow machine that might have lots of updates to apply
  reboot:
    reboot_timeout: 3600
```
returns: 
```
FAILED! => {"changed": false, "msg": "Invalid options for reboot: reboot_timeout"}
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /Users/pnotes/example/ansible/ansible.cfg
  configured module search path = ['/Users/pnotes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pnotes/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ansible
  executable location = /Users/pnotes/.pyenv/versions/3.6.4/bin/ansible
  python version = 3.6.4 (default, Feb 26 2018, 21:07:35) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/pnotes/example/ansible/ansible.cfg) = ['/Users/pnotes/example/ansible/inventories/test/hosts.ini']
DEFAULT_VAULT_PASSWORD_FILE(/Users/pnotes/example/ansible/ansible.cfg) = /Users/pnotes/.vault_pass.txt
```

##### OS / ENVIRONMENT

target OS versions => Ubuntu 16.04tls
##### STEPS TO REPRODUCE

Given this directory structure: 
```
├── ansible.cfg
├── inventories
│   └── test
│       └── hosts.ini
├── provision.yml
└── roles
    └── sample
        ├── handlers
        │   └── main.yml
        └── tasks
            └── main.yml
``` 

with And roles/sample/tasks/main.yml defined like so: 
``` 
- name: Update Linux Distribution Software (apt update && apt upgrade && apt autoremove)
  apt:
    upgrade: yes  # upgrade: 'dist'
    update_cache: yes
    autoremove: yes #this isn't working, need to change it
    dpkg_options: 'force-confold,force-confdef'  
    allow_unauthenticated: no

- name: Set Timezone to USA/NewYork
  timezone: 
    name: America/New_York
```

roles/sample/handlers/main.yml defined like so:
```
- name: Reboot machine 
  reboot: 
    reboot_timeout: 3600
    test_command: whoami
  notify:
    - Restart sshd
``` 

```yaml

```

##### EXPECTED RESULTS

I expect the handler, `Reboot machine`, defined above to return either `elapsed` or `rebooted` 

##### ACTUAL RESULTS

but instead the error message

```paste below
FAILED! => {"changed": false, "msg": "Invalid options for reboot: reboot_timeout"}
```
 is returned
