### ISSUE TITLE
register on multiple hosts fails to create correct output

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#47056]
##### SUMMARY
register on multiple hosts fails to create correct output. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
register

##### ANSIBLE VERSION

```
2.6.4
```

##### CONFIGURATION

```
Null
```

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804

##### STEPS TO REPRODUCE

```
- hosts: ALL
  gather_facts: True
  tasks:
  - name: Retrieve User information
    win_get_users: #Custom powershell module to retrive windows users
    register: facts_users

  - name: Pass variable
    set_stats:
      data:
        users_facts: "{{ facts_users.users[0] }}"
      per_host: no
```

##### EXPECTED RESULTS

I expect ansible either to overwrite facts_users variable with last host or generate a output a json format that shows the difference, like this:

`
[
    {
        "ADSPath": "WinNT://DOMAIN/TEST-1-VM/Admin", 
        "Class": "User", 
        "Domain": "DOMAIN", 
        "IsLocal": true, 
        "Name": "Admin"
    }
]
[
    {
        "ADSPath": "WinNT://DOMAIN/TEST-2-VM/Admin", 
        "Class": "User", 
        "Domain": "DOMAIN", 
        "IsLocal": true, 
        "Name": "Admin"
    }
]
`

##### ACTUAL RESULTS

This is simplified output. There are many more users. We have no way of filtering the json output in the below format.

`
[
    {
        "ADSPath": "WinNT://DOMAIN/TEST-1-VM/Admin", 
        "Class": "User", 
        "Domain": "DOMAIN", 
        "IsLocal": true, 
        "Name": "Admin"
    },
    {
        "ADSPath": "WinNT://DOMAIN/TEST-2-VM/Admin", 
        "Class": "User", 
        "Domain": "DOMAIN", 
        "IsLocal": true, 
        "Name": "Admin"
    }
]
`
