### ISSUE TITLE
Copy module fails to create destination directory with remote_src as per documentation

### ISSUE THREAD

**Issue by yktoo** [ansible/ansible#47050]
##### SUMMARY
The documentation for `copy` states that if `dest` ends with a `/`, it will be created if doesn't exist yet. It's not the case though if `remote_src` is set to `yes`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
(no changes)

##### OS / ENVIRONMENT
Linux box 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
**This works:**
```yaml
- copy:
      src: "/etc/skel/.profile"
      dest: '/etc/skel-new/'
      directory_mode: 0755
```

**This doesn't:**
```yaml
- copy:
      src: "/etc/skel/.profile"
      remote_src: yes
      dest: '/etc/skel-new/'
      directory_mode: 0755
```
```
fatal: [10.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Destination directory /etc/skel-new does not exist"}
```

##### EXPECTED RESULTS
The behaviour is the same with or without `remote_src`, or the difference is at least documented.
