### ISSUE TITLE
ios_config not idempotent when managing acls

### ISSUE THREAD

**Issue by benjdudas** [ansible/ansible#47067]
##### SUMMARY

When managing ACLs at the cisco device, the task is always shown as changed, even though the ACL is already present at the device.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 3453dace85) last updated 2018/10/12 10:45:28 (GMT -400)
  config file = /Users/bdudas/dev-net/csr1000v/ansible.cfg
  configured module search path = [u'/Users/bdudas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bdudas/dev-net/csr1000v/ansible/lib/ansible
  executable location = /Users/bdudas/dev-net/csr1000v/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

```

##### CONFIGURATION

```paste below
ovpn-121-196:csr1000v bdudas$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/bdudas/dev-net/csr1000v/ansible.cfg) = [u'/Users/bdudas/dev-net/inventory/hosts']
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.08.01a
##### STEPS TO REPRODUCE

```yaml
- name: " Access List"
  hosts: crs1000v
  gather_facts: no

  vars:
    mgmt_acl_90:
      - access-list 90 permit 172.20.40.0 0.0.0.255
      - access-list 90 permit 172.30.16.160 0.0.0.31
      - access-list 90 permit 172.20.16.0 0.0.0.127
      - access-list 90 permit 172.30.70.0 0.0.0.63

    mgmt_acl_99:
      - access-list 99 permit 172.20.35.98
      - access-list 99 permit 172.20.16.0 0.0.0.127
      - access-list 99 permit 172.30.70.0 0.0.0.63

  tasks:
    - name: "Setup"
      ios_config: &rm
        lines:
          - no access-list 90
          - no access-list 99

    - name: "Ensure access_list mgmt_acl_90"
      ios_config: &acl90
        save_when: "modified"
        lines: "{{ mgmt_acl_90 }}"
        match: line
        replace: block
        before: "no access-list 90"
      register: result

    - assert:
        that:
          - 'result.changed == true'

    - name: "validate config"
      ios_command:
        commands: "show running-config | include access-list"
      register: result

    - assert:
        that:
          - "'access-list 90 permit 172.20.40.0 0.0.0.255' in result.stdout[0]"
          - "'access-list 90 permit 172.30.16.160 0.0.0.31' in result.stdout[0]"
          - "'access-list 90 permit 172.20.16.0 0.0.0.127' in result.stdout[0]"
          - "'access-list 90 permit 172.30.70.0 0.0.0.63' in result.stdout[0]"


    - name: "Idempotence acl90"
      ios_config: *acl90
      register: result

    - assert:
        that:
          - 'result.changed == false'

    - name: "Ensure access_list mgmt_acl_99"
      ios_config: &acl99
        save_when: "modified"
        lines: "{{ mgmt_acl_99 }}"
        match: line
        replace: block
        before: "no access-list 99"
      register: result

    - assert:
        that:
          - 'result.changed == true'

    - name: "validate config"
      ios_command:
        commands: "show running-config | include access-list"
      register: result

    - assert:
        that:
          - "'access-list 99 permit 172.20.35.98' in result.stdout[0]"
          - "'access-list 99 permit 172.20.16.0 0.0.0.127' in result.stdout[0]"
          - "'access-list 99 permit 172.30.70.0 0.0.0.63' in result.stdout[0]"

    - name: "Idempotence acl99"
      ios_config: *acl99
      register: result

    - assert:
        that:
          - 'result.changed == false'

    - name: "TearDown"
      ios_config: *rm
```

##### EXPECTED RESULTS

The test with `Idempotence acl90` task should list as `"changed": false,` and not fail the assert check

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.8.0.dev0 (devel 3453dace85) last updated 2018/10/12 10:45:28 (GMT -400)
  config file = /Users/bdudas/dev-net/csr1000v/ansible.cfg
  configured module search path = [u'/Users/bdudas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bdudas/dev-net/csr1000v/ansible/lib/ansible
  executable location = /Users/bdudas/dev-net/csr1000v/ansible/bin/ansible-playbook
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
Using /Users/bdudas/dev-net/csr1000v/ansible.cfg as config file
Parsed /Users/bdudas/dev-net/inventory/hosts inventory source with ini plugin

PLAYBOOK: acl.yml ********************************************************************************************************************************************
1 plays in acl.yml

PLAY [Access List] *******************************************************************************************************************************************
META: ran handlers

TASK [Setup] *************************************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:19
<csr1000v> ESTABLISH LOCAL CONNECTION FOR USER: bdudas
<csr1000v> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199 `" && echo ansible-tmp-1539617964.54-130456048571199="` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199 `" ) && sleep 0'
Using module file /Users/bdudas/dev-net/csr1000v/ansible/lib/ansible/modules/network/ios/ios_config.py
<csr1000v> PUT /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/tmpi1XMCp TO /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199/AnsiballZ_ios_config.py
<csr1000v> EXEC /bin/sh -c 'chmod u+x /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199/ /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199/AnsiballZ_ios_config.py && sleep 0'
<csr1000v> EXEC /bin/sh -c '/usr/bin/python /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199/AnsiballZ_ios_config.py && sleep 0'
<csr1000v> EXEC /bin/sh -c 'rm -f -r /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617964.54-130456048571199/ > /dev/null 2>&1 && sleep 0'
changed: [csr1000v] => {
    "banners": {}, 
    "changed": true, 
    "commands": [
        "no access-list 90", 
        "no access-list 99"
    ], 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": false, 
            "before": null, 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": null, 
            "intended_config": null, 
            "lines": [
                "no access-list 90", 
                "no access-list 99"
            ], 
            "match": "line", 
            "multiline_delimiter": "@", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "replace": "line", 
            "csr1000ving_config": null, 
            "save": false, 
            "save_when": "never", 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null
        }
    }, 
    "updates": [
        "no access-list 90", 
        "no access-list 99"
    ]
}

TASK [Ensure access_list mgmt_acl_90] ************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:25
<csr1000v> ESTABLISH LOCAL CONNECTION FOR USER: bdudas
<csr1000v> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903 `" && echo ansible-tmp-1539617973.71-85284094784903="` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903 `" ) && sleep 0'
Using module file /Users/bdudas/dev-net/csr1000v/ansible/lib/ansible/modules/network/ios/ios_config.py
<csr1000v> PUT /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/tmpKX6Rt8 TO /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903/AnsiballZ_ios_config.py
<csr1000v> EXEC /bin/sh -c 'chmod u+x /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903/ /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903/AnsiballZ_ios_config.py && sleep 0'
<csr1000v> EXEC /bin/sh -c '/usr/bin/python /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903/AnsiballZ_ios_config.py && sleep 0'
<csr1000v> EXEC /bin/sh -c 'rm -f -r /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617973.71-85284094784903/ > /dev/null 2>&1 && sleep 0'
changed: [csr1000v] => {
    "banners": {}, 
    "changed": true, 
    "commands": [
        "no access-list 90", 
        "access-list 90 permit 172.20.40.0 0.0.0.255", 
        "access-list 90 permit 172.30.16.160 0.0.0.31", 
        "access-list 90 permit 172.20.16.0 0.0.0.127", 
        "access-list 90 permit 172.30.70.0 0.0.0.63"
    ], 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": false, 
            "before": [
                "no access-list 90"
            ], 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": null, 
            "intended_config": null, 
            "lines": [
                "access-list 90 permit 172.20.40.0 0.0.0.255", 
                "access-list 90 permit 172.30.16.160 0.0.0.31", 
                "access-list 90 permit 172.20.16.0 0.0.0.127", 
                "access-list 90 permit 172.30.70.0 0.0.0.63"
            ], 
            "match": "line", 
            "multiline_delimiter": "@", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "replace": "block", 
            "csr1000ving_config": null, 
            "save": false, 
            "save_when": "modified", 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null
        }
    }, 
    "updates": [
        "no access-list 90", 
        "access-list 90 permit 172.20.40.0 0.0.0.255", 
        "access-list 90 permit 172.30.16.160 0.0.0.31", 
        "access-list 90 permit 172.20.16.0 0.0.0.127", 
        "access-list 90 permit 172.30.70.0 0.0.0.63"
    ]
}

TASK [assert] ************************************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:34
ok: [csr1000v] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [validate config] ***************************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:38
<csr1000v> ESTABLISH LOCAL CONNECTION FOR USER: bdudas
<csr1000v> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724 `" && echo ansible-tmp-1539617988.45-232559368868724="` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724 `" ) && sleep 0'
Using module file /Users/bdudas/dev-net/csr1000v/ansible/lib/ansible/modules/network/ios/ios_command.py
<csr1000v> PUT /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/tmpCXJ0d8 TO /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724/AnsiballZ_ios_command.py
<csr1000v> EXEC /bin/sh -c 'chmod u+x /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724/ /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724/AnsiballZ_ios_command.py && sleep 0'
<csr1000v> EXEC /bin/sh -c '/usr/bin/python /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724/AnsiballZ_ios_command.py && sleep 0'
<csr1000v> EXEC /bin/sh -c 'rm -f -r /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617988.45-232559368868724/ > /dev/null 2>&1 && sleep 0'
ok: [csr1000v] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": null, 
            "commands": [
                "show csr1000ving-config | include access-list"
            ], 
            "host": null, 
            "interval": 1, 
            "match": "all", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null, 
            "wait_for": null
        }
    }, 
    "stdout": [
        "ip access-list standard GS_NAT_ACL\naccess-list 90 permit 172.20.40.0 0.0.0.255\naccess-list 90 permit 172.30.16.160 0.0.0.31\naccess-list 90 permit 172.20.16.0 0.0.0.127\naccess-list 90 permit 172.30.70.0 0.0.0.63\naccess-list 98 permit 172.20.216.78\naccess-list 98 permit 172.20.27.5\naccess-list 2678 deny   tcp any eq 623 any\naccess-list 2678 deny   tcp any eq 664 any\naccess-list 2678 deny   tcp any eq 16992 any\naccess-list 2678 deny   tcp any eq 16993 any\naccess-list 2678 deny   tcp any eq 16994 any\naccess-list 2678 deny   tcp any eq 16995 any\naccess-list 2678 permit ip any any"
    ], 
    "stdout_lines": [
        [
            "ip access-list standard GS_NAT_ACL", 
            "access-list 90 permit 172.20.40.0 0.0.0.255", 
            "access-list 90 permit 172.30.16.160 0.0.0.31", 
            "access-list 90 permit 172.20.16.0 0.0.0.127", 
            "access-list 90 permit 172.30.70.0 0.0.0.63", 
            "access-list 98 permit 172.20.216.78", 
            "access-list 98 permit 172.20.27.5", 
            "access-list 2678 deny   tcp any eq 623 any", 
            "access-list 2678 deny   tcp any eq 664 any", 
            "access-list 2678 deny   tcp any eq 16992 any", 
            "access-list 2678 deny   tcp any eq 16993 any", 
            "access-list 2678 deny   tcp any eq 16994 any", 
            "access-list 2678 deny   tcp any eq 16995 any", 
            "access-list 2678 permit ip any any"
        ]
    ]
}

TASK [assert] ************************************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:43
ok: [csr1000v] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Idempotence acl90] *************************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:51
<csr1000v> ESTABLISH LOCAL CONNECTION FOR USER: bdudas
<csr1000v> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625 `" && echo ansible-tmp-1539617995.1-77180669398625="` echo /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625 `" ) && sleep 0'
Using module file /Users/bdudas/dev-net/csr1000v/ansible/lib/ansible/modules/network/ios/ios_config.py
<csr1000v> PUT /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/tmpou1PUM TO /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625/AnsiballZ_ios_config.py
<csr1000v> EXEC /bin/sh -c 'chmod u+x /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625/ /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625/AnsiballZ_ios_config.py && sleep 0'
<csr1000v> EXEC /bin/sh -c '/usr/bin/python /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625/AnsiballZ_ios_config.py && sleep 0'
<csr1000v> EXEC /bin/sh -c 'rm -f -r /Users/bdudas/.ansible/tmp/ansible-local-49753JdXLsB/ansible-tmp-1539617995.1-77180669398625/ > /dev/null 2>&1 && sleep 0'
changed: [csr1000v] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": false, 
            "before": [
                "no access-list 90"
            ], 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": null, 
            "intended_config": null, 
            "lines": [
                "access-list 90 permit 172.20.40.0 0.0.0.255", 
                "access-list 90 permit 172.30.16.160 0.0.0.31", 
                "access-list 90 permit 172.20.16.0 0.0.0.127", 
                "access-list 90 permit 172.30.70.0 0.0.0.63"
            ], 
            "match": "line", 
            "multiline_delimiter": "@", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "replace": "block", 
            "csr1000ving_config": null, 
            "save": false, 
            "save_when": "modified", 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null
        }
    }
}

TASK [assert] ************************************************************************************************************************************************
task path: /Users/bdudas/dev-net/csr1000v/acl.yml:55
fatal: [csr1000v]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}
	to retry, use: --limit @/Users/bdudas/dev-net/csr1000v/acl.retry

PLAY RECAP ***************************************************************************************************************************************************
csr1000v : ok=6    changed=3    unreachable=0    failed=1    skipped=0   
```

**Comment by ansibot** [comment]
Hi @benjdudas, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@benjdudas, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by abenokraitis** [comment]
@justjais any ideas here? This has high priority. Thanks!

**Comment by ansibot** [comment]
cc @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by justjais** [comment]
@abenokraitis Apologies for the delay had reproduced the same but couldn't get to its resolution earlier as its related to `lines` cmd, but I'll try again and update on the same asap.

**Comment by justjais** [comment]
@benjdudas Apologies for the late response, I have looked into the issue and the issue you are observing is happening because of `no access-list 90` line cmd, as from the code end difference between the `running-config` is checked every-time the line cmd is fired via the `ios_config` module to check if its idempotent  and since `no access-list 90` cmd is not registered in the config of the device which results in firing the respective cmd each and every-time its encountered.
ref: https://github.com/ansible/ansible/blob/30c611a9cf5eee142f40d22b69556919b8e395e7/lib/ansible/modules/network/ios/ios_config.py#L44

And if you run `no` cmd for any other cmds also the behavior is same. eg: 
```
task1:
lines:
  - no ip forward-protocol nd`
task2:
lines:
  - ip forward-protocol nd
```
This will also result to `changed=true` every-time and thus will not be idempotent.

For the scenario to be idempotent, you'll need to run access-list separately as:
```
---
- hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    mgmt_acl_90:
      - "access-list 90 permit 172.20.40.0 0.0.0.255"
      - "access-list 90 permit 172.30.16.160 0.0.0.31"
  tasks:
  - name: "Ensure access_list mgmt_acl_90"
    ios_config: &acl90
      save_when: "modified"
      lines: "{{ mgmt_acl_90 }}"
      match: line
      replace: block
      before: "no access-list 90"
    register: result
```
Above, play shall be idempotent.
