### ISSUE TITLE
jenkins_plugin : not installing plugins while showing changed

### ISSUE THREAD

**Issue by sumanth567** [ansible/ansible#47069]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`jenkins_plugin.py`

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by sumanth567** [comment]
I am trying to install plugins in Jenkins, I am able to see the correct output which stated changed while installing plugin, but still plugins doesn't install in real. It also shows as changed for some of the plugins that have already been installed.

Below is my sample code with couple of plugins:

```yaml
- name: Install plugin
  tags: plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "/home/jenkins/.jenkins"
    state: present
    url: "http://example.com"   # access tomcat directly
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_password }}"
    with_dependencies: yes
  with_items:
     - amazon-ec2
     - Amazon Web Services SDK
     - Ant In Workspace
```

My Ansible version is 2.5.4
Can you please help me to get it worked.
