### ISSUE TITLE
Replace module regex does not work the same as lineinfile

### ISSUE THREAD

**Issue by jmj4000** [ansible/ansible#47064]
##### SUMMARY

Replace module regex does not work the same as lineinfile
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Replace module
##### ANSIBLE VERSION

```paste below
ansible 2.6.3
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Red Hat all versions
##### STEPS TO REPRODUCE

searching grub.conf
```
title Red Hat Enterprise Linux Server (2.6.32-754.3.5.el6.x86_64)
        root (hd0,0)
        kernel /vmlinuz-2.6.32-754.3.5.el6.x86_64 ro root=/dev/mapper/vg_sys-lv_root rd_NO_LUKS LANG=en_US.UTF-8 rd_LVM_LV=vg_sys/lv_swap rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_LVM_LV=vg_sys/lv_root  KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet
        initrd /initramfs-2.6.32-754.3.5.el6.x86_64.img
```
if you use this regex in line in file  regexp:
```
(^\s+kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.]+)*)\s*$'
```
then \1 returns
```
kernel /vmlinuz-2.6.32-754.3.5.el6.x86_64 ro root=/dev/mapper/vg_sys-lv_root rd_NO_LUKS LANG=en_US.UTF-8 rd_LVM_LV=vg_sys/lv_swap rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_LVM_LV=vg_sys/lv_root  KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet
```

If you use the replace module \1 returns
```
  kernel /vmlinuz-2.6.32-754.3.5.el6.x86_64 ro root=/dev/mapper/vg_sys-lv_root rd_NO_LUKS LANG=en_US.UTF-8 rd_LVM_LV=vg_sys/lv_swap rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_LVM_LV=vg_sys/lv_root  KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet
        initrd /initramfs-2.6.32-754.3.5.el6.x86_64.img
```

```yaml
---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: Edit grub to stop using transparent huge pages
    replace:
      path: /data01/grub.conf
      backup: true
      regexp: '(^\s+kernel(\s+(?!transparent_hugepage=never)[\w=/\-\.]+)*)\s*$'
      replace: '\1 transparent_hugepage=never'
...

```

##### ACTUAL RESULTS

title Red Hat Enterprise Linux Server (2.6.32-754.3.5.el6.x86_64)
        root (hd0,0)
        kernel /vmlinuz-2.6.32-754.3.5.el6.x86_64 ro root=/dev/mapper/vg_sys-lv_root rd_NO_LUKS LANG=en_US.UTF-8 rd_LVM_LV=vg_sys/lv_swap rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto rd_LVM_LV=vg_sys/lv_root  KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet
        initrd /initramfs-2.6.32-754.3.5.el6.x86_64.img transparent_hugepage=never
the transparent_hugepage=never is on the wrong line  it should appear just after "quiet"

```paste below

```
