### ISSUE TITLE
include_tasks with variables over "with_dict" fails.

### ISSUE THREAD

**Issue by rafernandez** [ansible/ansible#47071]
##### SUMMARY

include_tasks don't let me pass variable when looping over Hashes ("with_dict" loop).
Works in version 2.6 but not in 2.7.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_tasks

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

playbook-test.yml :
```
---
- hosts: all
  vars:
    lvm_vg:
      lvs:
        data01:
          size: 2000
          mount_point: /srv
          fstype: xfs
  tasks:
    - name: create logical volumes
      include_tasks: lv.yml lvm_lv_name={{item.key}} lvm_lv_specs={{item.value}}
      with_dict: "{{lvm_vg.lvs}}"
```
lv.yml : 

```
- debug: var=lvm_lv_name
- debug: var=lvm_lv_specs
```

##### EXPECTED RESULTS

Displays the variables lvm_lv_name and lvm_lv_specs

##### ACTUAL RESULTS

```
ERROR! Invalid options for include_tasks: lvm_lv_name,lvm_lv_specs

The error appears to have been in '/tmp/plabook-test.yml': line 11, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: create logical volumes
      ^ here
```

**Comment by sivel** [comment]
`include_tasks` no longer supports supplying inline vars.  Instead you must use `vars` to replicate your desired behavior:

```
    - name: create logical volumes
      include_tasks: lv.yml
      vars:
        lvm_lv_name: "{{item.key}}"
        lvm_lv_specs: "{{item.value}}"
      with_dict: "{{lvm_vg.lvs}}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
