### ISSUE TITLE
RFE: succeed_when/succeeded_when

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/ansible#47075]
##### SUMMARY
A new `succeed_when` argument (with the reverse logic of `failed_when`) would help define the success logic for command and/or shell tasks when there is not a module to manage a certain operation. If the criteria was not met then it is assumed to have failed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- command
- shell
- win_command
- win_shell

##### ADDITIONAL INFORMATION
Example:

```yaml
- name: Create a new libvirt network
  command: virsh net-define libvirt_network.xml
  register: define_libvirt_network
  succeed_when: "Requested operation is not valid: network is already active" in define_libvirt_network.stdout
  changed_when: define_libvirt_network.rc == 0
```

(Note: There is a virt_net module that would be better in this case, however this is just an example showcasing how `succeed_when` would work).

This could be even more useful if it's flexible enough to work with modules beyond just `command` or `shell`.

**Comment by ansibot** [comment]
Hi @ekultails, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/misc/virt_net.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/virt_net.py)
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)
* [lib/ansible/modules/commands/shell.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/shell.py)
* [lib/ansible/modules/windows/win_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_command.py)
* [lib/ansible/modules/windows/win_shell.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_shell.ps1)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by LukeShortCloud** [comment]
Another example use case I ran into:

```
- name: Create a container
  command: buildah from --name test centos:7
  register: buildah_centos_7
  succeed_when: "'that name is already in use' in buildah_centos_7.stdout"
```

**Comment by dagwieers** [comment]
I don't see the point, `failed_when` gives you all the functionality you need. If it didn't fail, it succeeded, so simply negate your expressions.

**Example 1:**
```yaml
- name: Create a new libvirt network
  command: virsh net-define libvirt_network.xml
  register: this
  failed_when: "'Requested operation is not valid: network is already active' not in this.stdout"
  changed_when: this.rc == 0
```
**Example 2:**
```yaml
- name: Create a container
  command: buildah from --name test centos:7
  register: this
  failed_when: "'that name is already in use' not in this.stdout"
```

And yes, `failed_when` works with every module (just like `changed_when`). So you have the fullest coverage possible already.
