### ISSUE TITLE
disable_excludes option for yum module doesn't accept Yum repository ids

### ISSUE THREAD

**Issue by wzur** [ansible/ansible#47085]
##### SUMMARY
The `disable_excludes` option for the `yum` module doesn't accept an actual Yum repository id.
This option has been added in Ansible 2.7

Instead it accepts only a literal `repoid` (apart of `all` and `main`) which is not exactly what it should have been. There is a snippet from the yum's man page for:

```
      --disableexcludes=[all|main|repoid]
              Disable the excludes defined in your config files. Takes one of three options:
              all == disable all excludes
              main == disable excludes defined in [main] in yum.conf
              repoid == disable excludes defined for that repo
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`yum` module

##### ANSIBLE VERSION
```paste below
ansible 2.7.0
  config file = /home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible.cfg
  configured module search path = [u'/home/waldemar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_SSH_ARGS(/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m -F ssh_config
ANSIBLE_SSH_CONTROL_PATH(/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible.cfg) = %(directory)s/%%h-%%r-%%p
DEFAULT_ROLES_PATH(/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible.cfg) = [u'/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/roles', u'/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/local-roles']
DEPRECATION_WARNINGS(/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/waldemar/IdeaProjects/kubernetes-cluster-ansible-deployment/ansible.cfg) = /tmp
```

##### OS / ENVIRONMENT
Ubuntu Bionic control host and CentOS 7 host

##### STEPS TO REPRODUCE

* Create a Yum repository with `exclude` populated
* Install a package with `yum` with `disable_excludes` set to previously created Yum repository

```yaml
- name: Add Kubernetes official repository
  become: True
  yum_repository:
    name: 'kubernetes'
    description: 'Kubernetes'
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
    enabled: yes
    exclude: 'kube*'
    gpgcheck: yes
    gpgkey: 'https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    repo_gpgcheck: yes

- name: Install with disable_excludes
  become: True
  name:
    - kubelet
    - kubeadm
    - kubectl
  disable_excludes: 'kubernetes'
```

##### EXPECTED RESULTS

All Kubernetes packages should be installed

##### ACTUAL RESULTS
`yum` module complains invalid value of the `disable_excludes`

```
failed: [centos7] (item=[u'kubeadm', u'kubelet', u'kubectl']) => {"changed": false, "item": ["kubeadm", "kubelet", "kubectl"], "msg": "value of disable_excludes must be one of: all, main, repoid, got: kubernetes"}
```
