### ISSUE TITLE
Terraform Module fails to validate variables.tf file when specified

### ISSUE THREAD

**Issue by iharrington** [ansible/ansible#47098]
##### SUMMARY

Attempting to use a variable file for terraform specified using the variables_file: '/path/to/variables.tf' and I can not get past validation step. When validating manually there are no issues, I can manually execute the same files/directory via terraform w/out issue. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Terraform module RE: variables_file (The path to a variables file for Terraform to fill into the TF configurations.)
##### ANSIBLE VERSION

```
ansible --version
ansible 2.7.0
  config file = None
  configured module search path = [u'/Users/iharrington/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### CONFIGURATION

```
Null
```

##### OS / ENVIRONMENT

Mac OS High Sierra
AKS
``` terraform version
Terraform v0.11.8
```

##### STEPS TO REPRODUCE

Create terraform block in ansible script and attempt to apply

```yaml
- name: Create terraform plan to build k8s cluster (AKS)
    terraform:
      project_path: '../k8s_terraform/'
      variables_file: '/k8s_terraform/variables.tf'
      plan_file: '../k8s_terraform/out.plan'
      state: planned


  - name: Confirm terraform plan is present
    wait_for:
      path: ../k8s_terraform/out.plan
      state: present


  - name: Apply terraform plan
    terraform:
      project_path: '../k8s_terraform/'
      variables_file: '/k8s_terraform/variables.tf'
      plan_file: '../k8s_terraform/out.plan'
      state: present
```

```terraform (variables file)
variable "client_id" {
  default = ""
}
variable "client_secret" {
  default = ""
}

variable "agent_count" {
  default = 4 
}

variable "ssh_public_key" {
  default = "~/.ssh/id_rsa.pub"
}

variable "dns_prefix" {
  default = "foo-sandbox"
}

variable cluster_name {
  default = "foo-platform-sandbox"
}

variable resource_group_name {
  default = "RG-Foo-US-West-SP-Bar-Compute"
}

variable location {
  default = "West US"
}
```

##### EXPECTED RESULTS

Terraform to validate file as it does manually.

##### ACTUAL RESULTS

Error during validation 

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate Terraform configuration files:\r\n\u001b[31minvalid value \"/k8s_terraform/variables.tf\" for flag -var-file: Error reading /k8s_terraform/variables.tf: open /k8s_terraform/variables.tf: no such file or directory\u001b[0m\u001b[0m\n\u001b[31mUsage: terraform validate [options] [dir]\n\n  Validate the terraform files in a directory. Validation includes a\n  basic check of syntax as well as checking that all variables declared\n  in the configuration are specified in one of the possible ways:\n\n      -var foo=...\n      -var-file=foo.vars\n      TF_VAR_foo environment variable\n      terraform.tfvars\n      default value\n\n  If dir is not specified, then the current directory will be used.\n\nOptions:\n\n  -check-variables=true If set to true (default), the command will check\n                        whether all required variables have been specified.\n\n  -no-color             If specified, output won't contain any color.\n\n  -var 'foo=bar'        Set a variable in the Terraform configuration. This\n                        flag can be set multiple times.\n\n  -var-file=foo         Set variables in the Terraform configuration from\n                        a file. If \"terraform.tfvars\" is present, it will be\n                        automatically loaded if this flag is not specified.\u001b[0m\u001b[0m\n"}

```
