### ISSUE TITLE
Enhancement: JBoss EAP Server Management Core Module

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#47092]
##### SUMMARY

A core module to manage JBoss EAP Server Management using the JBoss CLI

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

jboss_eap_server_mgmt_module

##### ADDITIONAL INFORMATION

```yaml
JDBC drivers

jdbc_drivers:
  - file: SomeJDBCDriver.jar

Datasources, <subsystem xmlns="urn:jboss:domain:datasources">

datasources:
  - DS:
    name: SomeDS
    connection_url: jdbc:mysql://localhost:3306/db
    connection_properties:
      - name: prop1
        value: val1
    jndi_name: java:jboss/datasources/SomeDS
    driver_name: mysql.jdbc.Driver_5_1
    jta: 'true'
    connectable: 'true'
    use_java_context: 'true'
    spy: 'true'
    use_ccm: 'true'
    statistics_enabled: 'true'
    driver_class: com.mydriver.jdbc.Driver
    datasource_class: com.datasoure.class
    new_connection_sql: select 1
    transaction_isolation: TRANSACTION_XX
    url_delimiter: XXX
    url_selector_strategy_class_name: XXX
    pool:
      min_pool_size: XXX
      max_pool_size: XXX
      prefil: True
      use_strict_min: 'true'
      flush_strategy: XXX
      allow_multiple_users: 'true'
    security:
      user_name: XXX
      password: XXX
      security_domain: XXX
      reauth_plugin_class_name: XXX
      reauth_plugin_properties: XXX
    validation:
      valid_connection_checker_class_name: XXX
      valid_connection_checker_properties: XXX
      check_valid_connection_sql: XXX
      validate_on_match: 'true'
      background_validation: 'false'
      background_validation_millis: XXX
      use_fast_fail: 'true'
      stale_connection_checker_class_name: XXX
      stale_connection_checker_properties: XXX
      exception_sorter_class_name: XXX
      exception_sorter_properties: XXX
    timeout:
      blocking_timeout_millis: XXX
      idle_timeout_minutes: XXX
      set_tx_query_timeout: XXX
      query_timeout: XXX
      use_try_lock: XXX
      allocation_retry: XXX
      allocation_retry_wait_millis: XXX
    statement:
      track_statements: 'true'
      prepared_statement_cache_size: XXX
      share_prepared_statements: 'true'
```
