### ISSUE TITLE
Ansible tower_user module is not idempotent

### ISSUE THREAD

**Issue by justjais** [ansible/ansible#47106]
##### SUMMARY

Ansible tower_user module is not idempotent, as it shows as changed as True every time the module runs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_user
##### ANSIBLE VERSION

```paste below
2.8.dev0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macos

##### STEPS TO REPRODUCE

On running the below playbook, tower_group modules shows changed=True every time the respective playbook runs.

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: create a user jdoe
    tower_user:
      username: jdoe
      password: foobarbaz
      email: jdoe@example.org
      first_name: John
      last_name: Doe
      superuser: no
      tower_verify_ssl: yes
      state: present
      tower_config_file: tower_cli.cfg
```

##### EXPECTED RESULTS

On running the same play for the second time, the tower_user module should be idempotent and should report `changed=False` if there is no change in play.

##### ACTUAL RESULTS

On running the same play for the second time, the module is not idempotent and reports `changed=True`, even if there is no change in play.

```paste below

```

**Comment by ansibot** [comment]
Hi @justjais, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AlanCoding @ghjm @jlaska @matburt @rooftopcellist @ryanpetrello @simfarm @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by AlanCoding** [comment]
See https://github.com/ansible/ansible/issues/36990

**Comment by justjais** [comment]
@AlanCoding thanks for updating about the issue, but have 1 query regarding the same that based on your comment: https://github.com/ansible/ansible/issues/36990#issuecomment-370440027.

I tried creating a user using:
```
- name: Add tower user
  tower_user:
    username: kirk
    password: "K!rkK!rk@"
    email: "kirk@startrek.com"
    first_name: Kirk
    last_name: Kirk
    state: present
```
and then in the second run commented on the password argument, but still was getting `changed=True` also tried changing the first name but again running for the second time it's coming `changed=True`. 
So, is that expected coz I am not changing the password now.
