### ISSUE TITLE
Grafana dashboard can't create a dashboard

### ISSUE THREAD

**Issue by ilychkov** [ansible/ansible#47119]
##### SUMMARY
When trying to create a dashboard, a error appears.
Apparently, it happens [here](https://github.com/ansible/ansible/blob/b48526ca65dd782a2dca5bf2db72e335ceb5e8f3/lib/ansible/modules/monitoring/grafana_dashboard.py#L243)
Seems like the script expects a "dashboard" section in the dashboard JSON, which actually doesn't exist.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_dashboard

##### ANSIBLE VERSION
```paste below
ansible 2.7.0
```

##### CONFIGURATION
```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Copy dev_servers.json
 copy: src=dev_servers.json dest=/tmp/dev_servers.json

- name: Deploy dev_servers.json
 grafana_dashboard:
   grafana_url: http://localhost:3000
   grafana_user: admin
   grafana_password: "{{ grafana_pwd }}"
   org_id: 1
   overwrite: true
   state: present
   message: Updated by ansible
   path: /tmp/dev_servers.json
```

##### EXPECTED RESULTS
New dashboard should appear

##### ACTUAL RESULTS
New dashboard doesn't appear

```paste below
 File \"/tmp/ansible_grafana_dashboard_payload_L0SL8v/__main__.py\", line 243, in grafana_create_dashboard
 KeyError: 'dashboard'
```
