### ISSUE TITLE
K8S_AUTH_* environment variables not read in Ansible 2.7

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/ansible#47149]
##### SUMMARY
In Ansible 2.7, the K8s module does not use any values set in K8S_AUTH_* environment variables.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
K8s

##### ANSIBLE VERSION
```paste below
ansible 2.7.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
CentOS 7 - AWX Container

##### STEPS TO REPRODUCE

```shell
export K8S_AUTH_KUBECONFIG=/path/to/other/config
Run a playbook using K8s module. The K8s module will either use values found in ~/.kube/config file or try to access the api server at localhost:443 if ~/.kube/config does not exist
```

##### EXPECTED RESULTS

K8s module uses the values set in the K8S_AUTH_* environment variables.

##### ACTUAL RESULTS

K8S_AUTH_KUBECONFIG set to /path/to/other/config. The K8s module will either use values found in ~/.kube/config file or try to access the api server at localhost:443 if ~/.kube/config does not exist.

This was working with Ansible 2.6.4.

**Comment by ansibot** [comment]
Hi @geauxvirtual, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
Hmm, I've used K8S_AUTH_KUBECONFIG and K8S_AUTH_CONTEXT successfully with 2.7

```
K8S_AUTH_KUBECONFIG=$HOME/.kube/aws.config K8S_AUTH_CONTEXT=my-context ansible -m k8s_facts -a 'kind=Pod namespace=test' localhost
```

works fine for me

**Comment by willthames** [comment]
Can you provide the full error message you're seeing running ansible with `-vvv`

**Comment by geauxvirtual** [comment]
Here is a gist that includes the output from 2.6.4 that succeeds and 2.7.0 that fails. At the end of the gist is the failure message. I wrote a simple playbook that displays the current-context in the kubeconfig file and then creates a namespace.

https://gist.github.com/geauxvirtual/3c7d889687bf10131f7b718d19745464

I seem to have confused the error messages I was seeing from my laptop to our AWX environment where I discovered this issue. You can see in the error message from 2.7, it's getting a forbidden error code returned because the call to the k8s api is trying to use the kubernetes service account in the namespace where AWX is running instead of the kubeconfig file loaded in K8S_AUTH_KUBECONFIG env variable.

**Comment by willthames** [comment]
Can you post the full output rather than the AWX truncated output (which has lots of `...` in it).

It would be helpful to see the full playbook you're using here too.

**Comment by geauxvirtual** [comment]
Here is the playbook. I looked through the output, the only two expansions I see are around the failure message that I posted in a separate file and the entire kubeconfig file that gets printed when set as an Ansible fact. I can post that whole output, but I'll have to redact out some information.

```yaml
- name: Demo Ansible
  hosts: k8s-master-nodes
  gather_facts: no
  tasks:
  - name: Get K8S_AUTH_KUBECONFIG
    set_fact:
      k8s_auth_kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG') }}"
  - debug: var=k8s_auth_kubeconfig
  - name: Get K8S_AUTH_KUBECONFIG contents
    set_fact:
      kubeconfig_contents: "{{ lookup('file', k8s_auth_kubeconfig) | from_yaml }}"
  - debug: msg="{{ kubeconfig_contents["current-context"] }}"
  - name: Create Namespace
    k8s:
      api_version: v1
      kind: Namespace
      name: ansible-demo
      state: present
```
