### ISSUE TITLE
nxos_static_route add track option

### ISSUE THREAD

**Issue by dmurarasu** [ansible/ansible#47148]
##### SUMMARY

Add track parameter option to the nxos_static_route module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_static_route 
##### ADDITIONAL INFORMATION

Adds the ability to configure track on static routes
I will create a PR to try and add this shortly.

```yaml
 - hosts: sw
  name: Configure switch
  connection: network_cli
  tasks:
      - name: configure static route with track
        nxos_static_route: 
          prefix: "192.168.20.64/24"
          next_hop: "192.0.2.3"
          route_name: default
          pref: 10
          tag: default
          track: 1
```
