### ISSUE TITLE
os_port - different order of items in allowed_address_pairs list should not trigger changes

### ISSUE THREAD

**Issue by moorglade** [ansible/ansible#47182]
##### SUMMARY
The exact order of items in `os_port` module's `allowed_address_pairs` parameter should not be considered a configuration change by the module.

Currently, if the order of port's address pairs returned from the OpenStack API is different from the order of items specified in the `allowed_address_pairs` list, the module treats it as a configuration change and proceeds to modify the port. This should not happen, as the list's order does not matter in any practical way and OpenStack does not provide any predictable sorting here.

I think there is a problem in the [`_needs_update`](https://github.com/ansible/ansible/blob/v2.7.0/lib/ansible/modules/cloud/openstack/os_port.py#L188) function, where `allowed_address_pairs` is considered to be a `dict`, when, in fact, it is a `list`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_port

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /home/myself/playbook/ansible.cfg
  configured module search path = [u'/home/myself/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04.1

##### STEPS TO REPRODUCE

Run the following playbook **twice**:

```yaml
---
- hosts: localhost
  tasks:
    - os_port:
        cloud: "my-cloud"
        name: "test"
        network: "my-network"
        allowed_address_pairs:
          - ip_address: "192.168.0.101"
            mac_address: "09:4a:f9:5b:e4:63"
          - ip_address: "192.168.0.100"
            mac_address: "09:4a:f9:5b:e4:63"
```

##### EXPECTED RESULTS

1. The first playbook execution creates and configures the port.
1. The second playbook execution does not make any changes.

##### ACTUAL RESULTS

When executing the playbook for the second time, the list of existing allowed address pairs returned by OpenStack has a different order than the one provided in the `allowed_address_pairs` (since OpenStack does not really care about any ordering here). The module interprets it as a configuration change and proceeds to modify the port.
