### ISSUE TITLE
pamd module adds duplicate arguments to rule when using state: args_present

### ISSUE THREAD

**Issue by shepdelacreme** [ansible/ansible#47197]
##### SUMMARY

The pamd module when using `state: args_present` doesn't account for rule arguments that have values when doing a comparison in the module code. i.e `remember=5` is different from `remember=6` so the module adds a duplicate argument to the rule. It should split on the `=` and compare value to value.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

pamd

##### ANSIBLE VERSION

```paste below
ansible 2.6.5
  config file = /Users/me/.ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/me/.virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /Users/me/.virtualenvs/ansible/bin/ansible
  python version = 3.6.6 (default, Jul 21 2018, 22:49:24) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

Also tested with `2.7.0`

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Use the pamd module in `state: args_present` mode and provide an argument that already exists on a rule but with a different value. i.e. `remember=5` vs `remember=6` 

Looking at the code in the module after the fact it is clear that it compares the entire argument as a single string. 

https://github.com/ansible/ansible/blob/dd46f953f6c88bc159c532b17e9b5c7e34f216bc/lib/ansible/modules/system/pamd.py#L630

```yaml
- name: Add rule so we can add arguments to it
   pamd:
     name: /etc/pam.d/system-auth
     state: before
     type: password
     control: sufficient
     module_path: pam_unix.so
     new_type: password
     new_control: requisite
     new_module_path: pam_pwhistory.so

- name: Add arguments to rule
   pamd:
     name: /etc/pam.d/system-auth
     state: args_present
     type: password
     control: requisite
     module_path: pam_pwhistory.so
     module_arguments:
       - use_authtok
       - remember=5
       - retry=3

- name: "Update argument value remember=5 to remember=6"
   pamd:
     name: /etc/pam.d/system-auth
     state: args_present
     type: password
     control: requisite
     module_path: pam_pwhistory.so
     module_arguments:
       - use_authtok
       - remember=6
       - retry=3
```

##### EXPECTED RESULTS

Module should replace the argument with the changed value. ie `remember=5` should change to `remember=6`

New rule should look like:
```paste below
password   requisite pam_pwhistory.so use_authtok remember=6 retry=3
```

##### ACTUAL RESULTS

The module instead of replacing a changed argument instead adds a duplicate argument with the different value. The module should not treat arguments with values as a single string during comparison.

```paste below
password   requisite pam_pwhistory.so use_authtok remember=5 retry=3 remember=6
```
