### ISSUE TITLE
bug in resolving/templating keys for dict variables

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4719]
Given this playbooklet:

``` yaml
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    name: app-dev-2
    node_num: "{{ name|last }}"
    datastore:
      "1": one 
      "2": two 

  tasks:
  - debug: msg="{{ datastore[node_num] }}" 
```

This fails with 

`fatal: [localhost] => One or more undefined variables: 'dict object' has no attribute '{{name|last}}'`

Expected result:

``ok: [localhost] => {    "msg": "two" }`

This faulty behaviour was introduced in 35cb9dc and still exist on latest devel 0faecdf7d1e8b2af1e69a7a67fffa3731ef130e3

**Comment by mpdehaan** [comment]
Still exploring options on the devel branch -- I believe when resolving the filters we need to run them for at least one pass, but not more, yet there are issues if we run them too many times.

Hope to have this resolved in a few days.  The temporary workaround for now is to filter inside the msg line.

**Comment by srgvg** [comment]
Just bumped into another issue, which probably will be the same.

Playbook:

``` yaml
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    admins:
    - paul
    - george
    - ringo
    - john
    devs:
    - mary
    - kate

    users:
    - "{{ admins }}"
    - "{{ devs }}"
  tasks:
  - debug: msg={{item}}
    with_flattened: users
```

With 35cb9dc~1 the full list is resolved and iterated.
With 35cb9dc I get 

```
ok: [localhost] => (item=users) => {
    "item": "users", 
    "msg": "users"
}
```
