### ISSUE TITLE
Custom error message when a module fails.

### ISSUE THREAD

**Issue by LeoUfimtsev** [ansible/ansible#47225]
##### SUMMARY
When a module fails, there is no built-in way to print a custom message. Only via a 2nd task.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- Module syntax

##### ADDITIONAL INFORMATION
For example: 

```yaml
 - name: Checking if user exists
    getent:                  
      database: passwd       
      key: myUser      
```
The error is not very clear if you're not the person who wrote the script:  

    fatal: [localhost]: FAILED! => {"changed": false, "msg": "One or more supplied key could not be found in the database."}

It would be great to be able to customize the error message.

There is a way to do this via saving result and checking with 'when' in a 2nd task and , but this is not very clean.
