### ISSUE TITLE
lookups no longer working in group_vars

### ISSUE THREAD

**Issue by neh** [ansible/ansible#4724]
A lookup I've had in my group_vars/all for a while stopped working recently. It stopped working as of baebe6d, and still doesn't work as of the latest, e0fbaea. The group_vars file looks similar to this:

```

---
local_dir: "{{ lookup('env', 'HOME') }}/dir"
```

Expected result: local_dir should equal /home/username/dir.
Actual result: local_dir is /home/username/ansible_working_dir/{{ lookup('env', 'HOME') }}/dir

**Comment by mpdehaan** [comment]
Just tried to reproduce this and encountered no problems.

I would have to see more of your playbook to see what may be going on but lookup plugins defined in group_vars are in fact running.

(note that we are going to revert some magic here soon that may also help you out)

**Comment by neh** [comment]
Thanks for testing it out. Now knowing that it should work, I did some more testing and realized that I was using local_dir in the above example inside a file lookup to install an authorized_key. Changing from this:

```
- name: Install deployment key
  hosts: targets
  sudo: yes
  tasks:
    - name: Install authorized key
      authorized_key: user={{ deployment_user }} key="{{lookup('file', local_dir + '/key.pub')}}"
```

to this:

```
- name: Install deployment key
  hosts: targets
  sudo: yes
  vars:
    key_path: local_dir + '/key.pub'
  tasks:
    - name: Install authorized key
      authorized_key: user={{ deployment_user }} key="{{lookup('file', key_path)}}"
```

makes things work (where local_dir is defined in group_vars as previously posted).
