### ISSUE TITLE
yaml inventory: empty keys in group declaration can break inventory parsing

### ISSUE THREAD

**Issue by tnielsen2** [ansible/ansible#47254]
##### SUMMARY

I am running Ansible from the command line on my local machine and am not able to get around two host-pattern groups in my inventory being ignored . I am unsure why this is happening. All new groups I have created work, with the exception of these two. I have verified my YAML inventory file with a linter with no issues.  I have tried deleting the information from the inventory file and manually retyping, validated the encoding and file format with no success. 

I have also tried to rename the groups, reposition them in the inventory file with the same issue. If I add "dummy" groups, they are easily read and recognized. 

I have also tried to run the playbook with a --flush-cache switch and I get the following:

```
ansible-playbook -i ./environments/network/network-inventory ./playbooks/network/ios-aaa.yml --flush-cache -vvv
ansible-playbook 2.7.0
  config file = /Users/tnielsen/dev/ansible/ansible.cfg
  configured module search path = [u'/Users/tnielsen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15 (default, Oct  2 2018, 11:42:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
Using /Users/tnielsen/dev/ansible/ansible.cfg as config file
Parsed /Users/tnielsen/dev/ansible/environments/network/network-inventory inventory source with ini plugin
ERROR! Unexpected Exception, this is probably a bug: u'core.sthd.corp.yamww.com'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 116, in run
    self._flush_cache(inventory, variable_manager)
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 196, in _flush_cache
    variable_manager.clear_facts(hostname)
  File "/usr/local/lib/python2.7/site-packages/ansible/vars/manager.py", line 613, in clear_facts
    del self._fact_cache[hostname]
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/cache/__init__.py", line 273, in __delitem__
    self._plugin.delete(key)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/cache/redis.py", line 119, in delete
    del self._cache[key]
KeyError: u'core.sthd.corp.yamww.com'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Secret Server

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /Users/tnielsen/dev/ansible/ansible.cfg
  configured module search path = [u'/Users/tnielsen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:42:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/tnielsen/dev/ansible/ansible.cfg) = True
CACHE_PLUGIN(/Users/tnielsen/dev/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/Users/tnielsen/dev/ansible/ansible.cfg) = production-a-cache.h6fgmd.ng.0001.usw2.cache.amazonaws.com:6379:0
CACHE_PLUGIN_TIMEOUT(/Users/tnielsen/dev/ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/Users/tnielsen/dev/ansible/ansible.cfg) = 50
DEFAULT_HASH_BEHAVIOUR(/Users/tnielsen/dev/ansible/ansible.cfg) = merge
DEFAULT_POLL_INTERVAL(/Users/tnielsen/dev/ansible/ansible.cfg) = 5
DEFAULT_ROLES_PATH(/Users/tnielsen/dev/ansible/ansible.cfg) = [u'/Users/tnielsen/dev/ansible/roles']
HOST_KEY_CHECKING(/Users/tnielsen/dev/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/tnielsen/dev/ansible/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/Users/tnielsen/dev/ansible/ansible.cfg) = 40
RETRY_FILES_ENABLED(/Users/tnielsen/dev/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Play step 1:
Extract credentials from Secret Server to run against network inventory file
Play step 2: 
run ios_command and ios_config modules to configure aaa configuration. 

##### STEPS TO REPRODUCE

Below is a snipped of my inventory file:
```
network-all:
  children:
    gope:
      children:
        gope-cisco:
          hosts:
            avrack.gope.corp.yamww.com:
            core.gope.corp.yammww.com:
            ntnx.gope.corp.yamww.com:
            usw11-0[1:5].gope.corp.yamww.com:
            usw12-01.gope.corp.yamww.com:
    gosc:
      children:
        gosc-icx:
          hosts:
           usw11-0[1:4].hnda.gosc.corp.yamww.com:
           usw11-01.rcv.gosc.corp.yamww.com:
    hdos:
      children:
        hdos-cisco:
          hosts:
            core.hdos.corp.yamww.com:
            ntnx.hdos.corp.yamww.com:
            tor02.hdos.corp.yamww.com:
            tor03.hdos.corp.yamww.com:
            tor06-07.hdos.corp.yamww.com:
            tor09-10.hdos.corp.yamww.com:
            usw[1:4].hdos.corp.yamww.com:
            theater.hdos.corp.yamww.com:
```
I can run this playbook with this inventory file with the below command (against any playbook that references this group) and get the error below the command. It is always the two same groups that have this issue. 
```
ansible-playbook -i ./environments/network/network-inventory ./playbooks/network/ios-aaa.yml
```

```
TASK [Assign Secrets to Variables] *********************************************************************************************************************************************************
ok: [localhost]
 [WARNING]: Could not match supplied host pattern, ignoring: gope-cisco
 [WARNING]: Could not match supplied host pattern, ignoring: sfcf-cisco
```

```yaml
---
- name: Retrieve Secrets
  hosts: localhost
  connection: local
  vars_files:
    - /etc/ansible/environments/all/vars/secretserver.yml
  tasks:
  - name: Retrieve Secrets
    secretserver:
      uri: "{{ secretserver_uri }}"
      username: "{{ secretserver_username }}"
      password: "{{ secretserver_password }}"
      domain: "{{ secretserver_userdom }}"
      secretid: "{{ item }}"
    with_items:
      - OMITTED
    register: secrets
  - name: Assign Secrets to Variables
    set_fact:
      local_ssh_pass: "{{ secrets.results.0.secret.Items.Password.Value }}"
      cacheable: True

#  - name: Show password retreived
#    debug:
#       msg: "{{ local_ssh_pass }}"
#

- name: Manage Cisco AAA Configuration
  hosts:
    - gope-cisco
    - hdos-cisco
    - sfcf-cisco
    - sthd-cisco
    - yamhq-cisco
  connection: network_cli
  remote_user: yitadmin
  vars:
    ansible_ssh_pass: "{{ hostvars['localhost']['local_ssh_pass'] }}"
    ansible_network_os: ios
  roles:
    - ios-aaa-config
    - ios-copy-run-start
```

##### EXPECTED RESULTS

I expect this playbook to be able to recognize the host patterns for the gope and sfcf host groups. 

##### ACTUAL RESULTS

Running with extra verbosity yields the same error. 

```paste below
TASK [Assign Secrets to Variables] *********************************************************************************************************************************************************
task path: /Users/tnielsen/dev/ansible/playbooks/network/ios-aaa.yml:20
ok: [localhost] => {
    "ansible_facts": {
        "local_ssh_pass": "OMITTED"
    },
    "changed": false
}
META: ran handlers
META: ran handlers
 [WARNING]: Could not match supplied host pattern, ignoring: gope-cisco
 [WARNING]: Could not match supplied host pattern, ignoring: sfcf-cisco

PLAY [Manage Cisco AAA Configuration] ******************************************************************************************************************************************************
```

**Comment by ansibot** [comment]
Hi @tnielsen2, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tnielsen2** [comment]
After much troubleshooting and testing, it was discovered that the commented out hosts in my inventory file were the culprit, somehow causing the issue.

**Comment by bcoca** [comment]
can you give a reproducer? this seems like an inventory parsing error.

**Comment by tnielsen2** [comment]
Can you provide a little guidance on how to do that? I would be happy to do so.

**Comment by tnielsen2** [comment]
To be more specific about the cause of the issue, below is my entire inventory file, and commented hosts in the lab and ywg groups were the culprit. I also tested this on a different Ansible deployment inventory file with far less hosts with the same issue.

```
---
# Network Inventory
network-all:
  children:
    gope:
      children:
        gope-cisco:
          hosts:
            avrack.gope.corp.yamww.com:
            core.gope.corp.yamww.com:
            ntnx.gope.corp.yamww.com:
            usw11-0[1:5].gope.corp.yamww.com:
            usw12-01.gope.corp.yamww.com:
    gosc:
      hosts:
        children:
          gosc-icx:
            usw11-0[1:4].hnda.gosc.corp.yamww.com:
            usw11-01.rcv.gosc.corp.yamww.com:
    hdos:
      children:
        hdos-cisco:
          hosts:
            core.hdos.corp.yamww.com:
            ntnx.hdos.corp.yamww.com:
            tor02.hdos.corp.yamww.com:
            tor03.hdos.corp.yamww.com:
            tor06-07.hdos.corp.yamww.com:
            tor09-10.hdos.corp.yamww.com:
            usw[1:4].hdos.corp.yamww.com:
            theater.hdos.corp.yamww.com:
    lab:
      children:
        lab-cisco:
          hosts:
            #test-3750-04-02.ydc.corp.yamww.com:
        lab-icx:
          hosts:
            test-icx-04-02.ydc.corp.yamww.com:
            test-icx-04-03.ydc.corp.yamww.com:
        #10.8.20.237:
    pxg-nbil:
      children:
        pxg-nbil-fortigate:
          hosts:
            fw.nbil.pxg.corp.yamww.com:
        pxg-nbil-icx:
          hosts:
            usw11-0[1:2].nbil.pxg.corp.yamww.com:
    sfcf:
      children:
        sfcf-cisco:
          hosts:
            core.sfcf.corp.yamww.com:
            usw[1:3].sfcf.corp.yamww.com:
    sngc:
      hosts:
        children:
          sngc-fortigate:
            hosts:
              fw.pxgh.sngc.corp.yamww.com:
          sngc-icx:
            hosts:
              usw11-0[1:2].mens.sngc.corp.yamww.com:
              usw11-0[1:2].admin.sngc.corp.yamww.com:
              usw11-01.sales.sngc.corp.yamww.com:
              usw11-01.maint.sngc.corp.yamww.com:
              usw11-0[1:8].pxgh.sngc.corp.yamww.com:
              tor01-0[1:8].pxgh.sngc.corp.yamww.com:
              usw11-0[1:2].bays.sngc.corp.yamww.com:
              usw11-0[1:2].pxgp.sngc.corp.yamww.com:
              core01-01.pxgh.sngc.corp.yamww.com:
              usw11-0[1:2].toc.sngc.corp.yamww.com:
              usw11-01.gs.sngc.corp.yamww.com:
    sthd:
      children:
        sthd-cisco:
          hosts:
            core.sthd.corp.yamww.com:
            usw21-0[1:2].sthd.corp.yamww.com:
            usw11-01.sthd.corp.yamww.com:
            nutanix.sthd.corp.yamww.com:
        sthd-cisco-wlc:
          hosts:
            wlc-sw.sthd.corp.yamww.com:
    yamhq:
      children:
        yamhq-cisco:
          hosts:
            av.yam.corp.yamww.com:
        icx:
          hosts:
            usw11-0[1:4].yam.corp.yamww.com:
    ywg:
      children:
        ywg-cisco:
          hosts:
            #usw31-01.ywg.corp.yamww.com:
```
