### ISSUE TITLE
apt module no longer optimizing with_items lists

### ISSUE THREAD

**Issue by neh** [ansible/ansible#4725]
Starting from 1f6edf7, the apt module (and presumably yum and pkgng as well) is processing each package in a with_items list separately, rather than bundling them into a single call. Here is one of my tasks where this is occurring:

```

---
- name: setup apt deps and base packages
  apt: pkg={{ item }}
  with_items:
    - python-software-properties
    - ubuntu-cloud-keyring
    - ntp
    - curl
    - wget
    - git
    - tmux
    - vim
```

That task lives in a main.yml in a common role, which is applied like this:

```

---
- hosts: all
  sudo: yes
  roles:
    - common
```

(edited to reflect correct commit)
