### ISSUE TITLE
AWS Lambda role will sometimes return erroneous ARN

### ISSUE THREAD

**Issue by flybd5** [ansible/ansible#47264]
##### SUMMARY
When creating a Lambda on AWS, sometimes the result shows a correct ARN, but once in a while it will append a version number at the end which breaks other modules that need that to perform some action related to the Lambda.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Lambda

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = ['/Users/ext.juan.jimenez/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.0/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Sep 18 2018, 18:47:22) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
```
(empty)
```

##### OS / ENVIRONMENT
AWS, I'm running OS/X 10.14.

##### STEPS TO REPRODUCE
```yaml
lambda:
        name: "{{ lambda_name }}"
        region: "{{ lambda_region }}"
        profile: "{{ lambda_profile }}"
        role: "{{ lambda_role }}"
        handler: "{{ lambda_handler }}"
        runtime: python2.7
        zip_file: dist/Archive.zip
        state: present
        timeout: 180
        environment_variables: "{{ lambda_environment_vars }}"
      register: create_lambda_result
```
From create_lambda_result I get the ARN:

`create_lambda_result.configuration.function_arn`

I then use that to create the event in S3 that calls the Lambda:

```yaml
- name: Setup the lambda event template for the S3 bucket
      shell: |
        echo '{"LambdaFunctionConfigurations": [{
                 "Id": "myESEvent",
                 "LambdaFunctionArn": "{{create_lambda_result.configuration.function_arn}}",
                 "Events": [ "s3:ObjectCreated:*" ]}]}' > ntemplate.json
      register: result
      failed_when: result.rc != 0
```

When I then use that to crete the S3 notification event here:

```yaml
- name: Set the Lambda S3 notification to the bucket
      shell: aws s3api put-bucket-notification-configuration --bucket {{ lambda_s3_bucket }} \
        --profile {{ lambda_profile }} --region {{ lambda_region }} \
        --notification-configuration file://ntemplate.json --debug 2>>log.txt
      retries: 10
      delay: 1
      register: result
      until: result.rc == 0
```

...the call to the s3api fails, saying it cannot interpret the destination (the lambda ARN). That does't happen all the time, only intermittently, and the reason it happens is that when it fails, it's because for some weird reason the call to the lambda role has returned an ARN with a version number at the end of the ARN. That is not supposed to happen. 

##### EXPECTED RESULTS

`arn:aws:lambda:eu-central-1:123456789012:function:testing_s3_logging_to_es`

##### ACTUAL RESULTS

`arn:aws:lambda:eu-central-1:123456789012:function:testing_s3_logging_to_es:6`

```
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": "aws s3api put-bucket-notification-configuration --bucket flaconi-dev-elb-logs --profile dev --notification-configuration file://ntemplate.json", "delta": "0:00:00.575015", "end": "2018-10-15 16:12:13.457195", "msg": "non-zero return code", "rc": 255, "start": "2018-10-15 16:12:12.882180", "stderr": "\nAn error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations", "stderr_lines": ["", "An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations"], "stdout": "", "stdout_lines": []}
```
