### ISSUE TITLE
Loop_var

### ISSUE THREAD

**Issue by Fantasylp2705** [ansible/ansible#47284]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.6.1
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventories']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/lib/ansible']
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: crm-db
  gather_facts: no
  tasks:
    - name: Backuping Databases
      include_role:
        name: update_db
        tasks_from:
          backup.yml
      with_items: "{{ dbs }}"
      loop_control:
        loop_var: db
      when: dbs[db].version != ""

- hosts: crm-backend
  gather_facts: no
  tasks:
    - name: Installing certificates
      include_role:
        name: install_certificate
      with_items: "{{ certificates }}"
      loop_control:
        loop_var: certificate
      when: certificates is defined and create_sites=="true"

    - name: Creating sites
      include_role:
        name: create_site
      with_items: "{{ webs }}"
      loop_control:
        loop_var: web
      when: webs[web].version != "" and create_sites=="true"

    - name: Stopping sites
      include_role:
        name: stop_site
      with_items: "{{ webs }}"
      loop_control:
        loop_var: web
      when: webs[web].version != ""

- hosts: crm-db
  gather_facts: no
  tasks:
    - name: Updating Databases
      include_role:
        name: update_db
      with_items: "{{ dbs }}"
      loop_control:
        loop_var: db
      when: dbs[db].version != ""

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Downloading config templates
      command: mono /usr/bin/nuget install Crm.Templates -Version {{ CRM_templates }} -Source http://examle.org:8030/nuget/{{ feed }} -PackageSaveMode nuspec -OutputDirectory /etc/templates -PreRelease

- hosts: crm-backend
  gather_facts: no
  tasks:
    - name: Updating web binary with configs
      include_role:
        name: update_web
      with_items: "{{ webs }}"
      loop_control:
        loop_var: web
      when: webs[web].version != "" and config_only!="true"

    - name: Updating only web configs
      include_role:
        name: update_web
        tasks_from:
          config.yml
      with_items: "{{ webs }}"
      loop_control:
        loop_var: web
      when: webs[web].version != "" and config_only=="true"

- hosts: crm-service
  gather_facts: no
  tasks:
    - name: Updating services with configs
      include_role:
        name: update_service
      with_items: "{{ services }}"
      loop_control:
        loop_var: service
      when: services[service].version != "" and config_only!="true"

    - name: Updating only services configs
      include_role:
        name: update_service
        tasks_from:
          config_only.yml
      with_items: "{{ services }}"
      loop_control:
        loop_var: service
      when: services[service].version != "" and config_only=="true"

- hosts: crm-backend
  gather_facts: no
  strategy: free
  tasks:
    - name: Starting sites
      include_role:
        name: start_site
      with_items: "{{ webs }}"
      loop_control:
        loop_var: web
      when: webs[web].version != ""
group_vars
---
services:
  1:
    name: "name-1"
    package: "package-1"

  2:
    name: "name-2"
    package: "package-2"

  3:
    name: "name-3"
    package: "package-3"

  4:
    name: "name-4"
    package: "package"

  5:
    name: "name-5"
    package: "package-5"

  6:
    name: "name-6"
    package: "package-6"

  7:
    name: "name-7"
    package: "package-7"

  8:
    name: "name-8"
    package: "package-8"

  9:
    name: "name-9"
    package: "package-9"

  10:
    name: "name-10"
    package: "package-10"

  11:
    name: "name-11"
    package: "package-11"

  12:
    name: "name-12"
    package: "package"

  13:
    name: "name-13"
    package: "package-13"

  14:
    name: " name-14"
    package: "package-14"



```

##### ACTUAL RESULTS

items are out of order

```paste below
ansible-playbook playbooks/deploy.yaml -i inventories/qa1 -vvvvv
```
