### ISSUE TITLE
Unable to find and restart built-in service on Slackware.

### ISSUE THREAD

**Issue by keeely** [ansible/ansible#47291]
##### SUMMARY

Can't restart service on Slackware 14.2

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
  ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.11 (default, Mar  3 2016, 13:35:30) [GCC 5.3.0]
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

Slackware 14.2, 64-bit unpatched.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Restart service
      service:
        name: '{{ item }}'
        state: restarted
      with_items:
        - dnsmasq
      become: true
      become_user: root
```

##### ACTUAL RESULTS

```
failed: [localhost] (item=dnsmasq) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "arguments": null, 
            "daemonize": false, 
            "enabled": null, 
            "name": "dnsmasq", 
            "pattern": null, 
            "runlevels": null, 
            "sleep": 1, 
            "state": "restarted"
        }
    }, 
    "item": "dnsmasq", 
    "msg": "Could not find the requested service dnsmasq: "
}
```
