### ISSUE TITLE
running bash command in ansible on centos 7 leads to /dev/null permission denied problem 

### ISSUE THREAD

**Issue by lwsanty** [ansible/ansible#47305]
##### SUMMARY

running bash command in ansible on centos 7 leads to `/dev/null` permission denied problem 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gce, command, shell

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/lwsanty/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
ansible returns empty output here, sorry :)
```

##### OS / ENVIRONMENT

Centos 7

##### STEPS TO REPRODUCE

circleci runs ansible script that performs
1) create gce instance with os centos 7
2) copy binary to instance
3) try to run this binary on instance via ssh

```yaml
---
- name: copy test binary
  copy:
    src: files/test
    dest: /home/user/test
    mode: u+rwx,g+rwx,o+rwx

- name: execute test binary
  command: bash -c "/home/user/test -test.v > /home/user/log.txt 2>&1"
```

##### EXPECTED RESULTS

run of test should finish successfully

##### ACTUAL RESULTS

`/dev/null: Permission denied` and no further commands can be performed
```
[WARNING]: Error deleting remote temporary files (rc: 1, stderr: /etc/bashrc:
line 84: /dev/null: Permission denied /etc/bashrc: line 84: /dev/null:
Permission denied /etc/bashrc: line 84: /dev/null: Permission denied
/etc/bashrc: line 84: /dev/null: Permission denied /etc/bashrc: line 84:
/dev/null: Permission denied /etc/bashrc: line 84: /dev/null: Permission denied
/etc/bashrc: line 84: /dev/null: Permission denied /bin/sh: /dev/null:
Permission denied })
```

```paste below

```

##### NOTES AND LINKS
https://github.com/ansible/ansible/issues/33010
https://github.com/openshift/openshift-ansible/issues/5331
