### ISSUE TITLE
VMware: Request for support SATA disk controller

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#47329]
##### SUMMARY

We need to test deploying new VM with disk attaching to SATA controller, now vmware_guest module supports config SCSI disk controller types.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest
##### ADDITIONAL INFORMATION

We need to deploy different disk controllers the VM/Guest supports on ESXi host, e.g. SCSI controller, SATA controller, IDE controller, nVME controller(#43000) as boot disk controller, but now vmware_guest supports SCSI types of disk controller.

```yaml
hardware:
     version: 13
     memory_mb: 4096
     num_cpus: 2
     num_cpu_cores_per_socket: 1
     sata: present
disk:
- size_gb: 40
   type: thin
   datastore: datastore1
```

**Comment by ansibot** [comment]
Hi @Tomorrow9, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/module_utils/facts/hardware/__init__.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/hardware/__init__.py)
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Tomorrow9, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Tomorrow9** [comment]
@Akasurde, hi, do you think it's better to add one more parameter as "hardware.sata" in this case?
Thanks.

**Comment by Akasurde** [comment]
@Tomorrow9 I think configuring controller per disk makes sense to me that gives more control to user. also, having parent key in hardware will help.

```yaml
disk:
- size_gb: 40
   type: thin
   datastore: datastore1
   controller: sata
```

Let me know if it make sense.
