### ISSUE TITLE
[getent module] getent wrapper should return associative arrays instead of lists

### ISSUE THREAD

**Issue by danowar2k** [ansible/ansible#47343]
##### SUMMARY
At the moment the getent wrapper returns the key with a list containing the found entries.
The problem is getent doesn't return an empty string for when e.g. a passwd entry misses a description or something like that. So the returned list is dynamic in size.

This way you can't access list items with indices, because you can't be sure if the index of a list item is the correct one.

Perhaps a better way would be to return dictionaries where the keys tell me what I get when I access them.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
getent

##### ADDITIONAL INFORMATION
I could easily access the home directory entry of a user using the following tasks:

```yaml
- name: Get user info
  getent:
    database: passwd
    key: someuser

- name: Display user info
  debug:
    var: getent_hosts
```
Would result in
```yaml
someuser:
  name: someuser
  uid: 100
  gid: 103
  homedir: /home/someuser
  description: "Some descriptive text"
```
