### ISSUE TITLE
"network_in_network" should be a jinja TEST

### ISSUE THREAD

**Issue by johnboy2** [ansible/ansible#47369]
##### SUMMARY
The `network_in_network` feature in `ipaddr.py` implements a _filter_ plugin which only ever returns a boolean. Arguably it should be a _test_ plugin instead.

##### ISSUE TYPE

 - Bug Report (?)
 - Feature Request (?)

##### COMPONENT NAME

ipaddr

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/johnn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

Ubuntu 18.04.1 LTS (controller)

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    subnets:
     - 10.0.0.0/8
     - 10.17.34.0/24
     - 192.168.0.0/24
    ip_address: '10.17.34.150'
  tasks:
    - vars:
        matches: '{{ subnets | select("network_in_network", ip_address) | list }}'
      block:
        - name: All matching subnets
          debug: var=matches

        - name: Closest matching subnet
          debug: var=nearest_subnet
          vars:
            nearest_subnet: '{{ matches | map("ipaddr", "prefix") | zip(matches) | max | last }}'
            # Alternative in case there is any chance that matches is an empty list: 
            # nearest_subnet: '{% if matches %}{{ matches | map("ipaddr", "prefix") | zip(matches) | max | last }}{% endif %}'
```

##### EXPECTED RESULTS

Matches shows `['10.0.0.0/8', '10.17.34.0/24']` (or similar)
Closest matching subnet shows `'10.17.34.0/24'`.

##### ACTUAL RESULTS

Play fails because `network_in_network` is a _filter_ rather than a test.
```
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ subnets | select(\"network_in_network\", ip_address) | list }}'. Error was a <class 'jinja2.exceptions.TemplateRuntimeError'>, original message: no test named 'network_in_network'"}
```

##### OTHER NOTES

The _only_ reason that the repro includes the "Closest matching subnet" debug statement is to fully demonstrate the use-case for `select()` with `network_in_network`.

Since `map()` uses filters rather than tests, it can work above in place of `select()` -- but then you are left with booleans -- and the non-trivial task of translating those into a limited list. It should be possible to just use `select()` for this.

It is straight-forward to work around the issue; see the attached `test_plugins/ipaddr-tests.py`.
[ipaddr-tests.zip](https://github.com/ansible/ansible/files/2497427/ipaddr-tests.zip)
