### ISSUE TITLE
include_tasks can also be used in the handlers: section.  Test  error

### ISSUE THREAD

**Issue by zsythink** [ansible/ansible#47392]
##### SUMMARY

Refer to the following article
[https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_includes.html](url)

include_tasks can also be used in the handlers: section.
After testing, the error was reported

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_tasks

##### ANSIBLE VERSION

```paste below
[root@test71 ansible]# ansible --version
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```paste below
nothing
```

##### OS / ENVIRONMENT

[root@test71 ansible]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 
[root@test71 ansible]# uname -a
Linux test71 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Execute the following playbook

```yaml

[root@test71 ansible]# cat intest2.yml 
---
- hosts: test70
  remote_user: root
  gather_facts: no
  tasks:
  - file: 
      path: /opt/test
      state: touch
    notify: test handlers
  
  handlers:
  - name: test handlers
    include_tasks : in3.yml


[root@test71 ansible]# cat in3.yml 
- debug:
    msg: "task1 in in.yml"
- debug:
    msg: "task2 in in.yml"

```

##### EXPECTED RESULTS

When handlers are called
Two debug tasks are executed

##### ACTUAL RESULTS

```paste below
[root@test71 ansible]# ansible-playbook intest2.yml

PLAY [test70] ********************************************************************************************************************************************************************

TASK [file] **********************************************************************************************************************************************************************
changed: [test70]

RUNNING HANDLER [test handlers] **************************************************************************************************************************************************
included: /testdir/ansible/in.yml for test70

RUNNING HANDLER [debug] **********************************************************************************************************************************************************
ok: [test70] => {
    "msg": "task1 in in.yml"
}
ERROR! Unexpected Exception, this is probably a bug: '0050562e-95d9-0177-48d1-000000000022'

```
