### ISSUE TITLE
Error passing correct license_model to rds_instance

### ISSUE THREAD

**Issue by dumblerod** [ansible/ansible#47405]
##### SUMMARY

When creating a new PostgreSQL instance in RDS using rds_instance module, I'm unable to pass in the correct license_model parameter.  Allowed parameters all give error message:
Unable to create DB instance: An error occurred (InvalidParameterCombination) when calling the CreateDBInstance operation: Invalid license model ''general-public-license'' for engine ''postgres''. Valid license models are: postgresql-license'
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

rds_instance.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/custom_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

[DEPRECATION WARNING]: DEFAULT_SQUASH_ACTIONS option, Loop squashing is deprecated and this configuration will no longer be used , use a list directly with the module argument instead. This feature will be removed in version 2.11.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 3
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_roles', u'profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/custom_modules']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles'']
DEFAULT_SQUASH_ACTIONS(/etc/ansible/ansible.cfg) = [u'apk', u'apt', u'dnf', u'package', u'pacman', u'pkgng', u'yum', u'zypper']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 20
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/.ssh/vault.key
```

##### OS / ENVIRONMENT

Not applicable

##### STEPS TO REPRODUCE

Execute the following playbook.

```yaml
- name: Test Play
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initial RDS instance creation
      rds_instance:
        id: "testRDS"
        engine: postgres
        engine_version: 9.6.9
        license_model: general-public-license
        allocated_storage: 30
        db_instance_class: db.m4.large
        master_username: rds
        master_user_password: password
        db_name: test_rds_delete
        db_subnet_group_name: rds_subnet_group
        vpc_security_group_ids: sg-65465465464
        auto_minor_version_upgrade: true
        backup_retention_period: 7
        copy_tags_to_snapshot: true
        storage_type: gp2
        wait: true
```

##### EXPECTED RESULTS

Expect to be able to create an RDS instance

##### ACTUAL RESULTS

Error when creating RDS instance due to unallowed parameter.

```paste below
TASK [Initial RDS instance creation] *******************************************************************************************************************************************************************
Sunday 21 October 2018  21:47:55 -0500 (0:00:00.098)       0:00:00.098 ********
Sunday 21 October 2018  21:47:55 -0500 (0:00:00.097)       0:00:00.097 ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: The general-public-license LicenseModel cannot be used for this configuration
fatal: [localhost]: FAILED! => changed=false
  boto3_version: 1.9.28
  botocore_version: 1.12.28
  error:
    code: InvalidParameterCombination
    message: The general-public-license LicenseModel cannot be used for this configuration
    type: Sender
  msg: 'Unable to modify DB instance: An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: The general-public-license LicenseModel cannot be used for this configuration'
  response_metadata:
    http_headers:
      connection: close
      content-length: '335'
      content-type: text/xml
      date: Mon, 22 Oct 2018 02:47:57 GMT
      x-amzn-requestid: 6afbc664-5fef-480b-b7b1-5139a3c9a13f
    http_status_code: 400
    request_id: 6afbc664-5fef-480b-b7b1-5139a3c9a13f
    retry_attempts: 0


When using license_model: postgresql-license I get following output:

TASK [Initial RDS instance creation] *******************************************************************************************************************************************************************
Sunday 21 October 2018  21:48:49 -0500 (0:00:00.092)       0:00:00.092 ********
Sunday 21 October 2018  21:48:49 -0500 (0:00:00.091)       0:00:00.091 ********
fatal: [localhost]: FAILED! => changed=false
  msg: 'value of license_model must be one of: license-included, bring-your-own-license, general-public-license, got: postgresql-license'
```
