### ISSUE TITLE
gcp_compute dynamic inventory doesn't properly handle keyed_groups separator key

### ISSUE THREAD

**Issue by flamein** [ansible/ansible#47413]
##### SUMMARY
Looking at https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/plugins/inventory/__init__.py#L334 the keyed_groups should support the following structure:
```yaml
    keyed_groups:
    - prefix: gcp
      separator: '-'
      keys: labels['group']
```
instead '\_' separator is used or overridden by Google API (as existing labels are also stripped of '-' in favor of '\_'

I am aware this key is not documented in the module: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/gcp_compute.py

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/gcp_compute.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /home/f_lamein/projects/ansible-devops/ansible.cfg
  configured module search path = [u'/home/f_lamein/projects/ansible-devops/library']
  ansible python module location = /home/f_lamein/PythonEnvironments/ansible-2.7/lib/python2.7/site-packages/ansible
  executable location = /home/f_lamein/PythonEnvironments/ansible-2.7/bin/ansible
  python version = 2.7.15 (default, Sep 21 2018, 23:26:48) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### CONFIGURATION

```paste below
irrelevant
```

##### STEPS TO REPRODUCE

ansible-inventory -i hosts.gcp.yml

```yaml
plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - europe-west4-a
projects:
  - dev
auth_kind: application
filters:
scopes:
  - https://www.googleapis.com/auth/compute
  - https://www.googleapis.com/auth/container
hostnames:
  - name
  - private_ip
  - public_ip
keyed_groups:
  - prefix: gc
    separator: '-'
    key: labels['group']
  - prefix: tag
    separator: '-'
    key: tags['items']
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  # ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  ansible_host: networkInterfaces[0].networkIP
```

##### EXPECTED RESULTS

Get groups with gc-dev-app.

##### ACTUAL RESULTS

Getting groups with gc_dev_app

```json
    "gc_dev_app": {
        "hosts": [
            "gc-dev-app0"
        ]
    }, 
```
