### ISSUE TITLE
vmware_host_datastore: Provide functionality to rename local datastore

### ISSUE THREAD

**Issue by mfish82** [ansible/ansible#47427]
##### SUMMARY

ESXi hosts use generic names for host datastores. Those are typically renamed by a user in an enterprise environment. Current module allows for management of that datastore, but not the ability to rename

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_host_datastore

##### ADDITIONAL INFORMATION

```
- name: Rename Datastores on ESXi host
  vmware_host_datastore:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter }}'
      datastore_name: datastore(1)
        rename: new_datastore_1
      esxi_hostname: '{{ inventory_hostname }}'
      state: present
```

**Comment by ansibot** [comment]
Hi @mfisher30, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_host_datastore.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_datastore.py)
* [lib/ansible/modules/system/hostname.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/hostname.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mfisher30, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ckotte** [comment]
This can be done via https://github.com/ansible/ansible/pull/40520. I already use it via:
```
- name: System & Storage | Gather datastore facts
  tags: always
  vmware_datastore_facts:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    datacenter_name: "{{ vcenter_datacenter if esxi_connect_via_vcenter else 'ha-datacenter' }}"
    gather_nfs_mount_info: False
    gather_vmfs_mount_info: False
    validate_certs: no
  register: datastore_facts
  no_log: "{{ esxi_no_log }}"
  delegate_to: localhost

- name: System & Storage | Rename local VMFS datastore
  tags: system, storage, local_datastore
  vmware_object_rename:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    name: "{{ item.name }}"
    new_name: "{{ inventory_hostname_short }}:local"
    object_type: 'Datastore'
    validate_certs: "{{ validate_vcenter_certs }}"
  delegate_to: localhost
  with_items: "{{ datastore_facts.datastores }}"
  ignore_errors: "{{ esxi_ignore_errors }}"
  when: item.type == "VMFS" and item.name | regex_search('^datastore')
```

This issue should be closed. I don't think it makes sense to implement the rename functionality in this module. The other module should be used instead.
