### ISSUE TITLE
vmware_host_ntp: Add ability to enable NTP

### ISSUE THREAD

**Issue by mfish82** [ansible/ansible#47428]
##### SUMMARY

Current module allows configuration of NTP, but does not enable NTP on the host. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_host_ntp

##### ADDITIONAL INFORMATION

```
- name: Set NTP setting for all ESXi Host in given Cluster
  vmware_host_ntp:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster_name: cluster_name
    state: present
    **enable: yes**
    ntp_servers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org

```

**Comment by mariolenz** [comment]
I've stumbled across exactly the same problem. But I'm not sure if this would really be a good idea: On the one hand, it would be easier to use ansible if I could configure NTP on an ESXi host and enable it at the same time; on the other hand, it would make ansible more complicated because the functionality of vmware_host_service_manager would be duplicated just for this one use case.

**Comment by ansibot** [comment]
Hi @mfisher30, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@mfisher30 What do you think about @mariolenz comment ? I have same opinion.

**Comment by mfish82** [comment]
@Akasurde I disagree. Why make two different calls to a device when you can make one call on the same module to accomplish the same thing? With large enterprise deployments like we do, the potential for socket errors and memory overuse (which we've encountered before), can be avoided by doing more with less module use.

Additionally, the vmware_host_service_manager module can accomplish much more than just enabling NTP. I don't see how it would make Ansible more complicated by adding a single parameter to the NTP module.  Actually, the current situation makes Ansible more complicated by having to use 2 modules to configure and enable NTP. Seems counter-intuitive.

**Comment by mariolenz** [comment]
> I don't see how it would make Ansible more complicated by adding a single parameter to the NTP
> module. Actually, the current situation makes Ansible more complicated by having to use 2 modules
> to configure and enable NTP. Seems counter-intuitive.

Well, yes and no. The feature you suggest would make ansible easier to *use* but make its code base *more complex*. That's what I wanted to say.

**Comment by ckotte** [comment]
I use this with a large enterprise deployment:
```
- name: System | Configure NTP
  tags: system, ntp, advanced_setting
  vmware_host_ntp:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    ntp_servers: "{{ ntp_servers }}"
    verbose: "{{ esxi_verbose }}"
    validate_certs: "{{ validate_vcenter_certs }}"
  ignore_errors: "{{ esxi_ignore_errors }}"
  delegate_to: localhost

# need to be done after NTP configuration to avoid the error 'an error occurred during host configuration' on a fresh ESXi host
- name: System | Enable and start NTP
  tags: system, service, ntp
  vmware_host_service_manager:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    service_name: "ntpd"
    service_policy: "on"
    state: "start"
    validate_certs: "{{ validate_vcenter_certs }}"
  ignore_errors: "{{ esxi_ignore_errors }}"
  delegate_to: localhost
```

You need to use dozens of tasks/modules anyway if you want to configure "everything" on an ESXi host. One module less doesn't make a difference.

You would need to duplicate the code in `vmware_host_service_manager` to have this functionality in `vmware_host_ntp`. It's not just enable yes/no. What should you do if you want the startup policy to start and stop with port usage?

This doesn't make any sense. This issue should be closed.
