### ISSUE TITLE
Ansible WAF condition module is hanging for a long period of time

### ISSUE THREAD

**Issue by GavrielNsof** [ansible/ansible#47473]
##### SUMMARY
Ansible WAF condition module is hanging for a long period of time while boto3 does the same job immediately.

It seems that the Ansible module is waiting for the update to finish, is there a way not to wait for the update?

Also, if I cancel the playbook after 3 seconds of waiting and I run it again it doesn't hang and the IP condition is updated as I wanted.

##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
aws_waf_condition

##### ANSIBLE VERSION
Ansible 2.6.5

##### CONFIGURATION
  config file = /Users/.ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lib/python2.7/site-packages/ansible
  executable location = /Users/ansible/bin/ansible

##### OS / ENVIRONMENT
Ubuntu 16.04 or macOS 10.13.5
python 2.7.15

##### STEPS TO REPRODUCE
Make sure you have AWS WAF with this IP condition: "example_ips"
Then run this module:
```
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:

  name: Update AWS WAF
  aws_waf_condition:
    region: "us-east-1"
    name: "example_ips"
    filters:
      - ip_address: "1.1.1.1/32"
    type: ip
    purge_filters: true
```

##### EXPECTED RESULTS
Updating the WAF condition with the relevant IPs immediately, without waiting
