### ISSUE TITLE
win_domain_membership:

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#47497]
##### SUMMARY
The following task

```yaml
- name: Join system to the domain
  win_domain_membership:
    dns_domain_name: '{{ local_domain }}'
    hostname: '{{ windows_shortname }}'
    domain_admin_user: '{{ windows_domain }}\{{ windows_admin_user }}'
    domain_admin_password: '{{ windows_admin_password }}'
    log_path: C:\Windows\Temp\ad_join_log.txt
    state: domain
  register: domain_state
```

Causes this error:
```
failed to join domain: Computer 'RAMSES-REU6T33J' was successfully joined to the new domain 'pod11vmm.aci.lab', but renaming it to 'c220m4-2' failed with the following error message: The account already exists.
```

This can be avoided by first renaming and rebooting the server, but since **win_domain_membership** reports it can rename a server, I would prefer to avoid an additional reboot.

In this case I have no clue what "The account already exists." really means, because that system has a unique system name which was not joined before.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
v2.8 and older

##### OS / ENVIRONMENT
controller: CentOS 7.5
target: Windows Server 2012 R2

##### STEPS TO REPRODUCE
Rename a system when you're joining. Potentially doing this twice with a reinstalled system using the same target name.

##### EXPECTED RESULTS
It works, or at least continues with no error.

##### ACTUAL RESULTS
Fails with:
```yaml
Failed: {
    "_ansible_parsed": true, 
    "_ansible_no_log": false, 
    "msg": "failed to join domain: Computer 'RAMSES-REU6T33J' was successfully joined to the new domain 'pod11vmm.aci.lab', but renaming it to 'c220m4-2' failed with the following error message: The account already exists.", 
    "changed": true, 
   "reboot_required": false
}
```
