### ISSUE TITLE
tags not working on post_tasks include?

### ISSUE THREAD

**Issue by davestern** [ansible/ansible#4750]
I have this playbook:

```

---
# Admin Playbook
- hosts: admin
  user: username
  sudo: yes
  roles:
    - common
    - admin
  post_tasks:
    - include: roles/admin/tasks/test.yml tags=test
```

But when I try to run just the tests, I get this output:

```
$ ansible-playbook -i hosts playbook-admin.yml -t test
ERROR: tag(s) not found in playbook: test.  possible values: apache,config,crontab
```

Tags do not appear to work in post_tasks: include files
