### ISSUE TITLE
Cannot add multiple ports in a Target group

### ISSUE THREAD

**Issue by ptselios-inmarsat** [ansible/ansible#47504]
##### SUMMARY
The way module is implemented it checks only if a specific host exists in the targets. If a host exists, it modifies it's entry. 
So, if I want to add multiple hosts that listen on different ports (eg 8080 & 8088), I cannot. 
Meaning, the module is restricted to one host one port at a time. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION

```paste below
2.7.0
```

##### CONFIGURATION

```paste below
No change
```

##### OS / ENVIRONMENT

Fedora 28, managing AWS

##### STEPS TO REPRODUCE

This is an example playbook:

```yaml

alb_target_port: 
  - 8080
  - 8088
my_instances:
  - id-xxxxxxxxx
  - id-yyyyyyy

- name: Create Target Group
  elb_target_group:
    name: "{{ alb_target_name }}"
    protocol: "{{ alb_protocol }}"
    port: "{{ alb_port }}"
    vpc_id: "{{ aws_vpc_id }}"
    health_check_path: /
    successful_response_codes: "200, 301"
    targets:
      - Id: "{{ item.0.id }}"
        Port: "{{ item.1|int }}"
    healthy_threshold_count: 3
    unhealthy_threshold_count: 2
    stickiness_enabled: true
    state: present
    purge_tags: true
    tags: '{{alb_tg_prom_tags}}'
  loop: '{{ my_instances |product(alb_target_port) | list }}'
```

##### EXPECTED RESULTS

Module should add all hosts/ports combinations. 

##### ACTUAL RESULTS

Module creates the Target Group but adds only last port for each host/port combination. 
 

```paste below

```
