### ISSUE TITLE
java_keystore module is not working when private key has a passphrase

### ISSUE THREAD

**Issue by fgiorgetti** [ansible/ansible#47525]
##### SUMMARY
The java_keystore module does not work when my private certificate has a passphrase (without a passphrase, it is working as expected). It hangs waiting for the passphrase to be entered via stdin.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
java_keystore

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /home/myuser/.ansible.cfg
  configured module search path = [u'/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/myuser/.ansible.cfg) = [u'/home/myuser/.ansible.hosts']
```

##### OS / ENVIRONMENT

OS: RHEL 7 x86_64
Python: 2.7.5
Tested using both: latest version (2.7) and from devel branch (2.8.0.dev0).

##### STEPS TO REPRODUCE

ansible-playbook playbook.yml

```
- hosts: localhost
  tasks:
    - java_keystore:
        certificate: "{{lookup('file', '/tmp/cert.pem') }}"
        private_key: "{{lookup('file', '/tmp/cert.key') }}"
        password: mypassword
        dest: /tmp/myuser.keystore
        name: myalias 
        force: yes
```

##### EXPECTED RESULTS

Keystore created and key/cert imported.

##### ACTUAL RESULTS

Ansible hangs as it waits for existing private key passphrase from stdin.

```
TASK [java_keystore] **********************************************************************************************************************************************************************************************
Enter pass phrase for /tmp/cert.key:
```

**Comment by ansibot** [comment]
Hi @fgiorgetti, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/java_keystore.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/java_keystore.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Mogztter
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ggrossetie** [comment]
Hello @fgiorgetti 
I guess we could add the passphrase as an attribute `private_key_passphrase` ?

```yml
- hosts: localhost
  tasks:
    - java_keystore:
        certificate: "{{lookup('file', '/tmp/cert.pem') }}"
        private_key: "{{lookup('file', '/tmp/cert.key') }}"
        private_key_passphrase: mypassphrase
        password: mypassword
        dest: /tmp/myuser.keystore
        name: myalias 
        force: yes
```

What do you think ?

**EDIT**: I just saw that you've already opened a pull request :wink:
