### ISSUE TITLE
NIOS Deletes identical record in secondary View

### ISSUE THREAD

**Issue by coreywan** [ansible/ansible#47531]
##### SUMMARY

When testing functionality of the `nios_cname_record`  module, one of my team members noticed that if you want to apply the same CNAME record into two or more views, it will remove the previous CNAME record from the other DNS view.  In our case, we want to have a CNAME record present in our External view, and Internal DNS View. 

 Looking through the code, it looks like this will be an issue for all DNS record types except for the HOST record which has this built in to the module util.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios_cname_record
##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /Users/wanlessc/innovate/tmp/ansible.cfg
  configured module search path = [u'/Users/wanlessc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/wanlessc/miniconda2/envs/ansible2.7/lib/python2.7/site-packages/ansible
  executable location = /Users/wanlessc/miniconda2/envs/ansible2.7/bin/ansible
  python version = 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: Creates record in internal view
      nios_cname_record:
        canonical: hostrec.domain.com
        name: coreytest.domain.com
        view: Internal
        provider: "{{provider}}"

    - name: Creates record in external view (and is deleting the record in the Internal view)
      nios_cname_record:
        canonical: hostrec.domain.com
        name: coreytest.domain.com
        view: External
        provider: "{{provider}}"
```

##### EXPECTED RESULTS

Create two DNS Records. One in the Internal View, and one in the External View

##### ACTUAL RESULTS

```paste below

```
