### ISSUE TITLE
k8s module documentation does not explain authentication logic sufficiently which leads to unexpected behaviour when running from inside kubernetes 

### ISSUE THREAD

**Issue by FilipB** [ansible/ansible#47556]
##### SUMMARY

When running playbook from OpenShift pod the ~/.kube/config.json file is not used and the task is executed against local OpenShift. It was working fine in ansible-2.5.7-1
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s
##### ANSIBLE VERSION

```paste below
ansible-playbook 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
Empty
```

##### OS / ENVIRONMENT

OpenShift v3.9.30 
openshift/jenkins-slave-base-centos7 docker image with ansible and oc installed
##### STEPS TO REPRODUCE

1. start the pod
2. oc login https://b12.jonqe.lab.eng.bos.redhat.com:8443 -u=jenkins -p=******** --insecure-skip-tls-verify
3. cp /var/lib/origin/openshift.local.config/master/admin.kubeconfig .kube/config.json
3. ansible-playbook install_bookinfo.yml -vvv

```yaml
- name: Install Bookinfo with or without Kiali Traffic Generator
  hosts: localhost
  tasks:
    - name: Define Bookinfo Namespace if is not defined
      set_fact:
        bookinfo_namespace: 'bookinfo'
      when: bookinfo_namespace is not defined

    - name: Define Rename Label if is not defined
      set_fact:
        rename_label: ''
      when: rename_label is not defined

    - name: Delete Test Bookinfo Project
      k8s:
        api_version: v1
        kind: Project
        name: "{{ item }}"
        state: absent
        verify_ssl: false
      ignore_errors: true
      with_items:
        - "{{ bookinfo_namespace }}"

    - name: Create Bookinfo Project
      k8s:
        api_version: v1
        kind: Project
        name: "{{ item }}"
        state: present
        verify_ssl: false
      register: projectStatus
      until: projectStatus.changed == true
      retries: 100
      delay: 20
      with_items:
        - "{{ bookinfo_namespace }}"
```

##### EXPECTED RESULTS

The bookinfo project should be created on b12.jonqe.lab.eng.bos.redhat.com

##### ACTUAL RESULTS

The bookinfo project is created on local openshift where the pod is running.
Content of kube config:
```
h-4.2$ cat .kube/config.json
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://b12.jonqe.lab.eng.bos.redhat.com:8443
  name: b12-jonqe-lab-eng-bos-redhat-com:8443
contexts:
- context:
    cluster: b12-jonqe-lab-eng-bos-redhat-com:8443
    namespace: default
    user: jenkins/b12-jonqe-lab-eng-bos-redhat-com:8443
  name: default/b12-jonqe-lab-eng-bos-redhat-com:8443/jenkins
current-context: default/b12-jonqe-lab-eng-bos-redhat-com:8443/jenkins
kind: Config
preferences: {}
users:
- name: jenkins/b12-jonqe-lab-eng-bos-redhat-com:8443
  user:
    token: ******
```

```paste below
sh-4.2$ ansible-playbook install_bookinfo.yml -vvv
ansible-playbook 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: install_bookinfo.yml *********************************************************************************************************************************************************************************************************
1 plays in install_bookinfo.yml

PLAY [Install Bookinfo with or without Kiali Traffic Generator] ************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************
task path: /home/jenkins/install_bookinfo.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: default
<127.0.0.1> EXEC /bin/sh -c 'echo ~default && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482 `" && echo ansible-tmp-1540379285.86-83440645787482="` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /home/jenkins/.ansible/tmp/ansible-local-1928WyCu23/tmpNK8AKo TO /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482/ /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jenkins/.ansible/tmp/ansible-tmp-1540379285.86-83440645787482/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Define Bookinfo Namespace if is not defined] *************************************************************************************************************************************************************************************
task path: /home/jenkins/install_bookinfo.yml:6
ok: [localhost] => {
    "ansible_facts": {
        "bookinfo_namespace": "bookinfo"
    },
    "changed": false
}

TASK [Define Rename Label if is not defined] *******************************************************************************************************************************************************************************************
task path: /home/jenkins/install_bookinfo.yml:11
ok: [localhost] => {
    "ansible_facts": {
        "rename_label": ""
    },
    "changed": false
}

TASK [Delete Test Bookinfo Project] ****************************************************************************************************************************************************************************************************
task path: /home/jenkins/install_bookinfo.yml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: default
<127.0.0.1> EXEC /bin/sh -c 'echo ~default && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643 `" && echo ansible-tmp-1540379293.31-128088653619643="` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /home/jenkins/.ansible/tmp/ansible-local-1928WyCu23/tmpxZZjbS TO /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643/ /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jenkins/.ansible/tmp/ansible-tmp-1540379293.31-128088653619643/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item=bookinfo) => {
    "changed": true,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "absent",
            "username": null,
            "verify_ssl": false
        }
    },
    "item": "bookinfo",
    "method": "delete",
    "result": {
        "apiVersion": "v1",
        "kind": "Status",
        "metadata": {},
        "status": "Success"
    }
}

TASK [Create Bookinfo Project] *********************************************************************************************************************************************************************************************************
task path: /home/jenkins/install_bookinfo.yml:27
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: default
<127.0.0.1> EXEC /bin/sh -c 'echo ~default && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196 `" && echo ansible-tmp-1540379295.55-277736799231196="` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /home/jenkins/.ansible/tmp/ansible-local-1928WyCu23/tmpnkpeMN TO /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196/ /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jenkins/.ansible/tmp/ansible-tmp-1540379295.55-277736799231196/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: Create Bookinfo Project (100 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "diff": [],
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": false
        }
    },
    "method": "patch",
    "result": {
        "apiVersion": "v1",
        "kind": "Project",
        "metadata": {
            "annotations": {
                "openshift.io/description": "",
                "openshift.io/display-name": "",
                "openshift.io/requester": "system:serviceaccount:jenkins-slaves:default",
                "openshift.io/sa.scc.mcs": "s0:c21,c10",
                "openshift.io/sa.scc.supplemental-groups": "1000440000/10000",
                "openshift.io/sa.scc.uid-range": "1000440000/10000"
            },
            "creationTimestamp": "2018-10-24T11:03:35Z",
            "deletionTimestamp": "2018-10-24T11:08:15Z",
            "name": "bookinfo",
            "resourceVersion": "34934445",
            "selfLink": "/oapi/v1/projects/bookinfo",
            "uid": "739ad7ef-d77c-11e8-b69b-ecf4bbc1e3dc"
        },
        "spec": {
            "finalizers": [
                "kubernetes"
            ]
        },
        "status": {
            "phase": "Terminating"
        }
    },
    "retries": 101
}
<127.0.0.1> EXEC /bin/sh -c 'echo ~default && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366 `" && echo ansible-tmp-1540379317.33-264616536352366="` echo /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /home/jenkins/.ansible/tmp/ansible-local-1928WyCu23/tmpiKgqBV TO /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366/ /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jenkins/.ansible/tmp/ansible-tmp-1540379317.33-264616536352366/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item=bookinfo) => {
    "attempts": 2,
    "changed": true,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": false
        }
    },
    "item": "bookinfo",
    "method": "create",
    "result": {
        "apiVersion": "v1",
        "kind": "Project",
        "metadata": {
            "annotations": {
                "openshift.io/description": "",
                "openshift.io/display-name": "",
                "openshift.io/requester": "system:serviceaccount:jenkins-slaves:default",
                "openshift.io/sa.scc.mcs": "s0:c21,c15",
                "openshift.io/sa.scc.supplemental-groups": "1000450000/10000",
                "openshift.io/sa.scc.uid-range": "1000450000/10000"
            },
            "creationTimestamp": "2018-10-24T11:08:38Z",
            "name": "bookinfo",
            "resourceVersion": "34934519",
            "selfLink": "/oapi/v1/projectrequests/bookinfo",
            "uid": "28bf1762-d77d-11e8-b69b-ecf4bbc1e3dc"
        },
        "spec": {
            "finalizers": [
                "openshift.io/origin",
                "kubernetes"
            ]
        },
        "status": {
            "phase": "Active"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=0

```
