### ISSUE TITLE
show feedback when using "ec2_asg" and doing a rolling restart with "replace_all_instances"

### ISSUE THREAD

**Issue by biohazd** [ansible/ansible#47555]
##### SUMMARY
Is it possible to show feedback when using "ec2_asg" and doing a rolling restart with "replace_all_instances". Currently if there are alot of Instances the play will run and not report anything until its all finished. Can it list the Instances as they are recycled.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
!ec2_asg

##### ADDITIONAL INFORMATION
The play just sits there and doesn't report as its rebooting the instances. It would be nice to see which instances have been rebooted and the order they are replaced in real-time.

```yaml
- name: change launch config and do a rolling restart of servers
  ec2_asg:
    name: "{{ asg_maybe.results[0].auto_scaling_group_name }}"
    launch_config_name: "{{ asg_maybe.results[0].launch_config_name }}"
    min_size: "{{ asg_maybe.results[0].min_size | int }}"
    max_size: "{{ asg_maybe.results[0].max_size | int }}"
    desired_capacity: "{{ asg_maybe.results[0].desired_capacity | int }}"
    replace_all_instances: yes
    target_group_arns: "{{ asg_maybe.results[0].target_group_arns | default([]) }}"
    replace_batch_size: 1
    health_check_type: ELB


```
