### ISSUE TITLE
vmware_host: ESXi servers failed to be added to vCenter

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#47563]
##### SUMMARY
Since updating to Ansible 2.7 hosts are failing to be added into vCenter with the message;

```
"msg": "Failed to add host <HOSTNAME.FQDN> to vCenter: Authenticity of the host's SSL certificate is not verified."
```

All other vmware_*.py modules I consume (I use a lot of them) are working ok with Ansible 2.7

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host.py

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /home/nick/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/home/nick/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
DEFAULT

##### OS / ENVIRONMENT
Ansible run environment: CentOS7
Target vCenter: 6.7
Target ESXi 6.7

##### STEPS TO REPRODUCE

**IMPORTANT** Only use an ESXi host that the target vCenter hasn't interacted with before or hasn't accepted an SSL thumbprint from the ESXi host.

Both playbooks below fail.

Adding to a cluster
```
- name: 'Add ESXi host to vCenter'
  connection: 'local'
  vmware_host:
    hostname: '{{ vcenter }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    datacenter_name: '{{ pod_name }}'
    cluster_name: '{{ cluster_name }}'
    esxi_hostname: '{{ ansible_host }}'
    esxi_username: '{{ esxi_root_account }}'
    esxi_password: '{{ esxi_password }}'
    state: 'present'
    validate_certs: '{{ validate_certs }}'

```

Adding to just the Datacenter
```
- name: 'Add ESXi host to vCenter'
  connection: 'local'
  vmware_host:
    hostname: '{{ vcenter }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    datacenter_name: '{{ pod_name }}'
    folder: '{{ dc_name }}/host'
    esxi_hostname: '{{ ansible_host }}'
    esxi_username: '{{ esxi_root_account }}'
    esxi_password: '{{ esxi_password }}'
    state: 'present'
    validate_certs: '{{ validate_certs }}'
```

If I specify the thumbprint in the playbook then it works. It appears the module is failing to force add the host.

If the host is removed and then added without specifying the SSL thumbprint then it works.

I've built a new CentOS7 server with Ansible 2.7 from scratch to rule out issues with an inplace upgrade of Ansible and the above still fails.

The previous version of Ansible I was using and where this works is 2.6.2

##### EXPECTED RESULTS
The ESXi host is added to vCenter despite the SSL thumbprint not being specified.

##### ACTUAL RESULTS

```
TASK [add_esxi_to_vcenter_datacenter : Add ESXi host to vCenter] ***********************************************************************************************************************************************************************************************************************
task path: <PATH TO PLAYBOOK>/vmware-ansible/roles/add_esxi_to_vcenter_datacenter/tasks/main.yml:1

<HOSTNAME.FQDN> ESTABLISH LOCAL CONNECTION FOR USER: <ME>
<HOSTNAME.FQDN> EXEC /bin/sh -c 'echo ~<ME> && sleep 0'
<HOSTNAME.FQDN> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo <PATH TO PLAYBOOK>.ansible/tmp/ansible-tmp-1540388469.44-25217277322162 `" && echo ansible-tmp-1540388469.44-25217277322162="` echo <PATH TO PLAYBOOK>/.ansible/tmp/ansible-tmp-1540388469.44-25217277322162 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_host.py
<HOSTNAME.FQDN> PUT <PATH TO PLAYBOOK>.ansible/tmp/ansible-local-56562_BWcpr/tmpmcoEie TO <PATH TO PLAYBOOK>.ansible/tmp/ansible-tmp-1540388469.44-25217277322162/AnsiballZ_vmware_host.py
<HOSTNAME.FQDN> EXEC /bin/sh -c 'chmod u+x <PATH TO PLAYBOOK>.ansible/tmp/ansible-tmp-1540388469.44-25217277322162/ <PATH TO PLAYBOOK>.ansible/tmp/ansible-tmp-1540388469.44-25217277322162/AnsiballZ_vmware_host.py && sleep 0'
<HOSTNAME.FQDN> EXEC /bin/sh -c '/usr/bin/python <PATH TO PLAYBOOK>.ansible/tmp/ansible-tmp-1540388469.44-25217277322162/AnsiballZ_vmware_host.py && sleep 0'
<HOSTNAME.FQDN> EXEC /bin/sh -c 'rm -f -r <PATH TO PLAYBOOK>.ansible/tmp/ansible-tmp-1540388469.44-25217277322162/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_host_payload_WOvEyN/__main__.py", line 258, in add_host_to_vcenter
    success, result = wait_for_task(task)
  File "/tmp/ansible_vmware_host_payload_WOvEyN/ansible_vmware_host_payload.zip/ansible/module_utils/vmware.py", line 59, in wait_for_task
    raise_from(TaskError(error_msg), task.info.error)
  File "/tmp/ansible_vmware_host_payload_WOvEyN/ansible_vmware_host_payload.zip/ansible/module_utils/six/__init__.py", line 744, in raise_from
    raise value

fatal: [HOSTNAME.FQDN]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "add_connected": true,
            "cluster_name": null,
            "datacenter_name": "<DATACENTER NAME>",
            "esxi_hostname": "<HOSTNAME.FQDN>",
            "esxi_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "esxi_ssl_thumbprint": "",
            "esxi_username": "root",
            "folder": "<DATACENTER NAME>/host",
            "hostname": "<VCENTER.FQDN>",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "<USERNAME>",
            "validate_certs": false
        }
    },
    "msg": "Failed to add host HOSTNAME.FQDN to vCenter: Authenticity of the host's SSL certificate is not verified."
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
HOSTNAME.FQDN : ok=0    changed=0    unreachable=0    failed=1

```
