### ISSUE TITLE
Expose .__class__.__name__  as a filter for easier variable validation

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#47566]
##### SUMMARY

Sometimes it is handy to validate variables by their type, or process them conditionally depending on their type. Current filters and tests provided by ansible/jinja2 are a bit cumbersome in this regard.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

filters
##### ADDITIONAL INFORMATION

For example, it would be cool to check if a var is a string, list or a dict directly, rather than chain tests

```yaml
- name: ensure var types
  assert:
    that:
      # current available tests
      - some_int is ?
      - some_float is ?
      - some_string is string
      - some_list is iterable and some_list is not string
      - some_dict is mapping

      # direct python references
      - some_int.__class__.__name__ == 'int'
      - some_float.__class__.__name__ == 'float'
      - some_string.__class__.__name__ == 'str'
      - some_list.__class__.__name__ in [ 'list', 'tuple' ]
      - some_dict.__class__.__name__ == 'dict'

      # feature request
      - some_int | vartype == 'int'
      - some_float | vartype == 'float'
      - some_string | vartype == 'str'
      - some_list | vartype in [ 'list', 'tuple' ]
      - some_dict | vartype == 'dict'

```
Meanwhile, is the usage of `.__class__.__name__` can be considered a valid workaround in a sense that it will continue to reliably work in ansible for some time?
