### ISSUE TITLE
How do I use group_vars with gcp_compute dynamic inventory?

### ISSUE THREAD

**Issue by walterdolce** [ansible/ansible#47574]
##### SUMMARY
Relates to #47573 

The following doesn't work:
```
# foo.gcp.yml
---
plugin: gcp_compute
projects:
  - theproject
filters:
- name = theinstancename
scopes:
- https://www.googleapis.com/auth/compute
service_account_file: path/to/json
auth_kind: serviceaccount
all:
  children:
    theproject:
```

Nor does the following:
```
# foo.gcp.yml
---
plugin: gcp_compute
projects:
  - theproject
filters:
- name = theinstancename
scopes:
- https://www.googleapis.com/auth/compute
service_account_file: path/to/json
auth_kind: serviceaccount
groups:
   theproject:
```

Dir structure is as follows:
```
group_vars/
   theproject/
      theproject.yml
      vault
foo.gcp.yml
playbook.yml
roles/
   # ...

```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
gcp_compute

##### ANSIBLE VERSION
The latest at this time of writing

##### CONFIGURATION
Not relevant

##### OS / ENVIRONMENT
Not relevant

##### ADDITIONAL INFORMATION
