### ISSUE TITLE
when conditionals on meta entries are evaluated when they should be ignored

### ISSUE THREAD

**Issue by tkellen** [ansible/ansible#47578]
##### SUMMARY
Conditionals on meta entries are evaluated even when tags used by operator indicate they should be ignored.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
meta

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tkellen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]

```

##### CONFIGURATION
```paste below
n/a
```

##### OS / ENVIRONMENT
```
➜ uname -a
Linux devbox 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
```
cat > test.yml <<EOF
- hosts: all
  connection: local
  tasks:
    - name: register a variable
      shell: echo test
      register: var
      tags: test

    - meta: end_play
      when: var.stdout == "test"
      tags: test
EOF
ansible-playbook -i localhost, test.yml --tags nope
```

##### EXPECTED RESULTS
Ansible exits 0 and runs no tasks.

##### ACTUAL RESULTS
Ansible exits 1 with this failure:

```
ERROR! The conditional check 'var.stdout == "test"' failed. The error was: error while evaluating conditional (var.stdout == "test"): 'var' is undefined

The error appears to have been in '/home/tkellen/sources/test.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - meta: end_play
      ^ here
```
