### ISSUE TITLE
Hash support for ios_user

### ISSUE THREAD

**Issue by pffs** [ansible/ansible#47577]
##### SUMMARY

Currently ios_user only supports the ability to set passwords on account creation or every time. It would be useful to be able to have an option to be able to supply a hash to the ios_user module in order to determine if the password needed to be changed as IOS hashes are portable between devices (assuming the version supports the type of hash, but that could be handled elsewhere by verifying IOS version).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ios_user

##### ADDITIONAL INFORMATION

Optional 

```yaml
- ios_user:
    name: username
    state: present
    configured_password:
      type: 5
      value: $1$1JDe$IcYgCYy.yz4ApbpkHG0.2/
```
