### ISSUE TITLE
variable declaration broken in 2.7

### ISSUE THREAD

**Issue by corbinstuard** [ansible/ansible#47585]
##### SUMMARY

As of 2.7, Ansible is declaring variables as true that I'm not declaring anywhere in my playbook or inventory. This issue wasn't present in 2.6.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
```paste below
ansible 2.6.6.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible2.6/lib/python2.7/site-packages/ansible
  executable location = ./ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=2000s -o UserKnownHostsFile=/de
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = /tmp
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 5
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/filter_plugins']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- name: update inventory
  hosts: all, !docker-df, !docker-callp
  connection: local
  serial: 1

  tasks:
  - import_role:
      name: inventory
    vars:
      external: true
```
```yaml
- debug:
    var: external
- debug:
    var: internal
- debug:
    var: docker

- name: update inventory with external ip's
  replace:
    dest: "{{ inventory_file }}"
    regexp: '^{{ inventory_hostname }}(?![\w-]).*$'
    replace: '{{ inventory_hostname }} ansible_host={{ newvm.instance.ipv4 }}'
  when: external is defined

- name: update inventory with internal ip's
  replace:
    dest: "{{ inventory_file }}"
    regexp: '^{{ inventory_hostname }}(?![\w-]).*$'
    replace: '{{ inventory_hostname }} ansible_host={{ hostvars[inventory_hostname].network[0].ipv4[0].ip }}'
  when: internal is defined and 'router' not in group_names

- name: update inventory with docker host ip's
  replace:
    dest: "{{ inventory_file }}"
    regexp: '^{{ inventory_hostname }}(?![\w-]).*$'
    replace: '{{ inventory_hostname }} ansible_host={{ hostvars[vtc.docker_host].network[0].ipv4[0].ip }}'
  when: docker is defined

- meta: refresh_inventory

```

##### ACTUAL RESULTS

2.6 results:
```paste below
PLAY [update inventory] ********************************************************************************************
 
TASK [inventory : debug] *******************************************************************************************
ok: [dps1-rhelno] => {
    "external": true
}
 
TASK [inventory : debug] *******************************************************************************************
ok: [dps1-rhelno] => {
    "internal": "VARIABLE IS NOT DEFINED!"
}
 
TASK [inventory : debug] *******************************************************************************************
ok: [dps1-rhelno] => {
    "docker": "VARIABLE IS NOT DEFINED!"
}
 
TASK [inventory : update inventory with external ip's] *************************************************************
changed: [dps1-rhelno]
 
TASK [inventory : update inventory with internal ip's] *************************************************************
skipping: [dps1-rhelno]
 
TASK [inventory : update inventory with docker host ip's] **********************************************************
skipping: [dps1-rhelno]
```
2.7 results:
```paste below
ok: [dps1-rhelno] => {
    "external": true
}
 
TASK [inventory : debug] *******************************************************************************************
ok: [dps1-rhelno] => {
    "internal": true
}
 
TASK [inventory : debug] *******************************************************************************************
ok: [dps1-rhelno] => {
    "docker": true
}
 
TASK [inventory : update inventory with external ip's] *************************************************************
changed: [dps1-rhelno]
 
TASK [inventory : update inventory with internal ip's] *************************************************************
changed: [dps1-rhelno]
 
TASK [inventory : update inventory with docker host ip's] **********************************************************
fatal: [dps1-rhelno]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'vtc' is undefined\n\nThe error appears to have been in '/etc/ansible/roles/inventory/tasks/main.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: update inventory with docker host ip's\n  ^ here\n"}
```
