### ISSUE TITLE
Fastly Ansible Module

### ISSUE THREAD

**Issue by cahlchang** [ansible/ansible#47609]
##### SUMMARY
Fastly Ansible Module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

fastly

##### ADDITIONAL INFORMATION

I would like to do CDN operations on Ansible.
Fastly has code of VCL among CDN vendors so I think that there is a special benefit of coding.
Since there is an API, it can be implemented.

```yaml
- fastly:
    name: "{{ name }}"
    api_key: "{{ api_key }}"
    resource: fastly_service_v1
    domain:
      name: "{{ domain_name }}"
      comment: "{{ domain_coment }}"
    vcl: "{{ lookup('file', VCL_FILE_PATH) }}"
```

see API
https://docs.fastly.com/api/
