### ISSUE TITLE
make: add output module option to specify output target

### ISSUE THREAD

**Issue by zhelanov** [ansible/ansible#47648]
##### SUMMARY
For now when I try to do 'make' with loop my target's result will be overridden by the last iteration

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
make module

##### ADDITIONAL INFORMATION
It would be good to have an additional parameter such as 'dest' to specify where to move builded target.
Example:
```
- name: Generate something
  make:
    chdir: "{{ src_path }}"
    target: all
    dest" "/tmp/{{ item }}"
    params:
      EMBED: "{{ item }}"
  with_items:
  - 'some_file.txt'
  - 'another_file.txt'
  - 'and_another_one.txt'
```
As a result I want to have 3 build, but I have only last one so it's necessary to add 'dest'/'move_to' parameter to this module
