### ISSUE TITLE
win_chocolatey hangs during first run when using a proxy

### ISSUE THREAD

**Issue by benschweizer** [ansible/ansible#47669]
##### SUMMARY
powershell execution of win_chocolatey hangs during first install using a proxy server
when a choco.exe is missing, it gets bootstraped by win_chocolatey but this step hangs; if the initial install of choco.exe is performed without a proxy, later package installs using win_chocolatey work as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```paste below
ansible 2.7.1
  config file = /home/bsc@dst-its.de/.ansible.cfg
  configured module search path = [u'/home/bsc@dst-its.de/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/2.7.1/local/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/2.7.1/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### CONFIGURATION
```paste below
DEFAULT_LOG_PATH(/home/bsc@dst-its.de/.ansible.cfg) = /home/bsc@dst-its.de/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/bsc@dst-its.de/.ansible.cfg) = [u'/etc/ansible/lookup_plugins']
RETRY_FILES_ENABLED(/home/bsc@dst-its.de/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible runs with python2 on Debian9
Target is Windows Server 2016

##### STEPS TO REPRODUCE

```yaml
- hosts: 10.56.100.203

  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_scheme: http
    ansible_port: 5985
    ansible_user: someone
    ansible_password: s3cr3t

  tasks:
    - name: install chocolatey packages
      win_chocolatey:
        name: sysinternals
        state: present
        proxy_url: http://proxy:3128
```

##### EXPECTED RESULTS
choco.exe should be installed during first use of win_chocolatey

##### ACTUAL RESULTS
proxy connection works, ansiball is making a first download of https://chocolatey.org/install.ps1
though, the task runs forever while the module timeout parameter has no effect, neither have other timeouts any effect

```paste below
[...]

PLAY [10.56.100.203] *********************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************
task path: /home/bsc@dst-its.de/ansible/playbooks/test.yml:1
Using module file /opt/ansible/2.7.1/local/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<10.56.100.203> ESTABLISH WINRM CONNECTION FOR USER: dst on PORT 5985 TO 10.56.100.203
checking if winrm_host 10.56.100.203 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [10.56.100.203]
META: ran handlers

TASK [install chocolatey packages] *******************************************************************************************************************************************
task path: /home/bsc@dst-its.de/ansible/playbooks/test.yml:12
Using module file /opt/ansible/2.7.1/local/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
<10.56.100.203> ESTABLISH WINRM CONNECTION FOR USER: dst on PORT 5985 TO 10.56.100.203
checking if winrm_host 10.56.100.203 is an IPv6 address
EXEC (via pipeline wrapper)
```
