### ISSUE TITLE
aci_switch_leaf_selector -> empty parameter "policy_group" results in "None" on ACI-fabric

### ISSUE THREAD

**Issue by smnmtzgr** [ansible/ansible#47668]
##### SUMMARY
The parameter "policy_group" is optional for the module aci_switch_leaf_selector what is in principal ok. But when leaving the parameter empty the module will set the value "None" for the parameter. On the ACI fabric then there needs to be a policy named "None" or a target missing failure will happen.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aci_switch_leaf_selector

##### ANSIBLE VERSION
```paste below
╰─ ansible --version
ansible 2.8.0.dev0 (devel 6eb7e2c470) last updated 2018/09/03 08:18:42 (GMT +200)
...
```
I've also tested the latest devel version and the issue still seems to exist.

##### CONFIGURATION
/

##### OS / ENVIRONMENT
ACI Firmware: Version: 3.2(3n)

##### STEPS TO REPRODUCE

```yaml
- name: adding a switch policy leaf profile selector associated Node Block range (w/o policy group)
  aci_switch_leaf_selector:
    host: apic
    username: admin
    password: SomeSecretPassword
    leaf_profile: sw_name
    leaf: leaf_selector_name
    leaf_node_blk: node_blk_name
    from: 1011
    to: 1011
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS
The expected result would be that the parameter "policy_group" is empty so that no policy group will be assigned. 

##### ACTUAL RESULTS
But instead the modules assigns a policy_group named "None".
