### ISSUE TITLE
URI module does not support async mode

### ISSUE THREAD

**Issue by lukasmrtvy** [ansible/ansible#47660]
##### SUMMARY
Its not possible to use async mode with uri module.
Command module and get_url module can handle async mode, but does not provide same functionality as uri module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri module

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sysadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
Ubuntu 18.04.1 LTS

##### STEPS TO REPRODUCE

```yaml
 - uri:
    url: https://localhost:8089/services/server/health
    method: GET
    user: healthcheck
    password: healthcheck
    return_content: yes
  until: healthcheck.content is search('<s:key name=\"healthy\">green</s:key>')
  retries: 10
  delay: 10
  async: 45
  poll: 0
  register: healthcheck
```

##### EXPECTED RESULTS

Run uri task in async mode

##### ACTUAL RESULTS

```paste below
fatal: [myserver1]: FAILED! => {"changed": false, "msg": "async is not supported for this task."}
fatal: [myserver2]: FAILED! => {"changed": false, "msg": "async is not supported for this task."}
```

##### Info
I can do something like this:
```
- shell: |
        for run in {1..10};
        do
           sleep 10
           curl -u healthcheck:healthcheck --max-time 10 -sSL -k https://localhost:8089/services/server/health | grep -q "<s:key name=\"health\">green</s:key>"
        done
    args:
      executable: /bin/bash
  async: 45
  poll: 0
  register: healthcheck
```
, but its not an ansible native way.
