### ISSUE TITLE
install_options not respected in homebrew 

### ISSUE THREAD

**Issue by kyledecot** [ansible/ansible#47681]
##### SUMMARY

When supplying `install_options` to `homebrew` it seems to ignore the options. For example if I supply `install_options: ---token="FOOBAR"` I would expect the resulting command to be:

```
brew install --token="FOOBAR" buildkite-agent
```

however it seems like the command ends up omitting the options:

```
brew install buildkite-agent
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`homebrew`

##### ANSIBLE VERSION

```
ansible 2.6.4
```

##### CONFIGURATION

```
  config file = None
  configured module search path = [u'/Users/kyledecot/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 18 2018, 14:55:12) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### OS / ENVIRONMENT

MacOS Mojave

##### STEPS TO REPRODUCE

```yaml
  - name: Install Buildkite Agent
    homebrew:
      package: buildkite-agent
      state: present
      install_options: --token='{{ buildkite_agent_token }}'
```

##### EXPECTED RESULTS

I would expect the resulting configuration file to have the token set correctly.

##### ACTUAL RESULTS

The command will install `buildkite-agent` however it seems to ignore the `install_options` resulting in the token being the default value.
