### ISSUE TITLE
Azure AKS - no support for enableRBAC?

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#47697]
##### SUMMARY
I am trying to set up an RBAC-enabled cluster with azure_rm_aks and it doesn't seem to be a way?

The rest API has an "enableRBAC" field, but I do not see a way to control it from the module. Ref: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate

I believe the module doesn't set the rbac field to anything, which means it will be false, which in turn means that the cluster will be somewhat insecure. Note however that azure cli now default to rbac=true, which adds to additional confusion.

So as a workaround I ended up going with a deployment, but I'd rather go with the aks module if possible. The template does list the enableRBAC field. However going the deployment route is a lot of typing which makes it more error prone. (related issue https://github.com/ansible/ansible/issues/47696)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_aks

##### ANSIBLE VERSION

```paste below
Ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/val/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18 / WSL

##### STEPS TO REPRODUCE

```yaml
Try to create an aks cluster, notice no enableRBAC control.
Or consult the documentation.
```

##### EXPECTED RESULTS

I would want to be able to toggle RBAC.

##### ACTUAL RESULTS

Nothing happens, no documented way to control RBAC.

```paste below

```

**Comment by ansibot** [comment]
Hi @vpopescu, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_aks.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_aks.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@vpopescu, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zikalino** [comment]
This option could be easily added, here's a sample how to use REST API in a meanwhile:

```
    - name: Sample for Azure REST API - ManagedClusters_CreateOrUpdate
      azure_rm_resource:
        # url: /subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerService/managedClusters/{resourceName}
        api_version: '2018-03-31'
        resource_group: "{{ resource_group }}"
        provider: containerservice
        resource_type: managedclusters
        resource_name: "{{ resourcename }}"
        body:
          location: location1
          tags: 
            tier: production
            archv2: 
          properties: 
            kubernetesVersion: 
            dnsPrefix: dnsprefix1
            agentPoolProfiles: 
              - name: nodepool1
                count: 3
                vmSize: Standard_DS1_v2
                osType: Linux
            linuxProfile: 
              adminUsername: azureuser
              ssh: 
                publicKeys: 
                  - keyData: keydata
            servicePrincipalProfile: 
              clientId: clientid
              secret: secret
            addonProfiles: 
            enableRBAC: yes
    
```
