### ISSUE TITLE
how to use multi dictionary

### ISSUE THREAD

**Issue by DFazeli** [ansible/ansible#47691]
##### SUMMARY
I have two dict in `/default/mian.yml` and I want to use together dict. please look my code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`/default/main.yml`
```
zookeeper_nodes: 
  node1: 
    ssh_ip: 192.168.163.37
    internal_ip: 192.168.163.37
    myid: 1
    port: 2181

  node2: 
    ssh_ip: 192.168.163.38
    internal_ip: 192.168.163.38
    myid: 2
    port: 2181

  node3: 
    ssh_ip: 192.168.163.39
    internal_ip: 192.168.163.39
    myid: 3
    port: 2181
topics:
  topic1: action1
  topic2: action2
  topic3: action3

```
and my playbook is: `/tasks/main.yml`
```
- name: --- Create Kafka Topic ---
  shell: |
   cd /opt/kafka/bin
   ./kafka-topics.sh --create --zookeeper "{{ item.0.internal_ip }}"/kafka --replication-factor 2 --partitions 12 --topic  "{{ item.1 }}" 
  with_subelements:
   - "{{ zookeeper_nodes }}" 
   - "{{ topics }}"

```
##### ANSIBLE VERSION

```
2.6
```

##### OS / ENVIRONMENT
```
Centos 7.4
```
##### EXPECTED RESULTS
I want set all ip nodes from first dict (`zookeeper_nodes`), like this `192.168.163.37:9092,192.168.163.38:9092,192.168.163.39:9092/kafka` 
and set all topics from second dict (`topics`), like this
`action1` and `action2` .....
