### ISSUE TITLE
azure deployment - integers being passed as string

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#47696]
##### SUMMARY
I am trying to deploy an cluster via azure_rm_deployment and an inline template. I am getting an error when trying to send an integer property, it appears it's being serialized as a string.

The value in question is count, below. I have a string value of "1" and I'm trying to send it as an integer:
```
...
    count: "{{ agent_count | int}}"
...
```
I found this filter in another bug report, and it appered that it would fix my needs. However my JSON still comes out as a string:

```
...
   "count": "1",
...
```

If I however replace the line with:

```
...
    count: 1
...
```

Then It gets generated correctly. What am I doing wrong?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_deployment

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/val/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu / WSL

##### STEPS TO REPRODUCE

...
  1. Create any playbook that contains an inline azure deployment template and has an integer field.
 2. Define the field as a string, and try to pass it via 

...

```yaml
...

- set_fact:
    agent_count: "{{ lookup('env', 'CONFIGURED_AGENT_COUNT) }}"

...

- name: Create AKS cluter via Azure template
  azure_rm_deployment:
    state: present
    resource_group_name: "{{ rg }}"
    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#managedCluster"
      contentVersion: "1.0.0.0"
      resources:
        - type: "Microsoft.ContainerService/managedClusters"
          apiVersion: '2018-03-31'
          location: "{{ location }} }"
          name: "{{ cn }}"
          properties:
            dnsPrefix: "{{ prefix }} "
            agentPoolProfiles:
              - name: "{{ anp }} "
                count: "{{ agent_count | int}}"
#                count: 1  (this works)
                vmSize:  "{{ vm ) }}"
            linuxProfile:
              adminUsername: "{{ luid }} "
              ssh:
                publicKeys:
                - keyData: "{{ lkey }} "
            servicePrincipalProfile:
              clientId: "{{ appId }}"
              secret:  "{{ password }}"
            addonProfiles: {}
            enableRBAC: true

```

##### EXPECTED RESULTS

The playbook should execute.

##### ACTUAL RESULTS

```paste below
he full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_azure_rm_deployment_payload_TScRh7/__main__.py", line 515, in deploy_template
    deployment_result = self.get_poller_result(result)
  File "/tmp/ansible_azure_rm_deployment_payload_TScRh7/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/azure_rm_common.py", line 484, in get_poller_result
    poller.wait(timeout=delay)
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_operation.py", line 511, in wait
    raise self._exception

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed_deployment_operations": [
        {
            "id": "/subscriptions/0f2f4954-26bf-4aed-bc0c-24ffc80d1c18/resourceGroups/agnxRG/providers/Microsoft.Resources/deployments/ansible-arm/operations/C435A2563172D838",
            "operation_id": "C435A2563172D838",
            "provisioning_state": "Failed",
            "status_code": "BadRequest",
            "status_message": {
                "code": "UnmarshalError",
                "message": "UnmarshalEntity encountered error: json: cannot unmarshal string into Go struct field AgentPoolProfile.count of type int."
            },
...,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "deployment_mode": "incremental",
            "deployment_name": "ansible-arm",
            "location": "westus",
            "parameters": null,
            "parameters_link": null,
            "password": null,
            "profile": null,
            "resource_group_name": "reactor42Test",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "template": {
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#managedCluster",
                "contentVersion": "1.0.0.0",
                "resources": [
                    {
...
                            "addonProfiles": {},
                            "agentPoolProfiles": [
                                {
                                    "count": "1",
                                    "name": "sampletestagnx",
                                    "vmSize": "Standard_DS2_v2"
                                }
                            ],
...
}

```
