### ISSUE TITLE
VMware: should have choice to specify vsan datastore name when configuring vsan cluster

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#47713]
##### SUMMARY

 While configuring vsan cluster we cant specify vsan datastore name that will get created.
 By default playbook gives name to datastore as vsanDatastore.If we have multiple vsan clusters on same vcenter it becomes confusing because new name will appeare as vsanDatastore(1).
 User should have facility to give datastore name in playbook

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py

##### ADDITIONAL INFORMATION

While configuring vsan cluster we cant specify vsan datastore name that will get created.
 By default playbook gives name to datastore as vsanDatastore.If we have multiple vsan clusters on same vcenter it becomes confusing because new name will appeare as vsanDatastore(1).
 User should have facility to give datastore name in playbook

```yaml
- name: Configure VMware VSAN Cluster
  hosts: deploy_node
  gather_facts: False
  tags:
    - vsan
  tasks:
    - name: Configure VSAN on first host
      vmware_vsan_cluster:
         hostname: "{{ groups['esxi'][0] }}"
         username: "{{ esxi_username }}"
         password: "{{ site_password }}"
      register: vsan_cluster

    - name: Configure VSAN on remaining hosts
      vmware_vsan_cluster:
         hostname: "{{ item }}"
         username: "{{ esxi_username }}"
         password: "{{ site_password }}"
         cluster_uuid: "{{ vsan_cluster.cluster_uuid }}"
      with_items: "{{ groups['esxi'][1:] }}"
```

**Comment by ansibot** [comment]
Hi @umrikar, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/galaxy/data/apb/tasks/main.yml.j2](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/tasks/main.yml.j2)
* [lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py)
* [lib/ansible/modules/system/hostname.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/hostname.py)
* [lib/ansible/modules/web_infrastructure/deploy_helper.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/deploy_helper.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [test/integration/targets/shadowed_module/library/tags](https://github.com/ansible/ansible/blob/devel/test/integration/targets/shadowed_module/library/tags)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@umrikar, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ckotte** [comment]
You cannot set the datastore name in the API directly. You would need to implement a rename of the datastore after the datastore is available.

As a workaround: You can rename the datastore with the module in https://github.com/ansible/ansible/pull/40520:

```
- name: System & Storage | Gather datastore facts
  tags: always
  vmware_datastore_facts:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    datacenter_name: "{{ vcenter_datacenter if esxi_connect_via_vcenter else 'ha-datacenter' }}"
    gather_nfs_mount_info: False
    gather_vmfs_mount_info: False
    validate_certs: no
  register: datastore_facts
  no_log: "{{ esxi_no_log }}"
  delegate_to: localhost

- name: System & Storage | Rename VSAN datastore
  vmware_object_rename:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    name: "{{ item.name }}"
    new_name: NewDatastoreName
    object_type: 'Datastore'
    validate_certs: "{{ validate_vcenter_certs }}"
  delegate_to: localhost
  with_items: "{{ datastore_facts.datastores }}"
  ignore_errors: "{{ esxi_ignore_errors }}"
  when: item.type == "VMFS" and item.name | regex_search('^vsanDatastore')
```

However, this only works if you don't have other datastores that start with the same name..
