### ISSUE TITLE
docker_swarm_service: Unable to publish a port in host mode

### ISSUE THREAD

**Issue by jfillatre** [ansible/ansible#47737]
##### SUMMARY
Despite of port publish mode set as host, service is deployed using ingress mesh routing 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_swarm_service

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /root/workspace/tpe-swarm-poc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/root/workspace/tpe-swarm-poc/ansible/ansible.cfg) = [u'/root/workspace/tpe-swarm-poc/ansible/inventory/hosts.yml']
DEFAULT_ROLES_PATH(/root/workspace/tpe-swarm-poc/ansible/ansible.cfg) = [u'/root/workspace/tpe-swarm-poc/ansible/roles']

```

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)
Linux RD-CAEN-TPE-HA-04 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
- name: Deploy registry service
  docker_swarm_service:
    name: "registry"
    image: "registry:2"
    mode: global
    mounts:
      - source: "{{ registry_host_datadir }}/"
        target: "/var/lib/registry"
        type: bind
    restart_policy: any
    restart_policy_attempts: 5
    restart_policy_window: 30
    publish:
      - published_port: "{{ registry_port }}"
        target_port: 5000
        protocol: tcp
        mode: host
    secrets:
      - secret_id: "{{ registry_secret_key_id.stdout }}"
        secret_name: registry.key
        filename: /etc/docker/registry/server.key
        uid: 0
        gid: 0
        mode: 0600
      - secret_id: "{{ registry_secret_crt_id.stdout }}"
        secret_name: registry.crt
        filename: /etc/docker/registry/server.crt
        uid: 0
        gid: 0
        mode: 0600
    configs:
      - config_id: "{{ registry_config_id.stdout }}"
        config_name: registry.config.yml
        filename: /etc/docker/registry/config.yml
        uid: 0
        gid: 0
        mode: 0640
  register: output
  run_once: true
```

##### EXPECTED RESULTS

```json
docker service inspect registry
[
    {
        "ID": "4gywz37hx8lcbevgxrcfkrbb3",
        "Version": {
            "Index": 5535
        },
        "CreatedAt": "2018-10-29T08:21:00.425232402Z",
        "UpdatedAt": "2018-10-29T08:21:00.432129168Z",
        "Spec": {
            "Name": "registry",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "registry:2@sha256:5a156ff125e5a12ac7fdec2b90b7e2ae5120fa249cf62248337b6d04abc574c8",
                    "Init": false,
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/var/lib/dockerregistry/",
                            "Target": "/var/lib/registry"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Secrets": [
                        {
                            "File": {
                                "Name": "/etc/docker/registry/server.crt",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 256
                            },
                            "SecretID": "n6t800ko0uyrvmgxnllv3g49d",
                            "SecretName": "registry.crt"
                        },
                        {
                            "File": {
                                "Name": "/etc/docker/registry/server.key",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 256
                            },
                            "SecretID": "yfy1hvl3fumha6jmlsf5v1wzy",
                            "SecretName": "registry.key"
                        }
                    ],
                    "Configs": [
                        {
                            "File": {
                                "Name": "/etc/docker/registry/config.yml",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 416
                            },
                            "ConfigID": "iweo9jfgt1r9pxwytg2auct6i",
                            "ConfigName": "registry.config.yml"
                        }
                    ],
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {
                    "Platforms": [
                        {
                            "Architecture": "amd64",
                            "OS": "linux"
                        }
                    ]
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Global": {}
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "host"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "host"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 5000,
                    "PublishedPort": 5000,
                    "PublishMode": "host"
                }
            ]
        }
    }
]
```

##### ACTUAL RESULTS

```json

docker service inspect registry
[
    {
        "ID": "14a6h6hy40o6bt0mquhiwrqwb",
        "Version": {
            "Index": 5552
        },
        "CreatedAt": "2018-10-29T08:46:09.65901934Z",
        "UpdatedAt": "2018-10-29T08:46:09.667424625Z",
        "Spec": {
            "Name": "registry",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "registry:2",
                    "User": "root",
                    "Mounts": [
                        {
                            "Type": "bind",
                            "Source": "/var/lib/dockerregistry/",
                            "Target": "/var/lib/registry"
                        }
                    ],
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {},
                    "Secrets": [
                        {
                            "File": {
                                "Name": "/etc/docker/registry/server.key",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 384
                            },
                            "SecretID": "yfy1hvl3fumha6jmlsf5v1wzy",
                            "SecretName": "registry.key"
                        },
                        {
                            "File": {
                                "Name": "/etc/docker/registry/server.crt",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 384
                            },
                            "SecretID": "n6t800ko0uyrvmgxnllv3g49d",
                            "SecretName": "registry.crt"
                        }
                    ],
                    "Configs": [
                        {
                            "File": {
                                "Name": "/etc/docker/registry/config.yml",
                                "UID": "0",
                                "GID": "0",
                                "Mode": 416
                            },
                            "ConfigID": "iweo9jfgt1r9pxwytg2auct6i",
                            "ConfigName": "registry.config.yml"
                        }
                    ],
                    "Isolation": "default"
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "any",
                    "Delay": 0,
                    "MaxAttempts": 5,
                    "Window": 30
                },
                "Placement": {},
                "LogDriver": {
                    "Name": "json-file"
                },
                "ForceUpdate": 0,
                "Runtime": "container"
            },
            "Mode": {
                "Global": {}
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "Delay": 10,
                "FailureAction": "continue",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "ingress"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "ingress"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 5000,
                    "PublishedPort": 5000,
                    "PublishMode": "ingress"
                }
            ],
            "VirtualIPs": [
                {
                    "NetworkID": "ussd5garbyp1df8269b8bel0v",
                    "Addr": "10.255.0.31/16"
                }
            ]
        }
    }
]


```

**Comment by ansibot** [comment]
Hi @jfillatre, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_swarm_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_swarm_service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akshay196 @danihodovic @dariko @felixfontein @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dariko** [comment]
@jfillatre Hi, I had to remove the configs/secrets parameters as I never used them and I don't know how to adapt them; without them I can't reproduce this:

On a clean centos 7, I installed docker 18.06.1
`````
# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
`````
 and run this task
`````
-   name: Deploy registry service
    docker_swarm_service:
        name: "registry"
        image: "registry:2"
        mode: global
        mounts:
        -   source: "/tmp/"
            target: "/var/lib/registry"
            type: bind
        restart_policy: any
        restart_policy_attempts: 5
        restart_policy_window: 30
        publish:
        -   published_port: "5000"
            target_port: 5000
            protocol: tcp
            mode: host
    register: output
    run_once: true
`````

which create the service with `PublishMode` `host`
`````
# docker service inspect registry
[cut]
            "EndpointSpec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "host"
                    }
                ]
            }
        },
        "Endpoint": {
            "Spec": {
                "Mode": "vip",
                "Ports": [
                    {
                        "Protocol": "tcp",
                        "TargetPort": 5000,
                        "PublishedPort": 5000,
                        "PublishMode": "host"
                    }
                ]
            },
            "Ports": [
                {
                    "Protocol": "tcp",
                    "TargetPort": 5000,
                    "PublishedPort": 5000,
                    "PublishMode": "host"
                }
            ]
        }
    }
[cut]
`````

I'm gonna try and see if this is about some strange interaction with the `configs` or `secrets` parameters, but it seems unlikely.
What docker version are you using?
