### ISSUE TITLE
Syntax improvements for complex "when" conditionals

### ISSUE THREAD

**Issue by achadwick** [ansible/ansible#47752]
##### SUMMARY

Please could the `when:` directive be extended with additional syntactic sugar for both AND and OR?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Not sure what is meant here. However, I would like the sugar to ideally use directives named `any` and `all`. This would provide a degree of similarity to Python's [`all()`](https://docs.python.org/3/library/functions.html#all) and [`any()`](https://docs.python.org/3/library/functions.html#any) functions.

##### ADDITIONAL INFORMATION

This would allow over-complex and bracket-y conditions to be rewritten in a more understandable way. The syntax would also be better when looking at diffs. A common use case is when targetting `tasks` or `import_*`s at multiple (distro, version) combinations. Currently one might write

```yaml
- import_tasks: stuff.yml
  when:
    - ((ansible_distribution == "Debian" and
        ansible_distribution_major_version in ["8", "9"]) or
       (ansible_distribution == "CentOS" and
        ansible_distribution_major_version in ["6", "7"]))
```

In future, perhaps one could write the following instead?

```yaml
# HYPOTHETICAL ONLY
- import_tasks: stuff.yml
  when:
    - any:
        - all:
            - ansible_distribution == "Debian"
            - ansible_distribution_major_version in ["8", "9"]
        - all: 
            - ansible_distribution == "CentOS"
            - ansible_distribution_major_version in ["6", "7"]
```
