### ISSUE TITLE
VMware: Unable to get ESXi ssl thumbprint through module "vmware_host_ssl_facts"

### ISSUE THREAD

**Issue by vigneshconfianza** [ansible/ansible#47769]
##### SUMMARY
Trying to retrieve ESXi ssl thumbprint, but the ansible out put returns empty dictionary value though available in system

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_host_ssl_facts

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

##### STEPS TO REPRODUCE
Trying to run playbook to retrieve ESXi ssl thumb print.
ESXi - 6.0 U3
Ansible: 2.7.1

```yaml
---
- name: Get ESXi facts
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: Gathering facts
    vmware_host_ssl_facts:
      hostname: '{{ esxi_hostname }}'
      validate_certs: no
      username: 'root'
      password: '!d0om$d@y'
      esxi_hostname: '{{ esxi_hostname }}'
    register: ssl_facts
  - debug:
     var: ssl_facts
```

##### EXPECTED RESULTS

expecting the thumb print value for ssl_thumbprints key.
TASK [debug] **********************************************
ok: [localhost] => {
    "ssl_facts": {
        "changed": false,
        "failed": false,
        "host_ssl_facts": {
            "esxi": {
                "owner_tag": "",
                "principal": "",
                "ssl_thumbprints": [67:33:80:7E:1F:2E:79:E1:90:36:7D:E9:94:4D:4E:79:C4:4A:92:27]
            }
        }
    }
}

##### ACTUAL RESULTS

No thumbprint returned by ansible module though available in system

[root@esxi:~] openssl x509 -in /etc/vmware/ssl/rui.crt -fingerprint -s
ha1 -noout
WARNING: can't open config file: /usr/lib/ssl/openssl.cnf
SHA1 Fingerprint=67:33:80:7E:1F:2E:79:E1:90:36:7D:E9:94:4D:4E:79:C4:4A:92:27

TASK [debug] **********************************************
ok: [localhost] => {
    "ssl_facts": {
        "changed": false,
        "failed": false,
        "host_ssl_facts": {
            "esxi": {
                "owner_tag": "",
                "principal": "",
                "ssl_thumbprints": []
            }
        }
    }
}

```paste below
[root@esxi:~] openssl x509 -in /etc/vmware/ssl/rui.crt -fingerprint -s
ha1 -noout
WARNING: can't open config file: /usr/lib/ssl/openssl.cnf
SHA1 Fingerprint=67:33:80:7E:1F:2E:79:E1:90:36:7D:E9:94:4D:4E:79:C4:4A:92:27

```
