### ISSUE TITLE
Integration with Mozilla SOPS for encrypted files

### ISSUE THREAD

**Issue by endorama** [ansible/ansible#47770]
##### SUMMARY

Integrate Mozilla `sops` to allow file content lookup.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Lookup plugin

##### ADDITIONAL INFORMATION

Issue #36982 requests `sops` integration for encrypted vars file.

As `sops` is capable of encrypting/decrypting [entire files][entire-files], a `lookup` plugin to load them can come useful to use encrypted file content.

[entire-files]: https://github.com/mozilla/sops#operational-requirements

As an example:

```yaml
tasks:
- name: add ssh private key
  copy:
    content: "{{lookup('sops', user + '-id_rsa')}}"
    dest: /home/{{user}}/.ssh/id_rsa
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0600
```
