### ISSUE TITLE
(edited) possible hybrid conditional problem

### ISSUE THREAD

**Issue by dirtyharrycallahan** [ansible/ansible#4779]
Possible bug when using or condition in when. I have assembled a playbook with examples. 

Looks like this condition containining two variables might not be being evaluated correctly.

Environment: ansible 1.4
Local Host OS is CentOS 6

```
[patrickc@localhost ansible.test]$ more variables.yml 
- hosts: all
  gather_facts: yes
  vars:
     is_centos5: "'{{ ansible_distribution }}' == 'CentOS' and '{{ ansible_lsb['major_release'] }}' == '5'"
     is_suse:    "'{{ ansible_distribution }}' == 'Suse'"

  tasks:


  - name: is_suse or is_centos5 t1
    debug: msg="FAIL is_suse or is_centos5"
    when: is_suse or is_centos5



[patrickc@localhost ansible.test]$ ansible-playbook -i stage variables.yml 


PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [is_suse or is_centos5 t1] ********************************************** 
ok: [localhost] => {
    "msg": "FAIL is_suse or is_centos5"
}


The observation is the above task did not get skipped.
```

**Comment by mpdehaan** [comment]
Hmm, you didn't file just the part of the defect I requested :)

I'll amend the ticket.

**Comment by mpdehaan** [comment]
done -- in queue for testing and debug if needed.

When reporting ansible versions always include the output of ansible --version

Ansible 1.4 is not yet released so the SHA version is usually useful and should be provided when running from source.

**Comment by mpdehaan** [comment]
Ok, I did some testing:

when: saved_expression

works fine.

However, if you are using two saved expressions, it needs to be written like so:

```
vars:
  x: 3
  one: "{{ x == 2 }}"
  two: "{{ x != 3 }}"
  three: "{{ 4 == 4 }}"
  four: "{{ x == 3 }}"

tasks:
   - shell: "echo this should skip"
    when: "{{ one }} and {{ two }}"

  - shell: "echo this should hit"
    when: "{{ four }} and {{ three }}"

  - shell: "echo this should skip"
    when: "two"

  - shell: "echo this should hit"
    when: "three"
```

Tested on the latest devel and all are operational.
