### ISSUE TITLE
how to telnet with enable password

### ISSUE THREAD

**Issue by hoyeunglee** [ansible/ansible#47793]
```
  tasks:
   - name: send configuration commands to IOS
     telnet:
       password: password
       login_prompt: "Password:"
       prompts:
         - "[>|#]"
       command:
         - en
         - enablepassword
         - terminal length 0
         - show environment all
```

can not enable password now
