### ISSUE TITLE
gcp_compute_address ignores subnet (selfLink not found by replace_resource_dict)

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#47805]
##### SUMMARY

The Module ignores the Subnetwork parameter if you try to register a internal static ip in an shared-vpc

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_address

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Unbuntu 18.04.1 LTS

##### STEPS TO REPRODUCE

```yaml
    - name:  a subnetwork facts
      gcp_compute_subnetwork_facts:
         region:                "{{ CE_GCE_REGION }}"
         filters:
         - name = net-sap-web
         project:                "xxx-xxxxx-prod"
         auth_kind:              serviceaccount
         service_account_file:   "{{ CE_GCE_CREDENTIAL_FILE }}"
         scopes:
            - https://www.googleapis.com/auth/compute
      register:                     subnetwork
      delegate_to:                  localhost
      environment:
        https_proxy: "http://{{PROXY_USER}}:{{PROXY_PASS}}@{{PROXY_IP}}:{{PROXY_PORT}}"
        http_proxy:  "http://{{PROXY_USER}}:{{PROXY_PASS}}@{{PROXY_IP}}:{{PROXY_PORT}}"


    - name: Reserve a Internal IP
      gcp_compute_address:
         name:                      "{{ CE_GCE_VM_RESERVED_INT_IP }}"
         subnetwork:                "{{  subnetwork }}"
         address:                   "10.xxx.x.66"
         region:                    "{{ CE_GCE_REGION }}"
         project:                   "{{ CE_GCE_PROJECT_ID }}"
         address_type:              INTERNAL
         auth_kind:                 serviceaccount
         service_account_file:      "{{ CE_GCE_CREDENTIAL_FILE }}"
         scopes:
            - https://www.googleapis.com/auth/compute
         state:                     present
      register:                     int_ip
      delegate_to:                  localhost
      environment:
        https_proxy: "http://{{PROXY_USER}}:{{PROXY_PASS}}@{{PROXY_IP}}:{{PROXY_PORT}}"
        http_proxy:  "http://{{PROXY_USER}}:{{PROXY_PASS}}@{{PROXY_IP}}:{{PROXY_PORT}}"
      when:                         CE_GCE_VM_RESERVED_INT_IP is defined

```

##### EXPECTED RESULTS

A static IP shoud be reserved in the Range of the Shared VPC

##### ACTUAL RESULTS

```paste below

fatal: [xxxxx.xxxxx.com -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address": "10.xxx.x.66",
            "address_type": "INTERNAL",
            "auth_kind": "serviceaccount",
            "description": null,
            "name": "xxxx-int",
            "network_tier": null,
            "project": "xx-xx-xxxx-xxx-xxxx",
            "region": "europe-west3",
            "scopes": [
                "https://www.googleapis.com/auth/compute"
            ],
            "service_account_email": null,
            "service_account_file": "/home/xxxxxx/xxxxx-xxxxx-xxxx-SAM-misc-xxxxxxxxx.json",
            "state": "present",
            "subnetwork": {
                "changed": false,
                "failed": false,
                "items": [
                    {
                        "creationTimestamp": "2018-10-29T02:00:36.495-07:00",
                        "fingerprint": "xxxxxxx",
                        "gatewayAddress": "10.xxx.x.65",
                        "id": "xxxxxxxxxxxxxxxxxxxxxx",
                        "ipCidrRange": "10.xxxxx.xxxx.64/26",
                        "kind": "compute#subnetwork",
                        "name": "net-xxxx-xxxx",
                        "network": "https://www.googleapis.com/compute/v1/projects/xxxx-network-prod/global/networks/shared-vpc-1",
                        "privateIpGoogleAccess": false,
                        "region": "https://www.googleapis.com/compute/v1/projects/xxxx-network-prod/regions/europe-west3",
                        "selfLink": "https://www.googleapis.com/compute/v1/projects/xxxx-network-prod/regions/europe-west3/subnetworks/net-xxxx-xxxx"
                    }
                ]
            }
        }
    },
    "msg": "GCP returned error: {u'error': {u'code': 400, u'message': u\"Invalid value for field 'resource.address': '10.xxxx.x.66'. Requested IP is not within the range of subnetwork 'default'.\", u'errors': [{u'domain': u'global', u'message': u\"Invalid value for field 'resource.address': '10.xxxx.x.66'. RequestedIP is not within the range of subnetwork 'default'.\", u'reason': u'invalid'}]}}"
}


IP Is requested in default net. Shared VPC is ignored.

Debuged: gcp_compute_address.py and found in Line 266

def resource_to_request(module):
    request = {
        u'kind': 'compute#address',
        u'address': module.params.get('address'),
        u'addressType': module.params.get('address_type'),
        u'description': module.params.get('description'),
        u'name': module.params.get('name'),
        u'networkTier': module.params.get('network_tier'),
######### Buggy Line ????
        u'subnetwork': replace_resource_dict(module.params.get(u'subnetwork', {}), 'selfLink')
    }
    return_vals = {}
    for k, v in request.items():
        if v:
            return_vals[k] = v

    return return_vals

I added a printout to a file with very key and Value + subnetwork as JSON. Looks as the following:

JSON: {"failed": false, "changed": false, "items": [{"kind": "compute#subnetwork", "name": "net-xxx-xxx", "creationTimestamp": "2018-10-29T02:00:36.495-07:00", "region": "https://www.googleapis.com/compute/v1/projects/xxx-network-prod/regions/europe-west3", "fingerprint": "xxxxxxxxx", "privateIpGoogleAccess": false, "ipCidrRange": "10.xxx.xx.64/26", "gatewayAddress": "10.xxx.x.65", "id": "xxxxxxxxxxxxxxx", "selfLink": "https://www.googleapis.com/compute/v1/projects/xxxx-network-xxxx/regions/europe-west3/subnetworks/net-xxxx-xxxx", "network": "https://www.googleapis.com/compute/v1/projects/xxx-network-prod/global/networks/shared-vpc-1"}]}
K: kind  V:compute#address
K: addressType  V:INTERNAL
K: address  V:10.xxx.xx.66
K: name  V:xxxxxx-int

```
