### ISSUE TITLE
gcp_compute_instance ignores subnet (selfLink not found by replace_resource_dict)

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#47812]
##### SUMMARY

The Module ignores the Subnetwork parameter from a internal static ip in an shared-vpc

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

Same issue as : https://github.com/ansible/ansible/issues/47805 only for this module

```yaml
              network_ip:           "{{ int_ip.address }}"       <<< not consistent to
              nat_ip: "{{ext_ip}}"                      

both is a instance of gcp_compute_address.py

 subnetwork:           "{{ subnetwork }}"                    <<< is ignored as an instance of gcp_compute_subnetwork_facts


```

##### EXPECTED RESULTS

VM with with correct subnet

##### ACTUAL RESULTS

VM isn't created because Subnet is not used.

```paste below

```
