### ISSUE TITLE
No way to add labels in gcp_compute_instance_template 

### ISSUE THREAD

**Issue by maelorn** [ansible/ansible#47815]
##### SUMMARY
We should be able to add labels in the properties as described in the google API documentation:   https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_compute_instance_template

##### ADDITIONAL INFORMATION

Example

```
- name: "create instance template"
  gcp_compute_instance_template:
    name: "test_template"
    properties:
      labels:
          env: production
      disks:
        - auto_delete: true
          boot: true
          initialize_params:
            source_image: 'projects/cos-cloud/global/images/cos-stable-70-11021-51-0'
      machine_type: f1-micro
      network_interfaces:
        - network: {name: "default"}
          access_configs:
            - name: 'External NAT'
              type: 'ONE_TO_ONE_NAT'
    project: "test_project"
    auth_kind: serviceaccount
    service_account_file: "/tmp/auth.pem"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
```
