### ISSUE TITLE
ssh_key_data parameter can only accept files for tower_credential module

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#47832]
##### SUMMARY
when setting the `ssh_key_data` to anything other than a file the module will error immediately with `    "msg": "file not found: ********"`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_credential

##### ANSIBLE VERSION
```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```paste below
-bash-4.2$ ansible-config dump --only-changed
-bash-4.2$
```

##### OS / ENVIRONMENT
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

##### STEPS TO REPRODUCE
the original use case was using the ec2 module, then using the key you product to instantly create a module
e.g. the first task would be->

```
    - name: Create ssh key pair
      ec2_key:
        name: "aws-reinvent-key"
      register: create_key
```

I simplified the error further and further to this->
```yaml
---
- name: AWS PLAYBOOK 101
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    create_key:
      key:
        private_key: "abcdef"

  tasks:

    - name: update SSH key with latest
      tower_credential:
        name: AWS_DEMO_INSTANCES_KEY
        organization: Default
        tower_host: https://localhost
        tower_username: admin
        tower_password: ansible
        kind: ssh
        #ssh_key_data: "123"
        #ssh_key_data: "{{ create_key.key.private_key }}"
      delegate_to: localhost
      run_once: true
```
when you uncomment the ssh_key_data you will get the `    "msg": "file not found: ********"`

##### ACTUAL RESULTS
it will error as described, here is some verbose output from Tower

```paste below
{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "authorize": false,
            "domain": null,
            "vault_password": null,
            "become_username": null,
            "become_method": null,
            "state": "present",
            "secret": null,
            "ssh_key_unlock": null,
            "authorize_password": null,
            "username": null,
            "description": null,
            "host": null,
            "user": null,
            "become_password": null,
            "password": null,
            "tenant": null,
            "subscription": null,
            "name": "AWS_DEMO_INSTANCES_KEY",
            "security_token": null,
            "project": null,
            "client": null,
            "ssh_key_data": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "team": null,
            "organization": "Default"
        }
    },
    "msg": "file not found: ********"
}
```

The exact line of code is here-> https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py#L278
