### ISSUE TITLE
iptables module attempts to use incompatible policy and action commands

### ISSUE THREAD

**Issue by gpulido-redhat** [ansible/ansible#47837]
##### SUMMARY

If I try to open a port on a RHEL6 machine with the following task:

    - name: Habilitar el firewall para SNMP (RHEL6)
      iptables:
        action: append
        chain: INPUT
        protocol: udp
        destination_port: 161
        policy: ACCEPT
        state: present
        table: filter

Then when running, I get the following error:

```
TASK [Habilitar el firewall para SNMP (RHEL6)] *********************************
fatal: [10.41.0.117]: FAILED! => {"changed": false, "cmd": "/sbin/iptables -t filter -L INPUT -p udp --destination-port 161", "msg": "iptables v1.4.7: Illegal option `-p' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.7: Illegal option `-p' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.\n", "stderr_lines": ["iptables v1.4.7: Illegal option `-p' with this command", "", "Try `iptables -h' or 'iptables --help' for more information."], "stdout": "", "stdout_lines": []}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module iptables
##### ANSIBLE VERSION

```paste below
[root@srvvtowerprd ~]# ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@srvvtowerprd ~]# 
```

##### CONFIGURATION

```paste below
[root@srvvtowerprd ~]# ansible-config dump --only-changed
[root@srvvtowerprd ~]# 

```

##### OS / ENVIRONMENT

RHEL6
##### STEPS TO REPRODUCE

Create a playbook with the task described before and run it on a RHEL6 (or RHEL7) machine. It will fail.

```yaml
    - name: Habilitar el firewall para SNMP (RHEL6)
      iptables:
        action: append
        chain: INPUT
        protocol: udp
        destination_port: 161
        policy: ACCEPT
        state: present
        table: filter
```

##### EXPECTED RESULTS

The port is opened in iptables

##### ACTUAL RESULTS

It fails with an error about wrong option passed to iptables command

```paste below
ansible-playbook  -b --become-method sudo -K -i ./inventory open-iptables-port.yaml
```

**Comment by ansibot** [comment]
Hi @gpulido-redhat, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/iptables.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/iptables.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @LinusU @sebastiendarocha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Kickimanjaro** [comment]
I see the same thing on Ansible 2.5.1 (the version available on WSL) control machine and CentOS 7.6.1810 client. iptables v1.4.21 on the client. 

Example of the task I used that triggered the error (almost identical to OP): 
```yaml
- name: open TCP 21 outbound
  iptables:
    action: append
    chain: OUTPUT
    protocol: tcp
    match: tcp
    destination_port: 21
    policy: ACCEPT
  become: yes
```

And the error I see upon running the playbook:
```
TASK [redacted : open TCP 21 outbound] ************************************************************************************************************************************************************************
fatal: [redacted]: FAILED! => {"changed": false, "cmd": "/sbin/iptables -t filter -L OUTPUT -p tcp -m tcp --destination-port 21", "msg": "iptables v1.4.21: Illegal option `-p' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.21: Illegal option `-p' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.\n", "stderr_lines": ["iptables v1.4.21: Illegal option `-p' with this command", "", "Try `iptables -h' or 'iptables --help' for more information."], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/mnt/c/Users/Kickimanjaro/Documents/GitHub/wrx/redacted.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
```

I was attempting to translate this command into an ansible task, `sudo iptables -A OUTPUT -p tcp -m tcp --dport 21 -j ACCEPT`, but mistakenly used `policy` instead of `jump`. When I changed my ansible task to use jump (shown below), it worked.

```yaml
- name: open TCP 21 outbound
  iptables:
    action: append
    chain: OUTPUT
    protocol: tcp
    match: tcp
    destination_port: 21
    jump: ACCEPT
    state: present
  become: yes
```

I believe this was user error, at least in my case, though it was certainly confusing. After I posted here I discovered my mistake and felt it worthwhile to update my comment in case it helps others.
