### ISSUE TITLE
azure_rm_deployment deploying to wrong location

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#47840]
##### SUMMARY
I have a region group in location centralus. It's an empty RG currently.
I am trying to deploy an AKS cluster to it via deployments.

It apparently is ignoring my settings and trying to deploy it into westus (which is the default location for a deployment). So it ends up dying with "invalid resource group location" error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_deployment

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/zdev/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/zdevl/log.txt
```

##### OS / ENVIRONMENT

Ubuntu 18.04 / WSL

##### STEPS TO REPRODUCE

```yaml
- name: Setting up a test environment
  hosts: localhost

  tasks:
    - name: Creating AKS cluster
      azure_rm_deployment:
        resource_group_name: "rslx45"
        template:
          $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#managedCluster"
          contentVersion: "1.0.0.0"
          deployment-name: "mypx"
          location: "centralus"
          resource_group_name: "rslx45"
          resources:
            - type: "Microsoft.ContainerService/managedClusters"
              name: "testcluster-xyzzy"
              apiVersion: '2018-03-31'
              location: "centralus"
              properties:
                kubernetesVersion: 1.11.13
                dnsPrefix: xyzzy31337
                agentPoolProfiles:
                  - name: xyzzy31337
                    count: 1
                    vmSize:  "Standard_DS2_v2"
                linuxProfile:
                  adminUsername: "kroot"
                  ssh:
                    publicKeys:
                      - keyData: "..."
                servicePrincipalProfile:
                 clientId: "prsxlm5_dev"
                 secret:  "9a7a4699-add8-4855-ba88-26c2a3306ee"
              addonProfiles: {}
              enableRBAC: yes
```

....
result of 'az group show':

{
  "id": "/subscriptions/.../resourceGroups/rslx45",
  "location": "centralus",
  "managedBy": null,
  "name": "rslx45",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "Environment": "dev",
    "delete": "never"
  }
}

##### EXPECTED RESULTS

The cluster should be deployed

##### ACTUAL RESULTS

I get the error below. Note that fields such as "deployment_mode", "deployment_name", and "location" under module args were set to defaults.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Resource group create_or_update failed with status code: 409 and message: Invalid resource group location 'westus'. The Resource group already exists in location 'centralus'."}

```paste below
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/zdev/.ansible/tmp/ansible-tmp-1540952677.91-30113970822294/AnsiballZ\
_azure_rm_deployment.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/zdev/.ansible/tmp/ansible-tmp-1540952677.91-30113970822294/ > /dev/null 2>&1\
 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_azure_rm_deployment_payload_jv5liA/__main__.py", line 505, in deploy_template
    self.rm_client.resource_groups.create_or_update(self.resource_group_name, params)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_ope\
rations.py", line 147, in create_or_update
    raise exp
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "deployment_mode": "incremental",
            "deployment_name": "ansible-arm",
            "location": "westus",
            "parameters": null,
            "parameters_link": null,
            "password": null,
            "profile": null,
            "resource_group_name": "rslx45",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "template": {
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#managedClust\
er",
                "contentVersion": "1.0.0.0",
                "deployment-name": "hpx",
                "location": "centralus",
                "resource_group_name": "rslx45",
                "resources": [
                    {
                        "addonProfiles": {},
                        "apiVersion": "2018-03-31",
                        "enableRBAC": true,
                        "location": "centralus",
                        "name": "testcluster-xyzzy",
                        "properties": {
                            "agentPoolProfiles": [
                                {
                                    "count": 1,
                                    "name": "xyzzy31337",
                                    "vmSize": "Standard_DS2_v2"
                                }
                            ],
                            "dnsPrefix": "xyzzy31337",
                            "kubernetesVersion": "1.11.13",
                            "linuxProfile": {
                                "adminUsername": "kroot",
                                "ssh": {
                                    "publicKeys": [
                                        {
                                            "keyData": "ssh-rsa ..."
                                        }
                                    ]
                                }
                            },
                            "servicePrincipalProfile": {
                               "clientId": "prsxlm5_dev",
                                "secret": "9a7a4699-add8-4855-ba88-26c2a3306ee"
                            }
                        },
                        "type": "Microsoft.ContainerService/managedClusters"
                    }
                ]
            },
            "template_link": null,
            "tenant": null,
            "wait_for_deployment_completion": true,
            "wait_for_deployment_polling_period": 10
        }
    },
    "msg": "Resource group create_or_update failed with status code: 409 and message: Invalid resource group location '\
westus'. The Resource group already exists in location 'centralus'."
}
        to retry, use: --limit @/home/zdev/test.retry

PLAY RECAP ************************************************************************************************************\
*
localhost                  : ok=1    changed=0    unreachable=0    failed=1

```
