### ISSUE TITLE
can not configure to add user or change password

### ISSUE THREAD

**Issue by hoyeunglee** [ansible/ansible#47841]
ISSUE TYPE
Bug Report

COMPONENT NAME
ios_config

ANSIBLE VERSION
Ansible 2.7.1

CONFIGURATION
```
---
- hosts: Testdevices
  gather_facts: false
  connection: local
  vars:
     date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  tasks:
   - name: change password
     ios_config:
       lines:
         - config t
         - username smsi privilege 15 password 0 password
         - line vty 5 15
         - login local

  - name: print out command
     debug:
       var: result2
     register: result2

   - local_action: copy content={{ result2 }} dest=/etc/ansible/debugmsg.txt

 
provider: "{{login_info}}"

```

OS / ENVIRONMENT
Linux version 4.15.0-29-generic (buildd@lcy01-amd64-024) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu116.04.10)) #3116.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018

SUMMARY
error and can not saved debug into a file

STEPS TO REPRODUCE
sudo ansible-playbook -s configure.yml -u martinlee -k

EXPECTED RESULTS
config switch to add a new user with password

ACTUAL RESULTS

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: noc01as01(config)#
fatal: [noc01as01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1540954819.24-257942826094869/AnsiballZ_ios_config.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1540954819.24-257942826094869/AnsiballZ_ios_config.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1540954819.24-257942826094869/AnsiballZ_ios_config.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ios_config_payload_o194I7/__main__.py\", line 536, in <module>\n  File \"/tmp/ansible_ios_config_payload_o194I7/__main__.py\", line 467, in main\n  File \"/tmp/ansible_ios_config_payload_o194I7/__main__.py\", line 328, in edit_config_or_macro\n  File \"/tmp/ansible_ios_config_payload_o194I7/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 173, in __rpc__\nansible.module_utils.connection.ConnectionError: config t\r\n                         ^\r\n% Invalid input detected at '^' marker.\r\n\r\nnoc01as01(config)#\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to have been in '/etc/ansible/configure.yml': line 16, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: print out command
  ^ here

**Comment by ansibot** [comment]
Hi @hoyeunglee, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
!component =lib/ansible/plugins/action/ios_config.py

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @ganeshrn @gdpak @justjais @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by NilashishC** [comment]
@hoyeunglee You do not need to enter the configuration mode while executing commands using `ios_config`, the module takes care of that. Please remove the `config t` line in the first task of your playbook and try running it again.

**Comment by hoyeunglee** [comment]
after remove config t and try again, got error

FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 10 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}


```
---
- hosts: Testdevices
  gather_facts: false
  connection: local
  vars:
     date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
     cli:
        host: "{{ ansible_host }}"
        username: "xxx"
        password: xxx
  tasks:
   - name: change password
     ios_config:
       lines:
         - username xxxx privilege 15 password 0 password
         - line vty 5 15
         - login local
       provider: "{{ cli }}"

```
