### ISSUE TITLE
Suggestion: Mark deprecated parameters within documentation

### ISSUE THREAD

**Issue by tux-84** [ansible/ansible#47844]
##### SUMMARY
Deprecated commands should be marked within the docs

##### ISSUE TYPE
- Documentation Report

For example on [this](https://docs.ansible.com/ansible/2.5/modules/get_url_module.html) site, the command *sha256sum* is deprecated, however it's just written at the end of a long description of the command, which many user might not read.

Maybe it's a good idea to mark deprecated commands within the docs (e.g. another color, deprecated column etc.).

**Comment by ansibot** [comment]
Hi @jzielke-nli, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [docs](https://github.com/ansible/ansible/blob/devel/docs)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jzielke-nli: in order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @acozine
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tux-84** [comment]
ansible version: 2.7.0

**Comment by acozine** [comment]
@jzielke-nli thanks for the suggestion - would you like to add it to the [agenda](https://github.com/ansible/community/issues/389) for next week's Documentation Working Group meeting?

**Comment by tux-84** [comment]
@acozine Yes, this would be great. Since Ansible changes it's syntax in many modules quite frequently, I think marking deprecated commands in the docs gives newbies as well as long time users a better overview on what cmd to use for what purposes without spending extra time on sorting out deprecated commands after a role has been written already.

**Comment by ansibot** [comment]
@jzielke84 This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jzielke84** [comment]
@acozine What's the bot up to?

**Comment by aknrdureegaesr** [comment]
> ansible version: 2.7.0

If you want to get rid of those ugly "needs_info" and "needs_template" labels on your issue, I'm afraid the bot only looks for that information in the initial description of the issue, not in a later comment. The [template](https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md) for that initial description has this:

    ##### ANSIBLE VERSION
    
    ```paste below
    
    ```

So my recommendation would be to put that into the initial description.

**Comment by gundalow** [comment]
Thanks for raising this. Something I'd thought about, but not recorded in an issue. I wonder if we add a new `deprecated` option in the modules schema:

```yaml
  sha256sum:
    description:
      - If a SHA-256 checksum is passed to this parameter, the digest of the
        destination file will be calculated after it is downloaded to ensure
        its integrity and verify that the transfer completed successfully.
    deprecated: Use C(checksum) instead.
    default: ''

    version_added: "1.3"

```


This is similar to when a whole module get's deprecated
```yaml
deprecated:
    removed_in: "2.12"
    why: "Replaced by re-designed individual modules living at https://github.com/theforeman/foreman-ansible-modules"
    alternative: https://github.com/theforeman/foreman-ansible-modules
```


If we want this it will require:
*  validate-module's schema.py`
* ensure matching argspec, ie `src': dict(type='path', removed_in_version=2.11),`
* document
* Update existing modules
