### ISSUE TITLE
aws_s3: get object ignore version parameter

### ISSUE THREAD

**Issue by gaelL** [ansible/ansible#47864]
##### SUMMARY

Following the doc we can specify a `version`  :  Version ID of the object inside the bucket. Can be used to get a specific version of a file if versioning is enabled in the target bucket.

Trying out, it seems the version is not use to download the s3 object. We always end up with the latest object

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aws_s3 module (action get)

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gael/Desktop/git/github/cycloidio/stack-magento/ansible/.env/local/lib/python2.7/site-packages/ansible
  executable location = /home/gael/Desktop/git/github/cycloidio/stack-magento/ansible/.env/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 05:55:50) [GCC 7.3.0]
```

Note : tested also on 2.4.3 and 2.5

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/etc/ansible']
```

##### OS / ENVIRONMENT

Debian

##### STEPS TO REPRODUCE

Create a s3 bucket with versioning, upload 2 version of the object.

Then create a ansible playbook to get this object, following the example in the doc
```yaml

- name: Get a specific version of an object.
  aws_s3:
    bucket: mybucket
    object: /my/desired/key.txt
    version: 48c9ee5131af7a716edc22df9772aa6f
    dest: /usr/local/myfile.txt
    mode: get

```

##### EXPECTED RESULTS

Have the object version 48c9ee5131af7a716edc22df9772aa6f downloaded

##### ACTUAL RESULTS

The latest version of the object in the s3 bucket is downloaded
