### ISSUE TITLE
Add Endpoint Type Support for ec2_vpc_endpoint Module 

### ISSUE THREAD

**Issue by tonyswu** [ansible/ansible#47898]
##### SUMMARY

Add support for VPC endpoint type for module "ec2_vpc_endpoint". AWS supports two types of endpoints, Service or Gateway. Current default is Gateway, which causes a failure if the endpoint being created is of type "Service".

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_vpc_endpoint

##### ADDITIONAL INFORMATION

The module fails as of now if the endpoint created is "Service" type:

Endpoint type (Gateway) does not match service type (Interface).

```yaml
ec2_vpc_endpoint:
  state: present
  region: "{{ aws_region }}"
  vpc_id: "{{ vpc.vpc.id }}"
  service: "{{ metrix_service_vpc_endpoint }}"
  type: "Service" | "Gateway"
```
