### ISSUE TITLE
ec2_group ruleset applies rules improperly

### ISSUE THREAD

**Issue by Daemoen** [ansible/ansible#47904]
##### SUMMARY
ec2_group changes has some condition where it encounters an issue comparing rule sets, recreating the rules (successfully), and says ok, but *fails* to properly recreate the ruleset as expected.

In our case, we have the plays in the attached gists -- if you run group1, followed by group2 (in our case), after group2, it will say it changed, and it does... but it does *not* apply *all* of the changes... which can leave you in a VERY bad / precarious state.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = ['/home/marc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/marc/.local/lib/python3.7/site-packages/ansible
  executable location = /home/marc/.local/bin/ansible
  python version = 3.7.0 (default, Aug 30 2018, 14:32:33) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/marc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(/home/marc/projects/ansible/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/marc/projects/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/marc/projects/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/marc/projects/ansible/ansible.cfg) = -o ForwardAgent=yes -o StrictHostKeyChecking=no
ANSIBLE_SSH_RETRIES(/home/marc/projects/ansible/ansible.cfg) = 2
DEFAULT_CALLBACK_WHITELIST(/home/marc/projects/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/marc/projects/ansible/ansible.cfg) = 25
DEFAULT_LOG_PATH(/home/marc/projects/ansible/ansible.cfg) = /home/marc/projects/ansible/log/ansible.log
DEFAULT_ROLES_PATH(/home/marc/projects/ansible/ansible.cfg) = ['/home/marc/projects/ansible/roles']
DEFAULT_TRANSPORT(/home/marc/projects/ansible/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/home/marc/projects/ansible/ansible.cfg) = /home/marc/sekrits
INVENTORY_ENABLED(/home/marc/projects/ansible/ansible.cfg) = ['aws_ec2', 'host_list', 'script', 'yaml', 'ini']
RETRY_FILES_ENABLED(/home/marc/projects/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/marc/projects/ansible/ansible.cfg) = /home/marc/projects/ansible/retries
```

##### OS / ENVIRONMENT

Environment:  AWS EC2 Security Groups

##### STEPS TO REPRODUCE
https://gist.github.com/Daemoen/1e6e79b1676ed22f27327e790ec05e69

##### EXPECTED RESULTS
ec2 group applies any differences without breaking

##### ACTUAL RESULTS
Play requires you run it 2x to get to the consistent state.  The first execution leaves you in an *incomplete* state, the second execution completes the state.

---
I have some screenshots and even verbose logs, but of course, because this is ec2, I cannot post them publically.  Ping me in channel or on here for more info as needed.

**Comment by ansibot** [comment]
Hi @Daemoen, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @adq
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Daemoen, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Daemoen** [comment]
Have pinged a few folks in channel, as this is a very rough bug to trigger, since it leaves you with a 'changed' but does not necessarily leave you with the state you actually expect.

**Comment by willthames** [comment]
Can someone run the test case in in an unimportant environment and post the logs here, along with highlighting the difference in expectation vs reality - might help with troubleshooting what's going on.

**Comment by willthames** [comment]
This is a horrendous bug. Minimal playbook test cases:

minimal.yml
```
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:

    - name: create a VPC
      ec2_vpc_net:
        name: ansible-issue-47904
        cidr_block: 10.1.2.0/24
        region: ap-southeast-2
      register: vpc

    - name: Create a security group
      ec2_group:
        region: ap-southeast-2
        name: ansible-issue-47904
        description: Ansible issue 47904
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp           # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
```

minimal2.yml
```
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:

    - name: create a VPC
      ec2_vpc_net:
        name: ansible-issue-47904
        cidr_block: 10.1.2.0/24
        region: ap-southeast-2
      register: vpc

    - name: Create a security group
      ec2_group:
        region: ap-southeast-2
        name: ansible-issue-47904
        description: Ansible issue 47904
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: ssh from anywhere
```
Credentials aren't passed as you can just do `AWS_PROFILE=your_profile ansible-playbook minimal.yml -vv`

Run minimal.yml, then minimal2.yml, and watch as `ip_permissions` is the empty list. Running minimal2.yml again fixes it, but that's a workaround
