### ISSUE TITLE
mesh ping error

### ISSUE THREAD

**Issue by hoyeunglee** [ansible/ansible#47911]
```
---
- hosts: Testdevices
  gather_facts: false
  connection: local
  vars:
     date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
     cli:
        host: "{{ ansible_host }}"
        username: "hello"
        password: "hello"
  tasks:
   - name: ping 
     ios_ping:
       dest: "{{ ansible_host }}"
       provider: "{{ cli }}"
     register: packets_rx
     ignore_errors: yes
     check_mode: no

   - name: save output to /etc/ansible/backups
     copy:
       content: "{{ packets_rx }}"
       dest: "/etc/ansible/backups/{{ inventory_hostname }}_ping_{{ date }}.txt"

```

```
TASK [ping] ********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'group'
fatal: [c0101as01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/martin/.ansible/tmp/ansible-tmp-1541046448.89-24491536146014/AnsiballZ_ios_ping.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/martin/.ansible/tmp/ansible-tmp-1541046448.89-24491536146014/AnsiballZ_ios_ping.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/martin/.ansible/tmp/ansible-tmp-1541046448.89-24491536146014/AnsiballZ_ios_ping.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ios_ping_payload_CwAyNw/__main__.py\", line 211, in <module>\n  File \"/tmp/ansible_ios_ping_payload_CwAyNw/__main__.py\", line 147, in main\n  File \"/tmp/ansible_ios_ping_payload_CwAyNw/__main__.py\", line 196, in parse_ping\nAttributeError: 'NoneType' object has no attribute 'group'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
...ignoring
fatal: [noc01as01]: FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 10 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}
...ignoring

TASK [save output to /etc/ansible/backups] *************************************
changed: [c0101as01]
changed: [noc01as01]

PLAY RECAP *********************************************************************
c0101as01                  : ok=2    changed=1    unreachable=0    failed=0   
noc01as01                  : ok=2    changed=1    unreachable=0    failed=0   
```
