### ISSUE TITLE
services-addition in hostvars in netbox dynamic inventory

### ISSUE THREAD

**Issue by ollybee** [ansible/ansible#47918]
##### SUMMARY
This is an extension to https://github.com/ansible/ansible/issues/47391
Adding services defined in Netbox to host vars would assist those intending to use Netbox to configure monitoring systems.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
netbox-services in hostvars in netbox dynamic inventory

##### ADDITIONAL INFORMATION
Feature could be used to configure monitoring systems by addition of services defined in Netbox in Ansible hostvars. Netbox allows arbitrary structured data to be assigned to servers via custom fields, tags, configuration contexts and services. Along with https://github.com/ansible/ansible/pull/47394 this would complete the set of these Netbox features support by the dynamic inventory script.

```yaml
ansible-inventory -vvv -i ./netbox_inventory.yml --host someserver
ansible-inventory 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/monitoring/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
/home/monitoring/ansible/netbox_inventory.yml did not meet host_list requirements, check plugin documentation if this is unexpected
/home/monitoring/ansible/netbox_inventory.yml did not meet virtualbox requirements, check plugin documentation if this is unexpected
Fetching: https://netboxdev.hyperslice.net/api/dcim/sites/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/regions/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/tenancy/tenants/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/racks/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/device-roles/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/device-types/?limit=0
Fetching: https://netboxdev.hyperslice.net/api/dcim/manufacturers/?limit=0
Fetching: https://netboxdev.hyperslice.net//api/dcim/devices/?limit=0&name=someserver
Fetching: https://netboxdev.hyperslice.net//api/virtualization/virtual-machines/?limit=0&name=someserver
Parsed /home/monitoring/ansible/netbox_inventory.yml inventory source with netbox plugin
{
    "config_context": [
        {}
    ],
    "device_roles": [
        "Dummy server"
    ],
    "device_types": [
        "Dummy"
    ],
    "manufacturers": [
        "Dummy"
    ],
    "services": [
        [
            {
                "created": "2018-11-01",
                "custom_fields": {
                    "key_text": null
                },
                "description": "",
                "device": {
                    "display_name": "someserver",
                    "id": 13084,
                    "name": "someserver",
                    "url": "https://netboxdev/api/dcim/devices/13084/"
                },
                "id": 28,
                "ipaddresses": [],
                "last_updated": "2018-11-01T11:59:01.696607Z",
                "name": "SSH",
                "port": 22,
                "protocol": {
                    "label": "TCP",
                    "value": 6
                },
                "virtual_machine": null
            },
            {
                "created": "2018-11-01",
                "custom_fields": {
                    "key_text": null
                },
                "description": "",
                "device": {
                    "display_name": "someserver",
                    "id": 13084,
                    "name": "someserver",
                    "url": "https://netboxdev/api/dcim/devices/13084/"
                },
                "id": 29,
                "ipaddresses": [],
                "last_updated": "2018-11-01T11:59:18.855776Z",
                "name": "awebsite.org",
                "port": 443,
                "protocol": {
                    "label": "TCP",
                    "value": 6
                },
                "virtual_machine": null
            },
            {
                "created": "2018-11-01",
                "custom_fields": {
                    "key_text": null
                },
                "description": "",
                "device": {
                    "display_name": "someserver",
                    "id": 13084,
                    "name": "someserver",
                    "url": "https://netboxdev/api/dcim/devices/13084/"
                },
                "id": 30,
                "ipaddresses": [],
                "last_updated": "2018-11-01T11:59:32.669569Z",
                "name": "anothersite.net",
                "port": 443,
                "protocol": {
                    "label": "TCP",
                    "value": 6
                },
                "virtual_machine": null
            },
            {
                "created": "2018-11-01",
                "custom_fields": {
                    "key_text": null
                },
                "description": "",
                "device": {
                    "display_name": "someserver",
                    "id": 13084,
                    "name": "someserver",
                    "url": "https://netboxdev/api/dcim/devices/13084/"
                },
                "id": 31,
                "ipaddresses": [],
                "last_updated": "2018-11-01T11:59:54.599007Z",
                "name": "arbitaryservice",
                "port": 5544,
                "protocol": {
                    "label": "UDP",
                    "value": 17
                },
                "virtual_machine": null
            }
        ]
    ],
    "sites": [
        "Dummy site"
    ]
}
```
