### ISSUE TITLE
mysql module failed with an error zlib.error: Error -2 while preparing to decompress data: inconsistent stream state

### ISSUE THREAD

**Issue by nitinkansal1984** [ansible/ansible#47927]
##### SUMMARY

mysql module failed zlib.error: Error -2 while preparing to decompress data: inconsistent stream state

failed: [server] (item=server) => {"chang
ed": false, "item": "server", "module_stderr": "Shared connection to server closed.\r\n", "module_stdout": "Traceback (most recent
 call last):\r\n  File \"/tmp/ansible_Aq1IFy/ansible_module_mysql_user.py\", line 206, in <module>\r\n    from ansible.module_utils.basic impor
t AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n", "msg": "MODULE FAILURE", "rc": 1}

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

`mysql_user.py`

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, May 3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

- name: Lock down root user by changing default root user to a local user
         mysql_user:
           check_implicit_admin=yes
           login_user="{{mysql_root_user}}"
           login_password="{{mysql_root_password}}"
           name="{{mysql_root_user}}"
           password="{{mysql_root_password}}"
           host="{{item}}"
           priv="*.*:ALL,GRANT"
         with_items:
            - "localhost"
            - "server FQDN"
            - "server IP"
            - "server"
         become: no
```

##### ACTUAL RESULTS

```paste below

```
