### ISSUE TITLE
ipa_dnsrecord: cannot create record without TTL

### ISSUE THREAD

**Issue by evanstoner** [ansible/ansible#47928]
##### SUMMARY

When using `ipa_dnsrecord` without the optional `record_ttl` attribute, the module passes the string 'None' to the IPA API, resulting in a failure to create the module. In my IPA server's /var/log/httpd/error_log I can see:

```
[Thu Nov 01 15:11:40.202217 2018] [:error] [pid 7307] ipa: INFO: [jsonserver_session] user@foo.com: dnsrecord_add(u'foo.com', u'foo-hostname', dnsttl=u'None', a_part_ip_address=u'10.x.y.z'): ConversionError
```

This appears to be caused by [using `to_native`](https://github.com/ansible/ansible/blob/v2.7.0/lib/ansible/modules/identity/ipa/ipa_dnsrecord.py#L214) which without any additional parameters [returns `str(obj)`](https://github.com/ansible/ansible/blob/v2.7.0/lib/ansible/module_utils/_text.py#L52-L58) if the parameter is not a string type (it is `None` in this case). Calling `to_native` with `nonstring='passthru'` would resolve this by returning the `None` value itself instead of a string representation of it, ensuring that it would [not be added](https://github.com/ansible/ansible/blob/v2.7.0/lib/ansible/modules/identity/ipa/ipa_dnsrecord.py#L158-L159) to the item being posted to the API. Alternatively, the `module_dnsrecord` could be updated conditionally with the TTL if it is set.

This can be worked around by setting `record_ttl`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipa_dnsrecord

##### ANSIBLE VERSION

```paste below
2.7.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Python 2.7.15rc1

##### STEPS TO REPRODUCE

Using env vars for host, user, and password configuration.

```yaml
- name: create dns record
  ipa_dnsrecord:
    validate_certs: no
    zone_name: foo.com
    record_name: "{{ item.instance.hw_name }}"
    record_value: "{{ item.instance.ipv4 }}"
  loop: "{{ clone_facts.results }}"
```

##### EXPECTED RESULTS

A "changed" result, and the record is created by IPA with its default TTL.

##### ACTUAL RESULTS

```
failed: [localhost] (item={...}, "msg": "response dnsrecord_add: invalid 'ttl': must be an integer"}
```
