### ISSUE TITLE
VMware: vmware_guest AttributeError: 'NoneType' object has no attribute 'rootSnapshotList'

### ISSUE THREAD

**Issue by mvrgotiks** [ansible/ansible#47920]
##### SUMMARY

Failed to create new VM using snapshort_src with/without template.
Also tested with 2.7.0 Ansible and with 2.6.4 Ansible
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest with snapshot_src

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

ESXI 6.5

##### STEPS TO REPRODUCE

My steps were all using Ansible:
1. Create a VM from Template (manually or via ansible) : vmname: markotest
2. Shutdown VM  (manually or via ansible)
3. Snapshot poweredoff VM (manually or via ansible): snapshotname: markosnapshot 
4. Using Ansible vmware_guest and snapshot_src create a clone VM (vmname: markotest2)from snapshot
4.1 tried without adding template
4.2 tried with template (next to snapshot source) 

- Create VM

 VM

```yaml
---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ vmguestname }}"
      template: "netapp_centos_75_100"
      datacenter: "{{ datacenter }}"
      folder: "/Datacenter/vm/Discovered virtual machine"
      state: poweredon
      cluster: "{{ cluster }}"
      networks:
        - name: VM Network
          ip: "{{ vmguestip }}"
          netmask: 255.255.0.0
          gateway: 172.16.1.1
          start_connected: True
      wait_for_ip_address: True
```

- Shutdown VM

```yaml
---
- name: Shutdown VM
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Shutdown VM
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      folder: "/Datacenter/vm/Discovered virtual machine"
      cluster: "{{ cluster }}"
      name: "{{ vmguestname }}"
      state: shutdownguest
    delegate_to: localhost
```

- Snapshot VM

```yaml
---
- name: Snapshot VM Guest
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create VM Guest Snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      folder: "/Datacenter/vm/Discovered virtual machine"
      name: "{{ vmguestname }}"
      state: present
      snapshot_name: "{{ vmsnapshotname }}"
      description: "{{ vmsnapshot_description }}"
    delegate_to: localhost
```

- Create VM Clone from Snapshot - attempt without template

```yaml
---
- name: Create a VM from a Snapshot
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create VM from Snapshot
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      snapshot_src: "{{ vmsnapshotname }}"
      name: "{{ vmguestname }}"
      datacenter: "{{ datacenter }}"
      folder: "/Datacenter/vm/Discovered virtual machine"
      state: poweredon
      cluster: "{{ cluster }}"
```

- Create VM Clone from Snapshot - attempt with template

```yaml
---
- name: Create a VM from a Snapshot
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Create VM from Snapshot
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      snapshot_src: "{{ vmsnapshotname }}"
      template: netapp_centos_75_100
      name: "{{ vmguestname }}"
      datacenter: "{{ datacenter }}"
      folder: "/Hilversum Datacenter/vm/Discovered virtual machine"
      state: poweredon
      cluster: "{{ cluster }}"
```

##### EXPECTED RESULTS

Create a new VM "markotest2" from Snapshot (with/without template since I do not know if its required for creating new VM from snapshot image) of the existing VM

##### ACTUAL RESULTS

The run fails:
In first attempt: no template

```paste below
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: centos
<127.0.0.1> EXEC /bin/sh -c 'echo ~centos && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966 `" && echo ansible-tmp-1541070526.32-79431538610966="` echo /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> PUT /home/centos/.ansible/tmp/ansible-local-28379jgRo0l/tmpsbQWkN TO /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966/AnsiballZ_vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966/ /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/centos/.ansible/tmp/ansible-tmp-1541070526.32-79431538610966/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "HV HA Cluster",
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "Hilversum Datacenter",
            "datastore": null,
            "disk": [],
            "esxi_hostname": null,
            "folder": "/Hilversum Datacenter/vm/Discovered virtual machine",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "172.16.1.48",
            "is_template": false,
            "linked_clone": false,
            "name": "markotest2",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": "markosnapshot",
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": null,
            "username": "administrator@avinity.tv",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_ip_address": false
        }
    },
    "msg": "Unable to find the datastore with given parameters. This could mean, markotest2 is a non-existent virtual machine and module tried to deploy it as new virtual machine with no disk. Please specify disks parameter or specify template to clone from."
}
	to retry, use: --limit @/home/centos/playbooks/darko/ansible-vmware/deploy_vm_from_snapshot.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
Which I why I assumed template or complete new VM specs are required, so I tried second attempt with teamplte

```paste below
[centos@ansible-magic ansible-vmware]$ ansible-playbook deploy_vm_from_snapshot.yml --extra-vars '{"vmguestname":"markotest2","vmsnapshotname":"markosnapshot"}' -vvvv
ansible-playbook 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: deploy_vm_from_snapshot.yml **************************************************************************************************************************************************************************************************************************************************************************************
1 plays in deploy_vm_from_snapshot.yml

PLAY [Create a VM from a Snapshot] *****************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create VM from Snapshot] *********************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/centos/playbooks/darko/ansible-vmware/deploy_vm_from_snapshot.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: centos
<127.0.0.1> EXEC /bin/sh -c 'echo ~centos && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102 `" && echo ansible-tmp-1541076021.71-60606769302102="` echo /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> PUT /home/centos/.ansible/tmp/ansible-local-29094GnbyM7/tmprKe2eI TO /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/ /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py", line 113, in <module>
    _ansiballz_main()
  File "/home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_vmware_guest_payload_HlDnwQ/__main__.py", line 2394, in <module>
  File "/tmp/ansible_vmware_guest_payload_HlDnwQ/__main__.py", line 2383, in main
  File "/tmp/ansible_vmware_guest_payload_HlDnwQ/__main__.py", line 2054, in deploy_vm
AttributeError: 'NoneType' object has no attribute 'rootSnapshotList'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/centos/.ansible/tmp/ansible-tmp-1541076021.71-60606769302102/AnsiballZ_vmware_guest.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_vmware_guest_payload_HlDnwQ/__main__.py\", line 2394, in <module>\n  File \"/tmp/ansible_vmware_guest_payload_HlDnwQ/__main__.py\", line 2383, in main\n  File \"/tmp/ansible_vmware_guest_payload_HlDnwQ/__main__.py\", line 2054, in deploy_vm\nAttributeError: 'NoneType' object has no attribute 'rootSnapshotList'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
	to retry, use: --limit @/home/centos/playbooks/darko/ansible-vmware/deploy_vm_from_snapshot.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
