### ISSUE TITLE
net_put module leaves empty files behind

### ISSUE THREAD

**Issue by mprasil** [ansible/ansible#47947]
##### SUMMARY

I'm trying to upload file to Mikrotik (routerOS) device using `net_put` like this:

```yaml
      net_put:
          src: "{{ source }}"
          dest: "/{{ destination }}"
          protocol: sftp
```
The module does upload the file successfully, but leaves empty file behind. The file is always named randomly - something like `dd5889ae-9f1c-4566-8722-79dc127b38a6`. (seems to follow some uuid format)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

net_put
##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
--- no extra config ---
```

##### OS / ENVIRONMENT

```
ansible_connection: network_cli
ansible_network_os: routeros
```
##### STEPS TO REPRODUCE

```yaml
      net_put:
          src: "{{ source }}"
          dest: "/{{ destination }}"
          protocol: sftp
```

##### EXPECTED RESULTS

No files are left behind after the upload.

##### ACTUAL RESULTS

The module does upload the file successfully, but leaves empty file behind. The file is always named randomly - something like `dd5889ae-9f1c-4566-8722-79dc127b38a6`. (seems to follow some uuid format)
