### ISSUE TITLE
VMware: Getting error while runing playbook on ansible 2.7 which works well on ansible 2.5.seems backward compatibility is missing

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#47969]
##### SUMMARY

'''
   on ansible 2.5 when i run my playbook i was able to run playbook successfully but same playbook on ansible 2.7 is asking extra parameters

'''

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

'''
vmware_portgroup
'''
##### ANSIBLE VERSION

```paste below
ansible 2.7
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

'''
on ansible 2.5 and 2.7 run below playbook
'''

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add Management Network VM Portgroup
      local_action:
        module: vmware_portgroup
        hostname: 10.243.1.45
        username: xxx
        password: xxx
        switch_name: vSwitch0
        portgroup_name: Management Network
        vlan_id: 0
        validate_certs: no
      tags:
        - add_portgrp

```

##### EXPECTED RESULTS

'''
 Expect playbook to run successfully
'''

##### ACTUAL RESULTS

'''
fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": false, "msg": "one of the following is required: cluster_name, hosts"}
'''

```paste below

```

**Comment by ansibot** [comment]
Hi @umrikar, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_portgroup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_portgroup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@umrikar, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ckotte** [comment]
This behavior was introduced somewhere in the 2.5 release. You have to execute the task like this:
```
- name: Network | Configure Management Port Group
  vmware_portgroup:
    hostname: "{{ vcenter_server if esxi_connect_via_vcenter else inventory_hostname }}"
    username: "{{ vcsa_username if esxi_connect_via_vcenter else esxi_username }}"
    password: "{{ vcsa_password if esxi_connect_via_vcenter else esxi_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    switch_name: "{{ vswitch_mgmt }}"
    portgroup_name: "{{ portgroup_management }}"
    vlan_id: "{{ vlan_id | default(omit) }}"
    validate_certs: "{{ validate_vcenter_certs }}"
  delegate_to: localhost
```

The options `hosts` / `esxi_hostname` and `cluster_name` indeed only make sense if you are connected to a vCenter server. We could change the code to check if we are connected to vCenter via `if self.is_vcenter():` and then require `esxi_hostname` or `cluster_name` instead of making it a requirement in the argument section. 

@Akasurde @dagwieers What do you think? I think the above example would still work if I use `esxi_hostname: "{{ inventory_hostname|default(omit) }}"`. A lot of other host modules have the same behavior. We should change all of them.
