### ISSUE TITLE
acl module performs recursive query after recursive set (present) or rm (absent)

### ISSUE THREAD

**Issue by mback2k** [ansible/ansible#47970]
##### SUMMARY

The acl module currently disallows to use recursive together with state query. This is most likely done due to slow performance of a recursive getfacl and the huge amount of data that could need to be stored in the returned values. Unfortunately the module is written in such a way that the "get" part responsible for a query is always run, even for allowed recursive operations.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Files module: acl

##### ANSIBLE VERSION

```paste below
ansible 2.4.6.0
  config file = /home/[redacted]/Projects/[redacted]/ansible.cfg
  configured module search path = ['/home/[redacted]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/[redacted]/VirtualEnvs/[redacted]/lib/python3.5/site-packages/ansible
  executable location = /home/[redacted]/VirtualEnvs/[redacted]/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```
Unfortunately tested with Ansible 2.4, but the **behaviour is still present** in the code currently **in master**.

##### CONFIGURATION

Not relevant for this bug.

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS as Ansible source and destination.

##### STEPS TO REPRODUCE

```yaml
---
- name: "(Re-)Setting User ACL for Share '{{ share.key }}' and Path '{{ path }}'"
  become: yes
  acl:
    path: "{{ path }}"
    entry: "user:\"{{ item.key }}\":{{ item.value }}"
    state: present
    recursive: yes
  with_dict: "{{ acl.user|default({}) }}"

- name: "(Re-)Setting User defaults ACL for Share '{{ share.key }}' and Path '{{ path }}'"
  become: yes
  acl:
    path: "{{ path }}"
    entry: "default:user:\"{{ item.key }}\":{{ item.value }}"
    state: present
    recursive: yes
  with_dict: "{{ acl.user|default({}) }}"

- name: "(Re-)Setting Group ACL for Share '{{ share.key }}' and Path '{{ path }}'"
  become: yes
  acl:
    path: "{{ path }}"
    entry: "group:\"{{ item.key }}\":{{ item.value }}"
    state: present
    recursive: yes
  with_dict: "{{ acl.group|default({}) }}"

- name: "(Re-)Setting Group defaults ACL for Share '{{ share.key }}' and Path '{{ path }}'"
  become: yes
  acl:
    path: "{{ path }}"
    entry: "default:group:\"{{ item.key }}\":{{ item.value }}"
    state: present
    recursive: yes
  with_dict: "{{ acl.group|default({}) }}"
...
```

##### EXPECTED RESULTS

Fast return of module after ACL modification.

##### ACTUAL RESULTS

Slow return of module due to query happening after ACL modification.

The following command runs quite long and slow behind the scenes:
```paste below
/usr/bin/getfacl --omit-header --absolute-names --recursive [path]
```

This is happening due to the [following code](https://github.com/ansible/ansible/blob/754c377dbd9828eacce4fa857058df483512b799/lib/ansible/modules/files/acl.py#L374-L377) running unconditionally also with recursive = True:
```
    acl = run_acl(
        module,
        build_command(module, 'get', path, follow, default, recursive, recalculate_mask)
    )
```
My suggestion would be to change the code mentioned above to always run with recursive = False.
