### ISSUE TITLE
docker_service fails to start containers

### ISSUE THREAD

**Issue by michalmedvecky** [ansible/ansible#47978]
##### SUMMARY

Recently, my `docker_service` jobs, running regularly on clean VMs, started failing with `Error: service image lookup failed after pull` message:

```
TASK [prometheus : Prometheus compose start] ***********************************
Wednesday 31 October 2018  09:56:20 +0000 (0:00:00.858)       0:04:30.298 ***** 
fatal: [vm01.example.com]: FAILED! => {
    "changed": false
}

MSG:

Error: service image lookup failed after pull - Image 'gitlab.example.com:4567/docker-images/prometheus:master' not found

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- docker_compose module

##### ANSIBLE VERSION

All recent stable versions

##### OS / ENVIRONMENT

Ubuntu 18.04, Ubuntu 16.04

##### STEPS TO REPRODUCE

playbook.yml:

```yaml
- hosts: localhost
  tasks:
    - name: Prometheus compose start
      docker_service:
        recreate: "{{ 'always' }}"
        project_src: "/opt/prometheus"
        pull: yes
```

docker-compose.yml in /opt/prometheus:

```yaml
---
version: "2.1"
services:
  prometheus:
    image: gitlab.example.com:4567/docker-images/prometheus:master
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.external-url=http://vm01.example.com/prometheus/"
    networks:
      - prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - "/opt/prometheus/data:/prometheus"
      - "/opt/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/opt/prometheus/etc/alert_rules.yml:/etc/prometheus/alert_rules.yml"
  blackbox:
    image: gitlab.example.com:4567/docker-images/blackbox-exporter:latest
    restart: always
    networks:
      - prometheus
    ports:
      - 127.0.0.1:9115:9115
    volumes:
      - "/opt/prometheus/etc/blackbox.yml:/etc/blackbox_exporter/config.yml"
  # not starting sachet as required variables are not defined
networks:
  prometheus:
    driver: bridge
```

Play once, fails with:

```
TASK [prometheus : Prometheus compose start] ***********************************
fatal: [vm01.example.com]: FAILED! => {
    "changed": false, 
    "failed": true
}

MSG:

Error: service image lookup failed after pull - Image 'gitlab.example.com:4567/docker-images/prometheus:latest' not found
```

Play again, fails with:

```
TASK [prometheus : Prometheus compose start] *************************************************************************************************************************************************************************************************
Friday 02 November 2018  10:18:14 +0100 (0:00:03.886)       0:02:50.276 ******* 
fatal: [vm01.example.com]: FAILED! => {
    "changed": false
}

MSG:

Error: service image lookup failed after pull - Image 'gitlab.example.com:4567/docker-images/blackbox-exporter:latest' not found
```

Play again, passes.

##### EXPECTED RESULTS

Well, it should work at the first shot

##### ACTUAL RESULTS

See above

##### Workarounds

1. Adding `time.sleep(5)` after https://github.com/ansible/ansible/blob/32e8251f86d53e244c38b8725e5dab164aecd196/lib/ansible/modules/cloud/docker/docker_service.py#L854 causes the problem to disappear
2. Recently, docker-compose new pip package has been released: https://pypi.org/project/docker-compose/#history. The module fails with 1.23.x, and works with 1.21.2

**Comment by ansibot** [comment]
Hi @michalmedvecky, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_config.py)
* [lib/ansible/modules/cloud/docker/docker_container.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)
* [lib/ansible/modules/cloud/docker/docker_image.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_image.py)
* [lib/ansible/modules/cloud/docker/docker_image_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_image_facts.py)
* [lib/ansible/modules/cloud/docker/docker_login.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_login.py)
* [lib/ansible/modules/cloud/docker/docker_network.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_network.py)
* [lib/ansible/modules/cloud/docker/docker_secret.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_secret.py)
* [lib/ansible/modules/cloud/docker/docker_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_service.py)
* [lib/ansible/modules/cloud/docker/docker_stack.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_stack.py)
* [lib/ansible/modules/cloud/docker/docker_swarm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_swarm.py)
* [lib/ansible/modules/cloud/docker/docker_swarm_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_swarm_service.py)
* [lib/ansible/modules/cloud/docker/docker_volume.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_volume.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @akshay196 @chouseknecht @danihodovic @dariko @felixfontein @jwitko @kassiansun @keitwb @olsaki @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ppotvin** [comment]
This issue started when Docker Compose 1.23 was released last week:

https://pypi.org/project/docker-compose/#history

Forcing Docker Compose to any version lower than 1.23 is a possible work-around.

Another work-around is to remove `pull: yes` from the task arguments and do the pull manually:

```yaml
- hosts: localhost
  tasks:
    - name: pull docker images
      command: docker-compose pull
      args:
        chdir: '/opt/prometheus'
      changed_when: False
    - name: Prometheus compose start
      docker_service:
        recreate: "{{ 'always' }}"
        project_src: "/opt/prometheus"
```
