### ISSUE TITLE
ansible_survey module

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#48011]
##### SUMMARY
It is currently not possible using the existing [tower modules](https://docs.ansible.com/ansible/latest/modules/list_of_web_infrastructure_modules.html#ansible-tower) to auto-configure a survey in tower.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
tower_survey

(honestly don't care what we call it as long as it matches the nomenclature that users can find easily.

##### ADDITIONAL INFORMATION
Here is an example of what the module could look like:

```yaml
- name: Add tower host
  tower_survey:
    job_template: "AWS DEPLOY"
    state: present
    questions:
      - prompt: "Name?"
         description: "What do you want to name the instance?"
         ansible_variable_name: instance_name
         answer_type: text
         min_length: 0
         max_length: 1024
         default_answer: TEST_INSTANCE
         required: True
      - prompt: "AWS REGION?"
         description: "What region do you want to deploy to?"
         ansible_variable_name: aws_region
         answer_type: multiple_choice_single_select
         mc_options:
           - us-west-2
           - ca-central-1
           - us-west-1
         default_answer: us-west-1
         required: True
    tower_config_file: "~/tower_cli.cfg"
```
