### ISSUE TITLE
Task fails with loop_control.label and when condition with an undefined variable

### ISSUE THREAD

**Issue by ckotte** [ansible/ansible#48045]
##### SUMMARY
The task fails with loop_control.label and when condition defined if the variable in the when condition isn't defined.

The task will be skipped if I comment out loop_control.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
loop_control
when

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /root/ansible-vmware/ansible.cfg
  configured module search path = [u'/root/ansible-vmware/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
or
```
ansible 2.8.0.dev0 (devel 16032d37c4) last updated 2018/11/03 15:22:58 (GMT +200)
  config file = /root/ansible-vmware/ansible.cfg
  configured module search path = [u'/root/ansible-vmware/library']
  ansible python module location = /ansible/lib/ansible
  executable location = /ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
DEFAULT_FORCE_HANDLERS(/root/ansible-vmware/ansible.cfg) = True
DEFAULT_LOG_PATH(/root/ansible-vmware/ansible.cfg) = /root/ansible-vmware/ansible.log
DEFAULT_MODULE_PATH(/root/ansible-vmware/ansible.cfg) = [u'/root/ansible-vmware/library']
DEFAULT_MODULE_UTILS_PATH(/root/ansible-vmware/ansible.cfg) = [u'/root/ansible-vmware/module_utils/ansible-hpilorest', u'/root/ansible-vmware/module_utils/ansible-vmware-vcsa']
DISPLAY_SKIPPED_HOSTS(/root/ansible-vmware/ansible.cfg) = False
HOST_KEY_CHECKING(/root/ansible-vmware/ansible.cfg) = False
RETRY_FILES_ENABLED(/root/ansible-vmware/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS 7.5

##### STEPS TO REPRODUCE
1. Create a task with loop_control and when condition
2. Don't define the variable

```
- name: Storage | Configure NFS datastores 2/2 (cluster-specific)
  tags: storage, datastores
  vmware_host_datastore:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcsa_username }}"
      password: "{{ vcsa_password }}"
      esxi_hostname: "{{ inventory_hostname }}"
      datastore_name: "{{ item.name }}"
      datastore_type: "{{ item.type }}"
      nfs_server: "{{ item.server }}"
      nfs_path: "{{ item.path }}"
      nfs_ro: "{{ item.read_only }}"
      state: "{{ item.state }}"
      validate_certs: "{{ validate_vcenter_certs }}"
  loop_control:
    label: "{{ item.name }}"
  with_items: "{{ esxi_cluster_nfs_datastores }}"
  delegate_to: "{{ jump_server }}"
  when: esxi_cluster_nfs_datastores is defined
```

##### EXPECTED RESULTS
Task will be skipped.

##### ACTUAL RESULTS

```
TASK [esxi : Storage | Configure NFS datastores 2/2 (cluster-specific)] **********************************************************************************************************************************************************************
fatal: [host]: FAILED! => {"msg": "'None' has no attribute 'name'"}
```

**Comment by ansibot** [comment]
Hi @ckotte, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/loop_control.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/loop_control.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I am not able to reproduce the issue (with `2.6`, `2.7` and latest `devel`). I tried to create a simple reproducer from your example:
```
- hosts: localhost
  gather_facts: no
  tasks:
    - shell: "echo {{ item.state }}"
      loop_control:
        label: "{{ item.name }}"
      with_items: "{{ this_var_is_not_defined }}"
      delegate_to: 192.168.122.97
      when: this_var_is_not_defined is defined
```

What am I missing? Thanks!

needs_info
