### ISSUE TITLE
When condition is not working as expected when decimal or point in playbook

### ISSUE THREAD

**Issue by aksharbarot** [ansible/ansible#48048]
##### SUMMARY

Ansible When condition not working expected when decimal or point in value.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)

##### STEPS TO REPRODUCE

```yaml

- name: Reboot machine when ping average time is above 100.000.
  hosts: all
  gather_facts: false
  become_user: root
  become: yes
  become_method: sudo
  tasks:

     - name: Ensure the ping average time
       shell: ping -c 4 {{ inventory_hostname }} | tail -1| awk '{print $4}' | cut -d '/' -f 2
       register: test
       delegate_to: 10.10.10.10

     - debug:
         var: test.stdout_lines

     - name: Ensure if above task result is above 100 then, run below task
       shell: sudo reboot
       when: test.stdout_lines > "99.000"
       delegate_to: 10.10.10.10

     - debug:
         var: test1.stdout_lines
```

##### EXPECTED RESULTS

If when condition is grater then, it should execute next task but, it didn't.
Below result shows that ping average time is **509.794** so, as per when condition >99.000. it should run next task. 

##### ACTUAL RESULTS

```paste below
PLAY [Transfer and execute a script.] *******************************************************************************************************************************************************

TASK [Ensure the ping average time] *********************************************************************************************************************************************************
changed: [11.11.11.11 -> 10.10.10.10]

TASK [debug] ********************************************************************************************************************************************************************************
ok: [11.11.11.11] => {
    "test.stdout_lines": [
        "**509.794**"
    ]
}

TASK [Ensure if above task result is above 100 then, run below task] ************************************************************************************************************************
skipping: [11.11.11.11]

TASK [debug] ********************************************************************************************************************************************************************************
ok: [11.11.11.11] => {
    "test1.stdout_lines": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP **********************************************************************************************************************************************************************************
11.11.11.11               : ok=3    changed=1    unreachable=0    failed=0
```
