### ISSUE TITLE
KeyError: 'retentionInDays'  bug in cloudwatchlogs_log_group

### ISSUE THREAD

**Issue by ofirshtrull** [ansible/ansible#48077]
##### SUMMARY
since I updated ansible from 2.6.7 to 2.7.1
when i run the cloudwatchlogs_log_group module get KeyError: 'retentionInDays' error in the run
at first, I thought  it was because of my retention value but I get the same error also if I omit this filed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloudwatchlogs_log_group

##### ANSIBLE VERSION

```
2.7.1 (in 2.6.7 it works)
```
##### OS / ENVIRONMENT
macos 14
##### STEPS TO REPRODUCE

```yaml
vars:
LogGroupBase: /aws/kinesisfirehose

streams:
  - {
    DeliveryStreamName: stream1,
    Retention: 3
    }

  cloudwatchlogs_log_group:
    state: present
    retention: "{{ item.Retention }}"
    log_group_name: "{{ LogGroupBase }}/{{ item.DeliveryStreamName }}"
  with_items:
    - "{{ streams }}"

```
##### EXPECTED RESULTS

cfreates new log
changed: [localhost] => (item={u'DeliveryStreamType': u'DirectPut', u'CopyOptions': u"json 'auto' GZIP", u'Prefix': u'aggregations_', u'DataTableName': u'aggregations', u'CompressionFormat': u'GZIP', u'DeliveryStreamName': u'aggregations', u'Retention': 3})
##### ACTUAL RESULTS

```paste below
failed: [localhost] (item={u'DataTableName': u'aggregations', u'DeliveryStreamType': u'DirectPut', u'CompressionFormat': u'GZIP', u'CopyOptions': u"json 'auto' GZIP", u'DeliveryStreamName': u'aggregations', u'Prefix': u'aggregations_', u'Retention': 3}) => {"changed": false, "item": {"CompressionFormat": "GZIP", "CopyOptions": "json 'auto' GZIP", "DataTableName": "aggregations", "DeliveryStreamName": "aggregations", "DeliveryStreamType": "DirectPut", "Prefix": "aggregations_", "Retention": 3}, "module_stderr": "Traceback (most recent call last):
  File \"/Users/ofir/.ansible/tmp/ansible-tmp-1541409165.98-130971251400288/AnsiballZ_cloudwatchlogs_log_group.py\", line 113, in <module>
    _ansiballz_main()
  File \"/Users/ofir/.ansible/tmp/ansible-tmp-1541409165.98-130971251400288/AnsiballZ_cloudwatchlogs_log_group.py\", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/Users/ofir/.ansible/tmp/ansible-tmp-1541409165.98-130971251400288/AnsiballZ_cloudwatchlogs_log_group.py\", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File \"/var/folders/mj/kvnrmwhn607gkyg8_rgpzhm00000gn/T/ansible_cloudwatchlogs_log_group_payload_oJNSm2/__main__.py\", line 282, in <module>
  File \"/var/folders/mj/kvnrmwhn607gkyg8_rgpzhm00000gn/T/ansible_cloudwatchlogs_log_group_payload_oJNSm2/__main__.py\", line 261, in main
  KeyError: 'retentionInDays'
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}

```
