### ISSUE TITLE
[win_user][wrong home directory]

### ISSUE THREAD

**Issue by Sviatik** [ansible/ansible#48076]
##### SUMMARY
When I create user using win_user, and then login to machine, the home directory create as :
```C:\\Users\<username>.HOSTNAME```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT

Windows 2012 R2
##### STEPS TO REPRODUCE

```yaml
- name: Ensure user sftp is present
  win_user:
    name: "{{ sftp_user }}"
    password: "{{ sftp_password }}"
    state: present
    password_expired: no
    password_never_expires: yes
    update_password: on_create
    groups:
      - Users
      - Administrators
```

##### EXPECTED RESULTS

Expect that ansible create home directory:
```C:\\Users\"{{ sftp_user }}"```

##### ACTUAL RESULTS

```json
See output below
```

```paste below
changed: [<HOSTNAME>] => {
    "account_disabled": false,
    "account_locked": false,
    "changed": true,
    "description": "",
    "fullname": "sftp",
    "groups": [
        {
            "name": "Users",
            "path": "WinNT://WORKGROUP/<HOSTNAME>/Users"
        },
        {
            "name": "Administrators",
            "path": "WinNT://WORKGROUP/<HOSTNAME>/Administrators"
        }
    ],
    "name": "sftp",
    "password_expired": false,
    "password_never_expires": true,
    "path": "WinNT://WORKGROUP/<HOSTNAME>/sftp",
    "sid": "S-1-5-21-2495721299-3743047723-3396551749-1004",
    "state": "present",
    "user_cannot_change_password": false
```
