### ISSUE TITLE
Parse cloudformation template from s3 fails

### ISSUE THREAD

**Issue by wysoki89** [ansible/ansible#48080]
##### SUMMARY
Since I got an error "'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200" I uploaded cf template to s3. However, variables an dynamic expressions are not parsed when creating stack.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloudformation

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tomasz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- name: Upload cf templates to s3
  register: s3_template
  aws_s3:
    bucket: "{{ cf_templates_bucket }}"
    mode: put
    src: ../templates/{{item}}
    object: /{{item}}
    region: "{{ cf_stack_region }}"
    profile: "{{AWS_PROFILE}}"
  loop:
    - cloudformation-nv.json.j2
    - cloudformation.json.j2

- name: Create a cloudformation stack in North Virgina
  cloudformation:
    stack_name: "{{ cf_stack_name }}"
    state: "present"
    region: "{{ cf_stack_region_north_virgina }}"
    disable_rollback: true
    template_url: "{{ s3_template.results[0].url }}"
    tags:
      Stack: "{{ cf_stack_name }}"
    profile: "{{AWS_PROFILE}}"
  register: nv_stack

```
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Cloudformation",
  "Parameters": {
    "DomainWebHost": {
      "Type": "String",
      "Description": "Domain name of web",
      "Default": "{{ cf_web_hostname }}"
    }
  },
  "Outputs": {
    "WebCertificateArn": {
      "Value": {"Ref": "WebCertificate"}
    }
  },
  "Resources": {
    "WebCertificate": {
      "Type": "AWS::CertificateManager::Certificate",
      "Properties": {
        "DomainName": {"Ref": "DomainWebHost"},
        "ValidationMethod": "DNS",
      }
    }
  }
}

```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": true, 
    "events": [
        "StackEvent AWS::CloudFormation::Stack cf-test UPDATE_ROLLBACK_COMPLETE", 
        "StackEvent AWS::CertificateManager::Certificate WebCertificate DELETE_COMPLETE", 
        "StackEvent AWS::CloudFormation::Stack cf-test UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS", 
        "StackEvent AWS::CertificateManager::Certificate WebCertificate UPDATE_COMPLETE", 
        "StackEvent AWS::CloudFormation::Stack cf-test UPDATE_ROLLBACK_IN_PROGRESS", 
        "StackEvent AWS::CertificateManager::Certificate WebCertificate UPDATE_FAILED", 
        "StackEvent AWS::CertificateManager::Certificate WebCertificate UPDATE_IN_PROGRESS", 
        "StackEvent AWS::CloudFormation::Stack cf-test UPDATE_IN_PROGRESS"
    ], 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "changeset_name": null, 
            "create_changeset": false, 
            "create_timeout": null, 
            "disable_rollback": true, 
            "ec2_url": null, 
            "events_limit": 200, 
            "notification_arns": null, 
            "profile": "test", 
            "region": "us-east-1", 
            "role_arn": null, 
            "security_token": null, 
            "stack_name": "cf-test", 
            "stack_policy": null, 
            "state": "present", 
            "tags": {
                "Stack": "cf-test"
            }, 
            "template": null, 
            "template_body": null, 
            "template_format": null, 
            "template_parameters": {}, 
            "template_url": "https://cf-test-templates.s3.amazonaws.com/cloudformation-nv.json.j2?AWSAccessKeyId=xxx&Expires=1541414432&Signature=xxx", 
            "termination_protection": null, 
            "validate_certs": true
        }
    }, 
    "log": [
        "AWS::CertificateManager::Certificate WebCertificate UPDATE_FAILED: 1 validation error detected: Value '{{ cf_web_hostname }}' at 'domainName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\\*\\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$ (Service: AWSCertificateManager; Status Code: 400; Error Code: ValidationException; Request ID: d8916603-e0e5-11e8-abca-f9bf695b5b24)"
    ], 
    "output": "Problem with UPDATE. Rollback complete", 
    "stack_outputs": {
        "WebCertificateArn": "arn:aws:acm:us-east-xxx:certificate/xxx"
    }, 
    "stack_resources": [
        {
            "last_updated_time": "2018-11-05T10:31:08.445000+00:00", 
            "logical_resource_id": "WebCertificate", 
            "physical_resource_id": "arn:aws:acm:us-east-xxx:certificate/xxx", 
            "resource_type": "AWS::CertificateManager::Certificate", 
            "status": "UPDATE_COMPLETE", 
            "status_reason": null
        }
    ]
}
```
