### ISSUE TITLE
proxmox_kvm.py raises exception "dictionary changed size during iteration"

### ISSUE THREAD

**Issue by alfredosola** [ansible/ansible#48096]
##### SUMMARY
When creating a Proxmox kvm:
fatal: [localhost]: FAILED! => {"changed": false, "msg": "creation of qemu VM _name_ with vmid _number_ failed with exception=dictionary changed size during iteration"}

This only happens if a dict is passed for creating several network interfaces, but not if a single network interface is created.

It looks very similar to #37454 and #46755.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm.py

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /Users/alfredo/.ansible.cfg
  configured module search path = ['/Users/alfredo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jul 23 2018, 20:22:55) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```
DEFAULT_FORKS(/Users/alfredo/.ansible.cfg) = 10
DEFAULT_HOST_LIST(/Users/alfredo/.ansible.cfg) = ['/Users/alfredo/ansible/ansible_hosts']
HOST_KEY_CHECKING(/Users/alfredo/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Mac OS X 10.14 "Mojave". Ansible installed with brew.

##### STEPS TO REPRODUCE
```yaml
    - proxmox_kvm:
        api_user    : "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host    : hostname.local
        name        : test
        node        : nodename
        net         : "{{ ports }}"
        virtio      : '{"virtio0":"a1-nfs:1,format=vmdk"}'
        cores       : 2
        memory      : 1024
        onboot      : yes
        vmid        : 1000
```

Where ports is
```
{
        "net0": "virtio=00:50:56:8d:4a:e2,bridge=vmbr0",
        "net1": "virtio=00:50:56:8d:26:85,bridge=vmbr0"
}
```

##### EXPECTED RESULTS

Virtual machine created with two interfaces

##### ACTUAL RESULTS
Exception - machine is not created

```paste below
The full traceback is:
  File "/var/folders/w2/5kld20x1515d264vrm5y51c00000gp/T/ansible_proxmox_kvm_payload_4udnbe2g/__main__.py", line 1017, in main
    watchdog=module.params['watchdog'])
  File "/var/folders/w2/5kld20x1515d264vrm5y51c00000gp/T/ansible_proxmox_kvm_payload_4udnbe2g/__main__.py", line 706, in create_vm
    for k in kwargs.keys():
```
