### ISSUE TITLE
[Errno 2] No such file or directory - thrown when executing a command

### ISSUE THREAD

**Issue by 0x4139** [ansible/ansible#48108]
##### SUMMARY

`[Errno 2] No such file or directory` is thrown when executing a command or a shell instruction, might be something i missed.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/0x4139/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:18:58) [Clang 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS mojave
##### STEPS TO REPRODUCE

```yaml

  - name: Fetching join command for workers
    shell: kubeadm token create --print-join-command
    register: join_command_output
  - name: Setting a up a dummy host to store the join command to work on cross tasks
    add_host:
      name: "KUBERNETES_TOKEN_HOLDER"
      token: "{{join_command_output.stdout_lines}}"
--------
 - name: Bootstrap the worker Nodes
    command: "{{ hostvars['KUBERNETES_TOKEN_HOLDER']['token']| regex_replace( 'kubeadm join','kubeadm join --cri-socket /run/containerd/containerd.sock') }}"
    become: true
    become_user: root


in the end we endup with this content (or similar)
kubeadm join 10.135.123.4:6443 --token no5mfb.exn7fhkx2yunz6h5 --discovery-token-ca-cert-hash sha256:b9aba233a9ec6290eaefe175d15e6e34e23ad43ce0490717376f518c0d9e3606z
```

##### EXPECTED RESULTS

To work
##### ACTUAL RESULTS

```paste below
 FAILED! => {"changed": false, "cmd": "'[/usr/bin/kubeadm join --cri-socket /run/containerd/containerd.sock 10.135.123.4:6443 --token fmud0x.iadfrunkuvbu59yb --discovery-token-ca-cert-hash sha256:b9aba233a9ec6290eaefe175d15e6e34e23ad43ce0490717376f518c0d9e3606]'", "msg": "[Errno 2] No such file or directory", "rc": 2}
```
