### ISSUE TITLE
apt_key module to behave like apt-key

### ISSUE THREAD

**Issue by jpcaruana** [ansible/ansible#4810]
Hi, 

as mentionned on the mailing list, it would it be great for apt_key module to behave like apt-key. For instance, adding a "keyserver" parameter, because sometimes there is no url to download from. This line is valid (and fully working) under my ubuntu :

``` bash
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 3D3B6BD098080A60
```

It would be great to write something similar in ansible :

``` yaml
- name: Download collectd public key for apt
  apt_key: keyserver=http://keyserver.ubuntu.com
  id=3D3B6BD098080A60 state=present
```

Today, I have to write this:

``` yaml

- name: Download collectd public key for apt
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x3D3B6BD098080A60
  state=present
```

BTW, my ansible version is :

``` bash
$ ansible --version
ansible 1.3.1
```

(related to #4544)
