### ISSUE TITLE
win_audit_policy_system module not changing the value

### ISSUE THREAD

**Issue by fsulbaran** [ansible/ansible#48117]
##### SUMMARY
Trying to use ansible on an ec2 windows server 2016.  winRM connection works and other modules run perfectly fine.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_audit_policy_system

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = None
  configured module search path = [u'/Users/fsulbaran/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 16:36:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```
##### OS / ENVIRONMENT
windows server 2016
##### STEPS TO REPRODUCE

simple playbook and run  win_audit_policy_system to change something.

```yaml
- name: Ensure 'Audit System Extension' is set to 'Success and Failure'
  win_audit_policy_system:
    subcategory: Security System Extension
    audit_type: success, failure
```

##### EXPECTED RESULTS

change local group policy to "success and failure"

```json
changed: [10.8.20.177] => {
    "changed": true,
    "current_audit_policy": {
        "security system extension": "success and failure"
    }
}
```
I do get the expected output by ansible.

##### ACTUAL RESULTS

When I go to check on the Machine if the state of the policy was changed was really applied I found that is not. I already restarted the machine and nothing. Any ideas what's going on?

State/vaule does not change: https://i.stack.imgur.com/Mu1jS.png

Thank you for your time :-)
