### ISSUE TITLE
loop_control is evaluated before when

### ISSUE THREAD

**Issue by mooninite** [ansible/ansible#48122]
##### SUMMARY
Tasks that use loops and process the results are evaluating loop_control before the when condition is tested. If a previous loop was skipped, causing results to not be defined, the loop_control evaluation fails and causes the play to end in failure. The when condition should override everything and if the when fails (causing a skip) nothing else in the task should be evaluated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

loop_control ?

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/michael/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 23 2018, 18:19:07) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 29 x86_64

##### STEPS TO REPRODUCE

```yaml
- connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: debug
      vars:
        debug_var: "true"
      when: debug_var == "false"
      stat:
        path: "{{ item }}"
      loop:
        - /tmp
        - /bin
      register: debug_test
    - name: debug2
      vars:
        test_var: "true"
      when: test_var == "false"
      debug:
        var: item.stat.path
      loop: "{{ debug_test.results }}"
      loop_control:
        label: "{{ item.stat.path }}"
```

##### EXPECTED RESULTS

The playbook should skip the second task. If you comment out loop_control the task is skipped.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => 
  msg: '''dict object'' has no attribute ''stat'''
```
