### ISSUE TITLE
Ability to temporarily mount a filesystem without altering /etc/fstab

### ISSUE THREAD

**Issue by ahuffman** [ansible/ansible#48134]
##### SUMMARY
Ability to perform temporary mounts without altering /etc/fstab.  Currently anything done with the mount module needs to manipulate /etc/fstab.

Additional parameter is needed to perform temporary mounts, such as with an ISO image that would be unmounted later in a play.  Currently this can't be done with the mount module, as altering the /etc/fstab is required.  Maybe call it "modify_fstab" and have it be a boolean.   Currently the only way to achieve this is via the command module using direct mount/unmount commands.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mount, fstab

##### ADDITIONAL INFORMATION
To mount an ISO image temporarily for pulling in data, but not make an entry in /etc/fstab.

```yaml
- name: Mount an ISO Temporarily
  mount:
    src: /path/to/my/iso.iso
    path: /path/to/mount/my/iso
    fstype: iso9660
    opts: ro
    modify_fstab: no
    state: mounted

- name: Unmount an ISO
  mount:
    path: /path/to/unmount/my/iso
    modify_fstab: no
    state: unmounted
```
