### ISSUE TITLE
win_chocolatey: chocolatey fails when no sources configured and package name is chocolatey

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#48147]
##### SUMMARY
When there are no sources configured and Chocolatey goes to check if itself is installed it will fail saying there are no sources enabled. While this would be true for other packages, the Chocolatey
package itself should not fail if Chocolatey is already installed. This would be a rare occurrence but may occur with the following playbook

```
---
- hosts: vagrant-windows
  gather_facts: no

  tasks:
  - name: ensure Chocolatey is installed
    win_chocolatey:
      name: chocolatey
      state: present

  - name: remove the public Chocolatey source
    win_chocolatey_source:
      name: chocolatey
      state: absent

  - name: install internal Chocolatey source
    win_chocolatey_source:
      name: http://choco/chocolatey
      state: present
```

If the 3rd task failed for whatever reason and we go to rerun the playbook it will fail on the first task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```paste below
devel
2.7
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Windows

##### STEPS TO REPRODUCE
Run this playbook twice, the 2nd run will fail on the `win_chocolatey` step

```yaml
---
- hosts: vagrant-windows
  gather_facts: no

  tasks:
  - win_chocolatey:
      name: chocolatey
      state: present

  - win_chocolatey_source:
      name: chocolatey
      state: absent
```

##### EXPECTED RESULTS
Every works fine with no changes recorded

##### ACTUAL RESULTS
```paste below
TASK [win_chocolatey] **********************************************************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:10
Using module file /Users/jborean/dev/ansible/lib/ansible/modules/windows/win_chocolatey.ps1
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 55986 TO 127.0.0.1
EXEC (via pipeline wrapper)
fatal: [vagrant-win]: FAILED! => {
    "changed": false, 
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output chocolatey", 
    "msg": "Error checking installation status for the package 'chocolatey'", 
    "rc": 1, 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "Unable to search for packages when there are no sources enabled for\r\n packages and none were passed as arguments.\r\n", 
    "stdout_lines": [
        "Unable to search for packages when there are no sources enabled for", 
        " packages and none were passed as arguments."
    ]
}
```

We should be skipping the package check/install for the `chocolatey` package when `state: present` as it refers to itself.
