### ISSUE TITLE
Lineinfile does not appear to work with global playbook variables

### ISSUE THREAD

**Issue by phillipuniverse** [ansible/ansible#4815]
Use case:
1. I have 2 roles: 'jenkins' and 'common'
2. The 'jenkins' role declares that it is a dependent of 'common' via meta/main.yml (this appears to work)
3. In my playbook, I specify that my hosts is a member of the jenkins role:

``` yml
- hosts: build-server
  remote_user: root
  roles:
    - jenkins
```
1. I have a group_vars/build-server file with the following:

``` yml

---
infrastucture_access_ips: ['1.2.3.4, '2.3.4.5', '6.7.8.9']
```
1. Within my common role I am using a Jinja filter to join the list by whitespace:

``` yml
- name: Whitelist the infrastructure IP addresses in fail2ban
  lineinfile: dest=/etc/fail2ban/jail.conf regexp=^ignoreip line="{{ 'ignoreip = ' ~ infrastructure_access_ips|join(' ') }}" state=present
  notify: reload fail2ban
```

When I run the playbook I get:

``` shell
 _____________________________________________________________ 
/ TASK: common | Whitelist the infrastructure IP addresses in \
\ fail2ban                                                    /
 ------------------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


fatal: [x.x.x.x] => One or more undefined variables: 'infrastructure_access_ips' is undefined

FATAL: all hosts have already failed -- aborting
```

I originally had this for my lineinfile module declaration but it also did not work:

``` yml
lineinfile: dest=/etc/fail2ban/jail.conf regexp=^ignoreip line="ignoreip = {{ infrastructure_access_ips|join(' ') }}" state=present
```

This also does not work when I define it with set_fact. I have other variables defined in group_vars/build-server not shown that I am using with `with_items` elsewhere in the role that work fine.
