### ISSUE TITLE
Tags do not work to call specific part of playbook

### ISSUE THREAD

**Issue by rads18** [ansible/ansible#48178]
##### SUMMARY
I am using tags for the first time.
FYI I am running this playbook on our company wide shared ANSIBLE TOWER(AWX).

From ansible docs:  https://docs.ansible.com/ansible/2.6/user_guide/playbooks_tags.html

"If you have a large playbook it may become useful to be able to run a specific part of the configuration 
without running the whole playbook."  <<<<<------------------------ Does not work for me, run the entire playbook.

I saw another post on github, with many others raise similar concern, but do not see any solution posted for it: 
https://github.com/ansible/ansible/issues/5952

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tags
##### ANSIBLE VERSION

```
"ansible_version": "2.6.4"
AWX "version": "1.0.8.0",
```

##### CONFIGURATION

```
Don't have access to run it.
```

##### OS / ENVIRONMENT

LINUX/SOLARIS
##### STEPS TO REPRODUCE

I have a playbook(play1) with multiple tasks, each for different operating system.

I have host attributes collected for each host in my dynamic inventory.

In my main playbook(main) I to want to pass the ostype as a tag and then only call part of playbook(play1) for the respective OS.

```
Main.yml
---
- hosts: all
  gather_facts: false


  tasks:

   - import_tasks: play.yml 
     tags: "{{ ostyp }}"


Play.yml

---
- name: Check Logs LINUX
  shell: cat /var/log/messages|grep -iv ansible|tail -2
  register: logck
  tags:
    - LINUX
  

- name: Check Logs SUN
  shell: cat /var/adm/messages|tail -2
  register: logck
  tags:
    - SOLARIS

```

##### EXPECTED RESULTS

This against to "LINUX" hosts

```
SSH password: 
SUDO password[defaults to SSH password]: 

PLAY [all] *********************************************************************
TASK [Check Logs LINUX] ********************************************************
changed: [Host1]
changed: [Host2]

PLAY RECAP *********************************************************************
Host1               : ok=2    changed=2    unreachable=0    failed=0   
Host2             : ok=2    changed=2    unreachable=0    failed=0 
```

##### ACTUAL RESULTS

This against to "LINUX" hosts

```
SSH password: 
SUDO password[defaults to SSH password]: 
PLAY [all] *********************************************************************
TASK [Check Logs LINUX] ********************************************************
changed: [Host1]
changed: [Host2]
TASK [Check Logs SUN] **********************************************************
changed: [Host1]
changed: [Host2]
PLAY RECAP *********************************************************************
Host1               : ok=2    changed=2    unreachable=0    failed=0   
Host2             : ok=2    changed=2    unreachable=0    failed=0 
```

Let me know if any other information is needed.
Please help!

thanks
Rads

**Comment by ansibot** [comment]
Hi @rads18, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration/targets/shadowed_module/library/tags](https://github.com/ansible/ansible/blob/devel/test/integration/targets/shadowed_module/library/tags)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This does not appear to be a bug report.

A better way to do this would be to use conditionals and facts so you don't have to remember to pass in tags every time.

```yaml
- name: Check Logs LINUX
  shell: cat /var/log/messages|grep -iv ansible|tail -2
  register: logck
  when: ansible_facts['system'] == 'Linux'

- name: Check Logs SUN
  shell: cat /var/adm/messages|tail -2
  register: logck
  when: ansible_facts['system'] == 'SunOS'
```

For further help with using tags, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
