### ISSUE TITLE
Ansible 1.4 hangs during installation linux packages (Service Pack for Proliant) provided by HP

### ISSUE THREAD

**Issue by przemolb** [ansible/ansible#4819]
Create /etc/yum.repos.d/spp.repo:
[spp]
name=Service Pack for ProLiant
baseurl=http://downloads.linux.hp.com/repo/spp/rhel/$releasever/$basearch/current
enabled=0
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/GPG-KEY-ServicePackforProLiant

Now using the following playbook:

``` yaml

---
- hosts: '{{ hosts }}'
  connection: ssh
  user: root
  tasks:
  - name: install hpvca package
    #yum: name=hpvca state=latest enablerepo=spp
    #command: yum -y --enablerepo=spp install hpvca
    shell: yum -y --enablerepo=spp install hpvca
```

I am trying to install this package. The required package is installed but ansible doesn't stop working and doesn't give you prompt back (I need to CTRL-C it ...). None of mentioned lines (yum/command/shell modules) works.
