### ISSUE TITLE
OS specific variables take precedence over host specific

### ISSUE THREAD

**Issue by nextus** [ansible/ansible#4822]
Hello. My ansible playbook defines some variables for role depends on which OS is using:

```
- name: deploy configuration into storage servers
  hosts: storages
  sudo: yes
  vars_files:
    - "group_vars/{{ ansible_system }}.yml"
  roles:
    - storages
```

And now I need to change some variables for specific host in spite of which OS is using. The most reasonable way doesn't work: I've tried to define this variable in inventory file but vars_files directive from playbook take precedence over it. I've read about parameterized roles but for my task it looks like a greasy hack.
In my opinion this bug makes inventory variable definitions totally useless.
