### ISSUE TITLE
eos_config with network_cli transport cannot create configuration sessions

### ISSUE THREAD

**Issue by skanagal** [ansible/ansible#48280]
##### SUMMARY
Issue is that when I try to create a custom 'configuration session' via Ansible eos_config module, the playbook errors out.

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION

```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = ['/Users/sureshk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.5/bin/ansible
  python version = 3.5.4rc1 (v3.5.4rc1:385b3686ff, Jul 23 2017, 23:51:54) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION

PLAYBOOK:

```
---
- hosts: all
  connection: local

  gather_facts: no
  no_log: False
  any_errors_fatal: true

  tasks:
    - name: Load config session
      eos_config:
        lines:
          - vlan 1000
          - name verizon
        before: configure session testing
        provider: "{{ provider|default(omit) }}"
      no_log: False

    - name: configure timer
      eos_command:
        commands: configure session testing commit timer 00:01:00
        provider: "{{ provider|default(omit) }}"
      no_log: False

    - name: checking if vlan 1000 exists in running-config
      eos_command:
        commands: show vlan 1000
        provider: "{{ provider|default(omit) }}"
      no_log: False
      register: vlan_info

    - name: commiting session if VLAN 100 exists
      eos_command:
        commands: configure session testing commit
        provider: "{{ provider|default(omit) }}"
      no_log: False
      # when: 1000 in vlan_info['stdout_lines'][0]['vlans'].keys()
```

Provider info:

```
provider:
  host: "{{ inventory_hostname }}"
  username: "cvpadmin"
  password: "admin"
  authorize: yes
  transport: cli
```

##### OS / ENVIRONMENT
MAC OS

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS
Expect the playbook to create config session called "testing" on the Arista node.

##### ACTUAL RESULTS

> sudo ansible-playbook -i hosts test.yml -vvv
Password:
ansible-playbook 2.5.0
  config file = None
  configured module search path = ['/Users/sureshk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.5/bin/ansible-playbook
  python version = 3.5.4rc1 (v3.5.4rc1:385b3686ff, Jul 23 2017, 23:51:54) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
No config file found; using defaults
Parsed /Users/sureshk/Automation/vz-ansible-issue/hosts inventory source with ini plugin

PLAYBOOK: test.yml *************************************************************************************************************************************
1 plays in test.yml

PLAY [all] *********************************************************************************************************************************************
META: ran handlers

TASK [Load config session] *****************************************************************************************************************************
task path: /Users/sureshk/Automation/vz-ansible-issue/test.yml:11
<10.92.225.26> using connection plugin network_cli (was local)
Using module file /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ansible/modules/network/eos/eos_config.py
<10.92.225.26> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.92.225.26> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.92.225.26> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967 `" && echo ansible-tmp-1541540937.21482-155780473996967="` echo /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967 `" ) && sleep 0'
<10.92.225.26> PUT /Users/sureshk/.ansible/tmp/ansible-local-41517ekv8t8wn/tmpoafv8ma_ TO /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967/eos_config.py
<10.92.225.26> EXEC /bin/sh -c 'chmod u+x /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967/ /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967/eos_config.py && sleep 0'
<10.92.225.26> EXEC /bin/sh -c 'python /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967/eos_config.py && sleep 0'
<10.92.225.26> EXEC /bin/sh -c 'rm -f -r /Users/sureshk/.ansible/tmp/ansible-tmp-1541540937.21482-155780473996967/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_QQZP1D/ansible_module_eos_config.py", line 491, in <module>
    main()
  File "/tmp/ansible_QQZP1D/ansible_module_eos_config.py", line 392, in main
    config_text = get_running_config(module)
  File "/tmp/ansible_QQZP1D/ansible_module_eos_config.py", line 305, in get_running_config
    contents = get_config(module, flags=flags)
  File "/tmp/ansible_QQZP1D/ansible_modlib.zip/ansible/module_utils/network/eos/eos.py", line 462, in get_config
  File "/tmp/ansible_QQZP1D/ansible_modlib.zip/ansible/module_utils/network/eos/eos.py", line 151, in get_config
  File "/tmp/ansible_QQZP1D/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
ansible.module_utils.connection.ConnectionError: %b requires bytes, or an object that implements __bytes__, not 'str'

fatal: [10.92.225.26]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_QQZP1D/ansible_module_eos_config.py\", line 491, in <module>\n    main()\n  File \"/tmp/ansible_QQZP1D/ansible_module_eos_config.py\", line 392, in main\n    config_text = get_running_config(module)\n  File \"/tmp/ansible_QQZP1D/ansible_module_eos_config.py\", line 305, in get_running_config\n    contents = get_config(module, flags=flags)\n  File \"/tmp/ansible_QQZP1D/ansible_modlib.zip/ansible/module_utils/network/eos/eos.py\", line 462, in get_config\n  File \"/tmp/ansible_QQZP1D/ansible_modlib.zip/ansible/module_utils/network/eos/eos.py\", line 151, in get_config\n  File \"/tmp/ansible_QQZP1D/ansible_modlib.zip/ansible/module_utils/connection.py\", line 146, in __rpc__\nansible.module_utils.connection.ConnectionError: %b requires bytes, or an object that implements __bytes__, not 'str'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

NO MORE HOSTS LEFT *************************************************************************************************************************************
	to retry, use: --limit @/Users/sureshk/Automation/vz-ansible-issue/test.retry

PLAY RECAP *********************************************************************************************************************************************
10.92.225.26               : ok=0    changed=0    unreachable=0    failed=1
