### ISSUE TITLE
os_security_group_rule: protocol: None

### ISSUE THREAD

**Issue by let-thomas** [ansible/ansible#48292]
##### SUMMARY
Cannot delete rule for "all" protocols. Tested were protocol= all and none.

In Horizon
Egress | IPv4 | ANY | 0 - 65535 | 0.0.0.0/0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_security_group_rule

##### ANSIBLE VERSION
```
ansible 2.6.0
ansible 2.7.1
````
##### STEPS TO REPRODUCE

```
- name: test
  hosts: localhost
  gather_facts: false
  tasks:
    - os_security_group_rule:
        cloud: onecloud
        security_group: https
        state: absent
        ethertype: IPv4
        protocol: None
        #protocol: all
        port_range_min: 0
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
        direction: egress 
```

Reported rule is
{
    "direction": "egress",
    "ethertype": "IPv4",
    "id": "865d0143-a567-47b4-8cba-f3a0c8030090",
    "port_range_max": 65535,
    "port_range_min": 0,
    "protocol": "any",
    "remote_group_id": null,
    "remote_ip_prefix": "0.0.0.0/0",
    "security_group_id": "584c95e0-da17-4d45-bb4b-7ebaf6083e6c",
    "tenant_id": "xxxxx"
}

##### EXPECTED RESULTS
ok: [localhost]

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of protocol must be one of: None, tcp, udp, icmp, 112, got: None"}
```
