### ISSUE TITLE
Mount Module - states absent/unmounted do not unmount device

### ISSUE THREAD

**Issue by programingnotes** [ansible/ansible#48313]
##### SUMMARY

Running **mount module**  with state `unmounted`/`absent` does not result in either of the expected results: 

- if `unmounted`, the device will be unmounted without changing fstab.
- `absent` specifies that the device mount's entry will be removed from fstab and will also unmount the device and remove the mount point. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[mount module](https://docs.ansible.com/ansible/latest/modules/mount_module.html)

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.7.0
  config file = /Users/pnotes/Code/Ansible/DigitalOceanProjects/TestAttachedVolume/ansible.cfg
  configured module search path = ['/Users/pnotes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pnotes/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ansible
  executable location = /Users/pnotes/.pyenv/versions/3.6.4/bin/ansible
  python version = 3.6.4 (default, Feb 26 2018, 21:07:35) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```paste below
AULT_VAULT_PASSWORD_FILE(/Users/pnotes/Code/Ansible/DigitalOceanProjects/TestAttachedVolume/ansible.cfg) = /Users/pnotes/.vault_pass.txt
```

##### OS / ENVIRONMENT
`target OS versions => Ubuntu 18.04tls`

##### STEPS TO REPRODUCE

Given this role below:

```yaml
---
- name: Check for mounted volume devices currently attached to droplet
  stat:
    path: "{{volume_by_id}}{{ item }}"
  register: sym
  loop: 
    - "{{volume_names[0]}}"
    - "{{volume_names[1]}}"

- name: Unmount volume devices currently attached to droplet
  mount:
    src: "{{volume_by_id}}{{ item }}"
    path: /mnt/"{{item}}"
    fstype: ext4 
    opts: defaults
    dump: 0
    passno: 2
    state: unmounted
  loop: "{{ sym.results | selectattr('stat.exists') | map(attribute='item') | list }}"
```

##### EXPECTED RESULTS

I expect the device **`"{{volume_by_id}}{{ item }}"`** mounted at **`/mnt/"{{item}}"`** to no longer be mounted; that is `lsblk` should return: 

```
root@simple-test:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0   20G  0 disk /mnt/logs
vda     252:0    0   25G  0 disk 
├─vda1  252:1    0 24.9G  0 part /
├─vda14 252:14   0    4M  0 part 
└─vda15 252:15   0  106M  0 part /boot/efi
```

##### ACTUAL RESULTS

Instead device is still mounted: 

```paste below
root@simple-test:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0   20G  0 disk /mnt/logs
vda     252:0    0   25G  0 disk 
├─vda1  252:1    0 24.9G  0 part /
├─vda14 252:14   0    4M  0 part 
└─vda15 252:15   0  106M  0 part /boot/efi
```

**Comment by ansibot** [comment]
Hi @programingnotes, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/mount.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/mount.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Thanks for reporting this. Please could you provide content of your `/proc/self/mountinfo` (before and after you run the tasks) as well as the values of all variables you use in your tasks?

**Comment by ansibot** [comment]
cc @skvidal
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JPvRiel** [comment]
Noticed this bug too. Example of my current unpleasant workaround to force it to unmount

```yaml
        - name: Unmount the default virt storage pool dir
          mount:
            path: /var/lib/libvirt/images
            state: '{{ item }}'
          with_items:
            - unmounted
            - absent
```

In my case, ansible 2.7.2 against a RHEL 7.5 target/server from an Ubuntu 16.04.5 LTS controller.
