### ISSUE TITLE
VMware: vcenter_folder module creates an error in vCenter

### ISSUE THREAD

**Issue by UnknownGnome** [ansible/ansible#48310]
##### SUMMARY
Using vcenter_folder to create a folder. After the folder is created by the first run, subsequent runs cause the vCenter to display an error: 

> The name 'folder-name' already exists.

 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vcenter_folder

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/ansible/modules/remote_management/ucsm-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ansible/modules/remote_management/ucsm-ansible/library']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

```

##### STEPS TO REPRODUCE

```yaml
- name: Create Datastore folders
      vcenter_folder:
        hostname: "{{secret.vcenter}}"
        username: "{{secret.vcusername}}"
        password: "{{secret.vcpassword}}"
        validate_certs: no
        datacenter: AnsibleDC1
        folder_name: Datastores
        folder_type: datastore
        state: present
```

##### EXPECTED RESULTS

If the folder exists, the vCenter should not generate an error.

##### ACTUAL RESULTS

```paste below

```
