### ISSUE TITLE
use encryption password some work, but some can not and has error

### ISSUE THREAD

**Issue by hoyeunglee** [ansible/ansible#48330]
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```
---
- hosts: cdx01ms03group
  gather_facts: false
  connection: local
  vars:
     date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
     cli:
        host: "{{ ansible_host }}"
        username: "noc"
        password: !vault |
          ...
        authorize: yes
        auth_pass: !vault |
          ...

  tasks:
   - name: show run
     ios_command:
       commands:
         - show run
       provider: "{{ cli }}"
     register: result
     ignore_errors: yes
     check_mode: no

   - name: save output to /etc/ansible/backups
     copy:
       content: "{{ result.stdout }}"
       dest: "/etc/ansible/backups/{{ inventory_hostname }}_config_{{ date }}.txt"

```

 ansible-playbook -s cdx01ms03.yml --vault-password-file vault_pass.txt

unable to elevate privilege to enable mode, at prompt [None] with error: For matched prompt '\nPassword:

use encryption password some work, but some can not has error, same config, and can login with putty but some can not elevate to to enable mode
