### ISSUE TITLE
docker_swarm: manager node can't join

### ISSUE THREAD

**Issue by motherboard1999** [ansible/ansible#48335]
##### SUMMARY
If I use the docker_swarm module to join another manager in an existing docker swarm, the swarm don't work anymore. 

##### ISSUE TYPE
The second master don't join correctly. 
Error message of "docker node ls" at the master: `Error response from daemon: rpc error: code = Unknow desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.`

##### COMPONENT NAME
---
- name: Join as manager
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[groups['docker_manager_first'][0]]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars[groups['docker_manager_first'][0]]['manager_token'] }}"
    remote_addrs: [ "{{ hostvars[groups['docker_manager_first'][0]]['ansible_default_ipv4']['address'] }}:2377" ]
  retries: 3
  delay: 20

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /Users/X/.ansible.cfg
  configured module search path = ['/Users/X/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.0/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jun 29 2018, 20:13:13) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below
DEFAULT_GATHER_SUBSET(/Users/X/.ansible.cfg) = all,!facter,!ohai
DEFAULT_HOST_LIST(/Users/X/.ansible.cfg) = ['/Users/X/Git/ansible-dev-env/vagrant_inventory.py']
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/X/.ansible.cfg) = ['/Users/X/Git/ansible-roles/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/X/.ansible.cfg) = Ansible managed
file: {file}
DEFAULT_ROLES_PATH(/Users/X/.ansible.cfg) = ['/Users/X/Git/ansible-roles/roles']
HOST_KEY_CHECKING(/Users/X/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/X/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Client: macOS 10.14.0
Server: Linux CentOS 7.5

##### STEPS TO REPRODUCE

Simply create a docker swam with the ansible module and try to join a second master.

```yaml
---
- name: Create primary swarm manager
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"

- name: Get manager token
  shell: docker swarm join-token -q manager
  register: manager_token

- name: Save manager token
  set_fact: manager_token="{{ manager_token.stdout }}"

- name: Get worker token
  shell: docker swarm join-token -q worker
  register: worker_token

- name: Save worker token
  set_fact: worker_token="{{ worker_token.stdout }}"
```
```
---
- name: Join as manager
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[groups['docker_manager_first'][0]]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars[groups['docker_manager_first'][0]]['manager_token'] }}"
    remote_addrs: [ "{{ hostvars[groups['docker_manager_first'][0]]['ansible_default_ipv4']['address'] }}:2377" ]
  retries: 3
  delay: 20
```

##### EXPECTED RESULTS

The swarm wouldn't be run anymore, because two leaders are inside.

##### ACTUAL RESULTS

The playbook will show the error below and stop, because the swarm is not 
reachable.

```paste below
fatal: [10.0.206.201]: FAILED! => {"changed": false, "msg": "Can not join the Swarm Cluster: 503 Server Error: Service Unavailable (\"Timeout was reached before node joined. The attempt to join the swarm will continue in the background. Use the \"docker info\" command to see the current swarm status of your node.\")"}
```
