### ISSUE TITLE
zabbix_template: result is always 'changed'

### ISSUE THREAD

**Issue by zasca** [ansible/ansible#48337]
##### SUMMARY
Result is always 'changed' when imported same template.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_template.py

##### ANSIBLE VERSION
2.6.4

##### OS / ENVIRONMENT
Ubuntu 18.04.1 LTS

##### STEPS TO REPRODUCE

```yaml
- name: test zabbix_template
  local_action:
    module: zabbix_template
    server_url: "{{ zabbix.server.url }}"
    login_user:     "{{ zabbix.server.login.user }}"
    login_password: "{{ zabbix.server.login.pass }}"
    state: present
    template_name: Template TEST Web
    template_groups: Templates
    template_json:
      zabbix_export:
        templates:
        - templates: []
          description: 'TEST'
          template: Template TEST Web
          groups:
          - name: Templates
          name: "[Custom Template] TEST Web"
        version: '3.0'
        groups:
        - name: Templates
```

##### EXPECTED RESULTS
```
TASK [test zabbix_template] ********************************************
ok: [test]
```

##### ACTUAL RESULTS

```paste below
TASK [test zabbix_template] ********************************************
changed: [test]
```

**Comment by ansibot** [comment]
Hi @zasca, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/zabbix/zabbix_template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/zabbix/zabbix_template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @D3DeFi @eikef
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by D3DeFi** [comment]
thank you for opening this issue @zasca. I will try to reproduce it and implement the fix as soon as I am able to :)

**Comment by vzabawski** [comment]
I'm having this issue in Ansible 2.8 with Zabbix 4.2.
I have two template import statements: one import templates that are not linked to any other templates, and other import templates that have dependencies from other templates. For some reason first statement shows *ok* while the second statement always shows its state as *changed* but not for all templates, only for some of them. And it seems like *ok* and *changed* statuses alternate one by one.

```
- name: Import Zabbix templates
  local_action:
    module: zabbix_template
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_login }}"
    login_password: "{{ zabbix_password }}"
    template_name: "{{ item.split('/')[-1] | replace('.json','')}}"
    template_json: "{{ lookup('file', '{{ item }}' ) }}"
    template_groups:
      - Templates
    state: present
  with_fileglob:
    - "../files/zabbix_templates/*.json"
  when: upload_templates
  tags:
  - templates


# Some templates have linked templates, so need to import them after linked templates have been uploaded
- name: Import dependent Zabbix templates
  local_action:
    module: zabbix_template
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_login }}"
    login_password: "{{ zabbix_password }}"
    template_name: "{{ item.split('/')[-1] | replace('.json','')}}"
    template_json: "{{ lookup('file', '{{ item }}' ) }}"
    template_groups:
      - Templates
    state: present
  with_fileglob:
    - "../files/zabbix_templates/dependent/*.json"
  when: upload_templates
  tags:
  - templates
```

Output:
```
TASK [Import Zabbix templates] *************************************************
ok: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/Linux Process Monitoring.json)
ok: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/Zabbix Server Monitoring.json)
ok: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/MySQL Monitoring.json)
ok: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/Java Application Monitoring.json)
<...>
TASK [Import dependent Zabbix templates] ***************************************
changed: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/dependent/Windows Connections Monitoring.json)
ok: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/dependent/PingFederate Monitoring.json)
changed: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/dependent/ActiveMQ Monitoring.json)
ok: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/dependent/Windows OS Monitoring.json)
changed: [127.0.0.1 -> localhost] => (item=/home/valery/Documents/ans-zabbix_config/tasks/../files/zabbix_templates/dependent/Windows Network Drives Monitoring.json)
```

I was reruning the playbook several times but the result is the same.
