### ISSUE TITLE
A lookup plugin to fetch secrets from Netbox

### ISSUE THREAD

**Issue by ollybee** [ansible/ansible#48354]
##### SUMMARY
A lookup plugin to fetch secrets from Netbox

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
netbox-secrets

##### ADDITIONAL INFORMATION
This would complement the Netbox inventory plugin already available for ansible to allow fetching secrets associated with servers. This is also similar to exsiting plugins for Lastpass and HashiCorp's vault. My use case is that I store passwords for servers out-of-band management facilities in netbox and want to have Ansible use them to configure a monitoring system.

```yaml
Example usage:
    - name: query Netbox for secret
      debug: msg={{ lookup("netbox_secrets", netbox_host="https://not_netbox.hyperslice.net:443", private_key_file=".netbox-private-key.pem", token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", device="someserver", secret_name="ilo-password")}}
	  
Example response:
TASK [query  for Netbox secret] 
ok: [someserver] => {
    "msg": "hunter2"
}
```
