### ISSUE TITLE
homebrew_cask install_options force not working

### ISSUE THREAD

**Issue by NathanUrwin** [ansible/ansible#48366]
##### SUMMARY

The cask app is not force installed, or reinstalled, if already installed. Related to #47681 ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`homebrew_cask`

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/nathan.urwin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nathan.urwin/miniconda3/envs/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/nathan.urwin/miniconda3/envs/ansible/bin/ansible
  python version = 3.7.1 (default, Oct 23 2018, 14:07:42) [Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

macOS High Sierra Version 10.13.6

##### STEPS TO REPRODUCE

```yaml
---
# Copied from https://github.com/geerlingguy/ansible-role-homebrew/blob/master/tasks/main.yml
- name: Install brew cask applications.
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "force"
  with_items:
    - virtualbox
```

##### EXPECTED RESULTS

```bash
$ sudo find / -iname virtualbox
/usr/local/bin/VirtualBox
/usr/local/Caskroom/virtualbox
/Library/Application Support/VirtualBox
/Applications/VirtualBox.app/Contents/MacOS/VirtualBox
```

##### ACTUAL RESULTS

```bash
$ sudo find / -iname virtualbox
/usr/local/Caskroom/virtualbox
```
```bash
TASK [brew-cask : Install brew cask applications.]
ok: [admin@10.20.39.171] => (item=virtualbox) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_external_apps": false,
            "greedy": false,
            "install_options": [
                "force"
            ],
            "name": [
                "virtualbox"
            ],
            "path": "/usr/local/bin",
            "state": "present",
            "update_homebrew": false,
            "upgrade_all": false
        }
    },
    "item": "virtualbox",
    "msg": "Cask already installed: virtualbox"
}
```
