### ISSUE TITLE
Redfish CreateBiosConfigJob command uses non-standard Jobs URI

### ISSUE THREAD

**Issue by billdodd** [ansible/ansible#48364]
##### SUMMARY

The code in redfish_utils.py:create_bios_config_job() POSTs to a non-standard URI to create a Bios config job.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_command.py
redfish_utils.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 41dfc5162f) last updated 2018/11/07 16:35:08 (GMT -500)
  config file = None
  configured module search path = ['/Users/bdodd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bdodd/Development/git/ansible/lib/ansible
  executable location = /Users/bdodd/Development/git/ansible/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
[no output]
```

##### OS / ENVIRONMENT

Targets are Redfish hosts.

##### STEPS TO REPRODUCE

Run a playbook like the one below against a non-Dell Redfish service.

```yaml
---
- hosts: myhosts
  connection: local
  name: Set BIOS attribute - choose below
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system.

  # BIOS attributes that have been tested
  #
  # Name            Value
  # --------------------------------------------------
  # OsWatchdogTimer     Disabled / Enabled
  # ProcVirtualization      Disabled / Enabled
  # MemTest         Disabled / Enabled
  # SriovGlobalEnable       Disabled / Enabled

  vars:
  - attribute_name1: SriovGlobalEnable
  - attribute_value1: Disabled
  - attribute_name2: ProcVirtualization
  - attribute_value2: Enabled

  tasks:

  - name: Set BIOS attribute {{ attribute_name1 }} to {{ attribute_value1 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name1 }}"
      bios_attr_value: "{{ attribute_value1 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set BIOS attribute {{ attribute_name2 }} to {{ attribute_value2 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name2 }}"
      bios_attr_value: "{{ attribute_value2 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Schedule Config Job - Reboot
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
```

##### EXPECTED RESULTS

Expect the CreateBiosConfigJob command to work on Redfish services that use the spec-defined mechanisms to create jobs/tasks.

##### ACTUAL RESULTS

Will fail in various ways on non-Dell Redfish services.

```paste below

```

The specific code in  redfish_utils.py:create_bios_config_job() that I noticed is POSTing to a non-standard URI is:

https://github.com/ansible/ansible/blob/92dccb68ece08ad952fdcb93ea0419d69952da4f/lib/ansible/module_utils/redfish_utils.py#L748-L755

**Comment by ansibot** [comment]
Hi @billdodd, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/remote_management/redfish/redfish_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/redfish/redfish_command.py)
* [lib/ansible/modules/remote_management/redfish/redfish_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/redfish/redfish_config.py)
* [lib/ansible/modules/remote_management/redfish/redfish_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/redfish/redfish_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jose-delarosa @mraineri @tomasg2012
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mraineri** [comment]
The concept of using this type of job really is a different topic than the "Jobs" concept introduced in 2018.2.

The proper flow for setting BIOS attributes should be:
- Modify the Settings object for the BIOS resource accordingly
- Reboot the ComputerSystem

**Comment by billdodd** [comment]
I've made a fix and will submit the PR shortly. Here is an outline of the fix:

1. Removed the CreateBiosConfigJob Systems command from redfish_commands.py
2. Removed the create_bios_config_job() method from redfish_utils.py
3. Added PowerReboot Systems command to redfish_commands.py
4. Updated manage_system_power() method (redfish_utils.py) to add PowerReboot command logic

The added PowerReboot command is a bit different from the existing Power commands in that it looks at the current power state. If the power is On it issues a restart command (GracefulRestart or ForceRestart). If the power is not On it issues an On command.

**Comment by billdodd** [comment]
While working on this issue, I also took the opportunity to do a proof-of-concept (POC) of adding a vendor redfish module that extends the standard Redfish utility module to provide Oem function. This POC code is of course not included in the PR, but I'll describe it here as a starting point for establishing a pattern for vendor extensions.

With the current Redfish support, there are three main modules (redfish_command.py, redfish_config.py and redfish_facts.py). These three modules are relatively thin modules that establish the commands and their parameters and then call out to a fourth module, redfish_utils.py, that has the bulk of the logic to interact with the Redfish services.

The redfish_utils.py module implements a RedfishUtils class that has many methods to perform the various Redfish operations. With this architecture, a new vendor module that needs to add a specific Oem feature can create a new class (e.g. ContosoRedfishUtils) that extends the existing RedfishUtils. New method(s) can be added to that class (or existing methods overridden) while still being able to leverage all the existing standard methods in the parent class. Then a new vendor module (e.g. contoso_redfish_command.py) can be written that is basically a sparse version of redfish_command.py that only needs to handle the new or changed vendor commands.

For the POC I created a module that does what is described above and tested it successfully. The POC module provides the non-standard CreateBiosConfigJob that is being removed in this issue as an example.  Here is the code:

```
DOCUMENTATION = '''
---
module: idrac_redfish_command
version_added: "2.7"
short_description: Manages Out-Of-Band controllers using Dell Oem Redfish APIs
description:
  - Builds Redfish URIs locally and sends them to remote OOB controllers to
    perform an action.
  - For use with Dell iDRAC operations that require Redfish Oem exyensions 
options:
  category:
    required: true
    description:
      - Category to execute on OOB controller
  command:
    required: true
    description:
      - List of commands to execute on OOB controller
  baseuri:
    required: true
    description:
      - Base URI of OOB controller
  user:
    required: true
    description:
      - User for authentication with OOB controller
  password:
    required: true
    description:
      - Password for authentication with OOB controller

author: "Jose Delarosa (github: jose-delarosa)"
'''

EXAMPLES = '''
  - name: Restart system power gracefully
    idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
'''

import re
from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.redfish_utils import RedfishUtils, HEADERS
from ansible.module_utils._text import to_native

class DracRedfishUtils(RedfishUtils):

    def create_bios_config_job(self):
        result = {}
        key = "Bios"
        jobs = "Jobs"

        # Search for 'key' entry and extract URI from it
        response = self.get_request(self.root_uri + self.systems_uri)
        if response['ret'] is False:
            return response
        result['ret'] = True
        data = response['data']

        if key not in data:
            return {'ret': False, 'msg': "Key %s not found" % key}

        bios_uri = data[key]["@odata.id"]

        # Extract proper URI
        response = self.get_request(self.root_uri + bios_uri)
        if response['ret'] is False:
            return response
        result['ret'] = True
        data = response['data']
        set_bios_attr_uri = data["@Redfish.Settings"]["SettingsObject"][
            "@odata.id"]

        payload = {"TargetSettingsURI": set_bios_attr_uri}
        response = self.post_request(
            self.root_uri + self.manager_uri + "/" + jobs,
            payload, HEADERS)
        if response['ret'] is False:
            return response

        response_output = response['resp'].__dict__
        job_id = response_output["headers"]["Location"]
        job_id = re.search("JID_.+", job_id).group()
        # Currently not passing job_id back to user but patch is coming
        return {'ret': True, 'msg': "Config job %s created" % job_id}


CATEGORY_COMMANDS_ALL = {
    "Systems": ["CreateBiosConfigJob"],
    "Accounts": [],
    "Manager": []
}


def main():
    result = {}
    module = AnsibleModule(
        argument_spec=dict(
            category=dict(required=True),
            command=dict(required=True, type='list'),
            baseuri=dict(required=True),
            user=dict(required=True),
            password=dict(required=True, no_log=True)
        ),
        supports_check_mode=False
    )

    category = module.params['category']
    command_list = module.params['command']

    # admin credentials used for authentication
    creds = {'user': module.params['user'],
             'pswd': module.params['password']}

    # Build root URI
    root_uri = "https://" + module.params['baseuri']
    rf_uri = "/redfish/v1/"
    rf_utils = DracRedfishUtils(creds, root_uri)

    # Check that Category is valid
    if category not in CATEGORY_COMMANDS_ALL:
        module.fail_json(msg=to_native("Invalid Category '%s'. Valid Categories = %s" % (category, CATEGORY_COMMANDS_ALL.keys())))

    # Check that all commands are valid
    for cmd in command_list:
        # Fail if even one command given is invalid
        if cmd not in CATEGORY_COMMANDS_ALL[category]:
            module.fail_json(msg=to_native("Invalid Command '%s'. Valid Commands = %s" % (cmd, CATEGORY_COMMANDS_ALL[category])))

    # Organize by Categories / Commands

    if category == "Systems":
        # execute only if we find a System resource
        result = rf_utils._find_systems_resource(rf_uri)
        if result['ret'] is False:
            module.fail_json(msg=to_native(result['msg']))

        for command in command_list:
            if command == "CreateBiosConfigJob":
                # execute only if we find a Managers resource
                result = rf_utils._find_managers_resource(rf_uri)
                if result['ret'] is False:
                    module.fail_json(msg=to_native(result['msg']))
                result = rf_utils.create_bios_config_job()

    # Return data back or fail with proper message
    if result['ret'] is True:
        del result['ret']
        module.exit_json(changed=True, msg='Action was successful')
    else:
        module.fail_json(msg=to_native(result['msg']))


if __name__ == '__main__':
    main()
``` 

Given this new vendor module, playbooks like this can be written that call a mix of tasks using standard and vendor modules. For example, here is a playbook that sets some BIOS attributes using a standard module and then applies the attributes using a vendor module:

```
---
- hosts: myhosts
  connection: local
  name: Set BIOS attribute - choose below
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system.

  # BIOS attributes that have been tested
  #
  # Name      Value
  # --------------------------------------------------
  # OsWatchdogTimer   Disabled / Enabled
  # ProcVirtualization    Disabled / Enabled
  # MemTest     Disabled / Enabled
  # SriovGlobalEnable   Disabled / Enabled

  vars:
  - attribute_name1: SriovGlobalEnable
  - attribute_value1: Disabled
  - attribute_name2: ProcVirtualization
  - attribute_value2: Enabled

  tasks:

  - name: Set BIOS attribute {{ attribute_name1 }} to {{ attribute_value1 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name1 }}"
      bios_attr_value: "{{ attribute_value1 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set BIOS attribute {{ attribute_name2 }} to {{ attribute_value2 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name2 }}"
      bios_attr_value: "{{ attribute_value2 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Schedule Config Job - Reboot
    idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"                                    
```
 
Note that the first 2 tasks use a standard module (redfish_config) and the last task uses a vendor module (idrac_redfish_command).

And here is an example playbook to set the BIOS attributes using all standard modules:

```
---
- hosts: myhosts
  connection: local
  name: Set BIOS attribute - choose below
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system.

  # BIOS attributes that have been tested
  #
  # Name      Value
  # --------------------------------------------------
  # OsWatchdogTimer   Disabled / Enabled
  # ProcVirtualization    Disabled / Enabled
  # MemTest     Disabled / Enabled
  # SriovGlobalEnable   Disabled / Enabled

  vars:
  - attribute_name1: SriovGlobalEnable
  - attribute_value1: Disabled
  - attribute_name2: ProcVirtualization
  - attribute_value2: Enabled

  tasks:

  - name: Set BIOS attribute {{ attribute_name1 }} to {{ attribute_value1 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name1 }}"
      bios_attr_value: "{{ attribute_value1 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set BIOS attribute {{ attribute_name2 }} to {{ attribute_value2 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name2 }}"
      bios_attr_value: "{{ attribute_value2 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Reboot
    redfish_command:
      category: Systems
      command: PowerReboot
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
```

**Comment by jose-delarosa** [comment]
@billdodd, I tested your proposed code to implement OEM-specific code and it works well. Just need to update with the new parameter names, add a RETURN section, and perhaps rename the class to IdracRedfishUtils.

This is the playbook I used to test it:

```
  vars:
  - attribute_name: SriovGlobalEnable
  - attribute_value: Enabled

  tasks:

  - name: Set BIOS attribute {{ attribute_name }} to {{ attribute_value }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: "{{ attribute_name }}"
      bios_attribute_value: "{{ attribute_value }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_attribute

  - name: Create BIOS configuration job (schedule BIOS setting update)
    idrac_redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: create_bios_config_job
    when: bios_attribute.changed

  - name: Reboot system to apply new BIOS settings
    redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: create_bios_config_job.changed

```
How do you want to handle this? Do you want to submit a PR for a new module `idrac_redfish_command`? Or should each OEM be responsible for submitting their own module, in which case, I don't mind submitting this one.
