### ISSUE TITLE
Ansible terraform module variables with spaces

### ISSUE THREAD

**Issue by danielkelly22** [ansible/ansible#48374]
##### SUMMARY

The terraform module fails when there is a variable defined that has spacing in it.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

terraform 
terraform.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
```

##### CONFIGURATION

```paste below

ANSIBLE_NOCOWS(/vmware-testing/ansible.cfg) = True
DEFAULT_ASK_PASS(/vmware-testing/ansible.cfg) = False
DEFAULT_GATHERING(/vmware-testing/ansible.cfg) = smart
DEFAULT_HOST_LIST(/vmware-testing/ansible.cfg) = [u'/vmware-testing/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(//vmware-testing/ansible.cfg) = True
DEFAULT_MODULE_PATH(/vmware-testing/ansible.cfg) = [u'/vmware-testing/library']
DEFAULT_NO_TARGET_SYSLOG(/vmware-testing/ansible.cfg) = True
DEFAULT_ROLES_PATH(/vmware-testing/ansible.cfg) = [u'/vmware-testing/required-roles', u'/vmware-testing/roles']
DEFAULT_SQUASH_ACTIONS(/vmware-testing/ansible.cfg) = [u'apk', u'apt', u'dnf', u'homebrew', u'package', u'pacman', u'pkgng', u'yum', u'zypper']
DEFAULT_STDOUT_CALLBACK(/vmware-testing/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/vmware-testing/ansible.cfg) = 10
RETRY_FILES_ENABLED(/vmware-testing/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

Trying to test using the terraform module to create a vSphere VM from template.  Everything functions normally unless there happens to be a variable with spaces in it.  

```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
     project_dir : "~/vmware-testing/terraform/basic_vm_build/"
     compute_cluster: "TEST"
     vm_network: "NETWORK NAME WITH SPACES"
     annotation: "Testing Ansible Terraform Playbook"

- name: terraform plan
    terraform:
      variables:
        vm_annotation: "{{ annotation }}"
        vsphere_network: "{{ vm_network }}"
     project_path: "{{ project_dir }}"
     plan_file: "{{ project_dir }}/myplan.tfplan"
     state: planned
     register: plan_result
```

##### EXPECTED RESULTS

Expect VM to be built with variables passed to terraform defined in the variables parameter block 

##### ACTUAL RESULTS

```paste below
fatal: [127.0.0.1]: FAILED! => changed=false
  invocation:
    module_args:
      backend_config: null
      binary_path: null
      force_init: false
      lock: true
      lock_timeout: null
      plan_file: /vmware-testing/terraform/basic_vm_build//myplan.tfplan
      project_path: /vmware-testing/terraform/basic_vm_build/
      purge_workspace: false
      state: planned
      state_file: null
      targets: []
      variables:
        vm_annotation: Testing Ansible Terraform Playbook
        vsphere_network: NETWORK NAME WITH SPACES

    variables_file: null
      workspace: default
   msg: |-
    Failed to validate Terraform configuration files:
    [31m
    [1m[31mError: [0m[0m[1mRequired variable not set: vm_annotation[0m

    [0m[0m[0m
    [31m
    [1m[31mError: [0m[0m[1mRequired variable not set: vsphere_network[0m

    [0m[0m[0m
```

**Comment by ansibot** [comment]
Hi @danielkelly22, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/misc/terraform.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/terraform.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@danielkelly22 Thanks for reporting this issue. Could you please test https://github.com/ansible/ansible/compare/devel...Akasurde:i48374 and let me know if works for you ? 

Thanks

needs_info

**Comment by danielkelly22** [comment]
@Akasurde Works perfectly!  Thanks so much for the quick fix to this.

**Comment by Akasurde** [comment]
@danielkelly22 Thanks for the reply and testing the fix.

**Comment by Akasurde** [comment]
resolved_by_pr #48805

**Comment by Akasurde** [comment]
Closing this issue as PR is merged. If issue persists, please feel free to re-open.

**Comment by Leletir** [comment]
Hello, 

I still got this issue, every variables with space in it does not work.
I'm using:
 - https://raw.githubusercontent.com/ansible/ansible/devel/lib/ansible/modules/cloud/misc/terraform.py
 - ansible 2.7.7

This is my variables.tf file:
```hcl
variable "region" {
  description = "Region to create things in."
  type = "string"
}

variable "image" {
    type = "string"
    #default = "Ubuntu 18.04 Bionic Beaver"
}
```

```hcl
data "openstack_images_image_v2" "ubuntu" {
  region = "${var.region}"
  name = "${var.image}"
  most_recent = true

  properties = {
    key = "value"
  }
}
```

```yaml
- terraform:
        project_path: '../infra/'
        state: 'present'
        force_init: yes
        backend_config:
          container: '{{ swift_container }}'
          auth_url: '{{ swift_auth_url }}'
          password: '{{ swift_password }}'
          user_name: '{{ swift_user_name }}'
          domain_name: '{{ swift_domain_name }}'
          region_name: '{{ swift_region_name }}'
          tenant_name: '{{ swift_tenant_name }}'
        variables:
           cloud_name: '{{ terraform_cloud_name }}'
           region: 'region1'
           image: "Ubuntu 18.04 Bionic Beaver"
           network: '{{ terraform_network }}'
```

And I obtained:
```
Failed to validate Terraform configuration files: Error: Required variable not set: image
```
