### ISSUE TITLE
Nested roles cannot access included vars

### ISSUE THREAD

**Issue by texdc** [ansible/ansible#48387]
##### SUMMARY
Variables passed to nested roles via `include_role` are not defined.
See also:  https://github.com/ansible/ansible/issues/16320

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible Core

##### ANSIBLE VERSION

```sh
$ ansible --version
ansible 2.7.1
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:20:07) [Clang 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION
redacted (config contains proprietary info)

##### OS / ENVIRONMENT
Mac OS 10.13.6

##### STEPS TO REPRODUCE
Define vars and include them in a playbook with `vars_files`.  Include one role that then includes another role and attempt to use the included vars.

> playbooks/example/vars/main.yml
```yaml
---
my_playbook_var: foo
```
> playbooks/example/main.yml
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
  - name: role 1
    include_role:
      name: role_1
```
> roles/role_1/tasks/main.yml
```yaml
---
- name: role 2
  include_role:
    name: role_2
  vars:
     my_role_var: "{{ my_playbook_var }}"
```
> roles/role_2/tasks/main.yml
```yaml
---
- debug: var=my_role_var
```

##### EXPECTED RESULTS
```
TASK [role_2 : debug] **********************************************************************************************************
task path: /srv/git/ansible/roles/role_2/tasks/main.yml:2
Friday 09 November 2018  01:18:05 +0000 (0:00:00.095)       0:00:09.805 ******* 
ok: [127.0.0.1] => {
    "my_role_var": "foo"
}
```

##### ACTUAL RESULTS
```
TASK [role_2 : debug] **********************************************************************************************************
task path: /srv/git/ansible/roles/role_2/tasks/main.yml:2
Friday 09 November 2018  01:44:00 +0000 (0:00:00.061)       0:00:09.850 ******* 
ok: [127.0.0.1] => {
    "my_role_var": "VARIABLE IS NOT DEFINED!"
}
```

> ansible command
```sh
$ ansible-playbook -i accounts/dev playbooks/example/main.yml -vvv
```
