### ISSUE TITLE
task retry after "rescue"

### ISSUE THREAD

**Issue by ssamdwii** [ansible/ansible#48398]
##### SUMMARY
- My role entered "rescue" during task execution because of failure of the task.
I want to run the task again after "rescue".
But after "rescue", it goes to the next block.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
task(or block) retry after "rescue"

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by ansibot** [comment]
Hi @ssamdwii, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by webknjaz** [comment]
I assume this is resubmitted as #48399.

**Comment by cfiske** [comment]
Is this the same as #48399? That one seems to be about suspending other hosts' tasks during `rescue`.

If I read it correctly (and I am looking for the same thing myself), OP is requesting that if a `rescue` is triggered (and executes successfully), the block/task it was rescuing should be able to be re-executed.

Consider:
```
  - name: set myself up for failure
    file:
      path: /tmp/myfile
      state: touch
      mode: "000"

  - block:
    - name: proceed to fail
      command: cat /tmp/myfile
    rescue:
    - name: fix it up
      file:
        path: /tmp/myfile
        state: touch
        mode: "666"
```
It would be nice to have an option to retry the block after rescue so we avoid coping the block tasks into the rescue section (DRY).
