### ISSUE TITLE
Block retry

### ISSUE THREAD

**Issue by ssamdwii** [ansible/ansible#48395]
##### SUMMARY
- Let's assume that my role consists of one block and three tasks in the block.
First task is is a file download and the second task is decompression.
An error occurs when decompressing. 
If the cause is that the downloaded file is not the correct size, the download should retry.
But now, the retry is only possible on the task.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- retry for block

##### ADDITIONAL INFORMATION
```yaml
- block:
  - name: Copy zip files from repository
    win_get_url:
      url: "{{download_file}}.zip"
      dest: "{{rootdir}}"
      force: yes
    register: installfile_download_result
    until: installfile_download_result is success
    retries: 12
    delay: 10
    
  - name:  Unzip zip file
    win_unzip:
      src: "{{rootdir}}}\\{{download_file_name}}.zip"
      dest: "{{tempdir}}"
      delete_archive: yes
```
