### ISSUE TITLE
Add support for applying Kubernetes deployments from URL

### ISSUE THREAD

**Issue by zimmertr** [ansible/ansible#48402]
##### SUMMARY

Lots of documentation instructs the user to apply Kubernetes deployments from URL. For example, it is recommended [here](https://github.com/kubernetes/dashboard/wiki/Installation) to apply the Dashboard with the following command: `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

Therefore, it would be natural to assume that this procedure should be followed when applying Kubernetes deployments using the `k8s` Ansible module. However, the `k8s` module does not support this. It would be possible to first download the deployment yaml with `get_url`, however this is more of a _hack_ than a _solution_.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
k8s

##### ADDITIONAL INFORMATION

When you attempt to apply a deployment from URL like so:

```
- name: Deploying the Dashboard to Kubernetes.
  become: yes
  k8s:
    src: "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml"
```

The following error is thrown:

> TASK [Deploying the Dashboard to Kubernetes.] ************************************************************************************************
> fatal: [pluto.sol.milkyway]: FAILED! => {"changed": false, "msg": "Error accessing https:/raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml. Does the file exist?"}
>     to retry, use: --limit @/home/tj/git/Bootstrap-Kubernetes-with-Ansible/playbooks/bootstrap_kubernetes.retry

If you modify the task to use the `shell` Ansible module instead, and apply the deployment with `kubectl`, it works just fine. For example:

```
- name: Deploying the Dashboard to Kubernetes.
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
```

The following output is then produced:

> TASK [Deploying the Dashboard to Kubernetes.] ************************************************************************************************
> changed: [pluto.sol.milkyway]

**Comment by ansibot** [comment]
Hi @zimmertr, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/_kubernetes.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_kubernetes.py)
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @erjohnso @fabianvf @flaper87 @maxamillion @supertom @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
That's a good point, I hadn't considered that use. I think the `src` parameter is pretty neglected at this point, we could probably incorporate this feature in with a general revamp that adds an action plugin to read the `src` file from the ansible controller instead of the remote host. I imagine we could copy the `src`/`remote_src` semantics from the [unarchive module](https://docs.ansible.com/ansible/latest/modules/unarchive_module.html). I don't currently have the bandwidth to pick this up though.

@maxamillion do you know why this was tagged with  the _kubernetes.py component?

**Comment by zimmertr** [comment]
It also looks like the module doesn't support deploying manifests with multiple resources separated by an `---`. Which is [recommended by Kubernetes themselves](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/)

Should I make a separate issue for this?

```
TASK [Deploying the NFS Provisioner to Kubernetes.] ****************************************************************************************************************************************************************
task path: /home/tj/git/Bootstrap-Kubernetes-with-QEMU/playbooks/deploy_nfs.yml:36
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/usr/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 530, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python3.7/site-packages/ansible/playbook/task.py", line 267, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python3.7/site-packages/ansible/playbook/base.py", line 364, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 535, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 490, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python3.7/site-packages/ansible/template/__init__.py", line 738, in do_template
    res = j2_concat(rf)
  File "<template>", line 12, in root
  File "/usr/lib/python3.7/site-packages/ansible/plugins/filter/core.py", line 196, in from_yaml
    return yaml.safe_load(data)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.7/site-packages/yaml/composer.py", line 43, in get_single_node
    event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 1, column 1:
    apiVersion: v1
    ^
but found another document
  in "<unicode string>", line 6, column 1:
    ---
    ^

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
	to retry, use: --limit @/home/tj/git/Bootstrap-Kubernetes-with-QEMU/playbooks/deploy_nfs.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1 
```

**Comment by willthames** [comment]
@zimmertr is that with src? I really recommend using definition, I don't use src at all.

According to the test suite (which passes), definition handles multipart

If you want to use definition with files, just use `definition: "{{ lookup('template', 'path/to/resource.yml', convert_data=False) }}"` - I think that should work.

You can also do `definition: "{{ lookup('template', 'path/to/resource.yml') | from_yaml_all | list }}"`

There are two other benefits of the `definition` approach with lookups - templating can be used, and the files can be vaulted.

One caveat is that the template files have to be on the controller side rather than the target (this doesn't matter when the controller and target are the same)

**Comment by zimmertr** [comment]
That specific example was with `src`. But I do use `definition` as well when I'm working with jinja templates. I didn't realize `definition` could be used without passing a template file like jinja.

**Comment by gundalow** [comment]
bot_status
not deprecated

**Comment by ansibot** [comment]
### Components
[lib/ansible/modules/clustering/k8s/_kubernetes.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_kubernetes.py)
support: community
maintainers: chouseknecht erjohnso fabianvf flaper87 maxamillion supertom willthames

[lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)
support: community
maintainers: chouseknecht fabianvf flaper87 maxamillion willthames

### Metadata
**waiting_on**: maintainer
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): False

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zimmertr** [comment]
I think this is incorrectly marked as deprecated. This is in fact referencing the `k8s` module not the deprecated `kubernetes` module. 

So, not sure if I have the ability to or not, but here goes nothing:

bot_status
not deprecated

**Comment by ansibot** [comment]
### Components
[lib/ansible/modules/clustering/k8s/_kubernetes.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_kubernetes.py)
support: community
maintainers: chouseknecht erjohnso fabianvf flaper87 maxamillion supertom willthames

[lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)
support: community
maintainers: chouseknecht fabianvf flaper87 maxamillion willthames

### Metadata
**waiting_on**: maintainer
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): False

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
!component -lib/ansible/modules/clustering/k8s/_kubernetes.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
-label deprecated

**Comment by fabianvf** [comment]
@zimmertr I think this should mostly be possible now, there's still a small issue (where we don't filter out empty documents), but I use the following task for installing cert-manager in test clusters:

```yaml
- name: Install cert-manager                                                                                                                                                                                       
  k8s:                                                                                                                                                                                                             
    definition: '{{ item }}'                                                                                                                                                                                       
    namespace: cert-manager                                                                                                                                                                                        
  with_items: '{{ lookup("url", "https://github.com/jetstack/cert-manager/releases/download/v0.10.1/cert-manager.yaml", split_lines=False) | from_yaml_all | list }}'                                              
  when: item is not none
```
