### ISSUE TITLE
Featured ansible_failed_task.host info on ansible_failed_task

### ISSUE THREAD

**Issue by macklus** [ansible/ansible#48410]
##### SUMMARY
when use block/rescue for Slack alerts on failures, if task is running on múltiple nodes, you dont know where the task fail. Added a ansible_failed_task.node should solve it.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
code on block/rescue

##### ADDITIONAL INFORMATION

```yaml
- hosts: 
    tag_Function_PrivatePhp
  become: true
  vars_files:
    - /var/lib/metadata.yml
  tasks:
  - block:
    - name: resque
      command: systemctl status daemon-resque
      changed_when: false
    rescue:
      - name: Send notification message via Slack all options
        slack:
          token: here_the_toke
          msg: Fallo en la plataforma {{ env_type }}, en el servicio {{ ansible_failed_task.name }}
          parse: 'none'
```

tag_Function_PrivatePhp contains 20 nodes.
