### ISSUE TITLE
VMware: vmware_guest module ignoring env vars VMWARE_PASSWORD and VMWARE_USER

### ISSUE THREAD

**Issue by ralphie02** [ansible/ansible#48435]
##### SUMMARY
Environment variable is not being used to populate vmware_guest module parameters
VMWARE_USER
VMWARE_PASSWORD

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /home/ralphie02/.ansible.cfg
  configured module search path = [u'/home/ralphie02/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ralphie02/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1800s
ANSIBLE_SSH_CONTROL_PATH(/home/ralphie02/.ansible.cfg) = /tmp/ansible-ssh-%%h:%%p-%%r
DEFAULT_CALLBACK_WHITELIST(/home/ralphie02/.ansible.cfg) = [u'profile_tasks', u'log_plays_capture', u'actionable', u'skippy', u'task_timer', u'vers
DEFAULT_HASH_BEHAVIOUR(/home/ralphie02/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/staging']
DEFAULT_REMOTE_USER(/home/ralphie02/.ansible.cfg) = razucena
DEFAULT_ROLES_PATH(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/roles']
DEFAULT_TIMEOUT(/home/ralphie02/.ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/ralphie02/.ansible.cfg) = /home/ralphie02/ansible-vault-key
RETRY_FILES_ENABLED(/home/ralphie02/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

localhost to VMware vCenter Server v6.0.0

##### STEPS TO REPRODUCE

I run my playbook below while omitting `username` and `password` because I didn't want to hardcode the password in the playbook or send it via extra-vars or something of the like. In addition, the parameters show up as output when `-vvv` is added for verbosity.

The steps are below:

In the terminal,
```
read -s VMWARE_USER
my_username
export VMWARE_USER
```
then do the same for VMWARE_PASSWORD

Afterwards, I run the playbook below:
`ansible-playbook vmware.yml -K -vvv`

```yaml
- hosts: my_host
  gather_facts: no
  become: yes
  tasks:
  - name: Clone my machine
    vmware_guest:
      hostname: vcenter_hostname
      datacenter: my_datacenter
      # user: omitted -- value SUPPOSED to be pulled from environment variable of controlled machine
      # pass: 
      template: my_template
      esxi_hostname: my_esxi_hostname
      folder: /my/folder/path
      name: my_hostname
      disk:
      - size_gb: 100
        type: thin
        datastore: my_datastore
      hardware:
        memory_mb: 2048
        memory_reservation: 0
        num_cpus: 2
        num_cpu_cores_per_socket: 1
      networks:
      - name: network_name
        device_type: network_type
      state: poweredon
      validate_certs: no
      wait_for_ip_address: yes
    delegate_to: localhost
```

##### EXPECTED RESULTS

Cloned machine in vCenter

##### ACTUAL RESULTS

It fails with the message below:

```paste below
fatal: [my_host -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "my_datacenter",
            "datastore": null,
            "disk": [
                {
                    "datastore": "my_datastore",
                    "size_gb": 100,
                    "type": "thin"
                }
            ],
            "esxi_hostname": "my_esxi_hostname",
            "folder": "/my/folder/path",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 4096,
                "memory_reservation": 0,
                "num_cpu_cores_per_socket": 1,
                "num_cpus": 2
            },
            "hostname": "vcenter_hostname",
            "is_template": false,
            "linked_clone": false,
            "name": "my_hostname",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "network_type",
                    "name": "network_name"
                }
            ],
            "password": null,
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": "my_template",
            "username": null,
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_ip_address": true
        }
    },
    "msg": "Username parameter is missing. Please specify this parameter in task or export environment variable like 'export VMWARE_USER=ESXI_USERNAME'"
}

```
