### ISSUE TITLE
modprobe doesn't actually unload kernel modules

### ISSUE THREAD

**Issue by leonsp** [ansible/ansible#48440]
##### SUMMARY
I'm trying to unload four kernel modules. The idiomatic Ansible way is to use `modprobe`. `modprobe` says it unloads but it doesn't actually unload the kernel module

Running `command: rmmod <name>` after the fact unloads the module.

It might be related to this old issue:  https://github.com/ansible/ansible-modules-extras/issues/2140

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
modprobe

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /Users/[snip]/ansible.cfg
  configured module search path = ['/Users/[snip]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Oct  2 2018, 09:20:07) [Clang 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/Users/[snip]/ansible.cfg) = -o ControlPersist=60m -o ControlMaster=auto
DEFAULT_CALLBACK_WHITELIST(/Users/[snip]/ansible.cfg) = ['profile_tasks', 'timer']
DEFAULT_HOST_LIST(/Users[snip]/ansible.cfg) = ['/Users/[snip]/ansible/plugins/inventory/terraform-inventory']
DEFAULT_PRIVATE_KEY_FILE(/Users[snip]/ansible.cfg) = /Users/[snip]
DEFAULT_REMOTE_USER(/Users/[snip]/ansible.cfg) = root
DEFAULT_ROLES_PATH(/Users[snip]/ansible.cfg) = ['/Users/[snip]/ansible/roles']
DEFAULT_SCP_IF_SSH(/Users/[snip]/ansible.cfg) = True
DEFAULT_VAULT_PASSWORD_FILE(/Users/[snip]ansible.cfg) = /Users/[snip]
HOST_KEY_CHECKING(/Users/[snip]/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
$ uname -a
Linux labs-tools-pdp1-fnode2-5-04 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:51:21 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

$ cat /etc/*issue*
Ubuntu 16.04.5 LTS \n \l

Ubuntu 16.04.5 LTS

$ arch
ppc64le
```
##### STEPS TO REPRODUCE

This handler says it changed something succesfully but doesn't.
```yaml
- name: unload nvidia
  modprobe:
    name: "{{ item }}"
    state: absent
  with_items:
    - nvidia_drm
    - nvidia_modeset
    - nvidia_uvm
    - nvidia
```

These alternate handlers work:
```yaml
- name: really unload nvidia drm
  listen: unload nvidia
  command: rmmod nvidia_drm

- name: really unload nvidia modeset
  listen: unload nvidia
  command: rmmod nvidia_modeset

- name: really unload nvidia uvm
  listen: unload nvidia
  command: rmmod nvidia_uvm

- name: really unload nvidia
  listen: unload nvidia
  command: rmmod nvidia
```

##### EXPECTED RESULTS

I expect the specified kernel modules to be absent after the fact.

##### ACTUAL RESULTS

```paste below
 _________________________________________________
< RUNNING HANDLER [nvidia-docker : unload nvidia] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Friday 09 November 2018  16:37:11 -0500 (0:00:04.594)       0:09:09.487 *******
changed: [labs-tools-pdp1-fnode2-5-02] => (item=nvidia_drm) => {"changed": true, "item": "nvidia_drm", "name": "nvidia_drm", "params": "", "state": "absent"}
changed: [labs-tools-pdp1-fnode2-5-02] => (item=nvidia_modeset) => {"changed": true, "item": "nvidia_modeset", "name": "nvidia_modeset", "params": "", "state": "absent"}
changed: [labs-tools-pdp1-fnode2-5-02] => (item=nvidia_uvm) => {"changed": true, "item": "nvidia_uvm", "name": "nvidia_uvm", "params": "", "state": "absent"}
changed: [labs-tools-pdp1-fnode2-5-02] => (item=nvidia) => {"changed": true, "item": "nvidia", "name": "nvidia", "params": "", "state": "absent"}
```

**Comment by ansibot** [comment]
Hi @leonsp, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/modprobe.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/modprobe.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bbyhuy** [comment]
I wasn't able to repro this on a centos 7 or ubuntu 16 system, the module acted accordingly...but both systems were x86_64. I don't have a ppc to test on. Probably need to triage this a little more.

**Comment by bblenard** [comment]
I ran into this issue as well and I think the issue is how the `name` argument is passed to `modprobe.py`

I am using a variable file formatted like this:
```
unneeded_filesystems:
  - cramfs
  - freevxfs
  - jffs2
  - hfs
  - hfsplus
  - squashfs
  - udf
  - fat
```

My ansible task is this:
```
- name: Remove unneeded filesystems from kernel
  modprober:
    name: "{{ unneeded_filesystems }}"
    state: absent
```

What happens is ansible passes the name variable as a list but modprobe.py expects a string [modprobe.py:65](https://github.com/ansible/ansible/blob/fd4b282f6f14fa917a40ddf13e414519c300e81b/lib/ansible/modules/system/modprobe.py#L65). Because of this the string representation of the list is used as the name parameter. Then in the section that checks if the kernel module is loaded already [modprobe.py:85](https://github.com/ansible/ansible/blob/fd4b282f6f14fa917a40ddf13e414519c300e81b/lib/ansible/modules/system/modprobe.py#L85) the string representation of the list of kernel modules is checked against each line of the file `/proc/modules`. This results in present [modprobe.py:87](https://github.com/ansible/ansible/blob/fd4b282f6f14fa917a40ddf13e414519c300e81b/lib/ansible/modules/system/modprobe.py#L87) always being false and therefore modprobe is never called.

I can try to write a fix for this issue if you all want.
