### ISSUE TITLE
netconf_rpc/netconf_get - option to ignore rpc-errors and still provide full reply

### ISSUE THREAD

**Issue by 2-face** [ansible/ansible#48469]
##### SUMMARY
Currently if there is at least one rpc-error in the reply for a query (get) then it is not successfull at all and such rpc fails with:

Raw reply exerpt:
```
<rpc-error xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
```

Actual playbook output:
```
 "msg": "error: 0 is not a valid value.\nerror: 0 is not a valid value.\nerror: 0 is not a valid value."
````

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
```netconf_rpc``` - rpc fails totally
```netconf_get``` - fails like above but in case there is  ```<error-option>ignore-error</error-option>``` then reply is not full (looks as if there was just header of the reply in stdout)

##### ADDITIONAL INFORMATION
Both modules shall work properly with **<error-option>** provided or have variable for that. Then reply shall include 
- failed rpc section in a separate variable ```output_fail```
- not failed part in another variable ```output_success```
- full reply in yet another variable  ```output```

**Comment by ansibot** [comment]
Hi @2-face, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
bot_status

**Comment by ansibot** [comment]
### Components
[lib/ansible/modules/utilities/logic/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include.py)
support: core
maintainers: ansible

### Metadata
**waiting_on**: maintainer
[needs_info](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#label-needs_info): False

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
!component netconf_rpc

**Comment by ganeshrn** [comment]
@2-face 
>  netconf_rpc - rpc fails totally
netconf_get - fails like above but in case there is <error-option>ignore-error</error-option> then reply is not full (looks as if there was just header of the reply in stdout)

As per netconf rfc `error-option` tag is for `edit-config` rpc, i am not getting how it can be used with `get` rpc.
Also if i understand the feature description correctly the beahviour can be achived using `ignore_errors: True` with `netconf_get` task.
```
  - name: get config data
    netconf_get:
      source: running
      filter: <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"><interface-configuration></interface-configuration></interface-configurations>
    register: result
    ignore_errors: True

  - name: check for fail condition
    fail:
      msg: "get config data failed {{ result }}"
    when: "'<error string>' in result.stdout[0]"
```

needs_info
