### ISSUE TITLE
Allow override variables defined in vars_files using vars of import_playbook

### ISSUE THREAD

**Issue by yaegashi** [ansible/ansible#48470]
##### SUMMARY

Unable to override variables defined in `vars_files` using `vars` of `import_playbook`.

The variable precedence explained [here](https://docs.ansible.com/ansible/2.7/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) might be related to this behavior.  It would be nice if we had a handy way to override variables of sub components imported/included by just using `vars`.  Probably they should be given the same or next lower precedence as extra vars.

##### ISSUE TYPE
- Feature Idea
~- Bug  Report~

##### COMPONENT NAME

import_playbook

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = [u'/home/yaegashi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Ubuntu 18.04 on Azure VM

##### STEPS TO REPRODUCE

main.yml
```yaml
---
- import_playbook: sub.yml
  vars:
    x: main
    y: main
```

sub.yml:
```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    x: sub
  vars_files:
    - sub_vars.yml
  tasks:
    - name: x defined in vars
      debug:
        var: x
    - name: y defined in vars_files
      debug:
        var: y
```

sub_vars.yml:
```yaml
---
y: sub
```

##### EXPECTED RESULTS

```paste below
$ ansible-playbook -i localhost, main.yml

PLAY [localhost] ***************************************************************************************

TASK [x defined in vars] *******************************************************************************
ok: [localhost] => {
    "x": "main"
}

TASK [y defined in vars_files] *************************************************************************
ok: [localhost] => {
    "y": "main"
}

PLAY RECAP *********************************************************************************************
localhost                  : ok=2    change
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i localhost, main.yml

PLAY [localhost] ***************************************************************************************

TASK [x defined in vars] *******************************************************************************
ok: [localhost] => {
    "x": "main"
}

TASK [y defined in vars_files] *************************************************************************
ok: [localhost] => {
    "y": "sub"
}

PLAY RECAP *********************************************************************************************
localhost                  : ok=2    change
```

**Comment by ansibot** [comment]
Hi @yaegashi, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/import_playbook.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/import_playbook.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
reclassifying as this works as intended, play is more specific than the import, so it is expected to override vars defined at an upper level. Leaving as a feature idea in case someone wants to work on a new override system.

**Comment by yaegashi** [comment]
Current workaround.  Looking for an elegant way to overwrite existing variables at root using an arbitrary object hierarchy as `include_vars` does.

main.yml (put variables to override in `extra_vars`):
```yaml
---
- import_playbook: sub.yml
  vars:
    extra_vars:
      x: main
      y:
        - main
        - a: 1
          b: 2
```

sub.yml:
```yaml
---
- hosts: all
  gather_facts: no
  vars:
    x: sub
  vars_files:
    - sub_vars.yml
  tasks:
    - set_fact:
        tmp_vars_file: "{{lookup('pipe', 'mktemp')}}"
      run_once: true
    - copy:
        content: "{{extra_vars}}"
        dest: "{{tmp_vars_file}}"
      connection: local
      changed_when: false
      run_once: true
    - include_vars: "{{tmp_vars_file}}"
    - name: x defined in vars
      debug:
        var: x
    - name: y defined in vars_files
      debug:
        var: y
```

ansible-playbook output:
```
$ ansible-playbook -i localhost, main.yml 

PLAY [all] ****************************************************************************************

TASK [set_fact] ***********************************************************************************
ok: [localhost]

TASK [copy] ***************************************************************************************
ok: [localhost]

TASK [include_vars] *******************************************************************************
ok: [localhost]

TASK [x defined in vars] **************************************************************************
ok: [localhost] => {
    "x": "main"
}

TASK [y defined in vars_files] ********************************************************************
ok: [localhost] => {
    "y": [
        "main", 
        {
            "a": 1, 
            "b": 2
        }
    ]
}

PLAY RECAP ****************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```

**Comment by igoratencompass** [comment]
For me even this is not working in 2.4.4:

In `group_vars/ami_builder.yml` file I have:

`ami_name: "TOMCAT-BASE-AMI"`

Then a playbook as such:
```
- hosts: localhost
  connection: local
  vars_files:
    - group_vars/ami_builder.yml
  vars:
    ami_name: "MONGO-BASE-AMI"
  tasks:
```
and what I get is that the variable in `vars` is not overriding the same var pulled via `vars_files`. This was definitely working in previous versions.

**Comment by PulsatingQuasar** [comment]
Running 2.7.7 here and indeed I can't override vars in include files via import_playbook module.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/import_playbook.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_playbook.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by notok** [comment]
Still same here in ansible 2.9.9.
But here's an another workaround without creating temporary vars file. (also inserting `extra_vars` to the vars hierarchy..)

main.yml (put variables to override in extra_vars):

```
---
- import_playbook: sub.yml
  vars:
    extra_vars:
      x: main
      y:
        - main
        - a: 1
          b: 2
```

sub.yml

```
---
- hosts: localhost
  gather_facts: no
  vars:
    x: sub
  vars_files:
    - sub_vars.yml
  tasks:
    - set_fact:
        "{{ item.key }}": "{{ item.value }}"
      with_dict: "{{ extra_vars }}"
    - name: x defined in vars
      debug:
        var: x
    - name: y defined in vars_files
      debug:
        var: y
```
