### ISSUE TITLE
YAML folded scalars are quoted too much or get spurious newline

### ISSUE THREAD

**Issue by marco-m** [ansible/ansible#48545]
##### SUMMARY
YAML folded scalars are quoted too much or get spurious newline. This causes various errors with at least get_url, but I think with any module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url and I think majority of modules

##### ANSIBLE VERSION
```paste below
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/foo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 11 2018, 11:14:08) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
```paste below
```

##### OS / ENVIRONMENT
macOS 10.14.1
Arch Linux

##### STEPS TO REPRODUCE
```
ansible-playbook -i localhost, get-url-bug.yml
```
with the following `get-url-bug.yml` playbook:
```yaml
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    plain_url: "https://www.google.com"
    folded_url: >
      "https://www.google.com"
    folded_url2: >
      https://www.google.com

  tasks:

    - name: show different rendering
      debug:
        msg:
          - plain_url   {{plain_url}}
          - folded_url  {{folded_url}}
          - folded_url2 {{folded_url2}}
  
    - name: plain_url works
      get_url:
        url: "{{plain_url}}"
        dest: .

    - name: 'folde_url fails with: "Request failed: <urlopen error unknown url type: \"https>"'
      ignore_errors: yes
      get_url:
        url: "{{folded_url}}"
        dest: .

    - name: 'folded_url2 fails with: "Failed to connect to www.x.org\n"'
      ignore_errors: yes
      get_url:
        url: "{{folded_url2}}"
        dest: .

```

##### EXPECTED RESULTS
I expect that for all the plays, the specified URL is downloaded.

##### ACTUAL RESULTS

First play, with `plain_url: "https://www.google.com"` works, while 2nd and 3rd play, with
```yaml
    folded_url: >
      "https://www.google.com"
    folded_url2: >
      https://www.google.com
```
error out in different ways as follows:

```paste below
PLAY [localhost] ******************************************************************************************************************************************************************************************

TASK [show different rendering] ***************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "plain_url   https://www.google.com",
        "folded_url  \"https://www.google.com\"\n",
        "folded_url2 https://www.google.com\n"
    ]
}

TASK [plain_url works] ************************************************************************************************************************************************************************************
changed: [localhost]

TASK [folde_url fails with: "Request failed: <urlopen error unknown url type: \"https>"] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": ".", "gid": 20, "group": "staff",
"mode": "0755", "msg": "Request failed: <urlopen error unknown url type: \"https>",
"owner": "foo", "size": 864, "state": "directory", "uid": 501, "url": "\"https://www.google.com\"\n"}
...ignoring

TASK [folded_url2 fails with: "Failed to connect to www.x.org\n"] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false,
"msg": "Failed to connect to www.google.com\n at port 443: [Errno 8] nodename nor servname provided, or not known"}
...ignoring

PLAY RECAP ************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0

```

##### COMMENTS

* I looked at all the open and closed Ansible bugs related to YAML folded scalars and I believe this is different.
* It took me a lot to understand the root cause; at the beginning I was googling for `"Request failed: <urlopen error unknown url type: \"https>"` and finding a lot of false positives related to Python 2.6 and/or urllib3
* You may wonder why I am using folded scalars like in the example:
```
    folded_url: >
      "https://www.google.com"
```
it is because I was actually building the URL out of various variables, so my line was very long. I then choose to use the simple example above with literals because it is simpler and still shows the bug.

**Comment by ansibot** [comment]
Hi @marco-m, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/get_url.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jpmens** [comment]
As can be seen from the output of `debug` this is not particular to `get_url`.

**Comment by jpmens** [comment]
Strip out newlines for the third example by using

```yaml
folded_url2: >-
    https://www.google.com
```

(Note that's a `>` and a hyphen `-`)

**Comment by marco-m** [comment]
I spent some more time on this problem. At this point I am not sure wether it is a bug or not. It might be plain YAML corner behavior plus the Ansible requirement that interpolated variables `{{foo}}` must be quoted if they are at the beginning of a value field. I know that this quoting requirement comes also from YAML since `{` represents a YAML map.

Going back to the repro case:

```
  vars:
    # OK
    plain_url: "https://www.google.com"
    # fail in one way
    folded_url: >
      "https://www.google.com"
    # fail in another way
    folded_url2: >
      https://www.google.com
```

Case `folder_url2` adding an unexpected newline can be fixed, as @jpmens mentions above, with `>-`. Reading the YAML spec I understood that `>` would not add newline at the end, but I might be wrong.

```
    # FIXED
    folded_url2: >-
      https://www.google.com
```

And now we come to the more interesting and baffling YAML interaction with quoting and `>`:

```
    folded_url: >
      "https://www.google.com"
```

This can be fixed by... removing the quotes AND adding the `-`:

```
    folded_url: >-
      https://www.google.com
```

Why was I adding the quotes to begin with ?

Because I was used to Ansible variables needing quotes if at the beginning of the value field:

```
    quotes_are_needed: "{{foo}}"
```

So I though that quotes were still needed when using YAML folded scalars:

```
    quotes_are_actually_not_needed_and_break_if_you_use_them: >-
        {{a_very}}/{{long}}/{{string}}/{{which}}/{{explains}}/{{why}}/{{I_went_down}}/{{this_rabbit}}/{{hole}}
```
