### ISSUE TITLE
regression: assert msg no longer accepts list

### ISSUE THREAD

**Issue by Lenbok** [ansible/ansible#48547]
##### SUMMARY

We have an assert that checks some preconditions to our playbook, and it has a multi-line msg parameter. Ansible now complains that it expected msg to be a string but got a list. This worked nicely on ansible 2.6.5 but no longer works now I have updated to 2.7.1. It's not mentioned in the porting notes as a breaking change, so I assume it's a bug.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
assert

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /home/len/.ansible.cfg
  configured module search path = ['/home/len/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/len/venv/fg-secondary/lib/python3.5/site-packages/ansible
  executable location = /home/len/venv/fg-secondary/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
RETRY_FILES_ENABLED(/home/len/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Running on Ubuntu 16.04 host.

##### STEPS TO REPRODUCE
Run the playbook below e.g. `ansible-playbook test.yml -vv`

```yaml
- hosts: localhost
  name: Verify local setup
  tags: ['pre-deploy']
  tasks:
    - name: Check required environment variables are set
      assert:
        that:
          - "lookup('env','AWS_ACCESS_KEY_ID')"
          - "lookup('env','AWS_SECRET_ACCESS_KEY')"
          - "lookup('env','COUCH_DB_PASSWORD')"
        msg:
          - "You must set environment variables:"
          - "  AWS_ACCESS_KEY_ID"
          - "  AWS_SECRET_ACCESS_KEY"
          - "  COUCH_DB_PASSWORD"
```

##### EXPECTED RESULTS
Playbook should either pass or fail according to whether the environment variables are set. If it fails, the output message should get multiple lines of output message., e.g:
```
fatal: [localhost]: FAILED! => {
    "assertion": "lookup('env','AWS_ACCESS_KEY_ID')",
    "changed": false,
    "evaluated_to": false,
    "msg": [
        "You must set environment variables:",
        "  AWS_ACCESS_KEY_ID",
        "  AWS_SECRET_ACCESS_KEY",
        "  COUCH_DB_PASSWORD"
    ]
}

```

##### ACTUAL RESULTS
Complaint about the msg parameter type.

```paste below
task path: /home/len/sandboxes/yyyy/ansible/test.yml:31
fatal: [localhost]: FAILED! => {"msg": "Incorrect type for fail_msg or msg, expected string and got <class 'list'>"}

```
