### ISSUE TITLE
Task with loop is only executed if all when conditions pass

### ISSUE THREAD

**Issue by jansohn** [ansible/ansible#48561]
##### SUMMARY
I try to clean-up temporary directories at the end of the playbook if they exist. The task with the `with_items` loop is only executed if the `when` condition passes for each item.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
debug

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /tmp/webapp/buildout/ansible/ansible-playbooks/ansible.cfg
  configured module search path = [u'/var/lib/wwwrun/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/wwwrun/.local/share/virtualenvs/ansible-playbooks-i-D3ZGUp/lib/python2.7/site-packages/ansible
  executable location = /var/lib/wwwrun/.local/share/virtualenvs/ansible-playbooks-i-D3ZGUp/bin/ansible
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
```

##### STEPS TO REPRODUCE
Create playbook with contents below and run `ansible-playbook --connection=local --inventory localhost, test.yml`

```yaml
---
- hosts: localhost
  connection: local
  tasks:
    - block:
      - name: Register temp_home_dir variable
        set_fact:
          temp_home_dir: '/tmp/home'
      - name: Register temp_clone_dir variable
        set_fact:
          temp_clone_dir: '/tmp/clone'
      always:
        - name: Remove temporary directories
          debug:
            msg: 'Removing temporary directory {{ item }}!'
          when: item is defined
          with_items:
          - '{{ temp_home_dir }}'
          - '{{ temp_ssh_dir }}'
          - '{{ temp_clone_dir }}'
```

##### EXPECTED RESULTS
I'd expect item 1 and 3 to be printed and 2 to be skipped.

##### ACTUAL RESULTS
All items are skipped.

**Comment by ansibot** [comment]
Hi @jansohn, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/debug.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/debug.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Just to note, your `when` condition is not doing what you think it is, it is not checking if the variables are defined, but that `item` is, which it should be even if the vars are empty. If you have an undefined error, it will break the loop definition and never get to the task, so this is not an issue with the conditional but with the list definition.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jansohn** [comment]
I'm in a corporate environment where IRC is blocked and I'm not interested in opening a Google account TBH. I also don't think it is a user question but rather a bug or at least an unexpected behavior which should get documented somewhere.

I never get an undefined error, so I'm not sure if you actually tested my example? If all items are defined I get 3 debug outputs. If (at least) one item is undefined then I get 0 debug outputs.

If it's easy to solve then I'd appreciate it if you could post the answer here!
If it's expected behavior then please point me to where this is documented and if possible how one can achieve what I'm trying to do (execute a task only if the variables behind an item are defined).

**Comment by jansohn** [comment]
Works like this:

```yaml
---
- hosts: localhost
  connection: local
  tasks:
    - block:
      - name: Register temp_home_dir variable
        set_fact:
          temp_home_dir: '/tmp/home'
      - name: Register temp_clone_dir variable
        set_fact:
          temp_clone_dir: '/tmp/clone'
      always:
        - name: Remove temporary directories
          debug:
            msg: 'Removing temporary directory {{ item }}!'
          with_items:
          - '{{ temp_home_dir | default([]) }}'
          - '{{ temp_ssh_dir | default([]) }}'
          - '{{ temp_clone_dir | default([]) }}'
```
