### ISSUE TITLE
Cisco IOS ios_config module always changes access-list definitions

### ISSUE THREAD

**Issue by javcasalc** [ansible/ansible#48567]
##### SUMMARY
Cisco IOS ios_config module always changes access-list definitions

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
```
ansible 2.7.1
```

##### CONFIGURATION

Router "show running-config":
```
Router#sh run | section access-list
ip access-list standard ACL-NTP
 permit 81.19.96.148
 permit 130.206.3.166
 deny   any

```

Ansible playbook:
```
- name: Configure ACL-NTP
  ios_config:
    lines:
      - permit 81.19.96.148
      - permit 130.206.3.166
      - deny any
    parents:
      - ip access-list standard ACL-NTP
```

##### EXPECTED RESULTS
```

TASK [config_common : Configure - ACL-NTP] **************************************************************************************************************************************************************************************
changed: [router-1] => {"changed": false}
```

##### ACTUAL RESULTS
```

TASK [config_common : Configure - ACL-NTP] **************************************************************************************************************************************************************************************
changed: [router-1] => {"banners": {}, "changed": true, "commands": ["ip access-list standard ACL-NTP", "deny any"], "updates": ["ip access-list standard ACL-NTP", "deny any"]}


```

**Comment by ansibot** [comment]
Hi @javcasalc, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@javcasalc, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by NilashishC** [comment]
@javcasalc I tried to reproduce this issue and realised that there's an extra space in between `deny` and `any` in running config. Ansible Network `*_config` modules compare the text of the commands you specify in lines to the text in the configuration. For idempotency to persist, these two must be exactly the same. 

Hence, adding an extra space in that line in the task solved the issue, i.e., the following task ran fine:
```
- name: Configure ACL-NTP
  ios_config:
    lines:
      - permit 81.19.96.148
      - permit 130.206.3.166
      - deny   any
    parents:
      - ip access-list standard ACL-NTP
```
