### ISSUE TITLE
Katello Entity does not accept product as parameter

### ISSUE THREAD

**Issue by phatman168** [ansible/ansible#48594]
##### SUMMARY
katello module seems to have a bug and does not accept product as entity. Product does not show as a choice for entity in https://docs.ansible.com/ansible/latest/modules/katello_module.html#katello-module , however examples show product being used.

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
katello

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
```

##### CONFIGURATION

```paste below
empty/none
```

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)
katello-3.9.0-0.11.rc2.el7.noarch

##### STEPS TO REPRODUCE

```yaml
**katello-configure.yml**
- name: configure katello
  hosts: localhost
  become: true
  roles:
    - katello-configure

**roles/katello-configure/tasks/katello.yml**
- name: "{{ name }}"
  katello:
    username: admin
    password: "{{ katellopass }}"
    server_url: "https://{{ ansible_hostname }}.{{ domain }}"
    entity: "{{ entity }}"
    params: "{{ params }}"
  delegate_to: localhost

**roles/katello-configure/tasks/main.yml**
- include: katello.yml
  vars:
    name: Create Dev Environment
    entity: lifecycle_environment
    params:
      name: Dev
      prior: Library
      organization: Default Organization

- include: katello.yml
  vars:
    name: Create Centos Product
    entity: product
    params:
      name: Centos 7
      organization: Default Organization
```

##### EXPECTED RESULTS
Product to be created in Katello
##### ACTUAL RESULTS

TASK [katello-configure : Create Centos Product] *******************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "value of entity must be one of: repository, manifest, repository_set, sync_plan, content_view, lifecycle_environment, activation_key, got: product"}

```paste below
ansible-playbook katello-configure.yml
```
