### ISSUE TITLE
EC2 Module fails with a boto exception when group_id is passed a variable list

### ISSUE THREAD

**Issue by rszewczyk** [ansible/ansible#4859]
ansible version 1.3.4

I'm using the EC2 module from a task list in a role, basically like this (this works with group instead of group_id and without vpc_subnet):

from the role:

```
local_action:
  module: ec2
  keypair: mykey
  group_id: "{{ group_ids }}"
  instance_type: m1.large
  image: ami-6e649707
  wait: yes
  wait_timeout: 500
  count: 5
  instance_tags: '{"db":"postgres"}'
  monitoring=yes
  vpc_subnet_id: mysubnet_id
```

calling the role with parameters:

```
roles:
  - role: ec2_role
    group_ids: "sg-0001,sg-0002,sg-0003"
```

results in:

```
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
Invalid id: "['sg-0001', 'sg-0002', 'sg-0003']" (expecting "sg-...")
```

I would have expected to be able to use group_id the same way I can use group - that is I can use it with a parameterized role.

It does work if I don't use a variable, and put the list directly in the role like this:

```
group_id: ['sg-0001', 'sg-0002', 'sg-0003']
```
