### ISSUE TITLE
uri module fails with New-style module did not handle its own exit

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#48602]
##### SUMMARY
uri module fails with New-style module did not handle its own exit. 

Downgraded ansible to version 2.5.11 and the error went away.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

uri

##### ANSIBLE VERSION

```
2.7.1
```

##### OS / ENVIRONMENT

Centos 7.3

##### STEPS TO REPRODUCE

```
- name: Create Sendgrid Apikey
  uri: 
    url: https://api.sendgrid.com/v3/api_keys
    validate_certs: no
    method: POST
    return_content: yes
    headers:
      authorization: "Bearer {{ sendgrid_bearer }}"
    body_format: json
    body: >
      {"name": "{{customer_prefix}}-apikey","scopes": ["mail.send"]}
    status_code: 201
  register: sendgrid_output
  delegate_to: localhost
```

##### EXPECTED RESULTS

Task complete. 

##### ACTUAL RESULTS

`
TASK [sendgrid : Create Sendgrid Apikey] **************************** | 15:20:40
-- | --
  | 244 | fatal: [xxx.xxx.xxx.xxx -> localhost]: FAILED! => {"changed": false, "msg": "New-style module did not handle its own exit"}
`
