### ISSUE TITLE
AWS: Postgres10 suport in 'rds_param_group' module

### ISSUE THREAD

**Issue by brophyja** [ansible/ansible#48623]
##### SUMMARY
Amazon RDS now supports Postgres 10 ([details here](https://aws.amazon.com/about-aws/whats-new/2018/02/postgresql-10-now-supported-in-amazon-rds/)), so that option should be available when creating RDS parameter groups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
```
cloud/amazon/rds_param_group.py
```
##### ADDITIONAL INFORMATION
Ansible Version:
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/brophyja/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

This is an example playbook referencing a Postgres 10.4 Parameter Group:
```yaml
---
- name: Create AWS RDS Instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - rds_param_group:
        state: present
        name: pg10-param-group
        description: 'Postgres 10.4 Parameter Group'
        engine: 'postgres10.4'
        params:
          rds.force_ssl: 1
```

The above playbook fails with the below 'InvalidParameterValue' error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (InvalidParameterValue) when calling the CreateDBParameterGroup operation: ParameterGroupFamily postgres10.4 is not a valid parameter group family
fatal: [127.0.0.1]: FAILED! => {"changed": false, "error": {"code": "InvalidParameterValue", "message": "ParameterGroupFamily postgres10.4 is not a valid parameter group family", "type": "Sender"}, "msg": "Couldn't create parameter group: An error occurred (InvalidParameterValue) when calling the CreateDBParameterGroup operation: ParameterGroupFamily postgres10.4 is not a valid parameter group family", "response_metadata": {"http_headers": {"connection": "close", "content-length": "323", "content-type": "text/xml", "date": "Tue, 13 Nov 2018 19:50:34 GMT", "x-amzn-requestid": "f64b0107-7bb5-47e2-b8dc-e541fc4ef94f"}, "http_status_code": 400, "request_id": "f64b0107-7bb5-47e2-b8dc-e541fc4ef94f", "retry_attempts": 0}}
```

The [rds_param_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/rds_param_group.py) file does not include any 'postgres10.*' options:
```
...
  engine:
    description:
      - The type of database for this group. Required for state=present.
    choices:
        - 'aurora5.6'
        - 'mariadb10.0'
        - 'mariadb10.1'
        - 'mysql5.1'
        - 'mysql5.5'
        - 'mysql5.6'
        - 'mysql5.7'
        - 'oracle-ee-11.2'
        - 'oracle-ee-12.1'
        - 'oracle-se-11.2'
        - 'oracle-se-12.1'
        - 'oracle-se1-11.2'
        - 'oracle-se1-12.1'
        - 'postgres9.3'
        - 'postgres9.4'
        - 'postgres9.5'
        - 'postgres9.6'
        - 'sqlserver-ee-10.5'
        - 'sqlserver-ee-11.0'
        - 'sqlserver-ex-10.5'
        - 'sqlserver-ex-11.0'
        - 'sqlserver-ex-12.0'
        - 'sqlserver-se-10.5'
        - 'sqlserver-se-11.0'
        - 'sqlserver-se-12.0'
        - 'sqlserver-web-10.5'
        - 'sqlserver-web-11.0'
        - 'sqlserver-web-12.0'
```

**Comment by ansibot** [comment]
Hi @brophyja, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/rds_param_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/rds_param_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @scottanderson42 @tastychutney @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@brophyja, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@brophyja Thanks for reporting this issue. Could you please try https://github.com/ansible/ansible/pull/48703 and let me know if it works for you ? You may need to specify - 

```yaml
---
- name: Create AWS RDS Instance
  hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - rds_param_group:
        state: present
        name: pg10-param-group
        description: 'Postgres 10.4 Parameter Group'
        engine: 'postgres10'
        params:
          rds.force_ssl: 1
```
