### ISSUE TITLE
docker_compose does not allow to choose the project-directory when specifying more than one docker-compose file

### ISSUE THREAD

**Issue by giovannipizzi** [ansible/ansible#48648]
##### SUMMARY

When specifying more than one file in the `docker_service`, the `project-directory` is assumed to be the one of the first docker-compose.yml file provided, and cannot be changed (even if `project_src` is provided).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_service

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = [u'/Users/pizzi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pizzi/.virtualenvs/generic/lib/python2.7/site-packages/ansible
  executable location = /Users/pizzi/.virtualenvs/generic/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Mac OS 10.13.6, but also happens on Ubuntu Linux 16.04 and 18.04
Using `docker-compose==1.23.1` from pip

##### STEPS TO REPRODUCE

Inside a folder, create two subfolders `a` and `b`.
Inside folder `a`, put the following `docker-compose.yml` file:
```yaml
version: '2'
services: 
  a:
    image: busybox
```
Inside folder `b`, put the following `docker-compose.yml` file:
```yaml
version: '2'
services: 
  b:
    build: ./dir
```
and finally inside the `b` folder, create a `b/dir` subfolder containing a `Dockerfile` with only the following line:
```
FROM busy box
```

The playbook to run (and to put in the `b` folder) is:

```yaml
- name: test
  hosts: localhost

  tasks:
  - name: docker-compose build and up
    docker_service:
      state: present
      build: True
      project_src: "./"
      project_name: 'c'
      restarted: True
      files:
      - ../a/docker-compose.yml
      - ./docker-compose.yml
```

##### EXPECTED RESULTS

The two docker-compose files are used, and the current folder is used as project-directory as well (i.e. the Dockerfile in the subdirectory `./dir` is found and used).

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Configuration error - build path /Users/pizzi/Desktop/test/a/dir either does not exist, is not accessible, or is not a valid URL."}
	to retry, use: --limit @/Users/pizzi/Desktop/test/b/playbook.retry
```

This means that the `project-directory` is set from the path of the *first* file provided, and cannot be changed, even if `project_src` is provided.

Note that this is the behaviour of docker-compose. I.e. if I am in the `b` folder, 
the command
```
docker-compose --project-name=c -f ../a/docker-compose.yml -f ./docker-compose.yml up
```
Fails with 
```
ERROR: build path /Users/pizzi/Desktop/test/a/dir either does not exist, is not accessible, or is not a valid URL.
```
and instead swapping the order works:
```
docker-compose --project-name=c -f ./docker-compose.yml -f ../a/docker-compose.yml up
```

**However**, from the command line specifying explicitly a `--project-directory=.` makes it work correctly:
```
docker-compose --project-name=c --project-directory=. -f ../a/docker-compose.yml -f ./docker-compose.yml up
```

The problem in ansible is that it is not possible to specify a `--project-directory`.

Possible suggestions:
- add `--project-directory` to `self.options` in the code before calling `compose.cli.command.project_from_options` in the module taking the value from `project_src`, if specified (however, I don't know if the two have a different meaning and it's not a good idea to merge them)
- add a `project_directory` option to the `docker_service` module that would set this option

I would favour option 2. 

In any case (or even if this is already possible somehow) I would suggest to add an entry to the examples in the documentation of the module, explaining how to properly deal with this use case.

If you let me know how you prefer to proceed, I can also prepare a PR.
