### ISSUE TITLE
win_copy fails with Get-AnsibleParam: Missing required argument: src

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#48646]
##### SUMMARY
win_copy fails with Get-AnsibleParam: Missing required argument: src

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_copy

##### ANSIBLE VERSION

```
2.5.11
```
##### STEPS TO REPRODUCE

```
- name: Transfer certificate content as json to IIS
  win_copy:
    content: '{{ variable | to_nice_json }}'
    dest: C:\WebDav\inventory\azure\{{ variable.tags.customer }}_facts_certificate.json
  when: variable is defined
```

##### EXPECTED RESULTS

win_copy documentation states:
_When used instead of src, sets the contents of a file directly to the specified value. This is for simple values, for anything complex or with formatting please switch to the template module._

win_copy works in other ansible versions, for example 2.6.7

##### ACTUAL RESULTS

```
TASK [importFacts : Transfer certificate content as json to IIS] *********** | 06:07:20
-- | --
  | 14 | fatal: [ansibleiis]: FAILED! => {"changed": false, "checksum": "f0c2c1283a04be8a36e5f1ff368b38d7bbed1733", "dest": "C:\\WebDav\\inventory\\azure\\customer_facts_certificate.json", "msg": "Get-AnsibleParam: Missing required argument: src", "operation": "file_copy", "original_basename": "tmpsMP0Xn", "size": 4073, "src": null}
```
