### ISSUE TITLE
template results in Unsupported parameters for (copy) module

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#48645]
##### SUMMARY
template module results in error _Unsupported parameters for (copy) module_

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION

```
2.5.11
```
##### STEPS TO REPRODUCE

```
- name: Copy httpd.conf
  template:
    src: "{{ role_path }}/templates/httpd.conf"
    dest: /usr/local/ctccap/etc/httpd.conf
    owner: ctccap
    group: ctccap
```

##### EXPECTED RESULTS

Have ran this part many times in other ansible versions without issues, for example 2.6.7

##### ACTUAL RESULTS

```
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "checksum": "cc8c9f2a09e3c544f018ba7fbf8dcbbb8008e3e3", "msg": "Unsupported parameters for (copy) module: _original_basename Supported parameters include: attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, original_basename, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate"}
```
