### ISSUE TITLE
Role Variable Specification

### ISSUE THREAD

**Issue by ant31** [ansible/ansible#48653]
##### SUMMARY
The current default/main.yaml is a great quick way to expose configuration to end-users.
But as an orchestration tool is reaching a certain size, it becomes harder to validate all user inputs, to document all options.

- The proposal is to allow OpenAPI specification as variables definitions

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

All variables, mainly to be used in role/defaults, roles/vars 
Since there is a field, 'default' in the spec, it can be equivalent to the current format once parsed.

Self-documentation is an important side-effect of using such convention. Ansible Galaxy could expose the variables. Ansible-playbook cloud have an option to validate user inputs. 
In general roles quality and user experience would be better

##### ADDITIONAL INFORMATION
example `default/main.spec.yaml` or maybe in `meta/main.yaml`
```yaml

container_engine: 
 description: Configure the container-engine used by the kubernetes control-plane(kubelet) to manage containers
 type: string
 default: docker
 oneOf: 
   - docker
   - crio

access_ip:
  description: |
     Public or Private IP accessible from outside the cluster network. 
     To be used to publicly expose the control plane in cloud environement for example
  required: false
  type: string
  format: ip
  default: null
```
