### ISSUE TITLE
loop_control label displays string representation of data in default callback

### ISSUE THREAD

**Issue by TermoK** [ansible/ansible#48663]
##### SUMMARY
The output of stdout_lines is shown in one line but not with new lines.

##### ISSUE TYPE
- ~Bug Report~
- Feature Idea

##### COMPONENT NAME
loopcontrol label

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/napalm-ansible/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/napalm-ansible/library']
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry
```

##### OS / ENVIRONMENT
Debian 9

##### STEPS TO REPRODUCE
Depending of a list of interfaces the configuration of these interface is shown with a loop:
```
---
interfaces:
  - int: Ethernet150/1/20
  - int: Ethernet150/1/21
```

Main playbook:
```
-----
- hosts: "{{ group }}"
  connection: local
  vars:
    int: "{{ int }}"

  tasks:
  - name: "Include Show Interface Tasks"
    include_tasks: "switchport_nxos_show_config_list.yml"
    vars:
      int: "{{ int }}"
    when: ansible_network_os == "nxos"

  - name: "Include Show Interface Tasks"
    include_tasks: "switchport_ios_show_config_list.yml"
    vars:
      int: "{{ int }}"
    when: ansible_network_os == "ios"
```

Included playbook:
```
---
- name: "Include Interface List"
  include_vars:
    file: ../group_vars/{{ int }}
    name: interfaces

- name: "Show Interface Running Config"
  nxos_command:
    commands:
      - show running-config interface {{ item.int }}
  register: loopresult
  loop: "{{ lookup('list' , interfaces.interfaces) }}"
  loop_control:
    label: "{{ loopresult.stdout_lines }}"

- meta: end_play
```

##### EXPECTED RESULTS
```
ok: [switchname] => (item=[
								[
								'!Command: show running-config interface Ethernet150/1/20', 
								'!Time: Wed Nov 14 14:48:19 2018', 
								'', 
								'version 5.2(1)N1(9b)', 
								'', 
								'interface Ethernet150/1/20', 
								'  description TDS-Pocov01lh01-mgmt1', 
								'  no cdp enable', 
								'  switchport mode trunk', 
								'  switchport trunk native vlan 10', 
								'  switchport trunk allowed vlan 199,337', 
								'  spanning-tree port type edge trunk', 
								'  channel-group 3000 mode active'
								]
							]
					)
ok: [switchname] => (item=[
								[
								'!Command: show running-config interface Ethernet150/1/21', 
								'!Time: Wed Nov 14 14:48:22 2018', 
								'', u'version 5.2(1)N1(9b)', 
								'', 
								'interface Ethernet150/1/21', 
								'  description TDS-Pocov01lh01-u2', 
								'  no cdp enable', 
								'  switchport mode trunk', 
								'  switchport trunk native vlan 10', 
								'  switchport trunk allowed vlan 127,216', 
								'  spanning-tree port type edge trunk', 
								'  channel-group 3001 mode active'
								]
						]
					)
```

##### ACTUAL RESULTS
No line wrapping happens:
```
ok: [switchname] => (item=[[u'!Command: show running-config interface Ethernet150/1/20', u'!Time: Wed Nov 14 14:48:19 2018', u'', u'version 5.2(1)N1(9b)', u'', u'interface Ethernet150/1/20', u'  description TDS-Pocov01lh01-mgmt1', u'  no cdp enable', u'  switchport mode trunk', u'  switchport trunk native vlan 10', u'  switchport trunk allowed vlan 199,337', u'  spanning-tree port type edge trunk', u'  channel-group 3000 mode active']])
ok: [switchname] => (item=[[u'!Command: show running-config interface Ethernet150/1/21', u'!Time: Wed Nov 14 14:48:22 2018', u'', u'version 5.2(1)N1(9b)', u'', u'interface Ethernet150/1/21', u'  description TDS-Pocov01lh01-u2', u'  no cdp enable', u'  switchport mode trunk', u'  switchport trunk native vlan 10', u'  switchport trunk allowed vlan 127,216', u'  spanning-tree port type edge trunk', u'  channel-group 3001 mode active']])
```
