### ISSUE TITLE
net_put does not allow for setting a per command timeout

### ISSUE THREAD

**Issue by reedium** [ansible/ansible#48667]
##### SUMMARY

Currently, the only method for setting the timeout of net_put is to utilize the command_timeout which is a global change. This is a bit of a weird requirement for a module that's built for file transfer. Is ansible/net_put unable to tell if the transfer is still going?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
net_put

##### ADDITIONAL INFORMATION
I am attempting to transfer an image from a linux device to a Cisco ASA. The transfer times out if the command_timeout isn't set globally. But this would affect all other commands being run.

I would expect this to follow closer to other modules where a "timeout" option can be defined for the specific module in question.

```yaml
    - name: Copy image to device
      connection: network_cli
      net_put:                                          
        src: "{{ image_path }}"
        dest: "{{ dst_path }}"                          
        protocol: scp
```

**Comment by ansibot** [comment]
Hi @rreed42, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/files/net_put.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/files/net_put.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/plugins/connection/network_cli.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/network_cli.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @ganeshrn @gdpak @justjais @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@rreed42, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gdpak** [comment]
@rreed42 
timeout value for net_put task can be set as per task var 'ansible_command_timeout'. I tried below and it works as expected
```
- hosts: ios01
  tasks:
    - name: copy 1 MB file with task timeout set
      net_put:
        src: 1mb_random_char_bin
      vars:
        ansible_command_timeout: 200

    - name: copy 1 MB file without task timeout set
      net_put:
        src: 1mb_random_char_bin2
```
Here 1st task would be completed as per increased command_timeout while second task would face default timeout issue.
```
TASK [copy 1 MB file with task timeout set] ***********************************************************************************
task path: /macos/net_role/dev/playbooks/ios_test/net_put.yaml:7
changed: [ios01] => {
    "changed": true, 
    "destination": "1mb_random_char_bin"
}

TASK [copy 1 MB file without task timeout set] ********************************************************************************
task path: /macos/net_role/dev/playbooks/ios_test/net_put.yaml:13
fatal: [ios01]: FAILED! => {
    "changed": true, 
    "destination": "1mb_random_char_bin2", 
    "msg": "Exception received : command timeout triggered, timeout value is 10 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
        to retry, use: --limit @/macos/net_role/dev/playbooks/ios_test/net_put.retry

PLAY RECAP ********************************************************************************************************************
ios01                      : ok=2    changed=1    unreachable=0    failed=1    skipped=0   

```
