### ISSUE TITLE
New parameter for `include_role` to pass role variables

### ISSUE THREAD

**Issue by juanvalino** [ansible/ansible#48709]
##### SUMMARY
Add a new parameter to `include_role` module to pass a dict with the variables to use within the role.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`include_role` module.

##### ADDITIONAL INFORMATION
Currently there is no way to dynamically pass variables to an included role. Passing a dictionary to `vars` keyword is not an option due to issue #19084.

WIthout this feature we don't have any way to implement meta-programming and the roles reuse is very limited. For example is not possible to implement a wrapper role that internally call other roles without explicitly hard-coding all the possible role variables with their defaults in the `vars` keyword.

```yaml
- hosts: localhost
  tasks:
    - include_role:
        name: myrole
        role_vars: {{ my_dynamic_vars }}
     vars:
       my_dynamic_vars:
         var1: "value1"
         var2: "value2"
         varN: "valueN"
```

**Comment by ansibot** [comment]
Hi @juanvalino, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/galaxy/data/apb/tasks/main.yml.j2](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/tasks/main.yml.j2)
* [lib/ansible/modules/utilities/logic/include_role.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_role.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/plugins/lookup/vars.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/vars.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
!component =lib/ansible/modules/utilities/logic/include_role.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include_role.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
+label needs_triage

**Comment by sivel** [comment]
-label needs_triage

**Comment by sivel** [comment]
Thank you very much for your submission.  We have discussed this and have decided against adding such a feature.

Instead you should create a top level variable via `vars` and assign the dynamic value to that top level var and reference it such as `my_dynamic_vars.var1` within the role.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by dnorthup-ums** [comment]
@sivel Could you please enlighten us further? Your answer reads very much like "I have no idea why you would want to do that, therefore you must want to do this other thing that you explicitly said you don't want to do." Such an answer doesn't help the community understand why the decision was made. It sure doesn't help me understand if the problem I'm seeing is related or not.

**Comment by juanvalino** [comment]
@sivel I respect the decision that has been made, but I do not share it.

I think that an **automation** system should not resolve in a tricky and not automated way things that can be solved internally and transparently to the final user.

I'll try to explain the necessity of this feature in more detail, and the consequences of the implementation you proposed.  

In my case this problem come up with the implementation of a role I've made that deploys a tomcat instance.  This role is available in [ansible galaxy](https://galaxy.ansible.com/amtega/tomcat) if you want the details.

This role receives a lot of variables and many of them are complex values, for example list of dicts. 

If I want to deploy multiple tomcat instances in the same server I need to call the role several times with different variables, and it is desirable that the different variable values for each instance be stored on the inventory and not hardcoded in the play. To get this I have to use `include_role` in a structure like this:

```
- name: deploy tomcat instances
  tasks:
    - include_role:
        name: amtega.tomcat      
      loop: "{{ tomcat_instances_settings }}
      vars: 
        tomcat_dynamic_vars: "{{ item }}"
```

With your proposed solution my `defaults/main.yml` needs to look something like this:
```
tomcat_version: "{{ tomcat_dynamic_vars.tomcat_version | default('8.0.0') }}"
tomcat_home: "{{ tomcat_dynamic_vars.tomcat_home | default('/opt/tomcat') }}"
tomcat_cms_users: "{{ tomcat_dynamic_vars.tomcat_cms_users | default(tomcat_default_cms_users) }}"

tomcat_default_cms_users:
  - username: admin
    password: admin
    roles:
      - admin-gui
      - manager-gui
      - manager-script
      - manager-jmx
      - manager-status
```

Look the extra level of variable nesting required to define the variable `tomcat_cms_users`. This is very tricky and does not encourage readability of the role and specifically of the defaults variable file.

The solution I proposed is more elegant and straight on because you will end with an structure like this:
```
- name: deploy tomcat instances
  tasks:
    - include_role:
        name: amtega.tomcat    
        role_vars: "{{ item }}"
      loop: "{{ tomcat_instances_settings }}
```

Also the `defaults/main.yml` is much more simpler and readable:
```
tomcat_version: 8.0.0
tomcat_home: /opt/tomcat
...
tomcat_cms_users: 
  - username: admin
    password: admin
    roles:
      - admin-gui
      - manager-gui
      - manager-script
      - manager-jmx
      - manager-status
...
```

Please, reconsider the decision. I think If we want to push ansible to the next level we need meta-programming tools like this. If not, out capacity to reuse roles is very limited.

**Comment by ahuffman** [comment]
Maybe I misunderstand the problem here, but the way that I typically do this, and it works well is to design your variables into lists of dictionaries like so:
```yaml
---
tomcat_instances_settings:
  - name: "Some tomcat deployment"
    tomcat_version: "8.0.0"
    tomcat_users:
      - username: "admin"
        password: "admin"
        roles:
          - "admin-gui"
          - "manager-gui"
          - "manager-script"
          - "manager-jmx"
          - "manager-status"
  - name: "another tomcat deployment"
    ...
```
When you have a structure like that you are then able to do something like this:
```yaml
- name: "deploy tomcat instances"
  tasks:
    - include_role:
        name: "amtega.tomcat"      
      loop: "{{ tomcat_instances_settings }}"
      vars: 
        tomcat_version: "{{ tomcat.tomcat_version }}"
        tomcat_users: "{{ tomcat.tomcat_users }}"
        tomcat_home: "{{ tomcat.tomcat_home }}"
      loop_control:
        loop_var: "tomcat"
        label: "{{ tomcat.name }}"
```
So you're able to iterate on the variable structure, while injecting the variables into your role.  Hopefully that helps you.

**Comment by juanvalino** [comment]
The structure you proposed is not enough if you need more abstract metaprogramming. It requires you to hard-code all role variables in the `vars` section and in some cases the variable list to use by the role may be generated dynamically because is different in any host to manage.

For example, using the same example, one host you may need to pass only the `tomcat_version` and let the role use the other variable defaults and in other host you may need `tomcat_version`, `tomcat_users` and `tomcat_home`. Your solution needs to list all the role variables in `vars` and as collateral effect you cannot use the implicit role defaults values any more (`defaults/main.yml`) because you are overriding them in the `vars`section, forcing the user to list also all the role variables in the inventory for each host inside the `tomcat_instances_settings` dict.

The solution I proposed above is more elegant and a real tool for powerful metaprogramming:

```
- name: deploy tomcat instances
  tasks:
    - include_role:
        name: amtega.tomcat    
        role_vars: "{{ item }}"
      loop: "{{ tomcat_instances_settings }}
```

With this solution the number of variables contained in the `tomcat_instances_settings` may be different for each host and the ones that you don't put in this dict will be taken by the role from its defaults. 

@ahuffman, do you see the difference between your solution and the feature I proposing here?. Have I explained the problem better now?

**Comment by lc-nyovchev** [comment]
I still agree with @juanvalino. Often you have the scenario as follows. Let's say I have a base role and many roles which inherit it by using include_role:

in the base role I have a variable in `roles/base/vars/main.yaml`:

`someVariable: "defaultBaseValue"`

in the inheriting role I have a variable in `roles/child/vars/main.yaml`:

`someVariable: "overriding"`

Then in my inheriting role my task is as follows `roles/child/tasks/main.yaml`:

```
## read the variables from the main.yaml of the Child role
- include_vars:
    file: main.yaml
    name: overriding_vars

## attempt to pass those variables to the Base role
- name: Include the base role
  include_role:
    name: base 
  vars:  "{{ overriding_vars }} " #this syntax doesn't work
```

What I want to do is get my child role's variables to **override those** of the base role. All of them! I don't want to assign them to a **new sub-level of dictionary**, I don't want to have all this complexity. I just want to have variable inheritance where my child's role variables override the variables of the base role.

If we can pass variables like this to the include_role directive:

```
- name: Include the base role
  include_role:
    name: base 
  vars:  
    - var1: "bla"
    - var2: "bla"
```

I think it's a completely reasonable request to want to be able to pass a whole dict to the Include_role.

**Comment by walterdolce** [comment]
I have just hit this problem today. 

I fail to understand why this has been rejected but I think there would not even be any need for adding the `role_vars` field, had the following worked:
```
    - name: Provision persistent disks
      include_role:
        name: gcp-persistent-disk
      vars: "{{ item }}"
      loop: "{{ gcp_persistent_disks | default([]) }}"
```

But you can't use `vars: "{{ item }}"` that way apparently.

**However**, for my specific use case, I was able to work around this limitation by simply tweaking the role variables and do the following:
```
    - name: Provision persistent disks
      include_role:
        name: gcp-persistent-disk
      vars:
        disk: "{{ item }}"
      loop: "{{ gcp_persistent_disks | default([]) }}"
```

Then, inside the role, the variables would be referenced as `disk.name` instead of `disk_name` - which I could have passed verbatim if `vars: "{{ item }}"` had worked..

Hope it helps.
