### ISSUE TITLE
Error starting service using win_nssm with user and password parameters and password contains special characters

### ISSUE THREAD

**Issue by shrabok-surge** [ansible/ansible#48728]
##### SUMMARY
When running `win_nssm` module with parameters `user` and `password` and the password contains special characters (we have a number of special characters such as `#` `$` `%`) the service will fail to start with `The service did not start due to a logon failure`.

The issue did not occur in ansible version 2.6, only seen in 2.7.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_nssm

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = REDACTED
  configured module search path = REDACTED
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING = True
ANSIBLE_SSH_ARGS = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
DEFAULT_CALLBACK_WHITELIST = [u'profile_tasks']
DEFAULT_LOAD_CALLBACK_PLUGINS = True
DEFAULT_REMOTE_USER = ansible
DEFAULT_STDOUT_CALLBACK = debug
RETRY_FILES_ENABLED = False
```

##### OS / ENVIRONMENT
Target: Windows Server 2012R2

##### STEPS TO REPRODUCE
Create a win_nssm service with `user` and `password` parameters and have a password with uses special characters including `#` `$` `%`.

```yaml
- name: Test NSSM Service with User and Password
  win_nssm:
    name: 'Test Service'
    state: started
    start_mode: manual
    application: 'C:\my_cmd'
    user: 'mytestuser@my.domain'
    password: 'MyPass12345%$#@!'
```

##### EXPECTED RESULTS
Task should pass with:
changed: [myhost.my.domain]

##### ACTUAL RESULTS

Command fails with Error starting service. If you check Event Viewer it states `The service did not start due to a logon failure.`

```
fatal: [myhost.my.domain]: FAILED! => {
    "changed": true,
    "changed_by": "start_mode",
    "nssm_app_parameters": null,
    "nssm_error_cmd": "start \"Test Service\"",
    "nssm_error_log": "Test Service: START: The service did not start due to a logon failure.\r\r\n",
}

MSG:

Error starting service "Test Service"

```
