### ISSUE TITLE
I cannot invoke different yml tasks files within a role

### ISSUE THREAD

**Issue by narcisbcn** [ansible/ansible#4876]
# Overview

When I try to divide yml tasks within a role I cannot invoke files different than main.yml
# Context
# ls /etc/ansible/roles/mysql/tasks/

   main.yml  master.yml
# setup.yml

``` ....
- hosts: databases
  roles:
   - { role: mysql/tasks/master.yml, mysql_root_password: XXXXX, tags: mysql }   
   - { role: mysql/tasks/main.yml,  tags: mysql }
....
```
# Error

```
[Sisu@ ansible]$ ansible-playbook -i cluster5 setup.yml -s --tags mysql
sudo password:
ERROR: cannot find role in /etc/ansible/roles/mysql/tasks/master.yml or /etc/ansible/mysql/tasks/master.yml
```

// Checking whether the file exists

```
[Sisu@ ansible]$ ll /etc/ansible/roles/mysql/tasks/master.yml
-rw-r--r-- 1 ansible ansible 181 Nov  1 19:02 /etc/ansible/roles/mysql/tasks/master.yml
```

If I do not specify the file, main.yml is invoked correctly:

```
...
roles:
   - { role: mysql, mysql_root_password: XXXX, tags: mysql }
...
```
# Ansible version

```
#ansible --version
ansible 1.3.3
```

**Comment by mpdehaan** [comment]
This isn't how this works.

Your role always loads main.yml, you never specify a .yml file when pathing a role.

Instead, within the role, your main.yml can do this:

```
----
- include: foo.yml
  when: something == 12
- include: other.yml
```

Stop by the list if you have further questions.

cc @jctanner

**Comment by mkchoithani** [comment]
```yaml
---
- name: experiment
  hosts: box
  tasks:
  - debug:
      msg: "before we run our role"

  - name: Run a task from a role
    include_role:
       name: rolename
       tasks_from: taskname
     when: ansible_os_family == "Debian"

  - name: Run a task from a role1
    include_role:
       name: rhidm_manage_users
       tasks_from: task1
    when: ssr  = 'man_create_tenant1'
```

**Comment by mkchoithani** [comment]
This is another way where you can call a specified task from a role inside a playbook

**Comment by varh1i** [comment]
@mkchoithani unfortunately it executes main.yml too when I specify only tasks_from: "taskname"

**Comment by utoddl** [comment]
It's unfortunate that main.yml is "special" in a role.
```
- hosts: foo
  roles:
      - my_role
```
should be equivalent to
```
- hosts: foo
  roles:
    - role: my_role
      tasks_from: main.yml
```
If that were the case, you could just as easily say
```
- hosts: foo
  roles:
    - role: my_role
      tasks_from: other.yml
```
and still have your tags observed.

Instead we have endless confusion about include_role vs. import_role and why tags don't work in those circumstances. It all very frustrating.
