### ISSUE TITLE
Add "creates" parameter to archive module

### ISSUE THREAD

**Issue by justwheel** [ansible/ansible#48780]
##### SUMMARY

Add `creates` parameter to check if archive already exists before creating an archive

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`archive` module

##### ADDITIONAL INFORMATION

Not sure if it makes sense to specify a path or use a boolean. `dest` is already used when writing an archive out, but it doesn't distinguish if the archive already exists. Instead, a boolean value could be used to indicate whether this task only _creates_ a new archive. So in some use cases, if an archive file already exists at `dest`, don't run this task.

I'm running a backup playbook that could be interrupted mid-process. If it's interrupted, I'd like for it to pick up where it left off instead of re-archiving the same files again. 

```yaml
- name: archive existing site content
  archive:
    path: "{{ site_dir }}"
    dest: "/tmp/{{ site_fqdn }}-www-content.tar.xz"
    format: xz
    creates: yes
```
