### ISSUE TITLE
Service "Could not find the requested service" when trying to restart httpd; but it is installed

### ISSUE THREAD

**Issue by shederman** [ansible/ansible#48786]
##### SUMMARY
Get "Could not find the requested service" when trying to restart httpd; but it is installed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = None
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, May  2 2018, 18:31:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
[ec2-user@ip-XX-XX-XX-XX ~]$  cat /etc/*release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2018.03
```

##### STEPS TO REPRODUCE

Run simple playbook that attempts to restart httpd
Ansible thinks that there is no `httpd` service at all on the target machine and does not restart or start the service, although the service is there, but not running, as this shell command demonstrates:
```
sudo service httpd restart
Stopping httpd:                                            [FAILED]
Starting httpd:                                            [  OK  ]
```

There is a similar issue, #36585 in this but it relates to `systemd`, not `service`. I don't believe `systemd` is installed on this version of Amazon Linux.

```yaml
- name: Restart Apache 
  service:
    name: "{{ services }}"
    state: started
    enabled: yes
  become: true
  vars:
    services:
    - httpd
```

##### EXPECTED RESULTS

httpd restarted

Ansible should restart the service and not tell me that there is no service at all, which is 100% false.

##### ACTUAL RESULTS

Ansible fails stating that httpd could not be found.

```paste below
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service ['httpd']: host"}
```

**Comment by ansibot** [comment]
Hi @shederman, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rhrn** [comment]
try `with_items`, it works for me
```
    - name: Ensure nfs service is running
      service:
        name: "{{item}}"
        state: started
        enabled: yes
      with_items:
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap
      when: inventory_hostname == "storage"
```

**Comment by RickS-C137** [comment]
Even when using `with_items` I'm running into this problem. It doesn't matter if its on Amazon Linux 1 (SystemV Init) oder Amazon Linux 2 (SystemD). The workarounds I've found so far aren't working. 
When will it be fixed?

**Comment by vivsri** [comment]
---
- name: enable multiple services
  become: true
  hosts: test
  vars:
    services:
     "httpd"
  tasks:
  - name: enable multiple services "{{ services }}"
    service:
         name: "{{ services }}"
         state: started
         enabled: true


this works, just try from your end
 ansible-playbook services.yml
BECOME password:

PLAY [enable multiple services] *****************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [192.168.227.128]

TASK [enable multiple services "httpd"] *********************************************************************************************************************
ok: [192.168.227.128]

PLAY RECAP **************************************************************************************************************************************************
192.168.227.128            : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by vthach** [comment]
I am having this issue on SUSE 11 SP 4 with tomcatd, but only on some servers.  My workaround to use the shell to call the service command, but it is something I am hoping to avoid.  Does anyone have a better solution or a fix for this yet?

**Comment by sprive** [comment]
I don't think this is an Ansible issue, but it is an issue which affects Ansible users.  The problem actually seems to be in some service and systemd scripts where those scripts return, before the service is fully running and ready to respond to further actions.

I can reliably reproduce this with Ansible 2.8.5, Vagrant (ubuntu/xenial64), and the following play:
```
---
- hosts: all
  tasks:
    - name: ensure ntpd is at the latest version
      yum: pkg=ntp state=latest update_cache=yes
      become: yes
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
      become: yes
```

*Steps:*
1. run `vagrant up --provision`, note error is `fatal: [default]: FAILED! => {"changed": false, "msg": "Could not find the requested service ntpd: host"}`
1. Run it again, note there is no error now.

*Workarounds:*
1. You can switch to`shell:` commands to start services (and possibly add `&& sleep 2` as needed) but this is clumsy.
1. There doesn't seem to be a way to tack a delay before the `service` module's state check. That's what I am looking for.
1. George Shuklin documents using state files to get around this: https://medium.com/@george.shuklin/handling-handlers-for-ansible-88b0c91515a4
^^ While George's solution has more boilerplate than a `shell` command, it's more ansible-like (not relying on shell or command)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by shederman** [comment]
To me the point of ansible is to help smooth over these inconsistencies. If a service command isn't working on a particular distro, rather than clutter every single ansible users code with extra complexity, surely the correct approach is to handle this logic within the ansible service implementation?

**Comment by GrigLars** [comment]
I have found the same issues with Armbian, Focal Fossa 20.04, in starting/stopping/restarting services either with systemd module or service module. The daemon_reload did nothing.  I ended up having to do a rescue block as a workaround:

```
    - name: Stop the k3s-agent service except on k3s-master-01
      block:
        - name: Attempt to shut down k3s-agent normally
          systemd: 
            name: k3s-agent
            state: stopped
            daemon_reload: yes
      rescue:
        - name: Force shutdown of stubborn k3s-agent
          shell: systemctl stop k3s-agent.service
      when: inventory_hostname != 'k3s-master-01'
```
This led to:

```
TASK [Attempt to shut down k3s-agent normally] ****************************************************************************************************************************************
skipping: [k3s-master-01]
changed: [k3s-master-02]
changed: [rpi-screen]
changed: [rpi3bp-kube1]
changed: [rpi3bp-kube2]
changed: [rpi-zw1]
changed: [rpi-zw2]
changed: [rpi3bp-kube3]
changed: [rpi4b4]
changed: [rpi4b42]
changed: [rpi4b]
changed: [rpi3bp-kube4]
changed: [rpi4b8]
changed: [rpi-z]
changed: [rpi-y]
changed: [jet-nano]
fatal: [orangepi1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Could not find the requested service k3s-agent: host"}
changed: [cray-super-spare-02]
changed: [potato1]
changed: [bananapim2zero]
changed: [rpibp]

TASK [Force shutdown of stubborn k3s-agent] *******************************************************************************************************************************************
changed: [orangepi1]
```

I hope this helps somebody else.

**Comment by stephan2012** [comment]
Just stumbled over this issue. While seeing this only on some systems, I discovered that the `LoadState` and other properties are not present in `systemctl show ‹unit›` on failing systems. `systemd` is the same version on all systems, the warning `Failed to parse bus message: Invalid argument` pointed me to the right direction: There might be issues between `dbus` and `systemd`. So, the solution is to upgrade the `systemd` package and everything works again.

Maybe I have encountered this issue because I have installed some packages from the `buster-backports` Debian repo which might have upgraded some dependencies to a not fully compatible version. The `systemd` version that I have upgraded to also comes from the `buster-backports` repo.

**Comment by cezmunsta** [comment]
> Just stumbled over this issue. While seeing this only on some systems, I discovered that the `LoadState` and other properties are not present in `systemctl show ‹unit›` on failing systems. `systemd` is the same version on all systems, the warning `Failed to parse bus message: Invalid argument` pointed me to the right direction: There might be issues between `dbus` and `systemd`. So, the solution is to upgrade the `systemd` package and everything works again.

This issue has presented itself on CentOS Stream 8 and indeed disappears once the relevant packages have been updated.

**Comment by DonBower** [comment]
I was getting this error when I coded the test like this:
```
   - name: Ensure docker is started
      become: yes
      ansible.builtin.systemd:
        name: docker
        state: started
```
But it works like this:
```
   - name: Ensure docker is started
      become: yes
      ansible.builtin.systemd:
        service: docker
        state: started
```
subtle difference between `name: docker` and `service: docker`, and probably a bug, if not a documentation issue.

Per Documentation:
[](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#parameter-name)name
 
string
Name of the unit. This parameter takes the name of exactly one unit to work with.
When no extension is given, it is implied to a .service as systemd.
When using in a chroot environment you always need to specify the name of the unit with the extension. For example, crond.service.

aliases: service, unit
