### ISSUE TITLE
homebrew_cask: "You must select a cask to install"

### ISSUE THREAD

**Issue by taraspos** [ansible/ansible#48796]
##### SUMMARY
`homebrew_cask`  has `name` property required, so I can't simply run `update_homebrew` operation without installing anything

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

homebrew_cask

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  python version = 3.7.1 (default, Nov  6 2018, 18:46:03) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE
```yaml
  - name: Update brew cask
    homebrew_cask:
      update_homebrew: yes
```

##### EXPECTED RESULTS
Executed `homebrew cask update` command

##### ACTUAL RESULTS
`FAILED! => {"changed": false, "msg": "You must select a cask to install."}`

**Comment by ansibot** [comment]
Hi @Trane9991, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/homebrew_cask.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/homebrew_cask.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MaxWinterstein** [comment]
But why? I can't imagine a good reason to do this 😉 

What are you trying to archive? I would guess there is a better way. Homebrew invalidates its update cache every 60s normally, so i guess this is intended.

**Comment by taraspos** [comment]
@MaxWinterstein sorry, bad example. The new one, for example.
Upgrade all casks on host, should be done by:
```
  - name: Upgrade brew casks
    homebrew_cask:
      upgrade_all: yes
```
but it will not work, while
```
  - name: Upgrade brew packages
    homebrew:
      upgrade_all: yes
```
works fine

**Comment by MaxWinterstein** [comment]
you try to up**grade**, not up**date**, now i understand. That makes way more sense to me.
Are you sure you did not mix update and upgrade somewhere? your posted code about can't work as you misstyped the module name, so i guess  it is not really a copy of your tasks file.

Can you provide more output, by what you mean with does not work? 

For my quick test, as my coffe is nearly sipped up, it works fine:
```bash
{17:13}~ ➭ ansible localhost -m homebrew_cask -a upgrade_all=true --check
```
```json
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

localhost | CHANGED => {
    "changed": true,
    "msg": "Casks would be upgraded."
}
```

**Comment by taraspos** [comment]
@MaxWinterstein 
Not really, I faced this problem because I had to separate tasks, I wanted to update the cache before the actual upgrade (just to be sure it is up-to-date).
So my code looked like:
```
  - name: Update brew cask
    homebrew_cask:
      update_homebrew: yes
  - name: Upgrade brew casks
    homebrew_cask
      upgrade_all: yes
```
And it failed on the first step and I didn't actually try running `upgrade_all: true` :(
Sorry, this confused me because I was doing the same with `homebrew` module and it worked fine, while it didn't for `homebrew_cask`

**Comment by MaxWinterstein** [comment]
oh, now i understand. 
As far as i understand, the cask repository is updated within the regular brew repository. So there is no need for an additional, separate update step.
See: https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks

**Comment by taraspos** [comment]
Yep, I realized that as well, Ansible docs as well say that `update_homebrew: update homebrew itself first. Note that brew cask update is a synonym for brew update.`, but that confused me even more since it worked for `homrebrew` but didn't for `homrebrew_cask`

**Comment by taraspos** [comment]
Can confirm that next code works fine:

```
tasks:
  - name: Update brew packages
     homebrew:
       update_homebrew: yes
       upgrade_all: yes
      
  - name: Update brew casks
     homebrew_cask:
        update_homebrew: yes
        upgrade_all: yes
```
