### ISSUE TITLE
Tilde expansion resolves to master user instead of managed node user

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible#48818]
##### SUMMARY
The use of `~` in dest of copy module resolves to a user from control node and not target one.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/files/copy.py

##### ANSIBLE VERSION
```
2.6.7
```

##### CONFIGURATION
Invoking Ansible playbook via Packer.

##### OS / ENVIRONMENT
Ran playbook from MacOS 10.13.6

##### STEPS TO REPRODUCE
Ansible connects to the destination Ubuntu 16.04 Linux box using `ubuntu` user and uses
`become: yes` & `become_user: root` to do other tasks with elevated privileges.

Task which fails:

```yaml
- name: add MySQL .cnf
  copy:
    force: yes
    src: my.cnf
    dest: ~/.my.cnf
  become: no
```

##### EXPECTED RESULTS
The destination file should be created under user account used by Ansible to connect to the target node, i.e. `ubuntu`

##### ACTUAL RESULTS
It tries to create the file with l local username/home from my laptop.

```
    amazon-ebs: TASK [roles/tools : add MySQL .cnf] *********************************
    amazon-ebs: task path: /Users/<my_local_usename>/ansible/roles/tools/tasks/mysql.yml:2
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "checksum": "bd7e648d38fd40a808e9da712d8f1f0b357c0eb1", "msg": "Destination directory /Users/<my_local_usename> does not exist"}
    amazon-ebs:
```
