### ISSUE TITLE
Authorized_key fails with invalid key specified error

### ISSUE THREAD

**Issue by amit-prayag** [ansible/ansible#48819]
##### SUMMARY

Getting following error, while executing job tempLate with AWX, which shows Ansible is looking for Private Key rather than Pub Key provied in playbook.

 FAILED! => {"changed": false, "msg": "invalid key specified: -----BEGIN RSA PRIVATE KEY-----"}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/system/authorized_key.py

##### ANSIBLE VERSION

```paste below
[root@awx awx]# ansible --version
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/var/lib/awx/projects/_37__demo_proj72232_pm/ansible.cfg) = jsonfil
CACHE_PLUGIN_CONNECTION(/var/lib/awx/projects/_37__demo_proj72232_pm/ansible.cfg
CACHE_PLUGIN_TIMEOUT(/var/lib/awx/projects/_37__demo_proj72232_pm/ansible.cfg) =
DEFAULT_GATHERING(/var/lib/awx/projects/_37__demo_proj72232_pm/ansible.cfg) = sm
DEFAULT_GATHER_TIMEOUT(/var/lib/awx/projects/_37__demo_proj72232_pm/ansible.cfg)
DEFAULT_VAULT_PASSWORD_FILE(/var/lib/awx/projects/_37__demo_proj72232_pm/ansible
```

##### OS / ENVIRONMENT

Centos OS 7 in a Docker Container.
##### STEPS TO REPRODUCE

While execute via AWX, get the error that it is taking private key, instead of pub key, in order to set the authorized_keys.

```yaml
  tasks:
  - name: Create SSH key
    command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
    args:
      creates: /root/.ssh/id_rsa

  - name: Downloading pub key
    fetch: src=/root/.ssh/id_rsa.pub dest=/tmp/id_rsa.tmp flat=yes

  - name: Set authorized key took from file
    authorized_key: # copy local pubkey to remote host
      user: root
      state: present
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: Set authorized key took from file
    authorized_key: # copy local pubkey to remote host
      user: root
      state: present
      key: "{{ lookup('file', '/tmp/id_rsa.tmp') }}"


```

##### EXPECTED RESULTS

It should copy id_rsa.pub key in authorized_keys file.
##### ACTUAL RESULTS

The playbook from CLI runs well, but not from AWX.

```paste below

```

**Comment by ansibot** [comment]
Hi @amit-prayag, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shaked** [comment]
I`m experiencing the same issue. 

If I change:
```
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20160714"
THE KEY
---- END SSH2 PUBLIC KEY ----
```

To

```
ssh-rsa THE KEY
```

It seems to work. 

```
✗ ansible --version
ansible 2.7.7

✗ docker -v
Docker version 18.09.1, build 4c52b90

Ubuntu 16.04
```

**Comment by amithapa** [comment]
I was facing the same issue and the following solution worked out for me:
```yaml
  tasks:
  - name: Set authorized key from file
    authorized_key:
      user: "ansible_user"
      state: present
      key: "{{ lookup('file', item) }}"
    with_fileglob:
    - /home/ansible_user/.ssh/*.pub
```
