### ISSUE TITLE
gcp_compute_instance_facts problem with the ":" operator in filters parameter

### ISSUE THREAD

**Issue by nafpliot** [ansible/ansible#48824]
##### SUMMARY
`gcp_compute_instance_facts` module does not return results when the filter is using the `:` operator. As per [documentation](https://cloud.google.com/sdk/gcloud/reference/topic/filters) the `:` operator can be used to match results when the value of a key contains a given pattern.

For example when using the gcloud command with the `:` operator in filter:
`gcloud compute instances list --filter="status:run"`
the `RUN` part is matched and we get all the instances with `status = RUNNING`. The same behavior should be expected from the module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_compute_instance_facts

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /Users/yolo/.ansible.cfg
  configured module search path = [u'/Users/yolo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Sep 16 2018, 21:01:16) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS 10.14.1

##### STEPS TO REPRODUCE

Run the module with a filter containing `:` instead of `=`
```yaml
---
- name: Retrieving facts from source instances
  gcp_compute_instance_facts:
    zone: "{{ gce_zone }}"
    filters:
      - "status : RUN"
    project: "{{ gce_project }}"
    scopes: "https://www.googleapis.com/auth/compute"
    auth_kind: serviceaccount
    service_account_file: "{{ gce_auth_file }}"
  register: result

- debug:
    var: result
```

```yaml

```

##### EXPECTED RESULTS

We should get back all the instances having `status: RUNNING` set.

##### ACTUAL RESULTS

empty list is returned

```paste below

```
