### ISSUE TITLE
Crash on ec2 un-named NACL update

### ISSUE THREAD

**Issue by johnboy2** [ansible/ansible#48832]
##### SUMMARY
`ansible-playbook` crashes when attempting to update an *unnamed* EC2 NACL, identified by its `nacl_id`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vpc_nacl

##### ANSIBLE VERSION

```
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/johnn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    my_vpc_id: 'vpc-0203b5d32306a922e'
    my_aws_region: 'us-west-2'
  tasks:
    - name: Find the VPCs default NACL
      ec2_vpc_nacl_facts:
        region: '{{ my_aws_region }}'
        filters:
          default: 'true'
          vpc-id: '{{ my_vpc_id }}'
      register: found_default_nacl
      failed_when: not found_default_nacl.nacls

    - name: Report found NACL ID
      debug: var=found_default_nacl.nacls[0].nacl_id

    - name: Ensure VPCs default NACL allows our CIDR lists
      ec2_vpc_nacl:
        region: '{{ my_aws_region }}'
        vpc_id: '{{ my_vpc_id }}'
        nacl_id: '{{ found_default_nacl.nacls[0].nacl_id }}'
        ingress:
          - [1, all, allow, '10.0.0.0/8', null, null, null, null]
        egress:
          - [1, all, allow, '10.0.0.0/8', null, null, null, null]
```

##### EXPECTED RESULTS

The NACL, identified by ID (which the docs explicitly allow), is updated successfully without error.

##### ACTUAL RESULTS

Although the NACL is actually updated, the command fails with an exception.

Non-debug output:

```
johnn@johnn-ws:/tmp$ ansible-playbook ./test.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ********************************************************************************************************************************************************************************************

TASK [Find the VPCs default NACL] ***************************************************************************************************************************************************************************
ok: [localhost]

TASK [Report found NACL ID] *********************************************************************************************************************************************************************************
ok: [localhost] => {
    "found_default_nacl.nacls[0].nacl_id": "acl-05b7862fef4a975e9"
}

TASK [Ensure VPCs default NACL allows our CIDR lists] *******************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Tags[0].Value, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/johnn/.ansible/tmp/ansible-tmp-1542412593.52-119506277744319/AnsiballZ_ec2_vpc_nacl.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/johnn/.ansible/tmp/ansible-tmp-1542412593.52-119506277744319/AnsiballZ_ec2_vpc_nacl.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/johnn/.ansible/tmp/ansible-tmp-1542412593.52-119506277744319/AnsiballZ_ec2_vpc_nacl.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ec2_vpc_nacl_payload_QpEKry/__main__.py\", line 587, in <module>\n  File \"/tmp/ansible_ec2_vpc_nacl_payload_QpEKry/__main__.py\", line 582, in main\n  File \"/tmp/ansible_ec2_vpc_nacl_payload_QpEKry/__main__.py\", line 353, in setup_network_acl\n  File \"/tmp/ansible_ec2_vpc_nacl_payload_QpEKry/__main__.py\", line 267, in tags_changed\n  File \"/tmp/ansible_ec2_vpc_nacl_payload_QpEKry/__main__.py\", line 410, in create_tags\n  File \"/usr/lib/python2.7/dist-packages/botocore/client.py\", line 324, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/lib/python2.7/dist-packages/botocore/client.py\", line 596, in _make_api_call\n    api_params, operation_model, context=request_context)\n  File \"/usr/lib/python2.7/dist-packages/botocore/client.py\", line 631, in _convert_to_request_dict\n    api_params, operation_model)\n  File \"/usr/lib/python2.7/dist-packages/botocore/validate.py\", line 291, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\nInvalid type for parameter Tags[0].Value, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
	to retry, use: --limit @/tmp/test.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1  
```

Stacktrace output from running with `-vvv` (cropped for failed task _only_)
```
The full traceback is:
Traceback (most recent call last):
  File "/home/johnn/.ansible/tmp/ansible-tmp-1542412685.51-54976287802838/AnsiballZ_ec2_vpc_nacl.py", line 113, in <module>
    _ansiballz_main()
  File "/home/johnn/.ansible/tmp/ansible-tmp-1542412685.51-54976287802838/AnsiballZ_ec2_vpc_nacl.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/johnn/.ansible/tmp/ansible-tmp-1542412685.51-54976287802838/AnsiballZ_ec2_vpc_nacl.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ec2_vpc_nacl_payload_1Yk4Dp/__main__.py", line 587, in <module>
  File "/tmp/ansible_ec2_vpc_nacl_payload_1Yk4Dp/__main__.py", line 582, in main
  File "/tmp/ansible_ec2_vpc_nacl_payload_1Yk4Dp/__main__.py", line 353, in setup_network_acl
  File "/tmp/ansible_ec2_vpc_nacl_payload_1Yk4Dp/__main__.py", line 267, in tags_changed
  File "/tmp/ansible_ec2_vpc_nacl_payload_1Yk4Dp/__main__.py", line 410, in create_tags
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 596, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 631, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Tags[0].Value, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
```
