### ISSUE TITLE
Adding file attributes always reports changed when attribute exists alongside others

### ISSUE THREAD

**Issue by NFarrington** [ansible/ansible#48839]
##### SUMMARY

The File module always reports changed when adding an attribute to a file when already has other attributes, even if the attribute is already present.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

File

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /Users/user/personal-projects/ap-ansible/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Jun 17 2018, 12:13:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

1. Create a file with multiple attributes, e.g. `A` and `i`.
2. Use the `file` module to set `+A` on the file. The module will report changed, despite the file already having the `A` attribute.

```yaml
- name: Set file attributes
  file:
    path: /tmp/file_with_attrs
    state: touch
    attributes: "dA"

- name: Set existing file attribute (+A)
  file:
    path: /tmp/file_with_attrs
    state: file
    attributes: "+A"
```

##### EXPECTED RESULTS

```
TASK [common : Set file attributes]
changed: [host]

TASK [common : Set +A]
ok: [host]
```

##### ACTUAL RESULTS

Setting `+A` reports changed, despite the file already having the `A` attribute.

```
TASK [common : Set file attributes]
changed: [host]

TASK [common : Set +A]
changed: [host]
```
