### ISSUE TITLE
ansible-lint "systemctl used in place of systemd module" No systemctl / systemd module.

### ISSUE THREAD

**Issue by vbotka** [ansible/ansible#48848]
Verified.

ansible-lint 3.4.20 is affected

##### SUMMARY

ansible-lint reports "[ANSIBLE0006] systemctl used in place of systemd module" with "command: "systemctl mask {{ item }}"".
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-lint and Ansible Galaxy Syntax Score
##### ANSIBLE VERSION

```paste below
> ansible --version
ansible 2.7.2
  config file = /export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg
  configured module search path = [u'/home/vlado/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg) = True
COLOR_CHANGED(/export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg) = purple
COLOR_DEPRECATE(/export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg) = bright purple
DEFAULT_HOST_LIST(/export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg) = [u'/home/vlado/.ansible/projects/planb.netng.org/hosts']
DEFAULT_STDOUT_CALLBACK(/export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/vlado/.vault_pass.txt
RETRY_FILES_ENABLED(/export/home/vlado.config/.ansible/projects/planb.netng.org/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04
##### STEPS TO REPRODUCE

https://galaxy.ansible.com/vbotka/linux_postinstall
Quality Score Details
E303:  systemctl used in place of systemd module

```yaml
- name: "wpagui: Mask NM services"                                                                                                                                                            
  command: "systemctl mask {{ item }}"                                                                                                                                                        
  loop: "{{ lp_wpagui_service_mask }}"                                                                                                                                                        
  changed_when: false                                                                                                                                                                         
  tags: lp_wpagui_mask_NM
```

##### EXPECTED RESULTS

No warning

##### ACTUAL RESULTS

E303:  systemctl used in place of systemd module

```paste below
> ansible-lint linux-postinstall.yml
[ANSIBLE0006] systemctl used in place of systemd module
/home/vlado/.ansible/roles/vbotka.linux_postinstall/tasks/wpagui.yml:60
Task/Handler: wpagui: Mask NM services
```
