### ISSUE TITLE
File needs state=file to change ownership and permissions

### ISSUE THREAD

**Issue by marcp** [ansible/ansible#4884]
Recent devel version:
ansible 1.4 (devel f31cb7c6e8) last updated 2013/11/12 14:00:57 (GMT -700)

Playbooks that were setting file permissions and ownership are now not working unless we add "state=file" to the file command.

This does not work:

```
- hosts: dev
  tasks:
    - name: Should chmod to 600
      file: path=/home/marcp/test.txt mode=600
```

Although it appears to succeed:

```
$ ansible-playbook -K doink.yml -u marcp -k
SSH password: 
sudo password [defaults to SSH password]: 

PLAY [dev] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Should chmod to 600] *************************************************** 
ok: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0 
```

This works:

```
- hosts: dev
  tasks:
    - name: Should chmod to 600
      file: path=/home/marcp/test.txt mode=600 state=file
```

```
$ ansible-playbook -K doink.yml -u marcp -k
SSH password: 
sudo password [defaults to SSH password]: 

PLAY [dev] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Should chmod to 600] *************************************************** 
changed: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0 
```
