### ISSUE TITLE
win_reboot unable to restart Windows server-Role change is in progress or this computer needs to be restarted.

### ISSUE THREAD

**Issue by dragan1979** [ansible/ansible#48867]
##### SUMMARY
Unable to reboot windows server 2016 when reboot is required, after manual restart, and applying playbook, server is rebooted.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_reboot

##### ANSIBLE VERSION
 
 `ansible 2.7.1`

 

 

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
 

```yaml
- name: install first domain controller
  hosts: winserver
  gather_facts: yes
  tasks:
   - name: install ad
     win_feature: >
          name=AD-Domain-Services
          include_management_tools=yes
          include_sub_features=yes
          state=present
     register: result
   - name: install domain
     win_domain: >
        dns_domain_name=ad.contoso.com
        safe_mode_password=Passw
     register: ad_result
   - name: reboot server
     win_reboot:
      msg: "Joining domain. Rebooting..."
     when: ad_result.reboot_required
```

I'm getting this error when need to reboot server:

```json
fatal: [winserver]: FAILED! => {
    "changed": false, 
    "module_stderr": "Exception calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \"0\" argument(s): \"The running command \r\nstopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: Role change is in \r\nprogress or this computer needs to be restarted.\r\n\"\"\r\nAt line:65 char:5\r\n+     $output = $entrypoint.Run($payload)\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n \r\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
``` 

This happens if i leave only win_reboot:

getting same error when specifying

```yaml
- name: Reboot upon promotion
  raw: shutdown /r
  when: result|changed
  async: 0
  poll: 0
ignore_errors: true
```

However, if, after DC is created, I run playbook again with only `win_reboot:` server is rebooted.

**Comment by ansibot** [comment]
Hi @dragan1979, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_reboot.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_reboot.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dragan1979** [comment]
Really have no idea what happened: removed AD Services, rebooted server, then changed a playbook:

```yaml
  - name: reboot server
    win_reboot:
      msg: "Joining domain. Rebooting..."
      pre_reboot_delay: 10
    when: ad.changed`
```

and now seems to work, i'll close this issue for now
