### ISSUE TITLE
Consistent use of docker config path for docker modules

### ISSUE THREAD

**Issue by barlik** [ansible/ansible#48874]
##### SUMMARY

Ansible module `docker_login` takes `config_path` as a parameter. This is generally a good idea as it's not always desirable to write to the default `$HOME/.docker/config.json` file.

This parameter is, however, missing from any other docker modules. The only way to use alternate docker config file with modules like `docker_image` or `docker_container` is to use environment variable `DOCKER_CONFIG`.
Confusingly enough, `DOCKER_CONFIG` needs to point to a **directory** containing the docker `config.json` file. This is poorly documented and unnecessarily confusing. See included snippet for an example. 

The proposed solutions:
 * add `config_path` parameter to all docker modules
 * alternatively, remove `config_path` from `docker_login` module and document the usage of
    `DOCKER_CONFIG` environment variable for all docker modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_*

##### ADDITIONAL INFORMATION

```yaml
---
- vars:
    registry: remote-docker-registry.host.example
    config_dir: /tmp
  block:
  - name: Login to docker registry
    docker_login:
      config_path: "{{ config_dir }}/config.json"
      registry: "{{ registry }}"
      username: username
      password: password
      email: no-reply@localhost.localdomain

  - docker_image:
      name: "{{ registry }}/image:latest"
      repository: "{{ registry }}/image:v1"
    environment:
      DOCKER_CONFIG: "{{ config_dir }}"

```
