### ISSUE TITLE
[rabbitmq_user] permissions: with multiple vhosts breaks functionality in 2.7.2

### ISSUE THREAD

**Issue by sander85** [ansible/ansible#48890]
##### SUMMARY

Since updating to 2.7.0 (now including 2.7.2) I can't add users anymore with multiple vhosts.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

rabbitmq_user
##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = None
  configured module search path = [u'/home/sander/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/soft/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/soft/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 17:08:05) [GCC 5.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7
##### STEPS TO REPRODUCE

```yaml
rabbitmq_users:
  - {user: 'user1', password: "{{rabbitmq_user1_pwd}}", permissions: [{configure_priv: '.*', read_priv: '.*', write_priv: '.*', vhost: '/dev'},{configure_priv: '.*', read_priv: '.*', write_priv: '.*', vhost: '/dev1'},{configure_priv: '.*', read_priv: '.*', write_priv: '.*', vhost: '/dev2'}], tags: 'management'}

- name: Manage RabbitMQ users
  rabbitmq_user:
    configure_priv: "{{item.configure_priv|default('^$')}}"
    force: "{{item.force|default(omit)}}"
    node: "{{item.node|default('rabbit')}}"
    password: "{{item.password|default(omit)}}"
    permissions: "{{item.permissions|default(omit)}}"
    read_priv: "{{item.read_priv|default('^$')}}"
    state: "{{item.state|default('present')}}"
    tags: "{{item.tags|default(omit)}}"
    update_password: "{{item.update_password|default('always')}}"
    user: "{{item.user}}"
    vhost: "{{item.vhost|default('/')}}"
    write_priv: "{{item.write_priv|default('^$')}}"
  loop: "{{rabbitmq_users}}"
  tags:
    - rabbitmq_users
```

##### EXPECTED RESULTS

Before 2.7 it updated users' permissions

##### ACTUAL RESULTS

Now only those rules work that don't have "permissions:"

```paste below
failed: [rabbitmq-dev01.example.eu] (item={u'permissions': [{u'read_priv': u'.*', u'write_priv': u'.*', u'configure_priv': u'.*', u'vhost': u'/dev'}, {u'read_priv': u'.*', u'write_priv': u'.*', u'configure_priv': u'.*', u'vhost': u'/dev1'}, {u'read_priv': u'.*', u'write_priv': u'.*', u'configure_priv': u'.*', u'vhost': u'/dev2'}], u'password': u'************', u'user': u'user1', u'tags': u'management'}) => {"changed": false, "cmd": "/sbin/rabbitmqctl -q -n rabbit clear_permissions -p vhost user1", "item": {"password": "***********", "permissions": [{"configure_priv": ".*", "read_priv": ".*", "vhost": "/dev", "write_priv": ".*"}, {"configure_priv": ".*", "read_priv": ".*", "vhost": "/dev1", "write_priv": ".*"}, {"configure_priv": ".*", "read_priv": ".*", "vhost": "/dev2", "write_priv": ".*"}], "tags": "management", "user": "user1"}, "msg": "Virtual host 'vhost' does not exist", "rc": 65, "stderr": "Virtual host 'vhost' does not exist\n", "stderr_lines": ["Virtual host 'vhost' does not exist"], "stdout": "", "stdout_lines": []}
```
