### ISSUE TITLE
GCP_compute inventory does not allow dynamic host selection

### ISSUE THREAD

**Issue by RustyTingz** [ansible/ansible#48894]
I have an ansible setup as detailed below which allows me to provision a GCE instance using a role.  This works perfectly with a single environment, however when additional environments are added it seems as though the last environment in the list is used to provision the GCE instance.  

Running the following, executes against stage 
`ansible-playbook -i ansible/inventory.dev.gcp.yml -e 'resources_state=present hosts_group=dev ansible_python_interpreter=/usr/bin/python3' ansible/my-playbook.yml -vvvv`

If the `prod` group_var folder and associated configuration is changed to `zprod` and the same ansible-playbook command is run again it is executed against `zprod`.  

## Ansible Inventory File inventory.yml
```yaml
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    dev:
      hosts:
        localhost:
          ansible_connection: local
    stage:
      hosts:
        localhost:
          ansible_connection: local
    prod:
      hosts:
        localhost:
          ansible_connection: local
```
## Group_vars folders
- all
- dev
- prod
- stage

## GCP_Compute Plugin inventory file - e.g. inventory.dev.gcp.yml

```yaml
plugin: gcp_compute
zones:
  - europe-west1-b
projects:
  - dev
filters:
  - name = my-gce-instance-name
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: ".gcp/dev-ansible-provisioner.json"
auth_kind: serviceaccount
groups:
  dev: true
```

##### COMPONENT NAME
plugin: gcp_compute
