### ISSUE TITLE
fail to add rules to ec2 security group

### ISSUE THREAD

**Issue by alexniehaus** [ansible/ansible#4890]
ansible-playbook 1.4

module: ec2_group

playbook contains :

```
- name: Create ec2 security group
  hosts: local
  connection: local
  tasks:
      - local_action:
            module: ec2_group
            name: testeu2
            description: 'testeu2'
            state: 'present'
            region: eu-west-1
            rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                from_port: 80
                to_port: 80
                cidr_ip: 0.0.0.0/0
```

Creates security group just fine but when running playbook again to try and add a rule:

failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/alexn/.ansible/tmp/ansible-1384330228.56-49642389926506/ec2_group", line 1312, in <module>
    main()
  File "/home/alexn/.ansible/tmp/ansible-1384330228.56-49642389926506/ec2_group", line 199, in main
    addRulesToLookup(group.rules, 'in', groupRules)
  File "/home/alexn/.ansible/tmp/ansible-1384330228.56-49642389926506/ec2_group", line 103, in addRulesToLookup
    grant.group_id, grant.cidr_ip)] = rule
AttributeError: 'GroupOrCIDR' object has no attribute 'group_id'

FATAL: all hosts have already failed -- aborting
