### ISSUE TITLE
can not generate report when number of hosts more than 300

### ISSUE THREAD

**Issue by hoyeunglee** [ansible/ansible#48919]
Ansible version 2.6.0

```
---
- hosts: SSHdevices
  gather_facts: false
  connection: local
  vars:
     date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
     cli:
        host: "{{ ansible_host }}"
        username: ""
        password: ""

  tasks:
   - name: gathering IOS XE facts
     ios_facts:
       gather_subset: all
       provider: "{{ cli }}"
     ignore_errors: yes
     check_mode: no
     register: all_facts

   - name: create HTML report
     template:
       src: report-ios.j2
       dest: /var/www/html/inventory_report_ios.html
       force: yes
     delegate_to: localhost
     ignore_errors: yes
     run_once: true

```

when number of hosts is 2 , it can generate report, but number of hosts more than 300 , it has error and html file has not been overwritten

 FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_net_hostname'"}
