### ISSUE TITLE
vmware_guest_facts returns path strings in "hw_files" part not accurate

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#48929]
##### SUMMARY

The path strings of VM files returned by vmware_guest_facts are not all accurate.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_facts
##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 1dae90325c) last updated 2018/11/20 20:07:04 (GMT +800)
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/root/ansible/ansible.cfg) = /var/log/ansible.log
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: myhost
  tasks:
  - name: 'get VM facts on: myhost'
    register: get_vm_facts
    vmware_guest_facts:
      hostname: myhost
      datacenter: ha-datacenter
      name: auto_deploy_winsrv_bios
      password: test123
      username: root
      validate_certs: false
    delegate_to: localhost
...
```

##### EXPECTED RESULTS

Snapshot files path is accurate, vmware.log file path is accurate.

##### ACTUAL RESULTS

```paste below
 "hw_files": [
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios.vmx", 
            "[GOS] auto_deploy_winsrv2019_331_bios[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios-Snapshot1.vmsn", 
            "[GOS] auto_deploy_winsrv2019_331_bios[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0.vmdk", 
            "[GOS] auto_deploy_winsrv2019_331_bios[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios-Snapshot2.vmsn", 
            "[GOS] auto_deploy_winsrv2019_331_bios[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0.vmdk", 
            "[GOS] auto_deploy_winsrv2019_331_bios[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0-000001.vmdk", 
            "[GOS] auto_deploy_winsrv2019_331_bios[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0-000003.vmdk", 
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios.vmxf", 
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios.nvram", 
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios.vmsd", 
            "[GOS] auto_deploy_winsrv2019_331_biosvmware.log", 
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0.vmdk", 
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0-000001.vmdk", 
            "[GOS] auto_deploy_winsrv2019_331_bios/auto_deploy_winsrv2019_331_bios_1000_0-000002.vmdk"
        ], 
```
