### ISSUE TITLE
pip module not idempotent when using pip > 9.0.1

### ISSUE THREAD

**Issue by MaxWinterstein** [ansible/ansible#48921]
##### SUMMARY

The pip module always comes back as changed. This only happens for pip > 9.0.1 for me.
But when staying on 9.0.1 i always get the "deprecated" warning, which also brings trouble.

I also made a quick *asciinema* to visualize it: https://asciinema.org/a/D5iKSGFuugMP9G8MfChzMkpDr

**Note:** I am using a local python package, this it not pypi related.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

pip
##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Nov 16 2018, 23:13:11) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
 
```

##### OS / ENVIRONMENT

All OS available for me, in repro i use a docker container 
`
python                                                                           2.7                                        f67e752245d6        3 days ago          908MB`
##### STEPS TO REPRODUCE

* start a docker container
 `docker run --rm -ti python:2.7 /bin/bash`
* inside the container:
  * install ansible
    `pip install ansible`
  * install python-setuptools
    `apt update && apt install python-setuptools`
  * get some python package for example docker-py
    `git clone https://github.com/docker/docker-py.git`
  * now run a one-liner to install that package 
    `ansible localhost -i localhost, -c local -m pip -a "name=/docker-py/ state=present"`
  * repeat the last step, it now shows the package as reinstalled, but it should not need to do that

**But** if i downgrade my pip to `9.0.1`:  
`pip install --upgrade pip==9.0.1`  
it works as expected.

##### EXPECTED RESULTS

The module should not return as changed, as there is no need to reinstall it every time.

output of a good result, using pip `9.0.1`:

```yaml
localhost | SUCCESS => {
    "changed": false,
    "cmd": [
        "/usr/local/bin/pip2",
        "install",
        "/docker-py/"
    ],
    "name": [
        "/docker-py/"
    ],
    "requirements": null,
    "state": "present",
    "stderr": "You are using pip version 9.0.1, however version 18.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n",
    "stderr_lines": [
        "You are using pip version 9.0.1, however version 18.1 is available.",
        "You should consider upgrading via the 'pip install --upgrade pip' command."
    ],
    "stdout": "Processing /docker-py\n  Requirement already satisfied (use --upgrade to upgrade): docker==3.6.0.dev0 from file:///docker-py in /usr/local/lib/python2.7/site-packages\nRequirement already satisfied: six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)\nRequirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)\nRequirement already satisfied: docker-pycreds>=0.3.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)\nRequirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)\nRequirement already satisfied: ipaddress>=1.0.16 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)\nRequirement already satisfied: backports.ssl_match_hostname>=3.5 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)\nRequirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)\nRequirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)\nRequirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)\nBuilding wheels for collected packages: docker\n  Running setup.py bdist_wheel for docker: started\n  Running setup.py bdist_wheel for docker: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/2f/52/1b/79c221f3d8441ba817dab55b2ba41c0b87031d85c48aa238d5\nSuccessfully built docker\n",
    "stdout_lines": [
        "Processing /docker-py",
        "  Requirement already satisfied (use --upgrade to upgrade): docker==3.6.0.dev0 from file:///docker-py in /usr/local/lib/python2.7/site-packages",
        "Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)",
        "Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)",
        "Requirement already satisfied: docker-pycreds>=0.3.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)",
        "Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)",
        "Requirement already satisfied: ipaddress>=1.0.16 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)",
        "Requirement already satisfied: backports.ssl_match_hostname>=3.5 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0)",
        "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)",
        "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)",
        "Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)",
        "Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0)",
        "Building wheels for collected packages: docker",
        "  Running setup.py bdist_wheel for docker: started",
        "  Running setup.py bdist_wheel for docker: finished with status 'done'",
        "  Stored in directory: /root/.cache/pip/wheels/2f/52/1b/79c221f3d8441ba817dab55b2ba41c0b87031d85c48aa238d5",
        "Successfully built docker"
    ],
    "version": null,
    "virtualenv": null
}
```

##### ACTUAL RESULTS

Return of model is marked as changed.

```yaml
localhost | CHANGED => {
    "changed": true,
    "cmd": [
        "/usr/local/bin/pip2",
        "install",
        "/docker-py/"
    ],
    "name": [
        "/docker-py/"
    ],
    "requirements": null,
    "state": "present",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Processing /docker-py\nRequirement already satisfied: six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (1.11.0)\nRequirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (0.54.0)\nRequirement already satisfied: docker-pycreds>=0.3.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (0.3.0)\nRequirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (2.20.1)\nRequirement already satisfied: backports.ssl_match_hostname>=3.5 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (3.5.0.1)\nRequirement already satisfied: ipaddress>=1.0.16 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (1.0.22)\nRequirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (3.0.4)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (2018.10.15)\nRequirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (1.24.1)\nRequirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (2.7)\nBuilding wheels for collected packages: docker\n  Running setup.py bdist_wheel for docker: started\n  Running setup.py bdist_wheel for docker: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/2f/52/1b/79c221f3d8441ba817dab55b2ba41c0b87031d85c48aa238d5\nSuccessfully built docker\nInstalling collected packages: docker\n  Found existing installation: docker 3.6.0.dev0\n    Uninstalling docker-3.6.0.dev0:\n      Successfully uninstalled docker-3.6.0.dev0\nSuccessfully installed docker-3.6.0.dev0\n",
    "stdout_lines": [
        "Processing /docker-py",
        "Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (1.11.0)",
        "Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (0.54.0)",
        "Requirement already satisfied: docker-pycreds>=0.3.0 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (0.3.0)",
        "Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (2.20.1)",
        "Requirement already satisfied: backports.ssl_match_hostname>=3.5 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (3.5.0.1)",
        "Requirement already satisfied: ipaddress>=1.0.16 in /usr/local/lib/python2.7/site-packages (from docker==3.6.0.dev0) (1.0.22)",
        "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (3.0.4)",
        "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (2018.10.15)",
        "Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (1.24.1)",
        "Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker==3.6.0.dev0) (2.7)",
        "Building wheels for collected packages: docker",
        "  Running setup.py bdist_wheel for docker: started",
        "  Running setup.py bdist_wheel for docker: finished with status 'done'",
        "  Stored in directory: /root/.cache/pip/wheels/2f/52/1b/79c221f3d8441ba817dab55b2ba41c0b87031d85c48aa238d5",
        "Successfully built docker",
        "Installing collected packages: docker",
        "  Found existing installation: docker 3.6.0.dev0",
        "    Uninstalling docker-3.6.0.dev0:",
        "      Successfully uninstalled docker-3.6.0.dev0",
        "Successfully installed docker-3.6.0.dev0"
    ],
    "version": null,
    "virtualenv": null
}
```

---
this is a follow up of #37177 as it was closed without solving the issue.
