### ISSUE TITLE
Handlers can be executed multiple times when defined in role and used under special circumstances

### ISSUE THREAD

**Issue by basos9** [ansible/ansible#48936]
##### SUMMARY

Handlers can be executed multiple times when the following conditions apply:
a) handler is defined in a role
b) handler is implemented with include_tasks
c) the role is used with **plays' role section** (assuming it does not define a default tasklist) and in a task **import_role**.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0 (devel 2337bb6fad) last updated 2018/11/19 16:59:28 (GMT +300)
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log
```

##### OS / ENVIRONMENT

PRETTY_NAME="Ubuntu 18.04.1 LTS"

##### STEPS TO REPRODUCE

Create a role *testro* with a handlers/main.yml
```yaml
---
  - name: "changed sth"
    import_tasks: "tasks/handler-sth.yml"
```

Create the file tasks/handler-sth.yml
```yaml
---
- name: Restarting this {{ handler_descr }}
  debug:
    msg: "Run this handler"
```

Create the file tasks/loopact.yml
```yaml
---
  - name: loop over changed stuff {{ testfiles | length }}
    command: ls -l {{ item.key }}
    register: cmd
    with_dict: "{{ testfiles }}"
    notify: "{{ testhandlers | default(omit) }}"
```

Create the playbook testhand.yml
```yaml
---
- name: test handler dedup
  hosts: all
  roles:
    - testro  # use handlers and variable definitions
  vars:
    dirs:
      "/": "basic"
      "/home": "users"
      "/var": "generic"
  tasks:

  - name: import action
    import_role: 
      name: testro
      tasks_from: "loopact.yml"
    vars:
      handler_descr: "Many files"
      testfiles: "{{ dirs }}"
      testhandlers: "changed sth"
```

##### EXPECTED RESULTS

```paste below
$ ansible-playbook -i hosts testhand.yml 

PLAY [test handler dedup] ****************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]

TASK [testro : loop over changed stuff 3] ************************************************************
changed: [localhost] => (item={'value': u'basic', 'key': u'/'})
changed: [localhost] => (item={'value': u'generic', 'key': u'/var'})
changed: [localhost] => (item={'value': u'users', 'key': u'/home'})

RUNNING HANDLER [testro : Restarting this Many files] ************************************************
ok: [localhost] => {
    "msg": "Run this handler"
}

PLAY RECAP *******************************************************************************************
localhost     
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i hosts testhand.yml 

PLAY [test handler dedup] ****************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [localhost]

TASK [testro : loop over changed stuff 3] ************************************************************
changed: [localhost] => (item={'value': u'basic', 'key': u'/'})
changed: [localhost] => (item={'value': u'generic', 'key': u'/var'})
changed: [localhost] => (item={'value': u'users', 'key': u'/home'})

RUNNING HANDLER [testro : Restarting this Many files] ************************************************
ok: [localhost] => {
    "msg": "Run this handler"
}

RUNNING HANDLER [testro : Restarting this Many files] ************************************************
ok: [localhost] => {
    "msg": "Run this handler"
}

PLAY RECAP *******************************************************************************************
localhost     
```
