### ISSUE TITLE
Included role cannot properly take vars as argument

### ISSUE THREAD

**Issue by dnorthup-ums** [ansible/ansible#48968]
< !- - - Verify first that your issue is not already reported on GitHub - ->
Either it isn't here, or somebody doesn't think I'd ever want to do this. See #48709 for something similar in intent.

<!- - - Also test if the latest release and devel branch are affected too - ->
I'm not playing development games, I'm attempting to get work done, thank you.

##### SUMMARY
include_role may loop, but runs each time with the same arguments as if it isn't processing the vars passed to it. If include_role is fed a reference to a list (eg, something from group_vars), it only executes once no matter how many items are in the list. If directly fed a list it runs the correct number of times, but only uses the values from the first item in the list.

Reason this matters: We cannot have the test and prod instances of this software on separate hosts for licensing reasons. The vendor will not be moved on this (I've tried many times).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
((Didn't return anything??))
```

##### OS / ENVIRONMENT
CentOS7

##### STEPS TO REPRODUCE

```yaml
  tasks:
  - name: Install the software instances, directly passing the list to `loop:`
    include_role:
      name: rolename
    loop:
    - soft_instance: "prod"
      soft_port: 2021
    - soft_instance: "test"
      soft_port: 2023
  - name: Install the software instances, passing the list to `loop:` from group vars
    include_role:
      name: rolename
    loop: "{{list_in_group_vars}}"


```

##### EXPECTED RESULTS

Run include_vars the number of times matching the length of the list AND use the values passed to it in turn for each pass.

##### ACTUAL RESULTS

I can't give the actual output, sorry. (I don't need to anger our vendors). See summary or ask me something more specific.

```paste below

```

**Comment by ansibot** [comment]
Hi @dnorthup-ums, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I cannot duplicate this issue:

playbook.yml
```
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Install the software instances, directly passing the list to `loop:`
    include_role:
      name: rolename
    loop:
    - soft_instance: "prod"
      soft_port: 2021
    - soft_instance: "test"
      soft_port: 2023
  - name: Install the software instances, passing the list to `loop:` from group vars
    include_role:
      name: rolename
    loop: "{{list_in_group_vars}}"
```

group_vars/all.yml
```
list_in_group_vars:
    - soft_instance: "prod"
      soft_port: 2021
    - soft_instance: "test"
      soft_port: 2023
```

roles/rolename/tasks/main.yml
```
- debug:
    var: item
```

Produces the following output:

```
PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Install the software instances, directly passing the list to `loop:`] ******************************************************************************************************************************************************************

TASK [rolename : debug] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "item": {
        "soft_instance": "prod",
        "soft_port": 2021
    }
}

TASK [rolename : debug] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "item": {
        "soft_instance": "test",
        "soft_port": 2023
    }
}

TASK [Install the software instances, passing the list to `loop:` from group vars] ***********************************************************************************************************************************************************

TASK [rolename : debug] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "item": {
        "soft_instance": "prod",
        "soft_port": 2021
    }
}

TASK [rolename : debug] **********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "item": {
        "soft_instance": "test",
        "soft_port": 2023
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0
```

Seeing as though you cannot show me real output, you should be able to use the reproducer I have created to confirm.

needs_info

**Comment by dnorthup-ums** [comment]
@sivel I used your debug method... The `item` var is evaluated as you demonstrated, which begs a further question.
Are you saying that if a role is to be used with include_role that it must be written in such a way as to be incompatible with being run the normal way (where role vars are provided individually as part of the "call")? I don't see that in the documentation.

**Comment by sivel** [comment]
@dnorthup-ums to be honest, I'm not sure what you are asking.  There is no requirement that roles that are invoked with `include_role` are designed any differently than those used under the `roles` header.

However, as you are looping, which only works with `include_role`, that role would have to make use of the `item` variable, unless you customize that with `loop_control.loop_var` to change the name of the loop variable.

needs_info

**Comment by dnorthup-ums** [comment]
@sivel Thank you, you answered my question. That would indeed mean that the role (as modified for the current include_role implementation) would be incompatible with being run the normal way, as there's no way to pass vars in the way the documentation implies (by omission of note otherwise where it is noted that include_role can loop). This should be either changed (no idea how to best ensure compatibility there) or added as an exception note in the documentation.

For what it is worth, this very bug is the reason why #48709 was requested.

**Comment by sivel** [comment]
I'm not sure what the following statement means:

> there's no way to pass vars in the way the documentation implies (by omission of note otherwise where it is noted that include_role can loop)

You can pass vars into a role when using `include_role` by using the `vars` keyword:

```
- include_role:
    name: rolename
  vars:
    some: thing
```

A role that could work both with `include_role` and under `roles` would use something like:

```
- role: rolename
  top_level_var:
    some: thing
```

and with `include_role`

```
- include_role:
    name: rolename
  loop: "{{ things }}"
  loop_control:
    loop_var: top_level_var
```

Then it would use `top_level_var` in the role.

#48790 was rejected, because we do not believe you should be able to inject the keys of a var into top level scope of a role the way that was proposed.  Either use a top level var name, or be explicit in the `vars` section.  There are many ways to achieve this goal, without adding a new way to inject vars into a role.

As `include_role` is working as expected here, I'm going to close this out.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by dnorthup-ums** [comment]
The documentation clearly indicates that the `vars` keyword in this statement is outside of the loop, therefore it does not accomplish what is desired (unless the documentation is wrong or poorly worded).

```yaml
- include_role:
    name: rolename
  loop: "{{list_from_group_vars}}"
  vars:
    some: thing
```
