### ISSUE TITLE
with_items: is working whereas loop: leads to error 'variable' is undefined. ansible 2.6.4

### ISSUE THREAD

**Issue by jifox** [ansible/ansible#48977]
##### SUMMARY

When using `loop` instead of `with_items` the playbook aborts with an error that the loop: "{{ list }}" is undefined.

When using `with_items` instead of `loop` everything works fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_tasks:
loop:

##### ANSIBLE VERSION

```paste below
ansible 2.6.4
  config file = /home/ansible/devel/net-automation/ansible.cfg
  configured module search path = ['/usr/lib/python3.6/site-packages/napalm_ansible', '/usr/lib/python3.6/site-packages/napalm']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```paste below
DEFAULT_ACTION_PLUGIN_PATH(/home/ansible/devel/net-automation/ansible.cfg) = ['/usr/lib/python3.6/site-packages/napalm_ansible/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/ansible/devel/net-automation/ansible.cfg) = ['/usr/lib/python3.6/site-packages/ansible/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/home/ansible/devel/net-automation/ansible.cfg) = ['selective']
DEFAULT_FILTER_PLUGIN_PATH(/home/ansible/devel/net-automation/ansible.cfg) = ['/home/ansible/devel/net-automation/filter_plugins', '/usr/lib/python3.6/si
DEFAULT_MODULE_PATH(/home/ansible/devel/net-automation/ansible.cfg) = ['/usr/lib/python3.6/site-packages/napalm_ansible', '/usr/lib/python3.6/site-packag
DEFAULT_ROLES_PATH(/home/ansible/devel/net-automation/ansible.cfg) = ['/home/ansible/devel/net-automation/roles']
DEFAULT_STDOUT_CALLBACK(/home/ansible/devel/net-automation/ansible.cfg) = selective
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible/devel/net-automation/ansible.cfg) = /home/ansible/.ssh/ansible-vault
```

##### OS / ENVIRONMENT

localhost

##### STEPS TO REPRODUCE

```yaml
---
#
# file: include/inc_validate_vlan_db.yml
#
#   is part of the tasks: valid_vlan_db.yml, gen_device_specific_vars_from_fabric.yml
#

- name: Ensure that switch_location_group directory is valid
  stat:
    path: "{{ vars_dir }}/{{ switch_location_group }}/vlan_db.yml"
  register: stat_result
  check_mode: false
  delegate_to: localhost
- assert:
    msg: "Missing File: {{ vars_dir }}/{{ switch_location_group }}/vlan_db.yml or incorrect 'switch_localtion:' variable"
    that:
      - stat_result.stat.exists
  check_mode: false
  delegate_to: localhost


- name: Read in the vlan_db
  include_vars:
    file: "{{ vars_dir }}/{{ switch_location_group }}/vlan_db.yml"
  check_mode: false
  changed_when: false


- assert:
    msg: "Missing Parameter: 'switch_location_group' is not defined."
    that:
      - switch_location_group is defined
  check_mode: false
  delegate_to: localhost


- name: Ensure directories exists
  include_tasks: "{{ include_dir }}/inc_validate_directories.yml"
  check_mode: false
  delegate_to: localhost


- assert:
    msg: "Duplicate Entry at group vars/{{ switch_location_group }}/vlan_db.yml in variable vlan_db.vlan_groups"
    that: >
          vlan_db.vlan_groups | list | count
          ==
          vlan_db.vlan_groups | list | unique | count
  check_mode: false
  delegate_to: localhost


- name: Linting vlan_db.yml file
  block:
    - shell: /usr/bin/ansible-lint "{{base_dir}}/vars/{{switch_location_group}}/vlan_db.yml"
      register: lint_result
      changed_when: false
    - assert:
        msg: "ansible-lint: {{ lint_result.stderr }}"
        that:
          - lint_result.stderr == ""
  check_mode: false
  delegate_to: localhost

- set_fact:
   all_vlans: "{{ vlan_db.vlan_defines | flatten }}"

- debug:
    msg: "{{ all_vlans }}"
  delegate_to: localhost
  tags: [print_action]

- name: Check vlan_deploy list is in vlan_groups
  include_tasks: "{{ include_dir }}/inc_validate_vlan_db_check_one_vlan.yml"
  loop: "{{ all_vlans }}"    #  <---FAILING  with_items: {{ all_vlans }} is working correctly
  loop_control:
    loop_var: check_vlan_id
  delegate_to: localhost
```

##### EXPECTED RESULTS

Loop should be executed the same way with 'loop:' as will do with 'with_items:'

##### ACTUAL RESULTS

```paste below
ansible@scvnetmgmt01 net-automation (develop *%=) $ ansible-playbook -i inv_develop.yml --limit ATBRACSE010 valid_vlan_db.yml -vvvvv
ansible-playbook 2.6.4
  config file = /home/ansible/devel/net-automation/ansible.cfg
  configured module search path = ['/usr/lib/python3.6/site-packages/napalm_ansible', '/usr/lib/python3.6/site-packages/napalm']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /home/ansible/devel/net-automation/ansible.cfg as config file
Reading vault password file: /home/ansible/.ssh/ansible-vault
setting up inventory plugins
Parsed /home/ansible/devel/net-automation/inv_develop.yml inventory source with yaml plugin
Loading callback plugin selective of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/selective.py
1 plays in valid_vlan_db.yml
META: ran handlers
# Validate vlan datastructure *********************************************************************************************
  * ATBRACSE010                - changed=False --  --------------------------------------------
  * ATBRACSE010                - FAILED!!! -- 'all_vlans' is undefined ------------------------
        to retry, use: --limit @/home/ansible/devel/net-automation/valid_vlan_db.retry

# STATS *******************************************************************************************************************
ATBRACSE010    : ok=0   changed=0       failed=1        unreachable=0
```
Output when using the working version that uses `with_items:`
```paste below
ansible@scvnetmgmt01 net-automation (develop *%=) $ ansible-playbook -i inv_develop.yml --limit ATBRACSE010 valid_vlan_db.yml 
....................
# debug *******************************************************************************************************************
  * ATBRACSE010                - changed=False --------------------------------------------------
    ['1', '2', '5', '10', '17', '18', '19', '20', '30', '32', '33', '34', '37', '60', '61', '70', '71', '90', '98', '99', '100', '101', '103', '105', '106', '150', '200', '239', '240', '2010', '2012', '2018', '2020', '2022', '2024', '2026', '2028', '2030', '2032', '2034', '2036', '2038', '2040', '2042', '2044', '2046', '2048', '2050', '2060', '2062', '2064', '2066', '2068', '2070', '2080', '2082', '2084', '2086', '2088', '2090', '2092', '2094', '2096', '2098', '2110', '2112', '2220', '2222', '2224', '2226', '2228', '2300', '2302', '2304', '2306', '2308', '2310', '2312', '2314', '2316', '2318', '2320', '2324', '2330', '3010', '3012', '3018', '3040', '3042', '3046', '3048', '3050', '3060', '3062', '3064', '3066', '3068', '3070', '3080', '3082', '3084', '3086', '3088', '3090', '3092', '3094', '3096', '3098', '3220', '3222', '3224', '3226', '3228', '3300', '3302', '3304', '3306', '3308', '3310', '3312', '3314', '3316', '3318', '3320', '3322']
............
```
