### ISSUE TITLE
azure_rm_loadbalancer does not include the "inbound_nat_rules" parameter

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ansible/ansible#48987]
##### SUMMARY

`azure_rm_loadbalancer` does not support the parameter inbound_nat_rules

##### ISSUE TYPE
- Implement inbound_nat_rules on the azure_rm_loadbalancer

##### COMPONENT NAME
azure_rm_loadbalancer

##### ADDITIONAL INFORMATION
Deploying the marketplace item "FortiGate NGFW Azure LB High Availability" deploys an Azure LoadBalancer with specific NAT rules enabled. I would like to duplicate that marketplace object in an Ansible playbook, however, I'm currently unable to do this in entirety due to the missing "inbound_nat_rules" element.

Running the module `azure_rm_loadbalancer_facts` against the LB created by the marketplace item, and then debugging the resulting (slightly sanitized) value returns the following array of data: https://gist.github.com/JonTheNiceGuy/dcb6d27e4f0a1f6c40824a00ae5bae74#file-azure_rm_loadbalancer_facts-json-L72-L149 (the lines in question are highlighted)

I would then expect to invoke the module as follows:

```yaml
  - azure_rm_loadbalancer:
      resource_group: my_rg
      name: lb
      frontend_ip_configurations:
      - name: lb_fe_a
        public_ip_address: lb_fe_a_pubip
      - name: lb_fe_b
        public_ip_address: lb_fe_b_pubip
      backend_address_pools:
      - name: lb_backend
      probes:
      - name: lbprobe
        port: 22
      inbound_nat_rules:
      - backend_ip_configuration: vm_a_nic
        frontend_ip_configuration: lb_fe_a
        backend_port: 22
        frontend_port: 22
        protocol: Tcp
        idle_timeout_in_minutes: 4
      - backend_ip_configuration: vm_b_nic
        frontend_ip_configuration: lb_fe_b
        backend_port: 22
        frontend_port: 22
        protocol: Tcp
        idle_timeout_in_minutes: 4
```

It should be noted that there is also a repo called https://github.com/Azure/azure_preview_modules and https://github.com/Azure/azure_modules, so it might be that one of these should be where this change is introduced - please let me know if you need me to raise an issue on one of those.
