### ISSUE TITLE
Add state "disabled" to route53_health_check module

### ISSUE THREAD

**Issue by kellervater** [ansible/ansible#49019]
##### SUMMARY

In module "route53_health_check" it would be helpful to be able to deactivate health checks.
My use case is to disable/deactivate health checks during a deployment and afterwards reenable them.
In the AWS Route 53 console it can be done via "Advanced Configuration" by checking "Disable health check". This option considers the health check positive as long as it is deactivated.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

route53_health_check

##### ADDITIONAL INFORMATION

I think the simplest way would be to add the state "disabled". So new health checks can be created in a disabled state or existing health checks will get disabled.

The other option would be to add the flag "disabled" additionally to the "present" state.

```yaml
- route53_health_check:
    state: disabled
    fqdn: host1.example.com
    type: HTTPS
    resource_path: /
  register: my_health_check
```
