### ISSUE TITLE
Prevent remove anything while installing package with apt

### ISSUE THREAD

**Issue by quanvuminh** [ansible/ansible#49020]
##### SUMMARY
Installing a package will force to remove conflicted packages including some important and unexpected ones.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

apt

##### ADDITIONAL INFORMATION

It would be better to have an argument to prevent this behavior. 

```yaml
- name:
   apt:
     name: <package_name>
     remove: no
```
