### ISSUE TITLE
acme_certificate challenge_data.resource_value has wrong quotation marks for AWS Route53

### ISSUE THREAD

**Issue by endorama** [ansible/ansible#49032]
##### SUMMARY

The `acme_certificate` example related to Route53 DNS-01 validation for ACME challenge explicitly states that *route53 requires TXT entries to be enclosed in quotes*. 
Running the code in the example leads to an error from AWS APIs:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Invalid Resource Record: FATAL problem: InvalidCharacterString (Value should be enclosed in quotati
on marks) encountered with '<challenge code omitted>'"}
```
Searching the [AWS documentation](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#TXTFormat) it seems that **double** quotation marks are required.

> A TXT record contains one or more strings that are enclosed in double quotation marks (").

So either the [examples in the documentation](https://docs.ansible.com/ansible/latest/modules/acme_certificate_module.html#examples) should be updated or the quotation enclosing the `record_value`.

Thanks to the second example the workaround to make it work with Route53 is straightforward:

```
- route53:
    zone: "example.com"
    record: "{{ item.key }}"
    state: present
    type: TXT
    ttl: 60
    # Note: route53 requires TXT entries to be enclosed in quotes
    value: "{{ item.value | map('regex_replace', '^(.*)$', '\"\\1\"' ) | list }}"
  loop: "{{sample_com_challenge.challenge_data_dns | dict2items}}"
  when: sample_com_challenge is changed
```
Note the `'\"\\1\"'` in place of `'\'\\1\''`.

Thank you for looking into this.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `acme_certificate`

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /home/endorama/code/github.com/.../operations/ansible.cfg
  configured module search path = [u'/home/endorama/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/endorama/.local/share/virtualenvs/operations-Xz-KgfLF/local/lib/python2.7/site-packages/ansible
  executable location = /home/endorama/.local/share/virtualenvs/operations-Xz-KgfLF/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below
DEFAULT_ACTION_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugins/
DEFAULT_CACHE_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugins/c
DEFAULT_CALLBACK_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugin
DEFAULT_CONNECTION_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plug
DEFAULT_FILTER_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugins/
DEFAULT_GATHERING(/home/endorama/code/github.com/.../operations/ansible.cfg) = smart
DEFAULT_INVENTORY_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugi
DEFAULT_LOOKUP_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugins/
DEFAULT_REMOTE_USER(/home/endorama/code/github.com/.../operations/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/roles/community'
DEFAULT_STRATEGY_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugin
DEFAULT_TERMINAL_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugin
DEFAULT_TEST_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugins/te
DEFAULT_VARS_PLUGIN_PATH(/home/endorama/code/github.com/.../operations/ansible.cfg) = [u'/home/endorama/code/github.com/.../operations/plugins/va
HOST_KEY_CHECKING(/home/endorama/code/github.com/.../operations/ansible.cfg) = False
INJECT_FACTS_AS_VARS(/home/endorama/code/github.com/.../operations/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/endorama/code/github.com/.../operations/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```yaml
### Example with DNS challenge against production ACME server ###

- name: Create a challenge for sample.com using a account key file.
  acme_certificate:
    account_key_src: /etc/pki/cert/private/account.key
    account_email: myself@sample.com
    src: /etc/pki/cert/csr/sample.com.csr
    cert: /etc/httpd/ssl/sample.com.crt
    challenge: dns-01
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    # Renew if the certificate is at least 30 days old
    remaining_days: 60
  register: sample_com_challenge

# perform the necessary steps to fulfill the challenge
# for example:

- route53:
    zone: sample.com
    record: "{{ sample_com_challenge.challenge_data['sample.com']['dns-01'].record }}"
    type: TXT
    ttl: 60
    # Note: route53 requires TXT entries to be enclosed in quotes
    value: "{{ sample_com_challenge.challenge_data['sample.com']['dns-01'].resource_value }}"
    when: sample_com_challenge is changed
```

##### EXPECTED RESULTS

Route53 record is created successfully.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Invalid Resource Record: FATAL problem: InvalidCharacterString (Value should be enclosed in quotati
on marks) encountered with '<challenge code omitted>'"}
```
