### ISSUE TITLE
NPM module is not installing project dependencies

### ISSUE THREAD

**Issue by kennashka** [ansible/ansible#49049]
##### SUMMARY
I would like to use npm install module but it is not working as expected, I had to use command module to install my project dependencies. I have tried multiple times with removing and adding some of the parameters options such as production and global but nothing seems to work. Please assist with this. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
npm 

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

Ubuntu 16.04
##### STEPS TO REPRODUCE

```yaml
  vars:
    app_folder: 'nodeapp'

tasks:
       - name: Install required npm packages
         npm:
           name: helmet
           global: yes
           state: present
           production: yes
           path: /home/ubuntu/{{ app_folder }}/

       - name: Install required npm packages
         npm:
           name: express-force-ssl
           global: yes
           state: present
           production: yes
           path: /home/ubuntu/{{ app_folder }}/
```

##### EXPECTED RESULTS

For npm installs to be added globally and to package.json file

##### ACTUAL RESULTS

PLAY [adc] ***********************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
ok: [52.87.170.208]

TASK [Install required npm packages] *********************************************************************************************************************
changed: [52.87.170.208]

TASK [Install required npm packages] *********************************************************************************************************************
changed: [52.87.170.208]

```paste below

```
