### ISSUE TITLE
Apt module fails when replacing a loop by a list for name parameter

### ISSUE THREAD

**Issue by niko2** [ansible/ansible#49043]
##### SUMMARY
As suggested by this warning
```
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying 
`name: {{ item }}`, please use `name: [u'linux-image-amd64', u'{{ __pve_kernel.old_packages }}']` and remove the loop. This feature will be removed in version 2.11. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
I tried to replace the loop with this list
```
    name: ['linux-image-amd64','{{ __pve_kernel.old_packages }}']
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10

```

##### OS / ENVIRONMENT

Linux Mint 18 as control host
Debian 9.6 as target host

##### STEPS TO REPRODUCE

```
- name: Collect kernel package information
  collect_kernel_info:
  register: __pve_kernel

- name: Remove old Debian/PVE kernels
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - linux-image-amd64
    - "{{ __pve_kernel.old_packages }}"
  when:
    - pve_remove_old_kernels
```
replaced by 

```yaml
- name: Collect kernel package information
  collect_kernel_info:
  register: __pve_kernel

- name: Remove old Debian/PVE kernels
  apt:
    name: ['linux-image-amd64','{{ __pve_kernel.old_packages }}']
    state: absent
    purge: yes
  when:
    - pve_remove_old_kernels
```
or by 
```
- name: Collect kernel package information
  collect_kernel_info:
  register: __pve_kernel

- name: Remove old Debian/PVE kernels
  apt:
    name:
      - linux-image-amd64
      - "{{ __pve_kernel.old_packages }}"
    state: absent
    purge: yes
  when:
    - pve_remove_old_kernels
```
produces same error (see below)

##### EXPECTED RESULTS

original code that produces deprecated warning is
```
TASK [pve_kernel : Remove old Debian/PVE kernels] **********************************************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying 
`name: {{ item }}`, please use `name: [u'linux-image-amd64', u'{{ __pve_kernel.old_packages }}']` and remove the loop. This feature will be removed in version 2.11. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [target_host] => (item=[u'linux-image-amd64', u'pve-kernel-4.15.18-7-pve', u'pve-kernel-4.15.18-8-pve'])

```

##### ACTUAL RESULTS

```paste below
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1542930962.09-17143637316515/AnsiballZ_apt.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1542930962.09-17143637316515/AnsiballZ_apt.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1542930962.09-17143637316515/AnsiballZ_apt.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_apt_payload_QQEYHF/__main__.py\", line 1127, in <module>\r\n  File \"/tmp/ansible_apt_payload_QQEYHF/__main__.py\", line 1118, in main\r\n  File \"/tmp/ansible_apt_payload_QQEYHF/__main__.py\", line 698, in remove\r\n  File \"/tmp/ansible_apt_payload_QQEYHF/__main__.py\", line 439, in expand_pkgspec_from_fnmatches\r\n  File \"/tmp/ansible_apt_payload_QQEYHF/__main__.py\", line 312, in package_split\r\nAttributeError: 'list' object has no attribute 'split'\r\n", 

```
