### ISSUE TITLE
seport: Not able to manage ports with selinux

### ISSUE THREAD

**Issue by vutkin** [ansible/ansible#49050]
##### SUMMARY
Reproduced in AWS scenario (with enabled) selinux

Preinstalled packages:

"policycoreutils-python"
"libsemanage-python"
"libselinux-python"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/system/seport.py

##### ANSIBLE VERSION

```paste below
ansible 2.5.8
  config file = /home/gitlab-runner/.ansible.cfg
  configured module search path = [u'/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py']
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible']
```

##### OS / ENVIRONMENT

CentOS 6 latest from aws
Python 2.6.6
##### STEPS TO REPRODUCE

```yaml
- name: "Enable connections to 8001 port"
      seport:
        ports: "8001"
        proto: "tcp"
        setype: "http_port_t"
        state: "present"
      when: ansible_selinux.status == "enabled" and ansible_selinux.mode != "disabled"
```

##### EXPECTED RESULTS

enable port 8001

##### ACTUAL RESULTS

```paste below
fatal: [test-endeca-mdex]: FAILED! => {
        "changed": false,
        "module_stderr": "Shared connection to ec2-xxxxxxx-central-1.compute.amazonaws.com closed.\r\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE",
        "rc": 247
```
