### ISSUE TITLE
Git cannot clone into specified directory

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#49109]
##### SUMMARY
A git clone using Ansible is throwing an error. This particular play is using become_user, although it didn't work if I removed it an executed it as root.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0 (devel 69191b10c1) last updated 2018/11/22 10:50:03 (GMT -500)
  config file = None
  configured module search path = [u'/Users/kbreit/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kbreit/Documents/Programming/ansible/lib/ansible
  executable location = /Users/kbreit/Documents/Programming/ansible/bin/ansible
  python version = 2.7.14 (default, Feb 25 2018, 14:48:55) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
macOS 10.13.x

##### STEPS TO REPRODUCE
```yaml
    - name: Create directory
      file:
        path: ~/projects
        state: directory
      become_user: '{{username}}'
    - name: Clone git repositories
      git:
        dest: "~{{username}}/projects/"
        repo: "{{repos}}"
      vars:
        repos:
          - git@github.com:kbreit/ansible-playbooks.git
          - git@github.com:kbreit/ansible.git
      become_user: '{{username}}'
```
##### EXPECTED RESULTS
Ansible should properly clone the repository on the remote.

##### ACTUAL RESULTS
```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_git_payload_CCAmrw/__main__.py", line 450, in clone
    os.makedirs(dest_dirname)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

fatal: [dev.digitalocean.kb-lab.net]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/git clone --origin origin '['\"'\"'git@github.com:********@github.com:kbreit/ansible.git'\"'\"']' /home/kbreit/projects",
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "archive": null,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/home/kbreit/projects/",
            "executable": null,
            "force": false,
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "['git@github.com:kbreit/ansible-playbooks.git', 'git@github.com:kbreit/ansible.git']",
            "separate_git_dir": null,
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "msg": "Cloning into '/home/kbreit/projects'...\nfatal: No path specified. See 'man git-pull' for valid url syntax",
    "rc": 128,
    "stderr": "Cloning into '/home/kbreit/projects'...\nfatal: No path specified. See 'man git-pull' for valid url syntax\n",
    "stderr_lines": [
        "Cloning into '/home/kbreit/projects'...",
        "fatal: No path specified. See 'man git-pull' for valid url syntax"
    ],
    "stdout": "",
    "stdout_lines": []
}
	to retry, use: --limit @/Users/kbreit/Documents/Programming/cloud_dev_environment/main.retry

```
