### ISSUE TITLE
k8s module isn't processing Kind: List

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/ansible#49100]
##### SUMMARY
I'm currently trying to run through some samples with the `k8s` module and it doesn't seem to handle the Openshift `kind: List` well. Whenever I try to run a file through with this type, I see the error: `Failed to find exact match for v1. by [kind, name, singularName, shortNames]`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`k8s`

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /Users/tylerauerbeck/workspace/openshift-applier/ansible.cfg
  configured module search path = [u'/Users/tylerauerbeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:47:18) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/Users/tylerauerbeck/workspace/openshift-applier/ansible.cfg) = [u'profile_tasks']
HOST_KEY_CHECKING(/Users/tylerauerbeck/workspace/openshift-applier/ansible.cfg) = False
INVENTORY_UNPARSED_IS_FAILED(/Users/tylerauerbeck/workspace/openshift-applier/ansible.cfg) = True
RETRY_FILES_ENABLED(/Users/tylerauerbeck/workspace/openshift-applier/ansible.cfg) = False
```

##### OS / ENVIRONMENT
MacOS Mojave 10.14

##### STEPS TO REPRODUCE
In order to reproduce this, you can run the below through with the following Openshift objects:
```yaml
---
apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: my-cakephp-dev
  displayName: My CakePHP Dev Project
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: my-cakephp-test
  displayName: My CakePHP Test Project
```

This is being tested with ansible 2.7 and openshift client 0.8.1
```
pip freeze | grep openshift        
openshift==0.8.1
```

Example Playbook:
```yaml
---

- hosts: localhost
  tasks:
    - name: 'Test Project Requests'
      k8s:
        state: 'present'
        src: '/path/to/my-cakephp-spaces.yml'
```

##### EXPECTED RESULTS
After running the above, I would expect two Project Requests to be processed: my-cakephp-dev and my-cakephp-test

##### ACTUAL RESULTS
Playbook fails with the error indicating it doesn't know how to match this type.

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/var/folders/8v/wkw8yj196fnbsjz87lfymrc40000gn/T/ansible_k8s_payload_tsgHVs/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py", line 194, in find_resource
    return self.client.resources.get(api_version=api_version, short_names=[kind])
  File "/usr/local/lib/python2.7/site-packages/openshift/dynamic/client.py", line 531, in get
    raise ResourceNotFoundError('No matches found for {}'.format(kwargs))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to find exact match for v1. by [kind, name, singularName, shortNames]"
}
```
