### ISSUE TITLE
How can i delete the “u” from the list output？

### ISSUE THREAD

**Issue by zhangmingld** [ansible/ansible#49117]
##### SUMMARY

I write a playbook, for example
```yaml
- hosts: masters
  sudo: yes
  tasks:
    - name: set master extra vars
      set_fact:
         kube_apiserver_extra_args:
            - --logtostderr=false
            - --allow-privileged=true
            - --feature-gates=PersistentLocalVolumes=true,PodPriority=true
            - --runtime-config=scheduling.k8s.io/v1alpha1=true
            - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
         kube_controller_manager_extra_args:
            - --logtostderr=false
            - --horizontal-pod-autoscaler-use-rest-clients=false
            - --node-monitor-grace-period=1m
            - --leader-elect-retry-period=5s
         kube_scheduler_extra_args:
            - --logtostderr=false
            - --feature-gates=PersistentLocalVolumes=true,PodPriority=true
            - --leader-elect-retry-period=5s

    - name: insert extra_args to hostvars
      lineinfile:
        dest: host_vars/{{ inventory_hostname }}
        state: present
        line: '{{ item }}'
      delegate_to: localhost
      with_items:
           - "kube_apiserver_extra_args: {{ kube_apiserver_extra_args }}"
           - "kube_controller_manager_extra_args: {{ kube_controller_manager_extra_args }}"
           - "kube_scheduler_extra_args: {{ kube_scheduler_extra_args }}"
```
So,  i get the result like this:
```
kube_scheduler_extra_args: [u'--logtostderr=false', u'--feature-gates=PersistentLocalVolumes=true,PodPriority=true', u'--leader-elect-retry-period=5s']
```
Well,  we have a "u" here 

Can we delete this u from the result ?
or Is there any way to avoid this "u" ?

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```
