### ISSUE TITLE
wait_for doesnt work in handler

### ISSUE THREAD

**Issue by emobortnik** [ansible/ansible#49141]
```
  handlers:
    - name: reboot
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
    - name: Wait for the host to finish rebooting
      local_action: wait_for host={{ ansible_host }} port=22 delay=15 connect_timeout=200
      become: false
      delegate_to: localhost
```

but this works in task fine, why

![ansible](https://user-images.githubusercontent.com/34957923/49031775-98cfdf00-f1b3-11e8-81d6-d16fc5d08276.png)

**Comment by ansibot** [comment]
Hi @emobortnik, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@emobortnik: in order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by emobortnik** [comment]
##### SUMMARY
wait_for doesnt work in handler

##### ISSUE TYPE

 - Bug Report


##### COMPONENT NAME
wait_for doesnt work in handler

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]


```

##### CONFIGURATION

```output is empty

```

##### OS / ENVIRONMENT

ubuntu 18.04 host and the same is remote node

##### STEPS TO REPRODUCE

just run playbook which is bellow


```yaml
---
- hosts: ca3.mysuperdomen.com
  become: true
  tasks:
  roles:
    - base
    - setupvpn



  post_tasks:
    - name:
      debug:
        msg: dont forget to replace login if you need


  handlers:
    - name: reboot
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system reboot"
      async: 1
      poll: 0
    - name: Wait for the host to finish rebooting
      local_action: wait_for host={{ ansible_host }} port=22 delay=15 connect_timeout=200
      become: false
      delegate_to: localhost

```



##### EXPECTED RESULTS

handler reboot works but local_action: wait_for host doesnt. But in task its works.
