### ISSUE TITLE
meraki_network - Update combined network type

### ISSUE THREAD

**Issue by ericdost** [ansible/ansible#49149]
##### SUMMARY

Combined network type automatically sets type to `switch wireless appliance` however not all combined templates are set up this way.  It appears that Combined only supports devices that are associated to an Organization.  Our org does not have wireless and the network would not bind to the configuration template until I removed wireless from the type payload.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

meraki_network

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules', u'/home/ansible/.ansible/roles/mkouhei.include_csv']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/callbacks']
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks', u'dense', u'selective']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/.ansible/tmp/ansible-local-14602D6jlLw
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules', u'/home/ansible/.ansible/roles/mkouhei.include_csv']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

Create a new network with type combined on an organization that only has 2 of the 3 types
Attempt to bind the network to a configuration template

```yaml
---

- name: GET DATE AND GATE
  connection: local
  hosts: localhost

  vars:
    my_key: 'abc12345'
    my_org: 'Meraki Organization'
    my_net_name: 'Meraki_Network'
    address: "1060 W. Addison St., Chicago, IL"
    mx_serial: "ABC-123"
    mx_name: "ABC-RT01"
    ms_name: "ABC-SW01"
    ms_serial: "ABC-456"
    config_template: "Standard_Site"

  tasks:

    - name: "Create meraki network {{ my_net_name }}"
      meraki_network:
        auth_key: " {{ my_key }}"
        state: present
        org_name: "{{ my_org }}"
        net_name: "{{ my_net_name }}"
        type: combined
        timezone: America/Chicago
        tags: production, central
      delegate_to: localhost

    - name: Pause for Meraki API rate limiting
      pause:
        seconds: 1

    - name: "Bind {{ mx_serial }} to {{ my_net_name }}"
      meraki_device:
        auth_key: "{{ my_key }}"
        org_name: "{{ my_org }}"
        net_name: "{{ my_net_name }}"
        serial: "{{ mx_serial }}"
        state: present
      delegate_to: localhost

    - name: Pause for Meraki API rate limiting
      pause:
        seconds: 1

    - name: "Bind {{ ms_serial }} to {{ my_net_name }}"
      meraki_device:
        auth_key: "{{ my_key }}"
        org_name: "{{ my_org }}"
        net_name: "{{ my_net_name }}"
        serial: "{{ ms_serial }}"
        state: present
      delegate_to: localhost

    - name: Pause for Meraki API rate limiting
      pause:
        seconds: 1

    - name: "Bind network {{ my_net_name }} to configuration template {{ config_template }}"
      meraki_config_template:
        auth_key: "{{ my_key }}"
        state: present
        org_name: "{{ my_org }}"
        net_name: "{{ my_net_name }}"
        config_template: "{{ config_template }}"
        auto_bind: yes
      delegate_to: localhost
```

##### EXPECTED RESULTS

Network to bind to config template

##### ACTUAL RESULTS

Error received due to incompatible network types

```paste below
fatal: [localhost -> localhost]: FAILED! => {
    "body": {
        "errors": [
            "'Meraki_Network' cannot be bound to 'Standard_Site' because they have incompatible network types."
        ]
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "auth_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "auto_bind": true, 
            "config_template": "Standard_Site", 
            "follow_redirects": "all", 
            "host": "api.meraki.com", 
            "net_id": null, 
            "net_name": "Meraki_Network", 
            "org_id": null, 
            "org_name": "Meraki Organization", 
            "output_level": "normal", 
            "protocol": "https", 
            "state": "present", 
            "timeout": 30, 
            "use_https": true, 
            "use_proxy": false, 
            "validate_certs": true
        }
    }, 
    "msg": "Request failed for https://api.meraki.com/api/v0/networks/<snip>/bind: 400 - HTTP Error 400: Bad Request", 
    "response": "HTTP Error 400: Bad Request", 
    "status": 400
}

```
