### ISSUE TITLE
oVirt: host occasionally fails to install

### ISSUE THREAD

**Issue by UXabre** [ansible/ansible#49164]
##### SUMMARY

Sometimes an oVirt host fails te get installed because the API returned something unexpected and a object of NoneType is returned; which has no status field.

It's not always reproducible and the exact reason why the API fails isn't clear either. I'd say this happens once every 5 installations on average.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_host

##### ANSIBLE VERSION

```paste below
Ansible-2.7
```

##### OS / ENVIRONMENT

CentOS 7.5; running in same subnet as the machine on which I install oVirt.
The device on which this runs is an APU2 with 4GB of RAM and 3 NICs, for which two are bonded and used for communication towards the to-be-oVirt engine host. So, not a heavy-hitter but I'd assume enough for these kind of use-cases.

##### STEPS TO REPRODUCE

I actually use the oVirt Ansible Playbooks on top, but looking at the playbook, this should be enough:

```yaml
- name: Add hosts
  ovirt_host:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.state | default(omit) }}"
    name: "{{ item.name }}"
    address: "{{ item.address }}"
    cluster: "{{ item.cluster }}"
    password: "{{ item.password | default(omit) }}"
    public_key: "{{ item.public_key | default(omit) }}"
    override_iptables: true
    timeout: "{{ item.timeout | default(ovirt_hosts_add_timeout) }}"
    poll_interval: "{{ item.poll_interval | default(20) }}"
    hosted_engine: "{{ item.hosted_engine | default(omit) }}"
  with_items:
    - "{{ hosts | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ ovirt_hosts_max_timeout }}"
  poll: 0
  register: add_hosts
  tags:
    - hosts
```

##### EXPECTED RESULTS

I expected that oVirt module doesn't fail because of an API error. Or, put differently: I would expect Ansible only to fail if the installation actually failed.

##### ACTUAL RESULTS

Once every 5 times on average, I'd get a similar error message from the one below (ran in debug, so sorry for the info overload). BUT, the oVirt host gets installed correctly.

```paste below
{"exception": "Traceback (most recent call last):\n File \"/tmp/ansible_ovirt_hosts_wa_44726_payload_yrn8Nn/__main__.py\", line 451, in main\n fail_condition=hosts_module.failed_state_after_reinstall if host is None else lambda h: False,\n File \"/tmp/ansible_ovirt_hosts_wa_44726_payload_yrn8Nn/ansible_ovirt_hosts_wa_44726_payload.zip/ansible/module_utils/ovirt.py\", line 610, in create\n poll_interval=self._module.params['poll_interval'],\n File \"/tmp/ansible_ovirt_hosts_wa_44726_payload_yrn8Nn/ansible_ovirt_hosts_wa_44726_payload.zip/ansible/module_utils/ovirt.py\", line 335, in wait\n elif fail_condition(entity):\n File \"/tmp/ansible_ovirt_hosts_wa_44726_payload_yrn8Nn/__main__.py\", line 324, in failed_state_after_reinstall\n if host.status in [\nAttributeError: 'NoneType' object has no attribute 'status'\n", "ansible_job_id": "48639052969.30299", "failed": true, "finished": 1, "invocation": {"module_args": {"comment": null, "activate": true, "force": false, "power_management_enabled": null, "cluster": "democustomer", "fetch_nested": false, "hosted_engine": null, "check_upgrade": true, "kdump_integration": null, "iscsi": null, "state": "present", "reboot_after_upgrade": true, "nested_attributes": [], "address": "mac549f3507b0ae.democustomer.televic.com", "override_iptables": true, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "wait": true, "public_key": false, "name": "mac549f3507b0ae.democustomer.televic.com", "spm_priority": null, "poll_interval": 20, "kernel_params": null, "timeout": 1200, "override_display": null}}, "msg": "'NoneType' object has no attribute 'status'"}
```

As far as I can tell, the error seems to be here:
https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/cloud/ovirt/ovirt_host.py#L324

I think we should retry, let's say, three times if a null-object has been returned?
