### ISSUE TITLE
ssh.Connection doesn't always collect all output

### ISSUE THREAD

**Issue by iffy** [ansible/ansible#4917]
I don't know for sure that the problem is the yum module.  The error is sporadic on an identical machine (a Vagrant VM) with an identical playbook/role.

Here is the relevant part of the role's playbook:

``` yaml
- name: Update yum packages to latest version
  yum: name=*
       state=latest
```

The failure/success cases are too big for the issue tracker, so I'll pastebin them instead.

Here's a failure: https://gist.github.com/iffy/7487203
Here's a success: https://gist.github.com/iffy/7487303
