### ISSUE TITLE
Support commands in authorized_key

### ISSUE THREAD

**Issue by henti** [ansible/ansible#49185]
##### SUMMARY
authorized_keys supports the ability to limit commands for key authentication. This is detailed in the authorized_keys man page

```
command="command"
             Specifies that the command is executed whenever this key is used
             for authentication.  The command supplied by the user (if any) is
             ignored.  The command is run on a pty if the client requests a
             pty; otherwise it is run without a tty.
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
authorized_key

##### ADDITIONAL INFORMATION
Currently the only way to limit commands would be using  `ForceCommand` in sshd_config, which would be system wide and not allow limiting commands to keys

```yaml
- name: Set authorized key taken from file and limit to command
  authorized_key:
    user: charlie
    state: present
    key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
    command: "/usr/local/bin/run_command"
    command_options: '-u username -l location'
```
This will execute `/usr/local/bin/run_command -u username -l location` on matching of key for user as user charlie and ignore any command options send via ssh. 

Currently adding required `command=<command>` string using something like `lineinfile` means the playbook revers that change.

**Comment by ansibot** [comment]
Hi @hentisemmle, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)
* [lib/ansible/modules/system/authorized_key.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/authorized_key.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/plugins/lookup](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
!component =lib/ansible/modules/system/authorized_key.py

**Comment by samdoran** [comment]
This can be accomplished by using the `key_options` parameter. 

```yaml
- name: Set authorized key defining key options
  authorized_key:
    user: charlie
    state: present
    key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
    key_options: 'no-port-forwarding,from="10.0.1.1"'
```

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
