### ISSUE TITLE
docker_swarm_service fails because of default "user: root"

### ISSUE THREAD

**Issue by fchiacchiaretta** [ansible/ansible#49199]
##### SUMMARY
I'm trying to start a service ([Traefik Load Balancer](https://traefik.io)) via docker_swarm_service and it fails because of `user: root` being passed by default in the invocation.
I can properly start the service if I specify `user: ''` or `user: ` (passes as user: null in the invocation), but service declaration is not idempotent, every time I run the deploy I get 
```json
[...]
    "changed": true,
    "changes": [
        "user"
    ],
[...]
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_swarm_service

##### ANSIBLE VERSION
```
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fchiacchiaretta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Nov 23 2018, 10:01:49) [GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]
```

##### OS / ENVIRONMENT

Control station OS: Fedora 29
Target OS: Debian 8.11 Jessie
Target docker version:

```
Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

##### STEPS TO REPRODUCE
Start a traefik service:
```yaml
  - name: Create traefik LB on manager node
    docker_swarm_service:
      debug: yes
      name: traefik-lb
      image: 'traefik:1.7'
      user:
      constraints:
      - "node.role==manager"
      networks:
      - traefik-net
      publish:
      - published_port: 8080
        target_port: 8080
      - published_port: 8081
        target_port: 8081
      args:
      - "--defaultEntryPoints=http"
      - "--entryPoints=Name:http Address::8080"
      - "--entryPoints=Name:mgt Address::8081"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=traefik"
      - "--docker.watch"
      - "--api"
      - "--api.entrypoint=mgt"
      - "--api.statistics.recentErrors=100"
      mounts:
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        type: bind
```

##### EXPECTED RESULTS
I can start a service without specifying user parameter

##### ACTUAL RESULTS
Service start fails. If I specify `user: ''` or `user: ` (passes as user: null in the invocation) it succeeds, but it is not idempotent anymore.

Best,
Federico Chiacchiaretta
