### ISSUE TITLE
Module ProxySQL - Backend_servers error

### ISSUE THREAD

**Issue by matt-horwood-mayden** [ansible/ansible#49191]
##### SUMMARY
Using the proxysql_backend_servers module, I get an error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/database/proxysql/proxysql_backend_servers.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /Users/user/.ansible.cfg
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION

```paste below
DEFAULT_ASK_SUDO_PASS(/Users/user/.ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/user/.ansible.cfg) = [u'/Users/user/git/ansible/inventories/production/hosts']
DEFAULT_REMOTE_USER(/Users/user/.ansible.cfg) = user
```

##### OS / ENVIRONMENT

MacOS 10.14.1 (18B75)

##### STEPS TO REPRODUCE

Use the proxysql_backend_servers in a task

```yaml
# Add or remove backend servers
- name: Add backend server
  proxysql_backend_servers:
    login_user: "{{ proxysql_admin_user }}"
    login_password: "{{ proxysql_admin_password }}"
    hostname: "{{ item.address }}"
    port: "{{item.port}}"
    hostgroup_id: "{{ item.hostgroup }}"
    state: present
    load_to_runtime: "{{ load_to_runtime }}"
    save_to_disk: "{{ save_to_disk }}"
  with_items: "{{ proxysql_mysql_servers }}"
  when:
    - proxysql_mysql_servers is defined
    - proxysql_mysql_servers_remove is undefined
```

##### EXPECTED RESULTS

The backend servers are added to proxysql

##### ACTUAL RESULTS

The module errors out

```paste below
failed: [host] (item={u'port': 3306, u'hostgroup': 2, u'address': u'1.2.3.4'}) => {"changed": false, "item": {"address": "1.2.3.4", "hostgroup": 2, "port": 3306}, "module_stderr": "Shared connection to 1.2.3.3 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1543327459.08-40750051886508/AnsiballZ_proxysql_backend_servers.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1543327459.08-40750051886508/AnsiballZ_proxysql_backend_servers.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1543327459.08-40750051886508/AnsiballZ_proxysql_backend_servers.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_yTxxSk/__main__.py\", line 504, in <module>\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_yTxxSk/__main__.py\", line 450, in main\r\nAttributeError: 'module' object has no attribute 'cursors'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
