### ISSUE TITLE
ali_instance: local variable 'filters' referenced before assignment

### ISSUE THREAD

**Issue by zhaolx01** [ansible/ansible#49225]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ali_instance

##### ANSIBLE VERSION

```
Ansible 2.6.3

```

##### CONFIGURATION

```ANSIBLE_NOCOWS(/home/lixia/ansible-test/oss/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/lixia/ansible-test/oss/ansible.cfg) = [u'/home/lixia/ansible-test/oss/hosts']
DEFAULT_LOG_PATH(/home/lixia/ansible-test/oss/ansible.cfg) = /var/log/ansible.log
DEPRECATION_WARNINGS(/home/lixia/ansible-test/oss/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```yaml
---
- name: Create an instance
  hosts: localhost
  vars:
    alicloud_access_key: xxxxx
    alicloud_secret_key: xxxxx
    alicloud_region: cn-shenzhen
    image_id: m-wz90t3wxz4c7a5e615ba
    type: ecs.xn4.small 
    instance_name: test-zlx-gtz-master-server
    description: gtz.io-master
    host_name: myhost
    password: Rhwl2018
    count: 1
    allocate_public_ip: True
    internet_charge_type: PayByBandwidth
    max_bandwidth_in: 100
    max_bandwidth_out: 10
  tasks:
    - name: create the instance on ECS
      alicloud_instance:
        alicloud_access_key: '{{alicloud_access_key}}'
        alicloud_secret_key: '{{alicloud_secret_key}}'
        alicloud_region: '{{alicloud_region}}'
        image_id: '{{image_id}}'
        instance_type: '{{type}}'
        instance_name: '{{instance_name}}'
        system_disk_size: 100      
        #description: '{{description}}'
        host_name: '{{host_name}}'
        password: '{{password}}'     
        vswitch_id: 'vsw-wz9u54p59fqetgf0v49m1'
        group_id: 'sg-wz99lk5j1zbivcxmh6ef'
        count: '{{count}}'
        allocate_public_ip: '{{allocate_public_ip}}'
        internet_charge_type: '{{internet_charge_type}}'
        max_bandwidth_in: '{{max_bandwidth_in}}'
        max_bandwidth_out: '{{max_bandwidth_out}}'
      register: ecs

```

##### EXPECTED RESULTS

```
TASK [create the instance on ECS] *************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'filters' referenced before assignment
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_0cA8zx/ansible_module_alicloud_instance.py\", line 589, in <module>\n    main()\n  File \"/tmp/ansible_0cA8zx/ansible_module_alicloud_instance.py\", line 439, in main\n    instances = ecs.get_all_instances(zone_id=zone_id, instance_name=instance_name)\n  File \"/usr/local/lib/python2.7/dist-packages/footmark/ecs/connection.py\", line 267, in get_all_instances\n    for inst in self.get_list_new(self.build_request_params(filters), ['Instances', Instance]):\nUnboundLocalError: local variable 'filters' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/lixia/ansible-test/oss/aliyun.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

##### ACTUAL RESULTS

```paste below

```
