### ISSUE TITLE
firewalld module can not set target property of a zone

### ISSUE THREAD

**Issue by juame** [ansible/ansible#49232]
##### SUMMARY
It's possible to set a `target` property with `firewall-cmd` for a specific firewalld zone:
```bash
~]# firewall-cmd --zone=zone-name --set-target=<default|ACCEPT|REJECT|DROP>
```
(Source: [RHEL 7 Documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-working_with_zones#sec-Using_Zone_Targets_to_Set_Default_Behavior_for_Incoming_Traffic))

To accept any traffic in a zone it would be great to be able to change from `target: default` to `target: ACCEPT` with the firewalld module. Or vice versa.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
firewalld

##### ADDITIONAL INFORMATION

With firewall-cmd:
```bash
# firewall-cmd --zone=myzone --list-all
myzone (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth1
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
# firewall-cmd --zone=myzone --set-target=ACCEPT --permanent
success

# firewall-cmd --reload
success

# firewall-cmd --zone=myzone --list-all
myzone (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: eth1
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

```

My workaround with command...:
```yaml
- name: populate variable for zone target
  command: 'firewall-cmd --permanent --zone={{ nic.key }} --get-target'
  changed_when: false
  when: nic.value.firewalld_zone_state == 'present'
  become: yes
  register: firewalld_zones_targets
  loop: "{{ lookup('dict', baseos_nics, wantlist=True) }}"
  loop_control:
    loop_var: nic
  tags:
    - firewalld

- name: ensure firewalld zone target
  command: 'firewall-cmd --permanent --zone={{ zone.nic.key }} --set-target={{ zone.nic.value.firewalld_zone_target }}'
  when:
    - zone.stdout is defined
    - zone.stdout != zone.nic.value.firewalld_zone_target|default('default')
  become: yes
  notify: reload firewalld
  loop: '{{ firewalld_zones_targets.results|default([]) }}'
  loop_control:
    loop_var: zone
  tags:
    - firewalld
```

Vars:

```yaml
baseos_nics:
  myzone:
    interface: eth0
    firewalld_zone_state: present
    firewalld_zone_target: default
    ipv4_address: '{{ ansible_eth0.ipv4.address }}'
```
