### ISSUE TITLE
Wrong changed state reported by docker_swarm_service

### ISSUE THREAD

**Issue by dariko** [ansible/ansible#49285]
##### SUMMARY
devel version of docker_swarm_service incorrectly reports changed state 

Some on the changes merged on #45674 (the `publish` and `update_force` parameters defaults, as an example) while correctly working on the older docker version in which they where tested by CI now wrongly reports changed state when run on recent docker versions.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_swarm_service

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0 (devel c51407c806) last updated 2018/11/29 08:44:43 (GMT +200)
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/src/ansible/lib/ansible
  executable location = /tmp/tests/venv/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  become: true
  tasks:
  - docker_swarm_service:
      name: test
      state: absent
  - docker_swarm_service:
      name: test
      image: 'nginx'
  - name: test idempotency
    docker_swarm_service:
      name: test
      image: 'nginx'
```

##### EXPECTED RESULTS
The second call to docker_service should return `changed=False`

##### ACTUAL RESULTS
Using docker 17.03.0-ce the `test idempotency` reports `changed=False`.
Using docker 18.09.0 the `test idempotency` reports `changed=True`.

**Comment by ansibot** [comment]
Hi @dariko, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_swarm_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_swarm_service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akshay196 @danihodovic @felixfontein @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hannseman** [comment]
Also seeing the wrong changed state reported for image when specifying an image digest:

```yml
- hosts: localhost
  become: true
  tasks:
    - docker_swarm_service:
        name: "test"
        image: "org/an_image@sha256:61b4c705859f4158d38090c1e38e8fdc4f3d29db007f012766276aa498835cf6"
```

```
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "image": "org/an_image"
+    "image": "org/an_image@sha256:61b4c705859f4158d38090c1e38e8fdc4f3d29db007f012766276aa498835cf6"
 }

changed: [localhost]
```


I'm running docker 18.06

**Comment by hannseman** [comment]
Also related to 
https://github.com/ansible/ansible/issues/50467

**Comment by felixfontein** [comment]
I don't think we officially support image digests yet, so there's no reason why they should work :) `docker_container` will probably have the same problem.

**Comment by hannseman** [comment]
I see, maybe that discussion is best made in a new issue then. One cool usecase is to trigger a service update when a new image is available instead of having to set `force_update`.

```yaml
- name: pull latest app image
  docker_image:
    name: "{{ app_image_name }}:{{ app_image_tag }}"
    force: true
  register: "app_image"

- name: get app image digest
  set_fact:
    app_image_digest: "{{ app_image.image.RepoDigests[0] }}"

- name: create app service
  docker_swarm_service:
    name: "app"
    image: "{{ app_image_digest }}"
```
