### ISSUE TITLE
unarchive as non-root is returning UnarchiveError when the zip is already unarchived

### ISSUE THREAD

**Issue by bbourdin** [ansible/ansible#49284]
##### SUMMARY

UnarchiveError is returned when trying to unarchive (as non-root) a zip file which has already been already unarchived.

The failing code in the unarchive module seems to be that specific condition, because the groups array is empty ([only containing supplemental groups](https://docs.python.org/2/library/os.html#os.getgroups)) :
```python
if run_uid != 0 and fut_gid not in groups:
     raise UnarchiveError('Cannot change group ownership of %s to %s, as user %s' % (path, fut_group, run_owner))
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

[unarchive module](https://docs.ansible.com/ansible/2.5/modules/unarchive_module.html)

##### ANSIBLE VERSION

```console
ansible 2.6.4
python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

empty ansible configuration

##### OS / ENVIRONMENT

Linux ubuntu 16.04 (docker container based on [ubuntu:16.04](https://hub.docker.com/_/ubuntu/)) 

User/group configured as below :
```console
$ id
uid=1000(raffia) gid=1000(raffia) groups=1000(raffia)
$ groups
raffia
```

So python would return the folowing :
```python
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print os.getgid()
1000
>>> print os.getgroups()
[]
>>>
```

##### STEPS TO REPRODUCE

Paste this content in a file called test.yml :
```yaml
---

- hosts: "{{ NODE }}" 
  tasks: 
    - name: create the subfolder for extracting
      local_action:
        module: file
        path: "mysubfolder"
        state: directory
    - name: unarchive one zip file
      local_action:
        module: unarchive
        src: "test.zip"
        dest: "mysubfolder"
```
Create your zip file before the first run :
```console
$ touch test.txt
$ zip test.zip test.txt
$ ls -l test.zip
-rwxr-xr-x 1 raffia raffia 166 Nov 29 08:46 test.zip
```

Command to start the playbook :
```console
ansible-playbook -i localhost, --connection=local -e "NODE=localhost" test.yml
```

##### EXPECTED RESULTS

First run (doing the unarchive) :
```console
TASK [unarchive one zip file] **************************************************
changed: [localhost -> localhost]
```

Second run (when the unarchive is already done) :
```console
TASK [create the subfolder for extracting] *************************************
ok: [localhost -> localhost]
```

##### ACTUAL RESULTS

First run (doing the unarchive) :
```console
TASK [unarchive one zip file] **************************************************
changed: [localhost -> localhost]
```

We have the folowing :
```console
$ ls -l
total 16
drwxr-xr-x 2 raffia raffia 4096 Nov 29 08:47 mysubfolder
-rw-r--r-- 1 raffia raffia    0 Nov 29 08:46 test.txt
-rwxr-xr-x 1 raffia raffia  314 Nov 29 08:46 test.yml
-rwxr-xr-x 1 raffia raffia  166 Nov 29 08:46 test.zip
$ ls -l mysubfolder/
total 0
-rw-r--r-- 1 raffia raffia 0 Nov 29 08:30 test.txt
```

Second run (when the unarchive is already done, with extra verbosity) :
```python-traceback
TASK [unarchive one zip file] **************************************************
task path: /tmp/test2/test.yml:10
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: raffia
<localhost> EXEC /bin/sh -c 'echo ~raffia && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230 `" && echo ansible-tmp-1543482824.34-170663587758230="` echo /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/stat.py
<localhost> PUT /home/raffia/.ansible/tmp/ansible-local-779iC5mLs/tmppSq5eo TO /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/stat.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/ /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/stat.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/stat.py && sleep 0'
<localhost> PUT /tmp/test2/test.zip TO /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/source
<localhost> EXEC /bin/sh -c 'chmod u+x /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/ /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/source && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/unarchive.py
<localhost> PUT /home/raffia/.ansible/tmp/ansible-local-779iC5mLs/tmpOIWRVy TO /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/unarchive.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/ /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/unarchive.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/unarchive.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/raffia/.ansible/tmp/ansible-tmp-1543482824.34-170663587758230/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ZxzT7f/ansible_module_unarchive.py", line 906, in <module>
    main()
  File "/tmp/ansible_ZxzT7f/ansible_module_unarchive.py", line 864, in main
    check_results = handler.is_unarchived()
  File "/tmp/ansible_ZxzT7f/ansible_module_unarchive.py", line 555, in is_unarchived
    raise UnarchiveError('Cannot change group ownership of %s to %s, as user %s' % (path, fut_group, run_owner))
__main__.UnarchiveError: Cannot change group ownership of test.txt to raffia, as user raffia

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZxzT7f/ansible_module_unarchive.py\", line 906, in <module>\n    main()\n  File \"/tmp/ansible_ZxzT7f/ansible_module_unarchive.py\", line 864, in main\n    check_results = handler.is_unarchived()\n  File \"/tmp/ansible_ZxzT7f/ansible_module_unarchive.py\", line 555, in is_unarchived\n    raise UnarchiveError('Cannot change group ownership of %s to %s, as user %s' % (path, fut_group, run_owner))\n__main__.UnarchiveError: Cannot change group ownership of test.txt to raffia, as user raffia\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

This error only happens when running as non-root. When trying as root, it works.

**Comment by ansibot** [comment]
Hi @bbourdin, thank you for submitting this issue!

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/unarchive.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/unarchive.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pileofrogs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I can't reproduce the issue:
```
$ docker images
REPOSITORY                                     TAG                 IMAGE ID            CREATED             SIZE
docker.io/ubuntu                               16.04               a51debf7e1eb        3 weeks ago         116 MB
```
```
$ docker run --name ubuntu --rm -i -t docker.io/ubuntu:16.04 bash
```
in the container from above:
```
$ id
uid=1000(mkrizek) gid=1000(mkrizek) groups=1000(mkrizek)
$ groups
mkrizek
$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getgid()
1000
>>> os.getgroups()
[1000]
```

**Comment by webknjaz** [comment]
Here's what I've got:
```console
$ docker run --name ubuntu --rm -i -t ubuntu:16.04 bash
root@fff3104844ec:/# python2.7 
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getgid()
0
>>> os.getgroups()
[]
root@fff3104844ec:/# su - test_user
No directory, logging in with HOME=/
$ python2.7
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getgid()
1000
>>> os.getgroups()
[1000]
>>> 
$ id
uid=1000(test_user) gid=1000(test_user) groups=1000(test_user)
$ groups
test_user
$ cd /tmp/test_unzip/
$ touch test.txt
$ zip test.zip test.txt
  adding: test.txt (stored 0%)
$ ls -l test.zip
-rw-rw-r-- 1 test_user test_user 166 May 31 12:18 test.zip
```
(getgid/getgroups are different from what's in the initial report and also zip archive privileges are different meaning other umask)

**Comment by webknjaz** [comment]
Running the playbook multiple times succeeds (Ansible 2.8).

**Comment by webknjaz** [comment]
Not reproducible under Ansible 2.7/2.6.

**Comment by philipsd6** [comment]
I've reproduced this in the latest AWX 9.0.1 (using Ansible 2.10.0.dev0) with a playbook using tasks like this:

```yaml
- unarchive:
    src: "{{ source_archive }}"
    dest: "{{ destination|quote }}"
    list_files: yes
  register: unarchived

# We don't know what the root directory is in the archive, and
# we want to unpack directly into the destination
- set_fact:
    archive_root_dirs: "{{ archive_root_dirs |default([]) |union(item.split('/')[0:1]) }}"                                       
  loop: "{{ unarchived.files }}"

# Delete what we just unarchived (wouldn't it be nice if the unarchive module supported check_mode?)
- file:
    dest: "{{ destination|quote }}/{{ archive_root_dirs[0] }}"                                                              
  state: absent

# Use this special trick to unzip the contents of the zipfile's root
# directory directly into the destination
- file:
    src: "."
    dest: "{{ destination|quote }}/{{ archive_root_dirs[0] }}"                                                              
    state: link

- unarchive:
    src: "{{ source_archive }}"
    dest: "{{ destination|quote }}"

- file:
    dest: "{{ destination|quote }}/{{ archive_root_dirs[0] }}"
    state: absent
```

The _second_ `unarchive` fails with:
`UnarchiveError: Cannot change group ownership of test-playbook-0.0.1/ to root, as user awx`
