### ISSUE TITLE
missing double quotes in variable

### ISSUE THREAD

**Issue by arnmtk** [ansible/ansible#49282]
##### SUMMARY

Ansible automatically escapes double quotes in variable. Even if variable is in single quotes '{{ var }}'.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /home/x/ansible/ansible-venv/lib/python2.7/site-packages/ansible
  executable location = /home/x/ansible/ansible-venv/bin/ansible
  python version = 2.7.11 (default, Aug 15 2016, 07:05:53) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

```
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
```
Ansible is used in virtual environment. Installed via pip install ansible

##### STEPS TO REPRODUCE

I am passing SQL query in ansible variable (via extra vars) and it has double quotes inside. After i stdout to console the double quotes are missing. 

```yaml
**Playbook**

- hosts: test
  remote_user: x
  roles:
    - query

**Command**

ansible-playbook -i inventory/hosts.something playbook.yml --extra-vars "query='SELECT COUNT(*) FROM "sql_table";'"

**Task**
- name: print query
  debug:
    msg: "'{{ query }}'"

```

##### Component name

I am using module "debug" for testing. I tried to pass variables value to other modules and results are same.

##### EXPECTED RESULTS

I want that quotes in both sides of word _coreApi_visitortracking_ would not be escaped.
```
ok: [replica2.vm.revelup.com] => {
    "msg": "'SELECT COUNT(*) FROM "sql_table";'"
}
```
##### ACTUAL RESULTS

```
ok: [replica2.vm.revelup.com] => {
    "msg": "'SELECT COUNT(*) FROM sql_table;'"
}
```
