### ISSUE TITLE
Unable to run playbooks on VMWARE 6.5 vCenter being part of Enchanced Linked Mode with external PSC

### ISSUE THREAD

**Issue by Whiteface84** [ansible/ansible#49287]
##### SUMMARY

Unable to run playbooks on VMWARE 6.5 vCenter being part of Enchanced Linked Mode with external PSC (Platform Services Controller) 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: vmware_guest

##### ANSIBLE VERSION

```
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

```
Target OS: VMware Version 6.5.0.20000 Build 8667236
```
##### STEPS TO REPRODUCE

```
Run any playbook with vmware_guest module on vCenter being part of Linked Mode with External PSC
```

```yaml

# create a new VM from a template
 
- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
       
  tasks:
        
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: vc.corp
        username: administrator@vsphere.local
        password: password
        folder: Ansible
        esxi_hostname: esx303.corp
        datacenter: DC1
        name: test
        template: ansible_template_v2
        disk:
          - size_gb: 30
            type: thin
            datastore: DS1
        networks:
          - name: VLAN_1
            type: static
            ip: 10.10.10.199
            netmask: 255.255.255.0
            gateway: 10.10.10.254
            dns_servers:
            - 10.10.10.1
            - 10.10.10.11
        hardware:
          memory_mb: 1024
          num_cpus: 1
        state: poweredon
        customization:
         dns_servers:
         - 10.10.10.1
         - 10.10.10.11
         domain: corp
         hostname: test
        wait_for_ip_address: yes
```

##### EXPECTED RESULTS

```
Clone virtual machine from template 
```
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unknown error while connecting to vCenter or ESXi API at  vc.corp:443 : [Errno 110] Connection timed out"}
```

```paste below

```
