### ISSUE TITLE
elb_application_lb wait flag should also wait for state "absent"

### ISSUE THREAD

**Issue by kellervater** [ansible/ansible#49291]
##### SUMMARY

In the module elb_application_lb the activated wait flag should also wait for the absent state.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

elb_application_lb

##### ADDITIONAL INFORMATION

We automatically provision and delete AWS resources for our CI feature branches. This also includes creation and deletion of load balancers and target groups assigned to them.
It' currently not possible to delete resources automatically without a workaround.
The example below doesn't work and fails with
`Target group 'arn:aws:elasticloadbalancing:region:account:targetgroup/targetgroup/xyz' is currently in use by a listener or a rule`

```yaml
- name: "Delete load balancer"
  elb_application_lb:
    name: "{{ application_name }}-{{ environment_name }}"
    region: "{{ aws_region }}"
    state: absent
    wait: yes

- name: "Delete target groups"
  elb_target_group:
    name: "{{ application_name }}-{{ environment_name }}-{{ item }}"
    region: "{{ aws_region }}"
    state: absent
  with_items:
    - blue
    - green
  register: target_group
```
