### ISSUE TITLE
F5 bigip_virtual_server module "present" state overrides existing virtual server state

### ISSUE THREAD

**Issue by tomservo3428** [ansible/ansible#49315]
##### SUMMARY
When using the bigip_virtual_server module, I found that when I attempt to update an existing disabled virtual server, the setting the state to "present" in the task (an Ansible best practice) will enable the virtual server. I discovered this when I applied a mass change to existing virtual servers in our lab environment where all of the virtual servers were disabled. 

Also, it might be worth looking at other attributes that have default values and how those are sent on existing objects. For instance, if an attribute isn't listed in a playbook task, is there a default value returned that could override the existing value?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/xxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

OS: macOS Mojave
Targets: F5 BIG-IPs

##### STEPS TO REPRODUCE

```yaml
    - name: Update Description for Dev VIPs
      bigip_virtual_server:
        provider: "{{ provider }}"
        state: "present"
        name: "{{ item.name }}"
        description: "::dev:: {{ item.description | default('') }}"
      with_items: "{{ myvips.virtual_servers }}"
```

##### EXPECTED RESULTS

Only the description of the existing virtual servers would be updated. All other attributes would be left in their current state.

##### ACTUAL RESULTS

All of the disable virtual servers were enabled.

```paste below

```
