### ISSUE TITLE
Puppet: Disable/Enable Agent

### ISSUE THREAD

**Issue by pioto** [ansible/ansible#49323]
##### SUMMARY

When using Ansible and Puppet in conjunction, it is possible for one to "step on" the other.

To avoid Puppet interfering with a running Ansible playbook, it would be helpful if there was support for specifically running:

```
puppet agent --disable "Doing Blah"
```

and, when done, run:

```
puppet agent --enable
```

It'd be "nice to have" for this to be part of the puppet module, rather than using raw commands, as it can be idempotent.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

puppet

##### ADDITIONAL INFORMATION

I'd see this working in a playbook something like this:

```yaml
- name: Disable Puppet
  puppet:
    enabled: no
    message: Doing Blah
- name: Upgrade Stuff
  yum: '....'
- name: Enable Puppet
  puppet:
    enabled: yes
```
