### ISSUE TITLE
ini_file: comment matching an option is deleted

### ISSUE THREAD

**Issue by seblu** [ansible/ansible#49340]
##### SUMMARY
It looks like comment matching an option is removed by the ini_file module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module ini_file

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /home/seblu/scm/ansible/ansible.cfg
  configured module search path = ['/home/seblu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### OS / ENVIRONMENT
Arch Linux.

##### STEPS TO REPRODUCE

Define an option with the same text as a comment line, will remove the comment line.
A good test file is the default [firewalld.conf](https://github.com/firewalld/firewalld/blob/master/config/firewalld.conf).

###### the relevant original ini file part

```ini
# FirewallBackend
# Selects the firewall backend implementation.
# Choices are:
#	- nftables (default)
#	- iptables (iptables, ip6tables, ebtables and ipset)
FirewallBackend=nftables
```

###### vars definition:

```yaml
  base_firewall_options:
    FirewallBackend: iptables
```
###### the playbook
```yaml
- name: define firewalld options
  ini_file:
    path: "{{ base_firewall_config }}"
    section: null
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
    state: present
  loop: "{{ base_firewall_options|dict2items }}"
  notify: reload firewalld
```

##### EXPECTED RESULTS

Comment should not be modified.
```paste below
TASK [base : define firewalld options] **************************************************************************************************************************************
--- before: /etc/firewalld/firewalld.conf (content)
+++ after: /etc/firewalld/firewalld.conf (content)
@@ -56,9 +56,8 @@
 # Default: system
 AutomaticHelpers=system
 
 # FirewallBackend
 # Selects the firewall backend implementation.
 # Choices are:
 #	- nftables (default)
 #	- iptables (iptables, ip6tables, ebtables and ipset)
-FirewallBackend=nftables
+FirewallBackend=iptables
```

##### ACTUAL RESULTS

```paste below
TASK [base : define firewalld options] **************************************************************************************************************************************
--- before: /etc/firewalld/firewalld.conf (content)
+++ after: /etc/firewalld/firewalld.conf (content)
@@ -56,9 +56,8 @@
 # Default: system
 AutomaticHelpers=system
 
-# FirewallBackend
+FirewallBackend=iptables
 # Selects the firewall backend implementation.
 # Choices are:
 #	- nftables (default)
 #	- iptables (iptables, ip6tables, ebtables and ipset)
-FirewallBackend=nftables
```
