### ISSUE TITLE
parsing json failling if 'items' as a key

### ISSUE THREAD

**Issue by michalswi** [ansible/ansible#49369]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/miswierc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04.5 LTS

##### STEPS TO REPRODUCE

If you run `kubectl --kubeconfig kube get svc --all-namespaces -ojson` you get json with key items.  
```json
ok: [localhost] => {
    "msg": {
        "apiVersion": "v1", 
        "items": [
            {
                "apiVersion": "v1", 
                "kind": "Service", 
...
```
If **items** as a key in json, executing playbook fails. If you put different name for key like 'noitems' it works but it's only possible if you edit json file..
I guess it's because items are python method.

```yaml
- name: Test
  hosts: localhost
  connection: local
  gather_facts: False
  any_errors_fatal: True
  tasks:
  - name: dummy json
    set_fact:
      dummy_json: '{"items":[{"test":"demo1"},{"test":"demo2"}]}'
  
  - name: parse to json
    set_fact:
      parse_json: "{{ dummy_json | from_json }}"
  
  - debug:
      msg: "{{ item.test }}"
    with_items: "{{ parse_json.items }}"
```

##### EXPECTED RESULTS

ok: [localhost] => (item={u'test': u'demo1'}) => {
    "msg": "demo1"
}
ok: [localhost] => (item={u'test': u'demo2'}) => {
    "msg": "demo2"
}

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'test'\n\nThe error appears to have been in '/<dir>/test.yml': line 17, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - debug:\n    ^ here\n"}

```
