### ISSUE TITLE
VMware new module request vmware_guest_video

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#49372]
##### SUMMARY

We want to modify the video related configuration of the VM:
video_card_settings
display_number
video_memory
enable_3d
3d_renderer
3d_memory
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest_video
##### ADDITIONAL INFORMATION

It can be used to re-configure VM to set the video related configurations.

```yaml
- name: Add disks to virtual machine using UUID
  vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    name: test_vm
    video_card:
        video_card_settings: custom
        display_number: 1
        video_memory_mb: 8
        enable_3d: true
        3d_renderer: automatic
        3d_memory_mb: 256
  delegate_to: localhost
  register: video_card

```
