### ISSUE TITLE
win_user does not add user to defined group on Windows Server 2019

### ISSUE THREAD

**Issue by gstorme** [ansible/ansible#49375]
##### SUMMARY

Using the win_user module, a new user is not added to the defined group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_user

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### OS / ENVIRONMENT

Microsoft Windows Server 2019 Standard

##### STEPS TO REPRODUCE

Add a new user, and add it to an existing group.

```yaml
- name: Create user
  win_user:
    name: test
    state: present
    groups_action: add
    password_expired: no
    password: "ABCdef?1357"
    groups: Administrators
    password_never_expires: yes
    user_cannot_change_password: yes
```

##### EXPECTED RESULTS

The new user is created, and added to the Administrators group

##### ACTUAL RESULTS

The new user is created, but not added to the defined group

```paste below
TASK [test : Create user] *************************************************
fatal: [L009298]: FAILED! => {"changed": false, "msg": "Exception calling \"Add\" with \"1\" argument(s): \"A member could not be added to or removed from the local group because the member does not exist.\r\n\""}
```
