### ISSUE TITLE
docker_secret logs the value of the secrets in clear text

### ISSUE THREAD

**Issue by jamesdh** [ansible/ansible#49388]
##### SUMMARY
When using `docker_secret` with a loop/dict, it logs the values of the loop in clear text.
 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_secret

##### ANSIBLE VERSION

```
ansible 2.6.4
  config file = /Users/james/Development/cohoot/ops/ansible/ansible.cfg
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Sep 21 2018, 15:36:36) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```
and also...
```
ansible 2.7.3
  config file = /Users/james/Development/cohoot/ops/ansible/ansible.cfg
  configured module search path = ['/Users/james/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.3/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 30 2018, 15:01:36) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/james/Development/ops/ansible/ansible.cfg) = ['/Users/james/Development/ops/ansible/hosts']
DEFAULT_ROLES_PATH(/Users/james/Development/ops/ansible/ansible.cfg) = ['/Users/james/.ansible/roles']
DEFAULT_STDOUT_CALLBACK(/Users/james/Development/ops/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/Users/james/Development/ops/ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/james/.ansible/.vault_pass.txt
HOST_KEY_CHECKING(/Users/james/Development/ops/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
OSX 10.14

##### STEPS TO REPRODUCE
We define our secrets in a group var dictionary, a la: 

```yaml
swarm_secrets:
  linkedin_client_secret: !vault | ...
  django_secret_key: !vault | ...
  ssl_key: "{{ lookup('file', 'star.domain.com.key') }}" 
```

We then have a task which installs the secrets for a given group, looping over each: 

```yaml
- name: Install Swarm Secrets
  docker_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  loop: "{{ swarm_secrets|dict2items }}"
```

Unfortunately, docker_secret outputs each item in the list/dict.

This is dangerous, especially for CI environments where many people have access to job logs but may not have access to the encrypted secrets. 

##### EXPECTED RESULTS
That the encrypted values/files are not exposed in clear text. 

##### ACTUAL RESULTS
Encrypted values are shown in clear text in their decrypted form. 

```
TASK [webapp : Install Swarm Secrets] *************************************************************************************************************************************************
changed: [54.87.205.217] => (item={'key': u'ssl_key', 'value': u'-----BEGIN PRIVATE KEY-----\n...
...
```
