### ISSUE TITLE
 na_ontap_user_role: cannot specify a query

### ISSUE THREAD

**Issue by angystardust** [ansible/ansible#49403]
##### SUMMARY

Actually it is possible to use **na_ontap_user_role** module to create a tailored role using the parameter `command_directory_name` but you cannot specify a query to limit the allowed commands on a specify subset of storage objects (volumes or luns). So, I think the module should be able to let a user set a `query` parameter

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
 na_ontap_user_role

##### ADDITIONAL INFORMATION
As example of what a playbook could be:

```yaml
- name: Create User Role
  na_ontap_user_role:
    state: present
    name: ansibleRole
    command_directory_name: "volume snapshot create"
    query: mycust*vol
    access_level: all
    vserver: ansibleVServer
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
```
