### ISSUE TITLE
azure_rm_subnet fails when existing subnet had route_table

### ISSUE THREAD

**Issue by yfried** [ansible/ansible#49419]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* azure_rm_subnet
##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = None
  configured module search path = [u'$HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible
  executable location = $HOME/.virtualenvs/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Try to execute the module against an existing subnet with route_table defined

```yaml
      - azure_rm_subnet:
          name: "{{ network.subnet }}"
          virtual_network_name: "{{ network.vnet }}"
          resource_group: "{{ network.group }}"
          address_prefix_cidr: "{{ network.cidr }}"
# make sure subnet exists and has a routing table defined

```

##### EXPECTED RESULTS

Subnet should not be created. `changed` value depends on whether defined `route_table` matches the existing route_table (probably should modify existing route_table if not.)

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "No handlers could be found for logger \"keyring.backend\"\nTraceback (most recent call last):\n  File \"/home/yfried/.ansible/tmp/ansible-tmp-1543756742.69-22661400925495/AnsiballZ_azure_rm_subnet.py\", line 261, in <module>\n    _ansiballz_main()\n  File \"/home/yfried/.ansible/tmp/ansible-tmp-1543756742.69-22661400925495/AnsiballZ_azure_rm_subnet.py\", line 251, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/yfried/.ansible/tmp/ansible-tmp-1543756742.69-22661400925495/AnsiballZ_azure_rm_subnet.py\", line 119, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 348, in <module>\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 344, in main\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 208, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/ansible_azure_rm_subnet_payload.zip/ansible/module_utils/azure_rm_common.py\", line 308, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_aYNzSG/__main__.py\", line 259, in exec_module\nUnboundLocalError: local variable 'route_table' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

```
