### ISSUE TITLE
tower_credentials idempotency issue

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible#49437]
##### SUMMARY

tower_credential is not idempotent when using scm+ssh (have not tried other forms)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_credential

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

```

##### OS / ENVIRONMENT

RHEL 7
python2-ansible-tower-cli-3.3.0-2.el7.noarch

##### STEPS TO REPRODUCE

```yaml
- name: Create SCM credentials
  tower_credential:
    state: present
    name: scm-test-ssh-access
    kind: scm
    organization: "testOrg"
    ssh_key_data: "{{ role_path }}/files/towerscm"
    #for latest
    #ssh_key_data: "{{ lookup('file', 'towerscm') }}"
    user: admin
```

##### EXPECTED RESULTS

First run: changed, second run no changes

##### ACTUAL RESULTS

```paste below
TASK [ansible-role-tower_configure : Create SCM credentials] ************************************************************************
changed: [localhost]
[....] next run [...]
TASK [ansible-role-tower_configure : Create SCM credentials] ************************************************************************
changed: [localhost]
[...]
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Klaas-** [comment]
@ansibot !component tower_credential

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AlanCoding @ghjm @jlaska @matburt @rooftopcellist @ryanpetrello @simfarm @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shaps** [comment]
@Klaas- I got 'hit' by this as well, although I don't really see a quick fix for it since the module dependence on tower_cli makes it quite complicated to fix. 
As far as I understand it, this happens because of the `force_on_existing` being hardcoded to `True` in the `modify` call here - https://github.com/ansible/tower-cli/blob/master/tower_cli/models/base.py#L713

**Comment by juanvalino** [comment]
I have the same problem.

**Comment by AlanCoding** [comment]
Is this the same as https://github.com/ansible/ansible/issues/36990, given that the SSH key data of an existing credential is unknowable?

**Comment by Klaas-** [comment]
@AlanCoding is there a best practice on how to deal with this. I would like to use the same playbook for an initial configuration and any subsequent changes made to tower/awx.

Would I do something like:
```
- tower_credential:
    state: present
    name: scm-test-ssh-access
    kind: scm
    organization: "testOrg"
    user: admin
  register: tower_admin

- tower_credential:
    state: present
    name: scm-test-ssh-access
    kind: scm
    organization: "testOrg"
    user: admin
    ssh_key_data: "{{ role_path }}/files/towerscm"
    #for latest
    #ssh_key_data: "{{ lookup('file', 'towerscm') }}"
  when: tower_admin.changed
```

or does anyone else have a better idea how to deal with this? :)
