### ISSUE TITLE
aws_config_recorder module always reports changed if resource_types list is not specified

### ISSUE THREAD

**Issue by ichekaldin** [ansible/ansible#49453]
##### SUMMARY

aws_config_recorder module will report as Changed if resource_types list attribute is not specified.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aws_config_recorder module

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Create an AWS Config configuration recorder as follows:

```yaml
- aws_config_recorder:
    name: DefaultConfigRecorder
    role_arn: arn:aws:iam::123412341234:role/ConfigRole
    recording_group:
      all_supported: true
      include_global_types: true
    state: present
```

##### EXPECTED RESULTS

Ansible to report `Changed = true` after the first execution (i.e. the initial configuration), and `Changed = false` after all subsequent executions (i.e. no further changes applied).

##### ACTUAL RESULTS

Ansible reports `Changed = true` every time the task is executed.
