### ISSUE TITLE
route53_facts improvements - allow zone instead of hosted_zone_id

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#49452]
##### SUMMARY
the route53_facts module has several small improvements to make it much more user friendly

1. `hosted_zone_id` is not human friendly and we should provide an alternative similar to the `route53` module where we can just use `zone`

The only way to automate this currently is to use the routet53_zone module and register the output and grab the zone_id (which is return value from that module).

2. some sort of filter, i have 700+ record entries in my DNS zone.  The closest thing I can find is the `start_record_name` but it would be ideal to apply a regex or anything to filter something like "anything containing this phrase"

3. if you set the `type` e.g. `type: A` it errors out unless you use the `start_record_name`

```
    "msg": "start_record_name must be specified if type is set"
```

I am not sure why?  I can't just filter on all records for this particular zone, for type A?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
route53_facts
https://docs.ansible.com/ansible/latest/modules/route53_facts_module.html

##### ADDITIONAL INFORMATION
Playing around with a Playbook here for the Ansible Workshops (ansible.com/workshops)

```yaml
- name: GRAB ZONE ID
  route53_zone:
    zone: "{{workshop_dns_zone}}"
  register: AWSINFO

- name: GRAB ROUTE53 INFORMATION
  route53_facts:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    # start_record_name: "student1.{{ec2_name_prefix|lower}}"
    max_items: 200
  register: record_sets

- name: PRINT OUT RECORD SETS
  debug:
    var: record_sets
```
