### ISSUE TITLE
`os_router` is not idempotent when server is attached

### ISSUE THREAD

**Issue by nicolasbock** [ansible/ansible#49451]
##### SUMMARY

The `os_router` module is not idempotent when an interface is attached to a server. The module tries to indiscriminately detach _all_ interfaces in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_router.py#L454 which fails in this case.

An example error message:

```
Error detaching interface from router 639a2c34-a897-42cb-b2bc-e23bee4456c4: Client Error for url: https://engcloud.prv.suse.net:9696/v2.0/routers/639a2c34-a897-42cb-b2bc-e23bee4456c4/remove_router_interface.json, {"NeutronError": {"message": "Router interface for subnet f436c5f5-1abe-4018-a52f-51a731e3a108 on router 639a2c34-a897-42cb-b2bc-e23bee4456c4 cannot be deleted, as it is required by one or more floating IPs.", "type": "RouterInterfaceInUseByFloatingIP", "detail": ""}}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`os_router`

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/openstack/os_router.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_router.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nicolasbock: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @evrardjp @juliakreger @mnaser @odyssey4me @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mnaser** [comment]
Hi @nicolasbock 

Can you please share the exact bit that you're trying to run which is causing that issue?

Thanks,
Mohammed

**Comment by pfisterer** [comment]
I have a similar issue (using ansible 2.7.0). 

- First run: It creates the router, everything is fine.
- All consecutive runs:  I get the following error: `Error detaching interface from router 57581af4-12db-4c8c-98dd-2ea55354770d: Client Error for url: http://controller.4c.dhbw-mannheim.de:9696/v2.0/routers/57581af4-12db-4c8c-98dd-2ea55354770d/remove_router_interface.json, {"NeutronError": {"message": "Router interface for subnet 4e535f60-26a6-4a08-8747-862b1a1f0dfe on router 57581af4-12db-4c8c-98dd-2ea55354770d cannot be deleted, as it is required by one or more floating IPs.", "type": "RouterInterfaceInUseByFloatingIP", "detail": ""}}`.

My playbook is as follows:

```yaml
- hosts: localhost
  tasks:
    - name: create network
      os_network:
        name: "{{ network_name }}"

    - name: create subnet
      os_subnet:
        network_name: "{{ network_name }}"
        name: "{{ subnet_name }}"
        cidr: 10.8.10.0/24
      register: subnet

    - name: create router
      os_router:
        name: "{{ router_name }}"
        network: "{{ external_network_name }}"
        interfaces:
          - "{{ subnet_name }}"
      register: router
      
    - name: Set variables
      set_fact:
        state: present
        routeruuid: "{{ router.id }}"
        subnetuuid: "{{ subnet.id }}"

    - name: Create OpenStack instance
      os_server:
        security_groups: "{{security_group}}"
        name: "{{ nodes_name }}{{ item }}"
        image: "{{ nodes_image }}"
        key_name: "{{ key_name }}"
        flavor_ram: "{{ nodes_flavor_ram if not nodes_flavor_name else omit }}"
        flavor: "{{ nodes_flavor_name if nodes_flavor_name else omit }}"
        nics:
          - net-name: "{{ network_name }}"
        floating_ip_pools: "{{ floating_ip_pools }}"
        userdata: |
          #cloud-config
          package_upgrade: true
          hostname: "{{ nodes_name }}{{ item }}"
          manage_etc_hosts: false
          packages:
            - python
            - python-simplejson
      when: state == "present"
      register: "instances"
      with_sequence: count={{ nodes_count }}
```

**Comment by pfisterer** [comment]
This resolved my issue: https://github.com/ansible/ansible/issues/29903. I modified `create router` to include ` enable_snat: yes`:

```yaml
    - name: create router
      os_router:
        name: "{{ router_name }}"
        network: "{{ external_network_name }}"
        interfaces:
          - "{{ subnet_name }}"
        enable_snat: yes # cf. https://github.com/ansible/ansible/issues/29903
      register: router
```
