### ISSUE TITLE
password/pass no_log

### ISSUE THREAD

**Issue by NikolayDachev** [ansible/ansible#49465]
##### SUMMARY
I'm working on custom module for ansible, in this module we have several vars which are include *password* key word. For all those var I get warring for no_log usage however they no need no_log to be set to true. Same is If I change it form *password* to *pass*

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module no_log

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
HOST_KEY_CHECKING(/root/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Linux **** 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
```yaml

  tasks:
    - name: vCenter localos users
      vmware_vcenter_localos_users:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs:   '{{ valid_cert }}'
        localos_username: '{{ item.value.username }}'
        localos_password: '{{ item.value.password }}'
        localos_state:    '{{ item.value.state }}'
        localos_role:     '{{ item.value.role }}'
        localos_fullname:     '{{ item.value.fullname }}'
        localos_email:  '{{ item.value.email }}'
        localos_warn_days_before_password_expiration: '{{ item.value.warn_days_before_password_expiration }}'
      loop: "{{ localos_users|dict2items }}"


```

```
def main():
    argument_spec = VmwareRestClient.vmware_client_argument_spec()
    argument_spec.update(localos_username=dict(type='str', required=True),
                         localos_password=dict(type='str', required=True, no_log=True),
                         localos_state=dict(type='str', choices=['present', 'absent'], default='present', required=False),
                         localos_role=dict(type='list', required=False),
                         localos_email=dict(type='str', required=False, default=None),
                         localos_fullname=dict(type='str', required=False, default=None),
                         localos_enabled=dict(type='bool', required=False, default=True),
                         localos_password_expires=dict(type='bool', required=False, default=False),
                         localos_password_expires_at=dict(type='str', required=False, default=None),
                         localos_inactive_after_password_expiration=dict(type='bool', required=False, default=False),
                         localos_days_after_password_expiration=dict(type='int', required=False, default=None),
                         localos_min_days_between_password_change=dict(type='int', required=False, default=None),
                         localos_max_days_between_password_change=dict(type='int', required=False, default=None),
                         localos_warn_days_before_password_expiration=dict(type='int', required=False, default=None))

    module = AnsibleModule(argument_spec=argument_spec, supports_check_mode=True)

```

##### EXPECTED RESULTS
We should not see no_log warnings for different vars which are include *password* or *pass* in name (we don't need to specify no_log=True for example:  **localos_min_days_between_password_change**) etc.

##### ACTUAL RESULTS

```
localos_password is set with no_log=True which is ok but still we get warnings for all other vars.

 [WARNING]: Module did not set no_log for localos_min_days_between_password_change

 [WARNING]: Module did not set no_log for localos_password_expires_at

 [WARNING]: Module did not set no_log for localos_warn_days_before_password_expiration

 [WARNING]: Module did not set no_log for localos_max_days_between_password_change

 [WARNING]: Module did not set no_log for localos_days_after_password_expiration


```
