### ISSUE TITLE
Intersection in patterns seems doesn't work well

### ISSUE THREAD

**Issue by Kamapcuc** [ansible/ansible#49478]
### ISSUE TYPE
 - Bug Report

### COMPONENT NAME
Patterns

### ANSIBLE VERSION
2.5.1

### STEPS TO REPRODUCE
My `inventory.yml` looks like:
```yaml
all:
  children:
    pre:
      children:
        account:
          hosts:
            server1:
            server2:
        game:
          hosts:
            server3:
            server4:
    prod:
      children:
        account:
          hosts:
            server5:
            server6:
        game:
          hosts:
            server7:
            server8:
```
#I have three playbooks:
`playbook.yml`
```yaml
- name: Update {{ env }} account servers
  hosts: "{{ env }}:&account"
  tasks:
  - name: Debug msg
    debug:
      msg: "Updating account server: {{ inventory_hostname }}"
#....................................... etc
```
`pre.yml` (And the same `prod.yml`)
```yaml
- name: Start pre playbook
  import_playbook: playbook.yml
  vars:
    env: pre
```

So, when i run my pre playbook, i expect to see:
```
PLAY [Register pre account servers] ************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [server1]
ok: [server2]

etc...
```

But actual results is:
```
PLAY [Register pre account servers] ************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [server1]
ok: [server2]
ok: [server5]
ok: [server6]

etc...
```

**Comment by Kamapcuc** [comment]
if i change `hosts: "{{ env }}:&account"` to `hosts: "{{ env }}"` it will select [1:6] servers. o.O

**Comment by sivel** [comment]
You have made an assumption about how groups are created based on the structure of the YAML in your inventory.

groups are top level, however they can specify relationships, like you have with children.

However, you have specified the group `account` under both `prod` and `pre`.  This leads to a concatenation, that will lead to the group `account` containing all hosts listed under that group.

There is no hierarchy of groups, so although you thought you were creating a group in a namespace like `pre.accounts` or `prod.accounts`, you are just creating 4 top level groups called `pre`, `prod`, `account`, and `game`. Additionally this causes all hosts to be part of `pre` and `prod`.

You will need to devise a different way of structuring your inventory to meet your needs.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Kamapcuc** [comment]
Yes, i understand that. The bug is how you parse those groups. If `pre` group contains `1,2,3,4` servers, and `account` contains `1,2,5,6` so the intersection is `1,2`. But, that's doesn't work! How servers from `prod` can be in `pre` group?!? That's totally insane and not transparent for the user. Read the topic one more time, please.

**Comment by bcoca** [comment]
The problem is not the intersection pattern, that is working fine, it is your assumption on how membership works:

This is how membership is assigned:
```
account: server1, server2, server5, server6
game: server3, server4, server7, server8

pre: account + game
prod: account + game
```
`pre` contains all servers, because `pre` contains `account` and `game`, so the intersection off `pre` and `account` is the same as `account`, since it is a subset of `pre`.

**Comment by Kamapcuc** [comment]
```
pre: account + game
prod: account + game
```
OMG o.O

**Comment by Kamapcuc** [comment]
P.S. thanks for reply

**Comment by bcoca** [comment]
@Kamapcuc I understand that the YAML hierarchy might be misleading in this case, I'm unsure how better to document this to prevent this kind of misunderstanding.

**Comment by Kamapcuc** [comment]
If someone find those topic in google, how i fix it:
```yaml
    pre:
      children:
        pre-account:
    prod:
      children:
        prod-account:
```

```yaml
- name: Update {{ env | upper }} account servers
  hosts: "{{ env }}:&{{ env }}-account"
```
