### ISSUE TITLE
Iam module should include codecommit credentials management 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#49471]
##### SUMMARY

- iam module should manage codecommit credentials creations/deletion , both ssh and https.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

iam

##### ADDITIONAL INFORMATION

The feature is needed to 
- automate credential creations/deletion for users: until now we can create aws secret key and access key but not ssh / https credentials for AWS Codecommit interactions.

```yaml

iam:
  iam_type: user
  name: "new-user"
  state: present
  codecommit_access_key_state : create
    ssh: true
    https: true
```
