### ISSUE TITLE
win_uri: fails to send json with just one item

### ISSUE THREAD

**Issue by ilpianista** [ansible/ansible#49483]
##### SUMMARY
`win_uri` fails to send a JSON with just one item into it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_uri

##### ANSIBLE VERSION
```
2.7.4
```

##### OS / ENVIRONMENT
Windows 2012 R2

##### STEPS TO REPRODUCE
```yaml
  win_uri:
    url: https://{{httpbin_host}}/post
    method: POST
    body: "[{{ lookup('file', 'item.json') }}]"
    headers:
      'Content-Type': 'text/json'
```

```
$ cat item.json
{
  "foo": "bar"
}
```

##### EXPECTED RESULTS
Request's content should be `{ "foo": "bar" }`

##### ACTUAL RESULTS
Request's content is `System.Object[]`.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_uri.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_uri.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
I can reproduce this on devel branch using this minimal reproducer:
```yaml
  - win_uri:
      url: https://httpbin.org/post
      method: POST
      body:
      - foo: bar
      headers:
        Content-Type: text/json
```
