### ISSUE TITLE
elasticache_facts does not pull configuration endpoint

### ISSUE THREAD

**Issue by irpaglide** [ansible/ansible#49544]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
elasticache_facts

##### ANSIBLE VERSION
```paste below
ansible 2.7.0

```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
AWS

##### STEPS TO REPRODUCE

- elasticache_facts:
        name: "{{memcached_cluster_name}}"

```yaml
- hosts: "{{localhost}}"
    gather_facts: no
    tasks:
      - elasticache_facts:
        name: "{{env}}-cache"
```

##### EXPECTED RESULTS
I can get "Configuration endpoint" of the cluster

##### ACTUAL RESULTS
I cannot get "Configuration endpoint" of the cluster
