### ISSUE TITLE
docker_swarm: labels not applied

### ISSUE THREAD

**Issue by ivanmrva** [ansible/ansible#49547]
##### SUMMARY
"labels" parameter of "docker_swarm" module is ignored (resp. labels are not applied on the target node)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_swarm

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  config file = /media/data/projects/alv/workspace/central-deployment/ansible.cfg
  configured module search path = ['/home/ivmr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.6/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.6/ansible
  python version = 3.6.5 (default, Jul  7 2018, 14:08:42) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

gentoo linux, kernel 4.14.52

##### STEPS TO REPRODUCE

Just use docker_swarm module with "state:join" and  "labels" parameter. 
See the full role below (incl. swarm initialization). The rest (besides labels) works just fine.

```yaml
- name: Init a docker swarm
  docker_swarm:
    advertise_addr: "{{ hostvars['docker-swarm-manager']['ansible_default_ipv4']['address'] }}"
    state: present
  when: inventory_hostname == 'docker-swarm-manager'

- name: Get swarm info
  docker_swarm:
    state: inspect
  register: swarm_info
  when: inventory_hostname == 'docker-swarm-manager'

- name: Add data workers to docker swarm
  docker_swarm:
    state: join
    join_token: "{{ hostvars['docker-swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    advertise_addr: "{{ ansible_default_ipv4.address }}"
    remote_addrs: ["{{ hostvars['docker-swarm-manager']['ansible_default_ipv4']['address'] }}"]
    labels:
      type: data
  when: inventory_hostname in groups['docker-swarm-data-workers']
```

##### EXPECTED RESULTS

Labels are applied on the target docker swarm node.

##### ACTUAL RESULTS

The ansible script doesn't produce any error. 
On the other side, no changes are also recognized if I add/remove "labels" parameter on the node that is already attached to an existing docker swarm cluster.

Verification of labels on the target host:
`docker node inspect <host>`
just returns no labels: ` "Labels": {},`

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_swarm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_swarm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akshay196 @danihodovic @dariko @felixfontein @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tbouvet** [comment]
`join` state is only to add a node in a swarm environment.
Labels can be added when you create or update a swarm environment.
```
- name: Update swarm configuration
  docker_swarm:
    state: present
    labels:
      key: value
```
