### ISSUE TITLE
Unexpected difference between YAML block and non block var

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#49579]
##### SUMMARY
YAML strings can be interpreted differently depending upon whether the string is inline or in a block.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/template/vars

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0 (devel 1c3fa2b07f) last updated 2018/12/06 10:08:57 (GMT +1000)
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/will/src/opensource/ansible/lib/ansible
  executable location = /Users/will/src/opensource/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

Issue is present in 2.7 and probably older too.

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local

  tasks:
    - name: set starting lists to empty
      set_fact:
        block: []
        non_block: []

    - set_fact:
        non_block: "{{ non_block + lookup('template', item)| from_yaml_all | list }}"
      loop: "{{ query('fileglob', 'template.yml') }}"

    - set_fact:
        block: >
          {{ block + lookup('template', item)| from_yaml_all | list }}
      loop: "{{ query('fileglob', 'template.yml') }}"

    - debug:
        var: item
      loop: "{{ non_block }}"

    - debug:
        var: item
      loop: "{{ block }}"
```

```yaml
data: '{{ '{{ $labels.host }}' }}'
```

##### EXPECTED RESULTS

Debug output is same for both debug statements

##### ACTUAL RESULTS

```paste below
TASK [set_fact] **************************************************************************************
task path: /Users/will/tmp/ansible/yaml_block_quote/play.yml:10
ok: [localhost] => (item=/Users/will/tmp/ansible/yaml_block_quote/template.yml) => {
    "ansible_facts": {
        "non_block": [
            {
                "data": "{{ $labels.host }}"
            }
        ]
    }, 
    "changed": false, 
    "item": "/Users/will/tmp/ansible/yaml_block_quote/template.yml"
}

TASK [set_fact] **************************************************************************************
task path: /Users/will/tmp/ansible/yaml_block_quote/play.yml:14
ok: [localhost] => (item=/Users/will/tmp/ansible/yaml_block_quote/template.yml) => {
    "ansible_facts": {
        "block": [
            {
                "data": "{{ $labels.host }}"
            }
        ]
    }, 
    "changed": false, 
    "item": "/Users/will/tmp/ansible/yaml_block_quote/template.yml"
}

TASK [debug] *****************************************************************************************
task path: /Users/will/tmp/ansible/yaml_block_quote/play.yml:19
ok: [localhost] => (item={'data': u'{{ $labels.host }}'}) => {
    "item": {
        "data": "{{ $labels.host }}"
    }
}

TASK [debug] *****************************************************************************************
task path: /Users/will/tmp/ansible/yaml_block_quote/play.yml:23
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '[{'data': u'{{ $labels.host }}'}]'. Error was a <class 'ansible.errors.AnsibleError'>, original message: template error while templating string: unexpected char u'$' at 3. String: {{ $labels.host }}"
}
```
The problem is the apparent double templating of the `block` variable, whereas the `non_block` variable doesn't get double templated, even though at first appearance the two are identical.

Using an adjusted set_fact that shows the data types of variables, the key difference is:

```
TASK [set_fact] *********************************************************************************************
task path: /Users/will/tmp/ansible/yaml_block_quote/play.yml:10
ok: [localhost] => (item=/Users/will/tmp/ansible/yaml_block_quote/template.yml) => {
    "ansible_facts": {
        "non_block": [
            {
                "data": "{{ $labels.host }}"
            }
        ], 
        "non_block_type": {
            "list": {
                "dict": {
                    "data": "AnsibleUnsafeText"
                }
            }
        }
    }, 
    "changed": false, 
    "item": "/Users/will/tmp/ansible/yaml_block_quote/template.yml"
}

TASK [set_fact] *********************************************************************************************
task path: /Users/will/tmp/ansible/yaml_block_quote/play.yml:14
ok: [localhost] => (item=/Users/will/tmp/ansible/yaml_block_quote/template.yml) => {
    "ansible_facts": {
        "block": [
            {
                "data": "{{ $labels.host }}"
            }
        ], 
        "block_type": {
            "list": {
                "dict": {
                    "data": "str"
                }
            }
        }
    }, 
    "changed": false, 
    "item": "/Users/will/tmp/ansible/yaml_block_quote/template.yml"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/template/vars.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/template/vars.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The problem here is that using folded scalar style in YAML `>` produces an implicit newline at the end of the value (https://yaml.org/spec/1.1/#id929764).

When a `lookup` is executed, it returns values as `AnsibleUnsafeText`, and later we don't template things that are unsafe.

When using `>` the newline that gets added to the end causing the value to no longer be marked as unsafe.

```
>>> foo = wrap_var('foo')
>>> type(foo)
ansible.utils.unsafe_proxy.AnsibleUnsafeText
>>> foo2 = foo + '\n'
>>> type(foo2)
str
```

Due to this, we will try to template the contents of the `block`.

To get the desired outcome, you need to instruct YAML to not include the trailing newline:

```
    - set_fact:
        block: >-
          {{ block + lookup('template', item)| from_yaml_all | list }}
      loop: "{{ query('fileglob', 'template.yml') }}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
