### ISSUE TITLE
Improve import_* performance

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#49599]
##### SUMMARY
Currently, import_tasks/import_role optimizes importing of tasks/roles over the include_* variant by being dumb (i.e. evaluating once at parse time). With a different implementation, it could significantly improve run time behaviour.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION
In Python, the `import` statement is a no-op (or as close as can be) when the module to be imported already has been imported. A similar behaviour would allow writing much more efficient re-usable roles.

Consider the following role:
```yaml
# tasks/main.yml
---
- import_tasks: packages.yml
- include_tasks: config.yml
```

```yaml
# tasks/packages.yml
---
# Install packages, e.g.
- apt: ...
```

```yaml
# tasks/config.yml
---
# Write configuration specific to the configuration of the role.
- template:
   src: foo.j2
   dest: /etc/<something>.d/{{ myrole.myconfig.name }}.conf
```

Re-usable roles should include all packages that need installing to make them work, otherwise it's too easy to miss something and have dependencies not satisfied.

On the other hand, when including a role multiple times, running tasks again that successfully completed before, with no expected change in result, is a waste of time.

If imported tasks or roles were cached, i.e. skipped automatically encountered for a second time, this would allow efficient splitting of tasks in a role as described in the example above.

The simplest implementation would likely be to remember fully qualified names or imported files, and skip importing when the file name is already in memory.

A better implementation might warn the user - there is a potential issue here when the imported file uses any variables or facts that can have changed. Once could parse the file for variable use and warn the user if any are found. Ansible pre-defined facts might be excluded from this.

An even better implementation could remember the value of the variables used when the file was imported first, and compare the values in order to evaluate whether to re-run the tasks - but that sort of defies the purpose of import as a one-off statement.

IMHO the simplest implementation would also work as an additional command, e.g. `once_tasks` in order to disambiguate the behaviour. In that case, the improved implementations are likely superfluous and too complex.
