### ISSUE TITLE
get_url using the content-disposition mechanism wget is using to find out the filename to download

### ISSUE THREAD

**Issue by tappoz** [ansible/ansible#49603]
##### SUMMARY

Being able to use `get_url` when the server redirects the download, miming what this command does: `wget --content-disposition URL`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`get_url`

##### ADDITIONAL INFORMATION

I am trying to automate the installation of common tools on my laptop e.g. Postman to perform manual HTTP requests and debug REST APIs.

From their documentation here https://www.getpostman.com/download?platform=linux64 they say we have to download an archive. I found out the static URL is this https://dl.pstmn.io/download/latest/linux64 however I need to use the "Content-Disposition" header to make `wget` figure out the filename like this:

```sh
wget --content-disposition https://dl.pstmn.io/download/latest/linux64
```
which (at the moment) then gives this file name as stored in the file system `Postman-linux-x64-6.5.3.tar.gz`, I guess the semantic versioning may vary in the future.

At the moment I am using Ansible providing myself an hard-coded filename to download the file - check the code below where I use `XXX` instead of the semantic version (which I don't know when downloading). It would be nice to get the file name "for free" in a similar way `wget` does.

```yaml
  - name: Download the file
    get_url:
      url: https://dl.pstmn.io/download/latest/linux64
      dest: /home/{{ cli_input_username }}/src/Postman-linux-x64-XXX.tar.gz
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py)
* [lib/ansible/modules/net_tools/basics/get_url.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [lib/ansible/plugins/shell/sh.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/shell/sh.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ptux** [comment]
@tappoz 

Is the following you want to do?

```
    - name:  Download the file
      get_url:
        url: https://dl.pstmn.io/download/latest/linux64
        dest: "/tmp"
```
You will get the latest file just like wget.
