### ISSUE TITLE
azure_rm_virtualmachine data_disks not idempotent

### ISSUE THREAD

**Issue by BradFelmey** [ansible/ansible#49659]
##### SUMMARY

Trying to add data_disks to an existing Azure virtual machine definition does not result in additional data_disks being provisioned.
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/custom_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 3
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_roles', u'profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/custom_modules']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 20
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.6 (Maipo)

##### STEPS TO REPRODUCE

Create an Azure Virtual Machine with data_disks
Change the data_disks argument to add more LUNs
Re-run the code against the Azure virtual machine. Observe that the data_disks are not changed, even though the module_args clearly shows the new disk[s].

```yaml
- name: "Manage Azure Virtual Machine"
  connection: local
  azure_rm_virtualmachine:
    accept_terms: yes
    admin_username: some_user
    admin_password: "{{ some_pass }}"
    resource_group: "{{ resourcegroup }}"
    name: "{{ inventory_hostname }}"
    vm_size: Standard_E8s_v3
    state: present
    managed_disk_type: Premium_LRS
    public_ip_allocation_method: Disabled
    subnet_name: "{{ subnet }}"
    os_disk_size_gb: 300
    data_disks:
      ### First two LUNs originally defined ###
      - lun: 2
        disk_size_gb: 512
        managed_disk_type: Premium_LRS
      - lun: 3
        disk_size_gb: 512
        managed_disk_type: Premium_LRS
      ### LUN below added to existing code ###
      - lun: 4
        disk_size_gb: 512
        managed_disk_type: Premium_LRS
    image:
      offer: "RHEL"
      publisher: "RedHat"
      sku: "7-LVM"
      version: latest
```

##### EXPECTED RESULTS

Expected that the additional LUNs would be provisioned and available to the pre-existing virtual machine.

##### ACTUAL RESULTS

The task completed with no changes. The module_args clearly show the additional LUN definition.

```paste below
ok: [some_hostname] => changed=false 
  ansible_facts:
    azure_vm:
      id: <redacted>
      location: southcentralus
      name: some_hostname
      powerstate: running
      properties:
        hardwareProfile:
          vmSize: Standard_E8s_v3
        instanceView:
          disks:
          - name: some_hostname
            statuses:
            - code: ProvisioningState/succeeded
              displayStatus: Provisioning succeeded
              level: Info
              time: '2018-12-04T23:33:51.550017Z'
          - name: some_hostname-datadisk-0
            statuses:
            - code: ProvisioningState/succeeded
              displayStatus: Provisioning succeeded
              level: Info
              time: '2018-12-04T23:33:51.550017Z'
          - name: some_hostname-datadisk-1
            statuses:
            - code: ProvisioningState/succeeded
              displayStatus: Provisioning succeeded
              level: Info
              time: '2018-12-04T23:33:51.550017Z'
          statuses:
          - code: ProvisioningState/succeeded
            displayStatus: Provisioning succeeded
            level: Info
            time: '2018-12-04T23:35:06.864847Z'
          - code: PowerState/running
            displayStatus: VM running
            level: Info
          vmAgent:
            extensionHandlers: []
            statuses:
            - code: ProvisioningState/succeeded
              displayStatus: Ready
              level: Info
              message: Guest Agent is running
              time: '2018-12-07T16:32:07.000Z'
            vmAgentVersion: 2.2.34
        networkProfile:
          <redacted>
        osProfile:
          adminUsername: some_user
          computerName: some_hostname
        provisioningState: Succeeded
        storageProfile:
          dataDisks:
          - caching: ReadOnly
            createOption: empty
            diskSizeGB: 512
            lun: 2
            managedDisk: <redacted>
              storageAccountType: Premium_LRS
            name: some_host-datadisk-0
          - caching: ReadOnly
            createOption: empty
            diskSizeGB: 512
            lun: 3
            managedDisk: <redacted>
              storageAccountType: Premium_LRS
            name: some_host-datadisk-1
          imageReference:
            offer: RHEL
            publisher: RedHat
            sku: 7-LVM
            version: 7.6.2018103108
          osDisk:
            caching: ReadOnly
            createOption: fromImage
            diskSizeGB: 300
            managedDisk: <redacted>
              storageAccountType: Premium_LRS
            name: some_host
            osType: Linux
        vmId: <redacted>
      type: Microsoft.Compute/virtualMachines
  invocation:
    module_args:
      accept_terms: false
      ad_user: null
      adfs_authority_url: null
      admin_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      admin_username: some_user
      allocated: true
      api_profile: latest
      append_tags: true
      auth_source: null
      availability_set: null
      cert_validation_mode: null
      client_id: null
      cloud_environment: AzureCloud
      custom_data: null
      data_disks:
      - disk_size_gb: 512
        lun: 2
        managed_disk_type: Premium_LRS
      - disk_size_gb: 512
        lun: 3
        managed_disk_type: Premium_LRS
      - disk_size_gb: 512
        lun: 4
        managed_disk_type: Premium_LRS
      image:
        offer: RHEL
        publisher: RedHat
        sku: 7-LVM
        version: 7.6.2018103108
      location: null
      managed_disk_type: Premium_LRS
      name: some_host
      network_interface_names: null
      open_ports: <redacted>
      os_disk_caching: ReadOnly
      os_disk_size_gb: 300
      os_type: Linux
      password: null
      plan: null
      profile: null
      public_ip_allocation_method: Disabled
      remove_on_absent:
      - all
      resource_group: some_resourcegroup
      restarted: false
      secret: null
      short_hostname: some_hostname
      started: true
      state: present
      storage_account_name: null
      storage_blob_name: null
      storage_container_name: vhds
      subnet_name: some_subnetname
      subscription_id: null
      tenant: null
      virtual_network_name: null
      virtual_network_resource_group: null
      vm_size: Standard_E8s_v3
  powerstate_change: null
```
