### ISSUE TITLE
s3 module - This module has been removed ansible 2.7.4

### ISSUE THREAD

**Issue by DeanKamali** [ansible/ansible#49686]
##### SUMMARY
Unable to use S3 module with ansible 2.7.4

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_s3 - alias s3 

##### ANSIBLE VERSION
```
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
- name: Simple PUT operation
  s3:
    aws_access_key: '16BXBPRD7ENM2D8WA4UD'
    aws_secret_key: 'c7RA+x+JMepINY5YHRddQAjV0dSQzqRZn9czZHZI'
    bucket: backups
    ec2_url: http://backup-store.my-compatible-s3-storage-minio.local:9000
    object: "{{server}}_full_db_backup.gz"
    src: "/var/lib/jenkins/data/{{server}}_full_db_backup.gz"
    mode: put

```

##### OS / ENVIRONMENT
CentOS 7

##### Error I'm getting 
```
TASK [roles/mongodb : Simple PUT operation] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "This module has been removed.  The module documentation for Ansible-2.6 may contain hints for porting"}
	to retry, use: --limit @/var/lib/jenkins/workspace/admin_utils/mongodb_backup/mongo-backup.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```
