### ISSUE TITLE
URI module LIST method

### ISSUE THREAD

**Issue by yura-shutkin** [ansible/ansible#49716]
##### SUMMARY

Please add LIST method to URI module.
https://www.vaultproject.io/api/auth/userpass/index.html List users need LIST method. Right now I need to create task that differs from others. I use curl with different set of args and output

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

uri

##### ADDITIONAL INFORMATION

I use ansible for managing hashicorp vault configs. I need LIST method for get list of available users and for some other API queries to Hashicorp Vault

```yaml
---
# Delete orphan userpass users
- name: Compile list described userpass users
  set_fact:
    described_userpass_users: "{{ described_userpass_users }} + [ '{{ item.params.login }}' ]"
  with_items: "{{ vault_config_applicator_userpass_users }}"
  loop_control:
    label: "{{ item.params.login }}"

# Better choice is to get list of all known userpass auth backends and delete every unknown user
# ansible module uri have no method LIST
- name: Get list existed users
  uri:
    url: "{{ vault_config_applicator_url }}/v1/auth/userpass/users"
    method: LIST
    user: "{{ vault_config_applicator_basic_auth_user }}"
    password: "{{ vault_config_applicator_basic_auth_pass }}"
    validate_certs: "{{ vault_config_applicator_validate_certs }}"
    headers:
      X-Vault-Token: "{{ vault_config_applicator_creds.token }}"
    follow_redirects: safe
    return_content: false
    status_code: 200
    timeout: "{{ vault_config_applicator_query_timeout }}"
  register:
    userpass_users_response

- name: Set list existed userspass users
  set_fact:
    existed_userpass_users: "{{ existed_userpass_users }} + [ '{{ item | regex_replace('/$', '') }}' ]"
  with_items:
    - "{{ userpass_users_response.json.data.keys() }}"

- name: Set orphan userpass users list
  set_fact:
    userpass_orphans: "{{ existed_userpass_users | difference(described_userpass_users) }}"

- name: Delete userpass orphans
  uri:
    url: "{{ vault_config_applicator_url }}/v1/auth/userpass/users/{{ userpass_orphan }}"
    method: DELETE
    user: "{{ vault_config_applicator_basic_auth_user }}"
    password: "{{ vault_config_applicator_basic_auth_pass }}"
    validate_certs: "{{ vault_config_applicator_validate_certs }}"
    headers:
      X-Vault-Token: "{{ vault_config_applicator_creds.token }}"
    follow_redirects: safe
    return_content: false
    status_code: 204
    timeout: "{{ vault_config_applicator_query_timeout }}"
  with_items:
    - "{{ userpass_orphans }}"
  loop_control:
    loop_var: userpass_orphan

```

Sorry, I can't give you access to config applicator repo or write more code cause NDA
But I'll be glad to answer your questions
