### ISSUE TITLE
ACI: aci_bd_subnet, error for state:query

### ISSUE THREAD

**Issue by somebody78** [ansible/ansible#49769]
##### SUMMARY

When using aci_bd_subnet state:query to get a list of subnets you have to limit the scope to either public or private. You cannot get a complete list with all subnets in one pull.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aci_bd_subnet

##### ANSIBLE VERSION

```paste below
ansible 2.6.1
  config file = None
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/ansible/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
  #
  # list of BD subnets
  #
  - name: Get a list of BD subnets from ACI
    aci_bd_subnet:
      state=query
      hostname="{{ inventory_hostname }}"
      username="{{ apic_user }}"
      password="{{ apic_pass }}"
      use_proxy=no
      validate_certs=no
    # no_log: true
    register: out
```

##### EXPECTED RESULTS

Complete list of subnets configured in ACI

##### ACTUAL RESULTS

...
line 358, in main\n    if 'private' in scope and 'public' in scope:\nTypeError: argument of type 'NoneType' is not iterable
...

```paste below

```
