### ISSUE TITLE
lineinfile with template does not check output in file

### ISSUE THREAD

**Issue by kborup-redhat** [ansible/ansible#49764]
##### SUMMARY
when defining a lineinfile with template, then lineinfile does not check destination to see if lines are already present in file. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```
ansible 2.6.8

  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```
DEFAULT_BECOME(/opt/customer/playbooks/cloudforms/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/opt/customer/playbooks/cloudforms/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/opt/customer/playbooks/cloudforms/ansible.cfg) = root
DEFAULT_FORKS(/opt/customer/playbooks/cloudforms/ansible.cfg) = 5
DEFAULT_PRIVATE_KEY_FILE(/opt/customer/playbooks/cloudforms/ansible.cfg) = /root/.ssh/ocpinstall
DEFAULT_REMOTE_USER(/opt/customer/playbooks/cloudforms/ansible.cfg) = ocpadmin
DEFAULT_ROLES_PATH(/opt/customer/playbooks/cloudforms/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/opt/customer/playbooks/cloudforms/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```yaml
- hosts: 127.0.0.1
  tasks:

   - name: Add project definitions to file
     lineinfile:
       state: "{{ state }}"
       insertafter: EOF
       path: vars/projects.yml
       line: "{{ lookup('template', 'projects.j2') }}"
```
projects.j2
```yaml
   {{ projectname }}:
    project: {{ projectname }}
    group: {{ groupname }}
```

##### EXPECTED RESULTS
I expect it to have the result in file projects.yml one time and to keep it that way. 

##### ACTUAL RESULTS
every time the playbook is run it just adds the same lines over and over. 
instead of seeing that they are already there, and skip it. 

```paste below
   xqbtest:
    project: xqbtest
    group: ETT
   xqbtest:
    project: xqbtest
    group: ETT
```
