### ISSUE TITLE
docker_container always reports changed when using network_mode: container:<name>

### ISSUE THREAD

**Issue by bengerman13** [ansible/ansible#49794]
##### SUMMARY
when using docker_container, if you set network_mode with a container:name, it always reports changed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```$ ansible --version
ansible 2.7.1
  config file = None
  configured module search path = ['/home/benb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/benb/.local/share/virtualenvs/ansible-platform-pnaOgkJy/lib/python3.7/site-packages/ansible
  executable location = /home/benb/.local/share/virtualenvs/ansible-platform-pnaOgkJy/bin/ansible
  python version = 3.7.0 (default, Sep 12 2018, 18:30:08) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]


```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
$ 
```

##### OS / ENVIRONMENT
Host and guest are Ubuntu 18.04

##### STEPS TO REPRODUCE

```
- name: Start telegraf sidecar container
  docker_container:
    name: telegraf_1
    image: telegraf
    network_mode: container:other_container

- name: Do it again
  docker_container:
    name: telegraf_1
    image: telegraf
    network_mode: container:other_container

```

##### EXPECTED RESULTS
Do it again should not report `changed`

##### ACTUAL RESULTS
```
        "changed": true,
        "diff": {
            "differences": [
                {
                    "network_mode": {
                        "container": "container:ef16e4f7a9f868fa0b0c409eb46b13a685174ce6c1f87878e8955283aab1516d",
                        "parameter": "container:other_container"
                    }
                }
            ]
        }
```
