### ISSUE TITLE
VMware: customvalues cannot be boolean in vmware_guest

### ISSUE THREAD

**Issue by adarobin** [ansible/ansible#49793]
##### SUMMARY

I am unable to set a boolean value with customvalues in the vmware_guest module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0 (devel a71cd49a0c) last updated 2018/12/10 17:00:28 (GMT -400)
  config file = None
  configured module search path = [u'/Users/adarobin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/adarobin/Code/ansible/lib/ansible
  executable location = /Users/adarobin/Code/ansible/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

Virtual Machine managed by vCenter 6.5 Update 2

##### STEPS TO REPRODUCE

```yaml
- name: 8.2.6 (L1) Ensure unauthorized modification and disconnection of devices is disabled (Scored)
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    name: "{{ inventory_hostname }}"
    customvalues:
      - key: 'isolation.device.edit.disable'
        value: true
  delegate_to: localhost
```

##### EXPECTED RESULTS

The task runs successfully.

##### ACTUAL RESULTS

```
TASK [cis-esxi-6.5-virtual-machine-benchmark-level-1 : 8.2.6 (L1) Ensure unauthorized modification and disconnection of devices is disabled (Scored)] ***
fatal: [HamSandwich -> localhost]: FAILED! => {"changed": true, "msg": "A specified parameter was not correct: config.extraConfig[\"isolation.device.edit.disable\"]"}
```

This runs successfully if I change the value to a string instead of a boolean like this:
```yaml
- name: 8.2.6 (L1) Ensure unauthorized modification and disconnection of devices is disabled (Scored)
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    name: "{{ inventory_hostname }}"
    customvalues:
      - key: 'isolation.device.edit.disable'
        value: 'true'
  delegate_to: localhost
```
