### ISSUE TITLE
Support for CORS configuration in azure_rm_storageaccount

### ISSUE THREAD

**Issue by NillsF** [ansible/ansible#49791]
##### SUMMARY
Add support to enable/disable CORS configuration in azure_rm_storageaccount, similar to aws_s3_cors_module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_storageaccount
##### ADDITIONAL INFORMATION

CORS is an HTTP feature that enables a web application running under one domain to access resources in another domain. It is turned off by default on new storage accounts.
CORS is turned on/off per service: blob, file, queue, table.

More info on [CORS](https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services)

```yaml
- azure_blob_cors:
    name: staccname
    state: present
    rules:
      - allowed_origins:
          - http://www.example.com/
        allowed_methods:
          - GET
          - POST
        allowed_headers:
          - x-ms-meta-data*
          - x-ms-meta-target*
          - x-ms-meta-abc
        expose_headers:
          - x-ms-meta-*
        max_age_seconds: 200
```
