### ISSUE TITLE
Ansible Failed to join domain

### ISSUE THREAD

**Issue by isorn44x** [ansible/ansible#49805]
##### SUMMARY
Failing to join the VM to Domain

##### ISSUE TYPE
win_domain_membership

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
```
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```
##### CONFIGURATION
```yaml
- name: Add VM into AD
  win_domain_membership:
    dns_domain_name: XXX.XXXXX
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "OU=XXXX,DC=XXX,DC=XXXXX"
    state: domain
  register: AD_result
```
##### OS / ENVIRONMENT
RHEL7.5

##### ADDITIONAL INFORMATION
I was trying to add the VM to AD but it failing, when i do manually it works fine. I have confirmed the user-id and password use to join the domain have no issue.

I am getting this error below.
```json
TASK [Post_Provision : Add VM into AD] *****************************************
task path: /var/lib/awx/projects/qa_environment/roles/Post_Provision/tasks/main.yml:22
Read vars_file 'DOMAIN_PWD.yml'
Read vars_file 'DOMAIN_PWD.yml'
Read vars_file 'DOMAIN_PWD.yml'
Read vars_file 'DOMAIN_PWD.yml'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_domain_membership.ps1
<Hostname> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT XXXX TO Hostname
checking if winrm_host Hostname is an IPv6 address
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_domain_membership.ps1
<Hostname> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT XXXX TO Hostname
checking if winrm_host Hostname is an IPv6 address
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_domain_membership.ps1
<Hostname> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT XXXX TO Hostname
checking if winrm_host Hostnameis an IPv6 address
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_domain_membership.ps1
<Hostname> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT XXXX TO Hostname
checking if winrm_host Hostname is an IPv6 address
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_domain_membership.ps1
<Hostname> ESTABLISH WINRM CONNECTION FOR USER: Admin on PORT XXXX TO Hostname
checking if winrm_host Hostname is an IPv6 address
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
fatal: [Hostname]: FAILED! => {
    "changed": true, 
    "msg": "failed to join domain: Computer 'Hostname' failed to join domain 'XXX.XXXXX' from its current workgroup 'WRKGRP' with following error message: Unknown error (0x8b0).", 
    "reboot_required": false
}
fatal: [Hostname]: FAILED! => {
    "changed": true, 
    "msg": "failed to join domain: Computer 'Hostname' failed to join domain 'XXX.XXXXX' from its current workgroup 'WRKGRP' with following error message: Unknown error (0x8b0).", 
    "reboot_required": false
}
fatal: [Hostname]: FAILED! => {
    "changed": true, 
    "msg": "failed to join domain: Computer 'Hostname' failed to join domain 'XXX.XXXXX' from its current workgroup 'WRKGRP' with following error message: Unknown error (0x8b0).", 
    "reboot_required": false
}
fatal: [Hostname]: FAILED! => {
    "changed": true, 
    "msg": "failed to join domain: Computer 'Hostname' failed to join domain 'XXX.XXXXX' from its current workgroup 'WRKGRP' with following error message: Unknown error (0x8b0).", 
    "reboot_required": false
}
fatal: [Hostname]: FAILED! => {
    "changed": true, 
    "msg": "failed to join domain: Computer 'Hostname' failed to join domain 'XXX.XXXXX' from its current workgroup 'WRKGRP' with following error message: Unknown error (0x8b0).", 
    "reboot_required": false
} 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_domain_membership.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain_membership.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
Hmm, lots of possibilities with this.
A couple of ideas come to mind.
One is to check if you already have computer accounts in your domain for those machine names.
The other is to have a read of this and see if any of it is relevant.
https://serverfault.com/questions/642587/unable-to-perform-an-unattended-domain-join-using-wds-and-an-answer-file-on-wind

Hope this helps,
Jon

**Comment by isorn44x** [comment]
The computer account already added on the domain, it works when we manually add the VM into AD..

**Comment by isorn44x** [comment]
```yaml
- name: Add VM into AD
  win_domain_membership:
    dns_domain_name: XXX.XXXXX
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    domain_ou_path: "OU=XXXX,DC=XXX,DC=XXXXX"
    log_path: C:\Windows\Temp\ad_join_log.txt
    state: domain
  register: AD_result
  
- win_reboot:
  when: domain_state.reboot_required
```

*** From ad_join_log.txt ****
```
2018-12-13 15:44:41Z current hostname XXXXXXXX matches XXXXXXXX: True
2018-12-13 15:44:41Z calling GetComputerDomain()
2018-12-13 15:44:41Z not currently joined to a reachable domain
2018-12-13 15:44:41Z not a domain member, joining...
2018-12-13 15:44:41Z adding domain_ou_path to domain-join args
2018-12-13 15:44:41Z Creating credential for user XXX.XXX.XXXXXX@XXX.XXX
2018-12-13 15:44:41Z adding hostname set arg to Add-Computer args
2018-12-13 15:44:41Z adding OU destination arg to Add-Computer args
2018-12-13 15:44:41Z calling Add-Computer with args: 
Name                           Value                                            
----                           -----                                            
Credential                     System.Management.Automation.PSCredential        
ComputerName                   .                                                
OUPath                         OU=XXXX,DC=XXX,DC=XXX
Force                                                                           
DomainName                     XXX.XXX
```
