### ISSUE TITLE
fmgr_provisioning - Provision devices via FortiMananger - no modules

### ISSUE THREAD

**Issue by kcapecchi** [ansible/ansible#49813]
##### SUMMARY
It is more question than a "regular" documentation report. It seems that yml modules for fmgr_provision are not exisiting.

Consequently to this, when I create a test playbook like this : 

```yaml
- name: Create Model Device
  hosts: FortiManager
  connection: local
  gather_facts: False
  tasks:
    - name: Create FGT1 Model Device
      fmgr_provision:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_pass }}"
        adom: "root"
        vdom: "root"
        policy_package: "default"
        name: "FGT1"
        group: "Ansible"
        serial: "FGVM000000117994"
        platform: "FortiGate-VM64"
        description: "Provisioned by Ansible"
        os_version: '5.0'
        minor_release: 0
        patch_release: 0
        os_type: 'fos'

```

and when I execute it : it gives me the following error :+1: 

```
ansible-playbook fmgr_provisioning.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/tubalcain/depot/ansible/lib/ansible/modules/network/fortimanager/fmgr_provisioning.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Create FGT1 Model Device
      ^ here

```

##### OS / ENVIRONMENT
Linux 

##### ADDITIONAL INFORMATION

Do you know when those YML modules for fortimanager will be implemented ?

thanks
