### ISSUE TITLE
Cloud config and provisioning

### ISSUE THREAD

**Issue by hilaf-pipl** [ansible/ansible#49814]
##### SUMMARY

Enhancement for the sl_vm module in Ansible, to allow more flexible machine provisioning in IBM softlayer.

##### ISSUE TYPE
- Feature Idea
Two requests somewhat connected together, under sl_vm module:
1. Use custom/private image under os_code
2. Ability to use (add field) cloud config when provisioning a machine.

##### COMPONENT NAME

sl_vm

##### ADDITIONAL INFORMATION

1. custom/private image, should still be used with field "os_code" under sl_vm module:
instead of "DEBIAN_LATEST_64", for example- "company_os_latest" - any name that will indicate we're using a custom/private image and not a well known one.
2. add another field called "cloud_config" or "user_data" (for example) under sl_vm module.

```yaml
- name: create machine
  sl_vm:
    hostname: "{{ VM_HOSTNAME }}{{ '%02d'| format(index + (start_count|int)) }}"
    domain: "{{ VM_DOMAIN }}"
    private: "{{ VM_PRIVATE }}"
    datacenter: "{{ item.1 }}"
    tags: "{{ VM_TAGS|join(',') }}"
    hourly: "{{ VM_HOURLY }}"
    dedicated: "{{ VM_DEDICATED }}"
    local_disk: "{{ VM_LOCAL_DISK }}"
    cpus: "{{ VM_CPUS }}"
    memory: "{{ VM_MEMORY }}"
    disks: "{{ VM_DISKS }}"
    *****os_code: "{{ VM_OS_CODE - Here we'll use the custom image name }}"
    *****user_data: "{{ VM_USER_DATA - Here we'll use variable that holds our cloud config }}"
    post_uri: "{{ VM_POST_URI }}"
    nic_speed: "1000"
    wait: "{{ VM_WAIT }}"
    wait_time: "{{ VM_WAIT_TIME }}"
  with_nested:
    - "{{ range(((( (end_count|int) + 1) - (start_count|int) ) / (VM_DATACENTER | length)) | round(0,'ceil')| int ) | list }}"
    - "{{ VM_DATACENTER }}"
  loop_control:
    index_var: index
  when: index < ( (end_count|int) - (start_count|int) + 1 )
  register: async_results
  async: 1200
  poll: 0
```
