### ISSUE TITLE
Ansible fetch sticky bit

### ISSUE THREAD

**Issue by gopurx** [ansible/ansible#49837]
##### SUMMARY

Using Fetch module trying to move files from windows host to unix, sticky bit on directory is not inherited to files moved under unix directory

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Fetch module ansible

##### ANSIBLE VERSION

Ansible 2.6.2

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml

- name: Creates archive directory
  file:
    path: "/tmp/files/"
    state: directory
    mode: 01777
- name: Move files to archive directory
  fetch:
    validate_checksum: yes
    src: 'D:\tmp\files\temp.txt'
    dest: /tmp/files/
    flat: yes
```

##### EXPECTED RESULTS

files to be copied with permissions and user set on files directory, but getting created with 0644 permissions and random user and group

##### ACTUAL RESULTS

N/A
