### ISSUE TITLE
When condition is not working properly with include

### ISSUE THREAD

**Issue by saharansible** [ansible/ansible#49840]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
```

##### CONFIGURATION

```paste below
PLAY [Upgrading ASA Firewall] ******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [Fw4Script-01.tor.bellnhs.int]
ok: [Fw4Script-02.tor.bellnhs.int]

TASK [show int ip br on ASA Firewall] **********************************************************************************************
ok: [Fw4Script-01.tor.bellnhs.int]
ok: [Fw4Script-02.tor.bellnhs.int]

TASK [show the state] **************************************************************************************************************
ok: [Fw4Script-01.tor.bellnhs.int] => {
    "output.stdout": [
        "failover lan unit primary"
    ]
}
ok: [Fw4Script-02.tor.bellnhs.int] => {
    "output.stdout": [
        ""
    ]
}

TASK [RUN the script] **************************************************************************************************************
skipping: [Fw4Script-01.tor.bellnhs.int]
skipping: [Fw4Script-02.tor.bellnhs.int]

TASK [show the output] *************************************************************************************************************
skipping: [Fw4Script-01.tor.bellnhs.int]
skipping: [Fw4Script-02.tor.bellnhs.int]

PLAY RECAP *************************************************************************************************************************
Fw4Script-01.tor.bellnhs.int : ok=3    changed=0    unreachable=0    failed=0   
Fw4Script-02.tor.bellnhs.int : ok=3    changed=0    unreachable=0    failed=0   
```

##### OS / ENVIRONMENT

entOS Linux release 7.5.1804 (Core) 

##### STEPS TO REPRODUCE

```yaml
---
- name: Upgrading ASA Firewall

  vars_prompt:
    - name: USERID
      prompt: Enter Username
      private: no

    - name: PASSWD
      prompt: Enter Password
      private: yes

    - name: ENABLE
      prompt: Enter Password
      private: yes



  hosts: PrimaryFW
  vars:
    ansible_ssh_user: "{{ USERID }}"
    ansible_ssh_pass: "{{ PASSWD }}"
    ansible_become_pass:  "{{ ENABLE }}"
    epic: true

  tasks:



#### Pre-verification ####

  - name: show int ip br on ASA Firewall
    asa_command:
      commands:
      -  show running-config | i unit primary
    register: output

  - name: show the state
    debug: var=output.stdout



  - include: show_command.yml
    when: '"primary" in output.stdout'
    
```

##### EXPECTED RESULTS

The playbook is running for 2 different hosts:

For the first one: the output of the "show running-config | i unit primary" is "failover lan unit primary" which will be registered in output, and when we have the below conditions, the show_command.yml playbook should be run for it since it passes the condition.

  - include: show_command.yml
    when: '"primary" in output.stdout'

For the second one: the output of the "show running-config | i unit primary" is empty which will be registered in output, and when we have the below conditions, the show_command.yml playbook should be skipped for it since it doesn't pass the condition.

  - include: show_command.yml
    when: '"primary" in output.stdout'

##### ACTUAL RESULTS

For both hosts, these steps are being skipped which is not expected. It seems that playbook it not able to check the condition before running the include command.

  - include: show_command.yml
    when: '"primary" in output.stdout'

```paste below
PLAY [Upgrading ASA Firewall] ******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [Fw4Script-01.tor.bellnhs.int]
ok: [Fw4Script-02.tor.bellnhs.int]

TASK [show int ip br on ASA Firewall] **********************************************************************************************
ok: [Fw4Script-01.tor.bellnhs.int]
ok: [Fw4Script-02.tor.bellnhs.int]

TASK [show the state] **************************************************************************************************************
ok: [Fw4Script-01.tor.bellnhs.int] => {
    "output.stdout": [
        "failover lan unit primary"
    ]
}
ok: [Fw4Script-02.tor.bellnhs.int] => {
    "output.stdout": [
        ""
    ]
}

TASK [RUN the script] **************************************************************************************************************
skipping: [Fw4Script-01.tor.bellnhs.int]
skipping: [Fw4Script-02.tor.bellnhs.int]

TASK [show the output] *************************************************************************************************************
skipping: [Fw4Script-01.tor.bellnhs.int]
skipping: [Fw4Script-02.tor.bellnhs.int]

PLAY RECAP *************************************************************************************************************************
Fw4Script-01.tor.bellnhs.int : ok=3    changed=0    unreachable=0    failed=0   
Fw4Script-02.tor.bellnhs.int : ok=3    changed=0    unreachable=0    failed=0   
```
