### ISSUE TITLE
vmware_guest VLAN/Network does not exist 

### ISSUE THREAD

**Issue by kartikaydw** [ansible/ansible#49842]
error of VLAN/Network does not exist , updated to ansible 2.7 after NIC was not getting connected automatically to to distributed portgroup
```
"msg": "VLAN '1112' does not exist." (1112 is a random number)
 "msg": "Network 'network-name' does not exist."
```
================================================

##### SUMMARY
vmware_guest VLAN/Network does not exist  while reconfiguring VM using vmware_guest module

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.7.4
config file = /opt/ansible/VC/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/opt/ansible/VC/ansible.cfg) = [u'/opt/ansible/VC/inventory']
```

##### OS / ENVIRONMENT
Source OS - CentOS 7.5
Target - VC 

##### STEPS TO REPRODUCE
```yaml
vmware_guest:
hostname: "{{ vc_name }}"
username: "{{ uname }}"
password: "{{ password }}"
validate_certs: False
datacenter: "DC"
name: "vm-name"
networks:
- vlan: "{{ network }}"
dvswitch_name: "switch name"
connected: True
type: static
delegate_to: localhost
```
OR 
```yaml
vmware_guest:
hostname: "{{ vc_name }}"
username: "{{ uname }}"
password: "{{ password }}"
validate_certs: False
datacenter: "DC"
name: "vm-name"
networks:
- name: "{{ network_name }}"
dvswitch_name: "switch name"
connected: True
type: static
delegate_to: localhost
```

```yaml

vmware_guest:
hostname: "{{ vc_name }}"
username: "{{ uname }}"
password: "{{ password }}"
validate_certs: False
datacenter: "DC"
name: "vm-name"
networks:
- name: "{{ network_name }}"
dvswitch_name: "switch name"
connected: True
type: static
delegate_to: localhost
```
