### ISSUE TITLE
postgresql_user can't detect password changes for scram-sha-256 PostgreSQL password encryption.

### ISSUE THREAD

**Issue by tinproject** [ansible/ansible#49878]
##### SUMMARY
The postgresql_user module can't detect password changes for scram-sha-256 encrypted passwords, so always mark the state as changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

All, checked with code from _devel_ branch.

##### STEPS TO REPRODUCE

Use a PostgreSQL server with `password_encryption = scram-sha-256` parameter on `postgresql.conf`.

Creates a playbook that creates an user using `postgresql_user` module with a clear text password using the PostgreSQL referenced before:

```yaml
- name: Create user on PostgreSQL server
  postgresql_user:
    state: present
    name: "my_user"
    password: "my_secret_password"
    role_attr_flags: "LOGIN"
```

Run playbook multiple times.

##### EXPECTED RESULTS

The `Create user on PostgreSQL server` task will have `"changed": false` after the first playbook run.

##### ACTUAL RESULTS

The `Create user on PostgreSQL server` task will show as `"changed": true` all the times.

```paste below

```
