### ISSUE TITLE
tower_project: traceback when scm_credential defined with same name in different orgs

### ISSUE THREAD

**Issue by Shaps** [ansible/ansible#49883]
##### SUMMARY
tower_project prints a traceback when looking for a scm credential that is defined with the same name more than one tower organization

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_project

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0 (tower_project_scm_cred_org d93d1430cc) last updated 2018/12/13 12:48:00 (GMT +100)
  config file = /home/shaps/.ansible.cfg
  configured module search path = [u'/home/shaps/.virtualenvs/spansible/lib/python2.7/site-packages/ara/plugins/modules']
  ansible python module location = /home/shaps/Documents/code/ansible/lib/ansible
  executable location = /home/shaps/Documents/code/ansible/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]

```
( Also tested in 2.7.4 )

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
ANSIBLE_PIPELINING(/home/shaps/.ansible.cfg) = True
DEFAULT_ACTION_PLUGIN_PATH(/home/shaps/.ansible.cfg) = [u'/home/shaps/.virtualenvs/spansible/lib/python2.7/site-packages/ara/plugins/actions']                                                                                                                                             
DEFAULT_CALLBACK_PLUGIN_PATH(/home/shaps/.ansible.cfg) = [u'/home/shaps/.virtualenvs/spansible/lib/python2.7/site-packages/ara/plugins/callbacks']                                                                                                                                         
DEFAULT_MODULE_PATH(/home/shaps/.ansible.cfg) = [u'/home/shaps/.virtualenvs/spansible/lib/python2.7/site-packages/ara/plugins/modules']
DEFAULT_STDOUT_CALLBACK(/home/shaps/.ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/shaps/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/shaps/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
**Control:** Fedora release 29 (Twenty Nine)
**Target:** Ansible Tower running on RHEL 7.4

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
- hosts: localhost                                                                                                                                                                                                                                                                          
  tasks:                                                                                                                                                                                                                                                                                    
    - name: "Create {{ item }}"                                                                                                                                                                                                                                                            
      tower_organization:                                                                                                                                                                                                                                                                   
        name: "{{ item }}"                                                                                                                                                                                                                                                                  
      loop:                                                                                                                                                                                                                                                                                
        - TestOrg1                                                                                                                                                                                                                                                                          
        - TestOrg2                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            
    - name: "Create credential"                                                                                                                                                                                                                                                             
      tower_credential:                                                                                                                                                                                                                                                                     
        kind: scm                                                                                                                                                                                                                                                                           
        name: TestCred1                                                                                                                                                                                                                                                                     
        organization: "{{ item }}"                                                                                                                                                                                                                                                          
      loop:                                                                                                                                                                                                                                                                                 
        - TestOrg2                                                                                                                                                                                                                                                                          
        - TestOrg1                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            
    - name: Create project TestProject                                                                                                                                                                                                                                                      
      tower_project:                                                                                                                                                                                                                                                                        
        name: TestProject                                                                                                                                                                                                                                                                   
        organization: TestOrg1                                                                                                                                                                                                                                                              
        scm_type: git                                                                                                                                                                                                                                                                       
        scm_url: "https://example.com/my-repo.git"                                                                                                                                                                                                                                          
        scm_credential: TestCred1     
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
```yaml
TASK [Create project TestProject] *******************************************************************************************************
task path: <redacted>
changed: [localhost] => changed=true
  id: 269
  project: TestProject
  state: present
```

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```paste below
*** DETAILS: Getting the record. **********************************************
GET https://<redacted>/api/v2/organizations/
Params: {'name': 'TestOrg1'}

*** DETAILS: Getting the record. **********************************************
GET https://<redacted>/api/v2/credentials/
Params: {'name': 'TestCred1'}

Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_tower_project_payload_7sQR3W/__main__.py", line 172, in <module>
  File "/tmp/ansible_tower_project_payload_7sQR3W/__main__.py", line 149, in main
  File "/home/shaps/.virtualenvs/spansible/lib/python2.7/site-packages/tower_cli/models/base.py", line 486, in get
    response = self.read(pk=pk, fail_on_no_results=True, fail_on_multiple_results=True, **kwargs)
  File "/home/shaps/.virtualenvs/spansible/lib/python2.7/site-packages/tower_cli/models/base.py", line 312, in read
    'fields. Please tighten your criteria.' % resp['count'])
tower_cli.exceptions.MultipleResults: Expected one result, got 2. Possibly caused by not providing required fields. Please tighten your criteria.
```
