### ISSUE TITLE
'pull: false' required when building image with docker_image using 'COPY --from'

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#49909]
##### SUMMARY

When I am building a series of Docker images which depend on each other, Ansible's `docker_image` module fails when building subsequent dependent images which use `COPY --from` (for multi-stage builds).

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`docker_image` module

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jeff.geerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/Users/jeff.geerling/Dropbox/VMs/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS, with Docker for Mac (tested on 18.09 and 2.0.0.0). Also tested on Ubuntu 16.04 with Docker 18.09.

##### STEPS TO REPRODUCE

Playbook to build two Docker images:

```yaml
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    - name: Build src image.
      docker_image:
        path: image-src
        name: image-src
        tag: latest
        state: present
        force: true

    - name: Build dest image.
      docker_image:
        path: image-dest
        name: image-dest
        tag: latest
        state: present
        force: true
```

Dockerfile in `image-src/Dockerfile`:

```
FROM nginx:1.15-alpine AS image-src

RUN touch /tmp/test-src.txt
```

Dockerfile in `image-dest/Dockerfile`:

```
FROM nginx:1.15-alpine AS image-dest

COPY --from=image-src /tmp/test-src.txt /tmp/test-dest.txt
```

##### EXPECTED RESULTS

I should see both tasks report changed / success, and no errors, when building the two images.

##### ACTUAL RESULTS

```
$ ansible-playbook main.yml

PLAY [127.0.0.1] ***************************************************************************************

TASK [Build src image.] ********************************************************************************
changed: [127.0.0.1]

TASK [Build dest image.] *******************************************************************************
fatal: [127.0.0.1]: FAILED! => changed=false 
  msg: 'Error building image-dest - code: None, message: invalid from flag value image-src: pull access denied for image-src, repository does not exist or may require ''docker login'', logs: [
  Step 1/2 : FROM nginx:1.15-alpine AS image-dest
   ---> 63356c558c79
  Step 2/2 : COPY --from=image-src /tmp/test-src.txt /tmp/test-dest.txt

PLAY RECAP *********************************************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=1  
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_image.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_image.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @akshay196 @chouseknecht @danihodovic @dariko @felixfontein @jwitko @kassiansun @softzilla @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by geerlingguy** [comment]
Note that if I _explicitly_ add a `pull: false` to the 2nd task, then the build succeeds:

```yaml
    - name: Build dest image.
      docker_image:
        path: image-dest
        name: image-dest
        tag: latest
        state: present
        force: true
        pull: false
```

I found an older related issue (https://github.com/ansible/ansible-modules-core/issues/3760), but in that issue, it seems that the limitation of requiring an explicit `pull: false` is _only_ supposed to apply when pulling images with a `/` in them (e.g. `my/image`). In this case, I have tried both ways and neither work unless you explicitly add the `pull: false`.

For now I will work around this by setting `pull: false` explicitly, but it would be nice if this could work out of the box, just like Docker itself does (e.g. if I do a `docker build -t image-dest image-dest/.` it works fine using the already-built `image-src` image, also tested and works with `docker-compose` building the images in succession).
