### ISSUE TITLE
Missing variable type for rds_instance module

### ISSUE THREAD

**Issue by davidhollenberger** [ansible/ansible#49904]
##### SUMMARY

Getting an error when creating a MySQL RDS instance with Performance Insights enabled.  The corresponsing parameter option is missing the variable type.

I got it working by changing this line:
https://github.com/ansible/ansible/blob/9d62cbc2af25fc0c8570afa1aa95520b476fc0de/lib/ansible/modules/cloud/amazon/rds_instance.py#L1051

to this:
`performance_insights_retention_period=dict(type='int'),`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

rds_instance

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ansible host: Mac OS X 10.13.6

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/aws-rds.yml

  tasks:

    - name: Create RDS Instance
      rds_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        db_instance_identifier: "{{ name }}"
        engine: "{{ engine }}"
        engine_version: "{{ engine_version }}"
        db_parameter_group_name: "{{ parameter_group_name }}"
        db_instance_class: "{{ db_instance_class }}"
        storage_encrypted: true
        storage_type: gp2
        allocated_storage: 50
        multi_az: true
        vpc_security_group_ids: "{{ vpc_secrutiy_group_ids }}"
        db_subnet_group_name: "{{ subnet_group_name }}"
        master_username: "{{ master_username }}"
        master_user_password: "{{ master_user_password }}"
        enable_performance_insights: true
        performance_insights_retention_period: 7
```

##### EXPECTED RESULTS

RDS instance is created with performance insights enabled.

##### ACTUAL RESULTS

Module fails to create instance.

```paste below
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.9.57",
    "botocore_version": "1.12.57",
    "changed": false,
    "invocation": {
        "module_args": {
            "allocated_storage": 50,
            "allow_major_version_upgrade": null,
            "apply_immediately": false,
            "auto_minor_version_upgrade": null,
            "availability_zone": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "backup_retention_period": null,
            "ca_certificate_identifier": null,
            "character_set_name": null,
            "copy_tags_to_snapshot": null,
            "creation_source": null,
            "db_cluster_identifier": null,
            "db_instance_class": "db.m5.large",
            "db_instance_identifier": "rds-test",
            "db_name": null,
            "db_parameter_group_name": "rds-test",
            "db_security_groups": null,
            "db_snapshot_identifier": null,
            "db_subnet_group_name": "rds-test",
            "domain": null,
            "domain_iam_role_name": null,
            "ec2_url": null,
            "enable_cloudwatch_logs_exports": null,
            "enable_iam_database_authentication": null,
            "enable_performance_insights": true,
            "engine": "mysql",
            "engine_version": "5.6.41",
            "final_db_snapshot_identifier": null,
            "force_failover": null,
            "force_update_password": false,
            "iops": null,
            "kms_key_id": null,
            "license_model": null,
            "master_user_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "master_username": "XXXXXX",
            "monitoring_interval": null,
            "monitoring_role_arn": null,
            "multi_az": true,
            "new_db_instance_identifier": null,
            "option_group_name": null,
            "performance_insights_kms_key_id": null,
            "performance_insights_retention_period": "7",
            "port": null,
            "preferred_backup_window": null,
            "preferred_maintenance_window": null,
            "processor_features": null,
            "profile": null,
            "promotion_tier": null,
            "publicly_accessible": null,
            "purge_cloudwatch_logs_exports": true,
            "purge_tags": true,
            "read_replica": null,
            "region": null,
            "restore_time": null,
            "s3_bucket_name": null,
            "s3_ingestion_role_arn": null,
            "s3_prefix": null,
            "security_token": null,
            "skip_final_snapshot": false,
            "snapshot_identifier": null,
            "source_db_instance_identifier": null,
            "source_engine": null,
            "source_engine_version": null,
            "source_region": null,
            "state": "present",
            "storage_encrypted": true,
            "storage_type": "gp2",
            "tags": null,
            "tde_credential_arn": null,
            "tde_credential_password": null,
            "timezone": null,
            "use_latest_restorable_time": null,
            "validate_certs": true,
            "vpc_security_group_ids": [
                "sg-XXXXXX"
            ],
            "wait": true
        }
    },
    "msg": "Unexpected failure for method create_db_instance with parameters {'Engine': 'mysql', 'DBParameterGroupName': 'rds-test', 'EnablePerformanceInsights': True, 'MultiAZ': True, 'MasterUsername': 'XXXXXX', 'PerformanceInsightsRetentionPeriod': '7', 'VpcSecurityGroupIds': ['sg-XXXXXX'], 'MasterUserPassword': '********', 'StorageType': 'gp2', 'StorageEncrypted': True, 'AllocatedStorage': 50, 'EngineVersion': '5.6.41', 'DBInstanceClass': 'db.m5.large', 'DBSubnetGroupName': 'rds-test', 'DBInstanceIdentifier': 'rds-test'}: Parameter validation failed:\nInvalid type for parameter PerformanceInsightsRetentionPeriod, value: 7, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>"
}
```
