### ISSUE TITLE
user-module is not using --ask-pass

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#49910]
##### SUMMARY
Usually, a user is allowed to change his own login shell. On some systems -- such as on RedHat -- this operation requires entering the user's password. Unfortunately, the `user`-module ignores the password given to Ansible via `--ask-pass` -- and there is no need for such a limitation.

In this organizations, new accounts are created with `/bin/ksh` as the shell and we want to make it easier for people to change their accounts as they wish afterwards.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
user

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /mi/A/ansible.cfg
  configured module search path = ['/mi/.ansible/plugins/modules', '/opt/share/py36-ansible/plugins/modules']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.7 (default, Dec 11 2018, 16:01:45) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/mi/A/ansible.cfg) = -q -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r
CACHE_PLUGIN(/mi/A/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/mi/A/ansible.cfg) = /tmp/afacts
```

##### OS / ENVIRONMENT
RedHat 5.x, 6.x, and 7.x

##### STEPS TO REPRODUCE

`ansible-playbook --ask-pass -i... -e mylogin_shell=/bin/tcsh playbook.yml`

```yaml
- name: Change shell if requested
  user:
    name: "{{ ansible_ssh_user }}"
    shell: "{{ hostvars[inventory_hostname][ansible_ssh_user + '_shell'] }}"
  when: hostvars[inventory_hostname][ansible_ssh_user + '_shell'] is defined
```

##### EXPECTED RESULTS
Shell changes to `/bin/tcsh` on all the hosts, where it was not that already.

##### ACTUAL RESULTS

```
fatal: [...]: FAILED! => {"changed": false, "cmd": "/sbin/usermod -s /bin/tcsh mylogin", "msg": "[Errno 13] Permission denied", "rc": 13}
```
