### ISSUE TITLE
ec2_vpc_subnet_facts not returning the expected result

### ISSUE THREAD

**Issue by tplive** [ansible/ansible#49926]
##### SUMMARY

When parsing output from `ec2_vpc_subnet_facts`, Ansible complains that the `combine()` filter expects a dict, the output isn't a dict and on inspecting the output, I find that one of the subnets is listed as "Undefined". They are all clearly available in AWS console. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vpc_subnet_facts
##### ANSIBLE VERSION

```bash
ansible 2.7.4
  config file = /home/username/Ansible/aws-apigee/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_PRIVATE_KEY_FILE(/home/username/Ansible/aws-apigee/ansible.cfg) = /home/username/.ssh/id_rsa_mykey
HOST_KEY_CHECKING(/home/username/Ansible/aws-apigee/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04.1 LTS 64-bit
##### STEPS TO REPRODUCE

```yaml
# Find our subnets by VPC ID that was just defined
- name: "VPC subnet facts"
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    filters:
      vpc-id: "{{ vpc_id }}"
  register: vpc_subnet_facts

- name: "set facts: VPC subnet IDs"
  set_fact:
    vpc_subnet_ids: "{{ vpc_subnet_ids | default({}) | combine({ (item.tags.Name | default('default')): item_id }) }}"
  loop: "{{ vpc_subnet_facts.subnets }}"
```

##### EXPECTED RESULTS

Subnet Ids should be kept in the object `vpc_subnet_ids`

##### ACTUAL RESULTS

```paste below
fatal: [vpc.ansibled]: FAILED! => {
    "msg": "|combine expects dictionaries, got u\"{u'private-c': u'subnet-041da87393d9553de', u'private-b': u'subnet-027de61fc8cc8b0aa', u'private-a': u'subnet-0200c81e8ca47cd01', u'public-a': u'subnet-0f73609b05d1b0fbf', u'public-b': Undefined, u'public-c': u'subnet-0e1f84dc751ba8a34'}\""
}
```
Deleting all AWS resources and rebuilding; it varies, from one run to the next, *which* subnet is 'Undefined'. This puzzles me, as they all pass initial creation, and are all clearly available in the AWS console.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_vpc_subnet_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_vpc_subnet_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@tplive, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@tplive Thanks for reporting this issue. I am not able to reproduce this issue with given playbook.

```yaml
ok: [localhost] => {
    "msg": {
        "default": "subnet-983006ec"
    }
}
```
