### ISSUE TITLE
git module: passphrase prompt maybe?

### ISSUE THREAD

**Issue by YAmikep** [ansible/ansible#4993]
The Git task is hanging and even after looking at the documention or on the internet, I still cannot make it work, thanks for your help.

I checked the known_hosts file but I think Git might be asking for the passphrase, and not the host. I cannot tell more, how can I see more what is going on?

Here is my provision.yml playbook where you can see I upload the known_hosts file, my key and the ssh config.

```
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  sudo: true

  tasks:
  - name: Create the project directory.
    file: state=directory path={{project_root}}

  - name: Create user.
    user: home={{project_root}}/home/ name={{project_name}} state=present password={{password}}

  - name: Update the project directory.
    file: group={{project_name}} owner={{project_name}} mode=755 state=directory path={{project_root}}

  - name: Create the code directory.
    file: group={{project_name}} owner={{project_name}} mode=755 state=directory path={{project_root}}/code/

  - name: Install required system packages.
    apt: pkg={{item}} state=installed update-cache=yes
    with_items: "{{system_packages}}"

  - name: Create the SSH directory.
    file: state=directory path={{project_root}}/home/.ssh/

  - name: Upload SSH known hosts.
    copy: src=known_hosts dest=${project_root}/home/.ssh/known_hosts mode=0600

  - name: Upload SSH Bitbucket key.
    copy: src=keys/bitbucket_id_rsa dest={{project_root}}/home/.ssh/bitbucket_id_rsa mode=0600

  - name: Upload SSH config.
    copy: src=keys/config dest={{project_root}}/home/.ssh/config
```

Here is where I use the git module:

```
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false

  tasks:
  - name: Pull sources from the repository.
    git: repo=${project_repo} dest=${project_root}/code/djangotutorial
```
