### ISSUE TITLE
VMware: Issues with vmware vcenter_folder(s) with ESXi

### ISSUE THREAD

**Issue by anirbee** [ansible/ansible#49938]
##### SUMMARY

While creating a folder in standalone ESXI server ansible gives the following exception

```
msg": "Failed to create folder due to generic exception (vmodl.fault.NotSupported) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'The operation is not supported on the object.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n} "
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vcenter_folder.py
##### ANSIBLE VERSION

```paste below
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/anirban/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]


```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

targetOS
ESXi-6.0.0-20160302001-standard 

target Host - It is a standalone Esxi server with no vSphere server in the environment

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ESXI
  connection: local
  gather_facts: false
 
  vars_files:
    - createVmVars.yaml
  
  tasks:
    -name: Create a VM folder on given datacenter
     vcenter_folder:
       hostname: '{{ esxi_server_hostname }}'
       username: '{{ esxi_server_username }}'
       password: '{{ esxi_server_password }}'
       datacenter: ha-datacenter
       folder_name: Test
       folder_type: vm
       state: present
     register: vm_folder_creation_result
     delegate_to: localhost
```

##### EXPECTED RESULTS

Test folder to be created under ha-datacenter
##### ACTUAL RESULTS

Error
```
"msg": "Failed to create folder due to generic exception : (vmodl.fault.NotSupported) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'The operation is not supported on the object.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n} "
```

```
TASK [Create a VM folder on given datacenter] **********************************
task path: /home/anirban/playbook/create_fol/vm_folder_prov.yaml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vcenter_folder.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: anirban
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861 `" && echo ansible-tmp-1544763777.16-41439361496861="` echo /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861 `" ) && sleep 0'
<localhost> PUT /home/anirban/.ansible/tmp/ansible-local-4085XWeVZA/tmp0Rdqwu TO /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861/vcenter_folder.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861/ /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861/vcenter_folder.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861/vcenter_folder.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/anirban/.ansible/tmp/ansible-tmp-1544763777.16-41439361496861/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_scKtza/ansible_module_vcenter_folder.py", line 176, in ensure
    datacenter_folder_type[folder_type].CreateFolder(folder_name)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [10.159.17.222 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "ha-datacenter",
            "folder_name": "Test",
            "folder_type": "vm",
            "hostname": "10.159.17.222",
            "parent_folder": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "root",
            "validate_certs": false
        }
    },
    "msg": "Failed to create folder due to generic exception : (vmodl.fault.NotSupported) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'The operation is not supported on the object.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n} "
}
```
