### ISSUE TITLE
while updating an existing ASG its termination_policies is changed to "Default"

### ISSUE THREAD

**Issue by dmytro-malovany** [ansible/ansible#49941]
##### SUMMARY

When I scale up ASG:
```
- name: Scale Up ASG
  ec2_asg:
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: 'eu-west-1'
    name: "{{ asgs.results[0].auto_scaling_group_name }}"
    max_size: "{{ asgs.results[0].min_size * 2 }}"
    desired_capacity: "{{ asgs.results[0].min_size * 2 }}"
  when: component is defined and scale == "up"
  register: update
```
Its `termination_policies` is changed to "Default". But in according to documentation it should remain the same in was. In my case: "OldestInstance"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: ec2_asg

##### ANSIBLE VERSION

```
ansible 2.5.5.dev0 (detached HEAD ref: refs/) last updated 2018/02/14 14:53:33 (GMT +200)
  config file = /opt/code/ansible-release-management/aws/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/code/ansible/lib/ansible
  executable location = /opt/code/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/opt/code/ansible-release-management/aws/ansible.cfg) = -o ForwardAgent=yes -o StrictHostKeyChecking=no
CACHE_PLUGIN(/opt/code/ansible-release-management/aws/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/opt/code/ansible-release-management/aws/ansible.cfg) = ['profile_tasks']
DEFAULT_CONNECTION_PLUGIN_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/opt/code/ansible-release-management/aws/ansible.cfg) = 5
DEFAULT_GATHERING(/opt/code/ansible-release-management/aws/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/opt/code/ansible-release-management/aws/hosts']
DEFAULT_LOG_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = /opt/code/ansible-release-management/aws/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/opt/code/ansible-release-management/aws/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG(/opt/code/ansible-release-management/aws/ansible.cfg) = C
DEFAULT_POLL_INTERVAL(/opt/code/ansible-release-management/aws/ansible.cfg) = 15
DEFAULT_ROLES_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/opt/code/ansible-release-management/aws/roles']
DEFAULT_SUDO_EXE(/opt/code/ansible-release-management/aws/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/opt/code/ansible-release-management/aws/ansible.cfg) = root
DEFAULT_TIMEOUT(/opt/code/ansible-release-management/aws/ansible.cfg) = 10
DEFAULT_TRANSPORT(/opt/code/ansible-release-management/aws/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/opt/code/ansible-release-management/aws/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
```

##### STEPS TO REPRODUCE

Scale up existing ASG with non-default termination policy
```yaml
- name: Scale Up ASG
  ec2_asg:
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: 'eu-west-1'
    name: "{{ asgs.results[0].auto_scaling_group_name }}"
    max_size: "{{ asgs.results[0].min_size * 2 }}"
    desired_capacity: "{{ asgs.results[0].min_size * 2 }}"
  when: component is defined and scale == "up"
  register: update
```
In result you will get x2 instances and Termination Policy = "Default"

##### EXPECTED RESULTS

I expect that only `max_size` and `desired_capacity` are changed and `termination_policies` remained = "OldestInstance"
```
        "termination_policies": [
            "OldestInstance"
        ],
```

##### ACTUAL RESULTS

```
            "termination_policies": [
                "Default"
            ],
```
