### ISSUE TITLE
How to use `count_tag` and `exact_count` with ec2_instance

### ISSUE THREAD

**Issue by SlayterDev** [ansible/ansible#49944]
##### SUMMARY

Currently our team uses the `ec2` module to provision a set of instances when running a playbook. However we'd like to begin deploying some tc2.unlimited instances. The `ec2_instance` module provides the `cpu_credit_specification` key which is what we need. However when migrating to this module it currently provides no support for `count_tag` and `exact_count` used by `ec2`. Is there currently a way to replicate this functionality using the `ec2_instance` module?

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2, ec2_instance

##### ANSIBLE VERSION

```paste below
2.7.2
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### STEPS TO REPRODUCE

Provision a set of instances using `ec2_instance` and have no way to specify instance counts.

Current playbook task:
```yaml
- name: Provision a set of instances
    ec2:
      key_name: "{{ ec2_key_pair_name }}"
      region: "{{ ec2_region }}"
      instance_type: "{{ instance_type | default(ec2_default_instance_type) }}"
      image: "{{ ami_id | default(ami_find.results[0].ami_id) }}"
      group: "{{ ec2_security_group_names | default(ec2_security_groups) }}"
      vpc_subnet_id: "{{ ec2_subnet_id | default(ec2_subnet_map[_availability_zone]) }}"
      wait: true
      ebs_optimized: "{{ True if (instance_type is defined and instance_type in ebs_optimized_types) else False }}"
      volumes: "{{ bdm_vols.result }}"
      instance_profile_name: "{{ _iam_role if instance_name is not defined else None }}"
      exact_count: "{{ _cluster_size if instance_name is not defined else omit }}"
      user_data: "{{ lookup('template', _user_data_script) }}"
      zone: "{{ _availability_zone.split('_')[0] }}"
      private_ip: "{{ private_ip_address | default(omit)}}"
      assign_public_ip: "{{ assign_public_ip | default(omit)}}"
      termination_protection: "{{ _ec2_termination_protection }}"
      count_tag:
        Lifecycle: "{{ env }}"
        Owner: "{{ owner }}"
        Ansible: di
        Service: "{{ service }}"
      instance_tags:
        Lifecycle: "{{ env }}"
        Owner: "{{ owner }}"
        Ansible: di
        Service: "{{ service }}"
        CreatedBy: "{{ ec2_tag_created_by }}"
    register: ec2
```

##### EXPECTED RESULTS

Provision a set of instances using `ec2_instance` with similar behavior to `ec2`

##### ACTUAL RESULTS

`ec2_instance` complains that `count_tag` and `exact_count` are not supported keys.

```paste below
12-Dec-2018 17:34:14 | "msg": "Unsupported parameters for (ec2_instance) module: count_tag, exact_count, group, instance_profile_name, instance_tags, zone Supported parameters include: availability_zone, aws_access_key, aws_secret_key, cpu_credit_specification, cpu_options, detailed_monitoring, ebs_optimized, ec2_url, filters, image, image_id, instance_ids, instance_initiated_shutdown_behavior, instance_role, instance_type, key_name, launch_template, name, network, profile, purge_tags, region, security_group, security_groups, security_token, state, tags, tenancy, termination_protection, tower_callback, user_data, validate_certs, volumes, vpc_subnet_id, wait, wait_timeout"
-- | --
12-Dec-2018 17:34:14 | }
12-Dec-2018 17:34:14 | to retry, use: --limit @/opt/ensighten/ebs0/bamboo/xml-data/build-dir/12091403-12255255/playbooks/example-api/aws_provision.retry
12-Dec-2018 17:34:14 |  
12-Dec-2018 17:34:14 | PLAY RECAP *********************************************************************
12-Dec-2018 17:34:14 | localhost                  : ok=10   changed=1    unreachable=0    failed=1
12-Dec-2018 17:34:14 |  
12-Dec-2018 17:34:14 | + fatal 'Failed to provision server'
12-Dec-2018 17:34:14 | + echo -e 'ERROR: Failed to provision server'
12-Dec-2018 17:34:14 | ERROR: Failed to provision server
12-Dec-2018 17:34:14 | + exit 1
12-Dec-2018 17:34:14 | + rm -rf /tmp/tmp.Gw2lcLWJ6x
12-Dec-2018 17:34:14 | ++ handle_error
12-Dec-2018 17:34:14 | ++ local errcode=1
12-Dec-2018 17:34:14 | ++ error 'Code: 1   Command: '\''scripts/deploy.sh${deploy_verbose_flag} "${params[@]}"'\''   Line: 165'
12-Dec-2018 17:34:14 | ++ echo -e 'ERROR: Code: 1   Command: '\''scripts/deploy.sh${deploy_verbose_flag} "${params[@]}"'\''   Line: 165'
12-Dec-2018 17:34:14 | ERROR: Code: 1   Command: 'scripts/deploy.sh${deploy_verbose_flag} "${params[@]}"'   Line: 165
12-Dec-2018 17:34:14 | ++ exit 1
12-Dec-2018 17:34:14 | + cleanup_temp_dir /tmp/tmp.EMq6WbvHcp
12-Dec-2018 17:34:14 | + verbose 'Cleaning up temp dir: /tmp/tmp.EMq6WbvHcp'
12-Dec-2018 17:34:14 | + is_verbose_enabled
12-Dec-2018 17:34:14 | + [[ '' -gt 0 ]]
12-Dec-2018 17:34:14 | + return 1
12-Dec-2018 17:34:14 | + rm -rf /tmp/tmp.EMq6WbvHcp
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2.py)
* [lib/ansible/modules/cloud/amazon/ec2_instance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_instance.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shaps @lwade @ryansb @tgerla
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@SlayterDev, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shaps** [comment]
Hi @SlayterDev, I'm not entirely sure if this is on purpose or just a not-yet-implemented feature. In any case to work around this, I believe the following should work:
```yaml
[...]
ec2_instances:
  [...]
  filters:
        Lifecycle: "{{ env }}"
        Owner: "{{ owner }}"
        Ansible: di
        Service: "{{ service }}"
loop: "{{ range(0, <your_n_instances>) | list }}"
```
