### ISSUE TITLE
Allow millisecond support for pause and loop_control

### ISSUE THREAD

**Issue by ericdost** [ansible/ansible#49951]
##### SUMMARY

Allow milliseconds in pause options

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

pause
loop_control

##### ADDITIONAL INFORMATION

I have a few playbooks where I have needed to implement pause due to API rate limiting.  I currently have to pause for 1 second, although if I could do sub-second pausing I would be able to do 5 requests a second.

```yaml
    - name: "Update device details for MX device(s)"
      meraki_device:
        auth_key: "{{ key }}"
        org_name: "{{ org }}"
        net_name: "{{ item.net_name }}"
        serial: "{{ item.mx_serial }}"
        name: "{{ item.mx_name }}"
        address: "{{ item.address }}"
        move_map_marker: yes
        state: present
      loop: "{{ meraki|flatten(levels=1) }}"
      loop_control:
        pause: 1
      delegate_to: localhost

    - name: Pause for Meraki API rate limiting
      pause:
        seconds: 1
```
