### ISSUE TITLE
Can't install many packages using `with_nested`

### ISSUE THREAD

**Issue by jbzdak** [ansible/ansible#4995]
I use ansible 1.3.4. 

I tried to install many packages using `apt` role and `with_nested` loop, I was following [this](http://www.ansibleworks.com/docs/playbooks_loops.html#id10) tutorial. 

Here is my code: 

```

---
- name: Install needed software
  apt: package={{item}}
  sudo: yes
  with_nested:
  - [ 'python3.3', 'virtualenvwrapper']
```

Expected behaviour: both packages get installed. 
Actual behaviour:

```
 TASK: [Install needed software] *********************************************** 
 (...)                                                                                        
 failed: [test_ansible] => (item=['p', 'y', 't', 'h', 'o', 'n', '3', '.', '3']) => {"failed": true, "item": ["p", "y", "t", "h", "o", "n", "3", ".", "3"]}
 msg: this module requires key=value arguments (['package=[p,', 'y,', 't,', 'h,', 'o,', 'n,', '3,', '.,', '3]'])
 (...)
```

It might be my mistake, or a bug in this loop. Anyways please either fix documentation to cover this case, or fix the bug with loop
