### ISSUE TITLE
Yum module: support state=distro-sync

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#49967]
##### SUMMARY

When dealing with development versions, distro-sync is useful yum command that brings the whole system or packages specified to versions that are currently available in the repo.

The same bug could be filed for `dnf` module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = /home/djasa/ansible/spice-qe/ansible.cfg
  configured module search path = ['/home/djasa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Nov 23 2018, 10:01:49) [GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$
```

##### STEPS TO REPRODUCE

```yaml
- name: revert custom packages to versions from repository
  module: yum
    package: '*'
    state: distro-sync
```

##### EXPECTED RESULTS

yum distro-sync [packages] is performed

##### ACTUAL RESULTS

```paste below

```
