### ISSUE TITLE
Add ability to rename dependency roles in meta/main.yml

### ISSUE THREAD

**Issue by jdorel** [ansible/ansible#49975]
##### SUMMARY

Add the ability to rename roles imported as dependency of other roles with the `name: ` tag.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

dependencies

##### ADDITIONAL INFORMATION

This could make the role independant of the developper, allowing us to change the creator of the role without modifying the name of the role in other files.

```yaml
dependencies:
  - src: jdorel.python_docker
    name: python_docker
```
