### ISSUE TITLE
maven_artifact doesn't manage non-standard authentication answer

### ISSUE THREAD

**Issue by DorianGeraut** [ansible/ansible#50015]
##### ANSIBLE VERSION

```paste below
ansible 2.7.2
```
##### SUMMARY
Like the get_url module, maven_artifact could get the force_basic_auth parameter, as it use the fetch_url function (from ansible.module_utils.urls). This function is based on httplib2 and only sends authentication information when a webservice responds to an initial request with a 401 status.
This option could save your day if you are dealing with servers that doesn't respond standard messages when authentification is required. In such sutiation, your request will failed even if you specify username and password as parameters to the module. 

For exemple, see the folllowing issue type. Here the remote server send you 404 error insteed of 401 when authentification is required. (of course you have to trust me when i say that the object i try to get do exist...)

##### ISSUE TYPE
TASK [springboot : Download du jar badkitt-ihm-web dmz] **********************
task path: /builds/softpussdep/integ/ansible-sad/roles/springboot/tasks/install_badkitt-ihm-web.yml:35
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_maven_artifact_payload_CkZMO_/__main__.py", line 533, in main
    download_error = downloader.download(module.tmpdir, artifact, verify_download, b_dest)
  File "/tmp/ansible_maven_artifact_payload_CkZMO_/__main__.py", line 402, in download
    raise e
```json
fatal: [front2]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "artifact_id": "badkitt-ihm-web", 
            "attributes": null, 
            "backup": null, 
            "classifier": "", 
            "content": null, 
            "delimiter": null, 
            "dest": "/appli/projects/sad/badkitt-ihm-web-releases.jar", 
            "directory_mode": null, 
            "extension": "jar", 
            "follow": false, 
            "force": null, 
            "group": null, 
            "group_id": "fr.catfactory.softpuss.dep.sad", 
            "http_agent": null, 
            "keep_name": false, 
            "mode": null, 
            "owner": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "regexp": null, 
            "remote_src": null, 
            "repository_url": "https://artifactory-dmz.catfactory.fr/artifactory/sick-maven-releases", 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "present", 
            "timeout": 10, 
            "unsafe_writes": null, 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "sick-reader-dmz", 
            "username": "sick-reader-dmz", 
            "validate_certs": false, 
            "verify_checksum": "download", 
            "version": "0.6.0.0"
        }
    }
}

MSG:

Failed to download artifact fr.catfactory.softpuss.dep.sad:badkitt-ihm-web:0.6.0.0 because of HTTP Error 404: Not Foundfor URL https://artifactory-dmz.catfactory.fr/artifactory/sick-maven-releases/fr/catfactory/softpuss/dep/sad/badkitt-ihm-web/0.6.0.0/badkitt-ihm-web-0.6.0.0.jar
```

##### COMPONENT NAME
!component=lib/ansible/modules/packaging/language/maven_artifact.py

##### ADDITIONAL INFORMATION

The parameter should bu used as it is for the get_url module
```yaml
- name: Download du jar badkitt-ihm-web dmz
  maven_artifact:
    group_id: fr.catfactory.softpuss.dep.sad
    artifact_id: badkitt-ihm-web
    username: "{{ artifactory_reader_username }}"
    password: "{{ artifactory_reader_password }}"
    force_basic_auth: true
    extension: jar
    repository_url: "{{ artifactory_url }}/sick-maven-{{ stages_or_releases }}"
    dest: /appli/projects/sad/badkitt-ihm-web.jar
    version: "{{ version_number }}"
```
