### ISSUE TITLE
Using import_role in a play results in unexpected static variable imports, even for roles that execute earlier

### ISSUE THREAD

**Issue by AndiDog** [ansible/ansible#50014]
##### SUMMARY

Using `import_role` in a play results in unexpected static variable imports, even for roles that execute "earlier" (= before `import_role:` in the playbook).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/playbook/role/__init__.py (maybe)

##### ANSIBLE VERSION

```
ansible-playbook 2.7.4
  config file = None
  configured module search path = ['/Users/asommer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.4/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.1 (default, Nov 12 2018, 09:28:23) [Clang 10.0.0 (clang-1000.11.45.5)]
```

and also with devel version.

##### CONFIGURATION

```
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT

irrelevant

##### STEPS TO REPRODUCE

Full example is here: https://github.com/AndiDog/ansible-import-bug

Copy-pasting it here since it's very short

```yaml
# printvar/defaults/main.yml
printvar_msg: "the default message"
```

```yaml
# printvar/tasks/main.yml
- debug:
    msg: "{{ printvar_msg }}"
```

```yaml
# ansible-import-bug.yml
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - include_role:
        name: printvar

    # Comment this block out to make the above role execution print "the default message".
    # Keep this in to make the above role execution print "delegated" (totally unexpected!).
    - delegate_to: "localhost" # in a real example, that would of course be a different host
      import_role:
        name: printvar
      vars:
        printvar_msg: "delegated"
```

##### EXPECTED RESULTS

Obviously, the first role should execute with the default value, the second with the explicitly overwritten value.

##### ACTUAL RESULTS

Both role executions print "delegated". This is very much unexpected since it can't make sense to a human why the first role should suddenly behave differently.

```paste below
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************************************************************************************************************************************************************************

TASK [include_role : printvar] *************************************************************************************************************************************************************************************************************

TASK [printvar : debug] ********************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "delegated"
}

TASK [printvar : debug] ********************************************************************************************************************************************************************************************************************
ok: [localhost -> localhost] => {
    "msg": "delegated"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0
```
