### ISSUE TITLE
elb_target_group doesn't update | set healthcheck path

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#50024]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

elb_target_group.py
##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = /Users/utente/Documents/Reply/bin/operations-open-workspace/ansible/ansible.cfg
  configured module search path = ['/Users/utente/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jul 23 2018, 20:22:55) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/utente/Documents/Reply/bin/operations-open-workspace/ansible/ansible.cfg) = ['/Users/utente/Documents/Reply/bin/operations-open-workspace/ansible/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/Users/utente/Documents/Reply/bin/operations-open-workspace/ansible/ansible.cfg) = /Users/utente/Documents/Reply/bin/operations-open-workspace/ansible
HOST_KEY_CHECKING(/Users/utente/Documents/Reply/bin/operations-open-workspace/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS 10.14.2

##### STEPS TO REPRODUCE

```yaml
#Var Declaration

target_groups:
  - name: test
    vpc_name: test
    protocol: https
    port: 443
    health_check_path: /server
    successful_response_codes: "200"
    target_instances:
      - test
    target_port: 443
    state: present
```

```yaml
#Playbook Tasks

- name: create targets
    set_fact:
      targets: "{{ targets|default([]) + [ {'Id': item, 'Port': target_group.target_port|default(target_group.port) } ] }}"

- name: target group
  elb_target_group:
    name: "{{ target_group.name }}"
    protocol: "{{ target_group.protocol }}"
    port: "{{ target_group.port }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    state: "{{ target_group.state }}"
    health_check_path: "{{ target_group.health_check_path}}"
    health_check_port: "{{ target_group.health_check_port }}"
    successful_response_codes: "{{ target_group.successful_response_codes}}"
    targets: "{{ targets }}"

```

##### EXPECTED RESULTS

**health_check_path** : /server

##### ACTUAL RESULTS

```yaml

ok: [localhost] => {
    "changed": false,
    "deregistration_delay_timeout_seconds": "300",
    "health_check_enabled": true,
    "health_check_interval_seconds": 30,
    "health_check_path": "/",
    "health_check_port": "443",
    "health_check_protocol": "HTTPS",
    "health_check_timeout_seconds": 5,
    "healthy_threshold_count": 5,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "deregistration_delay_timeout": null,
            "ec2_url": null,
            "health_check_interval": null,
            "health_check_path": "/server",
            "health_check_port": "443",
            "health_check_protocol": null,
            "health_check_timeout": null,
            "healthy_threshold_count": null,
            "modify_targets": true,
            "name": "https-test",
            "port": 443,
            "profile": null,
            "protocol": "https",
            "purge_tags": true,
            "region": "eu-west-1",
            "security_token": null,
            "state": "present",
            "stickiness_enabled": null,
            "stickiness_lb_cookie_duration": null,
            "stickiness_type": "lb_cookie",
            "successful_response_codes": "200",
            "tags": {},
            "target_type": "instance",
            "targets": [
                {
                    "Id": "i-017c4bb03bdfdbd91",
                    "Port": 443
                },
                {
                    "Id": "i-0c2dda357717d7b35",
                    "Port": 443
                }
            ],
            "unhealthy_threshold_count": null,
            "validate_certs": true,
            "vpc_id": "vpc-0d5184e2f3fc9042c",
            "wait": false,
            "wait_timeout": 200
        }
    },
    "load_balancer_arns": [
        "arn:aws:elasticloadbalancing:eu-west-1:432791473407:loadbalancer/app/test-alb/f92b633af947c3aa"
    ],
    "matcher": {
        "http_code": "200"
    },
    "port": 443,
    "protocol": "HTTPS",
    "slow_start_duration_seconds": "0",
    "stickiness_enabled": "false",
    "stickiness_lb_cookie_duration_seconds": "86400",
    "stickiness_type": "lb_cookie",
    "tags": {},
    "target_group_arn": "arn:aws:elasticloadbalancing:eu-west-1:432791473407:targetgroup/https-test/ba27dd69ec9ad9e1",
    "target_group_name": "https-test",
    "target_type": "instance",
    "unhealthy_threshold_count": 2,
    "vpc_id": "vpc-0d5184e2f3fc9042c"
}

```
which seems correct but the healthcheck_path , from console, is still "/".

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/elb_target_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/elb_target_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@emanuele-leopardi, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrewmcgilvray** [comment]
health_check_protocol is now required for the health_check_path to be set .. i got bitten too :-)
https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/cloud/amazon/elb_target_group.py#L428

**Comment by randlet** [comment]
Thank you @andrewmcgilvray that fixed the issue for me too.

**Comment by ghost** [comment]
@andrewmcgilvray , thanks for pointing this out! I've corrected my code as follows

```yaml

- name: target group
  elb_target_group:
    name: "{{ target_group.name }}"
    protocol: "{{ target_group.protocol }}"
    port: "{{ target_group.port }}"
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    state: "{{ target_group.state }}"
    health_check_protocol: "{{ target_group.health_check_protocol| default(target_group.protocol) }}"
    health_check_path: "{{ target_group.health_check_path|default(aws_default_target_group_health_check_path) }}"
    health_check_port: "{{ target_group.health_check_port|default(target_group.port) }}"
    successful_response_codes: "{{ target_group.successful_response_codes|default(aws_default_target_group_successful_response_codes)}}"
    targets: "{{ targets|default([]) }}"
```
