### ISSUE TITLE
ios_config enchancement, allow restorable config, remove non-config lines from return

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#50029]
##### SUMMARY
When a `backup` config of an IOS / IOS-XE device is done, there is a line in the config ```Building configuration...` which is not a legitimate config, meaning we can't do a restore from the config that is returned.  The means playbooks get more complicated, in the workshop we are doing this today->

```
    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_config

##### ADDITIONAL INFORMATION
This feature could be an additional parameter, something intuitive and easy like

```
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
        remove_extraneous: true
      register: config_output
```

imho we should make this the default
