### ISSUE TITLE
feat/os_object - timeout

### ISSUE THREAD

**Issue by Antoine-Sevec** [ansible/ansible#50075]
##### SUMMARY
It should also be possible to add the possibility of automatic deletion with a timeout on the uploaded objects either by a date or duration

##### TYPE OF PROBLEM
Today there is an impossibility to add a date or duration before delete of the uploaded object

New parameter: timeout

##### COMPONENT NAME
lib/ansible/modules/cloud/openstack/os_object.py

##### ADDITIONAL INFORMATION
Ability to add an automatic suppression based on a given time or date to avoid high storage costs.

```yaml
os_object:
  auth:
    auth_url: "https://URL"
    username: "user"
    password: "pass"
    project_name: "project"
  state: present
  name: "test.txt"
  container: "container"
  region_name: "ABC"
  filename: "/local/test.txt"
  timeout: 3600 or timestamp
```
