### ISSUE TITLE
ec2_group fails in diff mode

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#50072]
##### SUMMARY

ec2_group fails in diff mode
May be related to #19889

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = None
  configured module search path = ['/Users/hryamzik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 28 2018, 11:51:54) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
[defaults]
inventory = inventory-local
retry_files_save_path = retry
ansible_managed = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
nocows = 1
callback_whitelist = timer
stdout_callback = skippy
display_skipped_hosts = False
force_handlers = True
host_key_checking = False
vault_password_file = vaultkeychain
roles_path = ../roles

[ssh_connection]
pipelining = False
# control_path = %(directory)s/%%h-%%p-%%r
control_path = %(directory)s/%%h-%%p
```

##### OS / ENVIRONMENT

Mac OS

##### STEPS TO REPRODUCE

```yaml
- hosts: no_ssh_hosts
  gather_facts: no
  tasks:
      - block:
          - name: get facts about first security group
            ec2_group_facts:
                profile: "{{ aws_profile }}"
                region: us-west-2
                filters:
                    group-id: "{{ ec2_security_group_ids.split(',')[0] }}"
            register: first_security_group

          - name: add ssh access
            ec2_group:
                profile: "{{ aws_profile }}"
                name: "{{ item.group_name }}"
                description: "{{ item.description }}"
                vpc_id: "{{ ec2_vpc_id }}"
                purge_rules: no
                region: us-west-2
                rules:
                  - proto: tcp
                    ports: [22]
                    cidr_ip: 0.0.0.0/0
                    rule_desc: temporary ssh for ansible
            check_mode: no
            run_once: yes
            with_items: "{{ play_hosts | map('extract',hostvars,'first_security_group')|map(attribute='security_groups.0') | list | unique }}"
            loop_control:
                label: "{{ item.group_name }}"
        become: no
        delegate_to: localhost
```

Running without diff mode is fine, diff errors out.

##### EXPECTED RESULTS

```
TASK [add ssh access] **************************************************************************************************************************************************************************************
changed...
```

##### ACTUAL RESULTS

```paste below
failed: [somehost -> localhost] (item=some_host-us-west-2) => {"changed": false, "item": {"description": "Managed by Terraform", "group_id": "sg-17fc0c6d", "group_name": "some_host-us-west-2", "ip_permissions": [{"from_port": 8080, "ip_protocol": "tcp", "ip_ranges": [{"cidr_ip": "10.10.10.0/8"}, {"cidr_ip": "10.20.10.0/12"}, {"cidr_ip": "10.50.10.0/16"}], "ipv6_ranges": [], "prefix_list_ids": [], "to_port": 8080, "user_id_group_pairs": []}, {"from_port": 53, "ip_protocol": "udp", "ip_ranges": [{"cidr_ip": "10.10.10.0/8"}, {"cidr_ip": "10.20.10.0/12"}, {"cidr_ip": "10.50.10.0/16"}], "ipv6_ranges": [], "prefix_list_ids": [], "to_port": 53, "user_id_group_pairs": []}, {"from_port": 53, "ip_protocol": "tcp", "ip_ranges": [{"cidr_ip": "10.10.10.0/8"}, {"cidr_ip": "10.20.10.0/12"}, {"cidr_ip": "10.50.10.0/16"}], "ipv6_ranges": [], "prefix_list_ids": [], "to_port": 53, "user_id_group_pairs": []}], "ip_permissions_egress": [{"ip_protocol": "-1", "ip_ranges": [{"cidr_ip": "0.0.0.0/0"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "owner_id": "123456789102", "tags": {"Name": "some_host-us-west-2", "Owner": "someowner"}, "vpc_id": "someid"}, "module_stderr": "/Users/hryamzik/.ansible/tmp/ansible-tmp-1545123494.5145578-186404250214165/AnsiballZ_ec2_group.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/Users/hryamzik/.ansible/tmp/ansible-tmp-1545123494.5145578-186404250214165/AnsiballZ_ec2_group.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/Users/hryamzik/.ansible/tmp/ansible-tmp-1545123494.5145578-186404250214165/AnsiballZ_ec2_group.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/hryamzik/.ansible/tmp/ansible-tmp-1545123494.5145578-186404250214165/AnsiballZ_ec2_group.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/var/folders/79/szcjwt696vj84xrt7n_khg8w0000gn/T/ansible_ec2_group_payload_x_67rblm/__main__.py\", line 1182, in <module>\n  File \"/var/folders/79/szcjwt696vj84xrt7n_khg8w0000gn/T/ansible_ec2_group_payload_x_67rblm/__main__.py\", line 1174, in main\n  File \"/var/folders/79/szcjwt696vj84xrt7n_khg8w0000gn/T/ansible_ec2_group_payload_x_67rblm/__main__.py\", line 955, in get_diff_final_resource\n  File \"/var/folders/79/szcjwt696vj84xrt7n_khg8w0000gn/T/ansible_ec2_group_payload_x_67rblm/__main__.py\", line 943, in get_final_rules\nTypeError: '<' not supported between instances of 'dict' and 'dict'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
