### ISSUE TITLE
mysql_db present/dump creates incorrect mysql command line when using ssl_ca attribute

### ISSUE THREAD

**Issue by robpblake** [ansible/ansible#50096]
##### SUMMARY
I need to import a SQL dump to a MySQL database that has SSL connections enforced. To do this I created the following task definition:

```yaml
mysql_db:
 name: 'my_db'
 state: import
 target: '/dumps/db-dump.sql.gz'
 login_host: '{{ db_host }}'
 login_user: '{{ db_user }}'
 login_password: '{{ db_password }}'
 ssl_ca: '/path/to/ca.pem'
```

If I run this against any database that does not enforce SSL connections and omit the `ssl_ca` attribute, it works perfectly. If I re-add the `ssl_ca` attribute and run it against a database that requires SSL connections, it fails with the following error:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "\ngzip: stdout: Broken pipe\n"}
```

Taking a look at the code for the `mysql_db` module, it fails to build the command line correctly when either importing or dumping the database and the `ssl_ca` option is supplied. In particular the following is  incorrect on line 147 and 200 of [mysql_db.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_db.py):

```
if ssl_cert is not None:
        cmd += " --ssl-ca=%s" % pipes.quote(ssl_ca)
```

This should be:

```
if ssl_ca is not None:
        cmd += " --ssl-ca=%s" % pipes.quote(ssl_ca)
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_db
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
sh-4.2$ ansible-config dump --only-changed
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = !all
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/ansible-local-79114Gevau6
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = /tmp
```

##### OS / ENVIRONMENT

- RHEL 7

##### STEPS TO REPRODUCE

```yaml
mysql_db:
 name: 'my_db'
 state: import
 target: '/dumps/db-dump.sql.gz'
 login_host: '{{ db_host }}'
 login_user: '{{ db_user }}'
 login_password: '{{ db_password }}'
 ssl_ca: '/path/to/ca.pem'
```

##### EXPECTED RESULTS

I expect the database dump to be imported.

##### ACTUAL RESULTS

The database import fails with:

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "\ngzip: stdout: Broken pipe\n"}
```
