### ISSUE TITLE
Changing user primary group seems to not allow user add back to that as supplementary group? 

### ISSUE THREAD

**Issue by nickstenning** [ansible/ansible#5010]
I don't believe the user module is currently idempotent in its action when it is asked to change a user's primary group and move that same group to the additional groups list in the same ansible run.

To reproduce, create a user called `fred` with primary group `sudo`, say. Also create a group called `fred`, which we'll use in a moment. You could, of course, do so with a playbook like this:

``` yaml

---
- hosts: all
  tasks:
    - action: group name=fred state=present
    - action: user name=fred group=sudo state=present
```

After running that, here's the output of `id fred`:

```
uid=1000(fred) gid=27(sudo) groups=27(sudo)
```

Now change the playbook to read as follows:

``` yaml

---
- hosts: all
  tasks:
    - action: group name=fred state=present
    - action: user name=fred group=fred groups=sudo state=present
```

I would expect the action of this playbook to be to change the primary group of `fred` to `fred`, and to add him back to the `sudo` group in a single ansible run. Unfortunately, that's not what I see. After running the playbook once, here's `id fred` again:

```
uid=1000(fred) gid=1000(fred) groups=1000(fred)
```

And after running the playbook a second time:

```
uid=1000(fred) gid=1000(fred) groups=1000(fred),27(sudo)
```

_Tested with ansible 1.3.x and 1.4_

**Comment by mpdehaan** [comment]
Thanks for the report, I've updated the description a bit to better reflect what it sounds like you are reporting.

In queue to be reproduced.

**Comment by jctanner** [comment]
Reproduced, working on a fix.

```
- hosts: el6.lab.net
  gather_facts: False
  tasks:

    - shell: userdel fred; groupdel fred ; groupdel sudo 
      ignore_errors: True
    - shell: rm -rf /home/fred ; rm -rf /var/spool/mail/fred
      ignore_errors: True

    - action: group name=fred state=present
    - action: group name=sudo state=present
    - action: user name=fred group=sudo state=present

    - command: id fred
      register: return
    - command: test "{{ return.stdout }}" = 'uid=506(fred) gid=510(sudo) groups=510(sudo)'

    # first call
    - action: user name=fred group=fred groups=sudo state=present
    - shell: id fred
      register: return
    - command: test "{{ return.stdout }}" = 'uid=506(fred) gid=509(fred) groups=509(fred)'
      ignore_errors: True

    # second call
    - action: user name=fred group=fred groups=sudo state=present
    - shell: id fred
      register: return
    - command: test "{{ return.stdout }}" = 'uid=506(fred) gid=509(fred) groups=509(fred),510(sudo)'
      ignore_errors: True
```
