### ISSUE TITLE
{{ ansible_distribution_release }} returns wrong result

### ISSUE THREAD

**Issue by leaf-node** [ansible/ansible#50102]
##### SUMMARY

When using `{{ ansible_distribution_release }}` in a role, `flidas` (a release of Trisquel, like `xenail` is for Ubuntu) should be returned, but `trisquel` is returned instead. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

best guess: core

##### ANSIBLE VERSION

```
2.7.5-1ppa~xenial
```

##### CONFIGURATION

sorry, I've already downgraded the package.

##### OS / ENVIRONMENT

Trisquel flidas (8.0), based on Ubuntu Xenial

##### STEPS TO REPRODUCE

```yaml
- name: install main apt repo
  apt_repository:
    repo: deb http://mirror.fsf.org/trisquel/ {{ ansible_distribution_release }} main
    filename: 'trisquel-repos-added-by-ansible'
    state: present
    update_cache: yes
  when:
    - "'mirror.fsf.org' != ansible_fqdn"
```

##### EXPECTED RESULTS

````
deb http://mirror.fsf.org/trisquel/ flidas main
````

##### ACTUAL RESULTS

````
deb http://mirror.fsf.org/trisquel/ trisquel main
````
