### ISSUE TITLE
connect() got an unexpected keyword argument 'ssh_config'

### ISSUE THREAD

**Issue by siemsen** [ansible/ansible#50119]
##### SUMMARY
I'm trying to write a playbook that will simply do a "show version" command on my routers. I get this error for all my routers: "connect() got an unexpected keyword argument 'ssh_config'". This looks like a coding bug to me.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_command

##### ANSIBLE VERSION

```paste below
2.7.9
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/usr/local/ansible/siemsen/playbooks/ansible.cfg) = [u'/usr/local/ansible/siemsen/playbooks/inventory/hosts']
DEFAULT_LOG_PATH(/usr/local/ansible/siemsen/playbooks/ansible.cfg) = /usr/home/siemsen/tmp/ansible.log
DEFAULT_REMOTE_USER(/usr/local/ansible/siemsen/playbooks/ansible.cfg) = viewer
```

##### OS / ENVIRONMENT

Debian 8.11
Junipers are running JUNOS 16.1R6-S3.1, JUNOS 15.1R5.5, perhaps some others

##### STEPS TO REPRODUCE

```yaml
---
- hosts: junos
#  connection: local
  connection: network_cli
  
  tasks:
    - name: show version
      junos_command:
        commands: show version
      register: show_version

    - debug:
        msg: "{{show_version}}"
```

##### EXPECTED RESULTS

I expect to see the output of "show version" for each router. If I change the playbook to use "ios_command" instead of "junos_command", and I get the expected output for 6 out of 21 of the routers, and I get errors like these for the others:
fatal: [ml-mr-j5-es.unet]: FAILED! => {"msg": "paramiko: The authenticity of host '128.117.2.78' can't be established.\nThe ssh-rsa key fingerprint is 30ac82d8aa5a7029195f21e537512454."}

##### ACTUAL RESULTS

```paste below
The reason I'm not providing anything here is that it looks like the "unexpected keyword" error is a true coding error, in the code, that should never happen. I suspect I may somehow have a paramiko library that isn't compatible with the ansible code or something. I'd be happy to provide more information if needed.
```
