### ISSUE TITLE
lineinfile/blockinfile only runs once when looping

### ISSUE THREAD

**Issue by DrHashi** [ansible/ansible#50110]
##### ISSUE TYPE
- Bug Report

lineinfile/blockinfile only adds the first variable when looping through a list

##### COMPONENT NAME
lineinfile and blockinfile

##### ANSIBLE VERSION

```paste below

ansible 2.7.0
  config file = /opt//deploy/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/opt/deploy/ansible.cfg) = -o ForwardAgent=yes
DEFAULT_ROLES_PATH(/opt/deploy/ansible.cfg) = [u'/opt/deploy/roles']
DEFAULT_TRANSPORT(/opt/deploy/ansible.cfg) = ssh
HOST_KEY_CHECKING(/opt/deploy/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/deploy/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### STEPS TO REPRODUCE

run blockinfile or lineinfile more than once while looping through a list

```yaml

vars:
  whitelisted_ips:
    - 10.208.225.130
    - 10.208.225.131
tasks:
  - name: whitelisting ips
    lineinfile:
      path: /etc/hosts.allow
      regexp: '^sshd : '
      line: 'sshd : {{ item }}'
      state: present
    loop: "{{ whitelisted_ips }}"

OR

tasks:
  - name: whitelisting ips
    blockinfile:
      dest: /etc/hosts.allow
      block: |
        sshd : {{ item }}
    loop: "{{ whitelisted_ips }}"

```

##### EXPECTED RESULTS

sshd : 10.208.225.130
sshd : 10.208.225.131

OR

# BEGIN ANSIBLE MANAGED BLOCK
sshd : 10.208.225.130
sshd : 10.208.225.131
# END ANSIBLE MANAGED BLOCK

##### ACTUAL RESULTS

sshd : 10.208.225.130

or

# BEGIN ANSIBLE MANAGED BLOCK
sshd : 10.208.225.130
# END ANSIBLE MANAGED BLOCK

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/files/lineinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/lineinfile.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ahtik @dhozac @samdoran @yaegashi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by eriweb** [comment]
Your regexp is matching the newly created line.
Loop item number 1 creates a line that looks like
`sshd : 10.208.225.130`
Which matches the regexp `^sshd : ` for loop item number 2

Depending on what you want to achieve you could do it like this:
```
  - name: whitelisting ips
    lineinfile:
      path: /etc/hosts.allow
      regexp: '^sshd : {{ item }}'
      line: 'sshd : {{ item }}'
      state: present
    loop: "{{ whitelisted_ips }}"
```
Which will try to match the actual IP as well
