### ISSUE TITLE
get_url + cookie: accept licence not downloading ansible < 2.6

### ISSUE THREAD

**Issue by leupo** [ansible/ansible#50147]
##### SUMMARY
get_url + cookie: accept licence does not download file correctly with ansible < 2.6. I tried nearly every Version from 2.4.3.0 up to 2.6 with virtual envs.
Edit: 
**From Version 2.6 this bug doesnt occur.**
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
```
ansible 2.5.14
  executable location = /tmp/py_venv/ansible_2.4.3.0_python2/bin/ansible-playbook
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION

```
nothing changed
```

##### OS / ENVIRONMENT
Linux/Mac OS

##### STEPS TO REPRODUCE

This playbook:
```
---
  - hosts: localhost
    tasks:
    - name: get JDK tarball (as tar.gz file)
      get_url:
        url: "http://download.oracle.com/otn-pub/java/jdk/11.0.1+13/90cf5d8f270a4347a95050320eef3fb7/jdk-11.0.1_linux-x64_bin.tar.gz"
        headers:
          Cookie: 'oraclelicense=accept-securebackup-cookie'
        dest: "/tmp/123.tar.gz"
      delegate_to: localhost
      run_once: true
```

##### EXPECTED RESULTS
```
file /tmp/123.tar.gz
/tmp/123.tar.gz: gzip compressed data, last modified: Sat Oct  6 12:15:53 2018, from Unix, original size 302632960
```

##### ACTUAL RESULTS
```
...
TASK [get JDK tarball (as tar.gz file)] ********************************************************************************
changed: [localhost -> localhost]
...
```

```
file /tmp/123.tar.gz
/tmp/123.tar.gz: HTML document text, ASCII text, with very long lines, with CRLF line terminators
```
