### ISSUE TITLE
Lookup in vars file traceback (if invalid file path supplied to lookup)

### ISSUE THREAD

**Issue by nickstenning** [ansible/ansible#5014]
Consider the following `group_vars/all.yml`:

``` yaml

---
users_active:
  - name: foo
    group: foo
    authorized:
      - "{{ lookup('file', 'path/to/pubkey.pub') }}"
```

And the following playbook

``` yaml

---
- hosts: all
  tasks:
    - name: DEBUG users
      action: debug msg="{{ item }}"
      with_items: users_active
```

I would expect output similar to the following (assuming `path/to/pubkey.pub` was correct):

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [XX.XX.XX.XX]

TASK: [DEBUG users] ***********************************************************
ok: [XX.XX.XX.XX] => (item={'group': 'foo', 'name': 'foo', 'authorized': ['ssh-rsa AAAAB3Nza...dCOw== foo']}) => {
    "item": {
        "authorized": [
            "ssh-rsa AAAAB3Nza...dCOw== foo"
        ],
        "group": "foo",
        "name": "foo"
    },
    "msg": "{'group': 'foo', 'name': 'foo', 'authorized': ['ssh-rsa AAAAB3Nza...dCOw== foo']}"
}

PLAY RECAP ********************************************************************
XX.XX.XX.XX             : ok=2    changed=0    unreachable=0    failed=0
```

Instead, I see output as below. It seems that using a lookup in `group_vars/all.yml` completely breaks `with_items` to the extent that it no longer correctly retrieves the structured data for the items:

```
PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [XX.XX.XX.XX]

TASK: [DEBUG users] ***********************************************************
ok: [XX.XX.XX.XX] => (item=users_active) => {
    "item": "users_active",
    "msg": "users_active"
}

PLAY RECAP ********************************************************************
XX.XX.XX.XX             : ok=2    changed=0    unreachable=0    failed=0
```

If you now edit the vars file and replace the lookup with a simple string public key, the output will be as expected (the first playbook run above).

_Tested with Ansible 1.3.4 and 1.4_
