### ISSUE TITLE
Issue while activating a scaling group in alibaba cloud using ansible code

### ISSUE THREAD

**Issue by vutukuribharat** [ansible/ansible#50152]
I am trying to activate a scaling group in Alibaba cloud using ansible(yaml)code and facing issues while executing the code. I used alicloud_ess_group module in my code for activating the group and facing issues in it.

##### ISSUE TYPE
- Bug Report

ANSIBLE VERSION

ansible  2.3.1.0
python version = 2.7.5

 STEPS TO REPRODUCE:
YAML CODE:
```yaml
---
- name: basic provisioning example
  hosts: localhost
  connection: local
  vars:
    alicloud_access_key: "******************"
    alicloud_secret_key: "********************"
    alicloud_region: "ap-southeast-1"
    group_id: asg-t4n5ihynn27dk3d2m70s
    configuration_id: asc-t4nayc7z1b81l6nio2sf

  tasks:
    - name: active a specified scaling group
      ali_ess_group:
        alicloud_access_key: '{{ alicloud_access_key }}'
        alicloud_secret_key: '{{ alicloud_secret_key }}'
        alicloud_region: '{{ alicloud_region }}'
        configuration_id: '{{ configuration_id }}'
        id: '{{ group_id }}'
        state: inactive
```

 EXPECTED RESULTS

we will have a scaling group being enabled as mentioned in the below screen shots(output)

![output](https://user-images.githubusercontent.com/10670187/50225691-3ab7a580-03c7-11e9-8a7f-a3dd7fa680cd.png)

ACTUAL RESULTS

But we are facing the below errors:
```
Fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "implementation error: unknown type <type 'str'> requested for configuration_id"} 
```
screen shot for the above error:

![screenshot_1](https://user-images.githubusercontent.com/10670187/50225805-85392200-03c7-11e9-8e6c-4a6807ed5dcb.png)

Also, we have faced the depreciation warnings though even after setting it to both true and false(screen shot_2.png)

![screenshot_2](https://user-images.githubusercontent.com/10670187/50225473-a3eae900-03c6-11e9-8db9-d96e3b152785.png)
). 

Similarly, we are also facing issues while Launching and Deleting the scaling configuration and also while creating and deleting the scaling groups as well. 

modules used for scaling configuration: alicloud_ess_configuration
modules used for scaling groups: alicloud_ess_group
