### ISSUE TITLE
vmware_host_datastore - Datastore on a SAN device presented to several ESXi nodes

### ISSUE THREAD

**Issue by xenlo** [ansible/ansible#50161]
##### SUMMARY
When you deploy the ESXi nodes (more than one) for a new VMware environment, at some point you should mount the datastore. For that we use the `vmware_host_datastore` module. The issue comes when this module run in parallel on our 3 ESXi nodes that all have the same SAN volume presented to them. The 3 nodes try at the same time to create the partition and the FS on the same SAN volume. Which of course leads to a 1 success and 2 failures that stops the run of the playbook.

As it is not possible to run a single task sequentially (`serial: 1`), the workaround I found was to call `vmware_host_datastore` module twice in my playbook. First with a `run_once: true` to ensure that only one node will deal with the partitioning and file system creation. Then a second time to allow the 2 other node to proceed in the mount part. Unfortunately this was failing too! It seems that the module don't proceed into a filesystem rescan before trying to do anything. So the fix for my workaround is to add an extra command task (`esxcli storage filesystem rescan`) between the two calls to `vmware_host_datastore`.

So for me there is 2 problems spotted by this issue:
- It may have a difference between the real status on the disk volumes and the status fetched at the beginning of the task (`esxcli storage filesystem list`). It looks to me the easier to fix by always start with a forced `rescan`.
- The concurrent run of the task that in the end act on the same disk object. This may need a redesign? Maybe by splitting this module in 2 modules one dealing with the underlying part (partition and FS) and the second for the mount… This could answer the [feature request 47521](https://github.com/ansible/ansible/issues/47521) to be able to only format a LUN.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/modules/cloud/vmware/vmware_host_datastore.py`

##### ANSIBLE VERSION

```
ansible 2.7.4
  config file = $HOME/Projects/97/etc/ansible.cfg
  configured module search path = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/modules', u'$HOME/Projects/97/library']
  ansible python module location = $HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ansible
  executable location = $HOME/.virtualenvs/97/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
CACHE_PLUGIN($HOME/Projects/97/etc/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION($HOME/Projects/97/etc/ansible.cfg) = $HOME/.ansible/facts/
CACHE_PLUGIN_TIMEOUT($HOME/Projects/97/etc/ansible.cfg) = 3600
DEFAULT_ACTION_PLUGIN_PATH(env: ANSIBLE_ACTION_PLUGINS) = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/callbacks']
DEFAULT_FILTER_PLUGIN_PATH(env: ANSIBLE_FILTER_PLUGINS) = [u'$HOME/Projects/97/plugins/filter']
DEFAULT_GATHERING($HOME/Projects/97/etc/ansible.cfg) = smart
DEFAULT_HOST_LIST($HOME/Projects/97/etc/ansible.cfg) = [u'$HOME/Projects/97/inventories/T04', u'$HOME/Projects/97/inventories/setupenv']
DEFAULT_LOG_PATH($HOME/Projects/97/etc/ansible.cfg) = $HOME/.ansible/log/ansible.log
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/modules', u'$HOME/Projects/97/library']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'$HOME/Projects/97/roles.galaxy', u'$HOME/Projects/97/roles']
DEFAULT_STDOUT_CALLBACK($HOME/Projects/97/etc/ansible.cfg) = yaml
GALAXY_ROLE_SKELETON(env: ANSIBLE_GALAXY_ROLE_SKELETON) = $HOME/Projects/97/etc/skel/default
GALAXY_ROLE_SKELETON_IGNORE($HOME/Projects/97/etc/ansible.cfg) = [u'']
HOST_KEY_CHECKING($HOME/Projects/97/etc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
- VMWare ESXi 6.5
- VMWare vCenter 6.5
- pyvmomi==6.7.1
- SAN: HPe 3par

##### STEPS TO REPRODUCE
**Prereqs:**
- Having VLUN(s) presented to at least 2 ESXi nodes. 
- No partition, no FS on the presented VLUN(s)

**Initial attempt:**
```yaml
- name: Setup the ESXi cluster
  hosts: esxi-nodes

  vars:
    […]

  tasks:
    […]
    - name: Create the partition and the file system and mount it
      vmware_host_datastore:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ password_3par }}"
        datacenter_name: "{{ datacenter_name }}"
        esxi_hostname: "{{ ansible_host }}"
        datastore_name: "3PAR-VMFS01"
        datastore_type: "vmfs"
        vmfs_device_name: "naa.60002000000000000000000000000002"
        state: present
        vmfs_version: 6
      delegate_to: localhost
      run_once: true
```

**Working Workaround:**
```yaml
- name: Setup the ESXi cluster
  hosts: esxi-nodes

  vars:
    […]

  tasks:
    […]
    - name: Create the partition and the file system (on the first esx-node)
      vmware_host_datastore:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ password_3par }}"
        datacenter_name: "{{ datacenter_name }}"
        esxi_hostname: "{{ ansible_host }}"
        datastore_name: "3PAR-VMFS01"
        datastore_type: "vmfs"
        vmfs_device_name: "naa.60002000000000000000000000000002"
        state: present
        vmfs_version: 6
      delegate_to: localhost
      run_once: true

    - name: Rescan the Filesystem on all other esx-nodes
      command: |
        esxcli storage filesystem rescan

    - name: Mount VMFS datastores on the other esx-nodes
      vmware_host_datastore:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ password_3par }}"
        datacenter_name: "{{ datacenter_name }}"
        esxi_hostname: "{{ ansible_host }}"
        datastore_name: "3PAR-VMFS01"
        datastore_type: "vmfs"
        vmfs_device_name: "naa.60002000000000000000000000000002"
        state: present
        vmfs_version: 6
      delegate_to: localhost
```
##### STATE ON ESXi NODES BEFORE CALLING THE MODULE
```
user@localhost:~$ command="esxcli storage filesystem list | grep \"3PAR-VMFS01\|^Mount Point\|^-----------\""
user@localhost:~$ for i in $(seq 1 3); do echo "=== esx-node0${i} ==="; ssh -l root esx-node0${i} ${command}; done
=== esx-node01 ===
Mount Point                                        Volume Name        UUID                                 Mounted  Type             Size           Free
-------------------------------------------------  -----------------  -----------------------------------  -------  ------  -------------  -------------
=== esx-node02 ===
Mount Point                                        Volume Name        UUID                                 Mounted  Type             Size           Free
-------------------------------------------------  -----------------  -----------------------------------  -------  ------  -------------  -------------
=== esx-node03 ===
Mount Point                                        Volume Name        UUID                                 Mounted  Type             Size           Free
-------------------------------------------------  -----------------  -----------------------------------  -------  ------  -------------  -------------
user@localhost:~$ command="ls -l /vmfs/devices/disks/naa.6000*"
user@localhost:~$ for i in $(seq 1 3); do echo "=== esx-node0${i} ==="; ssh -l root esx-node0${i} ${command}; done
=== esx-node01 ===
-rw-------    1 root     root     3298534883328 Dec 20 10:42 /vmfs/devices/disks/naa.60002000000000000000000000000002
=== esx-node02 ===
-rw-------    1 root     root     3298534883328 Dec 20 10:42 /vmfs/devices/disks/naa.60002000000000000000000000000002
=== esx-node03 ===
-rw-------    1 root     root     3298534883328 Dec 20 10:42 /vmfs/devices/disks/naa.60002000000000000000000000000002
```
##### EXPECTED RESULTS
**Ansible run**:
```
TASK [Create the partition and the file system and mount it] *************************************
changed: [esx-node01 -> localhost] => (item=naa.60002000000000000000000000000002)
changed: [esx-node02 -> localhost] => (item=naa.60002000000000000000000000000002)
changed: [esx-node03 -> localhost] => (item=naa.60002000000000000000000000000002)
```
Where one `changed` status is for the partition, the FS and the mount, and on the two other `changed` status for the mount only.
**States on the ESXi nodes**:
```
user@localhost:~$ command="esxcli storage filesystem list | grep \"3PAR-VMFS02\|^Mount Point\|^-----------\""
user@localhost:~$ for i in $(seq 1 3); do echo "=== esx-node0${i} ==="; ssh -l root esx-node0${i} ${command}; done
=== esx-node01 ===
Mount Point                                        Volume Name        UUID                                 Mounted  Type             Size           Free
-------------------------------------------------  -----------------  -----------------------------------  -------  ------  -------------  -------------
/vmfs/volumes/5c1b746d-b210425e-4533-5820b1e38110  3PAR-VMFS01        5c1b746d-b210425e-4533-5820b1e38110     true  VMFS-6  2198754820096  2197210267648
=== esx-node02 ===
Mount Point                                        Volume Name        UUID                                 Mounted  Type             Size           Free
-------------------------------------------------  -----------------  -----------------------------------  -------  ------  -------------  -------------
/vmfs/volumes/5c1b746d-b210425e-4533-5820b1e38110  3PAR-VMFS01        5c1b746d-b210425e-4533-5820b1e38110     true  VMFS-6  2198754820096  2197210267648
=== esx-node03 ===
Mount Point                                        Volume Name        UUID                                 Mounted  Type             Size           Free
-------------------------------------------------  -----------------  -----------------------------------  -------  ------  -------------  -------------
/vmfs/volumes/5c1b746d-b210425e-4533-5820b1e38110  3PAR-VMFS01        5c1b746d-b210425e-4533-5820b1e38110     true  VMFS-6  2198754820096  2197210267648

user@localhost:~$ command="ls -l /vmfs/devices/disks/naa.6000*"
user@localhost:~$ for i in $(seq 1 3); do echo "=== esx-node0${i} ==="; ssh -l root esx-node0${i} ${command}; done
=== esx-node01 ===
-rw-------    1 root     root     3298534883328 Dec 20 10:54 /vmfs/devices/disks/naa.60002000000000000000000000000002
-rw-------    1 root     root     3298533817856 Dec 20 10:54 /vmfs/devices/disks/naa.60002000000000000000000000000002:1
=== esx-node02 ===
-rw-------    1 root     root     3298534883328 Dec 20 10:54 /vmfs/devices/disks/naa.60002000000000000000000000000002
-rw-------    1 root     root     3298533817856 Dec 20 10:54 /vmfs/devices/disks/naa.60002000000000000000000000000002:1
=== esx-node03 ===
-rw-------    1 root     root     3298534883328 Dec 20 10:54 /vmfs/devices/disks/naa.60002000000000000000000000000002
-rw-------    1 root     root     3298533817856 Dec 20 10:54 /vmfs/devices/disks/naa.60002000000000000000000000000002:1
```

##### ACTUAL RESULTS
**Initial attempt:**
```
TASK [Create the partition and the file system (on the first esx-node)] *************************************
failed: [esx-node02 -> localhost] (item=naa.60002000000000000000000000000002) => changed=false
  index: 1
  item: naa.60002000000000000000000000000002
  msg: 'Cannot mount datastore 3PAR-VMFS01 on host esx-node02.domain.org : An error occurred during host configuration.'
failed: [esx-node03 -> localhost] (item=naa.60002000000000000000000000000002) => changed=false
  index: 1
  item: naa.60002000000000000000000000000002
  msg: 'Cannot mount datastore 3PAR-VMFS01 on host esx-node03.domain.org : An error occurred during host configuration.'
changed: [esx-node01 -> localhost] => (item=naa.60002000000000000000000000000002)
        to retry, use: --limit @~/Projects/92/playground/deploy-setupenv-esxi-cluster.retry
```

**Working Workaround:**
```
[…]
TASK [Create the partition and the file system (on the first esx-node)] ************************************
changed: [esx-node01 -> localhost] => (item=naa.60002000000000000000000000000002)

TASK [Rescan the Filesystem on all other esx-nodes] ********************************************************
changed: [esx-node01]
changed: [esx-node03]
changed: [esx-node02]

TASK [Mount VMFS datastores on the other esx-nodes] ********************************************************
ok: [esx-node01 -> localhost] => (item=naa.60002000000000000000000000000002)
ok: [esx-node03 -> localhost] => (item=naa.60002000000000000000000000000002)
ok: [esx-node02 -> localhost] => (item=naa.60002000000000000000000000000002)
[…]
```
