### ISSUE TITLE
win_updates incorrectly reports changed.

### ISSUE THREAD

**Issue by puchalakd** [ansible/ansible#50185]
##### SUMMARY

Module win_updates is reporting "changed": false after make a change (installing update).

What I got was:
**"changed": false,
"installed_update_count": 1,** 

I use change field for restarting monitoring software agent (this clear the agent cache for windows updates) when developing that playbook on January 2017. 
It was working fine on older version some time ago. I cannot say exactly when the problem happened, because this is on customer systems.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: win_updates

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/puchalakd/Ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/puchalakd/Ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=180s
ANSIBLE_SSH_CONTROL_PATH(/home/puchalakd/Ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/home/puchalakd/Ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/puchalakd/Ansible/ansible.cfg) = [u'/home/puchalakd/Ansible/hosts']
DEFAULT_LOG_PATH(/home/puchalakd/Ansible/ansible.cfg) = /home/puchalakd/Ansible/logs/ansible.
DEFAULT_MANAGED_STR(/home/puchalakd/Ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H
DEFAULT_TRANSPORT(/home/puchalakd/Ansible/ansible.cfg) = smart
DEPRECATION_WARNINGS(/home/puchalakd/Ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

target OS: Windows Server 2012 R2

##### STEPS TO REPRODUCE

Try to install windows updates using win_updates, register output variable of that task and look at the changed field.

```yaml
---
- hosts: windows
  tasks:
  - name: Install updates 
    win_updates:
      category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
      state: installed
    tags: [windows, windows_updates]
    register: update_result

  - name: restart check_mk agent to invalidate cached results
    win_service:
      name: Check_MK_Agent
      state: restarted
      start_mode: auto
    when: update_result.changed == true
    tags: [windows, windows_updates]

  - debug: var=update_result

```

##### EXPECTED RESULTS

Task should returns **changed: true** after installing any updates (and making changes to the system).

The output should looked like this.

After installing updates I should get something like:
TASK [Install updates] ******************************************************
**changed**: [system1.example.com]
...
TASK [debug] ******************************************************************************************************************
ok: [system1.example.com] => {
    "update_result": {
        "changed": **true**, 
        "failed": false, 
        "failed_update_count": 0, 
        "filtered_updates": {}, 
        "found_update_count": 1, 
        "installed_update_count": 1, 

##### ACTUAL RESULTS

Task is reporting "changed": false after make a change (installing update).

```paste below
Full output of the task below.
TASK [Install updates] ******************************************************
ok: [system1.example.com]
...
TASK [debug] ******************************************************************************************************************
ok: [system1.example.com] => {
    "update_result": {
        "changed": false, 
        "failed": false, 
        "failed_update_count": 0, 
        "filtered_updates": {}, 
        "found_update_count": 1, 
        "installed_update_count": 1, 
        "reboot_required": false, 
        "updates": {
            "cb01b215-6879-4983-8e1f-a20742ca0dcf": {
                "id": "cb01b215-6879-4983-8e1f-a20742ca0dcf", 
                "installed": true, 
                "kb": [
                    "4483187"
                ], 
                "title": "2018-12 Skumulowana aktualizacja zabezpieczeń Internet Explorer 11 w systemie Windows Server 2012 R2 dla systemów opartych na architekturze x64(KB4483187)"
            }
        }
    }
}
```
