### ISSUE TITLE
vmware_host_datastore - Don't show 'changed' status when it does only the mount part

### ISSUE THREAD

**Issue by xenlo** [ansible/ansible#50195]
##### SUMMARY
When I use the `vmware_host_datastore` module to mount an device disk with a partition and a vmfs file system, the module proceeded well into mount, but don't show a '_changed_' status.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/modules/cloud/vmware/vmware_host_datastore.py`

##### ANSIBLE VERSION
```
ansible 2.7.4
  config file = $HOME/Projects/97/etc/ansible.cfg
  configured module search path = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/modules', u'$HOME/Projects/97/library']
  ansible python module location = $HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ansible
  executable location = $HOME/.virtualenvs/97/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
CACHE_PLUGIN($HOME/Projects/97/etc/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION($HOME/Projects/97/etc/ansible.cfg) = $HOME/.ansible/facts/
CACHE_PLUGIN_TIMEOUT($HOME/Projects/97/etc/ansible.cfg) = 3600
DEFAULT_ACTION_PLUGIN_PATH(env: ANSIBLE_ACTION_PLUGINS) = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/callbacks']
DEFAULT_FILTER_PLUGIN_PATH(env: ANSIBLE_FILTER_PLUGINS) = [u'$HOME/Projects/97/plugins/filter']
DEFAULT_GATHERING($HOME/Projects/97/etc/ansible.cfg) = smart
DEFAULT_HOST_LIST($HOME/Projects/97/etc/ansible.cfg) = [u'$HOME/Projects/97/inventories/T04', u'$HOME/Projects/97/inventories/setupenv']
DEFAULT_LOG_PATH($HOME/Projects/97/etc/ansible.cfg) = $HOME/.ansible/log/ansible.log
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'$HOME/.virtualenvs/97/local/lib/python2.7/site-packages/ara/plugins/modules', u'$HOME/Projects/97/library']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'$HOME/Projects/97/roles.galaxy', u'$HOME/Projects/97/roles']
DEFAULT_STDOUT_CALLBACK($HOME/Projects/97/etc/ansible.cfg) = yaml
GALAXY_ROLE_SKELETON(env: ANSIBLE_GALAXY_ROLE_SKELETON) = $HOME/Projects/97/etc/skel/default
GALAXY_ROLE_SKELETON_IGNORE($HOME/Projects/97/etc/ansible.cfg) = [u'']
HOST_KEY_CHECKING($HOME/Projects/97/etc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
- VMWare ESXi 6.5
- VMWare vCenter 6.5

##### STEPS TO REPRODUCE
1. Having disk device ready with a partition created and a file system of vmfs type created but not mounted on the ESXi node.
2. run a playbook with `vmware_host_datastore` module on that device:
```yaml
 tasks:
    - name: Mount an existing the vmfs datastore
      vmware_host_datastore:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ password_3par }}"
        datacenter_name: "{{ datacenter_name }}"
        esxi_hostname: "{{ ansible_host }}"
        datastore_name: "3PAR-VMFS01"
        datastore_type: "vmfs"
        vmfs_device_name: "naa.60002000000000000000000000000002"
        state: present
        vmfs_version: 6
      delegate_to: localhost
```
##### EXPECTED RESULTS
It tells me '_changed_' where it mounts the datastore.
```
TASK [ Mount an existing the vmfs datastore] ********************************************************
changed: [esx-node01 -> localhost] => (item=naa.60002000000000000000000000000002)
changed: [esx-node03 -> localhost] => (item=naa.60002000000000000000000000000002)
changed: [esx-node02 -> localhost] => (item=naa.60002000000000000000000000000002)
```

##### ACTUAL RESULTS
It tells me '_ok_' even I can see afterward on the nodes that the datastore is mounted!
```
TASK [ Mount an existing the vmfs datastore] ********************************************************
ok: [esx-node01 -> localhost] => (item=naa.60002000000000000000000000000002)
ok: [esx-node03 -> localhost] => (item=naa.60002000000000000000000000000002)
ok: [esx-node02 -> localhost] => (item=naa.60002000000000000000000000000002)
```
