### ISSUE TITLE
file module delete directory

### ISSUE THREAD

**Issue by anushak13** [ansible/ansible#50194]
##### ISSUE TYPE
•	Bug Report
##### COMPONENT NAME
Ansible delete
##### ANSIBLE VERSION
```
ansible --version
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/wasadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible-2.7.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
 ```
```
OS / ENVIRONMENT
NAME="SLES"
VERSION="11.4"
```
##### STEPS TO REPRODUCE
I am trying to delete files under a specific directory but not directory. Please find the below yaml files.

Playbook.yml

```
---
- hosts: all
    tasks:
    - name: Ansible remove file
      file:
        path: "{{ item.dest }}"
        state: absent
      with_items:
            - "{{ SAMPLE }}"
            - "{{ SAMPLE_TMP }}" 
```

vars/main.yml
```
---

SAMPLE:
- { src: '/tmp/abc.war', dest: '/tmp/test/' }
- { src: '/tmp/def.war', dest: 'tmp/test/' }
- { src: '/tmp/xyz.war', dest: '/tmp/test/' }


SAMPLE_TMP:
- { src: /tmp/test/abc.war, dest: /app/tomcatprofile/abc/webapps/ }
- { src: '/tmp/test/def.war', dest: '/app/tomcatprofile/def/webapps/' }
- { src: '/tmp/test/xyz.war', dest: '/app/tomcatprofile/test/webapps/' }

```

In the first loop SAMPLE all files under test folder are getting cleared but in the second loop...webapps folder itself is getting deleted....Could someone please help.

##### EXPECTED RESULTS
All files under webapps folder need to be deleted
##### ACTUAL RESULTS
Webapps folder is getting deleted
