### ISSUE TITLE
bigip_data_group doesn't support atomic adds or deletes of members

### ISSUE THREAD

**Issue by skylerbunny** [ansible/ansible#50210]
##### SUMMARY
As the bigip_data_group module works today, it is not possible to add or remove individual data group key/values from a data group - which is possible inside the F5 UI when a data group is created as type 'internal'.

Currently, your choices are to provide a complete list of records in the 'records' list item, the complete list of records via a records_src file, or a complete list of records via the 'content' block statement. 'state: absent' or 'state: present' only adds or deletes the entire data group.

I'd like to propose that this module's functions be split in a way similar to bigip_pool and bigip_pool_member, where bigip_data_group would handle the addition and creation of data groups in full, and bigip_data_group_member would handle the addition and deletion of individual entries IN an internal data group.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
bigip_data_group

##### ADDITIONAL INFORMATION
Consider the circumstance of wanting to create a data group named 'stringset'. In tmsh, we'd do something like this to create it, then add a record, in separate operations:

`tmsh create ltm data-group internal stringset type string`
`tmsh modify ltm data-group internal stringset records add {"peanut_butter" {data "jelly"}}`

(Later, perhaps in a different loop):
`tmsh modify ltm data-group internal stringset records add {"sour_cream" {data "onion"}}`

I could go back later and delete the first record I added, without removing the second:
`tmsh modify ltm data-group internal stringset records delete {"peanut_butter" }`

`tmsh modify ltm data-group internal NAME records` (ver 11) allows the following:
```
  add               Add items to the set
  delete            Delete specific items from the set
  modify            Modify existing items in the set
  none              Remove all items from the set
  replace-all-with  Replace the set with a new set
```

I could see a theoretical module working something like this:
```
- name: Create a new data group member, modify key's value instead if key exists
  bigip_data_group_member:
    name: stringset
    internal: yes # May not be necessary if by definition it must be internal
    records:
      - key: "sour_cream"
        value: "onion" # Value is "" by default if not provided (?)
    state: present
    type: string # May not be needed either, since the data group already exists (?)
    provider:
        ...
  delegate_to: localhost

- name: Remove an existing data group member by key
  bigip_data_group_member:
    name: stringset
    internal: yes # May not be necessary if by definition it must be internal
    records:
      - key: "peanut_butter"
    state: absent
    type: string # May not be needed either, since the data group already exists (?)
    provider:
        ...
  delegate_to: localhost
```
