### ISSUE TITLE
dnf module fails on python 3.7 when versionlock plug-in is installed

### ISSUE THREAD

**Issue by ericzolf** [ansible/ansible#50237]
##### SUMMARY

When the versionlock plug-in of DNF is installed and using Python 3.7, even the simplest usage of the DNF module fails with the error `File \"/usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py\", line 64, in sack\n    if not self.cli.demands.resolving:\nAttributeError: 'NoneType' object has no attribute 'demands'\n`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnf

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Nov 23 2018, 10:01:49) [GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]
```

##### CONFIGURATION

```paste below
(empty)
```

##### OS / ENVIRONMENT

Fedora 29 and Python 3.7.1
python3-dnf-plugin-versionlock-4.0.2-1.fc29.noarch
python3-dnf-plugin-system-upgrade-4.0.0-1.fc29.noarch
python3-dnf-plugins-extras-common-4.0.0-1.fc29.noarch
dnf-utils-4.0.2-1.fc29.noarch
dnf-data-4.0.9-2.fc29.noarch
python3-dnf-plugins-core-4.0.2-1.fc29.noarch
dnf-4.0.9-2.fc29.noarch
dnf-plugins-core-4.0.2-1.fc29.noarch
libdnf-0.22.3-1.fc29.x86_64
python3-dnf-4.0.9-2.fc29.noarch
dnf-yum-4.0.9-2.fc29.noarch
python3-libdnf-0.22.3-1.fc29.x86_64

##### STEPS TO REPRODUCE

- start with versionlock _NOT_ installed
- call `ansible -m dnf -a name=python3-dnf-plugin-versionlock localhost -b -K` => it works
- call again the same command and it fails (also with any other package name)

##### EXPECTED RESULTS

DNF works as usual...

##### ACTUAL RESULTS

```paste below
localhost | FAILED! => {
    "changed": false,
    "module_stderr": "/home/myuser/.ansible/tmp/ansible-tmp-1545384703.2069066-135233820167522/AnsiballZ_dnf.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/myuser/.ansible/tmp/ansible-tmp-1545384703.2069066-135233820167522/AnsiballZ_dnf.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/myuser/.ansible/tmp/ansible-tmp-1545384703.2069066-135233820167522/AnsiballZ_dnf.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/myuser/.ansible/tmp/ansible-tmp-1545384703.2069066-135233820167522/AnsiballZ_dnf.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib64/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_dnf_payload_4lvsrkjn/__main__.py\", line 1190, in <module>\n  File \"/tmp/ansible_dnf_payload_4lvsrkjn/__main__.py\", line 1179, in main\n  File \"/tmp/ansible_dnf_payload_4lvsrkjn/__main__.py\", line 1152, in run\n  File \"/tmp/ansible_dnf_payload_4lvsrkjn/__main__.py\", line 582, in _base\n  File \"/usr/lib/python3.7/site-packages/dnf/base.py\", line 428, in fill_sack\n    self._plugins.run_sack()\n  File \"/usr/lib/python3.7/site-packages/dnf/plugin.py\", line 100, in fn\n    dnf.util.mapall(operator.methodcaller(method), self.plugins)\n  File \"/usr/lib/python3.7/site-packages/dnf/util.py\", line 264, in mapall\n    return list(map(fn, *seq))\n  File \"/usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py\", line 64, in sack\n    if not self.cli.demands.resolving:\nAttributeError: 'NoneType' object has no attribute 'demands'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
or more stderr being more readable:

```python
/home/myuser/.ansible/tmp/ansible-tmp-1545381332.3860447-88286945308915/AnsiballZ_dnf.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home/myuser/.ansible/tmp/ansible-tmp-1545381332.3860447-88286945308915/AnsiballZ_dnf.py", line 113, in <module>
    _ansiballz_main()
  File "/home/myuser/.ansible/tmp/ansible-tmp-1545381332.3860447-88286945308915/AnsiballZ_dnf.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/myuser/.ansible/tmp/ansible-tmp-1545381332.3860447-88286945308915/AnsiballZ_dnf.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib64/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.7/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_dnf_payload_iie1fgq8/__main__.py", line 1190, in <module>
  File "/tmp/ansible_dnf_payload_iie1fgq8/__main__.py", line 1179, in main
  File "/tmp/ansible_dnf_payload_iie1fgq8/__main__.py", line 1152, in run
  File "/tmp/ansible_dnf_payload_iie1fgq8/__main__.py", line 582, in _base
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 428, in fill_sack
    self._plugins.run_sack()
  File "/usr/lib/python3.7/site-packages/dnf/plugin.py", line 100, in fn
    dnf.util.mapall(operator.methodcaller(method), self.plugins)
  File "/usr/lib/python3.7/site-packages/dnf/util.py", line 264, in mapall
    return list(map(fn, *seq))
  File "/usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py", line 64, in sack
    if not self.cli.demands.resolving:
AttributeError: 'NoneType' object has no attribute 'demands'
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/dnf.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/dnf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DJMuggs @berenddeschouwer @ignatenkobrain @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by maxamillion** [comment]
This actually turns out to be a bug in upstream dnf versionlock plugin, it assumes the plugin is being loaded by a call from the cli and doesn't properly handle the case where it's loaded by the python api. I've submitted a PR upstream to resolve. https://github.com/rpm-software-management/dnf-plugins-core/pull/317

**Comment by pghmcfc** [comment]
@maxamillion, is that "pass" a placeholder for "do something sane if not using the cli" here? On its own, this change doesn't appear to make any difference?

**Comment by maxamillion** [comment]
@pghmcfc the changed worked in my testing against a Fedora 29 host, are you seeing different behavior?

**Comment by pghmcfc** [comment]
@maxamillion, the change made no difference here:
```
[paul@akira ansible]$ diff -u /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py.orig /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py
--- /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py.orig	2018-11-22 10:16:48.000000000 +0000
+++ /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py	2019-01-10 10:14:32.745885488 +0000
@@ -61,6 +61,8 @@
                        and cp.get('main', 'locklist'))
 
     def sack(self):
+        if self.cli is None:
+            pass  # loaded via the api, not called by cli
         if not self.cli.demands.resolving:
             logger.debug(NO_VERSIONLOCK)
             return
[paul@akira ansible]$ ansible-playbook new-device.yml

PLAY [Playbook for setting up new device on network (DNS/DHCP)] **********************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************
ok: [akira]
ok: [goalkeeper]

TASK [include_role : bind-dns-server] ************************************************************************************************************************************

TASK [bind-dns-server : Install rsyslog package] *************************************************************************************************************************
fatal: [akira]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ::1 closed.\r\n", "module_stdout": "/root/.ansible/tmp/ansible-tmp-1547580049.2343416-29213492120740/AnsiballZ_dnf.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\r\n  import imp\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1547580049.2343416-29213492120740/AnsiballZ_dnf.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1547580049.2343416-29213492120740/AnsiballZ_dnf.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1547580049.2343416-29213492120740/AnsiballZ_dnf.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib64/python3.7/imp.py\", line 234, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib64/python3.7/imp.py\", line 169, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_dnf_payload_98vjbl8w/__main__.py\", line 1190, in <module>\r\n  File \"/tmp/ansible_dnf_payload_98vjbl8w/__main__.py\", line 1179, in main\r\n  File \"/tmp/ansible_dnf_payload_98vjbl8w/__main__.py\", line 1152, in run\r\n  File \"/tmp/ansible_dnf_payload_98vjbl8w/__main__.py\", line 582, in _base\r\n  File \"/usr/lib/python3.7/site-packages/dnf/base.py\", line 428, in fill_sack\r\n    self._plugins.run_sack()\r\n  File \"/usr/lib/python3.7/site-packages/dnf/plugin.py\", line 100, in fn\r\n    dnf.util.mapall(operator.methodcaller(method), self.plugins)\r\n  File \"/usr/lib/python3.7/site-packages/dnf/util.py\", line 264, in mapall\r\n    return list(map(fn, *seq))\r\n  File \"/usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py\", line 66, in sack\r\n    if not self.cli.demands.resolving:\r\nAttributeError: 'NoneType' object has no attribute 'demands'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
ok: [goalkeeper]
```
I'm no python expert, but isn't "pass" basically a no-op? How would this change help?

**Comment by jdoss** [comment]
It's not working on my end either @maxamillion 

Apply the patch to version lock:

```
  - name: Run dnf clean all
    command: /usr/bin/dnf clean all

  - name: Install dnf-plugin-versionlock
    package: name={{ item }} state=latest
    loop:
      - python2-dnf-plugin-versionlock
      - python3-dnf-plugin-versionlock

  - name: Download dnf versionlock PR 317 patch
    get_url:
      url: https://github.com/rpm-software-management/dnf-plugins-core/commit/01f1e60420b19c7432f8d52ee7f82ba661f92a7e.patch
      dest: /tmp/dnf-plugin-versionlock_pr_317.patch
      mode: 640

  - name: Apply dnf versionlock PR 317 patch to /usr/lib/python2.7/site-packages/dnf-plugins/versionlock.py
    patch:
      src: /tmp/dnf-plugin-versionlock_pr_317.patch
      dest: /usr/lib/python2.7/site-packages/dnf-plugins/versionlock.py
      remote_src: yes

  - name: Apply dnf versionlock PR 317 patch to /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py
    patch:
      src: /tmp/dnf-plugin-versionlock_pr_317.patch
      dest: /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py
      remote_src: yes

  - name: Update all packages
    dnf: name=* state=latest
```

Failure:

```
TASK [base : Update all packages] **********************************************
Tuesday 15 January 2019  14:17:46 -0600 (0:00:00.384)       0:01:50.148 ******* 
fatal: [dev]: FAILED! => changed=false 
  module_stderr: |-
    <stdin>:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    Traceback (most recent call last):
      File "<stdin>", line 113, in <module>
      File "<stdin>", line 105, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/usr/lib64/python3.7/imp.py", line 235, in load_module
        return load_source(name, filename, file)
      File "/usr/lib64/python3.7/imp.py", line 170, in load_source
        module = _exec(spec, sys.modules[name])
      File "<frozen importlib._bootstrap>", line 630, in _exec
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/ansible_dnf_payload_tt491esa/__main__.py", line 1190, in <module>
      File "/tmp/ansible_dnf_payload_tt491esa/__main__.py", line 1179, in main
      File "/tmp/ansible_dnf_payload_tt491esa/__main__.py", line 1152, in run
      File "/tmp/ansible_dnf_payload_tt491esa/__main__.py", line 582, in _base
      File "/usr/lib/python3.7/site-packages/dnf/base.py", line 428, in fill_sack
        self._plugins.run_sack()
      File "/usr/lib/python3.7/site-packages/dnf/plugin.py", line 100, in fn
        dnf.util.mapall(operator.methodcaller(method), self.plugins)
      File "/usr/lib/python3.7/site-packages/dnf/util.py", line 264, in mapall
        return list(map(fn, *seq))
      File "/usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py", line 66, in sack
        if not self.cli.demands.resolving:
    AttributeError: 'NoneType' object has no attribute 'demands'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

Target server:
```
$ cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)
[vagrant@dev ~]$ rpm -qa |grep dnf
dnf-data-4.0.9-2.fc29.noarch
python3-libdnf-0.22.3-1.fc29.x86_64
dnf-plugins-core-4.0.2-1.fc29.noarch
libdnf-0.22.3-1.fc29.x86_64
python2-dnf-4.0.9-2.fc29.noarch
dnf-yum-4.0.9-2.fc29.noarch
python2-libdnf-0.22.3-1.fc29.x86_64
python3-dnf-plugin-versionlock-4.0.2-1.fc29.noarch
python3-dnf-4.0.9-2.fc29.noarch
python2-dnf-plugins-core-4.0.2-1.fc29.noarch
dnf-4.0.9-2.fc29.noarch
python2-dnf-plugin-versionlock-4.0.2-1.fc29.noarch
python3-dnf-plugins-core-4.0.2-1.fc29.noarch
```

Ansible controller:

```
$ cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)
$ ansible --version
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jdoss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan  3 2019, 09:14:01) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]
```

**Comment by maxamillion** [comment]
ah, that should be:
```diff
     def sack(self):
+        if self.cli is None:
+            pass  # loaded via the api, not called by cli
+        elif not self.cli.demands.resolving:
-        if not self.cli.demands.resolving:

             logger.debug(NO_VERSIONLOCK)
             return
```

**Comment by maxamillion** [comment]
fixed upstream, sorry about that

**Comment by pghmcfc** [comment]
Thanks, that's better!

**Comment by jdoss** [comment]
This works for me now! Thanks @maxamillion :smile:

**Comment by maxamillion** [comment]
Upstream fix was accepted, so hopefully this will be a non issue soon. Happy automating!

**Comment by MarkMielke** [comment]
I think this is still an Ansible regression. Fedora 29 targets were working for me, but I just found they broke and it was because of upgrade from Ansible 2.7.4 to 2.7.5. Reverting to 2.7.4 returns this to working. Upgrading to 2.7.5 breaks it again.

The upstream fix to DNF is great for future, but that version of DNF is not available for Fedora 29 at this time, and I see no easy option to patch many Fedora 29 targets in place. This is a bit of a mess as a result.

Luckily, Ansible 2.7.4 still works, and I suggest that those facing this problem downgrade to 2.7.4 to revert this regression.

Is there something that can be done in Ansible to restore support for Fedora 29 targets with Python 2.7 and versionlock in Ansible 2.7.5+ the same as existed in Ansible 2.7.4? If you point me where to look, I'll take a stab at making the change... Or, I may look myself since the scope of what changed from 2.7.4 to 2.7.5 related to DNF must not be that large...

Ironic that I may have to "dnf versionlock ansible-2.7.4"... :-)

**Comment by maxamillion** [comment]
@MarkMielke are you certain that it actually works with Ansible 2.7.4 and doesn't just report success but not actually produce the intended outcome? There was a fix in 2.7.5 that resolved the fact that Ansible's dnf plugin wasn't properly initializing the plugin backends so I think what's happening is that the module is returning success but not actually doing what you ask of it. If this is in fact a regression I'd like to find a reproducer so that I can fix the issue in Ansible.

**Comment by MarkMielke** [comment]
Ansible 2.7.4 does what I need it to do which is to use a variety of "package:" and other directives to install a simple set of packages. Ansible 2.7.5 fails. I can't guarantee it works in all cases - specifically the case being fixed in 2.7.5. I only know that the simple cases work in 2.7.4 and fail in 2.7.5. :-(

**Comment by MarkMielke** [comment]
Here is an example bootstrap.yml play which is the first thing that failed for me when using Ansible 2.7.5 against a Fedora 29 target:

```
- name: bootstrap
  hosts: all
  tasks:
    - name: Ensure bootstrap packages are installed correctly.
      package:
        state: present
        name:
          - ansible
          - libselinux-python
    - name: Enable remote administration via SSH key.
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - name: Disable selinux. Reboot is still required.
      lineinfile:
        dest: /etc/sysconfig/selinux
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
```

The same play works fine in 2.7.4.

But the later playbook does much more complex things, and it also works fine in 2.7.4 and fails in 2.7.5.

**Comment by jboero** [comment]
> This actually turns out to be a bug in upstream dnf versionlock plugin, it assumes the plugin is being loaded by a call from the cli and doesn't properly handle the case where it's loaded by the python api. I've submitted a PR upstream to resolve. [rpm-software-management/dnf-plugins-core#317](https://github.com/rpm-software-management/dnf-plugins-core/pull/317)

Helpful as always.  Thanks Adam.  This affects Ansible too including Ovirt installer.  I manually disabled versionlock plugin and now have a stable Ovirt Engine+Host on my F28 box.

Johnnyb

**Comment by maxamillion** [comment]
@MarkMielke I understand your point, however the real issue is that previously we weren't initializing DNF plugins in the Ansible `dnf` module so it was not in fact loading plugins at all. That's on us, we should have been and it was a bug that was explicitly on Ansible to fix; specifically me because it was my error, so I fixed it. However, in light of fixing that bug in Ansible we uncovered a bug in upstream DNF and I don't think it is a good idea for Ansible to get in the business of suppressing bugs of other software (DNF or otherwise).

Until this issue is resolved in a new version of DNF, which should be the next release since it was accepted upstream in the devel branch, I suggest using the following work around:

```
    - name: Ensure bootstrap packages are installed correctly.
      package:
        state: present
        name:
          - ansible
          - libselinux-python
        disable_plugin: versionlock
```

**Comment by MarkMielke** [comment]
I've been thinking about this one on and off - mostly using Ansible 2.7.4 means I have bought time...

While the Ansible dnf module was not loading plugins at all, I think a patch release - 2.7.5 - is not the right time to introduce such a significant change. Probably, you thought it wasn't that significant, and you were only fixing something that was broken. But, the fact is that standard Ansible "package:" no longer works on any Fedora 29 system any longer. I see the patch made upstream, but I have no idea when it will get out to Fedora 29 update channel. I see your suggested work-around of using "disable_plugin: versionlock", but this implies I should add it to about 50 tasks. I'm struggling with understanding how this could be the right type of change to make in a patch release, and leave standing.

However, it is a free / open source project, and we will have different opinions, and I will have to work-around this in some way. Probably, I will hold off on upgrading beyond 2.7.4 until this is too frustrating, at which point if Fedora 29 has not patched dnf-plugins-core, I will do it myself.

**Comment by maxamillion** [comment]
@MarkMielke I ended up discussing this with some of the other core community maintainers and while the opinions were mixed, the majority agreed with you because of user impact. I'll get a patch in for this in and backported so it will be resolved in the next Ansible 2.7.x release.

**Comment by maxamillion** [comment]
@ericzolf @MarkMielke @jboero @jdoss so I've implemented a workaround in Ansible for this (here: https://github.com/ansible/ansible/pull/52859) and I'm interested in feedback in general and specifically about the UX of getting the warning:

```
$(ansible3)  ansible localhost -m dnf -a 'name=ninvaders state=absent' -e ansible_python_interpreter=/usr/bin/python3
 [WARNING]: Disabling dnf versionlock plugin due do known upstream bug:
https://github.com/rpm-software-management/dnf-plugins-core/pull/317

localhost | SUCCESS => {
    "changed": false,
    "msg": "Nothing to do",
    "rc": 0,
    "results": []
}

```

**Comment by jdoss** [comment]
Is there a way to skip disabling versionlock with this new PR @maxamillion ? We worked around this bug with:

```
- name: Run dnf clean all
    command: /usr/bin/dnf clean all

  - name: Install dnf-plugin-versionlock
    package:
      name: [ 'python2-dnf-plugin-versionlock',
              'python3-dnf-plugin-versionlock'
            ]
      state: latest

  - name: Download dnf versionlock PR 317 patch
    get_url:
      url: https://patch-diff.githubusercontent.com/raw/rpm-software-management/dnf-plugins-core/pull/317.patch
      dest: /tmp/dnf-plugin-versionlock_pr_317.patch
      mode: 640

  - name: Apply dnf versionlock PR 317 patch to /usr/lib/python2.7/site-packages/dnf-plugins/versionlock.py
    patch:
      src: /tmp/dnf-plugin-versionlock_pr_317.patch
      dest: /usr/lib/python2.7/site-packages/dnf-plugins/versionlock.py
      remote_src: yes
    ignore_errors: yes

  - name: Apply dnf versionlock PR 317 patch to /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py
    patch:
      src: /tmp/dnf-plugin-versionlock_pr_317.patch
      dest: /usr/lib/python3.7/site-packages/dnf-plugins/versionlock.py
      remote_src: yes
    ignore_errors: yes

  - name: Update all packages
    dnf:
      name: '*'
      state: latest
    tags: base
```

Which is pretty gross, but we need to be able to version lock MySQL on our development environments on Fedora 29.
