### ISSUE TITLE
provide filename output from return values for *os_config modules and cli_config

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#50245]
##### SUMMARY
provide the filename that is auto-created for the backup file name and return that value as a `return value` (e.g. https://docs.ansible.com/ansible/latest/modules/ios_config_module.html#return-values) for each config module.  Otherwise you end up having to do some more python within the Playbook which is not ideal for non-programmers (config_output.backup_path.split('/')[-1])

This allows the user to use the filename in subsequent tasks easily without using filters.

**Scenario**:
-Job kicked off on tower cluster
-backup done on various ansible nodes (job splitting)
-need to push to common place, filename is fine, but we don't care about path
- we can use copy modules, or sync module to copy the file over using the backup_path but we only want the filename for the destination side, we don't obviously want to copy the playbook_dir over to other devices or file backup storage devices

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_config
nxos_config
iosxr_config
vyos_config
eos_config
junos_config
cli_config
netconf_config

##### ADDITIONAL INFORMATION
This is how I am solving this today.... it works but it looks a little harder than it needs to be, if I had a backup_filename or something to work with it would be much easier.

```yaml
---
- name: SETUP NETWORK JOBS IN TOWER
  hosts: juniper
  connection: netconf
  become: yes
  gather_facts: no
  tasks:
    - name: BACKUP THE CONFIG
      junos_config:
        backup: yes
      register: config_output

    - name: debug it
      debug:
        var: config_output

    - name: debug 2
      debug:
        msg: "{{config_output.backup_path.split('/')[-1]}}"
```
