### ISSUE TITLE
gcp_compute_instance should not require storing credentials on disk

### ISSUE THREAD

**Issue by dch** [ansible/ansible#50247]
##### SUMMARY

Avoid needing to store GCP credentials/token on the filesystem.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`gcp_compute_instance`

##### ADDITIONAL INFORMATION

GCP requires very high levels of privilege  and yet the tokens need to be stored on disk.
In many environments this is either explicitly forbidden, and in general this is unwise.

Ideally GCP modules could acquire credentials from ansible variables, which would allow
adminstrators to store them inside vault, instead of continuously on disk.

```yaml
  gcp:
    project:        "{{ lookup('vault', 'secret/gcp', 'project') }}"
    account_file:   "facts/gcp-secrets.json"
    auth_kind:      "serviceaccount"
    scopes:
      - www.googleapis.com/auth/compute
      - www.googleapis.com/auth/ndev.clouddns.readwrite

```
