### ISSUE TITLE
Async docs example incorrect on 2.5 and 2.6

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#50262]
##### SUMMARY
Toure Dunnon reported that the example code in the docs for running multiple asynchronous tasks while limiting the amount of tasks running concurrently does not work on Ansible 2.5 or Ansible 2.6. 

Current:
```
#####################
# main.yml
#####################
- name: Run items asynchronously in batch of two items
  vars:
    sleep_durations:
      - 1
      - 2
      - 3
      - 4
      - 5
    durations: "{{ item }}"
  include_tasks: execute_batch.yml
  loop:
    - "{{ sleep_durations | batch(2) | list }}"
```

Correction/Replacement for last 3 lines of above example:

```
tasks:
    - include_tasks: execute_batch.yml
      with_items:
      - "{{ sleep_durations | batch(2) | list }}"
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/2.6/user_guide/playbooks_async.html

##### ANSIBLE VERSION
2.5
2.6

##### CONFIGURATION
Unknown or N/A

##### OS / ENVIRONMENT
Unknown or N/A
