### ISSUE TITLE
systemd module with scope: user will fail if using become

### ISSUE THREAD

**Issue by C0rn3j** [ansible/ansible#50272]
##### SUMMARY
Running within `scope: user` does not work if using `become`, `remote_user` has to match the user you're modifying the service for.

This should be at the very least noted in the documentation, along with the workaround for it if someone insists on using a different user.

https://docs.ansible.com/ansible/latest/modules/systemd_module.html

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
systemd module

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/c0rn3j/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### CONFIGURATION
```
default
```

##### OS / ENVIRONMENT
Arch Linux

##### STEPS TO REPRODUCE
Working:
```
---
- hosts: localhost
  remote_user: c0rn3j
  tasks:
    - become: true
      become_user: c0rn3j
      systemd:
        daemon_reload: yes
        enabled: yes
        scope: user
        state: started
        name: rebootrequiredcheck.timer
```

Broken:
```
---
- hosts: localhost
  remote_user: root
  tasks:
    - become: true
      become_user: c0rn3j
      systemd:
        daemon_reload: yes
        enabled: yes
        scope: user
        state: started
        name: rebootrequiredcheck.timer
```

Workaround (thanks to larsks on #ansible):
```
---
- hosts: localhost
  remote_user: root
  tasks:
    - name: get my user id
      become: true
      become_user: c0rn3j
      command: id -u
      register: myuid

    - become: true
      become_user: c0rn3j
      systemd:
        daemon_reload: yes
        enabled: yes
        scope: user
        state: started
        name: rebootrequiredcheck.timer
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ myuid.stdout }}"
```
One could also use ansible_user_id but it's not that much more comfortable.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1641362/50375693-0976e980-0602-11e9-9b40-b38e0ffda135.png">

##### EXPECTED RESULTS
Not an error, or at least note in a documentation for the module about the behavior.

##### ACTUAL RESULTS
```
# fatal: [localhost]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: Failed to connect to bus: No such file or directory\n"}
```

Note: seems like this behavior goes all the way up to sudo - 
https://bugs.launchpad.net/ubuntu/+source/sudo/+bug/1548300

Note #2: dbus.service needs to run for the user for the workaround to work. This can be achieved with linger. For the use case I was using this for however I just decided to switch to global as this is too much hassle.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/systemd.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/systemd.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by 50nar** [comment]
> 
- hosts: localhost
  remote_user: root
  vars:
     sudo_user : c0rn3j
  tasks:
    - name: test
      become: yes
      become_user: "{{ sudo_user }}"
      environment:
              XDG_RUNTIME_DIR: "/run/user/{{ lookup('pipe','id -u {{ sudo_user }}') }}"
      systemd:
        daemon_reload: yes
        enabled: yes
        scope: user
        state: started
        name: rebootrequiredcheck.timer

**Comment by larsks** [comment]
@yar05, that won't work.  lookups are executed on the local host where Ansible is running, not on the remote host, so that `id` command is running in the wrong place and will only co-incidentally return the correct information if the local identify of `sudo_user` happens to match the remote identity.

**Comment by 50nar** [comment]
@larks ahh you're right. Tested it with connection:local

**Comment by bcoca** [comment]
workaround:
```yaml
- getent: database=passwd key={{sudo_user}}

- name: test
  become: yes
  become_user: "{{ sudo_user }}"
  environment:
     XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['getent_passwd'][sudo_user][1] }}"
  systemd:
    daemon_reload: yes
    enabled: yes
    scope: user
    state: started
    name: rebootrequiredcheck.timer
```

**Comment by bcoca** [comment]
can you confirm that the PR above fixes the issue for you?

**Comment by C0rn3j** [comment]
Partially.

Am doing a simple reload like this -
```
---
- hosts: all
  remote_user: root
  tasks:
    - become: true
      become_user: c0rn3j
      systemd:
        daemon_reload: yes
        scope: user
```

So with that change instead of failing everywhere, it fails on machines where user `c0rn3j` is not logged in (because `c0rn3j`'s user dbus.service is not running on machines where the user is not logged in)
![image](https://user-images.githubusercontent.com/1641362/50777753-c0c75d80-129c-11e9-9d6b-2bc93d25e5a5.png)


---
Sidenote:
 I tried
```
  tasks:
    - become: true
      become_user: c0rn3j
      systemd:
        daemon_reload: yes
        enabled: no
        scope: user
        name: rebootrequiredcheck.timer
```
Which always gives me a changed status because rebootrequiredcheck.timer was activated globally, so disabling it in user mode doesn't really work. 
Not sure if this is not a systemd issue however. Or a systemd feature.
