### ISSUE TITLE
Can't reference a dict key inside the same dict

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#50280]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dictionaries

##### ANSIBLE VERSION

```paste below
2.7.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

All

##### STEPS TO REPRODUCE

```yaml
myapp:
  version: 1.6.3
  download_url: http://example.org/download/myapp-{{ myapp.version }}.tgz
```

##### EXPECTED RESULTS

We should be able to define a dict key relatively to another dict key (in the same dict)

##### ACTUAL RESULTS

```paste below
recursive loop detected in template string:
```

##### REFERENCE
https://github.com/ansible/ansible/issues/8603

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is expected and not something that we plan on changing.  You cannot create a self referential variable.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by BarbzYHOOL** [comment]
apparently people said that in many apps and languages it's expected to work, and quite logic too

**Comment by piscesvivian** [comment]
ansible is not design for people, but for fun, thanks
we design vars in dict but won't support this feature. 
so we need write a hundreds like:

spring_app1_jvm_opts: -Xms1G -Xmx2G
spring_app1_port: 1000
spring_app1_path: /usr/lib/app1

spring_app2_jvm_opts: -Xms1G -Xmx2G
spring_app2_port: 1000
spring_app2_path: /usr/lib/app2

spring_app3_jvm_opts: -Xms1G -Xmx2G
spring_app3_port: 1000
spring_app3_path: /usr/lib/app3

spring_tomcat_jvm_opts: -Xms1G -Xmx2G
spring_tomcat_port: 1000
spring_tomcat_path: /usr/lib/tomcat

spring_debug_app_jvm_opts: -Xms1G -Xmx2G
spring_debug_app_port: 1000
spring_debug_app_path: /usr/lib/debug_app

spring_debug_app2_jvm_opts: -Xms1G -Xmx2G
spring_debug_app2_port: 1000
spring_debug_app2_path: /usr/lib/debug_app2

....... more and more, and similar code, endless debug time. good luck

so use docker is a best choice, ansible is not good enough

**Comment by Akasurde** [comment]
@piscesvivian Might want to take a look at - https://github.com/Akasurde/ansible-reproducers/blob/master/useful_pbs/debug_anchor.yml

**Comment by bcoca** [comment]
also:
```yaml
spring:
  app1:
    jvm: &jvm_opts
       opts: '-Xms1G -Xmx2G'
       port: 1000
       path: /usr/lib/app1
  app2:
    jvm:
      <<: *jvm_opts
      path: /usr/lib/app2
  app3:
    jvm:
      <<: *jvm_opts
      path: /usr/lib/app3
  tomcat:
   jvm:
      <<: *jvm_opts
      path: /usr/lib/tomcat
...
```
