### ISSUE TITLE
Unsupported parameters for (dynamodb_table) module: SSEDescription

### ISSUE THREAD

**Issue by yojesh** [ansible/ansible#50291]
```yaml
- dynamodb_table:
    region: "{{ dynamodb.region }}"
    name: "{{ item.name }}"
    hash_key_name: "{{ item.hash_key_name }}"
    hash_key_type: "{{ item.hash_key_type }}"
    range_key_name: "{{ item.range_key_name | default(omit) }}"
    range_key_type: "{{ item.range_key_type | default(omit) }}"
    read_capacity: "{{ item.read_capacity | default(omit) }}"
    write_capacity: "{{ item.read_capacity | default(omit) }}"
    indexes: "{{ item.indexes | default(omit) }}"
    SSEDescription: {
         "SSEType": "KMS",
         "Status": "ENABLED",
         "KMSMasterKeyArn": "arn:aws:kms:us-west-2:528714515:key/8205aaef-2d9-4771-bd1e-0db10e9"
         }

    wait_for_active_timeout: 300
    state: "{{ dynamodb_state }}"
    tags: "{{ aws_tags }}"
  with_items: "{{ dynamodb_tables }}"
  loop_control:
    pause: 1

```
Why this code is not adding kms to the table while creating it ?
