### ISSUE TITLE
java_keystore can't be ussed to import CA certificate without private key

### ISSUE THREAD

**Issue by ilmarh** [ansible/ansible#50294]
##### SUMMARY

Can't add my own CA certificate (self-signed) to trustedstore without private key using java_keystore module. Issuing the command manually works: `keytool -keystore /tmp/truststore.jks -alias CARoot -import -file ca-test.crt -storepass password -keypass  password`. Doc says `private_key` is not required, but module return error 'missing required arguments: private_key'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

java_keystore

##### ANSIBLE VERSION

```paste below
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/angara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04.1 LTS as ansible controller, Ubuntu 16.04.5 as managed hosts with python3

##### STEPS TO REPRODUCE

Generate self-signed CA cert and store in file `ca_certificate_name`, then try to add just CA certificate without private key with sample playbook below. You will get error message. But if you'll issue something like `keytool -keystore /tmp/trustedstore.jks -alias CARoot -import -file ca-test.crt -storepass somepassword -keypass somepassword` and confirm, certificate will be added to the store without private key knowledge.

```yaml
---
- name: Java KeyTool test
  hosts: localhost
  tasks:

  - name: Create secrets directory.
    file:
      path: secrets
      state: directory

  - name: Generate CA private key.
    openssl_privatekey:
      path: 'secrets/ca-test.pem'

  - name: Generate CA CSR.
    openssl_csr:
      path: 'secrets/ca-test.csr'
      privatekey_path: 'secrets/ca-test.pem'
      common_name: "CA"

  - name: Generate a Self Signed certificate CA.
    openssl_certificate:
      path: 'secrets/ca-test.crt'
      privatekey_path: 'secrets/ca-test.pem'
      csr_path: 'secrets/ca-test.csr'
      provider: selfsigned

  - name: Generate keystore passwords.
    set_fact:
      store_password: "{{ lookup('password', 'secrets/store.pwd') }}"

  - name: Store CA in jks
    java_keystore:
      name: 'CAroot'
      certificate: "{{lookup('file', 'secrets/ca-test.crt') }}"
      password: '{{store_password}}'
      dest: '/tmp/trusted_keystore.jks'
```

##### EXPECTED RESULTS

I expect CA certificate to be added to /tmp/trustedstore.jks

##### ACTUAL RESULTS

I receive error below. 

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "certificate": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "dest": "/tmp/trusted_keystore.jks",
            "follow": false,
            "force": false,
            "name": "CAroot",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "missing required arguments: private_key"
}
```
