### ISSUE TITLE
kms on dynamodb table

### ISSUE THREAD

**Issue by yojesh** [ansible/ansible#50292]
##### SUMMARY
Existing Dynamodb module lacks lot of feature what AWS provides at this point. We need support for following features:

 1.   Create  tables and Enable encryption at rest

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Encryption at rest (SSE)

##### ANSIBLE VERSION
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

##### CONFIGURATION
-----

##### OS / ENVIRONMENT
----
##### STEPS TO REPRODUCE
```yaml
- dynamodb_table:
    region: "{{ dynamodb.region }}"
    name: "{{ item.name }}"
    hash_key_name: "{{ item.hash_key_name }}"
    hash_key_type: "{{ item.hash_key_type }}"
    range_key_name: "{{ item.range_key_name | default(omit) }}"
    range_key_type: "{{ item.range_key_type | default(omit) }}"
    read_capacity: "{{ item.read_capacity | default(omit) }}"
    write_capacity: "{{ item.read_capacity | default(omit) }}"
    indexes: "{{ item.indexes | default(omit) }}"
    SSEDescription: {
         "SSEType": "KMS",
         "Status": "ENABLED",
         "KMSMasterKeyArn": "arn:aws:kms:us-west-2:528719264515:key/820f-d9-4771bd1e-0db10da31"
         }

    wait_for_active_timeout: 300
    state: "{{ dynamodb_state }}"
    tags: "{{ aws_tags }}"
  with_items: "{{ dynamodb_tables }}"
  loop_control:
    pause: 1

```

##### EXPECTED RESULTS
In the result it should show that the table has been created with SSE=enabled and SSEtype= KMS

##### ACTUAL RESULTS
Unsupported parameters for (dynamodb_table) module: SSEDescription
