### ISSUE TITLE
vmware_deploy_ovf: Properties not being passed to post configuration

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#50299]
##### SUMMARY
When trying to deploy the VCSA OVA appliance none of the post VM creation configuration parameter properties are being applied.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_deploy_ovf

##### ANSIBLE VERSION
```
ansible 2.7.0
  config file = /home/nick/code/vmware-ansible/ansible.cfg
  configured module search path = [u'/home/nick/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
CentOS 7.4
ESXi 6.7
VCSA appliance VMware-vCenter-Server-Appliance-6.7.0.12000-8832884_OVF10

##### STEPS TO REPRODUCE
```
- name: 'Deploy the VCSA OVA to an ESXi server'
  connection: 'local'
  gather_facts: False
  hosts: '{{ target_esxi }}'
  serial: 1
  tasks:
    - name: 'Deploy OVF'
      vmware_deploy_ovf:
        hostname: '{{ target_esxi }}'
        username: '{{ esxi_root_account }}'
        password: "a_password_01"
        validate_certs: '{{ validate_certs }}'
        name: "vcenter01"
        datastore: "datastore-1"
        disk_provisioning: "thin"
        networks:
          "Network 1": "vmware"
        ovf: "/path/to/ova/VMware-vCenter-Server-Appliance-6.7.0.12000-8832884_OVF10.ova"
        power_on: "yes"
        deployment_option: "medium-lstorage"
        fail_on_spec_warnings: "yes"
        wait_for_ip_address: "no"
        properties:
          guestinfo.cis.appliance.net.addr.family: "ipv4"
          guestinfo.cis.appliance.net.mode: "static"
          guestinfo.cis.appliance.net.addr: "192.168.1.10"
          guestinfo.cis.appliance.net.prefix: "25"
          guestinfo.cis.appliance.net.gateway: "192.168.1.1"
          guestinfo.cis.appliance.net.dns.servers: "1.1.1.1"
          guestinfo.cis.appliance.net.pnid: "192.168.1.10"
          guestinfo.cis.vmdir.password: "a_password_02"
          guestinfo.cis.appliance.root.passwd: "a_password_03"
          guestinfo.cis.appliance.ssh.enabled: "true"
          guestinfo.cis.appliance.ntp.servers: "ntp1, ntp2"
          vami.domain.VMware-vCenter-Server-Appliance: "vsphere.local"
          vami.searchpath.VMware-vCenter-Server-Appliance: "test.local"
          guestinfo.cis.ceip_enabled: "false"
      delegate_to: localhost
```
Note:
The configuration keys in the *properties:* section are sourced from the original OVA by converting it to an OVF and inspecting VMware-vCenter-Server-Appliance-6.7.0.12000-8832884_OVF10.ovf xml file.

##### EXPECTED RESULTS

The VCSA VM would be deployed with the configuration as above.

##### ACTUAL RESULTS
A VM of the correct specification as per the key *deployment_option:* is created but none of the post configuration of the VM is passed through from the values in the *properties:* key

```
PLAY [Deploy an OVF to an ESXi server] *******************************************************************************************************************************************************************************************************************************************

TASK [Deploy OVF] ****************************************************************************************************************************************************************************************************************************************************************
changed: [esx01.test.local -> localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************
esx01.test.local : ok=1    changed=1    unreachable=0    failed=0
```

I've also updated the module vmware_deploy_ovf to the one avialable in Ansible 2.7.5 with the same result.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @ckotte @dav1x @sivel @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nicholasrodriguez, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kendrew71** [comment]
I can confirm that I am seeing the same behavior.

I don't know if it's not passing the properties (the -vvv output shows all my properties), but it's certainly not executing the autoconfig.

RedHat 7.4
ESXi 6.7u1
VMware-vCenter-Server-Appliance-6.7.0.20000-10244745_OVF10.ova
pyvmomi 6.7.1

The ansible RPM is from EPEL, not the RedHat Ansible Engine repo, which seems to be a slightly different build.
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```
I get the same output as the OP (ok=1 changed=1), and the play exits after the VM gets an IP.

At that point, I've seen two different behaviors, and I suspect the difference between them is whether the VM ends up with an IPv4 address via DHCP, but it may be something else entirely.

In the dev lab, the VM gets a DHCP address, boots to the blue/black screen, and proceeds to RPM installs, after which I can hit :5480 and run stage 2 manually.

In the test lab, the VM does not get an IPv4 address (but it does get IPv6 auto), goes through some initial config, then just sits at a black screen with a blinking cursor in the upper left corner (I let it sit for an hour, just in case).

**Comment by kendrew71** [comment]
I forgot to add that the following are the OVF properties that I pass to vmware_deploy_ovf:
```
guestinfo.cis.appliance.net.addr.family: "ipv4"
guestinfo.cis.appliance.net.mode: "static"
guestinfo.cis.appliance.net.addr: "{{ vcenter_ip_address | ipaddr }}"
guestinfo.cis.appliance.net.prefix: "{{ vcenter_net_prefix }}"
guestinfo.cis.appliance.net.gateway: "{{ vcenter_gateway | ipaddr }}"
guestinfo.cis.appliance.net.pnid: "{{ vcenter_fqdn }}"
guestinfo.cis.appliance.net.dns.servers: "{{ dns_servers }}"
guestinfo.cis.vmdir.site-name: "{{ sso_site_name }}"
guestinfo.cis.vmdir.domain-name: "{{ sso_domain_name }}"
guestinfo.cis.vmdir.username: "administrator@{{ sso_domain_name }}"
guestinfo.cis.vmdir.password: "{{ sso_password }}"
guestinfo.cis.vmdir.first-instance: "True"
guestinfo.cis.db.type: "embedded"
guestinfo.cis.appliance.root.passwd: "{{ vcenter_password }}"
guestinfo.cis.appliance.ssh.enabled: "True"
guestinfo.cis.appliance.time.tools-sync: "True"
guestinfo.cis.deployment.node.type: "embedded"
guestinfo.cis.deployment.autoconfig: "True"
guestinfo.cis.silentinstall: "True"
guestinfo.cis.ceip_enabled: "False"
```
I've also successfully used the method that was developed here:
https://github.com/virtualelephant/vsphere-sddc/tree/master/roles/vcsa-deploy/

It's basically executing ovftool via the ansible "command" module. I used the same properties above with it, along with the following (showing which ones match up to vmware_deploy_ovf options, and which are extra).

Options matching the ovftool method:

    validate_certs: no
        --noSSLVerify
    wait_for_ip_address: yes
        --X:waitForIp
    power_on: yes
        --powerOn
    name: "vc01"
        --name="vc01"
    deployment_option: "small"
        --deploymentOption="small"
    disk_provisioning: "thin"
        --diskMode="thin"
    datastore: "datastore"
        --datastore="datastore"
    networks: { "Network 1": "VM Network" }
        --net:"Network 1"="VM Network"

Additional options to ovftool:

    --acceptAllEulas
    --X:injectOvfEnv
    --allowExtraConfig
    --X:enableHiddenProperties
    --X:connectionFileTransferRetryCount=3
    --sourceType=OVA

**Comment by nicholasrodriguez** [comment]
Thanks for the contribution. I’ve been doing a bit of digging and it is down to how the VCSA OVA has been packaged and how **vmware_deploy_ovf**  handles the OVA configuration options rather than a fundamental issue with the current state of  **vmware_deploy_ovf**. 

There are certain settings in the VCSA OVA required for the post configuration of vCenter that are set to “userConfigurable="false"”. By changing the following values to userConfigurable="True" in the OVA and running the deployment against a vCenter (not an ESXi server) using vmware_deploy_ovf then I get a fully configured embedded VCSA.

OVA changes required;

guestinfo.cis.deployment.autoconfig
guestinfo.cis.appliance.ssh.enabled
guestinfo.cis.appliance.ntp.servers
guestinfo.cis.ceip_enabled

However, altering the OVA is probably not a supported method of deployment by VMware.

I think the additional options being called when you use the ovftool (--allowExtraConfig etc.) enable the properties of the OVA, as also seen with VMware vcsa-cli-installer.

It would be great if these options could be extended into **vmware_deploy_ovf** but I think I’ve read in other Issues raised with **vmware_deploy_ovf** than the endpoint the module uses hasn’t got this extended functionality (I could be wrong though).

One thing to note is that the above won’t work when deploying directly to an ESXi server. I think the OVF capabilities of ESXi directly lack the functionality to pass in the required properties to configure the VCSA. Therefore the playbook in my OP would never work.

Below is the playbook that works with the altered OVA against vCenter for reference.
```
---
# In order for the following to work the VCSA OVA has to be edited so
# that the following keys are marked as user configurable.
# guestinfo.cis.deployment.autoconfig
# guestinfo.cis.appliance.ssh.enabled
# guestinfo.cis.appliance.ntp.servers
# guestinfo.cis.ceip_enabled
#

- name: 'Deploy an OVF to an vCenter server'
  connection: 'local'
  gather_facts: False
  hosts: 'mgmt_vcenter'
  serial: 1
  tasks:
    - name: 'Deploy VCSA OVF to vCenter'
      vmware_deploy_ovf_new:
        datacenter: '{{ dc_name }}'
        cluster: '{{ cluster_name }}'
        hostname: '{{ ansible_host }}'
        username: '{{ ansible_vcenter_username }}'
        password: '{{ ansible_vcenter_password }}'
        validate_certs: '{{ validate_certs }}'
        name: 'vcenter01'
        datastore: 'datastore-1'
        disk_provisioning: "thin"
        networks:
          "Network 1": "vmware"
        ovf: '/path/to/ova/VMware-vCenter-Server-Appliance-6.7.0.12000-8832884_OVF10_new.ova'
        power_on: 'yes'
        deployment_option: 'large'
        fail_on_spec_warnings: 'yes'
        wait_for_ip_address: 'yes'
        properties:
          guestinfo.cis.deployment.autoconfig: "True"
          guestinfo.cis.appliance.net.addr.family: "ipv4"
          guestinfo.cis.appliance.net.mode: "static"
          guestinfo.cis.appliance.net.addr: "192.168.10"
          guestinfo.cis.appliance.net.prefix: "24"
          guestinfo.cis.appliance.net.gateway: "192.168.1"
          guestinfo.cis.appliance.net.dns.servers: "1.1.1.1"
          guestinfo.cis.appliance.net.pnid: "vcenter01.test.local"
          guestinfo.cis.vmdir.password: "a_password_01"
          guestinfo.cis.appliance.root.passwd: "a_password_02"
          guestinfo.cis.appliance.ssh.enabled: "True"
          guestinfo.cis.appliance.ntp.servers: "time1.test.local"
          vami.domain.VMware-vCenter-Server-Appliance: "test.local"
          vami.searchpath.VMware-vCenter-Server-Appliance: "test.local"
          guestinfo.cis.ceip_enabled: "False"
```

**Comment by sivel** [comment]
This likely seems to be related to the ovftool option `enableHiddenProperties`.

Found on another website:

> There is a hidden OVF property called `guestinfo.cis.appliance.ssh.enabled` that will allow SSH to be enabled upon deployment. To be able to configure this property, you must add an advanced ovftool option called `--X:enableHiddenProperties`

We would need to figure out how to configure that via pyvmomi during this process.

**Comment by sivel** [comment]
I'm going to guess, that what `ovftool` does with this option, is that after calling `ovfManager.CreateImportSpec` we would need to go through `importSpec.configSpec` and toggle the params that are set as `userConfigurable="false"` to being True.

**Comment by sivel** [comment]
The only thing stopping me right now, is not having an OVF/OVA that contains these types of properties, so I don't have a good way to validate and/or test.

**Comment by sivel** [comment]
Are any of you able to confirm whether this change resolves your issues:

```diff
diff --git a/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py b/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py
index 6eb690baed..f1da9dd142 100644
--- a/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py
+++ b/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py
@@ -56,6 +56,12 @@ options:
         default: thin
         description:
         - Disk provisioning type.
+    enable_hidden_properties:
+        description:
+        - Enable source properties that are marked as ovf:userConfigurable=false
+        default: "no"
+        type: bool
+        version_added: "2.8"
     fail_on_spec_warnings:
         description:
         - Cause the module to treat OVF Import Spec warnings as errors.
@@ -377,6 +383,10 @@ class VMwareDeployOvf:
             spec_params
         )
 
+        if self.params['enable_hidden_properties']:
+            for prop in self.import_spec.importSpec.configSpec.vAppConfig.property:
+                prop.info.userConfigurable = True
+
         errors = [to_native(e.msg) for e in getattr(self.import_spec, 'error', [])]
         if self.params['fail_on_spec_warnings']:
             errors.extend(
@@ -543,6 +553,10 @@ def main():
         'deployment_option': {
             'default': None,
         },
+        'enable_hidden_properties': {
+            'default': False,
+            'type': 'bool',
+        },
         'folder': {
             'default': None,
         },
```

needs_info

**Comment by kendrew71** [comment]
I see what you guys are saying about configurable=false. I have 10 properties that I set that are "not configurable", but I'm ok with the defaults on 6 of them. Unfortunately, like you say, the following must be set to true (either time.tools-sync, or ntp.servers).

key="guestinfo.cis.appliance.ssh.enabled" type="boolean" userConfigurable="false" value="False"
key="guestinfo.cis.appliance.time.tools-sync" type="boolean" userConfigurable="false" value="False"
key="guestinfo.cis.deployment.autoconfig" type="boolean" userConfigurable="false" value="False"
key="guestinfo.cis.silentinstall" type="boolean" userConfigurable="false" value="False"

However, @nicholasrodriguez, I was able to use ovftool via ansible to deploy the unmodified VCSA OVA to an ESXi server (not via vCenter), and it did continue on to autoconfig (stage 2). This procedure seems to be pretty well defined by a couple of projects here on github.

Of course, it would be much nicer if this module could do it, but I tried the patch @sivel, and it did not seem to make a difference. I thought it would do it, but I get the same result.

```
$ sudo patch -o vmware_deploy_ovf.py vmware_deploy_ovf.py.orig /tmp/vmware_deploy_ovf_patch
patching file vmware_deploy_ovf.py (read from vmware_deploy_ovf.py.orig)
Hunk #2 succeeded at 368 (offset -15 lines).
Hunk #3 succeeded at 538 (offset -15 lines).`
```
```
$ diff vmware_deploy_ovf.py.orig vmware_deploy_ovf.py 
58a59,64
>     enable_hidden_properties:
>         description:
>         - Enable source properties that are marked as ovf:userConfigurable=false
>         default: "no"
>         type: bool
>         version_added: "2.8"
364a371,374
>         if self.params['enable_hidden_properties']:
>             for prop in self.import_spec.importSpec.configSpec.vAppConfig.property:
>                 prop.info.userConfigurable = True
> 
529a540,543
>         },
>         'enable_hidden_properties': {
>             'default': False,
>             'type': 'bool',
```

I then ran pycompile on the new vmware_deploy_ovf.py, and re-ran my playbook, but it still does not continue on to stage 2.

**Comment by sivel** [comment]
Ok, it must be something extra.  I'll have to look at what `--X:injectOvfEnv` and `--allowExtraConfig` also do.  Because ovftool is closed source, it's not easy to tell exactly what they do and how they accomplish it.  `govmomi` supports `injectOvfEnv` by doing a reconfigure on the VM after it is built:

https://github.com/vmware/govmomi/blob/512fb9e1dc3ac5e887de7278f234be297c746554/govc/importx/ovf.go#L382-L431

At some point, we may not be able to mimic all of what `ovftool` is capable of.

**Comment by sivel** [comment]
```
--X:injectOvfEnv	Force the given OVF properties to be inserted into an OVF Environment and injected through VMware Tools. Must be used together with --powerOn the VI target for an ESX host and a single VM source.

--allowExtraConfig	Whether we allow ExtraConfig options. These options are a security risk as they control low-level and potential unsafe options on the VM.
```

**Comment by sivel** [comment]
Eventually for any of us to be able to implement these features, a very basic OVF/OVA will be needed so that it can be tested.

**Comment by sivel** [comment]
Also, just to state this, I'm by no means a VMware expert.  As such, I have no idea what the significance of `guestinfo.cis` is as a prefix on those properties.  Understanding that may help as well.

**Comment by kendrew71** [comment]
From the ovftool User Guide..

.. if you are deploying with the ovftool command from an ESXi host, you have to ‘inject’ the parameters into the resulting VM, when it is powered on. This is because the ESXi host doesn't have a cache to store the OVF parameters, like the vCenter Server does. Therefore, you MUST use the ‘--X:injectOvfEnv’ debug option with the ‘--poweron’ option in the command line if you are deploying a virtual machine from 
ESXi ..

So @nicholasrodriguez was touching on this part of the problem also, and this is the confirmation / explanation of it. And now it makes sense what you said about govmomi doing a reconfiguration on the VM to make it happen.

In regards to a test OVA, I think the VCSA installer ISO is free to download (you'll have to create a login on the Vmware site), and it has the OVA we've been referencing on it.

https://my.vmware.com/group/vmware/info?slug=datacenter_cloud_infrastructure/vmware_vsphere/6_7

I'm not sure why the ovftool invocation is using --allowExtraConfig for this deployment. This is supposed to allow passing of direct .vmx configuration, but from the guide it seems like it should be paired with one or more --extraConfig flags that specify the key:value pairs. Maybe that's just if they're not set in the .ovf file.

I don't think "guestinfo.cis" has any significance beyond namespace for the properties.

**Comment by nicholasrodriguez** [comment]
@sivel thanks for looking into this, hopefully you are able to hold of the OVA that @kendrew71 linked to. Building the functionality into this module (if possible) would enable the full end-to-end build of a vSphere infrastructure entriely driven by Ansible. Let me know if I can help with further testing, I have the capability at the moment.

@kendrew71 you mentioned in a previous comment you had a playbook to call the ovftool locally to deploy and unmodified OVA to an ESXi server. Would you be able to share that please?

**Comment by sivel** [comment]
I'll try to put something together to perform the InjectOvfEnv step based off of govmomi/pyvmomi-community-samples later this week.

I'll see about downloading VCSA as well so that I can test.

**Comment by kendrew71** [comment]
@nicholasrodriguez, I just created a playbook that simplifies the virtualelephant role I linked to earlier. It is just one play with some variables set at the top. I also set the ESXi host as my target so that I pick up the proper vars. Here is the play..

```
  - name: Deploy the vCenter appliance with embedded PSC
    command: >
      "{{ ovftool }}"
      --acceptAllEulas
      --noSSLVerify
      --X:injectOvfEnv
      --allowExtraConfig
      --X:enableHiddenProperties
      --X:waitForIp
      --X:connectionFileTransferRetryCount=3
      --sourceType=OVA
      --powerOn
      --net:"Network 1"="{{ target_esxi_portgroup }}"
      --datastore="{{ target_esxi_datastore }}"
      --diskMode="{{ disk_mode }}"
      --name="{{ vcenter_appliance_name }}"
      --deploymentOption="{{ vcenter_appliance_size }}"
      --prop:guestinfo.cis.deployment.autoconfig=True
      --prop:guestinfo.cis.silentinstall=True
      --prop:guestinfo.cis.vmdir.domain-name="{{ sso_domain_name }}"
      --prop:guestinfo.cis.vmdir.site-name="{{ sso_site_name }}"
      --prop:guestinfo.cis.vmdir.username="administrator@{{ sso_domain_name }}"
      --prop:guestinfo.cis.vmdir.password="{{ sso_password }}"
      --prop:guestinfo.cis.appliance.net.addr.family="{{ net_addr_family }}"
      --prop:guestinfo.cis.appliance.root.passwd="{{ vcenter_password }}"
      --prop:guestinfo.cis.appliance.ssh.enabled=True
      --prop:guestinfo.cis.vmdir.first-instance=True
      --prop:guestinfo.cis.ceip_enabled=True
      --prop:guestinfo.cis.appliance.net.pnid="{{ vcenter_fqdn }}"
      --prop:guestinfo.cis.appliance.net.mode="{{ network_ip_scheme }}"
      --prop:guestinfo.cis.appliance.net.addr="{{ vcenter_ip_address | ipaddr }}"
      --prop:guestinfo.cis.appliance.net.prefix="{{ vcenter_net_prefix }}"
      --prop:guestinfo.cis.appliance.net.gateway="{{ vcenter_gateway | ipaddr }}"
      --prop:guestinfo.cis.appliance.net.dns.servers="{{ dns_servers }}"
      --prop:guestinfo.cis.appliance.time.tools-sync=True
      --prop:guestinfo.cis.db.type="{{ appliance_type }}"
      --prop:guestinfo.cis.deployment.node.type="{{ appliance_type }}"
      "{{ vcsa_ova }}"
      vi://"{{ target_esxi_username | urlencode }}":"{{ target_esxi_password | urlencode }}"@"{{ inventory_hostname }}"/
    register: deploy_ovf_cmd_result
    delegate_to: localhost
    ignore_errors: True
```
The only var that may need to be explained is "appliance_type", which is set to "embedded". You could also just leave those properties out, since "embedded" is the default. Some of the SSO (cis.vmdir) properties are good with defaults as well.

The injectOvfEnv and allowExtraConfig options seem to be the magic combination to make it happen for ESXi (vs vCenter). Of course, from your testing it seems like enableHiddenProperties is needed as well regardless of target.

**Comment by nicholasrodriguez** [comment]
@kendrew71 and @sivel thanks for this.

**Comment by sivel** [comment]
Ok, here is round 2:

https://gist.github.com/sivel/8f50a0e468504ba83d7f6cb032bacc9c

I don't think `enable_hidden_properties` is required, but I could be wrong, if you could please test and let me know if things are working that would be great.  The new argument is `inject_ovf_env`.

Based on my minimal testing ssh is enabled when setting:

```
        properties:
          guestinfo.cis.appliance.ssh.enabled: "True"
          guestinfo.cis.deployment.autoconfig: "True"
        inject_ovf_env: true
```

needs_info

**Comment by nicholasrodriguez** [comment]
@sivel Thanks, I've run some tests and I have a configured vCenter server deployed to ESXi using your patch. There are other tests I need to perform but so far all the keys passed through have been applied to OVA post boot

**Comment by sivel** [comment]
Please be sure to try it without `enable_hidden_properties`.  Since I don't think that is required for anything, I'd like to remove it.  Unless you find it is doing something useful.

**Comment by nicholasrodriguez** [comment]
Ok, I'll give that a try, I should have the results tomorrow.

**Comment by nicholasrodriguez** [comment]
@sivel I removed ```enable_hidden_properties``` and the VCSA appliance deployed and passed through the parameters Ok.

**Comment by sivel** [comment]
I've submitted the PR to add this functionality: https://github.com/ansible/ansible/pull/51074

**Comment by Akasurde** [comment]
@nicholasrodriguez @kendrew71 Could you please check if #51074 works for you ? Thanks.

**Comment by Akasurde** [comment]
resolved_by_pr #51074

**Comment by nicholasrodriguez** [comment]
#51074 tested, all parameters passed through to the vCenter VMs and they built ok.

**Comment by sivel** [comment]
The above PR has been merged and the functionality will be included in the 2.8 release.

**Comment by ManuelPerrot** [comment]
Solution alternative until ansible 2.8 is released:
Don't powerOn the VM after the OVF has been deployed with this module by setting:  `    power_on: no`

Then reconfigure the deployed VM using `vmware_guest` like this to add the extra props:
```
- name: Manipulate vApp properties
  vmware_guest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: present
    vapp_properties:
      - id: guestinfo.cis.appliance.ssh.enabled
        type: boolean
        value: "True"
        userConfigurable: true
  delegate_to: localhost
```

`userConfigurable: true` is required for some (all?) of them
