### ISSUE TITLE
Meta module: reset_connection is always failing

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#50306]
##### SUMMARY

meta: reset_connection is failing

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

meta

##### ANSIBLE VERSION

```paste below
2.7.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 14.04 on controller

##### STEPS TO REPRODUCE

```yaml
  handlers:

    - name: Reset
      meta: reset_connection

  tasks:

    - shell: echo "test"
      notify: "Reset"

```

Note that with a simple task it doesn't output anything:
```
  tasks:

    - name: Reset
      meta: reset_connection
```
Nothing is shown

##### EXPECTED RESULTS

It should say "success" or "changed"

##### ACTUAL RESULTS

It fails. Also not sure it actually reset the connection or not

```paste below
Result => "connection closed" but it's a failure (in red) so it can break playbooks when "stop as first error" parameter is set up
```
