### ISSUE TITLE
firewalld module task gets failed

### ISSUE THREAD

**Issue by roytanmoy** [ansible/ansible#50307]
##### SUMMARY

firewalld module task get failed
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.7.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

running ansible-playbook againest ubuntu 16.04

##### STEPS TO REPRODUCE

Running below playbooks and observed the failures -
```paste below
- name: Install firewalld
  tags: test
  become: yes
  package:
    name: firewalld
    state: present


- name: Allow external HTTP(S) traffic
  tags: test
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
```

```yaml

```

##### EXPECTED RESULTS

should run the command successfully without error

##### ACTUAL RESULTS

task is error out
TASK [ingress_nginx : Allow external HTTP(S) traffic] *******************************************************************************
failed: [35.168.58.179] (item=http) => {"changed": false, "item": "http", "msg": "Python Module not found: firewalld and its python module are required for this module,                         version 0.2.11 or newer required (0.3.9 or newer for offline operations)"}
failed: [35.168.58.179] (item=https) => {"changed": false, "item": "https", "msg": "Python Module not found: firewalld and its python module are required for this module,                         version 0.2.11 or newer required (0.3.9 or newer for offline operations)"}

**Comment by roytanmoy** [comment]
affects_2.7

**Comment by roytanmoy** [comment]
anybody looking into this issue?

**Comment by HauptJ** [comment]
I am having the same problem running against Fedora 28 and 29 when running Ansible 2.7.5.

I have tried using both the Python 2 and Python 3 Ansible interpreters to no avail. However, CentOS 7 does not appear to be effected by this problem.

Below are the tasks I am running.
```
---
# Tasks to install firewalld and fail2ban

- name: Install Ipset, FirewallD, and Fail2Ban with FirewallD on CentOS
  yum:
    name:
      - ipset
      - firewalld
      - fail2ban-firewalld
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Install Ipset, FirewallD, and Fail2Ban with FirewallD on Fedora
  dnf:
    name:
      - ipset
      - firewalld
      - fail2ban-firewalld
      - python3-firewall
      - cockpit
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Copy fail2ban.local configuration
  template:
    src: fail2ban.local
    dest: /etc/fail2ban/

- name: Copy jail.local configuration for fail2ban
  template:
    src: jail.local
    dest: /etc/fail2ban/
  notify: restart firewalld

- name: Firewalld service state
  service:
    name: firewalld
    state: started
    enabled: yes

- name: fail2ban service state
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: open ports with firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ open_ports }}"
  tags:
    - open_ports

- name: close ports with firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
    immediate: yes
  with_items: "{{ close_ports }}"
  tags:
    - close_ports

```
