### ISSUE TITLE
vultr_server doesn't honor ssh_keys parameter

### ISSUE THREAD

**Issue by berlic** [ansible/ansible#50304]
##### SUMMARY
The docs state that `vultr_server` does support `ssh_keys` and `ssh_key` as its alias, but module silently ignores `ssh_keys` and only `ssh_key` is recognized.

Additionally the docs state that `ssh_keys` is a *list*, but module accepts only single key name as string, giving error for lists: `Could not find sshkey with name: ['name1', 'name2']`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vultr_server

##### ANSIBLE VERSION
```
ansible 2.7.5
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
not relevant

##### STEPS TO REPRODUCE
```
    # ignores ssh_keys completely
    - vultr_server:
        state: present
        label: test
        plan: '1024 MB RAM,25 GB SSD,1.00 TB BW'
        region: Amsterdam
        os: 'Ubuntu 16.04 x64'
        ssh_keys: name1

    # rises error
    - vultr_server:
        state: present
        label: test
        plan: '1024 MB RAM,25 GB SSD,1.00 TB BW'
        region: Amsterdam
        os: 'Ubuntu 16.04 x64'
        ssh_key:
            - name1
            - name2
```
