### ISSUE TITLE
authorized_key messes up options when using comma-separated from= list in key_options

### ISSUE THREAD

**Issue by maetthu** [ansible/ansible#5032]
When specifying multiple patterns in the "from=" options for a key (like for example from="1.2.3.4,5.6.7.8."), the option parsing breaks for both the new key_options param as well as specifying the options directly in the key. This also breaks existing playbooks which worked for version <1.4. 

``` yml
tasks:
- name: key with options
  authorized_key: user=root key='from="1.*,2.*" ssh-rsa WHATEVER1 user@host' 
- name: key with key_options
  authorized_key: user=root key_options='from="1.*,2.*"' key="ssh-rsa WHATEVER2 user@host" 
```

results in following entries written to authorized_keys file

```
2.*,from="1.*" ssh-rsa WHATEVER1 user@host
2.*,from="1.*" ssh-rsa WHATEVER2 user@host
```

which should actually result in

```
from="1.*,2.*" ssh-rsa WHATEVER1 user@host
from="1.*,2.*" ssh-rsa WHATEVER2 user@host
```

$ ansible --version
ansible 1.4

Only difference in authorized_key module to devel branch is commit 32986c4d, though this version just breaks differently, resulting authorized_keys file is

```
2.*",from="""1.*"" ssh-rsa WHATEVER1 user@host
2.*",from=""1.*" ssh-rsa WHATEVER2 user@host
```

Specifying multiple host-patterns in a comma-separated list in the "from" option is documented in the man-page of authorized_keys:

```
from="pattern-list"
        Specifies that in addition to public key authentication, either
        the canonical name of the remote host or its IP address must be
        present in the comma-separated list of patterns.  See PATTERNS in
        ssh_config(5) for more information on patterns.
```

**Comment by mpdehaan** [comment]
@jimi-c all yours

**Comment by jctanner** [comment]
test patch:

```
diff --git a/library/system/authorized_key b/library/system/authorized_key
index db0425d..ac9df88 100644
--- a/library/system/authorized_key
+++ b/library/system/authorized_key
@@ -177,7 +177,14 @@ def parseoptions(options):
     '''
     options_dict = {}
     if options:
-        options_list = options.strip().split(",")
+        lex = shlex.shlex(options)
+        lex.quotes = ["'", '"']
+        lex.whitespace_split = True
+        opt_parts = list(lex)
+        open("/tmp/awx.log", "a").write("opt_parts: %s\n" % opt_parts)
+
+        #options_list = options.strip().split(",")
+        options_list = opt_parts
         for option in options_list:
             # happen when there is comma at the end
             if option == '':
@@ -187,7 +194,8 @@ def parseoptions(options):
             else:
                 arg = option
                 val = None
-            options_dict[arg] = val
+            options_dict[arg] = val.replace('"', '').replace("'", "")
+    open("/tmp/awx.log", "a").write("options_dict: %s\n" % options_dict)
     return options_dict

 def parsekey(raw_key):
```

**Comment by maetthu** [comment]
Works better, but not completely fixed (still breaks my existing playbooks). Additional options are not parsed correctly:

```
  tasks:
  - name: key with options
    authorized_key: user=root key='from="1.*,2.*",no-X11-forwarding,no-agent-forwarding ssh-rsa WHATEVER1 user@host' state=present 
  - name: key with key_options
    authorized_key: user=root key_options='from="1.*,2.*",no-X11-forwarding,no-agent-forwarding' key="ssh-rsa WHATEVER2 user@host" state=present 
```

includes additional options within double quotes:

```
from="1.*,2.*,no-X11-forwarding,no-agent-forwarding" ssh-rsa WHATEVER1 user@host
from="1.*,2.*,no-X11-forwarding,no-agent-forwarding" ssh-rsa WHATEVER2 user@host
```

If additional options are placed before from list, like

```
key_options='no-X11-forwarding,no-agent-forwarding,from="1.*,2.*"'
```

The resulting authorized_key entry is fine:

```
no-X11-forwarding,no-agent-forwarding,from="1.*,2.*" ssh-rsa WHATEVER2 user@host
```
