### ISSUE TITLE
commit replace whe

### ISSUE THREAD

**Issue by santhosh1vaddi** [ansible/ansible#50350]
##### SUMMARY
i am trying to push config from the file using SSH keys for authentication. it clears complete configs in the device with below mentioned error and i am not able to login to device as it is clearing management interface configs 

##### ISSUE TYPE
- Bug Report
```
[centos@dev-ansibile cisco]$ ansible-playbook cisco_push.yml

PLAY [Configure IOS-XR devices] ***************************************************************************************************************************************************************

TASK [configure interface] ********************************************************************************************************************************************************************
[DEPRECATION WARNING]: Param 'ssh_keyfile' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
fatal: [192.168.100.10]: FAILED! => {"changed": false, "msg": "timeout trying to send command: commit replace"}
	to retry, use: --limit @/home/centos/test/cisco/cisco_push.retry

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.100.10             : ok=0    changed=0    unreachable=0    failed=1 
```
##### COMPONENT NAME

```paste below
iosxr_config
```
##### ANSIBLE VERSION

```paste below
ansible 2.7.2
```

##### CONFIGURATION

```paste below
interface Loopback101
 description super-service-vpn_service 
 ipv4 address 10.0.10.1 255.255.255.252
!
# just for testing purpose #
```

##### OS / ENVIRONMENT

Cisco IOSXRV
##### STEPS TO REPRODUCE

SSH login without password from the Ansible machine to XRv 
device config file with above content.
run below ansible playbook.

```yaml
---
### This play book is to push config to Cisco Router
- name: Configure IOS-XR devices
  hosts: IOSXR
  gather_facts: no
  # connection local instead of network_cli
  connection: local

  tasks:
  - name: configure interface
    iosxr_config:
       username: automation1
       ssh_keyfile: /home/centos/.ssh/id_rsa
       src: config.cfg
       replace: config

```

##### EXPECTED RESULTS

need to configure device without mentioning password in the /etc/ansible/host file.

##### ACTUAL RESULTS

```paste below
[centos@dev-ansibile cisco]$ ansible-playbook cisco_push.yml 

PLAY [Configure IOS-XR devices] ***************************************************************************************************************************************************************

TASK [configure interface] ********************************************************************************************************************************************************************
fatal: [192.168.100.9]: FAILED! => {"changed": false, "msg": "timeout trying to send command: commit replace"}
        to retry, use: --limit @/home/centos/test/cisco/cisco_push.retry

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.100.9              : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/iosxr/iosxr_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/iosxr/iosxr_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @gdpak @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@santhosh1vaddi, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by santhosh1vaddi** [comment]
@ansibot... could you please elaborate on the solution to get this working.
what i need is when i use ansible playbook to configure iosXRv, playbook should use SSH key instead of password.
i configured junos using SSH key using below playbook and it works fine. but same with cisco module (iosxr_config) doesnt work.

```yaml
---
- name: Push Config to Juniper VMX Routers
 hosts: localhost
 gather_facts: no
 connection: local

 tasks:
 - name: Push Config Service
   junos_config:
          username: "{{ user_name }}"
          #password: "{{ password }}"
          ssh_keyfile: "/home/centos/.ssh/id_rsa"
          src: "{{config_file}}"
```

**Comment by justjais** [comment]
@santhosh1vaddi from `2.5` onwards we have deprecated the use of provider and we encourage to use `network_cli` as the connection method. So, can you please try with **_connection: network_cli_** instead of **_connection: local_**, for your reference for _junos_ you can follow: https://docs.ansible.com/ansible/latest/network/user_guide/platform_junos.html, same should follow for _iosxr_ devices as well. 
Please let me know if you still face the issue.

**Comment by santhosh1vaddi** [comment]
Hi Sumit,

Thanks for your response. 

Right now I am using below ansible playbook to configuration using ssh-key.

---
- hosts: IOSXR
  gather_facts: no
  connection: local

  tasks:
  - name: configure interface
    iosxr_config:
      src: cisco_code.cfg

I have changed below parameters to use ssh-key for router login.

===== Changes in Ansible config file=====
private_key_file = "key_path"
host_key_checking = False
host_key_auto_add = True

Please advise is this the correct way.

Also, from the link you have shared, below config needs to be done in host inventory (@/etc/ansible/hosts) file??



Second problem I am facing is when I use replace: config in the playbook. When I run playbook it gives an error with "commit replace”.  Which clears complete config in the router(IOSXR-v).

Please advise what exactly replace: config does? 

Because when I use below playbook with username and clear text password, it works fine. 

  tasks:
  - name: configure interface
    iosxr_config:
      src: cisco_code.cfg
      replace: config

But when I run same playbook with username/ssh-key it gives error and clears existing config from router.

Please advise.

Santhosh Sant
santhosh.vaddi@gmail.com

**Comment by justjais** [comment]
@santhosh1vaddi have you tried using **_connection: network_cli_** instead of **_local_**, as it seems you are still trying to run over `local` connection. Can you please modify your playbook with the connection as `network_cli`.
```
---
- hosts: junos
  gather_facts: no
  connection: network_cli
  tasks:
  - name: login to device and check with rsa id
    junos_command:
      commands: show version
```
and its inventory:
```
[junos]
an-vsrx-01.ansible.eng.rdu2.redhat.com

[junos:vars]
ansible_connection=network_cli
ansible_network_os=junos
ansible_user=ansible
```
And, this if your system is authorized you can directly run the play without any issue. Before running the play you can check if you are able to login to the device via: `ssh -i id_rsa user@hostname`. Similar should work for `iosxr` as well.
