### ISSUE TITLE
NXAPI Issue

### ISSUE THREAD

**Issue by feisa** [ansible/ansible#50355]
##### SUMMARY
We are receiving errors using nxapi as our connection type
enable: CLI execution error" 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxapi connection issues when using  nxos_feature and nxos_conifg 
##### ANSIBLE VERSION
ansible 2.7.2
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
##### CONFIGURATION

```
Role 
- name: Check SSH Key Settings
  nxos_command:
    commands:
      - show ssh key 
  register: sshkey

- name: Update SSH Keys to stronger encryption
  block:  
     - name: Disable SSH 
       nxos_feature:
        feature: ssh
        state: disabled

     - name: Enable Telnet (Safety Net)
       nxos_feature:
        feature: telnet 
        state: enabled

     - nxos_config:
        lines:
#          - no feature ssh 
#          - feature telnet
          - ssh key rsa 2048 force

     - name: Enable SSH
       nxos_feature:
        feature: ssh
        state: enabled

     - name: Disable Telnet (Pass Pentest)
       nxos_feature:
        feature: telnet
        state: disabled
  when: "'2048' not in sshkey|string"
```

group vars
ansible_connection: httpapi
ansible_network_os: nxos
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
##### OS / ENVIRONMENT
centos 7.5
##### STEPS TO REPRODUCE
Run a playbook
##### EXPECTED RESULTS

```
ok: [device] => {
    "output": {
        "changed": false, 
        "failed": false, 
        "stdout": [
            "**************************************\nrsa Keys generated:Sun Sep  9 16:26:46 2018\n\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCfxFLX3lLtzvc+VF3dN+2o0yS9k56eujcmXJJEBhPmDoBJivtbBKJ3QEh+25ZtvKtuA/hJl4XWes/lJ6cSrGX2EEbGQEs9vdmATxbazO/e9i4j/mIAc9La6SpdQwHRalDsHvy7HhcwdT/COQreoY71rgoUKONt1yeeQVc6LWn5Hw==\n\nbitcount:1024\nfingerprint:\n68:45:0f:99:db:0f:b9:bc:9f:32:50:3b:a2:54:52:65\n**************************************\ncould not retrieve dsa key information\n**************************************"
        ], 
        "stdout_lines": [
            [
                "**************************************", 
                "rsa Keys generated:Sun Sep  9 16:26:46 2018", 
                "", 
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCfxFLX3lLtzvc+VF3dN+2o0yS9k56eujcmXJJEBhPmDoBJivtbBKJ3QEh+25ZtvKtuA/hJl4XWes/lJ6cSrGX2EEbGQEs9vdmATxbazO/e9i4j/mIAc9La6SpdQwHRalDsHvy7HhcwdT/COQreoY71rgoUKONt1yeeQVc6LWn5Hw==", 
                "", 
                "bitcount:1024", 
                "fingerprint:", 
                "68:45:0f:99:db:0f:b9:bc:9f:32:50:3b:a2:54:52:65", 
                "**************************************", 
                "could not retrieve dsa key information", 
```

##### ACTUAL RESULTS
```
ok: [device]=> {
    "output": {
        "changed": false, 
        "failed": true, 
        "msg": "enable: CLI execution error"
    }
}
```
