### ISSUE TITLE
[rabbitmq_user] Changes user's tags even when they are not defined

### ISSUE THREAD

**Issue by ptzianos** [ansible/ansible#50359]
##### SUMMARY
rabbitmq_user will empty an existing user's tags even when there is not `tags` field present in the configuration. It should differentiate between an empty list and a non-existent list of tags.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rabbitmq_user

##### ANSIBLE VERSION

```paste below
ansible 2.7.2
  config file = None
  configured module search path = [u'/home/pavlos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pavlos/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/pavlos/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 17:08:05) [GCC 5.4.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Ubuntu 16.04 64-bit

##### STEPS TO REPRODUCE
Supposing that a user called `user1` already exists and has a tag `some_tag`.

```yaml
rabbitmq_users:
  - {user: 'user1', password: 'pass', permissions: [{configure_priv: '.*', read_priv: '.*', write_priv: '.*', vhost: '/'}]}

- rabbitmq_user:
    user: "{{ item.name }}"
    permissions: "{{ admin_privileges }}"
  with_items:
    - "{{ rabbitmq_users }}"
  notify:
    - restart rabbitmq
```

##### EXPECTED RESULTS
In the example above I am not specifying a `tags` field for the user. If the user is already present, I do not want any tags, if they exist to be changed.

##### ACTUAL RESULTS
If the user is present and has some tags, the script will remove any tags, even though I have not specified that.
