### ISSUE TITLE
[rabbitmq_user] Allow tags to be a list of strings

### ISSUE THREAD

**Issue by ptzianos** [ansible/ansible#50360]
##### SUMMARY
rabbitmq_user expects tags to a string of comma separated tags. We should be able to provide a list of strings also.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/messaging/rabbitmq/rabbitmq_user.py

##### ADDITIONAL INFORMATION
Internally the string is split and converted into a list anyway. This would be useful, because the list of tags of users could be generated on the fly from the script.

```yaml
- rabbitmq_user:
    user: user1
    password: pass1
    tags: ["tag1","tag2"]
```
