### ISSUE TITLE
sysctl module does not enable net.ipv4.ip_forward .

### ISSUE THREAD

**Issue by roytanmoy** [ansible/ansible#50377]
##### SUMMARY

sysctl module fails to eanable flag net.ipv4.ip_forward in sysctl file
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

sysctl
##### ANSIBLE VERSION

```paste below
ansible 2.7.2
```

##### CONFIGURATION

```paste below
# Set ip forwarding on in /proc and /etc/ufw/sysctl.conf file and reload ("sysctl --system")
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
```

##### OS / ENVIRONMENT

ubuntu 16.04
##### STEPS TO REPRODUCE

```yaml
- name: Install and Update Python
  raw: sudo bash -c "test -e /usr/bin/pyhton || (apt -qqy update && apt install -qy python)"

- name: turn off swap
  command: swapoff -a

# Set ip forwarding on in /proc and /etc/ufw/sysctl.conf file and reload ("sysctl --system")
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

~                 
```

##### EXPECTED RESULTS

should enable the *net.ipv4.ip_forward=1* in sysctl.conf file
##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
cc @Akasurde @davixx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Is the setting not present in the `sysctl.conf` file? You may need to restart the system or a service in order for this to take affect. What are you expecting to see that indicates to you this module has worked?

needs_info

**Comment by ansibot** [comment]
@roytanmoy This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by orodbhen** [comment]
I'm seeing this same behavior on CentOS 7, except I'm setting it to `0`. The playbook completed sucessfully, but `sysctl -a | grep ipv4` shows `net.ipv4.ip_forward=1`. 

```yml
- name: Ensure sysctl net.ipv4.ip_forward is set to 0
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
        reload: yes
```

Rebooting the system doesn't change this, but running `sysctl -p` manually does. What exactly is `reload` supposed to do?
