### ISSUE TITLE
Loop over include_role with tasks_from always uses last value

### ISSUE THREAD

**Issue by mveroone** [ansible/ansible#50372]
##### SUMMARY

When trying to factor code by looping ofer task books of the same role, only the latest one is run N times

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```paste below
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mveroone/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['timer', 'profile_tasks']
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/mveroone/.vault_pass
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Fedora 28

##### STEPS TO REPRODUCE

```yaml
- include_role:
    name: myrole
    tasks_from: {{item}}.yml
  loop
  - tasks1
  - tasks2
```

##### EXPECTED RESULTS

Playbooks runs taskbook "taskl1" then "task2"

##### ACTUAL RESULTS

Playbook runs "task2" twice

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@mveroone Thanks for reporting this issue. Pardon me if I am missing something but I am not able to reproduce this 

```
PLAYBOOK: sample_include_test.yml **********************************************************************************************
1 plays in sample_include_test.yml

PLAY [Include role with loop] **************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
task path: /Volumes/data/src/ansible/playbooks/core/sample_include_test.yml:2
ok: [localhost]
META: ran handlers

TASK [include_role] ************************************************************************************************************
task path: /Volumes/data/src/ansible/playbooks/core/sample_include_test.yml:5

TASK [sample_include : debug] **************************************************************************************************
task path: /Volumes/data/src/ansible/playbooks/core/sample_include/tasks/task1.yml:1
ok: [localhost] => {
    "msg": "I am from task one"
}

TASK [sample_include : debug] **************************************************************************************************
task path: /Volumes/data/src/ansible/playbooks/core/sample_include/tasks/task2.yml:1
ok: [localhost] => {
    "msg": "I am from task two"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

Playbook
```yaml
---
- name: Include role with loop
  hosts: localhost
  tasks:
    - include_role:
        name: sample_include
        tasks_from: "{{ item }}.yml"
      loop:
      - task1
      - task2
``` 
I am using Ansible 2.5.

needs_info

**Comment by mveroone** [comment]
Here is my exact reproducing case :  

Playbook :  
```
---
- hosts: prometheus
  become: yes
  tasks:
  - include_role:
      name: prometheus
      tasks_from: "prom_{{ item }}.yml"
    loop:
    - cadvisor
    - node_exporter
    - rancher_exporter
    tags: prometheus
```
Role :  
```
#tree roles/prometheus
roles/prometheus
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── tasks
│   ├── main.yml
│   ├── prom_cadvisor.yml
│   ├── prom_node_exporter.yml
│   └── prom_rancher_exporter.yml
└── templates
    └── prometheus.yml.j2
```

taskbooks are single-task blockinfiles :  
```
roles/prometheus/tasks/prom_cadvisor.yml:- name: Configure prometheus targets for cAdvisor
roles/prometheus/tasks/prom_node_exporter.yml:- name: Configure prometheus targets for Docker Node Exporters
roles/prometheus/tasks/prom_rancher_exporter.yml:- name: Configure prometheus targets for Rancher Exporters
```

Example :  
```
- name: Configure prometheus targets for Docker Node Exporters
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    insertafter: "^scrape_config:"
    marker: "# Ansible {mark} Node Exporter Docker"
    block: |2
      {% for env, env_name in rancher_environments.iteritems() %}
        - job_name: 'docker-node-{{ env }}'
          static_configs:
           - targets:
      {%   for hostname in groups['docker-'~env] %}
             - {{ hostvars[hostname]['ansible_host'] }}:9100
      {%   endfor %}
             labels:
               rancher_environment: "{{ rancher_environments[env] }}"
      {% endfor %}
  notify: "reload prometheus"
```
They only differ by the block content, marker and task name.


Does this help ?
