### ISSUE TITLE
Imgadm Docker support

### ISSUE THREAD

**Issue by m1cr0man** [ansible/ansible#50399]
##### SUMMARY
SmartOS' imgadm supports importing Docker images from the Docker hub. The imgadm module currently supports adding the Docker Hub repository, but not pulling images from it.

In order to actually deploy Docker based images on SmartOS, there needs to be a way to specify a Docker image tag in the imgadm module and resolve its UUID.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
imgadm module

##### ADDITIONAL INFORMATION
The imgadm module currently verifies that the UUID provided matches the UUID format. Changing this behaviour would not be desirable, instead adding some new field which allows the user to specify the Docker image tag to use would be best.

However, only a few imgadm subcommands support Docker tags - namely `show` and `import`. For other subcommands (e.g. `delete`) the module will need to map the Docker tag to the UUID first using `show` then pass that onto the `delete` subcommand.

For use with vmadm, a UUID is also still necessary. When using Docker tags with the imgadm module, it must still return a UUID which can then be used to spin up actual zones using the imported image. This also means that imgadm is the only module that needs extensions to support Docker images in Ansible on SmartOS.

Example playbook:
```yaml
---
- hosts: baremetal
  tasks:
          - name: hello-world imported
            register: helloworld
            imgadm:
              tag: hello-world:latest
              state: present

         # Although a tag was used, the UUID will still be resolved allowing the user to spin up a VM with vmadm
          - debug: var=helloworld.uuid
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/galaxy/data/apb/tasks/main.yml.j2](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/tasks/main.yml.j2)
* [lib/ansible/modules/cloud/smartos/imgadm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/smartos/imgadm.py)
* [lib/ansible/modules/cloud/smartos/smartos_image_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/smartos/smartos_image_facts.py)
* [lib/ansible/modules/cloud/smartos/vmadm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/smartos/vmadm.py)
* [lib/ansible/modules/utilities/logic/import_role.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/import_role.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jasperla @xen0l
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by m1cr0man** [comment]
The introduction of the `tag` property does raise some confusion around what the `type` property does, but I feel it is out of scope to address that.

**Comment by sivel** [comment]
!component =lib/ansible/modules/cloud/smartos/imgadm.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/smartos/imgadm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/smartos/imgadm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @L2G @bcoca @brontitall @dagwieers @dermute @jpdasma @scathatheworm @szinck @troy2914
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @fishman @mator
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by precurse** [comment]
I wrote up a patch that's been working for me. It's up here in case anyone wants to try it: https://github.com/precurse/ansible/commit/c84392bc4b85fdf4a1b523ea6a248bf4285080aa 

I'll create a PR for it once I'm happy with it. 

Also, I don't think `tag:` is a fitting name for it. The command refers to the value as:
```
imgadm import <docker repo:tag>
```
Tag is only the latter portion of the value (such as `latest` or `v1.23`).

**Comment by m1cr0man** [comment]
Yeah that sounds good with the docker boolean instead of the tag module. Would you mind if I modified my PR to use that convention, or do you want to submit a pr from your work?

**Comment by precurse** [comment]
I can submit the PR for it. If you're also good with the `name` attribute to specify the name of an image? I'm open to change that if it makes more sense.

Personally, I'd like to be able to use the following syntax:
```
# For Docker:
imgadm;
  name: alpine:3.7
  docker: True
  state: present  # or latest

# For non-Docker (which I can implement at a later date)
imgadm:
  name: base-64-lts
  docker: False   # optional
  state: present   # or latest
```

Once this is implemented, I could work on adding similar functionality to `vmadm` to specify image name instead of only UUID.

Let me know what you think.

Cheers
