### ISSUE TITLE
"changed_when" can't be a list of conditions (while "when" can)

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#50404]
##### SUMMARY

changed_when can't be a list (and probably failed_when too) while "when" can

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

changed_when
failed_when (maybe)

##### ANSIBLE VERSION

```paste below
2.7.2
```

##### OS / ENVIRONMENT

ubuntu 14.04

##### STEPS TO REPRODUCE

```yaml
- name: Init borg repos with passphrase
  shell: "borgmatic --init --encryption repokey --verbosity 1"
  register: reg_var
  changed_when:
    - "Initializing repository at" in reg_var.stderr
    - "Done." in reg_var.stderr
```

##### EXPECTED RESULTS

It should work as written here https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#the-when-statement

With this, it works fine:

```yaml
- name: Init borg repos with passphrase
  shell: "borgmatic --init --encryption repokey --verbosity 1"
  register: reg_var
  changed_when: >
    "Initializing repository at" in reg_var.stderr
    and "Done." in reg_var.stderr
```

but it's harder to read

##### ACTUAL RESULTS

```paste below
ERROR! Syntax Error while loading YAML.
  did not find expected '-' indicator
```

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration/targets/changed_when/aliases](https://github.com/ansible/ansible/blob/devel/test/integration/targets/changed_when/aliases)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@BarbzYHOOL Thanks for reporting this issue. I agree the error message is not that specific but 

Could you please try this - 

```yaml
- name: Init borg repos with passphrase
  shell: "borgmatic --init --encryption repokey --verbosity 1"
  register: reg_var
  changed_when:
    - '"Initializing repository at" in reg_var.stderr' # <--- Notice single quotes
    - '"Done." in reg_var.stderr' # <--- Notice single quotes
```

TL;DR - Value specified starts with quotation and YAML parser expects to see line ended with same kind of quote. So, you may need to quote entire value.
