### ISSUE TITLE
Can we get this fetchlistfromdict added as a standard filter?

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#50410]
Can we simply just add this to the default filters available?
https://gist.github.com/smarthall/1e302b40f38ddd4e218d

The reason I'm asking for this is because I had a problem with using `with_items` or even trying to build a variable list to use with the gluster volume_manager. Eveything I attempted wouldn't pass all of my list to the `cluster` value:

```
    - name: create gluster volume
      gluster_volume:
        force: true
        state: present
        name: home
        bricks: /gluster-data/export1,/gluster-data/export2
        rebalance: yes
        cluster: "{{ hostvars|fetchlistfromdict(groups['glusterfs'])|map(attribute='private_ip')|list }}"
      run_once: true
```
I couldn't find any other concise way to do this either.
