### ISSUE TITLE
get_nic_inventory() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by warusadura** [ansible/ansible#50426]
##### SUMMARY

When executing the following [playbook](https://github.com/dnuka/automate/blob/master/ansible/redfish_102.yaml) against [sushy-static](https://github.com/openstack/sushy-tools) emulator on a remote Ubuntu server, results `get_nic_inventory() takes exactly 2 arguments (1 given)` error.

[playbook](https://github.com/dnuka/automate/blob/master/ansible/redfish_102.yaml)
```
- hosts: all
  remote_user: root
  tasks:
    - name: test redfish_facts module
      redfish_facts:
        category: all
        command: all
        baseuri: 0.0.0.0:8000
        username: test
        password: test
```
complete error message:
`fatal: [HOST]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to HOST closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1546339821.8157866-20711827649674/AnsiballZ_redfish_facts.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1546339821.8157866-20711827649674/AnsiballZ_redfish_facts.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1546339821.8157866-20711827649674/AnsiballZ_redfish_facts.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_redfish_facts_payload_5_vVIy/__main__.py\", line 268, in <module>\r\n  File \"/tmp/ansible_redfish_facts_payload_5_vVIy/__main__.py\", line 211, in main\r\nTypeError: get_nic_inventory() takes exactly 2 arguments (1 given)\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_facts

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
python version = 3.7.2rc1 (default, Dec 12 2018, 06:25:49) [GCC 8.2.0]
```
