### ISSUE TITLE
get_url fails to download https url on Ubuntu 16.04

### ISSUE THREAD

**Issue by zaixi** [ansible/ansible#50436]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

get_url module

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /home/liyj/github/ansible-ubuntu/ansible.cfg
  configured module search path = [u'/home/liyj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- name: get public_key                                                                       
  get_url:
    url: https://build.opensuse.org/projects/home:manuelschneid3r/public_key
    dest: /tmp/albert_gpg
```

##### EXPECTED RESULTS

The file should be downloaded

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => changed=false 
  dest: /tmp/albert_gpg
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  state: absent
  status_code: 404
  url: https://build.opensuse.org/projects/home:manuelschneid3r/public_key
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/get_url.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The problem here appears to be with the URL you are requesting.  It seems to require that an `Accept` header be passed along with it.

rfc2616 states:

> If no Accept header field is present, then it is assumed that the client accepts all media types.

So the server handling the request is not RFC2616 compliant.

However, to work around the issue, you can simply add:

```
- name: get public_key                                                                       
  get_url:
    url: https://build.opensuse.org/projects/home:manuelschneid3r/public_key
    dest: /tmp/albert_gpg
    headers:
      Accept: '*/*'
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
