### ISSUE TITLE
docker_swarm_service crashes due to bad default

### ISSUE THREAD

**Issue by hannseman** [ansible/ansible#50467]
##### SUMMARY

Using `docker_swarm_service` with `configs` set crashes on the second run.

It appears like this issue was introduced in https://github.com/ansible/ansible/pull/45674 where `DockerService.configs` was set to `None` instead of `[]` in the `__init__()`. If `configs` is set to `[]` everything works as expected.

I understand that the changes in https://github.com/ansible/ansible/pull/45674 was made to support older docker clients so maybe something more compatible needs to be made than just changing the default. Maybe @dariko has some insight here?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_swarm_service

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /Users/home/project/docker/ansible.cfg
  configured module search path = ['/Users/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/home/project/docker/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/home/project/docker/venv/bin/ansible
  python version = 3.7.1 (default, Nov 26 2018, 09:06:10) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/home/project/docker/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/home/project/docker/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/Users/home/project/docker/ansible.cfg) = ['/Users/home/project/docker/inventories/dev/hosts']
DEFAULT_REMOTE_USER(/Users/home/project/docker/ansible.cfg) = ubuntu
DEFAULT_ROLES_PATH(/Users/home/project/docker/ansible.cfg) = ['/Users/home/project/docker/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/home/project/docker/ansible.cfg) = /Users/home/project/docker/.vault_pass
DIFF_ALWAYS(/Users/home/project/docker/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/home/project/docker/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/home/project/docker/ansible.cfg) = False
```

##### OS / ENVIRONMENT

This is the docker version I'm running:

```
$ uname -a
Linux host 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

And docker python library:
```
$ pip freeze | grep docker
docker==3.6.0
docker-pycreds==0.4.0
```
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  become: true
  tasks:
    - docker_config:
        name: "config"
        data: "hello"
      register: "config"

    - docker_swarm_service:
        name: "test"
        image: "nginx"
        constraints:
          - "node.role == manager"
        replicas: "1"
        restart_policy: "any"
        configs:
          - config_id: "{{ config.config_id }}"
            config_name: "config"
            filename: "/tmp/config.ini"
```

##### EXPECTED RESULTS

No exceptions thrown and config being set to service.

##### ACTUAL RESULTS

```
"Error looking for service named app: 'NoneType' object has no attribute 'append'"
```

And traceback
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_docker_swarm_service_payload_bAzTnv/__main__.py", line 1061, in run
    current_service = self.get_service(module.params['name'])
  File "/tmp/ansible_docker_swarm_service_payload_bAzTnv/__main__.py", line 967, in get_service
    ds.configs.append({
```
