### ISSUE TITLE
Ansible Timeout

### ISSUE THREAD

**Issue by exd42062** [ansible/ansible#50476]
##### SUMMARY
I'm getting a timeout message from Ansible when running playbook against 3 devices.  When I run same playbook separately for each device it works fine, but when I run against all 3 devices in same play it timesout.

##### ISSUE TYPE
- timeout occurs when running play against multiple devices

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION

``root@NetworkAutomation-1:~# ansible --version
ansible 2.7.0
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
root@NetworkAutomation-1:~# ansible-config view -c ansible.cfg
[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it
can also be a list of hosts, a directory or a list of paths , use [defaults]
inventory=/path/to/file|dir instead. This feature will be removed in version
2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False
 in ansible.cfg.
[defaults]
# Specify the location for the log file
export ANSIBLE_LOG_PATH=~/ansible.log
# Enable Debug
export ANSIBLE_DEBUG=True
hostfile = ./hosts
host_key_checking = False
timeout = 5


```

##### OS / ENVIRONMENT

GNS3 Network Automation Appliance

##### STEPS TO REPRODUCE

ansible-playbook fd-sw-template.yml

```yaml
---
- name: Manage GNS3 devices
  hosts: gns3-core
  gather_facts: false
  connection: local

  vars:
    cli:
      username: cisco
      password: cisco

  tasks:
    - name: enable services
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        lines:
          - service timestamps debug datetime msec localtime
          - service timestamps log datetime msec localtime
          - service password-encryption
          - service tcp-keepalives-in
          - service tcp-keepalives-out
          - service sequence-numbers
          - ip domain-name freshdirect.com

      register: print_output

    -  debug: var=print_output
```

##### EXPECTED RESULTS

to complete successfully 

##### ACTUAL RESULTS

The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ios_config_payload_ym_S36/ansible_ios_config_payload.zip/ansible/module_utils/network/ios/ios.py", line 114, in get_config
    out = connection.get_config(flags=flags)
  File "/tmp/ansible_ios_config_payload_ym_S36/ansible_ios_config_payload.zip/ansible/module_utils/connection.py", line 173, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

fatal: [SW2]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": true,
            "backup": false,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "force": false,
            "host": null,
            "intended_config": null,
            "lines": [
                "service timestamps debug datetime msec localtime",
                "service timestamps log datetime msec localtime",
                "service password-encryption",
                "service tcp-keepalives-in",
                "service tcp-keepalives-out",
                "service sequence-numbers",
                "ip domain-name freshdirect.com"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "replace": "line",
            "running_config": null,
            "save": false,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "command timeout triggered, timeout value is 10 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}

```paste below

```
