### ISSUE TITLE
pip module should allow version=latest calling syntax

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#50487]
##### SUMMARY
Currently its very hard to parametrize the use of pip module for locking a package to a specific version or just installing the latest version.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
pip

##### ADDITIONAL INFORMATION
Example of real world usage which resorts to jinja2 abuse for working around the current pip module limitations

```yaml
- name: Install ara
  become: true
  pip:
    name: ara
    version: "{% if undercloud_ara_version == 'latest' %}{{ omit }}{% else %}{{ undercloud_ara_version }}{% endif %}"
    state: "{% if undercloud_ara_version == 'latest' %}latest{% else %}present{% endif %}"

```

If pip module would also allow the `latest` version parameter, its usage could highly be simplified, making code easier to read and maintain.

Mainly these two syntaxes should have the same effect
```yaml
# proposed
  - version: latest
# current:
   - status: latest
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/language/pip.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Lujeni @mattupstate @webknjaz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
We have discussed this and have decided against adding this functionality.

The recommendation would be to do one of the following:

1. Use `state=latest` but always provide version pinning in `name` via `ara=x.y.z`. Not pinning an actual version and just using `state: present` will undoubtedly lead to unexpected results
1. Use the `ternary` filter instead of the more verbose jinja you have used:

    ```
    - name: Install ara
      become: true
      pip:
        name: ara
        version: "{{ (undercloud_ara_version == 'latest')|ternary(omit, undercloud_ara_version) }}"
        state: "{{ (undercloud_ara_version == 'latest')|ternary(latest, present) }}"
    ```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
