### ISSUE TITLE
create junos_ping module

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#50497]
##### SUMMARY
create a junos_ping module to match functionality with ios_ping (https://docs.ansible.com/ansible/latest/modules/ios_ping_module.html)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
junos_ping

##### ADDITIONAL INFORMATION
make this work with net_ping

```yaml
- name: Test reachability to 10.10.10.10 using default vrf
  junos_ping:
    dest: 10.10.10.10
```
