### ISSUE TITLE
zabbix action operations not updated

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#50517]
##### SUMMARY
Recovery operations are not added for existing actions.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
devel

##### CONFIGURATION
```
DEFAULT_FORKS(/opt/ansible/config/ansible-config-hostname.cfg) = 100
DEFAULT_HOST_LIST(/opt/ansible/config/ansible-config-hostname.cfg) = [u'/opt/ansible/inventory/cert/hosts']
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config-hostname.cfg) = False
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
Create a simple trigger action, perhaps like so:

```yaml
- zabbix_action:
    server_url: "http://localhost/zabbix/"
    login_user: zbx_api_cli
    login_password: "{{zbx_api_cli_password}}"
    state: present
    status: enabled
    name: "auto resp: update motd"
    event_source: 'trigger'
    conditions:
      - type: 'host_group'
        operator: '='
        value: 'Linux servers'
    operations:
      - type: 'remote_command'
        command_type: 'custom_script'
        execute_on: 'server'
        command: command
        run_on_hosts:
          - 0
    recovery_operations:
      - type: 'remote_command'
        command_type: 'custom_script'
        execute_on: 'server'
        command: command
        run_on_hosts:
          - 0
```

Go to the Zabbix UI, remove the recovery operation and save the action, then re-run the playbook.

##### EXPECTED RESULTS
Recovery operation is added.

##### ACTUAL RESULTS
The recovery operation is not added.
