### ISSUE TITLE
zabbix action always reported as changed

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#50518]
##### SUMMARY
If a Zabbix action is created and the same playbook run again, it always reports the action as changed, even though there have been no changes made to the playbook/role or the action itself.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
devel

##### CONFIGURATION
```paste below
DEFAULT_FORKS(/opt/ansible/config/ansible-config-hostname.cfg) = 100
DEFAULT_HOST_LIST(/opt/ansible/config/ansible-config-hostname.cfg) = [u'/opt/ansible/inventory/cert/hosts']
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config-hostname.cfg) = False
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
Create a simple trigger action, perhaps like so:

```yaml
- zabbix_action:
    server_url: "http://localhost/zabbix/"
    login_user: username
    login_password: "password"
    state: present
    status: enabled
    name: "auto resp: update motd"
    event_source: 'trigger'
    conditions:
      - type: 'host_group'
        operator: '='
        value: 'Linux servers'
    operations:
      - type: 'remote_command'
        command_type: 'custom_script'
        execute_on: 'server'
        command: command
        run_on_hosts:
          - 0
    recovery_operations:
      - type: 'remote_command'
        command_type: 'custom_script'
        execute_on: 'server'
        command: command
        run_on_hosts:
          - 0
```

Run the playbook twice.

##### EXPECTED RESULTS
The first run reports action as changed (created), the second run reports it as unchanged.

##### ACTUAL RESULTS
Action is reported as changed on the second run.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/zabbix/zabbix_action.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/zabbix/zabbix_action.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @D3DeFi @K-DOT @eikef @rubentsirunyan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rubentsirunyan** [comment]
@richlv thank you for reporting this issue. Which Zabbix version are you using? I am checking on 3.4 and everything works as expected.

**Comment by richlv** [comment]
Tested with Zabbix 4.0.3.

**Comment by rubentsirunyan** [comment]
I can't reproduce this.

I tested with both 3.4 and 4.0. Second time it reports as _ok_

```
- connection: local
  hosts: localhost
  tasks:
    - name: Deploy new action
      zabbix_action:
        server_url: "http://192.168.10.{{ item }}/zabbix/"
        login_user: Admin
        login_password: "zabbix"
        state: present
        status: enabled
        name: "auto resp: update motd"
        event_source: 'trigger'
        conditions:
          - type: 'host_group'
            operator: '='
            value: 'Linux servers'
        operations:
          - type: 'remote_command'
            command_type: 'custom_script'
            execute_on: 'server'
            command: command
            run_on_hosts:
              - 0
        recovery_operations:
          - type: 'remote_command'
            command_type: 'custom_script'
            execute_on: 'server'
            command: command
            run_on_hosts:
              - 0
      with_items:
        - 34
        - 40
      register: result

    - assert:
        that:
          - "item.changed"
      with_items: "{{ result.results }}"
      ignore_errors: True
      loop_control:
        label: "zabbix version {{ item.item }}"

    - name: Deploy existing action
      zabbix_action:
        server_url: "http://192.168.10.{{ item }}/zabbix/"
        login_user: Admin
        login_password: "zabbix"
        state: present
        status: enabled
        name: "auto resp: update motd"
        event_source: 'trigger'
        conditions:
          - type: 'host_group'
            operator: '='
            value: 'Linux servers'
        operations:
          - type: 'remote_command'
            command_type: 'custom_script'
            execute_on: 'server'
            command: command
            run_on_hosts:
              - 0
        recovery_operations:
          - type: 'remote_command'
            command_type: 'custom_script'
            execute_on: 'server'
            command: command
            run_on_hosts:
              - 0
      with_items:
        - 34
        - 40
      register: result

    - assert:
        that:
          - "not result.changed"
      ignore_errors: True
      loop_control:
        label: "zabbix version {{ item.item }}"

```
