### ISSUE TITLE
New module request: tower_notification

### ISSUE THREAD

**Issue by samcarpentier** [ansible/ansible#50511]
##### SUMMARY

Add a module to create Ansible Tower notification templates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

tower_notification

##### ADDITIONAL INFORMATION

The tower_notification module could be used to automate the configuration of Ansible Tower and AWX via Ansible itself. There are multiple existing modules to do so, however the notification feature in Tower is not covered at the moment.

```yaml
---
- name: Add webhook notification
  tower_notification:
    name: webhook notification
    notification_type: webhook
    url: http://www.example.com/hook
    headers:
      X-Custom-Header: value123
    state: present
    tower_config_file: "~/tower_cli.cfg"

- name: Add Slack notification
  tower_notification:
    name: slack notification
    notification_type: slack
    channels:
      - general
    token: cefda9e2be1f21d11cdd9452f5b7f97fda977f42
    state: present
    tower_config_file: "~/tower_cli.cfg"

- name: Delete notification
  tower_notification:
    name: old notification
    state: absent
    tower_config_file: "~/tower_cli.cfg"
```
