### ISSUE TITLE
cli_command does not handle errors

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#50513]
##### SUMMARY
When an error appears (bad command, missing parameters) on the command line, the cli_command does not seem to pick it up.  Example below shows when I put in a bad password (trying to setup a new user) it does not tell me the problem (the password is not hard enough)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cli_command

##### ANSIBLE VERSION

```paste below
[student2@ansible network_setup]$ ansible --version
ansible 2.8.0.dev0
  config file = /home/student2/.ansible.cfg
  configured module search path = [u'/home/student2/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
[student2@ansible network_setup]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student2/.ansible.cfg) = [u'/home/student2/networking-workshop/lab_inventory/hosts']
DEFAULT_TIMEOUT(/home/student2/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student2/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student2/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/student2/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

```yaml
[student2@ansible network_setup]$ cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

##### STEPS TO REPRODUCE

use a playbook like this and set the network_configured_password to ansible (just simple word ansible)

```
- name: CHANGE PASSWORD FOR JUNIPER DEVICE
  vars:
    ansible_connection: network_cli
  cli_command:
    command: "{{item}}"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "{{network_configured_password}}"
      - "{{network_configured_password}}"
    check_all: True
  loop:
    - "configure"
    - "rollback"
    - "set system login user {{network_name}} authentication plain-text-password"
    - "set system login user {{network_name}} class {{network_juniper_class}}"
    - "commit"
  when: network_configured_password is defined and network_configured_password
```

##### EXPECTED RESULTS

tell me the error like it does on the cli

```
jnpr@ansible# set system login user ansible authentication plain-text-password
New password:
error: minimum password length is 6
error: require change of case, digits or punctuation
````

##### ACTUAL RESULTS

```paste below
Identity added: /tmp/awx_240_v3Kvrk/credential_2 (/tmp/awx_240_v3Kvrk/credential_2)

PLAY [CONFIGURE USER ON NETWORK DEVICES] ***************************************


TASK [LOAD PLATFORM ROLE junos] ************************************************



skipping: [ansible]






TASK [junos : LOAD USERNAME AND KEY PROPERTIES ONTO DEVICE] ********************


skipping: [rtr3]

skipping: [rtr4]

TASK [junos : debug this] ******************************************************
ok: [rtr4] => {
    "msg": "netconf"
}


ok: [rtr3] => {
    "msg": "netconf"
}

TASK [junos : CHANGE PASSWORD FOR JUNIPER DEVICE] ******************************
ok: [rtr3] => (item=configure)


ok: [rtr4] => (item=configure)
ok: [rtr4] => (item=rollback)
failed: [rtr4] (item=set system login user ansible authentication plain-text-password) => {"changed": false, "item": "set system login user ansible authentication plain-text-password", "msg": "timeout value 60 seconds reached while trying to send command: set system login user ansible authentication plain-text-password"}
failed: [rtr4] (item=set system login user ansible class super-user) => {"changed": false, "item": "set system login user ansible class super-user", "msg": "timeout value 60 seconds reached while trying to send command: set system login user ansible class super-user"}
ok: [rtr3] => (item=rollback)
failed: [rtr3] (item=set system login user ansible authentication plain-text-password) => {"changed": false, "item": "set system login user ansible authentication plain-text-password", "msg": "timeout value 60 seconds reached while trying to send command: set system login user ansible authentication plain-text-password"}
failed: [rtr3] (item=set system login user ansible class super-user) => {"changed": false, "item": "set system login user ansible class super-user", "msg": "timeout value 60 seconds reached while trying to send command: set system login user ansible class super-user"}
ok: [rtr4] => (item=commit)
ok: [rtr3] => (item=commit)


TASK [ios : LOAD SYSTEM PROPERTIES ONTO DEVICE] ********************************

changed: [rtr2]


changed: [rtr1]

PLAY RECAP *********************************************************************
ansible                    : ok=0    changed=0    unreachable=0    failed=0    skipped=1   
rtr1                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0   
rtr2                       : ok=1    changed=1    unreachable=0    failed=0    skipped=0   
rtr3                       : ok=1    changed=0    unreachable=0    failed=1    skipped=1   
rtr4                       : ok=1    changed=0    unreachable=0    failed=1    skipped=1   
```
