### ISSUE TITLE
match abillities between junos_command and cli_command

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#50510]
##### SUMMARY
the cli_command and junos_command don't have matching abilities and parameters

on cli_command we can do this->

```
- name: CHANGE PASSWORD FOR JUNIPER DEVICE
  vars:
    ansible_connection: network_cli
  cli_command:
    command: "{{item}}"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "{{network_configured_password}}"
      - "{{network_configured_password}}"
    check_all: True
  loop:
    - "configure"
    - "rollback"
    - "set system login user {{network_name}} authentication plain-text-password"
    - "commit"
  when: network_configured_password is defined and network_configured_password
```

there is multiple problems with junos_command
- no prompts
- no prompt answer parameter
- no explanation or example of match (is this similar to prompt?)
- why is there retries?  this is covered with until loop for ansible
- why is there intervals?  this is covered with the until loop for ansible
- why does this use commands vs cli_command uses command parameter?

there is multiple problems with cli_command
- no support for netconf, (netconf works with junos_command)
- no support for display? is this easy to add here?
- why does this command vs commands
- can we send a list of commands with cli_command like junos_command?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /home/student2/.ansible.cfg
  configured module search path = [u'/home/student2/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```paste below
ansible 2.8.0.dev0
  config file = /home/student2/.ansible.cfg
  configured module search path = [u'/home/student2/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[student2@ansible network_setup]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student2/.ansible.cfg) = [u'/home/student2/networking-workshop/lab_inventory/hosts']
DEFAULT_TIMEOUT(/home/student2/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student2/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student2/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/student2/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE
N/A but here is one examples

if i have hostvars set to netconf i have to do a switch like this->
```
  vars:
    ansible_connection: network_cli
```

```yaml
- name: CHANGE PASSWORD FOR JUNIPER DEVICE
  vars:
    ansible_connection: network_cli
  cli_command:
    command: "{{item}}"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "{{network_configured_password}}"
      - "{{network_configured_password}}"
    check_all: True
  loop:
    - "configure"
    - "rollback"
    - "set system login user {{network_name}} authentication plain-text-password"
    - "commit"
  when: network_configured_password is defined and network_configured_password
```

##### EXPECTED RESULTS
junos_command can be converted to cli_command with minimal changes

##### ACTUAL RESULTS
the commands don't work similarly at all, its a fork lift change and you create confusion for users b/c there is lots of differences and caveats
