### ISSUE TITLE
macOS 14.1 and 14.2 password change hangs

### ISSUE THREAD

**Issue by esajche** [ansible/ansible#50524]
##### SUMMARY
Using simple playbook to change a users password. 
This was working fine in macOS 10.14.0 but looks like something changed in macOS 10.14.1 and macOS 10.14.2.
The play just hangs. 

Upon further investigation, I found that macOS 14.1 and 14.2 now require the OLD password for any user to be entered before the new password can be changed.  Ansible tries to change the password via sudo but macOS 14.1 and 14.2 now requires the OLD password to be entered in even if it is a sudo user who is changing the password.  From what I could tell, ansible does not proceed because the macOS shows a prompt saying "Please enter OLD password".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
user module

##### ANSIBLE VERSION

```paste below

ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/sajche/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Apple OSX 10.14.1, OSX 10.14.2

##### STEPS TO REPRODUCE

```
---
- hosts: group1
  remote_user: administrator
  gather_facts: no
  tasks:
  - name: Changing "test" account password
    remote_user: administrator
    become: yes
    become_method: sudo
    user:
      name: test
      password: testpass
      update_password: always
...

```

##### ACTUAL RESULTS

The play hangs on the manager and on the OSX 10.14.1 client you see the following error in the logs
"ODRecordChangePassword failed"

```
If I run the the play in verbose mode I can see this command before the play hangs:
<IP address of lient> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=<somekey>] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-<somekey>; /usr/bin/python /Users/administrator/.ansible/tmp/ansible-tmp-1546556220.85-230785305326584/AnsiballZ_user.py'"'"' && sleep 0' 

```

If I copy the entire command and paste it into the OSX 10.14.1 client's terminal i get a prompt that says "permission denied: please enter OLD password"
