### ISSUE TITLE
Reboot VM failed

### ISSUE THREAD

**Issue by ewtang** [ansible/ansible#50530]
##### SUMMARY

Reboot failed with message:
    onosvm: fatal: [onosvm]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Running reboot with local connection would reboot the control node.", "rebooted": false}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible/plugins/action/reboot.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu xenial

##### STEPS TO REPRODUCE

Using a Vagrantfile to boot a Ubuntu xenial VM and to run below provision script:
  d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/machine-restart.yml -c local"

```yaml
---
# machine-restart.yml
# Restarts the target machine
#
- name: Restarting the machine
  hosts: all
  tasks:
    - name: Reboot
      reboot:
        reboot_timeout: 600
        connect_timeout: 60
        post_reboot_delay: 600
```

##### EXPECTED RESULTS

The VM or control node should be allowed to reboot.

##### ACTUAL RESULTS

Reboot failed with below message.

```paste below
    onosvm: fatal: [onosvm]: FAILED! => {"changed": false, "elapsed": 0, "msg": "Running reboot with local connection would reboot the control node.", "rebooted": false}
```
