### ISSUE TITLE
net_system domain-search vs correct domain_search (also show example with non-list)

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#50549]
##### SUMMARY
the parameter in the example is wrong, and we incorrectly state it "has" to be a list, it can be a single entry

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
net_system
https://docs.ansible.com/ansible/latest/modules/net_system_module.html

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### ADDITIONAL INFORMATION
The example

```
- name: configure hostname and domain name
  net_system:
    hostname: ios01
    domain_name: test.example.com
    domain-search:
      - ansible.com
      - redhat.com
      - cisco.com
```

is wrong, it should be 
```
- name: configure hostname and domain name
  net_system:
    hostname: ios01
    domain_name: test.example.com
    domain_search:
      - ansible.com
      - redhat.com
      - cisco.com
```

we should also show an example that is not a list like

```
- name: configure hostname and domain name
  net_system:
    hostname: leaf02
    domain_name: test.example.com
    domain-search: ansible.com
```

this is one I ran and for sure works->
```
---
- name: change pass
  hosts: rtr1
  gather_facts: no
  tasks:
    - name: domain_search
      net_system:
        domain_search: ansible.com
```
