### ISSUE TITLE
Allow defaulting nested undefined variables with undefined parental dicts

### ISSUE THREAD

**Issue by Drugoy** [ansible/ansible#50554]
##### SUMMARY

Allow defaulting nested undefined variables with undefined parental dicts:
Currently, if you have a variable dict defined and it's child dict not defined - you may rely on <a href="https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#defaulting-undefined-variables">defaulting undefined variables</a>:
```yaml
# this will work
- hosts: localhost
  vars:
    parent:
  tasks:
    - debug:
      msg: "{{ parent.child | default('some value') }}"
```
but you can't rely on defaulting of undefined variables if their parental dict is also not define:
```yaml
# this will result into a fatal error because variable 'parent' is undefined
- hosts: localhost
  tasks:
    - debug:
      msg: "{{ parent.child | default('some value') }}"
```
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

playbooks_filters

##### ADDITIONAL INFORMATION

Users could rely on defaulting undefined variables in complex tree structures where there might be undefined branches of any size.
