### ISSUE TITLE
meta: clear_facts does not invalidate cacheable set_fact variables

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#50556]
##### SUMMARY
`meta: clear_cache` is not invalidating the ability to lookup a "fact" set by set_fact + cacheable=True

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
meta clear_facts

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE

```yaml
- hosts: el6host
  connection: local
  gather_facts: False
  tasks:
    - set_fact:
        foo: "bar"
    - set_fact:
        foo_cacheable: "bar"
        cacheable: True

    - name: clearing facts
      meta: clear_facts

    - debug:
        msg: "{{ 'foo = ' + hostvars['el6host'].get('foo') }}"
    - debug:
        msg: "{{ 'foo_cacheable = ' + hostvars['el6host'].get('foo_cacheable') }}"

```

##### EXPECTED RESULTS
The final debug should show something like "UNDEFINED"

##### ACTUAL RESULTS

```paste below
PLAY [el6host] *****************************************************************************************************************************
META: ran handlers

TASK [set_fact] ****************************************************************************************************************************
task path: /home/jtanner/workspace/issues/AP-45315/site.yml:5
ok: [el6host] => {
    "ansible_facts": {
        "foo": "bar"
    }, 
    "changed": false
}

TASK [set_fact] ****************************************************************************************************************************
task path: /home/jtanner/workspace/issues/AP-45315/site.yml:7
ok: [el6host] => {
    "ansible_facts": {
        "foo_cacheable": "bar"
    }, 
    "changed": false
}
META: facts cleared

TASK [debug] *******************************************************************************************************************************
task path: /home/jtanner/workspace/issues/AP-45315/site.yml:18
ok: [el6host] => {
    "msg": "foo = bar"
}

TASK [debug] *******************************************************************************************************************************
task path: /home/jtanner/workspace/issues/AP-45315/site.yml:20
ok: [el6host] => {
    "msg": "foo_cacheable = bar"
}
```
