### ISSUE TITLE
vmware_guest generate new SID for windows OS

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#50574]
##### SUMMARY
For module vmware_guest in customization  parameters I would like to set the possibility to generate a new SID for windows OS.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_guest

##### ADDITIONAL INFORMATION
When deploy from template a vm with windows OS, is usefull generate a new SID for new VM.

```
- name: New VM
  vmware_guest:
    validate_certs: no
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    cluster: "{{ vccluster }}"
    name: test
      customization :
      - newsid: True
```
