### ISSUE TITLE
Ansible misrender files from multiline variable if it's json formated with literal \n inside.

### ISSUE THREAD

**Issue by fff7d1bc** [ansible/ansible#50580]
##### SUMMARY
Ansible tend to misrender files if the content was limited to single Jinja2 variable as in `"{{ foo }}"`if the `foo` is a multiline JSON and contain literal `\n` string inside of values. This happen also if the multiline string is encrypted with `encrypt_string` of `ansible-vault`. This issue does not seems to be occur if the multiline string is not a JSON formated.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Linux, ansible installed via pip

##### STEPS TO REPRODUCE

Just run below code and then check the 4 created files. Save as `test.yml`, add exec bit and run `./test.yml`.

```yaml
#!/usr/bin/env ansible-playbook

- name: test
  gather_facts: false
  connection: local
  hosts: localhost
  vars:
    var_test1: |
      {
        "bar": "one\ntwo\nthree\n"
      }
    var_test2: |
      {
        "foo": "one\ntwo\nthree\n",
        "bar": "test"
      }
    var_test3: |
        foo
        bar\nbaz\nfoobar\n
        foo

  tasks:
    - copy:
        dest: /tmp/var_test1_1
        content: "{{ var_test1 }}"
    - copy:
        dest: /tmp/var_test1_2
        content: " {{ var_test1 }}"
    - copy:
        dest: /tmp/var_test2_1
        content: "{{ var_test2 }}"
    - copy:
        dest: /tmp/var_test2_2
        content: " {{ var_test2 }}"
    - copy:
        dest: /tmp/var_test3_1
        content: "{{ var_test3 }}"
    - copy:
        dest: /tmp/var_test3_2
        content: " {{ var_test3 }}"

```

##### EXPECTED RESULTS

Currently ansible renders those JSON strings without a single real new line character, striping real new line chars, there's not a single `$` in generated files, unless there's at least single char in the content defintion, like `content: " {{ foo }}"`.

##### ACTUAL RESULTS

```paste below
% grep . /tmp/var_test*
/tmp/var_test1_1:{"bar": "one\ntwo\nthree\n"}
/tmp/var_test1_2: {
/tmp/var_test1_2:  "bar": "one\ntwo\nthree\n"
/tmp/var_test1_2:}
/tmp/var_test2_1:{"foo": "one\ntwo\nthree\n", "bar": "test"}
/tmp/var_test2_2: {
/tmp/var_test2_2:  "foo": "one\ntwo\nthree\n",
/tmp/var_test2_2:  "bar": "test"
/tmp/var_test2_2:}
/tmp/var_test3_1:foo
/tmp/var_test3_1:bar\nbaz\nfoobar\n
/tmp/var_test3_1:foo
/tmp/var_test3_2: foo
/tmp/var_test3_2:bar\nbaz\nfoobar\n
/tmp/var_test3_2:foo

```
