### ISSUE TITLE
vmware_guest fails provisioning with folder permission issue on NSX-T in VMC.

### ISSUE THREAD

**Issue by edcrosbys** [ansible/ansible#50605]
##### SUMMARY
Attempting to clone template results in:
```
    "msg": "Failed to clone virtual machine ******** to folder 'vim.Folder:group-v275' due to permission issue: Permission to perform this operation was denied."
```
   I have verified (the misspelled) folder name through govc find and vmware_guest_find. Cloudadmin user has permissions to provision to this folder from within vcenter and powershell. I have tried provisioning from content library and outside of content library with same results. I have tried specifying the cluster and/or esxi box as well with similar issues.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
No output
```

##### OS / ENVIRONMENT
vSphere Client version 6.8.2.350
NSX-T 2.2
VMC
##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
  - vm_name: test.deploy.ansible
  
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: vcenter.resolvable_url.vmwarevmc.com
      username: 'cloudadmin@vmc.local'
      password: 'redacted'
      validate_certs: no
      name: '{{ vm_name }}'
      state: poweredon
      template: RHEL7.5-Server_10-30-18
      datacenter: SDDC-Datacenter
 #    cluster: 'Cluster-1'
 #     esxi_hostname: '192.168.2.68'    
      folder: "/SDDC-Datacenter/vm/Workloads/Management Enviroment/CFME"
      hardware:
 #       memory_mb: '{{ ram }}'
 #       num_cpus: '{{ cpu }}'
        scsi: lsilogic
      customization:
        dns_servers:
        - 192.168.0.11
        - 192.168.0.12
        domain: domain.com
        hostname: '{{ vm_name }}'
      networks:
      - name: 'Simulated Management Segment'
        ip: '192.168.0.101'
        netmask: '255.255.255.0'
        gateway: '192.168.0.1'
        type: static
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
```

##### ACTUAL RESULTS

```
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_guest_payload_oTuFSg/__main__.py", line 2067, in deploy_vm
    task = vm_obj.Clone(folder=destfolder, name=self.params['name'], spec=clonespec)
  File "/usr/lib64/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib64/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib64/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ], 
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "customization_spec": null, 
            "customvalues": [], 
            "datacenter": "SDDC-Datacenter", 
            "datastore": null, 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": "/SDDC-Datacenter/vm/Workloads/Management Enviroment/CFME", 
            "force": false, 
            "guest_id": null, 
            "hardware": {
                "scsi": "lsilogic"
            }, 
            "hostname": "vcenter.resolvable_url.com", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "name_match": "first", 
            "networks": [
                {
                    "gateway": "192.168.0.1", 
                    "ip": "192.168.0.101", 
                    "name": "Simulated Management Segment", 
                    "netmask": "255.255.255.0", 
                    "type": "static"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredon", 
            "state_change_timeout": 0, 
            "template": "RHEL7.5-Server_10-30-18", 
            "username": "cloudadmin@vmc.local", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_ip_address": true
        }
    }, 
    "msg": "Failed to clone virtual machine ******** to folder 'vim.Folder:group-v275' due to permission issue: Permission to perform this operation was denied."

```
