### ISSUE TITLE
vmware_guest - vapp_properties not set.

### ISSUE THREAD

**Issue by stobias123** [ansible/ansible#50617]
##### SUMMARY
When using `vmware_guest` module to deploy an OVA template, you cannot use `state: poweredon` and have your `vapp_properties` set. 

Per the docs...

> If state is set to one of the following poweredon, poweredoff, present, restarted, suspended and virtual machine does not exists, then virtual machine is deployed with given parameters.

This is not the cast, vapp parameters are _only_ set when state is set to present.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`vmware_guest`

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /home/me/repos/Ansible/playbooks/app/ansible.cfg
  configured module search path = ['/home/me/repos/Ansible/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

```

##### CONFIGURATION
```
DEFAULT_GATHER_TIMEOUT(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = 300
DEFAULT_LOOKUP_PLUGIN_PATH(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = ['/home/me/repos/Ansible/playbooks/app/plugins']
DEFAULT_MODULE_PATH(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = ['/home/me/repos/Ansible/library']
DEFAULT_ROLES_PATH(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = ['/home/me/repos/Ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = 300
DEFAULT_VAULT_PASSWORD_FILE(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = /home/me/.vault_pass
HOST_KEY_CHECKING(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = False
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/home/me/repos/Ansible/playbooks/app/ansible.cfg) = 300

```

##### OS / ENVIRONMENT
F5 vapp

##### STEPS TO REPRODUCE
Run a playbook as defined below. 
```yaml
- name: Deploy a mini F5.
  vmware_guest:
    hostname: "{{ vcenter_ip }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{vm_datacenter}}"
    folder: "{{ f5_vm_folder }}"
    cluster: "{{ vm_cluster }}"
    name: "{{ f5_server }}"
    state: poweredon
    template: "BIG-IP VE 13.1.1.3.0.0.1"
    vapp_properties:
      - id: "net.mgmt.addr"
        value: "{{ f5_mgmt_ip }}/21"
        label: mgmt-addr
      - id: "net.mgmt.gw"
        value: "{{ f5_mgmt_gateway }}"
        label: mgmt-gw
      - id: "user.root.pwd"
        value: "testing"
        label: root-pwd
      - id: "user.admin.pwd"
        value: "testing"
        label: admin-pwd
```

##### EXPECTED RESULTS

```paste below
$ govc vm.info -json /path/to/vm/myvm123 | jq '.VirtualMachines[0].Config.VAppConfig'
  "Property": [
      {
        "Key": 0,
        "ClassId": "",
        "InstanceId": "",
        "Id": "net.mgmt.addr",
        "Category": "Network properties",
        "Label": "mgmt-addr",
        "Type": "string",
        "TypeReference": "",
        "UserConfigurable": true,
        "DefaultValue": "",
        "Value": "10.10.88.222/21",
        "Description": "F5 BIG-IP VE's management address in the format of \"IP/prefix\""
      },
      {
        "Key": 1,
        "ClassId": "",
        "InstanceId": "",
        "Id": "net.mgmt.gw",
        "Category": "Network properties",
        "Label": "mgmt-gw",
        "Type": "string",
        "TypeReference": "",
        "UserConfigurable": true,
        "DefaultValue": "",
        "Value": "10.10.88.1",
        "Description": "F5 BIG-IP VE's management default gateway"
      },
....
```

##### ACTUAL RESULTS
Template is deployed, vapp settings are not configured.
```paste below
$ govc vm.info -json /path/to/vm/myvm123 | jq '.VirtualMachines[0].Config.VAppConfig'
  {
      "Key": 1,
      "ClassId": "",
      "InstanceId": "",
      "Id": "net.mgmt.gw",
      "Category": "Network properties",
      "Label": "mgmt-gw",
      "Type": "string",
      "TypeReference": "",
      "UserConfigurable": true,
      "DefaultValue": "",
      "Value": "",
      "Description": "F5 BIG-IP VE's management default gateway"
    },
    {
      "Key": 2,
      "ClassId": "",
      "InstanceId": "",
      "Id": "user.root.pwd",
      "Category": "User properties",
      "Label": "root-pwd",
      "Type": "string",
      "TypeReference": "",
      "UserConfigurable": true,
      "DefaultValue": "",
      "Value": "",
      "Description": "F5 BIG-IP VE's SHA-512 shadow or plain-text password for \"root\" user"
    },
....
```
