### ISSUE TITLE
zip files created by archive-module are flagged by unzip

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#50624]
##### SUMMARY
When using `unzip -t` on a ZIP-archive created by the archive-module, every archived directory is flagged.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
archive

##### ANSIBLE VERSION
2.7.5

##### OS / ENVIRONMENT
Remote is Linux (RedHat-6.x)

##### STEPS TO REPRODUCE
Create a ZIP-archive of a directory tree with archive-module.

```yaml
  - name: Archive batches (if any)
    archive:
      format: zip
      dest: "/tmp/var-tmp.zip"
      mode: 0444
      path: /var/tmp
```
Then attempt to check the result: `unzip -t /tmp/var-tmp.zip`.

##### EXPECTED RESULTS
Clean output from unzip -- with every entry labeled "OK".

##### ACTUAL RESULTS
Although the archived _files_ are all OK, the archived _directories_ are flagged as containing an error: `error:  invalid compressed data to inflate`.

```
    testing: 20181024/batch110000005/.../portfolio1.txt   OK
    testing: 20181024/batch110000005/.../  
  error:  invalid compressed data to inflate
```
The files can still all be extracted, so it probably is not a very big deal...
