### ISSUE TITLE
nxos_install_os ignoring PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT passed as extra_vars

### ISSUE THREAD

**Issue by BDworak** [ansible/ansible#50626]
##### SUMMARY

When using the nxos_install_os module, the persistent command/connect timeout variables are only being read from ansible.cfg. If these variables are passed from extra_vars or set in playbook they are ignored. 

It is important to note we are running this via Ansible Tower.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

[lib/ansible/plugins/action/nxos.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/nxos.py#L58)
      
##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bartdwo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
<no-output> 
```

##### OS / ENVIRONMENT

Redhat Linux
NX-OS 6.0(2)U5(2)

##### STEPS TO REPRODUCE

set the following variables as extra vars before play:
ANSIBLE_PERSISTENT_COMMAND_TIMEOUT: 700
ANSIBLE_PERSISTENT_CONNECT_TIMEOUT: 700
PERSISTENT_COMMAND_TIMEOUT: 700
PERSISTENT_CONNECT_TIMEOUT: 700
connect_timeout: 700
command_timeout: 700

ansible-playbook -i inventory/dev_hosts -l cisco-nxos -e "{"ANSIBLE_PERSISTENT_COMMAND_TIMEOUT": 700, "ANSIBLE_PERSISTENT_CONNECT_TIMEOUT": 700, "PERSISTENT_COMMAND_TIMEOUT": 700, "PERSISTENT_CONNECT_TIMEOUT": 700,}" nxos_upgrade.yml

```yaml
---
  - name: Code Upgrade for Nexus 3k
    hosts: cisco-nxos
    connection: network_cli
    gather_facts: no 
    tasks:
       - name: setting persistent connection timeout and command time out
         set_fact:
           command_timeout: 600
           connect_timeout: 600

       - name: Upgrade OS on 3k
         nxos_install_os:
           kickstart_image_file: "{{ images_kickstart }}"
           system_image_file: "{{ images_system }}"
           issu: desired
```

##### EXPECTED RESULTS

Module uses extra_vars passed command/connect timeout values or allows the values to be set during the play.

##### ACTUAL RESULTS

```paste below
{
    "msg": "PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT must be set to 600 seconds or higher when using nxos_install_os module",
    "changed": false,
    "_ansible_no_log": false
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by BDworak** [comment]
!component +lib/ansible/plugins/action/nxos.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/action/nxos.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/nxos.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @ganeshrn @gdpak @justjais @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/50965

**Comment by trishnaguha** [comment]
@BDworak The PR https://github.com/ansible/ansible/pull/50965 fixes the issue. 

There is no need to use set_fact to set ansible specific variables.

If you want to pass it in playbook, the method is as follows:
```
  - name: Code Upgrade for Nexus 3k
    hosts: cisco-nxos
    connection: network_cli
    gather_facts: no 
    tasks:
       - name: Upgrade OS on 3k
         nxos_install_os:
           kickstart_image_file: "{{ images_kickstart }}"
           system_image_file: "{{ images_system }}"
           issu: desired
         vars:
           ansible_command_timeout: 700
           ansible_connect_timeout: 700
```  
Or if you want to pass it with extra vars, the method is:
```
ansible-playbook nxos.yaml -e "ansible_command_timeout=700 ansible_connect_timeout=700"
```

`ANSIBLE_PERSISTENT_CONNECT_TIMEOUT` or `ANSIBLE_PERSISTEN_COMMAND_TIMEOUT` are used if you want to set the variables as environment variable.

This can also be done in ansible.cfg
```
[persistent_connection]
connect_timeout=700
command_timeout=700
```

Here is network_cli connection plugin doc https://docs.ansible.com/ansible/latest/plugins/connection/network_cli.html

Please let us know if the issue persists.

**Comment by demakkar** [comment]
< TASK [Upgrade OS on 3k] >
 -------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /nxos_upgrade.yml:206
fatal: FAILED! => {
    "changed": false,
    "msg": "PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT must be set to 600 seconds or higher when using nxos_install_os module"
}

**Comment by BDworak** [comment]
Hi @trishnaguha, we applied the patch from #50965 to our local ansible installation and at first it did not take the variables. I added debug commands to nxos.py

```
msg = 'PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT'
msg += ' must be set to 600 seconds or higher when using nxos_install_os module'
msg += ' currently set to persistent_command_timeout:' + str(connection.get_option('persistent_command_timeout'))
msg += ' currently set to persistent_connect_timeout:' + str(connection.get_option('persistent_connect_timeout'))
````
We also modified the playbook and added vars: to the nxos_install_os task.

```
    tasks:
       - name: Upgrade OS on 3k
         nxos_install_os:
           kickstart_image_file: "{{ images_kickstart }}"
           system_image_file: "{{ images_system }}"
           issu: desired
         vars:
           ansible_command_timeout: 700
           ansible_connect_timeout: 700
```
Running the first time we got the following output:
```
fatal: [XXXXXXX]: FAILED! => {"changed": false, "msg": "PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT must be set to 600 seconds or higher when using nxos_install_os module currently set to persistent_command_timeout:700 currently set to persistent_connect_timeout:90"}
```
We had the connect_timeout set in ansible.cfg to 90 and it seemed that Ansible was preferring the variable set in ansible.cfg. After we removed the connect_timeout in ansible.cfg we re-ran and found the value set to the default of 30. It seems that the ansible_connect_timeout variable is not being read in. 
```
fatal: [XXXX]: FAILED! => {"changed": false, "msg": "PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT must be set to 600 seconds or higher when using nxos_install_os module currently set to persistent_command_timeout:700 currently set to persistent_connect_timeout:30"}
```

**Comment by BDworak** [comment]
One more test, we set the variables in ansible.cfg and it seems to take the ansible.cfg, it just does not like **ansible_connect_timeout** variable set in playbook/via extra vars at all. 
```
fatal: [XXXXXXX]: FAILED! => {"changed": false, "msg": "PERSISTENT_COMMAND_TIMEOUT and PERSISTENT_CONNECT_TIMEOUT must be set to 600 seconds or higher when using nxos_install_os module currently set to persistent_command_timeout:700 currently set to persistent_connect_timeout:400"}
```

**Comment by abenokraitis** [comment]
Requesting this issue be backported to the next 2.7.x release.

**Comment by trishnaguha** [comment]
@BDworak I am curious if the applied patch is activated on your environment or not. Note this fix is not released yet, It will be released with next 2.7.x release. 

Can you please follow the following steps?
```
$ git clone -b ansible_connect_timeout_debug https://github.com/trishnaguha/ansible.git
$ cd ansible
$ source hacking/env-setup
$ which ansible
```
The output of the last command should point to `<present-working-directory-path>/bin/ansible`

`ansible --version` command should return `ansible 2.8.0.dev0`
Please note that devel version is for **development/testing purpose only**.

Now run this play in the same environment:
`ansible-playbook <playbook-name> -vv`
```
  tasks:
  - name: show version
    nxos_command:
      commands:
        - 'show version'
    vars:
      ansible_network_os: nxos
      ansible_command_timeout: 800
      ansible_connect_timeout: 800
```
Verbose mode will show that you are using `2.8.0.dev0`

You will see the timeout values as warning on terminal when you run the playbook. 
Something like `[WARNING]: command_timeout is 800 and connect_timeout is 800`
It should take timeout value from variables as variables have higher precedence over ansible.cfg.
Please let us know what warning do you see with the repo cloned and activated on your environment.
