### ISSUE TITLE
nxos_config fails (but returns success) due to returned warnings

### ISSUE THREAD

**Issue by michaelford85** [ansible/ansible#50635]
##### SUMMARY

When running a task utilizing the nxos_config module, there are no errors thrown by ansible and it appears as if everything ran fine, however some commands do not execute. We believe it has to do with the fact that when the command is entered on the switch, a warning is displayed, this may be throwing off the Ansible interface. The warnings in question when configuring the switch manually:

nxos_switch(config-if)# spanning-tree port type edge trunk
Warning: Edge port type (portfast) should only be enabled on ports connected to a single
host. Connecting hubs, concentrators, switches, bridges, etc... to this
interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
Use with CAUTION

nxos_switch(config-if)# no lacp suspend-individual
Warning: !! Disable lacp suspend-individual only on port-channel with edge ports. Disabling this on network port port-channel could lead to loops.!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_config module

##### ANSIBLE VERSION

```
2.7.5
```

##### CONFIGURATION

```
Nothing (default ansible.cfg)
```

##### OS / ENVIRONMENT

NX-OS 7.3(1)N1(1) 

##### STEPS TO REPRODUCE

```
- name: CONFIGURE ETHERNET AND PO INTERFACES ON "A" SWITCH
  hosts: "{{ switch_name }}"
  connection: local
  gather_facts: no

  vars:
    nxos_provider:
      username: "ansible"
      password: "Ansible123"
      transport: nxapi
      host: "{{ inventory_hostname }}"

  tasks:

    - name: CONFIGURING ETHERNET INTERFACES
      nxos_interface:
        name: "{{ eth_interface_num }}"
        admin_state: up
        description: "{{ eth_interface_desc }}"
        provider: "{{ nxos_provider }}"

    - name: AGGREGATING ETHERNET INTERFACES
      nxos_linkagg:
        group: "{{ cpv_num }}"
        state: present
        mode: active
        force: true
        members:
          - "{{ eth_interface_num }}"
        provider: "{{ nxos_provider }}"

    - name: SETTING PORT TRUNK EDGE
      nxos_config:
        lines:
          - spanning-tree port type edge trunk
        parents: interface "{{ eth_interface_num }}"
        replace: block
        match: none
        provider: "{{ nxos_provider }}"

    - name: CONFIGURING PO INTERFACE PARAMETERS
      nxos_interface:
        name: po"{{ cpv_num }}"
        admin_state: down
        description: "{{ po_interface_desc }}"
        provider: "{{ nxos_provider }}"

    - name: CONFIGURING PO L2 PARAMETERS
      nxos_l2_interface:
        name: "{{ po_interface_num }}"
        mode: trunk
        native_vlan: 999
        trunk_allowed_vlans: "{{ po_allowed_vlans }}"
        provider: "{{ nxos_provider }}"

    - name: CONFIGURING PO LOGGING, LACP SUSPEND, AND PRIVATE VLAN PARAMETERS
      nxos_config:
        lines:
          - spanning-tree port type edge trunk
          - no lacp suspend-individual
          - no logging event port link-status
          - switchport mode private-vlan trunk secondary
          - switchport private-vlan trunk native vlan 999
          - switchport private-vlan trunk allowed vlan 1800-1801,1600-1601,1610-1611
          - switchport private-vlan association trunk 1800 1801
          - switchport private-vlan association trunk 1600 1601
          - switchport private-vlan association trunk 1610 1611
        parents: "{{ po_interface }}"
        replace: block
        provider: "{{ nxos_provider }}"

    - name: CONFIGURING PO VPC PARAMETERS
      nxos_vpc_interface:
        portchannel: "{{ cpv_num }}"
        vpc: "{{ cpv_num }}"
        provider: "{{ nxos_provider }}"

    - name: ADMIN UP PO INTERFACE
      nxos_interface:
        name: po"{{ cpv_num }}"
        admin_state: up
        provider: "{{ nxos_provider }}"

```

##### EXPECTED RESULTS

Expected resulting switch configuration:

interface port-channel273
  description CHUL9AP321 PORT-CHANNEL
  switchport mode private-vlan trunk secondary
  no lacp suspend-individual
  switchport trunk native vlan 999\
  switchport trunk allowed vlan 149
  spanning-tree port type edge trunk
  no logging event port link-status
  switchport private-vlan trunk native vlan 999
  switchport private-vlan trunk allowed vlan 1600-1601,1610-1611,1800-1801
  switchport private-vlan association trunk 1800 1801
  switchport private-vlan association trunk 1600 1601
  switchport private-vlan association trunk 1610 1611
  vpc 273

##### ACTUAL RESULTS

Actual resulting switch configuration:

interface port-channel273
  description CHUL9AP321 PORT-CHANNEL
  switchport mode trunk
  switchport trunk native vlan 999
  switchport trunk allowed vlan 149
  vpc 273

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha @tstoner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@michaelford85, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by michaelford85** [comment]
Awaiting details on nxos version, ansible version, etc. from the operator. Will update when I receive it.

**Comment by abenokraitis** [comment]
cc @abenokraitis @IPvSean

**Comment by abenokraitis** [comment]
cc @mikewiebe FYI

**Comment by michaelford85** [comment]
Added the following to the bug report:

- Ansible version 
- NX-OS version
- ansible.cfg output

**Comment by trishnaguha** [comment]
@michaelford85 I have tried this on NX-OS 9K (7.0(3)I7(3)), 7K (7.3(0)D1(1)), 3K(6.0(2)U6(10)) devices. Even though the command is returning the same warning on all these nexus devices, the config is getting applied on the running-config.
I am pretty sure that is there some other reason that config is not applied on your device. It is **NOT** the **WARNING**. 

Can you please follow the exact same steps of your playbook manually on the device and let us know the running-config?

Here is the playbook I used:
```
  tasks:
  - name: configure
    nxos_config:
      lines:
        - spanning-tree port type edge trunk
      parents: interface Ethernet1/3

  - name: display running-config
    nxos_command:
      commands: show running-config | section interface.Ethernet1/3
```

output: 
```
TASK [display running-config]
"stdout": [
        "interface Ethernet1/3\n  switchport mode trunk\n  spanning-tree port type edge trunk"
  ],
"stdout_lines": [
        [
            "interface Ethernet1/3", 
            "  switchport mode trunk", 
            "  spanning-tree port type edge trunk"
  ]
```

When run manually on the device it returns the similar warning:
```
test(config)# interface Ethernet1/3
test(config-if)# spanning-tree port type edge trunk
Warning: Edge port type (portfast) should only be enabled on ports connected to a single
 host. Connecting hubs, concentrators, switches, bridges, etc... to this
 interface  when edge port type (portfast) is enabled, can cause temporary bridging loops.
 Use with CAUTION

test# show running-config | section interface.Ethernet1/3
interface Ethernet1/3
  switchport mode trunk
  spanning-tree port type edge trunk
```

**Comment by mikewiebe** [comment]
@michaelford85 I booted image version `7.3(1)N1(1)` on my Nexus 6001 and simplified the playbook to just the interface configuration you are seeing issues with.

```yaml
- name: CONFIGURE ETHERNET AND PO INTERFACES ON "A" SWITCH
  hosts: nxos 
  connection: local
  gather_facts: no

  vars:
    nxos_provider:
      username: "admin"
      password: "password123"
      transport: cli 
      host: "{{ inventory_hostname }}"
      use_ssl: no

  tasks:

    - name: CONFIGURING PO LOGGING, LACP SUSPEND, AND PRIVATE VLAN PARAMETERS
      nxos_config:
        lines:
          - switchport
          - switchport mode trunk
          - description CHUL9AP321 PORT-CHANNEL
          - switchport mode private-vlan trunk secondary
          - no lacp suspend-individual
          - switchport trunk native vlan 999
          - switchport trunk allowed vlan 149
          - spanning-tree port type edge trunk
          - no logging event port link-status
          - switchport private-vlan trunk native vlan 999
          - switchport private-vlan trunk allowed vlan 1600-1601,1610-1611,1800-1801
          - switchport private-vlan association trunk 1800 1801
          - switchport private-vlan association trunk 1600 1601
          - switchport private-vlan association trunk 1610 1611
          - vpc 273
        parents: "interface port-channel273"
        replace: block
        provider: "{{ nxos_provider }}"
```

I was not able to get nxapi to work properly on my device (would not connect for some reason) but I was able to use cli as the transport and it applied properly.

Here is my starting state.

```
n6k(config)# show ver | inc system:
  system:    version 7.3(1)N1(1)
n6k(config)# 
n6k(config)# no interface port-channel273
port-channel273: port-channel not present
n6k(config)# 
n6k(config)# 
```

Now I run the playbook.

```
(py2-ansible) mwiebe@MWIEBE-M-D2TB:~/Projects/nxos_ansible/fix_ansible$ansible-playbook -i ~/Projects/nxos_ansible/hosts standalone_playbooks/test.yaml -vvvv
ansible-playbook 2.7.5 (detached HEAD a771ed93ab) last updated 2019/01/08 09:01:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible-playbook
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/Users/mwiebe/Projects/nxos_ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/Users/mwiebe/Projects/nxos_ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /Users/mwiebe/Projects/nxos_ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yaml *************************************************************************************************************************************************************************************************
1 plays in standalone_playbooks/test.yaml

PLAY [CONFIGURE ETHERNET AND PO INTERFACES ON "A" SWITCH] ***********************************************************************************************************************************************************
META: ran handlers

TASK [CONFIGURING PO LOGGING, LACP SUSPEND, AND PRIVATE VLAN PARAMETERS] ********************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/standalone_playbooks/test.yaml:16
<n6k> connection transport is cli
<n6k> using connection plugin network_cli (was local)
<n6k> starting connection from persistent connection plugin
<n6k> local domain socket does not exist, starting it
<n6k> control socket path is /Users/mwiebe/.ansible/pc/55d6b6927f
<n6k> <n6k> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: admin on PORT 22 TO n6k
<n6k> <inventory_hostname> ssh connection done, setting terminal
<n6k> <inventory_hostname> loaded terminal plugin for network_os nxos
<n6k> <inventory_hostname> loaded cliconf plugin for network_os nxos
<n6k> <n6k> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<n6k> <inventory_hostname> firing event: on_open_shell()
<n6k> <n6k> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<n6k> <n6k> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<n6k> <inventory_hostname> ssh connection has completed successfully
<n6k> connection to remote device started successfully
<n6k> local domain socket listeners started successfully
<n6k> 
<n6k> local domain socket path is /Users/mwiebe/.ansible/pc/55d6b6927f
<n6k> socket_path: /Users/mwiebe/.ansible/pc/55d6b6927f
<n6k> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n6k> EXEC /bin/sh -c 'echo ~mwiebe && sleep 0'
<n6k> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992 `" && echo ansible-tmp-1547223306.11-8504828875992="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992 `" ) && sleep 0'
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_config.py
<n6k> PUT /Users/mwiebe/.ansible/tmp/ansible-local-75668jrnKkv/tmpDYn0zO TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992/AnsiballZ_nxos_config.py
<n6k> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992/AnsiballZ_nxos_config.py && sleep 0'
<n6k> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992/AnsiballZ_nxos_config.py && sleep 0'
<n6k> EXEC /bin/sh -c 'rm -f -r /Users/mwiebe/.ansible/tmp/ansible-tmp-1547223306.11-8504828875992/ > /dev/null 2>&1 && sleep 0'
changed: [n6k] => {
    "changed": true, 
    "commands": [
        "interface port-channel273", 
        "switchport", 
        "switchport mode trunk", 
        "description CHUL9AP321 PORT-CHANNEL", 
        "switchport mode private-vlan trunk secondary", 
        "no lacp suspend-individual", 
        "switchport trunk native vlan 999", 
        "switchport trunk allowed vlan 149", 
        "spanning-tree port type edge trunk", 
        "no logging event port link-status", 
        "switchport private-vlan trunk native vlan 999", 
        "switchport private-vlan trunk allowed vlan 1600-1601,1610-1611,1800-1801", 
        "switchport private-vlan association trunk 1800 1801", 
        "switchport private-vlan association trunk 1600 1601", 
        "switchport private-vlan association trunk 1610 1611", 
        "vpc 273"
    ], 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": false, 
            "before": null, 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": "n6k", 
            "intended_config": null, 
            "lines": [
                "switchport", 
                "switchport mode trunk", 
                "description CHUL9AP321 PORT-CHANNEL", 
                "switchport mode private-vlan trunk secondary", 
                "no lacp suspend-individual", 
                "switchport trunk native vlan 999", 
                "switchport trunk allowed vlan 149", 
                "spanning-tree port type edge trunk", 
                "no logging event port link-status", 
                "switchport private-vlan trunk native vlan 999", 
                "switchport private-vlan trunk allowed vlan 1600-1601,1610-1611,1800-1801", 
                "switchport private-vlan association trunk 1800 1801", 
                "switchport private-vlan association trunk 1600 1601", 
                "switchport private-vlan association trunk 1610 1611", 
                "vpc 273"
            ], 
            "match": "line", 
            "parents": [
                "interface port-channel273"
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": null, 
                "authorize": null, 
                "host": "n6k", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_proxy": true, 
                "use_ssl": false, 
                "username": "admin", 
                "validate_certs": null
            }, 
            "replace": "block", 
            "replace_src": null, 
            "running_config": null, 
            "save": false, 
            "save_when": "never", 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "transport": "cli", 
            "use_proxy": true, 
            "use_ssl": false, 
            "username": "admin", 
            "validate_certs": null
        }
    }, 
    "updates": [
        "interface port-channel273", 
        "switchport", 
        "switchport mode trunk", 
        "description CHUL9AP321 PORT-CHANNEL", 
        "switchport mode private-vlan trunk secondary", 
        "no lacp suspend-individual", 
        "switchport trunk native vlan 999", 
        "switchport trunk allowed vlan 149", 
        "spanning-tree port type edge trunk", 
        "no logging event port link-status", 
        "switchport private-vlan trunk native vlan 999", 
        "switchport private-vlan trunk allowed vlan 1600-1601,1610-1611,1800-1801", 
        "switchport private-vlan association trunk 1800 1801", 
        "switchport private-vlan association trunk 1600 1601", 
        "switchport private-vlan association trunk 1610 1611", 
        "vpc 273"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************
n6k           : ok=1    changed=1    unreachable=0    failed=0   
```

State after running the playbook.

```
n6k(config)# show run interface port-channel273

!Command: show running-config interface port-channel273
!Time: Fri Jan 11 11:17:54 2019

version 7.3(1)N1(1)

interface port-channel273
  description CHUL9AP321 PORT-CHANNEL
  switchport
  switchport mode private-vlan trunk secondary
  no lacp suspend-individual
  switchport trunk native vlan 999
  switchport trunk allowed vlan 149
  spanning-tree port type edge trunk
  no logging event port link-status
  switchport private-vlan trunk native vlan 999
  switchport private-vlan trunk allowed vlan 1600-1601,1610-1611,1800-1801
  switchport private-vlan association trunk 1800 1801
  switchport private-vlan association trunk 1600 1601
  switchport private-vlan association trunk 1610 1611
  vpc 273

n6k(config)# 
```

**Comment by mikewiebe** [comment]
@michaelford85 Can you try with `transport: cli` to see if you get a different result and also would you be able to provide the verbose log output from the playbook run?

**Comment by ansibot** [comment]
@michaelford85 This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrisvanheuveln
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by connifer** [comment]
I'd like to second this issue as I'm seeing the same thing.  I ran a simple playbook which reconfigures a port on a switch.  It templates the new config to a file and then the file is applied to the switch via nxos_config.  I'm using network_cli as my connection method.

I've attached the playbook and the -vvv run result ([chg0000000.yml.txt](https://github.com/ansible/ansible/files/2907904/chg0000000.yml.txt), [chg0000000.txt](https://github.com/ansible/ansible/files/2907905/chg0000000.txt)).  I'm running against a N6004.

**Original config:**
!Command: show running-config interface Ethernet100/1/7

version 7.3(3)N1(1)

interface Ethernet100/1/7
  description UNUSED_PORT
  no lldp transmit
  no lldp receive
  no cdp enable
  switchport access vlan 2
  no shutdown

**Template file:**
[root@xxxxxxx xxxxx-xxxxx-xxxxx-0X]# cat chg0000000_eth100_1_7.cfg 

interface Ethernet100/1/7
  description xxxxxx-xxxxxx-0X
  switchport access vlan xxxx
  spanning-tree port type edge
  no shutdown

**Result after running playbook:**
!Command: show running-config interface Ethernet100/1/7

version 7.3(3)N1(1)

interface Ethernet100/1/7
  description xxxxxx-xxxxxx-0X
  switchport access vlan xxxx
  no shutdown

**If I go into the switch directly and apply the missing line it gets added to the config with a warning:**
xxxxx-xxxxx-xxxxx-0X(config-if)# spanning-tree port type edge 
Warning: Edge port type (portfast) should only be enabled on ports connected to a single
 host. Connecting hubs, concentrators, switches, bridges, etc... to this
 interface  when edge port type (portfast) is enabled, can cause temporary bridging loops.
 Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet100/1/7 but will only 
 have effect when the interface is in a non-trunking mode.
xxxxx-xxxxx-xxxxx-0X(config-if)# sh run int eth100/1/7

!Command: show running-config interface Ethernet100/1/7

version 7.3(3)N1(1)

interface Ethernet100/1/7
  description xxxxxx-xxxxxx-0X
  switchport access vlan xxxx
  spanning-tree port type edge
  no shutdown

**Comment by ikhan2010** [comment]
@mikewiebe  @trishnaguha Do you have any idea about what might be causing this?

**Comment by ansibot** [comment]
@michaelford85 You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mikewiebe** [comment]
Just updating this case.  This appears to be a problem in ansible version `2.7.x` .  I am unable to recreate the problem in the latest `devel` or candidate `2.8.0` branch.

Here is my test on the latest `devel` branch.

```
Hardware
  cisco Nexus 6001 Chassis ("Nexus 64 Supervisor")
  Intel(R) Xeon(R) CPU  @ 2.00 with 8238044 kB of memory.
  Processor Board ID FOC17403BG5
```
Version: `7.3(4)N1(1)`

Playbook

```yaml
- name: PUT INTERFACE INTO DEFAULT STATE
  nxos_config:
    lines:
      - default interface Ethernet1/5
    provider: "{{ connection }}"

- name: CONFIGURE EDGE TRUNK TYPE
  nxos_config: &config
    lines:
      - description foo
      - switchport
      - switchport access vlan 3333
      - spanning-tree port type edge
    parents: "interface Ethernet1/5"
    provider: "{{ connection }}"

- name: IDEMPOTENCE CHECK
  nxos_config: *config
```

Run the playbook

```
TASK [nxos_l2_interface : PUT INTERFACE INTO DEFAULT STATE] **********************************************************************************************************************************************************************************
changed: [n6k.example.com]

TASK [nxos_l2_interface : CONFIGURE EDGE TRUNK TYPE] *****************************************************************************************************************************************************************************************
changed: [n6k.example.com]

TASK [nxos_l2_interface : IDEMPOTENCE CHECK] *************************************************************************************************************************************************************************************************
ok: [n6k.example.com]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
n6k.example.com           : ok=10   changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Interface after running playbook:

```
n6k-77# sh run int e1/5

!Command: show running-config interface Ethernet1/5
!Time: Fri Mar 22 09:54:00 2019

version 7.3(4)N1(1)

interface Ethernet1/5
  description foo
  switchport
  switchport access vlan 3333
  spanning-tree port type edge

n6k# 
```

NOTE: This works for both `network_cli` and `nxapi`
