### ISSUE TITLE
‘’ansible -i inventory all -m setup‘’ cost more than 1 hour and no return

### ISSUE THREAD

**Issue by lojies** [ansible/ansible#50646]
##### SUMMARY

```shell
ansible-playbook -i inventory test.yml
```
gather_facts cost more than 1 hour and return nothing
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core
##### ANSIBLE VERSION

```paste below
ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.11+ (default, Apr 17 2016, 14:00:29) [GCC 5.3.1 20160413]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
```

##### OS / ENVIRONMENT

```shell
root@host90:/home/ubuntu# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

root@host90:/home/ubuntu# uname -a
Linux host90 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: true
  become: yes
  tasks:
    - shell: sleep 20
```
then i add different gather_subset
```yaml
---
- hosts: masters
  gather_facts: true
  gather_subset: ['network','!ohai','!hardware','!virtual','!facter']
  become: yes
  tasks:
    - shell: sleep 20
```
```shell
root@host90:/home/ubuntu# ansible-playbook -i inventory test.yml

PLAY [masters] ************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
Tuesday 08 January 2019  17:17:12 +0800 (0:00:00.094)       0:00:00.094 *******
ok: [10.47.225.93]

TASK [command] ************************************************************************************************************************************
Tuesday 08 January 2019  17:17:41 +0800 (0:00:28.810)       0:00:28.904 *******
changed: [10.47.225.93]

PLAY RECAP ****************************************************************************************************************************************
10.47.225.93               : ok=2    changed=1    unreachable=0    failed=0

Tuesday 08 January 2019  17:18:01 +0800 (0:00:20.629)       0:00:49.534 *******
===============================================================================
Gathering Facts --------------------------------------------------------------------------------------------------------------------------- 28.81s
command ----------------------------------------------------------------------------------------------------------------------------------- 20.63s

```
```yaml
---
- hosts: masters
  gather_facts: true
  gather_subset: ['!network','ohai','!hardware','!virtual','!facter']
  become: yes
  tasks:
    - shell: sleep 20
```
```shell
root@host90:/home/ubuntu# ansible-playbook -i inventory test.yml

PLAY [masters] ************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
Tuesday 08 January 2019  17:18:42 +0800 (0:00:00.095)       0:00:00.095 *******
ok: [10.47.225.93]

TASK [command] ************************************************************************************************************************************
Tuesday 08 January 2019  17:19:09 +0800 (0:00:26.974)       0:00:27.069 *******
changed: [10.47.225.93]

PLAY RECAP ****************************************************************************************************************************************
10.47.225.93               : ok=2    changed=1    unreachable=0    failed=0

Tuesday 08 January 2019  17:19:29 +0800 (0:00:20.627)       0:00:47.697 *******
===============================================================================
Gathering Facts --------------------------------------------------------------------------------------------------------------------------- 26.97s
command ----------------------------------------------------------------------------------------------------------------------------------- 20.63s
```
```yml
- hosts: masters
  gather_facts: true
  gather_subset: ['!network','!ohai','hardware','!virtual','!facter']
  become: yes
  tasks:
    - shell: sleep 20
```
this can not return anything as gather all facts.
```yml
- hosts: masters
  gather_facts: true
  gather_subset: ['!network','!ohai','!hardware','virtual','!facter']
  become: yes
  tasks:
    - shell: sleep 20
```
```shell
root@host90:/home/ubuntu# ansible-playbook -i inventory test.yml

PLAY [masters] ************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
Tuesday 08 January 2019  20:14:51 +0800 (0:00:00.095)       0:00:00.095 *******
ok: [10.47.225.93]

TASK [command] ************************************************************************************************************************************
Tuesday 08 January 2019  20:15:18 +0800 (0:00:26.995)       0:00:27.090 *******
changed: [10.47.225.93]

PLAY RECAP ****************************************************************************************************************************************
10.47.225.93               : ok=2    changed=1    unreachable=0    failed=0

Tuesday 08 January 2019  20:15:38 +0800 (0:00:20.629)       0:00:47.720 *******
===============================================================================
Gathering Facts --------------------------------------------------------------------------------------------------------------------------- 27.00s
command ----------------------------------------------------------------------------------------------------------------------------------- 20.63s
```
```yml
- hosts: masters
  gather_facts: true
  gather_subset: ['!network','!ohai','!hardware','!virtual','facter']
  become: yes
  tasks:
    - shell: sleep 20
```yml
```
```shell
root@host90:/home/ubuntu# ansible-playbook -i inventory test.yml

PLAY [masters] ************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************
Tuesday 08 January 2019  20:17:42 +0800 (0:00:00.093)       0:00:00.093 *******
ok: [10.47.225.93]

TASK [command] ************************************************************************************************************************************
Tuesday 08 January 2019  20:18:10 +0800 (0:00:28.070)       0:00:28.164 *******
changed: [10.47.225.93]

PLAY RECAP ****************************************************************************************************************************************
10.47.225.93               : ok=2    changed=1    unreachable=0    failed=0

Tuesday 08 January 2019  20:18:30 +0800 (0:00:20.633)       0:00:48.797 *******
===============================================================================
Gathering Facts --------------------------------------------------------------------------------------------------------------------------- 28.07s
command ----------------------------------------------------------------------------------------------------------------------------------- 20.63s
```

##### ACTUAL RESULTS

```paste below

```
what should i provide to resolve this?
