### ISSUE TITLE
docker_swarm_service incorrectly detects services running if names have a common prefix

### ISSUE THREAD

**Issue by rjw57** [ansible/ansible#50654]
##### SUMMARY

The Docker API used to query services takes a filter parameter. Filtering by name includes services whose name matches the name given but the match is not exact. For example, if there are services "foo-bar" and "foo-buzz" running then searching for a service with name "foo" matches both.

In this case, the logic used by docker_swarm_service to determine if the "foo" service was running would incorrectly determine that it is.

The upshot of this is that if you have a playbook which defines services with a common prefix and then have a service after whose name is *just* the prefix, the second service will fail to deploy since Ansible will either ignore it or try to delete a non-existent service first.

I think the following line change in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_swarm_service.py#L877 should help:

```python
# The "name" filter matches substrings so make sure to filter the returned results
# by the exact service name.
raw_data = [
    element for element in self.client.services(filters={'name': name})
    if element['Spec']['Name'] == name
]
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_swarm_service

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.0 (default, Sep  5 2018, 03:25:31) [GCC 6.3.0 20170516]

```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/home/xxxxx/.ansible.cfg) = ['/home/xxxxx/yyyyy/ansible/roles']

```
(redacted to remove local paths)
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  become: true
  tasks:                    
  - name: start service 1
    docker_swarm_service:   
      name: myservice-suffix
      image: "alpine:edge"  
      args:                 
        - "sleep"           
        - "7200"            
  - name: start service 2   
    docker_swarm_service:   
      name: myservice       
      image: "alpine:edge"  
      args:                 
        - "sleep"           
        - "7200"            
```

If the playbook runs correctly to begin with, remove the "myservice" service manually and try again.

##### EXPECTED RESULTS

Two services start.

##### ACTUAL RESULTS

Depending on the state of the swarm, one service will start since the "myservice-suffix" service will start and then Ansible incorrectly determines that the "myservice" service is already running.

```paste below
PLAY [test-cluster] ***************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [start service 1] ************************************************************************************************
ok: [localhost]

TASK [start service 2] ************************************************************************************************
ok: [localhost]


Then only one service is running.

$ docker service ls | grep myservice
ywmf7y7q586d        myservice-suffix          replicated          1/1                 alpine:edge                        

```
