### ISSUE TITLE
unable to use --- k8s modules or kubernetes modules in ansible 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#50668]
##### SUMMARY

unable to use --- k8s modules or kubernetes modules in ansible 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.6.11
  config file = /Users/kylix3511/k8s/learning/ansible.cfg
  configured module search path = [u'/Users/kylix3511/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kylix3511/venv260/lib/python2.7/site-packages/ansible
  executable location = /Users/kylix3511/venv260/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
ANSIBLE_PIPELINING(/Users/kylix3511/k8s/learning/ansible.cfg) = False
DEFAULT_FORKS(/Users/kylix3511/k8s/learning/ansible.cfg) = 10
DEFAULT_HOST_LIST(/Users/kylix3511/k8s/learning/ansible.cfg) = [u'/Users/kylix3511/k8s/learning/hosts']
DEFAULT_INTERNAL_POLL_INTERVAL(/Users/kylix3511/k8s/learning/ansible.cfg) = 0.001
DEFAULT_TIMEOUT(/Users/kylix3511/k8s/learning/ansible.cfg) = 10
HOST_KEY_CHECKING(/Users/kylix3511/k8s/learning/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/Users/kylix3511/k8s/learning/ansible.cfg) = True
RETRY_FILES_ENABLED(/Users/kylix3511/k8s/learning/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
kylix3511  (e) venv260  ~  k8s  learning  cat ansible1.yaml 
---
- hosts: node1 
  #become: true
  #gather_facts: yes
  connection: local

  tasks:
    - name: Create a kubernetes namespace
      kubernetes:
        api_endpoint: 192.168.26.10
        insecure: true
        inline_data:
          kind: Namespace
          apiVersion: v1
          metadata:
            name: ansible-test
            labels:
              label_env: production
              label_ver: latest
            annotations:
              a1: value1
              a2: value2
          state: present
 kylix3511  (e) venv260  ~  k8s  learning  



 kylix3511  (e) venv260  ~  k8s  learning  cat ansible2.yaml 
---
- hosts: master 
  connection: local

  tasks:
    - name: Create a kubernetes namespace
      k8s_raw:
        name: testing
        api_version: v1
        kind: Namespace
        state: present
 kylix3511  (e) venv260  ~  k8s  learning  


```

##### ACTUAL RESULTS

```paste below
kylix3511  (e) venv260  ~  k8s  learning  ansible-playbook ansible1.yaml -vvv
ansible-playbook 2.6.11
  config file = /Users/kylix3511/k8s/learning/ansible.cfg
  configured module search path = [u'/Users/kylix3511/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kylix3511/venv260/lib/python2.7/site-packages/ansible
  executable location = /Users/kylix3511/venv260/bin/ansible-playbook
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
Using /Users/kylix3511/k8s/learning/ansible.cfg as config file
Parsed /Users/kylix3511/k8s/learning/hosts inventory source with ini plugin
[DEPRECATION WARNING]: kubernetes is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more 
about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

PLAYBOOK: ansible1.yaml ************************************************************************************************************************************
1 plays in ansible1.yaml

PLAY [node1] ***********************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************
task path: /Users/kylix3511/k8s/learning/ansible1.yaml:2
<node1> ESTABLISH LOCAL CONNECTION FOR USER: kylix3511
<node1> EXEC /bin/sh -c 'echo ~kylix3511 && sleep 0'
<node1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745 `" && echo ansible-tmp-1546978453.7-240329721142745="` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745 `" ) && sleep 0'
Using module file /Users/kylix3511/venv260/lib/python2.7/site-packages/ansible/modules/system/setup.py
<node1> PUT /Users/kylix3511/.ansible/tmp/ansible-local-25871ibryO5/tmpNRmJrD TO /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745/setup.py
<node1> EXEC /bin/sh -c 'chmod u+x /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745/ /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745/setup.py && sleep 0'
<node1> EXEC /bin/sh -c '/usr/bin/python /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745/setup.py && sleep 0'
<node1> EXEC /bin/sh -c 'rm -f -r /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978453.7-240329721142745/ > /dev/null 2>&1 && sleep 0'
ok: [node1]
META: ran handlers

TASK [Create a kubernetes namespace] ***********************************************************************************************************************
task path: /Users/kylix3511/k8s/learning/ansible1.yaml:8
<node1> ESTABLISH LOCAL CONNECTION FOR USER: kylix3511
<node1> EXEC /bin/sh -c 'echo ~kylix3511 && sleep 0'
<node1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235 `" && echo ansible-tmp-1546978454.49-23446214182235="` echo /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235 `" ) && sleep 0'
Using module file /Users/kylix3511/venv260/lib/python2.7/site-packages/ansible/modules/clustering/k8s/_kubernetes.py
<node1> PUT /Users/kylix3511/.ansible/tmp/ansible-local-25871ibryO5/tmpGSaITt TO /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235/_kubernetes.py
<node1> EXEC /bin/sh -c 'chmod u+x /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235/ /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235/_kubernetes.py && sleep 0'
<node1> EXEC /bin/sh -c '/usr/bin/python /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235/_kubernetes.py && sleep 0'
<node1> EXEC /bin/sh -c 'rm -f -r /Users/kylix3511/.ansible/tmp/ansible-tmp-1546978454.49-23446214182235/ > /dev/null 2>&1 && sleep 0'
fatal: [node1]: FAILED! => {
    "changed": false, 
    "headers": {
        "Authorization": "Basic YWRtaW46", 
        "Content-Type": "application/json"
    }, 
    "invocation": {
        "module_args": {
            "api_endpoint": "192.168.26.10", 
            "certificate_authority_data": null, 
            "file_reference": null, 
            "force_basic_auth": true, 
            "http_agent": "ansible-k8s-module/0.0.1", 
            "inline_data": "{'kind': 'Namespace', 'state': 'present', 'apiVersion': 'v1', 'metadata': {'labels': {'label_env': 'production', 'label_ver': 'latest'}, 'name': 'ansible-test', 'annotations': {'a1': 'value1', 'a2': 'value2'}}}", 
            "insecure": true, 
            "patch_operation": "Strategic Merge Patch", 
            "state": "present", 
            "url_password": "", 
            "url_username": "admin", 
            "validate_certs": false
        }
    }, 
    "method": "POST", 
    "msg": "Failed to execute the API request: Request failed: <urlopen error [Errno 61] Connection refused>", 
    "url": "http://192.168.26.10/api/v1/namespaces"
}

PLAY RECAP *************************************************************************************************************************************************
node1                      : ok=1    changed=0    unreachable=0    failed=1   

 kylix3511  (e) venv260  ~  k8s  learning  
```
