### ISSUE TITLE
Windows become does not unload profile for Server 2008 and 2008 R2

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#50688]
##### SUMMARY
When using become on a Windows Server 2008 or 2008 R2 host, the profile for the become user is not unloaded after the task is complete. This means the profile for that user is unable to be removed until the host is restarted. I could not replicate the same behaviour on Server 2012+.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/executor/powershell/become_wrapper.ps1

##### ANSIBLE VERSION
```paste below
devel
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Remote Windows 2008 and 2008 R2

##### STEPS TO REPRODUCE
Make sure you are targeting a Server 2008 or 2008 R2 host.

```yaml
---
- hosts: 2008r2
  gather_facts: no

  tasks:
  - win_shell: echo hi
    become: True
    become_method: runas
    vars:
      ansible_become_user: '{{ ansible_user }}'
      ansible_become_pass: '{{ ansible_password }}'
```

Once done, check the keys in `regedit.exe` and the hive for the become user will still be present. This should have been unloaded after the task had completed.

You can not load the profile in the task with `become_flags: logon_flags=` but this is not the default. Once the profile has been loaded you will need to reboot the host for it to be unloaded again.

##### EXPECTED RESULTS
The profiles keys under `HKEY_USERS` for the become user should not be there.

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/8462645/50871151-73ff9600-1406-11e9-8b5d-e39e5040b62b.png)
