### ISSUE TITLE
Add support for options to Make module

### ISSUE THREAD

**Issue by cvoltz** [ansible/ansible#50692]
##### SUMMARY
Add support to the `make` module so it can accept short and long option switches like `-k` and `--keep-going`. The existing `params` parameter is a dictionary which only supports assignments of a key and value with no hyphen to provide the equivalent of `make target KEY=VALUE`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
make

##### ADDITIONAL INFORMATION
The `make` command supports many option switches in both long and short forms. The current `make` module has no mechanism to allow such options to be specified. Ideally, the mechanism which is provided would support any option that the `make` command supports so an option like `args` which accepts a string or a list of items would be simple to implement. If a generic mechanism isn't available then at least commonly used options (e.g., `--jobs=8`) should be supported.

With the current implementation, it isn't possible to do things like:
- use the environment to override `makefile` variables (`-e`, `--environment-overrides`)
- unconditionally make all targets (`-B`, `--always-make`)
- ignore errors (`-i`, `--ignore-errors`)
- specify a directory to search for included makefiles (`-I`, `--include-dir=dir`)
- specify the number of jobs to run (`-j [jobs]`, `--jobs[=jobs]`)
- continue as much as possible after an error (`-k`, `--keep-going`)
- disable builtin rules (`-r`, `--no-builtin-rules`)

While it is OK to still require the hyphens when taking the args as a string, using the hyphens in a list of items is awkward so they shouldn't be required (when processing the item, just prepend a single hyphen if the item is only one character and prepend two hyphens when the item is multiple characters). In both case, one should be able to specify the options with or without the hyphen.

```yaml
# arg string without hyphens 
- make:
    chdir: "{{ build_path }}"
    target: rpm-dkms
    args: jobs=8 keep-going 

# arg list without hyphens
- make
    chdir: "{{ build_path }}"
    target: rpm
    args:
    - i
    - always-make
    - jobs=8

# arg string with hyphens
- make:
    chdir: "{{ build_path }}"
    target: rpm-dkms
    args: --jobs=8 --keep-going 

# arg list with hyphens
- make
    chdir: "{{ build_path }}"
    target: rpm
    args:
    - -i
    - --always-make
    - -W file
```
