### ISSUE TITLE
Uri module fails to download file into directory

### ISSUE THREAD

**Issue by bsibaud** [ansible/ansible#50719]
Affect at least all tested versions from Ansible 2.1.6 to 2.7.5.

##### SUMMARY

uri module fails to download a file when dest is a directory and file is "big enough" (depending on local or remote connection). Not reading data received on the socket, so full TCP window, no more data received, client timeout (nothing received during 30s (default timeout) for example).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/local/lib/python2.7/site-packages/ansible
  executable location = /home/xxx/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
```

##### CONFIGURATION
```
(empty)
```

##### OS / ENVIRONMENT
Ubuntu 14.04 or CentOS 7.6

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    - src_dir: /tmp/ansible-uri-test-src
    - dst_dir: /tmp/ansible-uri-test-dst
  tasks:

  # setup mock
  - name: create folders
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ src_dir }}"
      - "{{ dst_dir }}"
  - name: create dummy file
    command: dd if=/dev/urandom of={{ src_dir }}/file_{{ item }} bs=1024 count={{ item }}
    with_items:
      - 1
      - 10
      - 100
      - 1000
      - 10000
  - name: launch local simple http server
    command: python -m SimpleHTTPServer 8000
    args:
      chdir: "{{ src_dir }}"
    async: 120
    poll: 0
    register: simple_http_server

  # test
  - block:
    - name: get file using uri module and dest filename (success)
      uri:
        url: "http://localhost:8000/file_{{ item }}"
        dest: "{{ dst_dir }}/with_filename_{{ item }}"
        method: GET
        status_code: 200
      with_items:
        - 1
        - 10
        - 100
        - 1000
        - 10000

    - name: get file using uri module and dest directory (failure)
      uri:
        url: "http://localhost:8000/file_{{ item }}"
        dest: "{{ dst_dir }}"
        method: GET
        status_code: 200
      with_items:
        - 1
        - 10
        - 100
        - 1000
        - 10000

  # terminate mock and cleanup
    always:
    - name: stop local simple http server
      shell: kill -HUP $(pgrep -f "^python -m SimpleHTTPServer 8000$")
    - name: wait for local simple http server to stop
      async_status:
        jid: "{{ simple_http_server.ansible_job_id }}"
      register: simple_http_server_result
      until: simple_http_server_result.finished
      retries: 5
      delay: 5
      failed_when: no
    - name: delete folders
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ src_dir }}"
        - "{{ dst_dir }}"

```

##### EXPECTED RESULTS
All files are retrieved and stored.

##### ACTUAL RESULTS
Fail to retrieve 10 MB file. "Status code was -1 and not [200]: Connection failure: timed out"

```
TASK [get file using uri module and dest directory (failure)] *************************************************************************************************************
(...)
failed: [localhost] (item=10000) => {
    "changed": false,
    "content": "",
    "content_length": "10240000",
    "content_type": "application/octet-stream",
    "cookies": {},
    "cookies_string": "",
    "date": "Wed, 09 Jan 2019 17:01:36 GMT",
    "gid": 1021,
    "group": "xxx",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": "/tmp/ansible-uri-test-dst",
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "path": "/tmp/ansible-uri-test-dst/file_10000",
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "200"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "http://localhost:8000/file_10000",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "item": 10000,
    "last_modified": "Wed, 09 Jan 2019 17:01:32 GMT",
    "mode": "0664",
    "msg": "Status code was -1 and not [200]: Connection failure: timed out",
    "owner": "xxx",
    "path": "/tmp/ansible-uri-test-dst/file_10000",
    "redirected": false,
    "server": "SimpleHTTP/0.6 Python/2.7.6",
    "size": 0,
    "state": "file",
    "status": -1,
    "uid": 1021,
    "url": "http://localhost:8000/file_10000"
}

```

**Comment by sivel** [comment]
Is there a good reason to not use the `get_url` module to download a file?

The `dest` functionality of the `uri` module is really designed to allow downloading of files that occur when performing non-GET operations such as POST or PUT.

The `get_url` module is much  more equipped for handling file downloads than the `uri` module.

**Comment by ansibot** [comment]
cc @romeotheriault
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bsibaud** [comment]
Just to be clear: it also fails to download a 512 KiB file from a distant Apache httpd through a squid proxy (the "10 MB limit" on localhost in the test playbook is larger than the "limit" for files retrieve through network)

**Comment by bsibaud** [comment]
> Is there a good reason to not use the `get_url` module to download a file?

First, 'uri' module documentation doesn't contain "Prefer get_url for downloading files" or "Uri module is not suited to download files" or "Be careful the whole retrieved file will be stored into memory, that's why uri module for GB file is a bad idea". (I would say that may be the "documentation part" of the issue)

Second, even if get_url does the trick, we may expect uri module with default GET method to be able to successfully retrieve small files like a 512 kiB file (a webservice may have a 512 kiB answer). (I would say that may be the "technical part" of this issue)

**Comment by sivel** [comment]
> Second, even if get_url does the trick, we may expect uri module with default GET method to be able to successfully retrieve small files

Does it "do the trick"?

**Comment by bsibaud** [comment]
> Does it "do the trick"?

It does. In the given playbook, replace uri by get_url, remove method and status parameters, and it will work. Even if based on the same common module_utils/urls.py file, get_url doesn't exactly use the same part of code.

**Comment by sivel** [comment]
There is one thing in `uri` that I am going to work on changing, and that is if `dest` is a directory (not a  file), the `uri` module performs 2 GET requests on the same URL.  I've meant to fix this for a while now, but haven't done it.

The other thing to note, aside from the double request above, is that `uri` will consume more memory and execute slower when fetching larger files.  I am unsure if I can resolve this in any decent way.  The reason is that `uri` is typically used for fetching data but not storing into a file, thus it reads the contents into a variable to later return in the module response.  `get_url` doesn't do this, as it's only goal is to download to a file.  Due to this, `uri` reads the whole response into a var, and then later it will write the contents of that var into a file.

In `uri` the `return_content` and `dest` options are not mutually exclusive, and json parsing happens regardless of `return_content`.  Due to this, we always need the content read into a variable.  There may be small room for improvement, but I am unsure how much that performance hit can be solved for.

Generally speaking however, both the `get_url` module and the `uri` module use the same underlying function (`fetch_url`) for downloading the file, it's just the means in which it stores the results that are different (with the exclusion of the double request that I plan to resolve).

**Comment by sivel** [comment]
I've opened the above PR to begin work on some improvements to the `uri` module.  I have some more time sensitive work coming down the pipeline, so that PR is likely to stall for a while.

In the mean time, as mentioned, using `get_url` would be the best approach.

**Comment by urskog84** [comment]
I get the same type off error when i Upload/POST file to a API.

**Error**
`Status code was -1 and not [200]: Request failed: <urlopen error [Errno 32] Broken pipe>` 


**Playbook task.**
```
- name: Add Engine file and main DAT file.
  uri:
    url: "{{ epo_url }}/remote/ext.install?deleteIfExists=true"
    method: POST
    src: /mnt/nest/Software/McAfee/JavaVersion_Recommended_by_TEC/McAfee Antivirus/Update/{{ item }}
    user: "{{ epo_mfsadminusername_ue }}"
    password: "{{ epo_mfsadminpassword_ue }}"
    force_basic_auth: "yes"
    status_code: 200
    validate_certs: no
    timeout: 120
  delegate_to: localhost
  with_items:
  - epo6010eng.zip
  - epoV3_3860.0dat.zip
  loop_control:
    pause: 15
  tags: upload_dat
```
**Error on run**
```
failed: [U00-VM-EPO1 -> localhost] (item=epoV3_3860.0dat.zip) => {
    "ansible_loop_var": "item",
    "changed": false,
    "content": "",
    "elapsed": 1,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": true,
            "group": null,
            "headers": {
                "Content-Length": 197927417
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/root/.ansible/tmp/ansible-tmp-1598522949.3162155-11401-97324588261868/epoV3_3860.0dat.zip",
            "status_code": [
                "200"
            ],
            "timeout": 120,
            "unix_socket": null,
            "unsafe_writes": null,
            "url": "https://193.181.215.214:443/remote/ext.install?deleteIfExists=true",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "EPO",
            "use_proxy": true,
            "user": "EPO",
            "validate_certs": false
        }
    },
    "item": "epoV3_3860.0dat.zip",
    "redirected": false,
    "status": -1,
    "url": "https://193.181.215.214:443/remote/ext.install?deleteIfExists=true"
}

MSG:

Status code was -1 and not [200]: Request failed: <urlopen error [Errno 32] Broken pipe>
```
