### ISSUE TITLE
openssl_pkcs12 should add 'chain' option

### ISSUE THREAD

**Issue by pjnagel** [ansible/ansible#50742]
##### SUMMARY
The command-line "openssl pkcs12 -export" utility has a -chain option. It includes all certificates in the chain of trust, up to and including the root. To find the root certificates, it looks in the path as specified by -CAfile and -CApath

The openssl_pkcs12 module has no equivalent option, although it does have equivalents for -CAfile (ca_certificates) and -CApath (certificate_path).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssl_pkcs12

##### ADDITIONAL INFORMATION
Example of why this is useful: I was trying to configure SSL on a Wildfly server, starting with an SSLForFree PEM format private key/certificate. That Wildfly server was configured to use a pkcs12 keystore. However, the default Java keystore on that server did not contain the root of trust for the SSLForFree CA, so I needed "openssl -export -chain ..." for the Wildfly server to make a self-contained PKCS#12 file containing the entire chain of trust.

```yaml
- name: 'Generate PKCS#12 file'
  openssl_pkcs12:
    action: export
    path: '/path-to/output.p12'
    privatekey_path: '/path-to/private-key.pem'
    ca_certificates: '/path-to/intermediate-certs-from-CA.pem'
    certificate_path: '/etc/ssl/certs'
    chain: true
    state: present
```
