### ISSUE TITLE
How to fetch the API URL from a Python file and use the URL in URI Module of Anisble

### ISSUE THREAD

**Issue by m2harshanalore** [ansible/ansible#50800]
##### SUMMARY

I have a python file which contains the task to interact with an application.How can i utilize this python file to integrate with URI Module of Ansible.

##### ISSUE TYPE
- 

##### COMPONENT NAME

URI Module of Ansible

##### ADDITIONAL INFORMATION

Basically i have a python file which possess function to perform various tasks on a web application. I need to utilize this file and build a Ansible URI module to perform API request to application.

```yaml
- name: URI Module
  uri:
    url: 
    method: POST
    headers:
      Content-Type: "application/json"
    force_basic_auth: no
    status_code: 200,201
    return_content: yes
    body: "{{ body }}"
    body_format: json
    validate_certs: no
```
