### ISSUE TITLE
service module detects status incorrectly when using openrc

### ISSUE THREAD

**Issue by davidklaftenegger** [ansible/ansible#50822]
##### SUMMARY
When using openrc, the service module does not always correctly detect a service that has already been started. This is caused by ansible looking for string output from `rc-service myservicename status` instead of looking at the return code.

See https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py line 615-618.

To confirm the behaviour is incorrect, I opened two bugs for affected gentoo packages:
https://bugs.gentoo.org/672128
https://bugs.gentoo.org/674836

As a result, I was pointed to
http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html

On freenode #openrc it was confirmed, that the return code is the correct way of checking for the current status. I was also given a warning that it might not always conform to the standard, but should at least have return code zero for "started" and non-zero for any error condition.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /home/david/.ansible.cfg
  configured module search path = [u'/home/david/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python2.7/site-packages/ansible
  executable location = /usr/lib/python-exec/python2.7/ansible
  python version = 2.7.14 (default, Feb  2 2018, 06:32:02) [GCC 6.4.0]
```

##### CONFIGURATION
irrelevant.
```
ANSIBLE_NOCOWS(/home/david/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/david/.ansible.cfg) = [u'profile_roles']
DEFAULT_FORKS(/home/david/.ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/david/.ansible.cfg) = [u'/home/david/ansible/hosts']
DEFAULT_LOCAL_TMP(/home/david/.ansible.cfg) = /tmp/ansible/ansible-local-283898scY7h
DEFAULT_STDOUT_CALLBACK(/home/david/.ansible.cfg) = default
DISPLAY_SKIPPED_HOSTS(/home/david/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/david/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Gentoo, using openrc

##### STEPS TO REPRODUCE
1) Install some package with an init script that overrides status() output
2) start said init script
3) run ansible service module, set state=started

##### EXPECTED RESULTS
in step 3 above, the status should be ok, not changed

##### ACTUAL RESULTS
the status is changed, despite the service already running

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
The service module treats openrc much like init scripts, it cannot fully rely on return codes of these as they tend to be misleading so we also end up parsing the return text, which is fragile. As much as openrc does the 'right thing' the scripts it calls may not and we had to deal with those cases. Gentoo packagers are particularly good about the quality, standards adherence and behaviour of the init scripts, but sadly not all distributions do the same.

Can you point us to the specific service that cause this issue or a small reproducer? The current code has been working as is for a long time and I (as a Gentoo/openrc user) have not encountered the issue you describe.

needs_info

FYI, I did have a openrc module planned, but my schedule has not really allowed me to complete it.

**Comment by davidklaftenegger** [comment]
According to the openrc IRC channel, having the wrong return code would be considered a bug in the init script, and should be fixed there. Having differing output is not considered a bug, as the output is purely informational. The output that the service module currently expects happens to be the default output iff the init script does not override the status function, but in these cases I'd expect the return code to also be correct. When status is overwritten in the script, then I can see how it might be incorrect, but these are also the cases where output is differing.

The two init scripts that I discovered thus far are zfs-import (from sys-fs/zfs) and postgresql-10 (from dev-db/postgresql:10), also see the two gentoo bugs linked above. If it helps, I can write a short playbook to cause the issue.

**Comment by davidklaftenegger** [comment]
assuming a working gentoo host, with no postgresql installed, and no configuration nor data directory for postgresql around:
```
- name: service module problem
  hosts: all
  remote_user: root
  become: yes
  tasks:
          - name: make sure postgresql is installed
            portage:
                    package: "dev-db/postgresql:10"
                    state: present
                    noreplace: yes
          - name: configure postgresql
            command: "emerge --config dev-db/postgresql:10"
            args:
                    creates: "/var/lib/postgresql/10/data"
          - name: start service
            service:
                    name: "postgresql-10"
                    state: started
                    enabled: yes
                    use: openrc
```
on the first run, everything seems fine:
```
PLAY RECAP ************************************************************
db.eddiehost.dkl.vpn       : ok=4    changed=3    unreachable=0    failed=0
```
but when running it again this yields:
```
PLAY RECAP ************************************************************
db.eddiehost.dkl.vpn       : ok=4    changed=1    unreachable=0    failed=0
```
which is unexpected, as the service is already running & enabled.

A similar playbook for zfs-import could be written, but it requires loading the out-of-tree kernel module for zfs, so it is somewhat more involved to prepare a system for it.
