### ISSUE TITLE
cannot import name mysql_driver

### ISSUE THREAD

**Issue by thomasliddledba** [ansible/ansible#50832]
##### SUMMARY
Receiving an error when adding a MySQL user using the database module for MySQL

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 
[Database modules - MySQL](https://docs.ansible.com/ansible/latest/modules/mysql_user_module.html#mysql-user-module)

##### ANSIBLE VERSION

```paste below
 $ ansible --version
ansible 2.5.2
```

##### CONFIGURATION

```paste below
 $ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(~/repos/ansible-role-mysql/ansible.cfg) = [u'~/repos']
HOST_KEY_CHECKING(~/repos/ansible-role-mysql/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Linux DESKTOP-H45BGP4 4.4.0-17134-Microsoft #523-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

*defaults/main.yml*
```yaml
---
mysql_users:
  - name: 'db_usr'
    host: '%'
    password: 'MyPassword~1234'
    priv: 'db.*:ALL'
```
*tasks/main.yml*
```yaml
---
- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  no_log: false
```
*playbook.yml*
```yaml
---
- name: Converge
  hosts: all
  become: 'yes'
  roles:
    - role: ansible-role-mysql
```

##### EXPECTED RESULTS

The user is created in MySQL.

##### ACTUAL RESULTS

The user does not be created and the debug gives the following error:

```paste below
    failed: [mysqlmachine] (item={u'host': u'%', u'password': u'MyPassword~1234', u'name': u'db_usr', u'priv': u'db.*:ALL'}) => {
        "changed": false,
        "item": {
            "host": "%",
            "name": "db_usr",
            "password": "MyPassword~1234",
            "priv": "db.*:ALL"
        },
        "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
        "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7CayMJ/ansible_module_mysql_user.py\", line 201, in <module>\r\n    from ansible.module_utils.mysql import mysql_connect, mysql_driver, mysql_driver_fail_msg\r\nImportError: cannot import name mysql_driver\r\n",
        "msg": "MODULE FAILURE",
        "rc": 1
    }
```
