### ISSUE TITLE
gcp_compute_disk does not work with snapshots

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#50839]
##### SUMMARY

Creating a disk from a snapshot fails with `gcp_compute_instance`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### CONFIGURATION

```paste below
None
```

##### STEPS TO REPRODUCE

```yaml                                   
- gcp_compute_disk:                                                   
    name: disk-name                                           
    # size_gb: 10                                   
    source_snapshot:                                                  
      selfLink:     
        projects/project-here/global/snapshots/snapshot-name            
```

##### EXPECTED RESULTS

The disk to be created from the snapshot

##### ACTUAL RESULTS

In my case, I tried to use the created disk as boot disk to create a new instance. The creation of the instance succeeded but the new instance was shut down after 15 seconds. In the google cloud logs it said that the shutdown was done from the guest os. I noticed that while the snapshot was created from a disk of 10gb, the created disk was of size 500gb. So, I added the commented-out line in the example above. Then I repeated the disk creation but that didn't change anything. I then compared the logs that `gcp_compute_disk` generates to the ones that are generated by the `gcloud` utility. It seems that `gcp_compute_disk` just creates an empty disk instead of using the snapshot.

gcloud logs:
```
 request: {
   @type: "type.googleapis.com/compute.disks.insert"    
   name: "name-here"    
   sourceSnapshot: "https://www.googleapis.com/compute/v1/projects/project-here/global/snapshots/snapshot-here"    
  }
```

gcp_compute_disk logs:
```
 request: {
   @type: "type.googleapis.com/compute.disks.insert"    
   name: "en2720-w1-cuiteur"    
   sizeGb: "10"    
  }
```
