### ISSUE TITLE
Add support for AWS FSX for Lustre

### ISSUE THREAD

**Issue by RodneyMarable** [ansible/ansible#50840]
##### SUMMARY
Please add support for AWS FSX for Lustre (https://aws.amazon.com/fsx/lustre/).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Two new modules should be created:

fsx_lustre (create and maintain FSX_Lustre file systems)
fsx_lustre_facts (obtain information about existing FSX_Lustre file systems)

##### ADDITIONAL INFORMATION

"fsx_lustre" and "fsx_lustre_facts" should provide similar functionality to the existing "efs" and "efs_facts" modules.

Something like this:

```yaml
  - name: Delete an FSX_Lustre file system
      fsx_lustre:
        state: absent
        name: "{{ fsx_lustre_fs_id }}"
        az: "{{ aws_availability_zone }}"
```
