### ISSUE TITLE
Copy module does not validate when using content instead of src

### ISSUE THREAD

**Issue by viralpoetry** [ansible/ansible#50863]
##### SUMMARY
Copy module is trying to validate empty string when rendering destination file from `content` variable instead of just copying files.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abcd/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
(nothing)
```

##### OS / ENVIRONMENT

Ubuntu 18.04 x64
##### STEPS TO REPRODUCE

```yaml
- name: Create configuration
  copy:
    content: "{{ __consul_config | to_nice_json | regex_replace('\"([0-9]+)\"','\\1') }}"
    dest: "{{ consul_config_path }}/config.json"
    owner: "{{ consul_config_owner }}"
    group: "{{ consul_config_group }}"
    mode: "{{ consul_config_mode }}"
    validate: "consul validate %s"
  notify:
    - restart consul
```

##### EXPECTED RESULTS

`validate` command should pass if there is correct config file in the `content` variable.
Maybe rendering content to a `tmp` file then run validation against it is the way.

##### ACTUAL RESULTS

Validation fails probably because it runs against the empty file.

```paste below
fatal: [node1]: FAILED! => {
    "changed": false, 
    "checksum": "284650f4b351ba58eb86ef0a944566ddc04df1a1", 
    "exit_status": 1
}

STDERR:

Config validation failed: data_dir cannot be empty
```
