### ISSUE TITLE
k8s module does not recognize deploymentConfig resource: the server could not find the requested resource

### ISSUE THREAD

**Issue by DAgostinoLucas** [ansible/ansible#50874]
##### SUMMARY

I tried to launch a deploymentConfig with the newest version of Ansible (2.7.5) and [k8s module](https://docs.ansible.com/ansible/latest/modules/k8s_module.html). It failed while the old [openshift_raw module ](https://docs.ansible.com/ansible/2.5/modules/openshift_raw_module.html)(which seemed merge like k8s_raw since 2.6 version) works fine with the same template.

**Seems related to [this closed issue](https://github.com/ansible/ansible/issues/36900)**
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s
##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /home/lda/ansible-2.7.5/projects/Openshift/ansible.cfg
  configured module search path = [u'/home/lda/ansible-2.7.5/projects/Openshift/ansible_custom_modules']
  ansible python module location = /home/lda/ansible-2.7.5/lib/python2.7/site-packages/ansible
  executable location = /home/lda/ansible-2.7.5/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/lda/ansible-2.7.5/projects/Openshift/ansible.cfg) = [u'/home/lda/ansible-2.7.5/projects/Openshift/hosts']
DEFAULT_MODULE_PATH(/home/lda/ansible-2.7.5/projects/Openshift/ansible.cfg) = [u'/home/lda/ansible-2.7.5/projects/Openshift/ansible_custom_modules']
RETRY_FILES_ENABLED(/home/lda/ansible-2.7.5/projects/Openshift/ansible.cfg) = False
```

##### OS / ENVIRONMENT

I'm using **Python virtualenv** to test different versions of Ansible on a machine runnning **RHEL7.6 (Maipo)**. I also use **Openshift 3.6**.
 Output of `oc version`:
```
oc v3.3.1.11
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
Output of `pip show openshift`:
```

Name: openshift
Version: 0.8.2
Summary: OpenShift python client
Home-page: https://github.com/openshift/openshift-restclient-python
Author: OpenShift
Author-email: UNKNOWN
License: Apache License Version 2.0
Location: /home/lda/ansible-2.7.5/lib/python2.7/site-packages
Requires: kubernetes, python-string-utils, ruamel.yaml, jinja2, dictdiffer, six
Required-by:

```
##### STEPS TO REPRODUCE

- Create a playbook with the following task (I create projects before this task, but if you have already a namespace that's ok to test only this task. Otherwise you should create a project/namespace and mention it in your deploymentConfig):

With Ansible 2.7.5, create the task as follow:
```
- name: Create SLA pods through deploymentConfig
  k8s:
    state: present
    kind: DeploymentConfig
    api_version: v1
    name: web-server
    namespace: "smals-lab-availabilitycheck"
    definition: "{{ lookup('template', 'dc.yml') | from_yaml }}"
```
With Ansible 2.5.1:
```
- name: Create SLA pods through deploymentConfig
  openshift_raw:
    state: present
    kubeconfig: /home/lda/.kube/config
    kind: dc
    definition: "{{ lookup('template', '{{ ansible_user_dir }}/ansible-2.7.5/projects/Openshift/dc.yml') | from_yaml }}"
```

- Be sure to have a valid kubeconfig (.kube/config)
- Use [this deploymentConfig file](https://gist.github.com/DAgostinoLucas/4416d882e0f7d9ea0684379a3f6f79f0). **Important Note:** you can of course use another image. The most important is that dc is successfully deployed on Openshift.

##### EXPECTED RESULTS

deploymentConfig (dc) pushed (`changed: True`) if doesn't exist in selected project, not changed if nothing difference between deployed dc and dc pushed from my Ansible task. As k8s module seems the definitive way to control your Kubernetes/Openshift infrastructure, k8s should work.

Just like you run 2.5.1 with openshift_raw:

##### ACTUAL RESULTS

**Ansible 2.7.5 with k8s module:**
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_k8s_payload_yQijNu/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py", line 174, in perform_action
    k8s_obj = resource.create(definition, namespace=namespace).to_dict()
  File "/home/smals-lda/ansible-2.7.5/lib/python2.7/site-packages/openshift/dynamic/client.py", line 43, in inner
    raise api_exception(e)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": 404,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "force": false,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to create object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the server could not find the requested resource\",\"reason\":\"NotFound\",\"details\":{},\"code\":404}\n",
    "reason": "Not Found",
    "status": 404
}
```

Ansible 2.5.1 with openshift_raw module:
```(... truncated output...)
        "status": {
            "available_replicas": 2,
            "conditions": [
                {
                    "last_transition_time": "2019-01-09T14:26:24+00:00",
                    "last_update_time": "2019-01-09T14:26:29+00:00",
                    "message": "replication controller \"web-server-1\" successfully rolled out",
                    "reason": "NewReplicationControllerAvailable",
                    "status": "True",
                    "type": "Progressing"
                },
                {
                    "last_transition_time": "2019-01-14T13:44:56+00:00",
                    "last_update_time": "2019-01-14T13:44:56+00:00",
                    "message": "Deployment config has minimum availability.",
                    "reason": null,
                    "status": "True",
                    "type": "Available"
                }
            ],
            "details": {
                "causes": [
                    {
                        "image_trigger": null,
                        "type": "ConfigChange"
                    }
                ],
                "message": "config change"
            },
            "latest_version": 1,
            "observed_generation": 3,
            "ready_replicas": 2,
            "replicas": 2,
            "unavailable_replicas": 0,
            "updated_replicas": 2
        }
    }
}
```

```paste below
ansible-playbook your_playbook.yml -vvv
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by DAgostinoLucas** [comment]
**Updates/Correction**: my deploymentConfig is pushed up to Ansible 2.5.14, and not only 2.5.1 (juste one version after 2.6, which seems a bit logical in fact).

**Comment by fabianvf** [comment]
Hmm, this seems like it might be an issue with not properly retrieving the resources from /oapi (in later versions of openshift, /oapi is deprecated in favor of custom group/versions). If you downgrade your version of the openshift Python client to 0.7.x (or 0.6.x if that doesn't work), does it work?

**Comment by DAgostinoLucas** [comment]
@fabianvf thanks for your quick answer.

I tried with openshift 0.7.x (.2, .1 and 0.7.0), same result. Also the same with all versions of 0.6.

I did a `pip install openshift==0.x.x --upgrade` each time to test in my virtualenv (e.g `pip install openshift==0.6.1 --upgrade`).

**Comment by fabianvf** [comment]
Interesting, could you paste a minimal example of a playbook + resource definition that's failing so I can try to reproduce this locally?

**Comment by fabianvf** [comment]
One thought I had, does the template you are doing the `lookup` on specify a namespace? The namespace in the template will take precedence over the namespace in the task, which could result in a 404 if the namespace in the template does not exist.

**Comment by DAgostinoLucas** [comment]
@fabianvf  Sorry for delay, had a lot things to do these times :)
Yes indeed it specifies a namespace, but I create all my required namespaces before pushing my dc.
I will send you a minimal example end of this day, promised.

**Comment by DAgostinoLucas** [comment]
@fabianvf ,
Here is (finally) a minimal playbook example. Note that I'm using _oc_project module_ coming from [here](https://github.com/openshift/openshift-ansible/blob/master/roles/lib_openshift/src/ansible/oc_project.py). As a workaround, I'm also using _oc_ module. If you want, you can compare results with that but don't forget to adapt _oc_host/port/token_ according to your environment.

Playbook.yml:
```
---
- name: Play to deploy resources on Openshift
  hosts: ansible-ctrl-acc
  connection: local
  gather_facts: yes
  vars_files:
    - oc_vars.yml
  tasks:
    - name: Create Projects in Openshift tenant
      oc_project:
        state: present
        name: "{{ oc_project_prefix }}-{{ env }}-{{ oc_project_suffix }}"
        display_name: "{{ oc_project_display_name }}"
        description: "{{ oc_project_desc }}"
        kubeconfig: "{{ ansible_user_dir }}/.kube/config"
      register: openshift_project_creation
    - name: Create pods through deploymentConfig
      k8s:
        state: present
        kind: DeploymentConfig
        api_version: v1
        name: web-server
        namespace: "{{ oc_project_prefix }}-{{ env }}-{{ oc_project_suffix }}"
        definition: "{{ lookup('template', 'dc.yml') | from_yaml }}"
      with_items: "{{ openshift_resources }}"
      loop_control:
        loop_var: oc_object
# I USED THIS AS WORKAROUND: (uncomment it to test)
#    - name: Create SLA pods through deploymentConfig
#      oc:
#        state: present
#        host: "{{ openshift_host }}"
#        port: "{{ openshift_port }}"
#        token: "{{ openshift_token }}"
#        validate_certs: "{{ openshift_validate_certs }}"
#        inline: "{{ lookup('template', 'dc.yml') | from_yaml }}"
#      register: openshift_dc_creation
#      with_items: "{{ openshift_resources }}"
#      loop_control:
#        loop_var: oc_object
```

oc_vars.yml:
```
---
env: lab
oc_project_prefix: company
oc_project_desc: "A good description for a project !"
oc_project_suffix: "example"
oc_project_display_name: "Project Created by Ansible"
openshift_host: "insert_your_url_here"
openshift_port: 443
openshift_validate_certs: no
openshift_token: "insert_your_token_here"
openshift_resources:
    - sla_pod_name: "platform-checks-web-srv1"
      sla_container_name: "pltfrm-cks-srv1" ### NB: Container Name limited to 15 characters
      sla_svc_name: "svc-platform-checks-web-srv1"
      sla_route_name: "route-platform-checks-web-srv1"
      sla_route_path: "platform-checks-web-srv1.route.dom"
      sla_dc_name: "platform-checks-web-srv1" ### IMPORTANT NOTE: when you deploy pods through deploymentConfig, it seems that pods take name of its own dc.
      sla_docker_image: "docker.io/httpd:latest"
      sla_replicas_number: 2
      sla_port_name: "web-http"
      sla_port_protocol: "TCP"
      sla_port_number: "8080"
      sla_cpu_limits: 200m
      sla_cpu_requests: 0
      sla_mem_limits: 256Mi
      sla_mem_requests: 256Mi

    - sla_pod_name: "platform-checks-web-srv2"
      sla_container_name: "pltfrm-cks-srv2"
      sla_svc_name: "svc-platform-checks-web-srv2"
      sla_route_name: "route-platform-checks-web-srv2"
      sla_route_path: "platform-checks-web-srv2.route.dom"
      sla_dc_name: "platform-checks-web-srv2"
      sla_docker_image: "docker.io/httpd:latest"
      sla_replicas_number: 2
      sla_port_name: "web-http"
      sla_port_protocol: "TCP"
      sla_port_number: "8080"
      sla_cpu_limits: 200m
      sla_cpu_requests: 0
      sla_mem_limits: 256Mi
      sla_mem_requests: 256Mi

## The following variable identify deployed resources via Ansible. I use a common label
### for associated pod,svc,route. Easier to handle resource in each project
label_id_resource: ansible-test
```

dc.yml:
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: {{oc_object.sla_dc_name}}
  namespace: {{oc_project_prefix}}-{{env}}-{{ oc_project_suffix }}
  labels:
    app: {{ oc_object.sla_pod_name }}
    resourcePurpose: {{label_id_resource}}
spec:
  replicas: {{oc_object.sla_replicas_number}}
  selector:
    deploymentConfig: {{oc_object.sla_dc_name}}
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{oc_object.sla_pod_name}}
      labels:
        app: {{ oc_object.sla_pod_name }}
        deploymentConfig: {{oc_object.sla_dc_name}}
        resourcePurpose: {{label_id_resource}}
    spec:
      containers:
      - name: {{oc_object.sla_container_name}}
        image: {{oc_object.sla_docker_image}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{oc_object.sla_cpu_limits}}
            memory: {{oc_object.sla_mem_limits}}
          requests:
            cpu: {{oc_object.sla_cpu_requests}}
            memory: {{oc_object.sla_mem_requests}}
        ports:
          - name: {{oc_object.sla_port_name}}
            containerPort: {{oc_object.sla_port_number}}
            protocol: {{oc_object.sla_port_protocol}}
        command:
          - run
      readinessProbe:
          httpGet:
            path: /
            port: {{oc_object.sla_port_number}}
            scheme: HTTP
          initialDelaySeconds: 3
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 5
      livenessProbe:
          httpGet:
            path: /
            port: {{oc_object.sla_port_number}}
            scheme: HTTP
          initialDelaySeconds: 15
          failureThreshold: 1
          periodSeconds: 20
      dnsPolicy: ClusterFirst
  triggers:
  - type: ConfigChange
```

**Comment by DAgostinoLucas** [comment]
@fabianvf any news concerning this issue?

**Comment by DAgostinoLucas** [comment]
@fabianvf I finally resolved that issue myself with help of some colleagues. According to [k8s documentation](https://docs.ansible.com/ansible/latest/modules/k8s_module.html), it uses by default v1 as api_version.

In recent Openshift releases this is no more the case, it needs to use `apis.openshift.io/v1` as api_version.

I think that [link](https://docs.openshift.com/container-platform/3.11/rest_api/apis-apps.openshift.io/v1.DeploymentConfig.html#Post-apis-apps.openshift.io-v1-namespaces-namespace-deploymentconfigs) is should be documented in k8s module documentation, isn't it?

Solution:

```
   - name: Create pods through deploymentConfig
      k8s:
        state: present
        kind: DeploymentConfig
        api_version: "apis.openshift.io/v1"
        name: web-server
        namespace: "{{ oc_project_prefix }}-{{ env }}-{{ oc_project_suffix }}"
        definition: "{{ lookup('template', 'dc.yml') | from_yaml }}"
```
