### ISSUE TITLE
ios_user take more than one ssh key

### ISSUE THREAD

**Issue by ericx** [ansible/ansible#50879]
##### SUMMARY

Allow submission of more than one ssh key per user.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ios_user

##### ADDITIONAL INFORMATION

Each workstation for a user should have a separate ssh key in order to allow revocation in the event of the machine's loss or compromise. Unfortunately standard IOS only allows a maximum of 2 keys, nonetheless, the ios_user module only allows a single key.

```yaml
- name: create a new user
  ios_user:
    name: ansible
    nopassword: True
    sshkey: 
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', '~/.ssh/id_dsa.pub') }}"
    state: present
```
