### ISSUE TITLE
ios_users parameter password_hashed

### ISSUE THREAD

**Issue by ericx** [ansible/ansible#50880]
##### SUMMARY
Allow use of hashed passwords when creating users.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_user

##### ADDITIONAL INFORMATION

Currently IOS_user requires that a password be provided in clear-text. This is problematic because those clear-text passwords need to be stored somewhere available for the script. Instead, hash strings (e.g. "5 $1$5wiD$8Ss.VaErWyarnyTkDv8Bm.") can be safely embedded in group_vars/all.yml

```yaml
- name: Change Password for User netop
  ios_user:
    name: netop
    hashed_password:  "5 $1$5wiD$8Ss.VaErWyarnyTkDv8Bm."
    update_password: always
    state: present
```

It's entirely possible that this will already work with `configured_password`, but if so, the documentation does not express that possibility.
