### ISSUE TITLE
Ansible NIOS Module Failure

### ISSUE THREAD

**Issue by CSimpiFoN** [ansible/ansible#50881]
##### SUMMARY
Module fails during record creation to Infoblox

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_host_record

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/csimpifon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
No change
```

##### OS / ENVIRONMENT
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
```
##### STEPS TO REPRODUCE

Create a playbook to add Infoblox DNS records
Try to run it

```yaml
---
- name: Install Dependencies (Infoblox Python Module - infoblox-client)
  pip:
    name: infoblox-client
  delegate_to: localhost
  become: True
  run_once: True

- name: Add Host Record
  nios_host_record:
    name: "{{ inventory_hostname }}"
    ipv4:
      - address: "{{ ip }}"
    state: present
    provider:
      host: "{{ infoblox }}"
      username: "{{ infoblox_user }}"
      password: "{{ infoblox_password }}"
  connection: local
```

##### EXPECTED RESULTS

A host record to be created in Infoblox

##### ACTUAL RESULTS

Fatal error dropped by Ansible

```paste below
PLAY [all] **************************************************************************************************************************

TASK [AddInfobloxRecord : Install Dependencies (Infoblox Python Module - infoblox-client)] ******************************************
ok: [server.test.com -> localhost]

TASK [AddInfobloxRecord : Add Host Record] ******************************************************************************************
fatal: [server.test.com]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"infoblox_client.connector\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_t7DzmQ/ansible_module_nios_host_record.py\", line 219, in <module>\n    main()\n  File \"/tmp/ansible_t7DzmQ/ansible_module_nios_host_record.py\", line 213, in main\n    result = wapi.run(NIOS_HOST_RECORD, ib_spec)\n  File \"/tmp/ansible_t7DzmQ/ansible_modlib.zip/ansible/module_utils/net_tools/nios/api.py\", line 240, in run\n  File \"/tmp/ansible_t7DzmQ/ansible_modlib.zip/ansible/module_utils/net_tools/nios/api.py\", line 145, in _invoke_method\n  File \"/tmp/ansible_t7DzmQ/ansible_modlib.zip/ansible/module_utils/net_tools/nios/api.py\", line 181, in handle_exception\nTypeError: argument of type 'NoneType' is not iterable\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/user/add-infoblox-record/AddInfobloxRecord.retry

PLAY RECAP **************************************************************************************************************************
server.test.com : ok=1    changed=0    unreachable=0    failed=1
```
