### ISSUE TITLE
Invalid input when management interface starts with upper case letter

### ISSUE THREAD

**Issue by gravitypaint** [ansible/ansible#50890]
##### SUMMARY
When we upgraded ansible from 2.5.6 to 2.7.5 our host variables for management interfaces on switches stopped working as expected
If the management interface name started with a capital the job would fail with the following error 

```"msg": "Invalid input (at token 1: 'forwarding')"```

where forwarding precedes a variable in a jinja2 template file. 

When we changed the management interface name to start with a lower case letter, the job ran successfully.

Has anyone else seen this issue? Is there a way this can be resolved without changing the capitalisation on all our management interface host vars?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
This could be related to eos_config, but unsure

##### ANSIBLE VERSION

```
ansible --version
ansible 2.7.5
 config file = /etc/ansible/ansible.cfg
 configured module search path = [u’/var/lib/awx/.ansible/plugins/modules’, u’/usr/share/ansible/plugins/modules’]
 ansible python module location = /usr/lib/python2.7/site-packages/ansible
 executable location = /usr/bin/ansible
 python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### OS / ENVIRONMENT
Arista switches

##### STEPS TO REPRODUCE
This role runs by using the template module and a jinja2 template, to generate configuration which is then deployed using eos_config. The template uses variables from host vars

```yaml

#Host vars used by jinja2 templates
# this fails
management:
   interface: Management1
   address: 1.1.1.1/24

# this works
management:
   interface: management1
   address: 1.1.1.1/24
 
#section of template
{% if management.address is defined %}
interface {{ management.interface }}
  vrf forwarding {{ mgmt_vrf }}
  ip address {{ management.address }}
{% endif %}
{% if management.additional_interfaces is defined %}
  {% for additional_interface in management.additional_interfaces %}
!
interface {{ additional_interface.name }}
  vrf forwarding {{ mgmt_vrf }}
  ip address {{ additional_interface.address }}
  {% endfor %}
{% endif %}
!

#tasks
- name: Generate management configurations
  template:
    src: "management.j2"
    dest: "{{ conf_dir}}/01_management.conf"
  check_mode: "no"
  changed_when: false
- name: Partial deploy Assemble all the configuration bits
  assemble:
    src: "{{ conf_dir }}/"
    dest: "{{ conf_dir }}/assembled.conf"
  check_mode: no
  changed_when: False

- name: Partial deploy Sanitize config file
  shell: "cat {{ conf_dir }}/assembled.conf | egrep -v '(!)|(^\\s*$)' > {{ conf_dir }}/sanitized.conf"
  check_mode: "False"
  changed_when: False
  failed_when: False

- stat:
    path: "{{ conf_dir }}/sanitized.conf"
  register: st

- debug:
    msg: "No changes to apply"
  when: st.stat.size == 0

- meta: end_play
  when: st.stat.size == 0

- name: Partial deploy Show configuration changes.
  vars:
    file_name: "{{ conf_dir}}/sanitized.conf"
  eos_config:
    provider: "{{ eos_provider }}"
    lines: "{{ lookup('file', file_name) }}"
    backup: "no"
    replace: "{{ replace }}"
    diff_against: session
    save_when: never
  check_mode: "yes"
  register: result
  changed_when: result.diff is defined and result.diff.prepared != "\n"

- debug:
    var: result.diff

- name: Partial deploy Give time to cancel changes.
  pause:
    minutes: 1
  when: not ansible_check_mode and result.diff.prepared != "\n"

- name: Partial deploy Apply configuration changes.
  vars:
    file_name: "{{ conf_dir}}/sanitized.conf"
  eos_config:
    provider: "{{ eos_provider }}"
    lines: "{{ lookup('file', file_name) }} "
    backup: "no"
    replace: "{{ replace }}"
    diff_against: session
    save_when: modified
  when: not ansible_check_mode and result.diff.prepared != "\n"
  changed_when: false

   
```

##### EXPECTED RESULTS
Playbook should run succesfully

##### ACTUAL RESULTS

```
TASK [deploy : Show configuration changes.] ************************************
13:10:05
fatal: [switch.domain.com]: FAILED! => {"changed": false, "code": 1002, "msg": "Invalid input (at token 1: 'forwarding')"}

```
Note, if the fowarding line of the template is commented out, it then fails on address. If both are commented out it does not fail.
