### ISSUE TITLE
cli_config module fails on eos while taking config backup

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#50925]
##### SUMMARY

If backup option is only set to true without `config` the task run fails with below error.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.7
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: take config backup
  cli_config:
    backup: yes
  become: yes
  register: result
```

##### EXPECTED RESULTS

Backup file should be created on disk

##### ACTUAL RESULTS

Fails with error:

```paste below
TASK [eos_config : take config backup] ***********************************************************************************************************
fatal: [eos02]: FAILED! => {"changed": false, "msg": "None\r\n% Invalid input\r\nveos02(config-s-ansibl)#"}
```
