### ISSUE TITLE
Derived boolean variables are stored as strings

### ISSUE THREAD

**Issue by progre55** [ansible/ansible#5094]
Here is an example:

``` yaml
- hosts: 127.0.0.1

  vars:
    myvar: '{{ "foo" == "bar" }}'

  tasks:
    - name: print var value
      local_action: command /bin/echo myvar is {{ myvar }}

    - name: this should run
      local_action: command /bin/echo whatever
      when: not myvar

    - name: this should not run
      local_action: command /bin/echo whatever
      when: myvar
```

This prints:

```
"stdout": "myvar is False"
```

for the first task, and **skips** the other two tasks.

This behavior has broken a bunch of tasks for us.
In order to make sure it works correctly, you have to append the variable _myvar_ with **|bool**:

``` yaml
- hosts: 127.0.0.1

  vars:
    myvar: '{{ "foo" == "bar" }}'

  tasks:
    - name: print var value
      local_action: command /bin/echo myvar is {{ myvar }}

    - name: this should run
      local_action: command /bin/echo whatever
      when: not myvar|bool

    - name: this should not run
      local_action: command /bin/echo whatever
      when: myvar|bool
```
