### ISSUE TITLE
docker_container:  Error creating container: 400 Client Error: Bad Request ("No command specified")

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#50951]
##### SUMMARY
docker_container module fail with fedora images when command is not mentioned, giving a:
```
 Error creating container: 400 Client Error: Bad Request ("No command specified")
```

Same does not happen with other images like 'centos:7' and I was not able to replicate the problem using the images without ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_PIPELINING(/Users/ssbarnea/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/ssbarnea/.ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=false -F /dev/null
DEFAULT_CALLBACK_WHITELIST(env: ANSIBLE_CALLBACK_WHITELIST) = [u'timer', u'profile_roles', u'profile_tasks']
DEFAULT_FORKS(/Users/ssbarnea/.ansible.cfg) = 500
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/Users/ssbarnea/rdo/harem/hosts.ini']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_TIMEOUT(/Users/ssbarnea/.ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/ssbarnea/.vault_pass.txt
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 0
HOST_KEY_CHECKING(/Users/ssbarnea/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/ssbarnea/.ansible.cfg) = False
SHOW_CUSTOM_STATS(/Users/ssbarnea/.ansible.cfg) = True
```

##### OS / ENVIRONMENT
Any: Confirmed on MacOS and Linux (CentOS) systems.

##### STEPS TO REPRODUCE

```yaml
#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: no
  tasks:
    - docker_container:
        name: test
        hostname: test
        # image: "centos:7"
        image: "fedora:28"
        debug: true
        # command: echo
        # ^ uncomment to make it work!
```

##### EXPECTED RESULTS

Succesfull execution of container with all images, even when command is null!

##### ACTUAL RESULTS

```paste below
Error creating container: 400 Client Error: Bad Request ("No command specified")
```
