### ISSUE TITLE
Re-run failed tasks after rescue

### ISSUE THREAD

**Issue by cfiske** [ansible/ansible#50956]
##### SUMMARY
If a rescue is triggered (and executes successfully), the block/task it was rescuing should be able to be re-executed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Ansible Block/Rescue

##### ADDITIONAL INFORMATION
It would be nice to have an option to retry the block after rescue so we avoid coping the block tasks into the rescue section (DRY).

Note that this is distinct from e.g. #8896. Using `retries` and `until` doesn't allow me to run a rescue task in between to clean up the mess.

```yaml
- name: ensure symlink exists
  block:
    file:
      path: /my/symlink
      src: /my/actual/dir
      state: link
      force: yes
  rescue:
  - name: fix it up
    file:
      path: /my/symlink
      state: absent
    redo_task: yes
```

I can't make `file` replace a (non-empty) directory even with `force` so I need the extra step. But if it's already a symlink I don't want to remove it and recreate it.

This seems like it would be a cleaner approach than:

- Having a separate `stat` task or similar just to check for this condition
- Always running the repair task in advance, even if it's not needed

Even beyond this specific use case it seems more natural to be able to have your playbook act on expected/normal conditions and use `rescue` to clean up corner cases (without duplicating block tasks in `rescue`). Otherwise you have to have what amounts to a pre-task to check for corner cases in advance and repair them, which seems inefficient to me.

In my example `redo_task` could be named/placed however is appropriate for `block`/`rescue` syntax but you get the idea.
