### ISSUE TITLE
URI Module is malforming JSON bodies with PEM formatted PKI 

### ISSUE THREAD

**Issue by danmanners** [ansible/ansible#50963]
##### SUMMARY

I'm attempting to use the URI module, as I have many times before, to post JSON to one of my Hashicorp Vault instances. It appears as though the URI module is now sending malformed data and is manipulating it somehow before it is sent. If I send the same JSON blob from curl (shown below), it works just fine.

Experiencing this issue in multiple versions of ansible and on multiple operating systems.

What I am unsure about is why some URI POST's work and others do not.

I can definitely provide any other details requested/required.

Thank you!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

URI

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = None
  configured module search path = ['/Users/danmanners/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Jan 13 2019, 12:50:01) [Clang 10.0.0 (clang-1000.11.45.5)]

ansible 2.7.0
  config file = None
  configured module search path = [u'/home/danmanners/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MacOS
##### STEPS TO REPRODUCE

```yaml
# This command generates output fine.
- name: Generating Customer CSR
  uri:
      url: "{{ vault }}/v1/{{ domain|lower }}-default-ca/intermediate/generate/exported"
      method: PUT
      body: '{"common_name":"{{ domain|lower }}.example.io","alt_names":"{{ domain|lower }}.example.com,{{ domain|lower }}.example.net", "ttl":"8760h", "key_bits":4096}'
      status_code: 200,307
      body_format: json
      headers:
          X-Vault-Token: "{{ vault_root_token }}"
      return_content: yes
  register: unsignedcsr

# URI module appears to be broken currently.
# The following 2 commands work
- name: Signing CSR with Root CA - Shell
  shell: "curl -XPOST -H 'X-Vault-Token: {{ vault_root_token }}' --data '{\"csr\":\"{{ unsignedcsr.json.data.csr|replace('\n','\\n') }}\",\"use_csr_values\":true }' {{vault}}/v1/root_ca/root/sign-intermediate "
  register: signedcsr_shell

- name: Setting Signed CSR for Customer.
  vars:
    signedcsr: "{{ signedcsr_shell.stdout | from_json }}"
  uri:
      url: "{{ vault }}/v1/{{ domain|lower }}-default-ca/intermediate/set-signed"
      method: POST
      body: "{\"certificate\":\"{{ signedcsr.data.certificate|replace('\n','\\n') }}\"}"
      status_code: 204,307
      body_format: json
      headers:
          X-Vault-Token: "{{ vault_root_token }}"
      return_content: yes

# The command below does not work. URI Module.
- name: Signing CSR with Root CA
  uri:
      url: "{{ vault }}/v1/root_ca/root/sign-intermediate)"
      method: POST
      body: "{\"csr\":\"{{ unsignedcsr.json.data.csr|replace('\n','\\n') }}\",\"use_csr_values\":true}"
      status_code: 200,307
      body_format: json
      headers:
          X-Vault-Token: "{{ vault_root_token }}"
      return_content: yes
  register: signedcsr
```

##### EXPECTED RESULTS

Status 204: OK

##### ACTUAL RESULTS

Vault does not receive the JSON body correctly and cannot parse it; responds as though it's an unsupported path. However, if the SAME body is copy/pasted like in the shell command, it works just fine.

```paste below
fatal: [X.X.X.61]: FAILED! => {
    "cache_control": "no-store",
    "changed": false,
    "connection": "close",
    "content": "{\"errors\":[\"1 error occurred:\\n\\t* unsupported path\\n\\n\"]}\n",
    "content_length": "59",
    "content_type": "application/json",
    "date": "Wed, 16 Jan 2019 03:59:47 GMT",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": {
                "csr": "-----BEGIN CERTIFICATE REQUEST-----\nMIIE...REDACTED...\n2Hx6tQ==\n-----END CERTIFICATE REQUEST-----",
                "use_csr_values": true
            },
            "body_format": "json",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Content-Type": "application/json",
                "X-Vault-Token": "FAKETOKENHERE"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "200",
                "307"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "http://vault:8200/v1/root_ca/root/sign-intermediate)",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "json": {
        "errors": [
            "1 error occurred:\n\t* unsupported path\n\n"
        ]
    },
    "msg": "Status code was 404 and not [200, 307]: HTTP Error 404: Not Found",
    "redirected": false,
    "status": 404,
    "url": "http://vault:8200/v1/root_ca/root/sign-intermediate)"
}
```

**Comment by ansibot** [comment]
cc @romeotheriault
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Instead of trying to build JSON data in the `body` try just passing a YAML hash/dict to `body`:

```
# The command below does not work. URI Module.
- name: Signing CSR with Root CA
  uri:
      url: "{{ vault }}/v1/root_ca/root/sign-intermediate)"
      method: POST
      body:
        csr: "{{ unsignedcsr.json.data.csr }}"
        use_csr_values: true
      status_code: 200,307
      body_format: json
      headers:
          X-Vault-Token: "{{ vault_root_token }}"
      return_content: yes
  register: signedcsr
```

`body_format: json` will then tell ansible to JSON serialize the body before sending to the API.

needs_info
