### ISSUE TITLE
redfish_facts fails on GetSystemInventory

### ISSUE THREAD

**Issue by frsauvage** [ansible/ansible#50969]
##### SUMMARY
In redfish_facts, the Systems command GetSystemInventory fails on a Ubuntu 18, as it seems that the port (or the http protocol) is not expected ?
Is it possible to force redfish_facts through **http** ??

-     A proxy is defined (through no_proxy in my case,  http_proxy and https_proxy environment variable in my case)
-     The target url is NOT secure i.e. uses http://
-     NO Certificate validation is active (which it is by default)

Same target url with "**uri**" ansible command works (with http protocol and force_basic_auth=True)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
redfish_facts
command: all

##### ANSIBLE VERSION
latest 
![image](https://user-images.githubusercontent.com/23147820/51233706-deff1e80-196a-11e9-8f48-ab17c15b35de.png)

##### CONFIGURATION
hosts
![image](https://user-images.githubusercontent.com/23147820/51233896-719fbd80-196b-11e9-9821-904a4ff9f02c.png)

get_system_inventory.yml playbook file
![image](https://user-images.githubusercontent.com/23147820/51233941-9b58e480-196b-11e9-8491-8eabc51838c9.png)

##### OS / ENVIRONMENT
![image](https://user-images.githubusercontent.com/23147820/51234086-05718980-196c-11e9-89da-5cd6ee481683.png)
NO_PROXY=localhost,127.0.0.1,172.31.xx.0/24

##### STEPS TO REPRODUCE
1. cd /etc/ansible directory, I added hosts and playbook files.
2. type
> ansible-playbook get_system_inventory.yml

```yaml
---
- hosts: OpenBMC
  connection: local
  name: Systems Inventory
  gather_facts: False
 
  tasks:
  - name: Getting system inventory
    redfish_facts:
      category: Systems
      baseuri: "http://172.31.60.18"
      user: "{{user}}"
      password: "{{password}}"
    failed_when: false
    register: result

```
##### EXPECTED RESULTS
get the Systems inventory

##### ACTUAL RESULTS
{
    "changed": false,
    "failed": false,
    "failed_when_result": false,
    "msg": "URL Error: [Errno -3] Temporary failure in name resolution"
}
'
