### ISSUE TITLE
Debug module may convert variable, making it's output unreliable when checking the type of the variable.

### ISSUE THREAD

**Issue by bzakdd** [ansible/ansible#50976]
##### SUMMARY
Debug module can implicitly convert it's variables making it hard to use it for debugging.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Debug module

##### ANSIBLE VERSION
```paste below
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home2/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
`No changes`
##### OS / ENVIRONMENT
Irrelevant

##### STEPS TO REPRODUCE
Take following playbook and run it:
```yaml
  - hosts: all
    gather_facts: no
    tasks:
      - set_fact:
         some_list: "['ala']"

      - debug:
          var=some_list

      - debug:
          msg="{{ some_list | list}}"

```

##### EXPECTED RESULTS

Debug module in the second task displays `some_list` as a string object.

##### ACTUAL RESULTS

Debug module in the second task displays `some_list` as a list, confusing readers into thinking that they can operate on it as a list.

```
PLAY [all] *********************************************************************

TASK [set_fact] ****************************************************************
ok: [localhost] => {"ansible_facts": {"some_list": "['ala']"}, "changed": false}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "some_list": [
        "ala"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": [
        "[", 
        "'", 
        "a", 
        "l", 
        "a", 
        "'", 
        "]"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0 
```

##### MORE INFO
Example shown above is simple and innocent, you can clearly see what's going on. In my case variable was defined somewhere else and we didn't access the list directly but we tried to intersect it.
**TL DR** it looked like this:
```yaml
  - hosts: all
    gather_facts: no
    tasks:
      - set_fact:
         some_list: "['abc']"

####
#### SOME CODE HERE
####

      - debug:
          var=some_list

#### We see that `some_list` is a list with `abc` as an element

      - debug:
          msg="{{ some_list | intersect(['abc'])}}"

#### We try to intersect it with list that holds `abc` but this returns empty list
```

and resulted with this
```
PLAY [all] *********************************************************************

TASK [set_fact] ****************************************************************
ok: [localhost] => {"ansible_facts": {"some_list": "['abc']"}, "changed": false}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "some_list": [
        "abc"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": []
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
what was extremely puzzling.
