### ISSUE TITLE
gce: Add autoheal functionality

### ISSUE THREAD

**Issue by kloeffler** [ansible/ansible#50972]
##### SUMMARY
Improve managed instance group creation in google cloud by adding autoheal functionality.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gce_mig

##### ADDITIONAL INFORMATION
Currently if you define managed instance groups in the google cloud, it offers autoheal which will be used to replace instances in that group that fail the health check (repeatedly).
This is possible bei gcloud compute beta command.

gcloud command:
```
gcloud beta compute instance-groups managed set-autohealing [INSTANCE_GROUP] \
    --health-check example-check \
    --initial-delay 120 \
    --zone [ZONE]

```

Possible extension  to the module:
```
- name: Create MIG with autoheal
  gce_mig:
    name: ansible-mig-example
    zone: us-central1-c
    state: present
    size: 1
    template: my-instance-template-1
    autoheal:
      enabled: yes 
      policy:
        health-check-type: https-health-check
        health-check-name: example-check
        initial-delay: 120


```
