### ISSUE TITLE
gce_mig string to int in cool_down_period fails

### ISSUE THREAD

**Issue by kloeffler** [ansible/ansible#50970]
##### SUMMARY
When using variables for setting the numbers for cool_down_period, min_instances and max_instances you get a type error "msg": "cool_down_period must be of type: <type 'int'>".
Not using variables but the actual numbers will result in proper creation of the managed instance group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gce_mig

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kloeffler/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
empty output
```

##### OS / ENVIRONMENT
Running from Debian 9.6 against google cloud.

##### STEPS TO REPRODUCE
vars/main.yml
```
---
env: "sbx"
zone: "europe-west3-a"
project_id: "myproject"

ig_dynamic:
  - name: "{{env}}-app"
    base_instance_name: "{{env}}-app"
    sm_zones: "single"
    target_size: 1
    min_instances: 1
    max_instances: 2
    cool_down: 60
    type: "app"
    cpu_utilization: .6
```
tasks/main.yml
```
---
- name: Create managed instance group {{env}}-app with autoscaler
  gce_mig:
    name: "{{item.name}}"
    zone: "{{zone}}" 
    state: present
    size: "{{item.target_size}}"
    template: "sbx-app-europe-west3-1" 
    recreate_instances: yes 
    project_id: "{{project_id}}"
    autoscaling:
      enabled: yes 
      name: "{{item.name}}-autoscaler" 
      policy:
        min_instances: "{{item.min_instances}}"
        max_instances: "{{item.max_instances}}"
        cool_down_period: "{{item.cool_down|int}}" 
        cpu_utilization: 
          target: "{{ item.cpu_utilization }}"
    service_account_email: "{{service_account_email}}"
    credentials_file: "{{ credentials_file }}"
  when: item.type == 'app'
  loop: "{{ ig_dynamic | list }}"
```

##### EXPECTED RESULTS
Expected the values I defined in my vars to be used resulting in the creation of the managed instance group.

##### ACTUAL RESULTS
```
failed: [localhost] (item={u'cpu_utilization': 0.6, u'name': u'test-app', u'min_instances': 1, u'max_instances': 2, u'cool_down': 60, u'base_instance_name': u'sbx-app', u'target_size': 1,  u'sm_zones': u'single', u'type': u'app'}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "autoscaling": {
                "enabled": true, 
                "name": "sbx-app-autoscaler", 
                "policy": {
                    "cool_down_period": "60", 
                    "cpu_utilization": {
                        "target": "0.6"
                    }, 
                    "max_instances": "2", 
                    "min_instances": "1"
                }
            }, 
            "credentials_file": "/home/kloeffler/infra_setup/SOMETHING.json", 
            "name": "sbx-app", 
            "named_ports": null, 
            "pem_file": null, 
            "project_id": "myproject", 
            "recreate_instances": true, 
            "service_account_email": "email@myproject.iam.gserviceaccount.com", 
            "service_account_permissions": null, 
            "size": 1, 
            "state": "present", 
            "template": "sbx-app-europe-west3-1", 
            "zone": "europe-west3-a"
        }
    }, 
    "item": {
        "base_instance_name": "sbx-app", 
        "cool_down": 60, 
        "cpu_utilization": 0.6, 
        "max_instances": 2, 
        "min_instances": 1, 
        "name": "sbx-app", 
        "sm_zones": "single", 
        "target_size": 1, 
        "type": "app"
    }, 
    "msg": "max_instances must be of type: <type 'int'>"
}
```
