### ISSUE TITLE
vmware_vmkernel module does not query vCenter for possible dvPortgroups 

### ISSUE THREAD

**Issue by kendrew71** [ansible/ansible#50989]
##### SUMMARY
The vmware_vmkernel module does not query vCenter for possible dvPortgroups when validating the given portgroup name for the vmk, it only queries the ESXi host. The need to query vCenter arises because, even though a host has been added to a dvSwitch which has the given dvPortgroup, that portgroup does not seem to actually "show up" (?) on the ESXi host until it is used. If you create a vmk via the host web client, you also will not see that portgroup, but if you use the vCenter web client you can add a vmk to the desired portgroup. (This may be related to #43351, but it seems different.)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vmkernel.py

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
```
no output
```

##### OS / ENVIRONMENT
RedHat 7.4
Ansible 2.7.5
pyvmomi 6.7
vSphere 6.7u1

##### STEPS TO REPRODUCE
These are the steps I followed..
1.. create dvSwitch (vmware_dvswitch)
2.. add host to dvSwitch (vmware_dvs_host)
3.. add dvPortgroups to dvSwitch (vmware_dvs_portgroup)
4.. add vmk with new dvPortgroup (vmware_vmkernel)

```
  - name: create dvSwitches
    vmware_dvswitch:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      datacenter_name: "{{ location }}_Datacenter"
      switch_name: "{{ item.key }}_dvSwitch"
      mtu: 1500
      uplink_quantity: 2
      discovery_proto: cdp
      discovery_operation: listen
    delegate_to: 127.0.0.1
    loop: "{{ lookup('dict', switches[model]) }}"

  - name: add Hosts and Uplinks to dvSwitches
    vmware_dvs_host:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      esxi_hostname: "{{ item[1] }}"
      validate_certs: no
      switch_name: "{{ item[0].key }}_dvSwitch"
      vmnics:
        - "{{ item[0].value.uplink1 }}"
        - "{{ item[0].value.uplink2 }}"
    delegate_to: 127.0.0.1
    with_nested:
      - "{{ lookup('dict', switches[model]) }}"
      - "{{ esxiCluster }}"

  - name: create vmk Portgroups
    vmware_dvs_portgroup:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      portgroup_name: "{{ item.key }}_dvPortGroup"
      switch_name: "{{ item.value[model] }}_dvSwitch"
      num_ports: 4
      vlan_id: "{{ item.value.vlan }}"
      portgroup_type: earlyBinding
      state: present
    delegate_to: 127.0.0.1
    loop: "{{ lookup('dict', portgroups) }}"

  - name: create/update vmk Interfaces
    vmware_vmkernel:
      hostname: "{{ inventory_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      esxi_hostname: "{{ item[1] }}"
      portgroup_name: "{{ item[0].value.pg }}_dvPortGroup"
      network:
        type: 'static'
        ip_address: "{{ item[1].split('.')[0] }}.{{ item[1].split('.')[1] }}.{{ item[0].value.sn }}.{{ item[1].split('.')[3] }}"
        subnet_mask: "{{ item[0].value.mask }}"
      enable_mgmt: "{{ item[0].value.mgmt }}"
      enable_vsan: "{{ item[0].value.vsan }}"
      enable_vmotion: "{{ item[0].value.vmotion }}"
      enable_ft: "{{ item[0].value.ft }}"
    delegate_to: 127.0.0.1
    with_nested:
      - "{{ lookup('dict', vmkernel) }}"
      - "{{ esxiCluster }}"
```

##### EXPECTED RESULTS
Expected vmk to be added on host into dvPortgroup.

##### ACTUAL RESULTS
The vmk is not added and fails with portgroup not found.

Output for one vmk on one host.. it is repeated for all others.
```
fatal: [vcsa.***** -> 127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "enable_ft": false,
            "enable_mgmt": false,
            "enable_vmotion": false,
            "enable_vsan": true,
            "esxi_hostname": "aa.bb.c0.dd",
            "hostname": "vcsa.*****",
            "ip_address": null,
            "mtu": 1500,
            "network": {
                "ip_address": "aa.bb.c1.dd",
                "subnet_mask": "255.255.255.0",
                "type": "static"
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "portgroup_name": "vSAN_dvPortGroup",
            "state": "present",
            "subnet_mask": null,
            "username": "administrator@vsphere.local",
            "validate_certs": false,
            "vlan_id": null,
            "vswitch_name": null
        }
    },
    "msg": "Portgroup name vSAN_dvPortGroup not found"
}
```
