### ISSUE TITLE
VMware: request support applying OS customization to existing VM

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#51010]
##### SUMMARY

vmware_guest can only be used for clone a new VM from template/existing VM and apply existing customization specification to the cloned VM. We want to create a new customization spec firstly, and then apply this spec to the existing VM to customize the Guest OS.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest_customization
##### ADDITIONAL INFORMATION

(1) can used to create new customization specifications for Linux or Windows guest OS.
(2) apply created customization spec to existing virtual machine to customize guest OS.

```yaml
e.g., 
customize_spec: new
customize_spec_name: win_spec_test
customize_spec_org: gosc_test
customize_spec_os: windows
.... (parameters required to create a windows customize spec)
```
