### ISSUE TITLE
Missing azure_rm_subnet_facts module

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ansible/ansible#51021]
##### SUMMARY
Like azure_rm_virtualnetwork_facts, azure_rm_networkinterface_facts, etc.. this module will ask Azure for details about the underlying subnets.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
In #38077 it was noted that while this module does not currently exist, the raw data is in azure_rm_virtualnetwork_facts which can be parsed. It would be nice to have this in it's own module.

```yaml
---
- hosts: localhost
  gather_facts: False
  tasks:
  - azure_rm_subnet_facts:
      resourcegroup: myrg
    register: subnetfact
  - debug: var=subnetfact
```
