### ISSUE TITLE
Handling of list-typed items using with_items regressed.

### ISSUE THREAD

**Issue by pfalcon** [ansible/ansible#5103]
```
$ ansible --version
ansible 1.4
```

Referring to https://coderwall.com/p/uaeeug as first-hand example from Ansible author. Updating listing 3 there to contemporary templating syntax and wrapping into complete playbook, we get list.yaml:

```
- hosts: all
  gather_facts: no
  tasks:
   - name:  template everything for fooserv
     local_action: command echo src={{item.0}} dest={{item.1}}
     with_items:
      - [ 'templates/foo.j2', '/etc/splat/foo.conf' ]
      - [ 'templates/bar.j2', '/etc/splat/bar.conf' ]
```

Running it leads to:

```
$ ansible-playbook list.yml -i "localhost," -v

PLAY [all] ******************************************************************** 

TASK: [template everything for fooserv] *************************************** 
changed: [localhost] => (item=templates/foo.j2) => {"changed": true, "cmd": ["echo", "src=t", "dest=e"], "delta": "0:00:00.001540", "end": "2013-11-29 20:49:53.796507", "item": "templates/foo.j2", "rc": 0, "start": "2013-11-29 20:49:53.794967", "stderr": "", "stdout": "src=t dest=e"}
changed: [localhost] => (item=/etc/splat/foo.conf) => {"changed": true, "cmd": ["echo", "src=/", "dest=e"], "delta": "0:00:00.001982", "end": "2013-11-29 20:49:53.874033", "item": "/etc/splat/foo.conf", "rc": 0, "start": "2013-11-29 20:49:53.872051", "stderr": "", "stdout": "src=/ dest=e"}
changed: [localhost] => (item=templates/bar.j2) => {"changed": true, "cmd": ["echo", "src=t", "dest=e"], "delta": "0:00:00.002631", "end": "2013-11-29 20:49:53.961348", "item": "templates/bar.j2", "rc": 0, "start": "2013-11-29 20:49:53.958717", "stderr": "", "stdout": "src=t dest=e"}
changed: [localhost] => (item=/etc/splat/bar.conf) => {"changed": true, "cmd": ["echo", "src=/", "dest=e"], "delta": "0:00:00.002053", "end": "2013-11-29 20:49:54.034788", "item": "/etc/splat/bar.conf", "rc": 0, "start": "2013-11-29 20:49:54.032735", "stderr": "", "stdout": "src=/ dest=e"}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

As can be seen, loop runs 4 times instead of 2, and {{item.0}} and {{item.1}} gets resolved to characters of first item, then second, then same for then second pair. {{item[0]}} and {{item[1]}} give the same results.

Using dictionaries as individual items works, so there's a workaround, but it's verbose.
