### ISSUE TITLE
Apache2 CustomLog "template error while templating string: Encountered unknown tag"  

### ISSUE THREAD

**Issue by Imagin0s** [ansible/ansible#51058]
##### SUMMARY

"template error while templating string: Encountered unknown tag 'FT'.. String: {\"PROGRAM\":\"a5129_dgs\",\"server_name\":\"%v\",\"remote_ip\":\"%a\",\"timestamp_da\":\"%{%FT%T}t.%{msec_frac}t%{%z}t\",\"request\":\"%U\",\"method\":\"%m\",\"status\":\"%s\",\"response_size_lo\":\"%B\",\"response_time_ms_lo\":\"%{ms}T\"}"}

```
- name: affectation
   set_fact:
     message_format: >
       CustomLog "" {{ MESSAGE_FORMAT[2:-2] | string }}

- name: "Add configuration line"
   lineinfile:
     dest: '/tmp/toto.conf'
     line: "{{ message_format }}"

```

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
ansible 2.1.1.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### ADDITIONAL INFORMATION

I have tried with {% raw %} ... {% endraw %} but it still doesn't work...

Have you got an idea ? Here below is the content of the inputs.json I pass in --extra-vars of my ansible_playbook :
{
"MESSAGE_FORMAT": "{% raw %}\'{"PROGRAM":"a5129_dgs","server_name":"%v","remote_ip":"%a","timestamp_da":"%{%FT%T}t.%{msec_frac}t%{%z}t","request":"%U","method":"%m","status":"%s","response_size_lo":"%B","response_time_ms_lo":"%{ms}T"}\'{% endraw %}"
}
