### ISSUE TITLE
Unable to pass special character as parameter to modules

### ISSUE THREAD

**Issue by iamgini** [ansible/ansible#51053]
##### SUMMARY
I am trying to run some shell commands (using shell module) and I want to pass some commands which contains "{{" as special characters. Since Ansible is using {{ as variable identifier, its causing issue and getting ```{{: template error while templating string: unexpected 'end of template'. String: {{``` error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

shell 

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb  8 2017, 06:57:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
bash: ansible-config: command not found
```

##### OS / ENVIRONMENT

RHEL7

##### STEPS TO REPRODUCE

Just try to run any commands using shell module which contains "{{" in command line
Eg:
```
  - name: Loop through docker list, get only PID and Config.Labels
    shell: "docker inspect -f '{{.State.Pid}} {{.Config.Labels}}' {{ item }} "
    with_items: "448ac0ea319e"
```
here, {{.State.Pid}} and {{.Config.Labels}} are formatting parameters to print only docker pid and labels from docker inspect command.
 

```yaml
  - name: Loop through docker list, get only PID and Config.Labels
    shell: "docker inspect -f '{{.State.Pid}} {{.Config.Labels}}' {{ item }} "
    with_items: "448ac0ea319e"
```

##### EXPECTED RESULTS

It should simply run on target node and provide docker pid and labels from docker inspect command.

##### ACTUAL RESULTS

```paste below
fatal: [node101]: FAILED! => {
    "failed": true
}

MSG:

{{: template error while templating string: unexpected 'end of template'. String: {{

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/shell.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/shell.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

in any case, you just need to use a 'unsafe' variable that will avoid templating:
``` yaml
    - name: Loop through docker list, get only PID and Config.Labels
      shell: "docker inspect -f '{{params}}' {{ item }} "
      with_items: "448ac0ea319e"
      vars:
          params: !unsafe '{{.State.Pid}} {{.Config.Labels}}'
```
Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
