### ISSUE TITLE
Ansible.Basic: "choices" are case-sensitive

### ISSUE THREAD

**Issue by varunchopra** [ansible/ansible#51063]
##### SUMMARY

`-validateset` would accept a list as case-insensitive but `@{ choices = "" }` does not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[Ansible.Basic.cs](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/csharp/Ansible.Basic.cs)

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /workspace/ansible/lib/ansible
  executable location = /workspace/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### STEPS TO REPRODUCE

**Module code**:
Using `Ansible.ModuleUtils.Legacy.psm1`:
```powershell
-validateset "fat12", "fat16", "extended", "huge", "ifs", "fat32"
```
would be case-insensitive, taking `ifs` as well as `IFS` as possible values.

However using `Ansible.Basic.cs`:
```powershell
mbr_type = @{ type = "str"; choices = "fat12", "fat16", "extended", "huge", "ifs", "fat32" }
```
The same logic would throw an error now.

**Test task**:
```yaml
- name: "Create new partition without drive letter and ifs mbr type"
  win_partition:
    disk_number: 1
    partition_size: -1
    mbr_type: IFS
    offline: True
  register: recreate_partition
```

```
TASK [win_partition : Create new partition without drive letter and ifs mbr type] *************************************************************************************
fatal: [win_partition]: FAILED! => {"changed": false, "msg": "value of mbr_type must be one of: fat12, fat16, extended, huge, ifs, fat32, got: IFS"}
```

Changing it to `ifs` would make the error go away.

Not sure if this is intentional or not.
