### ISSUE TITLE
Missing module `vmware_guest_network` to manage NICs

### ISSUE THREAD

**Issue by xenlo** [ansible/ansible#51066]
#### SUMMARY
Even the module `vmware_guest` allows to manage the NIC by providing a list, this has some limitations:
- You can't remove/delete a NIC
- It's really difficult if you only want to add a NIC to an existing VM. 
  1. You first need to call `vmware_guest_fact`, 
  2. Then you need to filter the returned dictionary and proceed in several conversions (as the network description from the output of  `vmware_guest_fact` don't match the intput for `vmware_guest`). 
  3. From there you can append/union the list of current NICs with the list of NIC(s) you want to add
  4. Finally call `vmware_guest` with the list of NICs you just forged
  A example of the tasks needed for this painful process is here under.

Actually it's a bit the same than the new module `vmware_guest_disk` (#36165) but for Network interfaces.

#### ISSUE TYPE
- Missing module to easily manage the NIC interfaces

#### COMPONENT NAME
- `vmware_guest`

##### Workaround to add NICs to an existing VM
Here is the workaround that I found to be able to add some extra NIC to the NAT/jump server VM we have in one of our lab:
```yaml
- name: Get the current status of the NAT/jump server (guest_facts)
  vmware_guest_facts:
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_pass }}"
    name: "{{ jump_host }}"
    datacenter: "{{ datacenter_name }}"
  delegate_to: localhost
  register: jump_guess_facts

- name: Generate the list of existing NIC
  set_fact:
    name: "{{ item.value.summary }}"
    mac: "{{ item.value.macaddress }}"
  loop: "{{ jump_guess_facts.instance | dict2items | selectattr('key', 'match', 'hw_eth') | list }}"
  register: list_current_nics

- name: Create list of NICs that need to be added to the NAT/jump server
  set_fact:
    name: "{{ virtinfra_id }} - vlan{{ vlan.vlan_id }} - {{ vlan.name }}"
    mac: "{{ 'aa:bb:cc:dd:%02d:%02d' | format((vptc_numid |int), (vlan.vlan_id |int)) }}"
  register: list_new_nics
  loop: "{{ infra_ip_vlan_lists }}"
  loop_control:
    loop_var: vlan

- name: Combine the current and the new lists of NICS
  set_fact:
    list_combined_nics: "{{ list_current_nics.results | map(attribute='ansible_facts') | list | union ( list_new_nics.results | map(attribute='ansible_facts') | list ) }}"

- name: Create the new NICs for the NAT/jump server
  vmware_guest:
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_pass }}"
    name: "{{ jump_host }}"
    datacenter: "{{ datacenter_name }}"
    networks:
      "{{ list_combined_nics }}"
    state: present
  delegate_to: localhost
```

It may help other waiting a more comfortable way with a new module.
