### ISSUE TITLE
Allow data_disks list specifies how the data disk should be created. 

### ISSUE THREAD

**Issue by jvalderrama** [ansible/ansible#51062]
##### SUMMARY

The **azure_rm_virtualmachine** module should allows to specifies **how data disks are crated**, due it does not allow to set a custom image for data disks. This possible values could be like terraform does: Attach, FromImage and Empty.
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#create_option

``` 
storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
```
It helps when a custom OS image has multiple data disks and can be changed from Standard to Premium for example.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine

##### ADDITIONAL INFORMATION
When a new virtual machine is going to be created should be specified like:
https://docs.ansible.com/ansible/latest/modules/azure_rm_virtualmachine_module.html 

```
 data_disks:
         - lun: 0
           disk_size_gb: 50
           managed_disk_type: Premium_LRS
           create_option: CUSTOM_IMAGE
         - lun: 1
           disk_size_gb: 30
           managed_disk_type: Premium_LRS
           create_option: CUSTOM_IMAGE
```

```
- name: Create VM Custom data_disks
  azure_rm_virtualmachine:
    name: "{{machine_hostname}}"
    resource_group: "{{worker.dcos.machine.resource_group}}"
    location: "{{worker.dcos.machine.location}}"
    vm_size: "{{worker.dcos.machine.vm_size}}"
    admin_username: "{{worker.dcos.machine.admin_username}}"
    ssh_password_enabled: "{{worker.dcos.machine.ssh_password_enabled}}"
    public_ip_allocation_method: "{{worker.dcos.machine.public_ip_allocation_method}}"
    managed_disk_type: "{{worker.dcos.machine.managed_disk_type}}"
    os_disk_size_gb: "{{worker.dcos.machine.os_disk_size_gb}}"
    network_interface_names:  "{{nic_name}}"
    ssh_public_keys:
    - path: "{{worker.dcos.machine.ssh_public_keys.path}}"
      key_data: "{{worker.dcos.machine.ssh_public_keys.key_data}}"
    image: "{{worker.dcos.machine.image.name}}" Custom image used with multiple data_disks
    data_disks: # Allow to use custom image used for OS disk with multiple data_disks
      "{{worker.dcos.machine.data_disks}}" # Allow to use custom OS disk with multiple_data_disks
    tags:
      "{{worker.dcos.machine.tags}}"

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)
* [test/integration/targets/shadowed_module/library/tags](https://github.com/ansible/ansible/blob/devel/test/integration/targets/shadowed_module/library/tags)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jvalderrama, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@jvalderrama Thanks for your report this issue! Whic ansible you're used? I try to create VM attach data disk and specified the create_option parameter, get success(Ansible version: 2.7.5). It seem meet your minds? if not , please share your question and ansible version? Thanks!
```e.g.
Create Virtual machine yaml
 - name: create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      state: present
      location: "{{ location }}"
      vm_size: Standard_A0
      managed_disk_type: Standard_LRS
      admin_username: azureuser
      admin_password: Password@0329
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
      data_disks:
        - lun: 0
          disk_size_gb: 64
          managed_disk_type: Standard_LRS
          create_option: CUSTOM_IMAGE
    register: output

```
```e.g.
Get Create Virtual machine data disk info:
            "cloud_environment": "AzureCloud", 
            "custom_data": null, 
            "data_disks": [
                {
                    "create_option": "CUSTOM_IMAGE", 
                    "disk_size_gb": 64, 
                    "lun": 0, 
                    "managed_disk_type": "Standard_LRS"
                }
            ], 
            "image": {
                "offer": "UbuntuServer", 
                "publisher": "Canonical", 
                "sku": "16.04-LTS", 
                "version": "16.04.201812230"
            },

**Comment by jvalderrama** [comment]
@Fred-sun , I am using the ansible version 2.7.1 , I set the create_option parameter like you mentioned to create a VM:
``` 
worker:
  dcos:
    nic:
      resource_group: DcosEE-RG
      virtual_network:
        resource_group: eCommerce_RG
        name: VNET_10_251_64_iaas
        subnet_name: VNET_10_251_64_iaas_subnet1
      security_group: DcosEE-NSG
    machine:
      resource_group: DcosEE-RG
      location: westeurope
      vm_size: Standard_E8s_v3
      admin_username: someruser
      ssh_password_enabled: false
      public_ip_allocation_method: Disabled
      managed_disk_type: Premium_LRS
      os_disk_size_gb: 60
      ssh_public_keys:
        path: /home/someuser/.ssh/authorized_keys
        key_data: "ssh-rsa xxxxxx"
      image:
        offer: RHEL
        publisher: RedHat
        sku: '7-RAW'
        version: latest
      data_disks:
         - lun: 0 
           disk_size_gb: 50 
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
         - lun: 1 
           disk_size_gb: 30
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
         - lun: 2
           disk_size_gb: 200
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
         - lun: 3 
           disk_size_gb: 50 
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
         - lun: 4 
           disk_size_gb: 300
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
         - lun: 5 
           disk_size_gb: 50 
           managed_disk_type: Premium_LRS
           caching: ReadOnly
           create_option: Redhat7.5_Slave
      tags:
        eci-service: "dcos-worker"
``` 

And the result is:

``` 
TASK [machines : Create VM DC-OS agent using existing NIC] *********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine wwazure0018e96 - Azure Error: InvalidParameter\nMessage: Cannot specify user image overrides for a disk already defined in the specified image reference.\nTarget: storageProfile"}
``` 

I am going to update the ansible version to 2.7.5/2.7.6 and set it again, I let you know

**Comment by Fred-sun** [comment]
@jvalderrama Thanks for your trying, waiting your good news!

**Comment by jvalderrama** [comment]
I have seen your point, it was able to create the machine specifying the create option for data_disks and using ansible version 2.7.6, that's right, but the OS disk image is taken in your sample like:

```
 image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest

```
That is a **not customize OS disk image**, therefore the data_disk list allows to set the create_option parameter therefore I think it has not any effect, even it has not be documented here https://docs.ansible.com/ansible/latest/modules/azure_rm_virtualmachine_module.html

If you try to create a VM with a **OS disk image customize** too
```
worker:
  dcos:
    nic:
      resource_group: DcosEE-RG
      virtual_network:
        resource_group: eCommerce_RG
        name: VNET_10_251_64_iaas
        subnet_name: VNET_10_251_64_iaas_subnet1
      security_group: DcosEE-NSG
    machine:
      resource_group: DcosEE-RG
      location: westeurope
      vm_size: Standard_E8s_v3
      admin_username: someruser
      ssh_password_enabled: false
      public_ip_allocation_method: Disabled
      managed_disk_type: Premium_LRS
      os_disk_size_gb: 60
      ssh_public_keys:
        path: /home/someuser/.ssh/authorized_keys
        key_data: "ssh-rsa xxxxxx"
      image:
          name: Redhat7.5_Slave
      data_disks:
         - lun: 0 
           disk_size_gb: 50 
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
         - lun: 1 
           disk_size_gb: 30
           managed_disk_type: Premium_LRS
           create_option: Redhat7.5_Slave
      tags:
        eci-service: "dcos-worker"
```

```
- name: Create VM DC-OS agent using existing NIC
  azure_rm_virtualmachine:
    name: "{{machine_hostname}}"
    resource_group: "{{worker.dcos.machine.resource_group}}"
    location: "{{worker.dcos.machine.location}}"
    vm_size: "{{worker.dcos.machine.vm_size}}"
    admin_username: "{{worker.dcos.machine.admin_username}}"
    ssh_password_enabled: "{{worker.dcos.machine.ssh_password_enabled}}"
    public_ip_allocation_method: "{{worker.dcos.machine.public_ip_allocation_method}}"
    managed_disk_type: "{{worker.dcos.machine.managed_disk_type}}"
    os_disk_size_gb: "{{worker.dcos.machine.os_disk_size_gb}}"
    network_interface_names:  "{{nic_name}}"
    ssh_public_keys:
    - path: "{{worker.dcos.machine.ssh_public_keys.path}}"
      key_data: "{{worker.dcos.machine.ssh_public_keys.key_data}}" 
      image: "{{worker.dcos.machine.image.name}}" # Use this only parameter for ECI Custom image otherwise use below
    data_disks:
      "{{worker.dcos.machine.data_disks}}"
    tags: 
      "{{worker.dcos.machine.tags}}" 
```

It fails :(

ASK [machines : Create VM DC-OS agent using existing NIC] *********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine wwazure0018e96 - Azure Error: InvalidParameter\nMessage: Cannot specify user image overrides for a disk already defined in the specified image reference.\nTarget: storageProfile"}

**Comment by Fred-sun** [comment]
@jvalderrama Thanks for your contribution, Yeah, The create_option parameter has no specification restrictions on the type of VM created.

**Comment by Fred-sun** [comment]
@zikalino Can you help me with this issue? The parameter create_option of data_disk has no constraints on the operating system type used to create the VM. Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Please help take a look this issue when you're available! Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Please help take a look this issue when you're available! Thanks!

**Comment by ansibot** [comment]
cc @cperrin88
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
Hi @jvalderrama , I am looking into the VM related issues these days. The `create_option` in this field is about how to create data disk attached to the VM. As [Azure API doc](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#datadisk) says, the possible value here is `from_image`, `attach`, `empty`. However for the `from_image` is "used when you are using an image to create the virtual machine.", which is used for `os_disk` instead of `data_disk`.

Currently, in the `azure_rm_virtualmachine` module, we supports the `create_option` as `empty`, to create a new data disk from disk or storage. If you wanna attach an exist managed disk to a VM, we do suggest to  use [`azure_rm_manageddisk`(previous `azure_rm_managed_disk`) module](https://docs.ansible.com/ansible/2.8/modules/azure_rm_manageddisk_module.html#azure-rm-manageddisk-module)'s `managed_by` option.

Your feature idea about [creating from image](https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate#diskcreateoption) is not supported yet unfortunately. I plan to add it  for v2.9 in managed disk module.

**Comment by ansibot** [comment]
cc @yungezz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jeking3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
!component=lib/ansible/modules/cloud/azure/azure_rm_manageddisk.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_manageddisk.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_manageddisk.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @brusMX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@jvalderrama Are you still pay attention this issue? You can use the[ azure_rm_manageddisk](https://github.com/ansible/ansible/blob/devel/test/integration/targets/azure_rm_manageddisk/tasks/main.yml) module to manage the VM data disk and You can upgrade to the latest ansible version attempt. Thank you very much!

**Comment by jvalderrama** [comment]
@Fred-sun Thanks for the thread. I understand that the feature was included in the latest version. 
I will try to test it.

**Comment by Fred-sun** [comment]
@jvalderrama Yes, you can update ansible to 2.8.3 to try. Thanks a lot!

**Comment by Fred-sun** [comment]
@jvalderrama When you finished testing, please share the test results. Thank you very much!

**Comment by arvindshmicrosoft** [comment]
Hi, @Fred-sun. We are hitting the same error but in the context of the VMSS module. In this case, we are trying to create the VMSS from a custom image, which in turn has the data disks included in the image definition itself. In such a case, we'd like to override the disk type (SSD vs. HDD) specified in the image version to a specific value, but we are unable to do so. The error is the same:

"msg": "Error creating or updating virtual machine somevmss - Azure Error: InvalidParameter\nMessage: Cannot specify user image overrides for a disk already defined in the specified image reference.\nTarget: storageProfile"

In the case of VMSS we are talking about hundreds of nodes, so manually attaching data disks is not an acceptable workaround. Would you like me to open a separate issue to track this?

**Comment by Fred-sun** [comment]
> Hi, @Fred-sun. We are hitting the same error but in the context of the VMSS module. In this case, we are trying to create the VMSS from a custom image, which in turn has the data disks included in the image definition itself. In such a case, we'd like to override the disk type (SSD vs. HDD) specified in the image version to a specific value, but we are unable to do so. The error is the same:
> "msg": "Error creating or updating virtual machine somevmss - Azure Error: InvalidParameter\nMessage: Cannot specify user image overrides for a disk already defined in the specified image reference.\nTarget: storageProfile"
> In the case of VMSS we are talking about hundreds of nodes, so manually attaching data disks is not an acceptable workaround. Would you like me to open a separate issue to track this?

@arvindshmicrosoft Yes, you can open a separate issue to track this! Thank you very much!

**Comment by Fred-sun** [comment]
Which maintainer will continue to focus and fix the problem?

**Comment by arvindshmicrosoft** [comment]
@Fred-sun was your last question for directed to me? For the VMSS case as you know we opened #61804 and my colleague @sputnik13 has implemented the fix in #62357.

**Comment by Fred-sun** [comment]
@arvindshmicrosoft  No, I want the community maintenance staff to pay attention to this problem! Thank you very much!

**Comment by Fred-sun** [comment]
@mybayern1974 Please take a look this issue when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
> @Fred-sun Thanks for the thread. I understand that the feature was included in the latest version right?.
> I will try to test it.

@jvalderrama Any update for this ? Could you help share your test result? Thank you very much!

**Comment by jvalderrama** [comment]
@Fred-sun I updated to v2.9 my ansible version and I was testing the feature to use the **azure_rm_manageddisk** module to create the **data_disks** after create the virtual machine, therefore as far as I understood the **create_option** will allow to set the **custom image**, but I don't have so clear the final definition for the **custom image** -if this affirmation is right- using this module.
@yuwzho mentioned to add this in v2.9 ,  can you guide me to complete the test and give some results.

```
worker:
  dcos:
    nic:
      resource_group: DcosEE-RG
      virtual_network:
        resource_group: eCommerce_RG
        name: VNET_10_251_64_iaas
        subnet_name: VNET_10_251_64_iaas_subnet1
      security_group: DcosEE-NSG
    machine:
      resource_group: DcosEE-RG
      location: westeurope
      vm_size: Standard_E8s_v3
      admin_username: someruser
      ssh_password_enabled: false
      public_ip_allocation_method: Disabled
      managed_disk_type: Premium_LRS
      os_disk_size_gb: 60
      ssh_public_keys:
        path: /home/someuser/.ssh/authorized_keys
        key_data: "ssh-rsa xxxxxx"
      image: RetHatSlave7.5
      tags:
        eci-service: "dcos-worker"
```

**Comment by Fred-sun** [comment]
@jvalderrama Sorry for the late reply. The azure_rm_manageddisk module currently only supports copy,import,empty three modes. Thank you very much!

**Comment by jvalderrama** [comment]
@Fred-sun , so you mean it will be something similar to the next block code, with a _blob uri_ in the **source_uri** that it is the **CUSTOM_IMAGE** parameter specification, in this case RetHatSlave7.5, right?
```
- name: Create managed operating system disk from page blob
  azure_rm_manageddisk:
    name: mymanageddisk
    location: westeurope
    resource_group: DcosEE-RG
    create_option: copy/import
    source_uri: /subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/DcosEE-RG/providers/Microsoft.Compute/images/RetHatSlave7.5
    os_type: linux
    storage_account_type: Premium_LRS
    disk_size_gb: 50
.....
```
