### ISSUE TITLE
aws lambda module returns inconsistent ARN

### ISSUE THREAD

**Issue by ezmac** [ansible/ansible#51071]
##### SUMMARY
Duplicate/re-opening of #47264 with more info.

When using boto3's lambda.get_function, if qualifier is given, an ARN to the qualified lambda function is returned. When not using a qualifier, the ARN to the lambda function is given.

```
>>> client = boto3.client('lambda')
>>> client.get_function(FunctionName='arn:aws:lambda:us-east-1:<snip>:function:myfunction')['Configuration']['FunctionArn']
'arn:aws:lambda:us-east-1:<snip>:function:myfunction'
>>> client.get_function(FunctionName='arn:aws:lambda:us-east-1:<snip>:function:myfunction:14')['Configuration']['FunctionArn']
'arn:aws:lambda:us-east-1:<snip>:function:myfunction:14'
```
So when used in the ansible lambda module, qualifier is used when `current_version is not None` roughly. When no change has happened, current_version is by default None.  If any change has happened, current_version will be set, qualifier will be used, and a version number will be appended to the ARN.

While that's technically consistent behavior, you have to do a lot of work to figure out what that behavior is.  Either it should be consistent or documented.

This problem showed up for me when creating lambda functions that are triggered by cloudwatchevent_rule.  When the function is new or changed, the rule had no target and playbook gave no errors indicating failure.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

amazon/lambda

##### ANSIBLE VERSION

Version is unimportant, behavior continues from at minimum 2.4 up to current devel.  possibly further back

```paste below
ansible 2.4.2.0
  config file = /home/tad/code/SSIT-Ansible/ansible.prod.cfg
  configured module search path = ['/home/tad/code/SSIT-Ansible/library']
  ansible python module location = /home/tad/.local/lib/python3.5/site-packages/ansible
  executable location = /home/tad/.pyenv/versions/3.5.2/bin/ansible
  python version = 3.5.2 (default, Jan  9 2019, 09:05:46) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Not relevant

##### STEPS TO REPRODUCE

```yaml
##  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html
- name: Lamda bashing
  hosts: localhost
  connection: local
  tasks:

    - name: make a lambda part 1
      shell: "echo \"print 'hello world'\" >  ./why.py"
      
    - name: re-package lambda function (zip step)
      shell: "zip why.zip why.py"

    - name: delete lambda if exists
      lambda:
        name: "bug-report-func"
        state: absent
    - name: set up a lambda function
      lambda:
        name: "bug-report-func"
        role: "private-dns-lambda-updater"
        runtime: python2.7
        zip_file: why.zip
        handler: test.handler
      register: lambda_function

      # Check it out; version number..
    - debug:
        var: lambda_function.configuration.function_arn

    - name: don't modify anything
      lambda:
        name: "bug-report-func"
        role: "private-dns-lambda-updater"
        runtime: python2.7
        zip_file: why.zip
        handler: test.handler
      register: lambda_function
      # But here? No version number.
    - debug:
        var: lambda_function.configuration.function_arn

```

##### EXPECTED RESULTS

I'd expect either a version number to ALWAYS be appended or never be appended.  Or some way to strip it, but as is I'd have to check if changed to see if I need to strip it off.

##### ACTUAL RESULTS

```paste below
PLAY [Lamda bashing] ******************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************
ok: [localhost]

TASK [make a lambda part 1] ***********************************************************************************************************************************
changed: [localhost]

TASK [re-package lambda function (zip step)] ******************************************************************************************************************
changed: [localhost]

TASK [delete lambda if exists] ********************************************************************************************************************************
changed: [localhost]

TASK [set up a lambda function] *******************************************************************************************************************************
changed: [localhost]

TASK [debug] **************************************************************************************************************************************************
ok: [localhost] => {
    "lambda_function.configuration.function_arn": "arn:aws:lambda:us-east-1:<snip>:function:bug-report-func:3"
}

TASK [set up a lambda function] *******************************************************************************************************************************
ok: [localhost]

TASK [debug] **************************************************************************************************************************************************
ok: [localhost] => {
    "lambda_function.configuration.function_arn": "arn:aws:lambda:us-east-1:<snip>:function:bug-report-func"
}

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=8    changed=4    unreachable=0    failed=0    skipped=0   

```

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.get_function

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/lambda.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/lambda.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @steynovich
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ezmac, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nethershaw** [comment]
This is also reproducible in Ansible 2.7.6.

It is more important than may be immediately apparent: some AWS APIs require fully-qualified Lambda ARNs that _must_ end in an absolute version number. The $LATEST qualifier is not permitted for use in such cases, so not only must one be able to control reliably how the ARN is expressed, one must also be able to reliably determine _which_ version is the latest version whether or not a change has been applied to the Lambda.

**Comment by nethershaw** [comment]
It seems the only way to get the latest version of a Lambda function without changing its code, and thus the only way to reliably produce a qualified function ARN that can be used with other AWS services, is to perform some complex JSON shenanigans in combination with the `lambda_facts` module after you create the function with the `lambda` module:

```
- name: gather Lambda function facts
  lambda_facts:
    function_name: myLambdaFunction
    region: us-east-1
    query: versions

- name: register Lambda function latest qualified ARN
  set_fact:
    cf_lambda_latest_qarn: "{{ lambda_facts['function']['myLambdaFunction'] | json_query('versions[?version!=`$LATEST`] | max_by(@, &to_number(version)).function_arn') }}"
```

That's ... needlessly complex, made worse by the fact that the `version` attribute of each item in the `versions` array is typed as a _string_ instead of a _number_, and the value `$LATEST` itself has an unknown type.

All of this just to get some digits to always show up at the end of your function ARN after you assert its existence seems un-Ansible-like.
