### ISSUE TITLE
digital_ocean_tag deletion isn't idempotent

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#51107]
##### SUMMARY
`digital_ocean_tag` can delete tags but it appears the action isn't idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean_tag

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0 (digital_ocean/integration_test_base f427f9b76a) last updated 2019/01/19 19:31:30 (GMT -500)
  config file = None
  configured module search path = [u'/Users/kbreit/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kbreit/Documents/Programming/ansible/lib/ansible
  executable location = /Users/kbreit/Documents/Programming/ansible/bin/ansible
  python version = 2.7.14 (default, Feb 25 2018, 14:48:55) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
macOS 10.13

##### STEPS TO REPRODUCE
```yaml
  - name: Delete tag
    digital_ocean_tag:
      oauth_token: abc123
      name: integration-test
      state: absent
    register: delete_tag

  - name: Delete tag
    digital_ocean_tag:
      oauth_token: abc123
      name: integration-test
      state: absent
    register: delete_tag_idempotent

  - assert:
      that:
        - delete_tag.changed == True
        - delete_tag_idempotent.changed == False
```

##### EXPECTED RESULTS
`delete_tag_idempotent.changed` should be false and the second task should show as unchanged.
