### ISSUE TITLE
'items' key in jinja2 filter selectattr not working

### ISSUE THREAD

**Issue by nabheet** [ansible/ansible#51105]
##### SUMMARY

While attempting to filter a list of dictionaries on the key `items`, selectattr does not work. It does not filter the list of dictionaries.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

selectattr

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.6
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/vagrant/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ANSIBLE_COW_SELECTION(/vagrant/ansible.cfg) = random
ANSIBLE_COW_WHITELIST(/vagrant/ansible.cfg) = [u'bud-frogs', u'bunny', u'cheese', u'daemon', u'default', u'dragon', u'elephant-in-snake', u'elephant', u'eyes', u'\\\nhellokitty',
ANSIBLE_PIPELINING(/vagrant/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/vagrant/ansible.cfg) = -o ServerAliveInterval=10 -o ControlMaster=auto -o ControlPersist=20s
ANSIBLE_SSH_RETRIES(/vagrant/ansible.cfg) = 5
DEFAULT_FORKS(/vagrant/ansible.cfg) = 10
DEFAULT_MODULE_PATH(/vagrant/ansible.cfg) = [u'/vagrant/modules']
DEFAULT_TIMEOUT(/vagrant/ansible.cfg) = 10
HOST_KEY_CHECKING(/vagrant/ansible.cfg) = False
LOCALHOST_WARNING(/vagrant/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: create data
      set_fact:
        created_data:
          - name: xyz
            items: ['a','b','c']
          - name: stu
            items: ['d', 'e', 'f']
          - name: ghi


    - name: extract data
      set_fact:
        defined_data: "{{ created_data | selectattr('items', 'defined') | list }}"
        undefined_data: "{{ created_data | selectattr('items', 'undefined') | list }}"


    - debug: var=defined_data
    - debug: var=undefined_data

```

##### EXPECTED RESULTS

defined_data should not have `name: ghi`
undefined_data should have `name: ghi`

##### ACTUAL RESULTS

```paste below
 ______________
< TASK [debug] >
 --------------
  \
   \   \_\_    _/_/
    \      \__/
           (oo)\_______
           (__)\       )\/\
               ||----w |
               ||     ||

ok: [localhost] => {
    "defined_data": [
        {
            "items": [
                "a",
                "b",
                "c"
            ],
            "name": "xyz"
        },
        {
            "items": [
                "d",
                "e",
                "f"
            ],
            "name": "stu"
        },
        {
            "name": "ghi"
        }
    ]
}
 ______________
< TASK [debug] >
 --------------
  \
   \   \
        \ /\
        ( )
      .( o ).

ok: [localhost] => {
    "undefined_data": []
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@nabheet Thanks for reporting this issue. Ansible is using `selectattr` filter from Jinja2 - [here](https://github.com/pallets/jinja/blob/9fe9520f2daa1df6079b188adba758d6e03d6af2/jinja2/filters.py#L1187). Also, if you change `items` to some other key then your example playbook works. I am not sure why `items` is not working with `selectattr`.

Here is my attempt

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: create data
      set_fact:
        created_data:
          - name: xyz
            sample: ['a','b','c']
          - name: stu
            sample: ['d', 'e', 'f']
          - name: ghi

    - name: extract data
      set_fact:
        defined_data: "{{ created_data | selectattr('sample', 'defined') | list }}"
        undefined_data: "{{ created_data | selectattr('sample', 'undefined') | list }}"


    - debug: var=defined_data
    - debug: var=undefined_data
```

Console log

```
# ansible-playbook selectattr.yml -v
Using /playbooks/core/ansible.cfg as config file

PLAY [localhost] ***************************************************************************************************************

TASK [create data] *************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"created_data": [{"name": "xyz", "sample": ["a", "b", "c"]}, {"name": "stu", "sample": ["d", "e", "f"]}, {"name": "ghi"}]}, "changed": false}

TASK [extract data] ************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"defined_data": [{"name": "xyz", "sample": ["a", "b", "c"]}, {"name": "stu", "sample": ["d", "e", "f"]}], "undefined_data": [{"name": "ghi"}]}, "changed": false}

TASK [debug] *******************************************************************************************************************
ok: [localhost] => {
    "defined_data": [
        {
            "name": "xyz",
            "sample": [
                "a",
                "b",
                "c"
            ]
        },
        {
            "name": "stu",
            "sample": [
                "d",
                "e",
                "f"
            ]
        }
    ]
}

TASK [debug] *******************************************************************************************************************
ok: [localhost] => {
    "undefined_data": [
        {
            "name": "ghi"
        }
    ]
}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0
```
