### ISSUE TITLE
vmware_guest - cannot change MAC address on existing interface

### ISSUE THREAD

**Issue by jsteel44** [ansible/ansible#51123]
##### SUMMARY

The MAC address is not updated if the NIC already exists. If I delete the NIC and run the task again, the NIC is created and it has the correct MAC address. But I am trying to clone the VM from a template which already has a NIC. One solution would be to delete the NIC first but it seems this cannot be done with vmware_guest.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jsteel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Arch Linux

##### STEPS TO REPRODUCE

```yaml
- name: VM NIC
  vmware_guest:
    hostname: vcenter-server
    username: user@vsphere.local
    validate_certs: no
    state: present
    datacenter: DC
    name: "{{ inventory_hostname }}"
    networks:
    - name: "{{ vm_network }}"
      mac: "aa:bb:dd:aa:00:14"
  delegate_to: localhost
```

##### EXPECTED RESULTS

The MAC address should be updated with the value above.

##### ACTUAL RESULTS

The MAC address is unchanged.
