### ISSUE TITLE
Unable to create service now ticket using ansible

### ISSUE THREAD

**Issue by sameermohanty02** [ansible/ansible#51137]
##### SUMMARY
I am trying to automate opening and closing of Service now tickets using Ansible. I have installed the required modules like pysnow as well. The problem is task runs fine but at the end no service now ticket is created

My ansible version is ansible 2.7.0 and I am running this on a docker container in GNS3.

##### ISSUE TYPE
Bug Report

##### ANSIBLE VERSION
ansible 2.7.0

##### STEPS TO REPRODUCE
Below is my code:

```
---
- hosts: localhost
  connection: local
  name: Test connection ServiceNow
  gather_facts: False

  tasks:
    - name: Create a incident
      snow_record:
        username: admin
        password: xxxxx
        instance: dev28162
        state: present
        data:
          short_description: "This is a test incident created by Ansible"
          priority: 2

        

      register: new_incident

    - debug: var=new_incident

```

Below is the result.

![image](https://user-images.githubusercontent.com/36122808/51488099-ae840e00-1dca-11e9-86c3-c99d0b04c26c.png)

**Comment by ansibot** [comment]
@sameermohanty02: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/notification/snow_record.py

**Comment by ansibot** [comment]
cc @garbled1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@sameermohanty02 I am not able to reproduce this issue.

I am able to create the record and retrieve it successfully - 

```
PLAY [localhost] *********************************************************************************************

TASK [Gathering Facts] ***************************************************************************************
ok: [localhost]

TASK [snow_record] *******************************************************************************************
changed: [localhost]

TASK [snow_record_find] **************************************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "INC0010009"
}

PLAY RECAP ***************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

I am using the following playbook 

```yaml
  tasks:
    - snow_record:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: "{{ instance }}"
        data:
            short_description: "Test 1"
            priority: 2
        state: present
      register: ticket_details

    - snow_record_find:
        username: "{{ username }}"
        password: "{{ password }}"
        table: incident
        instance: "{{ instance }}"
        query:
          sys_id: "{{ ticket_details['record']['sys_id'] }}"
      register: record_details

    - debug:
        msg: "{{ record_details['record'][0]['number'] }}"
```

Could you please check your environment and let us know? 

Thanks,

needs_info
