### ISSUE TITLE
Module request: read mail (IMAP support)

### ISSUE THREAD

**Issue by varunchopra** [ansible/ansible#51151]
##### SUMMARY
A module to get mail from an IMAP server would be great, for instance, proceeding with a task if confirmation has been received via mail.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`read_mail`

##### ADDITIONAL INFORMATION
```yaml
- read_mail:
    host: "{{ imap_host }}"
    username: "{{ imap_user }}"
    password: "{{ imap_pass }}"
    ssl: True
    filter:
      subject: "subject_should_contain_this"
```

Will list e-mails that match the subject filter.

A bunch of additional filters can be supplied, possibly supporting regular expressions as well.
