### ISSUE TITLE
Don't deprecate with_nested

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#51153]
##### SUMMARY

Please, don't deprecate with_nested
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

with_nested
##### ADDITIONAL INFORMATION

Don't deprecate with_nested because it's much more practical than "product", it's much more visual

What is more appealing to the eyes?
```yaml
  with_nested:
    - "{{ azerothcore___DTP }}"                             # 0
    - "{{ range(1, project.realms_count + 1 ) | list }}"    # 1
    - "{{ azerothcore___db_names }}"                        # 2

VS:

  loop: "{{ azerothcore___DTP | product( range(1, project.realms_count + 1 ) , azerothcore___db_names ) | list }}"
```

I think you guys want to deprecate every "with_*" for "product" but not sure it's the best idea.
