### ISSUE TITLE
gcp_compute_instance doesn't return output on second run

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#51174]
##### SUMMARY
Running gcp_compute_instance for second time won't return any facts to register (except changed and failed)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_compute_instance

##### ANSIBLE VERSION

```
ansible 2.7.6
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

archlinux
debian
coreos
##### STEPS TO REPRODUCE

Run the following tasks for 1 time - you will see the full debug output with instance info
Run for second time, only 'changed' and 'failed' is returned.

```yaml
    - name: Create gcloud instance
      gcp_compute_instance:
        auth_kind: "machineaccount"
        disks:
          - auto_delete: yes
            boot: yes
            initialize_params:
              source_image: "myimage"
              disk_size_gb: 15
        machine_type: "n1-standard-1"
        name: "my_name"
        network_interfaces:
          - name: eth0
        project: myproject
        service_account_email: "serviceaccount@developer.gserviceaccount.com"
        tags:
          items:
            - tag1
            - tag2
        zone: "us-central1-a"
      register: my_instance

    - debug:
        msg: "{{ my_instance }}"
```

##### EXPECTED RESULTS
Instance facts always registered, no matter how many runs

##### ACTUAL RESULTS
Only the first run (when instance is created) is registered

```
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "failed": false
    }
}
```
