### ISSUE TITLE
[vmware_guest] vswitch portgroup and distributed portgroup have same name. Clone failed

### ISSUE THREAD

**Issue by strom18** [ansible/ansible#51180]
##### SUMMARY

We have a VMware network Portgroup which have the same name on vSwitch and Distributed vSwitch.
When we clone a new virtual machine on a cluster with standard vSwitch, the clone failed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/support/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT
vCenter 6.5u2 & ESXi 6.0u3

##### STEPS TO REPRODUCE

1. Create a vSwtich Portgroup with name like TEST
2. Create a Distributed Portgroup with name like TEST
3. Clone a VM with the network name TEST on a cluster with standard vswitch

```yaml
---
- hosts: localhost
  connection: local
  tasks:
  - name: Clone a VM from Template and customize
    vmware_guest:
      hostname: vcenter.xxxx.xxx
      username: xxxxxx@xxxx.xxx
      password: xxxxxxxxxxxxxxxxxxxxxxxxxxx
      validate_certs: no
      datacenter: '{{ VM_DATACENTER }}'
      cluster: '{{ VM_CLUSTER }}'
      folder: /
      name: '{{ VM_NAME }}'
      template: '{{ VM_OS }}'
      disk:
        - size_gb: 25
          type: thick
          datastore: '{{ VM_STORAGE }}'
        - size_gb: 5
          datastore: '{{ VM_STORAGE }}'
      state: poweredon
      hardware:
        memory_mb: '{{ VM_MEMORY }}'
        num_cpus: '{{ VM_CPU }}'
      networks:
      - name: '{{ VM_NETWORK }}'
        ip: '{{ VM_IP }}'
        netmask: x.x.x.x
        gateway: x.x.x.x
        domain: xxxx.xxx
        dns_servers:
        - x.x.x.x
        - x.x.x.x
      customization:
        autologon: yes
        dns_servers:
        - x.x.x.x
        - x.x.x.x
        domain: xxxx.xxx
    delegate_to: localhost

```

##### EXPECTED RESULTS

Clone process force creation on standard vSwitch

##### ACTUAL RESULTS

Works fine on a cluster with ditributed vswitch.
Do not work on cluster with standard vswitch.

How can we force the configuration on standard portgroup (vswitch) ?
