### ISSUE TITLE
RFE: Add Ability to Iterate Loops Over Blocks

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#51197]
##### SUMMARY

Allow ability to loop over blocks in playbook

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

blocks

##### ADDITIONAL INFORMATION

```yaml
- block:
    [...]
  with_items:
    - list
```
