### ISSUE TITLE
Running nios_a_record with "state = absent" does not remove the record.

### ISSUE THREAD

**Issue by patrick-andrew-jain-taylor** [ansible/ansible#51193]
##### SUMMARY

I have modified an existing playbook to go from adding an A record to removing an A record. The state continues to show ok instead of changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios_a_record

##### ANSIBLE VERSION

```
ansible 2.7.5
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

```
Ansible Environment: Red Hat Enterprise Linux Server
```

##### STEPS TO REPRODUCE

```
- name: Add - A Record
    nios_a_record:
      comment: 'comment'
      ipv4: '{{ ipaddr }}'
      name: test.com
      provider: '{{ provider }}'
      state: present
      view: Internal
```

##### EXPECTED RESULTS

I would expect an output of changed instead of ok.

##### ACTUAL RESULTS

Play doesn't  remove the a_record
