### ISSUE TITLE
Docker default bridge is assigned to container when I'm not asking for

### ISSUE THREAD

**Issue by Poil** [ansible/ansible#51225]
**SUMMARY**

Hi,

If i do this

```yaml
- name: "redis"
  become: true
  docker_container:
    name: "redis"
    image: redis
    networks:
      - name: internal_network
    exposed_ports:
      - 6379
```

When inspecting my redis container it have 2 networks, the `internal_network` and the default bridge.
I don't understand why, because if running my redis via command line, it only have my internal_network

```sh
docker run -it --net=none --net=internal_network redis
```

It seems that when I add the parameter `purge_networks: true` to my docker_container definition I only have my `internal_network`
If it's what you want, it is very not user friendly :)

**ISSUE TYPE**

    Bug Report

**COMPONENT NAME**

docker_container

**Ansible Version**
```
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]
```

Best regards,
