### ISSUE TITLE
Enhance win_group_membership to remove all other users or groups not defined in playbook

### ISSUE THREAD

**Issue by mikemadeja** [ansible/ansible#51241]
##### SUMMARY
At my company, we have strict guidelines on who can access our Windows servers. Sometimes a ticket will come in from a developer asking to get access to a server and our 1st tier team will do it. I think it would be a great enhancement that if you have a parameter to drop all other groups defined in playbook.

IE I have a playbook that defines Active Directory group "RDP_Group_A" be added to local group Remote Desktop Users on servers.

If someone adds RDP_Group_B to the server manually to Remote Desktop Users group, and I run my playbook, it should remove RDP_Group_B and only have RDP_Group_A there.

Maybe some kind of parameter to drop all other? Say a boolean called **remove_all_other_objects**?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_group_membership

##### ADDITIONAL INFORMATION
This would allow us to have groups in a desired state including not allowing other groups to be added outside of the process via Ansible. 

```yaml
 tasks:
  - name: Remote Desktop Users membership
    win_group_membership:
      name: Remote Desktop Users
      members:
        - CORPORATE\{{ad_group}}
      state: present
      **remove_all_other_objects: true**
```
