### ISSUE TITLE
VMware: Adding IP specific firewall rules in vmware_host_firewall_manager

### ISSUE THREAD

**Issue by alongchamps** [ansible/ansible#51240]
##### SUMMARY
As a user of the VMware modules in Ansible, I want to be able to specify IP addresses to go along with vmware_host_firewall_manager configurations so we can configure network-based firewall rules on a per-rule basis

##### ISSUE TYPE
- Add support for IP specific rules for the ESXi firewall

##### COMPONENT NAME
vmware_host_firewall_manager

##### ADDITIONAL INFORMATION

This would be used to configure the ESXi firewall to only allow certain IP ranges for certain services. It would be used when we need to restrict inbound communications

This can also go along with the vmware_host_firewall_facts playbook, which returns the all_ip and ip_address fields as child properties

```yaml
- name: Enable faultTolerance rule set for an ESXi Host
  vmware_host_firewall_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster: '{{ cluster_name }}'
    rules:
        - name: faultTolerance
          enabled: True
          all_ip: False
          ip_address: ['10.0.10.0/24', '10.0.20.0/24']
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_firewall_manager.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@alongchamps: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @ckotte @dav1x @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@alongchamps, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alongchamps** [comment]
FYI for anyone reading this, I am working on this one internally in my current team's sprint because it solves a need for us. For any questions, just reach out.

**Comment by alongchamps** [comment]
@Akasurde can I get your thoughts on this for an example playbook for firewall rules where allowed_all is False and specifying IP addresses/networks:

https://paste.fedoraproject.org/paste/nPR6UFtUwFHJEs3UM6hqBA

**Comment by ansibot** [comment]
cc @lparkes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alongchamps** [comment]
This relates to an issue I discovered in vmware_host_firewall_facts where it only pulls back the list of allowed IP addresses and not IP networks that can also be found. I will open a bug report on that one because it is not pulling back all of the data as needed.

**Comment by Akasurde** [comment]
@alongchamps I raised PR for #52526. I am OK with the data-structure provided in https://paste.fedoraproject.org/paste/-uwtWiXskSfNEGiSIRZNdw. Please go ahead with the changes and raise a PR, let me know. Thanks.

**Comment by Akasurde** [comment]
In case we lose pastebin in future, this is data-structure we have decided for new firewall rulesets 

```
---
- hosts: localhost
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - name: set host firewall configuration
      vmware_host_firewall_manager:
        hostname: '{{ vcenter_ip }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: '{{ virtual_host_name }}'
        validate_certs: False
        rules:
          - name: CIMHttpServer
            enabled: True
            allowed_hosts:
              - all_ip: False
                ip_address:
                  - "192.168.100.25"
                  - "192.168.100.26"
                ip_network:
                  - "192.168.200.0/24"
```
