### ISSUE TITLE
Incorrect comment in example on sysctl module

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#51269]
##### SUMMARY

https://docs.ansible.com/ansible/latest/modules/sysctl_module.html has this example:

```
# Set ip forwarding on in /proc and do not reload the sysctl file
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
```

"do not reload the sysctl file" is incorrect here, since reload is "yes" by default. That probably refers to the previous example, which has "reload: no"

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

sysctl

##### ANSIBLE VERSION

2.5+
