### ISSUE TITLE
pacman module `state: absent` verification failure when package name is provided by another

### ISSUE THREAD

**Issue by greyltc** [ansible/ansible#51265]
On ansible 2.7.6 I've done:
```
- name: remove test
  pacman:
    name: linux-gpib
    state: absent
```
the linux-gpib package is not installed on the system, however linux-gpib-dkms is installed which provides linux-gpib
```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "failed to remove linux-gpib"}
```
I expect no errors because the the package is indeed absent on the system.
