### ISSUE TITLE
Ansible-pull /  sudo invalid output (sorry, you must have a tty to run sudo error)

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#5129]
Hi,

I have a playbook that downloads and install java, the java install tasks works OK in push mode but fails in **pull mode** using the same OS and Ansible version : 
- ansible 1.5 (devel 04b031756c) last updated 2013/12/02 15:05:03 (GMT +000))
- CentOS release 6.4 (Final)
### java-install-task.yml

```
- name: Installing Java
  shell: yes | /bin/sh {{ DOWNLOAD_DIR }}/jdk-{{ JDK_VERSION }}-linux-x64-rpm.bin
  sudo: yes
  when: java_version.stdout != 'jdk-1.6.0_26-fcs.x86_64'
  tags:
    - java
    - packages
```
### Error :

```
TASK: [web | Installing Java] *************************************************
failed: [localhost] => {"failed": true, "item": "", "parsed": false}
invalid output was: sudo: sorry, you must have a tty to run sudo
```

PS: The ansible-pull cronjob is running as root .
