### ISSUE TITLE
NIOS: Update records

### ISSUE THREAD

**Issue by mrchrd** [ansible/ansible#51301]
##### SUMMARY

NIOS modules fail to update an existing record. It tries to update the 'view' value, but it fails because it's a read-only field.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios_*_record modules

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04
infoblox-client 0.4.20
Infoblox 8.3.1

##### STEPS TO REPRODUCE

```yaml
 - hosts: localhost
  tasks:
  - nios_a_record:
      name: a.test.com
      extattrs:
        "Cloud API Owned": "True"
        "CMP Type": "test"
        "Tenant ID": "test"
      ipv4: 1.2.3.4
      state: present
```
First run this playbook, then rerun it with a different `ipv4` value.

##### EXPECTED RESULTS

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "comment": null,
            "extattrs": {
                "CMP Type": "test",
                "Cloud API Owned": "True",
                "Tenant ID": "test"
            },
            "ipv4": "1.2.3.5",
            "ipv4addr": "1.2.3.5",
            "name": "a.test.com",
            "state": "present",
            "ttl": null,
            "view": "default"
        }
    }
}
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "code": "Client.Ibap.Proto",
    "invocation": {
        "module_args": {
            "comment": null,
            "extattrs": {
                "CMP Type": "test",
                "Cloud API Owned": "True",
                "Tenant ID": "test"
            },
            "ipv4": "1.2.3.5",
            "ipv4addr": "1.2.3.5",
            "name": "a.test.com",
            "state": "present",
            "ttl": null,
            "view": "default"
        }
    },
    "msg": "Field is not allowed for update: view",
    "operation": "update_object",
    "type": "AdmConProtoError"
}
```
