### ISSUE TITLE
ec2 module: profile option ignored

### ISSUE THREAD

**Issue by wutzkachel** [ansible/ansible#51329]
##### SUMMARY
ec2 module: profile option ignored

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible aws ec2
##### ANSIBLE VERSION
```
ansible 2.7.6
  config file = /home/michael/ansible.cfg
  configured module search path = [u'/home/michael/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/michael/.local/share/virtualenvs/PipenvAnsible27Python27-TIMLuz9F/lib/python2.7/site-packages/ansible
  executable location = /home/michael/.local/share/virtualenvs/PipenvAnsible27Python27-TIMLuz9F/bin/ansible
  python version = 2.7.15 (default, Jan 10 2019, 23:20:52) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```
ansible-config dump --only-changed                                                                            ✔  5  13:27:09
DEFAULT_HOST_LIST(/home/michael/ansible.cfg) = [u'/home/michael/inventory']
HOST_KEY_CHECKING(/home/michael/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/michael/ansible.cfg) = False

```

##### OS / ENVIRONMENT
4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
##### STEPS TO REPRODUCE
Example Playbook:
---------------------

```yaml
- name: ProvisionEc2CentOs7Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - awscredentials.yml
  tasks:
    - name: Launch instance
      ec2:
        profile: AWSCockpitMonitoringDevelEnv
        region: "{{ region }}"
        key_name: "{{ key_pair_name }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ami_ID}}"
        vpc_subnet_id: "{{ subnet_ID }}"
        assign_public_ip: no
        group: "{{ security_group_name }}"
        user_data: "{{lookup('file', 'cloudconfig.txt')}}"
        wait: true
        count_tag:
          Name: testrechner
        exact_count: 1
        instance_tags:
          Creator: michaelmckirchner
          Name: testrechner
          Function: testrechner
        volumes:
          - device_name: /dev/sda1
            delete_on_termination: true
            volume_type: gp2
            volume_size: 10
          - device_name: /dev/sdf
            delete_on_termination: true
            encrypted: true
            kms_key_id: "{{ ec2volume_encryption_key }}"
            volume_type: gp2
            volume_size: 20
            async: 7200
            poll: 10
      register: ec2info
```

##### EXPECTED RESULTS
A running EC2  instance

##### ACTUAL RESULTS

The full traceback is:
Traceback (most recent call last):
  File "/home/michael/.ansible/tmp/ansible-tmp-1548419712.28-158847672618392/AnsiballZ_ec2.py", line 113, in <module>
    _ansiballz_main()
  File "/home/michael/.ansible/tmp/ansible-tmp-1548419712.28-158847672618392/AnsiballZ_ec2.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/michael/.ansible/tmp/ansible-tmp-1548419712.28-158847672618392/AnsiballZ_ec2.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ec2_payload_ODUj70/__main__.py", line 1692, in <module>
  File "/tmp/ansible_ec2_payload_ODUj70/__main__.py", line 1678, in main
  File "/tmp/ansible_ec2_payload_ODUj70/__main__.py", line 887, in enforce_count
  File "/tmp/ansible_ec2_payload_ODUj70/__main__.py", line 568, in find_running_instances_by_count_tag
  File "/tmp/ansible_ec2_payload_ODUj70/__main__.py", line 600, in get_reservations
  File "/home/michael/.local/share/virtualenvs/PipenvAnsible27Python27-TIMLuz9F/lib/python2.7/site-packages/boto/vpc/__init__.py", line 1152, in get_all_subnets
    return self.get_list('DescribeSubnets', params, [('item', Subnet)])
  File "/home/michael/.local/share/virtualenvs/PipenvAnsible27Python27-TIMLuz9F/lib/python2.7/site-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>09741a00-cc94-4992-b268-67a008d5fff1</RequestID></Response>

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/michael/.ansible/tmp/ansible-tmp-1548419712.28-158847672618392/AnsiballZ_ec2.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/michael/.ansible/tmp/ansible-tmp-1548419712.28-158847672618392/AnsiballZ_ec2.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/michael/.ansible/tmp/ansible-tmp-1548419712.28-158847672618392/AnsiballZ_ec2.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ec2_payload_ODUj70/__main__.py\", line 1692, in <module>\n  File \"/tmp/ansible_ec2_payload_ODUj70/__main__.py\", line 1678, in main\n  File \"/tmp/ansible_ec2_payload_ODUj70/__main__.py\", line 887, in enforce_count\n  File \"/tmp/ansible_ec2_payload_ODUj70/__main__.py\", line 568, in find_running_instances_by_count_tag\n  File \"/tmp/ansible_ec2_payload_ODUj70/__main__.py\", line 600, in get_reservations\n  File \"/home/michael/.local/share/virtualenvs/PipenvAnsible27Python27-TIMLuz9F/lib/python2.7/site-packages/boto/vpc/__init__.py\", line 1152, in get_all_subnets\n    return self.get_list('DescribeSubnets', params, [('item', Subnet)])\n  File \"/home/michael/.local/share/virtualenvs/PipenvAnsible27Python27-TIMLuz9F/lib/python2.7/site-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>AuthFailure</Code><Message>**AWS was not able to validate the provided access credentials**</Message></Error></Errors><RequestID>09741a00-cc94-4992-b268-67a008d5fff1</RequestID></Response>\n", 
    "module_stdout": "reply: 'HTTP/1.1 200 Connection established\\r\\n'\nheader: Connection: close\r\nsend: u'GET https://ec2.eu-central-1.amazonaws.com/?Action=DescribeSubnets&SubnetId.1=subnet-Number&Version=2014-10-01 HTTP/1.1\\r\\nAccept-Encoding: identity\\r\\nContent-Length: 0\\r\\nHost: ec2.eu-central-1.amazonaws.com\\r\\nAuthorization: AWS4-HMAC-SHA256 Credential=SomeCredentialInformation/20190125/eu-central-1/ec2/aws4_request,SignedHeaders=host;x-amz-date,Signature=SomeSignature\\r\\nX-Amz-Date: 20190125T123514Z\\r\\nUser-Agent: Boto/2.49.0 Python/2.7.15 Linux/4.20.3-arch1-1-ARCH\\r\\n\\r\\n'\nreply: 'HTTP/1.1 401 Unauthorized\\r\\n'\nheader: Transfer-Encoding: chunked\r\nheader: Date: Fri, 25 Jan 2019 12:35:14 GMT\r\nheader: Server: AmazonEC2\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
