### ISSUE TITLE
azure_rm_publicipaddress not idempotent

### ISSUE THREAD

**Issue by nomadcz** [ansible/ansible#51324]
##### SUMMARY
azure_rm_publicipaddress not idempotent

##### ISSUE TYPE
azure_rm_publicipaddress always returns status "changed" and takes a long time to run - so I guess it updates public ip object during every run ?

##### COMPONENT NAME
azure_rm_publicipaddress 

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /home/spider/ansible/ansible-michal/ansible.cfg
  configured module search path = [u'/home/spider/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/spider/python/ansible-michal/lib/python2.7/site-packages/ansible
  executable location = /home/spider/python/ansible-michal/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE

```
    - name: "Create Public IPs"
      azure_rm_publicipaddress:
        name: "{{ item.name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        allocation_method: "{{ item.allocation_method }}"
        domain_name: "{{ item.domain_name | default(omit) }}"
        tags: "{{ item.tags }}"
      loop: "{{ azure_objects.public_ips }}"
      loop_control:
        label: "Public IP: {{ item.name }} ; Allocation: {{ item.allocation_method }} ; Domain: {{ item.domain_name | default('NONE', true) }} ; Location: {{ location }} ; Resource Group: {{ resource_group }} ; Env: {{ item.tags.env }}"
      # For some reason always reports as changed :/
      changed_when: false
      tags:
        - "public_ip"
        - "public_ips"
```

##### EXPECTED RESULTS
No change is done nor reported when repeatedly run with the same parameters

##### ACTUAL RESULTS
Always reports change during run

```paste below

```
