### ISSUE TITLE
mysql_user fails to parse show grant response from mysql

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#51356]
##### SUMMARY

This appears to be a duplicate of #20520, but that is from 2017 and is marked as resolved.  I am seeing this behavior with MySQL versions 8 and 10.

Given a `mysql_user` task like this:

```
    - name: Create a new user {{ NEW_USER  }} with all rights on {{ DB_NAME  }} database
      mysql_user:
        login_host: "{{ DB_HOST }}"
        login_user: "{{ DB_USER }}"
        login_password: "{{ DB_PASS }}"
        name: "{{ NEW_USER }}"
        password: "{{ NEW_PASS }}"
        host: '%'
        priv: "{{ DB_NAME }}.*:ALL"
        state: present
```

The task will succeed the first time it is run, but on subsequent runs will fail with:

```
TASK [Create a new user testuser with all rights on somedb database] **************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InvalidPrivsError: unable to parse the MySQL grant string: GRANT USAGE ON *.* TO `testuser`@`%`
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to parse the MySQL grant string: GRANT USAGE ON *.* TO `testuser`@`%`"}
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to parse the MySQL grant string: GRANT USAGE ON *.* TO `larsks`@`%`"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /home/lars/.ansible.cfg
  configured module search path = [u'/home/lars/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lars/tmp/ansible/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/lars/tmp/ansible/.venv/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  vars:
    DB_HOST: 172.17.0.2
    DB_USER: root
    DB_PASS: secret
    DB_NAME: somedb

    NEW_USER: testuser
    NEW_PASS: password
  tasks:
    - name: Create a new database with name {{ DB_NAME  }} Company
      mysql_db:
        login_host: '{{ DB_HOST }}'
        login_user: "{{ DB_USER }}"
        login_password: "{{ DB_PASS }}"
        name: "{{ DB_NAME }}"
        state: present
    - name: Create a new user {{ NEW_USER  }} with all rights on {{ DB_NAME  }} database
      mysql_user:
        login_host: "{{ DB_HOST }}"
        login_user: "{{ DB_USER }}"
        login_password: "{{ DB_PASS }}"
        name: "{{ NEW_USER }}"
        password: "{{ NEW_PASS }}"
        host: '%'
        priv: "{{ DB_NAME }}.*:ALL"
        state: present
```

##### EXPECTED RESULTS

The task should run subsequently on playbooks runs other than the first.

##### ACTUAL RESULTS

```
TASK [Create a new user testuser with all rights on somedb database] **************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InvalidPrivsError: unable to parse the MySQL grant string: GRANT USAGE ON *.* TO `testuser`@`%`
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to parse the MySQL grant string: GRANT USAGE ON *.* TO `testuser`@`%`"}
```

This is happening in the [privileges_get](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_user.py#L409) method, which runs the `SHOW GRANTS` command and then attempts to parse the response using this regular expression:

```python
res = re.match("GRANT (.+) ON (.+) TO '.*'@'.*'( IDENTIFIED BY PASSWORD '.+')? ?(.*)", grant[0])
```

But the response from mysql looks like this:

```
MySQL [(none)]> show grants for 'testuser'@'%';
+------------------------------------------------------+
| Grants for testuser@%                                |
+------------------------------------------------------+
| GRANT USAGE ON *.* TO `testuser`@`%`                 |
| GRANT ALL PRIVILEGES ON `somedb`.* TO `testuser`@`%` |
+------------------------------------------------------+
```

The regular expression is looking for:

    '.*'@'.*'

But mysql is responding with:

    `.*`@`.*`
