### ISSUE TITLE
Add groupvars to playbook in addition to hostvars

### ISSUE THREAD

**Issue by abitrolly** [ansible/ansible#51369]
##### SUMMARY

The idea of adding `groupvars` lookup to playbooks can be considered a duplicate of #22559, so the goal of this issue is to provide more explicit example with no discussions about possible hacks and workarounds.

This is what I propose:
```yaml
---
- hosts: all
  vars:
  - TOKEN: gl5N4fV3udCaIc
  tasks:
  - template:
      src: config.cfg.j2
      dest: config.cfg
    vars:
    - token: "{{ TOKEN }}"

- hosts: servers
  tasks:
  - raw: "addtoken.sh {{ groupvars['all']['TOKEN'] }}"
```

This is the hack proposed by people on StackOverflow.
```yaml
---
- hosts: all
  vars:
  - TOKEN: gl5N4fV3udCaIc
  tasks:
  - template:
      src: config.cfg.j2
      dest: config.cfg
    vars:
    - token: "{{ TOKEN }}"
  - add_host:
      name: "TOKEN_HOLDER"
      TOKEN: "{{ TOKEN }}"

- hosts: servers
  tasks:
  - raw: "addtoken.sh {{ hostvars['TOKEN_HOLDER']['TOKEN'] }}"
```
https://stackoverflow.com/questions/33896847/how-do-i-set-register-a-variable-to-persist-between-plays-in-ansible/47811099#47811099

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

playbook.yml

##### ADDITIONAL INFORMATION

```yaml

```
