### ISSUE TITLE
NIOS (Infoblox) modules should use API authentication cookie

### ISSUE THREAD

**Issue by badnetmask** [ansible/ansible#51402]
##### SUMMARY

The current authentication implementation of the NIOS (Infoblox) modules makes use of statically defined variables for username and password, to be used in every single task. This breaks the use of dynamic authentication methods, like in environments that use time-based password (token/2FA).

The NIOS WAPI provides a cookie (ibapauth), which can be retrieved on the first authentication, and re-used on every subsequent call. Using this cookie would prevent the need to re-send the password for every task.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nios_*
nios_network
nios_zone
nios_a_record
nios_cname_record

##### ADDITIONAL INFORMATION

The final usage of this feature would make the NIOS-related playbooks behave like any other playbook that uses the "ovirt_*" modules. On those modules, the first task of the playbook is the authentication, which then generates an internal Ansible variable, which contains the authentication token, and is-reused for ever subsequent calls to the oVirt API. (examples can be found on: https://www.ovirt.org/develop/release-management/features/infra/ansible_modules.html)

Below is an example of how a NIOS playbook would look like, if this authentication token would be implemented:

```yaml
- hosts: nios
  connection: local
  tasks:
    - name: authenticate to Infoblox
      nios_auth:
        host: 192.0.0.2
        username: admin
        password: ansible
    - name: create management reverse DNS zone
      nios_zone:
        provider: "{{ nios_auth }}"
        name: 192.168.0.0
        state: present
    - name: create user reverse DNS zone
      nios_zone:
        provider: "{{ nios_auth }}"
        name: 192.168.1.0
        state: present
    - name: revoke authentication token (sends /wapi/vX/logout API call)
      nios_auth:
        state: absent
        nios_auth: "{{ nios_auth }}"
```
