### ISSUE TITLE
git module: 'git' command does not create --separate-git-dir path automatically

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#51425]
##### SUMMARY

The `git clone --separate-git-dir` command does not create the separate git dir automatically when cloning the source code, that only happens for the checked out worktree. When this functionality is used with Ansible `git` module, and the path to the separate git directory does not exist, the module returns with an error:
```
TASK [Clone repository with separate git dir] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin --separate-git-dir=/tmp/src/github.com/ansible/ansible https://github.com/ansible/ansible /tmp/public/github.com/ansible/ansible", "msg": "Cloning into '/tmp/public/github.com/ansible/ansible'...\nfatal: Could not switch to '/tmp/src/github.com/ansible/': No such file or directory", "rc": 128, "stderr": "Cloning into '/tmp/public/github.com/ansible/ansible'...\nfatal: Could not switch to '/tmp/src/github.com/ansible/': No such file or directory\n", "stderr_lines": ["Cloning into '/tmp/public/github.com/ansible/ansible'...", "fatal: Could not switch to '/tmp/src/github.com/ansible/': No such file or directory"], "stdout": "", "stdout_lines": []}
```

An obvious solution to this is to use the `file` module to create the required path beforehand. However at first glance this might look like a bug in the Ansible `git` module - perhaps a good idea would be to either create the separate git directory when it doesn't exist (in that case the module would have to create only the parent directory), or if that fails outside of the `git` module responsibility, catch the error sent by the `git` command and add a short explanation to the `git` module error message that the separate git dir needs to exist beforehand.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git module
##### ADDITIONAL INFORMATION

An example playbook to test the functionality:
```yaml
---

- name: Test separate git dir checkout
  hosts: 'all'

  vars:
    git_repo: 'https://github.com/ansible/ansible'
    git_dest: '{{ "/tmp/public/" + git_repo.split("://")[1] }}'
    git_dir:  '{{ "/tmp/src/" + git_repo.split("://")[1] }}'
    depth: 1

  tasks:

    - name: Clone repository with separate git dir
      git:
        repo: '{{ git_repo }}'
        dest: '{{ git_dest }}'
        separate_git_dir: '{{ git_dir }}'
```
