### ISSUE TITLE
Make known_hosts use plain public keys (.pub files content)

### ISSUE THREAD

**Issue by piccardi** [ansible/ansible#51435]
##### SUMMARY

Simplify hosts keys management in known_hosts module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

known_hosts

##### ADDITIONAL INFORMATION

Now to add a key to **.ssh/known_hosts** with this module you need to get it from a server, remove the comment field (the last field), prepend an hostname to it, then pass it in the **key** parameter. And you must have care to use the same hostname that you use in the **name** parameter. So you have to duplicate the same information (the hostname of the server) in two different parameters: **name** and  **key**. And having the same information in two different places it's always asking for troubles.

Having anyway the need to pass the **name**  parameter for a server hostname I suggest to use for the  **key** value (at least as an option) just the plain content of an SSH public key file, as found in the **/etc/ssh/** on the server, instead of the _known_hosts_ format, that you must craft by yourself. The conversion to the _known_hosts_ format (trivial anyway) should be done by the module.

The syntax should be just the same, adding the use of a **format** (or the like) parameter with a value to  select the key format if you want to mantain backward compatibility with the current behaviour:

```yaml
- name: tell the host about our servers it might want to ssh to
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: foo.com.invalid
    key: "{{ lookup('file', 'pubkeys/foo.com.invalid') }}"
    format: ssh_key
```
where using something like **format: know_hosts** will explicitely get the current behaviour, that can be left as default for beeing backward compatible.
