### ISSUE TITLE
Cisco unable to enter enabled mode

### ISSUE THREAD

**Issue by cr33phav** [ansible/ansible#51436]
##### SUMMARY
Unable to enter enable mode on Cisco devices

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

IOS command

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = False
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /root/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Cisco IOS Software, 3700 Software (C3745-ADVENTERPRISEK9-M), Version 12.4(25d), RELEASE SOFTWARE (fc1)

Cisco IO 4506

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

##### STEPS TO REPRODUCE

```yaml
Playbook:
- name: Simple test
  hosts: test
  connection: network_cli
  gather_facts: false
  tasks:
     - name: Change hostname
       ios_command:
          commands:
             - hostname ThisIsATest
       become_method: enable
       become: yes

Host file
all:
  children:
    test:
      hosts:
        192.168.200.1

Group Vars:
ansible_connection: network_cli
ansible_network_os: ios
ansible_user: admin
ansible_ssh_pass: password
absible_become_pass: password
```

##### EXPECTED RESULTS

Log into router, enter enable mode, make changes

##### ACTUAL RESULTS

```paste below
root@don-VirtualBox:/etc/ansible# ansible-playbook -vvvv router_test.yml 
ansible-playbook 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: router_test.yml ****************************************************************************************************************************************************
1 plays in router_test.yml

PLAY [Simple test] ***********************************************************************************************************************************************************
META: ran handlers

TASK [Change hostname] *******************************************************************************************************************************************************
task path: /etc/ansible/router_test.yml:9
<192.168.200.1> attempting to start connection
<192.168.200.1> using connection plugin network_cli
<192.168.200.1> local domain socket does not exist, starting it
<192.168.200.1> control socket path is /root/.ansible/pc/66252cb75e
<192.168.200.1> 
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/bin/ansible-connection", line 106, in start
    self.connection._connect()
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/network_cli.py", line 336, in _connect
    self._terminal.on_become(passwd=auth_pass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/terminal/ios.py", line 78, in on_become
    raise AnsibleConnectionFailure('unable to elevate privilege to enable mode, at prompt [%s] with error: %s' % (prompt, e.message))
AnsibleConnectionFailure: unable to elevate privilege to enable mode, at prompt [None] with error: timeout trying to send command: enable

fatal: [192.168.200.1]: FAILED! => {
    "msg": "unable to elevate privilege to enable mode, at prompt [None] with error: timeout trying to send command: enable"
}

```
