### ISSUE TITLE
na_ontap_export_policy_rule - 'absent' example doesn't work

### ISSUE THREAD

**Issue by fboux0** [ansible/ansible#51445]
##### SUMMARY

https://docs.ansible.com/ansible/latest/modules/na_ontap_export_policy_rule_module.html#na-ontap-export-policy-rule-module says we can delete with:
```
- name: Delete ExportPolicyRule
  na_ontap_export_policy_rule:
    state: absent
    policy_name: default123
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
```
This fails with
```
 msg: 'missing required arguments: vserver'
```
When I add the vserver it fails with
```
 msg: 'state is absent but all of the following are missing: client_match'
```
When I finally add a client_match (that exists) it does delete it. 
```
- name: Delete ExportPolicyRule
  na_ontap_export_policy_rule:
    state: absent
    policy_name: default123
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: VS0
    client_match: someserver.example.com
```
Specifying a specific rule index to delete without specifying a client_match also doesn't work. 
So either you can only delete specific client_match and the docs need updating to the example above or we can delete rules some other way that is not clear from the documentation?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

na_ontap_export_policy_rule

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
```
