### ISSUE TITLE
Support groups in command line inventory (host_list.py)

### ISSUE THREAD

**Issue by abitrolly** [ansible/ansible#51448]
##### SUMMARY

I am trying to init `newhost` with playbook for `[master]` group, and there is no way to specify the group for the host from command line without adding the host to inventory. This is what is needed.

    ansible-playbook -i "[master]newhost," playbook.yml

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/host_list.py

##### ADDITIONAL INFORMATION

```yaml
hosts: master
tasks:
- apt:
    name:
    - git
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/galaxy/data/apb/tasks/main.yml.j2](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/tasks/main.yml.j2)
* [lib/ansible/modules/packaging/os/apt.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)
* [lib/ansible/modules/source_control/git.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py)
* [lib/ansible/parsing/utils/yaml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Specifying group membership on the command line is not something we plan to implement. It is better to use the `add_host` module to temporarily add the host(s) to a group.

```yaml
- hosts: localhost
  connection: local
  become: no
  tasks:
    - add_host:
        name: newhost
        groups: master

- import_playbook: play.yml
```

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
