### ISSUE TITLE
gcp_container_node_pool module error with location field

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#51447]
##### SUMMARY
Container cluster pools not supported by module when using regions vs zone.
`https://container.googleapis.com/v1/projects/{{ project }}/locations/{{ region }}/clusters/{{ cluster_pool_name }}`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_container_node_pool

##### ANSIBLE VERSION
```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eanderson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /home/eanderson/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
```paste below
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
  gcp_container_node_pool:
    name: "node-pool-{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
    initial_node_count: 1
    cluster:
      name: "{{ gcp_k8s_cluster }}"
    autoscaling:
      enabled: yes
      min_node_count: 2
      max_node_count: 200
    config:
      disk_size_gb: 40
      image_type: UBUNTU
      machine_type: n1-standard-2
      oauth_scopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/service.management
        - https://www.googleapis.com/auth/servicecontrol
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
    zone: us-west1
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_service_account_file }}"
    state: present

```

##### EXPECTED RESULTS

 Expect that we could use locations instead of just zone because clusters should usually span multiple zones for high availability features of kubernetes.

##### ACTUAL RESULTS

```paste below
{"changed": false, "msg": "GCP returned error: {u'error': {u'status': u'INVALID_ARGUMENT', u'message': u\"'zone' field cannot be used to access GKE regional clusters. Use 'name' or 'parent' fields instead.\", u'code': 400}}"}
```
