### ISSUE TITLE
na_ontap_export_policy_rule - not idempotent

### ISSUE THREAD

**Issue by fboux0** [ansible/ansible#51441]
##### SUMMARY
I'm trying to allow hostnames in NetApp based on their Ansible group . 
When rerunning a playbook the na_ontap_export_policy_rule module creates a new rule instead of overwriting the current if the client_match is changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
na_ontap_export_policy_rule 

##### ANSIBLE VERSION

```
ansible 2.7.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

NetApp Release 9.3P6
##### STEPS TO REPRODUCE

```yaml

- name: "Allowing one server"
  na_ontap_export_policy_rule:
    state: present
    policy_name: test
    client_match: server.example.com
    ro_rule: any
    rw_rule: any
    super_user_security: none
    protocol: any
    allow_suid: false
    vserver: VS0
    hostname: netappserver
    username: admin
    password: ****
    rule_index: 999
  delegate_to: localhost

- name: "Allowing two servers"
  na_ontap_export_policy_rule:
    state: present
    policy_name: test
    client_match: server.example.com, secondserver.example.com
    ro_rule: any
    rw_rule: any
    super_user_security: none
    protocol: any
    allow_suid: false
    vserver: VS0
    hostname: netappserver
    username: admin
    password: ****
    rule_index: 999
  delegate_to: localhost
```

##### EXPECTED RESULTS

Since I'm specifying rule_index 999 I expect to see one single rule 999 that has clients "server.example.com, secondserver.example.com"

##### ACTUAL RESULTS

Instead, looking in OnCommand I see two rules:

```paste below
999 server.example.com, secondserver.example.com
1000 server.example.com
```
If you run it again with client_match: foo.bar.com you end up with:

```paste below
999 foo.bar.com
1000 server.example.com, secondserver.example.com
1001 server.example.com
```
