### ISSUE TITLE
Incompatibility between mysql and zlib package raises traceback in mysql_user 

### ISSUE THREAD

**Issue by hwali** [ansible/ansible#51458]
I have an issue creating user over Ansible using python connecting DB,Please if someone cant support over this .yml,.py &,wsgi code pasted below
Got below error
TASK [create demo user] **********************************************************************************************************
fatal: [db01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to db01 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_BpAAVO/ansible_module_mysql_user.py\", line 218, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n", "msg": "MODULE FAILURE", "rc": 0}
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=
---
- hosts: db01
  tasks:
    - name: install dependencies tool
      yum: name={{item}} state=latest update_cache=yes
      with_items:
          - MySQL-python
          -  mysql-devel
          -  python-devel

    - name: install mysql-server
      yum: name=mysql-server state=installed update_cache=yes

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db: name=demo state=present

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
import os, socket

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URI']
db = SQLAlchemy(app)
hostname = socket.gethostname()

@app.route('/')
def index():
  return 'Hello, from sunny %s!\n' % hostname

@app.route('/db')
def dbtest():
  try:
      db.create_all()
  except Exception as e:
      return e.message + '\n'
  return 'Database Connected from %s!\n' % hostname

if __name__ == '__main__':
  app.run()
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
activate_this = '/var/www/demo/.venv/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import os
os.environ['DATABASE_URI'] = 'mysql://demo:demo@db01/demo'

import sys
sys.path.insert(0, '/var/www/demo')

from demo import app as application
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Flask==0.10.1
Flask-SQLAlchemy==2.0

**Comment by ansibot** [comment]
@hwali: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hwali** [comment]
##### SUMMARY

I have an issue creating user over Ansible using python connecting DB,Please if someone cant support over this .yml,.py &,wsgi code pasted below
Got below error
TASK [create demo user] **********************************************************************************************************
fatal: [db01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to db01 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_BpAAVO/ansible_module_mysql_user.py\", line 218, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n", "msg": "MODULE FAILURE", "rc": 0}
##### ISSUE TYPE

 - Feature Idea
##### COMPONENT NAME

mysql_user, create demo user in mysql
##### ANSIBLE VERSION

```
[root@osboxes9 ~]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```
[defaults]
inventory = ./dev
```

##### OS / ENVIRONMENT
[root@osboxes9 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
[root@osboxes9 ~]# 


##### STEPS TO REPRODUCE

i dont sure about this

```yaml
---
- hosts: db01
  tasks:
    - name: install dependencies tool
      yum: name={{item}} state=latest update_cache=yes
      with_items:
          - MySQL-python
          -  mysql-devel
          -  python-devel

    - name: install mysql-server
      yum: name=mysql-server state=installed update_cache=yes

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db: name=demo state=present

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted

```



##### EXPECTED RESULTS


##### ACTUAL RESULTS



```paste below
[root@osboxes9 ansible2]# ansible-playbook playbooks/database.yml 

PLAY [db01] **********************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************
ok: [db01]

TASK [install dependencies tool] *************************************************************************************************
ok: [db01] => (item=[u'MySQL-python', u'mysql-devel', u'python-devel'])

TASK [install mysql-server] ******************************************************************************************************
ok: [db01]

TASK [ensure mysql started] ******************************************************************************************************
ok: [db01]

TASK [ensure mysql listening on all ports] ***************************************************************************************
ok: [db01]

TASK [create demo database] ******************************************************************************************************
ok: [db01]

TASK [create demo user] **********************************************************************************************************
fatal: [db01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to db01 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_BpAAVO/ansible_module_mysql_user.py\", line 218, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/etc/ansible/ansible2/playbooks/database.retry

PLAY RECAP ***********************************************************************************************************************
db01                       : ok=6    changed=0    unreachable=0    failed=1   

[root@osboxes9 ansible2]# 
```
