### ISSUE TITLE
add_host doesn't run on parallel hosts

### ISSUE THREAD

**Issue by sebmaynard** [ansible/ansible#5145]
add_host only seems to run on one of the hosts in a group, even when other tasks run for all hosts in the same group.

See this gist for the simplest example of this issue that I could create:
https://gist.github.com/sebmaynard/5195a97fd79cec8f3760/

Adding serial: 1 to the top play (which does the add_host) fixes the issue, but in my playbook where I'm using this, serial: 1 would be really unideal for speed reasons

Thanks to benno for helping me with this

**Comment by jctanner** [comment]
@sebmaynard ansible version?

**Comment by sebmaynard** [comment]
Running from a fresh pull of devel; I've also tried with 1.4.1 and both exhibit the same behaviour.

**Comment by sebmaynard** [comment]
Do you still need more info from me?

**Comment by mpdehaan** [comment]
Add host is something that is called a "bypass host loop" module.

This means it executes only once, ignoring the host loop.

It's not there to add the current host to more groups, but rather to add new hosts that are newly provisioned but not yet visible in inventory, such as the results of the ec2 module.

You'll want to use "group_by" in this case if you want to build dynamic groups.

In any event, feel free to stop by the mailing list if you'd like to discuss more.

Thanks!

**Comment by sebmaynard** [comment]
The hosts that I'm adding do in fact come from the ec2 module - I spawn new ec2 instances then use add_host to add them to appropriate groups. But I'm doing this on multiple controller hosts at once (hence my add_host needing to work in the hosts loop). I can't use group_by (I think?) as this adds the current host from the loop to a group, but I need to add {{ some_variable_assigned_from_ec2_spawn }} to a group (with variables).

**Comment by sebmaynard** [comment]
Apparently this was already requested here: https://github.com/ansible/ansible/issues/2963 but was closed as he worked around it; I too am "sort of" working around it by using serial: 1, but that's a cludge and slows down my playbook considerably. Thanks!

**Comment by marten** [comment]
I just bumped into the same issue. I tried doing something along the lines of (but split up into roles):

```
- name: Create VMs
  hosts: all
  gather_facts: no
  tasks:
    - command: xe vm-list name-label={{inventory_hostname}}
      register: vm_info
    - command: xe vm-install template=xyz new-name-label={{inventory_hostname}}
      when: vm_info.stdout == ""
    - add_host: name={{inventory_hostname}} groups=just_created
      when: vm_info.stdout == ""
- name: Install baseline config
  hosts: just_created
  remote_user: root
  roles: 
    - common
```

The issue I'm having is that you need to gather information to apply the `common` role, but you can't gather information from hosts that aren't running yet, so the first play seems to need `gather_facts: no`. Newly created VMs also don't have any users, so you need to initialize them while connecting as "root". However, after applying the common-role, we disable root login via ssh. So simply applying common to all hosts won't work.

If add_host works the way you say it does, then the documentation for that module could do with some large bold warnings, and better examples. As it stands, the example for the add_host module strongly suggests you should be able to use it to add a new ip to some group. It never states you can't do this twice on two hosts.
