### ISSUE TITLE
ignore_errors: true shows debugging output

### ISSUE THREAD

**Issue by sugitk** [ansible/ansible#51463]
##### SUMMARY

Regarding #39863 and #39868.  When `ignore_errors: true` is set in a task of a playbook, but if errors occurred the debug output is shown. Is it a desired behavior?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.6
  config file = None
  configured module search path = ['/Users/sugimura/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.6/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 18:04:55) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
  - shell: cat foo | grep bar
    ignore_errors: true
    #failed_when: false
    register: result
```

##### EXPECTED RESULTS

It should be the same as `failed_when: false` specified.

```
PLAY [localhost] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [shell] *************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

```

##### ACTUAL RESULTS

The result is here:

```
PLAY [localhost] *********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [localhost]

TASK [shell] *************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cat foo | grep bar", "delta": "0:00:00.006565", "end": "2019-01-30 09:14:50.556986", "msg": "non-zero return code", "rc": 1, "start": "2019-01-30 09:14:50.550421", "stderr": "cat: foo: No such file or directory", "stderr_lines": ["cat: foo: No such file or directory"], "stdout": "", "stdout_lines": []}
...ignoring

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by jdh239** [comment]
In my case, failed_when and changed_when do not work:
```
    - name: "Find the user_id for {{ user }}"
      set_fact:
        uid: "{{ (userinfo.json.users|selectattr('username','match',user)|list|first).user_id }}"
      ignore_errors: true
      failed_when: false
```

Result:
`TASK [Find the user_id for gomer] ********************************************************************************************************************************************************************************************************
fatal: [nagios]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: No first item, sequence was empty.\n\nThe error appears to have been in '/etc/ansible/role/purge_user/tasks/sample.yml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"Find the user_id for {{ user }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
...ignoring

`

**Comment by dagwieers** [comment]
Right, I don't think this is a good way of doing this. The expression could be failing for various reasons and this would not cover that. If you expect a list to be empty, you could evaluate this by doing:

```yaml
    - name: "Find the user_id for {{ user }}"
      set_fact:
        uid: "{{ (userinfo.json.users|selectattr('username','match',user)|list|first).user_id }}"
      when: userinfo.json.users|selectattr('username','match',user) != []
```

But it all depends what your doing in the larger picture, because this tends to look like we are programming in playbooks and that is to be avoided.

PS One of the things on my wishlist is to be able to nest multiple facts in a single `set_fact` call.
```yaml
- name: Set facts
  set_fact:
    users: '{{ (userinfo.json.users|selectattr('username','match',user)|list}}
    user: '{{ user[0] | default({ user_id: null})'
    uid: '{{ user.user_id }}'
```

Then you would have **uid** set to *None* in case it was not found. Now you need to do this in three separate `set_fact` steps. Although you could do this using `vars:`.

```yaml
- name: Do something with user
  set_fact:
    uid: '{{ user_id }}'
  vars:
    users: '{{ (userinfo.json.users|selectattr('username','match',user)|list}}
    user: '{{ user[0] | default({ user_id: null})'
    user_id: '{{ user.user_id }}'
```
I don't like that we have to do it like this, but it is a safer construction. Someone is working on a `dig` jinja filter that could be helpful in the future. https://github.com/ansible/ansible/pull/50706

```yaml
    - name: "Find the user_id for {{ user }}"
      set_fact:
        uid: "{{ (userinfo.json.users|selectattr('username','match',user) | dig(0, user_id) }}"
```
This would result in **uid** being set to *None* if there was no match.
