### ISSUE TITLE
VMware: support cluster_name in vmware_host_facts

### ISSUE THREAD

**Issue by karthi81** [ansible/ansible#51460]
##### SUMMARY

vmware_host_facts:
I'm trying to pull the all ESXi facts using cluster name instead of ESXi Name (User ID & Password) because handling of ESXi hosts and password for ESXi hosts are not always same across many clusters. Earlier version had option for Cluster Name and I think, it got removed with recent version. if I can pull the facts using cluster name again, it will be appreciated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 vmware

##### ANSIBLE VERSION

```
ansible 2.7.4
python version = 3.6.6 (default, Aug 13 2018, 18:24:23) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/opt/stackstorm/packs/dc_infra_ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_MODULE_PATH(/opt/stackstorm/packs/dc_infra_ansible/ansible.cfg) = ['/etc/ansible/library']
DEFAULT_REMOTE_USER(/opt/stackstorm/packs/dc_infra_ansible/ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(/opt/stackstorm/packs/dc_infra_ansible/ansible.cfg) = /opt/stackstorm/packs/dc_infra_ansible/.vault_pass
```

##### OS / ENVIRONMENT

```
- name: generating the facts for each cluster
    vmware_host_facts:
      username: "{{ vc_user }}"
      password: "{{ vc_password }}"
      #hostname: "{{ vc_name }}"
      hostname: "{{ inventory_hostname }}"
      validate_certs: false
    #delegate_to: localhost
    register: esxi_inventory
```

##### EXPECTED RESULTS

I am expecting to get the facts for all ESXi within given cluster name.

##### ACTUAL RESULTS

I do not have option to pass Cluster name and collect the facts for related ESXi hosts via VCenter but not via ESXi

```paste below

```
