### ISSUE TITLE
doas become method not working in FreeBSD 11

### ISSUE THREAD

**Issue by illogic-al** [ansible/ansible#51474]
##### SUMMARY
Using doas as the become_method in FreeBSD 11.1/11.2 does not work.
The reason, I believe, is that FreeBSD 11 doas has a `Password:` prompt by default.
Below you can see what I have in my `/usr/local/etc/doas.conf` file on FreeBSD 11.1 (I can confirm this is an issue in 11.0 also).

Reverting #16997 allows using doas on FreeBSD again. 
It seems like we might need a `doas_freebsd` in order to get this working for FreeBSD.

```
# wheel group can obtain elevated privs
permit setenv { -ENV PS1=$DOAS_PS1 SSH_AUTH_SOCK } :wheel
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
become

#### ANSIBLE VERSION
```
ansible 2.7.6
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.6/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Jan 13 2019, 12:50:15) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
```paste below
DEFAULT_BECOME_ASK_PASS(~/.ansible.cfg) = True
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = ['~/.ansible_hosts']
DEFAULT_REMOTE_PORT(~/.ansible.cfg) = 22
DEFAULT_REMOTE_USER(~/.ansible.cfg) = user
````

#### OS / ENVIRONMENT
From: Mac OS X 10.13.6
To: FreeBSD 11.1-RELEASE-p4 amd64

##### STEPS TO REPRODUCE
Use become feature in ansible playbook to get root privileges.

##### EXPECTED RESULTS
Expected  ansible to show password prompt but it did not until I reverted #16997

##### ACTUAL RESULTS
There is timeout waiting for the doas password prompt to show up.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/become.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/become.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
should be fixed by #50991

**Comment by illogic-al** [comment]
I’ll try to test today and verify.

**Comment by sivel** [comment]
@illogic-al The default in #50991 is still to match on `doas (`, however to get it to match a different prompt, you would set a different prompt to match:

```
        prompt_l10n:
            description:
                - List of localized strings to match for prompt detection
                - If empty we'll use the built in one
            default: []
            ini:
              - section: doas_become_plugin
                key: localized_prompts
            vars:
              - name: ansible_doas_prompt_l10n
            env:
              - name: ANSIBLE_DOAS_PROMPT_L10N
```

This can be done in ansible.cfg like:

```
[doas_become_plugin]
localized_prompts = Password:
```

Via a var in a YAML file like:

```
ansible_doas_prompt_l10n:
  - 'Password:'
```

Or via env var like:

```
ANSIBLE_DOAS_PROMPT_L10N="Password:" ansible-playbook ...
```

However it may just be a good idea for me to add `Password:` in there already, to match both `Password:` and `doas (`

needs_info
