### ISSUE TITLE
flatpak module fails to remove package on recent versions of flatpak

### ISSUE THREAD

**Issue by oolongbrothers** [ansible/ansible#51485]
##### SUMMARY

When removing a present flatpak, the removal would fail on recent version of flatpak.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

flatpak

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/.../Code/oolongbrothers/ansible/lib/ansible
  executable location = /home/.../Code/oolongbrothers/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Tested on Python 2/3, Ubuntu 16.04 and Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- flatpak:
    name: org.gnome.Characters
    state: present
- flatpak:
    name: org.gnome.Characters
    state: absent
```

##### EXPECTED RESULTS

The removal should proceed.

##### ACTUAL RESULTS

The module crashes with the following error from the flatpak CLI.:

```paste below
error: No ref chosen to resolve matches for '...'
```
