### ISSUE TITLE
unable to pass user of domain as authentication for cisco nxos

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/ansible#51486]
##### SUMMARY
Not able to connect to a cisco UCS device using netowerk_cli and user from the domain
but I can connect from terminal using ssh and same credentials: ssh ucs-DOMAIN\\x@ucshost
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.7.5
  config file = /Volumes/diskE/Users/msn3/.ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Using /Volumes/diskE/Users/x/.ansible.cfg as config file
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/Volumes/diskE/Users/x/.ansible.cfg) = -o ControlPersist=300s -o ControlMaster=auto
DEFAULT_ACTION_PLUGIN_PATH(/Volumes/diskE/Users/x/.ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(/Volumes/diskE/Users/x/.ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/callbacks']
DEFAULT_CALLBACK_WHITELIST(/Volumes/diskE/Users/x/.ansible.cfg) = [u'profile_tasks', u'logstash']
DEFAULT_LOG_PATH(/Volumes/diskE/Users/x/.ansible.cfg) = /Volumes/diskE/Users/msn3/log/DS/svc_worker.log
DEFAULT_MODULE_PATH(/Volumes/diskE/Users/x/.ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
DEFAULT_ROLES_PATH(/Volumes/diskE/Users/x/.ansible.cfg) = [u'/Volumes/diskE/Users/x/Documents/ansible-workspace/ds-roles']
DEFAULT_STDOUT_CALLBACK(/Volumes/diskE/Users/x/.ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/Volumes/diskE/Users/x/.ansible.cfg) = /Volumes/diskE/Users/x/x.txt
HOST_KEY_CHECKING(/Volumes/diskE/Users/x/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

macos try to connect to cisco UCS
##### STEPS TO REPRODUCE

```yaml
---

- hosts: ucshost
  vars:
    ansible_connection: network_cli
    ansible_network_os: nxos
    ansible_user: 'ucs-DOMAIN\\x'
    ansible_ssh_pass: mypass
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: mypass
  tasks:
     - name: collect output from nxos device
       nxos_command:
         commands:
           - show system detail
       register: output

     - name: print details
       debug: var=output
```

##### EXPECTED RESULTS

expected to see the results of the playbook

##### ACTUAL RESULTS

it returns error

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/bin/ansible-connection", line 106, in start
    self.connection._connect()
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 307, in _connect
    ssh = self.paramiko_conn._connect()
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 249, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 365, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
AnsibleConnectionFailure: Authentication failed.

fatal: [ucshost]: FAILED! => {
    "msg": "Authentication failed."
}
```
