### ISSUE TITLE
Win_DSC PSCredential conversion error for DSC module xFailoverCluster xCluster resource 

### ISSUE THREAD

**Issue by bradwilliamson** [ansible/ansible#51512]
##### SUMMARY

I am attempting to automate the creation of a failover cluster for SQL Server 2017.  When attempting to create the cluster and pass the domain credentials into the domainadministratocredential property on the dsc module xFailoverCluster (xCluster) I get the following 

[WARNING]: failed to cast property domainadministratorcredential from 'DOMAIN\USER' of type System.String to type
System.Management.Automation.PSCredential, the DSC engine may ignore this property with an invalid cast

fatal: [: FAILED! => {
    "changed": false, 
    "module_version": "1.12.0.0", 
    "msg": "Convert property 'domainadministratorcredential' value from type 'STRING' to type 'INSTANCE' failed\r\n At line:10, char:2\r\n Buffer:\r\nirectResourceAccess\";\n};^\n\ninsta\r\n", 
    "reboot_required": false
}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_dsc ansible module
xFailoverCluster win_psmodule

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  python version = 2.7.14 (default, Mar 14 2018, 16:45:33) [GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)]



```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 2016 Server 
SQL Server 2017
Fedora 27 workstation and Red Hat Jenkins Slaves

##### STEPS TO REPRODUCE

```yaml

- name: Setup the xRegistry module
  win_psmodule:
    name: xFailOverCluster
    state: present

- name: Add Failover clustering Feature
  win_feature:
    name: Failover-clustering
    state: present

- name: Add Failover clustering powershell
  win_feature:
    name: RSAT-Clustering-Powershell
    state: present

- name: Add Failover clustering powershell
  win_feature:
    name: RSAT-Clustering-CmdInterface
    state: present


- name: Setup Cluster Resource on primary/first node
  win_dsc:
    resource_name: xCluster
    name: '{{ clustername }}'
    staticipaddress: '{{ clusteripaddress }}'
    domainadministratorcredential: '{{ ansible_user }}'
  when: node1 is defined and node1





```

##### EXPECTED RESULTS

Convert to PsCredential

##### ACTUAL RESULTS

Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_dsc.ps1
<ipaddress> ESTABLISH WINRM CONNECTION FOR USER: domain\username on PORT 5985 TO ipaddress
EXEC (via pipeline wrapper)
 [WARNING]: failed to cast property domainadministratorcredential from 'domain\user' of type System.String to type
System.Management.Automation.PSCredential, the DSC engine may ignore this property with an invalid cast

fatal: []: FAILED! => {
    "changed": false, 
    "module_version": "1.12.0.0", 
    "msg": "Convert property 'domainadministratorcredential' value from type 'STRING' to type 'INSTANCE' failed\r\n At line:10, char:2\r\n Buffer:\r\nirectResourceAccess\";\n};^\n\ninsta\r\n", 
    "reboot_required": false

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_dsc.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_dsc.ps1)
* [lib/ansible/modules/windows/win_dsc.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_dsc.py)
* [lib/ansible/modules/windows/win_psmodule.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_psmodule.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @dlazz @jborean93 @jhawkesworth @nitzmahone @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
When you define a PSCredential DSC option you need to define it in 2 parts. We have this documented at https://docs.ansible.com/ansible/latest/user_guide/windows_dsc.html#pscredential but in your case you need to do;

```
- name: Setup Cluster Resource on primary/first node
  win_dsc:
    resource_name: xCluster
    name: '{{ clustername }}'
    staticipaddress: '{{ clusteripaddress }}'
    domainadministratorcredential_username: '{{ ansible_user }}'
    domainadministratorcredential_password: '{{ ansible_password }}'
```
