### ISSUE TITLE
looping is apparently completely broken in 2.7

### ISSUE THREAD

**Issue by sean-abbott** [ansible/ansible#51513]
##### SUMMARY
When trying to use with_filetree or lookup('filetree'... or query('filetree'... nothing works. Everything claims item has not src, and in every way I know how to debug item does, indeed, have that src.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
loop, with_filetree

##### ANSIBLE VERSION
```
ansible 2.7.6
  config file = /home/sabbott/workspace/platform/configuration_orchestration/ansible.cfg
  configured module search path = ['/home/sabbott/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sabbott/.virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/sabbott/.virtualenvs/ansible/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

(also happened in 2.7.1)

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/home/sabbott/workspace/platform/configuration_orchestration/ansible.cfg) = ['/home/sabbott/workspace/ansible_roles']
HOST_KEY_CHECKING(/home/sabbott/workspace/platform/configuration_orchestration/ansible.cfg) = False
INVENTORY_ENABLED(/home/sabbott/workspace/platform/configuration_orchestration/ansible.cfg) = ['script', 'ini', 'constructed']

```

##### OS / ENVIRONMENT
ubuntu 18.04 control, coreos target

##### STEPS TO REPRODUCE

```yaml
- name: "grab filetree on this because I hate everything"
  debug:
    var: item.src
  loop: "{{query('filetree', 'files/dashboard_templates/')}}"

- name: "copy in dashboards"
  become: yes
  tags:
    - grafana_dashboards
  copy:
    src: "{{ item.src }}"
    dest: "/etc/grafana/dashboards/{{ item.path }}"
    owner: "root"
    mode: "0644"
  loop: "{{lookup('filetree', 'files/dashboard_templates/', wantlist=True)}}"
```

```
$ find files/dashboard_templates
files/dashboard_templates
files/dashboard_templates/platform_aws
files/dashboard_templates/platform_aws/plat_1635_service.json
files/dashboard_templates/platform_aws/aws_ec2_coredns.json
files/dashboard_templates/platform_aws/concourse.json
files/dashboard_templates/platform_aws/aws_elb__alb_services.json
files/dashboard_templates/platform_aws/coredns.json
files/dashboard_templates/product_dev
files/dashboard_templates/product_prod
files/dashboard_templates/product_prod/node_exporter_lite.json
```

##### EXPECTED RESULTS
The files will get copy into the target at those directories

##### ACTUAL RESULTS

```
...much output...
ok: [10.x.x.x] => (item={'root': '/home/sabbott/workspace/ansible_roles/aws_grafana_config/files/dashboard_templates/', 'path': 'product_prod/node_exporter_lite.json', 'state': 'file', 'src': '/home/sabbott/workspace/ansible_roles/aws_grafana_config/files/dashboard_templates/product_prod/node_exporter_lite.json', 'uid': 1001, 'gid': 1001, 'owner': 'sabbott', 'group': 'sabbott', 'mode': '0644', 'size': 14447, 'mtime': 1548884543.5617557, 'ctime': 1548884543.5697556}) => {
    "item": {
        "ctime": 1548884543.5697556,
        "gid": 1001,
        "group": "sabbott",
        "mode": "0644",
        "mtime": 1548884543.5617557,
        "owner": "sabbott",
        "path": "product_prod/node_exporter_lite.json",
        "root": "/home/sabbott/workspace/ansible_roles/aws_grafana_config/files/dashboard_templates/",
        "size": 14447,
        "src": "/home/sabbott/workspace/ansible_roles/aws_grafana_config/files/dashboard_templates/product_prod/node_exporter_lite.json",
        "state": "file",
        "uid": 1001
    },
    "item.src": "/home/sabbott/workspace/ansible_roles/aws_grafana_config/files/dashboard_templates/product_prod/node_exporter_lite.json"
}

TASK [aws_grafana_config : copy in dashboards] *******************************************************************************************************************************************************************************************************************************************
fatal: [[10.x.x.x]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'src'\n\nThe error appears to have been in '/home/sabbott/workspace/ansible_roles/aws_grafana_config/tasks/main.yml': line 59, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"copy in dashboards\"\n  ^ here\n"}
fatal: [[10.x.x.x]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'src'\n\nThe error appears to have been in '/home/sabbott/workspace/ansible_roles/aws_grafana_config/tasks/main.yml': line 59, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"copy in dashboards\"\n  ^ here\n"}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The issue here, is that `filetree` also matches directories.  When `state` is `directory`, there is no `src` attribute.

You will need to add a `when` statement to skip dirs:

```
- name: "copy in dashboards"
  copy:
    src: "{{ item.src }}"
    dest: "./dashboards/{{ item.path }}"
  loop: "{{lookup('filetree', 'files/dashboard_templates/', wantlist=True)}}"
  when: item.state == 'file'
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
