### ISSUE TITLE
[ec2 module] spot instance request stay opened when module exit with timeout

### ISSUE THREAD

**Issue by vutkin** [ansible/ansible#51534]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ec2` module
##### ANSIBLE VERSION

```paste below
ansible 2.5.14
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/user/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/user/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey -o ControlPath=/var/ans/%%h
ANSIBLE_SSH_CONTROL_PATH(/home/user/.ansible.cfg) = /var/ans/%%h
DEFAULT_MODULE_PATH(/home/user/.ansible.cfg) = [u'/home/user/.local/lib/python2.7/site-packages/custom_ansible']
DEFAULT_TIMEOUT(/home/user/.ansible.cfg) = 30
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/home/user/.ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/user/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

```yaml
- name: Start Windows instances
      ec2:
        region: '{{ item.aws_region }}'
        image: '{{ item.aws_image_id }}'
        instance_type: '{{ item.instance_type }}'
        group: '{{ item.aws_sec_group }}'        
        assign_public_ip: '{{ item.assign_public_ip | default(True) }}'
        wait: True
        wait_timeout: '{{ item.wait_timeout | default(600) }}'
        instance_tags:
          instance: '{{ item.name }}'
          Name: '{{ item.name }}'
        vpc_subnet_id: '{{ item.vpc_subnet_id }}'
        spot_price: '{{ item.spot_price }}'
        spot_wait_timeout: '{{ item.wait_timeout | default(600) }}'
        user_data: "{{ ec2_user_data }}"
        exact_count: 1
        count_tag:
          instance: '{{ item.name }}'
      register: ec2
      loop: '{{ molecule_yml.platforms }}'
```

https://github.com/lean-delivery/ansible-role-java/blob/develop/molecule/resources/provisioning/winrm/create.yml

##### EXPECTED RESULTS

Spot request should be cancelled/expired when module failed.

##### ACTUAL RESULTS

Spot request stay in `open` state: default end date for `ValidUntil` is 7 days from the current date.

https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-instances.html
```
ValidUntil -> (timestamp)
The end date of the request, in UTC format (for example, YYYY -MM -DD T*HH* :MM :SS Z). If this is a one-time request, it remains active until all instances launch, the request is canceled, or this date is reached. If the request is persistent, it remains active until it is canceled or this date is reached. The default end date is 7 days from the current date.
```

```paste below
changed: [localhost] => {
    "changed": true,
    "instance_ids": [],
    "instances": [],
    "invocation": {
        "module_args": {
            "assign_public_ip": false,
            "aws_access_key": null,
            "aws_secret_key": null,
            "count": 1,
            "count_tag": "{'instance': 'test'}",
            "ebs_optimized": false,
            "ec2_url": null,
            "exact_count": 1,
            "group": [
                "default"
            ],
            "group_id": null,
            "id": null,
            "image": "ami-9887c6e7",
            "instance_ids": null,
            "instance_initiated_shutdown_behavior": null,
            "instance_profile_name": null,
            "instance_tags": {
                "Name": "test",
                "instance": "test",
                "ssh_user": "centos"
            },
            "instance_type": "m5.large",
            "kernel": null,
            "key_name": "XXXX",
            "monitoring": false,
            "network_interfaces": null,
            "placement_group": null,
            "private_ip": null,
            "profile": null,
            "ramdisk": null,
            "region": null,
            "security_token": null,
            "source_dest_check": true,
            "spot_launch_group": null,
            "spot_price": "0.01",
            "spot_type": "one-time",
            "spot_wait_timeout": "60",
            "state": "present",
            "tenancy": "default",
            "termination_protection": null,
            "user_data": null,
            "validate_certs": true,
            "volumes": null,
            "vpc_subnet_id": "subnet-XXXX",
            "wait": false,
            "wait_timeout": "300",
            "zone": null
        }
    },
    "tagged_instances": []

```
