### ISSUE TITLE
'loop' with 'lookup' ignores 'when' statement

### ISSUE THREAD

**Issue by bbl** [ansible/ansible#51542]
##### SUMMARY

The `when` statement is ignored when used with the `lookup` plugin along with the `loop` statement.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
```

##### OS / ENVIRONMENT

```bash
# cat /proc/version 
Linux version 3.10.0-862.14.4.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Wed Sep 26 15:12:11 UTC 2018
```

##### STEPS TO REPRODUCE

An example configuration listed bellow:

```yaml
- name: "Create a custom PV"
  openshift_raw:
    kubeconfig: "/tmp/conf"
    state: "present"
    namespace: "test-ns"
    definition: "{{ item }}"
  loop: "{{ lookup('template', '{{custom_pv}}') | from_yaml_all | list }}"
  when: custom_pv != ""
```
##### EXPECTED RESULTS

Expecting that this task will be skipped.

##### ACTUAL RESULTS

The `loop` expands and evaluates the `lookup`. The `when` statement is ignored.

```paste below
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <type 'exceptions.IOError'>, original message: [Errno 21] Is a directory: '/tmp/infra/ansible/roles/myrole/templates/'"}
```
