### ISSUE TITLE
win_dsc module: DSC resource MSFT_SqlSetup  failed to execute Test-TargetResource functionality with error message: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by MarekSarad** [ansible/ansible#51543]
##### SUMMARY
When I try to install SQL server with win_dsc resource it is failing with an error:
```
{
    "_ansible_parsed": true,
    "module_version": "12.2.0.0",
    "_ansible_no_log": false,
    "changed": false,
    "reboot_required": false,
    "msg": "PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource returned false after calling Set-TargetResource. "
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_dsc; SqlServerDSC; Resource: SQL Setup

##### ANSIBLE VERSION

```paste below
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']                                                          
~

```
##### OS / ENVIRONMENT

Target is Windows Server 2012 R2, SQL versionI try to install is SQL 2014
##### STEPS TO REPRODUCE

I am trying to install SQL server using win_dsc module. I am able to complete installation using native DSC configuration on that server as well as using Invoke-DSCResource cmdlet. It only fails when executed from Ansible . 

```yaml
# This playbook ensures dsc modules are installed and installs SQL Server

- name: Powershell | Install Required Powershell Modules
  debugger: on_failed
  hosts: all

  tasks:

  #- win_psmodule: name={{ item }} state=present
  #  with_items:
  #    - SQLServerDsc
  #    - StorageDsc
  #    - ServerManager
  #    - dbatools
  #    - xNetworking

  - win_dsc:
      resource_name: SQLSetup
      Action: Install
      UpdateEnabled: False
      SourcePath: "D:\\Temp\\2014 Enterprise x64"
      InstanceName: "SPDEV"
      InstallSharedDir: "C:\\Program Files\\Microsoft SQL Server"
      InstallSharedwowDir: "C:\\Program Files (x86)\\Microsoft SQL Server"
      InstanceDir: "C:\\Program Files\\Microsoft SQL Server"
      SQLUserDBDir: "D:\\SQL\\Data"
      SQLUserDBLogDir: "D:\\SQL\\DataLogs"
      SQLTempDBDir: "D:\\SQL\\TempDB"
      SQLTempDBLogDir: "D:\\SQL\\TempDBLogs"
      Features: "SQLENGINE, SSMS,ADV_SSMS"
      SQLCollation: "Latin1_General_CI_AS_KS_WS"
      BrowserSvcStartupType: "Automatic"
      SQLSysAdminAccounts: "Domain\\Group"
      PsDscRunAsCredential_username: "Domain\\Account"
      PsDscRunAsCredential_password: "PasswordRemoved"
    no_log: false

```

##### EXPECTED RESULTS
SQL is installed. 

##### ACTUAL RESULTS

I get an error:
{
    "_ansible_parsed": true,
    "module_version": "12.2.0.0",
    "_ansible_no_log": false,
    "changed": false,
    "reboot_required": false,
    "msg": "PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource returned false after calling Set-TargetResource. "
}

```paste below
What 'verbatim' should be here? I am running that playbook from AWX. 
```
I have dome some troubleshooting and seems the problem is with test method. 
https://github.com/PowerShell/SqlServerDsc/issues/1273 

But when I run this from PS on the target server everything seems to be fine
```
if (-not $credential) {
    $password = "PassRemoved" | ConvertTo-SecureString -asPlainText -Force
$username = "Domain\InstallAccount"
[PSCredential] $credential = New-Object System.Management.Automation.PSCredential($username,$password)
}
$params = @{}

$params = @{
            Action = "Install"
            InstanceName          = "INST2015"
            Features              = "SQLENGINE,SSMS,ADV_SSMS"
            SQLCollation          = "Latin1_General_CI_AS_KS_WS"
            SQLSysAdminAccounts   = [Array]"TestAccount, Domain\someaccount"
            InstallSharedDir      = "C:\Program Files\Microsoft SQL Server"
            InstallSharedWOWDir   = "C:\Program Files (x86)\Microsoft SQL Server"
            InstanceDir           = "C:\Program Files\Microsoft SQL Server"
            InstallSQLDataDir     = "D:\MSSQL\Data"
            SQLUserDBDir          = "D:\MSSQL\Data"
            SQLUserDBLogDir       = "D:\MSSQL\DataLogs"
            SQLTempDBDir          = "D:\MSSQL\TempDBData"
            SQLTempDBLogDir       = "D:\MSSQL\TempDBDataLogs"
            SQLBackupDir          = "D:\MSSQL\Backup"
            SourcePath            = "D:\Temp\2014 Enterprise x64"
            UpdateEnabled         = "False"          
            BrowserSvcStartupType = "Automatic"
            PsDscRunAsCredential  = $credential
}

$params.GetType()

Invoke-DscResource -Name SQLSetup -ModuleName SQLServerDSC -Verbose -Method Test -Property $params 
```

What other troubleshooting steps I  can take to figure out what is wrong (I am fairly new to Ansible, but have bit of experience with DSC itself)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/setup.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/setup.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hanssonsebastian** [comment]
Hi, I'm also getting this type of error. Atm I'm ignoring the error during the play because the SQL log says it passed the installation without any errors.

**Comment by MarekSarad** [comment]
@jborean93 Thank you for comments (especially the side notes as I am a newbie to Ansible so they are very useful). I have tried your suggestion but same error was returned. 

I tried as well remove  it completely (so only the set up account would be added to SysAdmin Group at least looking at the DSC code)  but it this case same error was returned as well.

**Comment by jborean93** [comment]
Ok I finally got round to start looking at this issue, for a start I've run the following playbook to reproduce this issue on Server 2019.

```
---
- hosts: vagrant-windows
  gather_facts: no
  tasks:
  - name: install DSC resource
    win_psmodule:
      name: SqlServerDsc
      state: present

  - name: download installer
    win_get_url:
      url: https://download.microsoft.com/download/5/2/2/522EE642-941E-47A6-8431-57F0C2694EDF/SQLServer2017-SSEI-Eval.exe
      dest: C:\temp\sql-setup.exe
      force: no

  - name: download install media
    win_command: C:\temp\sql-setup.exe /ENU /Action=Download /HideProgressBar /MediaPath=C:\temp\SQL /MediaType=ISO  /Quiet
    args:
      creates: C:\temp\SQL

  - name: fine ISO in downloaded media
    win_find:
      paths: C:\temp\SQL
      patterns: '*.iso'
      file_type: file
    register: iso_find

  - name: mount image
    win_disk_image:
      image_path: '{{ iso_find.files[0].path }}'
      state: present
    register: mount_info

  - name: install SQL Server
    win_dsc:
      resource_name: SQLSetup
      Action: Install
      UpdateEnabled: False
      SourcePath: '{{ mount_info.mount_paths[0] }}'
      InstanceName: SPDEV
      InstallSharedDir: C:\Program Files\Microsoft SQL Server
      InstallSharedwowDir: C:\Program Files (x86)\Microsoft SQL Server
      InstanceDir: C:\Program Files\Microsoft SQL Server
      SQLUserDBDir: C:\SQL\Data
      SQLUserDBLogDir: C:\SQL\DataLogs
      SQLTempDBDir: C:\SQL\TempDB
      SQLTempDBLogDir: C:\SQL\TempDBLogs
      Features: SQLENGINE, SMSS, ADV_SMSS
      SQLCollation: Latin1_General_CI_AS_KS_WS
      BrowserSvcStartupType: Automatic
      SQLSysAdminAccounts: BUILTIN\Administrators
      PsDscRunAsCredential_username: '{{ ansible_user }}'
      PsDscRunAsCredential_password: '{{ ansible_password }}'
```

Now that I've replicated the issue I will play around with it a bit more to figure out why it is happening.

**Comment by jborean93** [comment]
So after looking into this a bit more I think I've figured out the issue. I was able to debug this locally and found that `win_dsc` is properly casting values like `SQLSysAdminAccounts` to a `String[]` as expected by that property. The issue at handle is due to the space in the `Features` key that you have set `Features: "SQLENGINE, SSMS,ADV_SSMS"`.

Looking at the code we can see that the `Features` property is set as a `String` https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L773-L775 so the value for this will be `SQLENGINE, SSMS,ADV_SSMS`. Further down in the method we can see that it splits the features by `,`, verifies that `ADV_SMSS` or `SSMS` is not set when the SQL version is 13 or 14 then adds each feature to be installed if it's not already present https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L1069-L1085. The trouble here is that they are splitting by `,` but are not trimming any whitespace so the ultimate feature list will be `SQLENGINE, SSMS,ADV_SSMS` and the SQL server setup process does not like that whitespace.

I manually ran the DSC resource with these parameters, including the space, and was able to see that it also fails with the same error message. Adding the `-Verbose` flag to the `Invoke-DscResource` cmdlet I was able to see that the SQL server setup was actually running but it didn't show me the output. I was able to see it had a non 0 or 3010 exit code when looking at the warning messages. From there I looked at the `Summary.txt` at `C:\Program Files\Microsoft SQL Server\140\Setup Bootstrap\Log` the SQL installer produces and found the error around the invalid Feature parameter.

There's definitely some room for improvement in the error message when it comes to the `SQLSetup` DSC resource as they just call `Write-Warning` on an error from the installer instead of failing which subsequently means it fails when they go to test the resource hence the error we currently get.

On our side, it's shown that we should be looking at the warning output and bringing that back to the user as this would have helped you track down what may be happening. Putting this aside we are still at the mercy of the resource when it comes to the final error message returned.

**Comment by jborean93** [comment]
I've opened a PR https://github.com/ansible/ansible/pull/51927 that will return the warnings from the DSC run, in this case I was getting the following in the output

```
TASK [install SQL Server] ******************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:34
Using module file /Users/jborean/dev/ansible/lib/ansible/modules/windows/win_dsc.ps1
<127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 55986 TO 127.0.0.1
EXEC (via pipeline wrapper)
 [WARNING]: [WIN-RUEMJHAT927]:                            [[SqlSetup]DirectResourceAccess] Setup exited
with code '-2068578302'. Please see the 'Summary.txt' log file in the 'Setup Bootstrap\Log' folder.

fatal: [vagrant-win]: FAILED! => {
    "changed": false,
    "module_version": "12.2.0.0",
    "msg": "PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource returned false after calling Set-TargetResource. ",
    "reboot_required": false
}
```

This is really the best that Ansible can really do and in this case would have helped guide you to the proper location that contained the real error.

**Comment by hanssonsebastian** [comment]
Hey, Still getting this error but the Summary.txt says Final Result: Passed.
Don't know if it's the same issue or not. Anyone got any ideas?

```
- name: Check if installation media exists
  win_stat:
    path: '{{ installation_path }}\Media\SETUP.EXE'
  register: media_state

- name: Extract installation media
  win_shell: '{{ installation_path }}\SQLEXPRADV_x64_ENU.exe /X:{{ installation_path }}\Media /Q'
  when: media_state.stat.exists == False

  
- name: Powershell | Check for SQLServer DSC Powershell module
  win_psmodule:
    name: SQLServerDsc
    state: present

- name: Install SQL Server 2016 Express
  win_dsc:
     resource_name: SqlSetup
     Action: Install
     SourcePath: '{{ installation_path }}\Media'
     InstanceName: '{{ mssql_instance_name }}'
     InstanceDir: '{{ mssql_instance_path }}'
     InstallSQLDataDir: '{{ mssql_sqlinstalldata_path }}'
     SQLUserDBDir: '{{ mssql_sqluserdata_path }}'
     SQLUserDBLogDir: '{{ mssql_sqluserlog_path }}'
     SQLTempDBDir: '{{ mssql_sqltempDB_path }}'
     SQLTempDBLogDir: '{{ mssql_sqltempDBlog_path }}'
     SQLBACKUPDIR: '{{ mssql_sqlbackup_path }}'
     Features: '{{ mssql_features }}'
     SQLCollation: '{{ mssql_collation }}'
     BrowserSvcStartupType: '{{ mssql_browsersvc_mode }}'
     SuppressReboot: '{{ mssql_suppress_reboot }}'
     SecurityMode: '{{ mssql_security_mode }}'
     SAPwd_username: sa
     SAPwd_password: '{{ mssql_sa_password }}'
     SQLSysAdminAccounts: '{{ mssql_sysadmin_accounts }}'
```



#VARS in default.yml#
	 
```
installation_path: C:\Temp\Ansible\

mssql_instance_name: SQLEXPRESS
mssql_instance_path: D:\Microsoft SQL Server
mssql_sqlinstalldata_path: D:\Microsoft SQL Server
mssql_sqluserdata_path: D:\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\Data
mssql_sqluserlog_path: D:\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\Data
mssql_sqltempDB_path: D:\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\Data
mssql_sqltempDBlog_path: D:\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\Data
mssql_sqlbackup_path: D:\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\Backup
mssql_features: SQLENGINE,FULLTEXT,CONN,BC,SDK,SNAC_SDK
mssql_collation: Finnish_Swedish_CI_AS
mssql_browsersvc_mode: Automatic
mssql_suppress_reboot: False
mssql_security_mode: SQL
mssql_sa_password: MyPassword123
mssql_sysadmin_accounts: DOMAIN\myusername
```
