### ISSUE TITLE
xfconf-query failed with error: Failed to init libxfconf: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

### ISSUE THREAD

**Issue by poleguy** [ansible/ansible#51552]
##### SUMMARY

I tried to update the clock format in xfce4 and ansible xfconf returns an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

xfconf.py
Installed locally because Centos 7 only has ansible 2.7.5

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fpga/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
```
(no output produced)

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

```yaml
- name: set up time to show seconds and am/pm
  xfconf:
    channel: "xfce4-panel"
    property: "/plugins/plugin-5/digital-format"
    value_type: "string"
    value: "%r"
  become: True
  become_user: username
```

##### EXPECTED RESULTS

It should set the clock format. It should have the same effect as:
xfconf-query -c xfce4-panel -p /plugins/plugin-5/digital-format -s %r

##### ACTUAL RESULTS

It gives an error that seems to be related to trying to access the display. This seems to be a complication of the way xfce4 works rather than a bug in the ansible xfconf module per-se, but the effect is that this module is throwing an error. I can help fix it, but I'm not sure quite where to go next.

```paste below
xfconf-query failed with error: Failed to init libxfconf: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11.\n
```

**Comment by ansibot** [comment]
cc @jbenden
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by russoz** [comment]
Hi @poleguy ,

Can you please expand on your execution scenario? Are you trying to run this on a remote computer? Would you, by any chance, running this from the server console (vt1) rather than inside a terminal? Is there an user session open in the target host?

Cheers,
Alex

**Comment by NicolasLM** [comment]
Hi, not OP but I run into the same issue while trying to modify xfconf entries on a remote host via Anisble/SSH. There is a graphical session opened on the target host.

To get it to work I have to add an environment variable to the `xfconf-query` invocation, similar to https://askubuntu.com/a/1024588

**Comment by Helios-23** [comment]
> Hi, not OP but I run into the same issue while trying to modify xfconf entries on a remote host via Anisble/SSH. There is a graphical session opened on the target host.
> 
> To get it to work I have to add an environment variable to the `xfconf-query` invocation, similar to https://askubuntu.com/a/1024588

how did you solve this with ansible?
im using the xfconf: module to execute this
the 2 issues im having are: 
how to have anisble start a graphical session (or fake it enough that the xfconf-query will run)
how to set the environment variable so that the xfconf: module can use it.

**Comment by NicolasLM** [comment]
@Helios-23 I managed to solve my problem with:
```
- xfconf: [...]
  become: True
  become_user: [user with ID 1000]
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
```
