### ISSUE TITLE
`with_items` with invalid Jinja expression

### ISSUE THREAD

**Issue by junegunn** [ansible/ansible#5157]
``` yaml
- hosts: all
  vars:
    list:
      apple: red
      grass: green
      sky:   blue
  tasks:
  - debug:
      msg: '{{ item }}'
    with_items: list.values()

  - debug:
      msg: '{{ item }}'
    # Typo!!!
    with_items: list.valuess()
```

When a Jinja expression in `with_items` clause cannot be correctly evaluated, it is recognized as a list with that expression alone as a string literal. I find this behavior very confusing and error-prone.

```
TASK: [debug ] ****************************************************************
ok: [localhost] => (item=list.valuess()) => {
    "item": "list.valuess()",
    "msg": "list.valuess()"
}
```

So to be safe, I tried to be explicit with curly braces as follows,

``` yaml
  - debug:
      msg: '{{ item }}'
    with_items: '{{ undefined.values() }}'
```

but (understandably) it gives me a warning,

```
[WARNING]: It is unneccessary to use '{{' in loops, leave variables in loop
expressions bare.
```

and it fails but with an obscure message:

```
TASK: [debug ] ****************************************************************
fatal: [localhost] => with_items expects a list
```

So basically I believe that `with_items` should not evaluate a string as a single-item list, since I believe safety matters more than small flexibility in the syntax. I myself accidentally created a whole bunch of invalid files on production servers because of a slight mistake in the playbook (an undefined var), and it took me a while to figure out the cause.

What do you think? I understand that changing it is not an easy option as it will break backward-compatibility.
