### ISSUE TITLE
ec2_vol module not working as exprected

### ISSUE THREAD

**Issue by kernow** [ansible/ansible#51599]
##### SUMMARY

I wanted to start a conversation around this issue to work out the best way to resolve it. With the ec2_vol module as it currently stands if you try to create a volume with the same name as an existing one it will not create a new volume and will fail when it tried to attache it to an instance if the volume is already attache to another instance.

Having volumes with the same name is perfectly acceptable to AWS and it will do this without any troubles. The documentation for the module doesn't state it's behaviour correctly as it doesn't say the name must be unique.

The behaviour of the module is different when multiple volumes are created at the same time and when they are created at different times. When creating multiple volumes rapidly in the same play they will all be created. When creating one volume, then another in different plays the second volume will fail to be created.

This happens because the name is used as a unique key in the module. As the behaviour is inconsistent I think we should change the module behaviour so that it doesn't treat the name like a unique key as AWS fully supports this.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_vol

##### ANSIBLE VERSION

```paste below
2.7
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

This works when in the same ansible playbook run
```yaml
- ec2:
    keypair: "{{ keypair }}"
    image: "{{ image }}"
    zone: YYYYYY
    id: my_instance
    wait: yes
    count: 1
  register: ec2_first

- ec2_vol:
    instance: "{{ item.id }}"
    name: my_existing_volume_Name_tag
    device_name: /dev/xvdf
  with_items: "{{ ec2_first.instances }}"

- ec2:
    keypair: "{{ keypair }}"
    image: "{{ image }}"
    zone: YYYYYY
    id: my_instance
    wait: yes
    count: 1
  register: ec2_second

- ec2_vol:
    instance: "{{ item.id }}"
    name: my_existing_volume_Name_tag
    device_name: /dev/xvdf
  with_items: "{{ ec2_second.instances }}"
```

This fails when running separately, run 1 works
```
- ec2:
    keypair: "{{ keypair }}"
    image: "{{ image }}"
    zone: YYYYYY
    id: my_instance
    wait: yes
    count: 1
  register: ec2_first

- ec2_vol:
    instance: "{{ item.id }}"
    name: my_existing_volume_Name_tag
    device_name: /dev/xvdf
  with_items: "{{ ec2_first.instances }}"
```

Run 2 fails saying it cannot attach the volume as it's already attached to the previously created volume
```
- ec2:
    keypair: "{{ keypair }}"
    image: "{{ image }}"
    zone: YYYYYY
    id: my_instance
    wait: yes
    count: 1
  register: ec2_second

- ec2_vol:
    instance: "{{ item.id }}"
    name: my_existing_volume_Name_tag
    device_name: /dev/xvdf
  with_items: "{{ ec2_second.instances }}"
```

##### ACTUAL RESULTS

```paste below

```
