### ISSUE TITLE
VMware: vmware_guest ignore folder directive

### ISSUE THREAD

**Issue by gariels** [ansible/ansible#51591]
##### SUMMARY
The vmware_guest task tried to modify VMs of the same name at different VM folder.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = None
  configured module search path = ['/home/ariel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/ansible
  executable location = /var/tmp/ansible.201901/venv37/bin/ansible
  python version = 3.7.0 (default, Jul  6 2018, 11:13:41) [GCC 4.8.4]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Python 3.7.0
Target ESXi 5.5

##### STEPS TO REPRODUCE

```bash
ariel@lauenburg:/var/tmp/ansible.201901$ python3 -m venv venv37
ariel@lauenburg:/var/tmp/ansible.201901$ source venv37/bin/activate                                                                                                                                                                 
(venv37) ariel@lauenburg:/var/tmp/ansible.201901$ pip install ansible pyvmomi
(venv37) ariel@lauenburg:/var/tmp/ansible.201901$ ansible --version
ansible 2.7.6
  config file = None
  configured module search path = ['/home/ariel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/ansible
  executable location = /var/tmp/ansible.201901/venv37/bin/ansible
  python version = 3.7.0 (default, Jul  6 2018, 11:13:41) [GCC 4.8.4]
```

```yaml
-- ( playbook-1.yml ) ------>8---

- hosts:  localhost
  gather_facts:  true

  vars:
    esxi_hostname:  10.9.15.101
    vcenter_hostname:  10.9.15.120
    vcenter_username:  ansible_a@vsphere.local
    vcenter_password:  ansible_a

  tasks:
      - name: create VM, POTATO-A
        vmware_guest:
          esxi_hostname: "{{ esxi_hostname }}"
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          datacenter: MyLab
          folder: research/POTATO-A
          name: "{{ item }}"
          state: present
          guest_id: ubuntu64Guest
          disk:
            - size_gb: 4
              type: thin
              datastore: STORAGE1.iSCSI
          hardware:
              num_cpus: 1
              memory_mb: 2048
              scsi: lsilogic
              version: 10
          networks:
            - name: "STAGE1_genesis"
              device_type: vmxnet3
              start_connected: yes
            - name: "STAGE1_heartbeat"
              device_type: vmxnet3
              start_connected: no
            - name: "STAGE1_internal"
              device_type: vmxnet3
              start_connected: no
        delegate_to: localhost
        register: deploy_vm
        with_items:
          - unique-name-within-folder1
          - unique-name-within-folder2

-- ( playbook-1.yml ) ------>8---


-- ( playbook-2.yml ) ------>8---

- hosts:  localhost
  gather_facts:  true

  vars:
    esxi_hostname:  10.9.15.101
    vcenter_hostname:  10.9.15.120
    vcenter_username:  ansible_a@vsphere.local
    vcenter_password:  ansible_a

  tasks:
      - name: create VM, POTATO-B
        vmware_guest:
          esxi_hostname: "{{ esxi_hostname }}"
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          datacenter: MyLab
          folder: research/POTATO-B
          name: "{{ item }}"
          state: present
          guest_id: ubuntu64Guest
          disk:
            - size_gb: 4
              type: thin
              datastore: STORAGE1.iSCSI
          hardware:
              num_cpus: 2
              memory_mb: 2048
              scsi: lsilogic
              version: 10
          networks:
            - name: "STAGE1_genesis"
              device_type: vmxnet3
              start_connected: yes
            - name: "STAGE1_heartbeat"
              device_type: vmxnet3
              start_connected: no
            - name: "STAGE1_internal"
              device_type: vmxnet3
              start_connected: no
        delegate_to: localhost
        register: deploy_vm
        with_items:
          - unique-name-within-folder1
          - unique-name-within-folder2

-- ( playbook-2.yml ) ------>8---

```

##### EXPECTED RESULTS

playbook-2.yml to run successfully after the VMs from playbook-1.yml created and running.

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.7.6
  config file = None
  configured module search path = ['/home/ariel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/ansible
  executable location = /var/tmp/ansible.201901/venv37/bin/ansible-playbook
  python version = 3.7.0 (default, Jul  6 2018, 11:13:41) [GCC 4.8.4]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet yaml requirements, check plugin documentation if this is unexpected
Skipping due to inventory source not existing or not being readable by the current user
/etc/ansible/hosts did not meet ini requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet auto requirements, check plugin documentation if this is unexpected

PLAYBOOK: playbook-2.yml **********************************************************************************************************************************************************************************************************************
1 plays in /home/ariel/ansible-vmware_guest-bug/playbook-2.yml

PLAY [localhost] ******************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************************
task path: /home/ariel/ansible-vmware_guest-bug/playbook-2.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ariel
<127.0.0.1> EXEC /bin/sh -c 'echo ~ariel && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424 `" && echo ansible-tmp-1549001591.267002-200746254758424="` echo /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424 `" ) && sleep 0'
Using module file /var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /home/ariel/.ansible/tmp/ansible-local-5370jqglbtyk/tmpafeuk0n3 TO /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424/ /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/var/tmp/ansible.201901/venv37/bin/python3 /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ariel/.ansible/tmp/ansible-tmp-1549001591.267002-200746254758424/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [create VM, POTATO-B] ********************************************************************************************************************************************************************************************************************
task path: /home/ariel/ansible-vmware_guest-bug/playbook-2.yml:11
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ariel
<localhost> EXEC /bin/sh -c 'echo ~ariel && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651 `" && echo ansible-tmp-1549001592.2354808-47126017653651="` echo /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651 `" ) && sleep 0'
Using module file /var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /home/ariel/.ansible/tmp/ansible-local-5370jqglbtyk/tmp12jka74n TO /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/ /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/tmp/ansible.201901/venv37/bin/python3 /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/ > /dev/null 2>&1 && sleep 0'
failed: [localhost -> localhost] (item=unique-name-within-folder1) => {
    "changed": false,
    "item": "unique-name-within-folder1",
    "module_stderr": "/home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ariel/.ansible/tmp/ansible-tmp-1549001592.2354808-47126017653651/AnsiballZ_vmware_guest.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/home/ariel/.local/stow/python-3.7.0/lib/python3.7/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/home/ariel/.local/stow/python-3.7.0/lib/python3.7/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_vmware_guest_payload_k6tx_kmj/__main__.py\", line 2396, in <module>\n  File \"/tmp/ansible_vmware_guest_payload_k6tx_kmj/__main__.py\", line 2351, in main\n  File \"/tmp/ansible_vmware_guest_payload_k6tx_kmj/__main__.py\", line 2152, in reconfigure_vm\n  File \"/tmp/ansible_vmware_guest_payload_k6tx_kmj/__main__.py\", line 1081, in configure_hardware_params\n  File \"/var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py\", line 706, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py\", line 512, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py\", line 1374, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Permission to perform this operation was denied.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   object = 'vim.VirtualMachine:vm-697',\n   privilegeId = 'VirtualMachine.Config.UpgradeVirtualHardware'\n}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
<localhost> EXEC /bin/sh -c 'echo ~ariel && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263 `" && echo ansible-tmp-1549001593.0164618-225500380269263="` echo /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263 `" ) && sleep 0'
Using module file /var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /home/ariel/.ansible/tmp/ansible-local-5370jqglbtyk/tmp7_7r8q77 TO /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/ /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/tmp/ansible.201901/venv37/bin/python3 /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/ > /dev/null 2>&1 && sleep 0'
failed: [localhost -> localhost] (item=unique-name-within-folder2) => {
    "changed": false,
    "item": "unique-name-within-folder2",
    "module_stderr": "/home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ariel/.ansible/tmp/ansible-tmp-1549001593.0164618-225500380269263/AnsiballZ_vmware_guest.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/home/ariel/.local/stow/python-3.7.0/lib/python3.7/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/home/ariel/.local/stow/python-3.7.0/lib/python3.7/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_vmware_guest_payload_dic4mrkj/__main__.py\", line 2396, in <module>\n  File \"/tmp/ansible_vmware_guest_payload_dic4mrkj/__main__.py\", line 2351, in main\n  File \"/tmp/ansible_vmware_guest_payload_dic4mrkj/__main__.py\", line 2152, in reconfigure_vm\n  File \"/tmp/ansible_vmware_guest_payload_dic4mrkj/__main__.py\", line 1081, in configure_hardware_params\n  File \"/var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py\", line 706, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py\", line 512, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/var/tmp/ansible.201901/venv37/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py\", line 1374, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Permission to perform this operation was denied.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   object = 'vim.VirtualMachine:vm-698',\n   privilegeId = 'VirtualMachine.Config.UpgradeVirtualHardware'\n}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
	to retry, use: --limit @/home/ariel/ansible-vmware_guest-bug/playbook-2.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

I have two playbook to create VMs with the same name, but differs in VM folder
and CPU count.
The first playbook executed successfully, no problem there. So I start the VM.

But the second playbook failed with insufficient permission error.

My designation for `ansible_a@vsphere.local` user is to create new VMs only,
but it seems my playbook-2.yml tried to modify VMs in `research/POTATO-A/`
ignoring my `research/POTATO-B` directive in the playbook. I get this
conclusion because when I change the VM name in the second playbook it runs
just fine, the VMs created on correct folder too
