### ISSUE TITLE
 'Connection' object has no attribute 'ssh'

### ISSUE THREAD

**Issue by dhirajdebut** [ansible/ansible#51590]
##### SUMMARY

I have installed ansible in macOS & also sshpass through pip. I am trying to run a task. in below as specified below. Whenever I run this  task get error

```yaml
- name: Add user to a group
      user:
        name: "{{ansible_user}}"
        groups: docker
        append: yes
      become: yes
      when: node_type == "peer"
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible Version Details 
```
> ansible 2.7.6
>   config file = None
>   configured module search path = [u'/Users/harmeet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /Library/Python/2.7/site-packages/ansible
>   executable location = /usr/local/bin/ansible
>   python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```
##### ANSIBLE VERSION
```paste below
2.7.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac OS Sierra

##### STEPS TO REPRODUCE

run a task from playbook in ansible in macos
```
- name: Add user to a group
      user:
        name: "{{ansible_user}}"
        groups: docker
        append: yes
      become: yes
      when: node_type == "peer"
```

##### EXPECTED RESULTS

It should have worked for me 

##### ACTUAL RESULTS

> ERROR! Unexpected Exception, this is probably a bug: 'Connection' object has no attribute 'ssh'
> the full traceback was:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/ansible-playbook", line 118, in <module>
>     exit_code = cli.run()
>   File "/Library/Python/2.7/site-packages/ansible/cli/playbook.py", line 122, in run
>     results = pbex.run()
>   File "/Library/Python/2.7/site-packages/ansible/executor/playbook_executor.py", line 156, in run
>     result = self._tqm.run(play=play)
>   File "/Library/Python/2.7/site-packages/ansible/executor/task_queue_manager.py", line 291, in run
>     play_return = strategy.run(iterator, play_context)
>   File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/linear.py", line 267, in run
>     results.extend(self._execute_meta(task, play_context, iterator, host))
>   File "/Library/Python/2.7/site-packages/ansible/plugins/strategy/__init__.py", line 1098, in _execute_meta
>     connection.reset()
>   File "/Library/Python/2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 539, in reset
>     self.close()
>   File "/Library/Python/2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 553, in close
>     if self.get_option('host_key_checking') and self.get_option('record_host_keys') and self._any_keys_added():
>   File "/Library/Python/2.7/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 499, in _any_keys_added
>     for hostname, keys in iteritems(self.ssh._host_keys):
> AttributeError: 'Connection' object has no attribute 'ssh'
>
