### ISSUE TITLE
make git module support owner and group parameters

### ISSUE THREAD

**Issue by yusukensanta** [ansible/ansible#51601]
##### SUMMARY
make `git module` to support both `owner` and `group` parameters like copy module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
git

##### ADDITIONAL INFORMATION
In case that we want to clone a git repository under a specific user (except for root and default user)  ownership, `become: (yes|no)` won't work well because it just decides which user, root or default user, should own the directory created with git module.

Even if we intend to use the directory with the user, it ends up with seeing the message like  "Permission denied .git/FETCH_HEAD".

It can be achieved by using `file module` after `git module`, but it's a little bit troublesome.
  

```yaml
- tasks:
  - name: cloning git with configuration of ownership on dest directory
    git: 
      repo: "ssh://git@github.com/ORG/Example.git"
      dest: "/var/www/Example"
      ssh_opts: "xxxx"
      key_file: "yyyy"
      owner: app # nice to have
      group: app #  nice to have
```

**Comment by Kriechi** [comment]
By pure luck I just had the same issue - thanks for opening this feature request just a day ago!

Would you mind sharing your workaround with the file module? Does it always generate a "changed" task?

**Comment by geerlingguy** [comment]
I've recently run into the same issue as well; sometimes I would like to have the git checkout done as one user (e.g. `root`), but have the files in the working tree actually owned by another (e.g. `www-data`). It would be convenient to be able to do this in one task instead of two.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/git.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/git.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rosaLux161** [comment]
This feature would be very helpful.

**Comment by Mies-bvd89** [comment]
The feature would be helpful! Running into the same issues as described above.

**Comment by mattl** [comment]
I'd also find this very useful, my use-case is the same.

**Comment by pyrou** [comment]
Just for the the record, `become: false` execute git action (or any action) as the connected `remote_user`.
This might do the job for most use cases.

in playbook:
```yml
remote_user: app
```

in role task:
```yml
  - name: clone git repository
    become: false
    git:
      repo: "ssh://git@github.com/ORG/example.git"
      dest: "/var/www/example"
      ssh_opts: "xxx"
      key_file: "yyy"
```

of course destination must exists first and be writable by `app` in this example
