### ISSUE TITLE
y|Y|n|N|on|On|ON|off|Off|OFF not Converted to Boolean when DEFAULT_JINJA2_NATIVE is False

### ISSUE THREAD

**Issue by dennisconrad** [ansible/ansible#51618]
##### SUMMARY

When  `DEFAULT_JINJA2_NATIVE` is `False` certain strings which resemble YAML Booleans according to https://yaml.org/type/bool.html are not converted into Booleans, but kept as strings.  Affected strings are variations of `y`/`n` and `on`/`off`.

While I would argue that `DEFAULT_JINJA2_NATIVE` **should** be enabled as default, Ansible currently displays inconsistent behaviour when it is not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.0.dev0
  config file = /Users/dennis.conrad/ansible_devel/ansible/ansible.cfg
  configured module search path = ['/Users/dennis.conrad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dennis.conrad/ansible_devel/ansible/lib/ansible
  executable location = /Users/dennis.conrad/ansible_devel/ansible/bin/ansible
  python version = 3.6.5 (default, Dec 11 2018, 12:40:45) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
$
```

##### STEPS TO REPRODUCE
Here's a short playbook which will fail if `DEFAULT_JINJA2_NATIVE` is set to `False`, as `y`/`n` and `on`/`off` are not parsed to Booleans: 

```yaml
- hosts: localhost
  gather_facts: no

  tasks:
    - set_fact:
        string_y: "y"
        string_n: "n"
        string_yes: "yes"
        string_no: "no"
        string_on: "on"
        string_off: "off"
        string_true: "true"
        string_false: "false"
    
    - assert:
        that:
          - string_y ==  "y"
          - string_n ==  "n"
          - string_yes ==  "yes"
          - string_no ==  "no"
          - string_on ==  "on"
          - string_off ==  "off"
          - string_true ==  "true"
          - string_false ==  "false"
      when: lookup('config', 'DEFAULT_JINJA2_NATIVE') == true

    - assert:
        that:
          - string_y ==  true
          - string_n ==  false
          - string_yes ==  true
          - string_no ==  false
          - string_on ==  true
          - string_off ==  false
          - string_true ==  true
          - string_false ==  false
      when: lookup('config', 'DEFAULT_JINJA2_NATIVE') == false
```

##### EXPECTED RESULTS

Assertions to pass when `DEFAULT_JINJA2_NATIVE` is set to `False`.

##### ACTUAL RESULTS

Assertions fail when `DEFAULT_JINJA2_NATIVE` is set to `False`.

**Comment by dennisconrad** [comment]
PR: https://github.com/ansible/ansible/pull/51619

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
This is wrong, if you define it as a string, it should be a string. It always has been like this for good reasons. Otherwise people wouldn't be able to create a string containing "yes" or "True".

There is only one exception, which is when using `key=value` pairs, as we don't have the added value of YAML syntax and strings could become booleans (when not explicitly quoted).

**Comment by dennisconrad** [comment]
> This is wrong, if you define it as a string in YAML, it should be a string. It always has been like this for good reasons. Otherwise people wouldn't be able to create a string containing "yes" or "True".
> 
> There is only one exception, which is when using the `key=value` pair syntax, as we don't have the added value of YAML syntax and strings could become booleans (when not explicitly quoted).

Please see my comment on #51619 why people **right now** are not able to create strings like "yes" or "True".

**Comment by dagwieers** [comment]
@dennisconrad Ok, let's make it clear this is about **set_fact** only, and that someone (incorrectly) changed **set_fact** to convert certain strings to booleans. This behaviour is wrong, **set_fact** should be behaving exactly as **vars:** in YAML format.

I traced this back to a change more than 4 years ago (https://github.com/ansible/ansible/commit/a6d6a89ad1d460f8d29589128549e2bac1e54db8). I think we should either keep it as it is (to not break anyone's playbooks) or if we do want to correct this, we should remove this conversion in **set_fact**.

**Comment by dagwieers** [comment]
@dennisconrad Yes, and if we want to change that erratic behaviour we should be removing it, rather than extending it.

**Comment by bcoca** [comment]
also consider:
```   - set_fact:   string_y="y" string_n="n" string_yes="yes" ...```

**Comment by dagwieers** [comment]
@bcoca That's the origin of our madness, which we transported to YAML inadvertently :-(

**Comment by bcoca** [comment]
```yaml
- hosts: localhost
  gather_facts: no
  vars:
      listofvars: '{{q("varnames", "^string_.+")}}'
  tasks:
    - set_fact:
        string_y: "y"
        string_n: "n"
        string_yes: "yes"
        string_no: "no"
        string_on: "on"
        string_off: "off"
        string_true: "true"
        string_false: "false"

    - debug: msg={{item|type_debug}}
      loop: '{{ q("vars", *listofvars)}}'

    - debug: msg={{item|type_debug}}
      loop: '{{ q("vars", *listofvars)}}'
      vars:
        string_y: "y"
        string_n: "n"
        string_yes: "yes"
        string_no: "no"
        string_on: "on"
        string_off: "off"
        string_true: "true"
        string_false: "false"


    - set_fact: string_y="y" string_n="n" string_yes="yes" string_no="no" string_on="on" string_off="off" string_true="true" string_false="false"
    - debug: msg={{item|type_debug}}
      loop: '{{ q("vars", *listofvars)}}'
```
outputs:
```
PLAY [localhost] *************************************************************************************************************************************

TASK [set_fact] **************************************************************************************************************************************
ok: [localhost]

TASK [debug] *****************************************************************************************************************************************
ok: [localhost] => (item=y) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=n) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=True) => {
    "msg": "bool"
}
ok: [localhost] => (item=False) => {
    "msg": "bool"
}
ok: [localhost] => (item=on) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=off) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=True) => {
    "msg": "bool"
}
ok: [localhost] => (item=False) => {
    "msg": "bool"
}

TASK [debug] *****************************************************************************************************************************************
ok: [localhost] => (item=y) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=n) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=True) => {
    "msg": "bool"
}
ok: [localhost] => (item=False) => {
    "msg": "bool"
}
ok: [localhost] => (item=on) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=off) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=True) => {
    "msg": "bool"
}
ok: [localhost] => (item=False) => {
    "msg": "bool"
}

TASK [set_fact] **************************************************************************************************************************************
ok: [localhost]

TASK [debug] *****************************************************************************************************************************************
ok: [localhost] => (item=y) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=n) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=True) => {
    "msg": "bool"
}
ok: [localhost] => (item=False) => {
    "msg": "bool"
}
ok: [localhost] => (item=on) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=off) => {
    "msg": "AnsibleUnsafeText"
}
ok: [localhost] => (item=True) => {
    "msg": "bool"
}
ok: [localhost] => (item=False) => {
    "msg": "bool"
}

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
