### ISSUE TITLE
Directly support iterating over dicts in "loop"

### ISSUE THREAD

**Issue by sgrimm-sg** [ansible/ansible#51615]
##### SUMMARY

The `loop` keyword should implicitly call `dict2items` if its argument is a dict instead of a list.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

loop

##### ADDITIONAL INFORMATION

In several of my playbooks I use `with_dict` to iterate over dictionary literals (as opposed to looping over dicts that are defined elsewhere). I'd like to move to the new `loop` setup to get out ahead of `with_` being deprecated some day in the future, but for this specific case, it makes the tasks more verbose for no real benefit.

Suggestion: Instead of bombing out with an error about expecting a list, `loop` should iterate over the items of a dict if one is passed to it. In other words, it should implicitly call `dict2items`.

```yaml
# Before
- name: Some task
  lineinfile: ...
  with_dict:
    item1: foo
    item2: bar

# After
- name: Some task
  lineinfile: ...
  loop: "{{ items|dict2items }}"
  vars:
    items:
      item1: foo
      item2: bar
```

Here, the "vars" block and the filter expression make the playbook noisier but don't add any functionality.

Suggestion:

```yaml
- name: Some task
  lineinfile: ...
  loop:
    item1: foo
    item2: bar
```

To be clear, I'm not suggesting getting rid of the ability to call filters other than `dict2items` if you want something other than the default iteration order or the default mapping to `item.key` and `item.value`. The explicit syntax would still be available when finer control is required, so the change I'm suggesting doesn't remove any functionality. The proposal is just to replace the current behavior (playbook bombs out with an error if you feed a dict to `loop`) with default behavior that is likely to be what people would expect.
