### ISSUE TITLE
meraki_config_template not  using net_id

### ISSUE THREAD

**Issue by ericdost** [ansible/ansible#51625]
##### SUMMARY

When using net_id instead of net_name, the network is not bound to the configuration template

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

meraki_config_template

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules', u'/home/ansible/.ansible/roles/mkouhei.include_csv']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/callbacks']
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks', u'dense', u'selective']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/.ansible/tmp/ansible-local-11371tfVHNj
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/modules/ntc-ansible', u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules', u'/home/ansible/.ansible/roles/mkouhei.include_csv']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
---

- name: GET DATE AND GATE
  connection: local
  hosts: localhost
  gather_facts: no

  vars:
    key: '123456789'
    org: '123'
    net_name: 'TestSite'
    mx_serial: 'ABCD-1234-EFGH'
    template: 'Standard_Site'

  tasks:

    - name: "Create meraki network(s)"
      meraki_network:
        auth_key: " {{ key }}"
        state: present
        org_id: "{{ org }}"
        net_name: "{{ net_name }}"
        types:
          - appliance
          - switch
      delegate_to: localhost

    - name: "Query all networks in our organization in the Meraki Cloud"
      meraki_network:
        auth_key: "{{ key }}"
        org_id: "{{ org }}"
        state: query
      delegate_to: localhost
      register: networks

    - name: "Bind MX serial number(s) to network(s)"
      meraki_device:
        auth_key: "{{ key }}"
        org_id: "{{ org }}"
        net_id: "{{ networks.data | selectattr('name', 'equalto', net_name) | map(attribute='id') | join }}"
        serial: "{{ mx_serial }}"
        state: present
      delegate_to: localhost

    - name: "Query configuration templates"
      meraki_config_template:
        auth_key: "{{ key }}"
        org_id: "{{ org }}"
        config_template: "{{ template }}"
        state: query
      delegate_to: localhost
      register: config_templates

    - name: "Is network bound to the template?"
      debug:
        msg: "network {{ net_name }} is bound to template {{ template }}"
      when:
        - item.configTemplateId is defined
        - item.configTemplateId == (config_templates.data | selectattr('name', 'equalto', template) | map(attribute='id') | join)
        - item.name == net_name
      loop: "{{ networks.data | flatten(levels=1) }}"
      delegate_to: localhost

    - name: "Bind network(s) to configuration template"
      meraki_config_template:
        auth_key: "{{ key }}"
        state: present
        org_id: "{{ org }}"
        net_id: "{{ networks.data | selectattr('name', 'equalto', net_name) | map(attribute='id') | join }}"
        config_template: "{{ template | default('Standard_Site') }}"
        auto_bind: yes
      delegate_to: localhost

    - name: "Query all networks in our organization in the Meraki Cloud"
      meraki_network:
        auth_key: "{{ key }}"
        org_id: "{{ org }}"
        state: query
      delegate_to: localhost
      register: alsonetworks

    - name: "Is network bound to the template?"
      debug:
        msg: "network {{ net_name }} is bound to template {{ template }}"
      when:
        - item.configTemplateId is defined
        - item.configTemplateId == (config_templates.data | selectattr('name', 'equalto', template) | map(attribute='id') | join)
        - item.name == net_name
      loop: "{{ alsonetworks.data | flatten(levels=1) }}"
      delegate_to: localhost

    - name: "Bind network(s) to configuration template using net_name"
      meraki_config_template:
        auth_key: "{{ key }}"
        state: present
        org_id: "{{ org }}"
        net_name: "{{ net_name }}"
        config_template: "{{ template | default('Standard_Site') }}"
        auto_bind: yes
      delegate_to: localhost

    - name: "Query all networks in our organization in the Meraki Cloud"
      meraki_network:
        auth_key: "{{ key }}"
        org_id: "{{ org }}"
        state: query
      delegate_to: localhost
      register: alsoalsonetworks

    - name: "Is network bound to the template?"
      debug:
        msg: "network {{ net_name }} is bound to template {{ template }}"
      when:
        - item.configTemplateId is defined
        - item.configTemplateId == (config_templates.data | selectattr('name', 'equalto', template) | map(attribute='id') | join)
        - item.name == net_name
      loop: "{{ alsoalsonetworks.data | flatten(levels=1) }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

Using net_id properly binds the network to the configuration template

##### ACTUAL RESULTS

```paste below
PLAY [GET DATE AND GATE] *******************************************************************************************************************************************************************************************************************
Friday 01 February 2019  13:14:48 -0500 (0:00:00.146)       0:00:00.146 ******* 

TASK [Create meraki network(s)] ************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]
Friday 01 February 2019  13:14:57 -0500 (0:00:09.204)       0:00:09.351 ******* 

TASK [Query all networks in our organization in the Meraki Cloud] **************************************************************************************************************************************************************************
ok: [localhost -> localhost]
Friday 01 February 2019  13:15:03 -0500 (0:00:05.772)       0:00:15.124 ******* 

TASK [Bind MX serial number(s) to network(s)] **********************************************************************************************************************************************************************************************
changed: [localhost -> localhost]
Friday 01 February 2019  13:15:13 -0500 (0:00:10.511)       0:00:25.636 ******* 

TASK [Query configuration templates] *******************************************************************************************************************************************************************************************************
ok: [localhost -> localhost]
Friday 01 February 2019  13:15:21 -0500 (0:00:07.311)       0:00:32.947 ******* 
Friday 01 February 2019  13:15:22 -0500 (0:00:01.196)       0:00:34.144 ******* 

TASK [Bind network(s) to configuration template] *******************************************************************************************************************************************************************************************
ok: [localhost -> localhost]
Friday 01 February 2019  13:15:28 -0500 (0:00:06.325)       0:00:40.469 ******* 

TASK [Query all networks in our organization in the Meraki Cloud] **************************************************************************************************************************************************************************
ok: [localhost -> localhost]
Friday 01 February 2019  13:15:34 -0500 (0:00:05.423)       0:00:45.893 ******* 
Friday 01 February 2019  13:15:35 -0500 (0:00:01.142)       0:00:47.035 ******* 

TASK [Bind network(s) to configuration template using net_name] ****************************************************************************************************************************************************************************
changed: [localhost -> localhost]
Friday 01 February 2019  13:15:45 -0500 (0:00:10.280)       0:00:57.315 ******* 

TASK [Query all networks in our organization in the Meraki Cloud] **************************************************************************************************************************************************************************
ok: [localhost -> localhost]
Friday 01 February 2019  13:15:51 -0500 (0:00:05.844)       0:01:03.160 ******* 

TASK [Is network bound to the template?] ***************************************************************************************************************************************************************************************************
ok: [localhost -> localhost] => (item={u'disableMyMerakiCom': False, u'disableRemoteStatusPage': True, u'name': u'TestSite', u'tags': None, u'organizationId': u'123', u'timeZone': u'America/New_York', u'type': u'combined', u'id': u'L_1234', u'configTemplateId': u'L_7890'}) => 
  msg: network TestSite is bound to template Standard_Site

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
localhost                  : ok=9    changed=3    unreachable=0    failed=0   

Friday 01 February 2019  13:15:52 -0500 (0:00:01.224)       0:01:04.384 ******* 
=============================================================================== 
Bind MX serial number(s) to network(s) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 10.51s
Bind network(s) to configuration template using net_name --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 10.28s
Create meraki network(s) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 9.20s
Query configuration templates ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 7.31s
Bind network(s) to configuration template ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.33s
Query all networks in our organization in the Meraki Cloud -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.84s
Query all networks in our organization in the Meraki Cloud -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.77s
Query all networks in our organization in the Meraki Cloud -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.42s
Is network bound to the template? --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.22s
Is network bound to the template? --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.20s
Is network bound to the template? --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.14s
```
