### ISSUE TITLE
Obscure error message on expiring scheduled task

### ISSUE THREAD

**Issue by johnboy2** [ansible/ansible#51634]
##### SUMMARY
Within the "win_scheduled_task" module, the `delete_expired_task_after` setting can only _legitimately_ be used when at least one trigger has an `end_boundary` defined. Any tasks using `delete_expired_task_after` _without_ at least one trigger with an `end_boundary` is ill-defined.

This is problematic because the _requirement_ for that kind of trigger is undocumented and non-obvious. This request is to add such a check, including a human-readable error message if/when the check fails.

##### ISSUE TYPE
- Feature request

##### COMPONENT NAME

win_scheduled_task

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

Windows Server 2012 R2

##### STEPS TO REPRODUCE

```yaml
- hosts: windows
  gather_facts: no
  vars:
    ansible_user: administrator
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - win_scheduled_task:
        name: Test task
        actions:
          - path: C:\Windows\System32\hostname.exe
        triggers:
          - type: boot
        username: SYSTEM
        delete_expired_task_after: PT0S  # immediately
```

##### EXPECTED RESULTS

Example error message:
```
FAILED! => {"change": false, "msg": "Cannot use `delete_expired_task_after` without at least one trigger with an `end_boundary`"}
```

##### ACTUAL RESULTS

```paste below
TASK [win_scheduled_task] ***************************************************************************************************
fatal: [10.0.14.36]: FAILED! => {"changed": true, "msg": "failed to modify scheduled task: Exception calling \"RegisterTaskDefinition\" with \"6\" argument(s): \"(43,4):EndBoundary:\""}
```

##### NOTES
* I couldn't find any documentation describing this requirement, although it can be observed in practice by trying to manually create such a task via the Task Scheduler UI. If you do so, you get this message in a pop-up:
  > If you want to have a task deleted automatically after it runs, you must add at least one trigger that has an expiration date.
