### ISSUE TITLE
Expose facts.d path as variable

### ISSUE THREAD

**Issue by NotAFile** [ansible/ansible#51632]
##### SUMMARY

Expose the currently set path of the "facts.d" directory in a variable

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core, setup

##### ADDITIONAL INFORMATION

It is often useful to place something you want to remember on a later run into the facts.d directory of a host. However, since this path is not exposed to playbooks, this currently requires hard-coding the path, which breaks if users of a role decide to change it.

```yaml
- copy:
    src: "files/my_fact_executable.fact"
    dest: "{{ ansible_local_fact_dir }}"

- copy:
    content: "{{ ansible_date_time }}"
    dest: "{{ ansible_local_fact_dir }}/last_run.fact"

- copy:
    content: "{{ expensive_operation_results_we_want_to_save_for_next_time }}"
    dest: "{{ ansible_local_fact_dir }}/save_time.fact"
```

**Comment by jborean93** [comment]
The [config lookup plugin](https://docs.ansible.com/ansible/latest/plugins/lookup/config.html) is designed so that you can get config options in a playbook run. For your case you can do

```
- copy:
    src: files/my_fact_executable.fact
    dest: "{{ lookup('config', 'DEFAULT_FACT_PATH') }}"
```

I'm assuming [DEFAULT_FACT_PATH](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-fact-path) is the config option you want to retrieve but any config option can be looked up in the same way.

**Comment by NotAFile** [comment]
@jborean93 The problem with config lookups is that you can't detect a manual override that isn't done in the config file. I suppose that case is pretty rare, but it would be great to have a way to get this path without a "but sometimes" case.

**Comment by jborean93** [comment]
What do you mean by manual override? That lookup get's the value of the config option at that time.

**Comment by NotAFile** [comment]
@jborean93 the fact directory can be set with the fact_path directive at a play level. There is no method I've seen that will also retrieve that value, hence this issue. `lookup("config", "DEFAULT_FACT_PATH") ` also returns `"" ` if not set (instead of the default `/etc/ansible/fact.d`), which still would require hardcoding the path.

**Comment by jborean93** [comment]
Ah ok I see what you mean now. The docs for `DEFAULT_FACT_PATH` has no value as the default which is why the value is an empty string when you debug it. The only reason why `/etc/ansible/facts.d` is the default value is because that's the default value set in the [setup](https://docs.ansible.com/ansible/latest/modules/setup_module.html) module itself.

If you set the facts_path value in ansible.cfg I can confirm that lookup will work correctly but a play level setting will not. This is the same for other play/task directives like `become: True`, you won't be able to access those play directives as it's somewhat outside of the config/var system. If you need to set the `fact_path` on the play I would look at storing the value in a variable and use that. There are 2 ways of doing this

```
- name: through the play level - this would have to be defined in all or passed in with -e
  hosts: localhost
  fact_path: '{{ some_variable }}'
  tasks:
  ...
```

```
- name: or you can run the setup task manually and use host variables
  hosts: localhost
  gather_facts: no
  tasks:
  - setup:
      fact_path: '{{ some_var }}' # this can be a var scoped to the play host
```

It's not a perfect scenario but play/task based directives aren't really designed to be inspected in the tasks themselves.
