### ISSUE TITLE
digital_ocean_droplet: add rebuild option (state=pristine)

### ISSUE THREAD

**Issue by mz0** [ansible/ansible#51656]
##### SUMMARY
 Allow Droplet rebuilding from current or another image.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
digital_ocean_droplet

##### ADDITIONAL INFORMATION
Some Droplet mis-configuration issues may be solved by rebuilding droplet. One may also find it useful to rebuild a droplet from a new image without deleting existing Droplet.

```yaml
digital_ocean_droplet:
  oauth_token: xxxxxxxx
  name: vm111
  unique_name: true
  state: pristine

digital_ocean_droplet:
  oauth_token: xxxxxxxx
  name: vm222
  unique_name: true
  state: pristine
  image: debian-9-x64  # was debian-8-x64
```
