### ISSUE TITLE
os_network's provider_segmentation_id should be integer

### ISSUE THREAD

**Issue by dominikholler** [ansible/ansible#51655]
##### SUMMARY

According to the OpenStack Networking API
the attribute provider:segmentation_id of a network has to be
an integer.
Even if neutron accepts provider:segmentation_id to be a
string, other implementations may not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_network

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dominik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 19:49:22) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
   - name: Create network
     os_network:
        name: "ovn_vlan_5"
        cloud: packstack
        state: present
        provider_network_type: vlan
        provider_physical_network: extnet
        provider_segmentation_id: 5
```

##### EXPECTED RESULTS

Request produced by ansible should contain
"provider:segmentation_id": 5

##### ACTUAL RESULTS

Request produced by ansible contains
"provider:segmentation_id": "5"

```paste below

```
