### ISSUE TITLE
apt,yum modules: support with_items loops with a prefix for the apt and yum modules

### ISSUE THREAD

**Issue by patrickheeney** [ansible/ansible#5166]
This is regarding the discussion at https://groups.google.com/forum/#!topic/ansible-project/89nAO_ncAs0

The idea is to be able to add a prefix to apt and yum so that the following would work:

```
- name: PHP | MAIN | Install php packages
  apt: >
    pkg=php5-{{ item }}
    state=latest
  with_items: 
    - cli
    - intl
    - mcrypt
    - curl
  sudo: yes
```

A suggestion from James Tanner:

> One possible solution is to add a pkg_prefix option to the apt and yum modules.
