### ISSUE TITLE
win_package recursive copy

### ISSUE THREAD

**Issue by shorbachuk** [ansible/ansible#51670]
##### SUMMARY
I have some installers that have dependencies, answer files that are required by the installer. I know win_package copies the path locally. It would be nice to have an option to recursively copy if the path is a UNC path. Something like this:

- name: Install the Visual C thingy
  win_package:
    path: "\\\\server1\\installs\product.msi"
    product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
    recurse_copy: yes

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
win_package

##### ANSIBLE VERSION
v2.7

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_package.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_package.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
Question About This One
=======================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, and I don't want this to seem confrontational.  Our reasons for this are:

   * win_package only copies the files if the path is on the network and explicit credentials are set with the `username` and `password` options
   * In other situations it is installed from where `path` is specified
   * There's not much that can be done to have win_package analyse what files need to be copied, how deeply it should copy folders and so on. This is not a can of worms we want to open
   * You can always use win_copy with `remote_src: True` to copy what is needed before running win_package
   * If you are using `username` and `password` with `win_package`, have a look at swapping over to [become](https://docs.ansible.com/ansible/latest/user_guide/become.html#become-and-windows). You can achieve the same result and have win_package install straight from the network by doing

```
- name: Install the Visual C thingy
  win_package:
    path: \\server1\installs\product.msi
    product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
  become: True
  become_method: runas
  # The following flags means the become user is only used for network authentication, 
  # all local actions still run as the connection user
  become_flags: logon_type=new_credentials logon_flag=netcredentials_only
  vars:
    ansible_become_user: some_user
    ansible_become_pass: some_pass
```

With the above example, `ansible_become_user` does not even need to be a valid Windows user. The `become_flags` set means it is only used for network authentication just like the `username` and `password module options.

However, we're absolutely always up for discussion.  Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage
open dialog.  You can stop by the development list, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel

In the future, sometimes starting a discussion on the development list prior to implementing a feature can make getting things included a little easier, but it's not always necessary.

Thank you once again for this and your interest in Ansible!
