### ISSUE TITLE
Terraform module can't handle list/dict variables

### ISSUE THREAD

**Issue by plsanchezfaure** [ansible/ansible#51687]
##### SUMMARY
Terraform module does not escape correctly list/dict variables, so they can't be passed to Terraform command.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
terraform

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = None
  configured module search path = ['/home/my_user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/my_user/.virtualenvs/my_project/lib/python3.6/site-packages/ansible
  executable location = /home/my_user/.virtualenvs/my_project/bin/ansible
  python version = 3.6.8 (default, Dec 24 2018, 19:24:27) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
(no output for "ansible-config dump --only-changed")
```

##### OS / ENVIRONMENT
Ubuntu 16.04.5 LTS

##### STEPS TO REPRODUCE
- Terraform vars file:

```
variable "vms" {
  type = "list"
}
```

- Terraform main file:
```
resource "null_resource" "debug" {
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command = "echo '${jsonencode(var.vms)}' > /home/my_user/tmp/out"
  }
}
```

- Ansible playbook
```yaml
- hosts: localhost
  vars:
    vms:
      - "asdf"
      - "qwer"
  tasks:
    - register: terraform_output
      terraform:
        project_path: "{{ playbook_dir }}/terraform/"
        state: present
        force_init: true
        variables:
          vms: "{{ vms }}"
```

##### EXPECTED RESULTS
Variable being passed to Terraform as you can do with "-var 'vms=["asdf", "qwer"]' "

##### ACTUAL RESULTS
```
TASK [Create resources] ************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to validate Terraform configuration files:\r\n\u001b[31mUsage: terraform validate [options] [dir]\n\n  Validate the terraform files in a directory. Validation includes a\n  basic check of syntax as well as checking that all variables declared\n  in the configuration are specified in one of the possible ways:\n\n      -var foo=...\n      -var-file=foo.vars\n      TF_VAR_foo environment variable\n      terraform.tfvars\n      default value\n\n  If dir is not specified, then the current directory will be used.\n\nOptions:\n\n  -check-variables=true If set to true (default), the command will check\n                        whether all required variables have been specified.\n\n  -no-color             If specified, output won't contain any color.\n\n  -var 'foo=bar'        Set a variable in the Terraform configuration. This\n                        flag can be set multiple times.\n\n  -var-file=foo         Set variables in the Terraform configuration from\n                        a file. If \"terraform.tfvars\" is present, it will be\n                        automatically loaded if this flag is not specified.\u001b[0m\u001b[0m\n"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/misc/terraform.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/terraform.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ryansb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Leletir** [comment]
@plsanchezfaure I also have the same problem, and I'm running ansible 2.7.8

**Comment by raffienficiaud** [comment]
I am completely unable to pass complex variables through the command line. I did this for instance, according to the way variables on the CLI are handled (see [here](https://learn.hashicorp.com/terraform/getting-started/variables.html#assigning-maps))

```
- terraform:
          project_path: 'terraform-deployment/myproj'
          state: "present"
          workspace: staging
          variables:
            some_docker_image: '{ staging = docker-image-tag }'

```
with various combinations of quotes etc, but terraform always complains about the parsing of those variables. The workaround I found was to go through a file:

```
    - name: "Terraform use docker images"
      block:

      - tempfile:
          state: file
          suffix: .tfvars
        register: tmp_vars

      - template:
          src: terraform-var-file.j2
          dest: "{{ tmp_vars.path }}"
        vars:
          map_variables:
            frontend_app_image:
              staging:  "\"some-docker-image-1-with-tag\""
            var2_image:
              staging: "\"some-docker-image-2-with-tag\""
        tags: terraform

      - terraform:
          project_path: 'terraform-deployment/myproj'
          state: "present"
          workspace: staging
          variables_file: "{{ tmp_vars.path }}"

      always:
        - file:
            path: "{{ tmp_vars.path }}"
            state: absent
```

the content of the template is simply this:
```
{% for vars, maps in map_variables.items() %}
{{ vars }} = {
    {% for key, value in maps.items() %}
    {{ key }} = {{ value }}
    {% endfor %}
}
{% endfor %}
```
