### ISSUE TITLE
openssl_pkcs12: cannot create archive without a private key

### ISSUE THREAD

**Issue by rwaweber** [ansible/ansible#51703]
##### SUMMARY
When attempting to create a pkcs12 archive to use as a java truststore, I am unable to do so without the private key.

Looking at the documentation, I don't think that this is an intended use, so this may be more in the realm of a feature request.

##### ISSUE TYPE
- Bug Report
- Feature Request

##### COMPONENT NAME
`openssl_pkcs12`

##### ANSIBLE VERSION

```paste below
2.7.4
```

##### STEPS TO REPRODUCE
```yaml
    - name: Generate pkcs12 formatted truststore
      openssl_pkcs12:
        action: export
        path: "/tmp/truststore.p12"
        friendly_name: "Sampletruststore"
        ca_certificates: "/tmp/ca.pem"
        passphrase: "password"
```

##### EXPECTED RESULTS
A pkcs12-formatted truststore with the included certificate authority would exist at `/tmp/truststore.p12`.

##### ACTUAL RESULTS
It errors out with this, when the `friendly_name` parameter is included.
```paste below
"parameters are required together: privatekey_path, friendly_name"
```

Then with `friendly_name` removed, I receive the following:
```
"Friendly_name is required"
```
