### ISSUE TITLE
Unarchive task in ansible fails on macOS 

### ISSUE THREAD

**Issue by dhirajdebut** [ansible/ansible#51719]
##### SUMMARY

I am not able unarchive a tar file through the unarchive task in Ansible

 ```
   - name: Download the tar for sample config
      unarchive:
        src: http://someremoteurl/config.tar.gz 
        dest: /Users/{{ansible_user}}/.myfolder/
        remote_src: yes
        creates: /Users/{{ansible_user}}/.myfolder/config 
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

I am using the Ansible unarchive module and executing through a playbook created.

##### ANSIBLE VERSION

```paste below

ansible 2.8.0.dev0
  config file = /Users/harmeet/.ansible.cfg
  configured module search path = [u'/Users/harmeet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```yaml
 - name: Download the tar for sample config
      unarchive:
        src: http://someremoteurl/config.tar.gz 
        dest: /Users/{{ansible_user}}/.myfolder/
        remote_src: yes
        creates: /Users/{{ansible_user}}/.myfolder/config 
```

##### EXPECTED RESULTS

It should download the tar file for remote url & unarchive it.
It should create a new directory under home directory named `.myfolder `as & copy the unarchived dir into it.

##### ACTUAL RESULTS

    "msg": "Failed to find handler for \"/Users/harmeet/.ansible/tmp/ansible-tmp-1549339698.75-251687957122076/config.tar9IXAUQ.gz\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" detected as tar type bsd. GNU tar required. Command \"/usr/bin/unzip\" could not handle archive.

```paste below

```
