### ISSUE TITLE
nxos failure on 9k when removing vlan (nxos_vlan absent)

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#51745]
I don't think so

##### SUMMARY

I'm running into problems with nxos_vlan vlan removal on cisco nexus 9K. Works ok on 5k. For the 9k, ansible seems to try VXLAN commands when not configured for VXLAN.

"10.6.0.81": {
                            "_ansible_no_log": false,
                            "_ansible_parsed": true,
                            "action": "nxos_vlan",
                            "changed": false,
                            "failed": true,
                            "invocation": {
                                "module_args": {
                                    "admin_state": "up",
                                    "aggregate": null,
                                    "associated_interfaces": null,
                                    "auth_pass": null,
                                    "authorize": null,
                                    "delay": 10,
                                    "host": null,
                                    "interfaces": null,
                                    "mapped_vni": null,
                                    "mode": null,
                                    "name": "DEPTTEST-SF-TEST-dmz2",
                                    "password": null,
                                    "port": null,
                                    "provider": null,
                                    "purge": false,
                                    "ssh_keyfile": null,
                                    "state": "absent",
                                    "timeout": null,
                                    "transport": null,
                                    "use_ssl": null,
                                    "username": null,
                                    "validate_certs": null,
                                    "vlan_id": 53,
                                    "vlan_range": null,
                                    "vlan_state": "active"
                                }
                            },
                            "msg": "no vn-segment\r\r\n                                     ^\r\n% Invalid command at '^' marker.\r\n\rEDC-SF-LAB-9504-81(config-vlan)# "

Here's a 5k result:

                        "10.6.0.78": {
                            "_ansible_no_log": false,
                            "_ansible_parsed": true,
                            "action": "nxos_vlan",
                            "changed": true,
                            "commands": [
                                "no vlan 53"
                            ],
                            "invocation": {
                                "module_args": {
                                    "admin_state": "up",
                                    "aggregate": null,
                                    "associated_interfaces": null,
                                    "auth_pass": null,
                                    "authorize": null,
                                    "delay": 10,
                                    "host": null,
                                    "interfaces": null,
                                    "mapped_vni": null,
                                    "mode": null,
                                    "name": "DEPTTEST-SF-TEST-dmz2",
                                    "password": null,
                                    "port": null,
                                    "provider": null,
                                    "purge": false,
                                    "ssh_keyfile": null,
                                    "state": "absent",
                                    "timeout": null,
                                    "transport": null,
                                    "use_ssl": null,
                                    "username": null,
                                    "validate_certs": null,
                                    "vlan_id": 53,
                                    "vlan_range": null,
                                    "vlan_state": "active"
                                }
                            }
                        },

Does this seem like a bug ?

Regards,

Rick

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_vlan

##### ANSIBLE VERSION

```paste below
(py363venvAns) [netutil@ncc657 ncans]$ ansible --version
ansible 2.7.6
  config file = /opt/apps/netutil/ncans/ansible.cfg
  configured module search path = ['/home/netutil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/apps/netutil/py363venvAns/lib/python3.6/site-packages/ansible
  executable location = /opt/apps/netutil/py363venvAns/bin/ansible
  python version = 3.6.3 (default, Jan  9 2018, 10:19:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
(py363venvAns) [netutil@ncc657 ncans]$

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/opt/apps/netutil/ncans/ansible.cfg) = True
DEFAULT_GATHERING(/opt/apps/netutil/ncans/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/opt/apps/netutil/ncans/ansible.cfg) = 30
DEFAULT_HOST_LIST(/opt/apps/netutil/ncans/ansible.cfg) = ['/opt/apps/netutil/ncans/inventory']
DEFAULT_LOG_PATH(/opt/apps/netutil/ncans/ansible.cfg) = /opt/apps/netutil/ncans/log/ansible.log
DEFAULT_STDOUT_CALLBACK(/opt/apps/netutil/ncans/ansible.cfg) = json
DEFAULT_TIMEOUT(/opt/apps/netutil/ncans/ansible.cfg) = 10
HOST_KEY_CHECKING(/opt/apps/netutil/ncans/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/opt/apps/netutil/ncans/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/opt/apps/netutil/ncans/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/opt/apps/netutil/ncans/ansible.cfg) = 600
PERSISTENT_CONNECT_TIMEOUT(/opt/apps/netutil/ncans/ansible.cfg) = 600

```

##### OS / ENVIRONMENT

7.3(4)N1(1)  -  N5K-C5596UP
7.0(3)I7(4) - N9K-C9504

##### STEPS TO REPRODUCE

```yaml
# ------------------------------------------------------------------------------------------------
# sfsw_removeL2Vlan.yml
#
# By: Rick Williams
# (c) September, 2018
#
# Mods:
#   - 012819: v3 workaround for 9k vlan removal error
#   - 011719: v2 work on bug for removing vlan
#   - 011619: v1, built from sfsw_provL2n3.yml v5
#
# runs from netautogui:
#   "SFREMOVEL2VLANANS": "sfsw_removeL2Vlan.yml"
#
# ------------------------------------------------------------------------------------------------
- hosts: nataskgroup
  gather_facts: no
  force_handlers: true
  tasks:

    - name: Block of tasks
      block:
        - name: Ping device
          ping:
          register: pdResult

        - name: Check taskVars
          debug:
            var: taskVars

        # Do this task for supported nxos devices. For unsupported devices - skip this and do next one.
        # Use when directive to check for device type.
        # we get from inventory.
        - name: SUP Ensure VLAN {{ taskVars.vlanId }} is absent on {{ item.interfaceName }} [TRUNK]
          nxos_l2_interface:
            name: "{{ item.interfaceName }}"
            mode: trunk
            trunk_vlans: "{{ taskVars.vlanId }}"
            state: absent
          when:
            - item.mode == "trunk"
            - taskVars.deviceVars.model != "N5K-C5010P-BF"
            - taskVars.deviceVars.model != "N7K-C7010"
          with_items: "{{ taskVars.deviceVars.targetInterfaces }}"
          register: emailResults

        # Do this task for unsupported nxos devices.
        # Use when directive to check for device type.
        # we get from inventory.
        - name: UNSUP Ensure VLAN {{ taskVars.vlanId }} is removed on {{ item.interfaceName }} [TRUNK]
          nxos_config:
            parents: interface {{ item.interfaceName }}
            lines:
              - switchport trunk allowed vlan remove {{ taskVars.vlanId }}
            save_when: changed
          when:
            - item.mode == "trunk"
            - (taskVars.deviceVars.model == "N5K-C5010P-BF" or taskVars.deviceVars.model == "N7K-C7010")
          with_items: "{{ taskVars.deviceVars.targetInterfaces }}"
          register: emailResults

# 9ks were failing with this trying to do a no vn-segment command. So code it using nxos-config as a workaround
#        - name: Ensure VLAN {{ taskVars.vlanId }} is absent
#          nxos_vlan:
#            name: "{{ taskVars.vlanName }}"
#            vlan_id: "{{ taskVars.vlanId }}"
#            state: absent
#            admin_state: down

        - name: Ensure VLAN {{ taskVars.vlanId }} is absent
          nxos_config:
            lines:
              - no vlan {{ taskVars.vlanId }}
            save_when: changed
          register: emailResults


      always:

        # Update mongodb with results
        # Right now the results are ok if the ping task succeeds
        - name: Update NaTask
          naam_updateNaTaskResults:
            taskResultForDev: "{{ pdResult }}"
            nataskid: "{{ nataskid }}"
            devIp: "{{ inventory_hostname }}"
          register: naamResult
          delegate_to: 127.0.0.1
          notify:
            - Final NaTask Update
            - Email Results

  handlers:

    - name: Final NaTask Update
      run_once: true
      vars:
        ansible_python_interpreter: "/opt/apps/netutil/py363venvAns/bin/python3"
      naam_updateNaTaskResults:
        nataskid: "{{ nataskid }}"
        devIp: "FINAL"
      register: naamFinalResult
      delegate_to: 127.0.0.1


(py363venvAns) [netutil@ncc657 ncans]$
```

##### EXPECTED RESULTS

vlan layer 2 interface should be cleanly removed from config

##### ACTUAL RESULTS

```paste below
"msg": "no vn-segment\r\r\n                                     ^\r\n% Invalid command at '^' marker.\r\n\rEDC-SF-LAB-9504-81(config-vlan)# "

```
