### ISSUE TITLE
Apt module returns changed when pkg is already the newest version

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#51758]
##### SUMMARY

Apt module says changed when program is already installed.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

apt
##### ANSIBLE VERSION

```paste below
2.7.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

deb 9
##### STEPS TO REPRODUCE

```yaml
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
    default_release: stable
  loop:
    - libncurses-dev
```

##### EXPECTED RESULTS

Not changed

##### ACTUAL RESULTS

```paste below
libncurses5-dev is already the newest version (6.0+20161126-1+deb9u2).
0 upgraded, 0 newly installed, 0 to remove and 57 not upgraded.
changed: [H2_CT111] => (item=libncurses-dev) => changed=true 
  cache_update_time: 1549369636
  cache_updated: false
  item: libncurses-dev
  stderr: ''
  stderr_lines: []
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    libncurses5-dev is already the newest version (6.0+20161126-1+deb9u2).
    0 upgraded, 0 newly installed, 0 to remove and 57 not upgraded.
  stdout_lines: <omitted>
```
