### ISSUE TITLE
SNS Topic Subscription filter_policy

### ISSUE THREAD

**Issue by bcarpio** [ansible/ansible#51756]
##### SUMMARY
SNS Topic (sns_topic) in Ansible supports subscriptions but it doesn't seem to support subscription filter_policies. 

https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
sns_topic subscriptions. 

##### ADDITIONAL INFORMATION

This feature is important so messages sent to the SNS topic subscriber (Lambda, SQS, etc..) are filtered at the AWS level before it reaches the code or queue subscribed to the topic. 

```yaml

  subscriptions:
    - endpoint: "{{ aws_lambda_result.configuration.function_arn}}"
       protocol: lambda
       filter_policy:
         attribute_a:
           - value_1
           - value_2
         attribute_b:
           - value_3



```
