### ISSUE TITLE
Modules to Create, Delete, List Events in oVirt/RHV

### ISSUE THREAD

**Issue by nasx** [ansible/ansible#51760]
##### SUMMARY
Submitting a pair of oVirt/RHV modules (ovirt_event and ovirt_event_facts) to create, delete and list events in oVirt/RHV.

##### ISSUE TYPE
- New modules

##### COMPONENT NAME
oVirt Modules

##### ADDITIONAL INFORMATION

The modules would be used to create, delete and list events in oVirt/RHV.

```yaml
# Create an event
- ovirt_event:
    state: present
    description: "The file system /home on host xyz is almost full!"
    origin: "mymonitor"
    custom_id: 123456789
    severity: warning

# Return all events of type alert
- ovirt_event_facts:
    search: "severity=alert"
```
