### ISSUE TITLE
add_host allow variable override

### ISSUE THREAD

**Issue by akamac** [ansible/ansible#51811]
##### SUMMARY
`add_host` allows to specify host variables, but if one is already set, it won't be overridden.
Can be related to PR https://github.com/ansible/ansible/pull/13901

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`add_host` module

##### ANSIBLE VERSION
```
ansible 2.7.6 (detached HEAD 1594ccf533) last updated 2019/02/05 02:30:14 (GMT -700)
  config file = /home/amiasoedov/ansible/playbooks/linux/ansible.cfg
  configured module search path = ['/home/amiasoedov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/ansible/ansible/lib/ansible
  executable location = /var/lib/ansible/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```
##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### STEPS TO REPRODUCE
```yaml
- set_fact:
    fact: 1

- add_host:
    name: "{{ inventory_hostname }}"
    groups: g
    fact: 2

- debug: var=fact
```

##### EXPECTED RESULTS
`fact == 2`

##### ACTUAL RESULTS
```
TASK [set_fact]
ok: [localhost] => changed=false
  ansible_facts:
    fact: 1

TASK [add_host]
changed: [localhost] => changed=true
  add_host:
    groups:
    - g
    host_name: localhost
    host_vars:
      fact: 2

TASK [debug]
ok: [localhost] =>
  fact: 1
```
