### ISSUE TITLE
win_uri doesn't work the same as uri

### ISSUE THREAD

**Issue by mikemadeja** [ansible/ansible#51819]
##### SUMMARY
I was using the URI module and it worked on a linux server, I then discovered there's a win_uri module and all I did was change it from uri to win_uri and I get this error below.

fatal: [dinfmkdocsweb02.domain.com]: FAILED! => {"changed": false, "msg": "WebException occurred when sending web request: The underlying connection was closed: An unexpected error occurred on a send.", "url": "https://dev-autom.domain.com/job/Send-HelloWorld/build"}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_uri

##### ANSIBLE VERSION
```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/.mmadeja@iaai.com/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_IDENTITY_LIST(/etc/ansible/ansible.cfg) = [u'svcprdscorch@/etc/ansible/.vp']

```

##### OS / ENVIRONMENT
Ansible is centos 7
Clients running playbook are Windows Server 2016

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: DEV MKDOCS
  hosts: dev-mkdocs
  vars_files:
  - ../../../ps.yml
  vars:
    ad_account01: "svcdevmkdocs"
    iis_site01: "mkdocs"

  tasks:
  - name: Queue build of a project in Jenkins
    win_uri:
      url: https://dev-autom.domain.com/job/Send-HelloWorld/build
      method: POST
      return_content: yes
      status_code: 201
      body_format: json
      headers:
        Content-Length: 0
      validate_certs: no
      user: "USER"
      password: "PASSWORD"
      force_basic_auth: yes
```

##### EXPECTED RESULTS
I expect it to POST to Jenkins like uri module

##### ACTUAL RESULTS

```paste below
fatal: [dinfmkdocsweb02.domain.com]: FAILED! => {"changed": false, "msg": "WebException occurred when sending web request: The underlying connection was closed: An unexpected error occurred on a send.", "url": "https://dev-autom.domain.com/job/Send-HelloWorld/build"}


```
