### ISSUE TITLE
vmware_deploy_ovf - Resource Pool Not Working

### ISSUE THREAD

**Issue by hadfiiw** [ansible/ansible#51826]
##### SUMMARY
In trying to use the vmware_deploy_ovf module, I cannot get the VM to be created in a resource pool.

Not sure if this is a bug in the module, a bug in the documentation, or a layer 8 (me) problem?  I have tried "resource_pool" pointing to....
- The actual name of the resource pool
- The name of the resource pool as a variable
- "/Resources/{{ deploy_resource_pool }}"
- "{{ datacenter }}/{{ deploy_cluster }}/Resources/{{ deploy_resource_pool }}"
- "{{ deploy_cluster }}/Resources/{{ deploy_resource_pool }}"

...with no luck.  Each time, it gets created in the root of the cluster.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_deploy_ovf

##### ANSIBLE VERSION

```
ansible 2.7.6
  config file = /Users/admin/Workspaces/homelab/ansible.cfg
  configured module search path = [u'/Users/admin/Workspaces/homelab/library', u'/Users/admin/Workspaces/homelab/library/vmware', u'/Users/admin/Workspaces/homelab/library/windows', u'/Users/admin/Workspaces/nsxansible/library']
  ansible python module location = /Users/admin/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/admin/Library/Python/2.7/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```
```
pyvmomi                                6.7.1.2018.12
```

##### CONFIGURATION

```
hadfield-mini:homelab admin$ ansible-config dump --only-changed
DEFAULT_FORKS(/Users/admin/Workspaces/homelab/ansible.cfg) = 20
DEFAULT_HOST_LIST(/Users/admin/Workspaces/homelab/ansible.cfg) = [u'/Users/admin/Workspaces/homelab/inventory/hosts
DEFAULT_MODULE_PATH(/Users/admin/Workspaces/homelab/ansible.cfg) = [u'/Users/admin/Workspaces/homelab/library', u'/
DEFAULT_ROLES_PATH(/Users/admin/Workspaces/homelab/ansible.cfg) = [u'/Users/admin/Workspaces/homelab/roles', u'/Use
HOST_KEY_CHECKING(/Users/admin/Workspaces/homelab/ansible.cfg) = False
(END)
```

##### OS / ENVIRONMENT
Running on a Mac Mini with the latest OS

##### STEPS TO REPRODUCE
From my role...
```yaml
- name: "CREATING {{ server_name }} VIA {{ vcenter_username }} IN {{ deploy_vcenter }}, {{ deploy_cluster }} CLUSTER, {{ vcenter_folder }} FOLDER, USING OVA {{ ops_ubuntu_ova }}"
  connection: local
  vmware_deploy_ovf:
   hostname: "{{ deploy_vcenter }}"
   username: "{{ vcenter_username }}"
   password: "{{ hostvars[ deploy_vcenter ]['vcenter_passwd'] }}"
   datacenter: '{{ datacenter }}'
   datastore: '{{ deploy_datastore }}'
   name: '{{ server_name }}'
   networks: '{ "{{ orig_network }}": "{{ deploy_portgroup }}" }'
   cluster: '{{ deploy_cluster }}'
   folder: "{{ datacenter }}/vm/{{ vcenter_folder }}"
   disk_provisioning: '{{ disk_mode }}'
   ovf: "{{ path_to_ova }}/{{ ops_ubuntu_ova }}"
   validate_certs: "{{ validate_certs }}"
   fail_on_spec_warnings: yes
   power_on: no
   wait: no
   wait_for_ip_address: no
   resource_pool: TEST
   properties: '{{ deploy_ovf_properties }}'
```
Have also tried...
```
   resource_pool: "TEST"
   resource_pool: "{{ deploy_resource_pool }}"
   resource_pool: "/Resources/{{ deploy_resource_pool }}"
   resource_pool: "{{ deploy_cluster }}/Resources/{{ deploy_resource_pool }}"
   resource_pool: "/Resources/{{ deploy_cluster }}/{{ deploy_resource_pool }}"
   resource_pool: "{{ datacenter }}/{{ deploy_cluster }}/Resources/{{ deploy_resource_pool }}"
```

##### EXPECTED RESULTS
Expected the VM to be created in the TEST resource pool

##### ACTUAL RESULTS
VM gets created in the root of the cluster - "Resources"

```paste below
changed: [had01-100-ntp-b] => {
    "changed": true, 
    "instance": {
        "annotation": "", 
        "current_snapshot": null, 
        "customvalues": {}, 
        "guest_consolidation_needed": false, 
        "guest_question": null, 
        "guest_tools_status": "guestToolsNotRunning", 
        "guest_tools_version": null, 
        "hw_cores_per_socket": 1, 
        "hw_datastores": [
            "Nested-Lab"
        ], 
        "hw_esxi_host": "had01-sm-esx14.work.local", 
        "hw_eth0": {
            "addresstype": "assigned", 
            "ipaddresses": null, 
            "label": "Network adapter 1", 
            "macaddress": "00:50:56:bb:22:23", 
            "macaddress_dash": "00-50-56-bb-22-23", 
            "portgroup_key": "dvportgroup-69", 
            "portgroup_portkey": "4", 
            "summary": "DVSwitch: 74 e5 3b 50 6b e2 91 f9-cd f0 3b 6b 27 69 ad 80"
        }, 
        "hw_files": [
            "[Nested-Lab] had01-100-ntp-b_13/had01-100-ntp-b.vmx", 
            "[Nested-Lab] had01-100-ntp-b_13/had01-100-ntp-b.vmsd", 
            "[Nested-Lab] had01-100-ntp-b_13/had01-100-ntp-b.vmdk"
        ], 
        "hw_folder": "/had01/vm/Testing", 
        "hw_guest_full_name": null, 
        "hw_guest_ha_state": null, 
        "hw_guest_id": null, 
        "hw_interfaces": [
            "eth0"
        ], 
        "hw_is_template": false, 
        "hw_memtotal_mb": 2048, 
        "hw_name": "had01-100-ntp-b", 
        "hw_power_status": "poweredOff", 
        "hw_processor_count": 2, 
        "hw_product_uuid": "423b98d4-a05f-f992-27c5-2fc533cad705", 
        "hw_version": "vmx-11", 
        "instance_uuid": "503b46f2-80f3-ffd3-1c08-b890add54afb", 
        "ipv4": null, 
        "ipv6": null, 
        "module_hw": true, 
        "snapshots": []
    }, 
    "invocation": {
        "module_args": {
            "allow_duplicates": true, 
            "cluster": "had01-0-nested", 
            "datacenter": "had01", 
            "datastore": "Nested-Lab", 
            "deployment_option": null, 
            "disk_provisioning": "thin", 
            "fail_on_spec_warnings": true, 
            "folder": "had01/vm/Testing", 
            "hostname": "had01-0-core-vc-1.work.local", 
            "name": "had01-100-ntp-b", 
            "networks": {
                "dvs-21-mgmt": "had01-nested-core-infra-vm-21"
            }, 
            "ovf": "/Users/admin/Dropbox/Lab-JB/ubuntu-ops-base-server.ova", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "power_on": false, 
            "properties": {
                "dns_domain": "work.local", 
                "dns_server0": "192.168.21.101 192.168.21.102", 
                "gateway0": "192.168.21.1", 
                "ip0": "192.168.21.254", 
                "subnet_mask0": "255.255.255.0"
            }, 
            "resource_pool": "TEST", 
            "username": "administrator@sso-work.local", 
            "validate_certs": false, 
            "wait": false, 
            "wait_for_ip_address": false
        }
    }
}
Read vars_file '../common.yml'
```

![screen shot 2019-02-06 at 10 45 14 am](https://user-images.githubusercontent.com/22086548/52353508-b6fc5b80-29fc-11e9-9199-ca5f7d3386ff.png)
