### ISSUE TITLE
nios_host_record not idempotent when ip address assigned dynamically via lookup

### ISSUE THREAD

**Issue by victorock** [ansible/ansible#51843]
##### SUMMARY

When using the nios_host_record for a host entry that already exists when trying to assign IP dynamically via lookup, the module fails saying that an entry already exists, instead of behaving as idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios_host_record

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
```

##### CONFIGURATION

```paste below
no special configuration
```

##### OS / ENVIRONMENT

Infoblox NIOS.

##### DEPENDENCY PROBLEMS

```paste below
N/A
```

##### STEPS TO REPRODUCE

```yaml
- name: "Ensure state of Host Record"
  hosts: localhost
  gather_facts: no

  vars:
    nios_provider:
      host: "{{ lookup('ENV', 'INFOBLOX_HOST') }}"
      username: "{{ lookup('ENV', 'INFOBLOX_USERNAME') }}"
      password: "{{ lookup('ENV', 'INFOBLOX_PASSWORD') }}"

    nios_host_record_host: "ansible-test"
    nios_host_record_domain: "acme.com"
    nios_host_record_fqdn: "{{ nios_host_record_host }}.{{ nios_host_record_domain }}"
    nios_host_record_exists: "{{ lookup('nios', 'record:host', filter={'name': nios_host_record_fqdn }) }}"
    nios_host_record_view: "Internal DNS"
    nios_host_record_subnet: "192.168.0.0/24"
    nios_host_record_ipv4addr: "{{ lookup('nios_next_ip', nios_host_record_subnet) }}"
    nios_host_record_state: "present"

  tasks:
    - name: "Ensure state of host record in NIOS"
      nios_host_record:
        provider: "{{ nios_provider }}"
        name: "{{ nios_host_record_fqdn }}"
        view: "{{ nios_host_record_view | default(omit) }}"
        ipv4addrs:
          - ipv4addr: "{{ nios_host_record_ipv4addr[0] }}"
        state: "{{ nios_host_record_state }}"

```

##### EXPECTED RESULTS

When the provided playbook runs twice, a new ip is provided by Infoblox, so the the record should be updated with the new ip.

##### ACTUAL RESULTS

With the current implementation the module fails saying that entry already exists.

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/nios/nios_host_record.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nios/nios_host_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @ganeshrn @gdpak @justjais @privateip @rcarrillocruz @sganesh-infoblox @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @danielmellado
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dsbrng25b** [comment]
Looking up the next free IP, as described in the issue is not a good idea, because that way you have a race condition between looking up the next free IP and creating the host record with that IP.
From Ansible 2.8 on this should be possible in one step:
```
  - name: dynamically add host record to next available ip
    nios_host_record:
      name: dynhost.local
      ipv4:
      - address: {nios_next_ip: 192.168.123.0/24}
      comment: this is a test comment
      state: present
      provider: "{{ nios_provider }}"
    connection: local
    register: infoblox_ip
```
But this is still not idempotent. On the first run it does properly register the next available IP in Infoblox but on the second run I get the following error:
```
TASK [dynamically add host record to next available ip] ****************************************************************************************************************************************************
 [WARNING]: The value {'nios_next_ip': '192.168.123.0/24'} (type dict) in a string field was converted to u"{'nios_next_ip': '192.168.123.0/24'}" (type string). If this does not look like what you
expect, quote the entire value to ensure it does not change.

fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "code": "Client.Ibap.Data.Conflict", "msg": "The record 'dynhost.local' already exists.", "operation": "create_object", "type": "AdmConDataError"}
```
Further, it definitely should be possible to retrieve the newly registered IP with the result of the module. Currently it is only returning `"infoblox_ip": { "changed": true, "failed": false }`

Is actually someone working on this?
