### ISSUE TITLE
LogicMonitor: No collector specified

### ISSUE THREAD

**Issue by aksharbarot** [ansible/ansible#51858]
##### SUMMARY

Trying to keep host in SDT but giving an error "No collector specified"
##### ISSUE TYPE
- Bug Report

As per document, collector is not required if we use display name during execution. 

*This is required for updating, removing or scheduling downtime for hosts if 'displayname' isn't specified (target=host action=update action=remove action=sdt).*

##### COMPONENT NAME

/usr/lib/python2.7/site-packages/ansible/modules/monitoring/logicmonitor.py

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  remote_user: root
  vars:
    company: example
    user: test
    password: 'test@123'
  tasks:
  - name: SDT a host group
    logicmonitor:
      target: host
      action: sdt
      displayname: 'example123'
      duration: 3000
      starttime: '2019-02-07 01:50'
      company: '{{ company }}'
      user: '{{ user }}'
      password: '{{ password }}'
#      collector: mycompany-Collector
    delegate_to: localhost
```

##### ACTUAL RESULTS

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "sdt",
            "alertenable": true,
            "collector": null,
            "company": "example",
            "description": "",
            "displayname": "example123",
            "duration": "3000",
            "fullpath": null,
            "groups": [],
            "hostname": null,
            "id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "properties": {},
            "starttime": "2019-02-07 01:50",
            "target": "host",
            "user": "test"
        }
    },
    **"msg": "No collector specified."**
}

```paste below

```
