### ISSUE TITLE
Azure inventory plugin missing important hostvars that the inventory script has

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#51864]
##### SUMMARY
The Azure inventory plugin does not give sufficient data in hostvars to re-produce the content that we had from the Azure inventory script.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/inventory/azure_rm.py

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
(no output)
```paste below
```

##### OS / ENVIRONMENT
Local machine, Azure account

##### STEPS TO REPRODUCE
Run the inventory script like:

```yaml
AZURE_SUBSCRIPTION_ID=<removed> AZURE_CLIENT_ID=<removed> AZURE_SECRET=<removed> AZURE_TENANT=<removed> ansible-inventory -i contrib/inventory/azure_rm.py --list --export
```

And run:

```yaml
AZURE_SUBSCRIPTION_ID=<removed> AZURE_CLIENT_ID=<removed> AZURE_SECRET=<removed> AZURE_TENANT=<removed> ansible-inventory -i azure_rm.yml --list --export
```

and compare

##### EXPECTED RESULTS
I expect enough information in the output from the azure inventory plugin to at least get more important data that we had from the script

##### ACTUAL RESULTS
There are a great deal of differences, I have digested a large number of them and forced parity where I can. All of the following hostvars are those which I cannot translate from a new key to the old key.

 - fqdn
 - image subdict
   - offer, publisher, sku, version
 - mac_address
 - network_interface & network_interface_id
 - os_disk subdict
   - name, operating_system_type
 - resource_group
 - security_group & security_group_id
 - virtual_machine_size

It may be that not all of these matter, but I'm sure that at least the following are somewhat important, because the information from them are needed from the "group_by" options that existed in the inventory script:

 - os_disk, operating system
 - resource_group
 - security_group

Using the inventory plugin, I expect to be able to create a groups corresponding to resource groups, security groups, and OS.

script logic at the point where hostvars are initialized:

https://github.com/ansible/ansible/blob/e09196f760c0bcf54a523de6a3f1bcffdd38e942/contrib/inventory/azure_rm.py#L691-L713

plugin logic:

https://github.com/ansible/ansible/blob/ff49bbd15d3483af1508e7b540463035e6268817/lib/ansible/plugins/inventory/azure_rm.py#L474-L490

The file for `azure_rm.yml` I'm using has these existing translations from new values to old values, and for restoring old groups.

```yaml

plugin: azure_rm
auth_source: env

hostvar_expressions:
  provisioning_state: provisioning_state | title
  computer_name: name
  type: resource_type
  private_ip: 'private_ipv4_addresses | json_query("[0]")'

keyed_groups:
- prefix: ""
  separator: ""
  key: location
- prefix: ""
  separator: ""
  key: powerstate
- prefix: ""
  separator: ""
  key: name
```

I can do similar things for the other values, but the data needs to exist in the plugin output somewhere for me to do this.
