### ISSUE TITLE
Unable to use ansible_distribution in Mac OS? 

### ISSUE THREAD

**Issue by dhirajdebut** [ansible/ansible#51873]
##### SUMMARY

I want to run a playbook task depending upon the OS. so if OS MacOS then I want to run the task otherwise I don't want to run the task. I have tried `ansible_distribution`  and `ansible_facts` but that does not work for me. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

I am using ansible playbook for executing the task.

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /Users/harmeet/.ansible.cfg
  configured module search path = [u'/Users/harmeet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
MacOS 10.13 High Sierra

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- hosts: pinggroup
  remote_user: arun
  order: sorted
  tasks:
    - name: run this on OSX type systems
      debug: msg="hello from osx"
      when: ansible_distribution == 'MacOSX'
```

##### EXPECTED RESULTS

It shold be able to run a task based on the OS. 

##### ACTUAL RESULTS

It does not run the task based on OS. `ansible_distribution` and `os_family` does not work

```paste below

```
