### ISSUE TITLE
Nested variable value is not expanded when accessing a variable via the vars dictionary

### ISSUE THREAD

**Issue by emz00** [ansible/ansible#51878]
##### SUMMARY
When the value of a variable includes another variable the nested variable is not replaced by its value when reading the first variable via the `vars` dictionary. (It is correctly replaced when reading the variable directly.)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

template/vars

##### ANSIBLE VERSION

```paste below
ansible 2.7.4
  config file = /my/path/ansible.cfg
  configured module search path = [u'/my/home/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/my/path/ansible.cfg) = True
DEFAULT_BECOME(/my/path/ansible.cfg) = True
DEFAULT_HASH_BEHAVIOUR(/my/path/ansible.cfg) = merge
DEFAULT_ROLES_PATH(/my/path/ansible.cfg) = [u'/my/path/roles']
DEFAULT_TRANSPORT(/my/path/ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(/my/path/ansible.cfg) = /my/home/.ansible/password
RETRY_FILES_ENABLED(/my/path/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04.1 x64

##### STEPS TO REPRODUCE

Run the following playbook:

```yaml
---
 - name: "VARS test"
   hosts: localhost
   vars:
     - var1: "the value"
     - var2: "including {{ var1 }}"
   tasks:
     - debug: msg="var1 = {{ var1 }}, var2 = {{ var2 }}, vars[var1] = {{ vars['var1'] }}, vars[var2] = {{ vars['var2'] }}"
```

##### EXPECTED RESULTS
```
"msg": "var1 = the value, var2 = including the value, vars[var1] = the value, vars[var2] = including the value"
```

##### ACTUAL RESULTS

```
"msg": "var1 = the value, var2 = including the value, vars[var1] = the value, vars[var2] = including {{ var1 }}"
```

This looks like the same issue as #9501, but that was closed as a duplicate of #7844, which was closed as fixed, but the issue still occurs in 2.7.4. Note that this happens with group_vars, too.
