### ISSUE TITLE
Add "break_when" to the "loop_control"

### ISSUE THREAD

**Issue by taraspos** [ansible/ansible#51881]
##### SUMMARY

Add the ability to break the loop conditionally.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core

##### ADDITIONAL INFORMATION

```yaml
- set_fact:
       array: ["1", "2", "3", "stop here", "33333333" ]

- debug:
      var: item
   loop: "{{ array }}"
   loop_control:
       break_when: '{{ item }} == "stop here"'
```
