### ISSUE TITLE
gcp_compute inventory plugin missing gce_image, gce_uuid hostvars

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#51884]
##### SUMMARY
The hostvars returned by the gcp_compute inventory plugin offer no information that maps to the variables `gce_image` or `gce_uuid` variables from the old contrib inventory script.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/inventory/gcp_compute.py

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/.virtualenvs/ansible/lib/python2.7/site-packages/ansible-2.8.0.dev0-py2.7.egg/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
(no ouptut)
```paste below
```

##### OS / ENVIRONMENT
local machine, gce account set up

##### DEPENDENCY PROBLEMS
no dependency problems

##### STEPS TO REPRODUCE
I have replicated the vast major of the hostvars that were produced by https://github.com/ansible/ansible/blob/devel/contrib/inventory/gce.py

```yaml
ansible-inventory -i gcp_compute.yml --list
```

`gcp_compute.yml` file:

```yaml
auth_kind: serviceaccount
filters: null
plugin: gcp_compute
hostnames:
  - name
  - public_ip
  - private_ip
projects:
- <removed>

compose:
  ansible_ssh_host: 'networkInterfaces | json_query("[0].accessConfigs[0].natIP")'
  gce_id: id
  gce_description: description
  gce_machine_type: machineType
  gce_name: name
  gce_network: 'networkInterfaces | json_query("[0].network.name")'
  gce_private_ip: 'networkInterfaces | json_query("[0].networkIP")'
  gce_public_ip: 'networkInterfaces | json_query("[0].accessConfigs[0].natIP")'
  gce_status: status
  gce_subnetwork: 'networkInterfaces | json_query("[0].subnetwork.name")'
  gce_tags: 'tags | json_query("items")'
  gce_zone: zone

# missing
# gce_image
# gce_uuid

keyed_groups:
- prefix: ""
  separator: ""
  key: 'networkInterfaces | json_query("[0].networkIP")'  # gce_private_ip
- prefix: ""
  separator: ""
  key: 'networkInterfaces | json_query("[0].accessConfigs[0].natIP")'  # gce_public_ip
- prefix: ""
  separator: ""
  key: machineType
- prefix: ""
  separator: ""
  key: zone
- prefix: tag
  key: 'tags | json_query("items")'  # gce_tags
- prefix: status
  key: 'status | lower'

zones:
  - us-east1-d

service_account_file: private/gce/creds.json
```

##### EXPECTED RESULTS
I expect some way to recreate the image name and the UUID from the script.

They are also grouped by image:

https://github.com/ansible/ansible/blob/dfee94dfc7adeaa5a37a8e7fe19bdb80137e9416/contrib/inventory/gce.py#L501-L505

So I would like to re-produce that group, by using keyed_groups to make a custom group with a name corresponding to the gce image name.

##### ACTUAL RESULTS
There is no apparent way for me to get either of these hostvars with what the plugin currently returns.
