### ISSUE TITLE
--list-tasks isn't accurate

### ISSUE THREAD

**Issue by brandonhilkert** [ansible/ansible#5191]
Playbook:

```
- name: provision server
  gather_facts: false
  hosts:
    - tag_role_{{ role }}

  roles:
    - { role: common, tags: ["production", "staging"] }
    - { role: ruby193, tags: ["production", "staging"] }
    - { role: deployer, tags: ["production", "staging"] }
    - app

- name: upload assets to S3
  gather_facts: false
  hosts:
    - tag_role_{{ role }}[0]

  roles:
    - assets_sync
```

Show tasks:

```
system "ansible-playbook ansible/app.yml ---list-tasks --private-key=~/.ssh/pd-app-server --inventory-file=ansible/hosts/ --tags='staging,web,queue'
```

```
playbook: ansible/app.yml

  play #1 (provision server):
    shell echo 'alias wpld="watch -n 0 \"ps ax | grep unic\""' >> {{bash_file}}
    shell echo 'alias pld="cd {{code_dir}}"' >> {{bash_file}}
    shell echo 'alias rpld="sudo restart pipelinedeals"' >> {{bash_file}}
    shell echo 'alias lpld="tail -f /var/log/syslog"' >> {{bash_file}}
    create log dir
    move old logs and link dir
    restart rsyslog
    update apt
    install htop
    check if timezone has already been set up
    rm /etc/localtime
    link /etc/localtime
    install ntp
    install git
    Don't strict check github.com
    install build tools
    add repo for updated ruby
    install ruby193
    don't install docs
    install bundler
    use multiple cores in bundler
    install rake
    transfer deployer key
    install build tools
    add nginx log directory
    add apt repo for nginx
    install nginx and needed packages
    set up nginx.conf prod
    logrotate nginx
    start nginx
    check if then remote_syslog is installed
    install remote_syslog gem
    add log_files conf for papertrail
    check if remote_syslog is running
    start remote_syslog
    clone source code
    bundle install
    shell echo 'export RESQUE_PASSWORD=baggio77' >> /etc/environment
    install resque_web service
    start resque_web
    shell echo 'export RAILS_ENV={{rails_env}}' >> /etc/environment
    shell echo 'export RACK_ENV={{rails_env}}' >> /etc/environment
    shell echo 'export REDIS_NAMESPACE={{deploy_key}}' >> /etc/environment
    shell echo 'export GIT_BRANCH={{git_branch}}' >> /etc/environment
    shell echo 'export WEB_CONCURRENCY={{web_concurrency}}' >> /etc/environment
    install ruby build dependencies
    clone source code
    bundle install
    add database.yml
    create log dir
    touch log file
    install java
    remove old assets
    remove old assets
    remove old assets
    bundle assets
    drop in web Procfile
    drop in web .foreman
    drop in queue Procfile
    drop in queue .foreman
    drop in staging Procfile
    drop in staging .foreman
    install service
    get status of service
    start pipelinedeals service
    restart pipelinedeals service
```

As you can see it doesn't show playbook #2.

This is what happened when I actually ran it...

```
TASK: [app | get status of service] *******************************************
changed: [ec2-54-234-223-73.compute-1.amazonaws.com]

TASK: [app | start pipelinedeals service] *************************************
changed: [ec2-54-234-223-73.compute-1.amazonaws.com]

TASK: [app | restart pipelinedeals service] ***********************************
skipping: [ec2-54-234-223-73.compute-1.amazonaws.com]

PLAY [upload assets to S3] ****************************************************

TASK: [assets_sync | upload assets to S3 bucket - deal-shared] ****************
```

That last task is from the 2nd playbook. I cut it off b/c it was doing something it shouldn't have. But it was running...
