### ISSUE TITLE
vmware_host_config_manager crashes with ESXi 6.7U1

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#51928]
##### SUMMARY
```
option_manager = host.configManager.advancedOption
host_facts = {}
for option in option_manager.QueryOptions():
  host_facts[option.key] = dict(value=option.value)

for s_option in option_manager.supportedOption:
  host_facts[s_option.key].update(
    option_type=s_option.optionType,
  )
```

`option_manager.supportedOption` returns amongst others 'Vpx.Vpxa.config.log.level'. This setting doesn't exist on a newly installed ESXi 6.7U1. It is a supported option so the code above tries to update `host_fachts['Vpx.Vpxa.config.log.level']`, but this doesn't exist because 'Vpx.Vpxa.config.log.level' isn't returned by `option_manager.QueryOptions()`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_host_config_manager

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/lenzm02/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
vCenter 6.7U1 and newly installed ESXi 6.7U1; doesn't happen with ESXi 6.7U1 when upgraded from 6.5

##### STEPS TO REPRODUCE
Just try to use vmware_host_config_manager with a newly installed 6.7U1 host, no matter what setting you want to change:
```
- hosts: esx-hosts
  connection: local
  tasks:
    - name: Set advanced host settings
      vmware_host_config_manager:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        esxi_hostname: '{{ inventory_hostname }}'
        options:
          'UserVars.ESXiVPsDisabledProtocols': 'sslv3,tlsv1,tlsv1.1'
```

##### EXPECTED RESULTS
I expect ansible to _not_ crash.

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'Vpx.Vpxa.config.log.level'
fatal: [esx67.localdomain]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/lenzm02/.ansible/tmp/ansible-tmp-1549606788.73-67546411886653/AnsiballZ_vmware_host_config_manager.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/lenzm02/.ansible/tmp/ansible-tmp-1549606788.73-67546411886653/AnsiballZ_vmware_host_config_manager.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/lenzm02/.ansible/tmp/ansible-tmp-1549606788.73-67546411886653/AnsiballZ_vmware_host_config_manager.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_vmware_host_config_manager_payload_HcREag/__main__.py\", line 202, in <module>\n  File \"/tmp/ansible_vmware_host_config_manager_payload_HcREag/__main__.py\", line 198, in main\n  File \"/tmp/ansible_vmware_host_config_manager_payload_HcREag/__main__.py\", line 134, in set_host_configuration_facts\nKeyError: 'Vpx.Vpxa.config.log.level'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
