### ISSUE TITLE
Cannot use launch_template name in ec2_instance module

### ISSUE THREAD

**Issue by piroux** [ansible/ansible#51941]
##### SUMMARY

The `ec2_instance` module cannot use LaunchTemplate name because there is the bug on the following line:
https://github.com/ansible/ansible/blob/88df4e22d3a720127e87f1bb74eeaa5e773d63fe/lib/ansible/modules/cloud/amazon/ec2_instance.py#L1109

It should be:
```
if not params.get('launch_template').get('id') and not params.get('launch_template').get('name'):
```

Moreover, there are not any tests for the `launch_template` argument of this module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: ec2_instance

##### ANSIBLE VERSION

```paste below                                                                                 
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/home/piroux/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ***/ansible-project/ansible/lib/ansible
  executable location = ./venv/bin/ansible
  python version = 2.7.14 (default, Sep 18 2017, 00:00:00) [GCC 4.8.4]
```

##### CONFIGURATION
No config

##### STEPS TO REPRODUCE

This does not work: :-1: 

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: "Provison ec2 instance(s)"
      ec2_instance:
        state: present
        name: boom
        region: eu-west-3
        instance_type: t3.small
        launch_template:
          name: my-beloved-launch-template
```

This works: :+1: 

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:
    - name: "Provison ec2 instance(s)"
      ec2_instance:
        state: present
        name: boom
        region: eu-west-3
        instance_type: t3.small
        launch_template:
          id: lt-123456789abcdef
```

##### ACTUAL RESULTS
Results with the name argument:
```
TASK [Provison ec2 instance(s)] ***********************************************************************************************
failed: [localhost] (item=boom) => {"changed": false, "item": "boom", "msg": "Could not create instance with launch template. Either launch_template.name or launch_template.id parameters are required"}
```
