### ISSUE TITLE
user module reports "changed" when it shouldn't

### ISSUE THREAD

**Issue by jagipson** [ansible/ansible#51965]
##### SUMMARY

The user module reports changed when a user change isn't necessary.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

user module
##### ANSIBLE VERSION

```paste below
ansible 2.6.8
ansible 2.6.13
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/jagipson/Projects/ADMIN/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/jagipson/Projects/ADMIN/ansible/ansible.cfg) = [u'/home/jagipson/Projects/ADMIN/ansible/hosts.yml']
DEFAULT_LOCAL_TMP(/home/jagipson/Projects/ADMIN/ansible/ansible.cfg) = /tmp/.ansible/tmp/ansible-local-13837owEnFK
INVENTORY_ENABLED(/home/jagipson/Projects/ADMIN/ansible/ansible.cfg) = ['host_list', 'virtualbox', 'yaml', 'constructed']
```

##### OS / ENVIRONMENT

python 2.6.6
Controller: RHEL 6.10
Inventory Hosts: RHEL 6.10 and RHEL 7.4
##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

Run
```
ansible-playbook -K -l varna bugreport.yml
```

```yaml
# bugreport.yml
---
- hosts: metal
  become: yes
  become_method: sudo
  tasks:
      - include_role:
          name: localusers
        tags: users

# localusers is roles/localusers/tasks/main.yml:
---
- name: Add mygroup group
  group:
      gid: 6029
      name: mygroup
- name: Add ian user
  user:
      name: ian
      uid: 19004
      append: yes
      groups: mygroup
      shell: /bin/zsh
      password: REDACTED
      update_password: on_create
- name: Add ian user2
  user:
      name: ian
      uid: 19004
      append: yes
      groups: mygroup
      shell: /bin/zsh
      password: REDACTED
      update_password: on_create
```

##### EXPECTED RESULTS

I'm expecting the secondf task "Add ian user2" to return ok, but it returns changed

##### ACTUAL RESULTS

subsequent runs of this task should return ok, not changed. 

```paste below
$ ansible-playbook -v  -K -l varna bugreport.yml 
Using /home/jeff/Projects/ADMIN/ansible/ansible.cfg as config file
SUDO password: 

PLAY [metal] ****************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************
ok: [varna]

TASK [include_role : localusers] ********************************************************************************************************************************************************

TASK [localusers : Add mygroup group] ****************************************************************************************************************************************************
ok: [varna] => {"changed": false, "gid": 6029, "name": "mygroup", "state": "present", "system": false}

TASK [localusers : Add ian user] ********************************************************************************************************************************************************
changed: [varna] => {"append": true, "changed": true, "comment": "", "group": 19004, "groups": "mygroup", "home": "/home/ian", "move_home": false, "name": "ian", "password": "NOT_LOGGING_PASSWORD", "shell": "/bin/zsh", "state": "present", "uid": 19004}

TASK [localusers : Add ian user2] *******************************************************************************************************************************************************
changed: [varna] => {"append": true, "changed": true, "comment": "", "group": 19004, "groups": "mygroup", "home": "/home/ian", "move_home": false, "name": "ian", "password": "NOT_LOGGING_PASSWORD", "shell": "/bin/zsh", "state": "present", "uid": 19004}

PLAY RECAP ******************************************************************************************************************************************************************************
varna                      : ok=4    changed=2    unreachable=0    failed=0
```
