### ISSUE TITLE
java_cert module does not accept a file encrypted with ansible-vault in cert_path

### ISSUE THREAD

**Issue by teodorkostov** [ansible/ansible#51984]
##### SUMMARY

`java_cert` module does not accept a file encrypted with `ansible-vault` in `cert_path`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`java_cert`

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /path/to/project/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```
##### CONFIGURATION
```paste below
[defaults]
vault_password_file = vault-pass
```

##### OS / ENVIRONMENT

ArchLinux

##### STEPS TO REPRODUCE

```yaml
java_cert:
  cert_path: "/path/to/{{item}}.crt.vault"
  cert_alias: "{{item}}"
  keystore_path: "/path/to/store.jks"
  keystore_pass: 1234567890
  keystore_create: yes
loop
  - localhost
```

##### EXPECTED RESULTS

I would expect that `java_cert` transparently handles certificate files that are encrypted with `ansible-vault` when the vault password file is specified in the `ansible.cfg`.

##### ACTUAL RESULTS

```paste below
failed: [localhost] (item=localhost) => {"changed": false, "cmd": "keytool -importcert -noprompt -keystore '/path/to/store.jks' -storepass '********' -file '/path/to/localhost.crt.vault' -alias 'localhost'", "item": "localhost", "msg": "keytool error: java.lang.Exception: Input not an X.509 certificate\n", "rc": 1}
```
