### ISSUE TITLE
vmware_vmkernel: Portgroup name vmk1 not found

### ISSUE THREAD

**Issue by aksharbarot** [ansible/ansible#52006]
##### SUMMARY

Module is searching for port group in esxi while editing value in vmk nic but, actually no port groups are configured in esxi side. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

/usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_vmkernel.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

```yaml
   -  name: Add Management vmkernel port using static network type
      vmware_vmkernel:
       hostname: vc01.example.com
       username: test
       password: 'test@123'
       vswitch_name: vmk1
       portgroup_name: NFS
       esxi_hostname: esx01.example.com
       vlan_id: 490
       network:
        type: 'static'
#        ip_address: 192.168.127.10
        subnet_mask: 255.255.255.0
       state: present
       enable_mgmt: True
      delegate_to: localhost

```

##### ACTUAL RESULTS

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "enable_ft": null,
            "enable_mgmt": true,
            "enable_vmotion": null,
            "enable_vsan": null,
            "esxi_hostname": "esx01.example.com",
            "hostname": "vc01.example.com",
            "ip_address": null,
            "mtu": 1500,
            "network": {
                "ip_address": null,
                "subnet_mask": "255.255.255.0",
                "type": "static"
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "portgroup_name": "vmk1",
            "state": "present",
            "subnet_mask": null,
            "username": "test",
            "validate_certs": true,
            "vlan_id": 490,
            "vswitch_name": "dvSwitch0"
        }
    },
    "msg": "Portgroup name vmk1 not found"
}

```paste below

```

**Port groups is not present in esxi**

vmk1
   Name: vmk1
   MAC Address: 00:00:00:00:00:00
   Enabled: true
   Portset: DvsPortset-0
   **Portgroup: N/A**
   Netstack Instance: defaultTcpipStack
   VDS Name: dvSwitch0
   VDS UUID: 00 00 00 00 00 
   VDS Port: 166
   VDS Connection: 1000000000
   Opaque Network ID: N/A
   Opaque Network Type: N/A
   External ID: N/A
   MTU: 1500
   TSO MSS: 65535
   Port ID: 33554439
