### ISSUE TITLE
Need ability to make group of groups in keyed_groups

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#52035]
##### SUMMARY
The old `ec2.py` script in the contrib folder had the ability to group types of groups into a group for the category name. For example, groups named `tags`, `zones`, `instances`, `regions`, and others.

The current aws_ec2 inventory plugin has no corresponding capability, and since it needs groups constructed via `keyed_groups`, it begs an obvious implementation that the individual keyed group definition take a parameter to make a common parent group for all the groups that it creates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py

Implementation would actually be in the `Constructable` class, but I put aws_ec2, because this is the only contrib script I know of that implemented groups of groups.

##### ADDITIONAL INFORMATION
This would be specified via an additional argument to the individual keyed group arguments.

For sake of demonstration, I will call this key `parent_group`. The following inventory file should re-create the relevant groups that `ec2.py` used to produce.

```yaml
plugin: aws_ec2

keyed_groups:
  - prefix: tag
    key: tags
    parent_group: tags
  - prefix: key
    key: key_name
    parent_group: keys
  - prefix: ""
    separator: ""
    key: placement.region
    parent_group: regions
  - prefix: ""
    separator: ""
    key: placement.availability_zone
    parent_group: zones
  - prefix: platform
    key: platform
    parent_group: platforms
  - prefix: vpc_id  # redundant naming
    key: vpc_id
    parent_group: vpcs
  - prefix: type
    key: instance_type
    parent_group: types
  - prefix: instance_state
    key: state.name
    parent_group: instance_states
```

These correspond to:

https://github.com/ansible/ansible/blob/c581fbd0be95f7dde73004b682b1f908ce442a71/contrib/inventory/ec2.py#L961-L1035

Using functional tests, I have confirmed the existence of the above named parent groups from the old script.

Wherever `parent_group` is defined, a group by that name should be created, and any keyed groups created by the rule specified in the `key` should be added as a child of that group.
