### ISSUE TITLE
cannot globally set TOWER_VERIFY_SSL for tower modules

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#52047]
##### SUMMARY
You cannot globally set SSL verification for the tower_* modules.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_organization (et al)

##### ANSIBLE VERSION
```
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/notting/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 19:49:22) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]
```

##### CONFIGURATION
```ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
whatever, doesn't matter

##### STEPS TO REPRODUCE

The Tower modules/underlying library let you specify arguments via environment variables so you don't have to set module parameters all the time.

Examples: TOWER_HOST, TOWER_PASSWORD, TOWER_VERIFY_SSL

```
  environment:
    TOWER_USERNAME: admin
    TOWER_PASSWORD: "{{ tower_password }}"
    TOWER_HOST: "https://{{ tower_host }}/"

  tasks:
  - name: create default organization
    tower_organization:
       name: someorg
       state: present
```

##### EXPECTED RESULTS

all tower-cli parameters  to work

##### ACTUAL RESULTS

Settings for SSL verification do not work.

Let's go to the code!

lib/ansible/module_utils/ansible_tower.py
```
class TowerModule(AnsibleModule):
    def __init__(self, argument_spec, **kwargs):
        args = dict(
            tower_host=dict(),
            tower_username=dict(),
            tower_password=dict(no_log=True),
            tower_verify_ssl=dict(type='bool', default=True),
            tower_config_file=dict(type='path'),
        )
        args.update(argument_spec)
```

We do want the user to be able to override the environment with module args if you want. However... since we set a default for the verify_ssl parameter... we'll never ever use the environment var. Oops.
