### ISSUE TITLE
Feature request: vmware_host_kernel_manager

### ISSUE THREAD

**Issue by alongchamps** [ansible/ansible#52079]
##### SUMMARY
This script configures kernel module options on an ESXi host or a cluster

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_host_kernel_manager

##### ADDITIONAL INFORMATION
I have already written this module, a PR will be incoming as soon as I make sure it passes all the checks and ansible-docs.
This would be used to configure ESXi kernel module settings which are specified by module name and then a space-separated list of name=value sets (see example below). By configuring these settings, administrators can ensure that the kernel module settings are consistent.

```yaml
- name: Using cluster_name, ensure consistency across a cluster
vmware_host_kernel_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster_name: '{{ virtual_cluster_name }}'
    kernel_module_name: "vmw_psp_rr"
    kernel_module_option: "maxPathsPerDevice=2"
```
