### ISSUE TITLE
ec2_lc snapshot_id ignored

### ISSUE THREAD

**Issue by mauricerashad** [ansible/ansible#52085]
##### SUMMARY
Unable to create a launch configuration which returns the snapshot id to be used for an EBS volume that is different from the snapshot of the source AMI, though the module will accept the playbook and run successfully. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_lc

##### ANSIBLE VERSION

```  
config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/$USERNAME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/$USERNAME/homebrew/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /Users/$USERNAME/homebrew/Cellar/ansible//2.7.1/bin/ansible
  python version = 3.7.0 (default, Oct 31 2018, 14:21:29) [Clang 9.0.0 (clang-900.0.39.2)]

```

##### CONFIGURATION

```
[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of Ansible Become, which is a generic framework. See become_user. , use
become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /Users/$USERNAME/.ssh/id_rsa
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
OS X Sierra (10.12.6)

##### STEPS TO REPRODUCE
Define an ec2_lc task that specifies an EBS volume created from an EC2 instance's 2nd block device (/dev/sdb)

```yaml

    - name: Set Volume Facts
      set_fact:
        volumes:
        - device_name: /dev/sda1
          volume_size: 20
          ebs:
            snapshot_id: snap-XXXX
            volume_type: gp2
            delete_on_termination: true
            encrypted: no
        - device_name: /dev/sdb1
          volume_size: 15
          ebs:
            snapshot_id: snap-xxxx
            volume_type: gp2
            delete_on_termination: true
            encrypted: no

    - name: Create Launch Configuration
      ec2_lc:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ region | default('us-east-1') }}"
        name: lc1
        assign_public_ip: yes
        image_id: ami-xxxx
        instance_type: t2.medium
        key_name: my-key
        security_groups: "['sg-xxxx']"
        volumes: "{{ volumes }}"
      register: lc_info



```

##### EXPECTED RESULTS
```yaml
TASK [OUTPUT] ***********************************************************************************************************************
ok: [localhost] => {
    "lc_info": {
        "arn": "arn:aws:autoscaling:us-east-1:694543856728:launchConfiguration:49b6569f-420d-4aa6-ae36-30d0b5e0c7a8:launchConfigurationName/lc1",
        "changed": true,
        "created_time": "2019-02-12 15:22:28.042000+00:00",
        "failed": false,
        "image_id": "ami-xxxx",
        "instance_type": "t2.medium",
        "name": "lc1",
        "result": {
            "associate_public_ip_address": true,
            "block_device_mappings": [
                {
                    "device_name": "/dev/sda1",
                    "volume_size": 20,
                    "virtual_name": snap-XXXX
                },
                {
                    "device_name": "/dev/sdb1",
                    "ebs": {
                        "snapshot_id": snap-xxxx,
                        "volume_size": 15
                    },
                    "virtual_name": null
                }
            ],
            "classic_link_vpc_security_groups": [],
            "created_time": "2019-02-12 15:22:28.042000+00:00",
            "ebs_optimized": false,
            "image_id": "ami-xxxx",
            "instance_monitoring": false,
            "instance_type": "t2.medium",
            "kernel_id": "",
            "key_name": "my-key",
            "launch_configuration_arn": "arn:aws:autoscaling:us-east-1:694543856728:launchConfiguration:49b6569f-420d-4aa6-ae36-30d0b5e0c7a8:launchConfigurationName/lc1",
            "launch_configuration_name": "lc1",
            "ramdisk_id": "",
            "security_groups": [
                "sg-xxxx"
            ],
            "user_data": ""
        },
        "security_groups": [
            "sg-xxxx"
        ]
    }
}
```
##### ACTUAL RESULTS

```yaml

TASK [OUTPUT] ***********************************************************************************************************************
ok: [localhost] => {
    "lc_info": {
        "arn": "arn:aws:autoscaling:us-east-1:694543856728:launchConfiguration:49b6569f-420d-4aa6-ae36-30d0b5e0c7a8:launchConfigurationName/lc1",
        "changed": true,
        "created_time": "2019-02-12 15:22:28.042000+00:00",
        "failed": false,
        "image_id": "ami-xxxx",
        "instance_type": "t2.medium",
        "name": "lc1",
        "result": {
            "associate_public_ip_address": true,
            "block_device_mappings": [
                {
                    "device_name": "/dev/sda1",
                    "volume_size": 20,
                    "virtual_name": null
                },
                {
                    "device_name": "/dev/sdb1",
                    "ebs": {
                        "snapshot_id": null,
                        "volume_size": 15
                    },
                    "virtual_name": null
                }
            ],
            "classic_link_vpc_security_groups": [],
            "created_time": "2019-02-12 15:22:28.042000+00:00",
            "ebs_optimized": false,
            "image_id": "ami-xxxx",
            "instance_monitoring": false,
            "instance_type": "t2.medium",
            "kernel_id": "",
            "key_name": "my-key",
            "launch_configuration_arn": "arn:aws:autoscaling:us-east-1:694543856728:launchConfiguration:49b6569f-420d-4aa6-ae36-30d0b5e0c7a8:launchConfigurationName/lc1",
            "launch_configuration_name": "lc1",
            "ramdisk_id": "",
            "security_groups": [
                "sg-xxxx"
            ],
            "user_data": ""
        },
        "security_groups": [
            "sg-xxxx"
        ]
    }
}
```

If the AMI snapshot_id is not provided in volumes dict, it will still be reflected in the console, though subsequent volumes with snapshot_ids will have their type and size reflected but source snapshot_id missing...

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_lc.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_lc.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @garethr @wilvk
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mauricerashad, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mauricerashad** [comment]
I think I just resolved this one.

Don't specify 'snapshot_id', but rather simply 'snapshot' followed by the 'snap-xxxx' id.

In ec2_lc.py, lines 431 and 432 provided the clue that it's looking for 'snapshot' and not 'snapshot_id'.

After replacing the volume dict with snapshot, I get the expected results:
```yaml
                {
                    "device_name": "/dev/sdb1",
                    "ebs": {
                        "snapshot_id": "snap-xxxx",
                        "volume_size": 15
                    },
                    "virtual_name": null
                }
            ],
```
