### ISSUE TITLE
Unable to install apt package(s) - (needs info)

### ISSUE THREAD

**Issue by rcrowe** [ansible/ansible#5209]
```
Ansible version: 1.4.1
OS: ubuntu 12.04
```

I've created a [gist](https://gist.github.com/rcrowe/7831319) showing what I ran & got as output.
- I run the example playbook with no errors reported
- SSH in, type `git` but the command isn't found
- `sudo apt-get install git` works fine

**Comment by jctanner** [comment]
```
ansible-playbook -i provisioning/ansible_hosts provisioning/playbook.yml --sudo -vvvv
---
- name: Common configuration for all nodes
  hosts: all
  tasks:
    - name: Upgrade apt packages
      apt: upgrade=full update_cache=yes
    - name: Install git
      apt: pkg=git
```

```
TASK: [Install git] ***********************************************************
<10.0.0.200> ESTABLISH CONNECTION FOR USER: vagrant
<10.0.0.200> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/Rob/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'IdentityFile=/Users/Rob/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '10.0.0.200', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1386361248.02-135525040788606 && chmod a+rx $HOME/.ansible/tmp/ansible-1386361248.02-135525040788606 && echo $HOME/.ansible/tmp/ansible-1386361248.02-135525040788606'"]
<10.0.0.200> REMOTE_MODULE apt pkg=git
<10.0.0.200> PUT /var/folders/v7/rlw2x8ys7rd5tq17pbfv223r0000gn/T/tmpzF5Mvw TO /home/vagrant/.ansible/tmp/ansible-1386361248.02-135525040788606/apt
<10.0.0.200> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/Rob/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'IdentityFile=/Users/Rob/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '10.0.0.200', '/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=friupcnbuwrzcnvpknvczltynkxlwfao] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-friupcnbuwrzcnvpknvczltynkxlwfao; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-1386361248.02-135525040788606/apt; rm -rf /home/vagrant/.ansible/tmp/ansible-1386361248.02-135525040788606/ >/dev/null 2>&1\'"\'"\'\'']
ok: [10.0.0.200] => {"changed": false}
```
