### ISSUE TITLE
Cpanm module tasks hang on newer ansible version 2.7.7

### ISSUE THREAD

**Issue by katrinerachitsky** [ansible/ansible#52124]
##### SUMMARY

Cpanm module hangs on newer ansible version 2.7.7, executes properly for `2.6.4` and `2.6.12`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cpanm

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
``` 
(no output)

##### OS / ENVIRONMENT

control server:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---

- hosts: all
  become: yes
  tasks:

  - name: Install perl modules
    cpanm:
     name: '{{ item.name }}'
     notest: yes
     system_lib: yes
     executable: /usr/bin/cpan
    with_items:
      - { name: 'XML::Twig' }
      - { name: 'XML::Parser' }
      - { name: 'XML::Simple' }
```

##### EXPECTED RESULTS

Each perl module listed under `with_items` should be 'changed' or `ok` in the ansible output

example from a control server with a lower version of ansible:
```
TASK [Install perl modules] ****************************************************
changed: [<hostname>] => (item={u'name': u'XML::Twig'})
ok: [<hostname>] => (item={u'name': u'XML::Parser'})
ok: [<hostname>] => (item={u'name': u'XML::Simple'})
```

version of ansible on control server:
```
ansible 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

##### ACTUAL RESULTS

```paste below
mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 4921\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master
```
note that this is only occurring with -vvvv, without all I see is that the steps seem to hang. Note that this works perfectly on multiple versions of `2.6`
