### ISSUE TITLE
Allow to pass full dicts to vars in 'include_role'

### ISSUE THREAD

**Issue by lc-nyovchev** [ansible/ansible#52187]
##### SUMMARY

It's very useful when programming something with inheritance and you want to override the base variables.

Imagine the following situation. Let's say I have a **base** role and many roles which inherit it by using `include_role`, one of them being a role called **child**:

In the **base** role I have a variable in `roles/base/vars/main.yaml` defined like this:

`someVariable: "defaultBaseValue"`

in the inheriting role I have **the same** variable in `roles/child/vars/main.yaml` defined like this:

`someVariable: "overriding"`

Then I want my **child** role to **inherit** the **base** role, so I use the `include_role` directive.
Then in my **child** role my task is as follows `roles/child/tasks/main.yaml`:

```
## read the variables from the main.yaml of the Child role
- include_vars:
    file: main.yaml
    name: overriding_vars

## attempt to pass those variables to the Base role
- name: Include the base role
  include_role:
    name: base 
  vars:  "{{ overriding_vars }} " #this syntax doesn't work
```
What I want to do is get my child role's variables to **override those** of the base role. All of them! I don't want to assign them to a **new sub-level of dictionary**, I don't want to have all this complexity. I just want to have variable inheritance where my child's role variables override the variables of the base role.

If we can pass variables like this to the `include_role` directive:

```
- name: Include the base role
  include_role:
    name: base 
  vars:  
    - var1: "bla"
    - var2: "bla"
```
I think it's a completely reasonable request to want to be able to pass a whole dict to the Include_role in situation where you actually don't have an overview of all the variables that you want to override.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`include_role`

##### ADDITIONAL INFORMATION

I want to achieve something like this:

```
vars:
    dictionary:
         someVar: "someVal"
         someOtherVar: "someOtherVar"
    
include_role:
    name: "base"
    vars: {{ dictionary }}
```

but right now it's not possible to have it on the first level, we are advised to do things like:

```
vars:
    dictionary:
         someVar: "someVal"
         someOtherVar: "someOtherVar"
    
include_role:
    name: "base"
    vars: 
       dictionary: {{ dictionary }}
```

Which is completely weird cause then in our base role we have to refer to these variables like:

{{ dictionary.dictionary.someVar }}

This'd help a lot if we want proper role inheritance where one role's variables are overridden from the other role's variables as described in https://github.com/ansible/ansible/issues/48709 by @juanvalino
