### ISSUE TITLE
Cobbler module cobbler_system validate_certs error

### ISSUE THREAD

**Issue by Neurozone** [ansible/ansible#52239]
##### SUMMARY

With validate_certs: no using module cobbler_system , the module is  validating certificate:

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Connection to 'https://xxxxxx:443/cobbler_api' failed. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cobbler_system
##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules/oneview-ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/ansible/ansible-stuff/inventory']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/etc/ansible/modules/oneview-ansible/library']
DEFAULT_MODULE_UTILS_PATH(env: ANSIBLE_MODULE_UTILS) = [u'/etc/ansible/modules/oneview-ansible/library/module_utils']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7.6
```
cat /etc/python/cert-verification.cfg
# Possible values are:
# 'enable' to ensure HTTPS certificate verification is enabled by default
# 'disable' to ensure HTTPS certificate verification is disabled by default
# 'platform_default' to delegate the decision to the redistributor providing this particular Python version

# For more info refer to https://www.python.org/dev/peps/pep-0493/
[https]
verify=platform_default
```
##### DEPENDENCY PROBLEMS
If you're having problems with a Python library (e.g. you've installed a library but
Ansible is still telling you it's missing) add a task to the failing playbook:

```
- python_requirements_facts:
    dependencies:
      - $PROBLEM_LIBRARY (e.g. openshift, boto3, etc.)
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:

    - name: Query a specific system in Cobbler
      cobbler_system:
        host: cobbler01
        username: cobbler
        password: cobblerpass
        name: 'xxxxxxx'
        validate_certs: no
      register: cobbler_properties
      delegate_to: localhost

```

##### EXPECTED RESULTS

seeing system information

##### ACTUAL RESULTS

```paste below
TASK [Query a specific system in Cobbler] *********************************************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Connection to 'https://xxxxxx:443/cobbler_api' failed. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)"}
```
