### ISSUE TITLE
Unclear error message when using with_first_found in a role

### ISSUE THREAD

**Issue by guillemlc** [ansible/ansible#5227]
Hello.
Michael DeHaan asked for this to be an issue here after a post in google groups.

I try to use this:

http://www.ansibleworks.com/docs/playbooks_conditionals.html#selecting-files-and-templates-based-on-variables

This is for ansible 1.3.4

/etc/ansible/roles/common/templates# ls -lrt _some_
-rw-------. 1 root root 750 Dec  6 11:49 host1.some.conf.j2
-rw-r--r--. 1 root root 700 Dec  6 12:06 some.conf.j2

```
- name: Make sure configuration is correct.
  template: src={{ item }} dest=/etc/some.conf
  with_first_found:
    files:
       - ${ansible_hostname}.some.conf.j2
       - some.conf.j2
    paths:
       - ../templates
       - ../files
  tags:
    - common
    - auth
```

When I run:

```
TASK: [Make sure configuration is correct.] ******************************
 fatal: [host1] => input file not found at /etc/ansible/roles/common/templates/None or /etc/ansible/None
```

FATAL: all hosts have already failed -- aborting

So, the files exist, both the specific and the default. The pattern is as per given example.

This seems to be unclear as the files do exist, but do not seem to be found as expected.

Let me know what other information I can provide.

**Comment by mpdehaan** [comment]
Thanks, tweaked caption/formatting a bit

**Comment by mpdehaan** [comment]
unrelated public service announcement, should be:

```
- "{{ansible_hostname}}.conf.j2"
```

Legacy variables are on the way out.

**Comment by guillemlc** [comment]
Noted. I actually tried many combinations as I though that was the problem.
- name: Make sure some configuration is correct.
  template: src={{ item }} dest=/etc/some/some.conf
  with_first_found:
    templates:
       - $ansible_hostname.some.conf.j2     <<<< here
       - some.conf.j2
    paths:
       - ../templates
       - ../files
    skip: False
  tags:
  - common
  - some

I tried {{ansible_hostname}}  -> Syntax error   (counter intuitive to me, also it appears like that in the example).
I tried ${ansible_hostname}  -> Produces the error described.
I tried "{{ansible_hostname}} -> Produces the same error.

Using copy and files, instead of  template and templates, produces the same errors. 
- name: Make sure some configuration is correct.
  copy: src={{ item }} dest=/etc/some/some.conf
  with_first_found:
    files:
       - ${ansible_hostname}.some.conf.j2
       - some.conf.j2
    paths:
       - ../templates
       - ../files
    skip: False
  tags:
  - common
  - some
    _______________

Thanks for looking into this. I find this feature vastly important, I used it extensively in Puppet.

**Comment by jctanner** [comment]
@guillemlc this appears to actually be a typo in the doc example. I'll fix that in the docs, but here's how to fix your playbook:

```
  with_first_found:
    - files:
        - "{{ inventory_hostname + '.some.conf.j2' }}"
        - some.conf.j2
      paths:
        - ../templates
        - ../files
```

Notice that "files" is now prefixed with a hyphen. This causes "files" and "path" to become part of the same data structure(dict). Without the hypen, "files" is a list item and "path" is a list item and neither are related to eachother and therefore will not evaluate to real files ... aka None.

More examples: http://docs.ansible.com/playbooks_loops.html?highlight=loops#finding-first-matched-files
