### ISSUE TITLE
Windows FAQ should mention possible SSL protocol issue

### ISSUE THREAD

**Issue by Yvan-Masson** [ansible/ansible#52316]
##### SUMMARY

TLS 1.0 is by default the maximum TLS supported version on Windows 7. However, Linux distributions (at least Debian) begin to disable it to allow TLS 1.2 as a minimum. Thus by default connection fails with this message:

`ntlm: HTTPSConnectionPool(host='my-host', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)')))
`
Could you explain this issue on https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html and add the possible workarounds (enable TLS 1.2 on Windows 7 target / temporary re-enable TLS 1.0 on controller) that are well described on the original discussion on https://groups.google.com/forum/#!msg/ansible-project/CCjQTWSAt4I/mHsdpJGUAwAJ ?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

windows_faq.rst

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Debian testing with openssl 1.1.1a-1.

##### ADDITIONAL INFORMATION

Windows 7 is probably still a common target, and Debian Buster (next stable probably available in the summer) will probably be a common controller, so this issue should be briefly explained in the documentation.

Regards,
Yvan

**Comment by ansibot** [comment]
Files identified in the description:
* [docs/docsite/rst/user_guide/windows_faq.rst](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/windows_faq.rst)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @acozine
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by L1ghtman2k** [comment]
Yeah, I just had the same problem, I guess I will just use no encryption at all then :/

**Comment by jborean93** [comment]
@L1ghtman2k, not sure what you mean, this doesn't mean that encryption isn't available but that the Windows host you are connecting to doesn't offer the required TLS protocol that the client can handle. The end result is that you should explicitly enable TLS 1.2 through some registry keys on the Windows hosts so it does support TLS 1.2. This can be done with the following Ansible task but it can also be converted to a simple PowerShell script;

```
- name: enable TLSv1.2 support
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\{{ item.type }}
    name: '{{ item.property }}'
    data: '{{ item.value }}'
    type: dword
    state: present
    register: pri_personalise_tls_config
  loop:
  - type: Server
    property: Enabled
    value: 1
  - type: Server
    property: DisabledByDefault
    value: 0
  - type: Client
    property: Enabled
    value: 1
  - type: Client
    property: DisabledByDefault
    value: 0

- name: reboot fi TLS config was applied
  win_reboot:
  when: pri_personalise_tls_config is changed
```

If you cannot do this through Ansible a simple PowerShell script can be used;

```
Function Enable-TLS12 {
    param(
        [ValidateSet("Server", "Client")]
        [String]$Component = "Server"
    )

    $protocols_path = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols"
    New-Item -Path "$protocols_path\TLS 1.2\$Component" -Force
    New-ItemProperty -Path  "$protocols_path\TLS 1.2\$Component" -Name Enabled -Value 1 -Type DWORD -Force
    New-ItemProperty -Path  "$protocols_path\TLS 1.2\$Component" -Name DisabledByDefault -Value 0 -Type DWORD -Force
}
Enable-TLS12 -Component Server

# Not required but highly recommended to enable the Client side TLS 1.2 components
Enable-TLS12 -Component Client
```

If you can't do this you can still have encryption over WinRM by using NTLM, Kerberos, or CredSSP as the auth. They have their own mechanism for encrypting the WinRM messages but NTLM isn't as secure. In reality there should be no reason why you can't just enable TLS 1.2 on the Windows host and use that. There's a reason why TLS 1.0 is not enabled on newer distros.
