### ISSUE TITLE
Do not force sort_keys in to_nice_json

### ISSUE THREAD

**Issue by Marthym** [ansible/ansible#52321]
##### SUMMARY

Actually it is not possible to have a formated json without sorting keys. It should be usefull to have the possibility to only format and indent without sorting keys.

##### ISSUE TYPE
- Improvement

##### COMPONENT NAME
plugins/filter/core.py

##### ADDITIONAL INFORMATION

* ansible version: 2.7.7

```yaml
- name: "Write {{ project_root }}/package.json"
  copy: 
    content: "{{ package_json | to_nice_json(sort_keys=False) }}" 
    dest: "{{ project_root }}/package.json"
```
