### ISSUE TITLE
Duplicate role execution with dependencies (again)

### ISSUE THREAD

**Issue by monsterry** [ansible/ansible#52323]
##### SUMMARY

Roles are executed more then once when loaded via dependencies and when imported/included twice . There are several old bug report describing exactly this behavior (z.B: #9578, #14582, #50522). However they all use different include mechanism. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

##### STEPS TO REPRODUCE

```
$ tree
.
├── playbook.yml
└── roles
    ├── test1
    │   └── tasks
    │       └── main.yml
    ├── test2
    │   └── meta
    │       └── main.yml
    └── test3
        └── meta
            └── main.yml
```

```yaml
# playbook.yml
---
- name: 'Play using "old" syntax'
  hosts: localhost
  gather_facts: false
  roles:
    - role: "test1"
    - role: "test1"
    - role: "test2"
    - role: "test3"

- name: 'Play using new include syntax'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: "test1"
    - include_role:
        name: "test1"
    - include_role:
        name: "test2"
    - include_role:
        name: "test3"

- name: 'Play using new import syntax'
  hosts: localhost
  gather_facts: false
  tasks:
    - import_role:
        name: "test1"
    - import_role:
        name: "test1"
    - import_role:
        name: "test2"
    - import_role:
        name: "test3"
```

```yaml
#  roles/test1/tasks/main.yml
---
- name: Debug test1
  debug:
    msg: "test1"
```
```yaml
#  roles/test2/meta/main.yml
#  roles/test3/meta/main.yml
---
dependencies:
    - role: test1
```

##### EXPECTED RESULTS

IMHO there should be no difference which of the include-styles are used, in all cases task `Debug test1` should be executed only once. Furthermore I expect `--list-tasks` to display executed tasks correctly for all cases.

###### List tasks
On all three include-styles `--list-tasks` shows execution for task incorrect:
```
$ ansible-playbook playbook.yml --list-tasks

playbook: playbook.yml

  play #1 (localhost): Play using "old" syntax	TAGS: []
    tasks:
      test1 : Debug test1	TAGS: []
      test1 : Debug test1	TAGS: []
      test1 : Debug test1	TAGS: []

  play #2 (localhost): Play using new include syntax	TAGS: []
    tasks:
      include_role	TAGS: []
      include_role	TAGS: []
      include_role	TAGS: []
      include_role	TAGS: []

  play #3 (localhost): Play using new import syntax	TAGS: []
    tasks:
      test1 : Debug test1	TAGS: []
      test1 : Debug test1	TAGS: []
      test1 : Debug test1	TAGS: []
      test1 : Debug test1	TAGS: []
```

Old style recognizes double role inclusion, but `import_role` and `include_role` style do not. All of them do not detect duplicate role injection via dependencies.

###### Execute tasks

```
ansible-playbook playbook.yml

PLAY [Play using "old" syntax] ****************************************************************************************************

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

PLAY [Play using new include syntax] **********************************************************************************************

TASK [include_role : test1] *******************************************************************************************************

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

TASK [include_role : test1] *******************************************************************************************************

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

TASK [include_role : test2] *******************************************************************************************************

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

TASK [include_role : test3] *******************************************************************************************************

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

PLAY [Play using new import syntax] ***********************************************************************************************

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

TASK [test1 : Debug test1] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test1"
}

PLAY RECAP ************************************************************************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=0   
```

Well here at least old-style works correctly and the task is executed only once. The new-styles both execute the task four times.

```paste below

```

EDIT: Typo

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The new syntax does not use the old duplicates handling as they have explicit options to handle duplicates.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by monsterry** [comment]
Im am very sorry, that this issue was closed, as I changed the setup as follows and still get the results mentionend above:

```
# playbook.yml
---
- name: 'Play using "old" syntax'
  hosts: localhost
  gather_facts: false
  roles:
    - role: "test1"
    - role: "test1"
    - role: "test2"
    - role: "test3"

- name: 'Play using new include syntax'
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: "test1"
        allow_duplicates: False
    - include_role:
        name: "test1"
        allow_duplicates: False
    - include_role:
        name: "test2"
        allow_duplicates: False
    - include_role:
        name: "test3"
        allow_duplicates: False

- name: 'Play using new import syntax'
  hosts: localhost
  gather_facts: false
  tasks:
    - import_role:
        name: "test1"
        allow_duplicates: False
    - import_role:
        name: "test1"
        allow_duplicates: False
    - import_role:
        name: "test2"
        allow_duplicates: False
    - import_role:
        name: "test3"
        allow_duplicates: False
```

And 
```
 roles/test1/meta/main.yml 
---
allow_duplicates: False
```

Btw I tested with `no` instead of `False` same result. When looking at the integration tests I can't see any integration test for `import_role` or `include_role` that could be a good example on how to avoid deduplication. Also the issue for `--list-tasks` persists, which should be solved at least for `import_role`.

As for now, deduplication is not working for me at all for the new syntax. Please provide at least one example working for you.
