### ISSUE TITLE
'is not JSON serializable' when using hashed vault secret with copy module

### ISSUE THREAD

**Issue by tlofreso** [ansible/ansible#52339]
##### SUMMARY

When running a playbook that references a vault string, I get the following message:

`raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: u'cleartextpass' is not JSON serializable\n`

This error arises when running a task that uses the copy module.
My playbook also uses the ios_command module, and that task runs successfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/module_utils/connection.py`

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(/home/taml006/quicklert/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/taml006/quicklert/ansible.cfg) = [u'/home/taml006/quicklert/inventory']
DEFAULT_VAULT_PASSWORD_FILE(/home/taml006/quicklert/ansible.cfg) = /usr/share/ansible/ansible-vault
HOST_KEY_CHECKING(/home/taml006/quicklert/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/taml006/quicklert/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible Server: RHEL 7
##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

Navigate to ansible project directory
Send command: ansible-playbook phone_discovery.yml

```yaml
---
- hosts: INN-MAIN-SW1
  tasks:
  - name: gather phones from switches
    ios_command:
      commands: show cdp neighbor | inc SEP
    register: phones

  - name: save output to file
    copy:
      content: "{{ phones.stdout[0] }}"
      dest: "./files/{{ inventory_hostname }}"
    tags: save

  - name: assemble files to create master list
    assemble:
      src: ./files
      dest: ./output/phones.log
```

##### EXPECTED RESULTS

Playbook should do the following:
##### **Task 1**
gather output of `show cdp neighbor | inc SEP` and register to `phones`
##### **Task 2**
store output from each host to file named the hostname of the host
##### **Task 3**
Assemble all output files into one master file

For brevity, only 1 host is called in this playbook.

##### ACTUAL RESULTS

Task 1 runs successfully
Playbook fails on Task 2 (copy module) with error below.

Note. I've substituted `cleartextpass` in place of my actual password displayed in cleartext.

```paste below
Trying secret FileVaultSecret(filename='/usr/share/ansible/ansible-vault') for vault_id=default
Trying secret FileVaultSecret(filename='/usr/share/ansible/ansible-vault') for vault_id=default
Trying secret FileVaultSecret(filename='/usr/share/ansible/ansible-vault') for vault_id=default
Trying secret FileVaultSecret(filename='/usr/share/ansible/ansible-vault') for vault_id=default
<10.221.170.6> attempting to start connection
<10.221.170.6> using connection plugin network_cli
fatal: [INN-MAIN-SW1]: FAILED! => {
    "msg": "Traceback (most recent call last):\n  File \"/usr/bin/ansible-connection\", line 328, in <module>\n    main()\n  File \"/usr/bin/ansible-connection\", line 294, in main\n    conn.set_options(var_options=variables)\n  File \"/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py\", line 167, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/ansible/module_utils/connection.py\", line 144, in _exec_jsonrpc\n    data = json.dumps(req)\n  File \"/usr/lib64/python2.7/json/__init__.py\", line 243, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib64/python2.7/json/encoder.py\", line 207, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib64/python2.7/json/encoder.py\", line 270, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib64/python2.7/json/encoder.py\", line 184, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: u'cleartextpass' is not JSON serializable\n"
}
```
