### ISSUE TITLE
Inventory plugin aws_ec2 missing several variables contrib script had

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#52358]
##### SUMMARY
In general, as transition from the script (in the contrib) folder to the plugin was made, hostvars were renamed. This is fine for the majority of variables, because they can be aliased to the old names.

A handful of variables still remain that cannot be obviously aliased to an existing variables.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/inventory/aws_ec2.py

##### ANSIBLE VERSION
current devel
```paste below
ansible --version
ansible 2.8.0.dev0
  config file = None
  configured module search path = [u'/Users/alancoding/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alancoding/Documents/repos/ansible/lib/ansible
  executable location = /Users/alancoding/.virtualenvs/ansible/bin/ansible
  python version = 2.7.11 (default, Oct 17 2016, 14:59:40) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
default config, inventory file specifics are below

##### OS / ENVIRONMENT
Local machine, Mac OS, and AWS ec2 account.

##### DEPENDENCY PROBLEMS
no dependency problems

##### STEPS TO REPRODUCE
Inspect inventory content from an inventory file that uses the aws_ec2 plugin:

```yaml
ansible-inventory -i private/ec2/aws_ec2.yaml --list --export
```

look at hostvars, compare to the script output

```
AWS_ACCESS_KEY_ID=<removed> AWS_SECRET_ACCESS_KEY=<removed> ansible-inventory -i contrib/inventory/ec2.py --list --export
```

We can re-create most of the old variables via conversion like this:

```
plugin: aws_ec2

compose:
  ec2_id: instance_id
  # vars that change
  ec2_block_devices: dict(block_device_mappings | map(attribute='device_name') | list | zip(block_device_mappings | map(attribute='ebs.volume_id') | list))
  ec2_dns_name: public_dns_name
  ec2_group_name: placement.group_name
  ec2_instance_profile: iam_instance_profile | default("")
  ec2_ip_address: public_ip_address
  ec2_kernel: kernel_id | default("")
  ec2_monitored:  monitoring.state in ['enabled', 'pending']
  ec2_monitoring_state: monitoring.state
  ec2_placement: placement.availability_zone
  ec2_ramdisk: ramdisk_id | default("")
  ec2_reason: state_transition_reason
  ec2_security_group_ids: security_groups | map(attribute='group_id') | list |  join(',')
  ec2_security_group_names: security_groups | map(attribute='group_name') | list |  join(',')
  ec2_tag_Name: tags.Name
  ec2_state: state.name
  ec2_state_code: state.code | int
  ec2_state_reason: state_reason.message if state_reason is defined else ""
  ec2_sourceDestCheck: source_dest_check  # butchered snake_case case not a typo.
  ec2_account_id: 'network_interfaces | json_query("[0].owner_id")'

  # vars that just need ec2_ prefix
  ec2_ami_launch_index: ami_launch_index
  ec2_architecture: architecture
  ec2_client_token: client_token
  ec2_ebs_optimized: ebs_optimized
  ec2_hypervisor: hypervisor
  ec2_image_id: image_id
  ec2_instance_type: instance_type
  ec2_key_name: key_name
  ec2_launch_time: launch_time
  ec2_platform: platform | default("")
  ec2_private_dns_name: private_dns_name
  ec2_private_ip_address: private_ip_address
  ec2_public_dns_name: public_dns_name
  ec2_region: placement.region
  ec2_root_device_name: root_device_name
  ec2_root_device_type: root_device_type
  ec2_spot_instance_request_id: spot_instance_request_id
  ec2_subnet_id: subnet_id
  ec2_virtualization_type: virtualization_type
  ec2_vpc_id: vpc_id
hostnames:
  - network-interface.addresses.association.public-ip
  - dns-name
  - private-dns-name
```

##### EXPECTED RESULTS

This is still missing these which were in the old script.

Old script:

https://github.com/ansible/ansible/blob/6ac22416af987b4cd3e4cadf0f1d01352daf203c/contrib/inventory/ec2.py

List of variables with no conversion known yet:

  - ec2__in_monitoring_element
  - ec2_eventsSet
  - ec2_item
  - ~ec2_monitoring~
  - ec2_persistent
  - ec2_previous_state
  - ec2_previous_state_code
  - ec2_requester_id
  - ec2_spot_instance_request_id

EDIT: those in strike-out formatting _do_ have a variable that looks corresponding, I just need to confirm those, and they are not in scope of this issue.

##### ACTUAL RESULTS
Nothing that seems to reflect the meaning of those variables seem to be present.
