### ISSUE TITLE
Add swap module

### ISSUE THREAD

**Issue by dlee** [ansible/ansible#5241]
There should be an idempotent way to ensure a swapfile is created and enabled.

**Comment by srgvg** [comment]
Could be an extension to the mount module

**Comment by mpdehaan** [comment]
yes, it could.

We're welcome to take submissions but I'm not going to keep this tracker ticket open to keep the queue a little bit less cluttered.

Someone can implement if they like.

Thanks!

**Comment by motdotla** [comment]
Anyone aware of someone creating this? I'm also in need for it and starting to figure out my own tasks to handle it for now.

**Comment by motdotla** [comment]
for anyone else coming across this thread, I ended up with this:

``` yaml
...
- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count=512
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present

- name: Turn swap on
  command: swapon -a

- name: Set swapiness
  shell: echo 0 | sudo tee /proc/sys/vm/swappiness
...
```

**Comment by jwilberding** [comment]
@scottmotte Just used this myself, very helpful, thanks!!

**Comment by samos123** [comment]
@scottmotte Thanks for the swap role, I just made a role of this with a variable called swap_mb

**Comment by motdotla** [comment]
@samos123 woot. Thanks.

**Comment by eaigner** [comment]
@scottmotte Is this snippet idempotent?

**Comment by jwilberding** [comment]
@eaignerThe first two commands have the the when clause, and the 3rd uses a special command to only add the line when it doesn't exist. The last two commands will always run, but should harmless, so fairly indempotent.

**Comment by eaigner** [comment]
Oh... I didn't realize `ansible_swaptotal_mb` is a global ansible var

**Comment by manuelmeurer** [comment]
Swappiness should be permanently set using the [sysctl module](http://docs.ansible.com/sysctl_module.html) IMO:

```
- name: set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
```

Also, [setting it to 0 seems to disable swap](https://www.percona.com/blog/2014/04/28/oom-relation-vm-swappiness0-new-kernel/) so I'd set it to 1 to have minimum swappiness.

**Comment by JensDebergh** [comment]
I reused some of the snippets and adjusted them.
Ansible first pass through the commands work perfectly. 
The second run fails because the swapfile already enabled is being used. Any idea how I can counter this in ansible?

**Comment by manuelmeurer** [comment]
@JensDebergh Here's my swap role which checks whether the swap file already exists: https://gist.github.com/manuelmeurer/a2c0a8c24a0bb5092250

**Comment by JensDebergh** [comment]
@manuelmeurer  Awesome thanks ! :+1:

**Comment by WinstonSureChill** [comment]
+1

**Comment by ozbillwang** [comment]
There are two ways to create swap, on `disk device` and `file`, seems most documents and discussions are only talking about to create a swap file by ansible only. 

In some aws ec2 instances, we can use ephemeral storage as swap space. But this ansible playbook has to be added to cronjob, otherwise, if the instance is stop/start, the swap setting will disappear.

Here are the codes I did with logic volume created from disk device

```
- name: creating new LVM volume group 
  lvg: vg=swap pvs=/dev/xvdc state=present

# Normally assigned swap size is two times of memory
- name: creating new LVM logical volume 
  lvol: vg=swap lv=lvswap size='{{ facter_memorysize_mb|int * 2 }}'

- name: Format swap device
  command: mkswap /dev/swap/lvswap
  when: ansible_swaptotal_mb < 1

- name: activate swap device
  command: swapon /dev/swap/lvswap
  when: ansible_swaptotal_mb < 1
```

**Comment by ozbillwang** [comment]
@motdotla 

Your way works, which @manuelmeurer 's way is not idempotent with my way to set swap on logic volume

**Comment by manuelmeurer** [comment]
@SydOps I'm pretty sure my script is idempotent. Can you explain?

**Comment by ozbillwang** [comment]
@manuelmeurer 

Sorry for the misunderstand, I didn't test your way `when: not swap_file_check.stat.exists` with swapfile, but have issue with logic volume in my way. 

```
- name: check if swap file exists
  stat:
    path: "/dev/{{ vgname }}/{{ lvname }}"
  register: swap_file_check

# Here I can see the output, it is dict with stat.exist, value is true if it is set.
- command: echo {{ swap_file_check }}

- name: Format swap device
  command: mkswap /dev/swap/lvswap
  #when: ansible_swaptotal_mb < 1    
  when: not swap_file_check.stat.exists
```

The first when condition works fine, not the second.
