### ISSUE TITLE
Unable to update file with azure_rm_storageblob

### ISSUE THREAD

**Issue by LvffY** [ansible/ansible#52411]
##### SUMMARY
Impossible to upload a file in an azure blob storage with the module azure_rm_storageblob despite what is said in [issue #44815](https://github.com/ansible/ansible/issues/44815) and my ansible version >= 2.7.5.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_storageblob

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 26 2018, 20:53:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_CONTROL_PATH(/root/ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/root/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/root/ansible.cfg) = ~/.ansible/ansible_fact_cache
CACHE_PLUGIN_TIMEOUT(/root/ansible.cfg) = 86400
DEFAULT_FORKS(/root/ansible.cfg) = 10
DEFAULT_GATHERING(/root/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/root/ansible.cfg) = merge
DEFAULT_HOST_LIST(/root/ansible.cfg) = [u'/root/inventories/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/root/ansible.cfg) = /root/.ansible/.vault_pass
DISPLAY_SKIPPED_HOSTS(/root/ansible.cfg) = False
HOST_KEY_CHECKING(/root/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

##### STEPS TO REPRODUCE
Structure directory from `$HOME` : 
```
├── roles
│   ├── azr_deploy_semipersist
│   │   ├── defaults
│   │   │   └── main.yml
│   │   ├── files
│   │   │   ├── InitScript.sh
│   │   ├── tasks
│   │   │   └── main.yml
│   │   └── tests
│   │       ├── clean.yml
│   │       ├── group_vars
│   │       │   ├── azure
│   │       │   │   └── main.yml
│   │       │   └── vm_ssg
│   │       │       └── main.yml
│   │       ├── hosts
│   │       ├── host_vars
│   │       │   ├── testazure
│   │       │   │   ├── main.yml
│   │       │   │   └── vault.yml
│   │       │   └── vmtest
│   │       │       ├── main.yml
│   │       │       └── vault.yml
│   │       └── test.yml
```
defaults/main.yml : 
```yaml
---
resource_group: SEMIPERSISTENT
storage_account_name: "{{ resource_group | lower }}storage"
```

files/initScript.sh : 
```
### logs
mkdir -rf /tmp/initscript

echo "Installation du xsltproc" >> /tmp/initscript/logs
sudo apt-get install -y xsltproc
```
tasks/main.yml : 
```yaml
- name: "Ensure resource group {{ resource_group }} exists"
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    tenant: "{{ vault_tenant_id }}" ## portal : dashboard > AD > properties > DirectoryID
    secret: "{{ vault_secret }}"
    client_id: "{{ vault_client_id }}" ## portal : automationCdC > variables > servicePrincipalApplicationId
    subscription_id: "{{ vault_subscription_id }}"
    tags:
      description: "Metastores and semi persistent storages"
      delete: warn
  register: test_output
  delegate_to: localhost

- name: "Ensure containers are created in {{ storage_account_name }} storage account"
  azure_rm_storageblob:
    subscription_id: "{{ vault_subscription_id }}"
    resource_group_name: "{{ resource_group }}"
    tenant: "{{ vault_tenant_id }}" ## portal : dashboard > AD > properties > DirectoryID
    secret: "{{ vault_secret }}"
    client_id: "{{ vault_client_id }}" ## portal : automationCdC > variables > servicePrincipalApplicationId
    storage_account_name: "{{ storage_account_name }}"
    container: infra
    public_access: container
    blob: initScript.sh
    src: initScript.sh
  delegate_to: localhost
```

tests/groups_vars/azure/main.yml : 
```yaml
---
resources_prefix: "ansibletu"
azure_definition:
  rg_persist:
    name: LAB1_CDC_BIG_DATA_ANSIBLE_TU
    adl_name: "{{ resources_prefix }}adl"
  rg_semipersist:
    name: LAB1_CDC_BIG_DATA_ANSIBLE_TU
    storage_account:
      name: "{{ resources_prefix }}storages"
    sql_server:
      name: "{{ resources_prefix }}metastores"
    hive_size: S0
    oozie_size: S0
  rg_hdi:
    name: LAB1_CDC_BIG_DATA_ANSIBLE_TU
    cluster:
      name: "{{ resources_prefix }}"
      nodes:
        head:
          size: Standard_D12_V2
        worker:
          size: Standard_D4_V2
          number: 3
```

tests/group_vars/vm_ssg/main.yml : 

```yaml
---
ansible_ssh_private_key_file: your_private_key_file
```

tests/host_vars/testazure/main.yml : 

```yaml
---
ansible_ssh_private_key_file: your_private_key_file
ansible_ssh_pass: "{{ vault_ssh_pwd }}"
```
tests/host_vars/testazure/vault.yml : 

```yaml
---
vault_ssh_pwd: your_passwd_in_plain_text
```

tests/host_vars/vmtest/main.yml : 

```yaml
---
ansible_host: your_ip_or_dns

## Azure variables
subscription_id: "{{ vault_azure_subscription_id }}"
client_id: "{{ vault_azure_client_id }}"
secret: "{{ vault_azure_secret }}"
tenant_id: "{{ vault_azure_tenant }}"
objectId: "{{ vault_azure_object_id }}"
azurehost: testazure
```
tests/host_vars/vmtest/vault.yml : 

```yaml
---
vault_azure_subscription_id: your_sub_id
vault_azure_client_id: your_client_id
vault_azure_secret: your_azure_secret
vault_azure_tenant: your_tenant_id
vault_azure_object_id: your_object_id
```
tests/hosts :

```
[vm_ssg]
vmtest

[azure]
testazure
``` 

Finally, my playbook tests/test.yml :

```yaml
---
- name: Deploy Azure ressources
  hosts: vm_ssg

  tasks:

  - name: "Configure storage resource group"
    include_role:
        name: ~/roles/azr_deploy_semipersist
    vars:
      vault_subscription_id: "{{ subscription_id }}"
      vault_tenant_id: "{{ tenant_id }}"
      vault_secret: "{{ secret }}"
      vault_client_id: "{{ client_id }}"
      resource_group: "{{ hostvars[azurehost].azure_definition.rg_semipersist.name }}"
      storage_account_name: "{{ hostvars[azurehost].azure_definition.rg_semipersist.storage_account.name }}"
```
My command to execute my playbook : 
```
ansible-playbook -i roles/azr_deploy_semipersist/tests/hosts roles/azr_deploy_semipersist/tests/test.yml -vvvv
``` 

##### EXPECTED RESULTS
initScript.sh is  uploaded to my blob storage.

##### ACTUAL RESULTS

```
ansible-playbook 2.7.7
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Sep 26 2018, 20:53:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /root/ansible.cfg as config file
setting up inventory plugins
/root/roles/azr_deploy_semipersist/tests/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/root/roles/azr_deploy_semipersist/tests/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /root/roles/azr_deploy_semipersist/tests/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml **************************************************************************************************************************************************
1 plays in roles/azr_deploy_semipersist/tests/test.yml

PLAY [Deploy Azure ressources] **************************************************************************************************************************************
META: ran handlers
Trying secret FileVaultSecret(filename='/root/.ansible/.vault_pass') for vault_id=default
Trying secret FileVaultSecret(filename='/root/.ansible/.vault_pass') for vault_id=default
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394 `" && echo ansible-tmp-1550333207.18-164938253442394="` echo /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_resourcegroup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-3327QU3O3/tmpLZgpNK TO /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394/AnsiballZ_azure_rm_resourcegroup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394/ /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1550333207.18-164938253442394/ > /dev/null 2>&1 && sleep 0'

TASK [azr_deploy_semipersist : Ensure resource group LAB1_CDC_BIG_DATA_ANSIBLE_TU exists] ***************************************************************************
task path: /root/roles/azr_deploy_semipersist/tasks/main.yml:1
ok: [vmtest -> localhost] => {
    "changed": false,
    "contains_resources": true,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cloud_environment": "AzureCloud",
            "force": false,
            "location": "northeurope",
            "name": "LAB1_CDC_BIG_DATA_ANSIBLE_TU",
            "password": null,
            "profile": null,
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "subscription_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tags": {
                "delete": "warn",
                "description": "Metastores and semi persistent storages"
            },
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "state": {
        "id": "/subscriptions/********/resourceGroups/LAB1_CDC_BIG_DATA_ANSIBLE_TU",
        "location": "northeurope",
        "name": "LAB1_CDC_BIG_DATA_ANSIBLE_TU",
        "provisioning_state": "Succeeded",
        "tags": {
            "delete": "warn",
            "description": "Metastores and semi persistent storages"
        }
    }
}
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843 `" && echo ansible-tmp-1550333208.66-188490368973843="` echo /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_storageblob.py
<localhost> PUT /root/.ansible/tmp/ansible-local-3327QU3O3/tmpoxMPh3 TO /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843/AnsiballZ_azure_rm_storageblob.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843/ /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1550333208.66-188490368973843/ > /dev/null 2>&1 && sleep 0'

TASK [azr_deploy_semipersist : Ensure containers are created in ansibletustorages storage account] ******************************************************************
task path: /root/roles/azr_deploy_semipersist/tasks/main.yml:97
fatal: [vmtest -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "blob": "initScript.sh",
            "blob_type": "block",
            "cache_control": null,
            "cert_validation_mode": null,
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cloud_environment": "AzureCloud",
            "container": "infra",
            "content_disposition": null,
            "content_encoding": null,
            "content_language": null,
            "content_md5": null,
            "content_type": null,
            "dest": null,
            "force": false,
            "password": null,
            "profile": null,
            "public_access": "container",
            "resource_group": "LAB1_CDC_BIG_DATA_ANSIBLE_TU",
            "resource_group_name": "LAB1_CDC_BIG_DATA_ANSIBLE_TU",
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "src": "initScript.sh",
            "state": "present",
            "storage_account_name": "ansibletustorages",
            "subscription_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tags": null,
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "The source path must be a file."
}
        to retry, use: --limit @/root/roles/azr_deploy_semipersist/tests/test.retry

PLAY RECAP **********************************************************************************************************************************************************
vmtest                     : ok=1    changed=0    unreachable=0    failed=1

```
