### ISSUE TITLE
Transition to become plugin seems to fail privilege escalation for network modules

### ISSUE THREAD

**Issue by NilashishC** [ansible/ansible#52474]
##### SUMMARY
- Privilege escalation for networking platforms seem to fail with the following error in latest devel after #50991:
```
fatal: [ios-01]: FAILED! => {
    "msg": "Invalid become method specified, could not find matching plugin: 'enable'. Use `ansible-doc -t become -l` to list available plugins."
}
```
- This affects network_cli and httpapi connection privilege escalation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
become plugin

##### ANSIBLE VERSION

```
devel
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/vagrant/playbooks/ansible.cfg) = [u'/home/vagrant/playbooks/hosts']
HOST_KEY_CHECKING(/home/vagrant/playbooks/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/vagrant/playbooks/ansible.cfg) = 300
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/vagrant/playbooks/ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/home/vagrant/playbooks/ansible.cfg) = 300
RETRY_FILES_ENABLED(/home/vagrant/playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu Trusty64
Group Vars:
```yaml
ansible_connection: network_cli
ansible_network_os: <network_os>
ansible_ssh_user: <user_name>
ansible_ssh_pass: <password>
ansible_become: yes
ansible_become_method: enable
cli:
  authorize: yes
```
##### STEPS TO REPRODUCE
Run any task consisting of network modules that require privilege escalation. But for example:
```yaml
---
- name: Test ios facts for Config facts
  hosts: ios-01
  tasks:
    - name: ios facts 
      ios_facts:
        gather_subset:
          - interfaces
```

##### EXPECTED RESULTS
Should not hit privilege escalation failure.

##### ACTUAL RESULTS
```
fatal: [ios-01]: FAILED! => {
    "msg": "Invalid become method specified, could not find matching plugin: 'enable'. Use `ansible-doc -t become -l` to list available plugins."
}

```
