### ISSUE TITLE
cpanm: install multiple modules at once

### ISSUE THREAD

**Issue by inmediasit** [ansible/ansible#52477]
##### SUMMARY
Basically, one should be able to do the following:
```yaml
- name: Installing perl dependencies
  cpanm:
    name: "{{ item }}"
  use_sudo: yes
  with_items: 
    - Foo:Lib
    - John:Doe
```

Basically everything in ansible supports this syntax (except for this module, it seems).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cpanm

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/language/cpanm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/cpanm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @fcuny
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by papakai** [comment]
Would also be great supporting the below way to provide the explicit version:

```
- name: Install perl deps
  cpanm:
    notest: yes
    name: "{{ packages }}"
  vars:
    packages:
      - Perl::Critic@1.132
      - CPAN::Uploader@0.103013
      - Devel::Cover@1.30
```

**Comment by aviddiviner** [comment]
To anyone else coming to this issue after searching the web, here's how I did it.

Just make use of a YAML multi-line string (folded block using `>`), e.g.:
```yaml
- name: install perl modules
  cpanm:
    notest: true
    name: >
      Perl::Critic~1.132
      CPAN::Uploader~0.103013
      Devel::Cover~1.30
```
