### ISSUE TITLE
When mixing roles and tasks in a single "hosts group", the tasks don't execute

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#5250]
This playbook wil not execute the task "ensure apt cache is up to date (direct task)":

```
- name: Install common config on all nodes
  hosts: all
  user: root

  tasks:
  - name: ensure apt cache is up to date (direct task)
    action: apt update_cache=yes

  roles:
    - common
```

This could be an issue for organization with a policy to have more strict code reviews for "roles" than for singular tasks. My current workaround is to have two host group sections, first executing the task and then the role:

```
- name: Install common config on all nodes
  hosts: all
  user: root

  tasks:
  - name: ensure apt cache is up to date (direct task)
    action: apt update_cache=yes

  # roles:
  #   - common

- name: Install common config on all nodes(2)
  hosts: all
  user: root

  roles:
    - common
```
