### ISSUE TITLE
add the ablilty to template the `hosts` for a given play

### ISSUE THREAD

**Issue by joshuaconner** [ansible/ansible#5252]
It'd be super nice to be able to template the `hosts` portion of a play. Something like:

``` yaml
- name: Ensure instances are configured with docker and nginx
  hosts: "tag_Name_{{ ec2_tag_Name }}"
  user: ubuntu
  sudo: yes
  roles:
  - nginx
  - docker
```

Right now, this doesn't work, forcing me to use `when` statements everywhere, like this:

``` yaml
- name: Configure instance for mraid-js-server
  hosts: all
  user: ubuntu
  sudo: yes
  roles:
  - { role: nginx, when: ('tag_Name_' + ec2_tag_Name) in hostvars[inventory_hostname]['ec2_tags'] }
  - { role: docker, when: ('tag_Name_' + ec2_tag_Name) in hostvars[inventory_hostname]['ec2_tags'] }
```

Thoughts?
