### ISSUE TITLE
vmware_host_firewall_facts does not return networks, only individual IPs

### ISSUE THREAD

**Issue by alongchamps** [ansible/ansible#52526]
##### SUMMARY
In the return values for vmware_host_firewall_facts, the information that is returned only brings back single IP addresses and not networks - both of these are distinct, valid properties off the ESXi host firewall rule.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_host_firewall_facts

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory']
```

##### OS / ENVIRONMENT

Client: MacOS 10.14.3
VMware vCenter: 6.0, build 8803876
ESXi 6.0, build 5050593

##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

1. Navigate to the ESXi host's firewall configuration under host, manage, settings, security profile
2. Edit a rule on your test system, for example vMotion Inbound (port 8000) allowed all IP, set to false and IP networks set to 192.168.100.0/24 and 192.168.200.10
3. Run example playbook to pull back facts - note that it does not return 192.168.100.0/24 only 192.168.200.10 as an IP address in the firewall list

```yaml
---
- hosts: localhost
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - name: get host firewall facts
      vmware_host_firewall_facts:
        hostname: '{{ vcenter_ip }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        esxi_hostname: '{{ virtual_host_name }}'
        validate_certs: False
      delegate_to: localhost
      register: host_firewall_facts

    - name: with_dict
      debug:
        msg: "{{ item }}"
      loop: "{{ host_firewall_facts['hosts_firewall_facts'][{{ virtual_host_name  }}] }}"
      loop_control:
        label: "{{ item.key }}"
```
If the above doesn't work because of line 21, change {{ virtual_host_name }} to your test host's name.

##### EXPECTED RESULTS

```
ok: [localhost] => (item=vMotion) => {
    "msg": {
        "allowed_hosts": {
            "all_ip": false, 
            "ip_address": [
                "192.168.200.10"
            ], 
            "network": [
                [
                    "192.168.100.0/24"
                ]
            ]
        }, 
        "enabled": true, 
        "key": "vMotion", 
        "rule": [
            {
                "direction": "inbound", 
                "end_port": null, 
                "port": 8000, 
                "port_type": "dst", 
                "protocol": "tcp"
            }, 
            {
                "direction": "outbound", 
                "end_port": null, 
                "port": 8000, 
                "port_type": "dst", 
                "protocol": "tcp"
            }
        ], 
        "service": null
    }
}
```

##### ACTUAL RESULTS

```paste below
ok: [localhost] => (item=vMotion) => {
    "msg": {
        "allowed_hosts": {
            "all_ip": false, 
            "ip_address": [
                "192.168.200.10"
            ]
        }, 
        "enabled": true, 
        "key": "vMotion", 
        "rule": [
            {
                "direction": "inbound", 
                "end_port": null, 
                "port": 8000, 
                "port_type": "dst", 
                "protocol": "tcp"
            }, 
            {
                "direction": "outbound", 
                "end_port": null, 
                "port": 8000, 
                "port_type": "dst", 
                "protocol": "tcp"
            }
        ], 
        "service": null
    }
}
```
