### ISSUE TITLE
na_ontap_user module role_name not idempotent

### ISSUE THREAD

**Issue by jrdalrymple** [ansible/ansible#52569]
##### SUMMARY
When trying to use the na_ontap_user role to modify the role of an existing user, the role is not changed. The task completes successfully and indicates "ok" instead of "changed". The outcome can be validated on the vserver indicating the user/application still is assigned to the earlier role.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
na_ontap_user module

##### ANSIBLE VERSION

```
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

netapp-cluster::*> system node image show
                 Is      Is                                Install
Node     Image   Default Current Version                   Date
-------- ------- ------- ------- ------------------------- -------------------
netapp-node-1
         image1  false   false   9.3P4                     6/3/2018 07:42:56
         image2  true    true    9.3P8                     12/5/2018 04:56:52
netapp-node-2
         image1  false   false   9.3P4                     6/3/2018 08:45:58
         image2  true    true    9.3P8                     12/5/2018 04:58:16
4 entries were displayed.
##### DEPENDENCY PROBLEMS

```paste below

```

##### STEPS TO REPRODUCE

Create a new user using an existing role using the na_ontap_user module and that succeeds and assigns all resources properly. Change the "role_name" parameter to attempt to modify the login and rerun the playbook, the playbook succeeds but the role remains unchanged. It is possible to rerun the playbook with "state: absent" then once again with "state: present" and upon recreation the proper role is applied.

```
---
- hosts: netapp-cluster
  tasks:
    - name: Add Users to cluster
      na_ontap_user:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        application: "http"
        authentication_method: "domain"
        name: "DOMAIN\\username"
        role_name: "storage-associate"
        state: "present"
        vserver: netapp-cluster
      delegate_to: localhost
    - name: Add Users to cluster
      na_ontap_user:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        application: "http"
        authentication_method: "domain"
        name: "DOMAIN\\username"
        role_name: "storage-admin"
        state: "present"
        vserver: netapp-cluster
      delegate_to: localhost
```

##### EXPECTED RESULTS

I expect when I run the above playbook that the "DOMAIN\username" user would end up with the role storage-admin for the http application.

##### ACTUAL RESULTS

The "DOMAIN\username" user ends up with role storage-associate for the http application.

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/storage/netapp/na_ontap_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/storage/netapp/na_ontap_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @amit0701 @carchi8py @hulquest @lmprice @lonico @ndswartz @schmots1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by angystardust** [comment]
Hi @jrdalrymple recentrly the module `na_ontap_user_role` got a revamp with #49778. Can you please try to use the module module from master?
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/storage/netapp/na_ontap_user.py

**Comment by jrdalrymple** [comment]
The outcome is the same.

Simply changing the role_name has no effect.
Changing the state to absent removes the login.
Removing the state parameter (defaulting to present) restores the login with the expected role.

```
yum -y erase ansible
git clone https://github.com/ansible/ansible.git --recursive
cd ansible
git checkout 971cea8
source ./hacking/env-setup
```

Let me know if that wansn't the proposed process/solution.

For completeness sake, my actual task from the playbook:

```
    - name: Add user logins to cluster
      na_ontap_user:
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        application: "{{ item.1.name }}"
        authentication_method: "{{ item.1.authentication }}"
        name: "{{ item.0.name }}"
        role_name: "{{ item.1.role }}"
        state: "{{ item.1.state|default('present') }}"
        vserver: "{{ cluster-name }}"
      delegate_to: localhost
      loop: "{{ users|subelements('applications') }}"
```

and my "users" dictionary:

```
users:
  - name: "DOMAIN\\username"
    applications:
      - name: "http"
        role: "readonly"
        authentication: "domain"
      - name: "ssh"
        role: "ist_dp"
        authentication: "domain"
      - name: "ontapi"
        role: "ist_dp"
        authentication: "domain"
```
