### ISSUE TITLE
ec2_group module poorly handles new rule additions

### ISSUE THREAD

**Issue by AshtonDavis** [ansible/ansible#52609]
##### SUMMARY
The ec2_group module currently does a fine job of creating a security group, but a poor job of managing rules after the fact. Issues include requiring name AND description for updating, no support for using sg id instead (except when used with absent), and rules being purged _by default_.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_group

##### ADDITIONAL INFORMATION
Currently there are a few issues with day-2 operations using ec2_group.
Below is a code block that creates a security group. Totally fine and dandy.

```yaml
  ec2_group:
    name:             "Demo Security Group"
    description:      "Demo Security Group"
    vpc_id:           "{{ vpc_id }}"
    region:           "{{ aws_region }}"
    rules:
      - proto:        "tcp"
        ports:
           - 22
        cidr_ip:      "0.0.0.0/0"
```

Below is an example of what is required to ADD a rule.

```yaml
  ec2_group:
    name:             "Demo Security Group"
    description:      "Demo Security Group"
    vpc_id:           "{{ my_vpc_id }}" 
    region:           "{{ my_region }}"
    purge_rules:      false
    purge_rules_egress: false
    rules:
      - proto:        "tcp"
        ports:
          - 80
        cidr_ip:      "0.0.0.0/0"
```

From the top
1) It's only possible to update by name. Updating rules should support id as well, like everything else in our ec2 module infrastructure.
2) Description *is required* in order to update, which is NOT something you get from instance metadata. This is a break from touchless automation.
3) `purge_rules` and `purge_rules` are set to yes by default, which seems to be a departure from normal procedure - anything destructive is typically false by default. It should be in this case as well.

I would recommend setting purge_rules and purge_rules_egress to FALSE by default, supporting security group ID, and not requiring Description.
