### ISSUE TITLE
java_cert bug

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#52627]
##### SUMMARY

Task require variable but they are marked as not required.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 java_cert

##### ANSIBLE VERSION

```paste below
2.7.1
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Remove certificate with given alias from a keystore
  java_cert:
    cert_alias: somealias
    keystore_path: /usr/lib/jvm/jre7/lib/security/cacerts
    keystore_pass: changeit
    executable: /usr/lib/jvm/jre7/bin/keytool
    state: absent
```

##### EXPECTED RESULTS

alias removed from keystore

##### ACTUAL RESULTS

fatal: [host]: FAILED! => {"changed": false, "msg": "one of the following is required: cert_path, cert_url, pkcs12_path"}

```paste below

```
