### ISSUE TITLE
Use __inputs fields in grafana_dashboard_module

### ISSUE THREAD

**Issue by Duologic** [ansible/ansible#52635]
##### SUMMARY
Grafana dashboard can be exported or imported with __inputs fields for the datasources and other variables. `grafana_dashboard_module` should benefit from this feature.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[lib/ansible/modules/monitoring/grafana_dashboard.py
](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/grafana_dashboard.py)

##### ADDITIONAL INFORMATION
Since Grafana 3.0, exported dashboards can include a set of [input variables](http://docs.grafana.org/reference/export_import/#import-sharing-with-grafana-2-x-or-3-0) that allow easier templating and sharing of dashboards between Grafana users. This is mainly used to allow a Grafana user to set the correct datasource on import. The feature is very common in [Grafana community dashboards](https://grafana.com/dashboards).

I've explored this idea in the cloudalchemy.grafana role (https://github.com/cloudalchemy/ansible-grafana/pull/135) where I combined importing of dashboards from Grafana and setting __inputs variables through jinja templating, however this is a bit hackish.

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Import Grafana dashboard foo
      grafana_dashboard:
        grafana_url: http://grafana.company.com
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        path: /path/to/dashboards/foo.json
        variables:
          DS_GRAPHITE: 'Graphite Production'
          VAR_PREFIX: 'prod.grafana'
```
