### ISSUE TITLE
Jinja2 doesn't skip tasks if use when

### ISSUE THREAD

**Issue by Asgoret** [ansible/ansible#52632]
##### SUMMARY
I want skip task, but jinja2 module can't skip.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = None
  configured module search path = [u'/Users/a.ermakov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
macOS
```
python --version
Python 2.7.10
```

##### STEPS TO REPRODUCE
Run this task.

Bug task:
```
  - name: Prepare parametres for deployment config
    lineinfile:
      path: /tmp/parametres.txt
      state: present
      line: |-
        - name: {{ item.key }}
          value: {{ item.value }}
    loop: "{{ contents | dict2items }}"
    when: contents is defined
```

##### EXPECTED RESULTS
Task skipped because contents is undefined.

##### ACTUAL RESULTS
Task failed

```
fatal: [localhost]: FAILED! => {
    "msg": "dict2items requires a dictionary, got <class 'jinja2.runtime.StrictUndefined'> instead."
}
```

**Comment by mkrizek** [comment]
This should do what you want:
```
  - name: Prepare parametres for deployment config
    lineinfile:
      path: /tmp/parametres.txt
      state: present
      line: |-
        - name: {{ item.key }}
          value: {{ item.value }}
    loop: "{{ contents | default({}) | dict2items }}"
```

needs_info
