### ISSUE TITLE
Import dashboards from Grafana community dashboards

### ISSUE THREAD

**Issue by Duologic** [ansible/ansible#52636]
##### SUMMARY
Import [Grafana community dashboards](https://grafana.com/dashboards) directly with `grafana_dashboard_module`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[lib/ansible/modules/monitoring/grafana_dashboard.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/grafana_dashboard.py)

##### ADDITIONAL INFORMATION
[Grafana community dashboards](https://grafana.com/dashboards) have a lot of preconfigured dashboards available. These can easily be imported through the webinterface by simply providing an ID. It would be a nice feature to implement this feature in `grafana_dashboard_module`

The idea comes from the [cloudalchemy.grafana](https://github.com/cloudalchemy/ansible-grafana) role. This way we don't have to download these dashboards manually. 

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Import Grafana Internal Stats dashboard
      grafana_dashboard:
        grafana_url: http://grafana.company.com
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        grafana_com:
          id: 55
          revision: 3
```

Related:
- https://github.com/ansible/ansible/issues/52635
- https://github.com/cloudalchemy/ansible-grafana/pull/135
