### ISSUE TITLE
Unable to authenticate using nxapi 

### ISSUE THREAD

**Issue by laurent-perrin** [ansible/ansible#52647]
##### SUMMARY
I'm trying to use network automation as described here: https://docs.ansible.com/ansible/latest/network/user_guide/platform_nxos.html#using-nx-api-in-ansible-2-6
But I got an "Unauthorized" error message. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos modules using nxapi connection

##### ANSIBLE VERSION

```
ansible 2.7.7
  config file = /home/fgzx6022/Work/ansible-nexus/ansible.cfg
  configured module search path = [u'/home/fgzx6022/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fgzx6022/Work/python-env/ansible2.7/local/lib/python2.7/site-packages/ansible
  executable location = /home/fgzx6022/Work/python-env/ansible2.7/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/fgzx6022/Work/ansible-nexus/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/fgzx6022/Work/ansible-nexus/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=60
DEFAULT_CALLBACK_WHITELIST(/home/fgzx6022/Work/ansible-nexus/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/home/fgzx6022/Work/ansible-nexus/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/fgzx6022/Work/ansible-nexus/ansible.cfg) = [u'/home/fgzx6022/Work/ansible-nexus/nexus-inventory']
DEFAULT_STRATEGY(/home/fgzx6022/Work/ansible-nexus/ansible.cfg) = free
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

network configuration variables:
```yaml
ansible_connection: httpapi
ansible_network_os: nxos
ansible_user: USERNAME
ansible_ssh_pass: PASSWORD
```

Playbook
```yaml
- name: add ssh key to ansible user
  nxos_user:
    # provider:
    #   username: "{{ ansible_user }}"
    #   password: "{{ ansible_password }}"
    name: "{{ ansible_user }}"
    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  tags: system,ssh,test
```

##### EXPECTED RESULTS

Configuration should be applied.

##### ACTUAL RESULTS

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_nxos_user_payload_JGoxVT/ansible_nxos_user_payload.zip/ansible/module_utils/network/nxos/nxos.py", line 157, in run_commands
    out = connection.run_commands(commands, check_rc)
  File "/tmp/ansible_nxos_user_payload_JGoxVT/ansible_nxos_user_payload.zip/ansible/module_utils/connection.py", line 173, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

fatal: [cloud-sw-z01r-prd.cloud.620nm.net]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "aggregate": null, 
            "auth_pass": null, 
            "authorize": null, 
            "configured_password": null, 
            "host": null, 
            "name": "ansible", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "purge": false, 
            "roles": null, 
            "ssh_keyfile": null, 
            "sshkey": "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAiXoKxpu1fxIZcKGm2b7xV7EZr6v8GH2NXCt5FuD5pIQ9xhr0UqLK26SPL0/jP5cFziXfpSiADNrk+LQplDxlvB51gkLc0xj+DrTjvg72lA3SahlRXsOyvnNzoUIeVMCidycB8JA1/LBVTgPtXr7Cv9RXNIXGQ7ATmyy/Vyp0V5T8G6Cc7Gjzna5h4PWLz0H3xcKrF8USNCET7hlZATegtaLOIevzweyu/6bsMYVSdgBkLXwOiCJkMFGILY/5/0W0YCu9BVKUuG4XQaddiQjdQOdnDUHqWXTBWTiPVZPTtRIMjQzIJMEVW6oXyxiy2AF8tqx7XTb62/NTFXPy+eclbw== laurent2.perrin@orange.com", 
            "state": "present", 
            "timeout": null, 
            "transport": null, 
            "update_password": "always", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }, 
    "msg": "Could not connect to http://cloud-sw-z01r-prd.cloud.620nm.net:80/ins: Unauthorized"
}
```
