### ISSUE TITLE
known_host module fails tryin to install a @cert-authority key using an IP as name

### ISSUE THREAD

**Issue by piccardi** [ansible/ansible#52651]
##### SUMMARY

Trying to insert a @cert-authority line fails if I use an IP

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

known_hosts

##### ANSIBLE VERSION

```paste below
ansible 2.5.1
  config file = /home/xxx/ansible/ansible.cfg
  configured module search path = [u'/home/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/xxx/ansible/ansible.cfg) = True
DEFAULT_FILTER_PLUGIN_PATH(/home/xxx/ansible/ansible.cfg) = [u'/home/xxx/ansible/filter_plugins']
DEFAULT_HOST_LIST(/home/xxx/ansible/ansible.cfg) = [u'/home/xxx/ansible/hosts']
DEFAULT_ROLES_PATH(/home/xxx/ansible/ansible.cfg) = [u'/home/xxx/ansible/roles']

```

##### OS / ENVIRONMENT

Ubuntu 18.04.2 LTS, Mate desktop

##### STEPS TO REPRODUCE

Just use a task like the one on the example below, and it fails.

```yaml
vars:
  ssh_ca_pub_key: "{{lookup('file', 'my_ssh_ca_file.pub')}}"
tasks:

  - name: Add SSH CA for 192.168.42.18 to known_hosts
    known_hosts:
      name: '@cert-authority 192.168.42.18'
      key: "@cert-authority  192.168.42.18 {{ssh_ca_pub_key}}"

```
Gives:

```
TASK [Add SSH CA for 192.168.42.18 to known_hosts] *****************************
fatal: [192.168.77.7]: FAILED! => {"changed": false, "cmd": "/usr/bin/ssh-keygen -F '' -f /tmp/tmpZn4ZLH", "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```	

Note, if I run instead:

```yaml
vars:
  ssh_ca_pub_key: "{{lookup('file', 'my_ssh_ca_file.pub')}}"
tasks:

  - name: Add SSH CA for *.truelite.it to known_hosts
    known_hosts:
      name: '@cert-authority *.truelite.it'
      key: "@cert-authority  *.truelite.it {{ssh_ca_pub_key}}"

```

it works fine:

```
TASK [Add SSH CA for *.truelite.it to known_hosts] *****************************
changed: [192.168.77.7]
```

and in the .ssh/known host I got the correct line

```
@cert-authority  *.truelite.it ssh-rsa AAAAB3NzaC...
```

##### EXPECTED RESULTS

It should just create the correct line, now I'm forced to get it the line using:

```yaml
 - name: Add SSH CA for 192.168.42.18 to known_hosts
   lineinfile:
     path: /root/.ssh/known_hosts
     line: "@cert-authority 192.168.42.18 {{ssh_ca_pub_key}}"
```

##### ACTUAL RESULTS

It fails, below the error with -vvvv.

```paste below
...
fatal: [192.168.77.7]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/ssh-keygen -F '' -f /tmp/tmpcMVWP9", 
    "invocation": {
        "module_args": {
            "hash_host": false, 
            "key": "@cert-authority  192.168.42.18 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhS69JFW+P+IV6WaYiBpfSLqUNx/n9HdS4ZAlhPIt4bebKO/lCzBE7UKy6ZHMFhgYxLSf4eU8XP8zIQUyqabvh9w9+qWkd6rlbA88jHDmkOrguzQG2zXLooIiDfA0htaFv7PLpmQstniZAN9rlAy0isLGdQQJUX1SQFNpQmRfSgcZrgPJQPGmMumz+N24vWB3Uh2sE59aAxSAXfQ2a25og9gfxcJ8jOJGCS5RtffhI/mpc29AxTSmIpaHyEiA9Kyi83XlgBN6Wz/pxZguG3z8f0yBofSn9S2b8gBo7Eaugpf/HWJGStchvzRvEa7i6YKBXra9H8/yXR4Ay6AjZcRwF CA for matheria.it", 
            "name": "@cert-authority 192.168.42.18", 
            "path": "/root/.ssh/known_hosts", 
            "state": "present"
        }
    }, 
    "msg": "", 
    "rc": 1, 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}

```
