### ISSUE TITLE
Make openssh_keypair return public key

### ISSUE THREAD

**Issue by wedi** [ansible/ansible#52663]
##### SUMMARY
I'd like to suggets adding the public key to `openssh_keypair` return values.
This is helpful when generating a SSH key pair and distribute the resulting public key. At the moment one needs to run a command task that outputs keyfile.pub and use its stdout to get hold of the public key. This could be much more elegant.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssh_keypair

##### ADDITIONAL INFORMATION
Quick and dirty example:

```yaml
- name: Generate deploy key
  openssh_keypair:
    type: ed25519
    path: "~/.ssh/{{ ansible_hostname | replace('.', '-') }}_deploykey"
    comment: "{{ ansible_hostname | replace('.', '-') }}_deploykey"
    mode: 0600
  register: deploy_key

- name: Add new deploy key to project
  gitlab_deploy_key:
    state: present
    key: deploy_key.public_key
    project: "mygroup/projectname"
    title: "{{ ansible_hostname }} (generated by Ansible)"
    api_url: https://gitlab.example.com/api
    ...
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/crypto/openssh_keypair.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssh_keypair.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @MarkusTeufelberger @Shaps @Spredzy @Xyon @felixfontein @lolcube @puiterwijk @resmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
> This is helpful when generating a SSH key pair and distribute the resulting public key. At the moment one needs to run a command task that outputs keyfile.pub and use its stdout to get hold of the public key. This could be much more elegant.

Out of curiosity: why do you use [command](https://docs.ansible.com/ansible/latest/modules/command_module.html#command-module) instead of using [fetch](https://docs.ansible.com/ansible/latest/modules/fetch_module.html#fetch-module) or [slurp](https://docs.ansible.com/ansible/latest/modules/slurp_module.html#slurp-module)? (If you're working with `localhost`, you can also use the [file lookup](https://docs.ansible.com/ansible/latest/plugins/lookup/file.html).)

**Comment by wedi** [comment]
I am generating the private keys on the host where they will be used so, unfortunately, lookup is no option. Of course I could use slurp instead of a command I decided to go the command way to avoid the base64 decoding on every use. My reasoning stays the same whichever way you go: it's one more task and I guess reusing the public key after generating it is a very common use case. A use case that is considerably more elegant with openssh_keypair returning the public key by default.

**Comment by angystardust** [comment]
Recently I had the same need as you, @wedi 
Here is another real-life user-case: ssh pubkey exchange between a group of hosts and a NetApp storage in order to delegate execution of a subset of commands on the target storage:

```
---
- hosts: "{{ target }}"

  vars:

    na_connection: &na_connection
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

    methuser:

  tasks:

    - name: Generate ssh keypair
      openssh_keypair:
        path: "~/.ssh/netapp-{{ myuser }}"
        state: present
      register: sshkey
      become: yes
      become_user: "{{ myuser }}"

    - name: "Get the ssh publickey from { myuser }}@{{ inventory_hostname }}"
      slurp:
        src: "~/.ssh/netapp-{{ myuser }}.pub"
      register: sshpubkey
      become: yes
      become_user: "{{ myuser }}"

    - name: Decode the ssh publickey
      set_fact:
        sshpubkeydec: "{{ sshpubkey['content'] | b64decode | trim }}"

    - name: Assign a publickey to the user
      na_ontap_command:
        <<: *na_connection
        command: ['security', 'login', 'publickey', 'create', '-vserver', '{{ svm_name }}', '-username', '{{ myuser }}', '-publickey', "{{ sshpubkeydec }}", '-comment', "Publickey for {{ inventory_hostname }}" ]
      register: putpubkey
      changed_when: '"<cli-result-value>1</cli-result-value>" in putpubkey.msg'
      delegate_to: localhost

```
As you can see, I needed to add 2 more tasks to get the generated pub key and decode it before injecting it on my storage. I would be great if `openssh_keypair` module would return the publickey when invoked...
