### ISSUE TITLE
crash when passing variable in playbook to roll with same name as variable in role

### ISSUE THREAD

**Issue by queglay** [ansible/ansible#52724]
##### SUMMARY

If I pass a variable defined in a playbook that has the same name as a variable within a role, ansible crashes.  this functionality has been described in various documentation and tutorials I have been learning from.  it seems like necesary functionality for a modular way of working, otherwise I would have to create duplicate variable names that have the same value to workaround the bug.

I have seen another issue that was closed, but it seems like this is necesary for a modular way of working that is logical.  if it is actually desirable functionality, the error should probably be caught 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
```

##### CONFIGURATION

```paste below
vagrant@openfirehawkserver:/vagrant/ansible$ ansible-config dump --only-changed
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to inventory sources , use ANSIBLE_INVENTORY instead. This feature will be removed in 
version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = [u'/vagrant/ansible/hosts']

```

##### OS / ENVIRONMENT

ubuntu 16.04 running in virtualbox, launched with vagrant - ubuntu/xenial64

##### STEPS TO REPRODUCE

define a role with a variable used in it.
pass a variable of that same name into the role with a playbook.

example playbook-

```yaml
    vars:
        deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"\
    roles:
        - role: deadlinedb
          deadline_linux_installers_tar: "{{ deadline_linux_installers_tar }}"
```
my role tasks file look like this
```yaml
    - name: Ensures tar exists
      stat:
        path: "{{ deadline_linux_installers_tar }}"
      register: deadline_linux_installers_tar_stat
      become: yes
```

##### EXPECTED RESULTS

I would expect a role to inherit the variable without issue.

##### ACTUAL RESULTS

This will produce this error in a loop.  it will keep going through the shell for a page or so in a loop.

```paste below
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ deadline_linux_installers_tar }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ deadline_linux_installers_tar }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ deadline_linux_installers_tar }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ deadline_linux_installers_tar }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ deadline_linux_installers_tar }}
```

**Comment by queglay** [comment]
further things uncovered.  this is a hacky attempt that doesn't extend far.  I also don't think this hack would be a good way to work.
```yaml
  vars:
    main:
      deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"

  roles:
    - role: deadlinedb
      deadline_linux_installers_tar: "{{ main.deadline_linux_installers_tar }}"
```
so that does work.  but not this-

```
  vars:
    main:
      deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"
      no_extension: "{{ main.deadline_linux_installers_tar | splitext | first }}"
    #     basename: "{{ no_extension.split('/')[-1] }}"

  roles:
    - role: deadlinedb
      deadline_linux_installers_tar: "{{ main.deadline_linux_installers_tar }}"
```
it returns this error
```
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ main.deadline_linux_installers_tar }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'no_extension': u'{{ main.deadline_linux_installers_tar | splitext | first }}', u'deadline_linux_installers_tar
```

yet if I just do this-
```
  vars:
    main:
      deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"
      no_extension: "{{ main.deadline_linux_installers_tar | splitext | first }}"
```

its fine.

so theres more than just one strange thing happenning here it seems.

**Comment by sivel** [comment]
There is no need to do this:

```
    vars:
        deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"
    roles:
        - role: deadlinedb
          deadline_linux_installers_tar: "{{ deadline_linux_installers_tar }}"
```

Just doing this is sufficient, as the role will still have access to the var.  There is no need to try and define the var, and then explicitly pass it in.

```
    vars:
        deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"
    roles:
        - role: deadlinedb
```

Or

```
    roles:
        - role: deadlinedb
          deadline_linux_installers_tar: "{{ deadline_linux_installers_tar }}"
          vars:
            deadline_linux_installers_tar: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
