### ISSUE TITLE
panos_admpwd - allow ssh-agent auth

### ISSUE THREAD

**Issue by dthvt** [ansible/ansible#52727]
##### SUMMARY

Update panos_admpwd to allow use of ssh-agent authentication instead of manually specifying a key_filename parameter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

panos_admpwd

##### ADDITIONAL INFORMATION

This module requires the path to a ssh private key in order to authenticate to the Palo Alto.  This is painful when developing shared playbooks, and unnecessary since paramiko supports ssh-agent.

```yaml
- name: set admin password
  panos_admpwd:
    ip_address: "{{ instance.instances[0].public_ip_address }}"
    username: "admin"
    newpassword: "{{ admin_password }}"
  register: password_check
```
Same syntax as current command, but able to omit key_filename to default to ssh-agent auth.

See attached patch for suggested code change.  (Sorry, not a python dev, so may need cleanup.)

[patch.txt](https://github.com/ansible/ansible/files/2889783/patch.txt)
