### ISSUE TITLE
zabbix_action: operation media type cannot be unset

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#52740]
##### SUMMARY
No way to unset media type for action operations.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
devel

##### CONFIGURATION
Not relevant

##### OS / ENVIRONMENT
Zabbix 4.0.3.

##### STEPS TO REPRODUCE

Create two actions with zabbix_action:
```yaml
  - name: "TEST1"
    event_source: 'trigger'
    operations:
      - type: 'send_message'
        media_type: 'Email'
        send_to_groups:
          - Zabbix administrators

  - name: "TEST2"
    event_source: 'trigger'
    operations:
      - type: 'send_message'
        send_to_groups:
          - Zabbix administrators
```

Notice how the first one specifies to use "Email" media type, while the second one goes to all media types, as expected.

Now modify the definition of the first action and remove the 'media_type' parameter. Re-run the playbook.

##### EXPECTED RESULTS
Action is modified and sends to all media types.

##### ACTUAL RESULTS
Action is not modified.

I've also tried an empty definition, empty string and empty list - neither seemed to work.

Whatever is the correct solution might be good to document, too.
