### ISSUE TITLE
nxos_vlan on Nexus 3k fails with "ValueError: u'2' is not in list"

### ISSUE THREAD

**Issue by nomad-cyanide** [ansible/ansible#52817]
##### SUMMARY
Trying to deploy a vlan on a nexus 3064 using nxos_vlan. Fails with "ValueError: u'2' is not in list"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_vlan

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ist/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.7.7-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 30

```

##### OS / ENVIRONMENT

ITT-SKB-SW-03-2# sh ver
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2015, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

Software
  BIOS:      version 1.7.0
  loader:    version N/A
  kickstart: version 6.0(2)U3(9)
  system:    version 6.0(2)U3(9)
  Power Sequencer Firmware: 
             Module 1: version v1.0
  SFP uC:    version 2.12
  BIOS compile time:       10/14/2013
  kickstart image file is: bootflash:///n3000-uk9-kickstart.6.0.2.U3.9.bin
  kickstart compile time:  9/7/2015 22:00:00 [09/08/2015 06:46:46]
  system image file is:    bootflash:///n3000-uk9.6.0.2.U3.9.bin
  system compile time:     9/7/2015 22:00:00 [09/08/2015 07:58:13]

Hardware
  cisco Nexus 3064 Chassis ("48x10GE + 4x40G Supervisor")
  Intel(R) Celeron(R) CPU        P450 with 3785024 kB of memory.
  Processor Board ID FOC171312CG

  Device name: ITT-SKB-SW-03-2
  bootflash:    2007040 kB

Kernel uptime is 870 day(s), 22 hour(s), 18 minute(s), 25 second(s)

Last reset at 191304 usecs after  Tue Oct  4 12:58:43 2016

  Reason: Reset Requested by CLI command reload
  System version: 6.0(2)U3(9)
  Service: 

plugin
  Core Plugin, Ethernet Plugin
ITT-SKB-SW-03-2# 

##### STEPS TO REPRODUCE

ansible-playbook /prod/ansible-playbooks/addvlan.yaml --limit ITT-SKB-SW-03-2 -e "vlan_name=flannen vlan_id=33" -u ist -k -vvvv

```yaml
---
- hosts: all
  name: Add and Configure vlan
  gather_facts: no
  vars:
    vlan_name: I_AM_NOT_A_REAL_VLAN
    vlan_id: 0

  tasks:
    - name: NXOS Vlan config
      nxos_vlan: 
        vlan_id: "{{ vlan_id }}"
        state: present
        admin_state: up
        name: "{{ vlan_name }}"
      when: ansible_network_os == 'nxos'
    - name: Save changes
      nxos_config:
        save_when: modified
      when: ansible_network_os == 'nxos'
    - name: IOS Vlan config
      ios_vlan:
        vlan_id: "{{ vlan_id }}"
        state: present
        name: "{{ vlan_name }}"
      when: ansible_network_os == 'ios'
    - name: Save changes
      ios_config:
        save_when: modified
      when: ansible_network_os == 'ios'
```

##### EXPECTED RESULTS

The vlan created on the Nexus switch.

##### ACTUAL RESULTS

ist@ITTNETMGR01:/prod/ansible-playbooks> ansible-playbook /prod/ansible-playbooks/addvlan.yaml --limit ITT-SKB-SW-03-2 -e "vlan_name=flannen vlan_id=33" -u ist -k -vvvv
ansible-playbook 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ist/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.7.7-py2.7.egg/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
Using /etc/ansible/ansible.cfg as config file
SSH password: 
setting up inventory plugins
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible-2.7.7-py2.7.egg/ansible/plugins/callback/default.pyc

PLAYBOOK: addvlan.yaml *****************************************************************************************************************************************************************************************************************************************
1 plays in /prod/ansible-playbooks/addvlan.yaml

PLAY [Add and Configure vlan] **********************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [NXOS Vlan config] ****************************************************************************************************************************************************************************************************************************************
task path: /prod/ansible-playbooks/addvlan.yaml:10
<ITT-SKB-SW-03-2> attempting to start connection
<ITT-SKB-SW-03-2> using connection plugin network_cli
<ITT-SKB-SW-03-2> local domain socket does not exist, starting it
<ITT-SKB-SW-03-2> control socket path is /home/ist/.ansible/pc/a520457b73
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: ist on PORT 22 TO ITT-SKB-SW-03-2
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> ssh connection done, setting terminal
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> loaded terminal plugin for network_os nxos
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> loaded cliconf plugin for network_os nxos
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> firing event: on_open_shell()
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<ITT-SKB-SW-03-2> <ITT-SKB-SW-03-2> ssh connection has completed successfully
<ITT-SKB-SW-03-2> connection to remote device started successfully
<ITT-SKB-SW-03-2> local domain socket listeners started successfully
<ITT-SKB-SW-03-2> 
<ITT-SKB-SW-03-2> local domain socket path is /home/ist/.ansible/pc/a520457b73
<ITT-SKB-SW-03-2> ESTABLISH LOCAL CONNECTION FOR USER: ist
<ITT-SKB-SW-03-2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813 `" && echo ansible-tmp-1550828508.49-31016094096813="` echo /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible-2.7.7-py2.7.egg/ansible/modules/network/nxos/nxos_vlan.py
<ITT-SKB-SW-03-2> PUT /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/tmpa1EA6I TO /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py
<ITT-SKB-SW-03-2> EXEC /bin/sh -c 'chmod u+x /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/ /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py && sleep 0'
<ITT-SKB-SW-03-2> EXEC /bin/sh -c '/usr/bin/python /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py && sleep 0'
<ITT-SKB-SW-03-2> EXEC /bin/sh -c 'rm -f -r /home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py", line 113, in <module>
    _ansiballz_main()
  File "/home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_nxos_vlan_payload_yFfGWg/__main__.py", line 689, in <module>
  File "/tmp/ansible_nxos_vlan_payload_yFfGWg/__main__.py", line 667, in main
  File "/tmp/ansible_nxos_vlan_payload_yFfGWg/__main__.py", line 586, in map_config_to_obj
ValueError: u'2' is not in list

fatal: [ITT-SKB-SW-03-2]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ist/.ansible/tmp/ansible-local-12075jIrq1S/ansible-tmp-1550828508.49-31016094096813/AnsiballZ_nxos_vlan.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_nxos_vlan_payload_yFfGWg/__main__.py\", line 689, in <module>\n  File \"/tmp/ansible_nxos_vlan_payload_yFfGWg/__main__.py\", line 667, in main\n  File \"/tmp/ansible_nxos_vlan_payload_yFfGWg/__main__.py\", line 586, in map_config_to_obj\nValueError: u'2' is not in list\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
        to retry, use: --limit @/prod/ansible-playbooks/addvlan.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************
ITT-SKB-SW-03-2            : ok=0    changed=0    unreachable=0    failed=1   

```paste below
I have no idea what to put here! 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_vlan.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_vlan.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrisvanheuveln @jedelman8 @mikewiebe @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nomad-cyanide, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
@nomad-cyanide can you please try this on devel branch and let us know whether the issue persists there or not?

To test on devel branch:
```
git clone https://github.com/ansible/ansible.git
cd ansible
source hacking/env-setup
which ansible
```
The output of the last command should point to `<present-working-directory-path>/bin/ansible`
`ansible --version` command should return `ansible 2.8.0.dev0`
Please note that devel version is for **development/testing purpose only**.

This enables the ansible devel branch on your environment, as soon as you close the window/tab the environment is disabled.

**Comment by nomad-cyanide** [comment]
Hi

It totally works with 2.8.0.dev0. Tried both adding and deleting with 
nxos_vlan. Just went smooth all the way through with no errors.

I will continue testing with nxos_l2_interface, to see if that works 
with 2.8.0.dev0 as well.

Best regards

Ian

**Comment by nomad-cyanide** [comment]
Just did a quick test with nxos_l2_interface with this playbook and command:
ansible-playbook addvlan-esxcl1.yaml --limit nxos-switch -e "vlan_name=flannenTest vlan_id=33" -u username -k -vvvv

```
---
- hosts: all
  name: Add and Configure vlan
  gather_facts: no
  vars:
    vlan_name: I_AM_NOT_A_REAL_VLAN
    vlan_id: 0

  tasks:
    - name: NXOS Vlan config
      nxos_vlan: 
        vlan_id: "{{ vlan_id }}"
        state: present
        admin_state: up
        name: "{{ vlan_name }}"
      when: ansible_network_os == 'nxos'
    - name: Add vlan to interfaces
       nxos_l2_interface:
       name: Ethernet1/43
       mode: trunk
       trunk_vlans: "{{ vlan_name }}"
      when: ansible_network_os == 'nxos'
    - name: Save changes
      nxos_config:
        save_when: modified
      when: ansible_network_os == 'nxos'
    - name: IOS Vlan config
      ios_vlan:
        vlan_id: "{{ vlan_id }}"
        state: present
        name: "{{ vlan_name }}"
      when: ansible_network_os == 'ios'
    - name: Save changes
      ios_config:
        save_when: modified
      when: ansible_network_os == 'ios'
```
With Ansible 2.7.7 I get same error as with nxos_vlan module, which is the ValueError: u'2' is not in list.

With Ansible 2.8.0.dev0 I get this error:
"msg": "show interface ethernet1/43 | json\r\r\n                                             ^\r\n% Invalid command at '^' marker.\r\n\rnxos-switch# "
