### ISSUE TITLE
ovirt_vnic_profile module does not allow removing Network Filter

### ISSUE THREAD

**Issue by nugsolot** [ansible/ansible#52824]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ansible 2.8.0.dev0
  config file = /Users/briwils2/workspace/iova/ansible.cfg
  configured module search path = [u'/Users/briwils2/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jan 12 2019, 21:07:57) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]

Ovirt Engine 4.2.8

Package                 Version
----------------------- ----------
ansible                 2.8.0.dev0
asn1crypto              0.24.0
bcrypt                  3.1.6
certifi                 2018.11.29
cffi                    1.11.5
chardet                 3.0.4
cryptography            2.5
dnspython               1.16.0
enum34                  1.1.6
idna                    2.8
ipaddress               1.0.22
Jinja2                  2.10
jmespath                0.9.3
lxml                    4.3.0
MarkupSafe              1.1.0
netaddr                 0.7.19
ovirt-engine-sdk-python 4.3.0
paramiko                2.4.2
pexpect                 4.6.0
pip                     18.1
ptyprocess              0.6.0
pyasn1                  0.4.5
pycparser               2.19
pycurl                  7.43.0.2
PyNaCl                  1.3.0
PyYAML                  3.13
requests                2.21.0
setuptools              40.6.3
six                     1.12.0
urllib3                 1.24.1
wheel                   0.32.3
xmljson                 0.2.0

##### STEPS TO REPRODUCE

Setup a play book to attempt to remove a network filter from a vnic profile and run against it, when it cant find the "No Network Filter" name it errors out.
Inside the GUI for ovirt-engine there is an option for "No Network Filter" in the network filter selection box.  However looking into the API on a network filter where that is selected show no reference to any network filter at all probably causing the module to get a null response on the id lookup for the name.

```yaml
---
- name: Scratch Pad for testing tasks temporary
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vault.yaml
    - ../vars.yaml

  pre_tasks:
   - name: Obtain SSO token with using username/password credentials
     ovirt_auth:
       state: present
       url: "{{ engine_url }}"
       username: "{{ engine_user }}"
       password: "{{ engine_password}}"
       insecure: true

  post_tasks:
    - name: Always revoke the SSO token
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"

  tasks:
    - name: Setup Inital Non Routable Network Filters
      ovirt_vnic_profile:
        auth: "{{ ovirt_auth }}"
        data_center: "{{ pcloud_name }}"
        name: "{{ pcloud_name }}-{{ item }}"
        network: "{{ pcloud_name }}-{{ item }}"
        network_filter: "No Network Filter"
        #network_filter: None
        #network_filter: Null
      with_sequence: start=1101 end=1102
```

##### EXPECTED RESULTS

Would assign the vnic profile with the no network filter option

##### ACTUAL RESULTS

it errors out with a message about no finding no network filter which does make sense because that sets it to nothing but there should be a way to handle the no network filter as to mimic the selection in the GUI

```paste below
TASK [Setup Inital Non Routable Network Filters] ************************************************************************************************************************************************************
task path: /Users/briwils2/workspace/iova/plays/pcloud/infra/scratch.yaml:27
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_nh78RW/__main__.py", line 251, in main
    ret = entitynics_module.create()
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_nh78RW/ansible_ovirt_vnic_profile_payload.zip/ansible/module_utils/ovirt.py", line 575, in create
    new_entity = self.build_entity()
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_nh78RW/__main__.py", line 194, in build_entity
    if self.param('network_filter') else None
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_nh78RW/__main__.py", line 172, in __get_network_filter_id
    return get_id_by_name(nf_service, self.param('network_filter'))
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_nh78RW/ansible_ovirt_vnic_profile_payload.zip/ansible/module_utils/ovirt.py", line 322, in get_id_by_name
    raise Exception("Entity '%s' was not found." % name)
Exception: Entity 'No Network Filter' was not found.

failed: [localhost] (item=1101) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "custom_properties": null,
            "data_center": "u90c04p08",
            "description": null,
            "fetch_nested": false,
            "migratable": null,
            "name": "u90c04p08-1101",
            "nested_attributes": [],
            "network": "u90c04p08-1101",
            "network_filter": "No Network Filter",
            "pass_through": null,
            "poll_interval": 3,
            "port_mirroring": null,
            "qos": null,
            "state": "present",
            "timeout": 180,
            "wait": true
        }
    },
    "item": "1101",
    "msg": "Entity 'No Network Filter' was not found."
}
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_vnic_profile.py
Pipelining is enabled.
<localhost> EXEC /bin/sh -c '/usr/bin/env python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_w81ylD/__main__.py", line 251, in main
    ret = entitynics_module.create()
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_w81ylD/ansible_ovirt_vnic_profile_payload.zip/ansible/module_utils/ovirt.py", line 575, in create
    new_entity = self.build_entity()
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_w81ylD/__main__.py", line 194, in build_entity
    if self.param('network_filter') else None
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_w81ylD/__main__.py", line 172, in __get_network_filter_id
    return get_id_by_name(nf_service, self.param('network_filter'))
  File "/var/folders/86/s7p69s9101b3tqq1sjmz4qdc0000gn/T/ansible_ovirt_vnic_profile_payload_w81ylD/ansible_ovirt_vnic_profile_payload.zip/ansible/module_utils/ovirt.py", line 322, in get_id_by_name
    raise Exception("Entity '%s' was not found." % name)
Exception: Entity 'No Network Filter' was not found.

failed: [localhost] (item=1102) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "custom_properties": null,
            "data_center": "u90c04p08",
            "description": null,
            "fetch_nested": false,
            "migratable": null,
            "name": "u90c04p08-1102",
            "nested_attributes": [],
            "network": "u90c04p08-1102",
            "network_filter": "No Network Filter",
            "pass_through": null,
            "poll_interval": 3,
            "port_mirroring": null,
            "qos": null,
            "state": "present",
            "timeout": 180,
            "wait": true
        }
    },
    "item": "1102",
    "msg": "Entity 'No Network Filter' was not found."
}

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0
```
