### ISSUE TITLE
debug module with network_cli connection and vault password fails with a TypeError

### ISSUE THREAD

**Issue by branic** [ansible/ansible#52860]
##### SUMMARY

When using the network_cli connection type (to manage a Cisco Nexus switch in my case) with the connection password stored in a vault the debug module fails with a type error. If the password is entered as plain text then the debug task completes successfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

debug

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /home/bevans/cisco/ansible/ansible.cfg
  configured module search path = ['/home/bevans/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 19:49:22) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
ESC[0;33mDEFAULT_HOST_LIST(/home/bevans/cisco/ansible/ansible.cfg) = ['/home/bevans/cisco/ansible/inventory']ESC[0m
ESC[0;33mRETRY_FILES_ENABLED(/home/bevans/cisco/ansible/ansible.cfg) = FalseESC[0m
```

##### OS / ENVIRONMENT

Cisco Nexus 9000 is the target device. I've ran the playbook on both Fedora and RHEL7 as well as with Python2.7 and Python3

##### STEPS TO REPRODUCE

The playbook below will successfully run the `nxos_facts` task, but fails on the `debug` task when the `ansible_password` is set using a vault. If `ansible_password` is set to the plain text password then the playbook will run successfully.

```yaml
Example playbook:

---
- name: facts
  hosts: nxos
  gather_facts: false
  tasks:
    - name: facts task
      nxos_facts:
        gather_subset: all
      register: switch_facts

    - name: debug
      debug:
        var: switch_facts.ansible_net_interfaces



group_vars/nxos.yml
---
ansible_connection: network_cli
ansible_network_os: nxos
ansible_user: admin
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33333331326439366162623437316562633834306630356366306464356536366437303963643639
          3162623838623362316565663031353339353731316437630a653936313932386333356139313766
          39343064313635396634633837636666316430363562616337633161323633633739393235633462
          3832383266316263320a356631656566653366643830303838636332386636326432303830666463
          3536

```

##### EXPECTED RESULTS

The debug module outputs the requested variable.

##### ACTUAL RESULTS

The debug module fails with a TypeError: Object of type AnsibleVaultEncryptedUnicode is not JSON serializable.

```paste below
ansible-playbook --vault-id @prompt test.yml 
Vault password (default): 

PLAY [facts] **************************************************************************************************************************

TASK [facts task] *********************************************************************************************************************
ok: [192.168.150.2]

TASK [debug] **************************************************************************************************************************
fatal: [192.168.150.2]: FAILED! => {"msg": "Traceback (most recent call last):\n  File \"/usr/bin/ansible-connection\", line 328, in <module>\n    main()\n  File \"/usr/bin/ansible-connection\", line 294, in main\n    conn.set_options(var_options=variables)\n  File \"/usr/lib/python3.7/site-packages/ansible/module_utils/connection.py\", line 167, in __rpc__\n    response = self._exec_jsonrpc(name, *args, **kwargs)\n  File \"/usr/lib/python3.7/site-packages/ansible/module_utils/connection.py\", line 144, in _exec_jsonrpc\n    data = json.dumps(req)\n  File \"/usr/lib64/python3.7/json/__init__.py\", line 231, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib64/python3.7/json/encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib64/python3.7/json/encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib64/python3.7/json/encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type AnsibleVaultEncryptedUnicode is not JSON serializable\n"}

PLAY RECAP ****************************************************************************************************************************
192.168.150.2              : ok=1    changed=0    unreachable=0    failed=1   
```
