### ISSUE TITLE
Facts incorrectly report CPU count on ARM

### ISSUE THREAD

**Issue by samdoran** [ansible/ansible#52864]
##### SUMMARY
Ansible incorrectly reports the processor count and VCPUs on ARM systems. This happens because the keys being processed by https://github.com/ansible/ansible/blob/df5b8f65caf0f98cb01a5e920abd4f483b14e82a/lib/ansible/module_utils/facts/hardware/linux.py#L201-L201 match both `processor` and `model name`, but the keys for counting sockets do not match anything in the output. Both occurrences of `processor` and `model_name` are counted as separated CPUs. Furthermore, since there are no occurrences of `vendor_id`, the key count is used to infer the number of CPUs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/module_utils/facts/hardware/linux.py`

##### ANSIBLE VERSION

```paste below
2.5
2.6
2.8
```

##### CONFIGURATION

```paste below
> ansible-config dump --only-changed
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /Users/sdoran/.ansible/ansible.log
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/Users/sdoran/Source/ansible/library']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/sdoran/bin/getvaultkey.sh
```

##### OS / ENVIRONMENT
```
# Control
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

# Managed node
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ uname -a
Linux testing 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux
```

##### STEPS TO REPRODUCE

Gather facts on an ARM system and compare the information to that found in `/proc/cpuinfo`
```
> ansible pi2 -m setup | grep ansible_processor_
        "ansible_processor_cores": 1,
        "ansible_processor_count": 2,
        "ansible_processor_threads_per_core": 1,
        "ansible_processor_vcpus": 2,

# Managed ARM node
$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 0010
Serial		: 000000004a0abca9

```

Here is a playbook:

```yaml
- hosts: all
  become: no

  tasks:
    - name: Show architecture and CPU info
      debug:
        msg: |
          arch: {{ ansible_facts.architecture }}
          cores: {{ ansible_facts.processor_cores }}
          count: {{ ansible_facts.processor_count }}
          threads_per_core: {{ ansible_facts.processor_threads_per_core }}
          vcpus: {{ ansible_facts.processor_vcpus }}
```

##### EXPECTED RESULTS

This is a single core, single thread CPU. The output should reflect that:
```
> ansible pi2 -m setup | grep ansible_processor_
        "ansible_processor_cores": 1,
        "ansible_processor_count": 1,
        "ansible_processor_threads_per_core": 1,
        "ansible_processor_vcpus": 1,
```

##### ACTUAL RESULTS
The value of `i`, a counter in the loop, is used for `processor_count` which then skews the value for `processor_vcpus`
