### ISSUE TITLE
edgeos:  global name 'ConnectionError' is not defined

### ISSUE THREAD

**Issue by mms101** [ansible/ansible#52885]
##### SUMMARY

Hello.
My ansible play ended with error:  "global name 'ConnectionError' is not defined":

It seems, this is mistake in /site-packages/ansible/module_utils/network/edgeos/edgeos.py:
There are string:
from ansible.module_utils.connection import Connection

but, it seems it should be:
from ansible.module_utils.connection import Connection, ConnectionError

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module edgeos_config

##### ANSIBLE VERSION

```paste below
$ ansible --version                                                
ansible 2.7.8
  config file = None
  configured module search path = ['/Users/modest/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.8/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/modest/Google Drive/Work/Projects/Ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/modest/Google Drive/Work/Projects/Ansible/ansible.cfg) = 10
```

##### OS / ENVIRONMENT

ubnt@ubnt:~$ show version
Version:      v1.10.5
Build ID:     5098943
Build on:     06/22/18 15:55
Copyright:    2012-2018 Ubiquiti Networks, Inc.
HW model:     EdgeRouter X 5-Port
HW S/N:       788A20F95B62
Uptime:       19:32:51 up  1:22,  2 users,  load average: 1.09, 1.06, 1.05

##### STEPS TO REPRODUCE

```
- hosts: prepare_ubiquiti_router
  name: Deployment ubiquitu router 
  gather_facts: no
  vars:
    ansible_user: ubnt
    ansible_ssh_pass: !vault |
         <removed>

    ANSIBLE_PERSISTENT_COMMAND_TIMEOUT: 30
    ansible_network_os: edgeos

  tasks:
    - name: add main part 
      edgeos_config:
         save: yes
         lines:
            - set interfaces ethernet eth2 address 2.2.2.2

```

##### EXPECTED RESULTS

Message about wrong command (right command is "set interfaces ethernet eth2 address 2.2.2.2/24")

##### ACTUAL RESULTS

"module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-2582WaLBmx/ansible-tmp-1550931178.32-156872430447117/AnsiballZ_edgeos_config.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-2582WaLBmx/ansible-tmp-1550931178.32-156872430447117/AnsiballZ_edgeos_config.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-2582WaLBmx/ansible-tmp-1550931178.32-156872430447117/AnsiballZ_edgeos_config.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_edgeos_config_payload_gdbppa/__main__.py\", line 287, in <module>\n  File \"/tmp/ansible_edgeos_config_payload_gdbppa/__main__.py\", line 274, in main\n  File \"/tmp/ansible_edgeos_config_payload_gdbppa/__main__.py\", line 234, in run\n  File \"/tmp/ansible_edgeos_config_payload_gdbppa/ansible_edgeos_config_payload.zip/ansible/module_utils/network/edgeos/edgeos.py\", line 107, in load_config\nNameError: global name 'ConnectionError' is not defined\n"

```paste below

```
