### ISSUE TITLE
mongodb_user fails on MongoDB 3.2 config server replicaset

### ISSUE THREAD

**Issue by rhysmeister** [ansible/ansible#52897]
##### SUMMARY

The mongodb_user module fails on MongoDB 3.2 when attempting to create a user against a config server replicaset. The same issue does not occur with MongoDB 3.4, 3.6 or 4.0. The issue is due to write concern restrictions.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongodb_user

##### ANSIBLE VERSION

```
ansible 2.7.7
  config file = None
  configured module search path = ['/Users/rhyscampbell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/python/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.4 (default, Jan  6 2018, 11:51:59) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```
ANSIBLE_COW_SELECTION(env: ANSIBLE_COW_SELECTION) = random
```

##### OS / ENVIRONMENT

Running in integration tests with docker

##### STEPS TO REPRODUCE

```yaml
- name: Add mongodb admin user to each shard 3.4+
  mongodb_user:
    login_host: localhost
    login_port: "{{ item.port }}"
    replica_set: "{{ item.rs }}"
    database: admin
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles: ["root"]
    state: present
  register: mongo_admin_user
  with_items:
    - { "port": 3001, "rs": "{{ mongodb_replicaset1 }}" }
    - { "port": 3004, "rs": "{{ mongodb_replicaset2 }}" }
    - { "port": 4000, "rs": "{{ configsrv_replicaset }}" }
```

The integration tests where this bug was discovered can be found here...

https://github.com/rhysmeister/ansible/tree/mongodb_replicaset_int_tests

Clone the repo and checkout the correct branch...

```
git checkout mongodb_replicaset_int_tests
```
I've fixed this for 3.2 so you'll need to make a minor modification to see the error...

 See the task titled "Add mongodb admin user to each shard 3.4+" and comment out the 'when' clause at the bottom. Ensure mongodb_version is set to 3.2 in the file ..test/integration/targets/setup_mongodb/defaults/main.yml. Then run the tests...

```
test/runner/ansible-test integration -v mongodb_shard --docker ubuntu1604
```

##### EXPECTED RESULTS

User is created without error.

##### ACTUAL RESULTS

Task fails with the following error...

```
TASK [mongodb_shard : Add mongodb admin user to each shard 3.4+] ***************
changed: [testhost] => (item={u'port': 3001, u'rs': u'rs1'}) => {"changed": true, "item": {"port": 3001, "rs": "rs1"}, "user": "test_root"}
changed: [testhost] => (item={u'port': 3004, u'rs': u'rs2'}) => {"changed": true, "item": {"port": 3004, "rs": "rs2"}, "user": "test_root"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationFailure: command SON([('createUser', 'test_root'), ('pwd', u'20d6928b16f9af5c14585ddf610e38ec'), ('digestPassword', False), ('roles', ['root'])]) on namespace admin.$cmd failed: getLastError command failed: w: 'majority' is the only valid write concern when writing to config server replica sets, got: { w: 1, wtimeout: 0 }
failed: [testhost] (item={u'port': 4000, u'rs': u'cfg'}) => {"changed": false, "item": {"port": 4000, "rs": "cfg"}, "msg": "Unable to add or update user: command SON([('createUser', 'test_root'), ('pwd', u'20d6928b16f9af5c14585ddf610e38ec'), ('digestPassword', False), ('roles', ['root'])]) on namespace admin.$cmd failed: getLastError command failed: w: 'majority' is the only valid write concern when writing to config server replica sets, got: { w: 1, wtimeout: 0 }"}
```
Problem does not occur when mongodb_version variable is set to 3.4 or 3.6.
