### ISSUE TITLE
ios_config module fails with wrong error for invalid src option

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#52911]
##### SUMMARY

If the path in src option is invalid the error message reported back is not correct
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below
2.8
```

##### STEPS TO REPRODUCE

```yaml
  tasks:
    - ios_config:
        src: invalid/path
      register: result
      ignore_errors: True

    - debug:
        msg: "{{ result }}"
```

##### EXPECTED RESULTS

Should fail with an error:
```
{
    "msg": {
        "failed": true,
        "msg": "path specified in src not found"
    }
```

##### ACTUAL RESULTS

Fails with erro:

```paste below
{
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/8l/27cd4l3n2vnc2cpk3498__680000gp/T/ansible_ios_config_payload_iFCCGp/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 186, in __rpc__\nansible.module_utils.connection.ConnectionError: abc/ios_config.cfg\r\n                   ^\r\n% Invalid input detected at '^' marker.\r\n\r\nan-ios-02(config)#\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
