### ISSUE TITLE
json_query doesn't work with numbers

### ISSUE THREAD

**Issue by unkaputtbar112** [ansible/ansible#52916]
##### SUMMARY

json_query doesn't work with numbers.
According to that issue: https://github.com/ansible/ansible/issues/24445 where his mistake was to use the variablename instead of variablecontent, it seemed to work after he fixed it with the "port" which is a number/int and not a string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

json_query

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/taabara8/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS/RedHat 7, but irrelevant

##### STEPS TO REPRODUCE

```yaml
---        
- name: testing json_query
  hosts: localhost
  gather_facts: False
  vars:    
    mylist:
      - path: "/dev/sda"
        unit_number: 0
        scsi_id: 0
  tasks:   
           
    - set_fact:
        myquery: "{{ mylist|json_query(query) }}"
      vars:
        query: "[?scsi_id=='0']"
    - debug:
        var: myquery
           
    - set_fact:
        mylist2: "{{ [{ 'path': item.path, 'unit_number': item.unit_number|string, 'scsi_id': item.scsi_id|string }] }}"
      loop: "{{ mylist }}"
    - debug:
        var: mylist2
           
    - set_fact:
        myquery: "{{ mylist2|json_query(query) }}"
      vars:
        query: "[?scsi_id=='0']"
    - debug:
        var: myquery
...   
```

##### EXPECTED RESULTS

I would expect the same output from mylist and mylist2.

I've tried to leave the ' out on the query on the first list, but then it fails with:
fatal: [localhost]: FAILED! => {"msg": "JMESPathError in json_query filter plugin:\nInvalid token.: Parse error at column 11, token \"0\" (NUMBER), for expression:\n\"[?scsi_id==0]\"\n            ^"}

##### ACTUAL RESULTS

```paste below
PLAY [testing json_query] *****************************************************************************************************************************************************************************************

TASK [set_fact] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "myquery": []
}

TASK [set_fact] ***************************************************************************************************************************************************************************************************
ok: [localhost] => (item={u'path': u'/dev/sda', u'unit_number': 0, u'scsi_id': 0})

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "mylist2": [
        {
            "path": "/dev/sda", 
            "scsi_id": "0", 
            "unit_number": "0"
        }
    ]
}

TASK [set_fact] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "myquery": [
        {
            "path": "/dev/sda", 
            "scsi_id": "0", 
            "unit_number": "0"
        }
    ]
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nso/nso_query.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nso/nso_query.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmoberg @cnasten @tbjurman
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@unkaputtbar112, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@unkaputtbar112 You may want to enclose number in first query in ticks (`) like 

```yaml
    - set_fact:
        myquery: "{{ mylist|json_query(query) }}"
      vars:
        query: "[?scsi_id==`0`]"
```
