### ISSUE TITLE
Debug failed bashoutput

### ISSUE THREAD

**Issue by pratikkava1189** [ansible/ansible#52919]
##### SUMMARY
Executing task using custom bash modules, however output is correct and ansible playbook runs, it shows failed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
debug

##### ANSIBLE VERSION
```
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
```
##### OS / ENVIRONMENT
Redhat Enterprise Linux v6

##### STEPS TO REPRODUCE
```yaml
[root@development playbooks]# cat bashuptime.yml
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: uptime by python
    command: uptime
    register: uptimepy

  - name: python debug output
    debug: msg={{ uptimepy }}

  - name: uptime by bash
    bashshell:
      cuscom: uptime
    register: uptimebash

  - name: bash debug output
    debug: var={{ uptimebash }}
```
```bash
[root@development playbooks]# cat library/bashshell.bash
#!/bin/bash
source $1

changed=true
msg=tesxmess
content=ggig
echo sh $cuscom > stdout
if [ `echo $?` == "0" ]; then
   printf '{"changed": %s, "msg": "%s", "contents": %s}' "$changed" "$msg" "$contents"
   #echo { \"changed\": true, \"tested\": test}
   exit 0
else
   echo { \"changed\": false}
   exit 0
fi
[root@development playbooks]#
```
##### EXPECTED RESULTS
It should show as success output.

##### ACTUAL RESULTS
```json
[root@development playbooks]# ansible-playbook bashuptime.yml

PLAY [localhost] ****************************************************************************************************


TASK [uptime by python] *********************************************************************************************

changed: [127.0.0.1]

TASK [python debug output] ******************************************************************************************

ok: [127.0.0.1] => {
    "msg": {
        "changed": true,
        "cmd": [
            "uptime"
        ],
        "delta": "0:00:00.005542",
        "end": "2019-02-25 07:29:11.840162",
        "failed": false,
        "rc": 0,
        "start": "2019-02-25 07:29:11.834620",
        "stderr": "",
        "stderr_lines": [],
        "stdout": " 07:29:11 up 53 days, 17:48,  0 users,  load average: 0.01, 0.01, 0.00",
        "stdout_lines": [
            " 07:29:11 up 53 days, 17:48,  0 users,  load average: 0.01, 0.01, 0.00"
        ]
    }
}

TASK [uptime by bash] ***********************************************************************************************

fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "{\"changed\": true, \"msg\":
 \"tesxmess\", \"contents\": }", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}
       to retry, use: --limit @/home/ansible/playbooks/bashuptime.retry

PLAY RECAP **********************************************************************************************************

127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1
```
