### ISSUE TITLE
command scp hang sometimes

### ISSUE THREAD

**Issue by pandaamanda** [ansible/ansible#52918]
##### SUMMARY

playbook like bellow

1. copy the calico images to 50 nodes
```yaml
- name: Copy calico images file
  command: scp "{{ image_path }}/{{ item }}" {{ ssh_user }}@{{ inventory_hostname|ipwrap() }}:"/tmp/{{ item }}"
  delegate_to: localhost
  with_items:
  - "calico-cni_{{ calico_cni_version }}.tar.gz"
  - "calico-kube-controllers_{{ calico_cni_version }}.tar.gz"
  - "calico-node_{{ calico_cni_version }}.tar.gz"
  async: 7200
  poll: 0
  register: copy_calico_result
```
2. after execute other tasks，check the whether the images copy finished
```yaml
- name: Wait for completing the copy of calico image file
  async_status: jid={{ item.ansible_job_id }}
  register: copy_calico_file_job
  until: copy_calico_file_job.finished
  retries: 300
  delegate_to: localhost
  with_items: "{{ copy_calico_result.results|default([]) }}"
```
the problem is scp command hangs sometimes。
```
[root@node01:~]$ ps -ef |grep scp
root     10327  9751  0 17:12 pts/3    00:00:00 grep --color=auto scp
root     25065 25019  0 16:51 ?        00:00:00 scp files/calico-kube-controllers_v3.1.3.tar.gz ubuntu@192.168.1.47:/tmp/calico-kube-controllers_v3.1.3.tar.gz
root     25068 25065  0 16:51 ?        00:00:00 /usr/bin/ssh -x -oForwardAgent=no -oPermitLocalCommand=no -oClearAllForwardings=yes -l ubuntu -- 192.168.1.47 scp -t /tmp/calico-kube-controllers_v3.1.3.tar.gz
```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
[root@node01:~]$ ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.1.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 13 2017, 12:42:46) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

[root@node01:~]$ cat /etc/os-release
NAME="NewStart Carrier Grade Server Linux"
VERSION="5"
ID="ZTEOS"
ID_LIKE="rhel fedora"
VERSION_ID="5"
PRETTY_NAME="NewStart Carrier Grade Server Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="http://www.gd-linux.com/"
BUG_REPORT_URL="http://www.gd-linux.com/"

REDHAT_BUGZILLA_PRODUCT="NewStart Carrier Grade Server Linux"
REDHAT_BUGZILLA_PRODUCT_VERSION="5"
REDHAT_SUPPORT_PRODUCT="NewStart Carrier Grade Server Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="5"

[root@node01:~]$ openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
