### ISSUE TITLE
EC2 module - delete_on_termination not deleting the root device.

### ISSUE THREAD

**Issue by LozanoMatheus** [ansible/ansible#52979]
##### SUMMARY
When you delete an EC2 with more than one EBS, it not delete all of them. Just delete the root device.

I'm using the parameter `delete_on_termination: True`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_module

##### ANSIBLE VERSION
```text
ansible 2.7.6
config file = /opt/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.6.6 (default, Jan 26 2019, 16:53:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
Output from `ansible-config dump --only-changed`
```text
ALLOW_WORLD_READABLE_TMPFILES(/opt/ansible.cfg) = False
ANSIBLE_NOCOWS(/opt/ansible.cfg) = True
DEFAULT_BECOME(/opt/ansible.cfg) = False
DEFAULT_BECOME_ASK_PASS(/opt/ansible.cfg) = False
DEFAULT_HOST_LIST(/opt/ansible.cfg) = [u'/opt/hosts']
HOST_KEY_CHECKING(/opt/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible.cfg) = False
SYSTEM_WARNINGS(/opt/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Docker image that the ansible was executed.

```text
centos:{latest,centos7,7}
```

File `/etc/*release`

```text
CentOS Linux release 7.6.1810 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core)
```

Output from `uname -a`

```text
Linux bf010fb28ab1 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

Variable file
```yaml
volumes:
  device_name: "/dev/xvda"
  volume_type: "gp2"
  iops: 100
  volume_size: 15
```

Task file
```yaml
- name: Creating the ec2
  ec2:
    state: present
    image: "{{ ami['id'] }}"
    region: "{{ aws_region }}"
    wait: yes
    assign_public_ip: yes
    key_name: "{{ ssh_key['file'] }}"
    instance_type: "{{ instance['type'] }}"
    group_id: "{{ security_group_ids }}"
    count: "{{ instance['count'] | int }}"
    monitoring: yes
    vpc_subnet_id: "{{ subnet['id'] }}"
    user_data: "{{ lookup('file', bootstrap['path'] + bootstrap['item']) }}"
    volumes:
      - device_name: "{{ volumes['device_name'] }}"
        volume_type: "{{ volumes['volume_type'] }}"
        volume_size: "{{ volumes['volume_size'] }}"
        delete_on_termination: True
  with_items:
    - "{{ apps }}"
  register: ec2_return
```

##### EXPECTED RESULTS
Delete all EBS attached to this/these EC2.

##### ACTUAL RESULTS
Just delete the root device (For my case is: `/dev/sda1`).

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @tgerla
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@LozanoMatheus, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Hi, @LozanoMatheus, I'm unable to reproduce this on Ansible 2.7.6 or latest devel. Two volumes are created and both are automatically deleted when I terminate the instance.

When you create the instances, does the block_device_mapping show that some of your volumes don't have delete_on_termination enabled? For example, here's mine:
```
changed: [localhost] => {
    ...
    "instances": [
        {
            "ami_launch_index": "0",
            "architecture": "x86_64",
            "block_device_mapping": {
                "/dev/sda1": {
                    "delete_on_termination": true,
                    "status": "attached",
                    "volume_id": "vol-006b88e085d522aad"
                },
                "/dev/xvda": {
                    "delete_on_termination": true,
                    "status": "attached",
                    "volume_id": "vol-07104237f529c1412"
                }
            },
    ...
```

Some bits of your reproducer are missing, so here's the playbook I used to test:
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    volumes:
      device_name: "/dev/xvda"
      volume_type: "gp2"
      iops: 100
      volume_size: 15
  tasks:
  - name: create instance
    ec2:
      region: us-east-1
      state: present
      image: ami-0ac019f4fcb7cb7e6
      wait: yes
      assign_public_ip: yes
      key_name: "{{ ec2_key }}
      instance_type: t2.micro
      group_id: "{{ sg_ids }}"
      count: 1
      monitoring: yes
      vpc_subnet_id: "{{ subnet_id }}"
      volumes:
        - device_name: "{{ volumes['device_name'] }}"
          volume_type: "{{ volumes['volume_type'] }}"
          volume_size: "{{ volumes['volume_size'] }}"
          delete_on_termination: True
    register: ec2_return

  - set_fact:
      instance_ids: "{{ ec2_return.instance_ids }}"
  - set_fact:
      devices: "{{ ec2_return.instances[0].block_device_mapping }}"
  - set_fact:
      volume_ids: "{{ devices.keys() | list | map('extract', devices, 'volume_id') | list }}"

  - name: delete the instance
    ec2:
      region: us-east-1
      state: absent
      instance_ids: "{{ instance_ids }}"
      wait: yes
      vpc_subnet_id: "{{ subnet_id }}"

  - name: Verify volumes have been deleted - facts are empty
    ec2_vol_facts:
      region: us-east-1
      filters:
        volume-id: "{{ item }}"
    loop: "{{ volume_ids }}"
```
If you're attaching new volumes (such as with the `ec2_vol` module), you'll want to make sure you're setting `delete_on_termination` to the appropriate value. If you could provide a more complete reproducer that would be helpful in pinning down your issue.

needs_info

**Comment by LozanoMatheus** [comment]
Hi @s-hertel.

I believe that I getting this "error" because I'm creating just the "secondary" device.

For example how I'm defining the volumes for this EC2:

```yaml
    volumes:
      - device_name: "/dev/xvda"
        volume_type: "gp2"
        volume_size: "15"
        delete_on_termination: true
```
The output:
```json
{
  "block_device_mapping": {
    "/dev/sda1": {
      "delete_on_termination": false,
      "status": "attached",
      "volume_id": "vol-085f48c7d35b4d437"
    },
    "/dev/xvda": {
      "delete_on_termination": true,
      "status": "attached",
      "volume_id": "vol-05463856aed6e4e1b"
    }
  }
}
```

If I change the `device_name` to `/dev/sda1`, it will create a single device (as root device) and will set `delete_on_termination` to `true`. So, if I define a single device and it has the `device_name` different from `/dev/sda1`, it will create a secondary device (sda1/as root device and a secondary device) and the root device will get the default values/configs.

Apparently, it's more how to use/the AWS API (boto*, maybe) than a bug. But I don't know if it's possible to add a new parameter that will define `delete_on_termination` for all devices.

Something like (`volumes_delete_on_termination`) that :

```yaml
- name: Creating the ec2
  ec2:
    state: present
    image: "{{ ami['id'] }}"
    region: "{{ aws_region }}"
    wait: yes
    assign_public_ip: yes
    key_name: "{{ ssh_key['file'] }}"
    instance_type: "{{ instance['type'] }}"
    group_id: "{{ security_group_ids }}"
    count: "{{ instance['count'] | int }}"
    monitoring: yes
    vpc_subnet_id: "{{ subnet['id'] }}"
    volumes_delete_on_termination: true
    volumes:
      - device_name: "{{ volumes['device_name'] }}"
        volume_type: "{{ volumes['volume_type'] }}"
        volume_size: "{{ volumes['volume_size'] }}"
```

And thanks for sharing your code 💯  ! I like and will use it in here :D
