### ISSUE TITLE
unarchive support for .tar.gz with gtar is unclear

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#52971]
##### SUMMARY

I'm trying to use `unarchive` to download and extract [this file](http://trex-tgn.cisco.com/trex/release/v2.09.tar.gz), which is a `.tar.gz` archive.
The documentation states that this is possible, but the dependencies are unclear.

To do this manually, using the tools already installed on my target, I can use 

```
tar –xzf v2.53.tar.gz
```

So it *should* be possible without installing any other tool.

The [documentation](https://docs.ansible.com/ansible/latest/modules/unarchive_module.html#notes) for unarchive states:

> Can handle .zip files using unzip as well as .tar, .tar.gz, .tar.bz2 and .tar.xz files using gtar.

I do not know what `gtar` is.
`apt install gtar` doesn't work, because that package doesn't exist.

When i try to run my playbook:

```
- name: download and extract trex
  unarchive:
    src: http://trex-tgn.cisco.com/trex/release/v2.09.tar.gz
    dest: src
    remote_src: yes
```

It says:

> "Failed to find handler for \"/tmp/ansible_xthDM6/v2.53.tar.gz\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" could not handle archive. Command \"/usr/bin/unzip\" could not handle archive.

[This website](https://www.poftut.com/linux-gtar-command-tutorial-with-examples-and-compare-with-tar/) claims `gtar` is an alias for `tar`. But when I link `/bin/gtar` to `/bin/tar`, it fails.

> Failed to find handler for \"/tmp/ansible_j_5vQR/v2.53.tar.gz\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" could not handle archive. Command \"/usr/bin/unzip\" could not handle archive.

The documentation should make it clearer what dependencies are required to extract `.tar.gz`. Or perhaps this is a bug with the module itself, since I can manually extract the file with the `tar` utility already installed on the target.

##### ISSUE TYPE

- Documentation Report, maybe? Not sure

##### COMPONENT NAME
`unarchive` module

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/matthew/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

`ansible-config dump --only-changed`

no output

##### OS / ENVIRONMENT
machine running playbook: Ubuntu 18.04

target: Ubuntu 18.04

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/unarchive.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/unarchive.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pileofrogs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
`gtar` is the specific binary name for "gnu-tar".  On Ubuntu 18.04 `/bin/tar` is GNU tar and can be verified using `/bin/tar --version`

On a default Ubuntu 18.04 host, your task works without issue for me.

**Comment by mlda065** [comment]
Hmm. Yeah I just tried on a clean docker container and it works.

Hmm.
Any ideas how else I can debug this?

This ticket should probably be moved from docs to bugs then.

`Dockerfile`:

```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install --yes software-properties-common
RUN apt-add-repository --yes --update ppa:ansible/ansible
RUN apt-get install --yes ansible
ADD playbook.yml playbook.yml
RUN ansible-playbook -K playbook.yml
```

`playbook.yml`:

```
---

- name: run playbook on localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: download and extract trex
      unarchive:
        src: http://trex-tgn.cisco.com/trex/release/v2.09.tar.gz
        dest: ./
        remote_src: yes
```
