### ISSUE TITLE
NXOS playbooks broken by recent commit

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#53011]
##### SUMMARY
The following commit https://github.com/ansible/ansible/commit/cf6a92d268093ae390d31e893712b0e3263c8a37 a few hours back is causing the following error when we try and run our Cisco NX-OS playbooks using `network_cli` connection.

Original PR: https://github.com/ansible/ansible/pull/52604

```
task path: /root/agents-ci/ansible/test/integration/targets/prepare_nxos_tests/tasks/main.yml:2
<n9k.example.com> attempting to start connection
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> local domain socket does not exist, starting it
<n9k.example.com> control socket path is /root/.ansible/pc/35754ea263
<n9k.example.com> loaded cliconf plugin for network_os nxos
<n9k.example.com> 
The full traceback is:
Traceback (most recent call last):
  File "/root/agents-ci/ansible/bin/ansible-connection", line 104, in start
    self.connection._connect()
  File "/root/agents-ci/ansible/lib/ansible/plugins/connection/network_cli.py", line 327, in _connect
    ssh = self.paramiko_conn._connect()
  File "/root/agents-ci/ansible/lib/ansible/plugins/connection/paramiko_ssh.py", line 274, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/root/agents-ci/ansible/lib/ansible/plugins/connection/paramiko_ssh.py", line 387, in _connect_uncached
    raise AnsibleAuthenticationFailure(msg)
AnsibleAuthenticationFailure: Invalid/incorrect username/password. Authentication failed.

fatal: [n9k.example.com]: FAILED! => {
    "msg": "Invalid/incorrect username/password. Authentication failed."
}
```

If I back out this commit the connection to the nxos device succeeds.

```
git checkout 514b974182ff84a72c128d31710591930ee52ae0

agent-ci-143:integration:2084> git log
commit 514b974182ff84a72c128d31710591930ee52ae0
Author: Brian Coca <bcoca@users.noreply.github.com>
Date:   Tue Feb 26 11:51:16 2019 -0500

    Loader invalid plugin nicer error (#52754)
    
    * stop processing invalid plugins

```

Run task:

```
TASK [prepare_nxos_tests : Enable Feature Privilage] *********************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/prepare_nxos_tests/tasks/main.yml:2
<n9k.example.com> attempting to start connection
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> local domain socket does not exist, starting it
<n9k.example.com> control socket path is /root/.ansible/pc/6ef7cc467c
<n9k.example.com> <n9k.example.com> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: admin on PORT 22 TO n9k.example.com
<n9k.example.com> connection to remote device started successfully
<n9k.example.com> local domain socket listeners started successfully
<n9k.example.com> loaded cliconf plugin for network_os nxos
<n9k.example.com> ssh connection done, setting terminal
<n9k.example.com> loaded terminal plugin for network_os nxos
<n9k.example.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<n9k.example.com> firing event: on_open_shell()
<n9k.example.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<n9k.example.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<n9k.example.com> ssh connection has completed successfully
<n9k.example.com> 
<n9k.example.com> local domain socket path is /root/.ansible/pc/6ef7cc467c
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515 `" && echo ansible-tmp-1551211957.8-208953714078515="` echo /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515 `" ) && sleep 0'
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_config.py
<n9k.example.com> PUT /root/.ansible/tmp/ansible-local-22388EJdYXr/tmp4dmNpa TO /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515/AnsiballZ_nxos_config.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515/ /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515/AnsiballZ_nxos_config.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515/AnsiballZ_nxos_config.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-22388EJdYXr/ansible-tmp-1551211957.8-208953714078515/ > /dev/null 2>&1 && sleep 0'
ok: [n9k.example.com] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": null, 
            "backup": false, 
            "backup_options": null, 
            "before": null, 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "host": null, 
            "intended_config": null, 
            "lines": [
                "feature privilege"
            ], 
            "match": "line", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "replace": "line", 
            "replace_src": null, 
            "running_config": null, 
            "save_when": "never", 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "transport": null, 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
All nxos modules over connection type `network_cli`

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0
  config file = /root/agents-ci/ansible/test/integration/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
```paste below
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/root/agents-ci/ansible/test/integration/targets']
DEFAULT_SCP_IF_SSH(/root/agents-ci/ansible/test/integration/ansible.cfg) = True
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True
PERSISTENT_COMMAND_TIMEOUT(env: ANSIBLE_PERSISTENT_COMMAND_TIMEOUT) = 600
PERSISTENT_CONNECT_TIMEOUT(env: ANSIBLE_PERSISTENT_CONNECT_TIMEOUT) = 600
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### STEPS TO REPRODUCE
Run `ansible/test/integration/targets/nxos_l2_interface` test playbook

```yaml
---
- hosts: nxos
  gather_facts: no
  connection: local

  vars:
    debug: false

  roles:
    - { role: nxos_l2_interface }
```

Group Vars:

```yaml
---
cli:
  host: "{{ ansible_ssh_host }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('password') }}"
  transport: cli

nxapi:
  host: "{{ ansible_ssh_host }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('password') }}"
  transport: nxapi
  use_ssl: no

nxapi_ssl:
  host: "{{ ansible_ssh_host }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('password') }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: False

ansible_ssh_user: admin
ansible_ssh_pass: password
ansible_network_os: nxos
ansible_httpapi_port: 80
```
