### ISSUE TITLE
Allow loop on dict keys like python

### ISSUE THREAD

**Issue by guoqiao** [ansible/ansible#53041]
##### SUMMARY

Allow loop on dict keys like python.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- task_executor
- loop

##### ADDITIONAL INFORMATION

Currently ansible support dict loop with `dict2items` filter:
```yaml
- name: dict loop example
  debug:
    msg: "my key is {{item.key}}, my value is {{item.value}}"
  loop: '{{my_dict|dict2items}}'
```
To loop dict, users need to remember a few things in mind:
-  filter `dict2items`
-  use `item` to refer to item
-  use `item.key` to refer to key
-  use `item.value` to refer to value

Considering dict is so common everywhere, above syntax is actually too trivial and overloaded.
The python equavelant is:
```python
for item in [{'key': key, 'value': value} for key, value in my_dict.items()]:
    print(item)
```

In python, you can also loop dict just like list:

```python
for key in my_dict:
    val = my_dict[key]
    print(val)
```
this is handy for usage, breif and consistent in syntax.
Any one with basic python expericence will expect to use similar syntax in ansible:
```yaml
- name: loop dict on key
  debug:
    msg: "dict value for {{item}} is {{my_dict[item]}}"
  loop: '{{my_dict}}'
```
But ansible loop forbid that, which is a pity and unnecessary.
This patch enables this feature with tiny change. 

Example and compare:

```yaml
- hosts: localhost
  vars:
    my_list:
      - item0
      - item1
    my_dict:
      key0: val0
      key1: val1
  tasks:

    - name: loop on list
      debug: var=item
      loop: '{{my_list}}'

    - name: loop dict on key
      debug:
        msg: "dict value for {{item}} is {{my_dict[item]}}"
      loop: '{{my_dict}}'

    - name: loop dict with dict2items
      debug:
        msg: "dict value for {{item.key}} is {{item.value}}"
      loop: '{{my_dict|dict2items}}'

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by guoqiao** [comment]
I've created a PR #53042 for this.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/executor/task_executor.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
We prefer to keep the types accepted strict, you can already do what you want this way:
```yaml
    - name: loop dict on key
      debug:
        msg: "dict value for {{item}} is {{my_dict[item]}}"
      loop: '{{my_dict.keys()|list}}'
      vars:
        my_dict:
            a: 1
            b: 2
```
