### ISSUE TITLE
VMware: vmware_tag fails to update tag and reports changed

### ISSUE THREAD

**Issue by LeDOC666** [ansible/ansible#53060]
##### SUMMARY
Hi, Im working about creating/updating tags on vmware.
Tag creation work, but update statut in changed, but no change on VmWare.
If I repeat execution, still statut change...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_tag.py

##### ANSIBLE VERSION

```ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/datas/ansible/roles']
```

##### OS / ENVIRONMENT

vSphere 6.5

##### STEPS TO REPRODUCE

ansible-playbook -i /common/scripts/ib/inventory/inventory.py test_vcencer.yml -vvv

```
  - name: Create tags
    vmware_tag:
      hostname: '{{ item.name }}'
      username: '***@***.***'
      password: '****'
      validate_certs: false
      category_id: '{{ item.catuid }}'
      tag_name: '{{ tag_save }}'
      tag_description: '** {{ tag_save }} via ANSIBLE'
      state: present
    delegate_to: localhost
    loop:
      - { name: 'vsrv-vc-dmz', catuid: 'urn:vmomi:InventoryServiceCategory:f49d9392-a64a-4f46-a0a9-83a61f3eef5c:GLOBAL' }

```

##### EXPECTED RESULTS

Change Tag Description in VWMare

##### ACTUAL RESULTS

```
changed: [vsrvorabidb2 -> localhost] => (item={u'catuid': u'urn:vmomi:InventoryServiceCategory:f49d9392-a64a-4f46-a0a9-83a61f3eef5c:GLOBAL', u'name': u'vsrv-vc-dmz'}) => {
    "changed": true,
    "invocation": {
        "module_args": {
            "category_id": "urn:vmomi:InventoryServiceCategory:f49d9392-a64a-4f46-a0a9-83a61f3eef5c:GLOBAL",
            "hostname": "vsrv-vc-dmz",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "https",
            "state": "present",
            "tag_description": "** VEEAM - BIAPPS-REC via ANSIBLE",
            "tag_name": "VEEAM - BIAPPS-REC",
            "username": "****@***.***",
            "validate_certs": false
        }
    },
    "item": {
        "catuid": "urn:vmomi:InventoryServiceCategory:f49d9392-a64a-4f46-a0a9-83a61f3eef5c:GLOBAL",
        "name": "vsrv-vc-dmz"
    },
    "results": {
        "msg": "Tag VEEAM - BIAPPS-REC updated.",
        "tag_id": "urn:vmomi:InventoryServiceTag:b88c2b67-0996-4d71-b803-3a5cda075c7d:GLOBAL"
    }
}

```
