### ISSUE TITLE
ec2_group module: rules can't reference containing group

### ISSUE THREAD

**Issue by dhml** [ansible/ansible#5309]
In order to reference the containing group in rules that specify the group_id parameter, one must do the following:

```
- ec2_group:
    ...
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
  register: sg
- ec2_group:
    ...
    rules:
      - proto: all
        group_id: "{{ sg.group_id }}"
```

which is not idempotent.  I propose that the rule group_id parameter accept the special keyword "this" as a means of referencing the group that contains it.  Pull request forthcoming...
