### ISSUE TITLE
Openstack modules don't correctly set auth API version

### ISSUE THREAD

**Issue by megakoresh** [ansible/ansible#53108]
##### SUMMARY
Without an explicitly set environment variable `OS_IDENTITY_API_VERSION`, openstack modules don't properly determine it from given URL (or select latest by default), which leads to 404 errors. This concerns all openstack modules, but I list ones I've been testing with.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_project
os_user_role

##### ANSIBLE VERSION

```paste below
2.7.4
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/e102137/at-vault-password
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT

MacOS Mojave

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  become: false
  connection: local
  gather_facts: false
  tasks:
    - name: create projects
      loop: '{{clouds}}'
      os_project:
        interface: public
        state: present
        name: '{{project_name}}'
        description: '{{project_description}}'
        domain_id: elisa
        enabled: true
        auth:
          auth_url: '{{item.auth_url}}'
          username: '{{item.username}}'
          password: "{{lookup('hashi_vault', 'secret=kv/data/os/{{item.name}}/service_account_password:data')['password']}}"
          project_name: service
          project_domain_id: default
          user_domain_id: default
```

Where `clouds` is someting like

```yaml
clouds:
  - name: os1
    auth_url: https://os1.peruna.com:13000/v3
    username: myservice
```

I have tried to end the auth_url with v3.0, v3 (we dont have an enpoint for v2, it doesnt work) and without any version in URL - always same issue.

##### EXPECTED RESULTS

Module executes using v3 version of openstack identity API. 

##### ACTUAL RESULTS

```
NotFoundException: 404: Client Error for url: https://os1.peruna.com:13000/v2.0/tenants, {"error": {"message": "(https://os1.peruna.com:13000/v2.0/tenants): The resource could not be found.", "code": 404, "title": "Not Found"}}
```

If `OS_IDENTITY_API_VERSION` variable is set to `3`, then the playbook works OK.

This usage pattern is the only non-hacking way to execute playbook tasks on multiple clouds, please fix.
