### ISSUE TITLE
Octal mode incorrect when used with default filter

### ISSUE THREAD

**Issue by quulah** [ansible/ansible#53104]
##### SUMMARY

When used with the `default()` filter, the mode of a file is set to the wrong value.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Probably somewhere deep down, and not related to the file module itself, but:
- lib/ansible/modules/files/file.py

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.6.4
  config file = None
  configured module search path = [u'/Users/kuula/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kuula/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansible
  executable location = /Users/kuula/.pyenv/versions/2.7.14/bin/ansible
  python version = 2.7.14 (default, Sep 26 2018, 14:55:16) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.2)]
```
&

```paste below
$ ansible --version
ansible 2.7.3
  config file = None
  configured module search path = ['/Users/kuula/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kuula/.pyenv/versions/3.7.0/lib/python3.7/site-packages/ansible
  executable location = /Users/kuula/.pyenv/versions/3.7.0/bin/ansible
  python version = 3.7.0 (default, Feb 28 2019, 12:44:36) [Clang 10.0.0 (clang-1000.10.44.4)]
```
##### OS / ENVIRONMENT

Broken both locally on macOS 10.14.3 and a Centos 7 Linux target host.

##### STEPS TO REPRODUCE

This sets the mode incorrectly:
```yaml
- hosts: localhost
  gather_facts: no
  vars:
    file_mode: 0640
  tasks:
    - file:
        path: test.txt
        mode: "{{ my_mode | default(file_mode) }}"
        state: touch
```

These both work as expected:
```yaml
- hosts: localhost
  gather_facts: false
  vars:
    file_mode: "640"
  tasks:
    - file:
        path: test.txt
        mode: "{{ my_mode | default(file_mode) }}"
        state: touch
```
```yaml
- hosts: localhost
  gather_facts: false
  vars:
    file_mode: 0640
  tasks:
    - file:
        path: test.txt
        mode: "{{ my_mode | default(file_mode) }}"
        state: touch
      vars:
        my_mode: 0640
```

##### EXPECTED RESULTS

The mode should be correct even when an octal is passed through `default()`.

```
-rw-r-----  1 kuula  staff     0B Feb 28 12:29 test.txt
```
##### ACTUAL RESULTS

```
-r----xrw-  1 kuula  staff     0B Feb 28 12:33 test.txt
```
