### ISSUE TITLE
junos_config - edit mode

### ISSUE THREAD

**Issue by markeriv** [ansible/ansible#53139]
##### SUMMARY
Enable additional edit modes - particularly "edit private/exclusive" so that interrupted changes will be discarded and reduce chances of lock. Per the output I am seeing it looks like it is hard set to 'exclusive'.

hostname> edit ?
Possible completions:
  <[Enter]>            Execute this command
  batch                Work in batch mode (commit happens in batch)
  dynamic              Work in dynamic database
  exclusive            Obtain exclusive lock (other users cannot make changes)
  private              Work in private database (other's changes do not show)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
junos_config

##### ADDITIONAL INFORMATION

Prevent this issue from occurring when a playbook run is interrupted.

TASK [Push Config] ******************************************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "\n{\"msg\": \"\\nconfiguration database locked by:\\n  JUNOS-RW terminal  (pid 18186) on since 2019-02-28 12:10:04 PST, idle 00:05:03\\n      exclusive \\n\", \"failed\": true, \"invocation\": {\"module_args\": {\"comment\": \"configured by junos_config\", \"username\": null, \"ssh_keyfile\": null, \"rollback\": null, \"src_format\": \"set\", \"src\": 

```
---

- name: Push Config for Each EX3400 stack 
  hosts: access_switches
  connection: local
  gather_facts: no
  vars:
    ansible_ssh_user: "{{ junos_ssh_user }}"
    ansible_ssh_pass: "{{ junos_ssh_pass }}"
    ansible_network_os: junos
    ANSIBLE_PERSISTENT_COMMAND_TIMEOUT: 600

  tasks:
    - name: "Define Provider"
      set_fact:
        provider:
          host: "{{ ansible_ssh_host }}"
          username: "{{ ansible_ssh_user }}"
          password: "{{ ansible_ssh_pass }}"
          ANSIBLE_PERSISTENT_COMMAND_TIMEOUT: 600

    - name: Push Config
      register: push_config_access_output1
      check_mode: no
      diff: yes
      junos_config:
        backup: yes
        src: "{{ playbook_dir }}/config/{{ inventory_hostname }}.conf"
        src_format: set
        update: merge

    - name: copy diff to a file
      when: push_config_access_output1.changed
      lineinfile:
        line: "{{ inventory_hostname }}:\n {{ push_config_access_output1.diff.prepared }}\n"
        dest:  "{{ diff_dir }}/{{ inventory_hostname }}.diff"
        create: yes

```
