### ISSUE TITLE
Incorrect error message from openssl_publickey

### ISSUE THREAD

**Issue by acdha** [ansible/ansible#53140]
##### SUMMARY

I was attempting to make a playbook which would ensures that a target server (all RHEL 7 in this situation) has a key & CSR. openssl_privatekey runs but openssl_publickey fails with the message “the python pyOpenSSL module is required” despite it being installed

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = /Users/cadams/Projects/lc-prometheus-server/ansible.cfg
  configured module search path = ['/Users/cadams/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.8/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
DEFAULT_SCP_IF_SSH(/Users/cadams/Projects/lc-prometheus-server/ansible.cfg) = False
DEFAULT_VAULT_PASSWORD_FILE(/Users/cadams/Projects/lc-prometheus-server/ansible.cfg) = /Users/cadams/Projects/lc-prometheus-server/get_vault_password_from_keyring
RETRY_FILES_ENABLED(/Users/cadams/Projects/lc-prometheus-server/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL 7

##### STEPS TO REPRODUCE
```yaml
- name: Ensure that we have a TLS key for nginx
  block:
      - yum: name=pyOpenSSL state=installed
      - openssl_privatekey:
            path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
            type: RSA
            size: 4096
      - openssl_publickey:
            path: "/etc/pki/tls/certs/{{ inventory_hostname }}.crt"
            privatekey_path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
      - openssl_csr:
            path: "/etc/pki/tls/certs/{{ inventory_hostname }}.csr"
            privatekey_path: "/etc/pki/tls/private/{{ inventory_hostname }}.key"
            ocsp_must_staple: true
            common_name: "prometheus.{{ ansible_domain }}"
            subject_alt_name:
                - "{{ inventory_hostname }}"
```

##### EXPECTED RESULTS

A public key file would exist in the expected location

##### ACTUAL RESULTS

```The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_openssl_publickey_payload_rw3SSJ/__main__.py", line 131, in <module>
    from cryptography.hazmat.backends import default_backend

fatal: [HOSTNAME]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "format": "PEM",
            "group": null,
            "mode": null,
            "owner": null,
            "path": "/etc/pki/tls/certs/HOSTNAME.crt",
            "privatekey_passphrase": null,
            "privatekey_path": "/etc/pki/tls/private/HOSTNAME.key",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null
        }
    },
    "msg": "the python pyOpenSSL module is required"
}
```

Since Ansible doesn't provide real diagnostic output it's not obvious what the real error was. I had no trouble importing OpenSSL or pip-installing `cryptography` and using that.
