### ISSUE TITLE
improve ability to display nested json dictionaries: if a value is a dictionary it wont display correctly in msg

### ISSUE THREAD

**Issue by queglay** [ansible/ansible#53154]
##### SUMMARY

current Ansible version: 2.7.12
It would be helpful to provide more abilities to correctly format json output in debug messages.  methods like -v and from_json do not work in this situation I will explain.

When I read in json from a file, none of the methods to format json apear to work to help display output when reading a value in the dict that is also a dict.  it would be helpful if ansible was able to format this output when displayed in a debug msg.

when the file is initially read with include_vars, -v will correctly display the whole dictionary.  but if you attempt to use something like this to read a value that is also a dictionary, its not possible for me to format it correctly.  for example-

```
debug:
  msg: "{{softnas_list_disk_output_dict.result.records}}"
```

Will not produce nice formatted output.

Here is an example of the json file-

```
{"success" : true, "session_id" : "27108", "result" : {"success":true,"msg":"","records":[{"uuid":null,"brand":"SoftNAS, Amazon Cloud Disk (file)","brand_original":"S3 Cloud Disk Extender","disk_name":"\/dev\/s3-1","partitions":"1","disk_size":"345634576","mounted":false,"disk_extra":"S3 bucket: softnas-test-4, in Default, U.S. Standard region","poolmember":"Available to assign"}],"total":1}}
```

##### ISSUE TYPE
- provide a method to correctly format json

##### COMPONENT NAME
| from_json

##### ADDITIONAL INFORMATION
without this ability its very hard to navigate nested dictionary's.

```yaml
  # with -v this will format correctly when read.
  - include_vars:
      file: /tmp/softnas_list_disk_output_dict.json
      name: softnas_list_disk_output_dict

  - name: this won't format correctly with -v
    shell: |
      cat /tmp/softnas_list_disk_output_dict.json
    register: softnas_list_disk_output_shell

  - name: all json output, wont format correctly in msg.
    debug:
      msg: "{{ softnas_list_disk_output_dict }}"

  - name: sub json output, wont format correctly in msg.
    debug:
      msg: "{{ softnas_list_disk_output_dict.result.records }}"
```
