### ISSUE TITLE
Module for updating distribution release

### ISSUE THREAD

**Issue by dlee** [ansible/ansible#5315]
Ansible should have a module that allows you to specify a Ubuntu/Debian release. For example:

``` yaml

---
  - name: Update Ubuntu to saucy
  - ubuntu_release: name=saucy
```
