### ISSUE TITLE
 Idempotency test failed for openssl_csr (Country Name)

### ISSUE THREAD

**Issue by ag0n1k** [ansible/ansible#53167]
##### SUMMARY

While continuing to use ssl modules, idempotency test still has failures. I have heard about `force` mode, there is no such problem and I have some investigations, see the result below

Once again in function `check`, that returns condition (added some debug):
```python
self.debug.update({
    'subject': _check_subject(csr),
    'ext': _check_extensions(csr),
    'sign': _check_signature(csr)
    }
)
return _check_subject(csr) and _check_extensions(csr) and _check_signature(csr)
```
The debug is:
```json
{
        "ext": true,
        "sign": 1,
        "subject": false,
}
```
So the problem is in the function `_check_subject(csr)`. There is condition of old and new subjects, i add some debug inside the function:
```python
self.debug.update({'subject_old_set': "{}".format(set(subject))})
self.debug.update({'subject_cur_set': "{}".format(set(current_subject))})

if not set(subject) == set(current_subject):
    return False
```
Here is a result:
```json
    "debug": {
        "ext": true,
        "sign": 1,
        "subject": false,
        "subject_cur_set": "{(15, b'TA'), (16, b'test_st'), (17, b'test_on'), (18, b'test_un'), (13, b'example.com')}",
        "subject_old_set": "{(15, b'TA'), (16, b'test_st'), (17, b'test_on'), (14, b'test_cn'), (18, b'test_un'), (13, b'example.com')}"
    },
```
By the name (test_cn) i assume that subject of the new csr does not have country name parameter.

This may be not a root cause of a problem, but it is much like that.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssl_csr
##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = None
  configured module search path = ['/home/ag0n1k/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/py_ansible/lib64/python3.6/site-packages/ansible
  executable location = /opt/py_ansible/bin/ansible
  python version = 3.6.8 (default, Jan 31 2019, 09:38:34) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]
```

##### CONFIGURATION

```paste below
None
```

##### OS / ENVIRONMENT

Fedora 28
Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    ssl_csr_configuration:
      country_name: test_cn
      state_or_province_name: test_st
      locality_name: TA
      organization_name: test_on
      organizational_unit_name: test_un
      common_name: example.com
      basic_constraints: "CA:TRUE"
      basic_constraints_critical: true
      key_usage:
        - keyCertSign
        - cRLSign
        - digitalSignature
  tasks:
    - name: "Generate private key"
      openssl_privatekey:
        path: /tmp/key

    - name: "Generate Certificate Signing Request"
      openssl_csr:
        path: /tmp/req.csr
        privatekey_path: /tmp/key
        attributes: "{{ ssl_csr_configuration.attributes | default(omit) }}"
        basic_constraints: "{{ ssl_csr_configuration.basic_constraints | default(omit) }}"
        basic_constraints_critical: "{{ ssl_csr_configuration.basic_constraints_critical | default(omit) }}"
        common_name: "{{ ssl_csr_configuration.common_name | default(omit)  }}"
        country_name: "{{ ssl_csr_configuration.country_name | default(omit)  }}"
        digest: "{{ ssl_csr_configuration.digest | default(omit)  }}"
        email_address: "{{ ssl_csr_configuration.email_address | default(omit)  }}"
        extended_key_usage: "{{ ssl_csr_configuration.extended_key_usage | default(omit)  }}"
        extended_key_usage_critical: "{{ ssl_csr_configuration.extended_key_usage_critical | default(omit)  }}"
        locality_name: "{{ ssl_csr_configuration.locality_name | default(omit)  }}"
        organization_name: "{{ ssl_csr_configuration.organization_name | default(omit)  }}"
        organizational_unit_name: "{{ ssl_csr_configuration.organizational_unit_name | default(omit)  }}"
        state_or_province_name: "{{ ssl_csr_configuration.state_or_province_name | default(omit)  }}"
        subject_alt_name: "{{ ssl_csr_configuration.subject_alt_name | default(omit)  }}"
        subject_alt_name_critical: "{{ ssl_csr_configuration.subject_alt_name_critical | default(omit)  }}"
        version: "{{ ssl_csr_configuration.version | default(omit)  }}"
        state: "{{ ssl_csr_configuration.state | default(omit) }}"

```

##### EXPECTED RESULTS

```
PLAY [localhost] ***

TASK [Generate private key] ***
ok: [localhost]

TASK [Generate Certificate Signing Request] ***
ok: [localhost]

PLAY RECAP ***
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ***

TASK [Generate private key] ***
ok: [localhost]

TASK [Generate Certificate Signing Request] ***
changed: [localhost]

PLAY RECAP ***
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```
