### ISSUE TITLE
ovirt_network fails to edit/create networks attached to Default cluster

### ISSUE THREAD

**Issue by barloff-st** [ansible/ansible#53181]
##### SUMMARY
If specifying the Default cluster using ovirt_network's "clusters" dict parameter the exception is always hit "Exception("Cluster '%s' was not found." % param_cluster.get('name'))" and "Cluster 'None' was not found."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ovirt_network

##### ANSIBLE VERSION

```paste below
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

RHVH, hosted-engine

##### STEPS TO REPRODUCE

```yaml
- name: Create glusterfs logical network
  ovirt_network:
    auth: "{{ ovirt_auth }}"
    data_center: Default
    name: storage
    description: Gluster Network
    vm_network: false
    state: present
    clusters:
      - name: Default
      - assigned: true
      - required: false
      - display: false
      - migration: true
      - gluster: true
```

##### EXPECTED RESULTS

Creation of logical interface with no errors attached to the Default cluster and with the specified clusters parameters

##### ACTUAL RESULTS

Creation of logical interface with errors attached to the Default cluster but no specified clusters parameters, i.e. gluster: true

```paste below

```
