### ISSUE TITLE
openssl_privatekey - encrypt automatically private keys using vault password

### ISSUE THREAD

**Issue by zlbabe** [ansible/ansible#53191]
##### SUMMARY
Encrypt automatically the private keys when generated by `openssl_privatekey` using vault password.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssl_privatekey

##### ADDITIONAL INFORMATION

To encrypt the private keys, ansible-vault can be invoked but only once the generation is finished. It would be useful if there is an option within `openssl_privatekey` to encrypt automatically the private key once generated.
This would save time for those who need to generate multiple keys and encrypt them before pushing them to remote repo (git for example). This avoids forgetting encrypting private keys before pushing them. 

A simple and basic implementation may be adding a new state called 'encrypted' (I assume that we can also come up with a better implementation). 
```yaml

- openssl_privatekey:
    path: /etc/ssl/private/ansible.com.pem
    size: 2048
    state: encrypted

```
