### ISSUE TITLE
ios_logging: the module performs the configuration, even if not required (destination 'host')

### ISSUE THREAD

**Issue by hexdump0x0200** [ansible/ansible#53226]
##### SUMMARY
The module performs the configuration 'host' destination, even if not required.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_logging

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = /home/administrator/ansible/playbooks/ios_logging_test/ansible.cfg
  configured module search path = [u'/home/administrator/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/administrator/ansible/ansible/lib/ansible
  executable location = /home/administrator/ansible/ansible/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
DEFAULT_TRANSPORT(/home/administrator/ansible/playbooks/ios_logging_test/ansible.cfg) = paramiko
PARAMIKO_HOST_KEY_AUTO_ADD(/home/administrator/ansible/playbooks/ios_logging_test/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/home/administrator/ansible/playbooks/ios_logging_test/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/home/administrator/ansible/playbooks/ios_logging_test/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/administrator/ansible/playbooks/ios_logging_test/ansible.cfg) = False

```

##### OS / ENVIRONMENT
debian 9.8
cisco ios 12

##### STEPS TO REPRODUCE
cisco config:
```
test-sw1#sh run | i logging
no logging buffered
no logging console
no logging monitor
```

```yaml
---
- hosts: all
  gather_facts: no
  tasks:
  - name: configure syslog servers
    ios_logging:
     dest: host
     name: "192.168.1.1"

  - name: configure syslog servers (idempotent)
    register: result
    ios_logging:
     dest: host
     name: "192.168.1.1"

  - name: test
    assert:
     that:
     - "result.changed == false"
```
##### EXPECTED RESULTS
The task "configure syslog servers" should have the status "changed",
The task "configure syslog servers (idempotent)" should have the status "ok"
The task "test" should have the status "ok".

##### ACTUAL RESULTS
```
PLAY [all] ****************************************************************************************************

TASK [configure syslog servers] *******************************************************************************
changed: [test-sw1] => {"changed": true, "commands": ["logging 192.168.1.1"]}

TASK [configure syslog servers (idempotent)] ******************************************************************
changed: [test-sw1] => {"changed": true, "commands": ["logging 192.168.1.1"]}

TASK [test] ***************************************************************************************************
fatal: [test-sw1]: FAILED! => {
    "assertion": "result.changed == false ", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}

PLAY RECAP ****************************************************************************************************
test-sw1               : ok=2    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
