### ISSUE TITLE
Whitespace control for the ini_file module

### ISSUE THREAD

**Issue by mrmeszaros** [ansible/ansible#53235]
##### SUMMARY

The `ini_file` module could be configured how to handle whitespaces.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`ini_file`

##### ADDITIONAL INFORMATION
Currently the ini_file always puts a whitespace around the `=`, like this:
```ini
[section]
option = value
```
However some ini like files might follow other style. For example when systemd unit files (although strictly speaking not ini file) use a no-whitespace stlye, as well as `application.desktop` files.

For example:
```yaml
- name: Fix open vm tools service
  ini_file:
    path: /lib/systemd/system/open-vm-tools.service
    section: Unit
    option: After
    value: dbus.service
    whitespace: o=v
```

The `whitespace` option could receive a format-like string with the three mandatory parts (option equals value), and whitespace characters (tabs and spaces).
The default would be then `o = v` to reflect how it currently works.

A similar whitespace related issue #35710 might be solved with this:
```yaml
whitespace: '  o = v'
```
