### ISSUE TITLE
docker_swarm_service module should allow adding and removing custom host-to-IP mappings

### ISSUE THREAD

**Issue by raidokaldma** [ansible/ansible#53263]
##### SUMMARY
Docker Swarm supports adding creating, adding and removing custom host-to-IP mappings, but **docker_swarm_service** does not.

Docker examples:
```
docker service create --host my-host:1.2.3.4 my-service-name
```
See `--host` in https://docs.docker.com/engine/reference/commandline/service_create/

```
docker service update --host-rm my-host:1.2.3.4 --host-add my-host:4.3.2.1 my-service-name
```
See `--host-rm` and `--host-add` in https://docs.docker.com/engine/reference/commandline/service_update/

I would like to be able to use **docker_swarm_service** to put my docker service in desired state with provided hosts.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_swarm_service

##### ADDITIONAL INFORMATION

```yaml
-   name: change myservice.image
    docker_swarm_service:
        name: myservice
        image: "alpine:edge"
        hosts: # This is not possible right now, but I would like to be able to specifiy hosts like this
        - "my-host:1.2.3.4"
```
