### ISSUE TITLE
IOS devices: information missing from show commands when using e.g. parse_cli()

### ISSUE THREAD

**Issue by ajsiersema** [ansible/ansible#53277]
##### SUMMARY
The 'show vlan' output for VLAN's with lots of active ports will be spread over multiple lines with terminal length 512. This makes parse_cli() miss ports as there is no way to match lines starting with whitespace instead of the VLAN ID.
This issue is circumvented by sending 'terminal width 0' to an IOS device. If the device in question doesn't support width 0, we can first send 512 and subsequently try 0. If 0 fails, 512 will be the width, like the current implementation.

Unfortunately Cisco NX-OS (at least up to 7.1) doesn't support term width 0 or > 511
I haven't been able yet to check IOS-XR.
Hence the IOS scoping. At least it's possible to fix the issue there.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_command
ansible/plugins/terminal/ios.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /home/ops/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules', '/home/ops/local/ansible-modules']
  ansible python module location = /home/ops/lib/python3.7/site-packages/ansible
  executable location = /home/ops/bin/ansible
  python version = 3.7.0 (default, Jan 16 2019, 12:24:08) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

```paste below
DEFAULT_ACTION_PLUGIN_PATH(/home/ops/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/action_plugins', '/home/ops/local/ansible-plugins/action']
DEFAULT_ASK_VAULT_PASS(/home/ops/ansible/ansible.cfg) = True
DEFAULT_FILTER_PLUGIN_PATH(/home/ops/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/filter_plugins', '/home/ops/local/ansible-plugins/filter']
DEFAULT_FORKS(/home/ops/ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/home/ops/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/ops/ansible/ansible.cfg) = ['/home/ops/ansible/inventoryyaml']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/ops/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/inventory_plugins', '/home/ops/local/ansible-plugins/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/ops/ansible/ansible.cfg) = True
DEFAULT_LOOKUP_PLUGIN_PATH(/home/ops/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/lookup_plugins', '/home/ops/local/ansible-plugins/lookup']
DEFAULT_MODULE_PATH(/home/ops/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/modules', '/home/ops/local/ansible-modules']
DEFAULT_STDOUT_CALLBACK(/home/ops/ansible/ansible.cfg) = yaml
DEFAULT_TRANSPORT(/home/ops/ansible/ansible.cfg) = local
DEFAULT_VARS_PLUGIN_PATH(/home/ops/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/vars_plugins', '/home/ops/local/ansible-plugins/vars']
INVENTORY_ENABLED(/home/ops/ansible/ansible.cfg) = ['yaml']
PERSISTENT_COMMAND_TIMEOUT(/home/ops/ansible/ansible.cfg) = 120
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/ops/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/ops/ansible/ansible.cfg) = 120
RETRY_FILES_ENABLED(/home/ops/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RedHat 6.8
IOS-XE version 03.06.08.E (15.2-2e8)

##### STEPS TO REPRODUCE

Configure more than 60 ports in a VLAN.
parse_cli() the output of show vlan

Example parsers/cisco/ios_show_vlan_parser.yaml : 

```yaml
vars:
  vlan:
    id: "{{ item.id }}"
    name: "{{ item.name }}"
    status: "{{ item.status }}"
    ports: "{{ (item.ports|replace('Te', 'TenGigabit') | replace('Po','PortChannel')).split(', ')|select|list }}"

keys:
  vlans:
    value: "{{ vlan }}"
    items: "^(?P<id>\\d+)\\s+(?P<name>\\S+)\\s+(?P<status>[a-z]{4,})\\s*(?P<ports>([A-Za-z]+).+)?"
```

Example playbook (excerpt) : 

```yaml
  vars:
      vlan_parse_path: parsers/cisco/ios_show_vlan_parser.yaml

    tasks:
    - block:
        - name: "Get vlan list from switch, parse into structured data"
          ios_command:
            commands:
              - "show vlan"
          register: vlan_output
        - set_fact:
            all_vlans: "{{ vlan_output.stdout[0] | parse_cli(vlan_parse_path) }}"

```

##### EXPECTED RESULTS

Get all ports parsed

##### ACTUAL RESULTS

Not all ports included, after 512 chars the ports get wrapped to a new line, parse_cli() will not be able to match the line.

```paste below

```
