### ISSUE TITLE
allow kubernetes node-version as a parameter for gcp_container_node_pool

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#53304]
##### SUMMARY
When using gcloud I am able to specify which Kubernetes version I'd like the nodepool to have, Unfortunately this isn't possible with the Ansible module at this time.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_container_node_pool

##### ADDITIONAL INFORMATION
```yaml
- gcp_container_node_pool:
    node_version: 1.12.5-gke.5
....
```
