### ISSUE TITLE
jenkins_script: Template file

### ISSUE THREAD

**Issue by aquaplanet** [ansible/ansible#53319]
##### SUMMARY

Add parameter src to jenkins_script.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Module: jenkins_script

##### ADDITIONAL INFORMATION

Add "src" parameter to the module which should be mutually exclusive to "script". If src is specified it looks for a file under templates directories (if args is specified) or files directories (otherwise). The rest is the same as if script (and the file contents was its value) was specified.

If both script and src is specified, IMO the playbook should stop with an error. It is confusing to everyone having two scripts for the same task, which one will execute? Better to force having just one instead of a choice by precedence.

I think this would deliver a clean playbook separating what to do from how to do it. It leaves the playbook small, hiding the details in another file which could explain its functionality with a good filename. Nor do I see this change breaking backwards compatibility.

```yaml
- name: load template file script.j2 and apply args to it
  jenkins_script:
    src: script.j2
    args:
      jenkins_mode: Node.Mode.EXCLUSIVE

- name: looks for script.groovy under files directories and run it on the server
  jenkins_script:
    src: script.groovy
    user: admin
    password: admin
    url: https://localhost
    validate_certs: no

- name: script and src not allowed together, this should IMO cause an error
  jenkins_script:
    src: script.j2
    script: "{{ setmaster_mode }}"
    args:
      jenkins_mode: Node.Mode.EXCLUSIVE
```
