### ISSUE TITLE
yum module: with incorrect package names can result in partial changes

### ISSUE THREAD

**Issue by mvermaes** [ansible/ansible#5332]
If I use this play:

```
  tasks:
  - name: Testing
    yum: name={{ item }} state=present
    with_items:
    - postgresql
    - xxx
```

(where postgresql is a package that wasn't previously installed, and xxx is a package that doesn't exist in any repo), the task will fail, but postgresql gets installed. If postgresql is moved to the line under xxx, then the play will fail, and neither package will be installed.

I think it would be good if the result was the same regardless of the ordering, or maybe there is some way to generate a 'partial installation' warning message at least.

This is with ansible 1.5 (devel 3f81c3c416) last updated 2013/12/19 00:42:36 (GMT +800) by the way.
