### ISSUE TITLE
ecs_task does not support launch_type parameter

### ISSUE THREAD

**Issue by SJrX** [ansible/ansible#53352]
##### SUMMARY
No launch_type argument for ecs_task module.

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ecs_task 

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /path/to/ansible.cfg
  configured module search path = ['/path/to/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/path/to/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/path/to/ansible.cfg) = ['/path/to/ansible/inventory']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
INVENTORY_ENABLED(/path/to/ansible.cfg) = ['host_list', 'script', 'yaml', 'ini', 'auto', 'azure_rm']
```

##### OS / ENVIRONMENT

Linux / Arch.

##### STEPS TO REPRODUCE

Create an ecs_taskdefinition with a launch_type of fargate. 

```yaml
-
name: Run task
  ecs_task:
    operation: run
    cluster: console-sample-app-static-cluster
    launch_type: FARGATE
    task_definition: console-sample-app-static-taskdef
    count: 1
    started_by: ansible_user
  register: task_output
```

##### EXPECTED RESULTS

ECS task is launched on fargate

##### ACTUAL RESULTS

```paste below
Unsupported parameters for (ecs_task) module: launch_type Supported parameters include: aws_access_key, aws_secret_key, cluster, container_instances, count, ec2_url, network_configuration, operation, overrides, profile, region, security_token, started_by, task, task_definition, validate_certs
```
