### ISSUE TITLE
first_found Lookup w/ Skip Fails When Used Multiple Times

### ISSUE THREAD

**Issue by sw-elling** [ansible/ansible#53370]
##### SUMMARY
When using the first_found lookup with skip set to true, the first_found lookup works as expected but follow-up first_found lookups fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
first_found plugin

##### ANSIBLE VERSION

Ansible version 2.6 was not tested.

```paste below
ansible 2.4.6.0
  config file = /home/REDACTED/.ansible.cfg
  configured module search path = [u'/home/REDACTED/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Oct 21 2017, 15:18:57) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
```
```
ansible 2.5.14
  config file = /home/REDACTED/.ansible.cfg
  configured module search path = [u'/home/REDACTED/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python/virtualenv/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /usr/local/lib/python/virtualenv/ansible-2.5/bin/ansible
  python version = 2.7.14 (default, Oct 21 2017, 15:18:57) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
```
```
ansible 2.7.8
  config file = /home/REDACTED/.ansible.cfg
  configured module search path = [u'/home/REDACTED/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python/virtualenv/ansible-2.7/lib/python2.7/site-packages/ansible
  executable location = /usr/local/lib/python/virtualenv/ansible-2.7/bin/ansible
  python version = 2.7.14 (default, Oct 21 2017, 15:18:57) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/REDACTED/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/REDACTED/.ansible.cfg) = True
CACHE_PLUGIN(/home/REDACTED/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/REDACTED/.ansible.cfg) = $HOME/.cache/ansible
CACHE_PLUGIN_TIMEOUT(/home/REDACTED/.ansible.cfg) = 604800
COLOR_VERBOSE(/home/REDACTED/.ansible.cfg) = bright blue
DEFAULT_FORKS(/home/REDACTED/.ansible.cfg) = 16
DEFAULT_GATHERING(/home/REDACTED/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/REDACTED/.ansible.cfg) = [u'/etc/ansible/inventory']
DEFAULT_LOG_PATH(/home/REDACTED/.ansible.cfg) = /home/REDACTED/log/ansible.log
DEFAULT_REMOTE_TMP(/home/REDACTED/.ansible.cfg) = ~/.ansible/tmp
DEFAULT_STDOUT_CALLBACK(/home/REDACTED/.ansible.cfg) = debug
DEFAULT_TRANSPORT(/home/REDACTED/.ansible.cfg) = ssh
DISPLAY_SKIPPED_HOSTS(/home/REDACTED/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/REDACTED/.ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/REDACTED/.ansible.cfg) = /home/REDACTED/.ansible/retry
SHOW_CUSTOM_STATS(/home/REDACTED/.ansible.cfg) = True
```

##### OS / ENVIRONMENT

```sh
$ lsb_release -ds
"CentOS release 6.8 (Final)"
```

##### STEPS TO REPRODUCE

The "when" conditions were added as a result of #43833.

```yaml
# vim: syntax=yaml expandtab ts=2
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: True

####################
# These pre-tasks are only here to set up the environment to demonstrate the
# problem.
#
  pre_tasks:
  - name: "Pre-task: Setup Directories"
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - /tmp/ansible-test-dest
    - "/tmp/ansible-test-src2/{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}"
    - "/tmp/ansible-test-src3/{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}"

  - name: "Pre-task: Setup Files"
    copy:
      content: |
        {{ item | basename }}
      dest: "{{ item }}"
    with_items:
    - "/tmp/ansible-test-src2/{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}/first-found-lookup-2"
    - "/tmp/ansible-test-src3/{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}/first-found-lookup-3"
#
####################

  tasks:
  - name: First Found Lookup 1 (dir)
    vars:
      path_lookup:
        files:
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_version) | lower }}/"
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}/"
        - "{{ ansible_distribution | lower }}/"
        - "{{ ansible_os_family | lower }}/"
        paths:
        - /tmp/ansible-test-src1
        skip: true
      src_path: "{{ lookup('first_found', path_lookup) }}"
    copy:
      src: "{{ src_path }}"
      dest: /tmp/ansible-test-dest/
      backup: no
      mode: 0644
    when: src_path

  - name: First Found Lookup 2 (file)
    vars:
      path_lookup:
        files:
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_version) | lower }}/first-found-lookup-2"
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}/first-found-lookup-2"
        - "{{ ansible_distribution | lower }}/first-found-lookup-2"
        - "{{ ansible_os_family | lower }}/first-found-lookup-2"
        paths:
        - /tmp/ansible-test-src2
        skip: true
      src_path: "{{ lookup('first_found', path_lookup) }}"
    template:
      src: "{{ src_path }}"
      dest: /tmp/ansible-test-dest/first-found-lookup-2
      backup: no
      mode: 0644
    when: src_path
#    when: src_path | list

  - name: First Found Lookup 3 (dir)
    vars:
      path_lookup:
        files:
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_version) | lower }}/"
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}/"
        - "{{ ansible_distribution | lower }}/"
        - "{{ ansible_os_family | lower }}/"
        paths:
        - /tmp/ansible-test-src3
        skip: true
      src_path: "{{ lookup('first_found', path_lookup) }}"
    copy:
      src: "{{ src_path }}"
      dest: /tmp/ansible-test-dest/
    when: src_path
#    when: src_path | list

  - name: First Found Lookup 4 (file)
    vars:
      path_lookup:
        files:
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_version) | lower }}/first-found-lookup-4"
        - "{{ (ansible_distribution ~ '/' ~ ansible_distribution_major_version) | lower }}/first-found-lookup-4"
        - "{{ ansible_distribution | lower }}/first-found-lookup-4"
        - "{{ ansible_os_family | lower }}/first-found-lookup-4"
        paths:
        - /tmp/ansible-test-src4
        skip: true
      src_path: "{{ lookup('first_found', path_lookup) }}"
    template:
      src: "{{ src_path }}"
      dest: /tmp/ansible-test-dest/first-found-lookup-4
      backup: no
      mode: 0644
    when: src_path
#    when: src_path | list
...
```

##### EXPECTED RESULTS

```
PLAY [127.0.0.1] *****************************************************************************************************************************************************

TASK [Pre-task: Setup Directories] ***********************************************************************************************************************************
changed: [127.0.0.1] => (item=/tmp/ansible-test-dest)
changed: [127.0.0.1] => (item=/tmp/ansible-test-src2/centos/6)
changed: [127.0.0.1] => (item=/tmp/ansible-test-src3/centos/6)

TASK [Pre-task: Setup Files] *****************************************************************************************************************************************
changed: [127.0.0.1] => (item=/tmp/ansible-test-src2/centos/6/first-found-lookup-2)
changed: [127.0.0.1] => (item=/tmp/ansible-test-src3/centos/6/first-found-lookup-3)

TASK [First Found Lookup 1 (dir)] ************************************************************************************************************************************

TASK [First Found Lookup 2 (file)] ***********************************************************************************************************************************
changed: [127.0.0.1]

TASK [First Found Lookup 3 (dir)] ************************************************************************************************************************************
changed: [127.0.0.1]

TASK [First Found Lookup 4 (file)] ***********************************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************************************************
127.0.0.1                  : ok=4    changed=4    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```paste below
PLAY [127.0.0.1] *****************************************************************************************************************************************************

TASK [Pre-task: Setup Directories] ***********************************************************************************************************************************
changed: [127.0.0.1] => (item=/tmp/ansible-test-dest)
changed: [127.0.0.1] => (item=/tmp/ansible-test-src2/centos/6)
changed: [127.0.0.1] => (item=/tmp/ansible-test-src3/centos/6)

TASK [Pre-task: Setup Files] *****************************************************************************************************************************************
changed: [127.0.0.1] => (item=/tmp/ansible-test-src2/centos/6/first-found-lookup-2)
changed: [127.0.0.1] => (item=/tmp/ansible-test-src3/centos/6/first-found-lookup-3)

TASK [First Found Lookup 1 (dir)] ************************************************************************************************************************************

TASK [First Found Lookup 2 (file)] ***********************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {
    "failed": true
}

MSG:

The conditional check 'src_path' failed. The error was: Invalid conditional detected: invalid syntax (<unknown>, line 1)

The error appears to have been in '/home/REDACTED/etc/ansible/examples/lookup-first_found-skip.yml': line 52, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: First Found Lookup 2 (file)
    ^ here


        to retry, use: --limit @/home/REDACTED/.ansible/retry/lookup-first_found-skip.retry

PLAY RECAP ***********************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=2    unreachable=0    failed=1
```

**Comment by sw-elling** [comment]
The only way I've found to work around this issue is to use the "list" filter in the when condition.

**Comment by goneri** [comment]
In can simplify the problem to that:

```yaml
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: True
  tasks:
  - name: First Found Lookup 1 (dir)
    vars:
      path_lookup:
        files:
        - "fstab"
        paths:
        - /etc
        skip: true
      src_path: "{{ lookup('first_found', path_lookup) }}"
    debug:
      msg: "{{ src_path }}"
    when: src_path
```

Everything is fine if I replace the when condition with `when: "lookup('first_found', path_lookup)"`.

**Comment by goneri** [comment]
`src_path` is not evaluate when you reach the `when` the first time. You can use a `set_fact` before to fix its value.
The `when` is also problematic, Ansible evaluate the value of the variable before the test and it fails. I believe the error is something like:

```
The conditional check '/etc/fstab' failed. The error was: template error while templating string: unexpected '/'. String: {% if /etc/fstab %} True {% else %} False {% endif %}
```

`lookup` a string in case of success, or an empty list in case of error. So you can change your condition to something like below:

```yaml
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - set_fact:
      src_path: "{{ lookup('first_found', path_lookup) }}"
    vars:
      path_lookup:
        files:
        - "fstab"
        paths:
        - /etc
        skip: true
  - debug:
      var: src_path
    when: src_path|length>0
```
