### ISSUE TITLE
VMware: Return vim.virtualmachine._moId as value in response facts JSON

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#53372]
##### SUMMARY

Return the Mo_id in the response facts (not only when tags exist)

##### ISSUE TYPE
- Feature Idea
Return mo_id for use cases where users may want to later interact with the vc/vm via REST.

##### COMPONENT NAME

vmware_guest_facts

##### ADDITIONAL INFORMATION

The data set of facts currently returned doesnt contain the morefid (vim.VirtualMachine._moId)

If we cant get it added as a response fact which shouldnt be too much hassle

Below should do the trick inside the module (outside the scope of the tag check)
instance.update(vm_mid=vm._moId)

This would provide capacity to use REST calls to uniquely address the vm,
in a few circumstances including post provisioning

```yaml
- name: Gather facts for single VM
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    uuid: 421e4592-c069-924d-ce20-7e7533fab926
  delegate_to: localhost
  register: facts
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @ckotte @dav1x @lparkes @nerzhul @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@blambo10, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@blambo10 Thanks for the feature request. There are two ways two achieve this - 

1. With Pyvmomi version less than 6.7.1.2018.12, use PR #53523 (Backward compatible) 

2. With Pyvmomi version equal or greater than 6.7.1.2018.12, use following PB,

```yaml
    - name: Gather Managed object ID (moid) from a guest using the vSphere API output schema for REST Calls
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: Asia-Datacenter1
        folder: /Asia-Datacenter1
        name: "{{ vm_name }}"
        schema: vsphere
        properties:
          - _moId
```
