### ISSUE TITLE
openssl_* modules: PyOpenSSL asks user for password if trying to open password-protected key

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#53376]
##### SUMMARY
As reported in #53360, the `openssl_certificate` module will hang (on remote nodes) if a password-protected private key is used, while the `passphrase` option is not provided to the module. If the module is run on `localhost` (with `local` connection), one can see that PyOpenSSL asks for a password: it shows a `Enter PEM pass phrase:` prompt and waits for the user to enter something before trying to open the private key.

This problem also appears with the `openssl_csr` module and with `openssl_privatekey` itself (in all cases with the `PyOpenSSL` backend, with the `cryptography` backend this doesn't happen).

CC @johnwesley

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_privatekey
openssl_csr
openssl_certificate

##### ANSIBLE VERSION
```paste below
2.7.x
```

##### STEPS TO REPRODUCE
```yml
---
- hosts: localhost
  tasks:
  - openssl_privatekey:
      path: bla.key
      passphrase: xyz
      cipher: aes256
      select_crypto_backend: pyopenssl
  - openssl_privatekey:
      path: bla.key
      # passphrase: xyz
      # cipher: aes256
      select_crypto_backend: pyopenssl
  - openssl_csr:
      path: bla.csr
      privatekey_path: bla.key
      # privatekey_passphrase: xyz
      select_crypto_backend: pyopenssl
  - openssl_certificate:
      path: bla.pem
      privatekey_path: bla.key
      # privatekey_passphrase: xyz
      csr_path: bla.csr
      provider: selfsigned
```
This playbook hangs on every step (except the first). Uncommenting the options in each step make the playbook finish this step (and hang on the next one where the passphrase is still commented out).

(The `select_crypto_backend: pyopenssl` option is only needed for `devel` branch; for 2.7.x it must be left away.)
