### ISSUE TITLE
Variable check tries to decrypt password for unaccessed variables

### ISSUE THREAD

**Issue by dosera** [ansible/ansible#53388]
##### SUMMARY
Ansible variables are evaluated even though they are not accessed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /ansible-playbooks/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/path/to/playbooks/ansible.cfg) = True
COLOR_DEBUG(/path/to/playbooks/ansible.cfg) = bright gray
COLOR_VERBOSE(/path/to/playbooks/ansible.cfg) = dark gray
DEFAULT_FILTER_PLUGIN_PATH(/path/to/playbooks/ansible.cfg) = [u'/path/to/playbooks/plugins/filter']
DEFAULT_FORKS(/path/to/playbooks/ansible.cfg) = 1
DEFAULT_HOST_LIST(/path/to/playbooks/ansible.cfg) = [u'/path/to/playbooks/inventory/.private']
DEFAULT_MANAGED_STR(/path/to/playbooks/ansible.cfg) = This file is managed by ansible, don't make changes here - they will be overwritten.
DEFAULT_POLL_INTERVAL(/path/to/playbooks/ansible.cfg) = 10
DEFAULT_REMOTE_USER(/path/to/playbooks/ansible.cfg) = development
DEFAULT_ROLES_PATH(/path/to/playbooks/ansible.cfg) = [u'/path/to/playbooks/ext/roles', u'/path/to/playbooks/roles']
INVENTORY_IGNORE_EXTS(/path/to/playbooks/ansible.cfg) = ['["~"', '".orig"', '".bak"', '".ini"', '".cfg"', '".retry"', '".pyc"', '".pyo"', '".empty"]']
RETRY_FILES_ENABLED(/path/to/playbooks/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/path/to/playbooks/ansible.cfg) = /path/to/playbooks/.retry-files
```

##### OS / ENVIRONMENT
WSL @ Win 10

##### STEPS TO REPRODUCE
execute the task described below

Host
```
list:
   - id: id-1
     password: !vault |
        $ANSIBLE_VAULT;....
   - id: id-2
     password: 1234
   - id: id-3
     password: 45678

```

Task
```
- name: Ids have to be given
  assert:
    that:
      - "'id' in item.keys()"
  with_items:
    - "{{ list }}"
```

##### EXPECTED RESULTS
Expected to evaluate OK and to not throw an error.

##### ACTUAL RESULTS
```
fatal: [host]: FAILED! => {"msg": "Attempting to decrypt but no vault secrets found"}
```
