### ISSUE TITLE
Use aws_ec2.py to get an invetory of all linux server

### ISSUE THREAD

**Issue by ReinerNippes** [ansible/ansible#53397]
##### SUMMARY
I would like to get an inventory of all linux server with aws_ec2.py 
But 
```
plugin: aws_ec2
filters:
  platform: ''
```
doesn't work.

##### ISSUE TYPE
- Documentation Report
Please include an example to filter all instances where platform is '' (aka blank).
 
##### COMPONENT NAME
plugin: lib/ansible/plugins/inventory/aws_ec2.py

##### OS / ENVIRONMENT
AWS

##### ANSIBLE VERSION
2.7, 2.8

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/doc_fragments/aws.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/aws.py)
* [lib/ansible/plugins/inventory/aws_ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ReinerNippes: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/plugins/inventory/aws_ec2.py

**Comment by Akasurde** [comment]
cc @s-hertel

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/inventory/aws_ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/doc_fragments/aws.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/aws.py)
* [lib/ansible/plugins/inventory/aws_ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/inventory/aws_ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tinproject** [comment]
With this you can get groups by platform:

```yaml
keyed_groups:
  # Create groups for platform
  - prefix: 'platform'
    separator: '_'
    key: "platform | default('linux')"  # aws does not populate the platform field for linux hosts
```

```
# ansible-inventory --list -y output
all:
  children:
    aws_ec2:
      hosts:
        ...
    platform_linux:
      hosts:
        ...
    platform_windows:
      hosts:
        ...
    ungrouped: {}
```
