### ISSUE TITLE
Amazon AWS rds_intance - cannot create instance with aurora-mysql engine

### ISSUE THREAD

**Issue by ruimoreira** [ansible/ansible#53404]
##### SUMMARY
When creating a rds_instance with aurora-mysql engine the module expects a cluster_id, the documentation states that we should use rds_cluster module to manage however said module does not  exist. For reference see https://docs.ansible.com/ansible/latest/modules/rds_instance_module.html#id5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rds_instance module 

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = None
  configured module search path = [u'/Users/ru.moreira/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, May  4 2017, 09:21:27) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
MacOS 

##### STEPS TO REPRODUCE

```
- name: create minimal aurora instance in default VPC and default subnet group
  rds_instance:
    engine: aurora
    db_instance_identifier: ansible-test-aurora-db-instance
    instance_type: db.t2.small
    password: "{{ password }}"
    username: "{{ username }}"
    cluster_id: ansible-test-cluster  # This cluster must exist - see rds_cluster to manage it

```

##### EXPECTED RESULTS

A database instance is created, if a cluster is required the we need to have a module that allows for the cluster creation

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "engine is aurora-mysql but all of the following are missing: cluster_id"}

```
