### ISSUE TITLE
xml module in ansible 2.8 fails to fetch attribute content

### ISSUE THREAD

**Issue by tiraboschi** [ansible/ansible#53459]
##### SUMMARY
xml module in ansible 2.8 fails to fetch attribute content.
This is probably due to a side effect of https://github.com/ansible/ansible/pull/28662/files

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Centos 7.6 with 
ansible.noarch                               2.8.0-1.201903062333git.156613f025.el7.ans

##### STEPS TO REPRODUCE
Try to fetch the value of an attribute with
   content: attribute

```yaml
---
- name: Test xml module
  hosts: localhost
  connection: local
  tasks:
  - name: Parse OVF
    xml:
      path: "/root/ova.ovf"
      xpath: /ovf:Envelope/Section/Disk
      namespaces:
        ovf: http://schemas.dmtf.org/ovf/envelope/1/
        rasd: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData
        vssd: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData
        xsi: http://www.w3.org/2001/XMLSchema-instance
      content: attribute
      attribute: size
    register: disk_size_xml
  - debug: var=disk_size_xml
```

##### EXPECTED RESULTS
I expect the content of size attribute.

##### ACTUAL RESULTS
It fails with:
"msg": "missing parameter(s) required by 'attribute': value"

and if I add the value parameter it fails (as expected) with:
"msg": "parameters are mutually exclusive: add_children, content, count, print_match, set_children, value"

```paste below
[root@c76he20190307h1 ~]# cat ova.ovf
<ovf:Envelope ovf:version="0.9" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1/" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><References><File ovf:description="f4387c33-6d2b-48a8-b1a4-86398f27d022" ovf:href="364012f0-198f-43ef-88a0-6b4dac1d6a24/f060934e-2701-4432-93b8-9eb13f061f44" ovf:id="f060934e-2701-4432-93b8-9eb13f061f44" ovf:size="54760833024" /></References><Section xsi:type="ovf:NetworkSection_Type"><Info>List of Networks</Info></Section><Section xsi:type="ovf:DiskSection_Type"><Disk ovf:actual_size="51" ovf:boot="true" ovf:disk-interface="VirtIO" ovf:disk-type="System" ovf:diskId="f060934e-2701-4432-93b8-9eb13f061f44" ovf:fileRef="364012f0-198f-43ef-88a0-6b4dac1d6a24/f060934e-2701-4432-93b8-9eb13f061f44" ovf:format="http://www.vmware.com/specifications/vmdk.html#sparse" ovf:parentRef="" ovf:size="51" ovf:vm_snapshot_id="b4ef4820-7335-49e6-89ea-0be288aa4e9c" ovf:volume-format="COW" ovf:volume-type="Sparse" ovf:wipe-after-delete="false" /></Section><Content ovf:id="out" xsi:type="ovf:VirtualSystem_Type"><Name>f4387c33-6d2b-48a8-b1a4-86398f27d022</Name><TemplateId>f4387c33-6d2b-48a8-b1a4-86398f27d022</TemplateId><Description>Created by OVABuilder</Description><Domain /><CreationDate>2019/03/05 09:14:28</CreationDate><TimeZone /><IsAutoSuspend>false</IsAutoSuspend><VmType>1</VmType><default_display_type>0</default_display_type><default_boot_sequence>1</default_boot_sequence><Section ovf:id="f4387c33-6d2b-48a8-b1a4-86398f27d022" ovf:required="false" xsi:type="ovf:OperatingSystemSection_Type"><Info>Guest OS</Info><Description>OtherLinux</Description></Section><Section xsi:type="ovf:VirtualHardwareSection_Type"><Info>4 CPU, 16384 Memory</Info><System><vssd:VirtualSystemType>RHEVM 4.6.0.163</vssd:VirtualSystemType></System><Item><rasd:Caption>4 virtual CPU</rasd:Caption><rasd:Description>Number of virtual CPU</rasd:Description><rasd:InstanceId>1</rasd:InstanceId><rasd:ResourceType>3</rasd:ResourceType><rasd:num_of_sockets>1</rasd:num_of_sockets><rasd:cpu_per_socket>4</rasd:cpu_per_socket></Item><Item><rasd:Caption>16384 MB of memory</rasd:Caption><rasd:Description>Memory Size</rasd:Description><rasd:InstanceId>2</rasd:InstanceId><rasd:ResourceType>4</rasd:ResourceType><rasd:AllocationUnits>MegaBytes</rasd:AllocationUnits><rasd:VirtualQuantity>16384</rasd:VirtualQuantity></Item><Item><rasd:Caption>Drive 1</rasd:Caption><rasd:InstanceId>f060934e-2701-4432-93b8-9eb13f061f44</rasd:InstanceId><rasd:ResourceType>17</rasd:ResourceType><rasd:HostResource>364012f0-198f-43ef-88a0-6b4dac1d6a24/f060934e-2701-4432-93b8-9eb13f061f44</rasd:HostResource><rasd:Parent>00000000-0000-0000-0000-000000000000</rasd:Parent><rasd:Template>00000000-0000-0000-0000-000000000000</rasd:Template><rasd:ApplicationList /><rasd:StorageId>00000000-0000-0000-0000-000000000000</rasd:StorageId><rasd:StoragePoolId>00000000-0000-0000-0000-000000000000</rasd:StoragePoolId><rasd:CreationDate>2019/03/05 09:14:28</rasd:CreationDate><rasd:LastModified>2019/03/05 09:14:28</rasd:LastModified></Item><Item><rasd:Caption>Ethernet 0 rhevm</rasd:Caption><rasd:InstanceId>3</rasd:InstanceId><rasd:ResourceType>10</rasd:ResourceType><rasd:ResourceSubType>3</rasd:ResourceSubType><rasd:Connection>rhevm</rasd:Connection><rasd:Name>eth0</rasd:Name><rasd:speed>1000</rasd:speed></Item><Item><rasd:Caption>Graphics</rasd:Caption><rasd:InstanceId>5</rasd:InstanceId><rasd:ResourceType>20</rasd:ResourceType><rasd:VirtualQuantity>1</rasd:VirtualQuantity></Item></Section></Content></ovf:Envelope>

[root@c76he20190307h1 ~]# ansible-playbook -vvvv -i localhost, test.yml
ansible-playbook 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to localhost
Parsed localhost, inventory source with host_list plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yml ***********************************************************************************************************************************************************************************************************************************************************************
Positional arguments: test.yml
become_method: sudo
inventory: (u'localhost,',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in test.yml

PLAY [Trigger ovirt.hosted_engine_setup role] ********************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************
task path: /root/test.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402 `" && echo ansible-tmp-1551971382.05-269672232839402="` echo /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-12538JcaAEL/tmpiw_DDq TO /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402/ /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1551971382.05-269672232839402/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Parse OVF] *************************************************************************************************************************************************************************************************************************************************************************
task path: /root/test.yml:6
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212 `" && echo ansible-tmp-1551971382.92-37176930905212="` echo /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/xml.py
<localhost> PUT /root/.ansible/tmp/ansible-local-12538JcaAEL/tmp6Y2g5P TO /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212/AnsiballZ_xml.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212/ /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212/AnsiballZ_xml.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212/AnsiballZ_xml.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1551971382.92-37176930905212/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attribute": "size", 
            "backup": false, 
            "content": "attribute", 
            "count": false, 
            "input_type": "yaml", 
            "insertafter": false, 
            "insertbefore": false, 
            "namespaces": {
                "ovf": "http://schemas.dmtf.org/ovf/envelope/1/", 
                "rasd": "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData", 
                "vssd": "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", 
                "xsi": "http://www.w3.org/2001/XMLSchema-instance"
            }, 
            "path": "/root/ova.ovf", 
            "pretty_print": false, 
            "print_match": false, 
            "state": "present", 
            "strip_cdata_tags": false, 
            "xpath": "/ovf:Envelope/Section/Disk"
        }
    }, 
    "msg": "missing parameter(s) required by 'attribute': value"
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/xml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
Is this a regression (i.e. did it work with earlier releases) ?

**Comment by tiraboschi** [comment]
Yes, it's working as expected in 2.7.z: I think it has been introduced here https://github.com/ansible/ansible/pull/28662/files#diff-08db906cc1b77bbca8b05466314d1e01R836

Also on the examples on https://docs.ansible.com/ansible/latest/modules/xml_module.html
we have

```
# How to read an attribute value and access it in Ansible
- name: Read attribute value
  xml:
    path: /foo/bar.xml
    xpath: /business/website/validxhtml
    content: attribute
    attribute: validatedon
  register: xmlresp
```

that now is going to fail since now we are enforcing a check for 'value' when we have 'attribute' while 'value' (to write the attribute) and 'content' (to read it) are mutually exclusive.

**Comment by sandrobonazzola** [comment]
any update?

**Comment by mwperina** [comment]
Dag/Magnus/Tim, could you please take a look? This is a regression (it works fine with Ansible 2.7) and it will break oVirt/RHV when Ansible 2.8.0 is released.

@dagwieers @magnus919 @tbielawa

**Comment by dagwieers** [comment]
Yep, I am looking at this now. It is strange that this usage is not covered by our existing integration tests.

**Comment by dagwieers** [comment]
Ok, I am not 100% this is a regression in the sense that what you ought to be doing is:

```yaml
---
- name: Test xml module
  hosts: localhost
  connection: local
  tasks:
  - name: Parse OVF
    xml:
      path: "/root/ova.ovf"
      xpath: /ovf:Envelope/Section/Disk/size
      namespaces:
        ovf: http://schemas.dmtf.org/ovf/envelope/1/
        rasd: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData
        vssd: http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData
        xsi: http://www.w3.org/2001/XMLSchema-instance
      content: attribute
    register: disk_size_xml
```

Because the xml module is not using the value of `attribute` at all, it is returning the information coming from the xpath only. So it is ignoring the `attribute` parameter (as was documented/commented in the code and only now activated).

The stricter parameter testing was planned before, but because the supporting code was not accepted to Ansible for a few releases was not activated until now.

**Comment by tiraboschi** [comment]
If you look at https://docs.ansible.com/ansible/latest/modules/xml_module.html in the example section you have:

```yaml
# How to read an attribute value and access it in Ansible
- name: Read attribute value
  xml:
    path: /foo/bar.xml
    xpath: /business/website/validxhtml
    content: attribute
    attribute: validatedon
  register: xmlresp

- name: Show attribute value
  debug:
    var: xmlresp.matches[0].validxhtml.validatedon
```

And this is now broken so I think it's a regression or at lest remove the broken example.
