### ISSUE TITLE
file/template module does not set owner correctly before validating when using become

### ISSUE THREAD

**Issue by lucc** [ansible/ansible#53516]
##### SUMMARY
The `file` and `template` module do not set the correct file owner *before* calling the `validate` command when `become: true` is also given.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- file
- template

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/luc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION
can be empty but for readablility and debugging I set these in the environment:
```
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
```

##### OS / ENVIRONMENT
tested from Arch Linux, managing Arch Linux & CentOS 7

##### STEPS TO REPRODUCE
- Use this playbook as `bug.yml`:
```yaml
- hosts: localhost
  tasks:
    - file: path=foo state=touch
    - template: # or copy either one reproduces the problem
        src: foo
        dest: bar
        mode: '0777'
        # force ls to fail so that we see the stdout of it.
        validate: 'ls -l %s THIS_DOES_NOT_EXIST'
      become: true
```
- run
`ANSIBLE_STDOUT_CALLBACK=yaml ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook bug.yml -K`
- check the remot file that was keept:
`ls -l /home/luc/.ansible/tmp/ansible-tmp-1552040351.6839142-113674593213739/source` (replace with correct file path)

##### EXPECTED RESULTS
I expect the file to be owned by `root:root`:
```
-rwxrwxrwx 1 root root 0 Mar  8 11:19 /home/luc/.ansible/tmp/ansible-tmp-1552040351.6839142-113674593213739/source
```

##### ACTUAL RESULTS
The file is owned by the connecting user as can be seen from the (intentionally) failing task and the ls on the remote file afterwards:
```
TASK [template] ************************************************
fatal: [localhost]: FAILED! => changed=false 
  checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
  exit_status: 2
  msg: failed to validate
  stderr: |-
    ls: cannot access 'THIS_DOES_NOT_EXIST': No such file or directory
  stderr_lines:
  - 'ls: cannot access ''THIS_DOES_NOT_EXIST'': No such file or directory'
  stdout: |-
    -rwxrwxrwx 1 luc luc 0 Mar  8 11:19 /home/luc/.ansible/tmp/ansible-tmp-1552040351.6839142-113674593213739/source
  stdout_lines: <omitted>
```
and 
```
-rwxrwxrwx 1 luc luc 0 Mar  8 11:19 /home/luc/.ansible/tmp/ansible-tmp-1552040351.6839142-113674593213739/source
```

##### RELATED ISSUES
- #25667 for ansible 2.3 with some permission error, and a much bigger playbook and roles, otherwise very similar
- #46971 for ansible 2.6 but without an example playbook
- #11385 for ansible 1 and more concerned with permission than owner/group
- #28315 which strangely resolved itself
