### ISSUE TITLE
elasticache_parameter_group doesn't support group_family redis5.0

### ISSUE THREAD

**Issue by stevenscg** [ansible/ansible#53543]
##### SUMMARY
elasticache_parameter_group doesn't support the group_family redis5.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elasticache_parameter_group

##### ANSIBLE VERSION
```
ansible 2.7.8
  python version = 2.7.14 (default, Mar 25 2018, 16:06:33) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
- name: Create Elasticache Parameter Group
  elasticache_parameter_group:
    state: present
    name: 'testing-group'
    group_family: 'redis5.0'
    description: 'testing-group'
```

##### EXPECTED RESULTS
Creates a parameter group with group_family redis5.0

##### ACTUAL RESULTS
Throws error that redis5.0 isn't a valid option:

```
value of group_family must be one of: memcached1.4, redis2.6, redis2.8, redis3.2, redis4.0, got: redis5.0
```
