### ISSUE TITLE
Wishlist:  Improve "error while evaluating conditional" message

### ISSUE THREAD

**Issue by kevinoid** [ansible/ansible#5356]
It would be great if the error messages produced by errant `when` clauses could be improved by being more specific about the particular error which caused the clause to fail to evaluate.

As a motivating example, my playbook had the following incorrect code:

```
when: find_result.results[int(item) - 1].stdout == ""
```

Which should have been:

```
when: find_result.results[(item|int()) - 1].stdout == ""
```

Unfortunately, this took me quite a while to figure out (mostly due to my poor understanding of how `register` interacts with looping in addition to my misconception about whether the syntax was Jinja or Python).  It was not helped by the error message which was produced:

```
fatal: [hostname] => error while evaluating conditional: find_result.results[int(item) - 1].stdout == ""
```

In contrast to the significantly more useful error message which is printed when the same error occurs in a template:

```
fatal: [hostname] => {'msg': "One or more undefined variables: 'int' is undefined", 'failed': True}
```

I realize this is due to some special-casing of how "is defined" and "is undefined" are handled in `when` clauses, but it would be great if the more descriptive error message could be included in the output when these operators are not in use.

Thanks!

**Comment by pztrick** [comment]
I'd have to concur....

```
- name: Fetch RDS endpoint
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
      default_env: "dev"
      env: "{{ e | default(default_env)}}"
  vars_files:
    - vars/{{env}}/ec2.yml
  tasks:
    - name: get RDS instance facts
      local_action: rds command=facts instance_name={{rds_instance_name}} region={{region}}
      register: rds

    # - name: ensure that RDS is available
    #   assert: { that: "{{rds.instance.status}} == available" }

    - name: ensure that RDS is available
      assert: { that: "'{{rds.instance.status}}' == 'available'" }
```

The latter version works, and the commented version fails with this error message:

```
fatal: [localhost] => error while evaluating conditional: available == available
```

Sure looks like a valid comparison to me! :D I'm a Python developer so it was easier to try casting different types -- but other people merely using YAML because it's clear could be thrown for a loop.

Perhaps leaving quotes intact to show str type (versus undefined variable `available`) would help? e.g. `"available" == available`

**Comment by rhartkopf** [comment]
:+1: I'm currently troubleshooting a conditional and getting this same useless error message. Extra details would be very valuable.

```
- name: wait for route53 to return answer for this host
  connection: local
  command: dig +short {{ inventory_hostname }}
  register: route53_result
  until: '"{{ ip_address }}" in route53_result.stdout'
  changed_when: False
  retries: 20
  delay: 6
```

```
TASK: [route53_entries | wait for route53 to return answer for this host] ***** 
fatal: [dev.example.com] => error while evaluating conditional: "54.67.116.7" in route53_result.stdout
```

**Comment by bcoca** [comment]
try:

```
until: '{{ ip_address in route53_result.stdout}}'
```

The error comes from a failure of jinja2 to template the string, which we capture andn show as the 'evaluating conditional' and the string that it produced.  We could append the jinja2 error, not that I think will be more helpful in this case.

**Comment by MrMMorris** [comment]
running into this error as well and can't seem to figure out what's wrong:

```
command: docker pull tv-{{ item[0] }}:{{ item[1] }}-latest
  register: tv_{{ item[0] }}_{{ item[1] }}
  changed_when: tv_{{ item[0] }}_{{ item[1] }}.stdout.find('Downloaded newer image') != -1
  sudo: yes
  with_nested:
    - ['client', 'server']
    - ['dev']
```

`error while evaluating conditional: tv_client_dev.stdout.find('Downloaded newer image') != -1`

Any ideas?

**Comment by sivel** [comment]
@MrMMorris You cannot use variables in a 'register' line.  It is not templated, and that is on purpose.

So you are literally creating a variable called `tv_{{ item[0] }}_{{ item[1] }}`

You can only use static variable names in a register.

**Comment by MrMMorris** [comment]
well that's a huge pain....

then why does it show up as having evaluated the variables in the error? Or it's just the register...

**Comment by philbert** [comment]
I spent the best part of a day debugging this problem and was about to raise new issue until I learned the underlying cause was probably python's [character validity for identifiers and keywords](https://docs.python.org/2/reference/lexical_analysis.html#grammar-token-identifier).

I hit this error because I was trying to evaluate a conditional against a group name with a "-" character such as:

```
[some-group]
some-host
```

Ansible itself doesn't seem to worry about that too much until I tried to do something like this:
`when: '"some-host" in groups.some-group'`

...which resulted in this rather unhelpful error message:
`fatal: [some-host] => error while evaluating conditional: "some-host" in groups.some-group`

After some painful hours of trial and error I discovered that the conditional evaluated fine when the group name was named "some_group".

**Comment by discordianfish** [comment]
@phiche When I read you comment, I though "Wow, that guy probably saved me those painful hours". Until I replaced my - with a _ and still get the same error (not that this would work, since the var comes from ec2.py inventory):

Condition:

```
  when: ec2_tag_aws_cloudformation_stack_name == "us-east-1"
```

Log:

```
fatal: [XX.XX.XX.XX] => error while evaluating conditional: ec2_tag_aws_cloudformation_stack_name == "us-east-1"
```

Looks like in my case it's similar issue though: ec2.py generates the inventory json with (-) in the variable names. Ansible then silently ignores those variables so when I try to access it in 'where' it errors out again without a useful error message.

It's really impressive in how many ways ansible can break AND being totally silent about what caused it. Migrating off from ansible is already on my roadmap just as usual no time for that..

**Comment by berdario** [comment]
Apparently, it even hides error messages that belong to another part of the task

I had this task:

```
- name: Install ruby 2.2.1
  sudo: False
  command: rbenv install -s 2.2.1
  environment:
    CFLAGS: -fPIC
  register: rbenv_install
  changed_when: rbenv_install.stdout
```

it complained that `error while evaluating conditional: rbenv_install.stdout`

while the actual error was that rbenv was not available in the PATH

**Comment by bmhkim** [comment]
Exactly what @berdario said. I had this:

```
- name: ssh test nc {{ custom_ssh_port }}
  local_action: shell nc -z -w5 {{ inventory_hostname }} {{ custom_ssh_port }}
  register: nc_ssh_port
```

Ansible complained, `error while evaluating conditional: nc_ssh_default.stdout == ""` when in fact, the actual error was that ansible was trying to sudo on my local machine without a valid password. I wasted far too much time trying to figure out this issue today.

I'm really getting tired of things like this. Ansible seems like it has a lot of promise, but debug/development aids when trying to pull together playbooks seem to be extremely sorely lacking.

**Comment by dellis23** [comment]
+1 from me

I had this conditional:

```
when: resizing and not already_resized|bool
```

Which gave this output:

```
fatal: [foo.com] => error while evaluating conditional: resizing and not already_resized|bool
```

Turning on verbose output didn't help.  This conditional seemed to fix it:

```
when: "{{ resizing and not already_resized|bool }}"
```

At this point it's voodoo to me as to when I need to surround things in quotes, braces, cast to bool, or add an arbitrary `==` in there.

**Comment by davisonio** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by edulix** [comment]
+1

**Comment by kclausen-tm** [comment]
+1

**Comment by ghost** [comment]
+1, getting:
`error while evaluating conditional: current_zone.stdout != elasticsearch_timezone`

Edit: I think I figured this one out, but yeah, just doesn't tell me anything about where to start looking. What failed, why?

**Comment by gkibilov** [comment]
until: rds.instance.status == "available"
works fine on OSX on Linux same script gives error:
fatal: [localhost] => error while evaluating conditional: rds.instance.status == "available"

No idea what to look for!

**Comment by gvenka008c** [comment]
Any idea on how to fix this error?

  - name: Check if ln exists
    stat: path=/var/lib/docker/
    register: sym

  - name: stop docker
    #shell: systemctl stop docker
    service: name=docker state=stopped
    when: sym.stat.islnk == False
    tags: mount_docker_fs


Error:
TASK [mesos_slave : stop docker] ***********************************************
fatal: [6bb71f7b-4f75-4810-a5a1-55b8c56bac7a]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'sym.stat.islnk == False' failed. The error was: ERROR! error while evaluating conditional (sym.stat.islnk == False): ERROR! 'sym' is undefined\n\nThe error appears to have been in '/ansible/roles/mesos_slave/tasks/mount_fs.yml': line 21, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: stop docker\n    ^ here\n"}

**Comment by MrMMorris** [comment]
@gvenka008c 

I recommend checking if 'sym.stat.islnk' exists or is what you want like this:

``` yaml
debug: msg="{{ sym.stat.islnk }}"
```

**Comment by ipsi** [comment]
Another +1, but this time with an exciting difference:

```
  roles:
  - { role: Linux, when: '{{ ansible_system }} == "Linux"' }
  - { role: Darwin, when: '{{ ansible_system }} == "Darwin"' }
```

Gave the following error:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '{{ ansible_system }} == \"Darwin\"' failed. The error was: error while evaluating conditional ({{ ansible_system }} == \"Darwin\"): 'Darwin' is undefined"}
```

Which is damned peculiar, since it clearly made it past the first conditional (Linux), and that conditional also worked on my Linux box.

The following then worked:

```
  roles:
  - { role: Linux, when: '"{{ ansible_system }}" == "Linux"' }
  - { role: Darwin, when: '"{{ ansible_system }}" == "Darwin"' }
```

Why do I need to quote `{{ ansible_system }}` when comparing `Darwin` to `Darwin`, but _not_ when comparing `Darwin` to `Linux`? Who knows!

**Comment by nicolas-g** [comment]
+1 

This is very annoying , for the bellow playbook I get  **The conditional check 'rds.instance.status == \"available\"** if I don't have boto installed or my AWS credentials don't have the right access to deploy RDS. It makes it really heard to understand where the issue is .

```
    - name: Launch RDS instance
      local_action:
        module: rds
        instance_name: "rds-test-instance"
        db_engine: "postgres"
        command: create
        port: 7432
        size: "10"
        instance_type: "db.m4.large"
        region: "us-east-1"
        username: "masterUsername"
        password: "masterPassword"
        engine_version: "9.4.7"
        multi_zone: "false"
        parameter_group: "default.postgres9.4"
        backup_retention: "14"
        upgrade: no
      become: False
      register: rds
      until: rds.instance.status == "available"
      retries: 30
      delay: 60
```

**Comment by jimi-c** [comment]
@ipsi it is because you're using the `{{}}` variable syntax. All `when` statements are evaluated via the jinja2 templating system, which means your comparision ended up looking like this: `when: Darwin == "Darwin"`. As such, the templating system looked for the variable `Darwin` (as it had no quotes) and failed. For future reference, you do not need to use the curly braces for `when` statements, simply do `when: ansible_system == "Darwin"`.

**Comment by jimi-c** [comment]
@gkibilov and @nicolas-g, we do not insert that error for `until` statements, so I'm not sure where you're getting that error from.

**Comment by jimi-c** [comment]
Sorry to take so long to get back to this issue, however as of 2.0+, the error message for conditional errors of this nature is much more verbose and clear:

<pre>
TASK [debug] *******************************************************************
task path: /home/jamesc/testing/5356.yml:10
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'find_result.results[int(item) - 1].stdout == \"\"' failed. The error was: error while evaluating conditional (find_result.results[int(item) - 1].stdout == \"\"): 'int' is undefined\n\nThe error appears to have been in '/home/jamesc/testing/5356.yml': line 10, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  #- debug: msg=\"{{find_result.results[int(item) - 1].stdout}}\"\n  - debug: msg=\"{{find_result.results[item|int() - 1].stdout}}\"\n    ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
</pre>

Based on this, we'll close this issue now. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by hron84** [comment]
It appears again:

```
FAILED! => {"msg": "The conditional check 'item.enabled' failed. The error was: unable to evaluate conditional: item.enabled\n\nThe error appears to have been in '[ REDACTED ]/roles/web.apache/tasks/vhosts.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.
```

The source is:

```yaml
- name: "Enable vhost"
  file:
    src: /etc/apache2/sites-available/{{ item.server_name | replace('.', '-') }}.conf
    dest: /etc/apache2/sites-enabled/{{ item.server_name | replace('.', '-') }}.conf
    owner: root
    group: root
    state: link
  with_items:
    - "{{ apache.vhosts }}"
  when: item.enabled
```
Which really confuses me. For a newcomer Ansible user it seems like `when` does not support looping through conditionals. Which is - according to your docs - is not true. 

```
$ ansible --version 
ansible 2.4.2.0
  config file = /home/hron/Projects/job/itegration/ansible/ansible.cfg
  configured module search path = [u'/home/hron/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

**Comment by satya2art** [comment]
I made it work with a work around, i defined variable in general.yml as
`remote_check_volume_enabled: "{{remote_check_server_volume_enabled}}"`

and in the actual code 

```
  vars:
     remote_enabled: remote_check_volume_enabled
  vars_files:
        - var-files/general.yml
  tags:
    - remote_check_server
  roles:
    - role: msp-base
    - role: msp-ssh-user-management

    - role: msp-beancleaner
      when: beancleaner_enabled == 1

    - role: msp-mount-volumes
      mount_volumes:
        - device: /dev/xvdg
          filesystem_type: ext4
          mount_point: "/tmp"
          mount_options: "noatime,nodiratime"
          dump: 0
          passno: 0
      when: remote_enabled == 1`
```
