### ISSUE TITLE
ec2: use with normal parameters produces warnings

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#53562]
##### SUMMARY
Using normal documented parameters with `ec2` produces warnings

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/notting/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 19:49:22) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Fedora 29

##### STEPS TO REPRODUCE
```
  tasks:
  - name: Launch AWS instances
    ec2:
      group: << some group >>
      keypair: << some keypair >>
      type: << some type >>
      image: << some image >>
      region: << some region >>
      instance_tags: "{ 'Name':'aws-{{project_name}}_{{os_type}}'}"
      exact_count: "{{ ec2_count }}"
      count_tag:
        Name: "aws-{{ project_name }}_{{os_type}}"
      termination_protection: "{{ protect|default(True) }}"
      wait: true
    register: ec2_results
    when: ec2_count|default('0')|int > 0
```
ansible-playbook ... -e project_name=blorp -e os_type=rhel7 -e ec2_count=2

##### EXPECTED RESULTS

no warnings

##### ACTUAL RESULTS

```
 [WARNING]: The value 600 (type int) in a string field was converted to u'600' (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.

 [WARNING]: The value {'Name': 'aws-blorp_rhel7'} (type dict) in a string field was converted to u"{'Name': 'aws-blorp_rhel8'}" (type
string). If this does not look like what you expect, quote the entire value to ensure it does not change.

 [WARNING]: The value 300 (type int) in a string field was converted to u'300' (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
```

The ` {'Name': 'aws-blorp_rhel7'} (type dict) in a string field ` is for the `count_tag` parameter, which is being passed in the manner described in the docs at https://docs.ansible.com/ansible/devel/modules/ec2_module.html.

I have no idea where "300" and "600" are from... they're not in the playbook.
