### ISSUE TITLE
meraki_mr_l3_firewall - Integration test shouldn't rely on net_id for network deletion

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#53600]
##### SUMMARY
The `meraki_mr_l3_firewall` has a cleanup step at the end that is
```
  always:
  - name: Delete wireless network
    meraki_ssid:
      auth_key: '{{ auth_key }}'
      state: absent
      org_name: '{{test_org_name}}'
      net_id: '{{net}}'
      number: 1
    delegate_to: localhost
```

This should define `net_name` because if the network creation fails, the deletion will fail. Also, this should be `meraki_network` and not `meraki_ssid`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Meraki_mr_l3_firewall

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
