### ISSUE TITLE
lineinfile module not parsing \n\t correctly

### ISSUE THREAD

**Issue by jsalatiel** [ansible/ansible#53602]
##### SUMMARY

lineinfile module not parsing \n\t correctly

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/salatiel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]


```

##### OS / ENVIRONMENT

Linux Mint 19.1

##### STEPS TO REPRODUCE

```
---
  - hosts: localhost
    become: true
    tasks:
      - lineinfile:
          path: /etc/ssh/sshd_config
          state: present
          line: "{{ item }}"
        with_items:
          - "Match Address 10.10.0.0/16\n\tPasswordAuthentication yes"
          - "Match Address 10.11.12.0/24\n\tPasswordAuthentication yes"
          - "Match User root\n\tLogLevel VERBOSE"


```

##### EXPECTED RESULTS

Running this playbook more than once should not create duplicates of those lines

##### ACTUAL RESULTS
Each run add 3 more lines to the file

![image](https://user-images.githubusercontent.com/5522389/54079767-7de82d00-42c1-11e9-8dd6-d13adf873e11.png)
