### ISSUE TITLE
Make ec2_instance able to create new instance or fail if instance matching filter already found

### ISSUE THREAD

**Issue by Elias481** [ansible/ansible#53610]
##### SUMMARY
It would be fine if the filter in ec2_instance could be used to create new instance if no instance found matching filter criteria and fail otherwise without touching an already running instance.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_instance

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_instance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_instance.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shaps @ryansb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Elias481, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shaps** [comment]
@Elias481, thanks for submitting this, I don't think this should be included in the module itself, the module ( and ansible in general ) is to ensure you have the resource/s in the desired state; That said, if this is a feature you need, you can already achieve it by using `ec2_instance_facts/failed_when`:
```yaml
- name: Fail if instance already exist
  ec2_instance_facts:
    [...]
    filters:
      <your_filters>
  register: instance_exists
  failed_when: instance_exists.instances | length > 0
```
