### ISSUE TITLE
vmware_guest doesn't start virtual machine with force: yes

### ISSUE THREAD

**Issue by L1ghtman2k** [ansible/ansible#53618]
##### SUMMARY
When trying to clone pfsense using vmware_guest, the machine fails to poweron even with force function

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
Ansible 2.7.7 
AWX 3.0.1.0 
```

##### STEPS TO REPRODUCE

```
    - name:  Clone Pfsense form the template, and assign interfaces
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        force: yes
        state: poweredon
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        folder:  folder
        template: "pfsense_template"
        name: pfsense
        cluster: "{{ cluster }}"
        networks:
          - name: net1
          - name: net2
          - name: net3
      delegate_to: localhost
```

##### EXPECTED RESULTS
pfsense is deployed from a template and is in powered on state

##### ACTUAL RESULTS
pfsense is deployed, however, fails to poweron
```
{
    "_ansible_parsed": true,
    "_ansible_item_result": true,
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "changed": false,
    "item": "1",
    "invocation": {
        "module_args": {
            "resource_pool": null,
            "force": true,
            "customization_spec": null,
            "hardware": {},
            "cluster": "MAIN",
            "customization": {},
            "datastore": "THE-VAULT",
            "disk": [],
            "port": 443,
            "wait_for_ip_address": false,
            "uuid": null,
            "customvalues": [],
            "hostname": "cdr-vcenter1.cse.buffalo.edu",
            "is_template": false,
            "networks": [
                {
                    "type": "dhcp",
                    "name": "team1-net"
                },
                {
                    "type": "dhcp",
                    "name": "team1-net"
                },
                {
                    "type": "dhcp",
                    "name": "team1-net"
                }
            ],
            "state": "poweredon",
            "template": "pfsense_template",
            "linked_clone": false,
            "folder": "Lockdown/v6/Team01",
            "username": $username",
            "snapshot_src": null,
            "guest_id": null,
            "name_match": "first",
            "cdrom": {},
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "annotation": null,
            "datacenter": "Datacenter",
            "state_change_timeout": 0,
            "name": "Team01_Router",
            "vapp_properties": [],
            "esxi_hostname": null,
            "validate_certs": false
        }
    },
    "msg": "Failed to create a virtual machine : Customization of the guest operating system 'freebsd64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.",
    "_ansible_ignore_errors": true,
    "_ansible_item_label": "1"
}
```

wordaround:

```
    - name:  Clone Pfsense form the template, and assign interfaces
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        force: yes
        state: poweredon
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        folder:  folder
        template: "pfsense_template"
        name: pfsense
        cluster: "{{ cluster }}"
        networks:
          - name: net1
          - name: net2
          - name: net3
      delegate_to: localhost
      ignore_errors: yes
 
    - name: Set the state of a virtual machine to poweron
      vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: folder
        name: pfsense
        state: powered-on
        force: yes
      delegate_to: localhost

```
