### ISSUE TITLE
"check_mode", ovirt_disk and a new disk throws "HTTP response code is 404"

### ISSUE THREAD

**Issue by thordreier** [ansible/ansible#53619]
##### SUMMARY
check_mode does not work with ovirt_disk module when disk doesn't already exist.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ovirt_disk

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /home/td/ansible/ansible.cfg
  configured module search path = [u'/home/td/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/xx/ansible/ansible.cfg) = [u'/home/xx/ansible/hosts']
```

##### STEPS TO REPRODUCE

```
- hosts: engine.hosting.local
  tasks:
  - ovirt_auth:
      url: https://xxxxxx/ovirt-engine/api
      username: admin@internal
      password: xxxxxx
      insecure: true
  - name: check_mode works with existing disk
    check_mode: yes
    ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: existing-disk1
      size: 1GiB
      storage_domain: VMstore
  - name: check_mode does not work with new disk
    check_mode: yes
    ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: new-disk1
      size: 1GiB
      storage_domain: VMstore
```

##### EXPECTED RESULTS

Expect to not see "HTTP response code is 404" when running ovirt_disk with "check_mode" on nonexisting disks.

Some of the problem is that 'id' has a null value when running this (around line 692 in ovirt_disk.py):
disks_service.disk_service(module.params['id']).get()

Maybe there should be some "if not self._module.check_mode" checks around in the module - or check if 'id' has a value.

##### ACTUAL RESULTS

```
PLAY [xxxxxxx] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [xxxxxxx]

TASK [ovirt_auth] **************************************************************
ok: [xxxxxxx]

TASK [check_mode works with existing disk] *************************************
ok: [xxxxxxx]

TASK [check_mode does not work with new disk] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotFoundError: HTTP response code is 404.
fatal: [xxxxxxx]: FAILED! => {"changed": false, "msg": "HTTP response code is 404."}
        to retry, use: --limit @/home/td/ansible/test.retry

PLAY RECAP *********************************************************************
xxxxxxx       : ok=3    changed=0    unreachable=0    failed=1


The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_disk_payload_FP4s8J/__main__.py", line 636, in main
    disk = disks_service.disk_service(module.params['id']).get()
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 35245, in get
    return self._internal_get(headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 211, in _internal_get
    return future.wait() if wait else future
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 208, in callback
    self._check_fault(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 130, in _check_fault
    body = self._internal_read_body(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 312, in _internal_read_body
    self._raise_error(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
NotFoundError: HTTP response code is 404.

fatal: [xxxxxxx]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth": {
                "ca_file": null,
                "compress": true,
                "headers": null,
                "insecure": true,
                "kerberos": false,
                "timeout": 0,
                "token": "9OKJV9TH83wqW26XTL40jcGkOGivxam2csCJoT0PxGkBmn8_UVNHrW0263oaVHtYROhW5vOwr1PdHXIdOxRrMA",
                "url": "https://xxxxxxx/ovirt-engine/api"
            },
            "bootable": null,
            "description": null,
            "download_image_path": null,
            "fetch_nested": false,
            "force": false,
            "format": "cow",
            "id": null,
            "image_provider": null,
            "interface": null,
            "logical_unit": null,
            "name": "new-disk1",
            "nested_attributes": [],
            "openstack_volume_type": null,
            "poll_interval": 3,
            "profile": null,
            "quota_id": null,
            "shareable": null,
            "size": "1GiB",
            "sparse": null,
            "sparsify": null,
            "state": "present",
            "storage_domain": "VMstore",
            "storage_domains": null,
            "timeout": 180,
            "upload_image_path": null,
            "vm_id": null,
            "vm_name": null,
            "wait": true
        }
    },
    "msg": "HTTP response code is 404."
}
```
