### ISSUE TITLE
VMware: vmware_guest_custom_attribute_defs removes custom host attributes with state: absent

### ISSUE THREAD

**Issue by fbecker** [ansible/ansible#53630]
##### SUMMARY

The module vmware_guest_custom_attribute_defs does not check for the type of the custom attribute to remove. It just checks if any custom attribute with the specified name exists and removes it. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_custom_attribute_defs

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### OS / ENVIRONMENT

vSphere 6.5

##### STEPS TO REPRODUCE

Create a custom host attribute ("foo") using vSphere Client / pyVmomi / PowerCLI or any other supported method and run the following task:

```yaml
- vmware_guest_custom_attribute:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    attribute_key: foo
    state: absent

```

##### EXPECTED RESULTS

The custom host attribute should not be removed.

##### ACTUAL RESULTS

The custom host attribute gets removed.
