### ISSUE TITLE
RFE: A more compact way to do groupings of groups

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#53647]
##### SUMMARY
I want to nest AWS availability zones under regions

I have some syntax that works for this, but it scales with `O(N)`, where N is the number of regions, and it is very hacky.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
aws_ec2 inventory plugin

##### ADDITIONAL INFORMATION
The structure I seek to replicate:

```json
"us-east-1": {
    "children": [
        "us-east-1a", 
        "us-east-1b", 
        "us-east-1c", 
        "us-east-1d", 
        "us-east-1e", 
        "us-east-1f"
    ], 
```

(this is just a snippet from the `ansible-inventory` output from this scenario)

This syntax will reproduce this with the aws_ec2 inventory plugin:

```yaml
plugin: aws_ec2
strict: false
keyed_groups:
  - prefix: ""
    separator: ""
    key: placement.region
    parent_group: regions
  - key: "{'us-east-2': placement['availability_zone']}[placement['region']]"
    separator: ""
    parent_group: us-east-2
```

...repeat for all entries in

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html

Because I have something that works (even if ugly), this issue isn't urgent for me, but I think it's pretty clear that a better means of sub-grouping would be a general improvement.

Also note that my syntax will not capture empty availability zones in a region (`ec2.py` did, but would not add empty regions...). I don't expect that can be resolved, I just need to fully disclose the details of what I'm sharing.

Example with current syntax and using the legacy options:

```
    "us-east-2": {
        "children": [
            "us-east-2a", 
            "us-east-2b", 
            "us-east-2c"
        ], 
```

**Comment by AlanCoding** [comment]
Ping @s-hertel, who has been directly working with compatibility content. Link https://github.com/ansible/ansible/issues/53647

**Comment by AlanCoding** [comment]
Spitballing...

```yaml
keyed_groups:
  - key: "placement['region']"
    separator: ""
    parent_group: {{ region }}
```

That format could maybe work if the `parent_group` added some sort of templating functionality. Right now the parent group just takes a static string to be the name of the parent group. This implementation would still differ from the `key` entry, because you don't put the `{{ }}` in that case. Anyway, that's getting very far out of my expertise.

**Comment by s-hertel** [comment]
@AlanCoding I made a possible solution here https://github.com/ansible/ansible/pull/53649. I'm a little unsure of the right way to do it to keep literal strings working along with variables, so it probably needs some tweaking, like only ignoring specific exceptions.

**Comment by AlanCoding** [comment]
> I'm a little unsure of the right way to do it to keep literal strings working along with variables

That's why I hesitated making an attempt on my own.

I am already making use of the `parent_group` key to create groups like "tags" and "zones". I don't see how I would continue to make those after that change (if I read correctly, I have not yet tested).

Example:

```yaml
keyed_groups:
  - prefix: ""
    separator: ""
    key: placement.availability_zone
    parent_group: zones
  - prefix: platform
    key: platform | default('undefined')
    parent_group: platforms
  - prefix: vpc_id  # redundant naming
    key: vpc_id
    parent_group: vpcs
```

The `parent_group` feature has still not be released, so it's fine to break the above use case if some other way to do the same thing is introduced. I can change the syntax for those above groupings if we can introduce some new syntax for static naming. Could I somehow do `parent_group: '"vpcs"'`?

**Comment by AlanCoding** [comment]
Also, I should note that zones are a very special case. A single zone, for instance, `us-east-2a` has 2 direct parents. One parent is literally `zones`, and the other parent is `us-east-2`. Then the group `us-east-2` has a parent of `regions`. In this way, `regions` is a grandparent group of `us-east-2a`.

To do these 2 forms of groupings, we can have 2 entries in keyed_groups related to zones. Nothing wrong with that.

**Comment by bcoca** [comment]
quoting won't help, the reason we require explicit {{ }} in most cases is to disambiguate strings from variables, otherwise you might get a misspelled variable as a string (since its undefined it MUST/might? be a  string).

**Comment by AlanCoding** [comment]
Oh, so then is the expectation that

```yaml
keyed_groups:
  - prefix: ""
    separator: ""
    key: placement.availability_zone
    parent_group: zones
```

will continue to work with #53649? If that's the case then I should test it.

Assuming that is the case, the only thing I would worry about is "tags" which is both the name of a root group and the name of a key in hostvars. I would need some sort of solution for that oddball case.
