### ISSUE TITLE
VMware: Add better examples for vmware_deploy_ovf / properties key/values

### ISSUE THREAD

**Issue by 5t4rdu5t** [ansible/ansible#53650]
##### SUMMARY
No error, but no VM created

##### ISSUE TYPE
- feature request

##### COMPONENT NAME
vmware_deploy_ovf

##### ANSIBLE VERSION

```
ansible 2.7.8
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT

debian9

##### STEPS TO REPRODUCE

Run the playbook 

```
- hosts: localhost
  tasks:
  - name: Create a virtual machine "{{ vm_name }}"
    vmware_deploy_ovf:
      validate_certs: no
      hostname: '{{ vcenter }}'
      datacenter: '{{ datacenter }}'
      username: '{{ login }}'
      password: 'xxx'
      ovf: /path/to/vm.ovf
      name: 'vm-foobar'
      properties:
        capacity: "15" # I expect to set disk size to 15
      disk_provisioning: eagerZeroedThick
      networks: {}
      cluster: cluster1
      datastore: DS1
      folder: /path/to/folder
      power_on: yes

```

##### EXPECTED RESULTS

I expect to set the disksize, the doc said to put key/values from the ovf : I have: 

     <Disk ovf:capacity="8" ovf:capacityAllocationUnits="byte * 2^30" ovf:diskId="vmdisk1" ovf:fileRef="file1" ovf:format="http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized"/>

I tested so set `capacity: "15"` in the playbook.

Maybe I need to remove the vmdk with the exported size ?

##### ACTUAL RESULTS

No error, but size is like the vm where I exported the ovf.

Can the modification be made like this or I need to modify/generate a proper new ovf before processing ?

##### COMMENT

I can make a PR for the doc if someone provide me some more in depth properties key values examples ;)

I would like some sample for networking too if possible
