### ISSUE TITLE
ec2_launch_template - 'network-interface' is not a valid taggable resource type for RunInstances

### ISSUE THREAD

**Issue by ac-hibbert** [ansible/ansible#53680]
##### SUMMARY

I am using tags here and it is tagging instance, network-interface and volume. Network-interface seems to be an incompatible tagging type for RunInstances, I get the following error:-

```
[CRITICAL] 2019-03-12T12:47:22.358Z 5b575755-7f86-4304-b50a-342695dd93f8 Error launching instance: An error occurred (InvalidParameterValue) when calling the RunInstances operation: 'network-interface' is not a valid taggable resource type for this operation.
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_launch_template

##### ANSIBLE VERSION

Using this from devel and imported to Library in my role

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MacOS

##### STEPS TO REPRODUCE

```yaml
- name: Default EC2 Launch Template For Team
  ec2_launch_template:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    name: "{{ name }}"
    instance_type: "t3.medium"
    security_groups:
      - "{{ sg }}"
    iam_instance_profile: "{{ instance_profile }}"
    instance_initiated_shutdown_behavior: stop
    tags:
      TeamName: "{{ team }}"
      Environment: "{{ environment }}"
      Region: "{{ aws_region }}"
    state: present
```

##### EXPECTED RESULTS

Able to run instances

##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_launch_template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_launch_template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ryansb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@hibbert, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hibbert** [comment]
Looks like PR https://github.com/ansible/ansible/pull/53432/files may fix

**Comment by wmcbroomd2d** [comment]
@hibbert I'm getting the same error. I looked at the PR @mdaniel made and it adds some logic to not include a tags section for `network-interface` unless a `network_interfaces` is included in the launch template. But this solution doesn't work either.  I've tried adding a `network_interfaces` with a `network_interface_id` and without one and neither way works. I think the issue is that you are not allowed to tag a `network-interface` in a launch template at all. 

This documentation says that network interfaces do not support tagging on creation.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html

And this one says that only instance and volumes are allowed to be tagged through a launch template.
> For Tags, specify tags by providing key and value combinations. You can tag the instance, the volumes, or both. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template

Here is my example `network_interfaces` yaml config:
```
        network_interfaces:
          - network_interface_id: eni-abcde1234567
            device_index: 0
            associate_public_ip_address: True
            groups:
              - sg-1234567
```


So, I think the solution is just to remove the `network-interface` from the `r_type` in the code completely.
