### ISSUE TITLE
ec2_ami_facts does not work properly where the filters/name has spaces

### ISSUE THREAD

**Issue by yanivezrach** [ansible/ansible#53700]
Hi,

When using the module ec2_ami_facts to retrieve the latest AMI ID using "AMI name" in the filters part where the name has _spaces_ it does not find the AMI.

##### ANSIBLE VERSION
ansible 2.7.8

##### OS / ENVIRONMENT
Centos 7
##### STEPS TO REPRODUCE

###Does not work###
```
- name: Get latest AMI ID
  ec2_ami_facts:
    filters: 
     name: "CentOS Linux 7 x86_64 HVM EBS*"
    owners: amazon
    region: "{{ ec2_region_name }}"
  register: ami_list
```
The return error:
"The error was: No last item, sequence was empty"

###Works###
```
- name: Get latest AMI ID
  ec2_ami_facts:
    filters: 
     name: "Windows_Server-2012-R2_RTM-English-64Bit-Base*"
    owners: amazon
    region: "{{ ec2_region_name }}"
  register: ami_list
```
Thanks,
Yaniv

**Comment by ansibot** [comment]
@yanivezrach: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@yanivezrach Thanks for reporting this issue. I think there are no "CentOS" images with owner as "Amazon" 

Could you please try - 

```yaml
- ec2_ami_facts:
    filters:
      name: "CentOS Linux 7 x86_64 HVM EBS*"
      owner-alias: aws-marketplace
``` 
or

```yaml
- ec2_ami_facts:
    owners: aws-marketplace
    filters:
      name: "CentOS Linux 7 x86_64 HVM EBS*"
```

Above PB works for me. Let me know if you have different requirements.

needs_info
