### ISSUE TITLE
Exception message: cursor() got an unexpected keyword argument 'cursorclass'

### ISSUE THREAD

**Issue by vamshi8** [ansible/ansible#53725]
##### SUMMARY

mysql_replication fails with exception

Error:
fatal: [mysql-passive-master]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: cursor() got an unexpected keyword argument 'cursorclass'"}

I have done with all the prerequisites, I have ~/.my.cnf file in place and I still see that exception.
mysql_user succeeds but mysql_replication fails with that exception.

I have also tried giving user and password in the resource did not work either, I suspect issue with python3 vs python2 changes to ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_replication 

##### ANSIBLE VERSION

```
2.7.6

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
centos 7.6

##### STEPS TO REPRODUCE

```


- name: check if slave is already configured
  mysql_replication: mode=getslave login_user=root login_password=xxxxxx
  ignore_errors: true
  register: slave_status
  when: mysql_repl_role == 'passive-master'
  ignore_errors: yes
  tags:
    - mysql_replication

```
