### ISSUE TITLE
Missing is_public param on cs_iso

### ISSUE THREAD

**Issue by dpassante** [ansible/ansible#53738]
##### SUMMARY

While updating the modules doc, I noticed the parameter `ìs_public` was implemented and documented but missing on `argument_spec`.

This results in the inability to register public isos.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cloudstack/cs_iso.py

##### ANSIBLE VERSION

```paste below
2.8.0.dev0 and below.
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- name: Register a public ISO if ISO name does not already exist
  cs_iso:
    name: Debian 7 64-bit
    url: http://mirror.switch.ch/ftp/mirror/debian-cd/current/amd64/iso-cd/debian-7.7.0-amd64-netinst.iso
    os_type: Debian GNU/Linux 7(64-bit)
    is_public: yes
  delegate_to: localhost
```

##### EXPECTED RESULTS

Iso registered as public.

##### ACTUAL RESULTS

```paste below
fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (cs_iso) module: is_public 
```
