### ISSUE TITLE
Support vault in password lookup plugin

### ISSUE THREAD

**Issue by wedi** [ansible/ansible#53746]
##### SUMMARY
It would be cool, if passwords generated with the password lookup plugin could be encrypted with Vault. This would allow for a streamlined distribution process that includes automatic password generation with record keeping (in git).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
password lookup plugin
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py

##### ADDITIONAL INFORMATION

Vault support is, among others, included in the copy module and the [file lookup plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/file.py). The latter using the [dataloader](https://github.com/ansible/ansiblehttps://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/dataloader.py)

My use case: Automatic generation of master users for dovecot proxy nodes. Each proxy needs a password, each backend server needs the hashes.
Right now the passwords are stored in clear text files and cannot get checked into git. Vault support in the plugin would make the password distribution process much smoother.

Thank you for your time and efforts.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/lookup/password.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fhemberger** [comment]
At least have ansible-vault decrypt password lookups automatically.
I ran into the issue while trying to set a password from an encrypted cred file:

```yaml
- rabbitmq_user:
    user: myuser
    password: "{{ lookup('password', inventory_dir + '/mysecret.creds length=32') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
```

Instead of the stored password `$ANSIBLE_VAULT;1.1;AES256…` was used. Took a minute to figure that out … 😱
