### ISSUE TITLE
support openssl_crl much like openssl_certificate

### ISSUE THREAD

**Issue by fawaf** [ansible/ansible#53789]
##### SUMMARY

support openssl_crl much like openssl_certificate

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

new module name: openssl_crl

##### ADDITIONAL INFORMATION

it would be used in very much the same way as the openssl_certificate module just that it would be specific for crl. crl has some attributes that a cert does not have (e.g. lastupdated, nextupdate, etc.)

```yaml
openssl_certificate:
    path: /etc/ssl/example.com.crl
    provider: assertonly
    issuer:
      O: Let's Encrypt
    has_expired: False
    next_update: 39992711
```
