### ISSUE TITLE
na_ontap_interface always report as changed

### ISSUE THREAD

**Issue by delfer** [ansible/ansible#53803]
##### SUMMARY
na_ontap_interface always report as changed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
na_ontap_interface.py

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = None
  configured module search path = ['/Users/alexanderchumakov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.8/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Target OS: Centos 7

##### STEPS TO REPRODUCE
```yaml
---

- hosts: registry
  tasks:
    - name: Install python-setuptools
      yum:
        name:
          - python-setuptools
        state: present
    - easy_install:
        name: pip
        state: present
    - name: Install netapp-lib
      pip:
        name:
          - six
          - netapp-lib
    - name: Create storage SVM
      na_ontap_svm:
        state: present
        name: alpha
        allowed_protocols: nfs
        root_volume: root
        root_volume_aggregate: '{{ netapp_aggregate }}'
        root_volume_security_style: unix
        hostname: '{{ netapp_hostname }}'
        username: '{{ netapp_username }}'
        password: '{{ netapp_password }}'
        https: yes
        validate_certs: no
    - name: Create storage SVM Interface
      na_ontap_interface:
        state: present
        interface_name: data
        home_port: '{{ netapp_port }}'
        home_node: '{{ netapp_node }}'
        role: data
        protocols: nfs
        admin_status: up
        is_auto_revert: true
        address: '{{ netapp_svm_ip }}'
        netmask: 255.255.255.0
        vserver: alpha
        hostname: '{{ netapp_hostname }}'
        username: '{{ netapp_username }}'
        password: '{{ netapp_password }}'
        https: yes
        validate_certs: no
    - name: Enable nfs
      na_ontap_nfs:
        state: present
        service_state: started
        nfsv3: enabled
        vserver: alpha
        hostname: '{{ netapp_hostname }}'
        username: '{{ netapp_username }}'
        password: '{{ netapp_password }}'
        https: yes
        validate_certs: no
    - name: Create Docker registry Volume
      na_ontap_volume:
        state: present
        name: docker_registry
        junction_path: /docker_registry
        is_infinite: False
        aggregate_name: '{{ netapp_aggregate }}'
        size: 10
        size_unit: gb
        vserver: alpha
        hostname: '{{ netapp_hostname }}'
        username: '{{ netapp_username }}'
        password: '{{ netapp_password }}'
        https: yes
        validate_certs: no
    - name: Create ExportPolicyRule
      na_ontap_export_policy_rule:
        state: present
        policy_name: default
        client_match: 0.0.0.0/0
        ro_rule: any
        rw_rule: any
        protocol: any
        super_user_security: any
        allow_suid: true
        vserver: alpha
        hostname: '{{ netapp_hostname }}'
        username: '{{ netapp_username }}'
        password: '{{ netapp_password }}'
        https: yes
        validate_certs: no
```

Apply twice

##### EXPECTED RESULTS
Second apply task `na_ontap_interface` should be unchaged

##### ACTUAL RESULTS
Second apply task `na_ontap_interface` is chaged

```
PLAY [registry] 

TASK [Gathering Facts] 
ok: [stage2]

TASK [Install python-setuptools] 
ok: [stage2]

TASK [easy_install] 
ok: [stage2]

TASK [Install netapp-lib] 
ok: [stage2]

TASK [Create storage SVM] 
ok: [stage2]

TASK [Create storage SVM Interface] 
changed: [stage2]

TASK [Enable nfs] 
ok: [stage2]

TASK [Create Docker registry Volume] 
ok: [stage2]

TASK [Create ExportPolicyRule] 
ok: [stage2]

PLAY RECAP 
stage2                     : ok=9    changed=1    unreachable=0    failed=0   
```
