### ISSUE TITLE
include_vars not loading if variable was reset

### ISSUE THREAD

**Issue by samragu** [ansible/ansible#53817]
##### SUMMARY
include_vars loads the variables from the file just fine. However, if the same variable is reset as shown below to an empty list (or anything else), include_vars is not loading the variables from the file. The behavior is the same irrespective of hash_behaviour setting in ansible.cfg

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_vars

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /home/xxx/ansible/ansible.cfg
  configured module search path = [u'/home/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/xxx/ansible/ansible.cfg) = [u'/home/xxx/ansible/hosts']
```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

run the playbook

```yaml
---

- name: Test
  hosts: all

  tasks:
  - name: reset files variable
    set_fact:
      files: []

  - name: load file list
    include_vars: filelist

  - name: files
    debug: msg="file {{ item }}"
    with_items: "{{ files }}"


Contents of filelist

---

files:
  - one
  - two
  - three

```

##### EXPECTED RESULTS

```
PLAY [Test] ********************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
ok: [localhost]

TASK [reset files variable] ****************************************************************************************************
ok: [localhost]

TASK [load file list] **********************************************************************************************************
ok: [localhost]

TASK [files] *******************************************************************************************************************
ok: [localhost] => (item=one) => {
    "msg": "file one"
}
ok: [localhost] => (item=two) => {
    "msg": "file two"
}
ok: [localhost] => (item=three) => {
    "msg": "file three"
}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
PLAY [Test] ********************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
ok: [localhost]

TASK [reset files variable] ****************************************************************************************************
ok: [localhost]

TASK [load file list] **********************************************************************************************************
ok: [localhost]

TASK [files] *******************************************************************************************************************

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include_vars.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_vars.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @linuxdynasty
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

This is a precedence issue `set_fact` has HIGHER precedence than `include_vars` so the latter can never overwrite the former.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
You can see this by using other lower precedence forms:
```yaml
- name: Test
  hosts: localhost
  gather_facts: false
  vars:
      files: []
  tasks:

  - name: load file list
    include_vars: filelist

  - name: files
    debug: msg="file {{ item }}"
    with_items: "{{ files }}"
```

results in:
```

ok: [localhost] => (item=one) => {
    "msg": "file one"
}
ok: [localhost] => (item=two) => {
    "msg": "file two"
}
ok: [localhost] => (item=three) => {
    "msg": "file three"
}
```
