### ISSUE TITLE
git module does not see the .netrc 

### ISSUE THREAD

**Issue by ivansche** [ansible/ansible#53859]
##### SUMMARY
The git package does not see the .netrc file and freezes when I try to copy a private repository.
If I substitute the git command with a shell script doing the same thing (e.g. "git clone {repo} {dest}"), then everything works just fine. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- become: true
  block:
    - name: copy netrc
      copy:
        src: ~/.netrc
        dest: /home/vagrant
        owner: vagrant
        group: vagrant
        mode: 0644

    - name: Ansible check file exists example.
      stat:
        path: /git/TestRepo
      register: file_details

    - file:
        path: /git
        owner: vagrant
        group: vagrant
        recurse: true
        mode: 0775

    - name: git clone step
      git:
        repo: "https://github.com/Example/TestRepo"
        dest: /git/TestRepo
        clone: true
      when: file_details.stat.exists==false
```

##### EXPECTED RESULTS
a repository cloned to my desired destination

##### ACTUAL RESULTS
the git step is frozen

```paste below

```
