### ISSUE TITLE
Ufw module example does not work because of missing parameter

### ISSUE THREAD

**Issue by Th1990** [ansible/ansible#53854]
##### SUMMARY
Documentation for Ufw module gives this example:

```
- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow
```

Trying to run that task fails with error:
```
TASK [Ufw example] *******************************************************************
fatal: [10.100.105.24]: FAILED! => {
    "changed": false
}

MSG:
For default, direction must be one of "outgoing", "incoming" and "routed".
```

I belive that this is issue with documentation because the module works as expected if I add parameter for direction:
```
- name:  Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow
    direction: outgoing
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Ufw module documentation

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /home/user/example-ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/user/example-ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/user/example-ansible/ansible.cfg) = debug
RETRY_FILES_ENABLED(/home/user/example-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```
