### ISSUE TITLE
win_chocolatey: Failed to list local package when is not installed

### ISSUE THREAD

**Issue by toufoner** [ansible/ansible#53860]
##### SUMMARY

When you try to install a package for a first time, win_chocolatey failed to list local package.
Command return exit code 2

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey 0.10.12

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/touf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Target os: Microsoft Windows Server 2012 R2 Standard with powershell 4.0

##### STEPS TO REPRODUCE

Create a simple task to install a non-existant package on target for example 7zip.
```yaml~
- name: 7zip
  win_chocolatey:
    name: 7zip.install
    state: present
```

##### EXPECTED RESULTS
Package is installed on target.

##### ACTUAL RESULTS
Package is not installed on target.
Ansible Output
```
    "changed": false, 
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output 7zip.install", 
    "msg": "Error checking installation status for the package '7zip.install'", 
    "rc": 2, 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "", 
    "stdout_lines": []
}
```
Powershell output on target:
https://gist.github.com/toufoner/9ddc3283669940a3b97a6129d36f41c0

I also try to do same with chocolatey 0.12.11, and it works.

Thanks

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
This is due to the latest release of Chocolately changing the return codes for the choco list command. We’ve fixed this in devel and it will be included in the next 2.6 and 2.7 release https://github.com/ansible/ansible/pull/53841. In the meantime you can install just chocolately in your task and use the win_choco_feature to disable the enhanced exit codes.

**Comment by jborean93** [comment]
Just for anyone who is unable to upgrade when the next 2.7 release is made. You can use the following tasks to install the latest Chocolatey version and disable the enhanced exit codes that are incompatible with the `win_chocolatey` module.

```
- name: install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: present

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: install notepadplusplus
  win_chocolatey:
    name: notepadplusplus
    state: present
```
