### ISSUE TITLE
win_chocolatey failing to install during checking existing

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#53892]
##### SUMMARY

win_chocolatey fails to install gitversion.portable or git.install.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_ansible module

##### ANSIBLE VERSION

```
ansible 2.7.4
  config file = /Users/gnadaban/.ansible.cfg
  configured module search path = ['/Users/gnadaban/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gnadaban/dev/src/py/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/gnadaban/dev/src/py/ansible/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/gnadaban/.ansible_vault_pass.txt
HOST_KEY_CHECKING(/Users/gnadaban/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Vanilla Windows Server 2019 core install 

##### STEPS TO REPRODUCE

Task:
```yaml
- name: Install apps
  win_chocolatey:
    source: "{{default_choco_source}}"
    name: "{{ item.name }}"
    params: "{{ (item.params | default('')) }}"
    state: latest
  with_items:
    - { name: GitVersion.Portable }
    - { name: git.install }
```

##### EXPECTED RESULTS

Modules should install.

##### ACTUAL RESULTS

Package fails to install.

Output
```
failed: [<host redacted>] (item={'name': 'GitVersion.Portable'}) => {"changed": false, "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output GitVersion.Portable", "item": {"name": "GitVersion.Portable"}, "msg": "Error checking installation status for the package 'GitVersion.Portable'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
