### ISSUE TITLE
apt: package holds are ignored by upgrade

### ISSUE THREAD

**Issue by jvalrog** [ansible/ansible#53918]
##### SUMMARY
After installing a package and marking it with `apt-mark hold pkg=version`, doing an upgrade with the `apt` module the hold is removed and the package is updated to latest version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- apt

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /home/tigre/files/code/ansible/raspberry-cluster/ansible.cfg
  configured module search path = [u'/home/tigre/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/tigre/files/code/ansible/raspberry-cluster/ansible.cfg) = [u'/home/tigre/files/code/ansible/rasp
DEFAULT_PRIVATE_KEY_FILE(/home/tigre/files/code/ansible/raspberry-cluster/ansible.cfg) = /home/tigre/files/code/ansible/
DEFAULT_REMOTE_USER(/home/tigre/files/code/ansible/raspberry-cluster/ansible.cfg) = pi
HOST_KEY_CHECKING(/home/tigre/files/code/ansible/raspberry-cluster/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Raspberry Pi 1 B+ (arm32v6 / armhf)

##### STEPS TO REPRODUCE

```yaml
- name: Install Docker
  apt:
    name: "docker-ce={{ docker_host_vars.version }}"
    install_recommends: no
    autoremove: yes
    force: yes
    state: present

- name: Fix Docker version
  shell: apt-mark hold "docker-ce={{ docker_host_vars.version }}"

- name: Update the system (apt)
  apt:
    upgrade: yes
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
```

##### EXPECTED RESULTS

Upgrade should respect package holds.

```
pi@piworker1:~ $ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:42:54 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:38:25 2019
  OS/Arch:          linux/arm
  Experimental:     false

pi@piworker1:~ $ apt-mark showhold
docker-ce
```

##### ACTUAL RESULTS

```paste below
pi@piworker1:~ $ docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:57:21 2018
 OS/Arch:           linux/arm
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

pi@piworker1:~ $ apt-mark showhold
pi@piworker1:~ $ 

```
