### ISSUE TITLE
vyos_config does not support comment lines

### ISSUE THREAD

**Issue by yun** [ansible/ansible#53920]
##### SUMMARY

vyos_config only accepts `set` and `delete` commands, but vyos also supports `comment` to add comments to the configuration tree. To delete a comment just set an empty comment.

Reference: https://wiki.vyos.net/wiki/Comment_(command)

Currently when you use a comment line the `vyos_config` module will give the error:

    "msg": "line must start with either `set` or `delete`"
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vyos_config

##### ADDITIONAL INFORMATION

This how it would look like when we could use `comment` in the playbooks:

```yaml
- name: Custom Routing Table 100
  connection: network_cli
  vyos_config:
    timeout: 120
    lines:
      - set protocols static table 100 interface-route 0.0.0.0/0 next-hop-interface vtun0
      - comment protocols static table 100 "Routing table for vtun0"
```
Then when dumping the configuration with `show config` it would show the comment:

```
vyos@vyos# show protocols static table
 /* Routing table for vtun0 */
 table 100 {
     interface-route 0.0.0.0/0 {
         next-hop-interface vtun0 {
         }
     }
 }
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/vyos/vyos_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/vyos/vyos_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @qalthos @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@yun, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by NilashishC** [comment]
@yun `vyos_config` module works with the output of `show configuration commands`. Comments are not a part of this output and only appear with `show configuration` in a literal format.

For example, let say I wish to add a comment for the user `test`. The command would be `comment system login user test "This is a test user"`. This command is not a part of `show configuration commands` and only shows up in `show configuration` or `show configuration | grep '/\*'` as `"/* This is a test user */"`, indicating that this is not a config statement per se.

This breaks the idempotency property of `vyos_config` module since there's no proper way for us to detect if a comment is already present or not.

Alternatively, you can use `vyos_command` or `cli_command` modules to achieve this.

```yaml
- name: Add a comment
  cli_command:
    command: "{{ item }}"
  loop:
    - configure
    - comment system login user test "This is a test user"
    - commit
```
```yaml
- name: Add a comment
  vyos_command:
    commands:    
      - configure
      - comment system login user test "This is a test user"
      - commit
```
