### ISSUE TITLE
library scp is required when file_pull is False but does not appear to be installed. It can be installed using `pip install scp.  when run with module nxos_file_copy

### ISSUE THREAD

**Issue by MyTestCode1** [ansible/ansible#53931]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_file_copy

##### ANSIBLE VERSION
```
ansible --version
ansible 2.7.8
```

##### CONFIGURATION:
```
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_SCP_IF_SSH(/ansible.cfg) = True
HOST_KEY_CHECKING(/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/ansible.cfg) = 900
PERSISTENT_CONNECT_TIMEOUT(/ansible.cfg) = 900
```

##### STEPS TO REPRODUCE
SCPClient  is installed on host running module. using pip install scp.

##### OS / ENVIRONMENT
Centos

Target Device:
CICO MDS 9000 

ansible-playbook -i inventory/hosts myplaybook.yml

```
- name: Enable feature scp-server
  nxos_feature:
    feature: scp-server
    state: enabled
    provider: "{{ cli }}"

- name: "copy file from server to device"
  nxos_file_copy:
    local_file: "{{ ssh_key_client_file }}"
    remote_file: "{{ ssh_key_file }}"
    provider: "{{ cli }}"
```
##### ACTUAL RESULTS
Throws error,
library scp is required when file_pull is False but does not appear to be installed. It can be installed using `pip install scp.  when run with module nxos_file_copy .
