### ISSUE TITLE
aws_waf_condition fails when updating a condition 

### ISSUE THREAD

**Issue by bencart** [ansible/ansible#53932]
##### SUMMARY
aws_waf_condition fails for some filter types when updating a condition that already exists.

I have not tested this extensively, I know that some filter types do work okay, but this is reproducible  with the play below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
modules/cloud/amazon/aws_waf_condition.py
module_utils/ec2.py

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Linux 5.0.2-arch1-1-ARCH x86_64

##### STEPS TO REPRODUCE
This happens when updating an aws_waf_condition of type byte that already exists.

```
- name: create waf condition
  aws_waf_condition:
    filters:
    - field_to_match: 'header'
      header: 'authorization'
      position: 'ENDS_WITH'
      target_string: 'sample text'
      transformation: 'url_decode'
    name: 'my-test-condition'
    type: 'byte'

- name: update waf condition
  aws_waf_condition:
    filters:
    - field_to_match: 'header'
      header: 'authorization'
      position: 'ENDS_WITH'
      target_string: 'other text'
      transformation: 'url_decode'
    name: 'my-test-condition'
    type: 'byte'
```

##### EXPECTED RESULTS
Condition should be updated.

##### ACTUAL RESULTS
We have a Python type error when using module_extras/ec2.py => compare_policies to compare the two conditions.

```
Traceback (most recent call last):
  File \"/home/user/.ansible/tmp/ansible-tmp-1552879529.5581675-97499234813119/AnsiballZ_aws_waf_condition.py\", line 113, in <module>
    _ansiballz_main()
  File \"/home/user/.ansible/tmp/ansible-tmp-1552879529.5581675-97499234813119/AnsiballZ_aws_waf_condition.py\", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/user/.ansible/tmp/ansible-tmp-1552879529.5581675-97499234813119/AnsiballZ_aws_waf_condition.py\", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File \"/usr/lib/python3.7/imp.py\", line 234, in load_module
    return load_source(name, filename, file)
  File \"/usr/lib/python3.7/imp.py\", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File \"<frozen importlib._bootstrap>\", line 630, in _exec
  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/__main__.py\", line 659, in <module>
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/__main__.py\", line 649, in main
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/__main__.py\", line 595, in ensure_condition_present
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/__main__.py\", line 574, in find_and_update_condition
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/__main__.py\", line 565, in find_missing
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/ansible_aws_waf_condition_payload.zip/ansible/module_utils/ec2.py\", line 605, in compare_policies
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/ansible_aws_waf_condition_payload.zip/ansible/module_utils/ec2.py\", line 563, in _hashable_policy
  File \"/tmp/ansible_aws_waf_condition_payload_we998wf4/ansible_aws_waf_condition_payload.zip/ansible/module_utils/ec2.py\", line 556, in _hashable_policy
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
