### ISSUE TITLE
ERROR: aws_s3 is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by ghourlier** [ansible/ansible#53949]
##### SUMMARY
I get an error message "ERROR: aws_s3 is not a legal parameter in an Ansible task or handler"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_s3

##### ANSIBLE VERSION
Ansible 2.7.8

##### OS / ENVIRONMENT
ubuntu

##### STEPS TO REPRODUCE

```
- aws_s3:
    bucket: ""
    object: ""
    src: ""
    mode: put
    metadata: "Cache-Control: 'max-age=0, private, no-cache, no-store, must-revalidate'"
  when: ""
```

##### EXPECTED RESULTS

Send my local dev to a bucket s3

##### ACTUAL RESULTS

```
ERROR: aws_s3 is not a legal parameter in an Ansible task or handler
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/aws_s3.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_s3.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@hellsingblack, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
need more context, that works fine when i put it inside a play

needs_info

**Comment by hellsingblack** [comment]
@bcoca I use ubuntu and pyenv 1.2.9
I play my `playbook` with PYENV_VERSION=ansible2.5.5 ansible-playbook deploy_ui.yml -i 127.0.0.1, --extra-vars "project=console env=development"

everything work without aws_s3 implementation but when I add theses line 
```
- aws_s3:
    bucket: "{{ frontend_environments[env].bucket_name }}"
    object: "/release-{{ release_id }}/index.html"
    src: "{{ frontend_build_directory }}/index.html"
    mode: put
    metadata: "Cache-Control='max-age=0, private, no-cache, no-store, must-revalidate'"
  when: frontend_projects[project].build_type == 'yarn'
```

**Comment by bcoca** [comment]
again, not enough context, the task alone works for me, but i'm inserting it into a play:
```yaml
- name: Test
  hosts: localhost
  gather_facts: false
  tasks:
   - aws_s3:
       bucket: "{{ frontend_environments[env].bucket_name }}"
       object: "/release-{{ release_id }}/index.html"
       src: "{{ frontend_build_directory }}/index.html"
       mode: put
       metadata: "Cache-Control='max-age=0, private, no-cache, no-store, must-revalidate'"
     when: frontend_projects[project].build_type == 'yarn'
```

The message you get is normally related to the module not existing or not found, it is present in 2.7.8 so I suspect there is an issue with your use or configuration/setup.

**Comment by hellsingblack** [comment]
Ok @bcoca  I tried to simplified the code and get the same error
I also check in `https://github.com/ansible/ansible/blob/v2.7.8/lib/ansible/modules/cloud/amazon/aws_s3.py` there are reference of `aws_s3` in document not in the code

```
---

- name: Test
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ remote_user }}"
  vars:
    frontend_directory: "/home/{{ remote_user }}/development/frontend_app"
    frontend_build_directory: "{{ frontend_directory }}/{{ frontend_projects[project].build_dir }}"

  tasks: 
    - set_fact: release_id={{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}

    - name: Copy .env
      template: src=.env.j2 dest="{{ frontend_directory }}/{{ frontend_environments[env].environment  }}.env"

    - name: Install dependencies
      command: "yarn install"
      args:
        chdir: "{{ frontend_directory }}"

    - name: Build
      command: "yarn build:{{ frontend_environments[env].environment  }}"
      args:
        chdir: "{{ frontend_directory }}"

    - name: Copy build to S3
      command: "aws s3 cp {{ frontend_build_directory }} s3://{{ frontend_environments[env].bucket_name }}/release-{{ release_id }} --recursive"
      when: frontend_projects[project].build_type == 'yarn'

    - aws_s3:
        bucket: "{{ frontend_environments[env].bucket_name }}"
        object: "/release-{{ release_id }}/index.html"
        src: "{{ frontend_build_directory }}/index.html"
        mode: put
        metadata: "Cache-Control='max-age=0, private, no-cache, no-store, must-revalidate'"
      when: frontend_projects[project].build_type == 'yarn'

    - cloudfront_distribution:
        state: present
        distribution_id: "{{ frontend_environments[env].distribution_id }}"
        default_origin_path: "/release-{{ release_id }}"
      when: frontend_environments[env].cloudfront == true
```

**Comment by hellsingblack** [comment]
@bcoca another version of code 
```
---

- name: test
  hosts: 127.0.0.1
  connection: local
  remote_user: "{{ remote_user }}"
  vars:
    frontend_directory: "/home/{{ remote_user }}/development/frontend_app"
    frontend_build_directory: "{{ frontend_directory }}/{{ frontend_projects[project].build_dir }}"

  tasks: 
    - aws_s3:
        bucket: "{{ frontend_environments[env].bucket_name }}"
        object: "/release-{{ release_id }}/index.html"
        src: "{{ frontend_build_directory }}/index.html"
        mode: put
        metadata: "Cache-Control='max-age=0, private, no-cache, no-store, must-revalidate'"
      when: frontend_projects[project].build_type == 'yarn'
```

this code work with ansible 2.5.5 not with 2.7.8
