### ISSUE TITLE
Do not run CHANGE MASTER query on a running MySQL slave

### ISSUE THREAD

**Issue by rthouvenin** [ansible/ansible#53943]
##### SUMMARY
This is mostly a feature request, but also partly a bug report. When running the `mysql_replication` module with `mode=changemaster` while the slave is already running on the MySQL server, the task fails with error message "error totally whack" and nothing much more than that... This is the bug part: the error message should be improved. When doing this "manually" (that is, running the query), MySQL complains that you cannot do this while the slave is running, which is much clearer.

The feature request part is that it would be nice if the ansible module can detect that the request will not change the master settings, and therefore not try to run the query. I believe this is doable for the master host and user, much less sure for the password.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_replication

##### ADDITIONAL INFORMATION
Here is an example of task that cause such a problem

```yaml
name: MySQL server - Set replication master
mysql_replication:
    mode: changemaster
    master_host: '{{ mysql_vars.replication.master.name }}'
    master_user: '{{ mysql_server.replication.user }}'
    master_password: '{{ mysql_server.replication.password }}'
```

The complete error message:

> fatal: [myservername]: FAILED! => {"changed": false, "msg": "(-1, 'error totally whack'). Query == CHANGE MASTER TO ['MASTER_HOST=%(master_host)s', 'MASTER_USER=%(master_user)s', 'MASTER_PASSWORD=%(master_password)s']"}
