### ISSUE TITLE
Allow custom role metadata

### ISSUE THREAD

**Issue by jpic** [ansible/ansible#53950]
Currently, adding a new attribute to meta/main.yml as such:

```
jpic@ci:~$ cat yourlabs.docker/meta/main.yml
---
galaxy_info:
  author: James Pic
  description: Role to setup docker with pip3 module
  company: YourLabs
  issue_tracker_url: https://yourlabs.io/oss/yourlabs.docker/issues
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: GenericLinux
    versions:
    - all
softdependencies:
- yourlabs.io/oss/yourlabs.pip
- yourlabs.io/oss/yourlabs.roleonce
```

Will fail as such:

```
ERROR! 'softdependencies' is not a valid attribute for a RoleMetadata     
```

To finish this issue, allow users to put custom stuff in meta/main.yml

(EDIT: in my particular use case i could do without, if only ansible did not enforce executing role dependencies, ie. when you want to include a specific tasks file from a role in another role, you want to include_role yourself)
