### ISSUE TITLE
'prompts ' is not a valid attribute for a play

### ISSUE THREAD

**Issue by LucyMarieKiwi** [ansible/ansible#53966]
##### SUMMARY
I using Ansible to attempt to open and close interfaces on a Cisco IOS switch. Due to restrictions with money, I am having to use old kit therefore having to use telnet instead of SSH. I am getting an error for 'prompts ' is not a valid attribute for a play. I got 'prompts' from an Ansible document https://docs.ansible.com/ansible/latest/modules/telnet_module.html 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
root@lucy-VirtualBox:/etc/ansible# ansible --version
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
```
root@lucy-VirtualBox:/etc/ansible# ansible-config dump --only-changed
root@lucy-VirtualBox:/etc/ansible# 
```
##### OS / ENVIRONMENT
Cisco IOS devices

##### STEPS TO REPRODUCE
Checking Syntax of the following playbook
```
---
 - hosts: Switches
   gather_facts: false
   connection: local
   
   tasks:
 - name: DEFINE CONNECTION
   telnet:
    password: "{{ password }}"
    password_prompt: "password: "
   prompts:
     - "[>|#]"
    
 - name: RUN SHOW INTERFACES
   telnet:
     password: "{{ password }}"
     password_prompt: "password: "
   prompts:
     - "[>|#]"
   command:
     - show ip interface brief
```

##### EXPECTED RESULTS
No errors

##### ACTUAL RESULTS
Gets the following error:

````
root@lucy-VirtualBox:/etc/ansible# ansible-playbook switchinterface_open.yml --syntax-check
ERROR! 'prompts' is not a valid attribute for a Play

The error appears to have been in '/etc/ansible/switchinterface_open.yml': line 7, column 4, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   tasks:
 - name: DEFINE CONNECTION
   ^ here

```

**Comment by sivel** [comment]
You appear to have a lot of indentation issues.

You need to make sure that the tasks are properly indented under the `tasks:` header.  Additionally, you need to indent `prompts` and `command` to the same level as `password`.

An example of a properly indented playbook:

```
---
- hosts: Switches
  gather_facts: false
  connection: local
  tasks:
    - name: DEFINE CONNECTION
      telnet:
        password: "{{ password }}"
        password_prompt: "password: "
        prompts:
          - "[>|#]"

    - name: RUN SHOW INTERFACES
      telnet:
        password: "{{ password }}"
        password_prompt: "password: "
        prompts:
          - "[>|#]"
        command:
          - show ip interface brief
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
