### ISSUE TITLE
Deploy google cloud functions with ansible

### ISSUE THREAD

**Issue by jonahh-yeti** [ansible/ansible#53965]
##### SUMMARY

I would like to be able to deploy google cloud functions via ansible.  Other components in google cloud (pubsub, cloud storage, etc.) have been given support via magic-modules.  In order to deploy more of my infrastructure via ansible, it would be helpful if cloud functions were also supported.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

gcp_cloudfunctions

##### ADDITIONAL INFORMATION

Ideally, this module would be able to point at a local directory or zip file containing a cloud function, and deploy the function to a GCP environment.  Something like, 

```yaml
- name: Deploy my cloud function to GCP
  gcloudfuction:
    name: function-1
    memory: 256MB
    trigger: pubsub
    topic: pubsub-topic-1
    source: /path/to/code/code.zip
    runtime: Node-6
    entrypoint: helloPubSub
```
