### ISSUE TITLE
win_chocolotey fails to install curl or googlechrome

### ISSUE THREAD

**Issue by NasAmin** [ansible/ansible#53970]
##### SUMMARY
I am using win_chocolatey but have started getting an error that win_chocolatey cannot install curl and googlechrome. This error happens on all win_chocolatey tasks.

##### ANSIBLE VERSION
2.7.9 and 2.5.5

```

##### COMPONENT NAME
win_chocolatey

##### ISSUE TYPE
win_chocolatey cannot install any packages.

##### CONFIGURATION
- name: Install curl via Chocolatey
  win_chocolatey:
    name: curl
    state: present
        
```

##### OS / ENVIRONMENT
alpine based docker container

##### STEPS TO REPRODUCE
Create a task as metnioned above.
Run Ansible playbook containing the above task 

```yaml
ansible-playbook build-agents.yml -i packer-guest.yml --vault-password-file ./vault_password_file -vvvvv
```

##### EXPECTED RESULTS
Curl and googlechrom are installed successfully.

##### ACTUAL RESULTS

```
    vsphere-iso: TASK [common : Install Curl(7.61.0) via Chocolatey] ****************************
    vsphere-iso: task path: /tmp/packer/playbook/roles/common/tasks/install_curl.yml:1
    vsphere-iso:  [WARNING]: Chocolatey was missing from this system, so it was installed during
    vsphere-iso: fatal: [10.249.198.249]: FAILED! => {
    vsphere-iso:     "changed": true,
    vsphere-iso: this task run.
    vsphere-iso:     "command": "C:\\ProgramData\\Chocolatey\\bin\\choco.exe list --local-only --exact --limit-output curl",
    vsphere-iso:     "msg": "Error checking installation status for the package 'curl'",
    vsphere-iso:     "rc": 2,
    vsphere-iso:     "stderr": "",
    vsphere-iso:     "stderr_lines": [],
    vsphere-iso:     "stdout": "",
    vsphere-iso:     "stdout_lines": []
    vsphere-iso: }
    vsphere-iso:        to retry, use: --limit @/tmp/packer/playbook/build-agents.retry
    vsphere-iso:
    vsphere-iso: PLAY RECAP *********************************************************************
    vsphere-iso: 10.249.198.249             : ok=1    changed=0    unreachable=0    failed=1
```
I am not sure what is causing this issue as this has been working for months.
