### ISSUE TITLE
Ansible URI module bug with user set to null

### ISSUE THREAD

**Issue by tristanbes** [ansible/ansible#53977]
##### SUMMARY
A webservice excepts authentication calls to be in the form
```bash
curl -H "Accept: application/json" -H "Content-Type: application/json" \
 -u ":<your token>" \
 -X POST https://auth.example.com/v1/tokens/exchange
``` 

⚠️ Note the `:<your token>`, there are no user.

When trying to achieve that with Ansible, it keeps failing
```yml
- name: Exchange the token for a Bearer Token
  uri:
    url: https://auth.example.com/v1/tokens/exchange
    body_format: json
    user: null
    password: "{{ api_token }}"
    method: POST
    headers:
      Accept: application/json
    status_code: 200
  register: scalingo_response_bearer_token
```

I tried the following variations: 
- `user: null` 
- `user:`, 
- `user: ''`
- `force_basic_auth: true` 

and all the scenarios failed.

✅ The only working case was `user: foo_random_value`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION

```bash
ansible 2.7.8
  config file = None
  configured module search path = [u'/Users/tbessoussa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Feb 12 2019, 11:00:12) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
no configuration change.

##### OS / ENVIRONMENT
MacOSX 10.14.3

##### STEPS TO REPRODUCE

```yaml
- name: Exchange the token for a Bearer Token
  uri:
    url: https://auth.scalingo.com/v1/tokens/exchange
    body_format: json
    user: ''
    password: "{{ api_token }}"
    method: POST
    headers:
      Accept: application/json
    status_code: 200
  register: scalingo_response_bearer_token
```

##### EXPECTED RESULTS
I except to be auth and retrieve a Baerer. 

##### ACTUAL RESULTS

```bash
fatal: [127.0.0.1]: FAILED! => {
    "cache_control": "no-cache", 
    "changed": false, 
    "connection": "close", 
    "content": "{\"error\":\"unauthorized\"}", 
    "content_type": "application/json; charset=utf-8", 
    "date": "Mon, 18 Mar 2019 17:05:48 GMT", 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "body": null, 
            "body_format": "json", 
            "client_cert": null, 
            "client_key": null, 
            "content": null, 
            "creates": null, 
            "delimiter": null, 
            "dest": null, 
            "directory_mode": null, 
            "follow": false, 
            "follow_redirects": "safe", 
            "force": false, 
            "force_basic_auth": false, 
            "group": null, 
            "headers": {
                "Accept": "application/json", 
                "Content-Type": "application/json"
            }, 
            "http_agent": "ansible-httpget", 
            "method": "POST", 
            "mode": null, 
            "owner": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "regexp": null, 
            "remote_src": null, 
            "removes": null, 
            "return_content": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "status_code": [
                "200"
            ], 
            "timeout": 30, 
            "unsafe_writes": null, 
            "url": "https://auth.example.com/v1/tokens/exchange", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": null, 
            "use_proxy": true, 
            "user": null, 
            "validate_certs": true
        }
    }, 
    "json": {
        "error": "unauthorized"
    }, 
    "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized", 
    "redirected": false, 
    "server": "openresty", 
    "status": 401, 
    "strict_transport_security": "max-age=15552000; includeSubDomains", 
    "transfer_encoding": "chunked", 
    "url": "https://auth.example.com/v1/tokens/exchange", 
    "vary": "Origin", 
    "x_content_type_options": "nosniff", 
    "x_frame_options": "SAMEORIGIN", 
    "x_request_id": "9f166689-6074-44fa-9cf9-6d8207a6de13, 9f166689-6074-44fa-9cf9-6d8207a6de13", 
    "x_runtime": "0.003242", 
    "x_xss_protection": "1; mode=block"
}
```
