### ISSUE TITLE
Add send_string to wait_for module

### ISSUE THREAD

**Issue by heldner** [ansible/ansible#54024]
##### SUMMARY
I want to add the ability to send any string to the socket.

##### ISSUE TYPE
- Feature request

##### COMPONENT NAME
module **wait_for**

##### ADDITIONAL INFORMATION
Useful for checking ssh server. You can send a string with the ssh version and have clear auth.log.

Example:
```yaml
  - name: Wait for SSH
      wait_for:
        host: 'localhost'
        port: 22
        search_regex: OpenSSH
        send_string: 'SSH-2.0-OpenSSH_7.4p1\n'
        delay: 10
```
