### ISSUE TITLE
Make ansible_group_priority affect group branches

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#54038]
##### SUMMARY

`ansible_group_priority` in current form is of limited use. It is impossible to control relative priority of parallel group branches.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

inventory
##### ADDITIONAL INFORMATION

```yaml
# /all/group2
ansible_group_priority: -1
# /all/group1/subgroup1
foo: bar
# /all/group2/subgroup2
foo: baz
```
For host that is a member of both subgroup1 and subgroup2, the current behavior is `foo: baz`. 

Suppose `subgroup*` groups are dynamic via `group_by`, so it is impossible to assign priority beforehand. And `group2` branch is supposed to hold low-level data, like os/distribution/release hierarchy, so the whole branch should be of lower priority than any other neighboring branch relative to /all. If group priority set on `group2` would propagate down the branch, it would be possible to predictably get `foo: bar` on the host.
