### ISSUE TITLE
tower_job_template does not respect role path

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#54046]
##### SUMMARY
I have a file named network.yml in the files/ directory in a role and it does not pick it up,  so I have to do this->```      extra_vars_path: "{{playbook_dir}}/roles/setup_network/files/network.yml"```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_job_template

##### ANSIBLE VERSION
```paste below
ansible 2.7.7
  config file = /Users/sean/.ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION
```paste below
DEFAULT_STDOUT_CALLBACK(/Users/sean/.ansible.cfg) = yaml
```

##### OS / ENVIRONMENT
Mac OS Mojave1 0.14.3 (18D109

##### STEPS TO REPRODUCE

```yaml
    - name: CREATE NETWORK JOB TEMPLATE
      tower_job_template:
        name: "LINKLIGHT TEST RUN NETWORK"
        job_type: "run"
        inventory: "LINKLIGHT_TEST_INVENTORY"
        project: "LINKLIGHT TESTING"
        playbook: "provisioner/provision_lab.yml"
        tower_config_file: "~/tower_cli.cfg"
        extra_vars_path: "{{playbook_dir}}/roles/setup_network/files/network.yml"
      register: network_job

    - name: CREATE TEARDOWN NETWORK JOB TEMPLATE
      tower_job_template:
        name: "LINKLIGHT TEST TEARDOWN NETWORK"
        job_type: "run"
        inventory: "LINKLIGHT_TEST_INVENTORY"
        project: "LINKLIGHT TESTING"
        playbook: "provisioner/teardown_lab.yml"
        tower_config_file: "~/tower_cli.cfg"
        extra_vars_path: "{{playbook_dir}}/roles/setup_network/files/network.yml"
      register: network_teardown_job
```

##### EXPECTED RESULTS
should be able to use this tree structure->
```
setup_network/
..files/network.yml
..tasks/main.yml

##### ACTUAL RESULTS
fails unless I do full path
