### ISSUE TITLE
How could I get the result

### ISSUE THREAD

**Issue by zhangguanzhang** [ansible/ansible#54043]
vars
```yaml
log:
  apiserver:
    dir: /var/log/kubernetes/kube-apiserver
    size: 200M
    rotate: 7
  controllerManager:
    dir: /var/log/kubernetes/kube-controller-manager
    size: 200M
    rotate: 7
  scheduler:
    dir: /var/log/kubernetes/kube-scheduler
    size: 200M
    rotate: 7
  proxy:
    dir: /var/log/kubernetes/kube-proxy
    size: 200M
    rotate: 7
```
the tasks
```
- debug: msg={% if item.key != 'proxy'%}{{item.key}}{% endif %}
  with_dict: "{{ log }}"
```
the playbook's output
```
ok: [localhost] => (item={'value': {u'rotate': 7, u'dir': u'/var/log/kubernetes/kube-apiserver', u'size': u'200M'}, 'key': u'apiserver'}) => {
    "msg": "apiserver"
}
ok: [localhost] => (item={'value': {u'rotate': 7, u'dir': u'/var/log/kubernetes/kube-controller-manager', u'size': u'200M'}, 'key': u'controllerManager'}) => {
    "msg": "controllerManager"
}
ok: [localhost] => (item={'value': {u'rotate': 7, u'dir': u'/var/log/kubernetes/kube-proxy', u'size': u'200M'}, 'key': u'proxy'}) => {
    "msg": ""
}
ok: [localhost] => (item={'value': {u'rotate': 7, u'dir': u'/var/log/kubernetes/kube-scheduler', u'size': u'200M'}, 'key': u'scheduler'}) => {
    "msg": "scheduler"
}
```
I don't want the action of the `msg:""`
