### ISSUE TITLE
set_fact and loop issue still exists

### ISSUE THREAD

**Issue by alexanderccc** [ansible/ansible#54042]
##### SUMMARY
When trying to use set_fact with looping it only sets the last item as a fact.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact

##### ANSIBLE VERSION
```
ansible 2.7.9
  config file = /Users/alexandercristian/Dev/ansible/git/ansible.cfg
  configured module search path = [u'/Users/alexandercristian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alexandercristian/Dev/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/alexandercristian/Dev/ansible/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION
```
ACTION_WARNINGS(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = False
ALLOW_WORLD_READABLE_TMPFILES(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = True
ANSIBLE_FORCE_COLOR(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = True
ANSIBLE_NOCOWS(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = False
DEFAULT_HASH_BEHAVIOUR(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = [u'/etc/ansible/inventories']
HOST_KEY_CHECKING(/Users/alexandercristian/Dev/ansible/git/ansible.cfg) = False
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Set a variable for example:

```yaml
  vars:
    apps:
      - name: httpd
        desired_version: 2.8.38
        custom_package: false
      - name: nginx
        desired_version: 1.16.2
        custom_package: false
```
Then try to change it using set_fact
```yaml
  - name: FactChanger
    set_fact:
      apps:
        - name: "{{ item.name }}"
          desired_version: "{{ item.desired_version }}"
          custom_package: "{{ item.custom_package }}"
    loop: "{{ apps }}"
```

##### EXPECTED RESULTS
```yaml
ok: [test_srv] => {
    "apps": [
        {
            "custom_package": false, 
            "desired_version": "2.8.38", 
            "name": "httpd"
        }, 
        {
            "custom_package": false, 
            "desired_version": "1.16.2", 
            "name": "nginx"
        }
    ]
}
```

##### ACTUAL RESULTS

```yaml
ok: [test_srv] => {
    "apps": [
        {
            "custom_package": false, 
            "desired_version": "1.16.2", 
            "name": "nginx"
        }
    ]
}
```

I also tried the register solution but then the I have issues using the list

playbook

```yaml
  - name: FactChanger
    set_fact:
      apps:
        - name: "{{ item.name }}"
          desired_version: "{{ item.desired_version }}"
          custom_package: "{{ item.custom_package }}"
    when: ("{{ item.name }}" in ansible_facts.packages) and (ansible_facts.packages.{{ item.name }}[0].version != "{{ item.desired_version }}")
    loop: "{{ apps }}"
    register: new_facts

 - name: The Facts
    set_fact:
      apps: "{{ new_facts.results | map(attribute='ansible_facts.apps') | list }}"

```
Created list looks like this
```
ok: [test_srv] => {
    "apps": [
        [
            {
                "custom_package": false, 
                "desired_version": "2.8.38", 
                "name": "httpd"
            }
        ], 
        [
            {
                "custom_package": false, 
                "desired_version": "1.16.2", 
                "name": "nginx"
            }
        ]
    ]
}
```

And later on when trying to use the new facts I get this:

```
fatal: [test_srv]: FAILED! => {"msg": "The conditional check '(\"{{ item.name }}\" in ansible_facts.packages) and (ansible_facts.packages.{{ item.name }}[0].version == \"{{ item.desired_version }}\")' failed. The error was: error while evaluating conditional ((\"{{ item.name }}\" in ansible_facts.packages) and (ansible_facts.packages.{{ item.name }}[0].version == \"{{ item.desired_version }}\")): 'list object' has no attribute 'name'\n\nThe error appears to have been in '/Users/alexandercristian/Dev/ansible/git/playbooks/deployment.yml': line 60, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Check if the packages are the same version and stop\n    ^ here\n"}
```

Purpose of this is to check defined packages against existing packages on the servers and in case they are the same to set new facts containing only the packages that are different than the ones that already exist.
