### ISSUE TITLE
Add TTL as parameter to consul_session

### ISSUE THREAD

**Issue by perzizzle** [ansible/ansible#54054]
##### SUMMARY
Implement ttl parameter in consul_session module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

consul_session

##### ADDITIONAL INFORMATION

I am using consul_kv and consul_session to create consul locks that I use for orchestrating automation. Currently, TTL isn't a supported parameter. I would like to have a lock expire after reaching a TTL. This is supported by the underlying python library, https://python-consul.readthedocs.io/en/latest/#consul-session

```yaml
- name: register a session with ttl
  consul_session:
    name: session_with_ttl
    ttl: 600
```
