### ISSUE TITLE
replace module crashes when encountering Danish characters

### ISSUE THREAD

**Issue by mftovey** [ansible/ansible#54052]
##### SUMMARY
I am working on a playbook to replace the comment field in a server's password file.  I was trying to use the replace module to do this, but it began crashing on one server.  By elimination I was able to isolate the problem to one user's account entry in the password file.  The user is Danish and his name contains the minuscule character (small o with a slash through it, hexadecimal f8).  If I replace that character with the 'o' character, the replace module works fine, but if I put the minuscule character back, it crashes.  Interestingly, the lineinfile module does not have this problem, only the replace module is affected.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
replace
##### ANSIBLE VERSION
```paste below
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mtovey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/dsv/ansible/inventory']

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/
usr/share/ansible/roles']
DEFAULT_SSH_TRANSFER_METHOD(/etc/ansible/ansible.cfg) = scp
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

##### STEPS TO REPRODUCE

/etc/passwd entry:
        bjke:x:2032:900:Bj▒rn Keller:/home/bjke:/bin/bash

```yaml

Any attempt to run the replace module against a passwd file that contains a minuscule character anywhere in the file will fail.  For example:

    replace:
        path: /etc/passwd.tst
        regexp: 'root'
        replace: 'fred'

```

##### EXPECTED RESULTS

changed: [server1]

##### ACTUAL RESULTS

```paste below
fatal: [server1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to server1 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_o_C1bl/ansible_module_replace.py\", line 276, in <module>\r\n    main()\r\n  File \"/tmp/ansible_o_C1bl/ansible_module_replace.py\", line 222, in main\r\n    contents = to_text(f.read(), errors='surrogate_or_strict', encoding=encoding)\r\n  File \"/tmp/ansible_o_C1bl/ansible_modlib.zip/ansible/module_utils/_text.py\", line 235, in to_text\r\n  File \"/usr/lib64/python2.7/encodings/utf_8.py\", line 16, in decode\r\n    return codecs.utf_8_decode(input, errors, True)\r\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 2680: invalid start byte\r\n", "msg": "MODULE FAILURE", "rc": 1}

```

**Comment by sivel** [comment]
See https://github.com/ansible/proposals/issues/121

**Comment by ansibot** [comment]
cc @EvanK
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mftovey** [comment]
That looks like that will take care of the issue.  The company I work for is based in Copenhagen, so latin-1 encoding will likely be a constant issue for us.
    -Mark


--------------------------------------------------------------------------------------------------------------------------
[Description: cid:image001.gif@01D09EC0.4CEB1A90]Mark Tovey - UNIX Engineer
DSV<http://www.dsv.com/> | 110 N Marine Dr. | Bldg 1 | Portland | Oregon | 97217 | USA
MarkTovey@dsv.com<mailto:MarkTovey@dsv.com> | +1 503 222-5546

**Comment by EvanK** [comment]
FWIW, the replace module _does_ currently support an `encoding` parameter. You could try that in the mean time:

```yml
    replace:
        path: /etc/passwd.tst
        regexp: 'root'
        replace: 'fred'
        encoding: 'latin-1'
        # ^ change this out as needed, defaults to utf-8
```
