### ISSUE TITLE
file: mode=2750 != {mode: 2750}

### ISSUE THREAD

**Issue by groks** [ansible/ansible#5409]
Some kind of confusion over octal numbers?

```
- name: this works
  file: path=/tmp/ok state=directory mode=2750

- name: this fails
  file: {path: /tmp/nok, state: directory, mode: 2750}

- name: this also fails
  file:
    path: /tmp/nope
    state: directory
    mode: 2750
```

The permissions look like this:

```
drwxr-s---.    /tmp/ok
d-wSrwxrwT.    /tmp/nok
d-wSrwxrwT.    /tmp/nope
```

Only the first one is correct.
