### ISSUE TITLE
maven_artifact: state=absent not observed

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible#54109]
##### SUMMARY
When using `maven_artifact:` I'd like to use a desired-state variable for the state of the artifact. I.e. when state=absent I expect the artifact to be removed. Using such variables allows me to manage absense or presence of an artifact, such as a library or a service. Quite often I would like to manage a deployment with a bill-of-materials, a manifest of jars, wars, or ears that need to be present, COMBINED with a bill-of-obsolence a manifest of jars, wars and ears that should be removed due to architectural changes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module is maven_artifact

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /home/ONT/meijb05/code/dx-fundament-services/ansible/ansible.cfg
  configured module search path = [u'/home/ONT/meijb05/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/dev/project/ansible/ansible.cfg) = [u'/home/dev/project/ansible
DEFAULT_MANAGED_STR(/home/dev/project/ansible/ansible.cfg) = Ansible managed: {file} modifi
DEFAULT_STDOUT_CALLBACK(/home/project/code/ansible/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/home/dev/project/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.6 (Maipo)

##### STEPS TO REPRODUCE

After I first set `mockserver_state: present` I have a JAR file (with state 'file').

```yaml
- name: Download JAR File to the directory to be launched
  maven_artifact:
    group_id: org.mock-server
    artifact_id: mockserver-netty
    classifier: jar-with-dependencies
    extension: jar
    repository_url: "{{ repository_url }}"
    dest: "{{ mockserver_dir }}"
    mode: 0755
    state: "{{ mockserver_state }}"
```

##### EXPECTED RESULTS

when I set mockserver_state: absent I expected the JAR to be removed.

##### ACTUAL RESULTS

 But when I set mockserver_state: absent the JAR remains.

```paste below

```
