### ISSUE TITLE
win_unzip does not report an error when compressed file is faulty

### ISSUE THREAD

**Issue by gillesB** [ansible/ansible#54113]
##### SUMMARY
When `win_unzip` tries to extract a faulty zip-file, it returns `ok`.
Instead I would have expected `failed` and an error message.

Detailed description: https://serverfault.com/questions/959124/win-unzip-does-not-extract-file/959126#959126

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_unzip

##### ANSIBLE VERSION
```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
`ansible-config dump --only-changed` returns nothing.

##### OS / ENVIRONMENT

Ansible runs on a Ubuntu 18.04.
The target PC is a Windows 7.

##### STEPS TO REPRODUCE

Actually I have not yet tried to reproduce this issue, but it is probably reproducible with any faulty zip file.
Below are the tasks which I am using.
During the download of the zip-file I killed Ansible, which probably resulted in a faulty zip file.
Due to the `force: no`, the file was not replaced by a correct file.

```yaml
  - name: Download Eclipse Luna RCP (32-bit)
    win_get_url:
      url: http://ftp.snt.utwente.nl/pub/software/eclipse//technology/epp/downloads/release/luna/SR2/eclipse-rcp-luna-SR2-win32.zip
      dest: '%TEMP%\eclipse-rcp-luna-SR2-win32.zip'
      force: no
    tags: eclipse
  - name: Ensure Eclipse Luna RCP is extracted
    win_unzip:
      src: '%TEMP%\eclipse-rcp-luna-SR2-win32.zip'
      dest: '%userprofile%\Programs\eclipse_luna'
    tags: eclipse
```

##### EXPECTED RESULTS

In case of the a faulty zip-file I would expect something like (I do not know the result syntax):

```
TASK [Ensure Eclipse Luna RCP is extracted] *********************************************
failed: [192.168.1.87] => {"changed": false,
                                        "dest": "C:\\Users\\testuser\\Programs\\eclipse_luna",
                                         "removed": false,
                                         "src": "C:\\Users\\testuser\\AppData\\Local\\Temp\\eclipse-rcp-luna-SR2-win32.zip",
                                         "msg": "Could not extract the zip file" }
```

##### ACTUAL RESULTS

The folder `C:\Users\testuser\Programs\eclipse_luna` was created but was emtpy.
Ansible reported an `ok`.

```paste below
TASK [Ensure Eclipse Luna RCP is extracted] ************
ok: [192.168.1.87] => {"changed": false,
                       "dest": "C:\\Users\\testuser\\Programs\\eclipse_luna",
                       "removed": false,
                       "src": "C:\\Users\\testuser\\AppData\\Local\\Temp\\eclipse-rcp-luna-SR2-win32.zip"
                      }
```
