### ISSUE TITLE
Support for printing deprecation  warning with ansible-playbook --syntax-check

### ISSUE THREAD

**Issue by jcsmith** [ansible/ansible#54129]
##### SUMMARY
Add support to ansible-playbook --syntax-check to print deprecation warnings.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-playbook

##### ADDITIONAL INFORMATION
It would be great if ansible-playbook --syntax check printed deprecation warnings.  That way it could be used to search an ansible code base for the use od deprecated features.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
@awcrosby Can you verify whether ansible-lint is currently capable of giving this info?

**Comment by jcsmith** [comment]
If it is I cannot sort out how to do it. So I looked forward to seeing the response. 

--
Josh Smith

**Comment by awcrosby** [comment]
@sivel in short no, ansible-lint does not currently work with deprecation warnings, more detail:
1. ansible-lint won’t encounter all deprecation warnings, such as having `ask_sudo_pass = True` in `ansible.cfg`, since it only looks at playbooks, role tasks, role handlers, and role metadata
2. For those deprecation warnings it does encounter, like seeing a deprecated module in a playbook task, those are surfaced to ansible-lint output, but not as a linter issue just printed with exit code 0 (for this ansible-lint uses a rule with a list of deprecated modules to yield a linter issue)

**Comment by jcsmith** [comment]
@awcrosby By your description I would expect ansible-lint to print a warning when executed against the following playbook:

```yaml
---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: testing lint
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - foo
        - bar
        - baz
```
However it does not.  I am currently using anisble-lint version 4.1.0 and ansible version 2.7.9.  

As it relates to my initial issue, I really don't care if the mechanism exists in ansible-playbook or ansible-lint but desire a mechanism to detect the use of deprecated features with out actually executing a playbook.

**Comment by sivel** [comment]
Hrm, that squashing deprecation warning is a runtime warning.  I'm don't think that `--syntax-check` would be capable of supporting that.

**Comment by jcsmith** [comment]
That while concise was probably a poor example because in addition to squashing being deprecated so is the use of `with_items`.  I think both are runtime warnings which I think is the crux of the issue.

**Comment by sivel** [comment]
`with_items` is not deprecated in any form.

The squashing deprecation would happen using `with_items` or `loop`.

**Comment by jcsmith** [comment]
Ok, I see where my confusion came from with regards to with_items being deprecated:

https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#migrating-from-with-x-to-loop

states that `With the release of Ansible 2.5, the recommended way to perform loops is the use the new loop keyword instead of with_X style loops.`  At some point my brain conflated that with deprecation. Sorry for the confusion.

**Comment by jcsmith** [comment]
If we want a different perhaps less ambiguios example to work from:

```yaml
# vim: ft=ansible
---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: testing lint
      yum:
        name: foo
        state: present
      when: bar | failed
```
definitely triggers the deprecated Jinja tests used as filters feature and neither `ansible-playbook --syntax-check` nor `anisble-lint`  have a mechanism to report on the use of such deprecated features.
