### ISSUE TITLE
Creating an Azure Container Instance fails

### ISSUE THREAD

**Issue by asinn826** [ansible/ansible#54139]
##### SUMMARY
Creating an Azure Container Instance fails with the error below

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_containerinstance

##### ANSIBLE VERSION
```paste below
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/alsin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```paste below
[alsin@alfred-sandbox-vm ~]$ ansible-config dump --only-changed
[alsin@alfred-sandbox-vm ~]$
```

##### OS / ENVIRONMENT
RHEL 7.6

##### STEPS TO REPRODUCE
Run a playbook containing the following call to azure_rm_containerinstance

```yaml
    - name: Create Azure Container Instance
      azure_rm_containerinstance:
          resource_group: '{{resource_group_name}}' # required. Name of resource group.
          name: aci-test # required. The name of the container group.
          secret: '{{ secret }}' # not required. Azure client secret. Use when authenticating with a Service Principal.
          subscription_id: '{{ az_subscription }}' # not required. Your Azure subscription Id.
          ip_address: public
          os_type: linux
          ports:
            - 80
            - 81
          containers:
            - image: microsoft/aci-helloworld
              name: mycontainer
          client_id: '{{ client_id }}' # not required. Azure client ID. Use when authenticating with a Service Principal.
          tenant: '{{ tenant_id }}' # not required. Azure tenant ID. Use when authenticating with a Service Principal.
```

##### EXPECTED RESULTS
Resource creation is successful.

##### ACTUAL RESULTS
Error below is returned back.

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'ip_address'fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/alfred/.ansible/tmp/ansible-tmp-1553123532.77-114685133425465/AnsiballZ_azure_rm_containerinstance.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/alfred/.ansible/tmp/ansible-tmp-1553123532.77-114685133425465/AnsiballZ_azure_rm_containerinstance.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/alfred/.ansible/tmp/ansible-tmp-1553123532.77-114685133425465/AnsiballZ_azure_rm_containerinstance.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_containerinstance_payload_Hyz4fy/__main__.py\", line 426, in <module>\n  File \"/tmp/ansible_azure_rm_containerinstance_payload_Hyz4fy/__main__.py\", line 422, in main\n  File \"/tmp/ansible_azure_rm_containerinstance_payload_Hyz4fy/__main__.py\", line 264, in __init__\n  File \"/tmp/ansible_azure_rm_containerinstance_payload_Hyz4fy/ansible_azure_rm_containerinstance_payload.zip/ansible/module_utils/azure_rm_common.py\", line 308, in __init__\n  File \"/tmp/ansible_azure_rm_containerinstance_payload_Hyz4fy/__main__.py\", line 320, in exec_module\nKeyError: 'ip_address'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
When I edit `/usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_containerinstance.py` and comment out line 327 `self.results['ip_address'] = response['ip_address']['ip']`, the module returns successfully. Note that regardless of the error being returned, the my ACI is created sucessfully.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_containerinstance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_containerinstance.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@asinn826, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@zikalino Please help take a look this issue when you're available! I meet same error as above describe. Thanks!

**Comment by yuwzho** [comment]
Hi @asinn826 Thanks for your reporting. I have drafted a PR to fix the ACI issue. You can try the new branch by download the new python files and replace the original ones. 
BTW, the ports should be written with container,  so the playbook can be like this:

```yml
 - name: Create Azure Container Instance
   azure_rm_containerinstance:
          resource_group: '{{resource_group_name}}' 
          name: aci-test 
          secret: '{{ secret }}' 
          subscription_id: '{{ az_subscription }}' 
          ip_address: public
          os_type: linux
          containers:
            - image: microsoft/aci-helloworld
              name: mycontainer
              ports:
               - 80
               - 81
          client_id: '{{ client_id }}'
          tenant: '{{ tenant_id }}'
```
