### ISSUE TITLE
BYPASS_HOST_LOOP and action modules with conditions

### ISSUE THREAD

**Issue by neezgee** [ansible/ansible#5413]
Hello!

When I trying to use group_by with "when" conditions on list of hosts, it often is skipped for all hosts even when debug module runs for part of the host list. With other condition it can work as expected.

I suspect that problem is in Runner. _executor_internal_inner, where it checks conditinons. If first host in list not satisfy to condition, all hosts a skipped. So, I added check for BYPASS_HOST_LOOP in handler - and it resolved the problem in my case.

**Comment by mpdehaan** [comment]
Please stop by ansible-project list for questions such as these, where we can more easily talk about them with the group.

Thanks!

**Comment by mpdehaan** [comment]
Before you hop into code, can you show a playbook example so we can better
understand what you are trying to do?

**Comment by neezgee** [comment]
My english is so bad that you closed issue instantly. :-) Let's add more english.

This is playbook:

```
- hosts: all
  gather_facts: no
  vars:
    condition:
      test1: True
      test2: False
  tasks:

  - name: test action
    local_action: group_by key='test'
    when: condition[inventory_hostname]
```

With this inventory file it works as expected:

```
test1
test2
```

But this inventory makes 'test action' skipped:

```
test2
test1
```

I execute playbook without host limit.
