### ISSUE TITLE
Copy Module - Recursive directory copy does not work locally even with remote_src=yes

### ISSUE THREAD

**Issue by gujiwork** [ansible/ansible#54149]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Copy Module
##### ANSIBLE VERSION

```paste below
< 41  Jenkins - [root]: ~ > # ansible --version
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)
3.10.0-862.9.1.el7.x86_64

##### STEPS TO REPRODUCE

Local Recursive copy of directory does not work even with remote_src=True
From Ansible copy module documentation :
changed": false, "msg": "Remote copy does not support recursive copy of directory:

```yaml
- hosts: k8s-master
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
    - name: sync file data

      copy:
        src: "/opt/config/"
        dest: "/opt/{{ bdate_YYYYMMDD }}"
        remote_src: yes
        directory_mode: yes

```

##### EXPECTED RESULTS

fatal: [192.168.1.16]: FAILED! => {"changed": false, "msg": "Remote copy does not support recursive copy of directory: /opt/zup-config/"}

##### ACTUAL RESULTS

```paste below

```
