### ISSUE TITLE
command module: environment variables are substituted unconditionally

### ISSUE THREAD

**Issue by rfc1459** [ansible/ansible#54162]
##### SUMMARY
Contrary to what is stated in the [module documentation](https://docs.ansible.com/ansible/latest/modules/command_module.html#command-module), all occurrences of environment variables are unconditionally expanded. The expansion also does not take escape characters into account, so `\$HOME` gets expanded to `\actual-home-directory-path`.

This happens because `expand_user_and_vars` is not set to `False` when calling `module.run_command` and there is no way to control this behavior.

##### ISSUE TYPE
- Feature request

##### COMPONENT NAME
command module

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/administrator/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Minimal test case:
```
$ ansible -m command -a 'ls $HOME' localhost
```

##### EXPECTED RESULTS
Command should fail with result `ls: cannot access '$HOME': No such file or directory`

##### ACTUAL RESULTS
https://gist.github.com/rfc1459/0f80f01d0c93e73f27dfdd64f0069b0c

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
consider you are already consuming one quote due to calling ansible in a shell ` ansible -m command -a "'ls $HOME'" localhost`

**Comment by rfc1459** [comment]
Shell quotes with ansible command are a red herring (wrapping in double quotes as you wrote actually makes the shell expand `$HOME`), I reproduced the issue with a minimal playbook as well:
```yaml
---
- hosts: localhost
  tasks:
    - name: Should not expand $HOME
      command:
        /usr/bin/stat $HOME
      register: dont_expand_home
      failed_when: dont_expand_home.rc == 0
```

This still fails: https://gist.github.com/rfc1459/fd6b498ad6e4537fb0fd9f51757b6aa2.

This is caused by `module.run_command()` calling `os.path.expandvars` which expands all environment variables it encounters without taking into account any escape characters or single quotes (basically, the same issue as #52585). Using the shell module and wrapping `$HOME` in single quotes works because `module.run_command()` is called with `unsafe_shell=True`, so the call to `os.path.expandvars` is skipped.

**Comment by rfc1459** [comment]
Actually, looking at the source of `os.path.expandvars` _all_ environment variables are unconditionally expanded, not just `$HOME` and similar vars. I updated the issue title and description accordingly.

**Comment by JacobHenner** [comment]
Reproduced with Ansible 2.5.5

**Comment by fpob** [comment]
Actually variables are expanded even in other modules where no one expect variables expansion. For example

```yaml
- git:
    repo: file:///tmp/$HOME
    dest: /tmp/repo

- user:
    name: test
    comment: $HOME

- unarchive:
    src: /tmp/$HOME
    dest: /tmp

- acl:
    path: $HOME
```

And there is more modules that use `module.run_command()`.

**Comment by bcoca** [comment]
@fpob all file paths will get expanded, that is expected and done on purpose. 

In other cases it depends on being backed by an API or by a CLI tool, which is the case for `user` and `git`

**Comment by fpob** [comment]
@bcoca paths yes, it is expected. Unexpected is env variable expansion.

**Comment by yewwayne** [comment]
Still an issue in 2.9.6. There's no way to pass a literal `$HOME` using command module.

**Comment by bcoca** [comment]
no need to update, while ticket is open the issue is supposed to persist, leaning to this not being a bug, since the substitution is intended in all the cases discussed. 

I have not really seen a use case for the variables not to be expanded, just demonstrations on when they are.

**Comment by rfc1459** [comment]
Yet the [documentation](https://docs.ansible.com/ansible/latest/modules/command_module.html#command-module) says otherwise:

> The command(s) will not be processed through the shell, so variables like $HOME and operations like "<", ">", "|", ";" and "&" will not work. Use the shell module if you need these features.

It all boils down to whether the documentation is correct (then this is definitely a bug) or wrong (then it should be *very* clear that `$HOME` is a special case and will be expanded unconditionally).

By the way, here's the original use case: I need to send a command to a remote host which needs a literal `$HOME` in its arguments, but the command module will expand it unconditionally *before* calling the command, which is neither what I want nor what's written in the module docs.

**Comment by fpob** [comment]
@bcoca OK, let's say variable expansion is expected.

What about using `string.Template(...).safe_substitute(os.environ)` (https://docs.python.org/3/library/string.html#template-strings) instead of `os.path.expandvar(...)`? It should work the same way but it will allow to escape `$`.

---

@rfc1459 If you just want use literal `$HOME` in command you can try set `HOME` to `$HOME` in `environment` on task. Tried it on minimal playbook from your previous comment;

```yaml
- hosts: localhost
  tasks:
    - name: Should not expand $HOME
      command:
        /usr/bin/stat $HOME
      register: dont_expand_home
      failed_when: dont_expand_home.rc == 0
      environment:
        HOME: $HOME
```
