### ISSUE TITLE
[ADD] private key parameter to git module

### ISSUE THREAD

**Issue by gforster** [ansible/ansible#54181]
##### SUMMARY

need the ability for the git module to take a private key as a parameter instead of a file
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git

##### ADDITIONAL INFORMATION

In use cases where in awx/tower a team updating a git repo using the git module which does take a key file as a parameter, but teams do not have access to the backend server and don’t want to manage local files on the tower servers. 

The workaround is rather ugly -  taking a key and vaulting it as a variable, copying the var to a temp file, using that file as the key, and then deleting the temp file. 

This could potentially be solved by a resolution of #19125, which would allow this to be done via extra arguments. 

```yaml
- git:
    repo: ssh://git@github.com/mylogin/hello.git
    dest: /home/mylogin/hello
    key: "{{ some_encrypted_value }}"

```
