### ISSUE TITLE
mysql_variables not supporting variables name with dot (like new mysql 8 validate_password.policy)

### ISSUE THREAD

**Issue by Roxyrob** [ansible/ansible#54239]
##### SUMMARY

mysql_variables return "invalid variable name" trying to manage variable with dot in the name.

##### ISSUE TYPE
- Bug Report
Incorrect variables name characters type allowed

##### COMPONENT NAME

mysql_variables

##### ANSIBLE VERSION

```paste below
ansible 2.7.1
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING = False
DEFAULT_CALLBACK_WHITELIST = [u'profile_tasks']
DEFAULT_HOST_LIST= [u'......../hosts']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug

```

##### OS / ENVIRONMENT

CentOS 7
Linux Kernel 3.10.0-862.3.2.el7.x86_64

##### STEPS TO REPRODUCE

Execute playbook with a task like that below on host with MySQL 8.0  (8.0 uses these new validation policy system variables with dot in the name).

```yaml
- name: Get mysql variable value
  mysql_variables:
    variable: 'validate_password.policy'
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_pwd }}"
```

##### EXPECTED RESULTS

Ansible return value of mysql variable validate_password.policy

##### ACTUAL RESULTS

error "invalid variable name"

```paste below
fatal: [hostname1]: FAILED! => {
    "changed": false
}
MSG:
invalid variable name "validate_password.policy"
```
We found interested lines in the mysq_variables.py module:
```python
154    if match('^[0-9a-z_]+$', mysqlvar) is None:
155        module.fail_json(msg="invalid variable name \"%s\"" % mysqlvar)
```

Adding "dot" to the match regexp seems to fix the bug:
```python
154    if match('^[0-9a-z_.]+$', mysqlvar) is None:
155        module.fail_json(msg="invalid variable name \"%s\"" % mysqlvar)
```

but running mysq_variables to change value:

```yaml
- name: Get mysql variable value
  mysql_variables:
    variable: 'validate_password.policy'
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_pwd }}"
  value: 'LOW'
```

returns

```paste below
fatal: [hostname1]: FAILED! => {
    "changed": false
}
MSG:
MySQL does not support vars with more than 1 dots
```
