### ISSUE TITLE
start_mode: delayed doesn't work for win_service module

### ISSUE THREAD

**Issue by levshanton** [ansible/ansible#54250]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
win_service module
##### ANSIBLE VERSION
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/antonl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
##### CONFIGURATION

```COMMAND_WARNINGS(/etc/repos/devops/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/etc/repos/devops/ansible/ansible.cfg) = [u'/etc/repos/devops/ansible/inventories']
DEFAULT_ROLES_PATH(/etc/repos/devops/ansible/ansible.cfg) = [u'/etc/repos/devops/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/repos/devops/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/etc/repos/devops/ansible/ansible.cfg) = /etc/repos/devops/ansible/ansible-vault.pass
DISPLAY_SKIPPED_HOSTS(/etc/repos/devops/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/repos/devops/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Debian GNU/Linux 9.5 (stretch)
##### STEPS TO REPRODUCE

im using this step in playbooks:
```
  tasks:
    - name: Updating services with configs
      include_role:
        name: update_service
      with_items: "{{ services }}"
      loop_control:
        loop_var: service
      when: services[service].version != "" and config_only!="true"
```

called role:
```
- name: "Installing {{ services[service].name }}"
  win_service:
    path: "{{ services[service].path }}\\{{ services[service].bin }}"
    name: "{{ services[service].name }}"
    display_name: "{{ services[service].name }}"
    username: "{{ services[service].username }}"
    password: "{{ services[service].password }}"
    state: stopped
    start_mode: "delayed"
```

##### EXPECTED RESULTS
services installed with startup_type=delayed
##### ACTUAL RESULTS
services installed with startup_type=automatic
