### ISSUE TITLE
add support for regional persistent disk to gcp_compute_disk

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#54271]
##### SUMMARY
add support for regional persistent disk to gcp_compute_disk as documented here: https://cloud.google.com/compute/docs/disks/regional-persistent-disk
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_compute_disk

##### ADDITIONAL INFORMATION

```yaml
- name: create a disk
  gcp_compute_disk:
      name: "test_object"
      size_gb: 50
      disk_encryption_key:
        raw_key: SGVsbG8gZnJvbSBHb29nbGUgQ2xvdWQgUGxhdGZvcm0=
      region: us-west1
      replica_zones:
        - us-west1-a
        - us-west1-b
      project: "test_project"
      auth_kind: "service_account"
      service_account_file: "/tmp/auth.pem"
      state: present
```
