### ISSUE TITLE
docker_container isn't reliably updating port information

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#54308]
##### SUMMARY
My Docker playbook isn't reliably updating the port and exposed information when I make changes to my playbook.

I initially created my playbook using a `published_ports` parameter of `8010:80/tcp`. This was created properly. This value was removed from the configuration altogether but when I rerun the task, the `changed` value stays `false` and the container is updated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /Users/kbreit/Documents/Programming/home-lab/ansible.cfg
  configured module search path = [u'/Users/kbreit/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kbreit/Documents/Programming/ansible/lib/ansible
  executable location = /Users/kbreit/Documents/Programming/ansible/bin/ansible
  python version = 2.7.14 (default, Feb 25 2018, 14:48:55) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = [u'/Users/kbreit/Documents/Programming/home-lab/inventory/inventory']
DEFAULT_PRIVATE_KEY_FILE(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = /home/kbreit/.ssh/master
DEFAULT_REMOTE_USER(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = kbreit
DEFAULT_ROLES_PATH(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = [u'/Users/kbreit/Documents/Programming/home-lab/roles']
HOST_KEY_CHECKING(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/Users/kbreit/Documents/Programming/home-lab/ansible.cfg) = False

```

##### OS / ENVIRONMENT

macOS 10.13

##### STEPS TO REPRODUCE

```yaml
- name: Create new Vault container
  docker_container:
    name: vault
    state: started
    image: "vault:{{vault_version | default(version)}}"
    restart_policy: unless-stopped
    volumes:
      - vault-config:/vault/config
      - vault-logs:/vault/logs
      - vault-file:/vault/file
    env:
      VIRTUAL_HOST=vault.home.kevinbreit.net
  become: yes
```

##### EXPECTED RESULTS

The container should have been recreated without the 8010 forwarding.

##### ACTUAL RESULTS

```paste below
`66d9401db49d        vault:1.1.0                  "docker-entrypoint.s…"   6 minutes ago       Up 6 minutes        8200/tcp, 0.0.0.0:8010->80/tcp                       vault`
```
