### ISSUE TITLE
vmware_guest doesn't properly distribute load when datastore cluster selected

### ISSUE THREAD

**Issue by L1ghtman2k** [ansible/ansible#54323]
##### SUMMARY
When using playbook to deploy multiple virtual machines, it appears that even though storage cluster has 2 iscsis, named iscsi-2, iscsi-3, all the deployed machines are only deployed to iscsi-3, even though iscsi-2 is empty. 
When doing the same procedure by hand, with datastore cluster selected, VMs go to the datastore that is more empty.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
 _______________ 
<  AWX 3.0.1.0  >
 --------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

Ansible 2.7.7
```

##### CONFIGURATION

```
    - name:  Clone a virtual machine from "{{ name }}" template and customize the addresses to "{{ host }}"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        state: poweredon
        folder:  "{{ hostvars[host]['folder'] }}"
        template: "{{ hostvars[host]['template'] }}"
        name: "{{ 'Team%02d-'|format(hostvars[host]['team_number']) }}{{ name }}"
        cluster: "{{ cluster }}"
        networks: "{{ hostvars[host]['networks'] }}"
        wait_for_ip_address: True
        wait_for_customization: True
        customization: "{{ hostvars[host]['customization'] }}"
      delegate_to: localhost
      loop: "{{ groups[name] }}"
      loop_control:
        loop_var: host
      async: 30000
      poll: 0
```

##### STEPS TO REPRODUCE

```
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: Some_Storage_Cluster
        state: poweredon
        folder:  folder
        template: template
        name: Windows
        cluster: cluster
        networks: 
            - name: network1
            - ip: {{ ip }}
        wait_for_ip_address: True
        wait_for_customization: True
        customization: 
            - hostname: windows
      delegate_to: localhost
      async: 30000
      poll: 0

```

##### EXPECTED RESULTS
Deploy VM to a datastore that is more empty

##### ACTUAL RESULTS
deploys all 30-40 VMS that I have tested to the same, half full datastore
vcenter: 6.7
