### ISSUE TITLE
VMware: vmware_guest does not set "memory_reservation" in combination with "cpu_reservation"

### ISSUE THREAD

**Issue by vMarkusK** [ansible/ansible#54335]
##### SUMMARY

If a Playbook includes Memory and CPU reservation anly the CPU reservation is set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module: vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'vmware_vm_inventory']
```

##### OS / ENVIRONMENT

VMware vSphere 6.7 Update 1

##### STEPS TO REPRODUCE

```yaml
- name: Create a VM from Scratch
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Define Facts
    set_fact:
        vm_name: "test_vm_1001"
        vm_datastore: "SAN_RZ1"
        vm_group: "VM_RZ1"
        network_name: "VM Access"
  - name: Create a VM
    vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        cluster: "{{ cluster_name }}"
        validate_certs: no
        folder: "{{ folder_root }}"
        name: "{{ vm_name }}"
        state: poweredon
        guest_id: centos64Guest
        datastore: "{{ vm_datastore }}"
        disk:
          - size_gb: 10
            #datastore: "{{ vm_datastore }}"
        hardware:
            memory_mb: 512
            memory_reservation: 256
            num_cpus: 1
            cpu_reservation: 256
            scsi: paravirtual
            boot_firmware: efi
        networks:
          - name: "{{ network_name }}"
            device_type: "vmxnet3"
        customvalues:
          - key: "isolation.tools.copy.disable"
            value: "True"
          - key: "isolation.tools.paste.disable"
            value: "True"
          - key: "isolation.tools.diskShrink.disable"
            value: "True"
          - key: "isolation.tools.diskWiper.disable"
            value: "True"
          - key: "mks.enable3d"
            value: "False"
          - key: "tools.setInfo.sizeLimit"
            value: "1048576"
          - key: "RemoteDisplay.vnc.enabled"
            value: "False"
          - key: "tools.guestlib.enableHostInfo"
            value: "False"
        wait_for_ip_address: no
```

##### EXPECTED RESULTS

CPU and Memory reservation should be set. 

##### ACTUAL RESULTS

Anly the CPU Reservation ist set. Playbook exits withount any error.

```paste below
nsible-playbook 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Vault password:
/etc/ansible/hosts did not meet vmware_vm_inventory requirements, check plugin documentation if this is unexpected
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: vmware_create_vm.yml ***********************************************************************************************************************************************
1 plays in /users/s225654/Automation/AnsiblePlayground/vmware_create_vm.yml

PLAY [Create a VM from Scratch] **********************************************************************************************************************************************
META: ran handlers

TASK [Define Facts] **********************************************************************************************************************************************************
task path: /users/s225654/Automation/AnsiblePlayground/vmware_create_vm.yml:5
ok: [localhost] => {
    "ansible_facts": {
        "network_name": "VM Access",
        "vm_datastore": "SAN_RZ1",
        "vm_group": "VM_RZ1",
        "vm_name": "test_vm_1001"
    },
    "changed": false
}

TASK [Create a VM] ***********************************************************************************************************************************************************
task path: /users/<Hidden>/Automation/AnsiblePlayground/vmware_create_vm.yml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166 `" && echo ansible-tmp-1553521455.75-169101385180166="` echo /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-727dh4kvn/tmpbcIXLV TO /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166/AnsiballZ_vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166/ /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1553521455.75-169101385180166/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "0",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "SAN_<Hidden>_um"
        ],
        "hw_esxi_host": "<Hidden>",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": "<Hidden>",
            "macaddress_dash": "<Hidden>",
            "portgroup_key": "dvportgroup-34",
            "portgroup_portkey": "22",
            "summary": "DVSwitch: <Hidden>"
        },
        "hw_files": [
            "[<Hidden>_um] test_vm_1001/test_vm_1001.vmx",
            "[<Hidden>_um] test_vm_1001/test_vm_1001.vmsd",
            "[<Hidden>_um] test_vm_1001/test_vm_1001.nvram",
            "[<Hidden>_um] test_vm_1001/test_vm_1001.vmdk"
        ],
        "hw_folder": "/<Hidden>/vm",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": false,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 512,
        "hw_name": "test_vm_1001",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 1,
        "hw_product_uuid": "<Hidden>",
        "hw_version": "vmx-14",
        "instance_uuid": "<Hidden>",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "<Hidden>",
            "customization": {},
            "customization_spec": null,
            "customvalues": [
                {
                    "key": "isolation.tools.copy.disable",
                    "value": "True"
                },
                {
                    "key": "isolation.tools.paste.disable",
                    "value": "True"
                },
                {
                    "key": "isolation.tools.diskShrink.disable",
                    "value": "True"
                },
                {
                    "key": "isolation.tools.diskWiper.disable",
                    "value": "True"
                },
                {
                    "key": "mks.enable3d",
                    "value": "False"
                },
                {
                    "key": "tools.setInfo.sizeLimit",
                    "value": "1048576"
                },
                {
                    "key": "RemoteDisplay.vnc.enabled",
                    "value": "False"
                },
                {
                    "key": "tools.guestlib.enableHostInfo",
                    "value": "False"
                }
            ],
            "datacenter": "DC-01",
            "datastore": "SAN_RZ1",
            "disk": [
                {
                    "size_gb": 10
                }
            ],
            "esxi_hostname": null,
            "folder": "/<Hidden>/vm",
            "force": false,
            "guest_id": "centos64Guest",
            "hardware": {
                "boot_firmware": "efi",
                "cpu_reservation": 256,
                "memory_mb": 512,
                "memory_reservation": 256,
                "num_cpus": 1,
                "scsi": "paravirtual"
            },
            "hostname": "<Hidden>",
            "is_template": false,
            "linked_clone": false,
            "name": "test_vm_1001",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "name": "VM Access",
                    "type": "dhcp"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": null,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_ip_address": false
        }
    }
}

```

**Comment by mycloudrevolution** [comment]
Note: if `"cpu_reservation": 256` is removed from Playbook, the Memory reservation is set.

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @ckotte @dav1x @lparkes @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mycloudrevolution** [comment]
If the CPU and Memory Reservation of the VM is done in two additional tasks, separated from "VM Create Task", both values are set.

```
  - name: Set VM CPU Reservation
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ cluster_name }}"
      validate_certs: no
      folder: "{{ folder_root }}"
      uuid: '{{ deploy_vm.instance.hw_product_uuid }}'
      hardware:
        cpu_reservation: 256
      wait_for_ip_address: no
  - name: Set VM RAM Reservation
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ cluster_name }}"
      validate_certs: no
      folder: "{{ folder_root }}"
      uuid: '{{ deploy_vm.instance.hw_product_uuid }}'
      hardware:
        memory_reservation: 256
      wait_for_ip_address: no
```

**Comment by ansibot** [comment]
cc @goneri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible/ansible/pull/56161

**Comment by Akasurde** [comment]
@mycloudrevolution Thanks for reporting this issue. Could you please check if https://github.com/ansible/ansible/pull/56161 works for you ? Thanks.

needs_info

**Comment by mycloudrevolution** [comment]
The reported bug seems to be resolved.

The hardware snippet from my playbook:
```
        hardware:
            memory_mb: 256
            memory_reservation: 128
            num_cpus: 1
            cpu_reservation: 128
            scsi: paravirtual
            boot_firmware: efi
```
