### ISSUE TITLE
os_project and os_project_facts censor default domain ID

### ISSUE THREAD

**Issue by megakoresh** [ansible/ansible#54332]
##### SUMMARY

When you query project information if the domain is the default domain, it will show in the output variable as `VALUE_SPECIFIED_IN_NO_LOG_PARAMETER` which obviously will fail when you try to reference it in the next module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_project_facts

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /Users/e102137/.ansible.cfg
  configured module search path = ['/Users/e102137/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/e102137/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ansible
  executable location = /Users/e102137/.pyenv/versions/3.6.4/bin/ansible
  python version = 3.6.4 (default, Feb  5 2018, 13:51:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT

MacOS Mojave

##### STEPS TO REPRODUCE

```yaml
- hosts: os_sites
  become: false
  serial: 1
  connection: local
  gather_facts: false
  tasks:
    - name: create project
      register: created_project
      os_project:
        interface: public
        state: present
        name: '{{project_name}}'
        description: '{{project_description}}'
        domain: default
        enabled: true
        auth:
          auth_url: '{{auth_url}}'
          username: '{{auth_username}}'
          password: "{{lookup('hashi_vault', 'secret=kv/data/infra-automation/ansible/{{site_name}}/service_account_password:data')['password']}}"
          project_name: service
          project_domain_id: default
          user_domain_id: default

    - debug:
        var: created_project

    - name: add user(s)
      loop: '{{project_users}}'
      os_user_role:
        user: '{{item}}'
        role: _member_
        project: '{{created_project.project.id}}'
        domain: '{{created_project.project.domain_id}}'
        state: present
        auth:
          auth_url: '{{auth_url}}'
          username: '{{auth_username}}'
          password: "{{lookup('hashi_vault', 'secret=kv/data/infra-automation/ansible/{{site_name}}/service_account_password:data')['password']}}"
          project_name: service
          project_domain_id: default
          user_domain_id: default

```

##### EXPECTED RESULTS

Project created and users added

##### ACTUAL RESULTS

With inventory

```
[sdc_sites]
site1 auth_url=https://site1.local:13000/v3/ auth_username=service_user    site_name=site1 ansible_python_interpreter="/usr/bin/env python"
```

```paste below
ansible-playbook -i hosts os-create-project.yml -e sdc_project_name=project1 -e sdc_project_description="Test" -e sdc_project_users='["peruna"]'

PLAY [os_sites] *********************************************************************************************************************************************

TASK [create project] ****************************************************************************************************************************************
changed: [site1]

TASK [debug] *************************************************************************************************************************************************
ok: [site1] => {
    "created_project": {
        "changed": true,
        "failed": false,
        "project": {
            "description": "Testi",
            "domain_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "enabled": true,
            "id": "77e5e9b4a8334616b2778408dc16a7bc",
            "is_domain": false,
            "is_enabled": true,
            "location": {
                "cloud": "envvars",
                "project": {
                    "domain_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "domain_name": null,
                    "id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "name": null
                },
                "region_name": null,
                "zone": null
            },
            "name": "project1",
            "parent_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "properties": {
                "tags": []
            },
            "tags": []
        }
    }
}

TASK [add user(s)] *******************************************************************************************************************************************
failed: [site1] (item=peruna) => {
    "changed": false,
    "item": "peruna"
}

MSG:

Failed to get domain VALUE_SPECIFIED_IN_NO_LOG_PARAMETER: Client Error for url: ********domains/VALUE_SPECIFIED_IN_NO_LOG_PARAMETER, Could not find domain: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER.


PLAY RECAP ***************************************************************************************************************************************************
helpa                      : ok=2    changed=1    unreachable=0    failed=1
```

When domain is not `default`, it works as expected and domain_id is shown (not really but thats another issue).
