### ISSUE TITLE
allow specifying of node-version to gcp_container_node_pool

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#54345]
##### SUMMARY
Currently using the Ansible module you are unable to specify the node-version for creation this means there's some functionality gap between `gcloud container node-pools create` and the gcp_container_node_pool module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

gcp_container_node_pool

##### ADDITIONAL INFORMATION

I'd use it to create a node pool with a specific version as permitted by GCP.

```yaml
- name: create a node pool
  gcp_container_node_pool:
      name: "test_object"
      initial_node_count: 4
      cluster: "{{ cluster }}"
      zone: us-central1-a
      project: "test_project"
      auth_kind: "service_account"
      service_account_file: "/tmp/auth.pem"
      node_version: 1.12.5-gke.5
      state: present

```
