### ISSUE TITLE
win_acl doesn't work with registry keys

### ISSUE THREAD

**Issue by mhunsber** [ansible/ansible#54357]
##### SUMMARY

Since the module uses the `LiteralPath` argument for getting and setting the ACL, it does not work for registry keys. This is due to a weird behavior in PowerShell's `Get-Acl` and `Set-Acl` cmdlets where you have to be in the drive of the registry key for `LiteralPath` to work.

In earlier versions of powershell, e.g. PSv2, `LiteralPath` doesn't exist for `Get-Acl` and `Set-Acl`
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_acl

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/ansible/lib/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows Server 2012 R2
Windows 10

##### STEPS TO REPRODUCE

try to use win_acl on a registry key

```yaml
---

- hosts: windows
  tasks:
    - name: 'Administrators have full control on HKCU:\Environment'
      win_acl:
        path: 'HKCU:\Environment'
        user: Administrators
        type: allow
        rights: FullControl
        inherit: ContainerInherit,ObjectInherit
        propagation: None
        state: present
```

##### EXPECTED RESULTS

expected to get "ok" or "changed"

##### ACTUAL RESULTS

```paste below
Using module file /home/admin/ansible/lib/ansible/modules/windows/win_acl.ps1
Pipelining is enabled.
<192.168.101.103> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.101.103
EXEC (via pipeline wrapper)
fatal: [testhost]: FAILED! => {
    "changed": false,
    "msg": "an error occurred when attempting to present FullControl permission(s) on HKCU:\\Environment for Administrators - Cannot find path 'HKEY_CURRENT_USER\\Environment' because it does not exist."
}

PLAY RECAP *******************************************************************************************************************************************************
testhost            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
