### ISSUE TITLE
Changes to gcp_container_cluster and gcp_container_node_pool resources are not applied 

### ISSUE THREAD

**Issue by guhcampos** [ansible/ansible#54373]
##### SUMMARY

These modules work correctly when used for the first time, but if any changes are made to the resources in the roles/playbooks, those are never applied to said resources in practice. Every single subsequent run simply returns "OK" if the resource with the same name exists, regardless of any changes.

This may not be restricted to these two modules, but those are the ones I've verified this to be a problem.

The issue has been brought up in the Magic Modules issue tracker before, but it seems it's been closed without a solution: https://github.com/GoogleCloudPlatform/magic-modules/issues/394 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_container_cluster
gcp_container_node_pool

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = /home/gustavo/workspace/datalive/devops/ansible/ansible.cfg
  configured module search path = ['/home/gustavo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gustavo/.local/lib/python3.6/site-packages/ansible
  executable location = /home/gustavo/.local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]

```

##### STEPS TO REPRODUCE
Create any cluster or pool with an arbitrary config:
```yaml
- name: create a cluster
  gcp_container_cluster:
      name: "cluster-nodepool"
      initial_node_count: 4
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
      addons_config:
        horizontal_pod_scaling:
          disabled: true
```
Make a significant change to the playbook
```yaml
- name: create a cluster
  gcp_container_cluster:
      name: "cluster-nodepool"
      initial_node_count: 4
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
      addons_config:
        horizontal_pod_scaling: 
          disabled: false
```

##### EXPECTED RESULTS

The `horizontal_pod_autoscaling` configuration should be toggled in the cluster, and a [CHANGED] status should be reported by Ansible

##### ACTUAL RESULTS
No changes to the resource are ever made, and Ansible just returns [OK] for the task
