### ISSUE TITLE
XML Module doesn't accept commas in XML provided

### ISSUE THREAD

**Issue by erdebee** [ansible/ansible#54387]
##### SUMMARY
XML Module doesn't allow comma's in XML for set_children and add_children values. 

Escaping in any way doesn't seem to help.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg
  configured module search path = [u'/Users/roybrondgeest/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey
DEFAULT_FORKS(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = 10
DEFAULT_GATHER_TIMEOUT(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = 60
DEFAULT_INTERNAL_POLL_INTERVAL(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = 0.01
HOST_KEY_CHECKING(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/Users/roybrondgeest/Projects/dhl-parcel-platform/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

Running from: OSX 10.14.2 
Target machine: CentOS Linux release 7.6.1810 (Core) 

##### STEPS TO REPRODUCE

```yaml
- name: Reapply securityRealm
  xml:
    file: /data/jenkins/config.xml
    xpath: /hudson/securityRealm
    input_type: xml
    add_children: "<oauthScopes>read:org,user:email</oauthScopes>"
```

##### EXPECTED RESULTS

Should add the XML to the file provided.

##### ACTUAL RESULTS

Found error in log:
 
fatal: [10.5.3.13]: FAILED! => {"changed": false, "msg": "Error while parsing child element: Premature end of data in tag oauthScopes line 1, line 1, column 40"}

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/xml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sm4rk0** [comment]
Hi Roy,

`add_children` accepts a list of children and tries to convert the string you passed to it to a list.

If you run ansible with `-vvv` you'll see:
```JSON
            "add_children": [
                "<oauthScopes>read:org",
                "user:email</oauthScopes>"
            ],
```

This should work (if it does, please close this issue):
```YAML
- name: Reapply securityRealm
  xml:
    file: /data/jenkins/config.xml
    xpath: /hudson/securityRealm
    input_type: xml
    add_children: 
      - <oauthScopes>read:org,user:email</oauthScopes>
```

**Comment by dagwieers** [comment]
Hmm, it's unfortunate that Ansible still turns an (explicit) string into a list. But don't blame Ansible, it doesn't know there are quotes. So the only thing that will work is what @sm4rk0 suggested.

**Comment by dagwieers** [comment]
@rbrondgeest Please report back.

**Comment by rbrondgeest** [comment]
@sm4rk0 @dagwieers in my case i am actually using a variable, like this: 

````
- name: Fetch securityRealm
  command: "xmllint --xpath '/hudson/securityRealm' /data/jenkins/config_old.xml"
  register: securityRealm

- name: Reapply securityRealm
  xml:
    file: /data/jenkins/config_new.xml
    xpath: /hudson
    input_type: xml
    add_children: "{{securityRealm.stdout}}"

```
What syntax would I use to make this work?
Currently the only workaround that I found that works is as follows:
    `add_children: "{{ securityRealm.stdout | replace(',','&#44;') }}"`

**Comment by dagwieers** [comment]
So what @sm4rk0 suggests to use is:
```yaml
- name: Reapply securityRealm
  xml:
    file: /data/jenkins/config_new.xml
    xpath: /hudson
    input_type: xml
    add_children:
    - "{{securityRealm.stdout}}"
```
or even this:
```yaml
- name: Reapply securityRealm
  xml:
    file: /data/jenkins/config_new.xml
    xpath: /hudson
    input_type: xml
    add_children: [ "{{securityRealm.stdout}}" ]
```
Since `add_children` is a list, and since for historical reasons we turn comma-separated strings into lists automagically, you have this issue. But if you provide it a list, no such conversion is happening.
