### ISSUE TITLE
gcp_storage_bucket_access_control not accepting bucket dictionary

### ISSUE THREAD

**Issue by tdixonspin** [ansible/ansible#54386]
Couldn't find an existing issue listed for this module

##### SUMMARY
Using the gcp_storage_bucket_access_control module with the bucket object registered beforehand is returning "Invalid bucket name"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_storage_bucket_access_control 

##### ANSIBLE VERSION
```
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tdixon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
```
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Running ansible on Ubuntu 18.04.2 LTS on WSL with Windows 10 Build 1809. 

##### STEPS TO REPRODUCE
Reproduce by running:

`sudo ansible-playbook -u $(whoami) /mnt/e/Repos/REPO_NAME/playbooks/setup_estate.yml -i /mnt/e/Repos/REPO_NAME/inventory/hosts --key-file ~/.ssh/id_rsa -vvvv`

```
- name: Create Google Cloud Storage Bucket
  gcp_storage_bucket:
    auth_kind: serviceaccount
    location: "{{ gce_project_primary_region }}"
    name: "{{ gce_naming_convention_prefix }}-{{ gce_environment_type }}-cassandra-backups"
    service_account_file: "{{ gce_credentials_file }}"
    state: present
    project: "{{ gce_project_id }}"
    storage_class: NEARLINE
    versioning:
      enabled: yes
  register: bucket_item

- name: Create Bucket ACL
  gcp_storage_bucket_access_control:
    auth_kind: serviceaccount
    bucket: "{{ bucket_item }}"
    entity: "user-{{ cassandra_backup_sa_mail_address }}"
    project: "{{ gce_project_id }}"
    state: present
    role: OWNER
    service_account_file: "{{ gce_credentials_file }}"
```

##### EXPECTED RESULTS
I expect it to create the ACL for the bucket and return the appropriate details

##### ACTUAL RESULTS
The bucket is successfully created, and on subsequent attempts it just confirms it's there, but creating the ACL always fails.

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_gcp_storage_bucket_access_control_payload_rFztZA/ansible_gcp_storage_bucket_access_control_payload.zip/ansible/module_utils/gcp_utils.py", line 187, in raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

*snip* on all the invocation trash

"msg": "GCP returned error: {u'error': {u'code': 400, u'message': u\"Invalid bucket name: '{'kind': 'storage'\", u'errors': [{u'domain': u'global', u'message': u\"Invalid bucket name: '{'kind': 'storage'\", u'reason': u'invalid'}]}}"
```
