### ISSUE TITLE
VMware: Capacity to set configuration based on ESXI Host version

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#54383]
##### SUMMARY

Capacity to specify argument in module,
of what ESXI version to apply configuration too.

This feature can be used for both vmware_host_acceptance and vmware_host_config_manager modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_host_acceptance.py

##### ADDITIONAL INFORMATION

In a scenario where there are different configuration requirements for different ESXi Versions,
and a cluster contains ESXi Hosts of varying versions.

This would solve problems where configurations standards are by ESXi version 

```yaml
- name: Set acceptance level to vmware_accepted for the given ESXi Host
  vmware_host_acceptance:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    esxi_hostname: '{{ esxi_hostname }}'
    esxi_version: 6.5
    state: present
  delegate_to: localhost
  register: host_acceptance_level
```

and

```yaml
- name: Manage Log level setting for all ESXi Host in given Cluster
  vmware_host_config_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster_name: cluster_name
    esxi_version: 6.5
    options:
        'Config.HostAgent.log.level': 'info'
  delegate_to: localhost
```
