### ISSUE TITLE
vmware_host_config_manager: Capacity to set configuration based on ESXI Host version

### ISSUE THREAD

**Issue by blambo10** [ansible/ansible#54384]
##### SUMMARY

Capacity to specify argument in module,
of what ESXI version to apply configuration too.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_host_config_manager:.py

##### ADDITIONAL INFORMATION

In a scenario where there are different configuration requirements for different ESXi Versions,
and a cluster contains ESXi Hosts of varying versions.

This would solve problems where configurations standards are by ESXi version

```yaml
- name: Manage Log level setting for all ESXi Host in given Cluster
  vmware_host_config_manager:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster_name: cluster_name
    esxi_version: 6.5
    options:
        'Config.HostAgent.log.level': 'info'
  delegate_to: localhost
```
