### ISSUE TITLE
VMware: Debian10 guest: "VMWareTools is not installed or is not running in the guest" vSphere 6.0

### ISSUE THREAD

**Issue by 5t4rdu5t** [ansible/ansible#54393]
##### SUMMARY
The package `open-vm-tools` is running (2147483647) in the VM

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/modules/cloud/vmware/vmware_vm_shell.py

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT

```
pip3 list | grep pyvmo
pyvmomi (6.7.1.2018.12)

pip list | grep pyvmo
pyvmomi                      6.7.1.2018.12
```
##### STEPS TO REPRODUCE

Trying to run the module

```yaml
  - name: rm file
    vmware_vm_shell:
      datacenter: '{{ datacenter }}'
      hostname: '{{ vcenter }}'
      username: "{{ login }}"
      password: "{{ passwd }}"
      validate_certs: False
      folder: "{{ folder }}"
      vm_id: "{{ vm_name }}"
      cluster: "{{ cluster }}"
      vm_password: '{{ pass }}'
      vm_username: root
      vm_shell: '/bin/rm'
      vm_shell_args: ' -f /path/to/file'
```
(The VM is UP when the module is running)

##### EXPECTED RESULTS

I expect the module to run without error
##### ACTUAL RESULTS

```
TASK [rm possible old file] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "VMWareTools is not installed or is not running in the guest. VMware Tools are necessary to run this module."}
```
