### ISSUE TITLE
get_url checksum does not support checksum files containing *just* the checksum

### ISSUE THREAD

**Issue by DanHam** [ansible/ansible#54390]
##### SUMMARY

get_url fails to parse a checksum file when the file contains *just* the checksum

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /Users/dan/.ansible.cfg
  configured module search path = ['/Users/dan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dan/.venv-ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/dan/.venv-ansible/bin/ansible
  python version = 3.7.2 (default, Dec 30 2018, 08:55:50) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/dan/.ansible.cfg) = False
INVENTORY_ENABLED(/Users/dan/.ansible.cfg) = ['host_list', 'script', 'yaml', 'ini', 'auto', 'gcp_compute']
```

##### OS / ENVIRONMENT

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.3
BuildVersion:   18D109
```

##### STEPS TO REPRODUCE

```yaml
- name: Demo error with plain checksum file
  get_url:
    checksum: sha512:https://dl.k8s.io/v1.13.0/bin/linux/amd64/kube-scheduler.sha512
    dest: /usr/bin/kube-scheduler
    mode: 0755
    url: https://dl.k8s.io/v1.13.0/bin/linux/amd64/kube-scheduler
```

For easy reference, the contents of the checksum file is as follows:

```
f400eedaef4aa277ba9ffbc17d1937fe2e200f5b4886930ae2c34e5a1a4ee14aee5d26c45b3babf7e791ba292787c950f55f4b9a32294472c73ec7b62af45858
```

##### EXPECTED RESULTS

get_url should be able to obtain the checksum from a file containing just the checksum.

At present get_url is able to handle the more complex case of parsing out the correct checksum from a file containing multiple checksums.

With the example shown above, there is no need to parse out the correct checksum. Here the checksum makes up the entirety of the file contents and all that is needed is to simply read the file.

ping @sivel as this was worked on recently in #53685

##### ACTUAL RESULTS

get_url fails and returns the following error

```paste below
"msg": "The checksum parameter has to be in format <algorithm>:<checksum>"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/get_url.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I think I would consider this a feature request.

In any case, for now you can do the following:

```
- name: Demo error with plain checksum file
  get_url:
    checksum: "sha512:{{ lookup('url', 'https://dl.k8s.io/v1.13.0/bin/linux/amd64/kube-scheduler.sha512') }}"
    dest: /usr/bin/kube-scheduler
    mode: 0755
    url: https://dl.k8s.io/v1.13.0/bin/linux/amd64/kube-scheduler
```
