### ISSUE TITLE
gcp_compute plugin: Dynamic inventory - underscore prepended to group names

### ISSUE THREAD

**Issue by DanHam** [ansible/ansible#54395]
##### SUMMARY

GCP dynamic inventory returns groups with an underscore prepended to them

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /Users/dan/.ansible.cfg
  configured module search path = ['/Users/dan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dan/.venv-ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/dan/.venv-ansible/bin/ansible
  python version = 3.7.2 (default, Dec 30 2018, 08:55:50) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/dan/.ansible.cfg) = False
INVENTORY_ENABLED(/Users/dan/.ansible.cfg) = ['host_list', 'script', 'yaml', 'ini', 'auto', 'gcp_compute']
```

##### OS / ENVIRONMENT

```bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.3
BuildVersion:   18D109
```

##### STEPS TO REPRODUCE

I want my inventory groups to match labels I have set on the GCE instances. I have the following set up:

dynamic-inventory.gcp.yml:

```yaml
plugin: gcp_compute
zones:
  - europe-west2-a
projects:
  - example-project
auth_kind: serviceaccount
service_account_file: /path/to/credentials.json
scopes:
  - https://www.googleapis.com/auth/compute
keyed_groups:
   - key: labels.nodetype
hostnames:
  - public_ip
```

I have set the following labels on my instances:

```bash
$ gcloud compute instances describe controller-0
canIpForward: true
cpuPlatform: Intel Broadwell
...
labels:
  nodetype: controller
...

$ gcloud compute instances describe worker-0
canIpForward: true
cpuPlatform: Intel Broadwell
...
labels:
  nodetype: worker
...
```

##### EXPECTED RESULTS

The group names returned should match the given 'nodetype' label exactly. I expect the following to be returned:

```bash
$ ansible-inventory -i dynamic-inventory.gcp.yml --graph
@all:
  |--@controller:
  |  |--1.1.1.1
  |  |--1.1.1.2
  |  |--1.1.1.3
  |--@worker:
  |  |--1.1.1.4
  |  |--1.1.1.5
  |  |--1.1.1.6
  |--@ungrouped:
```

##### ACTUAL RESULTS

Instead the group names have an underscore prepended to them.

```bash
$ ansible-inventory -i dynamic-inventory.gcp.yml --graph
@all:
  |--@_controller:
  |  |--1.1.1.1
  |  |--1.1.1.2
  |  |--1.1.1.3
  |--@_worker:
  |  |--1.1.1.4
  |  |--1.1.1.5
  |  |--1.1.1.6
  |--@ungrouped:
```

##### WORKAROUND

I am able to work around the issue by adding `separator: ''` to the `keyed_groups` section of the inventory file:

```yaml
plugin: gcp_compute
zones:
  - europe-west2-a
projects:
  - example-project
auth_kind: serviceaccount
service_account_file: /path/to/credentials.json
scopes:
  - https://www.googleapis.com/auth/compute
keyed_groups:
   - key: labels.nodetype
     separator: ''
hostnames:
  - public_ip
```

This gives the required output shown in the expected results section above.

It seems that the gcloud compute plugin assumes that the user is going to set a prefix in the keyed_groups section and so always adds an underscore.
