### ISSUE TITLE
win_user_right reports error on success

### ISSUE THREAD

**Issue by raffienficiaud** [ansible/ansible#54413]
##### SUMMARY
`win_user_right` reports an error although the user is properly added to the security group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_user_right

##### ANSIBLE VERSION

```paste below
ansible 2.7.9                                                                                                        
  config file = /home/raffi/code/ansible/ansible.cfg                                                                 
  configured module search path = ['/home/raffi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']     
  ansible python module location = /home/raffi/code/sandbox/venv_ansible_python3/lib/python3.6/site-packages/ansible 
  executable location = /home/raffi/code/sandbox/venv_ansible_python3/bin/ansible                                    
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]                                                

```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/home/raffi/code/ansible/ansible.cfg) = ['/home/raffi/code/ansible-roles', '/home/raffi/.ansible/roles', '/usr/share/
(END)                                                                                                                                   
```

##### OS / ENVIRONMENT
- target OS: win10 pro
- host OS: Linux Ubuntu 18.04

##### STEPS TO REPRODUCE

* create a local user
* assign the `SeServiceLogonRight` security group with `win_user_right`

```yaml
- name: '[BAMBOOAGENT][WIN] create user "{{ bambooagent_user }}"'
    win_user:
      name: "{{ bambooagent_user }}"
      fullname: "Bamboo agent user"
      user_cannot_change_password: yes
      password_never_expires: yes
      state: present
      password: "{{ bambooagent_passwd }}"
      groups:
      - "{{ bambooagent_group }}"
    register: win_bamboo_user_reg

  # because this user will be running the service
  - name: '[BAMBOOAGENT][WIN] add account to Log on as a service'
    win_user_right:
      name: SeServiceLogonRight
      users:
      - '{{ ansible_hostname }}\{{ bambooagent_user }}'
      action: add

```

##### EXPECTED RESULTS

* the user is added to the security group
* no error is reported

##### ACTUAL RESULTS

* the user is added to the security group (checked with the local security group snapin)
* an error is reported

```paste below
TASK [atlassian-bambooagent-role : [BAMBOOAGENT][WIN] create user "bambooagent"] *******************************************************
ok: [bamboo-win-test.local]                                                                                                             

TASK [atlassian-bambooagent-role : [BAMBOOAGENT][WIN] add account to Log on as a service] **********************************************
fatal: [bamboo-win-test.local]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "0 1 {\"changed\":true,\"added\":[\"
BAMBOO-WIN-TEST\\\\bambooagent\"],\"removed\":[]}\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}        

```
