### ISSUE TITLE
azure_rm_networkinterface ignores security_group parameter if create_with_security_group is False

### ISSUE THREAD

**Issue by jeking3** [ansible/ansible#54417]
##### SUMMARY

*This is a security bug.*

According to the documentation in version 2.7, `azure_rm_networkinterface` has a property called `create_with_security_group`.  If this is False during creation, the documentation states that a default security group will not be created.  This flag erroneously also causes the module to ignore a supplied `security_group`.  This leads to a NIC without a security group and the error is silent.

Either the documentation is wrong, or the code is wrong.  I tend to think the code is wrong here.  The flag is documented as controlling the default security group only... but it's doing more than that.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_networkinterface

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /ansible/lib/ansible
  executable location = /ansible/bin/ansible
  python version = 3.7.2+ (default, Feb 27 2019, 15:41:59) [GCC 8.2.0]
```
Specifically, using ansible git hash 51f38b090e7e6ec6973de33b4ab89511b1a8525c which is from today.  I did not try older versions.

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(env: ANSIBLE_SSH_PIPELINING) = True
DEFAULT_GATHERING(env: ANSIBLE_GATHERING) = smart
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/ansible/playbooks/roles']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### STEPS TO REPRODUCE

```yaml
#
# According to the documentation, create_with_security_group is supposed to
# suppress the creation of a default security group at creation time.  I would
# expect that if you supply a security_group at creation time that would be
# used.  What is happening instead is that no security group is applied, and
# it is not an error.
#

- name: Demonstrate a security bug in azure_rm_networkinterface
  hosts: all
  gather_facts: false
  tasks:

    - name: Create Resource Group
      azure_rm_resourcegroup:
        location: westus2
        name: showBug
      register: rg

    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        resource_group: showBug
        address_prefixes_cidr:
          - 10.0.0.0/16
        name: bugNetwork
      register: vnet

    - name: Create Security Group
      azure_rm_securitygroup:
        resource_group: showBug
        name: onlySshAccess
        rules:
          - access: Allow
            destination_port_range: 22
            direction: Inbound
            name: SSH
            priority: 100
            protocol: Tcp
      register: sg

    - name: Create Subnet
      azure_rm_subnet:
        resource_group: showBug
        name: bugSubnet
        address_prefix_cidr: 10.0.0.0/16
        virtual_network_name: bugNetwork
      register: subnet

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: showBug
        name: incorrectlyUnsecuredNic
        create_with_security_group: False
        ip_configurations:
          - name: myNic
            primary: true
            private_ip_allocation_method: Dynamic
            public_ip_allocation_method: Dynamic
        security_group: "{{ sg.state.id }}"
        subnet: bugSubnet
        virtual_network: "{{ vnet.state.id }}"
```

##### EXPECTED RESULTS

Expected to get a network interface with a security group.

##### ACTUAL RESULTS

No security group is attached to the NIC.  Notice how the `network_security_group` in the result is None.  The request has a `security_group`, and none was applied, and the task did not error!

```paste below
TASK [Create NIC] ****************************************************************************************************************************************************************************************
task path: /config/azure_rm_networkinterface_bug.yaml:49
Using module file /ansible/lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "create_with_security_group": false,
            "dns_servers": null,
            "enable_accelerated_networking": false,
            "enable_ip_forwarding": false,
            "ip_configurations": [
                {
                    "application_security_groups": null,
                    "load_balancer_backend_address_pools": null,
                    "name": "myNic",
                    "primary": true,
                    "private_ip_address": null,
                    "private_ip_allocation_method": "Dynamic",
                    "public_ip_address_name": null,
                    "public_ip_allocation_method": "Dynamic"
                }
            ],
            "location": null,
            "name": "incorrectlyUnsecuredNic",
            "open_ports": null,
            "os_type": "Linux",
            "password": null,
            "private_ip_address": null,
            "private_ip_allocation_method": "Dynamic",
            "profile": null,
            "public_ip": true,
            "public_ip_address_name": null,
            "public_ip_allocation_method": "Dynamic",
            "resource_group": "showBug",
            "secret": null,
            "security_group": "/subscriptions/fc5abd91-4de7-460b-8675-b1e46a7ec2bd/resourceGroups/showBug/providers/Microsoft.Network/networkSecurityGroups/onlySshAccess",
            "state": "present",
            "subnet": "bugSubnet",
            "subnet_name": "bugSubnet",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network": "/subscriptions/fc5abd91-4de7-460b-8675-b1e46a7ec2bd/resourceGroups/showBug/providers/Microsoft.Network/virtualNetworks/bugNetwork"
        }
    },
    "state": {
        "dns_servers": [],
        "dns_settings": {
            "applied_dns_servers": [],
            "dns_servers": [],
            "internal_dns_name_label": null,
            "internal_fqdn": null
        },
        "enable_accelerated_networking": false,
        "enable_ip_forwarding": false,
        "etag": "W/\"135e04a4-2575-4d0e-9201-cfee62a5fb5c\"",
        "id": "/subscriptions/fc5abd91-4de7-460b-8675-b1e46a7ec2bd/resourceGroups/showBug/providers/Microsoft.Network/networkInterfaces/incorrectlyUnsecuredNic",
        "ip_configuration": {
            "application_security_groups": null,
            "load_balancer_backend_address_pools": null,
            "name": "myNic",
            "primary": true,
            "private_ip_address": "10.0.0.4",
            "private_ip_allocation_method": "Dynamic",
            "public_ip_address": null,
            "subnet": {
                "id": "/subscriptions/fc5abd91-4de7-460b-8675-b1e46a7ec2bd/resourceGroups/showBug/providers/Microsoft.Network/virtualNetworks/bugNetwork/subnets/bugSubnet",
                "name": "bugSubnet",
                "resource_group": "showBug",
                "virtual_network_name": "bugNetwork"
            }
        },
        "ip_configurations": [
            {
                "application_security_groups": null,
                "load_balancer_backend_address_pools": null,
                "name": "myNic",
                "primary": true,
                "private_ip_address": "10.0.0.4",
                "private_ip_allocation_method": "Dynamic",
                "public_ip_address": null,
                "subnet": {
                    "id": "/subscriptions/fc5abd91-4de7-460b-8675-b1e46a7ec2bd/resourceGroups/showBug/providers/Microsoft.Network/virtualNetworks/bugNetwork/subnets/bugSubnet",
                    "name": "bugSubnet",
                    "resource_group": "showBug",
                    "virtual_network_name": "bugNetwork"
                }
            }
        ],
        "location": "westus2",
        "mac_address": null,
        "name": "incorrectlyUnsecuredNic",
        "network_security_group": null,
        "provisioning_state": "Succeeded",
        "tags": null,
        "type": "Microsoft.Network/networkInterfaces"
    }
}
```
