### ISSUE TITLE
Do not produce a warning when setting errors='ignore' in lookup()

### ISSUE THREAD

**Issue by mveroone** [ansible/ansible#54412]
##### SUMMARY
The lookup plugin has an option `errors` which can be either `strict`, `warn` or `ignore`  
But `warn` produces 2 warnings per error and `ignore` produces one as demonstrated in the documentation : https://docs.ansible.com/ansible/latest/plugins/lookup.html#id5

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Lookup plugins

##### ADDITIONAL INFORMATION
Have one meaningful warning per lookup use when using `warn` and none when using `ignore`

`warn`
```
- name: file doesnt exist, but i dont care .. file plugin itself warns anyways ...
  debug: msg="{{ lookup('file', '/idontexist', errors='ignore') }}"

[WARNING]: Unable to find '/idontexist' in expected paths (use -vvvvv to see paths)

ok: [localhost] => {
    "msg": ""
}
```

`ignore` : 
```
- name: file doesnt exist, but i dont care .. file plugin itself warns anyways ...
  debug: msg="{{ lookup('file', '/idontexist', errors='ignore') }}"

ok: [localhost] => {
    "msg": ""
}
```

##### CONTEXT
I want to copy the content of files whose name match one of the groups of the current host, so I loop over the host's groups but I get a warning every time the file doesn't exist
```yaml
- blockinfile:
      path: /my/file
      marker: "# {mark} {{ group }}"
      #block: "{{ lookup('template', group~'.j2', errors='ignore') }}"
      block: "{{ lookup('template', group~'.j2', errors='warn') }}"
    loop: "{{ group_names }}"
    loop_control:
      loop_var: group
```

I can't split it in a `local_action: stat` loop'd + `blockinfile` over the register because the playbook repository path is unpredictable in my context...
