### ISSUE TITLE
tower_user cannot create an auditor user 

### ISSUE THREAD

**Issue by yuuichi-fujioka** [ansible/ansible#54446]
##### SUMMARY

The `auditor` parameter of the tower_user module has no effect.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_user

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = /Users/fujioka/.ansible.cfg
  configured module search path = [u'/Users/fujioka/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/fujioka/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/fujioka/Library/Python/2.7/bin/ansible
  python version = 2.7.15 (default, Sep 18 2018, 20:16:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- tower_user:
    username: john
    password: secret
    email: foo@example.com
    first_name: john
    last_name: doe
    state: present
    auditor: yes
    tower_config_file: "~/tower_cli.cfg"
```
##### EXPECTED RESULTS

John's role is "System Auditor".

##### ACTUAL RESULTS

John's role is "Normal User".

`is_auditor` in tower_user.py#L118 is wrong.
It must be `is_system_auditor`.

see: https://github.com/ansible/ansible/blob/v2.7.9/lib/ansible/modules/web_infrastructure/ansible_tower/tower_user.py#L118
see: https://github.com/ansible/tower-cli/blob/master/tower_cli/resources/user.py#L32
