### ISSUE TITLE
ipmath does not support netmasks

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#54457]
##### SUMMARY
ipmath filter is unable to add to a netmask, e.g. Calculate host ip based on provided cidr.

##### ISSUE TYPE
- ~Bug  Report~
- Feature Idea

##### COMPONENT NAME
ipmath_filter

##### ANSIBLE VERSION
```paste below
ansible 2.8.0.dev0
  config file = /home/user/Git/Create_Infrastrukture_Windows/plays/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Private/ansible-1/lib/ansible
  executable location = /home/user/Private/ansible-1/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]

```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
ArchLinux

##### STEPS TO REPRODUCE

```yaml
- name: test
  hosts: localhost
  become: false
  gather_facts: false
  connection: loca
  tasks:
    - debug:
        msg: "{{ '192.168.2.0/24' | ipmath(10) }}"
```

##### EXPECTED RESULTS
`192.168.2.10/24`

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"msg": "the field 'args' has an invalid value ({'msg': \"{{ '192.168.2.0/24' | ipmath(10) }}\"}), and could not be converted to an dict.The error was: IPAddress() does not support netmasks or subnet prefixes! See documentation for details.\n\nThe error appears to be in '/home/user/Git/Create_Infrastrukture_Windows/plays/inventory.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - debug:\n      ^ here\n"}
```
