### ISSUE TITLE
vmware_guest fails to assign static address to multiple hosts

### ISSUE THREAD

**Issue by UnstableAlpha** [ansible/ansible#54467]
##### SUMMARY
When deploying multiple Windows VM guests from a single template (not sysprep'd), utilizing static IP addresses, a number of hosts are not assigned the correct address, but instead receive a link-local address. This only occurs with Windows hosts, and the same behaviour was not observed when using Ubuntu hosts as a test case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/jb/ansible/inventory']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

ESXi version 6.5.0 build 7967591
vSphere Client version 6.7.0.20000
Ubuntu 18.04.02
pip 9.0.1

##### STEPS TO REPRODUCE

Run the following playbook, task, & inventory:

```
# Playbook
- hosts: all
  gather_facts: false
  vars_files:
    - /home/jb/ansible/test_deploy/group_vars/all
  roles:
    - vspheredeploy

# Inventory
[domain-controller]
cr-dc-01 device_ip='192.168.22.1' vsphere_template=windows-2012r2-server_template
cr-dc-02 device_ip='192.168.22.2' vsphere_template=windows-2012r2-server_template

[file-server]
cr-fs-01 device_ip='192.168.22.5' vsphere_template=windows-2012r2-server_template

[exchange-server]
cr-mail-01 device_ip='192.168.22.6' vsphere_template=windows-2012r2-server_template

[windows:children]
domain-controller
file-server
exchange-server

[windows:vars]
ansible_connection=winrm
ansible_user="{{ admin_windows_user }}"
ansible_password="{{ admin_windows_password }}"
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_transport=ntlm

# vspheredeploy main.yml
- name: "Deploy Windows Host"
  delegate_to: localhost
  vmware_guest:
   hostname: "{{ vcenter_ip }}"
   username: "{{ vcenter_user }}"
   password: "{{ vcenter_pass }}"
   validate_certs: False
   name: "{{ inventory_hostname }}"
   template: "{{ vsphere_template }}"
   folder: "{{ vsphere_folder }}"
   state: poweredon
   annotation: Added by Ansible.
   datacenter: "{{ vcenter_dc }}"
   wait_for_ip_address: yes
   networks:
   - name: "{{ vsphere_network_name }}"
     device_type: vmxnet3
     type: static
     ip: "{{ device_ip }}"
     netmask: "{{ device_mask }}"
     gateway: "{{ device_gateway }}"
   customization:
    hostname: "{{ inventory_hostname }}"
    autologon: true
    autologoncount: 2
    fullname: "{{ domain_owner_name }}"
    orgname: "{{ domain_org_name }}"
    password: "{{ admin_windows_password }}"
    runonce: netsh advfirewall set allprofiles state off

# group_vars
# vSphere Connectivity:
vcenter_ip: 192.168.19.10
vcenter_user: REMOVED
vcenter_pass: REMOVED
vcenter_dc: REMOVED
vsphere_folder: /TestLabs1
vsphere_network_name: TestLabs1_192.168.22.0
device_mask: 255.255.255.0
device_gateway: 192.168.22.250
domain_owner_name: REMOVED
domain_org_name: REMOVED
admin_windows_user: Administrator
admin_windows_password: REMOVED
```

##### EXPECTED RESULTS

vSphere should deploy five guests from the same template, each with a unique hostname and static IP address as-per the inventory file

##### ACTUAL RESULTS

The Windows hosts are created, but only a small number receive the intended static IP configuration. With two hosts: Typically one receives the correct address. When deploying six, usually two hosts are fully- and correctly-configured. All other deployed hosts are assigned RFC3927 link-local IP addresses. All other guest customization occurs correctly: Hostname is correctly applied, runonce command is processed, etc. Having attempted a test case of a similar deployment, but using Ubuntu 16.04 Server hosts (from a template), the same behaviour is not reproduced when deploying *nix hosts.
