### ISSUE TITLE
uri module fails (hangs forever) where wait_for succeeds

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#54466]
##### SUMMARY
Truing to verify the availability of a port.

`uri` hangs forever, `wait_for` succeeds

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`uri`

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.9
  config file = /home/pkara/Workspace/gitlab/mdr-deployment/ansible/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
```
(empty)

##### OS / ENVIRONMENT (on ansible controller)

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
/home/pkara/Desktop/test
$ uname -a
Linux pkara-pc01 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: True

  tasks:



      - name: pre_tasks -> Check that 8080 port is open
        wait_for:
          host: "{{ inventory_hostname }}"
          port:  8080
          timeout: 200
          state: started



      - name: pre_tasks -> Check that env is up and running
        uri:
          url: "https://{{ inventory_hostname }}:8080"
          method:  GET
        register: env_status
        until: not env_status.failed
        retries: 150
        delay: 2
```

[Here](https://gist.github.com/pkaramol/1f7e7d69b0845d92342442b3ed80a2f0) is a gist with the output with `-vvvv`

Note that I have also run several other modules against the specific target host (besides `wait_for`) without any problem whatsoever; it seems to be an issue specific to `uri` module;

The process hangs *FOR EVER* at the end of the gist.
