### ISSUE TITLE
tower_credential module does not allow credential creation of custom tower credential type 

### ISSUE THREAD

**Issue by stana** [ansible/ansible#54493]
##### SUMMARY

Ansible Tower allows for custom credential types to be created. They can also be created using the existing module - tower_credential_type. But tower_credential module seems to only allow referencing built-in credentials (using 'kind' param) and does not allow us to reference and create credential of custom type.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_credential module

##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = None
  configured module search path = ['...../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ....../lib/python3.7/site-packages/ansible
  executable location = ........../bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Linux 4.19.12-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux

##### STEPS TO REPRODUCE

If we create a custom credential type using tower_credential_type module. Cannot specify custom credential type when creating a credential of this type using tower_credential module.

```yaml
    #
    # create some credential type
    #
    - name: Credential Type
      tower_credential_type:
        name: ACME
        kind: cloud
        state: present
        inputs:
          fields:
            - type: "string"
              id: "username"
              label: "ACME Username"
            - type: "string"
              secret: true
              id: "password"
              label: "ACME Password"
        injectors:
          extra_vars:
            acme_user: "{{'{{ username }}'}}"
            acme_pass: "{{'{{ password }}'}}"

    #
    # cannot create credential of above type as tower_credential module only supports 
    # 'kind' attrib allowing built-in creds only. Need to be able to specify credential_type 
    # param, something like -
    #
    - name: Credential
      tower_credential:
        name: "ACME Cred"
        organization: Foo
        # 'cloud' invalid kind, and cannot specify custom credential type
        #kind: cloud
        #credential_type: ACME
        state: present
   
```

##### EXPECTED RESULTS

After custom cred type created cannot create credential of this type as tower_credential module only supports  'kind' attrib allowing built-in creds only. Need to be able to specify credential_type param, something like -

    - name: Credential
      tower_credential:
        name: "ACME Cred"
        organization: Foo
        # 'cloud' invalid kind, and cannot specify custom credential type
        kind: cloud
        credential_type: ACME
        state: present

##### ACTUAL RESULTS

Cannot create credential of custom cred type.

```paste below
"Unsupported parameters for (tower_credential) module: credential_type"
```
