### ISSUE TITLE
show reason for skipping the statement

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5449]
It would be nice if we could specify a message for skipped statements.

Something like:

``` yaml
- apt: pkg=ntp state=present
  when: not ec2
  skip_reason: "We don't need ntp on EC2"
```

This will but raise another issue for complex when-clauses, it will not be very easy to specify one in the case like the below:

``` yaml
- name: zabbix apt repository
  apt_repository: repo="{{ zabbix_apt_repository }}"
  sudo: true
  when: ansible_lsb.codename != "lenny"   # no repo for Lenny
    and ansible_kernel >= "2.6.27"  # https://support.zabbix.com/browse/ZBX-3395
```

Do you think raising a separate issues to let us specify several when clauses would make sense?
