### ISSUE TITLE
postgresql_privs ignores partioned tables in ALL_IN_SCHEMA

### ISSUE THREAD

**Issue by raymondroelands** [ansible/ansible#54516]
##### SUMMARY
The ALL_IN_SCHEMA option of postgresql_privs ignores the partioned tables.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postresql_privs

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = None
  configured module search path = ['/home/noot/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT
Postgresql version 10.0 > 

##### STEPS TO REPRODUCE

Include partioned table in your schema and grant access access to ALL_IN_SCHEMA

```yaml
- postgresql_privs:
    db: library
    state: present
    privs: INSERT,UPDATE
    objs: ALL_IN_SCHEMA
    role: myrole
```

##### EXPECTED RESULTS

The db user is granted access rights to the partioned and all underlying tables

##### ACTUAL RESULTS

The db user is only granted access to the underlying tables

```

```
