### ISSUE TITLE
Add networkRuleSets for evenhub

### ISSUE THREAD

**Issue by adithyakhamithkar** [ansible/ansible#54515]
##### SUMMARY

Add networkRuleSets for evenhub I am referring this documentation https://docs.microsoft.com/en-us/rest/api/eventhub/namespaces/createorupdatenetworkruleset

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

I am trying to structure the ansible playbook like this I am not sure if it's the right way
```
- name: Create network rules
    azure_rm_resource:
    api_version: '2017-04-01'
    resource_group: "{{pl_resource_group_name}}"
    provider: eventhub
    resource_type: namespaces
    resource_name: "{{pl_eventhub_namespacename}}"
    state: present
    subresource:
      - type: eventhubs
        name: networkRuleSets
    body:
      properties:
        defaultAction: "Deny"
        # virtualNetworkRules:
        #   - subnet: "{{pl_subnet_name}}"
        #     ignore_missing_vnet_service_endpoint: yes
        ipRules:
          - ipMask: "{{item}}"
            action: "Allow"
  with_items:
    - "{{pl_ip_range_filter | list}}"
```

This is how my body is going
```
"invocation": {
       "module_args": {
           "ad_user": null,
           "adfs_authority_url": null,
           "api_profile": "latest",
           "api_version": "2017-04-01",
           "auth_source": null,
           "body": {
               "properties": {
                   "defaultAction": "Deny",
                   "ipRules": [
                       {
                           "action": "Allow",
                           "ipMask": "*****"
                       }
                   ]
               }
           },
           "cert_validation_mode": null,
           "client_id": null,
           "cloud_environment": "AzureCloud",
           "idempotency": false,
           "method": "PUT",
           "password": null,
           "polling_interval": 60,
           "polling_timeout": 0,
           "profile": null,
           "provider": "eventhub",
           "resource_group": "****",
           "resource_name": "****",
           "resource_type": "namespaces",
           "secret": null,
           "state": "present",
           "status_code": [
               200,
               201,
               202
           ],
           "subresource": [
               {
                   "name": "networkRuleSets",
                   "type": "eventhubs"
               }
           ],
           "subscription_id": null,
           "tenant": null,
           "url": null
       }
```
