### ISSUE TITLE
Provide variable to iterate over all inventory hosts

### ISSUE THREAD

**Issue by 0x46616c6b** [ansible/ansible#5451]
At the moment they exists no method to iterate in a tasks over all hosts. This would be very helpful for small backup automation for example.

Like this:

```
- name: ensure backup directories are present
  action: file path=/var/backups/{{ item }} state=directory
      owner=backup group=backup mode=0700
  with_items: all_hosts
  tags:
    - backup
```
