### ISSUE TITLE
[RFE] Extend ovirt_template Module

### ISSUE THREAD

**Issue by tmichett** [ansible/ansible#54528]
##### SUMMARY

Extend the **ovirt_template** module import functionality. Currently, as it stands a template cannot be imported into any other RHV Data Center / Storage Domain if the template already exists. You get error from Ansible:

"Import Template failed - Template Id already exist in the system. Please remove the Template (Template_Name) from the system first]". HTTP response code is 409."

This is expected as even in the WebUI, it notices a template is already there and prompts with a "Import Template Conflict" UI where the user can specify a new **Cloned** name and the template will be allowed to import as needed.

##### ISSUE TYPE
- Feature Idea

When state import, then have another could options that can be used

clone_template: True/False
clone_template_name: {name to call the new template} or default where it will add "_copy" to the name

##### COMPONENT NAME

No new component/module name, just some additional features added to module. The module needs additional information to specify that user desires to clone the template in the import process and needs to allow the user to specify the new name for the cloned template.

As is, this is the only way to import a template:

    - name: Import Template from Development Export Domain - Production Data Center
      ovirt_template:
        auth: "{{ ovirt_auth }}"
        name: Dev_WS_VM_Template
        export_domain: Dev_EXPORT_Data
        storage_domain: Prod_iSCSI_Data
        cluster: Production_Cluster
        state: imported

However, if the "Dev_WS_VM_Template" exists in any Data Center, it will fail to import. Suggest that we do the following:

    - name: Import Template from Development Export Domain - Production Data Center
      ovirt_template:
        auth: "{{ ovirt_auth }}"
        name: Dev_WS_VM_Template
        clone_template: true
        clone_template_name: Prod_WS_VM_Template
        export_domain: Dev_EXPORT_Data
        storage_domain: Prod_iSCSI_Data
        cluster: Production_Cluster
        state: imported

##### ADDITIONAL INFORMATION

Often in production data centers and RHV environments there is a need to re-use or have the same template used in multiple Data Centers and storage domains. Without the ability to rename/clone in Ansible, this step isn't possible to do without going through the WebUI.

```yaml
    - name: Import Template from Development Export Domain - Production Data Center
      ovirt_template:
        auth: "{{ ovirt_auth }}"
        name: Dev_WS_VM_Template
        clone_template: true
        clone_template_name: Prod_WS_VM_Template
        export_domain: Dev_EXPORT_Data
        storage_domain: Prod_iSCSI_Data
        cluster: Production_Cluster
        state: imported

```
