### ISSUE TITLE
kinesis_stream fails to update shard count

### ISSUE THREAD

**Issue by Tyler-2** [ansible/ansible#54529]
##### SUMMARY

While support was added for updating the shard count of an existing Kinesis stream ( https://github.com/ansible/ansible/pull/24805 ) there is still logic left over from before that support was added that errors out if the stream exists and we're trying to change shard counts.

> Can not change the number of shards in a Kinesis Stream

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kinesis-stream

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tschwend/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below


```

##### STEPS TO REPRODUCE

Try to make changes to an existing stream's shard count. (Note the below is typed from memory and I haven't actually run it, sorry)

```yaml
  tasks:
    - name: create kinesis stream
      kinesis_stream:
        name: 'test-shard-updates'
        shards: 2
        retention_period: 24
        wait: yes
        state: present
    - name: now update kinesis stream and shard count
      kinesis_stream:
        name: 'test-shard-updates'
        shards: 4
        retention_period: 24
        wait: yes
        state: present
```

##### EXPECTED RESULTS

Update the shard count within the rules of AWS shard changes.

##### ACTUAL RESULTS

Fail with "Can not change the number of shards in a Kinesis Stream"

```paste below

```
