### ISSUE TITLE
kinesis_stream fails to delete tags

### ISSUE THREAD

**Issue by Tyler-2** [ansible/ansible#54534]
##### SUMMARY

When removing tags from a Kinesis stream, the module fails out with:

`botocore.exceptions.ParamValidationError: Parameter validation failed:\nInvalid type for parameter TagKeys, value: dict_keys(['app']), type: <class 'dict_keys'>, valid types: <class 'list'>, <class 'tuple'>`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kinesis_stream

##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tschwend/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: False
  vars:
    kinesis_name: tyler-test
    kinesis_shards: 2
    kinesis_retention: 24
    tags_allofem:
      service: testing
      owner: tyler-2
      app: somethingtodeletelater
    tags_onedeleted:
      owner: tyler-2
      service: testing
  tasks:
    - name: create kinesis stream
      kinesis_stream:
        name: '{{ kinesis_name }}'
        shards: '{{ kinesis_shards }}'
        retention_period: 24
        wait: yes
        tags: '{{ tags_allofem }}'
        state: present
    - name: delete the app key from the stream
      kinesis_stream:
        name: '{{ kinesis_name }}'
        shards: '{{ kinesis_shards }}'
        retention_period: 24
        wait: yes
        tags: '{{ tags_onedeleted }}'
        state: present
```

##### EXPECTED RESULTS

End up with a kinesis stream with `owner` and `service` tags.

##### ACTUAL RESULTS

Ansible fails to remove the unwanted tag.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/home/tschwend/.ansible/tmp/ansible-tmp-1553787583.1562543-240741273153257/AnsiballZ_kinesis_stream.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/tschwend/.ansible/tmp/ansible-tmp-1553787583.1562543-240741273153257/AnsiballZ_kinesis_stream.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/tschwend/.ansible/tmp/ansible-tmp-1553787583.1562543-240741273153257/AnsiballZ_kinesis_stream.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/tschwend/.ansible/tmp/ansible-tmp-1553787583.1562543-240741273153257/AnsiballZ_kinesis_stream.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_kinesis_stream_payload_xwbwgjmx/__main__.py\", line 1421, in <module>\n  File \"/tmp/ansible_kinesis_stream_payload_xwbwgjmx/__main__.py\", line 1390, in main\n  File \"/tmp/ansible_kinesis_stream_payload_xwbwgjmx/__main__.py\", line 1041, in create_stream\n  File \"/tmp/ansible_kinesis_stream_payload_xwbwgjmx/__main__.py\", line 968, in update\n  File \"/tmp/ansible_kinesis_stream_payload_xwbwgjmx/__main__.py\", line 585, in update_tags\n  File \"/tmp/ansible_kinesis_stream_payload_xwbwgjmx/__main__.py\", line 480, in tags_action\n  File \"/usr/lib/python3/dist-packages/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/lib/python3/dist-packages/botocore/client.py\", line 634, in _make_api_call\n    api_params, operation_model, context=request_context)\n  File \"/usr/lib/python3/dist-packages/botocore/client.py\", line 682, in _convert_to_request_dict\n    api_params, operation_model)\n  File \"/usr/lib/python3/dist-packages/botocore/validate.py\", line 297, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\nInvalid type for parameter TagKeys, value: dict_keys(['app']), type: <class 'dict_keys'>, valid types: <class 'list'>, <class 'tuple'>\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
