### ISSUE TITLE
Unable to remove deb package

### ISSUE THREAD

**Issue by helfgott** [ansible/ansible#54538]
##### SUMMARY

**After installing a package:**
```
- name: install nomachine
  apt:
    deb: /root/{{ nomachine_package }}
```
**I'm unable to uninstall it using:**
```
- name: uninstall nomachine
  apt:
    deb: nomachine-enterprise-terminal-server
    state: absent
```
**Error message is:**

`fatal: [SERVER]: FAILED! => {"changed": false, "failed": true, "msg": "deb only supports state=present"}`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
deb

##### ANSIBLE VERSION
```
ansible --version
ansible 2.3.0.0
```

##### CONFIGURATION
```
ansible-config dump --only-changed
-bash: ansible-config: command not found
```

##### OS / ENVIRONMENT
Target:
Linux  Ubuntu 16.04.4 LTS \n \l 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
```
# install a package with a .deb file (not from repos)
- name: install nomachine
  apt:
    deb: /root/{{ nomachine_package }}

# try uninstalling it

- name: uninstall nomachine
  apt:
    deb: nomachine-enterprise-terminal-server
    state: absent
```

##### EXPECTED RESULTS

The mentioned package gets uninstalled. This do not happen (probably) because apt.py is only able to uninstall the package if it was installed by repository.

##### ACTUAL RESULTS

```
<SERVEr> (0, '\r\n{"invocation": {"module_args": {"purge": false, "package": null, "force": false, "allow_unauthenticated": false, "autoremove": null, "state": "absent", "update_cache": null, "only_upgrade": false, "deb": "nomachine-enterprise-terminal-server", "dpkg_options": "force-confdef,force-confold", "cache_valid_time": 0, "default_release": null, "upgrade": null, "install_recommends": null}}, "failed": true, "msg": "deb only supports state=present"}\r\n', 'Shared connection to server closed.\r\n')
fatal: [server]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoremove": null, 
            "cache_valid_time": 0, 
            "deb": "nomachine-enterprise-terminal-server", 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": false, 
            "install_recommends": null, 
            "only_upgrade": false, 
            "package": null, 
            "purge": false, 
            "state": "absent", 
            "update_cache": null, 
            "upgrade": null
        }
    }, 
    "msg": "deb only supports state=present"
}
```

```paste below

```

**Comment by helfgott** [comment]
Seems like apt.py is looking for some cache of apt (this won't happen because the package was installed directly and not from repository).

As a workaround I'm executing this handler:
```
- name: uninstall nomachine
  shell: dpkg -r nomachine-enterprise-terminal-server
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is not a bug. The message you got is clear `deb only supports state=present`. You need to use the `name` param:
```
- name: uninstall nomachine
  apt:
    name: nomachine-enterprise-terminal-server
    state: absent
```

It does not make sense to use `deb` to uninstall a package since there is no `deb` file.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
