### ISSUE TITLE
jsonrpc log message not working for network_cli/netconf connection type

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#54605]
##### SUMMARY

Enable persistent logging with connection=netconf/network_cli. The ansible-connection jsonrpc log messages are not stored in the file
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.8
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ios
  gather_facts: no
  tasks:
  - name: get version information
    ios_command:
      commands:
        - show version
    vars:
      ansible_persistent_log_messages: True
```

##### EXPECTED RESULTS

jsonrpc request and response for command should be seen in the log file.

##### ACTUAL RESULTS

```paste below
jsonrpc request: {"params": [[], {}], "jsonrpc": "2.0", "method": "pop_messages", "id": "b6289b35-8240-4360-8be8-042afd09f4a7"} 
```
