### ISSUE TITLE
Jinja filters are insufficient for traversing complex data structures

### ISSUE THREAD

**Issue by jamesdh** [ansible/ansible#54614]
##### SUMMARY
Jinja2 filters are terrible at traversing complex structured data. We really need a better way. This to me seems like one of ansible's biggest weaknesses. See example below.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
filters

##### ADDITIONAL INFORMATION
I'm trying to consume some complex data in ansible, e.g...

```
defaults:
  com.apple.systempreferences:
    NSQuitAlwaysKeepsWindows: {type: bool, value: false}
  com.apple.universalaccess:
    reduceTransparency: {type: bool, value: true}
  NSGlobalDomain:
    NSAutomaticDashSubstitutionEnabled: {type: bool, value: false}
    NSAutomaticQuoteSubstitutionEnabled: {type: bool, value: false}
    NSWindowResizeTime: {type: float, value: 0.001}
```

Ultimately I'm trying to generate an iterable list of the cartesian product of various parts of that data, but I'm tripping up due to the fact the map filter cannot seemingly be interpreted as a dictionary. For example...

```
- debug:
    msg: "{{ item }}"
  loop: "{{ defaults|dict2items|map(attribute='value')|list }}"
```
 Correctly prints out the following: 
```
ok: [localhost] => (item=) =>
  msg:
    NSQuitAlwaysKeepsWindows:
      type: bool
      value: false
ok: [localhost] => (item=) =>
  msg:
    reduceTransparency:
      type: bool
      value: true
ok: [localhost] => (item=) =>
  msg:
    NSAutomaticDashSubstitutionEnabled:
      type: bool
      value: false
    NSAutomaticQuoteSubstitutionEnabled:
      type: bool
      value: false
    NSWindowResizeTime:
      type: float
      value: 0.001
```
But at this point I'm effectively stuck because I can't interpret the individual results of map in any sort of structured way. I effectively want to do the following: 
```
defaults|dict2items|map(attribute='value')|dict2items|map(attribute='key')|list
```
and have it result in a list that is just the following: 
```
    NSQuitAlwaysKeepsWindows
    reduceTransparency
    NSAutomaticDashSubstitutionEnabled
    NSAutomaticQuoteSubstitutionEnabled
    NSWindowResizeTime
```
But that doesn't appear possible with how the generator function that `map` returns works.

This seems like a fairly fundamental use case to me. This data isn't even that complex, yet with current Jinja filtering concepts I'm effectively stuck only a couple layers into it.
