### ISSUE TITLE
vmware_host: folder parameter is not consistent

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#54621]
##### SUMMARY

Hi!

I create a `Staging` folder in my dc1 datacenter with the following tasK

```yaml
  - name: Create host folder
    vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: dc1
      folder_name: "Staging"
      folder_type: host
      state: present
```

![vsphere](https://user-images.githubusercontent.com/49379/55260298-648e2d00-523e-11e9-9193-27e7694e2ce7.png)

Then I try to create a host in it:

```yaml
  - name: Add host to folder
    vmware_host:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      esxi_hostname: "{{ hostvars[esxi1].ansible_host }}"
      esxi_username: "{{ hostvars[esxi1].ansible_user }}"
      esxi_password: "{{ hostvars[esxi1].ansible_pass }}"
      datacenter_name: "dc1"
      folder_name: "/dc1/Staging"
      state: present
```

I get the following error: `fatal: [localhost]: FAILED! => {"changed": false, "msg": "Folder '/dc1/Staging' not found"}`

I also tried:

- Staging
- /dc1/Staging/host

I get the same error all the time. Am I doing something wrong?

note: I started a PR to simplify the access to the folders ( https://github.com/ansible/ansible/pull/54620 ). It allows me to create my host in the folder as expected. But since I'm not sure how to use the `vmware_host` module, I'm also afraid I may have introduce an unexpected behaviour too.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

vmware_host

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/goneri/git_repos/ansible/library']
  ansible python module location = /home/goneri/git_repos/ansible/lib/ansible
  executable location = /home/goneri/.virtualenvs/ansible/bin/ansible
  python version = 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```
