### ISSUE TITLE
known_hosts does not work with unhashed hosts

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#54661]
##### SUMMARY
`known_hosts` does not work with unhashed hosts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
known_hosts

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

##### STEPS TO REPRODUCE
```yaml
- name: Add known host
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: foo.bar
    key: foo.bar 2048 65537 123...456
    hash_host: no
```

##### EXPECTED RESULTS
Host added to file.

##### ACTUAL RESULTS
```paste below
fatal: [192.168.1.0]: FAILED! => {"changed": false, "msg": "Host parameter does not match hashed host field in supplied key"}
```

This error message doesn't make sense because the host field isn't _supposed_ to be hashed. I even explicitly set `hash_host: no` despite it purportedly being the default anyway.
