### ISSUE TITLE
cannot create zabbix discovery actions

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#54671]
##### SUMMARY
When creating a discovery action, escalation parameters are sent along, even though escalations are not supported for discovery actions.

This results in the discovery action creation failing:

    Cannot set "pause_suppressed" for action

This might be a regression from #51303.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION

Latest ansible_action from git with:

```paste below
ansible 2.6.8
  config file = /opt/ansible/config/ansible-config.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
```paste below
DEFAULT_FORKS(/opt/ansible/config/ansible-config.cfg) = 100
DEFAULT_HOST_LIST(/opt/ansible/config/ansible-config.cfg) = [u'/opt/ansible/inventory/cert/hosts']
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/config/ansible-config.cfg) = False
```

##### OS / ENVIRONMENT
Zabbix 4.0.6.

##### STEPS TO REPRODUCE
Try to create a discovery action:

```yaml
  - name: "discovery test action"
    event_source: 'discovery'
    conditions:
      - type: 'discovery_status'
        operator: '='
        value: 'up'
        formulaid: A
      - type: 'received_value'
        operator: 'like'
        value: 'some_value'
        formulaid: B
    formula: A and B
    operations:
      - type: 'remote_command'
        command_type: 'custom_script'
        execute_on: 'server'
        command: some_command
        run_on_hosts:
          - 0
```

##### EXPECTED RESULTS
Action gets created.

##### ACTUAL RESULTS
Action creation fails.

```paste below
Error -32602: Invalid params., Cannot set \"pause_suppressed\" for action \"discovery test action\". 
```
