### ISSUE TITLE
Module os_zone does not respect wait variable

### ISSUE THREAD

**Issue by ederst** [ansible/ansible#54680]
##### SUMMARY
Even though it is documented in the [documentation of the os_zone module](https://docs.ansible.com/ansible/latest/modules/os_zone_module.html) (I guess because it is a standard OpenStack module variable) it does not respect the `wait` variable.

This may be an issue with openstacksdk but since other OS modules implement wait themselves I am not sure about this. Anyhow, I've created a pull request for this (https://github.com/ansible/ansible/pull/54391) which adds a rudimentary `wait` functionality to the module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_zone

##### ANSIBLE VERSION
```paste below
ansible 2.7.6
  config file = None
  configured module search path = [u'/home/sprietl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
IMHO not relevant

##### OS / ENVIRONMENT
* Ubuntu 16.04
* openstacksdk 0.23.0

##### STEPS TO REPRODUCE

Btw. `wait` is not explicitly set because documentation says that default value is `yes|true`.

Example Playbook:
```yaml
- name: "delete zone"
  os_zone:
    auth: "{{ os_auth }}"
    state: absent
    name: "{{ item.name }}"
  loop: "{{ os_zones }}"

- name: "create zone"
  os_zone:
    auth: "{{ os_auth }}"
    state: present
    name: "{{ item.name }}"
    zone_type: "{{ item.type }}"
    email: "{{ item.email }}"
    description: "{{ item.description | default('') }}"
    ttl: "{{ item.ttl | default(3600) }}"
  loop: "{{ os_zones }}"

- name: "Create record sets"
  os_recordset:
    auth: "{{ os_auth }}"
    state: present
    zone: "{{ item.0.name }}"
    name: "{{ item.1.name }}.{{ item.0.name }}"
    recordset_type: "{{ item.1.type }}"
    records: "{{ item.1.records }}"
    description: "{{ item.1.description | default('') }}"
    ttl: "{{ item.1.ttl | default(omit) }}"
  loop: "{{ query('subelements', os_zones, 'record_sets', {'skip_missing': True}) }}"
```

Example configuration:
```yaml
os_zones:
  - name: "my-domain."
    type: "primary"
    email: "hostmaster@my-domain.com"
    description: "a zone"
    record_sets:
      - name: "myhost"
        type: "A"
        records:
          - "1.2.3.4"
```

##### EXPECTED RESULTS

(pseudo output)

```paste below
TASK [delete zone]
changed: []

TASK [create zone]
changed: []

TASK [Create record sets] 
changed: []
```

##### ACTUAL RESULTS

(pseudo output)

```paste below
TASK [delete zone]
changed: []

TASK [create zone]
ok: [] # it says ok here because zone still exists (but in PENDING/DELETING state)

TASK [Create record sets] 
fatal: [zone does not exist]
```
