### ISSUE TITLE
All GCP modules are broken and not updating resource correctly for changes

### ISSUE THREAD

**Issue by fangpenlin** [ansible/ansible#54694]
##### SUMMARY

All GCP modules are relying on `GcpRequest` for comparing differences between current resource and desired state described by the module

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/gcp_utils.py#L240-L250

It has weird assumption that only the value exists in the first given object (module) is checked against the second one (resource). As a result, many changes made won't trigger changes at all.

Given an example, say you want to add a new open port with your gcp firewall module, it ends up calling `GcpRequest` like this:

```python
module = dict(
    allowed=[
        dict(ip_protocol='tcp', port=1234),
        # new port
        dict(ip_protocol='tcp', port=22),
    ]
)
resource = dict(
    allowed=[
        dict(ip_protocol='tcp', port=1234),
    ]
)
from ansible.module_utils.gcp_utils import GcpRequest
# they should be different, but GcpRequest cannot detect it
assert(GcpRequest(module).difference(GcpRequest(resource)))
```

the same bugs for different modules:
https://github.com/ansible/ansible/issues/53753
https://github.com/ansible/ansible/issues/54373

the bug reported in upstream repo somehow got closed for no reason:
https://github.com/GoogleCloudPlatform/magic-modules/issues/394

I guess this bug is affecting all gcp modules, as changes like shown in the example won't trigger any resource change

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

all GCP modules

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = None
  configured module search path = ['/workplace/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /workplace/.local/share/virtualenvs/ansible-bug-XyY_Bc2M/lib/python3.7/site-packages/ansible
  executable location = /workplace/.local/share/virtualenvs/ansible-bug-XyY_Bc2M/bin/ansible
  python version = 3.7.0 (default, Sep  9 2018, 19:40:12) [Clang 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MacOS 10.14.4 (18E226)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_prompt:
    - name: "project_name"
      prompt: "Your GCP project name"
    - name: "service_account_file"
      prompt: "Your GCP service account file"
  tasks:
  # ensure GCP network is created and updated
  - name: create a network
    gcp_compute_network:
        name: "my-network"
        auto_create_subnetworks: true
        project: "{{ project_name }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ service_account_file }}"
        state: present
    register: network
  # create GCP network firewall
  - name: create a firewall
    gcp_compute_firewall:
        name: "my-network"
        allowed:
        - ip_protocol: tcp
          ports:
          - '1234'
        network: "{{ network.selfLink }}"
        project: "{{ project_name }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ service_account_file }}"
        state: present
  # update GCP network firewall
  - name: update the firewall
    gcp_compute_firewall:
        name: "my-network"
        allowed:
        - ip_protocol: tcp
          ports:
          - '1234'
        # the bug won't see this new port as a change here
        - ip_protocol: tcp
          ports:
          - '5678'
        network: "{{ network.selfLink }}"
        project: "{{ project_name }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ service_account_file }}"
        state: present

```

##### EXPECTED RESULTS

The last task should update the firewall rule and mark it as changed

##### ACTUAL RESULTS

The last task won't update the firewall rule as it doesn't think there's any difference between module and resource
