### ISSUE TITLE
yedit: string.split(',') | map('regex_replace', ...) | list will generate a bad list (Ansible 2.7.8-1.fc29)

### ISSUE THREAD

**Issue by nplanel** [ansible/ansible#54735]
##### SUMMARY

**input:**
```
"analyzers": "192.168.50.10:8082,192.168.50.20:8082"
```

**ansible**
```
- name: Setup Etcd embedded servers list
  yedit:
    src: "{{ skydive_config_file }}"
    key: "etcd.servers"
    value: "{{ analyzers.split(',') | map('regex_replace', '([^:]*).*', skydive_etcd_scheme + '://\\1:' + (skydive_etcd_port | string)) | list }}"
  when: (skydive_etcd_embedded | bool) and (analyzers.split(',') | list | length > 1)
```

**output:**
```
"servers": ["http://192.168.50.10:12379http://:12379", "http://192.168.50.20:12379http://:12379"]
```
**Expected**
```
"servers": ["http://192.168.50.10:12379", "http://192.168.50.20:12379"]
```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible-2.7.8-1.fc29.noarch
[root@dpdk2 ~]# ansible --version
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 16 2019, 19:49:22) [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 29

##### STEPS TO REPRODUCE

```yaml
- name: Setup Etcd embedded servers list
  yedit:
    src: "{{ skydive_config_file }}"
    key: "etcd.servers"
    value: "{{ analyzers.split(',') | map('regex_replace', '([^:]*).*', skydive_etcd_scheme + '://\\1:' + (skydive_etcd_port | string)) | list }}"
  when: (skydive_etcd_embedded | bool) and (analyzers.split(',') | list | length > 1)
```

##### EXPECTED RESULTS

```paste below
"servers": ["http://192.168.50.10:12379", "http://192.168.50.20:12379"]
```

##### ACTUAL RESULTS

```paste below
"servers": ["http://192.168.50.10:12379http://:12379", "http://192.168.50.20:12379http://:12379"]

```
