### ISSUE TITLE
Unable to use regex_replace filter in tags keyword

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#54780]
##### SUMMARY

When using `regex_replace` with `tags:` an error occurs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

task

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]

```

##### CONFIGURATION

```paste below
none
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  become: yes
  vars:
    roles:
      - sss.qqq
  gather_facts: no
  tasks:
    - include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item | regex_replace('.*([^.]+)', '\\.') }}"
      loop: "{{ item }}"
      tags: always
```

##### EXPECTED RESULTS

I would expect the `qqq` tag to apply to the tasks of the included role.

##### ACTUAL RESULTS

```paste below
ERROR! template error while templating string: unexpected end of template, expected ','.. String: {{ role | regex_replace('.*\\.'
```

I tried also the filter with the task's tag keyword (instead of `tags: always` and the result was the same.

This might be related to #51667.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/task.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The problem here is that `tags` can be a string, potentially with commas to separate tags, or it can be a list.  Due to that, you are passing a jinja2 expression that contains a comma and it's breaking the expression once it's split on the comma.

So you should be able to achieve your goal with:

```
- hosts: localhost
  become: yes
  vars:
    roles:
      - sss.qqq
  gather_facts: no
  tasks:
    - include_role:
        name: "{{ item }}"
        apply:
          tags:
            - "{{ item | regex_replace('.*([^.]+)', '\\.') }}"
      loop: "{{ item }}"
      tags: always
```

needs_info
