### ISSUE TITLE
include_role does not complain about undefined variables

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#54786]
##### SUMMARY

`include_role` does not complain when an undefined variable is used in one of the keywords, yet ansible exits with `1`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```paste below
ansible 2.8.0.dev0
  config file = /home/nikos/Projects/ansible-demo/ansible.cfg
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/nikos/Projects/ansible-demo/ansible.cfg) = ['/home/nikos/Projects/ansible-demo/inventory']
DEFAULT_ROLES_PATH(/home/nikos/Projects/ansible-demo/ansible.cfg) = ['/home/nikos/Projects/ansible-demo/roles', '/home/nikos/Projects']

```

##### OS / ENVIRONMENT

Arch linux latest

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  become: yes
  vars:
    roles:
      - sss.qqq
  gather_facts: no
  tasks:
    - include_role:
        name: "{{ role_name }}"
        apply:
          # tags: "{{ role | regex_replace('.*', '') }}"
          tags: "{{ role_name }}"
      loop: "{{ roles }}"
      tags: always
```

##### EXPECTED RESULTS

Some error about the undefined variable.

##### ACTUAL RESULTS

```paste below
[nikos@nikos-laptop ansible-demo]$ ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i inventory play1.yml 
 [WARNING]: Found variable using reserved name: roles


PLAY [localhost] *****************************************************************************************************************************************************************************

TASK [include_role : {{ role_name }}] ********************************************************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************************************************************************


```
