### ISSUE TITLE
manage_dir not working for authorized key module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#54789]
##### SUMMARY
The manage_dir option for the authorized key Module is not working as expected
so that permissions for an directory will be touched.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
authorized_key

##### ANSIBLE VERSION
ansible 2.7.9 installed via PIP

```

##### CONFIGURATION
DEFAULT_MANAGED_STR(/Users/sbaygithub/ansible/projects/ansible/ansible.cfg) = THIS FILE IS MANAGED BY ANSIBLE
DEFAULT_ROLES_PATH(/Users/sbaygithub/ansible/projects/ansible/ansible.cfg) = [u'/Users/sbaygithub/ansible/roles']
```

##### OS / ENVIRONMENT
Local OS: MacOS Mojave 10.14.3 with Python 2.7.10
Remote Server OS: Debian 9.8 with Python 2.7.13

##### STEPS TO REPRODUCE
Do the following as task or role:

```
- name: Add users publickey to root users authorized_key
  authorized_key:
      user: sbaygithub
      state: present
      manage_dir: no
      key: ssh-rsa ...
      path: /root/.ssh/authorized_keys
```

##### EXPECTED RESULTS

I would expect that the directory user/group permissions for /root/.ssh were not changed.

##### ACTUAL RESULTS
Currently when running the task, the /root/.ssh/ directory and their subfiles will be set to sbaygithub:sbaygithub  which is from my understanding not the right behavior. So I expect that the directory and files belong to root:root

-rw------- 1 sbaygithub sbaygithub 1184 Apr  3 07:26 /root/.ssh/authorized_keys
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/authorized_key.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/authorized_key.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
> Currently when running the task, the /root/.ssh/ directory and their subfiles will be set to sbaygithub:sbaygithub which is from my understanding not the right behavior. So I expect that the directory and files belong to root:root

In my testing, only `authorized_keys`'s permissions are changed. Permissions of `/root/.ssh/` directory remain the same. Can you confirm? Thanks.

```
[root@localhost ~]# ll -d /root/.ssh
drwxr-xr-x. 1 root root 30 Apr 10 14:50 /root/.ssh
[root@localhost ~]# ll /root/.ssh/authorized_keys 
-rw-------. 1 mkrizek mkrizek 15 Apr 10 14:50 /root/.ssh/authorized_keys
```

To me it seems that the behavior is correct. You stated that `sbaygithub`'s authorized_keys should be changed but pointed to an alternate location (`root`'s authorized_keys) and so it makes sense for that user to own them.

That said, maybe you wanted to do the following instead?
```
- name: Add users publickey to root users authorized_key
  authorized_key:
      user: root
      state: present
      manage_dir: no
      key: ssh-rsa ...
      path: /root/.ssh/authorized_keys
```

needs_info

**Comment by sbaygithub** [comment]
My goal is to add sshkeys for sshusers to the root's authorized_keys. In my case the users are defined in group_vars/all so users are present only on specified servers.

Maybe I just only misunderstand the docs or it's need to be added as feature.

**Comment by mkrizek** [comment]
> My goal is to add sshkeys for sshusers to the root's authorized_keys

As I already said in my previous comment. If you want to change authorized_keys for root, then you need to do `user: root` and not `user: sbaygithub`.

> Maybe I just only misunderstand the docs or it's need to be added as feature so that the manage_dir option won't touch the directory.

Again, as I already mentioned, the directory is not touched in my testing, just the file. Can you re-check that, please?

Also, did `/root/.ssh` existed prior to running `authorized_key` task?

Thanks!

needs_info

**Comment by sbaygithub** [comment]
Sorry for this, when I define user: sbaygithub the permissions looks like this:
```
drwx------  2 sbaygithub sbaygithub 4096 Apr 11 03:26 .ssh

drwx------ 2 sbaygithub sbaygithub 4096 Apr 11 03:26 .
drwx------ 5 root     root     4096 Apr 10 02:21 ..
-rw------- 1 sbaygithub sbaygithub 1954 Apr 11 03:26 authorized_keys
```

and when define root as user it looks similar:
```
drwx------  2 root root 4096 Apr 11 03:26 .ssh

drwx------ 2 root root 4096 Apr 11 03:26 .
drwx------ 5 root     root     4096 Apr 10 02:21 ..
-rw------- 1 root root 1954 Apr 11 03:26 authorized_keys
```

/root/.ssh was already present in my case.

My current testing scenario which is working as expected looks like the following:
group_vars/all/serverusers.yml
users:
- user1
- user2
- user 3
.....
In tasks/users there are files for user1, user2 and so on and includes:
```
- include: user.yml
  vars:
    username: sbaygithub
    sshkey: ssh-rsa....
    usershell: /bin/bash
    userhome: /home/{{ username }}
    userid: 123
```

The included user.yml looks like this:
```
- name: Add user to the system
  user:
    name: "{{ username }}"
    state: present
    home: "{{ userhome }}"
    uid: "{{ userid }}"
    group: "{{ username }}"
    shell: "{{ usershell }}"

- name: Add users Publickey to rootusers authfile < here is the part which breaks the .ssh dir
  authorized_key:
      user: "{{ username }}"
      state: present
      manage_dir: no
      key: "{{ sshkey }}"
      path: /root/.ssh/authorized_keys
```

As workaround I have added the following part to the users task:
```
- name: Fix permissions of /root/.ssh
  file:
  path: /root/.ssh/
  recurse: yes
   owner: root
   group: root
```

I hope I could clarify my problem better now :)

**Comment by mkrizek** [comment]
```
- name: Add users Publickey to rootusers authfile < here is the part which breaks the .ssh dir
  authorized_key:
      user: "{{ username }}"
      state: present
      manage_dir: no
      key: "{{ sshkey }}"
      path: /root/.ssh/authorized_keys
```

You are still setting the incorrect user. Again, you need to set `user: root` as your changing `root`'s authorized_keys and not `"{{ username }}"`

Documentation says:
```
The username on the remote host whose authorized_keys file will be modified
```

So `user` specifies who owns authorized_keys and NOT whose key you are inserting into authorized_keys.

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
