### ISSUE TITLE
XML module causes a failure when setting an unquoted number as value through a jinja2 variable

### ISSUE THREAD

**Issue by gator2003** [ansible/ansible#54797]
##### SUMMARY

Using the xml module causes a failure when setting an unquoted number as "value" through a jinja2 variable. The error is:

TypeError: Argument must be bytes or unicode, got 'int'

Putting \\" \\" around the variable is a workaround, but it puts the value in "" in the XML file, so I use another task to strip those out.

The following task works correctly:
```
- name: Set the https port
  xml:
    path: /opt/controller-info.xml
    xpath: /controller-info/controller-port
    value: "\"{{ https_port }}\""
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 10
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = maintuser
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = unixy
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.6 (Maipo)
FIPS mode enabled
AWS t3.small instance

##### STEPS TO REPRODUCE

Set the variable https_port to 8181 in all.yml under group_vars
Run the task below in a playbook on a remote machine

```yaml
- name: Set the https port
  xml:
    path: /opt/controller-info.xml
    xpath: /controller-info/controller-port
    value: "{{ https_port }}"
```

##### EXPECTED RESULTS

The value of 8181 in the all.yml is passed to the xml module and written to the file as text. Using unquoted numbers as values is in the Examples section of https://docs.ansible.com/ansible/latest/modules/xml_module.html

Expected output
```
<controller-info><controller-port>8181</controller-port></controller-info>
```
##### ACTUAL RESULTS

The playbook failed.

```paste below
rprxy-10 failed: {
"changed": false, 
"module_stderr": "FIPS mode initialized\r
Traceback (most recent call last):
  File \"<stdin>\", line 113, in <module>
  File \"<stdin>\", line 105, in _ansiballz_main
  File \"<stdin>\", line 48, in invoke_module
  File \"/tmp/ansible_xml_payload_MIujZQ/__main__.py\", line 868, in <module>
  File \"/tmp/ansible_xml_payload_MIujZQ/__main__.py\", line 854, in main
  File \"/tmp/ansible_xml_payload_MIujZQ/__main__.py\", line 584, in set_target
  File \"/tmp/ansible_xml_payload_MIujZQ/__main__.py\", line 570, in set_target_inner
  File \"lxml.etree.pyx\", line 921, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:41344)
  File \"apihelpers.pxi\", line 660, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:18894)
  File \"apihelpers.pxi\", line 1333, in lxml.etree._utf8 (src/lxml/lxml.etree.c:24601)
TypeError: Argument must be bytes or unicode, got 'int'
", 
"module_stdout": "", 
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1
} | msg: MODULE FAILURE
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/xml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sm4rk0** [comment]
This should work:
```YAML
- name: Set the https port
  xml:
    path: /opt/controller-info.xml
    xpath: /controller-info/controller-port
    value: "{{ https_port | string }}"
```

BTW, @dagwieers, is this the best practice or should the module do this internally? Would internal cast create problems like #54387?

Also, I tried with `to_text` instead of `string` like [here](https://github.com/ansible/ansible/blob/devel/test/integration/targets/jinja2_native_types/test_casting.yml), but got:
```
template error while templating string: no filter named 'to_text'
```
