### ISSUE TITLE
Add Extended Statistic to ec2_metric_alarm

### ISSUE THREAD

**Issue by wsill** [ansible/ansible#54810]
##### SUMMARY

It would be nice if ec2_metric_alarm supported the extended statistic.

https://aws.amazon.com/about-aws/whats-new/2017/10/amazon-cloudwatch-adds-support-for-extended-metrics-retention-percentile-statistics-and-high-resolution-custom-metrics-and-alarms-in-the-aws-govcloud-us-region/ 

like it does in powershell's Write-CWMetricAlarm
https://docs.aws.amazon.com/powershell/latest/reference/items/Write-CWMetricAlarm.html

and AWS CLI's put-metric-alarm
https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_metric_alarm

##### ADDITIONAL INFORMATION

We often use extended metrics to monitor our EC2 instances

```yaml
  - name: Create CloudWatch Alarm on production EC2s
     ec2_metric_alarm:
       state: present
       region: "{{ Region }}"
       name: "{{ StackName }}-CloudWatch-Alarm"
       metric: "StatusCheckFailed"
       namespace: "CPU"
       extendedstatistic: "p90"   <--- being able to do something like this is what I recommend
       comparison: ">="
       threshold: 1
       period: 3600
       evaluation_periods: 2
       description: "Created from Jenkins build"
       dimensions: {"InstanceId":"{{ aws_cf_stack.stack_outputs.InstanceId }}"}
       alarm_actions: ["arn:aws:sns:us-east-1:...:name"]
     when: Environment == "production"
```
