### ISSUE TITLE
`when: path is file` is actually checking localhost not remote host

### ISSUE THREAD

**Issue by guoqiao** [ansible/ansible#54834]
##### SUMMARY

use tests in `plugins/test/files.py` with `when` is actullay checking localhost other than remote.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tests/files

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.7.9
  config file = /home/joeg/.ansible.cfg
  configured module search path = ['/home/joeg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 18.04

##### STEPS TO REPRODUCE

Refer to following playbook example.

Although the file does exist on remote server, but the `when: item is file` condition is always False. If I create that file on my localhost, when condition turns True.

The other tests in `tests/files.py` have same behavior.

```yaml
- name: test ansible tests with when
  hosts: servers
  tasks:
    - name: test is file
      debug:
         msg: '{{item}} is file'
      when: item is file
      loop:
         - /tmp/test.txt
```

##### EXPECTED RESULTS

when condition should check the target remote hosts specified in play.

##### ACTUAL RESULTS

`when` is checking on localhost.

```paste below

```
