### ISSUE TITLE
gluster_peer: Use mode=script for peer detach/probe commands

### ISSUE THREAD

**Issue by sac** [ansible/ansible#54843]
##### SUMMARY
With recent changes in Gluster commands. gluster peer detach will prompt for question.
Hence ansible appears to have been stuck, as it is waiting on the (y/n) prompt in the remote
node.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gluster_peer

##### ANSIBLE VERSION

```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/home/sac/work']
```

##### OS / ENVIRONMENT

Fedora 28

##### STEPS TO REPRODUCE

```
- name: Delete a node from the trusted storage pool by force
  gluster_peer:
         state: absent
         nodes:
              - 10.0.0.1
         force: true
```

##### EXPECTED RESULTS

Ansible playbook should complete successfully.

##### ACTUAL RESULTS

Ansible playbook appears to have stuck.
