### ISSUE TITLE
apache2_module does not enbale new .conf if module is already enabled

### ISSUE THREAD

**Issue by tdaff** [ansible/ansible#54846]
##### SUMMARY

If a `.conf` file is created for an already enabled module `.load`, Ansible will not call `a2enmod` again to enable the config file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

apache2_module

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = None
  configured module search path = ['/home/tdd20/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tdd20/.local/Virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/tdd20/.local/Virtualenvs/ansible/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Debian and Ubuntu

##### STEPS TO REPRODUCE

* In the playbook, have some action that enables an Apache module that currently has no `.conf` file to to go with the `.load` file.
* Create a `.conf` file with configuration for the module.
* Re-run the Ansible command to enable the module.

```yaml

- name: Activate some_module
  apache2_module:
    name: some_module
    state: present

- name: Install some_module configuration
  copy:
    content: "ModuleConfig some_config"
    dest: /etc/apache2/mods-available/some_module.conf

- name: Re-activate some_module
  apache2_module:
    name: some_module
    state: present

```

Working example where installing a `.deb` activates the module by default. Writing some configuration after and the `apache2_module` does nothing.

```yaml

- name: Install mod_ucam_webauth package
  apt:
    deb: https://github.com/cambridgeuniversity/mod_ucam_webauth/releases/download/v2.0.5/libapache2-mod-ucam-webauth_2.0.5apache24.ubuntu-{{ ansible_distribution_version }}_amd64.deb
- name: Install mod_ucam_webauth configuration
  copy:
    content: "AAConfigVariable \"value\""
    dest: /etc/apache2/mods-available/ucam_webauth.conf
- name: Activae mod_ucam_webauth package
  apache2_module:
    name: ucam_webauth
    state: present
```

##### EXPECTED RESULTS

`a2enmod` will run during the second `apache2_module` invocation to enable the new config file. (Output of `a2enmod` would be `Enabling config file some_module.conf.`)

##### ACTUAL RESULTS

Module is treated as already loaded and no action is taken.

```paste below
ok: [host] => (item=some_module) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "force": false,
            "identifier": "some_module_module",
            "ignore_configcheck": false,
            "name": "some_module",
            "state": "present"
        }
    },
    "item": "some_module",
    "result": "Module some_module enabled"
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/apache2_module.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/apache2_module.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @berendt @n0trax @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by robinro** [comment]
@tdaff 
Can you please
- specify which distribution and version you are using and
- give a minimal working example, i.e. a playbook that can directly be run in a minimal docker image of your OS to reproduce the issue?

It sounds like you are referring to a feature of the debian/ubuntu a2enmod, that is not available on other distros like SUSE.

**Comment by n0trax** [comment]
@tdaff i can repoduce this issue at least on Ubuntu 18.04.

As a workaround for the described problem you have to disable the affected apache2 module and then enable it again. 

```
- name: Install some_module configuration
  copy:
    content: "ModuleConfig some_config"
    dest: /etc/apache2/mods-available/some_module.conf

- name: Deactivate some_module
  apache2_module:
    name: some_module
    state: absent

- name: Activate some_module
  apache2_module:
    name: some_module
    state: present
```

Currently apache2_module does not enable a module again if it is already active. Because of that a new configuration will not be activated by apache2_module.

@robinro How should we deal with this? IMHO this is a rare problem. Should we implement that `a2enmod` is called every time a module is requested to be present, even it is already enabled? But we would produce a lot of useless command calls with this behavior...or a additional module parameter to enforce a `a2enmod` call?
