### ISSUE TITLE
python2-dnf used instead of python3-dnf (Fedora 30)

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#54855]
##### SUMMARY
Fedora 30 [obsoleted the package python2-dnf](https://apps.fedoraproject.org/packages/fedora-obsolete-packages). When the module package or dnf is used, it wants to run the command `dnf install -y python2-dnf`. This fails since this package is not present anymore. This should point to python3-dnf.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dnf

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /home/user/git/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```

##### OS / ENVIRONMENT

Source OS: Fedora 29
Target OS: Fedora 30

##### STEPS TO REPRODUCE

```yaml
$ ansible --vault-id @prompt defiant -m dnf -a "name=vim state=present" -vv

defiant | FAILED! => {
    "changed": false,
    "cmd": "dnf install -y python2-dnf",
    "msg": "Error: Unable to find a match",
    "rc": 1,
    "stderr": "Error: Unable to find a match\n",
    "stderr_lines": [
        "Error: Unable to find a match"
    ],
    "stdout": "Last metadata expiration check: 0:02:19 ago on do 04 apr 2019 15:00:35 CEST.\nNo match for argument: python2-dnf\n",
    "stdout_lines": [
        "Last metadata expiration check: 0:02:19 ago on do 04 apr 2019 15:00:35 CEST.",
        "No match for argument: python2-dnf"
    ]
}
```
