### ISSUE TITLE
Logging on stderr slows down the win_shell module

### ISSUE THREAD

**Issue by bl4u90** [ansible/ansible#54865]
##### SUMMARY
Logging on stderr slows down the win_shell module.

Running a Python script, for example, using the `win_shell` module, which generates some logs to stderr, slows down the execution time of the module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_shell

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = None
  configured module search path = ['/Users/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/projects/XXX/lib/python3.6/site-packages/ansible
  executable location = /Users/XXX/projects/XXX/bin/ansible
  python version = 3.6.6 (default, Jun 28 2018, 05:43:53) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below
# empty, nothing changed
```

##### OS / ENVIRONMENT

Executing Ansible on MacOS 10.13.6. The node is a Windows Server 2012 R2 with python 3.6.5 installed.

##### STEPS TO REPRODUCE

Execute following playbook on a Windows node

```yaml
- hosts: all

  tasks:
    - name: Create test script for stdout
      win_copy:
        dest: "C:\\test_stdout.py"
        content: |+
          import sys
          for _ in range(5000):
            print('Test stdout', file=sys.stdout)

    - name: Test slow win_shell (stdout)
      win_shell: "py C:\\test_stdout.py"
      register: result

    - name: Print the time the task needed
      debug:
        var: result.delta

    - name: Create test script for stderr
      win_copy:
        dest: "C:\\test_stderr.py"
        content: |+
          import sys
          for _ in range(5000):
            print('Test stderr', file=sys.stderr)

    - name: Test slow win_shell (stderr)
      win_shell: "py C:\\test_stderr.py"
      register: result

    - name: Print the time the task needed
      debug:
        var: result.delta
```

##### EXPECTED RESULTS

The task to execute the script printing to stderr should be executed as fast as the script for the stdout.

##### ACTUAL RESULTS

```paste below
TASK [Create test script for stdout] *******************************************
changed: [windows-node]

TASK [Test slow win_shell (stdout)] ********************************************
changed: [windows-node]

TASK [Print the time the task needed] ******************************************
ok: [windows-node] => {
    "result.delta": "0:00:06.031194"
}

TASK [Create test script for stderr] *******************************************
changed: [windows-node]

TASK [Test slow win_shell (stderr)] ********************************************
changed: [windows-node]

TASK [Print the time the task needed] ******************************************
ok: [windows-node] => {
    "result.delta": "0:05:59.004226"
}
```

##### ROOT CAUSE
In the win_shell.ps1 the stderr output is [filtered](https://github.com/ansible/ansible/blob/d8bddc0d221209885f33817c656f087835b9694d/lib/ansible/modules/windows/win_shell.ps1#L122) by a [Cleanse-Stderr](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_shell.ps1#L16-L40) function which cause the slow down.

This change was commit by this PR: https://github.com/ansible/ansible/pull/23329
