### ISSUE TITLE
git module hanging with no output

### ISSUE THREAD

**Issue by jamesdh** [ansible/ansible#54876]
##### SUMMARY
git module hangs with basic clone example when running with `connection: local`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /Users/james/Development/dotfiles/ansible.cfg
  configured module search path = ['/Users/james/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/james/Development/dotfiles/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/Users/james/Development/dotfiles/ansible.cfg) = ['/Users/james/Development/dotfiles/hosts']
DEFAULT_STDOUT_CALLBACK(/Users/james/Development/dotfiles/ansible.cfg) = yaml
```

##### OS / ENVIRONMENT

MacOS 10.14.4

##### STEPS TO REPRODUCE

Using a very basic example of the `git` module running against localhost with `connection: local`, the git module hangs with no useful output. 

I've verified the host is added in my `known_hosts` file and have successfully cloned the dir manually via `git clone git@github.com:jamesdh/dotfiles.git`, yet it hangs indefinitely when attempting to with the following ansible playbook. 

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Setup git repositories 
      git:
        repo: "ssh://git@github.com:jamesdh/dotfiles.git"
        dest: "~/Projects/dotfiles"
        accept_hostkey: true
```

##### EXPECTED RESULTS

Repository is cloned 

##### ACTUAL RESULTS

```paste below
TASK [Setup git repositories] ****************************************************************************************************************************************************************************************************************
task path: /Users/james/Development/dotfiles/ansible.yml:4
Thursday 04 April 2019  13:26:06 -0500 (0:00:00.799)       0:00:00.901 ********
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: james
<127.0.0.1> EXEC /bin/sh -c 'echo ~james && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/james/.ansible/tmp/ansible-tmp-1554402366.2258828-130170850607735 `" && echo ansible-tmp-1554402366.2258828-130170850607735="` echo /Users/james/.ansible/tmp/ansible-tmp-1554402366.2258828-130170850607735 `" ) && sleep 0'
Using module file /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible/modules/source_control/git.py
<127.0.0.1> PUT /Users/james/.ansible/tmp/ansible-local-5449otu0qmdt/tmpksjtfc84 TO /Users/james/.ansible/tmp/ansible-tmp-1554402366.2258828-130170850607735/AnsiballZ_git.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/james/.ansible/tmp/ansible-tmp-1554402366.2258828-130170850607735/ /Users/james/.ansible/tmp/ansible-tmp-1554402366.2258828-130170850607735/AnsiballZ_git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /Users/james/.ansible/tmp/ansible-tmp-1554402366.2258828-130170850607735/AnsiballZ_git.py && sleep 0'
```
...and at that point it just hangs.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/source_control/git.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jamesdh** [comment]
FWIW, using the shell module as a workaround worked just fine: 

```
- hosts: localhost
  connection: local
  tasks: 
    - name: Setup git repositories 
      shell: "git clone git@github.com:jamesdh/dotfiles.git"
      args:
        chdir: "~/Projects"
```
