### ISSUE TITLE
Allow lookup modules as src for junos_config

### ISSUE THREAD

**Issue by sebastianw** [ansible/ansible#54897]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
modules/network/junos/junos_config

##### ADDITIONAL INFORMATION
Currently the `src` parameter in the `junos_config` module can only reference a filename on disk and **NOT** a lookup. To use for example the template engine without temporary files it would be nice if the src parameter could also contain the config itself so it can be used with a template lookup like this for example:

```
- name: load configure file into device
  junos_config:
    src: "{{ lookup('template', 'my_junos_config.j2') }}"
    update: replace
    comment: update config
```
Right now this takes two steps, a) writing the template to temporary file on disk and b) pushing the configuration.
