### ISSUE TITLE
bigip_profile_client_ssl fails when default(omit) filter is used on chain parameter

### ISSUE THREAD

**Issue by OncleDave** [ansible/ansible#54904]
##### SUMMARY
bigip_profile_client_ssl fails when adding a default(omit) filter on the chain parameter, and not defining it in the input parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
bigip_profile_client_ssl

##### ANSIBLE VERSION
```paste below
ansible 2.7.6
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]
```

##### CONFIGURATION
```
# Create client ssl profile on F5
- name: Create client ssl profile on F5
  bigip_profile_client_ssl:
    provider: "{{ credentials }}"
    state: "{{ act | default ('present')}}"
    partition: "{{ params.general.partition }}"
    cert_key_chain:
      - cert: "{{ params.sslprof.client.cert }}"
        key: "{{ params.sslprof.client.key }}"
        chain: "{{ params.sslprof.client.chain | default(omit) }}"
        passphrase: "{{ params.sslprof.client.pass | default(omit) }}"
    ciphers: "DEFAULT:!RSA:!3DES:!DHE:!TLSV1"
    name: "{{ params.sslprof.client.profile_name }}"
    parent: "{{ params.sslprof.client.parent_profile | default(omit)}}"
  delegate_to: localhost
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
Use this param variable
```       params:
      cert: null
      csr: null
      general:
        app_name: AppFoo
        bu: Global BU
        devices: lab-lb002.lab.net
        env: DEV
        partition: SandBox
      modules:
      - SSL Profiles
      pool: null
      sslprof:
        act: present
        client:
          cert: test.mydomain.test
          key: test.mydomain.test
          profile_name: test.mydomain.test_2019
      vs: null
```
Setting the following line as comment in the config works fine (no failure).
```
#        chain: "{{ params.sslprof.client.chain | default(omit) }}"
```

##### EXPECTED RESULTS
```
TASK [ssl_profile : Create client ssl profile on F5] ***************************************************************************************************************************************************
changed: [localhost -> localhost] => changed=true
```

##### ACTUAL RESULTS
Chain certificate is submitted to F5 in place of being omitted as requested by the default(omit) filter.

```
TASK [ssl_profile : Create client ssl profile on F5] ***************************************************************************************************************************************************
task path: /home/user/ansible/ansible-role-f5/ssl_profile/tasks/main.yml:3
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_bigip_profile_client_ssl_payload_ko2Ext/__main__.py", line 726, in main
    results = mm.exec_module()
  File "/tmp/ansible_bigip_profile_client_ssl_payload_ko2Ext/__main__.py", line 552, in exec_module
    raise F5ModuleError(str(e))

fatal: [localhost -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      allow_non_ssl: null
      auth_provider: null
      cert_key_chain:
      - cert: test.mydomain.test
        chain: __omit_place_holder__28fdcc7e78371261c2a11b95932fd503c1c8d08e
        key: test.mydomain.test
        passphrase: __omit_place_holder__28fdcc7e78371261c2a11b95932fd503c1c8d08e
      ciphers: DEFAULT:!RSA:!3DES:!DHE:!TLSV1
      name: test.mydomain.test_2019
      options: null
      parent: /Common/clientssl
      partition: SandBox
      password: null
      provider:
        auth_provider: null
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        server: lab-lb002.lab.net
        server_port: null
        ssh_keyfile: null
        timeout: null
        transport: rest
        user: admin
        validate_certs: false
      secure_renegotiation: null
      server: null
      server_port: null
      state: present
      transport: null
      user: null
      validate_certs: null
  msg: |-
    400 Unexpected Error: Bad Request for uri: https://lab-lb002.lab.net:443/mgmt/tm/ltm/profile/client-ssl/~SandBox~test.mydomain.test_2019/
    Text: u'{"code":400,"message":"0107134a:3: File object by name (/SandBox/__omit_place_holder__28fdcc7e78371261c2a11b95932fd503c1c8d08e.crt) is missing.","errorStack":[],"apiError":3}'
        to retry, use: --limit @/home/user/ansible/ansible-role-f5/f5_vip_master.retry

```
