### ISSUE TITLE
[KubeVirt] Creating a VM from template fails

### ISSUE THREAD

**Issue by vatsalparekh** [ansible/ansible#54900]
##### SUMMARY

Creating a VM from template fails with the error
>Playbook used
```
    - name: Create a VM from the template created
      kubevirt_vm:
        name: test
        namespace: default
        template: "{{ template_name }}"
        template_parameters:
          name: test-vm-template
```

>Error
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_kubevirt_vm_payload_I3bc0P/ansible_kubevirt_vm_payload.zip/ansible/module_utils/k8s/raw.py", line 279, in perform_action
    k8s_obj = resource.create(definition, namespace=namespace).to_dict()
  File "/home/vparekh/.local/lib/python2.7/site-packages/openshift/dynamic/client.py", line 77, in inner
    raise api_exception(e)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "error": 422, 
    "invocation": {
        "module_args": {
            "api_key": null, 
            "bootloader": null, 
            "ca_cert": null, 
            "client_cert": null, 
            "client_key": null, 
            "cloud_init_nocloud": null, 
            "context": null, 
            "cpu_cores": null, 
            "cpu_features": null, 
            "cpu_limit": null, 
            "cpu_model": null, 
            "cpu_shares": null, 
            "datavolumes": null, 
            "disks": null, 
            "ephemeral": false, 
            "force": false, 
            "headless": null, 
            "host": null, 
            "hugepage_size": null, 
            "interfaces": null, 
            "kubeconfig": null, 
            "labels": null, 
            "machine_type": null, 
            "memory": null, 
            "memory_limit": null, 
            "merge_type": null, 
            "name": "test", 
            "namespace": "default", 
            "password": null, 
            "resource_definition": null, 
            "smbios_uuid": null, 
            "state": "present", 
            "tablets": null, 
            "template": "test-template", 
            "template_parameters": {
                "name": "test-vm-template"
            }, 
            "username": null, 
            "validate_certs": null, 
            "wait": true, 
            "wait_timeout": 120
        }
    }, 
    "msg": "Failed to create object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"admission webhook \\\"virtualmachine-validator.kubevirt.io\\\" denied the request: spec.template.spec.networks.resource in body is a forbidden property, spec.template.spec.networks.name in body is required, spec.template.spec.volumes.name in body is required, spec.template.spec.domain.devices.disks.name in body is required, spec.template.spec.domain.devices.interfaces.name in body is required\",\"reason\":\"Invalid\",\"details\":{\"causes\":[{\"message\":\"spec.template.spec.networks.resource in body is a forbidden property\"},{\"message\":\"spec.template.spec.networks.name in body is required\"},{\"message\":\"spec.template.spec.volumes.name in body is required\"},{\"message\":\"spec.template.spec.domain.devices.disks.name in body is required\"},{\"message\":\"spec.template.spec.domain.devices.interfaces.name in body is required\"}]},\"code\":422}\n", 
    "reason": "Unprocessable Entity", 
    "status": 422
}
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubevirt_vm
##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by vatsalparekh** [comment]
@machacekondra I also wonder what would be the output with `template_parameter` taking `name` and `kubevirt_vm` also asking it (what if different). Same confusion around namespace and resources, template would have a value and `kubevirt_vm` can also be given those values.

**Comment by ansibot** [comment]
cc @kubevirt @mmazur @pkliczewski
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pkliczewski** [comment]
@machacekondra please take a look

**Comment by machacekondra** [comment]
How does your template look like. As error says you miss following there:

```
    "msg": "Failed to create object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"admission webhook \\\"virtualmachine-validator.kubevirt.io\\\" denied the request: spec.template.spec.networks.resource in body is a forbidden property, spec.template.spec.networks.name in body is required, spec.template.spec.volumes.name in body is required, spec.template.spec.domain.devices.disks.name in body is required, spec.template.spec.domain.devices.interfaces.name in body is required\",\"reason\":\"Invalid\",\"details\":{\"causes\":[{\"message\":\"spec.template.spec.networks.resource in body is a forbidden property\"},{\"message\":\"spec.template.spec.networks.name in body is required\"},{\"message\":\"spec.template.spec.volumes.name in body is required\"},{\"message\":\"spec.template.spec.domain.devices.disks.name in body is required\"},{\"message\":\"spec.template.spec.domain.devices.interfaces.name in body is required\"}]},\"code\":422}\n", 
```

> @machacekondra I also wonder what would be the output with template_parameter taking name and kubevirt_vm also asking it (what if different). Same confusion around namespace and resources, template would have a value and kubevirt_vm can also be given those values.

That's good question. We first take VM template parameters, then Ansible parameters. So Ansible parameter has higher prio.

**Comment by vatsalparekh** [comment]
> How does your template look like? As error says you miss following there:
```
    - name: Create a VM from the template created
      kubevirt_vm:
        name: test-template-vm
        namespace: default
        template: "{{ template_name }}"
        template_parameters:
          name: test-vm```
> 
> ```
>     "msg": "Failed to create object: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"admission webhook \\\"virtualmachine-validator.kubevirt.io\\\" denied the request: spec.template.spec.networks.resource in body is a forbidden property, spec.template.spec.networks.name in body is required, spec.template.spec.volumes.name in body is required, spec.template.spec.domain.devices.disks.name in body is required, spec.template.spec.domain.devices.interfaces.name in body is required\",\"reason\":\"Invalid\",\"details\":{\"causes\":[{\"message\":\"spec.template.spec.networks.resource in body is a forbidden property\"},{\"message\":\"spec.template.spec.networks.name in body is required\"},{\"message\":\"spec.template.spec.volumes.name in body is required\"},{\"message\":\"spec.template.spec.domain.devices.disks.name in body is required\"},{\"message\":\"spec.template.spec.domain.devices.interfaces.name in body is required\"}]},\"code\":422}\n", 
> ```
> > @machacekondra I also wonder what would be the output with template_parameter taking name and kubevirt_vm also asking it (what if different). Same confusion around namespace and resources, template would have a value and kubevirt_vm can also be given those values.
> 
> That's good question. We first take VM template parameters, then Ansible parameters. So Ansible parameter has higher prio.
so the `template_parameters` will be neglected if there's similar parameters passed in the task or with module defaults?

**Comment by vatsalparekh** [comment]
And the template
```
      kubevirt_template:
        state: present
        name: "{{ template_name }}"
        namespace: default
        display_name: Generic cirros template
        description: Basic cirros template
        long_description: Verbose description of cirros template
        provider_display_name: Just Be Cool, Inc.
        documentation_url: http://theverycoolcompany.com
        support_url: http://support.theverycoolcompany.com
        icon_class: icon-linux
        default_disk:
          disk:
            bus: virtio
        default_nic:
          model: virtio
        default_network:
          resource:
            resourceName: bridge.network.kubevirt.io/cnvmgmt
        default_volume:
          containerDisk:
            image: kubevirt/cirros-container-disk-demo
        objects:
          - name: ${NAME}
            kind: VirtualMachine
            memory: ${MEMORY_SIZE}
            state: present
            namespace: vms
        parameters:
          - name: NAME
            description: VM name
            generate: expression
            from: 'vm-[A-Za-z0-9]{8}'
          - name: MEMORY_SIZE
            description: Memory size
            value: 2Gi
```
