### ISSUE TITLE
with_items in wrong order over multiple hosts

### ISSUE THREAD

**Issue by samragu** [ansible/ansible#54909]
##### SUMMARY
with_items on a list having a sub-list runs in wrong order on a second host

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
with_items include_role 

##### ANSIBLE VERSION

```paste below
ansible 2.7.5
  config file = /home/xxxx/bug/ansible.cfg
  configured module search path = [u'/home/xxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/xxxx/bug/ansible.cfg) = [u'/home/xxxx/bug/hosts']

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

Run attached playbook

```yaml
bug.yml
---

- name: Bug
  hosts: all

  tasks:
    - file:
        path: /tmp/{{ inventory_hostname }}
        state: absent
    - file:
        path: /tmp/{{ inventory_hostname }}
        state: touch
    - include_role:
        name: bug
      vars:
        bugItem: "{{ item }}"
      with_items:
        - "{{ children }}"

hosts
---

[groupA]
hostA ansible_host=localhost ansible_connection=local

[groupB]
hostB ansible_host=localhost ansible_connection=local

roles/bug/tasks/main.yml
---

- name: Append to file
  lineinfile:
    path: /tmp/{{ inventory_hostname }}
    line: "{{ bugItem.name }}"

group_vars/all
---

children:
  - name: one
    grandchildren:
      - name: "{{ hello.world }}"
      - name: "{{ hello.world }}"

  - name: two
    grandchildren:
      - name: "{{ hello.world }}"

  - name: three
    grandchildren:
      - name: "{{ hello.world }}"

  - name: four

  - name: five

  - name: six

  - name: seven

group_vars/groupA
---

hello:
  world: A

group_vars/groupB
---

hello:
  world: B


```

##### EXPECTED RESULTS

When each host is run individually, for example,
ansible-playbook -l hostA bug.yml, it produces a /tmp/hostA file with contents
one
two
three
four
five
six
seven

but when both hosts are included, for example,
ansible-playbook -l hostA,hostB bug.yml

one of the file has correct order while the other file has incorrect order
four
five
six
seven
one
two
three

##### ACTUAL RESULTS

```paste below
PLAY [Bug] ******************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************
ok: [hostA]
ok: [hostB]

TASK [file] *****************************************************************************************************************************************
changed: [hostB]
changed: [hostA]

TASK [file] *****************************************************************************************************************************************
changed: [hostB]
changed: [hostA]

TASK [include_role : bug] ***************************************************************************************************************************

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]
changed: [hostA]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]
changed: [hostA]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]
changed: [hostA]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostB]
changed: [hostA]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostA]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostA]

TASK [bug : Append to file] *************************************************************************************************************************
changed: [hostA]

PLAY RECAP ******************************************************************************************************************************************
hostA                      : ok=10   changed=9    unreachable=0    failed=0
hostB                      : ok=10   changed=9    unreachable=0    failed=0

```
