### ISSUE TITLE
Chroot execution

### ISSUE THREAD

**Issue by renard** [ansible/ansible#5491]
I found #2106, this is a great module.

Is there a way to combine chroot with ssh? I mean is it possible to configure chroots on a remote host?

I aim to create chroots for severe purposes on many remote hosts and deploying ansible on each hosts is not an option.

For the moment I trick using something like:

```
- name: install packages in chroot
  shell:
    "chroot /srv/bases/{{ item.vendor }}-{{ item.release }}-{{ item.arch }} apt-get install -y --force-yes foo bar"
  with_items:
    - vendor: 'ubuntu'
      release: 'saucy'
      arch: 'amd64'
      components: restricted universe multiverse
```

And of course it would be more handy I one can define an option to an action such as

```
- name: install packages in chroot
  apt: pkg={{ item[1] }}
  with_nested:
    - vendor: 'ubuntu'
      release: 'saucy'
      arch: 'amd64'
      components: restricted universe multiverse
    - [ foo, bar ]
  chroot: /srv/bases/{{ item[0].vendor }}-{{ item[0].release }}-{{ item[0].arch }}
```
