### ISSUE TITLE
become_method isn't honored 

### ISSUE THREAD

**Issue by stephenl03** [ansible/ansible#54919]
##### SUMMARY
If the method of escalating is defined in the inventory file, ansible does not respect the become_method on the command line or in the playbook

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
become_method

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<REDACTED>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<REDACTED>/.local/lib/python3.7/site-packages/ansible
  executable location = /home/<REDACTED>/.local/bin/ansible
  python version = 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOLOR(/etc/ansible/ansible.cfg) = False
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o IdentitiesOnly=yes -o PasswordAuthentication=yes -o ProxyCommand="ssh -A <REDACTED> 'nc %h %p'"
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = ~/.ssh/master-%r@%h:%p
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = 
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Host: Fedora 29
Target: Ubuntu16.04, RedHat 7.6

##### STEPS TO REPRODUCE
ansible inventory file with `ansible_become_method=su` defined in it

ansible all -i inventory --become --become-method=sudo -m command -a "whoami" -vvv

```yaml
- name: test repo
  hosts: all
  become: no
  tasks:
  - name: through inventory, become no
    shell: "whoami; echo {{ ansible_become_method }}"

  - name: through inventory, become yes
    shell: "whoami; echo {{ ansible_become_method }}"
    become: yes

  - name: sudo through become_method
    shell: "whoami; echo {{ ansible_become_method }}"
    become_method: sudo
    become: yes

  - name: sudo through override become_method
    shell: "whoami; echo {{ ansible_become_method }}"
    vars:
      ansible_become_method: sudo
    become: yes
    ignore_errors: yes

  - name: sudo through override become_method and become_password
    shell: "whoami; echo {{ ansible_become_method }}"
    vars:
      ansible_become_method: sudo
      ansible_become_pass: "{{ ansible_ssh_pass }}"
    become: yes
```

##### EXPECTED RESULTS
task should be executed with sudo instead of su when `become_method: sudo` is used.

##### ACTUAL RESULTS
In the verbose output you can see the command being executed will contain...
```
'/bin/sh -c '"'"'su  root -c '"'"'"'"'"'"'"'"'...
```
