### ISSUE TITLE
dnf: successful etckeeper commit causes successful package install to fail

### ISSUE THREAD

**Issue by westurner** [ansible/ansible#54949]
##### SUMMARY

When etckeeper commits, dnf package installs (that are successfully installed) fail.
It may be due to the etckeeper output preceding dnf output?

Workarounds:
1. in `/etc/etckeeper/etckeeper.conf`, set `GIT_OPTIONS="-q"`
   - This is suboptimal, because I generally want to see the git output when running `etckeeper commit` (and in the ansible logs, TBH)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnf module

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]

```

##### CONFIGURATION

```paste below
.
```

##### OS / ENVIRONMENT

- Fedora 29
- dnf: 4.2.2
- etckeeper: 1.18.8

##### STEPS TO REPRODUCE

- Install etckeeper: `package: name=etckeeper`
- Modify a file in /etc: ``echo "TestTest" | sudo tee /etc/README.md``
- Install a package: `package: name=ctags-etags`
- Error: 

```yaml
- package: name=etckeeper
- command: etckeeper init
- command: etckeeper commit "Initial etckeeper commit by ansible"
```

```bash
echo "TestTest" | sudo tee /etc/README.md
```

```yaml
- package: name=ctags-etags
```

##### EXPECTED RESULTS

-  `package: name=ctags-etags` installs successfully

##### ACTUAL RESULTS

- `package: name=ctags-etags` does not install

```paste below
fatal: [node1]: FAILED! => {"changed": false,

 "module_stderr":
 "~/.ansible/tmp/ansible-tmp-1554590827.5738285-108733131594711/AnsiballZ_dnf.py:17:
 DeprecationWarning: the imp module is deprecated in favour of
 importlib; see the module's documentation for alternative uses\n
 import imp\n",

 "module_stdout": "[master 2151996] saving uncommitted changes in /etc
 prior to dnf run\n Author: Wes Turner <~>\n 1 file changed, 1
 insertion(+)\n\n{\"msg\": \"Nothing to do\", \"changed\": false,
 \"results\": [\"Installed: libX11-xcb\", \"Installed: which\"], \"rc\":
 0, \"invocation\": {\"module_args\": {\"name\": [\"libX11-xcb\",
 \"which\"], \"state\": \"present\", \"allow_downgrade\": false,
 \"autoremove\": false, \"bugfix\": false, \"disable_gpg_check\": false,
 \"disable_plugin\": [], \"disablerepo\": [], \"download_only\": false,
 \"enable_plugin\": [], \"enablerepo\": [], \"exclude\": [],
 \"installroot\": \"/\", \"install_repoquery\": true, \"security\":
 false, \"skip_broken\": false, \"update_cache\": false,
 \"update_only\": false, \"validate_certs\": true, \"conf_file\": null,
 \"disable_excludes\": null, \"list\": null, \"releasever\": null}}}\n",
 "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc":
 0}

```

**Comment by westurner** [comment]
Here's all this, which isnt really necessary:

```yaml
---
# playbook.yml
- hosts: all
  name: Install etckeeper
  tags: ['etckeeper']
  become: true
  roles:
  - role: etckeeper
    tags: ['etckeeper']

```

```yaml
---
# tasks file for etckeeper

- name: Load etckeeper-pre-task and etckeeper-post-task action_plugins
  import_role:
    name: hlovdal.etckeeper_actions
  tags: ['etckeeper']

- name: Install etckeeper
  tags: [etckeeper]
  become: true
  block:

  - name: Check for /etc/.git and etckeeper
    shell: test -d "/etc/.git" && test -e /usr/bin/etckeeper
    ignore_errors: true
    failed_when: etckeeper.rc > 1
    changed_when: etckeeper.rc > 1
    register: etckeeper

  - etckeeper-pre-task:
    when:
    - etckeeper.rc == 0

  - name: Install etckeeper package
    package:
      name: etckeeper

  - name: Configure etckeeper.conf
    lineinfile:
      path: /etc/etckeeper/etckeeper.conf
      regexp: '^GIT_COMMIT_OPTIONS=.*'
      line: 'GIT_COMMIT_OPTIONS="-q"'

  - name: Run etckeeper init
    command: etckeeper init
    args:
      creates: "/etc/.git"
    register: etckinit

  - name: Check git user
    command: git config --local --get user.name
    failed_when: gituser.rc > 1
    changed_when: gituser.rc > 1
    register: gituser

  - name: Check git email
    command: git config --local --get user.email
    failed_when: gitemail.rc > 1
    changed_when: gitemail.rc > 1
    register: gitemail

  - name: Set git user if not set
    command: git config --add user.name Root
    when: gituser.rc != 0

  - name: Set git email if not set
    command: git config --add user.email root@localhost
    when: gitemail.rc != 0

  #- name: Check whether there are uncommited etckeeper entries
  #  command: etckeeper unclean
  #  failed_when: etck.rc > 1
  #  changed_when: etck.rc == 0
  #  register: etck

  - name: Create initial etckeeper commit
    command: etckeeper commit "Initial commit by ansible"
    when: etckinit.changed == true

  #- name: Commit uncommited changes in /etc with etckeeper
  #  command: etckeeper commit "Commit uncommitted by ansible"
  #  when:
  #  - etck.rc == 0
  #  - etckinit.changed == false

  - etckeeper-post-task:
```
