### ISSUE TITLE
DynamoDB on-demand mode now

### ISSUE THREAD

**Issue by a-da** [ansible/ansible#54963]
There is a new option now, like "on-demand"  write_capacity and read_capacity.

DynamoDB on-demand is available globally in all commercial regions., they're telling in their announcement: https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/

Based on this issue from SAM https://github.com/serverless/serverless/issues/5535 

There is no such option here yet https://docs.ansible.com/ansible/latest/modules/dynamodb_table_module.html.

```yaml
- dynamodb_table:
    name: my-table
    region: us-east-1
    hash_key_name: id
    hash_key_type: STRING
    range_key_name: create_time
    range_key_type: NUMBER

    BillingMode: PAY_PER_REQUEST
    #read_capacity: 2
    #write_capacity: 2
    
    tags:
      tag_name: tag_valu
```
