### ISSUE TITLE
missing deprecation guide for boolean conditionals 

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#54996]
##### SUMMARY
I started getting warnings on conditionals where I use booleans
```
[DEPRECATION WARNING]: evaluating teardown as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature
will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Talking to @sivel it seems that when evaluating booleans with Ansible conditionals (the when parameter) we are now advising Ansible users to always use bool evaluations by using the `|bool` parameter .  This is because in certain cases the boolean is evaluating incorrectly when dealing with strings.  The `|bool` will enforce that the conditional always follows the correct logic.  There is several issues where this comes up

Issue where a problem occurded before we made this deprecation: https://github.com/ansible/ansible/issues/34591
PR is here: https://github.com/ansible/ansible/pull/51030

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
conditional ```when:```

##### ANSIBLE VERSION
```paste below
ansible 2.8.0a1.post0
  config file = /Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION
```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = [u'time']
DEFAULT_FORKS(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = [u'/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = yaml
HOST_KEY_CHECKING(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = False
SHOW_CUSTOM_STATS(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = True
```

##### OS / ENVIRONMENT
macOS

##### ADDITIONAL INFORMATION
here is an example of both
```
- include_tasks: teardown.yml
  when: teardown|bool

- name: provision workshop in AWS public cloud
  block:
    - name: provision aws resources and instances
      include_tasks: provision.yml
      tags: provisioned

    - name: create instructor_inventory, and student files
      include_tasks: create_inventory.yml
  when: not teardown|bool
```
