### ISSUE TITLE
ec2 module count_tag throws warning for type dict

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#55007]
##### SUMMARY
I am getting a warning on dev branch of ansible

```
TASK [manage_ec2_instances : Create EC2 instances for ansible node (control node)] *********************************************************************************************************************************************
 [WARNING]: The value {'Workshop_ansible': 'JUNIPER-TEST-ansible'} (type dict) in a string field was converted to u"{'Workshop_ansible': 'JUNIPER-TEST-ansible'}" (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION

```paste below
ansible 2.8.0a1.post0
  config file = /Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = [u'time']
DEFAULT_FORKS(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = [u'/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = yaml
HOST_KEY_CHECKING(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = False
SHOW_CUSTOM_STATS(/Users/sean/Documents/GitHub/IPvSean/linklight-local/provisioner/ansible.cfg) = True
```

##### OS / ENVIRONMENT
MacOS Mojave 10.14.3

##### STEPS TO REPRODUCE

```yaml
- name: Create EC2 instances for ansible node (control node)
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[control_type].size }}"
    image: "{{ ansible_control_node_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_ansible: "{{ec2_name_prefix}}-ansible"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[control_type].disk_space }}"
        delete_on_termination: true
  register: control_output
```

##### EXPECTED RESULTS
no warning

##### ACTUAL RESULTS

```paste below
 [WARNING]: The value {'Workshop_ansible': 'JUNIPER-TEST-ansible'} (type dict) in a string field was converted to u"{'Workshop_ansible': 'JUNIPER-TEST-ansible'}" (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
```
