### ISSUE TITLE
ec2_key module returns warning unless you explicitly set string timeout 

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#55005]
##### SUMMARY
on latest dev branch started getting warnings on the ec2_key module

```
 [WARNING]: The value 300 (type int) in a string field was converted to u'300' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_key

##### ANSIBLE VERSION

```paste below
ansible 2.8.0a1.post0
  config file = /Users/sean/.ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/Users/sean/.ansible.cfg) = yaml
```

##### OS / ENVIRONMENT
MacOS Mojave 10.14.3

##### STEPS TO REPRODUCE
run this->

```yaml
- name: Create ssh key pair for workshop {{ ec2_name_prefix }}
  ec2_key:
    name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
  register: create_key
```

##### EXPECTED RESULTS
no warning

##### ACTUAL RESULTS

```paste below
 [WARNING]: The value 300 (type int) in a string field was converted to u'300' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```
