### ISSUE TITLE
python API problem with module telnet

### ISSUE THREAD

**Issue by baseman2** [ansible/ansible#55018]
##### SUMMARY

I'm trying to telnet command with python API.
I succeed telnet module with playbook yml.
But with python, I cannot run telnet module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

telnet

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: show version
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
          - name: showversion_task
            telnet:
                    host: "{{ host }}"
                    user: "{{ username }}"
                    password: "{{ password }}"
                    login_prompt: "TACACS username: "
                    password_prompt: "TACACS password: "
                    prompts:
                            - "#$"
                    command:
                            - terminal length 0
                            - show version
            register: data

          - debug: var=data.output
```
    play_source = dict(
            name = "show version",
            hosts = 'localhost',
            connection = 'local',
            gather_facts = 'no',
            tasks = [
                dict(action=dict(module='telnet', host=ip, user=con_id, password=con_passwd, login_prompt="TACACS username: ", password_prompt="TACACS password: ", prompts="#$", command="terminal length 0"), register='data'),
                dict(action=dict(module='debug', args=dict(var='{{data.output}}')))
            ]
        )

##### ACTUAL RESULTS

```paste below
localhost | FAILED! => {
    "changed": true, 
    "msg": "Telnet requires a command to execute"
}
```
