### ISSUE TITLE
docker_swarm_service: Add support for only updating specified parameters

### ISSUE THREAD

**Issue by hannseman** [ansible/ansible#55010]
##### SUMMARY

This issue is created to continue the discussion in the closed PR https://github.com/ansible/ansible/pull/54960. 

Currently `docker_swarm_service` will replace unspecified parameters with default values when run. This means that if a parameter have been updated outside of Ansible by using for example `docker service update` it will be overwritten by a docker default value if not specified in the task.

This feature request asks the functionality to be able to declare that the task should only update the parameters that have been specified in the Ansible task. One use-case for this could be to have a lightweight task to only update the `image` parameters without having to run dependant taks like `docker_secret` and `docker_config` to get ids to set on the service.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_swarm_service

##### ADDITIONAL INFORMATION

One use-cause could be the above described lightweight task which only updates `image` by setting `state` to a new option called `updated`.

```yaml
- name: Example service creation
  docker_swarm_service:
    name: myservice
    image: alpine:3.8
    state: present
    update_config:
      failure_action: rollback
    rollback_config:
      parallelism: 2
      delay: 10s
      order: stop-first
```

```yaml
- name: Example image update
  docker_swarm_service:
    name: myservice
    image: alpine:latest
    resolve_image: yes
    state: updated
```

After running "Example image update" the service would still have `update_config` and `rollback_config` set to the values specified in the previous task.

Implementing this feature would probably end up being pretty complex as it would need to handle merging of nested data structures. As described in https://github.com/ansible/ansible/pull/54960 using the docker-py argument `fetch_current_spec` in [docker.api.service.ServiceApiMixin.update_service](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.service.ServiceApiMixin.update_service) is not suitable as it does not handle individual attributes in the Docker API object types.
