### ISSUE TITLE
Interpreter discovery should ignore network devices

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#55014]
##### SUMMARY
The new 2.8 interpreter discovery feature could potentially add spurious warning noise when the controller is run on platforms without a well-known platform Python (eg, Mac, Fedora with /usr/bin/python present). Interpreter discovery should be disabled on known network devices (by some heuristic TBD, like presence of `ansible_network_os` or ?), since the interpreter used to run networking modules should always be inherited from the controller.

Also still TBD is if this is an issue with actual networking modules, or only when running "normal" Ansible modules against the controller on behalf of the network device. eg, in this case, if we made `wait_for_connection` work right for networking devices, the problem would probably go away.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
BaseAction

##### ANSIBLE VERSION
2.8.0a1

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
MacOS, recent-ish Fedora with /usr/bin/python present, etc

##### STEPS TO REPRODUCE

```
- hosts: localhost
  gather_facts: no
  tasks:
  - add_host:
      name: yourmom
      groups: [newgrp]
      ansible_host: 127.0.0.1
      ansible_network_os: eos  # simulating a network device

- hosts: newgrp
  gather_facts: no
  tasks:
  - wait_for:
      host: '{{ ansible_host }}'
      timeout: 400
      port: 22
    vars:
      ansible_connection: local

```

Running the above playbook on a Mac or other platform that triggers interpreter discovery warnings will cause those warnings to fire for networking devices the first time a module is run, even though the actual interpreter will always be inherited from Ansible.

##### EXPECTED RESULTS

No interpreter discovery warnings on network devices

##### ACTUAL RESULTS
Interpreter discovery warnings for each host, eg:
