### ISSUE TITLE
Module kubernetes does not support networkpolicy

### ISSUE THREAD

**Issue by stearz** [ansible/ansible#55020]
##### SUMMARY

The ansible module 'kubernetes' does not support objects with 'kind: NetworkPolicy'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

kubernetes

##### ANSIBLE VERSION

```paste below
2.7.8
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1800s -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible-custom/callback']
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'timer', u'mail', u'influxdb']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible-custom/lookup_plugins']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible-custom/modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible-custom/module_utils']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = ~/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = smart
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = default
DEFAULT_STRATEGY(/etc/ansible/ansible.cfg) = linear
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

AmazonLinux

##### STEPS TO REPRODUCE

I have this yaml definition of a NetworkPolicy that should be applied to my kubernetes cluster:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkpolicy-rest-api
  namespace: myApplication
spec:
  podSelector:
    matchLabels:
      app: rest-api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace: ingress
    - podSelector:
        matchLabelss:
          app: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
```
Here is the ansible task definition:

```yaml
- name: creating networkpolicy
  delegate_to: localhost
  kubernetes:
    api_endpoint: "{{ k8s_api_endpoint }}"
    validate_certs: false
    url_username: "{{ k8s_api_username }}"
    url_password: "{{ k8s_api_password }}"
    file_reference: "{{ item }}"
    state: present
  with_items:
   - networkpolicy.yml
```

##### EXPECTED RESULTS

It should work

##### ACTUAL RESULTS

I am getting this error:

```paste below
failed: [localhost -> localhost] (item=networkpolicy.yml) => {"changed": false, "item": "networkpolicy.yml", "msg": "invalid resource kind specified in the data: 'networkpolicy'"}
```
