### ISSUE TITLE
proxmox_kvm cannot create a VM with ostype=win10

### ISSUE THREAD

**Issue by jrjsmrtn** [ansible/ansible#55045]
##### SUMMARY
Creating a VM with the `proxmox_kvm` module and an `ostype: "win10"` fails with:
```
value of ostype must be one of: other, wxp, w2k, w2k3, w2k8, wvista, win7, win8, l24, l26, solaris, got: win10
```

The `ostype` default list is hard-coded in the `ansible/lib/ansible/modules/cloud/misc/proxmox_kvm.py` module at line 831 but has not been updated for recent versions of Proxmox.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.7.10
  config file = /home/gmartin/Projects/ansible-pdp/etc/ansible.cfg
  configured module search path = [u'/home/gmartin/Projects/ansible-pdp/library']
  ansible python module location = /home/gmartin/.virtualenvs/ansible-pdp/local/lib/python2.7/site-packages/ansible
  executable location = /home/gmartin/.virtualenvs/ansible-pdp/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```
CACHE_PLUGIN(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = $HOME/.ansible/facts/
CACHE_PLUGIN_TIMEOUT(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = 3600
DEFAULT_ACTION_PLUGIN_PATH(env: ANSIBLE_ACTION_PLUGINS) = [u'/home/gmartin/.virtualenvs/ansible-pdp/local/lib/python2.7/site-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = [u'/home/gmartin/.virtualenvs/ansible-pdp/local/lib/python2.7/site-packages/ara/plugins/callbacks']
DEFAULT_FILTER_PLUGIN_PATH(env: ANSIBLE_FILTER_PLUGINS) = [u'/home/gmartin/Projects/ansible-pdp/plugins/filter']
DEFAULT_GATHERING(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = smart
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/gmartin/Projects/ansible-pdp/inventories/Z11', u'/home/gmartin/Projects/ansible-pdp/inventories/setupenv']
DEFAULT_LOG_PATH(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = /home/gmartin/.ansible/log/ansible.log
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/gmartin/Projects/ansible-pdp/library']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/home/gmartin/Projects/ansible-pdp/roles.galaxy', u'/home/gmartin/Projects/ansible-pdp/roles']
DEFAULT_STDOUT_CALLBACK(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = yaml
GALAXY_ROLE_SKELETON(env: ANSIBLE_GALAXY_ROLE_SKELETON) = /home/gmartin/Projects/ansible-pdp/etc/skel/default
HOST_KEY_CHECKING(/home/gmartin/Projects/ansible-pdp/etc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
* The Ansible controller:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ python --version
Python 2.7.13

$ python -c 'import proxmoxer; print proxmoxer.__version__'
1.0.3
```

* The Promox server:
```
# pveversion
pve-manager/5.2-10/6f892b40 (running kernel: 4.15.18-7-pve)
```

##### STEPS TO REPRODUCE

Execute a `promox_kvm` task with an `ostype: "win10"` parameter.

```yaml
- name: provision VM                                               
  proxmox_kvm:                                                     
    api_host: "{{ api_host }}"                                     
    api_user: "{{ api_user }}"                                     
    api_password: "{{ api_password }}"                             
    validate_certs: "{{ validate_certs }}"                         
    node: "{{ pve_node }}"                                         
                                                                   
    name: "{{ ansible_host }}"                                     
    pool: "{{ pool_id }}"
    description: "{{ description }}"    
    net: "{{ net }}"                                                                           
    balloon: "{{ balloon   }}"     
    cores: "{{ cores }}"       
    ide: "{{ ide }}"         
    memory: "{{ memory }}"      
    ostype: "{{ ostype }}"      
    scsi: "{{ scsi }}"        

  vars:
    api_host: ANONIMIZED
    api_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
    api_user: root@pam
    balloon: 1024
    cores: 2
    description: ANONIMIZED.ANONIMIZED.org in ANONIMIZED
    ide:
      ide2: none,media=cdrom
    memory: 4096
    name: ANONIMIZED.ANONIMIZED.org
    net:
      net0: virtio,bridge=vmbr11001
    node: ANONIMIZED
    ostype: win10
    pool_id: ANONIMIZED
    scsi:
      scsi0: ANONIMIZED:32,format=qcow2
    validate_certs: false
                                                                   
    state: present                                                 
  delegate_to: localhost                                           
```

##### EXPECTED RESULTS

The VM to be created in Promox with a "Windows 10" OS Type.

##### ACTUAL RESULTS

```paste below
TASK [vptc-pve-vm : provision VM] *************************************************************************************************************************************************************************
task path: /home/gmartin/Projects/ansible-pdp/roles/vptc-pve-vm/tasks/provision.yml:36
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: gmartin
<localhost> EXEC /bin/sh -c 'echo ~gmartin && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797 `" && echo ansible-tmp-1554823062.3-67946788860797="` echo /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797 `" ) && sleep 0'
Using module file /home/gmartin/.virtualenvs/ansible-pdp/local/lib/python2.7/site-packages/ansible/modules/cloud/misc/proxmox_kvm.py
<localhost> PUT /home/gmartin/.ansible/tmp/ansible-local-25868B9gfae/tmpVlu50S TO /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797/AnsiballZ_proxmox_kvm.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797/ /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797/AnsiballZ_proxmox_kvm.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/gmartin/.virtualenvs/ansible-pdp/bin/python /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797/AnsiballZ_proxmox_kvm.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/gmartin/.ansible/tmp/ansible-tmp-1554823062.3-67946788860797/ > /dev/null 2>&1 && sleep 0'
fatal: [controltools -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      acpi: true
      api_host: ANONIMIZED
      api_password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      api_user: root@pam
      autostart: false
      balloon: 1024
      boot: cnd
      cores: 2
      cpu: kvm64
      cpuunits: 1000
      description: ANONIMIZED.ANONIMIZED.org in ANONIMIZED
      format: qcow2
      full: true
      ide:
        ide2: none,media=cdrom
      kvm: true
      memory: 4096
      name: ANONIMIZED.ANONIMIZED.org
      net:
        net0: virtio,bridge=vmbr11001
      node: rndpxmx3
      onboot: true
      ostype: win10
      pool: vptc11
      scsi:
        scsi0: ANONIMIZED:32,format=qcow2
      sockets: 1
      state: present
      tablet: false
      template: false
      timeout: 30
      update: false
      validate_certs: false
      vga: std
  msg: 'value of ostype must be one of: other, wxp, w2k, w2k3, w2k8, wvista, win7, win8, l24, l26, solaris, got: win10'
        to retry, use: --limit @/home/gmartin/Projects/ansible-pdp/playbooks/provision-pve-vptc-vm.retry
```
