### ISSUE TITLE
xml's "print_matches" misdocumented

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#55051]
##### SUMMARY
The [documentation of the XML-module](https://docs.ansible.com/ansible/latest/modules/xml_module.html) is incorrect about the `matches` and `print_matches` parts:
1. When `print_matches` is set, the `matches` part of the returned dict may be empty, even when the matches are found.
2. Even when the `print_matches` is _not_ set, the `matches` part may be returned -- not empty -- when the `content` is requested, contrary to the documentation.
3. No (documented) way to get the entire element matched by the `xpath`-expression. Neither as YAML, nor as XML...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```
ansible 2.7.9
  config file = /mi/A/ansible.cfg
  configured module search path = ['/mi/.ansible/plugins/modules', '/opt/share/py36-ansible/plugins/modules']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.8 (default, Mar 27 2019, 23:58:03) [GCC 4.2.1 Compatible FreeBSD Clang 7.0.1 (tags/RELEASE_701/final 349250)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/mi/A/ansible.cfg) = -q -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=/tmp/ansible-ssh-%h-%p-%r
CACHE_PLUGIN(/mi/A/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/mi/A/ansible.cfg) = /tmp/afacts
DEFAULT_FORKS(/mi/A/ansible.cfg) = 61
DEFAULT_TIMEOUT(/mi/A/ansible.cfg) = 23
HOST_KEY_CHECKING(/mi/A/ansible.cfg) = False
```

##### OS / ENVIRONMENT

FreeBSD

##### STEPS TO REPRODUCE

Run the below mini-playbook as `ansible-playbook t.yml`

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create test XML
    set_fact:
      xml: >-
        <?xml version='1.0' encoding='US-ASCII'?>
        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <html xmlns:html="http://www.w3.org/1999/xhtml">
        <head><title>Listing of environment details</title></head>
        <body>
        	<table class="envlist" border="1">
        		<caption>Meow</caption>
        		<TR class="envrow"><TH class="first">Uno</TH><TD class="second">Dos</TD></TR>
        		<TR class="envrow"><TD class="second">Dos</TD></TR>
        	</table>
        </body>
        </html>
  
  - name: Search for "envrow"
    xml:
      xmlstring: "{{ xml }}"
      xpath: '//*[@class = "envrow"]'
      print_match: "{% if item %}true{% else %}{{ omit }}{% endif %}"
      content: "{% if item %}{{ omit }}{% else %}text{% endif %}"
      namespaces:
        html: 'http://www.w3.org/1999/xhtml'
    register: counts
    loop:
    - true
    - false

  - debug: var=counts
```

##### EXPECTED RESULTS
1. When `print_matches` is set, I expect the _non-empty_ `matches` list in the result -- instead it kinda-sorta appears in the `msg` string.
1. When `print_matches` is omitted, I expect there to be no `matches` list in the result _at all_, because documentation says so.
1. If the matches are listed -- which makes sense, since I do request `content: text` -- the values for each TR should not be `null`, in my opinion. I'm trying to get the entire rows so as to be able to manipulate them further...

##### ACTUAL RESULTS

Though the matches were found -- and are listed in `msg`, the actual `matches` part is empty:
```json
ok: [localhost] => {
    "counts": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": true,
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "actions": {
                    "namespaces": {
                        "html": "http://www.w3.org/1999/xhtml"
                    },
                    "state": "present",
                    "xpath": "//*[@class = \"envrow\"]"
                },
                "changed": false,
                "failed": false,
                "invocation": {
                    "module_args": {
                        "add_children": null,
                        "attribute": null,
                        "backup": false,
                        "content": null,
                        "count": false,
                        "input_type": "yaml",
                        "namespaces": {
                            "html": "http://www.w3.org/1999/xhtml"
                        },
                        "path": null,
                        "pretty_print": false,
                        "print_match": true,
                        "set_children": null,
                        "state": "present",
                        "strip_cdata_tags": false,
                        "value": null,
                        "xmlstring": "<?xml version='1.0' encoding='US-ASCII'?> <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> <html xmlns:html=\"http://www.w3.org/1999/xhtml\"> <head><title>Listing of environment details</title></head> <body>\n\t<table class=\"envlist\" border=\"1\">\n\t\t<caption>Meow</caption>\n\t\t<TR class=\"envrow\"><TH class=\"first\">Uno</TH><TD class=\"second\">Dos</TD></TR>\n\t\t<TR class=\"envrow\"><TD class=\"second\">Dos</TD></TR>\n\t</table>\n</body> </html>",
                        "xpath": "//*[@class = \"envrow\"]"
                    }
                },
                "item": true,
                "matches": [],
                "msg": "selector '//*[@class = \"envrow\"]' match: [\"/html/body/table/TR[1]\", \"/html/body/table/TR[2]\"]",
                "xmlstring": "<?xml version='1.0' encoding='UTF-8'?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns:html=\"http://www.w3.org/1999/xhtml\"> <head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><title>Listing of environment details</title></head> <body>\n\t<table class=\"envlist\" border=\"1\">\n\t\t<caption>Meow</caption>\n\t\t<TR class=\"envrow\"><TH class=\"first\">Uno</TH><TD class=\"second\">Dos</TD></TR>\n\t\t<TR class=\"envrow\"><TD class=\"second\">Dos</TD></TR>\n\t</table>\n</body> </html>"
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_label": false,
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "actions": {
                    "namespaces": {
                        "html": "http://www.w3.org/1999/xhtml"
                    },
                    "state": "present",
                    "xpath": "//*[@class = \"envrow\"]"
                },
                "changed": false,
                "count": 2,
                "failed": false,
                "invocation": {
                    "module_args": {
                        "add_children": null,
                        "attribute": null,
                        "backup": false,
                        "content": "text",
                        "count": false,
                        "input_type": "yaml",
                        "namespaces": {
                            "html": "http://www.w3.org/1999/xhtml"
                        },
                        "path": null,
                        "pretty_print": false,
                        "print_match": false,
                        "set_children": null,
                        "state": "present",
                        "strip_cdata_tags": false,
                        "value": null,
                        "xmlstring": "<?xml version='1.0' encoding='US-ASCII'?> <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> <html xmlns:html=\"http://www.w3.org/1999/xhtml\"> <head><title>Listing of environment details</title></head> <body>\n\t<table class=\"envlist\" border=\"1\">\n\t\t<caption>Meow</caption>\n\t\t<TR class=\"envrow\"><TH class=\"first\">Uno</TH><TD class=\"second\">Dos</TD></TR>\n\t\t<TR class=\"envrow\"><TD class=\"second\">Dos</TD></TR>\n\t</table>\n</body> </html>",
                        "xpath": "//*[@class = \"envrow\"]"
                    }
                },
                "item": false,
                "matches": [
                    {
                        "TR": null
                    },
                    {
                        "TR": null
                    }
                ],
                "msg": 2,
                "xmlstring": "<?xml version='1.0' encoding='UTF-8'?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns:html=\"http://www.w3.org/1999/xhtml\"> <head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><title>Listing of environment details</title></head> <body>\n\t<table class=\"envlist\" border=\"1\">\n\t\t<caption>Meow</caption>\n\t\t<TR class=\"envrow\"><TH class=\"first\">Uno</TH><TD class=\"second\">Dos</TD></TR>\n\t\t<TR class=\"envrow\"><TD class=\"second\">Dos</TD></TR>\n\t</table>\n</body> </html>"
            }
        ]
    }
}
```
