### ISSUE TITLE
xml module's "ensure: present" always treats value as yaml

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#55112]
##### SUMMARY
Both `add_children` and `set_children`  allow the _children_ of the node to be given in XML -- depending on the `input_type`. It is quite inconsistent for `value` to not allow the same.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /mi/A/ansible.cfg
  configured module search path = ['/mi/.ansible/plugins/modules', '/opt/share/py36-ansible/plugins/modules']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.8 (default, Mar 27 2019, 23:58:03) [GCC 4.2.1 Compatible FreeBSD Clang 7.0.1 (tags/RELEASE_701/final
```

##### CONFIGURATION

```paste below
N/A
```

##### STEPS TO REPRODUCE
Trying to run the below playbook, I do get the new row inserted. Unfortunately, the provided XML is mangled, with the "<" and ">" replaced by "&amp;lt;" and "&amp;gt;" respectively.

Such conversion makes no sense for when `input_type` is set to "xml"...

Looking inside the `xml.py`, I see that the `children_to_nodes` function is prepared to handle `in_type` of "xml", it is never called with anything but "yaml", regardless of the specified `input_type`...

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create test XML
    set_fact:
      xml: >-
        <?xml version='1.0' encoding='US-ASCII'?>
        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <html xmlns:html="http://www.w3.org/1999/xhtml">
        <head><title>Listing of environment details</title></head>
        <body>
        	<table class="envlist" border="1">
        		<caption>Meow</caption>
        		<TR class="envrow" e="prod"><TH class="first">Uno</TH><TD class="second">Dos</TD></TR>
        		<TR class="envrow" e="dev"><TD class="second">Dos</TD></TR>
        	</table>
        </body>
        </html>

  - name: Insert a new row
    xml:
      xmlstring: "{{ xml }}"
      xpath: '//*[@class = "envlist"]/TR[@class="envrow" and @e="qa"]'
      ensure: present
      input_type: xml
      value: '<TR class="envrow" e=qa"><TD class="third">Tres</TD></TR>'
    register: ensured

  - debug: var=ensured
```

##### EXPECTED RESULTS

The third row (`TR`-element) inserted as such: `<TR ...`.

##### ACTUAL RESULTS
The row is inserted mangled: `&lt;TR ...`

```json
ok: [localhost] => {
    "ensured": {
        "actions": {
            "namespaces": {},
            "state": "present",
            "xpath": "//*[@class = \"envlist\"]/TR[@class=\"envrow\" and @e=\"qa\"]"
        },
        "changed": true,
        "failed": false,
        "xmlstring": "<?xml version='1.0' encoding='UTF-8'?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns:html=\"http://www.w3.org/1999/xhtml\"> <head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><title>Listing of environment details</title></head> <body>\n\t<table class=\"envlist\" border=\"1\">\n\t\t<caption>Meow</caption>\n\t\t<TR class=\"envrow\" e=\"prod\"><TH class=\"first\">Uno</TH><TD class=\"second\">Dos</TD></TR>\n\t\t<TR class=\"envrow\" e=\"dev\"><TD class=\"second\">Dos</TD></TR>\n\t<TR class=\"envrow\" e=\"qa\">&lt;TR class=\"envrow\" e=qa\"&gt;&lt;TD class=\"third\"&gt;Tres&lt;/TD&gt;&lt;/TR&gt;</TR></table>\n</body> </html>"
    }
}
```
+label: m:xml
+label: module
