### ISSUE TITLE
nios_zone Module: Field is not allowed for update: zone_format

### ISSUE THREAD

**Issue by digifuchsi** [ansible/ansible#55128]
##### SUMMARY
If you are using the Module to create a forward or reverse lookup zone the first run succeeds in a changed, but the second run throws an error "Field is not allowed for update: zone_format" even if the zone_format stays the same.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_network

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /srv/vmwareAsCode/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_CONTROL_PATH(/srv/ansible/ansible.cfg) = %(directory)s/%%h-%%r
DEFAULT_BECOME_METHOD(/srv/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/srv/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/srv/ansible/ansible.cfg) = [u'default', u'log_gitrepo']
DEFAULT_MANAGED_STR(/srv/ansible/ansible.cfg) = This file is managed by ansible, don't make changes here - they will be overwritten.
RETRY_FILES_ENABLED(/srv/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS 7.6
infoblox-client v0.4.21

##### STEPS TO REPRODUCE
Run task two times without changing the configuration

Task in role I am using
```yaml
- name: configure DNS zones
  delegate_to: localhost
  nios_zone:
    fqdn: "{{ item.fqdn }}"
    zone_format: '{{ item.format }}'
    comment: "{{ ansible_managed }}"
    state: present
    restart_if_needed: true
    provider:
      host: "{{ ansible_host }}"
      username: "{{ infoblox_username }}"
      password: "{{ infoblox_password }}"
      ssl_verify: false
  with_items:
    - '{{ infoblox_zones }}'
```

infoblox_zones var:
```yaml
infoblox_zones:
  - fqdn: '192.168.0.0/24'
    format: 'IPV4'
```

##### EXPECTED RESULTS
The first run of the task should return changed and all other runs should return ok.

##### ACTUAL RESULTS
The first run of the task returns changed and the second run throws a failed.

```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_nios_zone_payload_udgUOl/ansible_nios_zone_payload.zip/ansible/module_utils/net_tools/nios/api.py", line 185, in _invoke_method
    return method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/infoblox_client/connector.py", line 42, in callee
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/infoblox_client/connector.py", line 432, in update_object
    code=r.status_code)
 
failed: [sbdns01.sb.bka.bund.de -> localhost] (item={u'fqdn': u'192.168.0.0/24', u'format': u'IPV4'}) => {
    "changed": false,
    "code": "Client.Ibap.Proto",
    "invocation": {
        "module_args": {
            "comment": "This item is managed by ansible, do not make changes here - they will be overwritten.",
            "extattrs": null,
            "fqdn": "192.168.0.0/24",
            "grid_primary": null,
            "grid_secondaries": null,
            "ns_group": null,
            "provider": {
                "host": "10.0.0.5",
                "http_pool_connections": 10,
                "http_pool_maxsize": 10,
                "http_request_timeout": 10,
                "max_results": 1000,
                "max_retries": 3,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "silent_ssl_warnings": true,
                "ssl_verify": false,
                "username": "admin",
                "validate_certs": false,
                "wapi_version": "2.1"
            },
            "restart_if_needed": true,
            "state": "present",
            "view": "default",
            "zone_format": "IPV4"
        }
    },
    "item": {
        "format": "IPV4",
        "fqdn": "192.168.0.0/24"
    },
    "msg": "Field is not allowed for update: zone_format",
    "operation": "update_object",
    "type": "AdmConProtoError"
}
```
