### ISSUE TITLE
win_nssm - set timeout for expected service state

### ISSUE THREAD

**Issue by anthraxn8b** [ansible/ansible#55129]
##### SUMMARY
The `win_nssm` module should allow to set the timeout waiting for the defined state/status of the service.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_nssm

##### ADDITIONAL INFORMATION
Right now some services need a measurable amount of time to come up but the `win_nssm` module times out before and generates errors.

```yaml
- name: service install
  win_nssm:
    name: "my service"
    application: "myService.exe"
    state: started
    state_wait_timeout: PT5M
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_nssm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_nssm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @if-meaton @jborean93 @jhawkesworth @ksubileau @nitzmahone @smadam813 @themiwi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ksubileau** [comment]
Starting from Ansible 2.8, the `started` value for the `state` option will be deprecated, in favor of using the `win_service` module (see #45693).

What happens if you write something like this instead ? Do you still have a timeout issue ?
```yaml
- name: service install
  win_nssm:
    name: my service
    application: myService.exe
    state: present

- name: service start
  win_nssm:
    name: my service
    state: started
```
