### ISSUE TITLE
Handlers in role dependencies may be never triggered

### ISSUE THREAD

**Issue by Benoit-DunandLaisin** [ansible/ansible#55151]
##### SUMMARY

Using roles **A** and **B** which have the same **common** role with handlers inside.
In a play, I execute the 2 roles **A** and **B** with a when condition (usually, I apply a role if host is in the right inventory group).
If first role **A** is not executed because of the when condition, but **B** is executed, handlers notified by **common** role (dependency of **B**) are not executed because already _not triggered_ by role **A**.

It's somehow related to #15476.

Same issue with ansible 2.6.16 and 2.7.5.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = None
  configured module search path = ['/home/benoit.dunandlaisin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/benoit.dunandlaisin/.local/lib/python3.6/site-packages/ansible
  executable location = /home/benoit.dunandlaisin/.local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```bash
tree
.
├── playbook.yml
└── roles
    ├── A
    │   └── meta
    │       └── main.yml
    ├── B
    │   └── meta
    │       └── main.yml
    └── common
        ├── handlers
        │   └── main.yml
        └── tasks
            └── main.yml
```

playbook.yml
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: true
  pre_tasks:
    - name: Ensure test files are removed to trigger handler
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: absent
      loop: ["dummy", "handler"]
  roles:
    - {role: A, when: false}
    - {role: B, when: true}
  post_tasks:
    - name: Check if handler file exists
      file:
        path: "{{ ansible_env.HOME }}/handler"
        state: file
```

roles/common/tasks/main.yml
```yaml
---
- name: Ensure file exists
  file:
    path: "{{ ansible_env.HOME }}/dummy"
    state: touch
  notify: my_handler
```
roles/common/handlers/main.yml
```yaml
---
- name: my_handler
  file:
    path: "{{ ansible_env.HOME }}/handler"
    state: touch
```
roles/A/meta/main.yml and roles/B/meta/main.yml
```yaml
---
dependencies:
  - common
```

##### EXPECTED RESULTS

**my_handler** executed and so playbook won't fail.

##### ACTUAL RESULTS

playbook fail because **my_handler** is not executed.

```paste below
ansible-playbook playbook.yml
```
