### ISSUE TITLE
Multiple WLC commands via aireos_command module are not working on a single persistent SSH connection

### ISSUE THREAD

**Issue by spmurali** [ansible/ansible#55159]
##### SUMMARY

Multiple WLC commands via aireos_command module are not working on a single persistent SSH connection. If a wlc command worked in first task, then another wlc command in second task would not work. 

If used below, after each WLC command, then it works fine but takes long time to complete.
\- meta: reset_connection

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aireos_command

##### ANSIBLE VERSION

```paste below
"ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]"

```

##### CONFIGURATION

```paste below
"DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 290
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 300"

```

##### OS / ENVIRONMENT

Prod:
Manufacturer's Name.............................. Cisco Systems Inc.
Product Name..................................... Cisco Controller
Product Version.................................. 8.2.166.0
Bootloader Version............................... 1.0.20
Field Recovery Image Version..................... 7.6.95.16
Firmware Version................................. FPGA 1.7, Env 1.8, USB console 2.2

Lab: (No issues in lab. Same ansible version installed in lab)
Manufacturer's Name.............................. Cisco Systems Inc.
Product Name..................................... Cisco Controller
Product Version.................................. 8.5.135.0
Bootloader Version............................... 1.0.20
Field Recovery Image Version..................... 7.6.101.1
Firmware Version................................. FPGA 1.7, Env 1.8, USB console 

##### STEPS TO REPRODUCE

```yaml
"---
- hosts: "WLC"
  connection: local
  gather_facts: no
#  become: yes
#  become_method: enable

  tasks:
  - name: Get Corp WLAN Subnet
    aireos_command:
      commands:
        - command: grep exclude "management|service-port|redundancy-port|unused|virtual" "show interface summary"
          prompt: "Press any key to continue"
          answer: y
    register: WLAN_summary

  - name: Display Interface Summary
    debug: var=WLAN_summary.stdout


  - name: Filter wlan_summary output
    local_action: shell echo -e "{{WLAN_summary.stdout[0]}}" | sed -n "/Interface Name/,/There are/p" | sed '1,2d' | tac | sed '1,2d' | awk '{print $1}'
    register: corp_wlans


  - name: Get interface details
    aireos_command:
      commands:
        - command: grep include "^IP Netmask|^IP Address" "show interface detailed {{item}}"
          prompt: "Press any key to continue"
          answer: y
    register: ipaddress_netmask
    with_items: "{{corp_wlans.stdout.split('\n')}}"
    ignore_errors: True
"

```

##### EXPECTED RESULTS

WLC commands should work without giving any error

##### ACTUAL RESULTS

WLC commands threw CLI error.

TASK [Get interface details] ****************************************************************************************************************************************************************************************************************
ok: [10.195.101.10] => (item=22th_floor_wifi)
ok: [10.193.36.21] => (item=28-wifi-users2)
ok: [10.193.36.20] => (item=28-wifi-users2)
ok: [10.194.126.4] => (item=)
ok: [10.193.59.4] => (item=12th_floor_wifi)
failed: [10.193.36.21] (item=28-wifi-users1) => {"changed": false, "item": "28-wifi-users1", "msg": "0\r\n\nThere are 2 lines matching the pattern ^IP Netmask|^IP Address \n\r\n(Cisco Controller) >rep include \"^IP Netmask|^IP Address\" \"show interface detailed 28-wifi-users1\"\r\n\r\nIncorrect usage.  Use the '?' or <TAB> key to list commands.\r\n\r\n(Cisco Controller) >", "rc": -32603}
...ignoring
failed: [10.193.36.20] (item=28-wifi-users1) => {"changed": false, "item": "28-wifi-users1", "msg": "0\r\n\nThere are 2 lines matching the pattern ^IP Netmask|^IP Address \n\r\n(Cisco Controller) >rep include \"^IP Netmask|^IP Address\" \"show interface detailed 28-wifi-users1\"\r\n\r\nIncorrect usage.  Use the '?' or <TAB> key to list commands.\r\n\r\n(Cisco Controller) >", "rc": -32603}
...ignoring
failed: [10.195.101.10] (item=21st_floor_wifi) => {"changed": false, "item": "21st_floor_wifi", "msg": "rep include \"^IP Netmask|^IP Address\" \"show interface detailed 21st_floor_wifi\"\r\n\r\nIncorrect usage.  Use the '?' or <TAB> key to list commands.\r\n\r\n(Cisco Controller) >y\r\n\r\nIncorrect usage.  Use the '?' or <TAB> key to list commands.\r\n\r\n(Cisco Controller) >", "rc": -32603}
ok: [10.194.126.4] => (item=)
ok: [10.195.101.10] => (item=20th_floor_wifi)
failed: [10.194.126.4] (item=Would) => {"changed": false, "item": "Would", "msg": "troller) >rep include \"^IP Netmask|^IP Address\" \"show interface detailed Would\"\r\n\r\nIncorrect usage.  Use the '?' or <TAB> key to list commands.\r\n\r\n(Cisco Controller) >y\r\n\r\nIncorrect usage.  Use the '?' or <TAB> key to list commands.\r\n\r\n(Cisco Controller) >", "rc": -32603}

```paste below
Attached the log
[wlc_summary_ansible.log](https://github.com/ansible/ansible/files/3069155/wlc_summary_ansible.log)

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/aireos/aireos_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/aireos/aireos_command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jmighion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@spmurali, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by netsiphon** [comment]
Just from experience I would advise against using grep commands within aireos itself since mistakes on some versions of the software at least can mess up your connection and require you to reconnect to fix them.  
  
I would suggest instead just accepting the output of the original command and using map against the output with a regular expression if you need to include/exclude. No reason you couldn't do the same with shell and sed though.

Example:

```

- name: "Get Corp WLAN Subnet"
  aireos_command:
    commands:
      - command: "show interface summary"
        prompt: "Would you like to display the next 15 entries? (y/n)"
        answer: y
  register: summary_result


# Group capture turns the output into lists of lists so use sum(start=[]) to consolidate
- set_fact:
    iface_list: >-
      {{ summary_result.stdout_lines[0] | map('regex_search',REGEX_HERE) | reject('equalto',none) | sum(start=[]) | list }}
  register: iface_list_result



```
