### ISSUE TITLE
xml module forces encoding to UTF-8

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#55155]
##### SUMMARY
Though UTF-8 is the most commonly-used one, there are other valid XML-encodings. Unfortunately, any document going through the xml-module will have its encoding reset.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
2.7.9

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### STEPS TO REPRODUCE
Run the below playbook

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create test XML
    set_fact:
      xml: >-
        <?xml version='1.0' encoding='US-ASCII'?><Animals/>

  - name: Insert a new row
    xml:
      xmlstring: "{{ xml }}"
      xpath: '/Animals/Cat'
      ensure: present
      input_type: xml
      value: 'meow'
    register: ensured

  - debug: var=ensured
```

##### EXPECTED RESULTS
I expect the encoding to _not change_. Maybe, it would be Ok for it to change if -- after the current manipulation -- the document can no longer be described in the original encoding. But that's not what's happening here.

```json
ok: [localhost] => {
    "ensured": {
        "actions": {
            "namespaces": {},
            "state": "present",
            "xpath": "/Animals/Cat"
        },
        "changed": true,
        "failed": false,
        "xmlstring": "<?xml version='1.0' encoding='US-ASCII'?>\n<Animals><Cat>meow</Cat></Animals>"
    }
}
```

##### ACTUAL RESULTS

```json
ok: [localhost] => {
    "ensured": {
        "actions": {
            "namespaces": {},
            "state": "present",
            "xpath": "/Animals/Cat"
        },
        "changed": true,
        "failed": false,
        "xmlstring": "<?xml version='1.0' encoding='UTF-8'?>\n<Animals><Cat>meow</Cat></Animals>"
    }
}
```
