### ISSUE TITLE
datadog_monitor does not allow setting thresholds on "query alerts"

### ISSUE THREAD

**Issue by matttowerssonos** [ansible/ansible#55177]
##### SUMMARY
The `datadog_monitor` module explicitly excludes "query alert" monitor types from being able to set `warning` and `*_recovery` threshold levels.  The DataDog documentation is misleading on this but I have confirmed with DataDog support that it is possible.  Therefore I believe this restriction can be removed.

Here are the offending lines:  https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/datadog_monitor.py#L292-L295

DataDog monitor threshold API docs:  https://docs.datadoghq.com/monitors/faq/what-are-recovery-thresholds/#api

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`datadog_monitor.py`

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
```

##### CONFIGURATION
```bash
$ ansible-config dump --only-changed
bash: ansible-config: command not found
```

##### OS / ENVIRONMENT
MacOS 10.14

##### STEPS TO REPRODUCE
Create a "query alert" DataDog monitor with `warning`, `critical_recovery`, and/or `warning_recovery` attributes.  After executing playbook, go to DataDog and inspect the created monitor.  Note that `warning`, `critical_recovery` and/or `warninig_recovery` levels are not set.

```yaml
- name: "insert alert name here"
  datadog_monitor:
    name: "insert alert name here [[region.name]]"
    type: "query alert"
    query: "[insert query alert query here]"
    message: |
      alert message for region: [[region.name]]
    notify_audit: false
    locked: false
    timeout_h: 1
    silenced:
      "*": "{{ monitors_enabled }}"
    new_host_delay: 300
    require_full_window: false
    notify_no_data: false
    renotify_interval: 0
    thresholds:
      critical: 5
      warning: 10
      critical_recovery: 6
      warning_recovery: 11
    state: "{{ monitor_state }}"
    api_key: "{{ datadog_api_key }}"
    app_key: "{{ datadog_app_key }}"
```

##### EXPECTED RESULTS
`warning`, `critical_recovery` and `warning_recovery` values should be set on the monitor.

##### ACTUAL RESULTS
`warning`, `critical_recovery` and `warning_recovery` are not set

```
TASK [insert alert name here] *********************************************************************************************************************************************
changed: [localhost]
```
