### ISSUE TITLE
Add User-Agent Config for AWS Modules

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#55182]
##### SUMMARY

Add the ability to specify a user agent string for boto/3

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

aws

##### ADDITIONAL INFORMATION

```yaml
aws_access_key: redact
aws_secret_key: redact
aws_useragent: "Mozilla/5.0 (X11; Linux x86_64)"
```
