### ISSUE TITLE
Filetree plugin should always return `src` attribute

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#55188]
##### SUMMARY
The filetree plugin currently does not return the `src` attribute when `item.state` is set to `directory`. 

See https://github.com/ansible/ansible/issues/51513#issuecomment-459150769 and https://github.com/ellaqezi/dotfiles#known-issues. 

The documentation was updated to reflect this limitation in #54347. Any PR to fix this should update the documentation along with the code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
filetree 

##### ANSIBLE VERSION
2.8

##### CONFIGURATION
All/any. 

##### OS / ENVIRONMENT
All/any. 

##### STEPS TO REPRODUCE

```yaml
- name: Template from a directory
  template:
    src: '{{ item.src }}'
    dest: /web/{{ item.path }}
    mode: '{{ item.mode }}'
  with_filetree: web/
  when: item.state == 'directory'
```

##### EXPECTED RESULTS
Task succeeds.

##### ACTUAL RESULTS
Task fails with 'dict object' has no attribute 'src'.
