### ISSUE TITLE
Cli context is not properly handled for VyOS modules

### ISSUE THREAD

**Issue by NilashishC** [ansible/ansible#55201]
##### SUMMARY
- [This](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/vyos.py#L84) does not properly handle cli context switching when prompt is already at `configure` mode. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
action/vyos.py

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/nchakrab/collections/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/nchakrab/collections/ansible.cfg) = 60
PERSISTENT_CONNECT_RETRY_TIMEOUT(/Users/nchakrab/collections/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/nchakrab/collections/ansible.cfg) = 60
```

##### OS / ENVIRONMENT
VyOS 1.1.8

##### STEPS TO REPRODUCE

```yaml
---
- hosts: vyos-appliance
  gather_facts: no
  tasks:
    - vyos_command:
        commands: configure

    - vyos_config:
        lines: set interface ethernet eth1 description 'TEST'
```

##### EXPECTED RESULTS

- The `vyos.py` action plugin detects that the prompt is in `configure` mode and executes `end` to go back.

##### ACTUAL RESULTS

```paste below
fatal: [vyos-appliance]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "comment": "configured by vyos_config",
            "config": null,
            "host": null,
            "lines": [
                "set interface ethernet eth1 description 'TEST'"
            ],
            "match": "line",
            "password": null,
            "port": null,
            "provider": null,
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "configure\r\n\r\n  Invalid command: [configure]\r\n\r\n[edit]\r\r\nvyos@vyos-appliance# "
}
```
