### ISSUE TITLE
[k8s] Failed to find exact match for v1.DeploymentConfig by [kind, name, singularName, shortNames]

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#55221]
##### SUMMARY
I'm not able to use k8s to create a DeploymentConfig on Openshift 3.6.

Error messages are:
- ResourceNotFoundError('No matches found for {}'.format(kwargs))
- Failed to find exact match for v1.DeploymentConfig by [kind, name, singularName, shortNames]

Please help to fix or advise if it is not supported.

The same setup works when creating Pods or Secrets.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = None
  configured module search path = ['/Users/chuot/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chuot/Dev/Ansible/ansible-virtualenv/lib/python3.6/site-packages/ansible
  executable location = /Users/chuot/Dev/Ansible/ansible-virtualenv/bin/ansible
  python version = 3.6.8 (default, Apr 11 2019, 22:58:09) [GCC 4.2.1 Compatible Clang 7.0.1 (tags/RELEASE_701/final)]
```

##### CONFIGURATION
```
(empty)
```

##### OS / ENVIRONMENT
MacOS 10.13.6

$ uname -a
Darwin NCELRND0546 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin

Gentoo Prefix

Virtualenv for ansible

##### STEPS TO REPRODUCE
Here is a small test config:

playbook.yml
```
---
- name: Test case for creating a DeploymentConfig with Ansible
  hosts: all
  gather_facts: no
  vars:
    k8s_url: https://172.30.19.49:8443/
    k8s_ns: myproject
    k8s_apikey: xxx
  tasks:
    - name: test DeploymentConfig
      delegate_to: 127.0.0.1
      run_once: true
      k8s:
        state: present
        resource_definition: "{{ lookup('template', 'test.yml') }}"
        host: "{{ k8s_url }}"
        namespace: "{{ k8s_ns }}"
        api_key: "{{ k8s_apikey }}"
        verify_ssl: false
...
```

test.yml:
```
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: totoDc
spec:
  template:
    metadata:
      labels:
        name: totoTemplate
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: totoContainer
        image: my/image:thetag
        imagePullPolicy: IfNotPresent
  replicas: 1
```

and a minimalist inventory which is actually not used (since running on control node):
inventory:
```
[all]
toto
```

##### EXPECTED RESULTS
The DeploymentConfig should be created

##### ACTUAL RESULTS

```
$ ansible-playbook -i inventory -vvvv playbook.yml
ansible-playbook 2.7.10
  config file = None
  configured module search path = ['/Users/chuot/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chuot/Dev/Ansible/ansible-virtualenv/lib/python3.6/site-packages/ansible
  executable location = /Users/chuot/Dev/Ansible/ansible-virtualenv/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 11 2019, 22:58:09) [GCC 4.2.1 Compatible Clang 7.0.1 (tags/RELEASE_701/final)]
No config file found; using defaults
setting up inventory plugins
/Users/chuot/Dev/Ansible/oracle_observers/molecule/default/inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/Users/chuot/Dev/Ansible/oracle_observers/molecule/default/inventory did not meet script requirements, check plugin documentation if this is unexpected
Parsed /Users/chuot/Dev/Ansible/oracle_observers/molecule/default/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /Users/chuot/Dev/Ansible/ansible-virtualenv/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: playbook.yml **************************************************************************************************************************************************************
1 plays in playbook.yml

PLAY [Test case for creating a DeploymentConfig with Ansible] ***********************************************************************************************************************
META: ran handlers

TASK [test DeploymentConfig] ********************************************************************************************************************************************************
task path: /Users/chuot/Dev/Ansible/oracle_observers/molecule/default/playbook.yml:10
File lookup using /Users/chuot/Dev/Ansible/oracle_observers/templates/test.yml as file
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: chuot
<127.0.0.1> EXEC /bin/sh -c 'echo ~chuot && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078 `" && echo ansible-tmp-1555088971.376927-162544634893078="` echo /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078 `" ) && sleep 0'
Using module file /Users/chuot/Dev/Ansible/ansible-virtualenv/lib/python3.6/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /Users/chuot/.ansible/tmp/ansible-local-33226s8wbs9mh/tmph00zv9rk TO /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078/AnsiballZ_k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078/ /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/chuot/Dev/Ansible/ansible-virtualenv/bin/python /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078/AnsiballZ_k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/chuot/.ansible/tmp/ansible-tmp-1555088971.376927-162544634893078/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/lq/mtrm60rd3xb75c4dv54rppk00000gp/T/ansible_k8s_payload_bchndbu9/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py", line 194, in find_resource
    return self.client.resources.get(api_version=api_version, short_names=[kind])
  File "/Users/chuot/Dev/Ansible/ansible-virtualenv/lib/python3.6/site-packages/openshift/dynamic/client.py", line 637, in get
    raise ResourceNotFoundError('No matches found for {}'.format(kwargs))

fatal: [toto -> 127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cert_file": null,
            "context": null,
            "force": false,
            "host": "https://172.30.19.49:8443/",
            "key_file": null,
            "kubeconfig": null,
            "merge_type": null,
            "password": null,
            "ssl_ca_cert": null,
            "state": "present",
            "username": null,
            "verify_ssl": false
        }
    },
    "msg": "Failed to find exact match for v1.DeploymentConfig by [kind, name, singularName, shortNames]"
}

NO MORE HOSTS LEFT ******************************************************************************************************************************************************************
	to retry, use: --limit @/Users/chuot/Dev/Ansible/oracle_observers/molecule/default/playbook.retry

PLAY RECAP **************************************************************************************************************************************************************************
toto                       : ok=0    changed=0    unreachable=0    failed=1
```
