### ISSUE TITLE
VMware: vmware_object_role_permission incorrectly assigns permissions on DVS object instead of folder

### ISSUE THREAD

**Issue by mamullen13316** [ansible/ansible#55248]
##### SUMMARY
When using object_type of DistributedVirtualSwitch, the permissions are created on the DVS object.  It appears that they should be created on the parent folder instead.  The permissions are applied to the DVS correctly,  however they do not have any affect.  The group being assigned permissions does not gain the ability to manage the DVS.  Also a warning message is seen in the GUI "Permissions for a distributed switch must be defined and managed on either the datacenter or a folder containing the switch".  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_object_role_permission

##### ANSIBLE VERSION
```
ansible 2.8.0a1.post0
  config file = None
  configured module search path = ['/Users/mmullen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mmullen/.virtualenvs/ansible_dev/lib/python3.7/site-packages/ansible
  executable location = /Users/mmullen/.virtualenvs/ansible_dev/bin/ansible
  python version = 3.7.2 (default, Apr 11 2019, 22:12:58) [Clang 9.0.0 (clang-900.0.38)]
```

##### CONFIGURATION
```
No output,  nothing changed from defaults. 
```

##### OS / ENVIRONMENT
Target: VMware vCenter Version 6.7.0.20000 Build 10244845
Controller: MacOS 10.14.2 (Mojave)
pyvmomi==6.7.1.2018.12

##### STEPS TO REPRODUCE
Run a playbook to set permissions on a DVS.
```
    - name: Change permissions on VMware DVS
      vmware_object_role_permission:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        group: "TestGroup"
        role: Admin
        object_name: "TestDVS"
        object_type: DistributedVirtualSwitch
        state: present
      delegate_to: localhost
```

##### EXPECTED RESULTS
Permissions should be assigned to the folder containing the specified DVS.  

##### ACTUAL RESULTS
Module executes successfully, but permissions are configured on the DVS object.  The result is that users are not given the intended permissions.  

```

```
