### ISSUE TITLE
win_chocolatey failed to install packages

### ISSUE THREAD

**Issue by Abuba-369** [ansible/ansible#55256]
##### SUMMARY

when i need to install chocolatey packages using win_chocolatey i get mentioned error below
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```ansible 2.7.5


##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT

Windows 2012 server 
##### STEPS TO REPRODUCE

```yaml
 - name: windows install packages
    win_chocolatey:
      name:
      - googlechrome
      - notepadplusplus
      - php
      - apache-httpd
      state: present
    when: ansible_os_family == "Windows"

```

##### EXPECTED RESULTS

To install those packages
##### ACTUAL RESULTS

fatal: [192.168.1.126]: FAILED! => {"changed": false, "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output php", "msg": "Error checking installation status for the package 'php'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

```paste below
play book run succeed on centos and ubuntu,but fails on windows
```
fatal: [192.168.1.126]: FAILED! => {"changed": false, "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output php", "msg": "Error checking installation status for the package 'php'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
