### ISSUE TITLE
Issue using openssl_csr module on MacOS Mojave

### ISSUE THREAD

**Issue by rehmatworks** [ansible/ansible#55267]
On Mojave, looks like the default export format of ssh-keygen has changed and now when we attempt to use Ansible's openssl_csr module from a Macbook running Mojave, the task fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_csr

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### OS / ENVIRONMENT
macOS Mojave version 10.14.4 running Python 3.7.1

##### STEPS TO REPRODUCE

```yaml
- name: Generate an OpenSSL private key.
      openssl_privatekey:
          path: "{{ privkeypath }}"
          force: true
          size: 2048

    - name: Generate CSR
      openssl_csr:
          path: "{{ csrpath }}"
          privatekey_path: "{{ privkeypath }}"
          common_name: "{{ hostname }}"
```

##### ACTUAL RESULTS

```paste below
fatal: [68.183.249.35]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 68.183.249.35 closed.\r\n", "mod
ule_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1555259261.789623-126355232345725
/AnsiballZ_openssl_csr.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-155525
9261.789623-126355232345725/AnsiballZ_openssl_csr.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_pa
th, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1555259261.789623-126355232345725/AnsiballZ_openssl_csr.py\"
, line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib/python3.6/imp.py\"
, line 235, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib/python3.6/imp.py\", line 170,
 in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 618, in _exe
c\r\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\r\n  File \"<frozen importlib._bootstrap>\",
 line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_openssl_csr_payload_mamj5lne/__main__.py\", line 591, in <mo
dule>\r\n  File \"/tmp/ansible_openssl_csr_payload_mamj5lne/__main__.py\", line 569, in main\r\n  File \"/tmp/ansible_openssl
_csr_payload_mamj5lne/__main__.py\", line 368, in generate\r\n  File \"/tmp/ansible_openssl_csr_payload_mamj5lne/__main__.py\
", line 492, in check\r\n  File \"/tmp/ansible_openssl_csr_payload_mamj5lne/ansible_openssl_csr_payload.zip/ansible/module_ut
ils/crypto.py\", line 93, in load_certificate_request\r\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 28
54, in load_certificate_request\r\n    _openssl_assert(req != _ffi.NULL)\r\n  File \"/usr/lib/python3/dist-packages/OpenSSL/_
util.py\", line 67, in openssl_assert\r\n    exception_from_error_queue(error)\r\n  File \"/usr/lib/python3/dist-packages/Ope
nSSL/_util.py\", line 54, in exception_from_error_queue\r\n    raise exception_type(errors)\r\nOpenSSL.crypto.Error: [('PEM r
outines', 'get_name', 'no start line')]\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
