### ISSUE TITLE
web application - playbook error

### ISSUE THREAD

**Issue by anasqureshi0811** [ansible/ansible#55271]
##### SUMMARY
Was having problem executing below playbook on cent os 7 1708 Oracle VM manager:

playbook:
```yaml
-
  name: Deploy a web application
  hosts: target1
  tasks:

    - name: Install dependencies
      apt: name={{ item }} state=installed
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb

    - name: Install MySQL database
      apt:
        name: "{{ item }}"
        state:  present
      with_items:
       - mysql-server
       - mysql-client

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db: name='employee_db' state=present


    - name: Create Application DB User
      mysql_user: name='db_user' password='Passw0rd' priv='*.*:ALL' host='%' state='present'

    - name: Install Python Flask dependencies
      pip:
        name: '{{ item }}'
        state: present
      with_items:
       - flask
       - flask-mysql

    - name: Copy web-server code
      copy: src=app.py dest=/opt/app.py

    - name: Start web-application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
```

```
[osboxes@anisblecontroller AQ-Project1]$ ansible-playbook playbook-webapp.yml -i inventory.txt

PLAY [Deploy a web application] ************************************************

TASK [Gathering Facts] *********************************************************
ok: [target1]

TASK [Install dependencies] ****************************************************
failed: [target1] (item=[u'python', u'python-setuptools', u'python-dev', u'build-essential', u'python-pip', u'python-mysqldb']) => {"changed": false, "cmd": "apt-get update", "item": ["python", "python-setuptools", "python-dev", "build-essential", "python-pip", "python-mysqldb"], "msg": "[Errno 2] No such file or directory", "rc": 2}
        to retry, use: --limit @/home/osboxes/AQ-Project1/playbook-webapp.retry

PLAY RECAP *********************************************************************
target1                    : ok=1    changed=0    unreachable=0    failed=1
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
