### ISSUE TITLE
ansible not deleting temporary files (in a few cases)

### ISSUE THREAD

**Issue by jmnavarrol** [ansible/ansible#55286]
##### SUMMARY
Answering to a request from @jhawkesworth at https://github.com/ansible/ansible/issues/5339#issuecomment-443414736.

This seems a re-ocurrence of #5339.  There are (at least) some cases where Ansible isn't deleting its temporary files.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
ansible 2.7.2
  config file = /path/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/ansible-2.7/local/lib/python2.7/site-packages/ansible
  executable location = /home/user/.virtualenvs/ansible-2.7/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### OS / ENVIRONMENT
Target is RHEL7 (don't think is of importance, beyond being a Linux target).

##### STEPS TO REPRODUCE
```yaml
- name: Example playbook to show an unexpected behaviour
  hosts: some.host
  become: true
  become_user: someuser

  tasks:
  - name: Creates a remote file
    shell: echo "hello, world!" >> ~/myfile.txt
```
Relevant contents from *ansible.cfg*:
```
[defaults]
remote_tmp = /tmp/ansible_${USER}
```

##### EXPECTED RESULTS
No remains under */tmp/* or, at most, an empty */tmp/ansible_someuser* dir.

##### ACTUAL RESULTS
```paste below
# tree -a /tmp/ansible_someuser/
tmp/ansible_someuser/
├── ansible-moduletmp-1555321104.27-3gzN5j
└── ansible-moduletmp-1555321105.42-5hvt6M
```
