### ISSUE TITLE
VMware: vmware_deploy_ovf - ova image invalid path

### ISSUE THREAD

**Issue by wioch** [ansible/ansible#55284]
##### SUMMARY

Hello. I'm trying to deploy ova image on ESXi using module vmware_deploy_ovf. Problem lies with 'ova' directive. Every time, no matter the path, I always get the same message:
```
"msg": "argument ovf is of type <type 'str'> and we were unable to convert to path_exists: /vmfs/volumes/datastore1/someimage.ova is not a valid path"
```

Target system is ESXi 6.5.0 Update 2 (Build 8294253) with python 3.5.3. 

So the questions are: 
- is it me providing wrong path (path checks ok in separate task) ?
- or is it problem with ova image (however I can deploy it using ovftool) ? 
- or is it a bug in vmware_deploy_ovf module that cannot correctly check given absolute path ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_deploy_ovf

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 13:41:07) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```

##### CONFIGURATION

```paste below
[root@host .ssh]# ansible-config dump --only-changed
[root@host .ssh]# <no output>
```

##### OS / ENVIRONMENT
Fedora 28 (with python 2.7.15) (Linux host 5.0.5-100.fc28.x86_64)
Fedora 29 (with python 3.7.3) (Linux fedora29 5.0.7-200.fc29.x86_64)

##### STEPS TO REPRODUCE

Run the playbook

```yaml
---
- name: test play
  hosts: esxi
  become: true
  vars:
    path: '/vmfs/volumes/datastore1'
    ova: 'someimage.ova'

  tasks:
  - name: stat the ova file
    stat:
      path: '{{ path }}/{{ ova }}'
    register: file_details

  - debug:
      msg: "The file or directory exists"
    when: file_details.stat.exists


  - name: Create a virtual machine on given ESXi hostname
    vmware_deploy_ovf:
      hostname: '10.3.1.190'
      username: 'root'
      password: 'somepass'
      ovf: '{{ path }}/{{ ova }}'
      disk_provisioning: thin
      name: test_vm_001
      power_on: yes
    delegate_to: localhost
```

##### EXPECTED RESULTS

success

##### ACTUAL RESULTS

```paste below
ansible-playbook play2.yml -u root -vv
ansible-playbook 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: play2.yml *************************************************************************************************************
1 plays in play2.yml

PLAY [test play] ****************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
task path: /root/.ssh/play2.yml:2
ok: [10.3.1.190]
META: ran handlers

TASK [stat the ova file] ********************************************************************************************************
task path: /root/.ssh/play2.yml:10
ok: [10.3.1.190] => {"changed": false, "stat": {"atime": 1555314194.0, "attr_flags": "", "attributes": [], "block_size": 131072, "blocks": 18290688, "charset": "unknown", "checksum": "0f0be2fef256eb184b1d2c8cb17e521f197d2231", "ctime": 1555249216.0, "dev": -6738084600919296302, "device_type": 0, "executable": false, "exists": true, "gid": 0, "gr_name": "root", "inode": 4216196, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mimetype": "unknown", "mode": "0644", "mtime": 1538130484.0, "nlink": 1, "path": "/vmfs/volumes/datastore1/someimage.ova", "pw_name": "root", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 9364071424, "uid": 0, "version": null, "wgrp": false, "woth": false, "writeable": true, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK [debug] ********************************************************************************************************************
task path: /root/.ssh/play2.yml:15
ok: [10.3.1.190] => {
    "msg": "The file or directory exists"
}

TASK [Create a virtual machine on given ESXi hostname] **************************************************************************
task path: /root/.ssh/play2.yml:20
fatal: [10.3.1.190 -> localhost]: FAILED! => {"changed": false, "msg": "argument ovf is of type <type 'str'> and we were unable to convert to path_exists: /vmfs/volumes/datastore1/someimage.ova is not a valid path"}
        to retry, use: --limit @/root/.ssh/play2.retry

PLAY RECAP **********************************************************************************************************************
10.3.1.190                 : ok=3    changed=0    unreachable=0    failed=1
```
