### ISSUE TITLE
K8s module support for creating configmap --from-file syntax

### ISSUE THREAD

**Issue by alonisser** [ansible/ansible#55329]
##### SUMMARY

Currently k8s module (which is great) does not seem to support syntax for creating configmap ```--from-file``` (where file might also be a folder )
For example from metacontroller [docs](https://metacontroller.app/)
```bash
kubectl create configmap service-per-pod-hooks -n metacontroller --from-file=hooks

```
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

k8s
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
This would be cool, though it's probably too specific for the `k8s` module. Probably best done as a separate `k8s_configmap` module that supports the various options to get closer to parity with `kubectl`

**Comment by gearoidibm** [comment]
One way to do this with the existing modules is to slurp the file and then use that in the k8s module
```
- name: slurp foo
  slurp:
    src: "/tmp/foo"
  register: foo

- name: create the configmap
  k8s:
    state: present
    namespace: default
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: foo-configmap
      data:
        foo: "{{ foo.content | b64decode }}"
```
