### ISSUE TITLE
[RFE] Extend ovirt_permission module for Group Permissions

### ISSUE THREAD

**Issue by tmichett** [ansible/ansible#55341]
##### SUMMARY

Currently the ovirt_permission module allows user permissions to be added to items within RHV, but does not allow for adding the **group** from LDAP.

Need a way to properly add LDAP groups via Ansible

##### ISSUE TYPE
- Feature Idea

Modify the **ovirt_permission** module to have **user_group_name** which will allow an LDAP group to be specified instead of a single user.

- name: Add permission for LDAP group
  ovirt_permission:
    state: present
    user_group_name: UserGroup1
    authz_name: example.com-authz
    object_type: cluster
    object_name: mycluster
    role: ClusterAdmin

Allows assigning UserGroup1 LDAP group to the cluster named "mycluster". Currently, there is no way to assign a group from LDAP using this ansible module.

##### COMPONENT NAME

ovirt_permission

##### ADDITIONAL INFORMATION

```yaml

- name: Add permission for LDAP group
  ovirt_permission:
    state: present
    user_group_name: UserGroup1
    authz_name: example.com-authz
    object_type: cluster
    object_name: mycluster
    role: ClusterAdmin

```
