### ISSUE TITLE
lineinfile: multiple lines (/g)

### ISSUE THREAD

**Issue by LeonB** [ansible/ansible#5535]
Maybe it would be a nice addition for lineinfile to add a flag (global/multiple) that makes lineinfile replace ALL matching lines.

In my case:

``` yml
- name: configure mod_php5
  lineinfile: dest=/etc/apache2/mods-enabled/php5.conf
    regexp="^(\s*)(SetHandler.*)$" line="\1# \2" backrefs=yes
```

/etc/apache2/mods-enabled/php5.conf:

```
<IfModule mod_php5.c>
    <FilesMatch "\.ph(p3?|tml)$">
    SetHandler application/x-httpd-php
    </FilesMatch>
    <FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
    </FilesMatch>
    # To re-enable php in user directories comment the following lines
    # (from <IfModule ...> to </IfModule>.) Do NOT set it to On as it
    # prevents .htaccess files from disabling it.
    <IfModule mod_userdir.c>
        <Directory /home/*/public_html>
            php_admin_value engine Off
        </Directory>
    </IfModule>
</IfModule>
```

For now I'll just use a template but I thought it could make a nice addition.

**Comment by mpdehaan** [comment]
If you can use a template you always should, that way you don't trust a human on the other end of the line and know exactly what you are pushing down.

If you are doing multiple lines, that is usually implemented by just calling sed.

That being said, I'm not against this either.

**Comment by mpdehaan** [comment]
I'm going to close this ticket as I haven't seen any pull requests for this, but wanted to point out they would definitely be entertained if you wanted to add this.

Still, calling sed should work for most users.

Thanks!

**Comment by samrocketman** [comment]
I've created a sort of "poor" implementation of the global search and replace using do-until loops.

```yaml
- name: "Ensure sources.list is Debian Testing"
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^(deb.*)jessie(.*main)$'
    line: '\1testing\2'
    backrefs: yes 
  register: result
  until: result.changed == false
  retries: 5
  delay: 0
```
It will "fail" four times and then on the last time succeed.

I think I'll switch to `sed` but it's a bit annoying because ansible throws a warning.

```yaml
- name: "Ensure sources.list is Debian Testing"
  shell: "sed -ri -- 's/^(deb.*)jessie(.*main)$/\\1testing\\2/' /etc/apt/sources.list"
```
