### ISSUE TITLE
Azure_rm_storageblob - Share key authorization support 

### ISSUE THREAD

**Issue by melezhik** [ansible/ansible#55350]
##### SUMMARY
Share key authorization support, see https://docs.microsoft.com/en-us/azure/storage/common/storage-auth , Shared Key authorization.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`azure_rm_storageblob`  module

##### ADDITIONAL INFORMATION
 Need to accept `access_key` parameter which is the value of shared authorization key

```yaml

- name: Remove container foo
  azure_rm_storageblob:
    resource_group: testing
    storage_account_name: clh0002
    container: foo
    access_key: "{{ my_access_key }}"
    state: present

```
