### ISSUE TITLE
portage module: inconsistent behaviour with present packages

### ISSUE THREAD

**Issue by s-hamann** [ansible/ansible#55365]
##### SUMMARY
The `portage` module shows inconsistent behaviour when dealing with already present packages. I stumbled over two issues that seem closely related.

First: When all specified packages are already present on the system, the `portage` module does not reinstall them. This is usually what a user would expect.
However, if the list contains a single (additional) package, that is not yet installed, *all* packages in the list are reinstalled, which is usually a waste of CPU cycles.
This does not happen with `noreplace: true`, since in this case portage's functionality to avoid re-merges is invoked.

Second: Due to Ansible's detection of already installed packages, there is no (sensible) way to force reinstalling an already installed package (that is up-to-date and has no changed USE flags, that is). A non-sensical workaround would be to install a second, new package at the same time.
Reinstalling an already present package is a valid use case when using portage's savedconfig feature and changing the saved config file (`/etc/portage/savedconfig/`), when adding custom patches (`/etc/portage/patches/`), after adding `buildpkg` to `FEATURES`, when using custom hooks (`/etc/portage/env/`), etc.

I suggest using `noreplace: true` by default. The list of packages could then be passed to `emerge` without further checkes (as done in about [line 296 of the `portage` module](../blob/devel/lib/ansible/modules/packaging/os/portage.py#L296)).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
modules/packaging/os/portage.py

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.6/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.6/ansible
  python version = 3.6.5 (default, Apr 22 2018, 15:17:10) [GCC 6.4.0]
```

##### CONFIGURATION
default configuration

##### OS / ENVIRONMENT
The target runs Gentoo Linux with portage version 2.3.62.

##### STEPS TO REPRODUCE
I used the following playbook on a fresh Gentoo installation:

```yaml
- hosts: localhost
  tasks:
    - name: 'set up packages'
      portage:
        package: "{{ item.package }}"
        state: "{{ item.state }}"
      loop:
        - package: sys-apps/busybox
          state: present
        - package: virtual/eject
          state: absent

    - name: 'test case 1: re-emerge present package'
      portage:
        package: sys-apps/busybox
        state: present
        noreplace: no
      # result: OK, i.e. package is not reinstalled
      # expected: changed, i.e. package is reinstalled

    - name: 'test case 2: do not re-emerge present package'
      portage:
        package: sys-apps/busybox
        state: present
        noreplace: yes
      # result: OK, portage runs but package is not reinstalled
      # expected: OK, package is not reinstalled

    - name: 'test case 3: emerge present and absent packages'
      portage:
        package:
          - sys-apps/busybox
          - virtual/eject
        state: present
        noreplace: no
      # result: changed, both packages are reinstalled
      # expected: changed, both packages are reinstalled

    - name: 'set up packages'
      portage:
        package: "{{ item.package }}"
        state: "{{ item.state }}"
      loop:
        - package: sys-apps/busybox
          state: present
        - package: virtual/eject
          state: absent

    - name: 'test case 4: do not re-emerge present and absent packages'
      portage:
        package:
          - sys-apps/busybox
          - virtual/eject
        state: present
        noreplace: yes
      # result: changed, portage runs but only virtual/eject is (re-)installed
      # expected: changed, only virtual/eject is (re-)installed

    - name: 'set up packages'
      portage:
        package: "{{ item.package }}"
        state: "{{ item.state }}"
      loop:
        - package: sys-apps/busybox
          state: present
        - package: virtual/eject
          state: absent

    - name: 'bonus test case 5: let Ansible do the right thing with present and absent packages'
      portage:
        package:
          - sys-apps/busybox
          - virtual/eject
        state: present
      # result: changed, both packages are (re-)installed
      # expected: changed, only virtual/eject is (re-)installed
```

##### EXPECTED RESULTS
Present packages are reinstalled when using `noreplace: false` (test case 1 and 3).
Present packages are not reinstalled when using `noreplace: true` (test case 2 and 4).
Present packages are not reinstalled with default parameters (test case 5).

##### ACTUAL RESULTS
Whether packages are reinstalled or not depends on the state of other packages that are also passed to the module as well as `noreplace`.
The present package (`sys-apps/busybox`) is re-installed only in test case 3 (and 5, which is actually the same).
