### ISSUE TITLE
[k8s] Surface resource discovery errors properly

### ISSUE THREAD

**Issue by fabianvf** [ansible/ansible#55388]
##### SUMMARY

Follow up on #55221

When we aren't able to find a specific resource, we fail cryptically. We should report the results of our search in our failure message so that users don't need to dig around in the python code manually.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s
##### ANSIBLE VERSION

```paste below
ansible 2.7.7
  config file = /home/fabian/.ansible.cfg
  configured module search path = [u'/home/fabian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fabian/.local/lib/python2.7/site-packages/ansible
  executable location = /home/fabian/.local/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```
##### STEPS TO REPRODUCE

```yaml
  - k8s:
      definition:
        kind: Deployment
        apiVersion: v1beta1
        metadata:
          name: test
          namespace: default
        spec:
          selector:
            matchLabels:
              app: test
          template:
            metadata:
              labels:
                app: test
            spec:
              containers:
                - image: busybox
                  name: busybox
                  command:
                    - sleep
                    - "600"

```
##### EXPECTED RESULTS

Fails, with a message that explains that a `v1beta1.Deployment` resource was found in both `extensions` and `apps` api groups

##### ACTUAL RESULTS

```paste below
TASK [k8s] ***************************************************************************************
fatal: [127.0.0.1]: FAILED! => changed=false 
  msg: Failed to find exact match for v1beta1.Deployment by [kind, name, singularName, shortNames]
```
