### ISSUE TITLE
hashi_vault flexibility

### ISSUE THREAD

**Issue by AndrewDoesNotCompute** [ansible/ansible#55408]
##### SUMMARY

The ability to specify different servers and/or tokens more efficiently for the `hashi_vault` lookup plugin, either through using variable interpolation or defining variables in inventory.

Currently, `hashi_vault` is very inflexible. In my environment, I cannot guarantee a single Vault server will be used. This leads to the issue of having to specify servers (verbose) and secrets (undesirable) in each `lookup` call.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hashi_vault

##### ADDITIONAL INFORMATION

h2. suggestion 1
Allow variables to be passed to the lookup plugin. This somewhat aids in the verbosity/copy-pasting of values. It also allows maximal flexibility if that is desirable. I do not know if this technically feasible for Ansible plugins however.

h2. suggestion 2
Allow variables to be defined in inventory files that the `hashi_vault` plugin will then use. This allows at a `group_var` or `host_var` level to define Vault access.

```yaml
# suggestion 1
my_var: "{{ lookup('hashi_vault', host={{ vault_server }}, token={{ vault_token }}, path=hello/world) }}"

# suggestion 2
hashi_vault_server: https://example.com:8200
hashi_vault_token_path: path/to/token
my_var: "{{ lookup('hashi_vault', path=hello/world) }}"
```
