### ISSUE TITLE
openvswitch_db: string key values causing not idempotent commands

### ISSUE THREAD

**Issue by nmiletic** [ansible/ansible#55432]
##### SUMMARY
string key values causing not idempotent commands. 
Double quotes are not stripped in map_config_to_obj leading to wrong key value in 'have'.

```
Maybe this can fix it:
<             col_value_to_dict[k.strip()] = v.strip().strip('\"')
---
>             col_value_to_dict[k.strip()] = v.strip()
```

```
root@ubuntu63:~/.ansible/tmp/ansible-tmp-1555491969.439463-157165670102828/debug_dir# python3 __main__.py  args

{"changed": true, "commands": ["/usr/bin/ovs-vsctl -t 5 set open_vswitch . other_config:pmd-cpu-mask=0xaaa00000000"], "invocation": {"module_args": {"table": "open_vswitch", "record": ".", "col": "other_config", "key": "pmd-cpu-mask", "value": "0xaaa00000000", "state": "present", "timeout": 5, "ovs-vsctl": "/usr/bin/ovs-vsctl"}}}
root@ubuntu63:~/.ansible/tmp/ansible-tmp-1555491969.439463-157165670102828/debug_dir# python3 __main__.py  args

{"changed": true, "commands": ["/usr/bin/ovs-vsctl -t 5 set open_vswitch . other_config:pmd-cpu-mask=0xaaa00000000"], "invocation": {"module_args": {"table": "open_vswitch", "record": ".", "col": "other_config", "key": "pmd-cpu-mask", "value": "0xaaa00000000", "state": "present", "timeout": 5, "ovs-vsctl": "/usr/bin/ovs-vsctl"}}}

(Pdb) p have
{'table': 'open_vswitch', 'record': '.', 'col': 'other_config', 'key': 'pmd-cpu-mask', 'value': '"0xaaa00000000"'}
(Pdb) p want
{'table': 'open_vswitch', 'record': '.', 'col': 'other_config', 'value': '0xaaa00000000', 'key': 'pmd-cpu-mask'}

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openvswitch_db

##### ANSIBLE VERSION
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nmiletic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nmiletic/src/ansible/lib/ansible
  executable location = /home/nmiletic/src/ansible/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION
~/ansible$ ansible-config dump --only-changed
:~/ansible$

##### OS / ENVIRONMENT
Ubuntu 18.04


##### STEPS TO REPRODUCE
Run twice:

- name: set pmd-cpu-mask
  openvswitch_db:
    table: open_vswitch
    record: .
    col: other_config
    key: pmd-cpu-mask
    value: "0xaaa00000000"



##### EXPECTED RESULTS
Second run should not run the command.


##### ACTUAL RESULTS
Second run runs the command.
```
