### ISSUE TITLE
zabbix_template: incorrect export and import of non-ACSII strings in template [bug]

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#55439]
##### SUMMARY

When Zabbix template is saved using `state=dump` of module zabbix_template, all non-ASCII strings become encoded like this: `"\u0422\u0435\u0441\u0442"`(this is Russian string "Тест"). On importing this template using `state=present`, trigger name presented by this string becomes `"\u0422\u0435\u0441\u0442"` instead of "Тест".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_template

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/user/work/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/user/work/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

OS: Ubuntu 16.04 Xenial
Zabbix Server: 4.0

##### STEPS TO REPRODUCE

```yaml
- name: Dump Zabbix template
  local_action:
    module: zabbix_template
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_password }}"
    template_name: "t_test"
    state: dump
  register: template_dump

- name: Save json template
  local_action:
    module: copy
    content: "{{ template_dump['template_json'] }}"
    dest: t_test.json

- name: Import Zabbix Template
  zabbix_template:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_password }}"
    template_name: "t_test"
    template_groups:
       - Templates
    state: present
    template_json: "{{ lookup('file', 't_test.json') }}"
```

##### EXPECTED RESULTS

Non-ASCII characters in template, like trigger names, should be restored correctly.

##### ACTUAL RESULTS

Non-ASCII characters in template, like trigger names, are restored in this form: \u0422\u0435\u0441\u0442"/

```paste below

```
