### ISSUE TITLE
Creating directory and checking it exist fail

### ISSUE THREAD

**Issue by emilorol** [ansible/ansible#55467]
I have the following task that check if the directory exist and if it doesn't then I create it, then a bit later I check if it was created to do more stuff, but it fail. What am I missing?

```
- hosts: "{{ target }}"
  vars:
     shared_path: /usr/local/apps/shared
     releases_path: /usr/local/apps/releases

  tasks:
   - name: shared_path exists
     stat: path={{shared_path}}
     register: sp

   - name: releases_path exists
     stat: path={{releases_path}}
     register: rp

   - include: tasks/setup.application.yml
     when: sp.stat.isdir is not defined and rp.stat.isdir is not defined

   - include: tasks/deploy.application.releases.yml
     when: sp.stat.isdir is defined and rp.stat.isdir is defined
```
I am running:

```
ansible 2.7.10
  config file = /home/MYUSER/Desktop/Ansible/ansible/ansible.cfg
  configured module search path = [u'/home/MYUSER/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
