### ISSUE TITLE
systemd module: glob pattern has inconsistent behavior

### ISSUE THREAD

**Issue by mbigras** [ansible/ansible#55476]
##### SUMMARY

The systemd module does not silently ignore units that aren't matched when using the glob pattern. It fails with error message:

```
    - name: run systemctl stop foo*.service --user
      systemd:
        name: foo*.service
        scope: user
        state: stopped
      ignore_errors: yes
```

```
Could not find the requested service foo*.service: host
```

This behavior is inconsistent with the expected result for systemctl:

https://www.freedesktop.org/software/systemd/man/systemctl.html

>Glob patterns use fnmatch(3), so normal shell-style globbing rules are used, and "*", "?", "[]" may be used. See glob(7) for more details. The patterns are matched against the primary names of units currently in memory, and patterns which do not match anything are silently skipped.

##### ISSUE TYPE
- ~Bug  Report~
- Feature Idea

##### COMPONENT NAME

systemd module

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /Users/max/code/ansible_systemd/ansible.cfg
  configured module search path = ['/Users/max/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.10/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/max/code/ansible_systemd/ansible.cfg) = ['/Users/max/code/ansible_systemd/inventory.ini']
DEFAULT_PRIVATE_KEY_FILE(/Users/max/code/ansible_systemd/ansible.cfg) = /Users/max/.vagrant.d/insecure_private_key
DEFAULT_REMOTE_USER(/Users/max/code/ansible_systemd/ansible.cfg) = vagrant
HOST_KEY_CHECKING(/Users/max/code/ansible_systemd/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
```

##### STEPS TO REPRODUCE

```
git clone https://github.com/mbigras/ansible_systemd
cd ansible_systemd
vagrant up
ansible-playbook playbook.yml
```

```yaml
---
- hosts: all
  tasks:
    - name: run systemctl stop foo*.service --user
      shell: systemctl stop foo*.service --user

    - name: run systemctl stop foo.service --user
      shell: systemctl stop foo.service --user
      ignore_errors: yes

    - name: run systemctl stop foo*.service --user
      systemd:
        name: foo*.service
        scope: user
        state: stopped
      ignore_errors: yes

    - name: run systemctl stop foo.service --user
      systemd:
        name: foo.service
        scope: user
        state: stopped
      ignore_errors: yes
```

##### EXPECTED RESULTS

The `run systemctl stop foo*.service --user` systemd task should succeed.

```
    - name: run systemctl stop foo*.service --user
      systemd:
        name: foo*.service
        scope: user
        state: stopped
      ignore_errors: yes
```

##### ACTUAL RESULTS

Observe how systemctl through the shell module silently ignores units that don't match the glob pattern, however, with the systemd module the task fails with error message:

```
Could not find the requested service foo*.service: host
```

```
$ ansible-playbook playbook.yml

PLAY [all] *****************************************************************************

TASK [Gathering Facts] *****************************************************************
ok: [192.168.33.10]

TASK [run systemctl stop foo*.service --user] ******************************************
changed: [192.168.33.10]

TASK [run systemctl stop foo.service --user] *******************************************
fatal: [192.168.33.10]: FAILED! => {"changed": true, "cmd": "systemctl stop foo.service --user", "delta": "0:00:00.003811", "end": "2019-04-17 23:33:27.925116", "msg": "non-zero return code", "rc": 5, "start": "2019-04-17 23:33:27.921305", "stderr": "Failed to stop foo.service: Unit foo.service not loaded.", "stderr_lines": ["Failed to stop foo.service: Unit foo.service not loaded."], "stdout": "", "stdout_lines": []}
...ignoring

TASK [run systemctl stop foo*.service --user] ******************************************
fatal: [192.168.33.10]: FAILED! => {"changed": false, "msg": "Could not find the requested service foo*.service: host"}
...ignoring

TASK [run systemctl stop foo.service --user] *******************************************
fatal: [192.168.33.10]: FAILED! => {"changed": false, "msg": "Could not find the requested service foo.service: host"}
...ignoring

PLAY RECAP *****************************************************************************
192.168.33.10              : ok=5    changed=2    unreachable=0    failed=0
```
