### ISSUE TITLE
DEFAULT_JINJA2_NATIVE causes escaping issues

### ISSUE THREAD

**Issue by wilmardo** [ansible/ansible#55517]
##### SUMMARY
The ANSIBLE_JINJA2_NATIVE option expands escaped character totally wrong.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
jinja2

##### ANSIBLE VERSION

```paste below
ansible 2.8.0b1
  config file = None
  configured module search path = ['/c/Users/wilmaro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /c/Users/wilmaro/Development/Intermax/Gitlab/configuration-management/roles/win-cmdb-state-sync/venv/lib/python3.6/site-packages/ansible
  executable location = /c/Users/wilmaro/Development/Intermax/Gitlab/configuration-management/roles/win-cmdb-state-sync/venv/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
DEFAULT_JINJA2_NATIVE(env: ANSIBLE_JINJA2_NATIVE) = True
```

##### STEPS TO REPRODUCE

```yaml
# Run export ANSIBLE_JINJA2_NATIVE=True first
---
- hosts: localhost
  gather_facts: false
  vars:
    old_dvd_drive_letter: B
    new_dvd_drive_letter: E
  tasks:
    - name: Move DVD drive to new letter
      win_shell:
        Set-CimInstance
          -Query 'SELECT * FROM Win32_Volume
                  WHERE DriveLetter
                  LIKE "{{ old_dvd_drive_letter }}{{ ':' }}"'
          -Arguments {{ '@{' }} DriveLetter='{{ new_dvd_drive_letter }}:' {{ '}' }}
```

##### EXPECTED RESULTS

The command to be expanded to:

```powershell
Set-CimInstance -Query 'SELECT * FROM Win32_Volume WHERE DriveLetter LIKE "E:"' -Arguments @{ DriveLetter='B:' }
```

##### ACTUAL RESULTS

The command get expanded wrong, with multiple `-Argument` when not specified

```powershell
Set-CimInstance -Query 'SELECT * FROM Win32_Volume WHERE DriveLetter LIKE "D:"' -Arguments :"' -Arguments @{ DriveLetter='B:' }:' }
```

```
ok: [add-disk-expand-disk-vm1] =>
      output:
        changed: true
        cmd: Set-CimInstance -Query 'SELECT * FROM Win32_Volume WHERE DriveLetter LIKE "D:"' -Arguments :"' -Arguments @{ DriveLetter='B:' }:' }
        delta: '0:00:00.421881'
        end: '2019-04-18 10:49:58.773210'
        failed: false
        rc: 0
        start: '2019-04-18 10:49:58.351329'
        stderr: |-
          The string is missing the terminator: ".
              + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
             ception
              + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
        stderr_lines:
        - 'The string is missing the terminator: ".'
        - '    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx '
        - '   ception'
        - '    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString'
        stdout: ''
        stdout_lines: []
```
