### ISSUE TITLE
os_port sends binding:vnic_type=normal without requested

### ISSUE THREAD

**Issue by dominikholler** [ansible/ansible#55525]
##### SUMMARY

On creating a new OpenStack port, os_port sends `binding:vnic_type="normal"` without requested.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_port
##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.9.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

fedora 28

##### STEPS TO REPRODUCE

Apply the following playbook

```yaml
---
- name: Create network net10
  os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: net10
  register: net10

- name: Create port net10_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: present
    name: net10_port1
    network: net10
    fixed_ips:
      - ip_address: 10.10.0.11
```

##### EXPECTED RESULTS

The request to create the port is sent without the attribute `binding:vnic_type` is set.

##### ACTUAL RESULTS

The request to create the port is sent with `binding:vnic_type=normal`

```paste below

```
