### ISSUE TITLE
os_port exects binding:vnic_type

### ISSUE THREAD

**Issue by dominikholler** [ansible/ansible#55524]
##### SUMMARY
Ansible fails on an update of an OpenStack port if the server does not report the attribute
`binding:vnic_type` of a port.
Ansible should not assume that the server reports this attribute because this attribute is part of the optional port binding extension of the OpenStack API.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_port

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.9.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
fedora 28

##### STEPS TO REPRODUCE

Apply the following playbook two times

```yaml
---
- name: Create network net10
  os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: net10
  register: net10

- name: Create port net10_port1
  os_port:
    cloud: "{{ cloud_name }}"
    state: present
    name: net10_port1
    network: net10
    fixed_ips:
      - ip_address: 10.10.0.11
```

##### EXPECTED RESULTS

Second run of the playbook succeeds without update.

##### ACTUAL RESULTS

```paste below
al: [localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"keystoneauth.identity.generic.base\"\nTraceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1555597535.79-177140408209916/AnsiballZ_os_port.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1555597535.79-177140408209916/AnsiballZ_os_port.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1555597535.79-177140408209916/AnsiballZ_os_port.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_os_port_payload_wiDsZ4/__main__.py\", line 410, in <module>\n  File \"/tmp/ansible_os_port_payload_wiDsZ4/__main__.py\", line 393, in main\n  File \"/tmp/ansible_os_port_payload_wiDsZ4/__main__.py\", line 236, in _needs_update\nKeyError: 'binding:vnic_type'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
