### ISSUE TITLE
Vmware: vmware_guest can't clone VM when datastore is specify in disk list

### ISSUE THREAD

**Issue by GrandeTartine** [ansible/ansible#55551]
##### SUMMARY
With ansible 2.8.0b1, when I try to clone a VM with one or many disks, when I specify the target datastore in the disk list, the clone failed with an error : "Unable to finish the operation because the file or the directory [stomaq02-maq-target1-lun02] test-1804/test-1804.vmdk already exist."

The file does not already exist.

If I do it in 2 step, it's not failing (like that: https://gist.github.com/GrandeTartine/09f42522cf19609e7859fcb156c04094).
But In the vcenter, for the second disk, the disk file is set to: [stomaq02-maq-target1-lun02]. So just the datastore and not the good one... And the file for this disk doesn't exist on any any of the datastore.
It shoud be "[stomaq01-maq-target1-lun01]test-20190419-2/test-20190419-2_1.vmdk or something like that.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
2.8.0b1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Vcenter 6.5

##### STEPS TO REPRODUCE

ansible-playbook playbook.yml

```yaml
---
- name: VM Creation
  hosts: localhost
  gather_facts: no
  connection: local

  # Need this hack with variables because we can't give specific
  # authentication informations for each vcenter in AWX
  vars_files:
  - vars/vault
  vars:
    vcenter_name: "vcmaq3-lyo.maquette.hosting.infra"
#  - vars/vault-template-maq

  pre_tasks:
  - name: Set login informations for the needed Vcenter.
    include_vars:
      file: vars/{{vcenter_name}}.yml

  tasks:
  - name: Clone template to new VM
    vmware_guest:
      # Vcenter needed informations
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs | default(True) }}"

      # VM identification
      datacenter: "DC-MAQ6"
      cluster: "MAQ-ESX6.5"
      folder: "test"
      name: "test-20190419-2"

      # vm to clone
      template: "MOD_CENTOS7_US"
      disk:
       - datastore: "stomaq02-maq-target1-lun02"
         size_gb: 20
         type: "eagerzeroedthick"
```

##### EXPECTED RESULTS

VM cloned.

##### ACTUAL RESULTS

```paste below
(vmware-2.8) [root@awx test-2.8]# ansible-playbook CreateVM.yml --ask-vault-pass -vvvv
ansible-playbook 2.8.0b1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/vmware-2.8/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/vmware-2.8/bin/ansible-playbook
  python version = 3.6.6 (default, Jan 26 2019, 16:53:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Vault password:
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /var/lib/awx/venv/vmware-2.8/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: CreateVM.yml **********************************************************************************************************************************************************************************************************************
Positional arguments: CreateVM.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
ask_vault_pass: True
forks: 5
1 plays in CreateVM.yml
Read vars_file 'vars/vault'
Read vars_file 'vars/vault'
Read vars_file 'vars/vault'

PLAY [VM Creation] **************************************************************************************************************************************************************************************************************************
Read vars_file 'vars/vault'

TASK [Set login informations for the needed Vcenter.] ***************************************************************************************************************************************************************************************
task path: /var/lib/awx/projects/test-2.8/CreateVM.yml:16
ok: [localhost] => {
    "ansible_facts": {
        "vcenter_hostname": "vcmaq3-lyo.maquette.hosting.infra",
        "vcenter_password": "{{ vault_vcmaq3_password }}",
        "vcenter_username": "{{ vault_vcmaq3_username }}",
        "vcenter_validate_certs": false
    },
    "ansible_included_var_files": [
        "/var/lib/awx/projects/test-2.8/vars/vcmaq3-lyo.maquette.hosting.infra.yml"
    ],
    "changed": false
}
META: ran handlers
Read vars_file 'vars/vault'

TASK [Clone template to new VM] *************************************************************************************************************************************************************************************************************
task path: /var/lib/awx/projects/test-2.8/CreateVM.yml:21
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fb2456ede48> for vault_id=default
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7fb2456ede48> for vault_id=default
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885 `" && echo ansible-tmp-1555665130.5631893-43234056935885="` echo /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885 `" ) && sleep 0'
Using module file /var/lib/awx/venv/vmware-2.8/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-7833u2_ibpb9/tmp7kf4umxj TO /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885/AnsiballZ_vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885/ /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/var/lib/awx/venv/vmware-2.8/bin/python36 /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1555665130.5631893-43234056935885/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "MAQ-ESX6.5",
            "convert": "eagerzeroedthick",
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "DC-MAQ6",
            "datastore": null,
            "disk": [
                {
                    "datastore": "stomaq02-maq-target1-lun02",
                    "size_gb": 20,
                    "type": "eagerzeroedthick"
                }
            ],
            "esxi_hostname": null,
            "folder": "test",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": "2048",
                "num_cpus": "2"
            },
            "hostname": "vcmaq3-lyo.maquette.hosting.infra",
            "is_template": false,
            "linked_clone": false,
            "name": "test-20190419-2",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredoff",
            "state_change_timeout": 0,
            "template": "MOD_CENTOS7_US",
            "use_instance_uuid": false,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Failed to create a virtual machine : Impossible de terminer l’opération car le fichier ou le dossier [stomaq02-maq-target1-lun02] test-20190419-2/test-20190419-2.vmdk existe déjà"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @ckotte @dav1x @lparkes @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@GrandeTartine, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Tomorrow9** [comment]
Hi @GrandeTartine, the disk you set in the playbook is the first disk of deployed VM, if you want to add a new one, there should be two disk elements as you do in the no failing playbook.
- datastore: "the datastore of the deployed VM's first disk"
   size_gb: 20
- datastore: "the datastore of the new added disk"
   size_gb: 10
   type: "eagerzeroedthick"

**Comment by GrandeTartine** [comment]
Hi @Tomorrow9. Thanks for your reply. Yes, I knew that, this test playbook was only to show that there is also a problem even if I don't try to add a second disk.
In fact I think there are multiple different problems. When I clone the existing VM, where it fail even without adding disk, and when I try to add a disk on a existing VM, where it fail to create the disk and it badly configure the VM even if the task is not failed.

These problems seem to be new in 2.8.x. I can't reproduce them in 2.7.x.

**Comment by Tomorrow9** [comment]
@GrandeTartine, let's resolve the issue one by one. So the first one is if you don't add new disk, just configure the first one? Below 3 parameters are all changed from the template VM? then you get the error.
- datastore: "stomaq02-maq-target1-lun02"
   size_gb: 20
   type: "eagerzeroedthick"

**Comment by GrandeTartine** [comment]
@Tomorrow9 Yes.
For example
playbook: https://gist.github.com/GrandeTartine/6b45a034c0406b7d37a7723f599cd1fd
result: https://gist.github.com/GrandeTartine/bf70f44e2bb56bd7809080e492ffbfea

The only way I founded in 2.8.x to clone a VM, is to not specify disk configuration, and specify datastore outside the disk list : 
playbook: https://gist.github.com/GrandeTartine/0ced22a66901091b35aa0a4db63b207d
resultat: https://gist.github.com/GrandeTartine/9d4522f1aa30ca5261da416f8a912c46

**Comment by Tomorrow9** [comment]
Hi @GrandeTartine, I can reproduce this issue in my env. And just set the "datastore" parameter under "disk" part to another "datastore" on the ESXi host with the different disk size of template will trigger this issue. Found that if the "disk.size_gb" is set to the same value in template, there will be no error. I'll take a look at this.
Just let you know that there is module: vmware_guest_disk, can also be used to reconfigure the deployed VM's disk configuration. Thanks.

**Comment by GrandeTartine** [comment]
Hi @Tomorrow9  thanks for your feed backs. I'll take look at vmware_guest_disk to see if I can easily adapt my playbook and avoid this bug

**Comment by davyvandelaar** [comment]
Hi, I have a similiar issue when trying to use the datastore option with disk.size_gb in the develop version of Ansible. At first it seems to be going okay and it is deploying the vm's. However when the vm's reach 100% in the VMware pane it throws an error: 
`
    "msg": "Failed to create a virtual machine : Cannot complete the operation because the file or folder /vmfs/volumes/e9f64481-5xxxxxxx/********/********.vmdk already exists"

testvmdlr028               : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
testvmdlr029               : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
testvmdlr030               : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
testvmdlr031               : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

`
It actually puts the asterisks there, that is not redacted.
When switching back to the current version of Ansible it deploys the vm's without a problem.
`
ansible 2.9.0.dev0
  config file = /home/laard00/ansible/gitprojects/adp-vmware-winvm/ansible.cfg
  configured module search path = [u'/home/laard00/ansible/gitprojects/adp-vmware-winvm/library']
  ansible python module location = /srv/software/ansible-devel/lib/ansible
  executable location = /srv/software/ansible-devel/bin/ansible
`
code used:
`
    datastore: "{{ vm_os_datastore }}"
    disk:
    - size_gb: "{{ vm_size_of_disk_1_gb }}"
    - size_gb: "{{ vm_size_of_disk_2_gb }}"
`

and for testing purposes:
`
    disk:
    - size_gb: "{{ vm_size_of_disk_1_gb }}"
      datastore: "{{ vm_os_datastore }}"
    - size_gb: "{{ vm_size_of_disk_2_gb }}"
      datastore: "{{ vm_os_datastore }}"
`

I am aware there is also a vmware_guest_disk module, although for our specific purpose it would make more sense for us to use these variables in the vmware_guest module.

Hope someone can help. Posted my comment here because it seems very closely related.
Thanks, Davy

**Comment by ansibot** [comment]
cc @goneri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nickcn** [comment]
Hello,

Bug also appears in 2.8.0 stable. When cloning from template, I must use the disk size specified in the template in order for the process to complete. It seems the datastore option is honored though (cloning to different datastore but with same size as the template, works). I also tried same datastore as template different size, still not working, so we can assume that the bug is resizing?

Please let me know if I can be of any assistance.

Thanks.

**Comment by makrohn** [comment]
Hi,

I'm also running into this on 2.8.0 stable. Same symptoms - I get the error `"Failed to create a virtual machine : Cannot complete the operation because the file or folder /vmfs/volumes/5a0adbe0-0fe7ebeb-4a73-246e968a2298/krohn-test/krohn-test.vmdk already exists"`. VCenter 6.5.

If I don't specify the disk size, it deploys without a problem.

Thanks.

**Comment by makrohn** [comment]
I've found a workaround: If you clone the template, resize the disk, and power on the VM as three separate steps, you can do what you need to do.

Pre-2.8.0 working play:
``` yaml
- name: Deploy a VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: service-ansible
    password: "{{ ansible_pass }}"
    validate_certs: no
    folder: /{{ esxi_datacenter }}/vm
    datacenter: "{{ esxi_datacenter }}"
    datastore: "{{ datastore }}"
    state: poweredoff
    name: "{{ instance_name }}"
    template: "{{ esxi_template }}"
    disk:
    - size_gb: "{{ drive_size_gb }}"
    hardware:
      memory_mb: "{{ ram_mb }}"
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy_results
```
Results in the following error in 2.8.0 Stable
>TASK [Deploy a VM] ********************************************************************
Tuesday 21 May 2019  08:52:34 -0400 (0:00:00.031)       0:00:00.743 *********** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create a virtual machine : Cannot complete the operation because the file or folder /vmfs/volumes/5a0adbe0-0fe7ebeb-4a73-246e968a2298/krohn-test/krohn-test.vmdk already exists"}

Workaround:
``` yaml
- name: Depoy a VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: service-ansible
    password: "{{ ansible_pass }}"
    validate_certs: no
    folder: /{{ esxi_datacenter }}/vm
    datacenter: "{{ esxi_datacenter }}"
    datastore: "{{ datastore }}"
    state: poweredoff
    name: "{{ instance_name }}"
    template: "{{ esxi_template }}"
    hardware:
      memory_mb: "{{ ram_mb }}"
  delegate_to: localhost

- name: Resize disk
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: service-ansible
    password: "{{ ansible_pass }}"
    validate_certs: no
    state: present
    name: "{{ instance_name }}"
    disk:
    - size_gb: "{{ drive_size_gb }}"
  delegate_to: localhost

- name: power on VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: service-ansible
    password: "{{ ansible_pass }}"
    validate_certs: no
    state: poweredon
    name: "{{ instance_name }}"
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy_results
```
Result:
>TASK [Depoy a VM] ********************************************************************
Tuesday 21 May 2019  09:42:35 -0400 (0:00:00.027)       0:00:00.704 *********** 
changed: [localhost]

>TASK [Resize disk] *******************************************************************
Tuesday 21 May 2019  09:43:08 -0400 (0:00:32.437)       0:00:33.141 *********** 
changed: [localhost]

>TASK [power on VM] *******************************************************************
Tuesday 21 May 2019  09:43:13 -0400 (0:00:05.119)       0:00:38.260 *********** 
changed: [localhost]
