### ISSUE TITLE
vmware_guest: "msg": "Failed to create a virtual machine : A specified parameter was not correct: nicsettings:adapter:ip"

### ISSUE THREAD

**Issue by andrew80k** [ansible/ansible#55560]
##### SUMMARY
I have tried a bunch of different stuff to get this working all to no avail.  Any insight would be great.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest
##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT

RHEL7

##### STEPS TO REPRODUCE

```yaml
- name: Clone a virtual machine from template
  vmware_guest:
    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    hostname: "{{ vm_host }}"
    username: "{{ ansible_connect_user }}"
    password: "{{ ansible_user_pwd }}"
    validate_certs: no
    state:  "{{ vm_state | default('poweredon') }}"
    name: "{{ inventory_hostname }}"
    template: "{{ vm_template |default(omit)}}"
    networks: "{{ vm_networks }}"
    disk: "{{ vm_disks }}"
    hardware: "{{ vm_hardware }}"
    annotation: "{{ vm_annotation | default('Ansible Managed') }}"
    customvalues: "{{ vm_customvalues | default(omit) }}"
    customization: "{{ vm_customization | default(omit) }}"
    customization_spec: "{{ vm_customization_spec | default(omit) }}"
    folder: "{{ vm_folder | default(omit) }}"
    guest_id: "{{ vm_guest_id | default(omit) }}"
    wait_for_ip_address: true
  delegate_to: localhost

```

##### EXPECTED RESULTS

Powered on VM.

##### ACTUAL RESULTS

```paste below
fatal: [my-answin-1 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": "Ansible Managed", 
            "cdrom": {}, 
            "cluster": "Local-NP", 
            "customization": {}, 
            "customization_spec": "DEV Server 2016", 
            "customvalues": [
                {
                    "key": "tools.syncTime", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.continue", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.restore", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.resume.disk", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.shrink", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.tools.startup", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.tools.enable", 
                    "value": 0
                }, 
                {
                    "key": "time.synchronize.resume.host", 
                    "value": 0
                }
            ], 
            "datacenter": "Local-US", 
            "datastore": null, 
            "disk": [
                {
                    "autoselect_datastore": false, 
                    "datastore": "NP_DScluster", 
                    "size_gb": 100, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "Discovered virtual machine", 
            "force": false, 
            "guest_id": "", 
            "hardware": {
                "memory_mb": 4096, 
                "num_cpus": 2, 
                "scsi": "paravirtual"
            }, 
            "hostname": "my-cluter-host", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "get-answin-1", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "domain": "domain.com", 
                    "gateway": "", 
                    "ip": "", 
                    "name": "E-ADMIN-DEV", 
                    "netmask": "", 
                    "type": "static"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "present", 
            "state_change_timeout": 0, 
            "template": "W2K16", 
            "username": "test-user", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "Failed to create a virtual machine : A specified parameter was not correct: nicsettings:adapter:ip"
```
