### ISSUE TITLE
notify calls an unexpected listener

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible#55575]
##### SUMMARY

Call an unexpected handler.

The string specified by notify seems to match as an intermediate match of the listener string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

handler, notify, listener

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.0b1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible2800/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/ansible2800/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

##### STEPS TO REPRODUCE

Run the following Playbook.

```yaml
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name:
      command: echo "changed"
      notify: handler

  handlers:
    - name: h
      debug:
        msg: notified handler
      listen: handler

    - name: h2
      debug:
        msg: notified handler2
      listen: handler2

    - name: h3
      debug:
        msg: notified handler3
      listen:
        - handler3
```

##### EXPECTED RESULTS

I expect that it notified only listen: handler. (likes in ansible 2.7.10)
```
$ ansible-playbook -i localhost, listener.yml 

PLAY [localhost] **************************************************************************

TASK [command] ****************************************************************************
changed: [localhost]

RUNNING HANDLER [h] ***********************************************************************
ok: [localhost] => {
    "msg": "notified handler"
}

PLAY RECAP ********************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

##### ACTUAL RESULTS

But it notified `listen: handler` and `listen: handler2`.

```paste below
$ ansible-playbook -i localhost, listener.yml 

PLAY [localhost] **************************************************************************

TASK [command] ****************************************************************************
changed: [localhost]

RUNNING HANDLER [h] ***********************************************************************
ok: [localhost] => {
    "msg": "notified handler"
}

RUNNING HANDLER [h2] **********************************************************************
ok: [localhost] => {
    "msg": "notified handler2"
}

PLAY RECAP ********************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```
If notify is specified as a list rather than a string, it seems an exact match.
