### ISSUE TITLE
docker_swarm_service secrets with gid/uid/mode

### ISSUE THREAD

**Issue by zoredache** [ansible/ansible#55581]
##### SUMMARY
Attempting to pass a uid/gid/mode as part of a secret for the docker_swarm_service module is either broken, or how to pass correctly it isn't obvious from the docs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module: docker_swarm_service

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = ./ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Target system is running Debian 9

# docker --version
Docker version 18.09.3, build 774a1f4
```

##### STEPS TO REPRODUCE

A play with a task like this will result in an error with Traceback.

```yaml
  - name: Test
    ignore_errors: yes
    docker_swarm_service:
      name: foo
      image: busybox:latest
      args:
      - "sleep"
      - "900"
      secrets:
      - secret_id: "{{ secret_id }}"
        secret_name: foo
        uid: 1000

```

A full playbook that tests a variety of possible options, and the output can be found here.

- https://gist.github.com/zoredache/39d7734a3a124a81ab9908a5928335d8

##### EXPECTED RESULTS

I  expect it to create a swarm service, with a 'secret' mounted with the correct owner/group/mode

##### ACTUAL RESULTS

I am getting a traceback with a docker APIError

```paste below
docker.errors.APIError: 400 Client Error: Bad Request ("json: cannot unmarshal number into Go struct field SecretReferenceFileTarget.UID of type string")

```
