### ISSUE TITLE
Migration from with_items to loop not clear

### ISSUE THREAD

**Issue by aparedero** [ansible/ansible#55596]
##### SUMMARY
Not sure if is either documentation or bug reportn but at the time of this writing I'm migrating a simple "with_items" loop with the new keyword "loop" and if the content of the loop keyword is the variable which contains the dictionary it fails. I've used flatten modifier and dict2items with no success.

The variable is a list of dictionaries, so the old way is to use "with_items:" keyword. But the current documentations is confusing as there is no an example about this scenario

So the loop keyword detect dictionary as a list

##### ISSUE TYPE
- Documentation

##### COMPONENT NAME

loop
##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Linux master 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Just play minimal playbook with ansible-playbook -i localhost file.yaml

```yaml
---
- hosts: localhost
  vars:
    usuarios:
      - {nombre: user1, grupos: root }
      - { nombre: user2, grupos: root }
  tasks:
    - name: Añade nuevos usuarios
      user:
        name: "{{ item.nombre }}"
        state: absent
        groups: "{{ item.grupos }}"
      #with_items:
      loop:
        - "{{ usuarios }}"
        #- "{{ usuarios |flatten(levels=1) }}"
...
```

##### EXPECTED RESULTS

TASK [Añade nuevos usuarios] ********************************************************************************************************************************************************************************
ok: [localhost] => (item={u'grupos': u'root', u'nombre': u'user1'})
ok: [localhost] => (item={u'grupos': u'root', u'nombre': u'user2'})

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0  

##### ACTUAL RESULTS

TASK [Añade nuevos usuarios] ********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '**list object' has no attribute 'nombre**'\n\nThe error appears to have been in '/vagrant/Ejercicios/5. Variables/loops.yml': line 51, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Añade nuevos usuarios\n      ^ here\n"}

```paste below
ansible-playbook -i inventory loop_test.yml
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aparedero** [comment]
I discovered that ```loop: "{{ usuarios }}" ``` works. 

But this way does not: ```
loop: 
  - "{{ usuarios }}"
```
With with_items, both ways are working:
 ```with_items: "{{ usuarios }}" ```

```
with_items: 
  - "{{ usuarios }}"
```

---
- hosts: localhost
  vars:
    usuarios:
      - nombre: user1
        grupos: root }
      - { nombre: user2, grupos: root }
  tasks:
    - name: Añade nuevos usuarios
      user:
        name: "{{ item.nombre }}"
        state: absent
        groups: "{{ item.grupos }}"
      loop: "{{ usuarios }}"
...
```

Well I was used to write all loops in a new line in order to be cleaner but it seems new loop keyword doesn't like that. I'm not sure if this can be considered either a bug or not.
