### ISSUE TITLE
No package matching 'nginx' found available, installed or updated

### ISSUE THREAD

**Issue by demogebruiker** [ansible/ansible#55638]
##### SUMMARY
when II run ansible-playbook configure.yml --ask-pass 
on centos 7 x64 I get error

##### ISSUE TYPE
fatal: [coderebels]: FAILED! => {"changed": false, "msg": "No package matching 'nginx' found available, installed or updated", "rc": 126, "results": ["No package matching 'nginx' found available, installed or updated"]}

##### COMPONENT NAME
On another centos it runs perfect. Burg when I make a new droppelt on Digital Ocean this bug happens.

##### ANSIBLE VERSION

```
ansible-playbook 2.7.10
  config file = /Users/timvogt/Software_projects/Backend/ansible_server_scripts/ansible.cfg
  configured module search path = [u'/Users/timvogt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
osx to centos 7 x64

##### STEPS TO REPRODUCE

**handler/main.yml**
```
- name: restart nginx
  service: name=nginx state=restarted

```

**tasks/main.yml**
```
- name: "Install Nginx"
  become: yes
  yum:
    name: nginx
    state: latest

- name: "Update Nginx config"
  become: yes
  copy:
    src: ./data/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Create sites-available directory
  become: yes
  file: path=/etc/nginx/sites-available state=directory

- name: Create sites-enabled directory
  become: yes
  file: path=/etc/nginx/sites-enabled state=directory

- name: "Update Nginx default config"
  become: yes
  copy:
    src: ./data/nginx/default
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: "Enable Nginx site config"
  become: yes
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - restart nginx

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  become: yes
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  notify:
    - restart nginx

- name: restart nginx
  service: name=nginx state=restarted
```

**ngnix.conf**
```
user root;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}

```

##### EXPECTED RESULTS
To run the boek without errors and install ngnix

##### ACTUAL RESULTS
```
fatal: [coderebels]: FAILED! => {"changed": false, "msg": "No package matching 'nginx' found available, installed or updated", "rc": 126, "results": ["No package matching 'nginx' found available, installed or updated"]}
        to retry, use: --limit @/Users/timvogt/Software_projects/Backend/ansible_server_scripts/configure.retry
```
