### ISSUE TITLE
Ansible 2.7.10 Bug - Failed to transfer file to /tmp/ansible/ansible-tmp-1556025517.87-250300098554941/AnsiballZ_setup.py: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by yami12376** [ansible/ansible#55647]
ansible --version
ansible 2.7.10

CentOS 7.6

 python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

Example playbook:
```

---
- hosts: localhost
  vars:
    node_version: 8.11.3
    nvm_version: 0.33.11

  tasks:

    - name: install wget
      become: true
      yum:
        name: wget
        state: latest
      become_flags: '-H -S'    

    - name: download nvm
      get_url:
        url: https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh
        dest: ~/nvm-install.sh

    - name: Changing perm of "/opt/nvm-install.sh", adding "+x"
      file:
        dest: ~/nvm-install.sh
        mode: "a+x"

    - name: Execute the script
      command: ~/nvm-install.sh
      args:
        creates: ~/.nvm/nvm.sh

    - name: Changing perm of "~/.nvm/nvm.sh", adding "+x"
      file:
        dest: ~/.nvm/nvm.sh
        mode: "a+x"

    - name: install node
      shell: |
        . ~/.nvm/nvm.sh
        nvm install {{ node_version }}
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}"

    - name: install jsreport-cli
      shell: |
        . ~/.nvm/nvm.sh
        npm install jsreport-cli -g
      args:
        creates: "~/.nvm/versions/node/v{{ node_version }}/lib/node_modules/jsreport-cli"

    - name: create jsreportapp directory
      file:
        path: ./jsreportapp
        state: directory

    - name: init jsreportapp directory
      shell: |
        . ~/.nvm/nvm.sh
        jsreport init
      args:
        chdir: ./jsreportapp
        creates: ./package-lock.json
```

when running like that:
` ansible-playbook 2_installJsReport.yml   --ask-sudo-pass`
And /etc/ansible/ansible.cfg got:

`remote_tmp     =  /tmp/ansible
`
i get an error after providing valid sudo password:

> 
> PLAY [localhost] ****************************************************************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
> fatal: [localhost]: FAILED! => {"msg": "failed to transfer file to /tmp/ansible/ansible-tmp-1556025975.13-119786583601338/AnsiballZ_setup.py: [Errno 13] Permission denied: '/tmp/ansible/ansible-tmp-1556025975.13-119786583601338/AnsiballZ_setup.py'"}
> 

If i comment: 
`remote_tmp     =  /tmp/ansible`

The output of that command will be:

> 
> PLAY [localhost] ****************************************************************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
> fatal: [localhost]: FAILED! => {"msg": "failed to transfer file to /home/kwitkowski1/.ansible/tmp/ansible-tmp-1556026091.06-248969949108757/AnsiballZ_setup.py: [Errno 13] Permission denied: '/home/userName/.ansible/tmp/ansible-tmp-1556026091.06-248969949108757/AnsiballZ_setup.py'"}
> 

```
[username@C .ansible]$ cd tmp
[username@C tmp]$ ls
ansible-tmp-1556022599.78-96582690576423  ansible-tmp-1556022938.2-246302224526129  ansible-tmp-1556023600.6-33974194176869  ansible-tmp-1556026091.06-248969949108757
[username@C tmp]$ cat ansible-tmp-1556022599.78-96582690576423
cat: ansible-tmp-1556022599.78-96582690576423: Permission denied
[username@C tmp]$ ls -lh
total 0
drwx------. 2 root username 6 Apr 23 14:29 ansible-tmp-1556022599.78-96582690576423
drwx------. 2 root username 6 Apr 23 14:35 ansible-tmp-1556022938.2-246302224526129
drwx------. 2 root username 6 Apr 23 14:46 ansible-tmp-1556023600.6-33974194176869
drwx------. 2 root username 6 Apr 23 15:28 ansible-tmp-1556026091.06-248969949108757
[username@C tmp]$ pwd
/home/username/.ansible/tmp
[username@C tmp]$


```
