### ISSUE TITLE
include_tasks and check_mode

### ISSUE THREAD

**Issue by esuarezsantana** [ansible/ansible#55657]
##### SUMMARY
`check_mode` is not propagated when used with `include_tasks`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- check_mode
- include_tasks

##### ANSIBLE VERSION
```
ansible 2.7.9
  config file = /home/eduardo/.ansible.cfg
  configured module search path = ['/home/eduardo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/virtual/python/virtualenv/ansible/lib/python3.6/site-packages/ansible
  executable location = /usr/local/virtual/python/virtualenv/ansible/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 09:26:25) [GCC 8.2.0]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/home/eduardo/.ansible.cfg) =['/home/eduardo/grow/setup/ansible/roles']
RETRY_FILES_ENABLED(/home/eduardo/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux mypc 4.19.19-edu83+ #3 SMP PREEMPT Thu Jan 31 12:12:06 WET 2019 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
- `main.yml`

```yaml
---

- hosts: all
  gather_facts: false
  tasks:
    - include_tasks: 'check_only.yml'
      check_mode: true
```

- `check_only.yml`

```yaml
---

- name: copy file
  copy:
    content: 'I should not exist\n'
    dest: '/home/myusername/test.txt'
```

##### EXPECTED RESULTS
`test.txt` not created on server.

##### ACTUAL RESULTS
`test.txt` is created on server.

**Comment by sivel** [comment]
This is expected, and had been documented since 2.5 as part of https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#dynamic-includes-and-attribute-inheritance

As such, starting with 2.7 you can now do:

```
- hosts: all
  gather_facts: false
  tasks:
    - include_tasks: 
        file: 'check_only.yml'
        apply:
          check_mode: true
      check_mode: true
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
