### ISSUE TITLE
firewalld module changed the rule but it didn't return `changed` status

### ISSUE THREAD

**Issue by sugitk** [ansible/ansible#55683]
##### SUMMARY

firewalld module changed the rule but it didn't return `changed` status.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

firewalld

##### ANSIBLE VERSION

```paste below
2.7.6
```

It also still persists on 2.7.10.

##### CONFIGURATION

```paste below
(nothing)
```

##### OS / ENVIRONMENT

target OS version: RHEL 7.2

##### STEPS TO REPRODUCE

At first, prepare the firewall rule at RHEL 7.2.

```
# firewall-cmd --zone=trusted --change-interface=enp1s0f1.1013 --permanent
# firewall-cmd --zone=trusted --add-source=2404:01A8:FF00:2006::0/126 --permanent
# firewall-cmd --zone=trusted --add-source=2404:01A8:FF00:2006::1/126 --permanent
# firewall-cmd --reload
#
# firewall-cmd --list-all --zone=trusted
trusted (active)
  interfaces: enp1s0f1.1013
  sources: 2404:01A8:FF00:2006::0/126 2404:01A8:FF00:2006::1/126
  services: 
  ports: 
  masquerade: no
  forward-ports: 
  icmp-blocks: 
  rich rules: 
```

Execute this playbook (interface: enp1s0f1.1013 and source: "2404:01A8:FF00:2006::2/126", which is not defined in a firewall-cmd --list-all --zone=trusted)

```
---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "remove source from trusted zone"
      firewalld:
        interface: enp1s0f1.1013
        source: "2404:01A8:FF00:2006::2/126"
        state: disabled
        zone: trusted
        immediate: True
        permanent: True
      become: True
```

It matches only `interface`, so it will be removed successfully.

```
TASK [remove source from trusted zone] *********************************************************************************************************
changed: [192.168.0.28] => {"changed": true, "msg": "Permanent and Non-Permanent(immediate) operation, Permanent and Non-Permanent(immediate) operation, Removed enp1s0f1.1013 from zone trusted"}
```

Next, run this playbook with interface: enp1s0f1.1013 and source: "2404:01A8:FF00:2006::1/126".

```
---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "remove source from trusted zone"
      firewalld:
        interface: enp1s0f1.1013
        source: "2404:01A8:FF00:2006::1/126"
        state: disabled
        zone: trusted
        immediate: True
        permanent: True
      become: True
```

Then the source matches source and removed it, however it returns `ok` instead of `changed`.

```
TASK [remove source from trusted zone] *********************************************************************************************************
ok: [192.168.0.28] => {"changed": false, "msg": "Permanent and Non-Permanent(immediate) operation, Removed 2404:01A8:FF00:2006::1/126 from zone trusted, Permanent and Non-Permanent(immediate) operation"}
```

##### EXPECTED RESULTS

```
TASK [remove source from trusted zone] *********************************************************************************************************
changed: [192.168.0.28] => {"changed": true, "msg": "Permanent and Non-Permanent(immediate) operation, Removed 2404:01A8:FF00:2006::1/126 from zone trusted"}
```

##### ACTUAL RESULTS

```
TASK [remove source from trusted zone] *********************************************************************************************************
ok: [192.168.0.28] => {"changed": false, "msg": "Permanent and Non-Permanent(immediate) operation, Removed 2404:01A8:FF00:2006::1/126 from zone trusted, Permanent and Non-Permanent(immediate) operation"}
```
