### ISSUE TITLE
VMware: Support VMware SPBM Disk and VM Placement

### ISSUE THREAD

**Issue by vMarkusK** [ansible/ansible#55703]
##### SUMMARY

The VMware vmware_guest Module should support SPBM Disk and VM Placement. An override should also be possible per disk.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

vmware_guest

##### ADDITIONAL INFORMATION

```yaml
- name: Create vSphere VM {{ vm_name }}
  vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ clustername }}"
      folder: "{{ vm_folder }}"
      validate_certs: yes
      name: "{{ vm_name }}" 
      state: poweredoff
      guest_id: "{{guest_id}}"
      **storagepolicy: "{{ default_spbm }}"**
      disk:
        - size_gb: "{{ size_gb_0 }}"
      hardware:
          memory_mb: "{{ memory_mb }}"
          num_cpus: "{{ num_cpus }}"
          scsi: paravirtual
          boot_firmware: efi
      networks:
        - name: "{{ network_name }}"
          device_type: vmxnet3
      wait_for_ip_address: no
```
