### ISSUE TITLE
nclu: changed attribute is always True unless commit is specified

### ISSUE THREAD

**Issue by eikef** [ansible/ansible#55718]
##### SUMMARY

"changed"-attribute with nclu will never be False if any command possibly affecting pending buffer is issued (due to before/after comparison finding timestamp differences, or commands being appended) without also issuing a commit.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nclu

##### ANSIBLE VERSION
ansible 2.7.8

##### OS / ENVIRONMENT
CumulusLinux 3.7.3+

##### STEPS TO REPRODUCE

An example would be a fairly innocent command sequence setting IP and Gateway for the eth0 interface:

```yaml
- name: Configure management interface
  nclu:
    abort: true
    commands:
        - add int eth0 ip address 172.16.0.1/12
        - add int eth0 ip gateway 172.16.0.2
```

If you execute this play multiple times in a row, it will result as "changed" every time, even though no actual change has been performed (the commands certainly didn't change). 
The reason is that the nclu module naively compares the output of `nclu pending` before and after the commands are run. Since "abort" is specified, the pending buffers should essentially be the same -- but they contain timestamps. Those timestamps lead to a changed: True.

If you instead do

```yaml
- name: Configure management interface
  nclu:
    commands:
        - add int eth0 ip address 172.16.0.1/12
        - add int eth0 ip gateway 172.16.0.2
```
Changed will also always be true since the commands, even though they are the exact same, get appended to the pending buffer. They do not change the outcome at all, though.

If you instead do 

```yaml
- name: Configure management interface
  nclu:
    commit: True
    commands:
        - add int eth0 ip address 172.16.0.1/12
        - add int eth0 ip gateway 172.16.0.2
```

then no change is registered, working as expected.

##### EXPECTED RESULTS

nclu should return changed: False when no configuration change is actually effected on pending buffers.

One way to accomplish this would be to check for the existence of a "diff" field in the output of 
 `net pending json` to see whether the commands in the pending buffer actually effect a change of configuration or not.
Minimally though, the before/after-comparison should disregard timestamps and possibly duplicate commands. 

##### ACTUAL RESULTS

Changed: True on all but committed configuration changes.
