### ISSUE TITLE
nios_network: Option 242 can not have a use_option flag

### ISSUE THREAD

**Issue by codyhackw** [ansible/ansible#55722]
##### SUMMARY

While using the nios_network module, defining option 242 on a network causes the following error:

"msg": "Option Avaya_VOIP can not have a use_option flag",
    "operation": "create_object",
    "type": "AdmConProtoError"

Appears to be the same issue as #43657 (nios_network: Option vendor-encapsulated-options can not have a use_option flag), which covered option 43.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios_network

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/41676/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server 7.6

##### STEPS TO REPRODUCE

```yaml
tasks:
    - name: modify option242
      nios_network:
        network: 10.10.10.0/24
        provider:
          host: "{{ nios_provider }}"
          username: "{{ username }}"
          password: "{{ password }}"
        options:
          - num: 242
            value: "L2Q=1"
```

##### EXPECTED RESULTS

ok: [localhost]

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "code": "Client.Ibap.Proto", "msg": "Option Avaya_VOIP can not have a use_option flag", "operation": "update_object", "type": "AdmConProtoError"}
```
