### ISSUE TITLE
gcp_compute plugin inventory hostname as GCP hostname

### ISSUE THREAD

**Issue by Loki22** [ansible/ansible#55753]
##### SUMMARY

Add the ability to specify the GCP hostname as the inventory hostname instead of only the machine name, public IP, or private IP.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

gcp_compute inventory plugin
##### ADDITIONAL INFORMATION

First reason this would be useful is for convenient matching in playbooks and ad-hoc. Additionally however, with multiple projects in GCP it is conceivable and probable that there would be duplicate instance names. This creates a scenario where items would be "missing" from inventory graph as well as an issue where patterns could inadvertently match unintended nodes. Ex: `ansible 'webserver1' -m ping` (see example below)

Example GCP assets:
```yaml
prod_project:
  - name: webserver1
    hostname: webserver1.prod.company.com
  - name: webserver2
    hostname: webserver2.prod.company.com
stage_project:
  - name: webserver1
    hostname: webserver1.stage.company.com
dev_project:
  - name: webserver1
    hostname: webserver1.dev.company.com
```

Current result of `ansible-inventory --graph`: (only 2 hosts appear)
(assumes hostname ordering first item is 'name')
```
@all:
  |--@ungrouped:
  |  |--webserver1
  |  |--webserver2
```

Desired result if GCP hostname is usable:
(assumes hostname ordering first item is desired new feature 'gcp_hostname')
```
@all:
  |--@ungrouped:
  |  |--webserver1.prod.company.com
  |  |--webserver2.prod.company.com
  |  |--webserver1.stage.company.com
  |  |--webserver1.dev.company.com
```

Besides seeing a less misleading result in --graph, now playbook pattern matching is much simpler to match specific assets. For example, now we can match all webservers in prod by using 'webserver*.prod.company.com' whereas before there is no logical path to use.
