### ISSUE TITLE
azure_rm_virtualnetworkpeering bug when using remote resource id

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#55759]
##### SUMMARY

azure_rm_virtualnetworkpeering does not create peering when using remote virtual network resource id

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualnetworkpeering

##### ANSIBLE VERSION

```paste below
2.8.0b1
```

##### STEPS TO REPRODUCE

```yaml
- name: Create vnet peering customer -> domain
  azure_rm_virtualnetworkpeering:
    subscription_id: '{{ az_customer_subscription_id }}'
    ad_user: '{{ ad_user_login_var }}'
    password: '{{ ad_password_var }}'
    resource_group: '{{ resource_group }}'
    virtual_network: '{{ vnet }}'
    name: '{{customer_prefix}}-peering'
    remote_virtual_network:
      - "/subscriptions/{{ aad_subscription_id }}/resourceGroups/aad/providers/Microsoft.Network/virtualNetworks/aad-vnet"
```

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: expected string or buffer
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_azure_rm_virtualnetworkpeering_payload_qaFPyg/__main__.py\", line 403, in <module>\n  File \"/tmp/ansible_azure_rm_virtualnetworkpeering_payload_qaFPyg/__main__.py\", line 399, in main\n  File \"/tmp/ansible_azure_rm_virtualnetworkpeering_payload_qaFPyg/__main__.py\", line 219, in __init__\n  File \"/tmp/ansible_azure_rm_virtualnetworkpeering_payload_qaFPyg/ansible_azure_rm_virtualnetworkpeering_payload.zip/ansible/module_utils/azure_rm_common.py\", line 325, in __init__\n  File \"/tmp/ansible_azure_rm_virtualnetworkpeering_payload_qaFPyg/__main__.py\", line 237, in exec_module\n  File \"/tmp/ansible_azure_rm_virtualnetworkpeering_payload_qaFPyg/ansible_azure_rm_virtualnetworkpeering_payload.zip/ansible/module_utils/azure_rm_common.py\", line 461, in parse_resource_to_dict\n  File \"/usr/local/lib/python2.7/dist-packages/msrestazure/tools.py\", line 133, in parse_resource_id\n    match = _ARMID_RE.match(rid)\nTypeError: expected string or buffer\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualnetworkpeering.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yungezz @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nicolaibaralmueller, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yungezz** [comment]
looking at it

**Comment by yungezz** [comment]
hi @nicolaibaralmueller could you pls change `remote_virtual_network` to string instead of list in your playbook, as below. let me know if any other error met.
```
- name: Create vnet peering customer -> domain
  azure_rm_virtualnetworkpeering:
    subscription_id: '{{ az_customer_subscription_id }}'
    ad_user: '{{ ad_user_login_var }}'
    password: '{{ ad_password_var }}'
    resource_group: '{{ resource_group }}'
    virtual_network: '{{ vnet }}'
    name: '{{customer_prefix}}-peering'
    remote_virtual_network: "/subscriptions/{{ aad_subscription_id }}/resourceGroups/aad/providers/Microsoft.Network/virtualNetworks/aad-vnet"
```
