### ISSUE TITLE
Cloudwatch module does not catch exceptions when describing alarms

### ISSUE THREAD

**Issue by kjw1** [ansible/ansible#55786]
##### SUMMARY
The cloudwatch module describes existing alarms, but does not catch any exceptions hat may happen as a result. The module throws the exception, and the task is not retried.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_metric_alarm

##### ANSIBLE VERSION
I checked the devel branch, and it is still an issue
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Mar  2 2019, 06:02:23) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
    - name: "terminate: Delete CloudWatch System Alarm - {{ name }} StatusCheckFailed_System Alarm"
      ec2_metric_alarm:
        state: absent
        region: "{{ region }}"
        name: "{{ name }} StatusCheckFailed_System Alarm"
      tags:
        - cloudwatch
      retries: 20
      delay: 10

```

##### OS / ENVIRONMENT
An AWS account which is experiencing API throttling, causing describe actions to fail.

##### STEPS TO REPRODUCE
1. Exhaust your ec2 api describe API limit.
2. Create and delete ec2 metric alarm via the module until a throttling error is raised.

##### EXPECTED RESULTS
The module should fail cleanly.

##### ACTUAL RESULTS
The module throws an exception and does not retry
```
2019-04-26 00:11:00,046 p=50 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_y5VU_q/ansible_module_ec2_metric_alarm.py\", line 327, in <module>\n    main()\n  File \"/tmp/ansible_y5VU_q/ansible_module_ec2_metric_alarm.py\", line 320, in main\n    delete_metric_alarm(connection, module)\n  File \"/tmp/ansible_y5VU_q/ansible_module_ec2_metric_alarm.py\", line 263, in delete_metric_alarm\n    alarms = connection.describe_alarms(alarm_names=[name])\n  File \"/usr/local/lib/python2.7/site-packages/boto/ec2/cloudwatch/__init__.py\", line 382, in describe_alarms\n    [('MetricAlarms', MetricAlarms)])\n  File \"/usr/local/lib/python2.7/site-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.BotoServerError: BotoServerError: 400 Bad Request\n<ErrorResponse xmlns=\"http://monitoring.amazonaws.com/doc/2010-08-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>Throttling</Code>\n    <Message>Rate exceeded</Message>\n  </Error>\n  <RequestId>c5661b3a-67b7-11e9-aeaa-6fd6e091195a</RequestId>\n</ErrorResponse>\n\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
