### ISSUE TITLE
CloudFormation module optional flag to prevent waiting

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#55793]
##### SUMMARY
I would like to have an option to prevent the cloudformation module to trigger describe stack. Like a fire and forget method to create stacks not verifying if it was successful nor not.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
CloudFormation

##### ADDITIONAL INFORMATION

Currently long running stacks can fail i.e. if the token is invalidated. As a user for me it would be ok just to trigger the stack creation. Could be an option option like `prevent_describe_stack: yes.

```yaml
- name: Excecute compute-stack
        cloudformation:
          profile: default
          region: eu-central-1
          stack_name: "jenkins-{{ env }}"
          state: "{{ state }}"
          create_changeset: yes
          prevent_describe_stack: yes
          template_url: https://s3.eu-central-1.amazonaws.com/{{ s3_bucket }}/ansible/jenkins-compute.yml
          template_parameters: "{{ lookup('file', '../cfn/jenkins-local/'+ env +'/compute.json') }}"
```
