### ISSUE TITLE
junos_l2_interface & junos_linkagg idempotence issue

### ISSUE THREAD

**Issue by JBaptisme** [ansible/ansible#55802]
Hello team,
##### SUMMARY
Configuration done via junos_linkagg is removed by junos_l2_interface module 
(LACP mode: active)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
use of junos_linkagg and junos_l2_interface module in same playbook

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Mar 29 2019, 00:03:27) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
DEFAULT_TIMEOUT(/root/.ansible.cfg) = 120
HOST_KEY_CHECKING(/root/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/root/.ansible.cfg) = 120
PERSISTENT_CONNECT_TIMEOUT(/root/.ansible.cfg) = 160
```

##### OS / ENVIRONMENT
Centos 7 - Python 3.6 - Juniper EX3300 switchs release 12.3

##### STEPS TO REPRODUCE

```
 tasks:
    - name: Configure LACP
      junos_linkagg:
        name: "{{ item.key }}"
        description:  "{{ item.value.description }}"
        members: "{{ item.value.members }}"
        mode: active
      with_dict: "{{ my_interfaces }}"
      when:
        -  item.key | search("ae")

    - name: Configure vlans on LACP interfaces
      junos_l2_interface:
        enhanced_layer: false
        name: "{{ item.key }}"
        mode: "{{ 'trunk' if item.value.tagged_vlans}}"
        description:  "{{ item.value.description }}"
        native_vlan: "{{ item.value.untagged_vlan }}"
        trunk_vlans: "{{ item.value.tagged_vlans }}"
      with_dict: "{{ my_interfaces }}"
      when:
        -  item.key | search("ae")
```

##### EXPECTED RESULTS
After playbook execution, for interface ae0 for example:

```
ae0 {
    description test;
    aggregated-ether-options {
        lacp {
            active;
        }
    }
    unit 0 {
        family ethernet-switching {
            port-mode trunk;
            vlan {
                members [ 10 20 ];
            }
            native-vlan-id 5;
        }
    }
}
```

##### ACTUAL RESULTS

Configuration related to aggregated-ether-options is removed by task junos_l2_interface execution
After junos_linkagg and before  junos_l2_interface  execution, result is:

```
ae0 {
    description test;
    aggregated-ether-options {
        lacp {
            active;
        }
    }
}
```

After  junos_l2_interface  execution, result is:

```
ae0 {
    description test;
    unit 0 {
        family ethernet-switching {
            port-mode trunk;
            vlan {
                members [ 10 20 ];
            }
            native-vlan-id 5;
        }
    }
}
```
