### ISSUE TITLE
gcp_sql_instance_facts: can not use output from "items"

### ISSUE THREAD

**Issue by rrey** [ansible/ansible#55824]
##### SUMMARY

The `gcp_sql_instance_facts` module output uses the `items` keyword which is reserved in python dict. 
When ones wants to parse the module output to navigate in the `items`, the return value is a python object representation. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_sql_instance_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.0rc1
  config file = /home/remirey/dev/fnac/gcp-tools/ansible/ansible.cfg
  configured module search path = ['/home/remirey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/remirey/.virtualenvs/fnactools/lib/python3.6/site-packages/ansible
  executable location = /home/remirey/.virtualenvs/fnactools/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = -F ssh_config
DEFAULT_REMOTE_USER(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = ['/home/remirey/dev/gcp-tools/ansible/roles-external', '/home/remirey/dev/gcp-tools/ansible/roles']
HOST_KEY_CHECKING(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
tasks:
   - name: "Get SQL instances facts"
      delegate_to: localhost
      become: false
      gcp_sql_instance_facts:
        project: "{{ your_project_id }}"
        auth_kind: serviceaccount
      register: sql_instances

    - debug:
        msg: "{{ sql_instances.items }}"
```

##### EXPECTED RESULTS

The `sql_instances.items` value should be a list of instances according to the doc.

##### ACTUAL RESULTS

```paste below
TASK [Get SQL instances facts] *****************************************************************************************************************************************************************************
ok: [tools-gitlab-dev]

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [tools-gitlab-dev] => {
    "msg": "<built-in method items of dict object at 0x7f86e0734a20>"
}
```
