### ISSUE TITLE
azure_rm_webapp.py: getting error while trying to create Web App

### ISSUE THREAD

**Issue by localdotcom** [ansible/ansible#55836]
##### SUMMARY

In my environment I use dockerized Anzible with Azure module. When I'm trying to create new Web App I'm getting error "app_service_plan_name is not a known attribute of class <class 'azure.mgmt.web.models.app_service_plan_py3.AppServicePlan'>".
As far as I know **app_service_plan_name** removed from azure-mgmt-web 0.41.0, but **plan** still mandatory in **azure_rm_webapp**.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_webapp.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.0b1
ansible python module location = /usr/lib/python3.6/site-packages
executable location = /usr/bin/ansible
python version = 3.6.8
```

##### OS / ENVIRONMENT

Debian 9.8 / Docker

##### STEPS TO REPRODUCE

- Create Resource Group
- Create Web App within a Resource Group in Azure subscription

```yaml
---
- name: Create a resource group
  azure_rm_resourcegroup:
    ad_user: '{{ user_test }}'
    password: '{{ pass }}'
    subscription_id: '{{ sub_test_id }}'
    name: rg-testing
    location: westeurope

- name: Create a docker web app with some app settings, with docker image
   azure_rm_webapp:
     ad_user: '{{ user_test }}'
     password: '{{ pass }}'
     subscription_id: '{{ sub_test_id }}'
     resource_group: rg-testing
     location: "westeurope"
     name: webapp-testing
     plan:
       subscription_id: '{{ sub_test_id }}'
       resource_group: rg-testing
       name: "asp-testing"
       location: "westeurope"
       sku: S1
     container_settings:
       name: webapp1
        
```

##### ACTUAL RESULTS

Returns exception

```paste below
PLAY [Deploy Azure resources] **************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [rg-create : Create a resource group] *************************************
ok: [127.0.0.1]

TASK [rg-create : Create a docker web app with some app settings, with docker image] ***
fatal: [127.0.0.1]: FAILED! =>
 {"changed": false, "module_stderr": "app_service_plan_name is not a known attribute of class
 <class 'azure.mgmt.web.models.app_service_plan_py3.AppServicePlan'> and will be ignored\n
Traceback (most recent call last):\n  
File \"/root/.ansible/tmp/ansible-tmp-1556311750.032416-94201624674514/AnsiballZ_azure_rm_webapp.py\", line 114, in <module>\n
_ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1556311750.032416-94201624674514/AnsiballZ_azure_rm_webapp.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n
File \"/root/.ansible/tmp/ansible-tmp-1556311750.032416-94201624674514/AnsiballZ_azure_rm_webapp.py\", line 49, in invoke_module\n
imp.load_module('__main__', mod, module, MOD_DESC)\n
File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n
return load_source(name, filename, file)\n
File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n
module = _exec(spec, sys.modules[name])\n
File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n
File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n
File \"/tmp/ansible_azure_rm_webapp_payload_kkgz6316/__main__.py\", line 1063, in <module>\n
File \"/tmp/ansible_azure_rm_webapp_payload_kkgz6316/__main__.py\", line 1059, in main\n
File \"/tmp/ansible_azure_rm_webapp_payload_kkgz6316/__main__.py\", line 541, in __init__\n
File\"/tmp/ansible_azure_rm_webapp_payload_kkgz6316/ansible_azure_rm_webapp_payload.zip/ansible/module_utils/azure_rm_common.py\", line 325, in __init__\n
File \"/tmp/ansible_azure_rm_webapp_payload_kkgz6316/__main__.py\", line 755, in exec_module\n
File \"/tmp/ansible_azure_rm_webapp_payload_kkgz6316/__main__.py\", line 844, in create_update_webapp\n
File \"/usr/lib/python3.6/site-packages/azure/mgmt/web/operations/web_apps_operations.py\", line 332, in create_or_update\n **operation_config\n
File \"/usr/lib/python3.6/site-packages/azure/mgmt/web/operations/web_apps_operations.py\", line 280,
 in _create_or_update_initial\n
raise models.DefaultErrorResponseException(self._deserialize, response)\nazure.mgmt.web.models.default_error_response_py3.DefaultErrorResponseException: Operation returned an invalid status code 'Conflict'\n",
"module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
exit status 2
```
