### ISSUE TITLE
import_tasks do not allow passing different variables in the same playbook

### ISSUE THREAD

**Issue by weshouman** [ansible/ansible#55842]
##### SUMMARY
Based on the docs we were allowed to call other playbooks with different variables with the following syntax.
```
tasks:
- import_tasks: wordpress.yml wp_user=timmy
- import_tasks: wordpress.yml wp_user=alice
...
```
Now using the new syntax will **Only get the wordpress.yml to be executed with wp_user=alice, but not with wp_user=timmy too** due to the way variables are handled in Ansible
```
tasks:
- import_tasks: wordpress.yml
  vars:
    wp_user=timmy
- import_tasks: wordpress.yml
  vars:
    wp_user=alice
```

Docs link [https://docs.ansible.com/ansible/2.4/playbooks_reuse_includes.html#including-and-importing-task-files](https://docs.ansible.com/ansible/2.4/playbooks_reuse_includes.html#including-and-importing-task-files).  
  
Note: In the issue [32812](https://github.com/ansible/ansible/issues/32812) such change is explained, but the side-effect of executing only the last defined variable isn't discussed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

import_tasks

##### ANSIBLE VERSION
```paste below
2.7.9
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
tasks:
- import_tasks: wordpress.yml
  vars:
    wp_user=timmy
- import_tasks: wordpress.yml
  vars:
    wp_user=alice
```

##### EXPECTED RESULTS

All the tasks get executed.

##### ACTUAL RESULTS

```paste below
Found a duplicate dictkey (tasks). Using last defined value only.
```
