### ISSUE TITLE
gcp_compute_disk can't use RHEL source_image

### ISSUE THREAD

**Issue by apitanga** [ansible/ansible#55843]
##### SUMMARY
Unable to create GCP disk using a RHEL image as source

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_disk
##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Mar 21 2019, 10:09:12) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```

##### STEPS TO REPRODUCE

```yaml
gcp_cloud_disk: "cloud-disk"
gcp_project: "web-development-238814"
gcp_cred_file: "/home/ansible/cloud-init/vars/ansible-238814-f2a2d39a312f.json"
gcp_cred_kind: "serviceaccount"
gcp_disk_size: "25"
gcp_project: "ansible-238814"
gcp_disk_zone: "us-east4-a"
gcp_source_image: "projects/rhel-cloud/global/licenses/rhel-7-server"
gcp_disk_state: "present"
```

##### EXPECTED RESULTS

A disk gets created based off rhel image (projects/rhel-cloud/global/licenses/rhel-7-server)

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "GCP returned error: {u'error': {u'code': 400, u'message': u\"Invalid value for field 'resource.sourceImage': 'projects/rhel-cloud/global/licenses/rhel-7-server'. Unexpected resource collection 'licenses'.\", u'errors': [{u'domain': u'global', u'message': u\"Invalid value for field 'resource.sourceImage': 'projects/rhel-cloud/global/licenses/rhel-7-server'. Unexpected resource collection 'licenses'.\", u'reason': u'invalid'}]}}"}
```
