### ISSUE TITLE
GCP attach shared VPC to project

### ISSUE THREAD

**Issue by apitanga** [ansible/ansible#55849]
##### SUMMARY

Create module or add feature to existing module that enables one to attach a project to a shared VPC

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`lib/ansible/modules/cloud/google/`
##### ADDITIONAL INFORMATION

Org X would like to use Ansible to automate creation and management of GCP projects.  a common related task is to attach a project to an existing Shared VPC.

```yaml
     gcp_attach_sharedvpc:
      name: "us-east4-dev"
      project: "development-network-238800"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
```
