### ISSUE TITLE
how to write pretty yaml for "free_form module" like "shell"

### ISSUE THREAD

**Issue by layerssss** [ansible/ansible#5585]
If I need to write:

```
- name: 'install nodejs {{ nodejs_version }} binary'
  sudo: yes
  sudo_user: '{{ app_name }}'
  shell: 'tar -xzf /public/node-{{ nodejs_version }}-linux-x64.tar.gz --strip 1 -C /home/{{ app_name }}/app.d/nodejs-{{ nodejs_version }}'
```

it's fine and working. But if I want to utilize `creates` parameter to achieve idempotency, I have to write.

```
- name: 'install nodejs {{ nodejs_version }} binary'
  sudo: yes
  sudo_user: '{{ app_name }}'
  shell: 'creates=/home/{{ app_name }}/app.d/nodejs-{{ nodejs_version }} tar -xzf /public/node-{{ nodejs_version }}-linux-x64.tar.gz --strip 1 -C /home/{{ app_name }}/app.d/nodejs-{{ nodejs_version }}'
```

But this ugly, long one-liner looks really nasty if you have to write it multiple times.(even more so if you have to add more parameters, like chdir..) It's hard to read either. Can I just write it like this?

```
# this actually doesn't work
- name: 'install nodejs {{ nodejs_version }} binary'
  sudo: yes
  sudo_user: '{{ app_name }}'
  shell: 
    creates: '/home/{{ app_name }}/app.d/nodejs-{{ nodejs_version }}'
    command: 'tar -xzf /public/node-{{ nodejs_version }}-linux-x64.tar.gz --strip 1 -C /home/{{ app_name }}/app.d/nodejs-{{ nodejs_version }}'
```
