### ISSUE TITLE
Unable to create security group rule using os_security_group_rule module

### ISSUE THREAD

**Issue by srimandarbha** [ansible/ansible#55876]
##### SUMMARY
Unable to create security group rule with error " Invalid CIDR NXDOMAIN/32 given as IP prefix." when trying to add a ip address as remote_ip

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
We are trying to add security group rule using the os_security_group_rule and dns plugin. When we are trying to add the rule for a ip address say devdb.fqdn internally resolv to 10.0.2.21 with /32 as suffix. we are seeing the error " Invalid CIDR NXDOMAIN/32 given as IP prefix."
!component -lib

##### ANSIBLE VERSION
```paste below
]# ansible --version
ansible 2.3.3.0
```

##### CONFIGURATION

```paste below
]# ansible-config dump --only-changed
DEFAULT_GATHERING(/root/buy_auto/buy_ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/root/buy_auto/buy_ansible/ansible.cfg) = [u'/root/buy_auto/buy_ansible/inventory']
DEFAULT_REMOTE_TMP(/root/buy_auto/buy_ansible/ansible.cfg) = /tmp
DEFAULT_REMOTE_USER(/root/buy_auto/buy_ansible/ansible.cfg) = serioussam
DEFAULT_ROLES_PATH(/root/buy_auto/buy_ansible/ansible.cfg) = [u'/root/buy_auto/buy_ansible/roles']
DEFAULT_TIMEOUT(/root/buy_auto/buy_ansible/ansible.cfg) = 40
DEPRECATION_WARNINGS(/root/buy_auto/buy_ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/root/buy_auto/buy_ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

OS: Centos 7.3
Python version: 2.7.5
shade version: 1.21.0

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
   vars:
    ensure_ans: present
    sg_names:
          - sgname: SG-Dev-testing
            cloud_name: 'ENV_DEV'
            sg_rule:
              - proto: 'tcp'
                portmin: '80'
                portmax: '80'
                remoteip: 'devapp.fqdn'
              - proto: 'tcp'
                portmin: '8080'
                portmax: '8080'
                remoteip: 'devdb.fqdn'
   tasks:
    - name: "Managing security group rules on {{item.0.sgname}}"
      os_security_group_rule:
        cloud: "{{item.0.cloud_name}}"
        security_group: "{{item.0.sgname}}"
        protocol: "{{item.proto|default('tcp')}}"
        direction: "{{item.direction|default('ingress')}}"
        port_range_min: "{{item.1.portmin|default(item.1.port)}}"
        port_range_max: "{{item.1.portmax|default(item.1.port)}}"
        remote_ip_prefix: "{{lookup('dig', 'item.1.remoteip')}}/32"
      with_subelements:
        - "{{sg_names}}"
        - sg_rule
        - skip_missing: yes
```

##### EXPECTED RESULTS

Expected: create a security group rule with ip address with CIDR

##### ACTUAL RESULTS

```paste below
"msg": "Error creating security group rule. (400) Client Error for url: https://neutronapi.fqdn:9696/v2.0/security-group-rules.json Invalid CIDR NXDOMAIN/32 given as IP prefix."
```
