### ISSUE TITLE
docker_container module: etc_hosts parameter does not interpolate variable in "host" position

### ISSUE THREAD

**Issue by earthquakesan** [ansible/ansible#55877]
##### SUMMARY
Given this playbook:
```
---
- hosts: all
  vars:
    - etc_hosts_host: "example.com"
    - etc_hosts_ip: "10.10.10.10"
  tasks: 
- name: run nginx docker container with etc_hosts
  docker_container:
    name: "nginx"
    image: nginx:latest
    etc_hosts:
      "{{ etc_hosts_host }}": "{{ etc_hosts_ip }}"
```

in docker container /etc/hosts {{ etc_hosts_host }} variable is not interpolated:
```
~ % docker exec -it nginx cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.10.10.10	{{ etc_hosts_host }}
172.17.0.3	0601d116d089
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0 config file = None configured module search path =
[u'/Users/ivanermilov/.ansible/plugins/modules',
u'/usr/share/ansible/plugins/modules'] ansible python module location =
/usr/local/lib/python2.7/site-packages/ansible executable location =
/usr/local/bin/ansible python version = 2.7.15 (default, Aug 22 2018,
16:36:18) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
```paste below
(empty)
```

##### OS / ENVIRONMENT
MacOS 10.14.4 with python2.7 and ansible installed via pip.
```
pip install git+https://github.com/ansible/ansible@devel
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  vars:
    - etc_hosts_host: "example.com"
    - etc_hosts_ip: "10.10.10.10"
  tasks: 
- name: run nginx docker container with etc_hosts
  docker_container:
    name: "nginx"
    image: nginx:latest
    etc_hosts:
      "{{ etc_hosts_host }}": "{{ etc_hosts_ip }}"
```

To run:
```
ansible-playbook -i hosts -b -K etc-hosts-test.yml
```

hosts file:
```
$ cat hosts
workstation.local
```

##### EXPECTED RESULTS

```
~ % docker exec -it nginx cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.10.10.10	example.com
172.17.0.3	0601d116d089
```

##### ACTUAL RESULTS

```
~ % docker exec -it nginx cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
10.10.10.10	{{ etc_hosts_host }}
172.17.0.3	0601d116d089
```
