### ISSUE TITLE
Extend file module absent state diff to show files removed

### ISSUE THREAD

**Issue by Taoquitok** [ansible/ansible#55882]
##### SUMMARY
Currently when using `file: "path=someFolderPath state=absent"`, if a folder is defined for removing, the diff result only shows the state change, not the files removed. I believe a small tweak to `initial_diff` would make sense in the case of using `state=absent` to make it more clear what's to be removed

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[Modules/Files/File.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py)

##### ADDITIONAL INFORMATION
This would be an extension of the existing --diff functionality found within [file](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py) module to allow for a clearer display of the difference when using `file:` to remove a folder

After some additional testing, I've edited my original suggestion to the below for adding to `initial_diff` after line [354](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py#L354) inside the `if prev_state != state:`  
From testing this is still a bit of work in progress as bizarrely symlinks are not being listed, only normal files. If I figure this out I'll update my example

###### Example change to file.py
```python
# Line 354 in devel
def initial_diff(path, state, prev_state):
    diff = {'before': {'path': path},
            'after': {'path': path},
            }

    if prev_state != state:
        diff['before']['state'] = prev_state
        diff['after']['state'] = state
        if state == 'absent':
            walklist = {
                'directories': [],
                'files': [],
            }
            for base_path, sub_folders, files in os.walk(path):
                for folder in sub_folders:
                    folderpath = os.path.join(base_path, folder)
                    walklist['directories'].append(folderpath)

                for filename in files:
                    filepath = os.path.join(base_path, filename)
                    walklist['files'].append(filepath)

            diff['before']['path_content'] = walklist

    return diff

```

###### Example playbook
```yaml
- name: Create example folder
  file:
    path: /tmp/example_folder
    state: directory

- name: Create example file
  file:
    path: /tmp/example_folder/example_file.tmp
    state: touch

- name: remove example folder and file
  file:
    path: /tmp/example_folder
    state: absent
```

I've looked through other pull requests/issues/features related to the file module and I don't believe anyone else is suggesting this specific change, or have previously suggested, so hopefully this will be a useful addition.  
I would be happy to put in a pull request for my example change if there's no objections, and develop it as necessary from there
