### ISSUE TITLE
rabbitmq_publish : content_type application/json fails

### ISSUE THREAD

**Issue by frsauvage** [ansible/ansible#55908]
##### SUMMARY
Cannot use JSON content with rabbitmq_publish module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module rabbitmq_publish

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0 config file = /var/lib/awx/ansible.cfg configured module
search path = [u'/usr/lib/python2.7/site-packages/ansible/modules'] ansible
python module location = /usr/lib/python2.7/site-packages/ansible executable
location = /usr/bin/ansible python version = 2.7.5 (default, Oct 30 2018,
23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/var/lib/awx/projects/inventory']
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/usr/lib/python2.7/site-packages/ansible/modules']
HOST_KEY_CHECKING(/var/lib/awx/ansible.cfg) = False
RETRY_FILES_ENABLED(/var/lib/awx/ansible.cfg) = False

```

##### STEPS TO REPRODUCE
In a playbook just put content_type: "application/json" 
```yaml
  - name: Publish result to rabbitmq
    rabbitmq_publish:
      host: rabbitmq
      proto: amqp
      exclusive: false
      port: 5672
      vhost: xxx
      durable: true
      username: xxx
      password: xxxxxxpass
      body: "{{item.value}}"
      queue: sensors
      content_type: "application/json"
    with_dict: "{{ all_fans }}"

```
##### EXPECTED RESULTS
I expect a well-formed  json message in rabbitmq

##### ACTUAL RESULTS
The rabbitmq message is not in json format
