### ISSUE TITLE
rabbitmq_publish : Unsuccessful publishing to queue response BUT message well published ?

### ISSUE THREAD

**Issue by frsauvage** [ansible/ansible#55919]
##### SUMMARY
"Unsuccessful publish" response in rabbitmq_publish modul  BUTmessage is well published (!)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/notification/rabbitmq_publish.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0 config file = /var/lib/awx/ansible.cfg configured module
search path = [u'/usr/lib/python2.7/site-packages/ansible/modules'] ansible
python module location = /usr/lib/python2.7/site-packages/ansible executable
location = /usr/bin/ansible python version = 2.7.5 (default, Oct 30 2018,
23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/var/lib/awx/projects/inventory']
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/usr/lib/python2.7/site-packages/ansible/modules']
HOST_KEY_CHECKING(/var/lib/awx/ansible.cfg) = False
RETRY_FILES_ENABLED(/var/lib/awx/ansible.cfg) = False
```

##### OS / ENVIRONMENT

rabbitmq is inside a docker container with last version of awx

##### STEPS TO REPRODUCE

I copy:paste the example from  https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/rabbitmq_publish.py 
```
- name: RabbitMQ auto generated queue
  rabbitmq_publish:
    url: "amqp://guest:guest@192.168.0.32:5672/%2F"
    body: "Hello world random queue from ansible module rabbitmq_publish"
    content_type: "text/plain"
```
I changed the ip address => not working
I added a queue because it is said that the queue_declare() needs a parameter => not working
I added the durable parameter as it is said => not working

I tried different options, with host/port/proto/vhost, and with url

```yaml
  tasks:
  - name: RabbitMQ auto generated queue
    rabbitmq_publish:
      url: "amqp://admin:password@rabbitmq:5672/awx"
      queue: basicmq
      durable: true
      body: "Hello world random queue from ansible module rabbitmq_publish"
      content_type: "text/plain"
```

##### EXPECTED RESULTS
I expect to have a successful response (basic_publish returns None ??)

##### ACTUAL RESULTS

always : "Unsuccessful publishing to queue"
