### ISSUE TITLE
ec2 module: Allow "auto" setting for ebs_optimized

### ISSUE THREAD

**Issue by nilsmeyer** [ansible/ansible#55912]
##### SUMMARY
Currently, the ec2 module defaults the "ebs_optimized" parameter to "false", which works with all instance types. There could be an option "auto" that will set ebs_optimized to "true" for instance types that support this.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* ec2 module 
* ec2_instance module

##### ADDITIONAL INFORMATION
A setting of "auto" for the ebs_optimized parameter that enables the EBS optimized setting for those instance types that support it and disables it for those that don't would make it easier to write generic playbooks that support multiple instance types. Currently, I'm using the following code to achieve the same:

```yaml
- name: Create molecule instance(s)
  ec2:
  [..]
  ebs_optimized: >-
    {%- if 'ebs_optimized' in item -%}
    item.ebs_optimized
    {%- elif item.instance_type[:2] in ['a1', 'c4', 'c5', 'd2', 'f1', 'g3',
          'h1', 'i3', 'm4', 'm5', 'p2', 'p3', 'r4', 'r5', 't3', 'u-', 'x1',
          'z1'] -%}
    true
    {%- else -%}
    false
    {%- endif -%}
```

While I would like to be able to do this:
```yaml
# EBS Optimized would be false
- name: Create instance 
  ec2: 
    instance_type: t2.micro 
    ebs_optimized: auto
    [..]

- name: Create EBS Optimized instance
  ec2:
    instance_type: t3.micro
    ebs_optimized: auto
    [..]
```
