### ISSUE TITLE
Module: [yum/package] 'state:absent' does not remove packages v2.7.10

### ISSUE THREAD

**Issue by MortallyRoasted** [ansible/ansible#55938]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Modules: [yum, package]

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/code/freeipa/.venv/lib/python3.7/site-packages/ansible
  executable location = /Users/user/code/freeipa/.venv/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora Server 29 (Base Install) (Running in VirtualBox)

##### STEPS TO REPRODUCE

```bash

# install the packages first...
ansible-playbook -i [MY-INVENTORY] --tags install site.yml

# try to uninstall them/rollback
ansible-playbook -i [MY-INVENTORY] --tags uninstall site.yml
```

```yaml
# site.yml
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - roles:
      name: freeipa
```

```yaml
# roles/freeipa/tasks/main.yml
- name: Install Packages
  package:
    name: freeipa-*
    state: present
  tags:
    - install
    - install:packages

- name: Uninstall Packages
  package:
    name: freeipa-*
    state: absent
  tags:
    - never
    - uninstall
    - uninstall:packages
```

This also does not work if I explicitly list the packages to remove with the `with_items` key.

```
- name: Uninstall Packages
  package:
    state: absent
  with_items:
    - freeipa-client
    - ...
    - ...
  tags:
    - never
    - uninstall
    - uninstall:packages
``` 

##### EXPECTED RESULTS

All freeipa related packages should be gone. Command below should return 0

```bash
$ yum list installed | grep freeipa | wc -l
0
```

##### ACTUAL RESULTS

```
$ yum list installed | grep freeipa | wc -l
11
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/yum.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @kustodian @maxamillion @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
If you run the command `dnf uninstall 'freeipa-*'` does it remove the packages? There were some issues with `dnf` on Fedora 29 and that may be the real issue.

needs_info

**Comment by MortallyRoasted** [comment]
> If you run the command `dnf uninstall 'freeipa-*'` does it remove the packages? There were some issues with `dnf` on Fedora 29 and that may be the real issue.
> 
> needs_info

@samdoran 

# Does Not Work

```yaml

- name: Uninstall Packages
  dnf:
    name: freeipa-*
    state: absent
  tags:
    - never
    - uninstall
    - uninstall:packages
```

# Works

```yaml
# example 1
- name: Uninstall Packages
  raw: "dnf remove -qy freeipa-*"
  tags:
    - never
    - uninstall
    - uninstall:packages

# example 2
- name: Uninstall Packages
  raw: "yum remove -qy freeipa-*"
  tags:
    - never
    - uninstall
    - uninstall:packages
```

The workaround is simple, so this is not a huge deal. However, it does defeat the purpose of using the generic `package` module in the first place.
