### ISSUE TITLE
os_server ignores `auth.project_name` when OS_* environment variables exists

### ISSUE THREAD

**Issue by fhemberger** [ansible/ansible#55932]
##### SUMMARY
Unlike other OpenStack modules, it's not possible to directly specify a project name where new server instances should be created. Setting `auth.project_name` is ignored when `OS_PROJECT_ID` and `OS_PROJECT_NAME` environment variables are set.

Use case: I'm logging into OpenStack as part of the "admin" project to create a new project and additional configuration. Afterwards, I want to spawn new compute instance inside the freshly generated project.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`os_server`

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /Users/frederic/Kunden/Oerlikon/04_development/infrastructure/openstack-kubernetes-setup/ansible.cfg
  configured module search path = ['/Users/frederic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.10/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = ['/Users/frederic/.ansible/hosts']
```

##### STEPS TO REPRODUCE

`source admin-openrc.sh` with a user belonging to the "admin" project, then run the following playbook:

```yaml
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        project_name: my-new-project

    - name: "Create OpenStack project '{{ project_name }}'"
      os_project:
        name: "{{ project_name }}"
        endpoint_type: admin
        domain_id: default
        state: present
        enabled: True
      register: new_project

    - name: "Create server instances"
      os_server:
        auth:
          project_name: "{{ project_name }}"
        name: "my-new-instance"
        image: …
        key_name: …
        flavor: …
        auto_ip: yes
```

##### EXPECTED RESULTS

Instance should be created in project "my-new-project".

##### ACTUAL RESULTS

Instance is created in project "admin".

So far, the only workaround I found was overwriting the environment variables in the task:

```yaml
- name: "Create server instances"
  environment:
    OS_PROJECT_ID: "{{ new_project.project.id }}"
    OS_PROJECT_NAME: "{{ new_project.project.name }}"
  os_server:
    name: "my-new-instance"
    image: …
    key_name: …
    flavor: …
    auto_ip: yes
```

But I don't think that's the best way it's supposed to work.
