### ISSUE TITLE
Roles default vars get overridden

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#55942]
##### SUMMARY
Let's assume we have a role with a default defined `mydefault: 'initial default`
If there is somewhere an `import_role` which overrides that default, the default is being overridden for all roles

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
import_role

##### ANSIBLE VERSION

```
2.7.10
```

##### OS / ENVIRONMENT
irrelevant

##### STEPS TO REPRODUCE

```yaml
# main.yml
- hosts: localhost
  tasks:
    - name: import role first time
      import_role:
        private: True
        name: role1

    - name: import role second time
      import_role:
        name: role1
        private: True
      vars:
        mydefault: "other"

# roles/role1/tasks/main.yml
---
- debug:
    msg: |
      mydefault: {{ mydefault }}

# roles/role1/defaults/main.yml
mydefault: "initial_default"

```

##### EXPECTED RESULTS
```
TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "msg": "mydefault: initial_default\n"
}

TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "msg": "mydefault: other\n"
}
```

##### ACTUAL RESULTS
```
TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "msg": "mydefault: other\n"
}

TASK [role1 : debug] ***********************************************************
ok: [localhost] => {
    "msg": "mydefault: other\n"
}
```
