### ISSUE TITLE
ec2 module needs to account for instance states

### ISSUE THREAD

**Issue by acdha** [ansible/ansible#55955]
##### SUMMARY

Currently the ec2 module will count instances which are shutting down towards the `exact_count` total

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /Users/cadams/Projects/chronam-deployment/ansible.cfg
  configured module search path = ['/Users/cadams/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.10/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]

```

##### CONFIGURATION
```
[defaults]
# No Ansible droppings if a playbook fails
retry_files_enabled = False

[ssh_connection]
# Enabling pipelining reduces the number of SSH operations required to
# execute a module on the remote server. This can result in a significant
# performance improvement when enabled, however when using "sudo:" you must
# first disable 'requiretty' in /etc/sudoers
#
# By default, this option is disabled to preserve compatibility with
# sudoers configurations that have requiretty (the default on many distros).
#
pipelining = True

# Don't allow SCP:
scp_if_ssh = False

[inventory]
enable_plugins = aws_ec2
```

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE
```yaml
ec2:
            exact_count: 1
            count_tag:
                Role: "solr"
                Environment: "{{ env }}"
            instance_tags:
                Role: "solr"
                Environment: "{{ env }}"
```

##### EXPECTED RESULTS

The exact count number of servers would be running, starting new servers if necessary

##### ACTUAL RESULTS

The server in the process of shutting down will be counted and thus not replaced.

I had hoped that this could be solved simply by adding `state: running` but the code actively prevents that with an argument which does not make sense since the parameters are in reality compatible:

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "parameters are mutually exclusive: exact_count, state"}
```
