### ISSUE TITLE
'module' object has no attribute 'ANSIBLE_CONNECTION_PATH'

### ISSUE THREAD

**Issue by wojtek0806** [ansible/ansible#55956]
##### SUMMARY

This issue is related to: https://github.com/F5Networks/f5-ansible/issues/1302

Running bigip_command module with CLI transport and SSH key authentication, raises the exception. the components listed are the ones involved in this issue. For now it seems like the problem lies with constants.py

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/action/bigip.py
constants.py
plugins/connection/persistent.py

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.0.4
Python 2.7.15rc1

##### STEPS TO REPRODUCE

```yaml

- name:                               Test playbook
  hosts:                                bigip.local
  connection:                           local
  gather_facts:                         no
  environment:
    ANSIBLE_NET_SSH_KEYFILE:            "~/.ssh/id_rsa.pub"

  tasks:

# Ansible F5 bigip_command module; runs on remote host with SSH & SSHkeys

  - name:                               Test Ansible F5 bigip_command module
    bigip_command:
      provider:
        transport:                      cli
        user:                           admin
        server:                       bigip.local
        ssh_keyfile:                    "~/.ssh/id_rsa.pub"
        validate_certs:                 no
      commands:                         tmsh modify auth user admin password admin shell bash

```

##### EXPECTED RESULTS

The connection to the device has been established.

##### ACTUAL RESULTS

Getting attribute error

```paste below
ansible-playbook 2.7.10
  config file = /home/sxw455/.ansible.cfg
  configured module search path = [u'/home/sxw455/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sxw455/.local/lib/python2.7/site-packages/ansible
  executable location = /home/sxw455/.local/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Using /home/sxw455/.ansible.cfg as config file
setting up inventory plugins
/home/sxw455/Ansible-F5/Inventory/Inventory.yaml did not meet host_list requirements, check plugin documentation if this is unexpected
/home/sxw455/Ansible-F5/Inventory/Inventory.yaml did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/sxw455/Ansible-F5/Inventory/Inventory.yaml inventory source with yaml plugin
Loading callback plugin yaml of type stdout, v2.0 from /home/sxw455/.local/lib/python2.7/site-packages/ansible/plugins/callback/yaml.pyc

PLAYBOOK: bigip_command.yaml **************************************************************************************************************************
1 plays in bigip_command.yaml

PLAY [Test playbook] **********************************************************************************************************************************
META: ran handlers

TASK [Test Ansible F5 bigip_command module] ***********************************************************************************************************
task path: /home/sxw455/Ansible-F5/Playbooks/bigip_command.yaml:18
The full traceback is:
Traceback (most recent call last):
  File "/home/sxw455/.local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/home/sxw455/.local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/sxw455/.ansible/roles/f5devcentral.f5ansible/action_plugins/bigip.py", line 83, in run
    socket_path = connection.run()
  File "/home/sxw455/.local/lib/python2.7/site-packages/ansible/plugins/connection/persistent.py", line 82, in run
    socket_path = self._start_connection()
  File "/home/sxw455/.local/lib/python2.7/site-packages/ansible/plugins/connection/persistent.py", line 91, in _start_connection
    candidate_paths = [C.ANSIBLE_CONNECTION_PATH or os.path.dirname(sys.argv[0])]
AttributeError: 'module' object has no attribute 'ANSIBLE_CONNECTION_PATH'
fatal: [awsf5proda.sherwin.com]: FAILED! => 
  msg: Unexpected failure during module execution.
  stdout: ''

PLAY RECAP ********************************************************************************************************************************************
awsf5proda.sherwin.com     : ok=0    changed=0    unreachable=0    failed=1 

```
