### ISSUE TITLE
Clarify win_dns_client support for IPv6

### ISSUE THREAD

**Issue by scottambroseio** [ansible/ansible#55962]
##### SUMMARY

Hey all o/

I recently started using ansible for configuring my windows desktop (Win10 Professional). One of the tasks I wanted to automate was changing the dns servers it uses. Upon looking at win_dns_client, I noticed it claims to only support ipv4 addresses via the ipv4_addresses property.

In order to set both the ipv4 and ipv6 addresses on my network adapter, I investigated doing this instead as a custom script. In doing so, I noticed that powershell actually uses the same method for both ipv4 and ipv6. With this and looking at the source for win_dns_client, I realised I could enter an ipv6 address in the ipv4_addresses field and get desired result.

With the following task, I successfully set both the ipv4 and ipv6 addresses for the specified adapter.

```yaml
- name: Ensure pihole as dns resolver
  win_dns_client:
    adapter_names: Ethernet
    ipv4_addresses:
   - "192.168.1.63"
   - "fd19:bf3e:7cd4:1:b85c:e8cf:94f3:de76"
```
Here's the output from before / after confirming the change

![dns](https://user-images.githubusercontent.com/7337433/56989334-1b593200-6b8a-11e9-8bba-44bb8f848e15.png)

I'm uncertain if this behaviour is limited to Win10 Pro or whether it also exists on other windows versions (server installs, I don't have access to any to check). If this behaviour is consistent, it might be an option to rename the property to reflect this behaviour. Regardless, this behaviour is probably worth documenting?

Thanks!

##### COMPONENT NAME

win_dns_client

##### ANSIBLE VERSION

2.7.10
