### ISSUE TITLE
file state=hard fails with relative path, docs say it should pass

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#55971]
##### SUMMARY

The docs say that the file module accepts a relative path for `src`. But if you try that with `state=hard` it fails.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

file module

##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/opentelco/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/opentelco/patches/ansible/lib/ansible
  executable location = /home/opentelco/patches/ansible/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION
`ansible-config dump --only-changed`: empty

##### OS / ENVIRONMENT

Ubuntu 18

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
     - name: create hard link
       file:
          dest: hard.txt
          src: file.txt
          state: hard
```

##### EXPECTED RESULTS

File `hard.txt` should be a hard link to `file.txt`.

##### ACTUAL RESULTS

```
TASK [create hard link] ***************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "src must be an absolute path"}

```
