### ISSUE TITLE
ipa_hbacrule cannot change between categories and specific host/users/service/sourcehosts

### ISSUE THREAD

**Issue by RobVerduijn** [ansible/ansible#55984]
##### SUMMARY
Example for usercategorie and users or usergroups.
If you want to change a hbacrule from usercategory=all to user or usergroup it fails.

This is because the usercategory and the user or usergroup are mutually exclusive.
If you want to set a user or usergroup you first need to set the usercategory to None.
Or if you wish to set the usercategory the user and the usergroups must be "None"

The same goes for:
service/servicegroups and servicecategory.
host/hostgroup and hostcategory
sourcehost/sourcehostgroup and sourcehostcategory

To reproduce this simply create a hbacrule with the usercategory set to all
```
  - name: add  access rule
    ipa_hbacrule:
      ipa_host: "{{ inventory_hostname }}"
      ipa_pass: '{{ ipaadmin_password }}'
      ipa_user: admin
      ipa_timeout: 120
      name: allow_admin_all
      description: Allow access
      usercategory: all
      state: present
```
Then try to change it to user
```
  - name: add  access rule for admin user
    ipa_hbacrule:
      ipa_host: "{{ inventory_hostname }}"
      ipa_pass: '{{ ipaadmin_password }}'
      ipa_user: admin
      ipa_timeout: 120
      name: allow_admin_all
      user: admin
      description: Allow admin access
      state: present
```
This will fail with :
"user cannot be added when user category='all'"

With the current version you need to remove the hbac rule first before you can set the user or usergroup.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ipa_hbacrule

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

you can use ipa_hbacrule to change between categories to user(groups)/service(groups)/host(groups)/servicehost(groups)

##### ACTUAL RESULTS

the ansible role failes with : user/host/service cannot be added when user category='all'

```paste below

```
