### ISSUE TITLE
Pip not idempotent when ran against multiple hosts w/ one ip

### ISSUE THREAD

**Issue by corbinstuard** [ansible/ansible#55991]
##### SUMMARY

Pio module is not idempotent when ran against multiple hosts in group with same ip address

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Pip

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=2000s -o UserKnownHostsFile=/dev/nu
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = /tmp
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 3
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/modules']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/etc/ansible/ansible.cfg) = [u'.pyc', u'.pyo', u'.swp', u'.bak', u'~', u'.rpm', u'.md', u'.txt', u
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Linux 3.10.0-693.21.1.el7.x86_64
CentOS 7.5

##### STEPS TO REPRODUCE

```yaml
- name: install docker-compose
  pip:
    name: docker-compose
```

inventory:
```yaml
docker-df:
  hosts:
    df1-1-docker-test:
      ansible_host: 192.168.2.50
    df1-docker-test:
      ansible_host: 192.168.2.50
```

##### EXPECTED RESULTS

One host should pass as Ok and one as Changed

##### ACTUAL RESULTS

One host always fails. Error is specific to the package being installed.

```paste below
fatal: [df1-docker-test]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "docker-compose"], "msg": "stdout: Collecting docker-compose\n  Downloading https://files.pythonhosted.org/packages/51/56/5745e66b33846e92a8814466c163f165a26fadad8b33afe381e8b6c3f652/docker_compose-1.24.0-py2.py3-none-any.whl (134kB)\nCollecting docker[ssh]<4.0,>=3.7.0 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/48/68/c3afca1a5aa8d2997ec3b8ee822a4d752cf85907b321f07ea86888545152/docker-3.7.2-py2.py3-none-any.whl (134kB)\nRequirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < \"3.5\" in /usr/lib/python2.7/site-packages (from docker-compose) (3.5.0.1)\nCollecting requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)\nCollecting six<2,>=1.3.0 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl\nRequirement already satisfied: PyYAML<4.3,>=3.10 in /usr/lib64/python2.7/site-packages (from docker-compose) (3.10)\nCollecting texttable<0.10,>=0.9.0 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/02/e1/2565e6b842de7945af0555167d33acfc8a615584ef7abd30d1eae00a4d80/texttable-0.9.1.tar.gz\nCollecting dockerpty<0.5,>=0.4.1 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz\nRequirement already satisfied: ipaddress>=1.0.16; python_version < \"3.3\" in /usr/lib/python2.7/site-packages (from docker-compose) (1.0.16)\nCollecting websocket-client<1.0,>=0.32.0 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl (200kB)\nCollecting enum34<2,>=1.0.4; python_version < \"3.4\" (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl\nCollecting docopt<0.7,>=0.6.1 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz\nCollecting jsonschema<3,>=2.5.1 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl\nCollecting cached-property<2,>=1.2.0 (from docker-compose)\n  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl\nCollecting docker-pycreds>=0.4.0 (from docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl\nCollecting paramiko>=2.4.2; extra == \"ssh\" (from docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl (193kB)\nCollecting idna<2.8,>=2.5 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)\nCollecting chardet<3.1.0,>=3.0.2 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)\nCollecting urllib3<1.25,>=1.21.1 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl (131kB)\nCollecting certifi>=2017.4.17 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)\nCollecting functools32; python_version == \"2.7\" (from jsonschema<3,>=2.5.1->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz\nCollecting cryptography>=1.5 (from paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/c3/c1/cf8665c955c9393e9ff0872ba6cd3dc6f46ef915e94afcf6e0410508ca69/cryptography-2.6.1-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)\nCollecting pynacl>=1.0.1 (from paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/b3/25/e605574f24948a8a53b497744e93f061eb1dbe7c44b6465fc1c172d591aa/PyNaCl-1.3.0-cp27-cp27mu-manylinux1_x86_64.whl (762kB)\nCollecting pyasn1>=0.1.7 (from paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)\nCollecting bcrypt>=3.1.3 (from paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/50/d8/95f7cb04344033bf9d1a12c5a7969a15999b6a710fbe1969c517333d9a62/bcrypt-3.1.6-cp27-cp27mu-manylinux1_x86_64.whl (59kB)\nCollecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)\nCollecting cffi!=1.11.3,>=1.8 (from cryptography>=1.5->paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl (415kB)\nCollecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.5->paramiko>=2.4.2; extra == \"ssh\"->docker[ssh]<4.0,>=3.7.0->docker-compose)\n  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)\nInstalling collected packages: six, websocket-client, docker-pycreds, idna, chardet, urllib3, certifi, requests, enum34, asn1crypto, pycparser, cffi, cryptography, pynacl, pyasn1, bcrypt, paramiko, docker, texttable, dockerpty, docopt, functools32, jsonschema, cached-property, docker-compose\n  Found existing installation: chardet 2.2.1\n    Uninstalling chardet-2.2.1:\n\n:stderr: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.\nCould not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/usr/bin/chardetect'\n\nYou are using pip version 19.0.3, however version 19.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}
```

**Comment by corbinstuard** [comment]
I had a discussion with someone on IRC and was told this is the way Pip works due to no inherent transaction locking. The issue still needs to be addressed as behavior is inconsistent with all other modules. The following all behave as expected when ran against two hosts with the same IP:

```yaml
- name: add docker repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker-ce
  yum:
    name: docker-ce
    state: present
    update_cache: yes

- name: enable and start docker
  systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: started

- name: create certs dir
  file:
    path: /var/lib/dvn-{{ inventory_hostname }}/certificates/
    state: directory
  when: twoway_cert

- name: create vtc_config.json from template
  template:
    src: vtc_config.json.j2
    dest: /etc/dvn-{{ inventory_hostname }}/vtc_config.json

- name: log into repo and force re-authorization
  docker_login:
    registry: "{{ jfrog_registry }}"
    username: "{{ jfrog_user }}"
    password: "{{ jfrog_pass }}"
    reauthorize: yes
```
