### ISSUE TITLE
file mode acts different when adding jinja default value 

### ISSUE THREAD

**Issue by molekuul** [ansible/ansible#56047]
##### SUMMARY
In this playbook I explain the problem in short:
When we use the file or copy module with where the file-mode is in a variable.
In the below example, there is a difference when the value is run trough the jinja filter "default" or not. When using the default filter, the value of the file mode gets converted to decimal.
however when the value in the parameter is quoted, it stays the same

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
modules tested are copy and file

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/os14iy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/os14iy/devel/ansible/lib/ansible
  executable location = /home/os14iy/devel/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
but also tested in ansible 2.53 and 2.7.0

##### CONFIGURATION

```ansible-config dump --only-changed
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)
but also tested at RHEL 7

##### STEPS TO REPRODUCE
see playbook below 
```
---
- hosts: all
  gather_facts: False
  vars:
    file_mode : 0644
  tasks:
    - name: Test a file 1
      file:
        src: 'testfile'
        dest: '/tmp/testfile'
        mode: "{{ file_mode | default(0640) }}"

    - name: Test a file 2
      file:
        src: 'testfile'
        dest: '/tmp/testfile'
        mode: "{{ file_mode }}"

```

##### EXPECTED RESULTS
I expect that the file mode will be 0644

##### ACTUAL RESULTS
I created a actual /tmp/testfile with mode 755 at "testserver" to show the example
There is a difference in the filemode between "Test a file 1" and "Test a file 2"
however I expect them to be the same.

```# ansible-playbook -i inventory  playbook_test.yml --check --diff

PLAY [all] ***********************************************************************************************************************************

TASK [Test a file 1] *************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "mode": "0755",
+    "mode": "0420",
     "path": "/tmp/testfile"
 }

 [WARNING]: The src option requires state to be 'link' or 'hard'.  This will become an error in Ansible 2.10

changed: [testserver]

TASK [Test a file 2] *************************************************************************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "mode": "0755",
+    "mode": "0644",
     "path": "/tmp/testfile"
 }

changed: [testserver]

PLAY RECAP ***********************************************************************************************************************************
testserver                 : ok=2    changed=2    unreachable=0    failed=0    skipped=0

```

When in the playbook I quote the value of the file_mode variable
 `   file_mode : "0644"
`

the outcome of both tests is the same.
