### ISSUE TITLE
mysql_db: allow multiple (but not all) databases to be dumped

### ISSUE THREAD

**Issue by markdorison** [ansible/ansible#56059]
##### SUMMARY
The `mysql_db` module allows the user to specify a single database or `all` when using the `dump` or `import` states. It would be useful to be able to specify multiple databases in situations where you want to dump or import more than one database, _but not all_, similar to the [mysqldump command's `--databases` flag](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_databases).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_db

##### ADDITIONAL INFORMATION
Currently, you can either specify a single database or 'all', but not multiple databases when dumping or importing databases. 

```yaml
- name: mysql dump.
  mysql_db:
    state: dump
    name: 
      - db1
      - db2
    target: "{{ dump_path }}"
```
