### ISSUE TITLE
win_chocolatey package_params as dictionary

### ISSUE THREAD

**Issue by mhunsber** [ansible/ansible#56051]
##### SUMMARY

right now, the `package_params` option for the win_chocolatey module is used as a string, so you have to know the chocolatey parameters format of "/Key:Value /Key2:Value2"

It would be nice to be able to pass in a dictionary of parameters instead, and have the module worry about how to format the parameter strings. It would also read nicer in the task file.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_chocolatey
##### ADDITIONAL INFORMATION

Since win_chocolatey is still in "preview," the module could determine if the user passed a string or a dictionary, and display a deprecation warning to allow the current interface to still function the same way.

**current interface**
```yaml
win_chocolatey:
  name: software
  state: present
  package_params: '"/Port:80 /Edition:LicenseKey /AdditionalTools /InstallationPath:C:\\tmp"'
```

**desired interface**
```yaml
win_chocolatey:
  name: software
  state: present
  package_params:
    Port: 80
    Edition: LicenseKey
    AdditionalTools: yes 
    InstallationPath: C:\tmp
```
I realize the boolean flag arguments might be tricky to nail down the best way to specify them, since it wouldn't be clear whether `AdditionalTools: yes` should be `/AdditionalTools` or `/AdditionalTools:yes`
