### ISSUE TITLE
nios module enhancement to add check if exists function

### ISSUE THREAD

**Issue by xpenno255** [ansible/ansible#56077]
##### SUMMARY
Add ability to specify check_if_exists option in relevant nios modules. Current behaviour is that it defaults to True with no ability to override.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nios_mx_record
nios_a_record
nios_cname_record

##### ADDITIONAL INFORMATION

You may wish to specify multiple MX records (same for a and cname etc...) for a single Domain as below

Domain Zone: spencertest.com
MX Record 1
  - Name: spencertest.com
  - mx: mail1.spencertest.com

MX Record 2
  - Name: spencertest.com
  - mx: mail2.spencertest.com

MX Record 3
  - Name: spencertest.com
  - mx: mail3.spencertest.com

The current behavior of the nios_mx_record is that it would create the first MX Record and then update it twice. The end result would be a single MX Record matching MX Record 3 above.

This is achieveable via Infoblox GUI and is supported in the relevant RFCs.

The Infoblox-Client appears to have functionality to achieve this with the check_if_exists option as mentioned here https://github.com/infobloxopen/infoblox-client/issues/171

The default behavior is True, however when set to False this allow Infoblox-Client to create multiple values with the same name.

```yaml
#current playbook example
vars:
    mailhosts:
      - mailhost.test.bham.ac.uk
      - mailhost2.test.bham.ac.uk

- name: configure multiple MX records for a single zone
  nios_mx_record:
    name: ansible.com
    mx: "{{ item }}"
    preference: 10
    state: present
    provider:
      host: myinfoblox.com
      username: admin
      password: admin
  connection: local
  loop: "{{ mailhosts }}"




#proposed playbook example
vars:
    mailhosts:
      - mailhost.test.bham.ac.uk
      - mailhost2.test.bham.ac.uk

- name: configure multiple MX records for a single zone
  nios_mx_record:
    name: ansible.com
    mx: "{{ item }}"
    preference: 10
    state: present
    check_if_exists: False
    provider:
      host: myinfoblox.com
      username: admin
      password: admin
  connection: local
  loop: "{{ mailhosts }}"

```
