### ISSUE TITLE
ERROR! 'delegate_to' is not a valid attribute for a TaskInclude on ansible 2.8

### ISSUE THREAD

**Issue by lfventura** [ansible/ansible#56072]
##### SUMMARY
Using delegate_to with include_tasks in a play returns
 ERROR! 'delegate_to' is not a valid attribute for a TaskInclude
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_task with delegate_to

##### ANSIBLE VERSION

```
ansible 2.8.0rc2.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/lucas.ventura/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lucas.ventura/.pyenv/versions/2.7.15/lib/python2.7/site-packages/ansible
  executable location = /Users/lucas.ventura/.pyenv/versions/2.7.15/bin/ansible
  python version = 2.7.15 (default, Feb 13 2019, 11:36:51) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(/etc/ansible/ansible.cfg) = True
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE

```yaml
  - name: Setting up xxxx
    include_tasks: xxxx.yml
    with_items:
      - "{{ plugins_loop }}"
    delegate_to: 127.0.0.1
    run_once: true
```

##### EXPECTED RESULTS
Normal run as in ansible 2.7

##### ACTUAL RESULTS

```paste below
ERROR! 'delegate_to' is not a valid attribute for a TaskInclude

The error appears to be in '/Users/lucas.ventura/git/youse/devops/ansible_v2/roles/xxxx/tasks/main.yml': line 44, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Setting up xxxx
    ^ here

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/task.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is expected.  In Ansible 2.7, although there was no error, using `delegate_to` on `include_tasks` was silently ignored and no delegation happened.

In Ansible 2.8, only attributes that will work, are allowed on includes.

I believe what you actually want is the following:

```
  - name: Setting up xxxx
    include_tasks: xxxx.yml
    args:
      apply:
          delegate_to: 127.0.0.1
    with_items:
      - "{{ plugins_loop }}"
    run_once: true
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
