### ISSUE TITLE
cloudstack: cs_network_acl: support cidr lists

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#56080]
##### SUMMARY

Similar as cs_firewall in #33020 implement `cidrs` as list (alias `cidr`) and also return a cidrs as list. Tests needs to be updated to cover this feature.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cs_network_acl_rule

##### ADDITIONAL INFORMATION

```yaml
- cs_network_acl_rule:
    network_acl: web
    rule_position: 1
    vpc: my vpc
    traffic_type: ingress
    action_policy: allow
    port: 80
    cidrs: 
    - 1.2.3.0/24
    - 1.2.1.0/24
```
