### ISSUE TITLE
Warn user if nothing is matched by tag

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#56106]
##### SUMMARY

If the user mis-spells a tag when invoking a playbook, then ansible will run 0 tasks and claim it suceeded. This is misleading.

Ansible should warn users when 0 tasks match the tags, because the user probably did not intent to run 0 tasks.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core

##### ADDITIONAL INFORMATION

```yaml
---
- hosts: localhost
  tasks:
     - name: test
       debug:
         msg: "test"
       tags:
         - something

```
Invoke this with:

`ansible-playbook test.yaml --tags somethin`

(Note the lack of the `e` at the end. It's a mis-spelled tag.)

Expected behavior: Ansible warns the user that no tag called `somethin` exists, and zero tasks will be run.

Actual behavior: Ansible runs and prints all green, but for zero tasks. As a user my first impression was that all tasked tagged with `something` had been completed, but this was not the case.
