### ISSUE TITLE
Allow configuring executable path for keytool in java_keystore, as implemented in java_cert

### ISSUE THREAD

**Issue by iinuwa** [ansible/ansible#56122]
##### SUMMARY

Allow configuring executable path for `keytool` in `java_keystore`, as implemented in `java_cert`
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`java_keystore`
##### ADDITIONAL INFORMATION

When keytool is not on the default path, then the `java_keystore` module cannot be used to create a keystore. The [code for the module](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/java_keystore.py#L248) uses  ` keytool_bin = module.get_bin_path('keytool', True)` to look up the path for the tool, the module returns:
```
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Failed to find required executable keytool in paths: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin"}
```

Since `java_cert` does not support adding a key to the keystore, either using `java_keystore` or `command`/`shell` is necessary to accomplish this. Adding the `executable` parameter as in `java_cert` would be helpful for users who have Java extracted to a directory that is not on the path.

```yaml
- name: Create keystore for Elasticsearch
  java_keystore:
    dest: "/path/to/keystore"
    password: "keystore_password"
    certificate: "-----BEGIN CERTIFICATE-----..."
    private_key: "-----BEGIN RSA PRIVATE KEY-----..."
    name: my_keystore
    executable: "/path/to/java/home/bin/keytool"
```
