### ISSUE TITLE
VMware: Specify Folder for vmware_vm_facts

### ISSUE THREAD

**Issue by codyja** [ansible/ansible#56125]
##### SUMMARY
It would be fantastic if vmware_vm_facts could be pointed to a folder and only return objects within that folder. For example if I only wanted templates within /builds/ folder, it should complete rather quickly instead of scanning all VMs and templates.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_vm_facts

##### ADDITIONAL INFORMATION

```yaml
- name: Gather only registered virtual machine templates in build folder
  vmware_vm_facts:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    vm_type: template
    folder: /build/
  delegate_to: localhost
  register: template_facts
```
