### ISSUE TITLE
fmgr_fwobj_address unable to exicute 

### ISSUE THREAD

**Issue by sinu** [ansible/ansible#56128]
##### SUMMARY

Hello team 
i am trying to consume fmgr_fwobj_address but i am getting the following error.
I couldn't see proper documentation about the module hence i am following below link.
https://buildmedia.readthedocs.org/media/pdf/ftnt-ansible-docs/latest/ftnt-ansible-docs.pdf 
```

- hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    - name: ADD IPv4 IP ADDRESS OBJECT
      fmgr_fwobj_address:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ipv4: "ipmask"
        ipv4addr: "10.7.220.30/32"
        name: "ansible_v4Obj"
        comment: "Created by Ansible"
        color: "6"

```
error

```
ESTABLISH LOCAL CONNECTION FOR USER: root
EXEC /bin/sh -c 'echo ~root && sleep 0'
EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105 `" && echo ansible-tmp-1557113620.46-150802724413105="` echo /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/fortimanager/fmgr_fwobj_address.py
PUT /root/.ansible/tmp/ansible-local-141555NrKyW/tmpYRETTe TO /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105/AnsiballZ_fmgr_fwobj_address.py
 EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105/ /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105/AnsiballZ_fmgr_fwobj_address.py && sleep 0'
EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105/AnsiballZ_fmgr_fwobj_address.py && sleep 0'
 EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1557113620.46-150802724413105/ > /dev/null 2>&1 && sleep 0'



fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "color": "6",
            "comment": "Created by Ansible",
            "host": "172.16.20.10",
            "ipv4": "ipmask",
            "ipv4addr": "10.7.220.30/32",
            "name": "ansible_v4Obj",
            "password": "admin123",
            "username": "admin"
        }
    },
    "msg": "Unsupported parameters for (fmgr_fwobj_address) module: host, password, username Supported parameters include: adom, allow_routing, associated_interface, cache_ttl, color, comment, country, end_ip, fqdn, group_members, group_name, ipv4, ipv4addr, ipv6, ipv6addr, mode, multicast, name, obj_id, start_ip, visibility, wildcard, wildcard_fqdn"
}

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fortimanager

##### ANSIBLE VERSION
2.8

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
FortiManager-VM64

##### STEPS TO REPRODUCE
```
- hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars
    - name: ADD IPv4 IP ADDRESS OBJECT
      fmgr_fwobj_address:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        ipv4: "ipmask"
        ipv4addr: "10.7.220.30/32"
        name: "ansible_v4Obj"
        comment: "Created by Ansible"
        color: "6"
```

```
