### ISSUE TITLE
docker_container_module: Ignore option for certain parameters

### ISSUE THREAD

**Issue by lukasmrtvy** [ansible/ansible#56172]
##### SUMMARY
It would be great if something like `ignore` parameter in `docker_container module` exist.
For example: if You dont want to redeploy container if label is changed.
Common use case:
Label with timestamp of creation.
```
- set_fact:
    mycontainer:
        labels: 
           owner: foo
           timestamp: "{{ ansible_date_time.iso8601 }}"

- docker_container:
    ...
    labels: "mycontainer.labels"
    ignore: "labels.mytimestamp"
```
In this case, container is not recreated.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_container
https://docs.ansible.com/ansible/latest/modules/docker_container_module.html

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lukasmrtvy** [comment]
!component docker_container

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @cove @danihodovic @dariko @dusdanig @felixfontein @joshuaconner @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
Check out the `comparisons` option, which is new for Ansible 2.8. It is not as detailled as you want, but it gives you a lot more freedom. You can see the documentation [here](https://docs.ansible.com/ansible/devel/modules/docker_container_module.html) -- this will become the new `latest` documentation once 2.8 is released.

**Comment by lukasmrtvy** [comment]
@felixfontein Thanks

Unfortunalley `comparsions` would not work like this:
```
  docker_container:
    name: test
    image: ubuntu:18.04
    env:
        - arg1: "true"
        - TIMESTAMP: "{{ ansible_date_time.iso8601 }}"
    comparisons:
      env.*: strict
      env.TIMESTAMP: ignore

```
```
  docker_container:
    name: test
    image: ubuntu:18.04
    labels:
        - arg1: "true"
        - TIMESTAMP: "{{ ansible_date_time.iso8601 }}"
    comparisons:
      labels.TIMESTAMP: ignore
      labels.*: strict
```
