### ISSUE TITLE
can't setup facts gathering by variable

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5618]
Consider the simple playbook:

``` yaml

---
- hosts: all
  gather_facts: "{{ foobar | bool }}"
```

I would expect to control if the facts are gathered by setting the value of foobar variable but the facts are gathered always no matter what the value for `foobar` is.

Removing the `"{{...}}"` enclosure does not help too.
