### ISSUE TITLE
no-run hosts

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5620]
This is a feature request for some special parameter in inventory which when set disables **all** actions done for the host **except** those which are delegated to some other host.

Generic example:

``` yaml

---
- hosts: all
  tasks:
  - name: configure some service
    ....
  - name: configure server-side configs for the service
    ...
    delegate_to: "{{ central_server }}"
```

This way we could do some minor hooking of Windows systems into inventory.
My specific use-case is configuring bacula_fd clients for all linux boxes and creating bacula director configs for both linux boxes and windows boxes.
I probably could do a workaround with having 2 separate playbooks for these 2 groups of boxes but this can't be done (or actually is much complicated) due to #5618 and #5619.
