### ISSUE TITLE
acme_certificate no wildcard cert dns-01 challenge fails due Incorrect TXT record.

### ISSUE THREAD

**Issue by amatacchieri** [ansible/ansible#56215]
##### SUMMARY
acme_certificate no wildcard cert dns-01 challenge fails due Incorrect TXT record. The code correctly creates the challenge and the TXT record, as showed in the playbook output. The TXT record is created correctly on Route 53, as requested in the challenge_data dns-01 resource_value field.
The TXT record is actually correct even if in the playbook output appears escaped:

`Incorrect TXT record \"GNA7T7Tb-rhWiaRciVVFtHrVdqouAR6rMRuFY1ILYg8\"
`

The TXT record is correct, resolved by global dns

In the output playbook is showed how the correct TXT record is actually resolved, matching the one requested by the challenge.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
acme_certificate

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
```

##### CONFIGURATION

```paste below
boto 2.49.0          
boto3 1.9.126
```

##### OS / ENVIRONMENT

Linux LinuxArch 5.0.9-arch1-1-ARCH  x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```
Just try to create a challenge and validate it using the code provided. 



```

```yaml
 name: Create a challenge for {{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}
  acme_certificate:
    account_key_src: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.pem
    account_email: "{{cert_email}}"
    src: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.csr
    cert: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.crt
    challenge: "{{challengetype}}"
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    remaining_days: 60
  register: challenge_out

- name: Create the challenge TXT record on Route 53
  route53:
    zone: "{{route53_domain}}"
    record: "{{challenge_out.challenge_data[fullzone][challengetype].record}}"
    type: TXT
    ttl: 5
    state: present
    overwrite: True
    #value: "{{ challenge_out.challenge_data[fullzone][challengetype].resource_value | regex_replace('^(.*)$', '\"\\1\"') }}"
    value: '"{{challenge_out.challenge_data[fullzone][challengetype].resource_value}}"'

# Sleep...
- pause:
    minutes: 1
  when: action=="deploy" and function=="app" and challenge_out is changed #and ec2_facts.instances |length==0


- name: Requesting challenge validation
  acme_certificate:
    account_key_src: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.account.pem
    account_email: "{{cert_email}}"
    src: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.csr
    cert: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.crt
    fullchain: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}.fullchain.crt
    chain: ~/{{projectName}}{{env}}-{{application}}-{{serverID}}.{{route53_domain}}-intermediate.crt
    challenge: "{{challengetype}}"
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    remaining_days: 60
    data: "{{ challenge_out }}"
```

##### EXPECTED RESULTS

Challenge validation to complete

##### ACTUAL RESULTS
Challenge validation fails. See below output. The real domain name used for the validation has been replaced with "foodomain.com" for privacy reasons.

```paste below
The full traceback is:
  File "/tmp/ansible_acme_certificate_payload_7t10ep32/__main__.py", line 930, in main
    client.finish_challenges()
  File "/tmp/ansible_acme_certificate_payload_7t10ep32/__main__.py", line 796, in finish_challenges
    self._validate_challenges(domain, auth)
  File "/tmp/ansible_acme_certificate_payload_7t10ep32/__main__.py", line 572, in _validate_challenges
    self._fail_challenge(domain, result, 'Authorization for {0} returned invalid')
  File "/tmp/ansible_acme_certificate_payload_7t10ep32/__main__.py", line 532, in _fail_challenge
    raise ModuleFailException("{0}: {1}".format(error.format(domain), error_details))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "account_email": "amatacchieri@foodomain.com",
            "account_key_content": null,
            "account_key_src": "/home/antonello/sittowerprd-twr-1.foodomain.com.account.pem",
            "account_uri": null,
            "acme_directory": "https://acme-v01.api.letsencrypt.org/directory",
            "acme_version": 1,
            "agreement": null,
            "cert": "~/sittowerprd-twr-1.foodomain.com.crt",
            "chain": "~/sittowerprd-twr-1.foodomain.com-intermediate.crt",
            "chain_dest": "/home/antonello/sittowerprd-twr-1.foodomain.com-intermediate.crt",
            "challenge": "dns-01",
            "csr": "/home/antonello/sittowerprd-twr-1.foodomain.com.csr",
            "data": {
                "account_uri": "https://acme-v01.api.letsencrypt.org/acme/reg/56099811",
                "authorizations": {
                    "sittowerprd-twr-1.foodomain.com": {
                        "challenges": [
                            {
                                "status": "pending",
                                "token": "MzGiTXimnA1x_Bm_aaJjhVyc_y09c4_KlOiPJvdA9D8",
                                "type": "http-01",
                                "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/w3UG7iEU8GqaVVF0JCRIpRmlcLWn8MxVSOlMHmxsjdA/15590902529"
                            },
                            {
                                "status": "pending",
                                "token": "xz5D1YxemsLAr8Tl4IKYruY1SKzuwhIv-VIsTXVQslQ",
                                "type": "tls-alpn-01",
                                "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/w3UG7iEU8GqaVVF0JCRIpRmlcLWn8MxVSOlMHmxsjdA/15590902530"
                            },
                            {
                                "status": "pending",
                                "token": "6HwwKxfBGSFEgIe6u9uipMhklpwo9ABDuGg8Uz3tNaA",
                                "type": "dns-01",
                                "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/w3UG7iEU8GqaVVF0JCRIpRmlcLWn8MxVSOlMHmxsjdA/15590902531"
                            }
                        ],
                        "combinations": [
                            [
                                0
                            ],
                            [
                                1
                            ],
                            [
                                2
                            ]
                        ],
                        "expires": "2019-05-14T13:31:10Z",
                        "identifier": {
                            "type": "dns",
                            "value": "sittowerprd-twr-1.foodomain.com"
                        },
                        "status": "pending",
                        "uri": "https://acme-v01.api.letsencrypt.org/acme/authz/w3UG7iEU8GqaVVF0JCRIpRmlcLWn8MxVSOlMHmxsjdA"
                    }
                },
                "cert_days": -1,
                "challenge_data": {
                    "sittowerprd-twr-1.foodomain.com": {
                        "dns-01": {
                            "record": "_acme-challenge.sittowerprd-twr-1.foodomain.com",
                            "resource": "_acme-challenge",
                            "resource_value": "GNA7T7Tb-rhWiaRciVVFtHrVdqouAR6rMRuFY1ILYg8"
                        },
                        "http-01": {
                            "resource": ".well-known/acme-challenge/MzGiTXimnA1x_Bm_aaJjhVyc_y09c4_KlOiPJvdA9D8",
                            "resource_value": "MzGiTXimnA1x_Bm_aaJjhVyc_y09c4_KlOiPJvdA9D8.LvaU5diu-DoPszk6kwswgeyIPhXA1wU0qir_aYP-XAg"
                        },
                        "tls-alpn-01": {
                            "resource": "sittowerprd-twr-1.foodomain.com",
                            "resource_value": "EhtdnyvCgkXE2pK0Z8ha5w+Vbh+W7Gohou47Hs/8ZG4="
                        }
                    }
                },
                "challenge_data_dns": {
                    "_acme-challenge.sittowerprd-twr-1.foodomain.com": [
                        "GNA7T7Tb-rhWiaRciVVFtHrVdqouAR6rMRuFY1ILYg8"
                    ]
                },
                "changed": true,
                "failed": false,
                "finalize_uri": null,
                "order_uri": null
            },
            "deactivate_authzs": false,
            "dest": "/home/antonello/sittowerprd-twr-1.foodomain.com.crt",
            "force": false,
            "fullchain": "~/sittowerprd-twr-1.foodomain.com.fullchain.crt",
            "fullchain_dest": "/home/antonello/sittowerprd-twr-1.foodomain.com.fullchain.crt",
            "modify_account": true,
            "remaining_days": 60,
            "select_crypto_backend": "auto",
            "src": "~/sittowerprd-twr-1.foodomain.com.csr",
            "terms_agreed": false,
            "validate_certs": true
        }
    },
    "msg": "Authorization for sittowerprd-twr-1.foodomain.com returned invalid:  CHALLENGE: dns-01 DETAILS: Incorrect TXT record \"GNA7T7Tb-rhWiaRciVVFtHrVdqouAR6rMRuFY1ILYg8\" found at _acme-challenge.sittowerprd-twr-1.foodomain.com; CHALLENGE: tls-alpn-01; CHALLENGE: http-01;",
    "other": {}
}

```
