### ISSUE TITLE
Script module remote

### ISSUE THREAD

**Issue by ivangonzalezz** [ansible/ansible#56213]
##### SUMMARY

Add a parameter to look for the script directly in the remote host such as in copy module, parameter remote_src

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

script module

##### ADDITIONAL INFORMATION

For example, if you want to download a script directly on the host and execute from there.

```yaml
- name: Get script from url
  get_url:
    url: https://example.com/script.sh
    dest: /tmp
    mode: 755

- name: Run the script
  script:
    free_form: /tmp/script.sh
    remote_src: yes
```
