### ISSUE TITLE
win_chocolatey_module requirements are incorrect in the documentation

### ISSUE THREAD

**Issue by captainjs** [ansible/ansible#56225]
##### SUMMARY
The requirements explained in the win_chocolatey_module are incorrect and information on that page is contradictory.
It says:
**_Requirements**
The below requirements are needed on the host that executes this module.

chocolatey >= 0.10.5 (will be upgraded if older)_

Source:
https://docs.ansible.com/ansible/latest/modules/win_chocolatey_module.html#win-chocolatey-module

That is not correct because it's possible to install chocolatey without it being installed at all, using the parameter "state":
_When present, will ensure the package is installed._

So we don't need to have chocolatey >= 0.10.5 as a requirement, since we can install it from "zero" using the very same module, with parameter "state: present".

By the way, installing chocolatey using ansible win_chocolatey module will:
-Download and leave some leftovers files (approximately 15mb of files) in:
C:\Users\thewindowsuser\AppData\Local\Temp\chocolatey\chocInstall

-Install chocolatey server here:
"C:\\ProgramData\\chocolatey\\bin\\choco.exe"

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
ansible 2.9.7
```

##### CONFIGURATION

```
 - name: Ensure Chocolatey itself is installed and use latest version
      win_chocolatey:
        name: chocolatey
       #state can be "present" to have chocolatey server installed
        state: latest
        #the following params are only for specific setup
        proxy_url: http://proxy.xyz:8080
        validate_certs: no

```

##### OS / ENVIRONMENT
Ansible, Windows 2012 server

##### ADDITIONAL INFORMATION

Correcting the requirements should improve the documentation and help understand how to install chocolatey server using win_chocolatey module.
