### ISSUE TITLE
win_file doesn't create directory if intermediates are missing (UNC)

### ISSUE THREAD

**Issue by jceddy** [ansible/ansible#56239]
##### SUMMARY
I have the following task:

```
- name: make sure target path exists
  win_file:
    path: full_target_path
    state: directory
  tags:
    - preload
    - full
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_pass: "{{ ansible_password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
```

I expect this to create the directory specified at full_target_path, including all intermediate folders, if they don't exist. In my case, it fails to do this, with no error/warning. The only "special" thing I can think of is that the path is a UNC directory specification. I know about the re-authentication issue for commands that touch the network, which is why I have ansible_become variables specified on the task (other similar tasks are working correctly).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_file

##### ANSIBLE VERSION

```
ansible 2.7.7
  config file = /home/userg/ansiblegit/ansible/ansible.cfg
  configured module search path = [u'/home/userg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
DEFAULT_JINJA2_EXTENSIONS(/home/userg/ansiblegit/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
```

##### OS / ENVIRONMENT

Ansible server information:
```
   Static hostname: ansibleserver.dev.company.local
         Icon name: computer-vm
           Chassis: vm
        Machine ID: c6fde27eb8cc4bdbb8b38af0103c4413
           Boot ID: 33f8c7daa99b482e936debdd9e1ba275
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.10.1.el7.x86_64
      Architecture: x86-64
```

Target Windows server information:

```
{
    "Platform":  2,
    "ServicePack":  "",
    "Version":  {
                    "Major":  10,
                    "Minor":  0,
                    "Build":  14393,
                    "Revision":  0,
                    "MajorRevision":  0,
                    "MinorRevision":  0
                },
    "VersionString":  "Microsoft Windows NT 10.0.14393.0"
}
```

##### STEPS TO REPRODUCE

Run the following task, providing a UNC path that you have write access to, and that is missing intermediate folders, as well as the required credentials for network access.

```
- name: make sure target path exists
  win_file:
    path: full_target_path
    state: directory
  tags:
    - preload
    - full
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_pass: "{{ ansible_password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
```

##### EXPECTED RESULTS

The directory is created, along with any missing intermediate subdirectories.

##### ACTUAL RESULTS

The directory is not created, and there is no error or warning message.

```
TASK [webserver : make sure target path exists] *******************************************************************************************************************************************************************
task path: /home/userg/ansiblegit/ansible/roles/webserver/tasks/product-app-win.yml:205
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_file.ps1
<targetserver.dev.company.local> ESTABLISH WINRM CONNECTION FOR USER: UserG@dev.company.local on PORT 5986 TO targetserver.dev.company.local
EXEC (via pipeline wrapper)
ok: [targetserver.dev.company.local] => {
    "changed": true
}
META: noop
META: noop
```

**Update**: I took a look inside win_file.ps1 and tried to manually run the relevant code portions directly in powershell on the target server. When I ran this line (everthing up through "Latest" already exists, so I expect "dev" and "project" to be created):

`New-Item -Path "\\databaseserver.dev.company.local\D\product\root\Latest\dev\project" -ItemType Directory -WhatIf:$false | Out-Null`

It actually generated the directory, as well as the intermediate directories...so something must be keeping that from happening further up in the code, but I can't figure out what that might be.

**More update**: I copied win_file.ps1 and the relevant module files to a temp directory on the target machine and tried to manually run it via powershell. When I did that, it worked, as well, and gave me the same output I see coming from ansible (changed: true).

```
PS C:\Users\UserG> $complex_args = @{path="\\databaseserver.dev.company.local\D\product\root\Latest\dev\project"; state="directory"}
PS C:\Users\UserG> c:\temp\win_file.ps1
{"changed":true}
```

**Even more update**: I managed to run this as Ad-Hoc command using Ansible from the command line, and that worked fine, as well, no now I'm completely at a loss as to why the task in the playbook isn't working.

```
[userg@dev.company.local@ansibleserver ansible]$ ansible windowsservers -i 'inventories/project' -m win_file -a 'path="\\\\databaseserver.dev.company.local\\D\\product\\root\\Latest\\dev\\project" state="directory"' --extra-vars '{"ansible_user":"UserG@dev.company.local","ansible_password":"THE_PASSWORD","ansible_become":"yes","ansible_become_method":"runas","ansible_become_user":"UserG@dev.company.local","ansible_become_pass":"THE_PASSWORD","ansible_become_flags":"logon_type=new_credentials logon_flags=netcredentials_only"}'
targetserver.dev.company.local | CHANGED => {
    "changed": true
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @if-meaton @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
Hmm, that's a head scratcher.
I had trouble like this in the past but in my case it turned out that the destination share wasn't actually a domain peer, it was just a samba share on some embedded linux nas drive thingy, not an actual windows domain member.  However that doesn't seem to apply in your case.

If you were only able to get it to work by running the powershell on the windows target, I'd suggest you were still having a second hop authentication issue... but you have it working using ansible ad-hoc.

Out of interest, how are you connecting (winrm or pypsrp)?  which transport are you using ( credssp, kerberos, ntlm)? And how are you authenticating?  It appears you are using domain users - if so you might try using credential delegation as mentioned here: https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#limitations by setting ```ansible_winrm_kerberos_delegation=true```

I've used credential delegation successfully for creating files on remote shares, not sure if I have tested creating directories though.  I'm not sure if you can set ```ansible_winrm_kerberos_delegation=true``` per task though so it might not meet you needs, but worth experimenting as it might make your task definition less verbose.

The only other thing that comes to mind as difference between ad-hoc and playbook is specifying the UNC path - it looks like you have a handle on this but python command line processing adds an extra layer of parsing over and above all the other parsers between the playbook text and commands being executed.  In case you arrived at this by trial and error (I know I did) then this is worth a read:  https://docs.ansible.com/ansible/latest/user_guide/windows_usage.html#path-formatting-for-windows

Can you share the original path you used in the playbook? Obviously its not good if it results in a silent failure but it might help to understand what's going on.

TBH we could usefully add some UNC path examples to the path-formatting-for-windows now that win_file / win_copy can be used with UNC paths.

**Comment by jceddy** [comment]
Well, I got it to work by changing the task to this:

```
- name: make sure target path exists
  win_file:
    path: "{{ full_target_path }}"
    state: directory
  tags:
    - preload
    - full
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_pass: "{{ ansible_password }}"
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
```

My confusion (and the reason I didn't just do this earlier) comes from the fact that elsewhere in the same script I am doing the same operation, feeding a variable directly into win_file's path argument and it's working fine.

The difference is that in that spot the path is not a UNC path, so this must be another one of the backslash-handling quirks (or something) that I've had to deal with when doing deployments to on the windows network.

Anyway...should I close the issue, or is this something that youse want to dig into further?
