### ISSUE TITLE
zabbix_screen graphs_in_row in loop

### ISSUE THREAD

**Issue by okgolove** [ansible/ansible#56233]
##### SUMMARY

If you use loop and set up graphs_in_row via {{ item.graphs_in_row | int }} you get an error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_screen

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = None
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:17:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac OS 10.14.4, remote host Xenial, python3.5

##### STEPS TO REPRODUCE

Create a list of dicts:
```
zabbix_screens:
  - name: EU - System
    group: EU
    graphs_in_row: 6
    graph_names:
      - CPU utilization
      - Memory usage
```

```yaml
- name: create zabbix auction system screens
  zabbix_screen:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_password }}"
    screens:
      - screen_name: "{{ item.name }}"
        host_group: "{{ item.group }}"
        state: present
        graph_names: "{{ item.graph_names }}"
        graph_width: 500
        graph_height: 100
        # it doesn't work
        graphs_in_row: "{{ item.graphs_in_row | int }}"
        # it works
        # graphs_in_row: 6
  with_items: "{{ zabbix_screens }}"
```

##### EXPECTED RESULTS

Screen has been created

##### ACTUAL RESULTS

I get an error:

```paste below
"module_stdout": "Traceback (most recent call last):
  File \"/root/.ansible/tmp/ansible-tmp-1557339142.75-80239796236786/AnsiballZ_zabbix_screen.py\", line 113, in <module>
    _ansiballz_main()
  File \"/root/.ansible/tmp/ansible-tmp-1557339142.75-80239796236786/AnsiballZ_zabbix_screen.py\", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/root/.ansible/tmp/ansible-tmp-1557339142.75-80239796236786/AnsiballZ_zabbix_screen.py\", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File \"/usr/lib/python3.5/imp.py\", line 234, in load_module
    return load_source(name, filename, file)
  File \"/usr/lib/python3.5/imp.py\", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File \"<frozen importlib._bootstrap>\", line 626, in _exec
  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module
  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed
  File \"/tmp/ansible_zabbix_screen_payload_z45h6t3j/__main__.py\", line 420, in <module>
  File \"/tmp/ansible_zabbix_screen_payload_z45h6t3j/__main__.py\", line 382, in main
  File \"/tmp/ansible_zabbix_screen_payload_z45h6t3j/__main__.py\", line 263, in get_hsize_vsize
TypeError: unorderable types: int() > str()
", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/zabbix/zabbix_screen.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/zabbix/zabbix_screen.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @D3DeFi @cove @eikef @harrisongu
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by D3DeFi** [comment]
Hey, finally had some time to test this. It seems that you've fixed this by yourself in #57325. Change that fixed this was explicit definition of `screens` sub options in `argument_spec`. Can you try this again with those changes merged?

Not sure how this was happening tho, maybe python3 was defaulting types to string for every missing `argument_spec['screens'][*]` sub option even when you've provided `| int` filter. This is reproducible without loop too. Just use variable like this:
```
          screens:
            - screen_name: "Linuxes"
              host_group: "Linux servers"
              state: present
              graph_names: ['CPU utilization', 'Memory usage']
              graph_width: 500
              graph_height: 100
              graphs_in_row: "{{ graphsrow | int }}"
```
