### ISSUE TITLE
docker_container_module: state restarted

### ISSUE THREAD

**Issue by lukasmrtvy** [ansible/ansible#56255]
##### SUMMARY
Its not possible to mitigate `docker restart mycontainer` with `docker_container` module.
Use case:

```
    - template:
         src: "{{ item.volumesrc  }}"
         dest: "{{ item.volumedest }}"
      loop: ....
      notify: 
         - restart container

    - name: create container
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        envs: "{{ item.envs }}"
      loop: ....
```
```
  handlers:
    - name: restart container
      shell: "docker restart {{ item.name }}"
      failed_when: ...
      changed_when: ...
      loop: ....
```

Of course that I can probably do:
```
  handlers:
    - name: restart container
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        restart: yes
      loop: ....
```
But I will also have to supply all parameters (from create container) , or container will be recreated with parameters specified in restart container task.

So this would be a solution:
```
  handlers:
    - name: restart container
      docker_container:
        name: "{{ item.name }}"
        state: restarted
      loop: ....
```

Another possible solution would be control sha of volumes and if something is changed, then restart container. There should be also something like `ignore_volume_sha_checking`, if container/image can handle hotreload ( config files )

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_container

##### ADDITIONAL INFORMATION

```yaml

```
