### ISSUE TITLE
os_server security groups not working on creation

### ISSUE THREAD

**Issue by josemgom** [ansible/ansible#56259]
##### SUMMARY
When creating a OpenStack instance with security groups, security groups are added but it doesn't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
/cloud/openstack/os_server.py

##### ANSIBLE VERSION
```
ansible 2.7.1
  config file = /Users/josemgom/local/ansible/myproject/ansible.cfg
  configured module search path = [u'/Users/josemgom/local/ansible/myproject/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible-2.7.1-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE
Give the following

```
    - name: "Create Box {{ box_name }}"
      when: boxEnabled == "True" and type == "TEST"
      register: box
      os_server:
        meta: "{{ diskSchema }}"
        state: present
        name: "{{ box_name }}"
        flavor: "{{ flavor }}”
        image: corp:centos-7.4
        terminate_volume: yes
        boot_from_volume: yes
        api_timeout: 300
        security_groups: ["default", "ssh"]
        nics:
          - port-name: "{{ box_name }}_APP"
          - net-name: "{{ openstack_nfs_network }}"
        key_name: '{{ box_name | regex_replace("\." ,"-") }}'

```

##### EXPECTED RESULTS
OpenStack instance is created with the security groups and rules are applied correctly. I.e. With the security group ssh I should be able to connect using ssh.

##### ACTUAL RESULTS
OpenStack instance is created with the security groups and I can’t connect using ssh.

Workaround 1: Join OpenStack, remove the group and add it again.
Workaround 2: Create the instance without security groups and add it after creation calling again to os_server module.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/openstack/os_server.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_server.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @evrardjp @gtema @juliakreger @mnaser @odyssey4me @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by acalm** [comment]
I have noticed the same behaviour, it does not seem that the bug is in the os_server module though, but rather the openstacksdk. The only security group applied is the default one. I currently work around the issue by running the module twice as it'll update the security groups. In your case that would mean duplicating "Create Box {{ box_name }}". I'm using a conditional for my workaround to avoid wasting time, something like:

`
- name: run os_server twice (workaround) to attach all security groups
  connection: local
  os_server:
    -- 8< -- 8< ---
    name: "{{ inventory_hostname }}"
    security_groups: "{{ my_security_groups }}"
  when:
    - my_security_groups is defined
`

**Comment by josemgom** [comment]
> I have noticed the same behaviour, it does not seem that the bug is in the os_server module though, but rather the openstacksdk. The only security group applied is the default one. I currently work around the issue by running the module twice as it'll update the security groups. In your case that would mean duplicating "Create Box {{ box_name }}". I'm using a conditional for my workaround to avoid wasting time, something like:
> 
> ```
> - name: run os_server twice (workaround) to attach all security groups
>   connection: local
>   os_server:
>     -- 8< -- 8< ---
>     name: "{{ inventory_hostname }}"
>     security_groups: "{{ my_security_groups }}"
>   when:
>     - my_security_groups is defined
> ```

Hi @acalm, yes, I am doing the same, my workaround is running the os_server task twice if there are security groups defined.

**Comment by gtema** [comment]
@acalm, @josemgom: which version of openstacksdk are you using? It works for me without problems with sdk==0.12.0 and sdk==0.27.0

```
    - name: create server
      os_server:
        cloud: otc
        name: "test-server"
        state: present
        flavor: "s2.large.1"
        image: "Standard_Fedora_29_latest"
        key_name: <snip>
        nics:
          - net-id: e75f7e17-9604-4aef-ab9d-4f60e3e1adbf
        security_groups:
          - test-bastion_sg
          - default
```
