### ISSUE TITLE
mysql_user unable to connect to database on Percona 8.0

### ISSUE THREAD

**Issue by gstorme** [ansible/ansible#56261]
##### SUMMARY

Setting a root password on a new MySQL (Percona) 8.0 instance fails.
Works fine on previous MySQL version 5.7.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.8.0rc1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### STEPS TO REPRODUCE

```yaml
- name: Install Percona Server Apt repository
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb

- name: Enable Percona 8.0 repository
  shell: percona-release setup ps80
  args:
    creates: /etc/apt/sources.list.d/percona-ps-80-release.list

- name: Install percona database server
  apt:
    name: "percona-server-server"
    state: present
    update_cache: yes

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
```

##### EXPECTED RESULTS

MySQL root user password gets (re)set

##### ACTUAL RESULTS

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_mysql_user_payload_il5T08/__main__.py", line 648, in main
    connect_timeout=connect_timeout)
  File "/tmp/ansible_mysql_user_payload_il5T08/ansible_mysql_user_payload.zip/ansible/module_utils/mysql.py", line 79, in mysql_connect
    db_connection = mysql_driver.connect(**config)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)

failed: [stretch] (item=localhost) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "ca_cert": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "name": "root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "priv": null,
            "sql_log_bin": true,
            "state": "present",
            "update_password": "always",
            "user": "root"
        }
    },
    "item": "localhost",
    "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2012, 'Error in server handshake')"
}
```

I found possibly related issues, but the exception message is different in my case.

https://github.com/ansible/ansible/issues/41116
https://github.com/ansible/ansible/issues/55917
https://github.com/ansible/ansible/issues/55845

MySQL root user:

```
mysql> select * from user where User = 'root'\G;
*************************** 1. row ***************************
                    Host: localhost
                    User: root
                ssl_type:
              ssl_cipher:
             x509_issuer:
            x509_subject:
           max_questions: 0
             max_updates: 0
         max_connections: 0
    max_user_connections: 0
                  plugin: auth_socket
   authentication_string:
        password_expired: N
   password_last_changed: 2019-05-09 13:00:13
       password_lifetime: NULL
          account_locked: N
        Create_role_priv: Y
          Drop_role_priv: Y
  Password_reuse_history: NULL
     Password_reuse_time: NULL
Password_require_current: NULL
         User_attributes: NULL
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/mysql/mysql_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Jmainguy @Xyon @bmalynovytch @bmildren @michaelcoburn @oneiroi @tolland
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gstorme** [comment]
Not specific to the Percona distribution, same result on MySQL 8.0.16 from the Oracle repo.mysql.com

**Comment by gstorme** [comment]
When I change the plugin from auth_socket to mysql_native_password, the module works as expected.  
https://github.com/ansible/ansible/issues/27179

```mysql
alter user 'root'@'localhost' identified with mysql_native_password by '';
```

```yaml
changed: [stretch] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "ca_cert": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": "root",
            "name": "root",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "priv": null,
            "sql_log_bin": true,
            "state": "present",
            "update_password": "always",
            "user": "root"
        }
    },
    "msg": "Password updated (new style)",
    "user": "root"
}
```
