### ISSUE TITLE
asa_command registered output garbled

### ISSUE THREAD

**Issue by ibarrere** [ansible/ansible#56282]
##### SUMMARY

Running the asa_command module and registering the output seems to inconsistently mangle the stdout/stdout_lines of its registered output. I've come across this a few times and I've usually been able to recover what I need through when statements and regex_replace, but the issue I'm working on now (extracting IPv6 addresses from ASAs) is tough using that approach.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

asa_command

##### ANSIBLE VERSION

```paste below
ansible 2.6.11 (detached HEAD 5e03754e8f) last updated 2018/12/27 09:29:26 (GMT -600)
  config file = /home/ibarrere/ansible/ansible.cfg
  configured module search path = [u'/home/ibarrere/ansible/library']
  ansible python module location = /opt/ansible/source/lib/ansible
  executable location = /opt/ansible/source/bin/ansible
  python version = 2.7.9 (default, Nov 18 2015, 13:07:23) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/ibarrere/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ibarrere/ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=10
CACHE_PLUGIN(/home/ibarrere/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ibarrere/ansible/ansible.cfg) = ./cache
CACHE_PLUGIN_TIMEOUT(/home/ibarrere/ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/ibarrere/ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/home/ibarrere/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ibarrere/ansible/ansible.cfg) = [u'/home/ibarrere/ansible/inventory/production']
DEFAULT_LOG_PATH(/home/ibarrere/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/home/ibarrere/ansible/ansible.cfg) = Ansible managed from {host}
DEFAULT_MODULE_PATH(/home/ibarrere/ansible/ansible.cfg) = [u'/home/ibarrere/ansible/library']
DEFAULT_POLL_INTERVAL(/home/ibarrere/ansible/ansible.cfg) = 7
DEFAULT_ROLES_PATH(/home/ibarrere/ansible/ansible.cfg) = [u'/home/ibarrere/ansible/roles']
DEFAULT_TIMEOUT(/home/ibarrere/ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/home/ibarrere/ansible/ansible.cfg) = /home/ibarrere/ansible/open_the_vault.sh
DISPLAY_SKIPPED_HOSTS(/home/ibarrere/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ibarrere/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/ibarrere/ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/ibarrere/ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/ibarrere/ansible/ansible.cfg) = 100
RETRY_FILES_SAVE_PATH(/home/ibarrere/ansible/ansible.cfg) = /home/ibarrere/.ansible-retry
```

##### OS / ENVIRONMENT

CentOS release 6.10 (Final)
ASA 9.8(3)18

##### STEPS TO REPRODUCE

```yaml
   - name: get configured interfaces
      asa_command:
        commands:
          - show interface ip brief | grep CONFIG up
      register: asa_interfaces_pre

    - set_fact:
        asa_interfaces: "{{ asa_interfaces_pre.stdout_lines.0 | map('regex_replace', ' .*$') | list }}"

   - name: get v6 addresses
      asa_command:
        commands:
          - show run interface {{ item }} | grep ipv6 address
      loop: "{{ asa_interfaces }}"
      register: asa_v6_ips

    - debug:
        var: asa_v6_ips.results
```

Fwiw, the asa_interfaces list looks like this:

``` 
[      
        "GigabitEthernet0/0.6",
        "GigabitEthernet0/0.15",
        "GigabitEthernet0/0.61",
        "GigabitEthernet0/0.132",
        "GigabitEthernet0/0.110",
        "GigabitEthernet0/0.384",
        "GigabitEthernet0/0.186",
        "GigabitEthernet0/0.319",
        "GigabitEthernet0/1",
        "GigabitEthernet0/3"
]
```

##### EXPECTED RESULTS

In some cases, stdout comes back as expected, like this:

```
                "ipv6 address 2001:db8:3000:201::1/64 standby 2001:db8:3000:201::2"
```

##### ACTUAL RESULTS

In other cases, mangled parts of the command itself are the only contents of stdout (1st line below), and in others still, mangled parts of the command are merged together with the expected output (2nd line below)

```paste below
"show run interface GigabitEthernet0/0.319 | grep ipv6 addresthernet0/0.319 | grep ipv6 address                         how run interface GigabitEthernet0/0.319 | grep ipv6 addre$"
"show run interface GigabitEthernet0/0.132 | grep ipv6 addresthernet0/0.132 | grep ipv6 address                         how run interface GigabitEthernet0/0.132 | grep ipv6 addre$\n ipv6 address 2001:db8:3000:5::1/64 standby 2001:db8:3000:5::2"
```
