### ISSUE TITLE
compare two register variables

### ISSUE THREAD

**Issue by pcleon** [ansible/ansible#56297]
could i  compare two register variables in ansible-playbook?

```
tasks:
  - name: step 1
    shell: hostname
    register: h1
    delegate_to: host_1

  - name: step 2
    shell: hostname
    register: h2
    delegate_to: host_2

  - name: compare vars
    fail: msg="h1 not equal h2"
    when: "{{ h1.stdout }} != {{ h2.stdout }}"
```
i want to make sure h1 equal h2 then continue, but it's not work
