### ISSUE TITLE
VMware: Cannot mount datastore on host :  list index out of range 

### ISSUE THREAD

**Issue by ketank1000** [ansible/ansible#56290]
##### SUMMARY
I am trying to create multiple vmfs datastore using vmware_host_datastore module on single exsi host. So every time it fails for first datastore and passes for other

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_host_datastore

##### ANSIBLE VERSION
2.7.5

##### OS / ENVIRONMENT
RHEL7.4

##### STEPS TO REPRODUCE

```yaml
# Creates vmfs datastore
- name: Mount VMFS datastores to ESXi
  vmware_host_datastore:
    hostname: "{{ esx_host }}"
    username: "root"
    password: "xyz"
    datacenter_name: "{{ datacenter_name }}"
    datastore_name: "{{ datastore_name }}"
    datastore_type: "vmfs"
    vmfs_device_name: "{{ naa_id }}"
    vmfs_version: 6
    validate_certs: no
    esxi_hostname: "{{ esx_host.split('.')[0] }}"
    state: present
  delegate_to: localhost

My ini file

[hosts]
nbs-pyrx256-11-24  name=nbs-pyrx256-11-24 os=ESX6.7-x86_64 ansible_connection=ssh ansible_user=root ansible_password=pass gateway=10.141.8.1 

[vmware_vms]
vmware_vm1 vm_name=nbsvm-rhel6U9 template=rhel6U9 esx_host=nbs-pyrx256-11-24 mac_address=00:50:56:90:7e:22 
vmware_vm2 vm_name=nbsvm-sles12sp3 template=sles12sp3 esx_host=nbs-pyrx256-11-24 mac_address=00:50:56:90:18:c7 
vmware_vm3 vm_name=nbsvm-win2016 template=win2016 esx_host=nbs-pyrx256-11-24 mac_address=00:50:56:90:58:33 

```

##### EXPECTED RESULTS
So the expection is to have all datastore store should be created

##### ACTUAL RESULTS
It always fails for first one. even if i change the no. of datastores to be created

```paste below
The full traceback is:
  File "/tmp/ansible_vmware_host_datastore_payload_b_nikwp_/__main__.py", line 239, in mount_vmfs_datastore_host
    vmfs_ds_options[0].spec.vmfs.volumeName = self.datastore_name

fatal: [vmware_vm1 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter_name": "naa.600a098038303472585d4c4b38325369_nbsvm-rhel6U9",
            "datastore_name": "naa.600a098038303472585d4c4b38325369_nbsvm-rhel6U9",
            "datastore_type": "vmfs",
            "esxi_hostname": "nbs-pyrx256-11-24",
            "hostname": "nbs-pyrx256-11-24",
            "nfs_path": null,
            "nfs_ro": false,
            "nfs_server": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "root",
            "validate_certs": false,
            "vmfs_device_name": "naa.600a098038303472585d4c4b38325369",
            "vmfs_version": 6
        }
    },
    "msg": "Cannot mount datastore naa.600a098038303472585d4c4b38325369_nbsvm-rhel6U9 on host nbs-pyrx256-11-24 : list index out of range"
}
ok: [vmware_vm2 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter_name": "naa.600a098038303472745d4c4b38326931_nbsvm-sles12sp3",
            "datastore_name": "naa.600a098038303472745d4c4b38326931_nbsvm-sles12sp3",
            "datastore_type": "vmfs",
            "esxi_hostname": "nbs-pyrx256-11-24",
            "hostname": "nbs-pyrx256-11-24",
            "nfs_path": null,
            "nfs_ro": false,
            "nfs_server": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "root",
            "validate_certs": false,
            "vmfs_device_name": "naa.600a098038303472745d4c4b38326931",
            "vmfs_version": 6
        }
    }
}
ok: [vmware_vm3 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter_name": "naa.600a0980383034724e3f4c4b3832776d_nbsvm-win2016",
            "datastore_name": "naa.600a0980383034724e3f4c4b3832776d_nbsvm-win2016",
            "datastore_type": "vmfs",
            "esxi_hostname": "nbs-pyrx256-11-24",
            "hostname": "nbs-pyrx256-11-24",
            "nfs_path": null,
            "nfs_ro": false,
            "nfs_server": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "root",
            "validate_certs": false,
            "vmfs_device_name": "naa.600a0980383034724e3f4c4b3832776d",
            "vmfs_version": 6
        }
    }
}


```
