### ISSUE TITLE
Assemble module ordering enhancement

### ISSUE THREAD

**Issue by rmbleeker** [ansible/ansible#56304]
##### SUMMARY
I require a way to dictate the order in which the `assemble` module concatenates files. This enhancement was suggested earlier in #19442 but the accompanying pull request was never accepted.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
assemble

##### ADDITIONAL INFORMATION
When creating a certificate or CRL chain from a bunch of PEM formatted certificate or CRL files, they need to be in a specific order. I realize the `assemble` module was not originally created for this purpose, but I can't find another way of doing what I want short of using `cat` with the `shell` module.

```
- name: download certificates
  get_url:
    url: "{{ item }}"
    dest: /tmp/crls
  loop: "{{ list_of_urls }}"

- name: assemble, validate and replace CRL chain
  assemble:
    src: /tmp/crls
    order: "{{ list_of_urls | urlsplit('path') | basename }}"
    dest: /etc/pki/CA/crl
    validate: "/usr/bin/openssl crl -noout -inform PEM -in %s -CAfile {{ ca_chain }}"
```

The resulting CRL chain can then be used in a HAproxy configuration for example.

_PS.: If someone knows a far superior way to accomplish this please let me know. I am by no means an expert when it comes to certificates and CRLs, I'm just trying to do this in Ansible for a client who is currently doing this with a bash script._
