### ISSUE TITLE
gitlab_group: parent value is not converted to gitlab format

### ISSUE THREAD

**Issue by rrey** [ansible/ansible#56303]
##### SUMMARY

I hesitated between bug and feature request.
In the provided code bellow, I create a group named "La Factory" which contains a space char which will be replaced by an underscore by Gilab and be retrievable through the path/id "La_Factory".

The module doc specifies that the id or path should be provided, so my issue could be considered as a bad usage but I feel like the module should accept a string a convert it to match the convertion performed by Gitlab.

Without this behaviour, I would need to create the main group, use a lookup to retrieve it and find its id/path and then use this id/path to create the subgroups. That would be a pain.

I know I could avoid spaces in the name, but that's not my point :)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gitlab_group.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.0rc2
  config file = /home/remirey/dev/fnac/gcp-tools/ansible/ansible.cfg
  configured module search path = ['/home/remirey/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/remirey/.virtualenvs/gcp-tools/lib/python3.6/site-packages/ansible
  executable location = /home/remirey/.virtualenvs/gcp-tools/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = -F ssh_config
DEFAULT_REMOTE_USER(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = ['/home/remirey/dev/gcp-tools/ansible/roles-external', '/home/remirey/dev/gcp-tools/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = /home/remirey/dev/gcp-tools/ansible/ansible_vault_password
HOST_KEY_CHECKING(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/remirey/dev/gcp-tools/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
- name: Create Gitlab groups
  gitlab_group:
    server_url: "{{ gitlab_url }}"
    api_token: "{{ gitlab_access_token }}"
    name: "{{ item.name }}"
    state: present
    parent: "{{ item.parent | default(omit)}}"
  loop: "{{ gitlab_groups }}"
```
with the following `gitlab_groups` value:
```
gitlab_groups:
  - name: "La Factory"
    visibility: "internal"
  - name: "CT-CloudAndDevops"
    parent: "La Factory"
    visibility: "internal"
```

##### EXPECTED RESULTS

The module retrieves the parent group based on the provided `parent` value and provide its id/path in the creation query.

##### ACTUAL RESULTS

```paste below
failed: [tools-gitlab-dev] (item={'name': 'CT-CloudAndDevops', 'parent': 'La Factory', 'visibility': 'internal'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "CT-CloudAndDevops", "parent": "La Factory", "visibility": "internal"}, "msg": "Failed create Gitlab group: Parent group doesn't exists"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/source_control/gitlab_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Lunik @Shaps @dj-wasabi @jlozadad @marwatk @waheedi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Lunik** [comment]
Hi,
When you create the parent group, you can register the return of the module.
Then access the `group` attribute and you should have the return of the Gitlab API.
You can get the parent id/path from there.

Example : 
```yaml
- name: Create Gitlab parent groups
  gitlab_group:
    server_url: "https://gitlab.com"
    api_token: "qwertyuiop"
    name: "My parent group"
    state: present
  register: result_parent_group

- name: Create Gitlab child groups
  gitlab_group:
    server_url: "https://gitlab.com"
    api_token: "qwertyuiop"
    name: "My child group"
    state: present
    parent: "{{ result_parent_group.group.id }}
```

**Comment by rrey** [comment]
Hi @Lunik, indeed it is a solution but it forces us to process the parent groups in different tasks.
The code would have to change each time I add a level in the groups hierarchy.

**Comment by Lunik** [comment]
Well, I guess you could force your groups `path` value

```yaml
gitlab_groups:
  - name: "La Factory"
    visibility: "internal"
    path: "la_factory"

  - name: "CT-CloudAndDevops"
    parent: "la_factory"
    visibility: "internal"
```
