### ISSUE TITLE
Can't asynchronously wait on restoring oVirt snapshot

### ISSUE THREAD

**Issue by pkubica** [ansible/ansible#56305]
##### SUMMARY

It is not possible to asynchronously wait to finish of restoring snapshot job. It will always fail on exceeded attempts.
Tested playbook with change "ovirt_vm: state=running" and it works as expected
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_snapshot

##### ANSIBLE VERSION

```paste below
ansible 2.8.0b1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

RHEL 7.6, RHV 4.3.3.6

##### STEPS TO REPRODUCE

run playbook inserted below (have already in pre_tasks

```yaml
  tasks:
    - ovirt_snapshot_facts:
        vm: "pkubica-ansible-engine"
        description: clean
        auth: "{{ ovirt_auth }}"

    - name: "Restore VM {{item.name}}"
      ovirt_snapshot:
        state: restore
        vm_name: "pkubica-ansible-engine"
        snapshot_id: "{{ ovirt_snapshots[0].id }}"
        wait: yes
        auth: "{{ovirt_auth}}"
      async: 30
      poll: 0
      register: restored_vm

    - set_fact:
        ovirt_worker_all_vms: "{{ ovirt_worker_all_vms | default([]) + [restored_vm] }}"

    - name: "Wait for VMs to be restored"
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: "{{ (30 * ovirt_worker_all_vms|length) + 1 }}"
      delay: "{{ 5 }}"
      with_items: "{{ ovirt_worker_all_vms }}"
```

##### EXPECTED RESULTS

when the module ovirt_snapshot ends restore of snapshot, value of job_result.finished should be 1

##### ACTUAL RESULTS

value job_result.finished is still 0, so it fails on exceeded attempts

```paste below
failed: [localhost] (item={'failed': False, u'finished': 0, u'results_file': u'/root/.ansible_async/945665307218.70977', u'ansible_job_id': u'945665307218.70977', u'started': 1, 'changed': True}) => {
    "ansible_job_id": "945665307218.70977", 
    "ansible_loop_var": "item", 
    "attempts": 31, 
    "changed": false, 
    "finished": 0, 
    "invocation": {
        "module_args": {
            "_async_dir": "/root/.ansible_async", 
            "jid": "945665307218.70977", 
            "mode": "status"
        }
    }, 
    "item": {
        "ansible_job_id": "945665307218.70977", 
        "changed": true, 
        "failed": false, 
        "finished": 0, 
        "results_file": "/root/.ansible_async/945665307218.70977", 
        "started": 1
    }, 
    "started": 1
}

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
