### ISSUE TITLE
nios_fixed_address remove network requirement

### ISSUE THREAD

**Issue by denngie** [ansible/ansible#56301]
##### SUMMARY

When using the API of Infoblox you can work with fixed addresses without entering the specific subnet. Consider the example below for when subnet is not easily available and requires additional tasks because of module requirement. The var ansible_net_all_ipv4_addresses is a list of all IP addresses on the switch
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nios_fixed_address
##### ADDITIONAL INFORMATION

```yaml
---

- name: IPAM verification
  hosts: cisco_switch
  gather_facts: false
  vars_files:
    - secrets.yml

  tasks:
    - name: Gather interface facts
      ios_facts:
        gather_subset:
          - interfaces
      when: ansible_network_os == "ios"

    - name: Document each IP as a reserved fixed address
      nios_fixed_address:
        ipaddr: "{{ item }}"
        mac: 00:00:00:00:00:00
        name: "{{ inventory_hostname_short }}"
        provider: "{{ provider }}"
        ipaddr: "{{ item }}"
      loop: "{{ ansible_net_all_ipv4_addresses }}"
      delegate_to: localhost

  - name: Register in Infoblox using API without subnet provided (working API example)
    uri:
      url: "https://{{ FQDN }}/wapi/v2.7/fixedaddress"
      method: POST
      user: "{{ username }}"
      password: "{{ password }}"
      body:
        ipv4addr: "{{ item }}"
        name: "{{ inventory_hostname_short }}"
        mac: 00:00:00:00:00:00
        network_view: default
      body_format: json
      status_code: 201,400
      validate_certs: false
    loop: "{{ ansible_net_all_ipv4_addresses }}"
    register: output
    changed_when: output.status == 201
    failed_when: output.status == 400

...
```
