### ISSUE TITLE
iam_role only detaches the first managed policy if multiple policies need to be detached

### ISSUE THREAD

**Issue by mhoroschun** [ansible/ansible#56329]
##### SUMMARY
iam_role only detaches the first managed policy if multiple policies need to be detached

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iam_role

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/matthew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 26 2019, 20:08:16) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
```

##### STEPS TO REPRODUCE

Create a role with several policies attached:
```yaml
- iam_role:
    name: "role1"
    managed_policies:
      - policy1
      - policy2
      - policy3
    purge_policies: yes
    state: present
```

Delete several policies:
```yaml
- iam_role:
    name: "role1"
    managed_policies:
      - policy1
    purge_policies: yes
    state: present
```

##### EXPECTED RESULTS

All of the absent policies should be removed from the IAM role.

##### ACTUAL RESULTS

Only one of the two policies (policy2 or policy3) is detached and the other remains.
