### ISSUE TITLE
Unexpected conditional behavior

### ISSUE THREAD

**Issue by ejez** [ansible/ansible#56323]
One moment: testing again...

**Comment by ejez** [comment]
I want to run the task only for one node in "group-2", thus the conditions:
```yaml
    - "'group-2' in group_names"
    - inventory_hostname == groups['group-2'][0]
```
But also only if "group-1" exists. If that group does not exist I don't want the task to run at all, thus the condition:
```yaml
    - "'group-1' in group_names"
```
When this condition is added, node-b gets discarded because it does not belong to group-1, which is not expected.

As of now, I am using a dirty workaround with added complications using delegate_to:
```yaml
  - when:
    - "'group-1' in group_names"
    - inventory_hostname in groups['group-1']
    delegate_to: "{{ groups['group-2'][0] }}"
    run_once: true
    debug:
      msg: "{{ hostvars[groups['group-2'][0]]['ansible_hostname'] }}"
```
