### ISSUE TITLE
stack delegated handlers

### ISSUE THREAD

**Issue by timurb** [ansible/ansible#5634]
When the handler is delegated to some host and several hosts kick that handler it is triggered several times instead of once.

Consider the generic example:

``` yaml
- hosts: all
  - tasks:
    - name: do some configuration stuff
      .....
      notify:
      - reload server
  - handlers:
    - name: reload server
      service: name=myservice state=restarted
      delegate_to: "{{ server_ip }}"
```

Here some processing is done on nodes and the central server (which connects|listens to these nodes) is reloaded afterwards. Now the reload will be triggered for each host with completed action "do some configuration stuff" but it is expected to be triggered only once for each `server_ip`.

I have not found in http://docs.ansible.com/playbooks_intro.html any params that could affect the behaviour.
