### ISSUE TITLE
ec2_asg adding MixedInstancesPolicy

### ISSUE THREAD

**Issue by wica128** [ansible/ansible#56385]
##### SUMMARY

AWS EC2 autoscaling , allows to specify MixedInstancesPolicy. So that you can use multiple instance type in a autoscaling group.

https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_MixedInstancesPolicy.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_asg

##### ADDITIONAL INFORMATION
It will allow to specify multiple instance types in a ASG.

For now, I have this in my role.

```yaml
- name: Create MixedInstancePolicy
  template:
    src: "MixedInstancesPolicy.json.j2"
    dest: "/tmp/aws-asg-{{ ec2_lt_name }}"
    mode: 0644

- name: update MixedInstancePolicy 
  shell: aws autoscaling update-auto-scaling-group --auto-scaling-group-name {{ customer }}-{{ env }}-{{ group }} --mixed-instances-policy file:///tmp/aws-asg-{{ ec2_lt_name }}
```
```json
{
	"LaunchTemplate": {
            "LaunchTemplateSpecification": {
                "LaunchTemplateName": "{{ ec2_lt_name }}",
                "Version": "1"
            },
            "Overrides": [
                {
                    "InstanceType": "m5d.large"
                },
                {
                    "InstanceType": "m5d.xlarge"
                },
                {
                    "InstanceType": "m5d.2xlarge"
                }
            ]
        },
	"InstancesDistribution": {
		"OnDemandBaseCapacity": 0,
		"OnDemandPercentageAboveBaseCapacity": 0,
		"SpotAllocationStrategy": "lowest-price",
		"SpotInstancePools": 2,
		"SpotMaxPrice": "0.6"

	}
}
```
