### ISSUE TITLE
state=directory and recursive=yes with symlink to the path throw an exception

### ISSUE THREAD

**Issue by theg4sh** [ansible/ansible#56397]
##### SUMMARY

Exception thrown on maximum recursion depth exceeded for directory with symlink to that directory.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module files

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /home/user/repos/demo/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_HASH_BEHAVIOUR(/home/user/repos/demo/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/user/repos/demo/ansible.cfg) = ['/home/user/repos/demo/hosts/all.yaml']
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```shell
ansible-playbook /tmp/demo-recurse.yml
```

```yaml
# /tmp/demo-recurse.yml
- hosts: localhost
  tasks:
    - name: mkdir demo-recurse
      file:
        state: "directory"
        path: "/tmp/demo-recurse"
        owner: "{{ lookup('env', 'USER') }}"
        recurse: yes
    - name: link demo-recurse-link
      file:
        state: "link"
        path: "/tmp/demo-recurse/linktothisdir"
        src: "/tmp/demo-recurse"
        owner: "{{ lookup('env', 'USER') }}"
    - name: repeat demo-recurse
      file:
        state: "directory"
        path: "/tmp/demo-recurse"
        owner: "{{ lookup('env', 'USER') }}"
        recurse: yes
```

##### EXPECTED RESULTS

Process link once per run.

##### ACTUAL RESULTS

Python exception thrown.
