### ISSUE TITLE
acl: set muptiple entries at once

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#56412]
##### SUMMARY

Add to acl module ability to set multiple ACLs in one time. `setfacl` command has this ability:

`setfacl -m u:foo:r-x -m u:bar:rwx -m g:baz:--- /some/path`

This will work much faster in cases when you need to set multiple ACLs on directory. Now you should do it with loops and that works slow.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

acl

##### ADDITIONAL INFORMATION

Example:

```yaml
- name: set acl with multiple entries at once
  acl:
    path: /some/path
    state: present
    recursive: yes
    acls:
      - entity: foo
        etype: user
        permissions: r-x
      - entity: bar
        etype: user
        permissions: rwx
      - entity: baz
        etype: group
        permissions: ---
```
