### ISSUE TITLE
gcp_container_cluster does not support cluster_version, min_nodes, max_nodes, labels (cluster labels)

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#56426]
##### SUMMARY
gcp_container_cluster does not support `cluster_version`, `min_nodes`, `max_nodes`, `labels` (cluster labels)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_container_cluster

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eanderson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /home/eanderson/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

```yaml
- name: create a cluster
  gcp_container_cluster:
      name: "{{ gke_cluster_name }}"
      initial_node_count: 1
      min_nodes: 1
      max_nodes: 300
      labels:
        key1: value1
      cluster_version: 1.12.7-gke.10
      node_config:
        machine_type: n1-standard-4
        disk_size_gb: 500
      location: "{{ gke_cluster_location }}"
      project: "{{ gke_cluster_project }}"
      auth_kind: serviceaccount
      service_account_file: "/tmp/auth.pem"
      state: present
```

##### EXPECTED RESULTS

Being able to specify those values for the cluster creation

##### ACTUAL RESULTS

```paste below

```
