### ISSUE TITLE
regex_replace does not work with the "file" lookup

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible#56446]
##### SUMMARY
The `regex_replace` filter does not work when used within a file lookup

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

regex_replace filter
##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = None
  configured module search path = [u'/home/achenamp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/achenamp/.virtualenvs/myvenv/lib/python2.7/site-packages/ansible
  executable location = /home/achenamp/.virtualenvs/myvenv/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```
FYI: Also tried with 2.8.0

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 7.4

##### STEPS TO REPRODUCE

```yaml
---
- name: REGEX REPLACE WITH LOOKUP
  hosts: localhost
  gather_facts: no

  tasks:

    - name: debug
      debug:
        msg: "{{ item | basename | regex_replace('yml', 'raw') }}"
      with_fileglob: "./bug_yml/*"


    - name: READ CONTENTS
      set_fact:
        raw_data: "{{ lookup( 'file', './bug_raw/{{ item | basename | regex_replace('yml', 'raw') }}' ) }}"
      with_fileglob: "./bug_yml/*"


    - debug: var=raw_data

```

Where the dir structure looks as follows:

```
(myvenv) ~/P/playbook_sandbox ❯❯❯ ls bug_raw
ifconfig.raw
(myvenv) ~/P/playbook_sandbox ❯❯❯ ls bug_yml
ifconfig.yml
(myvenv) ~/P/playbook_sandbox ❯❯❯ 

```

##### EXPECTED RESULTS

The contents of the `ifconfig.raw` file should be printed

##### ACTUAL RESULTS

```paste below
PLAY [REGEX REPLACE WITH LOOKUP] **************************************************************************************************************************
META: ran handlers

TASK [debug] **********************************************************************************************************************************************task path: /home/achenamp/Projects/playbook_sandbox/bug_test.yml:8
looking for "./bug_yml" at "/home/achenamp/Projects/playbook_sandbox/files/./bug_yml"
looking for "./bug_yml" at "/home/achenamp/Projects/playbook_sandbox/./bug_yml"
ok: [localhost] => (item=/home/achenamp/Projects/playbook_sandbox/./bug_yml/ifconfig.yml) => {
    "msg": "ifconfig.raw"
}

TASK [READ CONTENTS] **************************************************************************************************************************************
task path: /home/achenamp/Projects/playbook_sandbox/bug_test.yml:14
looking for "./bug_yml" at "/home/achenamp/Projects/playbook_sandbox/files/./bug_yml"
looking for "./bug_yml" at "/home/achenamp/Projects/playbook_sandbox/./bug_yml"
fatal: [localhost]: FAILED! => {
    "msg": "template error while templating string: expected token ',', got 'yml'. String: {{ lookup( 'file', './bug_raw/{{ item | basename | regex_replace
('yml', 'raw') }}' ) }}"
}

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```
