### ISSUE TITLE
vmware_guest: Clone from template failed 

### ISSUE THREAD

**Issue by f-hrtmnn** [ansible/ansible#56468]
##### SUMMARY

I cannot clone any vm from a vmware template
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest module
##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/harfae3/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
nothing changed
```

##### OS / ENVIRONMENT

esxi 6.0
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
python2-pyvmomi-6.7.1-3.el7.noarch

##### STEPS TO REPRODUCE

```
---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "vcenter_password"
      prompt: "enter password"
      private: yes
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "1.2.3.4"
      username: "administrator@vsphere.local"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: ansibleclone
      template: "GoldenImage_RedHat"
      datacenter: "DC1"
      folder: /Test/Felix/
      state: present
      cluster: "cluster1"
      wait_for_ip_address: no
```

##### EXPECTED RESULTS
vmware got cloned

##### ACTUAL RESULTS
```
"msg": "Failed to create a virtual machine : Unable to access the virtual machine configuration: Unable to access file [SAN_CLU010_LUN02] GoldenImage_RedHat/GoldenImage_RedHat.vmtx"
```
