### ISSUE TITLE
VMware: vmware_guest.py ignores esxi_hostname when creating a new vm

### ISSUE THREAD

**Issue by flloreda** [ansible/ansible#56467]
##### SUMMARY
vmware_guest.py ignores esxi_hostname when creating a new vm
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### OS / ENVIRONMENT
Container running RHEL 7.6

##### STEPS TO REPRODUCE

Executing the following Playbook ignores the esxi_hostname , creating the vm on a different esxi 
```yaml
- name: VMware test
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create the VMs
      vmware_guest:
        hostname: "vsphere.lab.whatever.com"
        port: "443"
        username: "lab@vsphere.local"
        password: "yourpass"
        cluster: "Lab_CPD_Old"
        datacenter: "Laboratorio_CPD_Old"
        validate_certs: False
        name: "sn8845.test"
        folder: "8845"
        guest_id: 'rhel6_64Guest'
        disk:
          - size_gb: 300 # in GB
            type: thin # Valid values: "thin" or "eagerzeroedthick"
            autoselect_datastore: True
          - size_gb: 300 # in GB
            type: thin # Valid values: "thin" or "eagerzeroedthick"
            autoselect_datastore: True 
        hardware: 
          num_cpus: 8
          memory_mb: 8192 # in MB
          version: 8.0
        networks:
          - name: "network"
            device_type: "vmxnet3"
            network: "10.69.26.0"
            ip: "10.69.26.9"
            gateway: "10.69.26.1"
            netmask: "255.255.255.128"
            vmnet: "network"
            dns:
              itg: "172.20.2.11"
              pre: "172.28.62.1"
              pro: "172.20.2.11"
        state: present
```

```
ansible-playbook -vvv test_vmware.yml 
ansible-playbook 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: test_vmware.yml ********************************************************************************************************************************************************************
1 plays in test_vmware.yml

PLAY [VMware test] ***************************************************************************************************************************************************************************
META: ran handlers

TASK [Create the VMs] ************************************************************************************************************************************************************************
task path: /root/test_vmware.yml:9
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656 `" && echo ansible-tmp-1557932519.57-247379686399656="` echo /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-785MfLEP/tmpQG607u TO /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656/AnsiballZ_vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656/ /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1557932519.57-247379686399656/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "instance": {
        "annotation": "", 
        "current_snapshot": null, 
        "customvalues": {}, 
        "guest_consolidation_needed": false, 
        "guest_question": null, 
        "guest_tools_status": "guestToolsNotRunning", 
        "guest_tools_version": "0", 
        "hw_cores_per_socket": 1, 
        "hw_datastores": [
            "10.200.1.105_datastore1"
        ], 
        "hw_esxi_host": "10.200.1.105", 
        "hw_eth0": {
            "addresstype": "assigned", 
            "ipaddresses": null, 
            "label": "Network adapter 1", 
            "macaddress": "00:50:56:ab:c7:e3", 
            "macaddress_dash": "00-50-56-ab-c7-e3", 
            "portgroup_key": null, 
            "portgroup_portkey": null, 
            "summary": "8845-srv"
        }, 
        "hw_files": [
            "[10.200.1.105_datastore1] sn8845.test/sn8845.test.vmx", 
            "[10.200.1.105_datastore1] sn8845.test/sn8845.test.vmxf", 
            "[10.200.1.105_datastore1] sn8845.test/sn8845.test.vmsd", 
            "[10.200.1.105_datastore1] sn8845.test/sn8845.test.vmdk", 
            "[10.200.1.105_datastore1] sn8845.test/sn8845.test_1.vmdk"
        ], 
        "hw_folder": "/Laboratorio_CPD_Old/vm/8845", 
        "hw_guest_full_name": null, 
        "hw_guest_ha_state": null, 
        "hw_guest_id": null, 
        "hw_interfaces": [
            "eth0"
        ], 
        "hw_is_template": false, 
        "hw_memtotal_mb": 8192, 
        "hw_name": "sn8845.test", 
        "hw_power_status": "poweredOff", 
        "hw_processor_count": 8, 
        "hw_product_uuid": "422bd18b-ec6d-17c9-4977-ec127f002560", 
        "hw_version": "vmx-08", 
        "instance_uuid": "502b350c-8f17-93a2-8230-2d77829a47df", 
        "ipv4": null, 
        "ipv6": null, 
        "module_hw": true, 
        "snapshots": []
    }, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": "Lab_CPD_Old", 
            "customization": {}, 
            "customization_spec": null, 
            "customvalues": [], 
            "datacenter": "Laboratorio_CPD_Old", 
            "datastore": null, 
            "disk": [
                {
                    "autoselect_datastore": true, 
                    "size_gb": 300, 
                    "type": "thin"
                }, 
                {
                    "autoselect_datastore": true, 
                    "size_gb": 300, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "8845", 
            "force": false, 
            "guest_id": "rhel6_64Guest", 
            "hardware": {
                "memory_mb": 8192, 
                "num_cpus": 8, 
                "version": 8.0
            }, 
            "hostname": "vclabcpd.lab.whatever.es", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "sn8845.test", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "dns": {
                        "itg": "172.20.2.11", 
                        "pre": "172.28.62.1", 
                        "pro": "172.20.2.11"
                    }, 
                    "gateway": "10.69.26.1", 
                    "ip": "10.69.26.9", 
                    "name": "8845-srv", 
                    "netmask": "255.255.255.128", 
                    "network": "10.69.26.0", 
                    "type": "static", 
                    "vmnet": "8845-srv"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "present", 
            "state_change_timeout": 0, 
            "template": null, 
            "username": "lab@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_ip_address": false
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0

```

##### EXPECTED RESULTS

To create the new vm on the specified esxi 

##### ACTUAL RESULTS

The vm is created in different esxi system

```

```
