### ISSUE TITLE
Bug in na_ontap_snapshot_policy module

### ISSUE THREAD

**Issue by matthgyver** [ansible/ansible#56472]
##### SUMMARY

I'd like to create a policy with different schedule inside like this by exemple : 
* my policy
  * schedule = daily / number of copy = 7
  * schedule = weekly / number of copy = 4
  * schedule = monthly / number of copy = 2

Only the first schedule is take.
Moreover, edit a policy does'nt work

Another question : is it possible to set snapmirror label ?
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

na_ontap_snapshot_policy
##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  8 2019, 18:17:52) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

Custom Docker Container

##### STEPS TO REPRODUCE

```yaml
  - name: Add 2 monthly snapshot to policy
    na_ontap_snapshot_policy:
      state: present
      name: myPolicy
      schedule: monthly
      count: 2
      enabled: yes
      <<: *authParams

  - name: Add 4 weekly snapshot to policy
    na_ontap_snapshot_policy:
      state: present
      name: myPolicy
      schedule: weekly
      count: 4
      enabled: yes
      <<: *authParams

  - name: Add 7 daily snapshot to policy
    na_ontap_snapshot_policy:
      state: present
      name: myPolicy
      schedule: daily
      count: 7
      enabled: yes
      <<: *authParams
```

##### EXPECTED RESULTS

In OnCommand System Manager, see a policy nammed "myPolicy" with 3 entry.

##### ACTUAL RESULTS

I see my policy "myPolicy" with only one entry (the first declared in the playbook)
