### ISSUE TITLE
win_uri, win_get_url lacks default User-Agent header

### ISSUE THREAD

**Issue by dentarg** [ansible/ansible#56470]
##### SUMMARY

The `win_uri`, `win_get_url` modules both lack a default User-Agent header. Certain websites block requests when they lack the User-Agent header (one example is https://api.github.com/). This is confusing and hard to find out.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`win_uri`
`win_get_url`

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /Users/dentarg/twingly/ansible/ansible.cfg
  configured module search path = [u'/Users/dentarg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dentarg/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/dentarg/Library/Python/2.7/bin/ansible
  python version = 2.7.16 (default, Mar  4 2019, 09:01:38) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### OS / ENVIRONMENT

Windows 2016

##### STEPS TO REPRODUCE / ACTUAL RESULTS

```yaml
ansible vagrant-win2016 -m win_uri -a 'url=https://api.github.com/'
vagrant-win2016 | FAILED! => {
    "cache_control": "no-cache",
    "changed": false,
    "character_set": "ISO-8859-1",
    "connection": "close",
    "content_encoding": "",
    "content_length": -1,
    "content_type": "text/html",
    "cookies": [],
    "headers": [
        "Connection",
        "Cache-Control",
        "Content-Type"
    ],
    "is_from_cache": false,
    "is_mutually_authenticated": false,
    "last_modified": "2019-05-15T15:23:48.6539544+00:00",
    "method": "GET",
    "msg": "Status code of request '403' is not in list of valid status codes 200 : 'Forbidden'.",
    "protocol_version": {
        "Build": -1,
        "Major": 1,
        "MajorRevision": -1,
        "Minor": 0,
        "MinorRevision": -1,
        "Revision": -1
    },
    "response_uri": "https://api.github.com/",
    "server": "",
    "status_code": 403,
    "status_description": "Forbidden",
    "supports_headers": true,
    "url": "https://api.github.com/"
}
```
```yaml
ansible vagrant-win2016 -m win_get_url -a 'dest=C:\Temp url=https://api.github.com/'
vagrant-win2016 | FAILED! => {
    "changed": false,
    "dest": "C:\\Temp",
    "msg": "Error downloading 'https://api.github.com/' to 'C:\\Temp': The remote server returned an error: (403) Forbidden.",
    "status_code": 403,
    "url": "https://api.github.com/",
    "win_get_url": {
        "dest": "C:\\Temp",
        "url": "https://api.github.com/"
    }
}
```

##### EXPECTED RESULTS

It works when you set the User-Agent header.

```yaml
ansible vagrant-win2016 -m win_get_url -a 'dest=C:\Temp url=https://api.github.com/ headers={{ headers }}' -e '{ "headers": { "user-agent": "Ansible" }}'
vagrant-win2016 | CHANGED => {
    "changed": true,
    "dest": "C:\\Temp",
    "msg": "OK",
    "status_code": 200,
    "url": "https://api.github.com/",
    "win_get_url": {
        "dest": "C:\\Temp",
        "url": "https://api.github.com/"
    }
}
```
```yaml
ansible vagrant-win2016 -m win_uri -a 'url=https://api.github.com/ headers={{ headers }}' -e '{ "headers": { "user-agent": "Ansible" }}'
vagrant-win2016 | SUCCESS => {
    "access_control_allow_origin": "*",
    "access_control_expose_headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type",
    "cache_control": "public, max-age=60, s-maxage=60",
    "changed": false,
    "character_set": "utf-8",
    "content_encoding": "",
    "content_length": "2039",
    "content_security_policy": "default-src 'none'",
    "content_type": "application/json; charset=utf-8",
    "cookies": [],
    "date": "Wed, 15 May 2019 15:26:16 GMT",
    "e_tag": "\"71c20e818259a283a4a0ff002435bd03\"",
    "headers": [
        "Status",
        "X-RateLimit-Limit",
        "X-RateLimit-Remaining",
        "X-RateLimit-Reset",
        "Vary",
        "X-GitHub-Media-Type",
        "Access-Control-Expose-Headers",
        "Access-Control-Allow-Origin",
        "Strict-Transport-Security",
        "X-Frame-Options",
        "X-Content-Type-Options",
        "X-XSS-Protection",
        "Referrer-Policy",
        "Content-Security-Policy",
        "X-GitHub-Request-Id",
        "Content-Length",
        "Cache-Control",
        "Content-Type",
        "Date",
        "ETag",
        "Server"
    ],
    "is_from_cache": false,
    "is_mutually_authenticated": false,
    "last_modified": "2019-05-15T15:26:16.6269587+00:00",
    "method": "GET",
    "protocol_version": {
        "Build": -1,
        "Major": 1,
        "MajorRevision": -1,
        "Minor": 1,
        "MinorRevision": -1,
        "Revision": -1
    },
    "referrer_policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    "response_uri": "https://api.github.com/",
    "server": "GitHub.com",
    "status": "200 OK",
    "status_code": 200,
    "status_description": "OK",
    "strict_transport_security": "max-age=31536000; includeSubdomains; preload",
    "supports_headers": true,
    "url": "https://api.github.com/",
    "vary": "Accept",
    "x_content_type_options": "nosniff",
    "x_frame_options": "deny",
    "x_git_hub_media_type": "github.v3; format=json",
    "x_git_hub_request_id": "E3E6:3970:576F48:AF8FED:5CDC2F98",
    "x_rate_limit_limit": "60",
    "x_rate_limit_remaining": "58",
    "x_rate_limit_reset": "1557937576",
    "xxss_protection": "1; mode=block"
}
```
