### ISSUE TITLE
group module: "local:yes" ignores existing GIDs

### ISSUE THREAD

**Issue by m3adow** [ansible/ansible#56481]
##### SUMMARY
When using `local: yes` in the **group** module, GIDs  are always forced, ignoring existing GIDs and therefore allowing duplicate GIDs. This also happens no matter the value of the recently added `non_unique`. The reason for this can be found in the help output of the used `lgroupadd`:

<code>-g, --gid=NUM         gid to <b>force</b> for new group</code>

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
group

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /home/wiestil/src/ansible_stuff/test_playbooks/ansible.cfg
  configured module search path = ['/home/wiestil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.5/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.5.1 (default, Sep 15 2016, 08:33:29) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/wiestil/src/ansible_stuff/test_playbooks/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/wiestil/src/ansible_stuff/test_playbooks/ansible.cfg) = -o ForwardAgent=yes
DEFAULT_FORKS(/home/wiestil/src/ansible_stuff/test_playbooks/ansible.cfg) = 25
RETRY_FILES_ENABLED(/home/wiestil/src/ansible_stuff/test_playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux 6.10 & 7.6

##### STEPS TO REPRODUCE
This problem will occur every time `local: yes` is used:

```yaml
    - name: Create correct groups
      group:
        name: "{{ item }}"
        gid: 1337
        local: yes
      loop:
        - user1
        - user2
    - name: Output GID 1337
      command: "grep 1337 /etc/group"
```

##### EXPECTED RESULTS
I'd expect Ansible to fail when the GID already exists, similarly to the behaviour without `local: yes`

##### ACTUAL RESULTS
Both users will be created with the identical GID.
