### ISSUE TITLE
lvg: Behavioral change in volume extend between versions 2.7 and 2.8

### ISSUE THREAD

**Issue by sac** [ansible/ansible#56501]
##### SUMMARY

In version 2.7 volume extend would work if the existing volume group was provided and the disk to extend was provided. For example:

- name: Extend volume group
  lvg:
     state: present
     vg: foo_vg                # Existing volume group
     pvs: "/dev/sdc"         # disk to be extended. Which was not part of foo_vg
     pv_options: "--dataalignment 256K"

Since /dev/sdc was not part of vg it would be extended than deleted.

Now since version 2.8 the behavior has changed, where all the existing pvs which which were part of volume group has to be provided. Like:
```
- name: Extend volume group
  lvg:
     state: present
     vg: foo_vg
     pvs: "/dev/sdb,/dev/sdc"
     pv_options: "--dataalignment 256K"
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module: lvg

##### ANSIBLE VERSION

```
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]

```

##### CONFIGURATION

No extra configuration is done.

##### OS / ENVIRONMENT

Fedora release 28 (Generic)

##### STEPS TO REPRODUCE

Create a volume with a disk say /dev/sdb and then try to extend by adding /dev/sdc and
executing lvol module.

```
- name: Extend volume group
  lvg:
     state: present
     vg: foo_vg
     pvs: "/dev/sdc"
     pv_options: "--dataalignment 256K"

```

##### EXPECTED RESULTS

When run with 2.8 it should have worked like it did with 2.7.

##### ACTUAL RESULTS

When run with 2.8 the following error is seen.

```
(item={u'vgname': u'vg_vdc', u'cachethinpoolname': u'thinpool_vg_vdc', u'cachelvname': u'cachelv_thinpool_vg_vdc', u'cachedisk': u'/dev/vdd', u'cachemetalvname': u'cache_thinpool_vg_vdc', u'cachemode': u'writethrough', u'cachemetalvsize': u'2G', u'cachelvsize': u'50G'}) => {"changed": false, "err": "  Physical volume \"/dev/vdc\" still in use\n", "item": {"cachedisk": "/dev/vdd", "cachelvname": "cachelv_thinpool_vg_vdc", "cachelvsize": "50G", "cachemetalvname": "cache_thinpool_vg_vdc", "cachemetalvsize": "2G", "cachemode": "writethrough", "cachethinpoolname": "thinpool_vg_vdc", "vgname": "vg_vdc"}, "msg": "Unable to reduce vg_vdc by /dev/vdc.", "rc": 5}

```

However changing the playbook to:

```
- name: Extend volume group
  lvg:
     state: present
     vg: foo_vg
     pvs: "/dev/sdb,/dev/sdc"
     pv_options: "--dataalignment 256K"
```
Will work without error.

We have to document this behavioral change.
