### ISSUE TITLE
Region eu-west-2 does not seem to be available for aws module

### ISSUE THREAD

**Issue by JPSerras** [ansible/ansible#56536]
##### SUMMARY
OS: Ubuntu 18.04
Ansible: 2.7
boto: 2.49.0
boto3: 1.9.149
botocore: 1.12.149

Using Ansible Python Module to execute the playbooks.
Could not able to create instances via Ansible on London (eu-west-2) Region even though the module has that region.
```
>>>import boto.ec2
>>>boto.ec2.regions()
[RegionInfo:ap-south-1, RegionInfo:ca-central-1, RegionInfo:eu-west-2, RegionInfo:us-east-2, RegionInfo:us-west-1, RegionInfo:ap-northeast-2, RegionInfo:cn-north-1, RegionInfo:ap-southeast-2, RegionInfo:sa-east-1, RegionInfo:eu-west-1, RegionInfo:eu-central-1, RegionInfo:us-west-2, RegionInfo:us-gov-west-1, RegionInfo:us-east-1, RegionInfo:ap-southeast-1, RegionInfo:ap-northeast-1]
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
From boto: 2.49.0
- boto.vpc
- boto.ec2

##### ANSIBLE VERSION
Ansible: 2.7

##### CONFIGURATION
```
- hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  tasks:
  - set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - ec2_vpc_igw:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      vpc_id: "{{ wps_aws_vpc.vpc.id }}"
      region: "{{ region }}"
      state: present
    register: igw
```

##### ACTUAL RESULTS
```
TASK [ec2_vpc_igw] *************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Region eu-west-2 does not seem to be available for aws module boto.vpc. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"}
	to retry, use: --limit @/home/PycharmProjects/ansible/playbooks/aws/create_aws_instance.retry
```

*Had similiar results previously with boto.ec2 module
