### ISSUE TITLE
cloudfront_distribution should allow custom s3_origin_config

### ISSUE THREAD

**Issue by saxonww** [ansible/ansible#56553]
##### SUMMARY

Teach the `cloudfront_distribution` module to accept a declared `origins[].s3_origin_config` instead of generating its own.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cloudfront_distribution

##### ADDITIONAL INFORMATION

The `cloudfront_distribution` module offers an `origins[].s3_origin_access_identity_enabled` flag, which, if set and the `origins[].domain_name` property matches the hardcoded s3 domain, will generate a cloudfront origin access identity and include it in a generated s3_origin_config statement.

Ansible also offers a `cloudfront_origin_access_identity` module to generate an identity for use with other modules, e.g. with `s3_bucket` and a bucket policy template. It would be good if `cloudfront_distribution` let users define their own `s3_origin_config` with an OAI generated externally by this module as well. 

The primary use case for this would be websites stored in S3 and accessed via CloudFront  using a CloudFront Origin Access Identity (see [here][0] and [here][1], but note the latter doesn't work in Ansible either because of [this][2]).

Right now, `cloudfront_distribution` _does_ seem to expose its generated `s3_origin_config` including the OAI but only via `invocation`. I only learned this by running my playbook with -vvv; this fact (and the data structure) is not explicitly documented.

[0]: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-granting-permissions-to-oai
[1]: https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-6
[2]: https://github.com/ansible/ansible/issues/42532#issuecomment-448576636

```yaml
- name: Create CloudFront OAI
  cloudfront_origin_access_identity:
    caller_reference: "{{ unique_and_deterministic }}"
    comment: "This shows up as the OAI identifier in the AWS S3 Console"
    region: "{{ region }}"
    state: present
  register: cloudfront_oai
- name: Create CloudFront Distribution
  cloudfront_distribution:
    origins:
      - id: my_awesome_site
        domain_name: my_awesome_site.s3.amazonaws.com
        s3_origin_config:
          origin_access_identity: "origin-access-identity/cloudfront/{{ cloudfront_oai.cloud_front_origin_access_identity.id }}"
```
