### ISSUE TITLE
[2.8] Adding objects with undefined properties to array transforms it into a string

### ISSUE THREAD

**Issue by lucasbasquerotto** [ansible/ansible#56552]
##### SUMMARY
When I add objects to a list in which at least 1 of the objects have an `AnsibleUndefined` property turns the entire list in a string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
!component

##### ANSIBLE VERSION
```
ansible 2.8.0rc3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/main/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/main/.local/lib/python3.6/site-packages/ansible
  executable location = /home/main/.local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION
```paste below

```
(there's no output when I run `ansible-config dump --only-changed`)

##### OS / ENVIRONMENT

Ubuntu 18.04, 1GB droplet in Digital Ocean

##### STEPS TO REPRODUCE

Use the code below to simulate the bug:

```yaml
- name: 'test list'
  set_fact: 
    test_list: []
    
- name: 'test_list loop'
  set_fact: 
    test_list: "{{ test_list + [{ 'name': item.name, 'answer': item.answer }] }}"
  loop: 
  - { name: "name1", answer: 42 }
  - { name: "name2", answer: 42 }
  - { name: "name3", answer: 42 }
  loop_control:
    label: "{{ item.name }}"

- debug:
    var: test_list

- name: 'test list2'
  set_fact: 
    test_list2: []
    
- name: 'test_list2 loop'
  set_fact: 
    test_list2: "{{ test_list2 + [{ 'name': item.name, 'answer': item.answer }] }}"
  loop: 
  - { name: "name1", answer: 42 }
  - { name: "name2", answer: 42 }
  - { name: "name3" }
  loop_control:
    label: "{{ item.name }}"

- debug:
    var: test_list2
```

##### EXPECTED RESULTS
```
ok: [localhost] => {
    "test_list": [
        {
            "answer": 42,
            "name": "name1"
        },
        {
            "answer": 42,
            "name": "name2"
        },
        {
            "answer": 42,
            "name": "name3"
        }
    ]
}

ok: [localhost] => {
    "test_list": [
        {
            "answer": 42,
            "name": "name1"
        },
        {
            "answer": 42,
            "name": "name2"
        },
        {
            "answer": AnsibleUndefined,
            "name": "name3"
        }
    ]
}
```

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "test_list": [
        {
            "answer": 42,
            "name": "name1"
        },
        {
            "answer": 42,
            "name": "name2"
        },
        {
            "answer": 42,
            "name": "name3"
        }
    ]
}

"test_list2": "[{'name': 'name1', 'answer': 42}, {'name': 'name2', 'answer': 42}, {'name': 'name3', 'answer': AnsibleUndefined}]"
```
