### ISSUE TITLE
jinja variables cannot be used in command module's cmd argument

### ISSUE THREAD

**Issue by jcdyer** [ansible/ansible#5657]
The following command fails with a syntax error because of 

```
- command: "{{ venv_dir }}/bin/gunicorn --config=gunicorn.conf"
```

But the following succeeds:

```
- action: command "{{ venv_dir }}/bin/gunicorn" --config=gunicorn.conf
```

It should be possible to use variables directly in a command.

**Comment by sivel** [comment]
I cannot duplicate this.  I tried with gunicorn, and I tried some use cases with echo and all of my tests work without issue.

Can you provide more information such as ansible version (`ansible -v`)?

My test:

``` yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    echo: echo
  tasks:
  - command: "{{ echo }} success --something=else"
    register: result
  - debug: var=result.stdout
```

```
TASK: [debug var=result.stdout] ***********************************************
ok: [localhost] => {
    "result.stdout": "success --something=else"
}
```
