### ISSUE TITLE
ERROR! 'listen' is not a valid attribute for a HandlerTaskInclude

### ISSUE THREAD

**Issue by victorock** [ansible/ansible#56580]
##### SUMMARY

When using `include_task` as handler with `listen` the following error is displayed:
`ERROR! 'listen' is not a valid attribute for a HandlerTaskInclude`

The snippet below was working fine in 2.7.10:
 handlers/main.yaml:
```yaml
---
- name: "Do Something"
  include_tasks: "{{ role_path }}/includes/something.yaml"
  listen: do_something
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_task

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /Users/jdacosta/.ansible.cfg
  configured module search path = [u'/Users/jdacosta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jdacosta/Devel/python/lib/python2.7/site-packages/ansible
  executable location = /Users/jdacosta/Devel/python/bin/ansible
  python version = 2.7.16 (default, Mar  8 2019, 11:42:47) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/jdacosta/.ansible.cfg) = [u'profile_tasks', u'skippy']
DEFAULT_HASH_BEHAVIOUR(/Users/jdacosta/.ansible.cfg) = merge
HOST_KEY_CHECKING(/Users/jdacosta/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/jdacosta/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

MAC OSX

##### STEPS TO REPRODUCE

```yaml
---
- name: "Do Something"
  include_tasks: "{{ role_path }}/includes/something.yaml"
  listen: do_something
```

##### WORKAROUND
```yaml
---
#- name: "Do Something"
- name: "do_something"
  include_tasks: "{{ role_path }}/includes/something.yaml"
#  listen: do_something
```

##### ACTUAL RESULTS

```paste below

```
