### ISSUE TITLE
gcp_dns_resource_record_set: Using 'state' produces Invalid value for 'parameters.name': 'None'

### ISSUE THREAD

**Issue by jamjon3** [ansible/ansible#56595]
##### SUMMARY

Using Ansible 2.8, when I add 'state: present' or 'state: absent', the module bombs with this error:

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_dns_resource_record_set

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04 / Ansible 2.8 in docker container

##### STEPS TO REPRODUCE

Add the 'state' with a value of present or absent. If you remove the 'state' parameter, it succeeds. This is a problem because I also need 'state: absent' to work and it doesn't.

```yaml
    - name: create a resource record set
      gcp_dns_resource_record_set:
        name: 'api.mygoogledomain.com.'
        managed_zone:
          name: "my-zone"
        type: A
        ttl: 600
        target:
          - "{{ api_ipaddress }}"
        project: "{{ lookup('env','CLOUDSDK_CORE_PROJECT') }}"
        state: present
      register: dns_resource
```

##### EXPECTED RESULTS

If I remove 'state' completely, it works fine:

TASK [create a resource record set] ********************************************
ok: [localhost]

aka (notice commented out 'state'):
```yaml
    - name: create a resource record set
      gcp_dns_resource_record_set:
        name: 'api.mygoogledomain.com.'
        managed_zone:
          name: "my-zone"
        type: A
        ttl: 600
        target:
          - "{{ api_ipaddress }}"
        project: "{{ lookup('env','CLOUDSDK_CORE_PROJECT') }}"
        # state: present
      register: dns_resource
```

##### ACTUAL RESULTS

Fails with Invalid value for 'parameters.name'

TASK [create a resource record set] ********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "GCP returned error: {u'error': {u'message': u\"Invalid value for 'parameters.name': 'None'\", u'code': 400, u'errors': [{u'reason': u'invalid', u'message': u\"Invalid value for 'parameters.name': 'None'\", u'domain': u'global'}]}}"}

```paste below
TASK [create a resource record set] ********************************************
task path: /var/lib/jenkins/workspace/pods_gke/ansible/playbook.yml:52
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809 `" && echo ansible-tmp-1558114750.45-225113795430809="` echo /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/google/gcp_dns_resource_record_set.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-211ipqObs/tmpaKdkJH TO /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809/AnsiballZ_gcp_dns_resource_record_set.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809/ /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809/AnsiballZ_gcp_dns_resource_record_set.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809/AnsiballZ_gcp_dns_resource_record_set.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1558114750.45-225113795430809/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_gcp_dns_resource_record_set_payload_vEWEwt/ansible_gcp_dns_resource_record_set_payload.zip/ansible/module_utils/gcp_utils.py", line 223, in raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_kind": "serviceaccount", 
            "managed_zone": {
                "name": "my-zone"
            }, 
            "name": "api.mygoogledomain.com.", 
            "project": "myproject", 
            "scopes": [
                "https://www.googleapis.com/auth/ndev.clouddns.readwrite"
            ], 
            "service_account_contents": null, 
            "service_account_email": null, 
            "service_account_file": "****", 
            "state": "present", 
            "target": [
                "10.80.223.105"
            ], 
            "ttl": 600, 
            "type": "A"
        }
    }, 
    "msg": "GCP returned error: {u'error': {u'message': u\"Invalid value for 'parameters.name': 'None'\", u'code': 400, u'errors': [{u'reason': u'invalid', u'message': u\"Invalid value for 'parameters.name': 'None'\", u'domain': u'global'}]}}"
}```
