### ISSUE TITLE
proxmox_kvm - updating VM config

### ISSUE THREAD

**Issue by mxkle** [ansible/ansible#56600]
##### SUMMARY
After creating a new VM from a clone, i cant update the VM config.
I am trying to modify the following values:
memory, cores, disks, description

The description value is getting updated correctly.
The memory, cores and disks values are left untouched, even though the ansible playbook returns changed or ok.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm

##### ANSIBLE VERSION
```
  config file = /home/maxe/Documents/it/ansible/ansible.cfg
  configured module search path = [u'/home/maxe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/maxe/Documents/it/ansible/ansible.cfg) = [u'/home/maxe/Documents/it/ansible/inventory/inventory.ini']
DEFAULT_LOG_PATH(/home/maxe/Documents/it/ansible/ansible.cfg) = /home/maxe/Documents/it/ansible/.ansible.log
DEFAULT_REMOTE_USER(/home/maxe/Documents/it/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/maxe/Documents/it/ansible/ansible.cfg) = [u'/home/maxe/Documents/it/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/maxe/Documents/it/ansible/ansible.cfg) = /home/maxe/Documents/it/ansible/.vault_pass.py
DISPLAY_SKIPPED_HOSTS(/home/maxe/Documents/it/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/maxe/Documents/it/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/maxe/Documents/it/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
root@pve:~# uname -a
Linux pve 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 GNU/Linux
```
pve template config
```
cat /etc/pve/qemu-server/902.conf 
bootdisk: virtio0
cores: 1
memory: 512
name: template-debian9
net0: virtio=AA:2D:0D:3C:E4:02,bridge=vmbr0
numa: 0
ostype: l26
scsihw: virtio-scsi-pci
smbios1: uuid=3ee34b3f-65cd-4df9-b584-506d65e19a11
sockets: 1
template: 1
virtio0: vmdata:base-902-disk-0,size=12G
vmgenid: 533a1cca-1c27-48ce-a839-e92468da3c15
```
vm999 host_vars
```
vmid: "902"
storage: "storage"
ostype: "l26"
onboot: yes
memory: 1024
node: "pve"
newid: "999"
name: "vm999"
ip: "192.168.122.134"
alternate_name: "test.clovr.lan"
cores: 4
clone: "arbitrary_name"

# start disks at virtio1 becuase virtio0 is already in use
disks: '{"virtio1":"storage:20,format=raw"}'
```
##### STEPS TO REPRODUCE

ansible playbook pve_deploy.yml
```
- name: clone template
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
    api_host: "{{ api_host }}"
    clone: arbitrary_name
    format: raw
    virtio: "{{ disks }}"
    vmid: "{{ vmid }}"
    storage: "{{ storage }}"
    state: present
    ostype: "{{ ostype }}"
    onboot: "{{ onboot }}"
    node: "{{ node }}"
    newid: "{{ newid }}"
    name: "{{ name }}"
    clone: "arbitrary_name"
  tags: deploy

- name: sleep for 30 seconds
  wait_for: timeout=30
  delegate_to: localhost

- name: update configuration | memory
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
    api_host: "{{ api_host }}"
    name: "{{ name }}"
    node: "{{ node }}"
    memory: "{{ memory }}"
    update: yes
  when: memory is defined
  tags: memory

- name: update configuration | cores
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
    api_host: "{{ api_host }}"
    name: "{{ name }}"
    node: "{{ node }}"
    cores: "{{ cores }}"
    update: yes
  when: cores is defined
  tags: cores

- name: update configuration | description
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
    api_host: "{{ api_host }}"
    name: "{{ name }}"
    node: "{{ node }}"
    description: |
      {{ name }}.clovr.lan
      alternate_dns: {{ alternate_name |default("-")}}
    update: yes
  tags: description

- name: start new vm
  proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
    api_host: "{{ api_host }}"
    name: "{{ name }}"
    node: "{{ node }}"
    state: started
  tags: start
```
##### EXPECTED RESULTS
Either a new VM should be created with 1 additional disk ({"virtio1":"storage:20,format=raw"}), 1024mb of ram and 4 cores or the module should print some errors.

##### ACTUAL RESULTS
Modul says everthing is fine:
```
ansible-playbook -e "@inventory/host_vars/vm999.clovr.lan/main.yml" playbooks/pve_deploy.yml
 --skip-tags start
 [WARNING]: While constructing a mapping from /home/maxe/Documents/it/ansible/roles/pve_deploy/tasks/main.yml, line 5, column 5,
found a duplicate dict key (clone). Using last defined value only.

 [WARNING]: Found variable using reserved name: name


PLAY [pve] *************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [pve.clovr.lan]

TASK [pve_deploy : clone template] *************************************************************************************************
ok: [pve.clovr.lan]

TASK [pve_deploy : sleep for 30 seconds] *******************************************************************************************
ok: [pve.clovr.lan -> localhost]

TASK [pve_deploy : update configuration | memory] **********************************************************************************
changed: [pve.clovr.lan]

TASK [pve_deploy : update configuration | cores] ***********************************************************************************
changed: [pve.clovr.lan]

TASK [pve_deploy : update configuration | description] *****************************************************************************
changed: [pve.clovr.lan]

PLAY RECAP *************************************************************************************************************************
pve.clovr.lan              : ok=6    changed=3    unreachable=0    failed=0  
```

VM Configuration:
```
cat /etc/pve/qemu-server/999.conf 
#vm999.clovr.lan
#alternate_dns%3A test.clovr.lan
acpi: 1
autostart: 0
balloon: 0
boot: cnd
bootdisk: virtio0
cores: 1
cpu: kvm64
cpuunits: 1000
kvm: 1
memory: 512
name: vm999
net0: virtio=02:51:33:FA:54:5C,bridge=vmbr0
numa: 0
onboot: 1
ostype: l26
scsihw: virtio-scsi-pci
smbios1: uuid=d3ffcdaa-3d15-4b85-9ad9-2fef22658808
sockets: 1
tablet: 0
template: 0
vga: std
virtio0: storage:vm-999-disk-0,size=12G
vmgenid: fe951911-f9a8-4d89-a8b5-3c906cb87ad2
``
Only the description value is updates, the rest (memory, cores, disks) is left untouched.
Is my desired deployment method possible with this module?
If yes, why does my playbook fail (or just behaves kinda strange)?

Any help appreciated here, thanks in advance!

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/misc/proxmox_kvm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @helldorado @joshainglis @karmab
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bkmeneguello** [comment]
I'm with a similar problem. I noticed "update" and "clone" are mutually exclusive, but they shouldn't. If VM exists, "clone" should always be ignored. So only when creating a new VM "clone" should be used.

**Comment by helldorado** [comment]
@mxkle @bkmeneguello fixe here #55874
Can you test and give a feedback ?

**Comment by bkmeneguello** [comment]
@helldorado Thanks for your effort, but unfortunately this don't fix my issue.
I'm trying to use "clone" and "update" in the same task, for example:
```yaml
- proxmox_kvm:
    state: started
    name: test
    template: Centos7
    update: true
```

What I expect is, when "test" VM doesn't exists, "clone" is used to create it. But if it does exists, it's updated.
Let's suppose my "state" is "started" by the VM is stopped. I what it to start, or if some options has changed, I want it updated. But if the VM doesn't exists, I want it created from my template.
