### ISSUE TITLE
Ansible galaxy role download should not have to perform additional check against tar archive file extension

### ISSUE THREAD

**Issue by arenard** [ansible/ansible#56616]
##### SUMMARY

Ansible galaxy role download should not have to perform additional check against tar archive file extension.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-galaxy

##### ADDITIONAL INFORMATION

Ansible galaxy role download performs unnecessary check against file extension and specifically against `.tar.gz`.
Tarfile `tarfile.is_tarfile(...)` method seems sufficient to identify if the file is a valid tarfile and if tarfile is able to open it.
This allows to open file by using transparent stream compression of tarfile. This makes `.tar.gz` and `.tar.bz2` formats valid with python 2.6.x/2.7.x (as well as `.tar.xz` with python 3.x).

```yaml
# from a webserver, where the role is packaged in a tar.gz
- src: https://some.webserver.example.com/files/master.tar.gz
  name: http-role-gz

# from a webserver, where the role is packaged in a tar.bz2
- src: https://some.webserver.example.com/files/master.tar.bz2
  name: http-role-bz2

# from a webserver, where the role is packaged in a tar.xz (only python 3.x)
- src: https://some.webserver.example.com/files/master.tar.xz
  name: http-role-xz
```
