### ISSUE TITLE
docker_container: `networks_cli_compatible: yes` playbook failed

### ISSUE THREAD

**Issue by g00nix** [ansible/ansible#56620]
##### SUMMARY

When running a playbook with `networks_cli_compatible: yes`, the playbook will fail with: 
```
failed: [vpn1] (item=192.168.121.2) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.2", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\")"}
```

Using `networks_cli_compatible: no` or commenting the `if self.networks_cli_compatible and self.networks:` section on `docker_container.py` will let the playbook run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container.py
[These linkes of code](https://github.com/ansible/ansible/blob/708bda06aa5cceaea5ead1e881a52b5adbc4d424/lib/ansible/modules/cloud/docker/docker_container.py#L1278-L1286) can be commented to prevent the playbook from crashing.

This seems like a good starting point for the troubleshoot.

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gunix/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

I am running the playbook on Arch Linux. Target nodes can be Fedora/Ubuntu/Arch, and the playbook fails for all of them. The docker version used is `18.09.6-ce`

##### STEPS TO REPRODUCE

This is the ansible code causing the issue:

```yaml
- name: "deploy network namespace that can hold all IPs"
  docker_network:
    name: "macvlan1"
    driver: macvlan
    driver_options:
      parent: "{{ ansible_default_ipv4.alias }}"
    ipam_config:
      - subnet: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('net') }}"
        gateway: "{{ ansible_default_ipv4.gateway }}"
        iprange: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr('net') }}"

- name: "deploy dummy containers to hold macvlan IPs"
  docker_container:
    name: "{{ item }}"
    image: "alpine:edge"
    state: started
    tty: true
    command: "/bin/sh"
    interactive: true
    restart_policy: always
    networks:
      - name: macvlan1
        ipv4_address: "{{ item }}"
      - name: internal_network
    purge_networks: yes
    networks_cli_compatible: yes
  with_items: "{{ macvlan_ips }}"
```

And this is how the host_vars look like:
```
macvlan_ips:
  - 192.168.121.11
  - 192.168.121.13
  - 192.168.121.14
```

##### EXPECTED RESULTS

The playbook should deploy the containers

##### ACTUAL RESULTS

The playbook fails.

```paste below
failed: [vpn1] (item=192.168.121.2) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.2", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\")"}
failed: [vpn2] (item=192.168.121.5) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.5", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\")"}
failed: [vpn3] (item=192.168.121.8) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.8", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"b'{\"message\":\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\"}'\")"}
failed: [vpn4] (item=192.168.121.11) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.11", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\")"}
failed: [vpn1] (item=192.168.121.3) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.3", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\")"}
failed: [vpn2] (item=192.168.121.6) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.6", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\")"}
failed: [vpn3] (item=192.168.121.9) => {"ansible_loop_var": "item", "changed": false, "item": "192.168.121.9", "msg": "Error creating container: 500 Server Error: Internal Server Error (\"b'{\"message\":\"json: cannot unmarshal object into Go struct field EndpointSettings.Aliases of type []string\"}'\")"}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
!component =lib/ansible/modules/cloud/docker/docker_container.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_container.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @cove @danihodovic @dariko @dusdanig @felixfontein @joshuaconner @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
@gun1x Which version of docker/docker-py (the Docker Python SDK) do you have installed on the host machines?

**Comment by gun1x** [comment]
Ubuntu 18.04:
```
pip3: docker-py (1.10.6)
apt: docker-ce                             5:18.09.6~3-0~ubuntu-bionic
```
ArchLinux:
```
docker 1:18.09.6-1
python-docker 3.7.2-1
```
Fedora:
```
python3-docker-3.5.0-1.fc29.noarch
docker-1.13.1-67.git1185cfd.fc29.x86_64
```

This is kind of embarrassing at the moment since it should be docker 18 on Fedora too. I must have a bug or something. I will fix it ASAP.

In case you need this, this is how I prepare the nodes:
```
cat roles/docker-host/distro_specific_tasks/*
---
- name: "(archlinux) upgrade all packages"
  pacman:
    update_cache: true
    upgrade: true
  register: reboot_required

- name: "(archlinux) install required packages"
  pacman:
    name:
      - 'vim'
      - 'docker'
      - 'python-docker'
      - 'bash-completion'
      - 'python-pyopenssl'
      - 'wireguard-tools'
      - 'wireguard-dkms'
      - 'linux-headers'
    state: present
  register: packages_installed
  until: packages_installed is succeeded
---
- name: "(fedora) disable selinux"
  selinux:
    state: disabled
  register: reboot_required

- name: "(fedora) upgrade all packages"
  dnf:
    name: "*"
    state: latest
  register: reboot_required

- name: "(fedora) create docker-ce repo with the latest stable version"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: 'config_files/docker/fedora-docker.repo'
      dest: '/etc/yum.repos.d/docker-ce.repo'
      mode: '0644'
    - src: 'config_files/wireguard/fedora-wireguard.repo'
      dest: '/etc/yum.repos.d/wireguard.repo'
      mode: '0644'

- name: "(fedora) install required packages"
  dnf:
    name:
      - 'vim'
      - 'docker'
      - 'python3-docker'
      - 'bash-completion'
      - 'wireguard-dkms'
      - 'wireguard-tools'
    state: present
  register: packages_installed
  until: packages_installed is succeeded

---
- name: "(ubuntu) run apt update"
  apt:
    update_cache: yes
  changed_when: False
  register: cache_update_status
  until: cache_update_status is succeeded

- name: "(ubuntu) do a full system upgrade"
  apt:
    upgrade: dist
    update_cache: no
  register: reboot_required

- name: "(ubuntu) add docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "(ubuntu) add docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: "add the WireGuard PPA"
  apt_repository:
    repo: 'ppa:wireguard/wireguard'

- name: "(ubuntu) install misc packages"
  apt:
    name:
      - 'vim'
      - 'aptitude'
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
      - 'python3-pip'
      - 'bash-completion'
      - 'python3-openssl'
      - 'wireguard'
    update_cache: yes

- name: "(ubuntu) install 'docker-ce'"
  apt:
    name: ['docker-ce']
    update_cache: yes

- name: "(ubuntu) get docker-py from pip"
  pip:
    name: docker-py
    state: latest
    #    executable: pip3
```
