### ISSUE TITLE
Ansible 2.7 crashes on apt upgrade because it upgrades itself to 2.8: "fragment_class is None"

### ISSUE THREAD

**Issue by somq** [ansible/ansible#56636]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

apt

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
```

##### CONFIGURATION

```paste below
`no output`
```

##### OS / ENVIRONMENT

```sh
uname -a
Linux hostname 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

When running apt upgrade ansible upgrades itself to latest version resulting in a crash (`"fragment_class is None"`) when running the next task:

I have a vagrant box setup which fails 

```sh
vagrant init _ocp/cobox-base --version 0.1.1
vagrant up
vagrant ssh

# inside the box
ansible-playbook playbook.yml -vvv
```

```yaml
---
- hosts: localhost
  gather_facts: yes

  tasks:
    - name: Upgrade all packages to the latest version.
      apt:
        upgrade: yes
        cache_valid_time: 3600

    - name: task2 - apt autoremove
      apt:
        autoremove: yes
```

##### EXPECTED RESULTS

Ansible should be able to update itself and continue running the playbook.

##### ACTUAL RESULTS

```paste below
TASK [task2 - apt autoremove)] *********************************************************************************************************************************************task path: /home/vagrant/shared/provisioning/scripts/ansible/playbook.yml:25
fatal: [localhost]: FAILED! => {
    "msg": "fragment_class is None"
}
        to retry, use: --limit @/home/vagrant/shared/provisioning/scripts/ansible/playbook.retry

PLAY RECAP **************************************************************************************************************************************************************localhost                  : ok=2    changed=1    unreachable=0    failed=1
```

##### Workaround

Put ansible package "`on hold`"

```yml
    - name: Put ansible on hold to prevent it auto-upgrading itself
      dpkg_selections:
        name: ansible
        selection: hold

    - name: Upgrade all packages to the latest version.
      apt:
        update_cache: yes
        upgrade: full
        force_apt_get: yes
```
