### ISSUE TITLE
azure_rm_deployment removes tags on Resource Group

### ISSUE THREAD

**Issue by rwaal** [ansible/ansible#56634]
##### SUMMARY
When the using the azure_rm_deployment module, the existing tags always seem to be removed from the Resource Group. The [documentation](https://docs.ansible.com/ansible/latest/modules/azure_rm_deployment_module.html) indicates that if you use the **append_tags** parameter, and set it to **true**, existing tags should not be removed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/roles']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANY_ERRORS_FATAL(/etc/ansible/ansible.cfg) = True
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = This file was created by Ansible, do not modify manually.
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible/roles']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/[myuser]/.ssh/[myansibleuser]
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible/roles']
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.6

##### STEPS TO REPRODUCE
```yml
- name: 'Create Azure Resource Group deployment'
  azure_rm_deployment:
	state: 'present'
	subscription_id: "{{ subscription_id }}"
	resource_group_name: "{{ item.network_virtual_appliance_resource_group_name }}"
	location: "{{ item.network_virtual_appliance_location }}"
	deployment_name: "NVA-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
	template: "{{ lookup('file', 'azuredeploy.json') }}"
	parameters:
	  virtualMachineName: 
		value: "{{ item.network_virtual_appliance_name }}"
	  virtualMachineNameOsDiskName:
		value: "{{ item.network_virtual_appliance_osdisk_name }}"
	  networkInterfaceProductionName:
		value: "{{ item.network_virtual_appliance_network_interface_production_name }}"
	  networkInterfaceManagementName:
		value: "{{ item.network_virtual_appliance_network_interface_management_name }}"
	  subnetProductionName:
		value: "{{ item.network_virtual_appliance_subnet_production_name }}"
	  subnetManagementName:
		value: "{{ item.network_virtual_appliance_subnet_management_name }}"
	  virtualNetworkName:
		value: "{{ item.network_virtual_applicance_vnet_name }}"
	  virtualNetworkResourceGroupName:
		value: "{{ item.network_virtual_appliance_vnet_resource_group_name }}"
	  availabilityZone:
		value: "{{ item.network_virtual_appliance_availability_zone }}"
	  vmSize:
		value: "{{ item.network_virtual_appliance_vmsize }}"
	  bootDiagnosticsBlobEndpoint:
		value: "{{ item.network_virtual_appliance_boot_diagnostics_primary_blob_endpoint }}"
	  adminPassword:
		value: "{{ network_virtual_appliance_admin_password }}"
	wait_for_deployment_polling_period: 10
	wait_for_deployment_completion: yes
	append_tags: true
  loop: "{{network_virtual_appliances | flatten(levels=1) }}"
  loop_control: 
	label: "{{ item.network_virtual_appliance_name }}" 
```

##### EXPECTED RESULTS
The Azure resources in the ARM template are deployed, where the existing tags on the Resources Group remain unchanged.

##### ACTUAL RESULTS
The ARM template is successfully deployed. However, the existing tags on the Resource Group have been removed.
