### ISSUE TITLE
gcp_container_cluster_facts use `items`.

### ISSUE THREAD

**Issue by henres** [ansible/ansible#56639]
##### SUMMARY
gcp_container_cluster_facts use `items` in his return so when i want to loop on it i have this.

Given:
```yaml
-
    name: "Get clusters facts"
    gcp_container_cluster_facts:
        location: "{{ cluster.zone | default(cluster_config.default_config.zone) }}"
        project: "{{ cluster.gke_project | default(cluster_config.default_config.gke_project) }}"
        auth_kind: "{{ cluster.auth_kind | default(cluster_config.default_config.auth_kind) }}"
        service_account_file: "{{ cluster.service_account_file | default(cluster_config.default_config.service_account_file) }}"
    delegate_to: "{{ worker.container.name }}"
    register: cluster_facts

-
    name: "debug"
    debug:
        msg: "{{ item }}"
    loop: "{{ cluster_facts.items|flatten(levels=1) }}"
```

error:
```
fatal: [clusters-manager]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ cluster_facts.items|flatten(levels=1) }}): 'builtin_function_or_method' object is not iterable"}
```

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /project/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/project/ansible.cfg) = True
DEFAULT_BECOME(/project/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/project/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/project/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/project/ansible.cfg) = root
DEFAULT_EXECUTABLE(/project/ansible.cfg) = /bin/bash
DEFAULT_HOST_LIST(/project/ansible.cfg) = [u'/project/inventory/hosts.yaml']
DEFAULT_LOG_PATH(/project/ansible.cfg) = /project/ansible.log
DEFAULT_REMOTE_USER(/project/ansible.cfg) = root
DEFAULT_ROLES_PATH(/project/ansible.cfg) = [u'/project/roles', u'/project/roles/galaxy']
DEFAULT_TIMEOUT(/project/ansible.cfg) = 20
HOST_KEY_CHECKING(/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT

on Docker Alpine installed by pip
