### ISSUE TITLE
HomeBrew updates anyway, even, if update_homebrew: no set

### ISSUE THREAD

**Issue by max-wittig** [ansible/ansible#56650]
##### SUMMARY
Expected: HomeBrew doesn't upgrade itself
Actual: HomeBrew updates itself

```yaml
- name: HomeBrew | Install and upgrade base packages
  homebrew:
    update_homebrew: no  # seems like this setting is not doing anything
    upgrade_all: yes
    name:
     - git
     - wget
     - curl
     - htop
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
homebrew

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/ladmin/Documents/Development/***/ansible.cfg
  configured module search path = ['/home/ladmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ladmin/.local/share/virtualenvs***-YaD9YgAS/lib/python3.6/site-packages/ansible
  executable location = /home/ladmin/.local/share/virtualenvs/***-YaD9YgAS/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/ladmin/Documents/Development/***/ansible.cfg) = ['/home/ladmin/Documents/Development/***/hosts-***.yml']
```

##### OS / ENVIRONMENT

```
ladmin$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

##### WORKAROUND

Setting the `HOMEBREW_NO_AUTO_UPDATE` environment variable

```yaml
- name: HomeBrew | Install and upgrade base packages
  homebrew:
    update_homebrew: no  # seems like this setting is not doing anything
    upgrade_all: yes
    name:
     - git
     - wget
     - curl
     - htop
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
```
