### ISSUE TITLE
copy: reflink support

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/ansible#56669]
##### SUMMARY
When doing a remote copy, support a new `copy` argument called `reflink` that will allow a sparse copy of a file if the file system (such as BtrFS or XFS) supports it. This helps to save space when backing up files.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
copy module

##### ADDITIONAL INFORMATION
Example usage:

```
- name: Example of a sparse copy
  copy:
    src: example.db
    dest: example.db.backup
    remote_src: True
    reflink: True
```

Behind-the-scenes, this would run `cp --reflink=always example.db example.db.backup` on the remote host.

Conversely, it can be explicitly disabled.

```
- name: Example of a sparse copy
  copy:
    src: example.db
    dest: example.db.backup
    remote_src: True
    reflink: False
```

Which would lead to this being executed to ensure it is a full copy: `cp --reflink=never example.db example.db.backup`.
