### ISSUE TITLE
Add_children in an XML file is not working

### ISSUE THREAD

**Issue by Oli67-DevOps** [ansible/ansible#56699]
##### SUMMARY
Hello,

I'm working with Ansible latest version (ansible 2.7.7), with the XML module and lxml latest version, I use some add_children in a role with different XML files, but weirdly one is not working.
Indeed, Ansible tells me it's ok, but it's not. The XML "injection" is not set.

The file is an XML with more than 4500 lines, it is provided by an editor of software for a web-app for scheduled/booked room for universities, etc.

The injection is for redirecting http to https.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Xml Module

##### ANSIBLE VERSION
```2.7.7```

##### CONFIGURATION
```ANSIBLE_SSH_CONTROL_PATH(/c/Users/oli/Documents/Git-Local/Ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%n-%%p-%%r 
DEFAULT_ROLES_PATH(/c/Users/oli/Documents/Git-Local/Ansible/ansible.cfg) = ['/c/Users/oli/Documents/Git-Local/Ansible/roles/common', '/c/Users/oli/Documents/Git-Local/Ansible/roles/cocktail', '/c/Users/oli/Documents/Git-Local/Ansible/roles/common', 
DEFAULT_SCP_IF_SSH(/c/Users/oli/Documents/Git-Local/Ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/c/Users/oli/Documents/Git-Local/Ansible/ansible.cfg) = skippy
RETRY_FILES_ENABLED(/c/Users/oli/Documents/Git-Local/Ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: Add XML for https redirection in "opt/ade600/Web/tomcat/conf/web.xml"
  xml:
    file: "/opt/ade600/Web/tomcat/conf/web.xml"
    xpath: /web-app
    input_type: xml
    pretty_print: yes
    state: present
    add_children: 
       - "<security-constraint><web-resource-collection><web-resource-name>Automatic Forward to HTTPS/SSL</web-resource-name><url-pattern>/*</url-pattern></web-resource-collection><user-data-constraint><transport-guarantee>CONFIDENTIAL</transport-guarantee></user-data-constraint></security-constraint>"
```
##### EXPECTED RESULTS

The XML block is added at the end of the xml files in the Xpath provided.

##### ACTUAL RESULTS
Ansible tells it's ok but the Xml block is not added.

```TASK [ade : Add XML for https redirection in "/opt/ade600/Web/tomcat/conf/web.xml"] ******************************ok: [server-test] ```
