### ISSUE TITLE
ansible 2.8: "skip: true" vs "errors=ignore"

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#56713]
##### SUMMARY
`find_first`: with ansible 2.8 `skip=false` is marked as deprecated in favour of `errors="ignore"`.
But when using `errors="ignore"` ansible tells me to use `skip: true` instead and fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
first_found

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/phil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - include: '{{item}}'
      loop: '{{q("first_found", dict(files=["a.yml", "b.yml", "c.yml"], skip=true))}}'
    - include: '{{item}}'
      loop: '{{q("first_found", dict(files=["a.yml", "b.yml", "c.yml"], errors="ignore"))}}'
```
please note that **none** of `{a,b,c}.yml` must exist.

##### EXPECTED RESULTS
both tasks being skipped.

##### ACTUAL RESULTS
```
PLAY [localhost] *************************************************************************

TASK [include] ***************************************************************************
[DEPRECATION WARNING]: Use errors="ignore" instead of skip. This feature will be removed 
in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

TASK [include] ***************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, origin
al message: No file was found when using first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}

PLAY RECAP *******************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```
