### ISSUE TITLE
ansible 2.7/2.8: copy result registration in check mode

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#56716]
##### SUMMARY
When running a playbook in check mode the `copy` module behaves differently than in "live" mode.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION
```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/phil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```
```
ansible 2.7.10 (detached HEAD e75f58f305) last updated 2019/05/21 09:56:29 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/phil/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/phil/ansible/lib/ansible
  executable location = /home/phil/ansible/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - copy:
        content: "{{item}}"
        dest: '/tmp/ansible-copy-{{item}}.tmp'
      loop: ['a', 'b', 'c']
      register: foo
    - debug: var=item
      loop: '{{foo.results|select("changed")|map(attribute="dest")|list}}'
```

##### EXPECTED RESULTS
same output as without `--check`.

##### ACTUAL RESULTS
```paste below
$ ANSIBLE_LOG=/dev/null ansible-playbook copy2.yml -C
PLAY [localhost] *************************************************************************************

TASK [copy] ******************************************************************************************
changed: [localhost] => (item=a)
changed: [localhost] => (item=b)
changed: [localhost] => (item=c)

TASK [debug] *****************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: [AnsibleUndefined, AnsibleUndefined, AnsibleUndefined]. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

PLAY RECAP *******************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
```$ ANSIBLE_LOG=/dev/null ansible-playbook copy2.yml

PLAY [localhost] *************************************************************************************

TASK [copy] ******************************************************************************************
changed: [localhost] => (item=a)
changed: [localhost] => (item=b)
changed: [localhost] => (item=c)

TASK [debug] *****************************************************************************************
ok: [localhost] => (item=/tmp/ansible-copy-a.tmp) => {
    "ansible_loop_var": "item",
    "item": "/tmp/ansible-copy-a.tmp"
}
ok: [localhost] => (item=/tmp/ansible-copy-b.tmp) => {
    "ansible_loop_var": "item",
    "item": "/tmp/ansible-copy-b.tmp"
}
ok: [localhost] => (item=/tmp/ansible-copy-c.tmp) => {
    "ansible_loop_var": "item",
    "item": "/tmp/ansible-copy-c.tmp"
}

PLAY RECAP *******************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/copy.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/copy.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This is happening because `dest` is not returned by the `copy` module when run in `check` mode. Here is a simpler reproducer (run with `-vvv` to see what is returned):

```yaml
- hosts: localhost
  connection: local
  become: no

  tasks:
    - name: Copy in check mode
      copy:
        content: a
        dest: /tmp/ansible-copy-a
      check_mode: yes

    - name: Normal copy
      copy:
        content: b
        dest: /tmp/ansible-copy-b
      check_mode: no
```
