### ISSUE TITLE
Win_Find Partially Unknown Folder Performance (2.4.2->2.8.0 Regression)

### ISSUE THREAD

**Issue by ScottMichaud** [ansible/ansible#56712]
##### SUMMARY

Finding partially-unknown folders (ex: name contains a version code) with **win_find** in Ansible 2.8.0 is slow. (I gave up after about an hour on a fresh Windows 10 VM.) Ansible 2.4.2 allowed narrowing down the search by wildcards, which cut down the search time to (approximately) a couple of minutes.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_find

##### ADDITIONAL INFORMATION

In Ansible 2.4.2, the **win_find** module was capable of wildcards in its paths property. This allowed finding folders with partially unknown names (ex: certain software packages, such as Apache Karaf, that store their version number in the folder name).

win_find in Ansible 2.8.0 fails with the msg: "Argument path C:\\apache-karaf* does not exist cannot get information on"

Ansible 2.4.2 would crash (system out of memory exception) attempting to scan the full C:\ drive (without the wildcard clue). Ansible 2.8.0 doesn't crash, but it takes an unreasonable amount of time to complete. (I've never actually seen 2.8.0 complete a full C:\ scan. I gave up after about an hour on a fresh Windows 10 VM.)

In Ansible 2.4.2 with wildcard paths, the playbook would complete in about a couple of minutes.

Note that copying win_find from Ansible 2.4.2 on the CentOS 7 extras repo (and renaming it as a user module called win_find_old in my case) allows wildcards in paths at high performance with Ansible 2.8.0.

```yaml
---
- name: Update Karaf Service Config File
  hosts: win
  tasks:
    - name: Searching for Apache Karaf
      win_find:
        paths:
          - "{{karaf_path_token}}"
        recurse: yes
        get_checksum: no
        patterns: "*my.config.file.cfg"
      register: found_paths
    - name: Update each config file from template
      win_template:
        src: "cfg_templates/my_config_file_template.cfg.j2"
        force: yes
        dest: "{{item.path}}"
      with_items: "{{found_paths.files}}"
      
# Hosts file contains the following variable:
#
# karaf_path_token=["C:\\apache-karaf*", "C:\\test\\apache-karaf*"]
# (as well as all the variables required for win_template)
#
# This finds, for example, C:\apache-karaf-2.4.5\etc\my.config.file.cfg or
# C:\test\apache-karaf-2.4.5\etc\my.config.file.cfg
#
# It would also find a new version number when the user manually updates Karaf.
# Ideally, this would also be managed with Ansible, but it is not.
#
# The benefit over starting from C:\ is speed. This wildcard behaviour
# was seen on Ansible 2.4.2. It's changed some time between then and 2.8.0. 
#
# Note: This suggestion is based on behaviour from Ansible 2.4.2. Another
# solution that would find a partially-unknown folder, potentially in C:\,
# without scanning every file (>1 hour vs about a couple minutes on a new VM in
# my testing) would also work.
```
