### ISSUE TITLE
Ansible 2.8.0 no longer able to autnenticate to ACI with private key

### ISSUE THREAD

**Issue by DaveCrown** [ansible/ansible#56744]
##### SUMMARY

After upgrading from 2.7.10 to 2.8.0, key based authentication with the ACI modules is intermittent. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- aci_config_snapshot
- aci_interface_policy_mcp
- aci_rest appears to work

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/dave/code/aci/ansible.cfg
  configured module search path = ['/home/dave/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

ansible 2.8.0
  config file = /opt/aci/ansible.cfg
  configured module search path = [u'/home/dave/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/dave/code/aci/ansible.cfg) = ['/home/dave/code/aci/etc/inventory']
YAML_FILENAME_EXTENSIONS(/home/dave/code/aci/ansible.cfg) = ['.json', '.yaml', '.yml', '.vault']
```

##### OS / ENVIRONMENT

- Fedora 30
- Centos 7.6
- RHEL 7.6

- prod aci 3.2.3o  
- test aci 4.1.1i

##### STEPS TO REPRODUCE

yum upgrade  
ansible-playbook create_snapshot.yml -e "apic=lab" (for aci 4.1.1i)  
fails

yum downgrade ansible  
ansible-playbook create-snapshot.yml -e "apic=prod" (for aci 3.2.3o)  
passes

create_snapshot.yaml
```yaml
---
- hosts: "{{apic}}"
  gather_facts: yes
  become: no
  connection: local
  #strategy: debug

  tasks:
  - name: take shanpshot for {{ apic_env.title() }}
    include_role:
      name: create-snapshot
```
create snapshot role
```yaml
---
- name: create {{ apic_env }} snapshot
  aci_config_snapshot:
    hostname: "{{ apic_address }}"
    username: "{{ apic_user }}"
    private_key: "{{apic_key_path}}"
    certificate_name: "{{apic_cert_name}}"
    validate_certs: no
    use_proxy: no
    state: present
    description: "{{descrption | default('auto_ansible') }}"
    export_policy: config_backup
  register: snapshot
```
group_vars/all
```yaml
---
apic_user: "{{ansible_env.APIC_USER}}"
apic_key_path: "{{ansible_env.APIC_KEY}}"
apic_key_filename: "{{ansible_env.APIC_KEY | basename | regex_replace('\\..*') }}"
apic_cert_name: "{{ ansible_env.APIC_CERT_NAME | default(apic_key_filename) }}"
<!--- HINT: You can paste gist.github.com links for larger files -->
```
##### EXPECTED RESULTS

dave@ACI-(dc1)-Sniffer aci]$ ansible-playbook create_snapshot.yaml -e "apic=prod"  

PLAY [prod] *******************************************************************************************************************  

TASK [Gathering Facts] ********************************************************************************************************  
ok: [(dc2)_aci]  
ok: [(dc1)_aci]  

TASK [take shanpshot for (DC1)] ***********************************************************************************************  

TASK [create-snapshot : create (dc1) snapshot] ********************************************************************************  
changed: [(dc1)_aci]  
changed: [(dc2)_aci]  

PLAY RECAP ********************************************************************************************************************  
(dc2)_aci                  : ok=2    changed=1    unreachable=0    failed=0  
(dc1)_aci                  : ok=2    changed=1    unreachable=0    failed=0  

[dave@ACI-(DC1)-Sniffer aci]$  

##### ACTUAL RESULTS

```paste below
[dave@ACI-(dc2)-Sniffer aci]$ ansible-playbook create_snapshot.yaml -e "apic=prod"  

PLAY [prod] *******************************************************************************************************************  

TASK [Gathering Facts] ********************************************************************************************************  
ok: [(dc2)_aci]  
ok: [(dc1)_aci]  

TASK [take shanpshot for (dc1)] ***********************************************************************************************  

TASK [create-snapshot : create (dc1) snapshot] ********************************************************************************  
fatal: [(dc2)_aci]: FAILED! => {"changed": false, "error": {"code": "403", "text": "Need a valid webtoken cookie (named APIC-Cookie) or a signed request with signature in the cookie APIC-Request-Signature for all REST API requests"}, "msg": "APIC Error 403: Need a valid webtoken cookie (named APIC-Cookie) or a signed request with signature in the cookie APIC-Request-Signature for all REST API requests"}  
fatal: [(dc1)_aci]: FAILED! => {"changed": false, "error": {"code": "403", "text": "Need a valid webtoken cookie (named APIC-Cookie) or a signed request with signature in the cookie APIC-Request-Signature for all REST API requests"}, "msg": "APIC Error 403: Need a valid webtoken cookie (named APIC-Cookie) or a signed request with signature in the cookie APIC-Request-Signature for all REST API requests"}  

PLAY RECAP ********************************************************************************************************************  
(dc2)_aci                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
(dc1)_aci                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  


```
verbose output in error.txt
[error.txt](https://github.com/ansible/ansible/files/3204034/error.txt)
