### ISSUE TITLE
gcp_compute inventory source much slower than gce.py

### ISSUE THREAD

**Issue by andyshinn** [ansible/ansible#56752]
##### SUMMARY
When upgrading from `gce.py` to the new `gcp_compute` inventory source there is a noticeable slowdown in performance. Without specifying zones it can take over 30 seconds for inventory to resolve. Specifying zones to lower the scope helps but it is still much slower than the old inventory script.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`gcp_compute` inventory source (https://docs.ansible.com/ansible/devel//plugins/inventory/gcp_compute.html).

##### ANSIBLE VERSION

```paste below
$ ansible --version                  
ansible 2.8.0
  config file = None
  configured module search path = ['/Users/andy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/Users/andy/Projects/myorg/infrastructure/ansible.cfg) = 2
DEFAULT_REMOTE_USER(env: ANSIBLE_REMOTE_USER) = andy
DEFAULT_ROLES_PATH(/Users/andy/Projects/myorg/infrastructure/ansible.cfg) = ['/Users/andy/Projects/myorg/infrastructure/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/andy/.ansible/vault
HOST_KEY_CHECKING(/Users/andy/Projects/myorg/infrastructure/ansible.cfg) = False
INVENTORY_UNPARSED_IS_FAILED(/Users/andy/Projects/myorg/infrastructure/ansible.cfg) = True
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

default.gcp.yml:
```yaml
plugin: gcp_compute
projects:
  - default-3afe2845
service_account_file: ~/.config/gcloud/andy-admin.json
auth_kind: serviceaccount
scopes:
  - "https://www.googleapis.com/auth/compute.readonly"
keyed_groups:
  - prefix: tag
    key: tags['items']
  - prefix: project
    key: project
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
```

##### OS / ENVIRONMENT

macOS 10.14.4
targets are Ubuntu 16.04 and 18.04

##### STEPS TO REPRODUCE

Run running inventory against the new module using `ansible-inventory` it is very slow when compared to `gce.py`:

```console
$ /usr/bin/time ansible-inventory -i default.gcp.yml --graph
...
       36.86 real         3.40 user         0.26 sys
```

```console
$ /usr/bin/time ansible-inventory -i gce.py --graph
...
        3.21 real         0.82 user         0.38 sys
```

##### EXPECTED RESULTS

The new `gcp_compute` inventory source should perform similar to the older script. I did some investigating and it looks like the `gce.py` contrib script is based on `apache-libcoud` which uses the https://cloud.google.com/compute/docs/reference/rest/v1/instances/aggregatedList API endpoint to get all the instances and their zones and applies the zones list _after_ the call. The new source uses https://cloud.google.com/compute/docs/reference/rest/v1/instances/list and requires the zone to be known and queried before listing which adds considerable amount of processing time.

Expected inventory time for ~30 instances to be around 3-4 seconds.

##### ACTUAL RESULTS

New `gcp_compute` inventory source when querying all zones can be over 30 seconds. Is much faster when zones can be specified ahead of time (closer to 4-5 seconds for 3 zones). But this is difficult as the zones are no always known beforehand.
