### ISSUE TITLE
plugins using load_file_common_arguments: mode=preserve is broken

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#56839]
##### SUMMARY

There are some plugins/modules out there that make use of `load_file_common_arguments`. This should enable these modules to use … well, common arguments, like:
```
- mode
        The permissions the resulting file or directory should have.
[…]
        As of Ansible 2.6, the mode may also be the special string
        `preserve'.
        When set to `preserve' the file will be given the same
        permissions as the source file.
        [Default: (null)]
        type: str
```
but `mode: preserve` throws
```
bad symbolic permission for mode: preserve"
```
As `openssl_privatekey` decides on its own about the file permissions (sets them to 0600 even though the file already exists with other access rights) instead of leaving them alone the `mode` option is mandatory in my playbooks.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

basic.py
(unsure)

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/phil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

```paste below
ansible 2.7.10 (detached HEAD e75f58f305) last updated 2019/05/23 12:53:22 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/phil/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/phil/ansible/lib/ansible
  executable location = /home/phil/ansible/bin/ansible
  python version = 2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    tmpdir: /tmp/ansible-test
  tasks:
    - file: path={{tmpdir}} state=directory
    - copy:
        dest: '{{tmpdir}}/copy.tmp'
        content: |
          [foo]
          bar = baz
        mode: preserve
      ignore_errors: true
    - file:
        path: '{{tmpdir}}/copy.tmp'
        state: file
        mode: preserve
      ignore_errors: true
    - ini_file:
        path: '{{tmpdir}}/copy.tmp'
        section: foo
        option: bar
        value: yatta
        mode: preserve
      ignore_errors: true
    - openssl_privatekey:
        path: '{{tmpdir}}/openssl_privatekey.tmp'
        mode: preserve
      ignore_errors: true
```

##### EXPECTED RESULTS

tasks succeeding, file modes being preserved

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ********************************************************************

TASK [file] *************************************************************************
ok: [localhost]

TASK [copy] *************************************************************************
changed: [localhost]

TASK [file] *************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "details": "bad symbolic permission for mode: preserve", "gid": 1002, "group": "phil", "mode": "0600", "msg": "mode must be in octal or symbolic form", "owner": "phil", "path": "/tmp/ansible-test/copy.tmp", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 16, "state": "file", "uid": 1002}
...ignoring

TASK [ini_file] *********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "details": "bad symbolic permission for mode: preserve", "gid": 1002, "group": "phil", "mode": "0600", "msg": "mode must be in octal or symbolic form", "owner": "phil", "path": "/tmp/ansible-test/copy.tmp", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 18, "state": "file", "uid": 1002}
...ignoring

TASK [openssl_privatekey] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "details": "bad symbolic permission for mode: preserve", "gid": 1002, "group": "phil", "mode": "0664", "msg": "mode must be in octal or symbolic form", "owner": "phil", "path": "/tmp/ansible-test/openssl_privatekey.tmp", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 3272, "state": "file", "uid": 1002}
...ignoring

PLAY RECAP **************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/module_utils/basic.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by atruskie** [comment]
I just run into this issue as well:

```yml
    - name: "Generate the private key file to sign the CSR"
      openssl_privatekey:
        path: "{{ dir }}/{{ name }}.key"
        passphrase: "{{ private_key_password }}"
        cipher: auto
        mode: preserve
```

```
fatal: [blah.blah.org -> localhost]: FAILED! => {
    "changed": false,
    "details": "bad symbolic permission for mode: preserve",
    "gid": 1000,
    "group": "anthony",
    "mode": "0744",
    "owner": "anthony",
    "path": "/blah/blah/blah.key",
    "size": 3326,
    "state": "file",
    "uid": 1000
}
MSG:
mode must be in octal or symbolic form
```

In my case, I'm (temporarily) storing a key on a mount that doesn't preserve permissions.

```
$ ansible --version
ansible 2.8.2
  config file = /mnt/c/Work/GitHub/baw-private/Ansible/ansible.cfg
  configured module search path = ['/home/anthony/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/anthony/.local/lib/python3.6/site-packages/ansible
  executable location = /home/anthony/.local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

**Comment by atruskie** [comment]
This also affects `openssl_certificate`

**Comment by sivel** [comment]
I believe this is a documentation error.  `mode=preserve` was only implemented in the copy module, and by extension the `template` module.

Someone later came in and attempted to consolidate documentation, and added the note about `mode=preserve` to the generic documentation fragment utilized by all modules supporting file operations.

These options were explicitly documented for copy/template as part of https://github.com/ansible/ansible/commit/83c1cba511c99d5c68d4e0c5e596b9d07021ab8a

The later commit that added `preserve` to the common file docs: https://github.com/ansible/ansible/commit/be0dc34b6fed0f8a272de87e049a29b964d1702c

As such, based on this, standard file operations do not support this functionality and the docs should be fixed.

A future feature enhancement could be done to allow `mode=preserve` to work in standard file operations in modules.

**Comment by sivel** [comment]
cc @acozine

**Comment by philfry** [comment]
In that case, modules like `openssl_privatekey` must not decide on their own about file properties. The `mode: preserve`-thingy only became necessary because `openssl_privatekey` suddenly did permission changed. Shall I open another bug report for it or is fixing the `mode: preserve` preferrable?

**Comment by sivel** [comment]
@philfry It could be fixed all at once potentially.  By adding the new feature it could resolve the docs issue.  However the docs in past versions are incorrect, and a new feature wouldn't be backported.  So we are likely looking at the necessity of a bugfix and a new feature.

**Comment by philfry** [comment]
Thanks. I'd offer my help but in the past there was no much interest in my PRs.
Guess I'll wait then :)

**Comment by septatrix** [comment]
Is there any status on whether or not it is planed to update the docs by reverting the section regarding the mode parameter from be0dc34. I think this would clear up a lot of confusion with other file related modules extending the default doc fragment even though to majority don't implement `mode=preserve`

**Comment by geerlingguy** [comment]
It seems like this also doesn't work with the `replace` module:

```yaml
    - name: Change the kubeconfig port to the proper value
      replace:
        regexp: 8443
        replace: "{{ lookup('env', 'KIND_PORT') }}"
        path: '{{ kubeconfig }}'
        mode: 'preserve'
      delegate_to: localhost
```

Results in:

```
fatal: [kind-test-local]: FAILED! => {"changed": false, "details": "bad symbolic permission for mode: preserve", "gid": 2000, "group": "travis", "mode": "0600", "msg": "mode must be in octal or symbolic form", "owner": "travis", "path": "/tmp/molecule/kind-test-local/kubeconfig", "size": 5436, "state": "file", "uid": 2000}
```
