### ISSUE TITLE
Digital Ocean - deleting droplets not working

### ISSUE THREAD

**Issue by gerhard** [ansible/ansible#5683]
I'm on OS X 10.8.5, running Python 2.7.2 & Ansible 1.4.4, using the following play:

``` yml

---
- name: DigitalOcean
  hosts: localhost

  vars_files:
    - vars/digital_ocean.yml

  tasks:
  - name: Delete DigitalOcean Droplet
    digital_ocean: >
      state=deleted
      name={{ name }}
      unique_name=yes
      region_id={{ region_id }}
      size_id={{ size_id }}
      region_id={{ region_id }}
      image_id={{ image_id }}
```

I'm running `ansible-playbook delete_droplet.yml -i hosts -c local -vvvv`:

``` sh
PLAY [DigitalOcean] ***********************************************************

GATHERING FACTS ***************************************************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1390171012.22-79718567464912 && chmod a+rx $HOME/.ansible/tmp/ansible-1390171012.22-79718567464912 && echo $HOME/.ansible/tmp/ansible-1390171012.22-79718567464912']
<localhost> REMOTE_MODULE setup
<localhost> PUT /var/folders/vc/x4k63yxn55z0p2cqztmq9f7w0000gn/T/tmpDEktBF TO /Users/gerhard/.ansible/tmp/ansible-1390171012.22-79718567464912/setup
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/gerhard/.ansible/tmp/ansible-1390171012.22-79718567464912/setup; rm -rf /Users/gerhard/.ansible/tmp/ansible-1390171012.22-79718567464912/ >/dev/null 2>&1']
ok: [localhost]

TASK: [Delete DigitalOcean Droplet] *******************************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1390171012.67-273759989272528 && chmod a+rx $HOME/.ansible/tmp/ansible-1390171012.67-273759989272528 && echo $HOME/.ansible/tmp/ansible-1390171012.67-273759989272528']
<localhost> REMOTE_MODULE digital_ocean state=deleted name=dod-ams2 unique_name=yes region_id=5 size_id=62 region_id=5 image_id=350076
<localhost> PUT /var/folders/vc/x4k63yxn55z0p2cqztmq9f7w0000gn/T/tmpsCMcp8 TO /Users/gerhard/.ansible/tmp/ansible-1390171012.67-273759989272528/digital_ocean
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /Users/gerhard/.ansible/tmp/ansible-1390171012.67-273759989272528/digital_ocean; rm -rf /Users/gerhard/.ansible/tmp/ansible-1390171012.67-273759989272528/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true}
msg: Unable to load id

FATAL: all hosts have already failed -- aborting
```

**Comment by mpdehaan** [comment]
Looking through the code here it looks like the code is attempting to look up 'id' and there is no parameter 'id' passed in, this is probably something broken in a refactor or update.

**Comment by mpdehaan** [comment]
This should be fixed in recent commits where it doesn't pass "id".  If you are still seeing this problem please let us know!

**Comment by jojje** [comment]
I also ran into this problem on v1.5.5
For some reason the commit is only in the devel branch and not yet in any of the releases.

If someone else runs into this snag, but want to stay on a stable release as much as possible, then just cherry pick this fix.

git cherry-pick 8276face94207cbbb6a803a3be38a36f46e3a9f6

**Comment by lgueye** [comment]
Hi all,
I also have this problem. I'm running ansible 1.8.2 and running in verbose mode logs 'The droplet is not found.'

**Comment by nsg** [comment]
I was affected by this in 2.2, looks like only `id` works with delete. Something like this worked for me:

```
    - name: Get data
      digital_ocean:
        unique_name: yes
        api_token: "{{ do_api_token }}"
        name: myserver.example.com
      register: message

    - name: Remove droplet
      digital_ocean:
        api_token: "{{ do_api_token }}"
        id: "{{ message.droplet.id }}"
        state: deleted
```

**Comment by obilodeau** [comment]
If you use a dynamic inventory with `digital_ocean.py` (available here: https://github.com/ansible/ansible/blob/devel/contrib/inventory/digital_ocean.py) you can use the `do_id` variable. This allows you to get rid of all the hosts that have a specific tag with a playbook like:

```yaml
- name: Destroy digital ocean instances based on tag
  hosts: <tag>
  connection: local
  gather_facts: False

  tasks:
  - name: Destroy instances
    digital_ocean:
      api_token: "{{ do_api_token }}"
      id: "{{ do_id }}"
      state: deleted
  - debug:
     msg: "Instance {{ do_name }} destroyed"
```

ansible 2.4.2

p.s.: leaving this here because this is what I was originally looking for and ended up here
