### ISSUE TITLE
nios_srv_record with view parameter can't be updated due to "Field is not allowed for update: view" error

### ISSUE THREAD

**Issue by simonlg** [ansible/ansible#56856]
##### SUMMARY
The nios_srv_record can't update a SRV record because it passes the view paramater within the PUT request.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_srv_record

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
I've tested on the latest 'devel' and 'stable-2.8' and the problem is still there.

##### CONFIGURATION

```paste below
No output
```

##### OS / ENVIRONMENT

RedHat 7.5, Infoblox WAPI 2.3.1

##### STEPS TO REPRODUCE
Create SRV record with nios_srv_record and then update the comment using nios_srv_record.

```yaml
---
- hosts: all
  become: yes
  tasks:
    - name: Setup-Playbook
      setup: # Executes gather facts on all inventory

- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: create SRV record
    nios_srv_record:
      name: "bug.domain.com"
      port: "10000"
      priority: 1
      target: "target-bug.domain.com"
      weight: 10
      state: present
      comment: "ansible bug"
      provider:
        host: "{{ infoblox_server }}"
        username: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        wapi_version: "{{ infoblox_api_version }}"
      view: "external"
    connection: local
  - name: update SRV record
    nios_srv_record:
      name: "bug.domain.com"
      port: "10000"
      priority: 1
      target: "target-bug.domain.com"
      weight: 10
      state: present
      comment: "ansible bug comment update"
      provider:
        host: "{{ infoblox_server }}"
        username: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        wapi_version: "{{ infoblox_api_version }}"
      view: "external"
    connection: local
```

##### EXPECTED RESULTS
I expect the SRV record 'comment' value to be updated.

##### ACTUAL RESULTS
Received a 'Field is not allowed for update: view' error.

https://gist.github.com/simonlg/4a917bf85507b8e91fa3d83ba59246a9

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/nios/nios_srv_record.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nios/nios_srv_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by justjais** [comment]
cc. @krisvasudevan can you please look into this issue.

**Comment by ansibot** [comment]
cc @danielmellado
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by krisvasudevan** [comment]
This issue is arising because the parameter "view" cannot be updated for an SRV record in NIOS. In the play for modifying SRV record, you need to remove the parameter "view", as below:
```
---
- hosts: all
  become: yes
  tasks:
    - name: Setup-Playbook
      setup: # Executes gather facts on all inventory

- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: create SRV record
    nios_srv_record:
      name: "bug.domain.com"
      port: "10000"
      priority: 1
      target: "target-bug.domain.com"
      weight: 10
      state: present
      comment: "ansible bug"
      provider:
        host: "{{ infoblox_server }}"
        username: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        wapi_version: "{{ infoblox_api_version }}"
      view: "external"
    connection: local
  - name: update SRV record
    nios_srv_record:
      name: "bug.domain.com"
      port: "10000"
      priority: 1
      target: "target-bug.domain.com"
      weight: 10
      state: present
      comment: "ansible bug comment update"
      provider:
        host: "{{ infoblox_server }}"
        username: "{{ infoblox_username }}"
        password: "{{ infoblox_password }}"
        wapi_version: "{{ infoblox_api_version }}"
    connection: local
```
