### ISSUE TITLE
Vmware: vmware_guest can't clone a running VM to a new VM with more vCPU

### ISSUE THREAD

**Issue by GrandeTartine** [ansible/ansible#56863]
##### SUMMARY
With ansible 2.8.0, when I try to clone a *running* VM and the new VM have more vCPU, it's fail with : fatal: [created_vm]: FAILED! => {"changed": false, "msg": "Configured cpu number is more than the cpu number of the VM, cpuHotAdd is not enabled"}

My current workaround : cloning the VM and then modifying the CPU/RAM. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
2.8.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Vcenter 6.5

##### STEPS TO REPRODUCE

ansible-playbook playbook.yml

```yaml
---
- name: VM Creation
  hosts: localhost
  gather_facts: no
  connection: local

  # Need this hack with variables because we can't give specific
  # authentication informations for each vcenter in AWX
  vars_files:
  - vars/vault
  vars:
    vcenter_name: "vcmaq3-lyo.maquette.hosting.infra"

  pre_tasks:
  - name: Set login informations for the needed Vcenter.
    include_vars:
      file: vars/{{vcenter_name}}.yml

  tasks:
  - name: Clone template to new VM
    vmware_guest:
      # Vcenter needed informations
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs | default(True) }}"

      # VM identification
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ folder_name }}"
      name: "{{ vm_name }}"

      # Template to clone
      template: "/{{ datacenter_name }}/vm{{ template_folder }}/{{ template_name }}"

      # If the VM doesn't start in 1 minute
      # something wrong, we stop de deploiement here.
      state: "poweredoff"
      state_change_timeout: 60

      # Networks is empty, else VM started with unconnected nic...
      networks: []
      # Only clone the template disk, it'll be modify later
      disk: []
      convert: "{{ vm_disks[0].type }}"
      datastore: "{{ vm_disks[0].datastore }}"
      hardware:
        memory_mb: "{{ vm_memory | default(omit) }}"
        num_cpus: "{{ vm_cpu | default(omit) }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS

VM cloned.

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/vmware-2.8/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/vmware-2.8/bin/ansible-playbook
  python version = 3.6.6 (default, Jan 26 2019, 16:53:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Vault password:
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /var/lib/awx/venv/vmware-2.8/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: test.yml **************************************************************************************************************************************************************************************************************************
Positional arguments: test.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
ask_vault_pass: True
forks: 5
1 plays in test.yml
Read vars_file 'vars/vault.dev'
Read vars_file 'vars/vault.dev'
Read vars_file 'vars/vault.dev'

PLAY [VM Creation] **************************************************************************************************************************************************************************************************************************
Read vars_file 'vars/vault.dev'

TASK [Set login informations for the needed Vcenter.] ***************************************************************************************************************************************************************************************
task path: /tmp/_8__virt_vmware_portal/test.yml:14
ok: [localhost] => {
    "ansible_facts": {
        "vcenter_hostname": "vcmaq3-lyo.maquette.hosting.infra",
        "vcenter_password": "{{ vault_vcmaq3_password }}",
        "vcenter_username": "{{ vault_vcmaq3_username }}",
        "vcenter_validate_certs": false
    },
    "ansible_included_var_files": [
        "/tmp/_8__virt_vmware_portal/vars/vcmaq3-lyo.maquette.hosting.infra.yml"
    ],
    "changed": false
}
META: ran handlers
Read vars_file 'vars/vault.dev'
Read vars_file 'vars/vault.dev'

TASK [Clone template to new VM] *************************************************************************************************************************************************************************************************************
task path: /tmp/_8__virt_vmware_portal/test.yml:19
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f4b111eb978> for vault_id=default
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f4b111eb978> for vault_id=default
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036 `" && echo ansible-tmp-1558630383.2937143-84446595937036="` echo /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036 `" ) && sleep 0'
Using module file /var/lib/awx/venv/vmware-2.8/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /root/.ansible/tmp/ansible-local-17196cng8hcb_/tmpk765_yjk TO /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036/ /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/vmware-2.8/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1558630383.2937143-84446595937036/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "MAQ-ESX6.5",
            "convert": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "DC-MAQ6",
            "datastore": null,
            "disk": [],
            "esxi_hostname": null,
            "folder": "/test",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": "2048",
                "num_cpus": "4"
            },
            "hostname": "vcmaq3-lyo.maquette.hosting.infra",
            "is_template": false,
            "linked_clone": false,
            "name": "test-2019052309",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredoff",
            "state_change_timeout": 60,
            "template": "/DC-MAQ6/vm/test/Template/MOD_DEBIAN9_FR",
            "use_instance_uuid": false,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Configured cpu number is more than the cpu number of the VM, cpuHotAdd is not enabled"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
