### ISSUE TITLE
vmware_guest: RC4122 /****.vmdk already exists

### ISSUE THREAD

**Issue by realged13** [ansible/ansible#56861]
##### SUMMARY

Deploying a new Centos7 linux vm in 2.8 no longer works due to a RF4122 error.  Works fine in 2.7

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /home/ansible28/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible28/lib/python2.7/site-packages/ansible
  executable location = /home/ansible28/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
HOST_KEY_CHECKING(/home/ansible28/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ansible28/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```
---
- hosts: dc-vcenter
  gather_facts: false
  connection: local
  roles:
    - vmware

  vars_prompt:
    - name: "vcenter_username"
      prompt: "vCenterUsername"
    - name: "vcenter_password"
      prompt: "vCenter Password"
    - name: "vmware_hostname"
      prompt: "VM Hostname"
      private: no
    - name: "vm_ip"
      prompt: "Enter VM IP Address"
      private: no
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"

  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

  # Create a VM from a template
  - name: Create CentOS 7 VM in Data Chambers VMware Environment
    vmware_guest:
      hostname: '{{ dc_vc_host }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: '{{ dc_vc_datacenter }}'
      cluster: '{{ dc_vc_cluster }}'
      folder: '{{ dc_vc_folder }}'
      name: '{{ vmware_hostname }}'
      state: poweredon
      guest_id: rhel7_64Guest
      annotation: "{{ notes }} - {{ creationdate }}"
      use_instance_uuid: true
      disk:
      - size_gb: 60
        type: thin
        datastore: '{{ dc_vc_ds }}'
      networks:
      - name: "{{ dc_vc_port_groups.servernet }}"
        ip: "{{ vm_ip }}"
        netmask: "{{ dc_vc_port_groups.servernet_mask }}"
        gateway: "{{ dc_vc_port_groups.servernet_gw }}"
        dns_servers:
        - 172.16.0.15
        - 192.1.1.15
        start_connected: true
        type: static
        allow_guest_control: true
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 172.16.0.15
        - 192.1.1.15
        domain: '{{ dc_domain }}'
        hostname: '{{ vmware_hostname }}'
      template: '{{ dc_vc_centos_temp }}'
      wait_for_ip_address: yes

```

##### EXPECTED RESULTS

VM is Created

##### ACTUAL RESULTS

```
    "msg": "Failed to create a virtual machine : Cannot complete the operation because the file or folder [DCPureSan-VVol] rfc4122.b2117e96-d5c2-4b76-b9b5-d715c60275c9/********.vmdk already exists"

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @dav1x @goneri @lparkes @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@realged13, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by GrandeTartine** [comment]
Hello.

I think  an issue is already open for this problem: https://github.com/ansible/ansible/issues/55551

**Comment by realged13** [comment]
@GrandeTartine Good info, the work around seems really dumb but I will try it.

**Comment by ansibot** [comment]
cc @pgbidkar
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by FleischKarussel** [comment]
Hey guys,
this is rather annoying, as this bug is also included in Tower if you've Upgraded to Tower 3.5.0 which requires ansible 2.8 to be installed aswell.
Just be warned. :)

**Comment by Akasurde** [comment]
@FleischKarussel Could you please share details about your playbook and VM that is being cloned ? I am not able to reproduce this error at my end. Thanks.

**Comment by Akasurde** [comment]
@realged13 Does this playbook used to work for 2.7 or earlier releases ?

needs_info

**Comment by realged13** [comment]
Yes works good for me. I had to revert back.

**Comment by Akasurde** [comment]
@realged13 Could you please provide additional details so that it will be easy to debug this issue ? Thanks.

**Comment by FleischKarussel** [comment]
> 
> 
> @FleischKarussel Could you please share details about your playbook and VM that is being cloned ? I am not able to reproduce this error at my end. Thanks.

```
  tasks:
    - name: Clone and configure
      vmware_guest:
        hostname: "{{ vmware_hostname }}"
        username: "{{ vc_user }}"
        password: "{{ vc_pass }}"
        datacenter: "{{ vmware_datacenter }}"
        datastore: "{{ vmware_datastore }}"
        folder: "{{ vmware_folder }}"
        validate_certs: no
        
        name: "{{ inventory_hostname }}"
        state: present
        template: "{{ vmware_template[vmware.type] }}"
        hardware:
          num_cpus: "{{ vmware.cpu }}"
          hotadd_cpu: yes
          hotremove_cpu: no
          memory_mb: "{{ vmware.ram|int*1024 }}"
          hotadd_memory: yes
          memory_reservation_lock: yes
        disk:
        - size_gb: "{{ vmware.disk }}"
      notify:
        - rescan disk
      register: vmfacts
      delegate_to: localhost 
```

this fails with 

```
    "msg": "Failed to create a virtual machine : Cannot complete the operation because the file or folder [datastore-name] vm-name/vm-name.vmdk already exists"
```
