### ISSUE TITLE
ipa_dnsrecord fail when TXT record already exist

### ISSUE THREAD

**Issue by jdorel** [ansible/ansible#56872]
##### SUMMARY

When a record already exists, I get `response dnsrecord_add: no modifications to be performed` and the tasks is marked as failed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ipa_dnsrecords

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

AWX 3.0.0.0

##### STEPS TO REPRODUCE

```yaml
ipa_dnsrecord:
    ipa_host: "{{ ipa.node }}"
    ipa_user: "{{ ipa.user }}"
    ipa_pass: "{{ ipa.password }}"
    state: present
    record_ttl: 10
    zone_name: "test.com"
    record_name: "_acme-challenge"
    record_type: 'TXT'
    record_value: "xxx"
    validate_certs: no
```

##### EXPECTED RESULTS

Task marked as not changed

##### ACTUAL RESULTS

```paste below
{
    "_ansible_parsed": true,
    "_ansible_item_result": true,
    "_ansible_no_log": false,
    "changed": false,
    "item": {
        "value": {
            "dns-01": {
                "resource_value": "xxx",
                "resource": "_acme-challenge",
                "record": "_acme-challenge.test.com"
            }
        },
        "key": "*.test.com"
    },
    "invocation": {
        "module_args": {
            "ipa_port": 443,
            "record_name": "_acme-challenge.test.com.",
            "record_ttl": 10,
            "ipa_prot": "https",
            "record_type": "TXT",
            "state": "present",
            "ipa_host": "xxx",
            "ipa_user": "xxx",
            "zone_name": "test.com",
            "ipa_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "record_value": "xxx",
            "ipa_timeout": 10,
            "validate_certs": false
        }
    },
    "msg": "response dnsrecord_add: no modifications to be performed",
    "_ansible_ignore_errors": null,
    "_ansible_item_label": {
        "value": {
            "dns-01": {
                "resource_value": "xxx",
                "resource": "_acme-challenge",
                "record": "_acme-challenge.test.com"
            }
        },
        "key": "*.test.com"
    }
}
```
