### ISSUE TITLE
The size of the extent is less than the minimum of 1MB

### ISSUE THREAD

**Issue by gstorme** [ansible/ansible#56910]
##### SUMMARY
When partitioning an existing partition with a value of -1 for partition_size, an error is returned `The size of the extent is less than the minimum of 1MB`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_partition

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
```

##### OS / ENVIRONMENT

Client OS is Windows 2019

##### STEPS TO REPRODUCE

```yaml
- name: Create partition
  win_partition:
    drive_letter: E
    partition_size: -1
    disk_number: 1
  register: partition_result
```

##### EXPECTED RESULTS

The partition is not resized because it's already at maximum available size, and ansible returns an `ok: [windows2019] => {"changed": false}`

##### ACTUAL RESULTS

```paste below
TASK [windows_disk : Create partition] ****************************************************************************************************************************************************************************
fatal: [windows2019]: FAILED! => {"changed": false, "msg": "Unable to change partition size: Size Not Supported\n \nExtended information:\nThe size of the extent is less than the minimum of 1MB.\n \n\nActivity ID: {da5775ec-3b99-45db-91b1-eb86cf6e2e33}"}
```

Related issue that was immediately closed after opened https://github.com/ansible/ansible/issues/55709
