### ISSUE TITLE
File module not idempotent with symlink perms

### ISSUE THREAD

**Issue by jeblair** [ansible/ansible#56928]
##### SUMMARY
Setting permissions on a symlink is not idempotent using the default value of "follow".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /home/corvus/openstack/zuul-testing/zuul-testing-env/lib/python3.6/site-packages/ansible
  executable location = /home/corvus/openstack/zuul-testing/zuul-testing-env/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT
Ubuntu Bionic (expect same behavior on any GNU/Linux)

##### STEPS TO REPRODUCE
As an unprivileged user, run:
```
sudo mkdir /tmp/source
```

Then run the following playbook (substituting your own username):

```yaml
- hosts: localhost
  tasks:
    - file:
        src: /tmp/source
        dest: /tmp/dest
        state: link
        owner: corvus
        group: corvus
    - file:
        src: /tmp/source
        dest: /tmp/dest
        state: link
        owner: corvus
        group: corvus
```

##### EXPECTED RESULTS
Both tasks should fail, since "follow" is true by default, and we're therefore asking Ansible to change the ownership of the link target.

##### ACTUAL RESULTS
Instead, the first task succeeds, creating the link, and the second task fails.  This suggests that the permissions change only happens before the link is created.  In order for this playbook to be idempotent, the file task will need to perform the permissions change after the link is created.

```paste below
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [file] ********************************************************************
changed: [localhost]

TASK [file] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: [Errno 1] Operation not permitted: b'/tmp/source'", "owner": "root", "path": "/tmp/source", "size": 4096, "state": "directory", "uid": 0}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
