### ISSUE TITLE
docker_container networks not changing network_mode

### ISSUE THREAD

**Issue by darkn3rd** [ansible/ansible#56963]
##### SUMMARY
Instead of using the network specified with `docker_container`, Ansible is changing the behavior and using a `default` network.  

It doesn't matter if `networks_cli_compatible` is set to `yes` or `no` in Ansible 2.8.  This behavior is also in Ansible 2.7.x as well as Ansible 2.8.

```
$ docker inspect wordpress | jq --raw-output '.[].HostConfig.NetworkMode'
default
$ docker inspect db | jq --raw-output '.[].HostConfig.NetworkMode'
default
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- docker_container

##### ANSIBLE VERSION

```bash
$ ansible --version
ansible 2.8.0
  config file = None
  configured module search path = ['/Users/joaquin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/joaquin/.pyenv/versions/3.7.1/lib/python3.7/site-packages/ansible
  executable location = /Users/joaquin/.pyenv/versions/3.7.1/bin/ansible
  python version = 3.7.1 (default, Nov 28 2018, 04:21:18) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

```$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B2107
```
```
$ docker --version
Docker version 18.09.2, build 6247962
```

```
$ pip list | grep docker
docker             4.0.1 
```

##### STEPS TO REPRODUCE
```bash
./docker_playbook.yml
```

```yaml
#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  gather_facts: no
  vars:
    docker_volume: db_data
    docker_network: wordpress_net
    db_name: db
    wp_name: wordpress
    wp_host_port: "{{ lookup('env','WORDPRESS_PORT') | default(8080)}}"
    wp_container_port: 80
  tasks:
    - name: "Create a Volume"
      docker_volume:
        name: "{{ docker_volume }}"
    - name: "Create a network"
      docker_network:
        name: "{{ docker_network }}"
    - name: "Launch database container"
      docker_container:
        name: "{{ db_name }}"
        image: mysql:5.7
        volumes:
          - "{{ docker_volume }}:/var/lib/mysql:rw"
        restart: true
        networks:
          - name: "{{ docker_network }}"
        networks_cli_compatible: no
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    - name: "Launch wordpress container"
      docker_container:
        name: "{{ wp_name }}"
        image: wordpress:latest
        ports:
          - "{{ wp_host_port }}:{{ wp_container_port }}"
        restart: true
        networks:
          - name: "{{ docker_network }}"
        networks_cli_compatible: yes
        env:
          WORDPRESS_DB_HOST: "{{ db_name }}:3306"
          WORDPRESS_DB_PASSWORD: wordpress
```

##### EXPECTED RESULTS

I expected that the `NetworkMode` would be set to the one I specified, e.g. `wordpress_net`:

```
$ docker inspect wordpress | jq --raw-output '.[].HostConfig.NetworkMode' 
wordpress_net
$ docker inspect db | jq --raw-output '.[].HostConfig.NetworkMode'
wordpress_net
```

##### ACTUAL RESULTS

Regardless of the `networks_cli_compatible` setting, the `NetworkMode` is set to `default`.

```
$ docker inspect wordpress | jq --raw-output '.[].HostConfig.NetworkMode' 
default
$ docker inspect db | jq --raw-output '.[].HostConfig.NetworkMode'
default
```

##### NOTES

I have recreated this solution using both the Docker CLI `docker` and using Docker Python SDK, and in both cases, they appropriately set the `NetworkMode`.  The behavior of Ansible `docker_container` module is inconsistent with both Docker CLI and Docker Python SDK.

**Docker CLI Example (positive results):**
```bash
#!/usr/bin/env bash
WORDPRESS_PORT=${WORDPRESS_PORT:-'8080'}
MYSQL_VOLUME="db_data"
NETWORK_NAME="wordpress_net"

docker volume create -d local --name $MYSQL_VOLUME

docker network list | grep -q $NETWORK_NAME || \
  docker network create $NETWORK_NAME

docker ps -f name=db -q | xargs docker stop && \
  docker ps -f name=db -aq | xargs docker rm

docker run -d \
  -v $MYSQL_VOLUME:/var/lib/mysql:rw \
  --network=$NETWORK_NAME \
  --restart=always \
  -e MYSQL_ROOT_PASSWORD="wordpress" \
  -e MYSQL_PASSWORD="wordpress" \
  -e MYSQL_USER="wordpress" \
  -e MYSQL_DATABASE="wordpress" \
  --name "db" \
  "mysql:5.7"

docker ps -f name=wordpress -q | xargs docker stop && \
  docker ps -f name=wordpress -aq | xargs docker rm

docker run -d \
  --network=$NETWORK_NAME \
  -p "$WORDPRESS_PORT:80" \
  --restart=always \
  -e WORDPRESS_DB_HOST="db:3306" \
  -e WORDPRESS_DB_PASSWORD="wordpress" \
  --name "wordpress" \
  "wordpress:latest"
```

```
$ docker inspect wordpress | jq --raw-output '.[].HostConfig.NetworkMode' 
wordpress_net
$ docker inspect db | jq --raw-output '.[].HostConfig.NetworkMode'
wordpress_net
```

**Docker Python SDK Example (positive results):**

```python
#!/usr/bin/env python3
import docker
import os

wordpress_port = os.environ.get('WORDPRESS_PORT') or '8080'
mysql_volume = "db_data"
network_name = "wordpress_net"

d = docker.from_env()

d.volumes.create(mysql_volume, driver='local')
if not d.networks.list(network_name):
  d.networks.create(network_name, driver='bridge')

# Stop any 'db' or 'wordpress' containers
containers = [c for c in d.containers.list() if c.name in ['db', 'wordpress']]
if containers:
    for container in containers:
        container.stop()

# Remove any 'db' or 'wordpress' containers
containers = [c for c in d.containers.list(all=True) if c.name in ['db', 'wordpress']]
if containers:
    for container in containers:
        container.remove()

d.containers.run( 'mysql:5.7',
                  detach=True,
                  network=network_name,
                  restart_policy={"Name": "always"},
                  volumes={
                    mysql_volume: {'bind': '/var/lib/mysql', 'mode': 'rw'}
                  },
                  environment=[
                   'MYSQL_ROOT_PASSWORD=wordpress',
                   'MYSQL_PASSWORD=wordpress',
                   'MYSQL_USER=wordpress',
                   'MYSQL_DATABASE=wordpress'
                  ],
                  name='db'
                )

d.containers.run( 'wordpress:latest',
                  detach=True,
                  network=network_name,
                  restart_policy={"Name": "always"},
                  ports={'80/tcp': wordpress_port},
                  environment=[
                   'WORDPRESS_DB_HOST=db:3306',
                   'WORDPRESS_DB_PASSWORD=wordpress',
                   'MYSQL_USER=wordpress',
                   'MYSQL_DATABASE=wordpress'
                  ],
                  name='wordpress'
                )
```

```
$ docker inspect wordpress | jq --raw-output '.[].HostConfig.NetworkMode' 
wordpress_net
$ docker inspect db | jq --raw-output '.[].HostConfig.NetworkMode'
wordpress_net
```
