### ISSUE TITLE
VMware: vmware_guest_powerstate fails when VM name is too long

### ISSUE THREAD

**Issue by xgy560501** [ansible/ansible#56987]
##### SUMMARY

When user has a VM with long name then vmware_guest_powerstate fails with - 

```
Schedule task for vm formentor_SHsiebdb01 for operation restarted at 27/05/2019 21:00' is invalid or exceeds the maximum number of characters permitted
``` 
warning
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_powerstate

##### ANSIBLE VERSION

```paste below
2.8
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
  - name: reboot at time
    vmware_guest_powerstate:
      hostname: ********
      username: ********
      password: "*******"
      validate_certs: no
      folder: "/"
      name: "formentor_SHsiebdb01"
      state: restarted
      scheduled_at: "27/05/2019 14:20"

```

##### ACTUAL RESULTS

```paste below

```
