### ISSUE TITLE
openvswitch_bridge does not update vlan on existing bridge.

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#57018]
##### SUMMARY

When creating a fake bridge with a parent, this module takes a `vlan` parameter. But when the bridge already exists, this module ignore the `vlan` parameter instead of updating the existing bridge.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openvswitch_bridge

##### ANSIBLE VERSION

```paste below
2.8.0
```

##### STEPS TO REPRODUCE

```yaml
- name: create lxd bridges
  openvswitch_bridge:
    bridge: "fake-br"
    parent: "br0"
    vlan: "100"

- name: update lxd bridges
  openvswitch_bridge:
    bridge: "fake-br"
    parent: "br0"
    vlan: "200"
```

##### EXPECTED RESULTS

The first command create the bridge, the second one update the bridge and set the vlan to 200.

The bridge can be updated using the following command:

`ovs-vsctl set port fake-br tag=200`

##### ACTUAL RESULTS

`vlan` parameter is ignored and the command reports 'no change'
