### ISSUE TITLE
when conditional is utterly broken when applied to include_roles, when used within a role.

### ISSUE THREAD

**Issue by Testicule** [ansible/ansible#57017]
##### SUMMARY

If a playbook has include_role, with a when conditional to test a var, which calls another role when satisified... it works, but if the included role does the same thing, the 2nd include_role is *never* executed, even when the when clause is true.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role/when

##### ANSIBLE VERSION

```
ansible --version
ansible 2.8.0
  config file = /mnt/dicker/awx/projects/vorpal/ansible.cfg
  configured module search path = ['/home/jss/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 13:41:07) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```
Also occurs on ansible 2.7

##### CONFIGURATION

```
not relevant
```

##### OS / ENVIRONMENT

Seen on EL7 with ansible 2.7 and fedora with ansible 2.8.0

##### STEPS TO REPRODUCE

```yaml

Playbook "role-test.yml":

- hosts: "{{ hostgroups }}"
  tasks:
    - name: "playbook - run testrole1 - with jobs=run-testrole2, so testrole1 calls testrole2."
      include_role:
        name: testrole1
        public: no
      vars:
        jobs: "run-testrole2"

main.yml from role "testrole1":

- name: "This task has same conditional as the include for testrole 2."
  debug: 
    msg: "jobs={{ jobs }}. If this task runs then next task MUST include testrole2!! The next task CANNOT SKIP!!"
  when:
    - ( "run-testrole2" in jobs )

- name: "If jobs contains run-testrole2 then run testrole2 - passing it jobs=meh."
  include_role:
    name: testrole2
    public: no
  vars:
    jobs: "meh"
  when:
    - ( "run-testrole2" in jobs )

It doesnt matter whats in testrole2, as it doesnt get included, but, for testing purposes, this will suffice:
main.yml from role "testrole2":

- name: "Report jobs var in testrole2."
  debug:
    var: jobs

```

##### EXPECTED RESULTS

Playbook calls testrole1 with jobs var = run-testrole2
testrole1:
   -  when clause is used so as  jobs=run-testrole2 then print value of jobs (run-testrole2) so we can see it has received correct value.
   -  when clause is used so as jobs=run-testrole2 then testrole1 includes testrole2 passing it jobs var = meh
testrole2:
   - prints value of jobs as "meh".

##### ACTUAL RESULTS

Playbook calls testrole1 with jobs var = run-testrole2
testrole1:
   -  when clause is used so as jobs=run-testrole2 then print value of jobs (run-testrole2) so we can see it has received correct value. This WORKS
   -  when clause is used so as jobs=run-testrole2 then testrole1 includes testrole2 passing it jobs var = meh. This DOES NOT WORK.
testrole2 is not included. -vvvv shows the include_role task is skipped due to failing conditonal, even though the conditional is the *exact same test* as on the previous task which was *not skipped*.

```
ansible-playbook -i ./inventory-vorpal.yml ./role-test.yml --extra-vars='{"hostgroups":"voltaire"}'

PLAY [voltaire] *****************************************************************************************************************************************************************************

TASK [playbook - run testrole1 - with jobs=run-testrole2, so testrole1 calls testrole2.] ****************************************************************************************************

TASK [testrole1 : This task has same conditional as the include for testrole 2.] ************************************************************************************************************
ok: [voltaire] =>
  msg: jobs=run-testrole2. If this task runs then next task MUST include testrole2!! The next task CANNOT SKIP!!

TASK [If jobs contains run-testrole2 then run testrole2 - passing it jobs=meh.] *************************************************************************************************************
skipping: [voltaire]

PLAY RECAP **********************************************************************************************************************************************************************************
voltaire                   : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0


```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Testicule** [comment]
I thought the purpose of roles was to reduce code duplication and increase re-use, but how is anyone supposed to accomplish this, when you hit bugs like this as soon as you have one role trying to all another?

**Comment by flowerysong** [comment]
```
- name: "If jobs contains run-testrole2 then run testrole2 - passing it jobs=meh."
  include_role:
    name: testrole2
    public: no
  vars:
    jobs: "meh"
  when:
    - ( "run-testrole2" in jobs )
```

This condition can *never* be true, because `jobs` is explicitly set to 'meh' for this task. You should avoid generic variable names, or at least not reuse them for different purposes in interrelated roles.

**Comment by samdoran** [comment]
As @flowerysong pointed out, the problem is the `jobs` variable is being overwritten to `meh` for this task, and the conditional then evaluates to `False`, preventing the role from being included.

The best way to avoid collisions like this is to prefix variables used in roles with the role name, e.g., `testrole2_jobs`.

```yaml
- hosts: localhost
  tasks:
    - include_role:
        name: testrole2
      vars:
        testrole2_jobs: run-testrole3
```

```yaml
# testrole2/tasks/main.yml
- debug:
    msg: in testrole2

- debug:
    var: testrole2_jobs
  tags: debug

- include_role:
    name: testrole3
  vars:
    testrole3_jobs: meh
  when: ("run-testrole3" in testrole2_jobs)
```

```yml
# testrole3/tasks/main.yml
- debug:
    msg: in testrole3
  tags: debug

- debug:
    var: testrole3_jobs
  tags: debug
```

For further help with this issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
