### ISSUE TITLE
kubectl community plugin not found but known

### ISSUE THREAD

**Issue by david-freistrom** [ansible/ansible#57046]
##### SUMMARY
When I try to use kubectl plugin I get the follwing error:

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

But If I try to verify it it works as expected:

> ansible-doc -t connection kubectl
> KUBECTL    (/usr/lib/python3.7/site-packages/ansible/plugins/connection/kubectl.py)
> ...

##### ISSUE TYPE
Plugin issue

##### COMPONENT NAME
kubectl

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:45:16) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Linux doha 5.0.11-200.fc29.x86_64 #1 SMP Thu May 2 14:25:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

> ansible localhost -m kubectl

```yaml
- name: Migrate database
  kubectl:
    kubectl_kubeconfig: "{{ playbook_dir }}/files/kubeconfig"
    kubectl_namespace: "{{ awx.namespace }}"
    kubectl_container: ansible-tower-management
    kubectl_extra_args: "-- bash -c 'awx-manage migrate --noinput'"
  delegate_to: localhost
  tags: awx
```

##### EXPECTED RESULTS
Running 
```bash
kubectl -n NAMESPACE exec ansible-tower-management -- bash -c 'awx-manage migrate --noinput'
```

##### ACTUAL RESULTS
```bash
[user@localhost]$ ansible-playbook --ask-vault-pass -i inventories/foo/hosts foo.yml --tags awx -vvvvv
ansible-playbook 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.7.3 (default, May 11 2019, 00:45:16) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
Using /etc/ansible/ansible.cfg as config file
Vault password: 
setting up inventory plugins
host_list declined parsing /home/user/projects/ansible/inventories/foo/hosts as it did not pass it's verify_file() method
script declined parsing /home/user/projects/ansible/inventories/foo/hosts as it did not pass it's verify_file() method
auto declined parsing /home/user/projects/ansible/inventories/foo/hosts as it did not pass it's verify_file() method
Parsed /home/user/projects/ansible/inventories/foo/hosts inventory source with ini plugin
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to be in '/home/user/projects/ansible/roles/awx/tasks/main.yml': line 309, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Migrate database
  ^ here
```
