### ISSUE TITLE
consul:  state=absent is not working

### ISSUE THREAD

**Issue by c35sys** [ansible/ansible#57068]
##### SUMMARY
In the playbook, the `state: absent` in consul module is not working.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

consul

##### ANSIBLE VERSION

```
ansible 2.7.11
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.virtualenvs/ansible2.7/local/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/.virtualenvs/ansible2.7/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT
- Ubuntu 18.04
- Consul 1.5.1 with the following ACL
```
# Enable ACLs with deny rule by default
acl {
  enabled = true
  default_policy = "deny"
  tokens {
    master = "11111111-2222-3333-5555-666666666666"
    agent = "11111111-2222-3333-5555-666666666666"
  }
}
```

##### STEPS TO REPRODUCE

Create the service `MyService` in consul.

```yaml
  - name: Register MyService
    consul:
      host: "{{ consul_server }}"
      port: "{{ consul_port }}"
      scheme: "{{ consul_scheme }}"
      validate_certs: "{{ consul_validate_certs }}"
      token: "{{ consul_token }}"
      service_id: MyService
      service_name: MyService
      service_address: myservicehost
      service_port: 1111
      tags:
        - ansible
        - node
      state: absent

```

##### EXPECTED RESULTS

The service `MyService` should be gone from consul.

##### ACTUAL RESULTS

The service `MyService` is still present in consul.

For information, I'm able to delete the service `MyService` using `consul services deregister -id=MyService` and the same token.

I checked if #34628 was implemented in my ansible version and the answer is yes. 

```paste below

```
