### ISSUE TITLE
traceback: AWS_REGIONS not defined 

### ISSUE THREAD

**Issue by itsonlycode** [ansible/ansible#5706]
PLAY [Create management servers] *********************************************\* 

GATHERING FACTS **************************************************************\* 
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1390315627.69-250982828866091 && chmod a+rx $HOME/.ansible/tmp/ansible-1390315627.69-250982828866091 && echo $HOME/.ansible/tmp/ansible-1390315627.69-250982828866091']
<127.0.0.1> REMOTE_MODULE setup 
<127.0.0.1> PUT /tmp/tmpER1J6b TO /home/rudolf/.ansible/tmp/ansible-1390315627.69-250982828866091/setup
<127.0.0.1> PUT /tmp/tmp27EVTw TO /home/rudolf/.ansible/tmp/ansible-1390315627.69-250982828866091/arguments
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/rudolf/.ansible/tmp/ansible-1390315627.69-250982828866091/setup /home/rudolf/.ansible/tmp/ansible-1390315627.69-250982828866091/arguments; rm -rf /home/rudolf/.ansible/tmp/ansible-1390315627.69-250982828866091/ >/dev/null 2>&1']
ok: [127.0.0.1]

TASK: [Launch instance] ******************************************************\* 
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1390315628.35-98982665486202 && chmod a+rx $HOME/.ansible/tmp/ansible-1390315628.35-98982665486202 && echo $HOME/.ansible/tmp/ansible-1390315628.35-98982665486202']
<127.0.0.1> REMOTE_MODULE ec2 image=ami-ad184ac4 keypair=AmazonKey instance_type=m1.small region=us-east-1 group=quick-start-1 
<127.0.0.1> PUT /tmp/tmppyEt6E TO /home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/ec2
<127.0.0.1> PUT /tmp/tmp4HifQr TO /home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/arguments
<127.0.0.1> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/ec2 /home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/arguments; rm -rf /home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/ >/dev/null 2>&1']
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/ec2", line 1731, in <module>
    main()
  File "/home/rudolf/.ansible/tmp/ansible-1390315628.35-98982665486202/ec2", line 622, in main
    region = dict(aliases=['aws_region', 'ec2_region'], choices=AWS_REGIONS),
NameError: global name 'AWS_REGIONS' is not defined

FATAL: all hosts have already failed -- aborting

```

---
 - name: Create management servers
   hosts: 127.0.0.1
   connection: local
   tasks:
     - name: Launch instance
       local_action:
         region: us-east-1
         group: quick-start-1
         module: ec2
         keypair: AmazonKey
         instance_type: m1.small
         image: ami-ad184ac4
         count: 1
         wait: yes
       register: ec2

     - name: Add tag
       local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
       with_items: ec2.instances
       args:
         tags:
           Name: DataAnalysis

     - name: Wait for SSH
       pause: minutes=1
```
