### ISSUE TITLE
Issue with nested groups in YAML

### ISSUE THREAD

**Issue by zarbafian** [ansible/ansible#57070]
##### SUMMARY

Hosts of a specific group are also present in other groups.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Groups in YAML inventory

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pzarbafian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:24:06) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
```

##### CONFIGURATION

```paste below
Empty
```

##### OS / ENVIRONMENT

Fedora 28

##### STEPS TO REPRODUCE

ansible -i debug.yml -m debug -a 'var=groups' localhost
(content of debug.yml below)

```yaml
all:
    children:
        group_1:
            children:
                production:
                    hosts:
                        g1_prod_host1:
                        g1_prod_host2:
                        g1_prod_host3:
        group_2:
            children:
                staging:
                    hosts:
                        g2_stag_host1:
                        g2_stag_host2:
                production:
                    hosts:
                        g2_prod_host1:
                        g2_prod_host2:
                        g2_prod_host3:
                development:
                    hosts:
                        g2_dev_host1:
                        g2_dev_host2:
```

##### EXPECTED RESULTS

The group group_2 should only contain hosts g2_xxx and group_1 should only contain hosts g1_xxx.

##### ACTUAL RESULTS

The group group_2 contains hosts of group_1, and group_1 contains hosts in group_2.

```paste below
localhost | SUCCESS => {
    "groups": {
        "all": [
            "g2_dev_host1", 
            "g2_dev_host2", 
            "g2_stag_host1", 
            "g2_stag_host2", 
            "g2_prod_host3", 
            "g2_prod_host2", 
            "g2_prod_host1", 
            "g1_prod_host2", 
            "g1_prod_host3", 
            "g1_prod_host1"
        ], 
        "development": [
            "g2_dev_host1", 
            "g2_dev_host2"
        ], 
        "group_1": [
            "g2_prod_host3", 
            "g2_prod_host2", 
            "g2_prod_host1", 
            "g1_prod_host2", 
            "g1_prod_host3", 
            "g1_prod_host1"
        ], 
        "group_2": [
            "g2_stag_host1", 
            "g2_stag_host2", 
            "g2_dev_host1", 
            "g2_dev_host2", 
            "g2_prod_host3", 
            "g2_prod_host2", 
            "g2_prod_host1", 
            "g1_prod_host2", 
            "g1_prod_host3", 
            "g1_prod_host1"
        ], 
        "production": [
            "g2_prod_host3", 
            "g2_prod_host2", 
            "g2_prod_host1", 
            "g1_prod_host2", 
            "g1_prod_host3", 
            "g1_prod_host1"
        ], 
        "staging": [
            "g2_stag_host1", 
            "g2_stag_host2"
        ], 
        "ungrouped": []
    }
}
```
