### ISSUE TITLE
__state: absent not working with extra attributes besides ID/Key

### ISSUE THREAD

**Issue by sfloresk** [ansible/ansible#57084]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nso_config

##### ANSIBLE VERSION

```
ansible 2.7.9
```

##### OS / ENVIRONMENT
MAC OS

##### STEPS TO REPRODUCE
This works
```yaml
- name: Create L3VPN
  nso_config:
    url: http://localhost:8080/jsonrpc
    username: username
    password: password
    data:
      l3vpn:vpn:
        l3vpn:
        - name: company
          route-distinguisher: 999
          endpoint:
          - id: branch-office3
            __state: absent
        __state: in-sync
```
This does not work:

```yaml
- name: Create L3VPN
  nso_config:
    url: http://localhost:8080/jsonrpc
    username: username
    password: password
    data:
      l3vpn:vpn:
        l3vpn:
        - name: company
          route-distinguisher: 999
          endpoint:
          - id: branch-office3
            ce-device: ce1
            ce-interface: GigabitEthernet0/11
            ip-network: 10.7.7.0/24
            bandwidth: 6000000
            as-number: 65102
            __state: absent
        __state: in-sync
```

##### EXPECTED RESULTS
Configuration should be removed

##### ACTUAL RESULTS
Configuration is not removed, and it is applied if it doesn't exist.
