### ISSUE TITLE
os_user_role module fails in multidomain environment when assigning role to group

### ISSUE THREAD

**Issue by dkt26111** [ansible/ansible#57099]
##### SUMMARY
In an OpenStack environment with multiple domains and when using keystone (identity) API v3, os_user_role module fails with "Group mygroup is not valid" when trying to assign a role to a group that exists only in a specific domain.

This is similar to #42911.  The main difference is that it also needs to include domain parameter when looking up a group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_user_role

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dtruong/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
On Ansible and control host side, no specific platform dependencies.

In order to reproduce this issue, on the OpenStack side (which the os_user module is utilized against):

* must be using Identity API v3
* must be a multidomain environment (ie. at least two domains must exist)
* a group must only exist in one domain and not in the other

##### STEPS TO REPRODUCE
```yaml
---
- hosts: inception
  gather_facts: no
  any_errors_fatal: yes
  tasks:
    - name: Assign admin role to mygroup
      os_user_role:
        auth_type: password
        auth:
          auth_url: "https://openstack.api.endpoint.url:5000/v3"
          username: admin
          password: "{{ admin_password }}"
          project_name: admin
          project_domain_name: default
          user_domain_name: default
        domain: mydomain
        group: mygroup
        role: admin
        project: myproject
```

##### EXPECTED RESULTS
User role is modified

##### ACTUAL RESULTS

```paste below
TASK [Assign admin role to mygroup] ***************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Group mygroup is not valid"}
```
The problem is that groups are retrieved without the domain parameter.  In this case the group only exists in a specific domain, so it cannot be found.  The call to get_group (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_user_role.py#L154) needs to pass in domain_id like it is done for get_user (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_user_role.py#L146).
