### ISSUE TITLE
nxos_vlan: purge param not working as documented

### ISSUE THREAD

**Issue by navisidhu** [ansible/ansible#57101]
##### SUMMARY
The `purge: yes` param for `nxos_vlan` module is not working as intended.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`nxos_vlan`

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg
  configured module search path = ['/home/navisidhu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/navisidhu/.local/lib/python3.6/site-packages/ansible
  executable location = /home/navisidhu/.local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = ['/home/navisidhu/Documents/Development/AnsibleNXOS/hosts']
DEFAULT_JINJA2_EXTENSIONS(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_ROLES_PATH(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = ['/home/navisidhu/Documents/Development/AnsibleNXOS/roles']
DISPLAY_SKIPPED_HOSTS(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = 75
RETRY_FILES_ENABLED(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/navisidhu/Documents/Development/AnsibleNXOS/ansible.cfg) = always
```

##### OS / ENVIRONMENT
```
❯ uname -a
Linux DevLappy 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

❯ lsb_release -a
No LSB modules are available.
Distributor ID: elementary
Description:  elementary OS 5.0 Juno
Release:  5.0
Codename: juno
```

##### STEPS TO REPRODUCE
Original Dataset:
```yaml
site_vlans:
  - { vlan_name: NET_TEMP_VLAN_A, vlan_id: 10, tags: ['cpe','firewall'] }
  - { vlan_name: NET_TEMP_VLAN_B, vlan_id: 11, tags: ['cpe','firewall'] }
  - { vlan_name: NET_TEMP_VLAN_C, vlan_id: 12, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client21, vlan_id: 21, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client22, vlan_id: 22, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client23, vlan_id: 23, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client24, vlan_id: 24, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client25, vlan_id: 25, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client26, vlan_id: 26, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client27, vlan_id: 27, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client28, vlan_id: 28, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client29, vlan_id: 29, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client30, vlan_id: 30, tags: ['cpe','firewall'] }
```
Role `cisco-nxos-switch`:

```yaml
- name: Create/Modify VLANs
  nxos_vlan:
    vlan_id: "{{ item.vlan_id }}"
    name: "{{ item.vlan_name }}_{{ item.vlan_id }}"
    admin_state: up
  loop: "{{ site_vlans | flatten(levels=1) }}"
  when:
    - item.tags is defined
    - '"badname" not in item.tags'

- name: Create Aggregate VLANs List
  set_fact:
    used_vlans:  "{{ used_vlans | default([]) +  [ {'vlan_id': item.vlan_id | string } ] }}"
  loop: "{{ site_vlans }}"

- name: Debug Aggregate VLANs List Type
  debug:
    msg: "{{ used_vlans | type_debug }}"

- name: Debug Aggregate VLANs List Data
  debug:
    msg: "{{ used_vlans }}"

# - name: Remove unused VLANs
#   nxos_vlan:
#     aggregate: "{{ used_vlans }}"
#     purge: true
```

The first run on an unconfigured switch should just create the VLANs.

Output: https://gist.github.com/navisidhu/a32462ec1099c78ee23f480816fc5ded#file-playbookinitialrun-txt

Now if we remove the temporary VLANs:

```yaml
site_vlans:
  - { vlan_name: NET_VDC_Client21, vlan_id: 21, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client22, vlan_id: 22, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client23, vlan_id: 23, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client24, vlan_id: 24, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client25, vlan_id: 25, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client26, vlan_id: 26, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client27, vlan_id: 27, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client28, vlan_id: 28, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client29, vlan_id: 29, tags: ['cpe','firewall'] }
  - { vlan_name: NET_VDC_Client30, vlan_id: 30, tags: ['cpe','firewall'] }
```
and enable the cleanup block:
```yaml
- name: Create/Modify VLANs
  nxos_vlan:
    vlan_id: "{{ item.vlan_id }}"
    name: "{{ item.vlan_name }}_{{ item.vlan_id }}"
    admin_state: up
  loop: "{{ site_vlans | flatten(levels=1) }}"
  when:
    - item.tags is defined
    - '"badname" not in item.tags'

- name: Create Aggregate VLANs List
  set_fact:
    used_vlans:  "{{ used_vlans | default([]) +  [ {'vlan_id': item.vlan_id | string } ] }}"
  loop: "{{ site_vlans }}"

- name: Debug Aggregate VLANs List Type
  debug:
    msg: "{{ used_vlans | type_debug }}"

- name: Debug Aggregate VLANs List Data
  debug:
    msg: "{{ used_vlans }}"

- name: Remove unused VLANs
  nxos_vlan:
    aggregate: "{{ used_vlans }}"
    purge: true
```
The output is: 

##### EXPECTED RESULTS
On the second run VLANs (listed below) should get removed from the switches:
```
  - { vlan_name: NET_TEMP_VLAN_A, vlan_id: 10, tags: ['cpe','firewall'] }
  - { vlan_name: NET_TEMP_VLAN_B, vlan_id: 11, tags: ['cpe','firewall'] }
  - { vlan_name: NET_TEMP_VLAN_C, vlan_id: 12, tags: ['cpe','firewall'] }
```

##### ACTUAL RESULTS
The playbook fails with the following message:
```
TASK [ccl-nxos-switch : Remove unused VLANs] ***************************************************************
"fatal: [A04-N9K-A]: FAILED! => {"changed": false, "msg": "'input'"}"
```
Verbose output: https://gist.github.com/navisidhu/a32462ec1099c78ee23f480816fc5ded#file-playbookcleanuprunverbose-txt
