### ISSUE TITLE
ec2_ami does not support "create volume" permissions

### ISSUE THREAD

**Issue by aghassemlouei** [ansible/ansible#57121]
##### SUMMARY
The [ec2_ami](https://docs.ansible.com/ansible/latest/modules/ec2_ami_module.html) module does not support sharing the associated volume when launch permissions are modified. This can be handled outside of ansible via awscli similarly here: 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html#sharingamis-aws-cli

While the command is invoking `modify-snapshot-attributes`, it does not appear as though the `ec2_snapshot` module handles modifying permissions whatsoever so that would leave `ec2_ami` as the more reasonable place to add this feature. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_ami

##### ADDITIONAL INFORMATION
Given that the `ec2_ami` module already supporting sharing the AMI and the AWS Console already groups the image and snapshot settings together, it would be beneficial to have the setting within the `ec2_ami` module as a flag that could be enabled every time the launch permissions are adjusted. Proposed handling this through something named `snapshot_permissions` or something similar.

```yaml
- name: Share with Accounts
  ec2_ami:
    launch_permissions:
      user_ids: "12345678"
    image_id: "ami-12345"
    snapshot_permissions: true 
    region: "us-west-1"
```
