### ISSUE TITLE
win_xml xpath issue

### ISSUE THREAD

**Issue by emper0r** [ansible/ansible#57171]
##### SUMMARY
Ansible not changing xml attribute

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
!component + lib/ansible/modules/windows/win_xml.py

##### ANSIBLE VERSION

```
ansible 2.7.9
python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] 
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
file: foo.xml
```
<configuration>
 <runtime>
   <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
     <dependentAssembly>
       <assemblyIdentity name="MySql.Data" publicKeyToken="c5687fc88969c44d" />
       <bindingRedirect oldVersion="5.2.7.0" newVersion="6.10.8.0" />
         <codeBase version="6.10.8.0" href="mysql/MySql.Data.6.10.8.dll" />
       </dependentAssembly>
   </assemblyBinding>
 </runtime>
</configuration>
```

file: main.yaml
```
name: TEST CASE
  win_xml:
    path: "foo.xml"
    xpath: /configuration/runtime/assemblyBinding/dependentAssembly/bindingRedirect
    fragment: '86.10.8.0'
    attribute: newVersion
    type: attribute
```

##### EXPECTED RESULTS
must change it -> newVersion="6.10.8.0" into newVersion="86.10.8.0"

##### ACTUAL RESULTS
Ansible not changing xml attribute

```
None output, all green like nothing changed.
```
