### ISSUE TITLE
synchronize does not support rsync:// correctly

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#57182]
##### SUMMARY
Documentation examples show the use of `rsync://` to use the rsync protocol to connect instead of SSH. However, in trying to do use a `src: rsync://host::module/path` it fails as rsync* doesn't know how to process rsync://. The rsync command receives the `rsync://` prefix which breaks. Removing the protocol from the rsync command works.

CentOS 6 rsync at least.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
synchronize_module

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.7.10
  config file = /Users/dkimsey/ansible/ansible.cfg
  configured module search path = ['/Users/dkimsey/ansible/library']
  ansible python module location = /Users/dkimsey/.virtualenvs/ansible-2.7/lib/python3.7/site-packages/ansible
  executable location = /Users/dkimsey/.virtualenvs/ansible-2.7/bin/ansible
  python version = 3.7.3 (default, May  1 2019, 10:48:04) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/dkimsey/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/dkimsey/ansible/ansible.cfg) = True
CACHE_PLUGIN(/Users/dkimsey/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/dkimsey/ansible/ansible.cfg) = .cache/
CACHE_PLUGIN_TIMEOUT(/Users/dkimsey/ansible/ansible.cfg) = 79200
DEFAULT_ACTION_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/action']
DEFAULT_BECOME(/Users/dkimsey/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/Users/dkimsey/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/filter']
DEFAULT_FORKS(/Users/dkimsey/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/Users/dkimsey/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/inventory/stg']
DEFAULT_INVENTORY_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(/Users/dkimsey/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_LOG_PATH(/Users/dkimsey/ansible/ansible.cfg) = /Users/dkimsey/ansible/log/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(/Users/dkimsey/ansible/ansible.cfg) = Ansible managed file **do not edit**
DEFAULT_MODULE_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/library']
DEFAULT_STRATEGY_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/strategy']
DEFAULT_TIMEOUT(/Users/dkimsey/ansible/ansible.cfg) = 120
DEFAULT_VARS_PLUGIN_PATH(/Users/dkimsey/ansible/ansible.cfg) = ['/Users/dkimsey/ansible/plugins/vars']
DEFAULT_VAULT_PASSWORD_FILE(/Users/dkimsey/ansible/ansible.cfg) = /Users/dkimsey/.ansible_vault_password_file
DISPLAY_SKIPPED_HOSTS(/Users/dkimsey/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/dkimsey/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/dkimsey/ansible/ansible.cfg) = ['auto', 'host_list', 'script', 'yaml', 'ini', 'ng_app_instance', 'aws_ec2']
```

##### STEPS TO REPRODUCE

```yaml
- name: Publish to Production
  hosts: all
  vars:
    web_root: /var/www/updates/repos/
  tasks:
    - name: Pull packages from Staging into Production
      synchronize:
        mode: pull
        archive: true
        copy_links: true
        delete: true
        src: rsync://remote.example::updates/repos/
        dest: '{{web_root}}'
      delegate_to: '{{inventory_hostname}}'
      #echo rsync {{"--dry-run" if ansible_check_mode else ""}} -v -a -L --delete-after "remote.example::updates/repos/" "{{web_root}}"
```

##### EXPECTED RESULTS
rsync should sync the two remotes correctly. Removing the `rsync://` prefix from the src and running manually works correctly.

##### ACTUAL RESULTS

```paste below
PLAY [Publish to Production] **********************************************************************
Thursday 30 May 2019  09:48:46 -0500 (0:00:00.453)       0:00:00.453 **********

TASK [Pull packages from Staging into Production] **********************************************************************
fatal: [foo.example.com -> foo.example.com]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --dry-run --delete-after --copy-links --archive --out-format=<<CHANGED>>%i %n%L rsync://remote.example::updates/repos/ /var/www/updates/repos/", "msg": "ssh: Could not resolve hostname rsync: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [receiver]\nrsync error: error in rsync protocol data stream (code 12) at io.c(600) [receiver=3.0.6]\n", "rc": 12}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/synchronize.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/synchronize.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tima
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dekimsey** [comment]
FWIW, I was able to get this working correctly by just stripping the prefix from the paths.

```
@@ -531,10 +569,30 @@
     if '@' not in dest:
         dest = os.path.expanduser(dest)

+    source = source.replace('rsync://', '', 1)
+    dest = dest.replace('rsync://', '', 1)
+
     cmd.append(source)
     cmd.append(dest)
```

**Comment by sivel** [comment]
It has been a long time since I have dealt with rsync daemons, however I just wanted to provide the small snipped from the man page:

> There are two different ways for rsync to contact a remote system: using a remote-shell program as the transport (such as ssh or rsh) or contacting an rsync daemon directly via TCP. The remote-shell transport is used whenever the source or destination path contains a single colon (:) separator after a host specification. Contacting an rsync daemon directly happens when the source or destination path contains a double colon (::) separator after a host specification, OR when an rsync:// URL is specified (see also the "USING RSYNC-DAEMON FEATURES VIA A REMOTE-SHELL CONNECTION" section for an exception to this latter rule).

Based on this, it seems like you should only use either `::` or `rsync://`.  When using `rsync://` you should use a URL style instead, which would look like:

```
rsync://remote.example/updates/repos/
```

**Comment by sivel** [comment]
needs_info

**Comment by dekimsey** [comment]
Oh, interesting. When I tried using `remote.example::/updates/repo` it would not work, which was my initial attempt, the module reads that as a relative file path. I did not try your invocation. I will give that a whirl and report back.

**Comment by dglinder** [comment]
@dekimsey how did your testing (mentioned on May 30) go?

**Comment by dawud** [comment]
As per the [comment](https://github.com/ansible/ansible/issues/57182#issuecomment-497460914)  above by @sivel, using modules requires using `rsync://$server/$module` syntax.
The following example works as expected:

```yaml
# https://www.rfc-editor.org/retrieve/rsync/
---
- hosts: localhost
  become: false
  gather_facts: true
  vars:
    - server: 'ftp.rfc-editor.org'
    - modules: ['rfcs-text-only', 'ids-text-only']
    - local_dir: "{{ lookup('env','HOME') }}/Documents/RFC/{{ item | regex_replace('-.*$') }}"
  tasks:
    - name: Create a local mirror of IETF RFCs and Internet Drafts in text mode
      synchronize:
        mode: pull
        src: "rsync://{{ server }}/{{ item }}"
        dest: "{{ local_dir }}"
        recursive: true
        delete: true
      loop: "{{ modules }}"
```

**Comment by monsoft** [comment]
Yes, it works when you run rsync daemon as "rsync://" indicate that you will use daemon. If you want to do rsync over ssh  in push mode it will not work.

```
- name: Sync file
  synchronize:
    src: "/home/ansible/{{ item }}"
    dest: "rsync://{{ hostvars['worker1'].ansible_host}}/{{ item }}"
    mode: push
  delegate_to: "manager"
  with_items:
    - test.txt
  tags: test-sync
```
Produce error:
`"rsync: failed to connect to 192.168.56.46 (192.168.56.46): Connection refused (111)\nrsync error: error in socket IO (code 10) at clientserver.c(125) [sender=3.1.2]\n",`

According to debug, this task produce code:
`/usr/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /home/ansible/test.txt rsync://192.168.56.46/test.txt"`

To be able to use rsync over remote shell it will have to produce code:
`/usr/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /home/ansible/test.txt 192.168.56.46:test.txt`
