### ISSUE TITLE
Git module bare clones give changed=False when non-default branch changes

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#57197]
##### SUMMARY
Doing a bare clone, a task using the git module will return an "ok" status when it should have returned a "changed" status

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git module

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/tmp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
CentOS

##### STEPS TO REPRODUCE
Ansible command:

```
ansible-playbook checkout.yml --connection local -i localhost, -e project_path=/tmp/mirrors/ansible -e scm_url=https://github.com/ansible/ansible.git -e force=False -e scm_clean=False -e bare=True -e refspec=+refs/heads/*:refs/heads/*
```

with playbook:

```yaml
- hosts: all
  gather_facts: false
  tasks:
      - name: update project using git
        git:
          dest: "{{project_path|quote}}"
          repo: "{{scm_url}}"
          version: "{{scm_branch|default(omit)|quote}}"
          force: "{{scm_clean}}"
          bare: "{{bare|default(omit)}}"
          refspec: "{{refspec|default(omit)}}"
          accept_hostkey: "{{scm_accept_hostkey|default(omit)}}"
        register: git_result
```

##### EXPECTED RESULTS
When doing a bare clone, if any of the branches matched by the `refs/heads/*` refspec changed, then the task should report that it changed.

##### ACTUAL RESULTS
Playbook output:

```
PLAY [all] ****************************************************************************************************************************************************************************

TASK [update project using git] *******************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0  
```

However, using another tool, I find comparing the versions before / after the playbook run, I find:

```
Changes detected in refs/tags/branches:
{
  "stable-2.8": [
    "19ffe970f7022fe78130bfea0803ae6f0a8ebdd5",
    "2128e7c14f8143777ba135dbff9c03c6f4549b1a"
  ]
}
```

In prior runs, I have found that it reports that it has changed when the `devel` branch of this repo has changed. This begs the obvious interpretation that the git module reports that a change has happened when the default branch changes, but not when other branches are updated.
