### ISSUE TITLE
nodeConfig has been deprecated in favor of nodePool on gcp_container_cluster

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#57194]
##### SUMMARY
nodeConfig is deprecated on gcp container cluster API, replaced by nodePool which contains a nodeConfig among other configuration values

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_container_cluster

##### ANSIBLE VERSION
```paste below
devel
```

##### STEPS TO REPRODUCE
```yaml
      gcp_container_cluster:
        name: my-cluster
        initial_node_count: 1
        node_pool:
          node_config:
            image_type: UBUNTU
            machine_type: n1-standard-8
            disk_size_gb: 100
        location: us-west1
        project: my-project
        auth_kind: serviceaccount
        service_account_file: ~/myserviceaccountfile.json
        state: present
      register: my_cluster
```

##### EXPECTED RESULTS

Ability to set autoscaling, etc
