### ISSUE TITLE
Remove omitted elements from `command` arguments

### ISSUE THREAD

**Issue by maxd** [ansible/ansible#57196]
##### SUMMARY
I want to have ability to remove elements marked with `omit` variable from `argv` array of `command` module:

```yaml
- command:
  args:
    argv:
      - echo
      - 1
      - "{{ omit }}"
      - 3
```

It should output `1 3` instead of `1 
__omit_place_holder__??? 3` (see explanation why I want it in `ADDITIONAL INFORMATION` section)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
command

##### ADDITIONAL INFORMATION
I am using `command` module in my projects and pass command arguments through `argv`. For example (`docker` here is just for example, I known about `docker_*` modules):

```yaml
- name: run docker image
  command:
  args:
    argv:
      - docker
      - run
      - --rm
      - "{% if privileged | bool %}--privileged{% endif %}"
      - hello-world
```

All works fine if `privileged` is equals to `true`, but if it `false` the command execution fail with error:

```
TASK [run docker image] ******************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["docker", "run", "--rm", "", "hello-world"], "delta": "0:00:00.045168", "end": "2019-05-30 22:02:26.595505", "msg": "non-zero return code", "rc": 125, "start": "2019-05-30 22:02:26.550337", "stderr": "docker: invalid reference format.\nSee 'docker run --help'.", "stderr_lines": ["docker: invalid reference format.", "See 'docker run --help'."], "stdout": "", "stdout_lines": []}
```

As you can see the `docker` (and a lot of other programs) can't handle empty arguments and fail.

Right now there aren't easy ways to remove empty string from `argv` array and I am using different hacks to fill the empty string i.e.:

```
- "{% if privileged | bool %}--privileged{% else %}--env=NOT_PRIVILEGED{% endif %}"
``` 

I suppose the right way to fix this problem is allow to use `omit` variable in `argv` array i.e.:

```
- "{% if privileged | bool %}--privileged{% else %}{{ omit }}{% endif %}"
```

In this case the `command` module should just remove omitted elements from `argv` array.

What do you think about such feature?

I am ready to prepare PR but I don't understand how to get `omit` variable inside of `command` module. Could you please explain me how to do it better?

##### STEPS TO REPRODUCE

1. Install `Docker` and pull `hello-world` image:

    ```
    docker pull hello-world
    ```

1. Create `main.yml` file:

    ```yaml
    - name: run command
      gather_facts: no
      hosts: localhost
      connection: local
      tasks:
        - name: run docker image
          command:
          args:
            argv:
              - docker
              - run
              - --rm
              - "{% if privileged | bool %}--privileged{% endif %}"
              - hello-world
    ```

1. Use this command to run playbook with different `privileged` value:

    ```
    ansible-playbook -v main.yml -e privileged=true

    or 

    ansible-playbook -v main.yml -e privileged=false
    ```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
We are conflicted about adding this feature, and it has come up in the past.

Should you want to pursue this further, please add this to the core IRC meeting agenda for additional discussion: https://github.com/ansible/community/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Ameeting_agenda+label%3Acore

Example PR from a previous attempt: https://github.com/ansible/ansible/pull/39179

**Comment by maxd** [comment]
I have read your discussion. Looks like there are no chances to promote this feature with `omit`.

I have decided that I will use hacks or something like that to remove empty elements:

```
    - set_fact:
        command_args:
          - docker
          - run
          - --rm
          - "{% if privileged | bool %}--privileged{% else %}{{ omit }}{% endif %}"
          - hello-world

    - name: run docker image
      command:
      args:
        argv: "{{ command_args | difference(omit) }}"
```

Ansible full of "such hacks" and yet one doesn't make it even worse 😞
