### ISSUE TITLE
VMware Tools Connector does not support pipelining

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#57234]
##### SUMMARY

The vmware_tools connector has self.has_pipelining set to true, even though pipelining is not supported. Therefore all plays fail with invalid command that try to use pipelining.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

lib/ansible/plugins/connection/vmware_tools.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /home/user/Git/Create_Infrastrukture_Windows/plays/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/Private/ansible-1/lib/ansible
  executable location = /home/user/Private/ansible-1/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/user/Private/playbook/plays/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/Private/playbook/plays/ansible.cfg) = -o ForwardAgent=no
COMMAND_WARNINGS(/home/user/Private/playbook/plays/ansible.cfg) = True
DEFAULT_BECOME(/home/user/Private/playbook/plays/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(/home/user/Private/playbook/plays/ansible.cfg) = True
DEFAULT_FORKS(/home/user/Private/playbook/plays/ansible.cfg) = 50
DEFAULT_MANAGED_STR(/home/user/Private/playbook/plays/ansible.cfg) = This file is managed by ansible - local changes will be lost
DEFAULT_REMOTE_USER(/home/user/Private/playbook/plays/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/user/Private/playbook/plays/ansible.cfg) = ['/home/user/Private/playbook/roles/internal', '/home/user/Private/Create_Infra>
DEFAULT_TRANSPORT(/home/user/Private/playbook/plays/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/home/user/Private/playbook/plays/ansible.cfg) = /home/user/Private/playbook/.vpass
DEPRECATION_WARNINGS(/home/user/Private/playbook/plays/ansible.cfg) = True
INTERPRETER_PYTHON(/home/user/Private/playbook/plays/ansible.cfg) = python3
RETRY_FILES_ENABLED(/home/user/Private/playbook/plays/ansible.cfg) = True
SYSTEM_WARNINGS(/home/user/Private/playbook/plays/ansible.cfg) = True
```

##### OS / ENVIRONMENT

ArchLinux

##### STEPS TO REPRODUCE

```yaml
- name: Get Inventory
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - add_host:
      name: 'VMwareVM'
      ansible_connection: vmware_tools
      ansible_shell_type: 'powershell'
      ansible_vmware_host: '{{ vcenter.hostname }}'
      ansible_vmware_user: '{{ vcenter.username }}'
      ansible_vmware_password: '{{ vcenter.password }}'
      ansible_vmware_validate_certs: '{{ vcenter.validate_certs|default(true) }}'
      ansible_vmware_guest_path: '{{ vmguestpath }}'
      ansible_user: Administrator
      ansible_vmware_tools_user: Administrator
      ansible_vmware_tools_password: '{{ item.ansible_vmware_tools_password }}
- name: Test
  hosts: VMwareVM
  gather_facts: false
  become: false
  strategy: linear
  tasks:
    - name: Example from an Ansible Playbook
      win_ping:
```

##### EXPECTED RESULTS

Successful task execution

##### ACTUAL RESULTS

```paste below
fatal: [VMwareVM]: FAILED! => {
    "changed": false,
    "module_stderr": "#< CLIXML\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S=\"Error\">invalid payload_x000D__x000A_</S><S S=\"Error\">At line:4 char:39_x000D__x000A_</S><S S=\"Error\">+ If (-not $split_parts.Length -eq 2) { throw \"invalid payload\" }_x000D__x000A_</S><S S=\"Error\">+                                       ~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : OperationStopped: (invalid payload:String) [], R _x000D__x000A_</S><S S=\"Error\">   untimeException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : invalid payload_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
