### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#57243]
##### SUMMARY

Attempting to use win_chocolatey to remove a package and an error message is returned "Object reference not set to an instance of an object"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /Users/tanner/projects/ansible.git/playbooks.git/celadonsystems.com/ansible.cfg
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```paste below
No changes
```

##### OS / ENVIRONMENT

Management host: macOS 10.14.5
Managed host: Windows Server 2016

##### STEPS TO REPRODUCE

```yaml
- name: remove old/deprecated packages (choco)
  win_chocolatey:
    name: "{{ item }}"
    state: "absent"
  when:
    - chocolatey_remove_packages is defined
  loop:  "{{ chocolatey_remove_packages|flatten(levels=1) }}"
  register: chocolatey_removed_packages
```

##### EXPECTED RESULTS

That all the list of package in the chocolatey_remove_packages would be removed from the Ansible managed host

##### ACTUAL RESULTS

```paste below
TASK [win_chocolatey : remove old/deprecated packages (choco)] *****************
task path: /Users/tanner/projects/ansible.git/playbooks.git/roles/win_chocolatey/tasks/main.yml:145
Using module file /Users/tanner/projects/ansible.git/ansible/lib/ansible/modules/windows/win_chocolatey.ps1
Pipelining is enabled.
<PC167.LAB.testing.com> ESTABLISH WINRM CONNECTION FOR USER: Administrator@LAB.testing.com on PORT 5986 TO PC167.LAB.testing.com
EXEC (via pipeline wrapper)
failed: [PC167.LAB.testing.com] (item=ccleaner) => {
    "ansible_loop_var": "item",
    "changed": false,
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output --all-versions ccleaner",
    "invocation": {
        "module_args": {
            "allow_empty_checksums": false,
            "allow_multiple": false,
            "allow_prerelease": false,
            "architecture": "default",
            "force": false,
            "ignore_checksums": false,
            "ignore_dependencies": false,
            "install_args": null,
            "name": [
                "ccleaner"
            ],
            "package_params": null,
            "pinned": null,
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "skip_scripts": false,
            "source": null,
            "source_password": null,
            "source_username": null,
            "state": "absent",
            "timeout": 2700,
            "validate_certs": true,
            "version": null
        }
    },
    "item": "ccleaner",
    "msg": "Error checking installation status for the package 'ccleaner'",
    "rc": 1,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Object reference not set to an instance of an object.\r\n",
    "stdout_lines": [
        "Object reference not set to an instance of an object."
    ]
}
```
I think this is a choco.exe problem. But I am opening an issue with ansible just in case it's how ansible handles return results from choco.exe

If ccleaner is **not** installed choco.exe 0.10.13 returns no values
```
> choco --version
0.10.13
> choco.exe list --local-only --exact --limit-output --all-versions ccleaner
```
If ccleaner is **not** installed choco.exe 0.10.14 throws an error?
```
> choco --version
0.10.14
> choco.exe list --local-only --exact --limit-output --all-versions ccleaner
Object reference not set to an instance of an object
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_chocolatey.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_chocolatey.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @elventear @if-meaton @jborean93 @jhawkesworth @nitzmahone @petemounce @ptemplier @smadam813 @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by basictheprogram** [comment]
## Choco 
  * https://github.com/chocolatey/choco/issues/1839
  * https://github.com/chocolatey/choco/issues/1837

**Comment by jborean93** [comment]
Yep this is a problem in the latest chocolately release as per https://github.com/chocolatey/choco/issues/1837. Nothing we can do here.

You can currently control what version of chocolately is bootstrapped by running

```
- name: install chocolatey 0.10.13
  win_chocolately:
    name: chocolately
    state: present
  environment:
    chocolatelyVersion: 0.10.13
```

The above won’t help if Chocolately is already installed though. There’s nothing we can do but wait for the new release.

**Comment by cwegener** [comment]
@basictheprogram @jborean93 There is a 0.10.15-beta version available for your testing

https://chocolatey.org/packages/chocolatey/0.10.15-beta-20190531

**Comment by hryamzik** [comment]
```yml
- name: install chocolatey 0.10.13
  win_chocolatey:
      name: chocolatey
      state: present
      version: 0.10.13
      force: yes

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled
```
