### ISSUE TITLE
New module - DigitalOcean Kubernetes Cluster

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#57244]
##### SUMMARY
Add a new `digital_ocean_kubernetes_cluster` module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
N/A (new module)

##### ADDITIONAL INFORMATION
DigitalOcean allows management of managed Kubernetes clusters via the v2 API: https://developers.digitalocean.com/documentation/v2/#create-a-new-kubernetes-cluster

It would be nice if I could manage clusters in a DigitalOcean account using a native Ansible module. For example, to create a new cluster:

```yaml
- name: Ensure K8s cluster exists.
  digital_ocean_kubernetes_cluster:
    state: present
    name: mydroplet
    version: 1.12.1-do.2
    auto_upgrade: true
    region: sfo1
    node_pools:
      - size: s-1vcpu-2gb
        count: 3
        name: frontend-pool
      - size: c-4
        count: 2
        name: backend-pool
```
