### ISSUE TITLE
ansible_playbook does not remove tmp folder and AnsiballZ_setup.py upon playbook completion

### ISSUE THREAD

**Issue by PgInsight** [ansible/ansible#57248]
##### SUMMARY

Running ansible-playbook on a local playbook leaves the AnsiballZ_setup.py in .ansible/tmp/xxx directory.  fills up partition.  Gather facts stage does not clean up tmp folder created.

252K    ./ansible-tmp-1558487422.92-213402409754226
252K    ./ansible-tmp-1558487423.6-149739088116744
252K    ./ansible-tmp-1558487424.94-170606399596096
252K    ./ansible-tmp-1558487426.76-59447206811990
252K    ./ansible-tmp-1558487701.88-87670703810721
252K    ./ansible-tmp-1558487707.83-164776858683603
252K    ./ansible-tmp-1558487713.65-153980385943633
252K    ./ansible-tmp-1558487718.42-242348535673841
^C
[root@ip-10-100-97-187 tmp]# cd ./ansible-tmp-1558487707.83-164776858683603
[root@ip-10-100-97-187 ansible-tmp-1558487707.83-164776858683603]# ls
AnsiballZ_setup.py
[root@ip-10-100-97-187 ansible-tmp-1558487707.83-164776858683603]# ls -la
total 1676
drwx------     2 root root    4096 May 22 01:15 .
drwx------ 15734 root root 1449984 May 31 20:18 ..
-rwxr--r--     1 root root  251964 May 22 01:15 AnsiballZ_setup.py

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-playbook gather facts does not clean up AnsiballZ_setup.py file and tmp folder

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Mar 18 2019, 18:38:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
(no output)

##### OS / ENVIRONMENT
Amazon Linux 1 AMI instance.  running in AWS

##### STEPS TO REPRODUCE

run the playbook on localhost

ansible-playbook main.yml

```yaml
- name: MOTD
  hosts: localhost
  tasks:
    - name: Welcome message using MOTD
      copy:
         dest: /etc/motd
         content: |

            ==================== NOTICE ===================
            + You are accessing a private system.
            + Unauthorized access is prohibited.
            + All connections are requests are logged and violations are reported to the authorities.
            + You have been notified.
            ==================== NOTICE ===================

```

##### EXPECTED RESULTS
tmp folders and files created during gather facts are removed upon playbook run completion

##### ACTUAL RESULTS
The .tmp folder is not removed.

```paste below

TASK [Gathering Facts] *******************************************************************************************************************************
task path: /root/main.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1559336745.95-72169235798231 `" && echo ansible-tmp-1559336745.95-72169235798231="` echo /root/.ansible/tmp/ansible-tmp-1559336745.95-72169235798231 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-3994LVqFpH/tmpthwJ4u TO /root/.ansible/tmp/ansible-tmp-1559336745.95-72169235798231/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1559336745.95-72169235798231/ /root/.ansible/tmp/ansible-tmp-1559336745.95-72169235798231/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1559336745.95-72169235798231/AnsiballZ_setup.py && sleep 0'
ok: [localhost] => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [

...

    "state": "file",
    "uid": 0
}
META: ran handlers
META: ran handlers

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

The tmp folder remains.
[root@ip-10-100-97-187 ~]# ll .ansible/tmp/
total 4
drwx------ 2 root root 4096 May 31 21:05 ansible-tmp-1559336745.95-72169235798231

[root@ip-10-100-97-187 ~]# ll .ansible/tmp/ansible-tmp-1559336745.95-72169235798231/
total 248
-rwxr--r-- 1 root root 251964 May 31 21:05 AnsiballZ_setup.py
