### ISSUE TITLE
/tmp/ansible/ not world-writable

### ISSUE THREAD

**Issue by chrisblossom** [ansible/ansible#5725]
When initially setting "user: root" in a playbook, /tmp/ansible is created with directory permissions 0755 when it should be 0777 (recurse=no) because when falling back to a non-root user the following error occurs:

Should be noted I'm not specifying "-u root" in the ansible-playbook command.

```
fatal: [dev] => Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p /tmp/ansible/$USER/ansible-tmp-1390414200.76-192986604554742 && chmod a+rx /tmp/ansible/$USER/ansible-tmp-1390414200.76-192986604554742 && echo /tmp/ansible/$USER/ansible-tmp-1390414200.76-192986604554742, exited with result 1: mkdir: cannot create directory `/tmp/ansible/chris': Permission denied
```

Example playbook:

```
-   name: initial setup
    hosts: all
    user: root
    roles:
        - system
        - packages
        - users

-   name: common setup
    hosts: all
    tasks:
        - include: roles/users/tasks/freshshell.yml

-   hosts: webservers
    gather_facts: false
    roles:
        - php
        - nginx
        - web_deploy
```

The solution I have done is to first setup the /tmp/ansible directory with the correct permissions:

```
-   name: /tmp/ansible/ directory exists with 0777 permission
    file: path=/tmp/ansible/ owner=root group=root mode=0777 recurse=no state=directory
    sudo: yes

```
