### ISSUE TITLE
ansible_net_model not populated on stacked switch models

### ISSUE THREAD

**Issue by Im0** [ansible/ansible#57285]
##### SUMMARY

Upgrading from Ansible 2.7.10 to Ansible 2.8 appears to have changed how ios_facts gathers information for `ansible_net_model`.  If a switch is stackable switch, `ansible_net_model` is no longer populated.

Instead, a single element list `ansible_net_stacked_models` has the switch model in it.

Requesting either:
* 2.7 -> 2.8 porting guide be updated to inform people of this change in functionality, or;
* Ensure that `ios_facts` populates `ansible_net_model` even if querying a stacked switch.  Eg. `ansible_net_model` should be the switch of the device you've connected to.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/johni/test_upgrade/ansible.cfg
  configured module search path = [u'/home/johni/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below
DEFAULT_TIMEOUT(/home/johni/test_upgrade/ansible.cfg) = 60
PERSISTENT_COMMAND_TIMEOUT(/home/johni/test_upgrade/ansible.cfg) = 1800

```

##### OS / ENVIRONMENT

* Ubuntu 16.04
* CIsco WS-C3750E-24PD

##### STEPS TO REPRODUCE

```yaml
- name: Get facts from switch
  hosts: switch
  gather_facts: no
  tasks:

    - name: gather facts > Get facts from IOS device
      ios_facts:
        gather_subset: all
      vars:
        ansible_persistent_log_messages: True

    - name: Debug ansible_net_model
      debug:
        var: ansible_net_model
      ignore_errors: true

    - name: Debug ansible_net_stacked_models
      debug:
        var: ansible_net_stacked_models
      ignore_errors: true

```

##### EXPECTED RESULTS

Ansible 2.7.10 works as expected:

```
johni@ansible:~/$ ansible-playbook -i switch_inventory getfacts.yml

PLAY [Get facts from switch] ***********************************************************************************

TASK [gather facts > Get facts from IOS device] ****************************************************************
ok: [c3750]

TASK [Debug ansible_net_model] *********************************************************************************
ok: [c3750] => {
    "ansible_net_model": "WS-C3750E-24PD"
}

TASK [Debug ansible_net_stacked_models] ************************************************************************
ok: [c3750] => {
    "ansible_net_stacked_models": [
        "WS-C3750E-24PD-S"
    ]
}

PLAY RECAP *****************************************************************************************************
c3750                      : ok=3    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

Running Ansible 2.8, the ansible_net_model does not get populated as expected... it is left as undefined.

```paste below
johni@ansible:~/$ ansible-playbook -i switch_inventory getfacts.yml

PLAY [Get facts from switch] ***********************************************************************************

TASK [gather facts > Get facts from IOS device] ****************************************************************
 [WARNING]: Persistent connection logging is enabled for 192.168.0.5. This will log ALL interactions and WILL
NOT redact sensitive configuration like passwords. USE WITH CAUTION!

[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host c3750 should use /usr/bin/python3, but is using
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default
to using the discovered platform python for this host. See
https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information. This
 feature will be removed in version 2.12. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ok: [c3750]

TASK [Debug ansible_net_model] *********************************************************************************
ok: [c3750] => {
    "ansible_net_model": "VARIABLE IS NOT DEFINED!"
}

TASK [Debug ansible_net_stacked_models] ************************************************************************
ok: [c3750] => {
    "ansible_net_stacked_models": [
        "WS-C3750E-24PD-S"
    ]
}

PLAY RECAP *****************************************************************************************************
c3750                      : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @privateip @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Im0, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jifox** [comment]
I'm focussing this problem even with switches that are not stacked.

```yaml
---
- hosts: all
  become: false

  tasks:

    - name: Test ansible_net_model exists
      ios_facts:
      register: result

    - name: Display ansible_net_stacked_models  
      debug:
        msg: |
          ansible_net_stacked_models: {{ ansible_net_stacked_models | to_nice_yaml() }}
      delegate_to: localhost
      changed_when: false
      tags: [print_action]

    - name: Display ansible_net_model  
      debug:
        msg: |
          ansible_net_model: {{ ansible_net_model|default('NOT DEFINED') }}
      delegate_to: localhost
      changed_when: false
      tags: [print_action]
```

Gives following output:

```bash
ansible@scvnetmgmt01 develop (develop *%=) $ ansible-playbook -i inv_develop.yml --limit ATRESERV01 test_ansible_plays.yml -vv
ansible-playbook 2.8.1
  config file = /home/ansible/devel/develop/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible', '/usr/local/lib/python3.6/site-packages/napalm', '/usr/local/lib/python3.6/site-packages/ntc-ansible']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /home/ansible/devel/develop/ansible.cfg as config file
1 plays in test_ansible_plays.yml
# Gathering Facts *********************************************************************************************************
  * ATRESERV01                 - changed=False --  --------------------------------------------
META: ran handlers
# Test ansible_net_model exists *******************************************************************************************
  * ATRESERV01                 - changed=False --  --------------------------------------------
# Display ansible_net_stacked_models **************************************************************************************
  * ATRESERV01                 - changed=False --------------------------------------------------
    ansible_net_stacked_models: - WS-C2960CX-8TC-L
    
# Display ansible_net_model ***********************************************************************************************
  * ATRESERV01                 - changed=False -- ansible_net_model: NOT DEFINED
 -------------
META: ran handlers
META: ran handlers

# STATS *******************************************************************************************************************
ATRESERV01    : ok=4    changed=0       failed=0        unreachable=0   rescued=0       ignored=0
```

show version on Cisco Switch:

```bash
ATRESERV01#show version 
Cisco IOS Software, C2960CX Software (C2960CX-UNIVERSALK9-M), Version 15.2(4)E6, RELEASE SOFTWARE (fc4)
...

Switch Ports Model                     SW Version            SW Image                 
------ ----- -----                     ----------            ----------               
*    1 12    WS-C2960CX-8TC-L          15.2(4)E6             C2960CX-UNIVERSALK9-M    

Configuration register is 0xF
```bash

same result also on a Catalyst 9300 switch 

```bash
ATKPTEST#show switch 
Load for five secs: 3%/1%; one minute: 4%; five minutes: 4%
Time source is NTP, 08:15:58.156 MES Thu Jun 13 2019

Switch/Stack Mac Address : 7018.a75f.dc00 - Local Mac Address
Mac persistency wait time: Indefinite
                                             H/W   Current
Switch#   Role    Mac Address     Priority Version  State 
-------------------------------------------------------------------------------------
*1       Active   7018.a75f.dc00     1      V02     Ready                
```
