### ISSUE TITLE
VMware: vmware_guest module does not set network for RHEL 8 images

### ISSUE THREAD

**Issue by gamuniz** [ansible/ansible#57306]
##### SUMMARY

While using vmware_guest to provision RHEL 8 images the network configuration is being ignored. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest.py

##### ANSIBLE VERSION

```ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

RHEL 7 control node

##### STEPS TO REPRODUCE

```- name: Create VM from template
  vmware_guest:
    hostname: "{{ vcenterHostname }}"
    username: "{{ vcenterUser }}"
    password: "{{ vcenterPass }}"
    validate_certs: false
    datacenter: "{{ vcenterDatacenter }}"
    name: "{{ ansible_host }}"
    template: "{{ vmTemplate }}"
    cluster: "{{ vmCluster }}"
    folder: "{{ vcenterDatacenter }}/vm/{{ vmBaseFolder }}{{ vmFolder }}"
    datastore: "{{ vcenterDatastore }}"
    customization:
      hostname: "{{ ansible_host.split('.')[0] }}"
      domain: "{{ ansible_host.split('.')[1:] | join('.') }}"
      dns_servers: "{{ networks[vmNetwork].dnsServers }}"
    hardware:
      memory_mb: "{{ vmMemory }}"
      num_cpus: "{{ vmCPUs }}"
    networks:
    - name: "{{ vmNetwork }}"
      ip: "{{ vmIP }}"
      netmask: "{{ networks[vmNetwork].vmNetmask }}"
      gateway: "{{ networks[vmNetwork].vmGateway }}"
      start_connected: true
    state: poweredon
    wait_for_ip_address: true
  retries: 5
  delay: 1
  register: newVMVar
  until: newVMVar is success
```

##### EXPECTED RESULTS

Network is configured correctly

##### ACTUAL RESULTS

```
[case-02392647.txt](https://github.com/ansible/ansible/files/3247722/case-02392647.txt)

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @dav1x @goneri @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@gamuniz, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Tomorrow9** [comment]
Hi, @gamuniz, do you mean after VM creation from template and "wait_for_ip_address", the IP address is not the one you configured in the yml file? Only network not configured correctly? hostname, domain were configured as expected? Thanks.

**Comment by Akasurde** [comment]
@gamuniz Could you please provide the required information as stated above ? Also, provide the ESXi version, open VM tool version or VMware tools version, Perl version.

needs_info

**Comment by ansibot** [comment]
@gamuniz This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@gamuniz You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jbertozzi** [comment]
Hi,

I would like to re-open this issue as I am facing the same issue.

##### SUMMARY

While using vmware_guest to provision RHEL 8 images, the customization is ignored. Machine is deployed, without correct network configuration, NIC not connected (despite the `start_connected``set to true).
This works well for RHEL7 VM.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest with VMware ESXi, version 6.7.0, build 13644319


##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /home/ansible/infra/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

OS: RHEL 7.7
python version: 2.7.5
ansible version: 2.8.4
VMware ESXi, 6.7.0, 13644319

##### STEPS TO REPRODUCE

Run the following task in a playbook:

```
  - name: Deploy the template
    vmware_guest:
      hostname: "{{ vmware_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: False
      name: "{{ inventory_hostname }}"
      template: tpl-rhel{{ servers[inventory_hostname]['os'] | default('7') }}
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      state: poweredon
      cluster: "{{ cluster }}"
      wait_for_ip_address: false
      hardware:
        num_cpus: "{{ servers[inventory_hostname]['cpu'] }}"
        memory_mb: "{{ servers[inventory_hostname]['ram'] * 1024 }}"
      disk:
      - size_gb: 20
        type: thin
        datastore: "{{datastore }}"
      - size_gb: "{{ servers[inventory_hostname]['disk'] }}"
        type: thin
        datastore: "{{ datastore }}"
      customization:
        dns_servers:
          - 10.33.0.100
          - 10.33.1.30
        dns_suffix:
          - "{{ dns_suffix }}"
        domain: "{{ domain }}"
        hostname: "{{ inventory_hostname }}"
      networks:
      - name: "{{ network_vcenter }}"
        start_connected: true
        ip: "{{ip.split('/')[0] }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
    delegate_to: localhost
```

```yaml
