### ISSUE TITLE
Unarchive is not idempotent when 'owner' is set

### ISSUE THREAD

**Issue by wawrzek** [ansible/ansible#57303]
##### SUMMARY
Unarchive is not idempotence when owner parameter is different from root.  The problem was already indepently confirm on Ansible project mailing list (see thread https://groups.google.com/forum/#!topic/ansible-project/TOGxHqHdjlY)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unarchive module

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /Users/wawrzek/Work/Ansible/ansible-r3-roles/cenm-base/ansible.cfg
  configured module search path = [u'/Users/wawrzek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Feb 12 2019, 11:00:12) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]

```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_ROLES_PATH(/Users/wawrzek/Work/Ansible/ansible-r3-roles/cenm-base/ansible.cfg) = [u'/Users/wawrzek/Work/Ansible']
DEPRECATION_WARNINGS(/Users/wawrzek/Work/Ansible/ansible-r3-roles/cenm-base/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/wawrzek/Work/Ansible/ansible-r3-roles/cenm-base/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/Users/wawrzek/Work/Ansible/ansible-r3-roles/cenm-base/ansible.cfg) = /tmp
```

##### OS / ENVIRONMENT
"Ubuntu Bionic" but also tested on "MacOSX (Darwin 18.2.0)"

##### STEPS TO REPRODUCE
I noticed the problem with zip archive consists only of files. To recreate just create a zip with any files and run TWICE playbook similar to one I pasted below.

```yaml
- hosts: localhost,
  become: true
  tasks:
    - name: unarchive
      unarchive:
        src: /tmp/test.zip
        dest: output
        mode: 0700
        remote_src: true
        owner: wawrzek2
        group: admin
```

##### EXPECTED RESULTS
Second run should not change anything.

##### ACTUAL RESULTS
Every time task is marked as 'changed'.
