### ISSUE TITLE
network_cli connection plugin performance issues

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#57322]
##### SUMMARY
We have observed a significant performance degradation for the `network_cli` `ansible_connection` since Ansible release `2.6.1` testing using the nxos modules.

Opening this issue to investigate and determine what is causing the changes from release to release.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible_connection: network_cli

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

```

##### CONFIGURATION
```paste below
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets']
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True
PERSISTENT_COMMAND_TIMEOUT(env: ANSIBLE_PERSISTENT_COMMAND_TIMEOUT) = 1000
PERSISTENT_CONNECT_TIMEOUT(env: ANSIBLE_PERSISTENT_CONNECT_TIMEOUT) = 1000

```

##### OS / ENVIRONMENT
Tests run on MacOs as the Ansible controller.

##### STEPS TO REPRODUCE
Here are the performance results:

**KEY:**
loop = Ansible playbook with looping used.
agg = Ansible playbook with aggregate used.
idem = Idempotent, device already in the desired state.

| Ansible Version  | network_cli | httpapi | local using nxapi provider |
| ---------------- | ----------- | ------- | -------------------------- |
| 2.6.1  | loop: 45s<br>loop idem: 40s<br>agg: 13s<br>agg idem: 7s<br>  | loop: 46s<br>loop idem: 41s<br>agg: 11s<br>agg idem: 7s<br> | loop: 44s<br>loop idem: 40s<br>agg: 8s<br>agg idem: 4s<br> |
| 2.7.8 | loop: 1m28s<br>loop idem: 47s<br>agg: 34s<br>agg idem: 8s<br>  | loop: 42s<br>loop idem: 41s<br>agg: 9s<br>agg idem: 6s<br> | loop: 40s<br>loop idem: 36s<br>agg: 8s<br>agg idem: 4s<br> |
| 2.8.0  | loop: 2m25s<br>loop idem: 2m4s<br>agg: 38s<br>agg idem: 11s<br>  | loop: 44s<br>loop idem: 39s<br>agg: 12s<br>agg idem: 9s<br> | loop: 43s<br>loop idem: 37s<br>agg: 10s<br>agg idem: 5s<br> |
| devel  | loop: 2m27s<br>loop idem: 2m3s<br>agg: 38s<br>agg idem: 11s<br>  | loop: 44s<br>loop idem: 41s<br>agg: 12s<br>agg idem: 9s<br> | loop: 40s<br>loop idem: 39s<br>agg: 10s<br>agg idem: 5s<br> |

As you can see from the table, `httpapi` and `local nxapi provider` has been pretty consistent since release `2.6.1` but `network_cli` performance has changed quite a bit.

The following playbooks were used to measure the performance using a looping ansible playbook mechanism vs. aggregate.

* Aggregate Playbook

```yaml
---
- name: Create static routes with aggregate
  hosts: nxos
  gather_facts: no
  connection: (httpapi | nework_cli | local - using provider)

  vars:
    nxapi:
      host: "{{ ansible_ssh_host }}"
      username: "{{ nxos_nxapi_user | default('admin') }}"
      password: "{{ nxos_nxapi_pass | default('admin') }}"
      transport: nxapi
      use_ssl: no

  tasks:
    - name: Create static routes
      nxos_static_route:
        provider: "{{ nxapi }}"
        state: (absent | present)
        vrf: BLUE
        aggregate:
          - { prefix: 1.1.1.1/32, next_hop: 192.168.0.1 }
          - { prefix: 2.2.2.2/32, next_hop: 192.168.0.1 }
          - { prefix: 3.3.3.3/32, next_hop: 192.168.0.1 }
          - { prefix: 4.4.4.4/32, next_hop: 192.168.0.1 }
          - { prefix: 5.5.5.5/32, next_hop: 192.168.0.1 }
          - { prefix: 6.6.6.6/32, next_hop: 192.168.0.1 }
          - { prefix: 7.7.7.7/32, next_hop: 192.168.0.1 }
          - { prefix: 8.8.8.8/32, next_hop: 192.168.0.1 }
          - { prefix: 9.9.9.9/32, next_hop: 192.168.0.1 }
          - { prefix: 10.10.10.10/32, next_hop: 192.168.0.1 }
          - { prefix: 11.11.11.11/32, next_hop: 192.168.0.1 }
          - { prefix: 12.12.12.12/32, next_hop: 192.168.0.1 }
          - { prefix: 13.13.13.13/32, next_hop: 192.168.0.1 }
          - { prefix: 14.14.14.14/32, next_hop: 192.168.0.1 }
          - { prefix: 15.15.15.15/32, next_hop: 192.168.0.1 }
          - { prefix: 16.16.16.16/32, next_hop: 192.168.0.1 }
          - { prefix: 17.17.17.17/32, next_hop: 192.168.0.1 }
          - { prefix: 18.18.18.18/32, next_hop: 192.168.0.1 }
          - { prefix: 19.19.19.19/32, next_hop: 192.168.0.1 }
          - { prefix: 20.20.20.20/32, next_hop: 192.168.0.1 }
          - { prefix: 21.21.21.21/32, next_hop: 192.168.0.1 }
          - { prefix: 22.22.22.22/32, next_hop: 192.168.0.1 }
          - { prefix: 23.23.23.23/32, next_hop: 192.168.0.1 }
          - { prefix: 24.24.24.24/32, next_hop: 192.168.0.1 }
          - { prefix: 25.25.25.25/32, next_hop: 192.168.0.1 }
          - { prefix: 26.26.26.26/32, next_hop: 192.168.0.1 }
          - { prefix: 27.27.27.27/32, next_hop: 192.168.0.1 }
          - { prefix: 28.28.28.28/32, next_hop: 192.168.0.1 }
          - { prefix: 29.29.29.29/32, next_hop: 192.168.0.1 }
          - { prefix: 30.30.30.30/32, next_hop: 192.168.0.1 }
          - { prefix: 31.31.31.31/32, next_hop: 192.168.0.1 }
          - { prefix: 32.32.32.32/32, next_hop: 192.168.0.1 }
          - { prefix: 33.33.33.33/32, next_hop: 192.168.0.1 }
          - { prefix: 34.34.34.34/32, next_hop: 192.168.0.1 }
          - { prefix: 35.35.35.35/32, next_hop: 192.168.0.1 }
          - { prefix: 36.36.36.36/32, next_hop: 192.168.0.1 }
          - { prefix: 37.37.37.37/32, next_hop: 192.168.0.1 }
          - { prefix: 38.38.38.38/32, next_hop: 192.168.0.1 }
          - { prefix: 39.39.39.39/32, next_hop: 192.168.0.1 }
          - { prefix: 40.40.40.40/32, next_hop: 192.168.0.1 }
          - { prefix: 41.41.41.41/32, next_hop: 192.168.0.1 }
          - { prefix: 42.42.42.42/32, next_hop: 192.168.0.1 }
          - { prefix: 43.43.43.43/32, next_hop: 192.168.0.1 }
          - { prefix: 44.44.44.44/32, next_hop: 192.168.0.1 }
          - { prefix: 45.45.45.45/32, next_hop: 192.168.0.1 }
          - { prefix: 46.46.46.46/32, next_hop: 192.168.0.1 }
          - { prefix: 47.47.47.47/32, next_hop: 192.168.0.1 }
          - { prefix: 48.48.48.48/32, next_hop: 192.168.0.1 }
          - { prefix: 49.49.49.49/32, next_hop: 192.168.0.1 }
          - { prefix: 50.50.50.50/32, next_hop: 192.168.0.1 }
```

*  Loop Playbook

```yaml
---
- name: Create static routes
  hosts: nxos
  gather_facts: no
  connection: (httpapi | nework_cli | local - using provider)

  vars:
    nxapi:
      host: "{{ ansible_ssh_host }}"
      username: "{{ nxos_nxapi_user | default('admin') }}"
      password: "{{ nxos_nxapi_pass | default('admin') }}"
      transport: nxapi
      use_ssl: no

  tasks:
    - name: Create static routes
      nxos_static_route:
        provider: "{{ nxapi }}"
        state: (present | absent) 
        prefix: "{{ item.prefix }}"
        next_hop: "{{ item.next_hop }}"
        vrf: BLUE
      loop:
        - { prefix: 1.1.1.1/32, next_hop: 192.168.0.1 }
        - { prefix: 2.2.2.2/32, next_hop: 192.168.0.1 }
        - { prefix: 3.3.3.3/32, next_hop: 192.168.0.1 }
        - { prefix: 4.4.4.4/32, next_hop: 192.168.0.1 }
        - { prefix: 5.5.5.5/32, next_hop: 192.168.0.1 }
        - { prefix: 6.6.6.6/32, next_hop: 192.168.0.1 }
        - { prefix: 7.7.7.7/32, next_hop: 192.168.0.1 }
        - { prefix: 8.8.8.8/32, next_hop: 192.168.0.1 }
        - { prefix: 9.9.9.9/32, next_hop: 192.168.0.1 }
        - { prefix: 10.10.10.10/32, next_hop: 192.168.0.1 }
        - { prefix: 11.11.11.11/32, next_hop: 192.168.0.1 }
        - { prefix: 12.12.12.12/32, next_hop: 192.168.0.1 }
        - { prefix: 13.13.13.13/32, next_hop: 192.168.0.1 }
        - { prefix: 14.14.14.14/32, next_hop: 192.168.0.1 }
        - { prefix: 15.15.15.15/32, next_hop: 192.168.0.1 }
        - { prefix: 16.16.16.16/32, next_hop: 192.168.0.1 }
        - { prefix: 17.17.17.17/32, next_hop: 192.168.0.1 }
        - { prefix: 18.18.18.18/32, next_hop: 192.168.0.1 }
        - { prefix: 19.19.19.19/32, next_hop: 192.168.0.1 }
        - { prefix: 20.20.20.20/32, next_hop: 192.168.0.1 }
        - { prefix: 21.21.21.21/32, next_hop: 192.168.0.1 }
        - { prefix: 22.22.22.22/32, next_hop: 192.168.0.1 }
        - { prefix: 23.23.23.23/32, next_hop: 192.168.0.1 }
        - { prefix: 24.24.24.24/32, next_hop: 192.168.0.1 }
        - { prefix: 25.25.25.25/32, next_hop: 192.168.0.1 }
        - { prefix: 26.26.26.26/32, next_hop: 192.168.0.1 }
        - { prefix: 27.27.27.27/32, next_hop: 192.168.0.1 }
        - { prefix: 28.28.28.28/32, next_hop: 192.168.0.1 }
        - { prefix: 29.29.29.29/32, next_hop: 192.168.0.1 }
        - { prefix: 30.30.30.30/32, next_hop: 192.168.0.1 }
        - { prefix: 31.31.31.31/32, next_hop: 192.168.0.1 }
        - { prefix: 32.32.32.32/32, next_hop: 192.168.0.1 }
        - { prefix: 33.33.33.33/32, next_hop: 192.168.0.1 }
        - { prefix: 34.34.34.34/32, next_hop: 192.168.0.1 }
        - { prefix: 35.35.35.35/32, next_hop: 192.168.0.1 }
        - { prefix: 36.36.36.36/32, next_hop: 192.168.0.1 }
        - { prefix: 37.37.37.37/32, next_hop: 192.168.0.1 }
        - { prefix: 38.38.38.38/32, next_hop: 192.168.0.1 }
        - { prefix: 39.39.39.39/32, next_hop: 192.168.0.1 }
        - { prefix: 40.40.40.40/32, next_hop: 192.168.0.1 }
        - { prefix: 41.41.41.41/32, next_hop: 192.168.0.1 }
        - { prefix: 42.42.42.42/32, next_hop: 192.168.0.1 }
        - { prefix: 43.43.43.43/32, next_hop: 192.168.0.1 }
        - { prefix: 44.44.44.44/32, next_hop: 192.168.0.1 }
        - { prefix: 45.45.45.45/32, next_hop: 192.168.0.1 }
        - { prefix: 46.46.46.46/32, next_hop: 192.168.0.1 }
        - { prefix: 47.47.47.47/32, next_hop: 192.168.0.1 }
        - { prefix: 48.48.48.48/32, next_hop: 192.168.0.1 }
        - { prefix: 49.49.49.49/32, next_hop: 192.168.0.1 }
        - { prefix: 50.50.50.50/32, next_hop: 192.168.0.1 }
```
