### ISSUE TITLE
lineinfile file descriptor leak since 2.7.0

### ISSUE THREAD

**Issue by dw** [ansible/ansible#57327]
##### SUMMARY

Since 4b5b4a760c5, lineinfile module received some gentle refactoring that replaced an `fdopen()` call with a regular `open()`, causing the file descriptor returned by `mkstemp()` to remain unconsumed by some managed resource object, as it was previously with `fdopen()`.

https://github.com/ansible/ansible/blob/8cf6f56a0103c51e93de9e26ce1982ce4aeb7ba0/lib/ansible/modules/files/lineinfile.py#L215-L219

If the leaked fd was for a script, subsequent attempts to execute that script while the lineinfile process still exists will exhibit errno `ETXTBSY`. This is not (or should not be?) a problem for Ansible, but with Mitogen the leaked FD is problematic, where the host process has indefinite lifetime.

It seems unlikely to be worth worrying about, but nonetheless important to note the `mkstemp()` interface returns a descriptor in order to avoid a race where a privileged process can be tricked into modifying the wrong file, should the parent directory be owned by a lesser privileged user. This seems quite contrived -- it would require Ansible to be specifically configured to create temporary files in directories with bad permissions.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

- lineinfile

##### ANSIBLE VERSION

````
v2.7.0
v2.7.1
v2.7.2
v2.7.3
v2.7.4
v2.7.5
v2.7.6
v2.7.7
v2.7.8
v2.7.9
v2.7.10
v2.7.11
v2.8.0
````

##### OS / ENVIRONMENT

Linux/Ubuntu

##### STEPS TO REPRODUCE

```yaml
# note: does not manifest unless run under Mitogen

- hosts: localhost
  tasks:
  - file:
      path: /tmp/foo
      state: absent
  - lineinfile:
      path: /tmp/foo
      create: true
      line: "#!/bin/sh"
  - command: chmod +x /tmp/foo
  - command: /tmp/foo
```

##### EXPECTED RESULTS

Empty shell script executes successfully.

##### ACTUAL RESULTS

```
TASK [command _raw_params=/tmp/foo] ******************************************************************************************************************************************
fatal: /home/dmw/src/mitogen/tests/ansible/a.yml:9: [localhost]: FAILED! => {
  changed: False
  cmd: /tmp/foo
  invocation: {
    module_args: {
      _raw_params: /tmp/foo
      _uses_shell: False
      argv: None
      chdir: None
      creates: None
      executable: None
      removes: None
      stdin: None
      stdin_add_newline: True
      strip_empty_ends: True
      warn: True
    }
  }
  msg: [Errno 26] Text file busy
  rc: 26
}
```
