### ISSUE TITLE
gcp_compute dynamic inventory not working with auth_kind: application/machineaccount

### ISSUE THREAD

**Issue by LucasBoisserie** [ansible/ansible#57344]
##### SUMMARY

Gcp_compute plugin inventory doesn't work when params auth_kind is not set to serviceaccount and service_account_file is defined.
The module accept others values for auth_kind ( application and machineaccount) which not working in ansible 2.8 and ansible devel

The bug was introduced by adding a required field on service_account_file params which not required with auth_kind others values

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.0 + devel
```

##### STEPS TO REPRODUCE

```bash
export GOOGLE_APPLICATION_CREDENTIALS=account.json
ansible-inventory -i inventories/gcp_compute.yml --graph
```

gcp_compute.yml

```yaml
plugin: gcp_compute
auth_kind: application
zones: # populate inventory with instances in these regions
  - europe-west1-b
  - europe-west1-c
  - europe-west1-d
projects:
  - lab-k8s
filters: []

```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```paste below
gcp_compute.yml with auto plugin: No setting was provided for required configuration plugin_type: inventory plugin: gcp_compute setting: service_account_file
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/inventory/gcp_compute.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/gcp_compute.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @erjohnso @rambleraptor
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kustodian** [comment]
I've managed to make it work by providing an empty `service_account_file:`, but that is just a workaround, it shouldn't need to be set.

**Comment by walterdolce** [comment]
I have just hit the same problem. The `service_account_file` plugin configuration field should only really be required when the `auth_kind` field is set to `serviceaccount`. By default (and like most tools out there), the plugin should make an attempt at getting the default application credentials on the machine where Ansible is being run.

Additionally, it has to be noted that in all `gcp_compute_*` modules, one can do the following:
```
- name: Manage firewall rules
  gcp_compute_firewall:
    allowed: "{{ item.allow_rules }}"
    auth_kind: "{{ gcp_auth_kind | default('application') }}"
    description: "{{ item.description }}"
    name: "{{ gcp_network + '-' + item.name }}"
    network: "{{ network }}"
    project: "{{ gcp_project }}"
    scopes: "{{ gcp_scopes }}"
    service_account_file: "{{ gcp_service_account_file | default(omit) }}"
    source_ranges: "{{ item.source_ranges }}"
    state: "{{ resources_state }}"
    target_tags: "{{ item.target_tags }}"
  with_items: "{{ gcp_firewall_rules }}"
```

Note how the `service_account_file` is set to `{{ gcp_service_account_file | default(omit) }}`. That means if I *don't* provide a `gcp_service_account_file` and `gcp_auth_kind` when I run Ansible, the `service_account_file` field would be omitted and the `auth_kind` field would be set to `application`, using my personal credentials. This is ideal. This allows me to choose when and how to authenticate against GCP. When running from my laptop, I could use my personal credentials. When running from CI, I could feed it a `gcp_service_account_file` and `gcp_auth_kind` vars and let it authenticate with a service account.

But the following does not work for the plugin configuration:
```
plugin: gcp_compute
projects:
  - some-gcp-project-id
scopes: "{{ gcp_scopes }}"
service_account_file: "{{ gcp_service_account_file | default(omit) }}"
auth_kind: "{{ gcp_auth_kind | default('application') }}"
groups:
  some_group: true
```

The above produces the following warning:
```
[WARNING]:  * Failed to parse inventory.some_group.gcp.yml with auto plugin: Service Account File only works with Service Account-based authentication
```
