### ISSUE TITLE
Regression when moving to ansible 2.8 when including a role that has a custom filter

### ISSUE THREAD

**Issue by sradco** [ansible/ansible#57351]
##### SUMMARY
Regression when moving to ansible 2.8 when including a role that has filter_plugins.
include_role now can't find the filter_plugins of the included role

##### ISSUE TYPE
- Bug Report
- Regression

##### COMPONENT NAME
include_role and filter_plugins

##### ANSIBLE VERSION
ansible 2.8

##### STEPS TO REPRODUCE
Add a playbook that includes a role that has filter_plugins.

##### EXPECTED RESULTS
In ansible 2.7 include_role found the filter_plugins,
expected that ansible 2.8 will find the filter_plugins as well.

##### ACTUAL RESULTS
```
The playbook can't find the filter_plugins of the included role.
template error while templating string: no filter named 'ovirtvmipv4'. String: {{ ovirt_vms | ovirtvmipv4 }}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/utilities/logic/include_role.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by machacekondra** [comment]
Few more information. This worked in 2.7.11, doesn't work since 2.8.

Reproduction steps:

1. Create simple role 
```bash
myrole/
├── filter_plugins
 │  ├── myplugin.py
└── tasks
    └── main.yml
```

2. Add following tasks to main.yml
```yaml
- name: test
   stat:
     path: "/etc/resolv.conf"
   delegate_to: "{{ "1.2.3.4" | parse_ip }}"
```

3. Craete the filter
```python
#!/usr/bin/python
class FilterModule(object):
    def filters(self):
        return {'parse_ip': self.parse_ip}

    def parse_ip(self, ip):
        return ip
````

4. Execute the playbook with including the role
```yaml
- hosts: localhost
   connection: local
   gather_facts: false

   tasks:
     - name: role
       include_role:
         name: myrole
```

**Comment by sivel** [comment]
I've verified this issue.  It does not manifest if the filter is used in module arguments such as with `msg` for `debug` but manifests with a task keyword such as `delegate_to`.

A git bisect indicates that it was introduced in 6069d09b9d7193a1896dfc2816e0e51833a53e6b

cc @pilou-

**Comment by mkrizek** [comment]
A little more detail to the note above. https://github.com/ansible/ansible/commit/6069d09b9d7193a1896dfc2816e0e51833a53e6b introduced using only  one single `Templar` instance through lifetime of `VariableManager`. That causes `filters` to be loaded only once and used from the cache each time after that resulting in them not being updated later if needed; when including a role in this case. So when templating `delegate_to`, which is done in `VariableManager`, the cached old filters are used resulting in `parse_ip` from the role not being found.

The issue does not manifest if the filter is used in module arguments because those are validated in `post_validate` which is being passed a `Templar` instance that is created for each task separately and so proper `filters` are loaded for each task.

So while https://github.com/ansible/ansible/commit/6069d09b9d7193a1896dfc2816e0e51833a53e6b introduces better performance in `_get_filters` method it seems to be because we don't load filters that might have been added and use old cache resulting in incorrect behavior.

https://github.com/ansible/ansible/commit/6069d09b9d7193a1896dfc2816e0e51833a53e6b was merged in https://github.com/ansible/ansible/pull/45572 which was re-submission of https://github.com/ansible/ansible/pull/40234.

cc @bcoca @dw

**Comment by bcoca** [comment]
so we update plugin_loader when we add roles and reset it's cache, which the diff templars would just hit the new cache, once we unified the templar it would keep the initial list and not get a new one (faster but incorrect!). We can revert the change or try to trigger a refresh on the templar if it detects a change in the path list.  This probably affects lookups and tests also.

**Comment by mkrizek** [comment]
Just a note, the above reproducer (https://github.com/ansible/ansible/issues/57351#issuecomment-498698619) is no longer valid after https://github.com/ansible/ansible/pull/57489 has been merged. That PR limits `Templar.template()` calls if it's not needed. For the reproducer that means that previous to the PR we called the templating engine on data that were not templates and filters got initialized before we hit  `{{ '1.2.3.4' | parse_ip }}"`. Now with the PR, `{{ '1.2.3.4' | parse_ip }}"` is the first template that goes through templating engine and so the cache is empty and we initialize the filters with correct values which 'fixes' the reproducer case. However the issue is still present.

**Comment by mkrizek** [comment]
So the playbook needs to be changed to reproduce the issue again:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "force templating in delegate_to before we hit the second one with a filter"                                                                                                                         
      delegate_to: "{{ 'localhost' }}"

    - include_role:
        name: role_filter
```
