### ISSUE TITLE
postgresql_table fails on table in any other schema than public

### ISSUE THREAD

**Issue by AsgerPetersen** [ansible/ansible#57352]
##### SUMMARY

In the module `postgresql_table` the test for existing table is hard coded to the schema `public`.

The module does not expose a `schema` parameter like the [postgresql_ext](https://docs.ansible.com/ansible/latest/modules/postgresql_ext_module.html) and [postgresql_privs](https://docs.ansible.com/ansible/latest/modules/postgresql_privs_module.html) modules.

It is possible to have the module create a table in another schema by prefixing the table name with the schema, but then it fails to detect the presence later on because the schema is hard coded to `public` here https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/postgresql/postgresql_table.py#L268

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_table

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = None
  configured module search path = ['/Users/asger/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/asger/miniconda3/envs/ansible/lib/python3.6/site-packages/ansible
  executable location = /Users/asger/miniconda3/envs/ansible/bin/ansible
  python version = 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### CONFIGURATION

(There are no changes listed by `ansible-config dump --only-changed`)
```paste below

```

##### OS / ENVIRONMENT

Not relevant.

##### STEPS TO REPRODUCE

Execute the below tasks twice

```yaml
  - name: Ensure test_schema
    postgresql_schema:
        name: test_schema
        database: "{{dbname}}"
  - name: Ensure test_schema.test
    postgresql_table:
      db: "{{dbname}}"
      table: test_schema.test
      columns:
        - name text PRIMARY KEY NOT NULL
```

##### EXPECTED RESULTS

I would expect the module to support schemas and I would expect it not to fail detecting existing tables.

##### ACTUAL RESULTS

`postgresql_table` fails to detect the presence of the table and then fails.

```paste below
TASK [test : Ensure test_schema.test] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Cannot execute SQL 'CREATE TABLE \"test_schema\".\"test\" (name text PRIMARY KEY NOT NULL)': relation \"test\" already exists\n"}
```

##### SOLUTION
I suggest adding a `schema` parameter like in the [postgresql_ext](https://docs.ansible.com/ansible/latest/modules/postgresql_ext_module.html) and [postgresql_privs](https://docs.ansible.com/ansible/latest/modules/postgresql_privs_module.html) modules.
