### ISSUE TITLE
vmware_guest_disk Either 'datastore' or 'autoselect_datastore' is required parameter while creating disk for disk index [0].

### ISSUE THREAD

**Issue by meons** [ansible/ansible#57356]
##### SUMMARY

Unable to add virtual disk. I always get the same error message.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_disk – Manage disks related to virtual machine in given vCenter infrastructure

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
```

##### CONFIGURATION

```paste below
not relevant
```

##### OS / ENVIRONMENT

not relevant

##### STEPS TO REPRODUCE

```bash
ansible-playbook vmware_add_disk.yml -i myinventory -e "datacenter=mydc" -e "datastore=mydatastore" -e "target=mytestvm" -e "system_disk_size_gb=10"
```

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: add disk
    vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
      name: "{{ target|upper }}"
      disk:
        - size_gb: "{{ system_disk_size_gb }}"
          type: thin
          scsi_controller: 1
          datastore: "{{ datastore }}"
```

##### EXPECTED RESULTS

Virtual hard disk should be added to my virtual machine.

##### ACTUAL RESULTS

Even if add/remove some parameters from playbook, the error message is always the same.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Either 'datastore' or 'autoselect_datastore' is required parameter while creating disk for disk index [0]."}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/vmware`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/vmware)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/vmware/vmware_guest_disk.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest_disk.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_disk.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@meons Thanks for reporting this issue. I can reproduce this error only If I drop 'datastore' from disk configuration parameter. Could you please check if it specified in playbook ? Thanks.

needs_info

**Comment by Akasurde** [comment]
Console - 
```
changed: [localhost] => {
    "changed": true,
    "disk_changes": {
        "0": "Disk created."
    },
    "disk_data": {
        "0": {
            "backing_datastore": "ds_226_3",
            "backing_disk_mode": "persistent",
            "backing_eagerlyscrub": false,
            "backing_filename": "[ds_226_3] sample_0005/sample_0005.vmdk",
            "backing_thinprovisioned": false,
            "backing_writethrough": false,
            "capacity_in_bytes": 42949672960,
            "capacity_in_kb": 41943040,
            "controller_key": 1000,
            "key": 2000,
            "label": "Hard disk 1",
            "summary": "41,943,040 KB",
            "unit_number": 0
        },
        "1": {
            "backing_datastore": "ds_226_3",
            "backing_disk_mode": "persistent",
            "backing_eagerlyscrub": false,
            "backing_filename": "[ds_226_3] sample_0005/sample_0005_1001_2.vmdk",
            "backing_thinprovisioned": true,
            "backing_writethrough": false,
            "capacity_in_bytes": 10485760,
            "capacity_in_kb": 10240,
            "controller_key": 1001,
            "key": 2018,
            "label": "Hard disk 2",
            "summary": "10,240 KB",
            "unit_number": 2
        },
        "2": {
            "backing_datastore": "ds_226_3",
            "backing_disk_mode": "persistent",
            "backing_eagerlyscrub": false,
            "backing_filename": "[ds_226_3] sample_0005/sample_0005_1001_3.vmdk",
            "backing_thinprovisioned": true,
            "backing_writethrough": false,
            "capacity_in_bytes": 10485760,
            "capacity_in_kb": 10240,
            "controller_key": 1001,
            "key": 2019,
            "label": "Hard disk 3",
            "summary": "10,240 KB",
            "unit_number": 3
        }
    }
}
```

YAML
```yaml

---
- name: Issue 57356
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Add disk to existing VM
      vmware_guest_disk:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        name: sample_0005
        folder: "{{ folder }}"
        disk:
          - size_mb: 10
            type: thin
            datastore: "{{ datastore }}"
            scsi_controller: 1
            unit_number: 3
            scsi_type: "paravirtual"

```

**Comment by meons** [comment]
Sorry for the late reply I was pretty busy last days :s
@Akasurde it works with following config.

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: add disk
    vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ dc }}"
      validate_certs: no
      name: "{{ target|upper }}"
      disk:
        - size_gb: 1
          type: thin
          scsi_controller: 0
          unit_number: 6
          datastore: "{{ ds }}"
```
That's really weird because I have just added `unit_number` parameter. And by the way if remove it from my actual yaml, I get the following message.
`TASK [add disk] ***************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Please specify 'unit_number' under disk parameter at index [0], which is required while creating disk."}`
