### ISSUE TITLE
Setup is skipped when using tags with import_playbook

### ISSUE THREAD

**Issue by 1efty** [ansible/ansible#57362]
##### SUMMARY

When using `import_playbook`, and referencing a tag within the imported playbook, setup is skipped.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

import_playbook

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg
  configured module search path = [u'/Users/ljb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ljb/.pyenv/versions/2.7.15/envs/2.7-web-ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/ljb/.pyenv/versions/2.7-web-ansible/bin/ansible
  python version = 2.7.15 (default, Mar 15 2019, 22:13:43) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = -C -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = memory
DEFAULT_BECOME_METHOD(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = root
DEFAULT_HOST_LIST(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = [u'/Users/ljb/Workspaces/gitlab/ljb/web-ansible/inventory/dev.yml
DEFAULT_MANAGED_STR(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = Ansible Managed - ANY CHANGES WILL NOT PERSIST
DEFAULT_PRIVATE_ROLE_VARS(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = [u'/Users/ljb/Workspaces/gitlab/ljb/web-ansible/roles']
HOST_KEY_CHECKING(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = [u'yaml', u'auto']
RETRY_FILES_ENABLED(/Users/ljb/Workspaces/gitlab/ljb/web-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target: CentOS 7
Control: Fedora 30 & macOS 10.14

##### STEPS TO REPRODUCE

Create a playbook that uses `import_playbook` to import `another-playbook.yml`.

```yaml
# playbook-that-imports-playbook.yml
---

# the tag is located within this play, but the import_playbook tag is different
- import_playbook: another-playbook.yml
  tags:
     - some-tag
```

```yaml
# another-playbook.yml
---

- name: Another Playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - debug:
        msg: This is a test.
      tags:
        - tag-in-imported-playbook
```

Run `playbook-that-imports-playbook.yml` like such:

```
ansible-playbook playbook-that-imports-playbook.yml -t tag-in-imported-playbook
```

##### EXPECTED RESULTS

For the `gather_facts` playbook keyword to be respected, and for setup to run when referencing tags  in a playbook that is called by import_playbook.

##### ACTUAL RESULTS

Setup is skipped, so facts are not present during the play.

##### WORKAROUND

A workaround is to use the `gather_facts` or `setup` module with the `always` tag.  You may also set `gather_facts: false` at the play level to not have it run twice when directly calling the playbook.

```yaml
---

- name: Play
   hosts: all
   gather_facts: false
   tasks:
     - name: Setup
       setup:
       tags:
         - always
```

**NOTE** this works on 2.7.11
