### ISSUE TITLE
Adding devices while having multiple racks in Netbox 

### ISSUE THREAD

**Issue by DoctorKM** [ansible/ansible#57397]
##### SUMMARY

It appears that you cannot add devices while having more than one rack in Netbox, as ansible  seems to not be able to distinguish between racks.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

netbox_device
Also other netbox modules can be affected
##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04 with Netbox installation v.2.5.12

##### STEPS TO REPRODUCE

Just write short playbook that have to add/delete/modify netbox device while having more that one rack added in Netbox

```yaml
- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False

 tasks:
    - name: Create R1
       netbox_device:
                 netbox_url: http://netbox.local
                 netbox_token: MyToken
                 data:
                     name: R1
                     rack: rack1
                     position: 12
                     face: front
                     device_type: Force10
                     device_role: Switch1G
                     site: Test_site
                     status: Active
                  state: present
```

##### EXPECTED RESULTS

Add a Netbox device, in this case Force10 1G switch in rack1 at position 12
##### ACTUAL RESULTS

Got error and message as belowe.

```paste below
TASK [netbox : Create R1] ****************************************************************************************************************************************************************************
task path: /root/ansible-provisioning/roles/netbox/tasks/R1.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297 `" && echo ansible-tmp-1559727456.73-119493480192297="` echo /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/net_tools/netbox/netbox_device.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-16333oO4kyG/tmpBrcxwu TO /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297/AnsiballZ_netbox_device.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297/ /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297/AnsiballZ_netbox_device.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297/AnsiballZ_netbox_device.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1559727456.73-119493480192297/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_netbox_device_payload_2d7Q1S/__main__.py", line 243, in main
    result = ensure_device_present(nb, nb_endpoint, norm_data)
  File "/tmp/ansible_netbox_device_payload_2d7Q1S/__main__.py", line 267, in ensure_device_present
    data = _find_ids(nb, normalized_data)
  File "/tmp/ansible_netbox_device_payload_2d7Q1S/__main__.py", line 258, in _find_ids
    return find_ids(nb, data)
  File "/tmp/ansible_netbox_device_payload_2d7Q1S/ansible_netbox_device_payload.zip/ansible/module_utils/net_tools/netbox/netbox_utils.py", line 316, in find_ids
    "Multiple results found while searching for key: %s" % (k)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": {
                "device_role": 1, 
                "device_type": 1, 
                "face": 0, 
                "name": "R1", 
                "position": 12, 
                "rack": "1", 
                "site": 3, 
                "status": 1
            }, : 3, 
                "status": 1
            }, 
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "netbox_url": "http://37.233.99.15", 
            "state": "present", 
            "validate_certs": true
        }
    }, 
    "msg": "Multiple results found while searching for key: rack"
}
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "netbox_url": "http://37.233.99.15", 
            "state": "present", 
            "validate_certs": true
        }
    }, 
    "msg": "Multiple results found while searching for key: rack"
}

PLAY RECAP *******************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
