### ISSUE TITLE
LXC_container container config file not being populated with defined values

### ISSUE THREAD

**Issue by Fraeco** [ansible/ansible#57396]
##### SUMMARY

Configuration settings made in container_config aren't transported to the /path/to/container/config file. If you are using a non-default lxc.network.link setting the container will fail to start because it can't attach to the (non-existant) bridge device. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lxc_container

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)
vmware toolbox version 10.2.5.3619 (build-8068406)

##### STEPS TO REPRODUCE

Create a play with lxc_container containing a container_config section that sets settings that aren't default. Run the play and check the config file of the created container. 

```yaml
- name: Create a LXC container
  lxc_container:
    name: "{{ item }}"
    state: started
    template: centos
    container_config:
      - "lxc.network.type = veth"
      - "lxc.network.link = br0"
      - "lxc.network.flags = up"
      - "lxc.network.name = eth0"
      - "lxc.network.ipv4.address = 10.1.1.100/24"
      - "lxc.network.ipv4.gateway = 10.1.1.1"
      - "lxc.mount.entry =  /var/lib/lxc/commonfs /var/lib/lxc/{{ item }}/mnt none bind 0 0"
      - "lxc.include = /usr/share/lxc/config/centos.common.conf"
      - "lxc.arch = x86_64"
      - "lxc.autodev = 1"
  with_items:
    - "testcontainer-01"
```

##### EXPECTED RESULTS

That the container config file contains the entries made in the play "container_config", and not the defaults and that the container ends up in the requested state.
```
[root@hdp-cl-02 testcontainer-01]# cat config 
...
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.name = eth0
lxc.network.ipv4.gateway = 10.1.1.1
lxc.network.ipv4 = 10.1.1.100/24
...
```

##### ACTUAL RESULTS

The config file contains only defaults and the container fails to start.

```paste below
 [root@containerhost testcontainer-01]# cat config 
...
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = virbr0
lxc.rootfs = /var/lib/lxc/testcontainer-01/rootfs
...
```
