### ISSUE TITLE
service module breaks on older versions of Debian. (Debian 5.0 specifically)

### ISSUE THREAD

**Issue by goozbach** [ansible/ansible#574]
The command update-rc.d doesn't have an enable/disable option in older versions of Debian.

you see an error like this:

```
{"failed": 1, "rc": 1}

usage: update-rc.d [-n] [-f] <basename> remove

       update-rc.d [-n] <basename> defaults [NN | SS KK]

       update-rc.d [-n] <basename> start|stop NN runlvl [runlvl] [...] .

                -n: not really

                -f: force
```

The work around I found was to install the package sysv-rc-conf and use that command non-interactively like this

```
- name: enable $item service
  action: command sysv-rc-conf $item on
  with_items:
    - openvpn
    - ntpd
```

I don't think that changing the service module to use the sysv-rc-con command is the right answer.

I'm wondering what other people thing the "right way" to fix this might be.
