### ISSUE TITLE
Chocolatey install fails when fips is enabled

### ISSUE THREAD

**Issue by daemenseth** [ansible/ansible#57405]
##### SUMMARY
When you install chocolatey with win_chocolatey  on a server you get a rc 1 because of fips mode detected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
2.7.4

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT
Server 2019

##### STEPS TO REPRODUCE

```yaml
  - name: Ensure Chocolatey itself is installed and use internal repo as source
    win_chocolatey:
      name: chocolatey
    ignore_errors: yes
    # Above ignore_erros is because the fips compliant error
```

##### EXPECTED RESULTS
Install without rc 1

##### ACTUAL RESULTS

```
fatal: [host]: FAILED! => {
    "changed": false, 
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe list --local-only --exact --limit-output chocolatey", 
    "msg": "Error checking installation status for the package 'chocolatey'", 
    "rc": 1, 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "\r\nFIPS Mode detected - run 'choco feature enable -n useFipsCompliantChecksums'\r\n to use Chocolatey.\r\nWhen FIPS Mode is enabled, Chocolatey requires useFipsCompliantChecksums feature also be enabled.\r\n", 
    "stdout_lines": [
        "", 
        "FIPS Mode detected - run 'choco feature enable -n useFipsCompliantChecksums'", 
        " to use Chocolatey.", 
        "When FIPS Mode is enabled, Chocolatey requires useFipsCompliantChecksums feature also be enabled."
    ]
}

```
