### ISSUE TITLE
uncompress doesn't like FreeBSD

### ISSUE THREAD

**Issue by g--** [ansible/ansible#5741]
Uncompress doesn't work with FreeBSD, even after bsdtar has been replaced with gnutar.. it returns the generic error:

```
TASK: [unarchive test] ******************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/geoff/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'IdentityFile=/home/geoff/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1390500933.84-273596065993280 && chmod a+rx $HOME/.ansible/tmp/ansible-1390500933.84-273596065993280 && echo $HOME/.ansible/tmp/ansible-1390500933.84-273596065993280'"]
<127.0.0.1> EXEC ['ssh', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/geoff/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'Port=2200', '-o', 'IdentityFile=/home/geoff/.vagrant.d/insecure_private_key', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', u'/bin/sh -c \'sudo -k && sudo -H -S -p "[sudo via ansible, key=edzmehrtongamyzhfzooorkdpnkjjzuw] password: " -u root /bin/sh -c \'"\'"\'echo SUDO-SUCCESS-edzmehrtongamyzhfzooorkdpnkjjzuw; rc=0; [ -r "/tmp/foo" ] || rc=2; [ -f "/tmp/foo" ] || rc=1; [ -d "/tmp/foo" ] && rc=3; (/usr/bin/md5sum /tmp/foo 2>/dev/null) || (/sbin/md5sum -q /tmp/foo 2>/dev/null) || (/usr/bin/digest -a md5 /tmp/foo 2>/dev/null) || (/sbin/md5 -q /tmp/foo 2>/dev/null) || (/usr/bin/md5 -n /tmp/foo 2>/dev/null) || (/bin/md5 -q /tmp/foo 2>/dev/null) || (/usr/bin/csum -h MD5 /tmp/foo 2>/dev/null) || (echo "${rc}  /tmp/foo")\'"\'"\'\'']
  failed: [default] => {"failed": true}
  msg: dest must be an existing dir
```

I get the same behaviour with zip files.  I checked that md5 is installed and appears to be properly working.

You can reproduce the problem by downloading this tarball  and:

```
 $ tar -xzf ansible_freebsd_uncompress.tar.gz
 $ cd ansible_freebsd_uncompress
 $ vagrant up
 [downloads the image, boots the vm, runs the playbook]
 $ vagrant ssh
 [poke around.. debug]
 $ vagrant destroy
```

For quick reference, the playbook is:

``` yaml

---
- hosts: all
  sudo: yes

  pre_tasks:
    - name: pkg remote site file
      copy: src=freebsd.conf dest=/usr/local/etc/pkg/repos/FreeBSD.conf owner=root mode=0644
      notify:
              - pkgng update
  tasks:

    - name: install gnutar
      pkgng: name=gtar state=present cached=yes

    - name: force replace bsdtar with gnutar
      file: src=/usr/local/bin/gtar dest=/usr/bin/tar state=link force=yes

    - name: create /tmp/foo
      file: name=/tmp/foo state=directory owner=root mode=0755

    - name: unarchive test
      #unarchive: src=foo.zip dest=/tmp/foo
      unarchive: src=foo.tar.gz dest=/tmp/foo

  handlers:
    - name: pkgng update
      command: pkg update
```
