### ISSUE TITLE
meta module cannot condition against a variable produced from an iterative

### ISSUE THREAD

**Issue by drewmullen** [ansible/ansible#57427]
##### SUMMARY
the meta module cannot recognize a variable produced from an iterative

##### ISSUE TYPE
~- Bug Report~
- Documentation Report

##### COMPONENT NAME
meta

##### ANSIBLE VERSION
```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/dmullen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dmullen/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/dmullen/venv/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```
^^ also tested on 2.8
##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  vars:
    mylist:
        - '1'
        - '2'
        - '3'              
  tasks:
    - name: play 1
      debug:
        var: item
      when: item == '3'
      loop: "{{ mylist }}"

    - name: play 2
      meta: end_play
      when: item == '3'
      loop: "{{ mylist }}"
```

##### ACTUAL RESULTS
fails on play 2 saying it cannot find 'item'. have also tried with a `loop_var`, same results

```paste below
TASK [play 1] *****************************************
skipping: [localhost] => (item=1)
skipping: [localhost] => (item=2)
ok: [localhost] => (item=3) =>
  item: '3'
ERROR! The conditional check 'item == '3'' failed. The error was: error while evaluating conditional (item == '3'): 'item' is undefined

The error appears to have been in '/Users/dmullen/git/test-ansi-lynn/test.yml': line 16, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: play 2
      ^ here
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/utilities/helper/meta.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is expected as meta tasks are handled differently internally than 'normal tasks' so looping on meta tasks is not supported. We probably should alter the documentation to mention that and/or emit a warning on runtime.

As for your reproducer, I wonder what would be the real use case for looping on `meta: end_play`?

**Comment by drewmullen** [comment]
well, knowing that limitation now i can work around it. but yeah, i agree it should be mentioned in the docs and maybe even highlighted that meta is *special*. 

feel free to close or leave this open if you want to tag it to a PR

**Comment by samccann** [comment]
Documentation fix should be within the meta.py file, adding to the Notes section:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py#L46

**Comment by mkrizek** [comment]
@drewmullen if you really need to, as a workaround you can put your meta task in a file and include that file like so:
```yaml
- hosts: localhost
  gather_facts: no
  vars:
    mylist:
        - '1'
        - '2'
        - '3'
  tasks:
    - include_tasks:
        file: include-meta-task.yml
      when: item == '3'                                                                                                                                                                                           
      loop: "{{ mylist }}"

    - debug:
        msg: 'past end_play'
```

include-meta-task.yml:
```yaml
- meta: end_play
```
