### ISSUE TITLE
'VariableManager' object has no attribute '_loader'"

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#57437]
##### SUMMARY

In a complex variable resolution case, ansible fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vars

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = None
  configured module search path = ['/home/nikos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/nikos/Projects/my/ansible/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/nikos/Projects/my/ansible/ansible.cfg) = False
ANSIBLE_PIPELINING(/home/nikos/Projects/my/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/nikos/Projects/my/ansible/ansible.cfg) = -o ControlPath=/var/shm/contr>
ANY_ERRORS_FATAL(/home/nikos/Projects/my/ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/nikos/Projects/my/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/nikos/Projects/my/ansible/ansible.cfg) = data/.tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/nikos/Projects/my/ansible/ansible.cfg) = 7200
COLOR_DEBUG(/home/nikos/Projects/my/ansible/ansible.cfg) = magenta
DEFAULT_CALLBACK_PLUGIN_PATH(/home/nikos/Projects/my/ansible/ansible.cfg) = ['/home/nikos/Pro>
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = False
DEFAULT_EXECUTABLE(/home/nikos/Projects/my/ansible/ansible.cfg) = /bin/bash
DEFAULT_GATHERING(/home/nikos/Projects/my/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/nikos/Projects/my/ansible/ansible.cfg) = ['/home/nikos/Projects/my/da>
DEFAULT_LOOKUP_PLUGIN_PATH(/home/nikos/Projects/my/ansible/ansible.cfg) = ['/home/nikos/Proje>
DEFAULT_MANAGED_STR(/home/nikos/Projects/my/ansible/ansible.cfg) = Ansible managed (do not ed>
DEFAULT_ROLES_PATH(/home/nikos/Projects/my/ansible/ansible.cfg) = ['/home/nikos/Projects/my/a>
DEFAULT_STRATEGY(/home/nikos/Projects/my/ansible/ansible.cfg) = linear
DEFAULT_TIMEOUT(/home/nikos/Projects/my/ansible/ansible.cfg) = 30
DEFAULT_TRANSPORT(/home/nikos/Projects/my/ansible/ansible.cfg) = ssh
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/home/nikos/Projects/my/ansible/ansible.cfg) = True
DEFAULT_VARS_PLUGIN_PATH(/home/nikos/Projects/my/ansible/ansible.cfg) = ['/home/nikos/Project>
DEPRECATION_WARNINGS(/home/nikos/Projects/my/ansible/ansible.cfg) = False
DISPLAY_ARGS_TO_STDOUT(/home/nikos/Projects/my/ansible/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/nikos/Projects/my/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/nikos/Projects/my/ansible/ansible.cfg) = False
INVALID_TASK_ATTRIBUTE_FAILED(/home/nikos/Projects/my/ansible/ansible.cfg) = True
INVENTORY_ENABLED(/home/nikos/Projects/my/ansible/ansible.cfg) = ['yaml']
RETRY_FILES_ENABLED(/home/nikos/Projects/my/ansible/ansible.cfg) = False
USE_PERSISTENT_CONNECTIONS(/home/nikos/Projects/my/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Arch linux latest

##### STEPS TO REPRODUCE

The role I am using below is [this one](https://github.com/debops/debops/tree/master/ansible/roles/debops.users).

```yaml
- hosts: server
  vars:
    features:
      - mailserver
    mailserver_accounts:
      - name: mail
        group: mail
    users__accounts: >-  # used by debops.users
      [
        {%- for f in features -%}
          {%- if lookup('vars', f + '_accounts', default='') -%}
            {%- for account in lookup('vars', f + '_accounts') -%}
              {{ account | to_json }},
            {%- endfor -%}
          {%- endif -%}
        {%- endfor -%}
      ]
  tasks:
    - include_role:
        name: debops.users
```

##### EXPECTED RESULTS

I would expect the role to succeed. If I replace `users__accounts` with:

```yaml
user__acounts:
  - name: mail
    group: mail
```

ansible does not fail.

##### ACTUAL RESULTS

```paste below
TASK [debops.users : Install required packages name={{ q("flattened", (users__base_packages + users__shell_packages + users__packages)) }}, state=present] ***
task path: /home/nikos/Projects/my/ansible/roles/system/debops.users/tasks/main.yml:4
fatal: [server]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{{ lookup(\"template\", \"lookup/users__shell_packages.j2\") }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ users__groups + users__group_groups + users__host_groups + users__dependent_groups + users__default_accounts + users__accounts + users__group_accounts + users__host_accounts + users__dependent_accounts }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '[\n  {%- for f in features -%}\n    {%- if lookup('vars', f + '_accounts', default='') -%}\n      {%- for account in lookup('vars', f + '_accounts') -%}\n        {{ account | to_json }},\n      {%- endfor -%}\n    {%- endif -%}\n  {%- endfor -%}\n]'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'vars'. Error was a <class 'AttributeError'>, original message: 'VariableManager' object has no attribute '_loader'"
}
```
