### ISSUE TITLE
Make the redhat_subscription module idempotent

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible#57472]
##### SUMMARY
Currently the redhat_subscription module does not appear to be idempotent, warranting workarounds within the playbook to check for registered systems.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

redhat_subscription

##### ADDITIONAL INFORMATION

Currently, the workaround being used is as follows

```yaml
---
- name: Check whether the system is already registered
  command: subscription-manager status
  register: rhsm_status
  become: yes
  ignore_errors: yes

- name: Register host to RHSM and attach pool
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool }}"
    consumer_name: "{{ rhsm_consumer_name | default(omit) }}"
    state: present
  become: yes
  when: rhsm_status.rc != 0
```

Ideally, the module should handle this and not fail if the system is currently registered.
