### ISSUE TITLE
vmware_guest_file_operation copy with binary file not work with python 3.6

### ISSUE THREAD

**Issue by stravassac** [ansible/ansible#57475]
##### SUMMARY
Using vmware_guest_file_operation copy binary file work with Python 2.7 but not with Python 3.6

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_file_operation

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /home/stravassac/.ansible.cfg
  configured module search path = ['/home/stravassac/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stravassac/virtualenvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/stravassac/virtualenvs/ansible/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```
- name: test un
  hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
    var_my_file: "hostnamectl"
  tasks:
    - name: file
      vmware_guest_file_operation:
        hostname: XXXXXXXX
        username: "{{ lookup('env','VMWARE_USER') }}"
        password: "{{ lookup('env','VMWARE_PASSWORD') }}"
        datacenter: XXXXX
        validate_certs: False
        folder: /vm/
        vm_id: test1
        vm_username: root
        vm_password: toor
        copy:
          src: "/usr/bin/{{var_my_file}}"
          dest: "/root/{{var_my_file}}"
          #overwrite: True

      delegate_to: localhost
```

##### EXPECTED RESULTS

Copy binary file

##### ACTUAL RESULTS

```paste below
"msg": "'utf-8' codec can't decode byte 0xf8 in position 96: invalid start byte"

```
