### ISSUE TITLE
Support different config.toml options in gitlab_runner module

### ISSUE THREAD

**Issue by rnestler** [ansible/ansible#57483]
##### SUMMARY
It looks like the [gitlab_runner module](https://docs.ansible.com/ansible/latest/modules/gitlab_runner_module.html) is currently only able to register runners and change the server settings (those available on https://gitlab.example.com/admin/runners/).

It would be awesome to also be able to configure the [advanced local settings](https://docs.gitlab.com/runner/configuration/advanced-configuration.html) of the gitlab-runner which are stored in the runners `config.toml`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gitlab_runner

##### ADDITIONAL INFORMATION

One would need to distinguish between the [global section](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section) which are applicable for all runners on the machine and the [runners section](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section) which configure a single runner.

It may look something like that:
```yaml
- name: "Register runner"
  gitlab_runner:
    api_url: https://gitlab.example.com/
    api_token: "{{ access_token }}"
    registration_token: 4gfdsg345
    description: Docker Machine
    state: present
    active: True
    tag_list: ['docker']
    run_untagged: False
    locked: False
    local_settings:
      executor: "docker"
      docker:
         privileged: False
         image: ubuntu:16.04
```

Some questions:
 * Should the module support a list of runners directly?
 * How do we guarantee that the correct section of the config.toml file is modified?
