### ISSUE TITLE
Git module fails to clone non-branch, non-head ref (github pull requests)

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#57497]
##### SUMMARY
The git module will not clone github pull requests. A workaround is possible, but it makes things messy.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git module

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/tmp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
only defaults

##### OS / ENVIRONMENT
CentOS

##### STEPS TO REPRODUCE

`ansible-playbook -i localhost, --connection=local issues/PR_checkout.yml`, where the playbook, `cat issues/PR_checkout.yml` is:

```yaml
- hosts: all
  gather_facts: false
  tasks:
      - name: update project using git
        git:
          dest: "/tmp/foo_dir"
          repo: "https://github.com/ansible/test-playbooks.git"
          version: "pull/62/head"  # PR exists, also, branch name "with_requirements" actually works
          force: false
```

##### EXPECTED RESULTS
I expect it to work just like a branch clone. Follow the instruction in the comment to change it to a branch clone.

```
$ ansible-playbook -i localhost, --connection=local issues/PR_checkout.yml 

PLAY [all] ************************************************************************************************************************************************************************************************

TASK [update project using git] ***************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************************************
localhost                
```

##### ACTUAL RESULTS

```
$ ansible-playbook -i localhost, --connection=local issues/PR_checkout.yml 

PLAY [all] ************************************************************************************************************************************************************************************************

TASK [update project using git] ***************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "cmd": "/usr/bin/git checkout --force pull/62/head", "msg": "Failed to checkout pull/62/head", "rc": 1, "stderr": "error: pathspec 'pull/62/head' did not match any file(s) known to git.\n", "stderr_lines": ["error: pathspec 'pull/62/head' did not match any file(s) known to git."], "stdout": "", "stdout_lines": []}

PLAY RECAP ************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

The culprit is probably related to assumptions baked in here:

https://github.com/ansible/ansible/blob/0dfc21c8268ab93c3ce0f6f2c1332cf6ab1b5af4/lib/ansible/modules/source_control/git.py#L762-L776

see:

> if refspecs is empty, i.e. version is neither heads nor tags assume it is a version hash 

Categorically, a pull request reference is _not_ a head _or_ a tag _or_ a version hash. The workaround involves an intermediate local directory:

```yaml
- hosts: all
  gather_facts: false
  connection: local
  tasks:
      - name: do bare clone with refspec
        git:
          dest: "/tmp/foo_dir1"
          repo: "https://github.com/ansible/test-playbooks.git"
          force: false
          bare: true
          refspec: +refs/pull/62/head:tmp_branch

      - name: clone from the local bare repo
        git:
          dest: "/tmp/foo_dir2"
          repo: "/tmp/foo_dir1"
          version: "tmp_branch"
          force: false
```

I believe that this should not be necessary, and that a single task (and a single repo) should be able to accomplish this common task with a code change made to the git module.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/source_control/git.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by AlanCoding** [comment]
After going back and re-reading the docs _very carefully_ I might have to walk back some of what I said here. For the refspec option, the docs say:

> Add an additional refspec to be fetched. If version is set to a SHA-1 not reachable from any branch or tag, this option may be necessary to specify the ref containing the SHA-1. Uses the same syntax as the 'git fetch' command. An example value could be "refs/meta/config".

So suggests that my goal should be accomplishable in a single command... but maybe it's not so obvious _how_. Here is the trial-and-error process I went through:

```yaml
- hosts: all
  gather_facts: false
  connection: local
  vars:
    repo_dir: "/tmp/foo_dir"
  tasks:
    - name: Remove any existing directory from prior runs
      file:
        state: absent
        path: "{{ repo_dir }}"

    - name: update project using git
      git:
        dest: "{{ repo_dir }}"
        repo: "https://github.com/ansible/test-playbooks.git"
        version: "pull/62/head"  # PR exists, also, branch name "with_requirements" actually works
        force: false
        # refspec: +refs/heads/*:refs/heads/*  # 'pull/62/head' did not match any file(s) known to git
        # refspec: +refs/pull/62/head:tmp_branch  # 'pull/62/head' did not match any file(s) known to git
        # refspec: +refs/*:refs/*  # Refusing to fetch into current branch refs/heads/master of non-bare repository
        # refspec: refs/heads/*:refs/remotes/origin/*  # 'pull/62/head' did not match any file(s) known to git
        # refspec: refs/*:refs/remotes/origin/*  # works, but inefficient
        # refspec: refs/pull/62/head  # pathspec 'pull/62/head' did not match any file(s) known to git
                                      # but works if version option is not supplied
        # refspec: refs/pull/62/head:refs/remotes/origin/pull/62/head  # works
        refspec: +refs/pull/62/head:refs/remotes/origin/pull/62/head  # works
```

It seems that the documentation is going in a different direction than I am, assuming that `refspec` is provided _in lieu of_ `version`. I'm interested in either providing both for a concrete clone, or only providing the refspec for a bare clone. The refspec syntax from the docs doesn't work for the bare clone case either due to more complications ("Refusing to fetch into current branch refs/heads/master of non-bare repository").

Looks like I might have what I need. I'll close this issue in a while if nothing here can be distilled into a logical patch to the docs.
