### ISSUE TITLE
postgresql_pg_hba does not correctly handle multiple options

### ISSUE THREAD

**Issue by ECRR** [ansible/ansible#57505]
##### SUMMARY
When there are multiple authentication options and multiple hosts, only the first authentication option is retained for hosts prior to the last

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql-pg-hba-module

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /home/user/PROJECT/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/user/PROJECT/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/home/user/PROJECT/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/home/user/PROJECT/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/PROJECT/ansible.cfg) = ./cachedir
CACHE_PLUGIN_TIMEOUT(/home/user/PROJECT/ansible.cfg) = 86400
DEFAULT_FORKS(/home/user/PROJECT/ansible.cfg) = 20
DEFAULT_GATHERING(/home/user/PROJECT/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/user/PROJECT/ansible.cfg) = [u'/home/user/PROJECT/enviroments/P1']
INVENTORY_CACHE_ENABLED(/home/user/PROJECT/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/home/user/PROJECT/ansible.cfg) = jsonfile
```

##### STEPS TO REPRODUCE

```yaml
- name: "Postgres pg_hba"
  postgresql_pg_hba:
    dest: "/var/opt/rh/rh-postgresql96/lib/pgsql/data/pg_hba.conf"
    create: "yes"
    contype: "hostssl"
    method: "cert"
    group: "postgres"
    owner: "postgres"
    options: "clientcert=1 map=mymap"
    address: "{{ item }}"
  loop: "{{ [ 'red', 'blue' ] }}"
```

##### EXPECTED RESULTS

pg_hba.conf should contain
```
hostssl	all	all	red	cert	clientcert=1 map=mymap
hostssl	all	all	blue	cert	clientcert=1 map=mymap
```

##### ACTUAL RESULTS
Only the final hostssl entry contains the map entry. Changing the order of the options consistently results in only the first option being preserved.

pg_hba.conf actually contains
```
hostssl	all	all	red	cert	clientcert=1
hostssl	all	all	blue	cert	clientcert=1 map=mymap
```
