### ISSUE TITLE
b64encode filter is incorrect in some cases (incorrect padding)

### ISSUE THREAD

**Issue by chengchengmu** [ansible/ansible#57521]
##### SUMMARY

The b64encode filter in ansible (2.8.0) does not give the correct value in some cases.
Noticed that in those cases, the last character is incorrect.
As a consequence, b64decode on the same value would not give back the original data.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

b64encode filter

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.8.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 3.7.3 (default, Apr 30 2019, 22:50:54) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION

Output of this command is empty
```paste below
```

##### OS / ENVIRONMENT

Amazon Linux 2  Linux Kernel 4.14.77-81.59.amzn2.x86_64 
Centos 7 Linux Kernel 4.4.179-1

##### STEPS TO REPRODUCE

Generate random file (long enough), ruse b64encode filter to encode the content until finding that the b64 encoded value is incorrect.

Example of playbook:
(see data.zip file in attachment, it's just a binary file, but had named it .zip because of github limitations.)
```yaml
---
- name: e
  hosts: local
  connection: local
  gather_facts: yes
  tasks:
    - name: base64 encode using ansible filter
      set_fact:
        b64encoded_data: "{{ lookup('file', 'data.zip' ) | b64encode }}"
    - debug:
        var: b64encoded_data

```

##### EXPECTED RESULTS

We expect the encoded value ends with the character M for this particular file (data.zip)

##### ACTUAL RESULTS

When actually executed:
The encoded value ends with the equal character: '='.

```paste below
python3 /bin/ansible-playbook  -i local, -vvvv ansible_b64encode.yml
```
[data.zip](https://github.com/ansible/ansible/files/3264124/data.zip)
