### ISSUE TITLE
vmware_vcenter_statistics doesn't change anything

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#57535]
##### SUMMARY
You cannot change anything with vmware_vcenter_statistics if you don't change at least one statistics level. These are the lines 348 and following:
```python
if not self.module.check_mode:
    if increase_level:
        # Loop in forward order (start with past day interval)
        for statistic in change_statistics_list:
            self.update_perf_interval(perf_manager, statistic)
    if decrease_level:
        # Loop in reverse order (start with past year interval)
        for statistic in change_statistics_list[::-1]:
            self.update_perf_interval(perf_manager, statistic)
```
You see, if you don't have at least one statistics level change, both increase_level and decrease_level are False and no changes are made.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vcenter_statistics

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.1 (default, Oct 26 2017, 01:54:52) [GCC 6.3.0]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
I think this is irrelevant.

##### STEPS TO REPRODUCE
```yaml
- hosts: vcenter
  connection: local
  gather_facts: no
  tasks:
    - name: Configure vCenter server statistics
      vmware_vcenter_statistics:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        interval_past_day:
          enabled: true
        interval_past_week:
          enabled: true
        interval_past_month:
          enabled: true
        interval_past_year:
          enabled: false
```

##### EXPECTED RESULTS
Past year statistic collection is disabled.

##### ACTUAL RESULTS
Nothing, although ansible says so:
```
PLAY [vcenter] ****************************************************************
TASK [Configure vCenter server statistics] *************************************

changed: [myvcenter.example]

PLAY RECAP *********************************************************************
myvcenter.example      : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
