### ISSUE TITLE
List support for mysql_user privs

### ISSUE THREAD

**Issue by meersjo** [ansible/ansible#57533]
##### SUMMARY

Allow lists or dictionaries for privilege specifications, for enhanced readability.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- mysql_user module

##### ADDITIONAL INFORMATION

Currently, mysql_user privileges are specified using a single string and a forward slash as separator between different sets of privileges.

However, when a single user requires multiple privilege sets, this quickly becomes unreadable and hard to maintain:
```yaml
- mysql_user:
    name: user1
    privs: "db1.*:ALL/db2.*:SELECT,INSERT/db3.table1,table2:SELECT/db3.table3:SELECT,DELETE"
```

I propose list support for increased legibility:
```yaml
- mysql_user:
    name: user1
    privs:
      - "db1.*:ALL"
      - "db2.*:SELECT,INSERT"
      - "db3.table1,table2:SELECT"
      - "db3.table3:SELECT,DELETE"
```

Alternatively, a dictionary would further increase clarity and maintainability by separating objects from privileges:
```yaml
- mysql_user:
    name: user1
    privs:
      "db1.*": "ALL"
      "db2.*": "SELECT,INSERT"
      "db3.table1,table2": "SELECT"
      "db3.table3": "SELECT,DELETE"
```
