### ISSUE TITLE
Add modules to support manipulation of borgbase SSH keys and repositories

### ISSUE THREAD

**Issue by adhawkins** [ansible/ansible#57548]
##### SUMMARY
Add ansible modules to allow the manipulation of borgbase SSH keys and repositories

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
borgbase_ssh
borgbase_repo

##### ADDITIONAL INFORMATION

https://www.borgbase.com/

This would allow the scripted creation of borg repositories hosted at borgbase, allowing automatic configuration of server backups using borg.

```yaml

- name: Read key from file
  slurp:
    src: ~/.ssh/id_rsa.pub
  register: ssh_key
  check_mode: yes

- name: Create key
  borgbase_ssh:
    state: present
    email: "{{ borgbase_email }}"
    password: "{{ borgbase_password }}"
    name: "root@{{ ansible_hostname }}"
    key: "{{ ssh_key['content'] | b64decode }}"
  register: borgbase_key

- name: Create repo
  borgbase_repo:
    state: present
    email: "{{ borgbase_email }}"
    password: "{{ borgbase_password }}"
    name: "{{ ansible_hostname }}"
    full_access_keys: [ "{{ borgbase_key.key_id }}" ]
    quota_enabled: false
    alert_days: 1
  register: borgbase_repo

```
