### ISSUE TITLE
yum_repository is not idempotent

### ISSUE THREAD

**Issue by maverick1982** [ansible/ansible#57541]
##### SUMMARY
Molecule idempotence test fails when I add a yum repository with yum_repository module and than install a package contained in that repository with yum module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION
```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/###/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/###/Workspace/galaxy/galaxy_env/local/lib/python2.7/site-packages/ansible
  executable location = /home/###/Workspace/galaxy/galaxy_env/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT

Host: Ubuntu 16.04
Target: CentOS 7.3 / CentOS 7.4

##### STEPS TO REPRODUCE
Run twice the task below

```
---
- name: Add Google repository
  yum_repository:
      name: "google-chrome"
      description: "Google Chrome"
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub
      enabled: yes
      gpgcheck: yes
      state: present

- name: Install packages
  yum:
      name: google-chrome-stable
      update_cache: yes
      state: present

```

##### EXPECTED RESULTS
I expect no changes in the second run

##### ACTUAL RESULTS
Second run report changes on "Add Google repository" task.
After that, if i run again and again the playbook, both tasks give no changes.

```
--> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
* [centos-7.3] => chrome : Add Google repository
An error occurred during the test sequence action: 'idempotence'. Cleaning up.

```
