### ISSUE TITLE
[Feature Req] [win_domain_user] add a creation return value

### ISSUE THREAD

**Issue by tbennett6421** [ansible/ansible#57547]
##### SUMMARY

For the win_domain_user module, it would be nice to have a Boolean returned value called `created` as `changed` would not always been indicative of creation.

>  update_password: Note that `always` will always report an Ansible status of 'changed' because we cannot determine whether the new password differs from the old password.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_domain_user

##### ADDITIONAL INFORMATION
I think anyone that wants to manage service accounts or guest accounts where the password is always going to be set to a known value would have a need for being able to distinguish when a user is created vs when the account is first provisioned.

I'm currently just doing lab work, but I think the distinction would be nice and that there would be numerous use cases other then the example below.

```yaml
    - name: Generate kiosk accounts
      win_domain_user:
        name: kiosk1
        password: correcthorsebatterystaple
        state: present
        password_never_expires: yes
        user_cannot_change_password: yes
      register: guest_creation
    
    - name: add user to a firewall access policy
      uri:
        url: https://fw.example.com/api/users/untrusted_group/add/kiosk1?token={{ oauth_token }}
        method: POST
        status_code: 201
      when: guest_creation.created
```
