### ISSUE TITLE
service unreachable error in async mode

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#57560]
##### SUMMARY

service restart fails in async mode

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

service

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  configured module search path = ['/Users/hryamzik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
[defaults]
inventory = inventory
retry_files_save_path = retry
ansible_managed = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
nocows = 1
callback_whitelist = timer
stdout_callback = skippy
display_skipped_hosts = False
force_handlers = True
host_key_checking = False
roles_path = ../roles

[ssh_connection]
pipelining = False
control_path = %(directory)s/%%h-%%p
```

##### OS / ENVIRONMENT

`18.04.1 LTS (Bionic Beaver)`, openvpnas instance

##### STEPS TO REPRODUCE

- Configure openvpn based on openvpnas
- Configure ansible connection over VPN
- Run playbook with restart handler

`handlers/main.yml`:

```yaml
- name: restart openvpn
  debug: msg="restarting openvpn"
  changed_when: yes
  notify:
      - restart openvpn raw
      - reconnect

- name: restart openvpn raw
  service: name=openvpnas state=restarted
  ignore_errors: yes
  async: 300
  poll: 0
  
- name: reconnect
  wait_for_connection:
    delay: 5
    timeout: 300
```

##### EXPECTED RESULTS

No errors

##### ACTUAL RESULTS

```
fatal: [vpn]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 10.10.10.2 port 22: Connection refused", "unreachable": true}
```
