### ISSUE TITLE
file module reports "absent" on PermissionError

### ISSUE THREAD

**Issue by Jakski** [ansible/ansible#57573]
##### SUMMARY
`file` module reports `absent`, when it can't access path to delete.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`file` module

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = None
  configured module search path = ['/home/jakski/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jakski/lib/ansible
  executable location = /home/jakski/venv/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```
It's from commit `c50a75a41e902cebf9f6438818570306e3ea71ba`(`devel` branch).

##### CONFIGURATION
`ansible-config dump --only-changed` doesn't return anything. I didn't overwrite any defaults.

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - file:
        path: tst
        state: directory

    - file:
        path: tst/test1
        state: touch

    - file:
        path: tst
        state: directory
        mode: 0000

    - file:
        path: tst/test1
        state: absent

    - file:
        path: tst
        state: directory
        mode: 0700

    - stat:
        path: tst/test1
      register: _test1

    - fail:
        msg: File tst/test1 still exists
      when: _test1.stat.exists
```

##### EXPECTED RESULTS

File should be removed or `file` module should report error, that it can't access path.

##### ACTUAL RESULTS

Ansible runs all tasks and reports error:

```
TASK [fail] ***********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "File tst/test1 still exists"}
```
Deleting `tst/test1` is being reported as an unchanged task.
