### ISSUE TITLE
Allow block to change strategie

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#57606]
##### SUMMARY

The blocks should be able to change the strategy within a playbook.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Blocks

##### ADDITIONAL INFORMATION

When provisioning a windows environment with multiple domain controllers, both domain controllers get simultaneously provisioned as a independent domain.

The role would be more clean if one could just specify:
```yaml
- name: Do sequentially
  strategy: serial
  block:
  - name: Create Domain and Forest
    win_domain:
      create_dns_delegation: no
      dns_domain_name: '{{ ad_domain_name }}'
      safe_mode_password: '{{ ad_dsr_password }}'
    register: ad_create_domain
  - name: Provision as Domain Controller
    win_domain_controller:
      state: domain_controller
      safe_mode_password: '{{ ad_dsr_password }}'
      dns_domain_name: '{{ ad_domain_name }}'
      domain_admin_password: '{{ ad_domain_user.password }}'
      domain_admin_user: '{{ ad_domain_user.name }}@{{ ad_domain_name }}'
    register: win_provision
    when: not ad_create_domain.changed
  - name: Reboot if provisioning requires it.
    win_reboot: null
    when: ad_create_domain.reboot_required or win_provision.reboot_required
```

This way the first domain controller is fully operational when the win_domain_controller module runs on the 2nd server and therefore adds it into the existing domain instead of creating a new one.

Currently there is a [workaround](https://shasawas.wordpress.com/2017/01/30/how-to-run-a-particular-task-serially-in-the-middle-of-the-play-in-ansible/), by specifying the task with:
```yaml
delegate_to: "{{item}}"
with_items: groups['Target']
run_once: true
```
But this requires hardcoding the group name within a role which is not desirable.

Edit: maybe the above example is not that great, I could also just have used run_once: true on the win_domain_controller module with a reboot action within a block, but when doing windows things, there are often situations, where stuff just depends on something else with a reboot in between, but everything else is fine when run parallel, like installing roles...
