### ISSUE TITLE
Regression: --diff does not produce output when template creates new file

### ISSUE THREAD

**Issue by vlitvin** [ansible/ansible#57618]
##### ISSUE TYPE
- Bug Report
- Regression

##### COMPONENT NAME
template module

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = None
```
ansible 2.8.0 is also affected

##### STEPS TO REPRODUCE

Create two files: template and playbook to generate file based on template

template: ./template_test.j2
```text
{{ ansible_managed }}
```

playbook: ./template_test.yaml
```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: create new file from template
      template:
        src:  template_test.j2
        dest: /path/to/file
```

Then run playbook: `ansible-playbook ./template_test.yaml --check --diff`

##### EXPECTED RESULTS
```
TASK [create new file from template] *************************
--- before
+++ after: <tmp_path>/template_test.j2
@@ -0,0 +1 @@
+Ansible managed

changed: [localhost]
```

##### ACTUAL RESULTS
```paste below
TASK [create new file from template] *************************
changed: [localhost]
```
