### ISSUE TITLE
yum hangs if gpg file needs to be downloaded

### ISSUE THREAD

**Issue by simpss** [ansible/ansible#57628]
##### SUMMARY

yum installations hang if repo needs to download gpg key file. I suspect it has something to do with an unhandled input request from yum. As if the same command is ran manually it asks if a downloaded GPG file is ok. Once the file has been added, ansible yum module starts working again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`lib/ansible/modules/packaging/os/yum_repository.py`
##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"

##### STEPS TO REPRODUCE

add repository with gpg key, try to install a package from it

```yaml
- name: Add k8s repo
  yum_repository:
    name: kubernetes
    file: kubernetes
    description: Kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    exclude: kube*
- name: install kubelet, kubeadm, kubectl
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes
    #disable_gpg_check: yes # workaround so it doesn't hang.
```

##### EXPECTED RESULTS

Package is installed or job fails because of missing signature file and a warning/error is emitted.
Might need to add an extra param to allow donwloading the gpg file?

##### ACTUAL RESULTS

ansible just hangs, no extra output is given.

```paste below
TASK [kubeadm : install kubelet, kubeadm, kubectl] *********************************************************************************************************************
```
