### ISSUE TITLE
vmware_guest: clone_with_convert.yml is failing

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#57653]
##### SUMMARY

vmware_guest's clone_with_convert.yml test playbook is failing with the following error:

```
TASK [vmware_guest : clone vm from template and convert to thin] **********************************************************************************************************************************
task path: /home/goneri/.ansible/test/tmp/vmware_guest-5GRWYH-ÅÑŚÌβŁÈ/test/integration/targets/vmware_guest/tasks/clone_with_convert.yml:5
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: goneri
<testhost> EXEC /bin/sh -c 'echo ~goneri && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258 `" && echo ansible-tmp-1560192695.04-170780141578258="` echo /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258 `" ) && sleep 0'                                                                                                                      
Using module file /home/goneri/git_repos/ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
<testhost> PUT /home/goneri/.ansible/tmp/ansible-local-17595A2ones/tmpFXShM2 TO /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258/AnsiballZ_vmware_guest.py
<testhost> EXEC /bin/sh -c 'chmod u+x /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258/ /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258/AnsiballZ_vmware_guest.py && sleep 0'                                                                                                                                                                                  
<testhost> EXEC /bin/sh -c 'VMWARE_VALIDATE_CERTS=no VMWARE_PROXY_HOST=esxi1-gw.ws.testing.ansible.com VMWARE_PROXY_PORT=11153 /home/goneri/.virtualenvs/ansible/bin/python /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258/AnsiballZ_vmware_guest.py && sleep 0'                                                                                                                 
<testhost> EXEC /bin/sh -c 'rm -f -r /home/goneri/.ansible/tmp/ansible-tmp-1560192695.04-170780141578258/ > /dev/null 2>&1 && sleep 0'
failed: [testhost] (item={u'folder': u'F0', u'name': u'DC0_H0_VM0'}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "convert": "thin", 
            "customization": {}, 
            "customization_spec": null, 
            "customvalues": [], 
            "datacenter": "DC0", 
            "datastore": null, 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": "F0", 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "vcenter.test", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "thin_DC0_H0_VM0", 
            "name_match": "first", 
            "networks": [], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "proxy_host": "localhost", 
            "proxy_port": 8888, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredoff", 
            "state_change_timeout": 0, 
            "template": "DC0_H0_VM0", 
            "use_instance_uuid": false, 
            "username": "administrator@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_customization": false, 
            "wait_for_ip_address": false
        }
    }, 
    "item": {
        "folder": "F0", 
        "name": "DC0_H0_VM0"
    }, 
    "msg": "Failed to create a virtual machine : A specified parameter was not correct: disk[0].diskId"
}
<testhost> EXEC /bin/sh -c 'echo ~goneri && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868 `" && echo ansible-tmp-1560192702.49-257173125343868="` echo /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868 `" ) && sleep 0'                                                                                                                      
Using module file /home/goneri/git_repos/ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
<testhost> PUT /home/goneri/.ansible/tmp/ansible-local-17595A2ones/tmpqCBHLA TO /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868/AnsiballZ_vmware_guest.py
<testhost> EXEC /bin/sh -c 'chmod u+x /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868/ /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868/AnsiballZ_vmware_guest.py && sleep 0'                                                                                                                                                                                  
<testhost> EXEC /bin/sh -c 'VMWARE_VALIDATE_CERTS=no VMWARE_PROXY_HOST=esxi1-gw.ws.testing.ansible.com VMWARE_PROXY_PORT=11153 /home/goneri/.virtualenvs/ansible/bin/python /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868/AnsiballZ_vmware_guest.py && sleep 0'                                                                                                                 
<testhost> EXEC /bin/sh -c 'rm -f -r /home/goneri/.ansible/tmp/ansible-tmp-1560192702.49-257173125343868/ > /dev/null 2>&1 && sleep 0'
failed: [testhost] (item={u'folder': u'F0', u'name': u'DC0_H0_VM1'}) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "convert": "thin", 
            "customization": {}, 
            "customization_spec": null, 
            "customvalues": [], 
            "datacenter": "DC0", 
            "datastore": null, 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": "F0", 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "vcenter.test", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "thin_DC0_H0_VM1", 
            "name_match": "first", 
            "networks": [], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "proxy_host": "localhost", 
            "proxy_port": 8888, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredoff", 
            "state_change_timeout": 0, 
            "template": "DC0_H0_VM1", 
            "use_instance_uuid": false, 
            "username": "administrator@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_customization": false, 
            "wait_for_ip_address": false
        }
    }, 
    "item": {
        "folder": "F0", 
        "name": "DC0_H0_VM1"
    }, 
    "msg": "Failed to create a virtual machine : A specified parameter was not correct: disk[0].diskId"
}
Read vars_file 'integration_config.yml'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

**Comment by goneri** [comment]
I face a similar issue with `clone_customize_guest_test.yml`:

```
    "msg": "Failed to create a virtual machine : A specified parameter was not correct: disk[0].diskId"
```

**Comment by ansibot** [comment]
@goneri: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @dav1x @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tomaszorlowski54** [comment]
Hey, I am facing the same issue. I was trying to change vm disks type by using ```convert``` option and I am always getting this error. I was trying to clone from different machines with different disks layout and still with out success. I only want to add that with out this parameter, cloning works perfectly. Am I using it wrong or it's a bug?
os `centos7`, ansible:

```ansible 2.8.1
  config file = /home/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
task code:
```
- name: Deploy VM from template
  vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    validate_certs: no
    datacenter: '{{ deploy_vsphere_datacenter }}'
    cluster: '{{ deploy_vsphere_cluster }}'
    folder: '{{ deploy_vsphere_folder }}'
    datastore: "{{ deploy_vsphere_datastore }}"
    name: '{{ guest_hostname }}'
    guest_id: '{{ guest_id }}'
    convert: 'thick'
    force: yes
    networks:
    - name: '{{ vlan1 }}'
      start_connected: "{{ connected }}"
      ip: '{{ vlan1 }}'
      netmask: '{{ vlan1 }}'
      gateway: '{{ vlan1 }}'
      dns_servers:
      - '{{ guest_dns_server }}'
    - name: '{{ vlan2 }}' 
      start_connected: "{{ connected }}"
      ip: '{{ vlan2 }}'
      netmask: '{{ vlan2 }}'
      gateway: '{{ vlan2 }}'
      dns_servers:
       - '{{ guest_dns_server }}'
    - name: '{{ vlan3 }}'
      start_connected: "{{ connected }}"
      ip: '{{ vlan3 }}'
      netmask: '{{ vlan3 }}'
      gateway: '{{ vlan3 }}'
      dns_servers:
      - '{{ guest_dns_server }}'
    hardware:
      memory_mb: '{{ guest_memory }}'
      num_cpus: '{{ guest_vcpu }}'
    customization:
      dns_servers:
      - '{{ guest_dns_server }}'
      domain : '{{ guest_domain_name }}'
      hostname: '{{ guest_hostname }}'
    template: '{{ guest_template }}'
    wait_for_ip_address: yes
    state: poweredon
  delegate_to: localhost
  tags: create_vsphere_vm
```
ERROR:
```
TASK [vmware : Deploy VM from template] ****************************************
 fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Failed to create a virtual machine : A specified parameter was not correct: disk[0].diskId"}
```
