### ISSUE TITLE
Templated dict variable is not merged

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#57680]
##### SUMMARY
When a dict in group_vars is defined via lookup, value is replaced instead of merged.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
```

##### CONFIGURATION

```paste below
hash_behaviour = merge
```

##### OS / ENVIRONMENT

FreeBSD 11

##### STEPS TO REPRODUCE

```yaml
# in roles/role1/defaults/isolated.yaml
foo: from-isolated
bar: from-isolated
```

```yaml
# in roles/role2/defaults/main.yaml
dict1:
  defaults: from-role2
dict2:
  defaults: from-role2
```

```yaml
# in group_vars/group1
dict1:
  foo: from-group
  bar: from-group
dict2: "{{ lookup('template', playbook-dir + '/roles/role1/defaults/isolated.yaml') | from_yaml }}"
```
`role2` depends on `role1`

##### EXPECTED RESULTS

dict2 is merged the same way as dict1 
```
dict1:
  defaults: from-role2
  foo: from-group
  bar: from-group
dict2:
  defaults: from-role2
  foo: from-isolated
  bar: from-isolated
```

##### ACTUAL RESULTS

dict2 is replaced at group_vars, values from role2 defaults discarded.

```paste below
dict1:
  defaults: from-role2
  foo: from-group
  bar: from-group
dict2:
  foo: from-isolated
  bar: from-isolated
```
