### ISSUE TITLE
Issue Mysql_user module with mysql 8

### ISSUE THREAD

**Issue by eowin** [ansible/ansible#57693]
Hello,

I have the ansible version 2.8.1 and I have python 2.7.

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

#### ISSUE

Module concerned : Mysql_user

When i try to set a password encrypted with sha2 I get the following error :

```yaml
"msg": "(1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PASSWORD '********'' at line 1\")", 
```

#### More informations

Please find the configuration which is bug : 

```yaml
...
password: "$A$005$O57hU%K7H2z0E7EGp7LaXHcpsPeT1hs.WUeFH3uV7AzShoZS76MRUSFub94"
encrypted: yes
....
```
