### ISSUE TITLE
SeSecurityPrivilege in win_acl module

### ISSUE THREAD

**Issue by P-Hessler** [ansible/ansible#57753]
##### SUMMARY
The win_acl fails when changing rights on a directory for which the inheritance from the parent folder has been disabled. The error message is "an exception occurred when adding the specified rule - The process does not possess the 'SeSecurityPrivilege' privilege which is required for this operation."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_acl

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Ansible is running on Ubuntu 18.04.2 LTS on a virtual machine. Target machine is running Windows Server 2012 R2

##### STEPS TO REPRODUCE
Create a directory {{dir}} on the target machine for which the ansible user has full rights and another user {{user}} has no rights. Disable inheritance of rights for this directory.

```yaml
- name: Set ListDirectory to {{cleaned_directory}}
  win_acl:
    user: '{{user}}'
    path: '{{dir}}'
    type: allow
    state: present
    rights: ListDirectory
    inherit: 'None'
    propagation: 'NoPropagateInherit'
```

##### EXPECTED RESULTS

Ansible modifies the rights on the directory.

```paste below
changed: [...] => (item={{dir}}) => {
    "changed": true,
    "dir": "{{dir}}"
}
```

##### ACTUAL RESULTS

```paste below
failed: [...] (item={{dir}}) => {
    "changed": false,
    "dir": "{{dir}}",
    "msg": "an exception occurred when adding the specified rule - The process does not possess the 'SeSecurityPrivilege' privilege which is required for this operation."
}

```
