### ISSUE TITLE
native jinja2 not working with template module

### ISSUE THREAD

**Issue by majidaldo** [ansible/ansible#57765]
##### SUMMARY
Templating files does not respect native jinja2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION

```
config file = None                                                                                      
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /opt/conda/lib/python3.7/site-packages/ansible                         
executable location = /opt/conda/bin/ansible                                                            
python version = 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]                                     
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/assetscore/config/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/assetscore/config/ansible.cfg) = /tmp/ansible_facts
DEFAULT_HOST_LIST(/assetscore/config/ansible.cfg) = ['/assetscore/inventory']
DEFAULT_JINJA2_NATIVE(/assetscore/config/ansible.cfg) = True
DEFAULT_MODULE_PATH(/assetscore/config/ansible.cfg) = ['/assetscore/library']
DEFAULT_ROLES_PATH(/assetscore/config/ansible.cfg) = ['/assetscore/roles']
DEFAULT_STDOUT_CALLBACK(/assetscore/config/ansible.cfg) = debug
ENABLE_TASK_DEBUGGER(/assetscore/config/ansible.cfg) = True
INVENTORY_CACHE_ENABLED(/assetscore/config/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/assetscore/config/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/assetscore/config/ansible.cfg) = /tmp/ansible_inventory
INVENTORY_ENABLED(/assetscore/config/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'aws_ec2'
```

##### OS / ENVIRONMENT

target OS: ubuntu 19.04
Docker version 18.06.0-ce, build 0ffa825

##### STEPS TO REPRODUCE

config
```
---
config:
  sim_name: something
  number_of_workers: 1

  cluster:
    number_of_nodes: 2 
    volume_size: 40
```

file contents (docker compose)
```yaml
  ...
    deploy:
      mode: replicated
      replicas: "{{config.number_of_workers | int }}"  # int doesn't matter
```
playbook
```
---
- hosts: aws_ec2[0]
  vars_files:
    - ../config/config.yml
  
  tasks:

  - name: send over the compose file
    template:
      src: ../sim.compose.yml
      dest: ~/{{config.sim_name}}.compose.yml
  - name: remove stupid quotes... hacky
    replace:
      path: ~/{{config.sim_name}}.compose.yml
      regexp: \"
      #replace: ..with nothing

  - name: run open studio server
    docker_stack:
      name: "{{config.sim_name}}"
      state: present
      compose:
        - ~/{{config.sim_name}}.compose.yml
      prune: yes
```

##### EXPECTED RESULTS

no quotes in deploy.replicas template result file

##### ACTUAL RESULTS

Quotes in deploy.replicas template result file.

Having quotes in a place where integers are expected will not work for a docker compose file.
