### ISSUE TITLE
Ansilble arista eos_config not working as expected

### ISSUE THREAD

**Issue by vikas7999** [ansible/ansible#57773]
##### SUMMARY

ansible 2.7.7

##### ISSUE TYPE
Trying to push Arista configuration commands using ansible src file.
After running the playbook its successfully executed however some commands are not configured on actual device which are there is ansible src config file.

##### COMPONENT NAME
Ansible eos_config module for Arista

##### ADDITIONAL INFORMATION
So ansible src file has following command:
```
interface Ethernet3/11/1
   no switchport
   ip address 1.1.1.1/32
```
However when i login to the actual device it gives me following error:
```
(s1)(config)#int Ethernet3/11/1
(s1)(config-if-Et3/11/1)#no switchport
(s1)(config-if-Et3/11/1)#ip address 1.1.1.1/32
% Prefix length must be less than 32
PLAY RECAP *************************************************************************************************************************************************************************
S1                : ok=1    changed=1    unreachable=0    failed=0   
```
Just need help to determine why ansible is not reporting failed error instead of saying successful

more arista_config_apply.yaml
---
```
- name: Arista config apply
  hosts: Arista
  gather_facts: false
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_become: yes
    authorize: yes
    ansible_become_method: enable
  ignore_errors: no
  #vars:
   # cli:
   #   transport: cli
   #   authorize: true

  tasks:
    - name: Apply config
      eos_config:
        diff_against: running
        src: /etc/ansible/CONFIGS/Temp.cfg
```

This is config file Temp.cfg

```
interface Ethernet 3/13/1 
   no shutdown
!
interface Ethernet3/11/1
   no switchport
   ip address 1.1.1.1/32 ============? Expecting error in Ansible however its success.

!
interface Ethernet3/21/1
   no switchport
   ip address 3.3.3.1/30
!
interface loopback100
   description ***test interface ***
   ip address 1.1.1.1/32
!
interface Port-Channel 503
   description test
   switchport trunk allowed vlan none
   switchport mode trunk
   spanning-tree portfast
!
interface Port-Channel 504
   description test
   switchport trunk allowed vlan none
   switchport mode trunk

```
