### ISSUE TITLE
win_acl on CIFS share on ansible 2.8

### ISSUE THREAD

**Issue by matthgyver** [ansible/ansible#57799]
##### SUMMARY

Ansible return an error when using win_acl module on a UNC path.
Same problem like #55875 but in last stable version (2.8 installed with pip).

No problem with devel version

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_acl
##### ANSIBLE VERSION

```paste below
[user@computer]$ ansible --version
ansible 2.8.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 13:24:18) [GCC 6.4.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: add ACE
      win_acl:
        user: foobar
        path: \\myNAS\mySharedFolder
        type: allow
        rights: FullControl
        propagation: NoPropagateInherit
        inherit: none
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```paste below
fatal: [windows]: FAILED! => {"changed": false, "module_stderr": "Exception lors de l'appel de «Run» avec «1» argument(s): «Exception lors de \r\nl'appel de «Invoke» avec «0» argument(s): «L’exécution de la commande s’est \r\narrêtée, car la variable de préférence «ErrorActionPreference» ou le paramètre \r\ncourant a la valeur Stop: Impossible d'analyser le chemin d'accès, car aucun \r\nqualificateur n'est spécifié pour le chemin d'accès «\\\\myNAS\\mySharedFolder\r\n».»»\r\nAu caractère Ligne:79 : 5\r\n+     $output = $entrypoint.Run($payload)\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE \r\n   xception\r\n    + FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n ", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
