### ISSUE TITLE
Environment variables fail to propagate from one task to the next with ansible 2.8.1 connecting to Windows Server 2016 via openssh 

### ISSUE THREAD

**Issue by petemounce** [ansible/ansible#57815]
##### SUMMARY
I am using ansible 2.8.1 to configure Windows Server 2016, to install chocolatey before using that to install other software. Also, to set environment variables in general.

I am using [powershell openssh 7.9.0.1-beta1 for sshd](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.9.0.0p1-Beta) and connecting via ssh from an ubuntu 16.04 LTS or a macOS Mojave 10.14.5 as the controller.

(I'd like to take the opportunity to _thank you_ for your work to enable openssh as a connection-option for controlling Windows hosts. I am counting the seconds before swapping over from winrm.)

I am observing that environment variables set do not take effect in subsequent tasks.

(Is this because pipelining is turned on...?)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

(these are my best guesses)

lib/ansible/modules/windows/win_environment.ps1
lib/ansible/modules/windows/win_path.ps1
lib/ansible/plugins/connection/ssh.py
lib/ansible/plugins/shell/powershell.py

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.1
  config file = None
  configured module search path = [u'/Users/petermounce/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Apr 12 2019, 15:32:40) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only changed
DEFAULT_CALLBACK_WHITELIST(/Users/petermounce/src/ip/platform/packer/improbable.io/buildkite/ansible/ansible.cfg) = [u'timer', u'profile_tasks']
```

##### OS / ENVIRONMENT

*Target*
* Windows Server 2016 (within google cloud)
* sshd from https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v7.9.0.0p1-Beta installed via https://gist.github.com/petemounce/d9e175b4e62d3a52e9cbb95bf9f35bbc#file-bootstrap-target-machine-ps1
    * sshd_config

    ```txt
    Port 22
    # Logging
    #SyslogFacility AUTH
    #LogLevel INFO

    # Authentication:

    #LoginGraceTime 2m
    #PermitRootLogin prohibit-password
    #StrictModes yes
    #MaxAuthTries 6
    #MaxSessions 10

    PubkeyAuthentication yes

    # The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
    # but this is overridden so installations will only check .ssh/authorized_keys
    AuthorizedKeysFile	.ssh/authorized_keys

    # To disable tunneled clear text passwords, change to no here!
    #PasswordAuthentication yes
    #PermitEmptyPasswords no

    TCPKeepAlive yes

    # override default of no subsystems
    Subsystem	sftp	sftp-server.exe

    Match Group administrators
        AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
    ```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: true

  tasks:
    - name: set an environment variable at machine-level
      win_environment:
        name: machine_level
        level: machine
        value: foobar
    - name: set an environment variable at user-level
      win_environment:
        name: user_level
        level: user
        value: foobar
    - name: add an element to PATH
      win_path:
        elements:
          - 'c:\foo'
        state: present
    - name: assert expectations
      win_shell: |
        echo "machine - $($env:machine_level)"
        echo "user - $($env:user_level)"
        echo "PATH - $($env:PATH)"
```

INVENTORY

Note `pipelining: true`.

```yaml
---
all:
  hosts:
    11.22.33.44
  vars:
    # https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html#windows-ssh-setup
    # Windows works differently than unix; with Windows, we don't need become because typically the user will be an administrator to be able to do anything at all.
    # With ansible_become: true on Windows, you get a ShellModule error.
    ansible_become: false
    ansible_connection: ssh
    # When powershell, Windows must also have HKLM:/SOFTWARE/OpenSSH set up.
    ansible_shell_type: powershell
    ansible_ssh_private_key_file: "/Users/petermounce/src/ip/platform/private_key"
    ansible_user: packer_user
    ansible_host_key_checking: false
    ansible_pipelining: true  # conflicts with 'become', see ansible docs. But Windows has become:false, so use it there.
    # defaults are "-C -o ControlMaster=auto -o ControlPersist=60s"
    ansible_ssh_args: ""
```

##### EXPECTED RESULTS

I expect to see the variables' values echo'd to stdout from the win_shell task's output.

```
    "stdout_lines": [
        "machine - foobar",
        "user - foobar",
        "PATH - C:\\Program Files\\OpenSSH-Win64;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\GooGet;C:\\Program Files\\Google\\Compute Engine\\metadata_scripts;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Program Files\\Google\\Compute Engine\\sysprep;C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps;c:\\Program Files\\OpenSSH-Win64;;C:\\Users\\packer_user\\AppData\\Local\\Microsoft\\WindowsApps;c:\\foo"
    ]
```

(I'm not sure if I should see `c:\foo` at the front or the end of the PATH, but somewhere in it).

##### ACTUAL RESULTS

https://gist.github.com/petemounce/d9e175b4e62d3a52e9cbb95bf9f35bbc

##### OTHER OBSERVATIONS

If I change `pipelining` to `false` then run the playbook a second time against the same machine, I get

```
    "stdout_lines": [
        "machine - ",
        "user - foobar",
        "PATH - C:\\Program Files\\OpenSSH-Win64;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\GooGet;C:\\Program Files\\Google\\Compute Engine\\metadata_scripts;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Program Files\\Google\\Compute Engine\\sysprep;C:\\Windows\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps;c:\\Program Files\\OpenSSH-Win64;;C:\\Users\\packer_user\\AppData\\Local\\Microsoft\\WindowsApps;"
    ]
```

Third run, no changes, same output as 2nd.

In run 1, all tasks report changed=true.

In runs 2 and 3, only the win_shell reports changed=true - yet still the output doesn't contain the values.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_environment.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_environment.py)
* [`lib/ansible/modules/windows/win_path.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_path.py)
* [`lib/ansible/plugins/connection/ssh.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py)
* [`lib/ansible/plugins/shell/powershell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/shell/powershell.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ShachafGoldstein** [comment]
Maybe this has something to do with the fact the Powershell is started via the sshd process which wasn't restarted to have its own environment initialized 

Did not test it but looking at the server with procexp and seeing what process starts the Powershell.exe would answer that

**Comment by petemounce** [comment]
That sounds like it's plausible. I'm sat on the host eyeballing sysinternals process explorer, and observing this process tree.

The children process running powershell has more environment variables than the parent.

<img width="876" alt="Screenshot 2019-06-20 at 00 16 36" src="https://user-images.githubusercontent.com/69720/59807724-0cbd0a80-92f1-11e9-9347-f6d585fda7c1.png">

I've partially worked around this via `win_reboot` - but finding that aside from injecting another 20s per reboot (or so), that seems to make my packer runs less reliable and I haven't figured out why.

Since when setting a machine-level environment variable on Windows via WinRM, that gets reflected into subsequent commands, this sounds like a question toward the win32-openssh folk; what do you think? I mean, I can see how it's convenient for it to just work, but on the other hand, here I am a remote connection modifying machine state. I suppose since I've got the connection, and admin-rights, calling this behaviour a security restriction might be redundant?

**Comment by jborean93** [comment]
Definitely sounds like something the sshd service is caching but doesn't really make much sense to me. Will need to look into it a bit more to confirm but if you can replicate this by just running `ssh` commands to the Windows box then it sounds like something that should be reporting to win32-openssh.

**Comment by ShachafGoldstein** [comment]
Another way to test would be to restart the sshd after the change and ignore the errors of the connection reset, ugly I know but it should work and be a valid workaround

**Comment by jhawkesworth** [comment]
I wonder if `meta: reset_connection` would do it?

**Comment by jborean93** [comment]
@jhawkesworth good idea, it could be a byproduct of control persist and `meta: reset_connection` would do that for you.

**Comment by ShachafGoldstein** [comment]
Unless the reset also makes the sshd process reload the environment it won't do the trick since the child process gets the variables from the parent and not from the machine

**Comment by jborean93** [comment]
@ShachafGoldstein we use something called Control Master or Multiplexing for SSH commands which save the actual TCP connection to the server for a limited period of time. This makes task execution quicker as it means we don't have to open a new connect and authenticate each and every task. Because the socket is saved it makes me thing this is the reason why the sshd service is keeping the profile loaded of the user's logon and not reloading environment values on a new task. Running `- meta: reset_connection` will force the Ansible controller to close that saved socket and start a new connection on the next ask which theoretically would means sshd would create a new logon session with the updated environment variables.

In saying that it would have to be tested and proved before I could say that's the reason but it would make more sense than sshd somehow caching the environment variables between invocations.

**Comment by ShachafGoldstein** [comment]
I understand but you will be surprised how many times I can across a similar issue where software creates a child process that simply inherits their context, environment wise.

Looking forward to the test results :)

**Comment by petemounce** [comment]
I was able to workaround the issue via restarting sshd async, then reseting the connection:

```yaml
- name: restart sshd to reflect changes to PATH
  win_service:
    name: sshd
    state: restarted
  async: 60
  poll: 0
  register: sshd_restart

- name: wait for connectivity to be resumed after sshd restart
  async_status:
    jid: "{{ sshd_restart.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 1

- name: reset
  meta: reset_connection
```

Both were necessary.
