### ISSUE TITLE
vmware_guest: Cloning with disk customization fails

### ISSUE THREAD

**Issue by ralphie02** [ansible/ansible#57817]
##### SUMMARY

Cloning from a template that has disk set to non-persistent fails when the disk for the new machine is set to persistent. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/ralphie02/.ansible.cfg
  configured module search path = [u'/home/ralphie02/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ralphie02/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1800s
ANSIBLE_SSH_CONTROL_PATH(/home/ralphie02/.ansible.cfg) = /tmp/ansible-ssh-%%h:%%p-%%r
COLOR_VERBOSE(/home/ralphie02/.ansible.cfg) = bright blue
DEFAULT_CALLBACK_WHITELIST(/home/ralphie02/.ansible.cfg) = [u'profile_tasks', u'log_plays_capture', u'actionable', u'skippy', u'task_timer', u'vers
DEFAULT_FORKS(/home/ralphie02/.ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(/home/ralphie02/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/staging']
DEFAULT_REMOTE_USER(/home/ralphie02/.ansible.cfg) = razucena
DEFAULT_ROLES_PATH(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/roles']
DEFAULT_TIMEOUT(/home/ralphie02/.ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/ralphie02/.ansible.cfg) = /home/ralphie02/ansible-vault-key
INJECT_FACTS_AS_VARS(/home/ralphie02/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ralphie02/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target:
debian 7,8,9
centos 6,7

Controlled:
debian 9

##### STEPS TO REPRODUCE

Step 1:
  Set a machine/template's disk to non-persistent
Step 2:
  Create machine wish disk set to persistent

```yaml
- hosts: localhost
  gather_facts: no

- vmware_guest:
    hostname: my_hostname
    datacenter: my_datacenter
    name: test-vm
    user: my_user
    pass: my_pass
    esxi_hostname: my_esxi_hostname
    folder: my_folder
    template: template_of_machine_with_non_persistent_vdisk
    hardware: my_hardware
    disk:
    - { size_gb: 200, type: thin, datastore: my_datastore, disk_mode: persistent }
    networks: []
    state: poweredon
    validate_certs: no
    wait_for_ip_address: yes
```

##### EXPECTED RESULTS

Machine created without issues

##### ACTUAL RESULTS

task fails with the following message below

```paste below
"msg": "Failed to create a virtual machine : Cannot complete the operation because the file or folder /vmfs/volumes/5751fd49-060f2861-6489-1c98ec2b9b94/test-vm/test-vm.vmdk already exists"
```

This used to work perfectly fine before 2.8.0.
I didn't see any major changes as per the changelog concerning vmware_guest/disk but I did find these commits: https://github.com/ansible/ansible/commit/8eff4cae10f7661a8fb9942e99fb0e251f485f3a and https://github.com/ansible/ansible/commit/7c8b5a407d63e1292fda2377017f0459ab8e1ee9
These are the only commits I found regarding disks/2.8 that might be causing this.
