### ISSUE TITLE
paths for the task “check if the backup file-1 exist” (backup.yaml) should not be a file name

### ISSUE THREAD

**Issue by Quanta-Switch** [ansible/ansible#57825]
##### SUMMARY
The argument of **paths** in task: "check if the backup file-1 exist" should be directory name rather than a file name in backup.yaml which is located at test/integration/targets/xxx_config/tests/... 

Yaml Extraction:
```
- name: check if the backup file-1 exist
  find:
    paths: "{{ role_path }}/backup_test_dir/{{ inventory_hostname_short }}/backup.cfg"
  register: backup_file
  connection: local
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
backup.yaml in test/integration/targets/ 
!component =lib/ansible/
##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
The task should be correctly processed.

##### ACTUAL RESULTS
There is a message for the task: 
```
...was skipped as it does not seem to be a valid directory or it cannot be accessed
```
