### ISSUE TITLE
Module zabbix_host still not idempotent

### ISSUE THREAD

**Issue by Hickory420** [ansible/ansible#57822]
##### SUMMARY

Almost exactly the same issue as #24964 (closed)
When trying to register Zabbix host for the second time, module tries to create two default interfaces (despite it did not change), what results in an error, as only one default interface per type is allowed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_host.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /home/hickory/git/ansible/ansible.cfg
  configured module search path = [u'/home/hickory/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```
##### ZABBIX VERSION
4.2.1

##### STEPS TO REPRODUCE

```yaml
- name: Adding to zabbix with default template
  zabbix_host:
    server_url: "https://{{ monitoring }}"
    login_user: "{{ domain_user.name }}"
    login_password: "{{ domain_user.pass }}"
    force: false
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ purpose }}"
    description: "{{ purpose }}"
    interfaces:
        # Interface type
        # 1 - agent; 2 - SNMP; 3 - IPMI; 4 - JMX
      - type: 1
        # Whether the interface is used as default on the host
        # 0 - not default; 
        # 1 - default.
        main: 1
        # Whether the connection should be made via IP
        # IP address used by the interface
        # 0 - connect using host DNS name; 
        # 1 - connect using host IP address.
        useip: 1
        # IP name used by the interface. 
        ip: "{{ ansible_host }}"
        # ID of the host the interface belongs to
        hostid: "{{ monitoring }}"
        # Port number used by the interface
        port: 10050
        # Blank because we are using IP. But still required to be defined.
        dns: ""
    link_templates: 
      - "Template OS Linux"
    host_groups:
      - "Servers"
      - "Web"
    status: enabled
    state: present
  delegate_to: localhost

```

##### EXPECTED RESULTS

Playbook can be successfully run twice, without side effects.

```json
changed: [AUSSVAP0519 -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": "FeCru",
            "force": false,
            "host_groups": [
                "1.Unix",
                "Servers"
            ],
            "host_name": "AUSSVAP0519",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [
                {
                    "dns": "",
                    "hostid": "zabbix.example.com.au",
                    "ip": "10.130.69.37",
                    "main": 1,
                    "port": 10050,
                    "type": 1,
                    "useip": 1
                }
            ],
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": [
                "Template OS Linux"
            ],
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "******",
            "proxy": null,
            "server_url": "https://zabbix.example.com.au",
            "state": "present",
            "status": "enabled",
            "timeout": 10,
            "tls_accept": 1,
            "tls_connect": 1,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "validate_certs": true,
            "visible_name": "FeCru"
        }
    },
    "result": "Successfully added host AUSSVAP0519 (10.130.69.37) and linked with template '['Template OS Linux']'"
}
```
##### ACTUAL RESULTS

Running the second time (without modifying any code):

```json
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_zabbix_host_payload_s1JEvk/__main__.py", line 360, in update_host
    self._zapi.hostinterface.update(interface_str)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 341, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 348, in do_request
    return self.parent.do_request(req)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 299, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])

fatal: [AUSSVAP0519 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": "FeCru",
            "force": false,
            "host_groups": [
                "1.Unix",
                "Servers"
            ],
            "host_name": "AUSSVAP0519",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [
                {
                    "dns": "",
                    "hostid": "zabbix.example.com.au",
                    "interfaceid": "36503",
                    "ip": "10.130.69.37",
                    "main": 1,
                    "port": 10050,
                    "type": 1,
                    "useip": 1
                },
                {
                    "dns": "",
                    "ip": "10.130.69.37",
                    "main": 1,
                    "port": 10050,
                    "type": 1,
                    "useip": 1
                }
            ],
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": [
                "Template OS Linux"
            ],
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "******",
            "proxy": null,
            "server_url": "https://zabbix.example.com.au",
            "state": "present",
            "status": "enabled",
            "timeout": 10,
            "tls_accept": 1,
            "tls_connect": 1,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "validate_certs": true,
            "visible_name": "FeCru"
        }
    },
    "msg": "Failed to update host AUSSVAP0519: (u'Error -32602: Invalid params., Cannot switch host for interface. while sending {\"params\": {\"interfaceid\": \"36503\", \"hostid\": \"zabbix.example.com.au\", \"ip\": \"10.130.69.37\", \"useip\": 1, \"dns\": \"\", \"main\": 1, \"type\": 1, \"port\": 10050}, \"jsonrpc\": \"2.0\", \"method\": \"hostinterface.update\", \"auth\": \"1a881eba66580a12a064e6c2768ccb64\", \"id\": 15}', -32602)"
}
```

If I specify `force: true`, I get the following result

```json
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_zabbix_host_payload_s4XLzI/__main__.py", line 360, in update_host
    self._zapi.hostinterface.update(interface_str)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 341, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 348, in do_request
    return self.parent.do_request(req)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_api.py", line 299, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])

fatal: [AUSSVAP0519 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "description": "FeCru",
            "force": true,
            "host_groups": [
                "1.Unix",
                "Servers"
            ],
            "host_name": "AUSSVAP0519",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [
                {
                    "dns": "",
                    "hostid": "zabbix.example.com.au",
                    "interfaceid": "36503",
                    "ip": "10.130.69.37",
                    "main": 1,
                    "port": 10050,
                    "type": 1,
                    "useip": 1
                }
            ],
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": [
                "Template OS Linux"
            ],
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "******",
            "proxy": null,
            "server_url": "https://zabbix.example.com.au",
            "state": "present",
            "status": "enabled",
            "timeout": 10,
            "tls_accept": 1,
            "tls_connect": 1,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "validate_certs": true,
            "visible_name": "FeCru"
        }
    },
    "msg": "Failed to update host AUSSVAP0519: (u'Error -32602: Invalid params., Cannot switch host for interface. while sending {\"params\": {\"interfaceid\": \"36503\", \"hostid\": \"zabbix.example.com.au\", \"ip\": \"10.130.69.37\", \"useip\": 1, \"dns\": \"\", \"main\": 1, \"type\": 1, \"port\": 10050}, \"jsonrpc\": \"2.0\", \"method\": \"hostinterface.update\", \"auth\": \"9f733ad1317b201b2a0af1568153fb19\", \"id\": 10}', -32602)"
}
```
