### ISSUE TITLE
vmware_guest_disk: Failed to find datastore named in given configuration.

### ISSUE THREAD

**Issue by ssaammoo** [ansible/ansible#57831]
##### SUMMARY
Failed to add a new disk to the VM

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_disk

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
```

##### CONFIGURATION

```paste below
# ansible-config dump --only-changed
#
```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

I try to collect VM facts and then add a VM to same datastore:

```yaml
- name: Assign VM facts to varaibles
      set_fact:
        sql_vm_datastore: "{{sql_facts.instance.hw_datastores}}"
        sql_vm_cluster: "{{sql_facts.instance.hw_cluster}}"
        sql_vm_folder: "{{sql_facts.instance.hw_folder}}"
      register: sql_vm_facts
```
```yaml

- name: Reconfigure VM Disks
  vmware_guest_disk:
    datacenter: "{{sql_vm_site}}"
    validate_certs: no
    name: "{{sql_vm}}"
    disk:
      - size_mb: 100
        type: eagerzeroedthick
        datastore: "{{sql_vm_datastore}}"
        state: present
        unit_number: 1
        scsi_type: 'paravirtual'
  delegate_to: localhost
  register: disk_facts
```

##### EXPECTED RESULTS

Disk is added successfully 

##### ACTUAL RESULTS

    "msg": "Failed to find datastore named '['XXXXX']' in given configuration."

```paste below
# verbatim
bash: verbatim: command not found
```
