### ISSUE TITLE
vmware_vmkernel - port group name for management vmk is not accounted

### ISSUE THREAD

**Issue by sat1121** [ansible/ansible#57859]
##### SUMMARY
Using vmware_vmkernel. Not changing the port group name associated with the vmkernel

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vmkernel

##### ANSIBLE VERSION

```
2.7
2.8

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

This issue occurs if you would like to change the port group name that is associated with the vmkernel. When a ESXi host is created the management vmk gets created with the name "Management Name". If in a day 1 config you would like to reconfigure the vmk with the port group change. The module seem to ignore the change in port group name and gives false positive.

```yaml
- name: "{{ inventory_hostname }} Setting Management network"
  delegate_to: localhost
  vmware_vmkernel:
    hostname: '{{ vcenter }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    vswitch_name: vSwitch0
    portgroup_name: '{{ esx_mgmt_new_name }}'
    network:
      type: 'static'
      ip_address: "{{ ipadd }}"
      subnet_mask: '{{ esx_mgmt_subnet }}'
    mtu: 9000
    enable_vmotion: 'False'
    enable_mgmt: 'True'
    state: present
    validate_certs: false
```

##### EXPECTED RESULTS

It would be easier if it just renames that port group to which the vmk is associated with, since the default port group for management network will be created when a host is built. I am not sure in vmware there is a feature to associate a vmk to a new port group. 

##### ACTUAL RESULTS

The playbook completes either with changed or not changed depending on the current state, but ignoring the new port group name. 

```paste below

```
