### ISSUE TITLE
System reboot module

### ISSUE THREAD

**Issue by g--** [ansible/ansible#5785]
I'd like to suggest/request a 'reboot' module that can restart a system under ansible's control and wait until the action is completed.

At the moment, this can be approximated with a shutdown handler followed by a pause:

``` yaml

---
- hosts: all

  pre_tasks:
   - name: kernel parameters that need a reboot to take effect
     #example for freebsd kernel paramaeters, but the general principle applies
     copy: src=boot_loader.conf dest=/boot/loader.conf owner=root mode=0644
     notify:
        - reboot

  handlers:

    - name: reboot
      command: shutdown -r now "ansible triggered"
      notify: post shutdown pause

    - name: post shutdown pause
      pause: seconds=40 
```
