### ISSUE TITLE
pmrun become plugin timeout while awaiting non-existent password prompt: "Enter UPM user password"

### ISSUE THREAD

**Issue by aka17034** [ansible/ansible#57858]
##### SUMMARY

When attempting to use `become_method: pmrun`, playbook hits timeout while awaiting non-existent password prompt: `Enter UPM user password:`.  

In this environment, pmrun profile is set to `pf_enableauthentication= false`, so user is never prompted for password.

Changing the pmrun profile to `pf_enableauthentication= true`, as well as manually changing the default password prompt to `pf_pamprompt = "Enter UPM user password:"`, does not seem to fix the issue.

No issues seen when using `become_method: sudo`, as long as sudoers set accordingly (e.g. `  NOPASSWD: ALL`)

The following workaround tested successfully:

Copy sudo.py to pmrun.py:

`cp sudo.py pmrun.py`

Change the become_exe:

`sed -i 's/default: sudo/default: pmrun/' pmrun.py`

Change the become_flags:

`sed -i 's/default: -H -S -n/default: /' pmrun.py`

After making those changes, playbook runs to success.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

pmrun

https://github.com/ansible/ansible/blob/445ff39f944f45492bf7b2360d99fdadc02d142b/lib/ansible/plugins/become/pmrun.py#L65

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/s90029/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = oneline
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)
pmrun Version 6.0.0 (050)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: sandbox
  gather_facts: no
  become: true
  become_method: pmrun
#  become_user: root
  tasks:

    - name: write motd
      template:
        src: /home/s90029/motd.j2
        dest: /etc/motd
        backup: yes
        group: bin
        owner: bin
        mode: 0444

```

##### EXPECTED RESULTS

SUCCESS 

##### ACTUAL RESULTS

```paste below
<snip>
2019-06-14 12:18:09,910 p=16330 u=s90029 |   16339 1560532689.91066: Initial state: awaiting_prompt: Enter UPM user password:
<snip>
2019-06-14 12:18:21,954 p=16330 u=s90029 |  sandbox | FAILED! => {    "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
<snip>
```
