### ISSUE TITLE
vmware_guest: Cloned machine's hostname is no longer updated

### ISSUE THREAD

**Issue by ralphie02** [ansible/ansible#57873]
##### SUMMARY

Cloning no longer customizes the new machine's hostname into the value specified in vmware_guest: name: vm_name
Tested on both 2.7.10 and 2.8.0. 
Works on 2.7.10 but not on 2.8.0

##### ISSUE TYPE
- Bug Report
- Regression

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/ralphie02/.ansible.cfg
  configured module search path = [u'/home/ralphie02/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ralphie02/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ralphie02/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1800s
ANSIBLE_SSH_CONTROL_PATH(/home/ralphie02/.ansible.cfg) = /tmp/ansible-ssh-%%h:%%p-%%r
COLOR_VERBOSE(/home/ralphie02/.ansible.cfg) = bright blue
DEFAULT_CALLBACK_WHITELIST(/home/ralphie02/.ansible.cfg) = [u'profile_tasks', u'log_plays_capture', u'actionable', u'skippy', u'task_timer', u'vers
DEFAULT_FORKS(/home/ralphie02/.ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(/home/ralphie02/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/staging']
DEFAULT_REMOTE_USER(/home/ralphie02/.ansible.cfg) = razucena
DEFAULT_ROLES_PATH(/home/ralphie02/.ansible.cfg) = [u'/home/ralphie02/Shared/Ansible/roles']
DEFAULT_TIMEOUT(/home/ralphie02/.ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/ralphie02/.ansible.cfg) = /home/ralphie02/ansible-vault-key
INJECT_FACTS_AS_VARS(/home/ralphie02/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ralphie02/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target:
centos 6,7

Controlled:
debian 9

##### STEPS TO REPRODUCE

Step 1: Clone a machine

```yaml
- hosts: localhost
  gather_facts: no

- vmware_guest:
    hostname: my_hostname
    datacenter: my_datacenter
    name: test-vm
    user: my_user
    pass: my_pass
    esxi_hostname: my_esxi_hostname
    folder: my_folder
    template: my_template
    hardware: my_hardware
    disk: [{ size_gb: 40, type: thin, datastore: my_datastore }]
    networks: [{ name: my_network}]
    state: poweredon
    validate_certs: no
    wait_for_ip_address: yes
```

##### EXPECTED RESULTS

Cloned machine's hostname is set to the value specified in vmware_guest module's name attribute.

##### ACTUAL RESULTS

Cloned machine's hostname is set to the template's hostname

```paste below

```
