### ISSUE TITLE
docker_container 404

### ISSUE THREAD

**Issue by tombrk** [ansible/ansible#57872]
##### SUMMARY

When creating docker containers, ansible sometimes fails with a 404 Error:

```
An exception occurred during task execution. To see the full traceback, use -vvv.
The error was: docker.errors.NotFound: 404 Client Error:
Not Found ("network {
'group': 'root', 
'mode': '0644', 
'gid': 0, 
'uid': 0, 
'changed': False, 
'diff': {
  'before': {
    'path': '/etc/docker/daemon.json'
  }, 
  'after': {
    'path': '/etc/docker/daemon.json'
  }
}, 
'state': 'file', 
'size': 97, 
'dest': '/etc/docker/daemon.json', 
'failed': False, 
'checksum': '7f96537ff788587842cd80528ded36150e969837', 
'path': '/etc/docker/daemon.json', 
'owner': 'root'
}
not found")
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /Users/tbraack/.ansible.cfg
  configured module search path = ['/Users/tbraack/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.9/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_STRATEGY(/Users/tbraack/.ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/Users/tbraack/.ansible.cfg) = ['/usr/local/lib/python2.7/site-packages/ansible_mitogen/plugins/strategy']
```

##### OS / ENVIRONMENT

```
$ uname -a
Darwin hostname 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

However, this also happens on Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: "connect sidecar: {{_.name}}"
  vars:
    container: "{{ _.container | default(_.name) }}"
    network: "{{_.proxy.network | default(container)}}"
  docker_container:
    name: "{{_.name}}-connect"
    image: "consul:1.4.4"
    pull: yes
    restart_policy: always
    command: [
      "connect", "proxy",
      "-sidecar-for {{_.name}}",
      "-http-addr=169.254.1.1:8500"
    ]
    networks:
      - name: "{{network}}"
    purge_networks: yes
    ports:
      - "{{_.proxy.listen}}:{{_.proxy.listen}}"

```

##### EXPECTED RESULTS

The container is created.

##### ACTUAL RESULTS

The creation fails using the above 404 Error, but I don't understand the error message. This only happens from time to time, it seems as if ssh'ing into the host, listing docker networks or removing the container helps
