### ISSUE TITLE
Cannot run playbook again when contract filter is already in place. 

### ISSUE THREAD

**Issue by aciguru** [ansible/ansible#57876]
##### SUMMARY

Unable to run the playbook again - stuck at adding a new contract filter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mso_schema_template_contract_filter

##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac OS - Terminal

##### STEPS TO REPRODUCE

```
- name: Configuring a new Three Tier Application on Multisite
  hosts: mso1
  connection: local
  gather_facts: no

  vars:
    tenant: RedHat_Ansible
    schema: RedHat Demo
    template: RedHat Template 1
    template2: RedHat Template 2
    vrf: vrf1
    bd: bd1
    ap: ap1
    epg1: db
    epg2: web
    epg3: app
    contract1: web2app
    contract2: app2db
    filter1: filter1
    filter2: filter2

  tasks:
  - name: Add a new tenant
    delegate_to: localhost
    mso_tenant:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     tenant: "{{ tenant }}"
     display_name: RedHat Ansible
     description: Tenant configured by Ansible
     users: "{{ user }}"
     sites:
       - "Miami"
       - "San Francisco"
     state: present
     validate_certs: no

  - name: Add a new template to a schema
    mso_schema_template:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     tenant: "{{ tenant }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new ANP
    mso_schema_template_anp:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     anp: "{{ ap }}"
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new VRF
    mso_schema_template_vrf:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     vrf: "{{ vrf }}"
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new BD
    mso_schema_template_bd:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     bd: "{{ bd }}"
     vrf: 
      name: vrf1
     state: present
     validate_certs: no
     layer2_stretch: True
    delegate_to: localhost

  - name: Add a new subnet to a BD
    mso_schema_template_bd_subnet:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     bd: "{{ bd }}"
     ip: 10.0.0.1/24
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new EPG
    mso_schema_template_anp_epg:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     anp: "{{ ap }}"
     epg: "{{ epg1 }}"
     bd:
      name: bd1
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new EPG
    mso_schema_template_anp_epg:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     anp: "{{ ap }}"
     epg: "{{ epg2 }}"
     bd:
      name: bd1
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new EPG
    mso_schema_template_anp_epg:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     anp: "{{ ap }}"
     epg: "{{ epg3 }}"
     bd:
      name: bd1
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new filter entry
    mso_schema_template_filter_entry:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     filter: "{{ filter1 }}"
     entry: filter1
     ethertype: ip
     ip_protocol: tcp 
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Add a new contract filter
    mso_schema_template_contract_filter:
     host: "{{ host }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     schema: "{{ schema }}"
     template: "{{ template }}"
     contract: web2app
     contract_filter_type: both-way
   #  contract_scope: vrf
     filter: "{{ filter1 }}"
     filter_type: consumer-to-provider
     state: present
     validate_certs: no
    delegate_to: localhost
```

##### EXPECTED RESULTS

```
TASK [Add a new contract filter] ********************************************************************************************************************************
ok: [mso1]
```
##### ACTUAL RESULTS

```
TASK [Add a new contract filter] *****************************************************************************************************************************
 [WARNING]: You are adding 'one-way' filters to a 'both-way' contract

fatal: [mso1]: FAILED! => {"changed": true, "current": {"directives": ["none"], "filterRef": {"filterName": "filter1", "schemaId": "5d02b04f100000e1092a5fe1", 
"templateName": "RedHat Template 1"}}, "data": [{"op": "replace", "path": "/templates/RedHat Template 1/contracts/web2app/filterType", "value": "bothWay"}, {"op": "replace", "path": "/templates/RedHat Template
1/contracts/web2app/filterRelationshipsConsumerToProvider/filter1", "value": {"directives": ["none"], "filterRef": {"filterName": "filter1", "schemaId": "5d02b04f100000e1092a5fe1", "templateName": "RedHat Template 1"}}}], "info": {"body": "
{\"code\":500,\"message\":\"FilterRelationship with name filter1 not found in List()\"}", "connection": "close", "content-language": "en", "content-length": "81", "content-type": 
"application/json", "date": "Fri, 14 Jun 2019 22:47:59 GMT", "msg": "HTTP Error 500: Internal Server Error", "server": "nginx", "status": 500, "strict-transport-security": "max-
age=31536000; includeSubDomains", "url": "https://172.31.187.59/api/v1/schemas/5d02b04f100000e1092a5fe1"}, "msg": "MSO Error 500: FilterRelationship with name filter1 not found in List()", "payload": {"code": 500, "message": "FilterRelationship with name filter1 not found in List()"}}
```
