### ISSUE TITLE
Restricted HTTP headers can not be set on Windows

### ISSUE THREAD

**Issue by mvorisek** [ansible/ansible#57880]
##### SUMMARY
Restricted HTTP headers can not be set on Windows like:
```
- name: Imagick .dll - download
  win_get_url:
    url: "https://windows.php.net/downloads/pecl/deps/ImageMagick-7.0.7-11-vc15-x64.zip"
    dest: "C:\\php\\imagick_dll.zip"
    timeout: 300
    headers: {"user-agent": "Mozilla/5.0"}
  changed_when: no
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_get_url

##### ANSIBLE VERSION
```
ansible 2.8.1
```
If I remember correctly, in 2.6.x version this bug was not presented.

##### CONFIGURATION
```
default
```

##### OS / ENVIRONMENT
Debian 9.9

##### STEPS TO REPRODUCE
Run the code from summary.

##### EXPECTED RESULTS
File is sucessfuly downloaded and ANY custom HTTP header can be set.

##### ACTUAL RESULTS
The most common HTTP headers can not be set, see https://stackoverflow.com/questions/239725/cannot-set-some-http-headers-when-using-system-net-webrequest . This is quite critical as some providers require HTTP headers like `User-Agent` making the `win_get_url` currently unusable.

What is the best way to overcome it and can this be hotfixed in the next stable release?
