### ISSUE TITLE
Ansible podman_image_info module doesn't have to fail if images doesn't exist

### ISSUE THREAD

**Issue by sshnaidm** [ansible/ansible#57899]
##### SUMMARY
When running podman_image_info on list of images and one of them doens't exist, the module fails. It's not always a desired behavior. Sometimes we might want just to get data about existing images and continue, like it's done for example in docker_image_info module.
We need a special option for that.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
podman_image_info module

##### ADDITIONAL INFORMATION
Example:
```yaml
- name: Gather info on several images and don't fail if some missing
  podman_image_info:
    name:
      - redis
      - idontexist
    skip_missing: true
```
