### ISSUE TITLE
add_host seems to not be working?

### ISSUE THREAD

**Issue by mark-casey** [ansible/ansible#5791]
This is a simplified version...(original: https://groups.google.com/forum/#!topic/ansible-project/c3pty9IrqRc). Am I doing something wrong?

ansible 1.4.3

``` yaml
- name: Group adding test
  hosts: localhost

  tasks:
    - name: Add a group
      add_host: hostname=localhost groups=testgroup

    - name: See if it is there
      debug: var=group_names
```

```


jenkins@ip-172-31-25-124:~/jobs/JobName/workspace$ ansible-playbook -vvvv -i 'localhost,' test.yml --connection=local

PLAY [Group adding test] ******************************************************

GATHERING FACTS ***************************************************************
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-1390856983.1-251208038321775 && chmod a+rx $HOME/.ansible/tmp/ansible-1390856983.1-251208038321775 && echo $HOME/.ansible/tmp/ansible-1390856983.1-251208038321775']
<localhost> REMOTE_MODULE setup
<localhost> PUT /tmp/tmpMgWuqZ TO /var/lib/jenkins/.ansible/tmp/ansible-1390856983.1-251208038321775/setup
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /var/lib/jenkins/.ansible/tmp/ansible-1390856983.1-251208038321775/setup; rm -rf /var/lib/jenkins/.ansible/tmp/ansible-1390856983.1-251208038321775/ >/dev/null 2>&1']
ok: [localhost]

TASK: [Add a group] ***********************************************************
creating host via 'add_host': hostname=localhost
added host to group via add_host module: testgroup
ok: [localhost] => {"new_groups": ["testgroup"], "new_host": "localhost"}

TASK: [See if it is ther] *****************************************************
ok: [localhost] => {
    "group_names": []
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
