### ISSUE TITLE
dconf should apply GVariant format internally

### ISSUE THREAD

**Issue by overratedpro** [ansible/ansible#57920]
##### SUMMARY

Writing dconf values requires proper formatting (GVariant) or else the invocation will fail. Instead the module should internally applly GVariant formatting basing on the passed YAML variable type and only then pass prepared values to the underlying `dconf` command/lib. For example a string should be automatically single-quoted, a list stringified, etc.

For now I am using a dirty workaround inside a playbook/role:
```
- set_fact:
      quoted_format: >-
          '%s'
- dconf:
      key: "/org/gnome/deja-dup/{{ item.key }}"
      value: "{{ quoted_format | format(item.value) }}"
  with_items:
      - key: backend
        value: s3
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dconf
##### ANSIBLE VERSION

```paste below
ansible 2.5.1
  config file = ansible.cfg
  configured module search path = [u'modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

```
also happens with latest from pip:
```
ansible 2.8.1
  config file = ansible.cfg
  configured module search path = ['modules']
  ansible python module location = .virtualenv/lib/python3.6/site-packages/ansible
  executable location = .virtualenv/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```
##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
$ uname -a
Linux 0x01-X260 4.15.0-46-lowlatency #49-Ubuntu SMP PREEMPT Wed Feb 6 10:23:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

##### STEPS TO REPRODUCE

```yaml
$ ansible -i 127.0.0.1, -e ansible_connection=local -m dconf -a 'key=/org/gnome/deja-dup/backend value=s3' 127.0.0.1

```

##### EXPECTED RESULTS

module successfully applies value to dconf registry

##### ACTUAL RESULTS

```paste below
127.0.0.1 | FAILED! => {
    "changed": false, 
    "msg": "dconf failed while write the value with error: error: 0:expected value\n\nUsage:\n  dconf write KEY VALUE \n\nWrite a new value to a key\n\nArguments:\n  KEY         A key path (starting, but not ending with '/')\n  VALUE       The value to write (in GVariant format)\n\n"
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/dconf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/dconf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @azaghal
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jdufresne** [comment]
This would be especially nice for settings that are very longs lists. For example, when setting `/org/gnome/shell/favorite-apps` to more than few items would be great if this could be expressed as a list in YAML syntax.

```yml
- dconf:
    key: /org/gnome/shell/favorite-apps
    value:
      - firefox.desktop
      - mozilla-thunderbird.desktop
      - org.gnome.Terminal.desktop
      - emacs.desktop
      ...
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/debconf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/debconf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bcoca
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/dconf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/dconf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by impala454** [comment]
@jdufresne I managed a workaround for that case as well.  Though am following this issue for the correct solution.
```
    - name: GNOME Preferences - Set favorite apps list
      set_fact:
        favorite_apps:
          - code.desktop
          - slack.desktop
          - google-chrome.desktop
          - org.gnome.Terminal.desktop
          - byobu.desktop
          - org.gnome.Nautilus.desktop

    - name: GNOME Preferences - Add favorite apps
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "[{% for item in favorite_apps %}('{{ item }}'),{% endfor %}]"
        state: present
      become_user: "{{ managed_user }}"
```
