### ISSUE TITLE
Newlines are somewhere beeing stripped during templating

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#5792]
This is a follow up to: https://github.com/ansible/ansible/pull/342/files -- I think the issue still exists. My Playbook is:

```

---
- hosts: all
  connection: ssh
  tasks:
    - name: Test
      copy:
        dest: /tmp/bla2
        content: "test\n"

    - name: Test2
      copy:
        dest: /tmp/bla
        content: "{{ 'test' }}\n"
```

"od -c" output of the results:

```
$ od -c /tmp/bla
0000000   t   e   s   t
0000004
$ od -c /tmp/bla2
0000000   t   e   s   t  \n
0000005
```
