### ISSUE TITLE
VMware: request removing disk controller feature for vmware_guest_disk

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#57937]
##### SUMMARY

vmware_guest_disk module can be used to add, configure, remove disks, we also want to use it to removing disk controller if there is no disks attaching to it.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest_disk
##### ADDITIONAL INFORMATION

This is used to remove the disk specified.
```yaml
disk:
  - state: absent
     scsi_controller: 1
     unit_number: 1
```
Maybe this can be used to remove the specified disk controller if there is no disk unit_number is configured in yml? Don't know if this is an appropriate way to do this. Thanks.
```yaml
disk:
  - state: absent
   scsi_controller: 2
```
