### ISSUE TITLE
Ansible 2.8 not respecting Python VirtualEnv

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/ansible#57949]
##### SUMMARY
Looks like working with Ansible 2.8 and Python virtual environment is no longer working as expected, and Ansible is using predefined (fallback) python interpreter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible-core

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.8.1
  config file = None
  ansible python module location = <FULL PATH>/002_cli/venv/lib/python3.7/site-packages/ansible
  executable location = <FULL PATH>/002_cli/venv/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION
```paste below
None (No changes)
```

##### OS / ENVIRONMENT

```
uname
Darwin
```

##### STEPS TO REPRODUCE

ansible-playbook -vvv -i hosts az_create_resources.yml

```yaml
---
# hosts file is having only one item: localhost 
- name: Create Azure VM
  gather_facts: false
  hosts: localhost
  connection: local

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: test-rg
        location: uksouth
```

##### EXPECTED RESULTS

That ansible will run python interpreter from virtualenv.

##### ACTUAL RESULTS

```
[WARNING]: Platform darwin on host localhost is using the discovered Python interpreter at /usr/bin/python
```
