### ISSUE TITLE
azure_rm_sqldatabase - specify sku?

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#57965]
##### SUMMARY
I can't seem to specify the sku when creating a SQL Database. I am not sure if "Edition" is supposed to be the Sku, but I specify edition "Basic" and I get edition "Standard" created.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_sqldatabase

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ax/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ax/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Linux (WSL / Windows 10)

##### STEPS TO REPRODUCE

I probably do not understand the relationship betwen 'edition' and 'sku'??

I create a database via:

```yaml

  - name: sql server
      azure_rm_sqlserver:
        resource_group: "myrg"
        name: "myserver9912"
        admin_username:  "myadmin9912"
        admin_password: "mypassword9912"

   - name: create db
      azure_rm_sqldatabase:
        edition: basic
        resource_group: "myrg"
        server_name: "myserver9912"
        name: "mydatabase9912"

 - name: Get instance of SQL Database
      azure_rm_sqldatabase_facts:
        resource_group: "myrg"
        server_name: "myserver9912"
        name: "mydatabase9912"

```

the facts returned are:

```json
            ...
            "location": "centralus",
            "sku": {
                "capacity": 10,
                "name": "Standard",
                "tier": "Standard"
            },
            "status": "Online",
           ...
```

```yaml

```

##### EXPECTED RESULTS
I would like to be able to create a Basic tier DB.

##### ACTUAL RESULTS
Got a Standard tier DB.
Also if I create using the above playbook, then change the SKU to Basic in the portal, then the playbook fails next time it runs, with "KeyError 'edition'".
