### ISSUE TITLE
XML files created by the bigip_asm_policy_fetch module are empty

### ISSUE THREAD

**Issue by gnagorski** [ansible/ansible#57972]
##### SUMMARY
XML files created by the bigip_asm_policy_fetch module are empty.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
bigip_asm_policy_fetch

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = None
  configured module search path = [u'/Users/gnagorski/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
Target device: BIG-IP 12.1.3.1

##### STEPS TO REPRODUCE
```
---
- name: Fetch ASM policy
  connection: local
  gather_facts: False

  vars_prompt:
    - name: "username"
      prompt: "Enter BIG-IP username"
      private: yes
    - name: "password"
      prompt: "Enter BIG-IP password"
      private: yes

  environment:
    F5_SERVER: ltm01
    F5_USER: "{{ username }}"
    F5_PASSWORD: "{{ password }}"
    F5_SERVER_PORT: 443

  tasks:
    - name: Get ASM policy
      bigip_asm_policy_fetch:
        name: ASM-POLICY
        partition: CUSTOMER-PARTITION
        file: ASM-POLICY.xml
        dest: /tmp/asm-export/

```

##### EXPECTED RESULTS
A file at /tmp/asm-export/ASM-POLICY.xml with the settings of ASM-POLICY.

##### ACTUAL RESULTS
The playbook runs without any errors and creates a file at /tmp/asm-export/ASM-POLICY.xml, but the file is empty. I walked through the steps this module takes, and the XML file created on the LTM has the expected content. However, the file that is created on the local machine is empty. I also tried using the `inline` option, but no XML is written to the terminal window with that option.
