### ISSUE TITLE
[openssh_keypair] Comment missing in returned `public_key`

### ISSUE THREAD

**Issue by jneuendorf** [ansible/ansible#57991]
##### SUMMARY
The comment (provided as `comment` parameter) only exists in the dumped public key file but not in the returned `public_key` string.

See https://github.com/ansible/ansible/issues/52663#issuecomment-502645374 and https://github.com/ansible/ansible/pull/53214 for details.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module `openssh_keypair`

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = <SOME_PROJECT>/deploy/ansible.cfg
  configured module search path = ['/Users/jim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:39) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(<SOME_PROJECT>/deploy/ansible.cfg) = ['<SOME_PROJECT>/deploy/inventory']
DEFAULT_REMOTE_USER(<SOME_PROJECT>/deploy/ansible.cfg) = ubuntu
DEFAULT_VAULT_PASSWORD_FILE(<SOME_PROJECT>/deploy/ansible.cfg) = <SOME_PROJECT>/deploy/vault_password.txt
```

##### OS / ENVIRONMENT

macOS 10.13.6

##### STEPS TO REPRODUCE

`ansible-playbook -i inventory/test generate_key_playbook.yaml`

```yaml
---
- name: Generate key
  hosts: all
  tasks:
    - name: Create SSH key
      openssh_keypair:
        path: /tmp/id_test_rsa
        comment: "test@beta"
      register: ssh_key
    - assert:
        that: ssh_key.public_key[-9:] == "test@beta"
```

##### EXPECTED RESULTS

The above playbook's assertion should pass.

##### ACTUAL RESULTS

The above playbook's assertion does not pass.
