### ISSUE TITLE
SROS: SAS-Sx only -  configure command indicates it successfully ran, config not changed or saved

### ISSUE THREAD

**Issue by burnitup** [ansible/ansible#58038]
##### SUMMARY

Attempting to change tacacs health checks on a number of  Nokia devices, two models used.

The application of the health check parameters and the admin save  are both successfully run on the SAR - the SAS-Sx doesn't get the config changed or the admin saved.  these devices are authenticating against TACACS - there is no indication the command was run in the TACACS logs or the SAS-Sx devices.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

SROS

sros_config

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = /home/obfuscated/work/ansible-nokia/ansible.cfg
  configured module search path = [u'/home/obfuscated/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/python2venv/ansible-networks/network-appliances/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/python2venv/ansible-networks/network-appliances/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS

##### STEPS TO REPRODUCE

Run the below playbook again t a SAS-Sx device.

```yaml
---
- name: Change Nokia Tacacs Config
  gather_facts: no
  hosts: all
  vars:
    cli:
      host: "{{ ansible_host }}"
  tasks:
    ## configure system security password no health-check
    - name: run configure system security password no health-check
      sros_config:
        lines:
          configure system security password no health-check
        provider: "{{ cli }}"

    ## admin save
    - name: run an admin save
      sros_config:
        lines:
          admin save
        provider: "{{ cli }}"

```

##### EXPECTED RESULTS

Expect config to be modified and the config saved.

##### ACTUAL RESULTS

Configuration is not modified or saved.

```paste below

```
