### ISSUE TITLE
Some IOS command responses cause a JSON failure that cause the task to fail

### ISSUE THREAD

**Issue by guest715** [ansible/ansible#58056]
##### SUMMARY

Some IOS command responses include content that is interpreted as a failure despite the command succeeding
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command
lib/ansible/plugins/terminal/ios.py
lib/ansible/plugins/connection/network_cli.py
##### ANSIBLE VERSION

```paste below
ansible 2.8.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7.0

##### STEPS TO REPRODUCE

Apply to following configuration to the IOS device where there is no current route to 1.1.1.1:
```
archive
  path scp://cisco:cisco@1.1.1.1/archive/cisco
  write-memory
```

```yaml
- name: Save running configuration
   ios_command:
     commands:
        - command: ‘copy running-config startup-config’
          prompt: ‘Destination filename \[startup-config\]\?’
          answer: “”
```

##### EXPECTED RESULTS

The config is successfully written so the playbook should succeed.

##### ACTUAL RESULTS

The playbook fails despite the config being successfully written.

```paste below
TASK [cisco : Save running configuration ] ***
fatal: [cisco]: FAILED! => {“changed”: false, “msg”: “py running-config startup-config\r\r\nDestination filename [startup-config]? startup-config\r\r\nBuilding configuration...\r\r\n[OK]\r\r\nWriting archive/cisco-Jun-21-2019-00-43-43.148-UTC-0 % Connection timed out; remote host not responding\r\r\n\r\r\ncisco#”}
```

```
The full traceback is:
WARNING: The below traceback may *not *be related to the actual failure.
  File “/tmp/ansible_ios_command_payload_dh40vA/ansible_ios_command_payload.zip/ansible/module_utils/network/ios/ios.py”, line 135, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File “/tmp/ansible_ios_command_payload_dh40vA/ansible_ios_command_payload.zip/ansible/module_utils/connection.py”, line 188, in __rpc__
    raise ConnectionError(to_text(msg, errors=’surrogate_then_replace’), code=code)
```
