### ISSUE TITLE
VMware: vmware_guest_disk autoselect_datastore returning invalid datastores

### ISSUE THREAD

**Issue by tmmruk** [ansible/ansible#58068]
##### SUMMARY
When using autoselect_datastore in vmware_guest_disk module the list of datastores returned is datacenter wide meaning that datastores not attached to the VM's cluster could be selected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_disk

##### ANSIBLE VERSION

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/txmooresa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```
None
```

##### OS / ENVIRONMENT
RedHat Linux Enterprise Server 7.5
vSphere 6.7 U2
pyvim (2.0.24)
pyvmomi (6.7.1.2018.12)

##### STEPS TO REPRODUCE

In vCenter create 2 clusters, each with different datastores presented. Ensure the datastore with the most free space is in a cluster that the target vm is NOT a member of.
Use the below task to add a new virtual disk to an existing VM with one disk on scsi controller 0.
The autoselect function will pick the datastore with the most free space in the vCenter datacenter, however the datastore is not accessible to the VM.

```yaml
- name: Add Additional VMDK Disk
  vmware_guest_disk:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ vcenter_datacenter }}'
      validate_certs: no
      name: "{{ vm_name }}"
      disk:
      - size_gb: 1
        autoselect_datastore: true
        scsi_controller: 0
        type: thin
        unit_number: 1
```

##### EXPECTED RESULTS
Selected datastore should be accessible to the VM. If all disks for a VM are on the same datastore/dscluster then the default behavior should be to use that datastore/dscluster.

##### ACTUAL RESULTS

Datastore with the most free space is selected in the datacenter. This may not be accessible to the VM.

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to manage disks for virtual machine 'test-vm1' with exception : (\"Invalid configuration for device '0'.\", None)"}
```
