### ISSUE TITLE
Removal for AWS Route53 TXT records with commas

### ISSUE THREAD

**Issue by kesor** [ansible/ansible#58084]
##### SUMMARY

When AWS Route53 has a TXT record with a value that includes commas, it is impossible to remove it using Ansible.

The official example in the documentation shows this pattern to use:

```
# Retrieve the details for new.foo.com
- route53:
      state: get
      zone: foo.com
      record: new.foo.com
      type: TXT
  register: rec

# Delete new.foo.com TXT record using the results from the get command
- route53:
      state: absent
      zone: foo.com
      record: "{{ rec.set.record }}"
      ttl: "{{ rec.set.ttl }}"
      type: "{{ rec.set.type }}"
      value: "{{ rec.set.value }}"
```

When `{{ rec.set.value}}` is something like `"aaaa,bbbb"` in a `TXT` record, this fails with the error -

    "[Tried to delete resource record set [name='new.foo.com.', type='TXT'] but the rdata provided is invalid]"

Looking at AWS CloudTrail logs, and in Ansible verbose logs shows that it has split the value into two values instead of keeping the original TXT value as-is.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloud / amazon / route53

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  8 2019, 18:17:52) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=2m -o ControlPath=/tmp/ansible-ssh-%C
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%C
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 3
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Using the Cloud AWS Route53 module in Ansible 2.8.1

##### EXPECTED RESULTS

Expected to be able to remove Route53 `TXT` records, but its seems to be completely impossible to do with Ansible.

##### ACTUAL RESULTS

AWS returns an error, because the request was sent incorrectly.

```paste below
[Tried to delete resource record set [name='new.foo.com.', type='TXT'] but the rdata provided is invalid]
```
