### ISSUE TITLE
xml module: element content gets cut off by XML comments

### ISSUE THREAD

**Issue by couyangm** [ansible/ansible#58094]
##### SUMMARY

When trying to get text content from a given XPath, the content gets cut off where there are XML comments.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

xml module
##### ANSIBLE VERSION

```paste below
ansible 2.5.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux 7 (Core)

##### STEPS TO REPRODUCE

example playbook:

```yaml
---
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    xml_string: >
                 <level1>
                   <level2>
                     text before comment
                     <!-- comment -->
                     text after comment
                   </level2>
                 </level1>
  tasks:
  - name: read xml with comments
    xml:
      xmlstring: "{{ xml_string }}"
      xpath: "/level1/level2"
      content: text
    register: content
  - debug:
      var: content.matches[0]
```

##### EXPECTED RESULTS

without the comment in xml_string:
ok: [test1] => {
    "content.matches[0]": {
        "level2": "\n    text before comment\n    text after comment\n  "
    }
}

##### ACTUAL RESULTS

with comment in xml_string:
ok: [test1] => {
    "content.matches[0]": {
        "level2": "\n    text before comment\n    "
    }
}

```paste below

```
