### ISSUE TITLE
os_server and device name for boot volume

### ISSUE THREAD

**Issue by ric79** [ansible/ansible#58110]
Hello,
when I create a server on Openstack using HOT template I can use: 

```
 MYSERVER:
    type: OS::Nova::Server
    depends_on: [ port_mgmt ]
    properties:
      name: { get_param: VMname }
      block_device_mapping: [{ device_name: "vda", volume_id : { get_resource : boot_volume }, delete_on_termination : "true" }]
```
In os_server I can specify **boot_volume** but I cannot map the device_name (vda)

```
- name: "Create server {{server_name}}"
  os_server:
    ...
    state: present
    name: "{{server_name}}"
    boot_volume: "{{volume_name}}"
    terminate_volume: true
    ...
```

Is it a missing feature?

Riccardo

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ric79: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ric79** [comment]
##### SUMMARY
os_server does not allow to attach a boot volume specifying the device_name. 

##### ISSUE TYPE
- When I create an openstack server I want to specify the device_name.
Here for example is an HOT template:

```
 MYSERVER:
    type: OS::Nova::Server
    depends_on: [ port_mgmt ]
    properties:
      name: { get_param: VMname }
      block_device_mapping: [{ device_name: "vda", volume_id : { get_resource : boot_volume }, delete_on_termination : "true" }]
```
And here the Ansible version: 
```
- name: "Create server {{server_name}}"
  os_server:
    ...
    state: present
    name: "{{server_name}}"
    boot_volume: "{{volume_name}}"
    terminate_volume: true
    ...
```
I need to specify "vda" as device name for boot_volume

##### COMPONENT NAME
https://docs.ansible.com/ansible/latest/modules/os_server_module.html

##### ANSIBLE VERSION
I'm using 2.6.4 but also the latest (2.8) is affected.

##### CONFIGURATION
See before

##### OS / ENVIRONMENT

##### STEPS TO REPRODUCE

##### EXPECTED RESULTS

##### ACTUAL RESULTS
