### ISSUE TITLE
Unexpected interaction between accelerated mode and "remote_user" in a task

### ISSUE THREAD

**Issue by jf89** [ansible/ansible#5812]
If you use accelerated mode and the remote_user option in a task, then the remote_user is silently ignored after a connection has been established.

The sequence of events, as far as I can see is:

First connection is made using whatever the value of remote user is. Ephemereal daemon is launched running as that user.
Subsequent command comes in with a new remote_user set, but the command connects to the already running daemon running as the previous user.

Example playbook (test.yml):

```
- hosts: all
  accelerate: yes
  tasks:
      - name: Test 1
        shell: 'whoami > /foo/bar/output'

      - name: Test 2
        shell: 'whoami >> /foo/bar/output'
        remote_user: baz
```

If this playbook is run with:

```
ansible-playbook test.yml -i <( echo localhost ) -u root
```

It will print out:
root
root

When you might naively expect (as I did)
root
baz

As opposed to fixing the bug, I have elected to use "sudo_user" in my case. However, ansible should _at least_ warn that there is a bad interaction between accelerated mode and the remote_user option.
