### ISSUE TITLE
tower_job_template: Add job template is not idempotent

### ISSUE THREAD

**Issue by rgerardi** [ansible/ansible#58146]
##### SUMMARY

The module tower_job_template is not idempotent

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module: tower_job_template

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /home/user1/tmp/tower01.olab/idempotency/ansible.cfg
  configured module search path = ['/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/user1/tmp/tower01.olab/idempotency/ansible.cfg) = ['/home/user1/tmp/tower01.olab/idempotency/hosts']
INTERPRETER_PYTHON(/home/user1/tmp/tower01.olab/idempotency/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/user1/tmp/tower01.olab/idempotency/ansible.cfg) = False
```

##### OS / ENVIRONMENT

OS: Fedora 30 (Workstation Edition)
Tower: Tower 3.5.0 running on RHEL 8

##### STEPS TO REPRODUCE

1. Execute the playbook below to add a Job Template into Tower:

```yaml
---
- name: Add a Job Template
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
  - name: Add Job Templates
    tower_job_template:
      name: "Test Job Template 01"
      job_type: "run"
      inventory: "Demo Inventory"
      project: "Demo Project"
      playbook: "hello_world.yml"
      credential: "Demo Credential"
      state: present
      tower_host: "https://{{ tower_host }}"
      tower_username: admin
      tower_password: ************
      tower_verify_ssl: no
```
2. Execute the same playbook again.

##### EXPECTED RESULTS

When executing the module for the second time, result should not be changed

##### ACTUAL RESULTS

Result of playbook execution is always changed

First Execution
```
ansible-playbook add_job_templates.yaml -e "tower_host=tower01.olab.home.ca" -v 
Using /home/user1/tmp/tower01.olab/idempotency/ansible.cfg as config file

PLAY [Add a Job Template] ************************************************************************************************************************

TASK [Add Job Templates] *************************************************************************************************************************
changed: [localhost] => {"changed": true, "id": 24, "job_template": "Test Job Template 01", "state": "present"}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Second Execution
```
ansible-playbook add_job_templates.yaml -e "tower_host=tower01.olab.home.ca" -v
Using /home/user1/tmp/tower01.olab/idempotency/ansible.cfg as config file

PLAY [Add a Job Template] ************************************************************************************************************************

TASK [Add Job Templates] *************************************************************************************************************************
changed: [localhost] => {"changed": true, "id": 24, "job_template": "Test Job Template 01", "state": "present"}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
