### ISSUE TITLE
gem module hangs when using state=absent

### ISSUE THREAD

**Issue by mtpereira** [ansible/ansible#5819]
Hello,

I've stumbled upon gem module hanging when trying to remove it by using state=absent. Here's a playbook that will reproduce the problem:

``` yaml

---
- hosts: all
  sudo: yes

  tasks:
  - apt: pkg=ruby1.9.3 update_cache=yes
  - gem: name=rake state=latest user_install=no
  - gem: name=rake state=absent user_install=no
```

I've used the following command to run it:

```
ansible-playbook -i ansible_inventory --user vagrant --sudo --private-key $path_to_key gem.yml
```

I'm using ansible 1.4.4.

Here's the pstree of the play:

```
sh,4037 -cecho SUDO-SUCCESS-hhtilorafbkqvpjssrdfsizqksqmhxqi; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-1391016614.61-10260315944499/gem; rm -rf /home/vagrant/.ansible/tm
  └─python,4038 /home/vagrant/.ansible/tmp/ansible-1391016614.61-10260315944499/gem
      └─gem,4041 /usr/bin/gem uninstall --all rake
          └─{gem},4042
```

When you run /usr/bin/gem uninstall --all rake by hand you get this output:

```
/usr/bin/gem uninstall --all rake
Remove executables:
    rake

in addition to the gem? [Yn]
```

For that reason, I assume that is waiting for user input.

I see no flag for gem to force yes, so it'll probably necessary to pipe a yes:

```
yes | /usr/bin/gem uninstall --all rake
Removing rake
Successfully uninstalled rake-10.1.1
```

Thank you.
