### ISSUE TITLE
UFW - allow specification by service name

### ISSUE THREAD

**Issue by benyanke** [ansible/ansible#58198]
##### SUMMARY
Currently, the UFW module allows a user to specify `app` which maps to a config in `/etc/ufw/applications.d`. However, UFW also understands the concept of `service`, which loads from `/etc/service`. I would like to propose adding an additional key, functioning similar to `app`, but for `service`. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
UFW

##### ADDITIONAL INFORMATION - Example Usage

```yaml
    - name: "tftp | UFW - Whitelist TFTP Allow"
      ufw:
        rule: allow
        service: "tftp"
        src: "1.2.3.4"
        comment: "Allow TFTP Protocol"

```
