### ISSUE TITLE
modules/network/junos/junos_config: allow specification of backup format

### ISSUE THREAD

**Issue by CameronNemo** [ansible/ansible#58219]
##### SUMMARY
For configuration source, one is able to specifiy the format used. It would be nice if a similar option could be allowed for the backup format (with choices of 'text' and 'set'). Current code tries set first, then falls back to text if it is unavailable.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_config.py#L415

##### ADDITIONAL INFORMATION

```yaml
- name: backup config
  backup: true
  backup_options:
    format: text
```
