### ISSUE TITLE
win_snmp not working ?

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#58222]
##### SUMMARY

win_snmp module doesnt set / add community strings or managers.  playbook results always shows the current configuration but no changes 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_snmp

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /root/myplatform/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows server 2016 standard edition

##### STEPS TO REPRODUCE

simple playbook based on documentation sample. tested with kerberos and ntlm method, also with become: 

```yaml
---
- name: SNMP test
  hosts: testhost
  gather_facts: no

  vars:
    ansible_user: AD username
    ansible_password: AD password
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    snmp_community_ro:
      - private
    snmp_managers:
      - localhost
      - 10.10.10.10 
  tasks:
  - name: Replace SNMP communities
    win_snmp:
      communities: "{{ snmp_community_ro}}"
      managers: "{{ snmp_managers }}"
      action: set

```

##### EXPECTED RESULTS

expected to get SNMP settings changed

##### ACTUAL RESULTS

playbook result only shows the current SNMP settings - no changes are applied

```paste below

PLAY [SNMP test] ***************************************************************

TASK [Replace SNMP communities] ************************************************
ok: [testhost] => {"changed": false, "community_strings": [], "permitted_managers": ["localhost"]}

PLAY RECAP *********************************************************************
testhost : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


```
