### ISSUE TITLE
Error: "No package matching 'docker-ce' is available" but apt-cache shows it, apt installs it

### ISSUE THREAD

**Issue by MarcDiethelm** [ansible/ansible#58237]
##### SUMMARY

Platform: armv7, OS: Armbian Bionic 18.04
The package "docker-ce" fails to install using the module `package`. Error msg: `No package matching 'docker-ce' is available`. However the repository is set up correctly and the package is found using `apt-cache show docker-ce` manually; the package can be installed using `apt install docker-ce` manually. This is a package made available by adding the repository from download.docker.com. Installing other packages with Ansible, e.g. from Ubuntu Universe repo works too.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

package

##### ANSIBLE VERSION

```paste below
"ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]"
```

##### CONFIGURATION

```paste below
""
```

##### OS / ENVIRONMENT
Platform: armv7, OS: Armbian Bionic 18.04, Rock64 single board computer

##### STEPS TO REPRODUCE

See summary... the last task fails, even though it should not, calling `apt install docker-ce` works just fine.

```yaml
- name: Add Docker apt key.
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    ignore_errors: true
    become: true

- name: Add Docker repository.
     apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: true
      become: true

 - name: Install Docker.
      package:
        name: docker-ce
        state: present
      become: true
```

##### EXPECTED RESULTS
It should install successfully

##### ACTUAL RESULTS
Fatal error
```paste below
fatal: [rock64.lan]: FAILED! => changed=false
  msg: No package matching 'docker-ce' is available
```
