### ISSUE TITLE
gcp_dns_resource_record_set - creating dns entries via specifying managed_zone.name does not work

### ISSUE THREAD

**Issue by gebi** [ansible/ansible#58243]
##### SUMMARY

Creating dns entries via specifying managed_zone.name does not work

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_dns_resource_record_set

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /.../ansible.cfg
  configured module search path = [u'/.../library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/.../ansible.cfg) = True
ANSIBLE_PIPELINING(/.../ansible.cfg) = True
ANSIBLE_SSH_ARGS(/.../ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN(/.../ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/.../facts
CACHE_PLUGIN_TIMEOUT(/.../ansible.cfg) = 7200
DEFAULT_FORKS(/.../ansible.cfg) = 50
DEFAULT_GATHERING(/.../ansible.cfg) = smart
DEFAULT_HOST_LIST(/.../hosts.ini']
DEFAULT_LOG_PATH(/.../log
DEFAULT_MODULE_PATH(/.../library']
DEFAULT_MODULE_UTILS_PATH(/.../module_utils']
DEFAULT_REMOTE_USER(/.../ansible.cfg) = root
DEFAULT_ROLES_PATH(/.../.galaxy']
DEFAULT_STDOUT_CALLBACK(/.../ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/.../get-vault-pass.sh
```

##### OS / ENVIRONMENT

Debian

##### STEPS TO REPRODUCE

```yaml
- name: DNS setup
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    target_ip: "123.123.123.123"
    gcp_project: "PROJECT"
    gcp_cred_kind: serviceaccount
    gcp_cred_content: "{{ gcp_service_account }}"
    gcp_cred_file: "./PROJECT-12345678.json"
  tasks:
    - name: create dns zones
      gcp_dns_managed_zone:
        name: foo-zone
        dns_name: bar.foo.
        description: "foo"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: registered_zones

    - name: Create dns records
      gcp_dns_resource_record_set:
        managed_zone:
          name: "foo-zone"
        # this works
        #managed_zone: "{{ registered_zones }}"
        name: "www.bar.foo."
        target:
          - "{{ target_ip }}"
        type: "A"
        ttl: 3600
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        #service_account_contents: "{{ gcp_cred_content }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
```

##### EXPECTED RESULTS

The dns record be created, as documented in https://docs.ansible.com/ansible/latest/modules/gcp_dns_resource_record_set_module.html#id3
managed_zone (required) ... "First, you can place a dictionary with key 'name' and value of your resource's name"

##### ACTUAL RESULTS

```paste below
TASK [Create dns records] *************************************************************************************************************
task path: /.../cloud-dns-creating-records-via-specifying-zone-by-name-does-not-work.yml:22
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/google/gcp_dns_resource_record_set.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: foo
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_gcp_dns_resource_record_set_payload_CF7AQP/ansible_gcp_dns_resource_record_set_payload.zip/ansible/module_utils/gcp_utils.py", line 223, in raise_for_status
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

fatal: [localhost]: FAILED! => changed=false 
  invocation:
    module_args:
      auth_kind: serviceaccount
      managed_zone:
        name: foo-zone
      name: www.bar.foo.
      project: PROJECT
      scopes:
      - https://www.googleapis.com/auth/ndev.clouddns.readwrite
      service_account_contents: null
      service_account_email: null
      service_account_file: ./PROJECT-12345678.json
      state: present
      target:
      - 123.123.123.123
      ttl: 3600
      type: A
  msg: 'GCP returned error: {u''error'': {u''message'': u"Invalid value for ''parameters.name'': ''None''", u''code'': 400, u''errors'': [{u''reason'': u''invalid'', u''message'': u"Invalid value for ''parameters.name'': ''None''", u''domain'': u''global''}]}}'

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
