### ISSUE TITLE
set_fact and run_once incorrectly setting facts

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#58240]
##### SUMMARY
If set_fact is used with run_once the fact gets applied to all hosts.

Edit: Documentation should mention `delegate_facts: True` is required.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
run_once

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/PycharmProjects/ansible-2/lib/ansible
  executable location = /home/user/PycharmProjects/ansible-2/bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```

##### OS / ENVIRONMENT
ArchLinux

##### STEPS TO REPRODUCE
There are at least two hosts in the group TestGroup
```yaml
- name: Test
  hosts: TestGroup
  become: false
  gather_facts: false
  tasks:
    - set_fact:
        foo: foo
    - run_once: yes
      block:
        - set_fact:
            foo: bar
    - ping: null
      when: foo == "bar"
```

##### EXPECTED RESULTS
The final ping gets executed for all hosts except the one that was randomly chosen for the RunOnce block.

##### ACTUAL RESULTS
The final ping gets skipped for all hosts.
