### ISSUE TITLE
azure_rm_aks not updating credentials

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#58285]
##### SUMMARY
When running azure_rm_aks and specifying new service principal credentials for an existing cluster, the new credentials are not applied.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_aks

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/val/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/val/.local/lib/python2.7/site-packages/ansible
  executable location = /home/val/.local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Ubuntu on Windows 10 (WSL)

##### STEPS TO REPRODUCE

Assume you have credential id id1, with secret secret1:

```yaml

- name: Initial
  azure_rm_aks:
    name: "myclustername123a"
    location: "centralus"
    resource_group: "myrgname123a"
    dns_prefix: "myrgname123a"
    kubernetes_version: "1.13.5"
    linux_profile:
      admin_username: "abc"
      ssh_key: "...."
    agent_pool_profiles:
      - name: "mypool123a"
        count: 3
        vm_size: ...
    service_principal:
      client_id: "... id1..."
      client_secret: "... secret1 ..."

```

then we want to use id2 with secret 2:

```yaml
- name: Initial
  azure_rm_aks:
    name: "myclustername123a"
    location: "centralus"
    resource_group: "myrgname123a"
    dns_prefix: "myrgname123a"
    kubernetes_version: "1.13.5"
    linux_profile:
      admin_username: "abc"
      ssh_key: "...."
    agent_pool_profiles:
      - name: "mypool123a"
        count: 3
        vm_size: ...
    service_principal:
      client_id: "... id2.."
      client_secret: "... secret2..."

```

The cluster SPN is stil id1 secret1.

##### EXPECTED RESULTS

After running the second block, the cluster should be using id2 secret2.

##### ACTUAL RESULTS

Cluster is still using id1 secret1, no change made.

```paste below

```
