### ISSUE TITLE
npm module's ci option always reports "changed"

### ISSUE THREAD

**Issue by sugar700** [ansible/ansible#58280]
##### SUMMARY

Having code like this:

```yaml
- name: Install dependencies
  npm:
    path: /something
    ci: yes
    state: present
```

Always reports that this caused a change, even if all packages are already in `package.lock` versions. This is because the following code causes `changed` to be always set to `True`: https://github.com/ansible/ansible/blob/17186bbde05dce4c9ba7d1d7876b2d999d2ff6dd/lib/ansible/modules/packaging/language/npm.py#L283-L285.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

npm

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xfix/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/xfix/kod/vault-pass
```

##### OS / ENVIRONMENT

Fedora 30

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:
  - name: Init
    shell: npm init -y

  - name: npm install to ensure package-lock.json gets created
    shell: npm install

  - name: Build package with ci
    npm:
      ci: yes
      path: .

```

##### EXPECTED RESULTS

"Build package with ci" shouldn't be reported as changed as nothing did change

##### ACTUAL RESULTS

```paste below
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ci": true,
            "executable": null,
            "global": false,
            "ignore_scripts": false,
            "name": null,
            "path": ".",
            "production": false,
            "registry": null,
            "state": "present",
            "unsafe_perm": false,
            "version": null
        }
    }
}
```
