### ISSUE TITLE
DNS Made Easy: Cannot update existing txt record

### ISSUE THREAD

**Issue by andrewsav-bt** [ansible/ansible#58306]
##### SUMMARY

If you create a TXT records with a plain value, like `world` and then try to update this record (re-run the task) it fails. This happens because if the value is not surrounded by quotation marks (e.g. `'"world"'`) dnsmadeeasy adds the quotation marks. When [this code](https://github.com/ansible/ansible/blob/e6166b40cc8f8766b8c91c46e98a89afeec3bd8f/lib/ansible/modules/net_tools/dnsmadeeasy.py#L482) compares the values, it discovers that `world` is not equal `"world"` and does not match the records. As a result it tries to create the record again, which fails, since the record is already there.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnsmadeeasy

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
 config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

default
```paste below

```

##### OS / ENVIRONMENT

Awx docker-compose install.

##### STEPS TO REPRODUCE

Make sure that the record matching below already exists.

```yaml
  - name: Publish the challenge to DNS
    dnsmadeeasy:
      account_key: "{{dnsmadeeasy_apikey}}"
      account_secret: "{{dnsmadeeasy_apisecret}}"
      monitor: 'no'
      domain: "{{dnsmadeeasy_domain}}"
      state: "present"
      record_name: "hello"
      record_value: "world"
      record_type: 'TXT'
      record_ttl: 1800
      sandbox: 'yes'
```

##### EXPECTED RESULTS

Nothing changes, the task succeeds.

##### ACTUAL RESULTS

Task fails.

```paste below
{
    "_ansible_no_log": false,
    "warnings": [
        "Sandbox is enabled. All actions are made against the URL https://api.sandbox.dnsmadeeasy.com/V2.0/"
    ],
    "changed": false,
    "invocation": {
        "module_args": {
            "httpFqdn": null,
            "domain": "REDACTED",
            "protocol": "HTTP",
            "autoFailover": false,
            "record_ttl": 1800,
            "sensitivity": "Medium",
            "contactList": null,
            "account_key": "REDACTED",
            "ip2": null,
            "record_type": "TXT",
            "ip1": null,
            "ip4": null,
            "ip5": null,
            "record_name": "hello",
            "port": 80,
            "monitor": false,
            "ip3": null,
            "httpQueryString": null,
            "failover": false,
            "sandbox": true,
            "maxEmails": 1,
            "state": "present",
            "systemDescription": "",
            "record_value": "world",
            "httpFile": null,
            "validate_certs": true,
            "account_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "msg": "https://api.sandbox.dnsmadeeasy.com/V2.0/dns/managed/REDACTED/records returned 400, with body: HTTP Error 400: Bad Request"
}
```
