### ISSUE TITLE
xml: unexpectedly does html encoding on value

### ISSUE THREAD

**Issue by akamensky** [ansible/ansible#58316]
##### SUMMARY
XML module converts characters to their HTML representation. In my case it converted `&` to `&amp;` despite `&` actually opening a encoded sequence (in my specific case is `&#x5c;` for example).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
```paste below
ansible 2.7.11
  config file = /redacted/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
Centos 7.5

##### STEPS TO REPRODUCE
Example task
```yaml
- name: configure server.xml
  xml:
    path: "/path/to/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "relaxedPathChars", value: "[]|" }
    - { name: "relaxedQueryChars", value: "[]|{}^&#x5c;&#x60;&quot;&lt;&gt;" }
```

##### EXPECTED RESULTS
XML elements looking like this:
```xml
<Connector relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;"/>
```

##### ACTUAL RESULTS
```xml
<Connector relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&amp;#x5c;&amp;#x60;&amp;quot;&amp;lt;&amp;gt;"/>
```
