### ISSUE TITLE
Ansible snow modules authentication issues with sso / ADFS

### ISSUE THREAD

**Issue by danilansible** [ansible/ansible#58311]
##### SUMMARY

Trying to update an Incident using ansible's servicenow modules failing with below authentication error
"Unexpected HTTP GET response code. Expected 200, got 401"

The web servicenow login is usually SSO for us, does this module work with SSO / ADFS .
If not, is there an alternative to get this done

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

snow module  / pysnow

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, Apr 9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ansible/plugins/
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'inventory']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = default
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)
3.10.0-957.12.1.el7.x86_64

##### STEPS TO REPRODUCE

---
- name: test Snow ticket update
  hosts: localhost
  connection: local
  gather_facts: no
  ignore_errors: True
  tasks:
    - name: update an incident
      snow_record:
        username: username@domain
        password: pass
        instance: instancesnow
        state: present
        number: INC18832222
        data:
          work_notes : "Duplicate ticket"

```yaml
---
- name: test Snow ticket update
  hosts: localhost
  connection: local
  gather_facts: no
  ignore_errors: True
  tasks:
    - name: update an incident
      snow_record:
        username: username@domain
        password: pass
        instance: fire
        state: present
        number: INC18832222
        data:
          work_notes : "Duplicate ticket"
```

##### ACTUAL RESULTS

```paste below
PLAY [test Snow ticket update] ******************************************************************************

TASK [update an incident] ***********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "instance": "instancesnow", "lookup_field": "number", "msg": "Failed to update record: Unexpected HTTP GET response code. Expected 200, got 401", "number": "INC1880978", "table": "incident"}
...ignoring

PLAY RECAP **************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```
