### ISSUE TITLE
blockinfile overridden the original file

### ISSUE THREAD

**Issue by weihao** [ansible/ansible#58359]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.0
  config file = None
  configured module search path = [u'/Users/weihgao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

MacOS Mojave

##### STEPS TO REPRODUCE

```yaml
- name: Copy {{ SHELL_PROFILE }}
  blockinfile:
    dest: "{{ SHELL_PROFILE }}"
    block: "{{ lookup('file', '../files/template') }}"
    insertafter: EOF
    state: present
    create: yes
- name: Add tomcat@8 to PATH
  blockinfile:
    path: "{{ SHELL_PROFILE }}"
    block: |
      export PATH="/usr/local/opt/tomcat@8/bin:$PATH"
```
##### EXPECTED RESULTS

```
$ cat files/template
#######################
#       TOMCAT        #
#######################
export CATALINA_HOME="/usr/local/tomcat"
export TOMCAT_HOME=$CATALINA_HOME
export CATALINA_PID=$CATALINA_HOME/catalina_pid.txt

$ cat ~/.bash_profile
# BEGIN ANSIBLE MANAGED BLOCK
#######################
#       TOMCAT        #
#######################
export CATALINA_HOME="/usr/local/tomcat"
export TOMCAT_HOME=$CATALINA_HOME
export CATALINA_PID=$CATALINA_HOME/catalina_pid.txt
# END ANSIBLE MANAGED BLOCK
# BEGIN ANSIBLE MANAGED BLOCK
export PATH="/usr/local/opt/tomcat@8/bin:$PATH"
# END ANSIBLE MANAGED BLOCK
```

##### ACTUAL RESULTS

```
$ cat ~/.bash_profile
# BEGIN ANSIBLE MANAGED BLOCK
export PATH="/usr/local/opt/tomcat@8/bin:$PATH"
# END ANSIBLE MANAGED BLOCK
```

Task 1 copied the file template into the bash profile. Then task 2 write (insert after the end of the file) to the block text into the bash profile. 

But when I checked, the file was overridden and it is an unexpected behavior because the documentation said it should insert, not override.

If I only run task 1, the original file template will be copied into the dest. If I run both tasks, the one that gets ran first will get overridden.
