### ISSUE TITLE
bool filter does not evaluate template

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#58352]
##### SUMMARY
The deprecation notice encourages use of `bool` filter in the `when` condition instead of a bare variable. However, the `bool` filter does not seem to evaluate the variable (template) like using it "bare" does.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core / bool filter

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.1
  config file = /Users/d/code/ou/ansible.cfg
  configured module search path = ['/Users/d/code/ou/library']
  ansible python module location = /Users/d/code/ou/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/d/code/ou/venv/bin/ansible
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/Users/d/code/ou/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/d/code/ou/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/d/code/ou/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey
ANSIBLE_SSH_RETRIES(/Users/d/code/ou/ansible.cfg) = 3
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/d/code/ou/ansible.cfg) = ['/Users/d/code/ou/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/Users/d/code/ou/ansible.cfg) = ['timer', 'profile_tasks', 'datadog_callback']
DEFAULT_FILTER_PLUGIN_PATH(/Users/d/code/ou/ansible.cfg) = ['/Users/d/code/ou/plugins/filter']
DEFAULT_FORKS(/Users/d/code/ou/ansible.cfg) = 300
DEFAULT_INTERNAL_POLL_INTERVAL(/Users/d/code/ou/ansible.cfg) = 3.0
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/d/code/ou/ansible.cfg) = ['/Users/d/code/ou/plugins/lookup']
DEFAULT_MODULE_PATH(/Users/d/code/ou/ansible.cfg) = ['/Users/d/code/ou/library']
DEFAULT_VARS_PLUGIN_PATH(/Users/d/code/ou/ansible.cfg) = ['/Users/d/code/ou/plugins/vars']
HOST_KEY_CHECKING(/Users/d/code/ou/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/d/code/ou/ansible.cfg) = auto
RETRY_FILES_SAVE_PATH(/Users/d/code/ou/ansible.cfg) = /Users/d/code/ou
```

##### OS / ENVIRONMENT

MacOS / Python 3.7.3

##### STEPS TO REPRODUCE

Deprecation notice yells that simply using `need_firmware_upgrade|bool` is no longer cool:
> [DEPRECATION WARNING]: evaluating need_firmware_upgrade as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature
will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg

Therefore, I am attempting to append `|bool` to the `when` condition:

```yaml
    - set_fact:
        need_firmware_upgrade: >
          smartarray_ver is success and new_firmware.raid_version is version(smartarray_ver.json.FirmwareVersion.Current.VersionString, '>')
          or new_firmware.ilo_version is version(ilo_firmware_ver.json.Version, '>')
          or new_firmware.bios_version is version(bios_ver.json.Version, '>')
      changed_when: need_firmware_upgrade

    - hpilo_boot:
        host: '{{ ipmi_ip_address }}'
        login: '{{ ipmi_username }}'
        password: '{{ ipmi_password }}'
        media: cdrom
        image: '{{new_firmware.spp_url}}'
        force: yes
        state: boot_once
      when: need_firmware_upgrade|bool
      delegate_to: localhost

    - debug:
        msg: "{{ need_firmware_upgrade }}"
```

##### EXPECTED RESULTS

`when` statement should evaluate to True just like it does for a bare variable condition like this: `when: need_firmware_upgrade`.

##### ACTUAL RESULTS

Task is skipped because `when` evaluates to False. 
```
TASK [debug] *********************************************************************************************************************************************************************************************************************************
Tuesday 25 June 2019  19:16:27 +0200 (0:00:03.022)       0:00:35.331 **********
ok: [hostname] => {
    "msg": "smartarray_ver is success and new_firmware.raid_version is version(smartarray_ver.json.FirmwareVersion.Current.VersionString, '>') or new_firmware.ilo_version is version(firmware_vers.json.Current.SystemBMC.0.VersionString, '>') or new_firmware.bios_version is version(firmware_vers.json.Current.SystemRomActive.0.VersionString, '>')\n"
}
```
