### ISSUE TITLE
In a list var, in a var file, parentheses at the end of a sublist string with no spaces fail to load into with_items

### ISSUE THREAD

**Issue by pol** [ansible/ansible#5836]
Yes, this is a weird one.  If you have a list of hashes in a vars file that contains a sublist of strings, and that sublist has a string in it which has no spaces and ends in parens, the whole list will fail to load into with_items.

It is easiest to see with a test case.  Here it is:

So, if you have the following vars.yml file:

``` yaml

---
broken_list:
  - str1: I am the first string.
    str2: a string with parens doesn't break (things)
    sublist: 
      - string.with.no.spaces.and.parens(breaks)
      - string.with.no.paren.params.also.breaks()
  - str1: I am a string!
    str2: client2
    sublist: 
       - (parens) at the beginning don't matter

working_list_1:
  - str1: I am the first string.
    str2: a string with parens doesn't break (things)
    sublist: 
      - string.()with.inner.parens.is.fine
      - string_is-a-string()
  - str1: I am a string!
    str2: client2
    sublist: 
       - (parens) at the beginning don't matter

working_list_2:
  - str1: I am the first string.
    str2: a string with parens doesn't break (things)
    sublist: 
      - string_that_ends_with_parens_but_has_spaces(turns out fine)
      - spaces in the string also are (fine)
  - str1: I am a string!
    str2: client2
    sublist: 
       - (parens) at the beginning don't matter

working_list_3:
  - str1: string.with.no.spaces.and.parens(breaks)
    str2: string.with.no.paren.params.also.breaks()
    sublist:
      - foo
      - bar
  - str1: I am a string!
    str2: client2
    sublist:
      - foo
      - bat
```

And you have the following playbook.yml:

``` yaml

---
- hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks: 
    - name: debug
      debug: var=working_list1

    - name: strings work in with_items!
      debug: var={{item}}
      with_items: working_list1

    - name: debug
      debug: var=working_list2

    - name: strings work in with_items!
      debug: var={{item}}
      with_items: working_list2

    - name: debug
      debug: var=working_list2

    - name: strings that break in a sublist work fine in a top level string
      debug: var={{item}}
      with_items: working_list3

    - name: debug
      debug: var=broken_list

    - name: this sublist breaks in with_items!
      debug: var={{item}}
      with_items: broken_list
```

And you run that playlist with this:

```
$ ansible-playbook playbook.yml -i 'foo.domain.com, '
```

You will get the following result:

```
PLAY [all] ********************************************************************

TASK: [debug] *****************************************************************
ok: [foo.domain.com] => {
    "working_list1": "{{ working_list1 }}"
}

TASK: [strings work in with_items!] *******************************************
ok: [foo.domain.com] => (item=working_list1) => {
    "item": "working_list1",
    "working_list1": "{{ working_list1 }}"
}

TASK: [debug] *****************************************************************
ok: [foo.domain.com] => {
    "working_list2": "{{ working_list2 }}"
}

TASK: [strings work in with_items!] *******************************************
ok: [foo.domain.com] => (item=working_list2) => {
    "item": "working_list2",
    "working_list2": "{{ working_list2 }}"
}

TASK: [debug] *****************************************************************
ok: [foo.domain.com] => {
    "working_list2": "{{ working_list2 }}"
}

TASK: [strings that break in a sublist work fine in a top level string] *******
ok: [foo.domain.com] => (item=working_list3) => {
    "item": "working_list3",
    "working_list3": "{{ working_list3 }}"
}

TASK: [debug] *****************************************************************
ok: [foo.domain.com] => {
    "broken_list": "[{'str2': \"a string with parens doesn't break (things)\", 'str1': 'I am the first string.', 'sublist': ['string.with.no.spaces.and.parens(breaks)', 'string.with.no.paren.params.also.breaks()']}, {'str2': 'client2', 'str1': 'I am a string!', 'sublist': [\"(parens) at the beginning don't matter\"]}]"
}

TASK: [this sublist breaks in with_items!] ************************************
fatal: [foo.domain.com] => with_items expects a list

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/pol/playbook.retry

foo.domain.com             : ok=7    changed=0    unreachable=1    failed=0
```

I tried to catch the obvious edge cases, but as I was writing this, I kept finding more.  There are probably others.  I have no idea what causes this, I discovered it with a variable of nfs host mounts, which have the format "hostname(var=val,var=val,var=val)".  As it turns out, this breaks due to this bizarre bug.  The variables work _just fine_ in an jinja template.  The variables also work _just fine_ if copy/pasted directly under with_items.  Only if they are loaded from a vars_file do they break.

**Comment by mpdehaan** [comment]
So if you'd like to help debug, it might be useful to print out the variable and see what type it was.

debug: var=broken_list

Also per contributing.md please share what version of Ansible you are using.

Thanks!

**Comment by pol** [comment]
Yeah, I did do debug messages (as you can see in the test playbook).  All of them look fine in the debug output (they look like lists of hashes). 

If you modify the error output, it states that the with_items value is of type Unicode.  But that's not true of the others!  A strange thing to be sure.

**Comment by mpdehaan** [comment]
So interestingly, what you have shared shows that this is the problem.

```
"working_list2": "{{ working_list2 }}"
```

The value of working_list2 is actually not a list.

From all of the output above it looks like none of these actually work because the variables aren't being sucked in (i.e. probably a playbook error).

```
ok: [foo.domain.com] => {
    "working_list1": "{{ working_list1 }}"
}
```

This doesn't look like it's working at all, in other words.   

So seems like this is not a bug, but that the variables weren't in scope.

**Comment by pol** [comment]
I think that I made a mistake migrating my actual bug to the synthetic test.  I shall re-create the test with less noise. :)

**Comment by pol** [comment]
Yeah, so, I had quotes messing things up in my first example.  Here's a better one:

vars.yml

```
---
broken_list:
  - str1: I am the first string.
    str2: non-sublist.str.works.(things)
    sublist:
      - string(breaks)
      - string.breaks()
  - str1: I am a string!
    str2: client2
    sublist:
       - (parens) at the beginning work

working_list:
  - str1: I am the first string.
    str2: non-sublist.str.works.(things)
    sublist:
      - string.()with.inner.parens.is.fine
      - string_is-a -string()
  - str1: I am a string!
    str2: client2
    sublist:
      - foo
      - bat
```

playbook.yml

```
---
- hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: debug
      debug: var=working_list

    - name: this sublist works in with_items!
      debug: var={{item}}
      with_items: working_list

    - name: debug
      debug: var=broken_list

    - name: this sublist breaks in with_items!
      debug: var={{item}}
      with_items: broken_list
```

output of `$ ansible-playbook playbook.yml -i 'foo.com, '`

```
PLAY [all] ********************************************************************

TASK: [debug] *****************************************************************
ok: [foo.com] => {
    "working_list": [
        {
            "str1": "I am the first string.",
            "str2": "non-sublist.str.works.(things)",
            "sublist": [
                "string.()with.inner.parens.is.fine",
                "string_is-a -string()"
            ]
        },
        {
            "str1": "I am a string!",
            "str2": "client2",
            "sublist": [
                "foo",
                "bat"
            ]
        }
    ]
}

TASK: [this sublist works in with_items!] *************************************
ok: [foo.com] => (item={'str2': 'non-sublist.str.works.(things)', 'str1': 'I am the first string.', 'sublist': ['string.()with.inner.parens.is.fine', 'string_is-a -string()']}) => {
    "item": {
        "str1": "I am the first string.",
        "str2": "non-sublist.str.works.(things)",
        "sublist": [
            "string.()with.inner.parens.is.fine",
            "string_is-a -string()"
        ]
    },
    "{str2:": "{{ {str2: }}"
}
ok: [foo.com] => (item={'str2': 'client2', 'str1': 'I am a string!', 'sublist': ['foo', 'bat']}) => {
    "item": {
        "str1": "I am a string!",
        "str2": "client2",
        "sublist": [
            "foo",
            "bat"
        ]
    },
    "{str2:": "{{ {str2: }}"
}

TASK: [debug] *****************************************************************
ok: [foo.com] => {
    "broken_list": "[{'str2': 'non-sublist.str.works.(things)', 'str1': 'I am the first string.', 'sublist': ['string(breaks)', 'string.breaks()']}, {'str2': 'client2', 'str1': 'I am a string!', 'sublist': ['(parens) at the beginning work']}]"
}

TASK: [this sublist breaks in with_items!] ************************************
fatal: [foo.com] => with_items expects a list

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/pol/playbook.retry

foo.com                    : ok=3    changed=0    unreachable=1    failed=0
```

Sorry about my other example, it was (as you said) not actually useful.  But this one is!
