### ISSUE TITLE
Allow mysql_db module to create/drop multiple databases

### ISSUE THREAD

**Issue by pratikgadiya12** [ansible/ansible#58370]
##### SUMMARY
mysql_db module should be able to create/drop multiple databases

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/database/mysql/mysql_db.py

##### ADDITIONAL INFORMATION
Why and what it would solve:
Avoids repetitive tasks to create/delete more than one databases (similar to https://github.com/ansible/ansible/issues/56059)

- Create (Multiple databases)
```yaml
  tasks:
  - name: Create multiple databases (provided in comma separated form)
    mysql_db:
      name: bobdata, bobthebuilder
      state: present
  - name: Create multiple databases (provided in list form)
    mysql_db:
      name:
        - bobdata
        - bobthebuilder
      state: present
```

- Delete/Drop (Multiple databases)
```yaml
  - name: Delete/drop multiple databases (provided in comma separated form)
    mysql_db:
      name: bobdata, bobthebuilder
      state: absent
  - name: Delete/drop multiple databases (provided in list form)
    mysql_db:
      name:
        - bobdata
        - bobthebuilder
      state: absent
```

Credits for the idea to @Andersson007 from comment https://github.com/ansible/ansible/pull/56721#issuecomment-505128646
