### ISSUE TITLE
group_names var ordered by name instead of level (2)

### ISSUE THREAD

**Issue by sgandon** [ansible/ansible#58380]
##### SUMMARY
I am sorry to create a new issue for this because there is already one here
https://github.com/ansible/ansible/issues/12730
And I don't understand why this has been closed cause the solution mentionned like using `group_names | sort` does not solve the pb at all, cause `sort` does an alphabetical order sort which is already the case and does not do the "level" sorting expected in the feature request.

This would be great cause we are having multiple groups level for a given host and we need to get the group name 2 level up of the host, and I can't find any way to do so.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
main engine ?

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@sgandon: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
if by 'level' you mean child depth, this is not a simple thing for a group, cause it can have many levels depending on how you follow the parent/child relationships.

```ini
[group1]
host1

[group2]
host2

[group3]
host3

[group4]
host4

[group1:children]
group4

[group2:children]
group3

[group3:children]
group4
```

**Comment by sgandon** [comment]
indeed I mean child depth
we have a hosts.yaml following this structure
```
all:
  children:
    team1:                   <- this is unique
      children:
        team1-stack1:              <- this is unique accross all teams
          children:
            chart1:
              hosts:
                chart1
            chart2:
              hosts:
                chart2
        team1-stack2:             <- this is unique accross all teams
          children:
            chart1:
              hosts:
                chart1
            chart3:
              hosts:
                chart2
```
So when you launch ansible with `-l team1-stack1` it would be great to be able to get the team associated with the stack. I know this is particular case where we enfoce stack name uniqness and we have a way around it by parsing the stack name and extract the team name.

**Comment by bcoca** [comment]
they are unique in YOUR case, that is not guaranteed as the following is also valid:
```yaml
all:
  children:
    team1:                   <- this is unique
      children:
        team1-stack1:              <- this is unique accross all teams
          children:
            chart1:
              hosts:
                chart1
            chart2:
              hosts:
                chart2
        team1-stack2:             <- this is unique accross all teams
          children:
            chart1:
              hosts:
                chart1
            chart3:
              hosts:
                chart2
chart1:
  children:
    chart3
```
