### ISSUE TITLE
can not update chart using helm module

### ISSUE THREAD

**Issue by seven2221** [ansible/ansible#58391]
##### SUMMARY
The "helm" module does not update the chart.  There are some problems with the namespace type.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
helm

##### ANSIBLE VERSION

```paste below
ansible 2.7.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core) 

##### STEPS TO REPRODUCE
There are 2 namespaces with kafka-manager v1.1.1.
```
kafka-manager-default         	1       	Mon Jun 24 13:31:45 2019	DEPLOYED	kafka-manager-1.1.1         	1.3.3.22      	default      
kafka-manager-temp            	1       	Tue Jun 25 20:47:43 2019	DEPLOYED	kafka-manager-1.1.1         	              	temp 
```
 When I try to update them to version 2.1.5, , I get a TypeError with a namespace like this:
```
TASK [k8s_configuration : Install helm chart | kafka-manager] *****************************************************************************************************************************
fatal: [k8s_master_hostname]: FAILED! => {"changed": false, "module_stderr": "Shared connection to t2ru-ds-test-k8s-master-01 closed.\r\n", "module_stdout": "2019-06-25 21:59:32,862 - ChartBuilder - INFO - Cloning https://kubernetes-charts.storage.googleapis.com/ for release kafka-manager\r\nTraceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1561489171.12-150404067009023/AnsiballZ_helm.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1561489171.12-150404067009023/AnsiballZ_helm.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1561489171.12-150404067009023/AnsiballZ_helm.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_helm_payload_c38BWa/__main__.py\", line 184, in <module>\r\n  File \"/tmp/ansible_helm_payload_c38BWa/__main__.py\", line 172, in main\r\n  File \"/tmp/ansible_helm_payload_c38BWa/__main__.py\", line 110, in install\r\n  File \"/usr/lib/python2.7/site-packages/pyhelm/tiller.py\", line 172, in update_release\r\n    description=description)\r\nTypeError: 'temp' has type str, but expected one of: int, long, bool\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

ansible task:
```yaml
- name: Install helm chart | kafka-manager
  helm:
    host: "{{ k8s_tiller_host }}"
    chart: "{{ k8s_chart_kafka_manager }}"
    state: present
    name: "{{ k8s_chart_kafka_manager.name }}-{{ k8s_namespace }}"
    namespace: "{{ k8s_namespace }}"
    values: "{{ k8s_chart_kafka_manager_values }}"
  environment:
    HTTP_PROXY: "{{ proxy_env_prod.http_proxy }}"
    HTTPS_PROXY: "{{ proxy_env_prod.https_proxy }}"
    NO_PROXY: "{{ k8s_tiller_host }}"
  tags: ['never','kafka_manager']
```

```yaml
k8s_chart_kafka_manager:
  name: kafka-manager
  version: 2.1.5
  source:
    type: repo
    location: https://kubernetes-charts.storage.googleapis.com
k8s_chart_kafka_manager_values:
  zkHosts: "reactive-sandbox-{{ k8s_namespace }}-reactive-sandbox-zookeeper"
  ingress:
    enabled: yes
    hosts:
        - "kafka-manager-{{ k8s_namespace }}"
```

##### ACTUAL RESULTS

```paste below
    "module_stdout": "2019-06-24 13:32:34,199 - ChartBuilder - INFO - Cloning https://kubernetes-charts.storage.googleapis.com/ for release kafka-manager
Traceback (most recent call last):
  File \"/home/ansible/.ansible/tmp/ansible-tmp-1561372353.28-223560552419948/AnsiballZ_helm.py\", line 113, in <module>
    _ansiballz_main()
  File \"/home/ansible/.ansible/tmp/ansible-tmp-1561372353.28-223560552419948/AnsiballZ_helm.py\", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/ansible/.ansible/tmp/ansible-tmp-1561372353.28-223560552419948/AnsiballZ_helm.py\", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File \"/tmp/ansible_helm_payload_AyHNJ_/__main__.py\", line 184, in <module>
  File \"/tmp/ansible_helm_payload_AyHNJ_/__main__.py\", line 172, in main
  File \"/tmp/ansible_helm_payload_AyHNJ_/__main__.py\", line 110, in install
  File \"/usr/lib/python2.7/site-packages/pyhelm/tiller.py\", line 171, in update_release
    description=description)
TypeError: 'default' has type str, but expected one of: int, long, bool
```
