### ISSUE TITLE
Add OAuth and Multi-Record Query for SNOW

### ISSUE THREAD

**Issue by n3pjk** [ansible/ansible#58402]
##### SUMMARY
Service Now (SNOW) modules currently do not support OAuth, even though
it is provided in pysnow. This functionality is added and tested in
both 2.7 and 2.8.

snow_record only performs create, update and delete operations on a
single record. When processing ticket queues, it is necessary to have a
module that can retrieve multiple records. snow_record_find does this,
and has also been modified to support OAuth. I have obtained permission
from the original author, Tim Rightnour, to include this module with the
tested upgrade. Email can be furnished, if necessary.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- snow_record.py modified
- snow_record_find.py added

##### ADDITIONAL INFORMATION
Authenticating to SNOW with sso/ADFS will not work, and requires an OAuth user that has no ties to ADFS. pysnow supports OAuth, but snow_record did not take this functionality into account.

snow_record also only supports creation, update or deletion of single records. A new module is needed that can retrieve multiple records based on a query.  The author of snow_record, Tim Rightnour, created another module, snow_record_find, to do just this; however, it too does not support OAuth, and thus also needed to be modified.

I will be submitting a pull request shortly to address these issues.

```yaml
- name: Grab a user record using OAuth
  snow_record:
    username: ansible_test
    password: my_password
    client_id: "1234567890abcdef1234567890abcdef"
    client_secret: "Password1!"
    instance: dev99999
    state: present
    number: 62826bf03710200044e0bfc8bcbe5df1
    table: sys_user
    lookup_field: sys_id

- name: Using OAuth, search for incident assigned to group, return specific fields
  snow_record_find:
    username: ansible_test
    password: my_password
    client_id: "1234567890abcdef1234567890abcdef"
    client_secret: "Password1!"
    instance: dev99999
    table: incident
    query:
      assignment_group: d625dccec0a8016700a222a0f7900d06
    return_fields:
      - number
      - opened_at
```
