### ISSUE TITLE
How to merge playbook/tasks with OS-specific variables?

### ISSUE THREAD

**Issue by SemajKP** [ansible/ansible#58401]
##### SUMMARY

Trying to merge 4 tasks with playbook. Get FAILURE when I run the playbook.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Debian-6-certificates.yaml

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kjames/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
"No putput"

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7 (64-bit))
     - NAME="Red Hat Enterprise Linux Server"
     - VERSION="7.4 (Maipo)"
     - ID="rhel"
     - ID_LIKE="fedora"
     - VARIANT="Server"
     - VARIANT_ID="server"
     - VERSION_ID="7.4"
     - PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"

(SUSE Linux Enterprise 12 (64-bit))
     - NAME="SLES"
     - VERSION="12-SP3"
     - VERSION_ID="12.3"
     - PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
     - ID="sles"
     - ANSI_COLOR="0;32"
     - CPE_NAME="cpe:/o:suse:sles:12:sp3"

(Ubuntu Linux (64-bit))
     - NAME="Ubuntu"
     - VERSION="12.04.5 LTS, Precise Pangolin"
     - ID=ubuntu
     - ID_LIKE=debian
     - PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
     - VERSION_ID="12.04"

(Other 3.x or later Linux (64-bit))
     - PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
     - NAME="Debian GNU/Linux"
     - VERSION_ID="8"
     - VERSION="8 (jessie)"
     - ID=debian

##### STEPS TO REPRODUCE

```yaml
---
- hosts: buildservers
   remote_user: root

   tasks:
   - name: Detect OS and run appropriate tasks
      include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-certificates.yaml"
   - name: Copy the proxy CA to /etc/ssl/certs/
      copy:
          src: library/{{ item }}.crt
          dest: /usr/local/share/ca-certificates/{{ item }}.crt
      with_items:
      -"{{ proxy_ca_certificate }}"
   - name: Update system CA certificates
      command: update-ca-certificates --fresh

```

##### EXPECTED RESULTS

I expect OS detection and the CA proxy to be copied to the path.

##### ACTUAL RESULTS

Actual Output:
TASK [Detect OS and run appropriate tasks] ******************************************************************************************************
fatal: [wblrh7ex6402]: FAILED! => {"reason": "Could not find or access '/home/kjames/ds9/RedHat-7-certificates.yaml' on the Ansible Controller."}
fatal: [wbls12ex6401]: FAILED! => {"reason": "Could not find or access '/home/kjames/ds9/SLES-12-certificates.yaml' on the Ansible Controller."}
fatal: [wblu12ex6401]: FAILED! => {"reason": "Could not find or access '/home/kjames/ds9/Ubuntu-12-certificates.yaml' on the Ansible Controller."}
fatal: [wbldeb8ex6402]: FAILED! => {"reason": "Could not find or access '/home/kjames/ds9/Debian-8-certificates.yaml' on the Ansible Controller."}

PLAY RECAP ******************************************************************************************************
wbldeb8ex6402 : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
wblrh7ex6402 : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
wbls12ex6401 : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
wblu12ex6401 : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0

```paste below

```
