### ISSUE TITLE
Snapcraft: Add 'snap connect'

### ISSUE THREAD

**Issue by benyanke** [ansible/ansible#58403]
##### SUMMARY
Because of the containerization of snaps, they often require explicit connection to other services, using the command `snap connect [app]:[plug]`. Right now, this can only be done with the `shell` cmd.

##### ISSUE TYPE
I would like to propose a snap module addition to support the `snap connect` commands. For the sake of full feature set, it would also be preferable to return currently connected snaps in a return value.

##### COMPONENT NAME

snap.py

##### ADDITIONAL INFORMATION

Currently, I run commands like this:

```yaml
    - name: Snap Packages - Standard Installs
      become: yes
      become_method: sudo
      snap:
        name:
          - nextcloud-client
          - remmina

    - name: Snap Packages - Setup Plugs
      become: yes
      become_method: sudo
      changed_when: false
      shell: 'snap connect {{ item.app }}:{{ item.plug }}'
      with_items:
        - plug: password-manager-service
          app: nextcloud-client
        - plug: avahi-observe
          app: remmina
```

Ideally, it should be configurable with something similar to:

```yaml

    - name: Snap Packages - Standard Installs
      become: yes
      become_method: sudo
      snap:
        name:
          - nextcloud-client
          - remmina
        connect:
          - plug: password-manager-service
            app: nextcloud-client
          - plug: avahi-observe
            app: remmina

```
