### ISSUE TITLE
Got "host is not a legal parameter in an Ansible task or handler" with ansible 1.4.4

### ISSUE THREAD

**Issue by ringe** [ansible/ansible#5842]
See bennojoy/mysql/issues/2.

The problem is that the Best Practices doesn't work:
http://docs.ansible.com/playbooks_best_practices.html#directory-layout

My site.yml looks like this:

```

---
# file: site.yml
- hosts: peers
  roles:
  - common
  - peer
  sudo: true
  vars_files:
    - passwords.yml
```

**Comment by bcoca** [comment]
you need to indent your roles

**Comment by mpdehaan** [comment]
Yep, this is more of a support question, please stop by the mailing list if you'd like more help...

**Comment by ringe** [comment]
Thank you, but you are mistaken. Here's the same, indented and failing:

```
---
# file: site.yml
- hosts: peers
  roles:
    - common
    - peer
  sudo: true
  vars_files:
    - passwords.yml
```

Then:

```
$ ansible-playbook site.yml 
ERROR: hosts is not a legal parameter in an Ansible task or handler
```
