### ISSUE TITLE
Argument env should be dict type note list like in examle

### ISSUE THREAD

**Issue by augustgerro** [ansible/ansible#58452]
##### SUMMARY

Argument env should be dict type note list like in examle.  

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

Module docker_container documentation
##### ANSIBLE VERSION

```paste below
2.8
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/user/.ansible.cfg) = ['/Users/user/ans/hosts']
DEFAULT_LOCAL_TMP(/Users/user/.ansible.cfg) = /Users/user/ans/tmp/ansible-local-32291a4w9np84
DEFAULT_LOG_PATH(/Users/user/.ansible.cfg) = /Users/user/ans/log
DEFAULT_PRIVATE_KEY_FILE(/Users/user/.ansible.cfg) = /Users/user/.ssh/id_rsa
DEFAULT_REMOTE_USER(/Users/user/.ansible.cfg) = root
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(/Users/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS 10.14.4
Ubuntu 18.04

##### ADDITIONAL INFORMATION

https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
instead
```yaml
    env:
      - arg1: "true"
      - arg2: "whatever"
```
should be 
```yaml
    env:
       arg1: "true"
       arg2: "whatever"
```
