### ISSUE TITLE
routeros_command wait_for contains fails when the string contains "yes"

### ISSUE THREAD

**Issue by tbaschak** [ansible/ansible#58473]
##### SUMMARY

When running a command with `routeros_command` and using `wait_for: "result[0] contains yes"` will fail, but `wait_for: result[0] contains ye` works as expected.

Similarly, the same thing happens if you do "wait_for: result[0] contains true"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

routeros_command or wait_for

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /home/gobcn.local/tbaschak/dev/bcn/ansible_testing/ansible.cfg
  configured module search path = ['/home/gobcn.local/tbaschak/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gobcn.local/tbaschak/dev/bcn/ansible_testing/venv/lib/python3.6/site-packages/ansible
  executable location = /home/gobcn.local/tbaschak/dev/bcn/ansible_testing/venv/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/gobcn.local/tbaschak/dev/bcn/ansible_testing/ansible.cfg) = ['/home/gobcn.local/tbaschak/dev/bcn/ansible_testing/hosts']
DEFAULT_LOG_PATH(/home/gobcn.local/tbaschak/dev/bcn/ansible_testing/ansible.cfg) = /home/gobcn.local/tbaschak/dev/bcn/ansible_testing/ansible.log
DEFAULT_TIMEOUT(/home/gobcn.local/tbaschak/dev/bcn/ansible_testing/ansible.cfg) = 5
HOST_KEY_CHECKING(/home/gobcn.local/tbaschak/dev/bcn/ansible_testing/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7
Debian Buster
Mikrotik RouterOS 6.40.8 & 6.43.4

##### STEPS TO REPRODUCE

```yaml
---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: no
  hosts: testap
  tasks:
  - name: Validate NTP Settings
    routeros_command:
      commands:
        - /system ntp client print
      wait_for:
        - "result[0] contains yes"
```

##### EXPECTED RESULTS

```yaml
---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: no
  hosts: testap
  tasks:
  - name: Validate NTP Settings
    routeros_command:
      commands:
        - /system ntp client print
      wait_for:
        - result[0] contains ye
```
This playbook works, adding an s to the end of ye makes it no longer work.

##### ACTUAL RESULTS

The string yes was not matched if it was contained fully within the contains clause of the wait_for. The same thing happens with tru/true.

```paste below

```
