### ISSUE TITLE
ansible modules: atomic_container, atomic_image not able to exec possible atomic commands

### ISSUE THREAD

**Issue by Elyytscha** [ansible/ansible#58496]
##### SUMMARY
not able to run a command like
`atomic install --name freeipa freeipa/freeipa-server --hostname=freeipa71.test.lx.domain.com ip-address 10.20.203.87 publish ipa-server-install --setup-dns --forwarder=10.10.30.1 --admin-password=adminadmin --ds-password=adminadmin --realm=LX.DOMAIN.COM --domain=lx.domain.com --auto-reverse --unattended`
with the ansible modules for atomic

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
atomic_container, atomic_image, atomic_host

##### ANSIBLE VERSION

```paste below
ansible 2.7.8
  config file = /home/erami/Devel/docker/docker-freeipa/ansible.cfg
  configured module search path = ['/home/erami/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
all

##### STEPS TO REPRODUCE
try to form a ansible task which runs this atomic command:
`atomic install --name freeipa freeipa/freeipa-server --hostname=freeipa71.test.lx.domain.com ip-address 10.20.203.87 publish ipa-server-install --setup-dns --forwarder=10.10.30.1 --admin-password=adminadmin --ds-password=adminadmin --realm=LX.DOMAIN.COM --domain=lx.domain.com --auto-reverse --unattended`

```yaml
    - name: Install freeipa atomic container
      atomic_container:
        name: freeipa
        image: docker.io/freeipa/freeipa-server
        backend: ostree
        state: latest
        mode: system
        values:
            - hostname=freeipa71.lx.oeamtc.at
            - ip-address=10.203.0.12
            - publish
            - ipa-server-install
            - --setup-dns
            - --forwarder=10.10.30.1 
            - --admin-password=adminadmin 
            - --ds-password=adminadmin 
            - --realm=LX.OEAMTC.AT 
            - --domain=lx.oeamtc.at 
            - --auto-reverse 
            - --unattended
```

##### EXPECTED RESULTS
install of freeipa container

##### ACTUAL RESULTS

```paste below
fatal: [freeipa71.lx.domain.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backend": "ostree",
            "image": "docker.io/freeipa/freeipa-server",
            "mode": "system",
            "name": "freeipa",
            "rootfs": null,
            "state": "latest",
            "values": [
                "hostname=freeipa71.lx.domain.com",
                "ip-address=10.203.0.12",
                "publish",
                "ipa-server-install",
                "--setup-dns",
                "--forwarder=10.10.30.1",
                "--admin-password=adminadmin",
                "--ds-password=adminadmin",
                "--realm=LX.DOMAIN.COM",
                "--domain=lx.domain.com",
                "--auto-reverse",
                "--unattended"
            ]
        }
    },
    "msg": "Invalid value 'publish'.  Expected form NAME=VALUE\n",
    "rc": 1
}

PLAY RECAP ****************************************************************************************************************************************************************************************************************
freeipa71.lx.domain.com     : ok=1    changed=0    unreachable=0    failed=1 
```
