### ISSUE TITLE
cron does not allow to remove a cron_file without user anymore

### ISSUE THREAD

**Issue by duck-rh** [ansible/ansible#58493]
##### SUMMARY
Removing a cron_file is no longer possible since 2.8 without specifying the user parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION
```paste below
ansible 2.8.1
  config file = /home/duck/OSPO/community-cage-infra-ansible/ansible.cfg
  configured module search path = ['/home/duck/OSPO/community-cage-infra-ansible/library']
  ansible python module location = /home/duck/.local/lib/python3.7/site-packages/ansible
  executable location = /home/duck/.local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_PIPELINING(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m
CACHE_PLUGIN(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ./facts_cache
CACHE_PLUGIN_TIMEOUT(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = 86400
DEFAULT_ACTION_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/actio
DEFAULT_CALLBACK_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/cal
DEFAULT_CONNECTION_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/c
DEFAULT_FILTER_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/filte
DEFAULT_FORKS(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/hosts.yml']
DEFAULT_LOOKUP_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/looku
DEFAULT_MANAGED_STR(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = Ansible managed
DEFAULT_MODULE_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/library']
DEFAULT_ROLES_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/str
DEFAULT_TIMEOUT(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = 40
DEFAULT_VARS_PLUGIN_PATH(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = ['/home/duck/OSPO/community-cage-infra-ansible/plugins/vars']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/duck/.ansible_vault/cage.txt
ERROR_ON_MISSING_HANDLER(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = True
PARAMIKO_HOST_KEY_AUTO_ADD(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/home/duck/OSPO/community-cage-infra-ansible/ansible.cfg) = 1800
```

##### OS / ENVIRONMENT
Ansible runs on Debian unstable and the node is using Debian Stretch.

##### STEPS TO REPRODUCE
The following worked before 2.8 and now fails.

```yaml
- name: remove useless backup cron
  cron:
    cron_file: backup-postgresql-databases
    state: absent
```

##### EXPECTED RESULTS

There is no reason to request the user when deleting the contab file thus it should continue to work as before 2.8.

I would dare to say a test is missing here.

##### ACTUAL RESULTS

```paste below
fatal: [catton.osci.io]: FAILED! => {"changed": false, "msg": "missing parameter(s) required by 'cron_file': user"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/cron.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/cron.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @EvanK @dirtyharrycallahan @dsummersl @lberruti @rhaido
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Confirmed as @duck-rh comments. In 2.7.x user is not required. Or the documentation needs to be changed or the code amended. I can help with both if you require it guys.

**Comment by imjoseangel** [comment]
@duck-rh, just confirmed that the documentation is correct:

>   **cron_file:**
    description:
      - If specified, uses this file instead of an individual user's crontab.
      - If this is a relative path, it is interpreted with respect to I(/etc/cron.d).
      - If it is absolute, it will typically be I(/etc/crontab).
      - Many linux distros expect (and some require) the filename portion to consist solely
        of upper- and lower-case letters, digits, underscores, and hyphens.
      - **To use the cron_file parameter you must specify the user as well.**

From my point of view this is not a bug and should be closed

**Comment by pilou-** [comment]
This a useless change introduced by https://github.com/ansible/ansible/commit/cd9471ef17c985006c7d77687030890003cf395d#diff-d62002ec9c674dc53b0782ca1794023e.

> To use the C(cron_file) parameter you must specify the C(user) as well.

is incorrect: `user` is only required if `cron_file` is used and `state` is `present`.

**Comment by imjoseangel** [comment]
Fully agree, using **user** doesn't make sense at deletion. Look at this example:

```yaml
    - name: Creates a cron file under /etc/cron.d
      cron:
        name: yum autoupdate
        weekday: 2
        minute: 0
        hour: 12
        user: root
        job: "YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate"
        cron_file: backup-postgresql-databases

    - name: Creates another user
      cron:
        name: yum autoupdate2
        weekday: 3
        minute: 0
        hour: 12
        user: ansible
        job: "YUMINTERACTIVE=1 /usr/sbin/yum-autoupdate"
        cron_file: backup-postgresql-databases

    - name: remove useless backup cron
      cron:
        name: yum autoupdate
        cron_file: backup-postgresql-databases
        state: absent
        user: ansible
```
This creates:

```sh
#Ansible: yum autoupdate
0 12 * * 2 root YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate
#Ansible: yum autoupdate2
0 12 * * 3 ansible YUMINTERACTIVE=1 /usr/sbin/yum-autoupdate
```
and deletes:

```sh
0 12 * * 2 root YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate
```

although the specified user is ansible. So the **name** is the key when **absent**, not the user. I would recommend removing the :

```python
        required_by=dict(
            cron_file=('user'),
        ),
```
 as specified by @pilou-
