### ISSUE TITLE
os_server is not idempotent when using security groups per ports

### ISSUE THREAD

**Issue by jeanlouisferey** [ansible/ansible#58495]
##### SUMMARY
os_server is not idempotent when the server has two network interfaces with security groups attached to ports. os_server creates well the server, but on the second time os_server deletes security groups on ports and changes its to default security group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_server

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /media/sf_Dev/os_server_test/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/.virtualenvs/ansible-2.8/local/lib/python2.7/site-packages/ansible
  executable location = /home/admin/.virtualenvs/ansible-2.8/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(/media/sf_Dev/os_server_test/ansible.cfg) = True
ANSIBLE_PIPELINING(/media/sf_Dev/os_server_test/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/media/sf_Dev/os_server_test/ansible.cfg) = -F ssh-config
DEFAULT_CALLBACK_WHITELIST(/media/sf_Dev/os_server_test/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/media/sf_Dev/os_server_test/ansible.cfg) = 10
DEFAULT_GATHERING(/media/sf_Dev/os_server_test/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/media/sf_Dev/os_server_test/ansible.cfg) = merge
DEFAULT_MANAGED_STR(/media/sf_Dev/os_server_test/ansible.cfg) = Please  do not change this file directly since it is managed by Ansible and will be overwritten
DEFAULT_ROLES_PATH(/media/sf_Dev/os_server_test/ansible.cfg) = [u'/media/sf_Dev/lemonldap-roles']
DEFAULT_STDOUT_CALLBACK(/media/sf_Dev/os_server_test/ansible.cfg) = skippy
DEPRECATION_WARNINGS(/media/sf_Dev/os_server_test/ansible.cfg) = False
HOST_KEY_CHECKING(/media/sf_Dev/os_server_test/ansible.cfg) = False
RETRY_FILES_ENABLED(/media/sf_Dev/os_server_test/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04
openstacksdk version 0.31.1

##### STEPS TO REPRODUCE

1- Create all resources with the playbook below

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: create security groups
      os_security_groups:
        state: present
        cloud: mycloud
        name: INLLD-SG-INTERNAL

    - name: create security groups
      os_security_groups:
        state: present
        cloud: mycloud
        name: INLLD-SG-REDIS

    - name: create security group rules
      os_security_group_rule:
        state: present
        cloud: mycloud
        security_group: INLLD-SG-INTERNAL
        direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: create security group rules
      os_security_group_rule:
        state: present
        cloud: mycloud
        security_group: INLLD-SG-REDIS
        direction: ingress
        protocol: tcp
        port_range_min: 6379
        port_range_max: 6379
        remote_ip_prefix: 0.0.0.0/0

    - name: create ports
      os_port:
        state: present
        cloud: mycloud
        name: INLLD-SERVER-REDIS-04-ETH0
        security_groups:
          - INLLD-SG-INTERNAL

    - name: create ports
      os_port:
        state: present
        cloud: mycloud
        name: INLLD-SERVER-REDIS-04-ETH1
        security_groups:
          - INLLD-SG-REDIS

    - name: create server
      os_server:
        state: present
        cloud: mycloud
        name: INLLD-SERVER-REDIS-04
        image: Ubuntu-18.04-v1.0
        flavor: m1.4cpu.8gb.64disk
        key_name: INLLD-KEY-ANSIBLE
        state: present
        nics:
          - INLLD-SERVER-REDIS-04-ETH0
          - INLLD-SERVER-REDIS-04-ETH1
```
2 - Restart the same playbook

##### EXPECTED RESULTS

Normally, the second time, the playbook should do nothing because the server is already created. In particular, the security groups attached to the ports should not have changed

##### ACTUAL RESULTS

1 - Create all resources with the playbook below

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: create security groups
      os_security_groups:
        state: present
        cloud: mycloud
        name: INLLD-SG-INTERNAL

    - name: create security groups
      os_security_groups:
        state: present
        cloud: mycloud
        name: INLLD-SG-REDIS

    - name: create security group rules
      os_security_group_rule:
        state: present
        cloud: mycloud
        security_group: INLLD-SG-INTERNAL
        direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: create security group rules
      os_security_group_rule:
        state: present
        cloud: mycloud
        security_group: INLLD-SG-REDIS
        direction: ingress
        protocol: tcp
        port_range_min: 6379
        port_range_max: 6379
        remote_ip_prefix: 0.0.0.0/0

    - name: create ports
      os_port:
        state: present
        cloud: mycloud
        name: INLLD-SERVER-REDIS-04-ETH0
        security_groups:
          - INLLD-SG-INTERNAL

    - name: create ports
      os_port:
        state: present
        cloud: mycloud
        name: INLLD-SERVER-REDIS-04-ETH1
        security_groups:
          - INLLD-SG-REDIS

    - name: create server
      os_server:
        state: present
        cloud: mycloud
        name: INLLD-SERVER-REDIS-04
        image: Ubuntu-18.04-v1.0
        flavor: m1.4cpu.8gb.64disk
        key_name: INLLD-KEY-ANSIBLE
        state: present
        nics:
          - INLLD-SERVER-REDIS-04-ETH0
          - INLLD-SERVER-REDIS-04-ETH1
```
2 - Verify security groups:
```shell
(openstack) server show INLLD-SERVER-REDIS-04 -c security_groups
+-----------------+--------------------------+
| Field           | Value                    |
+-----------------+--------------------------+
| security_groups | name='INLLD-SG-INTERNAL' |
|                 | name='INLLD-SG-REDIS'    |
+-----------------+--------------------------+

```
3 - Restart the same playbook

4 - Verify the security groups:
```shell
(openstack) server show INLLD-SERVER-REDIS-04 -c security_groups
+-----------------+----------------+
| Field           | Value          |
+-----------------+----------------+
| security_groups | name='default' |
|                 | name='default' |
+-----------------+----------------+
```
The security groups has been changed to default.
