### ISSUE TITLE
LOOKUP file should behave like module COPY when used inside a role

### ISSUE THREAD

**Issue by amiorin** [ansible/ansible#5849]
`{{ lookup('file', 'apt.gpg') }}` should search for `apt.gpg` inside `role/<name>/files` and then in the root project.

I would like to use `lookup` inside `meta/main.yml`, because I would like to make the content of the file a parameter for encapsulated role.

**Comment by mpdehaan** [comment]
Hmm, I thought it already did that.  (of course, roles/<name>/files).

What version of Ansible are you using?

We can check.

In any case, we don't want to break existing behavior, so if it doesn't, we'll just have it look there first.

**Comment by amiorin** [comment]
`ansible 1.4.4`
I have to write

``` yml
---
dependencies:
  - role: daemontools
    service: zookeeper
    run: "{{ lookup('file', 'roles/zookeeper/files/run') }}"
```

and I think it would be better

``` yml
---
dependencies:
  - role: daemontools
    service: zookeeper
    run: "{{ lookup('file', 'run') }}"
```

like module `copy` and `template`

The error is:
`ERROR: /Users/amiorin/Code/nugg.ad/spark/run does not exist`
