### ISSUE TITLE
False positive "recursive loop detection" inside a dictionary.

### ISSUE THREAD

**Issue by amiorin** [ansible/ansible#5851]
`hadoop.archive` should be allowed to reference `hadoop.namenode`.

Inside `group_vars/all`

``` yaml
hadoop:
  namenode: '{{groups.namenode_server.0}}'
  archive: 'hdfs://{{hadoop.namenode}}/hadoop.tar.gz'
```

Inside the template file

``` jinja
  <property>
    <name>mapred.mesos.executor.uri</name>
    <value>{{hadoop.archive}}</value>
  </property>
```

And the error is 

```
fatal: [ip-192-168-1-11.eu-west-1.compute.internal] => {'msg': 'recursive loop detected in template string: {{groups.namenode_server.0}}', 'failed': True}
```
