### ISSUE TITLE
win_find module not returning deduplicated files

### ISSUE THREAD

**Issue by MarkJB** [ansible/ansible#58511]
##### SUMMARY
Using the win_find module against a Windows share it is not returning some files. In this case .exe files.

The .exe files are deduplicated and looking at their properties in Windows explorer, they appear as something like this:

'Size: 100MB'
'Size on disk: 0 bytes'.

win_find is successfully returning other (non deduplicated) files from the same directory and it is showing the correct number of files in the directory (the number of files including the deduplicated .exe files).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_find.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/playbooks/ansible-venv/lib/python2.7/site-packages/ansible
  executable location = /root/playbooks/ansible-venv/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ansible Server: RHEL7
Target Host: Win20126
Share Server: Win2016

##### STEPS TO REPRODUCE

```yaml
   - name: Get list of exes from share with deduplication
     debugger: always
     win_find:
      paths: \\server\share\
      patterns: '*.exe' # When uncommented this returns no files from the share. 
      # When commented it returns everything but the deduplicated files (exes in this case)
      # The debug output then shows the list of files found plus; "examined": 29, "matched": 13
      # Still missing the exe files from the output...
      user_name: user
      user_password: pass
     register: list_of_exes
     become: true
     become_method: runas
     vars:
      ansible_become_user: '{{ ansible_user }}'
      ansible_become_pass: '{{ ansible_password }}'

   - debug:
      var: list_of_exes
```

##### EXPECTED RESULTS

Would expect the results to include the deduplicated files
```
TASK [debug] ********************************************************************************************************
ok: [169.254.0.1] => {
    "list_of_exes": {
        "changed": false,
        "examined": 29,
        "failed": false,
        "files": [...],
        "matched": 13
    }
}
```

##### ACTUAL RESULTS

Playbook executes ok but does not return the deduplicated files.

```paste below
TASK [debug] ********************************************************************************************************
ok: [169.254.0.1] => {
    "list_of_exes": {
        "changed": false,
        "examined": 29,
        "failed": false,
        "files": [],
        "matched": 0
    }
}
```
