### ISSUE TITLE
iosxr_config: path specified in src not found using retry loops

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible#58514]
##### SUMMARY
We are trying to mitigate an issue on zuul.ansible.com with cisco iosxr and network_cli sockets.  We randomly see cases, where the paramiko socket is closed, and working to handle that via ansible playbooks.

https://logs.zuul.ansible.com/00/58500/605d0d67102167cda67bd7f1046b4e1be408c372/third-party-check/ansible-test-network-integration-iosxr-python36/4d416d4/job-output.html#l13352

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iosxr_config

##### ANSIBLE VERSION
https://logs.zuul.ansible.com/00/58500/605d0d67102167cda67bd7f1046b4e1be408c372/third-party-check/ansible-test-network-integration-iosxr-python36/4d416d4/zuul-info/inventory.yaml

##### CONFIGURATION
ansible-test network integration iosxr_*

##### OS / ENVIRONMENT
iosxr-6.1.3
ubuntu-bionic (python3.6)

##### STEPS TO REPRODUCE
https://github.com/ansible/ansible/pull/58500

##### EXPECTED RESULTS
iosxr_config works, and opens socket via network_cli connection

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/iosxr/iosxr_config.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/iosxr/iosxr_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @justjais @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@pabelanger, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pabelanger** [comment]
example playbook:

https://github.com/ansible/ansible/commit/605d0d67102167cda67bd7f1046b4e1be408c372

**Comment by ganeshrn** [comment]
@pabelanger As a workaround, you can use the below task to achieve the same functionality
```
  - name: Ensure we have loopback 888 for testing
    iosxr_config:
      before:
      - interface Loopback888
      lines:
      - description test for ansible
      - shutdown
    connection: network_cli
    register: result
    until: result is success
```
