### ISSUE TITLE
archive module does not include top directory in archive

### ISSUE THREAD

**Issue by szeestraten** [ansible/ansible#58545]
##### SUMMARY

Archive module does not include top directory in archive.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

archive

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
vagrant@vagrant:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

##### STEPS TO REPRODUCE

I created a small repo with a Vagrantfile and playbook to reproduce: https://github.com/szeestraten/ansible-archive-bug

https://github.com/szeestraten/ansible-archive-bug/blob/master/archive.yml:
```yaml
---
- hosts: all
  tasks:
  - name: Create dirs
    file:
      path: /home/vagrant/dir1/dir2/dir3
      recurse: yes
      state: directory

  - name: Display directory
    command: find /home/vagrant/dir1 -print
    register: find_output
  - debug: var=find_output.stdout_lines

  - name: Create tar archive
    command: tar -cf /home/vagrant/tar_archive.tar.gz /home/vagrant/dir1

  - name: Create Ansible archive
    archive:
      path: /home/vagrant/dir1
      dest: /home/vagrant/ansible_archive.tar.gz

  - name: Extract tar archive
    command: tar -tvf /home/vagrant/tar_archive.tar.gz
    register: tar_output
  - debug: var=tar_output.stdout_lines

  - name: Extract Ansible archive
    command: tar -tvf /home/vagrant/ansible_archive.tar.gz
    register: ansible_output
  - debug: var=ansible_output.stdout_lines
```

```
$ vagrant up
...
PLAY [all] *********************************************************************                                                                                                                                                                      [13/1852]

TASK [Gathering Facts] *********************************************************
ok: [box]

TASK [Create dirs] *************************************************************
changed: [box]

TASK [Display directory] *******************************************************
changed: [box]

TASK [debug] *******************************************************************
ok: [box] => {
    "find_output.stdout_lines": [
        "/home/vagrant/dir1",
        "/home/vagrant/dir1/dir2",
        "/home/vagrant/dir1/dir2/dir3"
    ]
}

TASK [Create tar archive] ******************************************************
 [WARNING]: Consider using the unarchive module rather than running 'tar'.  If
you need to use command because unarchive is insufficient you can add 'warn:
false' to this command task or set 'command_warnings=False' in ansible.cfg to
get rid of this message.

changed: [box]

TASK [Create Ansible archive] **************************************************
changed: [box]

TASK [Extract tar archive] *****************************************************
changed: [box]

TASK [debug] *******************************************************************
ok: [box] => {
    "tar_output.stdout_lines": [
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 home/vagrant/dir1/",
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 home/vagrant/dir1/dir2/",
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 home/vagrant/dir1/dir2/dir3/"
    ]
}

TASK [Extract Ansible archive] *************************************************
changed: [box]

TASK [debug] *******************************************************************
ok: [box] => {
    "ansible_output.stdout_lines": [
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 dir1/dir2/",
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 dir1/dir2/dir3/"
    ]
}

PLAY RECAP *********************************************************************
box                        : ok=10   changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### EXPECTED RESULTS

Full path of all directories, including top directory:

```
TASK [Extract tar archive] *****************************************************
changed: [box]

TASK [debug] *******************************************************************
ok: [box] => {
    "tar_output.stdout_lines": [
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 home/vagrant/dir1/",
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 home/vagrant/dir1/dir2/",
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 home/vagrant/dir1/dir2/dir3/"
    ]
}
```

##### ACTUAL RESULTS

Missing top directory and different paths:

```paste below

TASK [Extract Ansible archive] *************************************************
changed: [box]

TASK [debug] *******************************************************************
ok: [box] => {
    "ansible_output.stdout_lines": [
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 dir1/dir2/",
        "drwxrwxr-x vagrant/vagrant   0 2019-06-29 16:10 dir1/dir2/dir3/"
    ]
}
```
