### ISSUE TITLE
Mail module works with US-ASCII encoding for Reply-To header but fails with UTF-8

### ISSUE THREAD

**Issue by chriscroome** [ansible/ansible#58543]
### SUMMARY
When using the [Mail module](https://docs.ansible.com/ansible/latest/modules/mail_module.html), in the documented manner, setting a `Reply-To` header fails unless the email character is set to US-ASCII.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Mail module by @dagwieers 

##### ANSIBLE VERSION
Debian Stretch with Ansible from backports
```
ansible 2.7.5
  config file = /home/chris/.ansible.cfg
  configured module search path = [u'/home/chris/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_PIPELINING(/home/chris/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/chris/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=240s -o PreferredAuthentications=publickey
ANSIBLE_SSH_CONTROL_PATH(/home/chris/.ansible.cfg) = /home/chris/tmp/cp%%h-%%p-%%r
DEFAULT_TIMEOUT(/home/chris/.ansible.cfg) = 60
```

##### OS / ENVIRONMENT
Debian Buster with Exim configured using [this Ansible role](https://git.coop/webarch/exim).

##### STEPS TO REPRODUCE
There is [a repo here](https://github.com/chriscroome/ansible-mail-test) that can be used to test this, it contains two tasks, the first one, reproduced below works and the second fails.

```yaml
- name: "US-ASCII Email sent to {{ mail_to }}"
  mail:
    from: "root <root@{{ inventory_hostname }}>"
    to: "{{ mail_to }}"
    subject: "Test email from {{ inventory_hostname }}"
    headers:
      - X-Auto-Response-Suppress=All
      - Reply-To=test@example.org
    charset: us-ascii
    body: "This is a test"
    host: localhost
    port: 25
    secure: never
  ignore_errors: true

- name: "UTF-8 Email sent to {{ mail_to }}"
  mail:
    from: "root <root@{{ inventory_hostname }}>"
    to: "{{ mail_to }}"
    subject: "Test email from {{ inventory_hostname }}"
    headers:
      - X-Auto-Response-Suppress=All
      - Reply-To=test@example.org
    charset: utf-8
    body: "This is a test"
    host: localhost
    port: 25
    secure: never
  ignore_errors: true
```

##### EXPECTED RESULTS

I would expect that UTF-8 email could be sent with a `Reply-To` header.

##### ACTUAL RESULTS

Mail only works with a `Reply-To` header when it is US-ASCII.

```paste below
TASK [mail : UTF-8 Email sent to you@example.org] ******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SMTPDataError: (550, 'header syntax')
fatal: [server.example.org]: FAILED! => {"changed": false, "msg": "Failed to send mail to 'you@example.org': (550, 'header syntax')", "rc": 1}
...ignoring
```

The Exim logs on the server documents this failures:

```
2019-06-29 11:03:20.784 [10043] 1hhB8a-0002bz-OP H=localhost (server.example.org) [127.0.0.1]:50190 I=[127.0.0.1]:25 F=<root@server.example.org> rejected after DATA: header syntax (unqualified address not permitted: failing address in "Reply-To:" header is: =?utf-8?q?test=40example=2Eorg?=): unqualified address not permitted: failing address in "Reply-To:" header is: =?utf-8?q?test=40example=2Eorg?=
```

The reason:

```
unqualified address not permitted:
  failing address in "Reply-To:" header is:
    =?utf-8?q?test=40example=2Eorg?=
```
