### ISSUE TITLE
ios_l2_interface does not add remove trunk vlans when many vlans configured

### ISSUE THREAD

**Issue by comshelp** [ansible/ansible#58575]
##### SUMMARY
When trunk vlans span multiple lines in the output from the "show int xxx switchport" command, ios_l2_interface  does not work for any vlans configured on the extra lines.

Changing the trunk match pattern to:
  trunk = re.search(r'Trunking VLANs Enabled: ([0-9,\s\-]+)', config, re.DOTALL)"

In ios_l2_interface.py fixes the problem. The key is adding DOTALL to the search which allows the pattern to span multiple lines.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l2_interface 

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 21 2019, 00:38:53) [GCC 4.9.2]
```

##### STEPS TO REPRODUCE

1) Add lots of vlans to a trunk interface so that vlans span multiple lines when doing "show int gi1/1 switchport" command, eg:

```
router1#show int gi1/1 switchport
Name: Gi1/1
Switchport: Enabled
...
Administrative private-vlan trunk mappings: none
Operational private-vlan: none
Trunking VLANs Enabled: 60,64,68,72,80,128,148,149,154,156,228,232,236,242,244,
     248,249,251,254,444,500,598-600,641,649,651,652,661,672,673,675,997,999
Pruning VLANs Enabled: 2-1001
...
Appliance trust: none
router1#
```

2) try and add/remove one of the vlans on the second line, eg vlan 997 using ios_l2_interface

```yaml
---
- name: ADD VLAN TO router1
  hosts: "router1"
  gather_facts: no
  connection: network_cli

  tasks:
  - name: add vlan to router1
    ios_l2_interface:
      name: gi1/1
      trunk_vlans: 997
      mode: trunk
      state: absent
```

3) After running the playbook the vlan 997 has not been removed.
