### ISSUE TITLE
Support omit within lists

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#58587]
##### SUMMARY
omit should also be supported within lists to allow jinja2 expressions to add elements to lists.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
omit
core

##### ADDITIONAL INFORMATION

As an administrator I want to have conditional elements in a task, so that I can simplify my playbook and roles and have less module invocations and a faster run.

```yaml
- win_feature:
    name:
      - "{% if not fs_installed_smb_v1|default(false) %}FS-SMB1{% else %}{{ omit }}{% endif %}"
      - "foo"
      - "bar"
    state: absent
- win_feature:
    name:
      - "{% if not fs_installed_smb_v1|default(false) %}FS-SMB1{% endif %}"
      - foo
      - bar
    state: absent
- win_feature:
    name: >-
      {{ '[' + (fs_installed_smb_v1) | ternary('"FS-SMB1",','') + '"foo", "bar"' ']' }}
    state: absent
```

The first example currently produces the following python list: [ '__omit_place_holder__375d4b174292829ef0a2d0878acbe8842696711d' ], therefore module execution will fail, as the omit place holder string gets passed onto the module. 
The second example instead produces [''], and module execution will fail, because of the empty string element. 
And the third one works as expected, but is not very intuitive and lists with more parameters tend to get messy really quickly, like:
```
- name: GitLab | bootstrap container
  docker_container:
    name: '{{ gitlab_container_name }}'
    state: present
    pull: yes
    purge_networks: yes
    image: '{{ gitlab_base_image }}'
    restart_policy: '{{ gitlab_restart_policy }}'
    # TODO: Fully fix, if the first element has ", " at the beginning, it fails.
    # Therefore if no ssh port is exposed it will fail.
    ports: >-
      {{ '[' + (gitlab_expose_ssh) | ternary(' "' + gitlab_ssh_host_ip + ':' ~
      gitlab_ssh_host_port +':22"','') + (gitlab_expose_http) | ternary(', "' +
      gitlab_http_host_ip + ':' ~ gitlab_http_host_port +':80"','') +
      (gitlab_expose_https) | ternary(', "' + gitlab_https_host_ip + ':' ~
      gitlab_https_host_port +':443"', '') + (gitlab_expose_prometheus) |
      ternary(', "' + gitlab_prometheus_host_ip + ':' ~
      gitlab_prometheus_host_port +':9090"', '') + ']' }}
    networks: '{{ gitlab_docker_networks }}'
    volumes:
      - '{{ gitlab_project_directory }}/etc:/etc/gitlab:rw'
      - '{{ gitlab_project_directory }}/opt:/var/opt/gitlab:rw'
      - '{{ gitlab_project_directory }}/log:/var/log/gitlab:rw'
```
Also they are prown for race conditions like in this example if gitlab_expose_ssh is false but any of the following gitlab_expose_http, gitlab_expose_https, gitlab_expose_prometheus is true, it will fail, as all of these elements have a prepended semicolon. Sure, that one could also be fixed with e.g. `(gitlab_expose_ssh and gitlab_expose_http) | ternary(',','')`, but even that would not cover all cases and more or less considerable as write only code (you can write it, but shortly after you're unable to read it again).

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/integration/targets/omit/48673.yml`](https://github.com/ansible/ansible/blob/devel/test/integration/targets/omit/48673.yml)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
We are conflicted about adding this feature, and it has come up in the past.

Should you want to pursue this further, please add this to the core IRC meeting agenda for additional discussion: https://github.com/ansible/community/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Ameeting_agenda+label%3Acore

Example PR from a previous attempt: #39179

**Comment by sivel** [comment]
!component =lib/ansible/executor/task_executor.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/executor/task_executor.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
You can already do this:
``` yaml
- win_feature:
    name: '{{ namestuff|reject('equal_to', omit)|list }}'
  state: absent
  vars:
    namestuff:
      - "{% if not fs_installed_smb_v1|default(false) %}FS-SMB1{% else %}{{ omit }}{% endif %}"
      - "foo"
      - "bar"
    state: absent
    
```

**Comment by felixfontein** [comment]
From IRC discussion; I think this should work:
```.yaml
- win_feature:
    name: "{{ name_list | filter("equal_to", omit) | list }}"
    state: absent
  vars:
    name_list:
      - "{% if not fs_installed_smb_v1|default(false) %}FS-SMB1{% else %}{{ omit }}{% endif %}"
      - "foo"
      - "bar"
```

**Comment by bcoca** [comment]
another way, construct it w/o omited
```yaml

- set_fact:
     namestuff: ' {{ namestuff|default([])|union([item])| }}'
  when: item != omit
  loop:
      - "{% if not fs_installed_smb_v1|default(false) %}FS-SMB1{% else %}{{ omit }}{% endif %}"
      - "foo"
      - "bar"

- win_feature: name={{namestuff}}
```
