### ISSUE TITLE
generate azure sas tokens

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#58585]
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

Please add a module that supports creating azure sas tokens for downloading private blob files.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nicolaibaralmueller: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
!component =lib/ansible/modules/cloud/azure/__init__.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/azure/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/__init__.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @yungezz @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@nicolaibaralmueller Thanks for your open this issue for the new feature!

**Comment by Fred-sun** [comment]
@zikalino @yungezz @MyronFanQiu Could you help take a look this issue when you're free? Thanks a lot!

**Comment by nicolaibaralmueller** [comment]
> @zikalino @yungezz @MyronFanQiu Could you help take a look this issue when you're free? Thanks a lot!

I tried using the module azure_rm_deployment and generate sas token via an ARM template but did not succeed.
Python examples is also very hard to find.

Easy to use powershell or azure-cli but a module would be prefered.

**Comment by zikalino** [comment]
I think you may try to use **azure_rm_resource**. Could you give Azure CLI example you're using?

**Comment by nicolaibaralmueller** [comment]
> I think you may try to use **azure_rm_resource**. Could you give Azure CLI example you're using?

@zikalino 

Sure.

`az storage blob generate-sas --account-name {{ account_name }} --account-key {{ vault_storage_account_key }} --container-name {{ container_name }} --name {{ file }} --permissions r --expiry {{ today }}T{{ later }}Z --https-only`

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
> I think you may try to use azure_rm_resource. Could you give Azure CLI example you're using?
> 
> @zikalino
> Sure.
> az storage blob generate-sas --account-name {{ account_name }} --account-key {{ vault_storage_account_key }} --container-name {{ container_name }} --name {{ file }} --permissions r --expiry {{ today }}T{{ later }}Z --https-only

@zikalino Any update for this?

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Fred-sun** [comment]
@mybayern1974

**Comment by tgadiev** [comment]
> > @zikalino @yungezz @MyronFanQiu Could you help take a look this issue when you're free? Thanks a lot!
> 
> I tried using the module azure_rm_deployment and generate sas token via an ARM template but did not succeed.
> Python examples is also very hard to find.
> 
> Easy to use powershell or azure-cli but a module would be prefered.

We managed to generate sas token via `azure_rm_resource` module. Working example:
```yaml
- name: Set expiration period
  set_fact:
    sas_time_start: '{{ ansible_date_time.iso8601_micro }}'
    sas_time_expire: >-
      {{ ('%Y-%m-%dT%H:%M:%S'
        | strftime(ansible_date_time.epoch|int + 120))
        ~ (ansible_date_time.iso8601_micro | splitext)[1] }}

- name: Generate access signature
  azure_rm_resource:
    resource_group: '{{ az_resource_group_name }}'
    method: POST
    url: "/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}\
          /resourceGroups/{{ az_resource_group_name }}/providers/\
          Microsoft.Storage/storageAccounts/\
          {{ az_storage_account_name }}/ListServiceSas/"
    body:
      canonicalizedResource: '/blob/{{ az_storage_account_name }}/{{ az_container_name }}/{{ az_file_name }}'
      signedResource: b
      signedPermission: r
      signedStart: '{{ sas_time_start }}'
      signedExpiry: '{{ sas_time_expire }}'
  register: storage_sig
```
This code created sas valid for 120 seconds allowing to download it directly throu https during that period.
