### ISSUE TITLE
vmware_guest_disk: add disk_mode parameter

### ISSUE THREAD

**Issue by meons** [ansible/ansible#58592]
##### SUMMARY

vmware_guest_disk should propose `disk_mode` parameter (like vmware_guest module).
The playbook bellow does not raise an error but disk is always added in `persistent` mode, even I set `independent_persistent` for `disk_mode` var.
If it's a bug please could you fix it? If it's not consider it as a feature request :)

##### ISSUE TYPE
- Feature Idea (or maybe a bug)

##### COMPONENT NAME

vmware_guest_disk 

##### ADDITIONAL INFORMATION

```yaml
---
- name: get vm {{ target | upper }} facts
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    name: "{{ target | upper }}"
  register: vm_facts
  delegate_to: localhost

- name: add disk to vm {{ target | upper }}
  vmware_guest_disk:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    name: "{{ target | upper }}"
    disk:
      - size_gb: "{{ size_gb }}"
        type: "{{ type }}"
        disk_mode: "{{ disk_mode }}"
        scsi_controller: "{{ scsi_controller }}" 
        unit_number: "{{ unit_number }}"
        datastore: "{{ vm_facts.instance.hw_datastores | first }}"
  delegate_to: localhost
```
