### ISSUE TITLE
Group module not respecting "local: yes"

### ISSUE THREAD

**Issue by pravindmali** [ansible/ansible#58619]
##### SUMMARY

Trying to to create a local group entry with "local:yes" even if entry exists in the global LDAP directory. Looks like issue is with the group module as its not respecting "local: yes"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

group
##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.8.1
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```
##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7

##### STEPS TO REPRODUCE

1] system should be member of the LDAP domain, where the group nginx already exist.
2] Then execute the below playbook.

```yaml
  - name: Create /etc/group entry for nginx
    group:
      gid: 38664
      local: yes
      name: nginx
      state: present
  
  - name: Create /etc/passwd entry for nginx
    user:
      comment: nginx
      group: nginx
      home: /var/lib/nginx
      local: yes
      name: nginx
      password_lock: yes
      shell: /sbin/nologin
      state: present
      uid: 38664
```

##### EXPECTED RESULTS

it should ignore the LDAP directory and create the /etc/group local entry with mentioned GID.

##### ACTUAL RESULTS

Its creating group with different GID. In this example playbook in passing GID 38664 but output shows its created with GID 1000 as below 

```
TASK [Create /etc/group entry for nginx]
[server.example.com] => {
    "changed": false, 
    "gid": 38664, 
    "invocation": {
        "module_args": {
            "gid": 38664, 
            "local": true, 
            "name": "nginx", 
            "non_unique": false, 
            "state": "present", 
            "system": false
        }
    }, 
    "name": "nginx", 
    "state": "present", 
    "system": false
}

TASK [Create /etc/passwd entry for nginx]

changed: [server.example.com] => {
    "changed": true, 
    "comment": "nginx", 
    "create_home": true, 
    "group": 1000,      <------------------------------------------------------
    "home": "/var/lib/nginx", 
    "invocation": {
        "module_args": {
            "append": false, 
            "authorization": null, 
            "comment": "nginx", 
            "create_home": true, 
            "expires": null, 
            "force": false, 
            "generate_ssh_key": null, 
            "group": "nginx", 
            "groups": null, 
            "hidden": null, 
            "home": "/var/lib/nginx", 
            "local": true, 
            "login_class": null, 
            "move_home": false, 
            "name": "nginx", 
            "non_unique": false, 
            "password": null, 
            "password_lock": true, 
            "profile": null, 
            "remove": false, 
            "role": null, 
            "seuser": null, 
            "shell": "/sbin/nologin", 
            "skeleton": null, 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on server.example..com", 
            "ssh_key_file": null, 
            "ssh_key_passphrase": null, 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": false, 
            "uid": 38664, 
            "update_password": "always"
        }
    }, 
    "name": "nginx", 
    "shell": "/sbin/nologin", 
    "state": "present", 
    "system": false, 
    "uid": 38664
}

```

```paste below

```
