### ISSUE TITLE
variable precedence for group loading is unclear

### ISSUE THREAD

**Issue by mhunsber** [ansible/ansible#58643]
##### SUMMARY

According to the [Variable Precedence](https://docs.ansible.com/ansible/devel/user_guide/playbooks_variables.html#ansible-variable-precedence) docs: 

> If multiple groups have the same variable, the last one loaded wins.

> Group loading follows parent/child relationships. Groups of the same ‘parent/child’ level are then merged following alphabetical order.

The wording makes it seem like if I have a host that is a member of a group at depth=1 and a group at depth=2, that the parent/child relationship will be loaded first, and then the alphabetical precedence takes place. When really it seems to be the case that depth is the sole determinant of variable precedence, not parent/child relations specifically, and that alphabetical order only matters if the variable is defined at two groups of the same depth.

It is easier to explain with an example:
**inventory.yml**
```yaml
---
all:
  vars:
    test: set by all
  children:
    group_a:
      hosts:
        host1:
      vars:
        test: set by group_a
      children:
        group_a1:
          hosts:
            host2:
          vars:
            test: set by group_a1
    group_b:
      hosts:
        host1:
        host2:
      vars:
        test: set by group_b
```
Because *group_b* is alphabetically after *group_a*, based on the docs I would expect `ansible-inventory --host host1` to output:
```json
{
    "test": "set by group_b"
}
```
(which it does).
However, based on how I interpret the meaning of the description in the docs, "parent/child relationships" are loaded first, and then "Groups of the same 'parent/child' level *are then* merged following alphabetical order." Therefore, I would expect `ansible-inventory --host host2` to output:
```json
{
    "test": "set by group_b"
}
```
Since "set by group_a1" would override "set by group_a", but then "set by group_b" would override the group_a variable. But the actual result is
```json
{
    "test": "set by group_a1"
}
```
suggesting that really each group depth is loaded in alphabetical order, so that the group at the highest depth and last in the alphabet is loaded last.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

playbooks_variables

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library', u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/ansible/lib/ansible
  executable location = /home/admin/.local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
```

##### ADDITIONAL INFORMATION

I'm **not** arguing that I think my "expected result" for *host2* is actually how ansible should behave. I think the note in the docs are confusing, and maybe should say that group depth is what matters, not the "parent/child" relationships bit. Or the docs could include an example for clarity.
