### ISSUE TITLE
failed to use variable for retries in the loop

### ISSUE THREAD

**Issue by jack1402** [ansible/ansible#5865]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.4.3
##### Environment:

RHEL 6.5
##### Summary:

we are trying to use the variable for the value of retries at loop. But always hit an error
##### Steps To Reproduce:

Run following playbook:

```
hosts: localhost 
     vars: tries: 5 
tasks:
     - name: test
       debug: msg="looping" 
       register: output 
       until: no 
       retries: "{{ tries | int }}" 
       delay: 1
```
##### Expected Results:

retries count is 5 
##### Actual Results:

get following error:

TASK: [test] ******************************************************************
fatal: [localhost] => Traceback (most recent call last):
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 394, in executor
execrc = self.executorinternal(host, new_stdin)
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 485, in executorinternal
return self.executorinternal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
File "/usr/lib/python2.6/site-packages/ansible/runner/init.py", line 694, in executorinternal_inner
for x in range(1, retries + 1):
TypeError: cannot concatenate 'str' and 'int' objects

FATAL: all hosts have already failed -- aborting

**Comment by rafecolton** [comment]
Looks like this is still an issue with 1.8.2?

**Comment by evgeny-goldin** [comment]
Yes, in 1.8.2

`retries:  '{{ 5 }}'`

produces

```
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 818, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1035, in _executor_internal_inner
    for x in range(1, int(retries) + 1):
ValueError: invalid literal for int() with base 10: '{{ 5 }}'
```

**Comment by srikanthsrs** [comment]
In which version is this fixed?

**Comment by evgeny-goldin** [comment]
I have it [working](https://github.com/evgeny-goldin/playbooks/blob/eac7c5ed672d80fae074c0e28e20efdae2d684ed/playbooks/utils/verify.yml#L49) with Ansible `1.8.4`.

**Comment by semente** [comment]
Hey guys, looks like we have a regression on 2.3.0, at least when using on docker_service.scale:

```
    - name: set up web apps
      docker_service:
        project_src: "/srv/{{ item }}"
        stopped: "{{ instances.get(item).is_disabled | default('false') }}"
        pull: yes
        scale:
          web: "{{ instances.get(item).scale }}"
      with_items: "{{ web_instances }}"
```

I've tried with and without `| int`. Any advice? Is it really a regression? On 2.2.0 it used to work.
