### ISSUE TITLE
ini_file: Custom values for boolean fields

### ISSUE THREAD

**Issue by JoyceBabu** [ansible/ansible#58662]
##### SUMMARY

Allow writing / reading custom values for boolean fields

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ini_file

##### ADDITIONAL INFORMATION
Currently boolean values are converted to `False` / `True`. But not all softwares support `True` / `False` for boolean fields. For example, MySQL and PHP use `On`/`Off` for boolean fields. Also, there may be others that use `Yes`/`No` or  non english values.

Currently it is possible to work around this by quoting the values, and Ansible shows a warning in such cases. But  it is possible that at least some users may miss the warning. Please add an option to configure the values to be used for boolean fields, so that role authors can choose the value that should written instead of asking users to quote the value.

```yaml
- name: Writing ini file
  become: true
  ini_file:
    path: "{{ config.path }}"
    section: "{{ item.section | default('') }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
    state_true: "ON"
    state_false: "OFF"
  loop: "{{ config.options }}"
```
