### ISSUE TITLE
acl module claims to support NFSv4 ACLs but does not

### ISSUE THREAD

**Issue by FraserMCampbell** [ansible/ansible#58679]
##### SUMMARY

The acl modules claims to support NFSv4 ACLs.  There is the parameter use_nfsv4_acls.

When I set the use_nfsv4_acls parameter to yes it does not attempt to use NFSv4 ACLs at all.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

acl

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = None
  configured module search path = ['/home/fraser.campbell/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fraser.campbell/ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/fraser.campbell/ansible/bin/ansible
  python version = 3.6.3 (default, Apr 19 2019, 02:01:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Any Linux OS as target, issue is the same regardless of target being RHEL6, RHEL7 or Oracle Linux 7.

NFS server is a NetApp ONTAP storage appliance exporting NFSv4 (ONTAP version is 9.4p3).

Here are examples of getting and settings NFS v4 ACLs:

[user@host ~]$ ls -ld path
drwxr-s--- 6 user user 4096 Jun 26 11:45 path
[user@host ~]$ nfs4_setfacl -a A:d:5827:rxtncy path
[user@host ~]$ nfs4_getfacl path
A:d:5827:rxtncy
A::OWNER@:rwaDxtTnNcCy
A:g:GROUP@:rxtncy
A::EVERYONE@:tncy

##### STEPS TO REPRODUCE

set use_nfsv4_acls parameter to yes for an ACL task, run it.

With my sample playbook:  ansible-playbook  -i somehost, -e "path=/somepath user=someuser" test_nfs4_acl.yaml

```yaml
---
- name: "Ensure proper ownership and ACLS"
  gather_facts: True
  hosts: all
  tasks:
  - name: "Set NFS4 ACL to allow uid 5827 access on {{ path }}"
    become: true
    become_flags: '-i'
    become_user: "{{ user }}"
    acl:
      path: "{{ path }}"
      entity: "5827"
      etype: user
      permissions: rx
      state: present
      recursive: yes
      default: yes
      use_nfsv4_acls: yes

```

##### EXPECTED RESULTS

On Linux NFSv4 ACLs must be set using the nfs4_setfacl command, the setfacl command does not support NFSv4 ACLs and cannot be used.  See https://access.redhat.com/solutions/3426621 for example.

##### ACTUAL RESULTS

acl module task uses setfacl command instead of nfs4_setfacl.

Also the string generated for ACL doesn't appear to represent correct syntax for an ACL (either NFSv4 or not).

```paste below
TASK [Set NFS4 ACL to allow uid 5827 access on /app/hworks/glagoon/IN] ***********************************************************************
fatal: [somehost]: FAILED! => {"changed": false, "cmd": "/bin/setfacl --test -d -m user:5827:rx:allow --recursive /somepath", "msg": "setfacl: Option -m: Invalid argument near character 13", "rc": 2, "stderr": "setfacl: Option -m: Invalid argument near character 13\n", "stderr_lines": ["setfacl: Option -m: Invalid argument near character 13"], "stdout": "", "stdout_lines": []}


```
