### ISSUE TITLE
os_port: setting device_id does not attach the port to an instance

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible/ansible#58671]
##### SUMMARY

In my scenario I have an already existing system in Openstack and I want to connect it to a newly created network. From what I found out so far is that one needs to have the following parts:

* Instance as created by ```os_server```
* Network as created by ```os_network```
* Port as created by ```os_port```

I am able to attach the created port via the Horizon interface to my pre-existing instance and it works. A new interface will be created in the hosts' OS and after configuring it, I can use it to connect to systems in the other network.

However, when I use Ansible to attach the port by updating the port's device_id, this does not happen.

Is this a bug, or do I need a different method of attaching ports/interfaces to instances? Or could be something at OVH's side?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_port

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Openstack platform: OVH, version unknown to me
Ansible master OS: Debian 9

Running tests on my role via Molecule.

##### STEPS TO REPRODUCE

```yaml
- name: 'Create fixed ports for connect_hosts'
  os_port:
    cloud: 'openstack'
    name: "my_port"
    network: "my_network"
    fixed_ips:
      - ip_address: "192.168.1.1"
    device_id: "{{ connect_host.id }}" # I collect this in a different task
```

##### EXPECTED RESULTS

Connect the port to my instance and work.

##### ACTUAL RESULTS

The webinterface shows the port associated with the instance, but there's no device created inside the instance.

```paste below

```
