### ISSUE TITLE
Casting a default variable to boolean gives incorrect result

### ISSUE THREAD

**Issue by TimRuhl** [ansible/ansible#58710]
##### SUMMARY
When we define a boolean variable in defaults/main.yml and use this variable in the when condition of a task step we get different results depending on whether the variable is cast to boolean (with |bool) or not.  The casted result is incorrect.  
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Boolean variables defined in default and used in when condition

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
[root@localhost ansible-error]# ansible-config dump --only-changed
[root@localhost ansible-error]# 

```

##### OS / ENVIRONMENT

[root@localhost ansible-error]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

[root@localhost ansible-error]# uname -a
Linux localhost.localdomain 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

We have created a role test with defaults and a simple task to output a debug message depending on the result of the variable defined in defaults/main.yml.  

```yaml
[root@localhost ansible-error]# cat roles/test/defaults/main.yml 
systemd_based: (ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7)

[root@localhost ansible-error]# cat roles/test/tasks/main.yml 
- name: test without cast
  debug:
    msg: "Without cast"
  when: systemd_based
- name: test with cast
  debug:
    msg: "With cast"
  when: systemd_based|bool

[root@localhost ansible-error]# cat playbook.yml 
- hosts: all
  roles:
  - {role: test}

[root@localhost ansible-error]# cat inventory/hosts.yml 
[all]
remote		ansible_host="{{ remote_address }}" ansible_port=22 ansible_user=root
local		ansible_connection=local


[root@localhost ansible-error]# ansible-playbook playbook.yml -i inventory -l local

PLAY [all] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************
ok: [local]

TASK [test : test without cast] **********************************************************************************************************************************************************
[DEPRECATION WARNING]: evaluating systemd_based as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see 
CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [local] => {
    "msg": "Without cast"
}

TASK [test : test with cast] *************************************************************************************************************************************************************
skipping: [local]

PLAY RECAP *******************************************************************************************************************************************************************************
local                      : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

##### EXPECTED RESULTS

We expected both steps to be executed, but the step with the cast is skipped

##### ACTUAL RESULTS

```paste below
[root@localhost ansible-error]# ansible-playbook -vvv playbook.yml -i inventory -l local  |egrep '(ansible_os_family|ansible_distribution_major_version)'
        "ansible_distribution_major_version": "7", 
        "ansible_os_family": "RedHat", 

```
