### ISSUE TITLE
Not possible to create CA certificate with openssl_certificate

### ISSUE THREAD

**Issue by ephracis** [ansible/ansible#58715]
##### SUMMARY
It is not possible to use Ansible's OpenSSL modules to generate a CA certificate.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssl_certificate

##### ADDITIONAL INFORMATION
Given the following three tasks:

```yaml
- name: Generate CA private key
  openssl_privatekey:
    path: /path/to/key

- name: Generate CA request
  openssl_csr:
    path: /path/to/csr
    privatekey_path: /path/to/key
    common_name: My CA
    # ...
    basic_constraints:
      - 'CA:true'

- name: Generate CA certificate
  openssl_certificate:
    path: /path/to/ca_cert
    privatekey_path: /path/to/key
    csr_path: /path/to/csr
    provider: selfsigned
```

I get a certificate that is missing the proper CA constraint (even though it was specified in the CSR) and all certificates signed by this CA will be rejected by web browsers such as Google Chrome.

The current workaround is to use the command line instead, losing stuff like idempotence, check mode, etc.
