### ISSUE TITLE
Azure Virtual Machine and VM fact modules - difficulties with Availability Zone support

### ISSUE THREAD

**Issue by andyeff** [ansible/ansible#58729]
##### SUMMARY

When querying an Azure virtual machine that is in an availability zone with the azure_rm_virtualmachine_facts module, the returned facts do not include the availability zone data.

Additionally, when trying to shut down or start an Azure virtual machine using the azure_rm_virtualmachine module, the module will fail unless the availability zone is also passed as a parameter - it looks like without specifying the 'zones' parameter, it attempts to remove the VM from an AZ. This causes a problem if we do not know the AZ ahead of time and cannot determine it from the VM Fact module output as above.

This generally affects us with our Ansible Tower based configuration ( Tower 3.5.0 / Ansible 2.8 ), but for the sake of testing / convenience, I will use a local Ubuntu 16.04 VM with Ansible 2.8 installed to get the relevant output required below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine
azure_rm_virtualmachine_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /home/vagrant/azure-dev/provisioning/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/.local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/vagrant/azure-dev/provisioning/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/vagrant/azure-dev/provisioning/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=5m -o User=localadm -o IdentityFile=~/.ssh/dev-o
DEFAULT_CALLBACK_WHITELIST(/home/vagrant/azure-dev/provisioning/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/home/vagrant/azure-dev/provisioning/ansible.cfg) = 50
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/vagrant/azure-dev/provisioning/inventories/REDACTED/hosts.ini']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/vagrant/azure-dev/provisioning/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/vagrant/azure-dev/provisioning/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/home/vagrant/azure-dev/provisioning/ansible.cfg) = /home/vagrant/azure-dev/provisioning/vaultpass
DEPRECATION_WARNINGS(/home/vagrant/azure-dev/provisioning/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/vagrant/azure-dev/provisioning/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/vagrant/azure-dev/provisioning/ansible.cfg) = False

```

##### OS / ENVIRONMENT

VM's in Azure public cloud environment, mixed operating systems (This bug only concerns using Azure modules and not talking directly to a VM)

##### STEPS TO REPRODUCE

For the facts problem, use azure_rm_virtualmachine_facts and pass along a VM name and resource group

For the start / stop VM and AZ issue, use azure_rm_virtualmachine 

```yaml
 - name: Query Azure for VM data
   azure_rm_virtualmachine_facts:
     name: "{{ inventory_hostname }}"
     resource_group: "{{ resgroup }}"
   delegate_to: localhost
   register: vm_facts
   ignore_errors: true

- name: Start VM
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ inventory_hostname }}"
    allocated: yes
    started: yes
  delegate_to: localhost

- name: Stop and deprovision VM
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ inventory_hostname }}"
    state: present
    allocated: no
  delegate_to: localhost

```

##### EXPECTED RESULTS

The facts module returns information about the AZ of a machine, if applicable.

The Start/Stop tasks will start or deallocate a VM if we do not provide an availability zone parameter.

##### ACTUAL RESULTS

The azure_rm_virtualmachine_facts module does not return availabiltiy zone data, the azure_rm_virtualmachine module fails to perform a power operation on a VM unless the 'zones' parameter is included - it in fact looks like it is trying to remove the VM from an availability zone.

```paste below
TASK [debug vm facts] ******************************************************************************************************************************************
task path: /home/vagrant/azure-dev/provisioning/azure-scheduler.yml:56
ok: [uksdvfog001] =>
  vm_facts:
    ansible_facts:
      discovered_interpreter_python: /usr/bin/python
    changed: false
    deprecations:
    - msg: Distribution Ubuntu 16.04 on host uksdvfog001 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information
      version: '2.12'
    failed: false
    vms:
    - admin_username: REDACTED
      data_disks: []
      id: /subscriptions/REDACTED/resourceGroups/dv-afogg01-rg/providers/Microsoft.Compute/virtualMachines/uksdvfog001
      image:
        offer: RHEL
        publisher: RedHat
        sku: '6.10'
        version: 6.10.2019061919
      location: uksouth
      name: uksdvfog001
      network_interface_names:
      - uksdvfog001-nic-0
      os_disk_caching: ReadOnly
      os_type: Linux
      power_state: running
      resource_group: dv-afogg01-rg
      state: present
      tags:
        environment: Development
        function: AFOGGTEST
      vm_size: Standard_B2s


TASK [Start VM] ************************************************************************************************************************************************
fatal: [uksdvfog001]: FAILED! => changed=false
  msg: 'You can''t change the Availability Zone of a virtual machine (have: [1], want: None)'


```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)
* [`lib/ansible/modules/cloud/azure/azure_rm_virtualmachine_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cperrin88 @gustavomcarmo @haroldwongms @jeking3 @nitzmahone @trstringer @yungezz @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@andyeff, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MyronFanQiu** [comment]
@andyeff Thanks! We will investigate this issue. @zikalino @yungezz This is a issue about VM and its `zones` parameter. Please take a look when you are free.

**Comment by Fred-sun** [comment]
@andyeff Are you still focused on the problem? If the VM is designated in available zones at creation time, it is necessary to add zones in the playbook when restarting or stopping the VM. This will fix any errors you encounter. Thank you very much!
```e.g.
- name: Start VM
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ inventory_hostname }}"
    allocated: yes
    started: yes
    zones: "{{ zone_number }}"
  delegate_to: localhost

- name: Stop and deprovision VM
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ inventory_hostname }}"
    state: present
    allocated: no
    zones: "{{ zone_number }}"
  delegate_to: localhost

**Comment by andyeff** [comment]
Hi @Fred-sun - yep, I am currently using a workaround of checking VM availability zone in the Azure Portal and manually adding it to the inventory.

I haven't yet checked if there's some other way to determine the availability zone of a machine using a different Ansible module, although I suspect I could use azure_rm_resource_facts to query the Azure API directly to get the information. (I haven't done this as I am in the fortunate position of using a fairly static inventory with not much changing once VM's have been deployed)

**Comment by Fred-sun** [comment]
@andyeff Thanks for your sharing. Normally, the zones parameter is not required for VM restart or stopping. This is a small bug and should be fixed in the future. Thank you very much!

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@zikalino Can you give a fix when you're free? Thank you very much!

**Comment by Fred-sun** [comment]
@mybayern1974 Would you please help take a look this issue? Thank you very much!

**Comment by mnaccarato** [comment]
> Hi @Fred-sun - yep, I am currently using a workaround of checking VM availability zone in the Azure Portal and manually adding it to the inventory.
> 
> I haven't yet checked if there's some other way to determine the availability zone of a machine using a different Ansible module, although I suspect I could use azure_rm_resource_facts to query the Azure API directly to get the information. (I haven't done this as I am in the fortunate position of using a fairly static inventory with not much changing once VM's have been deployed)

Hi @andyeff indeed you can gather zone info with azure_rm_resource_facts, here is a workaround to your problem:

```yml
- name: Get VM Availability Zone
  azure_rm_resource_facts:
    resource_group: "{{ resgroup }}"
    resource_name: "{{ inventory_hostname }}"
    resource_type: VirtualMachines 
    provider: Compute
  register: result

- name: Start VM
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ inventory_hostname }}"
    allocated: yes
    started: yes
    zones: "{{ result.response[0].zones }}"
  delegate_to: localhost

- name: Stop and deprovision VM
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ inventory_hostname }}"
    state: present
    allocated: no
    zones: "{{ result.response[0].zones }}"
  delegate_to: localhost
```
Btw the problem still persist in ansible 2.9.

Hope this helps!
