### ISSUE TITLE
VMware: vmware_guest throws vmdk already exists

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#58721]
##### SUMMARY

vmware_guest throws error that vmdk already exists although it does not. It is created during running the module but somehow fails. 

pyvmomi-6.7.1.2018.12

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
2.8.1
```

##### STEPS TO REPRODUCE

```yaml
- name: Create new VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    esxi_hostname: "{{ esxi_host }}"
    username: '{{domain_user}}'
    password: "{{ domain_user_password }}"
    validate_certs: False
    datacenter: TM
    name: "{{ vm_hostname }}"
    folder: "{{ vm_destination }}"      
    state: poweredon
    disk:
    - size_gb: '{{ disk_size }}'
      type: thin
      autoselect_datastore: True
    hardware:
      memory_mb: "{{ memory }}"
      num_cpus: "{{ cores }}"
      num_cpu_cores_per_socket: "{{ cores }}"
    networks:
    - name: LAN
      domain: "{{ domain }}"
      dns_servers:
      -  "{{ dns1 }}"
      -  "{{ dns2 }}"
      type: static
      ip: "{{ ip }}"
      netmask: 255.255.254.0
      gateway: 192.168.1.5
    customization:
      autologon: True
      hostname: "{{ vm_hostname }}"
      domain: "{{ domain }}"
      password: vagrant
      domainadmin: "{{ domain_user }}"
      domainadminpassword: "{{ domain_user_password }}"
      joindomain: "{{ domain }}"
      timezone: 105
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\StartupScripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\StartupScripts\DisableFirewall.ps1 
    wait_for_customization: yes
    template: "{{ vm_template }}"
    wait_for_ip_address: yes
```

##### EXPECTED RESULTS

Should just create the VM.

##### ACTUAL RESULTS

```paste below
Failed to create a virtual machine : Cannot complete the operation because the file or folder [EL02] ********/********.vmdk already exists"
```
