### ISSUE TITLE
hcloud_server misses a way to put a server in rescue mode

### ISSUE THREAD

**Issue by asarubbo** [ansible/ansible#58746]
##### SUMMARY

Atm, there is no way to put the server in rescue mode

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hcloud_server

##### ADDITIONAL INFORMATION

Atm, Since I can use the hetzner api, I'm using the following code to put it into rescue:

```yaml
    - name: Enable rescue
      uri:
        url: "https://api.hetzner.cloud/v1/servers/{{ item }}/actions/enable_rescue"
        method: POST
        status_code: 201
        body_format: json
        body:
          type: "linux64"
          ssh_keys: [341997]
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ hostvars['localhost']['hetzner_api_token'] }}"
      with_items:
        - "{{ server_id }}"
```
