### ISSUE TITLE
Playbook that doesn't gather facts can not be included by playbook that does gather facts

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible#5874]
##### Environment:

Ansible host is Mac OSX 10.9.1
Guest is CentOS 6.4
##### Summary:

Playbook that doesn't gather facts can not be included by playbook that does gather facts.  
##### Steps To Reproduce:

This playbook that gathers facts runs without issue

```
➜  ansible git:(bug) ✗ cat bug/main.yml 

---
- hosts: asirdev 
  user: root
  tasks:
    - shell: echo test
```

So does this one that doesn't gather facts

```
➜  ansible git:(bug) ✗ cat bug/other.yml 

---
- hosts: asirdev 
  user: root
  gather_facts: no
  tasks:
    - shell: echo test
```

But when the first one that gathers facts includes the second one that does not like this ...

```
➜  ansible git:(bug) ✗ cat bug/main.yml 

---
- hosts: asirdev 
  user: root
  tasks:
    - shell: echo test
    - include: /etc/ansible/bug/other.yml
```

It errors

```
➜  ansible git:(bug) ✗ ansible-playbook bug/main.yml
ERROR: gather_facts is not a legal parameter in an Ansible task or handler
```
##### Expected Results:

Expected the playbook to still run without error
##### Actual Results:

```
➜  ansible git:(bug) ✗ ansible-playbook bug/main.yml
ERROR: gather_facts is not a legal parameter in an Ansible task or handler
```
