### ISSUE TITLE
delegate_to not working

### ISSUE THREAD

**Issue by elwinh** [ansible/ansible#58763]
##### SUMMARY
My job can't connect to a Windows machine within 'delegate_to' task. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
delegate_to

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = None
  configured module search path = [u'/export/gitlab-runner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /export/gitlab-runner/.venv/lib/python2.7/site-packages/ansible
  executable location = /export/gitlab-runner/.venv/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 13:30:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
```
NAME="Oracle Linux Server"
VERSION="7.6"
ID="ol"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Oracle Linux Server 7.6"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:6:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.6
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.6
```

##### STEPS TO REPRODUCE
I use the following playfile and role:

main.yml
```yaml
---

- debug:
    msg: "Set service '{{ service.servicename }}' on server '{{ service.targetserver }}' to '{{ service.servicestate }}' and connect with username: '{{ service.ansible_user }}', port: '{{ service.ansible_port }}' and connection: '{{ service.ansible_connection }}'."

- name: "Change service."
  win_service:
    name: "{{ service.servicename }}"
    state: "{{ service.servicestate }}"
  vars:
    ansible_user: "{{ service.ansible_user }}"
    ansible_password: "{{ service.ansible_password }}"
    ansible_port: "{{ service.ansible_port }}"
    ansible_connection: "{{ service.ansible_connection }}"
    ansible_winrm_server_cert_validation: ignore
  delegate_to: "{{ service.targetserver }}"
```

playfile.yml
```yaml
---

- name: "Test play"
  hosts: "lnx_rundeck_machine"
  tasks:

    - name: "Set services that should be stopped"
      set_fact:
        list_services_stopped: 
          - targetserver: "win_testmachine"
            servicename: "W32Time"
            servicestate: "stopped"
            ansible_user: "ci-reddog\\rundeck-manage"
            ansible_password: "{{ win_ansible_password }}"
            ansible_port: "{{ win_ansible_port }}"
            ansible_connection: "{{ win_ansible_connection }}"
          - targetserver: "win_testmachine"
            servicename: "Spooler"
            servicestate: "stopped"
            ansible_user: "domain\\username"
            ansible_password: "********"
            ansible_port: "5986"
            ansible_connection: "winrm"

    - name: "Stop services"
      include_role:
        name: "change_servicestate"
      loop: "{{ list_services_stopped }}"
      loop_control:
        loop_var: "service"
```

##### EXPECTED RESULTS
I expect the code to be run on the windows testmachine

##### ACTUAL RESULTS
I get an error that the rundeck machine is unreachable. (delegate_to not working?)
```bash
[...]

TASK [change_servicestate : debug] *********************************************
ok: [lnx_rundeck_machine] => {
    "msg": "Set service 'W32Time' on server 'win_testmachine' to 'stopped' and connect with username: 'domain\\username', port: '5986' and connection: 'winrm'."
}

TASK [change_servicestate : Change service.] ***********************************
fatal: [lnx_rundeck_machine]: UNREACHABLE! => {"changed": false, "msg": "ssl: the specified credentials were rejected by the server", "unreachable": true}
	to retry, use: --limit @/playfile.retry
```
