### ISSUE TITLE
Issue accessing  nested data structures with a numeric variable attribute/key

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#58761]
##### SUMMARY
Using a variable attribute to access nested data structures confuses ansible when the depth is more than 1.
Let's assume the following nested data structure:
```
pg:
        admin:
                9.6:
                        port: 5432
                        ...
                11:
                        port: 5435
                        ...
        awx:
                port: 5433
                ...
        opennms:
                port: 5434
                ...
```
There is no issue accessing ```pg[pg_cluster].port``` where the variable attribute ```pg_cluster``` can be one of awx|opennms...
However, there is a strange issue accessing ```pg.admin[pg_version].port``` where ```pg_version``` can be 9.6|11.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yaml
?

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/actionmystique/src/Ansible/git-yang-networkop/ansible-101/library']
  ansible python module location = /media/actionmystique/SAMSUNG5-Shared/home/actionmystique/src/Ansible/git-ansible/lib/ansible
  executable location = /home/actionmystique/src/Ansible/git-ansible/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 240
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
controller host: Ubuntu 19.10
```

##### STEPS TO REPRODUCE
**Data structure**:
```
pg:
        admin:
                9.6:
                        data_dir: "/var/lib/postgresql/9.6"
                        ...
                11:
                        data_dir: "/var/lib/postgresql/11"
                        ...
        awx:
                data_dir: "/var/lib/postgresql/9.6/awx"
                ...
```
**Playbook** run with ```operation=pg_install```, ```object=package``` & ```version=11```
```
- name: Performing the PostgreSQL operation "{{ operation }}"
  become: yes
  become_user: root
  hosts:
        - localhost
  tasks:
        - include_role:
                name: postgresql
          vars:
                pg_operation: "{{ operation }}"
                pg_object: "{{ object }}"
                pg_version: "{{ version }}"
                pg_cluster: "{{ cluster | default('main') }}"
```
**Role postgresql/tasks/main.yml**:
```
- name: Performing postgresql "{{ pg_operation }}" "{{ pg_object }}" in "{{ pg_version }}"-"{{ pg_cluster }}" cluster  
  include_tasks: "{{ pg_operation }}.{{ pg_object }}.yml"
```
**Role postgresql/tasks/pg_install.package.yml**
```
...
- name: Creating the data folder on HDD disk
  file:
        follow: yes
        group: "somegroup"
        mode: 0770
        owner: "someowner"
        path: "{{ pg.admin[pg_version].data_dir }}"
        recurse: yes
        state: directory
```

##### EXPECTED RESULTS
Replace "{{ pg.admin[pg_version].data_dir }}" with its value

##### ACTUAL RESULTS
```
 __________________________________________________________
< TASK [postgresql : Creating the data folder on HDD disk] >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: postgresql/tasks/pg_install.package.yml:37
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'11'\n\n...```
```

##### WORKAROUND
Replacing ```"{{ pg.admin[pg_version].data_dir }}"``` with ```"{{ pg.admin[11].data_dir }}"``` works around this issue.
