### ISSUE TITLE
file module not creating directory if symlink exists

### ISSUE THREAD

**Issue by ansensible** [ansible/ansible#58772]
##### SUMMARY

The file module does not create a directory if a symlink exists
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

file
##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

debian stretch

##### STEPS TO REPRODUCE

run the following playbook

```yaml
---
- hosts: all
  gather_facts: no
  tasks:
  - file:
      path: /tmp/dir
      state: directory

  - file:
      path: /tmp/test
      state: link
      src: /tmp/dir
      force: yes

  - file:
      path: /tmp/test
      state: directory
```

##### EXPECTED RESULTS

/tmp/test is a directory

##### ACTUAL RESULTS

/tmp/test is a symlink

```paste below

```
