### ISSUE TITLE
Skipping undefined variables in a loop leads to skipping the whole task

### ISSUE THREAD

**Issue by s-hamann** [ansible/ansible#58797]
##### SUMMARY
I defined a task that processes a list of variables, some of which may be undefined. I use a conditional to skip undefined variables. However, instead of selectively skipping list entries, the whole task may get skipped (depending on some unknown circumstances).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = None
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.6/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.6/ansible
  python version = 3.6.5 (default, Apr 22 2018, 15:17:10) [GCC 6.4.0]
```
I see the same behaviour on latest `devel`.

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Gentoo Linux

##### STEPS TO REPRODUCE
Consider the following playbook:
```yaml
- hosts: localhost
  gather_facts: false
  vars:
    foo: 'Foo'
  tasks:
    - debug:
        msg: "{{ item.value }}"
      loop:
        - value: "{{ foo }}"
          condition: "{{ foo is defined }}"
        - value: "{{ bar }}"
          condition: "{{ bar is defined }}"
      when: "item.value is defined"
```
(`condition` is unused and can be omitted)

##### EXPECTED RESULTS
I expect the first iteration to display "Foo" and the second iteration to be skipped, i.e. something like the following:
```
PLAY [localhost] *****

TASK [debug] *****
ok: [localhost] => (item={'value': 'Foo', 'condition': True}) => {
    "msg": "Foo"
}
skipping: [localhost] => (item={'value': '', 'condition': False}) 

PLAY RECAP *****
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
##### ACTUAL RESULTS
The whole task gets skipped.
```
PLAY [localhost] *****

TASK [debug] *****
skipping: [localhost]

PLAY RECAP *****
localhost                  : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```
##### VARIATIONS
Consider the following slight variation of the above playbook:
```yml
- hosts: localhost
  gather_facts: false
  vars:
    foo: 'Foo'
  tasks:
    - debug:
        msg: "{{ item.value }}"
      loop:
        - value: "{{ foo }}"
          condition: "{{ foo is defined }}"
        - value: "{{ bar | default(None) }}"
          condition: "{{ bar is defined }}"
      when: "item.condition"
```
This works as expected and actually produced the output I pasted above.
I fail to understand the significant difference here.

When omitting the `| default(None)`, the task fails with `'bar' is undefined`. I am unsure, if this is expected behaviour or not. But it is easy enough to work around.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
```yaml
    - debug:
        msg: "{{ item.value }}"
      loop:
        - value: "{{ foo }}"
          condition: "{{ foo is defined }}"
        - value: "{{ bar }}"
          condition: "{{ bar is defined }}"
      when: "item.value is defined"
```

So just to describe what happens here:
1. the evaluation of `loop` fails on `bar` being undefined in ` value: "{{ bar }}"` which means that no `item` var is created,
2. before failing with `bar is undefined` we check to see if the task needs to be executed at all by evaluating the `when` conditional, that results in `False` because `item.value` does not exist at this point as mentioned in 1.,
3. the whole task is skipped as per 2.


The above hopefully explains why the workarounds work:

`- value: "{{ bar | default(None) }}"` - this won't trigger 1. because `bar` is replaced by `None` when undefined

`when: "item.condition"` - this won't be evaluated to false as in 2. because you don't test for `defined` so this fails on `item.condition` being undefined but because `bar is undefined` was a first failure (in 1.) it is printed instead.
