### ISSUE TITLE
Regression in ipaddr functionality in 2.8

### ISSUE THREAD

**Issue by relyt0925** [ansible/ansible#58807]
##### SUMMARY

I believe the functionality of ipaddr might have had a regression in ansible 2.8. This playbook demonstrates the possible regression 
```
- hosts: all
  tasks:
  - name: Hello World!
    set_fact:
      k8s_service_ip_range: "172.21.0.0/16"

  - name: Test ipaddr
    set_fact:
      ip_address_selection: "{{ k8s_service_ip_range|ipaddr('10')|ipaddr('address') }}"
```
In 2.7 `ip_address_selection` will be `172.21.0.10` as expected. In 2.8, the value is false as shown below
```
TASK [Test ipaddr] ********************************************************************************************************************************************************************************
task path: /Users/tlisowski3/gopath/src/github.ibm.com/lisowski/tyler-handy-scripts/ansibletest/testplay2.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "ip_address_selection": false
    },
    "changed": false
}
META: ran handlers
META: ran handlers
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ipaddr

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = None
  configured module search path = ['/Users/tlisowski3/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.1_1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jun 19 2019, 07:38:49) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```
Tylers-MBP-2:ansibletest tlisowski3$ ansible-config dump --only-changed
Tylers-MBP-2:ansibletest tlisowski3$ 
```

##### OS / ENVIRONMENT

Reproducible on every target OS that I tried which includes Mac OSX, RHEL 7, Ubuntu 16.04, and Ubuntu 18.04

##### STEPS TO REPRODUCE

Run the testplaybook using
`ansible-playbook -vvv -i "localhost," -c local testplay2.yml`

The playbook is copied below

```
- hosts: all
  tasks:
  - name: Hello World!
    set_fact:
      k8s_service_ip_range: "172.21.0.0/16"

  - name: Test ipaddr
    set_fact:
      ip_address_selection: "{{ k8s_service_ip_range|ipaddr('10')|ipaddr('address') }}"
```

##### EXPECTED RESULTS

Expected ip_address_selection to equal 172.21.0.10

##### ACTUAL RESULTS
 ip_address_selection equals false

```
TASK [Hello World!] *******************************************************************************************************************************************************************************
task path: /Users/tlisowski3/gopath/src/github.ibm.com/lisowski/tyler-handy-scripts/ansibletest/testplay2.yml:3
ok: [localhost] => {
    "ansible_facts": {
        "k8s_service_ip_range": "172.21.0.0/16"
    },
    "changed": false
}

TASK [Test ipaddr] ********************************************************************************************************************************************************************************
task path: /Users/tlisowski3/gopath/src/github.ibm.com/lisowski/tyler-handy-scripts/ansibletest/testplay2.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "ip_address_selection": false
    },
    "changed": false
}
META: ran handlers
META: ran handlers
```
