### ISSUE TITLE
Cloudformation rollback configuration parameters

### ISSUE THREAD

**Issue by oferziss** [ansible/ansible#58800]
##### SUMMARY
cloudformation module is lacking the rollback configuration parameters. support is already added to boto3 lib.

##### ISSUE TYPE
- Missing Feature 

##### COMPONENT NAME
cloudformation
##### ADDITIONAL INFORMATION
automatic update rollback based on provided cloudwatch alarm arn

```yaml
cloudformation:
      stack_name: <somename>
      state: present
      region: "{{region}}"
      disable_rollback: true
      capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      template_url: <some_s3_url>
      template_parameters:
        SomeParameter: SomeValue
      rollback_configuration: (dict)
        rollback_triggers: (list)
          - Arn: <some_cloudwatch_alarm_arn> (string)
             Type: <Currently, AWS::CloudWatch::Alarm is the only supported resource type> (string)
        MonitoringTimeInMinutes: (integer)
        
```
