### ISSUE TITLE
winrm or requests is not installed: No module named winrm

### ISSUE THREAD

**Issue by rolabrie** [ansible/ansible#58805]
##### SUMMARY

Ansible claims No module named winrm when clearly the module is installed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
winrm

##### ANSIBLE VERSION

```paste below
ansible 2.3.0.0
  config file = /Users/robertlabrie/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/Users/robertlabrie/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target OS is Windows Server 2019 running in AWS with WinRM enabled. My machine is macOS Sierra 10.12.6 and I'm running all of this in a virtualenv
```
(venv) ➜  playbooks git:(master) ✗ python --version
Python 2.7.15

Package       Version
------------- ---------
ansible       2.8.2
asn1crypto    0.24.0
certifi       2019.6.16
cffi          1.12.3
chardet       3.0.4
cryptography  2.7
enum34        1.1.6
idna          2.8
ipaddress     1.0.22
Jinja2        2.10.1
MarkupSafe    1.1.1
ntlm-auth     1.3.0
pip           19.1.1
pycparser     2.19
pywinrm       0.3.0
PyYAML        5.1.1
requests      2.22.0
requests-ntlm 1.1.0
setuptools    41.0.1
six           1.12.0
urllib3       1.25.3
wheel         0.33.4
xmltodict     0.12.0
```
##### STEPS TO REPRODUCE

* Create a virtual env
* pip install "pywinrm>=0.3.0"
* pip install ansible
* Follow the example here https://docs.ansible.com/ansible/2.4/intro_windows.html

```yaml
(venv) ➜  playbooks git:(master) ✗ cat windows.txt
[windows]
windowsbox.example.com

(venv) ➜  playbooks git:(master) ✗ cat group_vars/windows.yml
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit group_vars/windows.yml

ansible_user: Administrator
ansible_password: not_my_actual_password
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

```

##### EXPECTED RESULTS

It says success
##### ACTUAL RESULTS

It says the module is not installed

```paste below
(venv) ➜  playbooks git:(master) ✗ ansible windows -i windows.txt -m win_ping
windowsbox.example.com | FAILED! => {
    "failed": true,
    "msg": "winrm or requests is not installed: No module named winrm"
}

```
