### ISSUE TITLE
include_role: implicit version of apply to avoid double specification: inherit

### ISSUE THREAD

**Issue by mback2k** [ansible/ansible#58802]
##### SUMMARY

It would be great if we could get a second version of `apply` that does not require the keyword contents to be specified again. E.g. if the second version would be called `inherit`, then `inherit: tags` (single value or list) could automatically make the imported role inherit the tags of the include_role task. This would help to avoid the following pattern:

```yaml
- name: Update nginx vhost configuration
  include_role:
    name: nginx
    tasks_from: update-vhost
    apply:
      vars:
        nginx_sitename: ...
      tags:
        - application
        - nginx
  tags:
    - application
    - nginx
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

include_role

##### ADDITIONAL INFORMATION

This option would aid in avoiding redundant tags and other information in include_role tasks.

The previous example would look like this with the feature being implemented:
```yaml
- name: Update nginx vhost configuration
  include_role:
    name: nginx
    tasks_from: update-vhost
    apply:
      vars:
        nginx_sitename: ...
    inherit: tags
  tags:
    - application
    - nginx
```

If this feature were to be implemented it should also be forbidden to specify the same keyword in `apply` and `inherit` as that would be ambiguous.
