### ISSUE TITLE
VMware: vmware_dvs_portgroup: update protgroup options missing

### ISSUE THREAD

**Issue by JoschuaA4** [ansible/ansible#58824]
##### SUMMARY

A portgroup which exist but is not compliant with the specs in the playbook, did not get reconfigured.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_dvs_portgroup

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
is empty
```

##### OS / ENVIRONMENT

The target is a vCenter in Version 6.7.0.13639324.

##### STEPS TO REPRODUCE

Create a port portgroup with promiscuous set to "yes". Afterwards change the setting to yes in the playbook an rerun it.

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Create vlan portgroup 
      vmware_dvs_portgroup:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        portgroup_name: "test-portgroup"
        switch_name: "test-dvs"
        vlan_id: 42
        num_ports: 
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous: no
          forged_transmits: no
          mac_changes: no
        port_policy:
          block_override: no
          ipfix_override: no
          live_port_move: no
          network_rp_override: no
          port_config_reset_at_disconnect: no
          security_override: no
          shaping_override: no
          traffic_filter_override: no
          uplink_teaming_override: no
          vendor_config_override: no
          vlan_override: no
      delegate_to: localhost

```

##### EXPECTED RESULTS

I would expext that existing portgroups that aren't configured as described in the task step, get configured as described.

##### ACTUAL RESULTS

If i run a playbook and the portgroup exist but has not same setting (like promiscuous mode) as described in the playbook, it did not get reconfigured.

```paste below
[username@hostname playbooks]$ ansible-playbook -i ../inventories/aaa-bbb-ccc/hosts vdsportgroup.yml --ask-vault-pass -vvvv
ansible-playbook 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Vault password:
setting up inventory plugins
host_list declined parsing /home/username/ansible-vmware-infrastructure/inventories/aaa-bbb-ccc/hosts as it did not pass it's verify_file() method
script declined parsing /home/username/ansible-vmware-infrastructure/inventories/aaa-bbb-ccc/hosts as it did not pass it's verify_file() method
auto declined parsing /home/username/ansible-vmware-infrastructure/inventories/aaa-bbb-ccc/hosts as it did not pass it's verify_file() method
Parsed /home/username/ansible-vmware-infrastructure/inventories/aaa-bbb-ccc/hosts inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: vdsportgroup.yml ****************************************************************************************************************************************************************************************
Positional arguments: vdsportgroup.yml
become_method: sudo
inventory: (u'/home/username/ansible-vmware-infrastructure/inventories/aaa-bbb-ccc/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
ask_vault_pass: True
timeout: 10
1 plays in vdsportgroup.yml

PLAY [localhost] **************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create vlan portgroup] **************************************************************************************************************************************************************************************
task path: /home/username/ansible-vmware-infrastructure/playbooks/vdsportgroup.yml:5
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7f882e1cd210> for vault_id=default
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: username
<localhost> EXEC /bin/sh -c 'echo ~username && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648 `" && echo ansible-tmp-1562590189.93-110420814975648="` echo /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_dvs_portgroup.py
<localhost> PUT /home/username/.ansible/tmp/ansible-local-119753gmlHOI/tmp8VY4VJ TO /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648/AnsiballZ_vmware_dvs_portgroup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648/ /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648/AnsiballZ_vmware_dvs_portgroup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648/AnsiballZ_vmware_dvs_portgroup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/username/.ansible/tmp/ansible-tmp-1562590189.93-110420814975648/ > /dev/null 2>&1 && sleep 0'
ok: [localhost -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "192.168.0.100",
            "network_policy": {
                "forged_transmits": true,
                "mac_changes": false,
                "promiscuous": false
            },
            "num_ports": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "port_policy": {
                "block_override": false,
                "ipfix_override": false,
                "live_port_move": false,
                "network_rp_override": false,
                "port_config_reset_at_disconnect": false,
                "security_override": false,
                "shaping_override": false,
                "traffic_filter_override": false,
                "uplink_teaming_override": false,
                "vendor_config_override": false,
                "vlan_override": false
            },
            "portgroup_name": "SK-pg1",
            "portgroup_type": "earlyBinding",
            "state": "present",
            "switch_name": "SK-AnsibleTest2",
            "teaming_policy": {
                "inbound_policy": false,
                "load_balance_policy": "loadbalance_srcid",
                "notify_switches": true,
                "rolling_order": false
            },
            "username": "domain\\username",
            "validate_certs": false,
            "vlan_id": "42",
            "vlan_trunk": false
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
