### ISSUE TITLE
URI module can not use body and src togheter. binary file + another body parameter can not be POSTed

### ISSUE THREAD

**Issue by lukasmrtvy** [ansible/ansible#58823]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

uri

##### ANSIBLE VERSION

```paste below
2.8.1
```

##### STEPS TO REPRODUCE

```yaml
- name: Upload content
  uri:
    url: "{{ proxmox.api.host }}/api2/json/nodes/{{ node }}/storage/{{ storage }}/upload"
    method: POST
    headers:
      Cookie: "PVEAuthCookie={{ auth.json.data.ticket }}"
      CSRFPreventionToken: "{{ auth.json.data.CSRFPreventionToken }}"
      Content-Type: "multipart/form-data"
    return_content: yes
    body_format: form-urlencoded
    body:
      content: "iso"
    src: "{{ file_location }}"
```

##### EXPECTED RESULTS

- file (`file_location`) is uploaded and with another body parameter `content=iso`

For example -> curl can handle it:
```yaml
- name: Upload content
  shell: 'curl  -X POST "{{ proxmox.api.host }}/api2/json/nodes/{{ node }}/storage/{{ storage }}/upload" \
                -b "PVEAuthCookie={{ auth.json.data.ticket }}" \
                -H "CSRFPreventionToken: {{ auth.json.data.CSRFPreventionToken }}" \
                -H "Content-Type: multipart/form-data" \
                --form "content=iso" \
                --form "filename=@{{ file_location }}" \
               '
```
##### ACTUAL RESULTS

- `src` parameter cannot be used with `body` parameter togheter
- its not possible to use `filename=@{{ file_location }}` in body

EDIT:
```yaml
- name: Upload content
  uri:
    url: "{{ proxmox.api.host }}/api2/json/nodes/{{ node }}/storage/{{ storage }}/upload"
    method: POST
    headers:
      Cookie: "PVEAuthCookie={{ auth.json.data.ticket }}"
      CSRFPreventionToken: "{{ auth.json.data.CSRFPreventionToken }}"
      Content-Type: "multipart/form-data"
    return_content: yes
    body_format: form-urlencoded
    body:
      content: "iso"
      filename: "{{ lookup('file', file_location ) }}"
```
results in 
```
An unhandled exception occurred while running the lookup plugin 'file'. Error was a <type 'exceptions.UnicodeDecodeError'>, original message: 'utf8' c
odec can't decode byte 0xfb in position 3: invalid start byte
```
