### ISSUE TITLE
s3_lifecycle is deleting the prefix itself

### ISSUE THREAD

**Issue by AnthonyWC** [ansible/ansible#58833]
##### SUMMARY
s3_lifecycle module is applying the lifecycle rule to the prefix itself; which results in the prefix itself getting deleted after the files inside the prefix are deleted.  This behavior seems to be a bug?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
ansible-playbook 2.8.0
  config file = /ansible/playbook/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Feb  6 2019, 01:56:13) [GCC 8.2.0]
```

##### COMPONENT NAME
s3_lifecycle

##### CONFIGURATION
```
- name: Life cycle
  s3_lifecycle:
    name: foobar
    expiration_days: 3
    prefix: prefix/
    status: enabled
    state: foo
```

##### EXPECTED RESULTS
The prefix(es) to remain after the files are removed.

##### ACTUAL RESULTS
The prefix(es) are themselves removed after the files are removed.
