### ISSUE TITLE
gcp_storage_object not using environment variables per documentation

### ISSUE THREAD

**Issue by jpreed2** [ansible/ansible#58831]
##### SUMMARY
According to the documentation, you can set the GCP_SERVICE_ACCOUNT_FILE and GCP_AUTH_KIND environment variables in lieu of the service_account_file and auth_kind parameters.  However, these environment variables seem to be ignored by the gcp_storage_object module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_storage_object

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /var/ansible/gcp/ansible.cfg
  configured module search path = [u'/home/jim_reed_shipwire_com/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
CACHE_PLUGIN(/var/ansible/gcp/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/var/ansible/gcp/ansible.cfg) = /tmp
CACHE_PLUGIN_TIMEOUT(/var/ansible/gcp/ansible.cfg) = 86400
DEFAULT_GATHERING(/var/ansible/gcp/ansible.cfg) = smart
DEFAULT_PRIVATE_KEY_FILE(/var/ansible/gcp/ansible.cfg) = /etc/ansible/ssh-key-ansible-sa
DEFAULT_REMOTE_USER(/var/ansible/gcp/ansible.cfg) = xxx
HOST_KEY_CHECKING(/var/ansible/gcp/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/var/ansible/gcp/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Host: CentOS 7
Target: CentOS 6

##### STEPS TO REPRODUCE
Set environment variables as specified in documentation for gcp_storage_object:
```
[jim_reed_shipwire_com@ansible-01.infra gcp]$ env | grep GCP
GCP_AUTH_KIND=serviceaccount
GCP_SERVICE_ACCOUNT_FILE=/etc/ansible/gcp-auth.json
```

```yaml
- name: Install latest version of User Action Logger
  connection: local
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: 'Download latest {{ service.name }}'
    gcp_storage_object:
      action: download
      project: xxx
      overwrite: yes
      bucket: myBucket
      src: artifacts/go/myBinaryFile
      dest: '/tmp/{{ service.targetFile }}'
```

##### EXPECTED RESULTS
File is downloaded from Google Storage.

##### ACTUAL RESULTS
Error received:

```paste below
fatal: [worker-perf-01.prod]: FAILED! => {"changed": false, "msg": "Credential type 'None' not implemented"}
```

When service_account_file and auth_kind parameters are provided it works fine.
