### ISSUE TITLE
gcp_storage_object is not url encoding object path

### ISSUE THREAD

**Issue by jpreed2** [ansible/ansible#58830]
##### SUMMARY
When specifying an object that is contained within a folder to be downloaded, the path is not urlencoded before sending to the Google REST API.  As a result, an error is returned stating the object is not found.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_storage_object

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /var/ansible/gcp/ansible.cfg
  configured module search path = [u'/home/jim_reed_shipwire_com/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
CACHE_PLUGIN(/var/ansible/gcp/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/var/ansible/gcp/ansible.cfg) = /tmp
CACHE_PLUGIN_TIMEOUT(/var/ansible/gcp/ansible.cfg) = 86400
DEFAULT_GATHERING(/var/ansible/gcp/ansible.cfg) = smart
DEFAULT_PRIVATE_KEY_FILE(/var/ansible/gcp/ansible.cfg) = /etc/ansible/ssh-key-ansible-sa
DEFAULT_REMOTE_USER(/var/ansible/gcp/ansible.cfg) = xxx
HOST_KEY_CHECKING(/var/ansible/gcp/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/var/ansible/gcp/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Host: CentOS 7
Target: CentOS 6

##### STEPS TO REPRODUCE
```yaml
- name: Install latest version of User Action Logger
  connection: local
  hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: 'Download latest {{ service.name }}'
    gcp_storage_object:
      action: download
      auth_kind: serviceaccount
      service_account_file: /etc/ansible/gcp-auth.json
      project: xxx
      overwrite: yes
      bucket: myBucket
      src: artifacts/go/myBinaryFile
      dest: '/tmp/{{ service.targetFile }}'
```

##### EXPECTED RESULTS
The file should be downloaded from Google Storage.

##### ACTUAL RESULTS
```paste below
fatal: [worker-perf-01.prod]: FAILED! => {"changed": false, "msg": "File does not exist in bucket"}
```

If I urlencode the src object then it works.  i.e.
```yaml
      src: artifacts%2Fgo%2FmyBinaryFile
```
