### ISSUE TITLE
reboot module hangs with OpenVZ hosts

### ISSUE THREAD

**Issue by mvorisek** [ansible/ansible#58868]
##### SUMMARY
Currently there is some issue with the reboot module with OpenVZ hosts. The reboot command is executed correctly, all hosts reboots, but the Ansible reboot tasks hangs.

If exactly the same playbook is run on KVM or native host, it finish without any issues.

It should be hot fixed in 2.7+ branches.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
reboot module

##### ANSIBLE VERSION
2.7

##### CONFIGURATION
Debian 9.9 / Ansible 2.8

##### OS / ENVIRONMENT
Debian 9.9

##### STEPS TO REPRODUCE
Trigger this reboot handler on OpenVZ hosts
```
- name: Reboot system
  reboot:
    reboot_timeout: 1200
    post_reboot_delay: 5
    connect_timeout: 2
  listen: handler_reboot
```

##### EXPECTED RESULTS
Reboot is executed and once the host is back online, task is marked as changed and the execution of the playbook continues.

##### ACTUAL RESULTS
```
...
RUNNING HANDLER [shared_handlers : Reboot system] ********
```
(and no more output, the Ansible playbook hangs)
