### ISSUE TITLE
Inconsistency with import_tasks when using multiple conditionals with variables

### ISSUE THREAD

**Issue by dop-amine** [ansible/ansible#58879]
##### SUMMARY

Inconsistent behavior when using more than one conditional to determine whether to import_task. 

If using multiple `when !=` it seems that it must be separated into multiple lines:
The method below does not work:

`when: variable != test1 or test2`

The method below works:

```
when:
    - variable != test1
    - variable != test2
```

When using `when ==` for multiple variables, sometimes it works when separated and other times it works when put in the same line. I haven't figured out why.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

import_task

##### ANSIBLE VERSION

```
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/amine/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS Mojave
10.14.5 (18F132)

##### STEPS TO REPRODUCE

main.yml:

```
---
- name: Test issue
  hosts: web
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml

  tasks:

    - import_tasks: tasks/task1.yml
      when:
        - server_name != "test1"
        - server_name != "test2"
        - server_name != "test3"
   
    #method below does not work:
    #- import_tasks: tasks/task2.yml
    #  when: server_name != "test1" or "test2" or "test3"

    #from what I can tell, method below works for test2 and test3
    - import_tasks: tasks/task2.yml
      when: server_name == "test1" or "test2" or "test3"

    # versus the method below which works for test1 but not test2 or test3
    #- import_tasks: tasks/task2.yml
    #   when: 
           - server_name == "test1" 
           - server_name == "test2"
           - server_name == "test3"
```

vars.yml:

```
---
server_name: test1
# I change the variable depending on which server I am provisioning
```

##### EXPECTED RESULTS

I expect import_tasks to run when variable equals or does not equal one of the specified variables and skip the task if it does not.

##### ACTUAL RESULTS

Described in the example. Depending on the method it skips sometimes when it shouldn't and vice versa.

No error message. It just skips the task or runs it.
