### ISSUE TITLE
Keep role names in hostvars

### ISSUE THREAD

**Issue by eugene-bright** [ansible/ansible#58884]
##### SUMMARY
If a role attached to the host group then every host in this group must have this role name in the `hostvars[inventory_hostname].roles` list.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`hostvars`

##### ADDITIONAL INFORMATION

Playbook may affect several host groups in which case all affected hosts appear in `hostvars` regardless of their roles. Cluster servers configuration templates require exact list of servers marked by specific role.

Inventory:
```yaml
all:
  children:
    core:
      hosts:
        eugene1:
        eugene2:
  hosts:
    homeserver:
```

Playbook:
```yaml
- hosts: core
  user: root
  roles:
    - my_role

- hosts: homeserver
  user: root
```

Template in `my_role`:
```
{% for host in hostvars %}
    {{- host }}
{% endfor %}
```

Produced output (for hosts marked my `my_role`):
```
eugene1
eugene2
homeserver
```

My target is to get only names marked by  role `my_role`:
```
eugene1
eugene2
```

For now I filter hosts by testing role-specific variable presence. It's very complicated as role default variables are not present in `hostvars` due too #6189 (still actual for `ansible-2.8.2`).

Roles list could help do correct filtering a lot.
