### ISSUE TITLE
ansible-galaxy collection doesn't support 'cloud_platforms'

### ISSUE THREAD

**Issue by rambleraptor** [ansible/ansible#58892]
##### SUMMARY

Ran the new "ansible-galaxy collection" to build a collection. The galaxy.yml contained the "cloud_platforms" option (which was valid under mazer) and doesn't seem to be supported by ansible-galaxy

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Run ansible-galaxy collection build with the following galaxy.yml

```yaml
namespace: rambleraptor
name: another_google_role
version: 0.1.0
license:
  - Apache-2.0
description: A test collection. Do not use.
repository: null
documentation: null
homepage: null
issues: null
authors:
  - Google
tags: ["google", "googlecloud", "gcp"]
cloud_platforms: ["google"]
license_file: LICENSE
readme: README.md
dependencies: {}

```

##### EXPECTED RESULTS

```
Created collection for rambleraptor.another_google_role at /Users/alexstephen/mazer_test/rambleraptor/another_google_Role/rambleraptor-another_google_role-0.1.0.tar.gz
```

##### ACTUAL RESULTS

```paste below
 [WARNING]: Found unknown keys in collection galaxy.yml at '/Users/alexstephen/mazer_test/rambleraptor/another_google_Role/galaxy.yml': cloud_platforms

Created collection for rambleraptor.another_google_role at /Users/alexstephen/mazer_test/rambleraptor/another_google_Role/rambleraptor-another_google_role-0.1.0.tar.gz

```
