### ISSUE TITLE
Unable to elevate privilege to enable mode on cisco gears

### ISSUE THREAD

**Issue by jason87686667** [ansible/ansible#58910]
##### SUMMARY

We have a non-default prompt to get into privileged mode, we will met unable to elevate privilege to enable mode, at prompt [None] with error: timeout trying to send command: enable issue.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible ios_config
##### ANSIBLE VERSION

```paste below
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jason/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jason/.local/lib/python2.7/site-packages/ansible
  executable location = /home/jason/.local/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
default
```

##### OS / ENVIRONMENT

Ubuntu 19.04

##### STEPS TO REPRODUCE

```yaml
- name: show run
  hosts: switches
  gather_facts: false

  tasks:
    - name: add an acl
      ios_config:
        lines: 
           - ip access-list standard 7 permit 172.31.200.0 0.0.0.255
```

##### ACTUAL RESULTS

Our cisco gear has a non-default prompt to elevate privilege to enable mode, it is not only password, it also include some info cause it is with TACACS+ authentication so we can tell now we are using TACACS+ or local to authenticate. 

And there is no issue with ios_command module. 

```paste below

XXX-4510-3Fb>en
HCC password: 
XXX-4510-3Fb#

fatal: [sw1]: FAILED! => {"msg": "unable to elevate privilege to enable mode, at prompt [None] with error: timeout trying to send command: enable"}

```
