### ISSUE TITLE
Mount module resets permissions and ownership

### ISSUE THREAD

**Issue by LucaIcaro** [ansible/ansible#58916]
##### SUMMARY
A task that uses the `mount` module resets the permissions on the mount folder. I've found no option to avoid this.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Mount

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = None
  configured module search path = [u'/home/luca/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/luca/.virtualenvs/ansible-latest/local/lib/python2.7/site-packages/ansible
  executable location = /home/luca/.virtualenvs/ansible-latest/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION
Standard one (`ansible-config dump --only-changed` returns nothing)

##### OS / ENVIRONMENT
Ubuntu 18 LTS

##### STEPS TO REPRODUCE

```
- name: setup mountpoint
  file:
    state: directory
    path: /mnt/test
    owner: root
    group: hadoop
    mode: 0770

- name: Mount Volume
  mount:
    state: mounted
    path:  /mnt/test
    src: "localhost:test_vol"
    fstype: glusterfs
    opts: "defaults,_netdev"
```

##### EXPECTED RESULTS
The folder /mnt/test should be root:hadoop with permissions at 0770

##### ACTUAL RESULTS

```
ls -ld /mnt/test
drwxr-x---. 3 root root 4096 Jul 10 09:09 /mnt/volume01

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/mount.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/mount.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
As far as I know, the `mount` module is not setting any directory permissions. The module only executes the `mount` command. I might be the `mount` command changing it. Please could you run `mount` command from the command line to see if the permission changes?

```bash
ls -ld /mnt/test
chmod 0770 /mnt/test
chown root:hadoop /mnt/test
mount -t glusterfs -o defaults,_netdev localhost:test_vol /mnt/test
ls -ld /mnt/test
```

**Comment by LucaIcaro** [comment]
> As far as I know, the `mount` module is not setting any directory permissions. The module only executes the `mount` command. I might be the `mount` command changing it. Please could you run `mount` command from the command line to see if the permission changes?

I've done this, and the mount command does not change permissions

```
[root@hadoop01 ~]# chmod 0770 /mnt/test
[root@hadoop01 ~]# chown root:hadoop /mnt/test
[root@hadoop01 ~]# mount -t glusterfs -o defaults,_netdev localhost:test_vol /mnt/test
[root@hadoop01 ~]# ls -ld /mnt/test
drwxrwx---. 3 root hadoop 4096 Jul 10 09:09 /mnt/test
```

**Comment by jtyr** [comment]
The `mount` module only creates the director if it didn't exist. If you run your playbook multiple times, does it always set the `root:root` permissions on the directory?

**Comment by LucaIcaro** [comment]
No, just on the first run. Starting from the second run, the permissions are right.

**Comment by jtyr** [comment]
It looks like the directory didn't exist and the `mount` module created it with the default permissions.

**Comment by LucaIcaro** [comment]
I've tried to pause to see the exact behaviour of the `file` module, and it creates the folder correctly, with the right permissions. It's the `mount` module who change them.

**Comment by jtyr** [comment]
Please unmount and remove the directory and then use the following playbook:

```yaml
---

- hosts: all
  connection: local
  gather_facts: no
  become: yes
  vars:
    src: localhost:test_vol
    fstype: glusterfs
    dest: /tmp/xxx
    dest_owner: root
    dest_group: hadoop
    dest_mode: "0770"
    opts: defaults,_netdev
    fstab: /tmp/fstab
  tasks:
    - stat:
        path: "{{ dest }}"
      register: xxx

    - debug:
        msg: >-
          {{ xxx.stat.uid ~ ':' ~ xxx.stat.gid ~ ' (' ~ xxx.stat.mode ~ ')'
            if xxx.stat.exists
            else
          '?:? (?)' }}

    - file:
        path: "{{ dest }}"
        state: directory
        owner: "{{ dest_owner }}"
        group: "{{ dest_group }}"
        mode: "{{ dest_mode }}"

    - stat:
        path: "{{ dest }}"
      register: xxx

    - debug:
        msg: >-
          {{ xxx.stat.uid ~ ':' ~ xxx.stat.gid ~ ' (' ~ xxx.stat.mode ~ ')'
            if xxx.stat.exists
            else
          '?:? (?)' }}

    - copy:
        path: "{{ fstab }}"
        content: >
          {{ src }} {{ dest }} {{ fstype }} {{ opts }} 0 0
      when: false

    - mount:
        src: "{{ src }}"
        path: "{{ dest }}"
        state: mounted
        fstype: "{{ fstype }}"
        opts: "{{ opts }}"
        fstab: "{{ fstab }}"

    - stat:
        path: "{{ dest }}"
      register: xxx

    - debug:
        msg: >-
          {{ xxx.stat.uid ~ ':' ~ xxx.stat.gid ~ ' (' ~ xxx.stat.mode ~ ')'
            if xxx.stat.exists
            else
          '?:? (?)' }}
```

by running this command:

```shell
ansible-playbook -i localhost, site.yaml
```

I have tested the above and it keeps the permissions during the first and any consecutive run.
