### ISSUE TITLE
module azure_rm_postgresqlserver: support for storageProfile

### ISSUE THREAD

**Issue by Sispheor** [ansible/ansible#58929]
##### SUMMARY
On Azure, when creating a managed Postgres server, the "[Backup redundancy options](https://docs.microsoft.com/en-us/azure/postgresql/concepts-backup)" need to be set during the creation. (even if it'sa part of the Update API, I tried, we cannot update it)

It would be nice to handle the SotrageProfile part. [See the doc here](https://docs.microsoft.com/en-us/rest/api/postgresql/servers/update#storageprofile)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_postgresqlserver

##### ADDITIONAL INFORMATION
Add backup redundancy flag

```yaml
- name: Create (or update) managed PostgreSQL server
  azure_rm_postgresqlserver:
    resource_group: "{{ resource_group }}"
    name: "{{ postgres_server_name }}"
    sku:
      name: GP_Gen5_2
    location: "{{ location }}"
    storage_mb: "{% if is_prod %}100000{% else %}5120{% endif %}"
    geo_redundant_backup: "{% if is_prod %}yes{% else %}no{% endif %}"
    enforce_ssl: yes
    admin_username: "{{ postgres_admin_username }}"
    admin_password: "my_password"
    version: "{{ postgres_server_version }}"
  tags: ["postgres"]
```

ping @zikalino
