### ISSUE TITLE
first_found error message recommends deprecated usage

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#58942]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
with_first_found lookup plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jeff.geerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jul 23 2018, 21:27:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = /tmp/ansible-ssh-%%h-%
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = True
DEFAULT_ROLES_PATH(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = [u'/Users/jeff.geerling/Drop
DEFAULT_STDOUT_CALLBACK(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-pi/ansible.cfg) = False
```

##### OS / ENVIRONMENT
macOS 10.14

##### STEPS TO REPRODUCE

Add a task that uses with_first_found:

```yaml
    - name: Include non-existent-file.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - non-existent-file.yml
      tags: ['always']
```

Get error message:

```
TASK [Include non-existent-file.yml if it exists.] ************************************************************************
fatal: [10.0.100.136]: FAILED! => 
  msg: 'No file was found when using first_found. Use the ''skip: true'' option to allow this task to be skipped if no files are found'
```

Change task to use recommended option:

```
    - name: Include non-existent-file.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - non-existent-file.yml
          skip: true
      tags: ['always']
```

```
TASK [Include non-existent-file.yml if it exists.] ************************************************************************
[DEPRECATION WARNING]: Use errors="ignore" instead of skip. This feature will be removed in version 2.12. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

##### EXPECTED RESULTS
Documentation for failed task includes a non-deprecated usage recommendation.

##### ACTUAL RESULTS
Documentation for failed task recommends a deprecated parameter which, when used, throws a deprecation warning.

Related to: https://github.com/ansible/ansible/issues/56713 (I'm not sure why that particular issue was closed, though.

**Comment by geerlingguy** [comment]
Also—the syntax below does not work:

```
    - name: Include non-existent-file.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - non-existent-file.yml
          errors: ignore
      tags: ['always']
```

I tried adding `errors: ignore` to every level of that task and could not get it to not break Ansible's parser. How do I add `errors: ignore`?

**Comment by sivel** [comment]
Honestly, I just looked through this, and I might be wrong, but you cannot pass `errors` when using `with_` syntax.

It would only be possible when using `lookup('first_found', ...)` or `q/query`.

Using `with_` syntax bypasses `Templar._lookup`, and directly executes the `run` method of the lookup plugin.  `errors` is implemented in `Templar._lookup`.

If we wanted this to work with `with_` syntax, we would have to use `Templar._lookup` to execute the lookup plugin instead, and parse out things like `errors` and pass that to `_lookup`.

**Comment by eengstrom** [comment]
As noted by @geerlingguy, the documentation needs to be updated to give an example of proper usage.  Since the `with_first_found` is apparently just syntactic sugar around the `first_found` lookup function, I took @sivel's comments and experimented a bit further.  After my experiments, I think the new, non-deprecated expected usage behavior is not only confusing, due to the documentation being out of date, but also lacks the feedback I came to expect from the `skip: true` - that is, using `errors=ignore` does **NOT** mark the task as `skipped`.    For example:

```
    # Previous behavior; works, but deprecated 'skip: true' warning
    - name: with_first_found - DEPRECATED warning
      debug:
        msg: "{{ item }}"
      with_first_found:
        - files:
          - doesnotexist.yml
          - doesnotexisteither.yml
          skip: true
      tags: deprecated
```

Output:
```
TASK [with_first_found - DEPRECATED warning] ***************************************
[DEPRECATION WARNING]: Use errors="ignore" instead of skip. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY RECAP *************************************************************************
localhost: ok=0  changed=0  unreachable=0  failed=0  skipped=1  rescued=0  ignored=0
                                                     ^^^^^^^^^
```

Ignoring the **DEPRECATION WARNING**, using `skip: true` gives proper feedback that the task was skipped.  This is in contrast to what I presume to be expected usage without `skip: true`, instead using the `lookup('first_found',...)` option, as in:

```
    # function version; works, but task not marked as skipped
    - name: first_found lookup function, with errors='ignore'
      debug:
        msg: "{{ lookup('first_found', lookhere, errors='ignore') }}"
      vars:
        lookhere:
          files:
            - doesnotexist.yml
            - doesnotexisteither.yml
      tags: fn_w_ignore
```

Output:
```
TASK [first_found lookup function, with errors='ignore'] ***************************
ok: [localhost] => {}

PLAY RECAP *************************************************************************
localhost: ok=1  changed=0  unreachable=0  failed=0  skipped=0  rescued=0  ignored=0
           ^^^^
```

**WAIT A SEC...** - Status of the task is **OK**?  Really?  Where's my indication that _either_ an error was ignored and we proceeded anyway (like `ignore_errors: true`), or that the task was skipped?  I got neither!  That's seems wrong.

However, in the interest of finding a non-deprectated solution that **properly** (IMO) marks the task skipped, I have settled on this, more verbose, version:

```
    # function with ignore; works, and skip if item is not defined.
    - name: first_found lookup function, with errors='ignore' and skip if not defined
      debug:
        msg: "{{ lookup('first_found', lookhere, errors='ignore') }}"
      vars:
        lookhere:
          files:
            - doesnotexist.yml
            - doesnotexisteither.yml
      when:
        - item is defined
      tags: fn_w_when
```

... with output as I previously expected:

```
TASK [first_found lookup function, with errors='ignore' and skip if not defined] ****************************************
skipping: [localhost]

PLAY RECAP *************************************************************************
localhost: ok=0  changed=0  unreachable=0  failed=0  skipped=1  rescued=0  ignored=0
                                                     ^^^^^^^^^
```

Sadly, it is much more complicated to read than the `with_first_found` version.  

Is there any chance of retaining the functionality of the `with_first_found` syntactic sugar with something like 'skip: true' without warnings?  That would be ideal.   Or better yet, how about adding a `default: VALUE` option, as in:

```
    # Proposed 'default: VALUE' version
    - name: 'with_first_found - "default: VALUE" suggestion'
      debug:
        msg: "{{ item }}"
      with_first_found:
        - files:
          - doesnotexist.yml
          - doesnotexisteither.yml
          default: ""
      when:
        - item | length > 0
      tags: proposed
```

Or perhaps better yet, return an undefined value if the `default: ` clause is not defined, then could use `| d(omit)` or `| d("some-other-value.yml")` behavior.

Sorry, I know I've gone too far afield, suggesting future behavior in a bug report.  Where do I make proposals for future behavior?

**Comment by eengstrom** [comment]
Actually, it's a bit worse than I had hoped.  When using `include_vars` (or similar, I expect) in a role, I had to explicitly tell the lookup function `first_found` where to look:

```
- name: Gather OS specific variables
  include_vars: "{{ osvars }}"
  vars:
    osvars_:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - ../vars
    osvars: "{{ lookup('first_found', osvars_, errors='ignore') }}"
  when:
    - (osvars | length > 0)
```

If I did not specify the paths to examine, no file would be found.  I don't understand the difference between the `with_first_found` and `lookup(first_found,...)`, and [the documentation on `loop` v. `with_*`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#comparing-loop-and-with) doesn't help.  Where is the `with_*` rewriting magic documented?  

Perhaps someone else can come up with a better solution?
