### ISSUE TITLE
win_dns_client should skip or warn on not connected interfaces instead of fail

### ISSUE THREAD

**Issue by blindrood** [ansible/ansible#58958]
##### SUMMARY
If I provide asterisk as adapter_names, script tries to set dns entries on all interfaces, even those disabled or in state different than connected. This results with errors like:
`Unhandled exception while executing module: Set-DnsClientServerAddressLegacy: Error calling SetDNSServerSearchOrder, code 84)`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_client module

##### ADDITIONAL INFORMATION
This is the case on 2008R2 (using legacy functions)
Probably adding filter "NetConnectionState=2" is easiest but I'm not sure if other states should be supported as well.

```yaml
---
- name: Configure DNS client settings
  hosts: all
  tasks:
    - name: DNS setup
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses: "{{ win_dns_server_list }}"
```
