### ISSUE TITLE
vmware_guest:  dns_suffix list is not configured correctly on Amazon Linux 2

### ISSUE THREAD

**Issue by keirazhang** [ansible/ansible#58950]
##### SUMMARY

When dns_suffix is set with a list of more than 1 search domains, they couldn't be written to /etc/resolv.conf successfully on Amazon Linux 2 after customization.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
  config file = /home/qiz/workspace/Ansible/testcase/ansible.cfg
  configured module search path = [u'/home/qiz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/qiz/workspace/github/ansible/lib/ansible
  executable location = /home/qiz/workspace/github/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_SSH_RETRIES(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = 5
DEFAULT_BECOME(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = [u'/home/qiz/workspace/Ansible/testcase/plugin'
DEFAULT_HOST_LIST(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = [u'/home/qiz/workspace/Ansible/testcase/hosts']
DISPLAY_SKIPPED_HOSTS(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = False
HOST_KEY_CHECKING(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/qiz/workspace/Ansible/testcase/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Amazon Linux 2

##### STEPS TO REPRODUCE

```
Before doing customization on the existing VM, comment or remove line "disable_vmware_customization: false" in /etc/cloud/cloud.cfg.

    - name: Customize guest with DHCP IP
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: "{{ valid_cert | default(False) }}"
        folder: "{{ folder | default('/') }}"
        name: "{{ vm_name }}"
        networks:
        - name: "VM Network"
          type: "dhcp"
        customization:
          existing_vm: True
          dns_servers:
            - "192.168.1.1"
            - "192.168.2.1"
          dns_suffix:
            - "test1.com"
            - "test2.com"
          domain: "test1.com"
          hostname: "gosc-dhcp-vm-01"
          timezone: "Europe/Berlin"
          hwclockUTC: True
        wait_for_customization: True
        wait_for_ip_address: True
      delegate_to: localhost
```

##### EXPECTED RESULTS

/etc/dhcp/dhclient.conf should be
supersede domain-search "test1.com", "test2.com";
supersede domain-name-servers 192.168.1.1,192.168.2.1;

/etc/resolv.conf should be
; generated by /usr/sbin/dhclient-script
search test1.com. test2.com.
nameserver 192.168.1.1
nameserver 192.168.2.1

##### ACTUAL RESULTS

[root@gosc-dhcp-vm-01 dhcp]# cat /etc/dhcp/dhclient.conf 
supersede domain-search "test1.com test2.com";
supersede domain-name-servers 192.168.1.1,192.168.2.1;

[root@gosc-dhcp-vm-01 dhcp]# cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
search eng.vmware.com
nameserver 192.168.1.1
nameserver 192.168.2.1

By checking https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1600, all search domains in dns_suffix list was joined as a string like "test1.com test2.com", but this can not be successfully parsed from customization spec. Finally, we got 'DNS|SUFFIX|1' = 'test1.com test2.com', not 'DNS|SUFFIX|1' = 'test1.com' and  'DNS|SUFFIX|2' = 'test2.com' for the customization.
