### ISSUE TITLE
Improve machinectl's become plugin

### ISSUE THREAD

**Issue by HugoDelval** [ansible/ansible#58962]
##### SUMMARY
As of today, ansible does not provide a way to comunicate with systemd-nspawn's container.

An easy way to do this would be to add an option here: https://github.com/ansible/ansible/blob/33d2728879f8655337bc2157b723f1efa3a1920a/lib/ansible/plugins/become/machinectl.py#L84-L87 Something like :

```python
container = self.get_option('container') or ''
return '%s -q shell %s %s@%s %s' % (become, flags, user, container, cmd)
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
become/machinectl

##### ADDITIONAL INFORMATION
This would allow users to connect to a remote server via ssh, then interact with the systemd-nspawn machines running on the host

If that's ok with you, I can write the PR.

/cc @jos-b @bcoca @felixfontein

**Comment by jos-b** [comment]
I have found it is currently possible and have done so by specifying additional flags through `become_flags`. The following playbook demonstrates how I have achieved this:
```yaml
- hosts: vps
  become: yes
  become_user: root
  become_method: machinectl
  become_flags: "-M buildContainer"
  tasks:
      - name: Get hostname
        shell: hostname
        register: hostname

      - name: Print hostname
        debug:
            msg: "Hostname: {{hostname.stdout}}"
```

It is not as simple as I first believe because I think it is required that the containers must be able to execute the ansible python files. To do this I have added a `Bind` directive in my containers systemd.nspawn file to mount `/home/joseph/.ansible` to the container so that ansible can still work.
