### ISSUE TITLE
junos_user: wrong SSH-key assignment in aggregate mode

### ISSUE THREAD

**Issue by kr3ator** [ansible/ansible#58978]
##### SUMMARY

When adding multiple users with SSH keys with the aggregate option the first user gets created with all SSH keys of all users on the list. Rest of the users are created without their SSH key.

The bug was introduced in this commit: "junos_user add condition when user = root (#53111)".

To fix this bug line 227 must be replaced with line 228.  The conditional in line 227 prevents 'authentication' subelement of XML tree to be closed after first user iteration. Therefore, each new user doesn't get his own 'authentication' subelement and his key is being written to the first user's 'authentication' subelement.

EDIT: Same bug has been introduced for the 'encrypted_password' parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_user
##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[ansible@ansible ~]$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /home/ansible/.ansible/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/ansible/.ssh/id_rsa
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
NETWORK_GROUP_MODULES(/etc/ansible/ansible.cfg) = [u'eos', u'nxos', u'ios', u'iosxr', u'junos', u'vyos']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target device is vQFX runnig Junos 15.1X53-D60.4.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: no
  remote_user: "ec2-user"
  connection: netconf
  vars:
    ansible_network_os: junos
  vars_files:
    - "accounts.yml"
  tasks:
    - name: Add users
      junos_user:
        aggregate: "{{ configuration.vsrx_users }}"
```
```yaml
accounts.yml:
configuration:
  vsrx_users:
    - name: user1
      role: super-user
      sshkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8RWbIGKsIKJH5Id8oZ1lhgNnml1c/kB4qEsddwW4EzsnE0jtI9v2mBH5YCkd4TCirjKgxi7JpnEA78vm4iWgXNvWB9l20yjhXwAT1GKDYMvFUoUUhFpM34AfGRj+txWrhbS9Ao7kyiEUtQRCa8O7MPK1WRcgDFZkgn2xlnhZn3+l2+cq8Hea+dmfSmvX5bALljInWfWr899xLTgxACAm6Tt6UK5SCTR8NxKi/mge2LneSw1696ZCJKzGCSAW7RXj9OPXwlZs6HssmzgW3WWSxOKDExptKCk+/PCm3AroEWgfb6YWULCtvUfqOwxU/qy5d332J03phLDzSSS7jZ5Dj'
    - name: user2
      role: super-user
      sshkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA5mCmNCuSSRaUpaxOHm73pG8s6bATCGz5YYgDLGaXPe00QGqjlZ2T0Zileb7YdglESmih10vi3XFXsVQ+JTc9nNNawQdWmrdA+9G9UTipR53yZc0vQlCyMshtLB2NqdSUvzBnSf86zAKCzhnaRu5gD/UUbzikeaD3PDixi3hVSmWz4ziJnfwmtfCEUmbX+QeB1u2feltImx91G9itmU/CMBG2rfhpOSz3Ck/MCnfTlSCIjXS9C0HPzmBpiBbBwlKbZuG6NbE9aDgiYkPaB7JHi4Q/9yTjFwo8xCzwPDCbyO8yu2PVwDxOXPxkQTkuTjsrsvSlk3/FRCm19rEPwWCLCQ=='
 ```

##### EXPECTED RESULTS

The following account structure should be created on the Junos device.
```
system {
    login {
        user user1 {
            uid 2002;
            class super-user;
	    authentication {
                ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8RWbIGKsIKJH5Id8oZ1lhgNnml1c/kB4qEsddwW4EzsnE0jtI9v2mBH5YCkd4TCirjKgxi7JpnEA78vm4iWgXNvWB9l20yjhXwAT1GKDYMvFUoUUhFpM34AfGRj+txWrhbS9Ao7kyiEUtQRCa8O7MPK1WRcgDFZkgn2xlnhZn3+l2+cq8Hea+dmfSmvX5bALljInWfWr899xLTgxACAm6Tt6UK5SCTR8NxKi/mge2LneSw1696ZCJKzGCSAW7RXj9OPXwlZs6HssmzgW3WWSxOKDExptKCk+/PCm3AroEWgfb6YWULCtvUfqOwxU/qy5d332J03phLDzSSS7jZ5Dj"; ## SECRET-DATA
                
        }
        user user2 {
            uid 2006;
            class super-user;
            authentication {
                ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA5mCmNCuSSRaUpaxOHm73pG8s6bATCGz5YYgDLGaXPe00QGqjlZ2T0Zileb7YdglESmih10vi3XFXsVQ+JTc9nNNawQdWmrdA+9G9UTipR53yZc0vQlCyMshtLB2NqdSUvzBnSf86zAKCzhnaRu5gD/UUbzikeaD3PDixi3hVSmWz4ziJnfwmtfCEUmbX+QeB1u2feltImx91G9itmU/CMBG2rfhpOSz3Ck/MCnfTlSCIjXS9C0HPzmBpiBbBwlKbZuG6NbE9aDgiYkPaB7JHi4Q/9yTjFwo8xCzwPDCbyO8yu2PVwDxOXPxkQTkuTjsrsvSlk3/FRCm19rEPwWCLCQ=="; ## SECRET-DATA
            }
        }
    }
}
```

##### ACTUAL RESULTS

This is what get's created.

```paste below
system {
    login {
        user user1 {
            uid 2002;
            class super-user;
			authentication {
                ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8RWbIGKsIKJH5Id8oZ1lhgNnml1c/kB4qEsddwW4EzsnE0jtI9v2mBH5YCkd4TCirjKgxi7JpnEA78vm4iWgXNvWB9l20yjhXwAT1GKDYMvFUoUUhFpM34AfGRj+txWrhbS9Ao7kyiEUtQRCa8O7MPK1WRcgDFZkgn2xlnhZn3+l2+cq8Hea+dmfSmvX5bALljInWfWr899xLTgxACAm6Tt6UK5SCTR8NxKi/mge2LneSw1696ZCJKzGCSAW7RXj9OPXwlZs6HssmzgW3WWSxOKDExptKCk+/PCm3AroEWgfb6YWULCtvUfqOwxU/qy5d332J03phLDzSSS7jZ5Dj"; ## SECRET-DATA
				ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA5mCmNCuSSRaUpaxOHm73pG8s6bATCGz5YYgDLGaXPe00QGqjlZ2T0Zileb7YdglESmih10vi3XFXsVQ+JTc9nNNawQdWmrdA+9G9UTipR53yZc0vQlCyMshtLB2NqdSUvzBnSf86zAKCzhnaRu5gD/UUbzikeaD3PDixi3hVSmWz4ziJnfwmtfCEUmbX+QeB1u2feltImx91G9itmU/CMBG2rfhpOSz3Ck/MCnfTlSCIjXS9C0HPzmBpiBbBwlKbZuG6NbE9aDgiYkPaB7JHi4Q/9yTjFwo8xCzwPDCbyO8yu2PVwDxOXPxkQTkuTjsrsvSlk3/FRCm19rEPwWCLCQ=="; ## SECRET-DATA
                
        }
        user user2 {
            uid 2006;
            class super-user;
        }
    }
}

```
