### ISSUE TITLE
[docker_container][ansible 2.8] - missing Mount modes on volumes

### ISSUE THREAD

**Issue by grimlokason** [ansible/ansible#58976]
##### SUMMARY
Unable to use the mount mode :nocopy on volume 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/venv-Ansible-28-python27/lib/python2.7/site-packages/ansible
  executable location = /var/lib/awx/venv/venv-Ansible-28-python27/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
N/A
```

##### OS / ENVIRONMENT
AWX 3.0/docker 1.13/ RHEL7.4

##### STEPS TO REPRODUCE

```yaml
- name: start nexus_ihm services
  docker_container:
    name: nexus_ihm
    image: '{{ docker_images.nexus_ihm.image }}:{{ docker_images.nexus_ihm.version }}'
    state: started
    recreate: yes
    log_driver: json-file
    restart_policy: 'unless-stopped'
    hostname: nexus_ihm
    env:
      TZ: Europe/Paris
    volumes:
      - 'nfsdata:/nexus-data:nocopy'
      - 'nfsbackup:/backup'
```
##### EXPECTED RESULTS
Beeing able to access the volume within the container like in :  

```sh
[root@LX01665L ~]# docker run --rm -ti -v nfsdata:/test --name test alpine /bin/sh
/ # ls /test/
config.json  init-stdin   init-stdout
/ # exit
[root@LX01665L ~]# docker run --rm -ti -v nfsdata:/test:nocopy --name test alpine /bin/sh
/ # ls /test/
backup               etc                  kar                  port
blobs                generated-bundles    keystores            restore-from-backup
cache                health-check         lock                 tmp
db                   instances            log                  upgrades
elasticsearch        javaprefs            orient
/ #
```

##### ACTUAL RESULTS
The task crash with (NB, accordingly to the documentation in https://docs.ansible.com/ansible/latest/modules/docker_container_module.html where it's not specified beeing usable ) : 

```
fatal: [lx01665l.tb.uro.equant.com]: FAILED! => {"changed": false, "msg": "Found invalid volumes mode: nocopy"}
```
