### ISSUE TITLE
include_vars lazy evaluation destroys boolean-looking data

### ISSUE THREAD

**Issue by DVGeoffrey** [ansible/ansible#58986]
##### SUMMARY
Using `include_vars` on files with jinja inside is a powerful and useful tool, however when the jinja values lazy-evaluate to "boolean looking" strings, we lose stringyness with no way of getting it back.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`include_vars`

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = None
  configured module search path = [u'/Users/g/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Dec 27 2018, 11:55:59) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
(no output)
```

##### OS / ENVIRONMENT
Tested on OSX

##### STEPS TO REPRODUCE
`bool_to_json.yml` (playbook)
```yaml
---
  - hosts: local
    vars:
        one:
            type:   "bool"
            val:    True
        two:
            type:   "string"
            val:    "True"
    tasks:
      - include_vars:
            file:   example.yml
      - debug:
            msg: |
                meta to json
                {{meta | to_json}}
```

`vars/example.yml`
```yaml
---
meta:
    one_val:   "{{one.val}}"
    two_val:   "{{two.val}}"
    one_try1:   "{{one.val | quote}}"
    two_try1:   "{{two.val | quote}}"
    one_try2:   !!str "{{one.val}}"
    two_try2:   !!str "{{two.val}}"
    one_try3:   !!str "{{one.val | quote}}"
    two_try3:   !!str "{{two.val | quote}}"
```

##### EXPECTED RESULTS
Expecting all `meta.two_*` values to be the string "True"

##### ACTUAL RESULTS
All `meta.two_*` values are boolean.

```paste below
$ ansible-playbook -v -i hosts bool_to_json.yml
No config file found; using defaults

PLAY [local] *********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [local]

TASK [include_vars] **************************************************************************************************************************************************************
ok: [local] => {"ansible_facts": {"meta": {"one_try1": "{{one.val | quote}}", "one_try2": "{{one.val}}", "one_try3": "{{one.val | quote}}", "one_val": "{{one.val}}", "two_try1": "{{two.val | quote}}", "two_try2": "{{two.val}}", "two_try3": "{{two.val | quote}}", "two_val": "{{two.val}}"}}, "ansible_included_var_files": ["/Volumes/SensitiveHD/work/temp/test-ansible-var-shenanigans/vars/example.yml"], "changed": false}

TASK [debug] *********************************************************************************************************************************************************************
ok: [local] => {
    "msg": "meta to json\n{\"two_val\": true, \"one_try2\": true, \"one_try3\": true, \"one_try1\": true, \"one_val\": true, \"two_try1\": true, \"two_try2\": true, \"two_try3\": true}\n"
}

PLAY RECAP ***********************************************************************************************************************************************************************
local                      : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
