### ISSUE TITLE
with_nested not always registering results

### ISSUE THREAD

**Issue by tony-cocco** [ansible/ansible#58991]
##### SUMMARY
Inconsistent behavior is seen when registering a fact using with_nested.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
with_nested

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = centos
```

##### OS / ENVIRONMENT

Docker container from centos:7, ansible installed via yum

##### STEPS TO REPRODUCE

Depending on size of top array, output of: `ansible-playbook ansible.yml` differs.

```yaml
---
- hosts: 127.0.0.1
  vars_files:
    - vars.yml
  tasks:
    - name: Loop things
      shell:  echo "{{ item[0] }}" "{{ item[1] }}"
      with_nested:
        - [1,2,3,4,5,6] #,7,8]
        - [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
      register: loop_output

    - name: Set Fact
      when: loop_output is defined and loop_output is not none
      set_fact:
        my_dict: "{{ my_dict | default([]) + [ item ] }}"
      with_items: "{{ loop_output.results }}"
      no_log: true

    - name: Print Fact
      debug:
        var: my_dict
```

##### EXPECTED RESULTS

Expected list of object/dicts printed.
```
TASK [Print Fact] *************************************************************************************************
ok: [127.0.0.1] => {
    "my_dict": [
        {
            "ansible_loop_var": "item", 
            "changed": true, 
            "cmd": "echo \"1\" \"1\"", 
            "delta": "0:00:00.240103", 
            "end": "2019-07-11 18:02:01.136790", 
            "failed": false, 
            "invocation": {
                ...
            }, 
            "item": [
                1, 
                1
            ], 
            "rc": 0, 
            "start": "2019-07-11 18:02:00.896687", 
            "stderr": "", 
            "stderr_lines": [], 
            "stdout": "1 1", 
            "stdout_lines": [
                "1 1"
            ]
        },  
        ...       
    ]
}

PLAY RECAP ********************************************************************************************************
127.0.0.1                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS

Instead of array of items, `my_dict` has the AnsibleUnsafeText of `"{{ loop_output.results }}"`.

```paste below
TASK [Print Fact] *************************************************************************************************
ok: [127.0.0.1] => {
    "my_dict": [
        "[{'stderr_lines': [], 'ansible_loop_var': u'item', u'end': u'2019-07-11 17:49:30.434708', 'failed': False, u'stdout': u'1 1',...]"
    ]
}

PLAY RECAP ********************************************************************************************************
127.0.0.1                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
