### ISSUE TITLE
vmware_guest: Fails to create a VM attached on a dvs_portgroup:

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#59033]
##### SUMMARY

I try to create a VM attach on a dvs_portgroup, I get the following error:
```
Failed to create a virtual machine : A specified parameter was not correct: spec.deviceChange.device.port.switchUuid
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
devel
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
- name: create new VMs with portgroup
  vmware_guest:
    validate_certs: False
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: new_vm_pg
    guest_id: centos64Guest
    datacenter: "{{ dc1 }}"
    disk:
      - size: 3mb
        type: thin
        autoselect_datastore: yes
    networks:
      - name: portgroup_network
    hardware:
        num_cpus: 1
        memory_mb: 512
    state: poweredoff
    folder: "{{ f0 }}"
  register: vm_with_portgroup
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/vmware/vmware_guest.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Tomorrow9 @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by goneri** [comment]
I face the same problem if I set the `dvswitch_name` key:

```yaml
    networks:
      - name: portgroup_network
        dvswitch_name: dvSwitch
```
