### ISSUE TITLE
get_url deletes target file when checksum fails

### ISSUE THREAD

**Issue by danielhoherd** [ansible/ansible#59051]
##### SUMMARY

When using `get_url`, if the destination exists but has a mismatched checksum, ansible **deletes the target file**.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION

Ubuntu 18.04.2 LTS docker image:
```
ansible 2.8.2
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

Ubuntu 18.04.2 LTS docker image:
```
root@16c4339d1165:/temp# ansible --version
ansible 2.7.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

macOS 10.14.5 with homebrew
```
ansible 2.8.2
  config file = None
  configured module search path = ['/Users/daniel.hoherd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/daniel.hoherd/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Users/daniel.hoherd/Library/Python/3.7/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

No configuration.

##### OS / ENVIRONMENT

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

##### STEPS TO REPRODUCE

```yaml
---
# playbook.yml
- name: A local play
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Download a file with at md5 mismatch
      get_url:
        # url: "https://i.imgur.com/bkmzCVa.jpg"
        url: "http://0.0.0.0:8000/testfile"
        checksum: "md5: 00000000000000000000000000000000"
        dest: "/temp/"

```

```
root@16c4339d1165:/temp# cp /http_root/testfile ./
root@16c4339d1165:/temp# md5sum testfile
2296af62988c0612e6b4f45c2d83c1aa  testfile
root@16c4339d1165:/temp# ansible-playbook -i localhost playbook.yml 2>/dev/null </dev/null

PLAY [A local play] ************************************************************

TASK [Download a file with at md5 mismatch] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "checksum_dest": "e80905bff04158557d0e3c208bfa320f9ee2b7ec", "checksum_src": "e80905bff04158557d0e3c208bfa320f9ee2b7ec", "dest": "/temp/testfile", "elapsed": 0, "msg": "The checksum for /temp/testfile did not match 00000000000000000000000000000000; it was 2296af62988c0612e6b4f45c2d83c1aa.", "src": "/root/.ansible/tmp/ansible-tmp-1562977788.2907045-107139810965159/tmp3a8hrx75", "url": "http://0.0.0.0:8000/testfile"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@16c4339d1165:/temp# ls -la
total 12
drwxr-xr-x 2 root root 4096 Jul 13 00:29 .
drwxr-xr-x 1 root root 4096 Jul 13 00:24 ..
-rw-r--r-- 1 root root  339 Jul 13 00:29 playbook.yml
```

##### EXPECTED RESULTS

I would expect the target file to not be deleted, and for ansible to fail.

##### ACTUAL RESULTS

Target file was deleted.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/basics/get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by danielhoherd** [comment]
It looks like this is where the file is deleted: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py#L630-L635

**Comment by jpmahowald** [comment]
My interpretation of a provided checksum parameter is an assertion that the destination file contains content with that checksum. A failure to do so should be undone, I would expect the destination file to not be there.  In the extreme worst case, the download might be a compromised executable. Leave the invalid file there, ignore the error and continue, and your tasks run bad things.

A workaround might be to move the comparison to failed_when. 

```
- name: get_file keep if wrong
  register: result
  get_url:
    url: https://cdn.arstechnica.net/favicon.ico
    dest: /tmp/
  failed_when: result.checksum_src != "1234567890123456789012345678901234567890"
```
The module is without a checksum parameter, but still returns a checksum. Disadvantage being no choice in the algorithm used.
