### ISSUE TITLE
cloudfront_distribution fails with KeyError: Distribution

### ISSUE THREAD

**Issue by clarete** [ansible/ansible#59074]
##### SUMMARY

Updates to cloudfront distribution always fail. Creation works, but once I ran the same playbook again, it errors out. This looks very similar to the issue https://github.com/ansible/ansible/issues/45043.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = None
  configured module search path = ['/home/lincoln/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lincoln/src/github.com/clarete/dotfiles/.virtualenvs/animamundi/lib/python3.7/site-packages/ansible
  executable location = /home/lincoln/src/github.com/clarete/dotfiles/.virtualenvs/animamundi/bin/ansible
  python version = 3.7.0 (default, Apr 15 2019, 20:16:40) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
(came out empty)
```

##### OS / ENVIRONMENT

```
$ uname -a
Linux guinho 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15) x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

Given the following task

```yaml
- name: Create or update Cloudfront Website distribution
  cloudfront_distribution:
    enabled: true
    ipv6_enabled: true
    # Only specified aliases in this section remain
    purge_aliases: yes
    caller_reference: '{{ dist_ref }}'
    origins:
      - id: 'S3-{{ s3_bucket_name }}'
        domain_name: '{{ s3_bucket_name }}.s3-website-{{ s3_bucket_region }}.amazonaws.com'
        custom_origin_config:
          origin_protocol_policy: 'http-only'
          http_port: 80
          https_port: 443
        custom_headers: []
    http_version: 'http2'
    aliases:
      - '{{ root_domain }}'
      - '{{ www_domain }}'
    viewer_certificate:
      ssl_support_method: 'sni-only'
      certificate_source: 'acm'
      certificate: "{{ cert_arn }}"
    state: present
  register: cloudfront_distribution
  tags: ['cloudfront']
```

When I run the playbook with 
```bash
$ ansible-playbook -vvvv -i inventory/local infra.yml
```

##### EXPECTED RESULTS

Nothing really, since I didn't change any parameters of the distribution, I'd expect ansible to just not do anything and tell me that the distribution looks exactly the way it did before I ran the command.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/home/lincoln/.ansible/tmp/ansible-tmp-1563123345.3446357-186696466652620/AnsiballZ_cloudfront_distribution.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/lincoln/.ansible/tmp/ansible-tmp-1563123345.3446357-186696466652620/AnsiballZ_cloudfront_distribution.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/lincoln/.ansible/tmp/ansible-tmp-1563123345.3446357-186696466652620/AnsiballZ_cloudfront_distribution.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/lincoln/.ansible/tmp/ansible-tmp-1563123345.3446357-186696466652620/AnsiballZ_cloudfront_distribution.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/home/lincoln/.pyenv/versions/3.7.0/lib/python3.7/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/home/lincoln/.pyenv/versions/3.7.0/lib/python3.7/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_cloudfront_distribution_payload_rbpronug/__main__.py\", line 1982, in <module>\n  File \"/tmp/ansible_cloudfront_distribution_payload_rbpronug/__main__.py\", line 1912, in main\nKeyError: 'Distribution'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/amazon/cloudfront_distribution.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/amazon/cloudfront_distribution.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/cloudfront_distribution.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames @wilvk
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rakshazi** [comment]
Same here:
```yaml
- name: Create CloudFront distribution for bucket
  cloudfront_distribution:
    caller_reference: "S3-{{ s3_name }}"
    price_class: "{{ s3_cloudfront_price }}"
    region: "{{ aws_region }}"
    ipv6_enabled: yes
    wait: no
    origins:
      - id: "S3-{{ s3_name }}"
        domain_name: "{{ s3_url }}"
        s3_origin_access_identity_enabled: no
    tags:
      Name: "S3-{{ s3_name }}"
  when: s3_cloudfront == True
  register: s3_cf
```
