### ISSUE TITLE
ios_bgp - Not idempotent when using networks on classful boundaries

### ISSUE THREAD

**Issue by jvanderaa** [ansible/ansible#59083]
##### SUMMARY

When using a classful network boundary for a network, the router will not show "mask x.x.x.x" in the configuration. Thus the module will think a configuration change is needed, not fully idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_bgp

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /Users/joshv/Github/ansible-using_ios/ansible.cfg
  configured module search path = ['/etc/ansible/library']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Feb 10 2019, 15:44:18) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(/Users/joshv/Github/ansible-using_ios/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/Users/joshv/Github/ansible-using_ios/ansible.cfg) = ['/Users/joshv/Github/ansible-using_ios/hosts']
DEFAULT_MODULE_PATH(/Users/joshv/Github/ansible-using_ios/ansible.cfg) = ['/etc/ansible/library']
HOST_KEY_CHECKING(/Users/joshv/Github/ansible-using_ios/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/joshv/Github/ansible-using_ios/ansible.cfg) = /usr/local/bin/python3
RETRY_FILES_ENABLED(/Users/joshv/Github/ansible-using_ios/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS -> Cisco IOS

##### STEPS TO REPRODUCE

Advertise networks 198.51.100.0/24
          networks:
            - prefix: 198.51.100.0
              masklen: 24

```yaml
    - name: "TASK 1: Setup iBGP Peer"
      ios_bgp:
        config:
          bgp_as: 65500
          router_id: 10.0.0.3
          log_neighbor_changes: true
          neighbors:
            - neighbor: 198.51.100.2
              remote_as: 65500
              activate: true
              timers:
                keepalive: 15
                holdtime: 45
                min_neighbor_holdtime: 5
              description: R4
          networks:
            - prefix: 198.51.100.0
              masklen: 24
            - prefix: 203.0.113.0
              masklen: 24
          address_family:
            - afi: ipv4
              safi: unicast
              neighbors:
                - neighbor: 198.51.100.2
                  activate: yes
                  next_hop_self: yes
        operation: merge
      register: ibgp_peer1
```

##### EXPECTED RESULTS

I'd expect that the second run would be idempotent and not change. I'm getting a changed message instead of OK.

##### ACTUAL RESULTS

The module attempted to push

```paste below
            "commands": [
                "router bgp 65500",
                "network 198.51.100.0 mask 255.255.255.0",
                "address-family ipv4",
                "no auto-summary",
                "exit-address-family",
                "exit"
            ],
            "failed": false
```

I'm thinking of how to take a stab at this in the coming weeks if it isn't already a quick easy fix. Small low priority issue...
