### ISSUE TITLE
Syntax error is not caught in authorized_key module

### ISSUE THREAD

**Issue by maedox** [ansible/ansible#5908]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:
- Linux Mint 15
- Python 2.7.4
##### Summary:

Variables for user and key in the authorized_key doesn't seem to expand, when in fact there is a syntax error (missing ending paranthesis) for the lookup function.
##### Steps To Reproduce:

_test.yml_

``` yaml
-
  hosts: local
  sudo: yes
  gather_facts: no

  vars:
    users:
      - test

  tasks:
    - name: Add public key(s) for admin users
      authorized_key:
        user={{ item }}
        key="{{ lookup('file', item }}"
      with_items:
        users
```

$ ansible-playbook -vsc local -i local test.yml
##### Expected Results:

Ansible should exit with a syntax error.
##### Actual Results:

```
failed: [localhost] => (item=test) => {"failed": true, "item": "test"}
msg: Failed to lookup user {{item}}: 'getpwnam(): name not found: {{item}}'
```

Setting user=test and key=test yields "invalid key", so it seems the {{item}} variable is not expanded?

Also tested with same results on:
- Ansible 1.5 devel (0bc0315171efb83e7ac4f82584d9ec97f42f71a3)
