### ISSUE TITLE
k8s_facts: does not list the Statefulsets

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#59115]
##### SUMMARY
When using the ansible module to get a list of Statefulset resources, an empty array is returned. Even though matching resources exist.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_info

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eanderson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  vars:
    k8s_auth_kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    gcp_service_account_file: "{{ ansible_env.HOME }}/service-account-test-credentials.json"
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_auth_kubeconfig }}"
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gcp_service_account_file }}"
  tasks:
    - name: GKE | Get controller count from namespace
      k8s_facts:
        api_version: v1
        kind: Statefulsets
        namespace: be1625c8964342c5be010dbd9cce6973
      register: statefulsets
    - name: Output
      debug: var=statefulsets
```

##### EXPECTED RESULTS
The existing matching object to the namespace
```
$ kubectl get statefulsets -n be1625c8964342c5be010dbd9cce6973
NAME     READY   AGE
node-0   1/1     7d3h
```
##### ACTUAL RESULTS

```paste below
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,

            "context": null,
            "field_selectors": [],
            "host": null,
            "kind": "Statefulsets",
            "kubeconfig": null,
            "label_selectors": [],
            "name": null,
            "namespace": "be1625c8964342c5be010dbd9cce6973",
            "password": null,
            "username": null,
            "validate_certs": null
        }
    },
    "resources": []
}
```
