### ISSUE TITLE
Add python shebang to module_utils.service_now

### ISSUE THREAD

**Issue by n3pjk** [ansible/ansible#59111]
##### SUMMARY
SNOW modules have /usr/bin/python shebang, but refactored code did not, causing inconsistency. Adding shebang to module_utils.service_now allows refactored code to be imported.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
snow_record.py
snow_record_find.py

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /home/pknight/dci/ansible/servicenow/ansible.cfg
  configured module search path = [u'/home/pknight/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION
```
DEFAULT_VAULT_PASSWORD_FILE(/home/pknight/dci/ansible/servicenow/ansible.cfg) = /home/pknight/.ansiblevault
YAML_FILENAME_EXTENSIONS(/home/pknight/dci/ansible/servicenow/ansible.cfg) = [u'.json', u'.yaml', u'.yml', u'.vault']
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE

ansible-playbook 

```yaml
- name: Test Run
  hosts: all
  connection: local
  gather_facts: no
  ignore_errors: True
  tasks:

  - name: Gather facts on automation user
    snow_record_find:
      username: "ansible_user@domain.com"
      password: "S0m3P@ssw0rd"
      client_id: "1234567890abcdef01234567890abcde"
      client_secret: "S0m3S3cr3t"
      instance: "yourinstance"
      max_records: 1
      table: sys_user
      query:
        email: "ansible_user@domain.com"
      return_fields:
        - email
        - name
        - sys_id
    register: response
```

##### EXPECTED RESULTS
I am working on a possible issue with my SNOW instance that results in the following fatal error.  This is
still better than the actual result.  I will update this with the correct expected result when instance issue is resolved.
```json
fatal: [yourinstance.service-now.com]: FAILED! => {
    "changed": false, 
    "instance": "yourinstance", 
    "invocation": {
        "module_args": {
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "client_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "instance": "yourinstance", 
            "max_records": 1, 
            "order_by": "-created_on", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "query": {
                "email": "ansible_user@domain.com"
            }, 
            "return_fields": [
                "email", 
                "name", 
                "sys_id"
            ], 
            "table": "sys_user", 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    }, 
    "max_records": 1, 
    "msg": "Failed to find record: 'NoneType' object has no attribute 'query'", 
    "query": {
        "email": "ansible_user@domain.com"
    }, 
    "return_fields": [
        "email", 
        "name", 
        "sys_id"
    ], 
    "table": "sys_user"
}
```

##### ACTUAL RESULTS
```
fatal: [delawarecalgarytest.service-now.com]: FAILED! => {
    "msg": "Unable to import ('service_now',) due to invalid syntax"
}
```
