### ISSUE TITLE
azure_rm_virtualmachine suggests that a VM can be deployed to multiple Availability Zones

### ISSUE THREAD

**Issue by ferhaty** [ansible/ansible#59134]
##### SUMMARY

The azure_rm_virtualmachine module suggests that VM can be deployed to multiple availability zones. This is not the case. 

```python
    zones:
        description:
            - A list of Availability Zones for your virtual machine
        type: list
        version_added: "2.8"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/roles']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

- name: Create a VM with an Availability Zone
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: testvm001
    vm_size: Standard_DS1_v2
    admin_username: adminUser
    admin_password: password01
    image: customimage001
    zones: [1,2,3]
```

##### EXPECTED RESULTS

It should only be possible to specify a single AZ or no AZ at all

##### ACTUAL RESULTS

You're able to specify `zones: [1,2,3]` which is invalid.
