### ISSUE TITLE
oVirt: when having network with spaces in name, the search fails to find it.

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#59140]
##### SUMMARY

When having network with spaces in name, the search fails to find it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_network

##### ANSIBLE VERSION

```paste below
2.8.1
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
ovirt_network:
    name: Storage - VLAN
    vm_network: False
    vlan_tag: 33
    data_center: Default
    description: Storage with VLAN Tagging
    comment: Storage with VLAN Tagging
    clusters:
      - name: Default
        required: False
        migration: True
```

##### ACTUAL RESULTS

```paste below
ovirtsdk4.Error: Fault reason is "Operation Failed". Fault detail is "[Cannot add Network. The name of the logical network 'Storage - VLAN 33' is already used by an existing logical network in the same data-center.
```

The problem is that in oVirt API searching object with spaces in name, it won't find it. We need to quote the search string.
