### ISSUE TITLE
"docker_container" with "become" throws "No module named exceptions"

### ISSUE THREAD

**Issue by jbflowers** [ansible/ansible#59167]
##### SUMMARY
Using "docker_container" module with "become":

```
- name: start containers
  become: yes
  become_user: EXAMPLE_USER
  docker_container:
  .....

```
shows this error:

```
TASK [start containers] **************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker or docker-py - No module named exceptions. Try `pip install docker` or `pip install docker-py` (Python 2.6)"}
```
However it seems to be working without using "become".

**NOTES**
I've tried
- Installing "docx" and "python-docx" pip packages
- Installing "docker-py" and "docker" pip packages
- Making lib dirs in "/lib/python2.7/site-packages" 755 to ensure they're accessible by everyone
- Ensured "become" works with EXAMPLE_USER with a "command" module running "whoami" which worked
- Ran "python" and tried "import exceptions" and "import docx" successfully as both remote login user and "become" target user
- There's only one python2.7 interpreter installed on this machine 

```
[root@####]# sudo pip list
ansible (2.7.12.post0)
Babel (0.9.6)
backports.ssl-match-hostname (3.5.0.1)
certifi (2019.6.16)
cffi (1.6.0)
chardet (3.0.4)
configobj (4.7.2)
cryptography (1.7.2)
decorator (3.4.0)
docker-py (1.10.6)
docker-pycreds (0.3.0)
enum34 (1.0.4)
ethtool (0.8)
futures (3.1.1)
httplib2 (0.9.2)
idna (2.8)
iniparse (0.4)
insights-client (3.0.3)
ipaddress (1.0.16)
IPy (0.75)
isodate (0.5.0)
javapackages (1.0.0)
Jinja2 (2.7.2)
jmespath (0.9.0)
kitchen (1.1.1)
langtable (0.0.31)
lxml (3.2.1)
M2Crypto (0.21.1)
Magic-file-extensions (0.2)
MarkupSafe (0.11)
paramiko (2.1.1)
passlib (1.7.1)
pciutils (1.7.3)
perf (0.1)
Pillow (6.1.0)
pip (8.1.2)
ply (3.4)
policycoreutils-default-encoding (0.1)
pulp-agent (2.8.7.20)
pulp-common (2.8.7.20)
pulp-rpm-common (2.8.7)
pulp-rpm-handlers (2.8.7)
pyasn1 (0.1.9)
pycparser (2.14)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
pyinotify (0.9.4)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
python-augeas (0.5.0)
python-dateutil (1.5)
python-dmidecode (3.10.13)
python-docx (0.8.10)
python-linux-procfs (0.4.9)
python-qpid-proton (0.28.0)
pytoml (0.1.14)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
registries (0.1)
requests (2.22.0)
schedutils (0.4)
seobject (0.1)
sepolicy (1.1)
setuptools (41.0.1)
six (1.9.0)
slip (0.4.0)
slip.dbus (0.4.0)
subscription-manager (1.20.11)
urlgrabber (3.10)
urllib3 (1.25.3)
websocket-client (0.56.0)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```
ansible 2.7.12.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fclvappi025171/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
No output from command
```

##### OS / ENVIRONMENT

RHEL 7

##### STEPS TO REPRODUCE

Setup ansible 2.7 on RHEL and run a playbook to start a container like this: 

```
- name: start containers
  become: yes
  become_user: EXAMPLE_USER
  docker_container:
 ...
```

##### EXPECTED RESULTS

The container to be started by the EXAMPLE_USER provided.

##### ACTUAL RESULTS

Getting the error
```
TASK [start containers] **************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker or docker-py - No module named exceptions. Try `pip install docker` or `pip install docker-py` (Python 2.6)"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/docker/docker_container.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @cove @danihodovic @dariko @dusdanig @felixfontein @joshuaconner @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The [Docker SDK for Python](https://pypi.org/project/docker/) needs to be installed on the machine where the module is executed (this is in general **not** the machine you run ansible-playbook on), so that the Python interpreter used for user `EXAMPLE_USER` can find the Docker SDK for Python.

If you add another task
```.yaml
- name: install Docker SDK for Python
  become: yes
  become_user: EXAMPLE_USER
  pip:
    name: docker
```
it should be installed at the correct location.


PS: [docx](https://pypi.org/project/docx/) is for reading/writing Microsoft Office .docx files, and totally unrelated to docker. And there's no module called `exceptions`; it's trying to import `requests.exceptions`, and `requests` is a requisite of `docker` and `docker-py`. (https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/docker/common.py#L39)

**Comment by jbflowers** [comment]
Ahh, that's it, I needed to try the "requests" package. Wish the message included a reference to that. Now that I have the permissions fixed for "requests" and have "pip --user" ansible command working for "EXAMPLE_USER" everything seems to be working smoothly. Thanks for the help!

**Comment by felixfontein** [comment]
@jbflowers if you start having different permissions for different Python modules in the same Python installation, you have to make sure that all dependencies of docker / docker-py can be accessed.

Anyway, I don't know why the error message only mentions `exceptions` and not `requests`. With both 2.7 and 3.7 I always get the top-level package mentioned in the error message when I try to import a package which isn't there. Maybe it's related to your strange access rights?

**Comment by jbflowers** [comment]
Not sure about the error message, but I was able to determine the issue that caused the pip problems in the first place. Seems the current `epel-release` package containing `pip` for RHEL 7 installs pip incorrectly; it moves `pip` related packages to `/usr/lib/python2.7/sitepackages` as read-only for root. Then, whenever another use attempts to run `pip` they get a "module not found" exception. This is doubly hard to debug, because when one uninstalls `pip` with `yum` it leaves the broken packages with bad permissions in `/usr/lib/python2.7/sitepackages`. So, to fix this, one has to delete all the offending `pip` packages in `/usr/lib/python2.7/sitepackages` and then reinstall using the `get-pip.py` script from Python with the `--user` option set. Example set of plays that work consistently for me (obviously PROXY is optional and USER should be changed to the user to install as) :

```
- name: Download setuptools
  environment:
    https_proxy: PROXY
  get_url:
    url: https://pypi.python.org/packages/source/s/setuptools/setuptools-7.0.tar.gz
    dest: /home/USER
    validate_certs: no
  become: yes
  become_user: USER

- name: Unarchive setup tools
  unarchive:
    src: /home/USER/setuptools-7.0.tar.gz
    dest: /home/USER/
    remote_src: yes
  become: yes
  become_user: USER
 
- name: Run python command to install setup tools
  command: python /home/USER/setuptools-7.0/setup.py install

- name: Download pip installer
  environment:
    https_proxy: PROXY
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /home/USER
    validate_certs: no
  become: yes
  become_user: USER

- name: Run python command to install pip
  environment:
    https_proxy: PROXY
  command: python /home/USER/get-pip.py --user --proxy $https_proxy 
  become: yes
  become_user: USER

- name: install Docker SDK for Python
  become: yes
  become_user: USER
  pip:
    name: docker
    extra_args: --user --proxy=PROXY
    executable: /home/USER/.local/bin/pip


```
