### ISSUE TITLE
implementation error: unknown type password-3 requested for

### ISSUE THREAD

**Issue by indreek** [ansible/ansible#59176]
##### SUMMARY
When using fortios_vpn_ipsec_phase1 module i get error ""implementation error: unknown type password-3 requested for psksecret"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fortios_vpn_ipsec_phase1 

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /home/indrek/.ansible.cfg
  configured module search path = ['/home/indrek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/indrek/.local/lib/python3.6/site-packages/ansible
  executable location = /home/indrek/.local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

```

##### OS / ENVIRONMENT
Ubuntu 17
Python 3

Im getting error that password-3 type is not defined. I suspect that ansible doesn't support this type.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/fortios/fortios_vpn_ipsec_phase1.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/fortios/fortios_vpn_ipsec_phase1.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bjolivot @mamunozgonzalez @thomnico
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@indreek, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mamunozgonzalez** [comment]
Hi @indreek , 
can you share the playbook you are using? 
And also your fortigate sw version?

**Comment by indreek** [comment]
Simple testing playbook.

---
- hosts: localhost
  tasks:
    - name: Configure VPN remote gateway.
      fortios_vpn_ipsec_phase1:
        host:  192.168.11.1:8443
        username: user
        password: pass

        vpn_ipsec_phase1:
          state: present
          name: test
          remote-gw: 192.168.0.10
          interface: wan1
          psksecret: test

**Comment by eftner** [comment]
I hit the exact same case.

`ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eftner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]`

Task:
`- name: Create ipsec phase1 interface
  fortios_vpn_ipsec_phase1_interface:
    host: "{{ fortios_host }}"
    username: "{{ fortios_username }}"
    password: "{{ fortios_password }}"
    vdom: "{{ item.vdom }}"
    https: "False"
    vpn_ipsec_phase1_interface:
      state: "present"
      name: "{{ item.name }}"
      interface: "{{ item.phase1_local_interface }}"
      ike-version: "2"
      keylife: "28800"
      peertype: "any"
      proposal: "des-sha512"
      dhgrp: "5"
      remote-gw: "{{ item.phase1_remotegw }}"
      psksecret: "whatever123"
  with_items:
    - "{{ fortios_ipsec_s2s_vpn }}"
  tags: [s2s_ipsec_vpn, s2s_ipsec_vpn_phase1]`

Playbook:
`- hosts: all
  connection: local
  roles:
    - { role: fortios }`

host_vars:
`fortios_ipsec_s2s_vpn:
  - name: "MyDC"
    vdom: "root"
    phase1_local_interface: "root_internet"
    phase1_remotegw: "1.2.3.4"
    phase2_selectors:
     - name: "MyDC-S1"
       src-subnet: "10.129.68.0/255.255.255.0"
       dst-subnet: "10.120.68.0/255.255.255.0"
       #     - name: "MyDC-S2"`

Ansible run:
`TASK [fortios : Create ipsec phase1 interface] **********************************************************************
failed: [labforti] (item={u'vdom': u'root', u'name': u'MyDC', u'phase2_selectors': [{u'dst-subnet': u'10.120.68.0/255.255.255.0', u'name': u'MyDC-S1', u'src-subnet': u'10.129.68.0/255.255.255.0'}], u'phase1_local_interface': u'root_internet', u'phase1_psksecret': u'whatever123', u'phase1_remotegw': u'1.2.3.4'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "MyDC", "phase1_local_interface": "root_internet", "phase1_psksecret": "whatever123", "phase1_remotegw": "1.2.3.4", "phase2_selectors": [{"dst-subnet": "10.120.68.0/255.255.255.0", "name": "MyDC-S1", "src-subnet": "10.129.68.0/255.255.255.0"}], "vdom": "root"}, "msg": "implementation error: unknown type password-3 requested for psksecret"}`

My fw version is 5.6.9 build1673.

**Comment by eftner** [comment]
I hit the exact same case.

```
ansible 2.8.5

  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eftner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```


Task:

```
- name: Create ipsec phase1 interface
  fortios_vpn_ipsec_phase1_interface:
    host: "{{ fortios_host }}"
    username: "{{ fortios_username }}"
    password: "{{ fortios_password }}"
    vdom: "{{ item.vdom }}"
    https: "False"
    vpn_ipsec_phase1_interface:
      state: "present"
      name: "{{ item.name }}"
      interface: "{{ item.phase1_local_interface }}"
      ike-version: "2"
      keylife: "28800"
      peertype: "any"
      proposal: "des-sha512"
      dhgrp: "5"
      remote-gw: "{{ item.phase1_remotegw }}"
      psksecret: "whatever123"
  with_items:
    - "{{ fortios_ipsec_s2s_vpn }}"
  tags: [s2s_ipsec_vpn, s2s_ipsec_vpn_phase1]
```


Playbook:
```
- hosts: all
  connection: local
  roles:
    - { role: fortios }`
```

host_vars:

```
fortios_ipsec_s2s_vpn:
  - name: "MyDC"
    vdom: "root"
    phase1_local_interface: "root_internet"
    phase1_remotegw: "1.2.3.4"
    phase2_selectors:
     - name: "MyDC-S1"
       src-subnet: "10.129.68.0/255.255.255.0"
       dst-subnet: "10.120.68.0/255.255.255.0"
```

Ansible run:

```
TASK [fortios : Create ipsec phase1 interface] **********************************************************************
failed: [labforti] (item={u'vdom': u'root', u'name': u'MyDC', u'phase2_selectors': [{u'dst-subnet': u'10.120.68.0/255.255.255.0', u'name': u'MyDC-S1', u'src-subnet': u'10.129.68.0/255.255.255.0'}], u'phase1_local_interface': u'root_internet', u'phase1_psksecret': u'whatever123', u'phase1_remotegw': u'1.2.3.4'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "MyDC", "phase1_local_interface": "root_internet", "phase1_psksecret": "whatever123", "phase1_remotegw": "1.2.3.4", "phase2_selectors": [{"dst-subnet": "10.120.68.0/255.255.255.0", "name": "MyDC-S1", "src-subnet": "10.129.68.0/255.255.255.0"}], "vdom": "root"}, "msg": "implementation error: unknown type password-3 requested for psksecret"}
```


My fw version is 5.6.9 build1673.
