### ISSUE TITLE
ovirt_vm: Unable to find template shared among multiple clusters in the same datacenter

### ISSUE THREAD

**Issue by jbdelavoix** [ansible/ansible#59189]
##### SUMMARY

Since commit df581eb ovirt_vm is unable to find a template shared among multiple clusters in the same datacenter. Moreover, the document says that `cluster` parameter is a parameter used to define where VMs will be created. Then it should not be used to filter a template search which is not related to VM storage.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_vm

##### ANSIBLE VERSION

```paste below
2.8.2
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

In RHEVM:
1. Create a cluster `cluster_a` and add a template `template_a` in this cluster
2. Create a cluster `cluster_b`

```yaml

- name: Provision machine
  ovirt_vm:
    ...
    cluster: "cluster_b"
    template: "template_a"
    ...
```

##### EXPECTED RESULTS

The template should be found (Behaviour before commit df581eb)

##### ACTUAL RESULTS

It raises an error

```paste below
Template with name 'template_a' and version 'None' in cluster 'cluster_b' was not found
```
