### ISSUE TITLE
win_share: remove all other permissions of a share

### ISSUE THREAD

**Issue by LeDOC666** [ansible/ansible#59237]
##### SUMMARY
I have a playbook the user: App_Urb on a share EAI. Everything is ok, but If I have another user on that share, playbook remove it

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_share

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
[14:07:41]root@vsrvkermit playbook]# ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/datas/ansible/roles']

```

##### OS / ENVIRONMENT
Target is Windows 2012 R2

##### STEPS TO REPRODUCE

Case original:
```
C:\Windows\system32>net share EAI
Share name        EAI
Path              D:\Partage\EAI
Remark            Repertoire EAI
Maximum users     No limit
Users
Caching           Manual caching of documents
Permission        VSRVQSRM\Appli_Urba, FULL
                  PAM\EXP_TRT, READ
```
I manually added PAM\EXP_TRT with READ rules.

I run playbook like this:
```
- name: Add share EAI
  win_share:
    name: EAI
    description: Repertoire EAI
    path: D:\Partage\EAI
    list: no
    full: Appli_Urba
  when: ansible_distribution_version is version('6.2','>=')

```
This remove the created user

##### EXPECTED RESULTS

Keep original user, just add Appli_Urb if not exist

##### ACTUAL RESULTS

```
C:\Windows\system32>net share EAI
Share name        EAI
Path              D:\Partage\EAI
Remark            Repertoire EAI
Maximum users     No limit
Users
Caching           Manual caching of documents
Permission        VSRVQSRM\Appli_Urba, FULL
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_share.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_share.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @daBONDi @if-meaton @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
I think this is just 'desired state' behaviour.  Think of the win_share module as describing what permissions are required on the share.  So you must tell it all the permissions you need.

You would need to modify playbook like this:

```yaml
- name: Add share EAI
  win_share:
    name: EAI
    description: Repertoire EAI
    path: D:\Partage\EAI
    list: no
    full: Appli_Urba
    read: PAM\EXP_TRT
  when: ansible_distribution_version is version('6.2','>=')
```

I think behaving like it does is desirable because the ansible configuration becomes 'single point of truth' regarding how exactly the share should be configured.  Obviously this means that you must capture all the permissions you need to set up in your playbook, not just new ones you wish to add.
