### ISSUE TITLE
Docker logout reports no change even though it did something

### ISSUE THREAD

**Issue by reitzig** [ansible/ansible#59232]
##### SUMMARY
`docker_login` reports no change even though it logged out.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`docker_login`

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/raphael/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Client: Ubuntu 18.04 LTS 4.18.0-24-generic, ansible 2.8.1
Server: RHE7 3.10.0-957.21.3.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
- name: Pull some Docker images 
  block:
  - name: Log into Harbor (Docker registry)
    docker_login:
        registry: "{{docker_registry}}"
        username: "{{harbor_user}}"
        password: "{{harbor_password}}"
        reauthorize: yes
  - name: Pull Docker images
    loop:
      - "some_image"
      - "other_image"
    docker_image:
      name: "{{ item }}"
      state: present
      source: pull
  always:
    - name: Docker logout
      docker_login:
        registry: "{{docker_registry}}"
        state: absent
```

##### EXPECTED RESULTS

Task `Docker logout` should report changes.

##### ACTUAL RESULTS

```paste below
TASK [gears : Log into Harbor (Docker registry)] 
<snip>
changed: [<snip>] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "api_version": "auto", 
            "ca_cert": null, 
            "client_cert": null, 
            "client_key": null, 
            "config_path": "/home/<snip>/.docker/config.json", 
            "debug": false, 
            "docker_host": "unix://var/run/docker.sock", 
            "email": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "reauthorize": true, 
            "registry": "<snip>", 
            "registry_url": "<snip>, 
            "ssl_version": null, 
            "state": "present", 
            "timeout": 60, 
            "tls": false, 
            "tls_hostname": "localhost", 
            "username": "<snip>", 
            "validate_certs": false
        }
    }, 
    "login_result": {
        "IdentityToken": "", 
        "Status": "Login Succeeded"
    }
}

<snip>
TASK [gears : Pull Docker images]
ok:
<snip>

TASK [gears : Docker logout]
<snip>
ok: [<snip>] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_version": "auto", 
            "ca_cert": null, 
            "client_cert": null, 
            "client_key": null, 
            "config_path": "/home/<snip>/.docker/config.json", 
            "debug": false, 
            "docker_host": "unix://var/run/docker.sock", 
            "email": null, 
            "password": null, 
            "reauthorize": false, 
            "registry": "<snip>", 
            "registry_url": "<snip>", 
            "ssl_version": null, 
            "state": "absent", 
            "timeout": 60, 
            "tls": false, 
            "tls_hostname": "localhost", 
            "username": null, 
            "validate_certs": false
        }
    }, 
    "login_result": {}
}
```

But, on that host:

```
$ cat .docker/config.json | grep auth
	"auths": {}
```

When I remove the logout task, the login appears in that output. So logout _is_ effective.
