### ISSUE TITLE
The 'meta' module does not know how to work with the 'item' of the loop

### ISSUE THREAD

**Issue by anatolek** [ansible/ansible#59258]
##### SUMMARY
The 'meta' module does not know how to work with the 'item' of the loop.
Also this is true for with_items and with_list.
So, I always get the following error --> 'item' is undefined.
It seems a problem with "ansible_loop_var" variable, but I'm not sure.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

modules:
- meta
##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Ubuntu 16.04.6 LTS
4.15.0-54-generic #58~16.04.1-Ubuntu x86_64 GNU/Linux

##### STEPS TO REPRODUCE

defaults/main.yml
```yaml
---
de_service_name: "myservice.service"
```
tasks/main.yml
```yaml
- name: Get service facts
  service_facts:
  no_log: true

- name: It works correctly
  debug:
    msg: "{{ ansible_facts.services[item].state }}"
  when:
    - ansible_facts.services[item].state == "running"
  loop:
    - "{{ de_service_name }}"

- name: Fails with an error "'item' is undefined"
  meta: end_play
  when:
    - ansible_facts.services[item].state == "running"
  loop:
    - "{{ de_service_name }}"
```

##### EXPECTED RESULTS

Playbook finished without errors

##### ACTUAL RESULTS

```paste below
ERROR! The conditional check 'ansible_facts.services[item].state == "running"' failed. The error was: error while evaluating conditional (ansible_facts.services[item].state == "running"): 'item' is undefined
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/__init__.py)
* [`lib/ansible/modules/utilities/helper/meta.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
Actually, you should get a warning that `loop` is ignored in this context (not valid for most `meta` actions).

As a workaround you can use a filter to set the condition.

**Comment by anatolek** [comment]
@bcoca What exactly filters do you mean? Could you, please, give an example of how you see the issue could be resolved?

**Comment by bcoca** [comment]
not functional (top of my head), but something like this 

````when: ansible_facts.services|map('extract', de_service_name)|list|select('running')|list```
that 'should' run if any of the services in 'de_service_name' is in 'running' status, otherwise its an empty list, which is `False`.

**Comment by mkrizek** [comment]
We recently (#57921) added a note in the docs that looping on meta tasks is not supported. The `devel` docs: https://docs.ansible.com/ansible/devel/modules/meta_module.html#notes

Also see https://github.com/ansible/ansible/issues/57427

If you have further questions please stop by IRC or the mailing list:

* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by anatolek** [comment]
I solved my problem using the python dictionary method get()
```yaml
- name: Сheck if the service is running
  meta: end_play
  when:
    - ansible_facts.services.get(de_service_name).get('state') == "running"
```
