### ISSUE TITLE
aws_batch_job_definition_module converts parameters from THIS_CASING to THISCasing

### ISSUE THREAD

**Issue by glassresistor** [ansible/ansible#59255]
##### SUMMARY
The `aws_batch_job_definition_module` arguement parameters is used to set the default environment variables for an AWS batch job.  Typically environment variables are written in all caps with underscores.  AWS batch job has no additional requirements added to parameters but the ansible module is doing strange unnecessary and undocumented conversions of the parameters keys when creating job definitions.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_batch_job_definition_module

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.8.1
  config file = /home/mikela/.ansible.cfg
  configured module search path = [u'/home/mikela/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mikela/anaconda3/envs/playbooks/lib/python2.7/site-packages/ansible
  executable location = /home/mikela/anaconda3/envs/playbooks/bin/ansible
  python version = 2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 23:04:45) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(/home/mikela/.ansible.cfg) =[redacted]
HOST_KEY_CHECKING(/home/mikela/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
Debian stretch linux kernel 4.9.0-8

##### STEPS TO REPRODUCE
Use the aws_batch_job_definition_module to create a job definition with parameters of the from ALL_CAPS_WITH_UNDERSCORES and then look in the console and see that its now ALLCapsWithUnderscores

```yaml
- hosts: localhost
  connection: local

  tasks:
    - name: My Batch Job Definition
      aws_batch_job_definition:
        job_definition_name: "test_name"
        state: present
        type: container
        image: "any image will do"
        vcpus: 8
        memory: 16384
        attempts: 3
        parameters:
           TEST_CAPS: value1
```

##### EXPECTED RESULTS
That the parameters keys are not changed unnecessarily.

##### ACTUAL RESULTS
That the parameters keys are changed unnecessarily.
