### ISSUE TITLE
win_nssm password with quote

### ISSUE THREAD

**Issue by tclavier** [ansible/ansible#59301]
##### SUMMARY

Given this yaml entry

```yaml
- name: "Create a service via nssm"
  win_nssm:
    name: "node_name"
    application: 'D:\service.cmd'
    user: "windows_domain\\windows_user"
    password: "pass'word"
    state: present
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_nssm

##### ANSIBLE VERSION
```paste below
"an exception occurred when invoking NSSM: Au caractère Ligne:1 : 78\r\n+ ... \"windows-agent-1\" ObjectName RESSOURCES\\SVC_PACIFIC 'pass'word'\r\n+ 
```

##### CONFIGURATION
`ansible-config dump --only-changed` report nothing

##### OS / ENVIRONMENT
Windows server 2012

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_nssm.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_nssm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @ksubileau @nitzmahone @smadam813 @themiwi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ksubileau** [comment]
The user and password parameters are deprecated since 2.8. Please try using the new recommended approach with `win_service` and tell us if you still have the same issue this way:
```yaml
- name: Create a service via nssm
  win_nssm:
    name: node_name
    application: D:\service.cmd
    state: present

- name: Configure the service
  win_service:
    name: node_name
    user: windows_domain\windows_user
    password: "pass'word"
    state: started
```

**Comment by jborean93** [comment]
As @ksubileau has mentioned, using the username and password options in `win_nssm` is deprecated and you should be using `win_service`. If that is also having issues please open a issue for that not module. Feel free to open a PR to fix this in win_nssm but this won't be tracked because the feature is going away.

**Comment by tclavier** [comment]
@ksubileau that work fine, just a typo in your sample : 

Not : `user: windows_domain\windows_user` but `username: windows_domain\\windows_user`

```yaml
    - name: "Create a service via nssm"
      win_nssm:
        name: "test-nssm"
        application: 'D:\\agent\service.cmd'
        state: present

    - name: "Start the service"
      win_service:
        name: "test-nssm"
        state: restarted
        username: "windows_domain\\windows_user"
        password: "pass'word"
```
