### ISSUE TITLE
 ec2_launch_template missing delete specific template version

### ISSUE THREAD

**Issue by SarahJaine** [ansible/ansible#59303]
##### SUMMARY

First, thank you for creating and maintaining ansible. It's a great automation tool.

The [ec2_launch_template documentation](https://github.com/ansible/ansible/blob/stable-2.8/lib/ansible/modules/cloud/amazon/ec2_launch_template.py#L48) provides direction for deleting a specific version of a launch template (rather than all versions).  

> To delete only a specific version of a launch template, combine state=absent with the version option.

However, the [delete_template function](https://github.com/ansible/ansible/blob/stable-2.8/lib/ansible/modules/cloud/amazon/ec2_launch_template.py#L397) doesn't appear to handle a target version as an argument. Consequently, this module does not allow for deleting a specific launch template version.

I'm entering this as a bug because the documentation includes functionality that doesn't exist, or, doesn't exist as documented.  If you'd like me to open up a second ticket for a feature request please let me know.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_launch_template

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
```
devel branch is affected too

##### CONFIGURATION

nothing significant

##### OS / ENVIRONMENT

MacOS Mojave

##### STEPS TO REPRODUCE

Strategy 1: Assuming `version` in doc meant `default_version`
```yaml
- name: Delete old version of launch template
    ec2_launch_template:
      default_version: "10"
      template_name: "hello-deployment-template"
      state: absent
      template_id: "lt-1254ad3f568123456"
```
Strategy 2: Assuming `version` (as written in docs):
```yaml
- name: Delete old version of launch template
    ec2_launch_template:
      version: "10"
      template_name: "hello-deployment-template"
      state: absent
      template_id: "lt-1254ad3f568123456"
```

##### EXPECTED RESULTS

Both strategies: Template version 10 is deleted; versions 1-9 remain intact.

##### ACTUAL RESULTS

Strategy 1: All versions of template are removed
Strategy 2: Error because `version` is not a valid param (detail below).

Strategy 2:
```paste below
fatal: [localhost]: FAILED! => {"msg": "Unsupported parameters for (ec2_launch_template) module: version Supported parameters include: aws_access_key, aws_secret_key, block_device_mappings, cpu_options, credit_specification, debug_botocore_endpoint_logs, default_version, disable_api_termination, ebs_optimized, ec2_url, elastic_gpu_specifications, iam_instance_profile, image_id, instance_initiated_shutdown_behavior, instance_market_options, instance_type, kernel_id, key_name, monitoring, network_interfaces, placement, profile, ram_disk_id, region, security_group_ids, security_groups, security_token, state, tags, template_id, template_name, user_data, validate_certs"}
```
