### ISSUE TITLE
apt_repository, loop, Failed to connect to the host via ssh on 2nd iteration of loop

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#59321]
##### SUMMARY
Using apt_repository in a loop to add repositories and on the 2nd iteration of the loop the tasks fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apt_repository

##### ANSIBLE VERSION
```paste below
$ ansible --version
ansible 2.9.0.dev0
  config file = /Users/tanner/projects/py3-ansible/src/playbooks.git/igi.com/ansible.cfg
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible
  executable location = /Users/tanner/projects/py3-ansible/src/ansible/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION
```paste below
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Management host: macOS 10.14.5
Managed host: Ubuntu 14.04 Trusty

##### STEPS TO REPRODUCE
```yaml
- name: trusty (14.04) is deprecated update /etc/apt/sources.list.d/
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted"
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted"
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe"
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe"
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse"
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates multiverse"
    - "deb http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse"
    - "deb http://security.ubuntu.com/ubuntu trusty-security main restricted"
    - "deb http://security.ubuntu.com/ubuntu trusty-security universe"
    - "deb http://security.ubuntu.com/ubuntu trusty-security multiverse"
  when: ansible_lsb.codename == "trusty"
  tags: apt
```

##### EXPECTED RESULTS
`/etc/apt/sources.list.d/us_archive_ubuntu_com_ubuntu.list` would contain
```
deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb http://us.archive.ubuntu.com/ubuntu/ trusty universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
deb http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu trusty-security main restricted
deb http://security.ubuntu.com/ubuntu trusty-security universe
deb http://security.ubuntu.com/ubuntu trusty-security multiverse
```

##### ACTUAL RESULTS
The first iteration of the loop works and `deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted` is in the `/etc/apt/sources.list.d/us_archive_ubuntu_com_ubuntu.list` file but on the second iteration of the loop:
```paste below
<uart2.lab.testing.com> ESTABLISH SSH CONNECTION FOR USER: ansible
<uart2.lab.testing.com> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o ControlPath=/Users/tanner/.ansible/cp/a912f0eb8c uart2.lab.testing.com '/bin/sh -c '"'"'echo ~ansible && sleep 0'"'"''
<uart2.lab.testing.com> (255, b'', b'OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/tanner/.ssh/config\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: /Users/tanner/.ssh/config line 33: Applying options for *.lab.testing.com\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/tanner/.ansible/cp/a912f0eb8c" does not exist\r\ndebug2: resolving "uart2.lab.testing.com" port 22\r\nssh: Could not resolve hostname uart2.lab.testing.com: nodename nor servname provided, or not known\r\n')
failed: [uart2.lab.testing.com] (item=deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted) => {
    "ansible_loop_var": "item",
    "item": "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted",
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.9p1, LibreSSL 2.7.3\r\ndebug1: Reading configuration data /Users/tanner/.ssh/config\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: /Users/tanner/.ssh/config line 33: Applying options for *.lab.testing.com\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug3: kex names ok: [diffie-hellman-group1-sha1]\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/tanner/.ansible/cp/a912f0eb8c\" does not exist\r\ndebug2: resolving \"uart2.lab.testing.com\" port 22\r\nssh: Could not resolve hostname uart2.lab.testing.com: nodename nor servname provided, or not known",
    "unreachable": true
}
```
