### ISSUE TITLE
win_reg_stat fails when registry key is in HKEY_USERS\.DEFAULT hive

### ISSUE THREAD

**Issue by mgoleary** [ansible/ansible#59337]
##### SUMMARY
win_reg_stat module fails when running against keys in the HKEY_USERS\.DEFAULT hive. All other hives (HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE\*, etc) appear to be working fine, however. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_reg_stat module

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /home/admin/ansible-src/com/winrmtesting/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /users/ansible/lib/python2.7/site-packages/ansible
  executable location = /users/ansible/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/admin/ansible-src/com/winrmtesting/ansible.cfg) = [u'profile_tasks']
DEFAULT_HOST_LIST(/home/admin/ansible-src/com/winrmtesting/ansible.cfg) = [u'/home/admin/ansible-src/com/winrmtesting/inventory/hosts']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False

```

##### OS / ENVIRONMENT
target OS: Windows Server 2016 Datacenter

##### STEPS TO REPRODUCE

Run the win_reg_stat module against any key in the HKEY_USERS\.DEFAULT hive

```yaml
  - name: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications 
    win_reg_stat:
      path: 'HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications'
      name: NoToastApplicationNotificationOnLockScreen
    register: pushnotifications_regkey_stat

```

##### EXPECTED RESULTS

ok: [172.17.176.59] => {
    "pushnotifications_regkey_stat": {
        "changed": false, 
        "exists": true, 
        "failed": false, 
        "raw_value": 1, 
        "type": "REG_DWORD", 
        "value": 1
    }
}

##### ACTUAL RESULTS

```paste below
The full traceback is:
You cannot call a method on a null-valued expression.
At line:122 char:5
+     $registry_hive.Dispose()
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 122

fatal: [172.17.176.59]: FAILED! => {
    "changed": false, 
    "msg": "Unhandled exception while executing module: You cannot call a method on a null-valued expression."
}

```
