### ISSUE TITLE
win_domain / win_domain_controller - log path missing 

### ISSUE THREAD

**Issue by AirCombat** [ansible/ansible#59348]
##### SUMMARY

The equivelent powershell command to win_domain includes the option to specify log path:
```
Install-ADDSForest `
-DatabasePath "D:\Windows\NTDS" `
-SysvolPath "D:\Windows\SYSVOL" `
-LogPath "E:\Windows\NTDS"
```
This has been missed in the win_domain module but SYSVOL and Database path are included, this is not consistent.
In addition to this, the win_domain_controller does not include it as a parameter in docs but it is in the examples! but also has no effect.

Should be an easy fix to make, otherwise please fix the example in docs. Would be greatly appreciated. The only way to change this is by rebooting into restore mode while AD if offline.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_domain
win_domain_controller

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = /Users/redacted/projects/project/ansible/ansible.cfg
  configured module search path = ['/Users/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION
For example, the config below is ignored and the logs are in the C:\ drive
```
    win_domain:
      create_dns_delegation: no
      dns_domain_name: '{{ prod_domain_name }}'
      domain_netbios_name: '{{ prod_netbios }}'
      domain_mode: WinThreshold
      forest_mode: WinThreshold
      safe_mode_password: '{{ prod_dsrm_pass }}'
      database_path: D:\Windows\NTDS
      sysvol_path: D:\Windows\SYSVOL
      log_path: E:\Windows\NTDS
```

##### OS / ENVIRONMENT
Non OS Specific, Tested on Server 2019  and 2016

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
Logs go to E:\Windows\NTDS\ etc...

##### ACTUAL RESULTS
Logs go to %systemroot%\NTDS\
