### ISSUE TITLE
VMware: vmware_tag_manager ignores category_name

### ISSUE THREAD

**Issue by pugnacity** [ansible/ansible#59379]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_tag_manager

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /Users/pugnacity/projects/itsg/AP400/temp-dev-stage/ansible.cfg
  configured module search path = [u'/Users/pugnacity/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Mar  4 2019, 09:01:38) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### STEPS TO REPRODUCE

Create two Tag Categories within VMware and add to each Category the same Tags

in our example we've the following   category_names:
- NOC-DC-Backup
- CCB-C01-Backup

In each Category we've the same Tags, like NOB or LD.

Task for adding a tag to an VM: 

```yaml
- name: Add tags to a virtual machine
  vmware_tag_manager:
    hostname: "{{ pr_vsphere_vcenter_name }}"
    username: "{{ pr_vsphere_datacenter_username }}"
    password: "{{ pr_vsphere_datacenter_userpass }}"
    validate_certs: no
    tag_names:
      - CCB-C01-Backup:NOB
    object_name: "{{ inventory_hostname_short }}"
    object_type: VirtualMachine
    state: add
  delegate_to: localhost
```

##### EXPECTED RESULTS

Use the correct Tag from defined Category 
```yaml
changed: [dll0400-conf001 -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "hostname": "vc-noc.noclan.loc",
            "object_name": "dll0400-conf001",
            "object_type": "VirtualMachine",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "https",
            "state": "add",
            "tag_names": [
                "CCB-C01-Backup:NOB"
            ],
            "username": "SVC",
            "validate_certs": false
        }
    },
    "tag_status": {
        "current_tags": [
            "LD",
            "CCB-C01-Backup:NOB"
        ],
        "desired_tags": [
            "CCB-C01-Backup:NOB"
        ],
        "previous_tags": [
            "LD"
        ]
    }
}
```

##### ACTUAL RESULTS

Uses the correct Tag  Name but from  the category which was created first

```yaml
changed: [dll0400-conf001 -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "hostname": "vc-noc.noclan.loc",
            "object_name": "dll0400-conf001",
            "object_type": "VirtualMachine",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "https",
            "state": "add",
            "tag_names": [
                "CCB-C01-Backup:NOB"
            ],
            "username": "SVC",
            "validate_certs": false
        }
    },
    "tag_status": {
        "current_tags": [
            "LD",
            "NOB"
        ],
        "desired_tags": [
            "CCB-C01-Backup:NOB"
        ],
        "previous_tags": [
            "LD"
        ]
    }
}
```
