### ISSUE TITLE
ansible_failed_task can not found in a role when using block and include_role

### ISSUE THREAD

**Issue by jeffrey4l** [ansible/ansible#59370]
##### SUMMARY

`ansible_failed_task` and `ansible_failed_results` variable can not be used in a role which loaded by `import_role` in block rescue section.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```console
$ ansible --version
ansible 2.8.2
  config file = yyy
  configured module search path = ['xxx']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/sbin/ansible
  python version = 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
```

##### STEPS TO REPRODUCE

```yaml
# site.yml
---
- hosts: all
  gather_facts: false
  tasks:
    - block:
        - fail:
      rescue:
        - import_role:
            name: role1


# role/role1/tasks/main.yml
---
- debug:
    msg: |
      {{ ansible_failed_task|default('ansible_failed_task not found') }}
      {{ ansible_failed_result|default('ansible_failed_result not found') }}
```

##### EXPECTED RESULTS

we can get `ansible_failed_*` variable content in role tasks.

##### ACTUAL RESULTS

get `ansible_failed_tasks not found` ansible `ansible_failed_result not found`

```
ok: [127.0.0.1] => {
    "msg": "ansible_failed_task not found\nansible_failed_result not found\n"
}
```

if i change the `site.yml` like below, it works. 
```yaml
# site.yml
---
- hosts: all
  gather_facts: false
  tasks:
    - block:
        - fail:
      rescue:
        - debug: var=ansible_failed_result
        - import_role:
            name: role1
```
