### ISSUE TITLE
Homebrew output doesn't say what changed

### ISSUE THREAD

**Issue by glenjamin** [ansible/ansible#59376]
##### SUMMARY
At the moment, homebrew output with `-v` looks like this:
```
TASK [homebrew] **********************************************************************************************************************************************
changed: [127.0.0.1] => {"changed": true, "msg": "Changed: 1, Unchanged: 10"}
```
It would be helpful if it could say which packages were changed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
homebrew module

##### ADDITIONAL INFORMATION

This would make it clearer what actions were being performed when using the homebrew module

```yaml
  - homebrew:
      pkg:
        - ag
        - awscli
        - bash-completion
        - git
        - git-cola
        - jq
        - leiningen
        - mas
        - n
        - repo
        - tfenv
```
