### ISSUE TITLE
Handlers are being skipped on depndent role

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#59388]
##### SUMMARY
When role is installed as a role dependency with `when: False`, e.g.

```yaml
dependencies:
  - name: dependent_role
    src: git+git@mygit.git
    version: "v1.0"
    when: False
```
its handlers are not being run

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
import_role

##### ANSIBLE VERSION

```
2.8.2
```

##### CONFIGURATION
irrelevant

##### OS / ENVIRONMENT
irrelevant

##### STEPS TO REPRODUCE

1. Create a role with galaxy dependency. The role is not supposed to be run on installation -> thus `when: False`

```yaml
# roles/main_role/meta/main.yml

galaxy_info:
  author: Me
  description: my main role

dependencies:
  - name: dependent_role
    src: git+git@mygit.git
    version: "v1.0"
    when: False

# roles/main_role/tasks/main.yml
- import_role:
    role: dependent_role


```
2. Create the dependent role with a handler

```
# roles/dependent_role/tasks/main.yml

- debug:
    msg: "I will activate handler"
  changed_when: True
  notify: my handler

# roles/dependent_role/handlers/main.yml

- name: my handler
  debug:
    msg: "handler run"

```
3. Create a playbook to run it

```
# playbook.yml

- hosts: localhost
  connection: local
  tasks:
    - import_role:
        role: main_role
```

##### EXPECTED RESULTS
Handler is being run

##### ACTUAL RESULTS

Handler is being skipped

```

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [dependent_role : debug] **************************************************
skipping: [localhost]

TASK [dependent_role : debug] **************************************************
skipping: [localhost]

TASK [dependent_role : debug] **************************************************
ok: [localhost] => {
    "msg": "I won't activate handler"
}

TASK [dependent_role : debug] **************************************************
changed: [localhost] => {
    "msg": "I will activate handler"
}

RUNNING HANDLER [dependent_role : my handler] **********************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
```
