### ISSUE TITLE
YAML syntax does not allow group of groups

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#594]
As a matter of completeness, the INI file format allows to make a group of groups, which the YAML syntax doesn't do (yet). We should probably add code for this:

``` yaml
- group: animals
  groups: [ cat, dog, mouse ]
```

which is the same as:

``` yaml
- group: animals
  groups:
  - cat
  - dog  
  - mouse
```
