### ISSUE TITLE
docker_container doesnt support port ranges

### ISSUE THREAD

**Issue by kittys693** [ansible/ansible#59403]
##### SUMMARY
I tried to use  port range in docker container module and it throws an error.It works if I map individual ports

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/e2845/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]


```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Try to use docker_container module with port ranges 2003-2006:2003-2006

```yaml
```yaml
- name: Add Graphite container
  docker_container:
    name: graphite
    image: "graphiteapp/docker-graphite-statsd"
    networks:
      - name: "backend"
    published_ports:
      - "2003-2004:2003-2004"
      - "10000:80"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - "graphite:/opt/graphite/conf"
```

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
all ports mentioned should be published. Works in the below yaml
```yaml
- name: Add Graphite container
  docker_container:
    name: graphite
    image: "graphiteapp/docker-graphite-statsd"
    networks:
      - name: "backend"
    published_ports:
      - "2003:2003"
      - "2004:2004"
      - "10000:80"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - "graphite:/opt/graphite/conf"
```

##### ACTUAL RESULTS

"module_stdout": "Traceback (most recent call last):\r\n  File \"/home/kongsys-ansible/.ansible/tmp/ansible-tmp-1563820739.72-162452760206638/AnsiballZ_docker_container.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/kongsys-ansible/.ansible/tmp/ansible-tmp-1563820739.72-162452760206638/AnsiballZ_docker_container.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/kongsys-ansible/.ansible/tmp/ansible-tmp-1563820739.72-162452760206638/AnsiballZ_docker_container.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_docker_container_payload_3GoWTF/__main__.py\", line 2385, in <module>\r\n  File \"/tmp/ansible_docker_container_payload_3GoWTF/__main__.py\", line 2380, in main\r\n  File \"/tmp/ansible_docker_container_payload_3GoWTF/__main__.py\", line 1814, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_3GoWTF/__main__.py\", line 798, in __init__\r\n  File \"/tmp/ansible_docker_container_payload_3GoWTF/__main__.py\", line 1053, in _parse_publish_ports\r\nValueError: invalid literal for int() with base 10: '2003-2004'\r\n",

```paste below

```
