### ISSUE TITLE
ansible_play_host vars don't always match play

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#59401]
##### SUMMARY
When mid-play dynamic inventory actions (eg `add_host`, `meta: refresh_inventory` that causes hosts to appear/disappear) affect the host list for the currently-running play, `ansible_play_hosts` and `ansible_play_hosts_all` don't always reflect the current reality.

By design, the in-flight play will not start running tasks on newly-added hosts, but it will *stop* running tasks on hosts that have disappeared.

Newly-created hosts from an inventory refresh are immediately visible in `ansible_play_hosts`, even though they're not executing. Hosts added by an `add_host` do *not* appear in `ansible_play_hosts`. The behavior should probably be consistent, and favor reflecting what the current play is actually doing (ie the inventory refresh behavior seems incorrect).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
StrategyBase

##### ANSIBLE VERSION
2.8

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### STEPS TO REPRODUCE
Add a host mid-play via `meta: refresh_inventory`, dump `ansible_play_hosts`, note that the new host appears in the list. Add another host via `add_host` in the same play, dump `ansible_play_hosts`, note that the newest host does *not* appear.

##### EXPECTED RESULTS
Consistent behavior between dynamically-added hosts- preferably that `ansible_play_hosts` always shows the actual list of hosts executing for the current play at the current time.

##### ACTUAL RESULTS
Newly-added dynamic inventory-sourced hosts show up in `ansible_play_hosts`.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by vbotka** [comment]
1) Quoting from SUMMARY:

> By design, the in-flight play will not start running tasks on newly-added hosts, but it will stop running tasks on hosts that have disappeared.

Shouldn't this be mentioned both in *meta* and *add_host*?

2) I can't reproduce the problem in 2.12.1. What am I missing? Given the playbook and the inventory below

```yaml
shell> cat playbook.yml
- hosts: test
  gather_facts: false
  tasks:
    - debug:
        msg: |-
          ansible_play_hosts_all: {{ ansible_play_hosts_all|to_yaml }}
          ansible_play_hosts: {{ ansible_play_hosts|to_yaml }}
          ansible_play_batch: {{ ansible_play_batch|to_yaml }}
      run_once: true

    - lineinfile:
        path: hosts
        line: host03
      delegate_to: localhost
      run_once: true
      when: refresh_inventory|d(false)|bool
    - meta: refresh_inventory

    - add_host:
        name: host03
        groups: test
      run_once: true
      when: add_host|d(false)|bool

    - debug:
        msg: |-
          ansible_play_hosts_all: {{ ansible_play_hosts_all|to_yaml }}
          ansible_play_hosts: {{ ansible_play_hosts|to_yaml }}
          ansible_play_batch: {{ ansible_play_batch|to_yaml }}
      run_once: true

    - debug:
        var: hostvars.keys()|list
      run_once: true

    - debug:
        var: inventory_hostname

- hosts: test
  gather_facts: false
  tasks:
    - debug:
        var: inventory_hostname
```

```sh
shell> cat hosts
[test]
host01
host02
```

Both *add_host* and *refresh_inventory* give the same result

```sh
shell> ansible-playbook -i hosts playbook.yml -e add_host=true
```
gives (abridged)
```yaml
PLAY [test] **********************************************************************************

TASK [debug] *********************************************************************************
ok: [host01] => 
  msg: |-
    ansible_play_hosts_all: [host01, host02]
    ansible_play_hosts: [host01, host02]
    ansible_play_batch: [host01, host02]

TASK [lineinfile] ****************************************************************************
skipping: [host01]

TASK [meta] **********************************************************************************

TASK [add_host] ******************************************************************************
changed: [host01]

TASK [debug] *********************************************************************************
ok: [host01] => 
  msg: |-
    ansible_play_hosts_all: [host01, host02, host03]
    ansible_play_hosts: [host01, host02, host03]
    ansible_play_batch: [host01, host02]
```
```sh
shell> ansible-playbook -i hosts playbook.yml -e refresh_inventory=true
```
gives (abridged)
```yaml
PLAY [test] **********************************************************************************

TASK [debug] *********************************************************************************
ok: [host01] => 
  msg: |-
    ansible_play_hosts_all: [host01, host02]
    ansible_play_hosts: [host01, host02]
    ansible_play_batch: [host01, host02]

TASK [lineinfile] ****************************************************************************
changed: [host01 -> localhost]

TASK [meta] **********************************************************************************

TASK [add_host] ******************************************************************************
skipping: [host01]

TASK [debug] *********************************************************************************
ok: [host01] => 
  msg: |-
    ansible_play_hosts_all: [host01, host02, host03]
    ansible_play_hosts: [host01, host02, host03]
    ansible_play_batch: [host01, host02]
```
