### ISSUE TITLE
vmware_deploy_ovf The name already exists

### ISSUE THREAD

**Issue by bendaniels052** [ansible/ansible#59436]
##### SUMMARY
I'm trying to deploy multiple OVA files across our vmware farm using the `vmware_deploy_ovf` module. I'm required to run the same playbook more than once, with the playbook containing a set of vars for multiple VMs. This will require the module to be idempotent for when the VM already exists. However, when running the same playbook more than once, the play hangs on that module and displays an error message in vCenter, stating that the VM name is already there,
Note - there is no error handling message in the output of the play when running the playbook
  
Error `The name 'EU-LD8-Splunk-Data-Collector-1.bp.com' already exists.`

I've noticed this error since we'e upgraded our VMware vSphere from one version to another. 

Previous version - was able to use the module fine
```
vSphere Client version 6.5
```
Current version - Complaining that the VM is already there and doesnt skip
```
vSphere Client version 6.7.0.20000 
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`vmware_deploy_ovf `

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible_custom_modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.2 (default, Apr  2 2019, 10:14:42) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /home/dabhiy/.ansible/tmp/ansible-local-55475m3f4_ef
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible_custom_modules']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

##### STEPS TO REPRODUCE
Vars 
```
cnx_info:
  - name: EU-LD8-Splunk-Data-Collector-1.bp.com
    vc_host: xx.xxx.xx.xxx
    vc_user: xxxxxx
    vc_pass: xxxxxxx
    vc_state: yes
    vc_datacenter: EU-LD8-CNX
    vc_datastore: LD08-VM-DS01
    vc_folder: "EU-LD8-CNX/vm"
    vm_network:
      VM Network: "CNX-MGMT|CNX-MGMT|CNX-OOB"

ova_download_url: "{{ dml_url }}/{{ dml_repo }}/VMware/{{ app }}/splunk-ova-for-vmware_{{ splunk_version }}.ova"
ova_filename: 'splunk_plugin.ova'

dml_url: 'https://xxxxxxxxxx:443/artifactory'
app: Splunk
dml_repo: 'xx-xxxxxxx-tools-generic-local'
splunk_version: '345'

```
```
---

- name: Build VM infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - "group_vars/all/vault"
    - "group_vars/all/cnx_vars.yml"
  tasks:
  - name: Download OVA file
    get_url:
      url: "{{ ova_download_url }}"
      dest: "/tmp/{{ ova_filename }}"
      validate_certs: no
    delegate_to: "{{ delegation | default(omit) }}"
  - name: Create VMs in CNX
    vmware_deploy_ovf:
      hostname: "{{ item.vc_host }}"
      username: "{{ vc_user }}"
      password: "{{ vc_pass }}"
      validate_certs: no
      folder: "{{ item.vc_folder }}"
      datacenter: "{{ item.vc_datacenter }}"
      datastore: "{{ item.vc_datastore }}"
      resource_pool: "{{ vm_resource_pool }}"
      ovf: "/tmp/{{ ova_filename }}"
      power_on:  "{{ item.vc_state }}"
      name: "{{ item.name }}"
      networks: "{{ item.vm_network }}"
    with_items: "{{ cnx_info }}"
    loop_control:
      label: "{{ item.name }}"
    register: create_vm
```

##### EXPECTED RESULTS
First Run
```
PLAY [Build VM infrastructure] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Download OVA file] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create VMs in CNX] *************************************************************************************************************************************************************************************
changed: [localhost] => (item=EU-LD8-Splunk-Data-Collector-1.bp.com)
changed: [localhost] => (item=EU-LD6-Splunk-Data-Collector-1.bp.com)
changed: [localhost] => (item=NA-DA7-Splunk-Data-Collector-1.bp.com)
changed: [localhost] => (item=NA-CH3-Splunk-Data-Collector-1.bp.com)
```
Second Run
```
PLAY [Build VM infrastructure] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Download OVA file] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create VMs in CNX] *************************************************************************************************************************************************************************************
ok: [localhost] => (item=EU-LD8-Splunk-Data-Collector-1.bp.com)
ok: [localhost] => (item=EU-LD6-Splunk-Data-Collector-1.bp.com)
ok: [localhost] => (item=NA-DA7-Splunk-Data-Collector-1.bp.com)
ok: [localhost] => (item=NA-CH3-Splunk-Data-Collector-1.bp.com)
```
##### ACTUAL RESULTS
Second run - User interrupted as the module hangs with no error handling - error displayed in vCenter. 
```
PLAY [Build VM infrastructure] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Download OVA file] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create VMs in CNX] *************************************************************************************************************************************************************************************
^C [ERROR]: User interrupted execution
```
Error in vCenter
```
Deploy OVF template
Status:
The name 'EU-LD8-Splunk-Data-Collector-1.bp.com' already exists.
```
