### ISSUE TITLE
Using state in with_items with apt module leads to confusing behaviour

### ISSUE THREAD

**Issue by Habbie** [ansible/ansible#5943]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.4
##### Environment:

From: Mac OS X Mavericks, ansible installed from Homebrew
Managing: Debian Testing (Jessie)
##### Summary:

Putting state=X into with_items with apt: pkg={{ item }} yields confusing and inconsistent output and behaviour.
##### Steps To Reproduce:

Status: I have bundler and socat installed, and ruby-ffi\* are NOT installed.

When I run this task:

```
  - name: install remotebackend test deps
    apt: pkg={{ item }}
    with_items:
    - bundler
    - socat
    - ruby-ffi state=absent  # leave to local bundler
    - ruby-ffi-rzmq state=absent
```

(I can see how what I'm doing is wrong - interpolating state=X into the pkg= argument).
##### Expected Results:

No changes.
##### Actual Results:

I get output:

```
changed: [pdnsdev] => (item=bundler,socat,ruby-ffi state=absent,ruby-ffi-rzmq state=absent)
```

And now bundler and socat are gone. The output does not suggest it would remove them, and it is not what I expected.
