### ISSUE TITLE
URI modules shows - 401 authentication error

### ISSUE THREAD

**Issue by Rajinikamu84** [ansible/ansible#59447]
##### SUMMARY
ansible "uri" module throws 401 authentication error even i provided the valid "username" and password" 

REST API URL runs on IIS web server with "windows_authentication" enabled.

##### ISSUE TYPE
Status code was 401 and not [200]: HTTP Error 401: Unauthorized"

##### COMPONENT NAME
uri

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 20 2019, 12:21:26) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.6 

##### STEPS TO REPRODUCE

```yaml
---
- name: DNS API QUERY
  hosts: localhost
  gather_facts: no
  tasks:
    - name: DNS QUERY
      uri:
        url: "http://{{api_url}}/api/consumeBAMFunctions/"
        method: POST
        body_format: json
        body:
          DNSAction: Query
          QueryName: "ViewsByConfiguration"
        user:  "A2165545"
        password: "*********"
        return_content: yes
        status_code: 200
      register: dns
      tags: dns

```

##### EXPECTED RESULTS

 "",
        "Type  Output                                                                                                           ",
        "----  ------                                                                                                           ",
        "Query {@{id=35176; name=3-Internal; type=View; properties=}, @{id=6590105; name=External; type=View; properties=}, @...",
        "",
        ""

##### ACTUAL RESULTS

```paste below
 },
    "msg": "Status code was 401 and not [200]: HTTP Error 401: Unauthorized",
    "redirected": false,
    "server": "",
    "status": 401,
    "url": "http://{{api_url}}/api/consumeBAMFunctions/",
    "www_authenticate": "Negotiate, NTLM"

```
