### ISSUE TITLE
ios_interface gives keyerror exception on virtual interface with whitespace

### ISSUE THREAD

**Issue by jellestoel** [ansible/ansible#59440]
##### SUMMARY
 Using the  ios_interfaces module with a virtual tunnel interface with type tunnel present in the router configuration, will return a keyError exception.

This is caused by a regex expression in map_config_to_obj at /modules/network/ios/ios_interface.py:202
When the expression matches an interface, it includes only the first word, even when the interface value has multiple whitespace seperated words

```
def map_config_to_obj(module):
    config = get_config(module)
    configobj = NetworkConfig(indent=1, contents=config)

    match = re.findall(r'^interface (\S+)', config, re.M)
    if not match:
        return list()

    instances = list()

    for item in set(match):
        obj = {
            'name': item,
            'description': parse_config_argument(configobj, item, 'description'),
            'speed': parse_config_argument(configobj, item, 'speed'),
            'duplex': parse_config_argument(configobj, item, 'duplex'),
            'mtu': parse_config_argument(configobj, item, 'mtu'),
            'disable': True if parse_shutdown(configobj, item) else False,
            'state': 'present'
        }
        instances.append(obj)
    return instances
```

because the multi word interface is only included partialy in the list of matches a keyerror exception occurs below:
```
def parse_config_argument(configobj, name, arg=None):
    cfg = configobj['interface %s' % name]
    cfg = '\n'.join(cfg.children)
    match = re.search(r'%s (.+)$' % arg, cfg, re.M)
    if match:
        return match.group(1)
```

When the regex expression is changed to the following no keyError exception occurs:
match = re.search(r'%s (.+.*)$' % arg, cfg, re.M)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

    

map_config_to_obj in ios_interface.py

when changing 
```match = re.findall(r'^interface (\S+)', config, re.M)```
to 
```match = re.findall(r'^interface (\S+.*)', config, re.M)```
the exception no longer occurs

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/root/.ansible.cfg) = True
DEFAULT_DEBUG(/root/.ansible.cfg) = False
DEFAULT_HOST_LIST(/root/.ansible.cfg) = [u'/opt/hosts']
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_LOG_PATH(/root/.ansible.cfg) = /opt/ansible.log
DEFAULT_STDOUT_CALLBACK(/root/.ansible.cfg) = yaml
DEFAULT_TRANSPORT(/root/.ansible.cfg) = smart
HOST_KEY_CHECKING(/root/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
ansible host  
Linux c22-svp-ops001.c22.klanten.netco.nl 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cisco router  
System image file is "flash:c800-universalk9-mz.SPA.154-3.M3.bin"  
Cisco C887VAG-4G-GA-K9 (revision 1.0) with 887884K/29619K bytes of memory.  
##### STEPS TO REPRODUCE

create a virtual tunnel interface on your cisco router:  
```
interface Virtual-Template1 type tunnel
 ip unnumbered Vlan2
 ip mtu 1400
 ip tcp adjust-mss 1360
 tunnel mode ipsec ipv4
!
```

any parameters to ios_interface will do:
```
---
-   connection: network_cli
    hosts: Routers
    gather_facts: no

    tasks:
      - name: remove interface
        ios_interface:
          name: Vlan74
          state: absent
```

##### EXPECTED RESULTS
```
changed: [c22-0001-rt01] => changed=true
  commands:
  - no interface Vlan74
  invocation:
    module_args:
      aggregate: null
      auth_pass: null
      authorize: null
      delay: 10
      description: null
      duplex: null
      enabled: true
      host: null
      mtu: null
      name: Vlan74
      neighbors: null
      password: null
      port: null
      provider: null
      rx_rate: null
      speed: null
      ssh_keyfile: null
      state: absent
      timeout: null
      tx_rate: null
      username: null
META: ran handlers
META: ran handlers
```

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-1242x_B8yg/ansible-tmp-1563886489.01-227741760575802/AnsiballZ_ios_interface.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-1242x_B8yg/ansible-tmp-1563886489.01-227741760575802/AnsiballZ_ios_interface.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-1242x_B8yg/ansible-tmp-1563886489.01-227741760575802/AnsiballZ_ios_interface.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ios_interface_payload_LYbwnM/__main__.py", line 492, in <module>
  File "/tmp/ansible_ios_interface_payload_LYbwnM/__main__.py", line 472, in main
  File "/tmp/ansible_ios_interface_payload_LYbwnM/__main__.py", line 234, in map_config_to_obj
  File "/tmp/ansible_ios_interface_payload_LYbwnM/__main__.py", line 200, in parse_config_argument
  File "/tmp/ansible_ios_interface_payload_LYbwnM/ansible_ios_interface_payload.zip/ansible/module_utils/network/common/config.py", line 196, in __getitem__
KeyError: u'interface Virtual-Template1'
```
