### ISSUE TITLE
Add support for outputs only in terraform module

### ISSUE THREAD

**Issue by bkmeneguello** [ansible/ansible#59446]
##### SUMMARY

Allow to gather outputs only from terraform module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

terraform

##### ADDITIONAL INFORMATION

Sometimes we just want to gather information from Terraform, without need to run a full "plan". Should be nice to have this shortcut.

```yaml
terraform:
  state: outputs
  project_path: '{{ project_dir }}'
register: terraform
```
