### ISSUE TITLE
win_domain_user attributes do not comply with convention and cannot be fixed using module

### ISSUE THREAD

**Issue by AirCombat** [ansible/ansible#59485]
##### SUMMARY
Hi,

I am trying to create users that have attributes consistent with the format microsoft intends for those fields. Active Directory will create users with the following values:
```
cn                  John Smith
displayName         John Smith
name                John Smith
displayName         John Smith
userPrincipalName   jsmith@domain
sAMAccountName      jsmith
```
win_domain_user creates users with the sAMAccountName set to the display name instead of username. The breaks multiple applications which rely on sAMAccountName for login.

If I try to correct this by setting sAMAccountName seperately as custom value "jsmith" it fails with various errors and cannot reference that object in future plays.

You also cannot set 'name' as an attribute. 

So it appears win_domain user is creating an account with one attribute as the identifier, and then tries to search for that account in future using a different attrib.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_user 

##### ANSIBLE VERSION

```
ansible 2.8.2
  config file = /Users/redacted/projects/redacted/git/ansible/ansible.cfg
  configured module search path = ['/Users/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```
blank
```

##### OS / ENVIRONMENT
OSX 10.14.5
ansible hosts: WIndows Server 2019, Domain Function Level 2016

##### STEPS TO REPRODUCE

```
vars.yml
temp_pass: example
users:
  - username: jsmith
    firstname: John
    surname: Smith
    email: jsmith@example.com
    password: '{{ temp_pass }}'
    path: '{{ org_unit_users }}'
    groups: 
      - Example_Group
    company: Company
    update_password: on_create
    password_never_expires: no
    enabled: yes
    state: present

task.yml
---
- name: Prod Domain Users Exist
  win_domain_user:
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    name: "{{ item.firstname + ' ' + item.surname }}"
    upn: "{{ item.username + '@' + prod_domain_name }}"
    groups: "{{ item.groups }}"
    path: '{{ item.path }}'
    update_password: "{{ item.update_password }}"
    password: "{{ item.password }}"
    password_never_expires: "{{ item.password_never_expires }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ ad_users }}"
```

##### EXPECTED RESULTS

```
cn                 John Smith
displayName        John Smith
name               John Smith
userPrincipalName  jsmith@domain
sAMAccountName     jsmith
```

##### ACTUAL RESULTS
Creates user with the following attributes:
```
cn                 John Smith
displayName (Empty)
name               John Smith
userPrincipalName  jsmith@domain
sAMAccountName     John Smith
```

or, if you try to correct the module by specifying custom attributes: Upon initial account creations, successfully creates user but gives this error:

> Cannot find an object with identity: 'John Smith' under: 'DC=example,DC=com

Subsequent runs give the following error:

> An attempt was made to add an object to the directory with a name that is already in use

If i change the value of the name attribute in ansible to 
name: "{{ item.username }}"
from
name: "{{ item.firstname + ' ' + item.surname }}"

it will see the account successfully but will create future accounts with incorrect attributes.

Ideally the module should ask for username and domain name, set the SAMAccoutName to the username and set the UPN to username@domain and set the display name to Firstname Lastname if not set explicitly.
