### ISSUE TITLE
yum or package module - No package matching is available when using url

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible#59509]
##### SUMMARY
The install of package via `yum` or `package` module from url doesn't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum
package

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = None
  configured module search path = ['/Users/home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:15:00) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```yaml
    - name: install sumologic collector
      become: yes
      package:
        name: https://collectors.eu.sumologic.com/rest/download/rpm/64
        state: present
```

##### OS / ENVIRONMENT
Running playbook on MacOS.
Ansible installed via `brew install ansible`

##### STEPS TO REPRODUCE
Run the above playbook.

##### EXPECTED RESULTS
Package installed.

##### ACTUAL RESULTS

```paste below
    amazon-ebs: TASK [install sumologic collector] *********************************************
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'https://collectors.eu.sumologic.com/rest/download/rpm/64' is available"}
```
