### ISSUE TITLE
Netbox: Ability to query for non-device/vm related data

### ISSUE THREAD

**Issue by cpmills1975** [ansible/ansible#59558]
##### SUMMARY

Modules designed to modify Netbox also provide a means to query Netbox -or- lookup plugins to obtain lists of information from Netbox

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

netbox_*

##### ADDITIONAL INFORMATION

I see a number of people are contributing on writing modules to modify data held in Netbox. It would be useful if these modules, or perhaps a generic 'query' module could simply retrieve data from this area of Netbox.

I have a simple use-case where I want to add Hostgroups to Nagios/Icinga that reflect my tenants in Netbox. I'd like to query the Netbox tenants endpoint, simply to return a list of existing tenants. I don't need or want to modify this data, just return it.

This is, I believe, a different ask to the inventory plugin which already allows me to return details of devices and virtual machines.

Similar queries might be for a list of sites, list of roles, etc. Basically allowing a lookup of anything that isn't a device or virtual machine.

I'm open minded as to whether this should be integrated in to the modules that modify Netbox data - perhaps as a state: query or similar, or whether it should be a generic netbox_query module or a slightly more specific netbox_query_tenants, netbox_query_sites, etc.

```yaml

tasks:

  - name: Query Nebox tenants
    netbox_tenants:
      netbox_api_endpoint: http://localhost:8080/
      netbox_api_token: AAABBBCCC...YYYZZZ
      state: query

  - name: Query Netbox tenants
    netbox_query:
      netbox_api_endpoint: http://localhost:8080/
      netbox_api_token: AAABBBCCC.....YYYZZZ
      query: tenants

  - name: Output list of Netbox tenants
    debug: "{{ lookup('netbox', 'tenants', netbox_api_token='AAABBBCCC...XXX', netbox_api_endpoint='http://localhost:8080/') }}"
```
