### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by nicolemon** [ansible/ansible#59560]
##### SUMMARY

Add GitHub Enterprise support to the GitHub modules that don't currently support it by adding a single optional parameter for the GitHub API URL which defaults to non-enterprise GitHub, similar to how this is handled in the `github_webhook` module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- `github_deploy_key`
- `github_key`
- `github_issue`
- `github_release`

##### ADDITIONAL INFORMATION

`github_issue` and `github_release` are written with `github3` library, which does not support GitHub Enterprise. Proposing a refactor or re-implementation to use `PyGithub` or `requests` API.

```yaml
- name: get issue status from github repository
  github_issue:
    action: get_status
    organization: ansible
    repo: ansible
    issue: 59560
    github_url: https://github.company.com
```
