### ISSUE TITLE
can't ssh access to VM after create instance... gcp_compute_instance

### ISSUE THREAD

**Issue by Nurlan199206** [ansible/ansible#59573]
##### SUMMARY

I am using gcp_compute_instance for deploy instances but can't SSH access after instance creation.
![gcp](https://user-images.githubusercontent.com/22808731/61858304-a9258e80-aee7-11e9-8a51-43c5ce896dbc.PNG)

![image](https://user-images.githubusercontent.com/22808731/61857317-b6417e00-aee5-11e9-97c9-61dc3c7df94f.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`gcp_compute_instance`

##### ANSIBLE VERSION

```paste below
`2.8.2`
```

##### CONFIGURATION

```paste below
no changes, default config

`ansible-config dump --only-changed` command is empy

```

##### OS / ENVIRONMENT

`CentOS Linux release 7.6.1810 (Core) `

##### STEPS TO REPRODUCE

```
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address

   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: Add tags to instance
     gce_tag:
       instance_name: test-vm
       tags: http-server,https-server
       zone: europe-west4-c
       service_account_email: "nurlanizimbetov@gmail.com"
       state: present

   - name: create a firewall
     gcp_compute_firewall:
       name: test-vm
       allowed:
       - ip_protocol: tcp
         ports:
         - '22'
       target_tags:
       - test-vm
       source_tags:
       - test-vm
       project: web1-215116
       auth_kind: serviceaccount
       service_account_file: "{{ gcp_cred_file }}"
       state: present
```

```yaml
` ansible-playbook /etc/ansible/roles/gcp/tasks/ansible-gcp.yml`
```

##### EXPECTED RESULTS

instance must be create with ssh and http, https access

##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/google/gcp_compute_instance.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gcp_compute_instance.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @erjohnso @googlecloudplatform @rambleraptor
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @erjohnso @googlecloudplatform @rambleraptor
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by octohedron** [comment]
I had the same problem, and noticed that the network and subsequently firewall rules for the `test-vm` were wrong
![fw-rules-test-vm](https://user-images.githubusercontent.com/7332540/62368793-f29c5c00-b52d-11e9-9f10-c0b2f9b4f858.png)
This is a working VM for comparison
![firewall-rules-healthy](https://user-images.githubusercontent.com/7332540/62368816-02b43b80-b52e-11e9-97b6-d2de2db721bd.png)


As explained in the docs

> **network**
> Specifies the title of an existing network. When creating an instance, if neither the network nor the subnetwork is specified, the default network global/networks/default is used; if the network is not specified but the subnetwork is specified, the network is inferred.

It took me a few minutes to figure out that what all of that meant was that setting the `network` value to `null` would choose the `default` network interface and fix the issue, like

```yml
    - name: Create an instance
      gcp_compute_instance:
        state: present
        name: test-vm
        machine_type: f1-micro
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: null
            access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
      register: instance
```
So, I suggest updating that document to say something more clear/suitable/specific, i.e.

> Setting the **network** value to **null** will select the **default** network interface, which could have SSH already configured.
