### ISSUE TITLE
VMware: vmware_guest_network: adding new network adapter reports "Network 'VM Network' does not exist"

### ISSUE THREAD

**Issue by keirazhang** [ansible/ansible#59572]
##### SUMMARY

Adding new network adapter always reports network doesn't exist
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_network
##### ANSIBLE VERSION

```
ansible 2.9.0.dev0
  config file = /home/qiz/workspace/gitlab/newgos_testing/ansible.cfg
  configured module search path = [u'/home/qiz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/qiz/workspace/github/ansible/lib/ansible
  executable location = /home/qiz/workspace/github/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_SSH_RETRIES(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = 5
DEFAULT_BECOME(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = [u'/home/qiz/workspace/gitlab/newgos_testi
DEFAULT_HOST_LIST(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = [u'/home/qiz/workspace/gitlab/newgos_testing/hosts']
DISPLAY_SKIPPED_HOSTS(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = False
HOST_KEY_CHECKING(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/qiz/workspace/gitlab/newgos_testing/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```
- hosts: localhost
  vars_files:
     - ../vars/test.yml
  tasks:
    - name: "Add a new network adapter"
      vmware_guest_network:
        hostname: "10.117.17.14"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "10.117.17.14"
        validate_certs: "{{ valid_cert | default(False) }}"
        datacenter: "{{ datacenter | default('ha-datacenter') }}"
        folder: "{{ folder | default('/') }}"
        name: "{{ vm_name }}"
        networks:
          - name: 'VM Network'
            state: new 
            device_type: "e1000"
            connected: True
            start_connected: True
      delegate_to: localhost
```

##### EXPECTED RESULTS

New network adapter is added

##### ACTUAL RESULTS

```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "cluster": null, 
            "datacenter": "ha-datacenter", 
            "esxi_hostname": "10.117.17.14", 
            "folder": "/", 
            "gather_network_facts": false, 
            "hostname": "10.117.17.14", 
            "moid": null, 
            "name": "qiz-001-ubuntu-19.04", 
            "networks": [
                {
                    "connected": true, 
                    "device_type": "e1000", 
                    "name": "VM Network", 
                    "start_connected": true, 
                    "state": "new"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "username": "root", 
            "uuid": null, 
            "validate_certs": false
        }
    }, 
    "msg": "Network 'VM Network' does not exist."
}
```
