### ISSUE TITLE
Netbox: support for Custom Field choices

### ISSUE THREAD

**Issue by pugnacity** [ansible/ansible#59581]
##### SUMMARY
When creating a filter for a custom field from type selection it would be great to use the label instead of the ID.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
netbox

##### ADDITIONAL INFORMATION
I would expect when query for a custom field i could use the label field instead the ID.
```yaml
plugin: netbox
api_endpoint: http://netbox.domain.tld
query_filters:
  - cf_system_stage: dev
```
The Netbox API does support this, when the `/api/extras/_custom_field_choices/` has been used, see also [Netbox issue #1792](https://github.com/netbox-community/netbox/issues/1792)
