### ISSUE TITLE
Allow empty/omitted block_duration_minutes in ec2_launch_template module

### ISSUE THREAD

**Issue by GoodMirek** [ansible/ansible#59600]
##### SUMMARY
Thanks to @ryansb, we already have `ec2_launch_template` module, implemented in `lib/ansible/modules/cloud/amazon/ec2_launch_template.py`. While specifying `instance_market_options` as `spot` the module currently does not allow to omit key `block_duration_minutes`. This is causing an issue and hopefully could be improved.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_launch_template

##### ADDITIONAL INFORMATION

If `block_duration_minutes` is omitted, a different kind of spot instances is launched. This kind of instances is preemptible, with two minutes notice period. Duration of run time of such instances is not limited by default. These instances are preempted/terminated according to AWS needs.
If  `block_duration_minutes` is specified, a spot instance with fixed life time is launched. These instances are not preemptible and are more expensive.
I believe that boto3 supports the proposed feature, as AWS CLI supports that.

```yaml
    - name: Create launch template for preemptible spot instances
      ec2_launch_template:
        region: us-east-1
        template_name: preemptible-spot-instance
        security_group_ids: sg-123456
        instance_type: t3a.small
        key_name: ansible-key
        iam_instance_profile: ec2-profile
        credit_specification:
          cpu_credits: unlimited
        monitoring:
          enabled: true
        instance_market_options:
          market_type: spot
          spot_options:
            # block_duration_minutes: 
            instance_interruption_behavior: terminate
            max_price: "0.0204"
            spot_instance_type: one-time
        image_id: ami-987654321
```
