### ISSUE TITLE
Segregate dump and import operations from mysql_db module

### ISSUE THREAD

**Issue by pratikgadiya12** [ansible/ansible#59621]
##### SUMMARY
Supporting new options in ansible mysql dump/import operation will create more complexity in mysql_db module. So it's better to segregate dump and import operations to new modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
!lib/ansible/modules/database/mysql/mysql_db.py

##### ADDITIONAL INFORMATION
**Usage**:
```yaml
- name: Dump operation
  mysql_dump:
    name:
      - "{{ database_1 }}"
      - "{{ database_2 }}"
    target: "{{ dump_file }}"

- name: Import operation
  mysql_import:
    name: '{{ database_name }}'
    target: '{{ dump_file }}'
```

**Why it is needed and what it would solve?**

This will maintain code simplicity even after supporting multiple options for mysql dump/import.

Idea credit: @felixfontein and @Akasurde
