### ISSUE TITLE
win_dsc / ScheduledTask start time not working in 2.8

### ISSUE THREAD

**Issue by mmundy1** [ansible/ansible#59667]
##### SUMMARY

Calling win_dsc with the ScheduledTask resource from https://github.com/PowerShell/ComputerManagementDsc/wiki/ScheduledTask 
worked in 2.7 but fails in 2.8 - Tested in 2.8.2 and 2.8.3.
Possibly related to the exec_wrapper.  The AnsiballZ_win_dsc.ps1 LOOKS correct...
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_dsc
##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = None
  configured module search path = [u'/home/mundym/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7 for Ansible, target OS is Windows Server 2016

##### STEPS TO REPRODUCE

Try to create a scheduled task with minimal options but definitely include start time

```yaml
    - set_fact:
        scheduled_tasks:
          - task_name: "Task"
            task_path: "{{task_path}}"
            action_executable: "powershell.exe"
            action_arguments: "scriptname"
            action_workingpath: "dir"
            schedule_type: Daily
            days_interval: 1
            start_time: "06:00PM"
             executeas_credential_username: "User"
             executeas_credential_password:  "Password"
             start_when_available: False
             execution_timelimit: "72:00:00"
            logon_type: Password
            state: Present
    - win_psmodule:
        name: ComputerManagementDsc
    - win_dsc:
        resource_name: ScheduledTask
        TaskName                    : "{{ item.task_name }}"
        TaskPath                    : "{{ task_path }}"
        Description                 : "{{ item.description | default(omit) }}"
        ActionExecutable            : "{{ item.action_executable }}"
        ActionArguments             : "{{ item.action_arguments | default(omit) }}"
        ActionWorkingPath           : "{{ item.action_workingpath | default(omit) }}"
        ScheduleType                : "{{ item.schedule_type}}"
        DaysInterval                : "{{ item.days_interval | default(omit) }}"
        WeeksInterval               : "{{ item.weeks_interval | default(omit) }}"
        RepeatInterval              : "{{ item.repeat_interval | default(omit) }}"
        StartTime                   : "{{ item.start_time | default(omit) }}"
        DaysOfWeek                  : "{{ item.days_of_week | default(omit) }}"
        ExecuteAsCredential_username: "{{ item.executeas_credential_username | default(omit) }}"
        ExecuteAsCredential_password: "{{ item.executeas_credential_password | default(omit) }}"
        LogonType                   : "{{ item.logon_type | default(omit) }}"
        RandomDelay                 : "{{ item.random_delay | default(omit) }}"
        RepetitionDuration          : "{{ item.repetition_duration | default('Indefinitely') }}"
        DisallowDemandStart         : "{{ item.disallow_demand_start   | default(False) }}"
        DisallowHardTerminate       : "{{ item.disallow_hard_terminate | default(False) }}"
        Compatibility               : "{{ item.compatibility | default('Vista') }}"
        Hidden                      : "{{ item.hidden | default(False) }}"
        RunOnlyIfIdle               : "{{ item.run_only_if_idle   | default(omit) }}"
        IdleDuration                : "{{ item.idle_duration | default(omit) }}"
        IdleWaitTimeout             : "{{ item.idle_wait_timeout  | default(omit) }}"
        RestartOnIdle               : "{{ item.restart_on_idle    | default(omit) }}"
        DontStopOnIdleEnd           : "{{ item.dont_stop_on_idle_end | default(omit) }}"
        DisallowStartOnRemoteAppSession: "{{ item.disallow_start_on_remote_app_session | default(False) }}"
        ExecutionTimeLimit          : "{{ item.execution_time_limit  | default(omit) }}"
        RestartCount                : "{{ item.restart_count  | default(omit) }}"
        RestartInterval             : "{{ item.restart_interval  | default(omit) }}"
        multipleInstances           : "{{ item.multiple_instances | default('IgnoreNew') }}"
        Priority                    : "{{ item.priority| default('7') }}"
        RunLevel                    : "{{ item.runlevel | default('Limited') }}"
        Enable                      : true
        Ensure                      : Present
      loop: "{{scheduled_tasks}}"
```

##### EXPECTED RESULTS

Task will be created

##### ACTUAL RESULTS

```paste below
 "msg": "argument for StartTime is of type System.String and we were unable to convert to delegate: Exception calling \"ParseExact\" with \"4\" argument(s): \"String was not recognized as a valid DateTime.\""
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_dsc.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_dsc.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @nitzmahone @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @nitzmahone @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ShachafGoldstein** [comment]
Can you add the vars you are using?

**Comment by mmundy1** [comment]
See the scheduled_tasks fact being set at the top. 
Slightly less obfuscated:
(consoleapp_dir = "d:\\scripts\\")
- task_name: "Task"
            task_path: "Batches"
            action_executable: "powershell.exe"
            action_arguments: "{{consoleapp_dir}}\\{{consoleapp_script_name}}"
            action_workingpath: "{{consoleapp_dir}}"
            action_executable: 
            schedule_type: Daily
            days_interval: 1
            start_time: "06:00PM"
             executeas_credential_username: "User"
             executeas_credential_password:  "Password"
             start_when_available: False
             execution_timelimit: "72:00:00"
            logon_type: Password
            state: Present

**Comment by jborean93** [comment]
The win_dsc module went through a massive overhaul in Ansible 2.8 but it looks like there has been a regression on DateTime fields. I know you've supplied the vars but can you also share the output of the task when running with `-vvv`. That will tells us exactly what vars were passed to the module during execution.

What it looks like it happening is that we only accept a date time in a specific format, IIRC it's ISO 8601, but older versions were a bit more lenient. The question is whether they were actually applied correctly in older versions or were just silently ignored.

**Comment by mmundy1** [comment]
No problem!
Here is a quick test playbook (hostname, username, password store path only things changed)
`- hosts: testhost.testdomain.local
  tasks:
    - set_fact:
        scheduled_tasks:
          - task_name: "TestTask"
            task_path: "TestTasks"
            action_executable: "powershell.exe"
            action_arguments: "-c 'write-host \"TEST\" | out-file d:/test"
            action_workingpath: "d:/"
            schedule_type: Daily
            days_interval: 1
            start_time: "06:00PM"
            executeas_credential_username: "TESTDOMAIN\\mundym"
            executeas_credential_password:  "{{ lookup('passwordstore', 'mundym@testdomain.local')}}"
            start_when_available: False
            execution_timelimit: "72:00:00"
            logon_type: Password
            state: Present
    - win_psmodule:
        name: ComputerManagementDsc
    - win_dsc:
        resource_name: ScheduledTask
        TaskName                    : "{{ item.task_name }}"
        TaskPath                    : "{{ item.task_path }}"
        Description                 : "{{ item.description | default(omit) }}"
        ActionExecutable            : "{{ item.action_executable }}"
        ActionArguments             : "{{ item.action_arguments | default(omit) }}"
        ActionWorkingPath           : "{{ item.action_workingpath | default(omit) }}"
        ScheduleType                : "{{ item.schedule_type}}"
        DaysInterval                : "{{ item.days_interval | default(omit) }}"
        WeeksInterval               : "{{ item.weeks_interval | default(omit) }}"
        RepeatInterval              : "{{ item.repeat_interval | default(omit) }}"
        StartTime                   : "{{ item.start_time | default(omit) }}"
        DaysOfWeek                  : "{{ item.days_of_week | default(omit) }}"
        ExecuteAsCredential_username: "{{ item.executeas_credential_username | default(omit) }}"
        ExecuteAsCredential_password: "{{ item.executeas_credential_password | default(omit) }}"
        LogonType                   : "{{ item.logon_type | default(omit) }}"
        RandomDelay                 : "{{ item.random_delay | default(omit) }}"
        RepetitionDuration          : "{{ item.repetition_duration | default('Indefinitely') }}"
        DisallowDemandStart         : "{{ item.disallow_demand_start   | default(False) }}"
        DisallowHardTerminate       : "{{ item.disallow_hard_terminate | default(False) }}"
        Compatibility               : "{{ item.compatibility | default('Vista') }}"
        Hidden                      : "{{ item.hidden | default(False) }}"
        RunOnlyIfIdle               : "{{ item.run_only_if_idle   | default(omit) }}"
        IdleDuration                : "{{ item.idle_duration | default(omit) }}"
        IdleWaitTimeout             : "{{ item.idle_wait_timeout  | default(omit) }}"
        RestartOnIdle               : "{{ item.restart_on_idle    | default(omit) }}"
        DontStopOnIdleEnd           : "{{ item.dont_stop_on_idle_end | default(omit) }}"
        DisallowStartOnRemoteAppSession: "{{ item.disallow_start_on_remote_app_session | default(False) }}"
        ExecutionTimeLimit          : "{{ item.execution_time_limit  | default(omit) }}"
        RestartCount                : "{{ item.restart_count  | default(omit) }}"
        RestartInterval             : "{{ item.restart_interval  | default(omit) }}"
        multipleInstances           : "{{ item.multiple_instances | default('IgnoreNew') }}"
        Priority                    : "{{ item.priority| default('7') }}"
        RunLevel                    : "{{ item.runlevel | default('Limited') }}"
        Enable                      : true
        Ensure                      : Present
      loop: "{{scheduled_tasks}}"
`
and here is the -vvv output (same vars obfuscated) for 2.8.3:
`
% ansible-playbook -i inventory test-ScheduledTask.yml -vvv
ansible-playbook 2.8.3
  config file = None
  configured module search path = [u'/home/mundym/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
                "executeas_credential_username": "TESTDOMAIN\\mundym",
                "execution_timelimit": "72:00:00",
                "logon_type": "Password",
                "schedule_type": "Daily",
                "start_time": "06:00PM",
                "start_when_available": false,
                "state": "Present",
                "task_name": "TestTask",
                "task_path": "TestTasks"
            }
        ]
    },
    "changed": false
}

TASK [win_psmodule] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:19
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_psmodule.ps1
Pipelining is enabled.
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
ok: [testhost.testdomain.local] => {
    "changed": false,
    "nuget_changed": false,
    "output": "Module ComputerManagementDsc already present",
    "repository_changed": false
}

TASK [win_dsc] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:21
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_dsc.ps1
Pipelining is enabled.
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
failed: [testhost.testdomain.local] (item={u'days_interval': 1, u'task_name': u'TestTask', u'action_arguments': u'-c \'write-host "TEST" | out-file d:/test', u'start_time': u'06:00PM', u'action_workingpath': u'd:/', u'schedule_type': u'Daily', u'state': u'Present', u'start_when_available': False, u'action_executable': u'powershell.exe', u'logon_type': u'Password', u'execution_timelimit': u'72:00:00', u'executeas_credential_password': u'NOTREALLYTHISPASSWORD', u'executeas_credential_username': u'TESTDOMAIN\\mundym', u'task_path': u'TestTasks'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "ActionArguments": "-c 'write-host \"TEST\" | out-file d:/test",
            "ActionExecutable": "powershell.exe",
            "ActionWorkingPath": "d:/",
            "Compatibility": "Vista",
            "DaysInterval": 1,
            "DisallowDemandStart": false,
            "DisallowHardTerminate": false,
            "DisallowStartOnRemoteAppSession": false,
            "Enable": true,
            "Ensure": "Present",
            "ExecuteAsCredential_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ExecuteAsCredential_username": "TESTDOMAIN\\mundym",
            "Hidden": false,
            "LogonType": "Password",
            "MultipleInstances": "IgnoreNew",
            "Priority": 7,
            "RepetitionDuration": "Indefinitely",
            "RunLevel": "Limited",
            "ScheduleType": "Daily",
            "StartTime": "06:00PM",
            "TaskName": "TestTask",
            "TaskPath": "TestTasks",
            "module_version": "latest",
            "resource_name": "ScheduledTask"
        }
    },
    "item": {
        "action_arguments": "-c 'write-host \"TEST\" | out-file d:/test",
        "action_executable": "powershell.exe",
        "action_workingpath": "d:/",
        "days_interval": 1,
        "executeas_credential_password": "NOTREALLYTHISPASSWORD",
        "executeas_credential_username": "TESTDOMAIN\\mundym",
        "execution_timelimit": "72:00:00",
        "logon_type": "Password",
        "schedule_type": "Daily",
        "start_time": "06:00PM",
        "start_when_available": false,
        "state": "Present",
        "task_name": "TestTask",
        "task_path": "TestTasks"
    },
    "msg": "argument for StartTime is of type System.String and we were unable to convert to delegate: Exception calling \"ParseExact\" with \"4\" argument(s): \"String was not recognized as a valid DateTime.\""
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
testhost.testdomain.local : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

Same playbook for 2.7.11:
`

% ansible-playbook -i inventory test-ScheduledTask.yml -vvv
ansible-playbook 2.7.11
  config file = None
  configured module search path = [u'/home/mundym/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
No config file found; using defaults
/home/mundym/playbooks/inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/home/mundym/playbooks/inventory did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/mundym/playbooks/inventory inventory source with ini plugin

PLAYBOOK: test-ScheduledTask.yml **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in test-ScheduledTask.yml

PLAY [testhost.testdomain.local] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:1
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
ok: [testhost.testdomain.local]
META: ran handlers

TASK [set_fact] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:3
ok: [testhost.testdomain.local] => {
    "ansible_facts": {
        "scheduled_tasks": [
            {
                "action_arguments": "-c 'write-host \"TEST\" | out-file d:/test",
                "action_executable": "powershell.exe",
                "action_workingpath": "d:/",
                "days_interval": 1,
                "executeas_credential_password": "NOTREALLYTHISPASSWORD",
                "executeas_credential_username": "TESTDOMAIN\\mundym",
                "execution_timelimit": "72:00:00",
                "logon_type": "Password",
                "schedule_type": "Daily",
                "start_time": "06:00PM",
                "start_when_available": false,
                "state": "Present",
                "task_name": "TestTask",
                "task_path": "TestTasks"
            }
        ]
    },
    "changed": false
}

TASK [win_psmodule] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:19
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_psmodule.ps1
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
ok: [testhost.testdomain.local] => {
    "changed": false,
    "nuget_changed": false,
    "output": "Module ComputerManagementDsc already present",
    "repository_changed": false
}

TASK [win_dsc] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:21
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_dsc.ps1
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
changed: [testhost.testdomain.local] => (item={u'days_interval': 1, u'logon_type': u'Password', u'action_arguments': u'-c \'write-host "TEST" | out-file d:/test', u'start_time': u'06:00PM', u'action_workingpath': u'd:/', u'schedule_type': u'Daily', u'state': u'Present', u'start_when_available': False, u'action_executable': u'powershell.exe', u'task_name': u'TestTask', u'execution_timelimit': u'72:00:00', u'executeas_credential_password': u'NOTREALLYTHISPASSWORD', u'executeas_credential_username': u'TESTDOMAIN\\mundym', u'task_path': u'TestTasks'}) => {
    "changed": true,
    "item": {
        "action_arguments": "-c 'write-host \"TEST\" | out-file d:/test",
        "action_executable": "powershell.exe",
        "action_workingpath": "d:/",
        "days_interval": 1,
        "executeas_credential_password": "NOTREALLYTHISPASSWORD",
        "executeas_credential_username": "TESTDOMAIN\\mundym",
        "execution_timelimit": "72:00:00",
        "logon_type": "Password",
        "schedule_type": "Daily",
        "start_time": "06:00PM",
        "start_when_available": false,
        "state": "Present",
        "task_name": "TestTask",
        "task_path": "TestTasks"
    },
    "module_version": "6.1.0.0",
    "reboot_required": false
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
testhost.testdomain.local : ok=4    changed=1    unreachable=0    failed=0

`

**Comment by mmundy1** [comment]
No problem!
Here is a quick test playbook (hostname, username, password store path only things changed)
```yml

- hosts: testhost.testdomain.local
  tasks:
    - set_fact:
        scheduled_tasks:
          - task_name: "TestTask"
            task_path: "TestTasks"
            action_executable: "powershell.exe"
            action_arguments: "-c 'write-host \"TEST\" | out-file d:/test"
            action_workingpath: "d:/"
            schedule_type: Daily
            days_interval: 1
            start_time: "06:00PM"
            executeas_credential_username: "TESTDOMAIN\\mundym"
            executeas_credential_password:  "{{ lookup('passwordstore', 'mundym@testdomain.local')}}"
            start_when_available: False
            execution_timelimit: "72:00:00"
            logon_type: Password
            state: Present
    - win_psmodule:
        name: ComputerManagementDsc
    - win_dsc:
        resource_name: ScheduledTask
        TaskName                    : "{{ item.task_name }}"
        TaskPath                    : "{{ item.task_path }}"
        Description                 : "{{ item.description | default(omit) }}"
        ActionExecutable            : "{{ item.action_executable }}"
        ActionArguments             : "{{ item.action_arguments | default(omit) }}"
        ActionWorkingPath           : "{{ item.action_workingpath | default(omit) }}"
        ScheduleType                : "{{ item.schedule_type}}"
        DaysInterval                : "{{ item.days_interval | default(omit) }}"
        WeeksInterval               : "{{ item.weeks_interval | default(omit) }}"
        RepeatInterval              : "{{ item.repeat_interval | default(omit) }}"
        StartTime                   : "{{ item.start_time | default(omit) }}"
        DaysOfWeek                  : "{{ item.days_of_week | default(omit) }}"
        ExecuteAsCredential_username: "{{ item.executeas_credential_username | default(omit) }}"
        ExecuteAsCredential_password: "{{ item.executeas_credential_password | default(omit) }}"
        LogonType                   : "{{ item.logon_type | default(omit) }}"
        RandomDelay                 : "{{ item.random_delay | default(omit) }}"
        RepetitionDuration          : "{{ item.repetition_duration | default('Indefinitely') }}"
        DisallowDemandStart         : "{{ item.disallow_demand_start   | default(False) }}"
        DisallowHardTerminate       : "{{ item.disallow_hard_terminate | default(False) }}"
        Compatibility               : "{{ item.compatibility | default('Vista') }}"
        Hidden                      : "{{ item.hidden | default(False) }}"
        RunOnlyIfIdle               : "{{ item.run_only_if_idle   | default(omit) }}"
        IdleDuration                : "{{ item.idle_duration | default(omit) }}"
        IdleWaitTimeout             : "{{ item.idle_wait_timeout  | default(omit) }}"
        RestartOnIdle               : "{{ item.restart_on_idle    | default(omit) }}"
        DontStopOnIdleEnd           : "{{ item.dont_stop_on_idle_end | default(omit) }}"
        DisallowStartOnRemoteAppSession: "{{ item.disallow_start_on_remote_app_session | default(False) }}"
        ExecutionTimeLimit          : "{{ item.execution_time_limit  | default(omit) }}"
        RestartCount                : "{{ item.restart_count  | default(omit) }}"
        RestartInterval             : "{{ item.restart_interval  | default(omit) }}"
        multipleInstances           : "{{ item.multiple_instances | default('IgnoreNew') }}"
        Priority                    : "{{ item.priority| default('7') }}"
        RunLevel                    : "{{ item.runlevel | default('Limited') }}"
        Enable                      : true
        Ensure                      : Present
      loop: "{{scheduled_tasks}}"

```
and here is the -vvv output (same vars obfuscated) for 2.8.3:
```
% ansible-playbook -i inventory test-ScheduledTask.yml -vvv
ansible-playbook 2.8.3
  config file = None
  configured module search path = [u'/home/mundym/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
                "executeas_credential_username": "TESTDOMAIN\\mundym",
                "execution_timelimit": "72:00:00",
                "logon_type": "Password",
                "schedule_type": "Daily",
                "start_time": "06:00PM",
                "start_when_available": false,
                "state": "Present",
                "task_name": "TestTask",
                "task_path": "TestTasks"
            }
        ]
    },
    "changed": false
}

TASK [win_psmodule] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:19
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_psmodule.ps1
Pipelining is enabled.
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
ok: [testhost.testdomain.local] => {
    "changed": false,
    "nuget_changed": false,
    "output": "Module ComputerManagementDsc already present",
    "repository_changed": false
}

TASK [win_dsc] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:21
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_dsc.ps1
Pipelining is enabled.
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
failed: [testhost.testdomain.local] (item={u'days_interval': 1, u'task_name': u'TestTask', u'action_arguments': u'-c \'write-host "TEST" | out-file d:/test', u'start_time': u'06:00PM', u'action_workingpath': u'd:/', u'schedule_type': u'Daily', u'state': u'Present', u'start_when_available': False, u'action_executable': u'powershell.exe', u'logon_type': u'Password', u'execution_timelimit': u'72:00:00', u'executeas_credential_password': u'NOTREALLYTHISPASSWORD', u'executeas_credential_username': u'TESTDOMAIN\\mundym', u'task_path': u'TestTasks'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "ActionArguments": "-c 'write-host \"TEST\" | out-file d:/test",
            "ActionExecutable": "powershell.exe",
            "ActionWorkingPath": "d:/",
            "Compatibility": "Vista",
            "DaysInterval": 1,
            "DisallowDemandStart": false,
            "DisallowHardTerminate": false,
            "DisallowStartOnRemoteAppSession": false,
            "Enable": true,
            "Ensure": "Present",
            "ExecuteAsCredential_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ExecuteAsCredential_username": "TESTDOMAIN\\mundym",
            "Hidden": false,
            "LogonType": "Password",
            "MultipleInstances": "IgnoreNew",
            "Priority": 7,
            "RepetitionDuration": "Indefinitely",
            "RunLevel": "Limited",
            "ScheduleType": "Daily",
            "StartTime": "06:00PM",
            "TaskName": "TestTask",
            "TaskPath": "TestTasks",
            "module_version": "latest",
            "resource_name": "ScheduledTask"
        }
    },
    "item": {
        "action_arguments": "-c 'write-host \"TEST\" | out-file d:/test",
        "action_executable": "powershell.exe",
        "action_workingpath": "d:/",
        "days_interval": 1,
        "executeas_credential_password": "NOTREALLYTHISPASSWORD",
        "executeas_credential_username": "TESTDOMAIN\\mundym",
        "execution_timelimit": "72:00:00",
        "logon_type": "Password",
        "schedule_type": "Daily",
        "start_time": "06:00PM",
        "start_when_available": false,
        "state": "Present",
        "task_name": "TestTask",
        "task_path": "TestTasks"
    },
    "msg": "argument for StartTime is of type System.String and we were unable to convert to delegate: Exception calling \"ParseExact\" with \"4\" argument(s): \"String was not recognized as a valid DateTime.\""
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
testhost.testdomain.local : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

Same playbook for 2.7.11:
```
% ansible-playbook -i inventory test-ScheduledTask.yml -vvv
ansible-playbook 2.7.11
  config file = None
  configured module search path = [u'/home/mundym/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
No config file found; using defaults
/home/mundym/playbooks/inventory did not meet host_list requirements, check plugin documentation if this is unexpected
/home/mundym/playbooks/inventory did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/mundym/playbooks/inventory inventory source with ini plugin

PLAYBOOK: test-ScheduledTask.yml **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in test-ScheduledTask.yml

PLAY [testhost.testdomain.local] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:1
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
ok: [testhost.testdomain.local]
META: ran handlers

TASK [set_fact] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:3
ok: [testhost.testdomain.local] => {
    "ansible_facts": {
        "scheduled_tasks": [
            {
                "action_arguments": "-c 'write-host \"TEST\" | out-file d:/test",
                "action_executable": "powershell.exe",
                "action_workingpath": "d:/",
                "days_interval": 1,
                "executeas_credential_password": "NOTREALLYTHISPASSWORD",
                "executeas_credential_username": "TESTDOMAIN\\mundym",
                "execution_timelimit": "72:00:00",
                "logon_type": "Password",
                "schedule_type": "Daily",
                "start_time": "06:00PM",
                "start_when_available": false,
                "state": "Present",
                "task_name": "TestTask",
                "task_path": "TestTasks"
            }
        ]
    },
    "changed": false
}

TASK [win_psmodule] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:19
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_psmodule.ps1
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
ok: [testhost.testdomain.local] => {
    "changed": false,
    "nuget_changed": false,
    "output": "Module ComputerManagementDsc already present",
    "repository_changed": false
}

TASK [win_dsc] ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/mundym/playbooks/test-ScheduledTask.yml:21
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_dsc.ps1
<172.16.0.155> ESTABLISH WINRM CONNECTION FOR USER: AnsibleUser on PORT 5986 TO 172.16.0.155
EXEC (via pipeline wrapper)
changed: [testhost.testdomain.local] => (item={u'days_interval': 1, u'logon_type': u'Password', u'action_arguments': u'-c \'write-host "TEST" | out-file d:/test', u'start_time': u'06:00PM', u'action_workingpath': u'd:/', u'schedule_type': u'Daily', u'state': u'Present', u'start_when_available': False, u'action_executable': u'powershell.exe', u'task_name': u'TestTask', u'execution_timelimit': u'72:00:00', u'executeas_credential_password': u'NOTREALLYTHISPASSWORD', u'executeas_credential_username': u'TESTDOMAIN\\mundym', u'task_path': u'TestTasks'}) => {
    "changed": true,
    "item": {
        "action_arguments": "-c 'write-host \"TEST\" | out-file d:/test",
        "action_executable": "powershell.exe",
        "action_workingpath": "d:/",
        "days_interval": 1,
        "executeas_credential_password": "NOTREALLYTHISPASSWORD",
        "executeas_credential_username": "TESTDOMAIN\\mundym",
        "execution_timelimit": "72:00:00",
        "logon_type": "Password",
        "schedule_type": "Daily",
        "start_time": "06:00PM",
        "start_when_available": false,
        "state": "Present",
        "task_name": "TestTask",
        "task_path": "TestTasks"
    },
    "module_version": "6.1.0.0",
    "reboot_required": false
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
testhost.testdomain.local : ok=4    changed=1    unreachable=0    failed=0

```
