### ISSUE TITLE
Make module: incorrect params passed to make when using variables

### ISSUE THREAD

**Issue by komlevv** [ansible/ansible#59688]
##### SUMMARY

Unexpected result when using params with variables in make module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

make

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
no output
```

##### OS / ENVIRONMENT

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-957.21.3.el7.x86_64
Architecture: x86-64

##### STEPS TO REPRODUCE

```yaml
test_var: /tmp/testdir
```
```yaml
- name: Build
  make:
    target: install
    params:
      VAR_A: 1
      VAR_B: "{{ test_var }}"
      VAR_C: 1
```

##### EXPECTED RESULTS

`gmake install VAR_A=1 VAR_B=/tmp/testdir VAR_C=1`

##### ACTUAL RESULTS

`gmake install VAR_A=1 'VAR_B=/tmp/testdir' VAR_C=1`

```paste below

```
