### ISSUE TITLE
ec2_vpc_route_table not allowing using registred facts

### ISSUE THREAD

**Issue by mszumilak** [ansible/ansible#59694]
##### SUMMARY
I created a routing table with routing defined statically. After that I want to add VPC peering routing collected in separate task. I use routing table fact registered in previous task.

As result I'm getting:
```
TASK [aws/route-tables : Add peering routing] *******************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'route_table'\n\nThe error appears to be in '<path-to-file>': line 89, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n##############################################################\n- name: Add peering routing\n  ^ here\n"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_vpc_route_table

##### ANSIBLE VERSION
```
ansible 2.8.3
  config file = /path/to/config/file
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/venvs/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/user/venvs/ansible/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

```

##### CONFIGURATION
```paste below
RETRY_FILES_ENABLED(/home/user/path/to/config) = False
```

##### OS / ENVIRONMENT
AWS API

##### STEPS TO REPRODUCE
Playbook tasks:
```yaml
- debug: var=my_route_table_a

- name: Add peering routing
  ec2_vpc_route_table:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    lookup: id
    purge_subnets: no
    purge_routes: no
    purge_tags: no
    route_table_id: "{{ item.route_table.id }}"
    routes:
      - dest: "{{ vpc_peering.result.0.requester_vpc_info.cidr_block | default(omit) }}"
        gateway_id: "{{ vpc_peering.result.0.vpc_peering_connection_id | default(omit) }}"
  with_items:
    - my_route_table_a
    - my_route_table_b
    - my_route_table_c

```

Result:
```
TASK [aws/route-tables : debug] *************************************************
ok: [localhost] => {
    "my_route_table_a": {
        "changed": false,
        "failed": false,
        "route_table": {
            "associations": [
                {
                    "main": false,
                    "route_table_association_id": "rtbassoc-<redacted>",
                    "route_table_id": "rtb-<redacted>",
                    "subnet_id": "subnet-<redacted>"
                }
            ],
            "id": "rtb-<redacted>",
            "owner_id": "<redacted>",
            "propagating_vgws": [],
            "route_table_id": "<redacted>",
            "routes": [
                                {
                    "destination_cidr_block": "<redacted>",
                    "gateway_id": "local",
                    "origin": "CreateRouteTable",
                    "state": "active"
                },
                {
                    "destination_cidr_block": "0.0.0.0/0",
                    "nat_gateway_id": "nat-<redacted>",
                    "origin": "CreateRoute",
                    "state": "active"
                }
            ],
            "tags": {
                "Name": "MyRouteTableA"
            },
            "vpc_id": "vpc-<redacted>"
        }
    }
}

TASK [aws/route-tables : Add peering routing] ***********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'route_table'\n\nThe error appears to be in '<path-to-file>': line 89, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n##############################################################\n- name: Add peering routing\n  ^ here\n"}
```
##### EXPECTED RESULTS
The routing table should be modified.

##### ACTUAL RESULTS
Ansible is not able to use registered facts and is failing on undefined variable.

```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'route_table'\n\nThe error appears to be in '<path-to-file>': line 89, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n##############################################################\n- name: Add peering routing\n  ^ here\n"}
```
