### ISSUE TITLE
Making fetch work automagically when sudoing

### ISSUE THREAD

**Issue by davehatton** [ansible/ansible#597]
Not sure how to best fix this.

I use a standard user "ansible" with sudo nopasswd access to root - for all of my remote ansible systems.

I'm trying to collect /etc/shadow using fetch and with_items.
1. the fetch fails because sftp cannot sudo to root to access the file - the error comes back as md5 mismatch (technically correct) rather than "no access to file" - maybe a better error message could be produced?
2. maybe having trapped the error, fetch could ssh to the target, cp the file to tmp, change the ownership, collect it via the standard fetch method and then ssh and remove the file from tmp?
3. beyond this, having the failure seems to break the execution of the playbook
4. the PLAY RECAP stats don;t seem to added up now

example playbook:

```

---
- hosts: kvm
  user:  ansible
  sudo:  True

  tasks:
    - action: fetch src=$item dest=/data/transit/configs
      with_items:
          - /etc/passwd
          - /etc/shadow
          - /etc/bob
          - /etc/group
    - action: fetch src=$item dest=/data/transit/configs
      with_items:
          - /etc/sysctl.conf
          - /etc/centos-release
```

output:

```
ANSIBLE_SSH_ARGS="" ANSIBLE_REMOTE_USER=ansible ansible-playbook ~/playbooks/config_delta/config.delta.yml -c ssh -v 

PLAY [kvm] ********************* 

GATHERING FACTS ********************* 
ok: [zabbix.starground.co.uk]
ok: [office.starground.co.uk]
ok: [jabber.starground.co.uk]

TASK: [fetch src=$item dest=/data/transit/configs] ********************* 
ok: [zabbix.starground.co.uk] => {"changed": false, "file": "/etc/passwd", "md5sum": "4bdb5afeca6c234d970c8aee6707d30b"}
ok: [office.starground.co.uk] => {"changed": false, "file": "/etc/passwd", "md5sum": "522e1b4769cf88ae53cdcd2dce281475"}
ok: [jabber.starground.co.uk] => {"changed": false, "file": "/etc/passwd", "md5sum": "cbfc11f217062bb0eab9e4a7a0359631"}
failed: [zabbix.starground.co.uk] => {"failed": true, "file": "/etc/shadow", "md5sum": null, "msg": "md5 mismatch"}
failed: [office.starground.co.uk] => {"failed": true, "file": "/etc/shadow", "md5sum": null, "msg": "md5 mismatch"}
failed: [jabber.starground.co.uk] => {"failed": true, "file": "/etc/shadow", "md5sum": null, "msg": "md5 mismatch"}
ok: [office.starground.co.uk] => {"changed": false, "file": "/etc/bob", "msg": "missing remote file"}
ok: [zabbix.starground.co.uk] => {"changed": false, "file": "/etc/bob", "msg": "missing remote file"}
ok: [jabber.starground.co.uk] => {"changed": false, "file": "/etc/bob", "msg": "missing remote file"}
ok: [office.starground.co.uk] => {"changed": false, "file": "/etc/group", "md5sum": "efd2c18fa8c5ff3938b1c794158ccfe6"}
ok: [zabbix.starground.co.uk] => {"changed": false, "file": "/etc/group", "md5sum": "fbfd8e3b160604c41afa32ab662c96a7"}
ok: [jabber.starground.co.uk] => {"changed": false, "file": "/etc/group", "md5sum": "0f17fd9b46ad65a234017b5d8b646ccd"}

TASK: [fetch src=$item dest=/data/transit/configs] ********************* 
no hosts matched or remaining


PLAY RECAP ********************* 
jabber.starground.co.uk        : ok=1    changed=0    unreachable=0    failed=1    
office.starground.co.uk        : ok=1    changed=0    unreachable=0    failed=1    
zabbix.starground.co.uk        : ok=1    changed=0    unreachable=0    failed=1    
```
