### ISSUE TITLE
aws_s3 shows changed when not changed

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#59704]
##### SUMMARY

When using `aws_s3` to upload a file to S3, the task is always marked as "changed", even when running the playbook a second time, with the same file.

If the file that was previously in S3 matches the local file to upload, the task should not be marked as changed.

`overwrite: different` fixes this. The `mode` option should document that `put` is not idempotent by default.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

aws_s3

##### ANSIBLE VERSION

```
ansible 2.6.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.9 (unknown, Nov  2 2017, 19:21:21) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

`ansible-config dump --only-changed` returns nothing.

##### OS / ENVIRONMENT

Cloud9 inside AWS

##### STEPS TO REPRODUCE

Run a playbook with this task twice.
Where `s3_bucket` is any unique bucket name, and `file.zip` is any file.

```yaml
    - name: Upload Lambda zips to S3
      aws_s3:
        bucket: "{{ s3_bucket }}" # creates bucket if not exist
        object: "file.zip"
        src: "file.zip"
        mode: put 
        region: "ap-southeast-2"
```

##### EXPECTED RESULTS

The task should be marked as "changed" the first time, and "unchanged" the second.

I'm not sure whether you can query S3 to find out a hash of a file inside S3. If so, that could be a nice way to do it. Or failing that, perhaps Ansible should tag the files inside S3 when it uploads them? So future runs can read the hash from an ansible-specific tag.
(For large files this could also be used to avoid a slow upload of a duplicate file.)

##### ACTUAL RESULTS

The task and playbook run are marked as "changed"
