### ISSUE TITLE
uri converting body int to string

### ISSUE THREAD

**Issue by MichalTaratuta** [ansible/ansible#59732]
##### SUMMARY
URI module converting int to string when parameter is nested  in dictionary

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri
##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/lookups']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/modules']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml

vars:
    my_dict:
      key_1: 14

tasks:
   - name: Add Credential to Job Template
      uri:
        url: "https://tower.example.com/api/v2/job_templates/\
              {{ create_template.id }}/credentials/"
        method: POST
        status_code: 204
        headers:
          Authorization: "Bearer Token"
        body_format: json
        body:
          id: "{{ my_dict.key_1}}"
        validate_certs: False
```

##### EXPECTED RESULTS

```json
"body": {
  "id": 14
 }
```
##### ACTUAL RESULTS

```json
"body": {
  "id": "14"
 }
```
