### ISSUE TITLE
ec2_group, adding rules with non-existing group name fails silently.

### ISSUE THREAD

**Issue by codezerk** [ansible/ansible#5975]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5 (devel ae9843fccd) last updated 2014/02/03 16:35:52 (GMT +000)
##### Environment:

Linux debian-7 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux
##### Summary:

When adding a rule to a group with a group_name that doesn't exist, there will be no error notification, the task will complete successfully.

looking at the code in ec2_group.py, it continues if group_name is not found without warning.
##### Steps To Reproduce:

create a task like so:

```
- name: Manage EC2 security groups
  local_action:
    module: ec2_group
    name: "name"
    description: "description"
    vpc_id: "{{ec2_vpc_id}}"
    region: "{{ec2_region}}"
    ec2_access_key: "{{ec2_access_key}}"
    ec2_secret_key: "{{ec2_secret_key}}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        group_name: "control" # This doesn't exist
```
##### Expected Results:

Some kind of error notifying that the group doesn't exist  
##### Actual Results:

Changed successful. The groups rules won't have any rule set on it.
