### ISSUE TITLE
not able to access add_host module host variable into another host

### ISSUE THREAD

**Issue by thatsk** [ansible/ansible#59766]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
ansible
##### ANSIBLE VERSION
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```YAML
- name: Updating Rpm versions in {{ service_name }}
  hosts: local
  connection: local
  gather_facts: false
  tasks:
    - name: Getting host list from ipa
      shell: /etc/ansible/playbooks/hostfind.sh
    - name: Creating in memory inventory group for {{ nodetype }} in ansible playbook itself
      shell: cat /etc/ansible/hosts | grep {{ nodetype }} | grep {{ env }}
      register: host_list
    - add_host:
        name: "{{ item }}"
        group: "{{ nodetype }}"
      with_items: "{{ host_list.stdout_lines }}"

- name: Deployment Execution start on {{ nodetype }}
  hosts: "{{ nodetype }}"
  connection: ssh
  gather_facts: false
  any_errors_fatal: false
  user: test
  become: yes
  serial: 1
  tasks:
    - name: Deploying service on {{ inventory_hostname }}
      block:
        - name: Downgrading {{ service_name }} service on {{ inventory_hostname }}
          shell: rpm --queryformat "%{VERSION}-%{RELEASE}" -q {{ service_name }}
          register: downgraderpmversion
        - name: Restarting {{ service_name }} service on {{ inventory_hostname }}
          include_tasks: /etc/ansible/inventories/playbooks/common/service_restart.yaml
          with_items:
            - { servicename: '{{ service_name }}' }

- name: Updating Rpm versions for {{ service_name }}
  hosts: local
  connection: local
  gather_facts: false
  tasks:
  tasks:
    - debug:
        var: hostvars[groups['{{ nodetype }}'][0]]['downgraderpmversion']['stdout']
    - name: printing variable
      shell: echo hostvars[groups['{{ nodetype }}'][0]]['downgraderpmversion']['stdout']
 ```
