### ISSUE TITLE
Assert cannot accept 0 as value

### ISSUE THREAD

**Issue by Woitekku** [ansible/ansible#59760]
##### SUMMARY
Assert cannot accept 0 as value.

A task code looks like this:
```
 tasks:

  - name: Assert that imput parameters are provided
    assert:
      that:
        - vm_name|default('',true) != ''
        - size_gb|default('',true) != ''
        - datastore|default('',true) != ''
        - scsi_controller|default('',true) != ''
        - unit_number|default('',true) != ''
      fail_msg: "'vm_name', 'size_gb', 'datastore', 'scsi_controller' and 'unit_number' must be provided"
    tags:
      - always
```

When playbook is fired up with extra-vars where scsi_controller is set to 0 (integer not in "" or '') or the same is for unit_number, it throws an error:

* with scsi_controller: 0, unit_number: 0
```
fatal: [localhost]: FAILED! => {
    "assertion": "scsi_controller|default('',true) != ''",
    "changed": false,
    "evaluated_to": false,
    "msg": "'vm_name', 'size_gb', 'datastore', 'scsi_controller' and 'unit_number' must be provided"
}
```
* with scsi_controller: "0", unit_number: 0
```
fatal: [localhost]: FAILED! => {
    "assertion": "unit_number|default('',true) != ''",
    "changed": false,
    "evaluated_to": false,
    "msg": "'vm_name', 'size_gb', 'datastore', 'scsi_controller' and 'unit_number' must be provided"
}
```
With other numbers (also integers) it works like a charm. Only 0 provided as an integer makes this issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
assert module

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.8.1
  config file = /grdata/ansible/projects/vmware/ansible.cfg
  configured module search path = [u'/home/cichyw/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/grdata/ansible/projects/vmware/hosts']
DEFAULT_MANAGED_STR(/grdata/ansible/projects/vmware/ansible.cfg) = Ansible managed file. Be wary of possible overwrites.
DEFAULT_ROLES_PATH(/grdata/ansible/projects/vmware/ansible.cfg) = [u'/grdata/ansible/projects/vmware/roles']
DEPRECATION_WARNINGS(/grdata/ansible/projects/vmware/ansible.cfg) = False
HOST_KEY_CHECKING(/grdata/ansible/projects/vmware/ansible.cfg) = False
RETRY_FILES_ENABLED(/grdata/ansible/projects/vmware/ansible.cfg) = False
```

##### OS / ENVIRONMENT
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE
```
- name: Assert that imput parameters are provided
    assert:
      that:
        - vm_name|default('',true) != ''
        - size_gb|default('',true) != ''
        - datastore|default('',true) != ''
        - scsi_controller|default('',true) != ''
        - unit_number|default('',true) != ''
      fail_msg: "'vm_name', 'size_gb', 'datastore', 'scsi_controller' and 'unit_number' must be provided"
    tags:
      - always
```

##### EXPECTED RESULTS
0 should be accepted as integer, without need to provide "" around it.

##### ACTUAL RESULTS
Please see summary above.
