### ISSUE TITLE
Error on find module under local_location

### ISSUE THREAD

**Issue by gogeekness** [ansible/ansible#59771]
##### SUMMARY
I am trying to find a file `ms2i_x.x.x.x.tgz` on my local VM.

Later, I want to send the file to another VM on the same network segment (10.0.2.x).
Both VMs are on a single host using VBox internal network.

##### ISSUE TYPE
`fatal: [10.0.2.25]: FAILED! => {`
`    "msg": "privilege output closed while waiting for password prompt:\n"`
`}`

Error is from this task:

The source location is defined directly as the whole playbook is developed.
``` 
# These 2 tasks are related: to find the ms2i_install_tgz file
- name: Set source directory for ms2-isntall-package 
  set_fact:
    srcdir: "/home/user/Downloads"

- name: Find the local ms2 install archive to send to target server
  local_action:
    module: find
    path: "{{ srcdir }}"
    patterns: 'ms2i_*tgz'
    become: yes
  register: ms2archive
```

Inventory:

```[Debian_8]
10.0.2.25

[Debian_8:vars]
ansible_ssh_user=user
ansible_ssh_pass='xxxx.xxxx'
ansible_become_password='xxxx,xxxx'
```

Playbook
The target and permissions.  This play book calls the initial role to gather the needed data for next roles.
```
- hosts: Debian_8

  become: yes
  become_user: root
  become_method: su

  roles:
    - IA-Light-Online-InitalStart
    - IA-Light-Online-Install-Packages
```

I checked the file location and dropped any security for the file.  I run as 'user' here.
The file is own by user and the  

```
user@user-VirtualBox:~/Downloads$ pwd
/home/user/Downloads

drwxr-xr-x  6 user user 4,0K Mär 19  2018 .
drwxr-xr-x 30 user user 4,0K Jul 29 13:06 ..
-rwxr-xr-x  1 user user  44K Aug  5  2015 install-ialight-online.sh
-rwxr-xr-x  1 user root 166M Mär 19  2018 ms2i_1.6.1.8.tgz   <== key file on local VM
```

##### COMPONENT NAME
find module

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rdeseke/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rdeseke/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
`VirtualBox:~/O-S_Ansible/IA-Light-Online$ ansible-config dump --only-changed`
{ nothing }

##### OS / ENVIRONMENT
source:  Ubuntu 16.04
target: Debian 8

##### STEPS TO REPRODUCE

```yaml

# Basic Playbook. ===-
- hosts: Debian_8

  become: yes
  become_user: root
  become_method: su

tasks:

- name: Set source directory for ms2-isntall-package 
  set_fact:
    srcdir: "/home/user/Downloads"

- name: Find the local ms2 install archive to send to target server
  local_action:
    module: find
    path: "{{ srcdir }}"
    patterns: 'ms2i_*tgz'
    become: yes
  register: ms2archive

- name: un-compress ms2 files
  vars:  
    itisthere: False 
  unarchive:
    src: "{{ ms2archive.files[0].path | join }}"
    dest: "{{ destdir | join }}/ms2install/"
    remote_src: no
  when: itisthere == False
```

##### EXPECTED RESULTS
A ms2archive varible result for this task (in another role)
With a valid file name then unarchive can run.
Role: 

isithere is for testing (unarchive takes time)
```
- name: un-compress ms2 files
  vars:  
    itisthere: False 
  unarchive:
    src: "{{ ms2archive.files[0].path | join }}"
    dest: "{{ destdir | join }}/ms2install/"
    remote_src: no
  when: itisthere == False
```

##### ACTUAL RESULTS
```
TASK [IA-Light-Online-InitalStart : Find the local ms2 install archive to send to target server] ********************************
task path: /home/user/PycharmProjects/O-S_Ansible/IA-Light-Online/roles/IA-Light-Online-InitalStart/tasks/main.yml:83
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~user && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1564484773.89-128254709558314 `" && echo ansible-tmp-1564484773.89-128254709558314="` echo /home/user/.ansible/tmp/ansible-tmp-1564484773.89-128254709558314 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/files/find.py
<localhost> PUT /home/user/.ansible/tmp/ansible-local-10771UjgrE2/tmpl4D25j TO /home/user/.ansible/tmp/ansible-tmp-1564484773.89-128254709558314/AnsiballZ_find.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1564484773.89-128254709558314/ /home/user/.ansible/tmp/ansible-tmp-1564484773.89-128254709558314/AnsiballZ_find.py && sleep 0'
<localhost> EXEC /bin/sh -c 'su  root -c '"'"'/bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-aiowbxvyedkttpmehieqgxtbbdzpxljw ; /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1564484773.89-128254709558314/AnsiballZ_find.py'"'"'"'"'"'"'"'"''"'"' && sleep 0'
fatal: [10.0.2.25]: FAILED! => {
    "msg": "privilege output closed while waiting for password prompt:\n"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/files/find.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/find.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bcoca
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bcoca
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gogeekness** [comment]
Still have the same error with new latest Ansible:
```
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rdeseke/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

I believe you are misintepreting what `local` does, it runs on the machine 'ansible itself' is executed on, not on the VM host nor another VM, you might want to see `delegate_to` https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by gogeekness** [comment]
This is still an error. 

The find module does not have direct support for delagate_to: 
```
   "changed": false, 
    "invocation": {
        "module_args": {
            "delegate_to": "127.0.0.1", 
            "paths": "/home/user/Downloads", 
            "patterns": "ms2i_*tgz"
        }
    }, 
    "msg": "Unsupported parameters for (find) module: delegate_to Supported parameters include: age, age_stamp, contains, depth, excludes, file_type, follow, get_checksum, hidden, paths, patterns, recurse, size, use_regex"
```

So I need to run `find` with local_action
```
local_action:
  module: find
  paths: "{{ path }}"
  patterns: file*
register: output_var
```
Then I run tinto this error:
fatal: [10.0.2.25]: FAILED! ==> {
  "msg":  "privilege output closed while waiting for password prompt:\n"

I have scoured the internet trying to find a way to get around this error.  All of the refrences I have seen are about Ansible bug Issues.

**Comment by samdoran** [comment]
@gogeekness `delegate_to` is a [task parameter](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html#task), not a module parameter.

```yaml
- find:
    path: /tmp
    patterns: '*.txt'
    delegate_to: localhost  # <-- incorrect
```

```yaml
- find:
    path: /tmp
    patterns: '*.txt'
  delegate_to: localhost  # <-- correct
```

These are the corrections needed to the task from the example:

```yaml
- name: Find the local ms2 install archive to send to target server
  find:
    path: "{{ srcdir }}"
    patterns: 'ms2i_*tgz'
    become: yes
  register: ms2archive
  delegate_to: localhost
  become: no  # Need to disable privilege escalation to avoid the first error

- name: un-compress ms2 files
  unarchive:
    src: "{{ ms2archive['files'][0]['path'] }}"
    dest: "{{ destdir }}/ms2install/"
    remote_src: no
```

As @bcoca already mentioned, please reach out on IRC or the mailing list for help with playbooks.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
