### ISSUE TITLE
azure_rm_managed_disk_facts module doesn't filter by tags

### ISSUE THREAD

**Issue by bpados** [ansible/ansible#59770]
##### SUMMARY
azure_rm_managed_disk_facts module doesn't filter the result by defined tags. Error message: "Tags must be a dictionary of string:string values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
!component =lib/ansible/modules/cloud/azure/azure_rm_manageddisk_facts.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nladmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
NONE
```

##### OS / ENVIRONMENT

MS Azure Cloud

##### STEPS TO REPRODUCE

```yaml
- name: Get facts for disk
  azure_rm_managed_disk_facts:
    resource_group: "{{ azure_resource_group }}"
    tags:
      - 'Environment:NLCGenC5'
  register: Diskfacts

```

##### EXPECTED RESULTS

Complete list of managed disks.

##### ACTUAL RESULTS

```paste below
 [WARNING]: The value ['Environment:NLCGenC5'] (type list) in a string field was converted to "['Environment:NLCGenC5']" (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Tags must be a dictionary of string:string values."}


```
