### ISSUE TITLE
iam_password_policy ignores group/aws module defaults

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#59787]
##### SUMMARY
I am using the [module defaults] feature to set common defaults among aws modules. However, iam_password_policy ignored these defaults.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/config/module_defaults.yml

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = /home/mchappel/.ansible.cfg
  configured module search path = [u'/home/mchappel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/home/mchappel/.ansible.cfg) = [u'timer', u'profile_tasks']
HOST_KEY_CHECKING(/home/mchappel/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/mchappel/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL7

##### STEPS TO REPRODUCE
```
- hosts: all 
  gather_facts: no
  serial: 1
  tasks:
    - name: 'run roles under assumed context'
      module_defaults:
        group/aws:
          aws_access_key: '{{ current_account_sts_credentials.access_key }}'
          aws_secret_key: '{{ current_account_sts_credentials.secret_key }}'
          security_token: '{{ current_account_sts_credentials.session_token }}'
      block:
      -  iam_password_policy:
        state: present
        allow_pw_change: yes 
        min_pw_length: 14
        require_symbols: yes 
        require_numbers: yes 
        require_uppercase: yes 
        require_lowercase: yes 
        pw_reuse_prevent: 6
        pw_expire: 90

```

##### EXPECTED RESULTS
iam_password_policy uses provided defaults

##### ACTUAL RESULTS
iam_password_policy ignores provided defaults
