### ISSUE TITLE
redfish_facts: GetLogs can raise KeyError

### ISSUE THREAD

**Issue by billdodd** [ansible/ansible#59797]
##### SUMMARY

The GetLogs command can raise a KeyError if any of the properties it tries to read are not present. The properties being gathered are not required, so it should not be an error condition for them to be absent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_facts.py
redfish_utils.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = $HOME/.ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/Development/git/ansible/lib/ansible
  executable location = $HOME/Development/git/ansible/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
[no output]
```

##### OS / ENVIRONMENT

Applies to Redfish OOB controllers.

##### STEPS TO REPRODUCE

Run the GetLogs commands against a Redfish service that does not include one or more of these properties in the `LogServices` resources:

- `Description` 
- `Name`
- `Created`
- `Message`
- `Severity`

```yaml
---
- hosts: myhosts
  connection: local
  name: Get Manager Logs
  gather_facts: False

  vars:
    datatype: Logs

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get Manager Logs
    redfish_facts:
      category: Manager
      command: GetLogs
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
```

##### EXPECTED RESULTS

Playbook runs without error

##### ACTUAL RESULTS

```paste below
redfish_utils.py, line 316, in get_logs KeyError: 'Created'
```
