### ISSUE TITLE
Redfish: Power commands not mapping to allowable ResetType

### ISSUE THREAD

**Issue by billdodd** [ansible/ansible#59804]
##### SUMMARY

For the Power* commands (redfish_utils.py:manage_system_power(), there is some logic to check the allowable ResetType values and try to map the requested command to one that is supported by the system. For example, map `GracefulRestart` to `ForceRestart` if `ForceRestart` is allowed but `GracefulRestart` is not.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_command.py
redfish_utils.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = $HOME/.ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/Development/git/ansible/lib/ansible
  executable location = $HOME/Development/git/ansible/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```paste below
[no output]
```

##### OS / ENVIRONMENT

Applies to Redfish OOB controllers.

##### STEPS TO REPRODUCE

Issue `PowerGracefulRestart` command for a system where `ForceRestart` is allowed but `GracefulRestart` is not.

```yaml
---
- hosts: myhosts
  connection: local
  name: Manage System Power - Greaceful restart
  gather_facts: False

  tasks:

  - name: Restart system power gracefully
    redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
```

##### EXPECTED RESULTS

Command will successfully issue a computer system reset with `ResetType` of `ForceRestart`.

##### ACTUAL RESULTS

Command failed with:

```paste below
Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values
```
