### ISSUE TITLE
New Azure Datalake directories management Module

### ISSUE THREAD

**Issue by imjoseangel** [ansible/ansible#59821]
##### SUMMARY

Create Azure RM Datalake Gen1 Folder ACLs
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_datalakeacl.py

##### ADDITIONAL INFORMATION

This module will configure the Datalake Gen1 ACL Permissions. I already have this implemented and I would like to know if it is interesting to share. Another module for directories management is going to come and I need feedback to keep in a single module or splitted.

```yaml
---
- name: Configure acl for Datalake Gen1"
  azure_rm_datalakeacl:
    dir_name: "/raw"
    store_name: mydevdatalake
    object_id: myusername
    permissions: "r-w"
    type: "default:user"
```
