### ISSUE TITLE
win_domain_group_membership

### ISSUE THREAD

**Issue by thylocene** [ansible/ansible#59829]
##### SUMMARY
win_domain_group_membership does not support cross domain membership.
This module needs extra parameters so that both group and members have server specified.  At the moment the users and groups have to be in the same domain for the module to work!  We have a multi-domain forest and need the ability to add users to groups from the other domains

$user = Get-ADUser fredb -Server fabricam.com
$group = Get-ADGroup "Box Permanent user group" -Server contoso.com
Add-ADGroupMember -Identity $Group -Members $User -Server contoso.com

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_group_membership

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Target Active Directory. Host Windows Server 2012 R2

##### STEPS TO REPRODUCE

```yaml
---
-
  hosts: all
  ignore_errors: true
  vars:
    basic_user_group:
      - "group1"
      - "group2"
    userId:
      - "fredb"

  tasks:
    - name: Set fact basic_user_group
      set_fact:
        box_groups: "{{ basic_user_group }}"
      when: user_profile == "basic"

    - name: Add Username to GroupName
      win_domain_group_membership:
        name: "{{ basic_user_group }}"
        domain_server: "contoso.com"
        members:
          - "{{ userId }}"
        state: present
```

##### ACTUAL RESULTS

The full traceback is:
Cannot find an object with identity: 'System.Object[]' under: 'DC=xxx,DC=xxxx,DC=net'.
At line:51 char:19
+ $members_before = Get-AdGroupMember -Identity $name @extra_args
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (System.Object[]:ADGroup) [Get-ADGroupMember], ADIdentityNotFoundException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,Microsoft.ActiveDirectory.Management.Commands.GetADGroupMember

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 51

Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException: Cannot find an object with identity: 'System.Object[]' under: 'DC=xxx,DC=xxxx,DC=net'.
   at Microsoft.ActiveDirectory.Management.Commands.ADFactoryUtil.GetObjectFromIdentitySearcher(ADObjectSearcher searcher, ADEntity identityObj, String searchRoot, AttributeSetRequest attrs, CmdletSessionInfo cmdletSessionInfo, String[]& warningMessages)
   at Microsoft.ActiveDirectory.Management.Commands.ADFactory`1.GetDirectoryObjectFromIdentity(T identityObj, String searchRoot, Boolean showDeleted)
   at Microsoft.ActiveDirectory.Management.Commands.GetADGroupMember.GetADGroupMemberProcessCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()
fatal: [xxxxxxxxxxxxxxx.xxx.xxxxxxxxxxx.xxx]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Cannot find an object with identity: 'System.Object[]' under: 'DC=xxx,DC=xxxx,DC=net'."
}

```paste below

```
