### ISSUE TITLE
AttributeError: 'Block' object has no attribute 'notified_hosts'

### ISSUE THREAD

**Issue by snuser** [ansible/ansible#59855]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
```

##### CONFIGURATION

```paste below
 DEFAULT_FORKS(/root/k_img_deploy/ansible.cfg) = 4
DEFAULT_HOST_LIST(/root/k_img_deploy/ansible.cfg) = [u'/root/k_img_deploy/hosts']
DEFAULT_LOG_PATH(/root/k_img_deploy/ansible.cfg) = /root/k_img_deploy/logs/ansible.log
DEFAULT_ROLES_PATH(/root/k_img_deploy/ansible.cfg) = [u'/root/k_img_deploy/roles']
DEFAULT_TIMEOUT(/root/k_img_deploy/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

CentOS release 6.10 (Final)

##### STEPS TO REPRODUCE

```yaml
 tasks:
  - set_fact:
      kproxy_service_vars:
        service_name: kproxy
        conf_path: "{{nginx_kwork_conf_path}}"
      kwork_service_vars:
        service_name: kwork
        conf_path: "{{nginx_kproxy_conf_path}}"

  - name: xxx
    copy: src="{{local_template_path}}" dest="{{node_template_path}}" force=yes

  - name: xxx
    copy: src="{{nginx_kproxy_template_conf_path}}" dest="{{nginx_kproxy_conf_path}}" force=yes
    notify:
      -  reload nginx_kproxy

  - name: xxx
    copy: src="{{nginx_kwork_template_conf_path}}" dest="{{nginx_kwork_conf_path}}" force=yes
    notify:
      -  reload nginx_kwork

  handlers:
  - name: reload nginx_kproxy
    import_role:
      name: nginx_service
    vars:
      service_vars: kproxy_service_vars

  - name: reload nginx_kwork
    import_role:
      name: nginx_service
    vars:
      service_vars: kwork_service_vars
```

##### ACTUAL RESULTS

```paste below

```
