### ISSUE TITLE
Allow inline templates to be used as play parameters

### ISSUE THREAD

**Issue by sergiopacezup** [ansible/ansible#59944]
##### SUMMARY
I have some complex and dynamic configuration parameters on my playbooks. My current approach is to set a fact with the parameter content and feed it to "from_yaml". Something like this, only bigger:
```
- name: set fact text
  set_fact:
    fact_text: |
      {% for item in items_output.results %}
      - index: {{ loop.index }}
        name: {{ item.name }}
      {% if 'scope' in item %}
        scope: {{ item.scope }}
        type: {{ item.type }}
      {%   endif %}
      {% endfor %}

- name: set actual fact
  set_fact:
    actual_fact: "{{ fact_text | from_yaml }}"

- name: use fact
  any:
    config: "{{ actual_fact }}"
```

##### ISSUE TYPE
The double set_fact feels "hacky" at best. Been able to use inline template into the module would be way easier:
```
- name: simply use it
  any:
    config: |
      {% for item in items_output.results %}
      - index: {{ loop.index }}
        name: {{ item.name }}
      {% if 'scope' in item %}
        scope: {{ item.scope }}
        type: {{ item.type }}
      {%   endif %}
      {% endfor %}
```
Maybe there is a "best practice" to deal with this situations but a could find any.
Such feature would greatly simplify my, and probably others, playbooks.

##### COMPONENT NAME
Inline templates maybe...
