### ISSUE TITLE
gitlab_runner module: Misleading deprecation warnings in Ansible 2.8

### ISSUE THREAD

**Issue by colorchestra** [ansible/ansible#59976]
##### SUMMARY
The gitlab_runner module throws deprecation warnings for an option I don't use and another option that is not actually deprecated

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

'gitlab_runner' module

##### ANSIBLE VERSION

```
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/m/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/m/.local/lib/python3.6/site-packages/ansible
  executable location = /home/m/.local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### CONFIGURATION

```paste below
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target: Debian Buster, freshly installed. Kernel 4.19.0-5-amd64, Python versions 2.7.16 and 3.7.3

##### STEPS TO REPRODUCE

Create a task using the gitlab_runner module. Here is the task I use:

```
m@void:~/work/ansible-default-deployment$ cat roles/gitlab-runner/tasks/main.yml 
---
- name: Install python-gitlab via pip
  pip:
      name: python-gitlab
      state: present

- name: Register runner
  gitlab_runner:
      url: <redacted>
      api_token: "{{ gitlab_api_token }}"
      registration_token: "{{ gitlab_runner_registration_token }}"
      description: "Auto-created runner for project {{ project_name }}"
      state: present
      active: False
      tag_list: ['docker', '{{project_name}}']
      run_untagged: False
      locked: False
```

##### EXPECTED RESULTS

- I expect no deprecation warning for the `url` parameter because it is described as a required parameter with no possible alternative, and it is not marked as deprecated even in the 'devel' docs
- I expect no deprecation warning for the `login_token`  parameter because I don't use it

##### ACTUAL RESULTS

This is the output of running the aforenmentioned task:

```
TASK [gitlab-runner : Register runner] *************************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: Param 'url' is deprecated. See the module docs for more information. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Aliases 'login_token' are deprecated. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [redacted]
```
