### ISSUE TITLE
redfish_config fails with Huawei servers (412 Precondition Failed)

### ISSUE THREAD

**Issue by champtar** [ansible/ansible#60031]
##### SUMMARY
Trying to configure a Huawei 2288H V5 via iBMC/redfish, redfish_config module fails because `If-Match` header is missing
Huawei require to first issue a `GET` and put `If-Match: <etag value>` header in `POST/PUT/PATCH` requests

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
redfish_config

##### ANSIBLE VERSION
```paste below
ansible 2.8.1
  config file = /home/echampetier/git/ops/provisioning/ansible.cfg
  configured module search path = ['/home/echampetier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/echampetier/git/ops/provisioning/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/echampetier/git/ops/provisioning/ansible.cfg) = ['profile_tasks']
DEFAULT_REMOTE_USER(/home/echampetier/git/ops/provisioning/ansible.cfg) = root
```

##### OS / ENVIRONMENT
Fedora 30
Huawei 2288H V5 with iBMC 3.31 (U4282)

##### STEPS TO REPRODUCE
```
- name: Set Bios config
  redfish_config:
    category: Systems
    command: SetBiosAttributes
    bios_attribute_name: "PXE1Setting"
    bios_attribute_value: "Disabled"
    baseuri: "{{ ibmc_ip }}"
    username: "{{ ibmc_user }}"
    password: "{{ ibmc_pass }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS
It works ;)

##### ACTUAL RESULTS
```
HTTP Error 412 on PATCH request to 'https://192.168.1.2/redfish/v1/Systems/1/Bios/Settings', extended message: 'Precondition Failed'
```

##### Additional informations

Huawei redfish API requires `If-Match` header
https://support.huawei.com/enterprise/en/doc/EDOC1000126992/edfdf3b3/modifying-system-resource-properties
```
Operation type: PATCH
URL: https://device_ip/redfish/v1/Systems/system_id
Request header:
X-Auth-Token: auth_value
Content-Type: header_type
If-Match: ifmatch_value
Request message body:

ifmatch_value | Parameters matching the request message. | Perform the GET operation on the related resource and obtain the value from the ETag parameter in the header of the response message.
```
Using `Authorization: Basic ` instead of `X-Auth-Token` is not an issue, but `If-Match` is required
Here some curl commands to show the behavior
https://gist.github.com/champtar/76611d614949ba90a3bf6411d3cb7f75
