### ISSUE TITLE
Quoted values are falsly identified as boolean

### ISSUE THREAD

**Issue by mowgli** [ansible/ansible#60044]
##### SUMMARY
Quoted 'True' or 'False' are falsly identified as booleans.

With the new policy of nagging about that, that becomes to verbose.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ini_file

##### ANSIBLE VERSION
```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 11 2019, 10:43:21) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = su
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed file
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
linux

##### STEPS TO REPRODUCE
```yaml
- name: Setting ansible variables
  ini_file:
    dest: /etc/ansible/ansible.cfg
    section: "{{ item.section|default('defaults') }}"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: gathering, value: smart}
    - {section: privilege_escalation, name: become_method, value: su}
    - {section: ssh_connection, name: pipelining, value: 'True'}
    - {name: retry_files_enabled, value: 'False'}
    - {name: ansible_managed, value: 'Ansible managed file'}
```

##### EXPECTED RESULTS
Nothing

##### ACTUAL RESULTS
```paste below
ansible-ini_file: [WARNING] The value True (type bool) in a string field was converted to u'True' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
ansible-ini_file: [WARNING] The value False (type bool) in a string field was converted to u'False' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/files/ini_file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/ini_file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @noseka1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @noseka1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tazerdev** [comment]
I'm seeing this same behavior in RHEL's ansible 2.8.5. Here's my specific test case:

```
# Create the test file
cat > /tmp/test.ini << EOF                                                      
[section1]
testopt1 = False
testopt2 = False
testopt3 = False
testopt4 = False
testopt5 = False
testopt6 = False
EOF
```
Relevant Ansible task:

```
- name: 'Setting up /tmp/test.ini'
  ini_file:
    path: /tmp/test.ini
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    section: "{{ item.section }}"
  loop:
     - { section: section1, option: testopt1, value: True }
     - { section: section1, option: testopt2, value: true }
     - { section: section1, option: testopt3, value: 'true' }
     - { section: section1, option: testopt4, value: 'True' }
     - { section: section1, option: testopt5, value: "true" }
     - { section: section1, option: testopt6, value: "True" }
```

Of those 6 variations the only ones that don't generate the warning are the lowercase and quoted values:

```
     - { section: section1, option: testopt5, value: 'true' }
     - { section: section1, option: testopt5, value: "true" }
```

I get the same warning if I use single quotes around `'{{ item.value }}'` and if I leave quotes off altogether I get an error about missing quotes.

While it doesn't affect my specific use case, I would expect this might cause a problem where case sensitivity is expected in a given ini file.

**Comment by rshbb** [comment]
Can anyone explain me what we have to do here? In a nutshell?

**Comment by tazerdev** [comment]
> Can anyone explain me what we have to do here? In a nutshell?

The 'in a nutshell' request is, make the warning behavior consistent between setting an option individually vs setting the option via a loop.

Specifically I think the issue lies in the looping code somewhere because I do not receiving a warning when I do this:

```
- name: 'Setting up testopt1 test.ini'
  ini_file:
    path: test.ini
    option: testopt1
    value: 'True'
    section: section1
```

But I do receiving a warning when I do this:

```
- name: 'Setting up test.ini'
  ini_file:
    path: test.ini
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    section: '{{ item.section }}'
  loop:
    - { section: section1, option: testopt1, value: 'True' }
```

From an end user perspective, these tasks should be identical and generate the same output.
