### ISSUE TITLE
"Database name has not been passed, used default database to connect to."

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#60043]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_slot, postgresql_user

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
```

##### OS / ENVIRONMENT

archlinux latest

##### STEPS TO REPRODUCE

```yaml
- postgresql_user:
    name: user1
    password: password
  become: true
  become_user: postgres

- postgresql_slot:
    name: slot1
  become: true
  become_user: postgres
```

##### EXPECTED RESULTS

Consistent warnings. Either both postgresql_user and postgresql_slot should give a warning or neither should.

##### ACTUAL RESULTS

postgresql_slot gives warning "[WARNING]: Database name has not been passed, used default database to connect to." but postgresql_user doesn't, even though both of them have not specified a database.
