### ISSUE TITLE
cron overrides

### ISSUE THREAD

**Issue by tuwid** [ansible/ansible#60054]
##### SUMMARY

When I'm running something like this: 
```
- name: Setting cron
  cron:
    name: "Sync every minute"
    user: "root"
    job: "sleep 5; unison -batch /var/www ssh://{{other_node}}//var/www -owner -group"

- name: Setting cron for mid minute
  cron:
    name: "Sync every minute"
    user: "root"
    job: "sleep 35; unison -batch /var/www ssh://{{other_node}}//var/www -owner -group"

```
I'd get just one cron. 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.3
  config file = None
  configured module search path = [u'/Users/tarak/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun 19 2019, 07:40:37) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]

```

##### STEPS TO REPRODUCE

```yaml
- name: Setting cron
  cron:
    name: "Sync every minute"
    user: "root"
    job: "sleep 5; unison -batch /var/www ssh://{{other_node}}//var/www -owner -group"

- name: Setting cron for mid minute
  cron:
    name: "Sync every minute"
    user: "root"
    job: "sleep 35; unison -batch /var/www ssh://{{other_node}}//var/www -owner -group"


```
