### ISSUE TITLE
file - implement fallocate as an option

### ISSUE THREAD

**Issue by SpokeyWheeler** [ansible/ansible#60063]
##### SUMMARY
Implement fallocate as an option for the file module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
file

##### ADDITIONAL INFORMATION

We use Informix, which writes 0 repeatedly into a file to create a dbspace chunk of the requisite size. fallocate bypasses this by instantly creating a file of the requisite size. This hugely speeds up deployments

```yaml
---
- name: "Create a chunk for {{ dbspace }}"
  file:
    path: "{{ informix_server_dbspace_dir }}/{{ dbspace }}_01"
    state: fallocate
    size: 8GiB
    owner: "informix"
    group: "informix"
    mode: 0660

```
