### ISSUE TITLE
Can't escape quotes in shell/command calls

### ISSUE THREAD

**Issue by ex-nerd** [ansible/ansible#6006]
##### Issue Type:

Bug Report
##### Ansible Version:

1.4.5
##### Environment:

OSX but probably N/A
##### Summary:

Can't escape quotes inside of commands
##### Steps To Reproduce:

No variation of the following actions will "compile":

``` yaml

---
- name: test
  hosts: localhost
  gather_facts: False
  tasks:
    - local_action: command echo '{"a": 1, "b": 2}'
    - local_action: command "echo '{\"a\": 1, \"b\": 2}'"
    - local_action: "command echo '{\"a\": 1, \"b\": 2}'"
```

It seems that Ansible is just splitting on the `"` character rather than actually examining the string for proper escape sequences.  
##### Expected Results:

I would expect to have three lines of output which look a bit like:

```
'{"a": 1, "b": 2}
'{"a": 1, "b": 2}
'{"a": 1, "b": 2}
```
##### Actual Results:

Some variation on:

```
ERROR: Syntax Error while loading YAML script, foo.yml
Note: The error may actually appear before this position: line 6, column 39

  tasks:
    - local_action: command echo '{"a": 1, "b": 2}'
                                      ^
This one looks easy to fix.  There seems to be an extra unquoted colon in the line 
and this is confusing the parser. It was only expecting to find one free 
colon. The solution is just add some quotes around the colon, or quote the 
entire line after the first colon.

For instance, if the original line was:

    copy: src=file.txt dest=/path/filename:with_colon.txt

It can be written as:

    copy: src=file.txt dest='/path/filename:with_colon.txt'

Or:

    copy: 'src=file.txt dest=/path/filename:with_colon.txt'

```

**Comment by darkone23** [comment]
This is actually the behavior of the YAML parser.

If you try to parse those strings using PyYAML you get errors.

**Comment by ex-nerd** [comment]
Interesting.  Guess I should file a bug with them.

**Comment by ex-nerd** [comment]
Digging into the PyYAML docs for info, the following seems to work -- using single quotes `'` and escaping with two single quotes `''`:

``` yaml
---
- name: test
  hosts: localhost
  gather_facts: False
  tasks:
    - local_action: 'command echo ''{"a": 1, "b": 2}'''
```
