### ISSUE TITLE
win_dns_record incorrectly creates PTR records

### ISSUE THREAD

**Issue by bamason14** [ansible/ansible#60068]
##### SUMMARY

When specifying a PTR record, the module incorrectly creates the entry.

  - name: Create PTR Record
    win_dns_record:
      computer_name: "msdnsserver.example.com"
      name: "10.202.64.62"
      state: present
      type: "PTR"
      value: "awx_test.example.com"
      zone: "10.in-addr.arpa"    

Entry created:

10.62.64.202.10     Pointer (PTR)     awx_test.example.com

To correctly create the record I used the following format:

  - name: Create PTR Record
    win_dns_record:
      computer_name: "msdnsserver.example.com"
      name: "62.64.202"
      state: present
      type: "PTR"
      value: "awx_test.example.com"
      zone: "10.in-addr.arpa"    

which created record:

10.202.64.62     Pointer (PTR)     awx_test.example.com

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_dns_record
##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
# ansible-config dump --only-changed
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.6 (Maipo)

##### STEPS TO REPRODUCE

```yaml
  - name: Create PTR Record
    win_dns_record:
      computer_name: "msdnsserver.example.com"
      name: "10.202.64.62"
      state: present
      type: "PTR"
      value: "awx_test.example.com"
      zone: "10.in-addr.arpa"    
```

##### EXPECTED RESULTS

10.202.64.62     Pointer (PTR)     awx_test.example.com

##### ACTUAL RESULTS

```paste below
10.62.64.202.10     Pointer (PTR)     awx_test.example.com
```
