### ISSUE TITLE
ios_vlan: purge option tries to delete reserved VLANs

### ISSUE THREAD

**Issue by richardschuetz** [ansible/ansible#60060]
##### SUMMARY

If _ios_vlan_ is used with the `purge` option enabled, reserved VLANs must be explicitly included in the `aggregate` dictionary, otherwise the module tries to delete them with every run.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_vlan
##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Cisco IOS 15.2(4)E8

##### STEPS TO REPRODUCE

```yaml
- name: Configure VLANs
  ios_vlan:
    aggregate: "{{ vlans }}"
    purge: yes
  when: vlans is defined

vlans:
  # reserved VLANs not handled correctly by module if not explicitly included here
  - {vlan_id: 1002, name: fddi-default}
  - {vlan_id: 1003, name: trcrf-default}
  - {vlan_id: 1004, name: fddinet-default}
  - {vlan_id: 1005, name: trbrf-default}
```

##### EXPECTED RESULTS

Cisco IOS reserved VLANs should be ignored by the module because they cannot be renamed or deleted.

##### ACTUAL RESULTS

Module tries to delete reserved VLANs with every run if they are not explicitly included in the `aggregate` dictionary.

```paste below
changed: [c3560cx-a148] => {
    "changed": true,
    "commands": [
        "no vlan 1002",
        "no vlan 1003",
        "no vlan 1004",
        "no vlan 1005"
    ],
```
