### ISSUE TITLE
route53: Skip zone listing when hosted_zone_id is set

### ISSUE THREAD

**Issue by bkmeneguello** [ansible/ansible#60102]
##### SUMMARY
Improve route53 module performance when ZoneID is know

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

route53

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /home/bruno/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### STEPS TO REPRODUCE

* Define a long list of DNS records
* Use a `loop` with `route53` module to update them

```yaml
route53:
  state: present
  zone: example.com  # should not be required when hosted_zone_id is present
  private_zone: true  # should not be needed when hosted_zone_id is present
  hosted_zone_id: "XXXXXXXXXXX"
  record: "{{ item.name }}"
  ttl: "{{ item.ttl }}"
  type: "{{ item.type }}"
  value: "{{ item.value }}"
  overwrite: true
with_items: "{{ dns_records }}"
```

##### EXPECTED RESULTS

Since hosted_zone_id is provided, this should be a simple request to Route53 API

##### ACTUAL RESULTS

Currently the code in [route53.py](https://github.com/ansible/ansible/blob/41235ac05a7a52f102422da17d40b5952e722095/lib/ansible/modules/cloud/amazon/route53.py#L567) do a zone lookup witch may lead to a full listing with (possibly) pagination by boto.
This lookup returns a `zone` reference but only it's `id` attribute is read.
So, since the hosted_zone_id is the same id obtained above, and is developer responsibility to ensure it's correct, this lookup should be ignored and the provided hosted_zone_id used in place.
