### ISSUE TITLE
terraform: Plan file doesn't seen in next steps

### ISSUE THREAD

**Issue by Asgoret** [ansible/ansible#60126]
Continue of https://github.com/ansible/ansible/issues/39611 
Fix doesn't work (https://github.com/ansible/ansible/commit/9a607283aafce8f1eb424df6b4c567095844bfd7)

At this moment i specify plan file, but next step doesn't see it

##### COMPONENT NAME
terraform

Ansible version: 
```
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/aermakov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

Can you help to handle it? @mohitkumarsharmaflux7 @ryansb 

Code:
```
 - name: Check plan and created elements
   terraform: 
     project_path: '{{ playbook_dir }}/roles/terraform/templates/terraform'
     plan_file: '{{ playbook_dir }}/roles/terraform/templates/terraform/okd.tfplan'
     state: planned
     force_init: true

 - name: Create Vms and prepare inventoryfile
   terraform: 
     project_path: '{{ playbook_dir }}/roles/terraform/templates/terraform'
     state: present
```
