### ISSUE TITLE
Copy fails when there is a space in the source

### ISSUE THREAD

**Issue by brianmhunt** [ansible/ansible#6013]
When I try to use the `copy` module it fails when the source has a space in it. Simple example:
### playbook.yaml

```
- hosts: hosts
  vars_files:
   - vars.yaml
  tasks:
    - name: Copy a thing. With spaces.
      copy: >
        src="{{ origin }}"
        dest=dest
```
### vars.yaml:

```
origin: ~/My Directory/Source
```

The error is:

> Source /home/user/.ansible/tmp/ansible-1392391050.29-133280657689315/source failed to transfer

I have tried wrapping the `src` and `origin` in a variety of quotes and escapes but nothing availed me of the issue.

I worked around this by creating symlinks to the origin that do not have spaces in them.

Just a heads up.

Cheers.

**Comment by ansibot** [comment]
Thanks for filing a ticket! I am the friendly GitHub Ansibot. I see you did not fill out your issue description based on our new issue template. Please copy the contents of this [template](https://raw2.github.com/ansible/ansible/devel/examples/issues/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket. 

Our system will automatically close tickets that do not have an issue template filled out within 7 days. Please note that due to large interest in Ansible, humans may not comment on your ticket if you ask them questions. Don't worry, you're still in the queue and the robots are looking after you.

**Comment by jimi-c** [comment]
You just need to escape the space:

<pre>
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
  - origin: "/tmp/test\ file"
  tasks:
  - copy: >
      src='{{origin}}'
      dest=/tmp/foo
</pre>

And the output:

<pre>
# ansible-playbook ~/testing/6013.yml 
PLAY [localhost] ************************************************************** 
TASK: [copy src='/tmp/test file' dest=/tmp/foo] ******************************* 
changed: [127.0.0.1]
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0   
</pre>

If you have any further questions about this, let us know. Thanks!

**Comment by brianmhunt** [comment]
Thanks @jimi-c . Sorry I should have mentioned but adding an escape as you suggest breaks `lookup('file', origin)`.

**Comment by jimi-c** [comment]
I cannot reproduce that. Modifying my test playbook:

<pre>
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
  - origin: "/tmp/test\ file"
  - foo: "{{ lookup('file', origin) }}"
  tasks:
  - debug: var="{{foo}}"
  - copy: >
      src='{{origin}}'
      dest=/tmp/foo
</pre>

Resulting output:

<pre>
# ansible-playbook ~/testing/6013.yml 
PLAY [localhost] ************************************************************** 
TASK: [debug var="this is the test"] ****************************************** 
ok: [127.0.0.1] => {
    "this is the test": "{{ this is the test }}"
}
TASK: [copy src='/tmp/test file' dest=/tmp/foo] ******************************* 
ok: [127.0.0.1]
PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
</pre>

If you are using 1.4.5 or before, then this appears to be fixed in the current devel branch?

**Comment by brianmhunt** [comment]
Thanks so much for looking into it.

The issue occurs for me on Ansible 1.4.4 with the following:

``` yaml
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
#  - origin: "/tmp/test\ file"
# Take away the quotes:
  - origin: /tmp/test\ file
  - foo: "{{ lookup('file', origin) }}"
  tasks:
  - debug: var="{{foo}}"
  - copy: >
      src='{{origin}}'
      dest=/tmp/foo
```

The solution strikes me as odd because `"x\ y"` in YAML becomes `"x y"` (i.e. the `\` is superfluous), as [seen here](http://yaml-online-parser.appspot.com/?yaml=origin_1%3A+%2Ftmp%2Ftest%5C+file%0Aorigin_2%3A+%22%2Ftmp%2Ftest%5C+file%22+%0Aorigin_3%3A+%22%2Ftmp%2Ftest+file%22&type=json).

That said, – it works. :tada:  If the issue exhibits again then I will post a good example.

Many thanks & cheers.
