### ISSUE TITLE
Add support for OS/Platform on collection galaxy.yml and UI

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#60155]
##### SUMMARY

In Ansible Galaxy, roles can indicate platform/OS support with a `galaxy_info.platforms` in the `meta/main.yml` array of platforms (e.g. I can say my role supports "Fedora 29, CentOS 7, and Debian 10", among any other combinations).

In Collections, the `galaxy.yml` file does not offer any way to indicate which platforms are supported by a given Collection.

Plugins and modules might be platform-independent (sometimes), but it's extremely helpful to be able to filter roles (and sometimes other content) because if someone builds a role for RHEL only, or for Ubuntu only, there are many, many cases where it's a waste of time to even think about using it on a different platform due to differences between package names, etc.

Without a UI to filter by OS/platform in Galaxy, I don't know if I'd even consider searching for a collection to use, because I don't want to have to also spend a bunch of time trying to figure out which ones would work on the particular OS I am building a project on.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

- Collections

##### ADDITIONAL INFORMATION

Current Galaxy behavior from `meta/main.yml`:

```yaml
galaxy_info:
  [...]
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
```

And appearance on Ansible Galaxy UI:

<img width="423" alt="Screen Shot 2019-08-06 at 1 53 17 PM" src="https://user-images.githubusercontent.com/481677/62567791-900acf00-b851-11e9-9890-ead8628590a0.png">
