### ISSUE TITLE
galaxy-info --offline option doesn't work

### ISSUE THREAD

**Issue by raffaeldutra** [ansible/ansible#60167]
##### SUMMARY
Running `ansible-galaxy info` command using --offline option does not give the "description" information from role_name/meta/main.yml. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
roles

##### ANSIBLE VERSION
```
2.8
```
##### STEPS TO REPRODUCE
```
ansible-galaxy init my-role
- my-role was created successfully
```

Executing the following command, you can't see the "description" information.
```
ansible-galaxy info --offline --roles-path=/home/user my-role

Role: my-role
        description: 
        dependencies: []
        galaxy_info:
                author: your name
                company: your company (optional)
                galaxy_tags: []
                license: license (GPL-2.0-or-later, MIT, etc)
                min_ansible_version: 2.4
        path: (u'/home/user', u'/home/user/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
```
##### EXPECTED RESULTS
```
Role: my-role
        dependencies: []
        galaxy_info:
                author: your name
                description: your description >> description goes here
                company: your company (optional)
                galaxy_tags: []
                license: license (GPL-2.0-or-later, MIT, etc)
                min_ansible_version: 2.4
        path: (u'/home/user', u'/home/user/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
```

Changing the `meta/main.yml` to the following code, it works:
```
description: your description
galaxy_info:
  author: your name
  company: your company (optional)
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.4
  galaxy_tags: []
dependencies: []
```

Command/output:
```
ansible-galaxy info --offline --roles-path=/home/user my-role

Role: my-role
        description: your description
        dependencies: []
        galaxy_info:
                author: your name
                company: your company (optional)
                galaxy_tags: []
                license: license (GPL-2.0-or-later, MIT, etc)
                min_ansible_version: 2.4
        path: (u'/home/user', u'/home/user/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles')
```
