### ISSUE TITLE
Bind mounts not working for lack of "requires" option.

### ISSUE THREAD

**Issue by queglay** [ansible/ansible#60176]
##### SUMMARY
when mounting an nfs volume, and also multiple bind mounts, the current mount module doesn't allow us to use lines like 
```
/data/rootfs/usr    /usr    none    x-systemd.requires=/data,bind    0    0
```
per this use case on stackexchange-
https://unix.stackexchange.com/questions/486777/etc-fstab-fails-to-bind-mount-on-boot-but-running-mount-a-works-correctly

in my case, using standard ansible mount commands, I can only produce an fstab file that looks like this, which when systemd mounts in parallel will cause unreliable behaviour.

```
10.0.11.11:/pool1/volume1 /pool1/volume1 nfs4 rsize=8192,wsize=8192,timeo=14,intr,_netdev 0 0
10.0.11.11:/pool2/volume2 /pool2/volume2 nfs4 rsize=8192,wsize=8192,timeo=14,intr,_netdev 0 0
/pool1/volume1/ /prod/ none bind 0 0
/pool2/volume2/ /volatile/ none bind 0 0
/pool1/volume1/ /aws_sydney_prod/ none bind 0 0
/pool2/volume2/ /aws_sydney_volatile/ none bind 0 
```

##### ISSUE TYPE
- cannot specify dependency for bind with ansible mount module.

##### COMPONENT NAME
mount

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_RETRIES(/vagrant/ansible.cfg) = 10
DEFAULT_GATHER_SUBSET(/vagrant/ansible.cfg) = [u'!hardware']
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/vagrant/ansible/hosts']
DEFAULT_LOG_PATH(/vagrant/ansible.cfg) = /vagrant/tmp/ansible_log
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
```

##### OS / ENVIRONMENT

vagrant image - ubuntu/trusty64 running on macbook pro.
clients with nfs mount issues are aws instances.

##### STEPS TO REPRODUCE

Here is a sample from my playbook which scours information to mount the nfs volumes and binds per the fstab file shown above.

```yaml
  - name: insert/update block in in /etc/fstab on remote host for found exports from onsite nas using original unique pool and volume names - master
    become: yes
    mount:
      fstype: nfs4
      opts: nfsvers=4.1
      path: "{{ item.item.mount_path }}"
      opts: rsize=8192,wsize=8192,timeo=14,intr,_netdev
      src: "{{ item.item.ip }}:{{ item.item.path }}"
      state: "{{ ( item.item.mount_path and item.rc == 0 and item.item.state == 'present') | ternary( 'mounted' , 'absent' ) }}"
    with_items:
    - "{{ site_presence.results }}"
    tags:
    - cloud_install

  - name: bind1 master mounts to named paths from local onsit nas to remote host.  bind2 references the absolute mount names such as /aws_sydney_prod.  bind1 is relative site names such as /prod, which are not pushed from cloud to onsite since those paths should exist onsite from a high performance local mount
    become: yes
    mount:
      fstype: none
      path: "{{ item.item.bind1 }}"
      opts: bind
      src: "{{ item.item.mount_path }}"
      # if the path exists, and it was found in the exports, then set to mounted, else remove.
      state: "{{ ( item.item.mount_path and item.item.bind1 and item.rc == 0 and item.item.state == 'present' ) | ternary( 'mounted' , 'absent' ) }}"
    with_items:
    - "{{ site_presence.results }}"
    tags:
    - cloud_install

  - name: bind2 master mounts to named paths.  bind2 references the absolute mount names such as /aws_sydney_prod.  bind1 is relative site names such as /prod, which are not pushed from cloud to onsite since those paths should exist onsite from a high performance local mount
    become: yes
    mount:
      fstype: none
      path: "{{ item.item.bind2 }}"
      opts: bind
      src: "{{ item.item.mount_path }}"
      # if the path exists, and it was found in the exports, then set to mounted, else remove.
      state: "{{ ( item.item.mount_path and item.item.bind2 and item.rc == 0 and item.item.state == 'present' ) | ternary( 'mounted' , 'absent' ) }}"
    with_items:
    - "{{ site_presence.results }}"
    tags:
    - cloud_install
```

##### EXPECTED RESULTS

Bind mounts should be able to specify dependencies

##### ACTUAL RESULTS

Upon boot of an instance, not all binds will necessarily be present.  mount -a will usually resolve the issue.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/mount.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/mount.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Thanks for reporting the issue, @queglay. Unfortunately I don't understand what's the problem here. According to the StackExchange link, you just need to add `x-systemd.requires=/your_mount` into the `opts` option of the `mount` module:

```yaml
- mount:
    src: 10.0.11.11:/pool1/volume1
    path: /pool1/volume1
    fstype: nfs4
    opts: rsize=8192,wsize=8192,timeo=14,intr,_netdev
    state: mounted

- mount:
    src: 10.0.11.11:/pool2/volume2
    path: /pool2/volume2
    fstype: nfs4
    opts: rsize=8192,wsize=8192,timeo=14,intr,_netdev
    state: mounted

- mount:
    src: /pool1/volume1
    path: /prod
    fstype: none
    opts: x-systemd.requires=/pool1/volume1,bind
    state: mounted

- mount:
    src: /pool2/volume2
    path: /volatile
    fstype: none
    opts: x-systemd.requires=/pool2/volume2,bind
    state: mounted

- mount:
    src: /pool1/volume1
    path: /aws_sydney_prod
    fstype: none
    opts: x-systemd.requires=/pool1/volume1,bind
    state: mounted

- mount:
    src: /pool2/volume2
    path: /aws_sydney_volatile
    fstype: none
    opts: x-systemd.requires=/pool2/volume2,bind
    state: mounted
```

This should work when Ansible runs it (first mount the NFS and then binds) as well as when the system reboots as the options contain the right order of mounts for systemd.
