### ISSUE TITLE
VMWare: vmware_guest_facts seems to ignore the folder option

### ISSUE THREAD

**Issue by GrandeTartine** [ansible/ansible#60199]
##### SUMMARY
When I use the folder option of the vmware_guest_facts, the module retrieve fact of another VM in a another folder, but not always.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/debug_vmware/venv/lib/python3.6/site-packages/ansible
  executable location = /root/debug_vmware/venv/bin/ansible
  python version = 3.6.6 (default, Jan 26 2019, 16:53:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Vcenter 6.5

##### STEPS TO REPRODUCE

I created 4 directories in my vcenter : /test00, /test01, /test02, /test03.
I created a VM test01 in the directory "/test00".
If I use vmware_guest_facts to retrieve informations about a vm name "test00", in each directory, it will match the existing VM in /test00
But, If I create another VM name "test01" in the directory "/test02", it's working as exepted. ( when there are 2 differents VM with the name "test01".)

```yaml
---
- name: "Playbook to show bug"
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Check if VM already existing.
    vmware_guest_facts:
      # Vcenter needed informations
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs | default(True) }}"
      # VM identification
      datacenter: "{{ datacenter_name }}"
      folder: "{{ item }}"
      name: "{{ vm_name }}"
    register: test
    failed_when: False
    delegate_to: localhost
    loop:
      - "/test00/"
      - "/test01/"
      - "/test02/"
      - "/test03/"

  - debug:
      msg: "{{ item.instance.hw_folder | default('Not Found') }}"
    loop: "{{ test.results }}"
    loop_control:
      label: "{{ item.item }}"
```

##### EXPECTED RESULTS

I exept to found the VM only when the "folder" option is in /test00/ and not the other folders (there are empty).

##### ACTUAL RESULTS

With each folder, it found the same VM, in /test00.

```paste below
PLAY [Playbook to show bug] *****************************************************************************************************************************************************************************************************************

TASK [Check if VM already existing.] ********************************************************************************************************************************************************************************************************
ok: [localhost -> localhost] => (item=/test00/)
ok: [localhost -> localhost] => (item=/test01/)
ok: [localhost -> localhost] => (item=/test02/)
ok: [localhost -> localhost] => (item=/test03/)

TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=/test00/) => {
    "msg": "/DC-MAQ6/vm/test00"
}
ok: [localhost] => (item=/test01/) => {
    "msg": "/DC-MAQ6/vm/test00"
}
ok: [localhost] => (item=/test02/) => {
    "msg": "/DC-MAQ6/vm/test00"
}
ok: [localhost] => (item=/test03/) => {
    "msg": "/DC-MAQ6/vm/test00"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

But, If I create another VM name "test00" in the directory "/test02", it's working as exepted. 
(There are a vm name "test00" in /test00 and /test02)

```
PLAY [Playbook to show bug] *****************************************************************************************************************************************************************************************************************

TASK [Check if VM already existing.] ********************************************************************************************************************************************************************************************************
ok: [localhost -> localhost] => (item=/test00/)
ok: [localhost -> localhost] => (item=/test01/)
ok: [localhost -> localhost] => (item=/test02/)
ok: [localhost -> localhost] => (item=/test03/)

TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=/test00/) => {
    "msg": "/DC-MAQ6/vm/test00"
}
ok: [localhost] => (item=/test01/) => {
    "msg": "Not Found"
}
ok: [localhost] => (item=/test02/) => {
    "msg": "/DC-MAQ6/vm/test02"
}
ok: [localhost] => (item=/test03/) => {
    "msg": "Not Found"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@GrandeTartine, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by GrandeTartine** [comment]
It is more critical than I initially thought.

Other vmware modules are impacted too.

For example, same test but with vmware_guest. The playbook modify the VM cpu at the value of "loop.index +1" (so 1, 2 3, and 4). Instead of modifying it one time when the right folder is set, it's modifying it the 4 time.
So if for some reason you try to modify a non existing VM, you could end up modifying another VM. It seems serious to me.

Playbook:
```yml
---
- name: "Playbook to show bug"
  hosts: localhost
  gather_facts: false

  tasks:
  - name: "Change CPU"
    vmware_guest:
      # Vcenter needed informations
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs | default(True) }}"

      # VM identification
      datacenter: "{{ datacenter_name }}"
      cluster: "{{ cluster_name }}"
      folder: "{{ item }}"
      name: "{{ vm_name }}"

      hardware:
        memory_mb: "1024"
        num_cpus: "{{ loop_index + 1 }}"
    delegate_to: localhost
    register: test
    loop:
      - "/test00/"
      - "/test01/"
      - "/test02/"
      - "/test03/"
    loop_control:
      index_var: loop_index

  - debug:
      msg: "{{ item.instance.hw_folder | default('Not Found') }}, vm: {{ item.instance.hw_name }}, cpu: {{ item.instance.hw_processor_count }}"
    loop: "{{ test.results }}"
    loop_control:
      label: "{{ item.item }}"
```
Result: 
```
PLAY [Playbook to show bug] *****************************************************************************************************************************************************************************************************************

TASK [Change CPU] ***************************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost] => (item=/test00/)
changed: [localhost -> localhost] => (item=/test01/)
changed: [localhost -> localhost] => (item=/test02/)
changed: [localhost -> localhost] => (item=/test03/)

TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=/test00/) => {
    "msg": "/DC-MAQ6/vm/test00, vm: test01, cpu: 1"
}
ok: [localhost] => (item=/test01/) => {
    "msg": "/DC-MAQ6/vm/test00, vm: test01, cpu: 2"
}
ok: [localhost] => (item=/test02/) => {
    "msg": "/DC-MAQ6/vm/test00, vm: test01, cpu: 3"
}
ok: [localhost] => (item=/test03/) => {
    "msg": "/DC-MAQ6/vm/test00, vm: test01, cpu: 4"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
