### ISSUE TITLE
Missing options for gcp_compute_instance.py

### ISSUE THREAD

**Issue by cmoone** [ansible/ansible#60209]
##### SUMMARY
Add deletion_protection true/false as an option for gcp_compute_instance.py. Add Shielded VM 
options, Turn on Secure Boot true/false, Turn on vTPM true/false, Turn on Integrity Monitoring true/false.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_compute_instance.py

##### ADDITIONAL INFORMATION
Would be used to fully configure an instance on creation from Ansible playbook without the need to script out updates for the instance after creation.

```yaml
   gcp_compute_instance:
      name: ansible-test-instance
      machine_type: n1-highmem-2
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      - auto_delete: 'false'
        boot: 'false'
        initialize_params:
          disk_name: ansible-test-instance-data
          disk_size_gb: 100
          disk_type: pd-standard
      metadata:
        created_by: 'ansible'
      network_interfaces:
      - subnetwork: 
          selfLink: "projects/{{ gcp_project }}/regions/us-east1/subnetworks/subnet-us-east1-elastic"
      zone: "{{ gcp_zone }}"
      **deletion_protection: 'true'**
      **shielded_vm_options:**
           **enable_secure_boot: 'true'**
           **enable_vtpm: 'true'**
           **enable_integrity_monitoring: 'true'**
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
```
