### ISSUE TITLE
lack of check_type in proxysql_replication_hostgroups

### ISSUE THREAD

**Issue by markuman** [ansible/ansible#60205]
##### SUMMARY

The `mysql_replication_hostgroups` table in proxysql supports different values in column `check_type`  for different backends.  
https://github.com/sysown/proxysql/wiki/Main-(runtime)#mysql_replication_hostgroups

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

proxysql_replication_hostgroups

##### ADDITIONAL INFORMATION

A current workaround for this is

```yaml
    - name: assign backend servers to replication hostgroups
      proxysql_replication_hostgroups:
        login_user: "{{ proxy_sql_admin_user }}"
        login_password: "{{ proxy_sql_admin_password }}"
        state: present
        writer_hostgroup: "{{ hostgroup_master }}"
        reader_hostgroup: "{{ hostgroup_slave }}"
        load_to_runtime: no

    - name: overwrite hostgroup check_type
      command: mysql -h 127.1 -uadmin -padmin -P6032 -e "update mysql_replication_hostgroups set check_type = 'innodb_read_only';"

    - name: load everything to runtime
      proxysql_manage_config:
        login_user: "{{ proxy_sql_admin_user }}"
        login_password: "{{ proxy_sql_admin_password }}"
        action: "LOAD"
        config_settings: "MYSQL VARIABLES"
        direction: "TO"
        config_layer: "RUNTIME"

```
