### ISSUE TITLE
tower_job_template: add option to set the custom_virtualenv for the job template

### ISSUE THREAD

**Issue by HardTy** [ansible/ansible#60200]
##### SUMMARY
Add the possibility to set a custom_virtualenv for a job template in Ansible Tower. The tower-cli is able to do it. But the option is missing in the Ansible module tower_job_template.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
tower_job_template
As I know it is also possible to set the custom_environment in organization and project.

##### ADDITIONAL INFORMATION
We use the tower_job_template module to setup our Ansible AWX Tower instances and configure it completly. We also added a custom_virtualenv to our instance and we want to set it with the Ansible tower_job_template module. 

At the moment we run it like this:
```yaml
  - name: create rhv-setup-vm job template
    tower_job_template:
      name: "rhv-setup-vm"
      description:
      job_type: run
      inventory: "{{ server_groupname }} GIT Inventory"
      project: "Ansible Git"
      playbook: "setup-vm.yml"
      credential: "ansible"
      state: present
      survey_enabled: true
      survey_spec: "{{ lookup('template', 'survey_rhv_setup_vm.json.j2') }}"

  - name: "add {{ path_to_custom_python_environment }} custom-virtualenv to 'rhv-setup-vm' job_template"
    command: "{{ tower-cli_env_path }}/bin/tower-cli job_template modify \
              --name 'rhv-setup-vm' \
              --project 'Ansible Git' \
              --playbook 'setup-vm.yml' \
              --custom-virtualenv '{{ path_to_custom_python_environment }}' \
              --format json"
```

It would be nice to use it like this:
```yaml
  - name: create rhv-setup-vm job template
    tower_job_template:
      name: "rhv-setup-vm"
      description:
      job_type: run
      inventory: "{{ server_groupname }} GIT Inventory"
      project: "Ansible Git"
      playbook: "setup-vm.yml"
      credential: "ansible"
      custom-virtualenv: '{{ path_to_custom_python_environment }}'
      state: present
      survey_enabled: true
      survey_spec: "{{ lookup('template', 'survey_rhv_setup_vm.json.j2') }}"
```
