### ISSUE TITLE
ansible-test idempotence tests for roles in Ansible Collections

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#60226]
##### SUMMARY

It would be nice to be able to test role idempotence in Ansible Collections when running integration tests with `ansible-test`.

Currently it's easy to test the idempotence of a single task, e.g.:

```yaml
- module_name:
    key: value
  register: result

- fail:
  when: result.changed
```

However, when testing roles (e.g. via `include_role`), there is no easy way to test idempotence:

```yaml
- name: Run the PHP role.
  include_role:
    name: geerlingguy.php_roles.php

- name: Test the PHP role's idempotence.
  include_role:
    name: geerlingguy.php_roles.php
  register: idempotence_result
```

In the case of `include_role`, the `changed` status is _always_ `false` because the tasks in the included role are inlined and don't affect the status of the actual act of including them...

Right now the only way to test idempotence is to write your own shell script in a `runme.sh` script, manually running the playbook two times, and then parsing the results using regex or string matching to check for `changed=0`.

I used to do that kind of thing before Molecule came along, but with Molecule, it includes easy integrated `idempotence` checks, where it basically re-runs the entire test playbook and checks for changes.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-test

##### ADDITIONAL INFORMATION
I propose a new CLI flag like `--test-idempotence` (or something like that), and if it is passed, it would run the integration target a 2nd time for each target, verifying the 2nd time that `changes=0`.
