### ISSUE TITLE
ios_linkagg: allow creation of Layer 2 port-channel groups

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#60229]
##### SUMMARY
ios_linkagg appears to create Layer 3 port-channel groups.  I would like to be able to create Layer 2 groups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_linkagg

##### ADDITIONAL INFORMATION
Currently the module runs:
```
interface port-channel #
end
```
This defines a Layer 3 port-channel with an assumed "no ip address" added to the config.  Then when layer 2 interfaces are added to the group, it fails with:
```
Command rejected (Port-channel3, Gi1/20): Either port is L2 and port-channel is L3, or vice-versa
```
Layer 2 port-channels have "switchport" set.  Perhaps that could be set as an option.  Someting like:

```yaml
---
- hosts: cisco
  gather_facts: no
  tasks:
    - name: Gather facts
      ios_facts:
    - ios_linkagg:
       group: 1
       state: present
       type: layer2
       mode: active
       members:
         - GigabitEthernet1/1
         - GigabitEthernet1/2
         - GigabitEthernet1/3
         - GigabitEthernet1/4

```

As an aside - I see that https://github.com/ansible/ansible/pull/43540 was only applied to ansible-2.6.  I'm also not sure if that really fixed the issue, or if the issue is the one described here.

This is with:
```
Cisco IOS Software, Catalyst 4500 L3 Switch Software (cat4500-IPBASEK9-M), Version 15.0(2)SG11, RELEASE SOFTWARE (fc2)
```
So not sure if different IOS versions are to blame.
