### ISSUE TITLE
vmware_export_ovf fails with error "a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by larrybg** [ansible/ansible#60234]
##### SUMMARY

Exporting VM to OVF template with vmware_export_ovf module and getting error "a bytes-like object is required, not 'str'".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_export_ovf

##### ANSIBLE VERSION

```paste below
2.8.3
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OS - CentOS 7
AWX - 4.0.0.0
virtualenv - ansible 2.8.3

##### STEPS TO REPRODUCE

Clone existing VM with vmware_guest module.
Run vmware_export_ovf to export new VM to OVF Template.

```yaml
- name: Clone VM for backup
    vmware_guest:
      validate_certs: False
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      datacenter: DC
      folder: /Automation/BACKUPS
      name: "{{ newVmHostName }}"
      state: poweredoff
      template: "{{ vm_name }}"
      annotation: "Backup created with AWX"
      cluster: MyCluster
    delegate_to: localhost
    register: deploy




  - name: Exporting data
    vmware_export_ovf:
      validate_certs: false
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      datacenter: DC
      name: "{{ newVmHostName }}"
      export_with_images: no
      export_dir: /var/tmp/ovf_template/
    register: results
```

##### EXPECTED RESULTS

Exported template

##### ACTUAL RESULTS

Execution fails with error "a bytes-like object is required, not 'str'".

```paste below

TASK [Exporting data] **********************************************************
task path: /var/lib/awx/projects/vmMaintBackup/vmBackupDriver.yml:72
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root

<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139 `" && echo ansible-tmp-1565207124.098111-235606062377139="` echo /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139 `" ) && sleep 0'
Using module file /var/lib/awx/venv/ansible_2.8.3/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_export_ovf.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-21996atmfy13x/tmpvws3plbk TO /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139/AnsiballZ_vmware_export_ovf.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139/ /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139/AnsiballZ_vmware_export_ovf.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/var/lib/awx/venv/ansible_2.8.3/bin/python36 /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139/AnsiballZ_vmware_export_ovf.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1565207124.098111-235606062377139/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "DC",
            "export_dir": "/var/tmp/ovf_template/",
            "export_with_images": false,
            "folder": null,
            "hostname": "5.9.220.5",
            "name": "SANDBOX-phpIPAM-20190807-194354",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "username": "DC\\\\autouser",
            "uuid": null,
            "validate_certs": false
        }
    },
    "msg": "a bytes-like object is required, not 'str'"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
