### ISSUE TITLE
VMware: require vmware_guest_tools_wait module return more tools specific facts not vm facts

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#60258]
##### SUMMARY

This module can return the facts of VMware tools installed in guest OS, like: tools installed or not, tools running status, installed tools version, installed Open VM tools or VMware tools MSI install in Window or TAR install in Linux, the history of the tools install(need to test), etc.
Now, it returns VM facts we can get it from vmware_guest_facts module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest_tools_wait
##### ADDITIONAL INFORMATION

For example,
```yaml
    "tools_facts": {
        "changed": false,
        "failed": false,
         "instance": {
             "hw_name": "dw_win10_64_test",
             "hw_power_status": "poweredOn",
             "hw_product_uuid": "42284ad6-f28c-f582-1ab9-xxxx",
             "hw_version": "vmx-14",
             "instance_uuid": "50283c1f-4a0a-0ef9-e0cf-xxxx",
             "hw_guest_full_name": "Microsoft Windows 10 (64-bit)",
             "hw_guest_id": "windows9_64Guest",
             "guest_tools_status": "guestToolsRunning",
             "guest_tools_version": "10346",
             "guest_tools_version_release": "10.3.10",
             "guest_tools_install_type": "guestToolsTypeMSI", 
             ...
            }
    }
         
```
