### ISSUE TITLE
Enable unarchive module to process plain, non-tarred archives

### ISSUE THREAD

**Issue by rmbleeker** [ansible/ansible#60260]
##### SUMMARY
Not all archives are **tarred**, for example it's quite common for single files to be compressed directly with **gzip** or **xz**. Examples: log files compressed by logrotate (gzip) or binary software releases (often xz). It would be nice if Ansible's unarchive modules would be able to handle these files instead of failing because zip and gtar can't handle them.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
unarchive

##### ADDITIONAL INFORMATION
Just as an example we can download and install Gitea.

```yaml
- name: extract gitea
  unarchive:
    src: https://dl.gitea.io/gitea/1.9.0/gitea-1.9.0-linux-amd64.xz
    dest: /opt/gitea
    mode: 0755
    remote_src: yes
```

This results in a `Failed to find handler` error.
