### ISSUE TITLE
vmware_host_ntp Internal Module WARNING

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#60275]
##### SUMMARY
When executing vmware_host_ntp an Ansible warning is issued

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_host_ntp

##### ANSIBLE VERSION
```
ansible 2.8.0
  config file = /home/nick/vmware-ansible/ansible.cfg
  configured module search path = [u'/home/nick/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
HOST_KEY_CHECKING(/home/nick/vmware-ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/nick/vmware-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RedHat7.6 and CentOS 7.5
vSphere 6.7

##### STEPS TO REPRODUCE
Just run the module with some valid parameters as below. It has been tried with the Ansible 2.8 default module and also the version on devel

```
- name: 'Configure ESXi NTP settings'
  vmware_host_ntp:
    hostname: '{{ ansible_host }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    cluster_name: '{{ cluster_name }}'
    state: 'present'
    validate_certs: '{{ validate_certs }}'
    ntp_servers:
      - '{{ time1 }}'
      - '{{ time2 }}'
```

##### EXPECTED RESULTS
No purple Ansible warnings

##### ACTUAL RESULTS
The following is in purple
``` 
[WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.
```
