### ISSUE TITLE
k8s plugin not overwriting sts, rather updating it

### ISSUE THREAD

**Issue by Swetad90** [ansible/ansible#60285]
##### SUMMARY
When using K8s module to deploy a prometheus statefulset with initial config containing secret name "prometheus_secret_name", when we change the ansible template file to rename it as "prometheus-secret-name", ansible is updating the statefulset to have both the secret names.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```paste below
ansible 2.7.8.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sisadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

18.04.1 LTS (Bionic Beaver)

##### STEPS TO REPRODUCE

```
- name: Create prometheus statefulsets with HA
  k8s:
    state: present
    definition: "{{ lookup('template', 'prometheus/prometheus_statefulset.yaml.j2') }}"
```
```
prometheus_statefulset.yaml.j2:

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ install_metrics_monitoring_server.prometheus_sts_name }}"
  labels:
    app: prometheus
spec:
  serviceName: "{{ install_metrics_monitoring_server.prometheus_sts_name }}"
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        # We will use this label to put all StoreAPis
        # under the same headless service for
        # SRV lookup: thanos-store-api.default.svc
        thanos-store-api: "true"
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsNonRoot: true
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: "{{ install_metrics_monitoring_server.prometheus_image_name }}"
        args:
          - --config.file=/etc/prometheus-shared/prometheus.yaml
          - --storage.tsdb.path=/prometheus
          - --web.enable-lifecycle
          - --storage.tsdb.retention.time={{ install_metrics_monitoring_server.prometheus_retentionperiod }}
          - --storage.tsdb.min-block-duration=2h
          - --storage.tsdb.max-block-duration=2h
        ports:
          - name: http-prometheus
            containerPort: 9090
        volumeMounts:
          - name: config-shared
            mountPath: /etc/prometheus-shared
          - name: prometheus
            mountPath: /prometheus
          - name: prometheus-secret-name
            mountPath: /etc/prometheus/dmz
          - name: rules
            mountPath: {{ install_metrics_monitoring_server.prometheus_rules_file }}

      volumes:
         - name: config
           configMap:
             name: "{{ install_metrics_monitoring_server.prometheus_configmapname}}"
         - name: config-shared
           emptyDir: {}
         - name: prometheus-secret-name
           secret:
             secretName: prometheus-secret-name
         - name: rules
           configMap:
             name: rules
         
```

##### EXPECTED RESULTS

ansible to overwrite the secret name in existing sts and not create a new one
```
 prometheus-secret-name:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-secret-name
    Optional:    false
```

##### ACTUAL RESULTS

```
   prometheus_secret_name:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus_secret_name
    Optional:    false
   prometheus-secret-name:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-secret-name
    Optional:    false
```
