### ISSUE TITLE
vmware_guest- disks getting created on same datastore when cloning from template

### ISSUE THREAD

**Issue by saravananoff** [ansible/ansible#60286]
##### SUMMARY
When a VM gets created from an Template and disks should be created on defined datastore. But disks are getting crated on same datastore.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, May  8 2019, 05:28:42) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

VMware Vsphere 6.0
Deploying Windows Server 2016 Template with multiple disks.

##### STEPS TO REPRODUCE

```yaml
- name: "Create VM from template"
  vmware_guest: 
    validate_certs: false
    hostname: "{{ vCenter }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    esxi_hostname: "{{ VirtualHost }}"
    datacenter: "{{ Datacenter }}"
    folder: "{{ VMFolder }}"
    resource_pool: "{{ ResourcePool }}"
    name: "{{ server_name }}"
    template: "{{ VMTemplate }}"
    state: poweredon
    disk: 
      - size_gb: "{{ os_disk_size }}"
        type: eagerzeroedthick
        datastore: "{{ OSDatastoreName }}"
        autoselect_datastore: false
      - size_gb: "{{ E_disk_Size }}"
        type: eagerzeroedthick
        datastore: "{{ DataDatastoreName  }}"
        autoselect_datastore: false
    hardware: 
      memory_mb: "{{ memorymb }}"
      num_cpus: "{{ numcpus }}"
    networks: 
      - device_type: vmxnet3
        dns_servers: 
          - "{{ DNS1 }}"
          - "{{ DNS2 }}"
        gateway: "{{ Gateway }}"
        ip: "{{ IPAddress }}"
        name: "{{ PortGroup }}"
        netmask: "{{ Subnet }}"
        start_connected: true
        type: static
    wait_for_ip_address: true
    customization: 
      autologon: yes
      autologoncount: 2
      dns_suffix: "{{ domain }}"
      fullname: admin
      hostname: "{{ server_name }}"
      orgname: "Company"
      password: "{{ vmlocaladminpass }}"
      Timezone: 20
      runonce:
        - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfiguringRemotingForAnsible.ps1
  delegate_to: localhost  

```

##### EXPECTED RESULTS

When we clone a machine from template using above mentioned task, it should create first disk on {{ OSDatastoreName }} and second disk on {{ DataDatastoreName  }}. But currently it is creating both disks on {{ OSDatastoreName }} datastore. 

We have storage DRS, but we are inputting exact data stores for the disk creation.  

##### ACTUAL RESULTS

Currently it is creating both disks on {{ OSDatastoreName }} datastore. 

```paste below

```
