### ISSUE TITLE
group module: support creating multiple groups

### ISSUE THREAD

**Issue by L1ghtn1ng** [ansible/ansible#60296]
##### SUMMARY

Be able to do the following;
```yaml
- name: Creating required groups
  group:
    name: "{{ groups }}"
    state: present
  vars:
    groups:
    - sysadmins
    - superusers
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

group module

##### ADDITIONAL INFORMATION

From the documentations https://docs.ansible.com/ansible/latest/modules/group_module.html example you would need to create multiple entries for creating more than 1 group and I have tried running the below in a playbook and it fails. Being able to do the below just once keeps things tidy

```yaml
- name: Creating required groups
  group:
    name: "{{ groups }}"
    state: present
  vars:
    groups:
    - sysadmins
    - superusers
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/group.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case this is easy to achieve with a loop.
```yaml
- name: Creating required groups
  group:
    name: "{{ item }}"
    state: present
  loop:
    - sysadmins
    - superusers
```

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
