### ISSUE TITLE
archive: AttributeError: 'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by OPSTime** [ansible/ansible#60309]
**Version：**

> ansible 2.8.1
>   config file = /srv/ansible-deploy/ansible.cfg
>   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /bin/ansible
>   python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Error：**

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'startswith'
> failed: [localhost] (item={u'version': u'1.6.5', u'name': u'apr'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "apr", "version": "1.6.5"}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1565348138.1-75003094074592/AnsiballZ_archive.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1565348138.1-75003094074592/AnsiballZ_archive.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1565348138.1-75003094074592/AnsiballZ_archive.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_archive_payload_nJdpN9/__main__.py\", line 534, in <module>\n  File \"/tmp/ansible_archive_payload_nJdpN9/__main__.py\", line 236, in main\n  File \"/usr/lib64/python2.7/posixpath.py\", line 261, in expanduser\n    if not path.startswith('~'):\nAttributeError: 'dict' object has no attribute 'startswith'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'startswith'

**Task:**
```
- name: archive packages
  archive:
    path:
      - path: "/usr/local/{{ item.name }}-{{ item.version }}"
      - dest: "roles/tomcat/files/{{ item.name }}-{{ item.version }}.tar.gz"
    format: gz
    force_archive: true
  loop:
    - { name: "apr", version: "{{ apr_version }}" }
```
