### ISSUE TITLE
ansible-galaxy collections install -r requirements.yml to support multiple servers

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/ansible#60316]
##### SUMMARY
Currently, a single api-server must be specified per `ansible-galaxy` invocation via `ansible-galaxy --server mygalaxy.myhost.com`. When processing a `requirements.yml` file where collections could come from multiple different servers, this is problematic.

I would like a way to specify multiple collection servers in a single invocation of `ansible-galaxy`. Preferably, somewhere in the `requirements.yml` file.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-galaxy

##### ADDITIONAL INFORMATION

The meat of the design decision for this feature is deciding where to store the credentials and relating the credentials to the specific server.

A couple of potential implementation examples that would meet my needs:
```yaml
collections: 
  - name: ansible.tower 
    server: automation-hub.cloud.redhat.com 
    api_key: blahblahblah 
  - name: awx.awx 
    server: galaxy.ansible.com 
    api_key: blah2blah2 
```
Obviously don't love the above solution because it encourages putting creds in a file that will be source controlled.
  
OR 

```yaml
collections: 
  - name: awx.awx 
    server: galaxy.ansible.com 
  - name: ansible.tower 
    server: galaxy.mysite.com 
```
With a corresponding tempish auth/config file.

```  
#~/.ansible_galaxy 
[galaxy.ansible.com] 
server=galaxy.mysite.com
api_key=deadbeef 

[automation-hub.cloud.redhat.com] 
server=galaxy.ansible.com 
api_key=blahblah 
```
Note that the above example implies that only 1 auth entry is allowed per-unique-url. A server name could be added in `requirements.yml` to relax.

Also note that in the second example I would need a way to specify the `.ansible_galaxy` to use. The need for this stems from a multi-tenant environment.
