### ISSUE TITLE
Ansible yum module not downgrade 2.8.2

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ansible/ansible#60323]
##### SUMMARY
Ansible yum module not downgrade 2.8.2

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Yum module

##### ANSIBLE VERSION
2.8.2

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
RedHat 7.6/7.7

##### STEPS TO REPRODUCE

```
- name: update common outdated packages
  yum:
    name: '{{ list packages }}'
    state: latest
    allow_downgrade: yes
```

When example

```
list packages:
- htop
- systemd-219-62.el7_6.9
```

Show up to date.
If we have systemd old version then update correctly.

##### EXPECTED RESULTS
Downgrade installing exact version systemd-219-62.el7_6.9 and update htop to last version (With and systemd package installed version latest: 219-67.el7_7.1)

##### ACTUAL RESULTS
The htop are updated and systemd not downgrade and show: up to date.
