### ISSUE TITLE
route53_facts parameter max_items asks for string

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#60345]
##### SUMMARY
The max_items parameter will throw a warning for integers (numbers) and wants a string.  If you put an integer you will get a warning
```
[WARNING]: The value 1 (type int) in a string field was converted to u'1' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
route53_facts

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = [u'time']
DEFAULT_FORKS(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = [u'/Users/sean/Documents/GitHub/workshops/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = yaml
HOST_KEY_CHECKING(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = 60
RETRY_FILES_ENABLED(/Users/sean/Documents/GitHub/workshops/provisioner/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS 10.14.5 (18F132)

##### STEPS TO REPRODUCE

```yaml
- name: GRAB ROUTE53 INFORMATION
  route53_facts:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: "student1.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    max_items: "{{student_total}}"
  register: record_sets
```

##### EXPECTED RESULTS
no warning, works normally

##### ACTUAL RESULTS

```paste below
[WARNING]: The value 1 (type int) in a string field was converted to u'1' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

```
