### ISSUE TITLE
yum cleanup is broken

### ISSUE THREAD

**Issue by das7pad** [ansible/ansible#60349]
##### SUMMARY
Performing a one off cleanup task like the cli command `$ yum autoremove` should remove orphaned packages, like previous dependencies. But translated into an ansible task, no changes are applied to the system.

```yaml
- yum:
    autoremove: yes
```

Quoting from the docs for the `autoremove` option of the yum module:

> Should be used alone or when state is absent

I already spotted the bug (-> PR https://github.com/ansible/ansible/pull/60350), but noticed another issue.

Yum would now remove packages for which I previously set `state=present` via ansible.

This is due to the _install reason_ handling of yum. Given a package PARENT and a dependency CHILD. Both packages are not present on the target system. Installing PARENT would set reason to _user_ for PARENT and _dep_ for the CHILD. Installing CHILD explicit would not make any changes to the _install reason_ of it. After removing PARENT and performing an autoremove, the package CHILD is gone too.

TL;DR Packages that were previously installed as dependency are not marked as user-installed.

`$ yum install SOME_PACKAGE` would not mark it as well, but we are likely not seeing a change here any time soon. I found some bug reports that seem to be related, but none of them received too much attention (https://bugzilla.redhat.com/show_bug.cgi?id=1177540, can't find the other one) or were marked as duplicate of an unrelated bug (1376597, 1303721).

In addition to the PR for the missing autoremove invocation, I am proposing to mark packages installed via ansible with the install reason _user_.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/SNIP/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /SNIP/ansible/lib/ansible
  executable location = /SNIP/ansible/venv/bin/ansible
  python version = 2.7.15 SNIP
```
a01ee2759d309f8433aefbdaf477903fe0156639

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

CentOS7
Fedora30

##### STEPS TO REPRODUCE

https://github.com/ansible/ansible/issues/60349#issuecomment-526770917

##### EXPECTED RESULTS

orphaned packages are removed, excluding packages that were previously installed via ansible

##### ACTUAL RESULTS

no changes applied

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @kustodian @maxamillion @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @kustodian @maxamillion @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by das7pad** [comment]
Here is a demo playbook showing the brokenness.

```yaml
---

- hosts: all
  gather_facts: no
  tasks:
    - name: disable silent autoremove for fedora
      ini_file:
        path: /etc/dnf/dnf.conf
        section: main
        option: clean_requirements_on_remove
        value: 'false'
        create: false
      failed_when: no

    - name: ensure git and dep are not installed
      yum:
        name:
          - git
          - perl-HTTP-Tiny
        state: absent
      failed_when: no

# feature flags via variables
#
# PASS: install_before_git=1
#   install dep -> install git -> remove git -> autoremove -> check dep
#
# FAIL: install_before_delete=1
#   install git -> install dep -> remove git -> autoremove -> check dep
#
# FAIL: install_after_delete=1
#   install git -> remove git -> install dep -> autoremove -> check dep
#
# $ ansible-playbook -e install_before_git=1 ...

- hosts: all
  gather_facts: no
  tasks:
    - when: "install_before_git is defined"
      name: install dep before installing git
      yum:
        name: perl-HTTP-Tiny

    - name: install git
      yum:
        name: git

    - when: "install_before_delete is defined"
      name: install dep after installing git
      yum:
        name: perl-HTTP-Tiny

    - name: delete git
      yum:
        name: git
        state: absent

    - when: "install_after_delete is defined"
      name: install dep after deleting git
      yum:
        name: perl-HTTP-Tiny

    - name: autoremove any orphaned deps
      yum:
        autoremove: yes

    - name: check for dep, which we installed earlier
      yum:
        name: perl-HTTP-Tiny
      check_mode: yes
      register: install_check

    - name: dep should not went missing
      assert:
        that:
          - "install_check is not changed"
```
