### ISSUE TITLE
routeros_command - fails with timeout on "/system reboot"

### ISSUE THREAD

**Issue by ekzkgz** [ansible/ansible#60362]
##### SUMMARY
When running a command `/system reboot` recieve: 
"command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
routeros_command

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian 9
RouterOS 6.45.2-3

##### STEPS TO REPRODUCE

```yaml
- name: Update system

  hosts: office-routers
  connection: network_cli
  gather_facts: false
  tasks:
    - name: system command
      routeros_command:
        commands: /system reboot

```

##### ACTUAL RESULTS

```paste below
fatal: [10.100.101.2]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "commands": [
                "/system reboot"
            ], 
            "interval": 1, 
            "match": "all", 
            "retries": 10, 
            "wait_for": null
        }
    }, 
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
```
