### ISSUE TITLE
ovirt: linux boot params removal

### ISSUE THREAD

**Issue by liranr23** [ansible/ansible#60383]
##### SUMMARY

linux boot parameters for a VM is going to be removed due to:
https://bugzilla.redhat.com/1732437
The ansible should not be able to invoke these options.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_vm
ovirt_instance_type

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
```

##### CONFIGURATION

```paste below
Default
```

##### STEPS TO REPRODUCE

```yaml
---

- name: Update a VM
  hosts: all
  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ api_url }}"
            username: "{{ username }}"
            password: "{{ password }}"
            insecure: "{{ insecure }}"
          when: ovirt_auth is undefined or not ovirt_auth
          register: loggedin

        - name: Change linux boot params
          ovirt_vm:
            auth: "{{ ovirt_auth }}"
            name: test
            operating_system: other_linux
            kernel_path: iso://initramfs.img
      always:
        - name: Logout from oVirt
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
          when: not loggedin.skipped | default(false)

```

##### EXPECTED RESULTS

Should fail with unsupported type.

##### ACTUAL RESULTS

At the moment the operation functioning. In ovirt 4.4 soon it won't be supported.

```paste below

```
