### ISSUE TITLE
VMware: Ability to set response to “Power off and restart VMs”  in vmware_cluster HA settings

### ISSUE THREAD

**Issue by arjunprakashn** [ansible/ansible#60408]
HA Settings :- Response for Host Isolation under the Failures and Responses should be set to “Power off and restart VMs”  when we creating cluster from vmware_cluster

- Feature Idea

##### COMPONENT NAME
<vmware_cluster>

##### ADDITIONAL INFORMATION
<HA Settings :- Response for Host Isolation under the Failures and Responses should be set to “Power off and restart VMs”  when we creating cluster from vmware_cluster -->

HA Settings :- Response for Host Isolation under the Failures and Responses should be set to “Power off and restart VMs”  when we creating cluster from vmware_cluster

```


- name: Create Clusters
  vmware_cluster:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{validate_certs}}"
    datacenter_name: "{{ datacenter_name }}"
    cluster_name: "{{ cluster_name }}"
    enable_ha: "{{ vcenter_ha_enable }}"
    ha_vm_monitoring: "{{ hostvars[payload.summary.name].cluster_settings.HA_settings.vm_monitoring }}"
    enable_drs: "{{ hostvars[payload.summary.name].cluster_settings.DRS_settings.enable }}"
    drs_default_vm_behavior: "fullyAutomated"
    ha_admission_control_enabled: "yes"
    ha_failover_level: "{{ hostvars[payload.summary.name].cluster_settings.HA_settings.hostfailure_tolerance }}"
    ha_host_monitoring: "enabled"
    state: 'present'
  register: vmware_cluster_result
  delegate_to: localhost
```
