### ISSUE TITLE
VMware: “Define host failover capacity by” should be set to “cluster resource percentage” under Admission Control

### ISSUE THREAD

**Issue by arjunprakashn** [ansible/ansible#60409]
currently no support in vmware_cluster ansible module to set:- “Define host failover capacity by” should be set to “cluster resource percentage” under Admission Control

- Feature Idea

##### COMPONENT NAME
vmware_cluster

HA Settings :- “Define host failover capacity by” should be set to “cluster resource percentage” under Admission Control
```
- name: Create Clusters
  vmware_cluster:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{validate_certs}}"
    datacenter_name: "{{ datacenter_name }}"
    cluster_name: "{{ cluster_name }}"
    enable_ha: "{{ vcenter_ha_enable }}"
    ha_vm_monitoring: "{{ hostvars[payload.summary.name].cluster_settings.HA_settings.vm_monitoring }}"
    enable_drs: "{{ hostvars[payload.summary.name].cluster_settings.DRS_settings.enable }}"
    drs_default_vm_behavior: "fullyAutomated"
    ha_admission_control_enabled: "yes"
    ha_failover_level: "{{ hostvars[payload.summary.name].cluster_settings.HA_settings.hostfailure_tolerance }}"
    ha_host_monitoring: "enabled"
    state: 'present'
  register: vmware_cluster_result
  delegate_to: localhost
```
