### ISSUE TITLE
module `script`: add parameter `content`

### ISSUE THREAD

**Issue by tagirb** [ansible/ansible#60413]
##### SUMMARY
The `copy` module supports the parameter `content`, which allows to define inline content for a file to be copied to the remote system.
The `script` module does not have it. Having such a parameter is handy for storing short scripts directly in the playbooks / role task lists rather than in separate files.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
script

##### ADDITIONAL INFORMATION
```yaml
- name: run a short inline script
  script:
    content: |
       echo this is my
       echo multiline inline
       echo script
```
