### ISSUE TITLE
win_uri returns module failure when return_content is set to yes

### ISSUE THREAD

**Issue by spachika** [ansible/ansible#60434]
##### SUMMARY

win_uri module returns MODULE FAILURE error when return_content is set to yes
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_uri

##### ANSIBLE VERSION

```paste below
2.6.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 2016

##### STEPS TO REPRODUCE

```yaml
win_uri:
    url: '{{ url }}'
    method: POST
    content_type: "application/json"
    body:
      username: '{{ user }}'
      password: '{{ password }}'
      servername: '{{ ansible_nodename }}'
      aliasname: '{{ alias }}'
      environment: '{{ env }}'
    return_content: yes
  register: dns
```

##### EXPECTED RESULTS

output in structured JSON format

##### ACTUAL RESULTS

```paste below
"module_stderr": "\r\n"
"rc": 0,
"msg": "MODULE FAILURE"
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@spachika: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by spachika** [comment]
##### SUMMARY

win_uri module returns MODULE FAILURE error when return_content is set to yes
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_uri

##### ANSIBLE VERSION

```paste below
2.6.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 2016

##### STEPS TO REPRODUCE



```yaml
win_uri:
    url: '{{ url }}'
    method: POST
    content_type: "application/json"
    body:
      username: '{{ user }}'
      password: '{{ password }}'
      servername: '{{ ansible_nodename }}'
      aliasname: '{{ alias }}'
      environment: '{{ env }}'
    return_content: yes
  register: dns
```



##### EXPECTED RESULTS

output in structured JSON format

##### ACTUAL RESULTS



```paste below
"module_stderr": "\r\n"
"rc": 0,
"msg": "MODULE FAILURE"
```
