### ISSUE TITLE
junos_system does not remove name server configs when set to absent

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible#60432]
##### SUMMARY
Using the `junos_system` module to remove name servers from the current configuration does not work with the `state: absent` parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`junos_system`

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /home/student1/.ansible.cfg
  configured module search path = [u'/home/student1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = [u'/home/student1/networking-workshop/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

RHEL 7.6

##### STEPS TO REPRODUCE

```yaml
---
- name: JUNOS MODULE TO REMOVE SYSTEM CONFIGS
  hosts: juniper
  gather_facts: false

  tasks:

    - name: ENSURE THAT THE SYSTEM CONFIGS ARE REMOVED
      junos_system:
        state: absent
        name_servers:

```

##### ACTUAL RESULTS

Verbose output of relevant task
```paste below
changed: [rtr3] => changed=true 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  invocation:
    module_args:
      active: true
      domain_name: null
      domain_search: null
      host: null
      hostname: null
      name_servers: null
      password: null
      port: null
      provider: null
      ssh_keyfile: null
      state: absent
      timeout: null
      transport: null
      username: null

```
