### ISSUE TITLE
ios_command: ftp copy timeout

### ISSUE THREAD

**Issue by jmcgill298** [ansible/ansible#60440]
##### SUMMARY
Using `ios_command` module to transfer a file, the module exits before the file is finished transferring.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

targeting Cisco 3850

##### STEPS TO REPRODUCE

Issuing copy command for large OS image with the switch being located far from the Ansible Control Host.

```yaml
- ios_command:
    commands: "copy {{ source_url }} {{ destination_url }}"
- pause:
    seconds: 3
- ios_command:
    commands: "verify /md5 {{ desintation_url }}"
```
ansible_connect/command_timeout values are raised to a very high value to avoid timeouts

##### EXPECTED RESULTS

File to finish transferring and then Ansible continues executing the next tasks serially.

##### ACTUAL RESULTS

The first task to transfer the file exits before the task is complete. The return shows up as `None` instead of the results from transferring the file. I would expect something like `bytes transferred...`. The execution then continues with pause, and md5 verification. Since the file transfer was interrupted (Ansible completed task early), the switch cleans up the file as it is incomplete. The md5 check then enters a destination file that doesn't exist and creates a failed task (expected based on behavior of first task).

```paste below
Task 1:
{"stdout": ["None"], "failed": False}
```
