### ISSUE TITLE
RFE: os_object support deleting container and all files

### ISSUE THREAD

**Issue by jhg03a** [ansible/ansible#60449]
##### SUMMARY

As a os_object module user I'd like to be able to delete a container and all its contents.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

os_object

##### ADDITIONAL INFORMATION

Today if you try to delete a container that still has any files in it, you receive the message: `The container is not empty. Please delete the objects inside it before deleting the container`.  On the openstack CLI, normally you would pass in the `--recursive` option to delete the container and all its contents.  Alternatively, the os_object module could support a means to list all container contents in an order that could be passed to an ansible `loop` invocation of os_object prior to deleting the container itself.  The latter solution, while more complicated to get in the right order, is more powerful as it allows users to retrieve the contents of a swift container.

```yaml
- name: Destroy the Openstack Swift Container and its contents
  os_object:
    auth:
      auth_url: "{{ tf_swift_auth_url }}"
      tenant_name: "{{ tf_swift_tenant_name }}"
      domain_name: "{{ tf_swift_domain_name }}"
      tenant_id: "{{ tf_swift_tenant_id }}"
    region_name: "{{ tf_swift_region_name }}"
    container: "{{ tf_swift_container_name }}"
    state: absent
    recursive: true

# OR

- name: Get the Openstack Swift Container contents
  os_object:
    auth:
      auth_url: "{{ tf_swift_auth_url }}"
      tenant_name: "{{ tf_swift_tenant_name }}"
      domain_name: "{{ tf_swift_domain_name }}"
      tenant_id: "{{ tf_swift_tenant_id }}"
    region_name: "{{ tf_swift_region_name }}"
    container: "{{ tf_swift_container_name }}"
    state: list
  register: container_contents

- name: Destroy the contents of the Openstack Swift Container
  os_object:
    auth:
      auth_url: "{{ tf_swift_auth_url }}"
      tenant_name: "{{ tf_swift_tenant_name }}"
      domain_name: "{{ tf_swift_domain_name }}"
      tenant_id: "{{ tf_swift_tenant_id }}"
    region_name: "{{ tf_swift_region_name }}"
    container: "{{ tf_swift_container_name }}"
    state: absent
    filename: "{{ item }}"
  with_items: "{{ container_contents }}"

- name: Destroy the Openstack Swift Container
  os_object:
    auth:
      auth_url: "{{ tf_swift_auth_url }}"
      tenant_name: "{{ tf_swift_tenant_name }}"
      domain_name: "{{ tf_swift_domain_name }}"
      tenant_id: "{{ tf_swift_tenant_id }}"
    region_name: "{{ tf_swift_region_name }}"
    container: "{{ tf_swift_container_name }}"
    state: absent
```
