### ISSUE TITLE
Failed to change the permission

### ISSUE THREAD

**Issue by xgy560501** [ansible/ansible#60452]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

2.8.2
```
CONFIGURATION

```paste below
default
```

##### OS / ENVIRONMENT

centos7

##### STEPS TO REPRODUCE

```yaml
  - name: 创建日志文件
    file:
      path: /var/log/shell_audit/audit.log
      state: touch
      owner: nodody
      group: nodody
      mode: 0002
      attributes: +a
```

##### ACTUAL RESULTS

```paste below

fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0002", "msg": "chown failed: failed to look up user nodody", "owner": "root", "path": "/var/log/shell_audit/audit.log", "size": 959, "state": "file", "uid": 0}
