### ISSUE TITLE
AWS - Ansible 2.7 - aws_s3 valid session token permission denied

### ISSUE THREAD

**Issue by mathieucoavoux** [ansible/ansible#60460]
##### SUMMARY
When using STS token to connect to a S3 bucket I receive a permission denied from AWS when the token is valid
Versions affected: <= v2.7.12

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module: aws_s3
Related module_utils: ec2.py

##### ANSIBLE VERSION

```
ansible 2.7.12
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jun 24 2019, 19:20:54) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
none
```

##### OS / ENVIRONMENT

Amazon Linux release 2 (Karoo)

##### STEPS TO REPRODUCE

```yaml
- hosts: test
  vars:
    aws_profile: "profile1"
    accountid: 123456789
  tasks:
    # This module is working
    # Get the token
    - sts_assume_role:
        role_arn: "arn:aws:iam::123456789:role/test_role"
        role_session_name: "testsessiotestsession"
      register: assumed_role
      delegate_to: localhost
    # This step failed
    - aws_s3:
        bucket: "bucketname"
        profile: "{{aws_profile}}"
        mode: list
        object: "/"
      register: list
      environment:
        AWS_ACCESS_KEY_ID: "{{assumed_role.sts_creds.access_key}}"
        AWS_SECRET_ACCESS_KEY: "{{assumed_role.sts_creds.secret_key}}"
        AWS_SESSION_TOKEN: "{{assumed_role.sts_creds.session_token}}"
        AWS_SECURITY_TOKEN : "{{assumed_role.sts_creds.session_token}}"
```

##### EXPECTED RESULTS

```
PLAY [test] *******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [192.168.0.1]

TASK [sts_assume_role] ********************************************************************************************************************************************************************************************
changed: [192.168.0.1 -> localhost]

TASK [aws_s3] *****************************************************************************************************************************************************************************************************
ok: [192.168.0.1]

PLAY RECAP ********************************************************************************************************************************************************************************************************
192.168.0.1 
```

##### ACTUAL RESULTS

```
PLAY [test] *******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [192.168.0.1]

TASK [sts_assume_role] ********************************************************************************************************************************************************************************************
changed: [192.168.0.1 -> localhost]

TASK [aws_s3] *****************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
fatal: 192.168.0.1]: FAILED! => {"boto3_version": "1.9.205", "botocore_version": "1.12.92", "changed": false, "error": {"code": "403", "message": "Forbidden"}, "msg": "Failed while looking up bucket (during bucket_check) XYZ.: An error occurred (403) when calling the HeadBucket operation: Forbidden",..
	

```
