### ISSUE TITLE
[os_server] userdata usage example doesn't work

### ISSUE THREAD

**Issue by Maghin** [ansible/ansible#60481]
##### SUMMARY

Example for userdata usage in the os_server module does not work with the cloud-init module "chpasswd". According to the cloud-init documentation ([here](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#set-passwords)) : 

> The chpasswd config key accepts a dictionary containing a single one of two keys, either `expire` or `list`

The example provided with the module contain both and it result that password are not updated.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/2d98734ad51c3de557c3a7d1f7166bdd114ceb0f/lib/ansible/modules/cloud/openstack/os_server.py#L362

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
python 2.7.12
```

##### CONFIGURATION

```paste below
Private / Not related
(I do not wish to paste it here)
```

##### OS / ENVIRONMENT

Target : Centos 7.6 18.10 template

##### ADDITIONAL INFORMATION

The correct example to do this should be :
```
# Creates a new instance with provisioning userdata using Cloud-Init
- name: launch a compute instance
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        name: vm1
        state: present
        image: "Ubuntu Server 14.04"
        flavor: "P-1"
        network: "Production"
        userdata: |
          #cloud-config
          chpasswd:
            password: {{ default_password }}
            expire: False
          packages:
            - ansible
          package_upgrade: true
```
or
```
# Creates a new instance with provisioning userdata using Cloud-Init
- name: launch a compute instance
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        name: vm1
        state: present
        image: "Ubuntu Server 14.04"
        flavor: "P-1"
        network: "Production"
        userdata: |
          #cloud-config
          chpasswd:
            list: |
              ubuntu:{{ default_password }}
          packages:
            - ansible
          package_upgrade: true
```
