### ISSUE TITLE
k8s module shows diff changes for metadata added by default when we changed nothing

### ISSUE THREAD

**Issue by mitchellmaler** [ansible/ansible#60510]
##### SUMMARY
Using the k8s module running in --check and --diff modes shows metadata that would be removed which is data automatically added by kubernetes.

```
--- before
+++ after
@@ -1,5 +1 @@
-metadata:
-  creationTimestamp: '2019-05-16T00:49:39Z'
-  resourceVersion: '120846'
-  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/podsecuritypolicy-default
-  uid: 7c5e2d29-7774-11e9-ad63-0050569d5531
+metadata: {}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /workspace/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May  3 2019, 11:24:39) [GCC 8.3.0
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/workspace/ansible.cfg) = ['/workspace/ansible_remote_roles']
DEFAULT_STDOUT_CALLBACK(/workspace/ansible.cfg) = yaml
HOST_KEY_CHECKING(/workspace/ansible.cfg) = False
INVENTORY_ENABLED(/workspace/ansible.cfg) = ['yaml']
LOCALHOST_WARNING(/workspace/ansible.cfg) = False
RETRY_FILES_ENABLED(/workspace/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Kubernetes 1.14.1

##### STEPS TO REPRODUCE

Using the k8s module add kubernetes object. Run ansible again using check mode and it shows a diff of metadata that should be ignored as changing.

```yaml
- name: "default Pod Security Policy on {{ kubernetes_cluster_name }}"
  k8s:
    state: present
    definition: "{{ lookup('file', 'psp-default.yml') }}"
    kubeconfig: "{{ kubernetes_kubeconfig_file_path }}"
    validate_certs: no
```

##### EXPECTED RESULTS

Diff shows nothing changed since we didn't change anything. 

##### ACTUAL RESULTS

Diff shows changes of metadata that is automatically added by kubernetes

```paste below

```
