### ISSUE TITLE
Free strategy + include_task leads to wrong tasks running

### ISSUE THREAD

**Issue by ian-kelling** [ansible/ansible#60512]
##### SUMMARY

The free strategy, include_tasks will skip some hosts,
sometimes run twice on some hosts, sometimes run on a host
despite a when: "'groupx' not in group_names".

##### ANSIBLE VERSION

```paste below
ansible 2.7.4-1ppa~xenial
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/root/ansible-configs/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/root/ansible-configs/ansible.cfg) = 2
COLOR_VERBOSE(/root/ansible-configs/ansible.cfg) = bright blue
DEFAULT_FORKS(/root/ansible-configs/ansible.cfg) = 200
DEFAULT_STDOUT_CALLBACK(/root/ansible-configs/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/root/ansible-configs/ansible.cfg) = False
HOST_KEY_CHECKING(/root/ansible-configs/ansible.cfg) = False
RETRY_FILES_ENABLED(/root/ansible-configs/ansible.cfg) = False
```

##### ISSUE TYPE
- Bug Report

##### OS / ENVIRONMENT

trisquel 8 (derivative of ubuntu 16.04)

##### STEPS TO REPRODUCE

I already spent over a day tracking this down, I don't have time to
make a minimal repro or testing on the latest dev version, maybe sometime in the next few weeks I will, I figured better to report it than not.

```
timeout --foreground 1h ansible-playbook --key-file somekeyfile -i inventory site.yml -v |& tee -a logfile
```

In the main playbook, about line 250, earlier tasks do things like copy files, setup users, apt_repository, which all takes 8 minutes or so:

```
- include_tasks: roles/install.yml
  vars:
    title: "fundamental packages"
    packages: "{{ fundamental_packages }}"
```

roles/install.yml:

```
---
- name: install "{{ packages }}"
  apt:
   name: '{{ packages }}'
   state: present
   install_recommends: no
   update_cache: yes
   autoremove: yes
```

Out of 50 hosts fundamental_packages task should run on, with the free strategy, with somewhat random results, it would run usually on only 44-47 hosts, maybe half the time it would run on 1 host twice. A later include_task sometimes had a when: condition get ignored. All this only happened under the free strategy. The results changed seemingly randomly, it looks like a timing issue so I assume 8 minutes or so of earlier tasks is important for this to reproduce.
