### ISSUE TITLE
fortios_config - Failed while reading configuration backup

### ISSUE THREAD

**Issue by sigquit** [ansible/ansible#60556]
##### SUMMARY

After upgrading to ansible 2.8.3 (from 2.7.9), I get this error: {"msg": "Failed while reading configuration backup"}

I guess after the recent update "https://github.com/ansible/ansible/pull/50801"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

fortios_config
##### ANSIBLE VERSION

```paste below
ansible 2.8.3
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- name: fortios config backup
  gather_facts: no
  hosts: localhost

  tasks:
    - name: fortios config backup
      fortios_config:
        host: x.x.x.x
        username: user
        password: password
        backup: yes
        backup_path: /home/ansible/backup
        backup_filename: x.x.x.x.cfg
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"msg": "Failed while reading configuration backup"}
```

**Comment by mcpaint** [comment]
👍

**Comment by ansibot** [comment]
cc @bjolivot
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bjolivot
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sigquit** [comment]
The backup file was well generated, but TASK result is FAILED

**Comment by argopidi** [comment]
Hi Ansible Experts,
same here.. Can anyone help on this issue

**Comment by sigquit** [comment]
[Temporarily Solved]

lib/ansible/module_utils/network/fortios/fortios.py
- remove 3 lines
```
    ...
    backup_path=dict(type='path'),
    backup_filename=dict(type='str'),
    ...
    ['backup', True, ['backup_path']],
    ...
```
/lib/ansible/modules/network/fortios/fortios_config.py
- original
```
    ...
    argument_spec = dict(
        src=dict(type='str', default=None),
        filter=dict(type='str', default=""),
    )
    ...
    # backup config
    if module.params['backup']:
        backup(module, f.running_config.to_text())
    ...
```
- update
```
    ...
    backup_spec = dict(
        filename=dict(),
        dir_path=dict(type='path')
    )
    argument_spec = dict(
        src=dict(type='str', default=None),
        filter=dict(type='str', default=""),
        backup_options=dict(type='dict', options=backup_spec),
    )
    ...
    # backup config
    if module.params['backup']:
        result['__backup__'] = result['running_config']
    ...
```
and then upate my ansible config
```
  tasks:
    - name: fortios config backup
      fortios_config:
        host: x.x.x.x
        username: user
        password: password
        backup: yes
        backup_options:
          filename: x.x.x.x.cfg
          dir_path: /home/ansible/backup
```
