### ISSUE TITLE
'mysql_user' module is not idempotent on Python 3.7

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#60567]
##### SUMMARY

The `mysql_user` module always reports the "changed" state on hosts with Python 3.7 set as the inrerpreter. The changed message points to https://github.com/ansible/ansible/commit/9c5275092f4759c87d4cd938a73368955934b9b9 commit as the possible culprit; the changed state shows up on Ansible 2.8.0+, but not on Ansible 2.7.0+. The actual functionality (creation of the MySQL user account, setting password, etc.) seems to work fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = None
  configured module search path = ['/home/drybjed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/drybjed/.local/lib/python3.7/site-packages/ansible
  executable location = /home/drybjed/.local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
No changes
```

##### OS / ENVIRONMENT

The Ansible Controller is a Debian Buster (10) host, the working remote host is a Debian Stretch (9) host with Python 2.7 and 3.5 used as the interpreters (no changes). The faulty remote host is a Debian Buster (10) host with Python 3.7 as the interpreter.

##### STEPS TO REPRODUCE

```yaml
---

- hosts: all
  become: True
  tasks:

    - name: Manage MySQL account
      mysql_user:
        name: 'test-user'
        host: 'localhost'
        password: 'test-password'
        state: 'present'

    - name: Manage MySQL account
      mysql_user:
        name: 'test-user'
        host: 'localhost'
        password: 'test-password'
        state: 'present'
      register: output

    - debug: var=output
```

##### EXPECTED RESULTS

```
PLAY [all] ******************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************
ok: [remote]

TASK [Manage MySQL account] *************************************************************************************************************************
ok: [remote]

TASK [Manage MySQL account] *************************************************************************************************************************
ok: [remote]

TASK [debug] ****************************************************************************************************************************************
ok: [remote] => {
    "output": {
        "changed": false,
        "failed": false,
        "msg": "User unchanged",
        "user": "test-user"
    }
}
```

##### ACTUAL RESULTS

```paste below
PLAY [all] ******************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************
ok: [remote]

TASK [Manage MySQL account] *************************************************************************************************************************
changed: [remote]

TASK [Manage MySQL account] *************************************************************************************************************************
changed: [remote]

TASK [debug] ****************************************************************************************************************************************
ok: [remote] => {
    "output": {
        "changed": true,
        "failed": false,
        "msg": "Password updated (new style)",
        "user": "test-user"
    }
}
```
