### ISSUE TITLE
json_query does not work with zipped lists

### ISSUE THREAD

**Issue by Inilien** [ansible/ansible#60583]
##### SUMMARY
json_query fails when a zipped list was given.

##### ISSUE TYPE
I would like to be able to zip 2 lists and provide the result as an input to the `json_query` filter

##### COMPONENT NAME
json_query  
zip

##### ADDITIONAL INFORMATION

Here is an example from my playbook for creating users.  
`vnd_r_users` is a list of dict objects containing key-value data for each user to be created.
```yml
vnd_r_users:
  - name: 'user1'
    password: '<insert password here>'
    salt: '<insert salt here>'
    ssh_keys:
      gitlab:
        host: 'gitlab.com'
        username: 'user1'
  - name: 'user2'
    password: '<insert password here>'
    salt: '<insert salt here>'
    ssh_keys:
      gitlab:
        host: 'local.gitlab.organization_name_here.com'
        username: 'user2'
```  
The first task 'get users gitlab ids' for each user gets their gitlab id from gitlab.com  
The second task zips two lists (the original list of user data and the new list of gitlab ids) and uses information from both to get ssh_keys from gitlab.  

```yml
- name: 'create users'
  hosts: 'servers'
  become: true 
  remote_user: 'deployer'
  vars:
    ansible_become_pass: '{{ vnd_remote_user_password }}'
  tasks:
    - name: 'get users gitlab ids'
      local_action: 
        module: 'uri'
        url: 'https://{{ item.host }}/api/v4/users?username={{ item.username }}'
        return_content: true
      remote_user: '{{ lookup("env","USER") }}'  # run as the user executing playbook on localhost
      become: false
      run_once: true
      loop: '{{ vnd_r_users | json_query("[*].ssh_keys.gitlab.{host: host, username: username}") }}'
      register: 'vnd_s_users_ids'
      
    - name: 'get users ssh_keys from gitlab'
      local_action: 
        module: 'uri'
        url: 'https://{{ item.host }}/api/v4/users/{{ item.user_id }}/keys'
        return_content: true
      remote_user: '{{ lookup("env","USER") }}'  # run as the user executing playbook on localhost
      become: false
      run_once: true
      loop: '{{ vnd_s_users_ids.results | zip(vnd_r_users) | list | json_query("[*].{user_id: [0].json[0].id, host: [1].ssh_keys.gitlab.host}") }}'
      register: 'vnd_s_users_keys'
```
However, the second task fails since `json_query` does not understand lists of tuples (which you get applying list to zipped arrays)  

It would be great if some solution to this was implemented:  
- I have created pull request to [jmespath](https://github.com/jmespath/jmespath.py/pull/180) module in order to work with lists of tuples. But it seems that the module is not developed any more...
  - may be ansible could make its own fork
  - or may be it is possible to revive the repository...
- maybe it is possible to add filter to convert list of tuples to list of lists?  
- maybe there is another solution which I am missing..  

For now I have just forked the jmespath package and fixed the issue of not working with lists of tuples. But I would prefer to install packages from PyPI and not from github repositories.
