### ISSUE TITLE
module azure_rm_virtualmachine can't log in with ad_user and password 

### ISSUE THREAD

**Issue by JunqiZhang0** [ansible/ansible#60597]
##### SUMMARY

module azure_rm_virtualmachine can't log in with ad_user and password 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
2.8.3
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/*username/myWork/ansibleExp/4test/ansible.cfg) = [u'/home/*username/myWork/ansibleExp/4test/inventory']

```

##### OS / ENVIRONMENT

fedora30

##### STEPS TO REPRODUCE

```yaml
---
- name: Create a azure vm
  hosts: localhost
  tasks:
    - name: create a vm
      azure_rm_virtualmachine:
        ad_user: username
        password: 'passwd'
        admin_username: name
        admin_password: passwd
        resource_group: name
        vm_size: Standard_A5
        name: name
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest

```

##### EXPECTED RESULTS

creating the vm

##### ACTUAL RESULTS

msg": "Failed to get credentials. Either pass as parameters, set environment variables, define a profile in ~/.azure/credentials, or log in with Azure CLI (`az login`)."

```paste below

```
