### ISSUE TITLE
win_ping occasionally throws FATAL error 

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#60590]
##### SUMMARY

occasionally we get FATAL error when testing if newly created VM is responding to winrm
"msg": "kerberos: authGSSClientStep() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', -1765328377))",
    "unreachable": true,
    "changed": false
it crashed the play even with ignore_errors set to true 

we have multi domain environment with few global domains where ad replication sometime takes bit longer

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_ping
##### ANSIBLE VERSION

```paste below
2.8.3
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

simple playbook

```yaml
`- name: Check if host is available via WinRM
  win_ping:
  register: result_winrm
  until: result_winrm.unreachable| default ('false') == 'false' or result_winrm.ping | default ('') =='pong'
  retries: 5
  delay: 30
  ignore_errors: yes`
```

##### EXPECTED RESULTS

expected would be to have retries based on until loop till the successful connection

##### ACTUAL RESULTS

```paste below
"msg": "kerberos: authGSSClientStep() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), ('Server not found in Kerberos database', -1765328377))",
    "unreachable": true,
    "changed": false
```
