### ISSUE TITLE
cloudformation fails to remove a CF stack, or doesn't wait for success

### ISSUE THREAD

**Issue by axelabs** [ansible/ansible#60606]
#### SUMMARY
I have a playbook with the following task:
```
    - name: Delete VPC CloudFormation Template
      cloudformation:
        stack_name: "{{ stack_name_vpc }}"
        region: "{{ myregion }}"
        state: absent
```
Upon running the playbook with ansible-playbook 2.8.2, it outputs:
```
TASK [Delete VPC CloudFormation Template] **************************************
task path: .../delete_stack_vpc.yml:27
changed: [us-west-2] => {"changed": true, "events": [], "log": [], "output": "Stack DELETE complete"}
META: ran handlers
META: ran handlers
```
The command exits successfully but the underlying stack does not delete due to a dependency... Example from CF stack details:

```
Status | Status reason
------------------------
DELETE_IN_PROGRESS | User Initiated
CREATE_COMPLETE | Export TEST-VPC cannot be deleted as it is in use by ANOTHER-STACK.
```

I know why this dependency exists in my environment and I know how to clean it up but I do expect the task to not exist successfully in this case.  Can you make it do so?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloudformation

##### ANSIBLE VERSION

```
ansible-2.8.2-1.el7.noarch
```

##### CONFIGURATION

```
n/a
```

##### OS / ENVIRONMENT
Running in centos:7.6 docker container

##### STEPS TO REPRODUCE
Run the stack deletion task when the stack has dependencies.

##### EXPECTED RESULTS
ansible-playbook fails the task and exists with an non-zero code.

##### ACTUAL RESULTS
ansible-playbook exits successfully but stack continues to exist.
