### ISSUE TITLE
azure_rm_deployment doesn't expose full error details

### ISSUE THREAD

**Issue by vikramaditya234** [ansible/ansible#60619]
**ISSUE TYPE**

- Bug Report

**COMPONENT NAME**
azure/azure_rm_deployment

**ANSIBLE VERSION**
```
$ ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

**SUMMARY**
azure_rm_deployment does not expose azure error details on the failure. This is related to the closed issue: https://github.com/ansible/ansible/issues/24084

**STEPS TO REPRODUCE**
Try to create a template with error and try to deploy:

```
- name: Create deployment instance
  azure_rm_deployment:
    state: "present"
    name: "deployment-Virtual-Machine"
    location: "{{ location }}"
    resource_group: "{{ resource_group }}"
    template:
      $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
      contentVersion: "1.0.0.0"
      variables:
        location: "{{ location }}"
        resourceGroup: "{{ resource_group }}"
        environment: "{{ env }}"
        project: "{{ project }}"
        machineName: "{{ project }}-machine"
        diskName: "{{ project }}-disk"
        networkinterfaceName: "{{ project }}-networkinterface"

      resources:
        - type: "Microsoft.Compute/virtualMachines"
          apiVersion: "2019-03-01"
          name: "[variables('machineName')]"
          location: "[variables('location')]"
          dependsOn:
            - "[resourceId('Microsoft.Network/networkInterfaces', variables('networkinterfaceName'))]"
          tags:
            project: "[variables('project')]"
            environment: "[variables('environment')]"
            resource-group: "[variables('resourceGroup')]"
          properties:
            hardwareProfile:
              vmSize: "Standard_B1ms"
            storageProfile:
              imageReference:
                publisher: "OpenLogic"
                offer: "CentOS"
                sku: "7.6"
                version: "latest"
              osDisk:
                osType: "Linux"
                name: "[variables('diskName')]"
                createOption: "FromImage"
                caching: "ReadWrite"
                diskSizeGB: "100"
            osProfile:
              computerName: "[variables('machineName')]"
              adminUsername: "azure-user"
              linuxConfiguration:
                disablePasswordAuthentication: "true"
                ssh:
                  publicKeys:
                    - path: "/home/azure-user/.ssh/authorized_keys"
                      keyData: "---- BEGIN SSH2 PUBLIC KEY ----\nComment: \"rsa-key-20170207\"\nXXXX\n---- END SSH2 PUBLIC KEY ----\n"
                provisionVMAgent: "true"
            networkProfile:
              networkInterfaces:
                - id: "[resourceId('Microsoft.Network/networkInterfaces', variables('networkinterfaceName'))]"```
```
**EXPECTED RESULTS**
Full error details, this is what I get when I do it via portal:
```
{
  "telemetryId": "fa87e8e2-e644-4f3e-8897-e7e7938d0422",
  "bladeInstanceId": "Blade_66bc6c05c9a74520af1a7a5d5f236598_0_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The resource 'Microsoft.Network/networkInterfaces/deploy-networkinterface' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.",
  "additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 0,
        "positionNumber": 0,
        "snippet": ""
      }
    }
  ]
}
```
**ACTUAL RESULTS**
The error message in ansible (even with -vvvv) doesn't include the details of the failure:

```
TASK [createinstance : Create deployment instance] **********************************************************************************************************************
task path: /vagrant/amifactory/roles/createinstance/tasks/main.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453 `" && echo ansible-tmp-1566143742.95-11676842432453="` echo /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_deployment.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-3835gJSljm/tmpHxOFPN TO /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453/AnsiballZ_azure_rm_deployment.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453/ /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453/AnsiballZ_azure_rm_deployment.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453/AnsiballZ_azure_rm_deployment.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1566143742.95-11676842432453/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_azure_rm_deployment_payload_uk0E5A/__main__.py", line 540, in deploy_template
    deploy_parameter)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py", line 279, in create_or_update
    **operation_config
  File "/usr/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py", line 229, in _create_or_update_initial
    raise exp

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed_deployment_operations": [],
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "deployment_mode": "incremental",
            "location": "southafricanorth",
            "name": "deployment-Virtual-Machine",
            "parameters": null,
            "parameters_link": null,
            "password": null,
            "profile": null,
            "resource_group": "sa-beta",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "template": {
                "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "resources": [
                    {
                        "apiVersion": "2019-03-01",
                        "dependsOn": [
                            "[resourceId('Microsoft.Network/networkInterfaces', variables('networkinterfaceName'))]"
                        ],
                        "location": "[variables('location')]",
                        "name": "[variables('machineName')]",
                        "properties": {
                            "hardwareProfile": {
                                "vmSize": "Standard_B1ms"
                            },
                            "networkProfile": {
                                "networkInterfaces": [
                                    {
                                        "id": "[resourceId('Microsoft.Network/networkInterfaces', variables('networkinterfaceName'))]"
                                    }
                                ]
                            },
                            "osProfile": {
                                "adminUsername": "azure-user",
                                "computerName": "[variables('machineName')]",
                                "linuxConfiguration": {
                                    "disablePasswordAuthentication": "true",
                                    "provisionVMAgent": "true",
                                    "ssh": {
                                        "publicKeys": [
                                            {
                                                "keyData": "---- BEGIN SSH2 PUBLIC KEY ----\nComment: \"rsa-key-20170207\"\nXXXX\n---- END SSH2 PUBLIC KEY ----\n",
                                                "path": "/home/azure-user/.ssh/authorized_keys"
                                            }
                                        ]
                                    }
                                }
                            },
                            "storageProfile": {
                                "imageReference": {
                                    "offer": "CentOS",
                                    "publisher": "OpenLogic",
                                    "sku": "7.6",
                                    "version": "latest"
                                },
                                "osDisk": {
                                    "caching": "ReadWrite",
                                    "createOption": "FromImage",
                                    "diskSizeGB": "100",
                                    "name": "[variables('diskName')]",
                                    "osType": "Linux"
                                }
                            }
                        },
                        "tags": {
                            "environment": "[variables('environment')]",
                            "project": "[variables('project')]",
                            "resource-group": "[variables('resourceGroup')]"
                        },
                        "type": "Microsoft.Compute/virtualMachines"
                    }
                ],
                "variables": {
                    "diskName": "deploy-disk",
                    "environment": "beta",
                    "location": "southafricanorth",
                    "machineName": "deploy-machine",
                    "networkinterfaceName": "deploy-networkinterface",
                    "project": "deploy",
                    "resourceGroup": "sa-beta"
                }
            },
            "template_link": null,
            "tenant": null,
            "wait_for_deployment_completion": true,
            "wait_for_deployment_polling_period": 10
        }
    },
    "msg": "Deployment failed with status code: 400 and message: Operation failed with status: 'Bad Request'. Details: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/xxxxx/resourcegroups/sa-beta/providers/Microsoft.Resources/deployments/deployment-Virtual-Machine?api-version=2017-05-10"
}

PLAY RECAP **************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Update 1**
Changed the test case to make it easier to reproduce the issue
