### ISSUE TITLE
new module request: win_optional_feature

### ISSUE THREAD

**Issue by rigarash** [ansible/ansible#60663]
##### SUMMARY
It would be nice to handle optional features of Windows through Ansible.

##### ISSUE TYPE
- Feature Idea
There are {Get, Enable, Disable}-WindowsOptionalFeature cmdlets.
I believe Combining these cmdlets will do the job.

##### COMPONENT NAME
If a new name is needed, something like 'win_optional_feature' will be nice.
If we want to extend the existing feature, we should extend 'win_feature' module.

##### ADDITIONAL INFORMATION
I am considering the following syntax right now, almost the same syntax
as 'win_feature' module.

```yaml
- name: Enable needed windows optional feature
  win_optional_feature:
    name:
      - Containers-DisposableClientVM
      - Microsoft-Windows-Subsystem-Linux
    state: enabled
```
