### ISSUE TITLE
iterateing through inventory

### ISSUE THREAD

**Issue by EarlRamirez** [ansible/ansible#60662]
##### SUMMARY

Looping through an inventory with a key:value pair.

##### ISSUE TYPE
- I believe that this feature is already available in ansible; therefore, this is more of a question.
- I have 2000+ IOS devices in an inventory, I am working on replacing. I have the backups for all devices and will like to use this backup to restore it to the new 2000+ that will replace the existing switches in production.
- I have all hosts in the inventory and all configs in the template directory with the format of <IP_address_of_hosts>.txt

I reviewed the [Loop Docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-together) but I am at a bit of a lost on how well I can utilise a loop to iterate through the inventory and backups in the template to ensure that the config is copied to the correct device

How can I leverage ansible to lookup the inventory and the template to restore the configs using a key:value pair or is there some other recmmended method

##### COMPONENT NAME

ios_config

##### ADDITIONAL INFORMATION

Iterate through two files while using one as the key and the other as the value.

```yaml
---
- name: Restore ISO Backup
  hosts: all
  connection: local

  tasks:
  - name: Iterate through inventory and template
    ios_config:
      backup: no 
      src: "{{ inventory_hostname }}.txt"
```
