### ISSUE TITLE
prompt, answer for eric_eccli

### ISSUE THREAD

**Issue by lucasMoeller** [ansible/ansible#60673]
##### SUMMARY
A prompt argument like in cli_command, prompt, answer 

##### ISSUE TYPE
eric_eccli currently does not support prompts and times out.
Currently it is only possible with cli_command and that has to be modified to work.

It is crucial for doing automated backups of configurations
It is crucial for doing automated upgrades of devices

##### COMPONENT NAME

eric_eccli

##### ANSIBLE VERSION
```
ansible 2.9.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansibleUser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/ansible/repo/devel/ansible/lib/ansible
  executable location = /mnt/c/ansible/repo/devel/ansible/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```
##### ADDITIONAL INFORMATION

The feature should handle prompts like overwriting configurations and other things like upgrading the image of a device.

Prompt and answer should work similar to cli_command prompt

```
- name: save configuration to flash memory
  eric_eccli_command:
    commands: save configuration
    prompt: '(y/n)'
    answer: 'y'

```
