### ISSUE TITLE
[ec2] exact_count=0 launches an instance with matching count_tag

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#6067]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

RHEL-6.4, CentOS-6.4, Ubuntu-12.04
##### Summary:

When using the ec2 `count_tag` parameter, the `exact_count=0` value does not terminate existing instances.  Instead, it appears to create a new instance.
##### Steps To Reproduce:
1. Create the following playbook (note the `FIXME` values)

``` yaml

---
- hosts: localhost
  vars:
    ec2_region: 'us-east-1'
    ec2_instance_type: 'm1.small'
    ec2_security_group: 'FIXME'
    ec2_key_name: 'FIXME'
    ec2_name_prefix: 'ansible-testing'
    ec2_images:
       - name: 'centos-6.4-x86_64'
         user: 'root'
         id: 'ami-eb6b0182'

  tasks:
    - name: delete existing ec2 instance(s)
      ec2:
        region: '{{ ec2_region }}'
        instance_type: '{{ ec2_instance_type }}'
        instance_tags:
            Name: '{{ec2_name_prefix}}-{{item.name}}'
        group: '{{ ec2_security_group }}'
        key_name: '{{ ec2_key_name }}'
        image: '{{ item.id }}'
        exact_count: 0
        count_tag:
            Name: '{{ec2_name_prefix}}-{{item.name}}'
        wait: yes
      with_items: ec2_images
      register: ec2_terminated

    - name: terminated instances
      debug: var=item
      with_items: ec2_terminated.results
      when: ec2_images and ec2_terminated is defined
```
1. Run the following commands

``` bash
$ export ANSIBLE_HOST_KEY_CHECKING=False
$ export AWS_ACCESS_KEY='.........................'
$ export AWS_SECRET_KEY='.........................'
$ ansible-playbook -i localhost, ec2-test.yml 
```
##### Expected Results:

When using `count_tag` and `exact_count=0`, no instances should be running after the module exits.
##### Actual Results:

The `ec2` module creates a new instance when `count_tag` and `exact_count=0` are used.
