### ISSUE TITLE
 Add 'templates_from' option to import_role and include_role

### ISSUE THREAD

**Issue by SamyCoenen** [ansible/ansible#60703]
##### SUMMARY
Add an option similar to 'tasks_from' but for templates for a role named 'templates_from'

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
include_role/import_role

##### ADDITIONAL INFORMATION

Very similar to https://github.com/ansible/ansible/issues/46769#issue-368725898

Before Ansible v2.2 you could include roles and the templates would automatically be loaded from all the loaded roles. Now it only looks in the current role or in 'templates' in the same directory as the playbook.

This would allow for less template duplication between roles.

```yaml
    - name: Import shared templates
      import_role:
        name: templates
        templates_from: ""
```
