### ISSUE TITLE
s3_bucket bucket policy without optional SID causes timeout of ansible action event hough bucket policy is applied

### ISSUE THREAD

**Issue by dan-osms** [ansible/ansible#60706]
##### SUMMARY
Leveraging the s3_bucket policy module, to build a bucket policy without "sid" statements causes Ansible to fail "msg": "Bucket policy failed to apply in the expected time"

Sid statements are optional within building an s3 bucket policy

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /Users/someuser/.ansible.cfg
  configured module search path = ['/Users/someuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below
daniel.ANSIBLE_PIPELINING(/Users/someuser/.ansible.cfg) = True
COLOR_DEBUG(/Users/someuser/.ansible.cfg) = dark gray
DEFAULT_HOST_LIST(/Users/someuser/.ansible.cfg) = ['/etc/ansible/local']
DEPRECATION_WARNINGS(/Users/someuser/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/someuser/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS 10.14.6

##### STEPS TO REPRODUCE

Build a bucket policy with with no sid statements.

```yaml
Proprietary cannot post.
```

##### EXPECTED RESULTS

That ansible would move onto the next step within the task.

##### ACTUAL RESULTS

Ansible writes the policy but gets hung up errors out stating that bucket policy was not applied. When indeed it was, but didn't finish the task.

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/amazon/s3_bucket.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/s3_bucket.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@shdobxr, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jillr @s-hertel @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tremble** [comment]
close_me

It looks like AWS no longer magically adds "Sid" in the background.

tested using

```
- hosts: localhost
  collections:
  - amazon.aws
  - community.ws
  tasks:
    - name: Test Bucket
      s3_bucket:
        name: 'mchappel-gclbgasn'
        state: present
        policy:
          Statement:
          - Action:
            - "s3:PutObject"
            Effect: "Allow"
            Resource: "arn:aws:s3:::mchappel-XXXXXXXX/123/*"
            Principal:
              AWS:
              - 'XXXXXXXXXXXX'
```
