### ISSUE TITLE
Rolling ASG spins up the new instances but doesn't terminate the old ones

### ISSUE THREAD

**Issue by trevor5249** [ansible/ansible#60714]
##### SUMMARY

ec2_asg replace_all_instances creates the new ec2 servers (new launch config) but doesn't remove the old servers (old launch config). The servers are all healthy as well. The playbook command eventually times out and now has the new servers and old servers in the same auto scaling group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_asg
  replace_all_instances: yes
 
##### ANSIBLE VERSION

```paste below
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Mar 26 2019, 10:00:46) [GCC 4.8.4]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = [u'/home/ubuntu/pss-ansible/inventory-win/ec2.py']

```

##### OS / ENVIRONMENT

Windows Server 2012

##### STEPS TO REPRODUCE

```yaml
 - name: create asg that replaces old instances (terminates) with new ones   
     ec2_asg:
      name: "{{ ASG_name_ansible }}"
      launch_config_name: "{{ LC_name }}"
      health_check_period: 60
      health_check_type: ELB
      replace_all_instances: yes
      target_group_arns: "{{ tg_arns }}"
      min_size: "{{ min_size }}"
      max_size: "{{ max_size }}"
      desired_capacity: "{{ desired }}"
      replace_batch_size: "{{ batch_size }}"
      region: "{{ target_aws_region }}"
      availability_zones: "{{ asg_avail_zone }}"
      vpc_zone_identifier: "{{ target_aws_lb_subnets }}"
      wait_timeout: 600
```

##### EXPECTED RESULTS

I expect the new instances to spin up. Once the new instances are healthy, I expect the old instances to be terminated.

##### ACTUAL RESULTS

The new instances spin up. They are marked as healthy. However, the old instances do not self terminate and just stall there until the playbook command times out.

```paste below

```
