### ISSUE TITLE
nxos_vlan failure when configuring switch

### ISSUE THREAD

**Issue by gamename** [ansible/ansible#60729]
##### SUMMARY
There are 2 environments, prod and dev.  The dev environment has one host for ansible and two 9000v switches.  The prod environment has another host also with 2 Nexus 9000 switches. 

I have a very simple playbook to create vlans.  It works correctly in the dev environment, but not in the prod environment

Here are some datapoints:
- The prod and dev 9k switch versions are _exactly_ the same 
- The prod and dev versions of ansible are the same *except* the prod version uses python 2.7.  The dev ansible uses python 3.7.4
- The prod and dev versions of `nxos_vlan.py` in the `modules` directory are exactly the same.  I did an mdsum check on both and the values match.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_vlan

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /home/automation/dtcc_ansible/ansible.cfg
  configured module search path = [u'/home/automation/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

```paste below
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = True
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/automation/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(/home/automation/dtcc_ansible/ansible.cfg) = /home/automation/.vault_password_file
HOST_KEY_CHECKING(/home/automation/dtcc_ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/automation/dtcc_ansible/ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT
```
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2019, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.35
  NXOS: version 7.0(3)I7(6)
  BIOS compile time:  08/31/2018
  NXOS image file is: bootflash:///nxos.7.0.3.I7.6.bin
  NXOS compile time:  3/5/2019 13:00:00 [03/05/2019 22:04:55]


Hardware
  cisco Nexus9000 C9508 (8 Slot) Chassis ("Supervisor Module")
  Intel(R) Xeon(R) CPU E5-2420 v2 @ 2.20GHz with 24632988 kB of memory.
  Processor Board ID SAL1923GFZV

  Device name: JER-LAB-N95KSW1
  bootflash:  230644056 kB
Kernel uptime is 29 day(s), 0 hour(s), 1 minute(s), 37 second(s)

Last reset at 914945 usecs after Fri Jul 19 01:21:27 2019
  Reason: Reset Requested by CLI command reload
  System version: 7.0(3)I7(6)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):
        nxos.CSCvo86286-n9k_ALL-1.0.0-7.0.3.I7.6.lib32_n9000
```

##### STEPS TO REPRODUCE
Run the playbook (below) and pass in the configuration file (also) below
```bash
ansible-playbook -i <hosts> ./create_vlan.yml --extra-vars='@vlan_403.yml'
```

This is the playbook
```yaml
---
- name: vlan testing
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: no

  tasks:

    - name: Build VLAN
      nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        name: "{{ vlan_name }}"
        state: present
        interfaces: "{{ ports[inventory_hostname] }}"
      when: inventory_hostname in ports
```

This is the vlan definition file:
```yaml
---
vlan_number: 403
vlan_name: tennis_403
ports:
  n95ksw1:
    - Eth1/30
    - Eth1/31
    - Eth1/33
  n95ksw2:
    - Eth2/10
```

##### EXPECTED RESULTS
The expected result is to create a vlan with a number of 403 and a name of `tennis_403`.  

##### ACTUAL RESULTS
The vlan appears to create correctly, but we take a fatal error as well:
```
2019-08-17 08:51:12,116 p=24794 u=automation |  fatal: [n95ksw2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "switchport\r\r\n                                 ^\r\n% Invalid command at '^' marker.\r\n\rJER-LAB-95KSW2(config-if)# "}
```

##### DEBUG 
See https://gist.github.com/gamename/c54095603bd79d49107fb6b2e84b8381

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/nxos/_nxos_vlan.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/_nxos_vlan.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrisvanheuveln @jedelman8 @mikewiebe @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@gamename, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrisvanheuveln @jedelman8 @mikewiebe @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gamename** [comment]
This has been flagged as deprecated. What aspect of this is deprecated?

**Comment by gamename** [comment]
I found a workaround for this
```yaml
      - name: Ensure ports are configured for layer 2
        nxos_interface:
          name: "{{item}}"
          mode: layer2
        loop: "{{ ports[inventory_hostname] | flatten(levels=1) }}"

      - name: Ensure ports are in an unconfigured state
        nxos_l2_interface:
          name: "{{item}}"
          state: unconfigured
        loop: "{{ ports[inventory_hostname] | flatten(levels=1) }}"
```

This leads me to believe it isn't due to python version differences, but rather to some configuration difference in the production interface definition.
