### ISSUE TITLE
AWS sts_assume_role - PolicyArns parameter

### ISSUE THREAD

**Issue by mathieucoavoux** [ansible/ansible#60734]
##### SUMMARY

Add the parameter `PolicyArns` to the module `sts_assume_role`
This is supported by `boto3` latest version
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

sts_assume_role
##### ADDITIONAL INFORMATION

```yaml
sts_assume_role:
  role_arn: "arn:aws:iam::123456789012:role/someRole"
  role_session_name: "someRoleSession"
  policy_arns:
    - arn: "arn:aws:iam::123456789012:role/policyS3ReadOnly"
```
