### ISSUE TITLE
any_errors_fatal does not work 

### ISSUE THREAD

**Issue by gamename** [ansible/ansible#60731]
##### SUMMARY
Even in the simplest playbook, the `any_errors_fatal: true` construct does not work 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
any_errors_fatal

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = None
  configured module search path = ['/Users/tennis.smith/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.3/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]

```

##### CONFIGURATION

```paste below
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT
Any

##### STEPS TO REPRODUCE

```
ansible-playbook -i <hosts> ./create_vlan.yml --extra-vars '@vlan_103.yml' 
```

VLAN config file:
```yaml
---
vlan_number: 103
vlan_name: test_103
ports:
  n9kv1:
    - Ethernet1/88
    - Ethernet1/89
    - Ethernet1/90
  n9kv2:
    - Ethernet1/99
```

Playbook:
```yaml
- name: vlan testing
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: no

  tasks:
    - name: Build VLAN
      nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        name: "{{ vlan_name }}"
        state: present
        interfaces: "{{ ports[inventory_hostname] }}"
      when: inventory_hostname in ports
```

##### EXPECTED RESULTS
The playbook should fail on the first error found.

##### ACTUAL RESULTS
There are 2 errors in the output and the playbook continues to the end.  It should have aborted on the first error.  The error itself was reported in a separate issue (#60729). 

```paste below
PLAY [vlan testing] ******************************************************************************************************************
 
TASK [Build VLAN] ********************************************************************************************************************
skipping: [n7ksw1]
skipping: [n7ksw2]
fatal: [n95ksw2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "switchport\r\r\n                                 ^\r\n% Invalid command at '^' marker.\r\n\rJER-LAB-95KSW2(config-if)# "}
fatal: [n95ksw1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "switchport\r\r\n                                  ^\r\n% Invalid command at '^' marker.\r\n\rJER-LAB-N95KSW1(config-if)# "}
 
NO MORE HOSTS LEFT *******************************************************************************************************************
 
PLAY RECAP ***************************************************************************************************************************
n7ksw1                     : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
n7ksw2                     : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
n95ksw1                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
n95ksw2                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
