### ISSUE TITLE
lineinfile insertafter is not adding directly after line correctly.

### ISSUE THREAD

**Issue by queglay** [ansible/ansible#60738]
##### SUMMARY
lineinfile is ignoring insertafter

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```paste below
2.8.4
```

##### CONFIGURATION

```paste below
vagrant@openfirehawkserverdev:/vagrant$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/vagrant/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/vagrant/ansible.cfg) = 10
DEFAULT_CALLBACK_WHITELIST(/vagrant/ansible.cfg) = [u'profile_tasks']
DEFAULT_GATHER_SUBSET(/vagrant/ansible.cfg) = [u'!hardware']
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/vagrant/ansible/hosts']
DEFAULT_LOG_PATH(/vagrant/ansible.cfg) = /vagrant/tmp/ansible_log
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
vagrant@openfirehawkserverdev:/vagrant$ 

```

##### OS / ENVIRONMENT
vagrant, ubuntu, bento

##### STEPS TO REPRODUCE

this example playbook part here should append a host after a group in the hosts file, but the insert after command is ignored.  this is the section that appears to not work correctly-
```
    - name: group add host- update host or add if not exist
      lineinfile:
        state: present
        path: "{{ hosts_file }}"
        line: "{{ host_name }} ansible_host={{ host_ip }}"
        backup: true
        owner: vagrant
        regexp: ".*{{ host_name }} ansible_host=.*"
        insertafter: "[{{ group_name }}]"
        firstmatch: true
        create: true
      when: group_name != ''
      become: yes
```

Here is the rest of the playbook, to ensure groups and hosts without groups are added as well.

```yaml
- hosts: ansible_control
  remote_user: vagrant
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true
  
  vars:
    hosts_file: ''
    group_name: ''
  
  tasks:
    - name: update ansible_control or add if not exist
      lineinfile:
        state: present
        path: "{{ hosts_file }}"
        line: "ansible_control ansible_connection=local"
        backup: true
        owner: vagrant
        regexp: ".*ansible_control ansible_connection=.*"
      become: yes

    - name: update group or add if not exist
      lineinfile:
        state: present
        path: "{{ hosts_file }}"
        line: "[{{ group_name }}]\n"
        backup: true
        owner: vagrant
        #regexp: ".*\n[{{ group_name }}].*"
        regexp: ".{{ group_name }}."
      when: group_name != ''
      become: yes

    - name: ensure a new line exists at end of file always
      lineinfile:
        state: present
        path: "{{ hosts_file }}"
        line: ' '
        regexp: ' '
        backup: true
        owner: vagrant
        insertafter: EOF
      become: yes

    - name: group add host- update host or add if not exist
      lineinfile:
        state: present
        path: "{{ hosts_file }}"
        line: "{{ host_name }} ansible_host={{ host_ip }}"
        backup: true
        owner: vagrant
        regexp: ".*{{ host_name }} ansible_host=.*"
        insertafter: "[{{ group_name }}]"
        firstmatch: true
        create: true
      when: group_name != ''
      become: yes

    - name: update host or add if not exist
      lineinfile:
        state: present
        path: "{{ hosts_file }}"
        line: "{{ host_name }} ansible_host={{ host_ip }}"
        backup: true
        owner: vagrant
        regexp: ".*{{ host_name }} ansible_host=.*"
        firstmatch: true
        insertafter: ' '
      when: group_name == ''
      become: yes
```

##### EXPECTED RESULTS

running this-
```
ansible-playbook -i hosts ansible/hosts-add.yaml -v --extra-vars "host_name=test10 host_ip=195.329 group_name=group4"
```
should append the host after [group4], but instead, it erases the current last line after [group2], and appends after group2.

##### ACTUAL RESULTS

with this input-
```
#hosts
ansible_control ansible_connection=local
openvpnip ansible_host=13.238.136.146
[role_local_workstation]
workstation.firehawkvfx.com ansible_host=192.168.92.12
[role_softnas]
softnas0 ansible_host=195.326

test3 ansible_host=195.329
test2 ansible_host=195.329
[group4]
test4 ansible_host=195.329
test5 ansible_host=195.329
 
test7 ansible_host=195.329
test8 ansible_host=195.329
[group2]
test9 ansible_host=195.329
```

running this -
ansible-playbook -i hosts ansible/hosts-add.yaml -v --extra-vars "host_name=test10 host_ip=195.329 group_name=group4"

will produce this-

```paste below
#hosts
ansible_control ansible_connection=local
[role_local_workstation]
workstation.firehawkvfx.com ansible_host=192.168.92.12
[role_softnas]
softnas0 ansible_host=195.326

test3 ansible_host=195.329
test2 ansible_host=195.329
[group4]
test4 ansible_host=195.329
test5 ansible_host=195.329
 
test7 ansible_host=195.329
test8 ansible_host=195.329
[group2]
test10 ansible_host=195.329
```
