### ISSUE TITLE
Task fails with loop_control.label and when condition with an undefined variable

### ISSUE THREAD

**Issue by mchlrv** [ansible/ansible#60733]
##### SUMMARY
Same  as #48045

The task fails with loop_control.label and when condition defined if the variable in the when condition isn't defined.

The task will be skipped if I comment out loop_control.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
loop_control
when

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS 7.5

##### STEPS TO REPRODUCE

1. Create a task with loop_control and when condition
2. Don't define the variable

```
- name: Firewalld add interfaces to zones
  firewalld:
    zone: "{{ item.zone }}"
    interface: "{{ item.interface }}"
    state: "{{ item.state }}"
    permanent: "{{ item.permanent }}"
    immediate: "{{ item.immediate }}"
  loop: "{{ firewall | flatten(1) }}"
  loop_control:
   label: "Added {{ item.interface }} to {{ item.zone }}"
  when:
    - item.interface is defined
```

##### EXPECTED RESULTS
Task will be skipped.

##### ACTUAL RESULTS
```
"msg": "Failed to template loop_control.label: 'dict object' has no attribute 'interface'", "skip_reason": "Conditional result was False"}
```
