### ISSUE TITLE
Problem with gluster volume module

### ISSUE THREAD

**Issue by cyprix** [ansible/ansible#60751]
##### SUMMARY
Playbook fails, but volume created. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gluster_volume

##### ANSIBLE VERSION
```
2.7.5
```

##### CONFIGURATION

```paste below
DEFAULT_FACT_PATH(/etc/ansible/ansible.cfg) = /home/cyprix/Work/ansible/facts
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/cyprix/Work/ansible/inventory']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/home/cyprix/Work/ansible/roles']
```

##### OS / ENVIRONMENT

Host OS: Ubuntu 18.04.3 LTS x64
Target OS: RHEL 7.7 x64
GlusterFS: 4.1.9-1.el7.x86_64

##### STEPS TO REPRODUCE

```yaml
gluster_cluster_resources: 
  - resource : "IMAGES"
    block_device : "vg0/lv_images"
    mount_dir    : "images"
    lv_name      : "images"

- name: create GlusterFS Volume
  gluster_volume:
    state: present
    name: "{{ item.resource }}"
    bricks: "{{ gluster_cluster_volume_base_path }}/{{ item.lv_name }}/"
    replicas: 2
    cluster: "{{ gluster_servers_hosts_ips }}"
    host: "{{ inventory_hostname }}"
    force: true
  with_items: "{{ gluster_cluster_resources }}"
  delegate_to: "{{ groups['glusterfs-servers'][0] }}"
  run_once: true

```

##### EXPECTED RESULTS

I'm expecting that gluster volume is created, and the playbook will not fail.

##### ACTUAL RESULTS

As I see, gluster volume IMAGES created, but playbook failed.

```paste below
task path: /home/cyprix/ansible/roles/glusterfs-server/tasks/setup-volumes.yml:22
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/storage/glusterfs/gluster_volume.py
<172.16.105.140> ESTABLISH SSH CONNECTION FOR USER: root
<172.16.105.140> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=44774 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/cyprix/.ansible/cp/6b0f9421e4 172.16.105.140 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<172.16.105.140> (1, '\n{"msg": "error running gluster (/usr/sbin/gluster --mode=script volume add-brick IMAGES replica 2 172.16.105.140:/gluster/images/ 172.16.105.141:/gluster/images/ force) command (rc=1): volume add-brick: failed: Brick: 172.16.105.140:/gluster/images not available. Brick may be containing or be contained by an existing brick.\\n", "failed": true, "exception": "None\\n", "invocation": {"module_args": {"arbiters": null, "force": true, "name": "IMAGES", "replicas": 2, "bricks": "/gluster/images/", "disperses": null, "quota": null, "stripes": null, "cluster": ["172.16.105.140", "172.16.105.141"], "host": "gl_server01.local", "state": "present", "start_on_create": true, "redundancies": null, "directory": null, "rebalance": false, "options": {}, "transport": "tcp"}}}\n', '')
The full traceback is:
None

fatal: [gl_server01.local -> 172.16.105.140]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "arbiters": null, 
            "bricks": "/gluster/images/", 
            "cluster": [
                "172.16.105.140", 
                "172.16.105.141"
            ], 
            "directory": null, 
            "disperses": null, 
            "force": true, 
            "host": "gl_server01.local", 
            "name": "IMAGES", 
            "options": {}, 
            "quota": null, 
            "rebalance": false, 
            "redundancies": null, 
            "replicas": 2, 
            "start_on_create": true, 
            "state": "present", 
            "stripes": null, 
            "transport": "tcp"
        }
    }, 
    "msg": "error running gluster (/usr/sbin/gluster --mode=script volume add-brick IMAGES replica 2 172.16.105.140:/gluster/images/ 172.16.105.141:/gluster/images/ force) command (rc=1): volume add-brick: failed: Brick: 172.16.105.140:/gluster/images not available. Brick may be containing or be contained by an existing brick.\n"
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/storage/glusterfs/gluster_volume.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/storage/glusterfs/gluster_volume.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @devyanikota @rosmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @devyanikota @rosmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rosmo** [comment]
@cyprix This doesn't look like problem with the module. The issue is with your brick: `volume add-brick: failed: Brick: 172.16.105.140:/gluster/images not available. Brick may be containing or be contained by an existing brick.`

**Comment by rosmo** [comment]
notabug

**Comment by cyprix** [comment]
@rosmo I think that it is a bug in the Ansible.
All volumes not created before. Gluster peer status without any neighbor. When I'm running the playbook, the volume created, but playbook failed with this error.

**Comment by iserocco** [comment]
If try example 
```yaml
---
- name: example
  hosts: localhost
  gather_facts: False
  vars:
    gluster_cluster_resources:
      - resource : "gv0"
        mount_dir    : "/data/gluster"
        lv_name      : "gv0"
    gluster_servers_hosts_ips:
      - gluster1.local
      - gluster2.local
    inventory_hostname:
      - gluster1.local
      - gluster2.local

  tasks:
    - name: create GlusterFS Volume
      gluster_volume:
        state: present
        name: "{{ item.resource }}"
        bricks: "{{ item.mount_dir }}/{{ item.lv_name }}/"
        replicas: 2
        cluster: "{{ gluster_servers_hosts_ips }}"
        host: "{{ inventory_hostname }}"
        force: true
      with_items: "{{ gluster_cluster_resources }}"
      run_once: true
```
We will see calls run_gluster
```
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'peer', 'status']
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'volume', 'info']
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'peer', 'probe', 'gluster2.local']
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'volume', 'create', 'gv0', 'replica', '2', 'transport', 'tcp', 'gluster1.local:/data/gluster/gv0/', 'gluster2.local:/data/gluster/gv0/', 'force']
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'volume', 'info']
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'volume', 'start', 'gv0']
2019-08-19 INFO: __main__.run_gluster: run_gluster: args=['/usr/sbin/gluster', '--mode=script', 'volume', 'add-brick', 'gv0', 'replica', '2', 'gluster1.local:/data/gluster/gv0/', 'gluster2.local:/data/gluster/gv0/', 'force']
```
Create volume
```
/usr/sbin/gluster --mode=script volume create gv0 replica 2 transport tcp gluster1.local:/data/gluster/gv0/ gluster2.local:/data/gluster/gv0/ force 
```
After try add **exist brick**
```
/usr/sbin/gluster --mode=script volume add-brick gv0 replica 2 gluster1.local:/data/gluster/gv0/ gluster2.local:/data/gluster/gv0/ force
```
It's not work for glusterfs 4.1.9
