### ISSUE TITLE
copy module contents parameter does not allow for newline chars

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#6077]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.5 (devel ee6a0359f5) last updated 2014/02/19 16:45:25 (GMT -400)
```
##### Environment:

Control host -- ubuntu 12.04
Managed host -- ubuntu 12.04
##### Summary:

When creating a file via the copy module and the content= parameter, newline characters are not evaluated and will show up as ascii in the resulting file. 
##### Steps To Reproduce:

```
- name: make a new file
  copy: dest=/tmp/foo.txt mode=0644 content="hello world\n"
```
##### Expected Results:

```
root@u1204:# cat ~/ansible_testing/foo.txt
hello world
root@u1204:#
```
##### Actual Results:

```
root@u1204:# cat ~/ansible_testing/foo.txt
hello world\nroot@u1204:#
```

**Comment by techtonik** [comment]
Pretty annoying.

**Comment by techtonik** [comment]
Is it possible to use Jinja2 magic to escape this behavior somehow?

**Comment by techtonik** [comment]
An ugly workaround is to include `{{'\n'}}` at the beginning of each line.

**Comment by jctanner** [comment]
@techtonik should be fixed for you with 4e8ed92

**Comment by techtonik** [comment]
Cool. Will it be in 1.5.1?

**Comment by manuelmeurer** [comment]
I had to use two backslashes to get this working:

``` yaml
- name: set hostname
  sudo: yes
  copy:
    content: "{{ inventory_hostname }}\\n"
    dest: /etc/hostname
```

My Ansible version is 1.6.6

**Comment by trkoch** [comment]
I appears the behavior has changed. In Ansible 2.0 I have to use one backslash and double quotes.

Picking up the previous examples it should now be written as:

```
- name: set hostname
  become: yes
  copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/hostname
```

I don't know where this is documented. If it is, let's check what syntax is documented.

**Comment by nhooey** [comment]
@jctanner Is it intended that you need to add `\\n` in Ansible version < 2, and `\n` in Ansible version >= 2 as @trkoch mentioned?

**Comment by nhooey** [comment]
Nevermind.

In Ansible 1.9.4, a single backslash works:

``` yaml
- name: set hostname
  become: yes
  copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/hostname
```

So this seems to have been fixed after Ansible 1.6.6, but before Ansible 2.0 as well.
