### ISSUE TITLE
stat module returns mode 420 for a file that is 0644 

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#6080]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.5 (devel ee6a0359f5) last updated 2014/02/19 16:45:25 (GMT -400)
```
##### Environment:

ubuntu 12.04 on both hosts
##### Summary:

A file with 0644 permissions is reported as 420 by the stat module.
##### Steps To Reproduce:

```
- name: make a new file
  copy: dest=/tmp/foo.txt mode=0644 content="hello world"

- name: check stat of file
  stat: path=/tmp/foo.txt
  register: stat_result

- assert:
    that:
        - "stat_result.stat.mode == 644"
```
##### Expected Results:

Assert task does not fail.
##### Actual Results:

Assert task fails.
