### ISSUE TITLE
ec2_vol: One or more undefined variables: 'item' is undefined

### ISSUE THREAD

**Issue by thinrhino** [ansible/ansible#6087]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

OS X 10.8.5
##### Summary:

My ansible script to launch a ec2 volume fails with the error:
`fatal: [localhost] => One or more undefined variables: 'item' is undefined`

``` YAML
- name: Add EBS disks
  local_action:
    module: ec2_vol
    ec2_secret_key: "{{ ec2_secret_key }}"
    ec2_access_key: "{{ ec2_access_key }}"
    instance: "{{ item.id }}"
    volume_size: "{{ ebs_disk_size }}"
    device_name: sdh
    with_items: ec2.instances
    register: ec2_vol
```

I have not been able to figure out the issue. The current code example in the repo is the same!

**Comment by mpdehaan** [comment]
So you haven't defined "item" anywhere, so this isn't a bug.

Please stop by the mailing list and we can help you with usage questions.

**Comment by Anislav** [comment]
I am experiencing a similar if not the same problem when using Ansible 1.5 on OS X 10.9.2.
I have a few variables in group_vars/all.yaml and I have one playbook that works like a charm. I created another one that is responsible for the provisioning of some EC2 instances. I would like to execute it locally and that is why it looks like:

```
---
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - worker-instance
```

When I run it I get the same error:

```
fatal: [localhost] => One or more undefined variables:
```

It works if I copy group_vars/all.yaml into host_vars/localhost.yaml but I do not want to manage the variables in two places. Is this an issue or I got it wrong?
