### ISSUE TITLE
VMware: Add httpapi VMware REST VmwareRestModule

### ISSUE THREAD

**Issue by n3pjk** [ansible/ansible#60913]
##### SUMMARY
Implementing httpapi plugin-based REST modules for VMware.  Laying out initial directory structure and VmwareRestModule extended from AnsibleModule to support the connector and handle communications.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- VmwareRestModule.py
- vmware_appliance_access_info.py
- vmware_appliance_health_info.py
- vmware_cis_category_info.py
- vmware_core_info.py

##### ADDITIONAL INFORMATION
The AnsibleModule class was extended to create the VmwareRestModule class that implements comms with the httpapi plugin. It also provides debugging output, url and filtering generation by object, dynamic handling of HTTP return codes that can be tailored to each module's needs, and support for multiple VMware REST APIs including, but not limited to appliance, cis, content, vapi, vcenter, and vrops.

Using the 'appliance' API:
```yaml
- hosts: all
  connection: httpapi
  gather_facts: false
  vars:
    ansible_network_os: vmware
    ansible_host: vcenter.my.domain
    ansible_user: administrator@vsphere.local
    ansible_httpapi_password: "SomePassword"
    ansbile_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: false
  tasks:

  - name: Get all access modes information
    vmware_appliance_access_info:

  - name: Get ssh access mode information
    vmware_appliance_access_info:
      access_mode: ssh
```
Using the 'vcenter' API:
```yaml
- hosts: all
  connection: httpapi
  gather_facts: false
  vars:
    ansible_network_os: vmware
    ansible_host: vcenter.my.domain
    ansible_user: some.user
    ansible_httpapi_password: "SomePassword"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: false
  tasks:

  - name: get vm information
    vmware_core_info:
      object_type: vm
      filters:
        - names: "some_vm"
```
