### ISSUE TITLE
iosxr_config pushes the same configuration to all routers

### ISSUE THREAD

**Issue by kevintieman** [ansible/ansible#60934]
##### SUMMARY
When using the template function of Ansible to generate unique configurations iosxr_config pushes the configuration of the first iosxr device it touches to all devices.

Something very strange is happening, because when I use napalm sourcing the same config files it works without any issues.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iosxr_config

##### ANSIBLE VERSION
```paste below
kevin@ansible:~$ ansible --version
ansible 2.8.4
  config file = /home/kevin/.ansible.cfg
  configured module search path = [u'/home/kevin/.local/lib/python2.7/site-packages/napalm_ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION
```paste below
DEFAULT_ACTION_PLUGIN_PATH(/home/kevin/.ansible.cfg) = [u'/home/kevin/.local/lib/python2.7/site-packages/napalm_ansible/plugins/action']
DEFAULT_FORKS(/home/kevin/.ansible.cfg) = 60
DEFAULT_GATHERING(/home/kevin/.ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/kevin/.ansible.cfg) = [u'/home/kevin/gtn/inventory']
DEFAULT_INTERNAL_POLL_INTERVAL(/home/kevin/.ansible.cfg) = 0.001
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/kevin/.ansible.cfg) = True
DEFAULT_MODULE_PATH(/home/kevin/.ansible.cfg) = [u'/home/kevin/.local/lib/python2.7/site-packages/napalm_ansible/modules']
DEFAULT_STDOUT_CALLBACK(/home/kevin/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/kevin/.ansible.cfg) = 5
DEFAULT_TRANSPORT(/home/kevin/.ansible.cfg) = local
HOST_KEY_CHECKING(/home/kevin/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/kevin/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
Ubuntu 18.04
IOXR 6.1.2

##### STEPS TO REPRODUCE
```yaml
---
# Generate config per host

- name: Create config directory {{ inventory_hostname }}
  local_action: file path={{config_output_dir}} state=directory
  run_once: false
  check_mode: no
  changed_when: no
  tags: [createfs, template]
  
- name: generate configs based on template
  template: src=mpls_{{ ansible_network_os }}.j2 dest={{config_output_dir}}/{{ inventory_hostname }}.confg

---
- name: load a config from disk and replace the current config
  iosxr_config:
    src: "./CFGS/{{ inventory_hostname }}.confg"
    replace: config

```

##### EXPECTED RESULTS
Ansible pushes the unique configuration to each host and all routers forward packets happily ever after.

##### ACTUAL RESULTS
Ansible actually pushes the same configuration to each host and all packets get dropped creating a huge mess in the datacenter.

I snipped the config from each host except for the hostname to show to uniqueness of the config.

```paste below
https://pastebin.com/raw/Z9bmpFaC
```
