### ISSUE TITLE
ipa_user: It is not possible to create user if group with the same name exists

### ISSUE THREAD

**Issue by aniro** [ansible/ansible#60959]
##### SUMMARY
It is impossible to create user in FreeIPA if group with the same name already exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipa_user

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /mnt/c/Users/user/_work/_repos/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### CONFIGURATION

```paste below
DEFAULT_FORCE_HANDLERS(/mnt/c/Users/user/_work/_repos/ansible/ansible.cfg) = True
DEFAULT_MANAGED_STR(/mnt/c/Users/user/_work/_repos/ansible/ansible.cfg) =
This file is managed by ansible.
Don't make changes here - they will be overwritten.
DEFAULT_PRIVATE_KEY_FILE(/mnt/c/Users/user/_work/_repos/ansible/ansible.cfg) = /home/user/.ssh/ansible_id_rsa
DEFAULT_REMOTE_USER(/mnt/c/Users/user/_work/_repos/ansible/ansible.cfg) = ansible
HOST_KEY_CHECKING(/mnt/c/Users/user/_work/_repos/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
target_os: rhel7

##### STEPS TO REPRODUCE

```yaml
- name: test
  hosts: ipaservers[0]
  tasks:
    - ipa_group:
        ipa_pass: "{{ ipaadmin_password }}"
        ipa_user: admin
        name: test
        gidnumber: 330000
        user: []
        state: present
    - ipa_user:
        ipa_pass: "{{ ipaadmin_password }}"
        ipa_user: admin
        givenname: "{{ item.uid }}"
        sn: "{{ item.uid }}"
        uid: "{{ item.uid }}"
        uidnumber: "{{ item.uidnumber }}"
        gidnumber: "{{ item.gidnumber }}"
        state: "{{ item.state | default(state)}}"
      loop:
        - { uid: test, uidnumber: 330000, gidnumber: 330000 }
        - { uid: test2, uidnumber: 330001, gidnumber: 330000 }
```

##### EXPECTED RESULTS

Both users `test` and `test2` are created sharing the same group.

##### ACTUAL RESULTS

Even if private user groups are disabled globally on IPA server (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html-single/identity_management_guide/index#disabling-managed-entries-globally):
```
ipa-managed-entries -e "UPG Definition" status
Plugin Disabled
```
REST API seem to be doing some checks before user creation and fails if group with the same name already exists.

We could pass explicit parameter `noprivate` to user_add api call which helps to workaround the issue. But it is not supported by `ipa_user` module.

```paste below
failed: [qwe] (item={'uid': 'test', 'uidnumber': 330000}) => {"ansible_loop_var": "item", "changed": false, "item": {"uid": "test", "uidnumber": 330000}, "msg": "response user_add: Unable to create private group. A group 'test' already exists."}
changed: [qwe] => (item={'uid': 'test2', 'uidnumber': 330001, 'gidnumber': 330000}) => {"ansible_loop_var": "item", "changed": true, "item": {"gidnumber": 330000, "uid": "test2", "uidnumber": 330001}, "user": {"cn": ["test2 test2"], "displayname": ["test2 test2"], "dn": "uid=test2,cn=users,cn=accounts,dc=qwe,dc=qwe", "gecos": ["test2 test2"], "gidnumber": ["330000"], "givenname": ["test2"], "has_keytab": false, "has_password": false, "homedirectory": ["/home/test2"], "initials": ["tt"], "ipantsecurityidentifier": ["S-1-5-21-1847660308-3156656839-2481403808-31001"], "ipauniqueid": ["78629816-c363-11e9-becd-00505681bf8d"], "krbcanonicalname": ["test2@REALM"], "krbprincipalname": ["test2@REALM"], "loginshell": ["/bin/sh"], "mail": ["test2@realm"], "memberof_group": ["ipausers"], "nsaccountlock": ["FALSE"], "objectclass": ["top", "person", "organizationalperson", "inetorgperson", "inetuser", "posixaccount", "krbprincipalaux", "krbticketpolicyaux", "ipaobject", "ipasshuser", "ipaSshGroupOfPubKeys", "ipantuserattrs"], "sn": ["test2"], "uid": ["test2"], "uidnumber": ["330001"]}}
```
curl example:
fails:
```
curl -H referer:https://qwe/ipa --negotiate -u : -H "Content-Type:application/json" -H "Accept:application/json" -c $COOKIEJAR -b $COOKIEJAR --cacert /etc/ipa/ca.crt -d '{"id": 0,"method": "user_add","params": [["test"],{"gidnumber": 330000,"givenname": "test","sn": "test","version": "2.231"}]}' -X POST https://qwe/ipa/session/json

{"result": null, "version": "4.6.5", "error": {"message": "Unable to create private group. A group 'test' already exists.", "code": 4024, "data": {"group": "test"}, "name": "ManagedGroupExistsError"}, "id": 0, "principal": "admin@REALM"}
```
success with explicit `"noprivate": "true"`
```
curl -H referer:https://qwe/ipa --negotiate -u : -H "Content-Type:application/json" -H "Accept:application/json" -c $COOKIEJAR -b $COOKIEJAR --cacert /etc/ipa/ca.crt -d '{"id": 0,"method": "user_add","params": [["test"],{"gidnumber": 330000,"givenname": "test","sn": "test", "noprivate": "true", "version": "2.231"}]}' -X POST https://qwe/ipa/session/json

{"result": {"result": {"has_keytab": false, "cn": ["test test"], "krbcanonicalname": ["test@REALM"], "memberof_group": ["ipausers"], "has_password": false, "homedirectory": ["/home/test"], "uid": ["test"], "loginshell": ["/bin/sh"], "uidnumber": ["300013"], "mail": ["test@realm"], "dn": "uid=test,cn=users,cn=accounts,dc=qwe,dc=qwe", "displayname": ["test test"], "description": [], "ipauniqueid": ["9d91484c-c365-11e9-b16a-00505681bf8d"], "krbprincipalname": ["test@REALM"], "givenname": ["test"], "objectclass": ["top", "person", "organizationalperson", "inetorgperson", "inetuser", "posixaccount", "krbprincipalaux", "krbticketpolicyaux", "ipaobject", "ipasshuser", "ipaSshGroupOfPubKeys", "ipantuserattrs"], "ipantsecurityidentifier": ["S-1-5-21-1847660308-3156656839-2481403808-1013"], "gidnumber": ["330000"], "gecos": ["test test"], "sn": ["test"], "initials": ["tt"]}, "value": "test", "summary": "Added user \"test\""}, "version": "4.6.5", "error": null, "id": 0, "principal": "admin@REALM"}
```
