### ISSUE TITLE
win_scheduled_task should support gMSA principals

### ISSUE THREAD

**Issue by briantist** [ansible/ansible#60989]
##### SUMMARY
A [Group Managed Service Account or gMSA](https://techcommunity.microsoft.com/t5/Core-Infrastructure-and-Security/Windows-Server-2012-Group-Managed-Service-Accounts/ba-p/255910) is a special type of service account in Active Directory that has its password managed automatically and can be used across multiple servers. The password is not known to administrators, and services, applications, and scheduled tasks that run as this account are able to automatically retrieve the password for the account.

Scheduled Tasks can run as gMSA, by setting a `logon_type` of `password` without actually supplying a password.

The `win_scheduled_task` module enforces that a password is supplied when the logon type is `password`, but the code otherwise would work as is.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_scheduled_task

##### ADDITIONAL INFORMATION

```yaml
- name: Task with gMSA
  win_scheduled_task:
    name: TaskName2
    username: DOMAIN\gMsaSvcAcct$
    logon_type: password
```
