### ISSUE TITLE
tower_credential module not idempotent

### ISSUE THREAD

**Issue by itcultus** [ansible/ansible#61007]
##### SUMMARY
The tower_credential module is not idempotent, at least not when I create a new SCM credential with an SSH key. 

The code I use is the following (all variables are defined)

`  tower_credential:
    name: "{{ name  }}"
    description: "{{ description  }}"
    kind: "scm"
    organization: "{{ organization }}"
    ssh_key_data: "{{ ssh_key_data }}"
    state: present
    username: "{{ username }}"`

##### ISSUE TYPE
Every time I execute the playbook with the above code I get "Changed: 1" although the credentials are in the Ansible Tower already and nothing is modified since the last execution. 

##### COMPONENT NAME
tower_credential

##### ANSIBLE VERSION
ansible 2.8.2

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT
Fedora 29, latest patch level

##### STEPS TO REPRODUCE
Create a new 

```yaml
- name: Configure Ansible Tower
  hosts: towers
  gather_facts: no
  become: false

  tasks: 
    - name:  Create Credentials
       tower_credential:
          name: "{{ name  }}"
          description: "{{ description }}"
          kind: "scm"
          organization: "{{ organization }}"
          ssh_key_data: "{{ ssh_key_data }}"
          state: present
          username: "{{ username }}"`
```

##### EXPECTED RESULTS
The module should not return changed when the credentials already exist and they are the same. 

##### ACTUAL RESULTS

Module returns changed every time it's executed. 
 

```paste below
TASK [tower_configure : Setup tower credentials security attributes] **********************************************************************************************************************************
Wednesday 21 August 2019  14:01:54 +0300 (0:00:00.165)       0:00:00.165 ****** 
changed: [tower.example.com] => (item=cred_tower_gitlab)
```
