### ISSUE TITLE
user module fails when comment argument contains spaces

### ISSUE THREAD

**Issue by ava-miket** [ansible/ansible#6101]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.3
##### Environment:

client running Ubuntu 13.10, target server running Ubuntu 12.04
##### Summary:

JSON strings containing spaces passed to "user" module seem to be improperly converted to arrays
##### Steps To Reproduce:

Running this task:

```
- name: create users
  user: name={{ item.user }} group={{ item.user }} comment={{ item.name }} password={{ item.pass }} shell=/bin/bash state=present
  with_items:
    - { name: "One Two Three", user: 'onetwothree', pass: '********' }
    - etc.
```
##### Expected Results:

should create the user "onetwothree" in target server's /etc/passwd with a commment field of "One Two Three"
##### Actual Results:

```
failed: [xx.xxx.xxx.xxx] => (item={'pass': '********', 'user': 'onetwothree', 'name': 'One Two Three'}) => {"failed": true, "item": {"name": "One Two Three", "pass": "********", "user": "onetwothree"}}
msg: this module requires key=value arguments (['name=onetwothree', 'group=onetwothree', 'comment=One', 'Two', 'Three', 'password=********', 'shell=/bin/bash', 'state=present'])
```

Note: not tested on options other than "comment"
