### ISSUE TITLE
Delete cloudflare record

### ISSUE THREAD

**Issue by sysndevops** [ansible/ansible#61030]
##### SUMMARY

I'm trying to delete an existing 'A' record within the Cloudflare platform. It does not get deleted and task state always displays 'OK' after the execution. I can view the DNS record within the Cloudflare dashboard even after executing the deletion task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cloudflare_dns

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS

##### STEPS TO REPRODUCE

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Deleting the records...
      cloudflare_dns:
        zone: example.com
        value: "subdomain.example.com"
        account_email: myemail@gmail.com
        account_api_token: jsddscjsdbcsdbcdbjsbcsjcb
        state: absent
```

##### EXPECTED RESULTS

I expect the playbook to delete the record from the cloudflare and the state should be 'changed' if the DNS record gets deleted.

##### ACTUAL RESULTS

ok: [127.0.0.1] => {
    "info": {
        "changed": false, 
        "failed": false
    }

```paste below

```
