### ISSUE TITLE
module_defaults don't apply to aliased modules

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#61068]
##### SUMMARY

If you use module_defaults (especially on a group) but call the module by one of its aliases then it fails to pick up the defaults

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/config/module_defaults.yml

##### ANSIBLE VERSION

Triggered this against devel (because _facts was renamed to _info)

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/home/mchappel/.ansible.cfg) = [u'timer', u'profile_tasks']
HOST_KEY_CHECKING(/home/mchappel/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/mchappel/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL7

##### STEPS TO REPRODUCE
```
- name: Run ec2_asg integration tests.
  module_defaults:
    group/aws:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      security_token: "{{ security_token | default(omit) }}"
      region: "{{ aws_region }}"
  block:
    - name: Find AMI to use 
      ec2_ami_info:
        owners: 'amazon'
        filters:
          name: '{{ ec2_ami_name }}'
      register: ec2_amis
    - name: Find AMI to use 
      ec2_ami_facts:
        owners: 'amazon'
        filters:
          name: '{{ ec2_ami_name }}'
      register: ec2_amis
```
##### EXPECTED RESULTS

ec2_ami_facts and ec2_ami_info should both use the defaults.

##### ACTUAL RESULTS

ec2_ami_info uses the module_defaults, ec2_ami_facts doesn't.
