### ISSUE TITLE
ansible-playbook with --check does not define register variables causing conditionals to error out

### ISSUE THREAD

**Issue by awheeler** [ansible/ansible#6108]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.4.3
##### Environment:

CentOS 6
##### Summary:

When executing ansible-playbook with the --check argument, some variables are not defined that would be without the --check argument, resulting a in a confusing error message that is difficult to troubleshoot.  Even adding -vvv provides no extra detail on what went wrong.
##### Steps To Reproduce:

Consider the following playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Check the port
      shell: "iptables -L INPUT -n | grep ':1234 '; rc=0"
      register: iptables_result
      ignore_errors: True
      changed_when: False

    - name: Enable the port if it is not already
      command: lokkit -p 1234:tcp -q
      when: "':1234' not in iptables_result.stdout"
```
##### Expected Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Check the port] ******************************************************** 
ok: [127.0.0.1]

TASK: [Enable the port if it is not already] ********************************** 
skipping: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [127.0.0.1] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [Check the port] ******************************************************** 
skipping: [127.0.0.1]

TASK: [Enable the port if it is not already] ********************************** 
fatal: [127.0.0.1] => error while evaluating conditional: ':1234' not in iptables_result.stdout

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/test.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0   
```
