### ISSUE TITLE
document with_first_found example + template

### ISSUE THREAD

**Issue by elasticdog** [ansible/ansible#6109]
##### Issue Type:

Bug Report
##### Ansible Version:
ansible 2.2
ansible 1.4.5

##### Environment:

N/A
##### Summary:

It took me a while to figure out that `with_first_found` was only looking under the _files/_ path by default, and not under _templates/_ even when used with the template module. Looking up templates works fine if you [manually specify that paths should include _../templates/_](https://github.com/ansible/ansible/pull/3681#issuecomment-22207587), but that is not consistent with the [first looping docs example](http://docs.ansible.com/playbooks_loops.html#finding-first-matched-files).

Either the first example on that page should be switched to the copy module and a note added about the lookup path, or the path should be adjusted based on the module you're using (like copy vs template do currently).

And the error message itself is confusing, since it would appear to look in the correct place...
##### Steps To Reproduce:

**This did not work:**

``` yml
- name: configure the iptables packet filtering
  sudo: true
  template: src={{ item }} dest=/etc/iptables/rules.v4
    owner=root group=root mode=0644
  with_first_found:
    - iptables_{{ ruleset }}.rules.v4.j2
    - iptables_base.rules.v4.j2
  notify: reload the iptables rules
```
##### Expected Results:

```
TASK: [firewall | configure the iptables packet filtering] ******************** 
ok: [node1] => (item=/home/elasticdog/ansible-playbooks/roles/firewall/templates/iptables_base.rules.v4.j2)
```
##### Actual Results:

```
TASK: [firewall | configure the iptables packet filtering] ******************* 
fatal: [node1] => input file not found at /home/elasticdog/ansible-playbooks/roles/firewall/templates/None or /home/elasticdog/ansible-playbooks/None

FATAL: all hosts have already failed -- aborting
```

**This  produces the expected results:**

``` yml
- name: configure the iptables packet filtering
  sudo: true
  template: src={{ item }} dest=/etc/iptables/rules.v4
    owner=root group=root mode=0644
  with_first_found:
    - files:
      - iptables_{{ ruleset }}.rules.v4.j2
      - iptables_base.rules.v4.j2
      paths:
        - ../templates
  notify: reload the iptables rules
```
