### ISSUE TITLE
ansible_facts no longer passed to templates

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#611]
I note Ansible is no longer passing facts to templates, at least it doesn't work for me on -devel (last pulled a few minutes ago). I've looked at the code, in `lib/ansible/runner/__init__.py` and I believe it's due to `execute_template()` not calling `_add_result_to_setup_cache()` but I don't have a clue when or how to invoke the latter.

Here's a test run:

```
$ ANSIBLE_SSH_ARGS="" ANSIBLE_REMOTE_USER=f2 ansible-playbook --connection=ssh j1.yaml -v

PLAY [a1.ww.mens.de] ********************* 

GATHERING FACTS ********************* 
ok: [a1.ww.mens.de]

TASK: [JPSETUP] ********************* 
ok: [a1.ww.mens.de] => {"ansible_facts": {"users_logged_in": 3}}

TASK: [Demotemplate] ********************* 
ok: [a1.ww.mens.de] => {"changed": false, "dest": "/tmp/info.txt", "group": "adm", "md5sum": "30553208a6f542667c47e728e9bb7f9a", "mode": "0644", "path": "/tmp/info.txt", "src": "/home/f2/.ansible/tmp/ansible-1342596365.48-141559060171382/source", "state": "file", "user": "f2"}

PLAY RECAP ********************* 
a1.ww.mens.de                  : ok=3    changed=1    unreachable=0    failed=0    
```

Playbook:

```

---
- hosts: a1.ww.mens.de
  vars:
     name: v2
  tasks:
  - name: JPSETUP
    action: jpsetup
  - name: Demotemplate
    action: template src=info.in dest=/tmp/info.txt
```

Facts 

```
$ cat library/jpsetup 
#!/bin/sh

COUNT=`who | wc -l`
cat <<EOF
{
   "ansible_facts" : {
      "users_logged_in" : $COUNT
   }
}
EOF
```

Template

```
$ cat info.in
version: {{ name }}
logged-in: {{ users_logged_in }}
logged-in: ${users_logged_in}
```

Output

```
$ cat /tmp/info.txt
version: v2
logged-in: 
logged-in: ${users_logged_in}
```
