### ISSUE TITLE
Add group option to win_firewall_rule

### ISSUE THREAD

**Issue by linuxjoergen** [ansible/ansible#61102]
##### SUMMARY

On Windows, a firewall rule can be a member of a group.  Rule groups can be used to organize rules by influence and allows batch rule modification. 

It would be nice to have the option to manage grouping with Ansible as well. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_firewall_rule

##### ADDITIONAL INFORMATION

We use grouping of firewall rules to associate the rules with multi tiered applications. It provides a better overview and makes it easier to manage the firewall rules.

The feature is documented on New-NetFirewallRule page of PowerShell
https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps

```yaml

- name: Setup Windows Firewall (with group)
  win_firewall_rule:
     name: http
     state: absent
     action: allow
     direction: in
     group: myGroup


```
