### ISSUE TITLE
juniper junos_facts does not gather junos_interfaces facts using gather_network_resources: interfaces

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#61183]
##### SUMMARY
juniper junos_facts does not gather junos_interfaces facts using gather_network_resources: interfaces, this works for ios_facts and eos_facts and should match for junos_facts, basically this does not work->
```
- name: grab juniper junos info
  junos_facts:
    gather_subset: min
    gather_network_resources: interfaces
```

my inventory
```
[juniper]
rtr3 ansible_host=3.15.5.167 private_ip=172.16.25.197

[juniper:vars]
ansible_user=ec2-user
ansible_network_os=junos
ansible_connection=netconf
```

no interfaces information is gathered

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_facts

##### ANSIBLE VERSION

```paste below
[student1@ansible tower_workshop]$ ansible --version
ansible 2.9.0.dev0
  config file = /home/student1/tower_workshop/ansible.cfg
  configured module search path = [u'/home/student1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/student1/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
[student1@ansible tower_workshop]$ ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/home/student1/tower_workshop/ansible.cfg) = [u'time']
DEFAULT_FORKS(/home/student1/tower_workshop/ansible.cfg) = 50
DEFAULT_NO_TARGET_SYSLOG(/home/student1/tower_workshop/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/home/student1/tower_workshop/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/student1/tower_workshop/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/student1/tower_workshop/ansible.cfg) = False
INTERPRETER_PYTHON(/home/student1/tower_workshop/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/student1/tower_workshop/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/student1/tower_workshop/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/student1/tower_workshop/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
[student1@ansible tower_workshop]$ cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

##### STEPS TO REPRODUCE

```yaml
- name: grab juniper junos info
  junos_facts:
    gather_subset: min
    gather_network_resources: interfaces
  register: stuff

- debug:
    msg: "{{stuff}}"

- debug:
    msg: "{{ansible_network_resources}}"
```

##### EXPECTED RESULTS

```
ok: [rtr2] =>
  msg:
  - Interface info for rtr2
  - - enabled: true
      name: Ethernet1
    - enabled: true
      name: Loopback0
    - enabled: true
      name: Loopback1
    - enabled: true
      mtu: '1476'
      name: Tunnel0
    - enabled: true
      name: Ethernet1
    - enabled: true
      name: Tunnel1
    - enabled: true
      name: Ethernet1
```

##### ACTUAL RESULTS

```paste below
TASK [read_interfaces : debug] **************************************************************************************************
ok: [rtr3] =>
  msg:
    ansible_facts:
      ansible_net_api: netconf
      ansible_net_gather_network_resources:
      - interfaces
      ansible_net_gather_subset:
      - default
      ansible_net_hostname: ansible
      ansible_net_model: vSRX
      ansible_net_python_version: 2.7.5
      ansible_net_serialnum: 8d29dd56a32c
      ansible_net_system: junos
      ansible_net_version: 18.4R1.8
      ansible_network_resources: {}
      discovered_interpreter_python: /usr/bin/python
    changed: false
    failed: false
    warnings:
    - default value for `gather_subset` will be changed to `min` from `!config` v2.11 onwards

TASK [read_interfaces : debug] **************************************************************************************************
ok: [rtr3] =>
  msg: {}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/junos/junos_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@IPvSean, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by NilashishC** [comment]
Same task seems to work fine for me:
```yaml
ansible_facts:
    ansible_net_api: netconf
    ansible_net_gather_network_resources:
    - interfaces
    ansible_net_gather_subset:
    - default
    ansible_net_hostname: junos01
    ansible_net_model: vsrx
    ansible_net_python_version: 3.6.8
    ansible_net_serialnum: 35C463ACD59C
    ansible_net_system: junos
    ansible_net_version: 17.3R1.10
    ansible_network_resources:
      interfaces:
      - description: ANSIBLE
        enable: true
        name: fxp0
        speed: 1g
      - description: TEST-LOOPBACK
        enable: true
        name: lo0
```

I'm on ncclient version `0.6.6`.

**Comment by danielmellado** [comment]
Same there, I've tried reproducing the exact same commands there with a different version of junos, which is the one we used to develop with and it works just fine:

```yml
ok: [junos_local] => changed=false 
  ansible_facts:
    ansible_net_api: netconf
    ansible_net_gather_network_resources:
    - interfaces
    ansible_net_gather_subset:
    - default
    ansible_net_hostname: vsrx
    ansible_net_model: vSRX
    ansible_net_python_version: 3.7.4
    ansible_net_serialnum: 70a3960b81da
    ansible_net_system: junos
    ansible_net_version: 18.4R1-S3.1
    ansible_network_resources:
      interfaces:
      - enable: true
        name: fxp0
  invocation:
    module_args:
      config_format: text
      gather_network_resources:
      - interfaces
      gather_subset:
      - min
      host: null
      password: null
      port: null
      provider: null
      ssh_keyfile: null
      timeout: null
      transport: null
      username: null
```

If you just get the final message in your playbook, it'd be

```yml
ok: [junos_local] => 
  msg:
    interfaces:
    - enable: true
      name: fxp0
```

Could you please double check your `ncclient`version and junos version and reply here? I haven't been able to reproduce your issue.

Thanks!
