### ISSUE TITLE
Receiving deprecation notices in the win_group_membership module

### ISSUE THREAD

**Issue by wbagdon** [ansible/ansible#61181]
##### SUMMARY

Seeing a deprecation notice about group names in the win_group module.
I'm assuming this is some sort of oversight since the error is being thrown on the windows group that I want to add users to (Performance Monitor Users)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_group_membership

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.8.3
  config file = /home/taskdtcansible/ansible-teamcity-windows/ansible.cfg
  configured module search path = ['/home/taskdtcansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.7 (default, Dec  5 2018, 15:02:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/taskdtcansible/ansible-teamcity-windows/ansible.cfg) = ['logstash']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/taskdtcansible/ansible-teamcity-windows/ansible.cfg) = True
```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

group_membership def:
```yaml
installs:
  group_membership:
    sdlcuser:
      add:
        - Users
        - Remote Desktop Users
        - Performance Monitor Users
```

including the group membership task:
```yaml
- include_tasks: group_membership.yml
  when: "'group_membership' in installs | default(false)"
  with_items: "{{ installs.group_membership | default({}) | dict2items }}"
  loop_control:
    loop_var: user
```

group_membership.yml
```yaml
---
- block:
    - name: "add {{ user.key }} to given groups"
      win_group_membership:
        name: "{{ add_group }}"
        members:
          - 'SUSQ\{{ user.key }}'
        state: present
      when: user.value.add is defined
      loop: "{{ user.value.add }}"
      loop_control:
        loop_var: add_group
      notify: restart agents

    - name: "remove {{ user.key }} from given groups"
      win_group_membership:
        name: "{{ remove_group }}"
        members:
          - 'SUSQ\{{ user.key }}'
        state: absent
      when: user.value.remove is defined
      loop: "{{ user.value.remove }}"
      loop_control:
        loop_var: remove_group
      notify: restart agents
  tags: group_membership
```

##### EXPECTED RESULTS

No deprecation notice

##### ACTUAL RESULTS

Ansible is seeing the space in the windows group name and throwing the deprecation notice

```paste below
TASK [teamcity_windows : add sdlcuser to given groups] *********************************************************************************************task path: /home/taskdtcansible/ansible-teamcity-windows/playbooks/roles/teamcity_windows/tasks/group_membership.yml:3
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_group_membership.ps1
Pipelining is enabled.
<dtcdevbal501.ds.susq.com> ESTABLISH WINRM CONNECTION FOR USER: None on PORT 5986 TO dtcdevbal501.ds.susq.com
EXEC (via pipeline wrapper)
ok: [dtcdevbal501.ds.susq.com] => (item=Users) => {
    "add_group": "Users",
    "added": [],
    "ansible_loop_var": "add_group",
    "changed": false,
    "members": [
        "NT AUTHORITY\\INTERACTIVE",
        "NT AUTHORITY\\Authenticated Users",
        "SUSQ\\Domain Users",
        "SUSQ\\sdlcuser"
    ],
    "name": "Users"
}
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [dtcdevbal501.ds.susq.com] => (item=Remote Desktop Users) => {
    "add_group": "Remote Desktop Users",
    "added": [],
    "ansible_loop_var": "add_group",
    "changed": false,
    "members": [
        "SUSQ\\GlobalServerAdmins-RO",
        "SUSQ\\sdlcuser"
    ],
    "name": "Remote Desktop Users"
}
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/win_group_membership.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [dtcdevbal501.ds.susq.com] => (item=Performance Monitor Users) => {
    "add_group": "Performance Monitor Users",
    "added": [],
    "ansible_loop_var": "add_group",
    "changed": false,
    "members": [
        "SUSQ\\sdlcuser"
    ],
    "name": "Performance Monitor Users"
}
Not replacing invalid character(s) "{' '}" in group name (Remote Desktop Users)
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but
still be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

Not replacing invalid character(s) "{' '}" in group name (Performance Monitor Users)
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_group.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @chrishoffman @if-meaton @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wbagdon** [comment]
Updated to reflect the correct module name `win_group_membership`

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_group_membership.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_group_membership.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @andrewsaraceni
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrewsaraceni** [comment]
@wbagdon These deprecation warnings are not a function of the win_group_membership module, but rather Ansible in general, and the way in which your example is handling group names in your inventory.  It looks like your group names are the same names as the Windows groups you're trying to control membership on, so spaces in the name appear to be the issue.

There's some [documentation](https://docs.ansible.com/ansible/latest/reference_appendices/config.html) on this as of version 2.8, and some further discussion around it [here](https://github.com/ansible/ansible/issues/56930).

There's a fair amount going on in your included example, which may account for the confusion, but you should notice the warnings themselves go away were you to simplify your playbook to a direct call of the module using a more simply named host group.  Either way, you should be able to adjust your ansible.cfg to account for this, it looks like.

**Comment by jborean93** [comment]
See above

**Comment by wbagdon** [comment]
The notices are specifically for the strings in the `name` property of win_group_membership so I'm still not understanding why this is giving me a deprecation notice.
```
Not replacing invalid character(s) "{' '}" in group name (Remote Desktop Users)
Not replacing invalid character(s) "{' '}" in group name (Performance Monitor Users)
```

"Remote Desktop Users" and "Performance Monitor Users" are not ansible group names in my inventory file.

**Comment by wbagdon** [comment]
@jborean93 
I was able to remove the deprecation notice by changing my loop_var names from `remove_group` to `item`

```yaml
---
- block:
    - name: "add {{ user.key }} to given groups"
      win_group_membership:
        name: "{{ item }}"
        members:
          - 'SUSQ\{{ user.key }}'
        state: present
      when: user.value.add is defined
      loop: "{{ user.value.add }}"
      loop_control:
        loop_var: item
      notify: restart agents

    - name: "remove {{ user.key }} from given groups"
      win_group_membership:
        name: "{{ item }}"
        members:
          - 'SUSQ\{{ user.key }}'
        state: absent
      when: user.value.remove is defined
      loop: "{{ user.value.remove }}"
      loop_control:
        loop_var: item
      notify: restart agents
  tags: group_membership
```
