### ISSUE TITLE
git module - New release available return code

### ISSUE THREAD

**Issue by LucidOne** [ansible/ansible#61204]
##### SUMMARY
I'd like the git module return a `new_release` boolean to provide a means of throwing a warning if a new release has been tagged. Ideally it should support semver/calver
comparisons across all tags to see if a new tag is newer.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git

##### ADDITIONAL INFORMATION

This should provide a better means of version tracking when building from source.

```yaml
---
- hosts: localhost
  vars:
    ansible_connection: local
  tasks:
  - name: "Checkout Ansible source"
    git:
      repo: "https://github.com/ansible/ansible"
      dest: "{{ ansible_user_dir }}/src/ansible"
      version: "v2.8.3"
    register: result
  - name: "update"
    debug:
      msg: "Newer version available: {{result.new_tag}}"
    when: result.new_release
```
