### ISSUE TITLE
vmware_category add "Associable Object Types" functionality

### ISSUE THREAD

**Issue by nicholasrodriguez** [ansible/ansible#61220]
##### SUMMARY
Can functionality be added so that "Associable Object Types" can be configured for a tag category please?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_category

##### ADDITIONAL INFORMATION
Perhaps the module could be extended to include a list, examples below;
```
- name: 'Create a Category'
  connection: 'local'
  vmware_category:
    hostname: '{{ ansible_host }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    category_name: "sas_luns"
    category_description: "SAS LUNS"
    category_cardinality: 'multiple'
    associable_object_types:
         - Datastore
         - Datastore Cluster
    state: present
    validate_certs: '{{ validate_certs }}'

- name: 'Create a Category'
  connection: 'local'
  vmware_category:
    hostname: '{{ ansible_host }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    category_name: "Region 1"
    category_description: "Region"
    category_cardinality: 'multiple'
    associable_object_types:
         - All objects
    state: present
    validate_certs: '{{ validate_certs }}'
```
The type of Associable Object Types in vSphere 6.7 are:
All objects
Folder
Cluster
Datacenter
Datastore
Datastore Cluster
Distributed Port Group
Distributed Switch
Host
Content Library
Library item
Network
Resource Pool
vApp
Virtual Machine

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_category.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_category.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nicholasrodriguez, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@nicholasrodriguez Can you please check above PR and let me know if it works for you ? Thanks.

**Comment by nicholasrodriguez** [comment]
@Akasurde, thnaks for the PR, I've tested and I get a module error. Config parameters below

```
- name: 'Create a category'
  connection: 'local'
  vmware_category:
    hostname: '{{ ansible_host }}'
    username: '{{ ansible_vcenter_username }}'
    password: '{{ ansible_vcenter_password }}'
    category_name: "ssd_luns"
    category_description: "SSD LUNs"
    category_cardinality: "multiple"
    associable_object_types:
       - Datastore
       - Datastore Cluster
    state: present
    validate_certs: '{{ validate_certs }}'
```
Module error verbose output
```
fatal: [<VCENTER FQDN>]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1570018052.88-183978352512839/AnsiballZ_vmware_category.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1570018052.88-183978352512839/AnsiballZ_vmware_category.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1570018052.88-183978352512839/AnsiballZ_vmware_category.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_vmware_category_payload_oZ0mTS/__main__.py\", line 328, in <module>\n  File \"/tmp/ansible_vmware_category_payload_oZ0mTS/__main__.py\", line 323, in main\n  File \"/tmp/ansible_vmware_category_payload_oZ0mTS/__main__.py\", line 169, in __init__\nAttributeError: 'VmwareCategory' object has no attribute 'api_client'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
