### ISSUE TITLE
Add additional EKS cluster configuration options

### ISSUE THREAD

**Issue by JacobHenner** [ansible/ansible#61230]
##### SUMMARY

The following configuration parameters are [supported by boto](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/eks.html#EKS.Client.create_cluster), but are currently omitted from aws_eks_cluster:

- endpointPublicAccess
- endpointPrivateAccess
- clusterLogging

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

aws_eks_cluster
##### ADDITIONAL INFORMATION
This feature would be used to set the logging options and endpoint access options for EKS clusters.
For example:

```yaml
- name: Create an EKS cluster
  aws_eks_cluster:
    name: my_cluster
    version: v1.10.0
    role_arn: my_eks_role
    subnets:
      - subnet-aaaa1111
    security_groups:
      - my_eks_sg
      - sg-abcd1234
    endpoint_public_access: yes
    endpoint_private_access: yes
    logging:
      enabled:
        - api
        - audit
        - authenticator
      disabled:
        - controllerManager
        - scheduler
  register: caller_facts
```
