### ISSUE TITLE
l3_interfaces for ansible_network_resources are not working for eos, junos and ios

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#61242]
##### SUMMARY
Using the `ansible_network_resources: l3_interfaces` does not work on ios, eos and junos.

- eos fails
- ios fails
- junos returns empty list

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_facts
ios_facts
junos_facts

(these are only ones I tested)

e.g
```
    - name: grab info
      ios_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces
```

see below for more info

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = /home/student1/.ansible.cfg
  configured module search path = [u'/home/student1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/student1/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
[student1@ansible ~]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = [u'/home/student1/networking-workshop/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
[student1@ansible ~]$ cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

##### STEPS TO REPRODUCE

for ios
```yaml
---
- hosts: rtr1
  gather_facts: false
  tasks:
    - name: grab info
      ios_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - debug:
        var: ansible_network_resources
```

for eos
```
---
- hosts: rtr2
  gather_facts: false
  tasks:
    - name: grab info
      eos_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - debug:
        var: ansible_network_resources
```

for junos
```
---
- hosts: rtr3
  gather_facts: false
  tasks:
    - name: grab info
      junos_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - debug:
        var: ansible_network_resources
```

##### ACTUAL RESULTS

For Arista EOS
```
[student1@ansible ~]$ ansible-playbook eos.yml

PLAY [rtr2] *********************************************************************************************************************
---

TASK [grab info] ****************************************************************************************************************
fatal: [rtr2]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  msg: 'value of gather_network_resources must be one or more of: all, !all, interfaces, !interfaces, l2_interfaces, !l2_interfaces, lacp, !lacp, lag_interfaces, !lag_interfaces, vlans, !vlans. Got no match for: l3_interfaces'

PLAY RECAP **********************************************************************************************************************
rtr2                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
For Cisco IOS
```
[student1@ansible ~]$ ansible-playbook ios.yml

PLAY [rtr1] *********************************************************************************************************************

TASK [grab info] ****************************************************************************************************************
fatal: [rtr1]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  msg: 'value of gather_network_resources must be one or more of: all, !all, interfaces, !interfaces, l2_interfaces, !l2_interfaces, vlans, !vlans, lag_interfaces, !lag_interfaces, lacp, !lacp, lacp_interfaces, !lacp_interfaces, lldp_global, !lldp_global. Got no match for: l3_interfaces'

PLAY RECAP **********************************************************************************************************************
rtr1                       : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
For Juniper Junos
```
---
- hosts: rtr3
  gather_facts: false
  tasks:
    - name: grab info
      junos_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - debug:
        var: ansible_network_resources
```

**Comment by Qalthos** [comment]
I can't reproduce with eos, and I don't see an exact git hash (did that get removed from `ansible --version`?) so my guess is your checkout is from before yesterday when eos_l3_interfaces was merged.

needs_info

**Comment by IPvSean** [comment]
how do i get you the hash?

**Comment by IPvSean** [comment]
ok uninstalled and reinstalled and IOS and EOS work but JUNOS does **NOT** work

```
ok: [rtr1] =>
  ansible_network_resources:
    l3_interfaces:
    - ipv4:
      - address: 192.168.1.101 255.255.255.0
      name: loopback0
    - ipv4:
      - address: 10.1.1.101 255.255.255.0
      name: loopback1
    - ipv4:
      - address: 1.2.3.4 255.255.255.0
      ipv6:
      - address: fc00::2/64
      name: loopback100
    - ipv4:
      - address: dhcp
      name: GigabitEthernet1
```

yay

but junos is still empty as of Aug 23, 4:36 PM ET

I assume this is same thing @ganeshrn had for the other juniper module with junos_interfaces
