### ISSUE TITLE
Reporting shell/command task as "changed" in check mode

### ISSUE THREAD

**Issue by satken2** [ansible/ansible#61285]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- Check mode
- Shell/Command module

##### ADDITIONAL INFORMATION

When I execute shell module in non-check mode, Ansible always report it as "changed". 
However in check mode, Ansible always report it as "skipped" even if it would have been executed in non-check mode.

When I execute a playbook such as below, I do NOT want to execute task B in check mode, but I want to know whether it would have been executed in non-check mode.
When I execute it, the number of "changed" would differ between check mode and non-check mode.

```yaml
  - name: Task A - check if some command succeeds
    shell: /bin/some/command/a
    register: result
    check_mode: no

  - name: Task B - execute some command when the command failed
    shell: /bin/some/command/b
    when: not result.rc == 0
```

In check mode
```
PLAY RECAP *********************************************************
192.168.1.2  : ok=1   changed=0    skipped=1
```

In non-check mode
```
PLAY RECAP *********************************************************
192.168.1.2  : ok=1   changed=1    skipped=0
```

With this feature, the number of "changed" could be the same in check mode and non-check mode.
