### ISSUE TITLE
ANSIBLE_DISPLAY_SKIPPED_HOSTS does not work as play env

### ISSUE THREAD

**Issue by Hipska** [ansible/ansible#61319]
##### SUMMARY
It seems [ANSIBLE_DISPLAY_SKIPPED_HOSTS](https://docs.ansible.com/ansible/latest/reference_appendices/config.html?highlight=ansible_display_skipped_hosts#display-skipped-hosts) does not get respected as environment variable for a play in a playbook. It does work correctly when set up in the ini file or as environment for the whole cli command.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/callback/default.py

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /home/***/playbooks/ansible.cfg
  configured module search path = [u'/home/***/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
RedHat 7.4

##### STEPS TO REPRODUCE
Using this playbook:

```yaml
---
- hosts: some_group
  tasks:
    - debug:
        msg: "{{ ansible_env }}"
      when: (11 | random) > 5
  environment:
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: no
```

##### EXPECTED RESULTS
The details of the skipped task should not be visible.

##### ACTUAL RESULTS
Host with the skipped debug task show lines like this:

> TASK [debug] *******************************
> skipping: [hostname]

Other hosts correctly display `ANSIBLE_DISPLAY_SKIPPED_HOSTS: no` in their output
