### ISSUE TITLE
aci moduels not authenticating with private key under tower

### ISSUE THREAD

**Issue by DaveCrown** [ansible/ansible#61327]
##### SUMMARY

ACI modules in tower not correctly reading the private key. The private key is passed in as an env variable. When running on a local Fedora it picks up the key correctly from the env var, but not from tower when running with 2.8. Downgrading to 2.7 resolves the issue

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aci_tenant

##### ANSIBLE VERSION

```
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
[root@tower ~]# ansible-config dump --only-changed
[root@tower ~]# 

```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.7 (Maipo)  
Tower 3.4.3  
ACI 4.1.1k  

##### STEPS TO REPRODUCE

1. install ansible 2.8
2. launch play on tower
3. rollback to 2.7*
4. launch on tower

play
```yaml
- name: Get Tenants
  aci_tenant:
    hostname: "{{ apic_address }}"
    username: "{{ apic_user }}"
    private_key: "{{apic_key_path}}"
    certificate_name: "{{apic_cert_name}}"
    validate_certs: no
    use_proxy: no
    state: query
  register: response
```
variable definitions
```yaml
apic_user: "{{ansible_env.APIC_USER}}"
apic_key_path: "{{ansible_env.APIC_KEY}}"
apic_key_filename: "{{ansible_env.APIC_KEY | basename | regex_replace('\\..*') }}"
apic_cert_name: "{{ ansible_env.APIC_CERT_NAME | default(apic_key_filename) }}"
```
tower credential injector
```yaml
---
env:
  APIC_CERT_NAME: '{{ cred_apic_cert_name }}'
  APIC_KEY: '{{tower.filename.key}}'
  APIC_USER: '{{cred_apic_user}}'
  GIT_PWD: '{{ cred_git_pwd }}'
  GIT_USER: '{{ cred_git_user }}'
  netbox_key: '{{cred_netbox_key}}'
file:
  template.cert: |-
    [mycert]
    {{cred_apic_crt}}
  template.key: |-
    [mykey]
    {{cred_apic_key}}
```

##### EXPECTED RESULTS

```json
{
    "_ansible_parsed": true,
    "current": [
        {
            "fvTenant": {
                "attributes": {
                    "dn": "uni/tn-LabNetwork",
                    "lcOwn": "local",
                    "ownerKey": "",
                    "name": "LabNetwork",
                    "descr": "",
                    "extMngdBy": "",
                    "status": "",
                    "monPolDn": "uni/tn-common/monepg-default",
                    "modTs": "2019-06-20T09:18:03.108-04:00",
                    "ownerTag": "",
                    "uid": "8180",
                    "nameAlias": "",
                    "annotation": "",
                    "childAction": ""
                }
            }
        },
        {
            "fvTenant": {
                "attributes": {
                    "dn": "uni/tn-mgmt",
                    "lcOwn": "local",
                    "ownerKey": "",
                    "name": "mgmt",
                    "descr": "",
                    "extMngdBy": "",
                    "status": "",
                    "monPolDn": "uni/tn-common/monepg-default",
                    "modTs": "2019-04-08T14:00:47.320-04:00",
                    "ownerTag": "",
                    "uid": "0",
                    "nameAlias": "",
                    "annotation": "",
                    "childAction": ""
                }
            }
        },
        {
            "fvTenant": {
                "attributes": {
                    "dn": "uni/tn-common",
                    "lcOwn": "local",
                    "ownerKey": "",
                    "name": "common",
                    "descr": "",
                    "extMngdBy": "",
                    "status": "",
                    "monPolDn": "uni/tn-common/monepg-default",
                    "modTs": "2019-04-08T14:00:43.019-04:00",
                    "ownerTag": "",
                    "uid": "0",
                    "nameAlias": "",
                    "annotation": "",
                    "childAction": ""
                }
            }
        },
        {
            "fvTenant": {
                "attributes": {
                    "dn": "uni/tn-infra",
                    "lcOwn": "local",
                    "ownerKey": "",
                    "name": "infra",
                    "descr": "",
                    "extMngdBy": "",
                    "status": "",
                    "monPolDn": "uni/tn-common/monepg-default",
                    "modTs": "2019-04-08T14:00:47.450-04:00",
                    "ownerTag": "",
                    "uid": "0",
                    "nameAlias": "",
                    "annotation": "",
                    "childAction": ""
                }
            }
        },
        {
            "fvTenant": {
                "attributes": {
                    "dn": "uni/tn-iscsi",
                    "lcOwn": "local",
                    "ownerKey": "",
                    "name": "iscsi",
                    "descr": "",
                    "extMngdBy": "",
                    "status": "",
                    "monPolDn": "uni/tn-common/monepg-default",
                    "modTs": "2019-04-08T14:42:59.721-04:00",
                    "ownerTag": "",
                    "uid": "8180",
                    "nameAlias": "",
                    "annotation": "",
                    "childAction": ""
                }
            }
        }
    ],
    "changed": false,
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "username": "ansible",
            "private_key": "/tmp/awx_4073_RPDjd0/tmpVdljqn",
            "protocol": "https",
            "description": null,
            "certificate_name": "ansible_tower",
            "hostname": "10.3.10.101",
            "host": "10.3.10.101",
            "output_level": "normal",
            "state": "query",
            "timeout": 30,
            "use_ssl": true,
            "password": null,
            "validate_certs": false,
            "port": null,
            "tenant": null,
            "use_proxy": false
        }
    }
}
```

##### ACTUAL RESULTS

```json
{
    "invocation": {
        "module_args": {
            "username": "ansible",
            "private_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "https",
            "description": null,
            "certificate_name": "ansible_tower",
            "hostname": "10.3.10.101",
            "host": "10.3.10.101",
            "output_level": "normal",
            "state": "query",
            "timeout": 30,
            "use_ssl": true,
            "password": null,
            "validate_certs": false,
            "port": null,
            "tenant": null,
            "use_proxy": false
        }
    },
    "msg": "Provided private key file '********' does not appear to be a private key. Please correct.",
    "changed": false,
    "_ansible_no_log": false
}
```
