### ISSUE TITLE
tower_credential: Parameter 'vault_id' is only valid if parameter 'kind' is specified as 'vault'

### ISSUE THREAD

**Issue by mmallet-digipok** [ansible/ansible#61324]
##### SUMMARY
It seems that the commit 831f068 introduced a small regression. In the 'tower_credential' module, when the credential 'kind' is set to 'vault', the code expects the other parameter 'vault_id' to be set. Unfortunately, at execution time, the module returns an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_credential

##### ANSIBLE VERSION
```paste below
ansible 2.8.4
  config file = /home/mmallet/ansible/ansible_dev.cfg
  configured module search path = [u'/home/mmallet/ansible/library']
  ansible python module location = /home/mmallet/ansible/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/mmallet/ansible/.venv/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
CentOS 7.4

##### STEPS TO REPRODUCE
ansible-playbook <playbook content below>

```yaml
---
- name: Test Ansible Tower/AWX module for Vault creation
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_prompt:
    - name: awx_host
      prompt: AWX host
      private: no
    - name: awx_username
      prompt: Login
      private: no
    - name: awx_password
      prompt: Password

  tasks:
    - name: Create organization Foo
      tower_organization:
        name: Foo
        tower_host: "{{ awx_host }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        tower_verify_ssl: no
      register: organization_result

    - name: Create vault with ID 'bar' exists
      tower_credential:
        name: Foobar vault
        organization: "{{ organization_result.organization }}"
        kind: vault
        vault_id: bar
        vault_password: foobar
        tower_host: "{{ awx_host }}"
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        tower_verify_ssl: no
      register: vault_credentials_result

    - debug:
        var: vault_credentials_result
```

##### EXPECTED RESULTS
```
PLAY [Test Ansible Tower/AWX module for Vault creation] ***********************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
ok: [localhost]

TASK [Create organization Foo] ************************************************************************************************************************
changed: [localhost]

TASK [Create vault with ID 'bar' exists] **************************************************************************************************************
changed: [localhost]

TASK [debug] ******************************************************************************************************************************************
ok: [localhost] => {
    "vault_credentials_result": {
        "changed": true,
        "credential": "Foobar vault",
        "failed": false,
        "id": 43,
        "state": "present"
    }
}

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS
```
PLAY [Test Ansible Tower/AWX module for Vault creation] ***********************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
ok: [localhost]

TASK [Create organization Foo] ************************************************************************************************************************
ok: [localhost]

TASK [Create vault with ID 'bar' exists] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Parameter 'vault_id' is only valid if parameter 'kind' is specified as 'vault'"}

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
