### ISSUE TITLE
get_url: check mode not supported when using checksum URL

### ISSUE THREAD

**Issue by Normo** [ansible/ansible#61369]
##### SUMMARY

get_url does not support check mode (`--check`) when using the checksum format `<algorithm>:<url>`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- get_url

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nbe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nbe/.local/lib/python2.7/site-packages/ansible
  executable location = /home/nbe/.local/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

- Ubuntu 18.04.3 LTS

##### STEPS TO REPRODUCE

Run playbook in check mode: `ansible-playbook --check site.yml`

```yaml
---
- hosts: localhost
  connection: local

  vars:
    vault_version: '1.2.2'

  tasks:

    - name: Download zip archive using checksum
      get_url:
        url: 'https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip'
        dest: '/tmp/vault_{{ vault_version }}_linux_amd64.zip'
        checksum: 'sha256:7725b35d9ca8be3668abe63481f0731ca4730509419b4eb29fa0b0baa4798458'

    - name: Download zip archive using checksum url
      get_url:
        url: 'https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip'
        dest: '/tmp/vault_{{ vault_version }}_linux_amd64_2.zip'
        checksum: 'sha256:https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_SHA256SUMS'
```

##### EXPECTED RESULTS

The second task `'Download zip archive using checksum url'` using the format `<algorithm>:<url>` must not fail and should show the same result as the first task (ok/changed) in check mode.

##### ACTUAL RESULTS

The second task `'Download zip archive using checksum url'` using the format `<algorithm>:<url>` fails in check mode:

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "checksum": "sha256:https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_SHA256SUMS", 
            "client_cert": null, 
            "client_key": null, 
            "content": null, 
            "delimiter": null, 
            "dest": "/tmp/vault_1.2.2_linux_amd64.zip", 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "force_basic_auth": false, 
            "group": null, 
            "headers": null, 
            "http_agent": "ansible-httpget", 
            "mode": null, 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "sha256sum": "", 
            "src": null, 
            "timeout": 10, 
            "tmp_dest": null, 
            "unsafe_writes": null, 
            "url": "https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_linux_amd64.zip", 
            "url_password": null, 
            "url_username": null, 
            "use_proxy": true, 
            "validate_certs": true
        }
    }, 
    "msg": "Unable to find a checksum for file 'vault_1.2.2_linux_amd64.zip' in 'https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_SHA256SUMS'"
}
```

**Comment by n0guest** [comment]
> ##### SUMMARY
> get_url does not support check mode (`--check`) when using the checksum format `<algorithm>:<url>`.

Looks like it happens because get_url doesn't even trying to download checksums. Instead of GET method it's using HEAD (just to verify availability?).

PS: Same goes for Ubuntu 16.04/xenial:

```
$ ansible --version
ansible 2.8.2
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

**Comment by Akasurde** [comment]
I can confirm, with `--check` flag, `get_url` fails to download the checksum file from the given URL. This behaviour is because module only check the existence of checksum of file in the given URL (Added via 3f321e759158a3954cceacf62a14cd5126a225d0) rather than downloading the file. Respective code - https://github.com/ansible/ansible/blob/00193f27eb107310257efecae1d8ceadaa3acd95/lib/ansible/modules/net_tools/basics/get_url.py#L358

**Comment by kaminek** [comment]
👋 same behavior here in normal node (when not using `--check`)
```
ansible 2.9.4
  config file = /Users/amine/Work/git/ansible-playbooks/ansible.cfg
  configured module search path = ['/Users/amine/Work/git/ansible-playbooks/library']
  ansible python module location = /Users/amine/.local/share/virtualenvs/ansible-playbooks-84bBUirW/lib/python3.7/site-packages/ansible
  executable location = /Users/amine/.local/share/virtualenvs/ansible-playbooks-84bBUirW/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
```

task
```
  - name: Get natasha bin from nexus
    get_url:
      url: "{{ natasha_mirror_url }}/nat/{{ nat_version }}/amd64/{{ cpu_family }}/nat"
      dest: "{{ tmp_dir.path }}"
      checksum: "sha256:{{ natasha_mirror_url }}/nat/{{ nat_version }}/amd64/{{ cpu_family }}/nat.sha256"


```

output
```
fatal: [ch01nat01 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "sha256:https://nexus-registry.infra.net/repository/raw-registry/network/natasha/nat/latest/amd64/generic/nat.sha256",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/var/folders/n4/16063v8j6bj_nj9cnm44jc0m0000gn/T/ansible.hm2cg51q",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://nexus-registry.infra.net/repository/raw-registry/network/natasha/nat/latest/amd64/generic/nat",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Unable to find a checksum for file 'nat' in 'https://nexus-registry.infra.net/repository/raw-registry/network/natasha/nat/latest/amd64/generic/nat.sha256'"
}
```
