### ISSUE TITLE
Snapcraft: Add 'alias'

### ISSUE THREAD

**Issue by dmp1ce** [ansible/ansible#61400]
##### SUMMARY
Because of naming restrictions on snaps it is sometimes necessary to use an alias for snaps. Right now this can be done by requesting an alias in the snapcraft forum or by setting up an alias in the shell.

- ansible 2.9.9

##### ISSUE TYPE
I would like to propose a snap module addition to support the snap alias commands.

##### COMPONENT NAME
lib/ansible/modules/packaging/os/snap.py

##### ADDITIONAL INFORMATION
Currently, I run commands like this:

```yaml
    - name: Snap Package - Standard Install
      snap:
        name: check-cgminer
    - name: Snap Package - Setup Alias
      shell: 'snap alias check-cgminer check_cgminer'
```

Ideally, it should be configurable with something similar to:

```yaml
    - name: Snap Package - Standard Install
      snap:
        name: check-cgminer
        alias: check_cgminer
```

Similar to issue https://github.com/ansible/ansible/issues/58403
