### ISSUE TITLE
delegate_to with httpapi plugin does not use all necessary facts

### ISSUE THREAD

**Issue by axarriola** [ansible/ansible#61410]
##### SUMMARY

When a host connection uses  httpapi connection plugin with variables like ansible_httpapi_use_ssl specified in the inventory, and that host is delegated a task, it does not evaluate the facts values to make the connection and uses the default values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

connection/httpapi.py
httpapi/ftd.py

##### ANSIBLE VERSION

```paste below
2.7.4
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/myuser/myproject/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/myuser/myproject/ansible/ansible.cfg) = [u'timer', u'profile_roles']
DEFAULT_FORKS(/home/myuser/myproject/ansible/ansible.cfg) = 50
DEFAULT_PRIVATE_KEY_FILE(/home/myuser/myproject/ansible/ansible.cfg) = /home/myuser/myproject/ansible/.ssh/id_rsa
DEFAULT_REMOTE_USER(/home/myuser/myproject/ansible/ansible.cfg) = admin
DEFAULT_STDOUT_CALLBACK(/home/myuser/myproject/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/myuser/myproject/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

Create an inventory with a couple of hosts, one ftd and anything else. The FTD should have the httpapi connection facts specified. Call a playbook specifying the inventory with both hosts, the play is only for the second host. Delegate_to the FTD.

myinventory.yml
```yaml
all:
  children:
    my_group:
      hosts:
        ftd:
          name: 'ftd'
          ansible_host: 'ftd.mydomain'
          ansible_user: admin
          ansible_password: mypassword
          ansible_connection: httpapi
          ansible_network_os: ftd
          ansible_httpapi_use_ssl: True
          ansible_httpapi_ftd_token_path: /api/fdm/v3/fdm/token
          ansible_httpapi_validate_certs: false
          ansible_command_timeout: 360
        another-host:
          name: 'another-host'
          ansible_host: 'another-host.mydomain'
          ansible_user: admin
```

myplaybook.yml
```yaml
- hosts: another-host
  gather_facts: false
  tasks:
    - name: example task to delegate_to ftd host
       setup:
       delegate_to: ftd
```

Call the playbook specifying the inventory.
```yaml
ansible-playbook -i myinventory.yml myplaybook.yml
```

##### EXPECTED RESULTS

Ansible should be able to connect to ftd.mydomain with the httpapi plugin using:
ansible_httpapi_ftd_token_path: /api/fdm/v3/fdm/token
ansible_httpapi_use_ssl: true

In other words, it should connect to: https://ftd.mydomain:443/api/fdm/v3/fdm/token

##### ACTUAL RESULTS
The connection times out and it is clear that the httpapi connection was not using the following defined variables in the inventory ansible_httpapi_ftd_token_path and ansible_httpapi_use_ssl. And uses their default values of ansible_httpapi_ftd_token_path=/api/fdm/v2/fdm/token and ansible_httpapi_use_ssl=false instead of /api/fdm/v3/fdm/token and true respectively.

Other fact values from inventory, like ansible_connection, ansible_password and ansible_host are used correctly.
```paste below
'Could not connect to http://ftd.mydomain:80/api/fdm/v2/fdm/token: timed out'
```

hint: when running Ansible 2.8.3 it does work ok by default.

**Comment by justjais** [comment]
cc. @annikulin can u please look into this issue and update, thanks!

**Comment by annikulin** [comment]
Hi @axarriola, thanks for reporting the issue.

@justjais, I investigated the problem and the `delegate_to` parameter does not work correctly with the HTTPAPI connection type in Ansible 2.7.

Having the following inventory file, 
```
all:
  children:
    my_group:
      hosts:
        ftd:
          name: ftd
          ansible_host: ftd.domain
          ansible_httpapi_port: 12345
          ansible_user: admin
          ansible_password: pass
          ansible_connection: httpapi
          ansible_network_os: ftd
          ansible_httpapi_use_ssl: True
          ansible_httpapi_ftd_token_path: /api/fdm/v3/fdm/token
          ansible_httpapi_validate_certs: False
          ansible_command_timeout: 360
        another-host:
          name: another-host
          ansible_host: another-host.mydomain
          ansible_user: admin
```

and the following playbook:

```
- hosts: another-host
  gather_facts: false
  tasks:
    - name: example task to delegate_to ftd host
      setup:
      delegate_to: ftd
```

its run fails on Ansible 2.7.x:

```
TASK [example task to delegate_to ftd host] **************************************************************************************************************************************
fatal: **[another-host]**: FAILED! => {"msg": "Could not connect to **http://another-host.mydomain**:80/api/fdm/v2/fdm/token: [Errno 8] nodename nor servname provided, or not known"}
```

For some reason, the `ansible_host` variable is incorrect in FTD HTTP API plugin (same applies to `ansible_httpapi_ftd_token_path`). The `delegate_to` parameter does not reset the `ansible_host` value and HTTP API plugin still sends a request to `http://another-host.mydomain` when calling `self.connection.send`.

When I switch to Ansible 2.8.x, everything works as expected: the `ansible_host` is set correctly to the value specified in the inventory file and the playbook works as expected:

```
TASK [example task to delegate_to ftd host] **************************************************************************************************************************************
ok: [**ftd**]
```

@justjais, as there were no changes in [FTD HTTP API plugin](https://github.com/ansible/ansible/commits/stable-2.7/lib/ansible/plugins/httpapi/ftd.py) between 2.7 and 2.8, do you know what could be the reason? Do you know if anything changed to the `delegate_to`/HTTP API connection plugin in general?
