### ISSUE TITLE
apt_repository does not support remove_others

### ISSUE THREAD

**Issue by HOSTED-POWER** [ansible/ansible#61420]
##### SUMMARY
Simply allow the remove_others flag like the apt_repo module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
apt_repository 

##### ADDITIONAL INFORMATION
We use apt_repository a lot, however sometimes we want to update the repo to support higher version. e.g.

deb https://deb.nodesource.com/node_8.x stretch main
deb-src https://deb.nodesource.com/node_8.x stretch main

Has to become:
deb https://deb.nodesource.com/node_10.x stretch main
deb-src https://deb.nodesource.com/node_10.x stretch main

Unfortunately now this change in version always results in:

deb https://deb.nodesource.com/node_8.x stretch main
deb-src https://deb.nodesource.com/node_8.x stretch main
deb https://deb.nodesource.com/node_10.x stretch main
deb-src https://deb.nodesource.com/node_10.x stretch main

Which is not what we expect. We need to get rid of any other contents in this file.

**Comment by sashka** [comment]
apt_repository works with the repo explicitly passed to the module, so everything else is intact. 

The use-case you described may be solved with a playbook, let’s say, upgrade_nodejs.yml to install new apt source and ensure all old versions are removed.

**Comment by HOSTED-POWER** [comment]
> apt_repository works with the repo explicitly passed to the module, so everything else is intact.
> 
> The use-case you described may be solved with a playbook, let’s say, upgrade_nodejs.yml to install new apt source and ensure all old versions are removed.

Thanks for looking into this!

We tried, but we cannot keep track of all versions, for example with varnish we have easily 10 versions and more.

If you can support regex for removal, this could maybe be a solution. However keeping track of any possible version of a software ever released which may or may not exists seems not like an ideal solution unless I'm missing something?

It would be inefficient as well, we simply want to clear the file and fix the repo the way we want, that should be pretty simple with just a single command with the help of remove_others.

If we make an additional command to first remove the file, it would work out, but then the commands would run over and over with any new playbook run. Also not the smartest solution I can think of :)

**Comment by sashka** [comment]
> If we make an additional command to first remove the file, it would work out, but then the commands would run over and over with any new playbook run. Also not the smartest solution I can think of :)

It looks like you actually want to manage your `/etc/apt/sources.list.d/node.list` with `template` module and trigger the package upgrade when `node.list` has changed.

**Comment by HOSTED-POWER** [comment]
We use template a lot, but what is the purpose of the apt_repository then? 

Hence we can template a whole kubernetes config, why would we need any enhanced functions to manage stuff then? Will we solve all our problems from now on with the generic template approach? :)

I don't see how the template is THE solution for our problem, it's just a workaround since this module is unable to setup a clean repo file if it exists already.

**Comment by sashka** [comment]
I’d rather pass this thread to Core Team.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt_repository.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt_repository.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by darkdragon-001** [comment]
Any progress on this?

**Comment by serl** [comment]
Hello, I'm having the exact same issue (but with node 12 to node 14!).

I actually imagined the apt_repository module to work _by default_ in an "exclusive" manner (that is a repo for each file, and if a new repo was give, the file contents would be replaced).

So I guess this should be clarified in the doc. Personally, I prefer what @HOSTED-POWER suggests: add a flag to do either.

**Comment by HOSTED-POWER** [comment]
indeed, it has caused is many headaches because of duplicate configurations after certain upgrades :/ :)

**Comment by a666** [comment]
In other terms this module is not idempotent. A warning in the documentation would be nice, or a flag to

**Comment by a666** [comment]
In other terms this module is not idempotent... In a configuration management system...

2 possible quick fixes:

```yaml
## alternative 1
- name: package | Remove nodesource_nodejs repository since apt_repository is not idempotent
  # also, since #18910 as not been given any attention since 2019 we just delete the file
  file:
    path: /etc/apt/sources.list.d/nodesource_nodejs.list
    state: absent
 changed_when: false

- name: package | Add NodeSource deb repos
  apt_repository:
    filename: nodesource_nodejs
    repo: "{{ item }}"
    state: present
    mode: '0644'
    update_cache: true
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  changed_when: false

## alternative 2 (preferred)
- name: package | Add NodeSource deb repos
  copy:
    mode: 0644
    remote_src: true
    dest: /etc/apt/sources.list.d/nodesource_nodejs.list
    content: |
      deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main
      deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main

#remember to run apt update afterwards
```

**Comment by C0rn3j** [comment]
As per OP, this functionality is already included in a community module `apt_repo` as `remove_others`.
https://docs.ansible.com/ansible/latest/collections/community/general/apt_repo_module.html

I've ran into this myself a few times, and it would be very nice if the functionality could be taken into the core module.

The current module behavior is ___dangerous___ as it can configure repositories for multiple app versions for multiple operating system versions all at the same time.

I see @sashka wanted to pass this to the Core team but I do not see anyone in here commenting on the problem or tagged - hopefully the following is not too rude - @bcoca 

---

For the time being, here's a slightly hacky example playbook for DEB822 compatible .sources that is actually idempotent, using a template:

```yaml
- name: Add Icinga repo
  register: repoadd
  ansible.builtin.template:
    src: repo.j2
    dest: /etc/apt/sources.list.d/icinga.sources
    mode: '0644'

- name: Update package list on all Ubuntu servers
  when: repoadd.changed
  ansible.builtin.apt:
    upgrade: 'no'
    update_cache: true
```

example repo.j2 contents:
```yaml
X-Repolib-Name: Icinga PPA
Types: deb
URIs: https://packages.icinga.com/{{ ansible_distribution | lower }}
Suites: icinga-{{ ansible_distribution_release }}
Components: main
Signed-By: /etc/apt/keyrings/icinga.gpg
```

If the Signed-By clause is foreign to you, the former approach of applying armored keys for all repositories was only deprecated recently, see https://stackoverflow.com/a/72548342/8962143
