### ISSUE TITLE
vmware_cluster_ha support for advanced configuration parameters

### ISSUE THREAD

**Issue by patede** [ansible/ansible#61421]
##### SUMMARY
The vmware_cluster_ha module should support advanced configuration parameters in a generic way. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_cluster_ha

##### ADDITIONAL INFORMATION
The feature would allow advanced configurations like isolation address handling.

```yaml
name: Enable HA with multiple custom isolation addresses for stretched vSAN
  vmware_cluster_ha:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: datacenter
    cluster_name: cluster
    enable_ha: yes
    configuration_parameters:
      das.usedefaultisolationaddress: false
      das.isolationaddress0: '{{ primary_isolation_address }}'
      das.isolationaddress1: '{{ secondary_isolation_address }}'
  delegate_to: localhost
```
