### ISSUE TITLE
win_package does not use literal path for product_id/creates_path verification

### ISSUE THREAD

**Issue by iturovsky** [ansible/ansible#61434]
##### SUMMARY

In some cases package has product_id in form of arbitrary string instead of guid , see 7-Zip in example https://docs.ansible.com/ansible/latest/modules/win_package_module.html. 
If this string contains wildcard characters, win_package will not be able to see that package is already installed either with _product_id_ or _creates_path_ parameters

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_package
##### ANSIBLE VERSION

```paste below
ansible 2.8.4
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'timer', u'log_plays']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml

```

##### OS / ENVIRONMENT

Ansible controller  - Debian 9
Managed node - Windows 2012 R2

##### STEPS TO REPRODUCE

* Install Cumulative Update Package 1 for Microsoft AppFabric 1.1 for Windows Server (KB 2671763) https://www.microsoft.com/en-us/download/details.aspx?id=29241
* When it is installed, it creates path in registry 
```powershell
HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Windows Server AppFabric v1.1 CU1[KB 2671763]LDR
```

```yaml
- name: Cumulative Update Package 1 for Microsoft AppFabric 1.1 for Windows Server (KB 2671763)
  win_package:
    product_id: 'Windows Server AppFabric v1.1 CU1[KB 2671763]LDR'
    expected_return_code: 0,3010
    state: present
    path: '{{ wss_prerequisites_local_path }}\AppFabric1.1-RTM-KB2671763-x64-ENU.exe'
    arguments: /quiet
```

##### EXPECTED RESULTS

The task above reports _ok_ on second run

##### ACTUAL RESULTS

The task above reports _changed_ every time

```paste below

```
#### OTHER NOTES
It seems to be caused by using Test-Path with Path parameter instead of LiteralPath
```powershell
$path='HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Windows Server AppFabric v1.1 CU1[KB 2671763]LDR'
Test-Path -path $path # this returns $false
Test-Path -literalpath $path # this returns $true
```
