### ISSUE TITLE
gcp_compute_instance_group is not working with instances

### ISSUE THREAD

**Issue by mart3051** [ansible/ansible#61445]
##### SUMMARY

gcp_compute_instance_group is failing with below playbook.
However it works if in instances the format is selfLink: <<hard coded link>>

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance_group
##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/martand/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /home/martand/AnsibleLogs/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/martand/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'host_list', u'script', u'yaml', u'ini', u'auto', u'gcp_compute']

```

##### OS / ENVIRONMENT

Ununtu 19.04

##### STEPS TO REPRODUCE

Try the below playbook with -vvv option

```yaml
 - name: Create n master  Compute instance
             gcp_compute_instance:
                     state: present
                     name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}"
                     machine_type: "{{ lookup('env','MASTERSIZE') }}"
                     zone: "{{ lookup('env','DEFAULTZONE') }}"
                     project: "{{ lookup('env','PROJECTID') }}"
                     auth_kind: serviceaccount
                     service_account_file:  "{{ lookup('env','SERVICEAF') }}"
                     tags:
                             items:
                                  - "{{ lookup('env','CLUSTERID') }}-master"
                                  - "{{ lookup('env','CLUSTERID') }}-node"
                     network_interfaces:
                           - network: "{{ network }}"
                             subnetwork: "{{ subNetwork  }}"
                     scopes:
                             - https://www.googleapis.com/auth/cloud.useraccounts.readonly
                             - https://www.googleapis.com/auth/compute
                             - https://www.googleapis.com/auth/devstorage.read_write
                             - https://www.googleapis.com/auth/logging.write
                             - https://www.googleapis.com/auth/monitoring.write
                             - https://www.googleapis.com/auth/service.management.readonly
                             - https://www.googleapis.com/auth/servicecontrol
                     metadata:
                             startup-script-url: gs://smarclussetupsh/master.sh
                             ocp-cluster: "{{ lookup('env','CLUSTERID') }}" 
                             smarclus-type: master 
                     disks:
                     - auto_delete: 'true'
                       boot: 'true'
                       device_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}"
                       initialize_params:
                                 disk_size_gb: "{{ lookup('env','MASTERDISKSIZE') }}"
                                 disk_type: pd-ssd
                                 source_image: projects/rhel-cloud/global/images/family/rhel-7
                     - auto_delete: 'true'
                       boot: 'false'
                       device_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}-local"
                       initialize_params:
                                 disk_size_gb: "{{ lookup('env','MASTERLOCALSIZE') }}"
                                 disk_type: pd-standard
                                 disk_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}-local"
                     - auto_delete: 'true'
                       boot: 'false'
                       device_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}-containers"
                       initialize_params:
                                 disk_size_gb: "{{ lookup('env','MASTERCONTAINERSSIZE') }}"
                                 disk_type: pd-standard
                                 disk_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}-containers"
                     - auto_delete: 'true'
                       boot: 'false'
                       device_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}-etcd"
                       initialize_params:
                                 disk_size_gb: "{{ lookup('env','ETCDSIZE') }}"
                                 disk_type: pd-standard
                                 disk_name: "{{ lookup('env','CLUSTERID') }}-master-{{ mIndx }}-etcd"
             with_sequence: start=1 end={{ lookup('env','MASTER_NODE_COUNT') }} stride=1
             loop_control:
                     index_var: mIndx
             register: masterInstances

           - name: Master load balancer compute_instance_group
             gcp_compute_instance_group:
                     name: "{{ lookup('env','CLUSTERID') }}-master"
                     zone: "{{ lookup('env','DEFAULTZONE') }}"
                     network: "{{ network }}"
                     project: "{{ lookup('env','PROJECTID') }}"
                     auth_kind: serviceaccount
                     service_account_file:  "{{ lookup('env','SERVICEAF') }}"
                     state: present
                     instances:
                     - "{{  masterInstances }}"
                     named_ports:
                         - name: ocp-api
                           port: 443
             register: masterInstanceGroup
```

##### EXPECTED RESULTS

Instance group is properly created

##### ACTUAL RESULTS

The instance_group creation task failed

```paste below
TASK [Master load balancer compute_instance_group] *********************************************************************************************************************************************************
task path: /home/martand/AnsiblePB/openShiftInfraSetup.yml:557
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: martand
<127.0.0.1> EXEC /bin/sh -c 'echo ~martand && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464 `" && echo ansible-tmp-1567000907.09-41266981009464="` echo /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/google/gcp_compute_instance_group.py
<127.0.0.1> PUT /home/martand/.ansible/tmp/ansible-local-201409Z6WFn/tmpns5RHS TO /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464/AnsiballZ_gcp_compute_instance_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464/ /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464/AnsiballZ_gcp_compute_instance_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464/AnsiballZ_gcp_compute_instance_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/martand/.ansible/tmp/ansible-tmp-1567000907.09-41266981009464/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_gcp_compute_instance_group_payload_YOnkzL/ansible_gcp_compute_instance_group_payload.zip/ansible/module_utils/gcp_utils.py", line 229, in raise_for_status
    response.raise_for_status()
  File "/home/martand/.local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_kind": "serviceaccount", 
            "description": null, 
            "instances": [
                {
                    "changed": false, 
                    "msg": "All items completed", 
                    "results": [
                        {
                            "ansible_index_var": "mIndx", 
                            "ansible_loop_var": "item", 
                            "changed": false, 
                            "cpuPlatform": "Intel Broadwell", 
                            "creationTimestamp": "2019-08-28T05:50:40.116-07:00", 
                            "deletionProtection": false, 
                            "disks": [
                                {
                                    "autoDelete": true, 
                                    "boot": true, 
                                    "deviceName": "smarclus-master-0", 
                                    "index": 0, 
                                    "interface": "SCSI", 
                                    "kind": "compute#attachedDisk", 
                                    "licenses": [
                                        "https://www.googleapis.com/compute/v1/projects/rhel-cloud/global/licenses/rhel-7-server"
                                    ], 
                                    "mode": "READ_WRITE", 
                                    "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/disks/smarclus-master-0", 
                                    "type": "PERSISTENT"
                                }, 
                                {
                                    "autoDelete": true, 
                                    "boot": false, 
                                    "deviceName": "smarclus-master-0-local", 
                                    "index": 1, 
                                    "interface": "SCSI", 
                                    "kind": "compute#attachedDisk", 
                                    "mode": "READ_WRITE", 
                                    "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/disks/smarclus-master-0-local", 
                                    "type": "PERSISTENT"
                                }, 
                                {
                                    "autoDelete": true, 
                                    "boot": false, 
                                    "deviceName": "smarclus-master-0-containers", 
                                    "index": 2, 
                                    "interface": "SCSI", 
                                    "kind": "compute#attachedDisk", 
                                    "mode": "READ_WRITE", 
                                    "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/disks/smarclus-master-0-containers", 
                                    "type": "PERSISTENT"
                                }, 
                                {
                                    "autoDelete": true, 
                                    "boot": false, 
                                    "deviceName": "smarclus-master-0-etcd", 
                                    "index": 3, 
                                    "interface": "SCSI", 
                                    "kind": "compute#attachedDisk", 
                                    "mode": "READ_WRITE", 
                                    "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/disks/smarclus-master-0-etcd", 
                                    "type": "PERSISTENT"
                                }
                            ], 
                            "failed": false, 
                            "id": "6815530986865673840", 
                            "invocation": {
                                "module_args": {
                                    "auth_kind": "serviceaccount", 
                                    "can_ip_forward": null, 
                                    "disks": [
                                        {
                                            "auto_delete": true, 
                                            "boot": true, 
                                            "device_name": "smarclus-master-0", 
                                            "disk_encryption_key": null, 
                                            "index": null, 
                                            "initialize_params": {
                                                "disk_name": null, 
                                                "disk_size_gb": 20, 
                                                "disk_type": "pd-ssd", 
                                                "source_image": "projects/rhel-cloud/global/images/family/rhel-7", 
                                                "source_image_encryption_key": null
                                            }, 
                                            "interface": null, 
                                            "mode": null, 
                                            "source": null, 
                                            "type": null
                                        }, 
                                        {
                                            "auto_delete": true, 
                                            "boot": false, 
                                            "device_name": "smarclus-master-0-local", 
                                            "disk_encryption_key": null, 
                                            "index": null, 
                                            "initialize_params": {
                                                "disk_name": "smarclus-master-0-local", 
                                                "disk_size_gb": 30, 
                                                "disk_type": "pd-standard", 
                                                "source_image": null, 
                                                "source_image_encryption_key": null
                                            }, 
                                            "interface": null, 
                                            "mode": null, 
                                            "source": null, 
                                            "type": null
                                        }, 
                                        {
                                            "auto_delete": true, 
                                            "boot": false, 
                                            "device_name": "smarclus-master-0-containers", 
                                            "disk_encryption_key": null, 
                                            "index": null, 
                                            "initialize_params": {
                                                "disk_name": "smarclus-master-0-containers", 
                                                "disk_size_gb": 20, 
                                                "disk_type": "pd-standard", 
                                                "source_image": null, 
                                                "source_image_encryption_key": null
                                            }, 
                                            "interface": null, 
                                            "mode": null, 
                                            "source": null, 
                                            "type": null
                                        }, 
                                        {
                                            "auto_delete": true, 
                                            "boot": false, 
                                            "device_name": "smarclus-master-0-etcd", 
                                            "disk_encryption_key": null, 
                                            "index": null, 
                                            "initialize_params": {
                                                "disk_name": "smarclus-master-0-etcd", 
                                                "disk_size_gb": 50, 
                                                "disk_type": "pd-standard", 
                                                "source_image": null, 
                                                "source_image_encryption_key": null
                                            }, 
                                            "interface": null, 
                                            "mode": null, 
                                            "source": null, 
                                            "type": null
                                        }
                                    ], 
                                    "guest_accelerators": null, 
                                    "label_fingerprint": null, 
                                    "machine_type": "n1-standard-2", 
                                    "metadata": {
                                        "ocp-cluster": "smarclus", 
                                        "smarclus-type": "master", 
                                        "startup-script-url": "gs://smarclussetupsh/master.sh"
                                    }, 
                                    "min_cpu_platform": null, 
                                    "name": "smarclus-master-0", 
                                    "network_interfaces": [
                                        {
                                            "access_configs": null, 
                                            "alias_ip_ranges": null, 
                                            "network": {
                                                "autoCreateSubnetworks": false, 
                                                "changed": false, 
                                                "creationTimestamp": "2019-08-28T03:24:45.258-07:00", 
                                                "failed": false, 
                                                "id": "1817437395156199554", 
                                                "kind": "compute#network", 
                                                "name": "smarclus-net", 
                                                "routingConfig": {
                                                    "routingMode": "REGIONAL"
                                                }, 
                                                "selfLink": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/networks/smarclus-net", 
                                                "subnetworks": [
                                                    "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-west1/subnetworks/smarclus-subnet"
                                                ]
                                            }, 
                                            "network_ip": null, 
                                            "subnetwork": {
                                                "changed": false, 
                                                "creationTimestamp": "2019-08-28T03:25:09.821-07:00", 
                                                "failed": false, 
                                                "fingerprint": "LXfuBr-cxhc=", 
                                                "gatewayAddress": "10.240.0.1", 
                                                "id": "1135099063281903722", 
                                                "ipCidrRange": "10.240.0.0/24", 
                                                "kind": "compute#subnetwork", 
                                                "name": "smarclus-subnet", 
                                                "network": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/networks/smarclus-net", 
                                                "privateIpGoogleAccess": false, 
                                                "region": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-west1", 
                                                "selfLink": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-west1/subnetworks/smarclus-subnet"
                                            }
                                        }
                                    ], 
                                    "project": "xxxxxxxx", 
                                    "scheduling": null, 
                                    "scopes": [
                                        "https://www.googleapis.com/auth/cloud.useraccounts.readonly", 
                                        "https://www.googleapis.com/auth/compute", 
                                        "https://www.googleapis.com/auth/devstorage.read_write", 
                                        "https://www.googleapis.com/auth/logging.write", 
                                        "https://www.googleapis.com/auth/monitoring.write", 
                                        "https://www.googleapis.com/auth/service.management.readonly", 
                                        "https://www.googleapis.com/auth/servicecontrol"
                                    ], 
                                    "service_account_contents": null, 
                                    "service_account_email": null, 
                                    "service_account_file": "xxxxxxxx-xxxxxxxx.json", 
                                    "service_accounts": null, 
                                    "state": "present", 
                                    "status": null, 
                                    "tags": {
                                        "fingerprint": null, 
                                        "items": [
                                            "smarclus-master", 
                                            "smarclus-node"
                                        ]
                                    }, 
                                    "zone": "us-west1-a"
                                }
                            }, 
                            "item": "1", 
                            "kind": "compute#instance", 
                            "labelFingerprint": "42WmSpB8rSM=", 
                            "mIndx": 0, 
                            "machineType": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/machineTypes/n1-standard-2", 
                            "metadata": {
                                "ocp-cluster": "smarclus", 
                                "smarclus-type": "master", 
                                "startup-script-url": "gs://smarclussetupsh/master.sh"
                            }, 
                            "name": "smarclus-master-0", 
                            "networkInterfaces": [
                                {
                                    "fingerprint": "gKXIKTFzVbc=", 
                                    "kind": "compute#networkInterface", 
                                    "name": "nic0", 
                                    "network": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/networks/smarclus-net", 
                                    "networkIP": "10.240.0.13", 
                                    "subnetwork": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-west1/subnetworks/smarclus-subnet"
                                }
                            ], 
                            "scheduling": {
                                "automaticRestart": true, 
                                "onHostMaintenance": "MIGRATE", 
                                "preemptible": false
                            }, 
                            "selfLink": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/instances/smarclus-master-0", 
                            "startRestricted": false, 
                            "status": "RUNNING", 
                            "tags": {
                                "fingerprint": "kHBzZC7q_v0=", 
                                "items": [
                                    "smarclus-master", 
                                    "smarclus-node"
                                ]
                            }, 
                            "zone": "https://www.googleapis.com/compute/v1/projects/xxxxxx/zones/us-west1-a"
                        }
                    ]
                }
            ], 
            "name": "smarclus-master", 
            "named_ports": [
                {
                    "name": "ocp-api", 
                    "port": 443
                }
            ], 
            "network": {
                "autoCreateSubnetworks": false, 
                "changed": false, 
                "creationTimestamp": "2019-08-28T03:24:45.258-07:00", 
                "failed": false, 
                "id": "1817437395156199554", 
                "kind": "compute#network", 
                "name": "smarclus-net", 
                "routingConfig": {
                    "routingMode": "REGIONAL"
                }, 
                "selfLink": "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/global/networks/smarclus-net", 
                "subnetworks": [
                    "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/regions/us-west1/subnetworks/smarclus-subnet"
                ]
            }, 
            "project": "xxxxxxxx", 
            "region": null, 
            "scopes": [
                "https://www.googleapis.com/auth/compute"
            ], 
            "service_account_contents": null, 
            "service_account_email": null, 
            "service_account_file": "xxxxxxxx-xxxxxxxx.json", 
            "state": "present", 
            "subnetwork": null, 
            "zone": "us-west1-a"
        }
    }, 
    "msg": "GCP returned error: {u'error': {u'code': 400, u'message': u\"Invalid value for field 'instances[0].instance': ''. The URL is malformed.\", u'errors': [{u'domain': u'global', u'message': u\"Invalid value for field 'instances[0].instance': ''. The URL is malformed.\", u'reason': u'invalid'}]}}"
}

```
However instance group creation works if the instance group creation playbook is modified to below it works.

```
 - name: Master load balancer compute_instance_group
             gcp_compute_instance_group:
                     name: "{{ lookup('env','CLUSTERID') }}-master"
                     zone: "{{ lookup('env','DEFAULTZONE') }}"
                     network: "{{ network }}"
                     project: "{{ lookup('env','PROJECTID') }}"
                     auth_kind: serviceaccount
                     service_account_file:  "{{ lookup('env','SERVICEAF') }}"
                     state: present
                     instances:
                     - selfLink: "https://www.googleapis.com/compute/v1/projects/xxxxxxxx/zones/us-west1-a/instances/smarclus-master-0"
                     named_ports:
                         - name: ocp-api
                           port: 443
             register: masterInstanceGroup
```

I would not like the selfLink to be hard coded. It should have taken the selfLink on its own like other modules take
