### ISSUE TITLE
OpenSSL_CSR: Add custom OIDs to CSR

### ISSUE THREAD

**Issue by gvanheyst** [ansible/ansible#61473]
##### SUMMARY
I would like to add custom OIDs to OpenSSL_CSR. 
Particularly focussing on OIDs that are transient like the "challengePassword" (OID 1.2.840.113549.1.9.7) for example.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- ansible/modules/crypto/openssl_csr.py
_(i guess)_
##### ADDITIONAL INFORMATION
It would help with auto-enrollment of certificates using NDES or Puppet extensions.

```yaml
 - name: Generate an OpenSSL public key using RSA.
   openssl_csr:
    path: "./csr/{{ csr }}.rsa.csr"
    privatekey_path: ./keys/{{ key_rsa }}
    common_name: "{{ san }}"
    subject_alt_name: "DNS:{{ san.split('.')[0] | lower }},DNS:{{ san }}"
    **custom_oid:
     - "1.2.840.113549.1.9.7:<value>"**
    basic_constraints:
     - 'CA:FALSE'
```
