### ISSUE TITLE
dict order matters for eos_l3_interfaces data model

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#61490]
##### SUMMARY
it appears we will always say *changed* and issue commands if the order is not the same as the read in data model

to be more specific->
```
config:
  - ipv4:
    - address: 10.10.10.1/24
    ipv6:
    - address: fc00::100/64
    - address: fc00::101/64
    name: Loopback100
```

will be treated differently than
```
  - ipv4:
    - address: 10.10.10.1/24
    name: Loopback100
    ipv6:
    - address: fc00::100/64
    - address: fc00::101/64
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_l3_interfaces

##### ANSIBLE VERSION
```paste below
ansible 2.9.0.dev0
  config file = /home/student1/.ansible.cfg
  configured module search path = [u'/home/student1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/student1/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/home/student1/.ansible.cfg) = [u'/home/student1/networking-workshop/lab_inventory/hosts']
DEFAULT_STDOUT_CALLBACK(/home/student1/.ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/student1/.ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/student1/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/.ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/student1/.ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/student1/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

##### STEPS TO REPRODUCE
this Ansible Playbook will always report changed:
```yaml
---
- hosts: rtr2
  module_defaults:
    eos_facts:
      gather:network_resources:
      - l3_interfaces
  gather_facts: true
  vars:
    config:
    - ipv4:
      - address: 10.10.10.1/24
      name: loopback100
      ipv6:
      - address: fc00::100/64
      - address: fc00::101/64
  tasks:
    - eos_l3_interfaces:
        config: "{{config}}"
        state: merged
      register: result

    - name: ensure config did not change
      assert:
        that: not result.changed
```

##### EXPECTED RESULTS
run it twice, the 2nd time will report OK (not changed)

##### ACTUAL RESULTS
it won't match and re-issue all commands, here is `-v` output

```paste below
[student1@ansible ~]$ ansible-playbook test.yml  -v
Using /home/student1/.ansible.cfg as config file

PLAY [rtr2] *********************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
ok: [rtr2]

TASK [eos_l3_interfaces] ********************************************************************************************************
changed: [rtr2] => changed=true
  after:
  - ipv4:
    - address: dhcp
    name: Ethernet1
  - ipv4:
    - address: 192.168.2.102/24
    name: Loopback0
  - ipv4:
    - address: 10.2.2.102/24
    name: Loopback1
  - ipv4:
    - address: 10.10.10.1/24
    ipv6:
    - address: fc00::100/64
    - address: fc00::101/64
    name: Loopback100
  - ipv4:
    - address: 10.101.101.2/24
    name: Tunnel0
  - ipv4:
    - address: 10.200.200.2/24
    name: Tunnel1
  before:
  - ipv4:
    - address: dhcp
    name: Ethernet1
  - ipv4:
    - address: 192.168.2.102/24
    name: Loopback0
  - ipv4:
    - address: 10.2.2.102/24
    name: Loopback1
  - ipv4:
    - address: 10.10.10.1/24
    ipv6:
    - address: fc00::100/64
    - address: fc00::101/64
    name: Loopback100
  - ipv4:
    - address: 10.101.101.2/24
    name: Tunnel0
  - ipv4:
    - address: 10.200.200.2/24
    name: Tunnel1
  commands:
  - interface loopback100
  - ip address 10.10.10.1/24
  - ipv6 address fc00::100/64
  - ipv6 address fc00::101/64

TASK [ensure config did not change] *********************************************************************************************
fatal: [rtr2]: FAILED! => changed=false
  assertion: not result.changed
  evaluated_to: false
  msg: Assertion failed

PLAY RECAP **********************************************************************************************************************
rtr2                       : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
