### ISSUE TITLE
Provide a way to set infinite timeout when using async_status

### ISSUE THREAD

**Issue by srajtiwari** [ansible/ansible#61503]
##### SUMMARY
Provide a way to set infinite timeout when using "async_status". For the "async_status" module, retries defaults to 3 retries if omitted. The is no way to set async_status to keep retrying until the job is finished. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
async_status

##### ADDITIONAL INFORMATION

This feature will be used for kicking off multiple long running jobs asynchronously, then check the status of the jobs periodically until all jobs are finished. This feature is needed due to the long running nature some jobs for our use case. If implemented as requested this feature will solve the problem of determining the upper bound for retries. 
  

```yaml
- name: Wait
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: _jobs
  until: _jobs.finished
  delay: 15
  retries: 300
  with_items: "{{ _create_clusters.results }}"

```
