### ISSUE TITLE
Fail on skipped tasks

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [ansible/ansible#61537]
##### SUMMARY

When running certain tasks that should be skipped in the playbook, a fatal error will be generated instead of skipping it.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [ u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
```

##### OS / ENVIRONMENT

```
Linux 11105a1c4daa 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

1. Create the playbook file as `playbook.yml` (see below).
2. run `ansible-playbook playbook.yml`

```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - stat:
        path: "{{ playbook_dir }}"
      register: reg
      when: False

    - name: Apply templates
      debug: var=item
      with_items:
        - "{{ reg | map(attribute='') | select('search','a') | list }}"
      when: False

```

##### EXPECTED RESULTS

```
PLAYBOOK: playbook.yml ******************************************************
Positional arguments: playbook.yml
become_method: sudo
inventory: (u'/etc/ansible/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in playbook.yml

PLAY [localhost] ******************************************************
META: ran handlers

TASK [stat] ******************************************************
task path: /playbook.yml:5
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [Apply templates] ******************************************************
task path: /playbook.yml:10
skipping: [localhost] => {}
META: ran handlers
META: ran handlers

```

##### ACTUAL RESULTS

```
PLAYBOOK: playbook.yml ******************************************************
Positional arguments: playbook.yml
become_method: sudo
inventory: (u'/etc/ansible/hosts',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in playbook.yml

PLAY [localhost] ******************************************************
META: ran handlers

TASK [stat] ******************************************************
task path: /playbook.yml:5
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [Apply templates] ******************************************************
task path: /playbook.yml:10
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ reg | map(attribute='') | select('search','a') | list }}): expected string or buffer"
}

```

##### EXTRA INFO

Affects version all versions up to `2.8.4`. The nightly build of `2.9` produces the expected results.
