### ISSUE TITLE
Add line number to TemplateRuntimeError

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#61533]
##### SUMMARY
Please add the position within the Template file where a TemplateRuntimeError occurred.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
templating engine
template module
jinja2

##### ADDITIONAL INFORMATION
Currently a TemplateRuntimeError does not show the actual position it failed.
For long and complex templates having the actual line number that caused the error will significantly improve troubleshooting time.

```yaml
failed: [foobar] (item={'src': 'foo.conf.j2', 'dest': '/etc/foo/foo.conf'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "dest": "/etc/foo/foo.conf",
        "src": "foo.conf.j2"
    },
    "msg": "TemplateRuntimeError: no test named 'ipaddr'"
}
```
