### ISSUE TITLE
Region option to use with gcp_compute_instance_group_manager_facts 

### ISSUE THREAD

**Issue by willianccs** [ansible/ansible#61548]
##### SUMMARY
I trying to get a list of my instance group managers on all zones, but regional instance groups won't show.

##### ISSUE TYPE
- Module option "region".

##### COMPONENT NAME
gcp_compute_instance_group_manager_facts
gcp_compute_instance_group_manager_info

##### ADDITIONAL INFORMATION
Get instance group manager for a regional (multi-zone) instance group manager.

ansible 2.8.2
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

```yaml
- hosts: runner
  gather_facts: no
  connection: local

  vars:
    project_name: "project-dummy"
    project_credentials: "~/.gcp/projects/credentials.json"
    region: us-central1
    zones:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f

  - name: "Get instance group facts"
    gcp_compute_instance_group_manager_facts:
      zone: "{{ item }}"
      # filters:
      # - name = daemon
      # - name = backend
      project: "{{ project_name }}"
      auth_kind: serviceaccount
      service_account_file: "{{ project_credentials }}"
    register: igrp_results
    loop: "{{ zones }}"

```
