### ISSUE TITLE
Add examples for jinja2 advanced data manipulation with loops

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#61597]
##### SUMMARY
In irc often questions about advanced forms of data manipulation with registered variables inside lists arise.
It is by now documented how to do it with "normal return values", but as soon as there is a loop all examples fall apart. So we may need to provide some more examples.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
jinja2 data manipulation

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
ArchLinux

##### ADDITIONAL INFORMATION

Common problems are:
* most jinja2 filters cannot be applied to each element within the list.
* inability of mapping the loop item with specific elements of the list.
* Referencing items within this structure
* Writing logic like:
```
- module_a:
    do_foo: "with_Bar_{{ item }}"
  register: done_foo
  loop:
    - Project_A
    - Project_B
    - Project_C
- module_b:
    do_bar: "with_Foo_{{ item }}"
  loop: "{{ done_foo.results }}"
- add_host:
# And now trying to use properties of one of the loop elements to add host facts when adding a new host
# Or trying to map attributes of one element from the list with the wanted host (e.g. dict(keys_list | zip(values_list)) but with custom conditions (the one where a specific sub item has a specific value) and not using the position in the list)
```

Common solutions:
* Using a multiple tasks files and doing things like:
```
# main.yml
- include: 2nd.yml
  loop:
    - item001
    - item002
    - item003
# 2nd.yml
- debug:
    msg: "{{ item }}"
```
* Refactoring the whole playbook logic (maybe some guidance could be helpfull)
* Writing extremely complex and hardly readable/maintainable roles e.g. like I did a year ago when I first encountered this problem myself (example: https://chaos.expert/agowa338-ansible/ansible-gitlab-runner-dockerized/tree/master/tasks)

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
>most jinja2 filters cannot be applied to each element within the list.
You can use the `map` to apply other filters to elements of a list

>inability of mapping the loop item with specific elements of the list.
Similar to map, you have `select`, `reject`, `selectattr` and `rejectattr` filters that allow you to get a subset of elements of a list.

**Comment by agowa338** [comment]
I was referring to the inability of the user to apply the techniques, not a technical limitation ;-)

The main goal of this issue is to "transfer the way of thinking" for this kind of manipulation and I'm not quite certain how that could be approached (hopefully someone has a suggestion/idea) except doing step by step guides for one or two complex api interactions (which tbh is not that great of an idea)...

Basically the whole topic of list comprehensions needs to be "thought" somehow.

I think that the sheer presence of the outer list could be a mental barrier that we may need to break before referencing back to common things, as it changes the expression dramatically.

E.g. compare these examples:
```
foo:
  - id: 200
    name: bar
  - id: 210
    name: lorem
  - id: 300
    name: ipsum
```
Foo contains the return data of a previous task. And I want to get the name of the element with id 300. Therefore I use the jinja expression `foo|selectattr("id",300)`.

If the task providing this structure was executed with a loop the structure looks like:
```
foo:
  results:
    - Name: Foo
      - id: 200
        name: bar
      - id: 210
        name: lorem
      - id: 300
        name: ipsum
    - Name: Bar
      - id: 200
        name: dolar
      - id: 210
        name: sit
      - id: 300
        name: amen
```
Now the task of getting the element with id 300 seam to be an impossible challenge if one does not know list comprehension.

And if we try to use this structure for e.g. crafting a response it becomes even more tedious, as we need a list too loop over. E.g. we want to have ["Foo", "Bar"] for the loop and the tree underneath easily accessible for crafting the response or we need to compare these two trees etc...
