### ISSUE TITLE
Override and Replace state not behaving ideally for Iosxr_l3_interfaces 

### ISSUE THREAD

**Issue by justjais** [ansible/ansible#61600]
##### SUMMARY

For the Replace and Override use case, where `secondary ip` is already configured on to the device but in override and replace operation user tries to configure only IP without setting any secondary IP in that case already existing IP was not entirely replaced/overridden coz the new IP mentioned in play was set but the `secondary ip` was also coming as configured.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_l3_interfaces

##### ANSIBLE VERSION

```paste below
2.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

iosxr

##### STEPS TO REPRODUCE

```
```
##### EXPECTED RESULTS

Without ISSUE `no ipv4 address` command fired for interface `GigabitEthernet0/0/0/1`
```
before:
    - name: Loopback888
    - name: Loopback999
    - ipv4:
      - address: 198.51.100.1 255.255.255.0
      ipv6:
      - address: 2001:db8::/32
      name: GigabitEthernet0/0/0/0
    - ipv4:
      - address: 192.0.2.1 255.255.255.0
      - address: 192.0.2.2 255.255.255.0
        secondary: true
      name: GigabitEthernet0/0/0/1

  commands:
    - "interface GigabitEthernet0/0/0/0"
    - "no ipv4 address"
    - "no ipv6 address"
    - "interface GigabitEthernet0/0/0/1"
    - "no ipv4 address"
    - "ipv4 address 198.51.102.1 255.255.255.0"
    - "ipv6 address 2001:db8:1::/64"

  after:
    - name: Loopback888
    - name: Loopback999
    - ipv4:
      - address: 198.51.102.1 255.255.255.0
      ipv6:
      - address: 2001:db8:1::/64
      name: GigabitEthernet0/0/0/1

```

##### ACTUAL RESULTS

With Override, ISSUE
```
before:
    - name: Loopback888
    - name: Loopback999
    - ipv4:
      - address: 198.51.100.1 255.255.255.0
      ipv6:
      - address: 2001:db8::/32
      name: GigabitEthernet0/0/0/0
    - ipv4:
      - address: 192.0.2.1 255.255.255.0
      - address: 192.0.2.2 255.255.255.0
        secondary: true
      name: GigabitEthernet0/0/0/1

  commands:
    - "interface GigabitEthernet0/0/0/0"
    - "no ipv4 address"
    - "no ipv6 address"
    - "interface GigabitEthernet0/0/0/1"
    - "ipv4 address 198.51.102.1 255.255.255.0"
    - "ipv6 address 2001:db8:1::/64"

  after:
    - name: Loopback888
    - name: Loopback999
    - ipv4:
      - address: 198.51.102.1 255.255.255.0
      - address: 192.0.2.2 255.255.255.0
        secondary: true
      ipv6:
      - address: 2001:db8:1::/64
      name: GigabitEthernet0/0/0/1
```

```paste below

```
