### ISSUE TITLE
!!null  / ~ not null

### ISSUE THREAD

**Issue by Poil** [ansible/ansible#61602]
##### SUMMARY
Hi,

I'm not sure if it's a bug or if I do something wrong
I have a role
```
- name: "start {{ item.service_name }}.docker"
  tags: always
  become: true
  docker_container:
    name: "{{ item.service_name }}"
    image: "{{ docker_registry }}/{{ item.image_name }}:{{ item.image_version }}"
    networks: "{{ item.networks }}"
    dns_servers: ["{{ ansible_default_ipv4.address }}"]
    dns_opts: ['use-vc']
    volumes: "{{ item.volumes }}"
    published_ports: "{{ item.published_ports }}"
    restart_policy: "unless-stopped"
    env: "{{ item.env }}"
    labels: "{{ item.env }}"
    capabilities: "{{ item.capabilities }}"
```

In my playbook, if I declare a capabilities/env/published_ports it works, but if I try to declare a "None" (because the default value is None, https://github.com/ansible/ansible-modules-core/blob/devel/cloud/docker/docker_container.py), it does not work, ' \r\n' is pass from the role do the docker_container module. I tried `!!null` / `~` / `key:` and also a `key: false` with | default(!null) I'm unable to have it works.

```
    - include_role:
        name: docker_httpd
      tags: vpnssl,container,apigw
      vars:
        docker_registry: "{{ docker.local_registry_vpnssl }}"
      loop:
        - service_name: apigw
          service_tags: "apigw"
          (...)
          capabilities:
            - net_bind_service
```

Is there a way to pass a Null value from a playbook via a role to a module ?
Actually I need to duplicate my role definition and add a `when: capabilities` but this is so ugly ...
If it's not possible why we don't set default value to False in place of None ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```paste below
ansible 2.8.4
```
Best regards,
