### ISSUE TITLE
os_coe_cluster are not idempotent

### ISSUE THREAD

**Issue by panticz** [ansible/ansible#61608]
##### SUMMARY
os_coe_cluster module generates a new cluster with each execution

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_coe_cluster

##### ANSIBLE VERSION
2.8.4

##### STEPS TO REPRODUCE

```yaml
- name: Create Kubernetes cluster
  os_coe_cluster:
    name: foo-cluster1
    cluster_template_id: k8s-template1
    keypair: foo-key
    master_count: 1
    node_count: 2
```

##### EXPECTED RESULTS
No new cluster is created if a cluster with the parameter `name` (e.g "foo-cluster1") already exists

##### ACTUAL RESULTS
```
$ openstack coe cluster list
+--------------------------------------+---------- ---+---------+------------+--------------+--------------------+---------------+
| uuid                                 | name         | keypair | node_count | master_count | status             | health_status |
+--------------------------------------+--------------+---------+------------+--------------+--------------------+---------------+
| 818dbb63-7d45-4aca-aea8-8c61235e716c | foo-cluster1 | foo-key |          2 |            1 | CREATE_IN_PROGRESS |               |
| f1125fa6-f008-44c9-932c-4c19557e31d2 | foo-cluster1 | foo-key |          2 |            1 | CREATE_IN_PROGRESS |               |
+--------------------------------------+--------------+---------+------------+--------------+--------------------+---------------+
```
