### ISSUE TITLE
ansible_python_interpreter with local_action broken by recent commit

### ISSUE THREAD

**Issue by nikut** [ansible/ansible#6161]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

CentOS 5.9 with a Python 2.7.3 virtual environment for Ansible
##### Summary:

I believe the handling of ansible_python_interpreter when running a local_action was broken by this recent commit: https://github.com/ansible/ansible/commit/4af1d6098b35c7996d046c395650c497a313b733. 
##### Steps To Reproduce:

Playbook:

```

---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Test action
      action: debug var=ansible_python_interpreter
    - name: Test local_action
      local_action: debug var=ansible_python_interpreter
    - name: Test delegate_to
      action: debug var=ansible_python_interpreter
      delegate_to: localhost
```

This can be reproduced both when localhost is not present in the inventory and when it's defined like this:

```
localhost ansible_connection=local ansible_python_interpreter=/home/ware/python/ansible/bin/python
```
##### Expected Results:

Happens on commit a77ea0f942fd3bf6debfdece0c2d9d5bc8e4dd66 or earlier:

```

PLAY [localhost] ************************************************************** 

TASK: [Test action] *********************************************************** 
ok: [localhost] => {
    "ansible_python_interpreter": "/home/ware/python/ansible/bin/python"
}

TASK: [Test local_action] ***************************************************** 
ok: [localhost] => {
    "ansible_python_interpreter": "/home/ware/python/ansible/bin/python"
}

TASK: [Test delegate_to] ****************************************************** 
ok: [localhost] => {
    "ansible_python_interpreter": "/home/ware/python/ansible/bin/python"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

Happens on commit 4af1d6098b35c7996d046c395650c497a313b733 and later:

```

PLAY [localhost] ************************************************************** 

TASK: [Test action] *********************************************************** 
ok: [localhost] => {
    "ansible_python_interpreter": "/home/ware/python/ansible/bin/python"
}

TASK: [Test local_action] ***************************************************** 
ok: [localhost] => {
    "ansible_python_interpreter": "{{ ansible_python_interpreter }}"
}

TASK: [Test delegate_to] ****************************************************** 
ok: [localhost] => {
    "ansible_python_interpreter": "/home/ware/python/ansible/bin/python"
}
```

Note that in the local_action test case ansible_python_interpreter is not defined. 

This breaks local_action on our Ansible host (CentOS 5.9) which has Python 2.4 by default and a separate Python 2.7 virtualenv for running Ansible (enabled with `source /home/ware/python/ansible/bin/activate`before running Ansible).
