### ISSUE TITLE
Add 'torify' to the telegram module (for russians)

### ISSUE THREAD

**Issue by antonwantstosleep** [ansible/ansible#61610]
##### SUMMARY
I suggest to add to the module:
- dependency of 'tor' package
- 'use_tor:' bool parameter

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
telegram

##### ADDITIONAL INFORMATION
Today the telegram module is not working in Russia because of the government issues (the Roskomnadzor is blocking api.telegram.org). Using 'torify' (part of tor) is the solution.

Now I use THIS task because the module telegram is not working:
```yaml
- name: shell - Send a message to chat
  shell: "torify curl -s -X POST https://api.telegram.org/bot{{ telegram_token }}/sendMessage -d chat_id={{ telegram_chat_id }} -d text='Hello, world!'"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/notification/telegram.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/telegram.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tyouxa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by antonwantstosleep** [comment]
BTW, my case is to use 'torify' only for telegram.
```
- name: service - Turn on TOR
  service:
    name: tor
    enabled: no
    state: started

- name: wait_for - Wait for TOR
  wait_for:
    port: 9050
    delay: 5
    state: started

- name: shell - Send message to Telegram
  shell: "torify curl -s -X POST https://api.telegram.org/bot{{ telegram_token }}/sendMessage -d chat_id={{ telegram_chat_id }} -d text='{{ message }}'"

- name: service - Turn off TOR
  service:
    name: tor
    enabled: no
    state: stopped
```
