### ISSUE TITLE
slack module should return API response so that message can be threaded

### ISSUE THREAD

**Issue by nicholasamorim** [ansible/ansible#61639]
##### SUMMARY
slack module makes available a `thread_id` parameter but there's no way to actually start a thread using Ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
slack

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Just add `thread_id` to any slack task.

```yaml
# This is a first and naive attempt to provision a full SM2 platform.
---
- hosts: localhost
  tasks:
    - name: post to slack
      slack:
        token: yourtoken
        msg: "msg1!"
      register: out

    - debug:
        msg: "{{ out }}"  # will print just a barebone OK 

    - name: post to slack
      slack:
        token: yourtoken
        msg: '{{ inventory_hostname }} completed'
        # wont work and there's no way to start a thread
        thread_id: 1539917263.000100
```

##### EXPECTED RESULTS

To be able to `register` the result and use the messsage timestamp as the `thread_id`.

##### ACTUAL RESULTS

Registering the output simply yields:

```
{'msg': 'OK', 'failed': False, 'changed': False}
```

```paste below
{'msg': 'OK', 'failed': False, 'changed': False}
```
