### ISSUE TITLE
nxos_acl no idempotency if optional arguments are passed as empty

### ISSUE THREAD

**Issue by k01ek** [ansible/ansible#61661]
##### SUMMARY

There is no idempotency if optional arguments are passed as empty.
Beacuse empty options pass None filter:
```
    proposed_core = dict((param, value) for (param, value) in
                         module.params.items()
                         if param in CORE and value is not None)
```
All options is 'str', so simple patch should work:
```
    proposed_core = dict((param, value) for (param, value) in
                         module.params.items()
                         if param in CORE and bool(value))

    proposed_options = dict((param, value) for (param, value) in
                            module.params.items()
                            if param in OPTIONS_NAMES and bool(value))
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_acl
##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kolek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### STEPS TO REPRODUCE

```yaml
- name:
  hosts: nexus
  vars:
    acls:
    - name: acl1
      action: permit
      src: 2.2.2.2/32
      src_port1:
      src_port2:
      src_port_op:
      dest: 3.3.3.3/32
      dest_port1:
      dest_port2:
      dest_port_op:
      proto: ip
    - name: acl1
      action: permit
      src: 1.1.1.1/32
      src_port1:
      src_port2:
      src_port_op:
      dest: 3.3.3.3/32
      dest_port1:
      dest_port2:
      dest_port_op:
      proto: ip
    - name: acl1
      action: permit
      src: any
      src_port1:
      src_port2:
      src_port_op:
      dest: any
      dest_port1: 179
      dest_port2:
      dest_port_op: eq
      proto: tcp
    - name: acl1
      action: permit
      src: any
      src_port1:
      src_port2:
      src_port_op:
      dest: any
      dest_port1:
      dest_port2:
      dest_port_op:
      proto: ospf
    - name: acl1
      action: deny
      src: any
      src_port1:
      src_port2:
      src_port_op:
      dest: any
      dest_port1:
      dest_port2:
      dest_port_op:
      proto: ip

  tasks:
    - name: Create ACL on device
      nxos_acl:
        name: "{{ item.name }}"
        seq: "{{ '%d0'|format(loop_index + 1) }}"
        action: "{{ item.action }}"
        proto: "{{ item.proto }}"
        src: "{{ item.src }}"
        src_port1: "{{ item.src_port1 }}"
        src_port2: "{{ item.src_port2 }}"
        src_port_op: "{{ item.src_port_op }}"
        dest: "{{ item.dest }}"
        dest_port1: "{{ item.dest_port1 }}"
        dest_port2: "{{ item.dest_port2 }}"
        dest_port_op: "{{ item.dest_port_op }}"
        state: present
      loop: "{{ acls }}"
      loop_control:
        index_var: loop_index
```

##### EXPECTED RESULTS

```
$ ansible-playbook -i inventory/hosts test.yml

PLAY [nexus] ********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [nxos1]

TASK [Create ACL on device] *****************************************************************************************************************************************************************************************************************
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'2.2.2.2/32', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'1.1.1.1/32', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'tcp', u'dest': u'any', u'dest_port_op': u'eq', u'action': u'permit', u'dest_port1': 179, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ospf', u'dest': u'any', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'any', u'dest_port_op': None, u'action': u'deny', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
nxos1                      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

$ ansible-playbook -i inventory/hosts test.yml

PLAY [nexus] ********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [nxos1]

TASK [Create ACL on device] *****************************************************************************************************************************************************************************************************************
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'2.2.2.2/32', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'1.1.1.1/32', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'tcp', u'dest': u'any', u'dest_port_op': u'eq', u'action': u'permit', u'dest_port1': 179, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ospf', u'dest': u'any', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
ok: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'any', u'dest_port_op': None, u'action': u'deny', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
nxos1                      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i inventory/hosts test.yml

PLAY [nexus] ********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [nxos1]

TASK [Create ACL on device] *****************************************************************************************************************************************************************************************************************
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'2.2.2.2/32', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'1.1.1.1/32', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'tcp', u'dest': u'any', u'dest_port_op': u'eq', u'action': u'permit', u'dest_port1': 179, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ospf', u'dest': u'any', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'any', u'dest_port_op': None, u'action': u'deny', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
nxos1                      : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

$ ansible-playbook -i inventory/hosts test.yml

PLAY [nexus] ********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [nxos1]

TASK [Create ACL on device] *****************************************************************************************************************************************************************************************************************
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'2.2.2.2/32', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'3.3.3.3/32', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'1.1.1.1/32', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'tcp', u'dest': u'any', u'dest_port_op': u'eq', u'action': u'permit', u'dest_port1': 179, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ospf', u'dest': u'any', u'dest_port_op': None, u'action': u'permit', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})
changed: [nxos1] => (item={u'src_port_op': None, u'name': u'acl1', u'proto': u'ip', u'dest': u'any', u'dest_port_op': None, u'action': u'deny', u'dest_port1': None, u'dest_port2': None, u'src': u'any', u'src_port1': None, u'src_port2': None})

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
nxos1                      : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
