### ISSUE TITLE
digital_ocean creation example fails: unpermitted parameter virtio

### ISSUE THREAD

**Issue by nopdotcom** [ansible/ansible#61665]
##### SUMMARY
`digital_ocean` (the DO module *not yet* deprecated) can't run its example.

This appears to be the fault of the external `dopy` module, which is sending a `virtio` parameter which is no longer accepted. See https://github.com/Wiredcraft/dopy/issues/64

Presumably once this problem is resolved, it will also have problems with sending `id` as `null`; see #61664.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /Users/nop/gh/nop-streisand/ansible.cfg
  configured module search path = [u'/Users/nop/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nop/gh/nop-streisand/venv284/lib/python2.7/site-packages/ansible
  executable location = /Users/nop/gh/nop-streisand/venv284/bin/ansible
  python version = 2.7.16 (default, Mar  4 2019, 09:01:38) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/nop/gh/nop-streisand/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/nop/gh/nop-streisand/ansible.cfg) = [u'/Users/nop/gh/nop-streisand/inventories/inventory']
DEFAULT_LOCAL_TMP(/Users/nop/gh/nop-streisand/ansible.cfg) = /Users/nop/.ansible/tmp/ansible-local-81013_9LHwt
DEFAULT_TIMEOUT(/Users/nop/gh/nop-streisand/ansible.cfg) = 100
HOST_KEY_CHECKING(/Users/nop/gh/nop-streisand/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS 10.14.6. Homebrew Python `python@2` version 2.7.16.

##### STEPS TO REPRODUCE

```yaml
- name: Demonstrate digital_ocean_droplet
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: create a new droplet
      digital_ocean_local:
        state: present
        command: droplet
        name: mydroplet
        #api_token: XXX
        size_id: 1gb
        region_id: sfo1
        image_id: ubuntu-16-04-x64
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"

```

##### EXPECTED RESULTS

I expect a droplet to be created, and its id and address printed.

##### ACTUAL RESULTS

```
PLAY [Demonstrate digital_ocean_droplet] ***************************************************************************************************************************************
META: ran handlers

TASK [create a new droplet] ****************************************************************************************************************************************************
task path: /Users/nop/gh/nop-streisand/do2-example.yml:6
Using module file /Users/nop/gh/nop-streisand/library/digital_ocean_local.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: nop
<localhost> EXEC /bin/sh -c 'python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/4q/tyxp19zj4szcl9pxjj8tr5hc000101/T/ansible_digital_ocean_local_payload_bkzu3G/__main__.py", line 474, in main
    core(module)
  File "/var/folders/4q/tyxp19zj4szcl9pxjj8tr5hc000101/T/ansible_digital_ocean_local_payload_bkzu3G/__main__.py", line 383, in core
    ipv6=module.params['ipv6'],
  File "/var/folders/4q/tyxp19zj4szcl9pxjj8tr5hc000101/T/ansible_digital_ocean_local_payload_bkzu3G/__main__.py", line 281, in add
    backups_enabled=backups_enabled_lower, user_data=user_data, ipv6=ipv6_lower)
  File "/Users/nop/gh/nop-streisand/venv284/lib/python2.7/site-packages/dopy/manager.py", line 68, in new_droplet
    json = self.request('/droplets', params=params, method='POST')
  File "/Users/nop/gh/nop-streisand/venv284/lib/python2.7/site-packages/dopy/manager.py", line 424, in request
    resp = self.request_v2(url, params=params, headers=headers, method=method)
  File "/Users/nop/gh/nop-streisand/venv284/lib/python2.7/site-packages/dopy/manager.py", line 482, in request_v2
    raise DoError(json['message'])
DoError: found unpermitted parameters: virtio

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "backups_enabled": false,
            "command": "droplet",
            "id": null,
            "image_id": "ubuntu-16-04-x64",
            "ipv6": false,
            "name": "mydroplet",
            "private_networking": false,
            "region_id": "sfo1",
            "size_id": "1gb",
            "ssh_key_ids": null,
            "ssh_pub_key": null,
            "state": "present",
            "unique_name": false,
            "user_data": null,
            "wait": true,
            "wait_timeout": 500
        }
    },
    "msg": "found unpermitted parameters: virtio"
}

PLAY RECAP *********************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
