### ISSUE TITLE
digital_ocean_droplet creation example fails: unpermitted id param

### ISSUE THREAD

**Issue by nopdotcom** [ansible/ansible#61664]
##### SUMMARY
`digital_ocean_droplet`'s example does not work.

Other invocations are broken too.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean_droplet

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /Users/nop/gh/streisand/ansible.cfg
  configured module search path = ['/Users/nop/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nop/gh/streisand/venv3/lib/python3.7/site-packages/ansible
  executable location = /Users/nop/gh/streisand/venv3/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

Also tested with Homebrew's packaged Ansible, and de6e2de0c461d0ed0d3d8c8cf93ea691f31376ce ; identical results.

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/nop/gh/streisand/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/nop/gh/streisand/ansible.cfg) = ['/Users/nop/gh/streisand/inventories/inventory']
DEFAULT_LOCAL_TMP(/Users/nop/gh/streisand/ansible.cfg) = /Users/nop/.ansible/tmp/ansible-local-33080k8mzt5ai
DEFAULT_TIMEOUT(/Users/nop/gh/streisand/ansible.cfg) = 100
HOST_KEY_CHECKING(/Users/nop/gh/streisand/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS 10.14.6, Homebrew Python version 3.7.4. Ansible installed in venv.

##### STEPS TO REPRODUCE

This is [the `digital_ocean_droplet` create example](https://docs.ansible.com/ansible/2.8/modules/digital_ocean_droplet_module.html#examples), in a playbook.

```yaml
- name: Demonstrate digital_ocean_droplet
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: create a new droplet
      digital_ocean_droplet:
        state: present
        name: mydroplet
        #oauth_token: XXX
        size: 2gb
        region: sfo1
        image: ubuntu-16-04-x64
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"
```

##### EXPECTED RESULTS

I expect a droplet to be created, and its id and IP address printed.

##### ACTUAL RESULTS

```
$ ansible-playbook do-example.yml
 [WARNING]: Found both group and host with same name: localhost


PLAY [Demonstrate digital_ocean_droplet] *********************************************************************************

TASK [create a new droplet] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "found unpermitted parameters: id"}

PLAY RECAP ***************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

Note that there is no `id` in the playbook. There should not be an `id` in any case; we won't know it until the droplet is created.
