### ISSUE TITLE
jenkins_plugin: use of authorization crumb must be conducted in a session since LTS 2.176

### ISSUE THREAD

**Issue by JKDingwall** [ansible/ansible#61672]
##### SUMMARY
Plugins cannot be installed using the jenkins_plugin module since upgrading to LTS 2.176.  This is due to additional CSRF security where the crumb that is issued may only be used within the same session.

In the jenkins log messages like this are reported:

```
WARNING: Found invalid crumb 5cae269d58b83057dfbd85f6c32f0845.  Will check remaining parameters for a valid one...
```

The module will then error with `Cannot install plugin.`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
jenkins_plugin

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
(no output)
```

##### STEPS TO REPRODUCE

Install jenkins 2.176, attempt to install plugins using ansible, e.g. a task such as:

```
- name: "Install Jenkins plugins"
  jenkins_plugin:
    owner: jenkins  
    group: jenkins
    name: "{{ item }}"
    url: "https://{{ ansible_host }}:8090/"
    url_username: "{{ ansible_user }}"
    url_password: "{{ ansible_become_pass }}"
    force_basic_auth: yes
  with_items:
    - ansicolor
```

```yaml

```

##### EXPECTED RESULTS

The named plugin is installed in jenkins.

##### ACTUAL RESULTS

```paste below

```
