### ISSUE TITLE
Impossible to omit or pass a default value to published_ports on docker_container

### ISSUE THREAD

**Issue by Poil** [ansible/ansible#61698]
##### SUMMARY
Hi,

When you want to pass an empty list or a null/None value to published_ports on docker_container it's actually impossible, so you get this error

```
File \"/tmp/ansible_docker_container_payload_ZOZc5l/__main__.py\", line 1448, in _parse_publish_ports\r\n  File \"/tmp/ansible_docker_container_payload_ZOZc5l/__main__.py\", line 1003, in parse_port_range\r\nValueError: invalid literal for int() with base 10: ''\r\n",
 ```

Ref #61602

The problem is that we parse via `_parse_publish_ports` the parameter if self.published_ports is not None or not 'all'
Also after that there is no control on each elements of the list, (not like for the volumes parameter by example)

So I propose to patch line 1151
`self.published_ports = self._parse_publish_ports() `
to
`self.published_ports = self._parse_publish_ports() if self.published_ports else None`

Best regards

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* docker_container

##### ANSIBLE VERSION

```
ansible 2.8.4
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/docker/docker_container.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @cove @danihodovic @dariko @dusdanig @felixfontein @joshuaconner @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Poil** [comment]
I'm wrong, entering the code again

```
          if self.published_ports is None:  
              self.fail('ici')
              return None 
```

When running I have
```
fatal: [vpnssl-d01-dkb]: FAILED! => {"changed": false, "msg": "ici"}
```

So I enter in this condition and it's normal

But after we enter in self.ports = self._parse_exposed_ports(self.published_ports) and it fail in it

**Comment by felixfontein** [comment]
I don't think that helps, since `_parse_publish_ports` already checks for `None`. Anyway, it looks like you are passing something to `published_ports` (resp. its alias `port`), since the `for` loop in `_parse_publish_ports` is never entered when `published_ports` is `None` or `[]`. Can you check what exactly you are passing to the module by running `ansible-playbook -vvv`? Then you can also find the effective options passed to the module in the output.

**Comment by Poil** [comment]
Hey,

When passing a default(omit) or a None value, it's transform to `['']` (list with an empty element) and I really don't understand why, it's look like something transform what I've passed.
If I pass `default([])` I have an empty list `[]` that's look like more normal, but in this case I have to patch the _parse_publish_ports function in docker_container.py from `if  self.published_ports: is None` to `if not self.published_ports:`

Best regards,

**Comment by Poil** [comment]
What is strange, on CentOS 7 (Python 2.7.5), it's working without patching but not on my Ubuntu 19.04 (Python 2.7.16)

**Comment by felixfontein** [comment]
I created a little test playbook to try to reproduce this:
```.yml
- hosts: localhost
  tasks:
  - docker_container:
      name: test
      image: debian:stretch
      command: sleep 5
      published_ports: "{{ non_existent | default(omit) }}"
  - docker_container:
      name: test
      image: debian:stretch
      command: sleep 5
      published_ports: []
  - docker_container:
      name: test
      image: debian:stretch
      command: sleep 5
      published_ports: ['']
```
For the first two tasks, which seem to do what you describe, everything works fine. Can you check whether they work for you or not?

The third one crashes with a stack trace equivalent to yours (this one is for `devel`, not for `stable-2.8`):
```
Traceback (most recent call last):
  [...]
  File "/tmp/ansible_docker_container_payload_sv0u4b8f/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 3255, in <module>
  File "/tmp/ansible_docker_container_payload_sv0u4b8f/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 3246, in main
  File "/tmp/ansible_docker_container_payload_sv0u4b8f/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 2485, in __init__
  File "/tmp/ansible_docker_container_payload_sv0u4b8f/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 1235, in __init__
  File "/tmp/ansible_docker_container_payload_sv0u4b8f/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 1539, in _parse_publish_ports
  File "/tmp/ansible_docker_container_payload_sv0u4b8f/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 1086, in parse_port_range
ValueError: invalid literal for int() with base 10: ''
```

Regarding `default` and `omit`: I don't think these are at fault here, it looks like your playbook/role is doing something which causes `['']` to be passed. If you have `{{ var | default(omit) }}`, this is most likely caused by `var` being defined with value `['']` (or `''`, which is converted to `['']` as Ansible expects a list).

**Comment by felixfontein** [comment]
I've created #61740 to improve the error message when this happens.

**Comment by Poil** [comment]
Hi,

Same for me, I think I forgot to flush-cache on some runs that's why I was becoming crazy and looking for a complicated way.

But for me there is still something that is not  user friendly in Ansible :

If I create this role :

```
---
- name: "1 : {{ item.service_name }}"
  docker_container:
    name: "{{ item.service_name }}"
    image: debian:stretch
    command: sleep 5
    published_ports: "{{ item.published_ports | default(omit) }}"
- name: "2 : {{ item.service_name }}"
  docker_container:
    name: "{{ item.service_name }}"
    image: debian:stretch
    command: sleep 5
    published_ports: "{{ item.published_ports2 | default([]) }}"
...
```

And this playbook
```
---
- hosts: localhost
  become: true
  tasks:
  - include_role:
      name: pouet
    loop:
      - service_name: docker1
        published_ports:
          - 8080:8080
        published_ports2:
          - 8081:8080
      - service_name: docker2
        published_ports:
      - service_name: docker3
...
```

Loop docker1 is OK
Loop docker2 is KO (invalid literal for int() with base 10)
Loop docker3 is OK

I really don't understand why docker2 is KO, in YAML, ~ !!null  and `key:` are null and not empty, so Ansible change this natural behaviour

Also we never enter in default when doing `item.get('un_existant_key') | default('hello')` but get in python return `None` not an empty string, so we should enter in default

Best regards,
