### ISSUE TITLE
Jenkins Improved CSRF protection breaks some Ansible modules

### ISSUE THREAD

**Issue by plastikat** [ansible/ansible#61712]
##### SUMMARY

With Jenkins [2.192](https://jenkins.io/changelog/) and [LTS 2.176](https://jenkins.io/changelog-stable/) comes [SECURITY-626: Improved CSRF protection](https://jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626).
This change breaks all scripts and utilities that have been using CSRF tokens (crumbs), including Ansible modules `jenkins_script` and `jenkins_plugin`: when trying to use one of these modules with Jenkins versions given above or newer, these modules fail with the message presented in "ACTUAL RESULTS" below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

jenkins_script
jenkins_plugin

##### ANSIBLE VERSION

```paste below
ansible 2.7.13
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/media/vbox/clients/enovos/ansible2/ansible.cfg) = True
ANSIBLE_PIPELINING(/media/vbox/clients/enovos/ansible2/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/media/vbox/clients/enovos/ansible2/ansible.cfg) = False
RETRY_FILES_ENABLED(/media/vbox/clients/enovos/ansible2/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 16.04.3 LTS x64

##### STEPS TO REPRODUCE

```yaml
# From examples in module docs
- name: Obtaining a list of plugins
  jenkins_script:
    script: 'println(Jenkins.instance.pluginManager.plugins)'
    user: admin
    password: admin
```

##### EXPECTED RESULTS

The task completes without error.

##### ACTUAL RESULTS

```paste below
fatal: [hostname]: FAILED! => {"changed": false, "msg": "HTTP error 403 HTTP Error 403: No valid crumb was included in the request", "output": ""}
```
