### ISSUE TITLE
'CyberarkPassword' object has no attribute 'delimiter'" after #59500

### ISSUE THREAD

**Issue by gr33ngiant112** [ansible/ansible#61718]
Related to #52625 and #59500 

Ansible version:
```
stable-2.9
devel branch
```

Python version:
```
python3.7.3
```

##### SUMMARY

Pull #59500 fixes one issue but seems to create another.
{"msg": "An unhandled exception occurred while running the lookup plugin 'cyberarkpassword'. Error was a <class 'AttributeError'>, original message: 'CyberarkPassword' object has no attribute 'delimiter'"} 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cyberarkpassword

##### ANSIBLE VERSION

```
ansible 2.9.0b1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/.ara/virtualenv/lib/python3.7/site-packages/ansible
  executable location = /home/myuser/.ara/virtualenv/bin/ansible
  python version = 3.7.3 (default, Aug 29 2019, 16:29:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ansible 2.9.0b1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/.ara/virtualenv/lib/python3.7/site-packages/ansible
  executable location = /home/myuser/.ara/virtualenv/bin/ansible
  python version = 3.7.3 (default, Aug 29 2019, 16:29:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
DEFAULT_ACTION_PLUGIN_PATH(env: ANSIBLE_ACTION_PLUGINS) = ['/home/myuser/.ara/virtualenv/lib/python3.7/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = ['/home/myuser/.ara/virtualenv/lib/python3.7/site-packages/ara/plugins/callback']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Have ansible 2.9, or 2.10-devel and try to use the cyberarkpassword lookup plugin in a playbook. 

```yaml
---
- name: retrieve ssh keys
  hosts: local
  gather_facts: no
  vars_files:
    - ../vars.yml
    - secrets.yml
  tasks:
    - name: Lookup ssh key for each host and copy to disk
      copy:
        content: "{{ lookup('cyberarkpassword', cyquery)[0]['password'] }}\n"
        dest: "{{ deploy_temp_dir }}/keys/{{ item }}_rsa"
        mode: 0600
      vars:
        cyquery:
          appid: '{{ cark_app_id }}'
          query: 'Safe={{ cark_safe }};Folder=Root;Object={{ item }}'
          output: 'Password'
      with_items: "{{ groups[env] }}"
```

##### EXPECTED RESULTS

Expected: Password is successfully looked up from Cyberark

##### ACTUAL RESULTS

Previously used Ansible 2.8.4@ python 2.7.5, as I have a hard dependency on the cyberarkpassword module. Attempting to use Ansible in a virtualenv for ARA, which requires python >3.6, so now running Python37, ansible 2.8.4 produces error described in ##52625. 

Updated to Ansible 2.9 inside the venv to take advantage of #59500 , and receive a new error instead.

```
 {"msg": "An unhandled exception occurred while running the lookup plugin 'cyberarkpassword'. Error was a <class 'AttributeError'>, original message: 'CyberarkPassword' object has no attribute 'delimiter'"} 
```
