### ISSUE TITLE
gitlab_user: add support to block user account

### ISSUE THREAD

**Issue by mjeco** [ansible/ansible#61754]
### SUMMARY
The `gitlab_user` module currently supports only two states; present and absent. The `python-gitlab` package has the ability to also block a user account. Deleting a user is not always desired as all projects owned by that user will be also permanently removed from GitLab too. It would be nice to add a new state of `blocked` where the user account is blocked instead of deleted.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/source_control/gitlab_user.py

##### ADDITIONAL INFORMATION
Sample usage:
```yaml
- name: Block user account
  gitlab_user:
    server_url: example.gitlab.com
    api_token:  kFCjRgwa/WriXncb7ews6A
    username: mjeco
    email: ""
    name: ""
    password: ""
    state: blocked
```

##### NOTES
Also note that the `email`, `name` and `password` arguments are required by the `gitlab_user` module although they are only used when creating the user account. We have to pass empty values otherwise the playbook fails with error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: name, password, email"}
```
