### ISSUE TITLE
VMware: No State parameter for 'vmware_deploy_ovf' module.

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#61762]
##### SUMMARY
No State parameter for 'vmware_deploy_ovf' module.

##### ISSUE TYPE
- Allow state for 'vmware_deploy_ovf' module so that if the template is available, playbook can continue using the same template.

##### COMPONENT NAME
- vmware_deploy_ovf

##### ADDITIONAL INFORMATION
If a playbook is having four plays:
    - Create a folder for VM & Templates
    - Create a template using 'vmware_deploy_ovf'
    - Create a vm from the newly created template
    - Delete the template after vm deployment complete

Keeping the above plays in a single playbook there is no way to move further with the existing template as unable to pass the template creation play.

NOTE: After deleting the VM if some one will try to deploy the same vm using same template then also we have to build the template again. As there is no way to use the same playbook directly without removing the template creation section.

### Playbook
```
---
- name: VMware guest Management using OVA
  hosts: localhost
  connection: 'local'
  gather_facts: 'false'
  vars_files:
    - vsphere_var.yaml
  tasks:
    - name: Create folder
      [......]

    - name: Template creation from OVA
      vmware_deploy_ovf:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        datastore: '{{ vsphere_datastore }}'
        resource_pool: '{{ vsphere_resourcepool }}'
        folder: '{{ vsphere_folder }}'
        name: '{{ guest_template }}'
        disk_provisioning: 'thin'
        networks:
          "VM Network" : "VM Network"
        validate_certs: 'no'
        power_on: 'no'
        fail_on_spec_warnings: 'yes'
        wait_for_ip_address: 'no'
        ovf: '/root/VMware-OVA/myname-1.0.42.ova'
     delegate_to: localhost

      - name: VM Deployment
        [......]

      - name: Template deletion
        [......]
```
