### ISSUE TITLE
lineinfile, does not behave properly when there are colons in  the regexp (?)

### ISSUE THREAD

**Issue by rkhaja** [ansible/ansible#6177]
I have the following task:

``` yml
- name: Edit /etc/inittab to start in Graphical environment on next reboot
  lineinfile: "dest=/etc/inittab regexp='id:[1-3]:initdefault:' line='id:5:initdefault:'"
  register: line_replaced
```

Note the double " and single ' quotations.

This should enable booting into a graphical environment, if the system currently does not boot into a graphical environment (provided graphical desktop packages have already been installed).

The regex does not seem to work, and a new line is appended every time the task is executed. I am registering a variable: line_replaced, so that I can conditionally reboot the system, however, since the line is replaced every time, I always get a true value, and my system reboots every time the task is executes.

Here is what /etc/inittab looks like:

```
# Default runlevel. The runlevels used are:
#   0 - halt (Do NOT set initdefault to this)
#   1 - Single user mode
#   2 - Multiuser, without NFS (The same as 3, if you do not have networking)
#   3 - Full multiuser mode
#   4 - unused
#   5 - X11
#   6 - reboot (Do NOT set initdefault to this)
# 
id:5:initdefault:       <-- this was initially id:3:initdefault:
id:5:initdefault:
id:5:initdefault:
id:5:initdefault:
id:5:initdefault:
```

Could someone test this out?

**Comment by ansibot** [comment]
Thanks for filing a ticket! I am the friendly GitHub Ansibot. I see you did not fill out your issue description based on our new issue template. Please copy the contents of this [template](https://raw2.github.com/ansible/ansible/devel/examples/issues/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket. 

Our system will automatically close tickets that do not have an issue template filled out within 7 days. Please note that due to large interest in Ansible, humans may not comment on your ticket if you ask them questions. Don't worry, you're still in the queue and the robots are looking after you.

**Comment by mpdehaan** [comment]
"The regex does not seem to work, and a new line is appended every time the task is executed"

I am suspecting this ticket may come more down to a list/support question about helping with the regex rather than a bug report.   Have you tried asking on the mailing list about how to construct the right regex?

**Comment by rkhaja** [comment]
Hello Michael,

"Have you tried asking on the mailing list about how to construct the right regex?"
- No I have not done that.

I simplified my task, so that it does not use the character set: [1-3], so that we can eliminate that from the regexp construction.  To be more restrictive (not pattern matching anywhere on a line), I also added ^, to anchor pattern matching to the beginning of the line. 

I've tried the following:
- A. no escaping
- B. single escaping
- C. double escaping

permuted with:
- 1. no quotes
- 2. single quotes outside
- 3. double quotes outside
- 4. single quotes inside
- 5. double quotes inside 
- 6. single quotes outside + double quotes nested 
- 7. double quotes outside + single quotes nested

for a total of 21 permutations.

None of the permutations worked. I don't believe that there is anything complicated about the regexp.  

I think that the semicolons : are causing some kind of interpretation problem with yaml syntax and python regexp parsing, hence I believe this to be a bug, but if anyone can point out my fault in the regexp, I would surely appreciate it. 

I've looked at these resources:
http://docs.ansible.com/lineinfile_module.html
http://docs.python.org/2/library/re.html

An example from the lineinfile module describes what to do when there are semicolons in the task:

``` yml
# Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
- lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
```

Case A.7. below, matches the suggested syntax in the example above.

See the 21 permutations below:

``` yml
---
#########################
# A. no escaping
#########################

# 1. no quotes => Produces syntax error
#- lineinfile: dest=/etc/inittab regexp=^id:3:initdefault: line=id:5:initdefault: state=present 

# 2. single quotes outside => File changed, line added
- lineinfile: 'dest=/etc/inittab regexp=^id:3:initdefault: line=id:5:initdefault: state=present' 

# 3. double quotes outside => File changed, line added
- lineinfile: "dest=/etc/inittab regexp=^id:3:initdefault: line=id:5:initdefault: state=present"

# 4. single quotes inside => File changed, line added
- lineinfile: dest=/etc/inittab regexp='^id:3:initdefault:' line='id:5:initdefault:' state=present 

# 5. double quotes inside => File changed, line added
- lineinfile: dest=/etc/inittab regexp="^id:3:initdefault:" line="id:5:initdefault:" state=present

# 6. single quotes outside + double quotes nested => File changed, line added
- lineinfile: 'dest=/etc/inittab regexp="^id:3:initdefault:" line="id:5:initdefault:" state=present' 

# 7. double quotes outside + single quotes nested => File changed, line added
- lineinfile: "dest=/etc/inittab regexp='^id:3:initdefault:' line='id:5:initdefault:' state=present" 

#########################
# B. single escaping
#########################

# 1. no quotes => Produces syntax error
#- lineinfile: dest=/etc/inittab regexp=^id\:3\:initdefault\: line=id\:5\:initdefault\: state=present

# 2. single quotes outside => File changed, line added
- lineinfile: 'dest=/etc/inittab regexp=^id\:3\:initdefault\: line=id\:5\:initdefault\: state=present' 

# 3. double quotes outside => Produces syntax error
#- lineinfile: "dest=/etc/inittab regexp=^id\:3\:initdefault\: line=id\:5\:initdefault\: state=present" 

# 4. single quotes inside => File changed, line added
- lineinfile: dest=/etc/inittab regexp='^id\:3\:initdefault\:' line='id\:5\:initdefault\:' state=present 

# 5. double quotes inside => File changed, line added
- lineinfile: dest=/etc/inittab regexp="^id\:3\:initdefault\:" line="id\:5\:initdefault\:" state=present

# 6. single quotes outside + double quotes nested => File changed, line added
- lineinfile: 'dest=/etc/inittab regexp="^id\:3\:initdefault\:" line="id\:5\:initdefault\:" state=present'

# 7. double quotes outside + single quotes nested => File changed, line added
- lineinfile: "dest=/etc/inittab regexp='^id\:3\:initdefault\:' line='id\:5\:initdefault\:' state=present"

#########################
# C. double escaping
#########################

# 1. no quotes => Produces syntax error
#- lineinfile: dest=/etc/inittab regexp=^id\\:3\\:initdefault\\: line=id\\:5\\:initdefault\\: state=present 

# 2. single quotes outside => File changed, line added
- lineinfile: 'dest=/etc/inittab regexp=^id\\:3\\:initdefault\\: line=id\\:5\\:initdefault\\: state=present' 

# 3. double quotes outside => File changed, line added
- lineinfile: "dest=/etc/inittab regexp=^id\\:3\\:initdefault\\: line=id\\:5\\:initdefault\\: state=present"

# 4. single quotes inside => File changed, line added
- lineinfile: dest=/etc/inittab regexp='^id\\:3\\:initdefault\\:' line='id\\:5\\:initdefault\\:' state=present

# 5. double quotes inside => File changed, line added
- lineinfile: dest=/etc/inittab regexp="^id\\:3\\:initdefault\\:" line="id\\:5\\:initdefault\\:" state=present

# 6. single quotes outside + double quotes nested => File changed, line added
- lineinfile: 'dest=/etc/inittab regexp="^id\\:3\\:initdefault\\:" line="id\\:5\\:initdefault\\:" state=present'

# 7. double quotes outside + single quotes nested => File changed, line added
- lineinfile: "dest=/etc/inittab regexp='^id\\:3\\:initdefault\\:' line='id\\:5\\:initdefault\\:' state=present" 
```
