### ISSUE TITLE
host vars disappear after first iteration in with_items

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#618]
```

---
- hosts: localhost
  vars:
  - mylist: [1, 2, 3]
  tasks:
  - with_items: $mylist
    action: shell echo $item $ansible_hostname > $item.txt
```

Running this through `ansible-playbook`, `$ansible_hostname` goes missing after the first iteration, so this gives:

```
$ cat ~/[1-3].txt
1 myhost
2
3
```

This may be related to issue #616?
