### ISSUE TITLE
Ansible Deployment Bug

### ISSUE THREAD

**Issue by catspy** [ansible/ansible#61803]
There seems to be a bug when modifying the container's name of a Deployment resource.
##### STEPS TO REPRODUCE

First create a deployment resource with a specific name for the containers (container-x) and a specific limited memory and CPU quota.
Deploy into kubernetes cluster
Then modify the Manifest of kubernetes by changing the name of the container (container-y)
Deploy again

Ansible version: 2.7.8

```
apiVersion: v1
kind: Deployment
metadata:
  ...
    spec:
      containers:
      ...
        name: container-x
```

```
apiVersion: v1
kind: Deployment
metadata:
  ...
    spec:
      containers:
      ...
        name: container-y
```

##### EXPECTED RESULTS

Successfully deployed. The POD contains only the specified containers in the deployment yml WITHOUT the old container

##### ACTUAL RESULTS

The deployment contains the new specified container AND the OLD container
