### ISSUE TITLE
add "interface" parameter to ovirt_template module

### ISSUE THREAD

**Issue by mshabou** [ansible/ansible#61840]
##### SUMMARY

i'd like a way to specify the interface type: (virtio, virtio_scsi) when we import an image from Glance as a templace

##### ISSUE TYPE
- Add new template_image_disk_interface : interface

##### COMPONENT NAME

ovirt_template

##### ADDITIONAL INFORMATION

```yaml
# Import image from Glance s a template
- ovirt_template:
    state: imported
    name: mytemplate
    image_disk: "centos7"
    template_image_disk_name: centos7_from_glance
    image_provider: "glance_domain"
    template_image_disk_interface: virtio_scsi   <== new option
    storage_domain: mystorage
    cluster: mycluster
```
