### ISSUE TITLE
Feature: Collections search path in playbook for lookups, filters and tests (like for modules/roles)

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible#61871]
##### SUMMARY
Please extend the collections search path so that lookups, filters, and tests can also be referenced without a namespace in a playbook.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
collections search path in playbook for lookups, filters and tests

##### ADDITIONAL INFORMATION
Collections allow for bundling/distributing many different kinds of plugins.
To simplify using collections, the `collections` key allows play-level definition of a "search path/order" for which collections can provide un-namespaced actions, modules, and roles during the play.

Please also provide the same collections-searching behavior for lookups, filters, and tests (ie plugin types that are directly referenced within a playbook).

```yaml
- hosts: all
  collections:
   - my_namespace.my_collection
  tasks:
    - import_role:
        name: role1

    - mymodule:
        option1: value

    - debug:
        msg: '{{ lookup("lookup1", 'param1')| filter1 }}'
```
(example based on the example from https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html#using-collections )
