### ISSUE TITLE
AWS ec2_transit_gateway "auto_attach: yes" does not work

### ISSUE THREAD

**Issue by dvntstph** [ansible/ansible#61907]
##### SUMMARY

Currently when using Ansible to create a transit gateway in AWS the auto_attach parameter is ignored.
When the gateway comes into existence the "AutoAcceptSharedAttachments" is set to disabled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_transit_gateway
##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dvnt/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dvnt/.local/lib/python2.7/site-packages/ansible
  executable location = /home/dvnt/.local/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Workflow to ultimately manage Transit Gateway in the XXX AWS Account
  hosts: localhost
  
  tasks:

  - name: Create variable for desired region
    set_fact: 
      defined_region: us-east-1

  - name: Assume role and obtain STS token
    sts_assume_role:
     region: "{{ defined_region }}"
     role_arn: arn:aws:iam::123456789123:role/My-AWS-Automation-Role-Name
     role_session_name: "AWS-Automation-session"
    register: assumed_role

  - name: Manage Transit Gateway for XXX AWS Account
    ec2_transit_gateway:
     aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
     aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
     security_token: "{{ assumed_role.sts_creds.session_token }}"
     description: "My Awesome TGW"
     state: present
     #asn: 
     auto_associate: no
     auto_attach: yes 
     auto_propagate: no
     dns_support: yes
     vpn_ecmp_support: yes
     region: "{{ defined_region }}"
     tags:
      Name: my-awesome-tgw
      module: ec2_transit_gateway
      my-tag: heck-yeah
```

##### EXPECTED RESULTS

When querying the created gateway settings using 'aws ec2 describe-transit-gateways' the created gateway should have "AutoAcceptSharedAttachments": "enable"

##### ACTUAL RESULTS

Gateway gets created with "AutoAcceptSharedAttachments": "disabled"

```paste below
dvnt@icecream:~$ aws ec2 describe-transit-gateways
{
    "TransitGateways": [
        {
            "TransitGatewayId": "##REDACTED##",
            "TransitGatewayArn": "arn:aws:iam::123456789123:role/My-AWS-Automation-Role-Name",
            "State": "available",
            "OwnerId": "##REDACTED##",
            "Description": "My Awesome TGW",
            "CreationTime": "2019-09-05T21:19:12.000Z",
            "Options": {
                "AmazonSideAsn": 64512,
                "AutoAcceptSharedAttachments": "disable",
                "DefaultRouteTableAssociation": "disable",
                "DefaultRouteTablePropagation": "disable",
                "VpnEcmpSupport": "enable",
                "DnsSupport": "enable"
            },
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "my-awesome-tgw"
                }
            ]
        }
    ]
}

```
