### ISSUE TITLE
User module does not update user attribute in Alpine docker container

### ISSUE THREAD

**Issue by eauser-8** [ansible/ansible#61911]
##### SUMMARY

I'm trying to update a user's shell in an Alpine docker container using the user module, but it does not get updated. The task is marked as changed or ok, but when I check /etc/passwd the user's shell field is not updated. This works in Ansible 2.7.x and seems to only happen in 2.8.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

user module

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /home/centos/ansible.cfg
  configured module search path = ['/home/centos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/centos/venv/lib/python3.6/site-packages/ansible
  executable location = /home/centos/venv/bin/ansible
  python version = 3.6.8 (default, May  2 2019, 20:40:44) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/home/centos/ansible.cfg) = ['/home/centos/workspace/roles']
```

##### OS / ENVIRONMENT

Control machine: CentOS 7
Alpine docker container v3.10.2

##### STEPS TO REPRODUCE

- pull latest [alpine image](https://hub.docker.com/_/alpine)
- alpine container is running

example:
```yaml
- name: Alpine Issue
  hosts: local

  tasks:
    # making sure to have the shadow package
    - name: install shadow package (needed for user module)
      package:
        name: shadow
        state: present

    - name: Make temp_user
      user:
        name: temp_user

    - name: get temp_user /etc/passwd info before update
      command: grep temp_user /etc/passwd
      register: temp_user_info

    - name: print temp_user info
      debug:
        msg:
          - "{{ temp_user_info.stdout }}"
    
    - name: update shell for temp_user
      user:
        name: temp_user
        shell: /sbin/nologin

    - name: get temp_user /etc/passwd info after update
      command: grep temp_user /etc/passwd
      register: temp_user_info_after

    - name: print temp_user info
      debug:
        msg:
          - "{{ temp_user_info_after.stdout }}"
    
    - name: remove user
      user:
        name: temp_user
        state: absent
```

##### EXPECTED RESULTS

temp_user's shell gets updated to `/sbin/nologin`

##### ACTUAL RESULTS

```paste below
(venv) [centos@ansible-control ~]$ ansible-playbook ansible_issue.yml

PLAY [Alpine Issue] *************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [alpine_container]

TASK [install shadow package (needed for user module)] **************************************************************
ok: [alpine_container]

TASK [Make temp_user] ***********************************************************************************************
changed: [alpine_container]

TASK [get temp_user /etc/passwd info before update] *****************************************************************
changed: [alpine_container]

TASK [print temp_user info] *****************************************************************************************
ok: [alpine_container] => {
    "msg": [
        "temp_user:x:1000:1000:Linux User,,,:/home/temp_user:/bin/ash"
    ]
}

TASK [update shell for temp_user] ***********************************************************************************
ok: [alpine_container]

TASK [get temp_user /etc/passwd info after update] ******************************************************************
changed: [alpine_container]

TASK [print temp_user info] *****************************************************************************************
ok: [alpine_container] => {
    "msg": [
        "temp_user:x:1000:1000:Linux User,,,:/home/temp_user:/bin/ash"
    ]
}

TASK [remove user] **************************************************************************************************
changed: [alpine_container]

PLAY RECAP **********************************************************************************************************
alpine_container           : ok=9    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/user.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by skyfaller** [comment]
I am seeing a similar issue with a copy of Alpine that is not inside of a Docker container (it is an Alpine 3.14 image on a Linode virtual server).

Ansible version
```
ansible [core 2.11.3]
  config file = /Users/nelson/.ansible.cfg
  configured module search path = ['/Users/nelson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.3.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/nelson/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 06:20:32) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
```
OS is macOS Catalina 10.15.7

Example:
```
- name: Add limited user accounts for all sysadmins
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
    groups: "{{ sudoing_group }}"
    update_password: on_create
  loop: "{{ users }}"
  tags: user_accounts
```
When I run it, the shell does not get updated to my preferred shell. My user's shell gets stuck as `/bin/ash` and does not get switched to `/usr/bin/fish` as desired. Yes, fish is installed and at that location.
