### ISSUE TITLE
gitlab_user requires email, name, and password arguments when deleting a user

### ISSUE THREAD

**Issue by mjeco** [ansible/ansible#61921]
##### SUMMARY
In th `gitlab_user` module the `email`, `name`, and `password` arguments are required.
That is perfectly fine when creating a new user as this information is needed.
However, these three arguments are also required when deleting a user (state==absent), even though they are not used by the module for this action.
The module fails with an error if these arguments are not passed in. You are forced to pass in blank (or dummy) values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gitlab_user

##### ANSIBLE VERSION
```paste below
ansible 2.8.4
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Manjaro Linux 18.0.4

##### STEPS TO REPRODUCE
```yaml
- name: Delete user account
  gitlab_user:
    server_url: "{{ gitlab_url }}"
    api_token: "{{ token }}"
    username: "{{ username }}"
    state: absent
```

##### EXPECTED RESULTS
GitLab user should be successfully deleted. Only the `username` is required to find and delete the user.

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: name, password, email"}
```
##### WORKAROUND
```yaml
- name: Delete user account
  gitlab_user:
    server_url: "{{ gitlab_url }}"
    api_token: "{{ token }}"
    username: "{{ username }}"
    email: ""
    name: ""
    password: ""
    state: absent
```
