### ISSUE TITLE
win_scheduled_task trigger parameters are not allowing use of default(omit) placeholder

### ISSUE THREAD

**Issue by cdschneider** [ansible/ansible#61926]
##### SUMMARY
Using `| default(omit)` (null-safe variable fallback) in the `triggers` section on `days_of_week` and `days_of_month` causes exception in `win_scheduled_task`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* `win_scheduled_task`

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cschneider/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Mar 20 2019, 12:15:19) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

* **Target OS versions**: Windows Server 2016

##### STEPS TO REPRODUCE

```yaml
---
- name: schedule a windows task
  win_scheduled_task: 
    name: foo bar
    actions: 
      - path: 'powershell.exe'
        arguments: '-NoProfile -WindowStyle Hidden -File C:/Users/cschneider/my-script.ps1'
    triggers:
      - type: '{{ task_interval }}'
        start_boundary: '1970-01-01T{{ task_start_time }}'
        days_of_week: '{{ task_days_of_week | default(omit) }}'
        days_of_month: '{{ task_days_of_month | default(omit) }}'
```

##### EXPECTED RESULTS

Trying to organize this way so variables can be set for different hosts, groups and inventories for different scheduling effects, specifically `daily`, `weekly` and `monthly`. 

For example, for a daily schedule on ` hostname1`:

`host_vars/hostname1.yml`
```yaml
task_interval: daily
task_start_time: '05:00:00'
```

For a weekly schedule on `hostname2`:

`host_vars/hostname2.yml`
```yaml
task_interval: weekly
task_start_time: '05:00:00'
task_interval_days_of_week: sunday
```

For a monthly schedule on ` hostname3`:

`host_vars/hostname3.yml`
```yaml
task_interval: monthly
task_start_time: '05:00:00'
task_interval_days_of_month: 1
```

##### ACTUAL RESULTS

When either `days_of_week` or `days_of_month` are hit with the `default(omit)` fallback value, I get the following errors at the point this task is executed:

`default(omit)` on `days_of_week`:
```paste below
fatal: [hostname]: FAILED! => {"changed": false, "msg": "invalid day of week '__omit_place_holder__d07351985256f3ae2bfcf3314d3dd2082fe9f4b2', check the spelling matches the full day name"}
```

`default(omit)` on `days_of_month`:
```paste below
fatal: [hostname]: FAILED! => {"changed": false, "msg": "invalid day of month '__omit_place_holder__4241e48e369165e6fa4058d6d0d2829137e8132b', please specify numbers from 1-31"}
```
