### ISSUE TITLE
Pull files from Cisco NX-OS devices

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#61939]
##### SUMMARY
The ```nxos_file_copy``` module supports **pushing** files to NX-OS devices from the controller host or from a remote SCP file server .
However, it does not allow **pulling** files from NX-OS devices.
It is not possible to use the ```fetch``` module either (it fails to find the existing source file in bootflash:).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_file_copy

##### ADDITIONAL INFORMATION
This would allow users to fetch files from remote NX-OS devices, such as binary files.

```
- name: fetch file from NX-OS device
  nxos_file_copy:
    # Same parameter as in fetch module
    flat: yes
    # where to pull the file onto the host controller
    local_file: "/srv/scp/{{ os_family }}/{{ os_version }}/"
    # where to pull the file from the NX-OS device
    remote_file: "{{ nxos_bin_image }}"
    # Remote file system of the device
    remote_file_system: "{{ firmware.disk }}"
    # Operation type:
    # - pull from NX-OS device --> controller or scp server or 
    # - push from controller or scp server --> NX-OS device
    operation: pull 
    # Same parameter as in fetch module
    validate_checksum: yes
```
For clarity sake, the parameters 
- ```file_pull``` & ```file_pull_timeout``` must be renamed to, for instance, ```remote_scp_server``` & ```file_timeout``` respectively
- ```file_system``` has been renamed to ```remote_file_system``` to be consistent with ```remote_file```.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/nxos/nxos_file_copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_file_copy.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @GGabriele @chrisvanheuveln @jedelman8 @mikewiebe @rahushen @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jean-christophe-manciot, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ganeshrn** [comment]
Did you try with [net_get](https://docs.ansible.com/ansible/devel/modules/net_get_module.html) module to fetch the binary files?

needs_info

**Comment by jean-christophe-manciot** [comment]
@ganeshrn 
@mikewiebe 
If this module is dedicated to networking devices, I assume it supports the use of the disk in the ```src``` parameter. The documentation is unclear about that.
For instance: ```bootflash:/``` with NX-OS.

**Comment by jean-christophe-manciot** [comment]
I've just tried it on a local controller & a NFV NX-OSv-9k, and it does not seem stable: it fails after 7.6 MB have been received on the controller:
```
- name: Pulling NX-OS firmware binary image into "{{ firmware.controller_images_dir }}/{{ os_family }}/{{ os_version }}"
  vars:
        ansible_connection: network_cli
        ansible_network_os: nxos
        ansible_password: "{{ connections.ssh.password }}"
        ansible_user: "{{ connections.ssh.username }}"
  net_get:
        # where to pull the file onto the host controller
        dest: "{{ firmware.controller_images_dir }}/{{ os_family }}/{{ os_version }}/{{ return_nxos_bin_images.stdout }}"
        protocol: scp
        # where to pull the file from the NX-OS device
        src: "{{ firmware.nxos_disk }}:/{{ return_nxos_bin_images.stdout }}"
```
leads to:
```
fatal: [NX_OSv_9k-9.2.3]: FAILED! => {
    "changed": true,
    "destination": "/srv/scp/nx_osv_9k/9.2(3)/nxos.9.2.3.bin",
    "msg": "Exception received : command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
```
The controller received:
```
-rw-r--r-- 1 admin admin 7618560 Sep 11 17:09 nxos.9.2.3.bin
```
instead of:
```
NX_OSv_9k-9.2.3# dir bootflash:/nxos.9.2.3.bin
 1335985152    Feb 17 15:30:28 2019  nxos.9.2.3.bin
```
