### ISSUE TITLE
aws_s3 encryption_mode AES256 is not working

### ISSUE THREAD

**Issue by felipeng** [ansible/ansible#61935]
##### SUMMARY
Module: `aws_s3` with option `encryption_mode` and value `AES256`  is not working, the s3 bucket is created however the default encryption option is disabled

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module: aws_s3 encryption_mode

##### ANSIBLE VERSION
```
ansible --version
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
no config 

##### OS / ENVIRONMENT
debian 9
`Linux 932338f6af23 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux`

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: create bucket
      aws_s3:
        bucket: mybucket
        mode: create
        region: ca-central-1
        encryption_mode: "AES256"
        encrypt: yes
```

and then: `ansible-playbook main.yaml` no error on output

##### EXPECTED RESULTS
Create a s3 bucket with default encryption AES256 enabled

##### ACTUAL RESULTS
S3 bucket is created but default encryption AES256 is disabled

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/amazon/aws_s3.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_s3.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@felipeng, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jillr** [comment]
At the moment `aws_s3` only supports encryption for `PUT` operations (object uploads).  You can create encrypted buckets today via the `s3_bucket` module which will generally give you better bucket management options overall:
```
    - name: create bucket
      s3_bucket:
        name: mybucket
        state: present
        region: ca-central-1
        encryption: "AES256"
```
