### ISSUE TITLE
mongod_replicaset: test fails with Wait for mongod to start responding port={{ item }}

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#61938]
##### SUMMARY

Time to time, mongodb fails to start and the functional test fails because of that.

e.g:
- https://app.shippable.com/github/ansible/ansible/runs/142156/73/tests
- https://app.shippable.com/github/ansible/ansible/runs/143055/73/tests
- https://app.shippable.com/github/ansible/ansible/runs/143055/67/tests

```
 mongodb_replicaset-v2r_u7pa / /root/.ansible/test/tmp/mongodb_replicaset-nirs74ib-ÅÑŚÌβŁÈ/test/integration/targets/mongodb_replicaset/tasks/mongod_replicaset.yml:41 / [testhost] testhost: mongodb_replicaset : Wait for mongod to start responding port={{ item }}

failure: All items completed
```

```yaml
{
"changed": false,
"msg": "All items completed",
"results": [
{
"ansible_loop_var": "item",
"changed": false,
"elapsed": 300,
"failed": true,
"invocation": {
"module_args": {
"active_connection_states": [
"ESTABLISHED",
"FIN_WAIT1",
"FIN_WAIT2",
"SYN_RECV",
"SYN_SENT",
"TIME_WAIT"
],
"connect_timeout": 5,
"delay": 0,
"exclude_hosts": null,
"host": "127.0.0.1",
"msg": null,
"path": null,
"port": 3001,
"search_regex": null,
"sleep": 1,
"state": "started",
"timeout": 300
}
},
"item": 3001,
"msg": "Timeout when waiting for 127.0.0.1:3001"
},
{
"ansible_loop_var": "item",
"changed": false,
"elapsed": 0,
"failed": false,
"invocation": {
"module_args": {
"active_connection_states": [
"ESTABLISHED",
"FIN_WAIT1",
"FIN_WAIT2",
"SYN_RECV",
"SYN_SENT",
"TIME_WAIT"
],
"connect_timeout": 5,
"delay": 0,
"exclude_hosts": null,
"host": "127.0.0.1",
"msg": null,
"path": null,
"port": 3002,
"search_regex": null,
"sleep": 1,
"state": "started",
"timeout": 300
}
},
"item": 3002,
"match_groupdict": {},
"match_groups": [],
"path": null,
"port": 3002,
"search_regex": null,
"state": "started"
},
{
"ansible_loop_var": "item",
"changed": false,
"elapsed": 0,
"failed": false,
"invocation": {
"module_args": {
"active_connection_states": [
"ESTABLISHED",
"FIN_WAIT1",
"FIN_WAIT2",
"SYN_RECV",
"SYN_SENT",
"TIME_WAIT"
],
"connect_timeout": 5,
"delay": 0,
"exclude_hosts": null,
"host": "127.0.0.1",
"msg": null,
"path": null,
"port": 3003,
"search_regex": null,
"sleep": 1,
"state": "started",
"timeout": 300
}
},
"item": 3003,
"match_groupdict": {},
"match_groups": [],
"path": null,
"port": 3003,
"search_regex": null,
"state": "started"
}
]
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongod_replicaset

##### ANSIBLE VERSION

```paste below
devel
```
