### ISSUE TITLE
Cannot install/run docker on new ubuntu 18.04

### ISSUE THREAD

**Issue by lonix1** [ansible/ansible#61948]
##### SUMMARY
Can't install and run docker on new ubuntu 18.04 server.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### CONFIGURATION
```
---empty---
```

##### OS / ENVIRONMENT
controller: ubuntu 19.04
remote host: ubuntu 18.04 - brand new nothing else installed

##### STEPS TO REPRODUCE
ansible.cfg:
````ini
[defaults]
interpreter_python = /usr/bin/python3
````

playbook:
```yaml
##### provision brand new ubuntu 18.04 server
# ...

##### setup docker
- name: install packages required by docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg-agent
    - software-properties-common

- name: add docker GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repo
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  become: true
  apt:
    update_cache: yes
    state: latest
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: start docker
  become: true
  service: name=docker state=restarted

##### setup "Docker SDK for Python"

- name: install apt dependencies
  become: true
  apt:
    update_cache: yes
    state: latest
    name: python3-pip

- name: install pip dependencies
  pip:
    name: docker

##### test

- name: test docker
  become: true
  block:
  - docker_image:
      name: hello-world
      source: pull
  - docker_container:
      name: hello-world
      state: started
```

##### EXPECTED RESULTS
For docker image to be pulled and run.

##### ACTUAL RESULTS
>Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on host's Python /usr/bin/python3. Please read module documentation and install in the appropriate location, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'.

To confirm whether it's really installed, I ran `pip3 list` which showed `docker (4.0.2)`. So it is installed - the error is misleading.
