### ISSUE TITLE
gcp_dns_resource_record_set - Support SSHFP Record type 

### ISSUE THREAD

**Issue by justinturpin** [ansible/ansible#61954]
##### SUMMARY
Google cloud DNS record sets supports "sshfp" record types, which allow users to store SSH fingerprints in DNS for improved validation of hosts.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`gcp_dns_resource_record_set`

##### ADDITIONAL INFORMATION

Example usage might be:

```yaml
gcp_dns_resource_record_set:
      state: present
      name: "{{ name }}"
      project: "{{ gcp_project_id }}"
      managed_zone:
        name: "{{ gcp_zone }}"
      type: SSHFP
      ttl: 180
      target:
        - rsa
        - ecdsa
        - ed25519
```

But this currently fails with:
``` fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of type must be one of: A, AAAA, CAA, CNAME, MX, NAPTR, NS, PTR, SOA, SPF, SRV, TLSA, TXT, got: SSHFP"}```
