### ISSUE TITLE
vmware_tag_facts (_info) - Needs slick way to get Category ID

### ISSUE THREAD

**Issue by vMarkusK** [ansible/ansible#61963]
##### SUMMARY

The module should also return details about tag categories. The category ID, for example, needs to be used to create a  new tag (vmware_tag).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_tag_facts

##### ADDITIONAL INFORMATION

1. gather tag category ID via vmware_tag_facts
2. Create new Tag via vmware_tag

```yaml
- name: Manage vSphere VM Tags
  hosts: localhost
  gather_facts: no
  vars:
    tag_category: Protection
    tag_name: DemoApp
  tasks:
    - name: Get category id
      vmware_tag_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        category: '{ tag_category }'
        validate_certs: no
      register: tag_category_facts
      delegate_to: localhost
    - name: Create Tag for '{{ tag_name }}'
      vmware_tag:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: no
        category_id: "{{ tag_category_facts.category_id }}"
        tag_name: '{{ tag_name }}'
        state: present
      delegate_to: localhost
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/vmware/vmware_tag_info.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_tag_info.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_tag_info.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@mycloudrevolution Thanks for the feature request. Could you please elaborate more on the details you require from `vmware_tag_info` module ? 

I am able to use category id from `vmware_tag_info` - 

```yaml
  - name: Get all tags
    vmware_tag_facts:
      validate_certs: False
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
    register: tag_category_results

  - name: Create a new tag
    vmware_tag:
      validate_certs: False
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      category_id: "{{ tag_category_results['tag_facts']['tag_0001']['tag_category_id'] }}"
      tag_name: tag_0002
      tag_description: Sample Description
      state: present
```

**Comment by Akasurde** [comment]
needs_info

**Comment by mycloudrevolution** [comment]
But only for an exiting tag. If only the category exists without tags or you don't know the tag names you are not able to identify the category.

**Comment by Akasurde** [comment]
@mycloudrevolution How about using `vmware_category_info` instead - 

```yaml
- name: Gather category id from given tag category
  vmware_category_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
  delegate_to: localhost
  register: tag_category_results

- set_fact:
    category_id: "{{ item.category_id }}"
  loop: "{{ tag_category_results.tag_category_info | json_query(query) }}"
  vars:
    query: "[?category_name==`Category0001`]"
- debug: var=category_id
```

`tag_category_results` also contains information about tags which are using this particular category.

Let me know if it works for you. Thanks.

needs_info
