### ISSUE TITLE
pear module: always returns status changed for PECL mongodb

### ISSUE THREAD

**Issue by Addvilz** [ansible/ansible#61968]
##### SUMMARY

This simple PECL installation task always returns changed, despite the extension already being present on the system.

Interestingly, this only happens with pecl/mongodb. Other PECL tasks work as expected. 

I have this task run on 3 separate machines, and the result is the same.

```yaml
- name: Install PECL mongodb
  become: true
  pear:
    name: pecl/mongodb
    state: latest
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`pear` module.

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = <redacted>ansible.cfg
  configured module search path = [u'/<redacted>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ansible host: ElementaryOS 5.

Targets: 
Debian 10 (buster) latest, all updates.

```
PEAR Version: 1.10.6
PHP Version: 7.3.4-2
Zend Engine Version: 3.3.4
Running on: Linux e31.c3.g1.frontal.ie1.he.infra.testing 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64
```

##### STEPS TO REPRODUCE

```yaml
- name: Install PECL mongodb
  become: true
  pear:
    name: pecl/mongodb
    state: latest
```

##### EXPECTED RESULTS

Status `ok` once the extension is installed.

##### ACTUAL RESULTS

Status `changed` even with the extension is installed.

```paste below
TASK [fpm : Install PECL mongodb] ************************
changed: [e31]
changed: [e32]
changed: [e33]
```
