### ISSUE TITLE
get_url: conditional get does not work

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#61978]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
get_url in 2.6.4 would do a conditional get of url if dest points to existing file (using mtime of said file as the value for if-modified-since header).  In 2.7.7 the same configuration result in the task simply being skipped as not changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
ansible 2.7.7
  config file = /home/allan/.ansible.cfg
  configured module search path = ['/home/allan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
    - get_url:
        dest: .
        url: https://zoom.us/client/latest/zoom_amd64.deb
      delegate_to: localhost
```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
n/a

##### STEPS TO REPRODUCE
1. Setup a minimal server so you can inspect the header, i.e. `nc -l 8000`
2. touch zoom_amd64.deb
3. change url to http://localhost:8000/zoom_amd64.deb

##### EXPECTED RESULTS
get_url should make a conditional request for url using the mtime of dest.

##### ACTUAL RESULTS
get_url makes no remote requests and task is skipped as not changed.

##### WORK AROUND
The only reasonable easy work-around I found was to switch to the uri module and specify status_code of [200, 304].  Also, note the ote inconsistency in behavior here between get_url and uri with respect to dest.  uri doesn't change behavior depending on if dest is a file or a directory, while get_url does and I think the latter is unnecessarily confusing.

```
      - uri:                                                                                                                                                                                                                                   
          dest: .                                                                                                                                                                                                                              
          status_code: [200, 304]                                                                                                                                                                                                              
          url: https://zoom.us/client/latest/zoom_amd64.deb                                                                                                                                                                                    
        delegate_to: localhost                                                                                                                                                                                                                 
```

##### REFERENCES
#29861, #3191
