### ISSUE TITLE
VMware: most modules give results warning

### ISSUE THREAD

**Issue by UnknownGnome** [ansible/ansible#62006]
##### SUMMARY

Most modules give the warning 
[WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host_service_manager

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

awx docker image

##### STEPS TO REPRODUCE

```yaml
    - name: enable SSH
      vmware_host_service_manager:
        hostname: "{{ vcenter }}"        
        username: "{{ lookup('env','VMWARE_USER') }}"
        password: "{{ lookup('env','VMWARE_PASSWORD') }}"
        esxi_hostname: "{{inventory_hostname}}"
        service_name: TSM-SSH
        state: start
```

##### ACTUAL RESULTS

```paste below
The module works fine, but it produces the warning
 [WARNING]: Found internal 'results' key in module return, renamed to
'ansible_module_results'.
```
