### ISSUE TITLE
snow_record (and snow resources in general) should allow for host as well as instance

### ISSUE THREAD

**Issue by theemptyone** [ansible/ansible#62018]
##### SUMMARY
snow_record only allows for "instance" parameter to be passed and not host parameter to pysnow.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
snow_record 

##### ADDITIONAL INFORMATION
Pysnow has both an instance and a host parameter be set passed for target snow instance.  Often when internal systems go through adfs/sso options they will be pointing to an internal nat before it gets to the public site which would not be available on 443.  We've got around this by manually hacking the resource, to have the instance ansible parameter point to the host pysnow variable.  This obviously is not a long term solution.

This reflects the documentation at pysnow:
https://pysnow.readthedocs.io/en/latest/api/client.html

```
- name: Grab a user record
  snow_record:
    username: ansible_test
    password: my_password
    host: dev99999.blah.com
    state: present
    number: 62826bf03710200044e0bfc8bcbe5df1
    table: sys_user
    lookup_field: sys_id
```
