### ISSUE TITLE
Add support for terraform import resources

### ISSUE THREAD

**Issue by bkmeneguello** [ansible/ansible#62011]
##### SUMMARY
Allow to import resources to Terraform

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

terraform

##### ADDITIONAL INFORMATION

```yaml
- terraform:
    state: import
    project_path: ./terraform
    addr: aws_instance.web
    id: i-12345678
```
