### ISSUE TITLE
os_port does not respect network or auth user / project if port with same name exists in a different project or on a different network

### ISSUE THREAD

**Issue by mrobson** [ansible/ansible#62010]
##### SUMMARY
The openstack os_port module fails at creating ports with the same name when they are attaching to 2 different networks in 2 different projects.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- OpenStack os_port.py

##### ANSIBLE VERSION
```
ansible --version
ansible 2.8.1
  config file = None
  configured module search path = [u'/Users/matthewrobson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION
```
<blank>
```

##### OS / ENVIRONMENT
- Targeting OpenStack 14, running from OSX

##### STEPS TO REPRODUCE
Running for the first time, no issues:

1. Create unique project
2. Create unique user
3. Add roles
4. Add unique keypair
5. Add unique security rules
6. Add unique network
7. Add unique subnet
8. Add unique router
9. Create port using name of instance
10. Attach port to instance

Running for the second time using all new details for the project, user, network etc... In this case, the instance name is the same and thus the port would have the same name.

It fails with:

```
fatal: [api]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Error updating port 9b0b460b-65cd-4527-be76-c565dbf2b6d6: Client Error for url: https://10.37.197.10:13696/v2.0/ports/9b0b460b-65cd-4527-be76-c565dbf2b6d6.json, IP address 10.10.20.10 is not a valid IP for any of the subnets on the specified network."}
```

Even thought the task is using a login from the new project, the network from the new project and a new IP from the new project subnet, it's trying to update the port from the first run with an IP that is invalid for that subnet.

```
First network:
| 4cc819dc-5921-4b55-b62f-494a51ca2924 | first_network   | e7e0ad78-a274-4863-9eee-d7ceb6ab80e0                                       |

First subnet:
| e7e0ad78-a274-4863-9eee-d7ceb6ab80e0 | first_subnet    | 4cc819dc-5921-4b55-b62f-494a51ca2924 | 10.10.11.0/24    |

First port:
| 9b0b460b-65cd-4527-be76-c565dbf2b6d6 | api                                                                 | fa:16:3e:e4:d8:c7 | ip_address='10.10.11.10', subnet_id='e7e0ad78-a274-4863-9eee-d7ceb6ab80e0'     | ACTIVE |

Second network:
| 4a5dfb2d-6e3c-4715-aefb-71b89bda2417 | second_network      | a8b34d12-e0e1-4614-851d-79bf8a80b9bd                                       |

Second subnet:
| a8b34d12-e0e1-4614-851d-79bf8a80b9bd |second_subnet       | 4a5dfb2d-6e3c-4715-aefb-71b89bda2417 | 10.10.20.0/24    |

Second port: fails
```

```yaml
- name: Create project
  os_project:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ project }}"
     description: OCP 4 UPI
     domain_id: "{{ user_domain }}"
     enabled: True
- name: Create user
  os_user:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ ospuser }}"
     password: "{{ osppassword }}"
     email: "{{ email }}"
     domain: "{{ user_domain }}"
     default_project: "{{ project }}"
- name: Associate role
  os_user_role:
     cloud: "{{ os_admin }}"
     user: "{{ ospuser }}"
     role: admin
     project: "{{ project }}"
- name: Associate role
  os_user_role:
     cloud: "{{ os_admin }}"
     user: "{{ ospuser }}"
     role: member
     project: "{{ project }}"
- name: Add keypair
  os_keypair:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ ospuser }}"
     public_key_file: "{{ ssh_key }}"
- name: TCP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: tcp
     remote_ip_prefix: 0.0.0.0/0
- name: UDP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: udp
     remote_ip_prefix: 0.0.0.0/0
- name: ICMP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: icmp
     remote_ip_prefix: 0.0.0.0/0
- name: SSH Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: tcp
     port_range_min: 22
     port_range_max: 22
     remote_ip_prefix: 0.0.0.0/0
- name: Add network
  os_network:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ network_name }}"
     project: "{{ project }}"
     shared: no
     external: false
- name: Add subnet to network
  os_subnet:
     state: present
     cloud: "{{ os_project }}"
     project: "{{ project }}"
     network_name: "{{ network_name }}"
     name: "{{ subnet_name }}"
     cidr: "{{ subnet }}.0{{ cidr }}"
     gateway_ip: "{{ subnet }}.1"
     allocation_pool_start: "{{ subnet }}.2"
     allocation_pool_end: "{{ subnet }}.254"
     ip_version: 4
     dns_nameservers:
        - "{{ dns_server }}"
- name: Create router for private and external routing
  os_router:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ router_name }}"
     project: "{{ project }}"
     network: "{{ external_network_name }}"
     enable_snat: yes
     interfaces:
        - "{{ subnet_name }}"
- name: Create static port allocations
  os_port:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ inventory_hostname }}"
     network: "{{ network_name }}"
     fixed_ips:
       - ip_address: "{{ hostvars[inventory_hostname]['fixed_ip'] }}"
- name: Create apiserver instance
  os_server:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ inventory_hostname }}"
     image: "{{ hostvars[inventory_hostname]['image'] }}"
     key_name: "{{ ospuser }}"
     flavor: "{{ hostvars[inventory_hostname]['flavor'] }}"
     wait: yes
     timeout: 300
     nics:
       - port-name: "{{ inventory_hostname }}"
     auto_ip: no
```

##### EXPECTED RESULTS

The port should be created as expected.

##### ACTUAL RESULTS

There are 3 issues happening here:

1. The user / project specified in the auth is not used to determine where the port is created
2. There is no 'project' flag for os_port to explicitly define the project

If you attempt this via the openstack CLI specifying a project, it works.

Run as cluster admin user with project specified:
```
openstack port create --network second_network --fixed-ip ip-address=10.10.20.100 --enable --project second_project api

| aa6876e2-5484-49ff-a11f-8bceb0500125 | api                                                                 | fa:16:3e:86:90:db | ip_address='10.10.20.100', subnet_id='a8b34d12-e0e1-4614-851d-79bf8a80b9bd'    | UP  |
```

Delete port api.

Run again as second_project user, without specifying project:
```
openstack port create --network second_network --fixed-ip ip-address=10.10.20.100 --enable api

| 43730949-15a0-4138-8354-2027084eb163 | api                                                                 | fa:16:3e:22:f9:4d | ip_address='10.10.20.100', subnet_id='a8b34d12-e0e1-4614-851d-79bf8a80b9bd'    | UP   |
``

Either way, it works using the cli. Even without the ability to specify the project, it should create the port against the specified network using the user that issued the command. It should definitely not target a completely different subnet in a totally different project.

```paste below
fatal: [api]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "admin_state_up": null,
            "allowed_address_pairs": null,
            "api_timeout": null,
            "auth": null,
            "auth_type": null,
            "availability_zone": null,
            "binding:vnic_type": "normal",
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "device_id": null,
            "device_owner": null,
            "extra_dhcp_opts": null,
            "fixed_ips": [
                {
                    "ip_address": "10.10.20.10"
                }
            ],
            "interface": "public",
            "mac_address": null,
            "name": "api",
            "network": "second_network",
            "no_security_groups": false,
            "port_security_enabled": null,
            "region_name": null,
            "security_groups": null,
            "state": "present",
            "timeout": 180,
            "validate_certs": null,
            "wait": true
        }
    },
    "msg": "Error updating port 9b0b460b-65cd-4527-be76-c565dbf2b6d6: Client Error for url: https://10.37.197.10:13696/v2.0/ports/9b0b460b-65cd-4527-be76-c565dbf2b6d6.json, IP address 10.10.20.10 is not a valid IP for any of the subnets on the specified network."
}
```

##### WORKAROUND
If I remove admin from my user after creating the network, subnet and router and before creating the port, the port creation is successful on the correct subnet in the correct project.
