### ISSUE TITLE
Inconsistent variable visibility for subsequent tasks when using `vars` parameter on [include,import]_[role,tasks]

### ISSUE THREAD

**Issue by lucendio** [ansible/ansible#62032]
##### SUMMARY
Variables declared with the `vars` parameter might still be visible to (leak into) subsequent tasks depending on the module being used (`import_role`). Compared to the other three variations this could be seen as an inconsistent behavior.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`[include,import]_[role,tasks]`

##### ANSIBLE VERSION
tested against https://github.com/ansible/ansible/commit/e0ebc8c9b4ca1d4f6d7bb88a26e264eaeaee1c2b as well as [v2.8.4](https://github.com/ansible/ansible/releases/tag/v2.8.4)
NOTE: output redacted
```paste below
ansible 2.8.4
  config file = ${HOME}/path/to/project/environments/local/ansible.cfg
  configured module search path = ['${HOME}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ${HOME}/path/to/project/.python_modules/lib/python3.7/site-packages/ansible
  executable location = ${HOME}/path/to/project/.python_modules/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:32) [Clang 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
NOTE: output redacted
```paste below
DEFAULT_BECOME(${HOME}/path/to/project/environments/local/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(${HOME}/path/to/project/environments/local/ansible.cfg) = True
DEFAULT_HASH_BEHAVIOUR(${HOME}/path/to/project/environments/local/ansible.cfg) = merge
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = ${HOME}/path/to/project/.logs/bootstrap.log
DEFAULT_PRIVATE_KEY_FILE(${HOME}/path/to/project/environments/local/ansible.cfg) = ${HOME}/path/to/project/.vagrant/credentials/ssh-key.prv"
DEFAULT_REMOTE_USER(${HOME}/path/to/project/environments/local/ansible.cfg) = provisioner
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['${HOME}/path/to/project/.galaxy_roles', '${HOME}/path/to/project/roles']
DEFAULT_TRANSPORT(${HOME}/path/to/project/environments/local/ansible.cfg) = ssh
HOST_KEY_CHECKING(${HOME}/path/to/project/environments/local/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-52-generic x86_64)

##### STEPS TO REPRODUCE
`roles/some-tasks/main.yml`
```yaml
- name: ensure dir
  file:
    dest: "/tmp/foo"
    state: directory
- name: create file
  copy:
    content: |
      {{ foo }}
    dest: "/tmp/foo/{{ name }}"
```

`playbook_role.yaml`
```yaml
- hosts: all
  tasks:
    - [include,import]_role:
        name: some-tasks
      vars:
        name: "A"
        foo: "A"
    - [include,import]_role:
        name: some-tasks
      vars:
        name: "B"
        bar: "B"
```
`playbook_tasks.yaml`
```yaml
- hosts: all
  tasks:
    - import_tasks: ./roles/some-tasks/tasks/main.yml
      vars:
        name: "A"
        foo: "A"
    - import_tasks: ./roles/some-tasks/tasks/main.yml
      vars:
        name: "B"
        bar: "B"
```

##### EXPECTED RESULTS
That's a bit hard to say. One could argue that it should be consistent for all `import`s and/or - which actually would make more sense - `include`s, since variables are assigned during runtime (if I'm not mistaken). Another perspective would be to see `vars` as arguments for a "function" (=task), thus should not leak to other tasks at all.  But this could break code implicitly relying on this behavior.

##### ACTUAL RESULTS
When using `import_role` for the first task, all variables defined under `vars` for that task, are visible to subsequent tasks. When using one of the other tree modules (include_role, import_tasks, include_tasks) as the first task, its `vars` are NOT visible to subsequent tasks.

```bash
$   cat /tmp/foo/B
A
```
