### ISSUE TITLE
Pamd Module does not consider the possibility of duplicate parameters. State: args_present

### ISSUE THREAD

**Issue by pennking** [ansible/ansible#62046]
##### SUMMARY

When using the pamd module with state: args_present, it does not consider the possibility of duplicate parameters in the line. In my opinion, if args_present notices duplicate parameters in the line in question, it should remove all of duplicate instances and leave one instance with the correct value.

##### ISSUE TYPE
- Bug Report
- Suggestion for Functionality

##### COMPONENT NAME

pamd module Ansible

##### ANSIBLE VERSION

```paste below
Ansible 2.7.12
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ansible host(Ubuntu) and targets(Ubuntu, RHEL) 

##### STEPS TO REPRODUCE

```yaml
- name: "Verify if the required pam lines exist in the {{ pam_files }}
      files."
      pamd:
        name: "common-password"
        type: "auth"
        control: "required"
        module_path: "pam_faillock.so"
        module_arguments:
          - deny=5
          - unlock_time=3600
          - fail_interval=86400
        state: args_present
        path: /home/david
```

##### EXPECTED RESULTS

Existing line in pam file:
auth       required pam_faillock.so preauth silent audit deny=4 unlock_time=3600 audit fail_interval=86400 deny=7

(**Expected result**)
auth       required pam_faillock.so preauth silent unlock_time=3600 audit fail_interval=86400 **deny=5**
(**I expected that there would be one instance of the parameter with the correct value**)

##### ACTUAL RESULTS

```paste below
auth       required pam_faillock.so preauth silent audit deny=4 unlock_time=3600 audit fail_interval=86400 deny=5
```
(As seen above, it ignores the first instance of **deny** and changes the last instance of **deny**)
