### ISSUE TITLE
rocketchat: please support messages from personal account

### ISSUE THREAD

**Issue by asarubbo** [ansible/ansible#62050]
##### SUMMARY
Please support messages from a personal account.
##### ISSUE TYPE
I would like to send messages on rocket chat by using my personal account (via api) instead of an incoming webhook.
The module seems to not support that.

##### COMPONENT NAME
rocketchat

##### ADDITIONAL INFORMATION

I'm using the following atm:

```yaml
    - name: Rocket.Chat notification
      uri:
        url: "{{ rocket_url }}"
        method: "POST"
        status_code: "200"
        body_format: "json"
        body:
          channel: "{{ rocket_channel }}"
          alias: "Ansible"
          avatar: "{{ rocket_avatar_black }}"
          text: "test"
        headers:
          Content-Type: "application/json"
          X-Auth-Token: "{{ rocket_auth_token }}"
          X-User-Id: "{{ rocket_user_id }}"
```
