### ISSUE TITLE
When using loop_control with pause, loop should not pause when a task is skipped

### ISSUE THREAD

**Issue by ejez** [ansible/ansible#62057]
##### SUMMARY

When using loop_control with pause, loop should not pause when a task is skipped
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

!component
##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pyvenvs/ansible_controller/lib/python3.6/site-packages/ansible
  executable location = /opt/pyvenvs/ansible_controller/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
  - debug: msg="{{ item|string + ' ==> ' + lookup('pipe','date') }}"
    when: item in [8,9]
    loop: [1,2,3,4,5,6,7,8,9]
    loop_control:
      pause: 10
```

##### EXPECTED RESULTS

The general use case for pausing between tasks is to wait for something to finish as a result of a task execution before running the next task. When a task is skipped, there is no point to pause for the next task, pausing will result only in slowing down the loop without any benefit.

I think this should be the default behavior, if the actual behavior is still wanted we can add a new directive like "pause_between_skipped_tasks" (shoud default to "false")

##### ACTUAL RESULTS

```paste below

```
