### ISSUE TITLE
Terraform: Add support for create destroy plans

### ISSUE THREAD

**Issue by bkmeneguello** [ansible/ansible#62086]
##### SUMMARY

Terraform support `-destroy` flag in `plan` command. This should be supported by `planned` state.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml
- terraform:
    project_path: ./terraform
    state: planned
    state_file: tfplan
    destroy: true
```
