### ISSUE TITLE
no_log obscures loop_control label

### ISSUE THREAD

**Issue by andyfeller** [ansible/ansible#62091]
##### SUMMARY

`no_log` argument results in useless loop control label

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

callback

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = None
  configured module search path = ['/Users/afeller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.4_2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:29:04) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Darwin afeller-mbp 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

##### STEPS TO REPRODUCE

Run provided playbook.  Tested with ansible 2.8.2 and 2.8.4

```yaml
- hosts: localhost
  connection: local
  vars:
    things:
      - label: this is not
        secret: this is secret
      - label: this is not
        secret: this is secret
  tasks:
    - name: "Loop control label shouldn't always be obscured"
      debug:
        msg: "Let me tell you my {{ item.secret }}"
      with_items: "{{ things }}"
      no_log: yes
      loop_control:
        label: "{{ item.label }}"
```

##### EXPECTED RESULTS

I expected the item for each thing printed to show the label specified despite being `no_log: yes`.

##### ACTUAL RESULTS

Each item displayed `None`.

```paste below
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Loop control label shouldn't always be obscured] *************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost]

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
