### ISSUE TITLE
Windows modules running with Become can break JSON return parsing

### ISSUE THREAD

**Issue by veaviticus** [ansible/ansible#62102]
##### SUMMARY
Windows modules, run under Become, featuring Powershell commands that output something to stdout when not assigned to a variable cause Ansible to fail to parse the returned JSON string.

This affects everything from 2.5.1 to 2.7.13.
2.8.x is fine.

It was this commit that caused the issue: https://github.com/ansible/ansible/commit/38a13f41cdb49e429acb4f0a757c009102af087d.

I have reverted that commit locally and the issue is no longer present.

Related to #59803 (and likely others as mentioned in the comments on that issue)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible.ModuleUtils.CommandUtil
powershell
windows modules

##### ANSIBLE VERSION
```
ansible 2.7.13
  config file = None
  configured module search path = ['/home/rob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rob/.conda/envs/ansible/lib/python3.7/site-packages/ansible
  executable location = /home/rob/.conda/envs/ansible/bin/ansible
  python version = 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
```

##### CONFIGURATION
Nothing was reported here.

##### OS / ENVIRONMENT
Ansible Host:
    Fedora 30
    Fresh install of Ansible 2.7.13 in a clean Python 3.7.4 virtualenv

Ansible Targets:
    Have tested against Win10, Win2012 and Win2016

##### STEPS TO REPRODUCE
1) Create a simple windows module that runs a powershell function that outputs to stdout if the result is not saved to a variable. Minimal case below (I named this module test_return.ps1):
```
#!powershell
#Requires -Version 4
$result = @{changed = $false;}
New-Item -Path "C:\tmp" -ItemType directory -Force
Write-Output $result | ConvertTo-Json -Compress -Depth 99
```
2) Create a minimal playbook that calls this module, using become, targeting a Windows machine
```yaml
- hosts: windows
  gather_facts: false
  tasks:
  - name: Test
    test_return:
    register: te_output
    become: true
```

3) Simple inventory file for this playbook
```yaml
all:
    children:
        windows:
            hosts:
                win_machine:
                    ansible_host: 172.29.27.14
                    name: win_machine
                    ansible_user: Administrator
                    ansible_password: foobar
                    ansible_become_user: Administrator
                    ansible_become_pass: foobar
                    ansible_become_method: runas
                    ansible_port: 5985
                    ansible_connection: winrm
                    ansible_winrm_server_cert_validation: ignore
                    ansible_winrm_read_timeout_sec: 300
    hosts: {}
```

4) Execute the playbook

##### EXPECTED RESULTS
Sucessful return like this:
```
PLAY [windows] *********************************************************************************************************************************************************

TASK [Test] ************************************************************************************************************************************************************
ok: [win_machine]

PLAY RECAP *************************************************************************************************************************************************************
win_machine                : ok=1    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
The module is marked failed by Ansible with the following output
```
PLAY [windows] *********************************************************************************************************************************************************

TASK [Test] ************************************************************************************************************************************************************
fatal: [win_machine]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "C:\\tmp {\"changed\":false}\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}

PLAY RECAP *************************************************************************************************************************************************************
win_machine                : ok=0    changed=0    unreachable=0    failed=1
```

[This function](https://github.com/ansible/ansible/blob/v2.7.8/lib/ansible/module_utils/json_utils.py#L54) raises a ValueError since the reutrn string is not valid JSON. The return is `C:
tmp {\"changed\"`, where that leading C:\tmp shouldn't be there.

This functions attempts to filter out these leading non-json bits, but only filters entire lines that are preceding the json, it can't handle the case where there's junk on the same line as where the JSON starts (this case).

That raises to [here](https://github.com/ansible/ansible/blob/v2.7.8/lib/ansible/plugins/action/__init__.py#L879) where we catch the ValueError and fail the module with a generic "MODULE FAILURE" message, throwing the entire stdout ansible got as the module_stdout.

##### WORKAROUNDS

1)

By forcing a newline before the JSON return in the module, we can leverage the python "invalid JSON filter" function linked above; it will successfully strip any junk before the json starts, and things will work.
```
#!powershell
#Requires -Version 4
$result = @{changed = $false;}
New-Item -Path "C:\tmp" -ItemType directory -Force
Write-Output `r`n
Write-Output $result | ConvertTo-Json -Compress -Depth 99
```

2)

Remove the `#Requires -Version 4` line. Without this line... everything works just fine. Add this line (with any valid powershell version as the value), and suddenly we're broken. I'm not sure why on that yet.
