### ISSUE TITLE
checksum_url parameter for win_get_url fails with POSIX repositories

### ISSUE THREAD

**Issue by mtkunkel** [ansible/ansible#62106]
##### SUMMARY

`checksum_url` causes `win_get_url` to fail when downloading from a maven (or other POSIX-ish) repository.   It appears win_get_url is expecting some specific format for the checksum, including a windows carriage return?   Is this parameter supposed to be specific to NuGet style repositories?   I may attempt to fix it, just not a windows / `.ps1` expert. https://github.com/ansible/ansible/blame/0f52b18f3f42626ac1499a49d4a58c78d1a1ab32/lib/ansible/modules/windows/win_get_url.ps1#L55

Alternately, should this functionality be deprecated in favor of `{{lookup}}`?  Technically `lookup` is more efficient as the ansible controller would resolve checksums in lieu of each endpoint.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_get_url
##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/matt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/matt/venvs/ansible28/lib/python3.7/site-packages/ansible
  executable location = /home/matt/venvs/ansible28/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True

```

##### OS / ENVIRONMENT

Windows Server 2012
Windows Server 2016

##### STEPS TO REPRODUCE

Use a checksum_url targeting a maven repository.

```yaml
---
- hosts: windows
  gather_facts: False
  vars:
    artifactFilename: "Test_artifact.jar"
    artifactUrl:      "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar"
    artifactSha1Url:  "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar.sha1"
    artifactPath: "C:\\Windows\\Temp\\{{artifactFilename}}"

  tasks:
    - name: demonstrate working lookup
      win_get_url:
        url: "{{ artifactUrl }}"
        dest: "{{ artifactPath }}"
        force: no
        checksum:  "{{ lookup('url', artifactSha1Url, split_lines=False) }}"  # More efficient as the lookup happens once (control node)
        checksum_algorithm: sha1

    - name: checksum_url not working
      win_get_url:
        url: "{{ artifactUrl }}"
        dest: "{{ artifactPath }}"
        force: no
        checksum_url: "{{ artifactSha1Url }}"   # This should work but it doesn't. Each endpoint resolves sha1.
        checksum_algorithm: sha1
```

##### EXPECTED RESULTS

Artifact is downloaded and checksum validation succeeds.

##### ACTUAL RESULTS

Download fails with `Checksum record not found for file name 'metadata-extension-1\\.0\\.jar' in file` See logs below:

```paste below
(ansible28) [matt@archklap checksum_url_example]$ ansible-playbook -i ../windoze_inventory.yml main.yml -vvvv
ansible-playbook 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/matt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/matt/venvs/ansible28/lib/python3.7/site-packages/ansible
  executable location = /home/matt/venvs/ansible28/bin/ansible-playbook
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/matt/Documents/repos/windoze_inventory.yml as it did not pass it's verify_file() method
script declined parsing /home/matt/Documents/repos/windoze_inventory.yml as it did not pass it's verify_file() method
Parsed /home/matt/Documents/repos/windoze_inventory.yml inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/matt/venvs/ansible28/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: main.yml ***********************************************************************************************************************************
Positional arguments: main.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/matt/Documents/repos/windoze_inventory.yml',)
forks: 5
1 plays in main.yml

PLAY [windows] ***************************************************************************************************************************************
META: ran handlers

TASK [demonstrate working lookup] ********************************************************************************************************************
task path: /home/matt/Documents/repos/checksum_url_example/main.yml:12
url lookup connecting to https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar.sha1
Using module file /home/matt/venvs/ansible28/lib/python3.7/site-packages/ansible/modules/windows/win_get_url.ps1
Pipelining is enabled.
<WIN-UAGDK560E13.lan> ESTABLISH WINRM CONNECTION FOR USER: localhost\Administrator on PORT 5985 TO WIN-UAGDK560E13.lan
EXEC (via pipeline wrapper)
changed: [WIN-UAGDK560E13.lan] => {
    "changed": true,
    "checksum_dest": "c81d03f3a7800f7190c14548d2a91b0d26af6ec4",
    "checksum_src": "c81d03f3a7800f7190c14548d2a91b0d26af6ec4",
    "dest": "C:\\Windows\\Temp\\Test_artifact.jar",
    "elapsed": 3.1868874,
    "invocation": {
        "module_args": {
            "checksum": "c81d03f3a7800f7190c14548d2a91b0d26af6ec4",
            "checksum_algorithm": "sha1",
            "checksum_url": null,
            "dest": "C:\\Windows\\Temp\\Test_artifact.jar",
            "force": false,
            "force_basic_auth": false,
            "headers": {},
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "timeout": 10,
            "url": "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "OK",
    "size": 3199408,
    "status_code": 200,
    "url": "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar"
}

TASK [checksum_url not working] **********************************************************************************************************************
task path: /home/matt/Documents/repos/checksum_url_example/main.yml:20
Using module file /home/matt/venvs/ansible28/lib/python3.7/site-packages/ansible/modules/windows/win_get_url.ps1
Pipelining is enabled.
<WIN-UAGDK560E13.lan> ESTABLISH WINRM CONNECTION FOR USER: localhost\Administrator on PORT 5985 TO WIN-UAGDK560E13.lan
EXEC (via pipeline wrapper)
fatal: [WIN-UAGDK560E13.lan]: FAILED! => {
    "changed": false,
    "dest": "C:\\Windows\\Temp\\Test_artifact.jar",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "checksum": null,
            "checksum_algorithm": "sha1",
            "checksum_url": "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar.sha1",
            "dest": "C:\\Windows\\Temp\\Test_artifact.jar",
            "force": false,
            "force_basic_auth": false,
            "headers": {},
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "timeout": 10,
            "url": "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Checksum record not found for file name 'metadata-extension-1\\.0\\.jar' in file from url: 'https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar.sha1'",
    "url": "https://repo1.maven.org/maven2/com/redhat/engineering/maven/extensions/metadata-extension/1.0/metadata-extension-1.0.jar"
}

PLAY RECAP *******************************************************************************************************************************************
WIN-UAGDK560E13.lan        : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
