### ISSUE TITLE
VMware: vmware_guest module does not run customization for RHEL 8 images

### ISSUE THREAD

**Issue by jbertozzi** [ansible/ansible#62139]
Hi,

##### SUMMARY

While using vmware_guest to provision RHEL 8 images, the customization is ignored. Machine is deployed, without correct network configuration, NIC not connected (despite the `start_connected``set to true). The dns_suffix and the domain are also ignored.
This works well for RHEL7 VM.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest with VMware ESXi, version 6.7.0, build 13644319

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /home/ansible/infra/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

OS: RHEL 7.7
python version: 2.7.5
ansible version: 2.8.4
VMware ESXi, 6.7.0, 13644319
open-vm-tools (guest OS): 10.3.0
 
##### STEPS TO REPRODUCE

Run the following task in a playbook:

```
  - name: Deploy the template
    vmware_guest:
      hostname: "{{ vmware_hostname }}"
      username: "{{ vmware_username }}"
      password: "{{ vmware_password }}"
      validate_certs: False
      name: "{{ inventory_hostname }}"
      template: tpl-rhel{{ servers[inventory_hostname]['os'] | default('7') }}
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      state: poweredon
      cluster: "{{ cluster }}"
      wait_for_ip_address: false
      hardware:
        num_cpus: "{{ servers[inventory_hostname]['cpu'] }}"
        memory_mb: "{{ servers[inventory_hostname]['ram'] * 1024 }}"
      disk:
      - size_gb: 20
        type: thin
        datastore: "{{datastore }}"
      - size_gb: "{{ servers[inventory_hostname]['disk'] }}"
        type: thin
        datastore: "{{ datastore }}"
      customization:
        dns_servers:
          - "{{ dns_server }}"
        dns_suffix:
          - "{{ dns_suffix }}"
        domain: "{{ domain }}"
        hostname: "{{ inventory_hostname }}"
      networks:
      - name: "{{ network_vcenter }}"
        start_connected: true
        ip: "{{ip.split('/')[0] }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
    delegate_to: localhost
```

##### EXPECTED RESULTS

Customization is being applied.

##### ACTUAL RESULTS

VM is deployed, with no customization.

EDIT: provide vmware tools version  and more details about result
