### ISSUE TITLE
jenkins_script crumb not generated

### ISSUE THREAD

**Issue by tux-84** [ansible/ansible#62142]
##### SUMMARY
Using the latest Ansible and Jenkins version, it seems that jenkins_script is broken again (see #23250). The message "HTTP error 403 HTTP Error 403: No valid crumb was included in the request" comes up again. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
jenkins_script
##### ANSIBLE VERSION

```paste below
2.8.4
```
##### OS / ENVIRONMENT

Target OS: Debian Stretch
Ansible Controller: Debian Stretch
Proivisioned by ansible_local using Vagrant

##### STEPS TO REPRODUCE

```yaml
- name: Enbabling maintenance mode
  jenkins_script:
    script: |
      import jenkins.model.*;
      Jenkins.instance.doQuietDown();
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
  when: jenkins_admin_password != ""
```

##### EXPECTED RESULTS

Run groovy script properly
##### ACTUAL RESULTS

```paste below
fatal: [jenkins]: FAILED! => {"changed": false, "msg": "HTTP error 403 HTTP Error 403: No valid crumb was included in the request", "output": ""}
```
