### ISSUE TITLE
"win_domain_computer" ansible module not able to delete the computer objects from Active Directory

### ISSUE THREAD

**Issue by manaspatkar22** [ansible/ansible#62145]
##### SUMMARY
"win_domain_computer" ansible module not able to delete the computer objects from Active Directory

##### ISSUE TYPE
- Bug

##### COMPONENT NAME
Ansible Module Name: win_domain_computer

##### ANSIBLE VERSION
Ansible Versiom
```
ansible 2.8.4
  config file = /home/xxxxxxx/repos/ansible-playbooks/ansible.cfg
  configured module search path = [u'/home/xxxxxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/home/xxxxx/repos/ansible-playbooks/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=120m
ANSIBLE_SSH_RETRIES(/home/xxxx/repos/ansible-playbooks/ansible.cfg) = 10
DEFAULT_GATHERING(/home/xxxxx/repos/ansible-playbooks/ansible.cfg) = explicit
DEFAULT_LOG_PATH(/home/xxxxx/repos/ansible-playbooks/ansible.cfg) = /home/xxxxxx/repos/ansible-playbooks/ansible.log
DEFAULT_ROLES_PATH(/home/xxxxx/repos/ansible-playbooks/ansible.cfg) = [u'/home/i275943/repos/ansible-playbooks/roles']
DEFAULT_TIMEOUT(/home/xxxxxx/repos/ansible-playbooks/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/xxxxxxx/repos/ansible-playbooks/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/xxxxx/repos/ansible-playbooks/ansible.cfg) = False

```
##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE

```
- name: Remove Computer OU Object from Active Directory
  win_domain_computer:
        domain_username: "domain\\uid"
        domain_password: "password"
        domain_server: "active directory server name"
        name: "computer name"
        state: absent
```
Here computer name is "CN=TestComp1,OU=APP12345,DC=dummynet

##### EXPECTED RESULTS
I should be able to delete the computer object from within Active Directory.

##### ACTUAL RESULTS

The module throws following error
```
fatal: [localhost -> dummyServer]: FAILED! => {
    "changed": false,
    "msg": "Failed to remove the AD object TestComp1: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running."
}
```
I am able to successfully delete the computer object in Active Directory using the below Powershell commands
```
   - name: Remove Computer OU object from Active Directory
      win_shell: |
           $secpasswd = ConvertTo-SecureString "{{ ldap_domain_password }}" -AsPlainText -Force
           $mycreds = New-Object System.Management.Automation.PSCredential ( "{{ ldap_domain_user }}", $secpasswd)
           Remove-ADComputer -Identity "{{ computer_name }}" -Credential $mycreds -Confirm:$false -Server "{{ ldap_server }}"
      register: remove_cn
      delegate_to: dummyServer
```
Here computer name is "CN=TestComp1,OU=APP12345,DC=dummynet

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_domain_computer.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain_computer.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Daniel-Sanchez-Fabregas @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ShachafGoldstein** [comment]
What are the connection params?

**Comment by ansiblejunky** [comment]
@ShachafGoldstein Connection params to connect to the ldap server? or the jump server that we delegate to? The server we delegate to is a windows server, so we use typical kerberos connection vars. 

Here is a great test.yml playbook I just put together that proves the issue. Both tasks use the same vars. The first task tries to use the module, which always seems to return "OK" with nothing more than that. The second task uses the shell command and it works great.  What's the difference? Seems to me the module is not working right at all.
The ldap_jump_server group in this example simply has 1 server that is a windows machine that is used for running the module or shell command. 

```
---
- hosts: localhost

  vars:
    ldap_domain_password: 'password'
    ldap_domain_user: 'adtest\myuser'
    ldap_server: ldap.adtest.net
    computer_name: TestComp4
    ldap_computer_name: "CN={{ computer_name }},OU=APP12345,OU=IaaS Non-Prod,OU=Servers,OU=HCSC,DC=adtest,DC=net"

  tasks:
  - name: Remove linux computer from Active Directory using a windows machine
    win_domain_computer:
      name: "{{ ldap_computer_name }}"
      domain_server: "{{ ldap_server }}"
      domain_username: "{{ ldap_domain_user }}"
      domain_password: "{{ ldap_domain_password }}"
      state: absent
    delegate_to: "{{ groups['ldap_jump_server'][0] }}"
    tags: module


  - name: Remove Computer OU object from Active Directory
    win_shell: |
         $secpasswd = ConvertTo-SecureString "{{ ldap_domain_password }}" -AsPlainText -Force
         $mycreds = New-Object System.Management.Automation.PSCredential ( "{{ ldap_domain_user }}", $secpasswd)
         Remove-ADComputer -Identity "{{ ldap_computer_name }}" -Credential $mycreds -Confirm:$false -Server "{{ ldap_server }}"
    register: remove_cn
    delegate_to: "{{ groups['ldap_jump_server'][0] }}"
    tags: shell
```
