### ISSUE TITLE
Add owner/group/mode options to the fetch module.

### ISSUE THREAD

**Issue by czacharym** [ansible/ansible#62147]
##### SUMMARY

Add owner, group and mode options to the fetch module.

##### ISSUE TYPE
- Feature Idea

  Add owner, group and mode options to the fetch module.

##### COMPONENT NAME
fetch module

##### ADDITIONAL INFORMATION
This feature would allow for fetch to set the owner, group and mode on a file that is fetched from a remote server.

```yaml

  - fetch:
    src: /tmp/uniquefile
    dest: /tmp/special/
    flat: yes
    owner: user1
    group: user1
    mode: 0644
```
