### ISSUE TITLE
template error in changed_when causes incorrect failure message (description edited)

### ISSUE THREAD

**Issue by nathanhruby** [ansible/ansible#6215]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.4.5
##### Environment:

Ubuntu 12.05, Mac OSX 10.9.2
##### Summary:

Using local_action with a failing command generate misleading error output
##### Steps To Reproduce:

Example playbook

```
  - name: local play
    hosts: all
    gather_facts: no
    tasks:
    - name: local command
      local_action: command bjork
      register: bjork
      changed_when: bjork.stdout.find("swans") != -1
```
##### Expected Results:

ansible tells me the command failed like any other command.

This pattern should register a failed (not unreachable),  output the failure info returned by the command module, and optimally indicate the correct host where the failed command ran.
##### Actual Results:

```
[nhruby@badhorse ~/tmp]$ ansible-playbook -i test.inv localtest.yml

PLAY [local play] *************************************************************

TASK: [local command] *********************************************************
fatal: [randomhost.who.cares] => error while evaluating conditional: bjork.stdout.find("swans") != -1

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/nhruby/localtest.retry

randomhost.who.cares       : ok=0    changed=0    unreachable=1    failed=0

[nhruby@badhorse ~/tmp]$
```
