### ISSUE TITLE
AIX at command uses different arguments -- matching and deleting a job doesn't work

### ISSUE THREAD

**Issue by czi** [ansible/ansible#62153]
##### SUMMARY
The AIX at command uses different arguments than other operating systems.  Matching and deleting a job doesn't work, as there is no special case code to handle this in the module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
at

##### ANSIBLE VERSION

```
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/home/a154700/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /u/a154700/ansible/lib/ansible
  executable location = /u/a154700/ansible/bin/ansible
  python version = 3.7.2 (default, Jan 25 2019, 13:18:36) [GCC 4.8.5]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Target systems running on AIX 7.1

##### STEPS TO REPRODUCE

```yaml
---

- hosts: all
  become: yes
  gather_facts: no

  tasks:

   - name: Match a command to an existing job and delete the job
     at:
      command: ls -d / >/dev/null
      state: absent

   - name: Schedule a command to execute in 20 minutes making sure it is unique in the queue
     at:
      command: ls -d / >/dev/null
      count: 20
      units: minutes


```

##### EXPECTED RESULTS

Tasks should succeed

##### ACTUAL RESULTS

Task fails with syntax error, as AIX uses different arguments to the at command

```paste below
 FAILED! => {"changed": false, "cmd": "/usr/bin/at -c root.1568309869c0.a", "msg": "at: syntax error", "rc": 1, "stderr": "at: syntax error\n", "stderr_lines": ["at: syntax error"], "stdout": "", "stdout_lines": []}
```
