### ISSUE TITLE
win_psexec hostnames supports "servers group" from host file

### ISSUE THREAD

**Issue by graphcut** [ansible/ansible#62163]
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml
- name: Run the setup.exe installer on multiple servers using the Domain Administrator
  win_psexec:
    command: E:\setup.exe /i /IACCEPTEULA
    hostnames:
    - remote_server1
    - remote_server2
    username: DOMAIN\Administrator
    password: some_password
    priority: high
```
ideally, we can use a host group from host file to replace remote_server1&2
