### ISSUE TITLE
Setting openssl_csr version has no effect

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#62227]
##### SUMMARY
Setting [openssl_csr](https://docs.ansible.com/ansible/latest/modules/openssl_csr_module.html)'s `version` parameter has no effect in ansible 2.8.4; it always remains the default (1).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssl_csr

##### ANSIBLE VERSION
```
ansible 2.8.4
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/bilge/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]
```

##### CONFIGURATION

```yaml
- name: Generate CSR
  openssl_csr:
    privatekey_path: /tmp/private.pem
    path: /tmp/csr
    subject_alt_name: DNS:example.com
    version: 3
```

##### EXPECTED RESULTS

```
Certificate Request:
    Data:
        Version: 3 (0x2)
```

##### ACTUAL RESULTS

>$ openssl req -in /tmp/csr -noout -text

```
Certificate Request:
    Data:
        Version: 1 (0x0)
```
