### ISSUE TITLE
network_cli always connects, even for local actions

### ISSUE THREAD

**Issue by mdutton3** [ansible/ansible#62220]
##### SUMMARY

Some local actions (e.g. debug, assert, set_fact, include_vars), which should always work, try to initiate a connection to the target host when `ansible_connection: network_cli` is set. This causes the task to fail when the host is not reachable or cannot authenticate.

This causes patterns like below to fail:

```yaml
- hosts: all,localhost # Always run
  gather_facts: no
  tasks:
  - assert:
      that: 'my_var is defined'
```

and

```yaml
- hosts: my-csr-hosts
  gather_facts: no
  tasks:
  - include_vars: my_very_important_vars.yml
  - set_fact:
      ansible_user: '{{ some_dynamically_generated_value }}'
  - ios_command: do stuff
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
network_cli connection plugin

##### ANSIBLE VERSION
Reproduced on ansible v2.5.15, 2.8.0, and 2.8.4

```paste below
ansible 2.8.4
  config file = None
  configured module search path = [u'/Users/mdutton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mdutton/.virtualenvs/ansible-2.8-py2/lib/python2.7/site-packages/ansible
  executable location = /Users/mdutton/.virtualenvs/ansible-2.8-py2/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION
```paste below
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /Users/mdutton/ansible-issue/ansible.log
```

##### OS / ENVIRONMENT
Python 2.7

##### STEPS TO REPRODUCE

```yaml
- hosts: all,localhost
  vars:
    # This would be set on some subset of hosts in inventory
    ansible_connection: network_cli
  gather_facts: no
  ignore_errors: yes
  tasks:
  - debug: msg="Test"
  - debug:
      msg: Test2
    connection: local
  - set_fact:
      ansible_user: super-admin
      ansible_password: shh-dont-tell
  - assert:
      that: '(2+2)==4'
```

A more complete set of pass & fail examples with logs can be found at:
https://gist.github.com/mdutton3/967a1cbfd6ec7f3a28711b9669981b3f

##### EXPECTED RESULTS

I expect these tasks to work the same whether the connection is local, smart, ssh, ..., or network_cli.

I expect to be able to invoke local actions without the network connection functioning.

##### ACTUAL RESULTS
The local actions described above trigger an unnecessary connection from the `network_cli` plugin, which may fail and prevent the local action from working.

Even if the action doesn't fail, it may trigger an unnecessary login into the remote host.

Complete example and `ansible.log` at:
https://gist.github.com/mdutton3/967a1cbfd6ec7f3a28711b9669981b3f
