### ISSUE TITLE
Cant make nsupdate work with Windows DNS

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#62238]
##### SUMMARY

Im trying to create DNS records on Windows DNS server using simple playbook but getting error TSIG key error: Incorrect padding
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nsupdate
##### ANSIBLE VERSION

```paste below
2.8.3
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

DNS runs on Windows 2012R2

##### STEPS TO REPRODUCE

Simple playbook where use AD credentils as key_name and key_secret

```yaml

---
- name: DNS  test
  hosts: localhost
  gather_facts: no
  
  vars:
    ad_dns_user: "dns_admin"
    ad_ns_password: "password"
    dns_server: my.dns.server
    dns_zone: my.zone1.com

- name: TEST DNS update"
      nsupdate:
        key_name: "{{ ad_dns_user }}"
        key_secret: "{{ ad_dns_password }}"
        server: "{{ dns_server }}"
        zone: "{{dns_zone}}"
        record: "test-ans001"
        value: "10.0.10.12"
```

##### EXPECTED RESULTS

expected is creation of DNS A record

##### ACTUAL RESULTS

error "TSIG key error: Incorrect padding"

```paste below

```
