### ISSUE TITLE
cloudtrail : OUTPUT.exists returns false when creating a trail

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#62239]
##### SUMMARY

See also #61919 (Integration tests for Cloudtrail)

When creating a new trail the exists return value returns false.  Except in check mode...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/cloudtrail.py

##### ANSIBLE VERSION

devel

##### CONFIGURATION

"ansible-test" docker environment

##### OS / ENVIRONMENT

"ansible-test" docker environment

##### STEPS TO REPRODUCE

```
  - name: 'Create a trail'
    cloudtrail:
      state: present
      name: '{{ cloudtrail_name }}'
    register: output
  - assert:
      that:
      - output is changed
      - output.exists == True
      - output.trail.name == cloudtrail_name
```
##### EXPECTED RESULTS

exists is set to true

##### ACTUAL RESULTS

exists is set to false.
