### ISSUE TITLE
cloudtrail: tag keys get mangled

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#62243]
##### SUMMARY

See also #61919 (Integration tests for Cloudtrail)

the case of tag keys is being modified (and shouldn't be)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/cloudtrail.py

##### ANSIBLE VERSION

devel

##### CONFIGURATION

"ansible-test" docker environment

##### OS / ENVIRONMENT

"ansible-test" docker environment

##### STEPS TO REPRODUCE

```
    cloudtrail:
      state: present
      name: '{{ cloudtrail_name }}'
      tags:
        tag2: Value2
        Tag3: Value3
    register: output
  - assert:
      that:
      - output is changed
      - output.trail.name == cloudtrail_name
      - output.trail.tags | length == 2
      - '("tag2" in output.trail.tags) and (output.trail.tags["tag2"] == "Value2")'
      - '("Tag3" in output.trail.tags) and (output.trail.tags["Tag3"] == "Value3")'```
```

##### EXPECTED RESULTS

assertion passes

##### ACTUAL RESULTS

assertion fails (Tag3 -> tag3)
