### ISSUE TITLE
cloudtrail : Changed always returns true when using a KMS alias

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#62242]
##### SUMMARY

See also #61919 (Integration tests for Cloudtrail)

If you use an alias for the KMS CMK changed always returns true

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/cloudtrail.py

##### ANSIBLE VERSION

devel

##### CONFIGURATION

"ansible-test" docker environment

##### OS / ENVIRONMENT

"ansible-test" docker environment

##### STEPS TO REPRODUCE

```

  - name: 'Update logging encryption to alias'
    cloudtrail:
      state: present
      name: '{{ cloudtrail_name }}'
      kms_key_id: 'alias/{{ kms_alias }}'
    register: output
  - assert:
      that:
      - output is changed
      - output.trail.kms_key_id == kms_key.key_arn

  - name: 'Update logging encryption to alias (no change)'
    cloudtrail:
      state: present
      name: '{{ cloudtrail_name }}'
      kms_key_id: 'alias/{{ kms_alias }}'
    register: output
  - assert:
      that:
      - output is not changed
      - output.trail.kms_key_id == kms_key.key_arn
```

##### EXPECTED RESULTS

The second changed should return false

##### ACTUAL RESULTS

Changed always returns true
