### ISSUE TITLE
ec2_tag fails to remove 'true' or 'false' strings

### ISSUE THREAD

**Issue by coopernurse** [ansible/ansible#6225]
When using `ec2_tag state=absent` on tags with values of 'true' or 'false', the value is not removed.  Example:

```
- name: Remove tag
  local_action: ec2_tag
  sudo: false
  args:
    resource: my-resource
    state: absent
    tags:
      available: true
```

I debugged this a bit, and it appears to be due to how Ansible serializes and deserializes arguments.  When the ec2_tag script receives the map, the 'true' value is deserialized as a Python boolean, causing https://github.com/ansible/ansible/blob/devel/library/cloud/ec2_tag#L155 to test true, and the command to no-op.

I haven't tested this with numeric values, but they may be broken too if they're deserialized into python int/float types.

I'm not sure of the best fix. I don't think we can simply call str(value) to convert back to string because the boolean will come back as "True" instead of "true".

I'm working around this by avoiding the use of 'true' and 'false' as tag values, but others may run into this.

**Comment by ansibot** [comment]
Thanks for filing a ticket! I am the friendly GitHub Ansibot. I see you did not fill out your issue description based on our new issue template. Please copy the contents of this [template](https://raw2.github.com/ansible/ansible/devel/examples/issues/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket. 

Our system will automatically close tickets that do not have an issue template filled out within 7 days. Please note that due to large interest in Ansible, humans may not comment on your ticket if you ask them questions. Don't worry, you're still in the queue and the robots are looking after you.

**Comment by coopernurse** [comment]
Apologies, it looks like this is probably a feature, quoting the value works properly:

```
- name: Remove tag
  local_action: ec2_tag
  sudo: false
  args:
    resource: my-resource
    state: absent
    tags:
      available: "true"
```

Thanks
