### ISSUE TITLE
ecs_task_definition - specify protocol port mapping

### ISSUE THREAD

**Issue by tnielsen2** [ansible/ansible#62284]
##### SUMMARY

The ecs_task_definition does not appear to have the ability to specify the port used in the PortMapping configuration portion of the module. 

##### ISSUE TYPE
- Feature Idea
Add a switch to the PortMappings section to allow the ability to select udp. Seems to only default to tcp. 

##### COMPONENT NAME
ecs_task_definition

##### ADDITIONAL INFORMATION
Through the console when specifying the PortMappings, add a switch that will configure it for udp. 

```yaml

- name: Create task definition
  ecs_taskdefinition:
    region: "{{ task_service.aws_ecs_region }}"
    containers:
    - name: "{{ ecs_environment }}-{{ task_service.aws_ecs_app_name }}"
      essential: true
      image: "{{ task_service.aws_ecs_image }}"
      portMappings:
      - containerPort: "{{ task_service.aws_ecs_container_port }}"
        hostPort: "{{ task_service.aws_ecs_host_port }}"
        protocol: 'udp'
    launch_type: "{{ task_service.launch_type }}"
    cpu: "{{ task_service.aws_ecs_cpu }}"
    task_role_arn: "{{ task_service.aws_ecs_role }}"
    execution_role_arn: "{{ task_service.aws_ecs_role }}"
    memory: "{{ task_service.aws_ecs_memory }}"
    state: present
    family: "{{ ecs_environment }}-{{ task_service.aws_ecs_task_name }}"

```
