### ISSUE TITLE
Conditional loop over subset of computers fails

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#62280]
##### SUMMARY
Using loop inside block which has condition to certain machines fail.
All tasks (those without loop) in block are executed correctly just on the intended machine, it says "skipping" for all other machines, but when it comes to task where loop is present it behaves incorrectly and starts to consider all machines again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
loop

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
```yaml
- block:
  - name: find master stack files
    find:
        paths: "{{azure_mount_path}}/core.services/master"
        patterns: docker-stack.yml
        recurse: true
    register: master_compose_files

  - name: extract parent paths
    set_fact:
      master_compose_files: "{{master_compose_files | json_query('files[*].path') | list}}"

  - debug: "msg='{{item.split('/')[-2]}}'"
    loop: "{{master_compose_files}}"
  when: inventory_hostname in groups['master']
```

##### EXPECTED RESULTS
Block is executed only on machines in 'master' group, loop variable should not even be attempted to be assigned for other machines

##### ACTUAL RESULTS

```paste below
TASK [/mnt/d/Repos/toolbox/Azure/07_ansible/app_deploy/docker_core : find master stack files] ***********************************************************************************************************************************************
skipping: [dockercilin2]
skipping: [dockercilnpl1]
skipping: [dockerciwin1]
ok: [dockercilin1]

TASK [/mnt/d/Repos/toolbox/Azure/07_ansible/app_deploy/docker_core : extract parent paths] **************************************************************************************************************************************************
ok: [dockercilin1]
skipping: [dockercilin2]
skipping: [dockercilnpl1]
skipping: [dockerciwin1]

TASK [/mnt/d/Repos/toolbox/Azure/07_ansible/app_deploy/docker_core : debug] *****************************************************************************************************************************************************************
ok: [dockercilin1] => (item=/mnt/docker-repo/master/core.services/master/redis/docker-stack.yml) => {
    "msg": "redis"
}
ok: [dockercilin1] => (item=/mnt/docker-repo/master/core.services/master/traefik/docker-stack.yml) => {
    "msg": "traefik"
}
fatal: [dockercilin2]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
fatal: [dockercilnpl1]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
fatal: [dockerciwin1]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```
