### ISSUE TITLE
IOS VRF import/export route target

### ISSUE THREAD

**Issue by EarlRamirez** [ansible/ansible#62299]
##### SUMMARY

When adding VRF import/export route-target the value is converted to an integer; therefore, when the playbook has executed the command fails. For example, if I have an import/export of 65111:80, 3907716. Also when I explicitly specify ipv4 I am also seeing ipv6 for the vrf.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_vrf
##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/netadm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
No output produced by the command
```

##### OS / ENVIRONMENT

Cisco IOS XE Software, Version 16.09.03

##### STEPS TO REPRODUCE

```yaml
---
- name: Create new VRF, SVI, VLAN, and HSRP
  hosts: cores
  connection: local
  gather_facts: no

  tasks:
  - name: Gather hardware facts
    ios_facts:
      gather_subset:
        - hardware

  - name: Configure Test One VRF (route import)
    ios_vrf:
      name: test1
      rd: 61111:800
      route_both_ipv4:
        - 61111:80
        - 61111:80
      state: present
```

##### EXPECTED RESULTS

When the route-target import/export is sent to the device it must send what is defined in the playbook, for example, if an import target of 11111:22 it should be sent and not an arbitrary integer which is rejected by the destination device.  

##### ACTUAL RESULTS

```paste below
changed: [xxxxxx] => {"changed": true, "commands": ["vrf definition test1", "address-family ipv4", "exit", "address-family ipv6", "exit", "rd 65111:800", "address-family ipv4", "route-target import 3907716", "route-target import 3907716", "exit-address-family", "address-family ipv4", "route-target export 3907716", "route-target export 3907716", "exit-address-family"]}
```
