### ISSUE TITLE
junos_interfaces data model does not match ios_interfaces

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#62319]
##### SUMMARY
the data model for junos_interfaces does not match ios_interfaces for resource modules

```
            "interfaces": [
                {
                    "enable": true,
                    "name": "fxp0"
                }
            ],
```

junos_interfaces (https://docs.ansible.com/ansible/devel/modules/junos_interfaces_module.html) versus enabled for ios_interfaces (e.g. https://docs.ansible.com/ansible/devel/modules/ios_interfaces_module.html)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_interfaces

I think we should take a long look at all juniper modules and make sure testing is being done to ensure the data model across all resource modules

##### ANSIBLE VERSION
```paste below
devel latest
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### STEPS TO REPRODUCE
junos facts

```yaml
#https://github.com/ansible/ansible/issues/61183
- name: grab juniper junos info
  junos_facts:
    gather_subset: min
    gather_network_resources: "{{network_resources}}"
```

##### EXPECTED RESULTS
matching data model

##### ACTUAL RESULTS
```
{
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'enabled'",
    "changed": false,
    "_ansible_no_log": false
}
```
