### ISSUE TITLE
docker container loses networks on restarts when using with init: true

### ISSUE THREAD

**Issue by DaAllexx** [ansible/ansible#62324]
##### SUMMARY

With `init: true` set in the `docker_container` module, a container restarted with `docker_container` loses it network settings and is attached to the default bridge again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* `docker_container`

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /home/.../.../ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
```

##### CONFIGURATION

Default configuration without any changes.

##### OS / ENVIRONMENT

* ArchLinux

##### STEPS TO REPRODUCE

```yaml
---
- name: create test container
  hosts: localhost 
  gather_facts: false
  become: true
  tasks:

    - name: create a network
      docker_network:
        name: special

    - name: create a container with init set to true
      docker_container:
        name: 'test'
        state: started
        pull: true
        init: true
        image: 'traefik'
        restart_policy: always
        networks_cli_compatible: true
        networks:
          - name: special

    - name: restart test container after creation
      docker_container:
        name: 'test'
        state: started
        restart: true

...
```

##### EXPECTED RESULTS

The container should be restarted with the same settings and the diff should show the same as with `init: false`:
```
TASK [restart test container after creation] **************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "restarted": false,
+    "restarted": true,
     "running": true
 }
```

`docker inspect` still shows the custom network to be configured:
```
$ docker inspect test -f "{{ .NetworkSettings.Networks }}"                                                                      
map[special:0xc00056a000]
```

##### ACTUAL RESULTS
```paste below
TASK [restart test container after creation] **************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "init": true,
+    "init": false,
     "running": true
 }
```

`docker inspect` confirms that container has lost its custom network:
```
$ docker inspect test -f "{{ .NetworkSettings.Networks }}"                                                                      
map[bridge:0xc0001f0f00]
```
