### ISSUE TITLE
os_port_facts module cannot take fixed_ips.ip_address as filters

### ISSUE THREAD

**Issue by xding2020** [ansible/ansible#62364]
##### SUMMARY

I tried using ip_address as filters in os_port_facts module. But it doesn't work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_port_facts

##### ANSIBLE VERSION

```paste below
v2.8.5
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL

##### STEPS TO REPRODUCE

```yaml
I have following code in my Ansible playbook:
    - name: Get openstack port fact from IP
      os_port_facts:
        filters: 
          fixed_ips=ip_address=10.0.xxx.xxx # IP are masked
 Also I tried:
    - name: Get openstack port fact from IP
      os_port_facts:
        filters: 
          fixed_ips:
             ip_address=10.0.xxx.xxx # IP are masked
And:
    - name: Get openstack port fact from IP
      os_port_facts:
        filters: 
          fixed_ips:
             ip_address: 10.0.xxx.xxx # IP are masked
```

##### EXPECTED RESULTS

Matching port fact are returned

The IP is guaranteed to be correct. Also I called the openstack API to use the filter and it works. (i.e. https://openstack_url:port/v2.0/ports.json?fixed_ips=ip_address=10.0.xxx.xx)

##### ACTUAL RESULTS

```paste below
The first two codes above return empty result (no port matched). 
ok: [localhost] => {
    "ansible_facts": {
        "openstack_ports": []
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_timeout": null, 
            "auth": null, 
            "auth_type": null, 
            "availability_zone": null, 
            "ca_cert": null, 
            "client_cert": null, 
            "client_key": null, 
            "filters": {
                "fixed_ips": "ip_address=10.0.xxx.xx"
            }, 
            "interface": "public", 
            "port": null, 
            "region_name": null, 
            "timeout": 180, 
            "validate_certs": null, 
            "wait": true
        }
    }
}
The third code return error: 'ip_address' is not of the form <key>=[value].
```
