### ISSUE TITLE
azure_rm_subnet service_endpoints not added first time

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#62395]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_subnet

##### ANSIBLE VERSION

```paste below
2.8.4
```

##### STEPS TO REPRODUCE

```yaml
- name: create subnet
    azure_rm_subnet:
      tenant: '{{ tenant }}'
      client_id: '{{ client_id }}'
      secret: '{{ secret }}'
      subscription_id: '{{ subscription_id }}'
      resource_group: '{{ customer_prefix }}-test'
      virtual_network_name: '{{ customer_prefix }}-vnet'
      name: '{{ customer_prefix }}-test-subnet'
      address_prefix_cidr: 10.0.0.0/24'
      service_endpoints: 
        - service: Microsoft.Storage
```

##### EXPECTED RESULTS

Service endpoint should be added first time executing the module

##### ACTUAL RESULTS

Service endpoint is not added first time. Running the same module again adds the service endpoint correctly.
