### ISSUE TITLE
false positive from "raw module does not support the environment keyword" i

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#62402]
##### SUMMARY
It seems that `raw module does not support the environment keyword` warning is triggered even when environment is not defined in the raw task. 

Presence of environment at playbook triggers this error at raw task which makes not sense, as it could be totally impractical to duplicate the section to all tasks. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```paste below
2.8.5
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
   environment:
      FOO: bar
   tasks:
     # ... some tasks, eventually MANY
     - raw: df
     # ... some other tasks, some also needing environment
```
