### ISSUE TITLE
Ansible unable to connect to secured Docker daemon

### ISSUE THREAD

**Issue by Ag0s** [ansible/ansible#62415]
##### SUMMARY
When using a TLS secured remote docker daemon and trying to run tasks via Ansible all tasks fail with "Error while fetching server API" on client side and "http: TLS handshake error from 192.168.0.15:48348: tls: first record does not look like a TLS handshake"on server side.

Issuing the commands directly though the command line results in a succesfull network creation.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker TLS

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
```

##### OS / ENVIRONMENT
Local:
Ubuntu kernel: 4.15.0-62-generic
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Tue, 03 Sep 2019 19:59:35 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Remote:
Debian kernel: 4.19.37-5-amd64
Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Tue Sep  3 17:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false

##### STEPS TO REPRODUCE
```
- hosts: all
  gather_facts: no

  tasks:
    - name: Create dummy network
      docker_network:
        name: dummy-network
        state: present
        scope: global
      environment:
        DOCKER_HOST: "tcp://dockerhost.example.local:2376"
        DOCKER_TLS_VERIFY: "1"
        DOCKER_CERT_PATH: "{{ playbook_dir }}/certificates"

```

##### EXPECTED RESULTS
Network should be created and returned OK.

##### ACTUAL RESULTS
```
PLAY [all] **************************************************************************************************

TASK [Gathering Facts] **************************************************************************************
ok: [dockerhost.example.local]

TASK [Create dummy network] *********************************************************************************
fatal: [dockerhost.example.local]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: HTTPConnectionPool(host='dockerhost.example.local', port=2376): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcc79c1be10>: Failed to establish a new connection: [Errno 111] Connection refused',))"}

PLAY RECAP **************************************************************************************************
docker.example.local : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
And on server side:
```
2019-09-17 15:05:15.134548 I | http: TLS handshake error from 192.168.0.15:48502: tls: first record does not look like a TLS handshake
```
