### ISSUE TITLE
tower_job_template: Fails to set vault_credential

### ISSUE THREAD

**Issue by Moumoutaru** [ansible/ansible#62429]
##### SUMMARY
tower_job_template doesn't set vault credential on job templates

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tower_job_template

##### ANSIBLE VERSION
```
ansible 2.8.2
  config file = /home/amurphy/configuration-management/ansible.cfg
  configured module search path = [u'/home/amurphy/configuration-management/playbooks/library']
  ansible python module location = /srv/ansible/lib/python2.7/site-packages/ansible
  executable location = /srv/ansible/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

#### AWX VERSION
`6.1.0.0`

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/home/amurphy/configuration-management/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/amurphy/configuration-management/ansible.cfg) = -o ForwardAgent=yes
ANSIBLE_SSH_CONTROL_PATH(/home/amurphy/configuration-management/ansible.cfg) = %(directory)s/%%h-%%r
DEFAULT_ACTION_PLUGIN_PATH(/home/amurphy/configuration-management/ansible.cfg) = [u'/var/lib/awx/venv/ansible/lib/python2.7/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/amurphy/configuration-management/ansible.cfg) = [u'/home/amurphy/configuration-management/plugins/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/home/amurphy/configuration-management/ansible.cfg) = [u'rc', u'profile_tasks', u'es_annotations']
DEFAULT_LOG_PATH(/home/amurphy/configuration-management/ansible.cfg) = /home/amurphy/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/amurphy/configuration-management/ansible.cfg) = [u'/home/amurphy/configuration-management/plugins/lookup']
DEFAULT_MANAGED_STR(/home/amurphy/configuration-management/ansible.cfg) = !! Ansible managed: This file was created by ansible. Do not modify by hand! Changes will be overwritten. !!
DEFAULT_MODULE_PATH(/home/amurphy/configuration-management/ansible.cfg) = [u'/home/amurphy/configuration-management/playbooks/library']
DEFAULT_ROLES_PATH(/home/amurphy/configuration-management/ansible.cfg) = [u'/home/amurphy/configuration-management/playbooks/roles', u'/home/amurphy/roles']
DEFAULT_STRATEGY(/home/amurphy/configuration-management/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/amurphy/configuration-management/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ansible_mitogen/plugins/strategy', u'/srv/ansible/lib/python2.7/site-packages/ansible_mitogen/plugins/strategy', u'/srv
DEFAULT_VAULT_IDENTITY_LIST(env: ANSIBLE_VAULT_IDENTITY_LIST) = [u'/home/amurphy/.vault-pass']
INVENTORY_UNPARSED_IS_FAILED(/home/amurphy/configuration-management/ansible.cfg) = True
MAX_FILE_SIZE_FOR_DIFF(/home/amurphy/configuration-management/ansible.cfg) = 204800
RETRY_FILES_ENABLED(/home/amurphy/configuration-management/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

```yaml
---

- hosts: awx
  become: yes
  become_method: sudo

  tasks:
    - name: Setup hostgroup playbook template
      tower_job_template:
        tower_config_file: /root/tower_cli_config
        name: development - my_playbook.yml
        description: my_description
        playbook: playbooks/my_playbook.yml
        project: development
        vault_credential: ansible_vault_pass
        inventory: development
        job_type: "run"
        ask_credential: yes
        ask_diff_mode: yes
        ask_extra_vars: yes
        ask_inventory: yes
        ask_job_type: yes
        ask_limit: yes
        ask_tags: yes
        ask_skip_tags: yes
        ask_verbosity: yes
        become_enabled: yes
        fact_caching_enabled: yes
        state: present
...
```

##### EXPECTED RESULTS
job template is created based off of above information with vault_password defaulting to `ansible_vault_pass`.

##### ACTUAL RESULTS
job template is created but vault_password is not set.
