### ISSUE TITLE
Failed to become user SYSTEM: Exception Calling

### ISSUE THREAD

**Issue by Niolith** [ansible/ansible#62421]
##### SUMMARY
Hello, 

I'm currently trying to check update on Windows Server 2008 Std SP2. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates
    with the tags : check

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OS Target : Windows Server 2008 Standard SP2 (Version 6.0 Build 6003)

##### STEPS TO REPRODUCE

```yaml
- name: Check for missing updates
  win_updates:
    state: searched
    reboot: true
    reboot_timeout: 600
    log_path: c:\ansible_wu.txt
    category_names:
        - Application
        - Connectors
        - DefinitionUpdates
        - DeveloperKits
        - FeaturePacks
        - Guidance
        - ServicePacks
        - Tools
        - UpdateRollups
        - CriticalUpdates
        - SecurityUpdates
        - Updates
  register: update_result
  tags: check
- debug: msg="Found update count -  {{ update_result.found_update_count }}, Restart required -  {{ update_result.reboot_required }}"
  tags: check
```

##### EXPECTED RESULTS

On a working server :
```
{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "filtered_updates": {},
    "installed_update_count": 0,
    "changed": false,
    "reboot_required": false,
    "updates": {
        "437934f0-2915-4e74-b1cc-04921ce3aef1": {
            "kb": [
                "4512486"
            ],
            "installed": false,
            "id": "437934f0-2915-4e74-b1cc-04921ce3aef1",
            "title": "2019-08 Security Only Quality Update for Windows Server 2008 R2 for x64-based Systems (KB4512486)"
        },
        "82bf6959-36ff-4d3e-a909-b1cf9ffc9880": {
            "kb": [
                "4512506"
            ],
            "installed": false,
            "id": "82bf6959-36ff-4d3e-a909-b1cf9ffc9880",
            "title": "2019-08 Security Monthly Quality Rollup for Windows Server 2008 R2 for x64-based Systems (KB4512506)"
        },
        "8275ffa7-5730-4d56-abd2-504e6d07ab24": {
            "kb": [
                "3042058"
            ],
            "installed": false,
            "id": "8275ffa7-5730-4d56-abd2-504e6d07ab24",
            "title": "Security Update for Windows Server 2008 R2 x64 Edition (KB3042058)"
        }
    },
    "found_update_count": 3
}
```
##### ACTUAL RESULTS

On my server that we experiencing the issue

```paste below
{
    "_ansible_parsed": true,
    "exception": "Exception calling \"RunAsUser\" with \"7\" argument(s): \"Failed to start become \r\nprocess (Access is denied, Win32ErrorCode 5)\"\r\nAt line:955 char:9\r\n+         $result = [AnsibleBecome.BecomeUtil]::RunAsUser($username, \r\n$password, $l ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : Win32Exception\r\n \r\n",
    "_ansible_no_log": false,
    "msg": "Failed to become user SYSTEM: Exception calling \"RunAsUser\" with \"7\" argument(s): \"Failed to start become process (Access is denied, Win32ErrorCode 5)\"",
    "changed": false
}
```
