### ISSUE TITLE
Parted module is not idempotent

### ISSUE THREAD

**Issue by magick93** [ansible/ansible#62466]
##### SUMMARY
The parted module is not idempotent.

On first run of playbook the parted task succeed. On second run of the same playbook it fails with an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Parted

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /home/anton/git/ansible-deploy-vmware-vm/ansible.cfg
  configured module search path = [u'/home/anton/git/ansible-deploy-vmware-vm/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]


```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

- Target OS is Centos 7.
- Control machine is Ubuntu 18.04.

##### STEPS TO REPRODUCE
Run the following playbook twice

```yaml
---
- name: Fix Partition
  hosts: all
  gather_facts: no




  tasks:

    - parted: device=/dev/sda unit=s    
      register: sda_info

    - name: "debug sda_info"
      debug:  
        msg: "sda_info is {{ sda_info }}"
    
    
    - set_fact: partitionCount="{{ ((sda_info | to_json) | from_json).partitions | length}}"
    - set_fact: endOfLast="{{ ((sda_info | to_json) | from_json).partitions[(partitionCount | int)-1].end }}"
    
    - name: "get end of last partition"
      debug:  
        msg: "start of new is {{ (endOfLast | int)+1 }}"

    

    - parted:
        device: /dev/sda
        number: "{{(partitionCount | int)+1}}"
        flags: [ lvm ]
        state: present
        part_start: "{{ (endOfLast | int)+1 }}s"
        part_end: 100%
        unit: s
      become: true

```

##### EXPECTED RESULTS
Expect the same result everytime

##### ACTUAL RESULTS

```
fatal: [wallets-test-worker101.test.wallets]: FAILED! => {
    "changed": false, 
    "err": "Error: The location 2097152000s is outside of the device /dev/sda.\n", 
    "out": "", 
    "rc": 1
}

MSG:

Error while running parted script: /sbin/parted -s -m -a optimal /dev/sda -- unit s mkpart primary 2097152000s 100%


```
