### ISSUE TITLE
Warning after a failed zabbix_action task: "TypeError: 'ZabbixAPISubClass' object is not callable"

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#62485]
##### SUMMARY
Warning after a failed zabbix_action task: "TypeError: 'ZabbixAPISubClass' object is not callable"

` [WARNING]: Module invocation had junk after the JSON data: Error in atexit._run_exitfuncs: Traceback (most recent call last):   File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs     func(*targs, **kargs) TypeError: 'ZabbixAPISubClass' object is not callable Error in sys.exitfunc: Traceback (most recent call last):   File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs     func(*targs, **kargs) TypeError: 'ZabbixAPISubClass' object is not callable`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
```paste below
ansible 2.8.5
  config file = /opt/ansible/config/ansible-config.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv-ansible/lib/python2.7/site-packages/ansible
  executable location = /opt/venv-ansible/bin/ansible
  python version = 2.7.16 (default, May 20 2019, 06:24:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

Latest version of zabbix_action from github.

##### CONFIGURATION
```paste below
DEFAULT_FORKS(/opt/ansible/config/ansible-config.cfg) = 100
DEFAULT_HOST_LIST(/opt/ansible/config/ansible-config.cfg) = [u'/opt/ansible/inventory/cert/hosts']
HOST_KEY_CHECKING(/opt/ansible/config/ansible-config.cfg) = False
RETRY_FILES_ENABLED(/opt/ansible/config/ansible-config.cfg) = False
```

##### OS / ENVIRONMENT
RHEL6 master, RHEL7 target

##### STEPS TO REPRODUCE
Running a task that fails.

##### EXPECTED RESULTS
No warning/error.

##### ACTUAL RESULTS
Warning/error.

**Comment by richlv** [comment]
Actually does not seem to be related to failures - happens also when there are no failing tasks.
When there are failing and successful tasks, the message is printed after failures.

**Comment by ansibot** [comment]
cc @D3DeFi @K-DOT @eikef @rubentsirunyan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by D3DeFi** [comment]
Hey @richlv . Thanks for opening all the issues and sorry for my delayed response. I am now trying to find some time to dive into these zabbix_action problems.

Can you please provide any testing playbook that yields such warning for you? I've been unable to reproduce this problem with various combinations of python2/3, zabbix-api==0.5.4 and ansible devel/2.8.6

My env mostly consists of Ubuntu distros, but that shouldn't matter at all.

**Comment by richlv** [comment]
Heya, no worries and thank you for all the great help with modules :)

Currently testing with:
* Ansible master: Python 2.7.16, Ansible 2.8.5
* Ansible target host: Python 2.7.5, zabbix-api 0.5.3

Here's the simplest playbook I could get the error with:
```
- hosts: all
  gather_facts: no
  tasks:
    - name: Add Zabbix trigger actions
      module_defaults:
        zabbix_action:
          server_url: "http://localhost/zabbix/"
          login_user: username
          login_password: "password"
          state: present
          status: enabled
      zabbix_action:
        "{{item}}"
      loop: "{{actions_trigger_global}}"

  vars:
    default_command_action_status: "enabled"
    actions_trigger_global:
      - name: "auto resp: update motd"
        event_source: 'trigger'
        esc_period: '900'
        conditions:
          - type: 'host_group'
            operator: '='
            value: 'Linux servers'
        operations:
          - type: 'remote_command'
            command_type: 'custom_script'
            execute_on: 'server'
            command: command
            run_on_hosts:
              - 0
        status: "{{default_command_action_status}}"
```
