### ISSUE TITLE
azure_rm_virtualmachine winrm functionality

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#62489]
##### SUMMARY

winrm configruation during deployment does not support selfsigned certificate. This should be an option.

We are configuring winrm like so at the moment:
```
# Below is UTF-16 Base64 encoding for:
# https://encoder.mattiasgeniar.be/index.php
# New: Invoke-Expression -Command ((New-Object System.Net.WebClient).DownloadString('https://github.com/ansible/ansible/blob/devel/examples/scripts/ConfigureRemotingForAnsible.ps1')); Enable-WSManCredSSP -Role Server -Force
# Old: Invoke-Expression -Command ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1')); Enable-WSManCredSSP -Role Server -Force
# A UTF-16 Base64 encoded script is used so we don't have to escape any characters that may cause issues
- name: encode winrm script utf-16 base64
  set_fact:
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=

- name: configure virtual machine extension
  azure_rm_virtualmachineextension:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    name: winrm-extension
    resource_group: '{{ resource_group }}'
    virtual_machine_name: '{{ virtual_machine_name }}'
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: '1.9'
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
    auto_upgrade_minor_version: true

- name: wait for the winrm port to come online
  wait_for:
    port: 5986
    host: '{{ item.properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}'
    timeout: 600
  loop_control:
    label: "Online."
  loop: '{{ azure_vm.properties.networkProfile.networkInterfaces }}'
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine 

##### ADDITIONAL INFORMATION

```yaml
- name: deploy virtual machine
  azure_rm_virtualmachine:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    resource_group: '{{ customer_prefix }}-test'
    name: "{{ customer_prefix }}-test-vm"
    vm_size: "{{ vm_size }}"
    os_type: Windows
    managed_disk_type: StandardSSD_LRS
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    network_interface_names: '{{ customer_prefix }}-test-vm01'
    virtual_network_resource_group: "{{ customer_prefix }}-test"
    virtual_network_name: "{{ customer_prefix }}-vnet"
    subnet_name: "{{ customer_prefix }}-test-subnet"
    tags:
      type: test
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2012-R2-Datacenter
      version: latest
    winrm:  
      - protocol: https
```

Output:
```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine my-test-vm - Azure Error: InvalidParameter\nMessage: For WinRM Https listeners, a certificate must be specified.\nTarget: windowsConfiguration.winRM.listeners.certificateUrl"}
```
