### ISSUE TITLE
Replace module add newline for no reason when working with multiples lines replacement

### ISSUE THREAD

**Issue by Theoooooo** [ansible/ansible#62490]
##### SUMMARY
I discover a bug (i think it is) where, if you work with multiples lines in the replace value, it automaticaly add a new line at the end of the content replaced even if you don't want to.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
replace

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### OS / ENVIRONMENT
CentOS 7 1807

##### STEPS TO REPRODUCE

1. Create a simple task "replace" with the following format (i do not include the hosts files or anything like that.) :
```
- name: "Remplacement de la valeur disabled dans le bloc syscollector dans le fichier /var/ossec/etc/ossec.conf"
      replace:
        dest: /var/ossec/etc/ossec.conf
        regexp: '{{ item.from }}'
        replace: '{{ item.to }}'
      with_items:
        - { from: '<wodle name="syscollector">\n\s+<disabled>no</disabled>', to: '{{ v_logsvip.wazuh.syscollector.config }}' }
```
I have to do a regex based on the previous xml marker because "disabled" is present in many places on the file i'm working on.
I'm also using items because i replace multiples lines with this task.

2. Create a variable with the 2 lines that will replace the content match with the regex:
```
v_lovsgip:
  wazuh:
    syscollector:
      config: |
        <wodle name="syscollector">
            <disabled>yes</disabled>
```

3. Play this task in your playbook and look at the content being output by ansible:
```
changed: [172.40.0.56] => (item={u'to': u'<wodle name="syscollector">\n    <disabled>yes</disabled>\n', u'from': u'<wodle name="syscollector">\\n\\s+<disabled>no</disabled>'}) => {"ansible_loop_var": "item", "changed": true, "item": {"from": "<wodle name=\"syscollector\">\\n\\s+<disabled>no</disabled>", "to": "<wodle name=\"syscollector\">\n    <disabled>yes</disabled>**\n**"}, "msg": "1 replacements made"}
```
(Look at the end of the result. Ansible added a new line for no reason)

##### ACTUAL RESULTS

As you can see, ansible add a newline at the end of the content, and i'm getting this result in my file :

```
  <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>yes</disabled>

    <interval>1h</interval>
```

##### EXPECTED RESULTS
I don't want this new line in my config file. There is the result i'm expecting :
```
  <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>yes</disabled>
    <interval>1h</interval>
```
I've got a similar output in an another block that i'm replacing, but the new line added at the end is needed.
