### ISSUE TITLE
azure_rm_storageaccount module doesn't support BlockBlobStorage storage in Azure

### ISSUE THREAD

**Issue by wschoot** [ansible/ansible#62499]
##### SUMMARY
azure_rm_storageaccount module doesn't support BlockBlobStorage storage in Azure. In 'Premium_LRS', there's a kind BlockBlobStorage, which azure_rm_storageaccount doesn't yet support. See also https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview for all kinds

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_storageaccount

##### ANSIBLE VERSION
```paste below
ansible 2.8.5
  config file = /home/wouter.schoot/git/ansible/ansible.cfg
  configured module search path = [u'/home/wouter.schoot/git/ansible/library', u'/home/wouter.schoot/git/ansible/common/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

Create a storage account in Azure using
```yaml
- name: setup blobstorage                     
  azure_rm_storageaccount:                    
    resource_group: devcluster
    name: test
    type: Premium_LRS                         
    kind: BlockBlobStorage                    
    access_tier: Hot                          

```

##### EXPECTED RESULTS

Storage account creation succeeds and the 'Account kind' in Azure Portal account overview shows BlockBlobStorage

##### ACTUAL RESULTS
```
  msg: 'value of kind must be one of: Storage, StorageV2, BlobStorage, got: BlockBlobStorage'
```
