### ISSUE TITLE
User module: OpenBSD: entry not added to /etc/group, making su fail

### ISSUE THREAD

**Issue by kayront** [ansible/ansible#62576]
##### SUMMARY

Just noticed that on OpenBSD, a user created by ansible with `group: wheel` is unable to su - to root.

For example:

```
$ su -
Password:
you are not in group wheel
Sorry
```

But, strangely enough, it seems that this is not the case:

```
$ id
uid=1000(admin) gid=0(wheel) groups=0(wheel), 5(operator)
```
However, upon further research, I came across the following in the `su` manpage (OpenBSD version):

```
     It is not sufficient to change a user's /etc/passwd entry
     to add them to the "wheel" group; they must explicitly be listed in
     /etc/group.
```

And indeed we find that:

```
$ head -n1 /etc/group                                                                                                                                                                                                                   
wheel:*:0:root
```

Substituting the above for `wheel:*:0:root,admin` makes su work as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

user module

##### ANSIBLE VERSION

`ansible 2.8.4`

##### CONFIGURATION

##### OS / ENVIRONMENT

OpenBSD 6.5

##### STEPS TO REPRODUCE


```yaml
- name: "create admin account"                                                                                                                                                                                           
  user:                                                                                                                                                                                                                                       
    name: admin                                                                                                                                                                                                                               
    group: wheel
    groups: operator
```

##### EXPECTED RESULTS

Able to su - because user is in the `wheel` group.

##### ACTUAL RESULTS

```
$ su -
Password:
you are not in group wheel
Sorry
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Is specifying `groups: wheel` on the task sufficient?

**Comment by samdoran** [comment]
I have verified this behavior and it is not a bug in Ansible but rather an issue with the underlying tools, `usermod` and `useradd` in this case.

Adding `wheel` to the `groups` parameter does create the entry in `/etc/group`, but only when creating the account initially. The underlying command that is run is `/usr/sbin/useradd -g wheel -G operator,wheel -m admin`. Doing this will fix your issue for newly created accounts.

```yaml
- user:
    name: admin
    group: wheel
    groups:
      - operator
      - wheel
```


When trying to modify an existing account, the `usermod -S` and `-G` flags do not modify `/etc/group` when the user's primary group is specified. For instance, if a user's primary group is `wheel`, running `usermod -G wheel user` will not create an entry in `/etc/group`.

This has the unfortunate side effect of the task always reporting a change but the proper change is not made to the system. This seems like a bug in `usermod` in BSD, but the module is doing the right thing.

You can duplicate this behavior by running the following commands (which is what Ansible is doing):
```
/usr/sbin/useradd -g wheel -G operator -m admin
/usr/sbin/usermod -S operator,wheel admin
```

The `usermod` command works as expected on Linux, which makes me think this is a bug in `usermod` on OpenBSD (though I did not try other BSD distributions).

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
