### ISSUE TITLE
aws_ec2 inventory plugin: only one instance is registered for hostnames defined by tag values.

### ISSUE THREAD

**Issue by tinproject** [ansible/ansible#62583]
##### SUMMARY
When using `aws_ec2` inventory plugin with hostname based on tags values, if the tag value is shared among various instances only one of this instances is registered on the inventory.

Related: https://github.com/ansible/ansible/issues/55911

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ec2 inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /opt/app/src/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Aug 14 2019, 12:09:51) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

- Have two or more AWS Ec2 instances with the same `Name` tag, `web` for example.
- Configure dynamic inventory:
```yaml
# inventory.aws_ec2.yaml
---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: "running"

# Add ansible variables based on host inventory data
compose:
  ansible_host: public_ip_address if public_ip_address is defined else private_ip_address

hostnames:
  - tag:Name  # Uses the Name tag, if not present uses the dns-name
  - dns-name

strict: False
```

- run `ansible-inventory --graph -y`

##### EXPECTED RESULTS

Expected that all the matching instances are registered on the inventory.

##### ACTUAL RESULTS

Only one matching instance is added to the inventory

```paste below
$ ansible-inventory -i inventories/test/all.aws_ec2.yml --graph -y
@all:
  |--@aws_ec2:
  |  |--web
  |--@ungrouped:
```
