### ISSUE TITLE
win_service does not support virtual account

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#62601]
##### SUMMARY
Installing a service with the [virtual account](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts#virtual-accounts) configured for execution of the service does not work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_service

##### ANSIBLE VERSION
```paste below
ansible 2.8.5
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
ArchLinux

##### STEPS TO REPRODUCE

```yaml
- name: Create the windows service for auditbeat
  win_service:
    state: started
    display_name: Foobar
    name: foobar
    path: "C:\Windows\System32\calc.exe"
    username: NT SERVICES\foobar$
    password: ''
```

##### EXPECTED RESULTS

Service being created successfully.

##### ACTUAL RESULTS
```paste below
fatal: [naboo]: FAILED! => {
    "changed": false,
    "msg": "account_name NT SERVICES\\foobar$ is not a valid account, cannot get SID: Ausnahme beim Aufrufen von \"Translate\" mit 1 Argument(en):  \"Manche oder alle Identitätsverweise konnten nicht übersetzt werden.\""
}
```
