### ISSUE TITLE
Ansible - pip not found

### ISSUE THREAD

**Issue by jameskeithp** [ansible/ansible#62604]
##### SUMMARY

I am trying to install virtualenv tool to create isolated Python environments, but it is unable to find the pip executable through Ansible. I have run pip install virtuaenvmanually on SLES 15-SP1 and it works successfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

pip

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jamekeit/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/id_rsa
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

OS running from Red Hat Enterprise Linux Server 7.5
OS managing: SLES 15-SP1

driver: vmxnet3
version: 1.4.7.0-k-NAPI
firmware-version:
expansion-rom-version:
bus-info: 0000:0b:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no

Firmware Revision: 0.0

bios-version: 6.00

##### STEPS TO REPRODUCE

```yaml
- name: install pip
  easy_install:
    name: pip
    state: latest
- name: install additional pip modules
  pip:
    name: virtualenv
    executable: pip-3.6
  environment:
    http_proxy: "http://proxy.houston.hpecorp.net:8080"
    https_proxy: "http://proxy.houston.hpecorp.net:8080"

```

##### EXPECTED RESULTS

Successful installation of virtualenv

##### ACTUAL RESULTS

ansible-playbook -i buildservers-agd new-buildserver.yaml --limit abls15ex6406

fatal: [abls15ex6406]: FAILED! => {"changed": false, "msg": "Unable to find any of pip-3.6 to use.  pip needs to be installed."}

```paste below

```
