### ISSUE TITLE
win_get_url fails with empty string proxy parameters

### ISSUE THREAD

**Issue by jghal** [ansible/ansible#62613]
##### SUMMARY
We have to support public and private environments where we may or may not have a proxy, so we configure tasks with proxy conditional on a `use_proxy` variable in our roles. After upgrading to 2.8 the `win_get_url` module fails if the proxy username and password paramters have an empty string value. Same code worked in 2.7

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_get_url

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  8 2019, 18:17:52) [GCC 8.3.0]
```

##### CONFIGURATION

```
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/ansible-$USER/ansible-local-1013gsipsbln
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = false
```

##### OS / ENVIRONMENT
Docker container based on `runatlantis/atlantis:v0.8.2`.

##### STEPS TO REPRODUCE

```yaml
- debug:
    msg:
      - "proxy: {{ proxy }}"
      - "proxy_password: {{ proxy_password is defined | ternary('<masked>', '<undefined>') }}"
      - "proxy_username: {{ proxy_username is defined | ternary(proxy_username, '<undefined>') }}"

- name: Push a file (Windows)
  win_get_url:
    url: https://github.com/ansible/ansible/archive/v2.8.5.tar.gz
    dest: C:\\Windows\\Temp\\
    use_proxy: "{{ use_proxy }}"
    proxy_url: "{{ proxy | default('') }}"
    proxy_password: "{{ proxy_password | default('') }}"
    proxy_username: "{{ proxy_username | default('') }}"
  when: ansible_os_family == "Windows"
```

The `use_proxy` variable is defaulted to `no` in our `defaults/main.yml` and the rest have to be supplied if needed. After upgrading to 2.8 we have to instead supply a valid URL (ie the module is parsing out scheme, host, port and fails if not valid) and use `default('undefined')` for the credentials parameters.

##### EXPECTED RESULTS

```
    TASK [build : Push a file (Windows)] *******************************************
    skipping: [ci-agent-co7]
    changed: [ci-agent-w16]
```

##### ACTUAL RESULTS
```
    TASK [build : Push a file (Windows)] *******************************************
    skipping: [ci-agent-co7]
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 39
    fatal: [ci-agent-w16]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Exception calling \"Create\" with \"2\" argument(s): \"String cannot be of zero length.\r\nParameter name: oldValue\""}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_get_url.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @nitzmahone @tksarah
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
This isn't actually a problem with with `win_get_url` but actually an issue with the `Ansible.Basic` C# util we use in some PowerShell modules right now. Setting an empty string to any module option that has `no_log=True` set will produce this error. I've got a WIP PR in plcae but I may not have it ready until next week.

On a side not, I've had a look at the code for `win_get_url` and it should still see an empty string as a value not being set but this is not something I recommend you rely on.

What you should be using instead of an empty string is the [omit](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#omitting-parameters) value to specify module options that should not be set dynamically.

In your case your task will now look like

```
- name: Push a file (Windows)
  win_get_url:
    url: https://github.com/ansible/ansible/archive/v2.8.5.tar.gz
    dest: C:\Windows\Temp
    use_proxy: "{{ use_proxy }}"
    proxy_url: "{{ proxy | default(omit) }}"
    proxy_password: "{{ proxy_password | default(omit) }}"
    proxy_username: "{{ proxy_username | default(omit) }}"
  when: ansible_os_family == "Windows"
```

This will work on older Ansible versions as `omit` has been in place since Ansible 1.8. It works for any module options, including values inside a dict but it cannot be used outside of a module, say vars set on `include_roles` or as a way to skip a value.

I'll keep this issue open until the PR that fixes the Ansible.Basic no log values has been merged.
