### ISSUE TITLE
azure_rm_virtualmachinescalesetinstance_info is very slow for VMSS with large number (100s) of instances

### ISSUE THREAD

**Issue by arvindshmicrosoft** [ansible/ansible#62639]
##### SUMMARY

The performance of azure_rm_virtualmachinescalesetinstance_facts is very poor for VMSS with large number (100+) of instances

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachinescalesetinstance_info

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/arviadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/arviadmin/env/lib/python3.6/site-packages/ansible
  executable location = /home/arviadmin/.local/bin/ansible
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

##### STEPS TO REPRODUCE

1. Create an Azure Virtual Machine Scale set with 500 instances
2. Run the playbook below to get information for the VMSS instances

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - azure_rm_virtualmachinescalesetinstance_facts:
     resource_group: "some_rg"
     vmss_name: "somevmss"
    register: vmss_facts
  - debug:
     var: vmss_facts
```

##### EXPECTED RESULTS

Azure CLI takes ~ 20 seconds to list equivalent information.

##### ACTUAL RESULTS

Ansible module takes ~ 3 minutes to return

```paste below

```
