### ISSUE TITLE
IOS VRF option to chose ipv4, ipv6 or both

### ISSUE THREAD

**Issue by EarlRamirez** [ansible/ansible#62631]
##### ISSUE TYPE
- Feature Idea
When using ios_vrf module, both ipv4 and ipv6 address-family are created. It would nice to have the option to use either address-family or both similar to the import/export option.
##### COMPONENT NAME

ios_vrf
##### ADDITIONAL INFORMATION

This brings consistency when created VRF, currently when a VRF is created both families are used; however, if one is specifying ipv4 there is no need to have both in the VRF. The module can be enhanced by adding family or something similar where the three options are available ipv4, ipv6 or both.

```yaml
---
- hosts: node1
  connection: local
  gather_facts: no

  tasks:
  - name: Create VRF with import and export address family
    ios_vrf:
      family: ipv4
      name: test
      rd: 1:100
      route_both_ipv4:
        - 1:100
        - 1:100
```
