### ISSUE TITLE
Lookups in dynamic inventory composed variables

### ISSUE THREAD

**Issue by brian-maloney** [ansible/ansible#62660]
##### SUMMARY
Enable lookups in dynamic inventory script composed variables.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`lib/ansible/cli/inventory.py`

##### ADDITIONAL INFORMATION

I would like to vary my composed variable output based on an environment variable.  My specific use case is that I'd like to override ansible_host to use internal IP addresses when running from AWX inside my GCP environment, but otherwise use the the hostname to connect.

This works if I set `disable_lookups=False` in `_compose` in [ansible/plugins/inventory/\_\_init\_\_.py](https://github.com/ansible/ansible/blob/eb1995d41d8cb5967b86efa57faad91c4fdb6f5c/lib/ansible/plugins/inventory/__init__.py#L353)

I'm not sure if lookup processing in inventory is disabled for security or performance reasons, obviously if there's a security risk to enabling them I will retract this request.

Example GCP inventory script:

```yaml
plugin: gcp_compute
zones:
  - northamerica-northeast1-a
projects:
  - myproject
groups:
  gcp_hosts: true
hostnames:
  - name
scopes:
  - https://www.googleapis.com/auth/compute
compose:
  ansible_host: "lookup('env', 'AWX_RUN') | ternary(networkInterfaces[0].networkIP, omit)"
```

Thanks!

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by stawii** [comment]
I would love to see this in all parameters. Ie. I would love to set:
```yaml
filters:
  tag:Env: dev
  tag:Owner: "{{ lookup('env', 'USER') }}"
```

Second use case is to set different credentials based on different envs when using same plugin more than once so there is no need to hardcode them. Imagine two inventory files:
```yaml
plugin: aws_ec2
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_FOO') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_FOO') }}"
```
```yaml
plugin: aws_ec2
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_BAR') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_BAR') }}"
```
I believe there is no workaround for this (?).

**Comment by bcoca** [comment]
There are several reasons lookups are disabled in inventory plugins, mainly that at that point of execution we lack full context (it is the job of the inventory plugin to provide part of it for the play) that lookups equire, while some will work, others won't and instead of adding a seeming 'lottery' over which will work and won't we disabled them at this point. 

I started #70970 as an alternative by providing extra vars as a source both for composition and plugin configuration.

@stawii inventory plugins can already use environment variables directly, they just need to be specified by the plugin author as part of the the docs/configuration.

**Comment by stawii** [comment]
> inventory plugins can already use environment variables directly

Can you please elaborate more? I believe there is a technical possibility, but never seen this in any plugin, but I might be looking in wrong places. I'm taking about official inventory plugins `aws_ec2` and `azure_rm` in Ansible 2.9.x.
Or maybe you get me wrong. My goal is to have two inventory plugins, with different credentials taken from different envs.
For example ec2 plugin can read `AWS_ACCESS_KEY` env for `aws_access_key` parameter, but the name of env is not customizable. If set it, it would go to all ec2 plugins, but I need it different for each inventory file. I know I can bypass this by setting `aws_profile` but this is only exception for AWS and bit harder to setup.
Current workaround is to use contrib inventory scripts and wrap it in overlay which rewrites envs ie.
```
#!/bin/sh
export AWS_ACCESS_KEY_ID="$PROD_AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$PROD_AWS_SECRET_ACCESS_KEY"
exec contrib/inventory/ec2.py "$@"
```
But contrib inventory scripts sometimes lacks for features and are deprecated (?) in Ansible 2.10.

**Comment by ansibot** [comment]
@brian-maloney: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/cli/inventory.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/inventory.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by b-reich** [comment]
Something like would be great
```yml
plugin: community.general.proxmox
url: "https://nuc1:8006"
user: "ansible@pam"
password: "{{ lookup('bitwarden', 'xxxxx') }}"
validate_certs: no
```
(bitwarden is a third party lockup plugin)

Is there a workaround for that?
