### ISSUE TITLE
Handler loses ansible_local variable when using local facts

### ISSUE THREAD

**Issue by rlko** [ansible/ansible#62665]
##### SUMMARY
I saw since ansible 2.8.0, if you use local facts (facts.d) variables in a handler task. You will lose the ansible_local variable resulting in a `ERROR! 'ansible_local' is undefined` in the task you add a `notify:`.

Otherwise you don't have this issue in an ansible version <2.8

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
local facts
handlers

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]
```
##### OS / ENVIRONMENT

Ubuntu 18.04 

##### STEPS TO REPRODUCE

```bash
cat /etc/ansible/facts.d/some_vars.fact 
```
```json
{
        "appdir": "/tmp/ansible",
        "branch": "devel",
        "user": "root"
}
```

```bash
cat some_playbook.yml 
```
```yaml
- hosts: localhost

  vars:
    some_vars: "{{ ansible_local.some_vars }}"

    git_dir: "{{ some_vars.appdir }}"
    branch: "{{ some_vars.branch }}"
    user: "{{ some_vars.user }}"


  tasks:
  - name: "Ensure {{ git_dir }} exists"
    file:
      path: "{{ git_dir }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: "Clone project in {{ git_dir }}"
    git:
      repo: 'https://github.com/ansible/ansible.git'
      dest: "{{ git_dir }}"
      version: "{{ branch }}"
      recursive: yes
      force: yes
    become: yes
    become_user: "{{ user }}"
    notify: git clone


  handlers:
  - name: "Ansible {{ branch }} cloned"
    debug:
      msg: "{{ branch }}"
    listen: git clone
```

```bash
ansible-playbook -vv some_playbook.yml 
```

##### EXPECTED RESULTS

```bash
ansible-playbook 2.7.13
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet yaml requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet ini requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet auto requirements, check plugin documentation if this is unexpected
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'


PLAYBOOK: some_playbook.yml ********************************************************************************
1 plays in some_playbook.yml

PLAY [localhost] *******************************************************************************************

TASK [Gathering Facts] *************************************************************************************
task path: /root/some_playbook.yml:1
ok: [localhost]
META: ran handlers

TASK [Ensure /tmp/ansible exists] **************************************************************************
task path: /root/some_playbook.yml:12
changed: [localhost] => {"changed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/tmp/ansible", "size": 2, "state": "directory", "uid": 0}

TASK [Clone project in /tmp/ansible] ***********************************************************************
task path: /root/some_playbook.yml:19
NOTIFIED HANDLER Ansible {{ branch }} cloned for localhost
changed: [localhost] => {"after": "7cfcf18a8cfbe74309c3bc64c825e5208d99ff55", "before": null, "changed": true}

RUNNING HANDLER [Ansible {{ branch }} cloned] **************************************************************
task path: /root/some_playbook.yml:32
ok: [localhost] => {
    "msg": "devel"
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

```bash
ansible-playbook 2.8.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]
No config file found; using defaults
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'


PLAYBOOK: some_playbook.yml ********************************************************************************
1 plays in some_playbook.yml

PLAY [localhost] *******************************************************************************************

TASK [Gathering Facts] *************************************************************************************
task path: /root/some_playbook.yml:1
ok: [localhost]
META: ran handlers

TASK [Ensure /tmp/ansible exists] **************************************************************************
task path: /root/some_playbook.yml:12
changed: [localhost] => {"changed": true, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/tmp/ansible", "size": 2, "state": "directory", "uid": 0}

TASK [Clone project in /tmp/ansible] ***********************************************************************
task path: /root/some_playbook.yml:19
ERROR! 'ansible_local' is undefined
```
