### ISSUE TITLE
ec2_vpc_net: Modifying dns_hostnames or dns_support in check mode results in failure

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#62677]
##### SUMMARY

If you try to modify dns_hostnames or dns_support in check mode if fails with
```
    "msg": "Failed to wait for enableDnsSupport to be updated",
```

Found as part of additional tests in #62649 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/cloud/amazon/ec2_vpc_net.py

##### ANSIBLE VERSION

```
ansible 2.10.0.dev0
```

##### CONFIGURATION
N/A (ansible-test docker-container)

##### OS / ENVIRONMENT
N/A (ansible-test docker-container)

##### STEPS TO REPRODUCE

```
    - name: create a VPC 
      ec2_vpc_net:
        cidr_block: "{{ vpc_cidr }}"
        ipv6_cidr: True
        name: "{{ resource_prefix }}"
        state: present
      register: result

    - name: disable dns_hostnames (check mode)
      ec2_vpc_net:
        cidr_block: "{{ vpc_cidr }}"
        name: "{{ resource_prefix }}"
        dns_hostnames: False
        state: present
      register: result
      check_mode: True
```

##### EXPECTED RESULTS

Returns "changed" but with no changes made

##### ACTUAL RESULTS

```
TASK [ec2_vpc_net : disable dns_hostnames (check mode)] ************************
task path: /root/.ansible/test/tmp/ec2_vpc_net-rf7mid4k-ÅÑŚÌβŁÈ/test/integration/targets/ec2_vpc_net/tasks/main.yml:463
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<testhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306 `" && echo ansible-tmp-1569004305.4383004-120352358010306="` echo /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306 `" ) && sleep 0'
Using module file /root/ansible/lib/ansible/modules/cloud/amazon/ec2_vpc_net.py
<testhost> PUT /root/.ansible/tmp/ansible-local-12864no2jv9/tmpc98f70nc TO /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306/AnsiballZ_ec2_vpc_net.py
<testhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306/ /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306/AnsiballZ_ec2_vpc_net.py && sleep 0'
<testhost> EXEC /bin/sh -c 'ANSIBLE_DEBUG_BOTOCORE_LOGS=True /tmp/python-_nwibfvt-ansible/python /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306/AnsiballZ_ec2_vpc_net.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1569004305.4383004-120352358010306/ > /dev/null 2>&1 && sleep 0'
fatal: [testhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": "REDACTED",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cidr_block": [
                "10.79.0.0/24"
            ],
            "debug_botocore_endpoint_logs": true,
            "dhcp_opts_id": null,
            "dns_hostnames": false,
            "dns_support": true,
            "ec2_url": null,
            "ipv6_cidr": false,
            "multi_ok": false,
            "name": "ansible-test-mchappel-27933545",
            "profile": null,
            "purge_cidrs": false,
            "region": "us-west-2",
            "security_token": null,
            "state": "present",
            "tags": null,
            "tenancy": "default",
            "validate_certs": true
        }
    },
    "msg": "Failed to wait for enableDnsHostnames to be updated",
    "resource_actions": [
        "ec2:DescribeVpcs",
        "ec2:DescribeTags",
        "ec2:DescribeVpcClassicLink",
        "ec2:DescribeVpcAttribute"
    ]
}
```
