### ISSUE TITLE
azure_rm_appgateway backend_address_pools doesn't support multiple targets or changes to existing targets

### ISSUE THREAD

**Issue by dvntstph** [ansible/ansible#62715]
##### SUMMARY

Azure Application Gateways support multiple backend pools with multiple targets in the pool.
When trying to manage application gateways using Ansible, adding a second target to an existing pool is ignored, resulting in no changes. 
Also trying to add an additional backend pool with a different name is completely ignored resulting in no change or results in syntax error, depending on how it's written.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_appgateway
##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = None
  configured module search path = [u'/home/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
no changes - using Azure bash shell
```

##### OS / ENVIRONMENT

Azure Portal bash shell

##### STEPS TO REPRODUCE

Built an Application Gateway using one backend pool containing one target. Added a second target (10.128.8.6) to the code and reran playbook which results in OK, changed=0

Tested on local install of Ansible on Ubuntu and tested using Azure cloud bash Shell. 
Outcome is the same

Attempting to add second pool results in formating context error - see inline comments in example playbook

```yaml
---
- name: Manage Test Application Gateway
  hosts: localhost
  tasks :

  - name: Manage public ip address for App gateway
    azure_rm_publicipaddress:
     resource_group: USC-devzero-RG
     name: USC-devzero-APPGW01-IP
     allocation_method: dynamic
     #domain_name: test.devzero.co.za
     state: present

  - name: Manage Application Gateway
    azure_rm_appgateway:
      resource_group: USC-devzero-RG
      name: USC-devzero-APPGW01
      state: present
      sku:
        name: waf_medium
        tier: waf
        capacity: 2
      gateway_ip_configurations:
      - subnet:
          id: "/subscriptions/f56ddc6a-a983-4377-a2fa-354d079fbe49/resourceGroups/USC-devzero-RG/providers/Microsoft.Network/virtualNetworks/USC-devzero-RG-vnet/subnets/USC-devzero-subnet1"
        name: app_gateway_ip_config
      frontend_ip_configurations:
      - public_ip_address: USC-devzero-APPGW01-IP
        name: appGatewayFrontendIP
      frontend_ports:
      - port: 80
        name: FrontEndPort80
      - port: 443
        name: appGatewayFrontendPort
      backend_address_pools:
      - backend_addresses:
          - ip_address: 10.128.8.5
          - ip_address: 10.128.8.6
        name: USC-mytest-pool
    #####The following example - if uncommented is ignored
    ###   - ip_address: 10.128.9.6
    ### name: USC-myothertest-pool
    ####
    #####The following example - if uncommented results in syntax error
    #- backend_addresses:
    #     - ip_address: 10.128.8.5
    #     - ip_address: 10.128.8.6
    #   name: USC-mytest-pool
    ####
      backend_http_settings_collection:
      - port: 80
        protocol: http
        cookie_based_affinity: disabled
        name: appGatewayBackendHttpSettings
      http_listeners:
      - frontend_ip_configuration: appGatewayFrontendIP
        frontend_port: FrontEndPort80
        host_name: test.devzero.co.za
        name: test.devzero.co.za-HTTP
        protocol: http
      request_routing_rules:
      - rule_type: Basic
        backend_address_pool: USC-mytest-pool
        backend_http_settings: appGatewayBackendHttpSettings
        http_listener: test.devzero.co.za-HTTP
        name: test.devzero.co.za

```

##### EXPECTED RESULTS

Expected backend pool to be modified and a second target to be added.

##### ACTUAL RESULTS

Changes are ignored an play run returns OK nothing changed

```paste below
sean@Azure:~/clouddrive/hacking-work-in-progress/azure$ ansible-playbook azure_rm_appgateway.yml
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [Manage Test Application Gateway] ******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Manage public ip address for App gateway] *********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Manage Application Gateway] ***********************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
