### ISSUE TITLE
Enable implementation of ipsla monitors in new nx-os module

### ISSUE THREAD

**Issue by skylerbunny** [ansible/ansible#62714]
##### SUMMARY
Suggest implemention of ip sla objects as a new module. Several series of Nexus switches, (I believe with the notable exception of the 5000 series), have the ability to have configured IP Service Level Agreements (SLAs) (ip sla) objects. See https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/ip_sla/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_IP_SLAs_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_IP_SLAs_Configuration_Guide_7x_chapter_01010.html#concept_D1FF727F3AEF4475AAA3D75ABD51825A

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_ip_sla
nxos_ip_sla_schedule

##### ADDITIONAL INFORMATION
These objects have value in being able to periodically check that a given destination host or network is up, and provide additional diagnostic data when probed. They can also be used in situations like pinging a host on the far end of an IPSEC site-to-site tunnel, to keep the tunnel up (a scenario that is desired and in fact directly encouraged on AWS site-to-site tunnels and for other cloud providers).

There is NX-API REST support for these objects in many of the Nexus switch series: see https://developer.cisco.com/site/cisco-nexus-nx-api-references/ .

I realize there are a lot of different configuration possibilities, but this link gives a possible first guess as to what this might look like: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/sw/6_x/nx-os/IPSLA/configuration/guide/b_Cisco_Nexus_7000_Series_NX-OS_IP_SLAs_Configuration_Guide_rel_6-x/configuring_ip_slas_icmp_echo_operations.html#task_D1E146DB1B644827A9D93FE6DCEADDB6

```yaml
- name: Implement an ip sla tunnel
  nxos_ip_sla:
    operation_number: 6
    type: icmp-echo|udp ...
    source_ip: 192.168.1.1
    destination: foo.com|192.168.2.1
    source_interface: vlan20
    frequency: 30
    timeout: 10000

- name: Schedule operation 6 as a separate operation
  ip_sla_schedule:
    operation_number: 6
    lifetime: forever|3600
    start_time: now|after ...
```

If Ansible only wants to support individual operations associated with individual schedules, this could all be done in one single module, where the schedules for them are part of the ip_sla module itself and the schedule operation numbers would be assigned in the same block as the operation number of the sla itself. If a more robus implementation with the ability to assign them to groups is wanted, then it probably wants its own module, where the 'schedule' module can pull an operation in and out of groups, or add or delete one individual to the operation itself.
