### ISSUE TITLE
AWS Lambda layers support

### ISSUE THREAD

**Issue by thomaszooman** [ansible/ansible#62724]
##### SUMMARY

AWS Lambda now supports layers, it can reduce the code size and time spend dramatically. To support Lambda layers, it should be a new module to manage Lambda layers, update ```lambda``` module to support Lambda layers.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

```lambda```

##### ADDITIONAL INFORMATION

example of the new module 
```yaml
lambda_layers: 
    # aws_parameters
    name: layer_name
    zip_file: file_path
    # or
    s3_bucket: buclet_name
    s3_key: key_name
    runtimes:
    - 	nodejs10.x
    - 	nodejs8.10
```

```lambda``` module
```yaml
    lambda:
        layers:
        -    layer1_arn
        -    layer2_arn
        # other_paremeters
```
