### ISSUE TITLE
set_fact in a block not taken into account in the task

### ISSUE THREAD

**Issue by Poil** [ansible/ansible#62739]
##### SUMMARY
Hi,

I use ansible-prometheus role from Galaxy, when I configure it with "latest", "prometheus_version" fact is set to "2.12.0", but in the next task the value is still the original value "latest"

cf.
* https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/preflight.yml#L75-L101
* https://github.com/cloudalchemy/ansible-prometheus/issues/230

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible Core

##### ANSIBLE VERSION
```paste below
ansible 2.8.4
  config file = /home/bdupuis/git/vpnssl/ansible/ansible.cfg
  configured module search path = [u'/home/bdupuis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Jul  9 2019, 16:43:02) [GCC 8.3.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey
ANSIBLE_SSH_RETRIES(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = 3
CACHE_PLUGIN(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = /tmp/ansible
CACHE_PLUGIN_TIMEOUT(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = [u'timer', u'profile_tasks']
DEFAULT_GATHERING(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = [u'/opt/ansible/ansible_projects/vpnssl/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = /home/bdupuis/ansible.log
DEFAULT_ROLES_PATH(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = [u'/opt/ansible/ansible_roles']
HOST_KEY_CHECKING(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/xxxx/git/vpnssl/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

##### STEPS TO REPRODUCE
* Use https://github.com/cloudalchemy/ansible-prometheus
* Set version to latest

cf. https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/preflight.yml#L75-L101

##### EXPECTED RESULTS
URL should be set to https://github.com/prometheus/prometheus/releases/download/v2.12.0/sha256sums.txt

##### ACTUAL RESULTS
URL is setted to https://github.com/prometheus/prometheus/releases/download/vlatest/sha256sums.txt

```paste below
ok: [vpnssl-d01-mon] => {
    "ansible_facts": {
        "prometheus_version": "2.12.0"
    }, 
    "changed": false
}
(...)

fatal: [vpnssl-d01-mon]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://github.com/prometheus/prometheus/releases/download/vlatest/sha256sums.txt : HTTP Error 404: Not Found"
}
```

Best regards,

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/aws/core.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/aws/core.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@poil Thanks for reporting this issue. This has been fixed in `cloudalchemy/ansible-prometheus` repo. I am not able to reproduce this. 

```
# ansible-playbook 62739.yml
PLAY [localhost] *********************************************************************************************

TASK [Gathering Facts] ***************************************************************************************
ok: [localhost]

TASK [Get latest release] ************************************************************************************
ok: [localhost]

TASK [Set prometheus version to 2.14.0] **********************************************************************
ok: [localhost]

TASK [Get checksum for architecture] *************************************************************************
skipping: [localhost] => (item=30c5f14b8e05f5c14cf3d74d8b080ac6f93f765175cfedba524bb2bbb1310451  prometheus-2.14.0.darwin-386.tar.gz)
skipping: [localhost] => (item=252ab997f5bd458d1406060b1a0678d8220e586a1b437c024bb4b9e1d42032ad  prometheus-2.14.0.darwin-amd64.tar.gz)
skipping: [localhost] => (item=1c2a03f1761bed2d9521e2c82847c0dc594d29c4f91806d1a1512b8238f693ed  prometheus-2.14.0.dragonfly-amd64.tar.gz)
skipping: [localhost] => (item=fee0f7431f22512272adbfe36e9c13bd33e3be2af0e353e856a8b95c5d3b7a62  prometheus-2.14.0.freebsd-386.tar.gz)
skipping: [localhost] => (item=b75f29ac40542fa6d3ee9ecb15c0c834e62a1f4505f71380bdfe31ce5d646715  prometheus-2.14.0.freebsd-amd64.tar.gz)
skipping: [localhost] => (item=28c426dcc299e2c145cb17373bda9f6499cbce65987c52bdf49f5897483e3751  prometheus-2.14.0.freebsd-armv6.tar.gz)
skipping: [localhost] => (item=bafb494683130c8368d7b8512b1a0e13f81eaa5d4a5932bf5e503744ce073888  prometheus-2.14.0.freebsd-armv7.tar.gz)
skipping: [localhost] => (item=32d1122bce7e6a43f9a2cf623ea0a946d39803ab300516595656173645118c1a  prometheus-2.14.0.linux-386.tar.gz)
ok: [localhost] => (item=ddf47223ec716594254df110ee26ad52e66d7d4471ae8edbf9020087396861e5  prometheus-2.14.0.linux-amd64.tar.gz)
skipping: [localhost] => (item=15ed186405406c9423a1336ee539133a26bb597b4d2d3346ebd921788f083b45  prometheus-2.14.0.linux-arm64.tar.gz)
skipping: [localhost] => (item=5b3df831dba3b54db4deaf4b2df49edd04f98fea869714f5829f7ab0e77bb382  prometheus-2.14.0.linux-armv5.tar.gz)
skipping: [localhost] => (item=d352599d9a2c9db88f6ca448fc0ead9f63c7a66f6c20df689819c83215000957  prometheus-2.14.0.linux-armv6.tar.gz)
skipping: [localhost] => (item=c957149be652b8cfda5d2915b0760ab720014dc46b7c0f49f0b19e3d723e1431  prometheus-2.14.0.linux-armv7.tar.gz)
skipping: [localhost] => (item=8c72562c753a203396e4931797be060e69b3a9077cd07c6ec487133da22db33f  prometheus-2.14.0.linux-mips64.tar.gz)
skipping: [localhost] => (item=0ed799763f451fe09024d97290a3460c0c10086870d01dc3ba05c259f1fbd57b  prometheus-2.14.0.linux-mips64le.tar.gz)
skipping: [localhost] => (item=9f72c71358dc371792cc488188b0976e3d7282b5db7a69f3786ad61f748244f4  prometheus-2.14.0.linux-ppc64.tar.gz)
skipping: [localhost] => (item=b234b84339015b049223baa1a7a8798b7baf0b5d505033bd266a8ee601bcd271  prometheus-2.14.0.linux-ppc64le.tar.gz)
skipping: [localhost] => (item=2b12e75d07fa24523e8ab2a4bbaad58a7667b45a50956e989e0357ff13caa13c  prometheus-2.14.0.linux-s390x.tar.gz)
skipping: [localhost] => (item=d5465a19501ed68a5a8656d9dc09c2d19e837c73e61d7309af9fbf8e2227f054  prometheus-2.14.0.netbsd-386.tar.gz)
skipping: [localhost] => (item=f06d217935457380a548a9f6bb5ff4b41b8f115406e6ec53b85ae6322edeea51  prometheus-2.14.0.netbsd-amd64.tar.gz)
skipping: [localhost] => (item=6b76e49fd3d3076b6b114a50a417730e454373423c23e19f08d59f0d4fa1dfaa  prometheus-2.14.0.netbsd-armv6.tar.gz)
skipping: [localhost] => (item=2e97127ba5c211f049acbec86b6420b61f32e9d358d03a7fdfae2d44c83a83c3  prometheus-2.14.0.netbsd-armv7.tar.gz)
skipping: [localhost] => (item=d30a813107106acdda9b97396b2841b12dcb9bee54d73b828bef615f79cb6cd4  prometheus-2.14.0.openbsd-386.tar.gz)
skipping: [localhost] => (item=fb9ca8c36a6b2bf7c9f891316d67467096dfef50cd3b109b6a669a7ea826dbe8  prometheus-2.14.0.openbsd-amd64.tar.gz)
skipping: [localhost] => (item=d016478677ad2a519e4beae359591948daf7bc0adf60507ffca45074465957e0  prometheus-2.14.0.openbsd-armv7.tar.gz)
skipping: [localhost] => (item=3353c5a970c9a3303d1790564d918bcedb040cf1225a155c0777d1baa106180d  prometheus-2.14.0.windows-386.tar.gz)
skipping: [localhost] => (item=0180f767df0a3a855b98e3e3f6600c35af4486cc07d7f5f26b31e203f8a9a249  prometheus-2.14.0.windows-amd64.tar.gz)

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "ddf47223ec716594254df110ee26ad52e66d7d4471ae8edbf9020087396861e5"
}

PLAY RECAP ***************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Short version of preflight.yml 

```yaml

---
- hosts: localhost
  vars:
      go_arch: amd64
  tasks:
  - block:
      - name: Get latest release
        uri:
          url: "https://api.github.com/repos/prometheus/prometheus/releases/latest"
          method: GET
          return_content: true
          status_code: 200
          body_format: json
          validate_certs: false
        register: _latest_release
        until: _latest_release.status == 200
        retries: 5

      - name: "Set prometheus version to {{ _latest_release.json.tag_name[1:] }}"
        set_fact:
          prometheus_version: "{{ _latest_release.json.tag_name[1:] }}"

  - name: "Get checksum for architecture"
    set_fact:
      prometheus_checksum: "{{ item.split(' ')[0] }}"
    with_items:
      - "{{ lookup('url', 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version + '/sha256sums.txt', wantlist=True) | list }}"
    when:
      - "('linux-' + go_arch + '.tar.gz') in item"
  
  - debug:
      msg: "{{ prometheus_checksum }}"
```

needs_info
