### ISSUE TITLE
TSIG update error (PeerBadKey) with correct key credentials

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#62758]
##### SUMMARY
Using the module ```nsupdate``` with TSIG key credentials from bind9 /etc/bind/rndc.key fails.
The contents of the file looks like:
```
key "<key_name>" {
	algorithm <key_algorithm>;
	secret "<key_secret>";
};
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/actionmystique/src/Ansible/git-yang-networkop/ansible-101/library']
  ansible python module location = /media/actionmystique/SAMSUNG5-Shared/home/actionmystique/src/Ansible/git-ansible/lib/ansible
  executable location = /home/actionmystique/src/Ansible/git-ansible/bin/ansible
  python version = 3.7.4+ (default, Sep  6 2019, 02:09:12) [GCC 9.2.1 20190827]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 240
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
controller host: Ubuntu eoan 19.10
target: Ubuntu 19.10 eoan 19.10
```

##### STEPS TO REPRODUCE
```
- name: Preparing the challenge with Bind - pre-Phase II
  nsupdate:
        key_algorithm: "{{ key_algorithm }}"
        key_name: "{{ key_name }}"
        key_secret: "{{ key_secret }}"
        port: 53
        protocol: tcp
        record: "{{ record }}"
        server: "{{ server }}"
        state: present
        ttl: 60
        type: TXT
        value: "{{ value }}"
        zone: "{{ ansible_domain }}"
```

##### EXPECTED RESULTS
Created a DNS record using DDNS updates

##### ACTUAL RESULTS
Fails:
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_nsupdate_payload__2YYvx/__main__.py", line 240, in __do_update
    response = dns.query.tcp(update, self.module.params['server'], timeout=10, port=self.module.params['port'])
  File "/usr/lib/python2.7/dist-packages/dns/query.py", line 491, in tcp
    q.keyring, q.mac, ignore_trailing)
  File "/usr/lib/python2.7/dist-packages/dns/query.py", line 425, in receive_tcp
    ignore_trailing=ignore_trailing)
  File "/usr/lib/python2.7/dist-packages/dns/message.py", line 823, in from_wire
    reader.read()
  File "/usr/lib/python2.7/dist-packages/dns/message.py", line 751, in read
    self._get_section(self.message.additional, adcount)
  File "/usr/lib/python2.7/dist-packages/dns/message.py", line 703, in _get_section
    self.message.first)
  File "/usr/lib/python2.7/dist-packages/dns/tsig.py", line 185, in validate
    raise PeerBadKey

fatal: [<server>]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "key_algorithm": "<key_algorithm>",
            "key_name": "<key_name>",
            "key_secret": "<key_secret>",
            "port": 53,
            "protocol": "tcp",
            "record": "<record>",
            "server": "<server>",
            "state": "present",
            "ttl": 60,
            "type": "TXT",
            "value": [
                "<value>"
            ],
            "zone": "<ansible_domain>"
        }
    },
    "msg": "TSIG update error (PeerBadKey): The peer didn't know the key we used"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/nsupdate.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nsupdate.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andreaso** [comment]
Have you configured BIND to use the `/etc/bind/rndc.key` TSIG key for the purpose of updating the zone in question? Asking since zone updates is not normal the use of that key.

**Comment by jean-christophe-manciot** [comment]
I have audited my bind9 config & corrected it with a ```ddns-key```.
Now, I am able to successfully add & remove a TXT RR with ```nsupdate``` module.
However, I am experiencing some **trouble deleting an A record** with:
```
- name: Cleaning an A RR
  nsupdate:
        key_algorithm: "{{ key_algorithm }}"
        key_name: "{{ key_name }}"
        key_secret: "{{ key_secret }}"
        port: 53
        protocol: tcp
        record: "{{ record }}"
        server: "{{ server }}"
        state: absent
        ttl: 604800
        type: A
        value: "{{ ip_address }}"
        zone: "{{ ansible_domain }}."
```
leads to:
```
ok: [ns1.sdxlive.com] => {
    "changed": false,
    "dns_rc": 8,
    "dns_rc_str": "NXRRSET",
    "invocation": {
        "module_args": {
            "key_algorithm": "{{ key_algorithm }}",
            "key_name": "{{ key_name }}",
            "key_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 53,
            "protocol": "tcp",
            "record": "{{ record }}",
            "server": "{{ server }}",
            "state": "absent",
            "ttl": 604800,
            "type": "A",
            "value": [
                "{{ ip_address }}"
            ],
            "zone": "{{ ansible_domain }}."
        }
    },
    "record": {
        "record": "{{ record }}",
        "ttl": 604800,
        "type": "A",
        "value": [
            "{{ ip_address }}"
        ],
        "zone": "{{ ansible_domain }}."
    }
}
```
The ```NXRRSET``` return code seems to show that the RR does not exist.
However, after the call, the RR still exists on the name server:
```
dig @127.0.0.1 $record any

; <<>> DiG 9.15.3 <<>> @127.0.0.1 $record any
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42917
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (good)
;; QUESTION SECTION:
;$record	IN	ANY

;; ANSWER SECTION:
...RRSIG	& NSEC RRs
$record 604800 IN	A	

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Sep 24 17:18:49 CEST 2019
;; MSG SIZE  rcvd: 1247
```
