### ISSUE TITLE
vars from import_role affect unrelated identical task

### ISSUE THREAD

**Issue by saf** [ansible/ansible#62753]
##### SUMMARY
If I have a task which is identical between a role imported via `import_role` and another part of the playbook, the `vars` setting from the `import_role` seems to be applied on the other occurrence.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
?

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
```
This occurs with versions starting at Ansible 2.7.0.

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/saf/code/editshare-ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Ubuntu Linux 18.04.

##### STEPS TO REPRODUCE
The minimal test case, extracted from a larger playbook which has started failing with Ansible ≥2.7 is as follows:

**playbook.yml**
```yaml
---
- hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: Print out value of variable
      debug:
        msg:
        - "{{ variable }}"
        - "{{ second_variable | default(variable) }}"
      vars:
        variable: one

    - name: Get value for second import
      set_fact:
        second_value: two
    - name: Import role
      import_role:
        name: minimal
      vars:
        variable: '{{ second_value }}'
        second_variable: '{{ second_value }}'
```

The imported role is as follows:
**roles/minimal/tasks/main.yml**:
```yaml
---
- name: Do configuration for "{{ variable }}"
  debug:
    msg:
      - "{{ variable }}"
      - "{{ second_variable | default(variable) }}"
```
Note how the definition of the task in `playbook.yml` and the task in the `minimal` role are identical. If I change anything in either of those, the playbook executes properly.

##### EXPECTED RESULTS
The playbook should execute successfully because the task in the playbook is not related to the task in the role. This is the correct output, with Ansible 2.6:
```
PLAY [localhost] ***************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [Print out value of variable] *********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "one",
        "one"
    ]
}

TASK [Get value for second import] *********************************************************************************************************************************************************
ok: [localhost]

TASK [minimal : Do configuration for "two"] ************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "two",
        "two"
    ]
}
```

##### ACTUAL RESULTS

The first task in the playbook somehow attempts to use the variables defined at the `import_role`, and complains that `second_value` is not defined at this point.

```paste below
PLAY [localhost] ***************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [Print out value of variable] *********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'second_value' is undefined\n\nThe error appears to be in '/home/saf/code/editshare-ansible/playbook.yml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Print out value of variable\n      ^ here\n"}

PLAY RECAP *********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
This can be worked around by:
* changing anything in the task, compared to the task in the role,
* switching from `import_role` to `include_role`.
