### ISSUE TITLE
Allow `os_object` to set container properties

### ISSUE THREAD

**Issue by colans** [ansible/ansible#62760]
##### SUMMARY

I need to be able to run the following command in order to set a user-specific access key for the container:

```
openstack container set --property Full-Key=$CONTAINER_API_KEY $CONTAINER_NAME
```

...but this doesn't appear possible with the module currently.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

Ansible os_object.py

##### ADDITIONAL INFORMATION

This functionality is needed for enabling [container-specific API keys](http://docs.clouda.ca/bulk-storage/container-keys).  Without it, one must resort to running a `command` task to issue the command above.

I'm assuming we can add a `properties` parameter to enable this.  Here's an example task:

```yaml
- name: Create an object storage container
  os_object:
    state: present
    container: "{{ container_name }}"
    properties:
      - Full-Key: "{{ container_api_key }}"
      - ...
  delegate_to: "{{ control_server }}"
```
