### ISSUE TITLE
ios_interface doesn't allow to delete an interface description

### ISSUE THREAD

**Issue by herdir** [ansible/ansible#62765]
##### SUMMARY
ios_interface doesn't allow to delete an interface description

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_interface

##### ANSIBLE VERSION

```
ansible 2.7.5
  config file = /home/user/switch_int_desc/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```

ANSIBLE_SSH_ARGS(/home/user/switch_int_desc/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_WHITELIST(/home/user/switch_int_desc/ansible.cfg) = [u'timer']
DEFAULT_HOST_LIST(/home/user/switch_int_desc/ansible.cfg) = [u'/home/user/switch_int_desc/hosts']
DEFAULT_LOG_PATH(/home/user/switch_int_desc/ansible.cfg) = /home/user/switch_int_desc/ansible_log
DEFAULT_TIMEOUT(/home/user/switch_int_desc/ansible.cfg) = 5
DEFAULT_TRANSPORT(/home/user/switch_int_desc/ansible.cfg) = paramiko
HOST_KEY_CHECKING(/home/user/switch_int_desc/ansible.cfg) = False

```

##### OS / ENVIRONMENT

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

##### STEPS TO REPRODUCE

```yaml
    - name: delete description
      ios_interface:
        name: FastEthernet0/1
        description: false
        provider: "{{ cli }}"
      when:
        - ansible_net_interfaces['FastEthernet0/1']['operstatus'] == "down" or ansible_net_interfaces['FastEthernet0/1']['operstatus'] == "administratively down"


```

##### EXPECTED RESULTS

Name the interface description "False".
Same issue if the variable is "description: no" .

##### ACTUAL RESULTS

Verbose :
changed: [HOSTNAME => {
    "changed": true,
    "commands": [
        "interface FastEthernet0/1",
        "description False"
    ],
    "invocation": {
        "module_args": {
            "aggregate": null,
            "auth_pass": null,
            "authorize": null,
            "delay": 10,
            "description": "False",
            "duplex": null,
            "enabled": true,
            "host": null,
            "mtu": null,
            "name": "FastEthernet0/1",
            "neighbors": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 1200,
                "username": "Temp_support"
            },
            "rx_rate": null,
            "speed": null,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "tx_rate": null,
            "username": null
        }
    }
}
