### ISSUE TITLE
vm_guest module: Provision additional disks dynamically via variable.  

### ISSUE THREAD

**Issue by furball9000** [ansible/ansible#62770]
##### SUMMARY
From with the vm_guest module have the ability to provision additional disks dynamically via a variable. If the variable details are empty, skip.

The idea being that you can have a SNOW form to provision a server and the disk numbers/details can be defined and passed to Ansible. So you can 1 or 15 disks defined without vm_guest failing due to undefined variables.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_guest

##### ADDITIONAL INFORMATION
Having the ability to define all potential disks in the playbook and have them ignored if they are not referenced. This would be ideal and if I've missed a method whereby I can do this, please let me know. I've tried using omit and also defining the disks with a with_dict that would describe the disk requirements and iterate over the the -disk section of vm_guest, but it just overwrites the initial disk.  

```yaml

Variables: 
---
vm_disk_datastore0: C6200_T2_FCP_3Days
vm_disk_type0: Thin
vm_disk_size0: 80
vm_disk_datastore1: C6200_T2_FCP_3Days
vm_disk_type1: Thin
vm_disk_size1: 50
vm_disk_datastore2: ""
vm_disk_type2: ""
vm_disk_size2: ""
vm_domain: corp.local
vm_hostname: hplavcs001.corp.local
vm_datacenter: DC2
vm_folder: /DC2/vm/ap-dev
vm_servername: pdwaoatst76
vm_template: Windows2016_x64_AN_ESX_v1.1
vm_cluster: C6200_NPE_PC_ST
vm_memory_mb: 16000
vm_num_cpus: 4
vm_network: C6200_10.110.64.0_24_VL1750

  - name: Launch Windows 2016 VM Instance
    vmware_guest:
      validate_certs: no
      datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_servername }}"
      state: poweredon
      template: "{{ vm_template }}"
      cluster: "{{ vm_cluster }}"
      disk:
      - size_gb: "{{ vm_disk_size0 }}"
        type: "{{ vm_disk_type0 }}"
        datastore: "{{ vm_disk_datastore0 }}"
      - size_gb: "{{ vm_disk_size1 | default(omit) }}"
        type: "{{ vm_disk_type1 | default(omit) }}"
        datastore: "{{ vm_disk_datastore1 | default(omit) }}"
      - size_gb: "{{ vm_disk_size2 |default(omit) }}"
        type: "{{ vm_disk_type2 | default(omit) }}"
        datastore: "{{ vm_disk_datastore2 | default(omit) }}"
      hardware:
        memory_mb: "{{ vm_memory_mb | default(8192) }}"
        num_cpus: "{{ vm_num_cpus }}"
      networks:
      - name: "{{ vm_network }}"
        start_connected: yes
        vlan: "{{ vm_network }}"
        device_type: vmxnet3
        type: dhcp
        domain: "{{ vm_domain }}"
      customization:
        hostname: "{{ vm_servername }}"
        orgname: corp
        password: "{{ winlocal_admin_pass }}"
        timezone: 255
      wait_for_ip_address: yes 
    register: vm


second method:
Variables

disks:
  0:
    vm_disk_datastore: C6200_T2_FCP_3Days
    vm_disk_type: Thin
    vm_disk_size: 80
  1:
    vm_disk_datastore: C6200_T2_FCP_3Days
    vm_disk_type: Thin
    vm_disk_size: 50
  2:
    vm_disk_datastore: ""
    vm_disk_type: ""
    vm_disk_size: ""
vm_domain: corp.local
vm_hostname: hplavcs001..local
vm_datacenter: DC2
vm_folder: /DC2/vm/ap-dev
vm_servername: pdwaoatst75
vm_template: AP_Windows2016_x64_AN_ESX_v1.1
vm_cluster: C6200_NPE_PC_ST
vm_memory_mb: 16000
vm_num_cpus: 4
vm_network: C6200_10.110.64.0_24_VL1750

Playbook:
---
- hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:

  - name: Launch Windows 2016 VM Instance
    vmware_guest:
      validate_certs: no
      datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_servername }}"
      state: poweredon
      template: "{{ vm_template }}"
      cluster: "{{ vm_cluster }}"
      disk:
      - size_gb: "{{ item.value.vm_disk_size }}"
        type: "{{ item.value.vm_disk_type }}"
        datastore: "{{ item.value.vm_disk_datastore}}"
      hardware:
        memory_mb: "{{ vm_memory_mb | default(8192) }}"
        num_cpus: "{{ vm_num_cpus }}"
      networks:
      - name: "{{ vm_network }}"
        start_connected: yes
        vlan: "{{ vm_network }}"
        device_type: vmxnet3
        type: dhcp
        domain: "{{ vm_domain }}"
      customization:
        hostname: "{{ vm_servername }}"
        orgname: corp
        password: "{{ winlocal_admin_pass }}"
        timezone: 255
      wait_for_ip_address: yes 
    register: vm
    with_dict: "{{ disks }}"
    when:
      - item.value.vm_disk_datastore != ""
      - item.value.vm_disk_size != ""
      - item.value.vm_disk_type != ""

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@furball9000 Thanks for reporting. I think this is more of a user question than `vmware_guest` issue.

You can achieve same result by -

```yaml
---
- hosts: localhost
  vars_files:
    - vcenter_vars.yml
  vars:
    disks:
      'disk0':
        vm_disk_datastore: C6200_T2_FCP_3Days
        vm_disk_type: Thin
        vm_disk_size: 80
      'disk1':
        vm_disk_datastore: C6200_T2_FCP_3Days
        vm_disk_type: Thin
        vm_disk_size: 50
      'disk2':
        vm_disk_datastore: ""
        vm_disk_type: ""
        vm_disk_size: ""
  tasks:
    - set_fact:
        disk_data: "{{ disk_data | default([]) + [{'size_gb': item.value.vm_disk_size, 'datastore': item.value.vm_disk_datastore, 'type': item.value.vm_disk_type }]}}"
      with_dict: "{{ disks }}"
      when:
        - item.value.vm_disk_datastore != ""
        - item.value.vm_disk_size != ""
        - item.value.vm_disk_type != ""

    - debug:
        msg: "{{ disk_data }}"

    - name: Modify VM with existing disks
      vmware_guest:
        validate_certs: False
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: "{{ dc1 }}"
        cluster: Asia-Cluster1
        name: my_clone_deb_1
        folder: /Asia-Datacenter1/vm/
        disk: '{{ disk_data }}'
        state: present
      register: vm_nw_facts
```

Hope this helps. Thanks,
