### ISSUE TITLE
AWS: elb_application_lb_info filtering fails with more than one name

### ISSUE THREAD

**Issue by Xaroth** [ansible/ansible#62777]
##### SUMMARY
when using `elb_application_lb_info` to fetch information of more than one ALB by name, no info is returned. If only one name is used, information is returned

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elb_application_lb_info

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /deploy-data/ansible-deploy/ansible.cfg
  configured module search path = ['/deploy-data/ansible-deploy/library']
  ansible python module location = /var/lib/awx/venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible/bin/ansible
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu, Debian, RHEL

##### STEPS TO REPRODUCE

Step 1, have an ALB with the name 'test'

This yields a response
```yaml
- elb_application_lb_info:
    region: "{{ aws_region }}"
    names:
      - test
```

This will not yield a response
```yaml
- elb_application_lb_info:
    region: "{{ aws_region }}"
    names:
      - test
      - alb_that_does_not_exist
```

This will yield a response containing both albs
```yaml
- elb_application_lb_info:
    region: "{{ aws_region }}"
    names:
      - test
      - alb_that_does_exist
```

##### EXPECTED RESULTS
It is expected that the returned list contains ANY ALB that matches the name, instead of only returning if _all_ names exist.

##### ACTUAL RESULTS
When more than one name is specified in `names`, it will only result items if _all_ the names requested exist, if only a partial subset is matched, _no_ items are returned.
