### ISSUE TITLE
pids_module list pids by regexp

### ISSUE THREAD

**Issue by AlexeyPerevalov** [ansible/ansible#62776]
##### SUMMARY

Sometimes it's necessary to work with pids of the processes which match the particular regular expression.

For example: ".*" can match all pids on the system and these pids can be placed to cgroup or taskset can be executed for all pids. Or another operations with the group of pids could proceeded.

pids_module

```yaml
    - pids:
        name: .*
      register: pids_of_the_system

    - name: Place pids on appropriate CPU
      shell: taskset -p 7 {{ item }}
      loop: "{{ pids_of_the_system.pids | flatten(1) }}"

```
