### ISSUE TITLE
ec2_vpc_peer does not support modifying peering settings

### ISSUE THREAD

**Issue by Xaroth** [ansible/ansible#62783]
##### SUMMARY
EC2 VPC Peers support some settings that can be retrieved by ec2_vpc_peering_info, but cannot be set.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_vpc_peer

##### ADDITIONAL INFORMATION
Currently, the following settings are available, but unsettable by ansible:

```yaml
      peering_options:
        allow_dns_resolution_from_remote_vpc: false
        allow_egress_from_local_classic_link_to_remote_vpc: false
        allow_egress_from_local_vpc_to_remote_classic_link: false
```
This goes for both sides (requestor, acceptor) of the peering connection.

botocore already supports changing these settings through https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.modify_vpc_peering_connection_options
