### ISSUE TITLE
vmware_guest_network.py uses product uuid

### ISSUE THREAD

**Issue by patede** [ansible/ansible#62784]
##### SUMMARY
The documentation states the instance uuid is required for the uuid parameter but the hw product uuid is used instead. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_network

##### ANSIBLE VERSION

```paste below
ansible 2.9.0rc1.post0
  config file = None
  configured module search path = ['/home/pernst/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Configure virtual network cards
  vmware_guest_network:
    hostname: "{{ vsphere_host }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_pass }}"
    validate_certs: "{{ vsphere_validate_certs | default(true) }}"
    datacenter: "{{ vsphere_target_dc }}"
    uuid: "{{ vm_facts.instance.instance_uuid }}"
  register: vm_networks
  delegate_to: localhost
```

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "msg": "Unable to find the specified virtual machine using <UUID>
```

P.S.:  I suggest the same uuid handling as in vmware_guest with an additional use_instance_uuid parameter.
