### ISSUE TITLE
Apt module: aptitude, upgrade: yes hangs after completing

### ISSUE THREAD

**Issue by ZeroChanceCompile** [ansible/ansible#62807]
##### SUMMARY
Using the apt module to do a system upgrade hangs. I'm using the apt module to install aptitude then use aptitude to do apt update, apt upgrade. 

If I manually ssh into the managed device I can see the following running.
```
pi        1884  0.0  0.0   1940   392 pts/0    Ss+  02:50   0:00 /bin/sh -c sudo -H -S -n  -u root /bin/sh -c 'echo BECOME-SUCCESS-pywdgfievbjwsdkvgngqanirpvqr
root      1885  0.0  0.3   9952  3024 pts/0    S+   02:50   0:00 sudo -H -S -n -u root /bin/sh -c echo BECOME-SUCCESS-pywdgfievbjwsdkvgngqanirpvqropka ; /usr/b
root      1890  0.0  0.0   1940   372 pts/0    S+   02:50   0:00 /bin/sh -c echo BECOME-SUCCESS-pywdgfievbjwsdkvgngqanirpvqropka ; /usr/bin/python /home/pi/.an
root      1891  0.0  1.1  18300 11212 pts/0    S+   02:50   0:00 /usr/bin/python /home/pi/.ansible/tmp/ansible-tmp-1567561855.42-212285021489415/AnsiballZ_comm
root      1892  0.0  0.0   1940   396 pts/0    S+   02:50   0:00 /bin/sh -c sudo apt update -y && sudo apt upgrade -y
root      2012  0.0  0.3   9952  3052 pts/0    S+   02:51   0:00 sudo apt upgrade -y
root      2017  0.2  4.9  55700 46948 pts/0    S+   02:51   0:01 apt upgrade -y
```

I can see the update finish when the above processes go away. I can also manually run `sudo apt upgrade` and see that the system is up to date. However, the Ansible playbook is still running and will continue to hang. I've waited 45 minutes for it to terminate. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/redacted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Controller
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"

##### STEPS TO REPRODUCE
Raspberry Pi 3B+, Buster Raspbian stock image.
```
---
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present
    update_cache: yes

- name: Upgrade System
  apt: 
    update_cache: yes
    upgrade: yes
```

##### EXPECTED RESULTS
Same as sudo apt update && sudo apt upgrade, and then Ansible completes successfully.

##### ACTUAL RESULTS
sudo ansible-playbook -i inventory.yml rpi_buster.yml --become -vvvv | tee ~/ansibleVerboseUpgradeError.txt
 https://gist.github.com/ZeroChanceCompile/27b1357cc8f09502e84b3fa7aa5ee7f0

Managed machine ps -aux output:
https://gist.github.com/ZeroChanceCompile/e3d2043033786665fe9def8d32adc210

Aptitude log from managed machine:
https://gist.github.com/ZeroChanceCompile/e2f08df68733229bc94a17391abb3ddd

Thanks for reading!!

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by RogerSik** [comment]
Can confirm it. Same problem here with the module apt: When using with apt_cache true it hangs. Without it this problem doesn't appear. 

Ansible 2.8.4 is here in use.

**Comment by ZeroChanceCompile** [comment]
Okay, I found the problem for me. It appears that ssh is timing out but the playbook doesn't end when ssh closes which is weird. Personally, that seems like a bug.

I was able to do the update asynchronously and get it to work. 
```
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present
    update_cache: yes

- name: Upgrade System
  apt: 
    update_cache: yes
    upgrade: yes
  async: 3600
  poll: 30
  register: apt_sleeper
```
