### ISSUE TITLE
dnf (and probly yum) wild-card match remove is not idempotence

### ISSUE THREAD

**Issue by rabin-io** [ansible/ansible#62809]
##### SUMMARY
When using wild-card in package name to remove, the first run will remove the packages,
but the second run will fail with message `Failed to install some of the specified packages`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- dnf

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /home/rabin/src/ansible/workstation-setup/ansible.cfg
  configured module search path = ['/home/rabin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_CONTROL_PATH(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = ./.ansible/ssh-%%C
CACHE_PLUGIN(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = ./.ansible/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = 86400
DEFAULT_EXECUTABLE(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = /bin/bash
DEFAULT_GATHERING(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = ['/home/rabin/src/ansible/workstation-setup/inventory']
DEFAULT_REMOTE_PORT(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = 22
RETRY_FILES_SAVE_PATH(/home/rabin/src/ansible/workstation-setup/ansible.cfg) = /home/rabin/src/ansible/workstation-setup/.ansible/retry
```

##### OS / ENVIRONMENT

* Fedora 30

##### STEPS TO REPRODUCE

try to remove a package twice
or run the playbook twice (first run will work if there is a match, but secend run will fail)

```yaml
- dnf:
    name: lohit-*-fonts

- dnf:
    name: lohit-*-fonts
    state: absent

- dnf:
    name: lohit-*-fonts
    state: absent

```

##### EXPECTED RESULTS
Same as when you ask it to remove a spesific package
```yaml
- dnf:
    name: lohit-tamil-fonts

- dnf:
    name: lohit-tamil-fonts
    state: absent

- dnf:
    name: lohit-tamil-fonts
    state: absent
```

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "failures": ["lohit-*-fonts - no package matched: lohit-*-fonts"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```
