### ISSUE TITLE
Support pre-run condition to see if state is already correct (e.g. ok_when)

### ISSUE THREAD

**Issue by CendioOssman** [ansible/ansible#62817]
(This is a duplicate of #12710, which is a rather not-nice thing to do. But that issue was closed and locked with the reason "we don't understand what it is you are asking for". So in this case I think it warrants an exception. Please take the time to read that issue and this and understand what we are requesting. If you still decide it doesn't fit in Ansible then please try to help us understand why.)

##### SUMMARY
Add a `ok_when` condition to tasks. When it evaluates to True, dont run the task and show OK. When it evaluates to False or it is missing and when evaluates to True, run the task.
I know I could run the `Install WordPress plugins` task for each plugin but that is time consuming when you have a big list of plugins as the wp command seems to have a high startup time.

It also gives a much nicer user experience as you see the state is what you want, rather than unknown which is all `when` will give you.

Basically give us the power to a bit more of what modules can do directly from tasks.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION

Example play which would benefit form this feature.

```
- name: Get list of installed WordPress plugins
  command: 'wp plugin list --format=json'
  sudo_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  changed_when: False
  always_run: True
  register: wordpress_plugin_list_installed_cmd
- name: Convert list of installed WordPress plugins from JSON
  set_fact:
    wordpress_plugin_installed_dict: '{{ wordpress_plugin_list_installed_cmd.stdout|from_json }}'
- name: Set list of installed WordPress plugins
  set_fact:
    wordpress_plugin_installed_list: '{{ wordpress_plugin_installed_dict|map(attribute="name")|list }}'
    wordpress_plugin_active_list: '{{ wordpress_plugin_installed_dict|selectattr("status", "equalto", "active")|map(attribute="name")|list }}'
- name: Install WordPress plugins
  command: 'wp plugin install "{{ item.name }}"'
  sudo_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  when: item.name|d() and (item.install|d(True) | bool) and item.name not in wordpress_plugin_installed_list
  ok_when: item.name|d() and (item.install|d(True) | bool) and item.name in wordpress_plugin_installed_list
  with_items: wordpress_plugins
```

##### EXPECTED RESULTS

```
TASK: [wordpress | Install WordPress plugins] *********************************
ok: [jessie.testing] => (item={'name': 'akismet'})
```

##### ACTUAL RESULTS

```
TASK: [wordpress | Install WordPress plugins] *********************************
skipping: [jessie.testing] => (item={'name': 'akismet'})
```
