### ISSUE TITLE
pip module always set to changed when using check mode

### ISSUE THREAD

**Issue by rien** [ansible/ansible#62826]
##### SUMMARY
The pip module will always be 'changed' when using a virtualenv and when running in check mode.

This is caused by [this block](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py#L472) in the pip module:
```python
def setup_virtualenv(module, env, chdir, out, err):
    if module.check_mode:
        module.exit_json(changed=True)
    ...
```
Instead of actually checking if the virtualenv exists and if all the requirements are present.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Pip module

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

All OS'es

##### STEPS TO REPRODUCE

```yaml
- name: Test pip
  hosts: 127.0.0.1
  connection: local

  pre_tasks:
    - name: Create test dir
      file:
        path: /tmp/test-playbook/
        state: directory

    - name: Create requirements.txt
      copy:
        dest: /tmp/test-playbook/requirements.txt
        content: "ansible==2.8.5"

    - name: Install virtualenv
      pip:
        requirements: /tmp/test-playbook/requirements.txt
        virtualenv: /tmp/test-playbook/venv
        virtualenv_python: python3
```

First execute this playbook with `ansible-playbook test.yml` and then run `ansible-playbook --check test.yml`.

##### EXPECTED RESULTS

The "Install virtualenv" task should not be changed.

##### ACTUAL RESULTS

The task shows that it's changed.

```paste below
/t/test-playbook ❯❯❯ ansible-playbook test.yml --check
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [Test pip] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Create test dir] ************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Create requirements.txt] ****************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Install virtualenv] *********************************************************************************************************************************************************************
changed: [127.0.0.1]

PLAY RECAP ************************************************************************************************************************************************************************************
127.0.0.1                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Note: when running the playbook without check mode, it is not changed.
```
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [Test pip] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Create test dir] ************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Create requirements.txt] ****************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Install virtualenv] *********************************************************************************************************************************************************************
ok: [127.0.0.1]

PLAY RECAP ************************************************************************************************************************************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/language/pip.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Lujeni @mattupstate @webknjaz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by acalm** [comment]
The changed state is actually set on [line 712](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py#L712) in this block:
```python
if module.check_mode:
    if extra_args or requirements or state == 'latest' or not name:
        module.exit_json(changed=True)
```
Which is right before pip is actually run. Since the requirements parameter is set in the playbook the module guesses that the state will be changed as the list of packages to install/update is out of scope for the module, I.E they're specified in the requirements file.

**Comment by rien** [comment]
@acalm It is possible to check whether packages are installed with `pip freeze`:

When a package is not installed:
```
/tmp/test-playbook ❯❯❯ ./venv/bin/pip freeze --no-cache -vvvr requirements.txt
Created temporary directory: /tmp/pip-ephem-wheel-cache-z12gz0_a
WARNING: Requirement file [requirements.txt] contains ansible==2.8.5, but package 'ansible' is not installed
## The following requirements were added by pip freeze:
```
When a package is installed:
```
/tmp/test-playbook ❯❯❯ ./venv/bin/pip freeze --no-cache -vvvr requirements.txt
Created temporary directory: /tmp/pip-ephem-wheel-cache-ntsvzhmt
ansible==2.8.5
## The following requirements were added by pip freeze:
asn1crypto==0.24.0
cffi==1.12.3
cryptography==2.7
Jinja2==2.10.1
MarkupSafe==1.1.1
pycparser==2.19
PyYAML==5.1.2
six==1.12.0
```
Note that while the output says it has added requirements, it does not alter files in current the directory or the virtual environment.

I suggest fixing this issue by running `pip freeze -r requirements.txt` and checking the output.

**Comment by sivel** [comment]
I believe the code has been written under the assumption that you are using `virtualenv` and that `/path/to/vitrualenv/bin/activate` exists.

The virtualenv is only created when `/path/to/virtualenv/bin/activate` doesn't exist, and if you make it to the code block you indicate, you are creating the virtualenv, and thus in check mode it will return changed.

If I were to guess, that path check is failing for some reason:

https://github.com/ansible/ansible/blob/d3ec5ca80f630ed8c78ea3fab73e0d2927a89b5e/lib/ansible/modules/packaging/language/pip.py#L645-L648

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/pip.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/pip.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JulienPalard** [comment]
Looks like it can also be done using `pip list --outdated`.

**Comment by donkirkby** [comment]
Until this gets fixed, I came up with this workaround:

```
- name: create directory for virtualenv
  file:
    path: /opt/venv_myapp
    state: directory

- name: copy requirements file to track changes
  register: myapp_requirements
  copy:
    dest: /opt/venv_myapp/requirements.txt
    src: requirements.txt

- name: install python requirements
  when: myapp_requirements.changed
  pip:
    requirements: /path/to/src/requirements.txt
    virtualenv: /opt/venv_myapp
```

That saves a copy of the requirements file, and only runs the `pip` command when the requirements file has changed. You don't have to copy the requirements file into the virtualenv, it could go anywhere.

**Comment by vbotka** [comment]
I see this problem also without *virtualenv* in 2.10

```
ansible 2.10.10
  config file = /home/vlado/.ansible.cfg
  configured module search path = ['/home/vlado/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```



The [task](https://raw.githubusercontent.com/vbotka/ansible-lint/master/tasks/pip.yml) reports *changed: true* in check mode

```yaml
  result:
    changed: true
    msg: All items completed
    results:
    - ansible_loop_var: item
      attempts: 1
      changed: true
      failed: false
      invocation:
        module_args:
          chdir: null
          editable: false
          executable: /usr/bin/pip3
          extra_args: --user
          name:
          - ansible-lint
          requirements: null
          state: present
          umask: null
          version: null
          virtualenv: null
          virtualenv_command: virtualenv
          virtualenv_python: null
          virtualenv_site_packages: false
      item:
        name: ansible-lint
```
But, there are no changes when executing the module

```yaml
  result:
    changed: false
    msg: All items completed
    results:
    - ansible_loop_var: item
      attempts: 1
      changed: false
      cmd:
      - /usr/bin/pip3
      - install
      - --user
      - ansible-lint
      failed: false
      invocation:
        module_args:
          chdir: null
          editable: false
          executable: /usr/bin/pip3
          extra_args: --user
          name:
          - ansible-lint
          requirements: null
          state: present
          umask: null
          version: null
          virtualenv: null
          virtualenv_command: virtualenv
          virtualenv_python: null
          virtualenv_site_packages: false
      item:
        name: ansible-lint
      name:
      - ansible-lint
      requirements: null
      state: present
      stderr: |-
        /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
          from cryptography.utils import int_from_bytes
        /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
          from cryptography.utils import int_from_bytes
      stderr_lines:
      - '/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead'
      - '  from cryptography.utils import int_from_bytes'
      - '/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead'
      - '  from cryptography.utils import int_from_bytes'
      stdout: |-
        Requirement already satisfied: ansible-lint in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (5.0.11)
        Requirement already satisfied: rich>=9.5.1 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (10.2.2)
        Requirement already satisfied: packaging in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (20.9)
        Requirement already satisfied: wcmatch>=7.0 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (8.2)
        Requirement already satisfied: enrich>=1.2.6 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (1.2.6)
        Requirement already satisfied: ruamel.yaml<1,>=0.15.37; python_version >= "3.7" in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (0.17.9)
        Requirement already satisfied: tenacity in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (7.0.0)
        Requirement already satisfied: pyyaml in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (5.4.1)
        Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from rich>=9.5.1->ansible-lint) (0.9.1)
        Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/lib/python3/dist-packages (from rich>=9.5.1->ansible-lint) (0.4.3)
        Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from rich>=9.5.1->ansible-lint) (2.6.1)
        Requirement already satisfied: pyparsing>=2.0.2 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from packaging->ansible-lint) (2.4.7)
        Requirement already satisfied: bracex>=2.1.1 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from wcmatch>=7.0->ansible-lint) (2.1.1)
        Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ruamel.yaml<1,>=0.15.37; python_version >= "3.7"->ansible-lint) (0.2.2)
        Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from tenacity->ansible-lint) (1.14.0)
      stdout_lines:
      - 'Requirement already satisfied: ansible-lint in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (5.0.11)'
      - 'Requirement already satisfied: rich>=9.5.1 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (10.2.2)'
      - 'Requirement already satisfied: packaging in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (20.9)'
      - 'Requirement already satisfied: wcmatch>=7.0 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (8.2)'
      - 'Requirement already satisfied: enrich>=1.2.6 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (1.2.6)'
      - 'Requirement already satisfied: ruamel.yaml<1,>=0.15.37; python_version >= "3.7" in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (0.17.9)'
      - 'Requirement already satisfied: tenacity in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (7.0.0)'
      - 'Requirement already satisfied: pyyaml in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ansible-lint) (5.4.1)'
      - 'Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from rich>=9.5.1->ansible-lint) (0.9.1)'
      - 'Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/lib/python3/dist-packages (from rich>=9.5.1->ansible-lint) (0.4.3)'
      - 'Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from rich>=9.5.1->ansible-lint) (2.6.1)'
      - 'Requirement already satisfied: pyparsing>=2.0.2 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from packaging->ansible-lint) (2.4.7)'
      - 'Requirement already satisfied: bracex>=2.1.1 in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from wcmatch>=7.0->ansible-lint) (2.1.1)'
      - 'Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" in /export/home/vlado.config.ubuntu/.local/lib/python3.8/site-packages (from ruamel.yaml<1,>=0.15.37; python_version >= "3.7"->ansible-lint) (0.2.2)'
      - 'Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from tenacity->ansible-lint) (1.14.0)'
      version: null
      virtualenv: null
```
