### ISSUE TITLE
Ability to create EC2 spot blocks

### ISSUE THREAD

**Issue by asnkh** [ansible/ansible#62856]
##### SUMMARY
In October 2015, [AWS announced the ability to create EC2 spot blocks for defined duration workloads](https://aws.amazon.com/blogs/aws/new-ec2-spot-blocks-for-defined-duration-workloads/).  If ec2 module supports this feature, it will benefit people who want to save costs to run EC2 instances for workloads expected to end within predictable length of time.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- ec2

##### ADDITIONAL INFORMATION
Add a new parameter `block_duration_minutes`:
```yaml
- ec2:
    spot_price: 0.24
    spot_wait_timeout: 600
    block_duration_minutes: 360
    keypair: mykey
    group_id: sg-1dc53f72
    instance_type: m1.small
    image: ami-6e649707
    wait: yes
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
    spot_launch_group: report_generators
```
The parameter value is then passed to [request-spot-instances](https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-instances.html) aws-cli command.
