### ISSUE TITLE
Feature Request: azure_rm_publicip to include zonal support

### ISSUE THREAD

**Issue by JonTheNiceGuy** [ansible/ansible#62861]
##### SUMMARY

azure_rm_publicip does not currently support availability zones. It would be useful if it did. A similar change to managed disks was raised under #53788.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_publicipaddress

##### ADDITIONAL INFORMATION

If you're creating AZ specific VMs (using the value `zones: ['1']`, for example), and you've manually attached an Interface with a Public IP, this also needs to hold the Zone of the IP.

```yaml
- azure_rm_securitygroup:
    resource_group: "{{ rg_demoresourcegroup.state.name }}"
    location: "{{ Region }}"
    name: HostNSG
    rules:
    - name: Host-I-100
      priority: 100
      direction: Inbound
      access: Allow
      protocol: Tcp
      destination_port_range: 22
      source_address_prefix: 0.0.0.0/0
  register: nsg_hostnsg

- azure_rm_publicipaddress:
    resource_group: "{{ rg_demoresourcegroup.state.name }}"
    location: "{{ Region }}"
    name: PubIP
    allocation_method: Dynamic
    zone: "{{ Az1 }}"
  register: ip_pubip

- azure_rm_networkinterface:
    resource_group: "{{ rg_demoresourcegroup.state.name }}"
    location: "{{ Region }}"
    name: HostNIC
    virtual_network: "{{ vnet_demonetwork.state.name }}"
    subnet_name: "{{ subnet_public.state.name }}"
    security_group: "{{ nsg_hostnsg.state.name }}"
    ip_configurations:
    - name: host-nic-ip
      public_ip_address_name: "{{ ip_pubip.state.name }}"
      primary: yes
  register: nic_hostnic

- azure_rm_virtualmachine:
    resource_group: "{{ rg_demoresourcegroup.state.name }}"
    location: "{{ Region }}"
    name: Host
    vm_size: Standard_B1s
    zones: 
    - "{{ Az1 }}"
    network_interface_names: "{{ nic_hostnic.state.name }}"

    image:
      publisher: "Canonical"
      offer: "UbuntuServer"
      sku: "18.04-LTS"
      version: "latest"

    admin_username: "{{ VmUser }}"
    ssh_public_keys: 
    - path: "/home/{{ VmUser }}/.ssh/authorized_keys"
      key_data: "{{ PublicKey }}"
    ssh_password_enabled: false
```
