### ISSUE TITLE
docker_container not idempotent

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#62873]
##### SUMMARY
docker_container is not idempotent when specifying an ip address

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /home/pkueck/projects/cix.de/cix-ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

Fedora 30, CentOS 7

##### STEPS TO REPRODUCE

```yaml
---
- hosts: myhost
  gather_facts: no
  tasks:
    - docker_network:
        name: "foonet"
        ipam_config:
          - subnet: 172.16.44.0/24
    - docker_container:
        name: "foo"
        state: present
        image: centos
        networks:
          - name: foonet
            ipv4_address: "172.16.44.11"
        networks_cli_compatible: yes
      loop: [1,2]
```

##### EXPECTED RESULTS

container created on first loop cycle, not touched on second one

##### ACTUAL RESULTS

```paste below
PLAY [myhost] ***************

TASK [docker_network] *******
ok: [myhost]

TASK [docker_container] *****
--- before
+++ after
@@ -1,9 +1,10 @@
 {
-    "exists": false,
+    "exists": true,
     "network.foonet": {
         "aliases": null,
-        "ipv4_address": "",
-        "ipv6_address": "",
+        "id": "27e539c3b9af0160f02a0532ad081d1bd1ef3dd93e652095ec96d6dfd95bf2fb",
+        "ipv4_address": "172.16.44.11",
+        "ipv6_address": null,
         "links": null,
         "name": "foonet"
     }

changed: [myhost] => (item=1)
--- before
+++ after
@@ -1,10 +1,9 @@
 {
     "network.foonet": {
-        "aliases": [
-            "44cfded131d7"
-        ],
-        "ipv4_address": "",
-        "ipv6_address": "",
+        "aliases": null,
+        "id": "27e539c3b9af0160f02a0532ad081d1bd1ef3dd93e652095ec96d6dfd95bf2fb",
+        "ipv4_address": "172.16.44.11",
+        "ipv6_address": null,
         "links": null,
         "name": "foonet"
     }

changed: [myhost] => (item=2)
```
