### ISSUE TITLE
Ansible intermittently failed in setup after execution of "rm -f -r /home/theatro/.ansible/tmp/ansible-tmp-xxx"

### ISSUE THREAD

**Issue by yonaguska** [ansible/ansible#62882]
I don't see this issue reported

Sorry, I don't have the bandwidth to do that. I installed this ansible 9/23/2019.

##### SUMMARY

I have a set of ten cloned target hosts and a random subset will fail in setup. They appear to fail after the execution of "rm -f -r /home/theatro/.ansible/tmp/ansible-tmp-xxxxxx". If I rerun the playbook the set of failing hosts changes. Some hosts that passed previously will fail and some that have failed, will pass. There is no apparent pattern.

Is there a workaround?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

setup

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/theatro/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[
```

##### CONFIGURATION

```paste below
[theatro@arts playbooks]$ ansible-config dump --only-changed
[theatro@arts playbooks]$
```

##### OS / ENVIRONMENT

CentOS release 6.10 (Final) ... virtual machine running in Qemu/KVM hypervisor
network is bridged
The ten target VMs are clones, identical except for IP and hostname

##### STEPS TO REPRODUCE

Copy a file to a target host and see if the setup process fails (you may have to do this several times). After the run, I see ~/.ansible/tmp on all hosts and tmp is empty.

OUTPUT FROM THREE RUNS:
====================================================================
PLAY RECAP ***********************************************************************************************************************************************************************
10.0.12.20                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.21                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.22                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.23                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.24                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.25                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.26                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.27                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.28                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.29                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.5                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

PLAY RECAP *************************************************************************************************************************************************************************
10.0.12.20                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.21                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.22                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.23                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.24                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.25                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.26                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.27                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.28                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.29                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.5                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

PLAY RECAP *************************************************************************************************************************************************************************
10.0.12.20                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.21                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.22                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.23                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.24                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.25                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.26                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.27                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
10.0.12.28                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.29                 : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
10.0.12.5                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```yaml
INVENTORY:
=============================
devservers:
  hosts:
    10.0.12.1:
    10.0.12.6:

devtgs:
  hosts:
    10.0.12.5:

cloudservers:
  hosts:
    10.0.12.7:
    10.0.12.10:
    10.0.12.11:
    10.0.12.12:
    10.0.12.13:
    10.0.12.14:
    10.0.12.15:
    10.0.12.16:
    10.0.12.17:

storeservers:
  hosts:
    10.0.12.20:
    10.0.12.21:
    10.0.12.22:
    10.0.12.23:
    10.0.12.24:
    10.0.12.25:
    10.0.12.26:
    10.0.12.27:
    10.0.12.28:
    10.0.12.29:
  vars:
    ansible_python_interpreter: /usr/local/bin/python2.7
    discovered_interpreter_python: /usr/local/bin/python2.7


PLAYBOOK
======================
---
- hosts: devtgs
  tasks:
  - name: create a current tarball of arts
    archive:
      path: /opt/theatro/arts
      dest: /opt/theatro/this_arts.tgz
  - name: fetch the tarball from our dev TGS, put it in /tmp
    fetch:
      src: /opt/theatro/this_arts.tgz
      dest: /tmp

- hosts: storeservers
  tasks:
  - name: put the tarball on the remote
    copy:
      src: /tmp/10.0.12.5/opt/theatro/this_arts.tgz
      dest: /tmp
      owner: theatro
      group: theatro
      mode: '0664'
  - name: unpack the archive
    shell: /bin/tar xvfz /tmp/this_arts.tgz
    args: 
      chdir: /opt/theatro
      warn: false


```

##### EXPECTED RESULTS

A tarball is created on a development host and transferred to localhost's /tmp
This tarball is copied from /tmp to the target hosts and untarred, nothing more

##### ACTUAL RESULTS

The process runs correctly on some hosts and setup fails on others. Running the process repeatedly yields a different set of passing and failing hosts each time, there is no pattern.

```paste below
[theatro@arts playbooks]$ ansible-playbook -vvv testpackage.yaml -i inventory.yaml
ansible-playbook 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/theatro/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/theatro/arts_c7/playbooks/inventory.yaml as it did not pass it's verify_file() method
script declined parsing /home/theatro/arts_c7/playbooks/inventory.yaml as it did not pass it's verify_file() method
Parsed /home/theatro/arts_c7/playbooks/inventory.yaml inventory source with yaml plugin

The output of the run is in the attached file:

[failing_ansible_run.txt](https://github.com/ansible/ansible/files/3659298/failing_ansible_run.txt)

```
