### ISSUE TITLE
Cloudflare_dns Doesnt work Stuck/Frozen

### ISSUE THREAD

**Issue by gallexme** [ansible/ansible#62893]
##### SUMMARY
Task Stuck at
"TASK [Create Cloudflare  Records] ***"
no errors
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Cloudflare_dns

##### ANSIBLE VERSION

```
ansible --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```

##### CONFIGURATION
```paste below
ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Debian Linux 5.0 Kernel

##### STEPS TO REPRODUCE

Run this Playbook it instantly just "Stucks", doesnt matter if user exists

```yaml
      - name: Create Cloudflare  Records
        cloudflare_dns:
          zone: h0st.space
          proxied: "no"
          timeout: 5
          ttl: 120
          record: test
          type: A
          value: 127.0.0.1
          account_email:xxxx
          account_api_token: xxxx
```

##### EXPECTED RESULTS
Should Create the DNS Records

##### ACTUAL RESULTS
Freeze
