### ISSUE TITLE
only last iteration will be effective using set_fact with delegation to update object

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#62906]
##### SUMMARY
When updating list a of other hosts in a loop will only update the list with the last iteration of the loop.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- set_fact
- delegation
- loop

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/spolack/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```
NO OUTPUT
```

##### OS / ENVIRONMENT

- MacOSX / Linux, locally ran

##### STEPS TO REPRODUCE

inventory:
```
host_a peers='["a","b"]'
host_b peers='["c","d"]'
host_c peers='["e","f"]'
```

```yaml
---
- hosts: all
  gather_facts: no
  tasks:
   - name: set cache_host
     set_fact:
       cache_host: "{{ inventory_hostname }}"
     run_once: yes

   - name: set play-global cache
     set_fact:
       global_cache: []
     when: inventory_hostname == cache_host

   - name: show global_cache before test
     debug: var=hostvars[cache_host]['global_cache']

   - name: add local peers to global cache
     set_fact:
       global_cache: "{{ hostvars[cache_host]['global_cache'] + [item] }}"
     loop: "{{ peers }}"
     delegate_to: "{{ cache_host }}"
     delegate_facts: yes
     when:
      - inventory_hostname == 'host_a'

   - name: show global_cache after adding host_a peers
     debug: var=hostvars[cache_host]['global_cache']
     run_once: yes

   - name: add local peers to global cache
     set_fact:
       global_cache: "{{ hostvars[cache_host]['global_cache'] + [item]}}"
     loop: "{{ peers }}"
     delegate_to: "{{ cache_host }}"
     delegate_facts: yes
     when:
      - inventory_hostname == 'host_b'

   - name: show global_cache after adding host_b peers
     debug: var=hostvars[cache_host]['global_cache']
     run_once: yes

   - name: add local peers to global cache
     set_fact:
       global_cache: "{{ hostvars[cache_host]['global_cache'] + [item] }}"
     loop: "{{ peers }}"
     delegate_to: "{{ cache_host }}"
     delegate_facts: yes
     when:
      - inventory_hostname == 'host_c'

   - name: show global_cache after adding host_c peers
     debug: var=hostvars[cache_host]['global_cache']
     run_once: yes
```

##### EXPECTED RESULTS
After executing all tasks:
`hostvars[cache_host]['global_cache'] == [a,b,c,d,e,f]`

##### ACTUAL RESULTS
`hostvars[cache_host]['global_cache'] == [b,d,f]`

```
$ ansible-playbook -i inventory play.yml

PLAY [all] *************************************************************************************************************************************************************************

TASK [set cache_host] **************************************************************************************************************************************************************
ok: [host_a]

TASK [set play-global cache] *******************************************************************************************************************************************************
ok: [host_a]
skipping: [host_b]
skipping: [host_c]

TASK [show global_cache before test] ***********************************************************************************************************************************************
ok: [host_a] => {
    "hostvars[cache_host]['global_cache']": []
}
ok: [host_b] => {
    "hostvars[cache_host]['global_cache']": []
}
ok: [host_c] => {
    "hostvars[cache_host]['global_cache']": []
}

TASK [add local peers to global cache] *********************************************************************************************************************************************
ok: [host_a -> host_a] => (item=a)
ok: [host_a -> host_a] => (item=b)
skipping: [host_b] => (item=c)
skipping: [host_b] => (item=d)
skipping: [host_c] => (item=e)
skipping: [host_c] => (item=f)

TASK [show global_cache after adding host_a peers] *********************************************************************************************************************************
ok: [host_a] => {
    "hostvars[cache_host]['global_cache']": [
        "b"
    ]
}

TASK [add local peers to global cache] *********************************************************************************************************************************************
skipping: [host_a] => (item=a)
skipping: [host_a] => (item=b)
ok: [host_b -> host_a] => (item=c)
ok: [host_b -> host_a] => (item=d)
skipping: [host_c] => (item=e)
skipping: [host_c] => (item=f)

TASK [show global_cache after adding host_b peers] *********************************************************************************************************************************
ok: [host_a] => {
    "hostvars[cache_host]['global_cache']": [
        "b",
        "d"
    ]
}

TASK [add local peers to global cache] *********************************************************************************************************************************************
skipping: [host_a] => (item=a)
skipping: [host_a] => (item=b)
skipping: [host_b] => (item=c)
skipping: [host_b] => (item=d)
ok: [host_c -> host_a] => (item=e)
ok: [host_c -> host_a] => (item=f)

TASK [show global_cache after adding host_c peers] *********************************************************************************************************************************
ok: [host_a] => {
    "hostvars[cache_host]['global_cache']": [
        "b",
        "d",
        "f"
    ]
}

PLAY RECAP *************************************************************************************************************************************************************************
host_a                     : ok=7    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
host_b                     : ok=2    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
host_c                     : ok=2    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
```
