### ISSUE TITLE
[ec2_asg] fails before replacing instances launch config

### ISSUE THREAD

**Issue by blastik** [ansible/ansible#62931]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ec2_asg`

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /Users/whatever/Documents/Repos/whatever/ansible/ansible.cfg
  configured module search path = ['/Users/whatever/Documents/Repos/whatever/ansible/library']
  ansible python module location = /Users/whatever/Documents/Repos/whatever/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/whatever/Documents/Repos/whatever/venv/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```
DEFAULT_FILTER_PLUGIN_PATH(/Users/whatever/Documents/Repos/whatever/ansible/ansible.cfg) = ['/Users/whatever/Documents/Repos/whatever/ansible/filter_plugins']
DEFAULT_MODULE_PATH(/Users/whatever/Documents/Repos/whatever/ansible/ansible.cfg) = ['/Users/whatever/Documents/Repos/whatever/ansible/library']
DEFAULT_ROLES_PATH(/Users/whatever/Documents/Repos/whatever/ansible/ansible.cfg) = ['/Users/whatever/Documents/Repos/whatever/ansible/roles']
DISPLAY_SKIPPED_HOSTS(/Users/whatever/Documents/Repos/whatever/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
macosx

##### STEPS TO REPRODUCE
- Create a new Launch Configuration and try to replace de ASG with this new one.
```
- name: add new launch configuration
  ec2_lc:
    profile: "{{ env }}"
    name: "JenkinsLaunchConfig_{{ timestamp_short }}"
    instance_profile_name: "{{ stackname }}_InstanceProfile"
    image_id: "{{ image_id }}"
    instance_type: "{{ ec2_instance_type }}"
    security_groups: ["{{ securitygroup }}"]
    user_data: |
      {{ ec2_userdata }}

- name: modify autoscalling group
  ec2_asg:
    profile: "{{ env }}"
    name: JenkinsASG
    min_size: 1
    max_size: 1
    desired_capacity: 1
    health_check_period: 120
    health_check_type: ELB
    launch_config_name: "JenkinsLaunchConfig_{{ timestamp_short }}"
    replace_all_instances: yes
```

##### EXPECTED RESULTS
Replaces de ASG with the new launch configuration also replacing all the instances.

##### ACTUAL RESULTS
The launch config is deployed corrrectly and also replaced in the ASG, however the task fails before replacing the instances.

```
TASK [jenkins-deploy : modify autoscalling group] ***************************************************************************************************************
task path: /Users/whatever/Documents/Repos/whatever/ansible/roles/jenkins-deploy/tasks/release-deploy.yml:54
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/Users/whatever/.ansible/tmp/ansible-tmp-1569679517.620229-238573336007269/AnsiballZ_ec2_asg.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/Users/whatever/.ansible/tmp/ansible-tmp-1569679517.620229-238573336007269/AnsiballZ_ec2_asg.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/whatever/.ansible/tmp/ansible-tmp-1569679517.620229-238573336007269/AnsiballZ_ec2_asg.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/whatever/.ansible/tmp/ansible-tmp-1569679517.620229-238573336007269/AnsiballZ_ec2_asg.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/Users/whatever/Documents/Repos/whatever/venv/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/Users/whatever/Documents/Repos/whatever/venv/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/var/folders/xg/x0dv30290935jdy3fyx_6kr5nzm1qc/T/ansible_ec2_asg_payload_ygvjx_ab/__main__.py\", line 1677, in <module>\n  File \"/var/folders/xg/x0dv30290935jdy3fyx_6kr5nzm1qc/T/ansible_ec2_asg_payload_ygvjx_ab/__main__.py\", line 1670, in main\n  File \"/var/folders/xg/x0dv30290935jdy3fyx_6kr5nzm1qc/T/ansible_ec2_asg_payload_ygvjx_ab/__main__.py\", line 1312, in replace\n  File \"/var/folders/xg/x0dv30290935jdy3fyx_6kr5nzm1qc/T/ansible_ec2_asg_payload_ygvjx_ab/__main__.py\", line 1385, in get_instances_by_launch_config\nKeyError: 'launch_config_name'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/amazon/ec2_asg.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @garethr @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@blastik, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by blastik** [comment]
been troubleshooting the module a bit and when i print `props` var i get:
```
{
  'healthy_instances': 1,
  'in_service_instances': 1,
  'unhealthy_instances': 0,
  'pending_instances': 0,
  'viable_instances': 1,
  'terminating_instances': 0,
  'instances': ['i-11111'],
  'auto_scaling_group_name': 'JenkinsASG',
  'auto_scaling_group_arn': 'arn:aws:autoscaling:eu-west-1:1111:autoScalingGroup:1111:autoScalingGroupName/JenkinsASG',
  'availability_zones': ['eu-west-1b', 'eu-west-1c', 'eu-west-1a'],
  'created_time': datetime.datetime(2019, 9, 27, 11, 24, 37, 642000, tzinfo = tzutc()),
  'instance_facts': {
    'i-03d0e831ded5a5921': {
      'health_status': 'Healthy',
      'lifecycle_state': 'InService'
    }
  },
  'load_balancers': [],
  'launch_config_name': 'JenkinsLaunchConfig_20190928164734',
  'tags': [{
    'ResourceId': 'JenkinsASG',
    'ResourceType': 'auto-scaling-group',
    'Key': 'Name',
    'Value': 'whatever',
    'PropagateAtLaunch': True
  }, {
    'ResourceId': 'JenkinsASG',
    'ResourceType': 'auto-scaling-group',
    'Key': 'aws:cloudformation:logical-id',
    'Value': 'JenkinsASG',
    'PropagateAtLaunch': True
  }, {
    'ResourceId': 'JenkinsASG',
    'ResourceType': 'auto-scaling-group',
    'Key': 'aws:cloudformation:stack-id',
    'Value': 'arn:aws:cloudformation:eu-west-1:1111:stack/JenkinsMotor/1111',
    'PropagateAtLaunch': True
  }, {
    'ResourceId': 'JenkinsASG',
    'ResourceType': 'auto-scaling-group',
    'Key': 'aws:cloudformation:stack-name',
    'Value': 'JenkinsMotor',
    'PropagateAtLaunch': True
  }, {
    'ResourceId': 'JenkinsASG',
    'ResourceType': 'auto-scaling-group',
    'Key': 'env',
    'Value': 'pro',
    'PropagateAtLaunch': True
  }, {
    'ResourceId': 'JenkinsASG',
    'ResourceType': 'auto-scaling-group',
    'Key': 'owner',
    'Value': 'motor',
    'PropagateAtLaunch': True
  }],
  'min_size': 1,
  'max_size': 1,
  'desired_capacity': 1,
  'default_cooldown': 300,
  'healthcheck_grace_period': 120,
  'healthcheck_type': 'ELB',
  'termination_policies': ['Default'],
  'target_group_arns': ['arn:aws:elasticloadbalancing:eu-west-1:1111:targetgroup/JenkinsEC2TargetGroup/1111'],
  'vpc_zone_identifier': 'subnet-111,subnet-111,subnet-111',
  'metrics_collection': [],
  'target_group_names': ['whatever']
}
```

so i believe that in here https://github.com/ansible/ansible/blob/ee91714eb2c4f65862a227f9ced9c7b656265a0f/lib/ansible/modules/cloud/amazon/ec2_asg.py#L1392 is expecting a Key that no longer exist for some reason ?

**Comment by blastik** [comment]
i think the problem is somewhere here
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L628-L638
because it falls inside the else and no `launch_config_name` is added to the dict `instance_facts`

**Comment by blastik** [comment]
but... dont really understand because in here
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L660-L661
the  `autoscaling_group.get('LaunchConfigurationName')` DO have the `LaunchConfigurationName` :(

**Comment by blastik** [comment]
closing since i redeployed the initial stack using cloudformation and then using those ansible task worked fine. mystery.

**Comment by blastik** [comment]
reopen since it happened again

**Comment by naxhh** [comment]
To sumarize this a bit, the LC is created using `ec2_lc` module.

These are the args used for `ec2_asg` module

```
{
    "ANSIBLE_MODULE_ARGS": {
        "profile": "pro",
        "name": "JenkinsASG",
        "min_size": 1,
        "max_size": 1,
        "desired_capacity": 1,
        "health_check_period": 120,
        "health_check_type": "ELB",
        "replace_all_instances": true,
        "wait_timeout": 600,
        "launch_config_name": "JenkinsLaunchConfig_20191001111800"
    }
}
```

In the `replace` function the `describe_autoscaling_groups` (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L1303)

returns the following:

```
   'LaunchConfigurationName':'JenkinsLaunchConfig_20191002093650',
   'Instances':[ 
      { 
         'InstanceId':'i-086a6392a181ddcc8',
         'AvailabilityZone':'eu-west-1b',
         'LifecycleState':'InService',
         'HealthStatus':'Healthy',
         'ProtectedFromScaleIn':False
      }
   ],
```

The instance doesn't contain the `LaunchConfigurationName` option
So when `get_properties` is invoked ( https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L1308)

the `instance_facts` generated doesn't contain the lc information

```
'instance_facts': {'i-086a6392a181ddcc8': {'health_status': 'Healthy', 'lifecycle_state': 'InService'}}
```

So when the `get_isntances_by_launch_config` is called (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L1318)

it fails because it assumes the `launch_config_name` will be inside the `instance_facts` for each instance (https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_asg.py#L1392)

So, for me, the main question is why `describe_autoscaling_groups` isn't returning the launch configuration information for the instances...
I can say that we have launched this playbook in the past and it worked, so at some point it worked correctly.

**Comment by mhenniges** [comment]
Having the same experience, I believe this is the same or similar underlying cause that led to https://github.com/ansible/ansible/pull/54692  - the short version of which is that if the instances  have been detached/re-attached to the ASG, or the LC that they were originally spawned with has be removed, then the name of the LaunchConfigurationName what was in effect when they spawned is not included in the instance dictionary. 

Seems as though guarding the appropriate tests within get_instances_by_launch_config with a 'try/except Keyerror' might be a reasonable fix.

**Comment by ansibot** [comment]
cc @jillr @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ShivaniYasa** [comment]
I am having the same issue, it creates the launch configuration and replaces the asg with new launch configuration but does not replace the instances when I use target_group_arns and throws the below error. It does not even spin new instances and removes the existing instance from target group. 

ERROR
"msg": "Waited too long for ELB instances to be healthy

Ansible Version - 2.9.4

```
- name: create launch configuration
  ec2_lc:
    name: "test-lc"
    image_id: "{{ ami-id }}"
    key_name: "{{ KEY_PAIR }}"
    security_groups: "{{ securitygroups }}"
    instance_type: "{{ INSTANCE_TYPE }}"
    instance_profile_name: "{{ INSTANCE_PROFILE }}"
    region: us-east-1
    volumes:
    - device_name: /dev/sda1
      volume_size: 8
      volume_type: gp2
      delete_on_termination: true
    user_data: "{{ lookup('template','userdata.j2', convert_data=False) |string }}"  
  register: launch_config
  
- name: create or update autoscaling group
  ec2_asg:
    name: "test-ipfe-asg-test"
    launch_config_name: "{{ launch_config.result.launch_configuration_name }}"
    vpc_zone_identifier: "{{ subnets }}"  
    health_check_period: 90
    health_check_type: ELB
    min_size: 1
    max_size: 3
    desired_capacity: 1
    region: us-east-1
    termination_policies: OldestInstance
    wait_for_instances: yes
    default_cooldown: 60
    replace_all_instances: yes
    target_group_arns: "{{ target_group.target_group_arn }}"
```

If I use load_balancers instead of target_group_arns the code works fine and replaces all the instances. I tried using Ansible Version - 2.8.4, its same when I use target_group_arns it doesn't replaces instances.
