### ISSUE TITLE
VMware: rename_vm works only with uuid

### ISSUE THREAD

**Issue by pgbidkar** [ansible/ansible#62954]
##### SUMMARY
rename_vm functionality works only with uuid. [rename_task](https://github.com/ansible/ansible/blob/a79f7e575a9576f804007ed979aa6c1aa731dd2d/lib/ansible/modules/cloud/vmware/vmware_guest.py#L2536) and name param is used for new_name. 

uuid is not obvious param for all users and name is used to get existing VM.

Can we introduce new argument 'new_name' use name param as well to rename the VM?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vmware/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vmware/Ansible/ansible/lib/ansible
  executable location = /home/vmware/Ansible/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### STEPS TO REPRODUCE
```
- name: Rename a virtual machine (requires the virtual machine's uuid)
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    uuid: "{{ vm_uuid }}"
    name: new_name
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS
name: should be existing vm name
new_name: for new name for VM

##### ACTUAL RESULTS
```
module takes 'name' argument for new_name and uuid to identify existing vm

```
