### ISSUE TITLE
os_server_action fails when 'wait' = ' no' 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#62958]
##### SUMMARY

When using ansible to stop an OpenStack VM, specifying wait=no occur a error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_server_action

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
no change
```

##### OS / ENVIRONMENT

ubuntu 16.04

##### STEPS TO REPRODUCE

1. create a openstack vm
2. stop a openstack vm by ansible.

playbook
```yaml
- name: Stop an OpenStack instance
  hosts: all
  gather_facts: no
  roles:
    - instance_action
  vars:
    instance_action: stop
```
```yaml
- name: Operate an OpenStack instance action
  os_server_action:
    action: "{{ instance_action }}"
    server: "{{ instance_id }}"
    wait: "{{ wait | default('yes') }}"
    verify: "{{ verify | default('yes') }}"
```
vars
```yaml
instance_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
verify: no
wait: no
```

##### EXPECTED RESULTS

stop a OpenStack vm 

##### ACTUAL RESULTS

fail to stop a OpenStack vm 

```paste below
ansible-playbook 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: stop_instance.yml *****************************************************************************************************************************************************************
1 plays in stop_instance.yml

PLAY [Stop an OpenStack instance] ***********************************************************************************************************************************************************
META: ran handlers

TASK [instance_action : Operate an OpenStack instance action] *******************************************************************************************************************************
task path: /home/ubuntu/work/os-integ/roles/instance_action/tasks/main.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<127.0.0.1> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530 `" && echo ansible-tmp-1569828606.07-4717533724530="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530 `" ) && sleep 0'
<127.0.0.1> Attempting python interpreter discovery
<127.0.0.1> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/openstack/os_server_action.py
<127.0.0.1> PUT /home/ubuntu/.ansible/tmp/ansible-local-71929SqXFy/tmpj96ZTW TO /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530/AnsiballZ_os_server_action.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530/ /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530/AnsiballZ_os_server_action.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530/AnsiballZ_os_server_action.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1569828606.07-4717533724530/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A
future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more
 information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [127.0.0.1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "msg": "New-style module did not handle its own exit"
}

PLAY RECAP **********************************************************************************************************************************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

There were the same error at the "start" action.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/openstack/os_server_action.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_server_action.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @gtema @juliakreger @mnaser @odyssey4me @omgjlk @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by csmart** [comment]
I can take a look at this.

**Comment by csmart** [comment]
Can confirm this. With `wait=no` the tasks fail, however the request actually does get successfully sent to OpenStack and actioned. Tested by sourcing openrc creds and running this playbook to toggle the state of all servers in a project:

```yaml
- name: Test os_server_action with wait disabled
  hosts: all
  gather_facts: no
  tasks:
  - name: Get server details
    os_server_facts:
  - name: Toggle state on servers
    os_server_action:
      action: "{{ 'start' if (item.status == 'SHUTOFF') else 'stop' }}"
      server: "{{ item.id }}"
      wait: "{{ wait | default('yes') }}"
      verify: "{{ verify | default('yes') }}"
    with_items: "{{ openstack_servers }}"
  vars:
    wait: no
```
