### ISSUE TITLE
LogicMonitor Module RPC deprecated

### ISSUE THREAD

**Issue by mitchhh22** [ansible/ansible#62972]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

logicmonitor

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
  tasks:
  - name: Deploy/verify LogicMonitor collectors
    become: yes
    logicmonitor:
      target: collector
      action: add
      company: '{{ company }}'
      user: '{{ user }}'
      password: '{{ password }}'

```

##### EXPECTED RESULTS

200 OK status

##### ACTUAL RESULTS

410 GONE status

```paste below

```

>  Note that LogicMonitor's RPC API has been deprecated - it will remain available until December 1, 2017

https://www.logicmonitor.com/support/rpc-api-developers-guide/overview/using-logicmonitors-rpc-api/
