### ISSUE TITLE
synchronize and with_items doesn't play well with --sudo

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#6298]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-1.6 (latest from devel)
##### Environment:

Tested on RHEL-6 and CentOS-6.
##### Summary:

It appears the `synchronize` module does not properly set `rsync_path` when called with more than one element in `with_items`.
##### Steps To Reproduce:
1. Create the following playbook

``` yaml

---
- hosts: all

  vars:
    output_dir: ~/ansible-testing

  tasks:
    - name: clean out the local test directory
      file: name={{output_dir|mandatory}} state=absent
      delegate_to: localhost
      sudo: false

    - name: create the local test directory
      file: name={{output_dir}} state=directory
      delegate_to: localhost
      sudo: false

    - name: cleanup old remote files and remember remote_dir
      file: state=absent path={{output_dir}}
      register: remote_dir

    - name: create local test files
      copy: dest={{output_dir}}/{{item}} mode=0644 content="hello world - {{item}}\n"
      sudo: false
      delegate_to: localhost
      with_items:
        - foo.txt
        - bar.txt
        - baz.txt

    - name: synchronize local files to remote using with_items (issue#5965)
      synchronize: src={{output_dir}}/{{item}} dest={{remote_dir.path}}/
      with_items:
        - foo.txt
        - bar.txt
        - baz.txt
```
1. Create an inventory file that provides a non-root `ansible_ssh_user`

``` ini
[local]
testhost ansible_ssh_host=example.com ansible_ssh_user=ec2-user
```
1. Run the play with `--sudo`

``` bash
$ ansible-playbook -i inventory test_synchronize.yml --sudo
```
##### Expected Results:

The play should run to completion without error.
##### Actual Results:

The play fails while attempting to synchronize the second item on the `with_items` list.  See output below:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [testhost]

TASK: [clean out the local test directory] ************************************ 
changed: [testhost]

TASK: [create the local test directory] *************************************** 
changed: [testhost]

TASK: [cleanup old remote files and remember remote_dir] ********************** 
changed: [testhost]

TASK: [create local test files] *********************************************** 
changed: [testhost] => (item=foo.txt)
changed: [testhost] => (item=bar.txt)
changed: [testhost] => (item=baz.txt)

TASK: [synchronize local files to remote using with_items (issue#5965)] ******* 
changed: [testhost] => (item=foo.txt)
failed: [testhost] => (item=bar.txt) => {"cmd": "rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' ~/ansible-testing/bar.txt ec2-user@example.com:/root/ansible-testing/", "failed": true, "item": "bar.txt", "rc": 12}
msg: Warning: Permanently added 'example.com' (RSA) to the list of known hosts.
rsync: ERROR: cannot stat destination "/root/ansible-testing/": Permission denied (13)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(554) [receiver=3.0.6]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]

failed: [testhost] => (item=baz.txt) => {"cmd": "rsync --delay-updates -FF --compress --timeout=10 --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' ~/ansible-testing/baz.txt ec2-user@example.com:/root/ansible-testing/", "failed": true, "item": "baz.txt", "rc": 12}
msg: Warning: Permanently added 'example.com' (RSA) to the list of known hosts.
rsync: ERROR: cannot stat destination "/root/ansible-testing/": Permission denied (13)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(554) [receiver=3.0.6]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/jlaska/test_5965.retry

testhost                   : ok=5    changed=4    unreachable=0    failed=1 
```
