### ISSUE TITLE
Issue with the NVM mount via ansible

### ISSUE THREAD

**Issue by kargold100** [ansible/ansible#62990]
##### SUMMARY
Issue with one of our components where in the file system says not available even though the device is available (via Ansible)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
task

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
```

##### CONFIGURATION

```paste below
none
```

##### OS / ENVIRONMENT
RHEL 7

##### STEPS TO REPRODUCE

```yaml
- set_fact:
    device: /dev/nvme2n1
  when: nvmedev.stat.exists == True
Then attach / mount the volumes as (e.g. vol-a) using 

- name: Attach the existing cold summaries volume if it is found
  ec2_vol:
    id: "{{ ec2_vol_data_cold_summaries.volumes[0].id }}"
    instance: "{{ ansible_ec2_instance_identity_document_instanceid }}"
    device_name: "/dev/xvdf"
    region: "{{ ansible_ec2_instance_identity_document_region }}"
  when: ec2_vol_data_cold_summaries.volumes|length > 0

mount:
    path: /var/cold_summaries
    src: "{{ device }}"
    fstype: ext4
    state: mounted
    opts: noatime
```

##### ACTUAL RESULTS

```paste below
We are having an issue with one of our components where in the file system says not available even though the device is available (via Ansible).
The instance is spinned up and via ansible we set the facts like 
- set_fact:
    device: /dev/nvme2n1
  when: nvmedev.stat.exists == True
Then attach / mount the volumes as (e.g. vol-a) using 

- name: Attach the existing cold summaries volume if it is found
  ec2_vol:
    id: "{{ ec2_vol_data_cold_summaries.volumes[0].id }}"
    instance: "{{ ansible_ec2_instance_identity_document_instanceid }}"
    device_name: "/dev/xvdf"
    region: "{{ ansible_ec2_instance_identity_document_region }}"
  when: ec2_vol_data_cold_summaries.volumes|length > 0

mount:
    path: /var/cold_summaries
    src: "{{ device }}"
    fstype: ext4
    state: mounted
    opts: noatime
We get the error as below:

TASK [indexer : Mount the volume] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error mounting /var/cold_summaries: mount: special device /dev/nvme2n1 does not exist\n"}


NAME        MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1     259:1    0   4G  0 disk
└─nvme0n1p1 259:2    0   4G  0 part /
nvme1n1     259:0    0  50G  0 disk /opt/
nvme2n1     259:3    0  16T  0 disk


and when I manually mount using mount devicename filesystemname (as below) it works fine.

mount /dev/nvme2n1 /var/cold_summaries
```
