### ISSUE TITLE
conditionals useless  with missing module (managing ansible_version)

### ISSUE THREAD

**Issue by alex-left** [ansible/ansible#63000]
##### SUMMARY

Ansible provides the variable "ansible_version" to give the playbook the chance to change the behaviour across ansible versions. One point that ansible differs between versions is the available modules. 

But ansible checks if modules exist before check the conditional. So raises an error when should'nt

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

!component
##### ANSIBLE VERSION

```paste below
2.7, 2.8
```

##### STEPS TO REPRODUCE

try to use an inexistent module (but correct with a later version)and put a conditional to check if the ansible version is correct:

```yaml
- name: task from future
  when: ansible_version.full is version("2.12", ">=")
  a_inexistent_module_from_future:
    something: foo
```
also you can use a task with a module from ansible 2.8 and try it to use with ansible 2.7, for example postgresql_query:
```yaml
    - name: get something
      when: ansible_version.full is version("2.8", ">=")
      postgresql_query:
        db: foo
        login_host: localhost
        login_user: foo
        login_password: password
        query: "select * from something"
```

##### EXPECTED RESULTS

Ansible should skip the task and continues with playbook

##### ACTUAL RESULTS

ansible stop with error:
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alex-left** [comment]
A workaround is to put the affected task in another file and later import it with the conditional:
    - import_tasks: task_from_future.yml
      when: ansible_version.full is version("2.12", ">=")

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/aws/core.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/aws/core.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alex-left** [comment]
extracting the affected task and puting it in another file to later import/include it and use the conditional in that import, doesn't work :(

I no find any way to use a missing module with some previous version without raises and error.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
it won't work with imports since those just pass on conditionals as inheritance to imported task, it WILL work with include as the conditional affects the include itself (imports cannot be made conditional).

**Comment by sivel** [comment]
In addition to using `include_tasks`, you can alternatively use `action` to get around this:

```
    - name: get something
      when: ansible_version.full is version("2.8", ">=")
      action:
        module: postgresql_query
        db: foo
```
