### ISSUE TITLE
Improve win_find Performance

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#63018]
##### SUMMARY

Currently, win_find can take a significant amount of time to iterate through large collections of directories.

For example, the DLL directories in Windows show a significant variance in execution time with relatively similar disk space utilization

DLL directory at 3GB of disk space and 20,000 directories can take 10-15 minutes to complete a scan with win_find

DLL directory at 4GB of disk space and 120,000 directories can take over 6 hours to complete with win_find

##### ISSUE TYPE
- Bug report

##### COMPONENT NAME

win_find.py

##### ADDITIONAL INFORMATION

Parameters:
```yaml
scan_dir_list:
  - path: 'C:\Windows\System32'
    scandir: true
    recurse: true
    pattern:
      - '*.com'
      - '*.exe'
      - '*.dll'
      - '*.ocx'
      - '*.sys'
```

Task:
```yaml
- name: Get full list of files from directory
  win_find:
    paths: "{{ item.path }}"
    get_checksum: true
    recurse: "{{ item.recurse | default('false') }}"
    patterns: "{{item.pattern | default(omit) }}"
    use_regex: "{{ item.use_regex | default(omit) }}"
    file_type: file
  with_items: "{{ scan_dir_list }}"
  register: find_file_list
  ignore_errors: true
```
