### ISSUE TITLE
gcp_compute_disk still does not work with snapshots

### ISSUE THREAD

**Issue by decklord** [ansible/ansible#63028]
##### SUMMARY
Creating a disk from a snapshot fails with gcp_compute_instance.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_compute_instance

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /Users/user/deployment2/ansible-playbooks/postcenter/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/.virtualenvs/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/user/.virtualenvs/ansible/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_FORKS(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = 15
DEFAULT_STDOUT_CALLBACK(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = yaml
HOST_KEY_CHECKING(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = auto_legacy_silent
INVENTORY_CACHE_ENABLED(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = /tmp/ansible-inventory-cache
INVENTORY_CACHE_TIMEOUT(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = 30
INVENTORY_ENABLED(/Users/user/Projects/deployment2/ansible-playbooks/postcenter/ansible.cfg) = ['gcp_compute', 'host_list', 'yaml', 'ini', 'script']
```

##### OS / ENVIRONMENT
OS X

##### STEPS TO REPRODUCE

```yaml
- name: Get target snapshot
  gcp_compute_snapshot_info:
      filters:
      - name = "{{ base_snapshot }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
  register: snapshot

- name: "Snapshot debug"
  debug:
    msg: "{{snapshot}}"

- name: Create base disk from disk snapshot
  gcp_compute_disk:
      name: "test_instance"
      source_snapshot: "{{ snapshot }}"
      size_gb: "{{snapshot.resources[0].diskSizeGb}}"
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: present
  register: disk_from_snapshot
```

##### EXPECTED RESULTS

The disk to be created from the snapshot

##### ACTUAL RESULTS

As stated in https://github.com/ansible/ansible/issues/50839 the disk created is not using snapshot. It's creating a blank disk that I cannot use to create an instance.
