### ISSUE TITLE
dnf module fails all packages on single failure

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#63020]
##### SUMMARY

When using the package module to remove multiple packages, if one of them has an invalid name, then the whole thing fails and does not proceed to remove the other packages.

This is not the expected/consistent behaviour as seen in yum/dnf. In yum/dnf you may run "dnf remove invalid valid1 valid2" and the valid1 and valid2 packages will be removed and the invalid package will be ignored.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnf

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```paste below
(no output from the command)
```

##### OS / ENVIRONMENT

Fedora 30

##### STEPS TO REPRODUCE

The command below tries to remove multiple packages as a list. The very first one (*.i686) is invalid and causes the whole command to fail, which is inconsistent with how yum/dnf work, which would ignore just that package and proceed to remove the rest.

```yaml
- name: Remove unused packages
  package:
    name:
     - "*.i686"
     - "rdma-core"
     - "alsa-firmware"
     - "alsa-tools-firmware"
     - "aic94xx-firmware"
     - "ivtv-firmware"
     - "python-backports"
     - "ppp"
     - "fprintd"
     - "fprintd-pam"
     - "mcelog"
     - "teamd"
     - "mingw*"
    autoremove: yes
    state: absent
```

##### EXPECTED RESULTS

All valid packages to be removed.

##### ACTUAL RESULTS

No packages are removed.

```paste below
FAILED! => {"changed": false, "failures": ["*.i686 - no package matched", "mingw* - no package matched"], "msg": ["Failed to install some of the specified packages"], "rc": 1, "results": []}
```

I read the documentation of the package/yum/dnf modules but I could not find any reference is this situation is a bug or a "feature".

Thank you.

*edit* - changed component module from `package` to `dnf`.
