### ISSUE TITLE
Allow remote_src and mode 'preserve' to work on Unarchive module.

### ISSUE THREAD

**Issue by gamuniz** [ansible/ansible#63067]
##### SUMMARY

Currently if remote_src: true and mode: preserve are set on the Unarchive module there is a traceback as mode is being passed as a string "preserve".

##### ISSUE TYPE
- Feature Idea
configure unarchive to use preserve by doing the conversion as we do currently for copy win_copy and others.

##### COMPONENT NAME

unarchive
##### ADDITIONAL INFORMATION

```
- name: unarchive test preserve
    unarchive:
      src: /tmp/ansible-tower-setup-bundle-3.5.1-1.el7.tar.gz
      dest: /home/testuser/
      owner: testuser
      group: testuser
      mode: 'preserve'
      remote_src: True

```
