### ISSUE TITLE
Standardized return values for package modules

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#63071]
##### SUMMARY

Please standardize return values of package modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

package
pkgng
apt
yum
pacman

##### ADDITIONAL INFORMATION

In writing cross-platform playbooks we ended up with hacky shell parsers as a replacement for native package modules, because it proved more feasible to extract predictable lists of changed packages this way.

It would be a nice feature if a package module returned formalized results of it's work as lists:

```yaml
installed_packages: []
removed_packages: []
reinstalled_packages: []
upgraded_packages: []
donwgraded_packages: []
```
So this info could be registered and used later in the playbook for hooks and conditions.
