### ISSUE TITLE
I think the inventory file in yaml format isn't terse enough

### ISSUE THREAD

**Issue by jkklee** [ansible/ansible#63076]
I think the yaml format inventory use redundant `all:` and `children:` entry which result more depth of indents.
for `all:`, I think we can make it as a implicit definition just as sample as the `ini` format;
for `children:`, I think the indents it'self can represent the relationship of group and children host/group allready.
Let's see the below tow contents for compare:
```
all:
  children:
    usa:
      children:
        southeast:
          children:
            atlanta:
              hosts:
                host1:
                host2:
            raleigh:
              hosts:
                host2:
                host3:
          vars:
            some_server: foo.southeast.example.com
            halon_system_timeout: 30
            self_destruct_countdown: 60
```
```
usa:
  southeast:
    atlanta:
      hosts:
        host1:
        host2:
    raleigh:
      hosts:
        host2:
        host3:
    vars:
      some_server: foo.southeast.example.com
      halon_system_timeout: 30
      self_destruct_countdown: 60
```
