### ISSUE TITLE
nios_host_record still makes changes when run in check mode

### ISSUE THREAD

**Issue by noziwatele** [ansible/ansible#63082]
##### SUMMARY
When running a playbook with _nios_host_record_ in --check mode, if a change to 'extattrs' is required by the task then changes are still made to data in Infoblox.

Other changes with nios_host_record, such as adding/removing a host do respect the --check (that is, no changes are made in check mode).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_host_record

##### ANSIBLE VERSION
```paste below
ansible 2.8.5
  config file = /Users/<****>/ansible.cfg
  configured module search path = ['/Users/<****>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/<****>/venv/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/<****>/venv/ansible/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:16:38) [Clang 10.0.0 (clang-1000.11.45.5)]
```

Also tested with ansible 2.10.0.dev0 and behaviour is the same.

##### CONFIGURATION
```paste below
DEFAULT_FILTER_PLUGIN_PATH(/Users/<****>/ansible.cfg) = ['/Users/<****>/plugins/filter
DEFAULT_GATHERING(/Users/<****>/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/Users/<****>/ansible.cfg) = ['/Users/<****>/inventory']
DEFAULT_LOG_PATH(/Users/<****>/ansible.cfg) = /Users/<****>/log/ansible.log
DEFAULT_ROLES_PATH(/Users/<****>/ansible.cfg) = ['/Users/<****>/roles']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = auto_silent
RETRY_FILES_ENABLED(/Users/<****>/ansible.cfg) = False
```

##### OS / ENVIRONMENT
localhost: MacOS 10.14.6
Infoblox: 8.4.2

##### STEPS TO REPRODUCE
There is a host record named 'testhost.example.com' already present in Infoblox, with no extensible attributes. Then the below task is executed with --check on the command line, as follows:

```
ansible-playbook --check ipam_update_host_record.yml
```

```yaml
---
- name: Update IPAM host record
  hosts: localhost
  connection: local
  
  tasks:
  - name: update the host record
    nios_host_record:
      view: internal
      name: testhost.example.com
      ipv4: 
        - address: 10.0.0.1
      extattrs: {'ansible_network_os': 'ios'}
      state: present
      provider: "{{ nios_provider }}"
```

##### EXPECTED RESULTS
Task shows 'changed', but data is not actually changed.

##### ACTUAL RESULTS
Data in Infoblox is actually changed.

If the play is run a second time with check mode, then result is 'ok' (i.e. no change required).

```paste below
ansible-playbook --check ipam_update_host_record.yml
Vault password:

PLAY [Update IPAM host record] *********************************************************************************************************************************************************************************

TASK [add a host record] ***************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/nios/nios_host_record.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nios/nios_host_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @danielmellado @ganeshrn @justjais @privateip @sganesh-infoblox @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by justjais** [comment]
@noziwatele Thanks for logging the issue, I tried to reproduce the scenario on Ansible `devel` and `2.8.5` as well but for me `check_mode` is working as expected and for each play run it's running and showing as `changed=1` and `no` actual change is made to nios appliance. 
Play used:
```
---
- hosts: localhost
  connection: local
  vars:
    nios_provider:
      host: test_nios
      username: user
      password: pass
  tasks:
    - name: Create Host record
      nios_host_record:
        name: lookup_host_19.ansible.com
        ipv4addrs:
          - ipv4addr:  192.168.11.19
        comment: testing
        provider: "{{ nios_provider }}"
        state: present
```
run env:
```
ansible-playbook 2.8.5
  config file = /Users/sjaiswal/Sumit/bugs/nios/nios/ansible.cfg
  configured module search path = ['/Users/sjaiswal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sjaiswal/Sumit/ansible_fork/clone/ansible/lib/ansible
  executable location = /Users/sjaiswal/Sumit/ansible_fork/clone/ansible/bin/ansible-playbook
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
Using /Users/sjaiswal/Sumit/bugs/nios/nios/ansible.cfg as config file
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/nios/nios_host_record.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nios/nios_host_record.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by noziwatele** [comment]
Hi @justjais,
Sorry for the slow response. I have just tested this again today on ansible `2.9.7`, and have found that it is only under certain circumstances that `check_mode` is not working as expected, as follows:

The host record already exists in Infoblox. I want to add an extensible attribute to the host record. (the extensible attribute that I am adding is already defined globally in my Infoblox system)

When I run this in `check_mode`, the extattr is added to the host record in Infoblox.

```
---
- hosts: localhost
  connection: local
  vars:
    nios_provider:
      host: test_nios
      username: user
      password: pass
  tasks:
    - name: Add Extattrs to Host record
      nios_host_record:
        # this host record already exists
        name: lookup_host_19.ansible.com
        ipv4addrs:
          - ipv4addr:  192.168.11.19
        comment: testing
        extattrs: {'attribute_name': 'value'}
        provider: "{{ nios_provider }}"
        state: present
```

I haven't tried all other types of changes, but your test case above (creating a new record), and removing a record, both worked properly with `check_mode`, i.e. no change was made.

Cheers!
