### ISSUE TITLE
ios_banner: unneeded change when multiple banners are configured in IOS 12.x

### ISSUE THREAD

**Issue by kalimsshar** [ansible/ansible#63091]
##### SUMMARY
When multiple banners are present in a configuration and if the device does not support the "show banner" command, ios_banner incorrectly detects a change is needed in all banners but the last.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_banner

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kalimsshar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kalimsshar/dev/ansible/ansible/lib/ansible
  executable location = /home/kalimsshar/dev/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION
N/A (no output from "ansible-config dump --only-changed")

##### OS / ENVIRONMENT
Tested on multiple Cisco devices (switches and routers) using IOS 12.x with ansible running on Centos 7.7.1908

##### STEPS TO REPRODUCE
Create a playbook as follow, using the same banners that the ones on the Cisco device.

```yaml
---
- hosts: Switch1
  gather_facts: no

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios

  tasks:
  - name: "set login banner"
    ios_banner:
      banner: login
      text: |
        *********************************************
        *                                           *
        *    Actual banner configured on device     *
        *                                           *
        *********************************************
      state: present

  - name: "set exec banner"
    ios_banner:
      banner: exec
      text: |
        *********************************************
        *                                           *
        *    Actual banner configured on device     *
        *                                           *
        *********************************************
      state: present
```

##### EXPECTED RESULTS

Expected for ios_banner to detect no change is needed.

```
$ ansible-playbook -k -i hosts.ini banner.yml 
SSH password: 

TASK [set login banner] **********************************************************************************************************************************************************************************************
ok: [Switch1]

TASK [set exec banner] ***********************************************************************************************************************************************************************************************
ok: [Switch1]

PLAY RECAP ***********************************************************************************************************************************************************************************************************
Switch1                     : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS

```
$ ansible-playbook -k -i hosts.ini banner.yml 
SSH password: 

TASK [set login banner] **********************************************************************************************************************************************************************************************
ok: [Switch1]

TASK [set exec banner] ***********************************************************************************************************************************************************************************************
changed: [Switch1]

PLAY RECAP ***********************************************************************************************************************************************************************************************************
Switch1                     : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
