### ISSUE TITLE
vmware_tag_manager change single cardinal tag 

### ISSUE THREAD

**Issue by taschaal** [ansible/ansible#63108]
##### SUMMARY

Want to be able to change the value of a single cardinal tag category

Example:

I have a tag category called environment that allows one and only one of the following tags (DEV, PROD, UAT)

I have a vm tagged "PROD",  but I want to change it to "DEV" with the vm_tag_manager module.  Right now if I try to do it the module throws an error. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

 vm_tag_manager 

##### ADDITIONAL INFORMATION

```yaml

- name: set tag  
      vmware_tag_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        tag_names:
          - Environment:DEV
        object_name: "{{ vm_name }}"
        object_type: VirtualMachine
        state: present
```

default_message='Tagging cardinality violation'
