### ISSUE TITLE
Apt Module hangs forever when running on Kali Linux

### ISSUE THREAD

**Issue by KyleEvers** [ansible/ansible#63134]
##### SUMMARY
  
  The apt module has inconsistent behavior from the shell commands. When running ansible apt module to upgrade Kali Linux the command hangs forever. This error appears to stem from a GUI prompt expecting input. However if the shell apt-get upgrade is run with
  ```yaml
  environment:
    DEBIAN_FRONTEND: noninteractive
  ```
  the apt-get upgrade completes successfully. Based on the [code for the apt module the DEBIAN_FRONTEND environment](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py#L1043) variable should be set by default, but does not appear to be taking effect for this distribution for some reason.

  ##### ISSUE TYPE
  - Bug Report

  ##### COMPONENT NAME
  
  apt

  ##### ANSIBLE VERSION
  
  ```
  ansible 2.8.0
  ```

  ##### CONFIGURATION
  
  ```
  No changes
  ```

  ##### OS / ENVIRONMENT
  
  OS: Kali Linux that can be found in the [AWS AMI Marketplace Here](https://aws.amazon.com/marketplace/pp/Kali-Linux-Kali-Linux/B01M26MMTT)

  I am deploying this image in AWS, but for troubleshooting purposes I ran the playbook on a local copy of Kali and received the same outcome.

  ##### STEPS TO REPRODUCE
  

  
  ```yaml
  - name: apt-get update/apt-get upgrade for Kali
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution_release == "kali-rolling"
  ```
  
  Similarly the following command behavior is the same
  ```yaml
  - name: Update all packages to the latest version:
    apt:
      upgrade: yes
  ```

  

  ##### EXPECTED RESULTS
  
  I expect the apt image to be successfully upgraded as it is with the below commands:
  ```yaml
  - name: apt-get update
    shell: apt-get update
    when: ansible_distribution_release == "kali-rolling"

  - name: Upgrade with noninteractive frontend to handle GUI prompts
    shell: apt-get -yy upgrade
    when: ansible_distribution_release == "kali-rolling"
    environment:
      DEBIAN_FRONTEND: noninteractive
  ```

  ##### ACTUAL RESULTS
  

  
  ```
     The playbook hangs forever and never completes
  ```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
I cannot reproduce with the information given, you seem to have a package that prompts even when apt is instructed not to, w/o more information there is not much what we can do.

**Comment by KyleEvers** [comment]
To be clear only the ansible apt module returns a hanging result, while shell apt works fine. The expected behavior is that 
```json
- name: apt-get update
  shell: apt-get update
  when: ansible_distribution_release == "kali-rolling"

- name: Upgrade with noninteractive frontend to handle GUI prompts
  shell: apt-get -yy upgrade
  when: ansible_distribution_release == "kali-rolling"
  environment:
    DEBIAN_FRONTEND: noninteractive
```
and 
```json
 - name: apt-get update/apt-get upgrade for Kali
  apt:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_distribution_release == "kali-rolling"
```
return the same result. However the apt module hangs meaning the default ```DEBIAN_FRONTEND: noninteractive``` is not being set/or honored by the host. 

This is on the base version of Kali with no additional packages. I have verified this behavior running a remote playbook in AWS and locally. If you need more information please clarify what you are looking for.

**Comment by lod** [comment]
Observed this fault in Kali 2019.2
Did not observe the fault in Kali 2020.1 (latest)

Note that the AWS Marketplace Kali 2019 image now has python3-apt pre-installed so doesn't display the issue.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Amaelh** [comment]
Hello, 

I observe the same problem with Kali 2021.1 created with Vagrant. My provisionning is done by Ansible. During this process, an apt post-installation step of package "grub-pc" is launching a whiptail command about a problem. This whiptail should never be launched when using ansible.

```
root       54697   54683  0 08:06 pts/2    00:00:00 /usr/bin/dpkg --status-fd 16 --configure --pending
root       54698   54697  0 08:06 pts/2    00:00:00 /usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/grub-pc.postinst configure 2.04-12kali1
root       54709   54698  0 08:06 pts/2    00:00:00 /bin/bash /var/lib/dpkg/info/grub-pc.postinst configure 2.04-12kali1
root       54910   54698  0 08:06 pts/2    00:00:00 whiptail --backtitle Package configuration --title Configuring grub-pc --output-fd 11 --nocancel --msgbox The GRUB boot loader was previously installed to a disk that is no  longer present, or whose unique identifier has changed for some reason.  It is important to make sure that the installed GRUB core image stays in sync with GRUB modules and grub.cfg. Please check again to make sure  that GRUB is written to the appropriate boot devices.  If you're unsure which drive is designated as boot drive by your BIOS,  it is often a good idea to install GRUB to all of them.  Note: it is possible to install GRUB to partition boot records as well,  and some appropriate partitions are offered here. However, this forces  GRUB to use the blocklist mechanism, which makes it less reliable, and  therefore is not recommended. 19 77
```

**Comment by Amaelh** [comment]
While the initial problem is generated during a "apt upgrade", Ansible seems to catch it and return an error. My problem is due to my "rescue" section where I manually launched "apt clean && apt autoclean && apt install -f && apt upgrade" without setting DEBIAN_FRONTEND. 

So my problem is not an Ansible bug, but a personal coding problem :)                                                                                            

Ansible block :
```
- name : update
  block:
    - name: Upgrade all packages to their latest version
      apt:
        name: "*"
        update_cache: yes
        cache_valid_time: 3600
        state: latest
      register: apt_action
      retries: 10
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

  rescue:
    - name: apt repair
      shell: apt clean && apt autoclean && apt install -f && apt upgrade
      become: yes
```

You can safely ignore my message from yesterday :)
