### ISSUE TITLE
"Already configured" Error with ios_config using match: strict

### ISSUE THREAD

**Issue by rayterrill** [ansible/ansible#63167]
##### SUMMARY

I'm receiving an error when using the ios_config module and attempting to apply a config to a Cisco 3650 switch interface using the "match: strict" functionality.

I can clear the port, then apply the config one time. I remove one line from my lines: section to test the ability to respond to a line missing (hoping it would update the config), but instead I receive an error:

```
fatal: [myswitch.mydomain.com]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-local-201049_h88nbw/ansible-tmp-1570246058.4232726-143800085095187/AnsiballZ_ios_config.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/username/.ansible/tmp/ansible-local-201049_h88nbw/ansible-tmp-1570246058.4232726-143800085095187/AnsiballZ_ios_config.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-local-201049_h88nbw/ansible-tmp-1570246058.4232726-143800085095187/AnsiballZ_ios_config.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ios_config_payload_486uub/__main__.py\", line 569, in <module>\n  File \"/tmp/ansible_ios_config_payload_486uub/__main__.py\", line 500, in main\n  File \"/tmp/ansible_ios_config_payload_486uub/__main__.py\", line 364, in edit_config_or_macro\n  File \"/tmp/ansible_ios_config_payload_486uub/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 186, in __rpc__\nansible.module_utils.connection.ConnectionError: auto qos trust\r\nAutoQoS Error: AutoQoS already configured\r\n\r\nMYSWITCH(config-if)#\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
Cisco IOS XE Software, Version 16.06.04a
Cisco IOS Software [Everest], Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 16.6.4a, RELEASE SOFTWARE (fc3)
```

##### STEPS TO REPRODUCE

1. Clear port config
```
config t
default int g1/0/6
```
2. Apply config with ansible.
3. Remove a line (for example, remove the description line)
4. Re-apply the ansible config results in an error

```yaml
---
- name: "Test Configuring Interfaces"
  hosts: cisco_ios
  gather_facts: no

  tasks:
  - name: configure interface settings
    ios_config:
      parents:
        - interface GigabitEthernet1/0/6
      lines:
        - switchport access vlan 99
        - switchport mode access
        - ip arp inspection limit rate 100
        - load-interval 30
        - ipv6 nd raguard attach-policy HOST_POLICY
        - trust device cisco-phone
        - storm-control broadcast level 20.00
        - storm-control unicast level 87.00 65.00
        - auto qos trust
        - macro description AccessEdgeQoS | AccessEdgeQoS
        - spanning-tree portfast
        - spanning-tree guard root
        - service-policy input AutoQos-4.0-Trust-Cos-Input-Policy
        - service-policy output AutoQos-4.0-Output-Policy
        - ip dhcp snooping limit rate 100
      save_when: modified
      match: strict
```

##### EXPECTED RESULTS

I'd expect it to replace the config with the specific config.

##### ACTUAL RESULTS

```paste below
username@mymachine:~/cisco$ ansible-playbook -vvvv configureinterface_withiosconfig.yml --ask-vault-pass
ansible-playbook 2.8.5
  config file = /home/username/cisco/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Using /home/username/cisco/ansible.cfg as config file
Vault password: 
setting up inventory plugins
host_list declined parsing /home/username/cisco/inventory as it did not pass it's verify_file() method
script declined parsing /home/username/cisco/inventory as it did not pass it's verify_file() method
auto declined parsing /home/username/cisco/inventory as it did not pass it's verify_file() method
Parsed /home/username/cisco/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.6/dist-packages/ansible/plugins/callback/default.py

PLAYBOOK: configureinterface_withiosconfig.yml ****************************************************************************************
Positional arguments: configureinterface_withiosconfig.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/username/cisco/inventory',)
ask_vault_pass: True
forks: 5
1 plays in configureinterface_withiosconfig.yml

PLAY [Test Configuring Interfaces] ****************************************************************************************************
META: ran handlers
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x7ff41655ab70> for vault_id=default

TASK [configure interface settings] ***************************************************************************************************
task path: /home/username/cisco/configureinterface_withiosconfig.yml:7
<myswitch.mydomain.com> attempting to start connection
<myswitch.mydomain.com> using connection plugin network_cli
<myswitch.mydomain.com> local domain socket does not exist, starting it
<myswitch.mydomain.com> control socket path is /home/username/.ansible/pc/ae68ed0ceb
<myswitch.mydomain.com> <myswitch.mydomain.com> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: mysshuser on PORT 22 TO myswitch.mydomain.com
<myswitch.mydomain.com> connection to remote device started successfully
<myswitch.mydomain.com> local domain socket listeners started successfully
<myswitch.mydomain.com> loaded cliconf plugin for network_os ios
<myswitch.mydomain.com> ssh connection done, setting terminal
<myswitch.mydomain.com> loaded terminal plugin for network_os ios
<myswitch.mydomain.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<myswitch.mydomain.com> firing event: on_open_shell()
<myswitch.mydomain.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<myswitch.mydomain.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<myswitch.mydomain.com> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<myswitch.mydomain.com> ssh connection has completed successfully
<myswitch.mydomain.com> 
<myswitch.mydomain.com> local domain socket path is /home/username/.ansible/pc/ae68ed0ceb
<myswitch.mydomain.com> ESTABLISH LOCAL CONNECTION FOR USER: username
<myswitch.mydomain.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279 `" && echo ansible-tmp-1570312175.4968529-258389958436279="` echo /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279 `" ) && sleep 0'
<myswitch.mydomain.com> Attempting python interpreter discovery
<myswitch.mydomain.com> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<myswitch.mydomain.com> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/network/ios/ios_config.py
<myswitch.mydomain.com> PUT /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/tmpgbhhr5y9 TO /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py
<myswitch.mydomain.com> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/ /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py && sleep 0'
<myswitch.mydomain.com> EXEC /bin/sh -c '/usr/bin/python /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py && sleep 0'
<myswitch.mydomain.com> EXEC /bin/sh -c 'rm -f -r /home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py", line 114, in <module>
    _ansiballz_main()
  File "/home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ios_config_payload_AXRlrS/__main__.py", line 569, in <module>
  File "/tmp/ansible_ios_config_payload_AXRlrS/__main__.py", line 500, in main
  File "/tmp/ansible_ios_config_payload_AXRlrS/__main__.py", line 364, in edit_config_or_macro
  File "/tmp/ansible_ios_config_payload_AXRlrS/ansible_ios_config_payload.zip/ansible/module_utils/connection.py", line 186, in __rpc__
ansible.module_utils.connection.ConnectionError: auto qos trust
AutoQoS Error: AutoQoS already configured

H9337ACC01(config-if)#

[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host myswitch.mydomain.com should use /usr/bin/python3, but is using
 /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered
 platform python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more 
information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
fatal: [myswitch.mydomain.com]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/username/.ansible/tmp/ansible-local-21311kc08fjeh/ansible-tmp-1570312175.4968529-258389958436279/AnsiballZ_ios_config.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ios_config_payload_AXRlrS/__main__.py\", line 569, in <module>\n  File \"/tmp/ansible_ios_config_payload_AXRlrS/__main__.py\", line 500, in main\n  File \"/tmp/ansible_ios_config_payload_AXRlrS/__main__.py\", line 364, in edit_config_or_macro\n  File \"/tmp/ansible_ios_config_payload_AXRlrS/ansible_ios_config_payload.zip/ansible/module_utils/connection.py\", line 186, in __rpc__\nansible.module_utils.connection.ConnectionError: auto qos trust\r\nAutoQoS Error: AutoQoS already configured\r\n\r\nH9337ACC01(config-if)#\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ****************************************************************************************************************************
myswitch.mydomain.com : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/ios/ios_config.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @justjais @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@rayterrill, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rayterrill** [comment]
Potential workaround - force clearing of the config prior to laying down new config, replace entire block:
```
---
- name: "Test Configuring Interfaces"
  hosts: cisco_ios
  gather_facts: no

  tasks:
  - name: configure interface settings
    ios_config:
      parents:
        - interface GigabitEthernet1/0/6
      lines:
        - description test interface
        - switchport access vlan 99
        - switchport mode access
        - ip arp inspection limit rate 100
        - load-interval 30
        - ipv6 nd raguard attach-policy HOST_POLICY
        - trust device cisco-phone
        - storm-control broadcast level 20.00
        - storm-control unicast level 87.00 65.00
        - auto qos trust
        - macro description AccessEdgeQoS | AccessEdgeQoS
        - spanning-tree portfast
        - spanning-tree guard root
        - service-policy input AutoQos-4.0-Trust-Cos-Input-Policy
        - service-policy output AutoQos-4.0-Output-Policy
        - ip dhcp snooping limit rate 100
      save_when: modified
      match: strict
      replace: block
      before: default interface GigabitEthernet1/0/6
```
