### ISSUE TITLE
vcenter_folder is slow an creates 234 api request

### ISSUE THREAD

**Issue by yvespp** [ansible/ansible#63173]
##### SUMMARY
vcenter_folder creates 234 vsphere api requests and takes 4 to 5 seconds to run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vcenter_folder

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /rancher/ansible/ansible.cfg
  configured module search path = ['/home/dlw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/rancher/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/rancher/ansible/ansible.cfg) = True
ANY_ERRORS_FATAL(/rancher/ansible/ansible.cfg) = True
CONDITIONAL_BARE_VARS(/rancher/ansible/ansible.cfg) = False
DEFAULT_CALLBACK_WHITELIST(/rancher/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/rancher/ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/rancher/ansible/ansible.cfg) = smart
DEFAULT_LOAD_CALLBACK_PLUGINS(/rancher/ansible/ansible.cfg) = False
DEFAULT_ROLES_PATH(/rancher/ansible/ansible.cfg) = ['/rancher/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/rancher/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/rancher/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/rancher/ansible/ansible.cfg) = /usr/bin/python
```

##### OS / ENVIRONMENT

* vSphere 6.7u2

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - add_host:
        name: create-test
        groups: mycorp_lab

- hosts: create-test
  gather_facts: no
  vars:
    vcenter_base_folder: "kubernetes"
    vcenter_sub_folder: "create-test"
    vm_name: "create-test"
  tasks:
  - name: Create cluster VM folder {{ vcenter_sub_folder }}
    delegate_to: localhost
    vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ vcenter_datacenter }}"
      folder_name: "{{ vcenter_sub_folder }}"
      parent_folder: "{{ vcenter_base_folder }}"
      folder_type: vm
      state: present
    run_once: true
```

##### EXPECTED RESULTS

* No more then 10 api request are used
* Task takes less than on second to complete

##### ACTUAL RESULTS
* Creates 234 API requests. I can see this in the access log of nginx that proxies the vsphere api.
* Runs for 4 to 5 seconds.
```
dlw@80764e2b891e://rancher/ansible$ ansible-playbook -i inventories/base.yml tmp/create_test.yml

PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
Sunday 06 October 2019  11:55:03 +0200 (0:00:00.120)       0:00:00.120 ********
ok: [localhost]

TASK [add_host] *****************************************************************************************************************************************************************************************************************************
Sunday 06 October 2019  11:55:05 +0200 (0:00:01.870)       0:00:01.990 ********
changed: [localhost]

PLAY [create-test] **************************************************************************************************************************************************************************************************************************

TASK [Create cluster VM folder create-test] *************************************************************************************************************************************************************************************************
Sunday 06 October 2019  11:55:05 +0200 (0:00:00.053)       0:00:02.044 ********
ok: [create-test -> localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
create-test                : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Sunday 06 October 2019  11:55:10 +0200 (0:00:04.715)       0:00:06.759 ********
===============================================================================
Create cluster VM folder create-test ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.72s
Gathering Facts ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.87s
add_host ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
```
