### ISSUE TITLE
docker_container sets facts 

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#63172]
##### SUMMARY

docker_container sets facts, but should use "returns". ansible_facts is especially not helpful when looping over docker_container... only the last iteration would set as docker_container fact.

Facts should be remove (deprecate) in favor of returns

https://github.com/ansible/ansible/blob/a99af710fbfb768745b214f1a4de2f0dd5d40551/lib/ansible/modules/cloud/docker/docker_container.py#L2549

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
2.8, 2.9
```

##### CONFIGURATION

```paste below

DEFAULT_HOST_LIST(/home/resmo/Projects/resmo/home-lab/ansible.cfg) = [u'/home/resmo/Projects/resmo/home-lab/inventories/lab']
DEFAULT_REMOTE_USER(/home/resmo/Projects/resmo/home-lab/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/resmo/Projects/resmo/home-lab/ansible.cfg) = [u'/home/resmo/Projects/resmo/home-lab/roles_galaxy', u'/home/resmo/Projects/resmo/home-lab/roles']
```

##### OS / ENVIRONMENT

Debian 10

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: container present
      docker_container:
        name: busybox
        image: busybox
        state: present
    - assert:
        that:
          - docker_container is undefined
```

##### EXPECTED RESULTS

success

##### ACTUAL RESULTS

fails

```paste below
TASK [assert] *******************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "docker_container is undefined", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}

```
