### ISSUE TITLE
Suggestion nxos_vrf modules

### ISSUE THREAD

**Issue by tomicke** [ansible/ansible#63190]
##### SUMMARY
Hello!

Suggestions to nxos_vrf modules. 

Currently using 3 modules to create VRF, add AFI with EVPN route-targets and nxos_config to add IP route-targets. The nxos_vrf_af module only supports adding EVPN RTs and not IPv4/IPv6 RT needed for import/export and advertisements of prefix information.

Would it not be possible to:
-  add AFI and RT parameters(auto RTs for EVPN and IP) to nxos_vrf module to configure 
   everything when creating the VRF. Nxos_vrf_af module is still needed to add/remove AFI and 
   auto RT.

or

- add RT parameter for IP to nxos_vrf_af module to avoid using separate nxos_config 
  snippets to add this. The choices should be auto the same as for EVPN RT

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- nxos_vrf
- nxos_vrf_af

##### ADDITIONAL INFORMATION
If addning to nxos_vrf 
```
      nxos_vrf:
        afi: ipv4/ipv6
        route_target_both_auto: true
        route_target_both_auto_evpn: true
```

If adding to nxos_vrf_af

```
      nxos_vrf:
        route_target_both_auto: true
```

Running with Ansible 2.8.5
