### ISSUE TITLE
PostgreSQL user and db names should allow dots

### ISSUE THREAD

**Issue by raneq** [ansible/ansible#63204]
##### SUMMARY
Using postgresql modules, database (pending), users (fixed by #63565), ~~tables and probably others,~~ (see [comment](https://github.com/ansible/ansible/issues/63204#issuecomment-542686315)) can't contain dots, but should be able to, as escaped characters. Although it's not a good practice, it's supported and under certain circumstances some applications force you to create databases with dots inside (like Odoo) or user with dots (like LDAP), so Ansible gets very limiting here.

This is not a duplicate issue but a reopen of #22568

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* postgresql_user
* postgresql_db

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.2
  config file = None
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
(nothing)
```

##### OS / ENVIRONMENT

Debian 10 "Buster" running against localhost

##### STEPS TO REPRODUCE

Use this playbook in a Debian-like cleanable environment:
```yaml
# playbook.yml
---
- hosts: localhost
  tasks:
    - name: Install PostgreSQL
      become: yes
      apt:
        name:
          - postgresql
          - python3-psycopg2
          - python2-psycopg2
      tags:
        - user
        - db

    - name: PostgreSQL User
      become: yes
      become_user: postgres
      postgresql_user:
        name: first.last
      tags: user

    - name: PostgreSQL DB
      become: yes
      become_user: postgres
      postgresql_db:
        name: first.second
      tags: db
```
Then execute:
```
ansible-playbook playbook.yml --ask-become -vvv --tag db
ansible-playbook playbook.yml --ask-become -vvv --tag user
```

##### EXPECTED RESULTS

I expected Ansible to create escaped names, as PostgreSQL supports it.

##### ACTUAL RESULTS

**db**
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": null,
            "conn_limit": "",
            "db": "first.second",
...
            "state": "present",
            "target": "",
            "target_opts": "",
            "template": ""
        }
    },
    "msg": "PostgreSQL does not support database with more than 1 dots"
```

**user**
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
    ...
            "state": "present",
            "user": "first.last"
        }
    },
    "msg": "PostgreSQL does not support role with more than 1 dots"
```

---

Please, don't close automatically this issue as long as there's people asking for this and there's no human saying it won't happen for some reason. Thanks!
