### ISSUE TITLE
[RFE][file module] interpret numeric owner/group as uid/gid whether they're known to system or not

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#63224]
##### SUMMARY

File module currently expects string values of `owner` and `group` arguments, expects them to be usernames and if they're all numeric (which POSIX usernames unfortunately can be) and not present in the system, it then turns them to uid/gid. It would be quite clean for file module to intepret int-type values as uid/gid right away and set ownership to these right away (python's `os.chown`/`os.lchown` accept only numeric uid/gid anyway).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

file_module

##### ADDITIONAL INFORMATION

```yaml
- name: test uid/gid setting
  hosts: localhost
  gather_facts: False
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: create file with UID/GID not present on the system
      file:
        path: /tmp/uid_gid_test
        owner: 12321
        group: 32123
        state: touch
        mode: 0640
```
Actual result:
```
$ ansible-playbook playbooks/uidgid.yml | grep WARNING
 [WARNING]: The value 12321 (type int) in a string field was converted to '12321' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
 [WARNING]: The value 32123 (type int) in a string field was converted to '32123' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
```
Expected result: no warning, UID and GID are used directly

Note: when such an all-numeric user is not present (which OSs routinely do, e.g. RHEL), the command actually works as expected:
```
$ ls -l /tmp/uid_gid_test 
-rw-r-----. 1 12321 32123 0 Oct  8 12:44 /tmp/uid_gid_test
```
and int → string → int conversions don't present security risk of one user impersonating other, but making this would be cleaner and allow to get rid of warnings in cases where files are copied before system is configured for LDAP/IPA/AD identities for for cases when those UIDs won't exist on the system at all (e.g. content for specific user on nfs server).
