### ISSUE TITLE
[ovirt_vm] Provide possibility to change Display keyboard-layout

### ISSUE THREAD

**Issue by knumskull** [ansible/ansible#63225]
##### SUMMARY

I would like to be able to set the keyboard layout for graphical console through ansible, as it's already possible via API and UI

https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/rest_api_guide/types#types-display
==> keyboard_layout

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ovirt_vm

##### ADDITIONAL INFORMATION

In countries like Germany, I would like to setup the keyboard layout native to german. This is possible by API and UI, but not using ansible.

```yaml
ovirt_vm:
  graphical_console:
    protocol:
      - vnc
    keyboard_layout: de_DE          
```
