### ISSUE TITLE
Deleting the deployment using k8s module stuck into terminating state

### ISSUE THREAD

**Issue by uditgaurav** [ansible/ansible#63258]
**COMPONENT NAME**
k8s

**SUMMARY**
Deleting the deployment stuck into terminating state using k8s module 

**OPENSHIFT VERSION**
```
[root@master-1554817485 deployers]# openshift version
openshift v3.10.127

```
**ANSIBLE VERSION**
```
[root@master-1554817485 deployers]# ansible --version
ansible 2.7.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```
**USING K8S MODULE**
```
    - name: Deleting {{ deployment }} -n {{app_ns}}
      k8s:
        state: absent 
        src:  {{ deployment }}
        namespace: {{ app_ns }}
```
**EXPECTED RESULT**
The deployment should be deleted successfully.

**ACTUAL RESULT**
Application get stuck into terminating state as shown:

```
[root@master-1554817485 deployers]# kubectl get po -n percona1
NAME                      READY     STATUS             RESTARTS   AGE
percona-fc7db745c-gdzv9   0/1       Terminating        0          11m

```
