### ISSUE TITLE
win_pester - Add the possibility to generate a test result xml file #4 

### ISSUE THREAD

**Issue by gvcgael** [ansible/ansible#63267]
##### SUMMARY
To be able to show the tests results in the CI, it would be great if we could output the tests results as an xml file :
https://github.com/pester/Pester/wiki/Showing-Test-Results-in-CI-%28TeamCity%2C-AppVeyor%2C-Azure-DevOps%29

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`win_pester`

##### ADDITIONAL INFORMATION
The usage of this module would match the following playbook : 

```yaml
- name: Get facts
  setup:

- name : Copy test file(s)
   win_copy:
     src: "{{ item }}"
     dest: "{{ remote_test_folder[0] }}"
   with_items: "{{local_test_files}}"

- name: Add Pester module
  action:
    module_name: "{{ 'win_psmodule' if ansible_powershell_version >= 5 else 'win_chocolatey' }}"
    name: Pester
    state: present

- name: Run the pester test present in a folder and check the Pester module version.
  win_pester:
    path: C:\Pester\
    version: 4.1.0
    output_file: C:\Pester\TestsResults.xml
    output_format: JUnitXML

- name: Store file into /tmp
  fetch:
    src: C:\Pester\TestsResults.xml
    dest: /tmp/TestsResults.xml
```
