### ISSUE TITLE
add support to postgresql_privs to use ALTER DEFAULT PRIVILEGES .. GRANT .. ON SCHEMAS TO ...

### ISSUE THREAD

**Issue by sahapasci** [ansible/ansible#63273]
##### SUMMARY
Since postgresql 10 [ALTER DEFAULT PRIVILEGES](https://www.postgresql.org/docs/10/sql-alterdefaultprivileges.html) supports the syntax below;

```
GRANT { USAGE | CREATE | ALL [ PRIVILEGES ] }
    ON SCHEMAS
    TO { [ GROUP ] role_name | PUBLIC } [, ...] [ WITH GRANT OPTION ]
```
Apparently,  postgresql_privs does not allow to use `SCHEMAS` keyword for `objs` property.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_privs

##### ADDITIONAL INFORMATION

A possible playbook could look like this:
```yaml
- name: set default privs
  become_user: postgres
  postgresql_privs:
    db: library
    type: default_privs
    target_roles: owner
    objs: SCHEMAS
    privs: USAGE
    roles: reader
```
Right now a playbook which looks like above throws the error below;

`{"changed": false, "msg": "Invalid Object set specified: frozenset({'SCHEMAS'})"}`
