### ISSUE TITLE
hash_behaviour merge not merging when dict in same file

### ISSUE THREAD

**Issue by BarbzYHOOL** [ansible/ansible#63292]
##### SUMMARY

hash_behaviour = merge works fine if you have dicts in different variable priority order (= in different files) but if one dict is defined twice in the same file, then it doesn't work and DOES NOT WARN YOU

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hash_behaviour

##### ANSIBLE VERSION

```paste below
2.8.5
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    dict:
      something:
        bar: false
      else:
        foo: true

    dict:
      something:
        foo: true

tasks:

    - debug:
        var: dict
```

##### EXPECTED RESULTS

I think it should work or at least warn the user. Of course, I think the only reason to put two dicts in the same file would be only for testing purpose, but still made me waste some time wondering what was wrong

Expected:
```
  dict:
    else:
      foo: true
    something:
      bar: false
      foo: true
```
##### ACTUAL RESULTS

```paste below
  dict:
    something:
      foo: true
```
