### ISSUE TITLE
eos_logging : Logging configuration fails on not passing 'dest'

### ISSUE THREAD

**Issue by GomathiselviS** [ansible/ansible#63290]
**SUMMARY**
```

While trying to configure 'logging facility local7'  on an Arista EOS switch, following commands are pushed into the switch:

['logging facility local7', 'logging None']

Expected is only 'logging facility local7'

Because of this the playbook is failing.

```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```

eos_logging.py

```

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gosriniv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gosriniv/ansible/lib/ansible
  executable location = /home/gosriniv/ansible/bin/ansible
  python version = 3.6.5 (default, Sep  4 2019, 12:23:33) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]
```

##### OS / ENVIRONMENT

```

"Arista vEOS"
```

##### STEPS TO REPRODUCE

```
---
- hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Set up logging facility
      eos_logging:
        facility: local7
      become: yes
      register: result

    - assert:
        that:
          - 'result.changed == true'
          - '"logging facility local7" in result.commands'


```

##### EXPECTED RESULTS

Expectation is that there should not be any failure

##### ACTUAL RESULTS

```
fatal: [10.8.38.31]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "data": "logging None\r\n% Invalid input\r\nfoo(config-s-ansibl)#",
    "invocation": {
        "module_args": {
            "aggregate": null,
            "auth_pass": null,
            "authorize": null,
            "dest": null,
            "facility": "local7",
            "host": null,
            "level": null,
            "name": null,
            "password": null,
            "port": null,
            "provider": null,
            "size": null,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "msg": "logging None\r\n% Invalid input\r\nfoo(config-s-ansibl)#"
}


```
