### ISSUE TITLE
vmware_guest_network: fails with a backtrace if static MAC starts with '00:50:56'

### ISSUE THREAD

**Issue by goneri** [ansible/ansible#63302]
##### SUMMARY

hi @pgbidkar and @Tomorrow9.

If I use the following task:

```yaml
  - name: add new network adapters to virtual machine
    vmware_guest_network:
      validate_certs: False
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: test_vm1
      networks:
        - name: "VM Network"
          state: new
          device_type: e1000e
          manual_mac: "00:50:56:58:59:60"
        - name: "VM Network"
          state: new
          device_type: vmxnet3
          manual_mac: "00:50:56:58:59:61"
    register: add_netadapter
```
I get the following error: [add_nic.txt](https://github.com/ansible/ansible/files/3709181/add_nic.txt)

If I remove the `manual_mac` keys, everything works fine.

I create the Fedora 30 VM with:

```yaml
  - name: Create VMs
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ dc1 }}"
      validate_certs: no
      folder: '/DC0/vm/F0'
      name: test_vm1
      state: poweredon
      guest_id: centos7_64Guest
      disk:
      - size_gb: 1
        type: thin
        datastore: '{{ ds2 }}'
      hardware:
        version: latest
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual
      cdrom:
        type: iso
        iso_path: "[{{ ds1 }}] fedora.iso"
      networks:
      - name: VM Network
```
I've tried several hardware.version/guest_id combination, without any difference. My lab is set-up as described here: https://docs.ansible.com/ansible/devel/dev_guide/platforms/vmware_guidelines.html

My vcenter set-up:

```shell
$ govc ls '/**/**/**'
/DC0/vm/F0/test_vm1
/DC0/network/VM Network
/DC0/host/DC0_C0/Resources
/DC0/host/DC0_C0/esxi1.test
/DC0/host/DC0_C0/esxi2.test
/DC0/datastore/LocalDS_0
/DC0/datastore/LocalDS_1
/DC0/datastore/datastore1 (1)
/DC0/datastore/datastore1
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_network

##### ANSIBLE VERSION

```paste below
devel
```
