### ISSUE TITLE
rds_instance: ca_certificate_identifier value not honored

### ISSUE THREAD

**Issue by Xaroth** [ansible/ansible#63324]
##### SUMMARY
When creating a rds_instance with the `ca_certificate_identifier` set to the new (soon-to-be default) value of 'rds-ca-2019', an instance is created with the old 'rds-ca-2015' 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`rds_instance`

##### ANSIBLE VERSION

```paste below
ansible 2.9.0rc1
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible/bin/ansible
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Affects both running via AWX/tower as well as running it manually.

##### STEPS TO REPRODUCE

```yaml
- name: create/update the RDS instance
  rds_instance:
    region: "{{ region }}"
    allocated_storage: "10"
    storage_encrypted: True
    allow_major_version_upgrade: "False"
    apply_immediately: "True"
    auto_minor_version_upgrade: "False"
    ca_certificate_identifier: "rds-ca-2019"
    backup_retention_period: "28"
    copy_tags_to_snapshot: True
    db_instance_class: "db.t3.small"
    db_instance_identifier: "test-postgres"
    db_subnet_group_name: "test-subnet"
    engine: "postgres"
    engine_version: "9.6.15"
    master_username: "root"
    master_user_password: "very_secure_password"
    port: "5432"
    publicly_accessible: False
    state: present
    storage_type: "gp2"
    wait: True
```

##### EXPECTED RESULTS

An instance with the rds-ca-2019 cert being created

##### ACTUAL RESULTS

```paste below
{
    "changed": true,
    "db_instance_identifier": "xxxxxxx",
    "db_instance_class": "db.t3.small",
    "engine": "postgres",
    "db_instance_status": "available",
    [ ....... ]
    "storage_encrypted": true,
    "ca_certificate_identifier": "rds-ca-2015",
    "domain_memberships": [],
    [ ....... ]
    "invocation": {
        "module_args": {
            "region": "us-east-1",
            "allocated_storage": 10,
            "max_allocated_storage": 25,
            "storage_encrypted": true,
            "allow_major_version_upgrade": false,
            "apply_immediately": false,
            "auto_minor_version_upgrade": true,
            "ca_certificate_identifier": "rds-ca-2019",
            "backup_retention_period": 28,
            "copy_tags_to_snapshot": true,
            "db_instance_class": "db.t3.small",
            [ ....... ]
        }
    },
    "_ansible_no_log": false
}
```
note how the `ca_certificate_identifier` differs between invocation and result.
