### ISSUE TITLE
map regex_replace produces duplicate entries

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#63329]
##### SUMMARY
When mapping a list with  a  map filter using `regex_replace` as mapper function,
the replacement string appears twice

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Filter

##### ANSIBLE VERSION

```2.8.2

```

##### STEPS TO REPRODUCE
Try following playbook

```yaml
- hosts: localhost
  connection: local
  tasks:
    - debug:
        msg: "{{ mylist | map('regex_replace', '(.*)', 'foo') | list }}"
      vars:
        mylist:
          - 1
          - 2
          - 3
```

##### EXPECTED RESULTS

```
ok: [localhost] => {
    "msg": [
        "foo",
        "foo",
        "foo"
    ]
}
```
   

##### ACTUAL RESULTS

```
ok: [localhost] => {
    "msg": [
        "foofoo",
        "foofoo",
        "foofoo"
    ]
}


```
