### ISSUE TITLE
Ddifferent Behaviour between python versions on loop directive

### ISSUE THREAD

**Issue by toninis** [ansible/ansible#63333]
##### SUMMARY
There is different behaviour with ansible loop directive when you iterate over a dictionary var between python2.7 and python3 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```paste below
ansible 2.8.4
  config file = /Users/antonisstamatiou/test/ansible.cfg
  configured module search path = [u'/Users/antonisstamatiou/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/antonisstamatiou/test/venv/lib/python2.7/site-packages/ansible
  executable location = venv/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```
```
ansible-playbook 2.8.4
  config file = /Users/antonisstamatiou/test/ansible.cfg
  configured module search path = ['/Users/antonisstamatiou/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### OS / ENVIRONMENT
macOS Mojave 10.14.6 
Installed with pip.

##### STEPS TO REPRODUCE
Run the ansible playbook below with the two different ansible installations (python2/python3)

```yaml
---
- hosts: localhost
  become: no
  gather_facts: false

  vars:
    test_dictionary:
      key1:
        foo: bar
        foo2: bar2
      key2:
        foo: bar1
        foo2: bar3
      key3:
        foo: bar2
        foo2: bar4


  tasks:

    - debug:
        msg: "{{ item }}"
      loop: "{{ test_dictionary.keys() }}"
```

##### EXPECTED RESULTS
python2.7 compiled ansible results
```
PLAY [localhost] ***************************************************************************************************************************************

TASK [debug] *******************************************************************************************************************************************
ok: [localhost] => (item=key3) => {
    "msg": "key3"
}
ok: [localhost] => (item=key2) => {
    "msg": "key2"
}
ok: [localhost] => (item=key1) => {
    "msg": "key1"
}
```

##### ACTUAL RESULTS
python3 compiled ansible results
```paste below
PLAY [localhost] ***************************************************************************************************************************************

TASK [debug] *******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: dict_keys(['key1', 'key2', 'key3']). Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```
