### ISSUE TITLE
firewalld offline option does nothing

### ISSUE THREAD

**Issue by CendioOssman** [ansible/ansible#63337]
##### SUMMARY
Using the `offline` flag to the `firewalld` has absolutely no effect on behaviour. Looking at the code I can not find any reference to the option beyond parsing it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION
```paste below
ansible 2.8.5
  config file = /local/home/ossman/devel/ansible/ansible.cfg
  configured module search path = ['/home/ossman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 13:36:35) [GCC 9.0.1 20190227 (Red Hat 9.0.1-0.8)]
```

##### CONFIGURATION
```
[defaults]
stdout_callback = yaml
```

##### OS / ENVIRONMENT
Target is a Red Hat Enterprise Linux 7 machine.
Ansible is run on a Fedora 30 machine.

##### STEPS TO REPRODUCE
```yaml
- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
- name: allow NRPE in firewall
  firewalld:
    service: nrpe
    permanent: yes
    immediate: yes
    offline: yes # firewalld might be disabled on some machines
    state: enabled
```

##### EXPECTED RESULTS
```
TASK [server : allow NRPE in firewall] ******************************************************************
ok: [host.example.com]
```

##### ACTUAL RESULTS
```
TASK [server : allow NRPE in firewall] ******************************************************************
fatal: [host.example.com]: FAILED! => changed=false 
  msg: firewall is not currently running, unable to perform immediate actions without a running firewall daemon
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/firewalld.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/firewalld.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tazerdev** [comment]
This seems to work, mostly, as expected for me on a standard RHEL7.7 system but I would prefer to see a change in behavior nonetheless:

```
# ansible --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

What I'm seeing is that if you set both `offline: true` and `immediate: true` the task fails if the firewalld daemon isn't running. If you set only `offline: true` then it behaves as expected (i.e., the files are modified directly and when firewalld is started all the rules are present.) This means the author needs to know the state of the firewall before running the playbook.

It feels as though the `firewalld` module should determine state before proceeding if both `immediate: true` and `offline: true` are set:

```
if systemctl is-active firewalld
then
    # apply immediately via D-BUS
elif
    # modify files directly
fi
```

My current use case is a playbook which can be run via kickstart in the `%post` section for initial configuration (which means firewalld can't and won't be running) but it can also be run after the system has booted to enforce configuration (which means firewalld probably is and should be running).

Currently I'm accomplishing this by removing the `immediate` option and restarting the firewall via a handler based on a flag (which isn't ideal because it kills existing TCP sessions):

```
- name: 'Restarting firewalld'
  systemd:
    name: firewalld
    state: restarted
    enabled: true
    daemon_reload: true
  when: not kickstarting|bool
  listen: "restart firewalld"
```

Of course this can be handled differently during kickstart but code-reuse is my goal.
