### ISSUE TITLE
Passing vars and defaults to the following include_role or to the environment from a previous include_role

### ISSUE THREAD

**Issue by tanis2000** [ansible/ansible#63334]
##### SUMMARY

I need to switch from the usual `roles:` construct to a list of `include_role` and for some reason the vars/defaults of the first role aren't being passed over to the next one and so on. I don't know if this is due to the loop or if it's just the standard behavior, but it's definitely an issue. You can find more details below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Roles

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/tanis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS / Linux

##### STEPS TO REPRODUCE

I'm trying to wrap all the roles of Kubespray in block/rescue blocks so I had to move from the usual `roles` includes like this:

```yaml
- hosts: kube-master[0]
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults}
    - { role: kubernetes-apps/rotate_tokens, tags: rotate_tokens, when: "secret_changed|default(false)" }
    - { role: win_nodes/kubernetes_patch, tags: ["master", "win_nodes"]}
```

to this:

```yaml
- hosts: kube-master[0]
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    roles:
      - name: "kubespray-defaults"
      - name: kubernetes-apps/rotate_tokens
        tags: rotate_tokens
        when: "secret_changed|default(false)"
      - name: win_nodes/kubernetes_patch
        tags: ["master", "win_nodes"]
      - name: "ems-notification"
        msg: kubespray-defaults, kubernetes-apps/rotate_tokens and win_nodes/kubernetes_patch completed
  environment: {{ proxy_env }}

  tasks:
  - include_tasks: roles/a4-roles/tasks/main.yml
    loop: "{{ roles }}"
```

with a4-roles/tasks/main.yml being:

```yaml
- name: a4-roles
  when: item.when | default(omit)
  block:
    - include_role:
        name: "{{ item.name }}"
        public: true
        apply:
          tags: >-
            {%- if item.tags is defined -%}
            "{{ item.tags }}"
            {%- else -%}
            ""
            {%- endif -%}
  rescue:
    - include_role:
        name: "ems-notification"
      vars:
        msg: an error has occurred
        host: "{{ inventory_hostname }}"
        result: "{{ ansible_failed_result.msg | trim | default(omit) }}"
        role: "{{ item.name }}"
        error: "true"
```

The problem is that the `kubespray-defaults` as well as other roles are setting some vars and defaults that are being used by the subsequent roles in the `roles` block.
When using `include_role` those vars and defaults are just lost. Is there any way to retain them and pass them on to the next role?

##### EXPECTED RESULTS

vars and defaults should be passed down to the next include_role

##### ACTUAL RESULTS

The vars and defaults aren't being passed down to the next role included

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/role`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
By default `include_role` is "private" meaning it does not expose its vars and defaults to the rest of the playbook.  See the `public` argument for `include_role` to change this behavior.

**Comment by tanis2000** [comment]
@sivel I am using `public: yes` in the role in the description, but it doesn't work.

**Comment by tanis2000** [comment]
@sivel I think I narrowed down the actual issue. It's the `proxy_env` variable that can't be passed to the `environment` as it's being set by one of the roles. So I'm wondering how it's even working when using the standard `roles:` construct. How's that possible is the role that is setting it is in the list of those to run?

**Comment by tanis2000** [comment]
If you want to reproduce this problem, just use the following:

`roles/a4-roles/tasks/main.yml
```yml
- name: a4-roles
  when: item.when | default(omit)
  block:
    - include_role:
        name: "{{ item.name }}"
        public: yes
  rescue:
    - debug:
        msg: "Do something within rescue"
  always:
    - debug:
        msg: "Include completed"
```

`roles/setup-vars/defaults/main.yml`
```yml
---
myvar: "this is my var content"
```

`roles/setup-vars/tasks/main.yml`
```yml
- name: setup-vars
  debug:
    msg: "Setting up vars"
```

`roles/show-vars/tasks/main.yml`
```yml
- name: show-vars
  debug:
    msg: "Value of myvar: {{ myvar }}"
```

`deploy.yml`
```yml
---

- hosts: all
  name: "With roles"
  roles:
    - { role: setup-vars }
    - { role: show-vars }
  environment: "{{ myvar }}"

- hosts: all
  name: "Without roles"
  vars:
    roles:
      - name: "setup-vars"
      - name: "show-vars"
  environment: "{{ myvar }}"

  tasks:
  - include_tasks: roles/a4-roles/tasks/main.yml
    loop: "{{ roles }}"
```

`hosts`
```
[webservers]
172.16.69.12
```

You will get the following result:

```
ansible-playbook -i hosts deploy.yml --private-key=~/.ssh/id_rsa

PLAY [With roles] **************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************
 [WARNING]: could not parse environment value, skipping: ['{{ myvar }}']

ok: [172.16.69.12]

TASK [setup-vars : setup-vars] *************************************************************************************************************************************************************************************************************************************************
 [WARNING]: could not parse environment value, skipping: ['{{ myvar }}']

ok: [172.16.69.12] => {
    "msg": "Setting up vars"
}

TASK [show-vars : show-vars] ***************************************************************************************************************************************************************************************************************************************************
 [WARNING]: could not parse environment value, skipping: ['{{ myvar }}']

ok: [172.16.69.12] => {
    "msg": "Value of myvar: this is my var content"
}
 [WARNING]: Found variable using reserved name: roles


PLAY [Without roles] ***********************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************
fatal: [172.16.69.12]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'myvar' is undefined"}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
172.16.69.12               : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
