### ISSUE TITLE
Module Find, Contains option Regex bug ?

### ISSUE THREAD

**Issue by roxor45** [ansible/ansible#63377]
Hello, 

I found a strange return with a module find and contains option, with the python regex "\Z"

https://docs.python.org/2/library/re.html
\Z -->    Matches only at the end of the string.

I need to check the result of the last string if it's OK or KO

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module find
##### ANSIBLE VERSION
ansible 2.8.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible/ansible
  executable location = ansible
  python version = 2.7.5

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.3 (Maipo)

##### STEPS TO REPRODUCE
create a file /tmp/test.log with : 

> 
> 01/01- OK
> 01/02- OK
> 01/03- KO
> 01/04- OK

playbook : 

```
 
 ---
   - name: check if last line is OK
     hosts: localhost
     become: true
 
     tasks:
       - name: check
         find:
           paths: /tmp/
           pattern: 'test.log'
           age: -30d
           age_stamp: mtime
           contains: ".*OK$\\Z" 
           use_regex: yes
 
```
 ps : i try with contains: '.*OK$\Z' same result

##### EXPECTED RESULTS
the end of last line is OK so we need to have  = return "matched": 1,
the end of last line is KO so we need to have  = return "matched": 0,

regex check --> https://regex101.com/r/hR9BB8/1

##### ACTUAL RESULTS
IF my regex is  ".*OK$" (without \Z) , I get "matched": 1 but i don't check the last line and same result if the last line is KO

output : 
`ok: [localhost] => {
    "changed": false,
    "examined": 138,
    "files": [],
    "invocation": {
        "module_args": {
            "age": "-30d",
            "age_stamp": "mtime",
            "contains": ".*FIN OK$\\Z",
            "depth": null,
            "excludes": null,
            "file_type": "file",
            "follow": false,
            "get_checksum": false,
            "hidden": false,
            "paths": [
                "/tmp/"
            ],
            "pattern": "test.log",
            "patterns": [
                "test.log"
            ],
            "recurse": false,
            "size": null,
            "use_regex": true
        }
    },
    "matched": 0,
    "msg": ""
}`
