### ISSUE TITLE
ini_file does not modify the target symlinked file but creates a copy of it

### ISSUE THREAD

**Issue by acataluddi** [ansible/ansible#63383]
##### SUMMARY
Suppose having a symlink `/etc/example.ini` pointing to another INI file like the following

```
+ etc/
  + example.ini -- symlink --> /opt/package/conf/example.ini
```

If you try modifying the `/etc/example.ini` using `ini_file`, the module:

- **does not** modifies `/opt/package/conf/example.ini`.
- Creates a local copy of `/opt/package/conf/example.ini` in `/etc/example.ini`.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME
`ini_file`

##### ANSIBLE VERSION
```bash
ansible 2.6.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Jun 20 2019, 14:14:55) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

##### CONFIGURATION
```paste below
ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
```
cat /etc/redhat-release
CentOS release 6.9 (Final)

uname -a
Linux host 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
1. Quickly create the described scenario by the following BASH commands:

   ```bash
   mkdir -p /opt/package/conf/
   echo "[section]"                 >> /opt/package/conf/example.ini
   echo "change_me = initial_value" >> /opt/package/conf/example.ini
   
   ln -s /opt/package/conf/example.ini /etc/example.ini
   ```

   

2. Simply run the following task:

   ```yml
   - name: "Trying to modify 'change_me' value in /opt/package/conf/example.ini"
     ini_file:
       path: "/etc/example.ini"
       section: "section"
       option: "change_me"
       value: "new value!"
       follow: true # Tried both with/without the follow option, no luck.
   ```

3. At this point:
- Your `/etc/example.ini` isn't a symlink anymore but a copy of `/opt/package/conf/example.ini`.
- The **local copy** `/etc/example.ini` is correctly modified.

##### EXPECTED RESULTS
Having the following as the contents of `/opt/package/conf/example.ini`:
```ini
[section]
change_me = new value!
```
**and still** the following symlink:
```
+ etc/
  + example.ini -- symlink --> /opt/package/conf/example.ini
```

##### ACTUAL RESULTS
`/etc/example.ini` becomes a regular file and contains the modified INI file. `/etc/example.ini` and `/opt/package/conf/example.ini` are not linked anymore.
