### ISSUE TITLE
eos_vlans : 'Overridden' state is not adding the new configs

### ISSUE THREAD

**Issue by GomathiselviS** [ansible/ansible#63406]
##### SUMMARY

In eos_vlans, when state = "overridden" , the existing configurations are deleted/defaulted as expected. But it fails to add the new configuration. The playbook still declares "Pass".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_vlans.py

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gosriniv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gosriniv/ansible/lib/ansible
  executable location = /home/gosriniv/ansible/bin/ansible
  python version = 3.6.5 (default, Sep  4 2019, 12:23:33) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]


```

##### OS / ENVIRONMENT

```
Arista vEOS
```

##### STEPS TO REPRODUCE

```
---
- hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Merge given VLAN attributes with device configuration
      eos_vlans:
        config:
          - vlan_id: 10
            name: "ten"
          - vlan_id: 20
            name: "newvlan"
        state: merged

    - name: Override given VLAN attributes with device configuration
      eos_vlans:
        config:
          - vlan_id: 50
            name: "fifty"
            state: "suspend"
        state: overridden


```

##### EXPECTED RESULTS

Deletion of vlan 10 and vlan 20.
Addition of vlan 50

##### ACTUAL RESULTS

```
Refer to 'after'

changed: [10.8.38.31] => {
    "after": [
        {
            "vlan_id": 10
        },
        {
            "vlan_id": 20
        }
    ],
    "before": [
        {
            "name": "ten",
            "vlan_id": 10
        },
        {
            "name": "newvlan",
            "vlan_id": 20
        }
    ],
    "changed": true,
    "commands": [
        "vlan 10",
        "no name",
        "vlan 20",
        "no name"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "name": "fifty",
                    "state": "suspend",
                    "vlan_id": 50
                }
            ],
            "state": "overridden"
        }
    }
}


```
