### ISSUE TITLE
mysql_user priv '*.*:ALL,GRANT' is not idempotent with MySQL 8.0.16-7

### ISSUE THREAD

**Issue by checkphi** [ansible/ansible#63403]
##### SUMMARY
When running the module mysql_user against MySQL 8.0.16-7 to set the root users privileges to '*.*:ALL,GRANT' the change is working but is not idempotent.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### CONFIGURATION
No configuration changes

##### OS / ENVIRONMENT
* Debian Buster
* Percona MySQL 8.0.16-7

##### STEPS TO REPRODUCE
```yaml
  - name: Update root user
    mysql_user:
      name: "{{ percona_root_user }}"
      host: "{{ item }}"
      password: "{{ percona_root_password }}"
      priv: "*.*:ALL,GRANT"
      state: present
    with_items: "{{ [percona_bind_ip] + ['localhost'] }}"
    notify: Flush privileges
```

##### EXPECTED RESULTS
Run is idempotent

##### ACTUAL RESULTS
```
TASK [percona : Update MySQL root password] *****************************************************************************************************************************************************
changed: [foobar] => (item=10.0.0.1) => {"ansible_loop_var": "item", "changed": true, "item": "10.0.0.1", "msg": "Privileges updated", "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}
changed: [foobar] => (item=localhost) => {"ansible_loop_var": "item", "changed": true, "item": "localhost", "msg": "Privileges updated", "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}
```

###### COMMENT
I already found the responsible code in mysql_user.py
```
priv_diff = set(new_priv[db_table]) ^ set(curr_priv[db_table])
```
_new_priv[db_table]_ contains **ALL,GRANT** while _curr_priv[db_table]_ contains **SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,RELOAD,SHUTDOWN,PROCESS,FILE,REFERENCES,INDEX,ALTER,SHOW DATABASES,SUPER,CREATE TEMPORARY TABLES,LOCK TABLES,EXECUTE,REPLICATION SLAVE,REPLICATION CLIENT,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,CREATE USER,EVENT,TRIGGER,CREATE TABLESPACE,CREATE ROLE,DROP ROLE,GRANT**
