### ISSUE TITLE
aci_static_binding_to_epg - Space character in request causing connection failure

### ISSUE THREAD

**Issue by zjpeterson** [ansible/ansible#63410]
##### SUMMARY
When using `aci_static_binding_to_epg` with `state: query` and only supplying the following parameters:
- interface
- interface_type
- leafs
- pod

The module produces a connection failure: Connection failed for [...] An unknown error occurred: URL can't contain control characters. [...] (found at least ' ')

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aci_static_binding_to_epg

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

- Red Hat Enterprise Linux Server release 7.7 (Maipo)
- APIC 3.2(3n)

##### STEPS TO REPRODUCE

```yaml
 - name: Query EPG bindings
   aci_static_binding_to_epg:
     host: apic
     username: user
     password: password
     state: query
     interface: "1/1"
     interface_type: switch_port
     leafs: 1000
     pod: 1
  register: results
```

##### EXPECTED RESULTS

Successful query return

##### ACTUAL RESULTS

Below error occurs. If the request in the error is copied, and instead passed to the APIC via the `aci_rest` module, but with the space character after `fvRsPathAtt.tDn,` removed in the query-target-filter parameter, the query succeeds. This suggests a space character is being incorrectly inserted into the request, or not encoded properly.

```paste below
Connection failed for https://apic/api/class/fvRsPathAtt.json?query-target-filter=eq(fvRsPathAtt.tDn, \"topology/pod-1/paths-1000/pathep-[eth1/1]\")&rsp-subtree-class=fvRsPathAtt&rsp-subtree=full. An unknown error occurred: URL can't contain control characters. '/api/class/fvRsPathAtt.json?query-target-filter=eq(fvRsPathAtt.tDn, \"topology/pod-1/paths-1000/pathep-[eth1/1]\")&rsp-subtree-class=fvRsPathAtt&rsp-subtree=full' (found at least ' ')"

```
