### ISSUE TITLE
ssh ControlPath is set improperly when .ansible path contains spaces

### ISSUE THREAD

**Issue by yangm97** [ansible/ansible#63425]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ssh

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /Users/yan/Documents/Projects/ansible/ansible.cfg
  configured module search path = ['/Users/yan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Oct  7 2019, 16:05:41) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/yan/Documents/Projects/ansible/ansible.cfg) = True
CACHE_PLUGIN(/Users/yan/Documents/Projects/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/yan/Documents/Projects/ansible/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/Users/yan/Documents/Projects/ansible/ansible.cfg) = 500
DEFAULT_GATHERING(/Users/yan/Documents/Projects/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/yan/Documents/Projects/ansible/ansible.cfg) = ['/Users/yan/Documents/Projects/ansible/hosts']
DEFAULT_REMOTE_USER(/Users/yan/Documents/Projects/ansible/ansible.cfg) = ansible
DEFAULT_VAULT_PASSWORD_FILE(/Users/yan/Documents/Projects/ansible/ansible.cfg) = /Users/yan/Documents/Projects/ansible/vault_keyfile
```

##### OS / ENVIRONMENT

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

##### STEPS TO REPRODUCE

`ansible-playbook deploy.yml`

```yaml
- hosts: groupbutler
  vars_files:
    - "secrets.yml"
  tasks:
  - name: deploy staging
    become: yes
    docker_stack:
      name: gb_stag
      compose:
        - '{{ lookup("file", "stack/stag.yml") | from_yaml }}'
      with_registry_auth: yes
    tags: ["stag"]
    register: stack_deploy_res
    notify:
      - telegram deploy notify

  - name: deploy production
    become: yes
    docker_stack:
      name: gb_prod
      compose:
        - '{{ lookup("file", "stack/prod.yml") | from_yaml }}'
      with_registry_auth: yes
    tags: ["prod"]
    register: stack_deploy_res
    notify:
      - telegram deploy notify

  handlers:
  - name: telegram deploy notify
    telegram:
      token: "{{ tg_notify_bot_token }}"
      chat_id: "{{ tg_notify_chat_id }}"
      msg: "Deployed!\n{{ stack_deploy_res.docker_stack_spec_diff | from_json | to_nice_yaml }}"
    tags: ["test"]
```

##### ACTUAL RESULTS

shell gobbling

```paste below
ansible-playbook 2.8.5
  config file = /Users/yan/Documents/Projects/ansible/ansible.cfg
  configured module search path = ['/Users/yan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.4 (default, Oct  7 2019, 16:05:41) [Clang 11.0.0 (clang-1100.0.33.8)]
Using /Users/yan/Documents/Projects/ansible/ansible.cfg as config file
Reading vault password file: /Users/yan/Documents/Projects/ansible/vault_keyfile
setting up inventory plugins
host_list declined parsing /Users/yan/Documents/Projects/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /Users/yan/Documents/Projects/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /Users/yan/Documents/Projects/ansible/hosts as it did not pass it's verify_file() method
Parsed /Users/yan/Documents/Projects/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: deploy.yml ***************************************************************************************************************
Positional arguments: deploy.yml
verbosity: 5
remote_user: ansible
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/Users/yan/Documents/Projects/ansible/hosts',)
forks: 5
1 plays in deploy.yml
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt /Users/yan/Documents/Projects/ansible/secrets.yml
Trying to use vault secret=(FileVaultSecret(filename='/Users/yan/Documents/Projects/ansible/vault_keyfile')) id=default to decrypt /Users/yan/Documents/Projects/ansible/secrets.yml
Trying secret FileVaultSecret(filename='/Users/yan/Documents/Projects/ansible/vault_keyfile') for vault_id=default
Decrypt of "b'/Users/yan/Documents/Projects/ansible/secrets.yml'" successful with secret=FileVaultSecret(filename='/Users/yan/Documents/Projects/ansible/vault_keyfile') and vault_id=default
Read vars_file 'secrets.yml'
Read vars_file 'secrets.yml'
Read vars_file 'secrets.yml'

PLAY [groupbutler] *****************************************************************************************************************
Read vars_file 'secrets.yml'

TASK [Gathering Facts] *************************************************************************************************************
task path: /Users/yan/Documents/Projects/ansible/deploy.yml:1
<scw-cocky-gates.yetanothernerd.xyz> ESTABLISH SSH CONNECTION FOR USER: ansible
<scw-cocky-gates.yetanothernerd.xyz> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<scw-cocky-gates.yetanothernerd.xyz> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<scw-cocky-gates.yetanothernerd.xyz> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="ansible")
<scw-cocky-gates.yetanothernerd.xyz> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<scw-cocky-gates.yetanothernerd.xyz> SSH: PlayContext set ssh_common_args: ()
<scw-cocky-gates.yetanothernerd.xyz> SSH: PlayContext set ssh_extra_args: ()
<scw-cocky-gates.yetanothernerd.xyz> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/yan/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.ansible/cp/345df1a68a)
<scw-cocky-gates.yetanothernerd.xyz> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible"' -o ConnectTimeout=10 -o 'ControlPath=/Users/yan/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.ansible/cp/345df1a68a' scw-cocky-gates.yetanothernerd.xyz '/bin/sh -c '"'"'echo ~ansible && sleep 0'"'"''
<scw-cocky-gates.yetanothernerd.xyz> (255, b'', b'command-line line 0: garbage at end of line; "Documents/com~apple~CloudDocs/Mackup/.ansible/cp/345df1a68a".\r\n')
fatal: [scw-cocky-gates.yetanothernerd.xyz]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"Documents/com~apple~CloudDocs/Mackup/.ansible/cp/345df1a68a\".",
    "unreachable": true
}

PLAY RECAP *************************************************************************************************************************
scw-cocky-gates.yetanothernerd.xyz : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

```
