### ISSUE TITLE
vars and defaults defined in tasks included with include_role or import_role cannot be used with the environment directive

### ISSUE THREAD

**Issue by tanis2000** [ansible/ansible#63443]
##### SUMMARY

I need to switch from the usual `roles:` construct to a list of `include_role` and for some reason the vars/defaults of the included roles cannot be used as input in the environment directive of the playbook.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Roles

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/tanis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS / Linux

##### STEPS TO REPRODUCE

I'm trying to wrap all the roles of Kubespray in block/rescue blocks so I had to move from the usual `roles` includes like this:

```yaml
- hosts: kube-master[0]
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults}
    - { role: kubernetes-apps/rotate_tokens, tags: rotate_tokens, when: "secret_changed|default(false)" }
    - { role: win_nodes/kubernetes_patch, tags: ["master", "win_nodes"]}
```

to this:

```yaml
- hosts: kube-master[0]
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  vars:
    roles:
      - name: "kubespray-defaults"
      - name: kubernetes-apps/rotate_tokens
        tags: rotate_tokens
        when: "secret_changed|default(false)"
      - name: win_nodes/kubernetes_patch
        tags: ["master", "win_nodes"]
      - name: "ems-notification"
        msg: kubespray-defaults, kubernetes-apps/rotate_tokens and win_nodes/kubernetes_patch completed
  environment: {{ proxy_env }}

  tasks:
  - include_tasks: roles/a4-roles/tasks/main.yml
    loop: "{{ roles }}"
```

with a4-roles/tasks/main.yml being:

```yaml
- name: a4-roles
  when: item.when | default(omit)
  block:
    - include_role:
        name: "{{ item.name }}"
        public: true
        apply:
          tags: >-
            {%- if item.tags is defined -%}
            "{{ item.tags }}"
            {%- else -%}
            ""
            {%- endif -%}
  rescue:
    - include_role:
        name: "ems-notification"
      vars:
        msg: an error has occurred
        host: "{{ inventory_hostname }}"
        result: "{{ ansible_failed_result.msg | trim | default(omit) }}"
        role: "{{ item.name }}"
        error: "true"
```

The problem is that the `kubespray-defaults` as well as other roles are setting some vars and defaults like that `proxy_env` var that can't be found when used in the environment directive in the playbook.

I have a full reproduction of this issue here:

https://github.com/tanis2000/ansible-include-role-public-bug

##### EXPECTED RESULTS

vars and defaults should be accessible with the environment directive when included through include_role or import_role

##### ACTUAL RESULTS

The vars and defaults aren't being propagated correctly in order to use them in the environment directive.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/role`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The problem here is the use of `include_tasks`.  There is a distinction between how `include` and `import` work.  `import` is a pre-processor that traverses the imports statically at playbook parsing time and merges those tasks into the play.

`include` is just in time evaluated at task execution time.  So when trying to evaluate `environment` before `include_tasks` is run, means that the roles within have not been evaluated yet.

Switching to `import_tasks` allows it to work, but you cannot loop on an `import_tasks`.

To make this work, you have a few options:

1. Give `myenv` a default in the play:

    ```
    - hosts: all
      name: "Without roles"
      vars:
        roles:
          - name: "setup-vars"
          - name: "show-vars"
      environment: "{{ myenv|default({}) }}"

      tasks:
       - include_tasks: roles/a4-roles/tasks/main.yml
         loop: "{{ roles }}"
    ```
1. Don't try to loop the roles, be explicit.

    ```
     - import_tasks: roles/a4-roles/tasks/main.yml
       vars:
         item:
           name: setup-vars

     - import_tasks: roles/a4-roles/tasks/main.yml
       vars:
         item:
           name: show-vars
    ```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
