### ISSUE TITLE
 gitlab_ modules do not accept arg api_url

### ISSUE THREAD

**Issue by wkoot** [ansible/ansible#63448]
##### SUMMARY
The `api_url` arg is not accepted since `server_url` is required (although deprecated), while `api_url` and `server_url` are `mutually_exclusive`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```
lib/ansible/modules/source_control/gitlab_group.py
lib/ansible/modules/source_control/gitlab_project.py
lib/ansible/modules/source_control/gitlab_runner.py
lib/ansible/modules/source_control/gitlab_user.py
```

##### ANSIBLE VERSION
```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/ans3.6/lib/python3.6/site-packages/ansible
  executable location = /home/user/.virtualenvs/ans3.6/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```
- name: Create gitlab user
  gitlab_user:
    api_url: "{{ gitlab_url }}"
    api_token: "{{ gitlab_token }}"
    name: test user
    username: test_user
    password: "{{ user_password }}"
    email: "{{ user_email }}"
    state: present
```

##### EXPECTED RESULTS
This should work as expected. Now you can use workaround to set `server_url` as `api_url`:
```
- name: Create gitlab user
  gitlab_user:
    server_url: "{{ gitlab_url }}"
    api_token: "{{ gitlab_token }}"
    name: test user
    username: test_user
    password: "{{ user_password }}"
    email: "{{ user_email }}"
    state: present
```

##### ACTUAL RESULTS
```
TASK [Create gitlab user] *******************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: server_url"}
```
