### ISSUE TITLE
zabbix_action: do not require esc_period for state: absent

### ISSUE THREAD

**Issue by richlv** [ansible/ansible#63455]
##### SUMMARY
`esc_period` is mandatory even with `state: absent` - should be optional in that case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
latest

##### CONFIGURATION
Not relevant.

##### OS / ENVIRONMENT
Not relevant.

##### STEPS TO REPRODUCE
```yaml
  - name: "Report problems to Zabbix administrators"
    event_source: 'trigger'
    state: absent
```

##### EXPECTED RESULTS
Action, if exists, is removed.

##### ACTUAL RESULTS
```paste below
"msg": "missing required arguments: esc_period"
```
