### ISSUE TITLE
lambda_facts max_items unsupported

### ISSUE THREAD

**Issue by sambanks** [ansible/ansible#63489]
##### SUMMARY
By default the lambda_facts module only gives 50 results.
In the example there is a max_items option, but when I try and use that I get an error about max_items being an unsupported parameter

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lambda_facts

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### CONFIGURATION
Defaults
```
root@ip-192-168-205-155:~# ansible-config dump --only-changed
root@ip-192-168-205-155:~# 
```

##### OS / ENVIRONMENT
Debian 9.5
Amazon EC2 spot instance
Ansible 2.8.4-1ppa~trusty

##### STEPS TO REPRODUCE
```
- name: List all functions
  lambda_facts:
    query: all
    max_items: 500
    region: "{{cf_region}}"
    aws_access_key: "{{assumed_role.sts_creds.access_key}}"
    aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
    security_token: "{{assumed_role.sts_creds.session_token}}"
  loop_control:
    loop_var: sub_item

```

##### EXPECTED RESULTS

List all functions

##### ACTUAL RESULTS

```
TASK [aws_lambda_clean_versions : List all functions] **************************
--
  | fatal: [localhost]: FAILED! => changed=false
  | msg: 'Unsupported parameters for (lambda_facts) module: max_items Supported parameters include: aws_access_key, aws_secret_key, debug_botocore_endpoint_logs, ec2_url, event_source_arn, function_name, profile, query, region, security_token, validate_certs'
```
