### ISSUE TITLE
Passing through variables to dependent roles behaves unexpectedly

### ISSUE THREAD

**Issue by ThreeFx** [ansible/ansible#63483]
##### SUMMARY

When passing a role variable to a dependency via `meta/main.yml` multiple times in a block the variable in the dependency is not set correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles / variable handling

##### ANSIBLE VERSION

```
bfiedler@xps:~/programming/ansible
% ansible --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bfiedler/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Oct  4 2019, 06:57:26) [GCC 9.2.0]
```

##### CONFIGURATION

```
bfiedler@xps:~/programming/ansible
% ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

* OS: Arch Linux

The rest shouldn't matter.

##### STEPS TO REPRODUCE

```yaml
play.yml:
---
- name: Roll out r1 twice
  hosts: localhost
  roles:
    - role: r2
      vars:
        pb_var: one
    - role: r2
      vars:
        pb_var: two

---
r2/tasks/main.yml:
---
- debug:
    var: "pb_var"
---
r2/meta/main.yml:
---
dependencies:
  - role: r1
    vars:
      r1_var: "{{ pb_var }}"

r1/tasks/main.yml:
---
- debug:
    var: "r1_var"

---
r1/meta/main.yml:
---
allow_duplicates: true
```

[Full example to download here](https://github.com/ansible/ansible/files/3726297/example.zip)

##### EXPECTED RESULTS

I expect `r1_var` to be set to `one` when `pb_var` is `one`.

##### ACTUAL RESULTS

```
% ansible-playbook play.yml
PLAY [Roll out r1 twice] ****************************************************

TASK [r1 : debug] **********************************************************
ok: [localhost] => {
    "r1_var": "two"
}

TASK [r2 : debug] **********************************************************
ok: [localhost] => {
    "pb_var": "one"
}

TASK [r1 : debug] **********************************************************
ok: [localhost] => {
    "r1_var": "two"
}

TASK [r2 : debug] **********************************************************
ok: [localhost] => {
    "pb_var": "two"
}
```

```paste below
ansible-playbook play.yml
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ThreeFx** [comment]
The same thing happens when using 
[import_role](https://github.com/ansible/ansible/files/3726435/import_role.zip) or
[include_role](https://github.com/ansible/ansible/files/3726436/include_role.zip) instead of meta dependencies, which leads me to conclude that this is a bug.

**Comment by sivel** [comment]
The issue here is in how `vars` on a role are scoped.  `vars` on a role are scoped at the play level, and as such, the 2nd wins, so `pb_var` is only ever set to `two`.

This would have become apparent with `allow_duplicates: no` as `r1` would have only ever run 1 time, as both invocations are identical.

Take note that role `vars` are different than `params`:

```
role:
  - name: role_with_params
    pb_var: two

  - name: role_with_vars
    vars:
      pb_var: two
```

Those 2 invocations have different scope, where the `params` version is scoped to the role, and the `vars` version is scoped to the play.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
