### ISSUE TITLE
In complement of serial, be able to set how many hosts of a group can be treated at the same time.

### ISSUE THREAD

**Issue by msieurtoph** [ansible/ansible#63506]
##### SUMMARY
Be able to set a serial per group, to limit the play run on no more than N hosts of groupA at a time, no more than M hosts of groupB, ... 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
!component

Inventory could look like this : 

```
[groupA:serial=5]
hostA1
hostA2
...
hostA12

[groupB:serial=2]
hostB1
hostB2
...
hostB5

[groupC:serial=1]
hostC1
hostC2


```

##### ADDITIONAL INFORMATION

My play would look like this : 

```yaml

- name: My play
  hosts:
    - all
  
  tasks:
    - ...
    - ...

```
I would expect the play executes all iterations like this : 

First loop : 
- use 5 hosts of groupA, 2 of groupB and 1 of groupC.

Second loop : 
- use 5 other hosts of  groupA, 2 other ones of groupB and the last host of groupC.

Third iteration : 
- use the 2 last hosts of groupA and the last host of groupB. 

The "serial" variable could still work, limiting the max number of hosts used at the same time (independing of groups). I could set a serial to 7 for example and my first iteration would only use 7 hosts max, as long as there is no more than 5 hosts of groupA, 2 of groupB or 1 of groupC ...

See the point ?

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by msieurtoph** [comment]
Maybe, it could be easier and more scalable to have another dict property like this  : 

```yaml
- name: My play
  hosts:
    - all
  group_serial: 
    groupA: 5
    groupB: 2
    groupC: 1
  
  tasks:
    - ...
    - ...
```

This way, each play could have its own "configuration" depending on what it really does ...
Some could use all the hosts together and others could limit tasks to X hosts per group at the same time.

... and I guess it will be more easier to implement for the ansible team.
