### ISSUE TITLE
Ansible failed to run with "become: yes" when run with root user

### ISSUE THREAD

**Issue by akhilesh2410** [ansible/ansible#63549]
SUMMARY

I am running Ansible playbook in a K8S pod with root user, and have 3 AWS  instance on cloud with non root user, on which I need install some packages.

ISSUE TYPE
- Bug Report

COMPONENT NAME
Ansible Playbook

##### ANSIBLE VERSION

```
root@manager-78f457f4cc-vljgv:/# ansible --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
root@manager-78f457f4cc-vljgv:/#
```

CONFIGURATION
```
oot@manager-78f457f4cc-vljgv:/# ansible-config dump --only-changed
root@manager-78f457f4cc-vljgv:/#
```

##### OS / ENVIRONMENT
Source k8s pod with root user :
root@manager-78f457f4cc-vljgv:/# uname -a
Linux manager-78f457f4cc-vljgv 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@manager-78f457f4cc-vljgv:/#

Destination Machine with non-root user: 
1. Ubuntu 18.04 amd64
2. CentOS 7
3. Amazon ec2

STEPS TO REPRODUCE
1. run k8s pod (by default run with root user), Base OS Image ubuntu 16.04
2. from this pod I am running image-builder's packer utility using `make build-amp-default` : https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/Makefile#L48
3. the above command failed while running playbook on target machine.

```
- hosts: all
  become: yes
  roles:
    - role: common
    - role: containerd
    - role: kubernetes
    - role: providers
    - role: sysprep
```

 EXPECTED RESULTS
Ansible task should run successfully

ACTUAL RESULTS

```
  centos-7: TASK [common : add epel repo] **************************************************
    ubuntu-1804:
    ubuntu-1804: PLAY [all] *********************************************************************
    ubuntu-1804:
    ubuntu-1804: TASK [Gathering Facts] *********************************************************
    amazon-2: fatal: [default]: FAILED! => {"changed": false, "changes": {"installed": ["/tmp/.ansible/ansible-tmp-1571144007.24-77914685794005/epel-release-latest-7.noarchvxx1Zi.rpm"]}, "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: extras_suggestions, langpacks, priorities, update-motd\n"]}
    amazon-2:
    amazon-2: PLAY RECAP *********************************************************************
    amazon-2: default                    : ok=1    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0
    amazon-2:
    centos-7: fatal: [default]: FAILED! => {"changed": false, "changes": {"installed": ["/tmp/.ansible/ansible-tmp-1571144012.14-267347793039706/epel-release-latest-7.noarchIXX6WP.rpm"]}, "msg": "You need to be root to perform this command.\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\n"]}
    centos-7:
    centos-7: PLAY RECAP *********************************************************************
    centos-7: default                    : ok=1    changed=0    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0
    centos-7:
```
