### ISSUE TITLE
Does roles support block/rescue/finally section?

### ISSUE THREAD

**Issue by alwaysharsha** [ansible/ansible#63543]
##### SUMMARY
Does Ansible roles support block/rescue/finally section in the playbook like

roles:
  - block:
      - role_1
      - role_2
      - role_3
   rescue:
      - role_rescue
   finally:
      - role_finally

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible roles
##### ANSIBLE VERSION

```paste below
Ansible 2.8
```

##### STEPS TO REPRODUCE

```yaml
roles:
  - block:
    - role_1
    - role_2
    - role_3
    rescue:
    - role_rescue
   finally:
    - role_finally
```

Do we support block/rescue for Ansible roles? 
This helps as our tasks are complex incase of any failure we would like to perform rescue operation which is generic. It we add this to every role it means there is lot of duplicacy of same content.

Let us know if there is an better approach for this scenario.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/galaxy/data/default/collection/roles/.git_keep`](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/default/collection/roles/.git_keep)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
List Information
================

Hi!

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

Blocks are logical groupings of tasks. To use them with roles, you can use include_role/import_role under `tasks`:
```
tasks:
  - block:
      - name: Include a role that will fail
        include_role:
          name: role1
    rescue:
      - name: Include a role inside rescue
        include_role:
          name: role2
    always:
      - name: Include role inside always
        include_role:
          name: role3
```

Thanks and we look forward to seeing you on the list or IRC!
