### ISSUE TITLE
yum is very slow for already installed package

### ISSUE THREAD

**Issue by CendioOssman** [ansible/ansible#63551]
##### SUMMARY
Using the yum module to check if a package is already installed takes an enormous 8 seconds to complete, which eats up a lot of the time spent running any non-trivial playbook.

For reference rpm takes 20 ms to do the same.

(I found some existing bugs on the theme that the yum module was slow, but they all seemed to be about when it actually installs something)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /local/home/ossman/devel/ansible/ansible.cfg
  configured module search path = ['/home/ossman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION
```
DEFAULT_STDOUT_CALLBACK(/local/home/ossman/devel/ansible/ansible.cfg) = yaml
```

##### OS / ENVIRONMENT
Ansible machine: Fedora 30
Target machine: RHEL 7

##### STEPS TO REPRODUCE
```yaml
- name: install ntp
  package:
    name: ntp
    state: present
```

##### EXPECTED RESULTS
The yum module is able to verify the package is installed in a few hundred ms at most.

##### ACTUAL RESULTS
The yum module takes 7-8 seconds to determine that the package is already installed.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @kustodian @maxamillion @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by CendioOssman** [comment]
I did some tracing and found some where it spends its time:

The module initialises yum no less than **three** times, each invocation taking about 2.5 seconds:

 1. When listing modules to determine if it needs to apply the workaround using `repoquery`
 2. When setting up repos
 3. When querying the rpm database

I think all three can be optimised around.

 1. Check if the workaround is needed only when it actually matters. E.g. via a helper function that has a cached result for multiple calls.
 2. Don't init yum if the repo list won't change (which should be the common case)
 3. Something must be broken here since it looks like it does a rpmdb call, not a yum call. Yet it takes 2.5 seconds rather than the expected 20 ms. Hopefully it is possible to work around yum getting fully activated and accessing the rpmdb directly.

Besides these improvements, there should also be possible to keep a single yum instance around once it is created and avoid having to recreate it all the time.

**Comment by maxamillion** [comment]
Confirmed, it appears the code is re-instantiating the `YumBase` object many times which we shouldn't and don't need to. However, we must do it twice in the `state: absent` case because the `yumSack` and `rpmSack` data of the previously instantiated object becomes invalid and is no longer useful post transaction when we verify that the package removal did in fact take place.

I have a patch that I'll submit shortly, it appears to substantially speed things up:

```yaml
- hosts: rhel7
  remote_user: root
  tasks:
  - name: Install generic packages
    yum:
      state: present
      name:
        - iptraf-ng
        - screen
        - erlang
  - name: Remove generic packages
    yum:
      state: absent
      name:
        - iptraf-ng
        - screen
        - erlang
```

Before patch:
```
real    0m52.728s
user    0m5.645s
sys     0m0.482s
```

After patch:
```
real    0m17.139s
user    0m3.238s
sys     0m0.277s
```

**Comment by CendioOssman** [comment]
Great. This issue was about the case where things are already installed though. Have you checked if your patch also improves that? E.g. this play:

```yaml
- hosts: rhel7
  tasks:
  - name: install base pacakges
    yum:
      state: present
      name:
        - glibc
        - rpm
```
