### ISSUE TITLE
Use openssl_csr and openssl_certificates without disk access (sign certificates in memory)

### ISSUE THREAD

**Issue by onitake** [ansible/ansible#63553]
##### SUMMARY

When generating TLS certificates for a server, it would be very useful to generate certificate requests only in memory and sign them on the CA without writing unnecessary copies to disk.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssl_certificate
openssl_csr

##### ADDITIONAL INFORMATION

With the current implemetation, it is necessary to write certificate requests on the generating host to disk, transfer them to the CA host, sign them, write the certificate to disk and transfer the certificate file back to the server.

This is unnecessary, as the CSRs are temporary and can be kept only in memory during the signing process. Equally, the certificates are normally not needed to be stored on the CA host.

With the openssl command line tool, it is possible to use stdin and stdout to transfer the CSR and certificate directly back into Ansible, but the openssl command line tool is somewhat awkward to use and misses certain features on older versions.

Ideally, something like this should be possible:
```yaml
- name: Generate certificate signing request on target host
  openssl_csr:
    privatekey_path: /etc/ssl/private/ansible.com.pem
    common_name: www.ansible.com
  register: csr_created

- name: Sign certificate on CA host
  openssl_certificate:
    csr_content: "{{ csr_created.content }}"
    ownca_path: /etc/ssl/crt/ansible_CA.crt
    ownca_privatekey_path: /etc/ssl/private/ansible_CA.pem
    provider: ownca
  when: csr_created is changed
  delegate_to: cahost
  register: crt_created

- name: Store certificate on target host
  copy:
    dest: /etc/ssl/crt/ansible.com.crt
    content: "{{ crt_created.content }}"
    mode: 0644
  when: crt_created is changed
```
