### ISSUE TITLE
Infoblox NIOS: missing Module to create EAs

### ISSUE THREAD

**Issue by digifuchsi** [ansible/ansible#63560]
##### SUMMARY

I have noticed, that you can define extensible attributes in almost every(?) nios module, but a module to define those EAs is missing. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nios

##### ADDITIONAL INFORMATION

The module can be used to create an EA before setting it on an Infoblox Object (e.g. IPv4 Network).
The module (nios_extensible_attribute ?) should allow managing EAs (create/update/delete) so you do not have to define the EAs by hand before using them in other NIOS modules.

```yaml
- name: "add managed_by EA"
   nios_extensible_attribute:
     provider: "{{ nios_provider }}"
     name: "managed_by"
     type: "String"
     comment: "indicates system managing this object"
     inheritance: Yes
     default: "unmanaged"
     restrict_to:
        - "IPv4 Network"
        - "IPv6 Network"
```
