### ISSUE TITLE
User module fails when user already present

### ISSUE THREAD

**Issue by codingonHP** [ansible/ansible#63563]
##### SUMMARY
When executing user creation ansible module, below error is seen consistently.
Sample playbook and its corresponding output can be seen below

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
system/user module

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /home/ansible_user/ansible-repo/ansible.cfg
  configured module search path = [u'/home/ansible_user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```DEFAULT_HOST_LIST(/home/ansible_user/ansible-repo/ansible.cfg) = [u'/home/ansible_user/.ansible_protected/inventory', u'/home/ansible_user/ansible-repo/environments/common',
DEFAULT_TIMEOUT(/home/ansible_user/ansible-repo/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible_user/ansible-repo/ansible.cfg) = /home/ansible_user/.ansible_protected/ansible_vault_pass
PERSISTENT_COMMAND_TIMEOUT(/home/ansible_user/ansible-repo/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/ansible_user/ansible-repo/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
RHEL 7.4

##### STEPS TO REPRODUCE

```yaml
### Users / Groups
---
  - name: Testing user module
    hosts: all
    tasks:
    - name: Add primary group
      group:
          name: "some_user"
          state: present

    - name: Add user
      user:
          name: "some_user"
          comment: "service user"
          shell: "/bin/bash"
          home: "/opt/some_user"
          state: present

```

##### EXPECTED RESULTS
The user should not fail when user is state=present and user already present with expected properties

##### ACTUAL RESULTS
```
[ansible_user@ansible_host ansible-repo]$ ansible-playbook test.yml --limit host-3
 [WARNING]: Unable to parse /home/ansible_user/.ansible_protected/inventory as an inventory source

 [WARNING]: Unable to parse /home/ansible_user/ansible-repo/environments/common as an inventory source


PLAY [Testing user module] ***********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [host-3]

TASK [Add primary group] *************************************************************************************************************************************
ok: [host-3]

TASK [Add user] **********************************************************************************************************************************************
fatal: [host-3]: FAILED! => {"changed": false, "msg": "usermod: user some_user is currently used by process 5003\n", "name": "some_user", "rc": 8}

PLAY RECAP ***************************************************************************************************************************************************
host-3                     : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[ansible_user@ansible_host ansible-repo]$

```
