### ISSUE TITLE
credstash lookup plugin hangs after upgrading to catalina macos

### ISSUE THREAD

**Issue by vaibhav-research** [ansible/ansible#63601]
##### SUMMARY
credstash lookup plugin hangs after upgrading to catalina macos

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
credstash plugin

##### ANSIBLE VERSION
tried with ansible 2.8.4 and 2.8.5. 
credstash versions tried 1.14, 1.15 and 1.16

##### OS / ENVIRONMENT
catalina macos

##### STEPS TO REPRODUCE
1. update the macos to catalina
2. add a task to get the version in runtime using lookup plugin 
3. run the playbook
4. it will hang on the task below and never move forward

have this task to get the version from credstash table
```

- name: fdb_version - lookup postboot.versions.fdb.{{ ec2_tag_cluster }}
    set_fact:
      fdb_version: "{{ lookup('credstash', 'postboot.versions.fdb.{{ ec2_tag_cluster }}', region='us-west-2', table='runtime-credentials-store') }}"
    ignore_errors: true
    no_log: true
```

##### EXPECTED RESULTS
it should get the version from credstash table in runtime using lookup plugin

##### ACTUAL RESULTS
the task just sits there doing nothing

```
TASK [get-runtime-versions : debug] ***************************************************************************************
task path: /Users/vaibhavpandey/code/wavefront/ansible/roles/get-runtime-versions/tasks/get-bcs-version.yml:12
[mux  95251] 00:31:20.342214 D mitogen.[ssh.10.31.0.15.sudo.root]: Dispatcher: dispatching (None, u'mitogen.core', u'Dispatcher', u'forget_chain', ('vaibhavp-a01.vmware.com-95408-10e566d40-59513b0343cad',), Kwargs({}))
[mux  95251] 00:31:20.343141 D mitogen.[ssh.10.31.0.15.sudo.root]: Dispatcher: Message(4, 2095, 0, 101, 0, '\x80\x02(NX\x0c\x00\x00\x00mitogen.coreX\n\x00\x00\x00Dispatcherq\x01X\x0c\x00\x00\x00forget_'..147) -> None

```
