### ISSUE TITLE
IPA modules: allow host autodiscovery from domain SRV records

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#63617]
##### SUMMARY

IPA modules that connect to IPA API currently require `ipa_host` variable which is quite impractical when dealing with larger domain where servers are in different geos so with different latencies, particular server names can change or a specific server may be unreachable. All of the above is solved by using SRV records `_ldap._tcp.DOMAIN` and by instructing `ipa_*` modules to accept `ipa_domain` argument as an alternative to `ipa_host` which would then do all the proper things (use of priority, weight, trying next server if one fails and caching it for faster subsequent `ipa_*` modules execution) in the background

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ipa_dnszone, ipa_host, ...

##### ADDITIONAL INFORMATION
The missing feature ca be crudely approximated by this not exactly elegant invocation:
```yaml
- hosts: localhost
  vars:
    ipa_domain: DOMAIN
    ipa_host: "{{ (query('dig', '_ldap._tcp.' + ipa_domain, 'qtype=SRV',
               'flat=0') | sort(attribute='weight', reverse=True)
               | sort(attribute='priority') | first).target |
               regex_replace('\\.$', '') }}"
    tasks:
    - name: create zone
      ipa_dnszone:
        ipa_host: "{{ ipa_host }}"
        …
```
but this way, weight works absolutely instead of just raising chance for a record to be picked and most importantly, resilience is lost and the modules won't work if the first sorted result is unreachable.
