### ISSUE TITLE
[Cron module] Disabled option should work with a cron_file specified

### ISSUE THREAD

**Issue by mjip** [ansible/ansible#63629]
##### SUMMARY

There doesn't seem to be a way to disable a cronjob with a pre-existing cron_file without removing it completely. The disabled=true only seems to work when creating a new cron job using the cron module. If I want to comment out a pre-existing cronfile in Ansible (e.g. under /etc/cron.d), I'll use the replace module and match with the start of every line. I believe this kind of functionality should be provided in the cron module itself (disabling/enabling pre-existing jobs).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

The cron module (`ansible/modules/system/cron.py`)

##### ADDITIONAL INFORMATION

Ideal usage could be something like this for disabling:
```yaml
- name: Disable cronjob playbook
  tasks:
    - name: Disable /etc/cron.d/backup_system
      cron:
        cron_file: /etc/cron.d/backup_system
        disabled: true
```
If disabled=false with a cron_file specified, every line in the cron_file can be uncommented.

I'm open to discussion on this (feel free to tell me if this is a bad idea/won't work because of x). If there are no opposing views I'll attempt a PR
