### ISSUE TITLE
make_module fails if make command is under /usr/bin/make

### ISSUE THREAD

**Issue by theboyisno-1** [ansible/ansible#63627]
##### SUMMARY

If 'make' executable is not present under ['/sbin', '/usr/sbin', '/usr/local/sbin'] but in '/usr/bin/' and you try to run make_module, even with `become: true`, it will fail.
Basically [process.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/process.py) : 22 only looks into `['/sbin', '/usr/sbin', '/usr/local/sbin']` paths for executable however it should look into `/usr/bin` also if `become: true` is provided with task. 
On otherhand, according to line 25 [ ` if d is not None and os.path.exists(d):`], it also looks into $PATH variable, interestingly `/usr/bin` is presented in $PATH but module fails with err message: `msg": "Failed to find required executable make in paths: /usr/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"` 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

make_module : https://docs.ansible.com/ansible/latest/modules/make_module.html

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/home/<user>/Desktop/ansible/<My git repop>/ansible.cfg) = False
MAX_FILE_SIZE_FOR_DIFF(/home/<user>/Desktop/ansible/<My git repo>/ansible.cfg) = 1048576
```

##### OS / ENVIRONMENT

uname -a :
5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

- Create ansible role to compile some library or program.
- Provide it with 'become: true' so that it can escalate if required
- make path should be /usr/local/make.

```yaml

- name: Configure node_exporter | get $PATH
  shell: echo $PATH
  register: path_var

- name: Configure node_exporter | Build node_exporter
  become: true
  environment:
    PATH: "/usr/bin:/usr/local/go/bin:{{ path_var.stdout }}"
    GOPATH: "/root/go"
    GOBIN: "/root/go/bin"
  make: 
    target: build
    chdir: "/root/go/src/github.com/prometheus/node_exporter"
  when: node_exporter is defined
```

##### EXPECTED RESULTS

- Ansible will escalate if root access is required for executable.
- Above tasks run successfully

##### ACTUAL RESULTS

`msg": "Failed to find required executable make in paths: /usr/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"`

```paste below
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_make_payload_d_6c7_/ansible_make_payload.zip/ansible/module_utils/basic.py", line 1974, in get_bin_path
    bin_path = get_bin_path(arg, required, opt_dirs)
  File "/tmp/ansible_make_payload_d_6c7_/ansible_make_payload.zip/ansible/module_utils/common/process.py", line 41, in get_bin_path
    raise ValueError('Failed to find required executable %s in paths: %s' % (arg, os.pathsep.join(paths)))

fatal: [my-host-1]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "chdir": "/root/go/src/github.com/prometheus/node_exporter", 
            "file": null, 
            "params": null, 
            "target": "build"
        }
    }, 
    "msg": "Failed to find required executable make in paths: /usr/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
}

```
