### ISSUE TITLE
Hashed 'control_path' does't account for cases when different hosts in separate networks share the same 'ansible_host' values

### ISSUE THREAD

**Issue by ElSamhaa** [ansible/ansible#63647]
##### SUMMARY

The hashed socket name that ansible produces per host doesn't account for cases when 2 machines have the same `ansible_host` but are reached through different networks. Hence, ansible reuses the socket of the first run-host to reach the second host, and ends up retrieving the wrong values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ssh`
`control_path`
##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/a7mad/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

All machines _(control and remote)_ run `centos 7.7`.

##### STEPS TO REPRODUCE

I have two separate network environments; `a` and `b`, each containing a host with the same short hostname, say `linux`.

Now to differentiate between the two hosts without messing with connection parameters, I've temporarily appended the corresponding env names to each hostname, i.e `linux-a`, `linux-b`. This would allow me to run a simple test `ad-hoc` command and detect which host is reached.

With configuration left at defaults, and `/etc/ansible/hosts` containing the following:
```yaml
all:
  children:
    env_a:
      hosts:
        linux-a:
          ansible_host: linux
      vars:
        ansible_ssh_common_args: '-oProxyCommand="ssh -W %h:%p jumpserver -p 24255"'
    env_b:
      hosts:
        linux-b:
          ansible_host: linux
```

when I issue a simple test run such as:
`ansible all -a hostname`

##### EXPECTED RESULTS

```bash
linux-a | CHANGED | rc=0 >>
linux-a

linux-b | CHANGED | rc=0 >>
linux-b
```

##### ACTUAL RESULTS

```bash
linux-a | CHANGED | rc=0 >>
linux-a

linux-b | CHANGED | rc=0 >>
linux-a
```

_P.S, I'm working on a fix to account for such cases, and will issue a PR_

referencing [#63161](https://github.com/ansible/ansible/issues/63161)
