### ISSUE TITLE
Gather facts incorrect python interpreter (delegate_facts)

### ISSUE THREAD

**Issue by sanderdescamps** [ansible/ansible#63658]
##### SUMMARY
I need to gather facts from the new deployed machine CentOS and from my Ubuntu DNS server. For some reason does the order of execution matter. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
setup

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct  7 2019, 17:36:04) [GCC 8.3.0]
```

##### STEPS TO REPRODUCE

When I first gather facts on the dns server (other host) and then gather facts on the new template machine (current host) then it works. When I reverse the order then I get an error. It seems as Ansible uses the facts gathered from the current machine when it gathers facts from the other machine. Because the machines have a different OS, I get a python interpreter error. 

This failed
```
---
  - name: Reproduce issue
    gather_facts: no
    hosts:
      - srvtest01.domain.com
    vars:
      envdef_dns_server: srvdns01.domain.cm
      hostdef_vm_ip: 10.10.6.95
    tasks:
      - name: Gather facts on template
        setup:
        delegate_to: "{{hostdef_vm_ip}}"
      - name: Gather facts on DNS server
        setup:
        delegate_to: "{{envdef_dns_server}}"
        delegate_facts: yes
```

The error
```
user@machine:~/git/deploy_vm$ ansible-playbook test2.yml

PLAY [Reproduce issue] *********************************************************

TASK [Gather facts on template] ************************************************
ok: [srvtest01.domain.com -> 10.10.6.95]

TASK [Gather facts on DNS server] **********************************************
fatal: [srvtest01.domain.com -> srvdns01.domain.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to srvdns01.domain.com closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP *********************************************************************
srvtest01.domain.com   : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
This works
```
---
  - name: Reproduce issue
    gather_facts: no
    hosts:
      - srvtest01.domain.com
    vars:
      envdef_dns_server: srvdns01.domain.com
      hostdef_vm_ip: 10.10.6.95
    tasks:
      - name: Gather facts on DNS server
        setup:
        delegate_to: "{{envdef_dns_server}}"
        delegate_facts: yes
      - name: Gather facts on template
        setup:
        delegate_to: "{{hostdef_vm_ip}}"
```
result
```
user@machie:~/git/deploy_vm$ ansible-playbook  test2.yml

PLAY [Reproduce issue] *********************************************************

TASK [Gather facts on DNS server] **********************************************
ok: [srvtest01.domain.com -> srvdns01.domain.com]

TASK [Gather facts on template] ************************************************
ok: [srvtest01.domain.com -> 10.10.6.95]

PLAY RECAP *********************************************************************
srvtest01.domain.com   : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
