### ISSUE TITLE
backslash swallowed by command module

### ISSUE THREAD

**Issue by wferi** [ansible/ansible#6367]
##### Issue Type:

Bug Report
##### Ansible Version

ansible 1.6 (devel 6690c23439) last updated 2014/03/03 14:56:30 (GMT +200)
##### Environment:

(from and to) Debian wheezy
##### Summary:

backslash does not reach verbatim the target command line
##### Steps To Reproduce:

I'd expect the following to print literal \n, as the single quotes protect the backslash from the local shell, and -- according to the documentation -- no other shell comes into play:

```
$ ansible -i hosts localhost -vv -a 'echo \n'
<localhost> REMOTE_MODULE command echo \n
localhost | success | rc=0 >>
n
```

Indeed, protecting the backslash from the (local) shell and not involving Ansible gives:

```
$ echo \\n
\n
```

Maybe it's a _stealth shell_ problem, like the one unexpectedly invoked by the metacharacter on the command line here:

```
$ ssh localhost 'echo \n'
n
```

Anyway, it's against the documentation as I read it, thus an issue...
##### Expected Results:

```
\n
```
##### Actual Results:

```
n
```

**Comment by mpdehaan** [comment]
The default -m module is "shell", so you are evaluating through bash on the remote side.

The single quotes are only protecting things on your local side.

Use "-m command" to avoid running things through the remote shell.

**Comment by wferi** [comment]
Calling ansible without arguments says:

```
  -m MODULE_NAME, --module-name=MODULE_NAME
                        module name to execute (default=command)
```

Anyway, adding `-m command` to the command line does not change anything.

**Comment by mpdehaan** [comment]
Yep, that's true, hard to remember all option defaults!

**Comment by ilkka** [comment]
I have a kind of related problem.

Actually I have two problems, one of which is that I am trying to deploy stuff to a Windows Server 2012 machine using Ansible and kind of succeeding, but the other, more related problem is that it's generally speaking really really hard to deal with backslashes in Ansible.

Case in point:

``` yml
---
- name: run a command that spits out a windows backslashed path
  command: some_command
  register: cmd

- name: here I can use the output and backslashes are intact
  some_module: arg={{ cmd.stdout }}

- name: however, if I set_fact
  set_fact: cmd_out={{ cmd.stdout }}

- name: here the backslashes are stripped
  other_module: arg={{ cmd_out }}
```
