### ISSUE TITLE
vmware_guest: windows customization

### ISSUE THREAD

**Issue by cr00836** [ansible/ansible#63678]
##### SUMMARY

Even i don't set the customization parameters, when i do a clone from template of a windows machine the vmware customization starting and changing the hostname and the server SID.
It's possibile to prevent this behaviour?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
ansible 2.8.5
```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/home/ansible/ansible.cfg) = True
COMMAND_WARNINGS(/home/ansible/ansible.cfg) = False
DEFAULT_CALLBACK_WHITELIST(/home/ansible/ansible.cfg) = [u'minimal', u'profile_tasks', u'profile_roles']
DEFAULT_HOST_LIST(/home/ansible/ansible.cfg) = [u'/home/ansible/hosts']
DEFAULT_LOG_PATH(/home/ansible/ansible.cfg) = /home/ansible/log/ansible.log
DEFAULT_MANAGED_STR(/home/ansible/ansible.cfg) = Ansible managed
DEFAULT_ROLES_PATH(/home/ansible/ansible.cfg) = [u'/home/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/ansible/ansible.cfg) = yaml
DISPLAY_ARGS_TO_STDOUT(/home/ansible/ansible.cfg) = True
GALAXY_ROLE_SKELETON_IGNORE(/home/ansible/ansible.cfg) = [u'^.*/.git$', u'^.*/.git_keep$']
HOST_KEY_CHECKING(/home/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/home/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible 2.8.5
VMWare 6.5

##### STEPS TO REPRODUCE

```yaml
- name: Create a VM from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vcenter_folder }}"
    name: "{{ vm_name }}"
    state: poweredon
    template: "{{ vm_template }}"
    networks:
    - name: "{{ vm_vlan }}"
      type: static
      ip: "{{ vm_ip }}"
      netmask: "{{ vm_mask }}"
      gateway: "{{ vm_gw }}"
    wait_for_ip_address: yes
    annotation: "{{ vm_template }}"

```

##### EXPECTED RESULTS

My expectation is to have the original VM cloned to an equal VM with the designated IP 

##### ACTUAL RESULTS

```paste below
The VM it's cloned but the hostname and the SID operative system changed by the vmware customization process
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@cr00836, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sky-joker** [comment]
Hi @cr00836

sysprep is ran if `ip` is defined in `networks`.
If you don't run sysprep, create a playbook like this.

```yaml
- name: Create a VM from a template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vcenter_folder }}"
    name: "{{ vm_name }}"
    state: poweredon
    template: "{{ vm_template }}"
    networks:
      - name: "{{ vm_vlan }}"
    wait_for_ip_address: yes
    annotation: "{{ vm_template }}"
```

remove `ip` from networks.
