### ISSUE TITLE
parted doesn't set name when creating gpt partition on busy table

### ISSUE THREAD

**Issue by rosowiecki** [ansible/ansible#63673]
##### SUMMARY

Contrary to the documentation, parted module doesn't set name for GPT partitions it creates. It is able only to change name of existing partitions.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

parted
##### ANSIBLE VERSION

```paste below
ansible 2.7.11
```

##### STEPS TO REPRODUCE

```yaml
{
    "changed": false, 
    "err": "", 
    "failed_when_result": false, 
    "invocation": {
        "module_args": {
            "align": "optimal", 
            "device": "/dev/sdb", 
            "flags": null, 
            "label": "gpt", 
            "name": "rootfs", 
            "number": 1, 
            "part_end": "16001MiB", 
            "part_start": "1MiB", 
            "part_type": "primary", 
            "state": "present", 
            "unit": "MiB"
        }
    }, 
    "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/sdb -- unit MiB mkpart primary 1MiB 16001MiB", 
    "out": "Warning: WARNING: the kernel failed to re-read the partition table on /dev/sdb (Device or resource busy).  As a result, it may not reflect all of your changes until after reboot.\n", 
    "rc": 1
}
```
Note that script doesn't set the partition name set by name, it creates partition named "primary" instead (partition type is not relevant to GPT)

##### EXPECTED RESULTS

GPT partition should be created with specified name

##### ACTUAL RESULTS

GPT partition is created with 'primary' name. Repeated module invocation is necessary to set desired name.
