### ISSUE TITLE
win_package fails when arguments are passed as list

### ISSUE THREAD

**Issue by mjnorman** [ansible/ansible#63691]
##### SUMMARY
When using win_package and passing multiple arguments as a list, arguments are not correctly being interpreted.  This is proven by the fact that installation logs are not created at the destinations supplied in the arguments.  When those same arguments are passed as a single parameter, arguments are interpreted correctly since the logs are created in the correct destinations.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_package

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = [u'/ansible/library']
  ansible python module location = /root/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 22 2018, 13:24:18) [GCC 6.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/ansible/library']
```

##### OS / ENVIRONMENT

Docker image alpine 3.7
```
FROM alpine:3.7

RUN echo "===> Installing sudo to emulate normal OS behavior..."  && \
    apk --update add sudo                                         && \
    \
    \
    echo "===> Adding Python runtime..."  && \
    apk --update add python py-pip openssl ca-certificates    && \
    apk --update add --virtual build-dependencies \
    python-dev libffi-dev openssl-dev build-base  && \
    pip install --upgrade pip cffi                            && \
    \
    \
    echo "===> Installing handy tools (not absolutely required)..."  && \
    apk --update add sshpass openssh-client rsync krb5 krb5-dev && \
    \
    \
    echo "===> Installing Ansible..."  && \
    pip install ansible==2.8.4         && \
    \
    \
    echo "===> Installing pip packages ..."  && \
    pip install pywinrm xmltodict kerberos requests_kerberos && \
    \
    \
    echo "===> Removing package list..."  && \
    apk del build-dependencies            && \
    rm -rf /var/cache/apk/*




COPY files/krb5.conf /etc/krb5.conf

ENV PYTHONPATH /ansible/lib
ENV PATH /ansible/bin:$PATH
ENV ANSIBLE_LIBRARY /ansible/library

WORKDIR /ansible-playbook
```

##### STEPS TO REPRODUCE

The below does not work correctly.  Installation of the EXE fails as expected, and log files are **not created** in c:\test.
```yaml
  - name: Install Nuance Speech Suite
    win_package:
      ignore_errors: true
      path: 'C:\Users\user1\AppData\Local\Temp\ansible.vwkx42hj.cab\Nuance Speech Suite 11.0.exe'
      product_id: '{BE8C03C9-A24D-4A76-BF49-D864B3EB1291}'
      chdir: 'C:\Users\user1\AppData\Local\Temp\ansible.vwkx42hj.cab'
      arguments:
      - '/silent'
      - '/log"C:\test\nuance.log"'
      - '/debuglog"C:\test\debuglog.log"'
```

However, if I change the above task to the below--
```yaml
  - name: Install Nuance Speech Suite
    win_package:
      ignore_errors: true
      path: 'C:\Users\user1\AppData\Local\Temp\ansible.vwkx42hj.cab\Nuance Speech Suite 11.0.exe'
      product_id: '{BE8C03C9-A24D-4A76-BF49-D864B3EB1291}'
      chdir: 'C:\Users\user1\AppData\Local\Temp\ansible.vwkx42hj.cab'
      arguments:
      - '/silent /log"C:\test\nuance.log" /debuglog"C:\test\debuglog.log"'
```
This produces log files in the expected destinations.

##### EXPECTED RESULTS

I would expect that installation logs would be created at the given destination c:\temp

##### ACTUAL RESULTS

Installation logs are not created at the proper destination.  In this scenario the EXE installation fails which is expected since we are purposely omitting necessary arguments to force a failure condition.

```paste below
TASK [Install Nuance Speech Suite] ****************************************************************************************************************************************************************************************************************
task path: /ansible/playbooks/tts-playbook.yml:82
<servername> ESTABLISH WINRM CONNECTION FOR USER: user@domain.com on PORT 5985 TO servername
EXEC (via pipeline wrapper)
Using module file /root/.local/lib/python2.7/site-packages/ansible/modules/windows/win_package.ps1
<servername> PUT "/root/.ansible/tmp/ansible-local-1310H4inJm/tmp5XAZHk" TO "C:\Users\user1\AppData\Local\Temp\ansible-tmp-1571416857.73-210446901382243\AnsiballZ_win_package.ps1"
EXEC (via pipeline wrapper)
fatal: [server1]: FAILED! => {
    "changed": false,
    "msg": "unexpected rc from install  C:\\Users\\user1\\AppData\\Local\\Temp\\ansible.vwkx42hj.cab\\Nuance Speech Suite 11.0.exe: see rc, stdout and stderr for more details",
    "rc": 1603,
    "reboot_required": false,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []
}
```

I have turned on ANSIBLE_KEEP_REMOTE_FILES = 1, and the arguments portion of the json dump at the bottom powershell script that is created is shown below--

NOT WORKING 
```yaml
"arguments": ["/silent", "/log\"C:\\test\\nuance.log\"'", "/debuglog\"C:\\test\\debuglog.log\"'"]
```

WORKING
```yaml
 "arguments": ["/silent /log\"C:\\test\\nuance.log\" /debuglog\"C:\\test\\debuglog.log\""]
```
