### ISSUE TITLE
azure_rm_virtualmachine setting "latest" version of image gives inconsistent results. 

### ISSUE THREAD

**Issue by russelljftw** [ansible/ansible#63692]
##### SUMMARY
when creating a new VM, using azure marketplace images, selecting "latest" as the version does not always give the most current version of the image.  In June, it looks like MS changed the naming standard on some of their marketplace images 

if you hardcode the version to the current image it will deploy the specific image.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine.py 
it looks like this function expects the images to always be returned in order, with the most current being last, but with MS name change, the last result is not always the latest.  so the call is only returning the latest version of the old image name.  

```
def get_marketplace_image_version(self):
```

##### ANSIBLE VERSION
Tested on Ansible core 2.8.2 and 2.8.5 

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
no results 
```

##### OS / ENVIRONMENT

image:
        publisher: "MicrosoftWindowsServer"
        offer: "WindowsServer"
        sku: "2016-Datacenter"

##### STEPS TO REPRODUCE

```yaml
    azure_rm_virtualmachine:
      state: present
      resource_group: "rsgname"
      name: "hostname"
      vm_size: "Standard_D2s_v3"
      admin_username: "defaultadmin"
      admin_password: "---password---"
      network_interfaces: "hostname-nic"
      availability_set: "availability-set-001"
      os_type: Windows
      managed_disk_type: Premium_LRS
      image: 
        publisher: "MicrosoftWindowsServer"
        offer: "WindowsServer"
        sku: "2016-Datacenter"
        version: "latest"

```

##### EXPECTED RESULTS

running the following powershell 
$vm = get-azvm -ResourceGroupName rsgname -Name hostname
$vm.StorageProfile.ImageReference

returns 
image version:  14393.3274.1910061629 
(at time of posting).  

##### ACTUAL RESULTS

$vm = get-azvm -ResourceGroupName rsgname -Name hostname
$vm.StorageProfile.ImageReference

returns 
image version 2016.127.20190603

```paste below

```
