### ISSUE TITLE
Allow passing of variables with "import_playbook" to bypass playbook "vars_prompt"

### ISSUE THREAD

**Issue by smacz42** [ansible/ansible#63702]
##### SUMMARY

When a variable is set in a parent playbook, and a child playbook is being imported, even if the variable exists for that server, Ansible prompts for the new variable. There should exist a way that Ansible recognizes that the variable already exists and skip the prompt.

Additionally, when the var is prompted for in the second playbook, whatever it is set to does not override the value that it was set to in the parent play.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Core

### `demo1.yml`
```yaml
---
- hosts: localhost
  connection: local
  tasks:
    - set_fact:
        fact1_prompt: 'fact'

- import_playbook: demo2.yml
  fact1: "{{ fact1_prompt }}"

- hosts: localhost
  connection: local
  tasks:
    - debug:
        var: fact1
```

### `demo2.yml`
```yaml
---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: fact1
      prompt: "Do not prompt for me if I'm already set"
      private: no
  tasks:
    - debug:
        var: fact1
```

## Results

```
$ ansible-playbook -i localhost, playbooks/demo1.yml
Using /home/smacz/Documents/play-compositional/ansible.cfg as config file

PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [set_fact] *******************************************************************************************************
ok: [localhost] => {
    "ansible_facts": {
        "fact1": "fact"
    },
    "changed": false
}
Do not prompt for me if I'm already set: not_fact

PLAY [localhost] ******************************************************************************************************

TASK [debug] **********************************************************************************************************
ok: [localhost] => {
    "fact1": "fact"
}

PLAY [localhost] ******************************************************************************************************

TASK [debug] **********************************************************************************************************
ok: [localhost] => {
    "fact1": "fact"
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Related to https://github.com/ansible/ansible/issues/63365 that was closed so flippantly.

The gist of which should have been:

> Shouldn't variables passed into playbooks be registered as variables rather than completely disposed of?
