### ISSUE TITLE
k8s_facts fails with stdout_callback = selective

### ISSUE THREAD

**Issue by shanxops** [ansible/ansible#63767]
##### SUMMARY
k8s_facts module, shows as FAILED when stdout_callback = selective
A similar issue already exists for older ansible version https://github.com/ansible/ansible/issues/32071

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module: k8s_facts

##### ANSIBLE VERSION

```
ansible 2.8.6
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.7/bin/ansible
  python version = 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) [Clang 6.0 (clang-600.0.57)]
```

The issues exists with both Python 2.x and 3.x

##### UPDATE: ADDITIONAL INFO
This happens only when used with `with_items`. The workaround is to keep it as a separate task and use `with_items` on the `include_task` level

**This will show FAILED** when `stdout_callback=true`
```
# main.yaml 
- name: get a deployment object
  k8s_facts:
    api_version: extensions/v1beta1
    kind: Deployment
    name: "{{ item }}"
    namespace: "{{ kubernetes.namespace}}"
    context: "{{ kubernetes.context }}"
  register: deployed
  with_items: "{{ deployments }}"
```

**Workaround**
```
# k8s_facts.yaml

- name: get a deployment object
  k8s_facts:
    api_version: extensions/v1beta1
    kind: Deployment
    name: "{{ deployment }}"
    namespace: "{{ kubernetes.namespace}}"
    context: "{{ kubernetes.context }}"
  register: deployed
```
```
# main.yaml

- include_tasks: k8s_facts.yaml
  with_items: "{{ deployments }}"
  loop_control:
    loop_var: deployment
```
