### ISSUE TITLE
eos_interfaces: Virtual/loopback interface not getting created when state=overridden

### ISSUE THREAD

**Issue by GomathiselviS** [ansible/ansible#63760]
##### SUMMARY
With state='overridden' new virtual/loopback interface is not getting created . Only the existing interface configs are getting deleted or made to default.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
eos_interfaces.py

##### ANSIBLE VERSION

```ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gosriniv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gosriniv/ansible/lib/ansible
  executable location = /home/gosriniv/ansible/bin/ansible
  python version = 3.6.5 (default, Sep  4 2019, 12:23:33) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]

```

##### OS / ENVIRONMENT
Arista Eos

##### STEPS TO REPRODUCE

```
---
- hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Merge given interface attributes with device configuration
      eos_interfaces:
        config:
          - name: Ethernet1
            enabled: True
          - name: Vlan22
            description: 'Configured by Ansible'
            enabled: False
        state: merged

    - name: Override given interface attributes with device configuration
      eos_interfaces:
        config:
          - name: loopback20
            description: "Virtualinterface20"
        state: overridden



```

##### EXPECTED RESULTS

Along with the existing interfaces getting deleted, the new config should get added.

##### ACTUAL RESULTS

changed: [10.8.38.31] => {
    "after": [
        {
            "enabled": true,
            "name": "Port-Channel2"
        },
        {
            "enabled": true,
            "name": "Port-Channel10"
        },
        {
            "enabled": true,
            "name": "Ethernet1"
        },
        {
            "enabled": true,
            "name": "Ethernet2"
        },
        {
            "enabled": true,
            "name": "Ethernet3"
        },
        {
            "enabled": true,
            "name": "Ethernet4"
        },
        {
            "enabled": true,
            "name": "Ethernet5"
        },
        {
            "enabled": true,
            "name": "Ethernet6"
        },
        {
            "enabled": true,
            "name": "Ethernet7"
        },
        {
            "enabled": true,
            "name": "Loopback911"
        },
        {
            "enabled": true,
            "name": "Management1"
        },
        {
            "enabled": true,
            "name": "Vlan22"
        }
    ],
    "before": [
        {
            "enabled": true,
            "name": "Port-Channel2"
        },
        {
            "enabled": true,
            "name": "Port-Channel10"
        },
        {
            "enabled": true,
            "mtu": "1000",
            "name": "Ethernet1"
        },
        {
            "enabled": true,
            "name": "Ethernet2"
        },
        {
            "enabled": true,
            "name": "Ethernet3"
        },
        {
            "enabled": true,
            "name": "Ethernet4"
        },
        {
            "enabled": true,
            "name": "Ethernet5"
        },
        {
            "enabled": true,
            "name": "Ethernet6"
        },
        {
            "enabled": true,
            "name": "Ethernet7"
        },
        {
            "enabled": true,
            "name": "Loopback911"
        },
        {
            "enabled": true,
            "name": "Management1"
        },
        {
            "description": "Configured by Ansible",
            "enabled": false,
            "name": "Vlan22"
        }
    ],
    "changed": true,
    "commands": [
        "interface Management1",
        "no shutdown",
        "interface Ethernet2",
        "no shutdown",
        "interface Ethernet3",
        "no shutdown",
        "interface Port-Channel2",
        "no shutdown",
        "interface Ethernet1",
        "no shutdown",
        "no mtu",
        "interface Ethernet6",
        "no shutdown",
        "interface Ethernet7",
        "no shutdown",
        "interface Ethernet4",
        "no shutdown",
        "interface Ethernet5",
        "no shutdown",
        "interface Port-Channel10",
        "no shutdown",
        "interface Vlan22",
        "no shutdown",
        "no description",
        "interface Loopback911",
        "no shutdown"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "description": "Virtualinterface20",
                    "name": "loopback20"
                }
            ],
            "state": "overridden"
        }
    }
}
