### ISSUE TITLE
Unarchive should support gzip command to process .gz archives

### ISSUE THREAD

**Issue by johschmitz** [ansible/ansible#63824]
##### SUMMARY
Unarchive should support gzip command to process .gz archives.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
unarchive module

##### ADDITIONAL INFORMATION
Install simple (Go) tools from archives such as https://github.com/jpillora/chisel/releases/download/1.3.1/chisel_linux_arm.gz

```yaml
  - name: Extract Chisel
    unarchive:
      src: https://github.com/jpillora/chisel/releases/download/1.3.1/chisel_linux_arm.gz
      dest: /opt/chisel/bin/
      creates: /opt/chisel/bin/chisel
      remote_src: yes
```
