### ISSUE TITLE
VMware: vmware_guest fails if DC has ESX in maintenance mode

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#63855]
##### SUMMARY

Getting error msg": "Failed to create a virtual machine : The operation is not allowed in the current state of the host."
Creating VM from Template in Datacenter with specified cluster name. Datacenter has 1 cluster with 2 ESX nodes - both running,  and additional 2 nodes outside of cluster both in maintenance mode.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
2.8.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

VCS 6.5
DC with Cluster 
2 ESX nodes in Cluster ( running OK )
2 ESX nodes outside cluster ( both in maintenance mode )

##### STEPS TO REPRODUCE

```yaml
standard playbook - here is a json error result
{
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "invocation": {
        "module_args": {
            "username": "testuser",
            "force": false,
            "customization_spec": null,
            "hardware": {
                "hotadd_memory": true,
                "hotremove_cpu": true,
                "num_cpus": "2",
                "memory_mb": "8********92",
                "hotadd_cpu": true,
                "boot_firmware": "bios",
                "scsi": "paravirtual",
                "num_cpu_cores_per_socket": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "cluster": "DC01-CL01",
            "wait_for_customization": true,
            "customization": {
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "domainadminpassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "orgname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "dns_suffix": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domainadmin": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "autologoncount": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "joindomain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "timezone": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "autologon": true
            },
            "datastore": "DS01********",
            "disk": [],
            "port": 443,
            "wait_for_ip_address": true,
            "uuid": null,
            "customvalues": [],
            "hostname": "testvm********.test.********",
            "is_template": false,
            "networks": [
                {
                    "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "dns_servers": [
                        "********0.********25.********5.********",
                        "********0.********6.********5.7"
                    ],
                    "name": "VLAN_Server",
                    "ip": "********0.********25.********2.********",
                    "netmask": "255.255.255.0",
                    "start_connected": true,
                    "type": "static",
                    "gateway": "********0.********12.6.********"
                }
            ],
            "state": "poweredon",
            "template": "/DC01//vm/Templates/new_template_1",
            "linked_clone": false,
            "folder": "/DC01/vm/",
            "resource_pool": null,
            "snapshot_src": null,
            "convert": null,
            "guest_id": null,
            "name_match": "first",
            "cdrom": {},
            "use_instance_uuid": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "annotation": "TEST",
            "datacenter": "DC01",
            "state_change_timeout": 0,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vapp_properties": [],
            "esxi_hostname": null,
            "validate_certs": false
        }
    },
    "changed": false,
    "msg": "Failed to create a virtual machine : The operation is not allowed in the current state of the host."
}
```

##### EXPECTED RESULTS

Expected to deploy VM on on the ESX nodes in specified cluster. This solution works without any issues on any other DCs with all hosts online

##### ACTUAL RESULTS

"msg": "Failed to create a virtual machine : The operation is not allowed in the current state of the host."

```paste below

```
