### ISSUE TITLE
aws lightsail does not support wait: yes on create

### ISSUE THREAD

**Issue by jillr** [ansible/ansible#63869]
##### SUMMARY
In #63770 it was found that the `wait` specified in the module docs does not apply to create operations.  Wait functions are only defined for `delete_instance`, `restart_instance`, and `startstop_instance`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lightsail

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jill/src/ansible/lib/ansible
  executable location = /home/jill/src/ansible/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```
    - name: Start the instance
      lightsail:
        name: "{{ instance_name }}"
        state: running
        wait: yes
      register: result

    - assert:
        that:
          - result.changed == True
          - result.instance.state.name == 'running'
```

##### EXPECTED RESULTS
test pass

##### ACTUAL RESULTS
assertion failed
