### ISSUE TITLE
netbox_device module fails with custom NetBox slug name

### ISSUE THREAD

**Issue by karlism** [ansible/ansible#63862]
##### SUMMARY
`netbox_device` module fails to add device if it has non-standard slug name

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

netbox_device

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Oct 11 2019, 11:15:58) [Clang 8.0.1 (tags/RELEASE_801/final)]
```

##### CONFIGURATION

```paste below
COLOR_VERBOSE(/home/user/.ansible.cfg) = cyan
DEFAULT_CALLBACK_WHITELIST(/home/user/.ansible.cfg) = ['timer']
DEFAULT_HASH_BEHAVIOUR(/home/user/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/ansible/library/netbox/netbox.py']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/user/.ansible/vault_pass
```

##### OS / ENVIRONMENT

OpenBSD 6.6 amd64

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: False

  tasks:
    - netbox_device:
        netbox_url: "https://netbox.example.com/"
        netbox_token: "XXX"
        state: present
        data:
          name: "ansibletest1"
          device_role: "Cable Management"
          device_type: "Unknown"
          site: "Example"
          comment: "device with '-' in slug"

    - netbox_device:
        netbox_url: "https://netbox.example.com/"
        netbox_token: "XXX"
        state: present
        data:
          name: "ansibletest2"
          device_role: "VM Guest"
          device_type: "Unknown"
          site: "Example"
          comment: "device with '_' in slug"
```
Related NetBox objects are following:
```
        {
            "id": 16,
            "name": "Cable Management",
            "slug": "cable-management",
            "color": "795548",
            "vm_role": true,
            "device_count": 24,
            "virtualmachine_count": null
        },
        {
            "id": 18,
            "name": "VM Guest",
            "slug": "vm_guest",  # <- note that "-" is replaced with "_" here
            "color": "aa1409",
            "vm_role": true,
            "device_count": 115,
            "virtualmachine_count": null
        },
```

##### EXPECTED RESULTS

I would expect `netbox_device` module to work with any slug name.

##### ACTUAL RESULTS

`netbox_device` module fails when NetBox slug value is modified, as it takes given value, changes it to lowercase and replaces spaces to dashes.

```paste below
Using /home/user/.ansible.cfg as config file

PLAY [localhost] ***************************************************************************************************************

TASK [netbox_device] ***********************************************************************************************************
changed: [localhost] => {"changed": true, "device": {"asset_tag": null, "cluster": null, "comments": "", "config_context": {}, "created": "2019-10-23", "device_role": 16, "device_type": 48, "display_name": "ansibletest1", "face": null, "id": 1094, "last_updated": "2019-10-23T15:02:38.424536Z", "local_context_data": null, "name": "ansibletest1", "parent_device": null, "platform": null, "position": null, "primary_ip": null, "primary_ip4": null, "primary_ip6": null, "rack": null, "serial": "", "site": 13, "status": 1, "tags": [], "tenant": null, "vc_position": null, "vc_priority": null, "virtual_chassis": null}, "msg": "Device ansibletest1 created"}

TASK [netbox_device] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not resolve id of device_role: vm-guest"}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
