### ISSUE TITLE
ansible_loop_var is undefined in include_role.name

### ISSUE THREAD

**Issue by seblu** [ansible/ansible#63865]
##### SUMMARY
The  `ansible_loop_var` is reported undefined in include_role.name

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/seblu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Oct  4 2019, 06:57:26) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Arch Linux

##### STEPS TO REPRODUCE

Inventory:
```ini
foo
bar
```

Playbooks:
```yaml
- hosts: all
  gather_facts: false
  tasks:
    - debug: var=ansible_loop_var
      loop: ['a', 'b', 'c']
      loop_control:
        loop_var: bob
    - include_role:
        name: "{{ lookup('vars', ansible_loop_var) }}"
      loop: ['a', 'b', 'c']
      loop_control:
        loop_var: bob
```

##### EXPECTED RESULTS
We should be able to use `ansible_loop_var` as role name to include.

##### ACTUAL RESULTS

```paste below
PLAY [all] ******************************************************************************************************************************************************************

TASK [debug] ****************************************************************************************************************************************************************
ok: [foo] => (item=a) => {
    "ansible_loop_var": "bob",
    "bob": "a"
}
ok: [foo] => (item=b) => {
    "ansible_loop_var": "bob",
    "bob": "b"
}
ok: [foo] => (item=c) => {
    "ansible_loop_var": "bob",
    "bob": "c"
}
ok: [bar] => (item=a) => {
    "ansible_loop_var": "bob",
    "bob": "a"
}
ok: [bar] => (item=b) => {
    "ansible_loop_var": "bob",
    "bob": "b"
}
ok: [bar] => (item=c) => {
    "ansible_loop_var": "bob",
    "bob": "c"
}

TASK [include_role : {{ lookup('vars', ansible_loop_var) }}] ****************************************************************************************************************
ERROR! 'ansible_loop_var' is undefined

```
