### ISSUE TITLE
VMWare Host Service Manager Shows Service Started, but Service Remains Down

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#63876]
##### SUMMARY

When attempting to start the TSM-SSH, the vmware_host_service_manager module reports a "changed" status with a state set to "start". Following up with the associated facts module and checking vCenter reports the service is still down.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host_service_manager.py

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
```

##### STEPS TO REPRODUCE

```yaml
    - name: Enable TSM-SSH service
      vmware_host_service_manager:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
        service_name: TSM-SSH
        state: start
        service_policy: off
      delegate_to: localhost

    - name: Gather facts about esxi hosts
      vmware_host_service_facts:
        esxi_hostname: "{{ esxi_hostname }}"
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      delegate_to: localhost
```

##### EXPECTED RESULTS

The service shown as started should remain in a start or running state on the fact task

##### ACTUAL RESULTS

```paste below
TASK [Enable TSM-SSH service] **************************************************
[...]
changed: [vcenterhost.domain.com -> localhost] => {
    "ansible_module_results": {
        "host.domain.com": {
            "actual_service_policy": "off", 
            "actual_service_state": "stopped", 
            "changed": true, 
            "desired_service_policy": "off", 
            "desired_service_state": "start", 
            "error": "", 
            "service_name": "TSM-SSH"
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "cluster_name": null, 
            "esxi_hostname": "host.domain.com", 
            "hostname": "vcenterhost.domain.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "service_name": "TSM-SSH", 
            "service_policy": "off", 
            "state": "start", 
            "username": "user.name-1", 
            "validate_certs": false
        }
    }
}
[...]
TASK [Gather facts about esxi hosts] *******************************************
[...]
            {
                "key": "TSM-SSH", 
                "label": "SSH", 
                "policy": "off", 
                "required": false, 
                "running": false, 
                "source_package_desc": "This VIB contains all of the base functionality of vSphere ESXi.", 
                "source_package_name": "esx-base", 
                "uninstallable": false
            },
[...]
```
