### ISSUE TITLE
iam_role: support for adding tags to iam role

### ISSUE THREAD

**Issue by h35gao** [ansible/ansible#63874]
##### SUMMARY

iam_role does not have support for adding tags to the iam role

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

iam_role

##### ADDITIONAL INFORMATION

It would be nice if we can add tags to the iam role when we create it using iam_role.
Something similar to ec2_instance would be great

```yaml
- name: "Create a role and attach a managed policy called 'PowerUserAccess'"
  iam_role:
    name: mynewrole
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    managed_policy:
      - arn:aws:iam::aws:policy/PowerUserAccess
    tags:
      Owner: Dev
      Environment: Testing
```
