### ISSUE TITLE
"hosts: WEB[:1]" doesn't work to address any one of the server in the group

### ISSUE THREAD

**Issue by tomgoto** [ansible/ansible#6388]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.0, 1.5.1
##### Environment:

CentOS 6.4/6.5
##### Summary:

I've been using [:(number)] in hosts section of playbook so that I can limit the number of server to run.
It works in Ansible 1.4.3 (CentOS yum package), but not in Ansible 1.5.0 or 1.5.1.
Probably it is related to [issue 6331](https://github.com/ansible/ansible/issues/6331). 
##### Steps To Reproduce:

inventory file: 

```
[WEB]
API
WEB
DATABASE
```

playbook: 

```

---
- name: issue test
  hosts: WEB[:1]
  gather_facts: yes
  sudo: yes

  tasks:
    - name: gather the latest facts
      action: setup
```
##### Expected Results:

Playbook runs in any one of the  [WEB] server group. 

```
PLAY [issue test] *************************************************************

GATHERING FACTS ***************************************************************
ok: [API]

```
##### Actual Results:

```
PLAY [issue test] *************************************************************
skipping: no hosts matched
```
