### ISSUE TITLE
os_server module fails while creating instance on get_hostvars_from_server

### ISSUE THREAD

**Issue by FilipB** [ansible/ansible#63894]
##### SUMMARY

_exit_hostvars fails on get_hostvars_from_server with "flavor_id = server['flavor']['id']\nKeyError: 'id'"

It's because the flavor field does not contain 'id':
'flavor': Munch({u'vcpus': 2, u'disk': 40, u'extra_specs': {u'aggregate_instance_extra_specs:server_type:aggregate': u'general'}, u'swap': 0, u'original_name': u'm1.medium', u'ram': 4096, u'ephemeral': 0})

Full server dict looks like this:
Munch({'vm_state': u'active', 'disk_config': u'MANUAL', 'addresses': Munch({u'provider_net_cci_7': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:6d:a4:0e', u'version': 4, u'addr': u'10.0.96.184', u'OS-EXT-IPS:type': u'fixed'}]}), 'server_groups': None, 'terminated_at': None, 'os-extended-volumes:volumes_attached': [], 'image': Munch({'id': u'33543771-9453-4da2-bcbb-abd01d84b89a'}), 'ramdisk_id': None, 'user_data': None, 'OS-EXT-SRV-ATTR:user_data': None, 'OS-EXT-STS:task_state': None, 'OS-EXT-STS:vm_state': u'active', 'OS-EXT-SRV-ATTR:instance_name': None, 'OS-EXT-SRV-ATTR:root_device_name': None, 'OS-SRV-USG:launched_at': u'2019-10-24T04:20:45.000000', 'flavor': Munch({u'vcpus': 2, u'disk': 40, u'extra_specs': {u'aggregate_instance_extra_specs:server_type:aggregate': u'general'}, u'swap': 0, u'original_name': u'm1.medium', u'ram': 4096, u'ephemeral': 0}), 'az': u'nova', 'reservation_id': None, 'id': u'2011940c-551b-49ac-bd88-f780fc8b60eb', 'security_groups': [Munch({u'name': u'ocp4-load-balancer'}), Munch({u'name': u'SimpleHTTPServer'}), Munch({u'name': u'default'})], 'scheduler_hints': None, 'instance_name': None, 'user_id': u'3d2d7de52855717a544f11cbfb9771419519ba090103f76cfa04d93245af5bfb', 'OS-EXT-SRV-ATTR:hostname': None, 'hostname': None, 'OS-DCF:diskConfig': u'MANUAL', 'OS-EXT-SRV-ATTR:reservation_id': None, 'networks': {}, 'accessIPv4': u'10.0.96.184', 'accessIPv6': '', 'location': Munch({'project': Munch({'domain_id': None, 'id': u'0d9514d7da8441a199c33a296e541a7a', 'name': 'istio-dev', 'domain_name': None}), 'cloud': 'defaults', 'region_name': '', 'zone': u'nova'}), 'power_state': 1, 'public_v4': u'10.0.96.184', 'progress': 0, 'OS-EXT-STS:power_state': 1, 'interface_ip': u'10.0.96.184', 'launched_at': u'2019-10-24T04:20:45.000000', 'OS-SRV-USG:terminated_at': None, 'metadata': Munch({}), 'status': u'ACTIVE', 'OS-EXT-SRV-ATTR:ramdisk_id': None, 'updated': u'2019-10-24T04:20:45Z', 'hostId': u'8bf1ff9d253087c08c489db79f8038e336f4149fb3305640d3164f7b', 'OS-EXT-SRV-ATTR:host': None, 'description': u'fbr-oco41-t-services', 'block_device_mapping': None, 'kernel_id': None, 'key_name': u'kiali-qe', 'public_v6': '', 'hypervisor_hostname': None, 'private_v4': '', 'host': None, 'OS-EXT-SRV-ATTR:kernel_id': None, 'OS-SCH-HNT:scheduler_hints': None, 'host_id': u'8bf1ff9d253087c08c489db79f8038e336f4149fb3305640d3164f7b', 'task_state': None, 'properties': Munch({'OS-EXT-STS:task_state': None, 'OS-EXT-SRV-ATTR:user_data': None, 'OS-EXT-STS:vm_state': u'active', 'OS-EXT-SRV-ATTR:instance_name': None, 'OS-EXT-SRV-ATTR:root_device_name': None, 'OS-SRV-USG:launched_at': u'2019-10-24T04:20:45.000000', 'os-extended-volumes:volumes_attached': [], 'OS-EXT-SRV-ATTR:hostname': None, 'OS-DCF:diskConfig': u'MANUAL', 'OS-SCH-HNT:scheduler_hints': None, 'OS-EXT-STS:power_state': 1, 'OS-EXT-AZ:availability_zone': u'nova', 'OS-EXT-SRV-ATTR:ramdisk_id': None, 'OS-EXT-SRV-ATTR:host': None, 'OS-SRV-USG:terminated_at': None, 'OS-EXT-SRV-ATTR:reservation_id': None, 'OS-EXT-SRV-ATTR:kernel_id': None, 'OS-EXT-SRV-ATTR:hypervisor_hostname': None, 'locked': False, 'OS-EXT-SRV-ATTR:launch_index': None, 'host_status': None, 'trusted_image_certificates': None}), 'tags': [], 'OS-EXT-AZ:availability_zone': u'nova', 'host_status': None, 'project_id': u'0d9514d7da8441a199c33a296e541a7a', 'OS-EXT-SRV-ATTR:hypervisor_hostname': None, 'name': u'fbr-oco41-t-services', 'OS-EXT-SRV-ATTR:launch_index': None, 'adminPass': None, 'tenant_id': u'0d9514d7da8441a199c33a296e541a7a', 'created_at': u'2019-10-24T04:20:22Z', 'created': u'2019-10-24T04:20:22Z', 'launch_index': None, 'locked': False, 'has_config_drive': False, 'trusted_image_certificates': None, 'root_device_name': None, 'volumes': [], 'cloud': 'defaults', 'personality': None, 'config_drive': u'', 'region': ''})

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module: os_server

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fbrychta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 30
openstacksdk-0.36.0
openstack 13

##### STEPS TO REPRODUCE

Try to create new instance

```yaml
- name: Create services VM
  os_server:
    auth:
      auth_url: https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000/v3/
      username: "{{ psi_user }}"
      password: "{{ psi_passwd }}"
      project_name: "{{ psi_project }}"
      os_default_domain_name: redhat.com
    state: present
    timeout: 500
    name: "{{ cluster_name }}-services"
    image: "{{ psi_services_image_name }}"
    key_name: "kiali-qe"
    security_groups: "default,SimpleHTTPServer,ocp4-load-balancer"
    network: "{{ psi_network }}"
    flavor: "{{ psi_services_vm_flavor }}"
    wait: yes
    auto_ip: true
  register: instance
- name: Add it to inventory
  add_host:
    name: "{{ instance.server.name }}"
    ansible_host: "{{ instance.server.public_v4 }}"
    groups: "services_vms"
    ansible_user: cloud-user
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
```

##### EXPECTED RESULTS

The server is created without error.

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/home/fbrychta/.ansible/tmp/ansible-tmp-1571902237.7902298-18633730260520/AnsiballZ_os_server.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/fbrychta/.ansible/tmp/ansible-tmp-1571902237.7902298-18633730260520/AnsiballZ_os_server.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/fbrychta/.ansible/tmp/ansible-tmp-1571902237.7902298-18633730260520/AnsiballZ_os_server.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fbrychta/.ansible/tmp/ansible-tmp-1571902237.7902298-18633730260520/AnsiballZ_os_server.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/home/fbrychta/work/repo/kiali-qe-utils/openshift/cluster-installation/psi/venv/lib64/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/home/fbrychta/work/repo/kiali-qe-utils/openshift/cluster-installation/psi/venv/lib64/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_os_server_payload_e2t4ektx/__main__.py\", line 753, in <module>\n  File \"/tmp/ansible_os_server_payload_e2t4ektx/__main__.py\", line 743, in main\n  File \"/tmp/ansible_os_server_payload_e2t4ektx/__main__.py\", line 669, in _get_server_state\n  File \"/tmp/ansible_os_server_payload_e2t4ektx/__main__.py\", line 417, in _exit_hostvars\n  File \"/home/fbrychta/work/repo/kiali-qe-utils/openshift/cluster-installation/psi/venv/lib/python3.7/site-packages/openstack/cloud/_compute.py\", line 1889, in get_openstack_vars\n    return meta.get_hostvars_from_server(self, server)\n  File \"/home/fbrychta/work/repo/kiali-qe-utils/openshift/cluster-installation/psi/venv/lib/python3.7/site-packages/openstack/cloud/meta.py\", line 487, in get_hostvars_from_server\n    flavor_id = server['flavor']['id']\nKeyError: 'id'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
