### ISSUE TITLE
Templating seems to not follow the standard rules when including files

### ISSUE THREAD

**Issue by KoenraadM** [ansible/ansible#63900]
##### SUMMARY
When adding `..` in a variable name that holds the path of a file to be included while running templates, the build fails with `TemplateNotFound`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- Templating?

##### ANSIBLE VERSION
```
ansible 2.7.0rc4
  config file = /xxx/xxx/xxx/operations/ansible/ansible.cfg
  configured module search path = [u'/xxx/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:46:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
```
  ANSIBLE_PIPELINING(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = True
  ANSIBLE_SSH_ARGS(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=30m
  DEFAULT_HOST_LIST(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = [u'/xxx/xxx/xxx/operations/ansible/inventory']
  DEFAULT_JINJA2_EXTENSIONS(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.with_
  DEFAULT_ROLES_PATH(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = [u'/xxx/xxx/xxx/operations/ansible/roles']
  HOST_KEY_CHECKING(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = False
  RETRY_FILES_ENABLED(/xxx/xxx/xxx/operations/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

We use this snippet to generate large Vhost files for our Nginx
```
{% for site in sites -%}
    {% with item = site %}
        {% include vhost_config_template %}
    {% endwith %}
{% endfor %}
```

Document structure:
```yml
inventory/
    random-servers/
        group_vars/
            random-servers.yml
            random-servers-something.yml
            random-servers-stats.yml
        random-servers.yml
playbooks/
    random-servers/
        files/
            groups/
                random-servers/
                    nginx/
                        vhost.conf.j2
                random-servers-stats/
                    .gitkeep
                random-servers-something/
                    .gitkeep
        random-servers.yml
roles/
    ... not relevant
```

```yml
# inventory/random-servers/random-servers.yml
random-servers:
  children:
    random-servers-stats:
      hosts:
        192.168.x.x:
    random-servers-something:
      hosts:
        192.168.x.x:
```

```yml
# inventory/random-servers/group_vars/random-server.yml
---
# Group Settings
group: random-servers
group_files: "files/groups/{{ group }}"

# Nginx
vhost_config_template: "{{ group_files }}/../random-servers/nginx/vhost.conf.j2"
```

```yml
# inventory/random-servers/group_vars/random-server-stats.yml
---
# Group Settings
group: random-servers-stats

# Nginx
sites:
  - server_name: "some.example.com"
```

As you can see everything relies heavily on the group and the group hierarchy. Because of this it makes sense for children of a group to find their templates and files in the parent's location (not always but again group hierarchy allows more explicitly defined groups to override everything anyway).

This specifically highlights: `vhost_config_template: "{{ group_files }}/../random-servers/nginx/vhost.conf.j2"`. What I expect it to do (when loaded into the top snippet), is to find my `vhost.conf.j2` file in `playbooks/random-servers/files/groups/random-servers/nginx/vhost.conf.j2`. Instead I get:

```
fatal: [192.168.x.x]: FAILED! => {
    "changed": false, 
    "msg": "TemplateNotFound: files/groups/random-servers-stats/../random-servers/nginx/vhost.conf.j2"
}
```

Following things are things we have employed for years:
- `vhost_config_template: "{{ group_files }}/nginx/vhost.conf.j2"` points correctly to `playbooks/random-servers/files/groups/random-servers-stats/nginx/vhost.conf.j2`
- `vhost_config_template: "{{ group_files }}/./nginx/vhost.conf.j2"` while useless, points correctly to `playbooks/random-servers/files/groups/random-servers-stats/nginx/vhost.conf.j2`
- the following case:

```yml
- name: copy Keepalived configuration
  template:
    src: "{{ keepalived_config_template }}"
    dest: "{{ keepalived_config_file_path }}"
  notify:
    - restart keepalived
```

with the following config `keepalived_config_template: "{{ group_files }}/../haproxies-parent-group/keepalived.conf"` also correctly will find the correct file in `playbooks/haproxies/files/groups/haproxies-parent-group/keepalived.conf`, while `group: haproxies-child`

# Question
I was wondering why everything seems to work as expected, but when there is a `..` in the file|template location, everything just stops working. I read some things about correct scoping and security on threads from people with similar problems ... but I don't think it makes any sense that I'm not allowed to go to a parent directory that I'm clearly allowed to access if I went straight to it.

I also couldn't find anything interesting in the log for `-vvvvv`, I assume this is because it fails within a template rather than failing inside the main job, but I'm just guessing.
