### ISSUE TITLE
openssh_keypair handles encrypted key files poorly

### ISSUE THREAD

**Issue by thomwiggers** [ansible/ansible#63910]
##### SUMMARY

`openssh_keypair` handles encrypted key files poorly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssh_keypair

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /home/thom/git/dotfiles-ansible/ansible.cfg
  configured module search path = ['/home/thom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Oct  4 2019, 06:57:26) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/thom/git/dotfiles-ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/thom/git/dotfiles-ansible/ansible.cfg) = ['/home/thom/git/dotfiles-ansible/hosts']
DEFAULT_MANAGED_STR(/home/thom/git/dotfiles-ansible/ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}
host: {host}
```

##### OS / ENVIRONMENT

Arch Linux

```OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019```

##### STEPS TO REPRODUCE

```yaml
  - name: Obtain keyfile from this machine                                          
    openssh_keypair:                                                                
      path: "/tmp/sshkey"
      type: ed25519
```
I'm using ed25519 because it's independent of `size`; not sure if it also happens with eg. RSA.

0. Generate ``/tmp/sshkey`` using ``ssh-keygen -t ed25519 -f /tmp/sshkey -N password``
1. Run the above playbook, observe it marks it as `changed`.
2. Observe ``/tmp/sshkey.pub`` is now empty. 
3. Run it again, it's `changed` again
4. It has now replaced the SSH key and the public key is now correct.

##### EXPECTED RESULTS

1. Either give me an error about encrypted `.ssh` files already existing or properly replace it.
