### ISSUE TITLE
Implement datastore cluster as vmware_vmotion destination datastore

### ISSUE THREAD

**Issue by ellingtonsantos** [ansible/ansible#63913]
##### SUMMARY
Accept a datastore cluster as a destination datastore in vmware_vmotion

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_vmotion

##### ADDITIONAL INFORMATION
Set a datastore cluster in destination_datastore in vmware_vmotion migrates VM to this datastore cluster.
```yaml
- name: Migrate VM to datastore
  vmware_vmotion:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    vm_name: "{{ inventory_hostname }}"
    destination_datastore: "{{ vm_datastore_cluster }}"
  delegate_to: localhost
```
