### ISSUE TITLE
FR: Allow role authors to control when transitive dependencies are run after download

### ISSUE THREAD

**Issue by lhazlewood** [ansible/ansible#63923]
##### SUMMARY

When running a playbook, it is impossible to control when transitive role dependencies execute, and in what order.

The commonly suggested technique of using tags in the dependency metadata also does not work, as will be explained below.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible, perhaps ansible galaxy

##### ADDITIONAL INFORMATION

Consider the following playbook with dependencies (and transitive dependencies) example:

###### playbook `tasks/main.yml`:
```yaml
# ...
  tasks:
    # ... etc ...
    - import_role: name=role_a
    # ... etc ...
```

`role_a` is defined in the playbook repo's `requirements.yml` and successfully installed locally by running `ansible-playbook -r requirements.yml`

Now assume `role_a` has the following relevant parts of metadata and tasks files:

###### role_a `meta/main.yml`

```yaml
# ... etc
dependencies:
  - src: https://github.com/whatever/role_bar
    name: role_bar
  - src: https://github.com/whatever/role_foo
    name: role_foo
```

###### role_a `tasks/main.yml`

```yaml
- name: Step 1. Do some prep work before running foo
  # ...
- name: Step 2. Run foo
  import_role: name=role_foo
- name: Step 3. Do some post-role clean up and some other prep work
  # ...
- name: Step 3. Run bar
  import_role: name=role_bar
- name: Step 4. Do some final work
  # ... 
```

##### PROBLEM

When one calls `ansible-galaxy install -r requirements.yml`, the playbook's immediate dependency `role_a` is downloaded, as well as `role_a`'s dependencies `role_foo` and `role_bar`.  That's great! And expected.

HOWEVER, when the playbook is run, e.g. `ansible-playbook ... playbook.yml`, **it is impossible to guarantee the ordered execution flow for the tasks and role imports defined in `role_a`'s `tasks/main.yml` file**.

Calling `ansible-playbook` will *always* run `role_foo` and `role_bar` **first**, _before_ running `role_a`. This is incorrect because `role_a` is explictly taking control over what roles to run, and exactly _when_ they should be run, interleaved between various steps in its `tasks/main.yml` file.

Additionally, when running a playbook, the user should *only* be concerned with the immediate roles declared in `requirements.yml`.  The user should not be concerned about transitive roles (or transitive transitive roles, etc) at all as this completely breaks encapsulation and chain of responsibility.

As a result, today a playbook user is forced instead to look in every single transitive (and down the chain) dependency for every role, copy-and-paste all found dependency metadata in each found role, and manually put it all in the single `playbook.yml` file.  Even then, that doesn't work because a role's `meta/main.yml` `dependencies` list forces 'run all these roles before me' behavior no matter what.  Role authors have no control over what happens and in what order. 

This is a significant pain, and effectively eliminates the ability to build up a nice registry of composable roles that can be used in other roles and/or playbooks without imposing undue overhead.

###### What about tags?

Tags have been suggested in other GitHub Issue comments as a way to solve this problem.  For example, in a role's `meta/main.yml` file, declare a tag that would never be used to trigger exclusion logic (as suggested by this [stackoverflow answer](https://stackoverflow.com/questions/57581363/ansible-role-dependencies-install-but-dont-run-yet-how)):

```yaml
dependencies: 
  - src: https://github.com/whatever/role_foo
    scm: git
    tags: [never]   # <-- key part

```

But as described in that SO answer, this only works in special conditions and fails in others - i.e. it is frail and unreliable and cannot be used as a foundational technique.

For example, in the above `playbook.yml`, if the playbook author decides to assign a tag to `role_at` as follows:

```yaml

- import_role: name=role_a
  tags: mytag

```

If the playbook is run with `--tags mytag`, then `role_a` will be run, but `role_a`'s _dependencies will be run first because of ansible tag inheritance_.  That is, `role_foo` and `role_bar` are also implicitly tagged as `mytag` and therefore existing 'run first before role_a' logic executes, again violating the `role_a` author's intent to control when and how it's dependency roles execute.

##### PROPOSAL

Because of breaking encapsulation, forcing unnecessary burden on playbook authors, preventing role authors from specifying execution order, and preventing a composable library/registry of roles that can include other roles, I'm asking the ansible team to add another property to a`meta/main.yml` file's `dependencies` list items that allows a role author to override ansible automatic execution of dependency roles when required.  This would be backwards compatible because it's a new property and won't effect any existing dependency declarations, retaining current behavior.

###### Example `meta/main.yml`

```yaml
# ... etc ...
dependencies:
  - src: geerlingguy.whatever                  # runs before the including role, retaining current behavior
  - src: https://github.com/whatever/role_foo
    run: false                                 # Role author indicating they'll call the role when necessary
                                               # A value of 'auto' or `first` would be the current behavior. 
                                               # Perhaps other values could be allowed in the future if desired.
```
(`run` is just an example suggested property name - any suitable name the ansible team things best).

Both roles would still be downloaded as expected by `ansible-galaxy`, which is always required, but the role author indicates that they're taking over as to _when_ one of the roles should be run.

I had originally thought of asking for support for a new file in `meta/requirements.yml` that galaxy could use for 'download only' (and not run) roles, but that's not a good solution - dependency metadata should not be spread out in multiple locations and `meta/main.yml`'s `dependencies` property should be the only/canonical definition - otherwise maintenance and reference of dependency metadata is difficult and potentially error-prone.

Because of the above list of problems and that tags are insufficient, can you please add this feature?  It's a big missing link in attempting to rich build a library of composable roles.

Thank you for your consideration!
