### ISSUE TITLE
azure_rm_sqldatabase ignores edition variable during database copy

### ISSUE THREAD

**Issue by borncamp** [ansible/ansible#63927]
##### SUMMARY
I have a playbook that creates a copy of a database from one azure sql database to another. The original database is of the "Basic" tier. I am trying to create a new copy under the "Standard" tier on another server. The database is created fine, however the edition variable seems to be ignored during creation.

e.g. My intended result:
SQLDBServerA - DB123 - Basic Tier
COPY TO
SQLDBServerB - DB123 - Standard Tier

My actual result:
SQLDBServerA - DB123 - Basic Tier
COPY TO
SQLDBServerB - DB123 - Basic Tier

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_sqldatabase

##### ANSIBLE VERSION

```
ansible --version
ansible 2.8.4
  config file = None
  configured module search path = ['/home/username-not-real/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```
ACTION_WARNINGS(default) = True
AGNOSTIC_BECOME_PROMPT(default) = True
ALLOW_WORLD_READABLE_TMPFILES(default) = False
ANSIBLE_CONNECTION_PATH(default) = None
ANSIBLE_COW_PATH(default) = None
ANSIBLE_COW_SELECTION(default) = default
ANSIBLE_COW_WHITELIST(default) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake',ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
ANSIBLE_SSH_ARGS(default) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(default) = None
ANSIBLE_SSH_CONTROL_PATH_DIR(default) = ~/.ansible/cp
ANSIBLE_SSH_EXECUTABLE(default) = ssh
ANSIBLE_SSH_RETRIES(default) = 0
ANY_ERRORS_FATAL(default) = False
BECOME_ALLOW_SAME_USER(default) = False
BECOME_PLUGIN_PATH(default) = ['/home/user-name-not-real/.ansible/plugins/become', '/usr/share/ansible/plugins/become']
CACHE_PLUGIN(default) = memory
CACHE_PLUGIN_CONNECTION(default) = None
CACHE_PLUGIN_PREFIX(default) = ansible_facts
CACHE_PLUGIN_TIMEOUT(default) = 86400
COLLECTIONS_PATHS(default) = ['/home/user-name-not-real/.ansible/collections', '/usr/share/ansible/collections']
COLOR_CHANGED(default) = yellow
COLOR_CONSOLE_PROMPT(default) = white
COLOR_DEBUG(default) = dark gray
COLOR_DEPRECATE(default) = purple
COLOR_DIFF_ADD(default) = green
COLOR_DIFF_LINES(default) = cyan
COLOR_DIFF_REMOVE(default) = red
COLOR_ERROR(default) = red
COLOR_HIGHLIGHT(default) = white
COLOR_OK(default) = green
COLOR_SKIP(default) = cyan
COLOR_UNREACHABLE(default) = bright red
COLOR_VERBOSE(default) = blue
COLOR_WARN(default) = bright purple
COMMAND_WARNINGS(default) = True
CONDITIONAL_BARE_VARS(default) = True
CONNECTION_FACTS_MODULES(default) = {'eos': 'eos_facts', 'frr': 'frr_facts', 'ios': 'ios_facts', 'iosxr': 'iosxr_factDEFAULT_ACTION_PLUGIN_PATH(default) = ['/home/username-not-real/.ansible/plugins/action', '/usr/share/ansible/plugins/action'DEFAULT_ALLOW_UNSAFE_LOOKUPS(default) = False
DEFAULT_ASK_PASS(default) = False
DEFAULT_ASK_SUDO_PASS(default) = False
DEFAULT_ASK_SU_PASS(default) = False
DEFAULT_ASK_VAULT_PASS(default) = False
DEFAULT_BECOME(default) = False
DEFAULT_BECOME_ASK_PASS(default) = False
DEFAULT_BECOME_EXE(default) = None
DEFAULT_BECOME_FLAGS(default) =
DEFAULT_BECOME_METHOD(default) = sudo
DEFAULT_BECOME_USER(default) = root
DEFAULT_CACHE_PLUGIN_PATH(default) = ['/home/user-name-not-real/.ansible/plugins/cache', '/usr/share/ansible/plugins/cache']
DEFAULT_CALLABLE_WHITELIST(default) = []
DEFAULT_CALLBACK_PLUGIN_PATH(default) = ['/home/user-name-not-real/.ansible/plugins/callback', '/usr/share/ansible/plugins/calDEFAULT_CALLBACK_WHITELIST(default) = []
DEFAULT_CLICONF_PLUGIN_PATH(default) = ['/home/user-name-not-real/.ansible/plugins/cliconf', '/usr/share/ansible/plugins/clicoDEFAULT_CONNECTION_PLUGIN_PATH(default) = ['/home/user-name-not-real/.ansible/plugins/connection', '/usr/share/ansible/plugins
```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

Create an azure sql database server with a basic edition database, then run an ansible playbook like the one I've included to create a new sql database server and a copy of the database at a different edition.  

```
#relevant sections extracted
---
- name: Create Azure SQLDB
  hosts: localhost
  connection: local
  vars_files:
    - params.yml
    - secret-params.yml
  tasks:
  - name: Create (or update) SQL Database Server
    azure_rm_sqlserver:
      resource_group: "{{ resource_group_name }}"
      name: "{{ build_number }}-db"
      admin_username: "{{ databaseadminusername }}"
      admin_password: "{{ databaseadminpassword }}"
      location: centralus
    register: database_output
- name: Create a database copy from a Basic DB to a Standard DB on a different DB Server
 #    async: 1200
 #    poll: 0
     register: db_copy_bc
     azure_rm_sqldatabase:
       resource_group: "{{ resource_group_name }}"
       server_name: "{{ build_number }}-db"
       name: "{{ build_number }}_ApplicationName"
       location: centralus
       create_mode: copy
       edition: standard
       source_database_id: "/subscriptions/xxx-not-real-xxx/resourceGroups/xxx-not-real-xxx/providers/Microsoft.Sql/servers/xxx-not-real-xxx/databases/xxx-not-real-xxx"
```

##### EXPECTED RESULTS

I expect to have a database on the newly created database server with the "standard" size.

##### ACTUAL RESULTS

```TASK [ Create a database copy from a Basic DB to a Standard DB on a different DB Server] *************************
task path: /opt/agent1/_work/1/s/orchestration/database.yml:59
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: username-not-real
<localhost> EXEC /bin/sh -c 'echo ~username-not-real && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384 `" && echo ansible-tmp-1571945212.265195-225757976489384="` echo /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/cloud/azure/azure_rm_sqldatabase.py
<localhost> PUT /home/username-not-real/.ansible/tmp/ansible-local-1043095uzy67zd/tmpzx1glcbk TO /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/AnsiballZ_azure_rm_sqldatabase.py
<localhost> PUT /home/username-not-real/.ansible/tmp/ansible-local-1043095uzy67zd/tmprvubzwgj TO /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/async_wrapper.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/ /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/AnsiballZ_azure_rm_sqldatabase.py /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/async_wrapper.py && sleep 0'<localhost> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python3 /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/async_wrapper.py 352138147732 1200 /home/username-not-real/.ansible/tmp/ansible-tmp-1571945212.265195-225757976489384/AnsiballZ_azure_rm_sqldatabase.py _ && sleep 0'
changed: [localhost] => {
    "ansible_job_id": "352138147732.104797",
    "changed": true,
    "finished": 0,
    "results_file": "/home/username-not-real/.ansible_async/352138147732.104797",
    "started": 1
}
Read vars_file 'params.yml'
Read vars_file 'secret-params.yml'
```
