### ISSUE TITLE
Add Redfish commands to perform updates

### ISSUE THREAD

**Issue by mraineri** [ansible/ansible#63925]
##### SUMMARY

Add new commands to the Redfish remote_management modules to perform firmware update requests.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

redfish_config.py
redfish_utils.py

##### ADDITIONAL INFORMATION

Operators need a way to update firmware on Redfish managed systems. Would like an extension made to be able to perform SimpleUpdate actions with a specified firmware image. At the very minimum we can point to a remote HTTP/TFTP/SCP/etc server, but if possible, it might be good to spin up a lightweight HTTP server to service the request in case one isn't provisioned.

```yaml
  - name: Pull style update
    redfish_config:
      category: Update
      command: PullUpdate
      image: http://my.file.repo/someimage.bin
      targets:
        - /redfish/v1/Systems/1
        - /redfish/v1/Systems/2
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
```
