### ISSUE TITLE
lineinfile apparently matches the line before insertafter value in loop.

### ISSUE THREAD

**Issue by immanetize** [ansible/ansible#63931]
##### SUMMARY
I have a value which may need to be inserted multiple times into a file, in varied positions.  It is inserted once only.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.8.5
  config file = /home/pete9168/linux_toolkit2/ansible.cfg
  configured module search path = ['/home/pete9168/upstream/playbooks/library']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/pete9168/linux_toolkit2/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/pete9168/linux_toolkit2/ansible.cfg) = -o StrictHostKeyChecking=no
DEFAULT_FORKS(/home/pete9168/linux_toolkit2/ansible.cfg) = 5
DEFAULT_HOST_LIST(/home/pete9168/linux_toolkit2/ansible.cfg) = ['/home/pete9168/linux_toolkit2/inventory']
DEFAULT_MODULE_PATH(/home/pete9168/linux_toolkit2/ansible.cfg) = ['/home/pete9168/upstream/playbooks/library']
DEFAULT_ROLES_PATH(/home/pete9168/linux_toolkit2/ansible.cfg) = ['/home/pete9168/upstream/playbooks/roles']
DEFAULT_TRANSPORT(/home/pete9168/linux_toolkit2/ansible.cfg) = ssh
DEPRECATION_WARNINGS(/home/pete9168/linux_toolkit2/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/pete9168/linux_toolkit2/ansible.cfg) = True

```

##### OS / ENVIRONMENT

$ uname -a
Linux workstation.randomuser.org 5.3.6-200.fc30.x86_64 #1 SMP Mon Oct 14 13:11:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
Insertafter with more than one "after" thing to match and expect multiple inserts of the line, directly after each "after" value.

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    all_things:
      - orange
      - apple
      - banana
      - tomato
    fruits:
      - orange
      - apple
      - banana
  tasks:
      - name: begin report
        delegate_to: localhost
        copy:
          content: |
            Known items:
              {% for thing in all_things %}
              - name: {{ thing }}
              {% endfor %}
          dest: "/tmp/test.which_things.txt"
      - name: report what type of thing
        delegate_to: localhost
        lineinfile:
          insertafter: "- name: {{ item }}:"
          line: "      type: fruit"
          dest: "/tmp/test.which_things.txt"
        with_items: "{{ fruits }}"
```
##### EXPECTED RESULTS
```
Known items:
    - name: orange
      type: fruit
    - name: apple
      type: fruit
    - name: banana
      type: fruit
    - name: tomato
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook  test.yml && cat /tmp/test.which_things.txt  
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details


PLAY [localhost] ***************************************************************************************************************************************************************************************************************

TASK [begin report] ************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [report what type of thing] ***********************************************************************************************************************************************************************************************
changed: [localhost -> localhost] => (item=orange)
ok: [localhost -> localhost] => (item=apple)
ok: [localhost -> localhost] => (item=banana)

PLAY RECAP *********************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Known items:
    - name: orange
    - name: apple
    - name: banana
    - name: tomato
  
      type: fruit

```

Should I be expecting `insertafter` behavior like "inserts between marker and EOF" instead of "inserts new line directly after marker" ?  The example is somewhat contrived, my actual intent is to run a test on hosts and list hostnames per test condition in a report file, ie "append hostname under list for condition if host passes condition".
