### ISSUE TITLE
rds_instance enable_performance_insights does not work

### ISSUE THREAD

**Issue by NeckBeardPrince** [ansible/ansible#63934]
##### SUMMARY
When restoring a database from a snapshot with the enable_performance_insights set to true the database does not have it enabled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rds_instance

##### ANSIBLE VERSION

```paste below
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
ansible 2.8.5
  config file = None
  configured module search path = [u'/home/<removed>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Restoring a postgresql RDS snapshot
Postgresql version 11.5

##### STEPS TO REPRODUCE

Restore a RDS Snapshot

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: Destroying Requested RDS Instance
      rds_instance:
        state: absent
        id: "{{ lookup('env','QA_INSTANCE') }}"
        skip_final_snapshot: true
        wait: false
      ignore_errors: true
      register: delete_qa

    - name: Taking snapshot of Staging RDS
      rds:
        command: snapshot
        instance_name: staging-tesseract
        snapshot: "staging-snap-{{ lookup('env','BUILD_NUMBER') }}"
        wait: yes
        wait_timeout: 5000

    - name: Create new QA Database from Staging Snapshot
      rds_instance:
        engine: postgres
        creation_source: snapshot
        db_snapshot_identifier: "staging-snap-{{ lookup('env','BUILD_NUMBER') }}"
        snapshot_identifier: "staging-snap-{{ lookup('env','BUILD_NUMBER') }}"
        db_instance_identifier: "{{ lookup('env','QA_INSTANCE') }}"
        db_instance_class: db.t2.medium
        vpc_security_group_ids: <removed>
        db_parameter_group_name: "{{ lookup('env','PARAMETER_GROUP') }}"
        db_subnet_group_name: <removed>
        enable_cloudwatch_logs_exports:
          - postgresql
          - upgrade
        enable_iam_database_authentication: true
        enable_performance_insights: true
        performance_insights_kms_key_id: <removed>
        performance_insights_retention_period: 7
        wait: yes

    - rds_instance_facts:
        db_instance_identifier: "{{ lookup('env','QA_INSTANCE') }}"
      register: rds_facts

    - name: Enabling Performance Insights, CloudWatch Logs Export, AutoScale Storage, and IAM Database Auth
      shell: aws rds modify-db-instance --db-instance-identifier "{{ lookup('env','QA_INSTANCE') }}" --max-allocated-storage 1001 --apply-immediately
      
    - name: Wait for connection to become stable
      wait_for:
        host: "{{ lookup('env','QA_INSTANCE') }}.<removed>"
        port: 5432
        delay: 15

```

##### EXPECTED RESULTS

Performance Insights Enabled

##### ACTUAL RESULTS

```paste below

ok: [localhost] => {
    "changed": false, 
    "instances": [
        {
            "allocated_storage": 100, 
            "associated_roles": [], 
            "auto_minor_version_upgrade": false, 
            "availability_zone": "us-west-1b", 
            "backup_retention_period": 7, 
            "ca_certificate_identifier": "rds-ca-2015", 
            "copy_tags_to_snapshot": false, 
            "db_instance_arn": "removed", 
            "db_instance_class": "db.t2.medium", 
            "db_instance_identifier": "removed", 
            "db_instance_port": 0, 
            "db_instance_status": "available", 
            "db_name": "removed", 
            "db_parameter_groups": [
                {
                    "db_parameter_group_name": "removed", 
                    "parameter_apply_status": "in-sync"
                }
            ], 
            "db_security_groups": [], 
            "db_subnet_group": {
                "db_subnet_group_description": "private postgres databases", 
                "db_subnet_group_name": "removed", 
                "subnet_group_status": "Complete", 
                "subnets": [
                    {
                        "subnet_availability_zone": {
                            "name": "us-west-1b"
                        }, 
                        "subnet_identifier": "subnet-removed", 
                        "subnet_status": "Active"
                    }, 
                    {
                        "subnet_availability_zone": {
                            "name": "us-west-1c"
                        }, 
                        "subnet_identifier": "removed", 
                        "subnet_status": "Active"
                    }
                ], 
                "vpc_id": "removed"
            }, 
            "dbi_resource_id": "removed", 
            "deletion_protection": false, 
            "domain_memberships": [], 
            "enabled_cloudwatch_logs_exports": [
                "postgresql", 
                "upgrade"
            ], 
            "endpoint": {
                "address": "removed", 
                "hosted_zone_id": "removed", 
                "port": 5432
            }, 
            "engine": "postgres", 
            "engine_version": "11.5", 
            "iam_database_authentication_enabled": true, 
            "instance_create_time": "2019-10-24T21:27:49.980000+00:00", 
            "kms_key_id": "removed", 
            "latest_restorable_time": "2019-10-24T21:29:00+00:00", 
            "license_model": "postgresql-license", 
            "master_username": "postgres", 
            "monitoring_interval": 0, 
            "multi_az": false, 
            "option_group_memberships": [
                {
                    "option_group_name": "default:postgres-11", 
                    "status": "in-sync"
                }
            ], 
            "pending_modified_values": {}, 
            "performance_insights_enabled": false, 
            "preferred_backup_window": "06:27-06:57", 
            "preferred_maintenance_window": "thu:12:20-thu:12:50", 
            "publicly_accessible": false, 
            "read_replica_db_instance_identifiers": [], 
            "storage_encrypted": true, 
            "storage_type": "gp2", 
            "tags": {}, 
            "vpc_security_groups": [
                {
                    "status": "active", 
                    "vpc_security_group_id": "removed"
                }
            ]
        }
    ], 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "db_instance_identifier": "removed", 
            "debug_botocore_endpoint_logs": false, 
            "ec2_url": null, 
            "filters": null, 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "validate_certs": true
        }
    }
}


```
