### ISSUE TITLE
template lookup plugin regression 2.8.6 -> 2.9.0rc5, if expansion contains hostvars references

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#63940]
##### SUMMARY

Template contents with hostvars expansions, when given to e.g. `copy` module's `contents` parameter, via `lookup('template')` fails with 2.9.0b1 through 2.9.0rc5 (latest), but works with 2.8.6 (and has been working for a long while back).  The same template rendered by `template` module and then given to `copy` module via `lookup('file')` works correctly unchanged.

The issue appears to be when `hostvars[somehost]` is referenced in the template file.  Works with template module, but not as a lookup.  This is a regression from 2.8.6, first introduced in released version 2.9b1.

I have narrowed the break down to commit f37476e247 (from PR #55126, which fixes #55113). Installing 2.9.0rc5 and then manually reversing that diff to the installed ansible files, fixes the templating run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible/plugins/lookup/template.py

##### ANSIBLE VERSION

```
ansible 2.9.0rc5
  config file = /home/scott/src/setup/.ansible.cfg
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Oct 19 2019, 23:36:22) [GCC 9.2.1 20191008]
```

##### CONFIGURATION

```
DEFAULT_STDOUT_CALLBACK(/home/scott/src/setup/.ansible.cfg) = unixy
DISPLAY_ARGS_TO_STDOUT(/home/scott/src/setup/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Linux Debian

##### STEPS TO REPRODUCE

`test.yml`:
```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  vars:

    infile: template.in
    outfile: template.out
    dummy: /tmp/eraseme

  tasks:

    - template:
        src: template.in
        dest: template.out

    - name: succeeds
      copy:
        content: "{{lookup('file', outfile)}}"
        dest: '{{dummy}}'

    - name: fails
      copy:
        content: "{{lookup('template', infile)}}"
        dest: '{{dummy}}'
```
`host_vars/localhost`:
```yaml
thisvar: foobar
```
`template.in`:
```jinja
{{hostvars['localhost'].thisvar}}
```
this is a minimal test case, actual usage is a role that's doing system builds targeting different environments, creates libvirt xml configs by templating `xml` parameter for `virt` module, it lets me obtain attributes of the selected target based on variables from its inventory.

##### EXPECTED RESULTS

```
 $ sudo -i pip install ansible==2.8.6 >/dev/null &&
   ansible-playbook -i localhost, test.yml | tr -s ' ' | fmt -st

Executing playbook test.yml

- localhost on hosts: localhost -
template...
 localhost ok
succeeds...
 localhost ok
fails...
 localhost done

- Play recap -
 localhost : ok=3 changed=1 unreachable=0 failed=0 rescued=0 ignored=0
```

##### ACTUAL RESULTS

```
 $ sudo -i pip install ansible==2.9.0rc5 >/dev/null && 
   ansible-playbook -i localhost, test.yml | tr -s ' ' | fmt -st

Executing playbook test.yml

- localhost on hosts: localhost -
template...
 localhost ok
succeeds...
 localhost ok
fails...
 localhost failed | msg: The task includes an option with an undefined
 variable. The error was: 'ansible.vars.hostvars.HostVars object' has
 no attribute 'localhost'

The error appears to be in '/home/scott/src/setup/test.yml': line 21,
column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

 - name: fails
 ^ here

- Play recap -
 localhost : ok=2 changed=0 unreachable=0 failed=1 rescued=0 ignored=0
```

again, reverting f37476e247 fixes the issue.
