### ISSUE TITLE
mysql_db import fails with special characters in password

### ISSUE THREAD

**Issue by paulbadcock** [ansible/ansible#63955]
##### SUMMARY
mysql_db import fails when using special characters in the password parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_db

##### ANSIBLE VERSION
```
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible-2.8-nonroot/lib/python2.7/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible-2.8-nonroot/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```
Nothing
```

##### OS / ENVIRONMENT
RHEL 7.6 

##### STEPS TO REPRODUCE
You can reproduce the problem by attempting to use a ! in the password field of the login_password

```yaml
 - mysql_db:
    name: "db"
    state: import
    target: /tmp/sql_dump.sql.bz2
    login_host: "db.tld"
    login_user: "user"
    login_password: "pass!word"
```

##### EXPECTED RESULTS
Database to import with no errors

##### ACTUAL RESULTS
Failure to import with permission denied error

```
ERROR 1045 (28000): Access denied for user 'user'@'db.tld' (using password: YES)\n"
```
