### ISSUE TITLE
mysql_db module does not import database schema from gzipped files

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#6397]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.6 (devel)
##### Environment:

Debian
##### Summary:

After latest changes in 1.5.1, mysql_db module does not import provided schema file.
##### Steps To Reproduce:

```

---
- hosts: all
  sudo: True

  tasks:
    - name: Install PHPMyAdmin packages
      apt: pkg={{ item }} state=latest install_recommends=no
      with_items: [ 'mysql-server', 'phpmyadmin', 'python-mysqldb' ]

    - name: Create database for PHPMyAdmin
      mysql_db: name=phpmyadmin state=present
      register: phpmyadmin_database

    - name: Import PHPMyAdmin schema
      mysql_db: name=phpmyadmin state=import
                target=/usr/share/doc/phpmyadmin/examples/create_tables.sql.gz
      when: phpmyadmin_database is defined and phpmyadmin_database.changed == True
```
##### Expected Results:

Schema is imported correctly.
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [olaf]

TASK: [Install PHPMyAdmin packages] ******************************************* 
ok: [olaf] => (item=mysql-server,phpmyadmin,python-mysqldb)

TASK: [Create database for PHPMyAdmin] **************************************** 
changed: [olaf]

TASK: [Import PHPMyAdmin schema] ********************************************** 
failed: [olaf] => {"failed": true}
msg: gzip: unrecognized option '--user=root'
Try `gzip --help' for more information.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/drybjed/phpmyadmin.retry

olaf                       : ok=3    changed=1    unreachable=0    failed=1
```
