### ISSUE TITLE
Can't use `vars` in playbook when using collections

### ISSUE THREAD

**Issue by chkp-orso** [ansible/ansible#63975]
##### SUMMARY

When using collection with HTTP API plugin, it's not possible to use any kind of `vars` from the playbook
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible collection

##### ANSIBLE VERSION

```paste below
2.9
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Following play fails when trying to fetch `vars` value through `get_option('domain')` (ref: https://github.com/ansible/ansible/pull/63976/files#diff-911386a804691dadae5f292b64df16a9R47) when used via `ansible collections` but works as expected and gets the `vars` value when used directly from `core` side.

```yaml
- hosts: checkpoint
  connection: httpapi
  tasks:
    - name: create new mgmt
      cp_mgmt_host:
        name: "Sales Web Server 2"
        ip_address: 10.0.10.121
      register: show_network_response
      vars:
        ansible_checkpoint_domain: "System Data"
```

##### EXPECTED RESULTS

Get the `vars` value from ansible collections

##### ACTUAL RESULTS

Fail to retrieve the `vars` value from ansible collections side

```paste below

```
