### ISSUE TITLE
npm module won't install a package if it is installed as another package's dependency

### ISSUE THREAD

**Issue by davidminor** [ansible/ansible#6399]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

N/A
##### Summary:

npm module won't install a package if it is installed as another package's dependency
##### Steps To Reproduce:

``` yml
- name: Install less compiler, css minifier
  npm: name={{ item }}
  with_items:
    - less
    - clean-css
```
##### Expected Results:

clean-css should be installed, as it will be if you run:

``` shell
# npm install less clean-css
```
##### Actual Results:

clean-css is not installed.

This is because the npm module is misinterpreting the results of npm list. If the less package is installed, `npm list --json clean-css` returns:

``` json
{
  "dependencies": {
    "less": {
      "version": "1.7.0",
      "from": "less@",
      "dependencies": {
        "clean-css": {
          "version": "2.1.6",
          "from": "clean-css@2.1.x"
        }
      }
    }
  }
}
```

The npm module interprets this to mean that clean-css is installed.
