### ISSUE TITLE
Order of elements in ansible_facts['disks'] array does not match actual disk order

### ISSUE THREAD

**Issue by m3gat0nn4ge** [ansible/ansible#63998]
##### SUMMARY
On a system with multiple disks, ansible_facts['disks'][0] is not guaranteed to be the first disk.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_disk_facts

##### ANSIBLE VERSION

```paste below
Ansible 2.8.5 on Tower 3.5.2
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Windows Server 2019 Datacenter running in AWS 

##### STEPS TO REPRODUCE
Use the following playbook to illustrate the issue

```yaml
---
- name: Configure local storage
  hosts: win1.example.com

  tasks:
    - name: Disk facts are populated
      win_disk_facts:

    - name: Print second disk size
      debug:
        var: ansible_facts['disks'][1]['size']

    - name: Extract second disk as standalone fact
      set_fact:
        second_disk: "{{ ansible_facts['disks'] | json_query('[?number==`1`]') }}"

    - name: Print actual second disk size
      debug:
        var: second_disk[0]['size']

```

##### EXPECTED RESULTS
ansible_facts['disks'][0] should contain information for the first disk (number: 0)
ansible_facts['disks'][1] should contain information for the second disk (number: 1)

##### ACTUAL RESULTS

The first element in the ansible_facts['disks'] array is the second disk instead of the first.

```paste below
SSH password: 
PLAY [Configure local storage] *************************************************

TASK [Gathering Facts] *********************************************************
ok: [win1.example.com]

TASK [Disk facts are populated] ************************************************
ok: [win1.example.com]

TASK [Print second disk size] **************************************************
ok: [win1.example.com] => {
    "ansible_facts['disks'][1]['size']": "32212254720"
}

TASK [Extract second disk as standalone fact] **********************************
ok: [win1.example.com]

TASK [Print actual second disk size] *******************************************
ok: [win1.example.com] => {
    "second_disk[0]['size']": "5368709120"
}

PLAY RECAP *********************************************************************
win1.example.com           : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
Users should not need to add json_query filters to obtain the correct disk. This may be a bug, or an enhancement, or a documentation issue.
