### ISSUE TITLE
Cisco NXOS IPv6 HSRP Support

### ISSUE THREAD

**Issue by jonathanspw** [ansible/ansible#63999]
##### SUMMARY
Presently the HSRP role only supports IPv4 HSRP.  It would be great if IPv6 were supported as well.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/network/nxos/nxos_hsrp.py

##### ADDITIONAL INFORMATION
I propose a simple option to signify if an HSRP group should be an IPv6 one.  Something like this perhaps:

```
- name: Configure VLAN 131 HSRP IPv6 Interface
  nxos_hsrp:
    group: 131
    interface: vlan131
    version: 2
    vip: <ipv6 address>
    ip_version: 6
```

The required change in the module is pretty minor and I've worked up a proof of concept.  Should I submit it as a PR?
