### ISSUE TITLE
sts_assume_role should reuse credentials if possible

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [ansible/ansible#64014]
##### SUMMARY

Don't know if it's really possible but...

*sts_assume_role* module always returns a new credentials set  upon role assumption (**sts_creds** dictionary) when current ones from environment/configuration may already be valid.

Since most aws-related modules end up falling back to the environment set **before** calling ansible-playbook, this makes very difficult to have clean code that works on different environments (i.e.: locally with environment configuration vs on aws instances with role profile).  See an example of this situation at #64012, and also the _"environment problem"_ I describe at #63947.

So, if current AWS_* vars from environment  can already be used to impersonate the requested role (or else, whatever aws_config/boto can already get by themselves), then the current session/configuration should be re-used instead of getting a new one.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

sts_assume_role

##### ADDITIONAL INFORMATION

This feature would allow for something like this (provided the correct environment is in place).  
**NOTE:** the code below won't work as-is; it's just an implementation/hint example:

Either this...
```yaml
---
- name: Assume Role Play
  hosts: localhost
  connection: local

  tasks:
  - name: Assumes the requested role
    sts_assume_role:
      role_arn: "arn:aws:iam::XXXXXXX:role/assumed-role"
      role_session_name: "assumedRoleSession"
    register: assumed_role

  - name: Grabs an aws_secret with the help of the assumed role above
    debug:
      msg: "An AWS secret: {{ lookup(aws_secret, 'my_aws_secret') }}"
```

...or else, something like more or less like this:
```yaml
---
- name: Assume Role Play
  hosts: localhost
  connection: local

  tasks:
  - name: Assumes the requested role
    sts_assume_role:
      role_arn: "arn:aws:iam::XXXXXXX:role/assumed-role"
      role_session_name: "assumedRoleSession"
    register: assumed_role

  - name: Grabs an aws_secret with the help of the assumed role above
    debug:
      msg:
      - "An AWS secret: {{ lookup(aws_secret, 'my_aws_secret') }}"
      - "Or, maybe... {{ lookup(aws_secret, 'my_aws_secret', with_role = assumedRoleSession | default(null)) }}"
   # ...or, maybe...
    environment: "{{ assumed_role }}" /  "{{ ...or something related to 'assumedRoleSession' }}"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/amazon/sts_assume_role.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/sts_assume_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bekelchik @piontas
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@next-jesusmanuelnavarro, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jillr @s-hertel @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nicohouillon** [comment]
same problem, how can sts work in environment ? 
this fails for undefined :

pre_tasks:
    - name: Assume a role
      sts_assume_role:
        role_arn: "arn:aws:iam:::role/myrole"
        role_session_name: "mysession"
        region: "{{ cf_region }}"
      register: assumed_role
      no_log: true

roles: 
### here I need the environment to be passed to every subsequent roles 
 - myrole1
-  myrole2 
environment:
   AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
   AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
   AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token }}"

**Comment by tremble** [comment]
@nicohouillon the way I have approached your example requirement is to make use of module_defaults, include_role and block:

```
# Now perform the Per-Account setup on each specific account
- hosts: aws_accounts
  gather_facts: no
  tasks:
  - block:
    - name: 'Assume Role in account'
      sts_assume_role:
        role_arn: 'arn:aws:iam::{{ account_id }}:role/{{ sts_role_name }}'
        role_session_name: "Example-Session-Name"
        profile: '{{ aws_initial_profile }}'
      register: aws_sts_assumed_role
      check_mode: no
      no_log: true
    - set_fact:
        current_account_sts_credentials: '{{ aws_sts_assumed_role.sts_creds }}'
      no_log: true
    - name: 'run roles under assumed context'
      module_defaults:
        group/aws:
          aws_access_key: '{{ current_account_sts_credentials.access_key }}'
          aws_secret_key: '{{ current_account_sts_credentials.secret_key }}'
          security_token: '{{ current_account_sts_credentials.session_token }}'
      block:
      - include_role:
          name: 'role1'
      - include_role:
          name: 'role2'
```

**Comment by nicohouillon** [comment]
Nice, I need to test that pattern, can we include/import multiple roles at once, like with a "loop" ? 
can't seem to be working. It would be a list of roles or a dict of we need to spcify vars :



```

- include_role:
        - name: myrole1, when: something | default(None) 
        - name: myrole2, when: somethingElse | default(None)
  environment:
      AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
      AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token }}" 

```

**Comment by s-hertel** [comment]
Wait, why not just set a default value to fall back to until the var exists?
```
---
- hosts: all
  gather_facts: no
  pre_tasks:
      - name: Assume a role
        sts_assume_role:
          role_arn: "arn:aws:iam::448830907657:role/developer"
          role_session_name: "mysession"
          region: "us-east-1"
          profile: shertel
        register: assumed_role
        no_log: true
  roles:
    - role1
    - role2
  environment:
     AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key | default('') }}"
     AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key | default('') }}"
     AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token | default('') }}"
```
