### ISSUE TITLE
aws_secret should honor environment

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [ansible/ansible#64012]
##### SUMMARY
aws_secret lookup plugin should honor variables passed as environment.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

aws_secret lookup plugin

##### ADDITIONAL INFORMATION

While working on code that...
1. Should impersonate an AWS role
2. Should work both on a local workstation and on an AWS instance with an instance_profile

...I ended up using sts_assume_role module to impersonate the required role and then passing the returned sts_creds to a dictionary fact that I intented to use more or less like this:

1. First play to gather credentials
```yaml
---
- name: Assume Role Play
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Assumes the requested role
    sts_assume_role:
      region: "eu-west-1"
      role_arn: "arn:aws:iam::XXXX:role/target-role"
      role_session_name: "assumedRoleSession"
    register: assumed_role

  - name: Sets AWS environment facts
    set_fact:
      my_aws_credentials:
        AWS_ACCESS_KEY: "{{ assumed_role.sts_creds.access_key }}"
        AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
        AWS_SECRET_KEY: "{{ assumed_role.sts_creds.secret_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
        AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
        AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
        AWS_REGION: "eu-west-1"
        AWS_DEFAULT_REGION: "eu-west-1"
```

2. A second play tries to make use of credentials above
```yaml
- name: Main play
  hosts: localhost
  onnection: local
  environment: "{{ my_aws_credentials }}"

  - tasks:
    - name: tries to grab an AWS secret
      debug:
        msg: "Grabs a secret: {{ lookup(aws_secret, 'my_aws_secret') }}"
```

The idea above is that I could include the first playbook as needed.  It fails for two different reasons:
1. It seems aws_secret plugin doesn't look for EC2_REGION and/or AWS_REGION environment variables despite what's stated on documentation, so you are forced to pass *region* as param to aws_secret.
1. aws_secret doesn't honor *environment*  (which should come from ansible_env[]).  It seems, [looking at code](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/aws_secret.py), that this plugin just looks for what parameters have been set by the plugin as called and if it doesn't find them, it just falls back to aws_profile/boto (which, in turn, depend on either their own config files or environment variables set **before** ansible invocation) without attempt to look at the ansible_env[] array.

Also related (see #64014), but out of this request's scope is the fact that sts_assume_role won't reuse environment credentials if it in fact can impersonate the requested role with them but always will request and return new ones, so those from "real" environment before ansible-playbook invocation (which are the ones aws_secret will honor by means of aws_profile/boto related code) are of no use in this scenario.
