### ISSUE TITLE
azure_rm_dnszone does not create private zone when type set to private

### ISSUE THREAD

**Issue by rewilliams1** [ansible/ansible#64036]
##### SUMMARY

When running Ansible module azure_rm_dnszone with type "private", it does not set the zone private but to a public dns zone.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_dnszone
##### ANSIBLE VERSION

```paste below
ansible 2.8.6
Using Virtualenv
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac running Virtual environment installed via Pip

##### STEPS TO REPRODUCE

Run ansible-playbook against zone and it will create a public dns zone.

```yaml
  - name: Create a DNS zone
    azure_rm_dnszone:
      ad_user: "{{ ad_username }}"
      password: "{{ ad_password }}"
      resource_group: "{{ resource_group }}"
      name: "{{ zone_name }}"
      type: "private"
```

##### EXPECTED RESULTS

I expected that the dns zone would be created as a private dns zone.

##### ACTUAL RESULTS

Zone is found under standard DNS Zones service.

```paste below
ok: [local] => {
    "changed": false,
    "check_mode": false,
    "invocation": {
        "module_args": {
            "ad_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "name": "zone.test",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "profile": null,
            "registration_virtual_networks": null,
            "resolution_virtual_networks": null,
            "resource_group": "centralresource",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "type": "private"
        }
    },
    "state": {
        "id": "/subscriptions/subsciption_id/resourceGroups/centralresource/providers/Microsoft.Network/dnszones/zone.test",
        "name": "zone.test",
        "name_servers": null,
        "number_of_record_sets": 1,
        "registration_virtual_networks": null,
        "resolution_virtual_networks": null,
        "tags": {},
        "type": "private"
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/azure/azure_rm_dnszone.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_dnszone.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @ozboms @yungezz @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@rewilliams1, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@rewilliams1 Thank you for open this issue! DNS Zone ([Create DNS Zone](https://docs.microsoft.com/en-us/rest/api/dns/zones/createorupdate)) and Private DNS Zone(Create [Private DNS Zone](https://docs.microsoft.com/en-us/rest/api/dns/privatedns/privatezones/createorupdate)) are two functions, you mean there should be a module or function to create Private DNS Zone, right?

**Comment by rewilliams1** [comment]
@Fred-sun , If you look at the ansible documentation there is a type parameter that you can set to private. One would think that this would mean private zone. If thats not the meaning, what does it mean?

I ended up using the azure_rm_resource module and using the using the Private DNSZone(Create Private DNS Zone) to create the private zone.

**Comment by Fred-sun** [comment]
@rewilliams1 I checked the materials related to API and SDK, but did not clearly indicate the private and public purpose of zonetype. However, no matter API or azure portal, private DNS zone and DNS zone are two different modules. I'll keep following. Thank you very much!

**Comment by Fred-sun** [comment]
@mybayern1974 Can you confirm with the community staff the role of the two attributes of zone_type? Thank you very much!

**Comment by MrDecisive** [comment]
@Fred-sun - Hi, Is this being worked on? I've come across the same issue. The existing ansible module **azure_rm_dnszone** has a **type** parameter which can be set to public or private. It also has the **registration_virtual_networks** and **resolution_virtual_networks** which are only associated with private dns option for **type**.  As @rewilliams1 says - no matter what you set these options to, in the azure portal you see the resource created under the **dns zone** section and not under the **private dns zone** section. We either need a azure_rm_private_dnszone and azure_rm_dnszone module or the existing azure_rm_dnszone module needs to perform both functions base on the type parameter Cheers - I'm off to use the azure_rm_resource general rest client to do the same as @rewilliams1 :)

**Comment by Dagon-** [comment]
Private DNS was added to the module when it was still in preview and is using an outdated version of the API. Shortly before Private DNS went GA the API was updated and was split into it's own resource. Some details on this are here:

https://docs.microsoft.com/en-us/azure/dns/private-dns-migration-guide

The old API is deprecated so yeah, this need to updated. Personally I think  azure_rm_private_dnszone and azure_rm_dnszone as per the suggestion by @MrDecisive would make most sense.

**Comment by Fred-sun** [comment]
@MrDecisive @Dagon- Thank you for your advice, we are also working hard on this!

**Comment by ansibot** [comment]
cc @gavinfish @haiyuazhang
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang Would you please help take a look this issue when you're free! Thank you very much!

**Comment by chrisedebo** [comment]
I've just run into this issue also. Same behaviour, creating a standard DNS Zone when I set the type parameter to private. 

Can anyone assist with using azure_rm_resource module instead? a link to some docs as a work around until the issue is resolved would be very helpful for people who come across this issue 😃

**Comment by keiransteele** [comment]
@chrisedebo The below task works for me, I put it in a simple role to make it easier to use. Just make sure your service principal has the Private DNS Zone Contributor role.

```yaml
- name: Create A record in Private Azure DNS - record {{ record_type }}:{{ record_name }}
  azure_rm_resource:
    url: /subscriptions/{{ zone_subscription_id }}/resourceGroups/{{ zone_resource_group }}/providers/Microsoft.Network/privateDnsZones/{{ zone_domain_name }}/{{ record_type }}/{{ record_name }}
    secret: "{{ azure_secret }}"
    client_id: "{{ azure_clientid }}"
    subscription_id: "{{ azure_subscription_id }}"
    tenant: "{{ azure_tenant }}"
    api_version: '2018-09-01'
    body:
      properties: 
        metadata: 
          key1: "{{ record_name }}"
        ttl: "{{ ttl }}"
        aRecords: 
          - ipv4Address: "{{ a_record_ip }}"
  delegate_to: localhost
  when: record_type == "A"
```
