### ISSUE TITLE
nios_fixed_address not able to add options that don't require use_options

### ISSUE THREAD

**Issue by megabreit** [ansible/ansible#64034]
##### SUMMARY
It is not possible to add options that don't require use_options e.g. host-name

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
net_tools, nios, lib/ansible/modules/net_tools/nios/nios_fixed_address.py

##### ANSIBLE VERSION
```
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]


```

##### CONFIGURATION

```
empty
```

##### OS / ENVIRONMENT
Ubuntu 18.04 with Ansible 2.8.6 from Ansible PPA (2.8.6-1ppa~bionic)

pip freeze|grep -i infoblox
infoblox-client==0.4.23

##### STEPS TO REPRODUCE

```
    - name: set dhcp options for a ipv4 fixed address
      nios_fixed_address:
        name: hostname.domain
        ipaddr: "{{ vm_ipaddr }}"
        mac: "{{ macaddress }}"
        network: 10.0.0.0/24
        network_view: default
        options:
          - name: host-name
            value:  "{{ vm_name }}"
        state: present
        provider: "{{ nios_provider }}"
      connection: local
      register: dhcp_results
```

##### EXPECTED RESULTS

The host-name option should be set in the infoblox appliance for the specific fixed address.

##### ACTUAL RESULTS

Ansible terminates with the error below.
It is impossible to use any option that has no use_option. The source code has no special treatment for those occasions. "use_options" defaults always to "True". See line 221 in lib/ansible/modules/net_tools/nios/nios_fixed_address.py
The same error happens when any use_option is used. I tried "yes", "no", "true", "false". It's also not possible to use equivalent "num: 12" instead of "name: host-name".

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "code": "Client.Ibap.Proto", "msg": "Option host-name can not have a use_option flag", "operation": "create_object", "type": "AdmConProtoError"}
```
