### ISSUE TITLE
vlan_id parameter is missing from the vmware_vmkernel module

### ISSUE THREAD

**Issue by underqualifieditguy** [ansible/ansible#64038]
##### SUMMARY

Unable to configure the vlan id for a vmkernel adapter using the latest version of vmware_vmkernel

Was this taken out of this module for Ansible 2.8? I modified the module locally and added the parameter back and it works as expected. There is no note published on the module saying that the parameter has been removed.

https://docs.ansible.com/ansible/latest/modules/vmware_vmkernel_module.html?highlight=vmware_vmkernel

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_vmkernel

##### ANSIBLE VERSION

```paste below
ansible 2.8.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MAC OSX Mojave 10.14.6

##### STEPS TO REPRODUCE

```yaml
- name: VMK MTU
  vmware_vmkernel:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ portgroup_name }}"
    vlan_id: "{{ vlan_id }}"
    network:
      type: 'static'
      ip_address: "{{ ip_address }}"
      subnet_mask: "{{ subnet_mask }}"
    mtu: "{{ mtu }}"
    state: present
    validate_certs: no
  delegate_to: localhost
```

##### EXPECTED RESULTS

Expected that the vlan id for the vmkernel adapter would be updated

##### ACTUAL RESULTS

received an error that vlan_id is not a supported parameter

```paste below
FAILED! => {"changed": false, "msg": "Unsupported parameters for (vmware_vmkernel) module: vlan_id Supported parameters include: device, dvswitch_name, enable_ft, enable_mgmt, enable_provisioning, enable_replication, enable_replication_nfc, enable_vmotion, enable_vsan, esxi_hostname, hostname, ip_address, mtu, network, password, port, portgroup_name, state, subnet_mask, username, validate_certs, vswitch_name"}
```
