### ISSUE TITLE
vlan_id parameter missing from vmware_vmkernel module in Ansible 2.8

### ISSUE THREAD

**Issue by underqualifieditguy** [ansible/ansible#64039]
##### SUMMARY

Unable to configure the vlan id for a vmkernel adapter using the latest version of vmware_vmkernel

Was this taken out of this module for Ansible 2.8? I modified the module locally and added the parameter back and it works as expected. There is no note published on the module saying that the parameter has been removed.

https://docs.ansible.com/ansible/latest/modules/vmware_vmkernel_module.html?highlight=vmware_vmkernel

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_vmkernel

##### ANSIBLE VERSION

```paste below
ansible 2.8.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MAC OSX Mojave 10.14.6

##### STEPS TO REPRODUCE

```yaml
- name: VMK MTU
  vmware_vmkernel:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    dvswitch_name: "{{ dvswitch_name }}"
    portgroup_name: "{{ portgroup_name }}"
    vlan_id: "{{ vlan_id }}"
    network:
      type: 'static'
      ip_address: "{{ ip_address }}"
      subnet_mask: "{{ subnet_mask }}"
    mtu: "{{ mtu }}"
    state: present
    validate_certs: no
  delegate_to: localhost
```

##### EXPECTED RESULTS

Expected that the vlan id for the vmkernel adapter would be updated

##### ACTUAL RESULTS

received an error that vlan_id is not a supported parameter

```paste below
FAILED! => {"changed": false, "msg": "Unsupported parameters for (vmware_vmkernel) module: vlan_id Supported parameters include: device, dvswitch_name, enable_ft, enable_mgmt, enable_provisioning, enable_replication, enable_replication_nfc, enable_vmotion, enable_vsan, esxi_hostname, hostname, ip_address, mtu, network, password, port, portgroup_name, state, subnet_mask, username, validate_certs, vswitch_name"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_vmkernel.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vmkernel.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@underqualifieditguy, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by underqualifieditguy** [comment]
Any update on this?

**Comment by sky-joker** [comment]
Hi @underqualifieditguy

The vmware_vmkernel module vlan_id option has been removed from this PR(https://github.com/ansible/ansible/pull/47270
).

VLAN ID is set to the port group.
It is not set in VMkernel.
So, it seems to have been removed from this module.

If you want to set a VLAN, run a Playbook like this.

```yaml
---
- name: example playbook
  hosts: localhost
  gather_facts: no
  vars:
    auth_info: &auth_info
      hostname: vCenter IP
      username: administrator@vsphere.local
      password: password
      validate_certs: no
  tasks:
    - name: Create portgroup to vSwitch
      vmware_portgroup:
        <<: *auth_info
        hosts:
          - esxi_name
        switch_name: vSwitch0
        portgroup_name: TEST01
        vlan_id: 12
        state: present

    - name: Create vmkernel to portgroup
      vmware_vmkernel:
        <<: *auth_info
        esxi_hostname: esxi_name
        vswitch_name: vSwitch0
        portgroup_name: TEST01
        network:
          type: static
          ip_address: 192.168.100.1
          subnet_mask: 255.255.255.0
        state: present
```
