### ISSUE TITLE
RFE: to_uuid4 filter

### ISSUE THREAD

**Issue by pierreprinetti** [ansible/ansible#64054]
##### SUMMARY
Add a filter that formats an integer into its UUID4 representation.

Something like:
```Python
def to_uuid4(number):
    return str(uuid.UUID(int=number%2**128))
```

The required library [is already imported](https://github.com/pierreprinetti/ansible/blob/16d4d2dba9d62103a198647894f7f82020dca27c/lib/ansible/plugins/filter/core.py#L34) in the `core` filter module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

UUIDv4 is probably the most known and widespread version of UUID, and the only version that fully leverages the 128-bit entropy space.

However, the Ansible core filter `to_uuid` already exists and generates an [UUIDv5](https://en.wikipedia.org/wiki/Universally_unique_identifier#Versions_3_and_5_(namespace_name-based)) using an [arbitrary, hardcoded namespace](https://github.com/pierreprinetti/ansible/blob/16d4d2dba9d62103a198647894f7f82020dca27c/lib/ansible/plugins/filter/core.py#L279-L280).

Therefore, I suggest this filter to be named **`to_uuid4`**.

##### ADDITIONAL INFORMATION

EXAMPLES:
```yaml
- hosts: all
  vars:
    hardcoded_uuid4: "{{ 12 | to_uuid4 }}"              # '00000000-0000-0000-0000-00000000000c'
    max_wrap:        "{{ 2**128+1 | to_uuid4 }}"        # '00000000-0000-0000-0000-000000000001'
    random_uuid4:    "{{ 2**128 | random | to_uuid4 }}" # 'af6d1327-40ad-40ee-8abb-f8213c6478db'

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/filter`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pierreprinetti** [comment]
The bot says "has_pr", but no, #64057 is only about UUIDv5 which is functionality already present in Ansible.

**Comment by sivel** [comment]
Your proposal is not compliant with uuid4, as uuid4 is supposed to generate a random uuid.  In your case, you just want to convert an integer to uuid format, with the potential that a user provide the randomness, but which is still not uuid4.

I see that it would potentially collide with the current `to_uuid` filter as that generates a uuid5 with a static namespace (for idempotency).

On another note, uuid4 would likely not be something that we would accept, as it would not have a way to handle idempotency, which is why we used uuid5.

**Comment by pierreprinetti** [comment]
@sivel 

> uuid4 is supposed to generate a random uuid

Does this look better?
```Python
def uuid4():
    return to_text(uuid.uuid4())
```

EXAMPLE:
```yaml
- hosts: all
  vars:
    uuid4: "{{ uuid4 }}" # 'af6d1327-40ad-40ee-8abb-f8213c6478db'
```

I personally find it less flexible. However, it is still better than having to [rely](https://stackoverflow.com/a/30516467/1606248) [on](https://www.howtobuildsoftware.com/index.php/how-do/qaM/ansible-ansible-random-uuid-generation) `shell` (or [worse](https://stackoverflow.com/a/41455193/1606248), [misuse](https://stackoverflow.com/a/30519885/1606248) the UUIDv5 filter).

---

Regarding this:
> uuid4 would likely not be something that we would accept, as it would not have a way to handle idempotency

Does it mean that Ansible would not accept any filter that produces randomness?

I think that there is the need for random values, and [`random`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#random-number-filter) is a very useful filter.
