### ISSUE TITLE
Amazon ec2 module should tag instances at time of creation

### ISSUE THREAD

**Issue by andrewsnell-clarivate** [ansible/ansible#64063]
##### SUMMARY
In organizations that enforce a tagging compliance policy in EC2 (for example, all instances must have tags "org-owner" and "org-function" tags in order to launch) Ansible's ec2 module is effectively unusable, since tags are only applied after initial instance creation: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2.py#L1278

Launching instances with awscli tools or python+boto3 directly does not suffer from this limitation.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Amazon ec2 module

##### ADDITIONAL INFORMATION
This looks like it may be a limitation of the boto library, which does not seem to allow for specifying tags in the create_instance method. Moving to boto3 may allow this to change as the EC2.ServiceResource.create_instances method allows passing of a TagSpecifications parameter

```yaml
    - name: Create molecule instance(s)
      ec2:
        key_name: "molecule_key"
        image: "ami-04b762b4289fba92b"
        instance_type: "t2.micro"
        vpc_subnet_id: "subnet-xxxxxxx"
        group: "molecule"
        instance_tags: # Tags will not be applied until after the instance starts up
          "appFamily": sdlc
          "appName": molecule
          "environment-type": scratch
          "role": ami-provisioning

```
