### ISSUE TITLE
aws_kms_facts is very slow

### ISSUE THREAD

**Issue by rmatec** [ansible/ansible#64062]
##### SUMMARY
The aws_kms_facts module is very slow. It takes around 1-2 minutes to complete.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_kms_facts

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)]
```

Version 2.8.5 also affected. I don't have the 'ansible --version' output at hand as I upgraded to see whether the devel version fixes the issue.

##### CONFIGURATION

```paste below
No output
```

##### OS / ENVIRONMENT

MacOS Catalina and Windows 7

##### STEPS TO REPRODUCE

```yaml
---
- name: POC kms facts
  hosts: localhost
  tasks:
      - name: Get facts from KMS
        aws_kms_facts:
          region: "us-east-1"
```

##### EXPECTED RESULTS

The facts are returned in a sensible time

##### ACTUAL RESULTS

The facts are returned in 1-2 minutes

```paste below

```
