### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' on k8s

### ISSUE THREAD

**Issue by dove-young** [ansible/ansible#64129]
##### SUMMARY

Deploy `ingress-mandatory.yaml` and `ingress-service-nodeport.yaml`  to K8S cluster failed.  Error message said AttributeError: 'NoneType' object has no attribute 'get'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- k8s
##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

- RHEL 7.6

##### STEPS TO REPRODUCE

- define playbook `k8s-addons.yaml`
```yaml
- hosts: master
  tasks:
    - name: get addons
      get_url:
        url: "{{item.url}}"
        dest: "{{item.local}}"
        force: yes
      with_items:
      - {local: "{{playbook_dir}}/addons/ingress-mandatory.yaml", url: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml'}
      - {local: "{{playbook_dir}}/addons/ingress-service-nodeport.yaml", url: 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/baremetal/service-nodeport.yaml'}
      - {local: "{{playbook_dir}}/addons/dashboard-recommended.yaml", url: 'https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml'}
    - name: install addons
      k8s:                      ## yum install -y python2-openshift.noarch  in advance
        state: present
        src: "{{item.name}}"
        kubeconfig: /root/.kube/config
      with_items:
      - {name: "{{playbook_dir}}/addons/ingress-mandatory.yaml"}
      - {name: "{{playbook_dir}}/addons/ingress-service-nodeport.yaml"}
      - {name: "{{playbook_dir}}/addons/dashboard-recommended.yaml"} 
```
- `ansible-playbook -i hosts.local k8s-addons.yaml`
- `dashboard-recommended.yaml` will be deployed successfully
- `ingress-mandatory.yaml` and `ingress-service-nodeport.yaml` would fail

##### ACTUAL RESULTS

```paste below
failed: [<master-ip>] (item={u'name': u'/root/Ansible/addons/ingress-mandatory.yaml'}) => 
{"ansible_loop_var": "item", "changed": false, "item": {"name": "/root/Ansible/addons/ingress-mandatory.yaml"}, 
"module_stderr": "Shared connection to <master-ip> closed.\r
", "module_stdout": "Traceback (most recent call last):\r
  File \"/root/.ansible/tmp/ansible-tmp-1572490026.36-31679515591322/AnsiballZ_k8s.py\", line 114, in <module>\r
    _ansiballz_main()\r
  File \"/root/.ansible/tmp/ansible-tmp-1572490026.36-31679515591322/AnsiballZ_k8s.py\", line 106, in _ansiballz_main\r
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r
  File \"/root/.ansible/tmp/ansible-tmp-1572490026.36-31679515591322/AnsiballZ_k8s.py\", line 49, in invoke_module\r
    imp.load_module('__main__', mod, module, MOD_DESC)\r
  File \"/tmp/ansible_k8s_payload_8E6nyl/__main__.py\", line 258, in <module>\r
  File \"/tmp/ansible_k8s_payload_8E6nyl/__main__.py\", line 254, in main\r
  File \"/tmp/ansible_k8s_payload_8E6nyl/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 158, in execute_module\r
AttributeError: 'NoneType' object has no attribute 'get'\r
", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}failed: [<master-ip>] (item={u'name': u'/root/Ansible/addons/ingress-service-nodeport.yaml'}) => 
{"ansible_loop_var": "item", "changed": false, "item": {"name": "/root/Ansible/addons/ingress-service-nodeport.yaml"},
 "module_stderr": "Shared connection to <master-ip> closed.\r
", "module_stdout": "Traceback (most recent call last):\r
  File \"/root/.ansible/tmp/ansible-tmp-1572490028.09-92563553077018/AnsiballZ_k8s.py\", line 114, in <module>\r
    _ansiballz_main()\r
  File \"/root/.ansible/tmp/ansible-tmp-1572490028.09-92563553077018/AnsiballZ_k8s.py\", line 106, in _ansiballz_main\r
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r
  File \"/root/.ansible/tmp/ansible-tmp-1572490028.09-92563553077018/AnsiballZ_k8s.py\", line 49, in invoke_module\r
    imp.load_module('__main__', mod, module, MOD_DESC)\r
  File \"/tmp/ansible_k8s_payload_OecZzZ/__main__.py\", line 258, in <module>\r
  File \"/tmp/ansible_k8s_payload_OecZzZ/__main__.py\", line 254, in main\r
  File \"/tmp/ansible_k8s_payload_OecZzZ/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 158, in execute_module\r
AttributeError: 'NoneType' object has no attribute 'get'\r
", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}

```
