### ISSUE TITLE
`patch` module does not treat `strip` parameter in the same way `patch` command does. 

### ISSUE THREAD

**Issue by dove-young** [ansible/ansible#64130]
##### SUMMARY

`patch` module does not treat `strip` parameter in the same way `patch` command does. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

patch
##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
N/A
```

##### STEPS TO REPRODUCE

```yaml
- hosts: master
  vars:
    argocd_server_external: "{{ groups['worker'][0]}}"
    nfs_src: "{{playbook_dir}}/external-storage/nfs/deploy/kubernetes"
  tasks:
    - name: Clone nfs provider
      git:
        repo: 'https://github.com/kubernetes-incubator/external-storage.git'
        dest: "{{playbook_dir}}/external-storage"
        depth: 1
        update: yes
        force: yes
    - name: patch nfs provider
      patch:
        src: "{{playbook_dir}}/files/nfs-provider.patch"
        basedir: "{{playbook_dir}}/external-storage/nfs/deploy/kubernetes"
#        basedir: "{{playbook_dir}}/external-storage"
```

And here is my patch file 

```
diff --git a/nfs/deploy/kubernetes/class.yaml b/nfs/deploy/kubernetes/class.yaml
index 582d0f1..5bc2203 100644
--- a/nfs/deploy/kubernetes/class.yaml
+++ b/nfs/deploy/kubernetes/class.yaml
@@ -1,6 +1,8 @@
 kind: StorageClass
 apiVersion: storage.k8s.io/v1
 metadata:
+  annotations:
+    storageclass.kubernetes.io/is-default-class: "true"
   name: example-nfs
 provisioner: example.com/nfs
 mountOptions:
diff --git a/nfs/deploy/kubernetes/psp.yaml b/nfs/deploy/kubernetes/psp.yaml
index 2f8e188..03fd080 100644
--- a/nfs/deploy/kubernetes/psp.yaml
+++ b/nfs/deploy/kubernetes/psp.yaml
@@ -1,4 +1,4 @@
-apiVersion: extensions/v1beta1
+apiVersion: policy/v1beta1
 kind: PodSecurityPolicy
 metadata:
   name: nfs-provisioner
diff --git a/nfs/deploy/kubernetes/read-pod.yaml b/nfs/deploy/kubernetes/read-pod.yaml
index 31497e9..1c4e0f2 100644
--- a/nfs/deploy/kubernetes/read-pod.yaml
+++ b/nfs/deploy/kubernetes/read-pod.yaml
@@ -5,7 +5,7 @@ metadata:
 spec:
   containers:
   - name: read-pod
-    image: gcr.io/google_containers/busybox:1.24
+    image: docker.io/library/busybox:1.24
     command:
       - "/bin/sh"
     args:
diff --git a/nfs/deploy/kubernetes/write-pod.yaml b/nfs/deploy/kubernetes/write-pod.yaml
index 99f7d02..e6c3fb4 100644
--- a/nfs/deploy/kubernetes/write-pod.yaml
+++ b/nfs/deploy/kubernetes/write-pod.yaml
@@ -5,7 +5,7 @@ metadata:
 spec:
   containers:
   - name: write-pod
-    image: gcr.io/google_containers/busybox:1.24
+    image: docker.io/library/busybox:1.24
     command:
       - "/bin/sh"
     args:
~
```

##### EXPECTED RESULTS

Here is the content from `man patch` command.  and especially on this line

- and not specifying -p at all just gives you blurfl.c.  Whatever you end up with is looked for either in the current directory, or the directory specified by the -d option.

```
       -pnum  or  --strip=num
          Strip the smallest prefix containing num leading slashes from each file  name  found  in  the  patch
          file.   A  sequence of one or more adjacent slashes is counted as a single slash.  This controls how
          file names found in the patch file are treated, in case you keep your files in a different directory
          than the person who sent out the patch.  For example, supposing the file name in the patch file was

             /u/howard/src/blurfl/blurfl.c

          setting -p0 gives the entire file name unmodified, -p1 gives

             u/howard/src/blurfl/blurfl.c

          without the leading slash, -p4 gives

             blurfl/blurfl.c

          and not specifying -p at all just gives you blurfl.c.  Whatever you end up with is looked for either
          in the current directory, or the directory specified by the -d option.
```

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_patch_payload_PodKkW/__main__.py", line 208, in main
    dry_run=module.check_mode, backup=p.backup, state=p.state)
  File "/tmp/ansible_patch_payload_PodKkW/__main__.py", line 158, in apply_patch
    raise PatchError(msg)
PatchError: The text leading up to this was:
--------------------------
|diff --git a/nfs/deploy/kubernetes/class.yaml b/nfs/deploy/kubernetes/class.yaml
|index 582d0f1..5bc2203 100644
|--- a/nfs/deploy/kubernetes/class.yaml
|+++ b/nfs/deploy/kubernetes/class.yaml
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff --git a/nfs/deploy/kubernetes/psp.yaml b/nfs/deploy/kubernetes/psp.yaml
|index 2f8e188..03fd080 100644
|--- a/nfs/deploy/kubernetes/psp.yaml
|+++ b/nfs/deploy/kubernetes/psp.yaml
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff --git a/nfs/deploy/kubernetes/read-pod.yaml b/nfs/deploy/kubernetes/read-pod.yaml
|index 31497e9..1c4e0f2 100644
|--- a/nfs/deploy/kubernetes/read-pod.yaml
|+++ b/nfs/deploy/kubernetes/read-pod.yaml
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
The text leading up to this was:
--------------------------
|diff --git a/nfs/deploy/kubernetes/write-pod.yaml b/nfs/deploy/kubernetes/write-pod.yaml
|index 99f7d02..e6c3fb4 100644
|--- a/nfs/deploy/kubernetes/write-pod.yaml
|+++ b/nfs/deploy/kubernetes/write-pod.yaml
--------------------------
No file to patch.  Skipping patch.
patch unexpectedly ends in middle of line
1 out of 1 hunk ignored


fatal: [9.46.75.76]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "basedir": "/root/Ansible/external-storage/nfs/deploy/kubernetes",
            "binary": false,
            "dest": null,
            "remote_src": false,
            "src": "/root/.ansible/tmp/ansible-tmp-1572498437.38-259841358088847/nfs-provider.patch",
            "state": "present",
            "strip": 0
        }
    },
    "msg": "The text leading up to this was:\n--------------------------\n|diff --git a/nfs/deploy/kubernetes/class.yaml b/nfs/deploy/kubernetes/class.yaml\n|index 582d0f1..5bc2203 100644\n|--- a/nfs/deploy/kubernetes/class.yaml\n|+++ b/nfs/deploy/kubernetes/class.yaml\n--------------------------\nNo file to patch.  Skipping patch.\n1 out of 1 hunk ignored\nThe text leading up to this was:\n--------------------------\n|diff --git a/nfs/deploy/kubernetes/psp.yaml b/nfs/deploy/kubernetes/psp.yaml\n|index 2f8e188..03fd080 100644\n|--- a/nfs/deploy/kubernetes/psp.yaml\n|+++ b/nfs/deploy/kubernetes/psp.yaml\n--------------------------\nNo file to patch.  Skipping patch.\n1 out of 1 hunk ignored\nThe text leading up to this was:\n--------------------------\n|diff --git a/nfs/deploy/kubernetes/read-pod.yaml b/nfs/deploy/kubernetes/read-pod.yaml\n|index 31497e9..1c4e0f2 100644\n|--- a/nfs/deploy/kubernetes/read-pod.yaml\n|+++ b/nfs/deploy/kubernetes/read-pod.yaml\n--------------------------\nNo file to patch.  Skipping patch.\n1 out of 1 hunk ignored\nThe text leading up to this was:\n--------------------------\n|diff --git a/nfs/deploy/kubernetes/write-pod.yaml b/nfs/deploy/kubernetes/write-pod.yaml\n|index 99f7d02..e6c3fb4 100644\n|--- a/nfs/deploy/kubernetes/write-pod.yaml\n|+++ b/nfs/deploy/kubernetes/write-pod.yaml\n--------------------------\nNo file to patch.  Skipping patch.\npatch unexpectedly ends in middle of line\n1 out of 1 hunk ignored\n"
}
```

**Comment by dove-young** [comment]
This problem can be workaround by change playbook in this way

```
- hosts: master
  vars:
    argocd_server_external: "{{ groups['worker'][0]}}"
    nfs_src: "{{playbook_dir}}/external-storage/nfs/deploy/kubernetes"
  tasks:
    - name: Clone nfs provider
      git:
        repo: 'https://github.com/kubernetes-incubator/external-storage.git'
        dest: "{{playbook_dir}}/external-storage"
        depth: 1
        update: yes
        force: yes
    - name: patch nfs provider
      patch:
        src: "{{playbook_dir}}/files/nfs-provider.patch"
#       basedir: "{{playbook_dir}}/external-storage/nfs/deploy/kubernetes"
        basedir: "{{playbook_dir}}/external-storage"
        strip: 1
```

But this behavior is different than what was mentioned in `man patch`

`and not specifying -p at all just gives you blurfl.c. Whatever you end up with is looked for either in the current directory, or the directory specified by the -d option.`
