### ISSUE TITLE
Ansible 2.9.0 dynamic variable via set_fact stopped working in with_dict loop

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#64169]
##### SUMMARY

Ansible 2.8.x and earlier did not have an issue on any OS with an interpolated variable like `php{{ php_version }}` via `set_fact` using a loop, but it seems with 2.9.0, a variable set this way may cause issues:

```yaml
- name: Define PHP variables.
  set_fact: "{{ item.key }}={{ hostvars[inventory_hostname][item.value] }}"
  when:
    - hostvars[inventory_hostname][item.key] is undefined
    - hostvars[inventory_hostname][item.value] is defined
  with_dict:
    php_conf_paths: __php_conf_paths
    ...
    php_packages: __php_packages
```

In the role's `vars/main.yml`:

```
__php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-apcu"
  - "php{{ php_version }}-cli"
  - "php{{ php_version }}-common"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-dev"
  - "php{{ php_version }}-fpm"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-imap"
  - "php{{ php_version }}-json"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-opcache"
  - "php{{ php_version }}-sqlite3"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-yaml"
```

See role where this is done: https://github.com/geerlingguy/ansible-role-php-versions

I first noticed this on my Drush role as it started failing CI tests today, after I upgraded all my test environments to 2.9.0: https://travis-ci.org/geerlingguy/ansible-role-drush/jobs/605737820#L624

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

Core.

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
N/A - no overrides
```

##### OS / ENVIRONMENT

  - Ubuntu 18.04
  - Debian 9

##### STEPS TO REPRODUCE

  1. Clone or install the `geerlingguy.php-versions` role locally.
  2. Change directories into that role's root directory.
  3. (Make sure Molecule is installed) Run `MOLECULE_DISTRO=ubuntu1804 molecule test`

##### EXPECTED RESULTS

```
    TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
    changed: [instance]
```

##### ACTUAL RESULTS

```
    TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
    fatal: [instance]: FAILED! => {"changed": false, "msg": "No package matching 'php{{ php_version }}' is available"}
```

Note that when I run the `geerlingguy.php` role on its own (without php-versions or drush on top), the variable is interpreted correctly (but it is not through `set_fact` / `with_dict`...). So it seems like this might be an issue with overrides of variables via `set_fact` in a loop somewhere down the chain. I'm trying to figure out exactly what step is going wrong.
