### ISSUE TITLE
version_compare filter not working in Ansible 2.9.0, worked in 2.8.x

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#64174]
##### SUMMARY

I am using the `version_compare` filter in a task's `when` condition. In 2.8.x and earlier, the filter worked, but in 2.9.0 I get an error message.

See failed CI job from `geerlingguy.git` role: https://travis-ci.org/geerlingguy/ansible-role-git/jobs/605770099#L526

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

version_compare filter

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jgeerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Apr 12 2019, 15:32:40) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION

```
N/A (empty)
```

##### OS / ENVIRONMENT

  - Any (tested CentOS 7, Ubuntu 18.04)

##### STEPS TO REPRODUCE

  1. Download the `geerlingguy.git` role.
  2. (Ensure Molecule is installed) Run `MOLECULE_PLAYBOOK=playbook-source.yml molecule test`

```yaml
- name: Get installed version.
  command: >
    git --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: git_installed_version

- name: Force git install if the version numbers do not match.
  set_fact:
    git_reinstall_from_source: true
  when:
    - git_install_from_source_force_update | bool
    - (git_installed_version.rc == 0) and (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") | version_compare(git_version, operator="!="))
```

##### EXPECTED RESULTS

```
    TASK [geerlingguy.git : Force git install if the version numbers do not match.] ***
    changed: [instance]
```

##### ACTUAL RESULTS

```
    TASK [geerlingguy.git : Force git install if the version numbers do not match.] ***
    fatal: [instance]: FAILED! => {"msg": "The conditional check '(git_installed_version.rc == 0) and (git_installed_version.stdout | regex_replace(\"^.*?([0-9\\.]+)$\", \"\\\\1\") | version_compare(git_version, operator=\"!=\"))' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if (git_installed_version.rc == 0) and (git_installed_version.stdout | regex_replace(\"^.*?([0-9\\.]+)$\", \"\\\\1\") | version_compare(git_version, operator=\"!=\")) %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/travis/build/geerlingguy/geerlingguy.git/tasks/install-from-source.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Force git install if the version numbers do not match.\n  ^ here\n"}
```

More specific message from above:

```
template error while templating string: no filter named 'version_compare'
```
