### ISSUE TITLE
Ansible script fails on Proprietary CLI

### ISSUE THREAD

**Issue by vijaychebium** [ansible/ansible#64170]
Ansible script:
#Play book to push config file

```yaml
- name: First Play
  hosts: CNDBW
  gather_facts: false
  tasks:
   - name: First Task
     become: true 
     cli_command:
        command: show version
     register: command_output

   - name: PRINT TO TERMINAL WINDOW
     debug:
       msg: "{{command_output.stdout}}"
```

ansible-playbook first.yml -v

When I ran the above command I am getting the following error

```
fatal: [10.xxx.xxx.xxx.xxx]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "unable to elevate privilege to enable mode, at prompt [\n[local]CNDBW# ] with error: enable\r\r\nThursday October 31 23:29:42 UTC 2019\r\nIncomplete command\r\n[local]CNDBW# "}
```
