### ISSUE TITLE
zabbix_host add tags support

### ISSUE THREAD

**Issue by ikzelf** [ansible/ansible#64278]
##### SUMMARY

zabbix_host already has support for the inventory tag and Asset tag but the general host tags are still missing. They would be a nice addition.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_host.py

##### ADDITIONAL INFORMATION

It would make event correlation a bit easier and I am sire many more things.

```yaml
- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: "{{zabbix_server.url}}"
    login_user: "{{zabbix_server.username}}"
    login_password: "{{zabbix_server['password']}}"
    host_name: "{{item.name}}"
    host_groups: "{{item.groups | default(omit)}}"
    link_templates: "{{item.templates | default(omit)}}"
    tags: "{{item.tags}}"
    state: "{{item.state}}"
    status: "{{item.status}}"
    inventory_mode: automatic
    inventory_zabbix:
      asset_tag: "{{item.CI}}"
      alias: "{{item.HOST}}"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: 127.0.0.1
        dns: ""
        port: 10050
  with_items:
```

tags would need to be a list of name value pairs.
