### ISSUE TITLE
vmware_guest Module - VM Advanced Options fail with Ansible 2.9.0

### ISSUE THREAD

**Issue by vMarkusK** [ansible/ansible#64291]
##### SUMMARY

Adding VMware VM with Advanced Options fails since Ansible 2.9.0. The same Playbook was fine with Ansible 2.8.5

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT

- VMware vSphere 6.7 Update 2

##### STEPS TO REPRODUCE

```yaml
- name: Create a VM with security configuration
  hosts: localhost
  gather_facts: no
  vars:
    vm_datacenter: lab
    vm_cluster: cluster01
    vm_folder: /{{ vm_datacenter }}/vm/
    vm_name: test_vm_01
    vm_cpu: 1
    vm_mem: 256
    vm_datastore: datastore1
    vm_network: DPortGroup1
  tasks:
  - name: Check for existing VM with the same name
    vmware_guest_facts:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vm_datacenter }}"
      validate_certs: no
      name: "{{ vm_name }}"
    ignore_errors: True
    register: vm_find
  - fail:
      msg: "The VM already exists."
    when: vm_find is succeeded 
  - name: Create new VM - {{ vm_name }}
    vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vm_datacenter }}"
        cluster: "{{ vm_cluster }}"
        validate_certs: no
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}" 
        state: poweredoff
        guest_id: rhel7_64Guest
        datastore: "{{ vm_datastore }}"
        disk:
          - size_gb: 10
        hardware:
            memory_mb: "{{ vm_mem }}"
            memory_reservation: "{{ (vm_mem / 2) | int }}"
            num_cpus: "{{ vm_cpu }}"
            cpu_reservation: "{{ (vm_cpu * 256) | int }}"
            scsi: paravirtual
            boot_firmware: efi
        networks:
          - name: "{{ vm_network }}"
            device_type: vmxnet3
        customvalues:
          - key: "isolation.tools.copy.disable"
            value: "True"
          - key: "isolation.tools.paste.disable"
            value: "True"
          - key: "isolation.tools.diskShrink.disable"
            value: "True"
          - key: "isolation.tools.diskWiper.disable"
            value: "True"
          - key: "mks.enable3d"
            value: "False"
          - key: "tools.setInfo.sizeLimit"
            value: "1048576"
          - key: "RemoteDisplay.vnc.enabled"
            value: "False"
          - key: "tools.guestlib.enableHostInfo"
            value: "False"
        wait_for_ip_address: no
    register: vm_deploy
  - name: Enable UEFI SecureBoot for {{ vm_name }}
    vmware_guest_boot_manager:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      uuid: '{{ vm_deploy.instance.hw_product_uuid }}'
      secure_boot_enabled: True
```

##### EXPECTED RESULTS

Creates a New VMware vSphere VM with additional Advanced Options

##### ACTUAL RESULTS

vSphere VM is created but Advanced Options are not set and playbook failes:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find custom value key isolation.tools.copy.disable"}

```paste below
[root@ansible Ansible-Playground]# ansible-playbook --vault-password-file ~/.vault_pass.txt vmware_create_vm_secure.yml -vvv
ansible-playbook 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)

PLAYBOOK: vmware_create_vm_secure.yml **************************************************************************************************
1 plays in vmware_create_vm_secure.yml

PLAY [Create a VM with security configuration] *****************************************************************************************
META: ran handlers

TASK [Check for existing VM with the same name] ****************************************************************************************
task path: /root/Ansible-Playground/vmware_create_vm_secure.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611 `" && echo ansible-tmp-1572636427.93-26968377012611="` echo /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/_vmware_guest_facts.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-2124pX3ZTr/tmpWNvpZn TO /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611/AnsiballZ__vmware_guest_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611/ /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611/AnsiballZ__vmware_guest_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611/AnsiballZ__vmware_guest_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1572636427.93-26968377012611/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: The 'vmware_guest_facts' module has been renamed to 'vmware_guest_info'. This feature will be removed in version
 2.13. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "datacenter": "lab", 
            "folder": null, 
            "hostname": "192.168.234.100", 
            "moid": null, 
            "name": "test_vm_01", 
            "name_match": "first", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "properties": null, 
            "proxy_host": null, 
            "proxy_port": null, 
            "schema": "summary", 
            "tags": false, 
            "use_instance_uuid": false, 
            "username": "Administrator@vSphere.local", 
            "uuid": null, 
            "validate_certs": false
        }
    }, 
    "msg": "Unable to gather information for non-existing VM test_vm_01"
}
...ignoring

TASK [fail] ****************************************************************************************************************************
task path: /root/Ansible-Playground/vmware_create_vm_secure.yml:24
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}

TASK [Create new VM - test_vm_01] ******************************************************************************************************
task path: /root/Ansible-Playground/vmware_create_vm_secure.yml:27
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398 `" && echo ansible-tmp-1572636428.99-84111991973398="` echo /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-2124pX3ZTr/tmpDSvCgt TO /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398/AnsiballZ_vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398/ /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398/AnsiballZ_vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1572636428.99-84111991973398/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": [], 
            "cluster": "cluster01", 
            "convert": null, 
            "customization": {}, 
            "customization_spec": null, 
            "customvalues": [
                {
                    "key": "isolation.tools.copy.disable", 
                    "value": "True"
                }, 
                {
                    "key": "isolation.tools.paste.disable", 
                    "value": "True"
                }, 
                {
                    "key": "isolation.tools.diskShrink.disable", 
                    "value": "True"
                }, 
                {
                    "key": "isolation.tools.diskWiper.disable", 
                    "value": "True"
                }, 
                {
                    "key": "mks.enable3d", 
                    "value": "False"
                }, 
                {
                    "key": "tools.setInfo.sizeLimit", 
                    "value": "1048576"
                }, 
                {
                    "key": "RemoteDisplay.vnc.enabled", 
                    "value": "False"
                }, 
                {
                    "key": "tools.guestlib.enableHostInfo", 
                    "value": "False"
                }
            ], 
            "datacenter": "lab", 
            "datastore": "datastore1", 
            "disk": [
                {
                    "size_gb": 10
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/lab/vm/", 
            "force": false, 
            "guest_id": "rhel7_64Guest", 
            "hardware": {
                "boot_firmware": "efi", 
                "cpu_reservation": "256", 
                "memory_mb": 256, 
                "memory_reservation": "128", 
                "num_cpus": 1, 
                "scsi": "paravirtual"
            }, 
            "hostname": "192.168.234.100", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "test_vm_01", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "name": "DPortGroup1", 
                    "type": "dhcp"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "proxy_host": null, 
            "proxy_port": null, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredoff", 
            "state_change_timeout": 0, 
            "template": null, 
            "use_instance_uuid": false, 
            "username": "Administrator@vSphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_customization": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "Unable to find custom value key isolation.tools.copy.disable"
}

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=1   
```
