### ISSUE TITLE
azure_rm_networkinterface , problem adding static private ip and public ip to network interface card.

### ISSUE THREAD

**Issue by rewilliams1** [ansible/ansible#64357]
##### SUMMARY
I am attempting to create a network interface with a static private ip address, and a dynamic public ip on the same NIC. 

Wherever , primary is set under ip_configurations is what gets set on the VM. If its set for the static private ip address then the private ip address is set correctly. If the public ip is set to primary then the vm will get a public ip but the private ip is not set to what I statically set it to. The playbook does not error out. If I look in the console at the public ip address that was created by playbook , it says that it is attached to the correct NIC and VM, although the vm does not have the public ip and you can not access the server via public ip. If I go into the public ip resource and then attach it , this works just fine.

This is done here using powershell.
 https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-multiple-ip-addresses-powershell

Done here using azure cli.
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-multiple-ip-addresses-cli

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_networkinterface
##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = None
  configured module search path = ['/Users/rwilliams/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rwilliams/environments/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/rwilliams/environments/ansible/bin/ansible
  python version = 3.7.4 (default, Oct 12 2019, 18:55:28) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
  - name: Create a public ip address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      name: my_public_ip
      allocation_method: dynamic
      domain_name: "{{ db_server_pub_dns }}"

  - name: Create a network with mutilple ip configurations
    azure_rm_networkinterface:
      name: "{{ db_network_interface }}"
      resource_group: "{{ resource_group }}"
      subnet_name: "{{ subnet_name }}"
      virtual_network: "{{ vnet_name }}"
      security_group:
        name: "{{ network_db_sg }}"
        resource_group: "{{ resource_group }}"
      ip_configurations:
        - name: private-ipconfig1
          private_ip_address: "{{ private_ip_address }}"
          private_ip_allocation_method: Static
          primary: yes
        - name: public-ipconfig1
          public_ip_address_name: my_public_ip

  - name: Create VM
    azure_rm_virtualmachine:
      ad_user: "{{ ad_username }}"
      password: "{{ ad_password }}"
      resource_group: "{{ resource_group }}"
      name: "{{ db_server_name }}"
      vm_size: Standard_E4s_v3
      os_disk_caching: ReadWrite
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      subnet_name: "{{ subnet_name }}"
      virtual_network_name: "{{ vnet_name }}"
      network_interface_names: "{{ db_network_interface }}"
      managed_disk_type: Standard_LRS
      image:
        id: /subscriptions/{{ subscription_id }}/resourceGroups/{{ image_gallery_resource_group }}/providers/Microsoft.Compute/galleries/{{ gallery_name }}/images/{{ shared_image_name }}/versions/{{ shared_image_version }}
    tags:
      - create-vm
```

##### ACTUAL RESULTS

The public ip is not accessible from vm.
[Screenshots Ansible Possible Bug.docx](https://github.com/ansible/ansible/files/3801328/Screenshots.Ansible.Possible.Bug.docx)

```paste below

```
