### ISSUE TITLE
VMware: Unable to create vSphere Cluster in idempotent manner

### ISSUE THREAD

**Issue by kclinden** [ansible/ansible#64354]
##### SUMMARY
Playbook fails on create vSphere Cluster when running second time

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_cluster

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/klinden/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/klinden/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/klinden/hosts']
```

##### OS / ENVIRONMENT

Ubuntu on Windows 2019 WSL
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
##### STEPS TO REPRODUCE

Run playbook a second time on an empty vCenter instance.

```yaml
---
# Configure vCenter

- name: Configure vCenter
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: vcsa-01a.corp.local
    vcenter_username: 'administrator@regiona.local'
    vcenter_password: 'VMware1!'
    datacenter_name: 'OneCloud'
    cluster_name: 'Cluster-01'
    esxi_hostname: esx-01a.corp.local
    esxi_username: 'root'
    esxi_password: 'VMware1!'
    validate_certs: false
    state: present
  tasks:
    - name: Create Datacenter
      vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        validate_certs: '{{ validate_certs }}'
        state: present
    - name: Create Cluster
      vmware_cluster:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ validate_certs }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }} '
        state: present
    - name: Add ESXi Host to vCenter
      vmware_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ validate_certs }}'
        datacenter: '{{ datacenter_name }}'
        cluster: '{{ cluster_name }} '
        esxi_hostname: '{{ esxi_hostname }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present

```

##### ACTUAL RESULTS

```paste below

```
