### ISSUE TITLE
Use streaming for the replace module to avoid memory issues

### ISSUE THREAD

**Issue by dploeger** [ansible/ansible#64353]
##### SUMMARY
The replace module reads in the complete file into memory and works from there. This causes problems with big files (i.e. database dumps). As a suggestion, support a stream option, which will read the file using streams line by line (this obviously removes the multiline regexp feature).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
replace

##### ADDITIONAL INFORMATION
I tried modifying database dumps while building up a playbook, that clones production into an integration environment. The dump was 1.7GB big and processing it killed the Python process.

```yaml
- name: "Replace on a big file"
   replace:
     path: "big_file.txt"
     regexp: "some.*regex"
     replace: "something different"
     use_stream: "yes
```
