### ISSUE TITLE
postgresql_privs always reports as changed when using default_privs

### ISSUE THREAD

**Issue by anasbouzid** [ansible/ansible#64371]
##### SUMMARY
The `postgresql_privs` module always reports as changed if the `type` option is `default_privs`. Ansible adds multiple psql commands before running the actual task (see the verbatim command output bellow), I don't know why it's implemented like this, but such behavior leads to unexpected results: My issue isn't that risky, but if you try to revoke a privilege from a `sequence` (using `state: absent`), it will also revoke all default `table` and `type` privileges.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_privs

##### ANSIBLE VERSION
```
ansible 2.8.6
  config file = /home/razor/ansible-bug/ansible.cfg
  configured module search path = ['/home/razor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/razor/.pyenv/versions/3.7.0/lib/python3.7/site-packages/ansible
  executable location = /home/razor/.pyenv/versions/3.7.0/bin/ansible
  python version = 3.7.0 (default, Nov  3 2019, 02:20:02) [GCC 4.8.4]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/razor/ansible-bug/ansible.cfg) = ['/home/razor/ansible-bug/inventories/development']
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
Create a test.yml file with the playbook below:

```yaml
- name: Configure and deploy PostgreSQL
  hosts: all
  become: yes
  vars:
    - role_name: role_test
    - database_name: database_test
    - postgresql_privs:
      - roles: "{{ role_name }}"
        db: "{{ database_name }}"
        privileges:
          - privs: SELECT,INSERT,UPDATE,DELETE
            type: default_privs
            objs: TABLES
            schema: public
          - privs: SELECT,UPDATE
            type: default_privs
            objs: SEQUENCES
            schema: public
  tasks:
    - name: PostgreSQL databases
      postgresql_db:
        name: "{{ database_name }}"
      become_user: postgres

    - name: PostgreSQL users
      postgresql_user:
        name: "{{ role_name }}"
      become_user: postgres

    - name: PostgreSQL privileges
      postgresql_privs:
        roles: "{{ item.0.roles }}"
        db: "{{ item.0.db }}"
        privs: "{{ item.1.privs }}"
        type: "{{ item.1.type }}"
        objs: "{{ item.1.objs | default(omit) }}"
        schema: "{{ item.1.schema | default(omit) }}"
        state: "{{ item.1.state | default(item.0.state | default('present')) }}"
      with_subelements:
        - "{{ postgresql_privs }}"
        - privileges
      become_user: postgres
```

Run the following command **twice**:
```
ansible-playbook test.yml
```

##### EXPECTED RESULTS
The task "PostgreSQL privileges" should report as "ok" at the second run.

##### ACTUAL RESULTS
The task "PostgreSQL privileges" always shows "changed".

```paste below
TASK [Ensure PostgreSQL privileges are present] ***************************************************************************************************************
changed: [acme.test] => (item=[{'roles': 'role_test', 'db': 'database_test'}, {'privs': 'SELECT,INSERT,UPDATE,DELETE', 'type': 'default_privs', 'objs': 'TABLES', 'schema': 'public'}]) => {"ansible_loop_var": "item", "changed": true, "item": [{"db": "database_test", "roles": "role_test"}, {"objs": "TABLES", "privs": "SELECT,INSERT,UPDATE,DELETE", "schema": "public", "type": "default_privs"}], "queries": ["ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM \"role_test\";\nALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT UPDATE,INSERT,SELECT,DELETE ON TABLES TO \"role_test\";\nALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON TYPES TO \"role_test\";"]}
changed: [acme.test] => (item=[{'roles': 'role_test', 'db': 'database_test'}, {'privs': 'SELECT,UPDATE', 'type': 'default_privs', 'objs': 'SEQUENCES', 'schema': 'public'}]) => {"ansible_loop_var": "item", "changed": true, "item": [{"db": "database_test", "roles": "role_test"}, {"objs": "SEQUENCES", "privs": "SELECT,UPDATE", "schema": "public", "type": "default_privs"}], "queries": ["ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM \"role_test\";\nALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT UPDATE,SELECT ON SEQUENCES TO \"role_test\";\nALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON TYPES TO \"role_test\";"]}
```
