### ISSUE TITLE
docker_compose module crashes with error about a non empty directory

### ISSUE THREAD

**Issue by rhythmicdevil** [ansible/ansible#64387]
I have searched Github but all the responses are to upgrade to versions I am already running. 

##### SUMMARY
docker_compose module crashes with error
    
    [Errno 39] Directory not empty: '/tmp/ansibleGUnKQP'\r\n

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_compose

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /home/deployer/eclipse-workspace-jee/Playbooks/ansible.cfg
  configured module search path = [u'/home/deployer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/deployer/eclipse-workspace-jee/Playbooks/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes
DEFAULT_SCP_IF_SSH(/home/deployer/eclipse-workspace-jee/Playbooks/ansible.cfg) = True
DEFAULT_TIMEOUT(/home/deployer/eclipse-workspace-jee/Playbooks/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/deployer/eclipse-workspace-jee/Playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT
**Control Machine**
CentOS Linux release 7.7.1908 (Core)
Python 2.7.5

**Target machine**
CentOS Linux release 7.6.1810 (Core)
Python 2.7.5

Verified that docker for python is on the target

```
[root@vision360apps ~]# pip install docker
Requirement already satisfied (use --upgrade to upgrade): docker in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/lib/python2.7/site-packages (from docker)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/lib/python2.7/site-packages (from docker)
Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/site-packages (from docker)
Requirement already satisfied (use --upgrade to upgrade): docker-pycreds>=0.4.0 in /usr/lib/python2.7/site-packages (from docker)
Requirement already satisfied (use --upgrade to upgrade): requests!=2.18.0,>=2.14.2 in /usr/lib/python2.7/site-packages (from docker)
Requirement already satisfied (use --upgrade to upgrade): idna<2.8,>=2.5 in /usr/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.25,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests!=2.18.0,>=2.14.2->docker)
```

Verified that docker-compose for Python is installed on target
```
[root@vision360apps ~]# pip install docker-compose
Requirement already satisfied (use --upgrade to upgrade): docker-compose in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): docker[ssh]<4.0,>=3.7.0 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): six<2,>=1.3.0 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): PyYAML<4.3,>=3.10 in /usr/lib64/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): texttable<0.10,>=0.9.0 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): dockerpty<0.5,>=0.4.1 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): websocket-client<1.0,>=0.32.0 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): enum34<2,>=1.0.4; python_version < "3.4" in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): docopt<0.7,>=0.6.1 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): jsonschema<3,>=2.5.1 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): cached-property<2,>=1.2.0 in /usr/lib/python2.7/site-packages (from docker-compose)
Requirement already satisfied (use --upgrade to upgrade): docker-pycreds>=0.4.0 in /usr/lib/python2.7/site-packages (from docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): paramiko>=2.4.2; extra == "ssh" in /usr/lib/python2.7/site-packages (from docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): idna<2.8,>=2.5 in /usr/lib/python2.7/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.25,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): functools32; python_version == "2.7" in /usr/lib/python2.7/site-packages (from jsonschema<3,>=2.5.1->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=2.5 in /usr/lib64/python2.7/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): pynacl>=1.0.1 in /usr/lib64/python2.7/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): bcrypt>=3.1.3 in /usr/lib64/python2.7/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=2.5->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): cffi!=1.11.3,>=1.8 in /usr/lib64/python2.7/site-packages (from cryptography>=2.5->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.5->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose)
```

##### STEPS TO REPRODUCE
Execute the playbook. 

    ansible-playbook -vvv -i inventory/eti-evolution eti-evolution.yml --limit="webapps"

**Playbook**
```
#
# All Hosts
#
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    playbook_name: eti-evolution.yml 
    playbook_env:
      PATH: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/informix/bin:/usr/cbridge/bin:/usr/cbridge/jam/rh3:/root/bin"
  roles:
  - role: common
  - role: docker

#
# Vision 360 Applications running as dockerized spring boot apps
#      
- hosts: webapps
  become: true
  become_user: root
  become_method: sudo
  vars:
    playbook_name: eti-evolution.yml
    docker: true
    eti_config: "/var/lib/docker/volumes/webapps_config/_data/"  
    database_server: "vision360triad.dev.etisoftware.local" 
    mongo_server: "ftrmongo.dev.etisoftware.local"  
    playbook_env:
      PATH: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/informix/bin:/usr/cbridge/bin:/usr/cbridge/jam/rh3:/root/bin"
  environment:  "{{ playbook_env | combine(proxy_env) }}"
  roles:
  - role: docker_vision360_apps
  - role: connection_pool

```

**Role**
```
---
- name: Setup the ETI Config external volume
  docker_volume:
    name: webapps_config

- name: Setup Vision360 Apps as Docker Compose services
  docker_compose:
    project_name: vision360_web_apps
    definition:
      version: '3.7'
      services:
        nginx: 
          image: etisoftware/nginx:latest
          container_name: dev_nginx
          volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
          ports:
            - 80:80
            - 443:443
          depends_on:
            - adminpanel
            - launchpad
            - manager
        adminpanel:
          image: etisoftware/adminpanel:1.1.0-SNAPSHOT
          container_name: adminpanel
          expose:
            - 8080
          volumes:
            - type: volume
              source: logs
              target: /usr/cbridge/msg
              volume:
                nocopy: true
          environment:
            - SPRING_BOOT_ADMIN_TITLE=Tech Support Admin Panel
        launchpad:
          image: etisoftware/launchpad:2.1.0-SNAPSHOT
          container_name: launchpad
          volumes:
            - type: volume
              source: logs
              target: /usr/cbridge/msg
              volume:
                nocopy: true
            - type: volume
              source: webapps_config
              target: /usr/cbridge/config
              volume:
                nocopy: true
          environment:
              - server.port=8080
              - logging.level.com.etisoftware=debug
              - management.endpoint.logfile.enabled=true
              - spring.boot.admin.client.url=http://adminpanel:8080/AdminPanel
              - spring.boot.admin.client.instance.management-url=http://launchpad:8080/LaunchPad/manage
              - spring.boot.admin.client.instance.health-url=http://launchpad:8080/LaunchPad/manage/health
          expose:
            - 8080
        manager:
          image: etisoftware/manager:2.2.0-SNAPSHOT
          container_name: manager
          volumes:
            - type: volume
              source: logs
              target: /usr/cbridge/msg
              volume:
                nocopy: true
            - type: volume
              source: webapps_config
              target: /usr/cbridge/config
              volume:
                nocopy: true
          environment:
              - server.port=8080
              - spring.boot.admin.client.url=http://adminpanel:8080/AdminPanel
              - spring.boot.admin.client.instance.management-url=http://manager:8080/Manager/manage
              - spring.boot.admin.client.instance.health-url=http://manager:8080/Manager/manage/health
              - logging.level.com.etisoftware=debug
          expose:
            - 8080
      volumes:
        logs:
        webapps_config:
          external: true
```

##### EXPECTED RESULTS
I expect that the services start. This is the case when I take the docker compose service definition out of the ansible and execute it with docker-compose up

##### ACTUAL RESULTS
Ansible performs all tasks up to the docker_compose task and then crashes out. 

```
TASK [docker_vision360_apps : Setup Vision360 Apps as Docker Compose services] ******************************************************************************************************************
task path: /home/deployer/eclipse-workspace-jee/Playbooks/roles/docker_vision360_apps/tasks/main.yml:31
<vision360apps.dev.etisoftware.local> ESTABLISH SSH CONNECTION FOR USER: None
<vision360apps.dev.etisoftware.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 vision360apps.dev.etisoftware.local '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<vision360apps.dev.etisoftware.local> (0, '/home/deployer\n', '')
<vision360apps.dev.etisoftware.local> ESTABLISH SSH CONNECTION FOR USER: None
<vision360apps.dev.etisoftware.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 vision360apps.dev.etisoftware.local '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862 `" && echo ansible-tmp-1572873099.58-240310869440862="` echo /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862 `" ) && sleep 0'"'"''
<vision360apps.dev.etisoftware.local> (0, 'ansible-tmp-1572873099.58-240310869440862=/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_compose.py
<vision360apps.dev.etisoftware.local> PUT /home/deployer/.ansible/tmp/ansible-local-8170YQLyHG/tmp0IWnjH TO /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py
<vision360apps.dev.etisoftware.local> SSH: EXEC scp -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 /home/deployer/.ansible/tmp/ansible-local-8170YQLyHG/tmp0IWnjH '[vision360apps.dev.etisoftware.local]:/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py'
<vision360apps.dev.etisoftware.local> (0, '', '')
<vision360apps.dev.etisoftware.local> ESTABLISH SSH CONNECTION FOR USER: None
<vision360apps.dev.etisoftware.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 vision360apps.dev.etisoftware.local '/bin/sh -c '"'"'chmod u+x /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/ /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py && sleep 0'"'"''
<vision360apps.dev.etisoftware.local> (0, '', '')
<vision360apps.dev.etisoftware.local> ESTABLISH SSH CONNECTION FOR USER: None
<vision360apps.dev.etisoftware.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -tt vision360apps.dev.etisoftware.local '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-obavonvvyrdlpgfkkteyqlnmblsbuwiy ; PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/informix/bin:/usr/cbridge/bin:/usr/cbridge/jam/rh3:/root/bin /usr/bin/python /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<vision360apps.dev.etisoftware.local> (1, 'Traceback (most recent call last):\r\n  File "/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py", line 114, in <module>\r\n    _ansiballz_main()\r\n  File "/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py", line 49, in invoke_module\r\n    imp.load_module(\'__main__\', mod, module, MOD_DESC)\r\n  File "/tmp/ansible_docker_compose_payload_Fue3IU/__main__.py", line 1151, in <module>\r\n  File "/tmp/ansible_docker_compose_payload_Fue3IU/__main__.py", line 1142, in main\r\n  File "/tmp/ansible_docker_compose_payload_Fue3IU/__main__.py", line 684, in exec_module\r\nOSError: [Errno 39] Directory not empty: \'/tmp/ansibleGUnKQP\'\r\n', 'Shared connection to vision360apps.dev.etisoftware.local closed.\r\n')
<vision360apps.dev.etisoftware.local> Failed to connect to the host via ssh: Shared connection to vision360apps.dev.etisoftware.local closed.
<vision360apps.dev.etisoftware.local> ESTABLISH SSH CONNECTION FOR USER: None
<vision360apps.dev.etisoftware.local> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 vision360apps.dev.etisoftware.local '/bin/sh -c '"'"'rm -f -r /home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/ > /dev/null 2>&1 && sleep 0'"'"''
<vision360apps.dev.etisoftware.local> (0, '', '')
fatal: [vision360apps.dev.etisoftware.local]: FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to vision360apps.dev.etisoftware.local closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/deployer/.ansible/tmp/ansible-tmp-1572873099.58-240310869440862/AnsiballZ_docker_compose.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_docker_compose_payload_Fue3IU/__main__.py\", line 1151, in <module>\r\n  File \"/tmp/ansible_docker_compose_payload_Fue3IU/__main__.py\", line 1142, in main\r\n  File \"/tmp/ansible_docker_compose_payload_Fue3IU/__main__.py\", line 684, in exec_module\r\nOSError: [Errno 39] Directory not empty: '/tmp/ansibleGUnKQP'\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

PLAY RECAP **************************************************************************************************************************************************************************************
vision360apps.dev.etisoftware.local : ok=23   changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

I have tried removing all the containers, images, and volumes
I have tried removing all the directories under /home/deployer/.ansible and /tmp
