### ISSUE TITLE
azure_rm_virtualmachine does not preserve availability zone info with generalized option

### ISSUE THREAD

**Issue by mnaccarato** [ansible/ansible#64404]
##### SUMMARY
When you try to generalize a vm with availability zones defined in it, zone info is not preserved and must be passed on.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [ u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

When you try to generalize a vm with availability zones defined in it, zone info is not preserved and must be passed on.

 Furthermore zone information it’s not returned by azure_rm_virtualmachine_info so it has to be gathered with azure_rm_resource_info in order to be able to generalize the vm

```yaml
- name: Generalize VM
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vm }}"
    os_type: "{{ os_type | default(omit) }}"
    generalized: yes
    state: present 

```

##### EXPECTED RESULTS

Generalized VM

##### ACTUAL RESULTS

```paste below
    "msg": "You can't change the Availability Zone of a virtual machine (have: [<zone>], want: None)"

```
##### WORKAROUND
In order to be able to generalize the VM the following code should be used.

```yaml
- name: Get VM Availability Zone
  azure_rm_resource_info:
    resource_group: "{{ resourcegroup }}"
    resource_name: "{{ vm }}"
    resource_type: VirtualMachines 
    provider: Compute
  register: result

- name: Generalize VM
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vm }}"
    os_type: "{{ os_type | default(omit) }}"
    generalized: yes
    state: present
    zones: "{{ result.response[0].zones }}"
```
