### ISSUE TITLE
Can no longer create/retrieve OpenShift Templates using k8s module

### ISSUE THREAD

**Issue by wkulhanek** [ansible/ansible#64405]
##### SUMMARY
EPEL recently updated from the openshift python library 0.8 to 0.9. This broke the k8s module trying to create/retrieve templates.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s module

##### ANSIBLE VERSION

```paste below
ansible 2.7.9
```

##### OS / ENVIRONMENT
RHEL 7

##### STEPS TO REPRODUCE

```yaml
- name: Get All Templates
  hosts: localhost
  become: false
  tasks:
  - name: Retrieve Templates
    k8s_facts:
      kind: templates
      api_version: template.openshift.io/v1
      namespace: openshift
    register: r_templates
  - name: Print Result
    debug:
      msg: "{{ r_templates }}"
# this should be 120 on a new 4.2 OpenShift cluster
# but it is 0
  - name: Print Number
    debug:
      msg: "Found {{ r_templates.resources | length }} templates."
  - name: Print Templates
    debug:
      msg: "{{ item.metadata.name}}"
    loop: "{{ r_templates.resources }}"
  - name: Create Template
    k8s:
      state: present
      namespace: wk-test
      merge_type:
      - strategic-merge
      - merge
      definition: "{{ lookup('file', item ) | from_yaml }}"
    loop:
    - ./maria.yaml
```

Simplified mariadb template (also tried "kind: Template" instead of  "kind: templates" which worked until 0.8)
```yaml
apiVersion: template.openshift.io/v1
kind: templates
metadata:
  name: mariadb
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: ${DATABASE_SERVICE_NAME}
  stringData:
    database-name: ${MYSQL_DATABASE}
    database-password: ${MYSQL_PASSWORD}
    database-root-password: ${MYSQL_ROOT_PASSWORD}
    database-user: ${MYSQL_USER}
parameters:
- description: Username for MariaDB user that will be used for accessing the database.
  displayName: MariaDB Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: MYSQL_USER
  required: true
- description: Password for the MariaDB connection user.
  displayName: MariaDB Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_PASSWORD
  required: true
- description: Password for the MariaDB root user.
  displayName: MariaDB root Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Name of the MariaDB database accessed.
  displayName: MariaDB Database Name
  name: MYSQL_DATABASE
  required: true
  value: sampledb
```
##### EXPECTED RESULTS
Template gets created.

##### ACTUAL RESULTS

```paste below
fatal: [bastion.9ffa.example.opentlc.com]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": true, "cmd": ["oc", "apply", "-f", "-"], "delta": "0:00:00.994673", "end": "2019-11-04 16:26:23.618556", "msg": "non-zero return code", "rc": 1, "start": "2019-11-04 16:26:22.623883", "stderr": "error: unable to recognize \"STDIN\": no matches for kind \"templates\" in version \"template.openshift.io/v1\"", "stderr_lines": ["error: unable to recognize \"STDIN\": no matches for kind \"templates\" in version \"template.openshift.io/v1\""], "stdout": "", "stdout_lines": []}
```
@fabianvf
