### ISSUE TITLE
allow ec2_vpc_net to delete dependent objects

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#64406]
##### SUMMARY

The modules for AWS seem to equate one-to-one with actual AWS boto2 or boto3 API commands.  There is no additional logic in the Ansible Modules to deal with situations like this.  Because of this design choice and/or limitation we do not have the ability to easily do teardowns.  We must use multiple modules to perform a teardown happens to be a boto3 limitation:
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.delete_vpc
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteVpc.htm

From the documentation:

> You must detach or delete all gateways and resources that are associated with the VPC before you can delete it. For example, you must terminate all instances running in the VPC, delete all security groups associated with the VPC (except the default one), delete all route tables associated with the VPC (except the default one), and so on.

I propose we move this additional logic into the module code to make Ansible easy and match the web UI experience.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_vpc_net

##### ADDITIONAL INFORMATION

Since the VPC is the highest level function for infrastructure on AWS I vote that this is a function of the ec2_vpc_net module.  This could look something like this: 

```yaml
- name: delete AWS VPC {{ ec2_name_prefix }}
  ec2_vpc_net:
    name: "{{ ec2_name_prefix }}-vpc"
    cidr_block: "{{ ec2_subnet }}"
    region: "{{ ec2_region }}"
    state: absent
    delete_dependents: true  
```

For Red Hat employees I have outlined some additional information in Google Docs that may help: https://docs.google.com/document/d/1RWZVNAkvL2OkNAyGhIYImmQBY62PAcNxtgDMffg-L4E/edit?usp=sharing

You will not be able to see that unless you are a Red Hat employee, it has some internal projects that are not relevant to the open source community.
