### ISSUE TITLE
k8s deployment into openshift cancels deployment

### ISSUE THREAD

**Issue by mibaboo** [ansible/ansible#64429]
##### SUMMARY
I am create a deploymentconfig in openshift using the ansible k8s module. The deployment is being created and deploying however with each deploy it deploys a version then cancels and then deploys successfully. I am not sure why the deployment gets cancels.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s module

##### ANSIBLE VERSION

```paste below
ansible 2.6.17
  config file = /home/user/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/user/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/user/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s
ANSIBLE_SSH_CONTROL_PATH(/home/user/ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/home/user/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/ansible.cfg) = $HOME/ansible/facts
CACHE_PLUGIN_TIMEOUT(/home/user/ansible.cfg) = 600 
DEFAULT_CALLBACK_WHITELIST(/home/user/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/user/ansible.cfg) = 20
DEFAULT_GATHERING(/home/user/ansible.cfg) = smart
DEFAULT_ROLES_PATH(/home/user/ansible.cfg) = [u'/home/user/roles']
DEFAULT_TIMEOUT(/home/user/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/user/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/home/user/ansible.cfg) = ['secrets.py', '.pyc', '.cfg', '.crt', '.ini']
INVENTORY_UNPARSED_IS_FAILED(/home/user/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/user/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.7 (Maipo)
Openshift 3.11

##### STEPS TO REPRODUCE

1. Create an ansible role openshift_deployments
2. Create the template roles/openshift_deployments/templates/DeploymentConfig.j2
3. Create roles/openshift_deployments/tasks/main.yml 
4. Create a playbook playbook.yml

DeploymentConfig.j2
```yaml
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: {{APPLICATION_NAME}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{APPLICATION_NAME}}
    spec:
      containers:
      - name: {{APPLICATION_NAME}}
        image: docker-registry.default.svc:5000/{{OCP_PROJECT}}/demo:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - {{APPLICATION_NAME}}
        from:
          kind: ImageStreamTag
          name: 'demo:latest'
          namespace: {{OCP_PROJECT}}
      type: ImageChange
    - type: ConfigChange

```
main.yml
```yaml
---
- name: Create DeploymentConfig
  k8s:
    state: present
    definition: "{{ lookup('template', 'DeploymentConfig.j2') | from_yaml }}"
    host: "{{ ocp_master_api }}"
    api_key: '$API_KEY'
    namespace: "{{ OCP_PROJECT}}"

```
playbook.yml
```yaml
---
- name: OCP Deployments
  hosts: localhost
  gather_facts: True
  become: True
  vars:
    - APPLICATION_NAME: phpdemo
    - IMAGE_NAME: demo
    - IMAGE_TAG: latest
    - OCP_PROJECT: PROJECTNAME
  roles:
    - openshift_deployments

```

##### EXPECTED RESULTS

When running this playbook , a single deployment will start

##### ACTUAL RESULTS

When running this playbook , a deployment starts and immediately gets cancelled and another one is started.

```paste below

```
