### ISSUE TITLE
Git_Config Module Reports Changed Albeit Configuration Value is Not Changed

### ISSUE THREAD

**Issue by ktomk** [ansible/ansible#64438]
##### SUMMARY

When setting a configuration setting with the `git_config` module that already has this value (e.g. run the same task a second time on the same system), `git_config` still reports changed albeit the configuration setting has not been changed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git_config

##### ADDITIONAL INFORMATION

I don't know what the intention was for this module, as this could be a bug report and not a feature request but I filed this as a feature request as I don't know the project.

```yaml
# ...
        - name: 'git-config core.excludesfile'
          git_config:
            name: core.excludesfile
            scope: global
            value: '~/.gitignore'
          become: yes
          become_user: vagrant
# ...
```

(this is also the same if become not yes, I just have it in there as for the global scope. )
