### ISSUE TITLE
Akamai Cache purge using URI.PY

### ISSUE THREAD

**Issue by gjt11** [ansible/ansible#64448]
##### SUMMARY
I am using the Ansible uri.py to connect to Akamai API version 2 to delete cache content in Akamai.
Akamai no longer allow API version 2,and have discontinued it.
Hence why my Ansible jobs. keep failing 

Akamai informed me I must use their API Version 3
https://developer.akamai.com/api/core_features/fast_purge/v3.html
I can see in the uri.py it supports Interacts with HTTP and HTTPS web services and supports Digest, Basic and WSSE.

Akamai tell me the headers are not correctly formatted when I am trying to use their new API v3. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri.py

##### ANSIBLE VERSION
Ansible 2.8.6
Tower 3.5

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Red hat 7.6

##### STEPS TO REPRODUCE
```
---
# tasks file for akamai_purge

- name: Install python dependency
  pip: name={{item}} state=present
  with_items:
    - httplib2
  tags:
    - akamai_purge
    - akamai_purge_arl
    - akamai_purge_cpcode
    - akamai_status
    - akamai_purge_friendly

# Usage: ansible-playbook akamai.yml -i inventory/local --tags akamai_purge_arl -vv --extra-vars arl=http://www.example.com/graphics/picture.gif,http://www.example.com/documents/brochure.pdf
- name: Submit ARL Purge Request
  uri:
```

##### ACTUAL RESULTS

```paste below

```
