### ISSUE TITLE
vmware_guest_network unable to change portgroup

### ISSUE THREAD

**Issue by necouchman** [ansible/ansible#64456]
##### SUMMARY
I'm attempting to use the vmware_guest_network module to change the network associated with a particular interface on a bunch of virtual machines, but it seems as though it never tries to actually change the portgroup for the adapter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_network

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
```

##### OS / ENVIRONMENT
* OpenSuSE 42.3
* Python 2.7
* Connection to vCenter 6.0 on Windows

##### STEPS TO REPRODUCE

```yaml
    - name: Update network adapter
      vmware_guest_network:
        name: "{{ inventory_hostname }}"
        datacenter: Horizon_7
        cluster: Horizon_Cluster
        hostname: "{{ vchost }}"
        username: "{{ vcuser }}"
        password: "{{ vcpass }}"
        validate_certs: no
        networks:
          - name: "322-VDI"
            state: present
            label: "Network adapter 1"
            connected: false
      delegate_to: localhost
```

##### EXPECTED RESULTS
Network will be changed from its current portgroup to the new one listed in the "name" field above.

##### ACTUAL RESULTS
Network remains in existing configuration.

```paste below
TASK [Update network adapter] ****************************************************************************************************************************************************************************************************************
task path: /home/user/ansible/vsphere/network-vdi.yml:50
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: nick_couchman
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1572977679.95-73785211176372 `" && echo ansible-tmp-1572977679.95-73785211176372="` echo /tmp/ansible-tmp-1572977679.95-73785211176372 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_network.py
<localhost> PUT /home/user/.ansible/tmp/ansible-local-2500329XKtt/tmplLyFkx TO /tmp/ansible-tmp-1572977679.95-73785211176372/AnsiballZ_vmware_guest_network.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1572977679.95-73785211176372/ /tmp/ansible-tmp-1572977679.95-73785211176372/AnsiballZ_vmware_guest_network.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1572977679.95-73785211176372/AnsiballZ_vmware_guest_network.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1572977679.95-73785211176372/ > /dev/null 2>&1 && sleep 0'
changed: [WINVDI01 -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "cluster": "Horizon_Cluster", 
            "datacenter": "Horizon_7", 
            "esxi_hostname": null, 
            "folder": null, 
            "gather_network_info": false, 
            "hostname": "vcenter.domain.local", 
            "moid": null, 
            "name": "WINVDI01", 
            "networks": [
                {
                    "connected": false, 
                    "label": "Network adapter 1", 
                    "name": "322-VDI", 
                    "state": "present"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "proxy_host": null, 
            "proxy_port": null, 
            "username": "administrator@vsphere.local", 
            "uuid": null, 
            "validate_certs": false
        }
    }, 
    "network_data": {
        "0": {
            "allow_guest_ctl": true, 
            "connected": false, 
            "device_type": "VMXNET3", 
            "label": "Network adapter 1", 
            "mac_addr": "00:11:22:33:44:55", 
            "name": "313-VMW-VIEW-NET", 
            "start_connected": true, 
            "unit_number": 7, 
            "wake_onlan": true
        }
    }
}
```
Notice the `"name": "313-VMW-VIEW-NET"` line, in particular - this is what should be changed to the "322-VDI" setting.
