### ISSUE TITLE
Missing support for masterAuthorizedNetworksConfig, shieldedNodes, initialClusterVersion

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#64471]
##### SUMMARY
Add missing fields to duplicate GCP API to build Container Cluster

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_container_cluster

##### ADDITIONAL INFORMATION
Need to add masterAuthorizedNetworksConfig, shieldedNodes, and initialClusterVersion

```yaml
---
- hosts: localhost
  connection: local
  tasks:
  - name: create a cluster
    gcp_container_cluster:
      name: asia-southeast1-saas-cluster
      location: asia-southeast1
      addons_config:
        http_load_balancing:
          disabled: no
        horizontal_pod_autoscaling:
          disabled: no
      auth_kind: serviceaccount
      subnetwork: projects/saasprod-202018/regions/asia-southeast1/subnetworks/default
      resource_labels:
        type: saas
      private_cluster_config:
        enable_private_nodes: yes
        master_ipv4_cidr_block: 10.148.254.0/28
      ip_allocation_policy:
        use_ip_aliases: yes
      master_authorized_networks_config:
        enabled: true
        cidr_blocks:
          - display_name: Any
            cidr_block: 0.0.0.0/0
      default_max_pods_constraint:
        max_pods_per_node: '110'
      authenticator_groups_config: {}
      databaseEncryption:
        state: DECRYPTED
      shielded_nodes:
        enabled: true
      initial_cluster_version: 1.14.8-gke.2
```
