### ISSUE TITLE
ansible-playbook ignores --limit option

### ISSUE THREAD

**Issue by ovcharenko** [ansible/ansible#6449]
##### Issue Type:

BugReport
##### Ansible Version:

ansible 1.6 (d37f0c6d12)
##### Environment:

N/A
##### Summary:

ansible-playbook ignores --limit option.
##### Steps To Reproduce:

ansible-playbook hosts.yaml --limit=boo
##### Expected Results:

PLAY [Localhost] **************************************************************
skipping: no hosts matched

PLAY [All servers] ************************************************************
##### Actual Results:

PLAY [Localhost] **************************************************************

TASK: [setup] *****************************************************************
ok: [localhost]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by mpdehaan** [comment]
Can you please share your playbook?

**Comment by ovcharenko** [comment]
It's pretty simple:

```
- name: Localhost
  hosts: localhost
  sudo: no
  gather_facts: false
  tasks:
    - action: setup

- name: All hosts
  hosts: all
  sudo: no
  gather_facts: false
  tasks:
    - action: setup
```
