### ISSUE TITLE
please extend docs with extra example with failed_when

### ISSUE THREAD

**Issue by peterducai** [ansible/ansible#64520]
##### SUMMARY

please extend examples of error handling as it's not clear that following *DOES NOT* work

```
- name: check keys
    command: ssh-keygen -l -f {{item}}
    loop:
      - ~/.ssh/example_rsa_2k.pub
      - ~/.ssh/example_rsa_4k.pub
      - ~/.ssh/example_ed.pub
    register: sshout
    failed_when: >
      ("4096 " not in sshout.stdout) or
      ("ED25519" not in sshout.stdout)
```
but following *DOES* work
```
    failed_when: >
      not (("4096 " in sshout.stdout) or
      ("ED25519" in sshout.stdout))
```

PS:  existing documentation makes me thing both of these should work.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs

##### ANSIBLE VERSION

```paste below
latest
```
https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html

##### CONFIGURATION

```paste below

```
