### ISSUE TITLE
route53_info uses type string for <=2.9 and type int for greater than 2.10

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#64534]
##### SUMMARY
The task level parameter `max_items` for the route53_info uses a string for Ansible 2.9 and older, but for the development branch (2.10) and newer it uses an integer (type int)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
route53_info

##### ANSIBLE VERSION
```paste below

ansible 2.10.0.dev0

  config file = /etc/ansible/ansible.cfg

  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']

  ansible python module location = /root/.venv/lib/python2.7/site-packages/ansible

  executable location = /root/.venv/bin/ansible

  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
N/A, happening on multiple systems

##### OS / ENVIRONMENT
N/A, happening on multiple systems

##### STEPS TO REPRODUCE

For the parameter `max_items` just send a string on the development branch, here is what I do in workshops today.

```yaml
- name: GRAB ROUTE53 INFORMATION
  route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: "student1.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    max_items: "{{student_total|string}}"
  register: record_sets
```

##### EXPECTED RESULTS
unsure, I can switch but this will break many users Ansible Playbooks, we should accept string and convert to int

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => changed=false 

  msg: |-

    Parameter validation failed:

    Invalid type for parameter MaxItems, value: 2, type: <type 'int'>, valid types: <type 'basestring'>
```

for internal red hat folks the QE tests are happening here: http://jenkins.ansible.eng.rdu2.redhat.com/blue/organizations/jenkins/tower-qe-compatibility-pipepline/detail/tower-qe-compatibility-pipepline/567/pipeline
