### ISSUE TITLE
ec2_key does not update or readd key when contents change

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#6454]
##### Issue Type:

Bug Report 
##### Ansible Version:

```
ansible 1.6 (devel ebfc776533) last updated 2014/03/12 12:33:04 (GMT -400)
```
##### Environment:

Ubuntu 12.04
boto 2.23.0
##### Summary:

The ec2_key module only checks that the name of a key matches and ignores the content.

To update the key, I have to first run a task to declare state=absent, then run another with state=present.
##### Steps To Reproduce:

Run the task twice with two different key_material ...

```
- name: add temporary sshkey to ec2
  ec2_key:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: 'us-west-2'
    name: integration_test_key
    key_material: "{{ lookup('file', ec2_key_filename + '.pub' | expanduser ) }}"
```
