### ISSUE TITLE
docker_container: mac_address not respected

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#64555]
##### SUMMARY

When creating a docker container using `docker_container` the given `mac_address` is not being configured correctly. Tested with a `macvlan` network.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pkueck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:09:47) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
n/a
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: mytesthost
  tasks:
    - name: "create network"
      docker_network:
        name: 'dtestnet'
        driver: macvlan
        driver_options:
          macvlan_mode: bridge
          parent: eth1.123
        ipam_config:
          - subnet: '192.168.1.0/24'
    - name: "create container1 using ansible module"
      docker_container:
        name: 'dtestcontainer1'
        state: started
        networks_cli_compatible: no
        purge_networks: yes
        networks:
          - name: 'dtestnet'
            ipv4_address: '192.168.1.123'
        mac_address: '02:42:58:00:00:01'
        image: 'centos:centos7'
        command: '/bin/sleep 86400'
    - command: "docker exec dtestcontainer1 cat /sys/class/net/eth0/address"
      register: t_docker1
    - debug: msg='{{t_docker1.stdout}}'
    - name: "create container2 using cli"
      command: "docker run -d --name dtestcontainer2 --network dtestnet --ip 192.168.1.124 --mac-address 02:42:58:00:00:02 centos:centos7 /bin/sleep 86400"
    - command: "docker exec dtestcontainer2 cat /sys/class/net/eth0/address"
      register: t_docker2
    - debug: msg='{{t_docker2.stdout}}'
```

##### EXPECTED RESULTS

both containers having the configured mac address

##### ACTUAL RESULTS

container created with `docker_container` has a random mac address

```paste below
PLAY [mytesthost] ***************************************************                                                                                              

TASK [create network] ***********************************************
ok: [mytesthost]

TASK [create container1 using ansible module] ***********************
--- before
+++ after
@@ -1,9 +1,13 @@
 {
-    "exists": false,
-    "network.bridge": {
-        "id": "",
-        "name": "bridge"
+    "exists": true,
+    "network.bridge": null,
+    "network.dtestnet": {
+        "aliases": null,
+        "id": "5ec6e5058ee9ab069056a2660cbe757ed7f00955135ac7c2e781d9de50e50900",
+        "ipv4_address": "192.168.1.123",
+        "ipv6_address": null,
+        "links": null,
+        "name": "dtestnet"
     },
-    "network.dtestnet": null,
-    "running": false
+    "running": true
 }

changed: [mytesthost]

TASK [command] ******************************************************
changed: [mytesthost]

TASK [debug] ********************************************************
ok: [mytesthost] => {
    "msg": "02:42:c0:a8:01:7b"
}

TASK [create container2 using cli] **********************************
changed: [mytesthost]

TASK [command] ******************************************************
changed: [mytesthost]

TASK [debug] ********************************************************
ok: [mytesthost] => {
    "msg": "02:42:58:00:00:02"
}

PLAY RECAP **********************************************************
mytesthost    : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

docker inspect dtestcontainer1: https://gist.github.com/philfry/04f9dfe3d9cda923db2ddbb3b8f729b0
docker inspect dtestcontainer2: https://gist.github.com/philfry/a45969c8033e0897b17d7beb5cb7b409
docker inspect dtestnet: https://gist.github.com/philfry/8173406b6d80daa791a0bc54349f8996

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/docker/docker_container.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @cove @danihodovic @dariko @dusdanig @felixfontein @joshuaconner @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
That's not surprising at all since you explicitly set `networks_cli_compatible: no`, i.e. you request that the module works differently than docker CLI. In this case, the module creates the container with the default network, and the container probably gets the MAC address for this interface. Then, it adds the network you specified, and removes the default network. The interface to the new network will get a random MAC, since the MAC is only used on container creation.

Please change the `networks_cli_compatible` option to `yes` and try again.

**Comment by philfry** [comment]
That's not the cause, the problem still occurs with `networks_cli_compatible: yes`.
```yaml
---
- hosts: mytesthost
  tasks:
    - name: "create network"
      docker_network:
        name: 'dtestnet'
        driver: macvlan
        driver_options:
          macvlan_mode: bridge
          parent: eth1.123
        ipam_config:
          - subnet: '192.168.1.0/24'
    - name: "create container1 using ansible module"
      docker_container:
        name: 'dtestcontainer1'
        state: started
        networks_cli_compatible: no
        purge_networks: yes
        networks:
          - name: 'dtestnet'
            ipv4_address: '192.168.1.123'
        mac_address: '02:42:58:00:00:01'
        image: 'centos:centos7'
        command: '/bin/sleep 86400'
    - command: "docker exec dtestcontainer1 cat /sys/class/net/eth0/address"
      register: t_docker1
    - debug: msg='{{t_docker1.stdout}}'
    - name: "create container2 using cli"
      command: "docker run -d --name dtestcontainer2 --network dtestnet --ip 192.168.1.124 --mac-address 02:42:58:00:00:02 centos:centos7 /bin/sleep 86400"
    - command: "docker exec dtestcontainer2 cat /sys/class/net/eth0/address"
      register: t_docker2
    - debug: msg='{{t_docker2.stdout}}'
    - name: "create container3 using ansible module w/ networks_cli_compatible"
      docker_container:
        name: 'dtestcontainer3'
        state: started
        networks_cli_compatible: yes
        networks:
          - name: 'dtestnet'
            ipv4_address: '192.168.1.125'
        mac_address: '02:42:58:00:00:03'
        image: 'centos:centos7'
        command: '/bin/sleep 86400'
    - command: "docker exec dtestcontainer3 cat /sys/class/net/eth0/address"
      register: t_docker3
    - debug: msg='{{t_docker3.stdout}}'
```

output:
```
PLAY [mytesthost] ************************************************************

TASK [create network] *********************************************************************
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "exists": false
+    "exists": true
 }

changed: [mytesthost]

TASK [create container1 using ansible module] *********************************************
--- before
+++ after
@@ -1,9 +1,13 @@
 {
-    "exists": false,
-    "network.bridge": {
-        "id": "",
-        "name": "bridge"
+    "exists": true,
+    "network.bridge": null,
+    "network.dtestnet": {
+        "aliases": null,
+        "id": "83e46b1ca3f5c696e686e0ee0744f5682c97770df37bee18b7e0dffb9a0a2733",
+        "ipv4_address": "192.168.1.123",
+        "ipv6_address": null,
+        "links": null,
+        "name": "dtestnet"
     },
-    "network.dtestnet": null,
-    "running": false
+    "running": true
 }

changed: [mytesthost]

TASK [command] ****************************************************************************
changed: [mytesthost]

TASK [debug] ******************************************************************************
ok: [mytesthost] => {
    "msg": "02:42:c0:a8:01:7b"
}

TASK [create container2 using cli] ********************************************************
changed: [mytesthost]

TASK [command] ****************************************************************************
changed: [mytesthost]

TASK [debug] ******************************************************************************
ok: [mytesthost] => {
    "msg": "02:42:58:00:00:02"
}

TASK [create container3 using ansible module w/ networks_cli_compatible] ******************
--- before
+++ after
@@ -1,11 +1,12 @@
 {
-    "exists": false,
+    "exists": true,
     "network.dtestnet": {
         "aliases": null,
-        "ipv4_address": "",
-        "ipv6_address": "",
+        "id": "83e46b1ca3f5c696e686e0ee0744f5682c97770df37bee18b7e0dffb9a0a2733",
+        "ipv4_address": "192.168.1.125",
+        "ipv6_address": null,
         "links": null,
         "name": "dtestnet"
     },
-    "running": false
+    "running": true
 }

changed: [mytesthost]

TASK [command] ****************************************************************************
changed: [mytesthost]

TASK [debug] ******************************************************************************
ok: [mytesthost] => {
    "msg": "02:42:c0:a8:01:7d"
}

PLAY RECAP ********************************************************************************
mytesthost    : ok=10   changed=7    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
