### ISSUE TITLE
read_csv red dot issue

### ISSUE THREAD

**Issue by markatdxb** [ansible/ansible#64554]
##### SUMMARY

when i read specific csv file i get the red dot as the first char of the file which is causing issues to header vars
https://stackoverflow.com/questions/34535616/parsed-csv-file-shows-dot-at-the-beginning
according to this article its somehow related UTF-8 BOM encoding. would you be able to develop the switch to prevent module read this?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

read_csv
##### ANSIBLE VERSION

```paste below
2.9.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Read CSV file data to JSON format
      read_csv:
        path: '{{ csv_file }}'
      register: csv_import
      delegate_to: localhost
```

##### EXPECTED RESULTS

read first line headers correctly 

##### ACTUAL RESULTS

little red dot as first char of the first header item

![image](https://user-images.githubusercontent.com/43998117/68383887-0ee11200-0189-11ea-99c3-9a40050f5503.png)
