### ISSUE TITLE
ec2_key needs a wait parameter

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#6455]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.6 (devel ebfc776533) last updated 2014/03/12 12:33:04 (GMT -400)
```
##### Environment:

Ubuntu 12.04
boto 2.23.0
##### Summary:

The ec2_key needs to wait for the api call to finish so that later operations like removing a group can succeed without dependency failures.
##### Steps To Reproduce:

```
- name: remove temporary sshkey
  ec2_key:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: 'us-west-2'
    name: integration_test_key
    state: absent

- name: remove temporary security group
  ec2_group:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: 'us-west-2'
    name: "integration_test_group"
    description: "integration_test_group"
    state: absent
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: all
```
