### ISSUE TITLE
mysql_user module check_implicit_admin doesn't fallback to login credentials

### ISSUE THREAD

**Issue by ricco24** [ansible/ansible#64560]
##### SUMMARY
mysql_user module with check_implicit_admin=yes try to connect to database without password. But when login failed doesn't fallback to login_user and login_password credentials.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
2.9.0
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE
```yaml
- name: Update root password for all root accounts
  mysql_user: name=root password={{ mysql_root_password }} login_user=root login_password={{ mysql_root_password }} host={{ item }} check_implicit_admin=yes
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost
```

First run is ok, but on second run Ansible failed when try to connect as root without password and no fallback to login credentials.

##### EXPECTED RESULTS
First run -> root / no password
Other runs -> root / mysql_root_password

##### ACTUAL RESULTS
Provision failed at other as first run
