### ISSUE TITLE
Error in module  vmware_vm_shell  with windows command

### ISSUE THREAD

**Issue by jrvilda** [ansible/ansible#64567]
##### SUMMARY
Error in module  vmware_guest with windows command:
Example:

```yaml
tasks:
    - name: Changing user.
      vmware_vm_shell:
        hostname: 'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER'
        username: 'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER'
        password: 'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER'
        validate_certs: no
        datacenter: 'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER'
        folder: '/VALUE_SPECIFIED_IN_NO_LOG_PARAMETER/vm'
        wait_for_process: True
        vm_id: 'VALUE_SPECIFIED_IN_NO_LOG_PARAMETER'
        vm_username: 'admin'
        vm_password: 'pass'
        vm_shell: 'c:\windows\system32\wbem\wmic.exe'
        vm_shell_cwd: 'c:\'
        vm_shell_args: 'useraccount where name="admin" rename root'
      delegate_to: localhost
      register: out
```

```
PLAY RECAP ******************************************************************************************************************
TASK [Changing user.] *******************************************************************************************************
task path: /etc/ansible/playbooks/tools/vmware.yml:9
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_vm_shell_payload_TJaaaG/__main__.py", line 244, in __init__
    self.execute_command(vm, module.params)
  File "/tmp/ansible_vmware_vm_shell_payload_TJaaaG/__main__.py", line 270, in execute_command
    res_data = self.wait_for_process(vm, res, credentials)
  File "/tmp/ansible_vmware_vm_shell_payload_TJaaaG/__main__.py", line 307, in wait_for_process
    process_status, res_data = self.process_exists_in_guest(vm, pid, creds)
  File "/tmp/ansible_vmware_vm_shell_payload_TJaaaG/__main__.py", line 292, in process_exists_in_guest
    res = self.pm.ListProcessesInGuest(vm, creds, pids=[pid])
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cluster": null,
            "datacenter": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "folder": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "timeout": 3600,
            "username": "admin",
            "validate_certs": false,
            "vm_id": "host",
            "vm_id_type": "vm_name",
            "vm_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vm_shell": "c:\\windows\\system32\\wbem\\wmic.exe",
            "vm_shell_args": "useraccount where name=\"admin\" rename root",
            "vm_shell_cwd": "c:\\",
            "vm_shell_env": null,
            "vm_username": " admin",
            "wait_for_process": true
        }
    },
    "msg": "No se pudo autenticar en el sistema operativo invitado con las credenciales proporcionadas."
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vm_shell 
pyvmomi                          6.7.3

##### ANSIBLE VERSION
ansible 2.7.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

##### OS / ENVIRONMENT
CentOS Linux release 7.4.1708 (Core)
vsphere 6.0
Client: windows server v 1607 os build 14393.2395

##### EXPECTED RESULTS
not show error.

##### ACTUAL RESULTS
I launch the task and the command is executed correctly but error is displayed
