### ISSUE TITLE
Backward incompatible change in cli_command module

### ISSUE THREAD

**Issue by Spredzy** [ansible/ansible#64575]
##### SUMMARY

```
- name: CHANGE PASSWORD TO WORKSHOP DEFAULT
  cli_command:
    command: "{{item}}"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "{{admin_password}}1"
      - "{{admin_password}}1"
    check_all: True
  loop:
    - "configure"
    - "rollback"
    - "set system root-authentication plain-text-password"
    - "commit"

- name: TURN ON NETCONF ON PORT 830
  junos_netconf:

```

The above task is working on current `stable-2.9` and broke in `devel` in the last few days.
https://github.com/ansible/ansible/commit/c27e47327f902dddf0b93767e387cacdfc12e11f is probably related.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  - cli_command

##### ANSIBLE VERSION

  - devel

##### CONFIGURATION

  - N/A

##### OS / ENVIRONMENT

  - N/A

##### STEPS TO REPRODUCE

  - Task provided above

##### EXPECTED RESULTS

  - To work normally

##### ACTUAL RESULTS

```
failed: [trtr3] (item=rollback) => changed=false 
  ansible_loop_var: item
  item: rollback
  msg: |-

    rollback
                      ^
    syntax error.
 
    ec2-user>

failed: [rtr3] (item=set system root-authentication plain-text-password) => changed=false 
  ansible_loop_var: item
  item: set system root-authentication plain-text-password
  msg: |2-

     expecting <command>.

    ec2-user> set system   oot-authentication
                  ^

    syntax error, expecting <command>.

    ec2-user> set systemroot-authentication   lain-text-password
                  ^
    syntax error, expecting <command>.

    ec2-user>
```
