### ISSUE TITLE
find module should accept plain text as filter when searching file content

### ISSUE THREAD

**Issue by williamwu0220** [ansible/ansible#64584]
##### SUMMARY
When determine file content contains specified strings by using find module, contains parameter should accept plain text as filter condition.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
find module

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = None
  configured module search path = ['/home/williamwu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/williamwu/venv/py3k/lib/python3.7/site-packages/ansible
  executable location = /home/williamwu/venv/py3k/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```
no output
```

##### OS / ENVIRONMENT
Debian Buster (10)
kernel: Linux op-room 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

##### STEPS TO REPRODUCE
For example, when I want to make sure if **raspbian** string exists in /etc/apt/sources.list, the task must be written in this way or it does't work:

```yaml
- name: check target if raspbian os                                                                                                                                        
  find:                                                                                                                                                                    
    path: /etc/apt/                                                                                                                                                        
    pattern: "*.list"                                                                                                                                                      
    contains: ".+raspbian"
```

But I think it is more straightful like this:

```yaml
- name: check target if raspbian os                                                                                                                                        
  find:                                                                                                                                                                    
    path: /etc/apt/                                                                                                                                                        
    pattern: "*.list"                                                                                                                                                      
    contains: "raspbian"
```

After digging into source code, I think if using re.search instead of re.match solves this problem, and it does't hurt backward compatibility:

```python
# in https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/find.py
...
        with open(fsname) as f:
            for line in f:
                if prog.match(line): # using prog.search(line) improve this behavior
                    return True
...
```
