### ISSUE TITLE
Ansible k8s module ignores dropping loadBalancerIP for Kubernetes service

### ISSUE THREAD

**Issue by atikhono** [ansible/ansible#64597]
##### SUMMARY
Ansible k8s module ignores dropping loadBalancerIP for Kubernetes service.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s module

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = None
  configured module search path = [u'/Users/atikhonova/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/atikhonova/ansible-venv/lib/python2.7/site-packages/ansible
  executable location = /Users/atikhonova/ansible-venv/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:42:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```
Reproducible with Ansible 2.8.6 as well.

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

MacOS 10.14.6 Ansible controller + Docker Desktop local Kubernetes cluster
Centos 7 Ansible controller + Azure Kubernetes Service

The issue look independent fo OS/environment.

##### STEPS TO REPRODUCE

I'm running Ansible on localhost with a local Kubernetes cluster bundled in Docker Desktop.

1. Create a Kubernetes service with Ansible k8s module:

```
ansible-playbook reproducer.yml
```

```yaml
# reproducer.yml
- name: Remove loadBalancerIP
  hosts: localhost
  environment:
    K8S_AUTH_CONTEXT: docker-desktop
  tasks:
    - name: Create kong service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: kong
            namespace: default
          spec:
            externalTrafficPolicy: Cluster
            loadBalancerIP: 127.0.0.1                   # this
            ports:
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: http
              port: 80
              protocol: TCP
              targetPort: 8000
            selector:
              app: kong-dbless
            sessionAffinity: None
            type: LoadBalancer
```

2. Comment out the "loadBalancerIP: 127.0.0.1" line and run ansible-playbook again -- reports no changes. The service load balancer IP is still present in Kubernetes configuration (kubectl get service kong -o yaml). I expect that line to be removed and a dynamic IP assigned.

##### EXPECTED RESULTS

LoadBalancerIP removed from service configuration. Ansible reports changes in service configuration.

##### ACTUAL RESULTS

LoadBalancerIP is left unchanged (127.0.0.1 as per the reproducing case provided).
