### ISSUE TITLE
Always section of parent block for failed host will execute with always section of child block for successful hosts

### ISSUE THREAD

**Issue by geauxvirtual** [ansible/ansible#64611]
##### SUMMARY

Always section of a parent block for a failed host can execute at same time as always section of a child block for successful hosts. If this parent always section fails, this ends the play for the successful hosts, and always sections are not executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

roles
play_iterator

##### ANSIBLE VERSION

```paste below
ansible 2.7.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
DEFAULT_JINJA2_NATIVE(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS

##### STEPS TO REPRODUCE

The task file is structured as follows.
```yaml
---
- block: #block 1
    - include-tasks: 1.yml
    - include-tasks: 2.yml
    - include-tasks: 3.yml
    - include-tasks: 4.yml
    - block: #block 2
        - include-tasks: 5.yml
        - include-tasks: 6.yml
        - block: #block 3
            - include-tasks: 7.yml
            - include-tasks: 8.yml
            - include-tasks: 9.yml
            - include-tasks: 10.yml
          always:
            - include-tasks: always-1.yml
            - include-tasks: always-2.yml
        always:
          - include-tasks: always-3.yml
  when: foo != False
```

When the playbook runs, it's usually for 3 or more hosts. What we are seeing is that if a task fails for a host2 in block 2, block 3 will be executed for the successful hosts (host1 and host3). Upon completion of the block 3 tasks for host1 and host 3, Ansible schedules the always section for block 2 for the host2 at the same time as the always section of block 3 for host1 and host 3. If a task fails in the always section of block 3 for host3, this stops the entire play, and the remaining tasks in the always section of block 3 and block 2 are not executed for host1 and host 3.

```
TASK [foo/bar : include_tasks] ********
task path: /path/to/role/foo/bar/tasks/main.yml:17 (this corresponds to always-1.yml above)
included: /path/to/role/foo/bar/tasks/always-1.yml for host1,host3
included: /path/to/role/foo/bar/tasks/always-3.yml for host2
```

##### EXPECTED RESULTS

Always section for parent block gets scheduled after completion of child block including rescue/always sections.

##### ACTUAL RESULTS

Always section for parent block being scheduled at same time as always section of child block

After all the tasks in the third block are completed, I see the following in the output.
```
TASK [foo/bar : include_tasks] ********
task path: /path/to/role/foo/bar/tasks/main.yml:17 (this corresponds to always-1.yml above)
included: /path/to/role/foo/bar/tasks/always-1.yml for host1,host3
included: /path/to/role/foo/bar/tasks/always-3.yml for host2
```
