### ISSUE TITLE
k8s_info ignoring label_selectors in (at least) a certain scenario

### ISSUE THREAD

**Issue by alexbarcelo** [ansible/ansible#64669]
##### SUMMARY

The `k8s_info` is not filtering as expected. I have certain labels in a `Deployment` kubernetes resource, and trying to filter through them results in no filtering applied.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

k8s_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /home/abarcelo/Sources/ronda-theatre/ansible.cfg
  configured module search path = ['/home/abarcelo/Sources/ronda-theatre/kubespray/library']
  ansible python module location = /home/abarcelo/Sources/ronda-theatre/venv/lib/python3.6/site-packages/ansible
  executable location = /home/abarcelo/Sources/ronda-theatre/venv/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

##### CONFIGURATION

I think they are irrellevant, but I am using kubespray so just to be sure:

```paste below
DEFAULT_MODULE_PATH(/home/abarcelo/(...)/ansible.cfg) = ['/home/abarcelo/(...)/kubespray/library']
DEFAULT_REMOTE_USER(/home/abarcelo/(...)/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/abarcelo/(...)/ansible.cfg) = ['/home/abarcelo/(...)/kubespray/roles']
HOST_KEY_CHECKING(/home/abarcelo/(...)/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/abarcelo/(...)/ansible.cfg) = never
```

##### OS / ENVIRONMENT

Ubuntu 18.04 Desktop, using a virtual environment.

The openshift package is installed remotely in a Ubuntu 18.04 server.

##### STEPS TO REPRODUCE

Have a Deployment kubernetes resource with the following labels:

```yaml
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: "cert-manager"
  labels:
    app: cert-manager
    (...)
    helm.sh/chart: cert-manager-v0.11.0
(...)
```

Try that the label selector works in `kubectl`:

```
kubectl get deployments.apps -A -l='helm.sh/chart=cert-manager-v0.11.0'  # returns the deployment
kubectl get deployments.apps -A -l='helm.sh/chart=cert-manager-v0.12.0'  # returns nothing
```

The following doesn't work in a playbook:

```yaml
- name: Check if cert-manager is already installed
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
    label_selectors:
      - "helm.sh/chart=cert-manager-v0.12.0"
  register: cert_manager_deployment
```

##### EXPECTED RESULTS

A dictionary `cert_manager_deployment` containing an empty list in `resources`.

##### ACTUAL RESULTS

The return contains all the resources, meaning that the `label_selectors` has not been used/applied. Or something.
