### ISSUE TITLE
Ansible Azure FIrewall: Ability to append rules to Azure Firewall

### ISSUE THREAD

**Issue by samhabaneh** [ansible/ansible#64667]
##### SUMMARY

We want to use Ansible to manage our Azure Firewall rules. A great feature to have would be having the ability to either append or purge firewall rules. This would give users more flexibility in terms of managing the Azure Firewall strickly from the azure_rm_azurefirewall module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_azurefirewall

##### ADDITIONAL INFORMATION

This feature would allow use to exclusively use Ansible as our backend automation for managing the Azure Firewall

```yaml

- name: Create Azure Firewall
  azure_rm_azurefirewall:
    resource_group: myResourceGroup
    name: myAzureFirewall
    **purge_rules: "no"**
    application_rule_collections:
    nat_rule_collections:
    network_rule_collections:
    ip_configurations:

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/azure/azure_rm_azurefirewall.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_azurefirewall.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @needgithubid @nitzmahone @yungezz @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@samhabaneh, just so you are aware we have a dedicated Working Group for azure.
You can find other people interested in this in `#ansible-azure` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@samhabaneh Thank for your contribution, We will look into this! Thank you very much!

**Comment by Fred-sun** [comment]
@mybayern1974 @haiyuazhang Would you please help take look this issue? New feature request for azure_rm_azurefirewall module! Thank you very much!

**Comment by OxHobbs** [comment]
@samhabaneh - what if this worked like the tags property does on the other modules.  If you specify a rule set then you are making a declaration of what the configuration should be.  However, if you wanted to append rules then you would specify that: 

```yaml
- name: Create Azure Firewall
  azure_rm_azurefirewall:
    resource_group: myResourceGroup
    name: myAzureFirewall
    append_rule_collections: yes|no
    application_rule_collections:
    nat_rule_collections:
    network_rule_collections:
    ip_configurations:
```
