### ISSUE TITLE
Regression in jira module between ansible 2.8.6 and 2.9.0

### ISSUE THREAD

**Issue by rsommer** [ansible/ansible#64664]
##### SUMMARY

After updating from ansible 2.8.6 to 2.9.0, commenting via the jira-module failes with

`fatal: [testhost.local]: FAILED! => {"changed": false, "msg": "'module' object has no attribute 'comment'"}`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

jira

But there have been no code changes between 2.8.6 and 2.9.0 in this module.
##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/XXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Running on ubuntu 18.04 LTS

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  name: Comment on issue
  vars_prompt:
    - name: "jira_server"
      prompt: "JIRA server"
    - name: "jira_user"
      prompt: "JIRA username"
    - name: "jira_password"
      prompt: "JIRA password"
      confirm: yes
    - name: "jira_issue_key"
      prompt: "JIRA issue"
  tasks:
    - name: Comment on issue
      jira:
        uri: '{{ jira_server }}'
        username: '{{ jira_user }}'
        password: '{{ jira_password }}'
        issue: '{{ jira_issue_key }}'
        operation: comment
        comment: "(/) {{ inventory_hostname }}"
      connection: local
```

##### EXPECTED RESULTS

New comment on given JIRA issue.

##### ACTUAL RESULTS

Playbook failes with `fatal: [testhost.local]: FAILED! => {"changed": false, "msg": "'module' object has no attribute 'comment'"}`

```paste below
PLAY [Comment on issue] **************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [testhost.local]

TASK [Comment on issue] **************************************************************************************************************************************
fatal: [testhost.local]: FAILED! => {"changed": false, "msg": "'module' object has no attribute 'comment'"}

PLAY RECAP ***************************************************************************************************************************************************
testhost.local : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
