### ISSUE TITLE
The git module should provide warning if the ssh_opts parameter is supplied but the version of git is 2.2.3 or earlier

### ISSUE THREAD

**Issue by cherdt** [ansible/ansible#64673]
##### SUMMARY

The `ssh_opts` parameter relies on setting environment variables for git, such as GIT_SSH. Git did not recognize this environment variable until version 2.3.0 (see https://git-scm.com/docs/git/2.3.0), and many contemporary OSes (RHEL 7, CentOS7) include older versions of Git (1.8.3.1).

It would be useful to provide a warning in this case, similar to the warning for the `depth` parameter. E.g. "Your git version is too old to support the ssh_opts argument."

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git.py
source control, git module

##### ADDITIONAL INFORMATION

It would save users time when trying to troubleshoot failed git connections via SSH.

```yaml
- name: clone a git repo
  git:
    repo: git@github.com:cherdt/hello_ansible.git
    dest: /opt/hello_ansible
    version: master
    ssh_opts: "{{-o IdentityFile=github_id_rsa}}"
```
