### ISSUE TITLE
redfish_command - failure on user account deletion

### ISSUE THREAD

**Issue by spike77453** [ansible/ansible#64684]
### SUMMARY

Running the example playbook from https://docs.ansible.com/ansible/latest/modules/redfish_command_module.html#examples to disable and delete a certain user works as expected, but results in an error message

> The specified value is not allowed to be configured if the user name \\nor password is blank.'

Note that the user to be deleted (in the example below the user with id 5) _is different_ from the user specified in "username".  
The user (in the example below the user with id 5) is deleted as expected despite the error message.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
redfish_command

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /home/ansible/ansible_local/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
CentOS Linux release 7.6.1810 (Core)  
Dell R640, iDRAC Firmware 3.32.32.32

##### STEPS TO REPRODUCE
```yaml
- name: Disable and delete user
  hosts: dellR640
  gather_facts: False
  tasks:
    - name: Disable and delete user with id 5
      local_action:
        module: redfish_command
        category: Accounts
        command: ["DisableUser", "DeleteUser"]
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        id: "5"
```

##### ACTUAL RESULTS

```
fatal: [dellR640 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "account_properties": {}, 
            "baseuri": "dellR640idrac", 
            "boot_next": null, 
            "bootdevice": null, 
            "category": "Accounts", 
            "command": [
                "DisableUser", 
                "DeleteUser"
            ], 
            "id": "5", 
            "new_password": null, 
            "new_username": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_id": null, 
            "roleid": null, 
            "timeout": 10, 
            "uefi_target": null, 
            "update_username": null, 
            "username": "customadminuser"
        }
    }, 
    "msg": "HTTP Error 400 on PATCH request to 'https://dellR640idrac/redfish/v1/Managers/iDRAC.Embedded.1/Accounts/5', extended message: 'The specified value is not allowed to be configured if the user name \\nor password is blank.'"
}
```
