### ISSUE TITLE
tower_job_template: Add job template is not idempotent

### ISSUE THREAD

**Issue by GLaN1K** [ansible/ansible#64734]
##### SUMMARY

The module tower_job_template is not idempotent

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module: tower_job_template

##### ANSIBLE VERSION

```paste below
2.8.6
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/glanik/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/glanik/.ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=600s
ANY_ERRORS_FATAL(/home/glanik/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/glanik/.ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/home/glanik/.ansible.cfg) = 50
DEFAULT_GATHERING(/home/glanik/.ansible.cfg) = smart
DEFAULT_LOG_PATH(/home/glanik/.ansible.cfg) = /home/glanik/logs/ansible.log
DEFAULT_ROLES_PATH(/home/glanik/.ansible.cfg) = [u'/home/glanik/.roles', u'/home/glanik/roles', u'/home/glanik/roles_internal', u'/home/glanik/roles_customer']
DEFAULT_TRANSPORT(/home/glanik/.ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/home/glanik/.ansible.cfg) = /home/glanik/scripts/vault/bin/open_vault
HOST_KEY_CHECKING(/home/glanik/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/glanik/.ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/glanik/.ansible.cfg) = /home/glanik/ansible-retry
```

##### OS / ENVIRONMENT

OS: CentOS Linux 7 (Core)
Tower: 7.0.0

##### STEPS TO REPRODUCE

1. Execute the playbook below to add a Job Template into Tower:
**NOTE**: "survey_spec" and "survey_enabled" fields are mandatory to reproduce

```yaml
---
- name: Add a Job Template
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
  - name: Add Job Templates
    tower_job_template:
      name: "Test Job Template 01"
      job_type: "run"
      inventory: "Demo Inventory"
      project: "Demo Project"
      playbook: "hello_world.yml"
      credential: "Demo Credential"
      state: present
      survey_enabled: True
      survey_spec: '{
                    "description": "", 
                    "name": "", 
                    "spec": [
                        {
                            "default": "master", 
                            "max": null, 
                            "min": null, 
                            "new_question": true, 
                            "question_description": "", 
                            "question_name": "Ansible version", 
                            "required": true, 
                            "type": "text", 
                            "variable": "ansible_release"
                        }
                    ]
                }'
      tower_host: "https://{{ tower_host }}"
      tower_username: admin
      tower_password: ************
      tower_verify_ssl: no
```
2. Execute the same playbook again.

##### EXPECTED RESULTS

When executing the module for the second time, result should not be changed

##### ACTUAL RESULTS

Result of playbook execution is always changed
First Execution:

```paste below
changed: [localhost] => {"changed": true, "survey_spec": {"description":"","name":"","spec":[{"default":"master","max":null,"min":null,"new_question":true,"question_description":"","question_name":"Ansible version","required":true,"type":"text","variable":"ansible_release"}]}, "id": 24, "job_template": "Test Job Template 01", "survey_enabled": true, "state": "present"}
```
Second execution:
```paste below
changed: [localhost] => {"changed": true, "survey_spec": {"description":"","name":"","spec":[{"default":"master","max":null,"min":null,"new_question":true,"question_description":"","question_name":"Ansible version","required":true,"type":"text","variable":"ansible_release"}]}, "id": 24, "job_template": "Test Job Template 01", "survey_enabled": true, "state": "present"}
```
