### ISSUE TITLE
FAD, first_found lookup wokrs for directories

### ISSUE THREAD

**Issue by rosowiecki** [ansible/ansible#64741]
##### SUMMARY

**EDIT: not a bug, it was my mistake, read the last comment**

Currently, first_found lookup looks only for files. It used to work, but doesn't anymore (I haven't found exact version when this behavior was changed). I used to relay on this feature to find most recent version of software package like 
```yaml
set_fact: mysoft_installer_dir={{item}}
with_first_found:
   - "{{ mysoft_repository }}/devel/{{ mysoft_version}}"
   - "{{ mysoft_repository }}/unstable/{{ mysoft_version}}"
   - "{{ mysoft_repository }}/release/{{ mysoft_version }}"
```
.. but then it just stopped working with some ansible upgrade

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lookup

##### ADDITIONAL INFORMATION

A parameter for first_found lookup allowing to accept directories, default: only files.
