### ISSUE TITLE
Support for Amazon Aurora Cluster Snapshots is missing from rds_snapshot module

### ISSUE THREAD

**Issue by troyfontaine** [ansible/ansible#64765]
##### SUMMARY
The rds_snapshot module does not support AWS Aurora clusters, which require that they be managed using the `CreateDBClusterSnapshot API` which the module is not aware of (nor is it documented on the module as a limitation).  It should either be added as an option to the existing module or split out as a separate module. e.g. rds_cluster_snapshot

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
rds_snapshot

##### ADDITIONAL INFORMATION
This would allow for the ability to manage Amazon Aurora cluster snapshots as they are functionally different than typical RDS snapshots and use a different set of APIs to manage.

```yaml
    - rds_snapshot:
        db_cluster_identifier: my-aurora-cluster
        db_snapshot_identifier: my-aurora-cluster-snapshot
```
