### ISSUE TITLE
vmware_guest module: cluster setting doesnt create VM on the right datastores

### ISSUE THREAD

**Issue by Aech1977** [ansible/ansible#64764]
##### SUMMARY
My automation worked fine until I created 2 separate clusters and separate datastores.  I get an error that virtual machine is trying to install to a datastore it doesnt have a physical connection to when I specify cluster and use autoselect_datastore: true

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/modules/cloud/vmware/vmware_guest.py`

##### ANSIBLE VERSION
```
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
AWX 8.0.0 running on CentOS 7.5

##### STEPS TO REPRODUCE
Running playbook to create virtual machine thru AWX
```
- name: Connect to vSphere host
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: Survey Answers
      include_vars:
        dir: Vars

    - name: Create VM from Template
      vmware_guest:
        validate_certs: no
        hostname: 10.0.1.55
        username: vmware_builder
        password: "{{ vault_vcenter_pass }}"
        datacenter: "{{ company name }}"
        cluster: Corporate
        name: "{{ hostname }}"
        folder: "{{ Folder }}"
        annotation: "{{ annotation }}"
        template: CentOS 7.5
        disk:
        - size_gb: "{{ disk }}"
          type: thin
          autoselect_datastore: True
        networks:
        - name: "{{ network }}"
          start_connected: yes
        hardware:
          memory_mb: "{{ mem }}"
          num_cpus: "{{ cpus }}"
        state: poweredon
        wait_for_ip_address: yes
      register: new_vm
``'

##### EXPECTED RESULTS
Expect VM to be created successful


##### ACTUAL RESULTS
Fails citing the datastore that is not physically connected to cluster VM is attempting to be created on instead of the datastores it physically has a connection to (more then likely because the datastore its attempting to use has more space then the one available.

```
 },
    "changed": false,
    "msg": "Failed to create a virtual machine : Unable to access the virtual machine configuration: Unable to access file [TWASTG007_Datastore001]"
}
```
