### ISSUE TITLE
docker_image parameter to print build output

### ISSUE THREAD

**Issue by KajdeMunter** [ansible/ansible#64771]
##### SUMMARY

A parameter in the `docker_image` module that would enable printing the output of `docker build`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`docker_image`

##### ADDITIONAL INFORMATION

https://github.com/ansible/ansible/pull/20757 added an output on failure, but printing the output of a successful build is not possible as far as I know. For example, a use case could be to see what tests have been run during the build.

Something like this:
```yaml
- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: ./sinatra
    name: registry.ansible.com/chouseknecht/sinatra
    tag: v1
    push: yes
    source: build
    print_output: yes
```
