### ISSUE TITLE
vmware_guest clone from template will keep same MAC as the template

### ISSUE THREAD

**Issue by PulsatingQuasar** [ansible/ansible#64774]
##### SUMMARY
When using the vmware_guest module and cloning from a VMWare template the MAC address remains the same. 

The template and VM then have the same MAC which is not a problem untill you convert the template to a VM. In the vCenter console a MAC duplicate address triggered alarm is then triggered. vCenter then corrects the problem by changing the MAC to some other address and you can reset the triggered alarm to green.

The problem is, this not the same behaviour as via the vCenter console. If you clone from template there the VM has a different MAC address. Also we shouldn't have to turnoff the MAC duplicate address trigger.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
2.8.6

```

##### CONFIGURATION
Not relevant

##### OS / ENVIRONMENT
CentOS 7


##### STEPS TO REPRODUCE
Choose a VMWare template as the template

- name: Clone new VM from template and customize
    vmware_guest:
      annotation: "Aanmaakdatum {{date}}"
      hostname: "{{ vc_server }}"
      username: "{{ vc_admin  }}"
      password: "{{ vc_admin_password }}"
      validate_certs: no
      datacenter: "{{ vc_datacenter }}"
      cluster: "{{ vc_cluster }}"
      name: "{{ template_file_new }}"
      template: "{{ template_file }}"
      folder: "{{ template_folder }}"
      state: poweredon 
      disk:
      - size_gb: 80
        datastore: "{{ vc_storagecluster }}"
        autoselect_datastore: true
      - size_gb: 30
        autoselect_datastore: true
      - size_gb: 20
        autoselect_datastore: true
      hardware:
        memory_mb: "{{ vm_memory }}"
        num_cpus: 2
        version: 14 # Hardware version, latest will be supported in Ansible 2.10
      networks:
#      - name: "{{ template_vlan }}"
#        type: dhcp
#        device_type: vmxnet3
      - name: "{{ vm_net_zone }}"
        device_type: vmxnet3
        ip: "{{ vm_net_ip }}"
        netmask: "{{ vm_net_netmask }}"
        gateway: "{{ vm_net_routers }}"
        domain: "{{ duo_domain }}"
        dns_servers:
        - "{{ duo_net_dns1 }}"
        start_connected: true
      customization:
        autologon: False
        password: "{{ vault_vm_username_password }}"
      wait_for_ip_address: yes
    delegate_to: localhost
    register: vmware


##### EXPECTED RESULTS
The VM is cloned from the template with a different MAC address than the template. This is what actually happens when you use the vCenter console.


##### ACTUAL RESULTS
The VM is cloned with the same MAC address as the template. First of all this is not what the vCenter console does and second of all if the template is then converted to a VM we get a MAC conflict triggered alert. This is then automatically resolved by vCenter by changing it's MAC address but still not the behaviour you want.

We use a process in which a base template is cloned 2 times in a GitLAB CI pipeline and enhanced each step with more applications. So we then have 3 templates with the same MAC and a VM running with the same MAC.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@PulsatingQuasar, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mschelln** [comment]
Have the same issue.
Here's my playbook (sensitive information masked with *):
```
---
- hosts: localhost
  name: Volume Action
  vars:
    vcenter_hostname: *.*.*.*
    vcenter_vcenter:  *****
    vcenter_username: *****
    vcenter_password: *****
    vcenter_dc:       *****
    vcenter_name:     *****
  tasks:
  - vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_dc }}"
      validate_certs: no
      name: "test"
      folder: "/"
      cluster: OCP4
      state: poweredon
      template: RHEL-7.7-VM
      disk:
      - size_gb: 120
        type: thin
        datastore: "{{ vcenter_name }}"
      hardware:
        memory_mb: 16384
        num_cpus: 4
      networks:
      - name: "*****"
        mac: 00:50:56:87:bb:bb
      - name: "*****"
        mac: 00:50:56:87:bb:bc
      - name: "*****"
        mac: 00:50:56:87:bb:bd
```

This was cloning the template into a running VM...unfortunately with same MACs as the template.
Tested with several Ansible versions (2.7.x, 2.8.x) - always with same result: VM is created, but gets wrong IP caused by wrong MACs (all NICs).

Debugged the Python code behind and might found a bug in 
`/usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py `
(Version 2.2 - see DOCUMENTATION topic at the beginning of this file).

Have a look to "def configure_network(self, vm_obj):" (line 1418 ff.). Here network config from template is updated by information got from the playbook. But...MACs are not considered. 
There is a MAC handling from line 1464:
```
                ...
                # Changing mac address has no effect when editing interface
                if 'mac' in network_devices[key] and nic.device.macAddress != current_net_devices[key].macAddress:
                    self.module.fail_json(msg="Changing MAC address has not effect when interface is already present. "
                                              "The failing new MAC address is %s" % nic.device.macAddress)
                ...
```
But this is not enough.
So I added the following lines just behind
```
                ...
                if network_devices[key].get('mac') != nic.device.macAddress:
                    nic.device.macAddress = network_devices[key].get('mac')
                    nic_change_detected = True
                ...
```
Meaning: If the MAC given by playbook (network_devices[key].get('mac')) is different from MAC used in template, the MAC should be changed.

So, here is the complete code snippet:
```
...
                # Changing mac address has no effect when editing interface
                if 'mac' in network_devices[key] and nic.device.macAddress != current_net_devices[key].macAddress:
                    self.module.fail_json(msg="Changing MAC address has not effect when interface is already present. "
                                              "The failing new MAC address is %s" % nic.device.macAddress)
                if network_devices[key].get('mac') != nic.device.macAddress:
                    nic.device.macAddress = network_devices[key].get('mac')
                    nic_change_detected = True
...

```
Code currently not tested completely. So there is not warranty that there're bad side effects. But at the moment it's working fine for me (MACs given by a playbook are used creating the VMs which causes correct IPs during runtime).

Perhaps this will help to get a official bugfix.
