### ISSUE TITLE
openssl_certificates_info: use without disk access

### ISSUE THREAD

**Issue by skytime-sh** [ansible/ansible#64776]
##### SUMMARY

It would be nice if you could submit the Certificate content just in a variable instead of a file.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssl_certificates_info

##### ADDITIONAL INFORMATION

I am collecting information about the Certificates installed on a device via the devices Rest API.
Unfortunately the API just delivers the PEM Formate Certificate. I am not able to request any information like Serial number, expiration date etc. I need directly from the API.
So I use openssl_certificates_info to get the details about the certificates for further processing.
Currently I write the Certificate content I got in memory to a file and after processing ensure it gets deleted again...
Would be nice if that would not be necessary and I could submit the content direct to the module.

A similar request (but not identically) already exists:
Use openssl_csr and openssl_certificates without disk access (sign certificates in memory) #63553

```yaml
- name: "Get all SSL Cert as JSON from Device"
      uri:
        method: GET
        url: " https://{{ inventory_hostname }}/rest/configuration/ssl-certificates"
        return_content: yes
      register: listCertResult

# might not work directly in the loop but I hope it explains the idea        
- name: "Loop trough CertInfo"
  openssl_certificate_info:
     pem: "{{ item.attributes.serverCertificate }}"
  register: cert_info
  loop: "{{ listCertResult.json | json_query('data[*]') }}"
  loop_control:
     label: "{{ item.id }}"
```
