### ISSUE TITLE
Module mongodb_replicaset fails with "MongoDB Replicaset validation failed. Invalid arbiter index." even when arbiter index is correct

### ISSUE THREAD

**Issue by klingac** [ansible/ansible#64781]
##### SUMMARY
Trying to create mongodb replicaset with one arbiter with module mongodb_replicaset results in error if you set `validate` parameter to `true`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mongodb_replicaset

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/bin/ansible29/lib/python3.7/site-packages/ansible
  executable location = /home/user/bin/ansible29/bin/ansible
  python version = 3.7.5rc1 (default, Oct  8 2019, 16:47:45) [GCC 9.2.1 20191008]
```

##### CONFIGURATION

```paste below
DEFAULT_ACTION_PLUGIN_PATH(/home/klingac/.ansible.cfg) = ['/usr/local/lib/python2.7/dist-packages/ara/plugins/actions']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/klingac/.ansible.cfg) = ['/usr/local/lib/python2.7/dist-packages/ara/plugins/callbacks']
DEFAULT_CALLBACK_WHITELIST(/home/klingac/.ansible.cfg) = ['timer', 'profile_roles', 'actionable', 'counter_enabled', 'selective']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/klingac/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/klingac/.ansible.cfg) = actionable
HOST_KEY_CHECKING(/home/klingac/.ansible.cfg) = False
SHOW_CUSTOM_STATS(/home/klingac/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

uname -a

Linux wrk-ntb 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release

NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

##### STEPS TO REPRODUCE

Run playbook below. It will result to error no matter which of the members will be set as arbiter (try 0,1 or 2). Setting `validate` to `false` runs correctly.

```yaml
- hosts: mongo
  gather_facts: false
  tasks:
    - name: Ensure replicaset rs0 exists
      mongodb_replicaset:
        login_host: localhost
        login_user: admin
        login_password: admin
        login_database: admin
        replica_set: rs0
        arbiter_at_index: 1
        members:
          - mongo-1:27017
          - mongo-2:27017
          - mongo-3:27017
        validate: false
      when: groups.mongo.index(inventory_hostname) == 0
```

##### EXPECTED RESULTS

Expected result is completely opposite of actual behavior.
Setting `validate` to `true` should result to error only if arbiter index is incorrect - greater than (`number_of_members - 1`) or when you try to make an arbiter from already existing data member. 
Setting `validate` to `false` shouldn't do any validation.

##### ACTUAL RESULTS

Setting `arbiter_at_index` to correct index (e.g. 0) and `validate` to `true` will result to an error.

```paste below
TASK [Ensure replicaset rs0 exists] *************************
skipping: [mongo-2]
skipping: [mongo-3]
fatal: [mongo-1]: FAILED! => {"changed": false, "msg": "MongoDB Replicaset validation failed. Invalid arbiter index."}
```
Setting `validate` to `true` and `arbiter_at_index` to higher number, then max. index of members, will pass. Hovewer this is wrong and no arbiter will be created at last.

Setting `validate` to `false` works correctly and causes no errors.
