### ISSUE TITLE
zabbix_host module no longer supported in ansible >= 2.8.7

### ISSUE THREAD

**Issue by ericsysmin** [ansible/ansible#64819]
##### SUMMARY
The zabbix_host module now results in 
```
{"msg": "Failed to connect to Zabbix server: the first argument must be callable"}
```
In prior releases it worked fine. Looks like a possible edit that broke communication.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
```paste below
ansible 2.8.7
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

##### CONFIGURATION
```
  
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
  zabbix_host:
        login_user: "{{ deployment_zabbix_user }}"
        login_password: "{{ deployment_zabbix_password }}"
        server_url: "{{ deployment_zabbix_server }}"
        host_name: "{{ deployment_domain }}"
        host_groups:
          - "Group"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 127.0.0.1
            dns: ""
            port: 10050
        status: "{{ deployment_zabbix_host_status }}"
        state: "{{ deployment_zabbix_host_state }}"
      register: zabbix_host
      until: zabbix_host is success
      retries: 10
      delay: 2
```

##### EXPECTED RESULTS

Not a failure

##### ACTUAL RESULTS
```paste below
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "msg": "Failed to connect to Zabbix server: the first argument must be callable"}

```
