### ISSUE TITLE
Encryption in s3_sync module

### ISSUE THREAD

**Issue by calvinbui** [ansible/ansible#64818]
##### SUMMARY

The `s3_sync` module does not support any encryption options for uploads .The `aws_s3` module on the otherhand does. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`s3_sync`

https://docs.ansible.com/ansible/latest/modules/s3_sync_module.html

##### ADDITIONAL INFORMATION

```yaml
- name: basic upload
  s3_sync:
    bucket: tedder
    file_root: roles/s3/files/
    encrypt: true
    encryption_mode: AES256
```
