### ISSUE TITLE
docker_swarm_service force_update causes configuration loss

### ISSUE THREAD

**Issue by mcassaniti** [ansible/ansible#64820]
##### SUMMARY
When running the docker_swarm_service module to force a service update, and when the minimum number of parameters are supplied, the empty parameters are stripped from the service even though they don't show in the diff.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_swarm_service

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = /mnt/data/my-GIT-repos/ansible/ansible.cfg
  configured module search path = [u'/mnt/data/my-GIT-repos/ansible/library']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct  7 2019, 17:36:04) [GCC 8.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = True
DEFAULT_BECOME(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = False
DEFAULT_HOST_LIST(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = [u'/mnt/data/my-GIT-repos/ansible/hosts']
DEFAULT_MODULE_PATH(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = [u'/mnt/data/my-GIT-repos/ansible/library']
DEFAULT_REMOTE_USER(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = root
DEFAULT_SCP_IF_SSH(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/mnt/data/my-GIT-repos/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Controller OS: Ubuntu Linux 19.04
Target OS: Alpine Linux 3.10
Docker Version: 18.09

##### STEPS TO REPRODUCE
```yaml
  - name: Start my service
    docker_swarm_service:
      name: my-service
      image: "{{ image_name }}"
      resolve_image: yes
      env:
         - "SOME_ENV=some-value"

  - name: Restart my service
    docker_swarm_service:
      name: my-service
      image: "{{ image_name }}"
      resolve_image: yes
      force_update: true
```

##### EXPECTED RESULTS
Environment variable mentioned is maintained.

##### ACTUAL RESULTS
Environment variable mentioned is **not** maintained.

```paste below

```
