### ISSUE TITLE
vmware_guest : VM always created at same datastore as the template

### ISSUE THREAD

**Issue by wahaha2001** [ansible/ansible#64842]
##### SUMMARY

VM always created at same datastore as the template, even "autoselect_datastore" was set as True.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
ansible 2.6.6
  config file = /etc/releases/production/ansible/ansible.cfg
  configured module search path = [u'/etc/releases/production/ansible/library']
  ansible python module location = /etc/releases/production/venv/lib/python2.7/site-packages/ansible
  executable location = /etc/releases/production/venv/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_SSH_ARGS(/etc/releases/production/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=60 -o ServerAliveCountMax=60
ANSIBLE_SSH_CONTROL_PATH(/etc/releases/production/ansible/ansible.cfg) = %(directory)s/%%h-%%r
DEFAULT_FORKS(/etc/releases/production/ansible/ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(/etc/releases/production/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/etc/releases/production/ansible/inventory']
DEFAULT_MANAGED_STR(/etc/releases/production/ansible/ansible.cfg) = Ansible managed: modified on %Y-%m-%d %H:%M:%S
DEFAULT_MODULE_PATH(/etc/releases/production/ansible/ansible.cfg) = [u'/etc/releases/production/ansible/library']
DEFAULT_PRIVATE_KEY_FILE(env: ANSIBLE_PRIVATE_KEY_FILE) = /etc/releases/production/files/infra_orc_ssh_rsa
DEFAULT_ROLES_PATH(/etc/releases/production/ansible/ansible.cfg) = [u'/etc/releases/production/ansible/roles']
DEFAULT_SCP_IF_SSH(/etc/releases/production/ansible/ansible.cfg) = True
DEFAULT_TIMEOUT(/etc/releases/production/ansible/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /etc/releases/production/files/vault-pass.txt
HOST_KEY_CHECKING(/etc/releases/production/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/releases/production/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: XXXXXX
      username: XXXXXX
      password: XXXXXX
      validate_certs: False
      name: "{{ vmname }}"
      template: vmtemplate
      datacenter: DevCenter
      cluster: Dev
      folder: /VM
      state: poweredoff
      networks:
      - name: "VMNetwork"
        type: dhcp
      disk:
      - size_gb: 1000
        type: thin
        datastore: datastore
        autoselect_datastore: True
        disk_mode: independent_persistent
      wait_for_ip_address: no
    register: guest_facts
```

##### EXPECTED RESULTS

There have two esxi server in same cluster, each esxi have its own local datastore(can't share cross esxi servers, esxi01 with datastore01, esxi02 with datastore02). 
The vm template "vmtemplate" was stored at datastore01.  

We hope when create VM from template "vmtemplate", the new VM's disk can be allocated to a proper datastore automatically, mean can be balanced between datastores.

##### ACTUAL RESULTS

All new VMs' disk were created at datastore01, same datastore as template.  No one was created at datastore02

```paste below

```
