### ISSUE TITLE
Win_updates : does not install malicious sofware tool and drivers

### ISSUE THREAD

**Issue by daemenseth** [ansible/ansible#64849]
##### SUMMARY

Win_updates : does not install malicious sofware removal tool and drivers. I have added all categories.

see screenshot
![IMG_20191114_162444](https://user-images.githubusercontent.com/7492384/68883884-377d8480-0712-11ea-9349-cc2a664b82e8.jpg)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION

```2.7.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
target os is server 2019

##### STEPS TO REPRODUCE

```yaml
  - name: Install missing updates Loop "{{ outer_item }}".
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    register: update_result
    ignore_errors: yes
```

##### EXPECTED RESULTS
All updates installed.

##### ACTUAL RESULTS

```paste below

```
