### ISSUE TITLE
Match filter disappears ?

### ISSUE THREAD

**Issue by alk-rniveau** [ansible/ansible#64845]
##### SUMMARY
Match filter seems to have disappeared with the 2.9.1. I can't find anything about that in the changelog

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
assert

##### ANSIBLE VERSION
```ansible-playbook 2.9.1
config file = /home/deploy/infrastructure-ansible/ansible.cfg
configured module search path = [u'/home/deploy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /home/deploy/infrastructure-ansible/.venv/local/lib/python2.7/site-packages/ansible
executable location = /home/deploy/infrastructure-ansible/.venv/bin/ansible-playbook
python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ubuntu 16.04
OsX 10.14.5

##### STEPS TO REPRODUCE
Works with 2.8.5, not with 2.9.1

```
  - name: test
    assert:
      that: "{{ '0' | match('[0-9]') }}"
      fail_msg: "Instance must be a number"
  run_once: true

```

##### EXPECTED RESULTS
```
ok: [localhost] => changed=false
  msg: All assertions passed``` 

##### ACTUAL RESULTS
```fatal: [localhost]: FAILED! =>
  msg: 'template error while templating string: no filter named ''match''. String: {{ ''0'' | match(''[0-9]'') }}'

```
