### ISSUE TITLE
add dnf module enable/disable support

### ISSUE THREAD

**Issue by marcelvanveen** [ansible/ansible#64852]
##### SUMMARY
Update the dnf module to enable/disable modules (currently only install/remove is supported). 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- dnf

##### ADDITIONAL INFORMATION
To install 389-ds-base on CentOS 8, you first need to enable module '389-ds:1.4'. 
Using `dnf: name="@389-ds" state=present`, the module will not be enabled. 

Latest version of python-dnf does support enabling modules:
```import dnf

base = dnf.Base()
base.read_all_repos()
base.fill_sack()

module_base = dnf.module.module_base.ModuleBase(base)
module_base.enable(['389-ds:1.4'])

base.do_transaction()
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/dnf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DJMuggs @berenddeschouwer @ignatenkobrain @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by geerlingguy** [comment]
Subscribe; I'm trying to update some of my roles to support CentOS 8 / RHEL 8, and finding it annoying to do so, because I either need to use the full appstream spec in each package name (e.g. `php:remi-7.3`), or manually run `dnf module enable php:remi-7.3` in a `command` prior to yum/dnf install tasks.

Related: https://github.com/geerlingguy/ansible-role-php-versions/issues/44

**Comment by samdoran** [comment]
Does this capability already exist in the module, possibly the `enablerepo` or `disablerepo` parameters? From looking at the code, it seems this may have been added in 6d95624c22d1c275974db1e7c94dcc171dc1457e.

needs_info

**Comment by geerlingguy** [comment]
@samdoran - That seems to not be the case.

I tried the following (assuming `php_version` equals something like `7.4` and you have remi's repo already configured earlier):

```yaml
  tasks:
    - command: dnf module enable -y php:remi-{{ php_version }}
    - package:
      name: php-imap
      state: present
```

And that worked.

When I tried using enablerepo, it did not work (gave me the 'no package found' message):

```yaml
  tasks:
    - package:
      name: php-imap
      state: present
      enablerepo: remi-{{ php_version }}
```

(I also tried with `enablerepo: "php:remi-{{ php_version }}" and that didn't work.)

**Comment by sivel** [comment]
The code to do this does seem present, and it does roughly mirror that of the code sample from @marcelvanveen

Perhaps there is some subtle difference in the logic.

cc @maxamillion

**Comment by maxamillion** [comment]
@samdoran enabling modules and enabling repos are unfortunately not the same thing

@marcelvanveen how would you like to see the enable/disable functionality presented to the user? ... do you have an example task in mind that you'd like to see function? I can't think of a good clean way without overloading params and I generally prefer not to do that but I'm open to suggestion on this. I was thinking of adding an `enabled: true|false` param but that gets wonky with `state: present|absent`. Thoughts?

**Comment by sivel** [comment]
@maxamillion in our triage this morning, we assumed that it should only be enabled for the term of the module invocation, not persisting, but I don't have enough understanding of modules and dnf.

We were basically working off of the assumption that they would work like repos.  I'm not sure we should expose management of modules through the `dnf` module.  If necessary, management of a module should likely be another module.

My 2c is that the `dnf` module should concern itself with the lifecycle of packages, and not the configuration of dnf.

**Comment by geerlingguy** [comment]
So maybe a `dnf_config` or `dnf_module` module or something? We do have things like `apt_key`, `apt_repo`, `apt_repository`... and `yum` and `yum_repository`.

But the paradigm is a little strange, I grant :/

**Comment by HighKing81** [comment]
If a module has already been set and packages are installed, you have to do a 'dnf module reset' before you can issue a 'dnf module enable' command. So maybe an extra bool 'reset' would be nice?

This way you could upgrade a package by selecting another stream.

**Comment by ansibot** [comment]
@marcelvanveen This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Oof, this is a bit messier than I originally thought. I agree with @sivel that we probably need another module for configuring appstreams rather than further complicating the `dnf` module by allowing it to manage appstreams as well.

**Comment by marcelvanveen** [comment]
The suggestion by @geerlingguy seems perfectly fine. Regarding the extra bool 'reset': I would suggest to keep this as one of the values of state (so enabled, disabled or reset). 

If one wants to switch streams (for example, from php:remi-7.2 to php:remi-7.4), I would expect the following code to automatically perform the required actions (optionally uninstall all packages related to the old php:remi-7.2 stream, reset the php module and then enable php:remi-7.4 stream):

```yaml
tasks:
  - dnf_module:
      name: php:remi-{{ php_version }}
      state: enabled
      allow_switch_module_streams: true

  - package:
      name: php-imap
      state: present
```

That way, a playbook can be used for both upgrading a machine already containing a php:remi-7.2 installation and provisioning a new machine with php:remi-7.4.

I've added the extra bool parameter: `allow_switch_module_streams`, defaulting to false, for concerns about automatically uninstalling all packages related to the old php:remi-7.2 stream, which may be undesired default behavior.

**Comment by wixaw** [comment]
Hello @geerlingguy 
I use your playbook and to adap; I use this :
```
  - name: install the nginx rpm from a remote repo
    dnf:
      name: 'https://rpms.remirepo.net/enterprise/remi-release-8.rpm'
      state: present

  - name: enable remi-php repo 
    shell:
      cmd: dnf module enable -y php:remi-{{ php_version }}      

  - name: disable remi-safe repo
    shell:
      cmd: dnf config-manager --disable remi-safe
```

**Comment by mkubenka** [comment]
More idempotent way without using `command`/`shell`:

```yaml
- name: disable default mysql module
  copy:
    dest: /etc/dnf/modules.d/mysql.module
    content: |
      [mysql]
      name=mysql
      stream=
      profiles=
      state=disabled
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hoax89** [comment]
> 
> 
> More idempotent way without using `command`/`shell`:
> 
> ```yaml
> - name: disable default mysql module
>   copy:
>     dest: /etc/dnf/modules.d/mysql.module
>     content: |
>       [mysql]
>       name=mysql
>       stream=
>       profiles=
>       state=disabled
>   when: 
>     - ansible_os_family == 'RedHat'
>     - ansible_distribution_major_version | int >= 8
> ```

How would you reload this configuration? If I execute this, it (obviously) changes the config file, but `dnf module list` (and dnf install, for that matter) acts as if nothing happens. Is there any way to reload the configuration or something?

**Comment by juergenhoetzel** [comment]
> More idempotent way without using `command`/`shell`:

Alternative (`dnf module enable` is an idempotent command):

```yaml
    - name: "Enable mod_auth_openidc module"
      command: dnf module enable -y mod_auth_openidc
      register: result
      changed_when:
        - '"Enabling module streams" in result.stdout'
```

**Comment by arocki7** [comment]
I'm not sure whether we need a separate module. We can already do this as a part of DNF/YUM module.

```
- name: Install PHP {{ php_version }} from Remi
  dnf:
    name: "@php:remi-{{ php_version }}"
    state: present
```

It works for me.

**Comment by mkubenka** [comment]
@arocki7 There are use-cases when you want to disable certain modules. For example when using MySQL repositories:

> (EL8 systems only) EL8-based systems such as RHEL8 and Oracle Linux 8 include a MySQL module that is enabled by default. Unless this module is disabled, it masks packages provided by MySQL repositories

https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html#yum-repo-disabling-mysql

**Comment by kristvanbesien** [comment]
I currently have a scenario where I need this as well.

I need to enable a stream on several hosts, so I was hoping I could do: 
```
- name: Make sure the correct virt stream is selected.
    yum:
      name: '@virt:8.2' 
      state: present
```

But this lead to an error. The reason is that this tries to install the module, not enable it, and this fails. 

So I had to resort to just running "dnf module enable virt:8.2". And as a result again I do not have an idempotent playbook :-(

**Comment by carpii** [comment]
I ended up using this mess for installing php from remi stream...

PHP not installed: installs from remi
PHP already installed from default stream: removes it and installs from remi
PHP version number var changes: removes old and installs new version
Run repeatedly: reports no changes

````
vars

php_module_name: "php"
php_version: "7.4"
php_desired_repo: "remi"
php_desired_stream: "{{ php_desired_repo }}-{{ php_version }}"
php_packages:
  - php-devel
  - php-pdo
  - php-cli
  - php-opcache

tasks

- name: install remi repo
  include_tasks: setup_remi_repo.yml

- name: get the rpm package facts
  package_facts:
    manager: "auto"

- block:
  - name: "Retrieve remote php module file"
    fetch:
      src: "/etc/dnf/modules.d/{{ php_module_name }}.module"
      dest: /tmp/ansible
    changed_when: false  
    
  - name: "Read stream from {{ php_module_name }} module"
    set_fact:
      current_stream: "{{ lookup( 'ini', 'stream section={{ php_module_name }} file=/tmp/ansible/{{ inventory_hostname }}/etc/dnf/modules.d/{{ php_module_name }}.module' ) }}"

  - name: "Remove existing {{ php_module_name }}"
    dnf:
      name: "{{ php_module_name }}"
      state: absent
    when: current_stream != php_desired_stream      
    
  - name: reset {{ php_module_name }} module
    command: "dnf module reset -y {{ php_module_name }}"
    args: 
      warn: false
    when: 
      - current_stream != php_desired_stream
      
  - name: "Enable {{ php_module_name }}:{{ php_desired_stream }} module"
    command: "dnf module enable -y {{ php_module_name }}:{{ php_desired_stream }}"
    args: 
      warn: false
    register: dnf_module_php_enabled
    when: current_stream != php_desired_stream
    
  - name: Install {{ php_module_name }} {{ php_version }} from {{ php_desired_stream }}
    dnf:
      enablerepo: {{ php_desired_repo }}
      name: "@{{ php_module_name }}:{{ php_desired_stream }}"
      state: present
    when: dnf_module_php_enabled

- name: Installing additional PHP packages 
  dnf:
    name: "{{ php_packages }}"
    update_cache: yes
  when: current_stream != php_desired_stream
````

**Comment by aadnehovda** [comment]
> More idempotent way without using `command`/`shell`:
> 
> ```yaml
> - name: disable default mysql module
>   copy:
>     dest: /etc/dnf/modules.d/mysql.module
>     content: |
>       [mysql]
>       name=mysql
>       stream=
>       profiles=
>       state=disabled
>   when: 
>     - ansible_os_family == 'RedHat'
>     - ansible_distribution_major_version | int >= 8
> ```

Untested, but think should work too (for MariaDB in this case).

```yaml
  - name: disable default MariaDB module
    ini_file:
      path: /etc/dnf/modules.d/mariadb.module
      section: mariadb
      option: state
      value: disabled
      no_extra_spaces: yes
```
