### ISSUE TITLE
lineinfile race condition 

### ISSUE THREAD

**Issue by mslebodnik** [ansible/ansible#64899]
##### SUMMARY
when running following task from different playbooks simultaneously, sometimes only one update is in /etc/hosts, but both tasks finished succesfully 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```
ansible 2.7.7
  config file = /opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg
  configured module search path = [u'/home/ans/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible-2.7.7/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/ansible-2.7.7/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = 8
DEFAULT_GATHER_TIMEOUT(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = 30
DEFAULT_LOG_PATH(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = /service/prov/log/ansible.log
DEFAULT_TIMEOUT(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = [u'ini', u'host_list', u'virtualbox', u'yaml', u'constructed']
INVENTORY_IGNORE_EXTS(/opt/ansible/ansible-2.7.7/etc/ansible/ansible.cfg) = [u'.pyc', u'.pyo', u'.swp', u'.bak', u'~', u'.rpm', u'.md', u'.txt', u'~', u'.orig', u'.ini', u'.cfg', u'.retry']
```

##### OS / ENVIRONMENT
[ans@master ~]$ uname -a
Linux master.prg-dc.dhl.com 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
[ans@master ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### STEPS TO REPRODUCE

- not easy to reproduce ( run same playbook twice at same point e.g. makefile)

```
 - name: Fix IP address in /etc/hosts file
    lineinfile:
      dest: /etc/hosts
      line: "{{ lbm_ip }} {{ lbm_hostname }}.{{ domainname }} {{ lbm_hostname }}"
      state: present
      regexp: "\\b{{ lbm_hostname }}$"
  delegate_to: localhost
```

##### EXPECTED RESULTS
in /etc/hosts all entries  entry 
e.g 

```
172.28.128.75 r7g3_75.prg-dc.com r7g3_75
172.28.128.76 r7g3_76.prg-dc.com r7g3_76
```

##### ACTUAL RESULTS

```
172.28.128.75 r7g3_75.prg-dc.com r7g3_75
```
