### ISSUE TITLE
allow_duplicates: an example of a document doesn't work

### ISSUE THREAD

**Issue by knagamin** [ansible/ansible#64902]
##### SUMMARY

[The document](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-duplication-and-execution) says that `allow_duplicates: true` makes it possible to execute a same role multiple times in play but it doesn't work. Actually I'm not sure the current behavior is not intended or it's just an omission of correction in documents. However, I think the variable should enable the control of that execution as stated in the example because we can do that in `roles` directive.

Edit (sivel): This appears to have been caused by 376b199c0540e39189bdf6b31b9a60eadffa3989

Something is likely looking at the wrong reference of `play.roles`, maybe instead of using `self._extend_value` in `_load_roles` we can switch to doing: `self.roles[:0] = roles` so the reference stays the same. Or someone can track down the incorrect reference.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

allow_duplicates

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /home/knagamin/t/ansible/ansible-test-allow_duplicates/ansible.cfg
  configured module search path = ['/home/knagamin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/knagamin/.local/lib/python3.7/site-packages/ansible
  executable location = /home/knagamin/.local/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

NOTE: I tried it with some older versions then I found that It works correctly in v2.7.0 but doesn't in v2.7.1

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

* target OS version

```
$ uname -srvmpio
Linux 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

* Directory structure

```
├── playbook.yml
└── roles
    └── test_role
        ├── meta
        │   └── main.yml
        └── tasks
             └── main.yml
```

* `./playbook.yml`

```yaml

---
- name: test for allow_duplicates
  hosts: localhost
  gather_facts: false
  roles:
    - role: test_role
    - role: test_role
    - role: test_role
```

* `./roles/test_role/task/main.yml`

```yaml
---
# tasks file for test_role

- name: Just show a message
  debug:
      msg: "hoge"

```

* `./roles/test_role/meta/main.yml`
```yaml
galaxy_info:
  author: your name
  description: your role description
  company: your company (optional)
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
allow_duplicates: true
```

##### EXPECTED RESULTS

```
PLAY [test for allow_duplicates] *************************************************************************************

TASK [test_role : Just show a message] *******************************************************************************
ok: [localhost] => {
        "msg": "hoge"
}

TASK [test_role : Just show a message] *******************************************************************************
ok: [localhost] => {
        "msg": "hoge"
}

TASK [test_role : Just show a message] *******************************************************************************
ok: [localhost] => {
        "msg": "hoge"
}

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

```paste below
PLAY [test for allow_duplicates] *************************************************************************************

TASK [test_role : Just show a message] *******************************************************************************
ok: [localhost] => {
        "msg": "hoge"
}

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
