### ISSUE TITLE
notify is silently ignored on import_tasks

### ISSUE THREAD

**Issue by aschult5** [ansible/ansible#64935]
##### SUMMARY

`notify` is silently ignored on `import_tasks`.
This leads to unexpected behavior.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

import_tasks

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/aschultz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/aschultz/dev/vendor/ansible/lib/ansible
  executable location = /home/aschultz/dev/vendor/ansible/bin/ansible-playbook
  python version = 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]
```

##### STEPS TO REPRODUCE

`ansible-playbook test.yml -c local -l localhost`

*test.yml:*
```yaml
- hosts: localhost
  tasks:
    - import_tasks: tasks.yml
      notify:
        - myhandler

  handlers:
    - name: myhandler
      debug:
        msg: "handler"
```

*tasks.yml:*
```yaml
- name: a touch
  file:
    path: /tmp/touchme
    state: touch
```

##### EXPECTED RESULTS

An error is printed similar to the one for `include_tasks`, i.e.
> ERROR! 'notify' is not a valid attribute for a TaskInclude

##### ACTUAL RESULTS

The notify attribute is ignored.

```paste below
PLAY [localhost] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [a touch] ************************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
