### ISSUE TITLE
openssh_keypair module not idempotent on debian

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#64969]
##### SUMMARY
`openssh_keypair` seem to report changed in cases where it shouldn't

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

openssh_keypair

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = None
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/florian/.local/pipx/venvs/ansible/lib64/python3.7/site-packages/ansible
  executable location = /home/florian/.local/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT

Debian Sid in a docker container, see playbook below

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  gather_facts: no

  tasks:
    - docker_container:  name=testing_debian state=started image=debian:sid command="sleep infinity"
    - add_host: name=testing_debian ansible_connection=docker

- hosts: testing_debian
  gather_facts: no

  tasks:
    # Ensure we start from a consistent state
    - raw: "apt -y update && apt -y install python openssh-client"
    - file: path=/tmp/key state=absent
    - file: path=/tmp/key.pub state=absent

    # full reproducer here

    - openssh_keypair: path=/tmp/key comment=test type=ed25519 
    - openssh_keypair: path=/tmp/key comment=test type=ed25519 
```

##### EXPECTED RESULTS

I'd expect the second `openssh_keypair` task to report unchanged.

##### ACTUAL RESULTS

Both tasks show up as changed:

```paste below
TASK [file] **********************************************************************************************************************************************************************************************************************************
[WARNING]: Platform linux on host testing_debian is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

ok: [testing_debian] => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "path": "/tmp/key", "state": "absent"}

TASK [file] **********************************************************************************************************************************************************************************************************************************
ok: [testing_debian] => {"changed": false, "path": "/tmp/key.pub", "state": "absent"}

TASK [openssh_keypair] ***********************************************************************************************************************************************************************************************************************
changed: [testing_debian] => {"changed": true, "comment": "test", "filename": "/tmp/key", "fingerprint": "SHA256:k7zoCrUKcwjfvSsKSr+zElJL5wGgCbmNsgGdD4qXp6o", "public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ5JTc62+6h0NlqM0r5pranKV3kXS7+XbzO9ZPeY2f36 test", "size": 256, "type": "ed25519"}

TASK [openssh_keypair] ***********************************************************************************************************************************************************************************************************************
changed: [testing_debian] => {"changed": true, "comment": "test", "filename": "/tmp/key", "fingerprint": "SHA256:k7zoCrUKcwjfvSsKSr+zElJL5wGgCbmNsgGdD4qXp6o", "public_key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ5JTc62+6h0NlqM0r5pranKV3kXS7+XbzO9ZPeY2f36 test", "size": 256, "type": "ed25519"}
```
