### ISSUE TITLE
dnf/yum module not idempotent and reports changed for an installed package

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#64963]
##### SUMMARY

When installing epel-release with `dnf/yum` it reports as changed even though the package is already installed. This happens because the second iteration performs an upgrade!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dnf

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = None
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/florian/.local/pipx/venvs/ansible/lib64/python3.7/site-packages/ansible
  executable location = /home/florian/.local/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
```

##### OS / ENVIRONMENT

Target OS is centos:8 in a docker container

##### STEPS TO REPRODUCE

Example playbook:
```yaml
---

- hosts: localhost
  gather_facts: no

  tasks:
    - docker_container:  name=testing_dnf state=started image=centos:8 command="sleep infinity"
    - add_host: name=testing_dnf ansible_connection=docker

- hosts: testing_dnf
  gather_facts: no

  tasks:
    # Ensure we start from a consistent state
    - dnf: name=epel-release state=absent

    # full reproducer here

    # Reports changed, this is okay because epel-release was not installed
    - dnf: name=epel-release state=installed

    # Reports change because it upgraded epel-release, this should not happen
    - dnf: name=epel-release state=installed
```

##### EXPECTED RESULTS

The first epel-release installation should report changed, while the second shouldn't cause any changes.

##### ACTUAL RESULTS

Runnig  `ansible-playbook -v site.yml` will result in
```paste below
TASK [dnf] ***********************************************************************************************************************************************************************************************************************************
changed: [testing_dnf] => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": true, "msg": "", "rc": 0, "results": ["Removed: epel-release-8-7.el8.noarch"]}

TASK [dnf] ***********************************************************************************************************************************************************************************************************************************
changed: [testing_dnf] => {"changed": true, "msg": "", "rc": 0, "results": ["Installed: epel-release", "Installed: epel-release-8-5.el8.noarch"]}

TASK [dnf] ***********************************************************************************************************************************************************************************************************************************
changed: [testing_dnf] => {"changed": true, "msg": "", "rc": 0, "results": ["Installed: epel-release", "Installed: epel-release-8-7.el8.noarch", "Removed: epel-release-8-5.el8.noarch"]}
```
One can see that the second run upgrades epel-release from 8-5 to 8-7, imo this should not happen.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/dnf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DJMuggs @berenddeschouwer @ignatenkobrain @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dthielking** [comment]
@apollo13 I have the same problem, did you find any workaround for that?

**Comment by apollo13** [comment]
Aside from simply putting a "changed_when: false" or actually inspecting the resulting stdout and then adjusting changed_when base on that no

**Comment by dthielking** [comment]
Ok, I just added this one here.
```yaml
- name: check if epel is installed workaround Centos 8
   shell: "rpm -qa | grep epel-release"
     register: __epel_installed
     changed_when: false
     args:
       warn: false
     when:
       - ansible_os_family == "RedHat"
       - ansible_distribution_major_version == "8"

- name: install epel repository
   yum:
     name: epel-release
     state: present
     update_cache: yes
   when:
     - ansible_os_family == "RedHat"
     - ansible_distribution_major_version == "8"
     - __epel_installed.rc == 1
     - dots_enable_epel_repo
  become: true
```
