### ISSUE TITLE
Synchronize module does not work when remote shell is zsh

### ISSUE THREAD

**Issue by davidolrik** [ansible/ansible#64971]
##### SUMMARY
When rsync'en to a remote host that uses zsh the rsync fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[synchronize](https://docs.ansible.com/ansible/latest/modules/synchronize_module.html)

##### ANSIBLE VERSION
```
ansible 2.9.1
  config file = /Users/djo/Projects/grepmasters-ansible/ansible.cfg
  configured module search path = ['/Users/davidolrik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/davidolrik/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ansible
  executable location = /Users/davidolrik/.pyenv/versions/3.7.2/bin/ansible
  python version = 3.7.2 (default, Feb 19 2019, 23:16:25) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### OS / ENVIRONMENT

Target system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
Shell: zsh
```

##### STEPS TO REPRODUCE

```yaml
  - name: Sync certificates to target host
    synchronize:
      src: /etc/letsencrypt/live/{{ item }}
      dest: /etc/ssl/letsencrypt/
      mode: push
      copy_links: true
      dest_port: 1234
      delete: true
      rsync_opts: '--chown=root:ssl-cert --chmod=D0750 --chmod=F640'
    with_items: ['example.com']
```

##### EXPECTED RESULTS

Files are uploaded

##### ACTUAL RESULTS

rsync fails

```
failed: [synchronize task] (item=example.com) => {"ansible_loop_var": "item", "changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --copy-links --archive --rsh=/usr/bin/ssh -S none -o Port=1234 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --chown=root:ssl-cert --chmod=D0750 --chmod=F640 --out-format=<<CHANGED>>%i %n%L /etc/letsencrypt/live/example.com root@target.example.com:/etc/ssl/letsencrypt/", "item": "example.com", "msg": "Warning: Permanently added '[target.example.com]:1234,[<ip>]:1234' (ECDSA) to the list of known hosts.\r\nzsh:1: no matches found: --usermap=*:root\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.2]\n", "rc": 12}
```

I suspect that the `*` in `zsh:1: no matches found: --usermap=*:root\nrsync` is what makes rsync choke as it needs to be escaped when using zsh.

Changing shell on the target host to bash makes the error go away.
