### ISSUE TITLE
win_psexec module is exposing password to output 

### ISSUE THREAD

**Issue by cuichenli** [ansible/ansible#64978]
##### SUMMARY
The `win_psexec` module is exposing the password and username to output, is that intended? Is there a way to hide it? Thanks!

My playbook:
```
- name: Psexec
  win_psexec:
    command: >
      powershell.exe 
    session: 1
    wait: yes
    interactive: yes
    username: "username"
    password: "password"
```
 
```
changed: [MYSERVER] => {
	....
    "psexec_command": "psexec64.exe -u username -p password -i 1 -accepteula powershell.exe",
  	....
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_psexec

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

Host OS : Linux
Target OS: Windows
