### ISSUE TITLE
git module fails with "failed to stat '.': Permission denied"

### ISSUE THREAD

**Issue by yuriks** [ansible/ansible#6499]
##### Issue Type:

Bug report
##### Ansible Version:

`ansible-playbook 1.5.3`
##### Environment:

Both host and slave are running Ubuntu Server 12.04LTS
##### Summary:

This is the same issue as #6443 which doesn't seem to be fixed as of 1.5.3.

```
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook --version
ansible-playbook 1.5.3
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook -i yuriks.inventory site.yml

PLAY [glide-servers] **********************************************************

GATHERING FACTS ***************************************************************
ok: [provision]

[~~~snip~~~]

TASK: [cm | check out glide-cm] ***********************************************
failed: [provision] => {"cmd": ["/usr/bin/git", "ls-remote", "git@github.com:digEcor/glide-cm.git", "-h", "refs/heads/develop"], "failed": true, "item": "", "rc": 128}
stderr: fatal: failed to stat '.': Permission denied

msg: fatal: failed to stat '.': Permission denied

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/yuriks/site.retry

provision                  : ok=9    changed=0    unreachable=0    failed=1
```

The playbook is being run as root, but the git step has sudo and sudo_user fields to run as an unprivileged user. What seems to be happening is that the `git` command is being run with a cwd of `/root`, which isn't readable by the unprivileged user. Git tries to stat it and fails.
##### Steps To Reproduce:

Try to clone a new git repository using sudo.
##### Expected Results:

Cloning to succeed to the unprivileged user-owned directory.
##### Actual Results:

Git tries to read a directory it doens't have access to and aborts.

**Comment by mpdehaan** [comment]
Thanks, we'll take a look this very soon!

**Comment by jctanner** [comment]
@yuriks Can you show me the task from the playbook? 

I'm unable to reproduce based on my current understanding of the description:

```
- hosts: el6.lab.net
  #connection: local
  gather_facts: False
  user: jtanner
  tasks:
    - shell: whoami
    - shell: whoami
      sudo: True
    - shell: whoami
      sudo: True
      sudo_user: jtanner

    - git: repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/1
    - git: repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/2
      sudo: True
    - git: repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/3
      sudo: True
      sudo_user: jtanner
```

```
jtanner@u1204:~/issues/6499-git-path-sudo-fail$ ansible-playbook -v -i inventory site.yml

PLAY [el6.lab.net] ************************************************************

TASK: [shell whoami] **********************************************************
changed: [el6.lab.net] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002198", "end": "2014-03-17 10:49:18.204074", "rc": 0, "start": "2014-03-17 10:49:18.201876", "stderr": "", "stdout": "jtanner"}

TASK: [shell whoami] **********************************************************
changed: [el6.lab.net] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002212", "end": "2014-03-17 10:49:18.409052", "rc": 0, "start": "2014-03-17 10:49:18.406840", "stderr": "", "stdout": "root"}

TASK: [shell whoami] **********************************************************
changed: [el6.lab.net] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002191", "end": "2014-03-17 10:49:18.644251", "rc": 0, "start": "2014-03-17 10:49:18.642060", "stderr": "", "stdout": "jtanner"}

TASK: [git repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/1] ***
ok: [el6.lab.net] => {"after": "badf58e9edd821f611387a0907d56c002453b249", "before": "badf58e9edd821f611387a0907d56c002453b249", "changed": false}

TASK: [git repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/2] ***
ok: [el6.lab.net] => {"after": "badf58e9edd821f611387a0907d56c002453b249", "before": "badf58e9edd821f611387a0907d56c002453b249", "changed": false}

TASK: [git repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/3] ***
ok: [el6.lab.net] => {"after": "badf58e9edd821f611387a0907d56c002453b249", "before": "badf58e9edd821f611387a0907d56c002453b249", "changed": false}

PLAY RECAP ********************************************************************
el6.lab.net                : ok=6    changed=3    unreachable=0    failed=0
```

**Comment by yuriks** [comment]
I can't, but I'll try to create a self-contained repro.

**Comment by yuriks** [comment]
Ah. For this to happen, user: needs to be root, so that `$HOME` is set to `/root`

**Comment by yuriks** [comment]
Repro playbook:

```
- hosts: provision
  user: root
  tasks:
    - git: repo=https://github.com/jctanner/ansible-pull-test dest=/home/digecor/ansible-pull-test
      sudo: True
      sudo_user: digecor
```
