### ISSUE TITLE
Rescue tasks are run after a role called with import_role or include_role

### ISSUE THREAD

**Issue by mooninite** [ansible/ansible#64999]
##### SUMMARY

Block + Rescue behavior is unexpected when the Rescue is inside of a role that is called with import_role or include_role. The Rescue tasks are called *after* the role completes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

import_role
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/michael/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```
This bug has occurred since at least 2.8.

##### CONFIGURATION

```paste below
none
```

##### OS / ENVIRONMENT

Occurs in Fedora or RHEL or Ansible Tower.

##### STEPS TO REPRODUCE

```yaml
inventory
---------
[test_inv]
h1
h2

role test
---------
- name: FIRST
  debug: msg="first {{ lookup('pipe', 'date -Is') }}"

- block:
   - fail:
     when: inventory_hostname == 'h1'
  rescue:
    - pause:
        seconds: 5
    - name: SECOND
      debug: msg="second {{ lookup('pipe', 'date -Is') }}"

- name: THIRD
  debug: msg="third {{ lookup('pipe', 'date -Is') }}"
- name: FOURTH
  debug: msg="fourth {{ lookup('pipe', 'date -Is') }}"


playbook with roles and working
-------------------------------
- hosts: test_inv
  gather_facts: false
  roles:
    - test 

playbook with import_role and task executed in wrong order
----------------------------------------------------------
- hosts: test_inv
  gather_facts: false
  tasks:
    - import_role:
        name: test 
```

##### EXPECTED RESULTS

```json
h1 | SUCCESS => {    "changed": false,     "msg": "first 2019-11-16T00:32:19,950301026+01:00"}
h2 | SUCCESS => {    "changed": false,     "msg": "first 2019-11-16T00:32:19,955562309+01:00"}
h1 | FAILED! => {"changed": false, "msg": "Failed as requested from task"}
h2 | SKIPPED
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
h1 | SUCCESS => {"changed": false, "delta": 5, "echo": true, "rc": 0, "start": "2019-11-16 00:32:19.984584", "stderr": "", "stdout": "Paused for 5.0 seconds", "stop": "2019-11-16 00:32:24.984690", "user_input": ""}
h1 | SUCCESS => {    "changed": false,     "msg": "second 2019-11-16T00:32:25,001714127+01:00"}
h1 | SUCCESS => {    "changed": false,     "msg": "third 2019-11-16T00:32:25,018989962+01:00"}
h2 | SUCCESS => {    "changed": false,     "msg": "third 2019-11-16T00:32:25,024043908+01:00"}
h1 | SUCCESS => {    "changed": false,     "msg": "fourth 2019-11-16T00:32:25,043906428+01:00"}
h2 | SUCCESS => {    "changed": false,     "msg": "fourth 2019-11-16T00:32:25,049696619+01:00"} 
```

##### ACTUAL RESULTS

```json
h1 | SUCCESS => {    "changed": false,     "msg": "first 2019-11-16T00:34:02,669290823+01:00"}
h2 | SUCCESS => {    "changed": false,     "msg": "first 2019-11-16T00:34:02,674770477+01:00"}
h1 | FAILED! => {"changed": false, "msg": "Failed as requested from task"}
h2 | SKIPPED
h2 | SUCCESS => {    "changed": false,     "msg": "third 2019-11-16T00:34:02,709790864+01:00"}
h2 | SUCCESS => {    "changed": false,     "msg": "fourth 2019-11-16T00:34:02,728107251+01:00"}
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
h1 | SUCCESS => {"changed": false, "delta": 5, "echo": true, "rc": 0, "start": "2019-11-16 00:34:02.741146", "stderr": "", "stdout": "Paused for 5.0 seconds", "stop": "2019-11-16 00:34:07.741254", "user_input": ""}
h1 | SUCCESS => {    "changed": false,     "msg": "second 2019-11-16T00:34:07,759276494+01:00"}
h1 | SUCCESS => {    "changed": false,     "msg": "third 2019-11-16T00:34:07,779777709+01:00"}
h1 | SUCCESS => {    "changed": false,     "msg": "fourth 2019-11-16T00:34:07,799599716+01:00"} 
```
