### ISSUE TITLE
FortiOS - Support more encryption proposals for IPsec VPN Connections

### ISSUE THREAD

**Issue by forestoden** [ansible/ansible#65003]
##### SUMMARY

FortiGate firewalls support a multitude of encryption standards for VPN proposals. When going to configure a `fortios_vpn_ipsec_phase1_interface` and `fortios_vpn_ipsec_phase2_interface`, the `proposal` only allows for DES encryption. In the CLI and GUI, there are much more encryption options that are supported. Ansible should support these features, because right now the VPN configuration has to be fixed in the GUI or CLI after running Ansible.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

fortios

##### ADDITIONAL INFORMATION

```yaml
- name: fortios vpn phase1 interface
  fortios_vpn_ipsec_phase1_interface:
    host: "{{ host }}"
    username: "{{ username }}" 
    password: "{{ password }}"
    vdom: "root"
    https: "True"
    ssl_verify: False
    state: "present"
    vpn_ipsec_phase1_interface:
      dhgrp: "2"
      dpd_retryinterval: "10"
      interface: "port1"
      keylife: "28800"
      remote_gw: "{{ remote_gw_ip }}"
      name: "vpn"
      proposal: "aes128-sha1" #This is not supported today (along with any non-DES proposal)
      psksecret: "{{ psk_secret }}"
```

Please let me know if I'm simply missing something.
