### ISSUE TITLE
Timeout passed on stressed Windows hosts without option to increase it

### ISSUE THREAD

**Issue by okynos** [ansible/ansible#65001]
##### SUMMARY

Hello Ansible team,

I have detected a problem when I launch some of my stress scripts over a windows host with Ansible, it seems that the host is really stressed at some point and Ansible reach the timeout limit at this line https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/powershell/async_wrapper.ps1#L150

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

 `lib/ansible/executor/powershell/async_wrapper.ps1`

##### ANSIBLE VERSION

```paste below
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 10
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks', u'timer', u'mail']
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 300
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
```

##### OS / ENVIRONMENT

 Centos 7 as we show below, inside AWS instance.
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
Windows host:
![image](https://user-images.githubusercontent.com/10661307/69065966-d65ef500-0a20-11ea-9494-6a5d69f79627.png)

##### STEPS TO REPRODUCE

Prepare Windows host with python and other dependencies.
Launch Windows stress playbook

```yaml
- hosts: WindowsAgents
  gather_facts: False
  tasks:
  - name: Start process monitor Windows
    win_command: powershell.exe -
    args:
      stdin: "python monitor.py -t winagent -s {{ time }} -c {{ commit }} -v {{ version }} -n {{ inventory_hostname }}"
      chdir: "C:\\tmp"
    async: "{{ timeout }}"
    poll: 0

  - name: Start syscollector stress script Windows
    win_command: powershell.exe -
    args:
      stdin: "python syscollector.py -t {{ test_duration }} -p {{ sc_package }} -v {{ sc_package_version }}"
      chdir: "C:\\tmp"
    async: "{{ timeout }}"
    poll: 0
    when:
      - test_syscollector is defined
      - test_syscollector

  - name: Start active response stress script Windows
    win_command: powershell.exe -
    args:
      stdin: "./active_response.ps1"
      chdir: "C:\\tmp"
    async: "{{ timeout }}"
    poll: 0
    when:
      - test_activeresponse is defined
      - test_activeresponse

  - name: Start SCA stress script Windows
    win_command: powershell.exe -
    args:
      stdin: "python sca.py -t {{ test_duration }} -l {{ sca_limit }} -s {{ sca_sleep }}"
      chdir: "C:\\tmp\\sca_test"
    async: "{{ timeout }}"
    poll: 0
    when:
      - test_sca is defined
      - test_sca
```

##### EXPECTED RESULTS

I expect that all scripts run in a right way and no error thrown by timeout.

##### ACTUAL RESULTS

The async process timeout pass and throw error on terminal, I want to increase such value but it's hard coded.

```paste below
TASK [Start SCA stress script] *************************************************
task path: /******/launch_test.yml:132
Monday 18 November 2019  14:35:59 +0000 (0:00:00.035)       0:00:23.055 ******* 
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_command.ps1
Pipelining is enabled.
<***.***.***.***> ESTABLISH WINRM CONNECTION FOR USER: ****** on PORT 5986 TO ***.***.***.***
The full traceback is:
timeout while waiting for child process to connect to named pipe
At line:110 char:9
+         throw "timeout while waiting for child process to connect to  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (timeout while w...t to named pipe:String) [], RuntimeException
    + FullyQualifiedErrorId : timeout while waiting for child process to connect to named pipe
 
ScriptStackTrace:
at <ScriptBlock>, <No file>: line 110
at <ScriptBlock><End>, <No file>: line 137
at <ScriptBlock>, <No file>: line 7
  
fatal: [windows_node]: FAILED! => changed=false 
  msg: 'internal error: failed to run exec_wrapper action async_wrapper: timeout while waiting for child process to connect to named pipe'
  
PLAY RECAP *********************************************************************
windows_node : ok=4    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
  
Monday 18 November 2019  14:36:04 +0000 (0:00:17.690)       0:00:28.276 ******* 
 =============================================================================== 
Start logcollector stress script Windows ------------------------------- 17.69s
/******/launch_test.yml:292 
Start FIM stress script Windows ----------------------------------------- 3.74s
/******/launch_test.yml:280 
Start syscollector stress script Windows -------------------------------- 2.49s
/******/launch_test.yml:232 
Start SCA stress script Windows ----------------------------------------- 2.48s
/******/launch_test.yml:256 
Start process monitor Windows ------------------------------------------- 1.77s
/******/launch_test.yml:223 
Start vulnerability detector stress script Windows ---------------------- 0.02s
/******/launch_test.yml:268 
Start active response stress script Windows ----------------------------- 0.02s
/******/launch_test.yml:244 
Playbook run took 0 days, 0 hours, 0 minutes, 28 seconds
```

Thanks and regards!.
