### ISSUE TITLE
azure_rm_servicebusqueue: requires_session and requires_duplicate_detection are not set on service bus queue

### ISSUE THREAD

**Issue by damiandiaz76** [ansible/ansible#65005]
##### SUMMARY
azure_rm_servicebusqueue: requires_session and requires_duplicate_detection are not set on service bus queue

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Task: azure_rm_servicebusqueue

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/root/.ansible.cfg) = [u'profile_tasks']
```

##### OS / ENVIRONMENT
CentOS Linux release 7.7.1908 (Core)

##### STEPS TO REPRODUCE

```
- name: Create service bus requests queue
  azure_rm_servicebusqueue:
    resource_group: "{{ resource_group }}"
    name: requests
    namespace: "{{ servicebus_name }}"
    requires_session: yes
    requires_duplicate_detection: yes
```

##### EXPECTED RESULTS

Expected the created service bus queue to have "requiresSession" and "requiresDuplicateDetection" to be set to true.

##### ACTUAL RESULTS

"requiresSession" and "requiresDuplicateDetection" were false.  This is hard to see from the portal but the az cli will show it: az servicebus queue show.
