### ISSUE TITLE
AWS Application Load Balancer Fails with Multiple Host Headers

### ISSUE THREAD

**Issue by mjmayer** [ansible/ansible#65020]
##### SUMMARY
When using the `host-header` condition for a load balancer rule if there are multiple values for the host header ansible fails to apply the changes with broken json output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elbv2

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = None
  configured module search path = [u'/home/mjmayer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mjmayer/repos/ansible/lib/ansible
  executable location = /home/mjmayer/repos/ansible/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]

```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Mint 19.2 / Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
  - name: add a rule that uses the host header condition to the listener
    elb_application_lb:
      name: "{{ alb_name }}"
      subnets: "{{ alb_subnets }}"
      security_groups: "{{ sec_group.group_id }}"
      state: present
      purge_rules: no
      listeners:
        - Protocol: HTTP
          Port: 80
          DefaultActions:
            - Type: forward
              TargetGroupName: "{{ tg_name }}"
          Rules:
            - Conditions:
                - Field: host-header
                  Values:
                    - 'local.mydomain.com'
              Priority: '3'
              Actions:
                - TargetGroupName: "{{ tg_name }}"
                  Type: forward
      <<: *aws_connection_info
    register: alb

  - assert:
      that:
        - alb.changed
        - alb.listeners[0].rules|length == 4

  - name: test replacing the rule that uses the host header condition with multiple host header conditions
    elb_application_lb:
      name: "{{ alb_name }}"
      subnets: "{{ alb_subnets }}"
      security_groups: "{{ sec_group.group_id }}"
      purge_rules: no
      state: present
      listeners:
        - Protocol: HTTP
          Port: 80
          DefaultActions:
            - Type: forward
              TargetGroupName: "{{ tg_name }}"
          Rules:
            - Conditions:
                - Field: host-header
                  Values:
                    - 'local.mydomain.com'
                    - 'alternate.mydomain.com'
              Priority: '3'
              Actions:
                - TargetGroupName: "{{ tg_name }}"
                  Type: forward
      <<: *aws_connection_info
    register: alb
```
##### EXPECTED RESULTS
The second application of `elb_application_lb` should succeed and add the second host-header.

##### ACTUAL RESULTS
Ansible prints invalid json to the screen with the following error.
```paste below
Module invocation had junk after the JSON data
```
