### ISSUE TITLE
scaleway_user_data: multiline is broken, cloud-init doesn't work

### ISSUE THREAD

**Issue by jackivanov** [ansible/ansible#65036]
##### SUMMARY
There should be multiline in the cloud-init field, but instead either the module or API itself breaks it and sends the whole text as a string in double quotes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
scaleway_user_data

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
  - scaleway_user_data:
      server_id: "{{ scaleway_compute.msg.id }}"
      region: "{{ region }}"
      user_data:
        cloud-init: |
          #cloud-config
          # final_message
          # default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds
          # this message is written by cloud-final when the system is finished
          # its first boot
          final_message: "The system is finally up, after $UPTIME seconds"
```

1. Update the cloud-init and start the server
2. Cloud-init throws an error
`2019-11-18 19:27:31,692 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'b'"#cloud-config\\\\nfinal_me'...'`

##### EXPECTED RESULTS

```
root@test-cloudinit:~# curl --local-port 1-1023 http://169.254.42.42/user_data/cloud-init/ -w "\n"
#cloud-config
# final_message
# default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds
# this message is written by cloud-final when the system is finished
# its first boot
final_message: "The system is finally up, after $UPTIME seconds"
```

##### ACTUAL RESULTS

```
root@test-cloudinit:~# curl --local-port 1-1023 http://169.254.42.42/user_data/cloud-init/ -w "\n"
"#cloud-config\n# final_message\n# default: cloud-init boot finished at $TIMESTAMP. Up $UPTIME seconds\n# this message is written by cloud-final when the system is finished\n# its first boot\nfinal_message: \"The system is finally up, after $UPTIME seconds\"\n"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/scaleway/scaleway_user_data.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/scaleway/scaleway_user_data.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DenBeke @QuentinBrosse @abarbare @jerome-quere @kindermoumoute @remyleone @sieben
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jackivanov** [comment]
a workaround for now is to use the `uri` module:

```
- uri:
    url: "https://cp-{{ region }}.scaleway.com/servers/{{ server_id }}/user_data/cloud-init"
    method: PATCH
    body: "{{ lookup('template', 'cloud-config.yml') }}"
    status_code: 204
    headers:
      Content-Type: "text/plain"
      X-Auth-Token: "{{ token }}"
```
