### ISSUE TITLE
jinja2 version test

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#65046]
##### SUMMARY
Sometimes there's need to do something for specific major version, not lower, not greater. Current `version` filters don't allow that, you always need to combine e.g. `>=` and `<` tests to get this result

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core or jinja2

##### ADDITIONAL INFORMATION

```yaml
---
- hosts: localhost
  #remote_user: root
  connection: local
  vars:
    operators: ['==', '=', 'eq']
  tasks:
    - debug:
        msg: "version 4.4.4 is to 4.4: {{ '4.4.4' is version('4.4', item[0],
              item[1]) | bool }} when strict is {{ item[1] | bool }}"
      loop: "{{ operators | product(['true', 'false']) | list }}"
```

There should be some operator, that would resolve `4.4.<anything>` as True but `4.3[.anything]` or `4.5[.anything]` as False.

Current workaround would be:
```yaml
    when:
      - actual_version is version('4.4', '>=')
      - actual_version is version('4.5, '<')
```
but that requires more tests that can over time break the playbook (when the versions used as comparison are defined elsewhere).
