### ISSUE TITLE
Ansible Python Version is wrongly validated as pre_task

### ISSUE THREAD

**Issue by thanos1983** [ansible/ansible#65056]
##### SUMMARY

Pre_task on playbook seems to be first validating Python2 instead of Python3.

On my playbook I am trying to validate the Python version. On this OS (Linux) I have two versions of Python:

```
python --version
Python 2.7.5

python3 --version
Python 3.6.8
```

I set the pre_task to validate the Ansible version and also the Python version through setup module. Sample of code:

```yml
pre_tasks:
    - name: Validate we run with the correct Ansible version
      register: data
      assert:
        that:
          - ansible_version is defined
          - ansible_version.full is version('2.8.0.0', '>=')
          - ansible_python_version is defined
          - ansible_python_version is version('3.6.0', '>=')
        fail_msg: "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
      delegate_to: localhost
      run_once: true

    - name: Get facts
      register: facts
      setup:
        filter: ansible_python_version
      delegate_to: localhost
      run_once: true

    - name: Debug facts
      debug:
        var: facts

```

The pre_task is failing as the validation is failing. The weird part is that I have removed Ansible package from Python 2 and I have installed the Ansible package on Python 3.

If I change the validation of Python version then the pre_task proceeds and then prints ansible_python_version=3.6.8 (as expected).

But then why is failing to validate? I assume it first validates the Python version on the remote host and then on the local host.

Sample of output below in full verbose.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

setup Ansible module

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.1
  config file = /test/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
cat ansible.cfg
[defaults]
local_tmp = /tmp
remote_tmp = /tmp
host_key_checking = false
python_interpreter = /usr/bin/python3
# ansible_python_version = /usr/bin/python3
```

##### OS / ENVIRONMENT

```
# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

##### STEPS TO REPRODUCE

On my playbook I am trying to validate the Python version. On this OS (Linux) I have two versions of Python:

I set a pre_task to validate the Ansible version and also the Python version (sample below):

```yaml
    pre_tasks:
        - name: Validate we run with the correct Ansible version
          register: data
          assert:
            that:
              - ansible_version is defined
              - ansible_version.full is version('2.8.0.0', '>=')
              - ansible_python_version is defined
              - ansible_python_version is version('3.6.0', '>=')
            fail_msg: "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
          delegate_to: localhost
          run_once: true
    
        - name: Get facts
          register: facts
          setup:
            filter: ansible_python_version
          delegate_to: localhost
          run_once: true
    
        - name: Debug facts
          debug:
            var: facts
```

##### EXPECTED RESULTS

```
# ./build.sh
HOSTS TO DEPLOY TO inventories/development/hosts.yml environment is dev
ansible-playbook 2.9.1
  config file = /test/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /test/ansible.cfg as config file
host_list declined parsing /test/inventories/development/hosts.yml as it did not pass its verify_file() method
script declined parsing /test/inventories/development/hosts.yml as it did not pass its verify_file() method
Parsed /test/inventories/development/hosts.yml inventory source with yaml plugin

PLAYBOOK: build.yml *************************************************************************************************************************************************************************************************************************
1 plays in build.yml

PLAY [proxy_dev] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /test/build.yml:2
<hostname> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: user on PORT 22 TO hostname
<hostname> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1574164651.18929-243742289673627 `" && echo ansible-tmp-1574164651.18929-243742289673627="` echo /tmp/ansible-tmp-1574164651.18929-243742289673627 `" ) && sleep 0'
<hostname> Attempting python interpreter discovery
<hostname> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<hostname> Python interpreter discovery fallback (pipelining support required for extended interpreter discovery)
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<hostname> PUT /tmp/ansible-local-1600jy8n7jxf/tmpz9y37ggt TO /tmp/ansible-tmp-1574164651.18929-243742289673627/AnsiballZ_setup.py
<hostname> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1574164651.18929-243742289673627/ /tmp/ansible-tmp-1574164651.18929-243742289673627/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1574164651.18929-243742289673627/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1574164651.18929-243742289673627/ > /dev/null 2>&1 && sleep 0'
ok: [hostname]

TASK [Validate we run with the correct Ansible version] *************************************************************************************************************************************************************************************
task path: /test/build.yml:8
ok: [hostname -> localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Get facts] ****************************************************************************************************************************************************************************************************************************
task path: /test/build.yml:20
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1574164655.0734003-263935686695051 `" && echo ansible-tmp-1574164655.0734003-263935686695051="` echo /tmp/ansible-tmp-1574164655.0734003-263935686695051 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<localhost> PUT /tmp/ansible-local-1600jy8n7jxf/tmp404q3r7a TO /tmp/ansible-tmp-1574164655.0734003-263935686695051/AnsiballZ_setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1574164655.0734003-263935686695051/ /tmp/ansible-tmp-1574164655.0734003-263935686695051/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /tmp/ansible-tmp-1574164655.0734003-263935686695051/AnsiballZ_setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1574164655.0734003-263935686695051/ > /dev/null 2>&1 && sleep 0'
ok: [hostname -> localhost]

TASK [Debug facts] **************************************************************************************************************************************************************************************************************************
task path: /test/build.yml:27
ok: [hostname] => {
    "facts": {
        "ansible_facts": {
            "ansible_python_version": "3.6.8"
        },
        "changed": false,
        "failed": false
    }
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
hostname            : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

I can only get the expected results when I falsify my pre_task:

```yml
pre_tasks:
    - name: Validate we run with the correct Ansible version
      register: data
      assert:
        that:
          - ansible_version is defined
          - ansible_version.full is version('2.8.0.0', '>=')
          - ansible_python_version is defined
          - ansible_python_version is version('2.7.5', '>=')
        fail_msg: "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
      delegate_to: localhost
      run_once: true

    - name: Get facts
      register: facts
      setup:
        filter: ansible_python_version
      delegate_to: localhost
      run_once: true

    - name: Debug facts
      debug:
        var: facts
```

When I am not falsifying the pre_task it fails as it seems to be validating the Python 2 first (sample):

```yml
pre_tasks:
    - name: Validate we run with the correct Ansible version
      register: data
      assert:
        that:
          - ansible_version is defined
          - ansible_version.full is version('2.8.0.0', '>=')
          - ansible_python_version is defined
          - ansible_python_version is version('3.6.0', '>=')
        fail_msg: "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
      delegate_to: localhost
      run_once: true

    - name: Get facts
      register: facts
      setup:
        filter: ansible_python_version
      delegate_to: localhost
      run_once: true

    - name: Debug facts
      debug:
        var: facts
```

Output:

```
./build.sh
HOSTS TO DEPLOY TO inventories/development/hosts.yml environment is dev
ansible-playbook 2.9.1
  config file = /test/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /test/ansible.cfg as config file
host_list declined parsing /test/inventories/development/hosts.yml as it did not pass its verify_file() method
script declined parsing /test/inventories/development/hosts.yml as it did not pass its verify_file() method
Parsed /test/inventories/development/hosts.yml inventory source with yaml plugin

PLAYBOOK: build.yml *************************************************************************************************************************************************************************************************************************
1 plays in build.yml

PLAY [proxy_dev] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /test/build.yml:2
<hostname> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: user on PORT 22 TO hostname
<hostname> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1574165109.9264905-149406673725731 `" && echo ansible-tmp-1574165109.9264905-149406673725731="` echo /tmp/ansible-tmp-1574165109.9264905-149406673725731 `" ) && sleep 0'
<hostname> Attempting python interpreter discovery
<hostname> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<hostname> Python interpreter discovery fallback (pipelining support required for extended interpreter discovery)
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<hostname> PUT /tmp/ansible-local-1657crht_gzg/tmpucgxf8ap TO /tmp/ansible-tmp-1574165109.9264905-149406673725731/AnsiballZ_setup.py
<hostname> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1574165109.9264905-149406673725731/ /tmp/ansible-tmp-1574165109.9264905-149406673725731/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1574165109.9264905-149406673725731/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1574165109.9264905-149406673725731/ > /dev/null 2>&1 && sleep 0'
ok: [hostname]

TASK [Validate we run with the correct Ansible version] *************************************************************************************************************************************************************************************
task path: /test/build.yml:8
fatal: [hostname -> localhost]: FAILED! => {
    "assertion": "ansible_python_version is version('3.6.0', '>=')",
    "changed": false,
    "evaluated_to": false,
    "msg": "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
hostname            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

##### ACTUAL RESULTS

```
./build.sh
HOSTS TO DEPLOY TO inventories/development/hosts.yml environment is dev
ansible-playbook 2.9.1
  config file = /test/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /test/ansible.cfg as config file
host_list declined parsing /test/inventories/development/hosts.yml as it did not pass its verify_file() method
script declined parsing /test/inventories/development/hosts.yml as it did not pass its verify_file() method
Parsed /test/inventories/development/hosts.yml inventory source with yaml plugin

PLAYBOOK: build.yml *************************************************************************************************************************************************************************************************************************
1 plays in build.yml

PLAY [proxy_dev] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /test/build.yml:2
<hostname> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: user on PORT 22 TO hostname
<hostname> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1574162903.658131-215487178541419 `" && echo ansible-tmp-1574162903.658131-215487178541419="` echo /tmp/ansible-tmp-1574162903.658131-215487178541419 `" ) && sleep 0'
<hostname> Attempting python interpreter discovery
<hostname> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<hostname> Python interpreter discovery fallback (pipelining support required for extended interpreter discovery)
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<hostname> PUT /tmp/ansible-local-1555mk884cwv/tmpvo3828hr TO /tmp/ansible-tmp-1574162903.658131-215487178541419/AnsiballZ_setup.py
<hostname> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1574162903.658131-215487178541419/ /tmp/ansible-tmp-1574162903.658131-215487178541419/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1574162903.658131-215487178541419/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1574162903.658131-215487178541419/ > /dev/null 2>&1 && sleep 0'
ok: [hostname]

TASK [Validate we run with the correct Ansible version] *************************************************************************************************************************************************************************************
task path: /test/build.yml:8
ok: [hostname] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Get facts] ****************************************************************************************************************************************************************************************************************************
task path: /test/build.yml:19
<hostname> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: user on PORT 22 TO hostname
<hostname> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1574162906.4185665-247457345676988 `" && echo ansible-tmp-1574162906.4185665-247457345676988="` echo /tmp/ansible-tmp-1574162906.4185665-247457345676988 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<hostname> PUT /tmp/ansible-local-1555mk884cwv/tmpdd8rjg0u TO /tmp/ansible-tmp-1574162906.4185665-247457345676988/AnsiballZ_setup.py
<hostname> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1574162906.4185665-247457345676988/ /tmp/ansible-tmp-1574162906.4185665-247457345676988/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1574162906.4185665-247457345676988/AnsiballZ_setup.py && sleep 0'
<hostname> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1574162906.4185665-247457345676988/ > /dev/null 2>&1 && sleep 0'
ok: [hostname]

TASK [Debug facts] **************************************************************************************************************************************************************************************************************************
task path: /test/build.yml:25
ok: [hostname] => {
    "facts": {
        "ansible_facts": {
            "ansible_python_version": "2.7.5"
        },
        "changed": false,
        "failed": false
    }
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
hostname            : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

<!--- Paste verbatim command output between quotes -->

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/network/eos/providers/module.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/eos/providers/module.py)
* [`lib/ansible/module_utils/network/frr/providers/module.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/frr/providers/module.py)
* [`lib/ansible/module_utils/network/ios/providers/module.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/ios/providers/module.py)
* [`lib/ansible/module_utils/network/iosxr/providers/module.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/iosxr/providers/module.py)
* [`lib/ansible/modules/system/setup.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/setup.py)
* [`lib/ansible/modules/windows/setup.ps1`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/setup.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @NilashishC @Qalthos @ShachafGoldstein @danielmellado @ganeshrn @if-meaton @jborean93 @jhawkesworth @justjais @nitzmahone @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
There seems to be a few problems here.

1. You cannot define the python interpreter to use in an ansible.cfg file, you can only defined the discovery mechanism there, or you can define the `ansible_python_interpreter` in inventory or another var type.
2. The `setup` module is running against the remote host using `/usr/bin/python` which with a CentOS7 remote host, will be Python2.

You would need to move your `setup` with `delegate_to: localhost` above your assert, and you would need to assert using `hostvars['localhost']['ansible_python_version']`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by thanos1983** [comment]
@sivel It worked perfectly.

Sample of code (in case someone else might need it):

```yml
pre_tasks:
    - name: Validate we run with the correct Ansible version
      delegate_to: hostvars['localhost']['ansible_python_version']
      assert:
        that:
          - ansible_version is defined
          - ansible_version.full is version('2.8.0.0', '>=')
          - ansible_python_version is defined
          - ansible_python_version is version('3.6.0', '>=')
        fail_msg: "'Python' version must be 3.6.0 and Ansible 2.8.0 minimal version."
      run_once: True
```
