### ISSUE TITLE
azure_rm_manageddisk module allow LUN argument

### ISSUE THREAD

**Issue by Sneedes** [ansible/ansible#65072]
##### SUMMARY
 Desire the ability to use a user-provided LUN number rather than the next-sequential LUN number when using azure_rm_manageddisk module to attach a data disk to a VM.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_manageddisk 

##### ADDITIONAL INFORMATION

Utilizing the azure_rm_manageddisk module.  Desire the ability to use a user-provided LUN number rather than the next-sequential LUN number.  Using a provisioning play that creates additional Azure data disks for a VM and applies various LVM pv/vg/lv configuration on the disks.  Would prefer to rely on having a known/set LUN number than playing the guessing game on sequential lun numbering and/or disk device naming.

```
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/azure/lib/python2.7/site-packages/ansible
  executable location = /var/lib/awx/venv/azure/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

```yaml

my_vm_lvm_data_disks:
  - disk_size_gb: 256
    name: vg_sap01
    storage_account_type: Premium_LRS
    lvm_vg_name: vg_sap
    attach_caching: ''
    lun: 0
  - disk_size_gb: 512
    name: vg_oracle01
    storage_account_type: Premium_LRS
    lvm_vg_name: vg_oracle
    attach_caching: read_only
    lun: 1

- name: Additional Azure data disks are created (not attached yet)
  azure_rm_manageddisk :
    # prepend the managed disk name the the lowercase vm-name
    name: "{{ my_vm_name }}-{{ item.name }}"
    resource_group: "{{ my_vm_rg }}"
    disk_size_gb: "{{ item.disk_size_gb }}"
    attach_caching: "{{ item.attach_caching }}"
    storage_account_type: "{{ item.storage_account_type }}"
    #managed_by: "{{ my_vm_name }}"
    #lun: "{{ item.lun }}"
      # The LUN is what I'm missing as an argument.  
      # Currently would be just max+1
      # Makes it hard for me later to know what AZ Data Disk is for what in the OS
      # /dev/disk/azure/scsi1/lun0
      # /dev/disk/azure/scsi1/lun1
      # The Azure managed disks to LUN mapping is clear to me
      # Later tasks use LVM modules to create physical volumes by /dev/disk/azure/scsi1/lun_N_
  loop: "{{ my_vm_lvm_data_disks }}"


```
