### ISSUE TITLE
Named blocks and roles should appear in play output like named plays and roles alone do

### ISSUE THREAD

**Issue by r4j4h** [ansible/ansible#65099]
This feature was roughly discussed in https://github.com/ansible/ansible/issues/33835 but not clearly before the issue was closed.

##### SUMMARY

In #33835, user bcoca finishes the thread with:

> plays and roles also have 'name' but you cannot use them in --start-at-task, that only works for 'tasks'

It is completely understandable that only tasks can be used with --start-at-task. However, plays and roles do both appear in the output to varying extents. Because of this, I can't think of a reason for them to be so transparent in the output, especially with the way the docs suggest to use them with names.

Currently they only offer an affordance when looking in the play/role/task code.

By not appearing in the output they can sometimes lead to confusing output if not used carefully. This can become easy to cause in larger playbooks.

I demonstrate that we currently allow naming Plays and we currently show those names as a special outputted task with the word PLAY instead of TASK.

I think that there is a clean and simple way to insert block names into outputted task names: we already insert the role name if there is one. Similarly, if there is no block name we can just leave it off. It also still makes sense for nesting.

While researching this I also learned that roles always show their filename, but could also just as easily show their name if there is one. In this case I would prefer that we still show both, so I recommend wrapping the filename in parens `()`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Playbook execution

##### ADDITIONAL INFORMATION
The feature would allow adding a name to a role or a block to show up in the output, similar to how plays currently do.

---

Input A:
```yaml
- name: named play
  roles:
    - name: named role
      role: web
```
Current Output from A:
```
    PLAY [named play] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [some-hosts]
    
    TASK [web : Named Task inside Role] ***************************
```

Suggested role logic: If no name, do same as today. If name, wrap role filename in parenthesis and prefix the name. Using the previous example again:

Suggested Output from A:
```
    PLAY [named play] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [some-hosts]
    
    TASK [named role ( web ) : Named Task inside Role] ***************************
```

Now for named blocks, separate example for clarity.

Input B:

```yaml
- name: Install on CentOS
  block:
  - name: Named Task inside Role
    ... snipped task config for clarity ...
  ... snipped remaining tasks for clarity ...
  when: ansible_distribution == 'CentOS'

- name: Install on Debian/Ubuntu
  block:
  - name: Named Task inside Role
    ... snipped task config for clarity ...
  ... snipped remaining tasks for clarity ...
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
```

Current Output from B (assuming it is inside the web role, so that I demonstrate how the block would look next to it):

```
    TASK [Gathering Facts] *********************************************************
    ok: [some-centos-host]
    ok: [some-debian-host]
    
    TASK [web : Named Task inside Role] ***************************
    ok: [some-centos-host]
    skipping [some-debian-host]
    
    TASK [web : Named Task inside Role] ***************************
    skipping: [some-centos-host]
    ok: [some-debian-host]
```

Suggested Output from B:

```
    TASK [Gathering Facts] *********************************************************
    ok: [some-centos-host]
    ok: [some-debian-host]
    
    TASK [web : Install on CentOS : Named Task inside Role] ***************************
    ok: [some-centos-host]
    skipping [some-debian-host]
    
    TASK [web : Install on Debian/Ubuntu : Named Task inside Role] ***************************
    skipping: [some-centos-host]
    ok: [some-debian-host]
```

Known workarounds:

1. No known effective, non-intrusive work-around for role names not appearing.

    Possibly acceptable solutions include:
    - renaming the role
    - symlinking or copying a folder with the new name to the role (have not tried this)
    - pulling the role through ansible-galaxy and renaming it (slightly more reliable way of the previous)
    - and inserting a "dummy" task before the role (easiest and least intrusive but can only prints before and after, not with each inside task).

2. Moving block into separate file and using include_tasks with a name will effectively add a TASK representing the include.
    
   ```yaml
    - name: Install on CentOS
      include_tasks: centos.yml
      when: ansible_distribution == 'CentOS'
    
    - name: Install on Debian/Ubuntu
      include_tasks: ubuntu-debian.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ```
    
    which should result in:
    
    ```
    TASK [Gathering Facts] *********************************************************
    ok: [some-centos-host]
    ok: [some-debian-host]

    TASK [web : Install on CentOS] **********************************************
    skipping: [some-debian-host]
    included: /path/tasks/centos.yml for some-centos-host
    
    TASK [web : Named Task inside Roled] ***********************************
    ok: [some-centos-host]

    TASK [web : Install on Debian/Ubuntu] **********************************************
    included: /path/tasks/ubuntu-debian.yml for some-debian-host
    
    TASK [web : Named Task inside Roled] ***********************************
    ok: [some-debian-host]
    ```
