### ISSUE TITLE
Add configuration to buildah connection plugin to support "buildah unshare"

### ISSUE THREAD

**Issue by dtenbrinck** [ansible/ansible#65105]
##### SUMMARY

It would be nice to have a functionality for the buildah connection plugin that allows to change the user namespace via `buildah unshare` when interacting with containers in a rootless environment. This behaviour of the buildah connection plugin could be configured manually by the user or realized programmatically without any user interaction.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

buildah connection plugin

##### ADDITIONAL INFORMATION

Currently, in a rootless environment the only way to communicate with containers using the buildah connection plugin is to run the whole Ansible playbook in a user namespace, e.g., by prepending `buildah unshare` to the ansible-playbook command (see #50583). However, this change into user namespace also changes the ansible_user variable during the play (if not configured manually) and hence can mess up later tasks in the same playbook, e.g., connecting to other hosts via ssh. The only operation that needs a change into a different user namespace is the "buildah mount" command as described in [an article by Daniel Walsh](https://opensource.com/article/19/3/tips-tricks-rootless-buildah). Thus, it would be more elegant to restrict the user namespace change to the buildah relevant tasks by enhancing the buildah connection plugin.
After a short discussion with the maintainer of this plugin, @TomasTomecek, he agreed that this might be a good feature enhancement. This might also help for the issues #50583, #51529 and #63316.

```yaml
## content of mini_example.yml
# First play: Download python image and build a container using buildah
- hosts: localhost 
  connection: local

  tasks:
    - debug:
        msg: "Current ansible_user is: {{ ansible_user }}"

    - name: Pull current python:alpine image
      command: buildah pull python:alpine

    - name: Create a container
      command: buildah from --name test_container python:alpine

    - name: Add the newly created container to the inventory
      add_host:
        name: test_container 
        hostname: test_container 
        groups: temporary_containers
        ansible_python_interpreter: /usr/local/bin/python
        ansible_os_family: "Alpine"
        remote_tmp: "/tmp"

# Second play: Copy a file into the container and show it's content
- hosts: temporary_containers
  connection: buildah

  tasks:
    - name: Copy file to container 
      copy:
        src: testfile.txt
        dest: /tmp/testfile.txt
        mode: '0777'
  
    - name: Check file content
      command: cat /tmp/testfile.txt
      register: output_cat

    - debug: 
        msg: "{{ output_cat.stdout }}"
```

Run the above playbook as a non-root user on your machine with buildah installed and configured for rootless use, e.g., by following [Daniel Walsh's related article on rootless podman](https://opensource.com/article/19/2/how-does-rootless-podman-work). 

First, try 
`ansible-playbook -i ./hosts ./mini_example.yml`
which should fail and compare the output to
`buildah unshare ansible-playbook -i ./hosts ./mini_example.yml`
which succeeds but changes the ansible_user variable globally.

Don't forget to remove the container after each run via:
`buildah rm test_container`
