### ISSUE TITLE
gitlab_project: fail on 2nd play

### ISSUE THREAD

**Issue by Lunik** [ansible/ansible#65113]
##### SUMMARY

`gitlab_project` fail on idempotency 2nd run when project is in a group

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gitlab_project

##### ANSIBLE VERSION

```paste below
ansible 2.9.1 
  config file = None
  configured module search path = ['/home/lunik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lunik/tmp/venv/lib/python3.6/site-packages/ansible
  executable location = /home/lunik/tmp/venv/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Run this task 2 times

```yaml
    - name: Create GitLab Project in group Ansible
      gitlab_project:
        api_url: "{{ gitlab_url }}"
        api_token: "{{ token }}"
        validate_certs: no 
        name: my_first_project
        group: "my_first_group"
        issues_enabled: False
        wiki_enabled: True
        snippets_enabled: True
        state: present
```

##### EXPECTED RESULTS

The module should detect that the project is already present, update it if needed or do nothing

##### ACTUAL RESULTS

It fail

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create project: 400: {'name': ['has already been taken'], 'path': ['has already been taken'], 'limit_reached': []} "}
```
