### ISSUE TITLE
Issue with accessing variables across roles within same playbook

### ISSUE THREAD

**Issue by brstallings-clgx** [ansible/ansible#65135]
##### SUMMARY

I'm trying to configure Windows servers and take those server names across to another role in the same playbook to add them as nodes in our F5 appliances.  We are using Google Cloud and dynamic inventory.
I'm using 1 playbook to call 2 different roles.  The first role targets a dynamic inventory group named "_sbx_web_test."  The second role targets our F5 dynamic inventory group named "_f5"
I'm using the --extra-vars parameter to target a dynamic group or a specific host.
Everything runs great until the point that I try to set_facts to preserve the variables needed in the F5 config role.
It works fine if I target a specific host in my extra-vars parameter.  The problem occurs when I specify to target the dynamic group with multiple machines.  As it adds the values to the variables, it's only using the variables from one of the hosts and not multiple hosts.  There could be anywhere from 1 to 10 hosts in the dynamic group.  
The caveat to this is that it only needs to target the hosts that were configured within the 1st role.
Say there were 2 hosts already configured previously and I'm deploying 3 more host to this group.  When role 1 runs and configures the 3 new nodes, I need to pass only those 3 nodes to the 2nd role to be added to the F5 and not all 5 nodes.  This will be useful when we repave/destroy nodes so that I don't target the entire dynamic group at once and remove all nodes in that group from the F5 at the same time. It will only need to target the hosts affected in the 1st role.
I'm creating a "dummy host" in order to pass the variables across to the 2nd role.  I understand that this is only 1 host.  I don't know how to specify the number of servers that were configured in the 1st role and tell it to create that number of dummy hosts.  
Heck maybe I'm so far in the weeds with this configuration that I'm overlooking something very easy to resolve this issue.
If I'm doing something completely wrong. Please let me know. Each day learning Ansible is like drinking through a fire hose.

##### ISSUE TYPE
- I don't think this is a bug. It's something I'm not sure how to accomplish.

##### COMPONENT NAME

set_fact, add_host, bigip_node
##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.5
  config file = /home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/ansible.cfg) = [u'/home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/inventory.gcp.yml']
root@fnccsappansible-jumpbox:/home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx#
```

##### OS / ENVIRONMENT

Windows 2016 Standard.  F5 Network Load Balancer. Google Cloud

##### STEPS TO REPRODUCE

I'm running the following command:
ansible-playbook --extra-vars 'hosts=_sbx_web_test' sbx/pb_sbx_web_test_install.yml -v

```yaml
1. Playbook
---
# This playbook calls roles to configure sbx_web_test servers
- name: sbx_web_test playbook configure web server
  hosts: "{{ hosts }}"
  gather_facts: no
  become_method: runas

  roles:
  - web/test/test-install
 
# This playbook calls roles to configure the F5 nodes with sbx_web_test servers.
- name: Start F5 Configuration
  hosts: _f5
  connection: local
  gather_facts: no

  roles:
  - f5/f5-add-node

2. web-install task - main.yml
---
# Check inventory information
- name: Check Inventory Information
  debug: 
    msg: "{{hostvars[inventory_hostname].inventory_hostname}}"

# Set Fact to have variables survive across roles
- name: Set variables to survive across plays/roles
  set_fact:
    gcp_inventory_group: "{{hostvars[inventory_hostname].gcp_inventory_group}}"
    inventory_hostname_play: "{{hostvars[inventory_hostname].inventory_hostname}}"
      
# Create dummy host in order to use in other roles in this playbook to carry original variables from first play.
# This host will only live in memory and is gone after this playbook is finished.
- name: Create Dummy host with new variable
  add_host:
    name: "dummy_host"
    gcp_inventory_group: "{{gcp_inventory_group}}"
    inventory_hostname_play: "{{inventory_hostname_play}}"

3. F5 Configuration Task - main.yml
---
# Set_Facts for variables from previous play.
- name: Set_Facts for variables
  set_fact: 
    gcp_inventory_group: "{{hostvars['dummy_host'].gcp_inventory_group}}"
    inventory_hostname_play: "{{hostvars['dummy_host'].inventory_hostname_play}}"

# Validate Variables were set correctly.
- name: Validate Final Variables from Set_Facts
  debug: 
    msg: "{{gcp_inventory_group}} is the gcp_inventory_group, and {{inventory_hostname_play}} is the inventory_hostname."

# Add Node
- name: CREATE NODES
  bigip_node:
    provider: "{{provider}}"
    partition: "{{hostvars[item].f5_partition}}"
    host: "{{hostvars[item].networkInterfaces[0].networkIP}}"
    name: "{{hostvars[item].inventory_hostname}}"
    state: present
  loop: "{{hostvars['dummy_host'].inventory_hostname_play}}"
```
1. Playbook: 
[pb_sbx_web_test_install.txt](https://github.com/ansible/ansible/files/3872762/pb_sbx_web_test_install.txt)
2. web-install main.yml
[main.txt](https://github.com/ansible/ansible/files/3872765/main.txt)
3. F5-add-node main.yml
[main.txt](https://github.com/ansible/ansible/files/3872767/main.txt)
4. Screenshot of output when running the playbook
![2019 11 20_Ansible_Variables_Across_Roles_Screenshot](https://user-images.githubusercontent.com/49203171/69303813-fbe82c00-0be3-11ea-97ef-185437de63d5.JPG)

##### EXPECTED RESULTS

I would expect for the variables to be set across the roles per host that was configured in role1.
It would then use those variables to create the nodes in the F5.

##### ACTUAL RESULTS

When the group is enumerated using debug: msg: "{{hostvars[inventory_hostname].inventory_hostname}}", it sees the 2 nodes in the group as expected.
When I create the dummy node, it only sets variables for 1 of the 2 servers in the group.  I know using the add host feature is only creating 1 host, which is why it's not adding variables for both hosts.  I just don't know how to do this.  

```paste below
time ansible-playbook --extra-vars 'hosts=_sbx_web_test' sbx/pb_sbx_web_test_install.yml -vvvv
ansible-playbook 2.8.5
  config file = /home/xxxxxxxxxxxxx/xxxxxxxxxxxxxx/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
Using /home/xxxxxxxxxxx/xxxxxxxxxxxxxxx/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/xxxxxxxxxxxxxx/xxxxxxxxxxxxx/inventory.gcp.yml as it did not pass it's verify_file() method
script declined parsing /home/xxxxxxxxxxxxxx/xxxxxxxxxxxx/inventory.gcp.yml as it did not pass it's verify_file() method
Parsed /home/xxxxxxxxxxxxx/xxxxxxxxxxxxxx/inventory.gcp.yml inventory source with auto plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: pb_sbx_web_test_install.yml ***********************************************************************************************************************************************
Positional arguments: sbx/pb_sbx_web_test_install.yml
become_method: sudo
inventory: (u'/home/xxxxxxxxxxxx/xxxxxxxxxxxxxx/inventory.gcp.yml',)
forks: 5
tags: (u'all',)
extra_vars: (u'hosts=_sbx_web_test',)
verbosity: 4
connection: smart
timeout: 10
2 plays in sbx/pb_sbx_web_test_install.yml
 [WARNING]: Found variable using reserved name: hosts


PLAY [sbx_web_test playbook configure web server] ***********************************************************************************************************************************
META: ran handlers

TASK [web/test/test-install : Check Inventory Information] **************************************************************************************************************************
task path: /home/xxxxxxxxxxxx/xxxxxxxxxxxxx/sbx/roles/web/test/test-install/tasks/main.yml:4
ok: [fnc107test01] => {
    "msg": "fnc107test01"
}
ok: [fnc108test01] => {
    "msg": "fnc108test01"
}

TASK [web/test/test-install : Set variables to survive across plays/roles] **********************************************************************************************************
task path: /home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/sbx/roles/web/test/test-install/tasks/main.yml:9
ok: [fnc108test01] => {
    "ansible_facts": {
        "gcp_inventory_group": "_sbx_web_test",
        "inventory_hostname_play": "fnc108test01"
    },
    "changed": false
}
ok: [fnc107test01] => {
    "ansible_facts": {
        "gcp_inventory_group": "_sbx_web_test",
        "inventory_hostname_play": "fnc107test01"
    },
    "changed": false
}

TASK [web/test/test-install : Create Dummy host with new variable] ******************************************************************************************************************
task path: /home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/sbx/roles/web/test/test-install/tasks/main.yml:16
creating host via 'add_host': hostname=dummy_host
changed: [fnc107test01] => {
    "add_host": {
        "groups": [],
        "host_name": "dummy_host",
        "host_vars": {
            "gcp_inventory_group": "_sbx_web_test",
            "inventory_hostname_play": "fnc107test01"
        }
    },
    "changed": true
}
META: ran handlers
META: ran handlers

PLAY [Start F5 Configuration] *******************************************************************************************************************************************************
META: ran handlers

TASK [f5/f5-add-node : Set_Facts for variables] *************************************************************************************************************************************
task path: /home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxx/sbx/roles/f5/f5-add-node/tasks/main.yml:3
ok: [fncuc1gbbigip01-q19v] => {
    "ansible_facts": {
        "gcp_inventory_group": "_sbx_web_test",
        "inventory_hostname_play": "fnc107test01"
    },
    "changed": false
}
ok: [fncuc1gbbigip02-f61l] => {
    "ansible_facts": {
        "gcp_inventory_group": "_sbx_web_test",
        "inventory_hostname_play": "fnc107test01"
    },
    "changed": false
}

TASK [f5/f5-add-node : Validate Final Variables from Set_Facts] *********************************************************************************************************************
task path: /home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/sbx/roles/f5/f5-add-node/tasks/main.yml:9
ok: [fncuc1gbbigip01-q19v] => {
    "msg": "_sbx_web_test is the gcp_inventory_group, and fnc107test01 is the inventory_hostname."
}
ok: [fncuc1gbbigip02-f61l] => {
    "msg": "_sbx_web_test is the gcp_inventory_group, and fnc107test01 is the inventory_hostname."
}

TASK [f5/f5-add-node : CREATE NODES] ************************************************************************************************************************************************
task path: /home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx/sbx/roles/f5/f5-add-node/tasks/main.yml:14
fatal: [fncuc1gbbigip01-q19v]: FAILED! => {
    "msg": "Invalid data passed to 'loop', it requires a list, got this instead: fnc107test01. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."
}
fatal: [fncuc1gbbigip02-f61l]: FAILED! => {
    "msg": "Invalid data passed to 'loop', it requires a list, got this instead: fnc107test01. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."
}

PLAY RECAP **************************************************************************************************************************************************************************
fnc107test01               : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
fnc108test01               : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
fncuc1gbbigip01-q19v       : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
fncuc1gbbigip02-f61l       : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


real    0m4.055s
user    0m2.241s
sys     0m0.391s
root@fnccsappansible-jumpbox:/home/xxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx#

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/inventory/add_host.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/inventory/add_host.py)
* [`lib/ansible/modules/network/f5/bigip_node.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_node.py)
* [`lib/ansible/modules/utilities/logic/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/set_fact.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @caphrim007 @dagwieers @wojtek0806
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@brstallings, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Your issue is not with accessing a variable, but that you are trying to loop over a value which is not a list.

The error message indicates this:

```
Invalid data passed to 'loop', it requires a list, got this instead: fnc107test01
```

You likely don't want to use `loop` in this case, you likely just want to access the variable you want to use.

However you can just make it a list, and get your desired outcome:

```
- name: Create Dummy host with new variable
  add_host:
    name: "dummy_host"
    gcp_inventory_group: "{{gcp_inventory_group}}"
    inventory_hostname_play:
      - "{{inventory_hostname_play}}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
