### ISSUE TITLE
Templated keyed expressions no longer evaluate as of 2.9.0

### ISSUE THREAD

**Issue by msaladna** [ansible/ansible#65136]
##### SUMMARY

Prior to 2.9.0 and still available as of 2.8.7, a templated key will evaluate correctly. Beginning in 2.9.0, a templated key is evaluated literally with no discernible workaround that I'm aware of to dynamically evaluate these keys.

This is still broken in the devel branch.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`lib/ansible/plugins/strategy/__init__.py`

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

*N/A*

##### OS / ENVIRONMENT

CentOS 7.7.1908

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    subexpr: myvar
  tasks:
    - set_fact:
        dict:
          myvar_a: "A visible"
          myvar_b: "{{ subexpr }} visible"
          "{{ subexpr }}_c": "C visible"
    - debug: msg="{{ item.key }} {{ item.value }}"
      with_dict: "{{ dict }}"
```

##### EXPECTED RESULTS

```
TASK [set_fact] **********************************************************************************************************************************************************************************************************************************************************************************************
task path: /usr/local/apnscp/resources/playbooks/testing.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "dict": {
            "myvar_a": "A visible", 
            "myvar_b": "myvar visible", 
            "{{ subexpr }}_c": "C visible"
        }
    }, 
    "changed": false
}

TASK [debug] *************************************************************************************************************************************************************************************************************************************************************************************************
task path: /usr/local/apnscp/resources/playbooks/testing.yml:12
ok: [localhost] => (item={'value': u'C visible', 'key': u'myvar_c'}) => {
    "msg": "myvar_c C visible"
}
ok: [localhost] => (item={'value': u'myvar visible', 'key': u'myvar_b'}) => {
    "msg": "myvar_b myvar visible"
}
ok: [localhost] => (item={'value': u'A visible', 'key': u'myvar_a'}) => {
    "msg": "myvar_a A visible"
}
```

##### ACTUAL RESULTS

```
TASK [set_fact] **********************************************************************************************************************************************************************************************************************************************************************************************
task path: /usr/local/apnscp/resources/playbooks/testing.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "dict": {
            "myvar_a": "A visible", 
            "myvar_b": "myvar visible", 
            "{{ subexpr }}_c": "C visible"
        }
    }, 
    "changed": false
}

TASK [debug] *************************************************************************************************************************************************************************************************************************************************************************************************
task path: /usr/local/apnscp/resources/playbooks/testing.yml:12
ok: [localhost] => (item={'value': u'C visible', 'key': u'{{ subexpr }}_c'}) => {
    "msg": "{{ subexpr }}_c C visible"
}
ok: [localhost] => (item={'value': u'myvar visible', 'key': u'myvar_b'}) => {
    "msg": "myvar_b myvar visible"
}
ok: [localhost] => (item={'value': u'A visible', 'key': u'myvar_a'}) => {
    "msg": "myvar_a A visible"
}
```
*{{ subexpr_c }}* should be evaluated as *myvar_c*

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/strategy/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/__init__.py)
* [`lib/ansible/plugins/strategy/debug.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/debug.py)
* [`lib/ansible/plugins/strategy/free.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/free.py)
* [`lib/ansible/plugins/strategy/host_pinned.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/host_pinned.py)
* [`lib/ansible/plugins/strategy/linear.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/strategy/linear.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is expected. In order to template the keys, use `loop` instead of `with_dict`, like so:
```yaml
- hosts: localhost
  gather_facts: no
  vars:
    subexpr: myvar
  tasks:
    - set_fact:
        dict:
          myvar_a: "A visible"
          myvar_b: "{{ subexpr }} visible"
          "{{ subexpr }}_c": "C visible"
    - debug:
        msg: "{{ item.key }} - {{ item.value }}"
      loop: "{{ dict|dict2items }}"
```

This has been documented in the porting guide where you can read more about this change in behavior (a bugfix actually): https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html#loops


If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by msaladna** [comment]
Your example worked fine, but didn't work with my vars. After some additional work, usage of the block chomping indicator suppresses evaluation of the block if an undefined variable is encountered, despite having a default.

All things being equal and just changing the `dict` var, the following version works OK:

```yaml
dict:
  "a{{ subexpr }}-def": "C visible"
  "myvar-b": >-
    {{ subexpr | default(subexpr) }}
```

as does this version:
```yaml
dict:
  "a{{ subexpr }}-def": "C visible"
  "myvar-b": >
    {{ subexpr_undef | default(subexpr) }}
```

and this version:
```yaml
dict:
  "a{{ subexpr }}-def": "C visible"
  "myvar-b": >-
    {{ subexpr | default(subexpr) }}
```

Using the block chomping indicator (`-`) plus an undefined var seems to shutdown all evaluation in the templated expression. 

This no longer works as of 2.9.0:
```yaml
dict:
  "a{{ subexpr }}-def": "C visible"
  "myvar-b": >-
    {{ subexpr_undef | default(subexpr) }}
```
