### ISSUE TITLE
gitlab_runner creates a new runner each time and does not update existing ones

### ISSUE THREAD

**Issue by DeLoWaN** [ansible/ansible#65144]
##### SUMMARY
gitlab_runner creates a new runner each time and does not update existing ones

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gitlab_runner

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = [u'/home/damien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

* Debian buster
* python 2.7.16
* python-gitlab 1.12.1
* Gitlab 12.4.2

##### STEPS TO REPRODUCE
```yaml
- name: "Register runner"
  gitlab_runner:
    api_url: "{{ gitlab_url }}"
    api_token: "{{ gitlab_token }}"
    registration_token: "{{ gitlab_runner_registration_token }}"
    description: "{{ gitlab_runner_manager.description }}"
    state: present
    active: True
    tag_list: ['api_functional_tests']
    run_untagged: False
    locked: False
  register: runner
```

Of course the description var is always the same. I also tested with a static value.

##### EXPECTED RESULTS
The runner should be updated as long as I keep the same description. [Documentation](https://docs.ansible.com/ansible/latest/modules/gitlab_runner_module.html) states: "Runners need to have unique descriptions."

##### ACTUAL RESULTS
Each time a new runner is created.

```
Thursday 21 November 2019  11:21:37 +0100 (0:00:01.259)       0:00:06.673 ***** 
ok: [gitlab_runner_manager_dev_iwd] => {
    "runner": {
        "changed": true, 
        "failed": false, 
        "msg": "Successfully created or updated the runner Runner Manager", 
        "runner": {
            "id": 69, 
            "token": "i_nGC6izqFDBnRDGKEXE"
        }
    }
}
```

```paste below
TASK [gitlab-runner : debug] 
Thursday 21 November 2019  11:22:15 +0100 (0:00:01.226)       0:00:06.527 *****
ok: [gitlab_runner_manager_dev_iwd] => {
    "runner": {
        "changed": true, 
        "failed": false, 
        "msg": "Successfully created or updated the runner Runner Manager", 
        "runner": {
            "id": 70, 
            "token": "sTDg-RYjiKqrJ4N6TrEZ"
        }
    }
}
```
