### ISSUE TITLE
vmware_guest: Cannot create VM on standalone ESXi

### ISSUE THREAD

**Issue by wioch** [ansible/ansible#65143]
##### SUMMARY
I'm trying to create a single VM on standalone ESXi  (no vCenter here) with vmware_guest module. Task execution ends with error. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
PyVmomi 6.7.3
CentOS Linux release 7.7.1908 (Core)
VMware ESXi 6.7.0 Update 2 (Build 13981272)

##### STEPS TO REPRODUCE
Task I use:
```yaml
- name: Create a virtual machine on given ESXi hostname
  vmware_guest:
    hostname: "1.1.1.1"
    username: "root"
    password: "somepass"
    esxi_hostname: sgw999vmhost01
    datastore: "VSE_datastore"
    validate_certs: no
    folder: /
    name: test_vm_0001
    state: poweredoff
    guest_id: centos64Guest
    disk:
    - size_gb: 100
      type: thin
      datastore: "VSE_datastore"
    hardware:
      memory_mb: 2048
      num_cpus: 2
      scsi: paravirtual
    networks:
    - name: VM Network
      device_type: vmxnet3
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy_vm
```

##### EXPECTED RESULTS
Single virtual machine is expected. 

##### ACTUAL RESULTS
ESXi host shows that root connected correctly. 
Task execution ends with following error:
```
"msg": "Unable to find host \"sgw999vmhost01\""
```

##### QUESTION
Is it me doing something wrong with that module, or there is a bug ?
