### ISSUE TITLE
Ansible modifies or ignores PYTHONPATH

### ISSUE THREAD

**Issue by magick93** [ansible/ansible#65157]
##### SUMMARY

Ansible is ignoring or modifying the PYTHONPATH, which is causing various modules to fail, as they are looking for pip packages in the wrong place.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/anton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]


```

##### CONFIGURATION

```
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 300
```

##### OS / ENVIRONMENT
Control machine is Ubuntu 18.04.3 LTS.
Remote host is Centos 7

##### STEPS TO REPRODUCE

```yaml

# READ ME
# ansible-playbook  debug-py-path.yml -i myremotehost, -K
---
- name: Debug py path
  hosts: myremotehost
  gather_facts: yes
  vars:
    ansible_ssh_user: deploy
    ansible_python_interpreter:  "/usr/bin/python2.7"
    os_environment:
      - key: PYTHONPATH
        value: /home/deploy/.local/lib/python2.7
  
  tasks:

  - name: populate /etc/environment
    lineinfile:
      dest: "/etc/environment"
      state: present
      regexp: "^{{ item.key }}"
      line: "{{ item.key }}={{ item.value}}"
    with_items: "{{ os_environment }}"
    become: yes

    

  - name: Getting PYTHONPATH
    local_action: shell python -c 'import sys; print(":".join(sys.path))'
    register: pythonpath

  - debug:
      msg: "PYTHONPATH: {{ pythonpath.stdout }}"
```

##### EXPECTED RESULTS
I expect the debug output to contain `/home/deploy/.local/lib/python2.7`

##### ACTUAL RESULTS
The `PYTHONPATH` value is absent.
