### ISSUE TITLE
Ansible 2.9.1: "Maximum sessions reached" error with imc_rest module

### ISSUE THREAD

**Issue by laaubert** [ansible/ansible#65169]
##### SUMMARY
After an upgrade from 2.8.4 to 2.9.1, I noticed a regression issue with the imc_rest module.
The module doesn't clean up its session after each connection to the UCS so after few tasks it won't be able to connect because there are too many session still opened on the CIMC server.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

imc_rest
##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_TIMEOUT(/root/ansible/ansible.cfg) = 30
PARAMIKO_HOST_KEY_AUTO_ADD(/root/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

The target host is a UCS-E server
CIMC version is 3.2(6.20180817145819)

##### STEPS TO REPRODUCE

Execute at least 5 tasks on the CIMC server

```yaml
- name: Set imc connection settings
  set_fact:
    hostname: "{{ hostvars[kickstart_iso_host].imc_ip }}"
    username: "{{ imc_username }}"
    password: "{{ hostvars[kickstart_iso_host].imc_password }}"

- name: Initialize Virtual Drive
  imc_rest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    content: |
        <configConfMo><inConfig>
           <storageVirtualDrive dn="sys/rack-unit-1/board/{{ ucs_virtual_drive_path }}" adminAction="start-fast-initialization"/>
        </inConfig></configConfMo>

- name: delete fanhe Vmedia mapping
  register: error
  ignore_errors: True
  changed_when:
    - '"No such volume" in error'
  imc_rest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    content: |
        <configConfMo><inConfig>
           <commVMediaMap dn="sys/svc-ext/vmedia-svc/vmmap-fanhe" volumeName="fanhe" map="www" status="deleted"/>
        </inConfig></configConfMo>

- name: delete all saved Vmedia mapping
  imc_rest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    content: |
        <configConfMo><inConfig>
           <commVMedia dn="sys/svc-ext/vmedia-svc" adminAction="delete-all-saved-mappings"/>
        </inConfig></configConfMo>

- name: Configure vMedia to point to ISO image on http server, ignore if already exists
  register: error
  ignore_errors: True
  changed_when:
    - '"already exist" in error'
  imc_rest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    content: |
        <configConfMo><inConfig>
           <commVMediaMap dn="sys/svc-ext/vmedia-svc/vmmap-fanhe" map="www"
            mountOptions="username=,password=" remoteFile="{{ kickstart_iso_host }}.iso"
            remoteShare="http://{{ workstation_ip }}/" status="created" volumeName="fanhe"/>
        </inConfig></configConfMo>

- name: Configuring Boot Order to  CDROM, HDD, FDD, PXE, and EFI Without Rebooting the Host
  imc_rest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    content: |
        <configConfMo><inConfig>
           <lsbootDef dn="sys/rack-unit-1/boot-policy" rebootOnUpdate="no">
           <lsbootVirtualMedia access="read-only" order="1" type="virtual-media" rn="vm-read-only"/>
           <lsbootVirtualMedia access="read-write" order="3" type="virtual-media" rn="vm-read-write"/>
           <lsbootLan rn="lan-read-only" access="read-only" order="4" prot="pxe" type="lan"/>
           <lsbootStorage rn="storage-read-write" access="read-write" order="2" type="storage"/>
           <lsbootEfi rn="efi-read-only" access="read-only" order="5" type="efi"/>
           </lsbootDef>
        </inConfig></configConfMo>
```

##### EXPECTED RESULTS

Any task should be executed properly and only one session should be opened at a time with the CIMC server.

Below are some on-going capture of the number of sessions opened on the CIMC server while the playbook is being executed. This is with 2.8.4 where it does work as expected:

```
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
29     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
29     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
30     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
30     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
30     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
31     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
21     admin            10.195.123.15     CLI          no
E1120D-FOC22242ZRX#
```

##### ACTUAL RESULTS

the 5th task will fail with "Maximum sessions reached" error
If you ssh to the CIMC server, you can see there are already 5 sessions active which is the limit of the server

```paste below
TASK [./roles/deploy-iso-image : Set imc connection settings] **************************************************************************************************************************************************************************
task path: /root/ansible/roles/deploy-iso-image/tasks/deploy-iso.yml:4
ok: [localhost] => {"ansible_facts": {"hostname": "10.195.123.28/24", "password": "password", "username": "admin"}, "changed": false}

TASK [./roles/deploy-iso-image : Initialize Virtual Drive] *****************************************************************************************************************************************************************************
task path: /root/ansible/roles/deploy-iso-image/tasks/deploy-iso.yml:10
changed: [localhost] => {"aaaLogin": {"attributes": {"cookie": "", "outCookie": "1574355909/7b8b0746-97de-17de-8006-e44f02735d00", "outPriv": "admin", "outRefreshPeriod": "600", "outSessionId": "8", "outVersion": "3.2(6.20180817145819)", "response": "yes"}}, "changed": true, "configConfMo": {"attributes": {"cookie": "1574355909/7b8b0746-97de-17de-8006-e44f02735d00", "dn": "", "response": "yes"}, "children": [{"outConfig": {"attributes": {}, "children": [{"storageVirtualDrive": {"attributes": {"accessPolicy": "read-write", "adminAction": "no-op", "allowBackgroundInit": "true", "autoDeleteOldest": "true", "autoSnapshot": "false", "bootDrive": "true", "cachePolicy": "direct-io", "currentWriteCachePolicy": "write-through", "diskCachePolicy": "unchanged", "dn": "sys/rack-unit-1/board/storage-SAS-SLOT-5/vd-0", "driveState": "Optimal", "drivesPerSpan": "2", "fdeCapable": "no", "fdeEnabled": "no", "health": "Good", "hotspareAction": "no-op", "id": "0", "name": "RAID1_01", "physicalDrivesList": "Physical drives to be used for virtual drive reconstruction. pd_id1,pd_id2,...pd_idN", "raidLevel": "RAID 1", "readPolicy": "no-read-ahead", "requestedWriteCachePolicy": "write-through", "size": "3662109 MB", "spanDepth": "1", "status": "modified", "stripSize": "64k", "targetId": "0", "vdStatus": "Optimal"}}}]}}]}, "elapsed": 8, "response": "OK (unknown bytes)", "status": 200}

TASK [./roles/deploy-iso-image : delete fanhe Vmedia mapping] **************************************************************************************************************************************************************************
task path: /root/ansible/roles/deploy-iso-image/tasks/deploy-iso.yml:21
ok: [localhost] => {"aaaLogin": {"attributes": {"cookie": "", "outCookie": "1574355918/4784411f-97df-17df-8007-e44f02735d00", "outPriv": "admin", "outRefreshPeriod": "600", "outSessionId": "9", "outVersion": "3.2(6.20180817145819)", "response": "yes"}}, "changed": false, "configConfMo": {"attributes": {"cookie": "1574355918/4784411f-97df-17df-8007-e44f02735d00", "dn": "", "response": "yes"}, "children": [{"outConfig": {"attributes": {}}}]}, "elapsed": 7, "response": "OK (unknown bytes)", "status": 200}

TASK [./roles/deploy-iso-image : delete all saved Vmedia mapping] **********************************************************************************************************************************************************************
task path: /root/ansible/roles/deploy-iso-image/tasks/deploy-iso.yml:36
changed: [localhost] => {"aaaLogin": {"attributes": {"cookie": "", "outCookie": "1574355926/c4cf9784-97de-17de-8008-e44f02735d00", "outPriv": "admin", "outRefreshPeriod": "600", "outSessionId": "10", "outVersion": "3.2(6.20180817145819)", "response": "yes"}}, "changed": true, "configConfMo": {"attributes": {"cookie": "1574355926/c4cf9784-97de-17de-8008-e44f02735d00", "dn": "", "response": "yes"}, "children": [{"outConfig": {"attributes": {}, "children": [{"commVMedia": {"attributes": {"activeSessions": "0", "adminAction": "no-op", "adminState": "enabled", "dn": "sys/svc-ext/vmedia-svc", "encryptionState": "disabled", "lowPowerUsbState": "enabled", "status": "modified"}}}]}}]}, "elapsed": 7, "response": "OK (unknown bytes)", "status": 200}

TASK [./roles/deploy-iso-image : Configure vMedia to point to ISO image on http server, ignore if already exists] **********************************************************************************************************************
task path: /root/ansible/roles/deploy-iso-image/tasks/deploy-iso.yml:47
ok: [localhost] => {"aaaLogin": {"attributes": {"cookie": "", "outCookie": "1574355934/d78b7e1c-97de-17de-8009-e44f02735d00", "outPriv": "admin", "outRefreshPeriod": "600", "outSessionId": "11", "outVersion": "3.2(6.20180817145819)", "response": "yes"}}, "changed": false, "configConfMo": {"attributes": {"cookie": "1574355934/d78b7e1c-97de-17de-8009-e44f02735d00", "dn": "", "response": "yes"}, "children": [{"outConfig": {"attributes": {}, "children": [{"commVMediaMap": {"attributes": {"adminAction": "no-op", "dn": "sys/svc-ext/vmedia-svc/vmmap-fanhe", "map": "www", "mappingStatus": "OK", "mountOptions": "noauto,username=,********=", "password": "", "remoteFile": "fanhe-ucse-2.iso", "remoteShare": "http://10.195.123.15/", "status": "created", "volumeName": "fanhe"}}}]}}]}, "elapsed": 8, "response": "OK (unknown bytes)", "status": 200}

TASK [./roles/deploy-iso-image : Configuring Boot Order to  CDROM, HDD, FDD, PXE, and EFI Without Rebooting the Host] ******************************************************************************************************************
task path: /root/ansible/roles/deploy-iso-image/tasks/deploy-iso.yml:64
fatal: [localhost]: FAILED! => {"aaaLogin": {"attributes": {"cookie": "", "errorCode": "554", "errorDescr": "Maximum sessions reached", "invocationResult": "unidentified-fail", "response": "yes"}}, "changed": false, "error_code": "554", "error_text": "Maximum sessions reached", "msg": "Request failed: Maximum sessions reached", "output": "<aaaLogin cookie=\"\" response=\"yes\" errorCode=\"554\" invocationResult=\"unidentified-fail\" errorDescr=\"Maximum sessions reached\"> </aaaLogin>\n"}
```

Below is the list of sessions opened on the CIMC server after the playbook failed:
```
E1120D-FOC22242ZRX# show user-session
ID     Name             IP Address        Type         Killable
------ ---------------- ----------------- ------------ --------
25     admin            10.195.123.15     xmlapi       yes
24     admin            10.195.123.15     xmlapi       yes
23     admin            10.195.123.15     xmlapi       yes
22     admin            10.195.123.15     xmlapi       yes
21     admin            10.195.123.15     CLI          no
19     admin            10.61.204.131     webgui       yes
```
