### ISSUE TITLE
Implement custom CA certificate path option on all modules that interact over TLS

### ISSUE THREAD

**Issue by onitake** [ansible/ansible#65175]
##### SUMMARY

Currently, there is no option to interact with servers that use custom (non-public) CAs unless the CA certificate is added to the system-wide CA store or the `validate_certs: no` option is specified.

It would be very useful to have a task or ansible.cfg option to specify a custom CA path.

According to #12884 , there was an ansible.cfg option at one point of time, but it wasn't honoured by modules and later removed from the documentation.

There are many modules that interact with URIs and support TLS, perhaps it's possible to implement this feature globally and simply add the respective options to each module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

uri
get_url
...

##### ADDITIONAL INFORMATION

```yaml
- name: Check example.local and verify using a custom CA certificate 
  uri:
    url: https://example.local
    ca_certificate: "{{ playbook_dir }}/files/custom_ca.pem"
```
