### ISSUE TITLE
Handle the case of from_yaml_all ouput not filtered by list

### ISSUE THREAD

**Issue by weshouman** [ansible/ansible#65178]
##### SUMMARY
Show a meaningful error message for the case of not filtering with ```list``` after ```from_yaml_all```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- k8s
- could be in other modules too as it's specific to how output coming from ```from_yaml_all```

##### ANSIBLE VERSION
```paste below
ansible 2.9.1
  config file = /home/walid/ansible-for-devops-ws/kubernetes/ansible.cfg
  configured module search path = [u'/home/walid/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION
```paste below
ANSIBLE_NOCOWS(/home/walid/project_name/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/walid/project_name/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/home/walid/project_name/ansible.cfg) = %(directory)s/%%h-%%p-%%r
DEFAULT_ROLES_PATH(/home/walid/project_name/ansible.cfg) = [u'/home/walid/project_name/roles']
HOST_KEY_CHECKING(/home/walid/project_name/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/walid/project_name/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/walid/project_name/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT
OS Independent

##### STEPS TO REPRODUCE

- Use a multi-document yaml file
- Try to import it with ```from_yaml_all``` without filtering with ```list```

Example:
```yaml
    - name: Apply k8s dashboard - to get the dashboard created.
      k8s:
        state: present
        definition: "{{ lookup('file', 'dashboard.yml') | from_yaml_alll }}"

```
dashboard.yml file
```yaml
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: db

---

kind: Service
apiVersion: v1
metadata:
  name: db
spec:
  ports:
    - port: 443
      targetPort: 1111
  type: NodePort
```

##### EXPECTED RESULTS
```
Error: Input should be filtered into a list first check example at ...
```

##### ACTUAL RESULTS
```
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_k8s_payload_PWLOlf/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py\", line 279, in <module>\n  File \"/tmp/ansible_k8s_payload_PWLOlf/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py\", line 275, in main\n  File \"/tmp/ansible_k8s_payload_PWLOlf/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 175, in execute_module\nAttributeError: 'str' object has no attribute 'get'\n", 

```

#### Technical details
The reason is that:
In file ```ansible_modules/k8s/raw.py``` the ```self.params.get('resource_definition')``` holds a string representation of the generator object which doesn't get treated specially in the for loop  found in ``` api_version = definition.get('apiVersion', self.api_version)``` thus we get the error of a string being treated as an object.
