### ISSUE TITLE
ovirt_nic errors with exception "Network 'infra-prod' was not found in datacenter 'BUA'."

### ISSUE THREAD

**Issue by Timoses** [ansible/ansible#65190]
##### SUMMARY

ovirt_nic reports exception "Network 'infra-prod' was not found in datacenter 'BUA'.".
However, the VM resides in cluster "Default" which is located in datacenter "BAF".
The datacenter "BAF" does have a network named "infra-prod".
Hence, the `ovirt_nic` module should not throw the exception.

It is possible to manually assign the correct network to an interface for the VM via the GUI (in fact, the drop-down list only lists those networks which are available in datacenter "BAF")

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_nic

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /home/myuser/code/ansible/project/ansible.cfg
  configured module search path = [u'/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/.local/lib/python2.7/site-packages/ansible
  executable location = /home/myuser/.local/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/myuser/code/ansible/project/ansible.cfg) = [u'/etc/ansible/inventory/hosts']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/myuser/code/ansible/project/ansible.cfg) = [u'/home/myuser/code/ansible/project/plugins/inventory']
DEFAULT_LOG_PATH(/home/myuser/code/ansible/project/ansible.cfg) = /var/log/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(/home/myuser/code/ansible/project/ansible.cfg) = /home/myuser/.ansible/vault_pass
ENABLE_TASK_DEBUGGER(env: ANSIBLE_ENABLE_TASK_DEBUGGER) = True
HOST_KEY_CHECKING(/home/myuser/code/ansible/project/ansible.cfg) = False
INVENTORY_ENABLED(/home/myuser/code/ansible/project/ansible.cfg) = [u'host_list', u'script', u'auto', u'yaml', u'ini', u'toml']
RETRY_FILES_ENABLED(/home/myuser/code/ansible/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEV-Manager version: 4.3.4.3-0.1.el7

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
  - ovirt_vm:
      auth: "{{ ovirt_auth }}"
      state: "present"
      name: "myvmname"
      cluster: "BAF"
  - ovirt_nic:
      auth: "{{ ovirt_auth }}"
      vm: "myvmname"
      name: "testif"
      interface: "virtio"
      profile: "infra-prod"
      network: "infra-prod"
```

##### EXPECTED RESULTS

NIC 'testif' should be created with profile 'infra-prod' in network 'infra-prod'.

##### ACTUAL RESULTS

Module `ovirt_nic` errors with exception.

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Network 'infra-prod' was not found in datacenter 'BA-PERF'.
failed: [myvmname -> localhost] {"ansible_loop_var": "item", "changed": false, "item": [{"name": "myvmname", "profile": {"boot_devices": "hd", "cluster": "Default", "cores": 2, "disks": [{"activate": true, "bootable": true, "format": "raw", "interface": "virtio_scsi", "name": "infra_sys", "size": "50GiB", "storage_domain": "rhev_infra_data_10"}], "io_threads": 0, "memory": "4GiB", "operating_system": "rhel_7x64", "state": "running", "type": "server"}}, {"interface": "virtio", "name": "prod", "network": "infra-prod", "profile": "infra-prod"}], "msg": "Network 'infra-prod' was not found in datacenter 'BUA'."}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/ovirt/ovirt_nic.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_nic.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @machacekondra @mnecas @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mnecas** [comment]
Hi @Timoses,
I have tried to reproduce the issue but it worked without a problem.
I know you said that the VM is in the data center with network infra-prod, but could you please check it once again. Because we get the data center from the VMs cluster and then get the networks in it.

**Comment by Timoses** [comment]
Thanks for the quick response @mnecas .

I went ahead and tested below reduced example against our RHEV:
```
  - ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: "testvm"
      state: present
      cluster: Default
  - ovirt_nic:
      auth: "{{ ovirt_auth }}"
      vm: "testvm"
      name: "testif"
      interface: "virtio"
      profile: "infra-prod"
      network: "infra-prod"
```

Result:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Network 'infra-prod' was not found in datacenter 'BUA-PERF'.
fatal: [testvm -> localhost]: FAILED! => {"changed": false, "msg": "Network 'infra-prod' was not found in datacenter 'BUA-PERF'."}
```

On the VM when selecting "Edit" in RHEV-M it shows:

> Cluster: Default
>  (Data Center: BAF-INFRA)

In RHEV-M under Compute -> Clusters:

> Name |   | Comment | Data Center | Compatibility Version |
> Default |   |   | BAF-INFRA | 4.3 |

Under Network -> Networks / vNIC Profiles:
Both list `infra-prod` under datacenter `BAF-INFRA`.

Even when creating the VM in another cluster (e.g. `F-INFRA`) then it complains with the same error (looking for the `infra-prod` network in datacenter `BUA-PERF`).


I've checked at this point: https://github.com/ansible/ansible/blob/v2.9.1/lib/ansible/modules/cloud/ovirt/ovirt_nic.py#L259 and it correctly sets the cluster name.
However: https://github.com/ansible/ansible/blob/v2.9.1/lib/ansible/modules/cloud/ovirt/ovirt_nic.py#L261
`dc.name` prints the `BUA-PERF` datacenter... Which is wrong.

ovirt-engine-sdk-python version is 4.3.3 .
