### ISSUE TITLE
Jinja <2.9 fails to evaluate templated keys on CentOS7

### ISSUE THREAD

**Issue by msaladna** [ansible/ansible#65198]
##### SUMMARY

In reference to issue #65136, certain YAML patterns that fail to resolve templated keys beginning in Ansible 2.9.0. After more digging I've traced the issue back to Jinja 2.7 that ships with CentOS 7. Installing Ansible via EPEL, which pulls down the stock python-jinja2 package exhibits the problem. Installing via pip, which pulls down Jinja 2.10.3, does not.

The referenced issue, #65136, contains a couple other cases where the key is not properly evaluated but all appear to be linked back to changes introduced in pallets/jinja@1205e641ed9d1c4eb581b50ab3cc5313b9950773 that aren't backported to 2.7.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

pallets/jinja@1205e641ed9d1c4eb581b50ab3cc5313b9950773

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

*N/A*

##### OS / ENVIRONMENT

CentOS Linux release 7.7.1908 (Core)

##### STEPS TO REPRODUCE

```bash
pip uninstall -y Jinja2
# Install the EPEL python-jinja2 package
yum reinstall -y python-jinja2
# or
pip install Jinja2==2.7.2
```

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    subexpr: myvar
    dict:
      "a{{ subexpr }}-def": "C visible"
      "myvar-b": "{{ subexpr_undef | default('foo') }}"
      "myvar-c": >-
        "{{ subexpr }}"
  tasks:
    - set_fact:
        var2: "{{ dict | combine({}) }}"
    - debug: msg="{{ item.key }} - {{ item.value }}"
      loop: "{{ var2 | dict2items }}"
```

`"{{ lookup('pipe', 'echo HELLO') }}"` also exhibits this problem.

##### EXPECTED RESULTS

```
ok: [localhost] => (item={'key': 'amyvar-def', 'value': 'C visible'}) => {
    "msg": "amyvar-def - C visible"
}
ok: [localhost] => (item={'key': 'myvar-b', 'value': 'foo'}) => {
    "msg": "myvar-b - foo"
}
ok: [localhost] => (item={'key': 'myvar-c', 'value': '"myvar"'}) => {
    "msg": "myvar-c - \"myvar\""
}
```

##### ACTUAL RESULTS

```paste below
ok: [localhost] => (item={'key': u'myvar-c', 'value': u'"myvar"'}) => {
    "msg": "myvar-c - \"myvar\""
}
ok: [localhost] => (item={'key': u'myvar-b', 'value': u'foo'}) => {
    "msg": "myvar-b - foo"
}
ok: [localhost] => (item={'key': u'a{{ subexpr }}-def', 'value': u'C visible'}) => {
    "msg": "a{{ subexpr }}-def - C visible"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The templating changes in https://github.com/pallets/jinja/commit/1205e641ed9d1c4eb581b50ab3cc5313b9950773 mean that where in jinja2<2.9 we saw the undefined class used, in >=2.9 things are now templated fully.

Due to `AnsibleUndefined` being returned, and it's due to it's implementation, it passed the following check from `AnsibleContext._is_unsafe`

```
elif hasattr(val, '__UNSAFE__'):
```

This is because `AnsibleUndefined.__getattr__` always returns a value for every missing attribute.

We likely want to approach this in a few ways:

1. Improve the check in `AnsibleContext._is_unsafe` to use `getattr` with a comparison to `True`
2. `AnsibleUndefined` should special case `__UNSAFE__` to raise an `AttributeError`

**Comment by msaladna** [comment]
This resolves one case. What about in the situation of lookup('pipe')? 

```yaml
    dict:
      "a{{ subexpr }}-def": "C visible"
      "myvar-b": "{{ lookup('pipe', 'echo Test') }}"
      "myvar-c": "{{ subexpr }}"
```

I can understand the intention to be cautious on unsanitized input from untrusted sources. I pull defaults from a system-owned ini-style file, but because it's sectionless lookup('ini') won't work. grep/cut are used to set the defaults and the dict key is determined dynamically from another var like in this example.

If this case isn't able to be resolved presently, what about adding a "yaml_quote" or "to_safe" filter that takes the response data and reformats it in a safe manner such that the unsafe attribute may be removed and `dict | dict2items` properly templates keys? Or intentionally prefixing the value as "!safe" to complement the !unsafe pragma.
