### ISSUE TITLE
AWS ECR Attribute Error

### ISSUE THREAD

**Issue by mjmayer** [ansible/ansible#65206]
##### SUMMARY
When using the aws_ecr module to configure an existing elastic container registry the module fails.
I suspect this is related to the recent code change #62871

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ecs_ecr

##### ANSIBLE VERSION

```

ansible 2.10.0.dev0

config file = None
configured module search path = [u'/home/bamboo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /opt/ansible/lib/ansible
executable location = /opt/ansible/bin/ansible
python version = 2.7.5 (default, Aug  7 2019, 08:19:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]

```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT
REHL 7

##### STEPS TO REPRODUCE
```yaml
- name: set elastic container registry
  ecs_ecr:
    name: "{{ appname }}"
    state: present
    policy:
      Version: '2008-10-17'
      Statement:
        - Sid: "new statement"
          Effect: Allow
          Principal:
            AWS: 'arn:aws:iam::43242342342:role/ecsTaskExecutionRole'
          Action:
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - ecr:BatchCheckLayerAvailability
            - ecr:PutImage
            - ecr:InitiateLayerUpload
            - ecr:UploadLayerPart
            - ecr:CompleteLayerUpload
            - ecr:DescribeRepositories
            - ecr:GetRepositoryPolicy
            - ecr:ListImages
            - ecr:DescribeImages
            - ecr:DeleteRepository
            - ecr:BatchDeleteImage
            - ecr:SetRepositoryPolicy
            - ecr:DeleteRepositoryPolicy
            - ecr:GetLifecyclePolicy
            - ecr:PutLifecyclePolicy
            - ecr:DeleteLifecyclePolicy
            - ecr:GetLifecyclePolicyPreview
            - ecr:StartLifecyclePolicyPreview
```

##### EXPECTED RESULTS
The module completes without failure

##### ACTUAL RESULTS
```

22-Nov-2019 10:37:42 | TASK [docker_webapp : set elastic container registry] **************************
-- | --
22-Nov-2019 10:37:43 | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'ECR' object has no attribute 'put_image_tag_mutability'
22-Nov-2019 10:37:43 | fatal: [localhost]: FAILED! => {"changed": false, "created": false, "msg": "'ECR' object has no attribute 'put_image_tag_mutability'", "state": "present"}


```
