### ISSUE TITLE
Allow tower_host module to associate a host with groups

### ISSUE THREAD

**Issue by akira6592** [ansible/ansible#65225]
##### SUMMARY

I want to associate a host with  groups using the tower_host module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- tower_host

##### ADDITIONAL INFORMATION

In the case of tower-cli, it is realized as follows.
```
tower-cli host associate --host router1 --group router 
tower-cli host associate --host router1 --group dc 
```
However, it seems that this is not possible with the `tower_host` module.

```yaml
- name: create host
  tower_host:
    name: router1
    inventory: test_inventory
    state: present
    groups:       # For example, I want an option like this
      - router
      - dc
    tower_config_file: "~/tower_cli.cfg"
```
