### ISSUE TITLE
podman connection plugin order of arguments

### ISSUE THREAD

**Issue by ljesmin** [ansible/ansible#65220]
##### SUMMARY
Execution using podman connection fails due to issues executing podman on command line.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
podman connection plugin

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jesmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
No changes
```

##### OS / ENVIRONMENT
OS: Fedora 31, cgroupsv1 is disabled.

##### STEPS TO REPRODUCE

```
- hosts: localhost
  become: no
  tasks:
  - name: start container
    command: "podman run -d --name {{ container_name  }} --hostname {{ container_name  }} ubuntu:latest sleep infinity"
    ignore_errors: true

  - name: add new hosts to inventory
    add_host:
      ansible_connection: podman
      name: "{{ container_name }}"
      ansible_host: "{{ container_name }}"
      ansible_user: root
      groups: containers
    changed_when: false
  vars:
    container_name: 'testhost'

- hosts: testhost
  gather_facts: false
  tasks:
  - name: Check for Python
    raw: '/bin/sh -c "test -e /usr/bin/python"'
    changed_when: false
    failed_when: false
    register: check_python

  - name: install python
    raw: '/bin/sh -c "apt update && apt install -y python-minimal"'
    when: check_python.rc != 0

- hosts: testhost
  tasks:
  - name: exec command
    raw: "echo test"
```

As root, run ansible_playbook -vvv this_playbook.yml
There is another issue that prevents it from running as normal user.

Note that podman exec --interactive does not work on Fedora 31 as there is
additional bug in podman. This prevents interpreter discovery but is not related to
current bug.

https://github.com/containers/libpod/issues/3302 

##### EXPECTED RESULTS

returning stdout from "raw" execution would return "test"

##### ACTUAL RESULTS

Playbook contains this task:
```
- hosts: testhost
  tasks:
  - name: exec command
    raw: "echo test"
```

As task "exec command" is executed, arguments --user root are added by
connector plugin as last arguments and are therefore passed on to underlying command.

Correct order of arguments would be that --user root should be before container name
(this case testhost).

Result of task execution (note that stdout_lines should be only "test")

```
TASK [exec command] *********************************************************************************************************************************************************************************
task path: /home/jesmin/wrk/ansible_test/test_podman.yml:34
<testhost> RUN [b'podman', b'mount', b'testhost']
<testhost> RUN [b'podman', b'exec', b'testhost', b'echo', b'test', b'--user', b'root']
changed: [testhost] => {
    "changed": true,
    "rc": 0,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "test --user root\n",
    "stdout_lines": [
        "test --user root"
    ]
}
```
