### ISSUE TITLE
The --force-handlers option if used with 'strategy: free' does not run handlers on all hosts. 

### ISSUE THREAD

**Issue by benjdudas** [ansible/ansible#65254]
##### SUMMARY

As of Ansible 2.7 the `--force-handlers` option is no longer running the handler/s on all hosts when used with strategy free. Only tested back to 2.5 and this was working as I would expect it to on 2.5 & 2.6.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/strategy 

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /Users/bdudas/dev-net/handlers/ansible.cfg
  configured module search path = [u'/Users/bdudas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/bdudas/dev-net/handlers/ansible/lib/ansible
  executable location = /Users/bdudas/dev-net/handlers/ansible/bin/ansible
  python version = 2.7.16 (default, Oct 16 2019, 00:34:56) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION

```paste below
DEFAULT_STRATEGY(/Users/bdudas/dev-net/handlers/ansible.cfg) = free
HOST_KEY_CHECKING(/Users/bdudas/dev-net/handlers/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/bdudas/dev-net/handlers/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: false

  tasks:
    - command: hostname
      register: id
      notify: recovery_x

    - debug:
        var: id

    - name: failure
      fail: msg="Testing Failure"
      when: inventory_hostname == 'covfefe'

  handlers:
    - name: recovery_x
      shell: hostname
...
```
ansible-playbook <playbook.yml> --force-handlers

##### EXPECTED RESULTS

Handlers will run against all hosts when using the `--force-handlers` option. 

##### ACTUAL RESULTS

Handler is only run on 1 of the 2 target hosts.

```paste below

```
