### ISSUE TITLE
tower_job_launch fails on non-trivial extra_vars

### ISSUE THREAD

**Issue by jeffwarnica** [ansible/ansible#65258]
##### SUMMARY

tower_job_launch is documented to take `extra_vars` parameter. It is not clear what is allowed, but seems to take a simple k/v dictionary, as expected. However, it does _not_ take a deeper structure, or - and this is shocking - any data with a comma in it.

The error message (and comma failure) would seem to indicated the value for extra_var is mangled to a string and passed and re-parsed as a string, it breaking on commas being a giveaway. (sorry, the error message is in a VDI and unavailable). 

Whatever the root problem, extra_vars should take an arbitrary complex structure, and work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible_launch_job
TowerModule

##### STEPS TO REPRODUCE

* have a task with tower_launch_job that has either nested structure, or any value with a omma in it

##### EXPECTED RESULTS

Tower job be launched 

##### ACTUAL RESULTS

Exception

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/web_infrastructure/ansible_tower/tower_role.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jeffwarnica: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AlanCoding @chrismeyersfsu @ghjm @jladdjr @kdelee @matburt @rooftopcellist @ryanpetrello
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by AlanCoding** [comment]
An FYI, we are no longer maintaining the modules here, because we are moving them to a collection, with the current issue tracking at https://github.com/ansible/awx/issues?q=is%3Aissue+is%3Aopen+label%3Acomponent%3Aawx_collection

In your case, I would like to get the YAML of the task causing the error to help reproduce it.

**Comment by mjlshen** [comment]
Here's an example playbook @AlanCoding I can open another issue over there if that's the right place to put this.
```
- hosts: localhost
  tasks:
    - name: 'test extra vars'
      set_fact:
        my_list:
          - 'a'

    - name: 'Launch my-tower-job'
      tower_job_launch:
        job_template: 'my-tower-job'
        extra_vars:
          - my_list
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
```

**Comment by mjlshen** [comment]
Based off of your [AWX #5558 issue](https://github.com/ansible/awx/issues/5558) I found that this syntax, however, does allow passing in lists. So maybe it's really just a documentation issue:

```
- hosts: localhost
  tasks:
    - name: 'Launch my-tower-job'
      tower_job_launch:
        job_template: 'my-tower-job'
        extra_vars: >
          my_list: ['a']
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
```

**Comment by jeffwarnica** [comment]
`>` makes it a string, which _looks like_ yaml, and manages to get  passed along, except when it isn't.

I'm confident the following would barf:

```
- hosts: localhost
  tasks:
    - name: 'Launch my-tower-job'
      tower_job_launch:
        job_template: 'my-tower-job'
        extra_vars: >
          body: Dear Sir, this is text with a comma in it.
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: "{{ tower_host }}"
```
