### ISSUE TITLE
environment section not populated with pre-task variables

### ISSUE THREAD

**Issue by nicohouillon** [ansible/ansible#65269]
##### SUMMARY

before ansible 2.7.2 (at least) we could run pre-task before evaluating environment section .
since updated to 2.7.9 and above, environment section fails for undefined variable even though it is created in pre-task .

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible playbook 
##### ANSIBLE VERSION

```paste below
ansible-playbook 2.7.9
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True

```

##### OS / ENVIRONMENT

Centos 7.7 

##### STEPS TO REPRODUCE

```yaml
- name: Teardown cloudformation stack
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Fail if aws_env is not set to dev
      fail:
        msg: "aws_env is not set to dev. Set it to 'dev' in the job template."
      when: aws_env !="dev"

    - name: Fail if cf_stack_name is not set
      fail:
        msg: "cf_stack_name is not set. Set it to dev stack name in job template."
      when: not cf_stack_name

    - name: Assume teardown devel stack role
      sts_assume_role:
        role_arn: "arn:aws:iam::xxx:role/my_role" 
        role_session_name: "my_session"
        region: "{{ cf_region }}"
      register: assumed_role
      no_log: true
tasks: 
 - name: foo 
roles: 
 - my_role

environment:
    AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
    AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
    AWS_REGION: "{{ cf_region }}"
```

##### EXPECTED RESULTS

The content of environment should evaluate the pre-task 'assume role' and therefore populate the environment section with AWS credentials.  

##### ACTUAL RESULTS

```paste below
TASK [Gathering Facts] *********************************************************
task path: /var/lib/awx/projects/_1.yml:3
fatal: [127.0.0.1]: FAILED! => {
    "msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'assumed_role' is undefined"
}

```
