### ISSUE TITLE
Add state: empty for the file module

### ISSUE THREAD

**Issue by tquid** [ansible/ansible#65266]
##### SUMMARY

Emptying a directory is cumbersome using native Ansible tools, so mostly people will use a shell-command `rm` to do it.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

file
##### ADDITIONAL INFORMATION

Adding state `empty` to the file module would cause the playbook to delete all files in a directory. It could also be applied to a file to truncate it to 0 bytes.

```yaml
    - name: Clear sssd db when ldap_id_mapping setting is changed.
      file:
        state: empty
        path: /var/lib/sss/db/
      when: ldap_id_mapping.changed
```

This would replace the rather more verbose solution below (which also loses information about directory creation and modification times, as well as adding opportunities for getting ownership and mode incorrect):

```yaml
    - name: Clear sssd db when ldap_id_mapping setting is changed.
      file:
        state: "{{ item }}"
        path: /var/lib/sss/db/
        owner: sssd
        group: sssd
        mode: '0755'
      with_items:
        - absent
        - directory
      when: ldap_id_mapping.changed
```
