### ISSUE TITLE
Xenserver state inconsistency

### ISSUE THREAD

**Issue by planeturban** [ansible/ansible#65267]
##### SUMMARY
The states in xenserver_guest and xenserver_guest_powerstate have different naming conventions:
_guest: poweredon
_guest_powerstate: powered-on, powered-off (and so on)

It ought to be just one, right?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
xenserver_guest
xenserver_guest_powerstate

##### ANSIBLE VERSION
ansible 2.9.0

##### CONFIGURATION
Not applicable

##### OS / ENVIRONMENT
Not applicable

##### STEPS TO REPRODUCE
Docs:

https://docs.ansible.com/ansible/latest/modules/xenserver_guest_module.html

https://docs.ansible.com/ansible/latest/modules/xenserver_guest_powerstate_module.html#xenserver-guest-powerstate-module

##### EXPECTED RESULTS
Not having to remember if there should be a dash or not.

##### ACTUAL RESULTS
Keep failing 25% if the times when juggling the different modules?

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/xenserver/xenserver_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/xenserver/xenserver_guest.py)
* [`lib/ansible/modules/cloud/xenserver/xenserver_guest_powerstate.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/xenserver/xenserver_guest_powerstate.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bvitnik
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bvitnik** [comment]
Hi @planeturban . `poweredon` state for `xenserver_guest` is a leftover from early development and is kept for some internal backward compatibility. I'm more inclined to remove it completely than to rename it. All power related state management should be done trough `xenserver_guest_powerstate` module. Also, the idea was to keep the module compatible with `vmware_guest` module as much as possible. `vmware_guest` module also have this power state naming difference.

Maybe I can make this more clear in the docs. My advice is to use `xenserver_guest_powerstate` module exclusively. If Ansible supported module parameter value aliases, I would gladly make both `poweredon` and `powered-on` work on both modules.

**Comment by planeturban** [comment]
Ok, fine by me. :)

But in that case you probably want to update the "present" state. Since the guest has to be powered off to be reconfigured. The following will not work if powered on and change is true.

And this seems to be the logical way to do it, in my mind.


````
    - name: Create a VM from a template
      xenserver_guest:
        hostname: "{{ xenserver_hostname }}"
        username: "{{ xenserver_username }}"
        password: "{{ xenserver_password }}"
        validate_certs: no
        folder: /
        name: "{{ inventory_hostname }}"
        template: alpine-1.4
        state: present
        networks:
        - name: hostinterface
          type: dhcp
        hardware:
          num_cpus: "{{ guest_cpu }}"
          num_cpu_cores_per_socket: "{{ guest_cpu_socket }}"
          memory_mb: "{{ guest_memory }}"
      delegate_to: localhost
      register: data
```` 

 Or, maybe it's a feature request? Either way, I'm fine with whichever solution. :)


I've solved this with some handlers and an ugly changed_when:

````
changed_when: data['instance']['hardware']['num_cpus'] | int != guest_cpu|int or data['instance']['hardware']['num_cpu_cores_per_socket'] | int != guest_cpu_socket|int or data['instance']['hardware']['memory_mb'] != guest_memory | int
      notify:
        - "reconfigure"
````
