### ISSUE TITLE
tmp files not removed when using delegate_to in synchronize module

### ISSUE THREAD

**Issue by rule88** [ansible/ansible#65277]
##### SUMMARY
When using the synchronize module to synchronize files between directories where the source and directory are the same host, tmp (~.ansible/tmp/) files won't be removed after completion.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- synchronize

##### ANSIBLE VERSION
```
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
Also affects 2.9.1 (upgraded in place with RPM)
```
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
default:
```# ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
```cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
```

##### STEPS TO REPRODUCE
After running the following playbook:
```
  tasks:
  - name: Sync shibboleth configuration files from NAS
    synchronize:
      src: "/opt/test1/"                                                                                                                                                                                                                         
      dest: "/opt/test2/"                                                                                                                                                                                                                        
    delegate_to: "{{ inventory_hostname }}"
```

on the remote host the following contents are found in ~/.ansible/tmp:
```
# ls .ansible/tmp/
ansible-tmp-1574758137.42-167293202248350
```

after running the same playbook, but without delegate_to, no additional files are to be found in the ~/.ansible/tmp directory:
```
# ls .ansible/tmp/
ansible-tmp-1574758137.42-167293202248350
```

##### EXPECTED RESULTS
It is expected that even when using delegate_to the tmp files on the remote are removed by ansible.

##### ACTUAL RESULTS
Files are simply not removed on the remote, not trace of even ansible trying to:

```
changed: [remote_host -> remote_host ] => {
    "changed": true,
    "cmd": "/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /opt/test1/ /opt/test2/",
    "invocation": {
        "module_args": {
            "_local_rsync_password": null,
            "_local_rsync_path": "rsync",
            "_substitute_controller": false,
            "archive": true,
            "checksum": false,
            "compress": true,
            "copy_links": false,
            "delete": false,
            "dest": "/opt/test2/",
            "dest_port": null,
            "dirs": false,
            "existing_only": false,
            "group": null,
            "link_dest": null,
            "links": null,
            "mode": "push",
            "owner": null,
            "partial": false,
            "perms": null,
            "private_key": null,
            "recursive": null,
            "rsync_opts": [],
            "rsync_path": null,
            "rsync_timeout": 0,
            "set_remote_user": true,
            "src": "/opt/test1/",
            "ssh_args": null,
            "times": null,
            "verify_host": false
        }
    },
    "msg": ".d..t...... ./\n",
    "rc": 0,
    "stdout_lines": [
        ".d..t...... ./"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************************************************phb-s-app2                 : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
