### ISSUE TITLE
Ansible variable becomes defined in loop by `default` notation, despite when controller

### ISSUE THREAD

**Issue by tylarb** [ansible/ansible#65295]
##### SUMMARY

If a `| default ` is used in a loop, the variable in front of the "pipe" becomes defined before the "when" statement is resolved.

This leads to tasks getting executed in an unexpected way. 

Whereas for the "loop" example given, you can skip the task with an empty list, and the end result is the same, we believe that a variable should not be defined in a tasks until the "when" statement is passed - in this example, we can see that the task builds a variable and seemingly ignores the "when" statement if  `| default()` is used. 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
# ansible-config dump --only-changed

```

##### OS / ENVIRONMENT

Minimal test case:

Use following ansible playbook into "testplay.yml"

`ansible-playbook testplay.yml` 

```yaml
## variable remains undefined, entire task skipped
- hosts: all
  vars: 
   # yum_installs:
   # - wget
   # - curl
  tasks:
  - name: test
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ yum_installs }}" # | default([]) }}"
    loop_control:
      label: "{{ item }}"
    when: yum_installs is defined

## variable becomes defined, and task is NOT skipped
- hosts: all
  vars: 
   # yum_installs:
   # - wget
   # - curl
  tasks:
  - name: test
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ yum_installs  | default([]) }}"
    loop_control:
      label: "{{ item }}"
    when: yum_installs is defined

## task FAILS because "loop" expects a list, not an empty object, even though it should be skipped due to "yum_installs" not defined
- hosts: all
  vars: 
   # yum_installs:
   # - wget
   # - curl
  tasks:
  - name: test
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ yum_installs  | default({}) }}"
    loop_control:
      label: "{{ item }}"
    when: yum_installs is defined
```

##### EXPECTED RESULTS

task "test" is always skipped. 

##### ACTUAL RESULTS

task test is not always skipped, if `| default({}) ` is used, tasks fails due to variable resolved to invalid object.

```paste below
# ansible-playbook testplay.yml 

PLAY [all] **********************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [mdw4]
ok: [sdw4]
ok: [sdw2]

TASK [test] *********************************************************************************************
skipping: [sdw2]
skipping: [sdw4]
skipping: [mdw4]

PLAY [all] **********************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [mdw4]
ok: [sdw2]
ok: [sdw4]

TASK [test] *********************************************************************************************

PLAY [all] **********************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [mdw4]
ok: [sdw2]
ok: [sdw4]

TASK [test] *********************************************************************************************
fatal: [sdw2]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
fatal: [sdw4]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
fatal: [mdw4]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

PLAY RECAP **********************************************************************************************
mdw4                       : ok=3    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
sdw2                       : ok=3    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
sdw4                       : ok=3    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

```
