### ISSUE TITLE
Ansible role duplication at meta folder

### ISSUE THREAD

**Issue by foo-source** [ansible/ansible#65314]
I wanted to include two same roles in my meta/main.yml dependencies.
Below is Role-01:  

```
dependencies:
- role: ansible-role-service-account
    vars:
      service_account: test_user1
      service_account_group: test_user1
```

Below is Role-02

```
  - role: ansible-role-service-account
    vars:
      service_account: test_user2
      service_account_group: test_user2
      service_account_groups: test_groups
      service_account_shell: /bin/bash
      service_account_public_key:
      service_account_sudo_enabled: true
```

When execute, the Role-02 will overwrite Role-01 which it will create groups, add public key and  make a sudo account based on Role-02. 

Any method to prevent it from overwriting as stated above?

Thank you.
