### ISSUE TITLE
ansible[azure] output structure major changes

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#65316]
##### SUMMARY

This might not be a bug but no sure where to post the issue.
Output structure has changed so much that migration will take days.
Below is just one example.

Output before
```
"{{ item.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
```

Output after
```
"{{ item.publicipaddresses[0].ip_address }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_publicipaddress_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### OS / ENVIRONMENT

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```

```
azure-cli                         2.0.77
```

##### STEPS TO REPRODUCE

```yaml
- name: "get virtual machine facts by tag {{ tag }}"
  azure_rm_virtualmachine_facts:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    tags:
      - type:{{ tag }}
  register: virtualmachine_facts
  delegate_to: localhost

- name: "set {{ tag }} virtual machine facts"
  set_fact:
    vms: "{{ virtualmachine_facts.vms }}"
  delegate_to: localhost

- name: "get facts for {{ tag }} public ip"
  azure_rm_publicipaddress_facts:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    resource_group: "{{ item.resource_group }}"
  loop: "{{ vms }}"
  loop_control:
    label: "Public IP address facts added."
  register: publicipaddress_facts
  when: item is defined
  delegate_to: localhost

- name: "add virtual machine host {{ tag }} with ntlm credentials"
  add_host:
    name: "{{ item.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
    groups: "{{ tag }}"
    ansible_user: "{{ vm_user }}"
    ansible_password: '{{ vault_vm_password }}'
    ansible_port: 5986
    ansible_winrm_transport: ntlm
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    tag: "{{ tag }}"
    true_aio: "{{ item.item.tags.true_aio | default('false') | bool }}"
    vmname: "{{ item.item.name }}"
    resourcegroup: "{{ item.item.resource_group }}"
    address: "{{ item.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
  loop: "{{ publicipaddress_facts.results }}"
  loop_control:
    label: "{{ item.item.name | upper }} with public IP address {{ item.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }} was added as host."
  when: item.ansible_facts.azure_publicipaddresses[0].properties.ipAddress is defined
  delegate_to: localhost
  no_log: true
```

##### EXPECTED RESULTS

Expected that all modules generate the same output as before. Azure-Cli and Ansible release notes mention nothing about output structure changes.

##### ACTUAL RESULTS

Variable 'item' does not know some output properties:
```paste below
ansible_facts does not exist
azure_publicipaddresses does not exist
properties does not exist
ipAddress does not exist
```

New playbook
```
- name: "get virtual machine facts by tag {{ tag }}"
  azure_rm_virtualmachine_info:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    tags:
      - type:{{ tag }}
  register: virtualmachine_facts
  delegate_to: localhost

- name: "set {{ tag }} virtual machine facts"
  set_fact:
    vms: "{{ virtualmachine_facts.vms }}"
  delegate_to: localhost

- name: "get facts for {{ tag }} public ip"
  azure_rm_publicipaddress_info:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    resource_group: "{{ item.resource_group }}"
  loop: "{{ vms }}"
  loop_control:
    label: "Public IP address facts added."
  register: publicip_address_facts
  when: item is defined
  delegate_to: localhost

- name: "add virtual machine host {{ tag }} with ntlm credentials"
  add_host:
    name: "{{ item.publicipaddresses[0].ip_address }}"
    groups: "{{ tag }}"
    ansible_user: "{{ vm_user }}"
    ansible_password: '{{ vault_vm_password }}'
    ansible_port: 5986
    ansible_winrm_transport: ntlm
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    tag: "{{ tag }}"
    true_aio: "{{ item.item.tags.true_aio | default('false') | bool }}"
    vmname: "{{ item.item.name }}"
    resourcegroup: "{{ item.item.resource_group }}"
    address: "{{ item.publicipaddresses[0].ip_address }}"
  loop: "{{ publicip_address_facts.results }}"
  loop_control:
    label: "{{ item.item.name | upper }} with public IP address {{ item.publicipaddresses[0].ip_address }} was added as host."
  when: item.publicipaddresses[0].ip_address is defined
  delegate_to: localhost
```

Where can I find any changes to output structure?
