### ISSUE TITLE
MySQL Service Module Bug

### ISSUE THREAD

**Issue by yangchao0512** [ansible/ansible#65318]
##### SUMMARY

MySQL 5.6 use ansible service module bug：service mysql restart.
mysql restart error,but service module return success.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible service module
mysql 5.6

##### ANSIBLE VERSION

```paste below
2.6.19
```

##### CONFIGURATION

```paste below
Default configuration
```

##### OS / ENVIRONMENT

42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linu

##### STEPS TO REPRODUCE

```yaml
- name: Restart Mysql
  service:
    name: mysql
    state: restarted
```

##### EXPECTED RESULTS

Response error or restart failed

##### ACTUAL RESULTS

 Result none

```paste below

```
