### ISSUE TITLE
Add 'allow_change_held_packages' option to apt module.

### ISSUE THREAD

**Issue by tinproject** [ansible/ansible#65325]
##### SUMMARY

When installing or updating an already held apt package with the `apt` module, it fails. 
This forces to use the `force: yes` option that it's too broad and already deprecated by apt.

Add an option `allow_change_held_packages` to the `apt` module to use the `--allow-change-held-packages` `apt` option.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

apt

##### ADDITIONAL INFORMATION

```yaml
- name: Install package with specific version and hold
  block:
    - name: Install {{ package_name }} version {{ version }}"
      apt:
        name: "{{ package_name }}={{ version }}"
        state: present
        (force|allow_change_held_packages): yes

    - name: Hold {{ package_name }} package
      dpkg_selections:
        name: "{{ package_name }}"
        selection: hold
```

This is not idempotent without the `force: yes`, the second run will fail. 
The `allow_change_held_packages` will avoid problems with this special situation.

Related to: https://github.com/ansible/ansible/issues/15394

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/packaging/os/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by staelche** [comment]
Just found out there is another option which has to be used in addition to --allow-change-held-packages in case you want to downgrade a held package: --allow-downgrades.

Shall I add this option to my PR or create a new ticket and new PR. It would make sense to have it in one PR since those options are related when you look at how Ansible is using APT (settings the -y flag). Only in case you use the -y flag you need to add those additional options.

**Comment by r-pufky** [comment]
`--allow-downgrades` `--allow-remove-essential` `--allow-change-held-packages` should all be added as they are used together. They are commonly used together for silent {dist,full}-upgrades. With them all added you can essentially make full-upgrades very easy to do with ansible, assuming the driver does enough pre-checking to not shoot themselves in the foot.

With the proposed additions:
``` yaml
- name: full upgrade to next distro release
   ansible.builtin.apt:
     update: full
     dpkg_options: 'force-confold,force-confdef'
     allow_change_held_packages: true
     allow_remove_essential: true
     allow_downgrades: true
```

This gets you a full distribution upgrade with no interruptions if you've already done your pre-checks and setup your new distro version repos.

The ansible task above would essentially be doing this:
``` bash
DEBIAN_FRONTEND=noninteractive \
  apt-get \
  -o Dpkg::Options::=--force-confold \
  -o Dpkg::Options::=--force-confdef \
  -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
  full-upgrade
```
