### ISSUE TITLE
alternatives: Allow installation of alternatives without changing the existing selection

### ISSUE THREAD

**Issue by guenhter** [ansible/ansible#65328]
##### SUMMARY
When a ansible alternative is installed, it automatically also changes the selection to the newly added alternative (see here):

```
  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/my-jdk/jre/bin/java   50      manual mode
```

But this is not always intended. So it would be useful if

* alternative path is added
* a new option defines if the current selection is changes (if selection is e.g. 0 (auto-mode) it should leave that as it is)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
alternatives

##### ADDITIONAL INFORMATION

```yaml
---
- hosts: all
  become: true
  tasks:
    - name: Correct java version selected
      alternatives:
        name: java
        path: /usr/lib/jvm/my-jdk/jre/bin/java
        change_selection: False
```
