### ISSUE TITLE
fortios: Function underscore_to_hyphen does not seems right

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible#65330]
##### SUMMARY
All Fortios modules use a function called `underscore_to_hyphen`, which does not seems right to me. 
https://github.com/ansible/ansible/blob/6ae01d4fbdcf713b1bdd420f586db79e44debb61/lib/ansible/modules/network/fortios/fortios_firewall_address6.py#L388

When data is a list, it just loops over it and returns the same data.

I am not familiar with data structures which the modules are handling and processing using this function, so I am not quite sure what it is doing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/network/fortios/fortios_firewall_address.py

##### ANSIBLE VERSION

```paste below
devel and 2.9 as well
```

##### CONFIGURATION

```paste below

```

##### EXPECTED RESULTS

`underscore_to_hyphen` should be corrected as per the data structure available.
Also, move this function to common module_utils so that reduces the redundancy.

##### ACTUAL RESULTS
It is not doing whatever it is supposed to do.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/network/fortios/fortios_firewall_address.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/fortios/fortios_firewall_address.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bjolivot @mamunozgonzalez @thomnico
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Akasurde, just so you are aware we have a dedicated Working Group for network.
You can find other people interested in this in `#ansible-network` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by superAX** [comment]
Face same issue when coding playbook with `fortios` modules. Actually all the modules have this issue. The following is a quick solution,  
```
def underscore_to_hyphen(data):
    if isinstance(data, list):
        for i, elem in enumerate(data):
            data[i] = underscore_to_hyphen(elem)
    elif isinstance(data, dict):
        new_data = {}
        for k, v in data.items():
            new_data[k.replace('_', '-')] = underscore_to_hyphen(v)
        data = new_data
    return data
```

**Comment by akira6592** [comment]
The `ssl_exempt` option in the `fortios_firewall_ssl_ssh_profile` module seems to have the same problem.

```yaml
    fortios_firewall_ssl_ssh_profile:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      vdom: "{{ vdom }}"
      https: "{{ ansible_httpapi_use_ssl }}"
      ssl_verify: "{{ ansible_httpapi_validate_certs }}"
      state: "present"
      firewall_ssl_ssh_profile:
        name: "custom-deep-inspection4"
        ssl_exempt:
          - id: "1"
            type: "wildcard-fqdn"
            wildcard_fqdn: "google"    # here
```

The `wildcard fqdn` option should be replaced to `wildcard-fqdn` by `underscore_to_hyphen`. But because it is not replaced, an error occurs.
