### ISSUE TITLE
Add functionality to `nxos_l2_interfaces`  to append the allowed vlans list

### ISSUE THREAD

**Issue by benjdudas** [ansible/ansible#65332]
##### SUMMARY

Currently, the `nxos_l2_interfaces` module does not provide an option to append vlans to that allowed vlan list. When using the `state: merged`  any config that was untouched by the task remains but any configuration provided will replace the current config. This option was available in the `nxos_l2_interface` with the `trunk_vlans` parm.  The module is currently sending the `switchport trunk allowed vlan <#>` and not `switchport trunk allowed vlan add <#>` so a full list of allowed vlans must be supplied. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_l2_interfaces
##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/bdudas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8
```
##### OS / ENVIRONMENT

```
an-nxos-02# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Documents: http://www.cisco.com/en/US/products/ps9372/tsd_products_support_series_home.html
Copyright (c) 2002-2016, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained herein are owned by
other third parties and are used and distributed under license.
Some parts of this software are covered under the GNU Public
License. A copy of the license is available at
http://www.gnu.org/licenses/gpl.html.

NX-OSv is a demo version of the Nexus Operating System

Software
  loader:    version N/A
  kickstart: version 7.3(0)D1(1)
  system:    version 7.3(0)D1(1)
  kickstart image file is: bootflash:///titanium-d1-kickstart.7.3.0.D1.1.bin
  kickstart compile time:  1/11/2016 16:00:00 [02/11/2016 10:30:12]
  system image file is:    bootflash:///titanium-d1.7.3.0.D1.1.bin
  system compile time:     1/11/2016 16:00:00 [02/11/2016 13:08:11]


Hardware
  cisco NX-OSv Chassis ("NX-OSv Supervisor Module")
  QEMU Virtual CPU version 2.5 with 3064740 kB of memory.
  Processor Board ID TM000B0000B

  Device name: an-nxos-02
  bootflash:    3184776 kB

Kernel uptime is 0 day(s), 2 hour(s), 44 minute(s), 51 second(s)


plugin
  Core Plugin, Ethernet Plugin

Active Package(s)
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: nxos
  gather_facts: false
  vars:
    new_vlans: 200

  tasks:
    - name: add vlans to allowed list
      nxos_l2_interfaces:
        config:
          - name: Ethernet2/31
            trunk:
              allowed_vlans: "{{ new_vlans }}"
        state: merged
...
```

##### RESULTS

Starting Interface Config:
```
an-nxos-02# show run interface Ethernet 2/31

!Command: show running-config interface Ethernet2/31
!Time: Wed Nov 27 15:57:00 2019

version 7.3(0)D1(1)

interface Ethernet2/31
  shutdown
  switchport
  switchport trunk native vlan 99
  switchport trunk allowed vlan 101,104-106
```
Post Job interface Config:
```
an-nxos-02# show run interface Ethernet 2/31

!Command: show running-config interface Ethernet2/31
!Time: Wed Nov 27 16:04:53 2019

version 7.3(0)D1(1)

interface Ethernet2/31
  shutdown
  switchport
  switchport trunk native vlan 99
  switchport trunk allowed vlan 200
```

```paste below
ansible-playbook 2.9.1
  config file = /Users/fubar/dev-net/nxos/ansible.cfg
  configured module search path = ['/Users/fubar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
Using /Users/fubar/dev-net/nxos/ansible.cfg as config file
host_list declined parsing /Users/fubar/dev-net/inventory/hosts as it did not pass its verify_file() method
script declined parsing /Users/fubar/dev-net/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /Users/fubar/dev-net/inventory/hosts as it did not pass its verify_file() method
Parsed /Users/fubar/dev-net/inventory/hosts inventory source with ini plugin
 _____________________________
< PLAYBOOK: allowed_vlans.yml >
 -----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

1 plays in allowed_vlans.yml
 _____________
< PLAY [nxos] >
 -------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

META: ran handlers
 __________________________________
< TASK [add vlans to allowed list] >
 ----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /Users/fubar/dev-net/nxos/allowed_vlans.yml:8
<nxos-01> ESTABLISH LOCAL CONNECTION FOR USER: fubar
<nxos-01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828 `" && echo ansible-tmp-1574871651.6025379-270697238693828="` echo /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828 `" ) && sleep 0'
<nxos-01> Attempting python interpreter discovery
<nxos-01> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<nxos-01> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /usr/local/Cellar/ansible/2.9.1/libexec/lib/python3.7/site-packages/ansible/modules/network/nxos/nxos_l2_interfaces.py
<nxos-01> PUT /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/tmpjicqhgg0 TO /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828/AnsiballZ_nxos_l2_interfaces.py
<nxos-01> EXEC /bin/sh -c 'chmod u+x /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828/ /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828/AnsiballZ_nxos_l2_interfaces.py && sleep 0'
<nxos-01> EXEC /bin/sh -c '/usr/bin/python /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828/AnsiballZ_nxos_l2_interfaces.py && sleep 0'
<nxos-01> EXEC /bin/sh -c 'rm -f -r /Users/fubar/.ansible/tmp/ansible-local-351511mqamcek/ansible-tmp-1574871651.6025379-270697238693828/ > /dev/null 2>&1 && sleep 0'
[WARNING]: The value 200 (type int) in a string field was converted to u'200' (type string). If this does not look like
what you expect, quote the entire value to ensure it does not change.

[WARNING]: Platform darwin on host nxos-01 is using the discovered Python interpreter at
/usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

changed: [nxos-01] => {
    "after": [
        {
            "name": "Ethernet2/31",
            "trunk": {
                "allowed_vlans": "200",
                "native_vlan": 99
            }
        }
    ],
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "before": [
        {
            "name": "Ethernet2/31",
            "trunk": {
                "allowed_vlans": "101,104,105,106",
                "native_vlan": 99
            }
        }
    ],
    "changed": true,
    "commands": [
        "interface Ethernet2/31",
        "switchport trunk allowed vlan 200"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "access": null,
                    "name": "Ethernet2/31",
                    "trunk": {
                        "allowed_vlans": "200",
                        "native_vlan": null
                    }
                }
            ],
            "state": "merged"
        }
    }
}
META: ran handlers
META: ran handlers
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

nxos-01 : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by danielmellado** [comment]
@trishnaguha I saw that you authored the original module. Mind taking a look? Thanks!

**Comment by ansibot** [comment]
cc @chrisvanheuveln @mikewiebe @rahushen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lkthomas** [comment]
https://docs.ansible.com/ansible/latest/modules/nxos_l2_interfaces_module.html

Document example on "merged" seem wrong as well. The "merged" state is exactly like "replaced" if you compare the change before and after.

**Comment by stephenpaynter** [comment]
I flagged this to Ansible, the Cisco command line should read

switchport trunk allowed vlan add <vlan_number>

the add keyword allows the addition off a VLAN to a trunk/port-channel without affecting any current configuration already applied.

**Comment by freemti** [comment]
as a Cisco guy, there are few things as potentially catastrophic as dropping a list of allowed vlans from an trunked interface. Logic to include handling the "add <vlan id>" logic is included somehow within the ansible code right?

**Comment by freemti** [comment]
> https://docs.ansible.com/ansible/latest/modules/nxos_l2_interfaces_module.html
> 
> Document example on "merged" seem wrong as well. The "merged" state is exactly like "replaced" if you compare the change before and after.

no it isn't, it is slightly different. afaict, the merge behavior is working fine just merging new lines alongside the old ones in the individual interface config lines. However the examples used are not good because they do not have one with an existing "switch trunk allowed vlan 1,2,3" that would show how a new vlan id 10 would be merged into that list as "switch trunk allowed vlan 1,2,3,10"

**Comment by benjdudas** [comment]
> as a Cisco guy, there are few things as potentially catastrophic as dropping a list of allowed vlans from an trunked interface. Logic to include handling the "add " is included somehow within the ansible code right?

@freemti you could use the nxos_config module:
```yaml
---
- hosts: nxos
  gather_facts: false
  vars:
    new_vlan: 104

  tasks:
    - name: add allowed vlan
      nxos_config:
        lines:
          - 'switchport trunk allowed vlan add {{ new_vlan }}'
        parents: interface Ethernet2/31
...
```

But the only way I have been able to work around it with this module is to first build the current allowed VLAN list and provide that with anything new.

```yaml
    - name: get current vlan list
      nxos_l2_interfaces:
        config:
          - name: Ethernet2/31
      register: result

    - name: set VLAN list
      set_fact:
        x_vlans: "{{ result.before[0].trunk.allowed_vlans }}"

    - name: add allowed vlan
      nxos_l2_interfaces:
        config:
          - name: Ethernet2/31
            trunk:
              allowed_vlans: '{{ x_vlans }},{{ new_vlans }}'
```

**Comment by freemti** [comment]
@benjdudas yes, I looked at some of the other modules like ios_l2_interfaces and the behavior is the same. I think this should be added as a feature request. It is not always practical or possible to have the list of exiting allowed vlans in front of you when you are putting together a playbook to add some new infrastructure. At the very least you would need to add your own programming somehow to get that info and plug it into your playbook. I am not advanced enough to know how to do that and it would seem more robust to have the interfaces module handle this job.

**Comment by hefernan** [comment]
@benjdudas ,
I have tested that workaround and it does not seem to work for me (Nexus 3172, NX-OS 9.2(2)). Moreover, if you need to add that VLAN to multiple ports (with_items or loop), it will gather the L2 information for every port (expected, I guess) every time.

The workaround renders this error:

> {{ result.before[0].trunk.allowed_vlans }}  - 'dict object' has no attribute 'trunk'.

The port is actually a trunk port.

I parsed the result and I can get information for every individual port, but I am not proficient enough in Ansible to make this work for me.

VLAN deletion must also be taken into consideration. The approach would be the same, but removing the VLAN from the VLAN list.

**Comment by benjdudas** [comment]
@hefernan When running this against a list of interfaces you're going to need to look at looping those tasks somehow. If not you are going to have some problems with building the current VLAN list. For instance:

>mod_trunk_vlans.yml
```yaml
---
- hosts: nxos
  gather_facts: false
  vars:
    interfaces:
      - Ethernet2/30
      - Ethernet2/31
    vlans: 333,334

  tasks:
    - name: modify allowed list
      include_role:
        name: trunk_vlans
      vars:
        new_vlans: "{{ vlans }}"
      loop: "{{ interfaces }}"
      loop_control:
        loop_var: sw_interface
...
```

>./roles/trunk_vlans/tasks/main.yml
```yaml
---
# tasks file for trunk_vlans
- name: get current config
  nxos_l2_interfaces:
    config:
      - name: "{{ sw_interface }}"
  register: result

- name: debug result
  debug:
    var: result

- name: collect current vlans
  set_fact:
    x_vlans: "{{ result.before[0].trunk.allowed_vlans }}"

- name: add allowed vlan
  nxos_l2_interfaces:
    config:
      - name: "{{ sw_interface }}"
        trunk:
          allowed_vlans: '{{ x_vlans }},{{ new_vlans }}'
...
```
Also, this is not the only workaround available, I was just trying to find the best way to make it work with only this module.
