### ISSUE TITLE
[import,include]_role: more clever defaults

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [ansible/ansible#65347]
##### SUMMARY

Let *handlers_from*, *defaults_from*, *vars_from* default to the same name than *tasks_from* (with fallback to *main*).

Also, if not already implemented, allow *includes* within *defaults/*, *handlers/*, *vars/* to load files from those same directories.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* import_role
* include_role

##### ADDITIONAL INFORMATION
I have in mind the use case of roles akin to other languages libraries' for "packing" related functions/features.  Within this vision I think it makes sense for _"where do we read by default?"_ (handlers, default, vars) to be aligned to the *entry tasks* file, falling back to *main* if a file by that name doesn't exist in that realm.

I even would go further since I think that this is one of the rare cases where _"less is more"_, feature-wise, and I'd retire the *handlers_from*, *defaults_from*, *vars_from* params: I can't imagine a use case where it really adds value being able to individually set those params (once my suggested defaults are in place) and quite some _"bad patterns"_ arising from their existence.

An usage example follows:
```yaml
---
- hosts: all
  tasks:
  - name: Run tasks/other.yaml instead of 'main'
    import_role:
      name: myrole
      tasks_from: other

  - import_role:
    name: myrole
```
In the first example, since *tasks_from* is *other*, *handlers_from*, *defaults_from* and *vars_from* would also default to *other*, falling back to *main* if *other* doesn't exist.

The second example, without *tasks_from* being set, would be functionally-wise the same: since the default for *tasks_from* is *main*, it would also load *main* from *defaults/*, *vars/* and *handlers/* just as it is already the case, thus guaranteeing backwards compatibility.

In the *"role as a library"* use case, it naturally rises the situation where some variables are shared among different _"task groups"_: let's think of a role with network-aware tasks, i.e.: some AWS-related tasks; all of them may share connection params, so being able to do the following  would make sense:

At *defaults/other.yml*
```yaml
---
# defaults for other

a_var: 'some_default'
another_var: []

include: common_vars.yml
```

...and then, in *defaults/common_vars.yml*
```yaml
---
# shared vars

common_var_1: 'default_value_1'
common_var_2: 'default_value_2'
```
In this case, the current behaviour wouldn't change either, since the default role invocation (either from the *roles:* section or [import,include]_role without *tasks_from* being set, would read only *main.yml* from each section (unless *main.yml* also includes some other file).
