### ISSUE TITLE
postgresql_query doesn't support non-ASCII characters in SQL files with Python3

### ISSUE THREAD

**Issue by rtsisyk** [ansible/ansible#65367]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/roman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Local:

```
NAME=Fedora
VERSION="31 (Workstation Edition)"
```

Remote:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
```

All managed hosts are RHEL 8 (Python3 only):

hosts.yml:
```
all:
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
```

##### STEPS TO REPRODUCE

main.yml:

```yaml
- name: "Copy files with scheme"
  copy:
    src: "scheme.sql"
    dest: "/tmp/scheme.sql"
    mode: '0600'

- name: "Create scheme"
  postgresql_query:
    login_user: "{{ postgresql_user }}"
    login_password: "{{ postgresql_password }}"
    login_host: "{{ postgresql_host }}"
    db: "{{ postgresql_database }}"
    path_to_script: "/tmp/scheme.sql"
```

scheme.sql:
```
INSERT INTO test(id, name) VALUES(1,  'Данные'); -- use non-ASCII
```

##### EXPECTED RESULTS

scheme.sql applied.

##### ACTUAL RESULTS

```paste below
"msg": "Cannot read file '/tmp/scheme.sql' : 'ascii ' codec can't decode byte 0xd0 in position 4342: ordinal not in range(128)"}  
```
