### ISSUE TITLE
Cannot flush_handlers in role

### ISSUE THREAD

**Issue by herealways** [ansible/ansible#65389]
##### SUMMARY

I want to flush handlers in role/myrole/tasks/main.yml but it does not work

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role, meta

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

centos7 

##### STEPS TO REPRODUCE

```yaml

cat test_role.yml
- hosts: vm
  gather_facts: no
  tasks:
  - include_role:
      name: 1_role

cat roles/1_role/tasks/main.yml
- debug: 
    msg: "unchanged"
  notify: test handler

- name: exec handlers even the task is unchanged
  meta: "flush_handlers"

cat roles/1_role/handlers/main.yml
- name: test handler
  shell: "echo handler exec"

ansible_playbook test_role.yml

```

##### EXPECTED RESULTS

the handler is executed even the dubug module return 'ok' state because of the "flush_handlers"

##### ACTUAL RESULTS

```paste below
PLAY [vm] *************************************************************************************************

TASK [include_role : 1_role] ******************************************************************************

TASK [1_role : debug] *************************************************************************************
ok: [192.168.204.202] => {
    "msg": "unchanged"
}
ok: [192.168.204.132] => {
    "msg": "unchanged"
}

PLAY RECAP ************************************************************************************************
192.168.204.132            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.204.202            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
