### ISSUE TITLE
Group vars overwritten when a host is in multiple inventories

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#6538]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.5.3
##### Environment:

Debian, but shouldn't matter
##### Summary:

Ansible seems to be wrecking inventory vars when a host appears in multiple groups. It looks like it is impossible to figure out which vars it will use if you have a single host in multiple hostgroups.
##### Steps To Reproduce:

Run this playbook with the provided inventory:

Inventory file:

``` ini
[a_local]
localhost

[b_local]
localhost

[c_local]
localhost

[a_local:vars]
foo=one

[b_local:vars]
foo=two

[c_local:vars]
foo=three
```

Playbook:

``` yaml
- hosts: a_local
  gather_facts: no
  tasks: [{debug: var=foo}]

- hosts: b_local
  gather_facts: no
  tasks: [{debug: var=foo}]

- hosts: c_local
  gather_facts: no
  tasks: [{debug: var=foo}]
```
##### Expected Results:

The debug prompt should show 'one', then 'two', then 'three'.
##### Actual Results:

```
$ ansible-playbook -i inventory.ini -c local site.yaml                                                                                                             +[master]

PLAY [a_local] **************************************************************** 

TASK: [debug var=foo] ********************************************************* 
ok: [localhost] => {
    "foo": "three"
}

PLAY [b_local] **************************************************************** 

TASK: [debug var=foo] ********************************************************* 
ok: [localhost] => {
    "foo": "three"
}

PLAY [c_local] **************************************************************** 

TASK: [debug var=foo] ********************************************************* 
ok: [localhost] => {
    "foo": "three"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
