### ISSUE TITLE
non-IOS devices does not show running-config

### ISSUE THREAD

**Issue by vijaychebium** [ansible/ansible#65401]
##### SUMMARY

Ansible fail to run  show running-config on non-IOS device.
Note: The non-IOS device can take show command and config command. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

/usr/lib/python2.7/dist-packages/ansible/plugins/connection/ios.py

##### ANSIBLE VERSION
```
ansible --version
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
```

##### CONFIGURATION
```yaml
- hosts: ims_ops
  connection: network_cli
  gather_facts: false
  become: true
  become_method: enable
  tasks:
   - name: SMF_ims backup 
     ios_command: 
        commands: show running-config
     

```

##### OS / ENVIRONMENT
Linux
Network Device : NON - IOS device but has commands like show, config.

##### STEPS TO REPRODUCE
```yaml
- hosts: ims_ops
  connection: network_cli
  gather_facts: false
  become: true
  become_method: enable
  tasks:
   - name: backup
     ios_command: 
        commands: show running-config
     
```

##### EXPECTED RESULTS
show running-config 

##### ACTUAL RESULTS
```paste below
PLAY [ims_ops] ******************************************************************************************************************************
META: ran handlers

TASK [SMF_ims backup] ***********************************************************************************************************************
task path: /home/vijay/Documents/ansible_scripts/test.yml:7
<10.240.250.43> attempting to start connection
<10.240.250.43> using connection plugin network_cli
<10.240.250.43> local domain socket does not exist, starting it
<10.240.250.43> control socket path is /home/vijay/.ansible/pc/80fab2723b
<10.240.250.43> local domain socket listeners started successfully
<10.240.250.43> loaded cliconf plugin for network_os ios
<10.240.250.43> 
<10.240.250.43> local domain socket path is /home/vijay/.ansible/pc/80fab2723b
fatal: [ims]: FAILED! => {
    "changed": false, 
    "msg": "unable to set terminal parameters"
}

PLAY RECAP **********************************************************************************************************************************
ims     



```
