### ISSUE TITLE
nios_host_record is not idempotent

### ISSUE THREAD

**Issue by tsvsj** [ansible/ansible#65453]
##### SUMMARY
The module nios_host_record is not idempotent. It will always create a new, even duplicated, host record. From my understanding that is not the way it should be. To me it doesn't make any sense to create a new host record, if the name already exists. Unfortunately the NIOS does allow this configuration. You can even configure the same host record several time, on the same IP address.

However, I think this should be avoided when it comes to automation. I need to build idempotent playbooks, which do not register a new host each time.

As a workaround I'm doing pre-checks, using the nios lookup module and skip the tasks, if there is already a host registered. Unfortunately the nios lookup module has some format issue in the response (https://github.com/ansible/ansible/issues/65452), which makes it hard to validate, if there is already a host record registered or not.

##### ISSUE TYPE
- Bug Report
- Enhancement
- Feature Request

##### COMPONENT NAME
nios_host_record

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /Users/.../ansible.cfg
  configured module search path = [u'/Users/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/.../Ansible/ansible-dev/lib/python2.7/site-packages/ansible
  executable location = /Users/.../Ansible/ansible-dev/bin/ansible
  python version = 2.7.16 (default, Oct 17 2019, 17:14:30) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
DEFAULT_STDOUT_CALLBACK(/Users/.../ansible.cfg) = yaml
```

##### STEPS TO REPRODUCE
Just run the task in combination with the lookup module:
```
- nios_host_record:
    name: "www.example.com"
    ipv4addrs:
      - configure_for_dhcp: false
        ipv4addr: "{{ lookup('nios_next_ip', '1.1.1.0/24', exclude=nios_network_excludes, provider=nios_provider)[0] }}"
    configure_for_dns: no
    view: "{{ nios_network_view }}"
    provider: '{{ nios_provider }}'
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS
Check if `name` is already registered (maybe using the nios lookup module). If yes, take the address from the already registered host as `ipv4addr` and execute task. If no, receive next available address from lookup, set it as `ipv4addr` and execute task.

##### ACTUAL RESULTS
An additional host record ist registered with the received address from the nios_next_ip lookup module. Each execution results in a new host record registration, with a new address.
