### ISSUE TITLE
Lookup nios.py return value type is mixed

### ISSUE THREAD

**Issue by tsvsj** [ansible/ansible#65452]
##### SUMMARY
When using the lookup plugin for Infoblox NIOS, nios.py, I see inconsistent behavior of the return values from the module. I'm using the lookup to check if the host, that I'm planning to deploy, is not already registered. Unfortunately the response from the lookup differs, based on the number of returned host records.

If there is just one host record, the returned value type is dict:
```
nios_host_record:
  _ref: record:host/...:www.example.com/%20
  ipv4addrs:
  - _ref: record:host_ipv4addr/...:1.1.1.1/www.example.com/%20
    host: www.example.com
    ipv4addr: 1.1.1.1
```
The result of {{ nios_host_record | length }} is 2.

If there are more than one host records, the returned value type is a list:
```
nios_host_record:
  - _ref: record:host/...:www.example.com/%20
    ipv4addrs:
    - _ref: record:host_ipv4addr/...:1.1.1.1/www.example.com/%20
      host: www.example.com
      ipv4addr: 1.1.1.1
  - _ref: record:host/...:www.example.com/%20
    ipv4addrs:
    - _ref: record:host_ipv4addr/...:1.1.1.2/www.example.com/%20
      host: www.example.com
      ipv4addr: 1.1.1.2
  - _ref: record:host/...:www.example.com/%20
    ipv4addrs:
    - _ref: record:host_ipv4addr/...:1.1.1.3/www.example.com/%20
      host: www.example.com
      ipv4addr: 1.1.1.3
```
The result of {{ nios_host_record | length }} is 3.

As I was not able to find a consistent way to check, whether the response is of type list or dict. I've tried to generate a list from the lookup command.
```
"{{ [lookup('nios', 'record:host', filter={'name': 'www.example.com'}, provider=nios_provider, return_fields=['ipv4addrs.ipv4addr','ipv4addrs.host']) | from_yaml] | default([]) }}"
```
This wraps the reponse into a list, but if the response is already a list (more than 1 host record returned), it will still be nested into this list.

It would be great, to have the lookup module evaluating the response and always respond with a list, even if there is just one host record returned.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios.py

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /Users/.../ansible.cfg
  configured module search path = [u'/Users/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/.../Ansible/ansible-dev/lib/python2.7/site-packages/ansible
  executable location = /Users/.../Ansible/ansible-dev/bin/ansible
  python version = 2.7.16 (default, Oct 17 2019, 17:14:30) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
DEFAULT_STDOUT_CALLBACK(/Users/.../ansible.cfg) = yaml
```

##### STEPS TO REPRODUCE
Run the tasks with 0, 1 and 2 host records created within the Infoblox.
```
- set_fact:
    nios_host_record: "{{ [lookup('nios', 'record:host', filter={'name': 'www.example.com'}, provider=nios_provider, return_fields=['ipv4addrs.ipv4addr','ipv4addrs.host']) | from_yaml] | default([]) }}"
  delegate_to: localhost

- debug:
    var: nios_host_record
  delegate_to: localhost
```

##### EXPECTED RESULTS
Return values of the lookup:
```
0 = empty list
1 = list with 1 element
2 = list with 2 elements
```

##### ACTUAL RESULTS
Return values of the lookup:
```
0 = empty var/string
1 = dict
2 = list with 2 elements
```
