### ISSUE TITLE
docker_container using image digest doesn't recreate container when digest changes

### ISSUE THREAD

**Issue by bjornicus** [ansible/ansible#65486]
##### SUMMARY
when a docker container is started using the image digest instead of a tag, and then the digest is changed, the container is not recreated

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.8.7
  config file = /home/vagrant/.ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/vagrant/.ansible.cfg) = -o StrictHostKeyChecking=no
DEFAULT_LOOKUP_PLUGIN_PATH(/home/vagrant/.ansible.cfg) = [u'/home/vagrant/.ansible/plugins/lookup', u'/usr/share/ansible/plugins/lookup', u'/home/vagrant/source/infra/deployment/playbooks/services/lookup_plugins']
DEFAULT_REMOTE_USER(/home/vagrant/.ansible.cfg) = hoylu
DEFAULT_ROLES_PATH(/home/vagrant/.ansible.cfg) = [u'/home/vagrant/ansible-roles']
DEFAULT_SCP_IF_SSH(/home/vagrant/.ansible.cfg) = True
DEFAULT_TRANSPORT(/home/vagrant/.ansible.cfg) = ssh
```

##### OS / ENVIRONMENT
Linux ubuntu-xenial
Docker version 19.03.5

##### STEPS TO REPRODUCE
run the following playbook
```yaml
- name: test start container by digest, then update
  hosts: localhost
  tasks:
    - name: start busybox 1.31.0 by sha
      docker_container:
        name: "test-busybox"
        image: "busybox@sha256:fe301db49df08c384001ed752dff6d52b4305a73a7f608f21528048e8a08b51e"
        pull: yes
        state: started
        command: sleep 30
    - name: start busybox 1.31.1 by sha
      docker_container:
        name: "test-busybox"
        image: "busybox@sha256:1828edd60c5efd34b2bf5dd3282ec0cc04d47b2ff9caa0b6d4f07a21d1c08084"
        pull: yes
        state: started
        command: sleep 30
```

##### EXPECTED RESULTS
the container should get re-created in the second task
##### ACTUAL RESULTS
the container is unchanged by the second task
```paste below
TASK [start busybox 1.31.0 by sha] ***********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [start busybox 1.31.1 by sha] ***********************************************************************************************************************************************************************************************************
ok: [localhost]

```
