### ISSUE TITLE
Add Support for ICMP Protocol when creating rules using azure_rm_securitygroup

### ISSUE THREAD

**Issue by deano2point0** [ansible/ansible#65501]
##### SUMMARY

Azure securitygroups now support creating rules for the ICMP protocol when creating rules via the Azure portal, but Ansible doesn't seem to support this currently. 

It would be great if azure_rm_securitygroup could support this new option 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_securitygroup

##### ADDITIONAL INFORMATION

This would be used to easily create NSG rules on Azure that allow ICMP ping without opening up access to TCP and UDP

```yaml
 - name: Create My Azure Security group
    azure_rm_securitygroup:
      name: my-azure-sec-group
      resource_group: my-azure-rsg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
        - name: ICMP PING
          protocol: ICMP
          priority: 102
```
