### ISSUE TITLE
error using variable from set_fact in hosts

### ISSUE THREAD

**Issue by atimonin** [ansible/ansible#65512]
##### SUMMARY

When use variable in hosts: i get an error:
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'standby_nns' is undefined

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

maybe in set_fact
##### ANSIBLE VERSION

```paste below
ansible 2.8.6
  config file = /home/atimonin/.ansible.cfg
  configured module search path = [u'/home/atimonin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_NOCOWS(/home/atimonin/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/atimonin/.ansible.cfg) = True
DEFAULT_FILTER_PLUGIN_PATH(/home/atimonin/.ansible.cfg) = [u'/home/atimonin/filter_plugins']
DEFAULT_FORKS(/home/atimonin/.ansible.cfg) = 20
DEFAULT_GATHERING(/home/atimonin/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/atimonin/.ansible.cfg) = [u'/home/atimonin/src/crpt/motp-ansible/motp-inven
DEFAULT_MANAGED_STR(/home/atimonin/.ansible.cfg) = Ansible managed: file modified on %Y-%m-%d %H:%M
DEFAULT_ROLES_PATH(/home/atimonin/.ansible.cfg) = [u'/home/atimonin/roles']
DEFAULT_SCP_IF_SSH(/home/atimonin/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/atimonin/.ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/atimonin/.ansible.cfg) = 60
HOST_KEY_CHECKING(/home/atimonin/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/atimonin/.ansible.cfg) = /usr/bin/python3
RETRY_FILES_SAVE_PATH(/home/atimonin/.ansible.cfg) = /home/atimonin/retry
```

##### OS / ENVIRONMENT

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

##### STEPS TO REPRODUCE

run a like playbook

```yaml
- hosts: hdfs-namenodes[0]

  vars:
    env_name: default
  
  tasks:
  - name: get active NN
    shell: >
      {{ hadoop_distr_prefix }}-{{ env_name }}-current/bin/hdfs haadmin -getAllServiceState |
      awk '$2=="active" {split($1,f,":"); print f[1]}'
    register: get_active_nn
    check_mode: no

  - name: set as var
    set_fact:
      active_nn: "{{ get_active_nn.stdout }}"
      standby_nns: "{{ groups['hdfs-namenodes'] | difference(get_active_nn.stdout) }}"

  - name: print active NN
    debug:
      msg: "Active: {{ active_nn }} Standby: {{ standby_nns }}"

- hosts: "{{ standby_nns }}"
  become: yes
  serial: 1
  vars:
    env_name: default
  roles:
  - role: hadoop
  - role: hdfs-zkfc
```

##### EXPECTED RESULTS

playbook at least run

##### ACTUAL RESULTS

```paste below
PLAY [hdfs-namenodes[0]] **************************************************************************

TASK [Gathering Facts] ****************************************************************************
ok: [hbase01.lt02.gismt.crpt.tech]

TASK [get active NN] ******************************************************************************
changed: [hbase01.lt02.gismt.crpt.tech]

TASK [set as var] *********************************************************************************
ok: [hbase01.lt02.gismt.crpt.tech]

TASK [print active NN] ****************************************************************************
ok: [hbase01.lt02.gismt.crpt.tech] => {}

MSG:

Active: hbase01.lt02.gismt.crpt.tech Standby: [u'hbase02.lt02.gismt.crpt.tech']

ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'standby_nns' is undefined

The error appears to be in '/home/atimonin/src/crpt/DevOps/setup-and-configuration/hadoop-cluster/hadoop-upgrade-standby_NN.yml': line 29, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- hosts: "{{ standby_nns }}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```
