### ISSUE TITLE
Upgrade to version 2.9 seems to break proxysql_backend_servers module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#65525]
##### SUMMARY
Upgrade to version 2.9 seems to break proxysql_backend_servers module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxysql_backend_servers

##### ANSIBLE VERSION
```
2.9.1-1ppa~xenial
```

##### CONFIGURATION
``` 
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Both control host and target host running:
Ubuntu 16.04.6 LTS \n \l
Linux sqlproxy1 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
Receiving an "integer expected but got string instead" error after upgrading to 2.9. Downgrading to 2.8 solves the problem

```
- name: PROXYSQL Bring MySQL slave server offline gracefully in ProxySQL
      proxysql_backend_servers:
        login_user: "{{ proxysql_admin_user }}"
        login_password: "{{ proxysql_admin_password }}"
        hostname: "{{ slave_IP }}"
        state: present
        status: 'OFFLINE_SOFT'
        hostgroup_id: 1
        save_to_disk: yes
        load_to_runtime: yes
```

##### EXPECTED RESULTS
Expect ProxySQL to change the host status to OFFLINE_SOFT

##### ACTUAL RESULTS
proxysql_backend_servers module breaks and fails to connect run the needed command. 
```
fatal: [sqlprox1]: FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to 10.1.100.100 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/leandro.morgado/.ansible/tmp/ansible-tmp-1575486348.07-108679889387001/AnsiballZ_proxysql_backend_servers.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/leandro.morgado/.ansible/tmp/ansible-tmp-1575486348.07-108679889387001/AnsiballZ_proxysql_backend_servers.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/leandro.morgado/.ansible/tmp/ansible-tmp-1575486348.07-108679889387001/AnsiballZ_proxysql_backend_servers.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.database.proxysql.proxysql_backend_servers', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_0AQ1eX/ansible_proxysql_backend_servers_payload.zip/ansible/modules/database/proxysql/proxysql_backend_servers.py\", line 505, in <module>\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_0AQ1eX/ansible_proxysql_backend_servers_payload.zip/ansible/modules/database/proxysql/proxysql_backend_servers.py\", line 466, in main\r\n  File \"/tmp/ansible_proxysql_backend_servers_payload_0AQ1eX/ansible_proxysql_backend_servers_payload.zip/ansible/modules/database/proxysql/proxysql_backend_servers.py\", line 262, in check_server_config\r\nTypeError: tuple indices must be integers, not str\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```
