### ISSUE TITLE
lookup ('url',...) does not accept openssl 

### ISSUE THREAD

**Issue by jensbaitingerbosch** [ansible/ansible#65549]
##### SUMMARY
We have a corporate proxy that terminates tls connections and looks into the content and then reencrypts and presents its own certificate. In principle its an enterprise-man-in-the-middle attack .

The consequence is that each tool that does https connections needs to accepts the proxy certificate or ignore the certificate at all (Which is not secure at all). We installed the proxy root certificate [where openssl expects it](https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate) and most tools like cURL, wget, apt,... accept connections via the proxy. 

Tasks that uses lookup('url','https://...') to query an external https URL fails with the certification verification.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lookup plugin url

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/jenkins_home/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### CONFIGURATION

```
<empty>
```

##### OS / ENVIRONMENT

Linux 1b223c2b2edc 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

This task (from https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/preflight.yml) fails: 

```yaml
- name: "Get checksum for {{ go_arch }} architecture"
  set_fact:
    prometheus_checksum: "{{ item.split(' ')[0] }}"
  with_items:
    - "{{ lookup('url', 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version + '/sha256sums.txt', wantlist=True) | list }}"
  when: "('linux-' + go_arch + '.tar.gz') in item"
```

##### EXPECTED RESULTS
the file is downloaded 

##### ACTUAL RESULTS

```paste below
TASK [cloudalchemy.prometheus : Get checksum for amd64 architecture] ***********
fatal: [prometheus1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed lookup url for https://github.com/prometheus/prometheus/releases/download/v2.13.0/sha256sums.txt : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>"}
```
