### ISSUE TITLE
unixy callback duplicates entries in log

### ISSUE THREAD

**Issue by dkossako** [ansible/ansible#65561]
##### SUMMARY
When using such task items on output are duplicated.
```
  - name: Prepare static directories
    action: file path={{ item }} state=directory owner={{ owner }} group={{ owner }} mode=0750
    with_items:
      - "/opt/backups/{{ target_server }}/{{ site_name }}"
      - "/opt/files/{{ site_name }}"
    when: skip_create_files_dir is undefined or skip_create_files_dir != "1"
```
Using default output:

> 10:07:25  TASK [d-deploy-new : Prepare directories for EFS] ******************************
> 10:07:26  changed: [web-01] => (item=/opt/files/domain.pl/files)
> 10:07:26  changed: [web-01] => (item=/opt/files/domain.pl/private_files)

Using unixy:

> 14:48:22  Prepare directories for EFS...
> 14:48:22    web-01 done
> 14:48:23    web-01 done
> 14:48:23    web-01 done
> 14:48:23    web-01 ok

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unixy callback

##### ANSIBLE VERSION

```
ansible 2.9.1
```

##### CONFIGURATION

```
# empty
```

##### OS / ENVIRONMENT
```
$ uname -a
Linux dkossako-dell 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.2
DISTRIB_CODENAME=tina
DISTRIB_DESCRIPTION="Linux Mint 19.2 Tina"

$ python --version
Python 2.7.15+
```

##### STEPS TO REPRODUCE
```
export ANSIBLE_STDOUT_CALLBACK=unixy
ansible-playbook [...]
```

##### EXPECTED RESULTS
> 14:48:22  Prepare directories for EFS...
> 14:48:22    web-01 done
> 14:48:23    web-01 ok

##### ACTUAL RESULTS
> 14:48:22  Prepare directories for EFS...
> 14:48:22    web-01 done
> 14:48:23    web-01 done
> 14:48:23    web-01 done
> 14:48:23    web-01 ok
