### ISSUE TITLE
VMWare VM Inventory Plugin Host Filters

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#65571]
##### SUMMARY

Add ability to filter down results when using the vmware_vm_inventory plugin

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_vm_inventory

##### ADDITIONAL INFORMATION

The older vmware_inventory.py script had the ability to filter down hosts based on "host_filters". Please implement a similar feature into the vmware_vm_inventory plugin.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/inventory/vmware_vm_inventory.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/vmware_vm_inventory.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/support/integration/plugins/inventory/vmware_vm_inventory.py`](https://github.com/ansible/ansible/blob/devel/test/support/integration/plugins/inventory/vmware_vm_inventory.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible-collections/vmware/pull/137

**Comment by Akasurde** [comment]
User can use `filters` to filter host using inventory plugin like following example - 

```yaml
plugin: community.vmware.vmware_vm_inventory
strict: False
hostname: 10.65.223.31
username: administrator@vsphere.local
password: Esxi@123$%
validate_certs: False
properties:
- runtime.powerState
- config.name
filters:
- runtime.powerState == "poweredOn"
hostnames:
- config.name
```
