### ISSUE TITLE
Sysctl module should add {{ ansible_managed }} to managed files

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible/ansible#65572]
##### SUMMARY

When changing sysctl parameters with the sysctl module, this will create new files or edit existing ones. However, these files are not marked with {{ ansible_managed }} to discourage local edits.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

sysctl
##### ADDITIONAL INFORMATION

I feel that all files that are touched/managed by Ansible should contain a notice, discouraging local admins/users from changing them.

```yaml
# Set kernel.panic to 3 in /tmp/test_sysctl.conf
- sysctl:
    name: kernel.panic
    value: '3'
    sysctl_file: /etc/sysctl.d/test_sysctl.conf
```
The above task results in a file as follows:

```
kernel.panic=3
```

While I feel this is better:
```
# This file is managed using Ansible, all your changes will be lost!
# DO NOT EDIT
kernel.panic=3
```
