### ISSUE TITLE
tower_workflow_template does not configure a workflow from a valid schema file

### ISSUE THREAD

**Issue by vvaldez** [ansible/ansible#65577]
##### SUMMARY
Module `tower_workflow_template` does not build workflow from schema file

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-tower
tower_workflow_template

##### ANSIBLE VERSION
```
[root@tower tmp]# tower-cli --version
Tower CLI 3.3.0
[root@tower tmp]# ansible --version
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.7 (Maipo)

##### STEPS TO REPRODUCE
Given schema file:
```
[root@tower tmp]# cat deploy_all_workflow_schema.yaml 
---
- job_template: Template 1
  success:
  - job_template: Template 2
    success:
    - job_template: Template 3
      success:
      - job_template: template 4
```

Using a task such as:

```
- name: Add workflow template
  tower_workflow_template:
    name: "{{ tower_config_workflow_template_deploy.name }}"
    description: "{{ tower_config_workflow_template_deploy.description }}"
    schema: /tmp/deploy_all_workflow_schema.yaml
    organization: "{{ tower_org }}"
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: "{{ tower_host }}"
```

Result:

```
changed: [pool5-tower.practice.redhat.com] => {
    "changed": true, 
    "id": 35, 
    "invocation": {
        "module_args": {
            "allow_simultaneous": null, 
            "ask_extra_vars": null, 
            "ask_inventory": null, 
            "description": "Deploy all components", 
            "extra_vars": null, 
            "inventory": null, 
            "name": "Deploy All", 
            "organization": "Default", 
            "schema": "/tmp/deploy_all_workflow_schema.yaml", 
            "state": "present", 
            "survey": null, 
            "survey_enabled": null
        }
    }, 
    "state": "present", 
    "workflow_template": "Deploy All"
}
```

Seems to complete, but when looking at the workflow visualizer or tower-cli workflow schema of the workflow shows nothing:

```
[root@tower ~]# tower-cli workflow schema "Deploy All" 
[]
```

Using tower-cli on the exact same file does work:

```
[root@tower tmp]# tower-cli workflow schema "Deploy All" @deploy_all_workflow_schema.yaml 
- id: 15
  job_template: 26
  success_nodes:
  - id: 16
    job_template: 29
    success_nodes:
    - id: 17
      job_template: 27
      success_nodes:
      - id: 18
        job_template: 23
```

##### EXPECTED RESULTS
Module should build workflow as described in schema, as tower-cli does.

##### ACTUAL RESULTS
No workflow is built when using module.
