### ISSUE TITLE
sns_topic: add support to tags

### ISSUE THREAD

**Issue by aldobongio** [ansible/ansible#65613]
##### SUMMARY
The `sns_topic` module should include a `tags` parameter for attaching AWS tags

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
module/sns_topic

##### ADDITIONAL INFORMATION
Other AWS modules such as `ec2` and `s3_bucket` include parameters (respectively `instance_tags` and `tags`) for attaching AWS tags.

```yaml
-  sns_topic:
    name: "alarms"
    state: present
    tags:
     Environment: Production

```
