### ISSUE TITLE
[vmware_guest] windows: add support for autounattend.xml / floppy

### ISSUE THREAD

**Issue by DevFinGitGovSecChatOps** [ansible/ansible#65611]
##### SUMMARY

To create a windows template, an autounattend.xml file is needed. Usually it is provided with a floppy drive. Since there is no support for floppy drives in this module, there should be one. Optionally a method to directly specify an xml file could be implemented.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_guest

##### ADDITIONAL INFORMATION

This feature would be used to provide the os installation routine with a confuguration file in order to automate the installation.

This feature is similar to linux kickstart files, so a generic solution would be preferable

```yaml
    - name: create template vm
      vmware_guest:
        ...
        name: "{{ inventory_hostname }}"
        guest_id: "{{ vm_guest_id }}"
        cdrom:
          type: iso
          iso_path: "[datastore] windows.iso"
        floppy:
          floppy_path: "[datastore] floppy.flp"
        ...
        state: poweredon
```
or
```yaml
    - name: create template vm
      vmware_guest:
        ...
        name: "{{ inventory_hostname }}"
        guest_id: "{{ vm_guest_id }}"
        cdrom:
          type: iso
          iso_path: "[datastore] windows.iso"
        kickstart:
          kickstart_path: "[datastore] autounattend.xml"
        ...
        state: poweredon
```
