### ISSUE TITLE
VMware: No URL parameter for 'vmware_deploy_ovf' module.

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#65648]
#### SUMMARY
No option to specify URL based http link to OVA in vmware_deploy_ovf module.

##### ISSUE TYPE
- Currently only Path to OVF or OVA file to deploy is supported
- But VMware supports both absolute path and URL based deployment. Hence some option should be there to pass the URL for the deployment. So that manually no need to download the file on the system.

##### COMPONENT NAME
vmware_deploy_ovf

##### ADDITIONAL INFORMATION
Instead of downloading the OVA locally in the provision server if some one will provide the URL on the provision server, ansible should be able to download it and then continue with deployment.

- Current Playbook:

```
---
- name: Ubuntu based Provision server deployment
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_var.yml
  tasks:
    - name: VM Deployment from OVA
      vmware_deploy_ovf:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        datastore: '{{ vsphere_datastore }}'
        name: '{{ vsphere_vm_name }}'
        disk_provisioning: 'thin'
        validate_certs: 'no'
        networks: "{u'VM Network':u'{{ vsphere_network }}'}"
        power_on: 'yes'
        fail_on_spec_warnings: 'yes'
        wait_for_ip_address: 'no'
        ovf: '/root/ISO/Ubuntu-18.04.ova'         <<<< Current Method
      delegate_to: localhost
```

- Future Playbook:

```
---
- name: Ubuntu based Provision server deployment
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_var.yml
  tasks:
    - name: VM Deployment from OVA
      vmware_deploy_ovf:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        datastore: '{{ vsphere_datastore }}'
        name: '{{ vsphere_vm_name }}'
        disk_provisioning: 'thin'
        validate_certs: 'no'
        networks: "{u'VM Network':u'{{ vsphere_network }}'}"
        power_on: 'yes'
        fail_on_spec_warnings: 'yes'
        wait_for_ip_address: 'no'
        ova_url: 'http://xxx.xxx.xxx.xxx/ova/Ubuntu-18.04.ova'        <<<< Future Method
      delegate_to: localhost
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_deploy_ovf.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Udayendu: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Udayendu, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Udayendu** [comment]
Not necessarily but it may require an additional `ova_storage` parameter to download the OVA in the provision server and then start the deployment. So the playbook may look like:

```
---
- name: Ubuntu based Provision server deployment
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_var.yml
  tasks:
    - name: VM Deployment from OVA
      vmware_deploy_ovf:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        datastore: '{{ vsphere_datastore }}'
        name: '{{ vsphere_vm_name }}'
        disk_provisioning: 'thin'
        validate_certs: 'no'
        networks: "{u'VM Network':u'{{ vsphere_network }}'}"
        power_on: 'yes'
        fail_on_spec_warnings: 'yes'
        wait_for_ip_address: 'no'
        ova_url: 'http://xxx.xxx.xxx.xxx/ova/Ubuntu-18.04.ova'          // New Parameter //
        ova_storage: '/root/ISO'                                                       // New Parameter //
      delegate_to: localhost
```

And depending on space customer should define this location.
