### ISSUE TITLE
azure_rm_galleryimageversion is not updating the tags

### ISSUE THREAD

**Issue by singhujjwal** [ansible/ansible#65691]
SUMMARY
Module azure_rm_galleryimageversion does not update the tags on the image version object

ISSUE TYPE
Bug Report
COMPONENT NAME
azure_rm_galleryimageversion 

ANSIBLE VERSION
====================
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ujjwal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]

STEPS TO REPRODUCE
Run playbook below 

# cat playbook.yml

```yaml
---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Promote the  image to gallery
      azure_rm_galleryimageversion:
        resource_group: "sig-resource-group"
        gallery_name: "galery-name"
        gallery_image_name: "image-name"
        name: "{{ '%y.%m.%d%H%M' | strftime(ansible_date_time.epoch) }}"
        location: "southcentralus"
        publishing_profile:
          end_of_life_date:
            "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch|int + 60*86400) }}"
          exclude_from_latest: yes
          replica_count: 1
          storage_account_type: Standard_LRS
          target_regions:
            - name: South Central US
              regional_replica_count: 1
              storage_account_type: Standard_LRS
          managed_image:
            name: "image-name"
            resource_group: "image-resource-group"
        tags: "{'Name':'Value'}"
```

EXPECTED RESULTS

The image in the shared image gallery should be tagged

ACTUAL RESULTS

No tags appears on shared images
