### ISSUE TITLE
sros_config taking too long to configure a single device (over 30 minutes)

### ISSUE THREAD

**Issue by cwiech** [ansible/ansible#65695]
##### SUMMARY

When configuring nokia routers using the sros_config module it is taking 37 minutes to load a config with 13k lines of config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

sros_config 

##### ANSIBLE VERSION

```paste below

ansible 2.9.2
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]


ansible 2.7.3
  config file = /Users/cc/git/ansible/ansible.cfg
  configured module search path = ['/Users/cc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.3/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 28 2018, 11:51:54) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
2.9.2:
vagrant@ubuntu-bionic:~$ ansible-config dump --only-changed
vagrant@ubuntu-bionic:~$ 

2.7.3:
DEFAULT_STDOUT_CALLBACK(/Users/cc/git/ansible/ansible.cfg) = full_skip
HOST_KEY_CHECKING(/Users/cc/git/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/cc/git/ansible/ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/Users/cc/git/ansible/ansible.cfg) = 320

```

##### OS / ENVIRONMENT

I am seeing similar performance problems using the following:
operating systems: OSX, linux (ubuntu 18)
sros version: 14.0R8, 16.0.R4
ansible version: 2.7.3, 2.9.2 (NOTE that 2.8 had a bug and sros_config failed)

##### STEPS TO REPRODUCE

This can be reproduced using the sros_config module and a large source file (in my case I has 13k lines of configuration).

```yaml
- hosts: aluvm1
  gather_facts: no
  connection: network_cli
  tasks:

  - name: load nokia config
    sros_config:
      src: "files/aluvm1-fullconfig"
      match: none
    vars:
      ansible_command_timeout: 60


time ansible-playbook -i hosts testconfigs.yml 

PLAY [aluvm1] *******************************************************************************************

TASK [load nokia config] ****************************************************************************
changed: [aluvm1]

PLAY RECAP **********************************************************************************************
aluvm1                     : ok=1    changed=1    unreachable=0    failed=0   

real	37m57.125s


wc ../files/aluvm1-fullconfig 
   12882   30553  488015 ../files/aluvm1-fullconfig

```

##### EXPECTED RESULTS

The command takes 37 minutes to run. NOTE that on ansible 2.9.2 it took loner (85 minutes)

##### ACTUAL RESULTS

The play completes, but it takes so long its unusable in real life.

```paste below
Here is the command running with 2.9.2

time ansible-playbook -i hosts testconfigs.yml 

TASK [load nokia config] *********************************************************************************************

^[[D
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host nokiavalidator1 should use /usr/bin/python3, but is using 
/usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using 
the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature 
will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
changed: [nokiavalidator1]


PLAY RECAP ***************************************************************************************************************
nokiavalidator1            : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


real	85m11.157s


wc ../files/nokiavalidator-fullconfig 
  8348  22282 328938 ../files/nokiavalidator-fullconfig

```
