### ISSUE TITLE
user.py PR45507 broke update_password="on_create"

### ISSUE THREAD

**Issue by HRio** [ansible/ansible#65711]
##### SUMMARY

The merge of #45507 broke `update_password="on_create"` on Alpine Linux with the shadow package installed.

This does not work anymore
```yml
  - name: add users                                                                                                                                                                                                                                  
    user:
      name: "{{ item.name }}"
      comment: "{ item.comment }}"
      shell: "/bin/zsh"
      password: '*'
      update_password: on_create
   with_items:
    ....
```

After the PR, all users that have a password that is not '*' will get their password changed.

Reverting bf3e397ea7922e8bd8b8ffbc05d1aede0317d119, makes 'update_password: on_create' work as expected again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->

lib/ansible/modules/system/user.py

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
2.8.7
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->

Alpine Linux

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
  - name: add users                                                                                                                                                                                                                                  
    user:
      name: "{{ item.name }}"
      comment: "{ item.comment }}"
      shell: "/bin/zsh"
      password: '*'
      update_password: on_create
```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->

Users that are not created does not get their password changed.

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```paste below
Password "hash" changed to '*'
```
