### ISSUE TITLE
Difference in how we handle templating vault variable keys in v2.8 and v2.9

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/ansible#65722]
##### SUMMARY

I can see difference in how we handle templating in 2.9 and 2.8. You could see when we run the same playbook on 2.9.2 it is not showing us value of "testvar" in following result which we can see in 2.8.4

```
ok: [localhost] => {
    "big_test_list1": [
        {
            "key": "test2_{{ testvar }}_password", 
            "value": "test"
        }
    ]
}
```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
**Ansible** : 2.8.x
**Ansible** : 2.9.x

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 8

##### STEPS TO REPRODUCE

```yaml
---
Playbook.yml on 2.9.2

- name: TEST
  gather_facts: False
  hosts: localhost

  vars:
    testvar: "vars"
# vault password is: test
    testdict2:
       "test2_{{ testvar }}_password": !vault |
          $ANSIBLE_VAULT;1.2;AES256;test
          38636163353333363936333133633334646465393136613037626530663664326665613835326466
          6130633637383730613462353037613139323232373762630a616237356230333163666632303262
          32313232616539333664633364636562626539393439333539316236623161386163386533613063
          6466396661323462620a396565646637616264316338636333343738653831383137643463653830
          6433

  tasks:
   - debug:
       var: testdict2

   - set_fact:
       big_test_list1: "{{ big_test_list1 | default([]) + item }}"
     loop:
       - "{{ testdict2 | dict2items }}"

   - debug:
       var: big_test_list1
```

##### EXPECTED RESULTS

Playbook should show results as follows

```
**On 2.8.4**

Vault password: 

PLAY [TEST] *******************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "testdict2": {
        "test2_{{ testvar }}_password": "test"
    }
}

TASK [set_fact] ***************************************************************************************************************************************************************************************************
ok: [localhost] => (item=[{'key': 'test2_vars_password', 'value': 'test'}])

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "big_test_list1": [
        {
            "key": "test2_vars_password",
            "value": "test"
        }
    ]
}


```

##### ACTUAL RESULTS

```paste below
**On 2.9.2**

Vault password: 

PLAY [TEST] *******************************************************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "testdict2": {
        "test2_{{ testvar }}_password": "test"
    }
}

TASK [set_fact] ***************************************************************************************************************************************************************************************************
ok: [localhost] => (item=[{'key': u'test2_{{ testvar }}_password', 'value': u'test'}])

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "big_test_list1": [
        {
            "key": "test2_{{ testvar }}_password", 
            "value": "test"
        }
    ]
}

```
