### ISSUE TITLE
Support specify disks in ovirt_snapshot module

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#65721]
##### SUMMARY

Currently it's not possible to specify disks to be included in the snapshot, always all disks are used.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ovirt_snapshot

##### ADDITIONAL INFORMATION

Could look like:
```yaml
ovirt_snapshot:
  description: My snap
  vm_name: myvm
  disks:
    - id: 123
    - id: 456
```

or 

```yaml
ovirt_snapshot:
  description: My snap
  vm_name: myvm
  disks:
    - name: myvm_disk_db
    - name: myvm_disk_store
```
