### ISSUE TITLE
win_dsc : Invoke multiple resources in one run

### ISSUE THREAD

**Issue by gvcgael** [ansible/ansible#65771]
##### SUMMARY
Sometimes, invoking resources in different steps in ansible does not work. It would be great if `win_dsc` could call multiple dsc resources in one step without requiring ansible reconnecting.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`win_dsc`

##### ADDITIONAL INFORMATION
For example, consider the following dsc : 

```ps1
Configuration IPAddress_AddingStaticIP_Config
{
    Import-DscResource -Module NetworkingDsc

    Node localhost
    {
        NetIPInterface DisableDhcp
        {
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            Dhcp           = 'Disabled'
        }

        IPAddress NewIPv4Address
        {
            IPAddress      = '192.168.10.5'
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPV4'
        }
    }
}
```

The ansible equivalent would not work because disabling DHCP would remove any ip address and ansible could not connect anymore.

```yml 
  win_dsc:
    resource_name: NetIPInterface
    InterfaceAlias: 'Ethernet'
    AddressFamily: 'IPv4'
    Dhcp: 'Disabled'

  win_dsc:
    resource_name: IPAddress 
    IPAddress: '192.168.10.5'
    InterfaceAlias: 'Ethernet'
    AddressFamily: 'IPV4'
```

It would be great if we could do something like this : 

```yml 
  win_dsc:
  - DisableDhcp:
       resource_name: NetIPInterface
       InterfaceAlias: 'Ethernet'
       AddressFamily: 'IPv4'
       Dhcp: 'Disabled'
  - NewIPv4Address:
       resource_name: IPAddress 
       IPAddress: '192.168.10.5'
       InterfaceAlias: 'Ethernet'
       AddressFamily: 'IPV4'
```
