### ISSUE TITLE
template module should allow remote_src option

### ISSUE THREAD

**Issue by VeekeeFr** [ansible/ansible#65778]
##### SUMMARY
template module currently copies j2 file and fill values. It doesn't support a file already present on the remote node.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
template

##### ADDITIONAL INFORMATION
At the current time, using template only supports files available on the controller side. Allowing the process of files already available on the remote host, would also allow providing j2 files from other modules (like get_url, unarchive modules...).

```yaml
- name: Template a file to /etc/files.conf
  template:
    src: /etc/file.conf.j2
    dest: /etc/file.conf
    remote_src: true
```
