### ISSUE TITLE
[Systemd] Allow ansible to update the default systemd target mode

### ISSUE THREAD

**Issue by vlours** [ansible/ansible#65785]
##### SUMMARY

In some case it can be useful to update the default target level for systemd.
This is used from the "get-default", "set-default" and "isolate" systemd options.
- The "get-default" option will retrieve the current default target mode.
- The "set-default" option will set a new default target mode (used on next boot)
- The"isolate" option will set the new target mode dynamically

A combination of these 3 options will allow to manage the target mode in systemd

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

This will be a new functionality in the systemd.py module.

##### ADDITIONAL INFORMATION

This feature will required 2 options:
- default_set
       description:
            - Systemd default target you want to apply on your system
              Target modes can be included and actives in others. Such as "multi-user.target" which is included and active in "graphical.target" mode.
              If you want to ensure that you are running in the desired mode, you can use the "default_apply": "enforce" option to force the mode.
- default_apply:
        description: Apply the Systemd default target if required.
              * The 'no' option will set the desired target mode for next boot. It will not update the current node.
              * The 'yes' option will set the desired target mode and ensure that the desired mode is active.
              * The 'only' option will only ensure that the desired mode is active.
              * The 'enforce' option will do the same stuff as 'yes' but it will enforce the mode at the desired level.
                This can be used to change from "graphical.target" to "multi-user.target" and stop the graphical mode.
                This should be used only once otherwise the task will always be seen as changed.
        choices: [ no, yes, only, enforce ]

```yaml
- name: set the default target to "graphical.target", it will be applied on next boot (2.10 and above)
  systemd:
   default_set: graphical.target

- name: apply the target mode "multi-user.target".
  systemd:
    default_set: multi-user.target
    default_apply: only
```
