### ISSUE TITLE
grafana issue move test

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#65807]
##### SUMMARY
We should see what an issue moved from ansible/ansible to gundalow-collection/grafana looks like.

1) Does all history get moved across
2) What about labels that may not exist in the dest repo

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
grafana_dashboard

##### ADDITIONAL INFORMATION

```yaml
- name: Migrate it
  community.general.grafana_dashboard:
    foo: bar
```
