### ISSUE TITLE
Module to interact with AWS Transfer for SFTP

### ISSUE THREAD

**Issue by tyler-e-marshall** [ansible/ansible#65817]
##### SUMMARY

There is no module for interacting with AWS Transfer for SFTP.  I'll be writing my own module by following patterns in your other AWS modules.  The botocore library that is used in those modules is actually missing a few things for interacting with Transfer too.  For example, there are no waiters when creating/deleting SFTP servers.

##### ISSUE TYPE
- Feature Idea/Request

##### COMPONENT NAME

New module:  aws_transfer

Maybe two modules, one for interacting with just servers and one for just interacting with just users so things like `state:  present` makes sense.  In my example playbook below, I assume two module names.  Although the module for interacting with users on the SFTP server only makes sense if the server is SERVICE_MANAGED, meaning amazon takes care of authenticating users on the server.

##### ADDITIONAL INFORMATION

I am using ansible as an alternative to CloudFormation.  With this new module, I would be able to allocate SFTP servers, add users, and configure those users' SSH keys they will use for logging in.

The end goal of this playbook is to allocate an SFTP server, add a user to the server, and create a DNS entry for the server.

```yaml
- hosts: localhost
    connection: local
    become: false

    vars:
        sftp_hostname_zone:  my_hostname_zone
        sftp_hostname: sftp.my_hostname_zone
        region: us-east-2

    tasks:
        - name: Ensure sftp server present
            aws_transfer_server:
                region: "{{ region }}"
                aws_access_key: "{{ lookup('env', 'AWS_KEY') }}"
                aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
                state: present
                name: my_sftp_server_name
                identity_provider_type:  SERVICE_MANAGED
            register: sftp_server  # return value will have host key fingerprint for connecting securely

        - name: Ensure user present on SFTP server
            aws_transfer_user:
                  aws_access_key: "{{ lookup('env', 'AWS_KEY') }}"
                  aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
                  state: present
                  server_id: "{{ sftp_server.server_ids[0] }}"
                  role: my_role
                  user_name: my_username
                  ssh_public_key_body: my_public_key # maybe module can generate key if public key not provided
            register: sftp_user

        - name:  Ensure DNS entry present for SFTP server
            route53:
                aws_access_key: "{{ lookup('env', 'AWS_KEY') }}"
                aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
                state: present
                overwrite: true  # ensure if new server created, DNS entry now points to new one
                type: CNAME
                record: "{{ sftp_hostname }}"
                zone: "{{ sftp_hostname_zone }}"
                value: "{{ sftp_server.server_ids[0] + '.server.transfer.' + region + '.amazonaws.com' }}"  # default DNS is always serverId.server.transfer.region.amazonaws.com
            register: dns_record
```

The goal is after running the above playbook, a user can now transfer files to/from `my_username@sftp.my_hostname_zone` using the ssh key whose public key is `my_public_key` and expecting hostkey `"{{ sftp_server.host_key_fingerprint }}"`.

One thing that is missing from this example is ensuring an S3 bucket is allocated to hold the files deposited on the SFTP server, but hopefully you get the idea of how the new module would work.
