### ISSUE TITLE
Git ansible module now fails to update a project with untracked files

### ISSUE THREAD

**Issue by matburt** [ansible/ansible#6582]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Ubuntu 12.04
##### Summary:

Ansible 1.4.5 allowed updates to a source tree from the git module if there were untracked files.  Git will also allow updates to a source tree with untracked files as long as updating doesn't bring a file into existence that would conflict.

Ansible 1.5.3 seems to change this behavior.   This is likely the culprit:

https://github.com/ansible/ansible/blob/devel/library/source_control/git#L224

status will list untracked files there
##### Steps To Reproduce:

Clone a repo, add an untracked file, attempt to update it with ansible
##### Expected Results:

Success
##### Actual Results:

```
Local modifications exist in repository (force=no)
```

**Comment by jctanner** [comment]
@matburt Trying to reproduce this but I'm not seeing a problem ...

```
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - file: path=/tmp/atestrepo state=absent
    - git: repo=https://github.com/jctanner/ansible-tests dest=/tmp/atestrepo version=0a760071c81e8b01cfb2c095701fff1a60417dbc
    - copy: dest=/tmp/atestrepo/foobar content="foobar"
    - git: repo=https://github.com/jctanner/ansible-tests dest=/tmp/atestrepo update=yes
```

Result

```
PLAY [localhost] ************************************************************** 

TASK: [file path=/tmp/atestrepo state=absent] ********************************* 
changed: [localhost]

TASK: [git repo=https://github.com/jctanner/ansible-tests dest=/tmp/atestrepo version=0a760071c81e8b01cfb2c095701fff1a60417dbc] *** 
changed: [localhost]

TASK: [copy dest=/tmp/atestrepo/foobar content="foobar"] ********************** 
changed: [localhost]

TASK: [git repo=https://github.com/jctanner/ansible-tests dest=/tmp/atestrepo update=yes] *** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=4    unreachable=0    failed=0 
```

What am I missing from your description?

EDIT: set update=yes on the third play
