### ISSUE TITLE
to_nice_yaml does not emit non ascii characters when stdout_callback=yaml

### ISSUE THREAD

**Issue by mit0223** [ansible/ansible#65843]
##### SUMMARY
to_nice_yaml filter does not emit non ascii characters when stdout_callback=yaml and contents include newline.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
to_nice_yaml
stdout_callback=yaml

##### ANSIBLE VERSION
```paste below
ansible 2.9.2
  config file = None
  configured module search path = ['/home/mitsuru/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mitsuru/hive/lib64/python3.6/site-packages/ansible
  executable location = /home/mitsuru/hive/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
only one configuration ```stdout_callback=yaml``` from environment variable.

##### OS / ENVIRONMENT
macOS catalina 10.15.1
CentOS Linux release 7.7.1908

##### STEPS TO REPRODUCE
execute the playbook.
```shell
$  ANSIBLE_STDOUT_CALLBACK=yaml  ansible-playbook -i localhost, test.yml

PLAY [TEST] ************************************************************************************************************************************************************************************************

TASK [set_fact] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [put records to json file] ****************************************************************************************************************************************************************************
changed: [localhost -> localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
test.yml:
```yaml
---
- name: TEST
  gather_facts: False
  hosts: all
  tasks:
  - set_fact:
      txt:
      - layout: "<body>\n<div>日本語</div>\n</body>\n"
        type: text
      - layout: "<body>日本語</body>"
        type: text
  - name: put records to json file
    local_action:
      module: copy
      content: "{{ txt | to_nice_yaml}}"
      dest: "testout.yml"

```

##### EXPECTED RESULTS
contents of testout.yml should be:
```yaml
-   layout: |-
        <body>
        <div>日本語</div>
        </body>
    type: text
-   layout: <body>日本語</body>
    type: text
```

##### ACTUAL RESULTS
contents of testout.yml:
```yaml
-   layout: |-
        <body>
        <div></div>
        </body>
    type: text
-   layout: <body>日本語</body>
    type: text
```
Originally, "&lt;div>日本語&lt;/ div>" should be output on the third line of the file, but the non-ASCII characters have disappeared.

This bug only appears when the output string contains line breaks and stdout_callback = yaml is specified in the configuration. When stdout_callback = yaml is not specified, nice_to_yaml will output yaml in string style, but I want output in literal (begining with '|') style.

The result of no stdout_callback:
```yaml
-   layout: '<body>

        <div>日本語</div>

        </body>

        '
    type: text
-   layout: <body>日本語</body>
    type: text
```
