### ISSUE TITLE
Variable leaking from one role to the other

### ISSUE THREAD

**Issue by JulienPalard** [ansible/ansible#65851]
##### SUMMARY
I'm having a playbook reusing the same role multiple times, but variable are "leaking" from one use to the other.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
roles

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = None
  configured module search path = ['/home/mdk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mdk/clones/JulienPalard/ansible/.venv/lib/python3.8/site-packages/ansible
  executable location = /home/mdk/clones/JulienPalard/ansible/.venv/bin/ansible
  python version = 3.8.0 (default, Dec 12 2019, 09:56:28) [GCC 9.2.1 20191130]
```

##### CONFIGURATION

```paste below
```

##### STEPS TO REPRODUCE

I tried with this simple playbook:

```yaml
---

- hosts: tests
  roles:
    - role: static_website
      vars:
        uri: mdk.fr
        owner: mdk
        path: /var/www/mdk.fr/
        public_deploy_key: 'Has a deploy key'

    - role: static_website
      vars:
        uri: codeenseine.fr
        owner: codeenseine
        path: /var/www/codeenseine.fr/
```

and static_website role simply containing:
```yaml
---

- debug:
    msg: "In role static_website for {{ uri }}: deploy key is: {{ public_deploy_key }}"
```

in a hierarchy like this:
```
.
├── inventory.ini
├── playbook.yml
└── roles
    └── static_website
        └── tasks
            └── main.yml

3 directories, 3 files

```

##### EXPECTED RESULTS

I don't expect codeenseine.fr to have a deploy key, could even easily be a security issue.

##### ACTUAL RESULTS

```paste below
TASK [static_website : debug] *********************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "In role static_website for mdk.fr: deploy key is: Has a deploy key"
}

TASK [static_website : debug] *********************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": "In role static_website for codeenseine.fr: deploy key is: Has a deploy key"
}
```

Deploy key from mdk.fr "leaked" in codeenseine.fr!

I feed it can be related to https://github.com/ansible/ansible/issues/34300 or https://github.com/ansible/ansible/issues/50017, https://github.com/ansible/ansible/issues/36274
