### ISSUE TITLE
Debug verbosity not working as expected

### ISSUE THREAD

**Issue by magick93** [ansible/ansible#65856]
##### SUMMARY
The `debug` module is too noisy, and doesnt output only what is being requested. And the `verbosity` property isnt working as expected.

The `debug` module is outputting more than is being asked. 

When I set `verbosity: 3` and do not use `-v` / `-vv` / `-vvv` etc on the command line, I get blue, skipped, output from debug. 

When I set `verbosity: 0` it actually ouputs more info than  `verbosity: 3` as it includes the `msg` - which is the only thing it should be outputing - plus it includes the complete `{{item}}`.

The only semi effective way I've found to limit the output of `debug` is to use `loop_control` which still results in too much noise, as it outputs the requested value twice, eg:

```
- name: Debug list of files
      debug: 
        msg:  " path is {{item.path}}"
        verbosity: 0
      loop: "{{findfiles.files}}"
#      with_items: "{{findfiles.files}}"
      loop_control:
        label: "{{ item.path }}"
```
Will result in the following - not the file path is printed twice per result. Once would have been enough:
```
ok: [localhost] => (item=/home/user/file1.txt) => {
    "msg": " path is /home/user/file1.txt"
}
ok: [localhost] => (item=/home/user/file2.txt) => {
    "msg": " path is /home/user/file2.txt"
}
```

The documentation says the following:

> A number that controls when the debug is run, if you set to 3 it will only run debug when -vvv or above

However, when I run ` ansible-playbook debug_bug.yaml  -i localhost, -K -v` with `debug` set to `verbosity: 3` I get a lot of `skipping`, blue, output. So the color of the output has changed, but its basically the same as not using `loop_control`,

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
debug

##### ANSIBLE VERSION

```
ansible 2.8.4
  config file = None
  configured module search path = [u'/home/anton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Ubuntu 18.04.3 LTS (Bionic Beaver)

##### STEPS TO REPRODUCE
Run the following example

```yaml

# ansible-playbook debug_bug.yaml  -i localhost, -K
---
- name: debug too noisy
  hosts: all
  connection: local
  gather_facts: yes

  vars:
   - vm_host: localhost
   - ansible_user: deploy
   - no_log: True
  tasks:


    - name: loop over files
      find:
        paths: "{{ ansible_env.HOME }}"
        patterns: '*.*'
        recurse: no
      register: findfiles
      become: yes


    - name: Debug list of files
      debug: 
        msg:  " path is {{item.path}}"
        verbosity: 3
      loop: "{{findfiles.files}}"
#      with_items: "{{findfiles.files}}"
#      loop_control:
#        label: "{{ item.path }}"

```

### Other things I've tried
To limit `debug` output to what I've asked to output, I've also tried:

- using var `ANSIBLE_DEBUG: false`
- using var `no_log: True`
- using var  `ANSIBLE_VERBOSITY: 0`

None of these appear to have any impact, and still result in the debug output containing the `msg` and the complete `item`. 

If I use the following, rather than using  `msg:  " path is {{item.path}}"` the noise is even worse. The `item` is printed twice! Once unformatted, and once pretty, and then the actual `var` output.

```
- name: Debug list of files
      debug: 
        var:  item.path
        verbosity: 0
      loop: "{{findfiles.files}}"
```

##### EXPECTED RESULTS
I expect `debug` to print exactly what is being requested, no more, especially when using `verbosity: 0`. And especially when not using `ansible-playbook ... -v / -vvvv`.

##### ACTUAL RESULTS

For too much noise! For example, when using:

```
- name: Debug list of files
      debug: 
        var: item.path
        verbosity: 0
      loop: "{{findfiles.files}}"
```

The output is - notice the `item` is printed twice - including unformatted and pretty, and then the `var` is printed:

```
ok: [localhost] => (item={u'rusr': True, u'uid': 1000, u'rgrp': True, u'xoth': False, u'islnk': False, u'woth': False, u'nlink': 1, u'issock': False, u'mtime': 1576110963.0364165, u'gr_name': u'user', u'path': u'/home/user/file1.txt', u'xusr': False, u'atime': 1576110963.0364165, u'inode': 18884540, u'isgid': False, u'size': 0, u'isdir': False, u'ctime': 1576110963.0364165, u'isblk': False, u'wgrp': True, u'xgrp': False, u'isuid': False, u'dev': 64769, u'roth': True, u'isreg': True, u'isfifo': False, u'mode': u'0664', u'pw_name': u'user', u'gid': 1000, u'ischr': False, u'wusr': True}) => {
    "ansible_loop_var": "item", 
    "item": {
        "atime": 1576110963.0364165, 
        "ctime": 1576110963.0364165, 
        "dev": 64769, 
        "gid": 1000, 
        "gr_name": "user", 
        "inode": 18884540, 
        "isblk": false, 
        "ischr": false, 
        "isdir": false, 
        "isfifo": false, 
        "isgid": false, 
        "islnk": false, 
        "isreg": true, 
        "issock": false, 
        "isuid": false, 
        "mode": "0664", 
        "mtime": 1576110963.0364165, 
        "nlink": 1, 
        "path": "/home/user/file1.txt", 
        "pw_name": "user", 
        "rgrp": true, 
        "roth": true, 
        "rusr": true, 
        "size": 0, 
        "uid": 1000, 
        "wgrp": true, 
        "woth": false, 
        "wusr": true, 
        "xgrp": false, 
        "xoth": false, 
        "xusr": false
    }, 
    "item.path": "/home/user/file1.txt"
}
```

If I use the following, with `loop_control`, I still get too much noise, and still get the complete `item` printed, albeit only once:

```
- name: Debug list of files
      debug: 
        var: item.path
        verbosity: 0
      loop: "{{findfiles.files}}"
#      with_items: "{{findfiles.files}}"
      loop_control:
        label: "{{ item.path }}"
```
Also, using `label: "{{ item.path }}"` or `label:  item.path  ` doesnt make any difference - still prints way too much!
