### ISSUE TITLE
with_first_found does not find any files since Ansible 2.7

### ISSUE THREAD

**Issue by WilliamDEdwards** [ansible/ansible#65858]
##### SUMMARY
with_first_found is not finding files after updating to Ansible 2.7.

I have not found any changes in Ansible changelogs between versions 2.4 to 2.9 relating to with_first_found behaviour.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
with_first_found

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible controller OS: Debian 9.11

##### STEPS TO REPRODUCE
```
- name: Copy config
  copy: src={{ item }} dest=/etc/ferm/ferm.conf mode=0644 owner=root group=root
  with_first_found:
    - files:
      - "etc/ferm/ferm.conf"
      paths:
        - /etc/ansible/files/{{ inventory_hostname }}
        - /etc/ansible/files/{{ secondary_hostgroup }}
        - /etc/ansible/files/{{ primary_hostgroup }}
        - /etc/ansible/host_vars/{{ inventory_hostname }}/files
        - /etc/ansible/group_vars/{{ primary_hostgroup }}/files
        - files
  notify: restart ferm
```

##### EXPECTED RESULTS
with_first_found would find file `/etc/ansible/roles/ferm/files/etc/ferm/ferm.conf`. This is a `copy` task, so Ansible would look in roles/ferm/files, which would match the last line (`files`) in `paths`.

File exists:

```
$ ls /etc/ansible/roles/ferm/files/etc/ferm/ferm.conf
/etc/ansible/roles/ferm/files/etc/ferm/ferm.conf
```

**Important!** This exact task worked fine before Ansible 2.7. This broke after updating Ansible to version 2.7. There have been zero changes to the task or file structure according to Git.

with_first_found is 'broken' in all roles and tasks. Ansible is not finding any files with with_first_found; this problem is not specific to the `ferm` role.

##### ACTUAL RESULTS
```
TASK [ferm : Copy config] **********************************************************************************************************************************************************************************
task path: /etc/ansible/roles/ferm/tasks/main.yml:34
fatal: [clansible.cyberfusion.nl]: FAILED! => {
    "msg": "No file was found when using first_found. Use errors='ignore' to allow this task to be skipped if no files are found"
}
```
