### ISSUE TITLE
Ansible azure VM Generalization not working

### ISSUE THREAD

**Issue by vinayupadhyay1994** [ansible/ansible#65870]
I am writing a playbook to generalize a azure windows vm, after generalization, i capture an image. 

On creating a new vm from the captured image i get the below error : 

```
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "OSProvisioningClientError",
                "message": "OS Provisioning for VM 'work' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image:\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/ "
            }
        ]
    }
}
```

My play book looks like this : 
 ```
- name: Stop VM before it can be generalized and image captured
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_vm }}"
        name: "{{ vm_name }}{{random_suffix}}"
        started: false

    - name: Call REST API - VirtualMachines_Generalize
      azure_rm_resource:
        api_version: '2017-12-01'
        method: POST
        resource_group: "{{ resource_group_vm }}"
        provider: compute
        resource_type: virtualmachines
        resource_name: "{{ vm_name }}{{random_suffix}}"
        subresource:
            - type: generalize  
                
    - name: Create an image from a virtual machine
      azure_rm_image:
        resource_group: "{{ resource_group_vm }}"
        os_type: Windows
        name: "{{ vm_name }}{{random_suffix}}-image"
        source: "{{ vm_name }}{{random_suffix}}"
        state: present
```
Expected Result: 

VM is created from generalized image

Any idea where am I going wrong ?
