### ISSUE TITLE
redfish_info yielding Failed GET request for any command

### ISSUE THREAD

**Issue by xmadsen** [ansible/ansible#65889]
##### SUMMARY

Since updating to Ansible 2.9, redfish_info has failed to yield any inventory information successfully. The same commands that work in redfish_facts in Ansible 2.8 are failing their initial GET requests to the redfish service API endpoint.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xander/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xander/.local/lib/python3.5/site-packages/ansible
  executable location = /home/xander/.local/bin/ansible
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu WSL on WIndows 10 

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get all BIOS attributes
      redfish_info:
        category: Chassis
        command: GetChassisInventory
        baseuri: 10.240.50.79
        username: "{{ username }}"
        password: "{{ password }}"
      loop_control:
        loop_var: xcc_ip
      register: result

    - debug:
        var: result
```

##### EXPECTED RESULTS

I expect the task to return 

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xander/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xander/.local/lib/python3.5/site-packages/ansible
  executable location = /home/xander/.local/bin/ansible-playbook
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /Playbooks/hosts.yml as it did not pass its verify_file() method
Parsed /Playbooks/hosts.yml inventory source with ini plugin

PLAYBOOK: getbiosattributes-v3_1.yml ***************************************************************1 plays in getbiosattributes-v3_1.yml

PLAY [localhost] ***********************************************************************************META: ran handlers

TASK [Get all BIOS attributes from XCC hosts] ******************************************************task path: / Playbooks/getbiosattributes-v3_1.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: xander
<127.0.0.1> EXEC /bin/sh -c 'echo ~xander && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202 `" && echo ansible-tmp-1576525569.7230585-52323090220202="` echo /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202 `" ) && sleep 0'
Using module file /home/xander/.local/lib/python3.5/site-packages/ansible/modules/remote_management/redfish/redfish_info.py
<127.0.0.1> PUT /home/xander/.ansible/tmp/ansible-local-671840tzdyou/tmpza5kp1hl TO /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202/AnsiballZ_redfish_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202/ /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202/AnsiballZ_redfish_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202/AnsiballZ_redfish_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/xander/.ansible/tmp/ansible-tmp-1576525569.7230585-52323090220202/ > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item=10.240.50.79) => {
    "ansible_loop_var": "xcc_ip",
    "changed": false,
    "invocation": {
        "module_args": {
            "baseuri": "10.240.50.79",
            "category": [
                "Chassis"
            ],
            "command": [
                "GetChassisInventory"
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "timeout": 10,
            "username": "USERID"
        }
    },
    "msg": "Failed GET request to 'https://10.240.50.79/redfish/v1/': 'the JSON object must be str,
not 'bytes''",
    "xcc_ip": "10.240.50.79"
}

PLAY RECAP *****************************************************************************************localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/remote_management/redfish/redfish_info.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/redfish/redfish_info.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @billdodd @jose-delarosa @mraineri @tomasg2012
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by billdodd** [comment]
Strange. I cannot reproduce this. Nor can I see any reason that the module change from redfish_facts to redfish_info would result in this type of error.

Do you see the same error with the redfish_config and/or redfish_command modules?
Do you see the errors using the latest devel branch?

From the error you are getting, I would be interested in the Content-Type header in the response to the GET request (and any other headers as well). Are you able to capture the response headers?  

My results:

Version:
```
ansible 2.9.2.post0
  config file = $HOME/.ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/Development/git/ansible/lib/ansible
  executable location = $HOME/Development/git/ansible/bin/ansible
  python version = 3.6.5 (default, Apr 25 2018, 14:26:36) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

Playbook:
```
---
- hosts: myhosts
  connection: local
  name: Chassis Inventory 
  gather_facts: False

  vars:
    datatype: ChassisInventory

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get chassis Inventory
    redfish_info:
      category: Chassis
      command: GetChassisInventory
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
```

Output:
```
PLAY [Chassis Inventory] *******************************************************

TASK [Set output file] *********************************************************
included: $HOME/Development/DMTF/Ansible/playbooks/chassis/create_output_file.yml for ilo

TASK [Define timestamp] ********************************************************
ok: [ilo]

TASK [Define file to place results] ********************************************
ok: [ilo]

TASK [Create dropoff directory for host] ***************************************
[WARNING]: Platform darwin on host ilo is using the discovered Python
interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/devel/refer
ence_appendices/interpreter_discovery.html for more information.

ok: [ilo]

TASK [Get chassis Inventory] ***************************************************
ok: [ilo]

TASK [Copy results to output file] *********************************************
changed: [ilo]

PLAY RECAP *********************************************************************
ilo                        : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by billdodd** [comment]
@xmadsen Any update on this issue? I still can't reproduce and haven't seen any other reports of this problem. My questions from the comment above:

> Do you see the same error with the redfish_config and/or redfish_command modules?
> Do you see the errors using the latest devel branch?
> 
> From the error you are getting, I would be interested in the Content-Type header in the response to the GET request (and any other headers as well). Are you able to capture the response headers?

**Comment by m33x-7** [comment]
@billdodd I've just come across this error trying to configure some Cisco IMCs for the first time. I get the same error for redfish_info, redfish_config, and redfish_command. I've also put on the latest firmware just incase, but the results are the same.

I've included the output from all three modules, and the HTTP headers from the CIMC, as you've previously requested.

The modules work fine if I use a Python2 version of Ansible.

Let me know if you need anything else.

**Ansible Version:**
```
ansible 2.9.11
  config file = None
  configured module search path = ['/home/tcole/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tcole/.local/lib/python3.5/site-packages/ansible
  executable location = /home/tcole/.local/bin/ansible
  python version = 3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516]
```

**Playbook:**
```
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: redfish facts
      redfish_info:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      ignore_errors: true
    - name: redfish config
      redfish_config:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        category: Systems
        command: SetBiosDefaultSettings
      ignore_errors: true
    - name: redfish command
      redfish_command:
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        category: Systems
        command: PowerGracefulRestart
      ignore_errors: true
```

```[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [redfish facts] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed GET request to 'https://10.101.129.17/redfish/v1/': 'the JSON object must be str, not 'bytes''"}
...ignoring

TASK [redfish config] **********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed GET request to 'https://10.101.129.17/redfish/v1/': 'the JSON object must be str, not 'bytes''"}
...ignoring

TASK [redfish command] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed GET request to 'https://10.101.129.17/redfish/v1/': 'the JSON object must be str, not 'bytes''"}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=3

Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fcebde0e8c8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
<---snip repeated lots of time --->
````

**HTTP Headers:**
These are the headers from just doing a `curl -v` to the CIMC:
```
<---snip--->
> GET /redfish/v1/ HTTP/1.1
> Host: 10.101.129.17
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200
< Server: webserver
< Date: Wed, 22 Jul 2020 09:22:50 GMT
< Content-Type: application/json
< Content-Length: 1162
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Content-Security-Policy: default-src 'none'; child-src 'self' *; script-src 'self' 'unsafe-eval' 'unsafe-inline'; connect-src 'self' *; font-src 'self' data:; img-src 'self' data: ; style-src 'self' 'unsafe-inline'; frame-src 'self';
< X-Robots-Tag: noindex, nofollow, nosnippet, noarchive
<
{
        "@odata.id":    "/redfish/v1",
        "@odata.context":       "/redfish/v1/$metadata#ServiceRoot",
        "@odata.type":  "#ServiceRoot.v1_5_1.ServiceRoot",
        "Id":   "RootService",
        "Name": "Cisco RESTful Root Service",
        "Description":  "Root Service",
        "JsonSchemas":  {
                "@odata.id":    "/redfish/v1/JsonSchemas"
        },
<---snip--->
        "Links":        {
                "Sessions":     {
                        "@odata.id":    "/redfish/v1/SessionService/Sessions"
                }
        },
        "RedfishVersion":       "1.5.1",
        "Product":      "UCSC-C220-M5SX",
        "Vendor":       "Cisco Systems Inc."
* Curl_http_done: called premature == 0
* Connection #0 to host 10.101.129.17 left intact
```

**Python2 Ansible:**
```
ansible 2.9.11
  config file = None
  configured module search path = [u'/home/tcole/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tcole/.local/lib/python2.7/site-packages/ansible
  executable location = /home/tcole/.local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

**Python2 Output:**
```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [redfish facts] ***********************************************************
ok: [localhost]

TASK [redfish config] **********************************************************
changed: [localhost]

TASK [redfish command] *********************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by billdodd** [comment]
@m33x-7 Thanks for updates and detail on this issue.

The Redfish modules use the Ansible `module_utils.urls.open_url()` to make the HTTP requests to the Redfish service. And that method uses the Python `urllib` package. And I'm guessing that somewhere in there (probably in `urllib`), the response body is converted to JSON via something like `json.loads(s)`. 

While googling for the error seen here ("the JSON object must be str, not 'bytes'"), I came across the interesting detail that `json.loads(s)` only takes a `str` in Python 3.5, but will also accept `bytes` or `bytearray` in 3.6 or later.

And at that point, I also noticed that @xmadsen was using Python 3.5.2 and @m33x-7 was using Python 3.5.3 when the errors occurred.

I tried testing against the Redfish services that I have access to using Python 3.5.2, but was still unable to reproduce the issue.

But perhaps there is something different about the Lenovo and Cisco Redfish service responses.

In any case, could you try again with an environment using Python 3.6 or later?

**Comment by billdodd** [comment]
> The Redfish modules use the Ansible `module_utils.urls.open_url()` to make the HTTP requests to the Redfish service. And that method uses the Python `urllib` package. And I'm guessing that somewhere in there (probably in `urllib`), the response body is converted to JSON via something like `json.loads(s)`.

Actually, the `json.loads(s)` is in the redfish_utils.py module. So if that's the problem, I should be able to fix it.

But since I haven't been able to reproduce it, even on 3.5.2, it will help to see if moving to Python 3.6+ resolves it for you.

**Comment by billdodd** [comment]
OK, I figured out what was going on. My idea above is correct: The`json.loads(resp.read())` is failing on Python 3.5 because `json.loads()` expects a `str` and the `HTTPResponse.read()` returns `bytes`. In Python 3.6 and later,  `json.loads()` will also take `bytes`.

I was confused because I set up my Ansible env to use Python 3.5, but when I did that I still could not reproduce the error. It turns out that the invocation of the Redfish module was still being run using the system Python which for me was version 2.7.16.

I learned you can specify the Python version to use explicitly in the playbook using the `ansible_python_interpreter` var:

```
---
- hosts: myhosts
  connection: local
  name: System Inventory
  gather_facts: False

  vars:
    ansible_python_interpreter: /Users/bdodd/.pyenv/shims/python3.5

  tasks:
    ...
```

After I did that I could easily switch between different Python versions and could reproduce the error with Python 3.5.

I have a fix ready to go. The fix needs to first be submitted in the development release and the Redfish modules have moved to the new https://github.com/ansible-collections/community.general repo.

@m33x-7 Would you mind opening your issue in the https://github.com/ansible-collections/community.general repo? I'll then submit a PR there. And then that fix can be backported to the stable release.
