### ISSUE TITLE
k8s json merge patch broken

### ISSUE THREAD

**Issue by jkupferer** [ansible/ansible#65897]
##### SUMMARY
The k8s module does not support json patch as the documentation claims.

A simple review of the implementation of the k8s module reveals that json patch is not implemented. This did function in an earlier Ansible release, but the code base appears to have made so many assumptions that force the resource definition to be a dictionary that it may not be practical to support json patch in this module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jkupfere/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jkupfere/.local/lib/python3.7/site-packages/ansible
  executable location = /home/jkupfere/.local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 16:48:28) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

The playbook below results in no change being made to the configmap by the json patch.
The final value of `data.foo` is `"bar"`.

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - k8s:
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: test
          namespace: default
        data:
          foo: bar

  - k8s:
      api_version: v1
      kind: ConfigMap
      name: test
      namespace: default
      merge_type: json
      definition:
      - op: replace
        path: /data/foo
        value: foo
    register: r_patch

  - debug: var=r_patch
```

##### EXPECTED RESULTS

The expected result should be that `data.foo` is updated to `"foo"`.

##### ACTUAL RESULTS

The final value for `data.foo` is `"bar"`.

```paste below
$ansible-playbook test.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [k8s] ********************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [k8s] ********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "r_patch": {
        "changed": false,
        "diff": {},
        "failed": false,
        "method": "patch",
        "result": {
            "apiVersion": "v1",
            "data": {
                "foo": "bar"
            },
            "kind": "ConfigMap",
            "metadata": {
                "creationTimestamp": "2019-12-17T02:02:32Z",
                "name": "test",
                "namespace": "default",
                "resourceVersion": "3486998",
                "selfLink": "/api/v1/namespaces/default/configmaps/test",
                "uid": "49712f75-2071-11ea-a743-02e272cbcadc"
            }
        }
    }
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
