### ISSUE TITLE
VMware: vmware_guest always performs OS customization

### ISSUE THREAD

**Issue by mr-blanket** [ansible/ansible#65910]
##### SUMMARY

vmware_guest always performs Windows OS customization even if parameters **customization** and **customization_spec** are not provided.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
// empty - no output
```

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_user: '{{ lookup("env", "ANSIBLE_NET_USERNAME" ) }}'
    vcenter_pass: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "vc.domain.local"
        username: "administrator@vsphere.local"
        password: "xxxx"
        datacenter: "DC"
        name: "VM_CLONE"
        template: "VM_SOURCE"
        folder: "folder"
        resource_pool: "rp"
        networks: "PortGroupName-1234"
        state: present
```

##### EXPECTED RESULTS

Only clone of the virtual machine would happen.
Powering on the VM does not perform any OS customization (e.g. sysprep) on the Windows OS.

##### ACTUAL RESULTS

Clone of the virtual machine happens.
Powering on VM starts OS customization.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mr-blanket, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@mr-blanket Thanks for reporting this issue. `state: present` assumes that the user wants to reconfigure the given VM with the given parameters. If you just want to clone the VM then you can specify power state in `state` parameter. 

I am able to clone simple Debian machine using the following playbook - 

```yaml
---
- hosts: localhost
  vars_files:
    - vcenter_vars.yml
  tasks:
  - name: Get all guests
    vmware_guest:
      validate_certs: False
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: "{{ dc1 }}"
      state: poweredoff
      cluster: Asia-Cluster1
      template: debian10
      name: my_clone_deb_1
      datastore: ds_226_2
      folder: /Asia-Datacenter1/vm/
```

Let me know if I am missing anything here or your requirements are different from my understanding.

needs_info

**Comment by cigamit** [comment]
I believe he is stating that it does clone it, but even though he is not giving any customization options, it does a sysprep on the Windows VM.  Most likely its caused by setting the network port name, and is probably fixed by this #65997

I will test myself tonight.

**Comment by SF-DK** [comment]
I am having this same issue. I want to clone from a template and power on the new VM with no customization but no matter what I do it runs the vmware customization. The VM clones fine, it turns on fine but then it runs the image customization even though I don't want it to. Does anyone have a workaround to this?

**Comment by mr-blanket** [comment]
@everyone:
For 2.7 the issue was providing network name at clone time. This particular line https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1166 adds type key to networks dictionary that then always triggers OS customization because it is missing in the list here https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/cloud/vmware/vmware_guest.py#L2017

One possible workaround for 2.7 is to create two tasks:
```
- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_user: '{{ lookup("env", "ANSIBLE_NET_USERNAME" ) }}'
    vcenter_pass: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
  tasks:
    - name: Clone VM from template
      vmware_guest:
        validate_certs: False
        hostname: "vc.domain.local"
        username: "administrator@vsphere.local"
        password: "xxxx"
        datacenter: "DC"
        name: "VM_CLONE"
        template: "VM_SOURCE"
        folder: "folder"
        resource_pool: "rp"
        state: present
    - name: Change network adapter portgroup
      vmware_guest:
        name: "VM_CLONE"
        networks: "PortGroupName-1234"
```

@SF-DK:
I think you have a typo:
```
    networks:
    - name: 'xxx'
      start_conneted: yes <<< instead of start_connected
```

The code triggers OS customization if it finds an unknown key in networks dictionary. See keys that do not trigger OS customization: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L2435

I guess this issue can be closed.
