### ISSUE TITLE
template module shows diff even if "force=no" was passed

### ISSUE THREAD

**Issue by 8191** [ansible/ansible#6591]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 991399edf0) last updated 2014/03/20 08:41:39 (GMT +200)
##### Environment:

Host: Fedora 20
Target: OpenBSD 5.4
##### Summary:

When calling ansible-playbook with --diff, a diff is even shown by the template module, if the copy parameter "force=no" was passed and the dest file exists. Actually everything behaves correctly (since copy obeys the force and does not alter the file), but it is quite confusing to see a diff for a file which was not altered.

The template module should suppress the diff if force=no was passed and the dest file exists.
##### Steps To Reproduce:

Create a playbook with the _template_ module and specify an existing dest file and the _force=no_ parameter. Then call the playbook with the _--diff_ parameter of ansible-playbook.

``` yaml
- host: somehost
- tasks:
  - name: create new file but don't touch existing
    template:
      src: foo.j2
      dest: /tmp/existing.file
      force: no
```
##### Expected Results:

No diff should be shown and the dest file should not be touched.
##### Actual Results:

The template module shows a diff between the existing destination file and the generated template file. Nevertheless the file is not being touched (as expected).
