### ISSUE TITLE
vmware_guest_network unable to add a new dvPortgroup backed NIC

### ISSUE THREAD

**Issue by arpadhajdu** [ansible/ansible#65919]
##### SUMMARY
I'm attempting to use the vmware_guest_network module to add a new NIC in a specific DVS Portgroup to VMs, but the created new NIC is not using the backnig DVS but configured as "standard portgroup"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_network

##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ans1/lib/python3.6/site-packages/ansible
  executable location = /root/ans1/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['vmware_vm_inventory', 'yaml', 'host_list']
```

##### OS / ENVIRONMENT

- CentOS Linux release 7.6.1810
- Python 3.6  - python3-3.6.8-10.el7.x86_64
- vCentre: 6.0.0 Build: 13638473

##### STEPS TO REPRODUCE

```yaml
- name: Add NIC
  vmware_guest_network:
    hostname: "{{ vmware_vcentre }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    datacenter: "DC"
    cluster: "CLUSTER"
    name: "{{ ansible_nodename }}"
    gather_network_info: false
    networks:
      - name: "VLAN123_10.10.123.X"
        dvswitch_name: "DSwitch"
        connected: true
        start_connected: true
        state: new
  delegate_to: localhost
  register: vm_network_info
```

##### EXPECTED RESULTS

Expected: 
A new NIC added to the VM, which is connected and using the required PortGroup

##### ACTUAL RESULTS

```
{
    "changed": true,
    "invocation": {
        "module_args": {
            "cluster": "CLUSTER",
            "datacenter": "DC",
            "esxi_hostname": null,
            "folder": null,
            "gather_network_info": false,
            "hostname": "cc-devvcentre.domain.local",
            "moid": null,
            "name": "B3-DTRS-01",
            "networks": [
                {
                    "connected": true,
                    "dvswitch_name": "DSwitch",
                    "name": "VLAN123_10.10.123.X",
                    "start_connected": true,
                    "state": "new"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "username": "username",
            "uuid": null,
            "validate_certs": true
        }
    },
    "network_data": {
        "0": {
            "allow_guest_ctl": true,
            "connected": true,
            "device_type": "VMXNET3",
            "label": "Network adapter 1",
            "mac_addr": "00:50:56:81:b7:d1",
            "name": "DVSwitch: fc 6c 01 50 95 f5 b4 b6-d3 00 21 c3 4d e1 91 45",
            "start_connected": true,
            "unit_number": 7,
            "wake_onlan": true
        },
        "1": {
            "allow_guest_ctl": true,
            "connected": false,
            "device_type": "VMXNET3",
            "label": "Network adapter 2",
            "mac_addr": "00:50:56:81:1c:42",
            "name": "VLAN123_10.10.123.X",
            "start_connected": true,
            "unit_number": 8,
            "wake_onlan": true
        }
    }
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest_network.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_network.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@arpadhajdu, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by angystardust** [comment]
maybe fixed_by 65835

**Comment by Akasurde** [comment]
resolved_by_pr #65835

**Comment by Akasurde** [comment]
@arpadhajdu, Could you please check PR #65835 and let us know if it works for you ? <br><br>Please check [How to test a PR](https://docs.ansible.com/ansible/latest/dev_guide/testing.html#how-to-test-a-pr) for more help. <br><br> Thanks. <br><br> needs_info

**Comment by arpadhajdu** [comment]
@Akasurde , I did try the PR65835 and the result almost the same as earlier.

Used version for testinging:
```
ansible-playbook 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible-pr-testing/lib/ansible
  executable location = /root/ansible-pr-testing/bin/ansible-playbook
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

Earlier I tried to use "dvswitch_name" but this parameter is not working in the dev version.
```
 "msg": "Unsupported parameters for (vmware_guest_network) module: dvswitch_name Supported parameters include: cluster, datacenter, esxi_hostname, folder, gather_network_info, hostname, moid, name, networks, password, port, proxy_host, proxy_port, use_instance_uuid, username, uuid, validate_certs"
```

The result which was generaetd (after removing the dvswitch_name parameter) is almost identical to the original case.

```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014 `" && echo ansible-tmp-1576661123.9048986-236186844622014="` echo /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014 `" ) && sleep 0'
Using module file /root/ansible-pr-testing/lib/ansible/modules/cloud/vmware/vmware_guest_network.py
<localhost> PUT /root/.ansible/tmp/ansible-local-1150303eq_x8t/tmpclrcr6hm TO /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014/AnsiballZ_vmware_guest_network.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014/ /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014/AnsiballZ_vmware_guest_network.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014/AnsiballZ_vmware_guest_network.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1576661123.9048986-236186844622014/ > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "cluster": "CLUSTER",
            "datacenter": "DC",
            "esxi_hostname": null,
            "folder": null,
            "gather_network_info": false,
            "hostname": "cc-devvcentre.domain.local",
            "moid": null,
            "name": "RHEL7PERF",
            "networks": [
                {
                    "connected": true,
                    "name": "VLAN123_10.10.123.X",
                    "start_connected": true,
                    "state": "new"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "use_instance_uuid": false,
            "username": "username",
            "uuid": null,
            "validate_certs": true
        }
    },
    "network_data": {
        "0": {
            "allow_guest_ctl": true,
            "connected": true,
            "device_type": "VMXNET3",
            "directpath_io": true,
            "label": "Network adapter 1",
            "mac_addr": "00:50:56:81:21:d9",
            "name": "DVSwitch: fc 6c 01 50 95 f5 b4 b6-d3 00 21 c3 4d e1 91 45",
            "start_connected": true,
            "unit_number": 7,
            "wake_onlan": true
        },
        "1": {
            "allow_guest_ctl": true,
            "connected": false,
            "device_type": "VMXNET3",
            "directpath_io": true,
            "label": "Network adapter 2",
            "mac_addr": "00:50:56:81:f7:c3",
            "name": "VLAN600_10.10.1.X",
            "start_connected": true,
            "unit_number": 8,
            "wake_onlan": true
        }
    }
}

```

**Comment by sky-joker** [comment]
Hi @arpadhajdu

When run playbook following, succeed in my lab environment.

| component | version |
|-----------|---------|
| vCenter   | 6.7.0   |
| ESXi      | 6.7.0   |

```yaml
---
- name: "PR #65835 Test Playbook"
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_auth_info: &vcenter_auth_info
      hostname: vcenter server
      username: administrator@vsphere.local
      password: secret
      validate_certs: no
    datacenter: DC0
    folder: /vm/F0
    vm_name: test_vm1
    dvswitch_name: DVS0
    pg_name: DC0_DVPG0
  tasks:
    - vmware_guest_info:
        <<: *vcenter_auth_info
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        schema: vsphere
        properties:
          - config.hardware.device
      register: r

    - debug: msg="{{ item }}"
      loop: "{{ r.instance.config.hardware.device }}"
      loop_control:
        label: "{{ item.deviceInfo.label }}"
      when:
        - "'macAddress' in item"

    - vmware_guest_network:
        <<: *vcenter_auth_info
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
        networks:
          - name: "{{ pg_name }}"
            dvswitch_name: "{{ dvswitch_name }}"
            connected: true
            start_connected: true
            state: new
      register: r

    - debug: var=r

    - vmware_guest_info:
        <<: *vcenter_auth_info
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        schema: vsphere
        properties:
          - config.hardware.device
      register: r

    - debug: msg="{{ item }}"
      loop: "{{ r.instance.config.hardware.device }}"
      loop_control:
        label: "{{ item.deviceInfo.label }}"
      when:
        - "'macAddress' in item"
```

**result**

```
(venv) [root@localhost 65919]# DISPLAY_SKIPPED_HOSTS=False ansible-playbook main.yml
[DEPRECATION WARNING]: DISPLAY_SKIPPED_HOSTS option, environment variables without "ANSIBLE_" prefix are deprecated , use the "ANSIBLE_DISPLAY_SKIPPED_HOSTS" environment variable
instead. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [PR #65835 Test Playbook] ******************************************************************************************************************************************************

TASK [vmware_guest_info] ************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ************************************************************************************************************************************************************************
ok: [localhost] => (item=Network adapter 1) => {
    "msg": {
        "_vimtype": "vim.vm.device.VirtualVmxnet3",
        "addressType": "assigned",
        "backing": {
            "_vimtype": "vim.vm.device.VirtualEthernetCard.NetworkBackingInfo",
            "deviceName": "VM Network",
            "inPassthroughMode": null,
            "network": "vim.Network:network-227",
            "useAutoDetect": false
        },
        "connectable": {
            "_vimtype": "vim.vm.device.VirtualDevice.ConnectInfo",
            "allowGuestControl": true,
            "connected": false,
            "migrateConnect": "unset",
            "startConnected": true,
            "status": "untried"
        },
        "controllerKey": 100,
        "deviceInfo": {
            "_vimtype": "vim.Description",
            "label": "Network adapter 1",
            "summary": "VM Network"
        },
        "externalId": null,
        "key": 4000,
        "macAddress": "00:50:56:b2:5f:4a",
        "resourceAllocation": {
            "_vimtype": "vim.vm.device.VirtualEthernetCard.ResourceAllocation",
            "limit": -1,
            "reservation": 0,
            "share": {
                "_vimtype": "vim.SharesInfo",
                "level": "normal",
                "shares": 50
            }
        },
        "slotInfo": {
            "_vimtype": "vim.vm.device.VirtualDevice.PciBusSlotInfo",
            "pciSlotNumber": 192
        },
        "unitNumber": 7,
        "uptCompatibilityEnabled": true,
        "wakeOnLanEnabled": true
    }
}

TASK [vmware_guest_network] *********************************************************************************************************************************************************
changed: [localhost]

TASK [debug] ************************************************************************************************************************************************************************
ok: [localhost] => {
    "r": {
        "changed": true,
        "failed": false,
        "network_data": {
            "0": {
                "allow_guest_ctl": true,
                "connected": false,
                "device_type": "VMXNET3",
                "directpath_io": true,
                "label": "Network adapter 1",
                "mac_addr": "00:50:56:b2:5f:4a",
                "name": "VM Network",
                "start_connected": true,
                "unit_number": 7,
                "wake_onlan": true
            },
            "1": {
                "allow_guest_ctl": true,
                "connected": false,
                "device_type": "VMXNET3",
                "directpath_io": true,
                "label": "Network adapter 2",
                "mac_addr": "00:50:56:b2:2b:e9",
                "name": "DC0_DVPG0",
                "start_connected": true,
                "unit_number": 8,
                "wake_onlan": true
            }
        }
    }
}

TASK [vmware_guest_info] ************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ************************************************************************************************************************************************************************
ok: [localhost] => (item=Network adapter 1) => {
    "msg": {
        "_vimtype": "vim.vm.device.VirtualVmxnet3",
        "addressType": "assigned",
        "backing": {
            "_vimtype": "vim.vm.device.VirtualEthernetCard.NetworkBackingInfo",
            "deviceName": "VM Network",
            "inPassthroughMode": null,
            "network": "vim.Network:network-227",
            "useAutoDetect": false
        },
        "connectable": {
            "_vimtype": "vim.vm.device.VirtualDevice.ConnectInfo",
            "allowGuestControl": true,
            "connected": false,
            "migrateConnect": "unset",
            "startConnected": true,
            "status": "untried"
        },
        "controllerKey": 100,
        "deviceInfo": {
            "_vimtype": "vim.Description",
            "label": "Network adapter 1",
            "summary": "VM Network"
        },
        "externalId": null,
        "key": 4000,
        "macAddress": "00:50:56:b2:5f:4a",
        "resourceAllocation": {
            "_vimtype": "vim.vm.device.VirtualEthernetCard.ResourceAllocation",
            "limit": -1,
            "reservation": 0,
            "share": {
                "_vimtype": "vim.SharesInfo",
                "level": "normal",
                "shares": 50
            }
        },
        "slotInfo": {
            "_vimtype": "vim.vm.device.VirtualDevice.PciBusSlotInfo",
            "pciSlotNumber": 192
        },
        "unitNumber": 7,
        "uptCompatibilityEnabled": true,
        "wakeOnLanEnabled": true
    }
}
ok: [localhost] => (item=Network adapter 2) => {
    "msg": {
        "_vimtype": "vim.vm.device.VirtualVmxnet3",
        "addressType": "assigned",
        "backing": {
            "_vimtype": "vim.vm.device.VirtualEthernetCard.NetworkBackingInfo",
            "deviceName": "DC0_DVPG0",
            "inPassthroughMode": null,
            "network": "vim.Network:network-286",
            "useAutoDetect": false
        },
        "connectable": {
            "_vimtype": "vim.vm.device.VirtualDevice.ConnectInfo",
            "allowGuestControl": true,
            "connected": false,
            "migrateConnect": "unset",
            "startConnected": true,
            "status": "untried"
        },
        "controllerKey": 100,
        "deviceInfo": {
            "_vimtype": "vim.Description",
            "label": "Network adapter 2",
            "summary": "DC0_DVPG0"
        },
        "externalId": null,
        "key": 4001,
        "macAddress": "00:50:56:b2:2b:e9",
        "resourceAllocation": {
            "_vimtype": "vim.vm.device.VirtualEthernetCard.ResourceAllocation",
            "limit": -1,
            "reservation": 0,
            "share": {
                "_vimtype": "vim.SharesInfo",
                "level": "normal",
                "shares": 50
            }
        },
        "slotInfo": null,
        "unitNumber": 8,
        "uptCompatibilityEnabled": true,
        "wakeOnLanEnabled": true
    }
}

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Could you try the below step?

```
[root@localhost 65919]# python3 -m venv venv
[root@localhost 65919]# source venv/bin/activate
(venv) [root@localhost 65919]# curl -L https://github.com/ansible/ansible/archive/414d392f3f9f1b4deed010f5d78278aadc29b754.zip -O
(venv) [root@localhost 65919]# unzip 414d392f3f9f1b4deed010f5d78278aadc29b754.zip
(venv) [root@localhost 65919]# mv ansible-414d392f3f9f1b4deed010f5d78278aadc29b754/ ansible-pr-test
(venv) [root@localhost 65919]# cd ansible-pr-test/
(venv) [root@localhost ansible-pr-test]# pip install -r requirements.txt pyvmomi
(venv) [root@localhost ansible-pr-test]# python setup.py install
(venv) [root@localhost ansible-pr-test]# vi main.yml
Paste `PR #65835 Test Playbook` and change
(venv) [root@localhost ansible-pr-test]# ansible-playbook main.yml
```

Can you let us know the result of Playbook?

**Comment by Akasurde** [comment]
@arpadhajdu Hey, can follow the steps given by @sky-joker and let us know if it works for you? since it is also working for me.

Thanks

needs_info

**Comment by WintyBe** [comment]
I'm not OP, but I have the exact same issue. I tried the PR in a venv according to the steps, but it also doesn't work for me. The playbook:
```
- name: PR Test
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add NIC to DVS
      vmware_guest_network:
        <<: *vcenter_auth_info
        name: "TEST-VM"
        networks:
          - name: "539_inbound-mgmt"
            dvswitch_name: "POCBEHA_01"
            connected: true
            start_connected: true
            state: new
```

It will add a NIC in the given VLAN, but on a Standard vSwitch. I tried this twice on a VM without NICs but I can see in the VMware console that it's added on a Standard vSwitch.
```
changed: [127.0.0.1] => changed=true
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  network_data:
    '0':
      allow_guest_ctl: true
      connected: false
      device_type: VMXNET3
      directpath_io: true
      label: Network adapter 1
      mac_addr: 00:50:56:87:ba:c4
      name: 539_inbound-mgmt
      start_connected: true
      unit_number: 7
      wake_onlan: true
    '1':
      allow_guest_ctl: true
      connected: false
      device_type: VMXNET3
      directpath_io: true
      label: Network adapter 2
      mac_addr: 00:50:56:87:90:8e
      name: 539_inbound-mgmt
      start_connected: true
      unit_number: 8
      wake_onlan: true
```

I then manually added the same VLAN on the correct DVS. I tried the playbook again just to get the output, but you can see that for the manual NIC it shows a different name (starting with DVSwitch).
```
changed: [127.0.0.1] => changed=true
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  network_data:
    '0':
      allow_guest_ctl: true
      connected: false
      device_type: VMXNET3
      directpath_io: true
      label: Network adapter 1
      mac_addr: 00:50:56:87:ba:c4
      name: 539_inbound-mgmt
      start_connected: true
      unit_number: 7
      wake_onlan: true
    '1':
      allow_guest_ctl: true
      connected: false
      device_type: VMXNET3
      directpath_io: true
      label: Network adapter 2
      mac_addr: 00:50:56:87:90:8e
      name: 539_inbound-mgmt
      start_connected: true
      unit_number: 8
      wake_onlan: true
    '2':
      allow_guest_ctl: true
      connected: false
      device_type: VMXNET3
      directpath_io: true
      label: Network adapter 3
      mac_addr: 00:50:56:87:20:29
      name: 'DVSwitch: 50 07 0b 58 24 d6 71 b9-75 58 22 90 17 5d 4f b7'
      start_connected: true
      unit_number: 9
      wake_onlan: true
```

The same shows in the output from vmware_guest_info:
```
ok: [127.0.0.1] => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  instance:
    config:
      hardware:
        device:
        - _vimtype: vim.vm.device.VirtualVmxnet3
          addressType: assigned
          backing:
            _vimtype: vim.vm.device.VirtualEthernetCard.NetworkBackingInfo
            deviceName: 539_inbound-mgmt
            inPassthroughMode: null
            network: vim.Network:network-24901
            useAutoDetect: false
          connectable:
            _vimtype: vim.vm.device.VirtualDevice.ConnectInfo
            allowGuestControl: true
            connected: false
            migrateConnect: null
            startConnected: true
            status: untried
          controllerKey: 100
          deviceInfo:
            _vimtype: vim.Description
            label: Network adapter 1
            summary: 539_inbound-mgmt
          externalId: null
          key: 4000
          macAddress: 00:50:56:87:ba:c4
          resourceAllocation:
            _vimtype: vim.vm.device.VirtualEthernetCard.ResourceAllocation
            limit: -1
            reservation: 0
            share:
              _vimtype: vim.SharesInfo
              level: normal
              shares: 50
          slotInfo:
            _vimtype: vim.vm.device.VirtualDevice.PciBusSlotInfo
            pciSlotNumber: 160
          unitNumber: 7
          uptCompatibilityEnabled: true
          wakeOnLanEnabled: true
        - _vimtype: vim.vm.device.VirtualVmxnet3
          addressType: assigned
          backing:
            _vimtype: vim.vm.device.VirtualEthernetCard.NetworkBackingInfo
            deviceName: 539_inbound-mgmt
            inPassthroughMode: null
            network: vim.Network:network-24901
            useAutoDetect: false
          connectable:
            _vimtype: vim.vm.device.VirtualDevice.ConnectInfo
            allowGuestControl: true
            connected: false
            migrateConnect: null
            startConnected: true
            status: untried
          controllerKey: 100
          deviceInfo:
            _vimtype: vim.Description
            label: Network adapter 2
            summary: 539_inbound-mgmt
          externalId: null
          key: 4001
          macAddress: 00:50:56:87:90:8e
          resourceAllocation:
            _vimtype: vim.vm.device.VirtualEthernetCard.ResourceAllocation
            limit: -1
            reservation: 0
            share:
              _vimtype: vim.SharesInfo
              level: normal
              shares: 50
          slotInfo: null
          unitNumber: 8
          uptCompatibilityEnabled: true
          wakeOnLanEnabled: true
        - _vimtype: vim.vm.device.VirtualVmxnet3
          addressType: assigned
          backing:
            _vimtype: vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo
            port:
              _vimtype: vim.dvs.PortConnection
              connectionCookie: null
              portKey: null
              portgroupKey: dvportgroup-9646
              switchUuid: 50 07 0b 58 24 d6 71 b9-75 58 22 90 17 5d 4f b7
          connectable:
            _vimtype: vim.vm.device.VirtualDevice.ConnectInfo
            allowGuestControl: true
            connected: false
            migrateConnect: null
            startConnected: true
            status: untried
          controllerKey: 100
          deviceInfo:
            _vimtype: vim.Description
            label: Network adapter 3
            summary: 'DVSwitch: 50 07 0b 58 24 d6 71 b9-75 58 22 90 17 5d 4f b7'
          externalId: null
          key: 4002
          macAddress: 00:50:56:87:20:29
          resourceAllocation:
            _vimtype: vim.vm.device.VirtualEthernetCard.ResourceAllocation
            limit: -1
            reservation: 0
            share:
              _vimtype: vim.SharesInfo
              level: normal
              shares: 50
          slotInfo: null
          unitNumber: 9
          uptCompatibilityEnabled: true
          wakeOnLanEnabled: true
```
