### ISSUE TITLE
yum/apt with_items ignores filters, prefixes

### ISSUE THREAD

**Issue by Habbie** [ansible/ansible#6592]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.4.3
##### Environment:

RHEL 6.5 from RHEL 6.5; bug appears to be generic though.
##### Summary:

The hack at https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/__init__.py#L586 appears to break filter usage (name={{item | basename }}).
##### Steps To Reproduce:

This code:

```
  - name: install RPMs
    yum: name=/root/{{ item }}
    notify: restart recursor
    with_items:
    - '{{ recursor_rpm_url | basename }}'
    - '{{ pdnsmgrd_rpm_url | basename }}'
```

Should behave identically to:

```
  - name: install RPMs
    yum: name=/root/{{ item | basename }}
    notify: restart recursor
    with_items:
    - '{{ recursor_rpm_url }}'
    - '{{ pdnsmgrd_rpm_url }}'
```

However, the second version feeds the full URLs (that I have in those vars) to yum.

In both cases /root/ is dropped as well, but the first version accepts this because ansible is running from /root anyway.
##### Expected Results:

Both versions do the same, honoring /root and | basename.
##### Actual Results:

One version works, mostly by accident. The other does not work at all.
