### ISSUE TITLE
STDOUT Json with Strategy Free not formatted correctly

### ISSUE THREAD

**Issue by ggedde** [ansible/ansible#65931]
##### SUMMARY

When using stdout_callback = json in my ansible.cfg file and setting my playbook to be strategy: free the response tasks get mixed up. I am getting responses from one task in another task.  However, removing strategy: free then everything is fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

stdout_callback json
strategy: free

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = None
  configured module search path = [u'/Users/geoff/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```
I originally tested this on 2.8.4 and still got the same issue then upgraded and still the same issue.

##### CONFIGURATION

```paste below
[defaults]
retry_files_enabled = false
stdout_callback = json
deprecation_warnings = false

[ssh_connection]
retries=3
```

##### OS / ENVIRONMENT

Mac OS 10.14.6 (18G103)

##### STEPS TO REPRODUCE

Here is my playbook:

```yaml
---
- hosts: all
  strategy: free
  remote_user: root

  tasks:

  - name: hostname
    shell: 'echo $(hostname)'

  - name: load_average
    shell: "echo $(uptime | awk '{print $11}')"

  - name: cpu_idle
    shell: "echo $(vmstat 1 2 | tail -1 | awk '{print $15}')"

  - name: disk_size
    shell: 'echo $(df --output=size / | tail -1)'
  
  - name: disk_used
    shell: 'echo $(df --output=used / | tail -1)'
  
  - name: disk_available
    shell: 'echo $(df --output=avail / | tail -1)'
  
  - name: memory_size
    shell: "echo $(free -m -t | tail -1 | awk '{print $2}')"
  
  - name: memory_used
    shell: "echo $(free -m -t | tail -1 | awk '{print $3}')"
 
  - name: memory_available
    shell: "echo $(free -m -t | tail -1 | awk '{print $4}')"
```

##### EXPECTED RESULTS

When running without strategy free then everything is aligned correctly.
Example:
```
Array 
(
    [hosts] => Array
        (
            [xxx.xxx.xxx.xxx] => Array
                (
                    [_ansible_no_log] => 
                    [action] => command
                    [changed] => 1
                    [cmd] => echo $(df --output=used / | tail -1)
                    [delta] => 0:00:00.004550
                    [end] => 2019-12-17 22:04:10.091245
                    [invocation] => Array
                        (
                            [module_args] => Array
                                (
                                    [_raw_params] => echo $(df --output=used / | tail -1)
                                    [_uses_shell] => 1
                                    [argv] => 
                                    [chdir] => 
                                    [creates] => 
                                    [executable] => 
                                    [removes] => 
                                    [stdin] => 
                                    [stdin_add_newline] => 1
                                    [strip_empty_ends] => 1
                                    [warn] => 1
                                )

                        )

                    [rc] => 0
                    [start] => 2019-12-17 22:04:10.086695
                    [stderr] => 
                    [stderr_lines] => Array
                        (
                        )

                    [stdout] => 3574792
                    [stdout_lines] => Array
                        (
                            [0] => 3574792
                        )

                )

        )

    [task] => Array
        (
            [duration] => Array
                (
                    [end] => 2019-12-17T22:04:10.245292Z
                    [start] => 2019-12-17T22:04:09.392090Z
                )

            [id] => 80e65022-cacc-ca0e-762a-00000000000e
            [name] => disk_used
        )
)
```
As you can see the `disk_used` command is returned with the `disk_used` task.

##### ACTUAL RESULTS

But with strategy: free some tasks come back not in the correct placement.
Example:

```paste below
Array
(
    [hosts] => Array
        (
            [xxx.xxx.xxx.xxx] => Array
                (
                    [_ansible_no_log] => 
                    [action] => command
                    [changed] => 1
                    [cmd] => echo $(df --output=used / | tail -1)
                    [delta] => 0:00:00.004723
                    [end] => 2019-12-17 22:04:10.629498
                    [invocation] => Array
                        (
                            [module_args] => Array
                                (
                                    [_raw_params] => echo $(df --output=used / | tail -1)
                                    [_uses_shell] => 1
                                    [argv] => 
                                    [chdir] => 
                                    [creates] => 
                                    [executable] => 
                                    [removes] => 
                                    [stdin] => 
                                    [stdin_add_newline] => 1
                                    [strip_empty_ends] => 1
                                    [warn] => 1
                                )

                        )

                    [rc] => 0
                    [start] => 2019-12-17 22:04:10.624775
                    [stderr] => 
                    [stderr_lines] => Array
                        (
                        )

                    [stdout] => 5418200
                    [stdout_lines] => Array
                        (
                            [0] => 5418200
                        )

                )

        )

    [task] => Array
        (
            [duration] => Array
                (
                    [end] => 2019-12-17T22:04:10.780824Z
                    [start] => 2019-12-17T22:04:10.363869Z
                )

            [id] => 80e65022-cacc-ca0e-762a-00000000000f
            [name] => disk_available
        )

)
```
As you can see the `disk_used` command is returned in the `disk_available` task.

I am running this currently with 3 hosts.
