### ISSUE TITLE
Inconsistencies of ansible_python in connection with interpreter_python=auto ...

### ISSUE THREAD

**Issue by assarbad** [ansible/ansible#65944]
##### SUMMARY
There was a question [here](https://devops.stackexchange.com/q/10142/) which showed a peculiar behavior of Ansible.

I investigated this a little further and noticed that there are potentially two inconsistencies here:

1. when setting `interpreter_python=auto` in `ansible.cfg` the fact `ansible_python` is lying (it claims to use Python 3.x - in line with Ansible's default for Ubuntu 18.04 -, but in fact uses Python 2.x).
1. Invoking `ansible-playbook` without `ansible.cfg` but with the corresponding environment variable `INTERPRETER_PYTHON` (`env INTERPRETER_PYTHON=auto ansible-playbook ...`) the fact `ansible_python` truthfully claims to be using Python 2.x. But this means that the environment variable behaves differently from when setting it in `ansible.cfg`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

I'd guess this issue is for the core, not for `dig` (which is involved in the MWE).

##### ANSIBLE VERSION

```
$ ansible --version 2>&1|sed 's|'$LOGNAME'|username|g'
ansible 2.9.2
  config file = /home/username/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
```
(empty output)

##### OS / ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

###### Inconsistency 1

1. Make sure neither `python-dnspython` nor `python3-dnspython` are installed (`apt remove -y python-dnspython python3-dnspython`).
1. place an `ansible.cfg` into your current folder with the following content:
    ```
    [defaults]
    interpreter_python=auto
    ```
1. place a playbook (`ansible_python.yml`) into the current folder as well:
    ```yaml
    ---
    
    - hosts: all
      tasks:
        - block:
          - name: Install python-dnspython
            apt: pkg=python-dnspython update_cache=yes install_recommends=no state=present
            when: ansible_python.version.major == 2
          - name: Install python3-dnspython
            apt: pkg=python3-dnspython update_cache=yes install_recommends=no state=present
            when: ansible_python.version.major == 3
          become: true
        - debug:
            var: ansible_python
        - debug:
            msg: "{{lookup('dig', 'example.com./A')}}"
    ```
1. run `ansible-playbook -i localhost, -c local ansible_python.yml` from the current folder.

###### Inconsistency 2

1. Make sure neither `python-dnspython` nor `python3-dnspython` are installed (`apt remove -y python-dnspython python3-dnspython`).
1. Make sure _no_ `ansible.cfg` exists in the current folder.
1. place a playbook (`ansible_python.yml`) into the current folder as well:
    ```yaml
    ---
    
    - hosts: all
      tasks:
        - block:
          - name: Install python-dnspython
            apt: pkg=python-dnspython update_cache=yes install_recommends=no state=present
            when: ansible_python.version.major == 2
          - name: Install python3-dnspython
            apt: pkg=python3-dnspython update_cache=yes install_recommends=no state=present
            when: ansible_python.version.major == 3
          become: true
        - debug:
            var: ansible_python
        - debug:
            msg: "{{lookup('dig', 'example.com./A')}}"
    ```
1. run `env INTERPRETER_PYTHON=auto ansible-playbook -i localhost, -c local ansible_python.yml` from the current folder.

###### Inconsistency 1

Since the package installation decides whether to install `python-dnspython` or `python3-dnspython` based on the value of `ansible_python.version.major` the expectation _with and without_ `interpreter_python=auto` set would be that `ansible_python` reflects exactly the interpreter used to run `ansible`/`ansible-playbook`.

```
$ ansible-playbook -i localhost, -c local ansible_python.yml

PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Install python-dnspython] ***********************************************************************************************************************************************************************************
changed: [localhost]

TASK [Install python3-dnspython] **********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_python": {
        "executable": "/usr/bin/python",
        "has_sslcontext": true,
        "type": "CPython",
        "version": {
            "major": 2,
            "micro": 17,
            "minor": 7,
            "releaselevel": "final",
            "serial": 0
        },
        "version_info": [
            2,
            7,
            17,
            "final",
            0
        ]
    }
}

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "93.184.216.34"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

###### Inconsistency 2

This behaves the way I would expect it to, but since I am setting the environment variable `INTERPRETER_PYTHON=auto`, I'd expect it to be _consistent_ with the above case.

###### Inconsistency 1

```
$ ansible-playbook -i localhost, -c local ansible_python.yml

PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Install python-dnspython] ***********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [Install python3-dnspython] **********************************************************************************************************************************************************************************
changed: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_python": {
        "executable": "/usr/bin/python3",
        "has_sslcontext": true,
        "type": "cpython",
        "version": {
            "major": 3,
            "micro": 9,
            "minor": 6,
            "releaselevel": "final",
            "serial": 0
        },
        "version_info": [
            3,
            6,
            9,
            "final",
            0
        ]
    }
}

TASK [debug] ******************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errors.AnsibleError'>, original message: The dig lookup requires the python 'dnspython' library and it is not installed"}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
```

Here `python3-dnspython` was picked based on `ansible_python.version.major == 3` and was installed. But since Ansible is running on Python 2.x the `lookup('dig', ...)` fails.

###### Inconsistency 2

```
$ env INTERPRETER_PYTHON=auto ansible-playbook -i localhost, -c local ansible_python.yml

PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Install python-dnspython] ***********************************************************************************************************************************************************************************
changed: [localhost]

TASK [Install python3-dnspython] **********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_python": {
        "executable": "/usr/bin/python",
        "has_sslcontext": true,
        "type": "CPython",
        "version": {
            "major": 2,
            "micro": 17,
            "minor": 7,
            "releaselevel": "final",
            "serial": 0
        },
        "version_info": [
            2,
            7,
            17,
            "final",
            0
        ]
    }
}

TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "93.184.216.34"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

Here `ansible_python` contains the truth ("running on Python 2.x") and therefore the correct package (`python-dnspython`) gets installed. However, this deviates from the expected behavior because the environment variable `INTERPRETER_PYTHON=auto` should behave like `interpreter_python=auto` in `ansible.cfg`.
