### ISSUE TITLE
htpasswd module non idempotent

### ISSUE THREAD

**Issue by gabops** [ansible/ansible#65946]
##### SUMMARY
- htpasswd module is not idempotent if you pass an already hashed password and using  "crypt_scheme: plaintext". Doing this can be useful in scenarios where you do not wanna expose the passwords even if they are encrypted using ansible-vault.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
htpasswd module.

##### ANSIBLE VERSION
```paste below
ansible 2.9.0
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/test/.venv/lib64/python3.7/site-packages/ansible
  executable location = /home/user/test/.venv/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```paste below
No output from the command.
```

##### OS / ENVIRONMENT
Host running Fedora 31. Molecule tests running over Centos 6, Centos 7, Amazon Linux 1 and Amazon Linux 2.

##### STEPS TO REPRODUCE
Declare a user with a password already hashed (md5)
```yaml
users:
  - username: john.doe
    password: $apr1$RqTZxFQr$Zg228CXszmHkrVHWwUc0x/
```
And passing it to the htpasswd module like this.
```yaml
- name: Configure users
  htpasswd:
    path: /etc/httpd/passwd
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    crypt_scheme: plaintext
    state: present
  loop: "{{ users }}"
  no_log: true
```

##### EXPECTED RESULTS
The module should limit to add the value of the password as just 'plaintext' as declared.

##### ACTUAL RESULTS
The module generates 'changed' status everytime even being obviously the same password (hash) between executions. This does not happen when using a password which is not a hash such as for example "$myP4$$word".

Just important to mention that if I escape the first character of the hash ('$' with '\\$' or '$$') it behaves idempotently again however it adds literally the escape character to the password making it non usable for obvious reasons.

```paste below
ERROR: Idempotence test failed because of the following tasks:
* [instance] => test-role : Configure users
```
