### ISSUE TITLE
postgresql_privs ALL_IN_SCHEMA does not behave like GRANT ON ALL TABLES IN SCHEMA

### ISSUE THREAD

**Issue by geekq** [ansible/ansible#65951]
##### SUMMARY

The `objs: ALL_IN_SCHEMA` implies with its name, that it would behave like GRANT ON ALL TABLES IN SCHEMA.
Instead it iterates with
```
if p.type == 'table' and p.objs == 'ALL_IN_SCHEMA':
            objs = conn.get_all_tables_in_schema(p.schema)
```
over currently existing tables (typically none after the database is created).

Once application specific DB migrations (e.g. Java's Flyway or ruby on rails' db:migrate) create tables, the desired permissions on tables are missing.

I think it would be more intuitive, if `objs: ALL_IN_SCHEMA` would resemble the behavior of `GRANT ON ALL TABLES IN SCHEMA` or is the current behavior really desired? For which use case it would be helpful then? Only if tables are created via ansible? If ansible is run after the application/DB migrations are already run?

As a workaround I am trying to use `type: default_privs` to implement the desired behavior, but it feels much more complicated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_privs_module

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /home/vd/.ansible.cfg
  configured module search path = ['/home/myname/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myname/pyenvs/myenv/lib/python3.7/site-packages/ansible
  executable location = /home/myname/pyenvs/myenv/bin/ansible
  python version = 3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_TIMEOUT(/home/.../.ansible.cfg) = 18
RETRY_FILES_ENABLED(/home/.../.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: Set DB access for the new user
  postgresql_privs:
    db: '{{ db_name }}'
    login_unix_socket: '/var/run/postgresql'
    role: '{{ username }}'
    type: database
    obj: '{{ db_name }}'
    privs: CONNECT
  become_user: postgres
  become: yes
- name: Set table access for the new user
  postgresql_privs:
    db: '{{ db_name }}'
    login_unix_socket: '/var/run/postgresql'
    role: '{{ username }}'
    objs: ALL_IN_SCHEMA
    privs: 'INSERT,SELECT,UPDATE,DELETE,TRUNCATE'
  become_user: postgres
  become: yes
```

##### EXPECTED RESULTS

```
sudo -u postgres psql
CREATE TABLE mydata(ID INT PRIMARY KEY NOT NULL);
\dp
# the list of access priviliges to contain the rights for user on the new table
```

##### ACTUAL RESULTS

```
# the list of access privileges does not contain the desired user
```

```paste below

```
