### ISSUE TITLE
Impossible to renew a valid wildcard certificate before the end of the authorizations cache period

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#65966]
##### SUMMARY
I inadvertently lost the private key which has been used for the creation of a wildcard certificate through let's encrypt the day it was renewed.
But now, it cannot be renewed again despite ```force``` set to yes and ```remaining_days``` set to 90 or 91.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
acme_certificate

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path =
  ansible python module location = git-ansible/lib/ansible
  executable location = git-ansible/bin/ansible
  python version = 2.7.17 (default, Oct 19 2019, 23:36:22) [GCC 9.2.1 20191008]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 240
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
controller host: Ubuntu focal 20.04
target: Ubuntu focal 20.04
```

##### STEPS TO REPRODUCE
```
- name: Renewing a DNS domain with Let’s Encrypt CA for a wildcard domain server Certificates - Phase I
  local_action:
        module: acme_certificate
        account_email: "{{ email_address }}"
        account_key_src: "{{ key }}"
        acme_directory: "{{ acme_directory }}"
        acme_version: "{{ acme_version }}"
        chain_dest: "{{ chain_dest }}"
        challenge: dns-01
        csr: "{{ csr }}"
        dest: "{{ dest }}"
        force: yes
        fullchain_dest: "{{ fullchain_dest }}"
        remaining_days: 90
        select_crypto_backend: "{{ crypto_backend }}"
        terms_agreed: "{{ terms_agreed }}"
        validate_certs: "{{ validate_certs }}"
  register: return_phase_I
```

##### EXPECTED RESULTS
A renewed certificate

##### ACTUAL RESULTS
The certificate is not renewed.
```
< TASK [tls_cert : Print return_phase_I] >
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: tls_validate.server_cert.lets_encrypt.wildcard.yml:57
ok: [ns1.sdxlive.com] => {
    "return_phase_I": {
...
        "authorizations": {
            "*.sdxlive.com": {
                "challenges": [
                    {
                        "status": "valid", 
...
                    }
                ], 
                "expires": "2020-01-24T15:38:16Z", 
                "identifier": {
                    "type": "dns", 
                    "value": "sdxlive.com"
                }, 
                "status": "valid", 
...
                "wildcard": true
            }, 
            "sdxlive.com": {
                "challenges": [
...
                    {
                        "status": "valid", 
...
                    }, 
...
                ], 
                "expires": "2020-01-24T15:25:28Z", 
                "identifier": {
                    "type": "dns", 
                    "value": "sdxlive.com"
                }, 
                "status": "valid", 
...
            }
        }, 
        "cert_days": 89, 
        "challenge_data": {}, 
        "challenge_data_dns": {}, 
        "changed": true, 
        "failed": false, 
...
    }
}
```
The ```challenge_data``` field is empty, meaning the certificate has not been renewed, **despite 89 < 90**.

Am I missing something here?
