### ISSUE TITLE
vmware_guest_network: Unable to Connect the newly added interface

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#65968]
##### SUMMARY
Using **vmware_guest_network** I am able to add multiple network interface to the VM but unable to connect them when starting the vm. Even manually its not allowing to connect them. But when the VM is shutdown and I am selecting the 'Edit' option, its showing the interfaces are as connected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_network

##### ANSIBLE VERSION
```
# pip show ansible
Name: ansible
Version: 2.9.2
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python2.7/dist-packages
Requires: jinja2, PyYAML, cryptography

# pip show pyvmomi
Name: pyvmomi
Version: 6.7.1.2018.12
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, requests
```

##### CONFIGURATION
```
No specific configuration required.
```

##### OS / ENVIRONMENT
Ansible Provision Server: Ubuntu 18.04 LTS
vCenter: 6.5 / 6.7
ESXi: 6.5 / 6.7

##### STEPS TO REPRODUCE
```
# cat deploy-ova.yml
---
- name: Firewall Deployment
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_vars.yml
  tasks:
    - name: PA Firewall OVA Deployment
      vmware_deploy_ovf:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        datastore: '{{ vsphere_datastore }}'
        name: '{{ vsphere_vm_name }}'
        resource_pool: '{{ vsphere_resourcepool }}'
        disk_provisioning: 'thin'
        folder: '/{{ vsphere_datacenter }}/vm/{{ vsphere_folder }}'
        validate_certs: 'no'
        networks:
          "VM Network" : "{{ vsphere_network01 }}"
          "VM Network" : "{{ vsphere_network02 }}"
        power_on: 'no'
        fail_on_spec_warnings: 'yes'
        wait_for_ip_address: 'no'
        ovf: '/root/OVA/xxxxxxxxx.ova'
      delegate_to: localhost

    - name: Attach Multiple Network Adapters
      vmware_guest_network:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        validate_certs: 'no'
        cluster: '{{ vsphere_cluster }}'
        name: '{{ vsphere_vm_name }}'
        networks:
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 3"
            connected: true
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 4"
            connected: true
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 5"
            connected: true
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 6"
            connected: true
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 7"
            connected: true
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 8"
            connected: true
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 9"
            start_connected: true
          - name: "{{ vsphere_network01 }}"
            state: new
            device_type: vmxnet3
            label: "Network adapter 10"
            start_connected: true

    - name: Start the virtual machine
      vmware_guest:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        validate_certs: 'no'
        cluster: '{{ vsphere_cluster }}'
        name: '{{ vsphere_vm_name }}'
        state: poweredon
```
```
# cat vsphere_vars.yml
# vCenter Specific Variable
vsphere_datacenter: 'xxxxxxx'
vsphere_folder: 'Ansible-Demo-uskar'
vsphere_resourcepool: 'xxxxxx'
vsphere_cluster: 'xxxxxx'
vsphere_datastore: 'xxxxxx'
vsphere_vm_name: 'xxxxxx'
vsphere_network01: '192.168.0.1-management'
vsphere_network02: '192.168.1.1-deployment'
```
```
# cat vsphere_creds.yml
# vCenter information
vcenter_hostname: 'xxxxxxxxxxxx'
vcenter_username: 'ansibledemo@vsphere.local'
vcenter_password: 'Ansible@123!'
```

##### EXPECTED RESULTS
It should attach the module and connect it while starting the VM

##### ACTUAL RESULTS
Its able to connect only two interfaces mentioned in **vmware_deploy_ovf** module's function. Other interfaces are available but not connected.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest_network.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_network.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Udayendu, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Udayendu** [comment]
One more observation:
  - the dvswitched based port groups are already available but **vmware_guest_network** is creating the standard vswitch and attaching them.
  - And while removing the vm, its removing the standard vswitch created by this module.

Also FYI, both the dvSwitch based portgroups are part of the same dvSwitch:
```
vsphere_network01: '192.168.0.1-management'
vsphere_network02: '192.168.1.1-deployment'
```

Above are the dvSwitch based portgroup name.

**Comment by Udayendu** [comment]
I did some more testing and found that **vmware_guest_network** module is unable to handle dvswitch based port groups and creating them as the standard switch. And as those newly created standard vSwitch are not mapped to any host, its not allowing to connect that.

So if this module supporting only standard vSwitch ?

**Comment by Akasurde** [comment]
resolved_by_pr #65994

**Comment by Akasurde** [comment]
@Udayendu, Could you please check PR #65994 and let us know if it works for you ? <br><br>Please check [How to test a PR](https://docs.ansible.com/ansible/latest/dev_guide/testing.html#how-to-test-a-pr) for more help. <br><br> Thanks. <br><br> needs_info

**Comment by Udayendu** [comment]
@Akasurde, I did some test and found that e318cd0 is working well. Its able to add/remove/modify dvSwitch based portgroups. Thanks for fixing it. Please do the back port of this patch to ansible 2.9

**Comment by gflex** [comment]
This is still not working for VMC (VMware Cloud on AWS):
playbook:

```
- name: add network adapter to virtual machine
  vmware_guest_network:
    hostname: "{{ vcenter }}"
    username: "{{ vault_vc_user }}"
    password: "{{ vault_vc_pass }}"
    datacenter: "{{ sddc_datacenter }}"
    validate_certs: no
    name: "{{ inventory_hostname }}"
    gather_network_info: false
    networks:
      - name: "{{ sddc_ecosystem_net.name }}"
        state: 'new'
        label: 'Network adapter 2'
        connected: true
        start_connected: true
  delegate_to: "{{ hostvars[groups['jump_hosts'][0]].ansible_host }}"
  register: network_info
```

result is:

```
Unable to find the specified network adapter: {'name': 'sddc-cgw-ecosystem-net', 'state': 'present', 'label': 'eth1', 'connected': True}
```
And this is what I get from from registering network info
```
{
    "0": {
        "allow_guest_ctl": true,
        "connected": true,
        "device_type": "VMXNET3",
        "label": "Network adapter 1",
        "mac_addr": "00:50:56:ad:6a:11",
        "name": "nsx.LogicalSwitch: 4c9a1fb0-905f-4ca6-b00a-eeabd113ec7a",
        "start_connected": true,
        "unit_number": 7,
        "wake_onlan": false
    },
    "1": {
        "allow_guest_ctl": true,
        "connected": false,
        "device_type": "VMXNET3",
        "label": "Network adapter 2",
        "mac_addr": "00:50:56:ad:f7:66",
        "name": "sddc-cgw-ecosystem-net",
        "start_connected": true,
        "unit_number": 8,
        "wake_onlan": true
    }
}
```

Obviously the latter NIC is the one I'm trying to add whereas first is the one that's already present.
Needless to say that network itself is defined and available to add.
