### ISSUE TITLE
ec2_instance is slower than ec2 when creating new EC2 instance

### ISSUE THREAD

**Issue by cenwangumass** [ansible/ansible#65988]
##### SUMMARY
When I use `ec2_instance` to create a new instance, the task is slower than `ec2`. But from AWS console, it can be seen that the instance is started. Also, using `ec2` module doesn't have the same problem; it returns the result normally.

The waiter should be made configurable, so either the instance status 'OK' or the instance state name 'running' is achieved.

##### ISSUE TYPE
- Feature Request

##### COMPONENT NAME
ec2_instance

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/Users/cenwang/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/cenwang/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /Users/cenwang/Library/Python/3.8/bin/ansible
  python version = 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS 10.15

##### STEPS TO REPRODUCE

`ansible-playbook -i hosts playbook.yml`

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Provision a new instance

      ec2_instance:
        region: us-east-1
        name: "vpn-0"
        key_name: "tmp1"
        instance_type: t2.nano
        security_groups:
          - SSH
          - L2TP
        network:
          assign_public_ip: true
        image_id: ami-04b9e92b5572fa0d1
        wait: true

      # ec2:
      #   region: us-east-1
      #   key_name: tmp1
      #   group: ['SSH', 'L2TP']
      #   instance_type: t2.nano
      #   image: ami-04b9e92b5572fa0d1
      #   wait: true
      #   instance_tags:
      #     Name: vpn-0

      register: ec2
```

##### EXPECTED RESULTS

The playbook should return quickly after the instance is brought up.

##### ACTUAL RESULTS

Hungs up forever until timeout

```paste below
task path: /Users/cenwang/Desktop/ansible/playbook.yml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: cenwang
<127.0.0.1> EXEC /bin/sh -c 'echo ~cenwang && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/cenwang/.ansible/tmp/ansible-tmp-1576790481.253783-234155026508482 `" && echo ansible-tmp-1576790481.253783-234155026508482="` echo /Users/cenwang/.ansible/tmp/ansible-tmp-1576790481.253783-234155026508482 `" ) && sleep 0'
Using module file /Users/cenwang/Library/Python/3.8/lib/python/site-packages/ansible/modules/cloud/amazon/ec2_instance.py
<127.0.0.1> PUT /Users/cenwang/.ansible/tmp/ansible-local-6597zaw3a918/tmp6qyfaelk TO /Users/cenwang/.ansible/tmp/ansible-tmp-1576790481.253783-234155026508482/AnsiballZ_ec2_instance.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/cenwang/.ansible/tmp/ansible-tmp-1576790481.253783-234155026508482/ /Users/cenwang/.ansible/tmp/ansible-tmp-1576790481.253783-234155026508482/AnsiballZ_ec2_instance.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'python3 /Users/cenwang/.ansible/tmp/ansible-tmp-1576790481.253783-234155026508482/AnsiballZ_ec2_instance.py && sleep 0'
^C [ERROR]: User interrupted execution
```
