### ISSUE TITLE
eos_vlans is using ios_vlans examples

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#65989]
##### SUMMARY
https://docs.ansible.com/ansible/latest/modules/eos_vlans_module.html#eos-vlans-module

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
eos_vlans

##### ANSIBLE VERSION
N/A on latest/devel

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A, DOC BUG

##### ADDITIONAL INFORMATION
change ios->eos

```
- name: Replace all attributes of specified VLANs with provided configuration
  ios_vlans:
    config:
      - vlan_id: 20
        state: suspend
    state: replaced
```

should be

```
- name: Replace all attributes of specified VLANs with provided configuration
  eos_vlans:
    config:
      - vlan_id: 20
        state: suspend
    state: replaced
```
