### ISSUE TITLE
docker_container: Always recreates the container when restart_policy is changed

### ISSUE THREAD

**Issue by idelsink** [ansible/ansible#65993]
##### SUMMARY

The [docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html) module recreates a container when the `restart_policy` is changed. This can be changed using the `docker update` command.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[docker_container](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html)

##### ANSIBLE VERSION

```shell
$ ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ingmar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 17 2019, 12:09:47) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
<empty>
```

##### OS / ENVIRONMENT

```shell
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 30 (Thirty)
Release:        30
Codename:       Thirty
```

##### STEPS TO REPRODUCE

1. Run the following playbook:
```sh
$ ansible-playbook docker-container-update.yml
```

```yaml
- name: Container update restart_policy
  hosts: localhost
  tasks:
    - name: Container with restart_policy
      docker_container:
        name: restart_policy_example
        image: alpine
        state: present
        restart_policy: unless-stopped
        entrypoint: top
```
2. Change the `restart_policy` to `always` and run it again.
```sh
$ ansible-playbook docker-container-update.yml
```

```yaml
- name: Container update restart_policy
  hosts: localhost
  tasks:
    - name: Container with restart_policy
      docker_container:
        name: restart_policy_example
        image: alpine
        state: present
        restart_policy: unless-stopped
        entrypoint: top
```
3. Notice by using the `docker ps` command that the container is recreated instead of updated.

##### EXPECTED RESULTS
I expect the container to be update with  the new `restart_policy` by using the docker update command:
```sh
$ docker update --restart=<new policy>
``` 

##### ACTUAL RESULTS

The container is recreated instead of updated.
I currently run a `command` task before the container which updates the command.
```yml
# Update docker restart policy
- name: Update docker container restart policy
  command: "docker update --restart={{ (restart_policy == false) | ternary('no', restart_policy) }} {{ container }}"
  ignore_errors: true
```
