### ISSUE TITLE
I can't get loop values via loop, loop_control, loop_var

### ISSUE THREAD

**Issue by zarr12steven** [ansible/ansible#65990]
##### SUMMARY

I hope can use loop get different "TEAM_GROUP", and get the correct item.NAME, item.GROUP....etc, but I always get error below information.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

user,  group and authorized_key

##### ANSIBLE VERSION

```paste below
ansible 2.8.6
  config file = None
  configured module search path = ['/Users/nobody/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

* directory structure

```
.
├── README.md
├── ansible.cfg
├── inventories
│   └── lab
│       ├── group_vars
│       │   └── all
│       │       ├── user
│       │       └── vars
│       └── inventory
├── playbooks
│   └── Ubuntu_Bionic_18.04.yml
└── roles
    └── User
        └── tasks
            ├── main.yml
            └── TEAM_GROUP.yml
```

*  ansible.cfg

```paste below
[defaults]
inventory      = ./inventories/lab
roles_path      = ./roles
host_key_checking = False
retry_files_enabled = False
gathering = smart

fact_caching = jsonfile
fact_caching_connection = ./cache
fact_caching_timeout = 86400

[privilege_escalation]
become=True
become_user=root
```

* cat inventories/lab/group_vars/all/user

```
MIS:
  - NAME: tim
    UID: 1001
    PRIMARY_GROUP: mis
    GID: 1001
    COMMENT: Tim
    SHELL: /bin/bash
    PUBLIC_KEY: tim.pub
    REMOVE_HOME: yes
    STATE: present

  - NAME: john
    UID: 1002
    PRIMARY_GROUP: mis
    GID: 1001
    COMMENT: Tim
    SHELL: /bin/bash
    PUBLIC_KEY: tim.pub
    REMOVE_HOME: yes
    STATE: present

BIG_DATA:
  - NAME: alice
    UID: 1003
    PRIMARY_GROUP: big_data
    GID: 1002
    COMMENT: Tim
    SHELL: /bin/bash
    PUBLIC_KEY: alice.pub
    REMOVE_HOME: yes
    STATE: present

  - NAME: william
    UID: 1004
    PRIMARY_GROUP: big_data
    GID: 1002
    COMMENT: William
    SHELL: /bin/bash
    PUBLIC_KEY: william.pub
    REMOVE_HOME: yes
    STATE: present
```

* cat playbooks/Ubuntu_Bionic_18.04.yml

```
---
- hosts: test
  become: True
  roles:
    - { role: User, TEAM_GROUP: ['MIS', 'BIG_DATA'] }
```

* cat roles/User/tasks/main.yml

```
---
- include_tasks: TEAM_GROUP.yml
  loop:
    - "{{ TEAM_GROUP | flatten }}"
  loop_control:
    loop_var: item
```

* cat roles/User/tasks/TEAM_GROUP.yml

```
---
- debug:
    msg: "var_type is {{ TEAM_GROUP | type_debug }}"

- debug:
    var: "{{ item.NAME }}"
```

##### OS / ENVIRONMENT

My OSX version:

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G95
```

Target OS:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

I can get the correct values.

##### ACTUAL RESULTS

* ansible-playbook -i inventories/lab/inventory playbooks/Ubuntu_Bionic_18.04.yml -vvvv

```paste below
ansible-playbook 2.8.6
  config file = /Users/nobody/ansible/ansible.cfg
  configured module search path = ['/Users/nobody/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
Using /Users/nobody/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /Users/nobody/ansible/inventories/stage/inventory as it did not pass it's verify_file() method
script declined parsing /Users/nobody/ansible/inventories/stage/inventory as it did not pass it's verify_file() method
auto declined parsing /Users/nobody/ansible/inventories/stage/inventory as it did not pass it's verify_file() method
Parsed /Users/nobody/ansible/inventories/stage/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: Ubuntu_Bionic_18.04.yml ********************************************************************************************************************************************************
Positional arguments: playbooks/Ubuntu_Bionic_18.04.yml
verbosity: 4
connection: smart
timeout: 10
become: True
become_method: sudo
tags: ('all',)
inventory: ('/Users/nobody/ansible/inventories/stage/inventory',)
forks: 5
1 plays in playbooks/Ubuntu_Bionic_18.04.yml

PLAY [test] ***********************************************************************************************************************************************************************************
META: ran handlers

TASK [User : include_tasks] *******************************************************************************************************************************************************************
task path: /Users/nobody/ansible/roles/User/tasks/main.yml:11
included: /Users/nobody/ansible/roles/User/tasks/TEAM_GROUP.yml for test

TASK [User : debug] ***************************************************************************************************************************************************************************
task path: /Users/nobody/ansible/roles/User/tasks/TEAM_GROUP.yml:2
ok: [test] => {
    "msg": "var_type is list"
}

TASK [User : debug] ***************************************************************************************************************************************************************************
task path: /Users/nobody/ansible/roles/User/tasks/TEAM_GROUP.yml:5
fatal: [test]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'NAME'\n\nThe error appears to be in '/Users/nobody/ansible/roles/User/tasks/TEAM_GROUP.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ here\n"
}

PLAY RECAP ************************************************************************************************************************************************************************************
test                       : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
