### ISSUE TITLE
openssh_keypair: add option to specify the number of KDF (key derivation function) rounds used

### ISSUE THREAD

**Issue by expeditioneer** [ansible/ansible#66019]
##### SUMMARY
Currently it is not possible to specify the number of KDF (key derivation function) rounds used.
It would be nice to have this as a parameter for the module.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssh_keypair

##### ADDITIONAL INFORMATION

When ssh-keygen is executed via the command line, this parameter can be specified with '-a'.

```yaml
- openssh_keypair:
    path: /tmp/id_ssh_ed25519
    type: ed25519
    kdf_rounds: 100
```
