### ISSUE TITLE
ignore_unreachable needs better docs and cross references

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#66038]
##### SUMMARY
https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html needs to mention or at least link to a page about ignore_unreachable

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below
devel
```

**Comment by jctanner** [comment]
Example threads where ignore_unreachable documentation could help:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/kaBgYCZnYZ0/ZABz7-0qAwAJ

**Comment by bmillemathias** [comment]
Hi @jctanner 

reading the thread linked, looking in the code -- I've only find mention of `ignore_unreachable` in 
```
lib/ansible/playbook/base.py:    _ignore_unreachable = FieldAttribute(isa='bool')
lib/ansible/plugins/strategy/__init__.py:                ignore_unreachable = original_task.ignore_unreachable
lib/ansible/plugins/strategy/__init__.py:                if not ignore_unreachable:
```
did not really helped me to get the ins and the outs of `ignore_unreachable`.
I eventually created a test playbook with one unreachable node
```
- hosts: servers
  tasks:
    - name: Test the servers are actually down
      ping:
      ignore_unreachable: true

    - name: Test the servers are actually down
      ping:

    - name: Test the servers are actually down
      ping:
```
I saw the nodes unreachable during the task `ping` are showing up in the variable `result` and the nodes is kept in the list of nodes for the next task (2nd ping) and fails again, and this time is not kept and so it is not used for the 3rd ping.
`ignore_unreachable` can also be set at play level, so it'll apply to all tasks of the play.

I can't find of any short and meaningful example where it could be useful.
Thanks for confirming info and if you have hints for a good example
