### ISSUE TITLE
aws_s3 is not idempotent

### ISSUE THREAD

**Issue by asarubbo** [ansible/ansible#66034]
##### SUMMARY

The module aws_s3 looks to not be idempotent

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

aws_s3
##### ANSIBLE VERSION

```paste below
ansible 2.9.2.post0
  config file = /home/ago/.ansible.cfg
  configured module search path = ['/home/ago/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.6/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.6/ansible
  python version = 3.6.9 (default, Oct  9 2019, 20:42:16) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/ago/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ago/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=5m -o PreferredAuthentications=publickey
DEFAULT_FORKS(/home/ago/.ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/ago/.ansible.cfg) = ['/home/ago/git/ansible/common/hosts']
DEFAULT_REMOTE_USER(/home/ago/.ansible.cfg) = root
HOST_KEY_CHECKING(/home/ago/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/ago/.ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT

Gentoo x86_64

##### STEPS TO REPRODUCE

```yaml
    - name: Download something
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        s3_url: "{{ s3_url }}"
        bucket: "{{ mybucket }}"
        object: "/myfile.myext"
        dest: "/root/myfile.myext"
        overwrite: different
        mode: get
```

##### EXPECTED RESULTS

The task should not result as changed

##### ACTUAL RESULTS

The tasks results as "changed" and the object is downloaded on each playbook run
