### ISSUE TITLE
Error when disabling Windows schedule tasks in subfolders

### ISSUE THREAD

**Issue by robertoalves10** [ansible/ansible#66056]
##### SUMMARY
Error when disabling already existent Windows schedule tasks in subfolders

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_scheduled_task

##### ANSIBLE VERSION
2.8.6

##### CONFIGURATION
default ansible.cfg

##### OS / ENVIRONMENT
Windows 2016

##### STEPS TO REPRODUCE
Trying in using various combinations with/without quotes:
```
  - name: Disable schedule task \Microsoft\Windows\Customer Experience Improvement Program\Consolidator
    win_scheduled_task:
      name: \Microsoft\Windows\Customer Experience Improvement Program\Consolidator
      enabled: no

  - name: Disable schedule task \Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask
    win_scheduled_task:
      name: '\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask'
      enabled: no

  - name: Disable schedule task \Microsoft\Windows\Customer Experience Improvement Program\UsbCeip
    win_scheduled_task:
      name: '"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip"'
      enabled: no

  - name: Disable schedule task \Microsoft\Windows\Speech\SpeechModelDownloadTask
    win_scheduled_task:
      name: "\\Microsoft\\Windows\\Speech\\SpeechModelDownloadTask"
      enabled: no

  - name: Disable schedule task \Microsoft\XblGameSave\XblGameSaveTask
    win_scheduled_task:
      name: Microsoft\XblGameSave\XblGameSaveTask
      enabled: no
```

##### EXPECTED RESULTS
Disable the target (and already existent) Windows services

##### ACTUAL RESULTS
```
TASK [disable_microsoft_windows_scheduled_tasks : Disable schedule task \Microsoft\Windows\Customer Experience Improvement Program\Consolidator] ************
task path: /devops/ansible/ansible_roles/disable_microsoft_windows_scheduled_tasks/tasks/main.yml:14
Using module file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible/modules/windows/win_scheduled_task.ps1
Pipelining is enabled.
<192.168.100.103> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 192.168.100.103
EXEC (via pipeline wrapper)
fatal: [192.168.100.103]: FAILED! => {
    "changed": false,
    "msg": "cannot create a task with no actions, set at least one action with a path to an executable"
}
...ignoring

TASK [disable_microsoft_windows_scheduled_tasks : Disable schedule task \Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask] **********
task path: /devops/ansible/ansible_roles/disable_microsoft_windows_scheduled_tasks/tasks/main.yml:19
Using module file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible/modules/windows/win_scheduled_task.ps1
Pipelining is enabled.
<192.168.100.103> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 192.168.100.103
EXEC (via pipeline wrapper)
fatal: [192.168.100.103]: FAILED! => {
    "changed": false,
    "msg": "cannot create a task with no actions, set at least one action with a path to an executable"
}
...ignoring

TASK [disable_microsoft_windows_scheduled_tasks : Disable schedule task \Microsoft\Windows\Customer Experience Improvement Program\UsbCeip] *****************
task path: /devops/ansible/ansible_roles/disable_microsoft_windows_scheduled_tasks/tasks/main.yml:24
Using module file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible/modules/windows/win_scheduled_task.ps1
Pipelining is enabled.
<192.168.100.103> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 192.168.100.103
EXEC (via pipeline wrapper)
fatal: [192.168.100.103]: FAILED! => {
    "changed": false,
    "msg": "cannot create a task with no actions, set at least one action with a path to an executable"
}
...ignoring

TASK [disable_microsoft_windows_scheduled_tasks : Disable schedule task \Microsoft\Windows\Speech\SpeechModelDownloadTask] **********************************
task path: /devops/ansible/ansible_roles/disable_microsoft_windows_scheduled_tasks/tasks/main.yml:29
Using module file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible/modules/windows/win_scheduled_task.ps1
Pipelining is enabled.
<192.168.100.103> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 192.168.100.103
EXEC (via pipeline wrapper)
fatal: [192.168.100.103]: FAILED! => {
    "changed": false,
    "msg": "cannot create a task with no actions, set at least one action with a path to an executable"
}
...ignoring

TASK [disable_microsoft_windows_scheduled_tasks : Disable schedule task \Microsoft\XblGameSave\XblGameSaveTask] *********************************************
task path: /devops/ansible/ansible_roles/disable_microsoft_windows_scheduled_tasks/tasks/main.yml:34
Using module file /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible/modules/windows/win_scheduled_task.ps1
Pipelining is enabled.
<192.168.100.103> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO 192.168.100.103
EXEC (via pipeline wrapper)
fatal: [192.168.100.103]: FAILED! => {
    "changed": false,
    "msg": "cannot create a task with no actions, set at least one action with a path to an executable"
}
...ignoring
```
