### ISSUE TITLE
[cloud][amazon] CloudFront's cache_behaviors validation fails when purge_cache_behaviors is set

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#66083]
##### SUMMARY
Creating a cloudfront_distribution resource fails when setting `purge_cache_behaviors: True`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cloudfront_distribution.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<snip>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.0 (default, Oct 23 2019, 18:51:26) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Arch Linux

##### STEPS TO REPRODUCE

```yaml
- cloudfront_distribution:
    state: present
    default_origin_domain_name: example.com
    caller_reference: "test"
    comment: "test"
    http_version: 'http2'
    origins:
      - id: public-front-end
        domain_name: "example.com"
        origin_path: /asdf
        custom_origin_config:
          origin_protocol_policy: https-only
          https_port: 443
          origin_ssl_protocols:
            items:
              - TLSv1.2
        default_cache_behavior:
      allowed_methods:
        cached_methods:
          - HEAD
          - GET
          - OPTIONS
        items:
          - HEAD
          - DELETE
          - POST
          - GET
          - OPTIONS
          - PUT
          - PATCH
      compress: false
      forwarded_values:
        cookies:
          forward: all
        headers:
          - Accept
          - Accept-Charset
          - Accept-Datetime
          - Accept-Language
          - Authorization
          - Host  # Imperative to keep for SNI/HTTPS verification
          - User-Agent
          - Referer
          - X-FORWARDED-FOR
          - X-ORIGINAL-REQUEST
        query_string: false
      smooth_streaming: false
      target_origin_id: public-front-end
      viewer_protocol_policy: redirect-to-https
    cache_behaviors:
      - path_pattern: 'response-codes/*'
        target_origin_id: public-front-end
        compress: false
        default_ttl: 1
        max_ttl: 1
        min_ttl: 1
        allowed_methods:
          items:
            - GET
            - HEAD
          cached_methods:
            - GET
            - HEAD
        forwarded_values:
          query_string: false
        viewer_protocol_policy: redirect-to-https
        smooth_streaming: false
        field_level_encryption_id: ''
    ipv6_enabled: true
    price_class: PriceClass_All
    purge_aliases: true
    purge_cache_behaviors: true
    purge_origins: true
    purge_tags: true
    tags:
      Name: example distribution
      Project: example project
      Priority: '1'
```

Commenting out the `purge_cache_behaviors` line yields the correct verbose output and creates the resource:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_cloudfront_distribution_payload_7kbb8ab2/ansible_cloudfront_distribution_payload.zip/ansible/modules/cloud/amazon/cloudfront_distribution.py", line 1473, in validate_cache_behaviors
TypeError: 'NoneType' object is not iterable

fatal: [localhost]: FAILED! => {
    "boto3_version": "1.10.39",
    "botocore_version": "1.13.39",
    "changed": false,
    "invocation": {
        "module_args": {
            "alias": null,
            "aliases": [],
            "aws_access_key": null,
            "aws_secret_key": null,
            "cache_behaviors": null,
            "caller_reference": "test",
            "comment": "test",
            "custom_error_responses": null,
            "debug_botocore_endpoint_logs": false,
            "default_cache_behavior": null,
            "default_origin_domain_name": "example.com",
            "default_origin_path": null,
            "default_root_object": null,
            "distribution_id": null,
            "e_tag": null,
            "ec2_url": null,
            "enabled": null,
            "http_version": "http2",
            "ipv6_enabled": true,
            "logging": null,
            "origins": [
                {
                    "custom_headers": {
                        "quantity": 0
                    },
                    "custom_origin_config": {
                        "h_t_t_p_port": 80,
                        "h_t_t_p_s_port": 443,
                        "origin_keepalive_timeout": 5,
                        "origin_protocol_policy": "https-only",
                        "origin_read_timeout": 30,
                        "origin_ssl_protocols": {
                            "items": [
                                "TLSv1.2"
                            ],
                            "quantity": 1
                        }
                    },
                    "domain_name": "example.com",
                    "id": "public-front-end",
                    "origin_path": "/asdf"
                }
            ],
            "price_class": "PriceClass_All",
            "profile": null,
            "purge_aliases": true,
            "purge_cache_behaviors": true,
            "purge_custom_error_responses": false,
            "purge_origins": false,
            "purge_tags": false,
            "region": null,
            "restrictions": null,
            "security_token": null,
            "state": "present",
            "tags": {
                "Name": "example distribution",
                "Priority": "1",
                "Project": "example project"
            },
            "validate_certs": true,
            "viewer_certificate": null,
            "wait": false,
            "wait_timeout": 1800,
            "web_acl_id": null
        }
    }
}

MSG:

Error validating distribution cache behaviors: 'NoneType' object is not iterable

```

##### EXPECTED RESULTS

cache_behaviors is honored and non-explicit arguments are removed.

##### ACTUAL RESULTS

Distribution cache validation fails with a cryptic `'NoneType' object is not iterable`

```paste below
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.10.39",
    "botocore_version": "1.13.39",
[...]
            "cache_behaviors": null,
[...]
MSG:

Error validating distribution cache behaviors: 'NoneType' object is not iterable
```
