### ISSUE TITLE
Add ability to set and remove static routes in multiple distros of linux.

### ISSUE THREAD

**Issue by queglay** [ansible/ansible#66106]
##### SUMMARY
It would be helpful to be able to set and remove static routes in multiple distros of linux.
If we are using something like open vpn in a VM (I'm using it in a vagrant ubuntu 16 vm), then the only way to add and remove routes is with the commands like the one below.  This is problematic as we usually have to delete routes before adding them if there is some change or we might get conflicts / errors.
```
    - name: Remove route if it exists and re apply it later
      shell: |
        ip route del {{ item.subnet }}
      with_items:
        - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
        - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
        - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
      when: envtier == 'dev'
      ignore_errors: true
      become: yes
      tags:
        - add-routes

    - name: configure routes to opposite dev/prod environment so that nodes in both envs can access licence server
      shell: |
        ip route add {{ item.subnet }} via {{ item.next_hop }} dev {{ gatewaynic }}
      with_items:
        - { subnet: "{{ private_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
        - { subnet: "{{ public_subnet1_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
        - { subnet: "{{ vpn_cidr_prod }}", next_hop: "{{ openfirehawkserver_prod }}" }
      when: envtier == 'dev'
      become: yes
      tags:
        - add-routes
```

##### ISSUE TYPE
- can't set static routes in an idempotent approach.  only shell command's available.

##### COMPONENT NAME

ansible version 2.9.2

##### ADDITIONAL INFORMATION
https://serverfault.com/questions/742019/add-static-route-with-ansible
