### ISSUE TITLE
VMware: Required to deploy multiple VM's using template in ansible

### ISSUE THREAD

**Issue by vgprash24** [ansible/ansible#66103]
##### SUMMARY
I am trying to develop the code for creating multiple VM's using template in Ansible, please help me to get the right code for it 

##### ISSUE TYPE
- need to know how to create a code for deploying multiple vm's using template in ansible

##### COMPONENT NAME
I have got an example to create one vm using template in ansible, but my need to is to create multiple VM's could anyone help me with the code

My referred example is below

```yaml
name: Create a VM from a template
hosts: localhost
connection: local
gather_facts: no
tasks:
  name: Clone the template
  vmware_guest:
    hostname: 192.0.2.44
    username: administrator@vsphere.local
    password: vmware
    validate_certs: False
    name: testvm_2
    template: template_el7
    datacenter: DC1
    folder: /DC1/vm
    state: poweredon
    wait_for_ip_address: yes
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/galaxy/data/apb/tasks/main.yml.j2`](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/tasks/main.yml.j2)
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)
* [`lib/ansible/modules/files/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/template.py)
* [`lib/ansible/modules/system/gather_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/gather_facts.py)
* [`lib/ansible/modules/system/hostname.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/hostname.py)
* [`lib/ansible/plugins/connection/local.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/local.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@vgprash24: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @alikins @goneri @lparkes @nerzhul @pdellaert @pgbidkar @saito-hideki @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@vgprash24, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/galaxy/data/apb/tasks/main.yml.j2`](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/tasks/main.yml.j2)
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)
* [`lib/ansible/modules/files/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/template.py)
* [`lib/ansible/modules/system/gather_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/gather_facts.py)
* [`lib/ansible/modules/system/hostname.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/hostname.py)
* [`lib/ansible/parsing/utils/yaml.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)
* [`lib/ansible/plugins/connection/local.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/local.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
Hi @vgprash24 !

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

You can use `loop` or `with_items` to achieve this functionality - 

```
- name: Clone the template
  vmware_guest:
    hostname: 192.0.2.44
    username: administrator@vsphere.local
    password: vmware
    validate_certs: False
    name: testvm_"{{ item }}"
    template: template_el7
    datacenter: DC1
    folder: /DC1/vm
    state: poweredon
    wait_for_ip_address: yes
  delegate_to: localhost
  with_items:
    - 1
    - 2
    - 3
```

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by vgprash24** [comment]
Can i mention more than 500 + VM's also in this ?

**Comment by Akasurde** [comment]
Yes, you can use -

```
- name: Create 500+ vms
  vmware_guest:
    ...
    name: "{{ 'test_vm%03d' | format(item) }}"
    ...
    wait_for_ip_address: yes
  delegate_to: localhost
  loop: "{{ range(0, 501, 1) | list }}"
```

Please check [playbook loop's](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html) documentation for more information.
