### ISSUE TITLE
archive module returns OK if an archive already exists, but the archive's md5sum is different

### ISSUE THREAD

**Issue by itcultus** [ansible/ansible#66111]
##### SUMMARY
The archive module returns `OK` if an archive already exists, but the archive itseld is *different*. I have the feeling that the file specified in the `dest` is recreated or something is *touched* on the file itself and the md5sum of the file is modified. 
This behavior affects other modules (like for example fetch). 

Related bug report: #48780

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
archive module

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Oct 29 2019, 10:39:36) [GCC]
```
##### OS / ENVIRONMENT

openSUSE Leap 15.1

##### STEPS TO REPRODUCE

```yaml
- name: Backup Apache certificates
  archive: 
    path: "/etc/apache2/vhosts/"
    dest: "/tmp/apache_vhosts.tar.gz"
    mode: 0640
```

##### EXPECTED RESULTS

I would expect `CHANGED` everytime I run the archive to be honest if the archive **is** changed

##### ACTUAL RESULTS

```
<server.home> (0, b'/home/username\n', b'')
<server.home> ESTABLISH SSH CONNECTION FOR USER: username
<server.home> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="username"' -o ConnectTimeout=10 -o ControlPath=/home/username/.ansible/cp/f37f8c76ce server.home '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867 `" && echo ansible-tmp-1577643420.1231942-2340849213867="` echo /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867 `" ) && sleep 0'"'"''                                                                              
<server.home> (0, b'ansible-tmp-1577643420.1231942-2340849213867=/home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867\n', b'')
Using module file /usr/lib/python3.6/site-packages/ansible/modules/files/archive.py
<server.home> PUT /home/username/.ansible/tmp/ansible-local-15705abxtwq4c/tmp5j1c2_m1 TO /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867/AnsiballZ_archive.py                                                                                                                                                              
<server.home> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="username"' -o ConnectTimeout=10 -o ControlPath=/home/username/.ansible/cp/f37f8c76ce '[server.home]'        
<server.home> (0, b'sftp> put /home/username/.ansible/tmp/ansible-local-15705abxtwq4c/tmp5j1c2_m1 /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867/AnsiballZ_archive.py\n', b'')                                                                                                                                            
<server.home> ESTABLISH SSH CONNECTION FOR USER: username
<server.home> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="username"' -o ConnectTimeout=10 -o ControlPath=/home/username/.ansible/cp/f37f8c76ce server.home '/bin/sh -c '"'"'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867/ /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867/AnsiballZ_archive.py && sleep 0'"'"''                                                                                                                                                  
<server.home> (0, b'', b'')
<server.home> ESTABLISH SSH CONNECTION FOR USER: username
<server.home> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="username"' -o ConnectTimeout=10 -o ControlPath=/home/username/.ansible/cp/f37f8c76ce -tt server.home '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=pjpqcvtzgkrgxfllntwutkmartxogcut] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-pjpqcvtzgkrgxfllntwutkmartxogcut ; /usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867/AnsiballZ_archive.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''             
Escalation succeeded
<server.home> (0, b'\r\n\r\n{"archived": [<hidden>], "changed": false, "group": "root", "uid": 0, "expanded_exclude_paths": [], "dest": "/tmp/apache_vhosts.tar.gz", "missing": [], "expanded_paths": ["/etc/apache2/vhosts/"], "arcroot": "/etc/apache2/vhosts/", "owner": "root", "state": "file", "gid": 0, "mode": "0640", "invocation": {"module_args": {"directory_mode": null, "force": null, "remote_src": null, "path": "/tmp/apache_vhosts.tar.gz", "owner": null, "follow": false, "exclude_path": null, "group": null, "unsafe_writes": null, "setype": null, "content": null, "serole": null, "format": "gz", "dest": "/tmp/apache_vhosts.tar.gz", "selevel": null, "regexp": null, "src": null, "force_archive": false, "seuser": null, "remove": false, "delimiter": null, "mode": 416, "attributes": null, "backup": null}}, "size": 8400}\r\n', b'Shared connection to server.home closed.\r\n')                
<server.home> ESTABLISH SSH CONNECTION FOR USER: username
<server.home> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="username"' -o ConnectTimeout=10 -o ControlPath=/home/username/.ansible/cp/f37f8c76ce server.home '/bin/sh -c '"'"'rm -f -r /home/username/.ansible/tmp/ansible-tmp-1577643420.1231942-2340849213867/ > /dev/null 2>&1 && sleep 0'"'"''                                                      
<server.home> (0, b'', b'')
ok: [server.home] => (item=/etc/apache2/vhosts/) => changed=false 
  ansible_loop_var: item
  archived:
  - <hidden list>
  arcroot: /etc/apache2/vhosts/
  dest: /tmp/apache_vhosts.tar.gz
  expanded_exclude_paths: []
  expanded_paths:
  - /etc/apache2/vhosts/
  gid: 0
  group: root
  invocation:
    module_args:
      attributes: null
      backup: null
      content: null
      delimiter: null
      dest: /tmp/apache_vhosts.tar.gz
      directory_mode: null
      exclude_path: null
      follow: false
      force: null
      force_archive: false
      format: gz
      group: null
      mode: 416
      owner: null
      path: /tmp/apache_vhosts.tar.gz
      regexp: null
      remote_src: null
      remove: false
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      unsafe_writes: null
  item:
    src_dir: /etc/apache2/vhosts/
    tar_file: /tmp/apache_vhosts.tar.gz
  missing: []
  mode: '0640'
  owner: root
  size: 8400
  state: file
  uid: 0
```

However, the *md5sum* of the archive between runs is different: 

```
webserver:/etc/apache2 # md5sum /tmp/apache_vhosts.tar.gz 
c976f4751f011a7a9f145252204c8de2  /tmp/apache_vhosts.tar.gz
weserver:/etc/apache2 # md5sum /tmp/apache_vhosts.tar.gz 
43b5ac35468f8f60a62f33e7024d4bb7  /tmp/apache_vhosts.tar.gz
weserver:/etc/apache2 # md5sum /tmp/apache_vhosts.tar.gz 
951a585b8c14237cc43f656e9ec29080  /tmp/apache_vhosts.tar.gz
```
