### ISSUE TITLE
Can't get inventory_hostname

### ISSUE THREAD

**Issue by kiddingl** [ansible/ansible#66125]
##### SUMMARY

I want to deploy different apps according to different hosts
##### ISSUE TYPE
- Bug Report
The “when” can‘t use inventory_hostname
##### COMPONENT NAME

the task:
```
name: create directory
  file:
    path: "{{ app_dir }}/{{ app_name }}"
    state: directory
  when: inventory_hostname.split('_')[1] == "externel"
```
##### ANSIBLE VERSION

```paste below
ansible 2.6.5
  config file = /home/lifei/ansible2-tmp/ansible2/ansible.cfg
  configured module search path = [u'/home/lifei/ansible2-tmp/ansible2/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
my secret
```

##### OS / ENVIRONMENT

centos7

##### STEPS TO REPRODUCE

my ansible hosts:
```
externel_vm11 ansible_host=192.168.6.11
```

```yaml
name: create directory
  file:
    path: "{{ app_dir }}/{{ app_name }}"
    state: directory
  when: inventory_hostname.split('_')[1] == "externel"
```

##### ACTUAL RESULTS

fatal: [vm11]: FAILED! => {"msg": "The conditional check 'inventory_hostname.split('_')[1] == \"externel_vm11\"' failed. The error was: error while evaluating conditional (inventory_hostname.split('_')[1] == \"externel_vm11\"): list object has no element 1\n\nThe error appears to have been in '/home/lifei/ansible2-tmp/ansible2/ansible/roles/prometheus/tasks/node_exporter_docker.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: create directory\n  ^ here\n"}

```paste below

```
