### ISSUE TITLE
dnf module reports results inconsistently

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#66132]
##### SUMMARY

Installations are always reported regardless of whether anything was actually installed.
Installed packages reported with versions in actual install and without versions in dry run.
Removed packages are not reported in check mode.
Some consistency would be preferable: show or not show versions, do not list already installed packages with newly installed, show supposed actions in check mode.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnf
##### ANSIBLE VERSION

```paste below
ansible 2.8.6
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

CentOS 7 on target machine

##### STEPS TO REPRODUCE

`package0` and `package3` are installed, `package1`, `package2` are not installed, require dependencies
```yaml
---
- hosts: host1
  tasks:
    - dnf:
      name:
        - package0
        - package1
        - package2
      state: present
    - dnf:
      name:
        - package3
      state: absent
      register: package_remove
    - debug
        var: package_install
    - debug
        var: package_remove

```

##### EXPECTED RESULTS

On check mode run:
```
package_install.results:
- 'Installed: package1'
- 'Installed: package2'
- 'Installed: some-dependency1'
- 'Installed: some-dependency2'
package_remove.results:
- 'Removed: package3'
```

On first live run `package_install.results` contains:
```
package_install.results:
- 'Installed: package1'
- 'Installed: package2'
- 'Installed: some-dependency1'
- 'Installed: some-dependency2'
package_remove.results:
- 'Removed: package3'
```
On second run or second check mode run  `package_install.results`,  `package_remove.results` are empty

##### ACTUAL RESULTS

On check mode run:
```paste below
package_install.results:
- 'Installed: package0'
- 'Installed: package1'
- 'Installed: package2'
package_remove.results: []
```
On first live run `package_install.results` contains:
```
package_install.results:
- 'Installed: package0'
- 'Installed: package1-1:2.3-1.arch'
- 'Installed: package2-4:5.6-1.arch'
package_remove.results:
- 'Removed: package3-7:8.9-1.arch'
```
On second run:
```
package_install.results:
- 'Installed: package0'
- 'Installed: package1'
- 'Installed: package2'
package_remove.results: []
```
On check run:
```
package_install.results:
- 'Installed: package0'
- 'Installed: package1'
- 'Installed: package2'
package_remove.results: []
```
