### ISSUE TITLE
When using YAML anchors, Ansible shows the duplicate dict key warning

### ISSUE THREAD

**Issue by in-in** [ansible/ansible#66137]
##### SUMMARY

When using YAML anchors, Ansible shows the duplicate dict key warning

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

YAML parser

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /home/mint/Desktop/ansible_yaml_anchors/ansible.cfg
  configured module search path = ['/home/mint/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/mint/Desktop/ansible_yaml_anchors/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/mint/Desktop/ansible_yaml_anchors/ansible.cfg) = ['/home/mint/Desktop/ansible_ya$
```

##### OS / ENVIRONMENT

Linux Mint 19.3 Tricia x86_64

##### STEPS TO REPRODUCE

minimal test-case
https://github.com/in-in/ansible_yaml_anchors

##### EXPECTED RESULTS

Run playbook without any warnings.

##### ACTUAL RESULTS

```paste below
[WARNING]: While constructing a mapping from /home/mint/Desktop/ansible_yaml_anchors/helpers/copy.yml,
line 24, column 3, found a duplicate dict key (when). Using last defined value only.

[WARNING]: While constructing a mapping from /home/mint/Desktop/ansible_yaml_anchors/helpers/copy.yml,
line 27, column 3, found a duplicate dict key (when). Using last defined value only.

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
That warning seems accurate to me. Isn't this https://github.com/in-in/ansible_yaml_anchors/blob/master/helpers/copy.yml#L24-L25 the equivalent of:

```
- name: helper | copy | create directory
  become: "{{ item.privilege | default(false) }}"
  file:
    path: "{{ item.dest }}"
    state: directory
  when:
    - '"privilege" in item'
    - item.dest is not directory
  loop: "{{ copy_facts }}"
  when: '"privilege" not in item'
```
The `when:` key is provided twice, so only the last one is used.

**Comment by in-in** [comment]
YAML anchors are completely valid syntax. So why show a warning for correct syntax?

On the other hand, in this fragment of code I expect to see the warning:
```yaml
- name: test3
  copy:
    src: "test.txt"
    src: "test3.txt"
    dest: "~/dest"
```

I do not consider YAML anchors(and aliases) as adding another key, but as overwriting an existing one.
