### ISSUE TITLE
gitlab_project_variable: support hidden/protected variables

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible#66135]
##### SUMMARY
gitlab_project_variable: support hidden/protected variables

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gitlab_project_variable

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/source_control/gitlab/gitlab_project_variable.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab/gitlab_project_variable.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Lunik @Shaps @dj-wasabi @jlozadad @markuman @marwatk @waheedi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by markuman** [comment]
Ok, create a project variable with `masked`  or `protected`  value is easy.  
But I've got not idea how to update an existing variable with its `masked` or `protected` value.

https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html#id6

```
>>> pl[5].variables.create({"key": "m", "value": "test", "protected": True})
>>> pv = pl[5].variables.list()
>>> pv[1]
<ProjectVariable key:m>
>>> pv[1].attributes
{'variable_type': 'env_var', 'key': 'm', 'value': 'test', 'protected': True, 'masked': False, 'environment_scope': '*', 'project_id': 188}
>>> pv[1].attributes.update({'masked': True})
###
### everything has no affect
>>> pv[1].attributes.update()
>>> pv[1].save()
>>> pv[1].attributes['masked'] = True
>>> pv[1].attributes['masked']
False
```

any ideas?

**Comment by markuman** [comment]
https://github.com/python-gitlab/python-gitlab/issues/992

**Comment by markuman** [comment]
I'm working on it.  
We need a compliance to not break backwards compatibility...  
When the value is a string, `masked` and `protected`  will be defaults set to `false`. Otherwise, the value must be a dict, where addition values for a variable will be given.

```yml
- name: Set or update some CI/CD variables
  gitlab_project_variable:
    api_url: https://gitlab.com
    api_token: secret_access_token
    project: markuman/dotfiles
    purge: false
    vars:
      ACCESS_KEY_ID: abc123
      SECRET_ACCESS_KEY:
        value: 321cba
        masked: true
        protected: false
```
