### ISSUE TITLE
redfish_info / redfish_config - Manager - GetSerialInterfaces / SetSerialInterface

### ISSUE THREAD

**Issue by renxulei** [ansible/ansible#66142]
##### SUMMARY

This feature would implement a GetSerialInterfaces command for the Manager category of redfish_info, to retrieve all serial interfaces and their properties, like BitRate. And also implement a SetSerialInterface command for the Manager category of redfish_config, to set SerialInterface's properties, like enable/disable the interface, change BitRate.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

redfish_info.py
redfish_config.py
redfish_utils.py

##### ADDITIONAL INFORMATION

These 2 commands would help user to get serial interfaces' info or change serial interface.

```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    baseuri: 10.245.39.251
    username: USERID
    password: PASSW0RD
  tasks:
    - name: Get Serial Interfaces information
      redfish_info:
        category: Manager
        command: GetSerialInterfaces
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
    - name: Set Serial Interface
      redfish_config:
        category: Manager
        command: SetSerialInterface
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        serial_interface_id: "1"
        serial_interface_config:
          InterfaceEnabled: True
          BitRate: 115200
```
