### ISSUE TITLE
iam_role_info: format update

### ISSUE THREAD

**Issue by mmasko** [ansible/ansible#66148]
I could not find this feature request in general GitHub discussions.

Ansible version: 2.9.1

##### SUMMARY
Requesting that iam_role_info return the assume_role_policy_document return value formatted in such a way that AWS expects when using assume_role_policy_document in the iam_role module. 

The problem is the return value for assume_role_policy_document returns all field values as lower case. To be able to use the return value, the fields must be capitalized. Specifically, these fields:
        - Version
        - Statement
        - Action
        - Effect
        - Principal
        - AWS

I get around the issue for now by replacing the lowercase fields with uppercase. 

For reference, this is the task used to fix the lowercase issue:
```yaml
    - name: Get role information
      iam_role_info:
        name: somerole
      register: role_info

    - name: Isolate statement
      set_fact:
        role_info_updated: "{{ role_info.iam_roles[0].assume_role_policy_document }}"

    - name: Uppercase keys
      set_fact: 
        role_info_updated: "{{ role_info_updated | regex_replace(lowercase , item) }}"  
      vars:
        lowercase: "(?<!:)({{ item | lower }})(?!:)"
      loop:
        - Version
        - Statement
        - Action
        - Effect
        - Principal
        - AWS
```

##### ISSUE TYPE
Have the iam_role_info return the assume_role_policy_document in the format that AWS expects so it can be readily used by other Ansible AWS modules that require it. 

##### COMPONENT NAME
iam_role_info
specifically, the assume_role_policy_document of the iam_role_info return value

##### ADDITIONAL INFORMATION
If the iam_roles[0].assume_role_policy_document the return value of the iam_role_info module was returned formatted in such a way that AWS can readily use, it would allow users to query existing policy documents rather than them having to feed a JSON file, or post-processing formatting before utilizing the iam_role module for actions that require the assume_role_policy_document.

An example is below on how this feature request would simplify the use of the iam_role module. Notice that in the second task, Do some aim role action, the attribute assume_role_policy_document is defined from the return value of assume_role_policy_document from the iam_role_info module query.

```yaml
    - name: Get role information
      iam_role_info:
        name: somerole
      register: role_info

    - name: Do some iam role action
      iam_role:
        name: mynewrole
        assume_role_policy_document:  "{{ role_info.iam_roles[0].assume_role_policy_document }}"
        managed_policy: somepolicy
```
Below is how this feature request is requesting the value of the assume_role_policy_document return value would look. Currently the module returns the lines in lowercase, and as mentioned, AWS requires uppercase.

```json
    "role_info_updated": {
        "Statement": [
            {
                "Action": "sts:AssumeRole",
                "Effect": "Allow",
                "Principal": {
                    "AWS": [
                        "arn:aws:iam:::",
                        "arn:aws:iam:::"
                    ]
                }
            }
        ],
        "Version": "2012-10-17"
    }
}
```
