### ISSUE TITLE
docker_swarm_service healthcheck always changed

### ISSUE THREAD

**Issue by bozho** [ansible/ansible#66146]
##### SUMMARY
When using `healthcheck` in `docker_swarm_service`, it is always reported as having changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_swarm_service

##### ANSIBLE VERSION

```paste below
ansible 2.8.6
  config file = /mnt/f/Users/bozho/.ansible.cfg
  configured module search path = ['/mnt/f/Users/bozho/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20191022]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_CONTROL_PATH_DIR(/mnt/f/Users/bozho/.ansible.cfg) = /tmp/ansible/cp
```

##### OS / ENVIRONMENT

Debian Bullseye on WSL:
```
Linux bozho-host 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

I've added `healthcheck` option to an existing `docker_swarm_service` entry that was behaving as expected starting a service from a custom nginx image in global mode

```yaml
  docker_swarm_service:
    name: "custom-nginx"
    image: "{{ nginx_image_name }}"
    labels:
      tag: "my-tag"
    configs:
      - config_id: "{{ nginx_conf_config.config_id }}"
        config_name: "{{ docker_nginx_conf_config_name }}"
        filename: "/etc/nginx/nginx.conf"
        mode: 0644
      - config_id: "{{ default_conf_config.config_id }}"
        config_name: "{{ docker_default_conf_config_name }}"
        filename: "/etc/nginx/sites-enabled/default.conf"
        mode: 0644
    secrets: "{{ nginx_secrets_list | default([]) }}"
    mode: global
    update_config:
      delay: 1s
      failure_action: rollback
      order: stop-first
    healthcheck:
      test: [ "CMD", "curl", "--fail", "-k", "https://myhost.example.com" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: local
      options:
        "max-size": 10k
        "max-file": "3"
    publish:
      - published_port: 80
        target_port: 80
        protocol: tcp
        mode: host
      - published_port: 443
        target_port: 443
        protocol: tcp
        mode: host
    networks:
      - my_network
  run_once: true
```

##### EXPECTED RESULTS

Re-running the playbook should have no changes

##### ACTUAL RESULTS

```paste below
{
  "changed": true,
  "changes": [
    "healthcheck"
  ],
  "msg": "Service updated",
  "rebuilt": false,
  "swarm_service": {
    "args": null,
    "command": null,
    "configs": [
    ...
    ],
    ...
}

```
