### ISSUE TITLE
Inconsistent variable expansion when mixing dicts, vault variables and loops

### ISSUE THREAD

**Issue by sw-dbrown** [ansible/ansible#66177]
##### SUMMARY

Consider the following variable (type dict):

```
    mydict1:
      50-{{ mybar }}-dhcp:
        - Foo:
            - Bar: "{{ mybar }}"
    mydict2:
      50-{{ myfoo }}-dhcp:
        - Foo:
            - Bar: "{{ test }}"
```

where the variables `mybar` and `myfoo` are regular string variables and `test` is a string variable from an inline vault. When looping over these dicts with `loop` and `dict2items`, only the key of `mydict1` is expanded correctly, while the key in `mydict2` remains `50-{{ myfoo }}-dhcp`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core, vault

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dbrown/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 09:25:23) [GCC 9.2.1 20191130]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed | cat
<empty>
```

##### OS / ENVIRONMENT

Debian GNU/Linux bullseye/sid (unstable), ansible running against localhost 

##### STEPS TO REPRODUCE

```yaml
---
# Instructions to reproduce:
# ansible-playbook poc.yml --ask-vault-pass
# Vault password is 1234
- hosts: localhost
  become: false
  gather_facts: false
  vars:
    test: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34343061643639393135333139616565643363326335303437663139306464633961353362636239
      3631306163646431666563396265333765386461306562370a646337323865313161373635663830
      39363330646535646532383338306335313862386539653265343734636438303763363730353964
      3233303637383666640a653638353836326566356534343838616630323132643664306332663832
      6134
    myfoo: foo
    mybar: bar
    mydict1:
      50-{{ mybar }}-dhcp:
        - Foo:
            - Bar: "{{ mybar }}"
    mydict2:
      50-{{ myfoo }}-dhcp:
        - Foo:
            - Bar: "{{ test }}"
  tasks:
    - debug:
        msg: "This key is templated: {{ item.key }}"
      loop: "{{ mydict1 | dict2items }}"

    - debug:
        msg: "This key is not templated: {{ item.key }}"
      loop: "{{ mydict2 | dict2items }}"
```

##### EXPECTED RESULTS

I recently changed the tasks to use `loop` function as stated in the [porting guide for Ansible 2.9](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html#loops).

I was using `with_dict: "{{ mydict2 }}"` prior to the change. The keys in `mydict2` were correctly expanded when looping.

The expected results would therefore be:

```
50-bar-dhcp
50-foo-dhcp
```

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -vvv poc.yml --ask-vault-pass
ansible-playbook 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dbrown/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.7.6 (default, Dec 19 2019, 09:25:23) [GCC 9.2.1 20191130]
Using /etc/ansible/ansible.cfg as config file
Vault password:
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: poc.yml ***************************************************************************************************************************************************
1 plays in poc.yml

PLAY [localhost] ****************************************************************************************************************************************************
META: ran handlers

TASK [debug] ********************************************************************************************************************************************************
task path: /home/dbrown/ansible_dict_mwe/poc.yml:27
ok: [localhost] => (item={'key': '50-bar-dhcp', 'value': [{'Foo': [{'Bar': 'bar'}]}]}) => {
    "msg": "This key is templated: 50-bar-dhcp"
}

TASK [debug] ********************************************************************************************************************************************************
task path: /home/dbrown/ansible_dict_mwe/poc.yml:31
ok: [localhost] => (item={'key': '50-{{ myfoo }}-dhcp', 'value': [{'Foo': [{'Bar': '1234\n'}]}]}) => {
    "msg": "This key is not templated: 50-{{ myfoo }}-dhcp"
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
