### ISSUE TITLE
Servicenow cmdb update via Ansible

### ISSUE THREAD

**Issue by vgprash24** [ansible/ansible#66172]
##### SUMMARY
I need to update service now cmdb via Ansible

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I have this below code, but how to update the servicenow cmdb using ansible

```yaml
  - name: Retrieve fields for a table {{ snow_table }}
    snow_record:
      state: present
      table: "{{ snow_table }}"
      data:
        name: delete_this_record
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
    register: table_output
```
I need to update the CMDB, please suggest me

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/config/data.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/data.py)
* [`lib/ansible/modules/notification/snow_record.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/snow_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @garbled1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/notification/snow_record.py

**Comment by Akasurde** [comment]
@vgprash24 Thanks for reporting this issue. Are you getting an error while updating the record? Have you used `number` parameter which specifies the record number of existing record to update? 

Thanks.

needs_info

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/notification/snow_record.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/snow_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@vgprash24 I am unable to reproduce your issue - 

```
PLAY [localhost] *********************************************************************************************

TASK [Gathering Facts] ***************************************************************************************
ok: [localhost]

TASK [snow_record] *******************************************************************************************
changed: [localhost]

TASK [snow_record_find] **************************************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "Before update "
}

TASK [set_fact] **********************************************************************************************
ok: [localhost]

TASK [snow_record] *******************************************************************************************
changed: [localhost]

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "After update \"My detailed description\""
}

PLAY RECAP ***************************************************************************************************
localhost                  : ok=7    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

And I am using following playbook - 

```yaml
---
- hosts: localhost
  vars:
    username: admin
    password: passdw123
    instance: devinstance
  tasks:
    - snow_record:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: "{{ instance }}"
        data:
            short_description: "Test 1"
            priority: 2
        state: present
      register: ticket_details

    - snow_record_find:
        username: "{{ username }}"
        password: "{{ password }}"
        table: incident
        instance: "{{ instance }}"
        query:
          sys_id: "{{ ticket_details['record']['sys_id'] }}"
      register: record_details

    - debug:
        msg: "Before update {{ record_details['record'][0]['description'] }}"

    - set_fact:
        record_number: "{{ record_details['record'][0]['number'] }}"

    - snow_record:
        username: "{{ username }}"
        password: "{{ password }}"
        instance: "{{ instance }}"
        number: "{{ record_number }}"
        data:
            description: "My detailed description"
            priority: 2
        state: present
      register: update_ticket

    - debug:
        msg: After update "{{ update_ticket['record']['description'] }}"
```

needs_info
