### ISSUE TITLE
cannot remove security_groups from instance using os_server

### ISSUE THREAD

**Issue by netson** [ansible/ansible#66181]
##### SUMMARY

When running os_server in a play and adding security_groups, this works well, However, it does not seem possible to remove any security groups upon an additional playbook run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_server

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /opt/netson-ansible/ansible.cfg
  configured module search path = [u'/opt/netson-ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/opt/netson-ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/opt/netson-ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/opt/netson-ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
COLOR_DIFF_REMOVE(/opt/netson-ansible/ansible.cfg) = bright red
COLOR_ERROR(/opt/netson-ansible/ansible.cfg) = bright red
COLOR_UNREACHABLE(/opt/netson-ansible/ansible.cfg) = bright red
DEFAULT_CALLBACK_WHITELIST(/opt/netson-ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_GATHERING(/opt/netson-ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/opt/netson-ansible/ansible.cfg) = [u'/opt/netson-ansible/inventory']
DEFAULT_LOG_PATH(/opt/netson-ansible/ansible.cfg) = /opt/netson-ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/opt/netson-ansible/ansible.cfg) = [u'/opt/netson-ansible/lookup_plugins']
DEFAULT_MANAGED_STR(/opt/netson-ansible/ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}
host: {host}
DEFAULT_MODULE_PATH(/opt/netson-ansible/ansible.cfg) = [u'/opt/netson-ansible/modules']
DEFAULT_ROLES_PATH(/opt/netson-ansible/ansible.cfg) = [u'/opt/netson-ansible/roles']
DEFAULT_STDOUT_CALLBACK(/opt/netson-ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/opt/netson-ansible/ansible.cfg) = 30
INTERPRETER_PYTHON(/opt/netson-ansible/ansible.cfg) = auto_silent
INVENTORY_ENABLED(/opt/netson-ansible/ansible.cfg) = [u'host_list', u'script', u'yaml', u'ini', u'openstack', u'auto']
RETRY_FILES_ENABLED(/opt/netson-ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/opt/netson-ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

ansible host system:
```
$ lsb_release -a
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
```
target os: not relevant
OpenStack info: not sure, I'm running these scripts on the OpenStack cloud provided by cloudvps.com and can't for the life of me find any version info?

##### STEPS TO REPRODUCE

Running the following 2 tasks will result in your instance having both security groups attached, instead of the expected one:

```yaml
- name: launch a compute instance
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        state: present
        auth:
          auth_url: https://identity.example.com
          username: username
          password: Equality7-2521
          project_name: username-project1
        name: vm1
        region_name: region-b.geo-1
        availability_zone: az2
        image: 9302692b-b787-4b52-a3a6-daebb79cb498
        key_name: test
        timeout: 200
        flavor: 101
        security_groups:
        - default
        - somegroup
        auto_ip: yes

    - name: update security groups
      os_server:
        state: present
        auth:
          auth_url: https://identity.example.com
          username: username
          password: Equality7-2521
          project_name: username-project1
        name: vm1
        region_name: region-b.geo-1
        availability_zone: az2
        image: 9302692b-b787-4b52-a3a6-daebb79cb498
        key_name: test
        timeout: 200
        flavor: 101
        security_groups:
        - default
        # - somegroup - remove this group
        auto_ip: yes
```

##### EXPECTED RESULTS

Expected result was to end up with only a single security group attached to my instance. Use case: by default my Ubuntu images are provisioned with SSHD running on port 22, so I created a security group which allows access to port 22. However, after running all ansible playbooks, the port will have changed to something else to prevent spamming my logs and I need to revoke access to port 22 again, e.g., remove the security group.

##### ACTUAL RESULTS

Both groups are still attached to the instance.
