### ISSUE TITLE
Ability to delete a specific AWS ELB listener rule without purging/effecting entire listener rules section

### ISSUE THREAD

**Issue by techsemicolon** [ansible/ansible#66180]
##### SUMMARY
Ability to delete a specific AWS ELB listener rule without purging/effecting entire listener rules section

##### ISSUE TYPE
Feature Request

##### ADDITIIONAL INFORMATION
- Currently when we want to add a new ELB listener rule, we can do that by adding it in listeners section and making sure that we set `purge_rules : False` Something like this : 

```yaml
- name: Register new sandbox target group into load balancer
    elb_application_lb:
      name: Something
      subnets: ...
      region: ...
      purge_listeners : False
      purge_rules : False
      security_groups:
        - Some_Security_Group
      state: present
      listeners:
        - Protocol: HTTPS
          Port: 443
          DefaultActions:
            - Type: forward
              TargetGroupName: Default_TG_Name
          Certificates:
            - CertificateArn: Some_Certificate_ARN
          SslPolicy: ELBSecurityPolicy-2016-08
          Rules:
            - Conditions:
                - Field: host-header
                  Values:
                    - subdomain.domain.com"
              Priority: 10
              Actions:
                - TargetGroupName: Subdomain_TG_NAME
                  Type: forward
````
However, if now we want to just remove this specific listener rule without affecting any existing rules for this lister, it is a pain to first get all rules using info/facts API for this ELB, remove the rule from the rule list and then add that entire list into Rules section with forcefully purging the listener and rules so that old rules are cleared.

The feature request is adding the state/command key in the Rules section in which we can have `present` or `absent` based no the listener rule action we want to take. If we have that feature, removing a specific rule from listener will be like following : 

```yaml
- name: Register new sandbox target group into load balancer
    elb_application_lb:
      name: Something
      subnets: ...
      region: ...
      purge_listeners : False
      purge_rules : False
      security_groups:
        - Some_Security_Group
      state: present
      listeners:
        - Protocol: HTTPS
          Port: 443
          DefaultActions:
            - Type: forward
              TargetGroupName: Default_TG_Name
          Certificates:
            - CertificateArn: Some_Certificate_ARN
          SslPolicy: ELBSecurityPolicy-2016-08
          Rules:
            - Conditions:
                - Field: host-header
                  Values:
                    - subdomain.domain.com"
              Priority: 10
              Actions:
                - TargetGroupName: Subdomain_TG_NAME
                  Type: forward
              State: absent
```
##### COMPONENT NAME
elb_application_lb
