### ISSUE TITLE
Role + with_items error

### ISSUE THREAD

**Issue by dhorbach** [ansible/ansible#6618]
##### Issue Type:

Bug report
##### Ansible Version:

1.5.3 
##### Environment:

Centos 6.4
##### Summary:

Role + with_items gives error
##### Steps To Reproduce:

```
- hosts: localhost

  roles:
    - role: test
      with_items:
        - one
        - two

```
##### Expected Results:

No error
##### Actual Results:

ERROR: [DEPRECATED]: include + with_items is a removed deprecated feature.  Please update your playbooks.
