### ISSUE TITLE
vmware_cluster_drs support for advanced configuration parameters

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#66217]
##### SUMMARY
Similar to issue #61421 / PR #65675, vmware_cluster_drs module should also support advanced configuration parameters.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vmware_cluster_drs

##### ADDITIONAL INFORMATION

```
name: Enable DRS and distribute a more even number of virtual machines across hosts for availability
  vmware_cluster_drs:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: datacenter
    cluster_name: cluster
    enable_drs: yes
    advanced_settings:
      'TryBalanceVmsPerHost': '1'
```
