### ISSUE TITLE
docker_container does not allow host port ranges binded to a single container port

### ISSUE THREAD

**Issue by desimaniac** [ansible/ansible#66225]
##### SUMMARY

When using docker_container module, attempting to publish a port, using a range of ports from the host, does not work as expected. Instead, Ansible will attempt to use the port number in the range.

Example:

Trying to get a similar docker command as the following running in Ansible.

```
docker run -p 80-85:80 -d linuxserver/nginx
```

As of now, this will cause an error stating `Bind for 0.0.0.0:80 failed: port is already allocated"`

This is a supported command argument in Docker. 

Ref: https://docs.docker.com/network/links/

> Instead, you may specify a range of host ports to bind a container port to that is different than the default ephemeral port range:
>
> `$ docker run -d -p 8000-9000:5000 training/webapp python app.py`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```paste below
(venv) ➜  cloudbox git:(develop) ✗ ansible --version
ansible 2.10.0.dev0
  config file = /srv/git/cloudbox/ansible.cfg
  configured module search path = [u'/home/seed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

```
cloudbox git:(develop) ✗ ansible --version
ansible 2.9.2
  config file = /srv/git/cloudbox/ansible.cfg
  configured module search path = [u'/home/seed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/srv/git/cloudbox/ansible.cfg) = [u'profile_tasks']
DEFAULT_FACT_PATH(/srv/git/cloudbox/ansible.cfg) = /srv/git/cloudbox/ansible_facts.d
DEFAULT_HASH_BEHAVIOUR(/srv/git/cloudbox/ansible.cfg) = merge
DEFAULT_HOST_LIST(/srv/git/cloudbox/ansible.cfg) = [u'/srv/git/cloudbox/inventories/local']
DEFAULT_LOG_PATH(/srv/git/cloudbox/ansible.cfg) = /srv/git/cloudbox/cloudbox.log
DEFAULT_ROLES_PATH(/srv/git/cloudbox/ansible.cfg) = [u'/srv/git/cloudbox/roles', u'/srv/git/cloudbox/resources/roles']
DEFAULT_VAULT_PASSWORD_FILE(/srv/git/cloudbox/ansible.cfg) = /etc/ansible/.ansible_vault
RETRY_FILES_ENABLED(/srv/git/cloudbox/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS. Bare-metal setup

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: Create and start container
      docker_container:
        name: nginx
        image: linuxserver/nginx
        pull: yes
        published_ports:
          - "80-85:80"
        networks:
          - name: cloudbox
            aliases:
              - nginx2
        purge_networks: yes
        restart_policy: unless-stopped
        state: started
    - name: Create and start container
      docker_container:
        name: nginx2
        image: linuxserver/nginx
        pull: yes
        published_ports:
          - "80-85:80"
        networks:
          - name: cloudbox
            aliases:
              - nginx3
        purge_networks: yes
        restart_policy: unless-stopped
        state: started

```

##### EXPECTED RESULTS

Containers nginx2 and nginx3 to be created and binded to whatever host port was available between 80 and 85.

##### ACTUAL RESULTS

https://pastebin.com/MxMrGaHm

Both containers are being binded to port 80 on the host.

**Comment by desimaniac** [comment]
Sorry accidentally hit submit before I was done. I'm filling out the rest of the details as quickly as I can.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/docker/docker_container.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit @WojciechowskiPiotr @akshay196 @chouseknecht @danihodovic @dariko @dusdanig @felixfontein @joshuaconner @jwitko @kassiansun @softzilla @tbouvet @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
The module does as [documented](https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#parameters). That's different from what the `docker` CLI command does, and the main reason the module does this is to make idempotence checking not too complicated. As it is done right now, the module can simply compile a list of published ports (+IPs +protocols) from the options and compare it to the list of ports the container actually published.

**Comment by desimaniac** [comment]
@felixfontein Thanks for getting back. 

How would the idempotence checking be for cases where no host port is defined, eg `published_ports: ['80']` and could `published_ports: ['80-90:80']` not be done the same way?

**Comment by felixfontein** [comment]
Good question, I had to check that :) Turns out that docker is clever enough to store random ranges in such cases. Here are inspection results from some tests (also for me for later):

`docker run -p 80 ...`:
```
    "PortBindings": {
        "80/tcp": [
            {
                "HostIp": "",
                "HostPort": ""
            }
        ]
    },
```

`docker run -p 80-85:80 ...`:
```
    "PortBindings": {
        "80/tcp": [
            {
                "HostIp": "",
                "HostPort": "80-85"
            }
        ]
    },
```

`docker run -p 90-95:80-85 ...`:
```
    "PortBindings": {
        "80/tcp": [
            {
                "HostIp": "",
                "HostPort": "90"
            }
        ],
        "81/tcp": [
            {
                "HostIp": "",
                "HostPort": "91"
            }
        ],
        ...
        "85/tcp": [
            {
                "HostIp": "",
                "HostPort": "95"
            }
        ]
    },
```

So you're right, this is pretty simple to implement, also w.r.t. idempotency.

I'm now a bit hesistant to backport this, though, since this change would cause containers using something like `80-85:85` right now to be recreated. Maybe it's better to fix this in `devel` and let this only show up in Ansible 2.10 and later.

**Comment by desimaniac** [comment]
Ah good find and thanks for checking. And sorry for my bad grammar/typos earlier... Cleaned that post up :p. 

> Maybe it's better to fix this in devel and let this only show up in Ansible 2.10 and later.

That would be awesome! Thank You!

**Comment by felixfontein** [comment]
I've created a PR for this (#66382).

resolved_by_pr #66382

**Comment by desimaniac** [comment]
Thank You!

**Comment by felixfontein** [comment]
@desimaniac you're welcome! I'd be glad if you could try out the PR and mention it there if it works for your use-cases. (If you put the `docker_container.py` file in a subdirectory `library` of the directory where your playbook is in, it should be used by Ansible instead of the default module. Then you can try it directly without meddling with your Ansible installation ;) )

**Comment by desimaniac** [comment]
> (If you put the docker_container.py file in a subdirectory library of the directory where your playbook is in, it should be used by Ansible instead of the default module. Then you can try it directly without meddling with your Ansible installation ;) )

Nice trick! 

---

Test playbook:
```yaml
- hosts: localhost
  tasks:
    - name: Create and start container
      docker_container:
        name: "nginx-test{{ item }}"
        image: linuxserver/nginx
        pull: no
        published_ports:
          - "80-85:80"
        restart_policy: unless-stopped
        state: started
      loop: "{{ range(0, 4) | list }}"
```

Results:
```
CONTAINER ID  IMAGE             COMMAND CREATED              STATUS             PORTS                        NAMES
8d9ea6a11763  linuxserver/nginx "/init" About a minute ago   Up About a minute  443/tcp, 0.0.0.0:84->80/tcp  nginx-test3
9680dbdc8c6c  linuxserver/nginx "/init" About a minute ago   Up About a minute  443/tcp, 0.0.0.0:83->80/tcp  nginx-test2
1fd7d1a1f4c8  linuxserver/nginx "/init" About a minute ago   Up About a minute  443/tcp, 0.0.0.0:82->80/tcp  nginx-test1
10b8653d8874  linuxserver/nginx "/init" About a minute ago   Up About a minute  443/tcp, 0.0.0.0:81->80/tcp  nginx-test0
```

They all have the following:

```json
"PortBindings": {
    "80/tcp": [
        {
            "HostIp": "0.0.0.0",
            "HostPort": "80-85"
        }
    ]
},
```

So everything works great! TY!
