### ISSUE TITLE
copy with remote_src within a block with become escalation leaves tmp files

### ISSUE THREAD

**Issue by leupo** [ansible/ansible#66231]
##### SUMMARY
If used copy with remote_src: true within a block with become escalation ansible leaves tmp files in remote_tmp-Directory.
Tested versions:
2.8.7
2.9.2

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = None
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  ...
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```
```

##### STEPS TO REPRODUCE

echo "123" > /tmp/testfile
Execute(you must have root privileges and a user 'exampleuser':
ansible-playbook main.yml -i "localhost," -e '{ ansible_user: root }'

```
- hosts: "localhost"
  tasks:
  - name: block test
    block:
    - copy:
        src: "/tmp/testfile"
        dest: "/tmp/testfile_new"
        remote_src: true
    become: true
    become_user: "exampleuser" # must exists and have privileges to copy
    become_method: su
```

##### EXPECTED RESULTS
cleanup tempory dir

##### ACTUAL RESULTS
tempory file remains:
/var/tmp/ansible-tmp-1578382024.3181014-223153153358488/AnsiballZ_copy.py

```paste below

```
