### ISSUE TITLE
azure_rm_mysqldatabase does not set charset as expected.

### ISSUE THREAD

**Issue by dumblerod** [ansible/ansible#66251]
##### SUMMARY
When using the azure_rm_mysqldatabase module, using the charset or collation parameter does not work.  The database is ALWAYS created with latin1 instead of valid values passed into charset.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_mysqldatabase

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jarrod/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jarrod/.local/lib/python2.7/site-packages/ansible
  executable location = /home/jarrod/.local/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION
```
No changes
```

##### OS / ENVIRONMENT
Running in Azure

##### STEPS TO REPRODUCE
Run the following tasks to create a database:

```
  - name: Create empty database
    azure_rm_mysqldatabase:
      resource_group: "someresourcegroup"
      server_name: "mysqlservername"
      name: "mydbname"
      charset: "utf8"
      collation: "utf8_general_ci"
      force_update: "true"
```

##### EXPECTED RESULTS
I expect the database to be created with default charset of utf8.  Instead it is always created as latin1.

##### ACTUAL RESULTS
Database is created with charset as latin1
