### ISSUE TITLE
lambda_event module fails with non-standard aws partitions

### ISSUE THREAD

**Issue by garethbdavis** [ansible/ansible#66250]
##### SUMMARY

The lambda_event module does not handle aws partitions other than 'aws', for example 'aws-us-gov'.

A similar issue for the lambda module was resolved here: https://github.com/ansible/ansible/pull/28704

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lambda_event

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
```

##### CONFIGURATION

```paste below
no changes
```

##### STEPS TO REPRODUCE

- Use an AWS account in a non standard partition (e.g. us-gov-west-1)
- Create a lambda event (e.g. with sqs event_source, but it doesn't matter which source) referencing the lambda arn.
- Ansible will not detected the arn as an arn due to the partition, and will instead interpret it as a function name.  This causes a failure due to the function name being too long.
- Using the function name instead of arn will fail on the source_arn for the queue first, but the module code will try to expand the function name into and arn with the aws partition anyway. 

```yaml
- name: lambda_event test
  hosts: localhost
  tasks:
    - name: deploy lambda event
      lambda_event:
        state: present
        event_source: sqs
        region: us-gov-west-1                              
        lambda_function_arn: arn:aws-us-gov:lambda:us-gov-west-1:XXXXXXXXXXXX:function:my-function
        source_params:
          source_arn: arn:aws-us-gov:sqs:us-gov-west-1:XXXXXXXXXXXX:my-queue
          enabled: True
          batch_size: 1
```

##### EXPECTED RESULTS

Successful run with event created

##### ACTUAL RESULTS

play fails with character limit error

```paste below
TASK [deploy lambda event] ***************************************************************************************************************************
task path: /Users/XXXXXX/code/lambda_event_test/lambda_event_play.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: XXXXXX
<127.0.0.1> EXEC /bin/sh -c 'echo ~XXXXXX && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672 `" && echo ansible-tmp-1578418012.3666828-36294176732672="` echo /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672 `" ) && sleep 0'
Using module file /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ansible/modules/cloud/amazon/lambda_event.py
<127.0.0.1> PUT /Users/XXXXXX/.ansible/tmp/ansible-local-3267zon7bz72/tmpzje66vo6 TO /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672/AnsiballZ_lambda_event.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672/ /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672/AnsiballZ_lambda_event.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672/AnsiballZ_lambda_event.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/XXXXXX/.ansible/tmp/ansible-tmp-1578418012.3666828-36294176732672/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "alias": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "event_source": "sqs",
            "lambda_function_arn": "arn:aws-us-gov:lambda:us-gov-west-1:XXXXXXXXXXXX:function:my-function",
            "profile": null,
            "region": "us-gov-west-1",
            "security_token": null,
            "source_params": {
                "batch_size": 1,
                "enabled": true,
                "source_arn": "arn:aws-us-gov:sqs:us-gov-west-1:XXXXXXXXXXXX:my-queue"
            },
            "state": "present",
            "validate_certs": true,
            "version": 0
        }
    },
    "msg": "Function name \"arn:aws-us-gov:lambda:us-gov-west-1:XXXXXXXXXXXX:function:my-function\" exceeds 64 character limit"
}
```
