### ISSUE TITLE
Umask 0022 not working

### ISSUE THREAD

**Issue by rmasudur** [ansible/ansible#66280]
I've following task in Ansible playbook YAML. 
```
...
    become: yes
    become_user: root
    tasks:
      - name: Change Umask to 0022 to make installer working
        shell: umask 0022
...
```

But it's not working. Having following error during playbook run:

```
fatal: [********]: FAILED! => {"changed": true, "cmd": "./installer-binary.run --mode text --disable_glibcxx_version_check 1", "delta": "0:00:30.128584", "end": "2020-01-08 18:53:55.234070", "msg": "command exceeded timeout", "rc": null, "start": "2020-01-08 18:53:25.105486", "stdout": "\r\r\nError: There has been an error.\r\r\nThe installation has detected that the current umask is set to permissions of \r\r\n0027, the installation is now exiting. You should modify your umask to at least \r\r\n0022 before launching the installer. After the installation has completed, reset \r\r\nthe umask permissions to your original values.\r\r\nPress [Enter] to continue:", "stdout_lines": ["", "", "Error: There has been an error.", "", "The installation has detected that the current umask is set to permissions of ", "", "0027, the installation is now exiting. You should modify your umask to at least ", "", "0022 before launching the installer. After the installation has completed, reset ", "", "the umask permissions to your original values.", "", "Press [Enter] to continue:"]}
```
Could you please help me to set umask 0022.
