### ISSUE TITLE
When-clause on outer block wrongly executed for inner block

### ISSUE THREAD

**Issue by sorenmogensen** [ansible/ansible#66295]
##### SUMMARY
We have roles that check existence of facts before including other roles to determine those facts; this used to work fine, however after upgrading from 2.4.2 to 2.9.0 (and later 2.9.2) this appears to be broken.

It would appear that Ansible (at least from 2.9.0 through 2.9.2) is re-evaluating the when clause on the outer block when it evaluates the when clause on the inner block. It doesn't matter what the when clause is on the inner block, it will never execute if the outer when clause is no longer true. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

When clauses on nested blocks

##### ANSIBLE VERSION
```paste below
ansible 2.9.2
  config file = /opt/ibm/metaocean/provisioning/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/opt/ibm/metaocean/provisioning/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/opt/ibm/metaocean/provisioning/ansible.cfg) = -C -o CheckHostIP=no -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=6
ANSIBLE_SSH_CONTROL_PATH(/opt/ibm/metaocean/provisioning/ansible.cfg) = ~/.ssh/ansible-ssh-%%h-%%p-%%r
ANSIBLE_SSH_RETRIES(/opt/ibm/metaocean/provisioning/ansible.cfg) = 3
ANY_ERRORS_FATAL(/opt/ibm/metaocean/provisioning/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/opt/ibm/metaocean/provisioning/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/opt/ibm/metaocean/provisioning/ansible.cfg) = ['/opt/ibm/metaocean/provisioning/hosts']
DEFAULT_LOG_PATH(/opt/ibm/metaocean/provisioning/ansible.cfg) = /opt/ibm/metaocean/provisioning/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/opt/ibm/metaocean/provisioning/ansible.cfg) = /opt/ibm/metaocean/provisioning/ssh_key
DEFAULT_REMOTE_USER(/opt/ibm/metaocean/provisioning/ansible.cfg) = moadmin
DEFAULT_ROLES_PATH(/opt/ibm/metaocean/provisioning/ansible.cfg) = ['/opt/ibm/metaocean/provisioning/roles']
DEPRECATION_WARNINGS(/opt/ibm/metaocean/provisioning/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/ibm/metaocean/provisioning/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7.7

##### STEPS TO REPRODUCE

Define an outer block with a when clause depending on the existence of a fact, within the block define the missing fact then have a nested block with a when clause - the nested block will never execute.

```yaml
- hosts: master
  gather_facts: no
  tasks:
    - block:
      - set_fact:
          my_fact: true
      - block:
        - debug: msg="hello world"
        when: true
      when: my_fact is not defined
```

##### EXPECTED RESULTS

The tasks within the nested block should execute as the associated when clause evaluates to true.

##### ACTUAL RESULTS

The tasks from the inner block are all skipped because the outer when clause no longer evaluates to true.

```paste below
PLAY [master] **********************************************************************************************************************************************************************************************
META: ran handlers

TASK [set_fact] ********************************************************************************************************************************************************************************************
task path: /opt/ibm/metaocean/provisioning/play2.yaml:5
Thursday 09 January 2020  04:15:11 -0700 (0:00:00.190)       0:00:00.190 ****** 
ok: [IP] => {
    "ansible_facts": {
        "my_fact": true
    },
    "changed": false
}

TASK [debug] ***********************************************************************************************************************************************************************************************
task path: /opt/ibm/metaocean/provisioning/play2.yaml:8
Thursday 09 January 2020  04:15:11 -0700 (0:00:00.092)       0:00:00.283 ****** 
skipping: [IP] => {}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************************
IP               : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/block.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/block.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is expected. The `when` conditional is applied to each task within the block, so your example is equivalent to:

```yaml
- set_fact:
    my_fact: true
  when: my_fact is not defined

- block:
    - debug: msg="hello world"
  when: true and my_fact is not defined
```

To achieve your goal you can do the following:

playbook.yml:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - include_tasks:
        file: tasks.yml
      when: my_fact is not defined
```
tasks.yml:
```yaml
- set_fact:
    my_fact: true
- block:
  - debug: msg="hello world"
  when: true
```

Here the `when` conditional is applied to the `include_tasks` task itself, as opposed to `blocks` and `import_role` when the conditional is applied to all tasks within.

Basically the same example is in the documentation: https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#applying-when-to-roles-imports-and-includes

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by sorenmogensen** [comment]
I understand that, and have found the commit where we introduced an outer block - however, I still believe there is a problem here in that what we're actually doing is slightly more complicated and looks more like what you suggest is the solution!

I.e. the inner when clause is actually inside an include_tasks. I find it confusing that the following 2 playbooks perform differently:

play1.yaml:
```
- hosts: localhost
  gather_facts: no
  tasks:
    - block:
        - include_tasks:
            file: tasks.yaml
      when: my_fact is not defined
```
play2.yaml:
```
- hosts: localhost
  gather_facts: no
  tasks:
    - include_tasks:
        file: tasks.yaml
      when: my_fact is not defined
```
tasks.yaml:
```
- set_fact:
    my_fact: true
- block:
  - debug: msg="hello world"
  when: true
```

I.e. the outer when-clause is passed in through "include_tasks" differently depending on whether there is a surrounding block.

**Comment by mkrizek** [comment]
I understand the confusion.

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - block:
        - include_tasks:
            file: tasks.yaml
      when: my_fact is not defined
```

Here the conditional is applied to `include_tasks` and since it's evaluated to true, the tasks are included into the `block`. The difference (from the second example) is that the conditional is again applied to the included tasks because each task within the `block` inherits the `when`.

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - include_tasks:
        file: tasks.yaml
      when: my_fact is not defined
```

Here, as I mentioned earlier, the `when` conditional is applied to `include_tasks` itself, not to tasks within.

Hope that makes sense.
