### ISSUE TITLE
postgresql_table fails when try to create a column that has like name a reserved word

### ISSUE THREAD

**Issue by truki** [ansible/ansible#66303]
##### SUMMARY
When i try to create a table that has a field (column) with a name that it's a reserved word fail.
According to official documentation of Prostgresql if you want to use a field with a name that it's a reserved word you have to enclose between double quotes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_table

##### ANSIBLE VERSION
```
ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sergio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
not relevant

##### STEPS TO REPRODUCE
Executing this play that create a table with a column with name "group".

```yaml
- name: ---- Create table
  postgresql_table:
    name: xxxxx
    login_host: "{{ xxxx }}"
    login_user: "{{ xxxx_user }}"
    login_password: "{{ xxxxx_pass }}"
    db: xxxx_dbname
    columns:       
      - id VARCHAR(32) NOT NULL PRIMARY KEY
      - "group" VARCHAR(50)
      - type VARCHAR(50)
      - sub_type VARCHAR(50)
      - property VARCHAR(50)      
    state: present
  register: table_output
```

##### EXPECTED RESULTS
Table with the fields specified in the play, specifically "group" field. 

##### ACTUAL RESULTS

```
ERROR! Syntax Error while loading YAML.
 did not find expected '-' indicator
The error appears to be in '...tasks/main.yml': line 279, column 17, but may be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
 - topic VARCHAR(50)
 - "group" VARCHAR(50)
             ^ here
```
