### ISSUE TITLE
Allow tunneling through Google Cloud IAP when using dynamic inventory provided with inventory plugin gcp_compute.py

### ISSUE THREAD

**Issue by shadowzen1978** [ansible/ansible#66310]
##### SUMMARY
The inventory plugin **[gcp_compute.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/gcp_compute.py)** will return compute instances using private ip addresses (or hostnames) if a public ip address is not assigned.  However, Ansible cannot manage configuration of these resources if being run from outside of that private network.

I've tried to implement an ssh wrapper to remedy this but that's a global change to ansible config (supposedly, an ssh wrapper can be defined at inventory level but couldn't get it to work using a dynamic inventory file and documentation on ansible_ssh_executable is sorely lacking.

I partially got this working by parsing ansible ssh commands to format for **gcloud compute ssh** command but had trouble properly parsing ssh arguments and this method quickly becomes convoluted if using multiple projects using multiple gcloud sdk configurations in the local environment Ansible is being run in.  Plus, it reduces the portability of the ansible-playbooks if multiple people are managing them.

I know it's also possible to configure access through a bastion host but that also requires changes to ssh configuration in a local environment and to have a dedicated compute instance as the bastion host.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
gcp_compute.py

##### ADDITIONAL INFORMATION
Since the inventory plugin allows for dynamically showing compute instances using gcp service credentials, it would be nice to the plugin to allow Ansible to communicate with those resources using the same service account credentials, project, zone, and other values as defined in the dynamic inventory file.

Since I have multiple dynamic inventory files that may define different sets of resources, including ones that may be in their own project that uses different credentials from what my local gcloud sdk configuration profile defines, it would be nice to have Ansible regard the credentials within the dynamic inventory file as the source of truth if configuring against those resources.  The gcloud cli command supports overriding default project/zone values, etc.

It might be nice to have GCE dynamic inventory file also allow for defining ansible ssh_args values at the inventory level but that might not be a concern depending on how this feature would be implemented

```yaml
---
# Dynamic inventory file example
plugin: gcp_compute
projects:
  - project-name
zones:
  - "us-east1-b"
auth_kind: serviceaccount
service_account_file: "~/path/to/service-account-file.json"

filters:
  - labels.environment = development
hostnames:
  # If public_ip doesn't exist here, will return private_ip value
  # Would prefer to use name but might be more complicated to differentiate 
  # between instances that have public ips and those that don't and I think
  # using public_ip would be quicker if available rather than tunneling through
  # IAP for every resource.
  #- name
  - public_ip
  - private_ip
groups:
  # These define the groups that specific roles are applied to.
  dev: "*"
  frontend-hosts: "'frontend' in name"
  backend-hosts: "'backend' in name"
  nginx-ingress: "'nginx-ingress' in labels"
  graphql: "'graphql' in labels"
  postgres: "'postgres' in labels"
  neo4j: "'neo4j' in labels"
  docker-hosts: [frontend-hosts, backend-hosts]
keyed_groups:
  # I have group_vars files prepended by _env and also _inv to define 
  # environments, in addition to the filter above (_inv can be a subset of 
  # development resources or instances in a 2nd dev environment, for example).  
  # This is a dynamic inventory file specifically for development instances
  # as defined by the filter but I also have an all.gcp.yml file defined
  # without the filter that will apply configs as defined by labels.
  - prefix: _tagged
    key: tags['items']
  - prefix: _env
    key: labels['environment']
  - prefix: _inv
    key: labels['inventory-class']

```
