### ISSUE TITLE
k8s_scale is getting failed with error: "msg": "Exception reading event stream: "

### ISSUE THREAD

**Issue by deepakpal-in** [ansible/ansible#66344]
##### SUMMARY
ansible version: 2.7.8 
kubectl: 1.14.3
kubeadm: 1.14.3

While performing the scaleup operation on some of my resources under k8s cluster k8s_scale module is getting failed with below error:

> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Exception reading event stream: "}

I suspect this issue is arising because my resources are taking some time to come up running. But to avoid that situation I have already used the below wait parameters:

```
    wait: yes
    wait_timeout: 600

```

but in any scenarios, it is waiting for only 60 sec to get a response and then getting failed out with the provided error, although I have provided wait_timeout to wait for 600 sec and tried with more as well:

> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Exception reading event stream: "}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_scale

##### ANSIBLE VERSION

```ansible version: 2.7.8 

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Centos 7.5

##### STEPS TO REPRODUCE

```
- name: Scale deployment up for logstash
  k8s_scale:
    wait_timeout: 600
    api_version: v1
    kind: Deployment
    name: logstash
    namespace: logstash
    current_replicas: 0
    replicas: 1

```

I have also tried with :

```
- name: Scale deployment up for logstash
  k8s_scale:
    wait: yes
    wait_timeout: 600
    api_version: v1
    kind: Deployment
    name: logstash
    namespace: logstash
    current_replicas: 0
    replicas: 1


```

##### EXPECTED RESULTS

Deployment scaled up completely

##### ACTUAL RESULTS

```
got this error:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Exception reading event stream: "}
```
