### ISSUE TITLE
VMware: vmware_tag ignores category_id

### ISSUE THREAD

**Issue by DaLnx** [ansible/ansible#66340]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_tag

##### ANSIBLE VERSION

```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Create Tag in Category ITManager within VMware and create by ansible in other Category the same Tag

Task for create same tag in Category Owner:

```
- name: Create tag to category
  vmware_tag:
    hostname: "{{ pr_vsphere_vcenter_name }}"
    username: "{{ pr_vsphere_datacenter_username }}"
    password: "{{ pr_vsphere_datacenter_userpass }}"
    validate_certs: no
    category_id: "{{ category_id }}"
    tag_name: "{{ Owner | lower }}"
    tag_description: ""
    state: present
  delegate_to: localhost

```

##### EXPECTED RESULTS

"ansible_module_results": {
        "msg": "Tag 'user@company.com' created.",
        "tag_id": "urn:vmomi:InventoryServiceTag:....."

##### ACTUAL RESULTS

    "ansible_module_results": {
        "msg": "Tag user@company.com updated.",
        "tag_id": "urn:vmomi:InventoryServiceTag....."

Update the tag (tested using tag_description) already existing in another category, but do not create the tag in the indicated category.

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_tag.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_tag.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@DaLnx, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@DaLnx Could you please check if PR https://github.com/ansible/ansible/pull/61082 and let me know if it works for you? Thanks.

needs_info

**Comment by DaLnx** [comment]
With vmware_tag we create several tags and with vmware_tag_manager we assign them to a vmguest.

Result of calls to vmware_tag in the two categories:
Owner category, does not exist in it.
{
    "_ansible_no_log": false,
    "ansible_module_results": {
        "msg": "Tag user@company.com is unchanged.",
        "tag_id": "urn: vmomi: InventoryServiceTag: d682a09a-c57d-470e-abdf-a5bc068ab69d: GLOBAL"
    },
    "invocation": {
        "module_args": {
            "username": "ansibleuser@vsphere.local",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "https",
            "hostname": "vcenter.company.com",
            "tag_name": "user@company.com",
            "state": "present",
            "tag_description": "",
            "category_id": "urn: vmomi: InventoryServiceCategory: a716ccdc-03d5-47c4-aa70-5aac4b068f8a: GLOBAL",
            "validate_certs": false
        }
    },
    "changed": false
}

ITManager category, already exists in it.
{
    "_ansible_no_log": false,
    "ansible_module_results": {
        "msg": "Tag user@company.com is unchanged.",
        "tag_id": "urn: vmomi: InventoryServiceTag: d682a09a-c57d-470e-abdf-a5bc068ab69d: GLOBAL"
    },
    "invocation": {
        "module_args": {
            "username": "ansibleuser@vsphere.local",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protocol": "https",
            "hostname": "vcenter.company.com",
            "tag_name": "user@company.com",
            "state": "present",
            "tag_description": "",
            "category_id": "'urn: vmomi: InventoryServiceCategory: f08a0451-dec0-4215-8808-bba391ce2295: GLOBAL'",
            "validate_certs": false
        }
    },
    "changed": false
}

When I use vmware_tag_manager the result is:
{
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "username": "ansibleuser@vsphere.local",
            "object_type": "VirtualMachine",
            "protocol": "https",
            "hostname": "vcenter.company.com",
            "object_name": "VMGUEST",
            "state": "present",
            "tag_names": [
                "Owner: user@company.com",
                "Department: IT",
                "ITManager: user@company.com"
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "changed": false,
    "msg": "Category Owner does not contain tag user@company.com"
}

**Comment by Akasurde** [comment]
@DaLnx Could you please paste the output of following - 

```yaml
- name: Gather category id from given tag category
  vmware_category_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
  delegate_to: localhost
  register: tag_category_results

- set_fact:
    category_id: "{{ item }}"
  loop: "{{ tag_category_results.tag_category_info|json_query(query) }}"
  vars:
    query: "[?category_name==`Owner`]"

- debug: var=category_id
```
