### ISSUE TITLE
mso_schema_template_anp_epg_contract sometimes not idempotent ?

### ISSUE THREAD

**Issue by YoucefYousfi** [ansible/ansible#66354]
##### SUMMARY
I am using mso_schema_template_anp_epg_contract module to add contracts to an epg. On first run, it works as expected and it effectively adds the contract.
However, when I run the playbook again, it returns an error 400 Bad Request.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mso_schema_template_anp_epg_contract

##### ANSIBLE VERSION

ansible 2.9.2
  config file = None
  configured module search path = ['/home/gsb780/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gsb780/myvenvs/ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/gsb780/myvenvs/ansible/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]

##### CONFIGURATION

MSO version : 2.2(2d)

##### OS / ENVIRONMENT

CentOS Linux release 8.0.1905 (Core)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  become: false
  vars:
    epgs: 
      - { schema: SCHEMA_PRD_CLOUD, template: Template1, anp: AP_CLOUD_L3, epg: EPG_CLOUD_1552}
      - { schema: SCHEMA_PRD_CLOUD, template: Template1, anp: AP_CLOUD_L3, epg: EPG_CLOUD_1553}
  tasks:

  - name: ctr_epg_any to EPG provider
    mso_schema_template_anp_epg_contract:
      host: 10.10.10.10
      username: username
      password: 'password'
      anp: "{{ item.anp }}"
      epg: "{{ item.epg }}"
      schema: "{{ item.schema }}"
      template: "{{ item.template }}"
      contract:
        name: ctr_epg_any
        type: provider
      state: present
      validate_certs: False
    with_items:
      - "{{ epgs }}"
```

##### EXPECTED RESULTS

It should display the "ok" usual output whenever I am running the playbook.

##### ACTUAL RESULTS

On first run, it works as expected. On next runs, it displays this everytime :
![image](https://user-images.githubusercontent.com/59737779/72164488-0e9e0680-33c6-11ea-88fd-dd30e0c2f93a.png)
