### ISSUE TITLE
azure_rm_virtualmachine: "Error myvm has a provisioning state of Updating. Expecting state to be Succeeded."

### ISSUE THREAD

**Issue by julien1091** [ansible/ansible#66358]
##### SUMMARY

I encountering an issue when I use the Azure module **"azure_rm_virtualmachine"** to change the state of linux VM.__"updating"__ state is not handle by the module.
After some tests it seems the issue occured when the VM is in bad state and keep the status "updating"
For example we see the status "updating" (on the azure UI) when we update the flavor.

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- **azure_rm_virtualmachine**

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /home/users/fx12345/ansible/ansible_dev.cfg
  configured module search path = [u'/home/users/fx12345/ansible/library']
  ansible python module location = /home/users/fx12345/ansible/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/users/fx12345/ansible/.venv/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
DEFAULT_BECOME_METHOD(/home/***/ansible/ansible_dev.cfg) = sudo
DEFAULT_BECOME_USER(/home/***/ansible/ansible_dev.cfg) = root
DEFAULT_GATHER_TIMEOUT(/home/***/ansible/ansible_dev.cfg) = 30
DEFAULT_HOST_LIST(/home/***/ansible/ansible_dev.cfg) = [u'/home/***/ansible/inventory/azure-dev']
DEFAULT_LOG_PATH(/home/***/ansible/ansible_dev.cfg) = /home/***/ansible.log
DEFAULT_MODULE_PATH(/home/***/ansible/ansible_dev.cfg) = [u'/home/***/ansible/library']
DEFAULT_ROLES_PATH(/home/***/ansible/ansible_dev.cfg) = [u'/home/***/ansible/roles']
DEFAULT_VAULT_IDENTITY_LIST(/home/***/ansible/ansible_dev.cfg) = []
HOST_KEY_CHECKING(/home/***/ansible/ansible_dev.cfg) = False
INVENTORY_ENABLED(/home/***/ansible/ansible_dev.cfg) = [u'yaml', u'azure_rm', u'script']
RETRY_FILES_ENABLED(/home/***/ansible/ansible_dev.cfg) = False
```

##### OS / ENVIRONMENT

Controller: RHEL 7.4

##### STEPS TO REPRODUCE

```yaml
#ansible-playbook -i inventory/azure-dev playbooks/01-azure/04-test-status-lifecycle.yml -e d4x_vm_started="yes" -vvv
```

```yaml
---
- name: Playbook to reproduce issue
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - name: Set several variables
      set_fact:
        vm_fqdn: myvm.aze.michelin.com
        vm_name: myvm
        vm_resource_group: XXX
        vm_subscription_id: xxxxxxxxxxxx
        tenantId: xxxxxxxxxxx
        clientId: xxxxxxxxxxxxxxxxx
        secret: xxxxxxxxxxxxxxxx

    - name: Get fact from VM
      azure_rm_virtualmachine_facts:
        name: "{{ vm_name }}"
        resource_group: "{{ vm_resource_group }}"
        subscription_id: "{{ vm_subscription_id }}"
        tenant: "{{ tenantId }}"
        client_id: "{{ clientId }}"
        secret: "{{ secret }}"
      register: vm_state_before

    - name: Display value of 'd4x_vm_operation'
      debug:
        msg: "d4x_vm_started is set to {{ d4x_vm_started }}"

    - name: Display state of the VM before operation.
      debug:
        msg: "Before operation VM has powerstate '{{ vm_state_before.vms[0].power_state }}'"

    - name: Stop/Start Azure VM
      azure_rm_virtualmachine:
        name: "{{ vm_name }}"
        os_disk_caching: "{{ vm_state_before.vms[0].os_disk_caching }}"
        os_type: "{{ vm_state_before.vms[0].os_type }}"
        started: "{{ d4x_vm_started }}"
        state: present
        resource_group: "{{ vm_resource_group }}"
        subscription_id: "{{ vm_subscription_id }}"
        tenant: "{{ tenantId }}"
        client_id: "{{ clientId }}"
        secret: "{{ secret }}"
      register: vm_state_after

```

##### EXPECTED RESULTS
The code should handle the "updating" state.

##### ACTUAL RESULTS

Without extra verbosity:
```
TASK [azure/vm_lifecycle : Display state of the VM before operation.] **********
ok: [localhost] => {
    "msg": "Before operation VM has powerstate 'running'"
}
TASK [azure/vm_lifecycle : Display message for the start VM] *******************
ok: [localhost] => {
    "msg": "The vm \"myvm\" is starting."
}
TASK [azure/vm_lifecycle : Start Azure VM] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error myvm has a provisioning state of Updating. Expecting state to be Succeeded."}

```

With extra verbosity:
```
TASK [Display state of the VM before operation.] **************************************************************************************************************************************
task path: /home/users/fx12345/ansible/playbooks/01-azure/04-test-status-lifecycle.yml:43
ok: [localhost] =>
  msg: Before operation VM has powerstate 'running'

TASK [Stop/Start Azure VM] ************************************************************************************************************************************************************
task path: /home/users/fx12345/ansible/playbooks/01-azure/04-test-status-lifecycle.yml:47
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: fx12345
<localhost> EXEC /bin/sh -c 'echo ~fx12345 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760 `" && echo ansible-tmp-1578651521.36-86442862519760="` echo /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760 `" ) && sleep 0'
Using module file /home/users/fx12345/ansible/.venv/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
<localhost> PUT /home/users/fx12345/.ansible/tmp/ansible-local-571049UJN1F/tmpbKd_89 TO /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760/AnsiballZ_azure_rm_virtualmachine.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760/ /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760/AnsiballZ_azure_rm_virtualmachine.py && sleep 0'
<localhost> EXEC /bin/sh -c 'HTTPS_PROXY=http://proxy.aze.michelin.com:80/ HTTP_PROXY=http://proxy.aze.michelin.com:80/ /usr/bin/env python /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760/AnsiballZ_azure_rm_virtualmachine.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/users/fx12345/.ansible/tmp/ansible-tmp-1578651521.36-86442862519760/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      accept_terms: false
      ad_user: null
      adfs_authority_url: null
      admin_password: null
      admin_username: null
      allocated: true
      api_profile: latest
      append_tags: true
      auth_source: null
      availability_set: null
      cert_validation_mode: null
      client_id: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      cloud_environment: AzureCloud
      custom_data: null
      data_disks: null
      generalized: false
      image: null
      license_type: null
      location: null
      managed_disk_type: null
      name: myvm
      network_interface_names: null
      open_ports: null
      os_disk_caching: ReadWrite
      os_disk_name: null
      os_disk_size_gb: null
      os_type: Linux
      password: null
      plan: null
      profile: null
      public_ip_allocation_method: Static
      remove_on_absent:
      - all
      resource_group: mbd
      restarted: false
      secret: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      short_hostname: null
      ssh_password_enabled: true
      ssh_public_keys: null
      started: false
      state: present
      storage_account_name: null
      storage_blob_name: null
      storage_container_name: vhds
      subnet_name: null
      subscription_id: 1e3c156c-65c0-45b6-bf1a-cd78569041e3
      tags: null
      tenant: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      virtual_network_name: null
      virtual_network_resource_group: null
      vm_identity: null
      vm_size: null
      winrm: null
      zones: null
  msg: Error myvm has a provisioning state of Updating. Expecting state to be Succeeded.

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
