### ISSUE TITLE
mso_schema_template_external_epg_contract weird behavior with multiple contracts

### ISSUE THREAD

**Issue by YoucefYousfi** [ansible/ansible#66360]
##### SUMMARY
I am using mso_schema_template_external_epg_contract module to add 3 contracts to an external epg. On first run, it works as expected and it effectively adds the contracts.
However, when I run the playbook again, it has a weird behavior that I display below on obtained results.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mso_schema_template_external_epg_contract

##### ANSIBLE VERSION

ansible 2.9.2
  config file = None
  configured module search path = ['/home/gsb780/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gsb780/myvenvs/ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/gsb780/myvenvs/ansible/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]

##### CONFIGURATION

MSO version : 2.2(2d)

##### OS / ENVIRONMENT

CentOS Linux release 8.0.1905 (Core)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  become: false
  vars:
    epgs: 
      - { schema: SCHEMA_PRD_CLOUD, template: Template1, epg: EXT_EPG_CLOUD_1}
      - { schema: SCHEMA_PRD_CLOUD, template: Template1, epg: EXT_EPG_CLOUD_2}
  tasks:

  - name: ctr_l3out_any to EPG consumer
    mso_schema_template_external_epg_contract:
      host: 10.10.10.10
      username: username
      password: 'password'
      external_epg: "{{ item.epg }}"
      schema: "{{ item.schema }}"
      template: "{{ item.template }}"
      contract:
        name: ctr_l3out_any
        type: consumer
      state: present
      validate_certs: False
    with_items:
      - "{{ epgs }}"
  
  - name: ctr_epg_any to EPG consumer
    mso_schema_template_external_epg_contract:
      host: 10.10.10.10
      username: username
      password: 'password'
      external_epg: "{{ item.epg }}"
      schema: "{{ item.schema }}"
      template: "{{ item.template }}"
      contract:
        name: ctr_epg_any
        type: consumer
      state: present
      validate_certs: False
    with_items:
      - "{{ epgs }}"

  - name: ctr_epg_any to EPG provider
    mso_schema_template_external_epg_contract:
      host: 10.10.10.10
      username: username
      password: 'password'
      external_epg: "{{ item.epg }}"
      schema: "{{ item.schema }}"
      template: "{{ item.template }}"
      contract:
        name: ctr_epg_any
        type: provider
      state: present
      validate_certs: False
    with_items:
      - "{{ epgs }}"
```

##### EXPECTED RESULTS

It should display the "ok" usual output whenever I am running the playbook, and not modify any contract if they already exist.
![image](https://user-images.githubusercontent.com/59737779/72168979-82dca800-33ce-11ea-835f-6ef1ba66c28c.png)
![image](https://user-images.githubusercontent.com/59737779/72169006-8e2fd380-33ce-11ea-97c9-2378e8873745.png)

##### ACTUAL RESULTS

On first run, it works as expected. On next runs, it displays "changed" on ansible output and when checking on the mso I see this :
![image](https://user-images.githubusercontent.com/59737779/72169058-ac95cf00-33ce-11ea-9b44-2babb8ae5b53.png)
![image](https://user-images.githubusercontent.com/59737779/72169088-bc151800-33ce-11ea-8ade-7e1a1fb5a16c.png)
![image](https://user-images.githubusercontent.com/59737779/72169113-c7684380-33ce-11ea-9459-f1e11fa60d94.png)
