### ISSUE TITLE
nxos_vlans not recognizing support parameters

### ISSUE THREAD

**Issue by michmoor0725** [ansible/ansible#66387]
##### SUMMARY
Running network module per spec but it does not see the supported parameter that i am supposed to use.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_vlans

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Cisco  3548 Hardware  
BIOS: version 2.0.10
  NXOS: version 7.0(3)I7(4)
  BIOS compile time:  03/06/2018
  NXOS image file is: bootflash:///nxos.7.0.3.I7.4.bin

##### STEPS TO REPRODUCE

```yaml
---
- name: VLAN CONFIGURATION
  connection: network_cli
  hosts: spares
  gather_facts: false
  tasks:
    - name: Merge provided configuration with device configuration.
      nxos_vlans:
        config:
         - vlan_id: 5
           name: test-vlan5
         - vlan_id: 10
           enabled: False
        state: merged
```

##### EXPECTED RESULTS

Expect VLANs to be created on the target host

##### ACTUAL RESULTS

fatal: [172.25.164.213]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Unsupported parameters for (nxos_vlans) module: provider Supported parameters include: config, state"}

```paste below

```
