### ISSUE TITLE
Unable to setup Replica Set when a KeyFile and authorization is enabled

### ISSUE THREAD

**Issue by thy143** [ansible/ansible#66395]
##### SUMMARY

I have created three MongoDB servers (running version 4.2) which have been configured with “authorization: enabled” and a “keyFile”. When attempting to create a replica set using mongodb_replicaset, it errors out as it is unable not authorized to execute a command. 

On a fresh install MongoDB server with the above settings enabled, you can manual (via shell) login using localhost, create a replica set on all nodes and finally setup user authentication to allow authentication outside of localhost.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mongodb_replicaset

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

##### CONFIGURATION

```paste below
No Output
```

##### OS / ENVIRONMENT

Ubuntu 1804 with MongoDB 4.2

##### STEPS TO REPRODUCE

Using three MongoDB servers with the following config:
```
cat /etc/mongod.conf

#
# Ansible managed
#

storage:
  dbPath: /var/lib/mongodb
  directoryPerDB: false
  journal:
    enabled: true
systemLog:
  logAppend: true
security:
  keyFile: /etc/mongodb/keyfile/keyfile
  authorization: enabled
replication:
  replSetName: rs0
net:
   bindIp: localhost,<lan ip>,mongodb01
```
run the below task:

```yaml
- name: Setup Replica Set
  mongodb_replicaset:
    login_host: localhost
    login_user: ""
    login_password: ""
    replica_set: rs0
    members:
    - mongodb1:27017
    - mongodb2:27017
    - mongodb3:27017
  when: groups.mongod.index(inventory_hostname) == 0
```

##### EXPECTED RESULTS

Create a replicaset without user authentication

##### ACTUAL RESULTS

Module / task errors out unable to query the mongodb server

```paste below

The full traceback is:
  File "/tmp/ansible_mongodb_replicaset_payload_40mwp3sm/ansible_mongodb_replicaset_payload.zip/ansible/modules/database/mongodb/mongodb_replicaset.py", line 391, in main
  File "/tmp/ansible_mongodb_replicaset_payload_40mwp3sm/ansible_mongodb_replicaset_payload.zip/ansible/modules/database/mongodb/mongodb_replicaset.py", line 218, in replicaset_find
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/cursor.py", line 1073, in _refresh
    self.__send_message(q)
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
    address=self.__address)
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
    exhaust=exhaust)
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
    unpack_res)
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(first)
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)

fatal: [mongodb01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "arbiter_at_index": null,
            "chaining_allowed": true,
            "election_timeout_millis": 10000,
            "heartbeat_timeout_secs": 10,
            "login_database": "admin",
            "login_host": "localhost",
            "login_password": "",
            "login_port": 27017,
            "login_user": "",
            "members": [
                "mongodb01:27017",
                "mongodb02:27017",
                "mongodb03:27017"
            ],
            "protocol_version": 1,
            "replica_set": "rs0",
            "ssl": false,
            "ssl_cert_reqs": "CERT_REQUIRED",
            "validate": true
        }
    },
    "msg": "Unable to query replica_set info: not authorized on local to execute command { find: \"system.replset\", filter: {}, $db: \"local\", $readPreference: { mode: \"primaryPreferred\" } }"
}


```
