### ISSUE TITLE
meta: reset_connection not working on Ansible 2.9.1

### ISSUE THREAD

**Issue by Slowdive-Aideron** [ansible/ansible#66414]
##### SUMMARY
I add a user to a group, execute the meta module reset_connection, check the group association again, just to find that the connection is still the same. And it's still the same ssh session!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Meta Module : reset_connection 

##### ANSIBLE VERSION
ansible 2.9.1                                                                                                                                                                         config file = /workspace/ansible_test_2@2/ansible/ansible.cfg                                                                                                                    configured module search path = [u'/var/jenkins_home/.ansible/plugins/modules', u'/usr/shar   e/ansible/plugins/modules']                                                                                                                                                                ansible python module location = /usr/lib/python2.7/site-packages/ansible                                                                                                           executable location = /usr/bin/ansible                                                                                                                                                   python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-                                                                                            39)]                                      

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
ANSIBLE_SSH_ARGS(/workspace/ansible_test_2@2/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m                                                                           ANSIBLE_SSH_CONTROL_PATH(/workspace/ansible_test_2@2/ansible/ansible.cfg) = %(directory)s/%%h-%%p-%%r                                                                                     DEFAULT_HOST_LIST(/workspace/ansible_test_2@2/ansible/ansible.cfg) = [u'/environmen_data']                                                                                                DEFAULT_REMOTE_USER(/workspace/ansible_test_2@2/ansible/ansible.cfg) = USER                                                                                                               DEFAULT_ROLES_PATH(/workspace/ansible_test_2@2/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles', u'/${WORKSPACE}/ansible/roles', u'/workspace/ansible_test_2@2/aHOST_KEY_CHECKING(/workspace/ansible_test_2@2/ansible/ansible.cfg) = False 
```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
Targed OS = Red Hat Enterprise Linux Server release 7.7 (Maipo) running a normal docker-ce installation 
Source OS = Docker Container based on a CentOS v5 image, Ansible has been installed manually and it works perfectly. 


##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->
Check group association with id shell command, change group association using the normal ansible module -> Check id shell command again. 
<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: Id Check 1 
  shell: id 
  register: id_output 

- name: Give output of Id Check 1 
  debug: 
   msg: '{{ id_output.stdout }}'

- name: Modify User User group association 
  user: 
   name: '{{ ansible_user }}'
   groups: docker
   append: true
   state: present

- name: reset the SSH_CONNECTION!!!!
  meta: reset_connection 

# Optional , try a docker  command 

- name: try a docker ps command                                                                                                                                                             
  shell: docker ps                                                                                                                                                                          
  register: docker_output                                                                                                                                                                   
  ignore_errors: true                                                                                                                                                                                                                                                                                                                                                               

- name: give output of docker command                                                                                                                                                       
  debug:                                                                                                                                                                                     
   msg: '{{ docker_output.stdout  }}'

- name: Id Check 2 
  shell: id 
  register: id_output_2 

- name: Give output of Id Check 2 
  debug: 
   msg: '{{ id_output_2.stdout }}'

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
The ansible user is added to the docker group, SSH Connection is resetted so that group association is updated. And the second ID command reflects the new group association.  

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
The session is not interrupted, so that the current session is not updated with the new Group ! Thus i cannot use a docker command.
<!--- Paste verbatim command output between quotes -->
```paste below
The -vvv run of the playbook runs with the META task    .                                                                                                                                                                              META: reset connection 
So maybe i'm missing something,  But i cannot find any indicator that it's the problem with my config file or so. 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/utilities/helper/meta.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This should work. Can you provide the output with `-vvvv`?

needs_info

**Comment by Lin-Buo-Ren** [comment]
@samdoran 
Encountered this issue as well, here are the required info:
[ansible-issue-66414.vvvv.out.tar.gz](https://github.com/ansible/ansible/files/4198990/ansible-issue-66414.vvvv.out.tar.gz)

**Comment by Lin-Buo-Ren** [comment]
Also noticed that:

* The issue can NOT be reproduced when ssh_connection.control_path is not defined
* Reproduced in Ansible 2.8.5 as well, not a regression in the 2.9.1 Ansible release

@Slowdive-Aideron Can you verify if that's the case for you as well?

**Comment by Lin-Buo-Ren** [comment]
Playbook for reproducing the issue:

```yaml
- name: Check whether reset_connection works
  hosts: all
  gather_facts: False
  tasks:
    - name: Print current ssh connection persistence processes
      delegate_to: localhost
      shell: 'ps x | grep -E "ssh: .* \[mux\]"'

    - name: Create connection to test machine
      ping:

    - name: Print message as META module won't in non verbose mode
      debug:
        msg: Calling meta module to reset_connection

    - name: Intentionally reset connection
      meta: reset_connection

    - name: Create connection to test machine again
      ping:

    - name: Print current ssh connection persistence processes again, ensure the process ID of the SSH process of the managed node's connection changes
      delegate_to: localhost
      shell: 'ps x | grep -E "ssh: .* \[mux\]"'

```

Set `defaults.stdout_callback` configuration setting to `debug` to ease the verification:

```ini
[defaults]
stdout_callback = debug
```

**Comment by ansibot** [comment]
@Slowdive-Aideron This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Lin-Buo-Ren** [comment]
Or should I file a new issue for my specific case :frowning:

**Comment by Slowdive-Aideron** [comment]
Issue is still persisting .. here 's my SSH conn options : 
ssh_args = -o ControlMaster=auto -o ControlPersist=30m                                                                                                                                                             control_path = ~/.ssh/ansible-%%r@%%h:%%p

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/meta.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/meta.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by AmoVanB** [comment]
We have the same issue. Currently, we use the following workaround
```yaml
- name: reset ssh connection to allow user changes to affect 'current login user'
  shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
  async: 5
  poll: 1
```
to kill the SSH connection and reconnect.
