### ISSUE TITLE
Support for installing packages by binary path

### ISSUE THREAD

**Issue by psss** [ansible/ansible#66424]
##### SUMMARY
Add support for installing packages by binary path similarly as dnf does.

##### ISSUE TYPE
- Feature

##### COMPONENT NAME
dnf

##### ADDITIONAL INFORMATION
Sometimes package names differ across distros or product versions.  For such cases it would be very useful to have the option to provide binary path instead of the package name. See example below:

```yaml
- hosts: localhost
  tasks:
  - name: Install packages
    dnf:
      name:
      - /usr/bin/virtualenv
```

This could be handled in the same way how `dnf` supports the feature:

    dnf install /usr/bin/virtualenv

Currently the following error is displayed when the playbook above is run on Fedora:

    No group usr/bin/virtualenv available.

Thanks for looking into this.
