### ISSUE TITLE
RFE: Allow passing a list to the service and source parameters of firewalld

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#66449]
##### SUMMARY
A zone can have many services and sources associated with it.  Allow passing a list to the source parameter of firewalld like you can with yum/dnf.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
firewalld

##### ADDITIONAL INFORMATION

```yaml
  - name: "Define internal zone"
    firewalld:
      service:
         - http
         - https
      source: 
        - 192.168.0.0/16
        - 10.0.0.0/8
      zone: internal
      immediate: yes
      permanent: yes
      state: enabled
```
