### ISSUE TITLE
VMware: require "vmware_host_facts" module return ESXi server update version info

### ISSUE THREAD

**Issue by Tomorrow9** [ansible/ansible#66457]
##### SUMMARY

Now "vmware_host_facts" module returns the ESXi version and build number, no update version info, so request getting that info too.
References:
https://www.virtuallyghetto.com/2016/08/quick-tip-how-to-retrieve-the-esxi-update-level-using-the-vsphere-api.html
MOB path:
https://esxi_hostname/mob/?moid=ha-adv-options&doPath=setting%5b%22Misc.HostAgentUpdateLevel%22%5d

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vmware_host_facts
##### ADDITIONAL INFORMATION

Some features of ESXi are introduced in specific ESXi update release, so it's better to get that info and use it as a condition before some tasks. 

```yaml

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_host_facts.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @goneri @lparkes @pgbidkar @warthog9 @woshihaoren
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sky-joker** [comment]
Hi @Tomorrow9

In the latest version of vmware_guest_facts module, an option to specify schema and properties has been added.
https://docs.ansible.com/ansible/devel/modules/vmware_host_facts_module.html#vmware-host-facts-module

I think you can get the desired version information in the following Playbook example.

```yaml
---
- name: example playbook for issue 64457
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: vcenter server
    vcenter_username: administrator@vsphere.local
    vcenter_password: password
    esxi_hostname: esxi-host.local
  tasks:
    - name: gather host facts
      vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_hostname }}"
        schema: vsphere
        properties:
          - config.product
          - config.option
      register: gather_host_facts_result

    - debug:
        msg:
          - "Product : {{ gather_host_facts_result.ansible_facts.config.product.name }}"
          - "Version : {{ gather_host_facts_result.ansible_facts.config.product.version }}"
          - "Build : {{ gather_host_facts_result.ansible_facts.config.product.build }}"
          - "Update: {{ item.value }}"
      loop: "{{ gather_host_facts_result.ansible_facts.config.option }}"
      when:
        - item.key == 'Misc.HostAgentUpdateLevel'
```

run the playbook.

```
(venv) [root@localhost 66457]# ANSIBLE_DISPLAY_SKIPPED_HOSTS=False ansible-playbook example.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [example playbook for issue 64457] ********************************************************************************************************************************************

TASK [gather host facts] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ***********************************************************************************************************************************************************************
ok: [localhost] => (item={'_vimtype': 'vim.option.OptionValue', 'key': 'Misc.HostAgentUpdateLevel', 'value': '0'}) => {
    "msg": [
        "Product : VMware ESXi",
        "Version : 6.7.0",
        "Build : 8169922",
        "Update: 0"
    ]
}

PLAY RECAP *************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
