### ISSUE TITLE
s3_sync upload error

### ISSUE THREAD

**Issue by devopsnsysadm** [ansible/ansible#66458]
##### SUMMARY
I'm using the Ansible s3_sync module to sync 1TB+ data to an S3 bucket. But I'm receiving the following error:
`An error occurred (400) when calling the HeadObject operation: Bad Request`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
s3_sync

##### ANSIBLE VERSION
```
2.9.1
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
CentOS7

##### STEPS TO REPRODUCE
Upload multiple files sizing over 1TB to the S3 bucket.

```yaml
---
- hosts: prodweb
  tasks:
    - name: Creating the attachment backup folder within the Amazon S3 platform...
      aws_s3:
        aws_access_key: "AKIAJDDAdndknkdnf"
        aws_secret_key: "jfbkjfbkjbfvjvbCXvWHnQh2TP"
        s3_url: https://s3.us-east-1.amazonaws.com
        bucket: attachment-backups
        object: "{{ ansible_nodename }}"
        mode: create
        overwrite: "false"
        rgw: true

    - name: Syncing the changes to the S3 platform....
      s3_sync:
        aws_access_key: "AKIAJDDAdndknkdnf"
        aws_secret_key: "jfbkjfbkjbfvjvbCXvWHnQh2TP"
        bucket: attachment-backups
        file_root: /home/prodweb/attachment/
        key_prefix: "{{ ansible_nodename }}"
        region: us-east-1
      retries: 5
      delay: 2

```
