### ISSUE TITLE
zabbix_template dump/import errors

### ISSUE THREAD

**Issue by rockaut** [ansible/ansible#66466]
##### SUMMARY
Dumping a zabbix template to a file and then importing it again doesn't work.
Maybe related to #55439 but other errors.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_template

##### ANSIBLE VERSION
```paste below
ansible 2.9.2
  config file = /mnt/d/Code/gitlab/zabbix-servers/ansible/ansible.cfg
  configured module search path = ['/home/fism/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/d/Code/gitlab/zabbix-servers/venv/lib/python3.6/site-packages/ansible
  executable location = /mnt/d/Code/gitlab/zabbix-servers/venv/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### OS / ENVIRONMENT
Zabbix 4.4.4 Server on RHEL7

##### STEPS TO REPRODUCE
Dump templates to files 
```yaml
- name: "dump template - {{ item }} ..."
  zabbix_template:
    server_url: "{{ zabbix_apiserver_url }}"
    login_user: "{{ zabbix_apiuser_rw }}"
    login_password: "{{ zabbix_apipassword_rw }}"
    state: dump
    dump_format: xml
    template_name: "{{ item }}"
  register: zabbix_template_dump

- name: "save template - {{ item }} ..."
  copy:
    content: "{{ zabbix_template_dump.template_xml }}"
    dest: "{{ inventory_dir }}/templates/{{ template_file }}.xml"
```

Import the files again:
```yaml
- name: "import template - {{ template_src }} ..."
  vars:
    ansible_python_interpreter: "python3"
  zabbix_template:
    server_url: "{{ zabbix_apiserver_url }}"
    login_user: "{{ zabbix_apiuser_rw }}"
    login_password: "{{ zabbix_apipassword_rw }}"
    template_xml: "{{ lookup('file', template_src) }}"
    dump_format: xml
    state: present
```

##### EXPECTED RESULTS
The templates should be dumped to the files and then imported again to zabbix.

##### ACTUAL RESULTS
Maybe two problems here:

1. the files getting exported with a byte-type object. That's the actual file. Checked it - it is already that way in the template_xml property

```text
b'<zabbix_export><version>4.4</version><date>2020-01-14T08:49:45Z</date><groups><group><name>Templates</name></group></groups><templates><template><template>fisma</template><name>fisma</name><groups><group><name>Templates</name></group></groups></template></templates></zabbix_export>'
```

```text
TASK [zabbix/common : dump template - fismb ...] *******************************************************************************************************************************************************
task path: tasks/export-template.yml:8
Tuesday 14 January 2020  09:49:47 +0100 (0:00:00.092)       0:00:07.127 *******
Pipelining is enabled.
<localhost> EXEC /bin/sh -c 'python3 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "clear_templates": null,
            "dump_format": "xml",
            "http_login_password": null,
            "http_login_user": null,
            "link_templates": null,
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "macros": null,
            "server_url": "https://*******/",
            "state": "dump",
            "template_groups": null,
            "template_json": null,
            "template_name": "fismb",
            "template_xml": null,
            "timeout": 10,
            "validate_certs": true
        }
    },
    "template_xml": "b'<zabbix_export><version>4.4</version><date>2020-01-14T08:49:48Z</date><groups><group><name>Templates</name></group></groups><templates><template><template>fismb</template><name>
fismb</name><groups><group><name>Templates</name></group></groups></template></templates></zabbix_export>'"
```

If we then import the file an error occures.

```text
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zabbix_template_payload_93hxjtco/ansible_zabbix_template_payload.zip/ansible/modules/zabbix_template.py", line 544, in load_xml_template
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1

fatal: [localhost]: FAILED! => {
    "changed": false,
    "details": "not well-formed (invalid token): line 1, column 1",
    "invocation": {
        "module_args": {
            "clear_templates": null,
            "dump_format": "xml",
            "http_login_password": null,
            "http_login_user": null,
            "link_templates": null,
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "macros": null,
            "server_url": "https://**********/",
            "state": "present",
            "template_groups": null,
            "template_json": null,
            "template_name": null,
            "template_xml": "b'<zabbix_export><version>4.4</version><date>2020-01-14T08:49:45Z</date><groups><group><name>Templates</name></group></groups><templates><template><template>fisma</templat
e><name>fisma</name><groups><group><name>Templates</name></group></groups></template></templates></zabbix_export>'",
            "timeout": 10,
            "validate_certs": true
        }
    },
    "msg": "Invalid XML provided"
}
```
