### ISSUE TITLE
vmware_guest_network: No option to configure newly added interfaces

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#66468]
##### SUMMARY
No option to configure IP/Netmask/Gateway/DNS on an interface after adding it to the vm.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- vmware_guest_network

##### ADDITIONAL INFORMATION
Currently `vmware_guest_network` module can add/remove interface but cant configure them. So its not fully usable for vm's network operations related activities.

#### To attach an interface:
```
---
- name: Attach Private nic to provision server
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_vars.yml
  tasks:
    - name: Attach Private Network Adapters for FW Deployment
      vmware_guest_network:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        validate_certs: 'no'
        gather_network_info: false
        name: '{{ vsphere_vm_name }}'
        networks:
          - name: "{{ FW_Private_network }}"
            device_type: vmxnet3
            state: new
            label: "Network adapter 2"
            connected: true
            start_connected: true
      delegate_to: localhost
```

In the `networks` section there should be parameter like ip, netmask, gateway, dns, wait_for_ip_address etc to support the network configuration as they are there in `vmware_guest` module.

Future playbook should look something like:

```
---
- name: Attach Private nic to provision server
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_vars.yml
  tasks:
    - name: Attach Private Network Adapters for FW Deployment
      vmware_guest_network:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        validate_certs: 'no'
        gather_network_info: false
        name: '{{ vsphere_vm_name }}'
        networks:
          - name: "{{ FW_Private_network }}"
            device_type: vmxnet3
            state: new
            label: "Network adapter 2"
            connected: true
            start_connected: true
            ip: 192.168.1.2                           <<
            netmask: 255.255.255.0             <<
            gateway: 192.168.1.1                 <<
            dns_servers:                               <<
              - 10.10.10.10          
              - 10.10.10.11
        wait_for_ip_address: True               <<
      delegate_to: localhost
```

In `vmware_guest`, take a look at the network settings section to understand how its enabling the ip, nm, gateway, dns etc parameters. We need similar functionality here in `vmware_guest_network` module too.

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1792

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest_network.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_network.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Udayendu, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@Tomorrow9 Could you please take a look since you originally authored this module?

Thanks in advance.

**Comment by mariolenz** [comment]
I don't think this is a good idea. Adding a (virtual) NIC and configuring it are conceptually two different things.

Some people might want to add more than just one IP, and there are also port groups that aren't native; so the module would also have to this into account. This would make the module very complex and hard to maintain. I don't think this makes sense, the _vmware_-module should be responsible for adding the vNIC and the _OS-specific_-networking-module should be responsible for configuring the interface.

There are several problems I foresee when adding this functionality to vmware_guest_network while it's quite easy for you to just write two tasks:

1. Add vNic
2. Configure networking **inside** the OS

**Comment by Udayendu** [comment]
> 2\. Configure networking **inside** the OS

So according to you how the nic configuration need to be done in OS level. I have tried using `vmware_guest` module but its not working. `vmware_guest` module can configure the nic only at the time of vm deployment. Not on a running vm. 

So logically just for adding nic to a vm why some one need automation. Then to do the manual task to configure the nics in side the OS. Its an overhead. Automation should support end to end activity.

**Comment by Udayendu** [comment]
Now I got what you are saying. I tried with nmcli and able to configure it.

#### Working Playbook:

```
---
- name: Attach Private nic to provision server
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_vars.yml
  tasks:
    - name: Attach Private Network Adapters for FW Deployment
      vmware_guest_network:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        validate_certs: 'no'
        gather_network_info: false
        name: '{{ vsphere_vm_name }}'
        networks:
          - name: "{{ vsphere_network02 }}"
            device_type: vmxnet3
            state: new
            label: "Network adapter 2"
            connected: true
            start_connected: true
      delegate_to: localhost

    - name: Configure Network Interface 'ens192'
      nmcli:
        type: ethernet
        conn_name: 'ens192'
        ifname: 'ens192'
        ip4: 192.168.1.2/24
        state: present
```

May be we can drop this RFE.
