### ISSUE TITLE
vmware_vm_shell to have some become methode

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#66472]
Hey, using ansible 2.9.2

 I couldnt find information about how to run powershell as admin using vm_shell,
if theres a way it is not in the docs.

I need to run a script but it wont run unless i am runing 
vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
as admin.

From ansible side, i see playbook output in green with no errors. but in my vm nothing happands.
also if there some kind of error it only shows  general error, :
```
    "msg": "Failed to execute command",
    "name": "powershell.exe",

```
working output : 
```
ok: [localhost] => {
    "msg": {
        "changed": true,
        "cmd_line": "\"C:\\Windows\\System32\\WindowsPowershell\\v1.0\\powershell.exe\" -ExecutionPolicy Bypass -File create_user.ps1 -pass \"********7\" -user \"Tom1\" -gr \"Administrators\"",
        "end_time": "2020-01-14T13:53:22+00:00",
        "exit_code": 0,
        "failed": false,
        "name": "powershell.exe",
        "owner": "myuser",
        "start_time": "2020-01-14T13:53:21+00:00",
        "uuid": "420b2895-43ec-87c2-fdbf-53e527dff2a4"
    }
}
```

my playbook:

```
---
- hosts: localhost
  connection: local
  vars:
  vars_files:
            - vars.yml
  tasks:
    - name: "Createing windows user"
      vmware_vm_shell:
        cluster: "{{ cluster }}"
        datacenter: "{{ datacenter }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user  }}"
        password: "{{ vcenter_pass }}"
        folder: "{{ folder }}"
        vm_id: "{{ name }}"
        vm_username: "{{ vm_username }}"
        vm_password: "{{ vm_password }}"
        vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
        vm_shell_args: -ExecutionPolicy Bypass -File create_user.ps1 -pass "{{ pass }}" -user "{{ user }}" -gr "{{ gr }}"
        vm_shell_cwd: 'C:\Users\myuser\Desktop'
        wait_for_process: yes
        validate_certs: no
      delegate_to: localhost
      register: shell_command_output
    - debug:
            msg: "{{ shell_command_output }}"

```

my powershell script:
```
param (
	[Parameter(Mandatory=$True)]
	[string]$pass,
	[Parameter(Mandatory=$True)]
	[string]$user,
	[Parameter(Mandatory=$True)]
	[string]$gr
)

$Password = ConvertTo-SecureString -AsPlainText $pass -Force
New-LocalUser $user -Password $Password
Add-LocalGroupMember -Group $gr -Member $user


```
When i run script manually with powershell open as admin it works when i run:
`powershell.exe -ExecutionPolicy Bypass -File create_user.ps1 -pass "123" -user "tom" -gr "administrators"
`

I dont understad why ansible shows no errors while my script really not runing. 
I belive that it is related to "Run as admin"
Thanks

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@batchenr: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
!component =lib/ansible/modules/cloud/vmware/vmware_vm_shell.py

**Comment by Akasurde** [comment]
@batchenr Thanks for reporting this issue. `vmware_vm_shell` uses vSphere APIs to execute the task on the given VM. It is not related to `become` of Ansible. What is `vm_username` value? Is it a normal user or admin user on Windows VM? 

needs_info

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_vm_shell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vm_shell.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Tomorrow9 @chrrrles @goneri @lparkes @pgbidkar @ritzk @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by batchenr** [comment]
> @batchenr Thanks for reporting this issue. `vmware_vm_shell` uses vSphere APIs to execute the task on the given VM. It is not related to `become` of Ansible. What is `vm_username` value? Is it a normal user or admin user on Windows VM?
> 
> needs_info

The user in vm_username is a user in the windows vm and the user is in Administrators group, 
when i run the same command in the vm, it works.
i dont understad why ansible gives "no errors" but script is not really runing and i have no info on how to solve it.

also, before the script i was tring to run multipul commands in a row using ansible, 
thats also somthing that doesnt work 

```
        vm_shell: 'c:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
        vm_shell_args: '$Password= ConvertTo-SecureString {{ Password }} -AsPlainText -Force ; New-LocalUser {{ Username}} -Password {{ Password }} ; Add-LocalGroupMember -Group {{ Group }} -Member {{ Username }}'

```

because this doesnt work ( and also giving me "no errors") i switched to using a script.
please help.

**Comment by Akasurde** [comment]
@batchenr I am able to run your playbook successfully, but not sure what is wrong in your environment.

```yaml
---
- hosts: localhost
  vars_files:
    - vcenter_vars.yml
  vars:
    cluster: Asia-Cluster1
    datacenter: Asia-Datacenter1
    folder: /Asia-Datacenter1/vm
    name: Win2k16
    vm_username: Administrator
    vm_password: Secret123
    user: tom
    pass_word: esxi123
    gr: administrators
  tasks:
  - name: Get all tags
    vmware_vm_shell:
      cluster: "{{ cluster }}"
      datacenter: "{{ datacenter }}"
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      folder: "{{ folder }}"
      vm_id: "{{ name }}"
      vm_username: "{{ vm_username }}"
      vm_password: "{{ vm_password }}"
      vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
      vm_shell_args: -ExecutionPolicy Bypass -File create_user.ps1 -pass "{{ pass_word }}" -user "{{ user }}" -gr "{{ gr }}"
      vm_shell_cwd: 'C:\Users\Administrator\Desktop'
      wait_for_process: yes
      validate_certs: no
    delegate_to: localhost

```

Console - 

```
changed: [localhost -> localhost] => {
    "changed": true,
    "cmd_line": "\"C:\\Windows\\System32\\WindowsPowershell\\v1.0\\powershell.exe\" -ExecutionPolicy Bypass -File create_user.ps1 -pass \"esxi123\" -user \"tom\" -gr \"administrators\"",
    "end_time": "2020-01-14T13:34:56+00:00",
    "exit_code": 0,
    "invocation": {
        "module_args": {
            "cluster": "Asia-Cluster1",
            "datacenter": "Asia-Datacenter1",
            "folder": "/Asia-Datacenter1/vm",
            "hostname": "10.65.200.211",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "timeout": 3600,
            "username": "administrator@vsphere.local",
            "validate_certs": false,
            "vm_id": "Win2k16",
            "vm_id_type": "vm_name",
            "vm_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vm_shell": "C:\\Windows\\System32\\WindowsPowershell\\v1.0\\powershell.exe",
            "vm_shell_args": "-ExecutionPolicy Bypass -File create_user.ps1 -pass \"esxi123\" -user \"tom\" -gr \"administrators\"",
            "vm_shell_cwd": "C:\\Users\\Administrator\\Desktop",
            "vm_shell_env": null,
            "vm_username": "Administrator",
            "wait_for_process": true
        }
    },
    "name": "powershell.exe",
    "owner": "Administrator",
    "start_time": "2020-01-14T13:34:54+00:00",
    "uuid": "4217531d-f175-cc54-812c-61d3ccfb04db"
}
```

<img width="801" alt="Screenshot 2020-01-14 at 7 06 58 PM" src="https://user-images.githubusercontent.com/633765/72348747-167ce400-3701-11ea-83bd-466c09f858c9.png">

needs_info
