### ISSUE TITLE
azure_rm_virtualmachine_info.py fails to get vm by tag

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#66489]
##### SUMMARY

azure_rm_virtualmachine_info module fails to get info by tag on a VM. 

This does not happen on other VMs we have. I was not able to find the actual difference or why this error appeared with ansible 2.9.2.

I check the VM and the tag SQL exists. There was no problem in ansible version < 2.9.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine_info 

##### ANSIBLE VERSION

```paste below
2.9.2
```

##### STEPS TO REPRODUCE

```
- name: "get virtual machine facts by tag {{ tag }}"
  azure_rm_virtualmachine_info:
    tenant: '{{ tenant }}'
    client_id: '{{ client_id }}'
    secret: '{{ secret }}'
    subscription_id: '{{ subscription_id }}'
    tags:
      - type:{{ tag }}
  register: virtualmachine_facts
  delegate_to: localhost
```

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_azure_rm_virtualmachine_info_payload_y101o6xj/ansible_azure_rm_virtualmachine_info_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine_info.py", line 355, in get_vm
  File "/tmp/ansible_azure_rm_virtualmachine_info_payload_y101o6xj/ansible_azure_rm_virtualmachine_info_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine_info.py", line 420, in serialize_vm

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "cloud_environment": "AzureCloud",
            "name": null,
            "password": null,
            "profile": null,
            "resource_group": null,
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "subscription_id": "XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX",
            "tags": [
                "type:SQL"
            ],
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "msg": "Error getting virtual machine None - 'consoleScreenshotBlobUri'"
}
```
