### ISSUE TITLE
VLAN CHANGE THROUGH VARIABLE AND WITH_ITEMS LOOP

### ISSUE THREAD

**Issue by divesh37** [ansible/ansible#66494]
##### SUMMARY

I am trying to change vlan using a variable stored in file.yaml but while executing playbook it doesn't work seems I am missing something request you to help us achieving.

My switch is cisco ios but not able to do it.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

!component

##### ADDITIONAL INFORMATION

```yaml
- hosts: aswitch
  connection: local
  become: yes
  gather_facts: False
  vars_files:
        - processing/aport.yaml

  tasks:
 - name: take the config backup of the interface
      ios_command:
         commands: show run interface {{ item }}
         authorize: yes
         auth_pass: gen1234
      with_items: "{{ sport }}"
      register: sport
    - name: alskdfjalskdfj alskdj fkasdfj
      debug:
        var: sport

    - local_action: copy content={{ sport }} dest=processing/backup.log

    - name: Add interfaces to VLAN
      ios_vlan:
        vlan_id: 260
        authorize: yes
        auth_pass: gen1234
        interfaces: "{{ item }}"
      with_items: "{{ sport }}"
```
