### ISSUE TITLE
Add ipv4.dns-options support to nmcli

### ISSUE THREAD

**Issue by chilledornaments** [ansible/ansible#66498]
##### SUMMARY
The `nmcli` module currently lacks support for specifying DNS options.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`nmcli`

##### ADDITIONAL INFORMATION
[DNS options](http://man7.org/linux/man-pages/man5/resolv.conf.5.html) give control over the system's resolver. We primarily use DNS options to rotate queries between our DNS servers and specify query timeouts. However, you could use a DNS option to, say, force DNS over TCP, if you were so inclined. Adding this feature to `nmcli` gives greater control over a system's networking stack. 

I've created a [PR](https://github.com/ansible/ansible/pull/66429) for this change

Example playbook with `dns4_options`:

```yaml
- name: Create static IP with dns-options using nmcli
  nmcli:
    conn_name: eth0
    dns4: 10.0.0.2 10.0.0.3
    dns4_search: example.com
    dns4_options: rotate timeout:2
    gw4: 10.0.0.1
    ip4: 10.0.0.4
    state: present
    type: ethernet
```
