### ISSUE TITLE
win_domain_user -  create multiple users via inventory

### ISSUE THREAD

**Issue by sudoerss** [ansible/ansible#66508]
Hello,
I would like to build an inventory to create several users at the same time
basically I'm trying to populate the users variable with different users
```
- name: Create Users
   win_domain_user:
     name: {{ users }}
     firstname: {{ firstname }}
     surname: {{ surname }}
     password: {{ password }}
     groups: {{ groups }}
     state: present
```
Thanks
