### ISSUE TITLE
Bug: variables go out of scope inside an included template

### ISSUE THREAD

**Issue by machpo** [ansible/ansible#6653]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5
##### Environment:

debian 7
##### Summary:

Variables go out of scope inside an included template
##### Steps To Reproduce:

hosts.yml:

```

---
- hosts: all
  vars:
    mylist:
      - alpha
      - bravo
  tasks:
  - name: template test
    template: src=test.j2 dest=/tmp/testfile
```

test.j2:

```
{% for x in mylist %}

  X: {{ x }}

  {% include 'test-inc.j2' with context %}

{% endfor %}
```

test-inc.j2:

```
{{ x }}

```
##### Expected Results:

I expect x in test-inc.j2 to be properly dereferenced
##### Actual Results:

fatal: [myhost] => {'msg': "One or more undefined variables: 'x' is undefined", 'failed': True}
fatal: [myhost] => {'msg': "One or more undefined variables: 'x' is undefined", 'failed': True}
