### ISSUE TITLE
win_psmodule doesn't support private repositories that require authentication

### ISSUE THREAD

**Issue by passbt** [ansible/ansible#66538]
##### SUMMARY
I use a private NuGet repository that requires credentials for reading the feed and accessing artifacts. When I try to install a module from the private repository I get the error below.

```
{
    "nuget_changed": false,
    "_ansible_no_log": false,
    "changed": false,
    "repository_changed": false,
    "msg": "Problems installing test module: No match was found for the specified search criteria and module name 'test'. Try Get-PSRepository to see all available registered module repositories.",
    "output": ""
}
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_psmodule

##### ADDITIONAL INFORMATION
The Ansible module win_psmodule appears to wrap around various CmdLets in Native PowerShell modules `PackageManagement` and `PowerShellGet` like `Get-Module` and `Install-Module`. These Cmdlets expose a credential parameters that isn't being exposed by win_psmodule.

If I follow the instructions in the error message, I do see the the registered repository I'm using and I'm able to successfully list the 'test' module and install it using the native PowerShell command below.

```
$creds = Get-Credentials
Install-Module -name test -repository MyPrivateRepo -credentials $creds
```

The non-working yaml being used for this module is below.
```
- name: Install Test module
  win_psmodule:
    repository: MyPrivateRepo 
    name: test
```

Suggested enhancement would allow for this:

```
- name: Install Test module
  win_psmodule:
    repository: MyPrivateRepo 
    name: test
    repo_user: "{{ ansible_user }}"
   repo_passwd: "{{ ansible_password }}"
```

The win_psmodule would, then build the pscredential type object from the repo_user and repo_passwd parameters when specified and pass them along to the native PowerShell CmdLets.
