### ISSUE TITLE
Feature request - win_authorized_key module for Windows

### ISSUE THREAD

**Issue by sbilque** [ansible/ansible#66561]
##### SUMMARY
Include an Ansible module to add or to remove SSH authorized keys for particular user accounts on Windows-based systems.

This module runs like the `authorized_key` module for Linux.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_authorized_key

##### ADDITIONAL INFORMATION
To improve Windows management over SSH.

Example based on modules `informatiquecdc.win_authorized_key` and `informatiquecdc.win_password` available in Ansible Galaxy.

```yaml
- name: Deploy a ssh key on windows
  hosts: all
  tasks:

    - name: generate a complex password
      informatiquecdc.win_password:
        length: 20
        min_upper_case: 3
        min_lower_case: 3
        min_digit: 3
        min_special: 2

    - name: create the local account 
      win_user:
        name: myuser
        groups: administrators
        state: present
        password: "{{ win_complex_password }}"
        fullname: 'My remote account'

    - name: create the local user profile
      win_user_profile:
        username: myuser
        state: present

    - name: add the ssh public key in the local user profile
      informatiquecdc.win_authorized_key:
        user: myuser
        state: present
        key: "{{ lookup('file', playbook_dir + '/ssh/myuser.pub') }}" 
        exclusive: yes
```
