### ISSUE TITLE
lxd_container: lxc command not found in PATH

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#66597]
##### SUMMARY
fatal: [lxdserver01]: FAILED! => {"msg": "lxc command not found in PATH"}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lxd container

##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams # if you get a 404, try setting protocol: simplestreams
          alias: ubuntu/xenial/amd64
        profiles: ["default"]
        timeout: 600
    - name: touch
      delegate_to: mycontainer
      raw: touch /root/test.txt
      changed_when: false
```
hosts.ini
```
lxdserver01 ansible_host=172.16.72.8 ansible_user=root ansible_python_interpreter=/usr/bin/python3
[linux-containers]
mycontainer ansible_connection=lxd ansible_host=lxdserver01:mycontainer alias=ubuntu/xenial/amd64
```

##### ACTUAL RESULTS

```paste below
TASK [touch] **********************************************************************************************************************************************************************************************************************************
task path: /root/ansible/lxd_install_vps.yml:15
Saturday 18 January 2020  19:33:54 +0000 (0:00:00.913)       0:00:05.579 ****** 
fatal: [lxdserver01]: FAILED! => {
    "msg": "lxc command not found in PATH"
}

```
