### ISSUE TITLE
Role Variables leak to other Roles with docker_container module

### ISSUE THREAD

**Issue by rmanibus** [ansible/ansible#66607]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```paste below
AWX 9.1.0.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

I have the following role:
```yaml
---
# tasks file for create_container

- name: Log into private registry to pull {{image_name}}:{{image_tag}}
  when: registry_token is defined and registry_user is defined
  docker_login:
    registry: "{{registry_url}}"
    username: "{{registry_user}}"
    password: "{{registry_token}}"
    reauthorize: yes

- name: Deploy {{service_name}} {{container_name}} container in {{environment_name}} environment
  vars:
    frontend_labels: "{'traefik.enable': 'true', 'traefik.docker.network': 'frontend-{{environment_name}}', 'traefik.http.services.{{service_name}}-{{environment_name}}.loadbalancer.server.port': '{{service_port | default('80')}}' , 'traefik.http.routers.{{service_name}}-{{environment_name}}_{{container_name}}.rule': 'Host(`{{virtualhost | default('localhost')}}`)'}"
    traefik_labels: "{{ frontend_labels if container_type == 'frontend' else '{}' }}"
    datacenter_labels: {"ansible.service": "{{service_name}}-{{environment_name}}"}
  docker_container:
    name: "{{service_name}}-{{environment_name}}_{{container_name}}_1"
    image: "{{image_name}}:{{image_tag}}"
    state: "{{target_state  | default('started') }}"
    recreate: yes
    pull: yes
    restart_policy: always
    entrypoint: "{{entrypoint | default(omit) }}"
    user: "{{user | default(omit) }}"
    volumes: "{{volumes | default(omit) }}"
    published_ports: "{{published_ports | default(omit) }}"
    networks: "{{networks | default(omit) }}"
    networks_cli_compatible: yes
    labels: "{{traefik_labels | combine( datacenter_labels ) }}"
    env: "{{runtime_vars | default(omit) }}"

```
and the following playbook that create three containers:

```yaml
---
- name: Deploy Web Service
  hosts: all
  vars:
    service_name: sciam-web
    php_vars:
      APP_SECRET: "{{app_secret}}"
      OAUTH_AZURE_CLIENT_SECRET: "{{azure_client_secret}}"
      MAILER_DSN: "{{mailer_dsn}}"
      APP_ENV: REDACTED
      EMAIL_RECIPIENT: REDACTED
      DATABASE_URL: REDACTED
      REDIS_URL: REDACTED
      OAUTH_AZURE_CLIENT_ID: REDACTED
      TRUSTED_PROXIES: REDACTED

  roles:
    - role: create_container
      vars:
        image_name: redis
        image_tag: alpine
        container_name: redis
        container_type: "backend"
        volumes:
          - "{{service_name}}-{{environment_name}}_redis:/data"
        networks:
          - name: backend-{{service_name}}-{{environment_name}}

    - role: create_container
      vars:
        image_name: "{{registry_url}}/myPhpImage"
        image_tag: "{{environment_name}}"
        container_name: cron
        container_type: "backend"
        entrypoint:
          - php
          - bin/console
          - app:run-cron
        user: www-data
        volumes:
          - "{{service_name}}-{{environment_name}}_var:/var/www/html/var"
        networks:
          - name: backend-{{service_name}}-{{environment_name}}
        runtime_vars: "{{php_vars}}"

    - role: create_container
      vars:
        container_type: "frontend"
        image_name: "{{registry_url}}/myPhpImage"
        image_tag: "{{environment_name}}"
        container_name: app
        volumes:
          - "{{service_name}}-{{environment_name}}_var:/var/www/html/var"
        networks:
          - name: backend-{{service_name}}-{{environment_name}}
          - name: frontend-{{environment_name}}
        runtime_vars: "{{php_vars}}"

```

##### EXPECTED RESULTS

The three containers are created with the variables defined in each role

##### ACTUAL RESULTS

if a variable is not defined for a container, instead of beeing omited, it get the value of another role.
for example:
all three containers get the user www-data,
all three containers get the entrypoint php bin/console app:run-cron,
the redis container get the runtime_vars defined for the two php containers.

This is the result that I have for the redis container (the first one):
```paste below
{
    "invocation": {
        "module_args": {
            "tty": false,
            "dns_servers": null,
            "labels": {
                "ansible.service": "sciam-web-staging"
            },
            "docker_host": "unix://var/run/docker.sock",
            "cpuset_cpus": null,
            "force_kill": false,
            "networks": [
                {
                    "ipv6_address": null,
                    "name": "backend-sciam-web-staging",
                    "links": null,
                    "ipv4_address": null,
                    "id": "abb2c82b31b16d354873c8fc74f9b7f00b5cb6511ab9ac89726e0acee45dbf50",
                    "aliases": null
                }
            ],
            "tmpfs": null,
            "device_read_bps": null,
            "capabilities": null,
            "init": false,
            "volumes_from": null,
            "log_options": null,
            "device_write_iops": null,
            "network_mode": null,
            "detach": true,
            "restart": false,
            "name": "sciam-web-staging_redis_1",
            "privileged": false,
            "timeout": 60,
            "debug": false,
            "validate_certs": false,
            "ulimits": null,
            "cpu_shares": null,
            "trust_image_content": false,
            "dns_search_domains": null,
            "env_file": null,
            "cpu_quota": null,
            "cpuset_mems": null,
            "state": "started",
            "oom_killer": null,
            "networks_cli_compatible": true,
            "api_version": "auto",
            "exposed_ports": null,
            "shm_size": null,
            "tls_hostname": "localhost",
            "volume_driver": null,
            "restart_retries": null,
            "groups": null,
            "tls": false,
            "ignore_image": false,
            "sysctls": null,
            "ipc_mode": null,
            "runtime": null,
            "keep_volumes": true,
            "image": "redis:alpine",
            "recreate": true,
            "pid_mode": null,
            "cpu_period": null,
            "oom_score_adj": null,
            "mac_address": null,
            "auto_remove": false,
            "memory_swappiness": null,
            "memory_swap": null,
            "pull": true,
            "stop_signal": null,
            "devices": null,
            "uts": null,
            "blkio_weight": null,
            "published_ports": null,
            "cap_drop": null,
            "interactive": false,
            "links": null,
            "domainname": null,
            "restart_policy": "always",
            "command": null,
            "paused": false,
            "stop_timeout": null,
            "kernel_memory": null,
            "client_key": null,
            "read_only": false,
            "hostname": null,
            "dns_opts": null,
            "working_dir": null,
            "cleanup": false,
            "entrypoint": [
                "php",
                "bin/console",
                "app:run-cron"
            ],
            "env": {
                "MAILER_DSN": "REDACTED",
                "APP_SECRET": "REDACTED",
                "TRUSTED_PROXIES": "REDACTED",
                "APP_ENV": "REDACTED",
                "DATABASE_URL": "REDACTED",
                "REDIS_URL": "REDACTED",
                "EMAIL_RECIPIENT": "REDACTED",
                "OAUTH_AZURE_CLIENT_ID": "REDACTED",
                "OAUTH_AZURE_CLIENT_SECRET": "REDACTED",
            },
            "memory_reservation": null,
            "client_cert": null,
            "memory": "0",
            "log_driver": null,
            "ca_cert": null,
            "healthcheck": null,
            "kill_signal": null,
            "user": "www-data",
            "userns_mode": null,
            "purge_networks": false,
            "output_logs": false,
            "device_read_iops": null,
            "ssl_version": null,
            "security_opts": null,
            "etc_hosts": null,
            "pids_limit": null,
            "volumes": [
                "sciam-web-staging_redis:/data"
            ],
            "comparisons": null,
            "device_write_bps": null
        }
    },
    "changed": true,
    "actions": [
        {
            "create_parameters": {
                "tty": false,
                "stdin_open": false,
                "name": "sciam-web-staging_redis_1",
                "labels": {
                    "ansible.service": "sciam-web-staging"
                },
                "host_config": {
                    "NetworkMode": "default",
                    "Init": false,
                    "Binds": [
                        "sciam-web-staging_redis:/data:rw"
                    ],
                    "RestartPolicy": {
                        "MaximumRetryCount": null,
                        "Name": "always"
                    },
                    "Memory": 0,
                    "ReadonlyRootfs": false
                },
                "environment": {
                    "MAILER_DSN": "REDACTED",
                    "APP_SECRET": "REDACTED",
                    "TRUSTED_PROXIES": "REDACTED",
                    "APP_ENV": "REDACTED",
                    "DATABASE_URL": "REDACTED",
                    "REDIS_URL": "REDACTED",
                    "EMAIL_RECIPIENT": "REDACTED",
                    "OAUTH_AZURE_CLIENT_ID": "REDACTED",
                    "OAUTH_AZURE_CLIENT_SECRET": "REDACTED",
                },
                "entrypoint": "php bin/console app:run-cron",
                "user": "www-data",
                "volumes": [
                    "/data"
                ],
                "detach": true,
                "ports": [],
                "networking_config": {
                    "EndpointsConfig": {
                        "backend-sciam-web-staging": {}
                    }
                }
            },
            "created": "Created container"
        }
    ],
    "_ansible_no_log": false
}
```

**Comment by rmanibus** [comment]
This workaround is working:
```
  tasks:
    - include_role:
        name: create_container
        [...]
    - include_role:
        name: create_container
        [...]
```
