### ISSUE TITLE
maven_repository: Maven Central now requires `https` and 501 on `http`

### ISSUE THREAD

**Issue by behemphi** [ansible/ansible#66609]
##### SUMMARY
As of 2019-01-15 Maven Central now requires `https`. 

https://support.sonatype.com/hc/en-us/articles/360041287334

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
* maven_repository

##### ANSIBLE VERSION

```paste below
It's in the build system. Full out not relevant.

ANSIBLE_VERSION=2.8.5
```

##### CONFIGURATION

```paste below
Not relevant
```

##### STEPS TO REPRODUCE

Attempt to get an artifact from Maven Central using `http` instead of `https`

```yaml
- name: Download latest agent from maven central
  maven_artifact:
    group_id: com.contrastsecurity
    artifact_id: contrast-agent
    version: "{{ contrast_agent_version }}"
    dest: "{{ contrast_agent_path }}/contrast/contrast.jar"
    owner: tomcat
    group: tomcat 
    mode: 0644
```

##### EXPECTED RESULTS

I expected the artifact to be copied to the AMI as it has done for years before this :-)

##### ACTUAL RESULTS

amazon-ebs: TASK [contrast : Download latest agent from maven central] *********************
    amazon-ebs: fatal: [teamserver-intuit-1579469195]: FAILED! => {"changed": false, "msg": "Failed to download artifact com.contrastsecurity:contrast-agent:3.6.9.11819 because of HTTP Error 501: HTTPS Requiredfor URL http://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/3.6.9.11819/contrast-agent-3.6.9.11819.jar"}
    amazon-ebs:
 
http://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/3.6.9.11819/contrast-agent-3.6.9.11819.jar

```paste below
Not sure what command you are referring to?
```
