### ISSUE TITLE
blockinfile module doesn't work correctly

### ISSUE THREAD

**Issue by yamada-k-ts** [ansible/ansible#66616]
##### SUMMARY

I used blockinfile module to change `/etc/bashrc` , it didn't work correctly.
It wrote block between the file, it should write end of the file.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible --version
ansible 2.9.3
  config file = /Users/user/.ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ansible
  executable location = /Users/user/.pyenv/versions/3.7.5/bin/ansible
  python version = 3.7.5 (default, Dec 12 2019, 16:57:32) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/Users/user/.ansible.cfg) = -o UserKnownHostsFile=/dev/null -F /Users/user/.ssh/config
DEFAULT_HOST_LIST(/Users/user/.ansible.cfg) = ['/Users/user/.ansible/ec2.py']
HOST_KEY_CHECKING(/Users/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Amazonlinux2

##### STEPS TO REPRODUCE

```yaml
- name: add PATH
  blockinfile:
    path: /etc/bashrc
    marker: ""
    marker_begin: ""
    marker_end: ""
    block: |
      # enable remi path
      export PATH=/opt/remi/php71/root/usr/bin:/opt/remi/php71/root/usr/sbin${PATH:+:${PATH}}
      export LD_LIBRARY_PATH=/opt/remi/php71/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
      export MANPATH=/opt/remi/php71/root/usr/share/man:${MANPATH}
```

##### EXPECTED RESULTS

```
    SHELL=/bin/bash
    # Only display echos from profile.d scripts if we are no login shell
    # and interactive - otherwise just process them to set envvars
    for i in /etc/profile.d/*.sh; do
        if [ -r "$i" ]; then
            if [ "$PS1" ]; then
                . "$i"
            else
                . "$i" >/dev/null
            fi
        fi
    done
    unset i
    unset -f pathmunge
fi
# vim:ts=4:sw=4

# enable remi path
export PATH=/opt/remi/php71/root/usr/bin:/opt/remi/php71/root/usr/sbin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/remi/php71/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/opt/remi/php71/root/usr/share/man:${MANPATH}
``` 

##### ACTUAL RESULTS

```paste below
    SHELL=/bin/bash
    # Only display echos from profile.d scripts if we are no login shell
    # and interactive - otherwise just process them to set envvars
    for i in /etc/profile.d/*.sh; do
        if [ -r "$i" ]; then
            if [ "$PS1" ]; then
                . "$i"
            else
                . "$i" >/dev/null
            fi
        fi
    done

# enable remi path
export PATH=/opt/remi/php71/root/usr/bin:/opt/remi/php71/root/usr/sbin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/remi/php71/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/opt/remi/php71/root/usr/share/man:${MANPATH}

    unset i
    unset -f pathmunge
fi
# vim:ts=4:sw=4
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yamada-k-ts** [comment]
I tried lineinfile module, it worked correctly.
```yaml
- name: add PATH
  lineinfile:
    path: /etc/bashrc
    line: "{{ item }}"
  with_items:
    - '# enable remi path'
    - export PATH=/opt/remi/php71/root/usr/bin:/opt/remi/php71/root/usr/sbin${PATH:+:${PATH}}
    - export LD_LIBRARY_PATH=/opt/remi/php71/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    - export MANPATH=/opt/remi/php71/root/usr/share/man:${MANPATH}
  tags: path
```
