### ISSUE TITLE
lvol: specify activation option

### ISSUE THREAD

**Issue by raspbeguy** [ansible/ansible#66623]
##### SUMMARY

I think it would be useful to be able to specify the activation option (exclusive, shared, local) for LVs in a shared VG.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

lvol

##### ADDITIONAL INFORMATION

When using a shared VG between multiple nodes, sometimes we need to define an activation option different from the default (exclusive). For now, only default activation option is supported by the module.

We could introduce a new parameter `activation_option` which could take `exclusive`, `shared` or `local` as values.

```yaml
- name: Activate a logical volume with shared lock
  lvol:
    vg: firefly
    lv: test
    active: true
    activation_option: shared
```
