### ISSUE TITLE
asynchronous multiple tasks result in error for last task: unable to connect to socket

### ISSUE THREAD

**Issue by chillancezen** [ansible/ansible#66651]
##### SUMMARY

I have `n` tasks which run asynchronously. 
the first `n - 1` tasks run well as expected, while the `n`th task doesn't. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

custom collection: chillancezen.fortimanager.
##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
#cat script_set.yml
- hosts: fortimanager01
  collections:
    - chillancezen.fortimanager
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'update a script'
        async: 7200
        poll: 0
        fmgr_dvmdb_script:
            url_params:
                adom: 'global'
            method: "set"
            params:
                - data:
                    - name: 'add_firewall_policy0'
                      desc: 'the demo script to set'
                      type: 'cli'
                      filter_ostype: 'unknown'
                      content: |
                                config firewall policy
                                    edit 1
                                        set name foopolicy
                                    next
                                end

    -   name: 'update a script'
        async: 7200
        poll: 0
        fmgr_dvmdb_script:
            url_params:
                adom: 'global'
            method: "set"
            params:
                - data:
                    - name: 'add_firewall_policy1'
                      desc: 'the demo script to set'
                      type: 'cli'
                      filter_ostype: 'unknown'
                      content: |
                                config firewall policy
                                    edit 1
                                        set name foopolicy
                                    next
                                end

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus0'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus1'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus2'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus3'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus4'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'
```

and then run:
```
#ansible-playbook -i hosts/hosts -vvv script_set.yml
ansible-playbook 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/DEV/fortimanager-ansible-generator/tests_collection/hosts/hosts as it did not pass its verify_file() method
script declined parsing /root/DEV/fortimanager-ansible-generator/tests_collection/hosts/hosts as it did not pass its verify_file() method
auto declined parsing /root/DEV/fortimanager-ansible-generator/tests_collection/hosts/hosts as it did not pass its verify_file() method
Parsed /root/DEV/fortimanager-ansible-generator/tests_collection/hosts/hosts inventory source with ini plugin

PLAYBOOK: script_set.yml ***************************************************************************************************************************************************************************************************************
1 plays in script_set.yml

PLAY [fortimanager01] ******************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:1
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812 `" && echo ansible-tmp-1579598600.3734312-150995100642812="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812 `" ) && sleep 0'
<fortimanager01> Attempting python interpreter discovery
<192.168.190.102> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.190.102> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/system/setup.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpcxf1pfud TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812/AnsiballZ_setup.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812/AnsiballZ_setup.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812/AnsiballZ_setup.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598600.3734312-150995100642812/ > /dev/null 2>&1 && sleep 0'
ok: [fortimanager01]
META: ran handlers

TASK [update a script] *****************************************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:11
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138 `" && echo ansible-tmp-1579598612.7386248-266863669217138="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_dvmdb_script.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmptw54m7cz TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/AnsiballZ_fmgr_dvmdb_script.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpo8_r1xog TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/AnsiballZ_fmgr_dvmdb_script.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/async_wrapper.py 942934829070 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598612.7386248-266863669217138/AnsiballZ_fmgr_dvmdb_script.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "942934829070.34021",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/942934829070.34021",
    "started": 1
}

TASK [update a script] *****************************************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:33
<192.168.190.102> ESTABLISH HTTP(S) CONNECTFOR USER: APIUser TO https://192.168.190.102:443
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261 `" && echo ansible-tmp-1579598613.3976197-87035240213261="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_dvmdb_script.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpzzdgi4l7 TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/AnsiballZ_fmgr_dvmdb_script.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmp8jxbc0sp TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/AnsiballZ_fmgr_dvmdb_script.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/async_wrapper.py 816784343805 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.3976197-87035240213261/AnsiballZ_fmgr_dvmdb_script.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "816784343805.34046",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/816784343805.34046",
    "started": 1
}

TASK [Update a seurity profile anti-virus entry] ***************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:53
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707 `" && echo ansible-tmp-1579598613.8783433-173189751126707="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmp7jwo4aiz TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/AnsiballZ_fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpbfs0q483 TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/AnsiballZ_fmgr_antivirus_profile.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/async_wrapper.py 396612771724 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598613.8783433-173189751126707/AnsiballZ_fmgr_antivirus_profile.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "396612771724.34071",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/396612771724.34071",
    "started": 1
}

TASK [Update a seurity profile anti-virus entry] ***************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:66
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821 `" && echo ansible-tmp-1579598614.4681923-5895183770821="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpx6yx_gut TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/AnsiballZ_fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpnyccy98d TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/AnsiballZ_fmgr_antivirus_profile.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/async_wrapper.py 105818011146 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.4681923-5895183770821/AnsiballZ_fmgr_antivirus_profile.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "105818011146.34096",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/105818011146.34096",
    "started": 1
}

TASK [Update a seurity profile anti-virus entry] ***************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:79
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229 `" && echo ansible-tmp-1579598614.9502635-67530759245229="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpdk4muulo TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/AnsiballZ_fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpmcneeh48 TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/AnsiballZ_fmgr_antivirus_profile.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/async_wrapper.py 796717214852 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598614.9502635-67530759245229/AnsiballZ_fmgr_antivirus_profile.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "796717214852.34121",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/796717214852.34121",
    "started": 1
}

TASK [Update a seurity profile anti-virus entry] ***************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:92
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048 `" && echo ansible-tmp-1579598615.4324021-195459198912048="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmp5g79zs5b TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/AnsiballZ_fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpxiurymru TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/AnsiballZ_fmgr_antivirus_profile.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/async_wrapper.py 199210182449 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.4324021-195459198912048/AnsiballZ_fmgr_antivirus_profile.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "199210182449.34146",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/199210182449.34146",
    "started": 1
}

TASK [Update a seurity profile anti-virus entry] ***************************************************************************************************************************************************************************************
task path: /root/DEV/fortimanager-ansible-generator/tests_collection/script_set.yml:105
<192.168.190.102> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.190.102> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041 `" && echo ansible-tmp-1579598615.9270391-142578253973041="` echo /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmpzsg46poh TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py
<192.168.190.102> PUT /root/.ansible/tmp/ansible-local-339218_i5u1ld/tmp7kve4cak TO /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/async_wrapper.py
<192.168.190.102> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/ /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/async_wrapper.py && sleep 0'
<192.168.190.102> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /usr/bin/python /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/async_wrapper.py 346825434174 7200 /root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py _ && sleep 0'
changed: [fortimanager01] => {
    "ansible_job_id": "346825434174.34171",
    "changed": true,
    "finished": 0,
    "results_file": "/root/.ansible_async/346825434174.34171",
    "started": 1
}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
fortimanager01             : ok=8    changed=7    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

##### EXPECTED RESULTS

```
{
"invocation":{
"module_args":{
"url_params":{
"adom":"root"
},
"params":[
{
"data":[
{
"comment":"A seurity profile anti virus entry updated by Ansible",
"inspection-mode":"flow-based",
"name":"secprof_anti_virus3"
}
]
}
],
"method":"update"
}
},
"meta":{
"status":{
"message":"Object does not exist",
"code":-3
},
"url":"/pm/config/adom/root/obj/antivirus/profile"
}
}
```

##### ACTUAL RESULTS

the last one  `/root/.ansible_async/346825434174.34171`. note all others except last one work really fine.

```paste below
{
"ansible_job_id":"346825434174.34171",
"cmd":"/root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py",
"failed":1,
"stderr":"Traceback (most recent call last):\n File \"/root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py\", line 102, in <module>\n File \"/root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py\", line 94, in _ansiballz_main\n File \"/root/.ansible/tmp/ansible-local-339218_i5u1ld/ansible-tmp-1579598615.9270391-142578253973041/AnsiballZ_fmgr_antivirus_profile.py\", line 40, in invoke_module\n File \"/usr/lib/python2.7/runpy.py\", line 192, in run_module\n fname, loader, pkg_name)\n File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n exec code in run_globals\n File \"/tmp/ansible_fmgr_antivirus_profile_payload_qUqHgx/ansible_fmgr_antivirus_profile_payload.zip/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py\", line 616, in <module>\n File \"/tmp/ansible_fmgr_antivirus_profile_payload_qUqHgx/ansible_fmgr_antivirus_profile_payload.zip/ansible_collections/chillancezen/fortimanager/plugins/modules/fmgr_antivirus_profile.py\", line 607, in main\n File \"/tmp/ansible_fmgr_antivirus_profile_payload_qUqHgx/ansible_fmgr_antivirus_profile_payload.zip/ansible/module_utils/connection.py\", line 179, in __rpc__\n File \"/tmp/ansible_fmgr_antivirus_profile_payload_qUqHgx/ansible_fmgr_antivirus_profile_payload.zip/ansible/module_utils/connection.py\", line 150, in _exec_jsonrpc\n File \"/tmp/ansible_fmgr_antivirus_profile_payload_qUqHgx/ansible_fmgr_antivirus_profile_payload.zip/ansible/module_utils/connection.py\", line 199, in send\nansible.module_utils.connection.ConnectionError: unable to connect to socket\n",
"msg":"Traceback (most recent call last):\n File \"/tmp/ansible_async_wrapper_payload_OBhy46/ansible_async_wrapper_payload.zip/ansible/modules/utilities/logic/async_wrapper.py\", line 159, in _run_module\n File \"/tmp/ansible_async_wrapper_payload_OBhy46/ansible_async_wrapper_payload.zip/ansible/modules/utilities/logic/async_wrapper.py\", line 93, in _filter_non_json_lines\nValueError: No start of json char found\n",
"data":""
}
```

cc @frankshen01
