### ISSUE TITLE
Reference to variable in variable is not resolved in second and subsquent loop iterations

### ISSUE THREAD

**Issue by liutaurasa** [ansible/ansible#66659]
##### SUMMARY
My goal is to run through all the defined groups and compile a list of packages. If "web" group packages list is ['apache'] and "mta" group has a packages variable set to ['postfix'] then host in both of those groups should have _packages variable set to ['apache', 'postfix'].
It works in most cases, but doesn't when the list of packages in group variables is actualy reference to other variable. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact (in my case)

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /home/liutauras/.ansible/setup-kolab-groups/ansible.cfg
  configured module search path = ['/home/liutauras/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 22:52:49) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```
DEFAULT_BECOME(__replaced__/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(__replaced__/ansible.cfg) = False
DEFAULT_BECOME_METHOD(__replaced__/ansible.cfg) = sudo
DEFAULT_BECOME_USER(__replaced__/ansible.cfg) = root
DEFAULT_HOST_LIST(__replaced__/ansible.cfg) = ['__replaced__/inventory']
DEFAULT_JINJA2_EXTENSIONS(__replaced__/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_PRIVATE_KEY_FILE(__replaced__/ansible.cfg) = /home/.../.ssh/key
DEFAULT_REMOTE_USER(__replaced__/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(__replaced__/ansible.cfg) = ['__replaced__/roles', '/home/.../.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEPRECATION_WARNINGS(__replaced__/ansible.cfg) = False
HOST_KEY_CHECKING(__replaced__/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Hosts are CentOS 7, Management machine - Fedora 31

##### STEPS TO REPRODUCE
Inventory:
```
[ldap]
db.kvm.tinklas

[sql]
db.kvm.tinklas
```
Group variables:
group_vars/sql.yml
```
---
sql_packages:
  mariadb:
    CentOS:
      - mariadb-server
      - mysql-client

sql_role:
  packages: "{{ sql_packages[sql_type][ansible_distribution] }}"
```
group_vars/ldap.yml
```
---
ldap_packages:
  ds389:
    CentOS:
      - 389-ds-base
      - 389-ds-base-libs

ldap_role:
  packages: "{{ ldap_packages[ldap_type][ansible_distribution] }}"
```

```yaml
---
# Run preparations
- name: Initial setup
  hosts: db.kvm.tinklas
  vars:
    sql_type: mariadb
    ldap_type: ds389
  pre_tasks:
    - name: "packages to install"
      set_fact:
        _packages_to_install: "{{ _packages_to_install | default([]) + hostvars[inventory_hostname][item + '_role']['packages'] | default([]) }}"
      loop: "{{ group_names | difference(['all', 'ungrouped']) }}"
    - debug:
        var: _packages_to_install
```

##### EXPECTED RESULTS

I expect the list is joined list of packages defined in group_vars/sql.yml and group_vars/ldap.yml
```
TASK [debug] *************************************************************************************************************************************************************************
ok: [db.kvm.tinklas] => {
    "_packages_to_install": [
          "389-ds-base",
          "389-ds-base-libs",
          "mariadb-server",
          "mysql-client"
        ],
```

##### ACTUAL RESULTS
The play fails. The fail is:
```
PLAY [Initial setup] *****************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [db.kvm.tinklas]

TASK [packages to install] ***********************************************************************************************************************************************************
fatal: [db.kvm.tinklas]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ _packages_to_install | default([]) + hostvars[inventory_hostname][item + '_role']['packages'] | default([]) }}): can only concatenate list (not \"AnsibleUnicode\") to list"}

PLAY RECAP ***************************************************************************************************************************************************************************
db.kvm.tinklas             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
It took me a while to understand what exactly is failing. If I modify my play's set_fact command to look:
```
      set_fact:
        _packages_to_install: "{{ _packages_to_install | default([]) + [hostvars[inventory_hostname][item + '_role']['packages'] | default([])] }}"
```
In this modification the reference to array's "hostvars[..]..[..]" element is put in between square brakets []. With that change I'd expect the debug output was a list of lists of packages. But I got the debug var output:
```
TASK [debug] *************************************************************************************************************************************************************************
ok: [db.kvm.tinklas] => {
    "_packages_to_install": [
        [
            "389-ds-base",
            "389-ds-base-libs",
        ],
        "{{ sql_packages[sql_type][ansible_distribution] }}"
    ]
}
```
So it looks like on first loop iteration "hostvars[..]..[..]" is resolved correctly, however second iteration does not resolve a variable. If I change my group_vars and instead of referencing to variable I put actual list of packages - everything works.
