### ISSUE TITLE
loops over undefined items using conditions

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#66657]
##### SUMMARY

`loop` tasks are run regardless of a given condition. In this case, looping over an undefined dict cannot be skipped using simple `when:` conditions. Neither using conditions in an outer `block:` or `include:` helps here.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core
task_executor.py maybe

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/phil/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 22:52:49) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

##### CONFIGURATION

```paste below
n/a
```

##### STEPS TO REPRODUCE

```yaml
# file: main.yml
---
- hosts: localhost
  gather_facts: no
  tasks:
    # this won't work because 'when' runs for each iteration of the loop
    - debug: msg='{{item}}'
      loop: '{{nothing|dict2items}}'
      ignore_errors: true
      when: nothing is defined

    # 'when' should skip the whole block but 'nothing' still gets evaluated
    - block:
      - debug: msg='{{item}}'
        loop: '{{nothing|dict2items}}'
        ignore_errors: true
      when: nothing is defined

    # this doesn't work, even though ansible should consider this a dynamic include
    - include: nothingloop.yml
      ignore_errors: true
      when: nothing is defined

    # this doesn't fail but the task runs nevertheless
    - debug: msg='{{item}}'
      loop: '{{nothing|d({})|dict2items}}'
      ignore_errors: true
      when: nothing is defined

    # same here
    - block:
      - debug: msg='{{item}}'
        loop: '{{nothing|d({})|dict2items}}'
        ignore_errors: true
      when: nothing is defined

   # this works as expected: 'nothingloop.yml' is not run at all. But this requires an additional playbook file.
    - include_tasks: nothingloop.yml
      when: nothing is defined
```
```yaml
# file: nothingloop.yml
---
- debug: msg='{{item}}'
  loop: '{{nothing|dict2items}}'
```

##### EXPECTED RESULTS

```
PLAY [localhost] ******************************************************************

TASK [debug] **********************************************************************
skipping: [localhost]

TASK [debug] **********************************************************************
skipping: [localhost]

TASK [debug] **********************************************************************
skipping: [localhost]

TASK [debug] **********************************************************************
skipping: [localhost]

TASK [debug] **********************************************************************
skipping: [localhost]

TASK [include_tasks] **************************************************************
skipping: [localhost]

PLAY RECAP ************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   

```

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ******************************************************************

TASK [debug] **********************************************************************
fatal: [localhost]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
...ignoring

TASK [debug] **********************************************************************
fatal: [localhost]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
...ignoring

TASK [debug] **********************************************************************
fatal: [localhost]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
...ignoring

TASK [debug] **********************************************************************

TASK [debug] **********************************************************************

TASK [include_tasks] **************************************************************
skipping: [localhost]

PLAY RECAP ************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=3   

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is expected, and documented at https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html

> When combining Conditionals with a loop, the when: statement is processed separately for each item. See The When Statement for examples

As such, you must ensure that your loop can always be evaluated. This can be achieved through the use of the `|default` filter:

```
    - debug: msg='{{item}}'
      loop: '{{nothing|default({})|dict2items}}'
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by philfry** [comment]
Sorry, but please take a look at the playbook before closing the bug report. I already mentioned in the first task that `when:` is evaluated for each iteration. The point is that even when putting the loop in an additional `block:` and using a condition on that block the loop runs/gets evaluated. In my understanding the block should never be entered on a failed condition. Your example
```yaml
loop: '{{nothing|default({})|dict2items}}'
```
would not unnecessarily run if the outer condition worked as expected.
I'd like to understand the root cause of this behaviour. How does `block:` work – does this
```yaml
- block:
  - task_foo:
  - task_bar:
    when: this
  - task_baz:
    when: that
    loop: '{{something}}'
  when: something is defined
```
expand to
```yaml
- task_foo:
  when: something is defined
- task_bar:
  when:
    - something is defined
    - this
- task_baz:
  when:
    - something is defined
    - that
  loop: '{{something}}'
```
internally?
