### ISSUE TITLE
VMware: vmware_guest not waiting for ip

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#66662]
##### SUMMARY
Im using ansible 2.9.2 and i have this playbook that is runing on an exsisting machine, 
this machine has no NIC and this playbook assianing it a new NIC and i want it to wait until 
it gets an IP.

myabe this featuer isnt working because im not creating new machine but adding a nic? 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
ansible 2.9.2 

##### OS / ENVIRONMENT
Ubuntu 18

##### STEPS TO REPRODUCE
Get a vm powerwd on with no nic and run this playbook to add a nic
Playbook :
```
---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/env python3
  vars_files:
            - vars.yml
  gather_facts: no
  tasks:
    - name:  Add new nic
      vmware_guest:
        datacenter: "{{ datacenter }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user  }}"
        password: "{{ vcenter_pass }}"
        folder:  "{{ folder  }}"
        cluster: "{{ cluster }}"
        validate_certs: no
        name: "{{ name }}"
        networks:
        - label: "Network adapter 1"
          device_type: e1000e
          state: new
          connected: True
          name: "{{ nic }}"
        wait_for_ip_address: yes
      register: output
    - debug:
            msg: "{{ output.instance | json_query('hw_eth0.ipaddresses') }}"

```

Playbook  works fine it just doesnt wait for the ip
nic is DHCP and i get ip after15 seconds but i want the 
`            msg: "{{ output.instance | json_query('hw_eth0.ipaddresses') }}"
`
To return ip address the machine got.
Thanks

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_guest.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @lparkes @nerzhul @pdellaert @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@batchenr, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@batchenr Thanks for reporting this issue. When you specify `present` as `state` in `vmware_guest` will only reconfigure the existing VM with newly provided details and will not touch `powerstate` of the VM. 

In order to leverage the effect of `wait_for_ip_address`, you may want to power on the VM like in an additional task like - 


```yaml
  - name: Add a NIC in existing VM
    vmware_guest:
      validate_certs: False
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: "{{ dc1 }}"
      state: present
      cluster: Asia-Cluster1
      name: debian_10
      folder: /Asia-Datacenter1/vm/
      networks:
        - name: VM Network
          ip: 10.10.10.100
          netmask: 255.255.255.0
          device_type: vmxnet3

  - name: Poweron existing VM
    vmware_guest:
      validate_certs: False
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: "{{ dc1 }}"
      state: poweredon
      cluster: Asia-Cluster1
      name: debian_10
      folder: /Asia-Datacenter1/vm/
      wait_for_ip_address: yes
```

Here, `debian_10` is VM with no NIC. The first task will add the NIC and the second task will power on the VM and wait for IP address to get populated.

Let me know if it makes sense to you. Thanks.

needs_info
