### ISSUE TITLE
user.py Busybox support broke modifying users

### ISSUE THREAD

**Issue by HRio** [ansible/ansible#66679]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
<!--- Explain the problem briefly below --> 
The commit bf3e397ea7922e8bd8b8ffbc05d1aede0317d119 (PR #45507) that introduced Busybox support and changed so that class is always used on Alpine Linux, broke modifying existing user accounts.

Hence for instance a shell can not be changed for an existing user account.

Example
```yaml
 - name: add users                                                                                                                                                                                                                                  
    user:
      name: "userA"
      shell: "/bin/zsh"
      password: '*'
      update_password: on_create
    ....
```
and then changing shell to `/bin/bash`. Will only change the shell on for instance Debian systems but on Alpine systems the shell will not be changed.

Looking at the code it seems the Busybox class `modify_user` implementation only handles groups memberships and passwords and not things like shell, comment etc.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
lib/ansible/modules/system/user.py

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
2.8.8

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->

Alpine Linux


##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
 - name: add users                                                                                                                                                                                                                                  
    user:
      name: "userA"
      shell: "/bin/zsh"
      password: '*'
      update_password: on_create
    ....
```

Changing the shell for the user above works until upgrading to Ansible v2.8 or later.

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->

See above

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

See above

<!--- Paste verbatim command output between quotes -->
```paste below

```
