### ISSUE TITLE
Idempotency fails with ipv6 if input case differs in *_l3_interfaces module 

### ISSUE THREAD

**Issue by justjais** [ansible/ansible#66678]
##### SUMMARY

Idempotency fails with ipv6 if the input case differs in *_l3_interfaces module, meaning if IPV6 address is given in the upper case and if the device actually configures in lower case, play idempotency fails as it always takes it as different input.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l3_interfaces
eos_l3_interfaces
nxos_l3_interfaces

I believe in other supported platform l3 interfaces module too, but didn't tested 
##### ANSIBLE VERSION

```paste below
2.9, devel
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macos

##### STEPS TO REPRODUCE

play:

```yaml
- ios_l3_interfaces:
      config:
        - name: GigabitEthernet0/2
          ipv6:
            - address: 2001:DB8::2/32
- nxos_l3_interfaces:
      config:
        - name: Ethernet2/2
          ipv6:
            - address: 2001:DB8::2/32
- eos_l3_interfaces:
      config:
        - name: Ethernet2
          ipv6:
            - address: 2001:DB8::2/32
```

##### EXPECTED RESULTS

Play should configure the IPV6 address and play should be idempotent in the second run.

##### ACTUAL RESULTS

Play configures the IPV6 address as expected but the play is not idempotent in the second run, and will continue to show as changed every time the play runs.

```paste below

```
