### ISSUE TITLE
VMware: Unable to connect to vCenter or ESXi API (_ssl.c:877)

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#66681]
##### SUMMARY

I have a playbook that connects to vCenter which I can execute from my local machine without any problems. However, running the same playbook from AWX gives me this error:

Unable to connect to vCenter or ESXi API at virtualcenter.com on TCP/443: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:877)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_datastore_info

##### ANSIBLE VERSION

```paste below
2.9.2
```

##### CONFIGURATION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### STEPS TO REPRODUCE

```yaml
- name: Export facts from datastore
  vmware_datastore_info:
    hostname: "{{ hostname }}"
    username: '{{ domain_user }}'
    password: "{{domain_password}}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
  delegate_to: localhost
  register: datastore_facts
```

##### EXPECTED RESULTS

I expect the module to work the same way as on my own machine with ansible 2.9.2.

##### ACTUAL RESULTS

```paste below
{
    "msg": "Unable to connect to vCenter or ESXi API at virtualcenter.com on TCP/443: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:877)",
    "exception": "  File \"/tmp/ansible_vmware_datastore_info_payload_ek_qeoe7/ansible_vmware_datastore_info_payload.zip/ansible/module_utils/vmware.py\", line 562, in connect_to_api\n    service_instance = connect.SmartConnect(**connect_args)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/pyVim/connect.py\", line 847, in SmartConnect\n    sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/pyVim/connect.py\", line 726, in __FindSupportedVersion\n    httpProxyPort)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/pyVim/connect.py\", line 643, in __GetServiceVersionDescription\n    httpProxyHost, httpProxyPort)\n  File \"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/pyVim/connect.py\", line 608, in __GetElementTree\n    conn.request(\"GET\", path)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1239, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1285, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1234, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib64/python3.6/http/client.py\", line 1026, in _send_output\n    self.send(msg)\n  File \"/usr/lib64/python3.6/http/client.py\", line 964, in send\n    self.connect()\n  File \"/usr/lib64/python3.6/http/client.py\", line 1400, in connect\n    server_hostname=server_hostname)\n  File \"/usr/lib64/python3.6/ssl.py\", line 365, in wrap_socket\n    _context=self, _session=session)\n  File \"/usr/lib64/python3.6/ssl.py\", line 773, in __init__\n    self.do_handshake()\n  File \"/usr/lib64/python3.6/ssl.py\", line 1033, in do_handshake\n    self._sslobj.do_handshake()\n  File \"/usr/lib64/python3.6/ssl.py\", line 645, in do_handshake\n    self._sslobj.do_handshake()\n",
    "invocation": {
        "module_args": {
            "hostname": "virtualcenter.com",
            "username": "buildautomator",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "datacenter": "datacenter",
            "validate_certs": false,
            "port": 443,
            "gather_nfs_mount_info": false,
            "gather_vmfs_mount_info": false,
            "proxy_host": null,
            "proxy_port": null,
            "name": null,
            "cluster": null
        }
    },
    "_ansible_no_log": false,
    "changed": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_datastore_info.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_datastore_info.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @garbled1 @goneri @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@nicolaibaralmueller, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@nicolaibaralmueller Thanks for reporting this issue. Can you please provide steps to reproduce this issue? Thanks.

needs_info

**Comment by nicolaibaralmueller** [comment]
> @nicolaibaralmueller Thanks for reporting this issue. Can you please provide steps to reproduce this issue? Thanks.
> 
> needs_info

Using module vmware_datastore_info with ansible 2.9.2 in awx 9.1.0.

**Comment by nicolaibaralmueller** [comment]
I found out more information about the error.

Only unable to connect to vSphere 5.5.0 from Centos 8 with Python 3 intepreter "/usr/libexec/platform-python" in a virtual environment (AWX).

```
- name: Create new VMware Virtual Machine
  vmware_guest:
    hostname: "{{ hostname }}"
    esxi_hostname: "{{ esxi_hostname | default('minasanor.localdomain') }}"
    username: '{{ domain_user }}'
    password: "{{ domain_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_destination | default('/Test-Dev/QA') }}"      
    state: poweredon
    disk:
    - size_gb: '{{ disk_size | default(40) }}'
      type: thin
      autoselect_datastore: True
    hardware:
      memory_mb: "{{ memory | default(4096) }}"
      num_cpus: "{{ cores | default(2) }}"
      num_cpu_cores_per_socket: "{{ cores | default(2) }}"
    networks:
    - name: LAN
      domain: "{{ domain }}"
      dns_servers:
      -  "{{ dns1 }}"
      -  "{{ dns2 }}"
      type: static
      ip: "{{ new_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"
    customization:
      autologon: True
      hostname: "{{ vm_name }}"
      domain: "{{ domain }}"
      fullname: "{{ local_user }}"
      password: "{{ local_password }}"
      domainadmin: "{{ domain_user }}"
      domainadminpassword: "{{ domain_password }}"
      joindomain: "{{ domain }}"
      orgname: Solteq DK
      timezone: 105
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\StartupScripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      - netsh advfirewall set allprofiles state off
    wait_for_customization: yes
    template: "{{ template }}"
    wait_for_ip_address: yes
```

```
Unable to connect to vCenter or ESXi API at virtualcenter.localdomain on TCP/443: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:897)
```

The error seems to be related to pyvmomi module itself. 

I am using ansible module vmware_guest with ansible > 2.9.X

Digging around and it might have something to do with TLS but not sure.

When using my local environment with Ubuntu 19.10 no errors occur!

So this is a general issue with AWX and pyvmomi.
