### ISSUE TITLE
cloudflare_dns: ignoring 'proxied: yes' parameter

### ISSUE THREAD

**Issue by spankme** [ansible/ansible#66687]
##### SUMMARY
When creating DNS entries using the cloudflare_dns module with Ansible 2.9.3 , the bool type parameter `proxied` used as `proxied: yes` (also tested with `proxied: "yes"`, `proxied: true`, `proxied: "true"`) is ignored and the resulting entries have proxying disabled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

clourflare_dns

##### ANSIBLE VERSION

```ansible 2.9.3
  config file = None
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.3/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Dec 27 2019, 18:06:00) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```ANSIBLE_PIPELINING(/Users/myuser/Documents/devel/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/myuser/Documents/devel/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o Prefer
ANSIBLE_SSH_CONTROL_PATH(/Users/myuser/Documents/devel/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/Users/myuser/Documents/devel/ansible/ansible.cfg) = 20
DEFAULT_INTERNAL_POLL_INTERVAL(/Users/myuser/Documents/devel/ansible/ansible.cfg) = 0.001
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = ~/.vault_pass
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Use latest Ansible 2.9.3 with cloudflare_dns module to create DNS entries in Cloudflare DNS service:

```yaml
cloudflare_dns:
  - {
      zone: example.com,
      type: A,
      value: 127.0.0.1,
      record: example.com,
      solo: yes,
      proxied: yes,
    }
```

##### EXPECTED RESULTS

Resulting entry in Cloudflare DNS to have 'Proxied' option turned ON, instead of it being 'DNS only'.

##### ACTUAL RESULTS

Resulting entry in Cloudflare DNS 'Proxied' option is 'DNS only'.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/cloudflare_dns.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/cloudflare_dns.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @andreaso @mgruener
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by spankme** [comment]
Possibly related to https://github.com/ansible/ansible/issues/35190

**Comment by spankme** [comment]
I've actually tested it with the existing/new record scenario and the result is the same, that is Proxied is always 'DNS only' instead of 'ON'.

**Comment by andreaso** [comment]
Not able to reproduce. For me the proxied toggle works as expected.

I assume that the `value` you are actually using is a regular public ip address, rather than _127.0.0.1_, an RFC1918 address or so?

**Comment by spankme** [comment]
@andreaso You are correct, 127.0.0.1 was just an example. Is there any more information I could provide to help debugging this issue? Any chance you'd share your playbook where it works, so I could compare against mine? Have you checked in the Cloudflare web console that it actually changes the 'Proxied' switch - because it doesn't throw any errors for me, it's all executing well, but in effect the `proxied: yes` does nothing.

**Comment by andreaso** [comment]
Here is the playbook for this issue. The only modification I've done to the paste is to mask the account email and the account token.

```yaml
---

- hosts: localhost
  tasks:
    - name: Set a test record
      cloudflare_dns:
        account_email: ***masked***
        account_api_token: ***masked***
        zone: initctl.dev
        record: initctl.dev
        type: A
        value: 198.51.100.47
        proxied: yes
        solo: yes
```

Yes, I've verified the the proxied status both using the web console and by doing an actual DNS lookup.

I'll get back to you with follow-up questions once I've spent a bit more time looking at the issue.
