### ISSUE TITLE
vault hashi_vault lookup plugin and set_fact is not skipped properly

### ISSUE THREAD

**Issue by jdelvecchio** [ansible/ansible#66685]
##### SUMMARY
Skipped set_fact are still being run despite task is marked as 'skipped' and the fact has an odd value, bug occurs only when using the hashi_vault lookup plugin.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact
hashi_vault lookup plugin

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/julien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION
```
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Debian 9

##### STEPS TO REPRODUCE
Create those 3 files :

`main.yml` :
```yaml
- name: Run me
  import_playbook: runme.yml
  when: true
  tags:
    - always
    - auth

- name: Skip me
  import_playbook: skipme.yml
  when: false
  tags:
    - always
    - auth

- name: Fact print
  hosts: localhost
  connection: local
  tasks:
    - name: Print vmware_prometheus_vcenter_password (value should be what is stored in vault)
      debug:
        var: vmware_prometheus_vcenter_password
```

`runme.yml` (play that will be run) :
```yaml
- name: Run me
  hosts: all
  gather_facts: no
  run_once: yes
  vars:
    #Vault url
    vault_url: "https://yourvaulturl"
  vars_prompt:
    - name: "vault_username"
      prompt: "Enter your Vault username"
      private: no
    - name: "vault_password"
      prompt: "Enter your Vault password"
      private: yes
  tasks:
    - name: Query Vault to retrieve something
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/vmware_prometheus:password auth_method=ldap mount_point=ldap username={{vault_username}} password={{vault_password}} url={{vault_url}}')}}"
      register: vmware_prometheus_vcenter_password

    - name: Set fact - should be ran
      set_fact:
        vmware_prometheus_vcenter_password: "{{ vmware_prometheus_vcenter_password }}"
```

`skipme.yml` (same play as runme but will be skipped) :
```yaml
- name: Skip me
  hosts: all
  gather_facts: no
  run_once: yes
  vars:
    #Vault url
    vault_url: "https://yourvaulturl"
  vars_prompt:
    - name: "vault_username"
      prompt: "Enter your Vault username"
      private: no
    - name: "vault_password"
      prompt: "Enter your Vault password"
      private: yes
  tasks:
    - name: Query Vault to retrieve something
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/vcenter/vmware_prometheus:password auth_method=ldap mount_point=ldap username={{vault_username}} password={{vault_password}} url={{vault_url}}')}}"
      register: vmware_prometheus_vcenter_password

    - name: Set fact - should be skipped
      set_fact:
        vmware_prometheus_vcenter_password: "{{ vmware_prometheus_vcenter_password }}"
```

Execute it : 
`ansible-playbook main.yml -v -i localhost,`

##### EXPECTED RESULTS
The fact vmware_prometheus_vcenter_password should print the value stored in vault, like this :
```
TASK [Print vmware_prometheus_vcenter_password (value should be what is stored in vault)] *************************************************************************************************************************
ok: [localhost] => 
  vmware_prometheus_vcenter_password:
    msg: valuestoredinvault
```

##### ACTUAL RESULTS
The fact vmware_prometheus_vcenter_password shows a weird value corresponding to the skipped fact
```
TASK [Print vmware_prometheus_vcenter_password (value should be what is stored in vault)] *************************************************************************************************************************
ok: [localhost] => 
  vmware_prometheus_vcenter_password:
    changed: false
    skip_reason: Conditional result was False
    skipped: true
```
