### ISSUE TITLE
Bug Report: with_fileglob no skipping message when condition is not satisfied

### ISSUE THREAD

**Issue by craph** [ansible/ansible#66698]
##### SUMMARY

No "skipping" message shown when the conditionnal test is true when using `with_fileglob` in task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

component `copy` with `with_fileglob` in task

##### ANSIBLE VERSION

```bash
# ansible --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
no changes
```

##### OS / ENVIRONMENT

CentOS 7.7

##### STEPS TO REPRODUCE

Create a task like that.
And have a variable called `installation_mode` set to the default value to `FIRST`

When you launch a playbook to run your task you will not see the message `skipping` when installation_mode is equal to `FIRST`. It's blank...

```yaml
- name: Copy all data files
  copy:
    src: "{{ item }}"
    dest: "/opt/myfolder/data"
    group: "{{ my_group}}"
    owner: "{{ my_user }}"
  with_fileglob:
    - "{{ mypath}}/File*.txt"
  when: installation_mode == "UPGRADE"
  tags: copy_files
```

##### EXPECTED RESULTS

If the condition is not true, the Ansible output should be : `skipping` not empty or blank

##### ACTUAL RESULTS

```paste below
TASK [role-copy : Copy all data files] **********************************************************************************************************************


```
