### ISSUE TITLE
Handler from dependency role only executed for one host

### ISSUE THREAD

**Issue by lucc** [ansible/ansible#66694]
##### SUMMARY
The handler from a dependency role is not executed for all hosts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
handler

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/luc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/luc/ansible/lib/ansible
  executable location = /home/luc/ansible/bin/ansible
  python version = 3.8.1 (default, Jan  8 2020, 23:09:20) [GCC 9.2.0]
```
running from git checkout, `git describe` says `stable-2.9-branchpoint-1793-gec371eb227`.

##### CONFIGURATION
(no change/empty output)
##### OS / ENVIRONMENT
Arch Linux

##### STEPS TO REPRODUCE
- I have two roles that depend one one common base role
- the base role has a handler
- the roles are assigned to different hosts with `when: ...`

I am using two virtual machines provided by vagrant for this bug report but have observed the same problem on real machines in production.  You can use this Vagrant file and inventory to easy reproduction of the bug (it should reproduce with any other machine as well):

Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
  ["box1", "box2"].each do |name|
    config.vm.define name do |config|
      config.vm.box = "centos/7"
    end
  end
end
```
inventory:
```ini
box1 ansible_host=127.0.0.1 ansible_port=2200 ansible_private_key_file=.vagrant/machines/box1/virtualbox/private_key
box2 ansible_host=127.0.0.1 ansible_port=2201 ansible_private_key_file=.vagrant/machines/box2/virtualbox/private_key
```

```yaml
--- # playbook.yml
- hosts: all
  user: vagrant
  roles:
    - { role: role1, when: inventory_hostname == 'box1' }
    - { role: role2, when: inventory_hostname == 'box2' }
--- # roles/base/handlers/main.yml
- name: base handler
  command: echo base handler
--- # roles/base/tasks/main.yml
- command: /bin/true
--- # roles/role1/meta/main.yml
dependencies: [base]
--- # roles/role1/tasks/main.yml
- command: /bin/true
  notify: base handler
--- # roles/role2/meta/main.yml
dependencies: [base]
--- # roles/role2/tasks/main.yml
- command: /bin/true
  notify: base handler
```
##### EXPECTED RESULTS
The base handler should run on both machines.

##### ACTUAL RESULTS
It only runs on one machine:
```
[luc@luc test]$ ansible-playbook -i inventory --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" playbook.yml

PLAY [all] *******************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************
ok: [box1]
ok: [box2]

TASK [base : command] ********************************************************************************************
skipping: [box2]
changed: [box1]

TASK [role1 : command] *******************************************************************************************
skipping: [box2]
changed: [box1]

TASK [base : command] ********************************************************************************************
changed: [box2]

TASK [role2 : command] *******************************************************************************************
skipping: [box1]
changed: [box2]

RUNNING HANDLER [base : base handler] ****************************************************************************
skipping: [box2]
changed: [box1]

PLAY RECAP *******************************************************************************************************
box1                       : ok=4    changed=3    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
box2                       : ok=3    changed=2    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
```
