### ISSUE TITLE
Handlers are not activated with meta: flush_handlers

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#6670]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.6 (devel)
##### Environment:

Debian
##### Summary:

`- meta: flush_handlers` does not activate pending handlers during playbook run. Bisect shows https://github.com/ansible/ansible/commit/605156c9047a07e02cfaa3c36c3a063ff17af540 as a commit that introduced the bug.
##### Steps To Reproduce:

```

---
- hosts: localhost
  tasks:
    - command: touch /tmp/handler_test
      notify:
        - Run notifier
    - meta: flush_handlers
    - command: rm /tmp/handler_test
  handlers:
    - name: Run notifier
      command: touch /tmp/notifier
```
##### Expected Results:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [command touch /tmp/handler_test] *************************************** 
changed: [localhost]

NOTIFIED: [Run notifier] ****************************************************** 
changed: [localhost]

TASK: [command rm /tmp/handler_test] ****************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=3    unreachable=0    failed=0   
```
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [command touch /tmp/handler_test] *************************************** 
changed: [localhost]

TASK: [command rm /tmp/handler_test] ****************************************** 
changed: [localhost]

NOTIFIED: [Run notifier] ****************************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=3    unreachable=0    failed=0   
```
