### ISSUE TITLE
F5 module bigip_command not able to run bash commands?

### ISSUE THREAD

**Issue by janrv** [ansible/ansible#66712]
##### SUMMARY

Hello

component name: bigip_command

I am implementing the following module in my playbook:

https://docs.ansible.com/ansible/latest/modules/bigip_command_module.html

task:
```yaml
- name: Check certificate
      bigip_command: 
        provider: "{{provider}}"
        commands: 
          - ls        
      register: outputcmd
      delegate_to: localhost
```
In order to find a certificate on the LTM I need to send some bash commands, however this module doesn't seem to support bash commands although the title says it does?

Running the above task and debugging the output gives the following:

```
TASK [debug] *******************************************************************

ok: [127.0.0.1] => {
    "msg": {
        "changed": false, 
        "executed_commands": [
            "tmsh -c \\\\\\"ls\\\\\\""
        ], 
        "failed": false, 
        "stdout": [
            "Syntax Error: unexpected argument \\"ls\\""
        ], 
        "stdout_lines": [
            [
                "Syntax Error: unexpected argument \\"ls\\""
            ]
        ], 
        "warnings": [
            "Using \\"write\\" commands is not idempotent. You should use a module that is specifically made for that. If such a module does not exist, then please file a bug. The command in question is \\"ls...\\""
        ]
    }
}
```
As you can see this command is being executed in tmsh.
Am I doing something wrong or does this module really not support bash?

##### COMPONENT NAME

lib/ansible/modules/network/f5/bigip_command.py

##### ANSIBLE VERSION

N/A
