### ISSUE TITLE
ec2_asg: Add MaxInstanceLifetime support

### ISSUE THREAD

**Issue by anryko** [ansible/ansible#66716]
##### SUMMARY

Add support for `MaxInstanceLifetime` option to AWS ec2_asg module.
AWS feature introduction link: https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ec2-auto-scaling-supports-max-instance-lifetime/

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ec2_asg

##### ADDITIONAL INFORMATION

Usage example:

```yaml
- ec2_asg:
    name: myasg
    region: us-east-1
    launch_config_name: my_new_lc
    min_size: 1
    max_size: 5
    desired_capacity: 3
    max_instance_lifetime: 604800  # seconds
```
