### ISSUE TITLE
Include_Inventory modul

### ISSUE THREAD

**Issue by Syntax3rror404** [ansible/ansible#66710]
##### SUMMARY
A way, to include a dynamic inventory file to a static inventory. 

##### ISSUE TYPE
Feature request

##### COMPONENT NAME
include_inventory

##### ADDITIONAL INFORMATION
-The command `include_inventory: /your/path/inventory_dynamic.yml` inside the inventory_static.yml includes the stuff from the inventory_dynamic to the inventory_static.

With this solution you can switch the dynamic where is created by other playbooks.

Example of use: `ansible-playbook -i inventory_static.yml playbook_example.yml`
Loads now automatic the stuff from the inventory_dynamic and inventory_static.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
I'm not sure what this feature is trying to accomplish.

> With this solution you can switch the dynamic where is created by other playbooks.

Is the playbook spinning up hosts that you're going to locate with the included dynamic inventory? If that's the case, you may want to take a look at the meta task `refresh_inventory`.

For example, if your playbook spins up AWS instances, you'd create an aws_ec2 config file:
```
# filename: dev_aws_ec2.yml
plugin: aws_ec2
```
Run your playbook with -i dev_aws_ec2.yml. No instances may be found initially, but once you've provisioned them use a `- meta: refresh_inventory` task to pull them into your inventory.
```
- name: provisioning play
  hosts: localhost
  tasks:
  - name: ensure EC2 instances are running
    ...
  - meta: refresh_inventory

- name: use new hosts
  # the aws_ec2 plugin automatically creates the group aws_ec2, but you can use the `constructed` inventory plugin to create a group based on your own criteria
  hosts: aws_ec2
  ...
```

needs_info
