### ISSUE TITLE
add_host skipping added hosts in subsequent play

### ISSUE THREAD

**Issue by gforster** [ansible/ansible#66728]
##### SUMMARY

using `add_host` during provisioning of servers. Verified that new hosts are added to correct group. In the next play, which utilizes only the new group just added, getting "skipping: no hosts matched"
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

add_host
##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL7

##### STEPS TO REPRODUCE

```yaml
#####################################################
# PLAY 1 - machine provisioning, kickoff pxe install
#####################################################
- name: PLAY_1 | Setup and base provisioning
  hosts: localhost
  connection: local
  gather_facts: false

# .....irrelevant tasks that bootstrap a machine omitted for brevity....
  - name: INVENTORY | Update temp inventory with new host into new_provisions
    add_host:
      ansible_connection: ssh
      ansible_user: root
      host_key_checking: false
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      ansible_python_interpreter: "{{ os_info[operating_system]['python_interpreter'] | default(omit) }}"
      name: "{{ item }}"
      groups:
      - new_provisions
      - "{{ kit }}"
    loop: "{{ final_hostnames }}"

  - name: show all the hosts matching new_provisions and {{ kit }}
    debug:
      msg: "{{ item }}"
    with_inventory_hostnames:
    - new_provisions
    - "{{ kit }}"

  - name: test connection
    ping:
    delegate_to: "{{ item }}"
    loop: "{{ final_hostnames }}"

##############################################
# PLAY 2 - post install (unix config)
##############################################
- name: PLAY_2 | Post-install, *NIX Configuration, & Kit
  hosts: new_provisions
  gather_facts: false
  remote_user: root

  roles:
  - provision_servers_postinstall
 ....
```

##### EXPECTED RESULTS

Expect to run the second play against the group "new_provisions" 

##### ACTUAL RESULTS

```paste below
TASK [INVENTORY | Update temp inventory with new host into new_provisions] *****
changed: [localhost] => (item=new-server1)
TASK [show all the hosts matching new_provisions and unix] *********************
ok: [localhost] => (item=new-server1) => {
    "msg": "new-server1"
}
TASK [test connection] *********************************************************
ok: [localhost -> gabe-ap-ds11a] => (item=new-server1)
PLAY [PLAY_2 | Post-install, *NIX Configuration, & Kit] ************************
skipping: no hosts matched
```
