### ISSUE TITLE
becoming a sudo user can not read files created by root with permission 600.

### ISSUE THREAD

**Issue by cveto** [ansible/ansible#66732]
##### SUMMARY

Trying to play a playbook which:
1. Connects to a target CentOS7 as a _**non-sudo-user**_,
2. Become a sudo-user using the _**become_user: sudo_user**_ and _**become_method: su**_
3. Read a file owned by root with privileges 600 with elevated privileges using _**become: yes**_

The way SSH connection is made withouth SSH keys, only with passwords. 
Using: 
- ansible_ssh_user=non-sudo-user
- ansible_ssh_pass=non-sudo-userpwd
- ansible_become_pass=sudo-userpwd

##### ISSUE TYPE
- Ansible returns:  _**msg: file is not readable:** _ as if I do not have adequate permissions.
- Changing the user to _**root**_ and using _**rootpwd**_ works without an issue. 
This makes me believe that I did adequetely get the elevated permissions as a sudu user, but there is something else wrong with ansible.

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

_Returns empty_
```paste below

```

##### OS / ENVIRONMENT

Source: CentOS7 from osboxes.org
Target: CentOS7 from osboxes.org

##### STEPS TO REPRODUCE

You need 

- a target machine
-  2 files with permission 600. One owned by root and one owned by another sudo user. 
- 2 users on target machine. One sudo, one non-sudo.

Then just play the playbook with the inventory file while adapting usernames and passwords.

```yaml
---
# file: test476.yml
- name: test476
  hosts: boxxy  
  tasks:
    - name: cpfl
      become_user: sudo-user
      become_method: su
      become: yes
      fetch:
        dest: "./fetch_passwd/"  
        src: "{{ item }}"
        fail_on_missing: yes
        validate_checksum: yes
        flat: no                 
      loop:
        -  /etc/passwd
        -  /etc/group
        -  /etc/default/useradd
        -  /etc/login.defs
        -  /home/sudo-user/rootfile.txt         # owner is root. File permission 600
        -  /home/sudo-user/udo-userfile.txt  # owner is sudo-user. sudo-user is sudo.  File permission 600

```
```ini
# file: inventory
boxxy ansible_ssh_host=192.168.1.5

[all_servers]
boxxy

[all_servers:vars]
ansible_ssh_user=sudo-user
ansible_ssh_pass=sudo-userpwd
ansible_become_pass=sudo-userpwd
```

##### EXPECTED RESULTS

I expected the sudo user _**sudo-user**_ to be able to read  a file with permission 600, owned by root, when a non-sude-user become sudo-user using become_user method.

##### ACTUAL RESULTS

sudo user _**sudo-user**_ can not read a file with permission 600, owned by root. It returns _**msg: file is not readable:** _

However, if I set become_user: root and ansible_become_pass=rootpwd, it works as expected and can read the file. 

Root can also read files owned by other sudo users with permission 600.

```paste below
ansible-playbook -i inventory test476.yml

```
