### ISSUE TITLE
ios_interfaces doesn't issue description with overridden state

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#66730]
##### SUMMARY
I have a task executed using `ios_interfaces` where it should override the old description with a new description for an interface. The invocation shows a description associated but the commands aren't issued properly. It removes the description but doesn't re-add.

CC @tknipper11 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_interfaces

##### ANSIBLE VERSION

```paste below
 Ansible 2.9.0 

 _______________ 
<  Tower 3.5.3  >
 --------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||
```

##### OS / ENVIRONMENT
Red Hat

##### STEPS TO REPRODUCE
```yaml
- name: Create interface configuration data structures
  set_fact:
    int_general: >
      {{ int_general | default([]) + [{"enabled": item.enabled | default(omit),
                                       "speed": item.speed | default(omit),
                                       "mtu": item.mtu | default(omit),
                                       "description": item.description | default(omit),
                                       "duplex": item.duplex | default(omit),
                                       "name": item.number
                                       }]}}

- name: Configure interface
  ios_interfaces:
    state: overridden
    config: '{{ int_general }}'
  register: general

```

##### EXPECTED RESULTS
I expected the description to be updated.

##### ACTUAL RESULTS
```paste below
{
    "changed": true,
    "commands": [
        "interface GigabitEthernet1",
        "description Management interface",
        "interface GigabitEthernet2",
        "no description"
    ],
    "before": [
        {
            "name": "GigabitEthernet1",
            "enabled": true
        },
        {
            "name": "GigabitEthernet2",
            "description": "Test you",
            "enabled": true
        },
        {
            "name": "GigabitEthernet3",
            "enabled": true
        },
        {
            "name": "GigabitEthernet4",
            "enabled": true
        }
    ],
    "after": [
        {
            "name": "GigabitEthernet1",
            "description": "Management interface",
            "enabled": true
        },
        {
            "name": "GigabitEthernet2",
            "enabled": true
        },
        {
            "name": "GigabitEthernet3",
            "enabled": true
        },
        {
            "name": "GigabitEthernet4",
            "enabled": true
        }
    ],
    "invocation": {
        "module_args": {
            "state": "overridden",
            "config": [
                {
                    "enabled": true,
                    "description": "Management interface",
                    "name": "GigabitEthernet1",
                    "speed": null,
                    "mtu": null,
                    "duplex": null
                },
                {
                    "enabled": true,
                    "description": "CSR01-NXOS01",
                    "name": "GigabitEthernet2",
                    "speed": null,
                    "mtu": null,
                    "duplex": null
                },
                {
                    "enabled": true,
                    "name": "GigabitEthernet3",
                    "description": null,
                    "speed": null,
                    "mtu": null,
                    "duplex": null
                },
                {
                    "enabled": true,
                    "name": "GigabitEthernet4",
                    "description": null,
                    "speed": null,
                    "mtu": null,
                    "duplex": null
                }
            ]
        }
    },
    "_ansible_no_log": false
}
```
