### ISSUE TITLE
Starting in 2.9 service module no longer accepts wildcards

### ISSUE THREAD

**Issue by kjw3** [ansible/ansible#66740]
##### SUMMARY
As the subject states, starting in 2.9, the ability to feed wildcard names to the service module is no longer accepted. Wildcard names is a feature of systemctl and is very useful for service lists that start with a consistent prefix but may have many different service names that could change between releases.

Example:
systemctl restart openstack-*

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /root/hattrick/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### STEPS TO REPRODUCE
Create a task that uses the service module and passes a wildcard pattern as name. This worked in versions prior to 2.9

```yaml
- name: restart openstack services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - 'openstack-*'
    - 'neutron-*'
    - 'httpd'
  when: versions.rhosp <= 13
  tags: configure
```

##### EXPECTED RESULTS
Allow wildcard names and matching service names get acted on

##### ACTUAL RESULTS
Ansible task fails stating that wildcard names are not supported in version 2.9
