### ISSUE TITLE
Cannot add member to an aggregate interface on Fortios 

### ISSUE THREAD

**Issue by alfred-sa** [ansible/ansible#66766]
##### SUMMARY
I don't manager to add member to an LACP interface on fortios

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fortios_system_interface

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/huji/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 09:25:23) [GCC 9.2.1 20191130]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

On fortigate FG34E1-6.0.6-FW-build0272-190716

##### STEPS TO REPRODUCE

Here is a task that create a LACP interface on the fortigate and enslave the ports 3 and 4 into it.

```yaml
    - name: create vdom lacp port3-4
      fortios_system_interface:
        host: "{{ ansible_host }}"
        username: "{{ ansible_username }}"
        password: "{{ ansible_password }}"
        ssl_verify: "{{ ssl_verify }}"
        vdom: test
        state: "present"
        system_interface:
          type: aggregate
          name: test_lacp_name
          member:  [port3, port4]
          vdom: test
          lacp_mode: active
          lacp_speed: fast
          mtu: 9000
```

##### EXPECTED RESULTS

It should work.

##### ACTUAL RESULTS

It returns an error 500 "Error in repo".
It works if I let the member variable empty (but it doesn't enslave interfaces, of course), but as soon as I put something in it, it stops working.
