### ISSUE TITLE
Groups in vmware_vm_inventory plugin don't work

### ISSUE THREAD

**Issue by LeDOC666** [ansible/ansible#66767]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_vm_inventory

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /datas/ansible/logs/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/datas/ansible/roles']
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'vmware_vm_inventory']

```

##### OS / ENVIRONMENT

CentOS 7.5

##### STEPS TO REPRODUCE

```yaml
plugin: vmware_vm_inventory
strict: false
hostname: 'vsrv-vc-dmz'
username: 'login'
password: 'password'
validate_certs: false
groups:
  cluster_dmz: true
properties:
- 'name'
- 'guest.ipAddress'
- 'guest.hostName'
with_tags: true

```

##### EXPECTED RESULTS

Create a group name cluster_dmz with all host from that inventory in.

##### ACTUAL RESULTS

```paste below
no group created with:
ansible-inventory -i inv_dmz.vmware.yml --graph
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/inventory/vmware_vm_inventory.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/vmware_vm_inventory.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/support/integration/plugins/inventory/vmware_vm_inventory.py`](https://github.com/ansible/ansible/blob/devel/test/support/integration/plugins/inventory/vmware_vm_inventory.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible-collections/vmware/pull/140

**Comment by Akasurde** [comment]
With ansible-collection/vmware#140 you can now create groups - 

```yaml
plugin: community.vmware.vmware_vm_inventory
strict: False
hostname: 10.65.201.187
username: administrator@vsphere.local
password: Esxi@123$%
validate_certs: False
with_tags: False
properties:
- 'name'
- 'config.uuid'
- 'config.name'
- 'guest.toolsStatus'
- 'guest.toolsRunningStatus'
- 'guest.ipAddress'
- 'configIssue'
- 'config.bootOptions'
- 'config.annotation'
- 'config.alternateGuestName'
compose:
  ansible_host: 'guest.ipAddress'
groups:
    cluster_dmz: True
```
