### ISSUE TITLE
Variable precedence changes between tasks when -e and vars_files are used

### ISSUE THREAD

**Issue by rakuco** [ansible/ansible#6677]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

N/A
##### Summary:

Variables referenced in tasks (the ones which appear directly in the playbook/are included with `include` as well as ones in roles) have their value changed across tasks when they are specified both in `vars_files` and with `--extra-vars`: the first time a tasks refers to it the value in `vars_files` is used, and all subsequent tasks get the value passed via `--extra-vars`.
##### Steps To Reproduce:

my_vars.yml:

``` yaml

---
some_var: foo
```

playbook.yml:

``` yaml

---
- hosts: 127.0.0.1
  connection: local
  vars_files: [my_vars.yml]
  tasks:
  - command: echo {{ some_var }}
  - command: echo {{ some_var }}
  - command: echo {{ some_var }}
```

Then call ansible-playbook with `ansible-playbook -e some_var=bar playbook.yml`.
##### Expected Results:

The `echo` calls show me "bar" 3 times.
##### Actual Results:

The first `echo` call shows "foo", the other 2 show "bar".
