### ISSUE TITLE
unarchive module does not support checksums to validate file integrity of a file that needs to be downloaded

### ISSUE THREAD

**Issue by denisse-dev** [ansible/ansible#66787]
Check

Check
##### SUMMARY

The `unarchive` module allows you to unarchive a file that needs to be downloaded like this:

```yaml
 - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: <url>
        dest: <destination>
        remote_src: yes
```
However, issues may occur and the file could be intercepted and modified by an attacker, it could have changed to a new version (that may not be the one we want) or it could be simply be downloaded erroneously this is why validating a file with a checksum is handy, the only way to do it would be like this:

```yaml
- name: Download the file to unarchive
    get_url:
        url: <url>
        dest: <destination>
        checksum: <a hash>
- name: Unarchive the file we've just downloaded
    unarchive:
        src: <source of the file to unarchive>
        dest: <destination of the unarchived files>
        remote_src: yes
```

As you can see we need to use two modules for a single task, it would be pretty useful if the `unarchive` module supported checksum validation so we could simply do something like this:

```yaml
- name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: <url>
        dest: <destination>
        remote_src: yes
        checksum: <a hash>
```
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

unarchive

##### ADDITIONAL INFORMATION

It would be used to validate the integrity of the downloaded files when using the unarchive module to download remote files.

```yaml
- name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: <url>
        dest: <destination>
        remote_src: yes
        checksum: <a hash>
```
