### ISSUE TITLE
module ecs_task assign_public_ip appears to be non-functional

### ISSUE THREAD

**Issue by WesWWagner** [ansible/ansible#66781]
##### SUMMARY

During invocation by ecs_task of a task properly defined and successfully executed ecs_taskdefinition the ecs_task does not generate a public ip

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ecs_task

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml


- name: Check ECS Cluster
  connection: network cli
  gather_facts: false
  hosts: localhost-py3
  tasks:

  - ecs_cluster:
      name: jenkfg
      state: present
      region: us-west-2

  - ecs_taskdefinition:
      region: us-west-2
      family: httpd
      containers:
      - name: httpd
        essential: true
        image: "httpd"
        portMappings:
        - containerPort: 80
          hostPort:      80
      launch_type: FARGATE
      cpu: 512
      memory: 1024
      state: present
      network_mode: awsvpc

  - ecs_task:
      operation: run
      cluster: jenkfg
      region: us-west-2
      task_definition: httpd
      count: 1
      launch_type: FARGATE
      started_by: ansible
      network_configuration:
        assign_public_ip: true
        subnets:
        - subnet-0ea9d9fc367005dbe
        security_groups:
        - sg-0656e8c74b9bf19c9


```

##### EXPECTED RESULTS

I would expect an ecs_task to be generated with both a private ip and a public ip, but only the private ip is generated. I attemped to use both "true" and "yes" as options for assign_public_ip

##### ACTUAL RESULTS

```paste below

TASK [ecs_task] **************************************************************************************
task path: /home/ubuntu/git/jenkins/runbook.yml:30
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540 `" && echo ansible-tmp-1579970582.863367-258760910924540="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/dist-packages/ansible/modules/cloud/amazon/ecs_task.py
<localhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-21987xbbp5l7p/tmpcsqlr6fz TO /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540/AnsiballZ_ecs_task.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540/ /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540/AnsiballZ_ecs_task.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540/AnsiballZ_ecs_task.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1579970582.863367-258760910924540/ > /dev/null 2>&1 && sleep 0'
changed: [localhost-py3] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "cluster": "jenkfg",
            "container_instances": null,
            "count": 1,
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "launch_type": "FARGATE",
            "network_configuration": {
                "assign_public_ip": true,
                "security_groups": [
                    "sg-0656e8c74b9bf19c9"
                ],
                "subnets": [
                    "subnet-0ea9d9fc367005dbe"
                ]
            },
            "operation": "run",
            "overrides": null,
            "profile": null,
            "region": "us-west-2",
            "security_token": null,
            "started_by": "ansible",
            "task": null,
            "task_definition": "httpd",
            "validate_certs": true
        }
    },
    "task": [
        {
            "attachments": [
                {
                    "details": [
                        {
                            "name": "subnetId",
                            "value": "subnet-0ea9d9fc367005dbe"
                        }
                    ],
                    "id": "3e51692e-11f9-4b31-87d6-5fe93873865c",
                    "status": "PRECREATED",
                    "type": "ElasticNetworkInterface"
                }
            ],
            "availabilityZone": "us-west-2a",
            "clusterArn": "arn:aws:ecs:us-west-2:942067951460:cluster/jenkfg",
            "containers": [
                {
                    "containerArn": "arn:aws:ecs:us-west-2:942067951460:container/8beee46f-203c-4cf6-9fb9-18a1d536ab66",
                    "cpu": "0",
                    "image": "httpd",
                    "lastStatus": "PENDING",
                    "name": "httpd",
                    "networkInterfaces": [],
                    "taskArn": "arn:aws:ecs:us-west-2:942067951460:task/d2321873-3983-47f1-97c8-727df562dc4b"
                }
            ],
            "cpu": "512",
            "createdAt": "2020-01-25T16:43:05.117000+00:00",
            "desiredStatus": "RUNNING",
            "group": "family:httpd",
            "lastStatus": "PROVISIONING",
            "launchType": "FARGATE",
            "memory": "1024",
            "overrides": {
                "containerOverrides": [
                    {
                        "name": "httpd"
                    }
                ],
                "inferenceAcceleratorOverrides": []
            },
            "platformVersion": "1.3.0",
            "startedBy": "ansible",
            "tags": [],
            "taskArn": "arn:aws:ecs:us-west-2:942067951460:task/d2321873-3983-47f1-97c8-727df562dc4b",
            "taskDefinitionArn": "arn:aws:ecs:us-west-2:942067951460:task-definition/httpd:9",
            "version": 1
        }
    ]
}
META: ran handlers
META: ran handlers

```
