### ISSUE TITLE
aws_eks_cluster: InvalidSubnetID.NotFound

### ISSUE THREAD

**Issue by maniagarwal90** [ansible/ansible#66783]
I am using the new module aws_eks_cluster_module.
the task is defined as

```yaml
    - name: create an eks cluster
      aws_eks_cluster:
        name: mani-eks-cluster
        version: v1.10.0
        role_arn: mani-kube-role
        subnets:
          - "{{ subnet.subnet.id }}"
        security_groups:
          - "{{ security_group }}"
      register: caller_facts
```
vpc, subnet, security groups are created perfectly. but when this task is executed. it is giving me following error:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_aws_eks_cluster_payload_lj5RfE/ansible_aws_eks_cluster_payload.zip/ansible/modules/cloud/amazon/aws_eks_cluster.py", line 173, in ensure_present
  File "/home/mani.agarwal/.local/lib/python2.7/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/mani.agarwal/.local/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidSubnetID.NotFound) when calling the DescribeSubnets operation: The subnet ID 'subnet-034d34afe1d9e29e6' does not exist

fatal: [localhost]: FAILED! => {
    "boto3_version": "1.11.4", 
    "botocore_version": "1.14.4", 
    "changed": false, 
    "error": {
        "code": "InvalidSubnetID.NotFound", 
        "message": "The subnet ID 'subnet-034d34afe1d9e29e6' does not exist"
    }, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "debug_botocore_endpoint_logs": false, 
            "ec2_url": null, 
            "name": "mani-eks-cluster", 
            "profile": null, 
            "region": null, 
            "role_arn": "mani-kube-role", 
            "security_groups": [
                "mani-kube"
            ], 
            "security_token": null, 
            "state": "present", 
            "subnets": [
                "subnet-034d34afe1d9e29e6"
            ], 
            "validate_certs": true, 
            "version": "v1.10.0", 
            "wait": false, 
            "wait_timeout": 1200
        }
    }, 
    "msg": "Couldn't lookup security groups: An error occurred (InvalidSubnetID.NotFound) when calling the DescribeSubnets operation: The subnet ID 'subnet-034d34afe1d9e29e6' does not exist", 
    "response_metadata": {
        "http_headers": {
            "connection": "close", 
            "date": "Sat, 25 Jan 2020 18:40:46 GMT", 
            "server": "AmazonEC2", 
            "transfer-encoding": "chunked"
        }, 
        "http_status_code": 400, 
        "request_id": "395aa3c6-89f7-4806-ad80-25493a0241f9", 
        "retry_attempts": 0
    }
}
```
 Any suggestions?
