### ISSUE TITLE
win_xml module omits "warn: no" option

### ISSUE THREAD

**Issue by fartosh** [ansible/ansible#66804]
##### SUMMARY
When using win_xml module with
```
args:
  warn: no
```
option, multiple warnings can be seen in the output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_xml

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fartosh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fartosh/.local/lib/python2.7/site-packages/ansible
  executable location = /home/fartosh/.local/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks', u'log_plays']
```

##### OS / ENVIRONMENT

Windows Server 2016

##### STEPS TO REPRODUCE

1. Copy random xml file with some nodes to C:\Users\foo\Desktop\a.xml
2. Create role with task
```yaml
- name: Add node
  win_xml:
    backup: yes
    path: C:\Users\foo\Desktop\a.xml
    xpath: /
    type: element
    fragment: '<node><test myAttribute="01:00:00"/></node>'
  args:
    warn: no
```

##### EXPECTED RESULTS

No warnings in the output since `warn: no` option is provided

##### ACTUAL RESULTS

Very long output with warnings like:

```
[WARNING]: node:  element: [...] Element count is 8
```
and
```
[WARNING]: element is [...]
```
