### ISSUE TITLE
Module digital_ocean fails on python3: name 'basestring' is not defined

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#66825]
### SUMMARY
When using the `digital_ocean` module on a controller node running Python 3, an error is displayed:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'basestring' is not defined
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean

##### ANSIBLE VERSION
```
ansible 2.9.4
  config file = /home/robertdb/Documents/github.com/robertdebock/ansible-piratebay/ansible.cfg
  configured module search path = ['/home/robertdb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 22:52:49) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/robertdb/Documents/github.com/robertdebock/ansible-piratebay/ansible.cfg) = ['/home/robertdb/Documents/github.com/robertdebock/ansible-piratebay/inventory']
DEFAULT_ROLES_PATH(/home/robertdb/Documents/github.com/robertdebock/ansible-piratebay/ansible.cfg) = ['/home/robertdb/Documents/github.com/robertdebock/ansible-piratebay/roles']
```

##### OS / ENVIRONMENT
Controller: Fedora 31

##### STEPS TO REPRODUCE

```yaml
    - name: create droplet
      digital_ocean:
        state: active
        command: droplet
        name: my_name
        region_id: ams3
        size_id: s-1vcpu-1gb
        image_id: fedora-31-x64
        ssh_key_ids: xyzabc
        unique_name: yes
        api_token: abc123
        wait_timeout: 120
```

##### EXPECTED RESULTS
A working droplet.

##### ACTUAL RESULTS

```
TASK [create droplet] ************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'basestring' is not defined
fatal: [localhost]: FAILED! => {"changed": false, "msg": "name 'basestring' is not defined"}

```
