### ISSUE TITLE
nxos_devicealias : Adding an option to write config to startup

### ISSUE THREAD

**Issue by tkelkermans** [ansible/ansible#66843]
##### SUMMARY
When using this module, configure change is not written to the startup menu of all switches of the fabric. Adding an option to write the config would prevent a configuration mismatch in case of reboot.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
module nxos_devicealias.py on nxos/storage

##### ADDITIONAL INFORMATION
Adding an option to write the config would prevent a configuration mismatch in case of reboot.

```yaml
- name: 'Test that device alias module works'
  nxos_devicealias:
    da:
      - name: test1_add
        pwwn: '56:2:22:11:22:88:11:67'
      - name: test2_add
        pwwn: '65:22:22:11:22:22:11:d'
      - name: dev1
        remove: true
      - name: dev2
        remove: true
    distribute: true
    mode: enhanced
    save: true
```
