### ISSUE TITLE
unable to set an alias in the hosts file (unicode problem in line?)

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#6684]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Ubuntu 13.10 amd64
##### Summary:

Ansible is unable to handle aliases that are not "real" hostnames:

```
cloudncode-ansible-0 ansible_ssh_host=10.0.3.204 ansible_ssh_user=ubuntu
```
##### Steps To Reproduce:
- Install Ansible from GitHub devel branch.
- Update hosts file with content in summary.
- Create a dummy playbook.
- Run it.
##### Expected Results:

Expected to not fail.
##### Actual Results:

```
fatal: [cloudncode-ansible-0 ansible_ssh_host=10.0.3.204 ansible_ssh_user=ubuntu] => {'msg': 'FAILED: [Errno -2] Name or service not known', 'failed': True}
```

**Comment by mpdehaan** [comment]
Can you please paste your Ansible hosts file and your dummy playbook?

This should be splitting out variables on the same line without problems here, but for some reason it's not.

Seeing the whole hosts file would be helpful.

**Comment by davidfischer-ch** [comment]
```
cloudncode-ansible-0 ansible_ssh_host=10.0.3.204 ansible_ssh_user=ubuntu
```

Playbook:

```
---
- hosts: all
  gather_facts: False
  sudo: True

  tasks:

    - name: Install pycurl for APT Ansible module
      pip: name=pycurl

    - name: Add FFMpeg repository to install the real FFMpeg
      apt_repository: repo=ppa:jon-severinsson/ffmpeg state=present update_cache=yes

    - name: Install the real FFMpeg
      apt: name=ffmpeg state=latest
```
