### ISSUE TITLE
Unable to create new logical network on oVirt

### ISSUE THREAD

**Issue by dominikholler** [ansible/ansible#66858]
##### SUMMARY

Unable to create new logical network on oVirt

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ovirt_network

##### ANSIBLE VERSION

```paste below

```
master

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
  - ovirt_auth:
     state: present
     username: admin@internal
     password: '123456'
     url: https://ovirt-master.virt/ovirt-engine/api
     insecure: true

  - ovirt_network:
     auth: "{{ ovirt_auth }}"
     data_center: Default
     name: network_123

```

##### EXPECTED RESULTS

network is created

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_network_payload_32f6rvf8/ansible_ovirt_network_payload.zip/ansible/modules/cloud/ovirt/ovirt_network.py", line 327, in main
  File "/tmp/ansible_ovirt_network_payload_32f6rvf8/ansible_ovirt_network_payload.zip/ansible/module_utils/ovirt.py", line 620, in create
    self.build_entity(),
  File "/tmp/ansible_ovirt_network_payload_32f6rvf8/ansible_ovirt_network_payload.zip/ansible/modules/cloud/ovirt/ovirt_network.py", line 175, in build_entity
  File "/tmp/ansible_ovirt_network_payload_32f6rvf8/ansible_ovirt_network_payload.zip/ansible/module_utils/ovirt.py", line 327, in get_id_by_name
    raise Exception("Entity '%s' was not found.".format(service, name, entity))
Exception: Entity '%s' was not found.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "clusters": null,
            "comment": null,
            "data_center": "Default",
            "description": null,
            "external_provider": null,
            "fetch_nested": false,
            "id": null,
            "label": null,
            "mtu": null,
            "name": "network_123",
            "nested_attributes": [],
            "poll_interval": 3,
            "state": "present",
            "timeout": 180,
            "vlan_tag": null,
            "vm_network": null,
            "wait": true
        }
    },
    "msg": "Entity '%s' was not found."
}

PLAY RECAP *****************************************************************************************************************************************************************$
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
