### ISSUE TITLE
ucs_wwn_pool description

### ISSUE THREAD

**Issue by julie-blake-verizon** [ansible/ansible#66861]
##### SUMMARY
ucs_wwn_pool does not accept the 'description' parameter. It does allow the alias 'descr'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ucs_wwn_pool

##### ANSIBLE VERSION

```
ansible 2.9.0
  config file = /opt/ansible/etc/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOLOR(/opt/ansible/etc/ansible.cfg) = False
CACHE_PLUGIN(/opt/ansible/etc/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/opt/ansible/etc/ansible.cfg) = /opt/ansible/etc/facts_cache
CACHE_PLUGIN_TIMEOUT(/opt/ansible/etc/ansible.cfg) = 86400
COLLECTIONS_PATHS(/opt/ansible/etc/ansible.cfg) = ['/opt/ansible/collections']
COLOR_VERBOSE(/opt/ansible/etc/ansible.cfg) = magenta
DEFAULT_GATHERING(/opt/ansible/etc/ansible.cfg) = smart
DEFAULT_HOST_LIST(/opt/ansible/etc/ansible.cfg) = ['/opt/ansible/inventory']
DEFAULT_MANAGED_STR(/opt/ansible/etc/ansible.cfg) = WARNING!!! MANAGED SYSTEM: This file is managed by Ansible, all manual
DEFAULT_ROLES_PATH(/opt/ansible/etc/ansible.cfg) = ['/opt/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/.ansible/.vault
DEPRECATION_WARNINGS(/opt/ansible/etc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS Linux release 7.7.1908 (Core)

##### STEPS TO REPRODUCE
```
- name: "SAN > Pools > root > Sub-Organizations > {{ ucs_orgs[0].name }} > WWNN Pools (Node)"
  ucs_wwn_pool:
    hostname: "{{ ucs_hostname }}"
    username: "{{ ucs_username }}"
    password: "{{ ucs_password }}"
    use_ssl: "{{ ucs_use_ssl }}"
    name: "{{ item.name }}"
    #descr: "{{ item.desc | default('') }}"             # description should work here but doesn't !!!
    description: "{{ item.desc | default('') }}"
    org_dn: "{{ parent_dn }}/org-{{ item.org }}"
    purpose: node
    order: "{{ item.order | default('sequential') }}"
    first_addr: "{{ item.first.byte1 }}:{{ item.first.byte2 }}:{{ item.first.byte3 }}:{{ item.first.byte4 }}:{{ item.first.byte5 }}:{{ item.first.byte6 }}:{{ item.first.byte7 }}:{{ item.first.byte8 }}"
    last_addr: "{{ item.last.byte1 }}:{{ item.last.byte2 }}:{{ item.last.byte3 }}:{{ item.last.byte4 }}:{{ item.last.byte5 }}:{{ item.last.byte6 }}:{{ item.last.byte7 }}:{{ item.last.byte8 }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ucs_wwnn_pools }}"
```
##### EXPECTED RESULTS
Expect the output to be the same with either 'description' or 'descr' as they are supposed to be aliases.

##### ACTUAL RESULTS

```
    "msg": "Unsupported parameters for (ucs_wwn_pool) module: description Supported parameters include: descr, first_addr, hostname, last_addr, name, order, org_dn, password, port, proxy, purpose, state, use_proxy, use_ssl, username, wwn_list"
```
