### ISSUE TITLE
Allow inline Dockerfile specifications for Docker images.

### ISSUE THREAD

**Issue by tmbdev** [ansible/ansible#66862]
##### SUMMARY
Allow inline Dockerfile specifications for Docker images.

##### ISSUE TYPE
Add a dockerfile: option to docker_image:build: so that simple Docker files can be put in line.

##### COMPONENT NAME
docker_image

##### ADDITIONAL INFORMATION

Often, Docker files need to be built with just a few lines of text. It would be nice to be able to do this inline. In addition, this would also allow templating of Docker files.

```yaml
- name: Build an image and push it to a private repo
  docker_image:
    build:
      dockerfile: |
        FROM ubuntu/ubuntu
        RUN apt-get install -qqy dnsutils
    name: user/dnstestimage
    tag: v1
    push: yes
    source: build
```
