### ISSUE TITLE
k8s check mode does not work very well

### ISSUE THREAD

**Issue by ac-hibbert** [ansible/ansible#66870]
##### SUMMARY

With ```--check``` mode and k8s resources using the k8s_module (https://docs.ansible.com/ansible/latest/modules/k8s_module.html) it is showing things will change, when run without ```--check``` they don't change, which is correct

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.3
  config file = /Users/anhibber/.ansible.cfg
  configured module search path = ['/Users/anhibber/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.3/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Dec 27 2019, 18:05:45) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
INVENTORY_ENABLED(/Users/anhibber/.ansible.cfg) = ['host_list', 'script', 'yaml', 'ini', 'auto', 'k8s', 'k8s_inventory']
```

##### OS / ENVIRONMENT

mac os (controller)
EKS target

##### STEPS TO REPRODUCE

Example when running check and -vvvv

```yaml
changed: [jenkins-andy] => {
    "changed": true,
    "diff": {
        "after": {
            "spec": {}
        },
        "before": {
            "apiVersion": "v1",
            "kind": "PersistentVolumeClaim",
            "metadata": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{\"volume.beta.kubernetes.io/storage-class\":\"aws-efs\"},\"name\":\"jenkins-andy-home\",\"namespace\":\"jenkins-andy\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"1Mi\"}},\"storageClassName\":\"aws-efs\"}}",
                    "pv.kubernetes.io/bind-completed": "yes",
                    "pv.kubernetes.io/bound-by-controller": "yes",
                    "volume.beta.kubernetes.io/storage-class": "aws-efs",
                    "volume.beta.kubernetes.io/storage-provisioner": "example.com/aws-efs"
                },
                "creationTimestamp": "2019-11-19T17:18:09Z",
                "finalizers": [
                    "kubernetes.io/pvc-protection"
                ],
                "labels": {
                    "velero.io/backup-name": "19112019-2",
                    "velero.io/restore-name": "19112019-2-20191119171805"
                },
                "name": "jenkins-andy-home",
                "namespace": "jenkins-andy",
                "resourceVersion": "73344313",
                "selfLink": "/api/v1/namespaces/jenkins-andy/persistentvolumeclaims/jenkins-andy-home",
                "uid": "8f3babff-0af0-11ea-8fb2-0e6bf20680e8"
            },
            "spec": {
                "resources": {
                    "requests": {
                        "storage": "1Mi"
                    }
                },
                "storageClassName": "aws-efs",
                "volumeMode": "Filesystem",
                "volumeName": "pvc-8f3babff-0af0-11ea-8fb2-0e6bf20680e8"
            },
            "status": {
                "accessModes": [
                    "ReadWriteOnce"
                ],
                "capacity": {
                    "storage": "1Mi"
                },
                "phase": "Bound"
            }
        }
    },
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "append_hash": false,
            "apply": true,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": "thor-dev-eks-us-east-1",
            "force": false,
            "host": null,
            "kind": null,
            "kubeconfig": "/Users/anhibber/.kube/config",
            "merge_type": null,
            "name": null,
            "namespace": null,
            "password": null,
            "proxy": null,
            "resource_definition": "apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: \"jenkins-andy-home\"\n  namespace: \"jenkins-andy\"\n  annotations:\n    volume.beta.kubernetes.io/storage-class: aws-efs\nspec:\n  storageClassName: aws-efs\n  accessModes:\n    - ReadWriteOnce\n  resources:\n    requests:\n      storage: 1Mi",
            "src": null,
            "state": "present",
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "method": "apply",
    "result": {
        "spec": {
            "accessModes": [
                "ReadWriteOnce"
            ]
        }
    }
}
```
Run it again without check, it will not change

```yaml
ok: [jenkins-andy] => {
    "changed": false,
    "diff": {},
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "append_hash": false,
            "apply": true,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": "thor-dev-eks-us-east-1",
            "force": false,
            "host": null,
            "kind": null,
            "kubeconfig": "/Users/anhibber/.kube/config",
            "merge_type": null,
            "name": null,
            "namespace": null,
            "password": null,
            "proxy": null,
            "resource_definition": "apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: \"jenkins-andy-home\"\n  namespace: \"jenkins-andy\"\n  annotations:\n    volume.beta.kubernetes.io/storage-class: aws-efs\nspec:\n  storageClassName: aws-efs\n  accessModes:\n    - ReadWriteOnce\n  resources:\n    requests:\n      storage: 1Mi",
            "src": null,
            "state": "present",
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "method": "apply",
    "result": {
        "apiVersion": "v1",
        "kind": "PersistentVolumeClaim",
        "metadata": {
            "annotations": {
                "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"annotations\":{\"volume.beta.kubernetes.io/storage-class\":\"aws-efs\"},\"name\":\"jenkins-andy-home\",\"namespace\":\"jenkins-andy\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"1Mi\"}},\"storageClassName\":\"aws-efs\"}}",
                "pv.kubernetes.io/bind-completed": "yes",
                "pv.kubernetes.io/bound-by-controller": "yes",
                "volume.beta.kubernetes.io/storage-class": "aws-efs",
                "volume.beta.kubernetes.io/storage-provisioner": "example.com/aws-efs"
            },
            "creationTimestamp": "2019-11-19T17:18:09Z",
            "finalizers": [
                "kubernetes.io/pvc-protection"
            ],
            "labels": {
                "velero.io/backup-name": "19112019-2",
                "velero.io/restore-name": "19112019-2-20191119171805"
            },
            "name": "jenkins-andy-home",
            "namespace": "jenkins-andy",
            "resourceVersion": "73344313",
            "selfLink": "/api/v1/namespaces/jenkins-andy/persistentvolumeclaims/jenkins-andy-home",
            "uid": "8f3babff-0af0-11ea-8fb2-0e6bf20680e8"
        },
        "spec": {
            "accessModes": [
                "ReadWriteOnce"
            ],
            "resources": {
                "requests": {
                    "storage": "1Mi"
                }
            },
            "storageClassName": "aws-efs",
            "volumeMode": "Filesystem",
            "volumeName": "pvc-8f3babff-0af0-11ea-8fb2-0e6bf20680e8"
        },
        "status": {
            "accessModes": [
                "ReadWriteOnce"
            ],
            "capacity": {
                "storage": "1Mi"
            },
            "phase": "Bound"
        }
    }
}
```

Similar problems exist with normal patch/merge although that's probably expected

##### EXPECTED RESULTS

Only shows a change if there is going to be one

##### ACTUAL RESULTS

Shows changes that don't happen

```paste below

```
