### ISSUE TITLE
Yarn module: support  --frozen-lockfile argument

### ISSUE THREAD

**Issue by hallvors** [ansible/ansible#66901]
##### SUMMARY

Ensure `yarn install` will not update the `yarn.lock` file, and fail if an update is required

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Yarn module

##### ADDITIONAL INFORMATION

When deploying an update, the git checkout sometimes fails because `yarn install` apparently updated the `yarn.lock` file. This may very well be my fault for not having checked in an updated lock file with a package.json change or something, but it creates an annoying failure mode that potentially hits you way after the mistake. The ` --frozen-lockfile` command line argument to the `install command` is supposed to avoid this.

```yaml

- name: Install Node.js dependencies with Yarn
  yarn:
    production: true
    path: "{{ remote_app_directory }}"
    frozen_lockfile: yes

```
