### ISSUE TITLE
pkgin - not enough values to unpack

### ISSUE THREAD

**Issue by blackwood821** [ansible/ansible#66909]
##### SUMMARY

The `pkgin` module seems to always fail to install Java (could be any package) with the error `not enough values to unpack` after creating a new zone via the `vmadm` module. However when this happens if I run it again it succeeds. It seems to only happen when my playbook actually has to create the zone. If the zone already exists before the playbook runs then it doesn't seem to happen.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`pkgin`

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /Users/chad/.ansible.cfg
  configured module search path = ['/Users/chad/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.2_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Jan 17 2020, 23:56:55) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/chad/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/chad/.ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/Users/chad/.ansible.cfg) = ['/Users/chad/ansible_inventory']
HOST_KEY_CHECKING(/Users/chad/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

SmartOS native zone

##### STEPS TO REPRODUCE

Run a playbook that has two plays. The first play runs against the SmartOS global, creates a new zone using the `vmadm` module and adds the new zone to a new ansible host group. The second play runs against the newly created zone and attempts to install the `openjdk8` package using the `pkgin` module. This is the part that fails with the error `not enough values to unpack`.

```yaml
---
- hosts: global
  remote_user: root

  tasks:

    - name: create new zone
      vmadm:
        alias: "test_zone"
        hostname: "test_zone"
        state: present
        brand: joyent
        image_uuid: "b81bcc1e-f1c8-11e9-8876-03a841507d8c"
        autoboot: yes
        max_physical_memory: 1024
        quota: 10240
        resolvers: [ 8.8.8.8, 8.8.4.4 ]
        nics:
          - nic_tag: admin
            primary: yes
            ip: 10.10.50.225
            gateways: [ 10.10.50.1 ]
            netmask: 255.255.255.0
        customer_metadata:
          root_authorized_keys: "<ssh_key_here>"
          user-script: '/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys'
      register: zone_creation

    - name: add new zone to a new host group
      add_host:
        name: "10.10.50.225"
        groups: "new_zone"

- hosts: new_zone
  remote_user: root

  vars:
    jdk_package_name: openjdk8

  tasks:

  - name: install Java ({{ jdk_package_name }})
    pkgin:
      name: "{{ jdk_package_name }}"
      state: present
    register: install_java
```

##### EXPECTED RESULTS

I expected the zone to be created and Java to be successfully installed on the new zone.

##### ACTUAL RESULTS

The zone gets created but the `pkgin` module fails to install Java.

```paste below

PLAY [global] ********************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
Wednesday 29 January 2020  10:52:32 -0600 (0:00:00.060)       0:00:00.061 ***** 
ok: [10.10.50.100]

TASK [create new zone] ***********************************************************************************************************************************
Wednesday 29 January 2020  10:52:40 -0600 (0:00:08.136)       0:00:08.197 ***** 
changed: [10.10.50.100]

TASK [add new zone to a new host group] ******************************************************************************************************************
Wednesday 29 January 2020  10:53:31 -0600 (0:00:50.875)       0:00:59.073 ***** 
changed: [10.10.50.100]

PLAY [new_zone] ******************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
Wednesday 29 January 2020  10:53:31 -0600 (0:00:00.031)       0:00:59.105 ***** 
ok: [10.10.50.225]

TASK [install Java (openjdk8)] ***************************************************************************************************************************
Wednesday 29 January 2020  10:53:35 -0600 (0:00:03.905)       0:01:03.011 ***** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: not enough values to unpack (expected 2, got 1)
fatal: [10.10.50.225]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/opt/local/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/opt/local/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_pkgin_payload_9lw1spk2/ansible_pkgin_payload.zip/ansible/modules/packaging/os/pkgin.py\", line 381, in <module>\n  File \"/tmp/ansible_pkgin_payload_9lw1spk2/ansible_pkgin_payload.zip/ansible/modules/packaging/os/pkgin.py\", line 374, in main\n  File \"/tmp/ansible_pkgin_payload_9lw1spk2/ansible_pkgin_payload.zip/ansible/modules/packaging/os/pkgin.py\", line 265, in install_packages\n  File \"/tmp/ansible_pkgin_payload_9lw1spk2/ansible_pkgin_payload.zip/ansible/modules/packaging/os/pkgin.py\", line 169, in query_package\nValueError: not enough values to unpack (expected 2, got 1)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ***********************************************************************************************************************************************
10.10.50.100               : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
10.10.50.225               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Wednesday 29 January 2020  10:53:41 -0600 (0:00:05.644)       0:01:08.656 ***** 
=============================================================================== 
create new zone ---------------------------------------------------------------------------------------------------------------------------------- 50.88s
Gathering Facts ----------------------------------------------------------------------------------------------------------------------------------- 8.14s
install Java (openjdk8) --------------------------------------------------------------------------------------------------------------------------- 5.64s
Gathering Facts ----------------------------------------------------------------------------------------------------------------------------------- 3.91s
add new zone to a new host group ------------------------------------------------------------------------------------------------------------------ 0.03s
```
