### ISSUE TITLE
ec2_module does not create spot requests

### ISSUE THREAD

**Issue by jokerswild663** [ansible/ansible#6691]
##### Issue Type:

Bug
##### Ansible Version:

ansible 1.5.3
boto version 2.5.2
##### Environment:

ubuntu
fedora
##### Summary:

When trying to use the ec2 module, spot requests can't be created.  An error message is given saying that spot_price and spot_wait_timeout are not defined.
##### Steps To Reproduce:
1. have an ami ready within aws
2. run the following play

```
- name: ec2 launch
  local_action:
   module: ec2
   region: "{{ region }}"
   group: "{{ security_group }}"
   key_name: "{{ ec2_keyname }}"
   aws_access_key: "{{ aws_default_access }}"
   aws_secret_key: "{{ aws_default_secret }}"
   instance_tags: "{{ ec2_tags }}"
   instance_type: c1.medium
   wait: yes
   image: ami-9dffcbf4
   count: 1
  register: ec2
  tags: ec2
```
##### Expected Results:

an ec2 spot request will be created.
##### Actual Results:

TASK: [ec2 | ec2 launch] *****************************************************\* 
failed: [localhost] => {"failed": true, "item": ""}
msg: unsupported parameter for module: spot_price

FATAL: all hosts have already failed -- aborting
