### ISSUE TITLE
Allow to declare group variables in dynamic inventory (aws_ec2)

### ISSUE THREAD

**Issue by gabops** [ansible/ansible#66913]
##### SUMMARY
At the moment there is no way for declaring variables in a dynamic inventory other than throught "compose". This covers a lot of cases however, would be useful having a way to define group vars easily in a "keyed_groups" or even "groups".

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
aws_ec2.py

##### ADDITIONAL INFORMATION
I think something like the next examples can give us a lot of power when defining groups and specifically in situations where groups are at the same level (ansible_group_priority).

an example for "groups" could be:
```yaml
groups:
  a_group: tags.CustomTag == "foo"
  b_group: tags.CustomTag == "bar"

group_vars:
  a_group:
    ansible_group_priority: 10
    custom_variable: "hello world"

```

an example for keyed groups:
```yaml
keyed_groups:
  - prefix: 'c'
    key: ec2_region
    group_vars:
      ansible_group_priority: 0

  - prefix: 'b'
    key: ec2_architecture
    group_vars:
      foo: "{{ tags.CustomArchName }}"

  - prefix: 'a'
    key: tags.Role
    group_vars:
      project: "{{ tags.Project }}"
      env: production
      ansible_group_priority: 10
```
