### ISSUE TITLE
[ec2_vpc_vpn] static routes are not added when State is "deleted"

### ISSUE THREAD

**Issue by jtrain184** [ansible/ansible#66925]
##### SUMMARY
When static routes have been deleted

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_vpc_vpn

##### ANSIBLE VERSION

```
ansible 2.8.5
  config file = /home/user/amtrak_ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/share/venv/ansible-2.8.5-py2.7/lib/python2.7/site-packages/ansible
  executable location = /usr/local/share/venv/ansible-2.8.5-py2.7/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 12:19:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### OS / ENVIRONMENT
rhel7

##### STEPS TO REPRODUCE
Example playbook:
```yaml
- name: Add {{ VPC_NAME }} CIDR to the {{ target_vpc }} main route table
  ec2_vpc_route_table:
    region: '{{ region }}'
    vpc_id: 'vpc-xxxx'
    lookup: id
    route_table_id: 'rt-xxxx
    routes:
    - dest: '{{ item }}'
      gateway_id: "vgw-xxx"
    purge_routes: no
    purge_tags: no
    purge_subnets: no
  loop: '{{ destination_cidr_list }}'
```

##### EXPECTED RESULTS
Existing routes stay, new routes are added.

##### ACTUAL RESULTS
Routes that have "State": "deleted" don't get added back.  Possibly because current routes is not checking the state of all routes, just the state of the VPN:
https://github.com/ansible/ansible/blob/1156962cded3cfed8b40a23b841415811fb24cba/lib/ansible/modules/cloud/amazon/ec2_vpc_vpn.py#L658

Play output shows sate of "available" even for deleted routes.

ansible playbook output:
```
  routes:
  - destination_cidr_block: 172.23.7.0/24
    state: available
```

awscli output:
```
                {
                    "DestinationCidrBlock": "172.23.7.0/24",
                    "State": "deleted"
                },
```
