### ISSUE TITLE
Ansible checksum error on template/copy module

### ISSUE THREAD

**Issue by Bhagu5491** [ansible/ansible#66924]
##### SUMMARY
I'm getting below error when I'm using ansible copy or template module

fatal: [server]: FAILED! => {"changed": false, "checksum": "c1b955c231a37b92df49d26b32168a4fc9c17cf9", "msg": "Destination not writable"}

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

``
ansible 2.7.1
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT

coreos

##### STEPS TO REPRODUCE

```yaml
 - name: Copy etcd configuration environment scripts
      #copy: src=config.sh  dest=/opt/deployment/config.sh
      #  owner: "{{ ansible_ssh_user }}"
      #  mode: 0755
      #check_mode: no
     template:
        src: load-etcd-config.sh
        dest: /opt/rator/deployment/etcd-config/load-etcd-config.sh
        mode: 0755
      become: true
      become_method: sudo
      tags:
        - config
```

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

```paste below
fatal: [server]: FAILED! => {"changed": false, "checksum": "c1b955c231a37b92df49d26b32168a4fc9c17cf9", "msg": "Destination not writable"}
```
