### ISSUE TITLE
to_nice_yaml indentation not working as documentation

### ISSUE THREAD

**Issue by brsanche** [ansible/ansible#66932]
##### SUMMARY
to_nice_yaml indentation not working as mentioned in documentation 
https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Filters for formatting data

##### ANSIBLE VERSION

```paste below
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT

CentOS Linux release 7.7.1908 (Core)
3.10.0-1062.9.1.el7.x86_64 #1 SMP

##### STEPS TO REPRODUCE

The following Yaml has been defined:
```
es_config:
  node.name: "{{ computer_name }}"
  cluster.name: "infr0-elk0"
  cluster.initial_master_nodes:
    - elk0.logging0.infr0.XXX.io
    - elk1.logging0.infr0.XXX.io
    - elk2.logging0.infr0.XXX.io
  discovery.seed_hosts:
    - elk0.logging0.infr0.XXX.io
    - elk1.logging0.infr0.XXX.io
    - elk2.logging0.infr0.XXX.io
  network.host: "0.0.0.0"
  http.port: 9200
  node.data: true
  node.master: true
  bootstrap.memory_lock: false


The following variable with the to_nice_yaml filter is used in a jinja2 template:

{{ es_config | to_nice_yaml(indent=2) }}

```
##### EXPECTED RESULTS

```
node.name: "{{ computer_name }}"
  cluster.name: "infr0-elk0"
  cluster.initial_master_nodes:
    - elk0.logging0.infr0.XXX.io
    - elk1.logging0.infr0.XXX.io
    - elk2.logging0.infr0.XXX.io
  discovery.seed_hosts:
    - elk0.logging0.infr0.XXX.io
    - elk1.logging0.infr0.XXX.io
    - elk2.logging0.infr0.XXX.io
  network.host: "0.0.0.0"
  http.port: 9200
  node.data: true
  node.master: true
  bootstrap.memory_lock: false
```
##### ACTUAL RESULTS

The resulting file looks like this:
```
bootstrap.memory_lock: false
cluster.initial_master_nodes:
- elk0.logging0.infr0.XXX.io
- elk1.logging0.infr0.XXX.io
- elk2.logging0.infr0.XXX.io
cluster.name: infr0-elk0
discovery.seed_hosts:
- elk0.logging0.infr0.XXX.io
- elk1.logging0.infr0.XXX.io
- elk2.logging0.infr0.XXX.io
http.port: 9200
network.host: 0.0.0.0
node.data: true
node.master: true
node.name: elk0.logging0.infr0.XXX.io
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is a shortcoming with the underlying YAML library we use. PyYAML will indent keys from a dictionary past their parent, but does not do this with list items. The hyphen used to define a list item is always printed in alignment with the parent.

**Comment by brsanche** [comment]
I've also tested that without the list item, and it's not working as well.

yaml file

```
vars:
    example_config:
      host: test.example
      password: abcpasswd
      port: 443
      user: example

  tasks:

    - name: Copy configuration file
      template: src=conf.j2 dest=/root/config.yml

```

conf.j2 template file

```
{{ example_config | to_nice_yaml(indent=2) }}
```

config.yml result file

```
host: test.example
password: abcpasswd
port: 443
user: example
```

It only works when adding something like this on j2 template.

```
{{ example_config | to_nice_yaml | indent(2) }}
```

```
host: test.example
  password: abcpasswd
  port: 443
  user: example
```

Which is different usage from Ansible filters documentation.
