### ISSUE TITLE
win_domain_group "Unable to contact the server. This may be because this server does not exist"

### ISSUE THREAD

**Issue by SylvainMartel** [ansible/ansible#66954]
##### SUMMARY

Using win_domain_group with a WinRM connection returns 

> fatal: [<edited>]: FAILED! => {
    "changed": false,
    "created": false,
    "msg": "failed to retrieve initial details for group L_EXP_Administrators: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running."
}

It seems the Domain Controler is refusing the request.  My guess is that it's related to the "double-hop" problem and that the account used for remoting is thus not thrusted anymore.   

Running the command Get-ADGroup locally on the server works as expected.

Using the domain_username and domain_password parameters for the win_domain_group ressource gave the same error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_domain_group

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = None
  configured module search path = ['/home/<edited>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
 Windows 2016

##### STEPS TO REPRODUCE

```yaml
tasks:
  - name: Verification groupe AD
    win_domain_group:
      name: L_EXP_Administrators
      scope: domainlocal
      domain_server:  <edited>
      state: present
      domain_username: <edited>
      domain_password: "{{ hostvars['127.0.0.1']['ansible_user_password']}}"
```

##### ACTUAL RESULTS

```paste below
> fatal: [<edited>]: FAILED! => {
    "changed": false,
    "created": false,
    "msg": "failed to retrieve initial details for group L_EXP_Administrators: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running."
}
```
