### ISSUE TITLE
imgadm module - add the ability to create an image from an existing zone

### ISSUE THREAD

**Issue by blackwood821** [ansible/ansible#66960]
##### SUMMARY

The `imgadm` command on SmartOS supports creating an image from an existing zone by running a command such as `imgadm create -s /path/to/prepare-image-script <vm-uuid> name=<image-name> version=<image-version>`. I don't see a way to invoke that via the `imgadm` module. I think this would be much better than just running the command via the `command` or `shell` modules.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

imgadm

##### ADDITIONAL INFORMATION

This feature would be used to simplify the process of creating a new image from an existing zone. Here is an example task of how it could look:

```yaml
- name: create custom image from zone
  imgadm:
    vm_uuid: f27cc0f5-7fb6-ea0e-dc23-fbf1ef795d95
    state: created
    name: test_image
    version: 1.0
    prepare_image_script: /path/to/prepare-image-script
```
