### ISSUE TITLE
setup module failed on AIX servers

### ISSUE THREAD

**Issue by sadanand25** [ansible/ansible#66978]
##### SUMMARY

We are having ansible on Ubuntu server and we are making AIX as client.
we are planning for delete some files on AIX servers.   we able to ping servers from ubuntu server to AIX server. 

when we run playbook its gives Module failure error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
"module_stderr": "Shared connection to XX.XX.XX.XX closed.\r\n",
"module_stdout": "\r\n",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
```
##### ANSIBLE VERSION

```paste below


```

##### CONFIGURATION

```

root@devops:/home/ashwinij# ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
root@XXXX:/home/XXXXX# ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

```

##### OS / ENVIRONMENT

Server: Ubuntu 14.04.5 LTS
Client: AIX 7100-05-02-1832

##### STEPS TO REPRODUCE

```yaml
---
- name: Firstcheck
  hosts: "{{ HOSTNAME}}"
  become: true
  gather_facts: yes
  tasks:
   - name: printing echo
     command: echo {{ HOSTNAME }}
     register: echo

   - debug:
     var: echo.stdout
   - name: printing ip
     command: echo {{ ansible_host }}
     register: ip3

   - debug:
       var: ip3

   - name: seting facts
     set_fact: hostname="{{echo.stdout}}"
     register: output
     delegate_to: localhost

   - copy:
       dest: /home/XXX/back.txt
       content: |
                {{ hostname }}
     register: store
     delegate_to: localhost
   
   - debug:
       var: sedd

   - name: value finding
     shell: sh /home/XXXX/host.sh
     register: value1
     delegate_to: localhost

   - debug:
       var: value1

   - name: check last Backup status(checking hostname is present in the backup list or not )
     shell: cat /home/XXXXX/list.txt | grep -i {{ value1.stdout}}
     register: back
     delegate_to: localhost
     ignore_errors: yes

   - name: Mail Notification - Automated Archieve Log deletion
     mail:
       host: localhost
       port: 25
       to: asdas@asd.com
       from: adasa@asda.com
       subject: 'Automated Archieve log deletion Failed:  {{ HOSTNAME }} server is not in Backup list. '
       body: |
              Dear Team,

              Below mentioned server is not in Backup List.

              {{ HOSTNAME }} : {{ ansible_host }}
     delegate_to: 127.0.0.1
     tags: mail
     ignore_errors: true
     when: back.rc == 1

   - name: Grepping last backup date
     shell: cat /home/sdasdasdas/list.txt | grep -i {{ value1.stdout }} | awk -F " " '{print $2}'
     delegate_to: localhost
     register: result
     when: back.rc == 0

```

##### EXPECTED RESULTS

Playbook should run without module failure

##### ACTUAL RESULTS

```paste below
fatal: [XXXXXX]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "failed_modules": {
        "setup": {
            "ansible_facts": {
                "discovered_interpreter_python": "/usr/bin/python"
            },
            "failed": true,
            "module_stderr": "Shared connection to XXXXXXXXX closed.\r\n",
            "module_stdout": "\r\n",
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
            "rc": 1,
            "warnings": [
                "Platform aix on host XXXXX is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information."
            ]
        }
    },
    "msg": "The following modules failed to execute: setup\n"
}

```
