### ISSUE TITLE
proxmox_kvm linked clone fails because of format parameter

### ISSUE THREAD

**Issue by h3po** [ansible/ansible#67048]
##### SUMMARY
creating linked clone with `full: no` using proxmox_kvm fails because the parameter `format: qcow2` is forced set by proxmox_kvm
```
Unable to clone vm foohost from vmid 188=500 Internal Server Error: parameter 'format' not allowed for linked clones - b'{\"data\":null}'
```
I tried setting `format: none` but then I get
```
value of format must be one of: cloop, cow, qcow, qcow2, qed, raw, vmdk, got: none
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
proxmox_kvm

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = None
  configured module search path = ['/home/h3po/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/h3po/deployment-git/venv/lib/python3.8/site-packages/ansible
  executable location = /home/h3po/deployment-git/venv/bin/ansible
  python version = 3.8.1 (default, Jan  8 2020, 23:09:20) [GCC 9.2.0]
```
##### proxmox version: 6.1-5
```
{
  "data": {
    "version": "6.1-5",
    "keyboard": "de",
    "console": "vv",
    "release": "6.1",
    "repoid": "9bf06119"
  }
}
```

##### CONFIGURATION

```
no output
```

##### STEPS TO REPRODUCE

```yaml
    - name: create machines
      proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        clone: "{{ vm_template }}"
        name: "{{ inventory_hostname }}"
        vmid: "{{ vm_template_id }}"
        full: no
        node: "{{ vm_template_node }}"
    delegate_to: "{{ proxmox_api_jumphost }}"
```

##### EXPECTED RESULTS

I'm expecting proxmox_kvm to call `/api2/json/nodes/{node}/qemu/{vmid}/clone` without the `format` parameter as per the [api documentation](https://pve.proxmox.com/pve-docs/api-viewer/index.html): `Target format for file storage. Only valid for full clone`.
