### ISSUE TITLE
tags being applied to repeated roles

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#6705]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 1.6 (devel 2a976ac313) last updated 2014/03/26 10:47:10 (GMT -500)`

Git bisect indicates the issue was introduced in d327e3d11a3c7092327630541d01b04e8450b335
##### Environment:

Control: Mac OS, virtualenv, python 2.7.5

Target: N/A
##### Summary:

We have reusable roles called `app-webapp` and `app-proxy`.  These roles are parameterized to allow deployment of any one of our applications.

Our plays look similar to the following:

```
- name: Webapp Application deployments
  hosts: webapp
  connection: ssh
  sudo: yes
  tags:
    - applications
  roles:
    - role: app-webapp
      app_name: foo
      app_port: 5006
      tags:
        - foo

    - role: app-webapp
      app_name: bar
      app_port: 5014
      tags:
        - bar
```

As you can see, we call the role multiple times, one for each app, with unique tags per role.  Previous to d327e3d11a3c7092327630541d01b04e8450b335 the tags on each role were unique.  Now, the second role seems to include it's tag and the second role invocations tag.

The affect this has, is we used to be able to specify `-t foo` and have it only run the first role.  Now it runs both roles.
##### Steps To Reproduce:

Create a play similar to above where a role is called multiple times, each with a unique tag.

run ansible-playbook, perhaps just with --list-tasks and you will notice that all roles run, not just the one explicitly tagged
##### Expected Results:

Only the explicitly tagged role should run
##### Actual Results:

All invocations of the parameterized role are run.
