### ISSUE TITLE
os_server: volumes attachments are not updated

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible#67051]
##### SUMMARY
Trying to update the list of volumes (the `volumes` parameters) of an already existing server does not work.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_server

##### ANSIBLE VERSION
2.9.2 `python version = 3.7.5 (default, Nov 20 2019`

##### STEPS TO REPRODUCE

```yaml
- os_server:
    name: foo
    interface: internal
    region_name: BHS3
    boot_volume: root
    volumes: ['aaa', 'bbb', 'ccc']
    state: present
    terminate_volume: false
    flavor: "s1-8"
    availability_zone: nova
    network: "Ext-Net"
    security_groups: "default"
    auth: "{{ auth }}"
```

##### EXPECTED RESULTS
"ccc" volume must be attached to the "foo" server if it was not already.

##### ACTUAL RESULTS
No change is applied to the remote server. Ansible "green" output.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/openstack/os_server.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/openstack/os_server.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Shrews @cloudnull @dagnello @emonty @gtema @juliakreger @mnaser @odyssey4me @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Acronys1** [comment]
Exactly same problem with os_server_info.

With python2.7 no problem but with python3.x I got no volumes attachment.

openstacksdk 0.40.0 on both python version

**Comment by drzraf** [comment]
Same problem with, although not sure whether it's a regression or not:
```yaml
os_server_volume:
    state: present
    server: foo
    volume: vfoo
    device: /dev/sdd
    region_name: SGP1
```

If the volume already exists, the value for `device` is not changed and Ansible always shows `changed: false`.
