### ISSUE TITLE
vmware_guest needs to be able to set OVF Environment Transport

### ISSUE THREAD

**Issue by evilhamsterman** [ansible/ansible#67062]
##### SUMMARY
When deploying a VM to vSphere that can be configured using vApp properties (such as cloud-init type systems) you can set the properties in vmware_guest and they get set correctly, however you still have to select the "OVF Environment Transport" otherwise the values are not passed to the VM. 

https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vm_admin.doc/GUID-14A25C25-A6F8-4818-9D0C-C0247C0672FA.html

This has been mentioned in PR #53321 and the issue #41616 but it appears the person who filed those bugs never followed up and they were closed automatically. 

I'm filing this as a bug rather than a feature request because without this functionality the vApp properties are not very useful since the VM won't be able to read them. The only way that it works is if you are cloning from a template which already has the transport mode set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```paste below
ansible 2.9.4
  config file = /home/dmills/Development/ansible/ansible.cfg
  configured module search path = ['/home/dmills/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmills/Development/ansible/.venv/lib/python3.7/site-packages/ansible
  executable location = /home/dmills/Development/ansible/.venv/bin/ansible
  python version = 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008]

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/dmills/Development/ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/dmills/Development/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/dmills/Development/ansible/ansible.cfg) = /tmp
DEFAULT_CALLBACK_WHITELIST(/home/dmills/Development/ansible/ansible.cfg) = ['timer', 'yaml']
DEFAULT_FORKS(/home/dmills/Development/ansible/ansible.cfg) = 10
DEFAULT_MANAGED_STR(/home/dmills/Development/ansible/ansible.cfg) = This file is managed by IT with Ansible. 
DEFAULT_STDOUT_CALLBACK(/home/dmills/Development/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/dmills/Development/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/dmills/Development/ansible/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT
Ubuntu 19.10
vSphere 6.7

##### STEPS TO REPRODUCE
Try and deploy a VM using vmware_guest with vapp_properties defined

```yaml
  - name: Deploy RancherOS VMs
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_password }}"
      name: "{{ inventory_hostname_short }}"
      datacenter: DC
      folder: DC/vm/Production/Source Control/gitlab-ci
      cluster: Production
      state: poweredon
      guest_id: other4xLinux64Guest
      disk:
        - size_gb: 20
          type: thin
          datastore: datastore
      hardware:
        memory_mb: 4096
        num_cpus: 2
        boot_firmware: bios
      cdrom:
        type: iso
        iso_path: "[datastore] rancher/rancheros-vmware-autoformat.iso"
      networks:
        - name: Primary
          device_type: vmxnet3
      vapp_properties:
        - id: guestinfo.hostname
          value: rancheros-vm
       wait_for_ip_address: yes
    delegate_to: localhost
```

##### EXPECTED RESULTS
The VM will deployed and read the values from the vapp_properties to configure itself

##### ACTUAL RESULTS
The VM is deployed and the vapp_properties are set, but they are unavailable to the VM to use to configure until I manually set the OVF Environment Transport to either ISO or VMware Tools
