### ISSUE TITLE
ansible 2.9 - ipa_user module with ssh keys will error out with no modifications to be performed

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#67075]
##### SUMMARY
Using ssh keys with the ipa_user module will sometimes run into this "error"
```
"msg": "response user_mod: no modifications to be performed"
```
I've noticed that this will mostly happen with rsa4096 or rsa8192 keys.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipa_user

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.3
  config file = /home/user/ansible/iam/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/home/user/ansible/iam/ansible.cfg) = ['/home/user/ansible/iam/roles']
RETRY_FILES_ENABLED(/home/user/ansible/iam/ansible.cfg) = False
```

##### OS / ENVIRONMENT
host_os: fedora31 / rhel7
target_os: rhel8

##### STEPS TO REPRODUCE
Task:
```
- name: Administer technical users in IdM with ssh-key
  ipa_user:
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    displayname: "{{ item.displayname | default(item.name) }}"
    givenname: "{{ item.fname | default('FirstName') }}"
    sn: "{{ item.sname | default('SureName') }}"
    mail: "{{ item.mail | default('') }}"
    sshpubkey: "{{ item.sshpubkeys }}"
    ipa_user: "{{ idm_admin }}"
    ipa_pass: "{{ idm_admin_pass }}"
    ipa_host: "{{ idm_host }}"
    validate_certs: false
  loop: "{{ idm_technical_users }}"
  when: item.sshpubkeys is defined and not item.gidnumber is defined
```
Inventory user definition:
```
  - name: test
    state: present
    displayname: test user
    fname: test
    sname: user
    mail: test.user@domain.tld
    sshpubkeys:
      - 'ssh-rsa AAAA0000 test@host1.domain.tld' # noqa 204
      - 'ssh-rsa AAAA1111 test@host2.domain.tld' # noqa 204
```

##### EXPECTED RESULTS
If the state described in the .yml == the state in ipa, return ok.

##### ACTUAL RESULTS
```
failed: [idm-01.lx.domain.tld] (item={'name': 'test', 'state': 'present', 'displayname': 'test user', 'fname': 'test', 'sname': 'user', 'mail': 'test.user@domain.tld', 'sshpubkeys': ['ssh-rsa AAAA0000 test@host1.domain.tld', 'ssh-rsa AAAA1111 test@host2.domain.tld']}) => {"ansible_loop_var": "item", "changed": false, "item": {"displayname": "test user", "fname": "test", "mail": "test.user@domain.tld", "name": "test", "sname": "user", "sshpubkeys": ['ssh-rsa AAAA0000 test@host1.domain.tld', 'ssh-rsa AAAA1111 test@host2.domain.tld'], "state": "present"}, "msg": "response user_mod: no modifications to be performed"}
```
