### ISSUE TITLE
aws_s3 should support putting content without filesystem access

### ISSUE THREAD

**Issue by onitake** [ansible/ansible#67086]
##### SUMMARY

The aws_s3 module currently only supports PUTting objects from local files.
According to [the documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Object.put), the boto3 S3 module also supports passing the content body directly from a variable, without doing a roundtrip to disk.

It would be very useful to add a `content` parameter (or similar) that accepts the S3 object's content directly. This would also allow rendering Jinja2 templates into an S3 object.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

aws_s3

##### ADDITIONAL INFORMATION

```yaml
- name: Simple PUT operation from a template file
  aws_s3:
    bucket: mybucket
    object: /object.yml
    content: "{{ lookup('template', 'templates/object.yml.j2') }}"
    mode: put
```
