### ISSUE TITLE
vmware_drs_group does not update group - it overwrites

### ISSUE THREAD

**Issue by pertoft** [ansible/ansible#67087]
##### SUMMARY
When creating a vm group with "vmware_drs_group" it works as expected, but when another host is added to the group, it overwrites the existing ones.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/cloud/vmware/vmware_drs_group.py

##### ANSIBLE VERSION

```
pto:ansible pto$ ansible --version
ansible 2.9.4
  config file = /Users/pto/infrastructure/ansible/ansible.cfg
  configured module search path = ['/Users/pto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pto/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /Users/pto/Library/Python/3.8/bin/ansible
  python version = 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) [Clang 6.0 (clang-600.0.57)]
pto:ansible pto$
```
Also tested from latest dev release - same results.

##### CONFIGURATION

```
pto:ansible pto$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/pto/infrastructure/ansible/ansible.cfg) = ['/Users/pto/infrastructure/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/Users/pto/infrastructure/ansible/ansible.cfg) = ['/Users/pto/infrastructure/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/pto/infrastructure/ansible/ansible.cfg) = /Users/pto/.vault
HOST_KEY_CHECKING(/Users/pto/infrastructure/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/pto/infrastructure/ansible/ansible.cfg) = ['vmware_vm_inventory']
```

##### OS / ENVIRONMENT

Macos Catalina

##### STEPS TO REPRODUCE

```yaml
---
- name: Provision VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - vault.yml
    
  vars: 
    vcenter_hostname: vc01.xxx.dk
    vcenter_folder: "/vm/Test/"
    vmdatacenter: 'DC1'
    vmcluster: 'Cluster1'

  tasks:
    - name: "Create DRS VM group 1"
      delegate_to: localhost
      vmware_drs_group:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          cluster_name: "{{ vmcluster }}"              
          # datacenter_name: "{{ vmdatacenter }}"
          group_name: "group-test"
          vms:
            - "k8s-node01.test.netic.dk"
            - "k8s-node02.test.netic.dk"
          state: present
      register: results1

    - debug: 
        var: results1
        
    - name: "Create DRS VM group 2"
      delegate_to: localhost
      vmware_drs_group:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          cluster_name: "{{ vmcluster }}"              
          # datacenter_name: "{{ vmdatacenter }}"
          group_name: "group-test"
          vms:            
            - "k8s-node03.test.netic.dk"
          state: present
      register: results2

    - debug: 
        var: results2
```

##### EXPECTED RESULTS

drs vm group-test shoud contain:
k8s-node01.test.netic.dk
k8s-node02.test.netic.dk
k8s-node03.test.netic.dk

##### ACTUAL RESULTS

drs vm group-test contains:
k8s-node03.test.netic.dk

```paste below
pto:ansible pto$ ansible-playbook playbooks/vmware-configure-drs_group_test.yml
[WARNING]: Unable to parse /Users/pto/infrastructure/ansible/inventory.yml as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [Provision VM from template] *********************************************************************************************************************************************************************************************************************************

TASK [Create DRS VM group 1] **************************************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "results1": {
        "changed": true,
        "failed": false,
        "msg": "Created vm group group-test successfully",
        "result": {
            "Netic Internal vSAN": [
                {
                    "group_name": "group-test",
                    "type": "vm",
                    "vms": [
                        "k8s-node01.test.netic.dk",
                        "k8s-node02.test.netic.dk"
                    ]
                }
            ]
        }
    }
}

TASK [Create DRS VM group 2] **************************************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [debug] ******************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "results2": {
        "changed": true,
        "failed": false,
        "msg": "Updated vm group group-test successfully",
        "result": {
            "Netic Internal vSAN": [
                {
                    "group_name": "group-test",
                    "type": "vm",
                    "vms": [
                        "k8s-node03.test.netic.dk"
                    ]
                }
            ]
        }
    }
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

pto:ansible pto$
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/vmware/vmware_drs_group.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_drs_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @Tomorrow9 @goneri @karstenjakobsen @lparkes @pgbidkar @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@pertoft, just so you are aware we have a dedicated Working Group for vmware.
You can find other people interested in this in `#ansible-vmware` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mariolenz** [comment]
I think the module works as expected. You see, you don't "add" VMs to a DRS group- you define what the DRS group should look like. So
```
vms:
  - "k8s-node03.test.netic.dk"
```
means "I want group-test to contain exactly k8s-node03.test.netic.dk". Like a lot of other ansible modules, it's declarative.

@karstenjakobsen You're the original author, what do you say?

**Comment by pertoft** [comment]
How would you then add multiple vms to the drs group the “ansible” way with
tasks per host?

I am developing a script which pulls a list of vms from a folder in
vsphere. Then add each host to a in-memory inventory using add-host.

Next I run a play on the newly created group where each vm will have its
own set of tasks.
Then I extract the node Id and check if it’s divisible by two and assign it
to one of two drs availability groups. Finally, I assign the van by using
the vmware_drs_group and this fail as there is only one host in the group
when the playbook is done.

I tried two other approaches also;
1) using VMware dynamic inventory but I got stuck as it wasn’t possible to
fetch only a single folder
2) did everything in one play on local host but I was not able to regex the
hostnames/hostid, check dividable by 2 and sort the the host in two lists
for later to add them using vmware_drs_group.

Any suggestions?



tir. 4. feb. 2020 kl. 18.48 skrev Mario Lenz <notifications@github.com>:

**Comment by mariolenz** [comment]
> Next I run a play on the newly created group where each vm will have its own set of tasks.
> Then I extract the node Id and check if it’s divisible by two and assign it to one of two drs availability groups.

You had me at "I extract the node Id and check if it’s divisible by two", that sounds too complicated for me :-P

Actually, we don't discover VMs at the moment. We define them (and our ESXi hosts, clusters ...) in our inventory and can therefore define what DRS groups they should be part of.

Maybe ansible just isn't the right tool for you? For me, ansible is a (declarative) configuration management tool. If you want to develop a "script" that just does stuff, maybe you should look at something else. We use PowerCLI for the problems that aren't really suited to be solved with ansible, for example.

> I tried two other approaches also;
> 1) using VMware dynamic inventory but I got stuck as it wasn’t possible to fetch only a single folder

I think that might be worth a feature request: Restrict the dynamic inventory to a VM folder (or a cluster, a datastore...).

> 2) did everything in one play on local host but I was not able to regex the hostnames/hostid, check dividable by 2 and sort the the host in two lists for later to add them using vmware_drs_group.

As I've said above, "check dividable by 2" sounds too complicated for me. But that's just my personal opinion, let's see what @Akasurde @Tomorrow9 @goneri @karstenjakobsen @lparkes @pgbidkar @warthog9 have to say.

**Comment by karstenjakobsen** [comment]
@pertoft The module works as expected. 

I went through the same thoughts and problems you are facing now, and for a brief period i played around with adding an `append` and `remove` options to the `vmware_drs_group`. But that only resulted in more headaches since we also have the usual `state: present or absent`

What i ended up doing instead, was assigning all my vm hosts to groups using a key with `group_by`. Here is an example:

```
---
# -----------------------------------------------------------
# Sync DRS
# -----------------------------------------------------------
- hosts: all
  gather_facts: False

  tasks:

    - name: Group all hosts by drs_group_name
      group_by:
        key: "{{cluster_name}}_zone{{datazone}}_vms"
      when:
        - "vsphere_vm__state != 'absent'"
```

This way all my vm hosts were divided into groups:

`dc1_zone1_vms`,`dc1_zone2_vms`,`dc1_zone3_vms`
 and
`dc2_zone1_vms`,`dc2_zone2_vms`,`dc2_zone3_vms`

and then i could loop through a task, creating all the drs groups:

Example:
```
tasks:
  - name: "Create DRS VM group 1"
    delegate_to: localhost
    vmware_drs_group:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        cluster_name: "{{ vmcluster }}"              
        # datacenter_name: "{{ vmdatacenter }}"
        group_name: "{{item}}"
        vms: "{{ groups[item] }}"
        state: present
    register: results1
    with_items:
      - dc1_zone1_vms
      - dc1_zone2_vms
      - dc1_zone3_vms
      - dc2_zone1_vms
      - dc2_zone2_vms
      - dc2_zone3_vms
```

Hope this helps.

**Comment by an-t-oine** [comment]
i use this module, and it well update DRS groups.
BUT, it is very very slow !!!

I have a DRS VMs group larger than 300 VMs.
It takes around 30 minutes to add only one VM.

what i do is:

First, i gather DRS rules info :

`- name: Gather DRS info
    vmware_drs_rule_info:
      hostname: "{{ PRD_esx_guest_vcenter }}"
      username: "{{ PRD_esx_guest_username }}"
      password: "{{ PRD_esx_guest_password }}"
      cluster_name: "{{ PRD_esx_guest_cluster }}"
      validate_certs: false
    delegate_to: localhost
    register: _cluster_drs_info`

then i create a new variable (array) of the VMs that are already in the DRS group + my new VM that i want to add in this group:

`- name: Register VMs in linux_drs_vms variable
    set_fact:
      linux_drs_vms: "{{ _cluster_drs_info.drs_rule_info.CLUSTER1[1].rule_vms + [ PRD_esx_guest_vm_name ] }} "`

then, i use this variable to the vmware_drs-group module to add all the VMs from this variable to the existing DRS group.
For VMs that were already in this group. Nothing happend.
For the new VM, it is added to the group.

But, i repeat, it is very very slow.

`- name: Add the new VM in the DRS group Linux_Vms
  delegate_to: localhost
  vmware_drs_group:
    hostname: "{{ PRD_esx_guest_vcenter }}"
    password: "{{ PRD_esx_guest_password }}"
    username: "{{ PRD_esx_guest_username }}"
    cluster_name: "{{ PRD_esx_guest_cluster }}"
    datacenter_name: "{{ PRD_esx_guest_datacenter }}"
    validate_certs: false
    group_name: "Linux_Vms"
    state: present
    vms: "{{ item }}"
  loop:
    - "{{ linux_drs_vms }}"`
 
that's work.

**Comment by an-t-oine** [comment]
i use this module, and it well update DRS groups.
BUT, it is very very slow !!!

I have a DRS VMs group larger than 300 VMs.
It takes around 30 minutes to add only one VM.

what i do is:

First, i gather DRS rules info :

```
- name: Gather DRS info
    vmware_drs_rule_info:
      hostname: "{{ PRD_esx_guest_vcenter }}"
      username: "{{ PRD_esx_guest_username }}"
      password: "{{ PRD_esx_guest_password }}"
      cluster_name: "{{ PRD_esx_guest_cluster }}"
      validate_certs: false
    delegate_to: localhost
    register: _cluster_drs_info
```


then i create a new variable (array) of the VMs that are already in the DRS group + my new VM that i want to add in this group:

```
- name: Register VMs in linux_drs_vms variable
    set_fact:
      linux_drs_vms: "{{ _cluster_drs_info.drs_rule_info.CLUSTER1[1].rule_vms + [ PRD_esx_guest_vm_name ] }} "
```

then, i use this variable to the vmware_drs-group module to add all the VMs from this variable to the existing DRS group.
For VMs that were already in this group. Nothing happend.
For the new VM, it is added to the group.

But, i repeat, it is very very slow.

```
- name: Add the new VM in the DRS group Linux_Vms
  delegate_to: localhost
  vmware_drs_group:
    hostname: "{{ PRD_esx_guest_vcenter }}"
    password: "{{ PRD_esx_guest_password }}"
    username: "{{ PRD_esx_guest_username }}"
    cluster_name: "{{ PRD_esx_guest_cluster }}"
    datacenter_name: "{{ PRD_esx_guest_datacenter }}"
    validate_certs: false
    group_name: "Linux_Vms"
    state: present
    vms: "{{ item }}"
  loop:
    - "{{ linux_drs_vms }}"
```
 

that's work.
