### ISSUE TITLE
How to run  a task on all hosts except the last host

### ISSUE THREAD

**Issue by Mamosa** [ansible/ansible#67096]
##### SUMMARY
I have a task in my playbook that i need to run on all of the hosts in my inventory except the last host. This host could change over time so i would not know the name of the host to exclude it using its name.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
identify last host in inventory

##### ADDITIONAL INFORMATION
This feature would be used for tasks that need to be run on all hosts in an inventory except the final host on the inventory list.

As an example the task below copys a data structure to a file and adds a comma seperator. This task needs to run on all hosts in the inventoy except the final host because the final host does not require a comma.

```yaml
- name: write to file
  lineinfile:
    dest: "../roles/cisco_compliance/compliance-results/{{ date }}.json"
    line: "{{ compliance_results | to_json }},"
    create: yes
    insertbefore: EOF
```
