### ISSUE TITLE
tower_job_launch does not set credential against AWX 9.1.1

### ISSUE THREAD

**Issue by ephracis** [ansible/ansible#67098]
##### SUMMARY

When using the module `tower_job_launch ` against AWX 9.1.1 the job does not get the correct credential. This worked previously in AWX 2.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_job_launch

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /Users/chbr/repos/work/auxiliary/training/bos/ansible.cfg
  configured module search path = ['/Users/chbr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/Users/chbr/repos/work/components/awx/ansible.cfg) = True
ANY_ERRORS_FATAL(/Users/chbr/repos/work/components/awx/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/chbr/repos/work/components/awx/ansible.cfg) = ['profile_tasks', 'full_skip']
DEFAULT_HOST_LIST(/Users/chbr/repos/work/components/awx/ansible.cfg) = ['/Users/chbr/repos/work/components/awx/.vagrant/provisioners/ansible/inventory']
DEFAULT_STDOUT_CALLBACK(/Users/chbr/repos/work/components/awx/ansible.cfg) = debug
RETRY_FILES_ENABLED(/Users/chbr/repos/work/components/awx/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/Users/chbr/repos/work/components/awx/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT

- AWX on CentOS 7 and CentOS 8
- Ansible control machine on macOS Catalina and CentOS 7

##### STEPS TO REPRODUCE

Deploy AWX and configure it with a template, an inventory and a credential. The template has the property `ask_credential` and `ask_inventory` set.

Verify that the AWX template can be launched via the web interface when selecting the proper inventory and credential.

```yaml
# example from https://docs.ansible.com/ansible/latest/modules/tower_job_launch_module.html
- name: Launch a job with inventory and credential
  tower_job_launch:
    job_template: "My Job Template"
    inventory: "My Inventory"
    credential: "My Credential"
```

##### EXPECTED RESULTS

The job is launched with the credential `My Credential`.

##### ACTUAL RESULTS

The job is launched without any credential.
