### ISSUE TITLE
To Remove NIC from backend of a AZURE Load Balancer using azure_rm_networkinterface module

### ISSUE THREAD

**Issue by rbharadwaj16** [ansible/ansible#67092]
##### SUMMARY

As part of azure_rm_networkinterface, there is a option to add NIC to backend of Azure Load Balancer.

However, we cannot remove it through Ansible. Request the team to add this feature.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Ansible Module: azure_rm_networkinterface

##### ADDITIONAL INFORMATION

This will enable end to end management of VM's attaching/de-attaching them to a Azure Load balancer. There are situations where, we need VM to be part of a LB for a specific purpose/specific time and then remove it from LB. 
A typical use case would be, attach a VM to LB, perform configuration changes within VM, detach it from Outbound Load balancer.  (All done through Ansible)

```yaml
Below is my playbook to attach the NIC to backend pool of the LB:
---

- hosts: localhost
  gather_facts: yes
  become: yes
  
  
  tasks:
   - name: Attach a NIC to LB
     azure_rm_networkinterface:
       auth_source: msi
       name: "{{ nic_name }}"
       resource_group: "{{ nic_rg }}"
       virtual_network: "{{ nic_vnet }}"
       subnet_name: "{{ nic_sb }}"
       ip_configurations:
         - name: ipconfig1
           primary: True
         - name: ansible_lb_attach_config
           load_balancer_backend_address_pools:
            - name: "{{ nic_backend }}"
              load_balancer: "{{ nic_lb }}"
```
