### ISSUE TITLE
Unable to append a dictionary to a list of dictionarys

### ISSUE THREAD

**Issue by Mamosa** [ansible/ansible#67097]
##### SUMMARY
When i try to append a new dictionary to a list of existing dictionaries it does not append it overwrites the existing data.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dictionary append

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = None
  configured module search path = ['/home/shirtclr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /etc/venv/ansible/lib/python3.6/site-packages/ansible
  executable location = /etc/venv/ansible/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below
no output
```

##### OS / ENVIRONMENT

```yaml

- name: create dictionary
  set_fact:
    hosts:
       - hostname1:
             - "Test1"
             - "Pass"
             - "This has passed"

- name: build pass case
  set_fact:
    hostname:
      - "Access Control"
      - "Pass"
      - ""

- name: add to existing list of data structures
  set_fact:
    hosts: "{{ hosts| combine( hostname) }}"

```

##### EXPECTED RESULTS

I expect the new dictionary to be combined/appended onto the existing list of dictionaries

```paste below
    hosts:
       - hostname1:
             - "Test1"
             - "Pass"
             - "This has passed"
        - hostname:
             - "Access Control"
             - "Pass"
             - ""
```

##### ACTUAL RESULTS

The code runs with no errors, its just overwrites the existing list of dictionaries with the new dictionary instead of appending to it.

```paste below

```
