### ISSUE TITLE
git_url Unsupported parameter

### ISSUE THREAD

**Issue by pmartindev** [ansible/ansible#67106]
##### SUMMARY

When trying to download an artifact from a url using git_url, I am given an error for an unsupported status_code parameter. This contradicts the [documentation](https://docs.ansible.com/ansible/latest/modules/get_url_module.html
).

This is the task snippet:
```
- name: Download Artifact
  get_url:
    url: https://api.enterprise.apigee.com/v1/organizations/{{ organization }}/apis/{{ proxy_name }}/revisions/{{ revision_number }}
    url_username: "{{ username }}"
    url_password: "{{ password }}"
    dest: "{{ artifact_path }}"
    force_basic_auth: yes
    # status_code: 200  # 200 is returned for successful download
  register: add_application_response
```

And here is the error:

```
TASK [Download Artifact] *********************************************************************************************************************************************************************************************************************************
Tuesday 04 February 2020  16:57:36 -0600 (0:00:00.035)       0:00:01.185 ****** 
Tuesday 04 February 2020  16:57:36 -0600 (0:00:00.035)       0:00:01.184 ****** 
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Unsupported parameters for (get_url) module: password, status_code, user Supported parameters include: attributes, backup, checksum, client_cert, client_key, content, delimiter, dest, directory_mode, follow, force, force_basic_auth, group, headers, http_agent, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, sha256sum, src, timeout, tmp_dest, unsafe_writes, url, url_password, url_username, use_proxy, validate_certs'


```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```
ansible 2.9.3
  config file = /Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg
  configured module search path = ['/Users/prestonmartin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.3/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Dec 27 2019, 18:05:50) [Clang 10.0.0 (clang-1000.11.45.5)]

```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles', 'changes']
DEFAULT_ROLES_PATH(/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg) = ['/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/vendor', '/Users/prestonmartin/Doc
DEFAULT_STDOUT_CALLBACK(/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg) = yaml
DEFAULT_VERBOSITY(/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg) = 0
RETRY_FILES_ENABLED(/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg) = False
TAGS_SKIP(/Users/prestonmartin/Documents/Programming/Stelligent/wells-fargo-apigee-cicd-poc/ansible/ansible.cfg) = ['todo', 'install_only']
```

##### OS / ENVIRONMENT

macOs High Sierra Version 10.13.6
