### ISSUE TITLE
ovirt_snapshot has no option for multidisk machines

### ISSUE THREAD

**Issue by dhilst** [ansible/ansible#67110]
##### SUMMARY
I have a VM with two disks, one of them is a kind of cache. I use this machine for testing installations so the idea is the installation is rolled back to beginning (but downloaded packages keep in cache (a separated disk that is not part of the snapshot))

When I restore a snapshot from the Web UI it asks what I want disks I want to provide to the restored VM.

##### ISSUE TYPE
Provide an option to support multidisk restoring 

##### COMPONENT NAME
ovirt_snapshot module

##### ADDITIONAL INFORMATION

I'm running ansible 2.8 and 2.9 (2.8 when on el7)

```yaml
    - name: Restore snapshot
      ovirt_snapshot:
        vm_name: "{{ vm }}"
        auth:
          insecure: yes
          url: https://rhv.local.versatushpc.com.br/ovirt-engine/api
          username: admin@internal
          password: 'xxx'
        state: restore
        snapshot_id: '{{ ovirt_snapshots[0].id }}'
      delegate_to: localhost
      retries: 10
      delay: 3
      register: restore_snapshot
      until: not restore_snapshot.failed
      # provide something like this
      # additional_disks: "mymachine_disk2"
   

```
