### ISSUE TITLE
Raise error in `ansible-galaxy collection build` if readme in build_ignore

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible#67130]
##### SUMMARY
Because https://galaxy.ansible.com will reject collections that do not have an expected README file, the command `ansible-galaxy collection build` command should error if specified readme file is inside the list `build_ignore` inside `galaxy.yml`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/cli/galaxy.py 

##### ADDITIONAL INFORMATION

Example `galaxy.yml` file that caused me to hit this:

```yaml
namespace: alancoding
name: deps
version: 1.0.1
readme: README.md
authors:
- your name <example@domain.com>
description: your collection description
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies:
  alancoding.basic: 0.0.5
  awx.awx: ">=8.0.0"
  devoperate.base: 0.1.0
  crivetimihai.workstation: 1.0.12
  dynatrace_innovationlab.collection: 1.0.0
  ganeshrn.test: 1.0.0
  debops.debops: 1.1.4
  cjsteel.development_environment: 1.2.1
  xlab_si.sesame: 1.0.0
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore:
- target
- README.md
- LICENSE
- Makefile
- '*.tar.gz'
```

Steps:

 - run `ansible-galaxy collection build`
 - go to https://galaxy.ansible.com
 - go to my content
 - upload file

Import fails

![Screen Shot 2020-02-05 at 11 04 33 AM](https://user-images.githubusercontent.com/1385596/73859647-5a4aa100-4808-11ea-83b5-401dc0ca8220.png)

The issue is self-evident from the `galaxy.yml` file. It specifies a README.md file, but then excludes it from the included files.

If these conditions are met, then the `ansible-galaxy collection build`  command could safely exit with an error, which will make for a nicer user experience than waiting until the import step to error.
