### ISSUE TITLE
htpasswd module should allow hash specific configuration parameters

### ISSUE THREAD

**Issue by dnmvisser** [ansible/ansible#67146]
##### SUMMARY

The htpasswd module uses passlib for its crypto operations. Most of the algorithms that passlib offers accept custom parameters, such as number of rounds, salt, etc. For instance https://passlib.readthedocs.io/en/stable/lib/passlib.hash.argon2.html#interface. There is currently no way of using those through the htpasswd module.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

htpasswd
##### ADDITIONAL INFORMATION

Next to `crypt_scheme`, an extra parameter `scheme_opts` could be introduced, which is a dict with specific configuration for the chosen scheme:

```yaml
- name: Populate SMTP password file for Dovecot
  htpasswd:
    path: /etc/dovecot/passwords
    name: admin
    password: hackme
    crypt_scheme: bcrypt
    scheme_opts:
      rounds: 16
```
