### ISSUE TITLE
Property spread notation for Ansible

### ISSUE THREAD

**Issue by rinormaloku** [ansible/ansible#67161]
##### SUMMARY
Looping through a list of items and passing those to a role (using `include_role`) requires to store the items into a variable (by default `item`) and then requires changes in the role to use the properties such as `" {{ item.name }}"`.

**The drawback here is that the role will either be optimized to work with lists or with items. But not both.**

#### Visualizing with an example of how it works now
Below we have a playbook that passes to a role a list of items:
```yaml
- name: Playbook
  hosts: localhost
  connection: local
  tasks:
  - name: loop through roles
    with_items: 
      - { name: John Doe,  greeting: Hello }
      - { name: Jane Doe,  greeting: Hola }
    include_role: 
      name: greeting_role
 ```

To make use of those items we need to prepend the variable names with `item` in the role (effectively breaking backward compatibility, if this role is being used by other playbooks):
```yaml
- name: Friendly greeting
  debug: 
    msg: "{{ item.name }} says {{ item.greeting }}"
```

This can be improved if we borrow Property spread notation from JavaScript (made famous from React). Where instead of passing properties one by one as shown below:
```
<Modal a={props.a} b={props.b} title='Modal heading' animation={false}>
```
We can simply spread the props object:
```
<Modal {...props} title='Modal heading' animation={false}> 
```
Both options are equivalent. Below we have an example of how this could look in Ansibe:

#### Visualizing with an example of how Property spread property would be used:

The role would be kept as-is i.e. no need to prepend `item` for every property:
```yaml
- name: Friendly greeting
  debug: 
    msg: "{{ name }} says {{ greeting }}"
```
And in the playbook the property spread property would be used:
```yaml
- name: Playbook
  hosts: localhost
  connection: local
  tasks:
  - name: loop through roles
    with_items: 
      - { name: John Doe,  greeting: Hello }
      - { name: Jane Doe,  greeting: Hola }
    include_role: 
      name: greeting_role
      spread: {{ item }}
```

Benefits:
- The role is optimized for both single-items and for lists.
- Easy and clean.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Property spread property?

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rinormaloku** [comment]
Found out that there is an alternative instead of updating the role, by assigning variables directly in playbook:
```
    include_role: 
      name: greeting_role
    vars: 
      name: "{{ item.name }}"
      greeting: "{{ item.greeting }}"
```

Though this for objects with many properties would be much cleaner to the eye by using the 'spread' property
