### ISSUE TITLE
Use of wildcard in variable with ios_config module

### ISSUE THREAD

**Issue by Mamosa** [ansible/ansible#67180]
##### SUMMARY
I need to be able to use a wildcard symbol in the lines section of the ios_config module. I am trying to compare a line of config to a line stored in a variable, however the ip address at the end of the config may change depending on the switch or router. 

for example if i have 

ip address 10.1.1.1
 on one switches configuration and on another i have 

ip address 10.1.1.2

i would like to be able to store 

ip address .*

in a variable and check against that and have it match both switches config.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ios_config

##### ADDITIONAL INFORMATION
I need to be able to use a wildcard symbol in the lines section of the ios_config module. I am trying to compare a line of config to a line stored in a variable, however the ip address at the end of the config may change depending on the switch or router. 

for example if i have 

ip address 10.1.1.1
 on one switches configuration and on another i have 

ip address 10.1.1.2

i would like to be able to store 

ip address .*

in a variable and check against that and have it match both switches config.

```yaml
vars
  ios_hostname:
    - hostname .*

tasks:
  - name: check host name
     ios_config:
       lines: "{{ ios_hostname }}"
     check_mode: true
     register: check_output

```
