### ISSUE TITLE
openssh_keypair: check_mode should return public key

### ISSUE THREAD

**Issue by joernheissler** [ansible/ansible#67185]
Hello,

##### SUMMARY
When running in check mode, the `openssh_keypair` module returns `"public_key": {}`.
Can the module please return the current key, at least if no changes would be required?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`openssh_keypair`

##### ANSIBLE VERSION

2.9.4

##### STEPS TO REPRODUCE

Run that once without and then with check mode enabled:

```yaml
- name: create key
  openssh_keypair:
    path: /root/.ssh/somekey
  register: somevar
```
##### EXPECTED RESULTS

I expect `somevar.public_key` to contain the public key.

##### ACTUAL RESULTS

```paste below
ok: [somehost] => changed=false
  comment: ''
  filename: /root/.ssh/somekey
  fingerprint: ''
  public_key: {}
  size: 256
  type: ed25519
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/crypto/openssh_keypair.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssh_keypair.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @MarkusTeufelberger @Shaps @Spredzy @Xyon @felixfontein @lolcube @puiterwijk @resmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tpo** [comment]
Ugly (created by Golum Sysadmin) temporary work-around:
```
- name: Generate an OpenSSH keypair for joedoe
  openssh_keypair:
    path: /home/joedoe/.ssh/id_rsa
  register: key

- name: Get public key
  command: cat /var/joedoe/.ssh/id_rsa.pub
  changed_when: false # never changes anything
  check_mode: no # do run in check mode!
  register: key_pub
  when: ansible_check_mode

- set_fact:
    public_key: "{{ key.public }}"
  when: not ansible_check_mode
#
- set_fact:
    public_key: "{{ key_pub.stdout }}"
  when: ansible_check_mode
```

-> public key will be in `public_key`. **ATTENTION** might be empty when not created yet.

**Comment by clarsen** [comment]
The `cat` command will give you the key comment as well, while `openssh_keypair` gives you just the key.  If you store the public_key in a local file and are using --check periodically to ensure your repository config is in sync with the remote system, this is an adjusted approach (i.e. always using cat to grab the public key) so that you won't get `changed` warnings in check mode:

```yaml
- name: Generate an OpenSSH keypair for joedoe
  openssh_keypair:
    path: /home/joedoe/.ssh/id_rsa
  register: key

- name: Get public key
  command: cat /var/joedoe/.ssh/id_rsa.pub
  changed_when: false # never changes anything
  check_mode: no # do run in check mode!
  register: key_pub

- set_fact:
    public_key: "{{ key_pub.stdout }}"
```
