### ISSUE TITLE
pip: false positive [DEPRECATION WARNING]: Invoking "pip" only once while using a loop via squash_actions

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#67190]
##### SUMMARY

> [DEPRECATION WARNING]: Invoking "pip" only once while using a loop via
> squash_actions is deprecated. Instead of using a loop to supply multiple items
> and specifying `name: "{{ item }}"`, please use `name: ['pip', 'setuptools',
> 'pbr']` and remove the loop. This feature will be removed in version 2.11.
> 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pip

##### ANSIBLE VERSION

```paste below
2.10.devel
```

##### STEPS TO REPRODUCE

```yaml
    - name: Install python YAML module
      pip:
        name: pyyaml
        extra_args: "{{ item }}"
      with_items:
        - "--user"
        - ""
      ignore_errors: true
```

##### EXPECTED RESULTS
No warning should be seen. Warning implementation was incorrect as it assumed that if you loop on pip tasks you loop for packages.
