### ISSUE TITLE
vmware_host_firewall_manager: #63567 breaks existing rules

### ISSUE THREAD

**Issue by adarobin** [ansible/ansible#67219]
##### SUMMARY
The fix in #63567 allows rules to be created/managed again without setting `allowed_hosts`.  The way this was implemented seems to break the way the previous functionality worked.

For example, on Ansible 2.8 this code would enable the firewall rule for outbound syslog with allowed_hosts set to any.

On Ansible 2.9 this enables the syslog rule, but doesn't set any `allowed_hosts` which meant all outbound syslog traffic was being blocked until I figured out what happened.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host_firewall_manager

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = None
  configured module search path = ['/Users/adarobin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/adarobin/ansible/lib/python3.7/site-packages/ansible
  executable location = /Users/adarobin/ansible/bin/ansible
  python version = 3.7.6 (default, Dec 22 2019, 01:09:06) [Clang 11.0.0 (clang-1100.0.33.12)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

vSphere 6.5 Update 3

##### STEPS TO REPRODUCE

Running the following code with Ansible 2.8 will allow logs to be sent to a remote syslog server, but on Ansible 2.9 it blocks all logs from being sent to a syslog server.

```yaml
- name: Allow syslog through the firewall
  vmware_host_firewall_manager:
    hostname: '{{ vcenter_hostname }}'
    esxi_hostname: '{{ inventory_hostname }}'
    username: '{{ vmware_user }}'
    password: '{{ vmware_password }}'
    rules:
      - name: syslog
        enabled: True
  delegate_to: localhost
```

##### EXPECTED RESULTS

Syslog is able to send logs to a remote syslog host after using the previous code with Ansible 2.9

##### ACTUAL RESULTS

Syslog is unable able to send logs to a remote syslog host after using the previous code with Ansible 2.9

```paste below

```
