### ISSUE TITLE
uri module post request failing on remote host

### ISSUE THREAD

**Issue by jauyzed** [ansible/ansible#67223]
##### SUMMARY
The uri module is failing on the POST request on localhost but the GET request works as required. The uri module is executed on remote host by setting remote_src attribute to yes for both get and post requests. A curl on the the same remote host returns the right http code for POST request.

FYI: this is just a basic kafka connector worker app that I am trying to start. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ubuntu 18.04

##### STEPS TO REPRODUCE

```
---
- name: Delete the connector  REST service
  uri:
    url: "http://localhost:8083/connectors/connector"
    method: DELETE
    remote_src: yes
    status_code: 204

```
The above GET request works as required
```
- name: start the connector application through REST
  uri:
    url: "http://localhost:8083/connectors"
    method: POST
    body_format: json
    #headers:
    #  Content-Type: "json"
    src: "startconnector.json"
    remote_src: yes
    status_code: 201
```
The above POST request FAILS with Errors as shown below

##### EXPECTED RESULTS

Corresponding Curl request:

```
curl --location --request POST 'http://localhost:8083/connectors'  --header 'Accept: application/json'  --header 'Content-Type: application/json'  -d @startcon.json --verbose

 About to connect() to localhost port 8083 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8083 (#0)
> POST /connectors HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8083
> Accept: application/json
> Content-Type: application/json
> Content-Length: 578
>
* upload completely sent off: 578 out of 578 bytes
< HTTP/1.1 201 Created
< Date: Fri, 07 Feb 2020 22:28:32 GMT
< Location: http://localhost:8083/connectors/user-filesink-connector_1
< Content-Type: application/json
< Content-Length: 663
< Server: Jetty(9.4.20.v20190813)

```

Runs successfully creating the kafka connector. 

##### ACTUAL RESULTS

```fatal: [10.1.10.45]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [201]: Request failed: <urlopen error [Errno 113] No route to host>", "redirected": false, "status": -1, "url": "http://localhost:8083/connectors"}

FAILED! => {
    "changed": false,
    "content": "",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "json",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Content-Type": "application/json"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": "True",
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "connector_1.json",
            "status_code": [
                "201"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "http://localhost:8083/connectors",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Status code was -1 and not [201]: Request failed: <urlopen error [Errno 113] No route to host>",
    "redirected": false,
    "status": -1,
    "url": "http://localhost:8083/connectors"

```
Below is the output for the task
```

- name: start the connector application through REST
  uri:
    url: "http://localhost:8083/connectors"
    method: POST
    headers:
      Content-Type: "json"
    src: "startconnector.json"
    remote_src: yes
    status_code: 201
    use_proxy: no
```

```
FAILED! => {
    "cache_control": "must-revalidate,no-cache,no-store",
    "changed": false,
    "connection": "close",
    "content": "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 400 Bad Request</title>\n</head>\n<body><h2>HTTP ERROR 400</h2>\n<p>Problem accessing /connectors. Reason:\n<pre>    Bad Request</pre></p><hr><a href=\"http://eclipse.org/jetty\">Powered by Jetty:// 9.4.20.v20190813</a><hr/>\n\n</body>\n</html>\n",
    "content_length": "331",
    "content_type": "text/html;charset=iso-8859-1",
    "date": "Fri, 07 Feb 2020 22:40:59 GMT",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Content-Type": "json"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": "True",
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "connector_1.json",
            "status_code": [
                "201"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "http://localhost:8083/connectors",
            "url_password": null,
            "url_username": null,
            "use_proxy": false,
            "validate_certs": true
        }
    },
    "msg": "Status code was 400 and not [201]: HTTP Error 400: Bad Request",
    "redirected": false,
    "server": "Jetty(9.4.20.v20190813)",
    "status": 400,
    "url": "http://localhost:8083/connectors"

```

Few other tries: 

```
- name: start the connector application through REST
  uri:
    url: "http://localhost:8083/connectors/"
    method: POST
    body_format: json
    headers:
      Content-Type: "application/json"
    src: "startconnector.json"
    remote_src: yes
    status_code: 201
    use_proxy: no

```

```
[t-kc14.fb]: FAILED! => {
    "changed": false,
    "connection": "close",
    "content": "{\"error_code\":500,\"message\":null}",
    "content_length": "33",
    "content_type": "application/json",
    "date": "Fri, 07 Feb 2020 23:16:17 GMT",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "json",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Content-Type": "application/json"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": "True",
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "startconnector.json",
            "status_code": [
                "201"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "http://localhost:8083/connectors/",
            "url_password": null,
            "url_username": null,
            "use_proxy": false,
            "validate_certs": true
        }
    },
    "json": {
        "error_code": 500,
        "message": null
    },
    "msg": "Status code was 500 and not [201]: HTTP Error 500: Internal Server Error",
    "redirected": false,
    "server": "Jetty(9.4.20.v20190813)",
    "status": 500,
    "url": "http://localhost:8083/connectors/"

```
