### ISSUE TITLE
Mount bind repeats mount when mountpoint are nested

### ISSUE THREAD

**Issue by sgargel** [ansible/ansible#67265]
##### SUMMARY
When using `mount` module with **nested** *bind* mounts points, every run after the first, create a new entry in `/proc/mounts`.

`fstab` is created correctly

Seems that the module is not using `mount -o remount` but has the same effect of doing `mount`  command again.

With mount binds, `mount` command of already mounted fs does not returns  "mount point is already mounted", and the entry in `/proc/mounts` gets duplicated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
[mount module](https://docs.ansible.com/ansible/latest/modules/mount_module.html)

##### ANSIBLE VERSION
```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/local/DOMAIN/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- hosts: debian9
  gather_facts: true
  become: true
  vars:
    mounts:
      - { src: /a, path: /mnt }
      - { src: /b, path: /mnt/b }
      - { src: /c, path: /mnt/c }
  
  tasks:


    - name: try mount bind, make dst dirs if it fails
      block:
        - name: Mount bind per ftp
          mount:
            path: "{{ item.path }}"
            src: "{{ item.src }}"
            opts: bind
            state: mounted
            fstype: none
          with_items:
            - "{{ mounts }}"
      rescue:
        - name: Ensure src directory for mount bind exists
          file:
            path: "{{ item.src }}"
            state: directory
            recurse: yes
          with_items:
            - "{{ mounts }}"
          
        - name: Create a directory per mount bind if not exists
          file:
            path: "{{ item.path }}"
            state: directory
          with_items:
            - "{{ mounts }}"
          
        - name: Mount bind per ftp
          mount:
            path: "{{ item.path }}"
            src: "{{ item.src }}"
            opts: bind
            state: mounted
            fstype: none
          with_items:
            - "{{ mounts }}"
  
```

##### EXPECTED RESULTS

if the path is already mounted it must not be mounted again.

##### ACTUAL RESULTS

```paste below
PLAY [debian9] ****************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
[WARNING]: Platform linux on host debian9 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

ok: [debian9]

TASK [Mount bind per ftp] *****************************************************************************************************************************
failed: [debian9] (item={u'src': u'/a', u'path': u'/mnt'}) => {"ansible_loop_var": "item", "changed": false, "item": {"path": "/mnt", "src": "/a"}, "msg": "Error mounting /mnt: mount: special device /a does not exist\n"}
failed: [debian9] (item={u'src': u'/b', u'path': u'/mnt/b'}) => {"ansible_loop_var": "item", "changed": false, "item": {"path": "/mnt/b", "src": "/b"}, "msg": "Error mounting /mnt/b: mount: special device /b does not exist\n"}
failed: [debian9] (item={u'src': u'/c', u'path': u'/mnt/c'}) => {"ansible_loop_var": "item", "changed": false, "item": {"path": "/mnt/c", "src": "/c"}, "msg": "Error mounting /mnt/c: mount: special device /c does not exist\n"}

TASK [Ensure src directory for mount bind exists] *****************************************************************************************************
changed: [debian9] => (item={u'src': u'/a', u'path': u'/mnt'})
changed: [debian9] => (item={u'src': u'/b', u'path': u'/mnt/b'})
changed: [debian9] => (item={u'src': u'/c', u'path': u'/mnt/c'})

TASK [Create a directory per mount bind if not exists] ************************************************************************************************
ok: [debian9] => (item={u'src': u'/a', u'path': u'/mnt'})
ok: [debian9] => (item={u'src': u'/b', u'path': u'/mnt/b'})
ok: [debian9] => (item={u'src': u'/c', u'path': u'/mnt/c'})

TASK [Mount bind per ftp] *****************************************************************************************************************************
changed: [debian9] => (item={u'src': u'/a', u'path': u'/mnt'})
changed: [debian9] => (item={u'src': u'/b', u'path': u'/mnt/b'})
changed: [debian9] => (item={u'src': u'/c', u'path': u'/mnt/c'})

PLAY RECAP ********************************************************************************************************************************************
debian9                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0   
```
*  `/etc/fstab` after 1st run
```
/a /mnt none bind 0 0
/b /mnt/b none bind 0 0
/c /mnt/c none bind 0 0
```
* `/proc/mounts` after 1st run
``` 
/dev/sda1 on /mnt type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt/b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /a/b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt/c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /a/c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```
* 2nd run logs:
```
PLAY [debian9] ****************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************
[WARNING]: Platform linux on host debian9 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

ok: [debian9]

TASK [Mount bind per ftp] *****************************************************************************************************************************
ok: [debian9] => (item={u'src': u'/a', u'path': u'/mnt'})
changed: [debian9] => (item={u'src': u'/b', u'path': u'/mnt/b'})
changed: [debian9] => (item={u'src': u'/c', u'path': u'/mnt/c'})

PLAY RECAP ********************************************************************************************************************************************
debian9                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
* `/proc/mounts` after 2nd run

```
/dev/sda1 on /mnt type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt/b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /a/b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt/c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /a/c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt/b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /a/b type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt/c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /a/c type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

* `/etc/fstab` after 2nd run
```
/a /mnt none bind 0 0
/b /mnt/b none bind 0 0
/c /mnt/c none bind 0 0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/mount.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/mount.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sgargel** [comment]
The problem does not occurs when `state` is set to `remount`

```
        - name: Mount bind per ftp
          mount:
            path: "{{ item.path }}"
            src: "{{ item.src }}"
            opts: bind
            state: remounted
            fstype: none
          with_items:
            - "{{ mounts }}"
```
