### ISSUE TITLE
Allow to emit warning and display a summary on the end of playbook execution

### ISSUE THREAD

**Issue by mvorisek** [ansible/ansible#67260]
##### SUMMARY
Allow to emit warning and display a summary on the end of playbook execution

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION
Feature searched by more than 5000 people, see https://stackoverflow.com/questions/48033923/ansible-print-warnings-from-playbook

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
can you be more specific? we already do what you say above

needs_info

**Comment by mvorisek** [comment]
@bcoca Allow to emit warning directly from playbook, i.e. emit warning like:
- name: Show warning if conditions are matched
  warning: This is a message from an user
  when: '1+1 > 1'

**Comment by ssbarnea** [comment]
I subscribe to the issue, current warning mechanism in ansible is very poor when compared with python warnings for example. There are two main issues:

* inability to silence a specific warning, there is only the disable_warnings option which is a very bad practice in general.
* inability to collect warnings during execution so you can build a report at the end, even better to be able to fail a play if total number of warnings increased.

Both of these are key ingredients for building good coding practices, to prevent quality going down while whitelisting some known issues for which you cannot do anything about them yet.

Regarding implementation: as long as core will store warnings in an accesible variable someone could write a callback plugin to give a nice report. Still, we need first to store these warnings somewhere, and that is core-functionality.

**Comment by theque5t** [comment]
@mvorisek I recently opened PR #65844 which adds a callback plugin that I believe can assist with this. I have included an example below that I believe demonstrates the feature idea, and the potential implementation using the callback plugin. Lastly, this plugin is compatible with ansible 2.8.5 or higher, using python 2.7, 3.5, or 3.6.

# Example

## Ansible Version
```
ansible 2.10.0.dev0
  config file = None
  configured module search path = ['/home/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/root/ansible/lib/ansible
  executable location = /home/root/ansible/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

## CONFIGURATION
```

```

## OS / ENVIRONMENT
```
Linux TESTBOX 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## STEPS TO REPRODUCE

1. Create `callback_plugins` directory and add the [diy.py](https://raw.githubusercontent.com/ansible/ansible/781b71e17fc7fa5b3ae09b073c58d5142cceff23/lib/ansible/plugins/callback/diy.py) callback plugin to it

2. Create `playbook.yml`
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Show warning if conditions are matched
      debug:
        msg: '[WARNING]: This is a message from a user'
      when: true
      vars:
        ansible_callback_diy_playbook_on_task_start_msg: '' 
        ansible_callback_diy_runner_on_ok_msg: >-
          {%- if ansible_callback_diy.task.when -%}
          {{- ansible_callback_diy.result.output.msg -}}
          {%- endif -%}
        ansible_callback_diy_runner_on_ok_msg_color: magenta
```

3. Run the playbook command
```sh
ANSIBLE_STDOUT_CALLBACK=diy ansible-playbook -i localhost, playbook.yml
```

## RESULT
```sh
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************
[WARNING]: This is a message from a user

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
In the output above there is a warning message in magenta that states `[WARNING]: This is a message from a user`. Should you prefer to adjust the message further, I believe this example demonstrated how the plugin can be used to adjust the output to your preference(also, the plugin itself has documentation, which has additional examples).
