### ISSUE TITLE
ec2_win_password python3 unicode issue with key_data argument

### ISSUE THREAD

**Issue by fvzwieten** [ansible/ansible#67275]
##### SUMMARY
when passing a private_key as a variable in the key_data argument of the ec2_win_password module results in error "unable to parse key data" error. 

After investigation, this seems to be a python2 to python3 porting issue. When I change line 181 in ec2_win_password.py from:
key = load_pem_private_key(key_data, b_key_passphrase, default_backend())
to
key = load_pem_private_key(key_data.encode('ascii'), b_key_passphrase, default_backend())

it works as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_win_password

##### ANSIBLE VERSION
```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible/lib64/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.1 (Ootpa)

##### STEPS TO REPRODUCE

```yaml
ec2_win_password:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      instance_id: "{{ ec2.instance_ids[0] }}"
      region: "{{ aws_region }}"
      key_data: "{{ ec2key.key.private_key }}"
      wait: true
    register: win_pwd
```

##### EXPECTED RESULTS

TASK [Get the Windows Password of the administrator] ***************************
task path: /tmp/awx_569_zbjol32w/project/aws_create_vm.yml:53
changed: [localhost] => {"changed": true, "elapsed": 117, "win_password": "zgRkSd5r231q;.oUWlD13dkC;euT7ar{aS"}

##### ACTUAL RESULTS

TASK [Get the Windows Password of the administrator] ***************************
task path: /tmp/awx_565_m93qwf3b/project/aws_create_vm.yml:53
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to parse key data"}
