### ISSUE TITLE
Ansible logicmonitor module not working

### ISSUE THREAD

**Issue by AbhishekB15** [ansible/ansible#67284]
##### SUMMARY
When trying to use ansible logicmonitor module, i get the below error

```
fatal: [server -> localhost]: FAILED! => {"changed": false, "msg": "Error: Exception making RPC call to https://XXXXXX.logicmonitor.com/santaba/rpc/getHost\nExceptionHTTP Error 410: "}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
logicmonitor module

##### ANSIBLE VERSION
```
2.9.2

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Target server - Ubuntu 18.04

##### STEPS TO REPRODUCE

As per pre-requisite, you need to have a LogicMonitor account

#Install Collector on a Server
```yaml
---
  - name: Install LogicMonitor collectors
    logicmonitor:
      target: collector
      action: add
      company: '{{ company }}'
      user: '{{ user }}'
      password: '{{ password }}'
```

#Add host to monitoring
```
---
  - name: Deploy LogicMonitor Host
    logicmonitor:
      target: host
      action: add
      collector: '{{ collector-name }}'
      company: '{{ company }}'
      user: '{{ user }}'
      password: '{{ password }}'
      groups: test
    delegate_to: localhost
```

##### ACTUAL RESULTS

```paste below

```
