### ISSUE TITLE
Allow k8s module to client-side validate definitions without modifying the cluster state

### ISSUE THREAD

**Issue by mjlshen** [ansible/ansible#67286]
##### SUMMARY
According to [https://www.ansible.com/blog/continuous-improvements-in-ansible-and-kubernetes-automation](https://www.ansible.com/blog/continuous-improvements-in-ansible-and-kubernetes-automation) it seems like client-side validation is expected to work, but it doesn't seem to be the case, so just in case...

It would be nice if `state: present` or `state: absent` wasn't required with validate, so true client-side validation could be done.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

##### ADDITIONAL INFORMATION

It would allow me to validate templated k8s manifests before they get commited into git and our GitOps workflow tries to reconcile the state.

```yaml
- name: "Validate k8s manifests"
  k8s:
    definition: "{{ filepath }}"
    validate:
      version: '1.17.0'
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/clustering/k8s/k8s.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
You should be able to use `validate` with `check_mode` if you want to do client side validation.

What in particular isn't working for you?

**Comment by willthames** [comment]
Note that the docs say that `fail_on_error` is required. I don't think I've updated kubernetes-validate to 1.17 yet (but it will work for the huge overlap between 1.16 and 1.17). 

```
- name: "Validate k8s manifests"
  k8s:
    definition: "{{ filepath }}"
    validate:
      version: '1.17.0'
      fail_on_error: yes
  check_mode: yes
```

**Comment by mjlshen** [comment]
Ah, yes, thank you, I had been using `fail_on_error: yes`! `check_mode: yes` is mostly sufficient, but I guess the problem I have is that it requires a kubeconfig even in this case, so this is what I'm testing with now:

```yaml
- name: "Validate k8s manifests"
  k8s:
    definition: "{{ filepath }}"
    kubeconfig: "{{ kubeconfig_path }}"
    validate:
      fail_on_error: yes
  check_mode: yes
```

I guess my issue is that client-side validation requires a `kubeconfig` to be set, and defaults `state: present`. It seems more declarative if there was a `state: validate` or something along those lines, but at least I don't think a kubeconfig should be required, just like how it is with the kubernetes-validate library I believe you wrote, so thanks for that too 😄
