### ISSUE TITLE
Mail module and callback plugin mail.py do not play nice with eachother

### ISSUE THREAD

**Issue by danielkinahan** [ansible/ansible#67295]
##### SUMMARY
The yaml mail module built into ansible was working fine locally and remotely. After the introduction of the mail.py callback script to my playbook, my smtp server connection is timing out every time I run my playbook remotely. I have tried changing ports and using seperate authentication, neither seems to have worked.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Mail.py

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /space/towerMaxDeploy/ansible.cfg
  configured module search path = [u'/home2/daniel.kinahan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 08:19:52) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

##### CONFIGURATION
```
ANSIBLE_NOCOLOR(/space/towerMaxDeploy/ansible.cfg) = False
DEFAULT_CALLBACK_PLUGIN_PATH(/space/towerMaxDeploy/ansible.cfg) = [u'/space/towerMaxDeploy/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/space/towerMaxDeploy/ansible.cfg) = [u'timer', u'mail']
DEFAULT_LOAD_CALLBACK_PLUGINS(/space/towerMaxDeploy/ansible.cfg) = True
```

##### OS / ENVIRONMENT
My local environment and remote repository (the one causing the issue) is an Oracle Linux Server 7.7

##### STEPS TO REPRODUCE
Use mail module with any port
Use mail.py callback plugin with any port

```yaml
mail:
  host: smtp1.company.ca
  port: 587
  to: test@email.com
  from: sender@email.com
  username: usrnm
  password: pswd

##in python script, im using the unmodified plugin
        smtp = smtplib.SMTP(self.smtphost, port=self.smtpport)
        smtp.sendmail(b_sender, b_address, b_content)

```

##### EXPECTED RESULTS

TASK [sendEmail : send human email with attachment] 
ok: [localhost]

##### ACTUAL RESULTS

The SMTP connection times out.

```paste below
TASK [sendEmail : send human email without attachment] *************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SMTPServerDisconnected: Connection unexpectedly closed: timed out
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to Connect smtp1.company.ca:25: Connection unexpectedly closed: timed out", "rc": 1}
```
