### ISSUE TITLE
Python3+Service module fails with UnicodeDecodeError when setting `enabled` parameter

### ISSUE THREAD

**Issue by jfoliveira** [ansible/ansible#67293]
##### SUMMARY
Task execution fails when setting the `enabled` parameter of the service module.
The error was only observec when setting `interpreter_python=/usr/bin/python3` in `ansible.cfg`.
By commenting the `interpreter_python` line in `ansible.cfg` the module runs without any errors.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/www/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/var/www/my-project/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/var/www/my-project/ansible.cfg) = -C -o ControlPersist=30s -o PreferredAuthentications=publickey -o ControlMaster=no
DEFAULT_CALLBACK_WHITELIST(/var/www/my-project/ansible.cfg) = [u'json', u'timer']
DEFAULT_ROLES_PATH(/var/www/my-project/ansible.cfg) = [u'/var/www/my-project/remote/roles', u'/etc/ansible/roles', u'/var/
HOST_KEY_CHECKING(/var/www/my-project/ansible.cfg) = False
INTERPRETER_PYTHON(/var/www/my-project/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/var/www/my-project/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target node: Ubuntu 18.04 (bionic), running in a docker container
Control machine: Debian 8 (jessie), running in a docker container

##### STEPS TO REPRODUCE

Run a playbook that uses the service module setting the `enabled` flag to any value.
Error does not occur if the `enabled` parameter is not set.
Error does not occur for all service names. `php7.2-fpm` is the service that I first notice the error happening.

```yaml
- hosts: all
  gather_facts: no

  tasks:
  - name: Ensure php-fpm is started and enabled at boot (if configured).
    service:
      # testing with `mysql`, `ssh` and `supervisor` services' names the error was not reproduced
      name: "php7.2-fpm"
      state: started
       # the issue only happens when setting the `enabled` property, being it true or false, with `php7.2-fpm` service
      enabled: true
      #enabled: no # also throws the same exception
```

##### EXPECTED RESULTS

Task should complete successfully.

##### ACTUAL RESULTS

Got the error reported above.

```paste below

```
