### ISSUE TITLE
Check Syntax for Entire Role

### ISSUE THREAD

**Issue by Shackelford-Arden** [ansible/ansible#67290]
##### SUMMARY

I would be fantastic to have the ability to use `--syntax-check` on a playbook that imports/includes a role to have it also check each role/task vs just the single file designated after `--syntax-check`. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Playbook Syntax Check

##### ADDITIONAL INFORMATION

This is particularly helpful when roles are larger and more difficult to manage by a single person.

Really rough when I run a large role only to find there's a typo in the last task :disappointed: 

I do see #5524 was closed with a commit, but from my testing this is not working as of Ansible 2.9.4.

```yaml
---
- name: Deploy Fedora
  hosts: fedora_machine
  become: yes
  become_method: sudo

  tasks:
    - include_role: 
        name: install_docker
    - include_role:
        name: base_fedora
        
```

In the above example, a typo exists in one of the tasks for base_fedora, but running:
```
ansible-playbook --syntax-check deploy_fedora.yml
```
Doesn't return an error, even though the typo/error is a misnamed module and/or parameter.
