### ISSUE TITLE
Add password to win_unzip module

### ISSUE THREAD

**Issue by solairen** [ansible/ansible#67308]
##### SUMMARY
According to Ansible documentation, `win_unzip` module does not support the `password` parameter.
This makes ansible unable to unpack the `.zip` file, which is password protected.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_unzip:
  password: "password123"

##### ADDITIONAL INFORMATION
Adding this feature will solve problems with unpacking password-protected files.

```yaml
- name: Unzip zip file
  win_unzip:
    src: C:\test\file.zip
    dest: C:\test\unpacked\
    recurse: no
    password: "password123"
```
