### ISSUE TITLE
Deregisters all the instances from Target Group when AutoScaling Group is modified with new Launch Configuration

### ISSUE THREAD

**Issue by ShivaniYasa** [ansible/ansible#67306]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_asg

##### ANSIBLE VERSION

```ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.6.8 


```

##### CONFIGURATION

```ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/.ansible/tmp/ansible-local-27438j7_hjsagd
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False


```

##### OS / ENVIRONMENT

Ubuntu 18.04.2 LTS

##### STEPS TO REPRODUCE

```
- name: gather facts about all AMIs with tag key Name
  ec2_ami_info:
    filters:
      "tag:Name": "{{ AMI_NAME }}"
    region: "{{ AWS_REGION }}"
    owners: self
  register: ami_found
      
- name: create launch configuration
  ec2_lc:
    name: "{{ LAUNCH_CONFIG_NAME }}-{{ ansible_date_time.iso8601_basic_short }}"
    image_id: "{{ ami_found.images[-1].image_id }}"
    key_name: "{{ KEY_PAIR }}"
    security_groups: "{{ SECURITY_GROUPS }}"
    instance_type: "{{ INSTANCE_TYPE }}"
    instance_profile_name: "{{ INSTANCE_PROFILE }}"
    region: "{{ AWS_REGION }}"
    volumes:
    - device_name: /dev/sda1
      volume_size: 8
      volume_type: gp2
      delete_on_termination: true
    user_data: "{{ lookup('template','userdata.j2', convert_data=False) |string }}"  
  register: launch_config
    
- name: get the target group arn to attach to the autoscaling group
  elb_target_group_info:
     names:
      - "{{ TARGET_GROUP_NAME }}"
     region: "{{ AWS_REGION }}" 
  register: alb_info
   
- set_fact:
    TARGET_GROUP_ARN: "{{ alb_info.target_groups[0].target_group_arn }}"

- name: create or update autoscaling group
  ec2_asg:
    name: "{{ AUTOSCALING_GROUP_NAME }}"
    launch_config_name: "{{ launch_config.result.launch_configuration_name }}"
    vpc_zone_identifier: "{{ PRIVATE_SUBNET_IDS }}"  
    health_check_period: 300
    health_check_type: ELB
    min_size: 2
    max_size: 5
    desired_capacity: 2
    region: "{{ AWS_REGION }}"
    termination_policies: OldestLaunchConfiguration
    wait_for_instances: yes
    default_cooldown: 300
    state: present
    replace_all_instances: yes
    target_group_arns: "{{ TARGET_GROUP_ARN }}"
    tags:
      - Name: "{{ INSTANCE_NAME }}"
```

##### EXPECTED RESULTS

Spin up the instances with new launch configuration, register in target group (healthy) then deregister instance with old configuartion from  target group and terminate........process continues until it maintains the desired count.
##### ACTUAL RESULTS

First it deregisters all the instances from target group and does not spin any new instances with new launch configuration. Asg maintains old config instances even its updated with new launch config. At the end target group does not have any registered instances (empty). When I tried using load_balancers (classic) instead of target_group_arns, it works fine as expected. 

```TASK [autoscaling : create or update autoscaling group] ********************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "availability_zones": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "debug_botocore_endpoint_logs": false,
            "default_cooldown": 300,
            "desired_capacity": 2,
            "ec2_url": null,
            "health_check_period": 300,
            "health_check_type": "ELB",
            "launch_config_name": "test-launch-config-20200210T184312",
            "launch_template": null,
            "lc_check": true,
            "load_balancers": null,
            "lt_check": true,
            "max_size": 5,
            "metrics_collection": false,
            "metrics_granularity": "1Minute",
            "metrics_list": [
                "GroupMinSize",
                "GroupMaxSize",
                "GroupDesiredCapacity",
                "GroupInServiceInstances",
                "GroupPendingInstances",
                "GroupStandbyInstances",
                "GroupTerminatingInstances",
                "GroupTotalInstances"
            ],
            "min_size": 2,
            "name": "test-autoscaling-group",
            "notification_topic": null,
            "notification_types": [
                "autoscaling:EC2_INSTANCE_LAUNCH",
                "autoscaling:EC2_INSTANCE_LAUNCH_ERROR",
                "autoscaling:EC2_INSTANCE_TERMINATE",
                "autoscaling:EC2_INSTANCE_TERMINATE_ERROR"
            ],
            "placement_group": null,
            "profile": null,
            "region": "us-east-1",
            "replace_all_instances": true,
            "replace_batch_size": 1,
            "replace_instances": [],
            "security_token": null,
            "state": "present",
            "suspend_processes": [],
            "tags": [
                {
                    "Name": "test"
                },
            ],
            "target_group_arns": [
                "arn:aws:*
            ],
            "termination_policies": [
                "OldestLaunchConfiguration"
            ],
            "validate_certs": true,
            "vpc_zone_identifier": [
                "subnet-*",
            ],
            "wait_for_instances": true,
            "wait_timeout": 300
        }
    },
    "msg": "Waited too long for ELB instances to be healthy."
}


```
![image](https://user-images.githubusercontent.com/43036878/74249110-a25d3e00-4cb6-11ea-9b0e-c839f6d3fba7.png)

These are the instances with Old Launch Configuration 
![image](https://user-images.githubusercontent.com/43036878/74249966-f288d000-4cb7-11ea-89e3-f32fc8d4a2fb.png)
