### ISSUE TITLE
file module fails in check mode if directory exists but user or group does not.

### ISSUE THREAD

**Issue by nepella** [ansible/ansible#67307]
##### SUMMARY
In check mode, when using the file module to create a directory, if the directory already exists but the requested owner or group do not, the module will fail. I encountered this when running a playbook in check mode that creates a new user and changes the ownership of an existing directory.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION
```
ansible 2.9.3
  config file = /home/nepeta/wip/lockss-playbook/ansible.cfg
  configured module search path = ['/home/nepeta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Fedora 31 host

##### STEPS TO REPRODUCE
Run the following playbook in check mode (`ansible-playbook demo.playbook.yml -C`):

```yaml
# demo.playbook.yml---

- hosts: localhost
  tasks:
    - name: Create user.
      user:
        name: notauser
        state: present

    - name: Task succeeds in check mode.
      file:
        path: /notadirectory
        state: directory
        owner: notauser

    - name: Task fails in check mode.
      file:
        path: /usr
        state: directory
        owner: notauser
```

##### EXPECTED RESULTS
I expect the module to skip the lookup of the user or group if it doesn't exist and to report the task as changed.

##### ACTUAL RESULTS
```
TASK [Create user.] ***********************************************************************************************************************
changed: [localhost]

TASK [Task succeeds in check mode.] *******************************************************************************************************
changed: [localhost]

TASK [Task fails in check mode.] **********************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  gid: 0
  group: root
  mode: '0755'
  msg: 'chown failed: failed to look up user notauser'
  owner: root
  path: /usr
  secontext: system_u:object_r:usr_t:s0
  size: 4096
  state: directory
  uid: 0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/files/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Andersson007** [comment]
@nepella i think it must fail in both cases.
Just imagine you didn't add the user before. So, when you run it in check_mode it returns True but if you run the same in the actual mode your playbook fails.
It must fail in both cases, otherwise, it behaves wrong successfully passing this check.

**Comment by nepella** [comment]
@Andersson007: That's a good point; I agree with you. A false positive is
preferable to a false negative here, especially since this usage—creating a user
and using that user as a parameter to modules within the same playbook—is
probably not the most common case. Using `when: not ansible_check_mode` is a
fine solution. Also, it seems I have to make similar adjustments in many other
cases; the following would fail in check mode without the `when` clause:

```yaml
- tempfile:
    state: directory
  register: tmpdir

- command:
    cmd: foo
    chdir: "{{ tmpdir.path }}"
  when: tmpdir.path is defined
```
