### ISSUE TITLE
Please add support for specify syslog port number and transport type in the ios_logging module

### ISSUE THREAD

**Issue by erictomb** [ansible/ansible#67314]
##### SUMMARY

The ios_logging module does not support configuring logging on Cisco IOS to non standard syslog ports.  Standard port is UDP 514, but some log collectors listen on different ports.

##### ISSUE TYPE
- Feature Idea
Create a transport parameter so that users can specify sending syslog messages to different ports.  I would like to see it support the following command:
``
logging host 1.2.3.4 transport udp port 1234
``
On Cisco devices, tcp transport is also supported.  I'd like to see that as well.

##### COMPONENT NAME

This should be supported in the **ios_logging** module.

##### ADDITIONAL INFORMATION

There are services such as Sumologic that collect logs from an organization and keep them in the cloud.  Internally there are collectors that devices point their logs to and in turn are redirected to Sumologic.  Different port numbers are sometimes used to distinguish different types of devices.  For example, firewalls might log to port 11111, routers to port 22222, etc.

```yaml
Command would be: logging host 1.2.3.4 transport udp port 1234

it could look like this in the yaml file:

- name:
  ios_logging:
    - dest: host
    - name: 1.2.3.4
    - transport: udp
    - port: 1234
    - state: present

```
