### ISSUE TITLE
[cloud/vmware/vmware_guest_disk]: Remove disk failed.

### ISSUE THREAD

**Issue by cuixiangz** [ansible/ansible#67329]
##### SUMMARY

Use latest code on  ansible devel branch,  when try to remove one existing disk, it report fail.
```
  The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_vmware_guest_disk_payload_neeOUK/ansible_vmware_guest_disk_payload.zip/ansible/modules/cloud/vmware/vmware_guest_disk.py", line 864, in main
  File "/tmp/ansible_vmware_guest_disk_payload_neeOUK/ansible_vmware_guest_disk_payload.zip/ansible/modules/cloud/vmware/vmware_guest_disk.py", line 437, in ensure_disks
  File "/tmp/ansible_vmware_guest_disk_payload_neeOUK/ansible_vmware_guest_disk_payload.zip/ansible/modules/cloud/vmware/vmware_guest_disk.py", line 576, in sanitize_disk_inputs
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "XXX",
            "disk": [
                {
                    "scsi_controller": "3",
                    "state": "absent",
                    "unit_number": "1"
                }
            ],
   ...
        ...      .
        }
    },
    "msg": "Failed to manage disks for virtual machine 'xxxx' with exception : 'destroy'"
}
```
Error point to Line 576 of lib/ansible/modules/cloud/vmware/vmware_guest_disk.py
```
575             if current_disk['state'] == 'absent':
576                 current_disk['destroy'] = disk['destroy']
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/cloud/vmware/vmware_guest_disk.py

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.10.0.dev0
# git log -1
commit 4a1115785faa786bc86a31ff38a65dd382e29306 (origin/devel, origin/HEAD, devel)
Author: Gonéri Le Bouder <goneri@lebouder.net>
Date:   Thu Feb 6 17:23:49 2020 -0500
    vmware_guest_network/test: disable the test
...

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

- name: "Disks to virtual machine {{ vm_name }}: {{ state }}"
  vmware_guest_disk:
    hostname: "{{ vsphere_host_name }}"
    username: "{{ vsphere_host_user }}"
    password: "{{ vsphere_host_user_password }}"
    validate_certs: "{{ valid_cert | default(False) }}"
    datacenter: "{{ vsphere_host_datacenter }}"
    folder: "{{ vm_folder | default('/') }}"
    name: "{{ vm_name }}"
    disk:
      - state: "absent"
        scsi_controller: "{{ ctrl_no }}"
        unit_number: "{{ unit_no }}"
  delegate_to: localhost
  register: disk_facts
```

##### EXPECTED RESULTS

Remove the existing disk successfully.

##### ACTUAL RESULTS

Remove existing disk failed.

```paste below

```
