### ISSUE TITLE
redfish_utils.py: incorrectly uses PATCH method for add_user, incorrectly uses the ID

### ISSUE THREAD

**Issue by jgtaylor** [ansible/ansible#67338]
##### SUMMARY

The command attempts to PATCH to `self.root_uri + self.accounts_uri + "/" + user['userid']` - but the userid can not exist yet, so the server responds with Error 400.
```
HTTP Error 400 on PATCH request to 'https://host-name.example.net/redfish/v1/AccountService/Accounts/3', extended message: 'Bad Request'"
```
Removing the userid value, and retrying, the next error is Error 405. Per the specification, a "Create" should be done with POST, while PATCH should only be for "Update".
```
HTTP Error 405 on PATCH request to 'https://host-name.example.net/redfish/v1/AccountService/Accounts/', extended message: 'Method Not Allowed'
```
The documentation is also wrong - the id can not be used to create a user. http://redfish.dmtf.org/schemas/DSP0266_1.9.0.html#post-create-a-id-post-create-a-
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_command

(problem is in redifsh_utils.py)
##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.8.3
  config file = /home/taylor_j/src/playbooks/ansible.cfg
  configured module search path = ['/home/taylor_j/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/home/taylor_j/src/playbooks/ansible.cfg) = -o ControlMaster=no
DEFAULT_CALLBACK_WHITELIST(/home/taylor_j/src/playbooks/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/taylor_j/src/playbooks/ansible.cfg) = ['/home/taylor_j/src/playbooks/hosts/sls-prod']
DEFAULT_VAULT_PASSWORD_FILE(/home/taylor_j/src/playbooks/ansible.cfg) = /home/taylor_j/src/playbooks/ansible_password_file
HOST_KEY_CHECKING(/home/taylor_j/src/playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Linux - ansible 2.8, redfish module

##### STEPS TO REPRODUCE

attempt to add a user via a playbook - the example in the documentation produces the error.

```yaml
- hosts: all
  gather_facts: no
  tasks:
    - include_vars:
        file: ../hosts/servers_vault.yaml
        name: creds

    - set_fact:
        ilo_defaultuser: "{{ creds[inventory_hostname]['ilo_default_user'] }}"
        ilo_defaultpwd: "{{ creds[inventory_hostname]['ilo_default_password'] }}"
        ilo_default_hostname: "{{ creds[inventory_hostname]['ilo_default_hostname'] }}"

    - name: "Add default user to iLO: 'admin'"
      redfish_command:
        category: Accounts
        command: AddUser
        baseuri: "{{ ilo_prefix }}{{ inventory_hostname }}"
        username: "{{ ilo_defaultuser }}"
        password: "{{ ilo_defaultpwd }}"
        new_username: admin2
        new_password: password
        id: 3
        roleid: Administrator # One of Administrator, ReadOnly or Operator
      delegate_to: localhost
```

##### EXPECTED RESULTS

Expect a user to be created.

##### ACTUAL RESULTS

Command fails 

```paste below
 _________________________________________
< TASK [Add default user to iLO: 'admin'] >
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/taylor_j/src/playbooks/ilo/ilo_add_default_admin_user.yaml:13
Wednesday 12 February 2020  14:11:35 +0100 (0:00:00.057)       0:00:00.247 **** 
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: taylor_j
<localhost> EXEC /bin/sh -c 'echo ~taylor_j && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052 `" && echo ansible-tmp-1581513095.3662171-75495456501052="` echo /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/remote_management/redfish/redfish_command.py
<localhost> PUT /home/taylor_j/.ansible/tmp/ansible-local-25435er_fb3yg/tmpuxmfgtnh TO /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/ /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/ > /dev/null 2>&1 && sleep 0'
fatal: [example-host-name -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/taylor_j/.ansible/tmp/ansible-tmp-1581513095.3662171-75495456501052/AnsiballZ_redfish_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_redfish_command_payload_h9doetf_/__main__.py\", line 292, in <module>\n  File \"/tmp/ansible_redfish_command_payload_h9doetf_/__main__.py\", line 239, in main\n  File \"/tmp/ansible_redfish_command_payload_h9doetf_/ansible_redfish_command_payload.zip/ansible/module_utils/redfish_utils.py\", line 582, in add_user\nTypeError: can only concatenate str (not \"NoneType\") to str\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
