### ISSUE TITLE
docker_login not create config.json file with correct permission

### ISSUE THREAD

**Issue by richierg** [ansible/ansible#67347]
##### SUMMARY

The module docker_login save the config.json with 644 permission instead of 600 (default by docker login command)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_login
##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gael/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04 server

##### STEPS TO REPRODUCE

```yaml
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ registry_host }}"
    username: "{{ registry_user }}"
    password: "{{ vault_registry_password }}"
```

##### EXPECTED RESULTS

ll /root/.docker/config.json 
-rw------- 1 root root 181 Jan 10 10:53 /root/.docker/config.json

##### ACTUAL RESULTS

ll /root/.docker/config.json 
-rw-r--r-- 1 root root 181 Jan 10 10:53 /root/.docker/config.json

```paste below

```
