### ISSUE TITLE
postgresql_set converts value to uppercase if "mb" or "gb" or "tb" is in the string

### ISSUE THREAD

**Issue by cjewo** [ansible/ansible#67377]
##### SUMMARY

in postgresql_set.py:303 the value to be set is converted to uppercase if it contains "mb" or "gb" or "tb".
for example an archive command will fail if the case is not correct.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_set.py:303
##### ANSIBLE VERSION

```paste below
ansible 2.8.1
python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

debian stretch

##### STEPS TO REPRODUCE

```yaml
    postgresql_set:
      name: 'archive_command'
      value: 'test ! -f /mnt/postgres/mb/%f && cp %p /mnt/postgres/mb/%f'
```

##### EXPECTED RESULTS

grep archive_command postgresql.auto.conf:
```
archive_command = 'test ! -f /mnt/postgres/mb/%f && cp %p /mnt/postgres/mb/%f'
```

##### ACTUAL RESULTS

grep archive_command postgresql.auto.conf:
```
archive_command = 'TEST ! -F /MNT/POSTGRES/MB/%F && CP %P /MNT/POSTGRES/MB/%F'
```

```paste below

```
