### ISSUE TITLE
vmware_guest customization runonce not executing

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#67383]
##### SUMMARY

vmware_guest is not executing customization runonce command

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest 

##### ANSIBLE VERSION

```paste below
2.9.4
```

##### STEPS TO REPRODUCE

```yaml
# Converts template to VM
- name: "Convert {{ template }} to VM"
  vmware_guest:
    hostname: "{{ hostname }}"
    username: "{{ domain_user }}"
    password: "{{ domain_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    state: present
    name: "{{ template }}"
    is_template: False
    convert: thin
    wait_for_ip_address: yes

# Powers On VM
- name: "Power On {{ template }}"
  vmware_guest:
    hostname: "{{ hostname }}"
    username: "{{ domain_user }}"
    password: "{{ domain_password }}"
    datacenter: "{{ datacenter }}"
    validate_certs: no
    name: "{{ template }}"
    state: poweredon
    wait_for_ip_address: yes
    wait_for_customization: yes
    customization:
      #fullname: "{{ local_user }}"
      password: "{{ local_password }}"
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\StartupScripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
```

##### EXPECTED RESULTS

I expect the script to be executed.

##### ACTUAL RESULTS

No errors shown in output with verbose -vvvv but VALUE_SPECIFIED_IN_NO_LOG_PARAMETER is shown although I am not using no_log: true!

```paste below
"invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [],
            "cluster": null,
            "convert": null,
            "customization": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "runonce": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ]
            },
```

I know the script is not executed because I cannot connect to the VM with ansible. However, if I run the script manually on VM I can connect with no problems.
