### ISSUE TITLE
Git option to allow local modifications

### ISSUE THREAD

**Issue by pinko-fowle** [ansible/ansible#67390]
##### SUMMARY

As a developer, I use git to set up other coworkers & my own environments. We often have some local changes to our repos, but still want to be able to run our playbooks to do other tasks, such as running db migrations or updating libraries.

At the moment Ansible is very hard to use for developer automation because there is no good way to allow local modifications to exist in a repository while using the git module. This [has been a longstanding issue](https://stackoverflow.com/questions/41178361/how-to-use-ansible-git-module-pull-a-branch-with-local-changes) for developers, & no workarounds have been provided yet. Having a softer way to manage git would be very much appreciated.

Many modules have a `state` argument, for flags like `update` and `present`; this would be very very good to have & to replicate in git.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

git

##### ADDITIONAL INFORMATION

```yaml
# a simple example of what would be lovely lovely lovely to have:
- git:
    repo: https://github.com/ansible/ansible
    state: present
    dest: ~/src/ansible
```
