### ISSUE TITLE
eos_l3_interfaces missing list item for IP Address

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [ansible/ansible#67412]
##### SUMMARY
information missing in examples (List items missing from ip address field)

Example shown as per documentation (https://docs.ansible.com/ansible/latest/modules/eos_l3_interfaces_module.html#eos-l3-interfaces-module):
```
- name: Merge provided configuration with device configuration.
  eos_l3_interfaces:
    config:
      - name: Ethernet1
        ipv4:
          address: 198.51.100.14/24
    state: merged
```
Errors with 
fatal: [eos]: FAILED! => {"changed": false, "msg": "argument ipv4 is of type <type 'dict'> found in 'config'. and we were unable to convert to list: <type 'dict'> cannot be converted to a list"}

Example of correct input (where the list item dash (-) is missing from the address field for the code to complete correctly.
```
- name: Merge provided configuration with device configuration.
  eos_l3_interfaces:
    config:
      - name: Ethernet1
        ipv4:
          - address: 198.51.100.14/24
    state: merged
```

##### ISSUE TYPE
- Documentation 

##### COMPONENT NAME
eos_l3_interfaces is the plugin that has issues

##### ANSIBLE VERSION

```
[root@Elysium Create_VL_Interfaces]# ansible --version
ansible 2.9.3
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
[root@Elysium Create_VL_Interfaces]# ansible-config dump --only-changed
DEFAULT_HOST_LIST(/root/.ansible.cfg) = [u'/root/networking-workshop/lab_inventory/hosts']
DEFAULT_TIMEOUT(/root/.ansible.cfg) = 60
HOST_KEY_CHECKING(/root/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
CentOS Linux release 7.7.1908 (Core)
