### ISSUE TITLE
File operations failing on shared file system

### ISSUE THREAD

**Issue by StephenGevers** [ansible/ansible#67410]
##### SUMMARY

Both copy and stat fail to find a file in a shared directory that was deleted and recreated during a task list. I have a role that operates across two hosts that have a NAS storage.  A command on one host produces a file that I need on another host.  The command that produces the file fails if the file is already there, so there is a file task to remove it.  If I remove the file from one host (which removes it from both because it's shared), then create it from the other host, copy/stat fail on the newly created file on the host on which the file was initially removed.  I have supplied a sample playbook that recreates the issue.

Start with the file existing, the playbook does a stat of the file on both hosts, remove the file on host1, stat the file on both hosts create the file on host2, stat the file on both hosts.  You can see that the final stat shows the file does not exist on host1 even though host2 created the file in the shared location.   Note that I found this because the copy module throws a file not found error on the same shared file.  It's as if these modules are caching the file tasks removal and not checking the actual host
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.8.8
  config file = REDACTED/ansible.cfg
  configured module search path = ['REDACTED', 'REDACTED']
  ansible python module location = REDACTED
  executable location = REDACTED
  python version = 3.6.4 (default, Oct  2 2019, 09:58:18) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
ANY_ERRORS_FATAL(REDACTED/ansible.cfg) = True
CACHE_PLUGIN(REDACTED/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(REDACTED/ansible.cfg) = ['REDACTED
DEFAULT_CALLBACK_PLUGIN_PATH(REDACTED/ansible.cfg) = ['REDACT
DEFAULT_CALLBACK_WHITELIST(REDACTED/ansible.cfg) = ['q_callba
DEFAULT_FACT_PATH(REDACTED/ansible.cfg) = REDACTED
DEFAULT_FILTER_PLUGIN_PATH(REDACTED/ansible.cfg) = ['REDACTED
DEFAULT_FORKS(REDACTED/ansible.cfg) = 50
DEFAULT_GATHER_TIMEOUT(REDACTED/ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(REDACTED/ansible.cfg) = merge
DEFAULT_INVENTORY_PLUGIN_PATH(REDACTED/ansible.cfg) = ['REDAC
DEFAULT_MODULE_PATH(REDACTED/ansible.cfg) = ['REDACTED
DEFAULT_MODULE_UTILS_PATH(REDACTED/ansible.cfg) = ['REDACTED
DEFAULT_ROLES_PATH(REDACTED/ansible.cfg) = ['/REDACTED
HOST_KEY_CHECKING(REDACTED/ansible.cfg) = False
INVENTORY_ENABLED(REDACTED/ansible.cfg) = ['test_inv', 'host_
```

##### OS / ENVIRONMENT

Redhat Enterprise 6

##### STEPS TO REPRODUCE

```yaml
---
- name: Test shared file issue
  hosts: dmgr:solr
  become: yes
  become_user: REDACTED
  become_method: sudo
  tasks:
  - name: stat the file from both
    stat:
      path: "{{ shared_dir }}/testfile"
    register: st1
  - name: show the stat results
    debug:
      msg: "{{ st1.stat }}"
  - name: Remove the file from solr
    file:
      path: "{{ shared_dir }}/testfile"
      state: absent
    when: "'solr' in group_names"
  - name: stat the file from both
    stat:
      path: "{{ shared_dir }}/testfile"
    register: st2
  - name: show the stat results
    debug:
      msg: "{{ st2.stat }}"
  - name: create the file on dmgr
    shell: 'echo "Hello World" > {{ shared_dir }}/testfile'
    when: "'dmgr' in group_names"
  - name: stat the file from both
    stat:
      path: "{{ shared_dir }}/testfile"
    register: st3
  - name: show the stat results
    debug:
      msg: "{{ st3.stat }}"
```

##### EXPECTED RESULTS

The stat command shows the file exists on all hosts after it gets created

##### ACTUAL RESULTS

```paste below
PLAY [Test shared file issue] **************************************************

TASK [Gathering Facts] *********************************************************
ok: [SOLR REDACTED]
ok: [DMGR REDACTED]

TASK [stat the file from both] *************************************************
ok: [SOLR REDACTED]
ok: [DMGR REDACTED]

TASK [show the stat results] ***************************************************
ok: [DMGR REDACTED] => {
    "msg": {
        "atime": 1581632781.2166235,
        "attr_flags": "",
        "attributes": [],
        "block_size": 32768,
        "blocks": 51,
        "charset": "us-ascii",
        "checksum": "648a6a6ffffdaa0badb23b8baf90b6168dd16b3a",
        "ctime": 1581632781.2166235,
        "dev": 20,
        "device_type": 0,
        "executable": false,
        "exists": true,
        "gid": 600,
        "gr_name": "REDACTED",
        "inode": 923882965,
        "isblk": false,
        "ischr": false,
        "isdir": false,
        "isfifo": false,
        "isgid": false,
        "islnk": false,
        "isreg": true,
        "issock": false,
        "isuid": false,
        "mimetype": "text/plain",
        "mode": "0640",
        "mtime": 1581632781.2166235,
        "nlink": 1,
        "path": "REDACTED/testfile",
        "pw_name": "REDACTED",
        "readable": true,
        "rgrp": true,
        "roth": false,
        "rusr": true,
        "size": 12,
        "uid": 600,
        "version": null,
        "wgrp": false,
        "woth": false,
        "writeable": true,
        "wusr": true,
        "xgrp": false,
        "xoth": false,
        "xusr": false
    }
}
ok: [SOLR REDACTED] => {
    "msg": {
        "atime": 1581632781.2166235,
        "attr_flags": "",
        "attributes": [],
        "block_size": 32768,
        "blocks": 51,
        "charset": "us-ascii",
        "checksum": "648a6a6ffffdaa0badb23b8baf90b6168dd16b3a",
        "ctime": 1581632781.2166235,
        "dev": 20,
        "device_type": 0,
        "executable": false,
        "exists": true,
        "gid": 600,
        "gr_name": "REDACTED",
        "inode": 923882965,
        "isblk": false,
        "ischr": false,
        "isdir": false,
        "isfifo": false,
        "isgid": false,
        "islnk": false,
        "isreg": true,
        "issock": false,
        "isuid": false,
        "mimetype": "text/plain",
        "mode": "0640",
        "mtime": 1581632781.2166235,
        "nlink": 1,
        "path": "REDACTED/testfile",
        "pw_name": "REDACTED",
        "readable": true,
        "rgrp": true,
        "roth": false,
        "rusr": true,
        "size": 12,
        "uid": 600,
        "version": null,
        "wgrp": false,
        "woth": false,
        "writeable": true,
        "wusr": true,
        "xgrp": false,
        "xoth": false,
        "xusr": false
    }
}

TASK [Remove the file from solr] ***********************************************
skipping: [DMGR REDACTED]
changed: [SOLR REDACTED]

TASK [stat the file from both] *************************************************
ok: [DMGR REDACTED]
ok: [SOLR REDACTED]

TASK [show the stat results] ***************************************************
ok: [DMGR REDACTED] => {
    "msg": {
        "exists": false
    }
}
ok: [SOLR REDACTED] => {
    "msg": {
        "exists": false
    }
}

TASK [create the file on dmgr] *************************************************
skipping: [SOLR REDACTED]
changed: [DMGR REDACTED]

TASK [stat the file from both] *************************************************
ok: [SOLR REDACTED]
ok: [DMGR REDACTED]

TASK [show the stat results] ***************************************************
ok: [DMGR REDACTED] => {
    "msg": {
        "atime": 1581632801.6810343,
        "attr_flags": "",
        "attributes": [],
        "block_size": 32768,
        "blocks": 3,
        "charset": "us-ascii",
        "checksum": "648a6a6ffffdaa0badb23b8baf90b6168dd16b3a",
        "ctime": 1581632801.6810343,
        "dev": 20,
        "device_type": 0,
        "executable": false,
        "exists": true,
        "gid": 600,
        "gr_name": "REDACTED",
        "inode": 924192747,
        "isblk": false,
        "ischr": false,
        "isdir": false,
        "isfifo": false,
        "isgid": false,
        "islnk": false,
        "isreg": true,
        "issock": false,
        "isuid": false,
        "mimetype": "text/plain",
        "mode": "0640",
        "mtime": 1581632801.6810343,
        "nlink": 1,
        "path": "REDACTED/testfile",
        "pw_name": "REDACTED",
        "readable": true,
        "rgrp": true,
        "roth": false,
        "rusr": true,
        "size": 12,
        "uid": 600,
        "version": null,
        "wgrp": false,
        "woth": false,
        "writeable": true,
        "wusr": true,
        "xgrp": false,
        "xoth": false,
        "xusr": false
    }
}
ok: [SOLR REDACTED] => {
    "msg": {
        "exists": false
    }
}

PLAY RECAP *********************************************************************
DMGR REDACTED       : ok=8    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
SOLR REDACTED       : ok=8    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```
