### ISSUE TITLE
Failed to connect to gitlab server: 404 Not Found.

### ISSUE THREAD

**Issue by sakar97** [ansible/ansible#67416]
##### SUMMARY

When I use gitlab_project ansible module then I showed up with this error. I am confused between the api_url parameter vs server_url parameter. 

##### ISSUE TYPE
- Bug Report
"Failed to connect to GitLab server: 404: 404 Not Found.             GitLab removes Session API now that private tokens are removed from user API endpoints since version 10.2.

##### COMPONENT NAME

gitlab_project

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

##### OS / ENVIRONMENT

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

##### STEPS TO REPRODUCE

```
-
 - hosts: localhost
   gather_facts: no
   become_method: sudo
   become: true
   tasks:
           - name: Add a project to git
             gitlab_project:
                     api_url: https://gitlab.com/api/v4/projects
                     #server_url: https://gitlab.com/
                     api_username: username
                     api_password: password
                     #api_token: 
                     description: "This is my new project"
                     issues_enabled: no
                     #login_password: mypassword
                     #login_user: username
                     name: my_new_proj
                     state: present
                     snippets_enabled: False
                     validate_certs: True
                     visibility: public
             delegate_to: localhost

```

##### EXPECTED RESULTS

The project should be created on GIT

##### ACTUAL RESULTS

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Failed to connect to GitLab server: 404: 404 Not Found.             GitLab remove Session API now that private tokens are removed from user API endpoints since version 10.2."}

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/source_control/gitlab/gitlab_project.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab/gitlab_project.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Lunik @Shaps @dj-wasabi @jlozadad @marwatk @waheedi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Lunik** [comment]
Have you tried with `api_url: https://gitlab.com`

**Comment by sakar97** [comment]
Same Error...

**Comment by Lunik** [comment]
Your GitLab instance version greater than `10.2`, you can't use user/password authentication anymore. Try using `api_token` instead

**Comment by sakar97** [comment]
When I am adding api_url : https://gitlab.com/namespace and api_token: ****** then I am getting the output as 

``The error was: TypeError: 'Response' object has no attribute '__getitem__' ``

**Comment by Lunik** [comment]
`api_url` should still be equal to `https://gitlab.com` in your case

**Comment by sakar97** [comment]
But when I just type `https://gitlab.com` it asks for a namespace.

**Comment by sakar97** [comment]
Module working fine in Internal GIT when I am providing IP of the internal system but It is not working on public git.

**Comment by waheedi** [comment]
@sakar97 did you try using `"https://gitlab.com/api"` ?

**Comment by sakar97** [comment]
Yes I tried that also

**Comment by JosteinVH** [comment]
I have the same issue. 

`ansible 2.9.0` 
`python 3.7.5`  
`python-gitlab 1.12.1`
`gitlab instance version 12.6>`

_To add further comments_
When using `gitlab_project` parameter `server_url` it states that the parameter is deprecated and will be removed in `2.10`, but it does not state which options to use. It is `api_url`

Both the examples from `gitlab_project` and `gitlab_project_variable` use the `api_url` parameter with a trailing slash (`/`). From my experience this will add an extra slash when running the playbook, meaning the `//api/v4/users` will be used instead of `/api/v4/users`

**Comment by sakar97** [comment]
So I created GitLab instance in my computer and when I put my local instance URL to api_url then the module works fine. But when I try to put public GitLab URL which is gitlab.com then it shows an error.

**Comment by semente** [comment]
Got the same issue @sakar97 is having. Any workaroung?

**Comment by ltutar** [comment]
I had the same issue.
```
ansible 2.9.9
python 3.7.7
python-gitlab 1.12.1
gitlab instance version 13.0.0

```
I had to use the deprecated syntax to get it working i.e. `server_url` and `login_token`.

```
- name: "Create gitlab cdaas group"
  gitlab_group:
    server_url: "{{ gitlab_external_url }}"
    login_token: "{{ gitlab_personal_access_token }}"
    validate_certs: False
    name: cdaas
    state: present
  when: 
    - gitlab_personal_access_token is defined
    - gitlab_personal_access_token != None
```
The rest of the combinations like `api_xxx` is not working.
