### ISSUE TITLE
blockinfile: do not remove markers when block is empty

### ISSUE THREAD

**Issue by sylr** [ansible/ansible#67422]
##### SUMMARY

If you provide an empty block to blockinfile plugin it will remove the markers from the target files.

It would be nice if the plugin allowed the markers to remain.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
blockinfile

##### ADDITIONAL INFORMATION

```yaml
---
- name: Reset nsg rules to block cross subscription access
  connection: local
  gather_facts: false
  hosts: all
  tasks:
  - name: Reset dynamic rules
    blockinfile:
      state: present
      path: "{{ subscription }}/nsg-{{ item.name }}.tf"
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      insertbefore: "^}"
      block: ""
    loop: "{{ nsglist | sort(attribute='name') }}"
    when: item.name | string is match("k8s\d*-euw-.*-master-nsg")
    ignore_errors: yes
```
