### ISSUE TITLE
vmware_guest wait_for_customization does not wait

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#67424]
##### SUMMARY

vmware_guest  vmware_guest wait_for_customization does not wait for the vm to finish customizing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest 

##### ANSIBLE VERSION

```paste below
2.9.5
```

##### STEPS TO REPRODUCE

```yaml
- name: Create new VMware Virtual Machine
  vmware_guest:
    hostname: "{{ hostname }}"
    esxi_hostname: "{{ esxi_hostname }}"
    username: '{{domain_user }}'
    password: "{{ domain_password }}"
    validate_certs: False
    datacenter: "{{ datacenter }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_destination | default('/Test-Dev/QA') }}"      
    state: poweredon
    disk:
    - size_gb: '{{ disk_size | default(40) }}'
      type: thin
      autoselect_datastore: True
    hardware:
      memory_mb: "{{ memory | default(4096) }}"
      num_cpus: "{{ cores | default(2) }}"
      num_cpu_cores_per_socket: "{{ cores | default(2) }}"
    networks:
    - name: LAN
      domain: "{{ domain }}"
      dns_servers:
      -  "{{ dns1 }}"
      -  "{{ dns2 }}"
      type: static
      ip: "{{ new_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"
    customization:
      autologon: True
      hostname: "{{ vm_name }}"
      domain: "{{ domain }}"
      fullname: "{{ local_user }}"
      password: "{{ local_password }}"
      domainadmin: "{{ domain_user }}"
      domainadminpassword: "{{ domain_password }}"
      joindomain: "{{ domain }}"
      timezone: 105
      runonce:
      - powershell.exe -ExecutionPolicy Unrestricted -File C:\StartupScripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
      - netsh advfirewall set allprofiles state off
    wait_for_customization: yes
    template: "{{ template }}"
    wait_for_ip_address: yes
```

##### ACTUAL RESULTS

Once the VM is poweredOn the vmware_guest module finishes and goes to next task which will fail because of reboots during customization.
