### ISSUE TITLE
Ansible - vmware_deploy_ovf

### ISSUE THREAD

**Issue by Davidgithub202** [ansible/ansible#67468]
##### SUMMARY

vmware_deploy_ovf fails with "Failure validating OVF import spec: The provided network mapping between OVF networks and the system network is not supported by any host."

When I run the playbook in vcenter vvc003 a VM is created

When I run the playbook in vcenter vvc006 it fails

The main difference I can see - the vcenter vvc003 as an Network “VM Network and uses "Distributed Port Groups"

The vcenter vvc006  does not have a Network and only uses "Distributed Port Groups"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_deploy_ovf

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy


```

##### OS / ENVIRONMENT

Vsphere 6.5
python2-pyvmomi-6.7.3-4.el7.noarch
Red Hat Enterprise Linux Server release 7.7 (Maipo)

##### STEPS TO REPRODUCE

```yaml
---
- name: Create VM from OVF
  hosts: all
#  any_errors_fatal: true
  serial: 1
  gather_facts: False
  ignore_errors: yes
  vars_prompt:
  - name: "user_name"
    prompt: "vCenter uname_name"
    private: no
  - name: "vmware_passwd"
    prompt: "vCenter password"
    private: yes

  tasks:

  - name: Create VM from OVF
    vmware_deploy_ovf:
      datacenter: DC-A
      hostname: "{{ vc_name }}"
      username: "{{ user_name }}"
      password: "{{ vmware_passwd }}"
      allow_duplicates: no
      name: "{{ inventory_hostname_short|upper }}"
      power_on: no
      folder: /DC-A/vm/CL-TDC2TD01-Tier3-Standard
      cluster: CL-TDC2TD01-Tier3-Standard
      datastore: CL-TDC2TD01-VNX021-TESTDEV-20
      networks:
        "F_10_107_24_0-22_V202": F_10_107_24_0-22_V202
      validate_certs: no
      ovf: /tmp/DDC2RHL005/DDC2RHL005.ovf
    delegate_to: localhost

```

##### EXPECTED RESULTS

A VM to be created

##### ACTUAL RESULTS

```paste below

# ansible-playbook -vvv -i 'djk_rhl0088,' --extra-vars "vc_name=pdc2vvc006" /app/.djk/create_vm_from_ovf.yaml
ansible-playbook 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Parsed djk_rhl0088, inventory source with host_list plugin

PLAYBOOK: create_vm_from_ovf.yaml **********************************************************************************************************************
1 plays in /app/.djk/create_vm_from_ovf.yaml
vCenter uname_name: xdavidkelly
vCenter password:

PLAY [Create VM from OVF] ******************************************************************************************************************************
META: ran handlers

TASK [Create VM from OVF] ******************************************************************************************************************************
task path: /app/.djk/create_vm_from_ovf.yaml:29
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326 `" && echo ansible-tmp-1581938978.61-204462047092326="` echo /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_deploy_ovf.py
<localhost> PUT /root/.ansible/tmp/ansible-local-3849jv0NTn/tmpCM52Q2 TO /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326/AnsiballZ_vmware_deploy_ovf.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326/ /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326/AnsiballZ_vmware_deploy_ovf.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326/AnsiballZ_vmware_deploy_ovf.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1581938978.61-204462047092326/ > /dev/null 2>&1 && sleep 0'
fatal: [djk_rhl0088 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_duplicates": false,
            "cluster": "CL-TDC2TD01-Tier3-Standard",
            "datacenter": "DC-A",
            "datastore": "CL-TDC2TD01-VNX021-TESTDEV-20",
            "deployment_option": null,
            "disk_provisioning": "thin",
            "fail_on_spec_warnings": false,
            "folder": "/DC-A/vm/CL-TDC2TD01-Tier3-Standard",
            "hostname": "pdc2vvc006",
            "inject_ovf_env": false,
            "name": "DJK_RHL0088",
            "networks": {
                "F_10_107_24_0-22_V202": "F_10_107_24_0-22_V202"
            },
            "ovf": "/tmp/DDC2RHL005/DDC2RHL005.ovf",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "power_on": false,
            "properties": null,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": "Resources",
            "username": "xdavidkelly",
            "validate_certs": false,
            "wait": true,
            "wait_for_ip_address": false
        }
    },
    "msg": "Failure validating OVF import spec: The provided network mapping between OVF networks and the system network is not supported by any host."
}
...ignoring
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************************
djk_rhl0088                : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1


```
