### ISSUE TITLE
pkg virtual package for install packages via apt\yum\zypper\dnf

### ISSUE THREAD

**Issue by 4815162342lost** [ansible/ansible#67493]
##### SUMMARY
pkg virtual package for install packages via apt\yum\zypper\dnf

##### ISSUE TYPE
- I suggest to create 'virtual' universal (platform dependence) module (for example with pkg name) for simple actions with packages (just install\delete),

I do not want write two actions with conduction such as:
```
       - name: "install multiple pckages via yum"
         yum:
           state: present
           update_cache: yes
           name:           
             - nano
             - htop
             - iotop
             - ncdu
       when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

       - name: "install multiple pckages via apt"
         apt:
           state: present
           update_cache: yes
           name:           
             - nano
             - htop
             - iotop
             - ncdu
       when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '18'
```

I just want to type 'virtual' pkg module at once:
```
       - name: "install multiple pckages "
         pkg:
           state: present
           update_cache: yes
           name:           
             - nano
             - htop
             - iotop
             - ncdu
```
Is it possible?
