### ISSUE TITLE
blockinfile not work with multiline regexp

### ISSUE THREAD

**Issue by alexz-kh** [ansible/ansible#67516]
##### SUMMARY
blockinfile not work with multiline regexp

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION
2.9.5

##### OS / ENVIRONMENT
ubuntu18 + py3 virtualenv

```paste below
ansible --version
ansible 2.9.5
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/ansible-venv/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/ansible-venv/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### STEPS TO REPRODUCE

Initial `/home/ubuntu/cluster.yaml.template` file
```yaml
      key1:
        key2:
          - name: some-operator
            values: {}
```
Task:
```yaml
- name: "Add some extra values"
  blockinfile:
    path: "/home/ubuntu/cluster.yaml.template"
    insertafter: '^.*some-operator[\s\S].*values:.*{}'
    block: |2
                  values:
                    somekey: somevalue

```

##### EXPECTED RESULTS

```yaml
      key1:
        key2:
          - name: some-operator
               values:
                  somekey: somevalue
```

##### ACTUAL RESULTS

Block has been added to EOF

### Issue related to code line
https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/files/blockinfile.py#L289-L291
Since `insertre` proceed with `line` only it's not possible to cover multi-line operations.

Might-be related: https://github.com/ansible/ansible/issues/5679
