### ISSUE TITLE
cloudwatchevent_rule using event_pattern does not create rule when using {{ Jinja2 }}

### ISSUE THREAD

**Issue by adamlbo** [ansible/ansible#67510]
##### SUMMARY
When trying to create an event_pattern with a Jinja2 template using the cloudwatchevent_rule module it fails and the event rule is not created.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloudwatchevent_rule module specifically using event_pattern with a Jinja2 template

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/aboyd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.7/bin/ansible
  python version = 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```
n/a
```

##### OS / ENVIRONMENT

macOS Mojave
Version 10.14.6 (18G3020)

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    repo: test-api

  tasks:
  - name: Create Cloudwatch event rule & set target
    cloudwatchevent_rule:
     name: "cloudwatch-event-rule-dev"
     event_pattern: "{\"detail\": {\"eventName\": [\"PutImage\"],\"eventSource\": [\"ecr.amazonaws.com\"],\"requestParameters\": {\"imageTag\": [\"latest\"],\"repositoryName\": [\"{{ vars.repo }}\"]}},\"detail-type\": [\"AWS API Call via CloudTrail\"],\"source\": [\"aws.ecr\"]}"
     description: Capture ECR Put Image
     targets:
       - id: CodePipeline
         arn: "arn:aws:codepipeline:us-west-2:1234567890:test-api"
         role_arn: arn:aws:iam::1234567890:role/access-to-codepipeline
```

##### EXPECTED RESULTS

I expected the task to create the cloudwatch event rule with the listed pattern. 

##### ACTUAL RESULTS

It seems Jinja2 is replacing the double quotes with single quotes.

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/2c/l5sn1xpj5356g22r10jx3psw9kcq6m/T/ansible_cloudwatchevent_rule_payload_3ly_1vre/ansib
le_cloudwatchevent_rule_payload.zip/ansible/modules/cloud/amazon/cloudwatchevent_rule.py", line 174, in put
  File "/Users/aboyd/Library/Python/3.7/lib/python/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/aboyd/Library/Python/3.7/lib/python/site-packages/botocore/client.py", line 626, in _make_api
_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidEventPatternException: An error occurred (InvalidEventPatternException) when ca
lling the PutRule operation: Event pattern is not valid. Reason: Unexpected character (''' (code 39)): was e
xpecting double-quote to start field name
 at [Source: (String)"{'detail': {'eventName': ['PutImage'], 'eventSource': ['ecr.amazonaws.com'], 'requestP
arameters': {'imageTag': ['latest'], 'repositoryName': ['test-api']}}, 'detail-type': ['AWS API Call via Clo
udTrail'], 'source': ['aws.ecr']}"; line: 1, column: 3]

[WARNING]: The value {'detail': {'eventName': ['PutImage'], 'eventSource': ['ecr.amazonaws.com'],
'requestParameters': {'imageTag': ['latest'], 'repositoryName': ['test-api']}}, 'detail-type': ['AWS API
Call via CloudTrail'], 'source': ['aws.ecr']} (type dict) in a string field was converted to "{'detail':
{'eventName': ['PutImage'], 'eventSource': ['ecr.amazonaws.com'], 'requestParameters': {'imageTag':
['latest'], 'repositoryName': ['test-api']}}, 'detail-type': ['AWS API Call via CloudTrail'], 'source':
['aws.ecr']}" (type string). If this does not look like what you expect, quote the entire value to ensure
it does not change.

fatal: [localhost]: FAILED! => changed=false 
  boto3_version: 1.9.226
  botocore_version: 1.15.0
  error:
    code: InvalidEventPatternException
    message: |-
      Event pattern is not valid. Reason: Unexpected character (''' (code 39)): was expecting double-quote to start field name
       at [Source: (String)"{'detail': {'eventName': ['PutImage'], 'eventSource': ['ecr.amazonaws.com'], 'requestParameters': {'imageTag': ['latest'], 'repositoryName': ['test-api']}}, 'detail-type': ['AWS API Call via CloudTrail'], 'source': ['aws.ecr']}"; line: 1, column: 3]
  invocation:
    module_args:
      aws_access_key: null
      aws_secret_key: null
      debug_botocore_endpoint_logs: false
      description: Capture ECR Put Image
      ec2_url: null
      event_pattern: '{''detail'': {''eventName'': [''PutImage''], ''eventSource'': [''ecr.amazonaws.com''], ''requestParameters'': {''imageTag'': [''latest''], ''repositoryName'': [''test-api'']}}, ''detail-type'': [''AWS API Call via CloudTrail''], ''source'': [''aws.ecr'']}'
      name: cloudwatch-event-rule-dev
      profile: null
      region: null
      role_arn: null
      schedule_expression: null
      security_token: null
      state: present
      targets:
      - arn: arn:aws:codepipeline:us-west-2:1234567890:test-api
        id: CodePipeline
        role_arn: arn:aws:iam::1234567890:role/access-to-codepipeline
      validate_certs: true
  msg: |-
    Could not create/update rule cloudwatch-event-rule-dev: An error occurred (InvalidEventPatternException) when calling the PutRule operation: Event pattern is not valid. Reason: Unexpected character (''' (code 39)): was expecting double-quote to start field name
     at [Source: (String)"{'detail': {'eventName': ['PutImage'], 'eventSource': ['ecr.amazonaws.com'], 'requestParameters': {'imageTag': ['latest'], 'repositoryName': ['test-api']}}, 'detail-type': ['AWS API Call via CloudTrail'], 'source': ['aws.ecr']}"; line: 1, column: 3]
  response_metadata:
    http_headers:
      connection: close
      content-length: '449'
      content-type: application/x-amz-json-1.1
      date: Tue, 18 Feb 2020 03:12:03 GMT
      x-amzn-requestid: 080457d0-66e8-4f84-97a5-d92605091d5a
    http_status_code: 400
    request_id: 080457d0-66e8-4f84-97a5-d92605091d5a
    retry_attempts: 0
```
