### ISSUE TITLE
netbox_device_interface module is not working properly

### ISSUE THREAD

**Issue by mahoutukaisali** [ansible/ansible#67524]
I opened this issue because no one else mentioned about the netbox_device_interface module 

##### SUMMARY

netbox_device_interface module gives different results which between loop and not loop and also between using vars file and not using vars file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- module name: netbox_device_interface

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /Users/username/python3/project/netbox/netbox-docker/ansible/ansible.cfg
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/username/py3-venv/lib/python3.7/site-packages/ansible
  executable location = /Users/username/py3-venv/bin/ansible
  python version = 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) [Clang 6.0 (clang-600.0.57)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/username/python3/project/netbox/netbox-docker/ansible/ansible.cfg) = ['/Users/username/python3/project/netbox/netbox-docker/ansible/inventories']
```

##### OS / ENVIRONMENT

macOS High Sierra 10.13.6

##### STEPS TO REPRODUCE

I first gave a number to the device part in netbox_device_interface module as a device name because I also gotten the same error message as this issue: https://github.com/ansible/ansible/issues/57948 And it succeed but the below files gives different results in the following two files.

suceed_playbook.yaml
```yaml
- name: add management interfaces
   netbox_device_interface:
     netbox_url: "{{ netbox_url }}"
     netbox_token: "{{ netbox_token }}"
     data:
       device: 1
       name: GigabitEthernet0/0

```

failed_playbook.yaml
```yaml
- name: add management interfaces
   netbox_device_interface:
     netbox_url: "{{ netbox_url }}"
     netbox_token: "{{ netbox_token }}"
     data:
          device: "{{ item.name }}"
          name: "{{ item.management.interface }}"
   loop: "{{ devices }}"

```

error message from failed_playbook
```
failed: [localhost] (item={'name': 1, 'device_type': 'Catalyst', 'device_role': 'core', 'management': {'interface': 'GigabitEthernet0/0', 'address': '10.0.1.1/24'}, 'site': 'Shinjyuku'}) => {"ansible_loop_var": "item", "changed": false, "item": {"device_role": "core", "device_type": "Catalyst", "management": {"address": "10.0.1.1/24", "interface": "GigabitEthernet0/0"}, "name": 1, "site": "Shinjyuku"}, "msg": "Could not resolve id of device: 1"}
```

vars_file.yaml (To give failed_playbook.yaml)
```yaml
devices:
  # Cisco
  # cat1
  - name: 1
    device_type: Catalyst
    device_role: core
    management:   
      interface: GigabitEthernet0/0
      address: 10.0.1.1/24
    site: Shinjyuku

  # cat2
  - name: 2
    device_type: Catalyst
    device_role: core
    management:   
      interface: GigabitEthernet0/0
      address: 10.0.1.2/24
    site: Shinjyuku

```

##### EXPECTED RESULTS

```
changed: [localhost] => {"changed": true, "interface": {"cable": null, "connected_endpoint": null, "connected_endpoint_type": null, "connection_status": null, "count_ipaddresses": 0, "description": "", "device": 1, "enabled": true, "id": 1, "lag": null, "mac_address": null, "mgmt_only": false, "mode": null, "mtu": null, "name": "GigabitEthernet0/0", "tagged_vlans": [], "tags": [], "type": null, "untagged_vlan": null}, "msg": "interface GigabitEthernet0/0 created"}
changed: [localhost] => {"changed": true, "interface": {"cable": null, "connected_endpoint": null, "connected_endpoint_type": null, "connection_status": null, "count_ipaddresses": 0, "description": "", "device": 2, "enabled": true, "id": 2, "lag": null, "mac_address": null, "mgmt_only": false, "mode": null, "mtu": null, "name": "GigabitEthernet0/0", "tagged_vlans": [], "tags": [], "type": null, "untagged_vlan": null}, "msg": "interface GigabitEthernet0/0 created"}
```

##### ACTUAL RESULTS

```
failed: [localhost] (item={'name': 1, 'device_type': 'Catalyst', 'device_role': 'core', 'management': {'interface': 'GigabitEthernet0/0', 'address': '10.0.1.1/24'}, 'site': 'Shinjyuku'}) => {"ansible_loop_var": "item", "changed": false, "item": {"device_role": "core", "device_type": "Catalyst", "management": {"address": "10.0.1.1/24", "interface": "GigabitEthernet0/0"}, "name": 1, "site": "Shinjyuku"}, "msg": "Could not resolve id of device: 1"}
failed: [localhost] (item={'name': 2, 'device_type': 'Catalyst', 'device_role': 'core', 'management': {'interface': 'GigabitEthernet0/0', 'address': '10.0.1.2/24'}, 'site': 'Shinjyuku'}) => {"ansible_loop_var": "item", "changed": false, "item": {"device_role": "core", "device_type": "Catalyst", "management": {"address": "10.0.1.2/24", "interface": "GigabitEthernet0/0"}, "name": 2, "site": "Shinjyuku"}, "msg": "Could not resolve id of device: 2"}
```

```paste below

```
