### ISSUE TITLE
synchronize module uses sshpass when dest and src are local paths

### ISSUE THREAD

**Issue by cezmunsta** [ansible/ansible#67534]
##### SUMMARY
When the host running ansible has the `ansible_ssh_pass` or `ansible_password` variables set and the `synchronize` module is used to sync 2 local paths then the module attempts to use `sshpass`. This even occurs when `connection: local` is set in the playbook.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`synchronize`

##### ANSIBLE VERSION
```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Confirmed on CentOS 7.7.1908

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: generate dummy paths
      file:
        state: directory
        path: '/tmp/{{ item }}'
      loop:
        - t1
        - t2
    - name: sync dummy files                                                                                          
      synchronize:                                                                                                          
        src: /tmp/t1
        dest: /tmp/t2
        archive: yes                                                                                                        
        checksum: yes                                                                                                       
        times: no                                                                                                           
...
```

##### EXPECTED RESULTS
The rsync completes successfully even with `ansible_ssh_pass`/`ansible_password` set.
```yaml
TASK [sync dummy files] *******************************************************************************************************************************************************************************************
Tuesday 18 February 2020  14:11:06 +0000 (0:00:00.365)       0:00:00.407 ****** 
ok: [localhost]
```

##### ACTUAL RESULTS
```yaml
TASK [sync dummy files] *******************************************************************************************************************************************************************************************
Tuesday 18 February 2020  14:10:25 +0000 (0:00:00.353)       0:00:00.395 ****** 
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "sshpass -d8 /usr/bin/rsync --delay-updates -F --compress --checksum --archive --no-times '--out-format=<<CHANGED>>%i %n%L' /tmp/t1 /tmp/t2", "msg": "[Errno 32] Broken pipe", "rc": 32}
```
