### ISSUE TITLE
aws_ec2 inventory: Add ability to add host to multiple groups from a single tag.

### ISSUE THREAD

**Issue by adamdonahue** [ansible/ansible#67537]
##### SUMMARY

It'd be useful if one could assign a host to multiple groups via a single tag.

For example, let's say we've tagged an EC2 host with the name `ansible-groups` and the value `prometheus-hosts,jump-hosts`.  What we'd like is that given the `keyed_groups` setting, the following entry:

```yaml
keyed_groups:
  - key: tags["ansible-groups"]
    prefix: ""
    separator: ""
    value_separator: ","    # A new setting.
```

resulted in the addition of the host to the groups:

* `prometheus-hosts`; and
* `jump-hosts`

[If there is another means of doing this without a custom dynamic inventory script, please let me know.]

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`aws_ec2.py`

##### ADDITIONAL INFO

Interested in community discussion of this.  If it's something people would find of value, I can implement.
