### ISSUE TITLE
Filter ipv6 address with ipsubnet runs into endless loop with high CPU usage

### ISSUE THREAD

**Issue by trickert76** [ansible/ansible#67541]
##### SUMMARY

When I use the following playbook with ansible v.2.9.5, the CPU usage goes to 100% and after minutes of waiting there is no response in step 2 (it hangs).

I would expect, that the ip address is used to create a 96-subnet.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

?

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
```
I'm also using:
  - netaddr v0.7.19

##### CONFIGURATION

clean install:
 * `apt-get install python3-pip`
 * `pip3 install ansible netaddr`

##### OS / ENVIRONMENT

 * MacOS
 * Linux Debian 10.3

##### STEPS TO REPRODUCE

```yaml
    - name: My Test
      hosts: localhost
      gather_facts: no
      tasks:
        - name: "step1"
          set_fact:
            service_subnet_ipv6: "{{ 'fc00:2000::/64' | ipaddr }}"
        - name: "step2"
          set_fact:
            my_subnet_ipv6: "{{ service_subnet_ipv6 | ipsubnet(96,1000) }}"
        - name: "step3"
          debug:
            msg: "{{ my_subnet_ipv6 }}"
```

##### EXPECTED RESULTS

I would expect, the "Step 3" returns a subnet of the `service_subnet_ipv6`.

##### ACTUAL RESULTS

```paste below

$ ansible-playbook test.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [My Test] ***********************************************************

TASK [set default facts] *************************************************
ok: [localhost]

TASK [set instance facts ipv6] *******************************************


```
