### ISSUE TITLE
os_coe_cluster expects uuid while openstacksdk return uuid.

### ISSUE THREAD

**Issue by brtkwr** [ansible/ansible#67576]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- os_coe_cluster

##### ANSIBLE VERSION

```paste below
ansible 2.9.0.dev0
  config file = None
  configured module search path = [u'/opt/bharat/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/bharat/ansible/lib/ansible
  executable location = /opt/bharat/venv-openstack/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Try to create a cluster:
```yaml
- os_coe_cluster:
    name: k8s
    cluster_template_id: k8s-ha
    keypair: mykey
    master_count: 3
    node_count: 5
```

##### EXPECTED RESULTS

Create a cluster. If the cluster already exists, obtain the cluster id.

##### ACTUAL RESULTS

```paste below

```
uuid key does not exist in the resulting output.
