### ISSUE TITLE
module rabbitmq_users - permissions with vhost failing

### ISSUE THREAD

**Issue by DEvil0000** [ansible/ansible#67572]
##### SUMMARY
when creating a user with permission to a vhost it fails (maybe only on changes).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rabbitmq_user

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 19 2019, 09:25:23) [GCC 9.2.1 20191130]
```

##### OS / ENVIRONMENT
ubuntu 20.04

##### STEPS TO REPRODUCE
```yaml
- name: Configure rabbitmq users
  tasks:
    rabbitmq_user:
      user: "{{ item.name }}"
      password: "{{ item.password | default(omit) }}"
      permissions: "{{ item.permissions | default([]) }}"
      tags: "{{ item.tags | default(omit) }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ rabbitmq_users }}"
    notify: restart rabbitmq
  vars:
    rabbitmq_users: 
    - name: xxx
      password: xxx
      permissions:
      - vhost: xxx
        configure_priv: .*
        read_priv: .*
        write_priv: .*
```
##### EXPECTED RESULTS
change user permissions

##### ACTUAL RESULTS
failing due to incorrect parameter in command executed
```paste below
failed: [localhost] (item={'name': 'xxx', 'password': 'xxx', 'permissions': [{'vhost': 'xxx', 'configure_priv': '.*', 'read_priv': '.*', 'write_priv': '.*'}]}) => changed=false 
  ansible_loop_var: item
  cmd: /usr/sbin/rabbitmqctl -q -n rabbit clear_permissions -p vhost VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
  item:
    name: xxx
    password: xxx
    permissions:
    - configure_priv: .*
      read_priv: .*
      vhost: xxx
      write_priv: .*
  msg: Virtual host 'vhost' does not exist
  rc: 65
  stderr: |-
    Virtual host 'vhost' does not exist
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
