### ISSUE TITLE
Subelements filter can not descend into list items

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#67608]
##### SUMMARY

`subelements` filter can only descend into dicts, but not list elements, which is inconsistent with other filters like `map`, `selectattr`, etc

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

filter/core.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Vars:
```yaml
testvar:
  abc:
    name: foo
    items:
      - a
      - b
  def:
    name: bar
    items:
      - e
      - f
```
Construct:
```
testvar|dictsort|subelements('1.items')
```

##### EXPECTED RESULTS

```
- - - abc
    - items:
      - a
      - b
      name: foo
  - a
- - - abc
    - items:
      - a
      - b
      name: foo
  - b
- - - def
    - items:
      - e
      - f
      name: bar
  - e
- - - def
    - items:
      - e
      - f
      name: bar
  - f
```
This way I could iterate over dicts with subelements, accessing original keys as `item.0.0`, original attributes via `item.0.1` and current subelement as `item.1`

##### ACTUAL RESULTS

```paste below
'the key 1 should point to a dictionary, got ''(''abc'', {''name'': ''foo'', ''items'': [''a'', ''b'']})'''
```
There is a workaround: inserting `map(attribute='1')|list` before `subelements`, but original dict keys are inaccessible this way.

`subelements` inability to descend into `'1.something'` is incosnsistent with other filters. For example `map(attribute='1.something')` works, as does `selectattr('1.something', 'defined')`.
