### ISSUE TITLE
Add CVE support to the yum module

### ISSUE THREAD

**Issue by Wordsgames** [ansible/ansible#67609]
#### SUMMARY

I try to Update security only all CVE create by UpdateCVE.yml but i can't, so i tried to select the cve.
It does not find except in the rhel "host" yes

##### ANSIBLE 

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
##### ISSUE TYPE
- Feature Idea

##### STEPS TO REPRODUCE

```
---
- name: Update CVE for rhel
  hosts: rhel
  tasks:
  - name: yum update cve
    yum:
      name: ['CVE-2019-9636', 'CVE-2019-12735']
    tags: update --cve

```
##### COMPONENT NAME

`lib/ansible/modules/packaging/os/yum.py`

##### EXPECTED RESULTS

He should running udpate cve without issue

##### ACTUAL RESULTS

```
fatal: [host]: FAILED! => {"changed": false, "msg": "No package matching 'CVE-2019-9636' found available, installed or updated", "rc": 126, "results": ["No package matching 'CVE-2019-9636' found available, installed or updated"]}
```
It's my first time to create a yml but i'm little confused
I need help correcting my yml file and your advice for yml
