### ISSUE TITLE
win_dns_record: Support Round Robin Record Addition

### ISSUE THREAD

**Issue by OnceUponALoop** [ansible/ansible#67628]
##### SUMMARY
To support round robin we need to add multiple A records with identical names but different IP addresses. 

This is not currently possible with the module - if multiple identical names are used the last one is the only one added to the DNS server.

Maybe a `unique` flag could be added to account for this use-case?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_record

##### ADDITIONAL INFORMATION

**Example Usage**

```yaml
- name: "Oracle | add scan ips to dns"
  win_dns_record:
    name: oracle-rac-scan
    type: "A"
    value: "{{ item }}"
    zone: "test.example.lan"
  loop:
    - '192.168.10.101'
    - '192.168.10.102'
    - '192.168.10.103'
```

**Current Behavior/Result**

``` bash
# dig +nocmd oracle-rac-scan.test.example.lan any +multiline +noall +answer
oracle-rac-scan.test.example.lan. 3600 IN A 192.168.10.103
```

**Desired Behavior/Result**

``` bash
# dig +nocmd oracle-rac-scan.test.example.lan any +multiline +noall +answer
oracle-rac-scan.test.example.lan. 3600 IN A 192.168.10.103
oracle-rac-scan.test.example.lan. 3600 IN A 192.168.10.102
oracle-rac-scan.test.example.lan. 3600 IN A 192.168.10.101
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_dns_record.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_dns_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @johnboy2
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by johnboy2** [comment]
TLDR; try this:
```
- name: "Oracle | add scan ips to dns"
  win_dns_record:
    name: oracle-rac-scan
    type: "A"
    values:
     - '192.168.10.101'
     - '192.168.10.102'
     - '192.168.10.103'
    zone: "test.example.lan"
```

I think this is really a documentation issue.

This module treats the pair (`name`, `type`) as the fundamental unit, even though that's not really how DNS works. It does this because treating `value` (or its `values` alias) as potentially multi-valued is just easier for non-experts to understand. That said, this never made it into any examples (or even the integration tests, now that I've checked).

So let me know if that works, and if so, I'll spin off another issue to fix up the docs and tests.
