### ISSUE TITLE
Allow specifying more complex metrics for Cloudwatch Alarms in ec2_metric_alarm

### ISSUE THREAD

**Issue by willhughes-au** [ansible/ansible#67636]
##### SUMMARY
When using Cloudwatch Alarms, sometimes it is desirable to be able to use more than basic / single metrics. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_metric_alarm

##### ADDITIONAL INFORMATION

This would be useful if you were trying to have an Autoscaling group scale based upon the number of messages in multiple SQS queues. 

This is possible via the AWS CLI and the --metrics parameter as described on the AWS CLI Documentation for put-metric-alarm at: https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html 

Example of how this feature might be used: 

```

- name: Configure Metric Alarms based on sum of SQS Queue 'queue-1' and 'queue-2' messages visible
  ec2_metric_alarm:
    name: "pending-messages-in-queues"
    state: present
    alarm_actions: "{{ scale_up_actions }}"
    ok_actions: "{{ scale_down_actions }}"

    metrics: 
      - id: e1
        expression: "SUM(METRICS())"
        label: "total_queue_size"
        return_data: true

      - id: m1
        return_data: false

        namespace: "AWS/SQS"
        name: "ApproximateNumberOfMessagesVisible"
        dimensions: 
          - name: QueueName 
            value: queue-1
        period: 60
        statistic: average

      - id: m2
        return_data: false

        namespace: "AWS/SQS"
        name: "ApproximateNumberOfMessagesVisible"
        dimensions: 
          - name: QueueName 
            value: queue-2
        period: 60
        statistic: average
    
    comparison: "GreaterThanOrEqualToThreshold"
    threshold: "10"
    evaluation_periods: 1 

```
