### ISSUE TITLE
jenkins_job_info validate_certs failed

### ISSUE THREAD

**Issue by ripoul** [ansible/ansible#67646]
##### SUMMARY

I use the module `jenkins_job_info` on my personnal jenkins server. I have to use `validate_certs` argument set to False but my task send me an error :
```
Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

jenkins_job_info

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /home/jlebris/.ansible.cfg
  configured module search path = ['/home/jlebris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/virtualenv/python3.7/molecule/lib/python3.7/site-packages/ansible
  executable location = /opt/virtualenv/python3.7/molecule/bin/ansible
  python version = 3.7.5 (default, Nov 15 2019, 17:00:24) [GCC 8.3.0]
```

##### CONFIGURATION

```
ANSIBLE_SSH_CONTROL_PATH(/home/jlebris/.ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/home/jlebris/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/jlebris/.ansible.cfg) = /tmp/ansible_fact_cache
CACHE_PLUGIN_TIMEOUT(/home/jlebris/.ansible.cfg) = 86400
DEFAULT_FORKS(/home/jlebris/.ansible.cfg) = 10
DEFAULT_GATHERING(/home/jlebris/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/jlebris/.ansible.cfg) = ['/home/jlebris/inventories/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/jlebris/.ansible.cfg) = /home/jlebris/.ansible/.vault_pass
DISPLAY_SKIPPED_HOSTS(/home/jlebris/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/jlebris/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

##### STEPS TO REPRODUCE

Create a task with jenkins_job_info with validate_certs set to false. The url used has to have a self signed ssl certificate.

```yaml
- name: "Check if job {{ item }} exists"
  jenkins_job_info:
    name: "{{ item }}"
    token: "{{ templates.jenkins.admin_token }}"
    url: "{{ templates.jenkins.url }}"
    user: "{{ templates.jenkins.admin_user }}"
    validate_certs: False
```

##### EXPECTED RESULTS

the task have to succeed

##### ACTUAL RESULTS

```
The error was: requests.exceptions.SSLError: HTTPSConnectionPool(host='my-jenkins.com', port=443): Max retries exceeded with url: /crumbIssuer/api/json (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```
