### ISSUE TITLE
/tmp/.ansible ownership issues with non-root remote_user

### ISSUE THREAD

**Issue by parmstro** [ansible/ansible#67667]
##### SUMMARY

After creating a new non-root ansible user, new user is unable to perform actions that require write access to /tmp/.ansible due to ownership /tmp/.ansible. Deleting /tmp/.ansible on managed host prior to running plays with the new non-root user resolves the issue. Running the same play with remote_user: root succeeds without deleting or changing ownership of the /tmp/.ansible directory. All appropriate sudo permissions are in place. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible
##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /home/parmstro/Projects/ansible/ansible_user/ansible.cfg
  configured module search path = ['/home/parmstro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/parmstro/Projects/ansible/ansible_user/ansible.cfg) = True
COLOR_VERBOSE(/home/parmstro/Projects/ansible/ansible_user/ansible.cfg) = bright green
DEFAULT_KEEP_REMOTE_FILES(/home/parmstro/Projects/ansible/ansible_user/ansible.cfg) = False
DEFAULT_ROLES_PATH(/home/parmstro/Projects/ansible/ansible_user/ansible.cfg) = ['/etc/ansible/roles', '/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

2 basic test servers, both patched to latest
1 baremetal running RHEL 8.1 
1 vm on vmware running RHEL 7.7 

##### STEPS TO REPRODUCE

See below.

```yaml
# inventory
rme.parmstrong.ca
floyd-marentis.parmstrong.ca

ansible_user.yml
# Create the user running as me who has full sudo perms
# example username=ansible password=simple
# 
---
- name: Create the ansible user
  hosts: all
  become: true
  become_method: sudo  
  vars_prompt:
    - name: username
      prompt: "Enter the username for the ansible user:"
    - name: password
      prompt: "Enter the password for the user:"
      private: true

  vars:
    username: ""
    password: ""


  tasks:

    - name: "Clean up. This play succeeds if I have cleaned up first (repetitive runs)"
      file:
        path: "/tmp/.ansible"
        state: absent

    - name: "ensure python is installed correctly"
      package:
        name: python3
        state: latest

    - name: "generate the password hash to use with ansible"
      command: python3 -c "import crypt; print(crypt.crypt('{{ password }}'))"
      register: result

    - set_fact:
        enc_pass: "{{ result.stdout }}"

    - name: "create the new user on target"
      user:
        name: "{{ username }}"
        password: "{{ enc_pass }}"
        state: present
        update_password: always
        shell: "/bin/bash"

    - name: "ensure the ssh directory exists"
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0700 

    - name: "copy the ssh keys"
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: "add user to sudoers"
      copy: 
        dest: "/etc/sudoers.d/ansible"
        content: "{{ username }}     ALL=(ALL)     NOPASSWD: ALL"

# If you uncomment these lines all the tests in the play below succeed.
#    - name: "Clean up"
#      file:
#        path: "/tmp/.ansible"
#        state: absent


testuser.yml
# Test the new user
---
# This is a test play to determine if the testuser can 
# run plays from this directory against the specified hosts
#

- name: "Test Play"
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
# succeeds
  - name: "Capture the stdout of a command"
    command: "hostnamectl status"
    register: result
# succeeds
  - name: "Display the output"
    debug:
      msg: "{{ result.stdout }}"
# succeeds - requires root access
  - name: "Access something restricted"
    command: "cat /etc/grub2.cfg"
# fails with error below.
  - name: "Copy a file"
    copy:
      src: "/etc/fstab"
      dest: "/tmp/junk"
      remote_src: yes

  - name: "Remove the copied file"
    file:
      path: "/tmp/junk"
      state: absent
```

##### EXPECTED RESULTS

All tests should succeed. 

##### ACTUAL RESULTS

```paste below
...successful output omitted...
TASK [Copy a file] ***************************************************************************************************************************************************************************
task path: /home/parmstro/Projects/ansible/ansible_user/testplay.yml:25
<rme.parmstrong.ca> ESTABLISH SSH CONNECTION FOR USER: ansible2
<rme.parmstrong.ca> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible2"' -o ConnectTimeout=10 -o ControlPath=/home/parmstro/.ansible/cp/268540088a rme.parmstrong.ca '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0313132-27631582421008 `" && echo ansible-tmp-1582346827.0313132-27631582421008="` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0313132-27631582421008 `" ) && sleep 0'"'"''
<floyd-marentis.parmstrong.ca> ESTABLISH SSH CONNECTION FOR USER: ansible2
<floyd-marentis.parmstrong.ca> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible2"' -o ConnectTimeout=10 -o ControlPath=/home/parmstro/.ansible/cp/d892e909c1 floyd-marentis.parmstrong.ca '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0383408-228388822456465 `" && echo ansible-tmp-1582346827.0383408-228388822456465="` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0383408-228388822456465 `" ) && sleep 0'"'"''
<floyd-marentis.parmstrong.ca> (1, b'', b'mkdir: cannot create directory \xe2\x80\x98/tmp/.ansible\xe2\x80\x99: Permission denied\n')
<floyd-marentis.parmstrong.ca> Failed to connect to the host via ssh: mkdir: cannot create directory ‘/tmp/.ansible’: Permission denied
fatal: [floyd-marentis.parmstrong.ca]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0383408-228388822456465 `\" && echo ansible-tmp-1582346827.0383408-228388822456465=\"` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0383408-228388822456465 `\" ), exited with result 1",
    "unreachable": true
}
<rme.parmstrong.ca> (1, b'', b'mkdir: cannot create directory \xe2\x80\x98/tmp/.ansible\xe2\x80\x99: Permission denied\n')
<rme.parmstrong.ca> Failed to connect to the host via ssh: mkdir: cannot create directory ‘/tmp/.ansible’: Permission denied
fatal: [rme.parmstrong.ca]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0313132-27631582421008 `\" && echo ansible-tmp-1582346827.0313132-27631582421008=\"` echo /tmp/.ansible/tmp/ansible-tmp-1582346827.0313132-27631582421008 `\" ), exited with result 1",
    "unreachable": true
}

```
