### ISSUE TITLE
My task is fail with failed_when_result has true

### ISSUE THREAD

**Issue by zak39** [ansible/ansible#67687]
##### SUMMARY

Hello there :)

I have a problem with a task has fail but the failed_when_result has true.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = None
  configured module search path = [u'/home_user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

There my task.

```yaml
failed_when: 
  - command_result.rc == 10
  - "'[ERROR] Aucune instance dont portant ce sid' in command_result.stdout"

  - name: "Locker les users"
    command: "sshpass -p {{ password }} ssh {{ user }}@{{ item }} bash /home_user/lockUser.sh"
    delegate_to: localhost
    when: 
      - ( "{{ environnement.stdout }}" == "rct" ) or
        ( "{{ environnement.stdout }}" == "qal" ) or
        ( "{{ environnement.stdout }}" == "prd" )
      - _NB_EXTRA_TAGS == "0"
      - ( "{{ _STATE_ROBOT }}" == "robot:auto" ) or
        ( "{{ _STATE_ROBOT }}" == "robot:force" )
    register: command_result
    failed_when: 
      - command_result.rc == 10
      - "'[ERROR] Aucune instance ' in command_result.stdout"
    with_items: "{{ inventory_hostname }}"
```

And its result.

```
failed: [my_host_remote -> localhost] (item=my_host_remote) => {
      "ansible_loop_var": "item", 
      "changed": true, 
      "cmd": [
          "sshpass", 
          "-p", 
          "my_password", 
          "ssh", 
          "my_local_user@my_host_remote", 
          "bash", 
          "/path_user/lockUser.sh"
      ], 
      "delta": "0:00:00.724550", 
      "end": "2020-02-24 09:21:23.463125", 
      "failed_when_result": true, 
      "invocation": {
          "module_args": {
              "_raw_params": "sshpass -p my_password ssh my_local_user@my_host_remote bash /path_user/lockUser.sh", 
              "_uses_shell": false, 
              "argv": null, 
              "chdir": null, 
              "creates": null, 
              "executable": null, 
              "removes": null, 
              "stdin": null, 
              "stdin_add_newline": true, 
              "strip_empty_ends": true, 
              "warn": true
          }
      }, 
      "item": "my_host_remote", 
      "msg": "non-zero return code", 
      "rc": 10, 
      "start": "2020-02-24 09:21:22.738575", 
      "stderr": "", 
      "stderr_lines": [], 
      "stdout": "[ERROR] Aucune instance dont portant ce sid TOTO dans le serveur distant", 
      "stdout_lines": [
          "[ERROR] Aucune instance dont portant ce sid TOTO dans le serveur distant"
      ]
  }
```

I don't understand why itsn't work...

I am sorry if it's the bad issue for my case. It's my first issue on GitHub ^^'
