### ISSUE TITLE
azure_rm_manageddisk attach_caching not working

### ISSUE THREAD

**Issue by martinuu** [ansible/ansible#67702]
##### SUMMARY

Attach _caching not set for managed disk.  azure_rm_manageddisk called with these arguments (so attach_caching with read_only):
```
- name: Adding of additional disks
  azure_rm_manageddisk:
        #lun: "{{ item.lun }}"
        name: "{{ vm_name }}_disk_{{ idx }}"        
        managed_by: "{{ vm_name }}"
        disk_size_gb: "{{ item.disk_size_gb }}"
        location: "{{ location }}"       
        resource_group: "{{ resource_group }}"        
        storage_account_type: "{{ item.disk_type }}"
        attach_caching: read_only   #"{{ item.caching }}"
  loop: "{{ data_disks }}"
  loop_control: 
    index_var: idx
```

but and in the invocation attach_caching is with null value and so not set for the disk at the end:
```
"invocation": {
        "module_args": {
            "ad_user": null, 
            "adfs_authority_url": null, 
            "api_profile": "latest", 
            "append_tags": true, 
            "attach_caching": null, 
            "auth_source": null, 
            "cert_validation_mode": null, 
            "client_id": null, 
            "cloud_environment": "AzureCloud", 
            "create_option": null, 
            "disk_size_gb": 64, 
            "location": "westeurope", 
            "managed_by": "test509", 
            "name": "test509_disk_0", 
            "os_type": null, 
            "password": null, 
            "profile": null, 
            "resource_group": "rg-dev-app-shared-001", 
            "secret": null, 
            "source_uri": null, 
            "state": "present", 
            "storage_account_type": "StandardSSD_LRS", 
            "subscription_id": null, 
            "tags": null, 
            "tenant": null, 
            "zone": null
        }
    },
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_manageddisk

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /home/LS/0ulrichma/.ansible.cfg
  configured module search path = [u'/home/LS/0ulrichma/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
