### ISSUE TITLE
Role in collection doesn't search roles_path for roles

### ISSUE THREAD

**Issue by Legogris** [ansible/ansible#67723]
##### SUMMARY
Using a role from a collection that is itself referencing a role from another collection result in that role not being found.

Here, I am including the role `cryptsetup`, found in the collection `debops.roles03`. It is itself importing the role `secret`. It ignores `DEFAULT_ROLES_PATH` and the defined `collections` when searching.

Included as below:
```
- name: Set up LUKS
  tags: luks
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  block:
    - name: Configure LUKS volume
      tags: cryptsetup
      include_role:
        name: cryptsetup
      vars:
        ciphertext_block_device: '/dev/loop0'
      loop: "{{ cryptdisks }}"
```

The role `secret` is present at `vendor/ansible_collections/debops/debops/roles/secret`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /.../ansible.cfg
  configured module search path = ['/home/legogris/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/legogris/dev/homelab/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/home/legogris/dev/homelab/ansible/ansible.cfg) = ['/home/legogris/dev/homelab/ansible/vendor/ansible_collections', '/home/legogris/dev/homelab/ansible/vendor']
DEFAULT_BECOME_ASK_PASS(/home/legogris/dev/homelab/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/legogris/dev/homelab/ansible/ansible.cfg) = 20
DEFAULT_ROLES_PATH(/home/legogris/dev/homelab/ansible/ansible.cfg) = ['/home/legogris/dev/homelab/ansible/roles', '/home/legogris/dev/homelab/ansible/vendor', '/home/legogris/dev/homelab/ansible/vendor/ansible_collections/debops/debops/roles']
DEFAULT_STRATEGY(/home/legogris/dev/homelab/ansible/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/legogris/dev/homelab/ansible/ansible.cfg) = ['/home/legogris/dev/homelab/ansible/plugins/mitogen-0.2.9/ansible_mitogen/plugins/strategy']
```

##### OS / ENVIRONMENT
Arch Linux

##### EXPECTED RESULTS
Role is imported in included role.

##### ACTUAL RESULTS

```
ERROR! the role 'secret' was not found in debops.roles03:ansible.builtin

The error appears to be in '/home/legogris/dev/homelab/ansible/vendor/ansible_collections/debops/roles03/roles/cryptsetup/tasks/main.yml': line 7, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- import_role:
    name: 'secret'
          ^ here
```
