### ISSUE TITLE
Enable retry mechanism when dynamic inventory related api calls fail temporarily

### ISSUE THREAD

**Issue by f3rdy** [ansible/ansible#67725]
##### SUMMARY

We have the current issue that our inventory setup in the azure cloud is based upon dynamic inventory plugin where we fetch the given virtual machines for an environment dynamically using the ansible dynamic inventory plugin.

Since the azure API is not always responding to these requests thus being unstable temporarily, we already implemented a mechanism to check up the amount of expected hosts. Of course, this renders the whole dynamic inventory issue obsolete and we might go with defining the inventory statically completely.

I want to suggest a retry mechanism for failing or timeouted dynamic inventory plugins, especially in our case for MS Azure.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

dynamic inventory plugin (azure)

##### ADDITIONAL INFORMATION

Having this feature would greatly improve stability of the dynamic inventory plugin related connection issues or other problems related to API responds that are false negatives.

```yaml
# file: env-i.azure_rm.yml

plugin: azure_rm

batch_fetch: false

# specifying the resourcegroups explicitely fastens the lookup
include_vm_resource_groups:
    - R20-WE-ENV-I
    - R03-WE-COMMON-DEV-ENV

keyed_groups:
    # places each host in a group named 'tag_(tag name)_(tag value)' for each tag on a VM.
    - prefix:  'tag'
      key: tags
    # places each host in a group named 'azure_loc_(location name)', depending on the VM's location
    - prefix: azure_loc
      key: location
```
