### ISSUE TITLE
module zypper - state: absent not work with extra_args "--clean-deps' 

### ISSUE THREAD

**Issue by jbudev** [ansible/ansible#67737]
##### SUMMARY

module zypper - state: absent not work with extra_args "--clean-deps'
 
Uninstall packages with clean all recommends does not work in ansible. Module "package" has no Options. Module "zypper" not support sub commnd options.

state: absend --> "zypper remove ..."
extra_args: '--clean-deps' --> "zypper remove --clean-deps"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module zypper uninstall packages

##### ANSIBLE VERSION

```
ansible 2.8.1
  config file = ..../ansible/ansible.cfg
  configured module search path = [u'.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(<...PATH...>ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(<...PATH...>ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s -o ServerAliveInterval=150
ANSIBLE_SSH_CONTROL_PATH(<...PATH...>ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p
COMMAND_WARNINGS(<...PATH...>ansible/ansible.cfg) = False
DEFAULT_BECOME_ASK_PASS(<...PATH...>ansible/ansible.cfg) = True
DEFAULT_CALLBACK_PLUGIN_PATH(<...PATH...>ansible/ansible.cfg) = [u'<...PATH...>ansible/callback_plugins']
DEFAULT_FORCE_HANDLERS(<...PATH...>ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(<...PATH...>ansible/ansible.cfg) = [u'<...PATH...>ansible/hosts']
DEFAULT_LOG_FILTER(<...PATH...>ansible/ansible.cfg) = [u'paramiko.transport']
DEFAULT_LOG_PATH(<...PATH...>ansible/ansible.cfg) = <...PATH...>log/ansible.log
DEFAULT_MANAGED_STR(<...PATH...>ansible/ansible.cfg) =
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
This file is managed by ansible!
Source template (on {host}): {file}
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEFAULT_STDOUT_CALLBACK(<...PATH...>ansible/ansible.cfg) = 1_XXX_default
DEPRECATION_WARNINGS(<...PATH...>ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(<...PATH...>ansible/ansible.cfg) = False
INTERPRETER_PYTHON(<...PATH...>ansible/ansible.cfg) = auto_silent
PARAMIKO_HOST_KEY_AUTO_ADD(<...PATH...>ansible/ansible.cfg) = True
RETRY_FILES_ENABLED(<...PATH...>ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
```

##### STEPS TO REPRODUCE

```
- name: BuildModules | install needed packages
   become: true
   zypper:
     name:
       - gcc
       - make
       - kernel-devel
       - kernel-default-devel
     state: present
     disable_recommends: yes

- name: BuildModules | uninstall needed packages
   become: true
   zypper:
     name:
       - gcc
       - make
       - kernel-devel
       - kernel-default-devel
     state: absent
     extra_args "--clean-deps' 
```

##### EXPECTED RESULTS

Install needed packages for building kernel modules. --> OK
Build the kernel module. --> OK 
Uninstall the packages with all clean all deps. --> Failed!

##### ACTUAL RESULTS

Failed. Packages not uninstalled.

```
FAILED! => {"changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "--disable-repositories", "search", "--type", "package", "--clean-deps", "--match-exact", "--details", "--installed-only", "gcc", "make", "kernel-devel", "kernel-default-devel"], "msg": "Zypper run command failed with return code 2.", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<message type=\"error\">Flag --clean-deps ist unbekannt.</message>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<message type=\"error\">Flag --clean-deps ist unbekannt.</message>", "</stream>"]}

stdout:
<?xml version='1.0'?>
<stream>
<message type="error">Flag --clean-deps ist unbekannt.</message>
</stream>
```
