### ISSUE TITLE
Deprecation warning shows key and values in the output

### ISSUE THREAD

**Issue by Saurabh-Thakre** [ansible/ansible#67735]
##### SUMMARY

While running the playbook with deprecation warning enabled, it is showing key and value defined in the playbook.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Apr  3 2019, 17:26:03) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 8.

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  gather_facts: false
  vars:
    zboni_jboss_vault_values:
      key: "password"
      value: "mysecret"
  tasks:
  - command: "echo key:{{ item.key }} value{{item.value}}"
    with_items:
      - "{{ zboni_jboss_vault_values }}"
    when: zboni_jboss_vault_values
```

##### EXPECTED RESULTS

It should not show the key value in the deprecation warnings as we are doing **no_log:true** to hide the key and value.

##### ACTUAL RESULTS

```
# ansible-playbook dep.yml 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [command] ****************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: evaluating {'key': 'password', 'value': 'mysecret'} as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see 
CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [localhost] => (item=None)
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
