### ISSUE TITLE
Block with when always set facts

### ISSUE THREAD

**Issue by js-max** [ansible/ansible#67736]
##### SUMMARY
`set_fact` is being executed inside `block` even `when` conditional is `FALSE`.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
[...redacted...]
  python version = 3.7.3 (default, Sep  5 2019, 17:14:41) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### OS / ENVIRONMENT
MacOS
Working with Python 3 venv

##### STEPS TO REPRODUCE
`set_fact` is being executed inside `block` even `when` conditional is false

```yaml
  - name: Block 01
    block:

      - name: Inside block mapping
        set_fact:
          X_mapping: "{{ X_mapping | default([]) + [ item ] }}"
        with_items:
          - "{{ lookup('file', '/X/Y.file').split('\n') | list | select() | list }}"

      - name: Inside block
        debug:
          msg: Get in

    tags: test
    when: "'WORD' in wordvar" 
```

##### EXPECTED RESULTS
`set_fact` inside `block` only should be executed if `when` conditional is `TRUE`

##### ACTUAL RESULTS
Because `block` conditional is not being respected, `set_fact` is being executed.

```paste below
fatal: [127.0.0.1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /X/Y.file"
}
```

Without `set_fact` everything work as expected.

It's working as expected?
Tried to search on **issues** or even **Ansible Docs** but was not able to find something useful (or maybe with wrong keywords).
