### ISSUE TITLE
vmware_guest_file_operation cannot copy file from host to VM

### ISSUE THREAD

**Issue by jhb31** [ansible/ansible#67743]
##### SUMMARY
Hello, i'm trying to copy a file to a VM from Ansible host. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_file_operation

##### ANSIBLE VERSION
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

##### CONFIGURATION
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /opt/ansible/log/ansible.log

##### OS / ENVIRONMENT
RHEL 7

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  tasks:
  - name: Including Secret Environment Items
    include_vars: 
      file: secrets.yml
      name: secret
        
  - name: Including Var Environment Items
    include_vars:
      file: vars.yml
      name: var

  - name: Copy UEM files to Master
    vmware_guest_file_operation:
      hostname: "{{var.vcentername}}"
      username: "{{secret.username}}"
      password: "{{secret.password}}"
      datacenter: "{{var.datacentername}}"
      validate_certs: no
      vm_id: "{{var.mastername}}"
      vm_username: "{{secret.username}}"
      vm_password: "{{secret.password}}"
      copy:
          src: "/opt/ansible/test.txt"
          dest: "C:/Temp/test.txt"
          overwrite: False
    delegate_to: localhost
```

##### EXPECTED RESULTS
File copied to VM

##### ACTUAL RESULTS
```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cluster": null,
            "copy": {
                "dest": "C:/Temp/test.txt",
                "overwrite": false,
                "src": "/opt/ansible/test.txt"
            },
            "datacenter": "x",
            "directory": null,
            "fetch": null,
            "folder": null,
            "hostname": "x",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "username": "x",
            "validate_certs": false,
            "vm_id": "EPVXXXZJB",
            "vm_id_type": "vm_name",
            "vm_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vm_username": "x"
        }
    },
    "msg": "problem during file transfer, http message:{'status': 500, 'body': '<error>\\n   <errorCode>22</errorCode>\\n   <errorInfo>The file name is not valid</errorInfo>\\n</error>', 'content-length': '98', 'x-xss-protection': '1', 'x-content-type-options': 'nosniff', 'content-security-policy': 'block-all-mixed-content', 'url': 'https://xx.xx.xx.xx:443/guestFile?id=4&token=52836156-5da2-efe4-398b-29be3dcfde994', 'strict-transport-security': 'max-age=31536000', 'msg': 'HTTP Error 500: Internal Server Error', 'connection': 'close', 'date': 'Tue, 25 Feb 2020 16:09:00 GMT', 'x-frame-options': 'DENY', 'content-type': 'text/plain; charset=utf-8'}",
    "uuid": "4207ea05-5df7-66df-c1e6-5dfd742b392f"
}

```
