### ISSUE TITLE
ec2_key - force only forces if key material is provided

### ISSUE THREAD

**Issue by jjshoe** [ansible/ansible#67746]
##### SUMMARY
 Force only forces if key material is provided. If you let it create a private key for you, then try to create again with force: True, you'll get back a success, and a message about the key already existing

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_key.py#L192

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_key

##### STEPS TO REPRODUCE
```yaml
    - ec2_key:
        name: gitlab-runner
        force: Yes
    - ec2_key:
        name: gitlab-runner
        force: Yes
      register: ssh_key_detail
    - debug:
        var: ssh_key_detail
```

##### EXPECTED RESULTS
The old key to be deleted, and a new key to be made, returning the new private key data

##### ACTUAL RESULTS
`ok`, when what's expected is a `changed`, with a registered variable containing the new private key

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/amazon/ec2_key.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_key.py)
* [`lib/ansible/modules/source_control/gitlab/gitlab_runner.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab/gitlab_runner.py)
* [`lib/ansible/modules/utilities/logic/debug.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/debug.py)
* [`lib/ansible/parsing/utils/yaml.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jjshoe: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Lunik @SamyCoenen @Shaps @dagwieers @dj-wasabi @jillr @jlozadad @marwatk @prasadkatti @s-hertel @tremble @waheedi @zbal
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jjshoe, just so you are aware we have a dedicated Working Group for aws.
You can find other people interested in this in `#ansible-aws` on Freenode IRC
For more information about communities, meetings and agendas see https://github.com/ansible/community

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jjshoe** [comment]
looks as simple as dropping `key_material` from the if statement, but not sure if I'm missing a case here

**Comment by jjshoe** [comment]
Rough pseudo:

````
        if force:
            if not module.check_mode:
                new_fingerprint = None
                if key_material is not None:
                   new_fingerprint = get_key_fingerprint(module, ec2_client, key_material)
                if key['KeyFingerprint'] != new_fingerprint:
                    delete_key_pair(module, ec2_client, name, finish_task=False)
                    key = import_key_pair(module, ec2_client, name, key_material)
                    key_data = extract_key_data(key)
                    module.exit_json(changed=True, key=key_data, msg="key pair updated")
````

**Comment by flowerysong** [comment]
The current behaviour is not a bug, it is the intended function of that parameter ("Force overwrite of already existing key pair if key has changed"). Changing how force works would be a very intrusive  backwards-incompatible change (force defaults to True) and could make a lot of people very unhappy.

Since you can get the result you want by calling the module with `state: absent` followed by `state: present` I'm not sure adding a parameter to do it in one step would be widely useful.

**Comment by jjshoe** [comment]
If you don't provide key material, then it's always changed, is my point.

**Comment by jjshoe** [comment]
Consider the following use case:

1. User creates a brand new key in ec2
2. User registers output
3. User templates out file to save pem
4. User templates out file to save pub, but due to unforseen error, ansible exits

How does the user then re-create the key? You want the user to code in support for idempotency in ansible, rather than have the module account for it?

**Comment by flowerysong** [comment]
If the user wants to remove the key because a later step failed then yes, that is their responsibility to handle. Recreating the key every time the playbook runs does not particularly help them and is the opposite of idempotence.

**Comment by jjshoe** [comment]
There's a bug here, no matter how you skin it.

A subsequent run of the first example does not return the proper structure. The only way to do that is to delete, then re-create.

If you don't provide the `key_material` arg, then the value of the current fingerprint can't possibly match the new fingerprint, and force should work exactly as it currently is described.

Optionally, the module should out right fail on the second call, and the docs should be updated, to say this is a one time only operation.

Optionally, the end user could pass in junk for `key_material`, and it may always work.

Seems like fixing the module would be smarter, though.

**Comment by flowerysong** [comment]
> There's a bug here, no matter how you skin it.

No, there isn't. The module is working as it's meant to.

> A subsequent run of the first example does not return the proper structure.

It returns a different structure than a newly created key, which is the proper thing to do in this situation (and is what the module documentation states will happen.) Amazon only returns the private key once, and it's the caller's responsibility to preserve it.

> If you don't provide the `key_material` arg, then the value of the current fingerprint can't possibly match the new fingerprint, and force should work exactly as it currently is described.

When no `key_material` is provided, that is the caller declaring "I don't care what key it uses, I want a key named 'foo' to exist." There is no fingerprint comparison to be done.

> Optionally, the module should out right fail on the second call, and the docs should be updated, to say this is a one time only operation.

It should (and does) return `changed: False`, because the key already exists and does not need to be created. The current state is already the requested state.

This lets you write a nice, idempotent playbook like:
```
- hosts: localhost
  tasks:
    - block:
        - name: Create keypair
          ec2_key:
            name: foo
          register: result

        - name: Save private key
          copy:
            dest: /var/tmp/foo.rsa
            content: "{{ result.key.private_key }}"
          when: result is changed

      rescue:
        - name: Remove the keypair if we failed to save the private key
          ec2_key:
            name: foo
            state: absent
          when: result is changed

        - name: Still fail instead of actually rescuing
          fail:
```

or
```
- hosts: localhost
  vars:
    keyfile: /var/tmp/foo.rsa
  tasks:
    - name: Check for existing private key
      stat:
        dest: "{{ keyfile }}"
      register: result

    - name: Delete bad keypair
      ec2_key:
        name: foo
        state: absent
      when: not result.stat.exists

    - name: Create keypair
      ec2_key:
        name: foo
      register: result

    - name: Save private key
      copy:
        dest: "{{ keyfile }}"
        content: "{{ result.key.private_key }}"
      when: result is changed
```
