### ISSUE TITLE
win_domain_user - ability to clear an attribute

### ISSUE THREAD

**Issue by thylocene** [ansible/ansible#67764]
##### SUMMARY

The win_domain_user module currently has no way to clear an attribute e.g. city, PostalCode, etc.

The module throws an error if an empty string is used for an attribute:

e.g.
Microsoft.ActiveDirectory.Management.ADInvalidOperationException: replace ---> System.ServiceModel.FaultException: Bad AttributeTypeAndValue or Change found inside the request.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_domain_user

##### ADDITIONAL INFORMATION

```yaml

---
  - name: Map the answers from the servicenow request to the AD attributes
    win_domain_user:
      name: "fredb"
      street: ""
      city: ""
      postal_code: ""
    register: user_created

```
