### ISSUE TITLE
uri module only fails with an inventory is being used

### ISSUE THREAD

**Issue by maltron** [ansible/ansible#67783]
##### SUMMARY
I'm trying to download a tar.gz file using the module uri as seem in this playbook:

```
- hosts: localhost
  vars:
     istio_version: "1.4.5"
     istio_url: "https://github.com/istio/istio/releases/download/{{ istio_version }}/istioctl-{{ istio_version }}-linux.tar.gz"
  tasks:
     - uri: url={{ istio_url }}
            dest=/tmp/test7/istioctl.tar.gz headers={} validate_certs=False
```
It works like wonders. However, when I run the same playbook using this simple inventory as such:
```
[localhost]
127.0.0.1 ansible_connection=local
```
and running the command by: $ ansible-playbook -i hosts test.yaml -vvvvv
The all logs are here: https://pastebin.com/UdticRJ7
```
...
    "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>",
    "path": "/tmp/test7/istioctl.tar.gz",
    "redirected": false,
    "status": -1,
    "url": "https://github.com/istio/istio/releases/download/1.4.5/istioctl-1.4.5-linux.tar.gz"
```
So, why the presence of a inventory affects the behavior of this module ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION

```
ansible-playbook 2.9.4
  config file = None
  configured module search path = ['/Users/mauricio/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.4/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.1 (default, Feb 10 2020, 14:43:14) [Clang 9.0.0 (clang-900.0.39.2)]
```
