### ISSUE TITLE
cloudflare_dns: TXT idempotency

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible#67784]
##### SUMMARY

1. Using `solo=true` with `type=TXT` **replaces all other TXT records** for that domain (or APEX) and may break the domain in various ways
2. Using `solo=false` with `type=TXT` create **duplicated** TXT records of the same value for the same subdomain (or APEX).

But:
- A given domain (or subdomain) often has multiple TXT records, and often on the APEX.
- Emptying all TXT records is simply unacceptable
- Neither is duplicating records (can break many feature, like website verification or SPF which do not deal with or tolerate multiple records)
- Ansible `cloudflare_dns` module finds its very use in managing multiple records situation.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cloudflare_dns

##### ADDITIONAL INFORMATION
Suggestion:

If:
- `solo=true`
-  and `type=TXT`
- and value contains `(.+)=`
... then uniqueness among the various existing TXT records should be ensured on the basis of such value's prefix.

Would work for SPF (`v=spf1`) and `(facebook|google|...)-site-verification=`

See also #31511

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/cloudflare_dns.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/cloudflare_dns.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @andreaso @mgruener
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andreaso** [comment]
Just to make sure that I fully understand. When you talk about duplicates you don't talk about actual duplicate identical TXT records, but rather duplicates on a usage/prefix level? Such as two different `"v=spf1 ..."` records?

**Comment by drzraf** [comment]
I'm talking about duplicated identical TXT records.

Eg:
```yaml
cloudflare_dns:
  domain: example.net
  type: TXT
  record: "@"
  value: "v=spf1 include:_spf.google.com -all"
  solo: <boolean A>
cloudflare_dns:
  domain: example.net
  type: TXT
  record: "@"
  value: "google-site-verification=xxx-xxx"
  solo: <boolean B>
```

Consequence:
- `boolean A = true` and `boolean B = true`: Not idempotent, only `google-site-verification`
- `boolean A = true` and `boolean B = false`: Not idempotent, works once. But override any other records`
- `boolean A = false` and `boolean B = true`: Not idempotent, only `google-site-verification`
- `boolean A = false` and `boolean B = false`: Not idempotent, create duplicated records`

Basically, `solo=true` is non-nonsensical and dangerous for `type=TXT` since `TXT` is ubiquitous and aimed at replacing other specific records (like for former `type=SPF`).
A better heuristic must be found to deduplicate TXT records and ensure idempotency.
Maybe an additional `regexp` field?

**Comment by andreaso** [comment]
I think we might have parallel issues here.

First of all, yes the whole concept of the `solo` parameter is problematic when it comes to idempotency, and especially so when it comes to modern use of TXT records.

That said, I'm not sure I see the same thing as you regarding this case.

> `boolean A = false` and `boolean B = false`: Not idempotent, create duplicated records

Hence, before we start talking about design changes I would like to sort out if you also might be hitting some bug, or if we simple defines things a bit differently.

Anyway, here is my full example based on that scenario.

```yaml
---

- hosts: localhost
  tasks:
    - name: Set a TXT record
      cloudflare_dns:
        account_email: ...
        account_api_token: ...
        zone: initctl.dev
        record: bug67784.initctl.dev
        type: TXT
        value: "v=spf1 include:_spf.google.com -all"
        solo: no

    - name: Set another TXT record
      cloudflare_dns:
        account_email: ...
        account_api_token: ...
        zone: initctl.dev
        record: bug67784.initctl.dev
        type: TXT
        value: "google-site-verification=xxx-xxx"
        solo: no
```

The first time I run it I get two different records created, as expected.

```
PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set a TXT record] *******************************************************************************************************************************************************************************************
changed: [localhost]

TASK [try a different TXT record] *********************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

```
$ dig +short @dora.ns.cloudflare.com bug67784.initctl.dev TXT
"v=spf1 include:_spf.google.com -all"
"google-site-verification=xxx-xxx"
$
```

The second time I run it, no changes, and still the two same records.

```
PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set a TXT record] *******************************************************************************************************************************************************************************************
ok: [localhost]

TASK [try a different TXT record] *********************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
```
$ dig +short @dora.ns.cloudflare.com bug67784.initctl.dev TXT
"v=spf1 include:_spf.google.com -all"
"google-site-verification=xxx-xxx
$
```

At least the way I define things there haven't been any records created, and for this isolated case things are idempotent.

Are you experiencing anything different on your end?
