### ISSUE TITLE
handle `register` expressions for dict specs

### ISSUE THREAD

**Issue by beasteers** [ansible/ansible#67804]
##### SUMMARY

Currently `register` saves the entire module output to a variable, but many times you only need one part of the output. For example, I would love to be able to set:
`register: something=result.stdout` 
after running a shell command.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Basically - add dictionary support for `register`

##### ADDITIONAL INFORMATION

Essentially, you should be able to transform:
```yaml
- name: run command
  shell: echo 'hi'
  register: hi_out

- name: extract output
  set_fact: hi=hi_out.stdout
```
to:
```yaml
- name: run command
  shell: echo 'hi'
  register: hi=result.stdout
```
This doesn't affect normal functionality as strings would still work the same way. 

It would also let you set multiple variables if you so needed
```yaml
- name: run command
  shell: echo 'afdasdfasdfasdf'
  register: 
    start: result.stdout[:5]
    end: result.stdout[-5:]
    err: result.stderr
```

This would have the added benefit of not polluting ansible output logs (big plus !!) and variable namespace.

Here's an especially ugly one that I didn't have fun writing:

```yaml
- name: Load the supervisord config content
  slurp: src=/etc/supervisord.conf
  register: supervisord_conf_b64 # ughh..

- name: ughhh..
  set_fact:
    supervisord_conf: "{{ supervisord_conf_b64['content'] | b64decode }}"

- name: Extract ...
  set_fact:
    supd_pidfile: {{ supervisord_conf | regex_search(line_pattern, multiline=True) | first }}
```

But It'd be so much cleaner to be able to do:
```yaml
- name: Get the supervisord value
  slurp: src=/etc/supervisord.conf
  register: 
    supervisord_conf: > 
      result['content'] 
         | b64decode 
         | regex_search(line_pattern, multiline=True) | first
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
We have discussed this before, and there may be another feature request for it here somewhere.

I think generally speaking we are in favor of adding some form of "projection", that would allow you to manipulate the module response before registering the result.  It would likely be another keyword, that supplements `register` and not done in register directly.

However, with that being said, this will likely not be done for the 2.10 release, as our development efforts are focused elsewhere for the release.

**Comment by sivel** [comment]
I have a proof of concept of this at https://github.com/ansible/ansible/pull/72553

There are still a few things there that need more thought.

**Comment by bcoca** [comment]
There are other ways todo this without set_fact (but it is different scope).
```
- name: here we auto subset
  vars:
    hi: ' {{ res.stdout}}' # doing as block, but could be play, role level or from inventory.
  block:
    - name: run command
     shell: echo 'hi'
     register: res

    ... # everything in block has access to 'hi' already as a subset.
```
