### ISSUE TITLE
ec2: unsupported parameter for module: source_dest_check

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#6780]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.3
##### Environment:

N/A. 
##### Summary:

No matter what I do with the "source_dest_check" parameter in ec2, it fails outputting:

> failed: [127.0.0.1] => {"failed": true, "item": ""}
> msg: unsupported parameter for module: source_dest_check
##### Steps To Reproduce:

Use code attached below, run it and get results

```
- name: Create the NAT Instance
  ec2:
    region: "{{ aws_region}}"

    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    keypair: "{{ aws_keypair }}"
    instance_type: "{{ vpc_nat_instancetype }}"
    image: "{{ vpc_nat_instance_id }}"
    vpc_subnet_id: '{{vpc["subnets"][0]["id"]}}'
    assign_public_ip: true
    group: ansibleDeployedDefault
    source_dest_check: false
    wait: true
    instance_tags: 
      Name: "NAT Instance"
    exact_count: 1
  register: ec2
```
##### Expected Results:

source_dest_check is turned off on the ec2 instance
##### Actual Results:

Error message with the following output:

```
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: unsupported parameter for module: source_dest_check
```
