### ISSUE TITLE
deploy_helper module make broken link for current when using relative paths

### ISSUE THREAD

**Issue by wtfred** [ansible/ansible#67809]
##### SUMMARY
I'm on Plesk, so the paths used for symbolic links can't be absolute, else Plesk will fail to do action such as renaming a domain.
I know it's better to use absolute paths, and when i did everything was working fine. But working with Plesk (or any other system that let you rename the domain) you can't use absolute paths, else everything will break when renaming the domain.
On the documentation page of the deploy_helper module, it say you can use relative paths so i think this make this behaviour a bug.
Or maybe i'm doing something wrong? Please excuse me if this is the case, and point me to my error ^^ Thanks for reading!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
deploy_helper

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/my-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT
Linux (Manjaro 19.0 on controller, Debian 9.11 on host)
Plesk Onyx 17.8 on host

##### STEPS TO REPRODUCE
Here is my folder tree:

-- httpdocs
---- current -> must point to `releases/xxxx` but point to `httpdocs/releases/xxxx` (not working)
---- releases
-------- xxxxxx
------------ public
---------------- index.php
------------ var/log -> `../../../shared/log`
------------ some others folders of my app
---- shared
-------- log

```yaml
- name: Initialize deploy_helper module
  deploy_helper:
    path: "httpdocs"

- name: Clone repository
  git:
    repo: "{{ repository_url }}"
    dest: "{{ deploy_helper.new_release_path }}"
  register: clone

# Symlinking shared folders and files
- name: Add symlinks from the new release to the shared folder
  file:
    path: '{{ deploy_helper.new_release_path }}/{{ item.path }}'
    src: '{{ item.src }}'
    state: link
  with_items:
    - path: var/log
      src: ../../../shared/log

# Change the current/ symlink, "go" live
- name: Finalize the deploy, removing the unfinished file and switching the symlink
  deploy_helper:
    path: "{{ base_folder }}"
    release: "{{ deploy_helper.new_release }}"
    state: finalize
    clean: true
    keep_releases: 1
```

##### EXPECTED RESULTS
A functional symlink to last release
`current -> releases/xxxx` or `current -> ../httpdocs/releases/xxxx`

##### ACTUAL RESULTS
A broken symlink
`current -> httpdocs/releases/xxxx`
Every other folders or symlink to shared are fine.
