### ISSUE TITLE
ovirt_snapshot doesn't snapshot disk when creating snapshot of vm snapshot and disks to be snapshotted are enlisted

### ISSUE THREAD

**Issue by nemethloci** [ansible/ansible#67813]
##### SUMMARY
When creating VM snapshots with ovirt_snapshot it's possible to specify selectively which disk should be included in the snapshot, however snapshot currently will not contain the disk snapshot in such case (Note: without specifying the disks explicitly all disks are included in the snapshot and this works fine)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ovirt_snapshot

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/sha                                                                                                                                                             re/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (R                                                                                                                                                             ed Hat 4.8.5-39)]

```

##### CONFIGURATION

```no config change was reported by command

```

##### OS / ENVIRONMENT

RHEL 7.7

##### STEPS TO REPRODUCE

```

snapshots.yml:
- hosts: localhost
  connection: smart

  vars_files:
    - vars/vars.yml
    - vault/vault_rhevm.yml

  vars:
    timestamp: "{{ansible_date_time.iso8601_basic_short}}"

  tasks:
    - name: Obtains SSO token
      ovirt_auth:
        url: "{{ url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        insecure: "{{ insecure }}"
      tags:
        - auth

    - name: Create snapshot of "{{ vmnamevar }}"
      ovirt_snapshot:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ vmnamevar }}"
        description: snap_{{timestamp}}
        fetch_nested: true
        disks:
          - id: ed52b9a3-75ef-4af5-a5d7-b9909d2139b0
      register: snapshot
      tags:
        - create_snapshot


ansible-playbook -vvv --ask-vault-pass snapshot.yml --extra-vars="vmname=Fileserver-2"

```

##### EXPECTED RESULTS

VM snapshot should include the snapshot of disks enumerated (and only those)

##### ACTUAL RESULTS

No disks included in snapshot

Reason for the problem is that incorrect http request body is sent. I'll submit patch to correct the module code.

```paste below

```
