### ISSUE TITLE
handler not fired when subsequent redefined later in conditional role

### ISSUE THREAD

**Issue by alexcernat** [ansible/ansible#67812]
##### SUMMARY
In a playbook, when multiple roles are defining the same handler, the handler is skipped if subsequent when don't match the hostname (see example below).

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian 10

##### STEPS TO REPRODUCE

```yaml
- hosts: group_with_host1_and_host2
  roles:
    - role: role1_with_handler_service_restart_and_handler_notified
       tags:
         - role1
    - role: role2_with_handler_service_restart_but_no_change_so_no_notify
      tags:
         - role2
      when: ansible_hostname not in groups[group_matching_only_host2]
```

##### EXPECTED RESULTS

Because role1 made changes in both host1 and host2, handler service restart should run at the end of the playbook on both servers. Role2 made no changes to servers.

##### ACTUAL RESULTS

The handler (service restart) ran only on host1 (because the last role in playbook matched only host1).

```paste below

```
