### ISSUE TITLE
Support contentType for azure_rm_keyvaultsecret

### ISSUE THREAD

**Issue by WesToleman** [ansible/ansible#67839]
##### SUMMARY

Azure KeyVault secrets have an optional *content type*. This is exposed via the [setsecret REST API](https://docs.microsoft.com/en-us/rest/api/keyvault/setsecret/setsecret) and [Az Powershell `Set-AzKeyVaultSecret`](https://docs.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultsecret). The `azure_rm_keyvaultsecret` module does not support this option.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

azure_rm_keyvaultsecret

##### ADDITIONAL INFORMATION

I would like a `secret_content_type` parameter added to the module.

```yaml
# Example invocation
- name: Create a secret
  azure_rm_keyvaultsecret:
    secret_name: MySecret
    secret_value: My_Pass_Sec
    secret_content_type: My_Content_Type
    keyvault_uri: https://contoso.vault.azure.net/
    tags:
        testing: testing
        delete: never
```
