### ISSUE TITLE
Ansible user module delete user password

### ISSUE THREAD

**Issue by richierg** [ansible/ansible#67850]
##### SUMMARY

 Add password_delete option to user module
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Module name : user 
##### ADDITIONAL INFORMATION

Some cloud provider create an user / password for first installation of System. For me this user is ansible. 
Currently I just lock this user with the password_lock feature of user module.
But I would like delete this.

```yaml
- name: Remove the password for user 'johnd'
  user:
    name: johnd
    password_removed: yes
```
