### ISSUE TITLE
PROXY grants via mysql_user do not appear to work correctly

### ISSUE THREAD

**Issue by mcgoldrickm** [ansible/ansible#67858]
##### SUMMARY

```
I am attempting to grant PROXY on one user to another user.
What I would like to achieve:
GRANT PROXY ON 'db_admins'@'localhost' TO ''@''

What I'm passing to mysql_user:
priv: "db_admins@localhost:PROXY"

What I get:
GRANT PROXY ON 'db_admins@localhost'@'%' TO ''@''

After a bit of troubleshooting, I found that ansible is sending the grant statement to mysql as follows:
    "GRANT PROXY ON `db_admins@localhost`",
    "TO %s@%s"

The following code appears to be causing the problematic quotes:

        for i, side in enumerate(dbpriv):
            if side.strip('`') != '*':
                dbpriv[i] = '%s%s%s' % (quote, side.strip('`'), quote)
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user
##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
no output - default config
```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```yaml
---
 - hosts: mysql
   serial: 1
   any_errors_fatal: true
   gather_facts: false
   tasks:
     - name: create MySQL DB users
       mysql_user_plugin:
         name: ''
         login_user: XXXX
         login_password: XXXXX
         login_unix_socket: /mysql/run/mysql.sock
         plugin: auth_pam
         plugin_hash_string: 'mysqld, group_name=db_admins'
         priv: 'db_admins@localhost:PROXY'
         host: ''
         state: present
```

##### EXPECTED RESULTS

GRANT PROXY ON 'db_admins'@'localhost' TO ''@''

##### ACTUAL RESULTS

```paste below
GRANT PROXY ON 'db_admins@localhost'@'%' TO ''@''
```
