### ISSUE TITLE
Resizing swap using filesystem and/or lvol modules fails

### ISSUE THREAD

**Issue by rvdlinden** [ansible/ansible#67860]
##### SUMMARY

Unable to resize a swap filesystem on RHEL 7/8 using either the filesystem module nor the lvol module.

The filesystem module states in the documentation at https://docs.ansible.com/ansible/latest/modules/filesystem_module.html, that it can resize a swap partition. When used however, the following message is shown:
"msg": "module does not support resizing swap filesystem yet."

When using the lvol module, resizing swap also fails with a message like
"msg": "Unable to resize lv.paging00 to 4g", "rc": 5

NOTE: also have an issue with resizing an xfs filesystem, but that issue is already logged as https://github.com/ansible/ansible/issues/63278

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

filesystem module: resizefs parameter
lvol module: resizefs parameter

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /home/lindenre.eu/playbooks/rabobank.play-rootprivilege/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```
##### CONFIGURATION

```paste below
Default
```

##### OS / ENVIRONMENT

RHEL 7.7 and RHEL 8.1

##### STEPS TO REPRODUCE

```
- hosts: "{{ host | default('all')}}"
  gather_facts: no
  become: yes
  strategy: "{{ playbook_strategy | default('linear')}}"

  tasks:

  - name: lvm lvol
    lvol:
      vg: vg.root
      lv: lv.paging00
      size: 3G
      shrink: no
      opts: default
      state: present
      resizefs: true
    ignore_errors: yes

  - name: lvm filesystem
    filesystem:
      fstype: swap
      dev: /dev/vg.root/lv.paging00
      resizefs: true"

```
##### EXPECTED RESULTS

resizing of swap: /dev/vg.root/lv.paging00

##### ACTUAL RESULTS

```paste below
TASK [lvm lvol]
****************
fatal: [serverx]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "err": "fsadm: Filesystem \"swap\" on device \"/dev/mapper/vg.root-lv.paging00\" is not supported by this tool.\n  Filesystem check failed.\n", "msg": "Unable to resize lv.paging00 to 3g", "rc": 5}

TASK [lvm filesystem]
****************
fatal: [serverx]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "module does not support resizing swap filesystem yet."}"
```
