### ISSUE TITLE
Ansible's "vmware_guest" module seems to ignore it's host MTU Settings 

### ISSUE THREAD

**Issue by mjcotner** [ansible/ansible#67870]
##### SUMMARY

The Ansible Control Node seems to be ignoring it's OS defined MTU settings.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(etc/ansible/ansible.cfg) = /etc/ansible/.text
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = false
```

##### OS / ENVIRONMENT

Platform: VMware 6.7
OS: CentOS8
Ansible 2.9.5
Python3: 3.6.8
VCSA: 6.7.0.31100

##### STEPS TO REPRODUCE

1. Install Ansible 2.9.5 on CentOS8.
2. Install pyvmomi.
3. Set the MTU size on your Ansible Cent8 control node to 1200.
3. Configure a Network Tunnel to a remote vCenter system with an MTU size of 1276.
4. Set the MTU size on your vCenter Server to 1200.
5. Attempt to deploy a VM  from Template with Ansible's vmware_guest module.

hosts file:
```yaml
---
all:
  children:            
    vms:
      children:
        vcent_servers:
          hosts:
            remote-vcsa.man.net:
        cent7_servers:
          children:         
            test_servers:
              hosts:
                remote-server.man.net:
    remote:
      hosts:
        remote-server.man.net:
        remote-vcsa.man.net:
```
Cannonated group variables for the VM we are trying to create:
```yaml
---
vcenter_server: remote-vcsa.man.net
vcenter_username: ansible.user@man.net
vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          #########################################
vm_datacenter: Remote-Datacenter
vm_datastore: vsanDatastore
vm_network_name1: dpg-8
vm_network_name2: dpg-9
local_dc_ip1: 192.168.100.1
local_dc_ip2: 192.168.100.2
vm_template: CentOS7
app_var: testservers
vm_folder: testservers
vm_size_gb: 50
vm_memory_mb: 4096
```
Our remote-server's host variables:
```yaml
---
vm_name: Remote-Server
vm_ip1: 192.168.100.10
vm_ip2: 192.168.200.10
vm_netmask: 255.255.255.0
vm_gateway: 192.168.100.1
ansible_user: remotessh
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          #########################################
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          #########################################
ansible_connection: ssh
```
The VM creation playbook:
```
---
- name: Deploy a VM from Template
  gather_facts: no
  hosts: test_servers

  tasks:
  - name: Create a virtual machine from template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}"
      state: poweredon
      template: "{{ vm_template }}"
      datacenter: "{{ vm_datacenter }}"
      disk:
      - size_gb: "{{ vm_size_gb }}"
        type: thin
        datastore: "{{ vm_datastore }}"
      hardware:
        memory_mb: "{{ vm_memory_mb }}"
      networks:
        - name: "{{ vm_network_name1 }}"
          ip: "{{ vm_ip1 }}"
          netmask: "{{ vm_netmask }}"
          gateway: "{{ vm_gateway }}"
        - name: "{{ vm_network_name2 }}"
          ip: "{{ vm_ip2 }}"   
          netmask: "{{ vm_netmask }}" 
      customization: 
          dns_servers:
            - "{{ local_dc_ip1 }}"
            - "{{ local_dc_ip2 }}"
          dns_suffix:
            - man.net  
    delegate_to: localhost
```
Ansible control node's ifcfg-ens192 file:
```
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=ens192
DEVICE=ens192
ONBOOT=yes
IPADDR=192.168.0.5
PREFIX=24
DOMAIN=man.net
GATEWAY=192.168.0.1
DNS1=192.168.0.2
DNS2=192.168.0.3
MTU=1200
```
vCenter's /etc/systemd/network/10-eth0.network:
```
Name=eth0

[Network]
Gateway=192.168.100.1
Address=192.168.100.4/25
DHCP=no
Domains=man.net

[DHCP]
UseDNS=false

[Route]
Gateway=192.168.100.1
Destination=0.0.0.0/0

[Link]
MTUBytes=1200
```
Cisco tunnel 1000 MTU settings (1276):
```
#sh int tun1000
Tunnel1000 is up, line protocol is up 
  Hardware is Tunnel
  Description: MAN-MGMT
  Interface is unnumbered. Using address of Loopback1000 (10.10.254.255)
  MTU 9976 bytes, BW 100 Kbit/sec, DLY 50000 usec, 
     reliability 255/255, txload 107/255, rxload 15/255
  Encapsulation TUNNEL, loopback not set
  Keepalive not set
  Tunnel linestate evaluation up
  Tunnel source 10.10.253.255, destination 10.10.253.254
  Tunnel protocol/transport GRE/IP
    Key disabled, sequencing disabled
    Checksumming of packets disabled
  Tunnel TTL 255, Fast tunneling enabled
  Path MTU Discovery, ager 10 mins, min MTU 92
  Tunnel transport MTU 1276 bytes
  Tunnel transmit bandwidth 8000 (kbps)
  Tunnel receive bandwidth 8000 (kbps)
  Last input 00:00:03, output 00:00:01, output hang never
  Last clearing of "show interface" counters 22w2d
  Input queue: 0/375/0/0 (size/max/drops/flushes); Total output drops: 0
  Queueing strategy: fifo
  Output queue: 0/0 (size/max)
  5 minute input rate 6000 bits/sec, 5 packets/sec
  5 minute output rate 42000 bits/sec, 6 packets/sec
     89201285 packets input, 39898820325 bytes, 0 no buffer
     Received 0 broadcasts (0 IP multicasts)
     0 runts, 0 giants, 0 throttles 
     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored, 0 abort
     94196011 packets output, 43097688723 bytes, 0 underruns
     0 output errors, 0 collisions, 0 interface resets
     0 unknown protocol drops
     0 output buffer failures, 0 output buffers swapped out
```

##### EXPECTED RESULTS

This playbook should build a remote-server.man.net CentOS7 server from template in the remote ESXi Cluster. 

Packets no greater than 1200 bytes should be being passed from the local Ansible Control Node to the remote VCSA server.  

##### ACTUAL RESULTS

The Ansible play hangs for about 10 minutes before failing with a TimeoutError: [Errno 110].

Using WireShark we see that the Ansible Control Node is re-transmitting packets to the remote vCenter server. Those packets are 1294 bytes in size, and are being kicked back by the router as requiring fragmentation. The MTU size on the Ansible Control Node was reduced to 1100 and the results were the same.

Is there a way to set packet size in the Ansible application?

Detailed Ansible Error:
```paste below
fatal: [Remote-Server.man.net -> localhost]: FAILED! => {

    "changed": false,
	
    "module_stderr": "Traceback (most recent call last):\n  
	
	File \"/root/.ansible/tmp/ansible-tmp-1582734151.391276-71447770370709/AnsiballZ_vmware_guest.py\", line 102, in <module>\n    
	_ansiballz_main()\n  
	
	File \"/root/.ansible/tmp/ansible-tmp-1582734151.391276-71447770370709/AnsiballZ_vmware_guest.py\", line 94, in _ansiballz_main\n    
	invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  
	
	File \"/root/.ansible/tmp/ansible-tmp-1582734151.391276-71447770370709/AnsiballZ_vmware_guest.py\", line 40, in invoke_module\n    
	runpy.run_module(mod_name='ansible.modules.cloud.vmware.vmware_guest', init_globals=None, run_name='__main__', alter_sys=True)\n  
	
	File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    
	return _run_module_code(code, init_globals, run_name, mod_spec)\n  
	
	File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    
	mod_name, mod_spec, pkg_name, script_name)\n  
	
	File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    
	exec(code, run_globals)\n  
	
	File \"/tmp/ansible_vmware_guest_payload_feqdxk4f/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2834, in <module>\n  
	
	File \"/tmp/ansible_vmware_guest_payload_feqdxk4f/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2823, in main\n  
	
	File \"/tmp/ansible_vmware_guest_payload_feqdxk4f/ansible_vmware_guest_payload.zip/ansible/modules/cloud/vmware/vmware_guest.py\", line 2413, in deploy_vm\n  
	
	File \"/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py\", line 706, in <lambda>\n    
	self.f(*(self.args + (obj,) + args), **kwargs)\n  
	
	File \"/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py\", line 512, in _InvokeMethod\n    
	return self._stub.InvokeMethod(self, info, args)\n  
	
	File \"/usr/local/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py\", line 1351, in InvokeMethod\n    
	resp = conn.getresponse()\n  
	
	File \"/usr/lib64/python3.6/http/client.py\", line 1346, in getresponse\n    
	response.begin()\n  
	
	File \"/usr/lib64/python3.6/http/client.py\", line 307, in begin\n    
	version, status, reason = self._read_status()\n  
	
	File \"/usr/lib64/python3.6/http/client.py\", line 268, in _read_status\n    
	line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  
	
	File \"/usr/lib64/python3.6/socket.py\", line 586, in readinto\n    
	return self._sock.recv_into(b)\n  
	
	File \"/usr/lib64/python3.6/ssl.py\", line 968, in recv_into\n    
	return self.read(nbytes, buffer)\n  
	
	File \"/usr/lib64/python3.6/ssl.py\", line 830, in read\n    
	return self._sslobj.read(len, buffer)\n  
	
	File \"/usr/lib64/python3.6/ssl.py\", line 587, in read\n    
	v = self._sslobj.read(len, buffer)\n
	
	TimeoutError: [Errno 110] Connection timed out\n",
    
	"module_stdout": "",
    "msg": "MODULE FAILURE\n

See stdout/stderr for the exact error",
    "rc": 1
}
```
Repeated WireShark Packet Capture Errors:
```
No.     Time	        Source		Destination     Protocol Length  Info
697	58.856018273	192.168.0.5	192.168.100.4	TCP	 1294    [TCP Retransmission] 37592 → 443 [ACK] Seq=134804 Ack=210941 Win=394240 Len=1240
699	59.312172193	10.10.254.255	192.168.0.5	ICMP	 70	 Destination unreachable (Fragmentation needed)
```
