### ISSUE TITLE
tower_receive does not return inventory group name if user is not System Administrator

### ISSUE THREAD

**Issue by ecchong** [ansible/ansible#67885]
##### SUMMARY

Using tower_receive module, tower-cli or awx-cli command to pull a inventory from Tower does not return the group name if the user is not System Adminsitrator

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_receive
tower-cli
awx-cli

##### ANSIBLE VERSION

```paste below
2.9.5

```

##### CONFIGURATION

```paste below
Default configuration
```

##### OS / ENVIRONMENT

RHEL 7

##### STEPS TO REPRODUCE

```yaml
  - tower_receive:
      inventory: "my inventory"
      tower_host: tower_server
      tower_username: some_user
      tower_password: password
      validate_certs: no
    register: output
```

##### EXPECTED RESULTS

group name return in inventory asset

##### ACTUAL RESULTS

```paste below
      "group": [
        {
          "sub_groups": [],
          "hosts": [
            "linux_node",
            "windows_node"
          ]
        },
        {
          "sub_groups": [],
          "hosts": []
        },
        {
          "sub_groups": [],
          "hosts": []
        }
      ],
```
