### ISSUE TITLE
Roles that are tagged in dependencies duplicate execution with playbook

### ISSUE THREAD

**Issue by leedm777** [ansible/ansible#67913]
##### SUMMARY
If a dependency is tagged, then its execution is duplicated if that role is also listed in the play.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = None
  configured module search path = ['/Users/dlee/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.4_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.1 (default, Dec 27 2019, 18:06:00) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

macOS; local playbook

##### STEPS TO REPRODUCE

```yaml
# ./site.yml
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - { role: a, tags: a }
    - { role: b, tags: b }
    - { role: c, tags: c }

# ./roles/a/tasks/main.yml
---
- debug: msg=A

# ./roles/b/tasks/main.yml
---

- debug: msg=B

# ./roles/b/meta/main.yml
---
dependencies:
 - role: a

# ./roles/c/tasks/main.yml
---
- debug: msg=C

# ./roles/c/meta/main.yml
---
dependencies:
 - role: a
```

##### EXPECTED RESULTS

Tasks in role a should only be executed once.

##### ACTUAL RESULTS

Tasks in role `a` are executed twice.

```paste below
$ ansible-playbook site.yml 
PLAY [localhost] ****************************************************************

TASK [a : debug] ****************************************************************
ok: [localhost] => {
    "msg": "A"
}

TASK [a : debug] ****************************************************************
ok: [localhost] => {
    "msg": "A"
}

TASK [b : debug] ****************************************************************
ok: [localhost] => {
    "msg": "B"
}

TASK [c : debug] ****************************************************************
ok: [localhost] => {
    "msg": "C"
}

PLAY RECAP **********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
This is because you're passing different parameters to role `a`. The role will only run once if you change `./roles/c/meta/main.yml` to
```
---
dependencies:
 - role: a
   tags: a
```
(or remove `tags: a` from the play)
