### ISSUE TITLE
'register' for blocks

### ISSUE THREAD

**Issue by Hoeze** [ansible/ansible#67948]
Hi, I'm not sure if there is a better solution, but I would like the following solution for the problem: "Execute reload task if any other task in a block has changed".

##### SUMMARY
Allow `register` as attribute for task blocks:
```yaml
 - name: create test zone
   block:
     - name: set up zone
       firewalld:
         zone: test
         state: present
         permanent: yes
 
     - name: allow ssh access
       firewalld:
         zone: test
         service: ssh
         state: enabled
         permanent: yes
     - name: allow dhcpv6 client
       firewalld:
         zone: test
         service: dhcpv6-client
         state: enabled
         permanent: yes
   register: create_zone

 - name: firewalld reload
   command: firewall-cmd --reload
   when: create_zone.changed

```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible task blocks
