### ISSUE TITLE
vmware_guest cannot remove 2 CDROMs, adds 1 CDROM with state: absent

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ansible/ansible#67952]
##### SUMMARY

The module `vmware_guest` cannot remove CDROMs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
```

##### CONFIGURATION

```paste below
DEFAULT_MODULE_PATH(/home/comigo/WORK/AnsibleBaker/ansible.cfg) = ['/home/comigo/WORK/AnsibleBaker/modules']
DEFAULT_STDOUT_CALLBACK(/home/comigo/WORK/AnsibleBaker/ansible.cfg) = yaml
DEFAULT_STRATEGY(/home/comigo/WORK/AnsibleBaker/ansible.cfg) = free
DEFAULT_VAULT_PASSWORD_FILE(/home/comigo/WORK/AnsibleBaker/ansible.cfg) = /home/comigo/WORK/AnsibleBaker/.ansible_vault
DISPLAY_SKIPPED_HOSTS(/home/comigo/WORK/AnsibleBaker/ansible.cfg) = True
HOST_KEY_CHECKING(/home/comigo/WORK/AnsibleBaker/ansible.cfg) = False
```

##### OS / ENVIRONMENT

* vSphere Client version: 6.5.0.13000
* Hypervisor: VMware ESXi, 6.5.0
* VM Compatibility: ESXi 6.5 and later (VM version 13)

##### STEPS TO REPRODUCE

* Have a VM with two CDROMs in a 'disconnected' state (no ISO, no datastore link or such, but still present as devices from inside VM). Power the VM off.
* Execute `vmware_guest` with `cdrom: {type: none, state: absent}`
* **Get "OK" status.**
* Observe that **both** CDROMs are still present.
* Remove both CDROMs manually.
* Execute `vmware_guest` again.
* Get "Changed" status.
* Observe that VM now has one CDROM.
* Further runs return "OK" and do not remove the CDROM.

```yaml
- name: "{{'Delete a VM' if vm_delete else 'Clone a VM from a Windows template, or query info about it'}}"
  vmware_guest:
    hostname: "{{vSphere_hostname}}"
    username: "{{vcenter_username}}"
    password: "{{vcenter_password}}"
    cluster: "{{vSphere_cluster}}"
    datacenter: "{{vSphere_datacenter}}"

    validate_certs: no

    datastore: "{{vSphere_datastore | default('')}}"
    folder: "{{vSphere_folder}}"
    name: "{{inventory_hostname}}"
    template: "{{vcenter_template | default('')}}"
    networks:
    - name: …
    hardware:
      memory_mb: "{{hardware_memory}}"
    cdrom:
      type: none
      state: absent

    state: "{{'absent' if vm_delete else 'present'}}"
    force: "{{vm_delete|bool}}"
  register: vmData
  delegate_to: localhost
```

##### EXPECTED RESULTS

I expected a VM with 0 CDROM devices.

I would actually expect that `cdrom: []` should have worked (it does nothing). Still, 
```yaml
cdrom:
  type: none
  state: absent
```
seems to be [the official documented way](https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html#parameter-cdrom) to remove CDROMs. Instead, it either does nothing if there is already at least one CDROM or adds an unneeded one if 0 were present before running the task.

##### ACTUAL RESULTS

Starting with a VM with 2 CDROMs, you get 2 CDROMs and an OK status.
Starting with a VM with 1 CDROM, you get 1 CDROM and OK status.
Starting with a VM with 0 CDROMs, you get 1 CDROM and "Changed" status.

```paste below
ok: [Win2008-TRM -> localhost] => changed=false 
  instance:
    # (nothing relevant)
  invocation:
    module_args:
      cdrom:
        state: absent
        type: none
      cluster: …
      convert: null
      customization: {}
      customization_spec: null
      customvalues: []
      datacenter: …
      datastore: …
      disk: []
      esxi_hostname: null
      folder: Etalon/FunctionalTemplates
      force: false
      guest_id: null
      hardware:
        memory_mb: 10240
      hostname: …
      is_template: false
      linked_clone: false
      name: Win2008-TRM
      name_match: first
      networks:
      - name: …
        type: dhcp
      password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      port: 443
      proxy_host: null
      proxy_port: null
      resource_pool: null
      snapshot_src: null
      state: present
      state_change_timeout: 0
      template: Win2008R2_40G
      use_instance_uuid: false
      username: ComigoAnsible@vsphere.local
      uuid: null
      validate_certs: false
      vapp_properties: []
      wait_for_customization: false
      wait_for_ip_address: false
```
