### ISSUE TITLE
podman_image: remove_signatures option not correct implemented

### ISSUE THREAD

**Issue by bossi86** [ansible/ansible#67965]
#### SUMMARY
The module podman_image has a typo in the remove-signatures options.
The name of the options is "--remove-signatures", but "--remove_signatures" is used instead.
See: https://github.com/ansible/ansible/blame/devel/lib/ansible/modules/cloud/podman/podman_image.py#L580 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
podman_image

##### ANSIBLE VERSION
all Versions (including current devel)

##### CONFIGURATION
-

##### OS / ENVIRONMENT
Unix

##### STEPS TO REPRODUCE
push an image with the push arg remove_signatures
```
- name: Build and push an image to multiple registries
  podman_image:
    name: "{{ item }}"
    path: /path/to/build/dir
    push: yes
    auth_file: /etc/containers/auth.json
    push_args:
      remove_signatures: true
    loop:
    - quay.io/acme/nginx
    - docker.io/acme/nginx
```

##### EXPECTED RESULTS
If option remove_signatures are set it should remove the signatures or not, depending on the value.

##### ACTUAL RESULTS
I got an error from podman, that "remove_signatures" is an unknown option.
