### ISSUE TITLE
Fail when A != B not working  (A and B are vars of type String)

### ISSUE THREAD

**Issue by Zoran-P** [ansible/ansible#67970]
##### SUMMARY
When two string variables are checked for not being equal in:
fail when condition, it does not work for:
```
when A!=B ,
when A is not B
when  A is not match(B)
not( A== B),
```

and the check works only for being two strings equal. So following all works:
```
when A == B
when A is match(B)
```
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 17:58:22) [GCC 8.2.1 20180905 (Red Hat 8.2.1-3)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventories/ENG/hosts']

```

##### OS / ENVIRONMENT

not relevant

##### STEPS TO REPRODUCE

test.yaml

```yaml

- hosts: all
  gather_facts: False
  tasks:

- name: PARSE DNS CLIENT CONFIG
  shell: cat /etc/resolv.conf  | grep -E "(nameserver|search)" | awk '{print $2}'
  register: dns_client_cfg_result
- fail:
   msg: System's {{ inventory_hostname }} domain {{dns_client_cfg_result.stdout_lines[0] }} is not matching {{ expected_domain }}
  when: dns_client_cfg_result.stdout_lines[0]  != expected_domain
  vars:
    expected_domain: "moc.eng.epssg"
- debug:
    msg: System {{ inventory_hostname }} domain matches expected {{ expected_domain }}
```

##### EXPECTED RESULTS

if you replace the `!=` by `==` in when line:
```
 when: dns_client_cfg_result.stdout_lines[0]  == expected_domain
```
The task is working, but of course the check is worthless. So I expect the task to be correct for the test `!=` as for the test `==`.

##### ACTUAL RESULTS

```
fatal: [E2ENGMCSSV01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'expected_domain' is undefined\n\nThe error appears to be in '/etc/ansible/roles/dns_test/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    expected_domain: \"moc.eng.epssg\"\n- debug:\n  ^ here\n"}
```

```paste below

```
