### ISSUE TITLE
VmwareCategory object has no attribute api_client

### ISSUE THREAD

**Issue by jmkleijer** [ansible/ansible#67974]
##### SUMMARY
This bug was already mentioned on [Oct 2, 2019](https://github.com/ansible/ansible/issues/61220#issuecomment-537464245)
by nicholasrodriguez.

I'm using the module vmware_category from the devel branch but this results in an error.

The particular feature (for which I'm using this module from the development branch) is the ability to add associable_object_types.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_category.py

##### ANSIBLE VERSION
```
ansible 2.8.4
  config file = /home/nxf41739/git/ngvp.code/ngvp-code/ansible.cfg
  configured module search path = [u'/home/nxf41739/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nxf41739/git/ngvp.code/lib/python2.7/site-packages/ansible
  executable location = /home/nxf41739/git/ngvp.code/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
(using a module from the development branch in project using ansible 2.8.4)

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/home/nxf41739/git/ngvp.code/ngvp-code/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s -o PubkeyAuthentication=yes -o PasswordAuthentica
PARAMIKO_HOST_KEY_AUTO_ADD(/home/nxf41739/git/ngvp.code/ngvp-code/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/home/nxf41739/git/ngvp.code/ngvp-code/ansible.cfg) = False
```

##### STEPS TO REPRODUCE
When you use the module vmware_category, (from the devel branch), it refers to a function called api_client which the object / module doesn't seem to have. (and neither does the parent object)

```yaml
- name: "Create the categories in VMware"
  vmware_category:
    hostname: '{{ vcenter_server }}'
    username: '{{ vcenter_admin_user }}'
    password: '{{ vcenter_admin_pass }}'
    validate_certs: false
    category_name: 'category1'
    category_description: 'My New Category'
    category_cardinality: 'single'
    associable_object_types:
      - Datastore
    state: present

```

##### EXPECTED RESULTS
I would expect a Category to be created in VMware vCenter named category1 that could be associated to Datastores.

##### ACTUAL RESULTS
```
failed: [localhost] (item=VM Category) => {
    "ansible_loop_var": "cat_item",
    "cat_item": "VM Category",
    "changed": false,
    "module_stderr": "/home/nxf41739/git/ngvp.code/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'emea.nics.nxp.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/home/nxf41739/.ansible/tmp/ansible-tmp-1583256334.03-206123342172141/AnsiballZ_nxp_vmware_category.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/nxf41739/.ansible/tmp/ansible-tmp-1583256334.03-206123342172141/AnsiballZ_nxp_vmware_category.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/nxf41739/.ansible/tmp/ansible-tmp-1583256334.03-206123342172141/AnsiballZ_nxp_vmware_category.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_nxp_vmware_category_payload_M2Uddz/__main__.py\", line 325, in <module>\n  File \"/tmp/ansible_nxp_vmware_category_payload_M2Uddz/__main__.py\", line 320, in main\n  File \"/tmp/ansible_nxp_vmware_category_payload_M2Uddz/__main__.py\", line 166, in __init__\nAttributeError: 'VmwareCategory' object has no attribute 'api_client'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
