### ISSUE TITLE
Git module: Failed to download remote objects and refs

### ISSUE THREAD

**Issue by GuidoZuccarelli** [ansible/ansible#67972]
##### SUMMARY

The invocation to git module executes the command `git fetch --tags` which can fail under certain circumstances (some tag remotely overridden).
Even by adding the option `force: "yes"` the command it is executed without the **-f** option.
To workaround it, it is necessary to execute the command `git fetch --tags -f` previous to the git module execution.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Git Module

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Generate a git tag:
```
git checkout bla
git tag -f DEV
git push origin DEV --force
```

And remotely, override it:

```
git checkout foo
git tag -f DEV
git push origin DEV --force
```

Then in the first local environment, execute the ansible git task

```yaml
- name: "Clone/refresh Staging Repo with SSH"
      when: use_ssh == "yes"
      git:
        dest: "{{ staging_repo }}"
        name: "some git repo"
        version: "master"
        force: "yes"
        key_file: '~/.ssh/id_rsa'
        ssh_opts: "-o StrictHostKeyChecking=no"
```

##### EXPECTED RESULTS

If I set the option force to true, I would expect to get the git fetch command executed with the -f option.

##### ACTUAL RESULTS

```paste below
TASK [Clone/refresh Staging Repo with SSH] ************************************************************************************
4:37
fatal: [localhost]: FAILED! => {“changed”: false, “cmd”: [“/usr/local/bin/git”, “fetch”, “--tags”, “origin”], “msg”: “Failed to download remote objects and refs:  From XXXX   some commit..other commit  master               -> origin/master\n   
 ! [rejected]        DEV -> DEV (would clobber existing tag)}
```
