### ISSUE TITLE
Add AWS ECS Capacity Provider Strategy Support

### ISSUE THREAD

**Issue by Alex-Richman** [ansible/ansible#67997]
##### SUMMARY
Add support for AWS ECS Cluster Capacity Provider Strategy configuration.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ecs_cluster

##### ADDITIONAL INFORMATION
Enable configuration of ECS cluster capacity providers and strategies thereof.

```yaml
ecs_cluster:
  ...
  capacity_providers:
    - "FARGATE"
    - "FARGATE_SPOT"
  capacity_provider_strategy:
    - capacity_provider: "FARGATE"
      base: 1
      weight: 1
    - capacity_provider: "FARGATE_SPOT"
      weight: 100 
```

https://github.com/terraform-providers/terraform-provider-aws/issues/11150
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-capacity-providers.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.put_cluster_capacity_providers
