### ISSUE TITLE
Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol(unable to disable stickiness not supported in NLB)

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#67993]
##### SUMMARY
We are using Ansible 2.5 to deploy AWS resources in our environment. From March 02, 2019 our deployment is failing with the below error.

ERROR:
=====
TASK [immutable_server : target group for analytics-tst-plebos loadbalancer] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InvalidConfigurationRequestException:
An error occurred (InvalidConfigurationRequest) when calling the ModifyTargetGroupAttributes operation: 
Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol
17:21:08 fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "InvalidConfigurationRequest", "message": "Stickiness type 'lb_cookie'
is not supported for target groups with the TCP protocol", "type": "Sender"}, "msg": "An error occurred (InvalidConfigurationRequest) 
when calling the ModifyTargetGroupAttributes operation: Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol", 
"response_metadata": {"http_headers": {"connection": "close", "content-length": "359", "content-type": "text/xml", "date": "Tue, 03 Mar 2020 11:51:08 GMT", 
"x-amzn-requestid": "23b0ca87-e0fb-4b84-b93b-ae5b1363df53"}, "http_status_code": 400, "request_id": "23b0ca87-e0fb-4b84-b93b-ae5b1363df53", "retry_attempts": 0}}

##### ISSUE TYPE
- Bug Report - Unable to disable stickiness not supported in NLB

##### COMPONENT NAME
- name: "target group for {{ server_name }} loadbalancer"
  elb_target_group:
    state: present
    name: "{{ server_name }}-elb"
    protocol: tcp
    port: 80
    target_type: instance
    deregistration_delay_timeout: 35
    modify_targets: False
    vpc_id: "{{ vpc_out.vpcs.0.id }}"
    health_check_protocol: "{{ load_balancer_ping_protocol | default('http') }}"
    health_check_port: "{{ load_balancer_ping_port | default('80') }}"
    health_check_path: "{{ load_balancer_ping_path | default('/elb/ping')}}"
    health_check_interval: 30
    unhealthy_threshold_count: 2
    healthy_threshold_count: 2
    stickiness_enabled: False
    tags: "{{ aws.tags_as_dict }}"
  register: target_group_out

##### ANSIBLE VERSION
```paste below
Ansible version = 2.5.0
```

##### CONFIGURATION

```paste below
- name: "target group for {{ server_name }} loadbalancer"
  elb_target_group:
    state: present
    name: "{{ server_name }}-elb"
    protocol: tcp
    port: 80
    target_type: instance
    deregistration_delay_timeout: 35
    modify_targets: False
    vpc_id: "{{ vpc_out.vpcs.0.id }}"
    health_check_protocol: "{{ load_balancer_ping_protocol | default('http') }}"
    health_check_port: "{{ load_balancer_ping_port | default('80') }}"
    health_check_path: "{{ load_balancer_ping_path | default('/elb/ping')}}"
    health_check_interval: 30
    unhealthy_threshold_count: 2
    healthy_threshold_count: 2
    stickiness_enabled: False
    tags: "{{ aws.tags_as_dict }}"
  register: target_group_out

```

##### OS / ENVIRONMENT
Ubuntu 18.04 LTS / AWS environment

##### STEPS TO REPRODUCE
Kindly use the below playbook to deploy loadbalancer using Ansible on AWS cloud.

```yaml
- name: "target group for {{ server_name }} loadbalancer"
  elb_target_group:
    state: present
    name: "{{ server_name }}-elb"
    protocol: tcp
    port: 80
    target_type: instance
    deregistration_delay_timeout: 35
    modify_targets: False
    vpc_id: "{{ vpc_out.vpcs.0.id }}"
    health_check_protocol: "{{ load_balancer_ping_protocol | default('http') }}"
    health_check_port: "{{ load_balancer_ping_port | default('80') }}"
    health_check_path: "{{ load_balancer_ping_path | default('/elb/ping')}}"
    health_check_interval: 30
    unhealthy_threshold_count: 2
    healthy_threshold_count: 2
    stickiness_enabled: False
    tags: "{{ aws.tags_as_dict }}"
  register: target_group_out
```

##### EXPECTED RESULTS
An AWS Network loadbalancer will be created.

##### ACTUAL RESULTS
The deployment fails with below error.

```paste below
 TASK [immutable_server : target group for analytics-tst-plebos loadbalancer] ***
17:21:08 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InvalidConfigurationRequestException:
An error occurred (InvalidConfigurationRequest) when calling the ModifyTargetGroupAttributes operation: 
Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol
17:21:08 fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "InvalidConfigurationRequest", "message": "Stickiness type 'lb_cookie'
is not supported for target groups with the TCP protocol", "type": "Sender"}, "msg": "An error occurred (InvalidConfigurationRequest) 
when calling the ModifyTargetGroupAttributes operation: Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol", 
"response_metadata": {"http_headers": {"connection": "close", "content-length": "359", "content-type": "text/xml", "date": "Tue, 03 Mar 2020 11:51:08 GMT", 
"x-amzn-requestid": "23b0ca87-e0fb-4b84-b93b-ae5b1363df53"}, "http_status_code": 400, "request_id": "23b0ca87-e0fb-4b84-b93b-ae5b1363df53", "retry_attempts": 0}}

```

##### References
I can see a similar issue occurred for terraform users as well.

https://github.com/terraform-providers/terraform-provider-aws/issues/10494
