### ISSUE TITLE
oom killer - worker found in dead state - local playbook - set_fact

### ISSUE THREAD

**Issue by haanjde** [ansible/ansible#67996]
##### SUMMARY

After a task crashed on a server, I triaged the problem down to a small (except for the data) local task that is reproducing the problem hard.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct  7 2019, 17:36:04) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
<!--- This command did not produce any output, except for a returncode, which was 0.-->
```

##### OS / ENVIRONMENT

Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
Linux mylaptop 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Also hard reproducible on 

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
Linux server 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

##### STEPS TO REPRODUCE

ansible-playbook bug.yml > buglog.txt 2>&1

```yaml
---
- name: DNS - BIND 9 - test
  hosts: localhost
  gather_facts: yes
  become: true
  ignore_errors: no

  tasks:
    - name: Initialize an empty list for our strings
      set_fact:
        changes: []
        filenames: []

    - name: Process rsync output
      vars:
        rsyncoutput: [
<!--- data.txt goes here -->
        ]
      set_fact:
         changes: "{{ changes + [ item.split(' ')[0] ] }}"
         filenames: "{{ filenames + [ item.split(' ')[1] ] }}"
      with_items: "{{ rsyncoutput }}"
      run_once: true

    - name: Show filenames
      debug:
        msg: "{{ filenames }}"

```
gist link to data.txt : https://gist.github.com/HaanJde/69bb55105efe6024d2b6682f614c9497

##### EXPECTED RESULTS

I expected the values in the fact filenames to be shown.

##### ACTUAL RESULTS

process got killed by oom killer, ended with rc=1 and the message "ERROR! A worker was found in a dead state" was added to the output.

```paste below
gist link to output.txt : https://gist.github.com/HaanJde/a9def1e4d981428ea572ba689244ede6
gist link to syslog.txt : https://gist.github.com/HaanJde/dada78925d3c7fa8aefc8121ea01aa36
```
