### ISSUE TITLE
Unexpected Behavior with set theory Filters and Generators

### ISSUE THREAD

**Issue by Arvedui** [ansible/ansible#68008]
##### SUMMARY

The set theory filters intersect and difference are order dependent if the second input is a generator.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Set Theory filters

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/marcel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Just execute the provided playbook

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - set_fact:
      list1: ['a', 'b', 'c']
      list2: ['c', 'b', 'a']

  - name: passes - both inputs are lists
    set_fact:
      difference: "{{ list1 | difference(list2) }}"
    failed_when: "difference != []"
    ignore_errors: yes

  - name: failes - second input is a generator
    set_fact:
      difference: "{{ list1 | difference(list2 | map('string')) }}"
    failed_when: "difference != []"
    ignore_errors: yes

  - name: passes - second input is a list created from the generator
    set_fact:
      difference: "{{ list1 | difference(list2 | map('string') | list) }}"
    failed_when: "difference != []"
    ignore_errors: yes

  - name: passes - both inputs are lists
    set_fact:
      intersection: "{{ list1 | intersect(list2) }}"
    failed_when: "intersection != list1"
    ignore_errors: yes

  - name: failes - second input is a generator
    set_fact:
      intersection: "{{ list1 | intersect(list2 | map('string')) }}"
    failed_when: "intersection != list1"
    ignore_errors: yes

  - name: passes - second input is a list created from the generator
    set_fact:
      intersection: "{{ list1 | intersect(list2 | map('string') | list) }}"
    failed_when: "intersection != list1"
    ignore_errors: yes

```

##### EXPECTED RESULTS

I would expect all tasks to execute without error.

##### ACTUAL RESULTS

```paste below
Using /etc/ansible/ansible.cfg as config file

PLAY [127.0.0.1] ****************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [set_fact] *****************************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {"ansible_facts": {"list1": ["a", "b", "c"], "list2": ["c", "b", "a"]}, "changed": false}

TASK [passes - both inputs are lists] *******************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {"ansible_facts": {"difference": []}, "changed": false, "failed_when_result": false}

TASK [failes - second input is a generator] *************************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"ansible_facts": {"difference": ["b", "c"]}, "changed": false, "failed_when_result": true}
...ignoring

TASK [passes - second input is a list created from the generator] ***************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {"ansible_facts": {"difference": []}, "changed": false, "failed_when_result": false}

TASK [passes - both inputs are lists] *******************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {"ansible_facts": {"intersection": ["a", "b", "c"]}, "changed": false, "failed_when_result": false}

TASK [failes - second input is a generator] *************************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"ansible_facts": {"intersection": ["a"]}, "changed": false, "failed_when_result": true}
...ignoring

TASK [passes - second input is a list created from the generator] ***************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {"ansible_facts": {"intersection": ["a", "b", "c"]}, "changed": false, "failed_when_result": false}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=2   


```
