### ISSUE TITLE
unrelated variables get evaluated in set_fact every time resulting in high CPU load

### ISSUE THREAD

**Issue by mowgli** [ansible/ansible#68005]
##### SUMMARY
I use the following:
```
group_vars/all.yaml:ansible_become_pass: "{{ lookup('passwordstore', 'sudo') }}"
```

This allows to get the sudo password via pass.

Now I found out, that, when using set_fact in a loop, that task produced high CPU load. -vvv does not show why but when killing the gpg-agent, it gives the error:
```
An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Command '['pass', 'sudo']' returned non-zero exit status 2.
```

So it seems that this variable is evaluated every time in the loop.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```paste below
ansible 2.9.4
  config file = /home/klaus/devel/ansible/ansible.cfg
  configured module search path = ['/home/klaus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Jan 19 2020, 22:34:52) [GCC 9.2.1 20200117]
```

##### CONFIGURATION
iDoes not apply.

##### OS / ENVIRONMENT
iDoes not apply but on Debian linux.

##### STEPS TO REPRODUCE
Add the var above and use set_fact in a loop

##### EXPECTED RESULTS
iFast run with no CPU load

##### ACTUAL RESULTS
iVery high CPU load and the task runs very long.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mowgli** [comment]
An example for such a loop would be:
```yaml
- name: Construct Root-SSH-Keys
  set_fact:
    ssh__root_authorized_keys: "{% set _x = lookup('pipe', 'echo '~item|quote~' | head -1 | ssh-keygen -l -f -').split() %}{% set _k = item.split() %}{% set _o = [] %}{% if _k[1]|regex_search('^ssh-') %}{% set _o = [_k[0]] %}{% set _k = _k[1:] %}{% endif %}{% set _o = _o + ['command=\"/usr/local/bin/ssh_command  '~ _k[2]|quote ~' '~ _x.0 ~' '~ _x.1 ~'\"'] %}{{ ssh__root_authorized_keys|d([]) + [ _o|join(',') ~' '~ _k|join(' ')] }}"
  loop: "{{ ssh_root_authorized_keys }}"
- name: Root-SSH-Keys
  authorized_key:
    exclusive: yes
    key: "{{ ssh__root_authorized_keys|d([])|join('\n') }}"
    user: root
    state: present
```

As otherwise, there is no way to use `exclusive:`
