### ISSUE TITLE
VM ip is not set using ansible vmware_guest

### ISSUE THREAD

**Issue by ChavaliShr** [ansible/ansible#68063]
##### SUMMARY
I created a vm using ansible and installed RHEL 7.6. I am trying to set the ipv4 address of the vm, but it is not getting set, even though the playbook successfully runs.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest networks

##### ANSIBLE VERSION
ansible 2.9.0
  config file = path/ansible/ansible.cfg
  configured module search path = ['path/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = path/ansible/ansible-2.9.0/lib/ansible
  executable location = path/bin/ansible
  python version = 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]

##### OS / ENVIRONMENT
RHEL 7.6 on vm

##### STEPS TO REPRODUCE
```
- name: Create a virtual machine on the ESXI host
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: /Datacenter/vm/
        #name: "my_vm_{{ item }}"
        name: test_vm_00
        guest_id: rhel7_64Guest
        state: poweredon
        datastore: "{{ datastore }}"
        esxi_hostname: "{{ esxhost }}"
        disk:
        - size_gb: 10
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: 1024
          num_cpus: 2
          scsi: paravirtual
        cdrom:
        - type: iso
          iso_path: "{{ OS_ISO_path }}"
          controller_type: ide
          controller_number: 0
          unit_number: 0
          state: present
        - type: iso
          iso_path: "{{ kickstart iso_path }}"
          controller_type: ide
          controller_number: 0
          unit_number: 1
          state: present
        networks:
        - name: VM Network
          ip: "{{ ip_address }}"
          netmask: "{{ netmask }}"
          dns_servers:
          - ****
          start_connected: yes
        wait_for_ip_address: yes
        customization:
          dns_servers:
          - ****
          domain: ****
          #wait_for_customization: yes
        wait_for_ip_address: yes
```
##### Expected Results
IP should be set on the vm in vsphere.

##### ACTUAL RESULTS
```
changed: [localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "0",
        "hw_cluster": null,
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "datastore1"
        ],
        "hw_esxi_host": "****",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": "00:50:56:ad:ce:83",
            "macaddress_dash": "00-50-56-ad-ce-83",
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "VM Network"
        },
        "hw_files": [
            "[datastore1] test_vm_00/test_vm_00.vmx",
            "[datastore1] test_vm_00/test_vm_00.vmsd",
            "[datastore1] test_vm_00/test_vm_00.nvram",
            "[datastore1] test_vm_00/test_vm_00.vmdk"
        ],
        "hw_folder": "/Datacenter/vm",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": null,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 1024,
        "hw_name": "test_vm_00",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 2,
        "hw_product_uuid": "422dafa8-c0dc-e50e-e07f-90c15c622118",
        "hw_version": "vmx-14",
        "instance_uuid": "502d3587-7f01-4fc7-ee81-87c98707428d",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "moid": "vm-102",
        "snapshots": [],
        "vimref": "vim.VirtualMachine:vm-102",
        "vnc": {}
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [
                {
                    "controller_number": 0,
                    "controller_type": "ide",
                    "iso_path": "***",
                    "state": "present",
                    "type": "iso",
                    "unit_number": 0
                },
                {
                    "controller_number": 0,
                    "controller_type": "ide",
                    "iso_path": "***",
                    "state": "present",
                    "type": "iso",
                    "unit_number": 1
                }
            ],
            "cluster": null,
            "convert": null,
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "Datacenter",
            "datastore": "datastore1",
            "disk": [
                {
                    "datastore": "datastore1",
                    "size_gb": 10,
                    "type": "thin"
                }
            ],
            "esxi_hostname": "****",
            "folder": "/Datacenter/vm/",
            "force": false,
            "guest_id": "rhel7_64Guest",
            "hardware": {
                "memory_mb": 1024,
                "num_cpus": 2,
                "scsi": "paravirtual"
            },
            "hostname": "***",
            "is_template": false,
            "linked_clone": false,
            "name": "test_vm_00",
            "name_match": "first",
            "networks": [
                {
                    "dns_servers": [
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    ],
                    "ip": "{{ vm ip }}",
                    "name": "VM Network",
                    "netmask": "{{ netmask }}",
                    "start_connected": true,
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": ***,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": null,
            "use_instance_uuid": false,
            "username": "{{ username }}",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_ip_address": true
        }
    }
}
```

Now it is setting ipv6 ip, instead of ipv4
