### ISSUE TITLE
ec2_group is not idempotent for self-referenced rules

### ISSUE THREAD

**Issue by AndreasUfert** [ansible/ansible#68072]
##### SUMMARY
When creating a security group with ec2_group that has a self-referenced rule ([{ proto: all, group_name: "sg_examplegroup"}]) the module runs into a timeout when run for the first time. Yet, the security group is created. When run repeatedly it either takes very long and returns with changed: true (when called with purge_rules: true) oder returns with failed: true (when called with purge_rules: false).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /home/ansible-master/.ansible.cfg
  configured module search path = ['/home/ansible-master/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible-master/python/python-aws/lib/python3.5/site-packages/ansible
  executable location = /home/ansible-master/python/python-aws/bin/ansible
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/ansible-master/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ansible-master/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ansible-master/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=900s -o PreferredAuthentications=publickey
DEFAULT_CALLBACK_WHITELIST(/home/ansible-master/.ansible.cfg) = ['profile_tasks', 'timer']
DEFAULT_FORKS(/home/ansible-master/.ansible.cfg) = 128
DEFAULT_GATHERING(/home/ansible-master/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ansible-master/.ansible.cfg) = ['/home/ansible-master/zod_ansible/ec2.py']
DEFAULT_REMOTE_USER(/home/ansible-master/.ansible.cfg) = ansible
DEFAULT_TIMEOUT(/home/ansible-master/.ansible.cfg) = 180
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible-master/.ansible.cfg) = /home/ansible-master/.ansible_vault_pw
HOST_KEY_CHECKING(/home/ansible-master/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/ansible-master/.ansible.cfg) = /usr/bin/python3
INVENTORY_ENABLED(/home/ansible-master/.ansible.cfg) = ['script', 'yaml', 'ini']
RETRY_FILES_ENABLED(/home/ansible-master/.ansible.cfg) = True
TRANSFORM_INVALID_GROUP_CHARS(/home/ansible-master/.ansible.cfg) = silently
```

##### OS / ENVIRONMENT
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

##### STEPS TO REPRODUCE
Example code:

```
    - name: create security group (should immediately create the sg)
      ec2_group:
        profile: "{{ profile }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "sg_examplegroup"
        description: "Example Group"
        rules:
          - proto: all
            group_name: "sg_examplegroup"

    - name: re-create security group (should immediately return without changing anything)
      ec2_group:
        profile: "{{ profile }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "sg_examplegroup"
        description: "Example Group"
        rules:
          - proto: all
            group_name: "sg_examplegroup"

    - name: re-create security group (should immediately return without changing anything)
      ec2_group:
        profile: "{{ profile }}"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        name: "sg_examplegroup"
        description: "Example Group"
        rules:
          - proto: all
            group_name: "sg_examplegroup"
        purge_rules: false
```

##### EXPECTED RESULTS

Security group gets created in first task and is not changed in any of the following tasks.

##### ACTUAL RESULTS

```
TASK [create security group (should immediately create the sg)] ******************************************************************************************************
Friday 06 March 2020  12:08:10 +0100 (0:00:00.072)       0:00:00.998 ********** 
[WARNING]: Ran out of time waiting for sg-03ea4d9233e8b5af9 IpPermissions. Current: {Rule(port_range=(None, None), protocol='-1', target=('xxxxxxxxxxxx',
'sg-03ea4d9233e8b5af9', None), target_type='group', description=None)}, Desired: [Rule(port_range=(None, None), protocol='-1', target='sg-03ea4d9233e8b5af9',
target_type='group', description=None)]
changed: [localhost] => {"changed": true, "description": "Example Group", "group_id": "sg-03ea4d9233e8b5af9", "group_name": "sg_examplegroup", "ip_permissions": [{"ip_protocol": "-1", "ip_ranges": [], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": [{"group_id": "sg-03ea4d9233e8b5af9", "user_id": "xxxxxxxxxxxx"}]}], "ip_permissions_egress": [{"ip_protocol": "-1", "ip_ranges": [{"cidr_ip": "0.0.0.0/0"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "owner_id": "xxxxxxxxxxxx", "tags": {}, "vpc_id": "vpc-11e38679"}

TASK [re-create security group (should immediately return without changing anything)] ********************************************************************************
Friday 06 March 2020  12:09:17 +0100 (0:01:07.351)       0:01:08.350 ********** 
changed: [localhost] => {"changed": true, "description": "Example Group", "group_id": "sg-03ea4d9233e8b5af9", "group_name": "sg_examplegroup", "ip_permissions": [{"ip_protocol": "-1", "ip_ranges": [], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": [{"group_id": "sg-03ea4d9233e8b5af9", "user_id": "xxxxxxxxxxxx"}]}], "ip_permissions_egress": [{"ip_protocol": "-1", "ip_ranges": [{"cidr_ip": "0.0.0.0/0"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "owner_id": "xxxxxxxxxxxx", "tags": {}, "vpc_id": "vpc-11e38679"}

TASK [re-create security group (should immediately return without changing anything)] ********************************************************************************
Friday 06 March 2020  12:10:20 +0100 (0:01:03.539)       0:02:11.890 ********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (InvalidPermission.Duplicate) when calling the AuthorizeSecurityGroupIngress operation: the specified rule "peer: sg-03ea4d9233e8b5af9, ALL, ALLOW" already exists
fatal: [localhost]: FAILED! => {"boto3_version": "1.9.199", "botocore_version": "1.12.199", "changed": false, "error": {"code": "InvalidPermission.Duplicate", "message": "the specified rule \"peer: sg-03ea4d9233e8b5af9, ALL, ALLOW\" already exists"}, "msg": "Unable to authorize ingress rules: [{'IpProtocol': '-1', 'UserIdGroupPairs': [{'GroupId': 'sg-03ea4d9233e8b5af9'}]}]: An error occurred (InvalidPermission.Duplicate) when calling the AuthorizeSecurityGroupIngress operation: the specified rule \"peer: sg-03ea4d9233e8b5af9, ALL, ALLOW\" already exists", "response_metadata": {"http_headers": {"connection": "close", "date": "Fri, 06 Mar 2020 11:10:22 GMT", "server": "AmazonEC2", "transfer-encoding": "chunked"}, "http_status_code": 400, "request_id": "3e5c240e-1c34-4a9b-8431-06b67e780d34", "retry_attempts": 0}}
```
