### ISSUE TITLE
Add attribute in sysctl module to uncomment commented items

### ISSUE THREAD

**Issue by lliepins-clgx** [ansible/ansible#68075]
##### SUMMARY
In many cases, changing value of setting using sysctl moduel is not enaugh. You also need to enable ( a.k.a uncomment the settings ). That means you end up with boilerplate code (using lineinfile or block_file or even template module usage ) to do the job. To handle such cases and reduce needful length of code to achieve the result, I suggest to add one more attribute that essentially would call lineinfile or block_file module logic and uncomment the settings that sysctl module is changing.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
sysctl with lineinfile or block_file

##### ADDITIONAL INFORMATION
Currently, you need to do this to achieve the effect:
```
  - name: "Change to setting"
    lineinfile:
      path: /etc/sysctl.conf
      insertafter: EOF
      regexp: '^fs.suid_dumpable'
      line: 'fs.suid_dumpable='
      backup: yes

  - name: "Setting value and reloading dependant services"
    sysctl:
      name: fs.suid_dumpable
      value: 0
```
Instead, it could be minimIzed to:
```
  - name: "Setting value and reloading dependant services"
    sysctl:
      name: fs.suid_dumpable
      value: 0
      enabled: True
```

Now, the regexp would be called to strip everything from the begging of the line.
