### ISSUE TITLE
Option to reduce verbosity on a task

### ISSUE THREAD

**Issue by tomsucho** [ansible/ansible#68084]
##### SUMMARY
I'm mostly running on verbosity 1 as it is nicely logging things by default and no need to bother with explicit debug statements. However in some situations like with looping with_items going over a large list of massive dicts it is just an overkill of information and can't seem to find any way to limit that output. I tried no_log=True but that still gives one line per item, and is meaningless output "censored" and moreover this hides things when task fails with something.

Using verbosity 0 and instrumenting code with debug statements is lot more work and so it would be easier to use verbosity 1 and just turn off logging for the few tasks we don't want to see the output from. So having an option to control this per task (override the global verbosity level) would be great.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
tasks

##### ADDITIONAL INFORMATION

```yaml
- hosts: localhost
  gather_facts: no

  vars:
    my_var: ""
    my_list:
      - {name: Joe, value: 1}
      - {name: Zoe, value: 2}
      - {name: bingo, value: bingo}
      - {name: dan, value: 4}

  tasks:
    - set_fact:
        my_var: "{{ item.value if item.name=='bingo' else my_var }}"
      with_items: "{{ my_list }}"
      verbosity: 0
      loop_control:
        label: "{{ item.name }}"
```
