### ISSUE TITLE
Add Consul metadatas support

### ISSUE THREAD

**Issue by mxmorin** [ansible/ansible#68129]
##### SUMMARY
Consul now supports Metadatas. Is it possible to include this functionality ?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Ansible Consul

##### ADDITIONAL INFORMATION
Add metadatas informations to Consul module

```yaml
  - name: register metadatas dans Consul
    consul:
      host: "{{ consul_host }}"
      service_name: "xxxx"
      service_port: 80
      tags:
        - mytag
      metadatas:
        mymetadata: mymetadata_value
```
