### ISSUE TITLE
Copy module does not work with directory_mode

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible#6812]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel e2d86e4f43) last updated 2014/04/01 17:56:40 (GMT -400)

Also occurs in
ansible 1.5.3 (master 0c565e56ce) last updated 2014/04/01 21:17:05 (GMT -400)
##### Environment:

N/A
##### Summary:

It seems that the directory_mode functionality does not work in either the latest stable revision (1.5.4) or the tip of the devel branch.
##### Steps To Reproduce:

A trivial test case is attached, thanks to Johannes Graumann who reported this issue at Debian.

``` yaml
- name: "Demonstrate the copy bug"
  hosts: all
  tasks:
  - name: "Demonstrate the copy bug 1a - Make up src"
    action: shell mkdir -p /tmp/2bcopied
  - name: "Demonstrate the copy bug 1b - Make up src"
    action: shell touch /tmp/2bcopied/dummy.txt
  - name: "Demonstrate the copy bug 2 - Make up dest"
    action: shell mkdir -p /tmp/copytarget
  - name: "Demonstrate the copy bug 3 - Working copy"
    action: copy src=/tmp/2bcopied dest=/tmp/copytarget mode=644
  - name: "Demonstrate the copy bug 4 - Breaking copy"
    action: copy src=/tmp/2bcopied dest=/tmp/copytarget mode=644 directory_mode=755
```
##### Expected Results:

Success, the directory is copied with the correct permissions set on the directory and its child files.
##### Actual Results:

When you attempt to copy a folder to a destination while using the directory_mode functionality as in the playbook above, you get the following error:

```
msg: unsupported parameter for module: directory_mode
```
