### ISSUE TITLE
vmware_tag_manager - certificate validation fails

### ISSUE THREAD

**Issue by vMarkusK** [ansible/ansible#68128]
##### SUMMARY

If `validate_certs: yes` is set for the module vmware_tag_manager, the task fails.

```
FAILED! => {"changed": false, "msg": "Failed to login to <vCenter FQDN>: HTTPSConnectionPool(host='<vCenter FQDN>', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",),))"}
```

OpenSSL itself and other modules like vmware_guest_disk, do validate the certificate succenfully.

If `validate_certs: no` is set for the module vmware_tag_manager, the task executes successfully.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_tag_manager

/lib/ansible/modules/cloud/vmware/vmware_tag_manager.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT

- RHEL 8.1
- VMware vCenter 6.7 Update 3

##### STEPS TO REPRODUCE

```yaml
- name: Add additional Disk to {{ vm_name }}
  vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: yes
      uuid: "{{ deploy_vm.instance.hw_product_uuid }}"
      disk:
        - size_gb: 40
          datastore: "{{ deploy_vm.instance.hw_datastores.0 }}"
          scsi_controller: 1
          unit_number: 0
          scsi_type: paravirtual
          state: present
  delegate_to: localhost
- name: Add WTS vSphere Tag to {{ vm_name }}
  vmware_tag_manager:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: yes
      tag_names:
        - VM_App:WTS 
      object_name: "{{ vm_name }}"
      object_type: VirtualMachine
      state: add
  delegate_to: localhost 
```

##### EXPECTED RESULTS

Execution of the Task with certificate validation.

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "msg": "Failed to login to <vCenter FQDN>: HTTPSConnectionPool(host='<vCenter FQDN>', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",),))"}
```
