### ISSUE TITLE
Collections vs Platform abstraction action plugins

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#68134]
#### SUMMARY

Consider the case:
* `action/package.py` (ansible-base)
* `zypper.py` (community.general)

Using ansible-base today (without routing.yml) the use of `package` failes on opensuse as Ansible doesn't know where to look for `zypper`.

**Use-cases**
* 2.9 like out the box experience
* Users doing `when: ansible_pkg_mgr == 'yum'` (can't just expand to FQDN)
* 

```yaml
- name: install mysqldb_test rpm dependencies
  yum:
    name: "{{ mysql_packages }}"
    state: latest
  when: ansible_pkg_mgr == 'yum'
  notify: cleanup mysql
```

**Questions**
* Should we update the documentation for `package` and `service` to guide people to use the platform-specific modules?
* Should we suggest that people set `ansible_pkg_mgr` to the FQCN?
* Should `module_utils/facts/system/pkg_mgr.py` (in ansible-base) return FQCN?
* Should we just move all the package modules into ansible-base?

The same most likely applies to `service` and any other platform abstraction action plugins.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
package

##### ANSIBLE VERSION

```paste below
2.10
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
