### ISSUE TITLE
influxdb_user makes changes on --check run

### ISSUE THREAD

**Issue by tubemeister** [ansible/ansible#68139]
##### SUMMARY
influxdb_user changes the admin flag on existing users during a --check run

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
influxdb_user

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION
no changes

##### OS / ENVIRONMENT
Ubuntu 18.04 Bionic
Ansible 2.9.6 from PPA
Influxdb 1.7.9-1 from https://repos.influxdata.com/ubuntu bionic stable

##### STEPS TO REPRODUCE
- install influxdb, no configuration
- influx: create user 'test' with password 'test'
- influx: show users
```
> show users;
user         admin
----         -----
test         false
```

- ansible-playbook playbook.yml --check --diff
- influx: show users
```
> show users;
user         admin
----         -----
test         true
```

playbook.yml:
```
---
- name: Test case influxdb_user
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
    - name: test influxdb_user
      influxdb_user: 
        user_name: 'test'
        user_password: 'foo'
        admin: yes

```

##### EXPECTED RESULTS
Playbook runs in check mode, shows a change for user 'test' but no actual changes are made.

##### ACTUAL RESULTS
Playbook runs in check mode but user 'test' gets altered. (admin: true, possibly more)
```
changed: [hostname] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "admin": true, 
            "grants": null, 
            "hostname": "localhost", 
            "password": "root", 
            "port": 8086, 
            "proxies": {}, 
            "retries": 3, 
            "ssl": false, 
            "state": "present", 
            "timeout": null, 
            "udp_port": null, 
            "use_udp": false, 
            "user_name": "test", 
            "user_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "username": "root", 
            "validate_certs": true
        }
    }
}

```
