### ISSUE TITLE
gcp_compute_instance module failing with error "Invalid value for field 'resource.networkInterfaces[0].network"

### ISSUE THREAD

**Issue by vipinadm** [ansible/ansible#68133]
##### SUMMARY
gcp_compute_instance module failing to create instance in non default network with error "Invalid value for field 'resource.networkInterfaces[0].network" 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  executable location = /Library/Frameworks/Python.framework/Versions/3.7/bin/ansible
  python version = 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION

```paste below
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/Users/vipina/ansible/roles']
```

##### STEPS TO REPRODUCE

#1. Note the existing network and subnet details 
#2. Get info on a network  ( gcp_compute_network_info module) -- register: gcpnetwork
#3 Get info on a subnetwork (gcp_compute_subnetwork_info module-- register: subnetwork 
$4 Create an IP address (gcp_compute_address)
$5 Create a instance 

```yaml

tasks:
    - name: get info on a network
      gcp_compute_network_info:
        filters:
        - name = us-central
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
      register: gcpnetwork

    - name: Get info on a subnetwork
      gcp_compute_subnetwork_info:
        region: "{{ region }}"
        filters:
        - name = us-central-subnet
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ credentials_file }}"
      register: subnetwork

    - name: Create an IP address for first instance
      gcp_compute_address:
        name: "{{ name_zonea }}-ip"
        network_tier: "STANDARD"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        subnetwork: "{{ subnetwork }}"
      register: gcea_ip

    - name: Bring up the first instance in the first zone
      gcp_compute_instance:
        name: "{{ name_zonea }}"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ image }}"
        network_interfaces:
        - subnetwork: "{{ gcpnetwork }}"
        - subnetwork: "{{ subnetwork }}"
          access_configs:
            - name: External NAT
              nat_ip: "{{ gcea_ip }}"
              type: ONE_TO_ONE_NAT
        tags:
          items:
            - http-server
            - https-server
        zone: "{{ zone }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
      register: gcea
```

##### EXPECTED RESULTS

Playbook should create a compute instances in an existing custom VPC network with expected networking

##### ACTUAL RESULTS

Playbook failing at task "gcp_compute_instance" with below error

"msg": "GCP returned error: {'error': {'errors': [{'domain': 'global', 'reason': 'invalid', 'message': \"Invalid value for field 'resource.networkInterfaces[0].network': ''. The referenced network resource cannot be found.\"}], 'code': 400, 'message': \"Invalid value for field 'resource.networkInterfaces[0].network': ''. The referenced network resource cannot be found.\"}}"

```paste below

```
