### ISSUE TITLE
ios_command: "unable to set terminal parameters" error when user has "privilege level 0"

### ISSUE THREAD

**Issue by clarsen** [ansible/ansible#68149]
##### SUMMARY

Basically same as https://github.com/ansible/ansible/issues/44672 however that was closed out.

When attempting to run a playbook that uses the ios_command against a Cisco router that has "privilege level 0" configured for the user that ansible logs in as (ansible_user), the playbook fails with an, "unable to set terminal parameters" error because the "terminal length 0" command isnot permitted when in privilege 0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/terminal/ios.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /usr/bin/python3
```

##### OS / ENVIRONMENT

Linux (Alpine 3.11.3 docker container)

##### STEPS TO REPRODUCE

On Cisco:
```
enable
config terminal
username <the_user> privilege 0 secret <the password>
exit
wr mem
```

Invoking ansible:
`ansible-playbook -i inventory ./playbook.yml`

inventory:
```yaml
all:
  children:
    cisco:
      hosts:
        some_host:
          ansible_host: some_host_fqdn

```
group_vars/cisco.yml
```yaml
ansible_connection: network_cli
ansible_network_os: ios
ansible_user: <the user>
ansible_password: <the password>
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: <the enable password>
```

playbook.yml:
```yaml
---
- name: Get version (Cisco)
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Execute single "show version" command.
      ios_command:
        commands: show version
      register: response
    - name: Print the command output
      debug:
        var: response.stdout

```

##### EXPECTED RESULTS

result of `show version` stored in `response`.

##### ACTUAL RESULTS

````
fatal: [some_host]: FAILED! => {
    "changed": false,
    "msg": "unable to set terminal parameters"
}
````

Suggested fix:
 - add to https://github.com/ansible/ansible/pull/47290 to also not re-raise Exception for "terminal length 0"
PR to follow...
