### ISSUE TITLE
mysql_user module, problem with "priv" option

### ISSUE THREAD

**Issue by markotitel** [ansible/ansible#6816]
##### Issue Type:

Bug Report
##### Ansible Version:

```
marko@FOX:~/provisioning$ ansible --version
ansible 1.6 (devel fe88fcb6d2) last updated 2014/04/02 14:48:14 (GMT +200)
```
##### Environment:

Ubuntu 13.04
##### Summary:

mysql_user "priv" option does not work as expected when provided with subelements.
##### Steps To Reproduce:

Create a list:

```
users:
  - user: detlic
    webdir:
      - woodpecker.com
      - aligator.com
    db:
      - aligatordb
      - woodpeckerdb
      - detlicdb
```

Simple task to grant privileges to db.

```
- name: grant privileges on databases
  mysql_user: name={{ item.0.user }} host=localhost priv={{ item.1 }}.*:ALL
  with_subelements:
      - users
      - db
```
##### Expected Results:

Expected results should show all databases  when logged in as mysql user that those databases are granted to.

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| aligatordb         |
| woodpeckerdb       |
| detlicdb           |
+--------------------+
4 rows in set (0.00 sec)
```
##### Actual Results:

Instead of expected I get

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| detlicdb           |
+--------------------+
2 rows in set (0.00 sec)
```

Only last db is granted to user.
##### How did I check expected result?

I created additional task with RAW command which uses the same list.

```
- name: grant privileges on databases
  raw: mysql -e "grant all privileges on {{ item.1 }}.* to {{ item.0.user}}@localhost"
  with_subelements:
      - users
      - db
```

And I get resluts as expected.
