### ISSUE TITLE
In module cron parameter weekday seems not working

### ISSUE THREAD

**Issue by duch94** [ansible/ansible#68166]
##### SUMMARY
In module `cron` parameter `weekday` does not set the day of week in crontab. But alias `dow` does.
https://docs.ansible.com/ansible/latest/modules/cron_module.html#parameter-weekday

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module `cron`

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Work station is on Ubuntu 18.04.4 LTS, server is on Debian GNU/Linux 9

##### STEPS TO REPRODUCE

```yaml
# that will not change the weekday param
  - name: Weekly metrics calculation
    job: $PYTHONENV $PYTHONPATH/script/start.py
    weekday: 1
    hour: 9
    minute: 34

# that will
  - name: Weekly metrics calculation
    job: $PYTHONENV $PYTHONPATH/script/start.py
    dow: 1
    hour: 9
    minute: 34
```

##### EXPECTED RESULTS

Expected in crontab: 
```
#Ansible: Weekly metrics calculation
34 9 * * 1 $PYTHONENV $PYTHONPATH/script/start.py
```

##### ACTUAL RESULTS

Actial result in crontab: 
```
#Ansible: Weekly metrics calculation
34 9 * * * $PYTHONENV $PYTHONPATH/script/start.py
```
