### ISSUE TITLE
tower_send unable to process job template with multiple choice (single select) prompt

### ISSUE THREAD

**Issue by seamlesstesterWS1** [ansible/ansible#68188]
##### SUMMARY

tower_send module unable to process job templates that leverage survey's with Multiple Choice (single select) prompts.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tower_send
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

AWX Version: 9.2.0 

##### STEPS TO REPRODUCE

Create a job template with a survey. Within the survey, add a multiple choice (single select) prompt. Export the job template using the tower_receive module. Import the configuration using the tower_send module. 

```yaml
 - name: "Gather Configurations from Source Tower"
     tower_receive:
       tower_host: "{{ sourceTowerUrl }}"
       tower_username: "{{ sourceTowerUsername }}"
       tower_password: "{{ sourceTowerPassword }}"
       validate_certs: no
       job_template:  ["Template with MC Survey Option"]
     register: sourceTowerConfig
- name: "Import Configurations into Destination Tower"
     tower_send:
       assets: "{{ sourceTowerConfig.assets }}"
       tower_host: "{{ destinationTowerUrl }}"
       tower_username: "{{ destinationTowerUsername }}"
       tower_password: "{{ destinationTowerPassword }}"
       validate_certs: no

```

##### EXPECTED RESULTS

Job template is imported to destination tower with survey intact.

##### ACTUAL RESULTS

See stack below:

```paste below
"msg": "The Tower server claims it was sent a bad request.\n\nPOST https://awx-mig.test.net/api/v2/job_templates/17/survey_spec/\nParams: None\nData: {\"description\": \"\", \"spec\": [{\"required\": true, \"min\": \"None\", \"default\": \"a\", \"max\": \"None\", \"question_description\": \"\", \"choices\": \"a\\\\nb\\\\nc\", \"new_question\": true, \"variable\": \"mcOption\", \"question_name\": \"MC Option\", \"type\": \"multiplechoice\"}], \"name\": \"\"}\n\nResponse: {\"error\":\"The min limit in survey question 0 expected to be integer.\"}",

```
