### ISSUE TITLE
Unable to invoke handlers from another role with a Collection

### ISSUE THREAD

**Issue by ram-ibm** [ansible/ansible#68181]
##### SUMMARY

We have developed an Ansible Collection that has multiple roles. One of the roles has all the common handlers. We are unable to reference the handlers in that role from other roles in the Collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible Collection

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.5
  config file = None
  configured module search path = ['/Users/ram/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ram/anscoll/lib/python3.8/site-packages/ansible
  executable location = /Users/ram/anscoll/bin/ansible
  python version = 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) [Clang 6.0 (clang-600.0.57)]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = False
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /Users/ram/ansible.log
```

##### OS / ENVIRONMENT

I am executing code on MacBook Pro running Mojave.

##### STEPS TO REPRODUCE

Create two roles in a Collection. One role contains handlers/main.yml and the other role references the handlers using fully qualified names.

```yaml
# Update existing stanza(s)/entries in reverse proxy config file
- name: Configure Reverse Proxy stanza(s) entries (Updates)
  ibm.isam.isam:
    log:       "{{ log_level | default('INFO') }}"
    force:     "{{ force | default(False) }}"
    action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.update
    isamapi:
      reverseproxy_id: "{{ update_reverseproxy_conf_reverseproxy_id }}"
      stanza_id:       "{{ item.stanza_id }}"
      entry_id:        "{{ item.entry_id }}"
      value_id:        "{{ item.value_id }}"
  with_items:          "{{ update_reverseproxy_conf_entries }}"
  when: update_reverseproxy_conf_entries is defined
  notify:
  - 'ibm.isam.common_handlers : Commit Changes'
  - 'ibm.isam.common_handlers : Restart Reverse Proxy'

```

##### EXPECTED RESULTS

Playbook executing the task provided completes both the task (which it has no issues) but then is not able to find the handlers and fails.

##### ACTUAL RESULTS

```paste below
ansible-playbook rp_conf_update.yml -i ~/test_inv.yml -e "ansible_python_interpreter='/Users/ram/anscoll/bin/python' stanza_id=server entry_id=worker-threads value_id=220" --check -vvvv
ansible-playbook 2.9.5
  config file = None
  configured module search path = ['/Users/ram/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ram/anscoll/lib/python3.8/site-packages/ansible
  executable location = /Users/ram/anscoll/bin/ansible-playbook
  python version = 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) [Clang 6.0 (clang-600.0.57)]
No config file found; using defaults
setting up inventory plugins
host_list declined parsing /Users/ram/test_inv.yml as it did not pass its verify_file() method
script declined parsing /Users/ram/test_inv.yml as it did not pass its verify_file() method
Parsed /Users/ram/test_inv.yml inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /Users/ram/anscoll/lib/python3.8/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: rp_conf_update.yml ***************************************************
Positional arguments: rp_conf_update.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
check: True
inventory: ('/Users/ram/test_inv.yml',)
extra_vars: ("ansible_python_interpreter='/Users/ram/anscoll/bin/python' stanza_id=server entry_id=worker-threads value_id=220",)
forks: 5
1 plays in rp_conf_update.yml

PLAY [Update RP Entry] *********************************************************
META: ran handlers

TASK [update_reverseproxy_conf : Configure Reverse Proxy stanza(s) entries (Updates)] ***
task path: /Users/ram/.ansible/collections/ansible_collections/ibm/isam/roles/update_reverseproxy_conf/tasks/main.yml:2
<192.168.198.190> attempting to start connection
<192.168.198.190> using connection plugin isam
<192.168.198.190> local domain socket does not exist, starting it
<192.168.198.190> control socket path is /Users/ram/.ansible/pc/b473346846
<192.168.198.190> local domain socket listeners started successfully
<192.168.198.190> 
<192.168.198.190> local domain socket path is /Users/ram/.ansible/pc/b473346846
<192.168.198.190> ESTABLISH LOCAL CONNECTION FOR USER: ram
<192.168.198.190> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638 `" && echo ansible-tmp-1583969213.115962-141288217426638="` echo /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638 `" ) && sleep 0'
Using module file /Users/ram/.ansible/collections/ansible_collections/ibm/isam/plugins/modules/isam.py
<192.168.198.190> PUT /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/tmp5kmhc7f5 TO /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638/AnsiballZ_isam.py
<192.168.198.190> EXEC /bin/sh -c 'chmod u+x /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638/ /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638/AnsiballZ_isam.py && sleep 0'
<192.168.198.190> EXEC /bin/sh -c '/Users/ram/anscoll/bin/python /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638/AnsiballZ_isam.py && sleep 0'
<192.168.198.190> EXEC /bin/sh -c 'rm -f -r /Users/ram/.ansible/tmp/ansible-local-25600l6az5z7e/ansible-tmp-1583969213.115962-141288217426638/ > /dev/null 2>&1 && sleep 0'
changed: [192.168.198.190] => (item={'stanza_id': 'server', 'entry_id': 'worker-threads', 'value_id': '220'}) => {
    "ansible_facts": {
        "version": null
    },
    "ansible_loop_var": "item",
    "changed": true,
    "cmd": "ibmsecurity.isam.web.reverse_proxy.configuration.entry.update(isamAppliance=self.isam_server, force=False, check_mode=True, reverseproxy_id=\"default\", stanza_id=\"server\", entry_id=\"worker-threads\", value_id=\"220\")",
    "data": {},
    "delta": "0:00:11.104097",
    "end": "2020-03-11 17:27:05.672153",
    "invocation": {
        "module_args": {
            "action": "ibmsecurity.isam.web.reverse_proxy.configuration.entry.update",
            "force": false,
            "isamapi": {
                "entry_id": "worker-threads",
                "reverseproxy_id": "default",
                "stanza_id": "server",
                "value_id": "220"
            },
            "log": "INFO"
        }
    },
    "item": {
        "entry_id": "worker-threads",
        "stanza_id": "server",
        "value_id": "220"
    },
    "rc": 0,
    "start": "2020-03-11 17:26:54.568056",
    "status_code": 0,
    "stdout": "",
    "stdout_lines": [
        ""
    ]
}
ERROR! The requested handler 'ibm.isam.common_handlers : Commit Changes' was not found in either the main handlers list nor in the listening handlers list
```
