### ISSUE TITLE
debconf module: /bin/sh: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#6819]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible 1.6 (devel)
##### Environment:

Debian
##### Summary:

Debconf module fails when `value=` contains parameter with brackets(edit: parenthesis).
##### Steps To Reproduce:

```

---
- hosts: all
  sudo: True
  tasks:
    - name: First debconf value
      debconf: name=mailman question='mailman/site_languages' vtype='multiselect'
               value='en (English)'
    - name: Second debconf value
      debconf: name=mailman question='mailman/site_languages' vtype='multiselect'
               value='en (English), pl (Polish)'
```
##### Expected Results:

Debconf database is correctly configured and then updated with new value. Example result:

```
mailman mailman/site_languages  multiselect     en (English), pl (Polish)
```
##### Actual Results:

```
TASK: [First debconf value] *************************************************** 
failed: [anna] => {"failed": true}
msg: /bin/sh: 1: Syntax error: "(" unexpected


FATAL: all hosts have already failed -- aborting
```
