### ISSUE TITLE
Roles can't use collection modules when collections are listed at playbook level

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#68198]
##### SUMMARY

If I put a task from my playbook which uses a module defined in a collection into a role, it breaks the playbook.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

  - collections
  - roles

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Feb  9 2020, 13:28:08) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS Catalina

##### STEPS TO REPRODUCE

```yaml
# Create role.
mkdir roles && cd roles
ansible-galaxy init test_role
nano test_role/tasks/main.yml # add contents below 
cd ../

# Install collection (note that the k8s_log module is in pre-release).
ansible-galaxy collection install community.kubernetes

# Create and run playbook.
nano main.yml # add contents below
ansible-playbook main.yml
```

`main.yml` contents:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - community.kubernetes

  # This task works.
  pre_tasks:
    - name: Create a test namespace (pre_tasks).
      k8s_log:
        name: example-pod
        namespace: testing

  # But the same task doesn't work in a role.
  roles:
    - test_role
```

`test_role/tasks/main.yml` contents:

```yaml
---
- name: Create a test namespace (role).
  k8s_log:
    name: example-pod
    namespace: testing

```

##### EXPECTED RESULTS

The playbook should run. The `k8s_log` task should work the same in the role `tasks/main.yml` file as it does in the rest of the playbook.

##### ACTUAL RESULTS

```
$ ansible-playbook -i 'localhost,' main.yml
ERROR! couldn't resolve module/action 'k8s_log'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/jgeerling/Downloads/test/roles/test_role/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Create a test namespace (role).
  ^ here
```
