### ISSUE TITLE
Add support for subuid and subgid to user module

### ISSUE THREAD

**Issue by 00willo** [ansible/ansible#68199]
##### SUMMARY
Subuid's and subgid's are used as part of Linux user namespaces. Heavily relied on by container technologies such as podman/docker.

Adding subuid and subgid support in the user module would make this easier.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
The ansible user module

##### ADDITIONAL INFORMATION
The usermod command supports the following:
```
usermod --add-subuids 200000-201000 --add-subgids 200000-201000 johndoe
```

This results in a corresponding entry in `/etc/subuid` and `/etc/subgid`
```
johndoe:200000:1000
```

It could possibly look, like either this:
```yaml
- name: Add the user 'johndoe' with a specific uid and a primary group of 'admin'
  user:
    name: johndoe
    comment: John Doe
    uid: 1001
    group: admin
    subuids: 200000-201000
    subgids: 200000-201000
```
or this:
```yaml
- name: Add the user 'johndoe' with a specific uid and a primary group of 'admin'
  user:
    name: johndoe
    comment: John Doe
    uid: 1001
    group: admin
    subuid: 200000:1000
    subgid: 200000:1000
```
Depending on why you're using it, there may need to be a handler run to execute some commands, similar to the systemd daemon needing a reload after modifying a service file.  I'm just not 100% sure on what all the possible combinations of a user task being "changed" are that would require this handler to be triggered.  IE, updating a comment or group would not.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/user.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by PayBas** [comment]
Yes please!

Workarounds for this are extremely annoying to have to do:
```
- name: Add subuid/subgid entries for {{ ansible_username }} user because the user module doesn't handle this (yet)
  # See https://github.com/ansible/ansible/issues/68199
  block:
    - name: Get {{ subuid_file }} contents
      command: cat {{ subuid_file }}
      register: subuid
      changed_when: False

    - name: Add {{ ansible_username }} user to {{ subuid_file }}
      block:
        - name: Add ansible as first user to {{ subuid_file }}
          command: usermod -v 100000-165535 {{ ansible_username }}
          when: subuid.stdout | trim | length == 0

        - block:
            - set_fact:
                highest_subuid: "{{ subuid.stdout_lines[-1].split(':')[1] }}"

            - name: Add {{ ansible_username }} to list of users in {{ subuid_file }}
              command: usermod -v {{ highest_subuid|int + 65536 }}-{{ highest_subuid|int + 65536 + 65536 -1 }} {{ ansible_username }}
          when: subuid.stdout | trim | length > 0
      when: "'{{ ansible_username }}:' not in subuid.stdout"

    - name: Get {{ subgid_file }} contents
      command: cat {{ subgid_file }}
      register: subgid
      changed_when: False

    - name: Add {{ ansible_username }} user to {{ subgid_file }}
      block:
        - name: Add {{ ansible_username }} as first user to {{ subgid_file }}
          command: usermod -w 100000-165535 {{ ansible_username }}
          when: subgid.stdout | trim | length == 0

        - block:
            - set_fact:
                highest_subgid: "{{ subgid.stdout_lines[-1].split(':')[1] }}"

            - name: Add {{ ansible_username }} to list of users in {{ subgid_file }}
              command: usermod -w {{ highest_subgid|int + 65536 }}-{{ highest_subgid|int + 65536 + 65536 -1 }} {{ ansible_username }}
          when: subgid.stdout | trim | length > 0
      when: "'{{ ansible_username }}:' not in subgid.stdout"
```
