### ISSUE TITLE
os_router removes all interfaces on change

### ISSUE THREAD

**Issue by infcs** [ansible/ansible#68208]
##### SUMMARY

os_router removes all interfaces from router and recreates them even if I just add another internal network
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_router
##### ANSIBLE VERSION

```paste below
ansible 2.7.9
  config file = None
  configured module search path = [u'/home/*****/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/openstack/.venv/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/lib/openstack/.venv/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Debian 9.9 / ansible and openstacksdk are not from os

##### STEPS TO REPRODUCE

My test setup has 3 networks: external network test_exp and internal networks n1 and n2.
An instance d1 is connected to internal network n1. A precreated floating ip address is not yet attached to d1.
The play creates the router r1 and connects it only with n1.
The play attaches the floating ip to d1.
The play alters router r1 to connect it with n1 and n2. This step failes because os_router tries to delete all interfaces from the router first, which is not possible because of the floating ip.

```yaml

- hosts: all
  connection: local
  gather_facts: no
  run_once: true
  tasks:
    - name: create router
      os_router:
        auth: "{{openstack_auth}}"
        name: r1
        network: test_exp
        interfaces:
          - n1

    - name: create floating_ip
      os_floating_ip:
        auth: "{{openstack_auth}}"
        server: d1
        fixed_address: 192.168.1.21
        floating_ip_address: 10.20.45.11
        network: test_exp
        wait: yes
        reuse: yes

    - name: alter router
      os_router:
        auth: "{{openstack_auth}}"
        name: r1
        network: test_exp
        interfaces:
          - n1
          - n2
```

##### EXPECTED RESULTS

os_router should not delete all interfaces on any changes to the list of interfaces. In this example
it even fails because neutron does not allow to remove interfaces where floating ips are attached.

I tested this only on ansible 2.7 but according to the code I expect this to fail on any later version as well.

##### ACTUAL RESULTS

```paste below
PLAY [all] ******************************************************************************************************************

TASK [create router] ******************************************************************************************************************
changed: [manage]

TASK [create floating_ip] ******************************************************************************************************************
changed: [manage]

TASK [alter router] ******************************************************************************************************************
fatal: [manage]: FAILED! => {"changed": false, "msg": "Error detaching interface from router 7d4b2bf6-223d-4deb-9280-e59e08a667d9: 
Client Error for url: https://******:9696/v2.0/routers/7d4b2bf6-223d-4deb-9280-e59e08a667d9/remove_router_interface.json, 
Router interface for subnet 217cd366-b78b-4cd5-a02f-089430a6c5db on router 7d4b2bf6-223d-4deb-9280-e59e08a667d9 cannot be deleted, as it is required by one or more floating IPs."}

PLAY RECAP ******************************************************************************************************************
manage                     : ok=2    changed=2    unreachable=0    failed=1
```
