### ISSUE TITLE
Lineinfile and Replace modules do not allow for setting the temporary directory

### ISSUE THREAD

**Issue by infrascripting** [ansible/ansible#68218]
The replace and lineinfile modules do not allow for temporary directories to be set with environment variables. See https://github.com/ansible/ansible/issues/24082 for a similar bug report.

!component =lib/ansible/modules/files/lineinfile.py

However, this is for the facts directory. Here's how it is reproducible:

On the target server we are trying to write to `/etc/ansible/facts.d/cloudera.fact`:
```
# ls -al / | grep etc
drwxr-xr-x. 151 root     root         12288 Mar  9 08:38 etc
# ls -al /etc | grep ansible
drwxr-xr-x    3 root         root           4096 Nov 22  2016 ansible
# ls -al /etc/ansible/ | grep 'facts.d'
drwxr-xr-x    2 root root  4096 Mar 13 11:53 facts.d
# ls -al /etc/ansible/facts.d/ | grep cloudera.fact
-rw-rw-r--  1 cloudera-scm cloudera-scm   10 Mar 13 11:54 cloudera.fact
```

Here is the playbook:
```
cat playbooks/test_svcacct_lineinfile.yml
- hosts: all
  become: True
  become_user: cloudera-scm
  gather_facts: False
  tasks:
    - name: Add lineinfile
      lineinfile:
        line: 'key=value2'
        state: present
        create: False
        path: '/etc/ansible/facts.d/cloudera.fact'
```

This will fail since there is no way to override the directory that lineinfile hard-codes the destination directory as the one which has the file which is being edited, instead of `remote_tmp`  or any of the `['TMP', 'TEMP', 'TMPDIR']` environment variables:

https://github.com/ansible/ansible-modules-core/blob/devel/files/lineinfile.py#L213

which calls

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L2238

Hardcoding the `dir` param as the argument to the `tempfile.mkstemp()` call.

Is there a way that this can be changed to be able to set a custom temp dir?
