### ISSUE TITLE
GitLab requires admin tokens to create a unprivileged project runner

### ISSUE THREAD

**Issue by EvanCarroll** [ansible/ansible#68224]
##### SUMMARY

If a non-admin tries to register a project runner, they get 403 Forbidden. The current module only works to add runners with admin-level permissions.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`gitlab_runner`

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ecarroll/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

I am trying to create a runner, currently I have..

```
- name: Setup GitLab Runner
  gitlab_runner:
    api_url: https://git.asdf.net/
    api_token: <redacted_bar>
    registration_token: <redacted_foo>
    description: Build Box
    tag_list:
      - whmstore
      - build
```

The problem with this is `redacted_foo` is not the registration token found in 

> A valid registration token is required for registering a new runner. To create shared runners, you need to ask your administrator to give you this token. It can be found at https://$GITLAB_URL/admin/runners/.

(above from docs), instead the registration token I am using is the `Project Registration Token` from the [docs on gitlab,](https://docs.ansible.com/ansible/latest/modules/gitlab_runner_module.html#stq=ruby&stp=1)

> ### Registering a specific Runner with a project registration token
> 
> To create a specific Runner without having admin rights to the GitLab instance, visit the project you want to make the Runner work for in GitLab:
> 
> 1. Go to **Settings > CI/CD** to obtain the token
> 1. [Register the Runner](https://docs.gitlab.com/runner/register/)

If a non-admin tries to register a project runner, they get 403 Forbidden

Currently using Ansible 2.96
