### ISSUE TITLE
s3_lifecycle.py - add support for all storage modes

### ISSUE THREAD

**Issue by vchopra-eightfold** [ansible/ansible#68234]
##### SUMMARY

The module is missing support for a few storage classes - REDUCED_REDUNDANCY, INTELLIGENT_TIERING, DEEP_ARCHIVE.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

s3_lifecycle

##### ADDITIONAL INFORMATION

This will enable the full set of features that lifecycle rules allow us. Doesn't make sense to not support all storage classes.

```yaml
- s3_lifecycle:
    name: mybucket
    prefix: logs
    status: enabled
    storage_class: intelligent_tiering
    transition_days: 7
    state: present
```
