### ISSUE TITLE
lxd_container failing to fetch images

### ISSUE THREAD

**Issue by cweilguny** [ansible/ansible#68237]
##### SUMMARY

The lxd_container module is unable to fetch images. The example used in the documentation fails with the following message:
`msg: 'Failed to fetch https://uk.images.linuxcontainers.org/1.0/images/ubuntu/xenial/amd64: 404 Not Found'`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/chris/.ansible.cfg) = ['/home/chris/Projects/ansible/inventory/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/chris/.ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/chris/.ansible.cfg) = ['/home/chris/Projects/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/chris/.ansible.cfg) = yaml
RETRY_FILES_ENABLED(/home/chris/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Host: ArchLinuxm updated to the latest one hour ago
Target OS: Debian 10

##### STEPS TO REPRODUCE

Just use the first play of the lxd_container documentation.

```yaml
---
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd # if you get a 404, try setting protocol: simplestreams
          alias: ubuntu/xenial/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

##### EXPECTED RESULTS

An LXD container to be created.

##### ACTUAL RESULTS

The image can't be fetched.

```paste below
msg: 'Failed to fetch https://uk.images.linuxcontainers.org/1.0/images/ubuntu/xenial/amd64: 404 Not Found'
```
