### ISSUE TITLE
IOS_User Does not remove User account appropriately

### ISSUE THREAD

**Issue by jvanderaa** [ansible/ansible#68238]
##### SUMMARY

When using ios_user module to remove a user account that was created with ios_user by using `state: absent` it does not appropriately remove the user account. In working on a post to demonstrate the module I found that I was still able to log in with the user account after setting the state to abset.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_user

##### ANSIBLE VERSION

```paste below
nsible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/joshv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/joshv/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Target: CIsco IOS
```
Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(1)T, RELEASE SOFTWARE (fc1)
```

##### STEPS TO REPRODUCE

1. Create user with the task:

```yaml
    - name: "TASK 1: Add local username with SSH Key"
      ios_user:
        name: joshv
        nopassword: True
        sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      register: config_output
```
Produces the following:

```
        "commands": [
            "ip ssh pubkey-chain",
            "username joshv",
            "key-hash ssh-rsa <HASH_REMOVED> <local_user>,
            "exit",
            "exit",
            "username joshv nopassword"
```

2. Attempt to remove the user

```yaml
    - name: "TASK 1: Remove local username with SSH Key"
      ios_user:
        name: joshv
        nopassword: True
        sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: absent
      register: config_output
```

Produces the following command output
```
        "commands": [
            "ip ssh pubkey-chain",
            "no username joshv",
            "exit"
        ],
```

##### EXPECTED RESULTS

The `absent` flag should also remove the `username joshv nopassword` configuration.

##### ACTUAL RESULTS

See above in line. The resulting configuration on the device is:

```
rtr-1#show run | i username
username cisco secret 5 $1$GNTQ$RpNy.E9LZMzgrOz/g2pYJ.
username joshv nopassword
```

This will allow anyone to log in with an expected username missing.
