### ISSUE TITLE
gcp_container_cluster module throws error when username and password is not specified

### ISSUE THREAD

**Issue by rmonde** [ansible/ansible#68245]
##### SUMMARY
I am trying to launch GKE (google kubernets engine cluster using gcp_container_cluster module in ansible. In the [documentation ](https://docs.ansible.com/ansible/latest/modules/gcp_container_cluster_module.html) page of this module, specifying username and password parameters is not mandatory. However, when I omit them, it throws an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_container_cluster

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/a1258567_msp01_ey_net/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
GCP VM
Linux ansible-vm 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
Python 2.7.13

##### STEPS TO REPRODUCE

Assuming default vpc network and subnets with enough IP ranges
```
---
  - connection: local
    hosts: localhost
    gather_facts: true

- name: Launch GKE cluster
      gcp_container_cluster:
        name: my-cluster-custom
        initial_node_count: 1
        master_auth:
          client_certificate_config:
            issue_client_certificate: yes
        location: "us-central1-a"
        locations: "us-central1-a,us-central1-b"
        auth_kind: serviceaccount
        service_account_file: "/opt/my-svc-account.json" 
        state: present
        private_cluster_config:
          enable_private_nodes: yes
          master_ipv4_cidr_block: "172.31.0.0/28"
          enable_private_endpoint: yes 
      register: my-gke-cluster
```

##### EXPECTED RESULTS

Error -
An exception occurred during task execution. To see the full traceback, use -vvv. 
The error was: KeyError: 'username'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": 
"Traceback (most recent call last):\n  File \"/home/xxxxxxx/.ansible/tmp/ansible-tmp-1583927920.43-220053887510172/AnsiballZ_gcp_container_cluster.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/xxxxxxxxxx/.ansible/tmp/ansible-

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. 
The error was: KeyError: 'username'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": 
"Traceback (most recent call last):\n  File \"/home/xxxxxxx/.ansible/tmp/ansible-tmp-1583927920.43-220053887510172/AnsiballZ_gcp_container_cluster.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/xxxxxxxxxx/.ansible/tmp/ansible-
```
