### ISSUE TITLE
get_url returns "HTTP Error 304: Not Modified"

### ISSUE THREAD

**Issue by maxyko** [ansible/ansible#68243]
##### SUMMARY
get_url returns "HTTP Error 304: Not Modified" instead a status code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
2.8.4 or higher

##### OS / ENVIRONMENT
ubuntu-16.04.5 LTS

##### STEPS TO REPRODUCE
```
- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins_hostname }}:8080{{ jenkins_url_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: no
```

##### EXPECTED RESULTS
receive status code

##### ACTUAL RESULTS
```
fatal: [jenkins]: FAILED! => {
    "attempts": 5,
    "changed": false,
    "dest": "/opt/jenkins-cli.jar",
    "elapsed": 0,
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/opt/jenkins-cli.jar",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "http://localhost:8080/jnlpJars/jenkins-cli.jar",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "mode": "0644",
    "msg": "HTTP Error 304: Not Modified",
    "owner": "root",
    "size": 3625094,
    "state": "file",
    "uid": 0,
    "url": "http://localhost:8080/jnlpJars/jenkins-cli.jar"
}
```
