### ISSUE TITLE
redfish_config module fails to set BIOS attributes for boolean based attrs

### ISSUE THREAD

**Issue by jyundt** [ansible/ansible#68251]
##### SUMMARY
Setting BIOS attributes using the `redfish_config` module and the `SetBiosAttributes` command will fail for Redfish implementations that use boolean based BIOS attributes.

As an example, the `ConsoleRedirection` BIOS setting for one of our BMCs only accepts a boolean value. However, the default value for `bios_attribute_value` is undefined and defaults to type `str`. 
 ([Line in question for Ansible 2.9.6](https://github.com/ansible/ansible/blob/v2.9.6/lib/ansible/modules/remote_management/redfish/redfish_config.py#L145).) 

As a result, boolean inputs are converted to strings. When passed to the BMC, the BMC responds with an HTTP 400 error. 

Changing the type to `raw` (and a minor tweak to `set_bios_attributes()` in `redfish_utils.py`) will allow this to work as expected. I'll get a PR rolling shortly.

One thing to note: I've only tested on 2.9 and 2.8. I believe the changes introduced in #62764 will require a separate PR for >= 2.10.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

redfish_utils.py
redfish_config
##### ANSIBLE VERSION

``` 
ansible 2.9.6
  config file = /home/jyundt/git/firmware_updater/tests/ansible.cfg
  configured module search path = ['/home/jyundt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jyundt/git/firmware_updater/2.9.6/lib64/python3.6/site-packages/ansible
  executable location = /home/jyundt/git/firmware_updater/2.9.6/bin/ansible
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

``` 
ANSIBLE_PIPELINING(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = 3
DEFAULT_CALLBACK_WHITELIST(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = ['profile_tasks', 'timer']
DEFAULT_GATHERING(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = 120
DEFAULT_HASH_BEHAVIOUR(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = merge
DEFAULT_MODULE_UTILS_PATH(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = ['/home/jyundt/git/firmware_updater/tests/module_utils']
DEFAULT_TIMEOUT(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = 120
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/jyundt/.ansible/vault_pass
HOST_KEY_CHECKING(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = 360
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = 180
PERSISTENT_CONNECT_TIMEOUT(/home/jyundt/git/firmware_updater/tests/ansible.cfg) = 360
```

##### STEPS TO REPRODUCE

Sample ansible playbook, should work with either 2.8 or 2.9

```
---
- hosts: all
  gather_facts: false
  vars:
    bmc_username: admin
    bmc_password: hunter2
    bmc_address: 192.168.100.100
  tasks:
  - name: Configure boolean BIOS Settings
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: "ConsoleRedirection"
      bios_attribute_value: True
      baseuri: "{{ bmc_address }}"
      username: "{{ bmc_username }}"
      password: "{{ bmc_password }}"

  - name: Configure string BIOS Settings
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attribute_name: "IPv4HTTPSupport"
      bios_attribute_value: "Disabled"
      baseuri: "{{ bmc_address }}"
      username: "{{ bmc_username }}"
      password: "{{ bmc_password }}"

```

##### EXPECTED RESULTS
I would expect these the boolean based attributes to get set correctly.

##### ACTUAL RESULTS

Sample failure using 2.9.6:
```
(2.9.6) [jyundt@aurora tests]$ time ansible-playbook -i 10.39.67.209, supermicro_redfish.yml 

PLAY [all] *********************************************************************************************************************************

TASK [Configure boolean BIOS Settings] *****************************************************************************************************
Monday 16 March 2020  10:55:31 -0400 (0:00:00.087)       0:00:00.087 ********** 
[WARNING]: The value True (type bool) in a string field was converted to u'True' (type string). If this does not look like what you expect,
quote the entire value to ensure it does not change.
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host 10.39.67.209 should use /usr/bin/python3, but is using /usr/bin/python for 
backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this 
host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be 
removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [10.39.67.209]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "HTTP Error 400 on PATCH request to 'https://10.208.4.153/redfish/v1/Systems/1/Bios/SD', extended message: 'The value null for the property ConsoleRedirection is of a different type than the property can accept.'"}

PLAY RECAP *********************************************************************************************************************************
10.39.67.209               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Monday 16 March 2020  10:55:34 -0400 (0:00:03.637)       0:00:03.725 ********** 
=============================================================================== 
Configure boolean BIOS Settings ----------------------------------------------------------------------------------------------------- 3.64s
Playbook run took 0 days, 0 hours, 0 minutes, 3 seconds

real	0m5.148s
user	0m1.817s
sys	0m0.186s
(2.9.6) [jyundt@aurora tests]$
```

cc @nlopez
