### ISSUE TITLE
Add 'sources' parameter for Makefile-alike commands to modules which support 'creates' parameter (e.g. command)

### ISSUE THREAD

**Issue by krissi** [ansible/ansible#68257]
##### SUMMARY

When creating files using remote commands there is the parameter `creates` to check if the command needs to run. A new `sources` parameter (List) would make it possible to recreate the file when needed by running the specified command again. Like in Makefiles by comparing if the mtime of the `sources` paths agains the `creates` path.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

command

##### ADDITIONAL INFORMATION

The new parameter allows updates/recreates of files created on the remote system, like a Makefile. When using `when` there would be a variable and a `stat` needed for each source. When the playbook aborts in between, the variables will be lost, leaving the system in an invalid state. This parameter would mitigate the problem

This can be used in:
  * Anything a Makefile can be used for
  * Merging tls cert and private key without the private key leaving the remote system
  * Regenerating initramfs after changes of its config

```yaml
- template:
    src: some_config.j2
    dest: /etc/initramfs-tools/conf.d/some_config

- command: "update-initramfs -u"
  args:
    creates: /boot/initrd.img
    sources:
      - /etc/initramfs-tools/initramfs.conf
      - /etc/initramfs-tools/conf.d/some_config
      - /etc/initramfs-tools/conf.d/some_other_config
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/commands/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@krissi I use `stat` module to check the existence and change in modification time of files. Adding a new feature in `command` module, will increase the complexity. 

Let me know what do you think about this. 

needs_info

**Comment by krissi** [comment]
@Akasurde I am currently using `stat` as well. If I do it correctly, I think needs very complex playbooks. Am I correct that the example above when built with `stat` would look like this (pseudocode)? This is my current approach.

```yaml
- template:
    src: some_config.j2
    dest: /etc/initramfs-tools/conf.d/some_config

- stat:
    path: /boot/initrd.img
    register: dest

- stat:
    path: /etc/initramfs-tools/initramfs.conf
    register: source1

- stat:
    path: /etc/initramfs-tools/conf.d/some_config
    register: source2

- stat:
    path: /etc/initramfs-tools/conf.d/some_other_config
    register: source3

- command: "update-initramfs -u"
  args:
    creates: /boot/initrd.img
  when: "(!dest.stat.exists) or (source1.stat.exists and source1.stat.mtime > dest.stat.mtime) or (source2.stat.exists and source2.stat.mtime > dest.stat.mtime) or (source3.stat.exists and source3.stat.mtime > dest.stat.mtime)"
```
