### ISSUE TITLE
k8s_info ignores authorization parameters

### ISSUE THREAD

**Issue by kazito1** [ansible/ansible#68267]
##### SUMMARY
k8s_info is ignoring username: and password: fields

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible2_8/lib/python2.7/site-packages/ansible
  executable location = bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

RHEL 7.7, ansible 2.9. The remote OCP cluster is OCP 4.3

##### STEPS TO REPRODUCE

1. Create a playbook that connects to a RHEL 7.7 box that is trying to reach an OCP cluster
2. Make sure that the aforementioned box has python2-openshift and python2-kubernetes installed
3. Use the k8s_info module

```yaml

- name: Test for the k8s_info module
  hosts: ProxyA

  vars_files:
    - site/network_variables.yaml
    - site/ocp_variables.yaml

  tasks:
    - name: Try to login to OCP cluster
      k8s_auth:
        host: https://api.{{ ClusterName }}.{{ DNS_Domain }}:6443
        username: "{{ OCP_admin }}"
        password: "{{ OCP_Password }}"
        validate_certs: no
      register: k8s_auth_result
      ignore_errors: yes

    - name: test the description of a role
      k8s_info:
        host: https://api.{{ ClusterName }}.{{ DNS_Domain }}:6443
        username: "{{ OCP_admin }}"
        password: "{{ OCP_Password }}"
        validate_certs: no
        kind: ClusterRoleBinding
      register: blah
```

##### EXPECTED RESULTS

Receive information about the OCP requested resource in blah variable

##### ACTUAL RESULTS

The cluster returns Forbidden even if the user has cluster-admin privileges

```paste below
Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1584395020.86-82300935789067/AnsiballZ_k8s_info.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1584395020.86-82300935789067/AnsiballZ_k8s_info.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1584395020.86-82300935789067/AnsiballZ_k8s_info.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.clustering.k8s.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_k8s_info_payload_yE6iRL/ansible_k8s_info_payload.zip/ansible/modules/clustering/k8s/k8s_info.py\", line 179, in <module>\r\n  File \"/tmp/ansible_k8s_info_payload_yE6iRL/ansible_k8s_info_payload.zip/ansible/modules/clustering/k8s/k8s_info.py\", line 175, in main\r\n  File \"/tmp/ansible_k8s_info_payload_yE6iRL/ansible_k8s_info_payload.zip/ansible/modules/clustering/k8s/k8s_info.py\", line 148, in execute_module\r\n  File \"/tmp/ansible_k8s_info_payload_yE6iRL/ansible_k8s_info_payload.zip/ansible/module_utils/k8s/common.py\", line 200, in get_api_client\r\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 108, in __init__\r\n    self.__init_cache()\r\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 137, in __init_cache\r\n    self.__resources.update(self.parse_api_groups())\r\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 187, in parse_api_groups\r\n    groups_response = load_json(self.request('GET', '/{}'.format(prefix)))['groups']\r\n  File \"/usr/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 395, in request\r\n    _return_http_data_only=params.get('_return_http_data_only', True)\r\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\r\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\r\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 155, in __call_api\r\n    _request_timeout=_request_timeout)\r\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 342, in request\r\n    headers=headers)\r\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/rest.py\", line 231, in GET\r\n    query_params=query_params)\r\n  File \"/usr/lib/python2.7/site-packages/kubernetes/client/rest.py\", line 222, in request\r\n    raise ApiException(http_resp=r)\r\nkubernetes.client.rest.ApiException: (403)\r\nReason: Forbidden\r\nHTTP response headers: HTTPHeaderDict({'Date': 'Mon, 16 Mar 2020 21:43:41 GMT', 'Content-Length': '189', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'no-cache, private'})\r\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"forbidden: User \\\"system:anonymous\\\" cannot get path \\\"/apis\\\"\",\"reason\":\"Forbidden\",\"details\":{},\"code\":403}\r\n\r\n\r\n
```
