### ISSUE TITLE
nios_host_record can not use nested  Vault password

### ISSUE THREAD

**Issue by bergmannf** [ansible/ansible#68275]
##### SUMMARY
When trying to use the `nios_host_record` module using a nested `vaulted` variable for the password breaks with the follwing error:

```
fatal: [localhost]: FAILED! => {
    "msg": "Unable to pass options to module, they must be JSON serializable: Object of type AnsibleVaultEncryptedUnicode is not JSON serializable"
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nios_host_record

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /home/florian/code/test/ansible.cfg
  configured module search path = ['/home/florian/code/test/library', '/home/florian/code/test/roles/kubespray/library']
  ansible python module location = /home/florian/.local/share/virtualenvs/test-y4iIM3Df/lib/python3.7/site-packages/ansible
  executable location = /home/florian/.local/share/virtualenvs/test-y4iIM3Df/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below
DEFAULT_JINJA2_NATIVE(/home/florian/code/test/ansible.cfg) = True
DEFAULT_MODULE_PATH(/home/florian/code/test/ansible.cfg) = ['/home/florian/code/test/library', '/home/florian/code/test/roles/kubespray/library']
DEFAULT_ROLES_PATH(/home/florian/code/test/ansible.cfg) = ['/home/florian/code/test/roles', '/home/florian/code/test/roles/kubespray/roles']
```

##### OS / ENVIRONMENT

```
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

Infoblox client version:

```
pipenv run python -c 'import infoblox_client; print(infoblox_client.__version__)'
0.4.25
```

##### STEPS TO REPRODUCE

Attempt to pass the configuration of `nios_provider` as a dictionary to the [`nios_host_record`](https://docs.ansible.com/ansible/latest/modules/nios_host_record_module.html) module.

The variable `password` is stored nested:

```yaml
nios_provider:
  host: "host"
  username: "user"
  password: ! vault |
          <vault_here>
```

It is passed to the `nios_host_record` as a `dictionary`:

```yaml
- hosts: localhost
  tasks:
    - name: Remove a hostrecord from infoblox
      nios_host_record:
        name: "my-hostrecord.local"
        ipv4addrs:
          - ipv4addr:
              "192.168.1.120"
        state: absent
        provider: "{{ nios_provider }}"

```

##### EXPECTED RESULTS

Passing a variable with nested vaulted variable should work and not break the module.

##### ACTUAL RESULTS

```
TASK [Remove a hostrecord from infoblox] *************************************
fatal: [localhost]: FAILED! => {"msg": "Unable to pass options to module, they must be JSON serializable: Object of type AnsibleVaultEncryptedUnicode is not JSON serializable"}
```
