### ISSUE TITLE
dig filter does not correctly use IPv6 servers when the '@' notation is used

### ISSUE THREAD

**Issue by kalfeher** [ansible/ansible#68277]
##### SUMMARY
The following will fail:
lookup('dig', 'example.com', 'qtype=SOA', '@2001:4860:4860::8888') 
whereas the following will succeed:
lookup('dig', 'example.com', 'qtype=SOA', 'name_server=2001:4860:4860::8888') 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
the lookup filter 'dig' which uses dnspython

##### ANSIBLE VERSION

```
ansible 2.9.3
  config file = /home/ansible/lab/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/ansible/lab/ansible/ansible.cfg) = [u'timer', u'mail #', u'log_plays']
DEFAULT_HOST_LIST(/home/ansible/lab/ansible/ansible.cfg) = [u'/home/ansible/lab/ansible/hosts']
DEFAULT_LOG_PATH(/home/ansible/lab/ansible/ansible.cfg) = /var/log/ansible.log
```

##### OS / ENVIRONMENT
target OS is gentoo

##### STEPS TO REPRODUCE

```yaml
# this will fail with:
  - name: Test dig lookup feature
    hosts: myhosts
    gather_facts: no
    vars:
      resolvers:
        - "8.8.8.8"
        - "2610:00a1:1018:000:0000:0000:0000:5" # Neustar
        - "2620:fe::fe"
      domain: "example.com"
    tasks:
    - debug:
        msg: "{{ lookup('dig', domain +'.', 'qtype=SOA', '@'+ item) }}"
      loop: "{{resolvers}}"
```
The above code will receive this error:
FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errors.AnsibleError'>, original message: dns lookup NS: The DNS query name does not exist: 2610:00a1:1018:000:0000:0000:0000:5.localdomain."}

This play will work:
```yaml
---

  - name: Test dig lookup feature
    hosts: myhosts
    gather_facts: no
    vars:
      resolvers:
        - "8.8.8.8"
        - "2610:00a1:1018:000:0000:0000:0000:5" # Neustar
        - "2620:fe::fe"
      domain: "example.com"
    tasks:
    - debug:
        msg: "{{ lookup('dig', domain +'.', 'qtype=SOA', 'name_server='+ item) }}"
      loop: "{{resolvers}}"
```

##### EXPECTED RESULTS

ok: [myhost] => (item=8.8.8.8) => {
    "msg": "ns.icann.org. noc.dns.icann.org. 2019121355 7200 3600 1209600 3600"
}
ok: [myhost] => (item=2610:00a1:1018:000:0000:0000:0000:5) => {
    "msg": "ns.icann.org. noc.dns.icann.org. 2019121355 7200 3600 1209600 3600"
}
ok: [myhost] => (item=2620:fe::fe) => {
    "msg": "ns.icann.org. noc.dns.icann.org. 2019121355 7200 3600 1209600 3600"
}

##### ACTUAL RESULTS

```paste below
ok: [myhost] => (item=8.8.8.8) => {
    "msg": "ns.icann.org. noc.dns.icann.org. 2019121355 7200 3600 1209600 3600"
}
fatal: [myhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'dig'. Error was a <class 'ansible.errors.AnsibleError'>, original message: dns lookup NS: The DNS query name does not exist: 2610:00a1:1018:000:0000:0000:0000:5.localdomain."}

```
