### ISSUE TITLE
postgresql_info is not working 

### ISSUE THREAD

**Issue by seeavosh** [ansible/ansible#68285]
Hello 

postgresql_info  is not working it says it's not 

issue type bug 

```
- name: Collect PostgreSQL version and extensions
  become: yes
  become_user: postgres
  postgresql_info:
    filter: ver*,ext*

- name: Collect all info except settings and roles
  become: yes
  become_user: postgres
  postgresql_info:
    filter: "!settings,!roles"

# On FreeBSD with PostgreSQL 9.5 version and lower use pgsql user to become
# and pass "postgres" as a database to connect to
- name: Collect tablespaces and repl_slots info
  become: yes
  become_user: pgsql
  postgresql_info:
    db: postgres
    filter:
    - tablesp*
    - repl_sl*

- name: Collect all info except databases
  become: yes
  become_user: postgres
  postgresql_info:
    filter:
    - "!databases"

```

```
ERROR
ERROR! 'postgresql_info' is not a valid attribute for a Play

```
##### ANSIBLE VERSION
2.9

##### OS / ENVIRONMENT
Ubuntu 19

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@seeavosh: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
Hi @seeavosh,

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

The error `ERROR! 'postgresql_info' is not a valid attribute for a Play` is correct, since you are directly using task examples in your playbook.

It should be - 

```yaml
---
- hosts: localhost
  tasks:
    - name: Collect all info except databases
      become: yes
      become_user: postgres
      postgresql_info:
        filter:
        - "!databases"
```

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
