### ISSUE TITLE
azure_rm: public_ipv4_addresses is not set for VMSS

### ISSUE THREAD

**Issue by VKAlwaysWin** [ansible/ansible#68291]
##### SUMMARY
I am using dynamic inventory for VMSS and everything is working fine, but I need to get PublicIPAddress for created VM and it is always empty.
[using Azure Resource Manager scripts I can do next thing:](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#creating-a-scale-set-with-public-ip-per-virtual-machine)
```
"publicipaddressconfiguration": {
          "name": "pub1",
          "properties": {
         "idleTimeoutInMinutes": 15,
        "ipTags": [],
        "publicIPAddressVersion": "IPv4"
    }
},
```
and Public IP will be working fine for VMSS, but public_ipv4_addresses is empty for ansible_host:
hostvar_expressions:
  ansible_host: (public_dns_hostnames + public_ipv4_addresses + private_ipv4_addresses) | first
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm

##### ANSIBLE VERSION
```
ansible 2.9.6
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/user1/playbook/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user1/playbook/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=public
DEFAULT_HOST_LIST(/home/user1/playbook/ansible.cfg) = ['/home/user1/playbook/inventory.azure_rm.yml']
DEFAULT_PRIVATE_KEY_FILE(/home/user1/playbook/ansible.cfg) = /home/user1/playbook/id_rsa
DEFAULT_REMOTE_USER(/home/user1/playbook/ansible.cfg) = user1
DEPRECATION_WARNINGS(/home/user1/playbook/ansible.cfg) = False
HOST_KEY_CHECKING(/home/user1/playbook/ansible.cfg) = False
INVENTORY_ENABLED(/home/user1/playbook/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'azure_rm']
```

##### OS / ENVIRONMENT
Ubuntu 18.04 LTS

##### STEPS TO REPRODUCE
Create VMSS with PublicIP for each VM.
Try to use public_ipv4_addresses.
public_ipv4_addresses will be empty and only private_ipv4_addresses will be populated.
Possible place to fix: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/azure_rm.py#L635

Note: for single VM (not in VMSS) everything is working fine.

```yaml
plugin: azure_rm

include_vm_resource_groups :
- ''

include_vmss_resource_groups:
- '<resource_group_name>'

auth_source: auto

hostvar_expressions:
  ansible_host: (public_dns_hostnames + public_ipv4_addresses + private_ipv4_addresses) | first

exclude_host_filters:
- powerstate != 'running'
```

##### EXPECTED RESULTS
I need to use public_ipv4_addresses for my particular scenario.

##### ACTUAL RESULTS
Ansible command: ansible-inventory -i inventory.azure_rm.yml --list returns:
![image](https://user-images.githubusercontent.com/14337164/76899704-c3f6aa00-68a0-11ea-8a81-af7ccfc44655.png)
On Azure:
![image](https://user-images.githubusercontent.com/14337164/76899787-e5f02c80-68a0-11ea-9127-86d1ffa7e834.png)
