### ISSUE TITLE
win_reboot: failed to get host boot time info

### ISSUE THREAD

**Issue by MaartenMol** [ansible/ansible#68307]
##### SUMMARY

Getting the following error: `win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr:`

While running this play on Windows Server 2019

I have seen other reports from before but those are a long time ago and from very old versions of Ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_reboot

##### ANSIBLE VERSION

```paste below
2.9.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Running the playbook from Ansible AWX on Docker using the official installation steps. No other weird errors when running Playbooks on Windows.

OS to be configured by playbooks: Windows Server 2019 latest updates

Connection method to hosts: 
```
ansible_connection: vmware_tools
ansible_shell_type: powershell
```

##### STEPS TO REPRODUCE

```
---
- name: Deploy an Active Directory
  hosts: domaincontrollers
  gather_facts: yes
  tasks:
    - name: Create new Windows domain in a new forest
      win_domain:
        dns_domain_name: "{{ organization }}"
        safe_mode_password: P@ssword
      register: domain_install
    - name: Reboot when AD feature requires it
      win_reboot:
      when: domain_install.reboot_required
```

##### EXPECTED RESULTS

Reboots when the active directory module requires it.

##### ACTUAL RESULTS

```
{
    "reboot": false,
    "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: ",
    "_ansible_no_log": false,
    "changed": false
}
```

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/windows/win_reboot.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_reboot.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ShachafGoldstein @if-meaton @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MaartenMol** [comment]
When running a simple reboot all task with win_reboot, same results:

Playbook:
```
---
- name: Reboot Windows machines
  hosts: all
  gather_facts: yes
  tasks:
    - name: Reboot the machine with all defaults
      when: ansible_facts['os_family'] == "Windows"
      win_reboot:
```

Result:
```
{
    "reboot": false,
    "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: ",
    "_ansible_no_log": false,
    "changed": false
}
```
