### ISSUE TITLE
Include_tasks cannot not locate current role directory?

### ISSUE THREAD

**Issue by benzBrake** [ansible/ansible#68309]
##### SUMMARY
my playbook
```
- hosts: mysql_master,mysql_slave
  roles:
    - role: proxysql-for-centos
```
in role proxysql-for-centos
```
---
- include_tasks: a.yml

- include_tasks: b.yml

- include_tasks: c.yml
```
a.yml can be correctly loaded, but b.yml and c.yml was search at root directory that can not be loaed.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_tasks

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /ansible/.local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventory']
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
CentOS 8.1.1911
```

##### STEPS TO REPRODUCE

Files tree
```
├── ansible.cfg
├── install-proxysql.yml
├── inventory
│   ├── hosts.yml
├── pre_tasks
│   └── proxysql.yml
└── roles
    └── proxysql-for-centos
         ├── defaults
         │   └── main.yml
         ├── files
         │   └── gen_variables_yml_from_default_yml.sh
         ├── handlers
         │   └── main.yml
         ├── meta
         │   └── main.yml
         ├── README.md
         ├── tasks
         │   ├── main.yml
         │   ├── setup-Redhat-6.yml
         │   ├── setup-Redhat-7.yml
         │   └── variables.yml
         ├── templates
         │   ├── proxysql-ad.cnf.j2
         │   ├── proxysql.cnf.j2
         │   └── proxysql.service.j2
         ├── tests
         │   ├── inventory
         │   └── test.yml
         └── vars
             └── default.yml
```

proxysql-for-centos/tasks/main.yml
```yaml
---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat-6.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "6"

- include_tasks: setup-RedHat-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"

# Configure ProxySQL.
- include_tasks: configure.yml
```
proxysql-for-centos/tasks/main.yml
```
---
- name: Include default vars
  include_vars: vars/default.yml

- name: Set proxysql config dir
  set_fact:
    proxysql_config: "{{ __proxysql_config }}"
  when: proxysql_config is not defined

- name: Query mysql version
  shell: mysqld -V | awk '{print $3}'
  register: __mysql_version
  when: mysql_version is not defined
  
- name: Define mysql_version
  set_fact:
     mysql_version: "{{ __mysql_version.stdout_lines[0] }}"
  when: __mysql_version is defined

- name: Define mysql_root_user
  set_fact:
     mysql_root_user: root
  when: mysql_root_user is not defined

- name: Define proxysql_daemon
  set_fact:
     proxysql_daemon: "{{ __proxysql_daemon }}"
  when: proxysql_daemon is not defined

- name: Define proxysql_datadir
  set_fact:
     proxysql_datadir: "{{ __proxysql_datadir }}"
  when: proxysql_datadir is not defined

- name: Define proxysql_config
  set_fact:
     proxysql_config: "{{ __proxysql_config }}"
  when: proxysql_config is not defined

- name: Define proxysql_errlog
  set_fact:
     proxysql_errlog: "{{ __proxysql_errlog }}"
  when: proxysql_errlog is not defined

- name: Define proxysql_admin_user
  set_fact:
     proxysql_admin_user: "{{ __proxysql_admin_user }}"
  when: proxysql_admin_user is not defined

- name: Define proxysql_admin_password
  set_fact:
     proxysql_admin_password: "{{ __proxysql_admin_password }}"
  when: proxysql_admin_password is not defined

- name: Define proxysql_admin_port
  set_fact:
     proxysql_admin_port: "{{ __proxysql_admin_port }}"
  when: proxysql_admin_port is not defined

- name: Define proxysql_port
  set_fact:
     proxysql_port: "{{ __proxysql_port }}"
  when: proxysql_port is not defined

- name: Define proxysql_schema
  set_fact:
     proxysql_schema: "{{ __proxysql_schema }}"
  when: proxysql_schema is not defined

- name: Define proxysql_monitor_user
  set_fact:
     proxysql_monitor_user: "{{ __proxysql_monitor_user }}"
  when: proxysql_monitor_user is not defined

- name: Define proxysql_monitor_password
  set_fact:
     proxysql_monitor_password: "{{ __proxysql_monitor_password }}"
  when: proxysql_monitor_password is not defined

- name: Define proxysql_host_group
  set_fact:
     proxysql_host_group: "{{ __proxysql_host_group }}"
  when: proxysql_host_group is not defined

- name: Define proxysql_cnf_template
  set_fact:
     proxysql_cnf_template: "{{ __proxysql_cnf_template }}"
  when: proxysql_cnf_template is not defined
```
proxysql-for-centos/vars/default.yml
```
---
__proxysql_daemon: proxysql
__proxysql_datadir: /data/proxysql
__proxysql_config: /data/proxysql/proxysql.cnf
__proxysql_errlog: /data/proxysql/proxysql.log
__proxysql_admin_user: admin
__proxysql_admin_password: admin
__proxysql_admin_port: 6032
__proxysql_port: 6033
__proxysql_schema: information_schema
__proxysql_monitor_user: monitor
__proxysql_monitor_password: monitor
__proxysql_host_group: 1
__proxysql_cnf_template: proxysql.cnf.j2
```

##### EXPECTED RESULTS

```
included: /ansible/roles/proxysql-for-centos/tasks/variables.yml for mysql_master, mysql_slave
included: /ansible/roles/proxysql-for-centos/tasks/setup-RedHat-<?>.yml for mysql_master, mysql_slave
```
##### ACTUAL RESULTS

```paste below
TASK [proxysql-for-centos : include_tasks] ***************************************
task path: /ansible/roles/proxysql-for-centos/tasks/main.yml:3
included: /ansible/roles/proxysql-for-centos/tasks/variables.yml for mysql_master, mysql_slave

TASK [proxysql-for-centos : Include default vars] ********************************
task path: /ansible/roles/proxysql-for-centos/tasks/variables.yml:2
ok: [mysql_master] => {
    "ansible_facts": {
        "__proxysql_admin_password": "admin",
        "__proxysql_admin_port": 6032,
        "__proxysql_admin_user": "admin",
        "__proxysql_cnf_template": "proxysql.cnf.j2",
        "__proxysql_config": "/data/proxysql/proxysql.cnf",
        "__proxysql_daemon": "proxysql",
        "__proxysql_datadir": "/data/proxysql",
        "__proxysql_errlog": "/data/proxysql/proxysql.log",
        "__proxysql_host_group": 1,
        "__proxysql_monitor_password": "monitor",
        "__proxysql_monitor_user": "monitor",
        "__proxysql_port": 6033,
        "__proxysql_schema": "information_schema"
    },
    "ansible_included_var_files": [
        "/ansible/roles/proxysql-for-centos/vars/default.yml"
    ],
    "changed": false
}

.....


TASK [proxysql-for-centos : include_tasks] ***************************************
task path: /ansible/roles/proxysql-for-centos/tasks/main.yml:9
fatal: [mysql_master]: FAILED! => {
    "reason": "Could not find or access '/ansible/setup-RedHat-7.yml' on the Ansible Controller."
}
fatal: [mysql_slave]: FAILED! => {
    "reason": "Could not find or access '/ansible/setup-RedHat-7.yml' on the Ansible Controller."
}
```
