### ISSUE TITLE
URI module src is looking for src in incorrect path

### ISSUE THREAD

**Issue by demian711** [ansible/ansible#68305]
##### SUMMARY
URI module src is looking for src in incorrect path. This is working ok if using curl

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
URI

##### ANSIBLE VERSION
2.8.4

##### STEPS TO REPRODUCE
Just try to PUT some content to Nexus in this case, specifying the src in a local path where file exists: /tmp/xxx.jar in this example

```yaml
- name: "Upload plugin {{ plugin_name_install }} to nexus"
  delegate_to: 127.0.0.1
  uri:
    url: "{{ nexus_base_url }}/repository/{{ nexus_repository }}/{{ nexus_upload_path }}/{{ download_url.split('/')[-1] }}"
    user: "{{ nexus_rest_auth_username }}"
    password: "{{ nexus_rest_auth_password }}"
    method: PUT
    src: "/tmp/{{ my_file }}"
    status_code: 201
```

##### EXPECTED RESULTS
File located in 'src' is uploaded

##### ACTUAL RESULTS
Module fails because is looking for src in an incorrect path.
Looking into ~/.ansible/tmp instead of /tmp

```paste below
"src": "/home/demian711/.ansible/tmp/ansible-tmp-1584523216.6812847-79331840611217/sonar-crowd-plugin-2.1.3.jar",

    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Content-Length": 3966227
            },
            "http_agent": "ansible-httpget",
            "method": "PUT",
            "mode": null,
            "owner": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/home/demian711/.ansible/tmp/ansible-tmp-1584523216.6812847-79331840611217/sonar-crowd-plugin-2.1.3.jar",
            "status_code": [
                "201"
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": null,
            "url": "xxxx",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "xxxx",
            "use_proxy": true,
            "user": "admin",
            "validate_certs": true
        }
    },

```
