### ISSUE TITLE
filetree docuentation does only covers with_filetree and not the filetree filter

### ISSUE THREAD

**Issue by Aethylred** [ansible/ansible#68319]
##### SUMMARY
The documentation for filetree lookup is incomplete: https://docs.ansible.com/ansible/latest/plugins/lookup/filetree.html

It covers only usage of the `with_filetree` iterator and does not cover usage of the `filetree` filter with the `loop` iterator

It should also provide an example of iterating over a list _and_  filetree something like below where `usernames` is a list of usernames:

```
- name: Populate new home with skeleton
      copy:
        dest: "/home/{{ item.0 }}/{{ item.1.path }}"
        src: "{{ item.1.src }}"
        owner: "{{ item.0 }}"
        group: "{{ item.0 }}"
        mode: 0640
      become: true
      loop: "{{ usernames | filetree('skeleton/') | list }}"
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
filetree lookuo

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```
> ansible --version
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/hicksaw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 25 2019, 21:02:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### OS / ENVIRONMENT
RedHat & CentOS 7.7 x86_64
