### ISSUE TITLE
facts can't be used in vars_files paths

### ISSUE THREAD

**Issue by dmourati** [ansible/ansible#6832]
##### Issue Type:

What kind of ticket is this?  Bug Report
##### Ansible Version:

Please supply the verbatim output from running “ansible --version”. 

ansible 1.5.4
##### Environment:

Ubuntu 12.04 directed at localhost
##### Summary:

Facts don't work.
##### Steps To Reproduce:

```
# cat base-ubuntu.yml 

---
# Base playbook for ubuntu
- name: Base
  user: ubuntu
  sudo: True
  tags: base
  hosts: all
  roles:
    - base-test
  vars_files:
    - vars/{{ ansible_distribution }}.yml


---
# Main task list for Base
- name: Copy rc.local template
  copy: src={{ ansible_distribution }}/rc.local dest={{ rc_local_path }}  owner=root group=root mode=0755

# ansible-playbook base-ubuntu.yml 
```
##### Actual Results:

```
PLAY [Base] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [base-test | Copy rc.local template] ************************************ 
fatal: [127.0.0.1] => One or more undefined variables: 'rc_local_path' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
       to retry, use: --limit @/root/base-ubuntu.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0 
```
##### Expected Results:

```
PLAY [Base] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]
127.0.0.1: importing /usr/local/netflixoss-ansible/playbooks/vars/Ubuntu.yml

TASK: [base-test | Copy rc.local template] ************************************ 
changed: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0  
```
