### ISSUE TITLE
ovirt_vm lacks the ability to assign a bios type

### ISSUE THREAD

**Issue by DarinJ** [ansible/ansible#68347]
##### SUMMARY
When using the ovirt_vm module you have the ability to set most options contained within the ovirt API, however one option which is missing is the ability to specify the bios type.  This creates issues if you want to use images supporting UEFI.  Both type and boot_menu are sub objects of the bios object in the ovirt API so this is a trivial task.

To preserve compatibility suggest adding the field bios_type as a top level field just as boot_menu, and check that if the field exists that it is one of the four supported strings used in the API.

##### ISSUE TYPE
- Previously omitted feature

##### COMPONENT NAME

ovirt_vm
##### ADDITIONAL INFORMATION
Expected behavior would be:
```yaml
- ovirt_vm:
    name: myvm
    sso: False
    boot_menu: True
# Valid options for bios_type are: 'q35_ovmf', 'i440fx_sea_bios', 'q35_sea_bios', 'q35_secure_boot'
# Default is i440fx_sea_bios
    bios_type: q35_ovmf 
    usb_support: True
    serial_console: True
    quota_id: "{{ ovirt_quotas[0]['id'] }}"
```
