### ISSUE TITLE
Extracting from hostvars in loop through hostvars does not work :)

### ISSUE THREAD

**Issue by stawii** [ansible/ansible#68364]
##### SUMMARY

Uh.. hard to explain.. My best shot is: `map('extract', hostvars, 'any_variable')` does not work when it is in variable which is being accessed by `hostvars[host][var]` already. See example to see use case.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hostvars

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
```

##### CONFIGURATION

```paste below
all defaults
```

##### OS / ENVIRONMENT

ALL (?)

##### STEPS TO REPRODUCE

```yaml
## group_vars/any_group.yml

whatever: foobar
whatever_more: "{{ whatever }} and more at {{ inventory_hostname }}"
all_whatever: "{{ query('inventory_hostnames', 'any_group') | map('extract', hostvars, 'whatever_more') | list }}"
```

```yaml
## playbook.yml

- hosts: any_group
  gather_facts: false
  tasks:
    - name: simple var - works
      debug:
        msg: "{{ whatever }}"

    - name: simple var loop - works
      debug:
        msg: "{{ hostvars[item]['whatever'] }}"
      loop: "{{ query('inventory_hostnames', 'any_group') }}"

    - name: jinja var - works
      debug:
        msg: "{{ whatever_more }}"

    - name: jinja var loop - works
      debug:
        msg: "{{ hostvars[item]['whatever_more'] }}"
      loop: "{{ query('inventory_hostnames', 'any_group') }}"

    - name: mapped var - works
      debug:
        msg: "{{ all_whatever }}"

    - name: mapped var loop - ugh!
      debug:
        msg: "{{ hostvars[item]['all_whatever'] }}"
      loop: "{{ query('inventory_hostnames', 'any_group') }}"
```

##### EXPECTED RESULTS

```
TASK [mapped var loop - ugh!] *********
ok: [host1] => (item=host1) => {
    "msg": [
        "foobar and more at host1",
        "foobar and more at host2"

    ]
}
ok: [host1] => (item=host2) => {
    "msg": [
        "foobar and more at host1",
        "foobar and more at host2"
    ]
}
ok: [host2] => (item=host1) => {
    "msg": [
        "foobar and more at host1",
        "foobar and more at host2"
    ]
}
ok: [host2] => (item=host2) => {
    "msg": [
        "foobar and more at host1",
        "foobar and more at host2"
    ]
}
```

##### ACTUAL RESULTS

```paste below
TASK [mapped var loop - ugh!] *********
ok: [host1] => (item=host1) => {
    "msg": "[AnsibleUndefined, AnsibleUndefined]"
}
ok: [host2] => (item=host1) => {
    "msg": "[AnsibleUndefined, AnsibleUndefined]"
}
ok: [host1] => (item=host2) => {
    "msg": "[AnsibleUndefined, AnsibleUndefined]"
}
ok: [host2] => (item=host2) => {
    "msg": "[AnsibleUndefined, AnsibleUndefined]"
}

```

##### WORKAROUND
More or less pretty simple when you know which vars you need. All you have to do is "promote" them to facts and force to be eager evaluated. This sometimes cannot be done in pre_tasks if mapped vars depends on vars that do not yet exists or will be changed during run.
```yaml
  pre_tasks:
    - set_fact:
        all_whatever: "{{ all_whatever }}"
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shrews** [comment]
I've been able to confirm this issue. It seems when the extract filter is run for the map() call within the groups_vars file, the 'hostvars' value is 'AnsibleUndefined'. If I put the same variable value within the playbook, it works as expected since hostvars has a value.

test.yml

```
---
- hosts: test_group
  gather_facts: false
  tasks:

    - name: Test A
      debug:
        msg: "localhost test_var2 is {{ hostvars['localhost']['test_var2'] }}"

    - name: Test B
      debug:
        msg: "{{ groups['test_group'] | map('extract', hostvars, 'test_var1') | list }}"
```

group_vars/test_group.yml

```
test_var1: "foo"
test_var2: "{{ groups['test_group'] | map('extract', hostvars, 'test_var1') | list }}"
```

hosts.yml

```
all:
   children:
      test_group:
        hosts:
          localhost:
            ansible_connection: local
            ansible_python_interpreter: "{{ ansible_playbook_python }}"
```

ansible-playbook test.yml -i ./hosts.yaml

```
PLAY [test_group] ****************************************************************************************************************************************************

TASK [Test A] ********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "localhost test_var2 is [AnsibleUndefined]"
}

TASK [Test B] ********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "foo"
    ]
}
```
