### ISSUE TITLE
rhn_channel module HTTPS insecure mode

### ISSUE THREAD

**Issue by yakhatape** [ansible/ansible#68374]
##### SUMMARY
I'm trying to use the rhn_channel module to improve our automation but we are using an private CA. I want to know if its possible to add a insecure parameter [true, false] for exemple to be able to use it w/o certificat problem.

##### ISSUE TYPE
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unable to establish session with Satellite server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) "}

##### COMPONENT NAME
rhn_channel

##### ANSIBLE VERSION
```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  python version = 3.6.8 (default, Feb 15 2019, 01:54:23) [GCC 7.4.0]
```

##### OS / ENVIRONMENT
Target OS - centos7

##### STEPS TO REPRODUCE
use module rhn _channel with a RHN Satellite HTTPS certificate not valid
```
- name: "register host to XXXX repository"
  rhn_channel: 
    name: XXXXXX.x-x86_64
    sysname: "{{ vmname }}"
    url: "{{ url }}"
    user: "{{ login }}"
    password: "{{ password }}"
  delegate_to: localhost

```

##### EXPECTED RESULTS
Module didn't check the certificate during api calls

##### ACTUAL RESULTS

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unable to establish session with Satellite server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) "}
```

Thanks for your help ! :)
