### ISSUE TITLE
hostname: Module is unable to set the hostname in centos 6 

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#68390]
##### SUMMARY
Unable to set hostname using hostname module in centos6.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- hostname

##### ANSIBLE VERSION
```
# pip show ansible
Name: ansible
Version: 2.9.6
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python2.7/dist-packages
Requires: jinja2, PyYAML, cryptography
```

##### OS / ENVIRONMENT
- Ubuntu 18.04.04 LTS based Provision Server

##### STEPS TO REPRODUCE
 - Main Playbook:

```
---
- name: VM deployment using ansible for demo
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vsphere_creds.yml
    - vsphere_vars.yml
  tasks:
    - name: Make the vm folder
      vcenter_folder:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: 'no'
        datacenter: '{{ vsphere_datacenter }}'
        folder_name: '{{ vsphere_folder }}'
        folder_type: vm
        state: present
      delegate_to: localhost

    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: '{{ vsphere_datacenter }}'
        cluster: '{{ vsphere_cluster }}'
        validate_certs: no
        folder: '{{ vsphere_folder }}'
        name: '{{ vsphere_vm_name }}'
        state: poweredon
        template: uskar-centos6-demo-temp
        disk:
        - size_gb: 15
          type: thin
          autoselect_datastore: yes
        networks:
        - name: "{{ Management_network }}"
          ip: "{{ guest_ip }}"
          netmask: "{{ guest_netmask }}"
          gateway: "{{ guest_gateway }}"
          dns_servers: "{{ guest_dns }}"
          domain: "{{ guest_domain }}"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy

    - name: Set Hostname
      hostname:
        name: '{{ guest_hostname }}'
        use: 'redhat'
```

- Variable File:
```
# cat vsphere_vars.yml
# vCenter Specific Variable
vsphere_datacenter: 'xxxxxxxxxxx'
vsphere_folder: 'Ansible-Demo-uskar'
vsphere_cluster: 'xxxxxxxxxxx'
vsphere_vm_name: 'uskar-ansible-demo'

# Network Details
Management_network: 'VM Network'
guest_ip: 'xxxxxxxxxxx'
guest_netmask: 'xxxxxxxxxxx'
guest_gateway: 'xxxxxxxxxxx'
guest_dns: 'xxxxxxxxxxx'
guest_domain: 'xxxxxxxxxxx'
guest_hostname: 'webserver01'
```

##### EXPECTED RESULTS
It should set the hostname as 'webserver01'.

##### ACTUAL RESULTS
After deployment this is what I can see in the OS:

```
[root@uskar-ansible-demo ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

xxx.xxx.xxx.xxx   uskar-ansible-demo

[root@uskar-ansible-demo ~]# hostname
uskar-ansible-demo

[root@uskar-ansible-demo ~]# cat /etc/sysconfig/network
NETWORKING=yes
HOSTNAME=uskar-ansible-demo
GATEWAYDEV=eth0
GATEWAY=xxx.xxx.xxx.xxx

[root@uskar-ansible-demo ~]# cat /etc/sysconfig/network-scripts/ifcfg-eth0
# Generated by VMWare customization engine.
HWADDR=00:50:56:a6:3d:3f
NAME=eth0
GATEWAY=xxx.xxx.xxx.xxx
DEVICE=eth0
ONBOOT=yes
USERCTL=no
BOOTPROTO=static
NETMASK=xxx.xxx.xxx.xxx
IPADDR=xxx.xxx.xxx.xxx
PEERDNS=yes

check_link_down() {
 return 1;
}

[root@uskar-ansible-demo ~]# ls -l /etc/sysconfig/network
-rw-r--r--. 1 root root 79 Mar 22 12:20 /etc/sysconfig/network
```

- While running the playbook getting the below error:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_hostname_payload_I60GJ7/ansible_hostname_payload.zip/ansible/modules/system/hostname.py", line 286, in get_permanent_hostname
IOError: [Errno 2] No such file or directory: '/etc/sysconfig/network'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "name": "webserver01",
            "use": "redhat"
        }
    },
    "msg": "failed to read hostname: [Errno 2] No such file or directory: '/etc/sysconfig/network'"
}
```

```
# ansible-playbook  deploy_vm.yml --ask-vault
Vault password:

PLAY [VM deployment using ansible for demo] *****************************************************************************************************************************************************************************************************************************************************************************

TASK [Make the vm folder] ***********************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [Create a virtual machine from a template] *************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [Set Hostname] *****************************************************************************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/etc/sysconfig/network'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to read hostname: [Errno 2] No such file or directory: '/etc/sysconfig/network'"}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
