### ISSUE TITLE
ovirt_vm does not set cloud_init_persist properly

### ISSUE THREAD

**Issue by okamidash** [ansible/ansible#68397]
##### SUMMARY
When using the ovirt_vm module to create a virtual machine using cloud_init; it is not set properly, and when attempting to use the 'cloud_init_persist' boolean, it returns the message " The 'value' parameter must be a boolean"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ovirt_vm

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
  config file = /home/okami/code/ansible/infrastructure/ansible.cfg
  configured module search path = ['/home/okami/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/okami/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 26 2020, 22:21:03) [GCC 9.2.1 20200130]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/okami/code/ansible/infrastructure/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/okami/code/ansible/infrastructure/ansible.cfg) = ['profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/home/okami/code/ansible/infrastructure/ansible.cfg) = ['/home/okami/code/ansible/infrastructure/filter_plugins']
DEFAULT_HOST_LIST(/home/okami/code/ansible/infrastructure/ansible.cfg) = ['/home/okami/code/ansible/infrastructure/hosts.ini']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/okami/code/ansible/infrastructure/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/okami/code/ansible/infrastructure/ansible.cfg) = /home/okami/.ansible/tmp/ansible-local-397558xh8s4yvx
DEFAULT_ROLES_PATH(/home/okami/code/ansible/infrastructure/ansible.cfg) = ['/home/okami/code/ansible/infrastructure/roles']
DEFAULT_SCP_IF_SSH(/home/okami/code/ansible/infrastructure/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/okami/code/ansible/infrastructure/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/home/okami/code/ansible/infrastructure/ansible.cfg) = /home/okami/code/ansible/infrastructure/passkey
DEPRECATION_WARNINGS(/home/okami/code/ansible/infrastructure/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/okami/code/ansible/infrastructure/ansible.cfg) = False
HOST_KEY_CHECKING(/home/okami/code/ansible/infrastructure/ansible.cfg) = False
INTERPRETER_PYTHON(/home/okami/code/ansible/infrastructure/ansible.cfg) = auto_silent
PLAYBOOK_DIR(/home/okami/code/ansible/infrastructure/ansible.cfg) = /home/okami/code/ansible/infrastructure/playbooks
```

##### OS / ENVIRONMENT

Arch Linux (ansible host)
ovirt node 4.3.8 (target)

##### STEPS TO REPRODUCE

```yaml
---
- name: "Create ovirt VM and modify template"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: present
    name: "cloud-00"
    cpu_cores: 8
    template: "default_template"
    cluster: "default"
    type: "server"
    operating_system: "other_linux"
    serial_console: "yes"
    cloud_init:
      user_name: "root"
      root_password: "{{ ovirt_template_password }}"
      host_name: "cloud-00"
    cloud_init_persist: True
    nics:
      - interface: "virtio"
        name: "cloud-00"
        profile_name: "{{ ovirt_nic_network }}"

- name: "Start ovirt VM"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: "running"
    name: "cloud-00"
```

##### EXPECTED RESULTS

Task completes successfully and cloud-init is applied.

##### ACTUAL RESULTS

```paste below
TASK [virt/ovirt/modify_template : Start ovirt VM] *****************************************************************
task path: /home/okami/code/ansible/infrastructure/roles/virt/ovirt/modify_template/tasks/setup.yml:37
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ovirt_vm_payload_ptrknfk_/ansible_ovirt_vm_payload.zip/ansible/modules/cloud/ovirt/ovirt_vm.py"
  File "/tmp/ansible_ovirt_vm_payload_ptrknfk_/ansible_ovirt_vm_payload.zip/ansible/module_utils/ovirt.py", line 774
    getattr(entity_service, action)(**kwargs)
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/services.py", line 31406, in start
    return self._internal_action(action, 'start', None, headers, query, wait)
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/service.py", line 287, in _internal_action
    request.body = writer.Writer.write(action, indent=True)
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writer.py", line 189, in write
    writer(obj, cursor, root)
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writers.py", line 207, in write_one
    VmWriter.write_one(obj.vm, writer, 'vm')
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writers.py", line 9923, in write_one
    InitializationWriter.write_one(obj.initialization, writer, 'initialization')
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writers.py", line 4594, in write_one
    NicConfigurationWriter.write_many(obj.nic_configurations, writer, 'nic_configuration', 'nic_configurations')
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writers.py", line 6036, in write_many
    NicConfigurationWriter.write_one(obj, writer, singular)
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writers.py", line 6021, in write_one
    Writer.write_boolean(writer, 'on_boot', obj.on_boot)
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writer.py", line 61, in write_boolean
    return writer.write_element(name, Writer.render_boolean(value))
  File "/usr/lib/python3.8/site-packages/ovirtsdk4/writer.py", line 53, in render_boolean
    raise TypeError('The \'value\' parameter must be a boolean')
TypeError: The 'value' parameter must be a boolean
fatal: [localhost]: FAILED! => changed=false
  invocation:
    module_args:
      affinity_group_mappings: []
      affinity_label_mappings: []
      allow_partial_import: null
      ballooning_enabled: null
      boot_devices: null
      boot_menu: null
      cd_iso: null
      clone: false
      clone_permissions: false
      cloud_init:
        host_name: cloud-00
        root_password: dfsdifsdjfdsjfk
        user_name: root
      cloud_init_nics: []
      cloud_init_persist: false
      cluster: null
      cluster_mappings: []
      comment: null
      cpu_cores: null
      cpu_mode: null
      cpu_pinning: null
      cpu_shares: null
      cpu_sockets: null
      cpu_threads: null
      custom_compatibility_version: null
      custom_emulated_machine: null
      custom_properties: null
      delete_protected: null
      description: null
      disk_format: cow
      disks: []
      domain_mappings: []
      exclusive: null
      export_domain: null
      export_ova: null
      fetch_nested: false
      force: false
      force_migrate: null
      graphical_console: null
      high_availability: null
      high_availability_priority: null
      host: null
      host_devices: null
      id: null
      initrd_path: null
      instance_type: null
      io_threads: null
      kernel_params: null
      kernel_params_persist: false
      kernel_params_persist: false
      kernel_path: null
      kvm: null
      lease: null
      lun_mappings: []
      memory: null
      memory_guaranteed: null
      memory_max: null
      migrate: null
      name: cloud-00
      nested_attributes: []
      next_run: null
      nics: []
      numa_nodes: []
      numa_tune_mode: null
      operating_system: null
      placement_policy: null
      poll_interval: 3
      quota_id: null
      reassign_bad_macs: null
      rng_device: null
      role_mappings: []
      serial_console: null
      serial_policy: null
      serial_policy_value: null
      smartcard_enabled: null
      snapshot_name: null
      snapshot_vm: null
      soundcard_enabled: null
      sso: null
      state: running
      stateless: null
      storage_domain: null
      sysprep: null
      template: null
      template_version: null
      ticket: null
      timeout: 180
      timezone: null
      type: null
      usb_support: null
      use_latest_template_version: null
      vmware: null
      vnic_profile_mappings: []
      wait: true
      watchdog: null
      xen: null
  msg: The 'value' parameter must be a boolean

PLAY RECAP *********************************************************************************************************
localhost                  : ok=7    changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

```

**Comment by okamidash** [comment]
I have attempted to use "True", "yes", "true" for the value of `cloud_init_persist`

**Comment by ansibot** [comment]
cc @machacekondra @mnecas @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by okamidash** [comment]
This issue additionally persists within the following [collection](https://galaxy.ansible.com/ovirt/ovirt_collection)

**Comment by mnecas** [comment]
Hi @okamidash,
I was not able to reproduce the issue. This might be SDK issue but will need to do more investigation.

Was it working without `cloud_init_persist`?
Try to run it without putting VM to state running and then try from UI.

I noticed that it failed in `NicConfigurationWriter` but you empty nics (`nics: []`) so it's little bit strange.

**Comment by okamidash** [comment]
It wasn't working without cloud_init_persist. 
It doesn't appear to be able to modify the cloud-init settings at all, upon closer inspection.

I attempted to create the VM without any cloud-init configuration options, and attempted to set it _after_ the vm was created (but not running); with the same result. 

I've managed to come to a workaround and instead use the API after the vm is created; and send the cloud-init stuff through that.

I'm currently using the sdk version 4.3.0-3.

**Comment by mnecas** [comment]
Just tested your version of SDK and again went without a problem.
Try to add to the task which runs the vm `cloud_init_persist: True`.

Found similar error here https://github.com/ansible/ansible/issues/32670.

**Comment by okamidash** [comment]
```yaml
---
- set_fact: vm_network="{{ networks[ovirt_nic_network].gateway | ipv4('host/prefix') }}"
- name: "Create ovirt VM and modify template"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: present
    name: "cloud-00"
    cpu_cores: 8
    template: "{{ ovirt_base_template_name }}"
    cluster: "{{ ovirt_cluster_name }}"
    type: "server"
    operating_system: "other_linux"
    serial_console: "yes"
    nics:
      - interface: "virtio"
        name: "cloud-00"
        profile_name: "{{ ovirt_nic_network }}"

- name: "Start ovirt VM"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cloud_init:
     root_password: "helloworld"
     host_name: "cloud_test"
    cloud_init_persist: True
    state: "running"
    name: "cloud-00"
```

You are a star. This looks like it works! Thank you.
