### ISSUE TITLE
Unsupported parameters for (vmware_guest_boot_manager) module: boot_firmware, secure_boot_enabled

### ISSUE THREAD

**Issue by tanguy-legressus** [ansible/ansible#68401]
##### SUMMARY
Trying to add some features for Windows deployment, with the module "vmware_guest_boot_manager". Following the docs https://docs.ansible.com/ansible/latest/modules/vmware_guest_boot_manager_module.html.
Want to boot windows on EFI and with boot secure enabled.

Even if parameters are listed in the documentation, they seem to not be found/working while playing them.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_boot_manager
  secure_boot_enabled

##### ANSIBLE VERSION
Ansible 2.9.2

##### CONFIGURATION
Jenkins cent 7_X
version 2.204.5

##### OS / ENVIRONMENT
Target OS versions:
Windows 10_1809
Windows 10_1903

##### STEPS TO REPRODUCE

```yaml
- name: create a vm 
  block:

    - name: "vSphere actions | Create VM: {{ machine }} on {{ vm_CRUD_hostname }}"
      vmware_guest:
        hostname: "{{ vm_hostname }}"
        username: "{{ vm_username }}"
        password: "{{ vm_password }}"
        annotation: "{{ vm_initial_notes }}"
        datacenter: "{{ vm_esxi_datacenter }}"
        cluster: "{{ vm_cluster }}"
        resource_pool: "{{ vm_resource_pool }}"
        validate_certs: no
        folder: "{{ vm_extra_config_folder }}"
        name: "{{ machine }}"
        state: "{{ power_state | default('poweredoff') }}"
        template: "{{ vm_template_src | default(omit) }}"
        guest_id: "{{ vm_hardware_osid }}"
        disk: "{{ vm_vmware.disk|list if vm_template_src == '' else omit }}"
        hardware:
          memory_mb: "{{ vm_hardware_memory_mb if vm_template_src == '' else omit }}"
          num_cpus: "{{ vm_hardware_num_cpus if vm_template_src == '' else omit }}"
          num_cpu_cores_per_socket: "{{ vm_hardware_num_cpu_cores_per_socket|int|abs if vm_template_src == '' else omit }}"
          scsi: "{{ vm_hardware_scsi if vm_template_src == '' else omit }}"
          boot_firmware: efi
          nested_virt: yes
        networks:
        - name: "{{ vm_network }}"
          # start_connected: True
          # allow_guest_control: True
          # device_type: "{{ vm_type }}"
          # type: "{{ vm_type }}"
          # ip: "{{ vm_ip | default(omit) }}"
          # netmask: "{{ vm_netmask | default(omit) }}"
          # gateway: "{{ vm_gateway | default(omit) }}"
        # wait for address only when creating from template
        # customization:
        #     domain: "{{ vm_domain }}"
        #     hostname: "{{ machine }}"
        #     dns_servers: "{{ vm_dns_servers }}"
        wait_for_ip_address: no
      delegate_to: localhost
      register: vmware_result
      tags: vmware_host_create
  
    - name: Enable UEFI SecureBoot for {{ machine }}
      vmware_guest_boot_manager:
        hostname: "{{ vm_hostname }}"
        username: "{{ vm_username }}"
        password: "{{ vm_password }}"
        validate_certs: no
        uuid: "{{ vmware_result.instance.hw_product_uuid }}"
        boot_firmware: efi
        secure_boot_enabled: true
      delegate_to: localhost
      register: vm_uefi_boot
      tags: vmware_host_create

  # register: vmware_result
  tags: vmware_host_create
```

With defaults values:

vm_secure_boot: true

##### ACTUAL RESULTS

Jenkins log error:

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "boot_firmware": "efi", 
            "hostname": "hostname", 
            "password": "password", 
            "secure_boot_enabled": true, 
            "username": "username", 
            "uuid": "uuid", 
            "validate_certs": false
        }
    }, 
    "msg": "Unsupported parameters for (vmware_guest_boot_manager) module: boot_firmware, secure_boot_enabled Supported parameters include: boot_delay, boot_order, boot_retry_delay, boot_retry_enabled, enter_bios_setup, hostname, name, name_match, password, port, proxy_host, proxy_port, username, uuid, validate_certs"
}

```
