### ISSUE TITLE
uri module set string with masked content into content and json output

### ISSUE THREAD

**Issue by hungluong5791** [ansible/ansible#68400]
##### SUMMARY
uri module set string with masked content into content and json output

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = None
  configured module search path = ['/Users/hungluong/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/hungluong/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Users/hungluong/Library/Python/3.7/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below
N/A
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: send request
      uri:
        url: "https://postman-echo.com/get?name=something-with-admin"
        user: admin
        password: admin
        method: GET
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: response
    
    - name: extract value
      vars:
        query: args.name
      set_fact:
        value_content: "{{ response.content }}"
        value_content_parsed: "{{ response.content | from_json | json_query(query) }}"
        value_json: "{{ response.json.args.name }}"

    - name: debug
      debug:
        msg:
          - "{{ 'something-with-admin' in value_json }}"
          - "{{ 'something-with-admin' in value_content }}"
          - "{{ 'something-with-admin' in value_content_parsed }}"
          - "{{ 'something-with-********' in value_json }}"
          - "{{ 'something-with-********' in value_content }}"
          - "{{ 'something-with-********' in value_content_parsed }}"
```

##### EXPECTED RESULTS
The module should return the json/content value with the correct values

##### ACTUAL RESULTS

The module seems to apply sensitive info masking ('********') to value matching username/password in its output

```paste below
"msg": [
        false,
        false,
        false,
        true,
        false,
        true
    ]
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/net_tools/basics/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/uri.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
Actually we should be masking the non json keys also.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rubber-side-down** [comment]
> Actually we should be masking the non json keys also.

It's masking the non-json (response.content) value as well. Adding the facts to the debug msg confirms this:
```yaml
- hosts: localhost
  connection: local
  tasks:
    - name: send request
      uri:
        url: "https://postman-echo.com/get?name=something-with-admin"
        user: admin
        password: admin
        method: GET
        force_basic_auth: yes
        return_content: yes
        status_code: 200
      register: response

    - name: extract value
      vars:
        query: args.name
      set_fact:
        value_json: "{{ response.json.args.name }}"
        value_content: "{{ response.content }}"
        value_content_parsed: "{{ response.content | from_json | json_query (query) }}"

    - name: debug
      debug:
        msg:
          - "{{ value_json }}"
          - "{{ value_content }}"
          - "{{ value_content_parsed }}"
          - "{{ 'something-with-admin' in value_json }}"
          - "{{ 'something-with-admin' in value_content }}"
          - "{{ 'something-with-admin' in value_content_parsed }}"
          - "{{ 'something-with-********' in value_json }}"
          - "{{ 'something-with-********' in value_content }}"
          - "{{ 'something-with-********' in value_content_parsed }}"
```
```
ok: [localhost] => {
    "msg": [
        "something-with-********",
        {
            "args": {
                "name": "something-with-********"
            },
            "headers": {
                "accept-encoding": "identity",
                "authorization": "Basic YWRtaW46YWRtaW4=",
                "host": "postman-echo.com",
                "user-agent": "ansible-httpget",
                "x-amzn-trace-id": "Root=1-5ec4de30-6007601b0412140ca002d5eb",
                "x-forwarded-port": "443",
                "x-forwarded-proto": "https"
            },
            "url": "https://postman-echo.com/get?name=something-with-********"
        },
        "something-with-********",
        false,
        false,
        false,
        true,
        false,
        true
    ]
}
```
`'something-with-********' in value_content` returns `False` because the test is incorrect. It tests whether something-with-******** is a key in value_content rather than whether the string exists in the content. Changing the test to `'something-with-********' in value_content.__str__()` returns `True`.

@bcoca, is there work to do here? It sounds like the request is to stop masking the values, but your comment indicates that these values should be masked.

**Comment by hungluong5791** [comment]
> It tests whether something-with-******** is a key in value_content rather than whether the string exists in the content

@rubber-side-down Why is that the case? The module example seems to indicate that it is just a string:
```
- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
  uri:
    url: http://www.example.com
    return_content: yes
  register: this
  failed_when: "'AWESOME' not in this.content"
```
