### ISSUE TITLE
ucs_vnic_template not able to create vnic template under an existing org

### ISSUE THREAD

**Issue by sathiarajah** [ansible/ansible#68428]
##### SUMMARY
We are facing an issue whereby we are not able to create a vnic template under a org, e.g org-root/org-ucsmdndb.

Based on the error description, I am not sure why "lan-conn-templ" is appended to vNIC-A and it is not found.
"msg": "setup error: [ErrorCode]: 102[ErrorDescription]: configured object (org-root/org-ucsmdndb/lan-conn-templ-vNIC-A) not found "

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/remote_management/ucs/ucs_vnic_template.py

##### ANSIBLE VERSION

```
ansible 2.8.0
```

##### CONFIGURATION

```
(ansible) [root@anstvwells02 admin]# ansible-config dump --only-changed
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
```

##### OS / ENVIRONMENT

ucs manager system - 3.1(3g)
ucs manager service pack - 3.1(3)SP0

##### STEPS TO REPRODUCE

Execute the playbook below using the vars_file as the input

```yaml
- name: "Create update delete vnic template"
  ignore_errors: True
  ucs_vnic_template:
    hostname: "{{ansible_host}}"
    username: "{{username}}"
    password: "{{password}}"
    name: "{{ucs_vnic_item.name}}"
    fabric: "{{ucs_vnic_item.fabric}}"
    state: "{{ucs_vnic_item.state}}"
    template_type: "{{ucs_vnic_item.template_type}}"
    org_dn: "{{ucs_vnic_item.org_dn}}"

ucs_vnic_template:
- name: vNIC-A
  state: present
  fabric: A
  org_dn: "org-root/org-ucsmdndb"
  template_type: 'updating-template'

```

##### EXPECTED RESULTS

The vnic template to be created successfully under the defined org_dn param

##### ACTUAL RESULTS

```
{
 "exception": "WARNING: The below traceback may not be related to the actual failure.\n File "/tmp/ansible_ucs_vnic_template_payload_KBk9Rc/main.py", line 363, in main\n ucs.login_handle.commit()\n File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/ucsmsdk/ucshandle.py", line 942, in commit\n raise UcsException(response.error_code, response.error_descr)\n",
 "_ansible_no_log": false,
 "changed": false,
 "invocation": {
 "module_args": {
 "username": "ucs-local\admin",
 "redundancy_type": "none",
 "cdn_name": "",
 "stats_policy": "default",
 "network_control_policy": "",
 "proxy": null,
 "cdn_source": "vnic-name",
 "use_ssl": true,
 "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
 "port": null,
 "peer_redundancy_template": "",
 "use_proxy": true,
 "vlans_list": null,
 "fabric": "A",
 "description": "",
 "hostname": "10.173.253.72",
 "org_dn": "org-root/org-ucsmdndb",
 "name": "vNIC-A",
 "template_type": "updating-template",
 "state": "present",
 "mac_pool": "",
 "target": "adaptor",
 "pin_group": "",
 "mtu": "1500",
 "qos_policy": ""
 }
 },
 "msg": "setup error: [ErrorCode]: 102[ErrorDescription]: configured object (org-root/org-ucsmdndb/lan-conn-templ-vNIC-A) not found "
 }
```
