### ISSUE TITLE
vmware_guest not setting boot firmware

### ISSUE THREAD

**Issue by rolling1000ton** [ansible/ansible#68424]
##### SUMMARY

The vmware_guest module doesn't set the boot firmware to EFI when VM is created from template or when the boot firmware is set to EFI after the creation of the VM. If the VM is created without a template the boot firmware is set just fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /home/user/ansible-store/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION

```
DEFAULT_ACTION_PLUGIN_PATH(/home/user/ansible-store/ansible.cfg) = ['/usr/local/lib/python3.6/dist-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/user/ansible-store/ansible.cfg) = ['/usr/local/lib/python3.6/dist-packages/ara/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/home/user/ansible-store/ansible.cfg) = ['slack']
DEFAULT_HOST_LIST(/home/user/ansible-store/ansible.cfg) = ['/home/user/ansible-store/inventory']
DEFAULT_JINJA2_EXTENSIONS(/home/user/ansible-store/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/user/ansible-store/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/user/ansible-store/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/home/user/ansible-store/ansible.cfg) = ['/home/user/ansible-store/roles']
DEFAULT_TIMEOUT(/home/user/ansible-store/ansible.cfg) = 300
DEFAULT_VAULT_PASSWORD_FILE(/home/user/ansible-store/ansible.cfg) = /etc/ansible/.vault_pass
HOST_KEY_CHECKING(/home/user/ansible-store/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/ansible-store/ansible.cfg) = auto
INVENTORY_IGNORE_EXTS(/home/user/ansible-store/ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.ini', '.cfg', '.retry', '.py']
RETRY_FILES_ENABLED(/home/user/ansible-store/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ansible Host: Ubuntu 18.04.4 LTS
Client: VMWare ESXi 6.7

##### STEPS TO REPRODUCE

```
    - name: create vm
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: /folder/vm
        cluster: cluster
        datacenter: DC
        name: "{{ vmname }}"
        state: poweredoff
        template: vmtemplate
        hardware:
          boot_firmware: efi
        networks:
        - name: NETWORK
          mac: "{{ macaddress[0] }}"

    - name: set boot firmware efi
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ vmname }}"
        hardware:
          boot_firmware: efi
```

##### EXPECTED RESULTS

Boot Firmware set to EFI in VMWare

##### ACTUAL RESULTS

Boot Firmware stays BIOS in VMWare
