### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by ColFouks** [ansible/ansible#68423]
##### SUMMARY
The gcp dynamic inventory fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_compute

##### ANSIBLE VERSION

```ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/anatolii_kaliuzhnyi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['gcp_compute']
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.7 (Maipo)

##### STEPS TO REPRODUCE
Enable gcp_compute plugin in the inventory section of ansible.cfg:

[inventory]
enable_plugins = gcp_compute
Make inventory.gcp.yml file:
```
plugin: gcp_compute
projects:
  - test-project-124
keyed_groups:
  - prefix: gcp
    key: project
auth_kind: serviceaccount
service_account_file: key.json
```
Try to create graph of inventories:

ansible-inventory -i inventory.gcp.yml --graph

##### EXPECTED RESULTS
Graph of inventories

##### ACTUAL RESULTS

```[WARNING]:  * Failed to parse inventory.gcp.yml with gcp_compute plugin: 'NoneType' object has no attribute 'get'

[WARNING]: Unable to parse inventory.gcp.yml as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

@all:
  |--@ungrouped:
```
