### ISSUE TITLE
vmware_vm_shell does not successfully run nmcli commands

### ISSUE THREAD

**Issue by kobaltfox** [ansible/ansible#68437]
##### SUMMARY
In a playbook to clone a VM guest, the final task is to use vmware_vm_shell to run three commands to update the DNS, add search domain, take down the interface and then bring it back up to allow NetworkManager to update resolv.conf. The command work fine directing on the target VM guest. However, then the task runs, no failures are returned, but no changes are made to the guest.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_vm_shell

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tjwork/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION
```
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/inventory']
```

##### OS / ENVIRONMENT

Target guest is RHEL 8

##### STEPS TO REPRODUCE

Adding the tasks to a playbook role. This is run using Ansible Tower.

```yaml
# Fix network confiruration - DNS
- name: Add DNS to network interface
  vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ datacenter_name }}"
    folder: "/LinuxAdmin/ansible_RHv7/"
    vm_id: "{{ env_name }}"
    vm_username: 'root'
    vm_password: 'supersecretpassword'
    vm_shell: "/bin/bash"
    vm_shell_args: "nmcli con mod 'ens192' ipv4.dns '192.168.10.12 192.168.10.15'"
    vm_shell_env:
      - "PATH=/bin/bash"
    vm_shell_cwd: "/root"
    validate_certs: False
  register: shell_command_dns
  tags:
    - dns_refreash

# Pause for 30 seconds to allow command to execute
- pause:
    seconds: 30
  tags:
    - dns_refreash

  # Fix network configuration - Search Domain
- name: Add search domain to network interface
  vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ datacenter_name }}"
    folder: "/LinuxAdmin/ansible_RHv7/"
    vm_id: "{{ env_name }}"
    vm_username: 'root'
    vm_password: 'supersecretpassword'
    vm_shell: "/bin/bash"
    vm_shell_args: "nmcli con mod 'ens192' ipv4.dns-search 'domain.com'"
    vm_shell_env:
      - "PATH=/bin/bash"
    vm_shell_cwd: "/root"
    validate_certs: False
  register: shell_command_search
  tags:
    - dns_refreash

# Pause for 30 seconds to allow command to execute
- pause:
    seconds: 30
  tags:
    - dns_refreash

  # Fix network configuration - shut down interface
- name: Add search domain to network interface
  vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ datacenter_name }}"
    folder: "/LinuxAdmin/ansible_RHv7/"
    vm_id: "{{ env_name }}"
    vm_username: 'root'
    vm_password: 'supersecretpassword'
    vm_shell: "/bin/bash"
    vm_shell_args: "nmcli con down 'ens192'"
    vm_shell_env:
      - "PATH=/bin/bash"
    vm_shell_cwd: "/root"
    validate_certs: False
  register: shell_command_down
  tags:
    - dns_refreash

# Pause for 30 seconds to allow command to execute
- pause:
    seconds: 30
  tags:
    - dns_refreash

# Fix network configuration - power up interface
- name: Add search domain to network interface
  vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: "{{ datacenter_name }}"
    folder: "/LinuxAdmin/ansible_RHv7/"
    vm_id: "{{ env_name }}"
    vm_username: 'root'
    vm_password: 'supersecretpassword'
    vm_shell: "/bin/bash"
    vm_shell_args: "nmcli con up 'ens192'"
    vm_shell_env:
      - "PATH=/bin/bash"
    vm_shell_cwd: "/root"
    validate_certs: False
  register: shell_command_up
  tags:
    - dns_refreash
```

##### EXPECTED RESULTS

After running the tasks the resolv.conf should contain the search domain and nameservers

##### ACTUAL RESULTS

The resolve.conf is empty

```
SSH password: 
Vault password: 
PLAY [all] *********************************************************************
TASK [install_rhelvm : set_fact] ***********************************************
ok: [192.168.22.29]
TASK [install_rhelvm : Get VM "server-an11" uuid] ******************************
ok: [192.168.22.29]
TASK [install_rhelvm : Add DNS to network interface] ***************************
changed: [192.168.22.29]
TASK [install_rhelvm : pause] **************************************************
Pausing for 30 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [192.168.22.29]
TASK [install_rhelvm : Add search domain to network interface] *****************
changed: [192.168.22.29]
TASK [install_rhelvm : pause] **************************************************
Pausing for 30 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [192.168.22.29]
TASK [install_rhelvm : Add search domain to network interface] *****************
changed: [192.168.22.29]
TASK [install_rhelvm : pause] **************************************************
Pausing for 30 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [192.168.22.29]
TASK [install_rhelvm : Add search domain to network interface] *****************
changed: [192.168.22.29]
PLAY RECAP *********************************************************************
192.168.22.29               : ok=9    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
