### ISSUE TITLE
ios L3 IPv4 address loopback interface

### ISSUE THREAD

**Issue by maxrainer** [ansible/ansible#68430]
##### SUMMARY
IOS L3 Interfaces Module not working with loopback interfaces. 
Not possible to set IPv4 Address on Loopback Interface.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_l3_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/mrainer/Documents/dev/ansible/labs/ansible.cfg
  configured module search path = ['/Users/mrainer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mrainer/venv/network/lib/python3.7/site-packages/ansible
  executable location = /Users/mrainer/venv/network/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below
- name: Interface IPv4 Addresses
  ios_l3_interfaces: 
    config: 
      - name: "{{ item.name }}"
        ipv4: 
        - address: "{{ item.ipv4.address }}"
    state: merged
  loop: "{{ interface_config }}"
  notify: save config
  tags: [always, config]
```

##### OS / ENVIRONMENT

different Cisco IOS versions tested
p.e: Cisco IOS XE Software, Version 17.01.01

##### STEPS TO REPRODUCE

IPv4 address on loopback interface is never set 
status is always OK
config "ip address" is always untouched
no matter the subnet is /30 or /32 or /24
also changing the IP address after first deployment, never changes the ansible status or the config on device

```yaml
interface_config:
    - name: GigabitEthernet2
      ipv4:
        address: 172.16.1.100/25
      description: WAN interface
      enabled: True
    
    - name: GigabitEthernet3
      ipv4:
        address: 172.16.2.100/24
      description: headquarter LAN 
      enabled: True
    
    - name: Loopback1
      ipv4: 
        address: 9.9.9.9/32
      description: loopback 1
      enabled: True
```

##### EXPECTED RESULTS

IP address on loopback1 should be set

##### ACTUAL RESULTS

IPv4 address is not set ("no ip address" on device)

```paste below

```
