### ISSUE TITLE
ansible task gets failed for some hosts devices errors='surrogate_then_replace' module ios_command

### ISSUE THREAD

**Issue by fernandomullerjr** [ansible/ansible#68454]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION

```
[root@poadtcsrv06 ~]# ansible --version
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[root@poadtcsrv06 ~]#
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.7.1908 (Core)
[root@poadtcsrv06 ~]# uname -a
Linux poadtcsrv06.corp 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@poadtcsrv06 ~]#

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ccr:cio:gub:mgo:tes
  connection: local
  gather_facts: yes

  tasks:
  - name: OBTER CREDENCIAIS DE LOGIN
    include_vars: secret.yaml

  - name: PREENCHER AS VARIAVEIS
    set_fact:
      provider:
        host: "{{ ansible_host }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: Pegar a versao do equipamento
    ios_command:
     provider: "{{ provider }}"
     commands:
        - display version
    register: show_versionoltma5800

  - name: Rodar comandos para equipamentos olt-1
    ios_command:
     authorize: yes
     provider: "{{ provider }}"
     commands:
        - scroll
    when:
        - "'MA5' in show_versionoltma5800.stdout[0]"

  - name: Rodar Comandos para equipamentos olt-2
    ios_command:
     authorize: yes
     provider: "{{ provider }}"
     commands:
        - display current-configuration
    register: backupoltma5800
    when:
        - "'MA5' in show_versionoltma5800.stdout[0]"

  - set_fact:
     backupequipamentos: '{{ backupoltma5800 }}'
    when: backupoltma5800 is not skipped

  - name: Criacao de diretorio de exemplo no Ansible
    file:
      path: /tmp/rotinabkp/{{ group_names }}
      state: directory

  - name: Checar se o arquivo já existe
    stat:
      path: /tmp/rotinabkp/{{ group_names }}/{{ inventory_hostname }}_{{ ansible_date_time.day }}{{ ansible_date_time.month }}{{ ansible_date_time.year }}.txt
    register: result_file

  - name: Salvar a saída dos backups dos equipamentos
    copy:
      content: "Backup do Equipamento {{ inventory_hostname }} - CRIADO POR Fernando Müller DATACENTER POA - \n {{ backupequipamentos.stdout[0] }}  \n "
      dest: "/tmp/rotinabkp/{{ group_names }}/{{ inventory_hostname }}_{{ ansible_date_time.day }}{{ ansible_date_time.month }}{{ ansible_date_time.year }}.txt"
    when: result_file.stat.exists == False

  - debug: var=show_versionoltma5800.stdout_lines
```

##### EXPECTED RESULTS

all changed

##### ACTUAL RESULTS

PLAY RECAP *********************************************************************
CCRCNTOLT01                : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
CIOCTROLT01                : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
CIOCTROLT03                : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
GUBCNTOLT01                : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
GUBVLIOLT01                : ok=11   changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
MGOCTROLT01                : ok=11   changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
TESCALOLT01                : ok=11   changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
TESCTROLT01                : ok=11   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[root@poadtcsrv06 ansible]#

```paste below

```
