### ISSUE TITLE
gcp_compute_disk fails with family images usage.

### ISSUE THREAD

**Issue by Maunty** [ansible/ansible#68455]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_disk
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ./env/lib/python3.8/site-packages/ansible
  executable location = ./env/bin/ansible
  python version = 3.8.2 (default, Feb 26 2020, 15:17:37) [GCC 9.2.0
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
```

##### STEPS TO REPRODUCE

```yaml
        - name: create a disk
          gcp_compute_disk:
            name: '{{ hostname }}-boot-disk'
            size_gb: "{{ disk_size }}"
            source_image: 'family/centos-7'
            zone: "{{ zone }}"
            project: "{{ project_id }}"
            auth_kind: serviceaccount
            service_account_file: "{{ credentials_file }}"
            state: present
            scopes:
                    - https://www.googleapis.com/auth/compute
          register: boot_disk
```

##### EXPECTED RESULTS

Created disk from latest debian-8 image

##### ACTUAL RESULTS

```paste below
msg: 'GCP returned error: {''error'': {''errors'': [{''domain'': ''global'', ''reason'': ''invalid'', ''message'': "Invalid value for field ''resource.sourceImage'': ''family/debian-9''. The URL is malformed."}], ''code'': 400, ''message'': "Invalid value for field ''resource.sourceImage'': ''family/debian-9''. The URL is malformed."}}'

```
