### ISSUE TITLE
Ansible 2.9.6 on localhost fails with: failed to find the executable specified sh. Please verify if the executable exists and re-try

### ISSUE THREAD

**Issue by renepardon** [ansible/ansible#68453]
##### SUMMARY

After updating my Ansible and Python to latest versions on Mac OS Catalina, I receive this strange error when executing my playbook:

> fatal: [127.0.0.1]: FAILED! => {"msg": "failed to find the executable specified sh. Please verify if the executable exists and re-try."}

Changing the`ansible.cfg` file to contain **bash** instead of **sh** doesn't work either. Removing the *executable* setting at all works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- pre_task
-- package

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/renepardon/Projects/***/installer/ansible.cfg
  configured module search path = ['/Users/renepardon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 24 2020, 14:20:20) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/renepardon/Projects/***/installer/ansible.cfg) = ['profile_tasks']
DEFAULT_EXECUTABLE(/Users/renepardon/Projects/***/installer/ansible.cfg) = sh
DEFAULT_GATHERING(/Users/renepardon/Projects/***/installer/ansible.cfg) = smart
DEFAULT_REMOTE_USER(/Users/renepardon/Projects/***/installer/ansible.cfg) = vagrant
DEFAULT_TRANSPORT(/Users/renepardon/Projects/***/installer/ansible.cfg) = local
HOST_KEY_CHECKING(/Users/renepardon/Projects/***/installer/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/renepardon/Projects/***/installer/ansible.cfg) = True
```

##### OS / ENVIRONMENT

- Mac OS Catalina 10.15.1 (19B88)

##### STEPS TO REPRODUCE

```bash
ansible-playbook setup.yml --ask-become-pass --extra-vars "namespace=dev"
```

```yaml
---
- hosts: 127.0.0.1
  connection: local
  become: no
  gather_facts: no
  pre_tasks:
    - name: Ensure Python and libgit2 are installed
      package:
        name:
          - python
          - libgit2
          - kubernetes-helm
        state: present

    - name: Ensure pyhelm is installed
      pip:
        name:
          - pyhelm
        extra_args: --ignore-installed
        state: present
      become: yes
      become_user: root

  tasks:
    - name: Install treafik ingress controller
      helm:
        chart:
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/traefik
        state: present
        name: "traefik-{{ namespace }}"
        namespace: "{{ namespace }}"
```

##### EXPECTED RESULTS

I expect the playbook to run without any errors ;)

##### ACTUAL RESULTS

Even with -vvvv there is no more output than the one posted in the title and above within this report.

```paste below
$ ansible-playbook setup.yml --ask-become-pass --extra-vars "namespace=de
BECOME password: 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [127.0.0.1] ************************************************************************************************************************************************************************************

TASK [Ensure Python and libgit2 are installed] ******************************************************************************************************************************************************
Wednesday 25 March 2020  07:41:05 +0100 (0:00:00.054)       0:00:00.054 ******* 
fatal: [127.0.0.1]: FAILED! => {"msg": "failed to find the executable specified sh. Please verify if the executable exists and re-try."}
        to retry, use: --limit @/Users/renepardon/Projects/***/installer/setup.retry

PLAY RECAP ******************************************************************************************************************************************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Wednesday 25 March 2020  07:41:06 +0100 (0:00:00.418)       0:00:00.472 ******* 
=============================================================================== 
Ensure Python and libgit2 are installed ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.42s
```

And when i remove the _executable_ setting within **ansible.cfg**:

```yaml
$ ansible-playbook setup.yml --ask-become-pass --extra-vars "namespace=de
BECOME password: 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [127.0.0.1] ************************************************************************************************************************************************************************************

TASK [Ensure Python and libgit2 are installed] ******************************************************************************************************************************************************
Wednesday 25 March 2020  07:42:48 +0100 (0:00:00.052)       0:00:00.052 ******* 
ok: [127.0.0.1]

TASK [Ensure pyhelm is installed] *******************************************************************************************************************************************************************
Wednesday 25 March 2020  07:42:55 +0100 (0:00:06.938)       0:00:06.991 ******* 
changed: [127.0.0.1]

TASK [Install treafik ingress controller] ***********************************************************************************************************************************************************
Wednesday 25 March 2020  07:43:19 +0100 (0:00:23.495)       0:00:30.486 ******* 
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not import the pyhelm python module. Please install `pyhelm` package."}
        to retry, use: --limit @/Users/renepardon/Projects/***/installer/setup.retry

PLAY RECAP ******************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Wednesday 25 March 2020  07:43:19 +0100 (0:00:00.777)       0:00:31.263 ******* 
=============================================================================== 
Ensure pyhelm is installed ------------------------------------------------------------------------------------------------------------------------------------------------------------------ 23.50s
Ensure Python and libgit2 are installed ------------------------------------------------------------------------------------------------------------------------------------------------------ 6.94s
Install treafik ingress controller ----------------------------------------------------------------------------------------------------------------------------------------------------------- 0.78s
```

But when running `pip list |grep pyhelm`, I see that pyhelm version 2.14.5 is installed.
