### ISSUE TITLE
Add tag description

### ISSUE THREAD

**Issue by Ahmed-Hussein-Karam** [ansible/ansible#68459]
##### SUMMARY

Sometimes tag name needs more description to specify accurately when to use this tag. For example, tags like `urgent`, `severe`, `low_priority` don't have a concrete meaning that specifies accurately the task category. This can be a problem if the playbook is shared with several team members, and someone wants to add a task to the playbook. Now, he/she might be hesitated whether to add some tag to the task or not.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Ansible Tags

##### ADDITIONAL INFORMATION

This feature can be implemented in several ways. For example: In the `main.yaml` of the playbook, we can add (optional) description for any tag used in the playbook.

```yaml
tags:
- name: urgent
  description: any tasks related to services, containers or sockets.
- name: important
  description: tasks related to new features in the beta version and not fully tested yet
```
