### ISSUE TITLE
jenkins_plugin failing with "Connection timed out" error

### ISSUE THREAD

**Issue by alok15ee** [ansible/ansible#68475]
##### ISSUE TYPE
- Bug Report

##### SUMMARY
certain plugin installation fail with:
`failed: [custom-jenkins] (item={u'name': u'artifactory'}) => {"details": "Connection failure: timed out", "failed": true, "item": {"name": "artifactory"}, "msg": "Cannot install plugin."}`

##### COMPONENT NAME
jenkins_plugin module 

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/asingh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Mar 25 2020, 22:31:15) [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]

```
Tested with 2.6 and 2.7
##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Redhat6

##### STEPS TO REPRODUCE

```
- name: Install plugins with a specific version and restart jenkins
  jenkins_plugin:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ 'present' if item.version is defined else jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    updates_url: "{{ jenkins_updates_url }}"
  with_items:
    - "{{ jenkins_plugins }}"
  notify: restart jenkins
  tags: plugins
  retries: 5
  delay: 8

```

##### ACTUAL RESULTS

```
Plugin installed 
changed: [default] => (item={u'name': u'artifactory'})
```
