### ISSUE TITLE
jinja2_native=True with jinja comments duplicates template contents!

### ISSUE THREAD

**Issue by akhayyat** [ansible/ansible#68486]
##### SUMMARY
With `jinja2_native` enabled, a Jinja2 comment (`{# comment #}`) causes duplication of template contents.

Disabling `jinja2_native` produces the expected output.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Jinja2

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = <working-dir>/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 13:18:53) [GCC 9.2.1 20200306]
```

##### CONFIGURATION

```
DEFAULT_JINJA2_NATIVE(<working-dir>/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Debian testing amd64

##### STEPS TO REPRODUCE

```yaml
# playbook
- hosts: localhost
  connection: local
  tasks:
    - copy:
        content: |
          First line
          Second line
          {# This is a comment #}
          Third line
          Fourth line
        dest: test.txt
```

```ini
# ansible.cfg
[defaults]
jinja2_native = True
```

##### EXPECTED RESULTS
```
# test.txt (output)
First line
Second line
Third line
Fourth line
```

##### ACTUAL RESULTS

```
# test.txt (output)
First line
Second line
Third line
Fourth lineFirst line
Second line
Third line
Fourth line
```

Command output:

```paste below
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [copy] ************************************************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
