### ISSUE TITLE
Error in repo when using fortios_system_admin to configure ssh_public_key

### ISSUE THREAD

**Issue by yamjoepobuda** [ansible/ansible#68497]
##### SUMMARY
When attempting to add ssh keys (ssh_public_key1, ssh_public_key2, ssh_public_key3) to adminisistrators using the fortios_system_admin module, the task errors out with a non-descriptive message. Running the same play with "ssh_public_key1" line commented out, the task completes successfully.

I've attempted to define each of the three keys individually, as well as all 3 keys at the same time. I've also reviewed Fortinet's official documentation for this config section (https://kb.fortinet.com/kb/documentLink.do?externalID=FD38771) and the format appears to be what the device is expecting.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fortios_system_admin

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = production-a-redis.h6fgmd.0001.usw2.cache.amazonaws.com:6379:0
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'datadog_callback']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 5
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 40
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
ubuntu: 18.04
ansible_version: 2.9.6

Fortigate OS: 6.0.9
Fortigate hardware: 60E

Fortigate OS: 6.0.6
Fortigate hardware: 600D, 300D

##### STEPS TO REPRODUCE

Notable vars:
```
remote_authorization:
  admins:
    - johndoe

rsa_public_keys:
  johndoe:
    keys:
      - AAAAB3NzaC1yc2EAAAADAQABAAABAQDR3N6ygJB0quJM4586+Txw04ugV3JtUYn4uZJ0PA7ePafJtNvv4DAYPLWuvwOPrk3u5kaRew1eIhLrj7CgsI/nrKB4F7LHUQ8Fd1pJte13i7mTW8BlNbs4ilGSDLdZOpmJU0+Xdfoon/xvoVzK6RCcoaA3+Q/WW2ASlrKmzRhm4Gp/oQrnFE9cUI+s8YfAtR10FAmYEDRezhypy672nccZh4pwHR6s/DgxsqR28JS/X2OvAj5/ErouqIelTNtFmyU/wNhPMYCmKlh5R1wZyPUk98lqA2ReFS8/O+1cN4eQAjHY5956y5zl7yMTCFrMPvscTcP1tl4JLRMg1P/jLmVV
```

Ansible task:
```
- name: Configure SSH key 1
  fortios_system_admin:
    host:  "{{ fortios_host }}"
    username: "{{ fortios_username }}"
    password: "{{ fortios_password }}"
    vdom:  "{{ fortios_vdom }}"
    ssl_verify: "False"
    state: "present"
    system_admin:
      name: "{{ item }}"
      ssh_public_key1: "{{ 'ssh-rsa ' + rsa_public_keys[item]['keys'][0]|default(omit) }}"
  loop: "{{ remote_authorization.admins }}"
  when: fos_version is version('6.0.5','>=') and rsa_public_keys[item]['keys'][0] is defined
  register: _ssh_key_1
```

##### EXPECTED RESULTS

```
TASK [fortios-system-admin : Configure SSH key 1] ****************************
changed: [fw-60e.test.internal] => (item=johndoe)
changed: [fw-300d.test.internal] => (item=johndoe)
changed: [fw-600d.test.internal] => (item=johndoe)
```

##### ACTUAL RESULTS
Task errors with "Error in repo" on every device, on every run. Unfortunately, every failure I've ever experienced with these modules has had the same error message. I wish this were more descriptive, but I digress.

The command does not get entered into FortiOS. Manually entering the command via cli or FortiManager works fine without issue. Running the same module without ssh_public_key1 defined completes successfully.

Non-verbose output:
```
TASK [fortios-system-admin : Configure SSH key 1] ******************************
failed: [fw-60e.test.internal] (item=johndoe) => {"ansible_loop_var": "item", "changed": false, "item": "johndoe", "meta": {"build": 335, "error": -5, "http_method": "POST", "http_status": 500, "name": "admin", "path": "system", "revision": "196.0.0.2736635036.1581028194", "serial": "FGTXXXXXXXXXXXXX", "status": "error", "vdom": "root", "version": "v6.0.9"}, "msg": "Error in repo"}
failed: [fw-300d.test.internal] (item=johndoe) => {"ansible_loop_var": "item", "changed": false, "item": "johndoe", "meta": {"build": 272, "error": -5, "http_method": "POST", "http_status": 500, "name": "admin", "path": "system", "revision": "175.0.0.4021061266.1576194083", "revision_changed": false, "serial": "FGTXXXXXXXXXXXXX", "status": "error", "vdom": "root", "version": "v6.0.6"}, "msg": "Error in repo"}
failed: [fw-600d.test.internal] (item=johndoe) => {"ansible_loop_var": "item", "changed": false, "item": "johndoe", "meta": {"build": 272, "error": -5, "http_method": "POST", "http_status": 500, "name": "admin", "path": "system", "revision": "175.0.0.4021061266.1576194083", "serial": "FGTXXXXXXXXXXXXX", "status": "error", "vdom": "root", "version": "v6.0.6"}, "msg": "Error in repo"}
```

Verbose output (only 1 example shown, since they're all the same):
```
TASK [fortios-system-admin : Configure SSH key 1] ******************************
task path: /etc/ansible/roles/fortios-system-admin/tasks/main.yml:69
failed: [fw-60e.test.internal] (item=johndoe) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "host": "fw-60e.test.internal:8443", 
            "https": true, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "ssl_verify": false, 
            "state": "present", 
            "system_admin": {
                "accprofile": null, 
                "accprofile_override": null, 
                "allow_remove_admin_session": null, 
                "comments": null, 
                "email_to": null, 
                "force_password_change": null, 
                "fortitoken": null, 
                "guest_auth": null, 
                "guest_lang": null, 
                "guest_usergroups": null, 
                "gui_dashboard": null, 
                "gui_global_menu_favorites": null, 
                "gui_vdom_menu_favorites": null, 
                "hidden": null, 
                "history0": null, 
                "history1": null, 
                "ip6_trusthost1": null, 
                "ip6_trusthost10": null, 
                "ip6_trusthost2": null, 
                "ip6_trusthost3": null, 
                "ip6_trusthost4": null, 
                "ip6_trusthost5": null, 
                "ip6_trusthost6": null, 
                "ip6_trusthost7": null, 
                "ip6_trusthost8": null, 
                "ip6_trusthost9": null, 
                "login_time": null, 
                "name": "johndoe", 
                "password": null, 
                "password_expire": null, 
                "peer_auth": null, 
                "peer_group": null, 
                "radius_vdom_override": null, 
                "remote_auth": null, 
                "remote_group": null, 
                "schedule": null, 
                "sms_custom_server": null, 
                "sms_phone": null, 
                "sms_server": null, 
                "ssh_certificate": null, 
                "ssh_public_key1": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDR3N6ygJB0quJM4586+Txw04ugV3JtUYn4uZJ0PA7ePafJtNvv4DAYPLWuvwOPrk3u5kaRew1eIhLrj7CgsI/nrKB4F7LHUQ8Fd1pJte13i7mTW8BlNbs4ilGSDLdZOpmJU0+Xdfoon/xvoVzK6RCcoaA3+Q/WW2ASlrKmzRhm4Gp/oQrnFE9cUI+s8YfAtR10FAmYEDRezhypy672nccZh4pwHR6s/DgxsqR28JS/X2OvAj5/ErouqIelTNtFmyU/wNhPMYCmKlh5R1wZyPUk98lqA2ReFS8/O+1cN4eQAjHY5956y5zl7yMTCFrMPvscTcP1tl4JLRMg1P/jLmVV", 
                "ssh_public_key2": null, 
                "ssh_public_key3": null, 
                "state": null, 
                "trusthost1": null, 
                "trusthost10": null, 
                "trusthost2": null, 
                "trusthost3": null, 
                "trusthost4": null, 
                "trusthost5": null, 
                "trusthost6": null, 
                "trusthost7": null, 
                "trusthost8": null, 
                "trusthost9": null, 
                "two_factor": null, 
                "vdom": null, 
                "wildcard": null
            }, 
            "username": "admin", 
            "vdom": "root"
        }
    }, 
    "item": "johndoe", 
    "meta": {
        "build": 335, 
        "error": -5, 
        "http_method": "POST", 
        "http_status": 500, 
        "name": "admin", 
        "path": "system", 
        "revision": "196.0.0.2736635036.1581028194", 
        "revision_changed": false, 
        "serial": "FGTXXXXXXXXXXXXX", 
        "status": "error", 
        "vdom": "root", 
        "version": "v6.0.9"
    }, 
    "msg": "Error in repo"
}
```
