### ISSUE TITLE
Password lookup doesn't fully enforce chars parameter

### ISSUE THREAD

**Issue by itaylaufer** [ansible/ansible#68490]
##### SUMMARY

When using password lookup with default chars=ascii_letters,digits,punctuation the result won't force that each one of the categories will be in the generated password.

For example, some passwords won't have digits in them, others won't have special punctuation chars in them.

##### ISSUE TYPE
- Feature Idea
- ~Bug Report~

##### COMPONENT NAME

password lookup plugin

##### ANSIBLE VERSION

```paste below
ansible 2.7.10 2.9.6 devel
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

linux

##### STEPS TO REPRODUCE

```yaml
    - name: set fact
      set_fact:
        generated_password: "{{ lookup('password', '/dev/null length=16') }}"
      until: generated_password | search("[0-9]") and generated_password | search("[A-Za-z]") and generated_password | search("[.,:-_]")
      with_sequence: count=20
      retries: 1
      delay: 3
```

##### EXPECTED RESULTS

The sequence is only to generate password multiple times until the error occurred.
I'm expecting to always get a password that has at least one letter, one digit and one punctuation char.

##### ACTUAL RESULTS

Sometimes i get a password that doesn't have one of each, sometimes missing digit and other times missing punctuation char.

Also, the retry in the task won't generate a new password but for the retry will use the same password but i think this is a different issue that might realte to this:
https://github.com/ansible/ansible/pull/67429

I'm currently using ansible 2.7.10 but i've reproduced it also on latest ansible and in devel.

```paste below
ok: [localhost] => (item=1) => {
    "ansible_facts": {
        "generated_password": "Ao2Kj4_IlMinmily"
    },
    "attempts": 1,
    "changed": false,
    "item": "1"
}
ok: [localhost] => (item=2) => {
    "ansible_facts": {
        "generated_password": "pSh7NK:4bfxA0ZO-"
    },
    "attempts": 1,
    "changed": false,
    "item": "2"
}
ok: [localhost] => (item=3) => {
    "ansible_facts": {
        "generated_password": "sukTpjlvo_J2YmHS"
    },
    "attempts": 1,
    "changed": false,
    "item": "3"
}
ok: [localhost] => (item=4) => {
    "ansible_facts": {
        "generated_password": "lxuyAZ652gV9Nhh7"
    },
    "attempts": 1,
    "changed": false,
    "item": "4"
}
ok: [localhost] => (item=5) => {
    "ansible_facts": {
        "generated_password": "Ep-B2Fr.LJgKX_Ru"
    },
    "attempts": 1,
    "changed": false,
    "item": "5"
}
ok: [localhost] => (item=6) => {
    "ansible_facts": {
        "generated_password": "N-vpDNqD2-PvvIXJ"
    },
    "attempts": 1,
    "changed": false,
    "item": "6"
}
ok: [localhost] => (item=7) => {
    "ansible_facts": {
        "generated_password": "jL2CcBBG-z,cgk_9"
    },
    "attempts": 1,
    "changed": false,
    "item": "7"
}
FAILED - RETRYING: set fact (1 retries left).Result was: {
    "ansible_facts": {
        "generated_password": "YDAxedvUQNTXUKgj"
    },
    "attempts": 1,
    "changed": false,
    "retries": 2
}
failed: [localhost] (item=8) => {
    "ansible_facts": {
        "generated_password": "YDAxedvUQNTXUKgj"
    },
    "attempts": 1,
    "changed": false,
    "item": "8"
}
ok: [localhost] => (item=9) => {
    "ansible_facts": {
        "generated_password": "SALero0hrbUL0CTi"
    },
    "attempts": 1,
    "changed": false,
    "item": "9"
}
ok: [localhost] => (item=10) => {
    "ansible_facts": {
        "generated_password": "9MnMLhTk,cx38gMe"
    },
    "attempts": 1,
    "changed": false,
    "item": "10"
}

PLAY RECAP ************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/lookup/password.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
As it is written, this isn't a functionality of the password lookup.  As such, this is a request for a new feature.

`chars` only defines a character pool to use, it doesn't indicate that at least one character from each set will be present in each password

**Comment by Akasurde** [comment]
@itaylaufer I would like this - 

```yaml
  vars:
    password_length: 12
    password_specs:
    - digits
    - ascii_lowercase
    - ascii_uppercase
    - punctuation
  tasks:
    - set_fact:
        remaining_password_length: "{{ password_length -  password_specs | length }}"
        password_spec_str: "{{ password_specs | join(',') }}"

    - set_fact:
        pwd_pool: "{{ pwd_pool | default([]) + [lookup('password', '/dev/null length=1 chars=' ~item)]}}"
      loop: "{{ password_specs }}"

    - debug:
        msg: "{{ pwd_pool | join('') + lookup('password', '/dev/null length=' ~ remaining_password_length ~ ' chars=' ~ password_spec_str )}}"

```
