### ISSUE TITLE
Special handling of SELinux fails in Python 3

### ISSUE THREAD

**Issue by srjturner** [ansible/ansible#68500]
##### SUMMARY
Ansible's [special handling of file systems for SELinux](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-selinux-special-fs) relies upon matching a target path to one of the system's mount points. This does not work when running with Python 3. 

In module_utils/basic.py the function `is_special_selinux_path()` looks for the mount point that is the parent of the supplied path. It does this by passing the path to `find_mount_point()`, and that  function honours the input type of the path parameter - so if a byte array (`b'path'`) is passed to it then a byte array will be returned. The problem is that the potential matches reported by `/proc/mounts` are all strings. In Python 3 comparing a string to a byte array always evaluates to false, so the path is never matched to the mount that it belongs to.

The consequence is that (with Python 3) there is absolutely no special handling of paths under any filesystem, regardless of the value of `special_context_filesystems`. Predictably this results in failures due to the resulting violations of SELinux policy.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module_utils/basic.py

##### ANSIBLE VERSION

```
  ansible 2.9.6
  config file = /tmp/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```
DEFAULT_SELINUX_SPECIAL_FS(/tmp/ansible/ansible.cfg) = ['nfs', 'vboxsf', 'fuse', 'ramfs', 'myspecialfs', 'cifs']
```

##### OS / ENVIRONMENT

OS: CentOS Linux release 8.1.1911 (Core) 
Python: 3.6
SELinux: enabled and enforcing

##### STEPS TO REPRODUCE

Mount a file system e.g. cifs
Try to create a private key on that file system

```
--
- hosts: localhost
  connection: local
  vars:
    yum_mount_packages:
      - samba-common
      - samba-client
      - cifs-utils
    share: //REDACTED/REDACTED
    mount_user: REDACTED
    mount_pass: REDACTED
    mount_path: '/share'
    local_user: foo
    local_group: foo
    filename: 'foo.ca-pkey.pem'
  tasks:
    - yum: name={{ item }} update_cache=yes state=installed
      with_items: "{{ yum_mount_packages }}"
    - template:
        src: ./smbcredentials.j2
        dest: "/etc/smbcredentials"
        owner: "{{ local_user }}"
        mode: 0600
    - mount:
        fstype: cifs
        state: mounted
        path: "{{ mount_path }}"
        opts: "credentials=/etc/smbcredentials,file_mode=0755,dir_mode=0755,uid={{ local_user }},gid={{ local_group }}"
        src: "{{ share }}"
      remote_user: "{{ local_user }}"
    - openssl_privatekey:
        path: '{{ mount_path}}/{{ filename }}'
        size: '1024'

```

##### EXPECTED RESULTS

The private key is created at /share/foo.ca-pkey.pem

##### ACTUAL RESULTS

The openssl_privatekey fails to create the key because it fails to treat the cifs mount
as 'special' i.e. it tries to get the default SELinux context 
("system_u:object_r:default_t:s0') as opposed to the cifs one ('system_u:object_r:cifs_t:s0').

```
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602 `" && echo ansible-tmp-1585251293.868567-18336240996602="` echo /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/crypto/openssl_privatekey.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-297758x9ctvh3/tmpp9wx7cs4 TO /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602/AnsiballZ_openssl_privatekey.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602/ /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602/AnsiballZ_openssl_privatekey.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602/AnsiballZ_openssl_privatekey.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1585251293.868567-18336240996602/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_openssl_privatekey_payload_tmff_dfq/ansible_openssl_privatekey_payload.zip/ansible/module_utils/basic.py", line 974, in set_context_if_different
    rc = selinux.lsetfilecon(to_native(path), ':'.join(new_context))
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cur_context": [
        "system_u",
        "object_r",
        "cifs_t",
        "s0"
    ],
    "gid": 1001,
    "group": "foo",
    "input_was": [
        "system_u",
        "object_r",
        "default_t",
        "s0"
    ],
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "cipher": null,
            "content": null,
            "curve": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": null,
            "mode": "0600",
            "owner": null,
            "passphrase": null,
            "path": "/share/foo.ca-pkey.pem",
            "regexp": null,
            "remote_src": null,
            "select_crypto_backend": "auto",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "size": 1024,
            "src": null,
            "state": "present",
            "type": "RSA",
            "unsafe_writes": null
        }
    },
    "mode": "0755",
    "msg": "invalid selinux context: [Errno 95] Operation not supported",
    "new_context": [
        "system_u",
        "object_r",
        "default_t",
        "s0"
    ],
    "owner": "foo",
    "path": "/share/.ansible_tmpme0393tgfoo.ca-pkey.pem",
    "secontext": "system_u:object_r:cifs_t:s0",
    "size": 891,
    "state": "file",
    "uid": 1001
}
```

##### NOTES

The key is created without issue if i do either of the following:

1. Comment out the lines 897-898 in basic.py:

```
# if path_is_bytes:
#   return b_path
```

This confirms that the problem is that Ansible is not honouring 
special_context_filesystems

2. If I install Ansible under Python 2. 

This confirms that the problem is with Python 3 because Python 2 
essentially ignores the distinction between byte arrays and strings.

```
