### ISSUE TITLE
 Module authorized_key fails when the user doesn't exist on the system and the path isn't the default

### ISSUE THREAD

**Issue by llsousa** [ansible/ansible#68509]
##### SUMMARY

Module authorized_key fails when the user doesn't exist on the system and the path isn't the default. 

The problem, supposedly, was fixed on issues #11257 and #30112, but on the current version 2.9.6, still occurs. Could this be a regression?

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

Module authorized_key.

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Vagrant box "debian/stretch64", Debian GNU/Linux 9 (stretch).

##### STEPS TO REPRODUCE

Supposing that the file `/etc/security/authorized_keys` has the key `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIZwyo6tX8DZ+HQM4ppEdueTPhp+XJCh7Lcpn/Vx5ofY` for `user3`, the user was deleted from the system on a previous task, consider the task below to remove the key from file:

```yaml
- name: garbage collect sudo authorized keys (users deleted)
  authorized_key:
    user: user3
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIZwyo6tX8DZ+HQM4ppEdueTPhp+XJCh7Lcpn/Vx5ofY
    state: absent
    path: /etc/security/authorized_keys
    # Not the default location, manage_dir must set to 'no' to retain permissions
    manage_dir: no
```

##### EXPECTED RESULTS

The key `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIZwyo6tX8DZ+HQM4ppEdueTPhp+XJCh7Lcpn/Vx5ofY` from `user3`, on file `/etc/security/authorized_keys`, was deleted, and the file retains file permissions.

##### ACTUAL RESULTS

The user `user3` wasn't deleted and was returned the error:

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to lookup user user3: 'getpwnam(): name not found: user3'"}
```
