### ISSUE TITLE
Wrong identification of user on remote machine.

### ISSUE THREAD

**Issue by ToadKillerDog1** [ansible/ansible#68513]
##### SUMMARY
win_command use local group to perform tasks instead of user who is used in ansible inventory file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_command and win_shell

##### ANSIBLE VERSION

```paste below

ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Jenkins execute ansible-playbook. Jenkins slave server is RHEL7. Below task is executed on Windows 2016

##### STEPS TO REPRODUCE

Below is an inventory and example of win_command playbook with robocopy command. If I use the same robocopy command after logon to windows machine as a `company\systemansible` user it is being executed without any problem. User `company\systemansible` is domain user with full admin access to all servers and to the network share `\\network-share`

```
[bamboo_host]
server_name ansible_host=server_name.domain.companynet.net ansible_connection=winrm ansible_winrm_transport=kerberos ansible_user=systemansible@comapanynet.net ansible_password=******** ansible_port=5986 ansible_winrm_server_cert_validation=ignore
```
```
- name: Sync the contents of bamboo-home directory to backup site, including subdirectories
  win_command: robocopy \\network-share\bamboo-home d:\backup\bamboo-home /E /w:5 /r:2 /log:D:\Applications\Atlassian\log.txt /XD \\network-share\bamboo-home\artifacts
  register: info_robocopy
  tags:
    - robo
```

##### EXPECTED RESULTS

Copy all data between source and destination. Properly being recognized as a `company\systemansible`

##### ACTUAL RESULTS

The problem is when I'm execute win_command I'm being recognized as a windows local group `server_name\administrators` instead of `company\systemansible`. In scope of the server there is no problem that user is `server_name\administrators` but it could be useful to be properly recognized. Unfortunately for CIFS share `\\network-share` where local server group is not authorized it is necessary to be recognized properly as a `ansible_user=systemansible@comapanynet.net` because I'm receiving ACCESS DENIED. 

```paste below

```
