### ISSUE TITLE
Ansible.ModuleUtils.WebRequest: cannot ignore proxy

### ISSUE THREAD

**Issue by johnbui423** [ansible/ansible#68528]
##### SUMMARY

It seems not possible to run `win_get_url` without proxy.

Based on the documentation, my expectation was that setting the parameter `use_proxy` to 'no' should ignore the default IE proxy, and run without proxy if `proxy_url` is not set at the same time. However, this is not working, even with `use_proxy: no`, the IE proxy is still being used.

Looking into the actual source code at https://github.com/ansible/ansible/blob/e5995a2eed08c0a0bf4797ae8a38aefd160b0f0a/lib/ansible/module_utils/powershell/Ansible.ModuleUtils.WebRequest.psm1#L252, I believe the issue is this:

```
    if (-not $UseProxy) {
        $proxy = $null
    } elseif ($ProxyUrl) {
        $proxy = New-Object -TypeName System.Net.WebProxy -ArgumentList $ProxyUrl, $true
    } else  {
        $proxy = $web_request.Proxy
    }

    # $web_request.Proxy may return $null for a FTP web request. We only set the credentials if we have an actual
    # proxy to work with, otherwise just ignore the credentials property.
    if ($null -ne $proxy) {
        [...]

        $web_request.Proxy = $proxy
    }
```

In other words, when `use_proxy: no`, the `$proxy` variable will first (correctly) be set to `$null`, but that value is never written to `$web_request.Proxy`, and thus never used. Instead the default value is used. 
Bringing `$web_request.Proxy = $proxy` outside of that last `if block` fixes things for me, but might break other things.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/powershell/Ansible.ModuleUtils.WebRequest.psm1

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.1
```

##### CONFIGURATION

NA

##### OS / ENVIRONMENT

Seeing this on Windows 10.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  vars:
    # set unexisting proxy
    proxy: unexisting
    download_url: <local url that can be reached without proxy>

  tasks:
    - name: Configure IE to use explicit proxy host with port and without auto detection
      win_inet_proxy:
        auto_detect: no
        proxy: "{{ proxy }}"

    - name: Download package without proxy
      win_get_url:
        url: "{{ download_url }}"
        dest: C:\Users\ansible\test.jpg
        use_proxy: no
```

##### EXPECTED RESULTS

Playbook should succesfully download test file without trying to connect to the unexisting proxy.

##### ACTUAL RESULTS

Playbook fails, as it tries to connect to the unexisting proxy.
