### ISSUE TITLE
Integar casting of unicode strings [u4185686016], [u1021896] returns zero

### ISSUE THREAD

**Issue by dineshr93** [ansible/ansible#68527]
##### SUMMARY
number in the Unicode string format needs to be casted {{ x | int}} to get the integer as mentioned in 
this  #4170
But further integer casting of the unicode string results as 0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact.
unicode string Casting to integer set_fact {{ x | int }}

##### ANSIBLE VERSION
```
dinesh@dinesh-VirtualBox:/$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dinesh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

##### OS / ENVIRONMENT
Ubuntu 16.04 in Virtual box of Windows 10

##### STEPS TO REPRODUCE

```
---
- hosts: fossology_test
  become: true
  become_user: root
  environment: 
   HOME: /usr/ansible
  gather_facts: no
  tasks:
   - name: run shell script
     become: true
     become_user: root
     command: ./shm.sh
     args:
      chdir: /usr/local/src/
     register: results

   - set_fact:
        shmmax: "{{ shmmax }}" #returns [u4185686016]
        shmall: "{{ shmall  }}"       #returns [u1021896]
     vars:
        shmmax: "{{ results.stdout | regex_search('shmmax=([0-9]+)','\\1') }}" 
        shmall: "{{ results.stdout | regex_search('shmall=([0-9]+)','\\1') }}"   

   - name: sysctl -w kernel.shmmax={{ shmmax | int}}
     become: true
     become_user: root
     command: sysctl -w kernel.shmmax={{ shmmax  | int}} 

   - name: sysctl -w kernel.shmall={{ shmall  | int}}
     become: true
     become_user: root
     command: sysctl -w kernel.shmall={{ shmall  | int}}

```

##### EXPECTED RESULTS
```
dinesh@dinesh-VirtualBox:~/Documents/remote/Ansible-Playbook/fossology_playbook$ ansible-playbook regex.yml -K -v
Using /etc/ansible/ansible.cfg as config file
BECOME password: 

PLAY [fossology_test] ************************************************************************************

TASK [run shell script] **********************************************************************************
changed: [fossology_test] => {"changed": true, "cmd": ["./shm.sh"], "delta": "0:00:00.007140", "end": "2020-03-28 10:38:21.298275", "rc": 0, "start": "2020-03-28 10:38:21.291135", "stderr": "", "stderr_lines": [], "stdout": "kernel.shmmax=4185686016\nkernel.shmall=1021896", "stdout_lines": ["kernel.shmmax=4185686016", "kernel.shmall=1021896"]}

TASK [set_fact] ******************************************************************************************
ok: [fossology_test] => {"ansible_facts": {"shmall": ["1021896"], "shmmax": ["4185686016"]}, "changed": false}

TASK [sysctl -w kernel.shmmax=4185686016] *************************************************************************
changed: [fossology_test] => {"changed": true, "cmd": ["sysctl", "-w", "kernel.shmmax=4185686016"], "delta": "0:00:00.004259", "end": "2020-03-28 10:38:21.869796", "rc": 0, "start": "2020-03-28 10:38:21.865537", "stderr": "", "stderr_lines": [], "stdout": "kernel.shmmax = 4185686016", "stdout_lines": ["kernel.shmmax = 4185686016"]}

TASK [sysctl -w kernel.shmall=1021896] *************************************************************************
changed: [fossology_test] => {"changed": true, "cmd": ["sysctl", "-w", "kernel.shmall=1021896"], "delta": "0:00:00.005827", "end": "2020-03-28 10:38:22.420847", "rc": 0, "start": "2020-03-28 10:38:22.415020", "stderr": "", "stderr_lines": [], "stdout": "kernel.shmall = 1021896", "stdout_lines": ["kernel.shmall = 1021896"]}

PLAY RECAP ***********************************************************************************************
fossology_test             : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

dinesh@dinesh-VirtualBox:~/Documents/remote/Ansible-Playbook/fossology_playbook$ 

```

##### ACTUAL RESULTS

```
dinesh@dinesh-VirtualBox:~/Documents/remote/Ansible-Playbook/fossology_playbook$ ansible-playbook regex.yml -K -v
Using /etc/ansible/ansible.cfg as config file
BECOME password: 

PLAY [fossology_test] ************************************************************************************

TASK [run shell script] **********************************************************************************
changed: [fossology_test] => {"changed": true, "cmd": ["./shm.sh"], "delta": "0:00:00.007140", "end": "2020-03-28 10:38:21.298275", "rc": 0, "start": "2020-03-28 10:38:21.291135", "stderr": "", "stderr_lines": [], "stdout": "kernel.shmmax=4185686016\nkernel.shmall=1021896", "stdout_lines": ["kernel.shmmax=4185686016", "kernel.shmall=1021896"]}

TASK [set_fact] ******************************************************************************************
ok: [fossology_test] => {"ansible_facts": {"shmall": ["1021896"], "shmmax": ["4185686016"]}, "changed": false}

TASK [sysctl -w kernel.shmmax=0] *************************************************************************
changed: [fossology_test] => {"changed": true, "cmd": ["sysctl", "-w", "kernel.shmmax=0"], "delta": "0:00:00.004259", "end": "2020-03-28 10:38:21.869796", "rc": 0, "start": "2020-03-28 10:38:21.865537", "stderr": "", "stderr_lines": [], "stdout": "kernel.shmmax = 0", "stdout_lines": ["kernel.shmmax = 0"]}

TASK [sysctl -w kernel.shmall=0] *************************************************************************
changed: [fossology_test] => {"changed": true, "cmd": ["sysctl", "-w", "kernel.shmall=0"], "delta": "0:00:00.005827", "end": "2020-03-28 10:38:22.420847", "rc": 0, "start": "2020-03-28 10:38:22.415020", "stderr": "", "stderr_lines": [], "stdout": "kernel.shmall = 0", "stdout_lines": ["kernel.shmall = 0"]}

PLAY RECAP ***********************************************************************************************
fossology_test             : ok=4    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

dinesh@dinesh-VirtualBox:~/Documents/remote/Ansible-Playbook/fossology_playbook$ 


```
