### ISSUE TITLE
podman_image should only report changed: true if it actually builds a new image

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#68541]
##### SUMMARY

podman_image reports `changed: true` even if the build process does not actually create a new image.  This means it's not possible to use `notify` to restart containerized services when a new image is available.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

podman_image

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /home/lars/.ansible.cfg
  configured module search path = ['/home/lars/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

##### CONFIGURATION

```paste below
COMMAND_WARNINGS(/home/lars/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/lars/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

Fedora 31

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - podman_image:
        name: squid
        state: build
        force: true
        path: .
      register: build

    - debug:
        msg: "It changed!"
      when: build is changed

```

##### EXPECTED RESULTS

I expect the  playbook to report `It changed!` the first time it runs, but not for subsequent runs if no files in the build directory have changed.

##### ACTUAL RESULTS

The playbook reports `It changed!` every time it runs.

Without specifying `force: true`, the task won't even attempt to build the image if an existing image of the same name/tag exists.
