### ISSUE TITLE
Ability to prompt only vars that don't have default value

### ISSUE THREAD

**Issue by Ahmed-Hussein-Karam** [ansible/ansible#68549]
##### SUMMARY

Because Ansible is used for automation, the less human interaction, the better it is. To achieve this, I suggest adding a feature to be able to prompt for only vars that don't have default value. In other words, the third case in the following `else` statement is: when user explicitly specifies that playbook should use default values and run normally.
https://github.com/ansible/ansible/blob/0fb5593abf0a703baadf2ef18ffde592c710993c/lib/ansible/executor/playbook_executor.py#L138-L139
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- Play directives
- Prompts
##### ADDITIONAL INFORMATION

This can be implemented in two ways.
**Method 1:** using a flag in `vars_prompt`

```yaml
vars_prompt:

    - name: username
      prompt: "What is your username?"
      default: "Ahmed_Hussein"
      force: no # [ no: ask only if no default value, yes: always ask]
```
**Method 2:** adding play [directive](https://docs.ansible.com/ansible/2.3/playbooks_directives.html)

```
ansible-playbook main.yaml --prompt_when_no_default
```
