### ISSUE TITLE
Task time out feacture is needed 

### ISSUE THREAD

**Issue by msgithub789** [ansible/ansible#68582]
##### SUMMARY

Ansible gets hung when multiple hosts are used in inventory and yum command is used.
its not that I am performing yum upgrade . Simple command like yum updateinfo list also gets hung when multiple hosts are used in inventory. So if it gets stuck for 1 host then it does not skip and proceed . Also output is not displayed .

##### ISSUE TYPE
- Feature Idea
Ansible gets hung when multiple hosts are used in inventory and yum command is used.
its not that I am performing yum upgrade . Simple command like yum updateinfo list also gets hung when multiple hosts are used in inventory. So if it gets stuck for 1 host then it does not skip and proceed . Also output is not displayed .

##### COMPONENT NAME

timeout

##### ADDITIONAL INFORMATION

each task needs a timeout . Without that it is hung in a endless loop.

```yaml
name: Test Yum
hosts: Custom3
connection: paramiko
become_user: root
become: yes
become_method: sudo
tasks:
- shell: yum updateinfo lis
```
