### ISSUE TITLE
package_facts auto issue

### ISSUE THREAD

**Issue by impsik** [ansible/ansible#68583]
##### SUMMARY
package_facts not detecting apt under debian 10

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
package_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
```

##### CONFIGURATION

```paste below
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python
```

##### OS / ENVIRONMENT

Debian 10.3

##### STEPS TO REPRODUCE

ansible -m package_facts -a "manager=auto" localhost

OR

```yaml
  - name: "Gather the package facts"
    package_facts:
      manager: auto

  - name: "Check whether a package called bash is installed"
    debug:
      msg: "{{ ansible_facts.packages['bash'] | length }} versions of bash are installed!"
    when: "'bash' in ansible_facts.packages"
```

##### EXPECTED RESULTS

ansible should report that bash is installed when manager is set to auto

`manager: apt`

```
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Gather the package facts] ***********************************************************************************************************************************************************************************
ok: [localhost]

TASK [Check whether a package called bash is installed] ***********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "1 versions of bash are installed!"
}
```
##### ACTUAL RESULTS

`manager: auto`

```
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Gather the package facts] ***********************************************************************************************************************************************************************************
ok: [localhost]

TASK [Check whether a package called bash is installed] ***********************************************************************************************************************************************************
skipping: [localhost]

```
