### ISSUE TITLE
Magic Varaible ansible_limit could not match pattern

### ISSUE THREAD

**Issue by automateyournetwork** [ansible/ansible#68585]
##### SUMMARY
I am trying to use 

- hosts: ansible_limit

      when: ansible_limit is defined

However my playbook returns the following error:

[WARNING]: Could not match supplied host pattern, ignoring: ansible_limit

I am using 

anisble-playbook playbook.yml --limit hostname 

I am expecting ansible_limit to equal 'hostname' and be able to be used for my hosts 

Am I using this magic variable incorrectly?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible_limit magic variable

##### ANSIBLE VERSION

``ansible 2.9.1
  config file = /home/capobj/Lab-Repository/playbooks/ansible.cfg
  configured module search path = ['/usr/lib/python2.7/site-packages/napalm_ansible/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below

```

##### OS / ENVIRONMENT

CentOS

##### STEPS TO REPRODUCE

```yaml
- hosts: ansible_limit
  vars_prompt:
    - name: git_commit_prompt
      when: ansible_limit is defined
      prompt: "Enter Git Commit Message"
      private: no
      tags: ['config','documentation']
```

##### ACTUAL RESULTS

```paste below
[WARNING]: Could not match supplied host pattern, ignoring: ansible_limit
```
