### ISSUE TITLE
win_acl module does not seem to be able to accept environment variables for path

### ISSUE THREAD

**Issue by brettfire** [ansible/ansible#68597]
##### SUMMARY

Some modules such as win_lineinfile support using environment variables as part of the path, for example `%programdata%\ssh\administrators_authorized_keys`, however win_acl seems to lack this capability. I believe all windows modules should be able to use environment variables in the path.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_acl

##### ADDITIONAL INFORMATION

```yaml
- name: Set administrators_authorized_keys ACL - BUILTIN\Administrators
  win_acl:
    path: '%programdata%\ssh\administrators_authorized_keys'
    user: BUILTIN\Administrators
    rights: FullControl
    type: allow
    state: present
```
