### ISSUE TITLE
YUM groupremove is not idempotent

### ISSUE THREAD

**Issue by luiscachog** [ansible/ansible#68599]
##### SUMMARY
I have this task, that runs OK the first time:

```yaml
- name: Ensure X Window System is not installed (Scored)
  yum:
    name:
      - "@X Window System"
      - "@Server with GUI"
    state: absent
```

But the second time that my playbook runs it gives me the error:

```json
fatal: [redhat7]: FAILED! => {
    "changed": false,
    "changes": {
        "removed": [
            "@Server with GUI"
        ]
    },
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "@X Window System",
                "@Server with GUI"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "absent",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "Package '@Server with GUI' couldn't be removed!",
    "rc": 0,
    "results": [
        "@X Window System is not installed",
        "Loaded plugins: langpacks, ovl, product-id, search-disabled-repos, subscription-\n              : manager\nNo Packages marked for removal\n"
    ]
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
I believe is: lib/ansible/modules/packaging/os/yum.py 

##### ANSIBLE VERSION

```shell
ansible --version
ansible 2.9.4
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.virtualenvs/ca-env/lib/python3.7/site-packages/ansible
  executable location = ~/.virtualenvs/ca-env/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

TARGET: RHEL7

##### STEPS TO REPRODUCE

```yaml
- name: Ensure X Window System is not installed (Scored)
  yum:
    name:
      - "@X Window System"
      - "@Server with GUI"
    state: absent
```

##### EXPECTED RESULTS

If the YUM group is NOT installed, I expect do not generate an error and marked the task as ok on the second run.

##### ACTUAL RESULTS

```json
"results": [
        "@X Window System is not installed",
        "Loaded plugins: langpacks, ovl, product-id, search-disabled-repos, subscription-\n              : manager\nNo Packages marked for removal\n"
    ]

```
