### ISSUE TITLE
vmware_guest: virt_based_security switch does not work as expected

### ISSUE THREAD

**Issue by benjaminrein** [ansible/ansible#68614]
##### SUMMARY

virt_based_security: False does not work as expected, because it enabled Virtualization Based Security (VBS). Disabling VBS on a vm already present is not possible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules                                           ', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (R                                           ed Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT

RHEL 7.7, vCenter 6.7 U1

##### STEPS TO REPRODUCE

Create a new VM configured as below. First error.
Execute task a second time where the vm is already present. Second error.

```yaml
  - name: create a virtual machine on given ESXi hostname
    vmware_guest:
      hostname:       '{{ vcenter_hostname }}'
      username:       '{{ vcenter_username }}'
      password:       '{{ vcenter_password }}'
      datacenter:     '{{ vcenter_datacenter }}'
      folder:         '{{ vmware_settings.folder }}'
      resource_pool:  '{{ vmware_settings.resource_pool }}'
      name:           'TestVM'
      guest_id:       'windows9Server64Guest'
      cluster:        '{{ vmware_settings.cluster }}'
      disk:
      - size_gb:                    "1"
        type:                       "thin"
        datastore:                  "Linux-Windows"
      hardware:       
        version:                    "14"
        boot_firmware:              "efi"
        memory_mb:                  "1024"
        num_cpus:                   "1"
        virt_based_security:        "False"      
      state:          'present'
      force:          true
      validate_certs: 'no'
```

##### EXPECTED RESULTS

When creating a new VM VBS should be disabled.
When the VM is already present with VBS enabled, VBS should be switched off.

##### ACTUAL RESULTS

If the switch virt_based_security is present in hardware configuration, VBS is enabled regardless of the switch value.

```paste below

```
