### ISSUE TITLE
iptables module broken

### ISSUE THREAD

**Issue by The-Judge** [ansible/ansible#68612]
##### SUMMARY
Module triggers an unsupported syntax with iptables executable.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
iptables

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = -SNIP-/ansible.cfg
  configured module search path = ['-SNIP-/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 15:23:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```
DEFAULT_BECOME = True
HOST_KEY_CHECKING = False
INTERPRETER_PYTHON = auto_silent
```

##### OS / ENVIRONMENT

OS Ansible is executed in: MacOSX
Destination OS: SUSE Linux Enterprise Server 12 SP5

##### STEPS TO REPRODUCE

Play:
```yaml
- name: create ajp port whitelist
  iptables:
    action: insert
    chain: INPUT
    comment: See Ticket123
    destination_port: '8009'
    policy: ACCEPT
    protocol: tcp
    source: '172.18.0.2'
```

##### EXPECTED RESULTS
Not to receive an error.

##### ACTUAL RESULTS
When executed, this doesn't work:

```
failed: [-SNIP-] (item=172.18.0.2) => {"ansible_loop_var": "item", "changed": false, "cmd": "/usr/sbin/iptables -t filter -L INPUT -p tcp -s 172.18.0.2 --destination-port 8009 -m comment --comment 'See Ticket123'", "item": "172.18.0.2", "msg": "iptables v1.4.21: Illegal option `-s' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.4.21: Illegal option `-s' with this command\n\nTry `iptables -h' or 'iptables --help' for more information.\n", "stderr_lines": ["iptables v1.4.21: Illegal option `-s' with this command", "", "Try `iptables -h' or 'iptables --help' for more information."], "stdout": "", "stdout_lines": []}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/iptables.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/iptables.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@The-Judge Could you please try using 'jump' instead of 'policy'? 

cc @sebastiendarocha

needs_info

**Comment by Akasurde** [comment]
resolved_by_pr #69152

**Comment by Akasurde** [comment]
@The-Judge I investigated in parameters. It seems that `policy` only allows one parameter `chain`, which translates to `iptables -P INPUT ACCEPT`, the rest of the parameters are ignored. 

So basically, you need -

```yaml
- name: create ajp port whitelist
  iptables:
    action: insert
    chain: INPUT
    comment: See Ticket123
    destination_port: '8009'
    jump: ACCEPT # <---- instead of policy
    protocol: tcp
    source: '172.18.0.2'
```

Which turns out to -

```
# iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  172.18.0.2           anywhere             tcp dpt:8009 /* See Ticket123 */
```
I hope that is what you expected from this task. I updated to description of `policy` in module. Please go through once and let me know if you want to add anything. Thanks

needs_info
