### ISSUE TITLE
include_role: vars_from with loop: variables not loaded

### ISSUE THREAD

**Issue by Altiire** [ansible/ansible#68615]
##### SUMMARY
I loop over a role with a base variable changed at every run.

A var file is supposed to be loaded every time based on the item of the loop.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/altiire/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION
```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Debian 10 hosted on GCP

##### STEPS TO REPRODUCE
```yaml
- name: Save existing deployments
  hosts: all

  vars_files:
    - vars/common.yml

  tasks:
    - shell: find . -maxdepth 2 -mindepth 2 -type f -name "docker-compose.yml" | egrep -v "common|deployment_template" | xargs -I{} dirname {} | xargs -I{} basename {}
      args:
        chdir: "{{ deployment_path }}"
      register: existing_deployments

- name: Update the deployments
  hosts: all
  remote_user: "{{ remote_user }}"

  vars_files:
    - vars/common.yml
  vars:
    - deployment_template_path: "{{ deployment_path }}/deployment_template"

  tasks:
    - debug:
        msg: "{{ item }}"
      loop: "{{ existing_deployments.stdout_lines }}"
    - include_role:
        name: deploy
        vars_from: "vars/deployment_{{ item }}.yml"
      vars:
        - current_deployment_path: "{{ deployment_path }}/{{ item }}"
        - deployment_name: "{{ item }}"
      loop: "{{ existing_deployments.stdout_lines }}"
```

##### EXPECTED RESULTS
Variables under `vars/deployment_{{ item }}.yml` should be loaded

##### ACTUAL RESULTS
```paste below
TASK [deploy : replace] ********************************************************************************************************************************************************************************************
task path: /home/altiire/deployer/roles/deploy/tasks/files.yml:75
fatal: [127.0.0.1]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'vhost_prefix' is undefined\n\nThe error appears to be in '/home/altiire/deployer/roles/deploy/tasks/files.yml': line 75, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n        replace: \"{{ deployment_name }}\"\n    - replace:\n      ^ here\n"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/role/include.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This issue needs verified, I believe this had already been resolved in the following code:

https://github.com/ansible/ansible/blob/a213b9160c7902122d20f05b2fa27a15cd541f4a/lib/ansible/playbook/included_file.py#L180-L185

**Comment by sivel** [comment]
I'm not able to reproduce this.  If you can provide a full, minimal reproducer like I have here, we might be able to troubleshoot further.

Here is my reproducer:

```
.
├── 68615.yml
└── roles
    └── loopy
        ├── tasks
        │   └── main.yml
        └── vars
            ├── one.yml
            └── two.yml
```

68615.yml
```
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        role: loopy
        vars_from: "{{ item }}.yml"
      loop:
        - one
        - two
```

roles/loopy/tasks/main.yml
```
- debug:
    var: foo
```

roles/loopy/vars/one.yml
```
foo: one
```

roles/loopy/vars/two.yml
```
foo: two
```

Output:
```
$ ansible-playbook 68615.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [include_role : loopy] ****************************************************

TASK [loopy : debug] ***********************************************************
ok: [localhost] => {
    "foo": "one"
}

TASK [loopy : debug] ***********************************************************
ok: [localhost] => {
    "foo": "two"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

needs_info
