### ISSUE TITLE
azure_rm_common.has_tags correct error when tag's key got ":" in it

### ISSUE THREAD

**Issue by Maarc-D** [ansible/ansible#68628]
##### SUMMARY

On all cloud provider there is bestpractices, and we see a lot of documentations about cloud tags that advice to name tag's key with ":" syntaxe. for example : 
key : "company:group:function" 
value : "value"
If we use this best practice the has_tag function will split on ":" and raise `ValueError: too many values to unpack`

I propose to have another delimiter or better use JSON syntaxe in the string : `'{"company:group:function":"value"}'`

in the function `has_tag` we could first try to json.decode if it raise error split on ":" as now to keep backward compatibility

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`has_tags` in `module_utils.azure_rm_common.has_tags`

##### ANSIBLE VERSION

```paste below
2.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

all

##### STEPS TO REPRODUCE

* create azure VM with tag as key : "company:group:fonction" and value "value"
* try to retrive it using azure_rm_virtualmachine_info @see code bellow
  

```yaml
- name: "Get Azure VM infolved for collected host"
  azure_rm_virtualmachine_info:
    tags: 
      - "company:group:fonction:value"
  register: vms
  connection: local
```

##### EXPECTED RESULTS

* to return the previous created vm according to the vm output 

##### ACTUAL RESULTS

```paste below
ValueError: too many values to unpack
```
