### ISSUE TITLE
enos_config task ignores --check 

### ISSUE THREAD

**Issue by stamfest** [ansible/ansible#68634]
##### SUMMARY
Using --check on ansible-playbook using enos_config task gets ignored

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
enos_config

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION

```paste below

```
(no output from ansible-config dump --only-changed)

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE

```yaml
- name: "Show enos_config ansible bug"
  hosts: pureflex
  gather_facts: no

  tasks:
    - name: configure interface settings
      enos_config:
        lines:
          - enable
          - switchport mode trunk
        parents: 
          - interface port EXT4
```

ansible-playbook --check DEMO.yml

##### EXPECTED RESULTS

Config before

```paste below
interface port EXT4
        shutdown
        exit
```

Config after

```paste below
interface port EXT4
        shutdown
        exit
```

##### ACTUAL RESULTS

Config after contains "switchport mode trunk" line when using the playbook with the "--check" option

```paste below
interface port EXT4
        shutdown
        switchport mode trunk
        exit
```

```paste below

PLAY [Show enos_config ansible bug] *******************************************************************************************************************

TASK [configure interface settings] *******************************************************************************************************************
ok: [<REDACTED>]

PLAY RECAP ********************************************************************************************************************************************
<REDACTED>               : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
