### ISSUE TITLE
Postgresql_*, can't modify role with dot in name.

### ISSUE THREAD

**Issue by michalg91** [ansible/ansible#68632]
##### SUMMARY
While creating role with dot in name (eg jan.kowalski) postgres module fails with PostgreSQL does not support role with more than 1 dots.
`(item={'name': 'jan.kowalski'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "jan.kowalski"}, "msg": "PostgreSQL does not support role with more than 1 dots"}`
When trying to assing group with postgresql_membership module it fails telling the user i just created doesn't exist. Modyfying user privileges also doesn't work when running next postgresql_user task.
Providing user with escaped quotes works only when user doesn't exists in database and it only allow me to create the user, next tasks are failing at **PostgreSQL does not support role with more than 1 dots**.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_*

##### ANSIBLE VERSION

```
ansible 2.9.6
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### OS / ENVIRONMENT

target os: Debian stretch
Postgresql version: 11

##### STEPS TO REPRODUCE

```yaml
---
- postgresql_user:
      name: "sample_group"
      role_attr_flags: "NOLOGIN"

- postgresql_user:
      name: "jan.kowalski"

- postgresql_membership:
      group: "sample_group"
      target_roles: ['jan.kowalski']

- postgresql_user:
      name: "jan.kowalski"
      db: "test_db"
      priv: 'CONNECT'

```

##### EXPECTED RESULTS

Ansible should create role and assing parent role to the user, running it again should not fail, and should not try to create user again. The **PostgreSQL does not support role with more than 1 dots** should not come out, while it has only one error.

##### ACTUAL RESULTS

```
 (item={'name': 'jan.kowalski'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "jan.kowalski"}, "msg": "PostgreSQL does not support role with more than 1 dots"}
```
