### ISSUE TITLE
win_pagefile does nothing when override is false

### ISSUE THREAD

**Issue by LukasGibb** [ansible/ansible#68652]
##### SUMMARY
win_pagefile does nothing when override is false ('no')

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_pagefile

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/{redacted}/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = {redacted}
```

##### OS / ENVIRONMENT

Currently experiencing the issue with Windows 2016 hosts but pretty sure it will affect 2012 R2 also.

##### STEPS TO REPRODUCE

Apply the play below with the page file 'maximum_size' currently set to something different.

```yaml
---
# This role contains plays that will configure pagefile/virtual memory settings on windows hosts.

- name: Set C pagefile, do not override if exists
  win_pagefile:
    drive: C
    initial_size: 1024
    maximum_size: "{{ win_pagefile_c_max_size }}"
    state: present
    override: no
  notify: reboot
  tags: win_pagefile
```

##### EXPECTED RESULTS

Ansible should apply the change once (if required) and on subsequent runs, show 'OK'.

##### ACTUAL RESULTS

Nothing happens (ie. Ansible returns 'OK' even on the first run so the settings are never applied).

```
TASK [win_pagefile : Set C pagefile, do not override if exists] ********************************************************************************
ok: [host]

```
