### ISSUE TITLE
Meta: end_host in Block being triggered despite tags/when statement

### ISSUE THREAD

**Issue by michaelsmoody** [ansible/ansible#68655]
##### SUMMARY

We have several tasks in our role that perform some checking, and if a specific set of conditions are met, ends the run for that host, via meta: end_host.

We place these tasks inside of a block section. We also have the block statement being part of tags, and the block section also has a when: statement that must match several conditions. While this has tended to work, I have two of these blocks that are always getting triggered. At first glance, this seemed similar to #64558, but the addition of blocks with when statements guided me to open a separate issue. If it is that the root cause is the same, then please feel to merge the issues.

Example playbook below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

meta
when
tags

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/michaelsmoody/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
No Output
```

##### OS / ENVIRONMENT

macOS 10.14.6. Target device Windows Server 2016 (though confirmed on Linux target)
Confirmed against physical server across VPN, and local system. Confirmed against local Virtualbox VM. Confirmed against Vagrant.

##### STEPS TO REPRODUCE

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES; export PYTHONHTTPSVERIFY=0; ansible-playbook -i inventory/hosts -u ansible-control-user -k -l 127.0.0.1 main.yml --tags 'imy-first-tag' -e "someextravariable=content"

```
- block:
    - name: "Perform a set of tasks if conditions are met"
      pause:
        seconds: 5
        prompt: |
          "Several lines of output"
           "Another line of output"
           "We are providing some information to the user here"

    - name: "End the task if the conditions are met after the output is provided"
      meta: end_host

  when: avariablehere is defined and bvariablehere is defined and avariablehere['content']|b64decode|default('avariabledefault') is not search(bvariablehere['content']|b64decode|default('bvariabledefault'))

  tags:
    - my-first-tag
    - my-second-tag
    - my-third-tag
```

##### EXPECTED RESULTS

I expect that when the conditions are met, the play will end for the host. When the conditions are not met, the play will continue for the host.

##### ACTUAL RESULTS

When the conditions are met, the play ends for the host. When the conditions are not met, the play ends for the host. However, the pause/prompt does NOT appear, only the end_host is triggered. Similarly, it does not appear with -vvvvv, only a message about:

META: ending play for 127.0.0.1

```paste below
Relevant output:

META: ending play for 127.0.0.1

```
