### ISSUE TITLE
Misleading example in `Implicit localhost` docs

### ISSUE THREAD

**Issue by rchincholkar** [ansible/ansible#68659]
##### SUMMARY
The documentation of [Implicit localhost](https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html) shows there is a need to define host with specific connection variables as follows:

```
...

hosts:
  localhost:
   vars:
     ansible_connection: local
     ansible_python_interpreter: "{{ansible_playbook_python}}"
```
This does not work, Inventory sync shows below Warning:
```
ERROR    [WARNING]: Skipping unexpected key (localhost) in group (hosts), only "vars",
ERROR    "children" and "hosts" are valid
```

**Proposed Fix:**
We need to modify the example as follows:

```
---
all:
  hosts:
    localhost:
       ansible_connection: local
       ansible_python_interpreter: "{{ansible_playbook_python}}"

```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Implicit ‘localhost’ (Document)

##### ANSIBLE VERSION
NA

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### ADDITIONAL INFORMATION
NA
