### ISSUE TITLE
Ansible creates locked user on Alpine

### ISSUE THREAD

**Issue by FloMiau** [ansible/ansible#68676]
##### SUMMARY
I'm creating an user via ansible. This works on Debian based system like Ubuntu 16, 18, Raspbian, Debian.

The same tasks don't work on Alpine Linux. The user is created but no login is possible. Die user is locked.

This issue is maybe related to #61911 and #66679.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/modules/system/user.py

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/florian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```
I had the same problem on 2.9.5

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=5m
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['timer', 'profile_tasks', 'profile_roles']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_STRATEGY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/local/lib/python3.6/dist-packages/ansible_mitogen/plugins/strategy\nstrategy = mitogen_linear']
```

##### OS / ENVIRONMENT

Target:
Alpine 3.11.5

##### STEPS TO REPRODUCE

```yaml
- name: "create user"
  user:
    name: testuser
    shell: /bin/ash
  become: true

- name: "Set up authorized key"
  authorized_key:
    user: testuser
    state: present
    key: '{{ item }}'
  with_file:
    - ssh.publickey
  become: true
```

##### EXPECTED RESULTS

User is created and it is possible to login.

##### ACTUAL RESULTS

User is created and it is not possible to login.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/system/user.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by saito-hideki** [comment]
Hi,
As far as I know, if you want to create a disabled user account(but not locked) on Alpine,  you need to set `'*'` to the `password` value as follows:

```
    - user:
        name: testuser
        shell: /bin/ash
        password: '*'
      become: true
```

It worked on my end(Alpine 3.11.5. I hope this helps.
