### ISSUE TITLE
to_nice_yaml filter prints an omitted variable

### ISSUE THREAD

**Issue by kopecmartin** [ansible/ansible#68670]
Also reproducible in devel branch.

##### SUMMARY
to_nice_yaml filter is printing out an omitted variable, instead of not printing the omitted variable at all the filter prints out a string representation of omit object

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
to_nice_yaml filter

##### ANSIBLE VERSION
```paste below
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION
```paste below
```

##### OS / ENVIRONMENT
Centos

##### STEPS TO REPRODUCE
Run the following playbook.yaml (ansible-playbook playbook.yaml):
```yaml
---
- hosts: localhost
  vars:
    our_dict:
      first_val: true
      my_var: "{{ not_defined_var | default(omit) }}"
  tasks:
    - name: Override tempestconf profile
      copy:
        content: "{{ our_dict | to_nice_yaml }}"
        dest: "/home/centos/sandbox/output.yaml"
```
Cat the output.yaml file:
```yaml
first_val: true
my_var: __omit_place_holder__fe57ad78bf97c0f91a1875f4d6397c7566fc0059
```

##### EXPECTED RESULTS
omit object is not printed out, the my_var shouldn't be printed at all as it's expected to be omitted
Cat the output.yaml file:
```yaml
first_val: true
```
