### ISSUE TITLE
Maven Artifact Module Fails After Installing Python3

### ISSUE THREAD

**Issue by PStoner3** [ansible/ansible#68686]
##### SUMMARY
maven_artifact fails using ansible 2.9.6 and python 3.6 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
maven-artifact

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
COLOR_CHANGED(/etc/ansible/ansible.cfg) = yellow
COLOR_DEBUG(/etc/ansible/ansible.cfg) = dark gray
COLOR_DEPRECATE(/etc/ansible/ansible.cfg) = purple
COLOR_DIFF_ADD(/etc/ansible/ansible.cfg) = green
COLOR_DIFF_LINES(/etc/ansible/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/etc/ansible/ansible.cfg) = red
COLOR_ERROR(/etc/ansible/ansible.cfg) = red
COLOR_HIGHLIGHT(/etc/ansible/ansible.cfg) = white
COLOR_OK(/etc/ansible/ansible.cfg) = green
COLOR_SKIP(/etc/ansible/ansible.cfg) = cyan
COLOR_UNREACHABLE(/etc/ansible/ansible.cfg) = red
COLOR_VERBOSE(/etc/ansible/ansible.cfg) = bright blue
COLOR_WARN(/etc/ansible/ansible.cfg) = bright purple
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Using maven_artifact to download required jar file from azure artifact repository

```yaml
- hosts: localhost
  connection: local

  tasks:
  - name: Download extension jar
    maven_artifact:
        group_id: "{{ mfg_extensions_jar_group }}"
        artifact_id: "{{ mfg_extensions_jar_name }}"
        version: "{{ mfg_extensions_jar_version }}"
        repository_url: "{{ mfg_artifacts_url }}"
        username: "{{ mfg_artifacts_user }}"
        password: "{{ mfg_artifacts_password }}"
        verify_checksum: never
        dest: "{{ mfg_workdir.path }}/{{ mfg_app_name }}/"
    when:
        - mfg_extensions_jar_group is defined and mfg_extensions_jar_group|trim|length
        - mfg_extensions_jar_name is defined and mfg_extensions_jar_name|trim|length
        - mfg_extensions_jar_version is defined and mfg_extensions_jar_version|trim|length
```

##### EXPECTED RESULTS

Normally this would download the expected jar to later be placed into an archive

##### ACTUAL RESULTS

```paste below
TASK [Download extension jar] **************************************************
task path: /home/***/azagent/_work/r21/a/_mfgdocker/playbooks/prepare_deploy.yml:29
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ...
<127.0.0.1> EXEC /bin/sh -c 'echo ~... && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061 `" && echo ansible-tmp-1585937008.9940004-57614064643061="` echo /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/packaging/language/maven_artifact.py
<127.0.0.1> PUT /home/***/.ansible/tmp/ansible-local-20567jq4z5nax/tmpg2d1fxul TO /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061/AnsiballZ_maven_artifact.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061/ /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061/AnsiballZ_maven_artifact.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/bin/python3 /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061/AnsiballZ_maven_artifact.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/***/.ansible/tmp/ansible-tmp-1585937008.9940004-57614064643061/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_maven_artifact_payload_nsowczm2/ansible_maven_artifact_payload.zip/ansible/module_utils/urls.py", line 1494, in fetch_url
    unix_socket=unix_socket, ca_path=ca_path)
  File "/tmp/ansible_maven_artifact_payload_nsowczm2/ansible_maven_artifact_payload.zip/ansible/module_utils/urls.py", line 1390, in open_url
    unredirected_headers=unredirected_headers)
  File "/tmp/ansible_maven_artifact_payload_nsowczm2/ansible_maven_artifact_payload.zip/ansible/module_utils/urls.py", line 1294, in open
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1208, in http_error_401
    host, req, headers)
  File "/usr/lib64/python3.6/urllib/request.py", line 1092, in http_error_auth_reqed
    " the following scheme: '%s'" % scheme)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "artifact_id": "amer_mfgweb_ext",
            "attributes": null,
            "backup": null,
            "classifier": "",
            "content": null,
            "delimiter": null,
            "dest": "/tmp/ansible.iezktzanwork/mfgweb/",
            "directory_mode": null,
            "extension": "jar",
            "follow": false,
            "force": null,
            "group": null,
            "group_id": "com.***",
            "headers": null,
            "http_agent": "Ansible 2.9.6 maven_artifact",
            "keep_name": false,
            "mode": null,
            "owner": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "regexp": null,
            "remote_src": null,
            "repository_url": "https://***/***/_packaging/***/maven/v1",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "timeout": 10,
            "unsafe_writes": null,
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "***",
            "username": "***",
            "validate_certs": true,
            "verify_checksum": "never",
            "version": "2020.04.2"
        }
    },
    "msg": "AbstractDigestAuthHandler does not support the following scheme: 'Bearer'",
    "status": -1,
    "url": "https://***/***/_packaging/***/maven/v1/com/***/amer_mfgweb_ext/2020.04.2/amer_mfgweb_ext-2020.04.2.jar"
}
```

**Comment by jpdias92** [comment]
I'm having the same problem.

Using `lxml-4.5.0` and the following ansible version.

### Ansible Version
```
ansible 2.9.2
python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

Trying to connect to a Maven repo hosted in Azure DevOps.

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jpdias92** [comment]
@PStoner3  I solved the problem by passing the authorization HTTP header:

```
    - name: Download artifacts
      maven_artifact:
        repository_url: "{{ repository_url }}"
        group_id: "{{ group_id }}"
        artifact_id: "{{ artifact_id }}"
        version: "{{ version }}"
        verify_checksum: never  # Cannot be used due to bug in checksum, opened issue https://github.com/ansible-collections/community.general/issues/186
        headers:
          Authorization: "Basic {{ (username + ':' + password) | b64encode }}"
        dest: "/tmp/"
        keep_name: true
```

Note also the `verify_checksum` if you are using Azure DevOps as I am, I think there is a mismatch between the case used by Azure DevOps and Ansible when calculating the md5 hash for the checksum, one calculates the hash in lower case and the other in upper case. Since the comparison in Ansible is case sensitive, the checksum verification is not reliable and often results in errors. I opened an issue for this: https://github.com/ansible-collections/community.general/issues/186
