### ISSUE TITLE
netconf_config on iosxr

### ISSUE THREAD

**Issue by geordish** [ansible/ansible#68682]
##### SUMMARY
I'm trying to create a simple playbook using iosxr and netconf, and I'm experiencing issues. Ansible errors out when trying to log into the netconf SSH session.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netconf_config

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = None
  configured module search path = [u'/home/dave/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dave/.local/lib/python2.7/site-packages/ansible
  executable location = /home/dave/.local/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```
Nothing
```

##### OS / ENVIRONMENT
Cisco IOS XR Software, Version 6.6.3

##### STEPS TO REPRODUCE

```yaml
---
- name: Configure Hostname on IOS XR
  hosts: all
  connection: netconf

  tasks:
    - name: Configure IS-IS
      netconf_config:
        content: |
          <host-names xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-shellutil-cfg">
            <host-name>Test</host-name>
          </host-names>
```

##### EXPECTED RESULTS

The device being logged into and configured.

##### ACTUAL RESULTS

https://gist.github.com/geordish/c6d4d9c39f556861b7ad97a6ebb79c3e
https://gist.github.com/geordish/533c58158a4a17156b18adebd044583b
