### ISSUE TITLE
docker_login using TLS-enabled docker hosts is failing

### ISSUE THREAD

**Issue by jstewart612** [ansible/ansible#68693]
##### SUMMARY

docker_login using TLS-enabled docker hosts is failing

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_login

##### ANSIBLE VERSION

```paste below
2.9.5
```

##### OS / ENVIRONMENT

AWX 10.0.0

##### STEPS TO REPRODUCE

```yaml
  docker_login:
    ca_cert: "{{ docker_tls_ca_cert }}"
    client_cert: "{{ docker_tls_cert }}"
    client_key: "{{ docker_tls_key }}"
    debug: "yes"
    docker_host: "{{ docker_host }}"
    registry: "https://index.docker.io/v1/"
    tls: "yes"
    tls_hostname: "{{ docker_tls_domain }}"
    username: "{{ docker_user_name }}"
    password: "{{ docker_user_pass }}"
```

##### EXPECTED RESULTS

It connects to the remote docker host and runs a docker login.

##### ACTUAL RESULTS

```paste below
TASK [docker-swarm-deploy : docker | log into the registry] ********************
fatal: [dve2-vm-ci-app-manager001 -> localhost]: FAILED! => {"changed": false, "msg": "TLS config error: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details."}
```
