### ISSUE TITLE
Plugin 'mount' doesn't support loop with 'with_items' correctly

### ISSUE THREAD

**Issue by benocms** [ansible/ansible#68722]
##### SUMMARY
When creating multiple mount points using a loop, the mount points are not entered in /etc/fstab. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- mount

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```
none
```

##### OS / ENVIRONMENT

CentOS 8 - 4.18.0-80.11.2.el8_0.x86_64

##### STEPS TO REPRODUCE

```yaml

mounts: 
  - name: mount1    
    src: //10.1.1.1/testa
    path: /mnt/testa
    opts: domain=ad,username=test,password=test
  - name: mount2    
    src: //10.1.1.1/testb
    path: /mnt/testb
    opts: domain=ad,username=test,password=test

- name: Mount shares
  mount:
    fstype: cifs
    opts: "{{ item.opts }}"
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: mounted
  become: yes    
  with_items:
     "{{ mounts }}"  
```

##### EXPECTED RESULTS
Added mount points in /etc/fstab.

##### ACTUAL RESULTS
The mounts are created and available. But no entries are made in /etc/fstab.
