### ISSUE TITLE
The type being used for parsing should be uint32, not int32

### ISSUE THREAD

**Issue by wsteinford** [ansible/ansible#68732]
#### ISSUE TYPE
Bug Report

#### ANSIBLE VERSION
ansible 2.9

##### OS / ENVIRONMENT
Deploying to Windows host

#### SUMMARY
https://github.com/ansible/ansible/blob/18a2183a0be3896f28b9fc77f90563585916e98c/lib/ansible/modules/windows/win_package.ps1#L65

This should use uint32 because the function [Ansible.Process.ProcessUtil]::CreateProcess returns uint32.  CreateProcess calls, WaitProcess, which gets the result code on this line:
https://github.com/ansible/ansible/blob/18a2183a0be3896f28b9fc77f90563585916e98c/lib/ansible/module_utils/csharp/Ansible.Process.cs#L403

It causes a failure if the expected value exceeds 31 bits, though it should be allowed to reach 32 bits.

#### STEPS TO REPRODUCE
1. Add a task like this:
```
- name: Run installer
  win_package:
    path: "installer.msi"
    product_id: "{e2b3431b-3f10-4f53-abdd-d3ff3feaa1ad}"
    # This package usually returns 3221225477 (access exception) when it succeeds installing
    expected_return_code: [0, 3010, 3221225477]
```

#### EXPECTED RESULTS
The installer runs and returns 3221225477, and Ansible accepts it as OK

#### ACTUAL RESULTS
Ansible returns the message:
```
fatal: [hostname]: FAILED! => {"changed": false, "msg": "failed to parse expected return code 3221225477 as an integer", "reboot_required": false}
```
