### ISSUE TITLE
Harmonizing default search path for copy command

### ISSUE THREAD

**Issue by jkeskikangas** [ansible/ansible#6874]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.3
##### Environment:

Running from OS X, managing Ubuntu precise64
##### Summary:

I recently wrote a role [ansible-rbenv](https://github.com/leonidas/ansible-rbenv). The role provides default `.gemrc` and copies it to the target host. I'd like enable users to override it by providing their version in `playbook/files/.gemrc` 
##### Steps To Reproduce:

I created a test playbook.

```
git clone git@github.com:pyykkis/ansible-copy.git
cd ansible-copy
ansible-playbook -i hosts test.yml
```
##### Expected Results:

File is copied from `files/config.txt` to `result/config.txt`
##### Actual Results:

File is copied from `roles/copy/files/config.txt` to `result/config.txt`. If `roles/copy/files/config.txt` is removed, playbook fails with

```
fatal: [localhost] => input file not found at /Users/pyykkis/work/ansible-copy/roles/copy/files/config.txt or /Users/pyykkis/work/ansible-copy/config.txt
```

As a workaround, I changed order with `with_first_found`, but of course, that's a little cumbersome to repeat for every config file (databases, web servers, etc)

```
- name: Copy config.txt to the working directory
  copy: src={{ item }} dest=result/config.txt
  with_first_found:
    - ../../../files/config.txt
    - config.txt
```
