### ISSUE TITLE
rsplit() stopped working

### ISSUE THREAD

**Issue by vladimirtiukhtin** [ansible/ansible#68747]
##### SUMMARY
rsplit() is supposed to do revers splitting in oppose to split(), but it currently copying split() behaviour

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
jinja rsplit()

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /Users/vtiukhtin/.ansible.cfg
  configured module search path = ['/Users/vtiukhtin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:29:30) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### OS / ENVIRONMENT
Tested on MacOS and inside Debian and CentOS containers

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  connection: local
  vars:
    test: "0-1-2-3-4-5-6-7-8-9"
  tasks:
    - debug: msg="{{ test.rsplit('-')[0] }}"
```

##### EXPECTED RESULTS
```
TASK [debug] **********************************************************************************************
ok: [localhost] => {
    "msg": "9"
}
```

##### ACTUAL RESULTS
```
TASK [debug] **********************************************************************************************
ok: [localhost] => {
    "msg": "0"
}
```
