### ISSUE TITLE
lineinfile, not creating file when it doesn't exist, and not updating the file with new added / removed / updated line.

### ISSUE THREAD

**Issue by ernestocasas** [ansible/ansible#68751]
##### SUMMARY

First I want to say this was working fine on Ansible 2.8.

Since upgraded to 2.9, lineinfile module is no creating any file with create=yes, neither updating existing file, even the result show message "line added"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lineinfile

##### ANSIBLE VERSION

```ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/                                                                                                             usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (R                                                                                                             ed Hat 4.8.5-39)

```

##### CONFIGURATION

```empty
```

##### OS / ENVIRONMENT

```
---
  # This playbook consolidates all data needed to create or update the results file for
  # final generation of data and materials for students
   - name: Get Ingate SIParator unit information
     ig_unit_information:
       client:
         version: v1
         scheme: https
         validate_certs: no
         address: "{{ ec2_var | json_query('instances[].private_ip | [0]') }}"
         username: ecasas
         password: kF37MN9f
     register: ig_var
   - set_fact:
      data_image_id: "{{ ec2_var | json_query('instances[].image_id') }}"
      data_outside_ip: "{{ ec2_var | json_query('instances[].private_ip') }}"
      data_securitygr: "{{ ec2_var | json_query('instances[].groups[]') }}"
      data_instance_id: "{{ ec2_var | json_query('instances[].id | [0]') }}"
      data_tag_domain: "{{ ec2_var | json_query('instances[].tags.domain') }}"
      data_tag_class: "{{ ec2_var | json_query('instances[].tags.class') }}"
      data_tag_name: "{{ ec2_var | json_query('instances[].tags.Name') }}"
      data_placement: "{{ ec2_var | json_query('instances[].placement') }}"
      data_instance_type: "{{ ec2_var | json_query('instances[].instance_type') }}"
      data_public_ip: "{{ eip | json_query('public_ip') }}"
      data_inside_ip: "{{ eni_var_2 | json_query('interface.private_ip_address') }}"
      data_product: "{{ ig_var | json_query('*.product') }}"
      data_install_id: "{{ ig_var | json_query('*.installid') }}"
      data_unitname: "{{ ig_var | json_query('*.unitname') }}"
      data_macaddr: "{{ ig_var | json_query('*.macaddr') }}"
      data_version: "{{ ig_var | json_query('*.version') }}"
      data_did: "{{ item.did_var }}"
      data_ext_range: "{{ item.ext_var }}"
      data_colon: ", "
# here we create the final file <name>.csv.
# name will be composed of "class_data_"+ data_tag_class + ".csv"
   - name: Line in File to add host to hosts_sbc_training
     become_method: su
     lineinfile:
        dest: "/var/lib/awx/projects/SiparatorTraining/hosts/test"
        create: yes
        regexp: ".*{{ data_tag_domain }}.*"
        state: present
        line: "{{ data_tag_domain }} {{ data_colon }} {{ data_instance_id }} {{ data_colon }} {{ data_public_ip }} {{ data_colon }} {{ data_did }} {{ data_colon }} {{ data_tag_name }} {{ data_colon }} {{ data_ext_range }} {{ data_colon }} {{ data_outside_ip }} {{ data_colon }} {{ data_inside_ip }} {{ data_colon }} {{ data_securitygr }} {{ data_colon }} {{ data_tag_class }} {{ data_colon }} {{ data_tag_name }} {{ data_colon }} {{ data_placement }} {{ data_colon }} {{ data_instance_type }} {{ data_colon }} {{ data_product }} {{ data_colon }} {{ data_install_id }} {{ data_colon }} {{ data_unitname }} {{ data_colon }} {{ data_macaddr }} {{ data_colon }} {{ data_version }}"
        backup: yes
     register: line_var

```

##### EXPECTED RESULTS

Test file created with the new line added in:
/var/lib/awx/projects/SiparatorTraining/hosts/test

##### ACTUAL RESULTS

Only result displayed, does not seem to report any file creation:
```
{
    "_ansible_no_log": false,
    "changed": true,
    "invocation": {
        "module_args": {
            "directory_mode": null,
            "force": null,
            "remote_src": null,
            "dest": "/var/lib/awx/projects/SiparatorTraining/hosts/test",
            "selevel": null,
            "backrefs": false,
            "insertafter": null,
            "follow": false,
            "owner": null,
            "path": "/var/lib/awx/projects/SiparatorTraining/hosts/test",
            "line": "[u'https://g01siparator.ingatelabs.com'] ,  i-0ec73578bba408b3c ,  54.164.31.176 ,  9548667650 ,  [u'G01 Group'] ,  1011-1014 ,  [u'10.0.0.104'] ,  10.0.1.47 ,  [{u'sg-d649dca4': u'INGATE SIParator SG'}] ,  [u'Ingate hands on training'] ,  [u'G01 Group'] ,  [u'us-east-1a'] ,  [u't2.micro'] ,  [u'Software SIParator/Firewall'] ,  [u'03779d47d5c180044f07202227ab4be5de18904c'] ,  [u'714F-063D-DA7E-731F-1655-E364'] ,  [u'12:53:e1:be:18:9f'] ,  [u'6.2.2']",
            "validate": null,
            "src": null,
            "group": null,
            "insertbefore": null,
            "unsafe_writes": null,
            "delimiter": null,
            "create": true,
            "seuser": null,
            "serole": null,
            "regexp": ".*[u'https://g01siparator.ingatelabs.com'].*",
            "content": null,
            "state": "present",
            "mode": null,
            "firstmatch": false,
            "attributes": null,
            "backup": true,
            "setype": null
        }
    },
    "diff": [
        {
            "after": "[u'https://g01siparator.ingatelabs.com'] ,  i-0ec73578bba408b3c ,  54.164.31.176 ,  9548667650 ,  [u'G01 Group'] ,  1011-1014 ,  [u'10.0.0.104'] ,  10.0.1.47 ,  [{u'sg-d649dca4': u'INGATE SIParator SG'}] ,  [u'Ingate hands on training'] ,  [u'G01 Group'] ,  [u'us-east-1a'] ,  [u't2.micro'] ,  [u'Software SIParator/Firewall'] ,  [u'03779d47d5c180044f07202227ab4be5de18904c'] ,  [u'714F-063D-DA7E-731F-1655-E364'] ,  [u'12:53:e1:be:18:9f'] ,  [u'6.2.2']\n",
            "after_header": "/var/lib/awx/projects/SiparatorTraining/hosts/test (content)",
            "before_header": "/var/lib/awx/projects/SiparatorTraining/hosts/test (content)",
            "before": ""
        },
        {
            "after_header": "/var/lib/awx/projects/SiparatorTraining/hosts/test (file attributes)",
            "before_header": "/var/lib/awx/projects/SiparatorTraining/hosts/test (file attributes)"
        }
    ],
    "backup": "",
    "msg": "line added"
}
```
