### ISSUE TITLE
gcp_compute_instance doesn't attach persistent disk to already launched instance

### ISSUE THREAD

**Issue by dsavov** [ansible/ansible#68766]
##### SUMMARY

gcp_compute_instance doesn't attach persistent disk to already created instance.
When instance is initially created with persistent disk it's being attached.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gcp_compute_instance
##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/***/***/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/***/***/ansible.cfg) = -o "ControlMaster=auto" -o "ControlPersist=3600s"
ANSIBLE_SSH_CONTROL_PATH(/home/***/***/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_RETRIES(/home/***/***/ansible.cfg) = 5
```

##### OS / ENVIRONMENT

Ubuntu 18.04.4 LTS

##### STEPS TO REPRODUCE

Launch instance
Create persistent disk
Try to attach persistent disk

```yaml
    - name: main.yml | launch gce instances
      local_action:
        module: gcp_compute_instance
        # Account variables
        project: "{{ _project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        # Environments variables
        name: "{{ instance_name }}"
        machine_type: "{{ _machine_type }}"
        zone: "{{ _zone }}"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ system_disk_result }}"
        network_interfaces:
          - network: "{{ system_network_result }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ external_ip_address_result }}"
                type: 'ONE_TO_ONE_NAT'
        tags:
          items: "{{ _tags }}"
        state: present
      register: instance_result

    - name: main.yml | create additional disk
      local_action:
        module: gcp_compute_disk
        # Account variables
        project: "{{ _project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        # Environments variables
        name: "{{ persistent_disk_name }}"
        type: "{{ persistent_disk_type }}"
        size_gb: "{{ persistent_disk_size }}"
        labels:
          instance: "{{ instance_name }}"
        zone: "{{ _zone }}"
        state: present
      register: persistent_disk_result

    - name: main.yml | attach persistent disk
      local_action:
        module: gcp_compute_instance
        # Account variables
        project: "{{ _project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        # Environments variables
        name: "{{ instance_name }}"
        machine_type: "{{ _machine_type }}"
        zone: "{{ _zone }}"
        disks:
          - auto_delete: false
            boot: false
            interface: 'SCSI'
            mode: 'READ_WRITE'
            device_name: "{{ persistent_disk_name }}"
            source: "{{ persistent_disk_result }}"
            type: "PERSISTENT"
        state: present
      register: attach_persistent_disk_result
```

##### EXPECTED RESULTS

Persistent disk is attached to instance

##### ACTUAL RESULTS

Persistent disk is not attached to instance when I check in GCP portal

```paste below
TASK [main.yml | attach persistent disk] **************************************************************************************************************************************************************************************************************************************
task path: /home/***/***/gcp-deploy-instance.yml:141
Wednesday 08 April 2020  11:47:07 +0300 (0:00:04.605)       0:00:26.557 ******* 
Using module file /home/***/***/env/lib/python3.6/site-packages/ansible/modules/cloud/google/gcp_compute_instance.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/home/***/***/env/bin/python3.6 && sleep 0'
ok: [localhost -> localhost] => changed=false 
  cpuPlatform: Intel Broadwell
  creationTimestamp: '2020-04-08T01:46:54.844-07:00'
  deletionProtection: false
  disks:
  - autoDelete: true
    boot: true
    deviceName: persistent-disk-0
    diskSizeGb: '35'
    index: 0
    interface: SCSI
    kind: compute#attachedDisk
    mode: READ_WRITE
    source: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a/disks/test2-instance-name
    type: PERSISTENT
  fingerprint: *********
  id: *********
  invocation:
    module_args:
      auth_kind: serviceaccount
      can_ip_forward: null
      deletion_protection: null
      disks:
      - auto_delete: false
        boot: false
        device_name: test2-instance-name-disk-01
        disk_encryption_key: null
        index: null
        initialize_params: null
        interface: SCSI
        mode: READ_WRITE
        source:
          changed: true
          creationTimestamp: '2020-04-08T01:47:04.551-07:00'
          failed: false
          id: *********
          kind: compute#disk
          labelFingerprint: *********
          labels:
            instance: test2-instance-name
          name: test2-instance-name-disk-01
          physicalBlockSizeBytes: '4096'
          selfLink: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a/disks/test2-instance-name-disk-01
          sizeGb: '30'
          status: READY
          type: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a/diskTypes/pd-standard
          zone: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a
        type: PERSISTENT
      env_type: null
      guest_accelerators: null
      hostname: null
      labels: null
      machine_type: n1-standard-2
      metadata: null
      min_cpu_platform: null
      name: test2-instance-name
      network_interfaces: null
      project: *********
      scheduling: null
      scopes:
      - https://www.googleapis.com/auth/compute
      service_account_contents: null
      service_account_email: null
      service_account_file: .google/test2-cluster-name.json
      service_accounts: null
      shielded_instance_config: null
      state: present
      status: null
      tags: null
      zone: europe-west2-a
  kind: compute#instance
  labelFingerprint: *********
  machineType: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a/machineTypes/n1-standard-2
  metadata: {}
  name: test2-instance-name
  networkInterfaces:
  - accessConfigs:
    - kind: compute#accessConfig
      name: External NAT
      natIP: *********
      networkTier: PREMIUM
      type: ONE_TO_ONE_NAT
    fingerprint: *********
    kind: compute#networkInterface
    name: nic0
    network: https://www.googleapis.com/compute/v1/projects/***/global/networks/default
    networkIP: *********
    subnetwork: https://www.googleapis.com/compute/v1/projects/***/regions/europe-west2/subnetworks/default
  scheduling:
    automaticRestart: true
    onHostMaintenance: MIGRATE
    preemptible: false
  selfLink: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a/instances/test2-instance-name
  startRestricted: false
  status: RUNNING
  tags:
    fingerprint: *********
    items:
    - prometheus
    - webcp
  zone: https://www.googleapis.com/compute/v1/projects/***/zones/europe-west2-a
```
