### ISSUE TITLE
AWS elb_target_group requires protocol, port when state is absent

### ISSUE THREAD

**Issue by TC-robV** [ansible/ansible#68760]
##### SUMMARY

when trying to delete a target group via elb_target_group it throws 
target_type is instance but all of the following are missing: protocol, port.
double checked and eve in the docs it says those are only needed if state is present

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

elb_target_group
##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /Users/xx/.ansible.cfg
  configured module search path = ['/Users/xx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xx/python-env/ansible2.9/lib/python3.7/site-packages/ansible
  executable location = /Users/xx/python-env/ansible2.9/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]

```

##### OS / ENVIRONMENT

macos 10.15.4

##### STEPS TO REPRODUCE

```
- name: Delete Target Groups
  elb_target_group:
    region: "{{ tt_region }}"
    profile: "{{ profile }}"
    name: "{{ tt_env_short }}-{{ item.name }}"
    vpc_id: "{{ vpc.vpcs[0].id }}"
    state: absent

```

##### EXPECTED RESULTS

delete with no error.

##### ACTUAL RESULTS

it throws an error about needed the protocol and port during state=absent.
if i put in random protocol and port it works fine.
