### ISSUE TITLE
Action plugin in dellemc_networking.os10 collections not picked unless ANSIBLE_NETWORK_GROUP_MODULES is set

### ISSUE THREAD

**Issue by parkrish** [ansible/ansible#68769]
##### SUMMARY
An action plugin with name os10.py is defined in collections dellemc_networking.os10(https://github.com/ansible-collections/dellemc_networking.os10)

When using a role defined in the collections in the playbook, the os10.py action plugin in the  collections is not getting used.Instead only normal action plugin in core module is getting used.

Only when the environment variable ANSIBLE_NETWORK_GROUP_MODULES is set to 'os10', the os10.py action plugin gets set.

The test was done in Ansible 2.9.4 as well as latest devrel code(Code as on 7th April IST) and in both the case the issue is observed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/executor/task_executor.py Function: _get_action_handler

##### ANSIBLE VERSION

The test was done in Ansible 2.9.4 as well as latest devrel code(Code as on 7th April IST) and in both the case the issue is observed.

##### STEPS TO REPRODUCE
1. Install dellemc_networking.os10 collections 
ansible-galaxy collection install dellemc_networking.os10

2. Contents of playbook, host_vars files used
```
playbook.yaml
===========
- hosts: os10_sw1
  connection: network_cli
  collections:
    - dellemc_networking.os10
  roles:
    - os10_vlan

host_vars/os10_sw1.yaml
===================
hostname: os10_sw1
# parameters for connection type network_cli
ansible_ssh_user: xxxx
ansible_ssh_pass: xxxx
ansible_network_os: dellemc_networking.os10.os10

os10_vlan:
    vlan 100:
      description: "Blue"
      tagged_members:
          - port: ethernet 1/1/32
            state: present
          - port: ethernet 1/1/31
            state: present
      untagged_members:
          - port: ethernet 1/1/30
            state: present
          - port: ethernet 1/1/29
            state: present
      state: present

inventory.yaml
=================
[os10]
os10_sw1 ansible_host=100.104.28.119
```
3. Execute playbook
ansible-playbook -i inventory.yaml playbook.yaml

The playbook fails as the Action plugin os10.py did not load.Instead the normal Action plugin got loaded.
Note: The os10_vlan role internally invokes the os10_config module as below
- name: "Provisioning VLAN configuration for os10"
   os10_config:
      src: os10_vlan.j2

##### EXPECTED RESULTS
The os10.py Action plugin should get loaded and the playbook should pass.

##### ACTUAL RESULTS
The playbook fails as the Action plugin os10.py did not load.Instead the normal Action plugin got loaded.

Root cause:

In Ansible(2.9.4),  file: lib/ansible/executor/task_executor.py Function: _get_action_handler
We have the following code that loads the appropriate Action plugin for the module used in the playbook
module_prefix = self._task.action.split('.')[-1].split('_')[0]
collections = self._task.collections

if self._shared_loader_obj.action_loader.has_plugin(self._task.action, collection_list=collections):
            handler_name = self._task.action
        # FIXME: is this code path even live anymore? check w/ networking folks; it trips sometimes when it shouldn't
elif all((module_prefix in C.NETWORK_GROUP_MODULES, module_prefix in self._shared_loader_obj.action_loader)):
            handler_name = module_prefix
else:
            # FUTURE: once we're comfortable with collections impl, preface this action with ansible.builtin so it can't be hijacked
            handler_name = 'normal'
            collections = None  # until then, we don't want the task's collection list to be consulted; use the builtin

The first IF statement, checks for a Action plugin with the same name as module name(os10_config) in the collection. This IF check fails ,since our plugin is ‘os10’ and not ‘os10_config’
The second ELIF statement, checks if the module prefix(‘os10’) is part of NETWORK_GROUP_MODULES and if so, searches it for Action plugin in collections.
The Ansible maintains only the following list of prefixes in NETWORK_GROUP_MODULES by default.Since ‘os10’ prefix is not part of this list,
the ELIF check also fails. Eventually we end up loading ‘normal’ plugin.

File: : lib/ansible/config/base.yml
NETWORK_GROUP_MODULES:
  name: Network module families
  default: [eos, nxos, ios, iosxr, junos, enos, ce, vyos, sros, dellos9, dellos10, dellos6, asa, aruba, aireos, bigip, ironware, onyy
x, netconf]
  description: 'TODO: write it'

Possible fix:
==========
Fix1
Including os10 in the lib/ansible/config/base.yaml should fix this issue.

Fix 2:
In the function _get_action_handler, introduce a new elif case, which will search for module_prefix(‘os10’) for the Action plugin in the collection.

elif self._shared_loader_obj.action_loader.has_plugin(module_prefix, collection_list=collections):
            #Search for the module_prefix for a Action plugin in collection
            handler_name = module_prefix

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@parkrish: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
cc @Qalthos 

!component =lib/ansible/executor/task_executor.py

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/executor/task_executor.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by parkrish** [comment]
I'm observing one more issue with respect to loading Action plugin. With the following playbook, the backup is not happening as the action plugin is not getting load properly.

---
- hosts: os10_sw1
  connection: network_cli
  gather_facts: No
  vars:
    output_dir: "/root/switch_dump/"

  tasks:
  - name: dump switch config
    dellemc_networking.os10_config:
      backup: yes
      backup_options:
        filename: 'my.cfg'
        dir_path: "{{ output_dir }}"

However, if refer the collections earlier and use only os10_config as module name , the action plugin is getting loaded properly and the backup file creation works fine.

The backup action happens finely for the following playbook.

---
- hosts: os10_sw1
  connection: network_cli
  gather_facts: No
  vars:
    output_dir: "/root/switch_dump/"
  collections:
    - dellemc_networking.os10
  tasks:
  - name: dump switch config
    os10_config:
      backup: yes
      backup_options:
        filename: 'my.cfg'
        dir_path: "{{ output_dir }}"

**Comment by sivel** [comment]
bot_skip

(to prevent un-labeling)

**Comment by ganeshrn** [comment]
The WIP PR https://github.com/ansible/ansible/pull/67684 adds the capability for action plugin redirection within the collection.
You can add the redirection info within your collection at the location (subject to change based on changes/updates in the PR #67684)

`<collection>/meta/routing.yml`
eg content for redirection within collection
```
plugin_routing:
  action:
    os10_config:
      redirect: dellemc_networking.os10.os10
```
