### ISSUE TITLE
win_lineinfile unable to read file in use by another process

### ISSUE THREAD

**Issue by brilong** [ansible/ansible#68777]
##### SUMMARY
Using win_lineinfile to search for a string in a logfile when that logfile is being actively written to by another process is not possible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_lineinfile

##### ANSIBLE VERSION

```paste below
ansible 2.8.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/users/brilong.adm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL 7

##### STEPS TO REPRODUCE

```yaml
  - name: sccm | Check SCCM log for exit code 0
    win_lineinfile:
      path: C:\Windows\ccmsetup\Logs\ccmsetup.log
      line: "CcmSetup is exiting with return code 0"
      state: present
    retries: 30
    delay: 15
    check_mode: yes
```

##### EXPECTED RESULTS

I expect win_lineinfile with check_mode: yes to check over and over for the presence of line without opening the file for writing.

##### ACTUAL RESULTS

win_lineinfile is unable to open the file since it is actively being written by another process.

```paste below
Unhandled exception while executing module: Exception calling "ReadAllLines" with "2" argument(s): "The process cannot access the file 'C:\Windows\ccmsetup\Logs\ccmsetup.log' because it is being used by another process."
```
