### ISSUE TITLE
gitlab_group module ignores group description on group creation

### ISSUE THREAD

**Issue by gustavomcarmo** [ansible/ansible#68778]
##### SUMMARY
The gitlab_group module ignores the description parameter for creating the group in GitLab. However, the description parameter is considered for updating the group. The module has to be executed twice in order to have the group properly created.

[See the code.](https://github.com/ansible/ansible/blob/9e3ccd64b6a233390cd70c314193b6ba1aacfe21/lib/ansible/modules/source_control/gitlab_group.py#L180)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gitlab_group

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /c/Users/142936/projects/op/dai/config/ansible.cfg
  configured module search path = ['/home/gustavomcarmo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gustavomcarmo/.local/lib/python3.6/site-packages/ansible
  executable location = /home/gustavomcarmo/.local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### CONFIGURATION
```
DEFAULT_CALLBACK_WHITELIST(/c/Users/142936/projects/op/dai/config/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/c/Users/142936/projects/op/dai/config/ansible.cfg) = ['/c/Users/142936/projects/op/dai/config/inventory.yml']
DEFAULT_VAULT_PASSWORD_FILE(/c/Users/142936/projects/op/dai/config/ansible.cfg) = /c/Users/142936/projects/op/dai/config/vault-password-file
INVENTORY_ENABLED(/c/Users/142936/projects/op/dai/config/ansible.cfg) = ['yaml']
```

##### OS / ENVIRONMENT
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

##### STEPS TO REPRODUCE
```yaml
- name: "Create GitLab Group"
  gitlab_group:
    server_url: https://gitlab.example.com/
    validate_certs: True
    api_username: dj-wasabi
    api_password: "MySecretPassword"
    name: my_first_group
    path: my_first_group
    description: My First Group
    state: present
```

##### EXPECTED RESULTS
Group created with the description: "My First Group".

##### ACTUAL RESULTS
Group created with no description.
