### ISSUE TITLE
netconf ansible_connection does not use ansible_private_key_file

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#68776]
##### SUMMARY
When using the ```netconf``` connection type, ansible tries to connect with the user's private key(s) even when ```ansible_private_key_file``` is set to another specific file.
No such issue when using the ```network_cli``` connection type with ```ansible_ssh_private_key_file```.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netconf

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
controller host: Ubuntu focal 20.04
```

##### STEPS TO REPRODUCE
```
- name: Testing which private SSH key is used by network_cli connection
  hosts:
        - all
  vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_ssh_private_key_file: "{{ private_key_file }}"
        ansible_user: "{{ username }}"
  tasks:
        - name: Getting all facts
          ios_facts:
                gather_subset: all
          
- name: Testing which private SSH key is used by netconf connection
  hosts:
        - all
  vars:
        ansible_connection: netconf
        ansible_network_os: ios
        ansible_private_key_file: "{{ private_key_file }}"
        ansible_user: "{{ username }}"
  tasks:
        - name: Getting running configuration and state data
          netconf_get:
```

##### EXPECTED RESULTS
Both plays should use the same SSH private key. 

##### ACTUAL RESULTS

1. The first play uses the correct SSH key matching ```private_key_file```.
2. The second play does **not** use the SSH key matching ```private_key_file```. and requests the password for another SSH private key.
