### ISSUE TITLE
Add an option to skip execution of rescue part

### ISSUE THREAD

**Issue by Ahmed-Hussein-Karam** [ansible/ansible#68797]
##### SUMMARY

When running an Ansible playbook, it might be interesting to skip the execution of all rescue tasks (for all `block - rescue` statements) across the playbook .

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-playbook

##### ADDITIONAL INFORMATION

To achieve this, we can add an additional option `--no-rescue` to the `ansible-playbook` command. The below example illustrate the idea:

```yaml
block:
    <set_of_block_tasks>
rescue:
    <set_of_rescue_tasks>
```
Then we can run the playbook like this: `sudo ansible-playbook <file_name.yaml> --no-rescue` to skip the `<set_of_rescue_tasks>` part.
