### ISSUE TITLE
SSL issue running fortios_firewall_adress

### ISSUE THREAD

**Issue by greenspartan** [ansible/ansible#68809]
**ISSUE TYPE**

Hello,

Using Ansible via Tower, we are not able to create an object on Fortigate 240D firewall using  fortios_firewall_adress module.
Playbook ends each time with same error (see below).

**COMPONENT NAME**
Ansible: 2.9.6
Python 3.6
FortiosAPI: 1.0.1
Ansible module : fortios_firewall_adress
Fortigate firewall is 240D running on 6.0.6

##### ANSIBLE VERSION
```
Ansible version is  2.9.6
```

##### OS / ENVIRONMENT

Tower is running on CentOS Linux release 7.7.1908

##### STEPS TO REPRODUCE

To reproduce you can play playbook below

```
---                                                                               

- hosts: localhost
  gather_facts: False
  vars:                                                                           
   host: "10.109.109.1"                                                           
   username: "fakeusername"                                                              
   password: "fakepassword"                                                          
   vdom: "root"                                                            
  tasks:                                                                          
  - name: Configure IPv4 addresses.                                               
    fortios_firewall_address:                                                     
      host:  "{{ host }}"                                                         
      username: "{{ username }}"                                                  
      password: "{{ password }}"                                                  
      vdom:  "{{ vdom }}"                                                         
      state: "present"                                                            
      firewall_address:                                                           
        name: "TOWER_TEST"                                                
        subnet: "1.2.3.4 255.255.255.255"
        comment: "TOWER_TEST_COMMENT"		
```

##### EXPECTED RESULTS

Object to be created in the firewall.

##### ACTUAL RESULTS

```

PLAY [localhost] ***************************************************************

TASK [fortios_tasks : CREATE OBJECT ON FORTIGATE] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.109.109.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\\n  InsecureRequestWarning,\\nTraceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586426295.6123304-22106732036127/AnsiballZ_fortios_firewall_address.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586426295.6123304-22106732036127/AnsiballZ_fortios_firewall_address.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1586426295.6123304-22106732036127/AnsiballZ_fortios_firewall_address.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.network.fortios.fortios_firewall_address', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 205, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/usr/lib64/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 570, in <module>\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 560, in main\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 462, in fortios_firewall\\n  File \\"/tmp/ansible_fortios_firewall_address_payload_o04mvvs_/ansible_fortios_firewall_address_payload.zip/ansible/modules/network/fortios/fortios_firewall_address.py\\", line 445, in firewall_address\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 422, in set\\n    mkey = self.get_mkey(path, name, data, vdom=vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 233, in get_mkey\\n    keyname = self.get_mkeyname(path, name, vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 222, in get_mkeyname\\n    schema = self.schema(path, name, vdom=vdom)\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 322, in schema\\n    url = self.cmdb_url(path, name, vdom=vdom) + \\"&action=schema\\"\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 257, in cmdb_url\\n    self.check_session()\\n  File \\"/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/fortiosapi/fortiosapi/fortiosapi.py\\", line 131, in check_session\\n    raise NotLogged()\\nfortiosapi.fortiosapi.exceptions.NotLogged: Not logged on a session, please login.\\n", "module_stdout": "", "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", "rc": 1}
[

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```
