### ISSUE TITLE
public key generated by openssh_keypair module cannot be copied by authorized_key module

### ISSUE THREAD

**Issue by abdennour** [ansible/ansible#68835]
##### SUMMARY
The input of authorized_key module (key param) is the output of the openssh_keypair module (key.pub).
authorized_key does not accept the key throwing the error "invalid key specified"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

**modules**
- openssh_keypair
- authorized_key

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/abdennour/playbook/ansible.cfg
  configured module search path = ['/Users/abdennour/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/abdennour/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Users/abdennour/Library/Python/3.7/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:29:04) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
Empty
```

##### OS / ENVIRONMENT

macOS High Sierra 10.13.6
MacBook Pro ( 2018)

##### STEPS TO REPRODUCE

```yaml
- name: key pair is generated
  openssh_keypair:
    path: "{{ keyair_path }}"
    type: rsa
    size: 4096
  delegate_to: localhost
  become: no
- name: given public key is copied remotely inside ~/.ssh/authorized keys
  authorized_key:
    user: ansible
    state: present
    key: '{{ item }}'
  with_fileglob:
    - "{{ keyair_path }}.pub"
```

##### EXPECTED RESULTS

By running above tasks, I expected to :
- generate ssh keypair
- copy the ssh public key to the remote target

##### ACTUAL RESULTS

- ✅ generate ssh keypair
- ❌ copy the ssh public key to the remote target

```paste below
TASK [ given public key is copied remotely inside ~/.ssh/authorized keys] *******************************************
failed: [rhel8] (item=/tmp/id_rsa.pub) => {"ansible_loop_var": "item", "changed": false, "item": "/tmp/id_rsa.pub", "msg": "invalid key specified: /tmp/id_rsa.pub"}
```
