### ISSUE TITLE
aix_lvg returns OK even when the task has failed

### ISSUE THREAD

**Issue by roxyland** [ansible/ansible#68830]
**SUMMARY**

aix_lvg(aix_lvg.py) returns OK even when the task has failed. 
In this case the command has failed because the disk was previously part of another VG and AIX will not create the VG unless it is forced.

**ISSUE TYPE**

- Bug Report

**COMPONENT NAME**

aix_lvg

**ANSIBLE VERSION**
```
ansible 2.9.3
  config file = /home/xxxxxx/.ansible.cfg
  configured module search path = [u'/home/xxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**OS/ ENVIRONMENT**

Target: AIX 7.2 LPAR

**STEPS TO REPRODUCE**

Use a disk(pp) that was previously part of a volume group that should cause AIX mkvg to fail unless it is forced.

```
aix_data_vgs:
  - { vg_name: 'datavg01', disks: [ 'hdisk1' ], vg_type: 'normal', pp_size: '', state: 'present' }

- name: configure data volume groups
  aix_lvg:
    vg: "{{ item.vg_name }}"
    vg_type: "{{ item.vg_type }}"
    pp_size: "{{ item.pp_size | int | default(omit) }}"
    pvs: "{{ item.disks | join(',') }}"
    state: "{{ item.state }}"
    # force: yes
  with_items:
    - "{{ aix_data_vgs }}"
```

**COMMAND OUTPUT**
```
ok: [lpar01] => (item={u'state': u'present', u'disks': [u'hdisk1'], u'pp_size': u'', u'vg_name': u'datavg01', u'vg_type': u'normal'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "force": false,
            "pp_size": null,
            "pvs": [
                "hdisk1"
            ],
            "state": "present",
            "vg": "datavg01",
            "vg_type": "normal"
        }
    },
    "item": {
        "disks": [
            "hdisk1"
        ],
        "pp_size": "",
        "state": "present",
        "vg_name": "datavg01",
        "vg_type": "normal"
    },
    "msg": "Creating volume group 'datavg01' failed.",
    "state": "present"
}
```

**EXPECTED RESULT**
The Ansible task should have failed because the AIX command has failed.
