### ISSUE TITLE
win_format > allocation_unit_size is always 4096

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/ansible#68896]
##### SUMMARY
win_format > allocation_unit_size is always 4096

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_format

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/vault_password_file
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible server: Ubuntu Server 18.04
Guest OS: Windows Server 2016/2019

##### STEPS TO REPRODUCE

```yaml
      win_format:
        drive_letter: "{{ variable }}"
        file_system: NTFS
        new_label: "{{ variable }}"
        allocation_unit_size: 65536
```

##### EXPECTED RESULTS
Disk will be formatted to 64k 

##### ACTUAL RESULTS

```paste below
All disks formatted with default 64K.
PS C:\Users\user> Get-WmiObject -Class Win32_Volume | Select-Object BlockSize | Format-Table

BlockSize
---------
     4096
     4096
     4096
     4096
     4096
     4096
     4096
     4096
```
