### ISSUE TITLE
Using the template module on FIPS system throw "OpenSSL internal error"

### ISSUE THREAD

**Issue by rabin-io** [ansible/ansible#68901]
##### SUMMARY
Trying to apply a template on a file will throw this error 

```
fips_md.c(146): OpenSSL internal error, assertion failed: Digest update previous FIPS forbidden algorithm error ignored
    /bin/bash: line 1: 16852 Aborted                 (core dumped) /usr/bin/python
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- module_utils/basic.py

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rabin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.6 (default, Jan 30 2020, 09:44:41) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```
NULL
```

##### OS / ENVIRONMENT
It's Linux appliance based on Ubuntu 16.04, 
installed openssl version on the device
```
# openssl version 
OpenSSL 1.0.2s-fips  28 May 2019
```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: dev_edge_cluster
  remote_user: root

  tasks:

  - name: fix ssmtp conf file
    template:
      src: ssmtp.conf.j2
      dest: /etc/ssmtp/ssmtp.conf
      owner: root
      group: mail
      mode: 'u=rw,g=r,o='
    tags: template
    environment:
      # LD_DEBUG: libs

```

##### EXPECTED RESULTS

Apply the template

##### ACTUAL RESULTS

```
fatal: [dev-edge-1]: FAILED! => changed=false 
  checksum: 8f65b6bed77c364ce241dbe1330f46ad49cf9fcf
  diff: []
  invocation:
    dest: /etc/ssmtp/ssmtp.conf
    follow: false
    group: mail
    mode: null
    module_args:
      dest: /etc/ssmtp/ssmtp.conf
      follow: false
      group: mail
      mode: null
      owner: root
      src: /home/rabin/.ansible/tmp/ansible-local-20520434h1qcjo2/tmp3g75zz95/ssmtp.conf.j2
    owner: root
    src: /home/rabin/.ansible/tmp/ansible-local-20520434h1qcjo2/tmp3g75zz95/ssmtp.conf.j2
  module_stderr: |-
    fips_md.c(146): OpenSSL internal error, assertion failed: Digest update previous FIPS forbidden algorithm error ignored
    /bin/bash: line 1: 17960 Aborted                 (core dumped) /usr/bin/python
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 134
```

P.S

In the end I used `lineinfile` module to achieve the same result.
