### ISSUE TITLE
Vultr: implement load balancer module

### ISSUE THREAD

**Issue by senorsmile** [ansible/ansible#68900]
##### SUMMARY

Vultr introduced managed load balancers on January 13, 2020: https://www.vultr.com/news/Increase-Performance-With-Vultr-Load-Balancers/

Add a new vultr_lb module that enables creating and destroying load balancers.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

I would recommend either vultr_lb or vultr_loadbalancer

##### ADDITIONAL INFORMATION

This module will allow one to provision managed load balancers in vultr. 

```yaml
- name: 
  vultr_lb:
    name: web
    port: 80
    instance_port: 8080
    algorithm: Leastconn
    label: web
    instances:
      - web01
      - web02

```
