### ISSUE TITLE
Cloudformation nested stacks

### ISSUE THREAD

**Issue by azarboon** [ansible/ansible#68906]
##### SUMMARY
[AWS Cloudformation Nested stacks](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html) provide an easy way to organize project into components and to reuse them. Nested stacks are currently not supported in Ansible. 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cloudformation
cloudformation_info

##### ADDITIONAL INFORMATION

Cloudformation nested stacks are recommended by AWS; as project grows their usage become inevitable. To use Ansible with a Cloudformation root stack (template that contains a nested stack), currently users need to breakdown their root stack and organize nested stacks into playbook. (Importing a nested stack in my playbook, I get this error while the corresponding nested stack is tried to be deployed `TemplateURL must be an Amazon S3 URL.`). This is just extra effort and inconvenient. 

If that would be supported, then users just need to import template file of the root stack and rest will be handled internally ( so need to take out nested stack and put them in playbook)

```
- name: create a cloudformation root stack
  cloudformation:
    stack_name: "root-stack"
    state: "present"
    region: "us-east-1"
    disable_rollback: true
    template: "files/root-stack.json"
    template_parameters:

```
