### ISSUE TITLE
when using --check unarchive does not see directory built in previous task 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#68929]
##### SUMMARY
Works when not in --check mode.  But in --check mode I  get:
TASK [mule_machines : JDK - ensure remote directory state] *********************
changed: [MuleD02] => (item={'mode': '0755', 'name': '/home/mule/apps/jdk8u242b08'})

TASK [mule_machines : JDK - unarchive jdk archive file contents into apps subfolder] ***
fatal: [MuleD02]: FAILED! => {"changed": false, "msg": "dest '/home/mule/apps/jdk8u242b08' must be an existing dir"}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unarchive

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /data/ansible.cfg
  configured module search path = ['/home/mule/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Oct 17 2019, 11:10:22) [GCC 8.3.0]
```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
DEFAULT_HOST_LIST(/data/ansible.cfg) = ['/data/inventory']
DEFAULT_ROLES_PATH(/data/ansible.cfg) = ['/data/roles']
DEFAULT_STRATEGY(/data/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/data/ansible.cfg) = ['/usr/lib/python3.6/site-packages/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/data/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL 7.7

##### STEPS TO REPRODUCE
Run these tasks with --check:
```
- name: JDK - ensure remote directory state
  file:
    path: "{{ item.name }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { mode: '0755', name: "/home/mule/apps/jdk8u242b08" }

- name: JDK - unarchive jdk archive file contents into apps subfolder
  unarchive:
    src: "/deployablePackages/vendor/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz"
    dest: "/home/mule/apps/jdk8u242b08"
    extra_opts: "--strip-components=1"
    creates: "/home/mule/apps/jdk8u242b08/bin"
```

##### EXPECTED RESULTS
ok: for the unarchive task

##### ACTUAL RESULTS
```
TASK [mule_machines : JDK - ensure remote directory state] *********************
changed: [MuleD02] => (item={'mode': '0755', 'name': '/home/mule/apps/jdk8u242b08'})

TASK [mule_machines : JDK - unarchive jdk archive file contents into apps subfolder] ***
fatal: [MuleD02]: FAILED! => {"changed": false, "msg": "dest '/home/mule/apps/jdk8u242b08' must be an existing dir"}
```
