### ISSUE TITLE
get_url does not authenticate against ftp servers

### ISSUE THREAD

**Issue by michaelsstuff** [ansible/ansible#68956]
##### SUMMARY
get_url does not authenticate against ftp servers

##### ISSUE TYPE
- ~Bug Report~
- Feature Idea

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION

```paste below
ansible 2.10.0.dev0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Python 3.6.5
OpenSSL 1.1.0i-fips  14 Aug 2018

##### STEPS TO REPRODUCE

```yaml
---
- name: TEST
  connection: localhost
  gather_facts: false
  hosts: localhost
  tasks:
    - name: download ftp
      get_url:
        url: ftp://u205615.your-storagebox.de/mods/
        url_username: u205615-sub1
        url_password: y4N66hRjQwswrp0o
        force_basic_auth: yes
        validate_certs: no
        dest: /home/michael/test/
```

##### EXPECTED RESULTS

I expect get_url to use credentials to loginto the ftp url

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/11227197/79310777-c4fd1480-7efc-11ea-888a-a96d8e395af6.png)
Ansible ignores username and password and does an anonymous login

```paste below
PLAY [TEST] *****************************************************************************************************************************************************************************************************************************************************

TASK [download ftp] *********************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/home/michael/test/", "elapsed": 0, "gid": 100, "group": "users", "mode": "0777", "msg": "Request failed: <urlopen error ftp error: error_perm('530 Login incorrect.',)>", "owner": "michael", "size": 512, "state": "directory", "uid": 1000, "url": "ftp://u205615.your-storagebox.de/mods/"}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
