### ISSUE TITLE
Azure image and gallyerimageversion info modules don't support check mode

### ISSUE THREAD

**Issue by jghal** [ansible/ansible#68953]
##### SUMMARY

Developing a playbook to delete old images and shared image gallery versions and test it by running with `--check --diff`. The `_info` modules used to lookup candidates are reporting they do not support check mode.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_image_info
azure_rm_galleryimageversion_info

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = None
  configured module search path = ['/home/jghal/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jghal/Code/venv/ansible-2.9/lib64/python3.6/site-packages/ansible
  executable location = /home/jghal/Code/venv/ansible-2.9/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT

Playbook will be run against localhost using only cloud modules

##### STEPS TO REPRODUCE

```yaml
- name: "Find all {{ image_name }} images"
  azure_rm_image_info:
    resource_group: "{{ azure.packer_resource_group }}"
    tags:
      - "Name:{{ image_name }}"
      - "branch:master"
  register: build_image
- name: List all gallery image versions in a gallery image definition.
  azure_rm_galleryimageversion_info:
    gallery_name: "{{ azure.sig_name }}"
    gallery_image_name: "{{ image_name }}"
    resource_group: "{{ azure.sig_resource_group }}"
  register: sig_image
```

```bash
$ ansible-playbook main.yml --check --diff --tags azure -e '{"image_name":["centos7.base"], }' -v
```

##### EXPECTED RESULTS

Should return the list of matching images and image versions

##### ACTUAL RESULTS

```paste below
No config file found; using defaults
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [Retire base images] **********************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Retire AZURE] ****************************************************************************************************
included: /home/jghal/Code/Halliburton-Landmark/ienergy-cloud/packer/retire-base-images/retire-azure.yml for localhost

TASK [Find all centos7.base images] ****************************************************************************
skipping: [localhost] => {"changed": false, "msg": "remote module (azure_rm_image_info) does not support check mode"}

TASK [List all gallery image versions in a gallery image definition.] **************************************************
skipping: [localhost] => {"changed": false, "msg": "remote module (azure_rm_galleryimageversion_info) does not support check mode"}
```
