### ISSUE TITLE
node_resource_group doesn't work with azure_rm_aks in ansible 2.9.6

### ISSUE THREAD

**Issue by imlight** [ansible/ansible#68955]
##### SUMMARY
node_resource_group doesn't work with azure_rm_aks in ansible 2.9.6

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_aks

##### ANSIBLE VERSION

```ansible --version
ansible 2.9.6
  config file = None
  configured module search path = [u'/home/devans/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/devans/.local/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 16:02:27) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]
```

##### CONFIGURATION
```Blank output  of  ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
cat /etc/oracle-release
Oracle Linux Server release 7.6

##### STEPS TO REPRODUCE

```
 - name: Create a managed Azure Container Services (AKS) instance in mel for APT
    azure_rm_aks:
      name: "{{ snd_aks_mel_cluster_name }}"
      location: "{{ snd_mel_nsg_location }}"
      resource_group: "{{ snd_aks_resource_group }}"
      node_resource_group: "{{ snd_aks_mel_node_resource_group_name }}"
      enable_rbac: yes
      dns_prefix: "{{ snd_aks_mel_cluster_name }}"
      kubernetes_version: "{{ versionssyd.azure_aks_versions[-1] }}"
      linux_profile:
        admin_username: azure-user
        ssh_key: "{{ lookup('file', '/home/devans/ansible-awx-git/cloud-automation/azure-user-ssh-key.pub') }}"
      service_principal:
        client_id: "{{ snd_apt_mel_spr_client_id }}"
        client_secret: "{{ snd_apt_mel_spr_secret }}"
      agent_pool_profiles:
        - name: nodepool1
          count: 3
          vm_size: Standard_DS3_v2
          vnet_subnet_id: "{{ snd_mel_subnet_reg.state.id }}"
      network_profile:
        dns_service_ip: "10.253.0.10"
        docker_bridge_cidr: "10.255.0.1/16"
        network_plugin: kubenet
        service_cidr: "10.253.0.0/16"
      addon:
        monitoring:
          enabled: yes
          log_analytics_workspace_resource_id: "{{ snd_mel_law_reg.id }}"
      profile: "{{ profilename }}"
      tags:
          CostCenter: "{{ CostCenter_tag }}"
          Environment: "{{ Environment_tag }}"
          Owner: "{{ Owner_tag }}"
    environment: "{{ proxy_env }}"
    register: aks_mel


```

##### EXPECTED RESULTS
Ansible module azure_rm_aks allows to pass node_resource_group argument 

##### ACTUAL RESULTS

```    },
    "msg": "Unsupported parameters for (azure_rm_aks) module: node_resource_group Supported parameters include: aad_profile, ad_user, addon, adfs_authority_url, agent_pool_profiles, api_profile, append_tags, auth_source, cert_validation_mode, client_id, cloud_environment, dns_prefix, enable_rbac, kubernetes_version, linux_profile, location, name, network_profile, password, profile, resource_group, secret, service_principal, state, subscription_id, tags, tenant"
}

```

I saw in ansible 2.9.6 azure_rm_aks.py python script and looks it accepts the node_resource_group  argument . For some reason it looks like not working . Or may be we are not there yet ?

Also I have tried role  azure_preview_modules , still I get similar error
