### ISSUE TITLE
Unsupported parameters for (synchronize) module

### ISSUE THREAD

**Issue by ReyRen** [ansible/ansible#68973]
##### SUMMARY

When I use synchronize module to push some files into child nodes, the error always occur about "not supported parameters" without any specified.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

The task is to push some files to remote child nodes
The module used is synchronize

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /home/yuanren/deepops/ansible.cfg
  configured module search path = [u'/home/yuanren/deepops/kubespray/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/yuanren/deepops/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/yuanren/deepops/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=5m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null
ANSIBLE_SSH_CONTROL_PATH(/home/yuanren/deepops/ansible.cfg) = ~/.ssh/ansible-%%r@%%h:%%p
CACHE_PLUGIN(/home/yuanren/deepops/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/yuanren/deepops/ansible.cfg) = /var/tmp/ansible_cache
CACHE_PLUGIN_TIMEOUT(/home/yuanren/deepops/ansible.cfg) = 86400
DEFAULT_FORKS(/home/yuanren/deepops/ansible.cfg) = 25
DEFAULT_GATHERING(/home/yuanren/deepops/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/yuanren/deepops/ansible.cfg) = [u'/home/yuanren/deepops/config/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/yuanren/deepops/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/yuanren/deepops/ansible.cfg) = /tmp/ansible-local-1083371wfg0
DEFAULT_MODULE_PATH(/home/yuanren/deepops/ansible.cfg) = [u'/home/yuanren/deepops/kubespray/library']
DEFAULT_ROLES_PATH(/home/yuanren/deepops/ansible.cfg) = [u'/home/yuanren/deepops/galaxy-roles', u'/home/yuanren/deepops/roles', u'/home/yuanren/deepops/kubespray/roles']
DEFAULT_STDOUT_CALLBACK(/home/yuanren/deepops/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/yuanren/deepops/ansible.cfg) = 60
DEPRECATION_WARNINGS(/home/yuanren/deepops/ansible.cfg) = False
HOST_KEY_CHECKING(/home/yuanren/deepops/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04 LTS
OS: 5.3.0-46-generic

##### STEPS TO REPRODUCE

```yaml
 - name: sync_file | Upload file images to node
    synchronize:
      src: "{{ file_path_cached }}"
      dest: "{{ download.dest }}"
      use_ssh_args: "{{ has_bastion | default(false) }}"
      mode: push
      #become: true
      #register: get_task
      #until: get_task is succeeded
      #retries: 4
      #delay: "{{ retry_stagger | random + 3 }}"
      when:
        - ansible_os_family not in ["CoreOS", "Coreos", "Container Linux by CoreOS"]
```

##### EXPECTED RESULTS

Pushed to all nodes within the specific groups

##### ACTUAL RESULTS

```
TASK [download : sync_file | Upload file images to node] ****************************************************************************************************************************
task path: /home/yuanren/deepops/kubespray/roles/download/tasks/sync_file.yml:27
META: noop
META: noop
META: noop
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/files/synchronize.py
Pipelining is enabled.
<cluster-master> ESTABLISH LOCAL CONNECTION FOR USER: root
<cluster-master> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [cluster-master]: FAILED! => changed=false
  invocation:
    module_args:
      _local_rsync_password: null
      _local_rsync_path: rsync
      dest: root@cluster-master:/tmp/releases/kubeadm-v1.16.7-amd64
      mode: push
      private_key: ~/.ssh/id_rsa
      rsync_path: sudo rsync
      src: /tmp/releases/kubeadm-v1.16.7-amd64
      when:
      - ansible_os_family not in ["CoreOS", "Coreos", "Container Linux by CoreOS"]
  msg: 'Unsupported parameters for (synchronize) module: when Supported parameters include: _local_rsync_password, _local_rsync_path, _substitute_controller, archive, checksum, compress, copy_links, delete, dest, dest_port, dirs, existing_only, group, link_dest, links, mode, owner, partial, perms, private_key, recursive, rsync_opts, rsync_path, rsync_timeout, set_remote_user, src, ssh_args, times, verify_host'
```
