### ISSUE TITLE
RFE: add option(s) to ansible-playbook to check modules are found and what content source they come from

### ISSUE THREAD

**Issue by kdelee** [ansible/ansible#68989]
##### SUMMARY

There is a need to provide tooling for the following use cases:

1) I have a playbook and I want to check to see what modules I am using are not in ansible-base, rather now they live in collections. I want to know what collection they live in without having to manually search through [routing.yml](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml). I prefer not to know `routing.yml` exists. I want to know which ones these are without having to run the playbook and see where it breaks, following including roles and `include_tasks`.

2) I have a playbook and have installed in my environment a bunch of collections, I want to check and see what collection is going providing each module before running the playbook.

These address both users that are taking advantage of "tombstoning" as well as those who would like to update their content to explicitly use certain collections.

It provides a more sane way of developing and linting ansible content without having to take the approach of "just run it and see where blows up, then run it again and see where it blows up the next time" which is not a great development experience.

Currently, in order to figure out what collections my playbooks depend on, I either need to read ever task of every playbook and role and know intimately what has been moved (e.g. have routing.yml memorized) or run it and let it blow up, then manually look up what collection it is now hosted in by looking at https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml .

https://github.com/ansible/ansible/pull/67684 is putting place "tombstoning" aims to enable people to not have to re-write their playbooks to be able to run with ansible 2.10, given that a collection is installed that provides the content that ansible knows to try based on https://github.com/ansible/ansible/blob/devel/lib/ansible/config/routing.yml

If indeed we are capable of doing such routing, then we should be capable of reporting to the user what that routing is without having to actually execute the playbook tasks.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

collections
routing.yml

##### ADDITIONAL INFORMATION

This feature would allow me to:
1) Take inventory of what I need collections I need to install in order to run my existing playbooks with 2.10, simply taking advantage of tombstoning
2) If I want to write new content or update current content to specify FQCN, it tells me what I need to do
3) Once I have my playbooks the way I like and my collections installed in an environment, it allows me to double check that I am using the content from the desired collections. Would be extra great if it told me what version of that collection I am using, but that's a stretch goal. At least tell me what you are using. This is especially important if we are taking advantage of "flatmapping" aka tombstoning and there is some room for interpretation from the user about what collection might take precedence for providing a module.

Could look something like this:

Most basic, just show my modules mapped out w/ FQCN, have it behave like `--list-tasks` when it finds all some source for each module and show the source, have it fail like `--syntax-check` when it fails.
 
```yaml

# happy path
ansible-playbook --content-check myplaybook.yml

playbook: ./myplaybook.yml

  play #1 (local):
    community.general.ini_file name='hello_ini_file' path=what second=example option=favorite value=color
    ansible.base.template src=mytemplate.j2 dest=foo.txt
```

```yaml

# unhappy path (no source found for module)
ansible-playbook --content-check myplaybook.yml

playbook: ./myplaybook.yml

ERROR! Module "ini_file" not available but provided by community.general.ini_file.

If you intended to use "community.general.ini_file" make sure the "community.general" collection is installed and available in your ANSIBLE_COLLECTIONS_PATHS

The error appears to be in '/home/elijah/sfw/ansible/myplaybook.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending task appears to be:

  tasks:
    - name: Update setting in an ini_file.
      ini_file: 

```

Alternatively, we might not need `--content-check` at all and all of the functionality could be rolled into `--list-tasks` and `--syntax-check`
