### ISSUE TITLE
module_defaults versus module property

### ISSUE THREAD

**Issue by ademprojects** [ansible/ansible#68992]
##### ISSUE TYPE
- Feature Idea
When providing module_defaults, this should be inherited up to the last element -> task.
But if you define more specific or even the property in a task, the property inside the task should win over module_defaults. This should be the expected goal.
Currently you get an error, that state is not defined, as module_defaults seems not to combine with loop_control.var.
Maybe this due to this reported bug ? https://github.com/ansible/ansible/issues/68991

##### COMPONENT NAME

module_defaults
##### ADDITIONAL INFORMATION

```yaml
    - package:
        name:  "{{ Ipackage.name |default(TaskName['defaults']['name']) }}"
        use:   "{{ Ipackage.use  |default(TaskName['defaults']['use'])  |default(omit) }}"
        state:   "{{ Ipackage.state |default(TaskName['defaults']['state']) }}"

      loop_control:
        loop_var: Ipackage
        label: "Module 'package': name='{{ Ipackage.name }}', {{Ipackage.state}}' "
      module_defaults:
        package:
          state: present
      << : *WDTaskDefaults #name and loop as YAML merge
```
