### ISSUE TITLE
Allow hidden keys in YAML so that they can be used to declare YAML anchors

### ISSUE THREAD

**Issue by rohit-gohri** [ansible/ansible#68994]
##### SUMMARY

Currently using YAML anchors in an inventory file can be done as described in https://docs.ansible.com/ansible/latest/user_guide/playbooks_advanced_syntax.html#yaml-anchors-and-aliases-sharing-variable-values

This quickly leads to complicated and difficult to understand inventory files in case of large number of entries. I propose allowing hidden keys in yaml files (like supported in `.gitlab-ci.yml`: https://docs.gitlab.com/ee/ci/yaml/#hidden-keys-jobs). They could be keys prefixed with a `.` or something else. These hidden keys can be used as anchors in the whole config making it more easy to understand.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

YAML Parser

##### ADDITIONAL INFORMATION

Current inventory file structure with Anchors:

```yaml
servers:
  children:
    core_servers:
      hosts:
        192.168.1.10: &stage-config
          hostname: example-host
          ansible_user: ec2-user
    staging:
      hosts:
        192.168.1.10: *stage-config
```

After adding hidden keys the same inventory file could look like:

```yaml
.stage-server: &stage-config
  192.168.1.10:
    hostname: example-host
    ansible_user: ec2-user

servers:
  children:
    core_servers:
      hosts:
        <<: *stage-config
    staging:
      hosts:
        <<: *stage-config
``` 

This currently leads to a warning: 

> Invalid characters were found in group names but not replaced, use -vvvv to see details

**Comment by flowerysong** [comment]
You seem to be under the misapprehension that declarations of the same host in different groups are independent. This is not the case; every time an inventory host is referenced in a file it is the same host, so you only have to put the hostvars on one entry.


This is exactly the same inventory as your original example:
```
all:
  hosts:
    192.168.1.10:
      hostname: example-host
      ansible_user: ec2-user

servers:
   children:
      core_servers:
        hosts:
          192.168.1.10:
      staging:
        hosts:
          192.168.1.10:
```

As is this:
```
servers:
  children:
    core_servers:
      hosts:
        192.168.1.10:
          hostname: example-host
          ansible_user: ec2-user
    staging:
      hosts:
        192.168.1.10:
```
