### ISSUE TITLE
module_defaults in combination with loop_control.label fails

### ISSUE THREAD

**Issue by ademprojects** [ansible/ansible#68991]
##### SUMMARY

When you use 
##### ISSUE TYPE
- Bug Report
It is not possible to use module_defaults in combination with loop_control.label. The variable is not resolved. Tried **state**, **package.state**, **module_defaults.package.state** as well as the expected variabled which should work **Ipackage.state**. 
None of them are resolved.

##### COMPONENT NAME

loop_control.label / module_defaults

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /srv/DSOPS/appsrv/adem/ansible.cfg
  configured module search path = ['/srv/DSOPS/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /srv/DSOPS/appsrv/python/versions/3.8.2/envs/dsopsAnsibleHost-3.8.2/lib/python3.8/site-packages/ansible
  executable location = /srv/DSOPS/appsrv/python/versions/dsopsAnsibleHost-3.8.2/bin/ansible
  python version = 3.8.2 (default, Mar 28 2020, 16:29:03) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/srv/DSOPS/appsrv/adem/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/srv/DSOPS/appsrv/adem/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
DEFAULT_EXECUTABLE(/srv/DSOPS/appsrv/adem/ansible.cfg) = /bin/bash
DEFAULT_FACT_PATH(/srv/DSOPS/appsrv/adem/ansible.cfg) = /srv/DSOPS/metadata/facts/custom_facts.d
DEFAULT_HOST_LIST(/srv/DSOPS/appsrv/adem/ansible.cfg) = ['/srv/DSOPS/appsrv/adem/hiera/data/ansible_inventory']
DEFAULT_LOCAL_TMP(/srv/DSOPS/appsrv/adem/ansible.cfg) = /srv/DSOPS/temp/.ansible/ansible-local-10055t9y4hd2f
DEFAULT_LOG_PATH(/srv/DSOPS/appsrv/adem/ansible.cfg) = /srv/DSOPS/logs/ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/srv/DSOPS/appsrv/adem/ansible.cfg) = ['/srv/DSOPS/appsrv/adem/plugins/lookup']
DEFAULT_REMOTE_USER(/srv/DSOPS/appsrv/adem/ansible.cfg) = root
DEFAULT_ROLES_PATH(/srv/DSOPS/appsrv/adem/ansible.cfg) = ['/srv/DSOPS/appsrv/adem/roles']
DEFAULT_VAULT_PASSWORD_FILE(/srv/DSOPS/appsrv/adem/ansible.cfg) = /srv/DSOPS/appsrv/adem/.vault
HOST_KEY_CHECKING(/srv/DSOPS/appsrv/adem/ansible.cfg) = False
```

##### OS / ENVIRONMENT

virtualbox - centos 7

##### STEPS TO REPRODUCE

```yaml
    - package:
        name:  "{{ Ipackage.name |default(TaskName['defaults']['name']) }}"
        use:   "{{ Ipackage.use  |default(TaskName['defaults']['use'])  |default(omit) }}"

      loop_control:
        loop_var: Ipackage
        label: "Module 'package': name='{{ Ipackage.name }}', {{Ipackage.state}}' "
      module_defaults:
        package:
          state: present
      << : *WDTaskDefaults #name and loop as YAML merge
```

##### EXPECTED RESULTS

{{Ipackage.state}} should be resolved

##### ACTUAL RESULTS

```paste below
failed: [buildRundeck] (item=None) => {"Ipackage": {"name": "at"}, "ansible_loop_var": "Ipackage", "changed": false, "msg": "Failed to template loop_control.label: 'state' is undefined", "rc": 0, "results": ["at-3.1.13-24.el7.x86_64 providing at is already installed"]}
```
