### ISSUE TITLE
elb_application_lb Updating Listener Rules Of Existing LB Fails After Edit

### ISSUE THREAD

**Issue by Alex-Richman** [ansible/ansible#69017]
##### SUMMARY
Updating the Listener Rules of an existing elbv2 load balancer via elb_application_lb successfully modifies the rules but raises an exception while parsing the response.  If no update is made (e.g. playbook is run again after the failed run) then it correctly returns [OK].

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
elb_application_lb

##### STEPS TO REPRODUCE
Run playbook with some ELB rules, creating the ELB for the first time - Observe success
```yaml
elb_application_lb:
  state: present
  ...
  listeners:
    ...
    Rules:
      ...
      - Type: fixed-response
         FixedResponseConfig:
         StatusCode: "403"
         ContentType: "text/plain"
         MessageBody: Forbidden
```

Modify parameters of one of the rules slightly, re-run playbook - Observe failure, but note that rules have updated in AWS console.

Re-run playbook again - Observe [OK].

The particular playbook I see this on has one `source-ip` rule, 5-13 `host-header` rules with `forward` actions, and a `fixed-response` default action.  I'm not sure if it's specifically any of those which are causing the issue or if it happens more generally.

##### ACTUAL RESULTS
```
[WARNING]: Module invocation had junk after the JSON data:
... (massive blob of JSON representing the elb configuration)

fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "modified_rule:" ... (massive blob of JSON representing the elb configuration) ... \\n", "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", "rc": 0}
```
