### ISSUE TITLE
Flatten field yields unexpected results when it hits None

### ISSUE THREAD

**Issue by borisovano** [ansible/ansible#69012]
##### SUMMARY
Flatten field yields unexpected results when it hits None. Instead of skipping over none it silently discards the to-be-flatten list. See example below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
flatten filter

##### ANSIBLE VERSION

```paste below
ansible 2.8.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr  8 2019, 18:17:52) [GCC 8.3.0]
```

##### OS / ENVIRONMENT

`FROM pad92/ansible-alpine:latest`

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  vars:
    nested_a:
      - "a"
      - "b"
      - ["c","d"]

    nested_b:
      - ["a", None, "b"]
      - "c"
      - "d"

  tasks:
    - name: Works 
      debug:
        msg: "Flatten list: {{ nested_a | flatten }}"

    - name: Where is 'b'
      debug:
        msg: "Flatten list: {{ nested_b | flatten }}"

```

##### EXPECTED RESULTS

ok: [localhost] => {
    "msg": "Flatten list: ['a', 'b', 'c', 'd']"
}

TASK [WTF is 'b'] ************************************************************************************************************
ok: [localhost] => {
    "msg": "Flatten list: ['a', 'b', 'c', 'd']'      <--------- 'b' is present
}

##### ACTUAL RESULTS
ok: [localhost] => {
    "msg": "Flatten list: ['a', 'b', 'c', 'd']"
}

TASK [where is 'b'] ************************************************************************************************************
ok: [localhost] => {
    "msg": "Flatten list: ['a', 'c', 'd']"     <--------- 'b' is missing
}
