### ISSUE TITLE
issue with delegate_to + add_host

### ISSUE THREAD

**Issue by omgjlk** [ansible/ansible#6901]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible-playbook 1.6 (devel dfa8aef408) last updated 2014/04/07 17:26:26 (GMT -700)
and
ansible-playbook 1.5.4 (release1.5.4 1184470d39) last updated 2014/04/08 11:29:59 (GMT -700)
##### Environment:

N/A
##### Summary:

Hard to word this right, but I have a playbook setup with a task include file. The included tasks can optionally be delegated, and if not, they default to delegating to the inventory_hostname, that is the host running in the loop. The construct is

`delegate_to: "{{ delegate|default(inventory_hostname) }}"`

When including this task, we're doing:

`- include: tasks/taskfile.yaml delegate=nodename`

With 1.5.4, ansible appears to be processing the delgate_to template very early, and finding that "delegate" is undefined at that point, thus it's defaulting to non-delegation.
##### Steps To Reproduce:

cachetest.yaml: 

```

---
- name: Test play 1
  hosts: all
  gather_facts: no

  tasks:
    - name: add a real host
      add_host: name=derp ansible_ssh_host=127.0.0.1

    - name: set a fact
      set_fact: derphost=derp

    - name: ping
      ping:
      delegate_to: "{{ derphost|default(inventory_hostname) }}"
```

`$ bin/ansible-playbook -i herp, cachetest.yaml -vvvv`
##### Expected Results:

The expected result would be a successful ping: action to the localhost, so in the -vvvv output you'd see an attempt to ssh to 127.0.0.1
##### Actual Results:

What I'm seeing is an attempt to ssh to "hurp", which does not resolve and thus ssh fails:
`ssh: Could not resolve hostname herp: nodename nor servname provided, or not known`

Additional Info:

I have bisected with my test and discovered the suspected commit that breaks the previous behavior is 12b12bba925713eff48c70f4c52b087be226b9ee . If I revert that commit (from the release1.5.4 branch) my tests pass.

**Comment by jctanner** [comment]
A workaround:

```
delegate_to: "{{ hostvars[inventory_hostname]['derphost'] | default(inventory_hostname) }}"
```

Another:

```
    - name: set a fact
      set_fact: derphost=derp

    - name: set a fact2
      set_fact: ihost='{{ inventory_hostname }}'

    - name: ping
      ping:
      delegate_to: "{{ derphost|default(ihost) }}"
```
