### ISSUE TITLE
Failed to import the required Python library (python-ldap)

### ISSUE THREAD

**Issue by jlegido** [ansible/ansible#69045]
##### SUMMARY
First of all many thanks to all the people involved in this project for your time.

Getting below error:

```
Failed to import the required Python library (python-ldap) on remote_host's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```
* Package ```python-ldap``` is installed in target host
* I tried installing ```python-ldap``` in ansible host, but same result
* I forced to use python3 as interpreter
* I already try putting python3 interpreter in ```ansible.cfg```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ldap_entry

##### ANSIBLE VERSION

```
2.9.6
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
```

##### OS / ENVIRONMENT
Host executing ansible:
* Docker container (version python:3.8.2-alpine)

Target host:
* GNU/Linux debian 10

##### STEPS TO REPRODUCE
Executing below task:

```
- name: Create '{{ ldap_object_readonly }}' user
  ldap_entry:
    dn: "{{ ldap_object_readonly }}"
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      description: LDAP readonly to be used by 3rd party applications
      userpassword: "{SSHA}myshapasswordhiddenhere"
    bind_dn: "{{ ldap_object_admin }}"
    bind_pw: "{{ ldap_admin_password }}"
  tags: ldap
```

##### EXPECTED RESULTS
Task being executed successfully

##### ACTUAL RESULTS
Get below error:

```
Failed to import the required Python library (python-ldap) on ecologicpan's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```
