### ISSUE TITLE
known_host module seems to work but the file hasn't changed

### ISSUE THREAD

**Issue by SallyBlich** [ansible/ansible#69046]
##### SUMMARY
known_host module seems to work but the file hasn't changed

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module: known_host

##### ANSIBLE VERSION
2.9.2

##### CONFIGURATION
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'nmap']

##### OS / ENVIRONMENT
Running Ansible on CentOS 7.7

##### STEPS TO REPRODUCE

```yaml
- name: sshKeyGenCreation
  hosts: all
  become: true
  connection: local

  - name: Add host to known hosts
    known_hosts:
      path: '/root/.ssh/known_hosts'
      name: "{{ IP }}"
      key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + IP) }}"
    delegate_to: localhost
```

##### EXPECTED RESULTS
To see the IP that I scanned in known_hosts file
IP KEY

##### ACTUAL RESULTS
So it seems to work but the IP didn't show up in the known_hosts file.

```paste below
{
    "uid": 0,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "_ansible_no_log": false,
    "hash_host": false,
    "key": "IP ssh-rsa....."
    "path": "/root/.ssh/known_hosts",
    "owner": "root",
    "diff": {
     "after": "IP-X ... KEY"
        "after_header": "/root/.ssh/known_hosts",
        "before_header": "/root/.ssh/known_hosts",
       "before": "IP-X ... KEY"
    "size": 36186,
    "group": "root",
    "name": "IP",
    "changed": false,
    "state": "file",
    "gid": 0,
    "mode": "0644",
    "invocation": {
        "module_args": {
            "state": "present",
            "hash_host": false,
            "name": "IP",
            "key": "IP... KEY"
            **"after": "IP-X ... KEY"**
            "after_header": "/root/.ssh/known_hosts",
             "before_header": "/root/.ssh/known_hosts",
             **"before": "IP-X ... KEY"**
```

Same IP in both lines: before, after
And it does show the id_rsa.pub but nothing happened.
When I tried to run the command locally on the Ansible server, it worked, so I assumed something I did was wrong.
ssh-keyscan -trsa IP  >> /root/.ssh/known_hosts
