### ISSUE TITLE
feature request: inventory plugins support yaml references in "compose"

### ISSUE THREAD

**Issue by SimonHeimberg** [ansible/ansible#69043]
##### SUMMARY
It would be handy if inventory plugins would support yaml references **in compose** (for settings with string values). This would allow to pass on settings to variables (see ADDITIONAL INFORMATION for an example):

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
inventory plugin

##### ADDITIONAL INFORMATION
example inventory showing how settings could be passed to variables:

inventory/yyy.yaml
```yaml
plugin: openstack # or clouldscale or ...
some_plugin_setting: &ref1 12345
inventory_hostname: &inventory_hostname_value uuid

compose:
  setting_1: *ref1 # should work already now
  setting_of_inventory_hostname: *inventory_hostname_value # fails now, is interpreted as variable name
```

This does not work because compose expects jinja2 expressions. When strings are passed, they are interpreted as variables. And I see no way to put quotes around *inventory_hostname_value or tell compose that the value is a string.

##### suggestion
Feature request: Please provide a way to use (string) setting values as variables.
 * by allowing something like this
    ```yaml
    compose:
        some_setting1:
            compose_setting:
                value: *some_string_ref
                type: value
      ```
 * by defining another section:
    ```yaml
    compose_values: #similar as compose, but takes values instead of jinja2
        some_setting1: *some_string_ref
    ```
<hr/>

##### old info

I do not get an error *(because `strict` is not set)*, but I do not see the variables settings_1 and setting_of_inventory_hostname.

Currently I can copy the values manually, which is error prone.

ansible version: 2.9.4
yaml syntax for saml references: https://en.wikipedia.org/wiki/YAML#Syntax or https://yaml.org/spec/1.0/#id2489959

**Comment by sivel** [comment]
This should already be possible.  What happens when you do this?

For reference, your syntax is backwards.  It should be `&ref1` instead of ref1&`, and `*ref1` instead of `ref1*`.

**Comment by SimonHeimberg** [comment]
Oops, true. Thanks for the hint. Somewhen during testing I did the syntax wrong. I fixed and extended the question.
So I have to redo the tests. An update will follow.

**Comment by SimonHeimberg** [comment]
Why does this fail?

```yaml
plugin: constructed

# add variables to existing inventory

keyed_groups:
  - key: from_inventory
    prefix: inventory
    parent_group: &common_parent_group test_group_1

compose:
  var_from_constructed: 1233456789
  also_from_constr: "'also'" # must be in quotes 2x!
  some_from_constr: &ref1 1234567777
  ref_from_constr: *ref1 # this works fine
  ref_to_test: *common_parent_group # <--- this line returns an error

strict: yes
```
Error: `Could not set ref_to_test for host my_host: 'test_group_1' is undefined`

But it passes when I uncomment the marked line. (the ref &common_parent_group is still defined, but not used with *common_parent_group.)

How to reproduce: `ansible -i some_of_your_inventory -i inventory_constructed.yaml -m debug -a var=vars`
