### ISSUE TITLE
Generic "package" module doesn't detect a package manager for Fedora-CoreOS  

### ISSUE THREAD

**Issue by s8k-37** [ansible/ansible#69064]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
package

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/steven/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_2/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:29:50) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### OS / ENVIRONMENT
Fedora CoreOS 31.20200323.3.2

##### STEPS TO REPRODUCE
Use the package module to install "Ceph-common" package with auto detection or with rpm-ostree

Try1:
```yaml
- name: "Install ceph-commmon package"
  package:
    name:
      - ceph-common
    state: present

```
Try2:
```yaml
- name: "Install ceph-commmon package"
  package:
    name:
      - ceph-common
    state: present
    use: rpm-ostree
```

##### EXPECTED RESULTS
install "ceph-common" package

##### ACTUAL RESULTS
Try1:
```
TASK [bootstrap-os : Install ceph-commmon package] *************************************************************************************************************************************************************************************
fatal: [node1]: FAILED! => {"changed": false, "msg": "missing required arguments: image, backend"}
```
Try2:
```
TASK [bootstrap-os : Install ceph-commmon package] *************************************************************************************************************************************************************************************
fatal: [node1]: FAILED! => {"changed": false, "msg": "Could not find a module for rpm-ostree."}

```
