### ISSUE TITLE
Openstack: enable pass in os-compute-api-version parameter

### ISSUE THREAD

**Issue by let-thomas** [ansible/ansible#69068]
##### SUMMARY
I am not really sure if this is bug or rather feature request.

I would like to attach "multi attach" volume.
From command line doable using $> openstack --os-compute-api-version 2.60 server add volume <VM-ID> <VOLUME-ID>

Passing in "compute_api_version: '2.60'" is not possible, please add this feature.

Surprisingly also adding "compute_api_version" into cloud.yaml does not fix the issue.
Detach works fine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os_server_volume

##### ANSIBLE VERSION

```
ansible 2.9.0
```

##### CONFIGURATION
```
```

##### STEPS TO REPRODUCE
```
---
- name: OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
    - os_server_volume:
        server: 'my_server'
        volume: 'mutli_att_vol'

```

##### EXPECTED RESULTS

changed: [localhost] => {
    "changed": true,
...etc.

##### ACTUAL RESULTS
```
    "msg": "Error attaching volume 111-long-id-111 to server 111-long-id-111 : Client Error for url: https://openstack-x.x.x:8774/v2.1/servers/4653ce78-1778-4895-ab36-a761127e302a/os-volume
_attachments, Multiattach volumes are only supported starting with compute API version 2.60."
```
