### ISSUE TITLE
Update developing modules documentation, to indicate submitting to collection repos

### ISSUE THREAD

**Issue by solomonakinyemi** [ansible/ansible#69069]
##### SUMMARY

I just tried to clone the ansible repository to start developing a new ansible module and it looks like the 'cloud' folder is missing in: lib/ansible/modules/

Has something changed that I am not aware of?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

unable to access: lib/ansible/modules/cloud/azure

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
Following the instruction of the following page:
https://docs.ansible.com/ansible/2.7/dev_guide/developing_modules_general.html?highlight=module
------
Clone the Ansible repository: $ git clone https://github.com/ansible/ansible.git
Change directory into the repository root dir: $ cd ansible
Create a virtual environment: $ python3 -m venv venv (or for Python 2 $ virtualenv venv. Note, this requires you to install the virtualenv package: $ pip install virtualenv)
Activate the virtual environment: $ . venv/bin/activate
Install development requirements: $ pip install -r requirements.txt
Run the environment setup script for each new dev shell process: $ . hacking/env-setup

* Navigate to the correct directory for your new module: $ cd lib/ansible/modules/cloud/azure/
```

##### EXPECTED RESULTS

available folder cloud/azure in: lib/ansible/modules/

##### ACTUAL RESULTS

```paste below
Folder unavailable
```
