### ISSUE TITLE
pip: add download feature

### ISSUE THREAD

**Issue by caimez** [ansible/ansible#69073]
##### SUMMARY
The ansible pip module would be so much better with a download feature to download whl files to a folder for an offline installation on another host.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
pip

##### ADDITIONAL INFORMATION
By specifying an archive_path, as is possible in the docker_image module, the whl files for a python package and all dependencies would be saved in the archive_path folder.

Currently, the only way to do this is by typing the pip download command within a shell module as below:
```yaml
- name: Download python {{package_name}} package and dependencies to {{archive_path}}
  shell: pip download {{package_name}} -d "{{archive_path}}"
```

Would be great if we could specify it directly via the pip module. Even more so because we have a warning saying that pip should be used via the pip module when we execute the task above.
Example:
```yaml
- name: Download python {{package_name}} package and dependencies to {{archive_path}}
  pip:
    name: "{{package_name}}"
    archive_path: "{{archive_path}}"
```
