### ISSUE TITLE
pkg5_publisher: cannot have two publishers in different locations with the same name

### ISSUE THREAD

**Issue by stauraum** [ansible/ansible#69095]
##### SUMMARY
If i add a second publisher with the name "solaris" the first publisher is deleted

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pkg5_publisher

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /home/<username>/git/ansible-syscfg/ansible.cfg
  configured module search path = ['/home/<username>/git/ansible-syscfg/modules']
  ansible python module location = /opt/<folder>/vens/ansible-2.9-py3/lib/python3.6/site-packages/ansible
  executable location = /opt/<folder>/vens/ansible-2.9-py3/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
```

##### OS / ENVIRONMENT
Solaris 11.4 SRU19

##### STEPS TO REPRODUCE

```
- name: Hinterlege Solaris 11 Repos
  pkg5_publisher: name=solaris origin=http://<reposerver>/solaris/ state=present
  when: ansible_container != "zone" and ansible_kernel == "5.11"

- name: Hinterlege Solaris 11.4 Oracle Solaris Cluster-Repo
  pkg5_publisher: name=solaris origin=http://<reposerver>/osc/solaris/ state=present
  when: ansible_container != "zone" and ansible_kernel == "5.11" and ansible_distribution_version == "11.4" and ansible_hostname == "<servername>"

- name: Hinterlege Solaris 11.4 HA-Cluster Repo
  pkg5_publisher: name=ha-cluster origin=http://<reposerver>/osc/ha-cluster/ state=present
  when: ansible_container != "zone" and ansible_kernel == "5.11" and ansible_distribution_version == "11.4" and ansible_hostname == "<servername>"
```

##### EXPECTED RESULTS
both repository's are present

##### ACTUAL RESULTS
The first is added and will be dropped by the second. only the last repository is present

```
root@<servername> ~ # pkg publisher
PUBLISHER                   TYPE     STATUS P LOCATION
solaris                     origin   online F http://<reposerver>/osc/solaris/
ha-cluster                  origin   online F http://<reposerver>/osc/ha-cluster/
```

**Comment by sivel** [comment]
Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.general

Please re-submit this issue in the above repository.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by wertel** [comment]
You need to use a list for 'origin' parameter.

```
- name: "publisher: set publishers"
  pkg5_publisher:
    name: "{{ item.name }}"
    sticky: "{{ item.sticky }}"
    origin: "{{ item.origin }}"
  with_items:
      - { name: 'solaris', origin: ['http://{{ repository_host }}/solaris-114', 'http://{{ repository_host }}/solaris-legacy'], sticky: true }
      - { name: 'Veritas', origin: 'http://{{ repository_host }}/veritas', sticky: false}
      - { name: 'Symantec', origin: 'http://{{ repository_host }}/symantec', sticky: false}
```
