### ISSUE TITLE
delegate_to not consider group variables

### ISSUE THREAD

**Issue by bert2002** [ansible/ansible#69091]
##### SUMMARY
I have different groups in my inventory files and each group as its own `ansible_ssh_common_args` definition with a different bastion host.
The problem is when using `delegate_to` in a task it is not using the `ansible_ssh_common_args` parameter unless its configured in `all`.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
# ansible --version
ansible 2.9.6
  config file = /home/user/git/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

```

##### CONFIGURATION
inventory (not working): 
```
all:
  vars:
    ansible_python_interpreter: auto_legacy_silent
  hosts:
  children:
    custom1:
      vars:
        ansible_ssh_common_args: -oUserKnownHostsFile='~/.ssh/known_hosts_test' -oProxyCommand='ssh -W %h:%p -q {{ hostvars["custom1-bastion-1"]["external_ip"] }}'
      hosts:
        custom1-bastion-1:
          ansible_host: 192.168.1.123
          internal_ip: 192.168.1.123
          external_ip: 192.168.1.123
    custom2:
      vars:
        ansible_ssh_common_args: -oUserKnownHostsFile='~/.ssh/known_hosts_test' -oProxyCommand='ssh -W %h:%p -q {{ hostvars["custom2-bastion-1"]["external_ip"] }}'
      hosts:
        custom2-bastion-1:
          ansible_host: 10.10.10.123
          internal_ip: 10.10.10.123
          external_ip: 10.10.10.123

```
inventory (working): 
```
all:
  vars:
    ansible_python_interpreter: auto_legacy_silent
    ansible_ssh_common_args: -oUserKnownHostsFile='~/.ssh/known_hosts_test' -oProxyCommand='ssh -W %h:%p -q {{ hostvars["custom1-bastion-1"]["external_ip"] }}'
  hosts:
  children:
    custom1:
      hosts:
        custom1-bastion-1:
          ansible_host: 192.168.1.123
          internal_ip: 192.168.1.123
          external_ip: 192.168.1.123
    custom2:
      hosts:
        custom2-bastion-1:
          ansible_host: 10.10.10.123
          internal_ip: 10.10.10.123
          external_ip: 10.10.10.123

```
When the configuration is like this then the `delgate_to` will use the `ansible_ssh_common_args` variable. Unfortunately this will not work if I want to have separate definitions for different groups.

##### OS / ENVIRONMENT
Debian 10 Buster

##### STEPS TO REPRODUCE

```yaml
- name: create directory
  file:
    path: /tmp/test/
    state: directory
    mode: '0700'
  delegate_to: "{{ test_host }}"
```
Please note that `test_host` is not in the inventory configuration.

##### EXPECTED RESULTS
Expected is that the ssh connection is opened through the bastion host configured in `ansible_ssh_common_args`.

##### ACTUAL RESULTS
The ssh connection gets opened directly from the computer where ansible is executed.
