### ISSUE TITLE
until module is ignored if when module is used in same task

### ISSUE THREAD

**Issue by rothgar** [ansible/ansible#6909]
I'm trying to retry a task when it fails but I only want the task to run if it needs to. I tried with ansible 1.5.2 and 1.6 and both times the following task does not enter the until loop.

``` yaml

---
 - hosts: salt-jlg.devel.apu.edu
   remote_user: jlg
   sudo: True
   vars:
     tools_version: "9.0.5.21788"
   tasks:
   - name: Check current vmware-tools
     shell: /usr/bin/vmware-toolbox-cmd -v
     register: vmware_version
     when: ansible_virtualization_type == "VMware"
     ignore_errors: True
  - name: Mount VMware Tools - Make sure you mount the ISO in VMware
    mount: name=/mnt/cdrom src=/dev/cdrom fstype=iso9660 opts=ro state=mounted
    register: result
    until: not result|failed
    retries: 5
    delay: 10
    ignore_errors: True
    when: not vmware_version.stdout.find( tools_version )|bool
```

If the test passes or fails the task output is "ok"

**Comment by ansibot** [comment]
Thanks for filing a ticket! I am the friendly GitHub Ansibot. I see you did not fill out your issue description based on our new issue template. Please copy the contents of this [template](https://raw2.github.com/ansible/ansible/devel/examples/issues/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket. 

Our system will automatically close tickets that do not have an issue template filled out within 7 days. Please note that due to large interest in Ansible, humans may not comment on your ticket if you ask them questions. Don't worry, you're still in the queue and the robots are looking after you.

**Comment by mpdehaan** [comment]
Looks like you have a weird indent error in your YAML above.

We can obviously test to see why that didn't produce an appropriate error for you, but please let us know if the above is correct.

**Comment by rothgar** [comment]
Indent errors are a result of copy/paste into github. They don't exist in the original playbook.

**Comment by jctanner** [comment]
@rothgar please show us the verbose ansible-playbook -vvvv output. I am unable to reproduce with this simplified test:

```
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - shell: exit 0
      register: result
      when: True
      until: result.rc != 0
      retries: 5
```

```
TASK: [shell exit 0] **********************************************************
<localhost> REMOTE_MODULE command exit 0 #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397497953.58-277426580589184 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397497953.58-277426580589184 && echo $HOME/.ansible/tmp/ansible-tmp-1397497953.58-277426580589184']
<localhost> PUT /tmp/tmplU31h3 TO /home/jtanner/.ansible/tmp/ansible-tmp-1397497953.58-277426580589184/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1397497953.58-277426580589184/command; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1397497953.58-277426580589184/ >/dev/null 2>&1']
<localhost> REMOTE_MODULE command exit 0 #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397497958.66-124360769250323 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397497958.66-124360769250323 && echo $HOME/.ansible/tmp/ansible-tmp-1397497958.66-124360769250323']
<localhost> PUT /tmp/tmptgJ1VE TO /home/jtanner/.ansible/tmp/ansible-tmp-1397497958.66-124360769250323/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1397497958.66-124360769250323/command; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1397497958.66-124360769250323/ >/dev/null 2>&1']
Result from run 1 is: {u'changed': True, u'end': u'2014-04-14 13:52:38.718134', u'stdout': u'', u'cmd': u'exit 0 ', u'rc': 0, u'start': u'2014-04-14 13:52:38.716411', 'attempts': 1, u'stderr': u'', u'delta': u'0:00:00.001723'}
<localhost> REMOTE_MODULE command exit 0 #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397497963.74-111411363617985 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397497963.74-111411363617985 && echo $HOME/.ansible/tmp/ansible-tmp-1397497963.74-111411363617985']
<localhost> PUT /tmp/tmp9dq0KN TO /home/jtanner/.ansible/tmp/ansible-tmp-1397497963.74-111411363617985/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1397497963.74-111411363617985/command; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1397497963.74-111411363617985/ >/dev/null 2>&1']
Result from run 2 is: {u'changed': True, u'end': u'2014-04-14 13:52:43.804358', u'stdout': u'', u'cmd': u'exit 0 ', u'rc': 0, u'start': u'2014-04-14 13:52:43.802042', 'attempts': 2, u'stderr': u'', u'delta': u'0:00:00.002316'}
<localhost> REMOTE_MODULE command exit 0 #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397497968.82-229795043727041 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397497968.82-229795043727041 && echo $HOME/.ansible/tmp/ansible-tmp-1397497968.82-229795043727041']
<localhost> PUT /tmp/tmpAydzXa TO /home/jtanner/.ansible/tmp/ansible-tmp-1397497968.82-229795043727041/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1397497968.82-229795043727041/command; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1397497968.82-229795043727041/ >/dev/null 2>&1']
Result from run 3 is: {u'changed': True, u'end': u'2014-04-14 13:52:48.883807', u'stdout': u'', u'cmd': u'exit 0 ', u'rc': 0, u'start': u'2014-04-14 13:52:48.881640', 'attempts': 3, u'stderr': u'', u'delta': u'0:00:00.002167'}
<localhost> REMOTE_MODULE command exit 0 #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397497973.91-199306519586054 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397497973.91-199306519586054 && echo $HOME/.ansible/tmp/ansible-tmp-1397497973.91-199306519586054']
<localhost> PUT /tmp/tmpZb6Jxd TO /home/jtanner/.ansible/tmp/ansible-tmp-1397497973.91-199306519586054/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1397497973.91-199306519586054/command; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1397497973.91-199306519586054/ >/dev/null 2>&1']
Result from run 4 is: {u'changed': True, u'end': u'2014-04-14 13:52:53.968549', u'stdout': u'', u'cmd': u'exit 0 ', u'rc': 0, u'start': u'2014-04-14 13:52:53.966313', 'attempts': 4, u'stderr': u'', u'delta': u'0:00:00.002236'}
<localhost> REMOTE_MODULE command exit 0 #USE_SHELL
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1397497978.98-125163890514370 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1397497978.98-125163890514370 && echo $HOME/.ansible/tmp/ansible-tmp-1397497978.98-125163890514370']
<localhost> PUT /tmp/tmpzq8Jnt TO /home/jtanner/.ansible/tmp/ansible-tmp-1397497978.98-125163890514370/command
<localhost> EXEC ['/bin/sh', '-c', '/usr/bin/python /home/jtanner/.ansible/tmp/ansible-tmp-1397497978.98-125163890514370/command; rm -rf /home/jtanner/.ansible/tmp/ansible-tmp-1397497978.98-125163890514370/ >/dev/null 2>&1']
Result from run 5 is: {u'changed': True, u'end': u'2014-04-14 13:52:59.046441', u'stdout': u'', u'cmd': u'exit 0 ', u'rc': 0, u'start': u'2014-04-14 13:52:59.044248', 'attempts': 5, u'stderr': u'', u'delta': u'0:00:00.002193'}
failed: [localhost] => {"attempts": 5, "changed": true, "cmd": "exit 0 ", "delta": "0:00:00.002193", "end": "2014-04-14 13:52:59.046441", "failed": true, "rc": 0, "start": "2014-04-14 13:52:59.044248"}
msg: Task failed as maximum retries was encountered
```
