### ISSUE TITLE
set_fact with "when" statement doesn't properly evaluate conditions

### ISSUE THREAD

**Issue by michaelsmoody** [ansible/ansible#69138]
##### SUMMARY

(First, I read the topics of a few hundred issues on Github, and none of them seemed to match this. However, If I missed it, or if I fundamentally misunderstand something here, I apologize in advance)

We're attempting to set a variable, only if it is not already set, and perform some minor input validation (the variable must be set to one of a few options). A practical example of this would be defining an environment (staging/development/production, etc).

When attempting to use a task to set_fact, we're running into issues. Using "when:" where the condition is `is undefined` works as expected, and the variable is set.

Using a condition where we try to match it, equal or does not equal `=` or `!=` does not work, and the variable remains as originally set via `-e`

We are using tags, so as to quickly iterate through out tasks, though no documentation I've found yet shows that a tag+when+set_fact would cause an issue (and apologies if there is).

I'll write the working and not working tests, including the more complex multi-condition tests.

EDIT: Realized my examples had the wrong tag, but that is not the issue, only an issue with my issue writing skills. Corrected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

set_fact
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/michaelsmoody/Development/ansible-playbooks/ansible.cfg
  configured module search path = ['/Users/michaelsmoody/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/Users/michaelsmoody/Development/ansible-playbooks/ansible.cfg) = ['/Users/michaelsmoody/Development/ansible-playbooks/inventory']
```

##### OS / ENVIRONMENT

Any target OS thus far.

##### STEPS TO REPRODUCE

`ansible-playbook -i inventory/hosts -u ansible-control-user -k -l 192.168.1.100 main.yml --tags 'variable-test-task' -e "deploy_environment=Snails"`

```yaml
###This works as expected
- name: "Setting Deploy Environment Variable for Deployment Tasks"
  set_fact:
    deploy_environment: "Development"

  when: deploy_environment is undefined
  
  tags:
    - variable-test-task

###This does not work
- name: "Setting Deploy Environment Variable for Deployment Tasks"
  set_fact:
    deploy_environment: "Development"

  when: deploy_environment != "Development"
  
  tags:
    - variable-test-task

###This does not work
- name: "Setting Deploy Environment Variable for Deployment Tasks"
  set_fact:
    deploy_environment: "Development"

  when: deploy_environment == "Production"
  
  tags:
    - variable-test-task

###This does not work, playing with syntax, might be expected
- name: "Setting Deploy Environment Variable for Deployment Tasks"
  set_fact:
    deploy_environment: "Development"

  when: not (deploy_environment is defined) or not ((deploy_environment == 'Development') or (deploy_environment == 'Production'))
  
  tags:
    - variable-test-task

###This does not work, playing with syntax, might be expected
- name: "Setting Deploy Environment Variable for Deployment Tasks"
  set_fact:
    deploy_environment: "Development"

  when: (deploy_environment is undefined) or ((deploy_environment != 'Development') or (deploy_environment != 'Production'))
  
  tags:
    - variable-test-task

###This does not work, playing with syntax, might be expected
- name: "Setting Deploy Environment Variable for Deployment Tasks"
  set_fact:
    deploy_environment: "Development"

  when: (deploy_environment != 'Development') or (deploy_environment != 'Production')
  
  tags:
    - variable-test-task
```

##### EXPECTED RESULTS

Variable is set to "Development" as a default, if undefined. Variable is set to "Development" if not set already to "Development" Variable is set to "Development" if not "Development" or "Production"

##### ACTUAL RESULTS

Variable remains as set "Snails" for instance.

```paste below
TASK [deploy : Setting Deploy Environment Variable for Deployment Tasks] *****************************************************************************************
task path: /Users/michaelsmoody/Development/ansible-playbooks/roles/deploy_website/tasks/includes/deploy_website.yml:33
ok: [192.168.1.100] => {
    "ansible_facts": {
        "deploy_environment": "Development"
    },
    "changed": false
}

TASK [deploy : debug] ********************************************************************************************************************************************
task path: /Users/michaelsmoody/Development/ansible-playbooks/roles/deploy_website/tasks/includes/deploy_website.yml:49
ok: [192.168.1.100] => {
    "msg": "Snails"
}
```
