### ISSUE TITLE
Add ability to create Git module archive with file filter

### ISSUE THREAD

**Issue by michaelsmoody** [ansible/ansible#69137]
##### SUMMARY

Though possibly not a common use case, it would be beneficial to supply arguments to the Git module that allows for a subset of files to be retrieved (specifically for the purposes of creating an archive).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Git

##### ADDITIONAL INFORMATION

This is perhaps a bit of an edge case.

We use the git module "archive" argument to create an archive for a point-in-time (Git Commit ID/Tag/Branch/Etc).

However, we also create incremental deploys, which contains a delta archive between Commit ID: X, and Commit ID: Y. This is helpful to only transfer the files which have changed between two points, releases, tags, branches, etc. Reference https://git-scm.com/docs/git-archive where "<path>" is supplied. The way we handle the delta archive is as follows:

`git archive -o archive.zip HEAD $(git diff --diff-filter=ACMTUXB --name-only {{ current_commit_id }} {{ target_commit_id }})'`

This creates archive.zip with only the files which have changed between X and Y. (Later versions of Git can use --diff-filter=dr to filter out deletes and renames).

However, it could be more simply (to extend to further use cases):

`git archive -o archive.zip HEAD <path>`

We handle deletes and renames via:
`git diff --diff-filter=D --name-only {{ current_commit_id }}`
`git diff --diff-filter=R --name-only {{ current_commit_id }}`
And build that file list to handle with the file/win_file modules.

Actually, in the case of renames, since Ansible has no "move" module, we create a script/powershell to take care of it, basically by this method, for instance in Powershell:

`{{ git_files_to_move + [ item | regex_replace("/", "\\") | regex_replace("R\d{3}\t", "Move-Item -Force -Path ''C:\\PathToFiles\\") | regex_replace("\t", "'' -Destination ''C:\\PathToFiles\\") | regex_replace("$", "''") ] }}`

It's ugly, but since there's no "move" module (for idempotence reasons, as I understand it), we do what we need to do.

Back to the point of the feature request, extending the Git module to allow an argument of files specifically for archive purposes, would be immensely helpful to this and varying other workflows.
Extending it even further to create deltas between gitrefs would be even better, and example of which is provided below.

```yaml
##With supplied file list
- name: "Pull down codebase via Git for version: {{ deploy_version }} (Incremental Deploy)"
  git:
    repo: "git@{{ deploy_git_username }}:{{ deploy_git_repository_path }}"
    dest: "{{ deploy_git_local_repository_path }}"
    archive: "{{ deploy_git_full_archive_zipfile_prefix }}{{ deploy_version }}.zip"
    version: "{{ deploy_version }}"
    file_filter: "{{ git_file_list }}"
    accept_hostkey: yes
  delegate_to: localhost
  become: no
  register: git_fetch_pull

##With git diff method
- name: "Pull down codebase via Git for version: {{ deploy_version }} (Incremental Deploy)"
  git:
    repo: "git@{{ deploy_git_username }}:{{ deploy_git_repository_path }}"
    dest: "{{ deploy_git_local_repository_path }}"
    archive: "{{ deploy_git_full_archive_zipfile_prefix }}{{ deploy_version }}.zip"
    version: "{{ deploy_version }}"
    old_gitref: "{{ current_commit_id }}"
    new_gitref: "{{ target_commit_id }}"
    gitref_diff_filter: "ACMTUXB"
    accept_hostkey: yes
  delegate_to: localhost
  become: no
  register: git_fetch_pull
```
