### ISSUE TITLE
vmware_guest - allow specifying OU when joining Windows guest to a domain

### ISSUE THREAD

**Issue by senilio** [ansible/ansible#69146]
##### SUMMARY

When using the joindomain directive in vmware_guest, any computer automatically joins into a default directory path, which is usually CN=Computers in the directory root.

A new directive like joindomain_ou could be implemented the be able to specify the directory path a computer will be joined into.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- joindomain_ou (string): AD domain path to join, optional, used only with joindomain

##### ADDITIONAL INFORMATION

When defined, it will allow a Windows guest to be automatically joined to the OU of your choice, instead of being joined to the default path in AD.

```yaml

  vmware_guest:
  ...
    customization:
      dns_servers: "{{ vm_dns }}"
      domain: "{{ vm_domain }}"
      hostname: "{{ inventory_hostname_short }}"
      password: "{{ vm_administrator_password }}"
      joindomain: "{{ vm_joindomain | default(omit) }}"
      joindomain_ou: "{{ vm_joindomain_ou }}"
      domainadmin: "{{ vm_domainadmin }}"
      domainadminpassword: "{{ vm_domainadminpassword }}"
```
