### ISSUE TITLE
with_nested should also handle lists of hashes

### ISSUE THREAD

**Issue by akkie** [ansible/ansible#6916]
##### Issue Type:

“Feature Idea”
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 14.04
##### Summary:

Currently `with_nested` does only handle lists with scalar values. But it should also handle lists of hashes.
##### Steps To Reproduce:

Consider the following use case:

``` yaml
- name: Provision instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - volumes: [{dev: /dev/hda1, size: 10}]
  tasks:
    # previous tasks

    - name: Attach volumes to previously created instances
      local_action:
        module: ec2_vol
        instance: "{{ item[0].id }}"
        device_name: "{{ item[1].dev }}"
        volume_size: "{{ item[1].size }}"
        region: $aws_region
      with_nested:
        ec2.instances
        volumes
      register: ec2_volumes
      when: volumes is defined
```
##### Expected Results:

The module should create multiple devices for every instance.
##### Actual Results:

Ansible fails with the message:

```
fatal: [localhost] => One or more undefined variables: 'str object' has no attribute 'id'
```
