### ISSUE TITLE
Cloning template to create VM fails with "msg": "Failed to create a virtual machine : The name 'test0' already exists."}

### ISSUE THREAD

**Issue by srivaa31** [ansible/ansible#69185]
##### SUMMARY

Deploying a VM from a cent OS 7/8 template fails with VM already exists error message. The datastore where the VM template is present is a shared datastore and is created through one of the corporate internal deployment and orchestration software. 
Noticed that there was a similar issue in the past . reference here : #28250
I tried the work around mentioned in comments by different folks. none worked 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 8
vSphere Client version 6.7.0.42000

##### STEPS TO REPRODUCE

```yaml
---

- name: Clone the template
  vmware_guest:
    hostname: "{{ vmware_server }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_pass }}"
    validate_certs: False
    name: "{{ item.name }}"
    template: "{{ item.template }}"
    datacenter: "{{ source_datacenter_name }}"
    datastore: "{{ source_datastore }}"
    folder: "{{ source_datacenter_name }}/vm"
    #folder: /
    state: present
    #state: poweredon
    esxi_hostname: "{{ item.esxi_host }}"
    wait_for_ip_address: yes
  with_items: "{{ vms }}"
  register: result

```

##### EXPECTED RESULTS

Vcenter should display in recent task that target VM is created successfully and VM is powered on and assigned an IP through DHCP in  my case for further action.

##### ACTUAL RESULTS

I get the error message (red bang) in vcenter that vm with the name already exists, though it creates the VM successfully and is functional .This impacts subsequent test cases for execution in my playbook.(Although that can be avoided , but it doesn't gives the clean impression) 
Upon manually creating the VM with a new name ,the above error message is not observed ,ruling out the possibility of open issues with vmware in my opinion.

```paste below

```
