### ISSUE TITLE
Strange behaviour with required / required_* module parameters

### ISSUE THREAD

**Issue by tremble** [ansible/ansible#69190]
##### SUMMARY

The 'required', 'required_together', 'required_if', etc parameters when creating modules behave oddly when passed `None`.  This can be achieved a couple of ways in a playbook:

```
- some_module:
    arg_a: null
    arg_b: ~
    arg_c:
```

An example can be seen in the lambda integration tests:
https://github.com/ansible-collections/community.aws/blob/dedf734b21def6c1968869f8ac57cf59a20ee18f/tests/integration/targets/aws_lambda/tasks/main.yml#L55

When this is done the type checking is ignored and the argument is treated as having been passed.  This means that None can end up propagating as a value even though the argument is set as 'required' or 'required_together'.  Which is extremely counterintuitive and means that as a module author I can't actually rely on any of the 'required' options actually existing.

This behaviour appears to have been introduced in commit
e4e913b33131aed03123dab9932aaa44f0183c09

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/module_utils/basic.py

##### ANSIBLE VERSION
ansible 

##### CONFIGURATION
```
ansible 2.9.6
  config file = /home/mchappel/.ansible.cfg
  configured module search path = ['/home/mchappel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mchappel/vcs/redhat/ansicloud-full/python3/ansible-2.9/lib/python3.6/site-packages/ansible
  executable location = /home/mchappel/vcs/redhat/ansicloud-full/python3/ansible-2.9/bin/ansible
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

```
ansible 2.10.0.dev0
  config file = /home/mchappel/.ansible.cfg
  configured module search path = ['/home/mchappel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mchappel/vcs/ansible/ansible/lib/ansible
  executable location = /home/mchappel/vcs/ansible/ansible/bin/ansible
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
##### OS / ENVIRONMENT

This can be seen in the standard integration test environment

##### STEPS TO REPRODUCE

In a module (example taken from community.aws.lambda) define:
```
def main():
    argument_spec = dict(
        name=dict(required=True),
...
        vpc_subnet_ids=dict(type='list', elements='str'),
        vpc_security_group_ids=dict(type='list', elements='str'),
...
    )
...
    required_together = [['vpc_subnet_ids', 'vpc_security_group_ids']]
...
    module = AnsibleAWSModule(argument_spec=argument_spec,
...
                              required_together=required_together,
...
    )
```

When invoking the module use `null` as the value (or ~, or leave it blank)  This may be desired when (for example) module_defaults are in use.

```
  - name: test state=present with security group but no vpc 
    lambda:
      name: '{{lambda_function_name}}'
      runtime: python2.7
      role: ansible_lambda_role
      zip_file: '{{zip_res.dest}}'
      handler: null
      description: null
      vpc_subnet_ids: null
      vpc_security_group_ids: sg-FA6E
      environment_variables: null
      dead_letter_arn: null
    register: result
    ignore_errors: true
  - name: assert lambda fails with proper message
    assert:
      that:
      - result is failed
      - result.msg != "MODULE FAILURE"
      - result.changed == False
      - '"requires at least one security group and one subnet" in result.msg'
```

##### EXPECTED RESULTS

The test should 'pass' (ie the module should complain that the argument is missing)

##### ACTUAL RESULTS

The test fails because although 'required' and defined as needing to be a list of strings, `None` is treated as an acceptable value for `vpc_subnet_ids`
