### ISSUE TITLE
datadog_monitor does not accept "process alert "

### ISSUE THREAD

**Issue by asciifaceman** [ansible/ansible#69219]
##### SUMMARY
Datadog built-in module failing to deploy a "process alert" type which is a valid type of monitor.

This worked on ansible 2.6 as I referenced here: https://github.com/DataDog/ansible-datadog/issues/219

I just updated to Ansible 2.9.7 and found the issue still.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`datadog_monitor`

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = None
  configured module search path = ['/Users/ccorbett/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:27) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OSX 10.13.6
Python 3.7.7

##### STEPS TO REPRODUCE

```yaml
    - name: Deploy datadog monitor
      delegate_to: localhost
      register: datadogstatDeploy
      datadog_monitor:
        type: "process alert"
        thresholds:
          critical: 0
        name: "your alert name"
        state: "present"
        query: "your alert query"
        message: "your alert message"
        api_key: "{{ datadog.apiKey }}"
        app_key: "{{ datadog.appKey }}"
```

##### EXPECTED RESULTS

The process monitor to deploy.

##### ACTUAL RESULTS

```paste below
FAILED! => {"changed": false, "msg": "value of type must be one of: metric alert, service check, event alert, got: process alert"}
```
