### ISSUE TITLE
task names do not appear if display_skipped_hosts is false

### ISSUE THREAD

**Issue by rwagnergit** [ansible/ansible#69216]
##### SUMMARY

The name of certain tasks (e.g., include_role) does not appear in output when display_skipped_hosts = False.  This was reported on the ansible google group at https://groups.google.com/d/msg/ansible-project/d04DcvvsaUU/oYLuVSCEBwAJ, but looks like no one ever opened a bug report.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role, but may be elsewhere
##### ANSIBLE VERSION

```
ansible --version
ansible 2.9.4
  config file = /home/rowagn/r/ansible.cfg
  configured module search path = [u'/home/rowagn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /sso/sfw/virtualenv/ansible29/lib/python2.7/site-packages/ansible-2.9.4-py2.7.egg/ansible
  executable location = /sso/sfw/virtualenv/ansible29/bin/ansible
  python version = 2.7.17 (default, Feb  6 2020, 10:54:17) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
ansible-config dump --only-changed
DISPLAY_SKIPPED_HOSTS(/home/rowagn/r/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Don't think it's OS specific, but I'm on Ubuntu 16.04

##### STEPS TO REPRODUCE

Set display_skipped_hosts = False and run below playbook.  Note how task names ("including role with v = ?") are not displayed.  Switch display_skipped_hosts = True and note how task names to appear.

```yaml
(ansible29) rowagn@localhost:~/r$ cat roles/r/tasks/main.yml 
---
- name: do something
  debug: "Doing something with {{ v }}"

(ansible29) rowagn@localhost:~/r$ cat test.yml 
---
- hosts: all
  gather_facts: no
  tasks:
  - name: including role with v = a
    include_role:
      role: r
    vars:
      v: a

  - name: including role with v = b
    include_role:
      role: r
    vars:
      v: b

(ansible29) rowagn@localhost:~/r$ cat hosts
localhost
(ansible29) rowagn@localhost:~/r$ cat ansible.cfg 
[defaults]
display_skipped_hosts = False
(ansible29) rowagn@localhost:~/r$ ansible-playbook test.yml -i ./hosts 

```

##### EXPECTED RESULTS

Task names should be output.  See the following output when display_skipped_hosts=True:
```
(ansible29) rowagn@localhost:~/r$ cat ansible.cfg 
[defaults]
display_skipped_hosts = True
(ansible29) rowagn@localhost:~/r$ ansible-playbook test.yml -i ./hosts 0< /dev/null

PLAY [all] *********************************************************************

TASK [including role with v = a] ***********************************************

TASK [r : do something] ********************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK [including role with v = b] ***********************************************

TASK [r : do something] ********************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

##### ACTUAL RESULTS

When running with display_skipped_hosts = False, task names are missing.

```
(ansible29) rowagn@localhost:~/r$ cat ansible.cfg 
[defaults]
display_skipped_hosts = False
(ansible29) rowagn@localhost:~/r$ ansible-playbook test.yml -i ./hosts 0< /dev/null

PLAY [all] *********************************************************************

TASK [r : do something] ********************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK [r : do something] ********************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


```
