### ISSUE TITLE
New merge lists plugin from a given key 

### ISSUE THREAD

**Issue by imjoseangel** [ansible/ansible#69211]
##### SUMMARY

Given two lists like:

```yaml
list1:
  - name: myname01
    param01: myparam01
  - name: myname02
    param01: myparam02

list2:
  - name: myname01
    param01: myparam03
  - name: myname02
    param02: myparam04
  - name: myname03
    param03: myparam03
```

When doing:

```yaml
"{{ query('mergelist', 'name', list1, list2) }}"
```

The results will be:

```yaml
  - name: myname01
    param01: myparam03
  - name: myname02
    param01: myparam02
    param02: myparam04
  - name: myname03
    param03: myparam03
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`mergelist`
##### ADDITIONAL INFORMATION

I have already developed the solution. I really think it could be really useful in the Ansible Core. Please confirm.

```yaml
  - name: Basic usage
    debug:
      msg: "{{ query('mergelist', 'name', list1, list2) }}"
```
