### ISSUE TITLE
net_get - attribute _connect_uncached error when being used as first task in a playbook

### ISSUE THREAD

**Issue by danpospisil** [ansible/ansible#69214]
##### SUMMARY
When I have only this task in playbook:
```
  - name: Copy file to local
    net_get:
      src: /test.txt
      dest: test.txt2
```
I get this error message:
```
TASK [Copy file to local] ********************************************************************************************************************************************************************************task path: /mnt/c/Users/daniel.pospisil/Desktop/ansible/playbook.yml:22
<192.168.239.21> attempting to start connection
<192.168.239.21> using connection plugin network_cli
<192.168.239.21> local domain socket does not exist, starting it
<192.168.239.21> control socket path is /home/daniel/.ansible/pc/8bb5926241
<192.168.239.21> local domain socket listeners started successfully
<192.168.239.21> loaded cliconf plugin routeros from path /usr/local/lib/python3.6/dist-packages/ansible/plugins/cliconf/routeros.py for network_os routeros
<192.168.239.21> 
<192.168.239.21> local domain socket path is /home/daniel/.ansible/pc/8bb5926241
Getting network OS from inventory
fatal: [mikrotik]: FAILED! => {
    "changed": true,
    "destination": "/mnt/c/Users/daniel.pospisil/Desktop/ansible/test.txt2",
    "msg": "Exception received : 'NoneType' object has no attribute '_connect_uncached'"
}
```
If I prepend a task which opens a SSH connection to my device before this task then everything works properly (eg. routeros_command). So this led me to this merge request https://github.com/ansible/ansible/pull/62103 and I tried to use the same approach - add `conn.get_capabilities()` after calling `conn = Connection(socket_path)` in `net_get.py` and indeed it started to work. So the same fix should be applied to this plugin as well. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
net_get

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = None
  configured module search path = ['/home/daniel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 10 - using WSL with Ubuntu 18.04

##### STEPS TO REPRODUCE

playbook.yml:
```yaml
- name: Mikrotik Backup Playbook
  hosts: routeros

  - name: Copy file to local
    net_get:
      src: /test.txt
      dest: test.txt2
```

group_vars/routeros.yml:
```yaml
ansible_connection: network_cli
ansible_network_os: routeros
ansible_become: yes
ansible_become_method: enable
```
hosts:
```
[routeros]
mikrotik ansible_host=192.168.239.21 ansible_user=admin ansible_password=pass
```

##### EXPECTED RESULTS

```paste below
TASK [Copy file to local] **********************************************************************************************************************************************************************************
ok: [mikrotik]
```

##### ACTUAL RESULTS

```paste below
TASK [Copy file to local] **********************************************************************************************************************************************************************************
fatal: [mikrotik]: FAILED! => {"changed": true, "destination": "/mnt/c/Users/daniel.pospisil/Desktop/ansible/test.txt2", "msg": "Exception received : 'NoneType' object has no attribute '_connect_uncached'"}
```
