### ISSUE TITLE
when using dynamic inventory what are good practices for public cloud in provisioning 

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#69227]
##### SUMMARY
I would love some discussion on this problem I am having with public workshops for the Ansible Automation Platform.

Originally->
- provision instances on AWS (using ec2 modules)
- use add_host to create in-memory inventory for subsequent plays 
- run on those new groups (create by add_host) in subsequent plays to configure and automate the newly created instances

###### PROBLEM STATEMENT WITH ADD_HOST
- the add_host required multiple loops for each type of instance.  If I had 50 node1s that would require you to loop 50 times (just for node1).  If i had four nodes (ansible, node1, node2, node3) times 50 student, this would require 200 loops.  This also required a get_info (e.g. ec2_instance_info) four times (once for each instance type).  (see example below)
- as you can see below the add_host is also long... 13 lines+ for each host, which literally was creating a 57+ line add_Host section per workshop type or 360 lines of Ansible Playbook just dealing with inventory creation.  The dynamic inventory approach can shrink 6 files of 360+ lines and multiple tasks into one file of 44 lines (and honestly without security workshop would be like 30 lines!) 
- the templates with add_host were horrendous! For example we could not use Ansible's natural parallelism to template out files on each device until we got inventory sorted, so you would have to loop through facts for each type of instance, map that to the correct student using tags, then subsequent roles would be clean again (see example below)

NOW WITH DYNAMIC INVENTORY! ->
- point to empty aws_ec2.yml plugin before running ansible playbook (e.g. in ansible.cfg I am pointing to the aws_ecw2.yml `inventory = aws_ec2.yml`
- provision instances on AWS (using ec2 modules)
- template out and create the `aws_ec2.yml` file (here is an example https://gist.github.com/IPvSean/86050b4a5daa93d9336e4e18a81bca66) 
- meta refresh
```
- name: refresh AWS inventory information
  meta: refresh_inventory
```
- run on those new groups (create by add_host) in subsequent plays to configure and automate the newly created instances

###### PROBLEM STATEMENT WITH DYNAMIC INVENTORY
all in all this is a MUCH BETTER approach.  However I am hitting one problem.  If I kick off two Ansible Playbooks at the same time (e.g. one for a windows automation workshop, and one for a networking workshop) they will now contest for the `aws_ec2.yml` file.  Depending on how fast the Ansible Playbook takes to run they could conflict that file.  Apparently the GPTE team is kicking off tons of Ansible Playbooks from the same source...

- Would tower solve this naturally? 
- Is there a way I could point inventory mid-play, so that I am not hardcoding the inventory in Ansible.cfg and gain the advantage of the add_host method?

Talking to @s-hertel one of the methods we were thinking of was this->

a subsequent role (this ones just waits for things to boot) was this->
```
- name: wait for all nodes to have SSH reachability
  hosts: "control_nodes:lab_hosts"
  become: true
  gather_facts: false
  roles:
    - connectivity_test
```

what about just switching this to-> 

```
- name: wait for all nodes to have SSH reachability
  hosts: "control_nodes_{{ec2_name_prefix}}:lab_hosts_{{ec2_name_prefix}}"
  become: true
  gather_facts: false
  roles:
    - connectivity_test
```

Think of the ec2_name_prefix as the workshop name which is a unique value per workshop.

I then could use an inventory folder versus a single file and pull any inventories that are currently being tested... so even if 10 Ansible Playbooks are loading at the same time... it would be filtering out the non-relevant instances.

I still think this is over complicated.... if there was just a way to set the inventory somehow mid-play this would greatly make this super easy...

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
inventory plugins

##### ADDITIONAL INFORMATION
Here is what add_host would look like (from above description)

```
- name: add hosts to groups (ANSIBLE RHEL MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes
  with_items:
    - "{{ node1_node_facts.instances }}"
    - "{{ node2_node_facts.instances }}"
    - "{{ node3_node_facts.instances }}"
  changed_when: false
```

example of bad templating that had to be done pre-dynamic inventory plugin
```
{% for vm in rtr1_node_facts.instances %}
{% if 'student' + item == vm.tags.Student %}
{{ vm.tags.short_name }} ansible_host={{ vm.public_ip_address }} private_ip={{ vm.private_ip_address }}
{% endif %}
{% endfor %}
```
you had to loop through all facts, then try to map the student to the correct instance within the facts... this required multiple loops..... and is really hard for folks to read and understand what was happening.
