### ISSUE TITLE
get_url: failed to create temporary content file: (''The read operation timed out'',)

### ISSUE THREAD

**Issue by ReyRen** [ansible/ansible#69247]
##### SUMMARY

When I use `get_url` to download some items on remote host, it will get error: "failed to create temporary content file: (''The read operation timed out'',)". But this download operation seems good  in the localhost. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`lib/ansible/modules/net_tools/basics/get_url.py`

I tried change remote_tmp and local_tmp following https://github.com/ansible/ansible/issues/18894#issuecomment-315792098
and also tried upgrade or install the urllib3. 
All useless. 

##### ANSIBLE VERSION

```
ansible 2.9.5
  config file = /root/K8s4ML/ansible.cfg
  configured module search path = [u'/root/K8s4ML/kubespray/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/root/K8s4ML/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/root/K8s4ML/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=5m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null
ANSIBLE_SSH_CONTROL_PATH(/root/K8s4ML/ansible.cfg) = ~/.ssh/ansible-%%r@%%h:%%p
CACHE_PLUGIN(/root/K8s4ML/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/root/K8s4ML/ansible.cfg) = /var/tmp/ansible_cache
CACHE_PLUGIN_TIMEOUT(/root/K8s4ML/ansible.cfg) = 86400
DEFAULT_FORKS(/root/K8s4ML/ansible.cfg) = 25
DEFAULT_GATHERING(/root/K8s4ML/ansible.cfg) = smart
DEFAULT_HOST_LIST(/root/K8s4ML/ansible.cfg) = [u'/root/K8s4ML/config/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/root/K8s4ML/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/root/K8s4ML/ansible.cfg) = /root/.ansible/tmp/ansible-local-24185ZExTBx
DEFAULT_MODULE_PATH(/root/K8s4ML/ansible.cfg) = [u'/root/K8s4ML/kubespray/library']
DEFAULT_ROLES_PATH(/root/K8s4ML/ansible.cfg) = [u'/root/K8s4ML/galaxy-roles', u'/root/K8s4ML/roles', u'/root/K8s4ML/kubespray/roles']
DEFAULT_STDOUT_CALLBACK(/root/K8s4ML/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/root/K8s4ML/ansible.cfg) = 100
DEPRECATION_WARNINGS(/root/K8s4ML/ansible.cfg) = False
HOST_KEY_CHECKING(/root/K8s4ML/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

##### STEPS TO REPRODUCE

```yaml
- name: download_file | Download item
    get_url:
      url: "{{ download.url }}"
      dest: "{{ file_path_cached if download_localhost else download.dest }}"
      owner: "{{ omit if download_localhost else (download.owner | default(omit)) }}"
      mode: "{{ omit if download_localhost else (download.mode | default(omit)) }}"
      checksum: "{{ 'sha256:' + download.sha256 if download.sha256 or omit }}"
      validate_certs: "{{ download_validate_certs }}"
      url_username: "{{ download.username | default(omit) }}"
      url_password: "{{ download.password | default(omit) }}"
      force_basic_auth: "{{ download.force_basic_auth | default(omit) }}"
    delegate_to: "{{ download_delegate if download_run_once else inventory_hostname }}"
    run_once: "{{ download_run_once }}"
    register: get_url_result
    become: "{{ not download_localhost }}"
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 4
    delay: "{{ retry_stagger | default(5) }}"
```

https://github.com/ReyRen/K8s4ML/blob/master/kubespray/roles/download/tasks/download_file.yml#L37
##### ACTUAL RESULTS

```paste below
<192.168.0.211> Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017                                            
debug1: Reading configuration data /etc/ssh/ssh_config                                                                                                        
debug1: /etc/ssh/ssh_config line 19: Applying options for *                                                                                                   
debug1: auto-mux: Trying existing master                                                                                                                      
debug2: fd 3 setting O_NONBLOCK                                                                                                                               
debug2: mux_client_hello_exchange: master version 4                                                                                                           
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote                                                                                           
debug3: mux_client_request_session: entering                                                                                                                  
debug3: mux_client_request_alive: entering                                                                                                                    
debug3: mux_client_request_alive: done pid = 21007                                                                                                            
debug3: mux_client_request_session: session request sent                                                                                                      
debug1: mux_client_request_session: master session id: 2                                                                                                      
debug3: mux_client_read_packet: read header failed: Broken pipe                                                                                               
debug2: Received exit status from master 1                                                                                                                    
FAILED - RETRYING: download_file | Download item (2 retries left).Result was: changed=false                                                                   
  attempts: 3                                                                                                                                                 
  elapsed: 0                                                                                                                                                  
  invocation:                                                                                                                                                 
    module_args:                                                                                                                                              
      attributes: null                                                                                                                                        
      backup: null                                                                                                                                            
      checksum: sha256:2ebc93a6f64419e5e7f26a4674c6784463c7b2a51c0afe8ec2c0423471e7cec3                                                                       
      client_cert: null                                                                                                                                       
      client_key: null                                                                                                                                        
      content: null                                                                                                                                           
      delimiter: null                                                                                                                                         
      dest: /tmp/releases/kubeadm-v1.15.11-amd64                                                                                                              
      directory_mode: null
      follow: false
      force_basic_auth: false
      group: null
      headers: null
      http_agent: ansible-httpget
      mode: '0755'
      owner: root
      regexp: null
      remote_src: null
      selevel: null
      serole: null
      setype: null
      seuser: null
      sha256sum: ''
      src: null
      timeout: 10
      tmp_dest: null
      unsafe_writes: null
      url: https://storage.googleapis.com/kubernetes-release/release/v1.15.11/bin/linux/amd64/kubeadm
      url_password: null
      url_username: null
      use_proxy: true
      validate_certs: true
  msg: 'failed to create temporary content file: (''The read operation timed out'',)'
  retries: 5
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/net_tools/basics/get_url.py
Pipelining is enabled.

```
Thanks in advance
