### ISSUE TITLE
Jinja2_native and missing quotes in string

### ISSUE THREAD

**Issue by bogd** [ansible/ansible#69242]
##### SUMMARY

When using a multiline string with multiple quotes, some of the quotes disappear if jinja2_native is enabled. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

jinja2_native

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=180s -o StrictHostKeyChecking=no
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
DEFAULT_JINJA2_NATIVE(/etc/ansible/ansible.cfg) = True
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/ansible_key
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - vars:
      port: 20200
      cmd: >
        add chain=dstnat && dst-port="{{port}}"
        comment="{{ansible_host}} - SSH for {{inventory_hostname}}" 
        dst-port="{{ port }}" protocol=tcp 
        }'
    debug:
      msg: "{{cmd}}"
    tags: 
    - networking
```

##### EXPECTED RESULTS

All quotes in the multiline string should be kept.

##### ACTUAL RESULTS

Some of the quotes simply disappear, changing the string (and the number of arguments in the command that is actually sent to the network device - in my case, a Mikrotik router). 

The problem goes away if I set jinja2_native back to False in ansible.cfg.

More details on the issue (and some additional samples) in the issue I posted on SO before narrowing this down to jinja2_native: [link](https://stackoverflow.com/questions/61510884/ansible-multiline-string-with-multiple-quotes)

```paste below
# ansible-playbook test.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *****************************************************************************************************************

TASK [debug] *********************************************************************************************************************
Thursday 30 April 2020  00:00:51 +0300 (0:00:00.032)       0:00:00.032 ******** 
ok: [localhost] => {
    "msg": "add chain=dstnat && dst-port=\"20200 comment=127.0.0.1 - SSH for localhost  dst-port=20200\" protocol=tcp  }'\n"
}
```
