### ISSUE TITLE
Change comment string in template

### ISSUE THREAD

**Issue by empire** [ansible/ansible#69254]
##### SUMMARY
Add comment_start_string and comment_end_string to template plugin.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
template

##### ADDITIONAL INFORMATION
In some situation, we need to change comment behavior of template plugin, for an example macros in Zabbix is like {#MACRO}.

```yaml
- name: Render a template with "comment_start_string" set to [#
  template:
    src: template.xml.j2
    dest: template.xml
    comment_start_string: "[#"
    comment_end_string: "#]"
```
