### ISSUE TITLE
yum state=absent doesnt expand file names

### ISSUE THREAD

**Issue by marafa** [ansible/ansible#69251]
##### SUMMARY

when running this task
```
  - name: Erase all evolution name packages
    dnf: name={{ item }} state=absent
    with_items:
      - "evolution*"
```
fails with `Failed to install some of the specified packages`
verbose output shows 
```
    "failures": [
        "evolution* - No match for argument: evolution*",
```
i do recall that it _used_ to work but cannot recall which version

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: yum

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /home/marafa/bin/ansible/pi/ansible.cfg
  configured module search path = ['/home/marafa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]

```

##### CONFIGURATION

```paste below

ANSIBLE_PIPELINING(/home/marafa/bin/ansible/pi/ansible.cfg) = True
DEFAULT_CALLBACK_PLUGIN_PATH(/home/marafa/bin/ansible/pi/ansible.cfg) = ['/home/marafa/bin/ansib>
DEFAULT_CALLBACK_WHITELIST(/home/marafa/bin/ansible/pi/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/marafa/bin/ansible/pi/ansible.cfg) = 50
DEFAULT_LOG_PATH(/home/marafa/bin/ansible/pi/ansible.cfg) = /home/marafa/bin/ansible/pi/log/ansi>
DEFAULT_STDOUT_CALLBACK(/home/marafa/bin/ansible/pi/ansible.cfg) = debug
DEFAULT_STRATEGY(/home/marafa/bin/ansible/pi/ansible.cfg) = free
HOST_KEY_CHECKING(/home/marafa/bin/ansible/pi/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/marafa/bin/ansible/pi/ansible.cfg) = False

```

##### STEPS TO REPRODUCE

Fedora release 32 (Thirty Two)

```yaml
  - name: Erase all evolution name packages
    dnf: name={{ item }} state=absent
    with_items:
      - "evolution*"
```

##### EXPECTED RESULTS

expands the file name and uninstall the package

##### ACTUAL RESULTS

errors out
with 
```
    "failures": [
        "evolution* - No match for argument: evolution*",
```

```paste below

```
