### ISSUE TITLE
Future variable overrides are substituted before being defined

### ISSUE THREAD

**Issue by Prof-Bloodstone** [ansible/ansible#69269]
##### SUMMARY
When creating a play, if variable is to be used in `pre_tasks` section, it's substituted with an override from a per-role `vars` override under `roles` section. Converting to `include_role` inside `pre_tasks` fixes the issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
playbook
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /tmp/ansible-bug/ansible.cfg
  configured module search path = ['/home/prof_bloodstone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/prof_bloodstone/.pyenv/versions/3.8.2/envs/infrastructure/lib/python3.8/site-packages/ansible
  executable location = /home/prof_bloodstone/.pyenv/versions/infrastructure/bin/ansible
  python version = 3.8.2 (default, Mar 10 2020, 18:40:04) [GCC 9.2.1 20200130]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/tmp/ansible-bug/ansible.cfg) = True
DEFAULT_LOG_PATH(/tmp/ansible-bug/ansible.cfg) = /tmp/ansible-bug/ansible.log
```

##### STEPS TO REPRODUCE

Create inventory with name, host and users defined. Example ini used:
```ini
test-instance-1 ansible_host=1.2.3.4 ansible_user=prof_bloodstone
```
Then create a empty test role: `mkdir -p roles/test`
Run following playbook:

```yaml
---
- name: Test tmp_var
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Set tmp_var
      set_fact:
        # ansible_user should be available here - it's defined in inventory
        tmp_var: "{{ ansible_user }}"
  roles:
    - role: test
      vars:
        ansible_user: "{{ tmp_var }}"
```

##### EXPECTED RESULTS

```
ansible-playbook -i inventory/inventory test.yml 

PLAY [Test tmp_var] **************************************************************************************************

TASK [Set tmp_var] ***************************************************************************************************
ok: [test-instance-1]

TASK [include_role : test] *******************************************************************************************

PLAY RECAP ***********************************************************************************************************
test-instance-1            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

##### ACTUAL RESULTS

 

```paste below
ansible-playbook -i inventory/inventory test.yml -vvvv
ansible-playbook 2.9.7
  config file = /tmp/ansible-bug/ansible.cfg
  configured module search path = ['/home/prof_bloodstone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/prof_bloodstone/.pyenv/versions/3.8.2/envs/infrastructure/lib/python3.8/site-packages/ansible
  executable location = /home/prof_bloodstone/.pyenv/versions/infrastructure/bin/ansible-playbook
  python version = 3.8.2 (default, Mar 10 2020, 18:40:04) [GCC 9.2.1 20200130]
Using /tmp/ansible-bug/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/ansible-bug/inventory/inventory as it did not pass its verify_file() method
script declined parsing /tmp/ansible-bug/inventory/inventory as it did not pass its verify_file() method
auto declined parsing /tmp/ansible-bug/inventory/inventory as it did not pass its verify_file() method
Parsed /tmp/ansible-bug/inventory/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/prof_bloodstone/.pyenv/versions/3.8.2/envs/infrastructure/lib/python3.8/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: test.yml ***************************************************************************************************
Positional arguments: test.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/tmp/ansible-bug/inventory/inventory',)
forks: 5
1 plays in test.yml

PLAY [Test tmp_var] **************************************************************************************************

TASK [Set tmp_var] ***************************************************************************************************
task path: /tmp/ansible-bug/test.yml:6
fatal: [test-instance-1]: FAILED! => {
    "msg": "The field 'remote_user' has an invalid value, which includes an undefined variable. The error was: 'tmp_var' is undefined"
}

PLAY RECAP ***********************************************************************************************************
test-instance-1            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```
#### WORKAROUND

```yaml
---
- name: Test tmp_var
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Set tmp_var
      set_fact:
        # ansible_user should be available here - it's defined in inventory
        tmp_var: "{{ ansible_user }}"
    - include_role:
        name: test
      vars:
        ansible_user: "{{ tmp_var }}"
```
