### ISSUE TITLE
Error parsing Cisco IOS interface configuration with parse_cli using "start_block"&"end_block"

### ISSUE THREAD

**Issue by tnizharadze** [ansible/ansible#69277]
##### SUMMARY

Error parsing Cisco IOS interface configuration with parse_cli when using "start_block" and "end_block" parameters.
Here is small patch, that eliminates this bug.
[network.py.patch.txt](https://github.com/ansible/ansible/files/4564884/network.py.patch.txt)
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

parse_cli
[network.py.patch.txt](https://github.com/ansible/ansible/files/4564877/network.py.patch.txt)

ansible/plugins/filter/network.py

##### ANSIBLE VERSION

```paste below
root@ansible:~/ansible# ansible --version
ansible 2.9.7
  config file = /root/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
root@ansible:~/ansible# ansible-config dump --only-changed
DEFAULT_GATHERING(/root/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/root/ansible/ansible.cfg) = [u'/root/ansible/inventories']
DEFAULT_LOG_PATH(/root/ansible/ansible.cfg) = /root/ansible/log/ansible.log
DISPLAY_ARGS_TO_STDOUT(/root/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/root/ansible/ansible.cfg) = auto
PARAMIKO_HOST_KEY_AUTO_ADD(/root/ansible/ansible.cfg) = True
```

##### STEPS TO REPRODUCE

```yaml
root@ansible:~/ansible# cat test.yml
---
- name: Test
  hosts: s-terra
  gather_facts: no
  vars:
    test_var: |
      interface GigabitEthernet1
       ip address 10.10.10.1 255.255.255.0
      !
      interface GigabitEthernet1.10
       encapsulation dot1Q 10
       ip address 10.10.20.1 255.255.255.0
      !
      !
      ip forward-protocol nd
      ip http server
      ip http authentication local
      ip http secure-server
      !
      !
  tasks:
    - name: Debug
      vars:
        second_var: "{{ test_var | parse_cli('parse_templates/ios_test.yml') }}"
      debug: var=second_var

root@ansible:~/ansible# cat parse_templates/ios_test.yml
---
vars:
  ios_iface:
    name: "{{ item[0].name }}"
    ip: "{{ item[1].ip }}"

keys:
  ios_ifaces:
    value: "{{ ios_iface }}"
    start_block: "^interface .*$"
    end_block: "^!$"
    items:
      - "^interface (?P<name>.+)\\n"
      - "\\sip address (?P<ip>.+)\\n"
```

##### EXPECTED RESULTS

```paste below
root@ansible:~/ansible# ansible-playbook test.yml

PLAY [Test] *******************************************************************************************************

TASK [Debug var=second_var] ***************************************************************************************
ok: [s-terra] => {
    "second_var": [
        {
            "ip": "10.10.10.1 255.255.255.0",
            "name": "GigabitEthernet1"
        },
        {
            "ip": "10.10.20.1 255.255.255.0",
            "name": "GigabitEthernet1.10"
        }
    ]
}

PLAY RECAP ********************************************************************************************************
s-terra                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```
##### ACTUAL RESULTS

```paste below
root@ansible:~/ansible# ansible-playbook test.yml

PLAY [Test] *******************************************************************************************************

TASK [Debug var=second_var] ***************************************************************************************
ok: [s-terra] => {
    "second_var": [
        {
            "ip": "10.10.10.1 255.255.255.0",
            "name": "GigabitEthernet1"
        },
        {
            "ip": "10.10.20.1 255.255.255.0",
            "name": "GigabitEthernet1.10"
        },
        {
            "ip": "10.10.20.1 255.255.255.0",
            "name": "GigabitEthernet1.10"
        },
        {
            "ip": "10.10.20.1 255.255.255.0",
            "name": "GigabitEthernet1.10"
        },
        {
            "ip": "10.10.20.1 255.255.255.0",
            "name": "GigabitEthernet1.10"
        }
    ]
}

PLAY RECAP ********************************************************************************************************
s-terra                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```
