### ISSUE TITLE
Accessing variable with `vars` performs nested substitutions only sometimes

### ISSUE THREAD

**Issue by Prof-Bloodstone** [ansible/ansible#69272]
##### SUMMARY

When accessing variable `X` directly (`{{ X }}`), partially yields different results to accessing it through `vars` dict (`{{ vars['X'] }}`).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

variables
vars

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /tmp/ansible-bug/ansible.cfg
  configured module search path = ['/home/prof_bloodstone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/prof_bloodstone/.pyenv/versions/3.8.2/envs/infrastructure/lib/python3.8/site-packages/ansible
  executable location = /home/prof_bloodstone/.pyenv/versions/infrastructure/bin/ansible
  python version = 3.8.2 (default, Mar 10 2020, 18:40:04) [GCC 9.2.1 20200130]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/tmp/ansible-bug/ansible.cfg) = True
DEFAULT_LOG_PATH(/tmp/ansible-bug/ansible.cfg) = /tmp/ansible-bug/ansible.log
```

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: no
  vars:
    my_var: three
    my_list:
      - one
      - two
      - "{{ my_var }}"
  tasks: 
  - name: Display my_list content
    debug:
      var: item
    loop:
      - "{{ my_list }}"
      - "{{ vars['my_list'] }}"
      - "{{ ['my_list'] | map('extract', vars) | list | flatten }}"
```

##### EXPECTED RESULTS

```
PLAY [all] ***********************************************************************************************************

TASK [Display my_list content] ***************************************************************************************
ok: [test-instance-1] => (item=['one', 'two', 'three']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "three"
    ]
}
ok: [test-instance-1] => (item=['one', 'two', 'three']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "three"
    ]
}
ok: [test-instance-1] => (item=['one', 'two', 'three']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "three"
    ]
}

PLAY RECAP ***********************************************************************************************************
test-instance-1            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

##### ACTUAL RESULTS

Notice that in the loop label, the item values are properly substituted, while module receives list with it's third value not substituted.

```paste below
PLAY [all] ***********************************************************************************************************

TASK [Display my_list content] ***************************************************************************************
ok: [test-instance-1] => (item=['one', 'two', 'three']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "three"
    ]
}
ok: [test-instance-1] => (item=['one', 'two', 'three']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "{{ my_var }}"
    ]
}
ok: [test-instance-1] => (item=['one', 'two', 'three']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "{{ my_var }}"
    ]
}

PLAY RECAP ***********************************************************************************************************
test-instance-1            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/lookup/vars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/vars.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is explicitly a limitation of the `vars` variable.  It is not meant to be templated. 

Typically speaking, you should never actually use the `vars` variable.

Look at using the `vars` lookup instead.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Prof-Bloodstone** [comment]
Thanks for quick response!

I didn't find that information in the doc.
Then the other issue is as I mentioned - the loop label seems to template already templated value.
This has potential security implications:
```yaml
- hosts: all
  gather_facts: no
  vars:
    my_var: "date"
    my_list:
      - one
      - two
      - "{{ '{{' }} lookup('pipe', my_var | quote ) {{ '}}' }}"
  tasks: 
  - name: Display my_list content
    debug:
      var: item
    loop:
      - "{{ my_list }}"
      - "{{ vars['my_list'] }}"
```
Result:
```
PLAY [all] ***********************************************************************************************************

TASK [Display my_list content] ***************************************************************************************
ok: [test-instance-1] => (item=['one', 'two', 'Fri 01 May 2020 05:19:49 PM CEST']) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "{{ lookup('pipe', my_var | quote ) }}"
    ]
}
ok: [test-instance-1] => (item=['one', 'two', "{{ lookup('pipe', my_var | quote ) }}"]) => {
    "ansible_loop_var": "item",
    "item": [
        "one",
        "two",
        "{{ '{{' }} lookup('pipe', my_var | quote ) {{ '}}' }}"
    ]
}

PLAY RECAP ***********************************************************************************************************
test-instance-1            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

I don't expect the third value to be templated - would expect it to be a string containing a valid jinja template.
But as you can see loop label executes it - if `my_var` is from external source, this might not end well.

As for using `vars` lookup - I looked into it, but it only accepts a singe variable name -there's no way to convert a list of variable names into a list of their values. Would need to do some jinja programming, which I always try not to do.
