### ISSUE TITLE
get_url fails when a password is provided in URL

### ISSUE THREAD

**Issue by rothgar** [ansible/ansible#6928]
I have tried on ansible 1.6 (devel 5a075e3b93) and 1.5.4 to run the following playbook task (some details changed/removed)

``` yaml
- hosts: tomcat
  vars:
    apps:
      - { app: 'app1', version: '01' }
      - { app: 'app2', version: '05' }
    apps_url: "https://user:password@server.example.com/"

    - name: Download wars
      get_url: url={{ apps_url }}{{ item.app }}.{{ item.version }}.war
        dest=/opt/tomcat/wars/{{ item.app }}.war force=yes validate_certs=no
        mode=0644 owner=root group=root
      with_items: apps
```

The following tasks returns

failed: [tomcat.example.com] => (item={'version': '01', 'app': 'app1'}) => {"dest": "/opt/tomcat/wars/app1.war", "failed": true, "item": {"app": "app1", "version": "01"}, "response": "HTTP Error 401: basic auth failed", "state": "absent", "status_code": 401, "url": "https://user:password@server.example.com/app.01.war"}
msg: Request failed

I tested the url path and credentials by running
`wget --no-check-certificate "https://user:password@server.example.com/app1.01.war` which works without any errors.

I also found that if there are any special characters is the password they need to be [URL encoded](http://en.wikipedia.org/wiki/Percent-encoding) otherwise you will get the error 

`InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port`

Is there a way for us to convert the URL in the playbook (maybe jinja filter) by default? I think the [urlencode() jinja filter](http://jinja.pocoo.org/docs/templates/#urlencode) will work but I haven't tested it yet.
