### ISSUE TITLE
Synchronize wrong user and doesn't work

### ISSUE THREAD

**Issue by craph** [ansible/ansible#69301]
##### SUMMARY

I'm unable to use synchronize Ansible module to copy files from a server A to server B
I'm using a shared user between thoses servers to authorize ssh connection without password by using ssh key.
But when I launch the synchronize module it seems it's the wrong user that it is used in the dest...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

synchronize

##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 7.7

##### STEPS TO REPRODUCE

```yaml
- name: "Copy all files from {{ old_server }} to {{ inventory_hostname }}"
  synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
  delegate_to: "{{ old_server }}"
  become: yes
  become_user: "{{ my_shared_user }}"
  with_items:
    - "/tmp/toto"
  tags: copy_files
```

##### EXPECTED RESULTS

I should be able to copy files.

##### ACTUAL RESULTS

Now It seems the dest is wrong in the tmp python file

```paste below
ANSIBALLZ_PARAMS = '{"ANSIBLE_MODULE_ARGS": {"_ansible_version": "2.9.3", "src": "/tmp/toto", "_ansible_syslog_facility": "LOG_USER", "_ansible_selinux_special_fs": ["fuse", "nfs", "vboxsf", "ramfs", "9p", "vfat"], "_ansible_no_log": false, "_local_rsync_path": "rsync", "dest": "root@old_server:/tmp/toto", "_ansible_module_name": "synchronize", "_ansible_remote_tmp": "$HOME/.ansible/tmp", "_ansible_verbosity": 4, "_ansible_keep_remote_files": false, "_local_rsync_password": null, "_ansible_socket": null, "_ansible_string_conversion_action": "warn", "_ansible_diff": false, "_ansible_debug": false, "_ansible_shell_executable": "/bin/sh", "_ansible_check_mode": false, "_ansible_tmpdir": null, "rsync_path": "sudo rsync"}}'
```

Why it's "root@old_server" instead of the user in the become_user ?

Thank you very much for your help.
