### ISSUE TITLE
"Failure validating OVF import spec: Host did not have any virtual network defined.

### ISSUE THREAD

**Issue by ansibleusersili** [ansible/ansible#69309]
##### SUMMARY

Hello everyboby, i have a problem with automatic OVF/OVA deployement with Ansible on vmware. I had this error message 'Failure validating OVF import spec: Host did not have any virtual defined'
 I tried multiple combination and following issue that were referenced on github, but nothing worked.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_deploy_ovf

##### ANSIBLE VERSION

```paste below
vmware_deploy_ovf
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/node-manager/Documents/socinbox/ansible.cfg) = ['/home/node-manager/Documents/socinbox/hosts']
```

##### OS / ENVIRONMENT

VSPhere version: 6.7
Ubuntu version 18.0.4 TLS
Ansible 2.9.7

##### STEPS TO REPRODUCE

```yaml
- name: Deploy_ovf
  vmware_deploy_ovf:
    hostname: '{{vcenter_hostname}}'
    username: '{{vcenter_username}}'
    password: '{{vcenter_password}}'
    validate_certs: no
    datacenter: '{{datacenter}}'
    datastore: '{{datastore}}'
    ovf: '/home/user-ansible/Documents/OVF_files/***.ovf'
    ressource_pool: '***'
    networks: "{u'VM Network': u'***'}"
```

##### EXPECTED RESULTS

"msg": "Failure validating OVF import spec: Host did not have any virtual network defined."

##### ACTUAL RESULTS

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_duplicates": true,
            "cluster": null,
            "datacenter": "***",
            "datastore": "***",
            "deployment_option": null,
            "disk_provisioning": "thin",
            "fail_on_spec_warnings": false,
            "folder": null,
            "hostname": "***",
            "inject_ovf_env": false,
            "name": "***",
            "networks": {
                "VM Network": "***"
            },
            "ovf": "/home/node-manager/Documents/socinbox/OVF_files/share-file/share-file.ovf",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "power_on": true,
            "properties": null,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": "****",
            "username": "***",
            "validate_certs": false,
            "wait": true,
            "wait_for_ip_address": false
        }
    },
    "msg": "Failure validating OVF import spec: Host did not have any virtual network defined."
}

```paste below

```
