### ISSUE TITLE
Error with module

### ISSUE THREAD

**Issue by nishant2019** [ansible/ansible#69327]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

 
- name: launch an instance
  hosts: localhost
  os_server_actions:
       action: start
       server: CTF
       timeout: 200

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->


##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```paste below

```
I am getting this error
ERROR! 'os_server_actions' is not a valid attribute for a Play
The error appears to be in '/tmp/awx_100_1hlhozhi/project/start_vm.yaml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: launch an instance
  ^ here

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
Hi! @nishant2019 `os_server_actions` is not a play parameter. You may correct your play like

```yaml
- name: launch an instance
  hosts: localhost
  tasks:
    - os_server_actions:
        action: start
        server: CTF
        timeout: 200
```


Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
