### ISSUE TITLE
Skipped task mess registered variable

### ISSUE THREAD

**Issue by Passo1** [ansible/ansible#69333]
##### SUMMARY
Task what is skipped due to the condition, clear the variable what has been set earlier if that skipped task has the same variable setting.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
register, when

##### ANSIBLE VERSION
```
ansible 2.9.7
  config file = /ansible/ansible-playbooks/ansible.cfg
  configured module search path = [u'/home/tiffany/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 12 2018, 20:00:40) [GCC 4.8.4]
```

##### CONFIGURATION
```
ALLOW_WORLD_READABLE_TMPFILES(/ansible/ansible-playbooks/ansible.cfg) = True
ANSIBLE_NOCOWS(/ansible/ansible-playbooks/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/ansible/ansible-playbooks/ansible.cfg) = -o ForwardAgent=yes
DEFAULT_HOST_LIST(/ansible/ansible-playbooks/ansible.cfg) = [u'/ansible/ansible-playbooks/hosts']
DEFAULT_SCP_IF_SSH(/ansible/ansible-playbooks/ansible.cfg) = True
DEFAULT_TRANSPORT(/ansible/ansible-playbooks/ansible.cfg) = smart
HOST_KEY_CHECKING(/ansible/ansible-playbooks/ansible.cfg) = False
```
##### OS / ENVIRONMENT
ubuntu 1404
4.4.0-148-generic #174~14.04.1-Ubuntu SMP Thu May 9 08:17:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
---
- name: Testing
  hosts: local
  tasks:
  - name: read current directory in trusty
    shell: pwd
    register: workspace
    when: ansible_distribution_release == 'trusty'

  - debug:
      var: workspace

  - name: read current directory in something else
    shell: pwd
    register: workspace
    when: ansible_distribution_release == 'else'

  - debug:
      var: workspace
```

##### EXPECTED RESULTS
Variable should stay unchanged over the skipped task

##### ACTUAL RESULTS

```
tiffany@tiffany-devenv1404x86:/ansible/ansible-playbooks$ ansible-playbook variableSetting.yml

PLAY [Testing] ***************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************
ok: [127.0.0.1]

TASK [read current directory in trusty] **************************************************************************
changed: [127.0.0.1]

TASK [debug] *****************************************************************************************************
ok: [127.0.0.1] => {
    "workspace": {
        "changed": true,
        "cmd": "pwd",
        "delta": "0:00:00.002029",
        "end": "2020-05-05 12:11:40.972877",
        "failed": false,
        "rc": 0,
        "start": "2020-05-05 12:11:40.970848",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "/ansible/ansible-playbooks",
        "stdout_lines": [
            "/ansible/ansible-playbooks"
        ]
    }
}

TASK [read current directory in something else] ******************************************************************
skipping: [127.0.0.1]

TASK [debug] *****************************************************************************************************
ok: [127.0.0.1] => {
    "workspace": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

PLAY RECAP *******************************************************************************************************
127.0.0.1                  : ok=4    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```
