### ISSUE TITLE
k8s module: apply and force parameters still permit OpenShift secret change

### ISSUE THREAD

**Issue by Roia5** [ansible/ansible#69330]
##### SUMMARY
When attempting to use the `k8s` module to deploy OpenShift objects (secrets, deployments etc.) using operator-sdk, we configured a secret with `apply: no` (also tried `force: no`) to disallow changing the secret contents. 
Despite these parameters, changing the input variables in the CustomResource still resulted in the secret contents changing to the new parameters.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s module

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
empty output
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server (7.8 (Maipo))
OpenShift Client Version: openshift-clients-4.3-31-gc25fb9c7
Kubernetes Version: v1.16.2

##### STEPS TO REPRODUCE

The user specified input in the form of a CustomResource:
```
apiVersion: dba.mongodb/v1
kind: MongoDB
metadata:
  name: elmx
spec:
  # Add fields here
  name: elmprojx
  version: 4.2.6
  adminName: vlad
  adminPassword: vlad
  dataSize: 3Gi
  cpuWanted: 500
  memoryWanted: 500
```
The secret was deployed using the following role: 

```yaml
- name: The MongoDB Secret is present
  k8s:
    state: present
    apply: no
    definition: "{{ lookup('template', 'mongodb-secret.yml') | from_yaml  }}"
```
Where the template `mongodb-secret.yml` is defined as:
```
kind: Secret
apiVersion: v1
metadata:
  name: "{{ name }}-mongodb-connection"
  namespace: '{{ meta.namespace }}'
  labels:
    app: "{{ name }}"
    container: mongodb
    group: dba.mongodb
type: kubernetes.io/basic-auth
stringData:
  username: '{{ admin_name }}'
  password: '{{ admin_password }}'
```

Then, the playbook was executed by operator-sdk and a secret was created with vlad:vlad as wanted by the user.
When changing the admin_name (for example to 'john') and applying the new CustomResource, the secret then contained the new admin_name despite the `apply:no` parameter (also tried with force and same results).

##### EXPECTED RESULTS
Setting `force: no` or `apply:no` will not allow the secret to change.

##### ACTUAL RESULTS

The secret info was still changed.

Thank you in advance!
