### ISSUE TITLE
gluster_volume can not directly start volumes

### ISSUE THREAD

**Issue by robojones** [ansible/ansible#69346]
##### SUMMARY

- I want to create GlusterFS volumes and directly start them.
- The gluster_volume module does not automatically create the GlusterFS volume if it does not exist and the state is set to "started".
- I would expect that the gluster_volume module supports transitions from any state to any other state. Even from "absent" to "started".

The only workaround I could find was to create another gluster_volume task where the state is set to "present" before my task tries to start a volume. In my case, the state is dynamically set from a list of volumes in a variable. The state can be any of "absent", "stopped", "present" and "started". This means that my playbook gets more complicated because the workaround task should not always be executed and also there are loops involved.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gluster_volume module

##### ANSIBLE VERSION
I have tested this with Ansible 2.9.5 and 2.9.7

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Ubuntu 18.04.4 LTS

##### STEPS TO REPRODUCE
- You need a GlusterFS setup with three nodes (in my example they are called node1, node2 and node3).

```yaml
- name: "Create GlusterFS volumes"
  gluster_volume:
    name: test_volume
    state: started
    cluster:
      - node1
      - node2
      - node3
    replicas: 3
    bricks: /glusterfs/test_volume/brick1/brick
```

##### EXPECTED RESULTS
The test_volume should be created and started.

##### ACTUAL RESULTS
When I execute my playbook on node1, I get the following error message:
```
volume not found test_volume
```
