### ISSUE TITLE
Timeout (12s) waiting for privilege escalation prompt:

### ISSUE THREAD

**Issue by ITslacker** [ansible/ansible#69343]
##### SUMMARY

Timeout error even when timeout is set to 300 seconds. 
##### ISSUE TYPE
- Bug Report
I have a playbook that patches and reboots my webfarm. While testing my playbook with a simple check update command, I would get the error mentioned in the title. I've tried setting my timeout to 300 seconds, but it seems like ansible tower doesn't honor the timeout set. When I check the job template api, the timeout reflects "0". So I went ahead and manually set that to "300" and it patch. When the job ran again, I received the same error and when I checked the job template api, the timeout still reflected "0". I've tried adding become_method: sudo with no luck either.
##### ANSIBLE VERSION

```paste below
"Ansible 2.9.7"
"Tower 3.6.2"
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL6/RHEL7 OS

##### STEPS TO REPRODUCE

Create a simple webserver, create a linux role that consist of
- name: Check Updates
  yum: list=updates update_cache=true

```
- hosts: webfarm:&web_server:&production
  gather_facts: true
  gather_subset:
    - network
  become: yes
  serial: 1
  vars:
    port: 80
  tasks:
    - include_role:
        name: linux-pre-patch
```

##### EXPECTED RESULTS

to return ok

##### ACTUAL RESULTS

"msg":Timeout (12s) waiting for privilege escalation prompt:

```paste below

```
