### ISSUE TITLE
nios_ptr_record - "state: absent" not removing existing PTR records

### ISSUE THREAD

**Issue by MTWiley** [ansible/ansible#69359]
##### SUMMARY
Trying to remove PTR records, playbook executes and returns ok, but no changes are made and I just get status ok

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_ptr_record

##### ANSIBLE VERSION
```

ansible 2.9.7
  config file = /home/username/ansible_working_directory/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 26 2019, 16:55:40) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION
```

DEFAULT_CALLBACK_WHITELIST(/home/username/ansible_working_directory/ansible.cfg) = ['splunk']
DEFAULT_HOST_LIST(/home/username/ansible_working_directory/ansible.cfg) = ['/home/username/ansible_working_directory/inventory/inventory']
DEFAULT_VAULT_PASSWORD_FILE(/home/username/ansible_working_directory/ansible.cfg) = /opt/ansible/ansible_private.pem
HOST_KEY_CHECKING(/home/username/ansible_working_directory/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/username/ansible_working_directory/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Ansible Server - Red Hat Enterprise Linux Server release 7.4 (Maipo) - delegated_to
InfoBlox - IB-1410 - Version : 8.2.2-363203 - Supported WAPI Versions:
- 1.0
- 1.1
- 1.2
- 1.2.1
- 1.3
- 1.4
- 1.4.1
- 1.4.2
- 1.5
- 1.6
- 1.6.1
- 1.7
- 1.7.1
- 1.7.2
- 1.7.3
- 1.7.4
- 1.7.5
- 2.0
- 2.1
- 2.1.1
- 2.1.2
- 2.2
- 2.2.1
- 2.2.2
- 2.3
- 2.3.1
- 2.4
- 2.5
- 2.6
- 2.6.1
- 2.7

##### STEPS TO REPRODUCE

Create multiple PTR records in for 10.100.100.30

  - 10.100.100.30 - "name." - unnecessary ptr record
  - 10.100.100.30 - "name.domain.lan." - necessary ptr record
  - 10.100.100.30 - "othername.domain.lan." - unnecessary ptr record

Run the playbook to try to remove the unnecessary ptr records

```yaml

---
  - hosts: 10.100.100.30
    gather_facts: no
    vars:
      nios_provider:
        host: "{{ infoblox_ip }}"
        username: "{{ vault_infoblox_username }}"
        password: "{{ vault_infoblox_password }}"
        validate_certs: no
    tasks:
    - name: Debugging returned ptr_records
      debug:
        msg: "{{ lookup('dig', "10.100.100.30", 'qtype=PTR', wantlist=True) }}"

    - name: Remove Incorrect PTR Record
      nios_ptr_record:
        ipv4: 10.100.100.30
        ptrdname: othername.domain.lan. # Tried with and without the trailing .
        state: absent
        provider: "{{ nios_provider }}"
      connection: local

    - name: Debugging returned ptr_records
      debug:
        msg: "{{ lookup('dig', "10.100.100.30", 'qtype=PTR', wantlist=True) }}"

```

##### EXPECTED RESULTS

10.100.100.30 - othername - unnecessary ptr record removed

##### ACTUAL RESULTS

10.100.100.30 - othername - unnecessary ptr record remains

```

[username@hostname domain_ansible]$ ansible-playbook playbooks/remove-single-ptr.yml -i inventory/ -i 10.100.100.30

PLAY [10.100.100.30] *******************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************
ok: [10.100.100.30]

TASK [Debugging returned ptr_records] *************************************************************************************************************************************************************************
ok: [10.100.100.30] => {
    "msg": [
        "name.",
        "name.domain.lan.",
        "othername.domain.lan."
    ]
}

TASK [Remove Incorrect PTR Record] ****************************************************************************************************************************************************************************
ok: [10.100.100.30]

TASK [Debugging returned ptr_records] *************************************************************************************************************************************************************************
ok: [10.100.100.30] => {
    "msg": [
        "name.domain.lan.",
        "othername.domain.lan.",
        "name."
    ]
}

PLAY RECAP ****************************************************************************************************************************************************************************************************
10.100.100.30               : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[username@hostname domain_ansible]$
