### ISSUE TITLE
lookup.ini plugin does not work

### ISSUE THREAD

**Issue by nik786** [ansible/ansible#69353]
```
 ansible --version
ansible 2.7.12
  config file = /home/nik/Desktop/python-ops/study/new-01/play/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

```
python --version
Python 3.6.9
```
```yaml
- hosts: 127.0.0.1
  tasks:
      - name: print hello
        shell: echo "hello world" 
        register: helo
      - set_fact: 
          my_var: "{{ lookup('ini', 'Resource.Point type=properties file=w.ini') }}"  
      - debug: 
          msg: "{{ my_var }}"
```
```
fatal: [127.0.0.1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'ini'. Error was a <class 'configparser.DuplicateOptionError'>, original message: While reading from '<???>' [line 65]: option 'lbproberesponder' in section 'java_properties' already exists"
}
	to retry, use: --limit @/home/nik/Desktop/python-ops/study/new-01/play/helo.retry

PLAY RECAP *********************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1 
```
