### ISSUE TITLE
Error reading SSH protocol banner on using ProxyCommand with ios_command

### ISSUE THREAD

**Issue by vparames86** [ansible/ansible#69389]
##### SUMMARY

I am trying to run an ansible playbook via a bastion server (using ProxyCommand) to "show version" on csr1000v(Cisco Device). I get the following error when I run the playbook.

fatal: [csr1]: FAILED! => {
    "changed": false,
    "msg": "Error reading SSH protocol banner"
}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command, ansible_ssh_common_args, ProxyCommand

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = None
  configured module search path = [u'/home/venkat/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cisco CSR1000v

##### STEPS TO REPRODUCE

1) Try running "show version" via "ios_command" module via a bastion server

```yaml
- name: Network Getting Started First Playbook Extended
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show interfaces
      vars:
        ansible_command_timeout: 200
```
ansible_ssh_common_args='-o StrictHostKeyChecking=no ProxyCommand="sshpass -p ***** ssh -W %h:%p -q root@****"'

##### ACTUAL RESULTS

```paste below

```
