### ISSUE TITLE
Assert evaluates false but should be true

### ISSUE THREAD

**Issue by bandwiches** [ansible/ansible#69392]
##### SUMMARY
I'm using the assert module to determine if text is present within a registered variable.  The variable has the text in it and it displayed in the 'fail_msg' parameter with the text in it but the module always evaluates to false.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
assert.that

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu/Docker (AWX release 10.0.0)

##### STEPS TO REPRODUCE

```yaml
---
  - hosts: REMOVED
    gather_facts: no
    tasks:
      - name: Run show version
        ios_command:
          commands:
            - show version
        register: showversion
      - name: Debug show version
        debug:
          var: showversion.stdout
          verbosity: 0
      - name: Check for 3560
        assert:
          that:
            - "'C3560E' in showversion.stdout"
          success_msg: "This is a 3650."
          fail_msg: "{{ showversion.stdout }}"
```

##### EXPECTED RESULTS

Expected the module to evaluate true since the text is in the variable.

##### ACTUAL RESULTS

Module evaluates to false and fails the job.

```paste below
{
    "_ansible_verbose_always": true,
    "evaluated_to": false,
    "assertion": "'C3560E' in showversion.stdout",
    "msg": [
        "Cisco IOS Software, C3560E Software...<removed for brevity>"
    ],
    "_ansible_no_log": false,
    "changed": false
}
```
![image](https://user-images.githubusercontent.com/16140382/81416438-5b44e480-910f-11ea-9c37-46dd81990297.png)
