### ISSUE TITLE
iptables ipsec policy matching

### ISSUE THREAD

**Issue by AFriemann** [ansible/ansible#69394]
##### SUMMARY

It would be great to have support for iptables ipsec policy matching as described in https://linux.die.net/man/8/iptables.

This would require adding at least the options

* --pol
* --dir

when `match: policy` is set to support (I think) most setups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

iptables module (modules/system/iptables.py)

##### ADDITIONAL INFORMATION

currently to configure iptables for ipsec traffic you have to resort to command/shell tasks, e.g. to enable POSTROUTING for tunneled traffic you have to run

```
iptables -t nat -A POSTROUTING -m policy --pol ipsec --dir out -j ACCEPT
```

which of course means needing to implement additional checks to check if those entries already exist.

I suppose implemented this cloud look something like the following

```yaml
- name: enable POSTROUTING nat for ipsec traffic
  iptables:
    table: nat
    chain: POSTROUTING
    match: policy
    ipsec: yes
    ipsec_direction: out
    jump: ACCEPT
```

However I am unsure on a good fit for naming.
