### ISSUE TITLE
[2.9]gitlab_deploy_key unexpected email parameter

### ISSUE THREAD

**Issue by flotho** [ansible/ansible#69416]
##### SUMMARY
Running the module gitlab_deploy_key with only access_token seems to keep old email parameter 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

gitlab_deploy_key

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /home/florent.thomas/DEV/Projets_Infra/all-ansible-serverplaybooks/ansible.cfg
  configured module search path = ['/home/florent.thomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Local : Fedora 31

Remote : CentOS 8 uptodate
```
pip3 list | grep python-gitlab
python-gitlab (2.2.0)
```

##### STEPS TO REPRODUCE

create a user with admin ACL in gitlab, add a personnal access token. then in a playbook : 
 

```
gitlab_deploy_key:
  api_url: https://gitlab.example.com/
  api_token: "{{ gitlab_access_token }}"
  key: "{{ user_infos['ssh_public_key'] }}"
  project: "{{ project }}"
  state: present
  title: "{{ vm_odoo[0] }}"

```

##### EXPECTED RESULTS

Hope that the ssh key will be added to appropriate projects

##### ACTUAL RESULTS

failed there https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/source_control/gitlab_deploy_key.py#L293, looks like email still present.
Maybe the python-gitlab library version is not the appropriate neither on my remote server nor in the offical documentation

```
ansible_gitlab_deploy_key_payload.zip/ansible/modules/source_control/gitlab_deploy_key.py\", line 294, in main\nTypeError: __init__() got an unexpected keyword argument 'email'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```
