### ISSUE TITLE
VMWare : vmware_content_deploy_template module don't create VM on Datastore Cluster

### ISSUE THREAD

**Issue by xander-sh** [ansible/ansible#69411]
##### SUMMARY

Please synchronize the creation parameters need to create VM from vmware_guest module:
cluster 
hosts (esxi_hostname)
datastore  

##### ISSUE TYPE
- Feature Idea
I want to create VM in vCenter Cluster, not on a specific esxi_host, but **hosts** parameters are required in vmware_content_deploy_template module. 
On vmware_guest module i can and this parameter (esxi_hostname) depends from **cluster**
 
[cluster parameter on vmware_guest](https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html#parameter-cluster)
```
The cluster name where the virtual machine will run.
This is a required parameter, if esxi_hostname is not set.
esxi_hostname and cluster are mutually exclusive parameters.
This parameter is case sensitive.
```
vmware_content_deploy_template does not support create VM in Datastore Cluster, like in vmware_guest module
[datastore parameter on vmware_guest](https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html#parameter-datastore)
```
Specify datastore or datastore cluster to provision virtual machine.
This parameter takes precedence over "disk.datastore" parameter.
This parameter can be used to override datastore or datastore cluster setting of the virtual machine when deployed from the template.
```

##### COMPONENT NAME

vmware_content_deploy_template

##### ADDITIONAL INFORMATION

It would be perfect to create VM from template, specify cluste and datastore_cluster rather than cluster, specific esxi_host, specific datastore 
```yaml
  - name: VCenter - create VMs from tempalte (Nodes)
    vmware_content_deploy_template:
      hostname: "{{ vc_server }}"
      username: "{{ domainadminUser }}"
      password: "{{ domainadminPassword }}"
      name: "{{ vm_name }}"
      template: "{{ template_name }}"
      datacenter: "{{ vc_datacenter }}"
      cluster: "{{ vc_cluster }}"
      datastore: "{{ datastore_cluster }}"
      resource_pool: "{{ k8s_cluster_name }}"
      folder: "{{ k8s_vsphere_folder }}"
      state: present
      validate_certs: no
```
