### ISSUE TITLE
Pycrypto error PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.

### ISSUE THREAD

**Issue by goozbach** [ansible/ansible#6941]
##### Issue Type:

Bug Report
##### Ansible Version:

```
[root@vagrant-centos-6_4 ansible]# ansible --version
ansible 1.5.4
```
##### Environment:

Ansible-host: CentOS 6.5
Ansible-client: CentOS 6.5
##### Summary:

This is most likely a bug in pycrypto  but it seems to be related to or the same as #276 or #6190 
##### Steps To Reproduce:
1. fresh install of centos 6.5
2. rpm -ivh http://url/to/epel-release
3. yum -y install ansible --enablerepo='epel*'
4. create localhost ssh key and authorized keys
5. install goozbach.EPEL galaxy role
6. create following playbook:
   
   ```
   ---
   - name: master playbook
     hosts: all
     user: root
     roles:
       - { role: goozbach.EPEL, epel_enabled: 1, epel_testing_enabled: 1 }
   ```
7. run your ansible playbook
##### Expected Results:

Pycrypto shouldn't show warning message.
##### Actual Results:

``````
```
[root@vagrant-centos-6_4 ansible]# ansible-playbook site.yml
/usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
<SNIP all good output>
```
``````
