### ISSUE TITLE
template module doesn't look into files directory for src file

### ISSUE THREAD

**Issue by mamun217** [ansible/ansible#69422]
##### SUMMARY
Using `template` module to copy a file to remote host but ansible throws an error saying `Could not find or access 'file_name.yml'`. The file to be copied is under `roles/sample/files` directory.  Looking at the error message, it appears that the module doesn't look into `files` directory at all event though mentioned in the [role documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-roles).

> Any copy, script, template or include tasks (in the role) can reference files in roles/x/{files,templates,tasks}/ (dir depends on task) without having to path them relatively or absolutely.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`template` module

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.7
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.7/site-packages/ansible
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.7.6 (default, Feb 26 2020, 20:54:15) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]

```

##### STEPS TO REPRODUCE

**_Playbook_**
```yaml
- hosts: myhost
  gather_facts: no
  tasks:
    - name: Configuring instance
      import_role:
        name: sample
        tasks_from: configure
```
**_roles/sample/tasks/configure.yml_**
```yaml
    - name: Copy docker specific files to the destination
      template:
        owner: "ec2-user"
        mode: '0644'
        src: "{{ item }}"
        dest: "{{ dir_config }}/{{ item }}"
      with_items:
        - file_name.yml
```

##### EXPECTED RESULTS

The file should be copied to the destination directory of remote host.

##### ACTUAL RESULTS

Masked some of the information.
```
failed: [xxx.xxx.xxx.xxx] (item=file_name.yml) => {"ansible_loop_var": "item", "changed": false, "item": "file_name.yml", "msg": "Could not find or access 'file_name.yml'\nSearched in:\n\t/home/ec2-user/ansible/roles/sample/templates/file_name.yml\n\t/home/ec2-user/ansible/roles/sample/file_name.yml\n\t/home/ec2-user/ansible/roles/sample/tasks/templates/file_name.yml\n\t/home/ec2-user/ansible/roles/sample/tasks/file_name.yml\n\t/home/ec2-user/ansible/templates/file_name.yml\n\t/home/ec2-user/ansible/file_name.yml on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

```
