### ISSUE TITLE
Allow one to override the hardcoded value "ansible_syslogger" in the syslogger module.

### ISSUE THREAD

**Issue by mivanov-its** [ansible/ansible#69428]
##### SUMMARY

It is useful to allow one to specify the application name in the syslogger module. It is hardcoded to "ansible_syslogger" at the moment, see:

https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/notification/syslogger.py#L151
https://github.com/ansible/ansible/blob/stable-2.7/lib/ansible/modules/notification/syslogger.py#L155

Moreover, this hardcoded string is not mentioned in the documentation:

https://docs.ansible.com/ansible/latest/modules/syslogger_module.html

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

lib/ansible/modules/notification/syslogger.py

##### ADDITIONAL INFORMATION

One could override it with:

```
- name: Test syslog
  syslogger:
    appname: "myapp"
    msg: "Hello from ansible"
    priority: "err"
    facility: "daemon"
    log_pid: true
```

or in some other way.
