### ISSUE TITLE
discovered_interpreter_facts being added and removed and issuing a Warning

### ISSUE THREAD

**Issue by psv1979** [ansible/ansible#69446]
##### SUMMARY
When I have several 'stat' commands with 'delegate_to' in a playbook I always obtain this message before the second 'stat':
```
"[WARNING]: Removed restricted key from module data: ansible_facts = {u'discovered ... thon'}"
```
It started after updating the ansible 2.9.6 to 2.9.7 and wasn't before in the same playbook.

The Warning message appears when I use FQDN host name in 'delegate_to' and doesn't if I use 'Localhost' e.g.
This message never appears after the second, third stat and etc. Only after the first one!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
stat

##### ANSIBLE VERSION
Current version: 2.9.7

##### OS / ENVIRONMENT
CentOS Linux release 7.8.2003

##### STEPS TO REPRODUCE
The playbook for example:
```
- name: "Showing warning"
  hosts: localhost
  gather_facts: no
  tasks:
  - name: "Stat 1"
    stat:
        path: "/etc/crontab"
    delegate_to: "SomehostFQDNname"
  - name: "Stat2"
    stat:
        path: "/etc/crontab"
    delegate_to: "SomehostFQDNname"
  - name: "Stat3"
    stat:
        path: "/etc/crontab"
    delegate_to: "SomehostFQDNname"
```

##### EXPECTED RESULTS
```
PLAY [Showing warning] *********************************************************************************************************

TASK [Stat 1] *********************************************************************************************************
ok: [localhost -> SomehostFQDNname]

TASK [Stat2] *********************************************************************************************************
ok: [localhost -> SomehostFQDNname]

TASK [Stat3] *********************************************************************************************************
ok: [localhost -> SomehostFQDNname]

PLAY RECAP *********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
##### ACTUAL RESULTS
```
PLAY [Showing warning] *********************************************************************************************************

TASK [Stat 1] *********************************************************************************************************
ok: [localhost -> SomehostFQDNname]
[WARNING]: Removed restricted key from module data: ansible_facts = {u'discovered ... thon'}

TASK [Stat2] *********************************************************************************************************
ok: [localhost -> SomehostFQDNname]

TASK [Stat3] *********************************************************************************************************
ok: [localhost -> SomehostFQDNname]

PLAY RECAP *********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
