### ISSUE TITLE
Ansible git module stuck when cloning via HTTPS if authentication is required 

### ISSUE THREAD

**Issue by mathewatspm** [ansible/ansible#69489]
##### SUMMARY

Ansible git task would stuck if a HTTPS git repo requires username/password authentication, but such credential was not included in the task.

##### ISSUE TYPE
- Bug Report (or possibly an enhancement request)

##### COMPONENT NAME
Ansible git module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True

```

##### OS / ENVIRONMENT

* CentOS 8

##### STEPS TO REPRODUCE

* Assuming `https://foo.bar/repo.git` is a private repo which requires username and password to clone/pull etc.
```
# This would work
- git:
    repo: "https://{{ username | urlencode }}:{{ password | urlencode }}@foo.bar/repo.git"
    dest: /some/dir
```
```
# This would cause the task to stuck
# indefinitely possibly because Ansible
# git module does not know how to react
# to a username prompt
- git:
    repo: "https://foo.bar/repo.git"
    dest: /some/dir
```
* I expect I will be advised to use SSH auth instead.  But in my situation, SSH is not a possibility and HTTPS auth is the only option.

##### EXPECTED RESULTS

Expect the git task to fail with some kind of error message if HTTPS authentication credential is required, but not provided.

##### ACTUAL RESULTS

The git task would just stuck there what seemed like indefinitely.
