### ISSUE TITLE
cloudflare_dns SRV record always reports as changed

### ISSUE THREAD

**Issue by Dutchy-** [ansible/ansible#69485]
##### SUMMARY
I create SRV records using cloudflare_dns.
On the first run, the module reports that the record changed (created)
On the second run, it still reports as changed, even though the module invocation did not change.

There are no visible changes in the cloudflare dashboard between invocations.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloudflare_dns

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /Users/hidden/for/privacy/ansible.cfg
  configured module search path = ['/Users/hidden/for/privacy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/hidden/for/privacy/.pyenv/versions/3.8.1/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Users/hidden/for/privacy/.pyenv/versions/3.8.1/bin/ansible
  python version = 3.8.1 (default, Jan 15 2020, 16:56:34) [Clang 11.0.0 (clang-1100.0.33.12)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/hidden/for/privacy/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/hidden/for/privacy/ansible.cfg) = -o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH_DIR(/Users/hidden/for/privacy/ansible.cfg) = ./.ansible/cp
CACHE_PLUGIN(/Users/hidden/for/privacy/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Users/hidden/for/privacy/ansible.cfg) = ./ansible-facts/
DEFAULT_BECOME(/Users/hidden/for/privacy/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/Users/hidden/for/privacy/ansible.cfg) = True
DEFAULT_FORKS(/Users/hidden/for/privacy/ansible.cfg) = 50
DEFAULT_GATHERING(/Users/hidden/for/privacy/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Users/hidden/for/privacy/ansible.cfg) = ['/Users/hidden/for/privacy/inventory_prod.ini']
INTERPRETER_PYTHON(/Users/hidden/for/privacy/ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT

MacOS 10.15

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  become: false
  vars:
    email: "EMAIL HERE"
    # This is the GLOBAL cloudflare API key. The ansible cloudflare_dns module does not work
    # with more specific (user) API keys.
    token: TOKEN HERE
    credentials:
      account_email: "{{ email }}"
      account_api_token: "{{ token }}"
    zone_records:
      - zone: example.com
        records:
           # Also tried without underscores for the values
           - { record: "@", type: "SRV", value: "sipfed.online.lync.com", service: "_sipfederationtls", proto: "_tcp", weight: 1, port: 5061, priority: 100 }
  tasks:
    - name: Create records for all the zones
      cloudflare_dns:
      args: "{{ credentials|combine({'state': 'present', 'zone': item.0.zone })|combine(item.1) }}"
      with_subelements:
        - "{{ zone_records }}"
        - records
      register: created_records
    - name: debug created records
      debug: var=created_records
```

##### EXPECTED RESULTS

No change after the second run

##### ACTUAL RESULTS

```paste below
changed: [localhost] => (item=[{'zone': 'example.org'}, {'record': '@', 'type': 'SRV', 'value': 'sipfed.online.lync.com', 'service': '_sipfederationtls', 'proto': '_tcp', 'weight': 1, 'port': 5061, 'priority': 100}]) => {
    "ansible_loop_var": "item",
    "changed": true,
    "invocation": {
        "module_args": {
            "account_api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "account_email": "hidden for privacy",
            "algorithm": null,
            "cert_usage": null,
            "hash_type": null,
            "key_tag": null,
            "port": 5061,
            "priority": 100,
            "proto": "_tcp",
            "proxied": false,
            "record": "@",
            "selector": null,
            "service": "_sipfederationtls",
            "solo": null,
            "state": "present",
            "timeout": 30,
            "ttl": 1,
            "type": "SRV",
            "value": "sipfed.online.lync.com",
            "weight": 1,
            "zone": "example.org"
        }
    },
    "item": [
        {
            "zone": "example.org"
        },
        {
            "port": 5061,
            "priority": 100,
            "proto": "_tcp",
            "record": "@",
            "service": "_sipfederationtls",
            "type": "SRV",
            "value": "sipfed.online.lync.com",
            "weight": 1
        }
    ],
    "result": {
        "record": {
            "content": "1\t5061\tsipfed.online.lync.com",
            "created_on": "2020-05-13T12:41:18.415013Z",
            "data": {
                "name": "example.org",
                "port": 5061,
                "priority": 100,
                "proto": "_tcp",
                "service": "_sipfederationtls",
                "target": "sipfed.online.lync.com",
                "weight": 1
            },
            "id": "hidden for privacy",
            "locked": false,
            "meta": {
                "auto_added": false,
                "managed_by_apps": false,
                "managed_by_argo_tunnel": false,
                "source": "primary"
            },
            "modified_on": "2020-05-13T12:41:18.415013Z",
            "name": "_sipfederationtls._tcp.example.org",
            "priority": 100,
            "proxiable": false,
            "proxied": false,
            "ttl": 1,
            "type": "SRV",
            "zone_id": "hidden for privacy",
            "zone_name": "example.org"
        }
    }
}
```

I've tried various things such as "TCP", "_tcp", a dot after the target, etc, but it always reports changed.

In the above report I've changed some things to prevent information leaks about my domains and local paths. I hope that's ok.
