### ISSUE TITLE
[Docs] Add example of capturing show tech output for networks

### ISSUE THREAD

**Issue by samccann** [ansible/ansible#69493]
##### SUMMARY

A common network task is to gather the 'show tech' output from a network device. Add an example of how to do this in the network user guide.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs.ansible.com
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

**Comment by samccann** [comment]
Use this to source the info from - https://github.com/network-automation/ansible-gather-show-tech

**Comment by samccann** [comment]
the ansible-gather-show-tech does work with few modifications

```
- hosts: "{{ swname }}"
  connection: network_cli
  gather_facts: no
  vars:
    ansible_command_timeout: "{{ cmd_timeout | default(999) }}"
  roles:
    - role: showtech
```
capture_showtech.yml   added longer command timeout (edited) 

```
--
# - name: do not run this role if the version of ansible is wrong
#   assert:
#     that: "ansible_version is defined and (ansible_version.full | version_compare('2.5', '>='))"
#     msg: "Requires Ansible 2.5 and higher"
- name: get the timestamp so that the show techs can be timestamped
  setup:
    filter: ansible_date_time
  delegate_to: localhost
- include_tasks: "{{ ansible_network_os }}.yml"
```

roles/showtech/tasks/tftp/main.yml   comment out version control

**Comment by samccann** [comment]
Another working example:

```
---
- name: Test Show tech
  hosts: rtr1
  gather_facts: no
  tasks:
    - name: collect show tech
      ios_command:
        commands: show tech
      register: output
    - name: save report
      template:
        src: sh_tech.j2
        dest: tech_report.txt
      delegate_to: localhost
      run_once: true
```
