### ISSUE TITLE
Ansible "copy" module excessive memory usage

### ISSUE THREAD

**Issue by sbonds** [ansible/ansible#69506]
This is similar to the closed issue #16837

The latest release branch in GitHub is affected. "devel" would not work in my test environment so I could not check that branch.

##### SUMMARY

When using the "copy" module to save data on localhost from a large number of hosts, the memory usage becomes excessive irrespective of the number of forks in use.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy module

##### ANSIBLE VERSION
```paste below
ansible 2.9.9.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bondsst/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bondsst/ansible-github/lib/ansible
  executable location = /home/bondsst/ansible-github/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```paste below
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = dzdo
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/sbonds/.ansible/inventory']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /home/sbonds/.ansible/ansible.log
```

##### OS / ENVIRONMENT
Azure VM running RHEL 7.8 patched as of May 3 2020.

VM sizes tried: B2ms: 2vCPU 8GiB RAM and B16ms: 16vCPU 64GiB RAM.

##### STEPS TO REPRODUCE
There's probably still some work on making this "minimal" but when run against approximately 150 hosts, the below collect-and-save Ansible facts playbook only gets about 8-9 hosts into the copy process before the 8GiB host is out of memory. The 64GiB host managed to make it about 60 hosts in before it ran out of memory. In the 8GiB case, "forks=1" was used. In the 64GiB case, "forks=5" was used, but this doesn't seem to make any difference, most likely due to the "delegate_to: localhost" in use.

Here is the playbook:

```yaml
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Put Ansible date into var for creating output files with the same timestamp
    set_fact:
      datestamp: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second}}"
      cacheable: yes
  - name: Copy Ansible facts to local files in Ansible playbook directory
    copy:
      content: "{{ vars }}"
      dest: "ansible_facts-{{ inventory_hostname }}-{{ datestamp }}.json"
    delegate_to: localhost
    become: false
```

##### EXPECTED RESULTS
I would expect the memory usage to be relatively independent of the number of hosts since the data goes into individual files by host. Once that host's info has been written to the file it would no longer be needed so could be discarded.

##### ACTUAL RESULTS
When copying a large variable to per-host files, the "ansible-playbook" process memory usage grows without bound until the host OS fails due to running out of memory.

```paste below
<oom-killer on Linux gets activated>
[716456.007899] Out of memory: Kill process 7866 (ansible-playboo) score 154 or sacrifice child
[716456.015780] Killed process 7866 (ansible-playboo), UID 1000, total-vm:1901200kB, anon-rss:1494920kB, file-rss:1100kB, shmem-rss:0kB
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/files/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/copy.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is somewhat expected, understanding the mechanics behind what the copy module has to do to place `content` into a file. A few things to note:

1. When using `copy` with `content`, ansible will end up making multiple copies of that data.  The process is, intake the data from `content`, JSON encode that data, create an in memory tar.gz that contains that JSON, write that tar.gz to disk, copy that tar.gz to a temporary directory on the target, spin up a fork, establish a connection, read that tar.gz, read the JSON, deserialize the JSON, write the `content` to a file.  When doing this effectively all against localhost, there may be many many copies of this data open.
1. `vars` should typically not be used. It purposefully doesn't template data, and was never meant for public consumption
1. `vars` is not inherently JSON data, it's just a python dict, so writing that content straight to a file isn't JSON.

I would recommend switching to a `template` task, that uses something like the following:

vars.j2
```
{{ hostvars[inventory_hostname]|to_nice_json }}
```

And the associated task:

```yaml
  - name: Copy Ansible facts to local files in Ansible playbook directory
    template:
      src: vars.j2
      dest: "ansible_facts-{{ inventory_hostname }}-{{ datestamp }}.json"
    delegate_to: localhost
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by sbonds** [comment]
Thanks for the excellent workaround. Here's the new playbook which works perfectly even against 100+ hosts run 15 at a time.

```yaml
---
- hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Put Ansible date into var for creating output files with the same timestamp
    set_fact:
      datestamp: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second}}"
      cacheable: yes
  # Prior method using "copy" module used a truly excessive amount of memory
  # This is the approach suggested in:
  #   https://github.com/ansible/ansible/issues/69506
  - name: Copy Ansible facts to local files in Ansible playbook directory
    template:
      src: save-ansible-facts.j2
      dest: "ansible_facts-{{ inventory_hostname }}-{{ datestamp }}.json"
    delegate_to: localhost
    become: false
```

I especially appreciate the walk-through of the copy process. I was picking through the Python and couldn't follow what it was trying to do for the specific case of `content:` since there are so many code paths possible related to recursive copy, etc. Your summary really does a nice job of describing why I saw what I saw and will help me resolve some other issues I'm having with "copy" in a completely different context.
