### ISSUE TITLE
junos_command module does not seem to support huge_tree

### ISSUE THREAD

**Issue by crab86** [ansible/ansible#69512]
##### SUMMARY
When running junos_command module with a command that has a huge output (e.g. request support information) an error is shown. The error message basically points to huge_tree either not supported or not used: 
```xmlSAX2Characters:` huge text node, line 218817, column 28 (<string>, line 218817)'" Full error message below.```

The corresponding fix in ncclient was commited May 20, 2019  (https://github.com/ncclient/ncclient/pull/319) and py-junos-eznc implemented the fix in November 2019 (https://github.com/Juniper/py-junos-eznc/pull/975). 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_command.py / junos_command Module. Maybe other modules are affected as well. 

##### ANSIBLE VERSION
Basically we are using ansible AWX Version 9.3.0 with corresponding ansible-version etc. 
```
bash-4.4# ansible --version
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION
Basically we are using ansible AWX Version 9.3.0
```
bash-4.4# ansible-config dump --only-changed
bash-4.4#

```

##### OS / ENVIRONMENT
Model: mx960

##### STEPS TO REPRODUCE
Run the playbook below. 
```
---
- name: Create RSI and Log Archives for Juniper Cases
  hosts: all
  gather_facts: False
  tasks:
    - name: gather facts from localhost
      setup:
      delegate_to: localhost
    - name: Create RSI, compress it and compress all Logs (may take some time..)
      junos_command:
        commands:
          - 'request support information | save /var/tmp/rsi_{{ ansible_play_batch | join(" ") }}_{{ ansible_date_time.date }}.log'
          - 'file compress file /var/tmp/rsi_{{ ansible_play_batch | join(" ") }}_{{ ansible_date_time.date }}.log'
          - 'file archive compress source /var/log/* destination /var/home/ansible/logs_{{ ansible_play_batch | join(" ") }}_{{ ansible_date_time.date }}.tgz'
        timeout: 900
      register: output

  vars:
     ansible_connection: local
     ansible_network_os: junos
     ansible_command_timeout: 900
     persistent_command_timeout: 900
     persistent_log_messages: yes
     timeout: 900
```

##### EXPECTED RESULTS
Getting rsi and logs as compressed files.

##### ACTUAL RESULTS
We are getting the error below. 
```
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 83, in parse_rpc_error\n  File \"src/lxml/etree.pyx\", line 3236, in lxml.etree.fromstring\n  File \"src/lxml/parser.pxi\", line 1876, in lxml.etree._parseMemoryDocument\n  File \"src/lxml/parser.pxi\", line 1764, in lxml.etree._parseDoc\n  File \"src/lxml/parser.pxi\", line 1127, in lxml.etree._BaseParser._parseDoc\n  File \"src/lxml/parser.pxi\", line 601, in lxml.etree._ParserContext._handleParseResultDoc\n  File \"src/lxml/parser.pxi\", line 711, in lxml.etree._handleParseResult\n  File \"src/lxml/parser.pxi\", line 640, in lxml.etree._raiseParseError\n  File \"<string>\", line 1\nlxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1589456899.7499487-74285743259611/AnsiballZ_junos_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1589456899.7499487-74285743259611/AnsiballZ_junos_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1589456899.7499487-74285743259611/AnsiballZ_junos_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.junos.junos_command', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/modules/network/junos/junos_command.py\", line 443, in <module>\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/modules/network/junos/junos_command.py\", line 390, in main\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/modules/network/junos/junos_command.py\", line 229, in rpc\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 53, in exec_rpc\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 76, in __rpc__\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 108, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: b'xmlSAX2Characters: huge text node, line 218817, column 28 (<string>, line 218817)'\n",
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 83, in parse_rpc_error\n  File \"src/lxml/etree.pyx\", line 3236, in lxml.etree.fromstring\n  File \"src/lxml/parser.pxi\", line 1876, in lxml.etree._parseMemoryDocument\n  File \"src/lxml/parser.pxi\", line 1764, in lxml.etree._parseDoc\n  File \"src/lxml/parser.pxi\", line 1127, in lxml.etree._BaseParser._parseDoc\n  File \"src/lxml/parser.pxi\", line 601, in lxml.etree._ParserContext._handleParseResultDoc\n  File \"src/lxml/parser.pxi\", line 711, in lxml.etree._handleParseResult\n  File \"src/lxml/parser.pxi\", line 640, in lxml.etree._raiseParseError\n  File \"<string>\", line 1\nlxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1589456899.7499487-74285743259611/AnsiballZ_junos_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1589456899.7499487-74285743259611/AnsiballZ_junos_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1589456899.7499487-74285743259611/AnsiballZ_junos_command.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.junos.junos_command', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/modules/network/junos/junos_command.py\", line 443, in <module>\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/modules/network/junos/junos_command.py\", line 390, in main\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/modules/network/junos/junos_command.py\", line 229, in rpc\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 53, in exec_rpc\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 76, in __rpc__\n  File \"/tmp/ansible_junos_command_payload_xv4gr6j3/ansible_junos_command_payload.zip/ansible/module_utils/network/common/netconf.py\", line 108, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: b'xmlSAX2Characters: huge text node, line 218817, column 28 (<string>, line 218817)'\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "_ansible_no_log": false,
    "changed": false
}
```
