### ISSUE TITLE
Network resource modules behaves inconsistently between IOS/EOS

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible#69511]
##### SUMMARY

Playbook tasks that use the IOS Resource modules do not print out the proposed changes when executed in check mode.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

An example would be `ios_l3_interfaces`. But it is not just this one module.

##### ANSIBLE VERSION

```paste below
ansible 2.9.3
  config file = /home/student1/gerald_test/ansible.cfg
  configured module search path = [u'/home/student1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/student1/gerald_test/ansible.cfg) = [u'/home/student1/gerald_test/coll
DEFAULT_HOST_LIST(/home/student1/gerald_test/ansible.cfg) = [u'/home/student1/networking-works
DEFAULT_STDOUT_CALLBACK(/home/student1/gerald_test/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/home/student1/gerald_test/ansible.cfg) = False
HOST_KEY_CHECKING(/home/student1/gerald_test/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/student1/gerald_test/ansible.cfg) = 600
PERSISTENT_CONNECT_TIMEOUT(/home/student1/gerald_test/ansible.cfg) = 600
RETRY_FILES_ENABLED(/home/student1/gerald_test/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Linux ansible 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Cisco CSR

##### STEPS TO REPRODUCE

```yaml
---
- name: IOS Resource module test
  hosts: rtr1
  gather_facts: no
  tags: ios
  tasks:
    - name: GATHER L3 CONFIG
      ios_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - name: DISPLAY INTERFACE DATA
      debug: var=ansible_network_resources

    - name: ADD LOOPBACK
      ios_l3_interfaces:
        config: 
          - name: Loopback 100
            ipv4:
              - address: 192.168.0.1/24
        state: merged        
          
        
- name: EOS Resource module test
  hosts: rtr2
  gather_facts: no
  tags: eos
  tasks:
    - name: GATHER L3 CONFIG
      eos_facts:
        gather_subset: min
        gather_network_resources: l3_interfaces

    - name: DISPLAY INTERFACE DATA
      debug: var=ansible_network_resources

    - name: ADD LOOPBACK
      eos_l3_interfaces:
        config: 
          - name: Loopback 100
            ipv4:
              - address: 192.168.0.1/24
        state: merged    
```

Execute using check mode to see the difference:
```
ansible-playbook resource_test.yaml --check -v
```

##### EXPECTED RESULTS

Expect the ios modules to also display the changed config to be displayed.

##### ACTUAL RESULTS

```paste below
[student1@ansible gerald_test]$ ansible-playbook resource_test.yaml --check -v
Using /home/student1/gerald_test/ansible.cfg as config file

PLAY [IOS Resource module test] **************************************************************

TASK [GATHER L3 CONFIG] **********************************************************************
[WARNING]: default value for `gather_subset` will be changed to `min` from `!config` v2.11
onwards

ok: [rtr1] => changed=false 
  ansible_facts:
    ansible_net_api: cliconf
    ansible_net_gather_network_resources:
    - l3_interfaces
    ansible_net_gather_subset:
    - default
    ansible_net_hostname: ip-172-16-149-162
    ansible_net_image: bootflash:packages.conf
    ansible_net_iostype: IOS-XE
    ansible_net_model: CSR1000V
    ansible_net_python_version: 2.7.5
    ansible_net_serialnum: 9NHO4224RYH
    ansible_net_system: ios
    ansible_net_version: 16.09.02
    ansible_network_resources:
      l3_interfaces:
      - ipv4:
        - address: dhcp
        name: GigabitEthernet1
    discovered_interpreter_python: /usr/bin/python

TASK [DISPLAY INTERFACE DATA] ****************************************************************
ok: [rtr1] => 
  ansible_network_resources:
    l3_interfaces:
    - ipv4:
      - address: dhcp
      name: GigabitEthernet1

TASK [ADD LOOPBACK] **************************************************************************
ok: [rtr1] => changed=false 
  before:
  - ipv4:
    - address: dhcp
    name: GigabitEthernet1
  commands: []

PLAY [EOS Resource module test] **************************************************************

TASK [GATHER L3 CONFIG] **********************************************************************
ok: [rtr2] => changed=false 
  ansible_facts:
    ansible_net_api: cliconf
    ansible_net_fqdn: rtr2
    ansible_net_gather_network_resources:
    - l3_interfaces
    ansible_net_gather_subset:
    - default
    ansible_net_hostname: rtr2
    ansible_net_image: flash:vEOS-Router.swi
    ansible_net_model: vEOS
    ansible_net_python_version: 2.7.5
    ansible_net_serialnum: 7D3DD3733E86DADEA9A86FBE905D0F4A
    ansible_net_system: eos
    ansible_net_version: 4.22.1FX-VEOSRouter-cloud
    ansible_network_resources:
      l3_interfaces:
      - ipv4:
        - address: dhcp
        name: Ethernet1
      - ipv4:
        - address: 192.168.2.2/32
        name: Loopback0
      - ipv4:
        - address: 10.101.101.2/24
        name: Tunnel0
      - ipv4:
        - address: 10.200.200.2/24
        name: Tunnel1
    discovered_interpreter_python: /usr/bin/python

TASK [DISPLAY INTERFACE DATA] ****************************************************************
ok: [rtr2] => 
  ansible_network_resources:
    l3_interfaces:
    - ipv4:
      - address: dhcp
      name: Ethernet1
    - ipv4:
      - address: 192.168.2.2/32
      name: Loopback0
    - ipv4:
      - address: 10.101.101.2/24
      name: Tunnel0
    - ipv4:
      - address: 10.200.200.2/24
      name: Tunnel1

TASK [ADD LOOPBACK] **************************************************************************
changed: [rtr2] => changed=true 
  after:
  - ipv4:
    - address: dhcp
    name: Ethernet1
  - ipv4:
    - address: 192.168.2.2/32
    name: Loopback0
  - ipv4:
    - address: 10.101.101.2/24
    name: Tunnel0
  - ipv4:
    - address: 10.200.200.2/24
    name: Tunnel1
  before:
  - ipv4:
    - address: dhcp
    name: Ethernet1
  - ipv4:
    - address: 192.168.2.2/32
    name: Loopback0
  - ipv4:
    - address: 10.101.101.2/24
    name: Tunnel0
  - ipv4:
    - address: 10.200.200.2/24
    name: Tunnel1
  commands:
  - interface Loopback100
  - ip address 192.168.0.1/24

PLAY RECAP ***********************************************************************************
rtr1                       : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
rtr2                       : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


```
