### ISSUE TITLE
When the tasks with json_query inside a block are always evaluated

### ISSUE THREAD

**Issue by comefigo** [ansible/ansible#69528]
##### SUMMARY
When a task inside a skipped block has a json_query with var defined inside that block, ansible tries to run that task when it should have skipped (it is inside the block). It doesn't happens when using json_query

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/plugins/filter

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Dec 12 2019, 23:58:22) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]
```

##### CONFIGURATION
```
N/A Just pip installed
```

##### OS / ENVIRONMENT

on Windows Docker Desktop
Amazon Linux 2 container

##### STEPS TO REPRODUCE

```yaml
- name: Failed
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - block:
      - set_fact:
          myvar:
            key1: value1
            childrens: ['1', '2', '3']

      - debug:
          msg: "Item is: {{ item }}"
        with_items: "{{ myvar| json_query('childrens[*]') }}"
      when: False
```

##### EXPECTED RESULTS
To skip the task with json_query that is inside the block skipped

##### ACTUAL RESULTS
```paste below
bash-4.2# ansible-playbook -i inventories/local_hosts playbooks/test.yml 

PLAY [Failed] *************************************************

TASK [set_fact] ************************************************
skipping: [localhost]

TASK [debug] **************************************************
fatal: [localhost]: FAILED! => {"msg": "Error in jmespath.search in json_query filter plugin:\n'myvar' is undefined"}

PLAY RECAP ***************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
```
