### ISSUE TITLE
ansible_connection docker does not recognize PATH environment variable in /etc/profile

### ISSUE THREAD

**Issue by abdennour** [ansible/ansible#69529]
##### SUMMARY

A playbook with host `ansible_connection=docker` is not able to ready environment variables added under /etc/profile.d directory.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker ansible_connection 

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /Users/abdennour/dev/k8s-cluster/ansible.cfg
  configured module search path = ['/Users/abdennour/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/abdennour/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /Users/abdennour/Library/Python/3.7/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:27) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

I have a playbook which : 
- update some environment variables (i.e: `PATH`) by adding sh files inside `/etc/profile.d` directory.
- Then run some tasks which rely on these environment variables

I installed SSHD inside my container, and I hit the container with `ansible_connection=ssh` . 
Everything is working fine.
Now, I changed `ansible_connection=ssh` to be `ansible_connection=docker` using the same container.
However, I got some errors which means that the environment variables added under /etc/profile.d have not been take effect. 

```yaml
- name: Set GOPATH for all users and add to PATH
  copy:
    src: go-path.sh
    dest: /etc/profile.d
- name: Version check
  command: "go version" 
# Here we got the error. because it cannot find "go" while it is added in PATH by the previous task

```

##### EXPECTED RESULTS

We expect that when we use `ansible_connection=docker` , it should consider env variables added unside /etc/profile or /etc/profile.d in general.

##### ACTUAL RESULTS

```paste below
container-rhel2 | FAILED | rc=1 >>                             │
which: no go in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)non-zero return code 
```
