### ISSUE TITLE
group_by handles jinja filters non-gracefully

### ISSUE THREAD

**Issue by neshura** [ansible/ansible#6953]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.5.3
##### Environment:

control: OSX
management: RHEL5/6
##### Summary:

If you supply a jinja filter in a group_by key, the unexpected result is a dynamic group created with the name as a string literal up to and including the pipe (|) symbol. It would be nice if it either failed in a way that made it clear that filters are not allowed, or supported filters.
##### Steps To Reproduce:

Create a group of hosts and filter the variable used for the key. 

```

---
- hosts: somehosts
  user: deploy
  sudo: yes
  gather_facts: yes
  tasks:
    - group_by: key={{ ansible_distribution_release }}-{{ ansible_distribution_version | truncate(1, True, '') }}
```

Create a group of hosts with the group name that would be expected.

```
- hosts: RedHat-6
  user: deploy
  sudo: yes
  gather_facts: yes
  roles:
    - somerole

- hosts: RedHat-5
  user: deploy
  sudo: yes
  gather_facts: yes
  tasks:
    - fail: "RHEL5 is not currently supported for this release"
```

Create a group of hosts with the group name as a strange string literal that matches a chunk of unhandled code.

```
- hosts: '{{ansible_distribution_release}}-{{ansible_distribution_version'
  user: deploy
  sudo: yes
  gather_facts: yes
  tasks:
    - command: echo $HOSTNAME
```
##### Expected Results:

I would expect the role 'somerole' to be applied to the RedHat-6 machines in production, and not to end up deployed on any lingering RedHat-5 hosts. (Obviously I can match and handle os versions in a different way, such as any number of os-specific group vars suggested by the documentation, the scenario exists just to demonstrate the issue.)

I would definitely not expect the final group of hosts, as above, to be created and usable.
##### Actual Results:

```
TASK: [group_by key={{ansible_distribution_release}}-{{ansible_distribution_version | truncate(1, True, '')}}] ***
changed: [foohost1-somesite]

PLAY [RedHat-6] ***************************************************************
skipping: no hosts matched

PLAY [RedHat-5] ***************************************************************
skipping: no hosts matched

PLAY [{{ansible_distribution_release}}-{{ansible_distribution_version] ********

GATHERING FACTS ***************************************************************
ok: [foohost2-somesite]
ok: [foohost3-somesite]
ok: [foohost1-somesite]

TASK: [command echo $HOSTNAME] ************************************************
changed: [foohost2-somesite]
changed: [foohost3-somesite]
changed: [foohost1-somesite]
```

Working around is not difficult, but one is required to create a temporary variable or fact to hold interim filtered results.
