### ISSUE TITLE
win_regedit is modifying wrong registry keys

### ISSUE THREAD

**Issue by wstestdwf** [ansible/ansible#69535]
##### SUMMARY
Hi all,
I noticed today morning that wrong keys are modified when using win_regedit module.
**HKU keys are modified instead of HKCU**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/windows/win_regedit.ps1

##### ANSIBLE VERSION

```paste below
ansible 2.7.10
```

##### OS / ENVIRONMENT
Windows server 2016

##### STEPS TO REPRODUCE

```yaml
   - name: MigrateProxy
     win_regedit:
      path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\
      name: MigrateProxy
      data: 1
      type: dword

   - name: ProxyEnable
     win_regedit:
      path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\
      name: ProxyEnable
      data: 0
      type: dword

   - name: AutoConfigURL
     win_regedit:
      path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\
      name: AutoConfigURL
      data: http://pac.zscloud.net/

   - name: AutoDetect
     win_regedit:
      path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\
      name: AutoDetect
      data: 0
      type: dword
```

##### EXPECTED RESULTS
Add reg keys:
MigrateProxy
ProxyEnable
AutoConfigURL
AutoDetect 

under HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings

##### ACTUAL RESULTS
PS output
Get-ItemProperty   -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet   Settings"
![image](https://user-images.githubusercontent.com/48476603/82049945-9028dc80-96b7-11ea-8faf-83a9e4aa8d8a.png)

** `module is modifying HKU instead HKCU`**
PS output:
Get-ItemProperty -Path "Registry::HKEY_USERS\SID\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings"
![image](https://user-images.githubusercontent.com/48476603/82050122-df6f0d00-96b7-11ea-9611-b12c9f2a57eb.png)

Could you please take a look at it?
