### ISSUE TITLE
win_user_right: Intermittent failure on domain controller

### ISSUE THREAD

**Issue by dmhii** [ansible/ansible#69538]
##### SUMMARY
We are receiving intermittent errors when applying user right assignments to a domain controller.

FAILED! => {"changed": false, "msg": "failed to convert sid '[sid value removed]' to a logon name: Exception calling \"Translate\" with \"1\" argument(s): \"Some or all identity references could not be translated.\""}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_user_right

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/AD/zzmorada/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/AD/zzmorada/.local/lib/python3.5/site-packages/ansible
  executable location = /home/AD/zzmorada/.local/bin/ansible
  python version = 3.5.2 (default, Apr 16 2020, 17:47:17) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = ignore

```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml

  win_user_right:
    name: SeAuditPrivilege
    users: "{{ security_win2012r2_wn12_ur_000024_users }}"
    action: set
  when: (security_win2012r2_wn12_ur_000024|bool)
  tags:
    - userRightsAssignment


----

security_win2012r2_wn12_ur_000024_users:
  - Local Service
  - Network Service
  - IIS APPPOOL\DefaultAppPool

```

##### EXPECTED RESULTS
win_user_right works consistently and is idempotent

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "msg": "failed to convert sid '[sid removed]' to a logon name: Exception calling \"Translate\" with \"1\" argument(s): \"Some or all identity references could not be translated.\""}
```
