### ISSUE TITLE
Variables are not delegated in sub-task loop

### ISSUE THREAD

**Issue by Wernfried** [ansible/ansible#69544]
##### SUMMARY

When running a delegated subtask then variables are not delegated to host.

Only the last item of loop is delegated. The delegating host gets the variable value.
If I set `delegate_facts: no` then results are populated to delegating host (as expected).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
[domscheit@p-ansbl-as-01 case]$ ansible-playbook --version
ansible-playbook 2.9.5
  config file = /home/domscheit/case/ansible.cfg
  configured module search path = [u'/home/domscheit/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
[domscheit@p-ansbl-as-01 case]$ ansible-config dump --only-changed
COLOR_DIFF_REMOVE(/home/domscheit/case/ansible.cfg) = bright purple
COLOR_ERROR(/home/domscheit/case/ansible.cfg) = bright red
COLOR_UNREACHABLE(/home/domscheit/case/ansible.cfg) = bright red
COLOR_VERBOSE(/home/domscheit/case/ansible.cfg) = cyan
DEFAULT_HOST_LIST(/home/domscheit/case/ansible.cfg) = [u'/home/domscheit/case/inventory']
HOST_KEY_CHECKING(/home/domscheit/case/ansible.cfg) = False
INVENTORY_ENABLED(/home/domscheit/case/ansible.cfg) = [u'yaml', u'ini']
```

##### OS / ENVIRONMENT

```
[domscheit@p-ansbl-as-01 case]$ hostnamectl
   Static hostname: p-ansbl-as-01
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 1f825306d5ee467d9aa34bea35751abc
           Boot ID: 5cb9042c6b3f4f539f9e1ad4c2840189
    Virtualization: vmware
  Operating System: Red Hat Enterprise Linux
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.8:GA:server
            Kernel: Linux 3.10.0-1127.8.2.el7.x86_64
      Architecture: x86-64
```

##### STEPS TO REPRODUCE

The main playbook:

```
---
- hosts: all
  vars:
    results: {}
  tasks:
  - include_tasks: "subtask.yml"
    vars:
      par: "{{ item }}"
    loop:
      - "a"
      - "b"
      - "c"
    when: "'d-mipmdb-cfg-01' == inventory_hostname_short"
    
  - include_tasks: "subtask-delegate.yml"
    vars:
      par: "{{ item }}"
    loop:
      - "x"
      - "y"
      - "z"
    when: "'d-mipmdb-cfg-01' == inventory_hostname_short"

  - debug:
      var: results
...  
```
And these subtasks files:
```
---
# subtask.yml
- shell:
    cmd: "echo {{ par }}"
  register: ret
- set_fact:
    results: "{{ results | combine({par: ret.rc}) }}"
...  

---
# subtask-delegate.yml
- shell:
    cmd: "echo {{ par }}"
  register: ret
  delegate_to: d-mipmdb-arb-01
  delegate_facts: yes
- set_fact:
    results: "{{ results | combine({par: ret.rc}) }}"
  delegate_to: d-mipmdb-arb-01
  delegate_facts: yes
...  
```
##### EXPECTED RESULTS

```
TASK [debug] **********************************************
ok: [d-mipmdb-cfg-01] => {
    "results": {
        "a": 0, 
        "b": 0, 
        "c": 0
    }
}
ok: [d-mipmdb-arb-01] => {
    "results": {
        "x": 0
        "y": 0
        "z": 0
    }
}
```

##### ACTUAL RESULTS
```
TASK [debug] **********************************************
ok: [d-mipmdb-cfg-01] => {
    "results": {
        "a": 0, 
        "b": 0, 
        "c": 0
    }
}
ok: [d-mipmdb-arb-01] => {
    "results": {
        "a": 0, 
        "b": 0, 
        "c": 0, 
        "z": 0
    }
}

```
