### ISSUE TITLE
copy module: No option to exclude directory in copy module

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#69559]
##### SUMMARY
Currently there is no option to exclude the directory inside a directory while using copy module. Due to which copy module is failing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
copy.py

##### ANSIBLE VERSION
```
$ pip3 show ansible
Name: ansible
Version: 2.9.9
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: jinja2, PyYAML, cryptography
Required-by:
```

##### OS / ENVIRONMENT
- Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE

```
---
- name: Copy Folder to Provision Server
  hosts: pro1
  gather_facts: false

  tasks:
  - name: Copying '/root/CodePlay' to Provision Server under '/tmp' directory
    copy:
      src: '/root/CodePlay'
      dest: '/tmp'
      directory_mode: True
      owner: ubuntu
      group: ubuntu
```
```
$ cat inventory
[pro1]
xxx.xxx.xxx.xxx
```

##### EXPECTED RESULTS
Using exclude option, should be able to exclude the file the way its available with rsync command in linux.

##### ACTUAL RESULTS
```
# ansible-playbook copyfile.yaml -i inventory  -u ubuntu --ask-pass
SSH password:

PLAY [Copy Folder to Provision Server] **********************************************************************************************************************************************************************************************************************************************************************************

TASK [Copying '/root/CodePlay' to Provision Server under '/tmp' directory] **********************************************************************************************************************************************************************************************************************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"msg": "Failed to get information on remote file (/tmp/CodePlay/.git/COMMIT_EDITMSG): Permission denied"}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************
xxx.xxx.xxx.xxx              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
```
$ ls -l CodePlay/.git/COMMIT_EDITMSG
-rw-r--r-- 1 root root 50 May  7 17:42 CodePlay/.git/COMMIT_EDITMSG
```

Similarly there are many files with 600 permission and 444 permission. And copying the .git file is not a wise decision. So I want to ignore that. Using rsync its really simple:

```
$ rsync  -avP --exclude=*.git  /root/CodePlay  ubuntu@xxx.xxx.xxx.xxx:/tmp
```

**Comment by manojscode** [comment]
please share the directory structure ( or sample structure )at the source and what you expect to see on the destination.

**Comment by Udayendu** [comment]
@manoj-ms 

Please find the requested details:

- Source folder structure
```
# pwd
/root/CodePlay

# ls -la
drwxrwxr-x  2 codebox codebox 4096 May 16 16:26 Code
drwxrwxr-x  2 codebox codebox 4096 May 16 13:37 Creds
drwxrwxr-x  6 codebox codebox 4096 Apr  1 09:33 Firewall
drwxr-xr-x  4 codebox codebox 4096 Mar 28 13:39 FirewallXML
drwxr-xr-x  8 root    root    4096 May  7 17:42 .git
drwxr-xr-x  2 codebox codebox 4096 May 16 13:37 GlobalVars
drwxrwxr-x  3 codebox codebox 4096 Mar 18 15:35 .idea
drwxr-xr-x  2 codebox codebox 4096 May 15 16:18 NSX-Scripts
drwxrwxr-x  5 codebox codebox 4096 May 16 18:40 Provision
drwxrwxr-x  2 codebox codebox 4096 May  3 16:24 Templates
```

- Destination folder structure
```
# pwd
/tmp/CodePlay

# ls -la
drwxrwxr-x  2 codebox codebox 4096 May 16 16:26 Code
drwxrwxr-x  2 codebox codebox 4096 May 16 13:37 Creds
drwxrwxr-x  6 codebox codebox 4096 Apr  1 09:33 Firewall
drwxr-xr-x  4 codebox codebox 4096 Mar 28 13:39 FirewallXML
drwxr-xr-x  2 codebox codebox 4096 May 16 13:37 GlobalVars
drwxr-xr-x  2 codebox codebox 4096 May 15 16:18 NSX-Scripts
drwxrwxr-x  5 codebox codebox 4096 May 16 18:40 Provision
drwxrwxr-x  2 codebox codebox 4096 May  3 16:24 Templates
```

**Comment by sysadmin75** [comment]
The synchronize module is an rsync wrapper and can already handle this.  It even gives an example.
```
- name: Synchronize passing in extra rsync options
  synchronize:
    src: /tmp/helloworld
    dest: /var/www/helloworld
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
```
