### ISSUE TITLE
pip and src install of ansible showing different behavior for action plugins in collections

### ISSUE THREAD

**Issue by anshulbehl** [ansible/ansible#69552]
##### SUMMARY

I am able to replicate an issue faced by Aruba where their action plugin is not getting triggered when being part of a new collection, interestingly enough I can only replicate that through a src install of ansible 2.9.9 and not through a pip install of ansible-2.9

With src install:
Value of ansible_host in inventory is not getting substituted and I see the below error:

TASK [Create VLAN 200] ***********************************************************************************************************************************************************************************************************************
fatal: [switch1]: FAILED! => {"changed": false, "msg": "Request failed: <urlopen error [Errno -2] Name or service not known>", "status": -1, "url": "http://None:80/rest/v6.0/login-sessions"}

With pip install:

The value is getting substituted

TASK [Create VLAN 200] ***********************************************************************************************************************************************************************************************************************
fatal: [switch1]: FAILED! => {"changed": false, "msg": "Request failed: <urlopen error timed out>", "status": -1, "url": "http://10.0.0.1:80/rest/v6.0/login-sessions"}

I am attaching the collection tarball which has an action plugin that gets triggered with pip install but not with the src install and that is causing the issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible core
Action plugins

##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/abehl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/abehl/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]


src install 
=============

ansible --version                                                     
ansible 2.9.9.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/abehl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/abehl/work/src/ansible/lib/ansible
  executable location = /home/abehl/work/src/ansible/bin/ansible
  python version = 3.8.2 (default, Feb 28 2020, 00:00:00) [GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  collections:
    - arubanetworks.arubaoss
  tasks:
    - name: Create VLAN 200
      arubaoss_vlan:
        vlan_id: 300
        name: "vlan300"
        config: "create"
        command: config_vlan
```

```yaml
all:
  hosts:
    switch1:
      ansible_host: 10.0.0.1
      ansible_user: admin
      ansible_password: password
      ansible_network_os: arubanetworks.arubaoss.arubaoss
      ansible_connection: local  # REST API connection method
```

##### EXPECTED RESULTS

Both installs should have no discrepancies

##### ACTUAL RESULTS

Action plugin is not getting triggered with a src install
Please find attached the collection tarball 
[arubaoss.tar.gz](https://github.com/ansible/ansible/files/4637211/arubaoss.tar.gz)

```paste below

```
