### ISSUE TITLE
Expose roles_path configuration option as variable

### ISSUE THREAD

**Issue by jgornick** [ansible/ansible#6955]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.5.4
##### Environment:

OS X 10.9.2
##### Summary:

Since you can configure the roles path with multiple paths and some roles provide "parameterized includes", it would be nice if the `roles_path` list was available as a variable.

An example might look like:

```
    - name: Call some role parameterized include
      include: "{{ item }}"
        param_one: "foo"
        param_two: "bar"
      with_first_found:
        - files:
            - "my_role/tasks/my_tasks.yml"
          paths: roles_path
```

**Comment by jgornick** [comment]
I've now learned that include + with_\* is deprecated.

There is still an issue though with roles providing parameterized includes and having to find those includes.

**Comment by jgornick** [comment]
To expand on the "There is still an issue though with roles providing parameterized includes and having to find those includes.", when multiple role paths are provided and you want to load a role parameterized include, you have to explicitly provide the path to the task file.

Just thinking out loud, it might be nice to have something like:

```
- name: Call some role parameterized include
  role_include: "my_role/tasks/my_tasks.yml"
  param_one: "foo"
  param_two: "bar"
```

The `role_include` statement will search through the configured role paths for the specified file to include. The `param_*` parameters would then be available as variables in the my_tasks.yml. This behavior is very similar to using parameterized includes but the `role_include` allows one to easily include a role include.

**Comment by jonhattan** [comment]
@jgornick I think you're asking for two things here:
1. A way to obtain a role's path, in order to reference a task. Something like rolename::taskname.yml that expands to /path/to/role/tasks/taskname.yml
2. A way to allow looping on parameterized includes. include + with_\* is forbidden, but it would be great to have a way to iterate over the same include file with different parameters.

To put an example, it would be great if this example from the docs:

``` yaml
tasks:
  - include: wordpress.yml user=timmy
  - include: wordpress.yml user=alice
  - include: wordpress.yml user=bob
```

could be expressed as:

``` yaml
- include: wordpress.yml {{ item }}
  with_items:
    - {user: timmy}
    - {user: alice}
    - {user: bob}
```

To put everything together:

``` yaml
- include: rolename::taskname.yml {{ item }}
  with_items: list_of_items_variable
```
