### ISSUE TITLE
Fedora-IoT package manager rpm-ostree is not recognized

### ISSUE THREAD

**Issue by ikke-t** [ansible/ansible#69565]
##### SUMMARY

I try ansible against Fedora-IoT, but the first package command fails:
```
TASK [setup nfs client] *********************************************************************************************************************
fatal: [fediot.ikenet]: FAILED! => {"changed": false, "msg": "missing required arguments: image, backend"}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
package

##### ANSIBLE VERSION
```
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ikke/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
nothing
```

##### OS / ENVIRONMENT
Ansible host: RHEL8.2
Ansible target: Fedora-IoT, Fedora release 32 (Thirty Two)

##### STEPS TO REPRODUCE

```
---

- name: setup Fedora IoT server
  hosts: all
  become: yes
  tasks:

    - name: install nfs client
      package:
        name: nfs-utils
        state: present

    - name: start nfs client
      service:
        name: rpc-bind
        state: running
        enabled: true
```

##### EXPECTED RESULTS

Recognise it needs to use rpmostree, and use that to install the package.

##### ACTUAL RESULTS
```
TASK [setup nfs client] *********************************************************************************************************************
fatal: [fediot.ikenet]: FAILED! => {"changed": false, "msg": "missing required arguments: image, backend"}
```
