### ISSUE TITLE
[module: cron] support for different print format and whitespace separator

### ISSUE THREAD

**Issue by tnaskali** [ansible/ansible#69573]
##### SUMMARY
Add support for a specific print format and whitespace separator in the cron module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cron module

##### ADDITIONAL INFORMATION
Add two new parameters `field_separator` and `field_print_format` to the cron module. Authorised values for `field_separator` are `SPACE` (default) and `TAB`. If `field_separator` is `SPACE`, then `field_print_format` (default value is `%s`) can be used to set the print format of each time field in printf style.

To use the TAB character as a separator :

```yaml
- cron:
    name: cron separator example
    field_separator: TAB
    job: script.sh
```

To use fixed-sized columns of size 10 for time fields, padded with spaces and aligned left :

```yaml
- cron:
    name: cron print format example
    field_print_format: %-10s
    job: script.sh
```

An error is raised if the application of the given format would truncate any of the time field values. Alternatively, only a warning can be raised and the column expanded to the required width.
