### ISSUE TITLE
Add ansible galaxy module

### ISSUE THREAD

**Issue by yajo** [ansible/ansible#69572]
##### SUMMARY

Currently, to install ansible galaxy requirements you need to use the CLI. But isn't Ansible about automation?

We should have an `ansible_galaxy` module which handles installing roles or collections in the specified path.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

modules

##### ADDITIONAL INFORMATION

```yaml
- name: base playbook
  hosts: localhost
  tasks:
  - name: install collections
    ansible_galaxy:
      type: collections
      requirements_file: "{{ playbook_dir }}/requirements.yml"
      dst: "{{ playbook_dir }}/collections"

  - name: install roles
    ansible_galaxy:
      type: roles
      requirements:
        - tecnativa.docker
      dst: "{{ playbook_dir }}/roles"

- name: do the real thing
  collections:
  - a_collection_that_i_just_installed.in_the_previous_play

  ...
```
