### ISSUE TITLE
Reopen: VMWare: Fix issue #62810 Allow Dash in Windows Server DNS name #64052

### ISSUE THREAD

**Issue by guliaka** [ansible/ansible#69589]
##### SUMMARY

vmware_guest module strips dashes from computer name during customization
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest.py
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Centos 8.1/RHEL 8.1 /RHEL 8.2

##### STEPS TO REPRODUCE

```yaml
  - name:  Clone a virtual machine from Windows 2019 template and customize
    vmware_guest:
      hostname: "{{ VMWARE_HOST }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      validate_certs: no
      datacenter: 'xxxxxxxx'
      # state: poweredon
      folder: 'xxxxxxxxxxxxxx'
      template: 'xxxxxxxxxxxxxxx'
      name: "{{ hstname }}"
      cluster: 'Internal cluster'
      datastore: 'tst datastore cluster'
      networks:
        - name: xxxxxxxxxxxx
          type: static
          ip: "{{ guest_ip }}"
          netmask: 255.255.255.0
          gateway: xxx.xxx.xxx.xxx
      customization:
        joindomain: xxxxxxxxx
        domainadmin: "{{ ad_add_user }}"
        domainadminpassword: "{{ ad_add_password }}"
        fullname: 'Tech'
        orgname: 'xxxxxxxxx'
        timezone: 004
        dns_servers:
          - xxx.xxx.xxx.xxx
          - xxx.xxx.xxx.xxx
        dns_suffix:
          - xxxxxxxxxxx   
      wait_for_ip_address: True
      wait_for_customization: yes
    when: act1 == 'create'
    delegate_to: localhost
    register: vm
	
	hstname = vm-tst-xxxxxx
```

##### EXPECTED RESULTS

Get new vm with name vm-tst-xxxxxx in vCenter and windows server name  vm-tst-xxxxxx

##### ACTUAL RESULTS

```paste below
I'm getting new vm with name vm-tst-xxxxxx in vCenter and windows server name  vmtstxxxxxx 
```
