### ISSUE TITLE
block/rescue do not work with tags 

### ISSUE THREAD

**Issue by KervinGtz** [ansible/ansible#69584]
##### SUMMARY
when specifying tags such as 'ansible-playbook lab.yml --tags bar', errors are not caught by rescue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

block, rescue, tags

##### ANSIBLE VERSION

```paste below

ansible 2.9.2
  config file = /home/netadmin/tmp/dev_vlan_ci/ansible.cfg
  configured module search path = ['/home/netadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/netadmin/.local/lib/python3.6/site-packages/ansible
  executable location = /home/netadmin/.local/bin/ansible
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
"CACHE_PLUGIN(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = ./artifacts/facts
CACHE_PLUGIN_TIMEOUT(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = ['profile_tasks']
DEFAULT_GATHERING(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = ['/home/netadmin/tmp/dev_vlan_ci/artifacts/host.vars.yml']
HOST_KEY_CHECKING(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = False
INTERPRETER_PYTHON(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = /usr/bin/python3
INVENTORY_CACHE_ENABLED(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = True
PARAMIKO_HOST_KEY_AUTO_ADD(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = 30
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/netadmin/tmp/dev_vlan_ci/ansible.cfg) = False
"
```

##### OS / ENVIRONMENT
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

##### STEPS TO REPRODUCE

```yaml
##
---
- hosts: localhost
  connection: local
  gather_facts: no
  name: labbing roles
  tasks:
    - name: test tags inside playbook
      block:
        - name: this task should fail due to variable not defined
          debug:
            msg: 'This should print tagged - FOO'
          tags:
             - foo

        - name: this task should fail due to variable not defined
          debug:
            msg: 'This {{ undefined }} should print tagged - BAR'
          tags:
            - bar
      rescue:
        - name: debug error
          debug:
            msg: 'found error {{ ansible_failed_result }}'
...
## running playbook with no tags defined:
$ ansible-playbook lab.yml

PLAY [labbing roles] ************************************************************************************************************************************************************************

TASK [this task should fail due to variable not defined] ************************************************************************************************************************************
Monday 18 May 2020  11:17:53 -0400 (0:00:00.055)       0:00:00.055 ************
ok: [localhost] => {
    "msg": "This should print tagged - FOO"
}

TASK [this task should fail due to variable not defined] ************************************************************************************************************************************
Monday 18 May 2020  11:17:53 -0400 (0:00:00.037)       0:00:00.093 ************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'undefined' is undefined\n\nThe error appears to be in '/home/netadmin/tmp/dev_vlan_ci/lab.yml': line 15, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: this task should fail due to variable not defined\n          ^ here\n"}

TASK [debug error] **************************************************************************************************************************************************************************
Monday 18 May 2020  11:17:53 -0400 (0:00:00.156)       0:00:00.250 ************
ok: [localhost] => {
    "msg": "found error {'failed': True, 'msg': \"The task includes an option with an undefined variable. The error was: 'undefined' is undefined\\n\\nThe error appears to be in '/home/netadmin/tmp/dev_vlan_ci/lab.yml': line 15, column 11, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n        - name: this task should fail due to variable not defined\\n          ^ here\\n\", '_ansible_no_log': False}"
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0

## running playbook with tags defined:
$ ansible-playbook lab.yml --tags foo,bar

PLAY [labbing roles] ************************************************************************************************************************************************************************

TASK [this task should fail due to variable not defined] ************************************************************************************************************************************
Monday 18 May 2020  11:21:43 -0400 (0:00:00.054)       0:00:00.054 ************
ok: [localhost] => {
    "msg": "This should print tagged - FOO"
}

TASK [this task should fail due to variable not defined] ************************************************************************************************************************************
Monday 18 May 2020  11:21:43 -0400 (0:00:00.038)       0:00:00.092 ************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'undefined' is undefined\n\nThe error appears to be in '/home/netadmin/tmp/dev_vlan_ci/lab.yml': line 15, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: this task should fail due to variable not defined\n          ^ here\n"}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Monday 18 May 2020  11:21:43 -0400 (0:00:00.136)       0:00:00.229 ************
===============================================================================
this task should fail due to variable not defined ------------------------------------------------------------------------------------------------------------------------------------ 0.14s
this task should fail due to variable not defined ------------------------------------------------------------------------------------------------------------------------------------ 0.04s

```

##### EXPECTED RESULTS

when no tags are defined. error triggers rescue however when tags are defined rescue is not triggered. 

##### ACTUAL RESULTS

```paste below
$ ansible-playbook lab.yml --tags foo,bar -vvv
ansible-playbook 2.9.2
  config file = /home/netadmin/tmp/dev_vlan_ci/ansible.cfg
  configured module search path = ['/home/netadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/netadmin/.local/lib/python3.6/site-packages/ansible
  executable location = /home/netadmin/.local/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 20 2019, 17:12:48) [GCC 8.3.0]
Using /home/netadmin/tmp/dev_vlan_ci/ansible.cfg as config file
host_list declined parsing /home/netadmin/tmp/dev_vlan_ci/artifacts/host.vars.yml as it did not pass its verify_file() method
script declined parsing /home/netadmin/tmp/dev_vlan_ci/artifacts/host.vars.yml as it did not pass its verify_file() method
Skipping empty key (children) in group (ESX)
Parsed /home/netadmin/tmp/dev_vlan_ci/artifacts/host.vars.yml inventory source with yaml plugin

PLAYBOOK: lab.yml ***************************************************************************************************************************************************************************
1 plays in lab.yml

PLAY [labbing roles] ************************************************************************************************************************************************************************
META: ran handlers

TASK [this task should fail due to variable not defined] ************************************************************************************************************************************
task path: /home/netadmin/tmp/dev_vlan_ci/lab.yml:9
Monday 18 May 2020  11:26:24 -0400 (0:00:00.055)       0:00:00.055 ************
ok: [localhost] => {
    "msg": "This should print tagged - FOO"
}

TASK [this task should fail due to variable not defined] ************************************************************************************************************************************
task path: /home/netadmin/tmp/dev_vlan_ci/lab.yml:15
Monday 18 May 2020  11:26:24 -0400 (0:00:00.037)       0:00:00.093 ************
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'undefined' is undefined\n\nThe error appears to be in '/home/netadmin/tmp/dev_vlan_ci/lab.yml': line 15, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: this task should fail due to variable not defined\n          ^ here\n"
}

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Monday 18 May 2020  11:26:24 -0400 (0:00:00.143)       0:00:00.237 ************
===============================================================================
this task should fail due to variable not defined ------------------------------------------------------------------------------------------------------------------------------------ 0.14s
/home/netadmin/tmp/dev_vlan_ci/lab.yml:15 --------------------------------------------------------------------------------------------------------------------------------------------------
this task should fail due to variable not defined ------------------------------------------------------------------------------------------------------------------------------------ 0.04s
/home/netadmin/tmp/dev_vlan_ci/lab.yml:9 ---------------------------------------------------------------------------------------------------------------------------------------------------

```
