### ISSUE TITLE
Allow "vars_files" with "include_tasks"

### ISSUE THREAD

**Issue by darkdragon-001** [ansible/ansible#69598]
##### SUMMARY
I would like to use `include_tasks` module together with `vars_files`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_tasks

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION
_empty_

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE
This should run `task.yml` with the item specific configuration. `vars` works, so `vars_files` should be not be a problem to implement.

```yaml
- hosts:
  - localhost
  gather_facts: no
  tasks:
  - include_tasks: "task.yml"
    vars:
      ID: "prefix_{{ item }}"
    vars_files:
    - "{{ ID }}.yml"
    with_items:
    - a
    - b
```

##### EXPECTED RESULTS
It should run `task.yml` with variables in `a.yml` and `b.yml`.

##### ACTUAL RESULTS

    ERROR! conflicting action statements: include_tasks, var_files
