### ISSUE TITLE
[patch] Grsecurity/gradm support

### ISSUE THREAD

**Issue by sbocahu** [ansible/ansible#696]
I added support of authentication against a Grsecurity role (RBAC) in the paramiko transport.
Are you interested in merging it or is it too specific ?

You can find a patch against the devel branch here: https://gist.github.com/3181663

cheers

**Comment by mpdehaan** [comment]
It feels a little too specific to me to get command line options, especially if it only serves paramiko, but I'd be open to it just listening for environment variables,  I think.   We should have a proper configuration file soon.   I am also curious as to whether it should also affect the SSH transport and if you are going to work on that.

This is actually the first I've heard of gradm, could you bring this up on the mailing list?

**Comment by mpdehaan** [comment]
closing for now, you can resubmit when it just works through env vars and does not change the Ansible/Runner API.

thanks!

**Comment by goozbach** [comment]
has any further work been done on GrSec? (I'm not finding anything in issues/mailing list)

**Comment by sbocahu** [comment]
Not that I heard of. It seems I was the only one interested in GrSec support at the time and I had no time to work on it. Nowadays, I don't work in a GrSec environment anymore.

**Comment by Doooooo0o** [comment]
There is a workaround about this. Since you need only to disable the RBAC policies temporarly, you can modify the ansible variable [remote-tmp](http://docs.ansible.com/intro_configuration.html#remote-tmp) to /tmp or wherever you have the permission to write. 
Then, you can establish your connection (imo, there might be some problems about gathering facts, but it's not perfect since it's a workaround) to the remote server. From this, you can temporarly disable RBAC with :

```
- name: Disabling RBAC
  tags:
    - grsec
  shell: echo MyVeRySeCuRePaSs | gradm -D
- name: Testing RBAC (error is normal)
  tags:
    - grsec
  shell: gradm -S
  ignore_errors: yes
- name: Enabling RBAC
  tags:
    - grsec
  shell: gradm -E
```
