### ISSUE TITLE
not able to take single table dump from postgresql using ansible

### ISSUE THREAD

**Issue by SHUFIL** [ansible/ansible#69616]
##### SUMMARY

I have used postgresql_db module, but its taken full schema backup, target_opts I mention both schema and table, but again its taken full schema with all table, or we need to use a different module?
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_db module
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/ubuntu/Ansible/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = postgres

```

##### OS / ENVIRONMENT

ubuntu 16.04

##### STEPS TO REPRODUCE

not able to take single table backup from schema, its taken only full schema.

```yaml
- name: Dump a single table for an existing database schema
  postgresql_db:
    name: acme
    state: dump
    target: /tmp/acme.sql
    target_opts: "-n test-table.test-schema"
```

##### EXPECTED RESULTS

i want to take single or selective muliple table dump from schema

##### ACTUAL RESULTS

its taken dump file , but that is full schema , i want only single table from schema, i used target_opts: "-n test-table.test-schema" , but still its taken full schema backup.

```paste below

```
