### ISSUE TITLE
support slack block kits

### ISSUE THREAD

**Issue by fawaf** [ansible/ansible#69610]
##### SUMMARY

support slack block kits, similar to the `attachments` parameter of the slack module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

slack notifications module

##### ADDITIONAL INFORMATION

slack considers attachments a legacy functionality: https://api.slack.com/messaging/composing/layouts#when-to-use-attachments. they recommend using block kits.

```yaml
- name: Send notification message via Slack all options
  slack:
    token: thetoken/generatedby/slack
    msg: '{{ inventory_hostname }} completed'
    ...snip...
    blocks: [
     {
       type: "section",
       text: {
         ...snip...
       }
     }
   ]
```

more details here: https://api.slack.com/block-kit
