### ISSUE TITLE
Could not import the pyhelm python module. Please install `pyhelm` package.

### ISSUE THREAD

**Issue by ShubhamGundawarIBM** [ansible/ansible#69611]
##### SUMMARY

I am trying to install a helm chart through ansible, but I am getting pyhelm python module could not import, even after pip installing pyhelm. I can do import pyhelm through python.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Helm module for Ansible

##### ANSIBLE VERSION

```paste below
ansible 2.9.6

```

##### CONFIGURATION

```paste below
No Output
```

##### OS / ENVIRONMENT

RHEL 

##### STEPS TO REPRODUCE

```yaml
- name: Install helm chart
  helm:
    chart:
      name: test
      version: 0.0.0
      source:
        location: /home/k8s-helm
    state: present
    name: test
    namespace: default
```

##### EXPECTED RESULTS

The helm chart should be installed

##### ACTUAL RESULTS

{"changed": false, "msg": "Could not import the pyhelm python module. Please install `pyhelm` package."}

```paste below

```
