### ISSUE TITLE
Unarchive could allow me to create a new directory

### ISSUE THREAD

**Issue by wkoszek** [ansible/ansible#69633]
##### SUMMARY
It would be very nice if I could just say: unarchive URL to my machine to directory X, and have the `unarchive` plugin create the output directory for me.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Unarchive module

##### ADDITIONAL INFORMATION

I always have 2-3 ZIPs with the most up-to-date tools I need, and I kinda want to do:
- for each ZIP
- unpack it to dirs A, B and C

And I don't want to worry about directories, or adding a new block with a directory creation. Right now from what I see `unarchive` doesn't allow me to make a target directory. It'd be nice to add this feature. Could be a nice task for a junior Ansible hacker.

```yaml

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/unarchive.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/unarchive.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ainiml** [comment]
+1

You currently have to run two commands to use unarchive module. This should be able to be done in one command

The `creates` function should be updated to be a boolean to "create" the destination directory 

```
unarchive:
  src: https://extensions.gnome.org/download-extension/no-title-bar%40franglais125.gmail.com.shell-extension.zip?version_tag=7334
  dest: "{{ ext }}/no-title-bar"
  creates: yes
  remote_src: yes
```

or to be more explicit, leaving the current `creates` alone:

```
unarchive:
  src: https://extensions.gnome.org/download-extension/no-title-bar%40franglais125.gmail.com.shell-extension.zip?version_tag=7334
  dest: "{{ ext }}/no-title-bar"
  create_dir: yes
  remote_src: yes
```
