### ISSUE TITLE
get_url failed to download aws cli version2

### ISSUE THREAD

**Issue by vickey123** [ansible/ansible#69643]
##### SUMMARY
```
 get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2test.zip
        mode: 0700
        timeout: 120
        use_proxy: no
        force: no
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url
##### ANSIBLE VERSION
```
Ansible 2.9
```

##### ACTUAL RESULTS
```
{
    "_ansible_no_log": false,
    "dest": "/root/aws_tmp_version2/awscliv2.zip",
    "changed": false,
    "elapsed": 211,
    "url": "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip",
    "invocation": {
        "module_args": {
            "directory_mode": null,
            "force": false,
            "backup": null,
            "remote_src": null,
            "owner": null,
            "follow": false,
            "client_key": null,
            "group": null,
            "use_proxy": false,
            "unsafe_writes": null,
            "setype": null,
            "content": null,
            "serole": null,
            "client_cert": null,
            "url_username": null,
            "src": null,
            "dest": "/root/aws_tmp_version2/awscliv2.zip",
            "selevel": null,
            "force_basic_auth": false,
            "sha256sum": "",
            "http_agent": "ansible-httpget",
            "regexp": null,
            "url_password": null,
            "url": "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip",
            "checksum": "",
            "seuser": null,
            "headers": null,
            "delimiter": null,
            "mode": 448,
            "timeout": 60,
            "attributes": null,
            "validate_certs": true,
            "tmp_dest": null
        }
    },
    "msg": "Request failed: <urlopen error timed out>"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/get_url.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I cannot replicate this behavior, downloading that file via `get_url` works as expected.  This sounds like an issue in your environment, or a transient network issue that is causing this failure for you.

**Comment by sahotay** [comment]
As @sivel mentioned i also can't reproduce your issue @vickey123. By your error `"Request failed: <urlopen error timed out>"` it looks like some firewall issues?

Here is a test which worked with Ansible v2.9
```
ansible 2.9.0
  config file = None
  configured module search path = ['/Users/sahotay/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Dec 13 2019, 19:58:14) [Clang 11.0.0 (clang-1100.0.33.17)]
```
Ansible `Playbook`
```
---
- name: test aws cli v2
  hosts: localhost
  tasks:
    - name: get aws cli v2
      get_url:
          url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
          dest: /tmp/awscliv2test.zip
          mode: 0700
          timeout: 120
          use_proxy: no
          validate_certs: false
          force: no
```

Result:
```
$ ansible-playbook aws_v2_cli.yml
[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [test aws cli v2] ***************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************
ok: [localhost]

TASK [get aws cli v2] ****************************************************************************************************************
changed: [localhost]

PLAY RECAP **********************************************************************************************************
```
