### ISSUE TITLE
get_url module always raise out "HTTP Error 401: basic auth failed

### ISSUE THREAD

**Issue by itsgodzilla** [ansible/ansible#69641]
### get_url module always raise out "HTTP Error 401: basic auth failed

Here is my playbook which used get_url module, when I ran it , it caused 401 error.
( just like the other guy said. Here is his issue: 
https://groups.google.com/forum/#!topic/ansible-project/AtP7ifLzdjk
.)
```
- name: wget rpm 
  get_url:
    url: "http://nginxsrv-file.local/repo/{{ item.src }}"
    dest: "{{ item.dest }}"
    username: 'nginx_sec'
    password: 'A?C$XV/1UhA~vQp%'
  with_items:
    - { src: "jdk.rpm", dest: "/tmp/" }

It raised error:

{...
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp/",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "password": "A?C$XV/1UhA~vQp%",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "http://nginxsrv-file.local/repo/jdk.rpm",
            "url_password": "A?C$XV/1UhA~vQp%",
            "url_username": "nginx_sec",
            "use_proxy": true,
            "username": "nginx_sec",
            "validate_certs": true
        }
    },
    "item": {
        "dest": "/tmp/",
        "src": "jdk.rpm"
    },
    "mode": "01777",
    "msg": "Request failed",
    "owner": "root",
    "response": "HTTP Error 401: basic auth failed",
    "size": 4096,
    "state": "directory",
    "status_code": 401,
    "uid": 0,
    "url": "http://nginxsrv-file.local/repo/jdk.rpm"
}
```

Is anybody can give some help?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible get_url urllib urllib_request url_username url_password http 401

##### ANSIBLE VERSION

```paste below
And my env:
\# ansible --version
ansible 2.9.7
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Linux A04-R08-I195-3-7T2FT92.JCLOUD.COM 3.10.0-327.36.4.el7.x86_64 #1 SMP Sun Jan 7 13:32:06 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
- name: wget rpm 
  get_url:
    url: "http://nginxsrv-file.local/repo/{{ item.src }}"
    dest: "{{ item.dest }}"
    username: 'nginx_sec'
    password: 'A?C$XV/1UhA~vQp%'
  with_items:
    - { src: "jdk.rpm", dest: "/tmp/" }
```

##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
You may need to use `force_basic_auth`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by itsgodzilla** [comment]
Thank you anyway. I have went to read the mailing list, and there also had a guy talking about the same issue and it still not be solved. Pity!  (By searching keywords "get_url 401", you can find it.)
Hers is my test result below, and it works:
```
- name: wget rpm 
  get_url:
    url: "http://nginxsrv-file.local/repo/{{ item.src }}"
    dest: "{{ item.dest }}"
    username: 'nginx_sec'
    password: 'A?CXV/1UhA~vQp$%'    # No numbers or letters are allowd behind '$' .
  with_items:
    - { src: "jdk.rpm", dest: "/tmp/" }
```

1. special charactors are allowed anywhere: '?~/%'.
2. special charactor is allowed only at the special place: '$'. 
Means you can't put any numbers or English letters behind '$', but the other special charactors could.`

### Hope this will help someone else.
