### ISSUE TITLE
Unable to Assign fixed IP address to Openstack Instance using os_server

### ISSUE THREAD

**Issue by ajaybhatnagar** [ansible/ansible#69652]
##### SUMMARY

Unable to Assign fixed IP address to Openstack Instance using os_server
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os_server

##### ANSIBLE VERSION

```paste below
ansible 2.9.9

openstack  client version 5.2.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04 :  4.15.0-91-generic

##### STEPS TO REPRODUCE

```yaml
cluster.yml
---
- hosts: localhost
  tasks:
  - include_vars: settings.yml
  - name: launch openstack instances
    os_server:
      state: present
      auth:
        auth_url: "{{ os_cloud_profile.os_auth_url }}"
        username: "{{ os_cloud_profile.os_username }}"
        password: "{{ os_cloud_profile.os_password }}"
        project_name: "{{ os_cloud_profile.os_tenant_name }}"
      name: "{{ item.0 }}"
      region_name: "{{ os_cloud_profile.os_region |default('') }}"
      availability_zone: "{{ os_cloud_profile.os_availability_zone |default('') }}"
      image: "{{ os_cloud_profile.os_image_name }}"
      key_name: "{{ os_cloud_profile.os_key_name |default('') }}"
      flavor: "{{ os_cloud_profile.os_flavor_name }}"
      nics:
        - net-id: "{{ os_cloud_profile.os_network_id }},v4-fixed-ip={{ item.2 }}"
      security_groups: "{{ os_cloud_profile.os_security_groups |default('') }}"
    with_together:
      - "{{ nodes }}"
      - "{{ nodes_role }}"
      - "{{ nodes_ip }}"
    when: create_nodes
-----
settings,yml
---
#Define all program variables here
#Set to true for the instances to be created
create_nodes: true
nodes: ["esm03","esm04","esd02"]
nodes_role: ["master","master","data"]
nodes_ip: ["10.239.51.145","10.239.51.146","10.239.51.147"]
ansible_user: <ANSIBLE_USER_NAME>
#Openstack profile for launching instances
#Change the below value to match your deployment
os_cloud_profile:
  os_compute_api_version: "3.0"
  os_ssh_user: <USER_NAME>
  os_username: <USER_NAME>
  os_password: <PASSWORD>
  os_tenant_name: <TENANT NAME>
  os_project_name: <PROJECT NAME>
  os_region: regionOne
  os_availability_zone: nova
  os_security_groups:
    - "<SEC GRP>"
  os_network_name: <NETWORK_NAME>
  os_network_id: <NETWORK ID>
  os_key_name: <PUB KEY>
  os_flavor_name: h1.c8m8
  os_image_name: <IMAGE_NAME>
  os_auth_url: 'https://<AUTH_URL_IP>/v3'


```

##### EXPECTED RESULTS

Instance should get preassigned IP address as possible with openstack client execution but it picks up any available address with out any additional specs. when specifying v4-fixed-ip address it gives error

##### ACTUAL RESULTS

```paste below
It is not able to take parameters available in openstack instance creation with network_id and specified fixed IP address. Documentation says quote:
"A list of networks to which the instance's interface should be attached. Networks may be referenced by net-id/net-name/port-id or port-name.
Also this accepts a string containing a list of (net/port)-(id/name) Eg: nics: "net-id=uuid-1,port-name=myport" Only one of network or nics should be supplied."
End quote.

<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: local
<127.0.0.1> EXEC /bin/sh -c 'echo ~local && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/local/.ansible/tmp `"&& mkdir /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224 && echo ansible-tmp-1590085495.526485-4643-69995998945224="` echo /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224 `" ) && sleep 0'
Using module file /home/local/.local/lib/python3.6/site-packages/ansible/modules/cloud/openstack/os_server.py
<127.0.0.1> PUT /home/local/.ansible/tmp/ansible-local-4567jmek3do1/tmpvi5mh4wk TO /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224/AnsiballZ_os_server.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224/ /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224/AnsiballZ_os_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224/AnsiballZ_os_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/local/.ansible/tmp/ansible-tmp-1590085495.526485-4643-69995998945224/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_os_server_payload_vtgmap1n/ansible_os_server_payload.zip/ansible/modules/cloud/openstack/os_server.py", line 750, in main
  File "/tmp/ansible_os_server_payload_vtgmap1n/ansible_os_server_payload.zip/ansible/modules/cloud/openstack/os_server.py", line 544, in _create_server
  File "<decorator-gen-4>", line 2, in create_server
  File "/usr/local/lib/python3.6/dist-packages/openstack/cloud/_utils.py", line 378, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/openstack/cloud/_compute.py", line 935, in create_server
    microversion=microversion))
  File "/usr/local/lib/python3.6/dist-packages/openstack/proxy.py", line 543, in _json_response
    exceptions.raise_from_response(response, error_message=error_message)
  File "/usr/local/lib/python3.6/dist-packages/openstack/exceptions.py", line 236, in raise_from_response
    http_status=http_status, request_id=request_id
failed: [localhost] (item=['esm03', 'master', '10.239.51.145']) => {
    "ansible_loop_var": "item",
    "changed": false,
    "extra_data": null,
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": {
                "auth_url": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "project_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "auth_type": null,
            "auto_ip": true,
            "availability_zone": "nova",
            "boot_from_volume": false,
            "boot_volume": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "config_drive": false,
            "delete_fip": false,
            "flavor": "h1.c8m8",
            "flavor_include": null,
            "flavor_ram": null,
            "floating_ip_pools": null,
            "floating_ips": null,
            "image": "image_762_v1a",
            "image_exclude": "(deprecated)",
            "interface": "public",
            "key_name": "pubkey20",
            "meta": {},
            "name": "esm03",
            "network": null,
            "nics": [
                {}
            ],
            "region_name": "regionOne",
            "reuse_ips": true,
            "scheduler_hints": null,
            "security_groups": [
                "default"
            ],
            "state": "present",
            "terminate_volume": false,
            "timeout": 180,
            "userdata": null,
            "validate_certs": null,
            "volume_size": false,
            "volumes": [],
            "wait": true
        }
    },
    "item": [
        "esm03",
        "master",
        "10.239.51.145"
    ],
    "msg": "BadRequestException: 400: Client Error for url: https://10.231.101.250:13774/v2.1/servers, Bad networks format: network uuid is not in proper format (4d43b98d-b848-4b05-8e05-d3f58f70390d,v4-fixed-ip=10.239.51.145)"
}

```
