### ISSUE TITLE
Strategy Plugin support custom options

### ISSUE THREAD

**Issue by kevin-j-smith** [ansible/ansible#69668]
##### SUMMARY

While developing a generic strategy for cross team consumption with my organization we determined that our teams custom strategy would benefit from configuration options.  Similar to how other plugin types use documentation to define custom options.

An example document section:
```
DOCUMENTATION = '''
    strategy: whole-environment-task-orchestration
    short_description: Specializes in task orchestration particularly when clusters are not defined by inventory but by ansible local facts.
    description:
        - Dynamic Strategy based on host facts
    version_added: "2.0"
    notes:
     - My Custom Strategy implementation
    author: kevin-j-smith
    options:
        cluster_name_fact:
            description:
                - Fact used to define strategy's clustering
            env:
                - name: CLUSTER_NAME_FACT
            ini:
                - section: whole-environment-task-orchestration
                  key: cluster_name_fact
            required: True
'''

```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible.plugins.strategy custom plugins could also benefit from customization options as do many of the other plugin types.   

##### ADDITIONAL INFORMATION

This feature would be used to allow custom strategy plugins the ability to have custom configuration through Ansible configuration options matching the pattern already defined by other plugins.  It would solve the ability to dynamically change the behavior of my custom strategy through means similar to other plugins.

```yaml
#ansible.cfg
[defaults]
strategy_plugins = /etc/ansible/plugins/strategy/whole-environment-task-orchestration-strategy
strategy = whole-environment-task-orchestration

[whole-environment-task-orchestration]
cluster_name_fact='my_special_task/cluster_name'
```

```json
# inventory host specialized task that needs orchestration /etc/ansible/facts.d/my_special_task
{
  "cluster_name": "product_master_group"
}
```

```yaml
#~/playbook.yaml
---
- name: run_special_task_on_all_hosts_in_environment
  hosts: all
  tasks:
    - name: simple
       debug: msg="strategy handled me by placing me in a group with others determined by my cluster_name"
```
