### ISSUE TITLE
win_chocolatey ... pinned: yes hangs

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#69663]
##### SUMMARY
Trying to pin a package using name and version and the process hangs

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```paste below

```

##### CONFIGURATION

```paste below
$ ansible --version
ansible 2.9.9.post0
  config file = None
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible
  executable location = /Users/tanner/projects/py3-ansible/src/ansible/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### OS / ENVIRONMENT
Ansible management host
  * ProductName:	Mac OS X
  * ProductVersion:	10.14.6
  * BuildVersion:	18G4032

Manage host
  * Windows 10 Professional
  
##### STEPS TO REPRODUCE

```yaml
- name: pin packages
  win_chocolatey:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    pinned: yes
  when:
    - chocolatey_packages_pinned is defined
  ignore_errors: yes
  loop: "{{ chocolatey_packages_pinned|flatten(levels=1) }}"
```
##### EXPECTED RESULTS
Packages listed int the chocolatey_package_pinned list are pinned by chocolatey

##### ACTUAL RESULTS
Process just hangs

`ansible-playbook -i test ../chocolatey.yml -vvvv`
```paste below
TASK [win_chocolatey : debug] **************************************************
task path: /Users/tanner/projects/py3-ansible/src/playbooks.git/roles/win_chocolatey/tasks/main.yml:34
ok: [PC106.xxx.test] => {
    "msg": [
        {
            "name": "draftsight",
            "version": "2019.03.0.20190120"
        }
    ]
}

TASK [win_chocolatey : pin packages] *******************************************
task path: /Users/tanner/projects/py3-ansible/src/playbooks.git/roles/win_chocolatey/tasks/main.yml:46
Using module file /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible/modules/windows/win_chocolatey.ps1
Pipelining is enabled.
<PC106.xxx.test> ESTABLISH WINRM CONNECTION FOR USER: Administrator@xxx.test on PORT 5986 TO PC106.xxx.test
EXEC (via pipeline wrapper)
```
