### ISSUE TITLE
YUM Module issue

### ISSUE THREAD

**Issue by nagaraju99narisetti** [ansible/ansible#69664]
##### SUMMARY

```
 FAILED! => {"changed": false, "failed": true, "msg": "python2 bindings for rpm are needed for this module. python2 yum module is needed for this  module"}
```

Issue Type:
Bug

COMPONENT NAME
yum

Ansible Verison
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nnarisetti/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, May 22 2015, 08:34:51) [GCC 4.4.7 20120313 (Red Hat 4.4.7-15)]
```

I am getting above error while I execute the below playbook.

```yaml
---

- hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: "Install a list of packages"
    yum:
     name:
        - gawk
        - java
        - curl
        - expect
        - perl
        - openssh-clients-7.4p1-16.el7.x86_64
     state: present

```

Result:
```
 ansible-playbook symlink.yml -i host -u nnarisetti -k -K --check
SSH password:
SUDO password[defaults to SSH password]:

PLAY [all] ********************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: []

TASK [Install a list of packages] *********************************************************************************************
fatal: []: FAILED! => {"changed": false, "failed": true, "msg": "python2 bindings for rpm are needed for this module. python2 yum module is needed for this  module"}
        to retry, use: --limit @/home/nnarisetti/symlink/symlink.retry

PLAY RECAP ********************************************************************************************************************
 : ok=1    changed=0    unreachable=0    failed=1

```
