### ISSUE TITLE
Long variable in multi line not being parsed correctly

### ISSUE THREAD

**Issue by screwyy** [ansible/ansible#69676]
##### SUMMARY
When trying to limit the number of characters to 80 some variables need to be formatted YAML multi line. Even if I try with `|` or `>` or `>-` or `|-` the output is not correct. I'm trying to create a value for a variable that is made out of another var + multiple filters and I want it to fit into line-length of 80. Please don't offer `line-length: disable` or `skip-ansible-lint` since both are not solutions.
```
value: "{{ list_servers_to_silence | map('regex_replace', '^([a-z]{13})([0-9]{2})$', '\\1.*|') | list | unique | join() | regex_replace('\\|$', '') }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

variable
##### ANSIBLE VERSION

```paste below
2.7.18, 2.8.12, 2.9.9
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/ansible/qgzq5002/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ansible/qgzq5002/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/home/ansible/qgzq5002/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
CACHE_PLUGIN(/home/ansible/qgzq5002/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/a
DEFAULT_CALLBACK_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages
DEFAULT_EXECUTABLE(/home/ansible/qgzq5002/ansible.cfg) = /bin/bash
DEFAULT_FILTER_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/a
DEFAULT_FORKS(/home/ansible/qgzq5002/ansible.cfg) = 5
DEFAULT_GATHERING(/home/ansible/qgzq5002/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/home/ansible/qgzq5002/ansible.cfg) = ['/home/ansible/qgzq5002/ansible-inventories/test/i
DEFAULT_LOCAL_TMP(/home/ansible/qgzq5002/ansible.cfg) = /home/ansible/.ansible/tmp/ansible-local-7491uo_z_p
DEFAULT_LOG_PATH(/home/ansible/qgzq5002/ansible.cfg) = /var/log/ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/a
DEFAULT_MANAGED_STR(/home/ansible/qgzq5002/ansible.cfg) = Ansible managed: {file} on {host}
DEFAULT_MODULE_LANG(/home/ansible/qgzq5002/ansible.cfg) = C
DEFAULT_MODULE_SET_LOCALE(/home/ansible/qgzq5002/ansible.cfg) = True
DEFAULT_POLL_INTERVAL(/home/ansible/qgzq5002/ansible.cfg) = 15
DEFAULT_PRIVATE_KEY_FILE(/home/ansible/qgzq5002/ansible.cfg) = /home/ansible/.ssh/id_ed25519
DEFAULT_REMOTE_PORT(/home/ansible/qgzq5002/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/home/ansible/qgzq5002/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/home/ansible/qgzq5002/roles']
DEFAULT_SQUASH_ACTIONS(/home/ansible/qgzq5002/ansible.cfg) = ['apk', 'apt', 'dnf', 'package', 'pacman', 'pk
DEFAULT_STRATEGY_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages
DEFAULT_SUDO_EXE(/home/ansible/qgzq5002/ansible.cfg) = sudo
DEFAULT_SUDO_FLAGS(/home/ansible/qgzq5002/ansible.cfg) = -E
DEFAULT_SUDO_USER(/home/ansible/qgzq5002/ansible.cfg) = root
DEFAULT_TEST_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ans
DEFAULT_TIMEOUT(/home/ansible/qgzq5002/ansible.cfg) = 30
DEFAULT_TRANSPORT(/home/ansible/qgzq5002/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/home/ansible/qgzq5002/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ans
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible/qgzq5002/ansible.cfg) = /home/ansible/.vault.txt
DEPRECATION_WARNINGS(/home/ansible/qgzq5002/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/ansible/qgzq5002/ansible.cfg) = True
HOST_KEY_CHECKING(/home/ansible/qgzq5002/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ansible/qgzq5002/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7.4

##### STEPS TO REPRODUCE

```yaml
- hosts: prometheus[0]
  vars:
    list_servers_to_silence:
      - "cdgiglltruans01"
      - "cdhigiitruans02"
    value: >-
      "{{ list_servers_to_silence | map('regex_replace', '^([a-z]{13})([0-9]{2})$', '\\1.*|') | list
      | unique | join() | regex_replace('\\|$', '') }}"
  tasks:
    - debug:
        msg: "{{ value }}"
```
Or
```yaml
- hosts: prometheus[0]
  vars:
    list_servers_to_silence:
      - "cdgiglltruans01"
      - "cdhigiitruans02"
    value: >-
      "{{ list_servers_to_silence | map('regex_replace', '^([a-z]{13})([0-9]{2})$', '\\1.*|') | list | unique |
       join() | regex_replace('\\|$', '') }}"
  tasks:
    - debug:
        msg: "{{ value }}"
```
Nothing works

##### EXPECTED RESULTS

I expect this output: `"cdgiglltruans.*|cdhigiitruans.*"`
```paste below
(nsi) ansible@tsmlmfetlsans01 ~/qgzq5002$ ansible-playbook cucu.yml

PLAY [prometheus[0]] **************************************************************************************

TASK [Gathering Facts] ************************************************************************************
ok: [tsmlmfetrupro01]

TASK [debug] **********************************************************************************************
ok: [tsmlmfetrupro01] => {
    "msg": "cdgiglltruans.*|cdhigiitruans.*"
}

PLAY RECAP ************************************************************************************************
tsmlmfetrupro01            : ok=2    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

I get this output: `"\"1.*|\""`

```paste below
(nsi) ansible@tsmlmfetlsans01 ~/qgzq5002$ ansible-playbook cucu.yml

PLAY [prometheus[0]] **************************************************************************************

TASK [Gathering Facts] ************************************************************************************
ok: [tsmlmfetrupro01]

TASK [debug] **********************************************************************************************
ok: [tsmlmfetrupro01] => {
    "msg": "\"1.*|\""
}

PLAY RECAP ************************************************************************************************
tsmlmfetrupro01            : ok=2    changed=0    unreachable=0    failed=0
```
