### ISSUE TITLE
[UFW module] ERROR: problem running sysctl

### ISSUE THREAD

**Issue by trollqaa** [ansible/ansible#69684]
##### SUMMARY
When I try to set state: enabled I get 'ERROR: problem running sysctl', any further manipulations with the firewall end with the same message

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ufw module

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /home/troll/.ansible.cfg
  configured module search path = ['/home/troll/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/home/troll/.ansible.cfg) = -o UserKnownHostsFile=/dev/null
HOST_KEY_CHECKING(/home/troll/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/troll/.ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT
OS host: Ubuntu 20.04
OS remote server: Debian 10 (buster)

##### STEPS TO REPRODUCE
Tasks for reproduce
```
- name: install UFW package
  apt:
    name: ufw

- name: block incoming
  ufw:
    default: deny
    direction: incoming

- name: allow outgoing
  ufw:
    default: allow
    direction: outgoing


- name: allow ssh
  ufw:
    rule: allow
    from_ip: '{{ item }}'
    port: '22'
    proto: 'tcp'
  with_items:
    - '1.1.1.1'
    - '2.2.2.2'

- name: enable ufw
  ufw:
    state: enabled
```

##### EXPECTED RESULTS
I expect successful execution of tasks (in advance, the connection is from an allowed address)

##### ACTUAL RESULTS
first run (state: enabled error):
```
fatal: [upd-node1]: FAILED! => {
    "changed": false,
    "commands": [
        "/sbin/ufw status verbose",
        "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules",
        "/sbin/ufw -f enable",
        "/sbin/ufw status verbose"
    ],
    "invocation": {
        "module_args": {
            "comment": null,
            "default": null,
            "delete": false,
            "direction": null,
            "from_ip": "any",
            "from_port": null,
            "insert": null,
            "insert_relative_to": "zero",
            "interface": null,
            "log": false,
            "logging": null,
            "name": null,
            "proto": null,
            "route": false,
            "rule": null,
            "state": "enabled",
            "to_ip": "any",
            "to_port": null
        }
    },
    "msg": "ERROR: problem running sysctl\n"
}
```
try again run tasks:
```
fatal: [upd-node3]: FAILED! => {
    "changed": false,
    "commands": [
        "/sbin/ufw status verbose"
    ],
    "invocation": {
        "module_args": {
            "comment": null,
            "default": "deny",
            "delete": false,
            "direction": "incoming",
            "from_ip": "any",
            "from_port": null,
            "insert": null,
            "insert_relative_to": "zero",
            "interface": null,
            "log": false,
            "logging": null,
            "name": null,
            "proto": null,
            "route": false,
            "rule": null,
            "state": null,
            "to_ip": "any",
            "to_port": null
        }
    },
    "msg": "ERROR: problem running sysctl\n"
}
```
