### ISSUE TITLE
Add this interesting example to setup module documentation

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#6968]
http://docs.ansible.com/setup_module.html

Direct call to setup module can be used to reload facts after adding custom fact:

```
- name: create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d
- name: install custom impi fact
  copy: src=ipmi.fact dest=/etc/ansible/facts.d
- name: re-read facts after adding custom fact
  setup: filter=ansible_local
```

This is very useful  technique, because without it variables from created local fact can't be used in first run.

**Comment by mpdehaan** [comment]
Thanks, I'm adding something about this now.   Will show up soon!

**Comment by selivan** [comment]
Better variant:

```
tasks:
- name: create directory for ansible custom facts
  file: state=directory recurse=yes path=/etc/ansible/facts.d
- name: install custom impi fact
  copy: src=ipmi.fact dest=/etc/ansible/facts.d
  notify:
    - re-read facts
handlers:
- name: re-read facts
  setup: filter=ansible_local
```

First one always slow down palybook execution, even if local fact is already created.
