### ISSUE TITLE
no_log not working in postgresql_user module

### ISSUE THREAD

**Issue by faruqisan** [ansible/ansible#69700]
##### SUMMARY

I set `no_log` true when using `postgresql_user` module, but it still printing the password in the log.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `postgresql_user`

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/faruqisan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/faruqisan/.molecule-venv/lib/python3.6/site-packages/ansible
  executable location = /home/faruqisan/.molecule-venv/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

target OS : ubuntu versions 18.04

##### STEPS TO REPRODUCE

- Run below playbooks:

```yaml
- name: PostgreSQL | Create User
  postgresql_user:
    name: "{{item.name}}"
    password: "{{ item.password | default(omit) }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
  no_log: True
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_users}}"
  when:
    - create_user == true
    - postgresql_users|length > 0
```

##### EXPECTED RESULTS

Expect no password / no log printing when creating users.

##### ACTUAL RESULTS

password printed on log.

```paste below
    TASK [postgresql-basic-config : PostgreSQL | Create User] **********************
    changed: [pg-12] => (item={'name': 'admin', 'password': 'secret'})
    changed: [pg-12] => (item={'name': 'johndoe', 'password': 'secret'})
[WARNING]: Module did not set no_log for no_password_changes
```
