### ISSUE TITLE
Document example to loop add_host

### ISSUE THREAD

**Issue by SamyCoenen** [ansible/ansible#69707]
The `add_host` module notes that:
> This module bypasses the play host loop and only runs once for all the hosts in the play, if you need it to iterate use a with-loop construct.

There doesn't seem to be an example how this could be done.

Someone already found the solution though:

```yaml
  add_host:
    name: "{{ item }}"
  loop: "{{ hostvars | json_query('*.var') }}"
```

Full example

```yaml
---

- name: Generating hosts
  hosts: hypervisors
  gather_facts: no
  tasks:

    - name: Exclude skip_nodes
      shell:
        cmd: onevm list -l NAME,IP --csv | tail -n +2 | sed s/^/{{inventory_hostname}},/g
      changed_when: false
      register: onevm

    - add_host:
        name: "{{ name }}"
        groups: "{{hypervisor}}:vms"
        ansible_ssh_host: "{{ ip }}"
      vars:
        hypervisor: "{{ item.split(',')[0] }}"
        name: "{{ item.split(',')[1] }}"
        ip: "{{ item.split(',')[2] }}"
      with_items: "{{ hostvars | json_query('*.onevm.stdout_lines') | regex_replace('\"') }}"
      changed_when: false

- name: Executing tasks
  hosts: "*vms"
  gather_facts: no
  tasks:

    - debug: msg="whoa!"
```

_Originally posted by @kvaps in https://github.com/ansible/ansible/issues/6912#issuecomment-310501334_

##### COMPONENT NAME
add_host
