### ISSUE TITLE
awc_ec2 inventory plugin hostnames list precedence does not work

### ISSUE THREAD

**Issue by invizus** [ansible/ansible#69701]
##### SUMMARY
Using aws_ec2 inventory plugin. Defined several options for`hostnames`, but ansible will only use first in the list. Some hosts may be available only via public internet, and others only via VPN or via ssh proxy of publicly available servers.
Reason behind this: Ansible will generate inventory, and will group them by role or purpose, by owner etc. But I want my team to use it flexibly. i.e. we also define custom DNS names.
There will be playbooks for hosts like `*.internal`, `*.security.company.com`, or `monitoring` (as in group).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ec2 inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/user/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/ansible/ansible.cfg) = -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey,keyboard-interactive -o ControlMaster=auto -o ControlPersist=600s
CACHE_PLUGIN(/home/user/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/ansible/ansible.cfg) = cachedir
CACHE_PLUGIN_TIMEOUT(/home/user/ansible/ansible.cfg) = 86400
DEFAULT_ACTION_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/home/user/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/home/user/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/user/ansible/ansible.cfg) = [u'/home/user/ansible/inventory']
DEFAULT_LOG_PATH(/home/user/ansible/ansible.cfg) = /home/user/ansible/ansible_user.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/home/user/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG(/home/user/ansible/ansible.cfg) = C
DEFAULT_POLL_INTERVAL(/home/user/ansible/ansible.cfg) = 15
DEFAULT_TIMEOUT(/home/user/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/home/user/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/home/user/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
HOST_KEY_CHECKING(/home/user/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/user/ansible/ansible.cfg) = [u'aws_ec2', u'ini', u'yaml']
```

##### OS / ENVIRONMENT
My OS is Ubuntu 18.04
Working with AWS EC2 via API using AWS EC2 inventory plugin.
##### STEPS TO REPRODUCE
inventory:
```yaml
plugin: aws_ec2
boto_profile: myprofile
keyed_groups:
  - key: tags.Name
    separator: ""
    parent_group: user
  - key: tags.role
    separator: ""
    parent_group: role
cache: yes
cache_timeout: 300
hostnames:
  - dns-name
  - private-dns-name
  - private-ip-address
  - tag:Name
```
playbook:
```yaml
---
#- hosts: all
#- hosts: myrole
- hosts: "*.internal"
  tasks:
  - debug:
      msg: "{{ ansible_host }}"

  - name: touch file
    file:
      path: /tmp/test
      state: touch
```
Also, AWS API credentials in `~/.aws/credentials`

`ansible-playbook test-touch.yml`

##### EXPECTED RESULTS
ansible will use .internal DNS name, that is listed as second in `hostnames` list.
ansible will execute tasks for servers with .internal
i.e. this works when 
```yaml
hostnames:
  - private-dns-name
  - dns-name
```
```
TASK [debug] ************************************************************************************************************************************************************************************************
ok: [ip-10-5-0-41.us-west-1.compute.internal] => {
    "msg": "ip-10-5-0-41.us-west-1.compute.internal"
}
^C
```
##### ACTUAL RESULTS
```paste below
 [WARNING]: Could not match supplied host pattern, ignoring: *.internal


PLAY [*.internal] *******************************************************************************************************************************************************************************************
skipping: no hosts matched
```
