### ISSUE TITLE
Ansible 2.9.9 reports its version as "2.8.0".

### ISSUE THREAD

**Issue by Jim-Ivey** [ansible/ansible#69716]
##### SUMMARY
Ansible 2.9.9 responds to `ansible --version` with "2.8.0".

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jimivey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

```

##### CONFIGURATION
Nothing.  New installation.

```paste below

```

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

##### STEPS TO REPRODUCE
1.  Remove/purge all versions of Ansible.
2.  `sudo add-apt-repository ppa:ansible/ansible-2.9`
3.  To be sure I was getting Ansible from this repository, I pinned the PPA at a priority of 600.
4. `sudo aptitude install ansible`
5.  Be sure that version 2.9 is being installed: `aptitude` output includes `Preparing to unpack .../ansible_2.9.9-1ppa~bionic_all.deb ...` and `Unpacking ansible (2.9.9-1ppa~bionic) ...` and `Setting up ansible (2.9.9-1ppa~bionic) ...`
6.  Run `ansible --version`.  It reports `2.8.0`.
7. Compare `man ansible` in which the footer reports "Ansible 2.9.9"

```yaml
# A playbook to verify that we're using the proper version of ansible.

- hosts: all
  gather_facts: false
  pre_tasks:
    - set_fact:
        canonical_ansible_version_major: 2
        canonical_ansible_version_minor: 9

    - name: Verify Ansible version is {{ canonical_ansible_version_major }}.{{ canonical_ansible_version_minor }}.
      assert:
        that: ansible_version.major is version(canonical_ansible_version_major, '==')
              and ansible_version.minor is version(canonical_ansible_version_minor, '==')
        msg: >
          You must use Ansible version {{ canonical_ansible_version_major }}.{{ canonical_ansible_version_minor }}.
          Your version of Ansible is {{ ansible_version.full }}.

```

##### EXPECTED RESULTS
I expected `ansible --version` to yield "2.9.\?".

I expected the YAML above to recognize a valid version of ansible and continue.

##### ACTUAL RESULTS
`ansible --version` yielded "2.8.0".

The YAML above failed, reporting that the Ansible version is 2.8.0.

```paste below
$ ansible --version
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jimivey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]


$ /usr/bin/ansible-playbook -i localhost includes/verify-ansible.yml -vv -K
ansible-playbook 2.8.0
  config file = /home/jimivey/everlaw/servers/ansible/ansible.cfg
  configured module search path = [u'/home/jimivey/everlaw/servers/ansible/modules', u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /home/.../ansible/ansible.cfg as config file
BECOME password: 
Vault password: 
 ______________________________
< PLAYBOOK: verify-ansible.yml >
 ------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

1 plays in includes/verify-ansible.yml
 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _________________
< TASK [set_fact] >
 -----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/.../ansible/includes/verify-ansible.yml:6
ok: [localhost] => changed=false 
  ansible_facts:
    canonical_ansible_version_major: 2
    canonical_ansible_version_minor: 9
 _______________________________________
< TASK [Verify Ansible version is 2.9.] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/.../ansible/includes/verify-ansible.yml:10
fatal: [localhost]: FAILED! => changed=false 
  assertion: ansible_version.major is version(canonical_ansible_version_major, '==') and ansible_version.minor is version(canonical_ansible_version_minor, '==')
  evaluated_to: false
  msg: |-
    You must use Ansible version 2.9. Your version of Ansible is 2.8.0.
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```
