### ISSUE TITLE
netbox_interface module

### ISSUE THREAD

**Issue by piotrsmerda** [ansible/ansible#69724]
##### SUMMARY
Required parameter is not specified in docs:
after running simple playbook like listed below you'll get error message:

Fatal: [localhost]: FAILED! => {"changed": false, "msg": {"type": ["This field is required."]}}

##### ISSUE TYPE
Missing required "type" field from documentation

##### COMPONENT NAME
netbox_interface

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION
no changes to default config

##### OS / ENVIRONMENT
RHEL8.1, Centos 7.8

##### STEPS TO REPRODUCE
```
- name: "Add NetBox Interface"
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
      - name: Add one device
        netbox_interface:
            netbox_url: "http://1.2.3.4:5678"
            netbox_token: 1234567890098765432
            data:
                device: server101
                name: port-channel1
                form_factor: Link Aggregation Group (LAG)
                mtu: 1600
                mgmt_only: false
                mode: Access
            state: present

```

##### EXPECTED RESULTS
Interface should appear in Netbox host entry

##### ACTUAL RESULTS
```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~user && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573 && echo ansible-tmp-1590572042.74-11688-102609608710573="` echo /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/netbox/netbox_interface.py
<localhost> PUT /home/user/.ansible/tmp/ansible-local-116753O7JVM/tmpVQd9kF TO /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573/AnsiballZ_netbox_interface.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573/ /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573/AnsiballZ_netbox_interface.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573/AnsiballZ_netbox_interface.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1590572042.74-11688-102609608710573/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_netbox_interface_payload_0rdqn4w0/ansible_netbox_interface_payload.zip/ansible/modules/net_tools/netbox/netbox_interface.py", line 272, in main
  File "/tmp/ansible_netbox_interface_payload_0rdqn4w0/ansible_netbox_interface_payload.zip/ansible/modules/net_tools/netbox/netbox_interface.py", line 311, in ensure_interface_present
  File "/tmp/ansible_netbox_interface_payload_0rdqn4w0/ansible_netbox_interface_payload.zip/ansible/module_utils/net_tools/netbox/netbox_utils.py", line 200, in create_netbox_object
    nb_obj = nb_endpoint.create(data)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 287, in create
    ).post(args[0] if args else kwargs)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 381, in post
    return self._make_call(verb="post", data=data)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "device": 115,
                "form_factor": 200,
                "mgmt_only": false,
                "mode": 100,
                "mtu": 1600,
                "name": "port-channel1"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://1.2.3.4:5678",
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": {
        "type": [
            "This field is required."
        ]
    }
}

```
