### ISSUE TITLE
Rename parameters for file module: link

### ISSUE THREAD

**Issue by macau23** [ansible/ansible#69738]
### SUMMARY
Symlinks are horrible in Ansible because they do the opposite to what is expected. The Ansible documentation says:
`"which is how the Unix command ln -s SRC DEST treats relative paths."`

Well yes, perhaps, but `man ln` actually says this:
`Usage: ln [OPTION]... [-T] TARGET LINK_NAME`

The Ansible example shows:
```
- name: Create a symbolic link
  file:
    src: /file/to/link/to
    dest: /path/to/symlink
    state: link
```

The problem here is that `src` and `dest` make no sense at all. If I have a link it points _to_ a destination, the destination doesn't point to a source! Ansible has them the wrong way round!

Could Ansible support the same naming convention as the man page for ln? i.e.

```
- name: Create a symbolic link
  file:
    target: /file/to/link/to
    link_name: /path/to/symlink
    state: link
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
file

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
I'm not sure the issue is with the names, which are generic in this case for the different operations, we CAN make link_name an alias, but it would only make sense for 2 of the states, I believe most of your confusion can be alleviated just by reordering of the task options:
```
- name: Create a symbolic link
  file:
    dest: /path/to/symlink
    src: /file/to/link/to
    state: link
```
