### ISSUE TITLE
docker_swarm join requires advertise_addr

### ISSUE THREAD

**Issue by curt-hash** [ansible/ansible#69744]
##### SUMMARY
The `docker_swarm` module requires `advertise_addr` when `state: join`, but the `docker swarm join` command does not.

The Docker documentation for the `--advertise-addr` option (https://docs.docker.com/engine/reference/commandline/swarm_join/) states:
> This flag is generally not necessary when joining an existing swarm.

However, the Ansible [source](https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/cloud/docker/docker_swarm.py#L635) has:

```
    required_if = [
        ('state', 'join', ['advertise_addr', 'remote_addrs', 'join_token']),
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_swarm

##### ANSIBLE VERSION

```paste below
ansible 2.8.3
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Controller/target: Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- hosts: swarm_manager_init
  tasks:
    - name: Initialize the swarm
      docker_swarm:
        state: present
- hosts: swarm_workers
  tasks:
    - name: Join workers
      docker_swarm:
        state: join
        join_token: '<token>'
        remote_addrs:
          - '<addr>:2377'
```

##### EXPECTED RESULTS

The workers join the swarm.

##### ACTUAL RESULTS

```paste below
state is join but all of the following are missing: advertise_addr
```
