### ISSUE TITLE
Apache Enable Rewrite Module fails if already enabled

### ISSUE THREAD

**Issue by jlariza** [ansible/ansible#69750]
##### SUMMARY
ansible Apache2 module has a bug with ubuntu and enable task. It fails if rewrite is already enabled. It is a variant of this bug https://github.com/ansible/ansible/issues/22635. I tried to create a PR to solve it based on the PR that solved the previous bug, but I could not find where is the apache module .py file in current repository.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
apache2_module

http://docs.ansible.com/ansible/apache2_module_module.html

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
python version = 3.6.8
```

##### CONFIGURATION

```paste below
```

##### STEPS TO REPRODUCE

```yaml
- name: Enable mod-rewrite
  become: yes
  apache2_module:
    state: present
    name: rewrite
```

##### EXPECTED RESULTS

expected an ok / no change message

##### ACTUAL RESULTS

```paste below
Failed to set module rewrite to enabled: Module rewrite already enabled
```
