### ISSUE TITLE
The error was: ansible.module_utils.connection.ConnectionError: Failed to authenticate: private key file is encrypted

### ISSUE THREAD

**Issue by grdesai719** [ansible/ansible#69755]
```
ansible 2.9.7
  config file = /Users/g/Ansible_test/Ine_test/ansible.cfg
  configured module search path = ['/Users/g/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.7/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2
```

I constantly see the below issue, please guide how to resolve:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Failed to authenticate: private key file is encrypted
172.30.100.159.xip.io | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

==========ansible.cfg
```

[defaults]
host_key_checking = False
look_for_keys = False
```
========playbook

```yaml
---
- name: Arista
  hosts: "arista-devices"
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: admin
      password: automation
      transport: cli

  tasks:
    - name: configure hostname
      eos_command:
        commands: show version
        provider: "{{ cli }}"

      register: output

    - name: show output
      debug:
        var: output
```
================

```
hosts
[arista-devices]
172.30.100.159.xip.io
```
============

```
host_vars
---
ansible_network_os: eos
ansible_ssh_host:  172.30.100.159
ansible_ssh_user: ansible
ansible_ssh_password: automation
ansible_connection: network_cli
```
