### ISSUE TITLE
VMware: vmware_host_ntp module does not override

### ISSUE THREAD

**Issue by vMarkusK** [ansible/ansible#69785]
##### SUMMARY

In PR #47273 a change was done to override the NTP servers by default. But this does not work in my case

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host_ntp module

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Harden ESXi Host
  hosts: localhost
  gather_facts: false
  strategy: free
  vars:
    #cluster_name: "cluster01" 
    esxi_hostname: "192.168.234.102"
    host_services_query: "host_service_info.*[?key=='ntpd']"
    host_firewall_query: "hosts_firewall_info.*[?key=='ntpClient']"
  tasks:
    - name: Get Services
      vmware_host_service_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname}}" 
        validate_certs: no
      register: host_services
      tags: debug
    - name: Debug NTP Service
      debug:
        var: host_services | json_query(host_services_query)
    - name: Get Firewall Rules
      vmware_host_firewall_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname}}" 
        validate_certs: no
      register: host_firewall
      tags: debug
    - name: Debug Firewall Rules
      debug:
        var: host_firewall | json_query(host_firewall_query)
    - name: Get NTP Config
      vmware_host_ntp_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
      register: host_ntp
      tags: debug
    - name: Debug NTP Config
      debug:
        var: host_ntp.hosts_ntp_info
    - name: Set NTP Service
      vmware_host_service_manager:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname}}" 
        validate_certs: no
        service_name: ntpd
        state: present
        service_policy: on 
      tags: ntp  
    - name: Manage NTP Firewall Rules
      vmware_host_firewall_manager:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname}}"   
        validate_certs: no
        rules:
        - name: ntpClient
          enabled: True
          allowed_hosts:
            all_ip: False
            ip_address:
            - 192.168.20.10
            - 192.168.20.11
      tags: ntp  
    - name: Set NTP servers
      vmware_host_ntp:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname}}"
        validate_certs: no  
        verbose: yes 
        state: present
        ntp_servers:
        - 192.168.20.10
        - 192.168.20.11
      tags: ntp 
    - name: Get NEW NTP Config
      vmware_host_ntp_info:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
        validate_certs: no
      register: host_ntp
      tags: debug
    - name: Debug NEW NTP Config
      debug:
        var: host_ntp.hosts_ntp_info
```

##### EXPECTED RESULTS

The two specified ntp server should be added and all existing should be removed

##### ACTUAL RESULTS

The two specified ntp server are added and all existing are preserved

```paste below
[mkus@ansible01 Ansible-Playground]# ansible-playbook vmware_secure_ntp.yml --ask-vault-pass 
Vault password: 
[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [Harden ESXi Host] **********************************************************************************************************************************************************************

TASK [Get Services] **************************************************************************************************************************************************************************
ok: [localhost]

TASK [Debug NTP Service] *********************************************************************************************************************************************************************
ok: [localhost] => {
    "host_services | json_query(host_services_query)": [
        [
            {
                "key": "ntpd",
                "label": "NTP Daemon",
                "policy": "on",
                "required": false,
                "running": true,
                "source_package_desc": "This VIB contains all of the base functionality of vSphere ESXi.",
                "source_package_name": "esx-base",
                "uninstallable": false
            }
        ]
    ]
}

TASK [Get Firewall Rules] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [Debug Firewall Rules] ******************************************************************************************************************************************************************
ok: [localhost] => {
    "host_firewall | json_query(host_firewall_query)": [
        [
            {
                "allowed_hosts": {
                    "all_ip": false,
                    "ip_address": [
                        "192.168.20.11",
                        "192.168.20.10"
                    ],
                    "ip_network": []
                },
                "enabled": true,
                "key": "ntpClient",
                "rule": [
                    {
                        "direction": "outbound",
                        "end_port": null,
                        "port": 123,
                        "port_type": "dst",
                        "protocol": "udp"
                    }
                ],
                "service": "ntpd"
            }
        ]
    ]
}

TASK [Get NTP Config] ************************************************************************************************************************************************************************
ok: [localhost]

TASK [Debug NTP Config] **********************************************************************************************************************************************************************
ok: [localhost] => {
    "host_ntp.hosts_ntp_info": {
        "esxi02.lab.local": [
            {
                "ntp_servers": [
                    "192.168.2.1",
                    "192.168.1.1",
                    "192.168.20.10",
                    "192.168.20.11"
                ],
                "time_zone_description": "UTC",
                "time_zone_gmt_offset": 0,
                "time_zone_identifier": "UTC",
                "time_zone_name": "UTC"
            }
        ]
    }
}
[WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.


TASK [Set NTP Service] ***********************************************************************************************************************************************************************
[WARNING]: The value True (type bool) in a string field was converted to 'True' (type string). If this does not look like what you expect, quote the entire value to ensure it does not
change.

ok: [localhost]

TASK [Manage NTP Firewall Rules] *************************************************************************************************************************************************************
ok: [localhost]
[WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.


TASK [Set NTP servers] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [Get NEW NTP Config] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [Debug NEW NTP Config] ******************************************************************************************************************************************************************
ok: [localhost] => {
    "host_ntp.hosts_ntp_info": {
        "esxi02.lab.local": [
            {
                "ntp_servers": [
                    "192.168.2.1",
                    "192.168.1.1",
                    "192.168.20.10",
                    "192.168.20.11"
                ],
                "time_zone_description": "UTC",
                "time_zone_gmt_offset": 0,
                "time_zone_identifier": "UTC",
                "time_zone_name": "UTC"
            }
        ]
    }
}

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
