### ISSUE TITLE
vmware_guest: customvalues not applied to pre-existing VM

### ISSUE THREAD

**Issue by PrymalInstynct** [ansible/ansible#69784]
##### SUMMARY

I am attempting to apply custom values (Advanced Options -> Configuration Parameters) using the vmware_guest module to an VM that already exists. The VM will power off per playbook task but the customvalues are not applied.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/playbooks/ansible.cfg
  configured module search path = [u'/home/zimmermanc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/playbooks/ansible.cfg) = [u'profile_tasks']
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
    - name: Stop & Configure Test VM with Custom Options
      vmware_guest:
        hostname: esxi01
        username: root
        password: 
        esxi_hostname: esxi01
        validate_certs: no
        name: app01
        state: poweredoff
        customvalues:
          - key: "isolation.tools.copy.disable"
            value: "True"
          - key: "isolation.tools.paste.disable"
            value: "True"
          - key: "isolation.tools.diskShrink.disable"
            value: "True"
          - key: "isolation.tools.diskWiper.disable"
            value: "True"
          - key: "mks.enable3d"
            value: "False"
          - key: "tools.setInfo.sizeLimit"
            value: "1048576"
          - key: "RemoteDisplay.vnc.enabled"
            value: "False"
          - key: "tools.guestlib.enableHostInfo"
            value: "False"
      delegate_to: localhost

    - name: Start Test VM
      vmware_guest:
        hostname: esxi01
        username: root
        password: 
        esxi_hostname: esxi01
        validate_certs: no
        name: app01
        state: poweredon
      delegate_to: localhost
```

##### EXPECTED RESULTS

I would expect to be able to browse to the advanced options of the VM and find the custom configuration parameters

##### ACTUAL RESULTS

```paste below
TASK [Stop & Configure Test VM with Custom Options] *************************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/configure-esxi.yml:72
changed: [localhost -> localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "11265",
        "hw_cluster": null,
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "datastore1"
        ],
        "hw_esxi_host": "esxi01.localhost",
        "hw_eth0": {
            "addresstype": "generated",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": "00:0c:29:25:65:e0",
            "macaddress_dash": "00-0c-29-25-65-e0",
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "Server-LAN-10.10.10.0/24"
        },
        "hw_files": [
            "[datastore1] app01/app01.vmx",
            "[datastore1] app01/app01.nvram",
            "[datastore1] app01/app01.vmsd",
            "[datastore1] app01/vmware-1.log",
            "[datastore1] app01/vmware.log",
            "[datastore1] app01/app01.vmdk"
        ],
        "hw_folder": "/ha-datacenter/vm",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": null,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 8192,
        "hw_name": "app01",
        "hw_power_status": "poweredOff",
        "hw_processor_count": 4,
        "hw_product_uuid": "564dc025-2bfa-e686-b042-2bdcd32565e0",
        "hw_version": "vmx-13",
        "instance_uuid": "5238b257-84f7-1268-a026-769cad552c6a",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "moid": "7",
        "snapshots": [],
        "vimref": "vim.VirtualMachine:7",
        "vnc": {}
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [],
            "cluster": null,
            "convert": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [
                {
                    "key": "isolation.tools.copy.disable",
                    "value": "True"
                },
                {
                    "key": "isolation.tools.paste.disable",
                    "value": "True"
                },
                {
                    "key": "isolation.tools.diskShrink.disable",
                    "value": "True"
                },
                {
                    "key": "isolation.tools.diskWiper.disable",
                    "value": "True"
                },
                {
                    "key": "mks.enable3d",
                    "value": "False"
                },
                {
                    "key": "tools.setInfo.sizeLimit",
                    "value": "1048576"
                },
                {
                    "key": "RemoteDisplay.vnc.enabled",
                    "value": "False"
                },
                {
                    "key": "tools.guestlib.enableHostInfo",
                    "value": "False"
                }
            ],
            "datacenter": "ha-datacenter",
            "datastore": null,
            "disk": [],
            "esxi_hostname": "esxi01",
            "folder": null,
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "esxi01",
            "is_template": false,
            "linked_clone": false,
            "name": "app01",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredoff",
            "state_change_timeout": 0,
            "template": null,
            "use_instance_uuid": false,
            "username": "root",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_ip_address": false
        }
    }
}
```
