### ISSUE TITLE
Modified "vars:" not visible inside include_role.

### ISSUE THREAD

**Issue by vbotka** [ansible/ansible#69799]
IMHO. Not included in https://github.com/ansible/ansible/projects/19

tested with ansible 2.9.6

##### SUMMARY

A modification of a variable declared in "vars" is not visible inside the included role.
```
    - include_role:
        name: test
        tasks_from: task.yml
      vars:
        my_var: A
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /export/home/vlado.config/.ansible/ansible-examples/examples/example-136/ansible.cfg
  configured module search path = ['/home/vlado/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/export/home/vlado.config/.ansible/ansible-examples/examples/example-136/an$
DEFAULT_ROLES_PATH(/export/home/vlado.config/.ansible/ansible-examples/examples/example-136/a$
```

##### OS / ENVIRONMENT

Linux host9 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Fresh role with this task only
```
shell> cat roles/test/tasks/task.yml
- debug:
    var: my_var
- set_fact:
    my_var: B
- debug:
    var: my_var
```

```yaml
- hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: test
        tasks_from: task.yml
        apply:
          vars:
            my_var: A
    - debug:
        var: my_var

# Variable must be declared by "apply: vars".
#
#    "my_var": "A"
#    "my_var": "B"
#    "my_var": "B"

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include_role:
        name: test
        tasks_from: task.yml
      vars:
        my_var: A
    - debug:
        var: my_var

# New copy visible outside the role only will be created if the variable
# is declared by "vars:".
#
#    "my_var": "A"
#    "my_var": "A"
#    "my_var": "B"
```

##### EXPECTED RESULTS

Fix the documentation

```
- name: Pass variables to role
  include_role:
    name: myrole
    apply:
      vars:
        rolevar1: value from task
```
##### ACTUAL RESULTS

Quoting from Examples
https://docs.ansible.com/ansible/latest/modules/include_role_module.html#examples

```
- name: Pass variables to role
  include_role:
    name: myrole
  vars:
    rolevar1: value from task
```

```paste below

```

**Comment by vbotka** [comment]
Edit on GitHub fails: 404
https://docs.ansible.com/ansible/latest/modules/include_role_module.html

**Comment by Akasurde** [comment]
@vbotka "Edit on GitHub fail" is known and reported here - https://github.com/ansible/ansible/issues/69683#issuecomment-633396236

**Comment by bcoca** [comment]
for full fix #69040

**Comment by vbotka** [comment]
Is (should be/will be) any difference between these options?

```yaml
    - include_role:
        name: test
        tasks_from: task.yml
        apply:
          vars:
            my_var: A
```
and

```yaml
    - include_role:
        name: test
        tasks_from: task.yml
      vars:
          my_var: A
```
