### ISSUE TITLE
Please add "creates" to the archive module

### ISSUE THREAD

**Issue by DaveWK** [ansible/ansible#69809]
##### SUMMARY
I have a process which generates a list of files locally to be archived. Each host may or may not have the same files. In order to prevent a lot of archives being generated that have the same files in them, I took a sha of the list of files and added it to the filename. It appears archive is still remaking the file every time. I could see this being useful if you cared about the contents of the files being archived changing, but that is not the case for my use case as it's bundling files that are all local. In example:
```
    - name: Archive all the files locally, use a sha to dedupe
      archive:
        path: "{{ archive_files }}"
        dest: "deploy-{{ archive_files | hash('sha1') }}.tar.gz"
      delegate_to: 127.0.0.1
```
where `archive_files` is a list of files I have created earlier.

This will attempt to re-archive for every host in the play even when the sha matches, so I have to wait for it to re-archive every time for every host even when the file is the same. 

I'd like this to either have the option to skip when the files already exists, or to use the "creates" var like shell/command do. I could see this being a problematic change of behaviour, so I would suggest making this default to recreating, but optionally skip when the file exists. I can work around this by using "stat" and "register" but it really would be cleaner to have this in the single command.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
archive

##### ADDITIONAL INFORMATION

```yaml
    - name: Archive all the files locally, use a sha to dedupe
      archive:
        path: "{{ archive_files }}"
        dest: "deploy-{{ archive_files | hash('sha1') }}.tar.gz"
      delegate_to: 127.0.0.1
```
