### ISSUE TITLE
Conditional and wild card usage

### ISSUE THREAD

**Issue by sandeep444033** [ansible/ansible#69810]
##### SUMMARY

Conditional and wild card usage

##### ISSUE TYPE
- Feature Idea
Conditional and wild card usage

##### ADDITIONAL INFORMATION

Is there any way I can use the wild cards or regex in when statements,

when: ansible_distribution_major_version|int == 6 or ansible_fqdn == "test[0-1][0-9].example.com"

Like here I want only respective action to be taken on my hosts if my server OS version is 6 or hostname matches test01-19.example.com

```yaml

```

**Comment by Akasurde** [comment]
Hi @sandeep444033 !

You can use all jinja filters in `when` conditionals, so use [`regex_search`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#regular-expression-filters) filter for your regex.

Like - 
 
```yaml
  vars:
    hostname: test1-9.example.com
  tasks:
    - name: debug
      debug:
        msg: "passed"
      when:
        - "hostname | regex_search('test[0-1]-[0-9].example.com')"
```

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs, and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
