### ISSUE TITLE
How can i get ip addresses of group hostnames

### ISSUE THREAD

**Issue by KostLinux** [ansible/ansible#69827]
I can't find anywhere, how can i get ip addresses of hosts in specific group
```
- hosts: opmon
  tasks:
    - lineinfile:
        create: true
        line: "host\t'op-monitor'\topmonitor\t{{ item}}/24\t\tmd5"
        dest: /tmp/groups.txt
      with_items: "{{ groups.nodes }}"
```
This playbook prints
` host     'op-monitor'     opmonitor     node1.itarchive.home/24     md5`
to pg_hba.conf
I need, that node1.itarchive.home will be in IP
Something like that:
`host     'op-monitor'     opmonitor     192.168.0.95/24     md5'
