### ISSUE TITLE
Openshift Pod and module error

### ISSUE THREAD

**Issue by joeibm2020** [ansible/ansible#69841]
##### SUMMARY
In openshift architecture we have ansible deployment running inside of a pod, while running a playbook to connect to openshift using module k8s_info is failing 

##### ISSUE TYPE
this is the output error from ansible after to run the playbook,while using module

"msg": "Failed to import the required Python library (openshift) on oc-us-south1-int2.bm.ciocloud.nonprod.intranet.ibm.com's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter",
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_k8s_info_payload_x1p366/ansible_k8s_info_payload.zip/ansible/module_utils/k8s/common.py\", line 33, in <module>\n    import kubernetes\nImportError: No module named kubernetes\n",
    "error": "No module named kubernetes",
    "invocation": {
        "module_args": {
            "username": null,
            "kind": "Pod",
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "field_selectors": [],
            "name": null,
            "ca_cert": null,
            "namespace": null,
            "label_selectors": [],
            "kubeconfig": null,
            "host": "https://{'changed': True, 'end': '2020-05-29 14:45:15.078495', 'stdout': 'api.servername.com', 'cmd': \"cat /var/lib/dnsmasq/ocnet.addnhosts | grep api.us | awk '{print $3}'\", 'rc': 0, 'start': '2020-05-29 14:45:15.071849', 'stderr': '', 'delta': '0:00:00.006646', 'stdout_lines': ['api.servername.com], 'stderr_lines': [], 'failed': False}:6443",
            "proxy": null,
            "context": null,
            "password": null,
            "validate_certs": false,
            "client_cert": null,
            "api_version": "v1",
            "client_key": null
        }
    },
    "_ansible_no_log": false,
    "changed": false

##### COMPONENT NAME
we are using k8s_info module 

##### ANSIBLE VERSION

```paste below
Ansible 2.9.7 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: connect to bare metal
  hosts: host1
  user: account1
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  vars:
   token1: lookup("env",'OCP_TOKEN')
   ocp_api: output_result.stdout 

  tasks:
  - name: get the api to connect to openshift and filter out api openshift and create variable
    shell: "cat /var/lib/dnsmasq/ocnet.addnhosts | grep api.us | awk '{print $3}'"
    register: output_result
  - set_fact: 
     result_api: "{{ output_result.stdout }}"

  - name: Fetch a list of pods
    k8s_info:
     kind: Pod
     host: https://{{ output_result }}:6443
     validate_certs: no
     api_key: "{{ token1 }}"
    register: pod_list
```

##### EXPECTED RESULTS
it was expected to be able to connect to the openshift software via api and get pod list

##### ACTUAL RESULTS
we are getting a module error related with openshift libraries and k8s_info module

```paste below

```
