### ISSUE TITLE
ios_user sshkey does not remove/replace existing keys

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#69849]
##### SUMMARY

We are configuring users with:
```
- name: "Create user {{ item.user }}"
  ios_user:
    name: "{{ item.user }}"
    sshkey: "{{ item.keylist }}"
    role: network-admin
    privilege: 1
    state: present
  become: yes
```
however when we change the list of ssh keys, it does not replace the existing ssh keys in the config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/export/home/orion-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  1 2020, 10:09:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT
EL7

Cisco IOS Software, C2960S Software (C2960S-UNIVERSALK9-M), Version 15.2(2)E9, RELEASE SOFTWARE (fc4)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ios
  tasks:
    - name: "Create user testuser"
      ios_user:
        name: testuser
        sshkey:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxko6+8zhPJn010N99aM1EMogLHjzItU4QWhqRJ5Se6K24q8JaxgdFrysKJkR/W4scw0PPTz/jIl3FRMJi/LIFlDoSgeZRywmDLQRhmHbSCysnr3aUURI4QYdNeKX6wV7ORviWCIG66rUKdRCdVGFWxNYUTcXoTlYcgbOvHi/OWS2ppdRPrJpOGj3lr2UYcuyCJ+43SGhhPKrTWgq/XeKi8D9rK4CuQzxSAk6zmA9m+v68oiGlMMJgsCWp/VE+Cjl3FWmTf+kfwQ+JpMmiN3QD7Unlhwr4ExQLdl9m8504vh7Gk2KcCT/FrMfdf+9UJueXTovXVXagegGxubADS+fh
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCns7Q+QLg2MQ04mu+0EPJpRXqdgdw+tUAEgBwqbvKLr4xmf3WVmsIZlN2ZOywuNSdb9k2BQJCXuZKxSHYKBtmN9k1kdYtGEVAQC7i1rOQklKjrD4MmhUIAyuKd9q8cOoabnxmubpitxaz1aFfAMqsjg+PCFho7mjjV0s8+VTzG9waQ4SEQcV6wEi/AkqNRQREPbbHptfDqKkPY3plDspee/dvRfPd6QzAWLcpgSLVYRlLw+h+7MTAu7aotxto8R8kBdsBE//d1Gyo1y+S0Q8qDJ6c4klr6E8jbDeWQN+jqiQWGGTSiV8ntrKG1LB0xOjelQ1A8jAb0QCSSNFptfD5r
        state: present
      become: yes
    - name: "Modify user testuser"
      ios_user:
        name: testuser
        sshkey:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0xBuag8zlMxJ2+SXkkgcO8l5nmCqFzF5BgwfxCq6sj/BVn4aoN5lsECr+YAQEie6ZXrXWI/qIvbg4WRVW/htIMLeOd5AqKO7RPe6oaTF80FrmaFjAR4gxHFVwqnBINhTv1wgHwcazfyd3MA0p/BY0kR+DnllQ4ro7+yBBBXYZet/PuHJaAq9wQKvL1n4+TqbhSIXI3Bi7BrI0y+DgTfQq5LhyxdtYKOcKfdTLAlBVuzGEAsAVOQe5c6oOOZSe5xmrd7OQhqhpXhpUz5NcpqeVUXIgz9erq+PGHCHEmTD885TxlYBQjV2x5OO0wR/fahESL3vCtQMX4ZvG0HjtssCn
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0rbm0RJlpt16T8hM4TJauyh+1pQZI6tzlMPMAvljpo52KNXof9zf5z21kn+fmWmESkuHi32Ddzx5u+QoOu7YngDa+Ek/vfMpoLCpc2ioyJTXyOSArj3PLllNzSRewm5LJYxhKYqz7PegfTR9m0+NpNYh6vOIm9rzLFmG5+MZJdkv8zwZoIYbcON+ZAZDczGxinTSU5qK/G8c20CdDJbNyu+YWnd2B0owhgXlq7faddG/aXEpIT3FDJtTcX0EjHLyh1Zr2IIZiMvRlRLdTl2Kq4ujNYJcYSiQGkAfXo5KEyC2iZh5k2m+7qyE7v82m+MXUdVtcFtuw4fTj1edSnOBv
        state: present
      become: yes
```

##### EXPECTED RESULTS

testuser is left with the ssh keys of the second invocation.

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.9.9
  config file = /export/home/orion-admin/ansible-network/ansible.cfg
  configured module search path = [u'/export/home/orion-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Apr  1 2020, 10:09:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /export/home/orion-admin/ansible-network/ansible.cfg as config file
BECOME password: 
host_list declined parsing /export/home/orion-admin/ansible-network/hosts as it did not pass its verify_file() method
script declined parsing /export/home/orion-admin/ansible-network/hosts as it did not pass its verify_file() method
auto declined parsing /export/home/orion-admin/ansible-network/hosts as it did not pass its verify_file() method
Parsed /export/home/orion-admin/ansible-network/hosts inventory source with ini plugin

PLAYBOOK: ios_user_sshkey.yml **********************************************************************************************************************************************
1 plays in ios_user_sshkey.yml

PLAY [ios] *****************************************************************************************************************************************************************
META: ran handlers

TASK [Create user testuser] ************************************************************************************************************************************************
task path: /export/home/orion-admin/ansible-network/ios_user_sshkey.yml:4
<switch-2960s> Attempting python interpreter discovery
<switch-2960s> ESTABLISH LOCAL CONNECTION FOR USER: orion-admin
<switch-2960s> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'                                                                                          
<switch-2960s> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/ios/ios_user.py
Pipelining is enabled.
<switch-2960s> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
[WARNING]: Module did not set no_log for update_password
[WARNING]: Module did not set no_log for password_type
changed: [switch-2960s] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": true, 
    "commands": [
        "ip ssh pubkey-chain", 
        "username testuser", 
        "key-hash ssh-rsa 2723856A8FDEDC5E54262B1AB5D70357", 
        "key-hash ssh-rsa 18F3175F7C08ADBEBDDB35E892FFCAD0", 
        "exit", 
        "exit"
    ], 
    "invocation": {
        "module_args": {
            "aggregate": null, 
            "auth_pass": null, 
            "authorize": null, 
            "configured_password": null, 
            "hashed_password": null, 
            "host": null, 
            "name": "testuser", 
            "nopassword": null, 
            "password": null, 
            "password_type": "secret", 
            "port": null, 
            "privilege": null, 
            "provider": null, 
            "purge": false, 
            "ssh_keyfile": null, 
            "sshkey": [
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxko6+8zhPJn010N99aM1EMogLHjzItU4QWhqRJ5Se6K24q8JaxgdFrysKJkR/W4scw0PPTz/jIl3FRMJi/LIFlDoSgeZRywmDLQRhmHbSCysnr3aUURI4QYdNeKX6wV7ORviWCIG66rUKdRCdVGFWxNYUTcXoTlYcgbOvHi/OWS2ppdRPrJpOGj3lr2UYcuyCJ+43SGhhPKrTWgq/XeKi8D9rK4CuQzxSAk6zmA9m+v68oiGlMMJgsCWp/VE+Cjl3FWmTf+kfwQ+JpMmiN3QD7Unlhwr4ExQLdl9m8504vh7Gk2KcCT/FrMfdf+9UJueXTovXVXagegGxubADS+fh",                                                                                                                     
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCns7Q+QLg2MQ04mu+0EPJpRXqdgdw+tUAEgBwqbvKLr4xmf3WVmsIZlN2ZOywuNSdb9k2BQJCXuZKxSHYKBtmN9k1kdYtGEVAQC7i1rOQklKjrD4MmhUIAyuKd9q8cOoabnxmubpitxaz1aFfAMqsjg+PCFho7mjjV0s8+VTzG9waQ4SEQcV6wEi/AkqNRQREPbbHptfDqKkPY3plDspee/dvRfPd6QzAWLcpgSLVYRlLw+h+7MTAu7aotxto8R8kBdsBE//d1Gyo1y+S0Q8qDJ6c4klr6E8jbDeWQN+jqiQWGGTSiV8ntrKG1LB0xOjelQ1A8jAb0QCSSNFptfD5r"                                                                                                                      
            ], 
            "state": "present", 
            "timeout": null, 
            "update_password": "always", 
            "username": null, 
            "view": null
        }
    }
}

TASK [Modify user testuser] ************************************************************************************************************************************************
task path: /export/home/orion-admin/ansible-network/ios_user_sshkey.yml:12
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/ios/ios_user.py
Pipelining is enabled.
<switch-2960s> ESTABLISH LOCAL CONNECTION FOR USER: orion-admin
<switch-2960s> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [switch-2960s] => {
    "changed": true, 
    "commands": [
        "ip ssh pubkey-chain", 
        "username testuser", 
        "key-hash ssh-rsa FFFE5EDD40AA702CAE06DFDAE95F0924", 
        "key-hash ssh-rsa D79DBEA16EFAC377BCB3740E0A793053", 
        "exit", 
        "exit"
    ],
    "invocation": {
        "module_args": {
            "aggregate": null,
            "auth_pass": null,
            "authorize": null,
            "configured_password": null,
            "hashed_password": null,
            "host": null,
            "name": "testuser",
            "nopassword": null,
            "password": null,
            "password_type": "secret",
            "port": null,
            "privilege": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "sshkey": [
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0xBuag8zlMxJ2+SXkkgcO8l5nmCqFzF5BgwfxCq6sj/BVn4aoN5lsECr+YAQEie6ZXrXWI/qIvbg4WRVW/htIMLeOd5AqKO7RPe6oaTF80FrmaFjAR4gxHFVwqnBINhTv1wgHwcazfyd3MA0p/BY0kR+DnllQ4ro7+yBBBXYZet/PuHJaAq9wQKvL1n4+TqbhSIXI3Bi7BrI0y+DgTfQq5LhyxdtYKOcKfdTLAlBVuzGEAsAVOQe5c6oOOZSe5xmrd7OQhqhpXhpUz5NcpqeVUXIgz9erq+PGHCHEmTD885TxlYBQjV2x5OO0wR/fahESL3vCtQMX4ZvG0HjtssCn",
                "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0rbm0RJlpt16T8hM4TJauyh+1pQZI6tzlMPMAvljpo52KNXof9zf5z21kn+fmWmESkuHi32Ddzx5u+QoOu7YngDa+Ek/vfMpoLCpc2ioyJTXyOSArj3PLllNzSRewm5LJYxhKYqz7PegfTR9m0+NpNYh6vOIm9rzLFmG5+MZJdkv8zwZoIYbcON+ZAZDczGxinTSU5qK/G8c20CdDJbNyu+YWnd2B0owhgXlq7faddG/aXEpIT3FDJtTcX0EjHLyh1Zr2IIZiMvRlRLdTl2Kq4ujNYJcYSiQGkAfXo5KEyC2iZh5k2m+7qyE7v82m+MXUdVtcFtuw4fTj1edSnOBv"
            ],
            "state": "present",
            "timeout": null,
            "update_password": "always",
            "username": null,
            "view": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************
switch-2960s : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

show run reports:
```
  username testuser
   key-hash ssh-rsa 2723856A8FDEDC5E54262B1AB5D70357
   key-hash ssh-rsa 18F3175F7C08ADBEBDDB35E892FFCAD0
```
which if you compare to the output above is the hashes from the first invocation.
