### ISSUE TITLE
Issue with delagate_to from centos8 to centos6, bad python interpreter used

### ISSUE THREAD

**Issue by vengaar** [ansible/ansible#69853]
##### SUMMARY
delegate_to from centos8 server to centos6 server doesn't work because the python interpreter path used is centos8 path

I hope issue will be fixed in 2.9.7 with https://github.com/ansible/ansible/issues/61002 but it is not the case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Maybe connection plugin ? 
See test playbook below in *STEPS TO REPRODUCE*

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/kookel/kelkoo_ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /opt/kookel/kloud/data/inventory/fact
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 108000
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/kelkoo_ansible/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/kelkoo_ansible/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/kelkoo_ansible/plugins/filter']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventories']
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}. Do not modify it manually
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/kelkoo_ansible/modules']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = ...
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/opt/kookel/ansible/common/playbooks/roles', u'/opt/kookel/ansible_roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = kelkoo_stdout
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = ...
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_ANY_UNPARSED_IS_FAILED(/etc/ansible/ansible.cfg) = True
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'ini', u'script', u'yaml']
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = always
```

##### OS / ENVIRONMENT

Ansible server in "CentOS Linux release 7.8.2003 (Core)"
Target servers in centos8/centos6, see output of playbook test below

##### STEPS TO REPRODUCE

```yaml
---
- name: Show discovered_interpreter_python
  hosts:
    - dc1-kel-dev-ope-centos8.dev.dc1.kelkoo.net
    - dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net
  gather_facts: false
  tasks:
    - meta: clear_facts
    - setup:
    - name: Show server facts
      debug:
        msg: |
          discovered_interpreter_python => {{ discovered_interpreter_python }}
          ansible_lsb.description => {{ ansible_lsb.description }}

- name: Test delegate_to
  hosts:
    - dc1-kel-dev-ope-centos8.dev.dc1.kelkoo.net
  tasks:
    - name: uname delegate_to centos6
      command: uname -a
      delegate_to: dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net

    - name: uname
      command: uname -a
...
```

##### ACTUAL RESULTS

```paste below
[kookel@dc1-kloud-ifr-dev-01 ansible]$ ansible-playbook /opt/kookel/ansible/kloud/playbooks/kloud_test_delegate_to.yml -v
Using /etc/ansible/ansible.cfg as config file

PLAY [Show discovered_interpreter_python] *************************************************************************************************************************

TASK (07:26:49) [setup] *******************************************************************************************************************************************
ok: [dc1-kel-dev-ope-centos8.dev.dc1.kelkoo.net]
task duration: 0:00:02
ok: [dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net]
task duration: 0:00:04

TASK (07:26:53) [Show server facts] *******************************************************************************************************************************
ok: [dc1-kel-dev-ope-centos8.dev.dc1.kelkoo.net] => {}

MSG:

discovered_interpreter_python => /usr/libexec/platform-python
ansible_lsb.description => CentOS Linux release 8.1.1911 (Core)

task duration: 0:00:00
ok: [dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net] => {}

MSG:

discovered_interpreter_python => /usr/bin/python
ansible_lsb.description => CentOS release 6.10 (Final)

task duration: 0:00:00

PLAY [Test delegate_to] *******************************************************************************************************************************************

TASK (07:26:54) [uname delegate_to centos6] ***********************************************************************************************************************
fatal: [dc1-kel-dev-ope-centos8.dev.dc1.kelkoo.net -> dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net]: FAILED! => {
    "changed": false, 
    "rc": 127
}

MSG:

The module failed to execute correctly, you probably need to set the interpreter.
See stdout/stderr for the exact error


MODULE_STDOUT:

/bin/sh: /usr/libexec/platform-python: No such file or directory



MODULE_STDERR:

Shared connection to dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net closed.

task duration: 0:00:00

PLAY RECAP ********************************************************************************************************************************************************
dc1-ifr-dev-install-centos6.dev.dc1.kelkoo.net : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
dc1-kel-dev-ope-centos8.dev.dc1.kelkoo.net : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

I hope to provide you with all informations you need.
Do not hesitate if I can help you.
