### ISSUE TITLE
Large initial latency when launching and polling asynchronious operations 

### ISSUE THREAD

**Issue by momcilo78** [ansible/ansible#69857]
##### SUMMARY
When launching the async jobs (poll:0, async: 30), iterated over items, each item is iterated and takes on between 300-600ms. If there are more of them this results in the whole operation taking up to 20 seconds. Expected is rapid launch of all items in no more than 1-2 seconds.  I gather this is not much visible if tasks are in the minute range, but if you need to launch a series of short lived tasks this ruins the async performance to the level that is barely faster then sequential iteration. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- loop, poll, async, async_status

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/momcilo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION
Empty:
```paste below
```

##### OS / ENVIRONMENT
Ubuntu 20.04, (but also CentOS 8 environments)

##### STEPS TO REPRODUCE
Execute the following playbook locally.
Expected that first tasks executes rather fast.  

Second problem occurs when joining results, where the iteration & polling is rather slow (you would need to reduce the waiting times to 1 second range to observe this properly).

```yaml
- name: Run tasks in parallel
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Pretend to create instances
      command: "sleep {{ item }}"  # Instead of calling a long running operation at a cloud provider, we just sleep.
      loop:
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
        - 30
        - 20
        - 10
      register: _create_instances
      async: 600  # Maximum runtime in seconds. Adjust as needed.
      poll: 0  # Fire and continue (never poll)
      delay: 0

    - name: Wait for creation to finish
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _jobs
      until: _jobs.finished
      delay: 5  # Check every 5 seconds. Adjust as you like.
      retries: 10  # Retry up to 10 times. Adjust as needed.
      loop: "{{ _create_instances.results }}"
```

##### EXPECTED RESULTS
For launch: 
everything gets launched in 2-3 seconds

For async_status:
wait 30 seconds, and display all results with 2-3 seconds. 

##### ACTUAL RESULTS
For launch: 
is rather slow

For async_status:
is rather slow.

Also I have noticed that jobs scheduled for 10 seconds, will very frequently not be caught by async_status, until the last task finishes the execution. I would sort of expect that all 10s get reported after 10-13 seconds, followed by 20s, followed by 30s.
