### ISSUE TITLE
Incorrect entries in ansible_builtin_runtime.yml file

### ISSUE THREAD

**Issue by wojtek0806** [ansible/ansible#69862]
##### SUMMARY

Incorrect entries in `ansible_builtin_runtime.yml`

Problematic lines:
https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml#L2163 to
https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml#L2178

The entries should be as below:

```
    bigip_device_facts:
      redirect: f5networks.f5_modules.bigip_device_info
    bigip_iapplx_package:
      redirect: f5networks.f5_modules.bigip_lx_package
    bigip_security_address_list:
      redirect: f5networks.f5_modules.bigip_firewall_address_list
    bigip_security_port_list:
      redirect: f5networks.f5_modules.bigip_firewall_port_list
    bigip_traffic_group:
      redirect: f5networks.f5_modules.bigip_device_traffic_group
    bigip_facts:
      tombstone:
        removal_date: 2019-11-06
        warning_text: bigip_facts has been removed please use bigip_device_info module
    bigip_gtm_facts:
      tombstone:
        removal_date: 2019-11-06
        warning_text: bigip_gtm_facts has been removed please use bigip_device_info module
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lib/ansible/config/ansible_builtin_runtime.yml
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
