### ISSUE TITLE
Allow using generated item into with_subelements

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [ansible/ansible#69879]
##### SUMMARY
When using with_subelements in code it would be useful choosing which subdict will be iterated basing on the key of the first dict, this would help in looping through nested dicts while keeping original dicts values

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
with_subelements

##### ADDITIONAL INFORMATION

```yaml
vars:
  apt_repo:
    repo1:
      local: true
      myrepo:
        components:
          - main
          - contrib
          - nonfree
      myrepo-security:
        components:
          - main
          - contrib
          - nonfree
      myrepo-backports:
        components:
          - main
          - contrib
          - nonfree
    repo2:
      local: true
      myrepo:
        components:
          - main
          - contrib
          - nonfree
      myrepo-security:
        components:
          - main
          - contrib
          - nonfree
      myrepo-backports:
        components:
          - main
          - contrib
          - nonfree
tasks:
  - name: Create repositories conf repo dirs
    file:
      path: "{{web_root}}/{{item[0]|lower}}/conf/{{item[1]|lower}}"
      mode: '0755'
      state: directory
    when: apt_repo[item.0].local is defined and apt_repo[item.0].local
    with_subelements:
      - apt_repo
      - "{{apt_repo[item.0]}}"
```
