### ISSUE TITLE
Python psycopg2 module is required

### ISSUE THREAD

**Issue by pierot** [ansible/ansible#6989]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Locally: Mac OSX 10.9.2
Host: Arch Linux
##### Summary:

Ansible task keeps telling me the psycopg2 module isn't installed, although everything seems to be ok to me.
##### Steps To Reproduce:

If I try to run:

```
TASK: [postgresql_create | postgresql_db name=xxxx encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8'] ***
failed: [188.226.164.130] => {"failed": true, "item": ""}
msg: the python psycopg2 module is required
```
##### Expected Results:

The task should complete without errors.
##### Things I tried / Extra clues

On the host I have the following packages installed:

```
- name: install postgresql package
  pacman: name={{ item }} state=installed
  with_items:
    - postgresql
    - postgresql-libs
    - python-psycopg2
    - postgresql-devel

- name: install psycopg2 python module
  pip: name=psycopg2
```

If I ssh to the remote host and execute:

```
python -c "import psycopg2"
```

The command doesn't generate any error. 

```
pip list
```

shows

```
pip (1.5.4)
psycopg2 (2.5.2)
setuptools (3.4.4)
```

Any ideas?

**Comment by SiggyF** [comment]
I have the same issue. Ansible is using  `/usr/bin/python` (the system python) and not python (in my case the macports version that has psycopg2 installed). 
You can set the python interpreter used using the [ansible_python_interpreter](http://docs.ansible.com/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine).

**Comment by mpdehaan** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

On September 26, 2014, due to enormous levels of contribution to the project Ansible decided to reorganize module repos, making it easier
for developers to work on the project and for us to more easily manage new contributions and tickets.

We split modules from the main project off into two repos, http://github.com/ansible/ansible-modules-core and http://github.com/ansible/ansible-modules-extras

If you would still like this ticket attended to, and believe this problem or idea is still present in the latest version of Ansible (1.7.2) or the development branch, we will need your help in having it reopened in one of the two new repos, and instructions are provided below.

We apologize that we are not able to make this transition happen seamlessly, though this is a one-time change and your help is greatly appreciated -- 
this will greatly improve velocity going forward.

Both sets of modules will ship with Ansible, though they'll receive slightly different ticket handling.

To locate where a module lives between 'core' and 'extras'
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your pull request to update the existing module to https://github.com/ansible/ansible-modules-core
- action_plugins (modules with server side components) still live in the main repo.  If your ticket affects both, open the ticket
   on the module repo just the same.

Additionally, should you need more help with this, you can ask questions on:
- the ansible-project mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thank you very much!

**Comment by steenzout** [comment]
note that it seems that it's the remote host who is the one who needs to have psycopg2 installed unless you are doing `connection=local`.

**Comment by olalonde** [comment]
I think I have solved this problem with the following task:

``` yaml
- name: install prerequisites
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  tags:
    - packages
```

**Comment by earldouglas** [comment]
> mpdehaan closed this on Sep 29, 2014

Was this issue migrated to a different repo?  I'm running into it, and can't find a way around it, no matter how I install psycopg2.

**Comment by janewilkin** [comment]
[That task](https://github.com/ansible/ansible/issues/6989#issuecomment-122483368) solved it for me too! Thanks @olalonde !

**Comment by LennyLip** [comment]
@mpdehaan 

I have a question about python3

Install python3-psycopg2

```
- name: Install PostgreSQL
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - python3-psycopg2
```

then

```
- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
```

raise: 
     msg: the python psycopg2 module is required

How i can use http://docs.ansible.com/ansible/postgresql_db_module.html with python3 ?

**Comment by dizlv** [comment]
Any updates on what @LennyLip wrote above?

**Comment by cRyckreator** [comment]
@dizlv   @LennyLip  
Try this when using python3:
```    
    - name: Install PostgreSQL
      apt: name={{ item }} update_cache=yes state=installed
      with_items:
        - postgresql
        - postgresql-contrib
        - python3-psycopg2
```
It worked for me.
