### ISSUE TITLE
netscaler_nitro_request filter only parses the first argument

### ISSUE THREAD

**Issue by JonasVerhofste** [ansible/ansible#69895]
##### SUMMARY
netscaler_nitro_request has a parameter `filter`, that accepts a dict of filter options.
However, the code [only ever parses the first element](https://github.com/ansible/ansible/blob/v2.9.9/lib/ansible/modules/network/netscaler/netscaler_nitro_request.py#L650-L653), whilst it should combine them with an `&` instead.

Could perfectly fix this myself, but I've got no clue where the module is hiding on the devel branch. If someone could point me to it, I'll gladly make that PR.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netscaler_nitro_api

##### ANSIBLE VERSION
2.9.9

##### STEPS TO REPRODUCE
Make a netscaler_nitro_request with operation `get_filtered`

```yaml
- name: Do some filter
  netscaler_nitro_request:
    nsip: mynetscaler.mydomain.mytld
    nitro_user: myuser
    nitro_pass: mypass
    nitro_protocol: https
    operation: get_filtered
    resource: sslcertkey
    filter:
      certificatetype: "{{ '/ROOT_CERT|INTM_CERT/' | urlencode | replace('/', '%2F') }}"
      subject: "{{ '/COMODO/' | replace('/', '%2F') }}"
```
That [urlencode](https://jinja.palletsprojects.com/en/master/templates/#urlencode) would also make more sense to be done in python, rather than in yaml..

##### EXPECTED RESULTS
The request that is sent to netscaler contains all filters. In case of the above:
`https://mynetscaler.mydomain.mytld/nitro/v1/config/sslcertkey?filter=certificatetype:%2FROOT_CERT%7CINTM_CERT%2F&subject:%2FCOMODO%2F`

##### ACTUAL RESULTS
The request only contains the first filter from the dict:
The request that is sent to netscaler contains all filters. In case of the above:
`https://mynetscaler.mydomain.mytld/nitro/v1/config/sslcertkey?filter=certificatetype:%2FROOT_CERT%7CINTM_CERT%2F`
