### ISSUE TITLE
authorized_key no return values in checking mode

### ISSUE THREAD

**Issue by gstorme** [ansible/ansible#69907]
##### SUMMARY

When I run a task using the authorized_key module in checking_mode and register the result, it does not contain any return values.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

authorized_key

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/gregory/.ansible.cfg
  configured module search path = ['/home/gregory/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gregory/.local/lib/python3.7/site-packages/ansible
  executable location = /home/gregory/.local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### STEPS TO REPRODUCE

```yaml
- name: check if an authorized_key change is needed
  authorized_key:
    user: gregory
    key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQB2tZ7l62JQCTgr88sZseQp6L7syhg+a7 Gregory
  check_mode: true
  register: authkey_change

- name: check if a group change is needed for a user
  user:
    name: gregory
    group: gregory
  check_mode: true
  register: group_change

- debug:
    var: authkey_change

- debug:
    var: group_change
```

##### EXPECTED RESULTS

I would expect that the authkey_change variable contains the return values from the `authorized_key` task, like the group_change does have from the `user` task.

##### ACTUAL RESULTS

The authorized_key module does not have any return values in checking_mode.

```yaml
TASK [test : debug] *****************************************************************************************************************************************************************************************************************************************
ok: [buster] => {
    "authkey_change": {
        "changed": false,
        "failed": false
    }
}

TASK [test : debug] *****************************************************************************************************************************************************************************************************************************************
ok: [buster] => {
    "group_change": {
        "append": false,
        "changed": false,
        "comment": "",
        "failed": false,
        "group": 1000,
        "home": "/home/gregory",
        "move_home": false,
        "name": "gregory",
        "shell": "/bin/bash",
        "state": "present",
        "uid": 1000
    }
}
```
