### ISSUE TITLE
Template variables in task tags

### ISSUE THREAD

**Issue by xammi** [ansible/ansible#69916]
##### SUMMARY
A similar problem has been described here - https://github.com/ansible/ansible/issues/69097
One another issue was closed here - https://github.com/ansible/ansible/issues/14384

What this feature request is about:

```bash
# execute tasks only in the webdav role
ansible-playbook --tags="webdav" 

# execute all tasks tagged by "config" in all roles in the playbook
ansible-playbook --tags="config"

# execute all tasks tagged by "config" inside webdav role
ansible-playbook --tags="webdav:config" 

# execute all tasks in webdav role and all tasks tagged by "config" in all roles in playbook
ansible-playbook --tags="webdav,config"
```

These execution commands work as I expect with **import_tasks: file**, but not with **import_role: tasks_from**, because **import_role** can be (and expected to be) used many times from many other roles.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

```
lib/ansible/playbooks/taggable.py
lib/ansible/plugins/strategy/__init__.py
```

##### ADDITIONAL INFORMATION

An example of task inside the imported role (it's named base_app):
```yaml
- name: "set nginx conf for {{ app_name }}"
  tags:
    - nginx
    - config
    - "{{ app_name }}:config"   # not working
  template:
    src: "nginx.j2"
    dest: "/etc/nginx/conf.d/{{ domain }}"
  notify:
   - "reload nginx for {{ app_name }}"

--- more tasks with different tags
```
Template variable "app_name" will not be calculated by ansible.

An example of usage inside webdav role:
```yaml
- name: "configure nginx"
  tags:
    - "webdav:nginx"
  import_role:
    name: 'apps/base_app'
    tasks_from: nginx.yml

--- more tasks and imports
```

An example of playbook:
```yaml
- name: "code cluster deploy"
  hosts: [...]
  roles:
    - {
      role: 'apps/webdav',
      tags: webdav
    }
    --- more roles in PLAY with different tags
```
