### ISSUE TITLE
Problem with acme_certificate and pending authorizations.

### ISSUE THREAD

**Issue by ankerstal** [ansible/ansible#69932]
##### SUMMARY
I've been using acme_certificate for a while now but since upgrading to ansible 2.9 I dont get a certificate anymore. There seems to be a problem with the challange data I get from the module. 

When I try to validate my challanges using DNS I get two sets och different tokens. First I get a list of pending auths: 
```json
    "authorizations": {
        "git.pean.org": {
            "challenges": [
                {
                    "status": "pending",
                    "token": "XXX",
                    "type": "http-01",
                    "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxx/xxx"
                },
                {
                    "status": "pending",
                    "token": "XXX",
                    "type": "dns-01",
                    "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxx/xxx"
                },
                {
                    "status": "pending",
                    "token": "XXX",
                    "type": "tls-alpn-01",
                    "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/xxx/xxx"
                }
            ],
            "expires": "2020-06-14T08:13:32Z",
            "identifier": {
                "type": "dns",
                "value": "git.pean.org"
            },
            "status": "pending",
            "uri": "https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx"
        }
```
But in the challange_data I get another set:
```json
    "challenge_data_dns": {
        "_acme-challenge.git.pean.org": [
            "YYY"
        ]
 },
```

My guess is that the problem is that I have the wrong dns records in DNS. But the validation task does not fail. It just doesnt write any certificates to disk and my authorizations is still pending.
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
acme_certificate

##### ANSIBLE VERSION

```
ansible 2.9.7
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/local/share/py37-ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 21 2020, 01:20:51) [Clang 8.0.1 (tags/RELEASE_801/final 366581)]
```

##### CONFIGURATION

```
CACHE_PLUGIN(/usr/local/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/usr/local/etc/ansible/ansible.cfg) = /usr/local/etc/ansible/cache
DEFAULT_GATHERING(/usr/local/etc/ansible/ansible.cfg) = smart
DEFAULT_MANAGED_STR(/usr/local/etc/ansible/ansible.cfg) = Ansible managed: {file}
RETRY_FILES_ENABLED(/usr/local/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

In the playbooks I use this tasks to create certificate request
```yaml
  - name: Create Certificate request
    openssl_csr:
      path: /etc/ssl/{{ item.name }}.csr
      privatekey_path: /etc/ssl/{{ item.name }}.key
      common_name: "{{ item.name }}"
      subject_alt_name: "{{ item.alt_names|map('regex_replace', '^', 'DNS:')|join(',') }}"
    loop: "{{ certs|flatten(levels=1) }}"

  - name: Create ACME challenge
    acme_certificate:
      account_key_content: "{{ letsencrypt_account_key }}"
      account_email: "{{ admin_email }}"
      src: /etc/ssl/{{ item.name }}.csr
      cert: /etc/ssl/{{ item.name }}.crt
      challenge: dns-01
      acme_directory: https://acme-v02.api.letsencrypt.org/directory
      remaining_days: "{{ letsencrypt_renew_days }}"
      acme_version: 2
      terms_agreed: yes
      force: yes
    register: challenge
    notify: "new letsencrypt cert"
    loop: "{{ certs }}"

  - meta: flush_handlers
```
and then I use handlers to create dns records and validate the challange
```yaml
  - name: Certloop
    include_tasks: acme_validation.yaml
    with_items: "{{ challenge.results }}"
    loop_control:
      loop_var: cert
    listen: "new letsencrypt cert"
    
  - name: resign zones
    command: ods-signer sign --all
    delegate_to: "{{ item }}"
    with_items: "{{ groups['master'] }}"
    listen:
      - "new letsencrypt cert"
      - "new tlsa"
      - "new sshfp"
  
  - name: restart nsd on master
    command: nsd-control reload
    delegate_to: "{{ item }}"
    with_items: "{{ groups['master'] }}"
    listen:
      - "new letsencrypt cert"
      - "new tlsa"

  - name: Let DNS propagate
    pause:
      seconds: 20
    listen: "new letsencrypt cert"

  - name: Let the challenge be validated and retrieve the cert and intermediate certificate
    acme_certificate:
      account_key_content: "{{ letsencrypt_account_key }}"
      account_email: "{{ admin_email }}"
      src: /etc/ssl/{{ item.name }}.csr
      dest: /etc/ssl/{{ item.name }}.crt
      fullchain_dest: /etc/ssl/{{ item.name }}-fullchain.crt
      challenge: dns-01
      acme_directory: https://acme-v02.api.letsencrypt.org/directory
      remaining_days: "{{ letsencrypt_renew_days }}"
      data: "{{ challenge }}"
      acme_version: 2
      deactivate_authzs: yes
    with_items: "{{ certs }}"
    when: challenge is changed
    notify: restart tls services
    listen: "new letsencrypt cert"
```

This is the part where I add the DNS records:
```yaml
  - name: Create DNS validation record
    lineinfile:
      path: /usr/local/etc/nsd/zones/{{ item.key | regex_replace('.*\.(\w+\.\w+)$', '\1') }}
      regexp: '^{{ item.key }}'
      line: "{{ item.key }}. IN TXT {{ item.value[0] | regex_replace('^(.*)$', '\"\\1\"') }}"
    with_dict: "{{ cert.challenge_data_dns }}"
    delegate_to: "{{ groups.master[0] }}"
```
