### ISSUE TITLE
ansible_distribution_release is wrongly set

### ISSUE THREAD

**Issue by Altiire** [ansible/ansible#69946]
##### SUMMARY

Unable to add apt repository because apt cache update failed. Module args are wrong.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

apt_repository

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/altiire/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o StrictHostKeyChecking=accept-new
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'gcp_compute', u'host_list', u'yaml']
```

##### OS / ENVIRONMENT

Ansible running from my computer, Windows 10 with WSL 2 running Debian
On remote host, Debian 9

##### STEPS TO REPRODUCE

```yaml
- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: true
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
```

```
ansible preprod.example.com -i inventories/staging -m setup | grep ansible_distribution
[WARNING]: Platform linux on host preprod.example.com is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
        "ansible_distribution": "Debian", 
        "ansible_distribution_file_parsed": true, 
        "ansible_distribution_file_path": "/etc/os-release", 
        "ansible_distribution_file_variety": "Debian", 
        "ansible_distribution_major_version": "9", 
        "ansible_distribution_release": "stretch", 
        "ansible_distribution_version": "9.12", 
```

##### EXPECTED RESULTS

Docker repository should be added to source list

##### ACTUAL RESULTS

```paste below
TASK [common : Add Docker repository] ******************************************************************************************************************************************************************************
task path: /home/altiire/admin-playbooks/roles/common/tasks/docker.yml:18
<preprod.example.com> ESTABLISH LOCAL CONNECTION FOR USER: altiire
<preprod.example.com> EXEC /bin/sh -c 'echo ~altiire && sleep 0'
<preprod.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/altiire/.ansible/tmp `"&& mkdir /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196 && echo ansible-tmp-1591621439.27-4956-188561437545196="` echo /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt_repository.py
<preprod.example.com> PUT /home/altiire/.ansible/tmp/ansible-local-3984hvbwTP/tmpdQYaC4 TO /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196/AnsiballZ_apt_repository.py
<preprod.example.com> EXEC /bin/sh -c 'chmod u+x /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196/ /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196/AnsiballZ_apt_repository.py && sleep 0'
<preprod.example.com> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-edbzikijwckuqewbazhrfzqzyjlhebdr ; /usr/bin/env python3 /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196/AnsiballZ_apt_repository.py'"'"' && sleep 0'
<preprod.example.com> EXEC /bin/sh -c 'rm -f -r /home/altiire/.ansible/tmp/ansible-tmp-1591621439.27-4956-188561437545196/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_apt_repository_payload_2vpug6hp/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 591, in update
    raise FetchFailedException()
fatal: [preprod.example.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "codename": null, 
            "filename": null, 
            "install_python_apt": true, 
            "mode": null, 
            "repo": "deb [arch=amd64] https://download.docker.com/linux/debian buster stable", 
            "state": "present", 
            "update_cache": true, 
            "validate_certs": true
        }
    }, 
    "msg": "apt cache update failed"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt_repository.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt_repository.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @Altiire Thanks for reporting. The issue is not a module related. I think you are missing the following before running it:

```yaml
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
```

Could you please check? Thank you!

**Comment by Altiire** [comment]
Hi @imjoseangel ,

apt_key is the previous task:

```
- name: Add Docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present
  become: yes
  when: proxy is none and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Add Docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present
  become: yes
  when: proxy is not none and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  environment:
    HTTP_PROXY: "{{ proxy }}"
    HTTPS_PROXY: "{{ proxy }}"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: true
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
```

**Comment by imjoseangel** [comment]
With the same versions I can reproduce only the scenario when the key has not been properly added:

```bash
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_apt_repository_payload_laPwvc/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 591, in update
    raise FetchFailedException()
```

When adding the key, everything works like a charm:

```yaml
---
- name: Ansible Test
  hosts: all
  gather_facts: true

  tasks:

    - name: Add Docker apt key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
        state: present
      become: yes
      when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
        state: present
        update_cache: true
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
```

**Comment by Altiire** [comment]
gather_facts is enabled:

```
TASK [Gathering Facts] *****************************************************
ok: [preprod.example.com]
TASK [common : Add Docker apt key] *****************************************
ok: [preprod.example.com]
TASK [common : Add Docker apt key] *****************************************
skipping: [preprod.example.com]
TASK [common : Add Docker repository] **************************************
fatal: [preprod.example.com]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
```

**Comment by PisikeSipelgas** [comment]
I have similar experience with apt_repository. 
Task goes like that:

```
- name: "/etc/apt/sources.list.d/local-ubuntu.list: ... main restricted universe multiverse"
  apt_repository:
    repo: deb [ arch=amd64 ] http://debianrepo.example.com/ubuntu/ {{ ansible_distribution_release}} main 
    state: present
    filename: local-ubuntu
```

Produces error:

```
The full traceback is:
  File "/tmp/ansible_apt_repository_payload_dnb6kc95/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 591, in update
    raise FetchFailedException(e)
fatal: [192.168.1.7]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": "kemit-ubuntu",
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [ arch=amd64 ] http://debianrepo.example.com/ubuntu/ focal main",
            "state": "present",
            "update_cache": true,
            "validate_certs": false
        }
    },
    "msg": "apt cache update failed"
}
```

Expected repo file /etc/apt/sources.list.d/local-ubuntu.list is not created and repo is not present. So the "apt update" fails.
Now in my case changing from "update_cache: true,"  to "false" allows repo file to be created.

````
- name: "/etc/apt/sources.list.d/local-ubuntu.list: ... main restricted universe multiverse"
  apt_repository:
     repo: deb [ arch=amd64 ] http://debianrepo.example.com/ubuntu/ {{ ansible_distribution_release}} main 
     state: present
     update_cache: false
     filename: local-ubuntu
````
And debug output:

```
changed: [192.168.1.7] => {
    "changed": true,
    "diff": {},
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": "local-ubuntu",
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [ arch=amd64 ] http://debianrepo.example.com/ubuntu/ focal main",
            "state": "present",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "repo": "deb [ arch=amd64 ] http://debianrepo.example.com/ubuntu/ focal main",
    "state": "present"
}
```

**Comment by samdoran** [comment]
This looks like a failure to update the apt cache. Cache update retrying was added in #57266. Please try with Ansible 2.10 and see if that resolves the issue.

needs_info

**Comment by samdoran** [comment]
The distribution information looks correct in my testing.

```
> ansible --version
ansible 2.9.9
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = ['/Users/sdoran/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 3.9.0 (default, Oct 14 2020, 11:40:34) [Clang 12.0.0 (clang-1200.0.32.2)]

> ansible -c community.docker.docker -i 51654cc2ff58, -m setup -a 'filter=ansible_distribution*' all
51654cc2ff58 | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "Debian",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Debian",
        "ansible_distribution_major_version": "9",
        "ansible_distribution_release": "stretch",
        "ansible_distribution_version": "9.12",
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false
}

```

Test playbook:

```yaml
- hosts: all
  connection: community.docker.docker
  gather_facts: yes
  become: yes

  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts.distribution|lower }} {{ ansible_facts.distribution_release|lower }} stable"
        state: present
        update_cache: true
```

Partial output:

```
TASK [Add Docker repository] **************************************************************************************
task path: /Users/sdoran/Projects/Vagrant/Ansible Lab/test-container.yml:15
<51654cc2ff58> ESTABLISH DOCKER CONNECTION FOR USER: root
<51654cc2ff58> EXEC ['/usr/local/bin/docker', b'exec', b'-i', '51654cc2ff58', '/bin/sh', '-c', "/bin/sh -c 'echo ~ && sleep 0'"]
<51654cc2ff58> EXEC ['/usr/local/bin/docker', b'exec', b'-i', '51654cc2ff58', '/bin/sh', '-c', '/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549 && echo ansible-tmp-1611249180.098366-78235-248785763249549="` echo /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549 `" ) && sleep 0\'']
Using module file /Users/sdoran/Source/ansible/lib/ansible/modules/packaging/os/apt_repository.py
<51654cc2ff58> PUT /Users/sdoran/.ansible/tmp/ansible-local-78048ikzbt55k/tmphbq52cjk TO /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549/AnsiballZ_apt_repository.py
<51654cc2ff58> EXEC ['/usr/local/bin/docker', b'exec', b'-i', '51654cc2ff58', '/bin/sh', '-c', "/bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549/ /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549/AnsiballZ_apt_repository.py && sleep 0'"]
<51654cc2ff58> EXEC ['/usr/local/bin/docker', b'exec', b'-i', '51654cc2ff58', '/bin/sh', '-c', '/bin/sh -c \'sudo -H -S -n  -u root /bin/sh -c \'"\'"\'echo BECOME-SUCCESS-zxrezdqlwuvtxthhwfyxetydxwkjcflc ; /usr/bin/python /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549/AnsiballZ_apt_repository.py\'"\'"\' && sleep 0\'']
<51654cc2ff58> EXEC ['/usr/local/bin/docker', b'exec', b'-i', '51654cc2ff58', '/bin/sh', '-c', "/bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1611249180.098366-78235-248785763249549/ > /dev/null 2>&1 && sleep 0'"]
changed: [51654cc2ff58] => {
    "changed": true,
    "diff": {},
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": null,
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable",
            "state": "present",
            "update_cache": true,
            "validate_certs": true
        }
    },
    "repo": "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable",
    "state": "present"
}
```

On the container:

```
root@51654cc2ff58:/# cat /etc/apt/sources.list.d/download_docker_com_linux_debian.list
deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
```
