### ISSUE TITLE
Environment variable leakage in command line parameters on multi-user systems

### ISSUE THREAD

**Issue by Barro** [ansible/ansible#69961]
##### SUMMARY

I reported this issue to Ansible security and it resulted just in a documentation update <https://github.com/ansible/ansible/pull/69618>. I would like to bring this issue up in wider community, as I don't think it's good that the internal implementation of Ansible breaks the basic assumption on how environment variables are visible to other domains. And that it is not very well documented and that all suggested workarounds to run individual commands require Ansible module implementation knowledge or are much more cumbersome than by default using the "command" or "shell" modules.

Ansible leaks task environment variables as "ssh" and "sh" commands' parameters on both of "shell" and "command" modules. And likely on many more, as these environment variable values are set as command line parameters to the shell command that executes the Python interpreter and final command that Ansible uses. This is an issue on multi-user systems where users can see each other's processes that are either running Ansible playbooks or are the hosts that Ansible is managing.

Passing environment variables as command line parameters leads into CWE-214 <https://cwe.mitre.org/data/definitions/214.html> type of situation when there are commands that Ansible executes that take their secrets through environment variables to avoid storing them on the machine for various reasons. This is completely reasonable approach of avoiding leaking secrets to other users and users of Ansible may assume this also to hold true for Ansible, as it holds true everywhere else.

Following playbook demonstrates the issue:

```yaml
---
- name: Demonstrate CWE-214 with Ansible
  hosts: remote-host.example.com
  gather_facts: no
  become: no

  tasks:

    - name: leak secrets with command module
      command:
        cmd: sleep 30
      environment:
        SECRET_VARIABLE: qwertyuiop
```

Then let's see the process listings on the host that executes Ansible playbooks and on the host that is being managed.

```
# playbook executing host:
ssh <ssh-options> remote-host.example.com /bin/sh -c 'SECRET_VARIABLE=qwertyuiop /usr/bin/python3 && sleep 0'

# Ansible managed host:
/bin/sh -c SECRET_VARIABLE=qwertyuiop /usr/bin/python3 && sleep 0
```

In this context I would expect that also environment variables would go through the Python subsystem, as the actual shell command goes through.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
command module
shell module
Likely all other modules that consume environment variables.

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu Linux 18.04.

##### STEPS TO REPRODUCE

```yaml
---
- name: Demonstrate CWE-214 with Ansible
  hosts: remote-host.example.com
  gather_facts: no
  become: no

  tasks:

    - name: leak secrets with command module
      command:
        cmd: sleep 30
      environment:
        SECRET_VARIABLE: qwertyuiop
```

##### EXPECTED RESULTS

I would expect that `SECRET_VARIABLE` would not be exposed to other users.

##### ACTUAL RESULTS

```paste below
# playbook executing host:
ssh <ssh-options> remote-host.example.com /bin/sh -c 'SECRET_VARIABLE=qwertyuiop /usr/bin/python3 && sleep 0'

# Ansible managed host:
/bin/sh -c SECRET_VARIABLE=qwertyuiop /usr/bin/python3 && sleep 0
```
