### ISSUE TITLE
version compare returns false when comparing 2.9.9 < 2.10.

### ISSUE THREAD

**Issue by Jim-Ivey** [ansible/ansible#69975]
##### SUMMARY
In Ansible version 2.9.9, the following assertion fails:
```
      assert:
        that: ansible_version is version('2.10', '<')
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`assert` module, `version` test

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/.../ansible/packer/ansible.cfg
  configured module search path = [u'/home/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/home/...ansible/packer/ansible.cfg) = -F /dev/null
DEFAULT_BECOME(/home/.../ansible/packer/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/.../ansible/packer/ansible.cfg) = [u'/home/.../ansible/roles']
```

##### OS / ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

##### STEPS TO REPRODUCE

Include the following in a playbook:

```yaml
      assert:
        that: ansible_version is version('2.10', '<')
        msg:
          - You must use an Ansible version that less than {{ ansible_version_not_yet }}.
          - Your version of Ansible is {{ ansible_version.full }}.
          - Refer to ansible/README.md for upgrading information.
```

##### EXPECTED RESULTS

```
ok: [localhost] => changed=false 
  msg: All assertions passed
```

##### ACTUAL RESULTS

The assertion failed.

```paste below
task path: /home/.../ansible/includes/verify-ansible.yml:19
fatal: [localhost]: FAILED! => changed=false 
  assertion: ansible_version is version('2.10', '<')
  evaluated_to: false
  msg:
  - You must use an Ansible version that less than 2.10.
  - Your version of Ansible is 2.9.9.
  - Refer to ansible/README.md for upgrading information.
```

##### Variations Attempted

Other things I've tried without success:
- `ansible_version is version(''2.10'', operator=''lt'', strict=True)`
- `ansible_version is version(''2.10'', operator=''le'', strict=True)`
- `ansible_version is version(''2.10.0'', operator=''le'', strict=True)`

```
fatal: [localhost]: FAILED! => 
  msg: 'The conditional check ''ansible_version is version(''2.10.0'', operator=''le'', strict=True)'' failed. The error was: Version comparison: invalid version number ''{''major'': 2, ''full'': ''2.9.9'', ''string'': ''2.9.9'', ''minor'': 9, ''revision'': 9}'''                                                                                                                                       
```

##### Known workaround
The following works, though we'd prefer to use the `version()` test properly.

```
assert:
  that: ansible_version.major == 2 and ansible_version.minor == 9
```
