### ISSUE TITLE
Allow suppression of logging of with_items/with_dict debug output

### ISSUE THREAD

**Issue by bloodearnest** [ansible/ansible#6998]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.5.3
##### Environment:

Ubuntu 12.04
##### Summary:

Add ability to suppress logging of with_items/with_dict iterations
##### Steps To Reproduce:

Have an action that uses with_items and allow for suppression of loop param output when using no_log: True to protect sensitive info.

```
 - name: some task
   no_log: True
   copy: content="{{ item.content }}" dest="{{ item.path }}"
   with_items:
     - {{ content: "{{ secret1 }}", path: "/foo" }}
     - {{ content: "{{ secret2 }}", path: "/bar" }}
```
##### Expected Results:

Have the item output suppressed.

186 2014-04-15 15:56:08 INFO TASK: [some task] **********************************************************·
187 2014-04-15 15:56:08 INFO changed: [localhost] => (item=&lt;suppressed&gt;)
188 2014-04-15 15:56:08 INFO changed: [localhost] => (item=&lt;suppressed&gt;)
##### Actual Results:

186 2014-04-15 15:56:08 INFO TASK: [some task] **********************************************************·
187 2014-04-15 15:56:08 INFO changed: [localhost] => (item={'content': 'secret1', 'path': '/foo'})
188 2014-04-15 15:56:08 INFO changed: [localhost] => (item={'content': 'secret2', 'path': '/bar'})

Currently, this forces me to split into individual repetitive actions to avoid.

Thanks
