### ISSUE TITLE
file module to support asterisk pattern expansion

### ISSUE THREAD

**Issue by ainiml** [ansible/ansible#69988]
##### SUMMARY

It seems that when using an `*` in the `path` it is taking the path literally, and not expanding it out to match other files. 

The file doesn't get deleted, and all matching files aren't deleted either

```
    - name: Delete files
      file:
        path: /path/to/files*
        state: absent
```

```
TASK [Delete files] *************************************************************
ok: [localhost]
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

file
