### ISSUE TITLE
paramiko_conn is not getting initialised with net_get/net_put modules

### ISSUE THREAD

**Issue by wisotzky** [ansible/ansible#69990]
##### SUMMARY
Both net_get and net_put run into errors

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Plugin cliconf
Plugin connection/network_cli

##### ANSIBLE VERSION
```ansible 2.9.5```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: nokia
  vars:
    - ansible_network_os: nokia.sros.md
  vars_prompt:
    - name: ansible_user
      prompt: "Username"
      private: no
    - name: ansible_password
      prompt: "Password"
  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
  - name: download file
    net_get:
       src: "cf3://NVRAM.dat"
       protocol: sftp

  - name: upload file
    net_put:
       src: "test.txt"
       dest: "cf3://test.txt"
       mode: binary
       protocol: sftp
...
```

##### EXPECTED RESULTS
Files getting transferred.

##### ACTUAL RESULTS
```
fatal: [135.228.152.229]: FAILED! => {"changed": true, "destination": "/Users/wiso/.ansible/collections/ansible_collections/nokia/sros/playbooks/NVRAM.dat", "msg": "Exception received : 'NoneType' object has no attribute '_connect_uncached'"}
```

Error happens because of:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/__init__.py#L343
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/cliconf/__init__.py#L364

Using the example playbook, the CLI connection is not established. In `plugins/connection/network_cli.py` it looks like that the constructor initialised `self.paramiko_conn` with value `None`. If and only if a connection is established using the `_connect` method, this variable is getting initialised:

```
         if not self.connected:
             self.paramiko_conn = connection_loader.get('paramiko', self._play_context, '/dev/null')
``` 

In conclusion if the connection was not established before, the following lines will run into an error as the member variable `paramiko_conn` is not set:

```
 ssh = self._connection.paramiko_conn._connect_uncached()
```

As a workaround one can add a simple CLI command to make sure that the session is initialised and paramiko_conn is defined:

```yaml
---
- hosts: nokia
  vars:
    - ansible_network_os: nokia.sros.md
  vars_prompt:
    - name: ansible_user
      prompt: "Username"
      private: no
    - name: ansible_password
      prompt: "Password"
  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
  - name: get system information
    cli_command:
      command: show system information

  - name: download file
    net_get:
       src: "cf3://NVRAM.dat"
       protocol: sftp

  - name: upload file
    net_put:
       src: "test.txt"
       dest: "cf3://test.txt"
       mode: binary
       protocol: sftp
...
```
