### ISSUE TITLE
VMware: vmware_guest module does not set network for RHEL 8 images

### ISSUE THREAD

**Issue by saravananoff** [ansible/ansible#70001]
##### SUMMARY

While using vmware_guest to clone RHEL 8 from template the network configuration is being ignored. Same parameters input works for RHEL 7. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest.py
##### ANSIBLE VERSION

```paste below
 ansible 2.9.6
   config file = /etc/ansible/ansible.cfg
   configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
   executable location = /usr/local/bin/ansible
   python version = 3.8.2 (default, Feb 26 2020, 14:58:38) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cloning VM from template using ansible vmware_guest module. Executed through Debian 10 docker container.

##### STEPS TO REPRODUCE

Clone RHEL 8 VM from template using below task with parameters

```yaml
  vmware_guest: 
    validate_certs: false
    hostname: "{{ vCenter }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    esxi_hostname: "{{ VirtualHost }}"
    datacenter: "{{ Datacenter }}"
    folder: "{{ VMFolder }}"
    resource_pool: "{{ ResourcePool }}"
    name: "{{ server_name }}"
    template: "{{ VMTemplate }}"
    state: poweredon
    disk: 
      - size_gb: "{{ os_disk_size }}"
        type: eagerzeroedthick
        datastore: "{{ OSDatastoreName }}"
        autoselect_datastore: false
    hardware: 
      memory_mb: "{{ memorymb }}"
      num_cpus: "{{ numcpus }}"
    networks: 
      - device_type: vmxnet3
        gateway: "{{ Gateway }}"
        ip: "{{ IPAddress }}"
        name: "{{ PortGroup }}"
        netmask: "{{ Subnet }}"
        start_connected: true
        type: static
    wait_for_ip_address: true
    customization: 
      hostname: "{{ server_name|lower }}"
      dns_servers: 
        - "{{ DNS1 }}"
        - "{{ DNS2 }}"
      dns_suffix:
        - lan.net
        - lan.com            
      Timezone: 20
  delegate_to: localhost  
```

##### EXPECTED RESULTS

VM must be configured with provided IP address and network must be connected.

##### ACTUAL RESULTS

Network configurations are ignored, Ip address not assigned to VM and network adapter not connected to VM (disconnected state even though stay_connected is set to true)

```paste below

```
