### ISSUE TITLE
Add b64decode option directly to Slurp

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#70004]
##### SUMMARY

It is making templates un-readably messy to repeatedly add
```ansible
{{ myvar.content | b64decode | trim }}
```
rather than just
```ansible
{{ myvar.content }}
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Slurp

##### ADDITIONAL INFORMATION

```yaml
- name: My example raw Slurp task
  slurp:
    src: /path/to/my/file
    raw: true
```
