### ISSUE TITLE
apt module in upgrade cases should avoid using the shell

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#7001]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

ubuntu
##### Summary:

See this thread:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/82Sm5K-9Zxs/2Gf0VrPL4uYJ

This command wasn't being run through the shell, on line 277 is the main problem.

We could pass "use_unsafe_shell=True" here, but that's not ideal.  Better would be to set the various environment options directly and then call the command not using the shell.
##### Steps To Reproduce:

```
  tasks:
    - name: apt-get update
      apt: update_cache=yes

    - name: apt-get dist-upgrade
      apt: upgrade=dist dpkg_options='force-confold,force-confdef'

    - name: reboot
      command: '/sbin/reboot'
```
##### Expected Results:

Task succeeds
##### Actual Results:

```
TASK: [apt-get dist-upgrade] **************************************************
<10.0.20.4> REMOTE_MODULE apt upgrade=dist dpkg_options='force-confold,force-confdef'
<10.0.20.67> REMOTE_MODULE apt upgrade=dist dpkg_options='force-confold,force-confdef'
failed: [10.0.20.4] => {"cmd": ["DEBIAN_FRONTEND=noninteractive", "DEBIAN_PRIORITY=critical", "/usr/bin/apt-get", "-y", "-o", "Dpkg::Options::=--force-confold", "-o", "Dpkg::Options::=--force-confdef", "dist-upgrade"], "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory
```
