### ISSUE TITLE
docker_image fails to retag when name has integer tag

### ISSUE THREAD

**Issue by yselkowitz** [ansible/ansible#70041]
##### SUMMARY
In the `docker_image` module, retagging an image by specifying both `name` and `repository` fails when `name` includes an integer tag.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```paste below
ansible 2.9.9
  config file = /home/yselkowi/src/newarches-playbooks/ansible.cfg
  configured module search path = ['/home/yselkowi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/home/yselkowi/src/newarches-playbooks/ansible.cfg) = ['/home/yselkowi/src/newarches-playbooks/inventory/hosts']
```

##### OS / ENVIRONMENT
controller: Fedora 31, Moby Engine 19.03.8, Python 3.7.7, python3-docker 4.0.2 (for localhost testing)
node: both localhost and also on RHEL 7 with Docker 1.13.1, Python 2.7.5, python-docker-py 1.10.6

##### STEPS TO REPRODUCE
With the docker_image module, pass both a name with an integer tag, and any value of repository; it doesn't matter whether the image has already been pulled or not, e.g.:

```yaml
---
- name: test docker_image bug
  hosts: localhost
  tasks:
  - name: pull docker image
    docker_image: 
      name: registry.redhat.io/ubi8/nodejs-10:1 # quotes do not help
      # pull works without retagging, but this breaks, and tag does not matter:
      repository: ubi8/nodejs-10:foo
      source: pull
```

##### EXPECTED RESULTS
The image should be both pulled (if not already present) and retagged, and both specs should be shown by docker images.

##### ACTUAL RESULTS
Image is correctly pulled if not already present (as can be seen by docker images afterwards) but retagging fails, as if it tries to retag from `:latest` instead of from `:1`

```paste below
The full traceback is:
  File "/tmp/ansible_docker_image_payload_czq4zaxz/ansible_docker_image_payload.zip/ansible/modules/cloud/docker/docker_image.py", line 709, in tag_image
  File "/usr/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/docker/api/image.py", line 546, in tag
    self._raise_for_status(res)
  File "/usr/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "archive_path": null,
            "build": null,
            "buildargs": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "container_limits": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "dockerfile": null,
            "force": null,
            "force_absent": false,
            "force_source": false,
            "force_tag": false,
            "http_timeout": null,
            "load_path": null,
            "name": "registry.redhat.io/ubi8/nodejs-10:1",
            "nocache": false,
            "path": null,
            "pull": null,
            "push": false,
            "repository": "ubi8/nodejs-10:foo",
            "rm": true,
            "source": "pull",
            "ssl_version": null,
            "state": "present",
            "tag": "latest",
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "use_tls": null,
            "validate_certs": false
        }
    },
    "msg": "Error: failed to tag image - 404 Client Error: Not Found (\"No such image: registry.redhat.io/ubi8/nodejs-10:latest\")"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cloud/docker/docker_image.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_image.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @yselkowitz, Thanks for reporting,

Could you please give some more data to try to reproduce the issue?

Personally, I have run the following with different scenarios with no issues:

```yaml
---
- name: Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  vars:

    variable1: value

  tasks:

    - name: Log into private registry and force re-authorization
      docker_login:
        registry: registry.redhat.io
        username: myuser
        password: mypass
        reauthorize: true

    - name: pull docker image
      docker_image:
        name: registry.redhat.io/ubi8/nodejs-10:1 # quotes do not help
        # pull works without retagging, but this breaks, and tag does not matter:
        repository: ubi8/nodejs-10:foo
        source: pull
```

got:

```bash
ubi8/nodejs-10                           foo                                              c380224c08db        9 days ago          746MB
registry.redhat.io/ubi8/nodejs-10        1                                                c380224c08db        9 days ago          746MB
registry.redhat.io/ubi8/nodejs-10        latest                                           c380224c08db        9 days ago          746MB
```
