### ISSUE TITLE
docker_image don't support Docker BuildKit

### ISSUE THREAD

**Issue by allen12921** [ansible/ansible#70065]
##### SUMMARY

docker_image doesn't not support Docker BuildKit 
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.5
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
```

##### OS / ENVIRONMENT

target OS versions: CentOS Linux release 7.8.2003 (Core)
Docer version: 19.03.9

##### STEPS TO REPRODUCE

With Below  content Dockerfile:

```
#syntax=docker/dockerfile:experimental
FROM alpine
RUN apk add --no-cache openssh-client git
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh git clone git@github.com:myorg/myproject.git myproject
```
Then build image with docker_image
```
  - name: build and push rails image
    docker_image:
      name: "test"
      build: 
        dockerfile: Dockerfile
        path: "test"
        pull: yes
      push: yes
      source: build
      force_source: yes
    delegate_to: "localhost"
```

```yaml
ansible-playbook    buikd.yml
```

##### EXPECTED RESULTS

the test image will be build
##### ACTUAL RESULTS

not recognize the mount option when build with ansible while I can build success by  running docker build command directly

```paste below
fatal: [localhost -> localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "An unexpected docker error occurred: 400 Client Error: Bad Request (\"Dockerfile parse error line 5: Unknown flag: mount\")"}

```
