### ISSUE TITLE
Ansible is being run in a world writable directory (/vagrant), ), ignoring it as an ansible.cfg source

### ISSUE THREAD

**Issue by abhishekkarigar** [ansible/ansible#70069]
##### SUMMARY
trying to provision the vagrant guest using ansible_local. 
with ansible provision i was able to do it successfully.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

windows 10 / cygwin /ansible 2.9.x version

##### STEPS TO REPRODUCE

vagrant up 

```yaml
---
- hosts: all
  become: true
  tasks:
    - name: Install NTP
      apt: package=ntp,ntpdate state=present update_cache=yes
      tags: ntp
  
    - name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp

    - name: install JDK 11
      apt:
        name: openjdk-7-jdk
        state: present

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
    
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    
```

##### ACTUAL RESULTS

$ vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' version '20190514.0.0' is up to date...
==> default: Running provisioner: ansible_local...
    default: Running ansible-playbook...
 [WARNING] Ansible is being run in a world writable directory (/vagrant), ignoring it as an ansible.cfg source. For more information see https://
docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 2222: Con
nection refused", "unreachable": true}

PLAY RECAP *********************************************************************
default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
