### ISSUE TITLE
Collections in Roles

### ISSUE THREAD

**Issue by StevenBarre** [ansible/ansible#70083]
> This is expected, please see https://github.com/ansible/ansible/pull/66667

_Originally posted by @sivel in https://github.com/ansible/ansible/issues/68198#issuecomment-598417297_

What version of Ansible does this work in? I'm using 2.9.2 and it is not working for me.

```
# cat roles/trident/metadata/main.yml
collections:
  - netapp.ontap
# cat roles/trident/tasks/main.yaml
- name: Configure iSCSI security
  na_ontap_iscsi_security:
    state: present
    initiator: default
    address_ranges: "{{ ontap.clients }}"
    auth_type: none
```

Still gives me

```
fatal: [localhost]: FAILED! =>
  reason: |-
    couldn't resolve module/action 'na_ontap_iscsi_security'. This often indicates a misspelling, missing collection, or incorrect module path.

    The error appears to be in '/root/platform-ops/ocp4/roles/trident/tasks/main.yaml': line 49, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: Configure iSCSI security
      ^ here
```
