### ISSUE TITLE
RFE: Support success_rcs option for command module to not fail on other return codes than 0

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#70090]
##### SUMMARY

Some tools return a returncode different that 0 even if there was no problem. For example grep returns 1 if there was no match but 2 on errors. Therefore it would be nice to specify success/good return codes for the command module to accept those rcs when they are ok.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

command

##### ADDITIONAL INFORMATION

```yaml
- name: get ETHTOOL opts
  command: grep ^ETHTOOL /etc/sysconfig/network-scripts/ifcfg-eth0
  args:
    success_rcs:
      - 0
      - 1
  register: ethtool
```

success_rcs could also accept `0,1`.
