### ISSUE TITLE
 postgresql_idx does not take case into account for index or table name

### ISSUE THREAD

**Issue by maxbes** [ansible/ansible#70098]
##### SUMMARY

`postgresql_table` considers that table names are case sensitive

however `postgresql_idx` does not consider table names as case sensitive, nor index names, (maybe not column names either)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_idx module

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/maxbes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Ansible client: Debian 10 but should be irrelevant
Target server: RHEL8, using python3-psycopg2-2.8.5-2.rhel8.x86_64

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: no
  tasks:
    - postgresql_table:
        db: postgres
        name: lowertable
        columns: 
         - id int 
      become: yes
      become_user: postgres

    - postgresql_table:
        db: postgres
        name: UPPERTABLE
        columns: 
         - id int 
      become: yes
      become_user: postgres

    - postgresql_idx:
        db: postgres
        table: lowertable
        columns: id
        name: IDX_LOWERTABLE_ID
      become: yes
      become_user: postgres

    - postgresql_idx:
        db: postgres
        table: UPPERTABLE
        columns: id
        name: IDX_UPPERTABLE_ID
      become: yes
      become_user: postgres

```

##### EXPECTED RESULTS

The previous playbook should create two tables: ` UPPERTABLE` and `lowertable`, as well as two indexes, with uppercase names. The playbook should be idempotent.

##### ACTUAL RESULTS

On first run, the index on `lowertable` is created, but with a lowercase name. The index on `UPPERTABLE` fails

On second run, the index on `lowertable` is not found anymore, and the module errs trying to recreate it.

```paste below

## FIRST RUN

PLAY [all] ****************************************************************************************************************

TASK [postgresql_table] ***************************************************************************************************
changed: [postgres]

TASK [postgresql_table] ***************************************************************************************************
changed: [postgres]

TASK [postgresql_idx] *****************************************************************************************************
changed: [postgres]

TASK [postgresql_idx] *****************************************************************************************************
fatal: [postgres]: FAILED! => {"changed": false, "msg": "Cannot execute SQL 'CREATE INDEX CONCURRENTLY IDX_UPPERTABLE_ID ON public.UPPERTABLE USING BTREE (id)': relation \"public.uppertable\" does not exist\n"}

PLAY RECAP ****************************************************************************************************************
postgres                   : ok=3    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


## SECOND RUN

PLAY [all] ****************************************************************************************************************

TASK [postgresql_table] ***************************************************************************************************
ok: [postgres]

TASK [postgresql_table] ***************************************************************************************************
ok: [postgres]

TASK [postgresql_idx] *****************************************************************************************************
fatal: [postgres]: FAILED! => {"changed": false, "msg": "Cannot execute SQL 'CREATE INDEX CONCURRENTLY IDX_LOWERTABLE_ID ON public.lowertable USING BTREE (id)': relation \"idx_lowertable_id\" already exists\n"}

PLAY RECAP ****************************************************************************************************************
postgres                   : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


```

In the end, I solved my issue by using only lowerscore index names and table names. But in my opnion, the various PostgreSQL modules should be more consistent with regard to case handling. If `postgres_table` allows the user to choose table case, `postgres_idx` should as well.

I can work on a PR for this. But I'm not sure which way is the way to go, there might be a lot of possible regressions involved.
