### ISSUE TITLE
parted module wipes partition table

### ISSUE THREAD

**Issue by ei-grad** [ansible/ansible#70101]
```
  - name: create partition for lvm on each nvme
    parted:
      device: "/dev/nvme1n1"
      number: 3
      part_start: 197257216s
      part_end: 100%
      state: present
```

this task results in wiped partition table, which is not the behaviour which should be expected
