### ISSUE TITLE
azure_rm_virtualmachine boot_diagnostics resource group configuration

### ISSUE THREAD

**Issue by broth13** [ansible/ansible#70116]
##### SUMMARY
azure_rm_virtualmachine can currently only specify a boot_diagnostics storage account that exists in the same resource group as the VM itself.  Would like to be able to specify a "resource_group" tag in the "boot_diagnostics" stanza to allow the use of boot diagnostics storage accounts in other resource groups.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine 

##### ADDITIONAL INFORMATION
Sometimes a single storage account is dedicated in a subscription as a shared boot diagnostics repository to consolidate all console log data.  In this case, the boot diagnostics storage account may not necessarily exist in the same resource group as the VM being provisioned.

Currently azure_rm_virtualmachine assumes the boot_diagnostics storage account is in the same resource group, and provisioning yields an error such as the following:

"msg": "Error fetching storage account mybootdiags - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Storage/storageAccounts/mybootdiags' under resource group 'DIFFERENT-RG' was not found."

It would be helpful to be able to specify an optional alternate resource group for the storage account as follows:

```yaml
        boot_diagnostics:                                                                             
          enabled: yes                                                                                
          storage_account: "{{ azure_bootdiag }}"                                                     
          resource_group: "{{ azure_bootdiag_rg }}"

```
