### ISSUE TITLE
Ansible 'replace' unable to find the hidden file paths

### ISSUE THREAD

**Issue by rameshar16** [ansible/ansible#70110]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

replace
##### ANSIBLE VERSION

```paste below
└─> $  ansible --version
ansible 2.9.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS7

##### STEPS TO REPRODUCE

- name: Replace version with new version
  replace:
    path: "/home/user/.env"
    regexp: ^(VERSION=.+)$
    replace: "VERSION={{version}}"
    backup: yes

```
- name: Replace version with new version
  replace:
    path: "/home/user/.env"
    regexp: ^(VERSION=.+)$
    replace: "VERSION={{version}}"
    backup: yes
```

##### EXPECTED RESULTS

replace the matching string in a file
##### ACTUAL RESULTS

```
msg: Path /home/user/.env does not exist !
  rc: 257

```
