### ISSUE TITLE
Problem with "rubrik_assign_sla" with "object_type: mssql_host"

### ISSUE THREAD

**Issue by FrankMauroJr** [ansible/ansible#70128]
##### SUMMARY
When trying to use the module "rubrik_assign_sla" with "object_type: mssql_host" I am getting the following error: **_fatal: [10.176.50.127]: FAILED! => {"changed": false, "msg": "'InvalidParameterException' object has no attribute 'format'"}_**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rubrik_assign_sla   object_type: mssql_host

##### ANSIBLE VERSION
```
ansible 2.9.2
```

##### CONFIGURATION

``` 
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = true
DEFAULT_SSH_TRANSFER_METHOD(/etc/ansible/ansible.cfg) = scp

```

##### STEPS TO REPRODUCE

ansible-playbook ./rubrik.pdc2.nonprod.yml -i host

```yaml

---
- hosts: rubrik_pdc2
  connection: local
  gather_facts: false
  vars:
    node: VMPID-E4DVRT01
    policy: EA_SQL_NONPROD
    credentials:
      username: admin
      password: <am not including password>
      node_ip: 10.176.50.127   #rubrik_pdc2

  tasks:
    - name: get Rubrik
      debug:
        msg: "{{ credentials }}"

#    - name: Rubrik assign policy to server
#      rubrik_assign_sla:
#        provider: "{{ credentials }}"
#        timeout: 60
#        object_name: "{{ node }}"
#        sla_name: "{{ policy }}"
    - name: Rubrik assign policy to SQL
      rubrik_assign_sla:
        provider: "{{ credentials }}"
        timeout: 90
        object_name: "vmpid-e4dvrt01"
        object_type: "mssql_host"
        windows_host: "vmpid-e4dvrt01"
        sla_name: "EA_SQL_NONPROD"
        log_backup_frequency_in_seconds: 120
        log_retention_hours: 12
        copy_only: false


<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
I expected the module to assign a Rubrik policy to the server


##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes -->
```
# ansible-playbook ./rubrik.pdc2.nonprod.yml -i host -vvvv
ansible-playbook 2.9.2
  config file = /home/a0007699/rubrik_install/ansible.cfg
  configured module search path = [u'/home/a0007699/rubrik_install/rubrik-modules-for-ansible/rubrikinc/cdm/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
Using /home/a0007699/rubrik_install/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/a0007699/rubrik_install/host as it did not pass its verify_file() method
script declined parsing /home/a0007699/rubrik_install/host as it did not pass its verify_file() method
auto declined parsing /home/a0007699/rubrik_install/host as it did not pass its verify_file() method
Parsed /home/a0007699/rubrik_install/host inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: rubrik.pdc2.nonprod.yml ****************************************************************************************
Positional arguments: ./rubrik.pdc2.nonprod.yml
become_method: sudo
inventory: (u'/home/a0007699/rubrik_install/host',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in ./rubrik.pdc2.nonprod.yml

PLAY [rubrik_pdc2] *******************************************************************************************************
META: ran handlers

TASK [Rubrik assign policy to SQL] ***************************************************************************************
task path: /home/a0007699/rubrik_install/rubrik.pdc2.nonprod.yml:37
<10.176.50.127> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.176.50.127> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.176.50.127> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938 `" && echo ansible-tmp-1592429172.78-174813897606938="` echo /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938 `" ) && sleep 0'
<10.176.50.127> Attempting python interpreter discovery
<10.176.50.127> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.176.50.127> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<10.176.50.127> Python interpreter discovery fallback (unsupported Linux distribution: oracle)
Using module file /home/a0007699/rubrik_install/rubrik-modules-for-ansible/rubrikinc/cdm/plugins/modules/rubrik_assign_sla.py
<10.176.50.127> PUT /root/.ansible/tmp/ansible-local-13302jlBszR/tmpHRxXtq TO /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938/AnsiballZ_rubrik_assign_sla.py
<10.176.50.127> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938/ /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938/AnsiballZ_rubrik_assign_sla.py && sleep 0'
<10.176.50.127> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938/AnsiballZ_rubrik_assign_sla.py && sleep 0'
<10.176.50.127> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1592429172.78-174813897606938/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_rubrik_assign_sla_payload_1tCRjR/ansible_rubrik_assign_sla_payload.zip/ansible/modules/rubrik_assign_sla.py", line 182, in main
  File "/usr/lib/python2.7/site-packages/rubrik_cdm/data_management.py", line 693, in assign_sla
    "Host ID not found for instance '{}'").format(object_name)

[WARNING]: Platform linux on host 10.176.50.127 is using the discovered Python interpreter at /usr/bin/python, but future
installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

fatal: [10.176.50.127]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": null,
            "copy_only": false,
            "log_backup_frequency_in_seconds": 120,
            "log_retention_hours": 12,
            "node_ip": "10.176.50.127",
            "object_name": "vmpid-e4dvrt01",
            "object_type": "mssql_host",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": {
                "api_token": null,
                "node_ip": "10.176.50.127",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "username": "admin"
            },
            "sla_name": "EA_SQL_NONPROD",
            "timeout": 90,
            "username": "admin",
            "windows_host": "vmpid-e4dvrt01"
        }
    },
    "msg": "'InvalidParameterException' object has no attribute 'format'"
}

PLAY RECAP ***************************************************************************************************************
10.176.50.127              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```
