### ISSUE TITLE
win_dsc: PsCredential exception with null or blank password

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#70140]
##### SUMMARY
PsCredential not working with null or blank password

##### ISSUE TYPE
Abillity to use PsCredential with blank password

##### COMPONENT NAME
win_dsc

##### ADDITIONAL INFORMATION
i'm tried to avoid win_service virtual account bug (fail mapping) with win_dsc + service resource and its also turned out to be fatal.

```yaml
- name: "test-service"
  win_dsc:
    resource_name: Service
    Name: "test-service"
    Path: 'c:\windows\system32\notepad.exe'
    Description: "test"
    StartupType: Automatic
    State: Running
    Credential_username: 'NT Service\test-service'
    Credential_password: '' # or []
```
