### ISSUE TITLE
telnet module string concationation TypeError 

### ISSUE THREAD

**Issue by geexmmo** [ansible/ansible#70166]
##### SUMMARY
telnet.py fails to execute if username or password are numeric AND not quoted in either vault, variables or module parameters inside playbook. Even if you quote variables in module parameters inside of playbook. it looks like there should be type conversion to strings (as Python does when you put numbers in quotes) but it does not happening for some reason.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/commands/telnet.py

##### ANSIBLE VERSION

```ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/geexmmo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

##### CONFIGURATION

```
```
##### OS / ENVIRONMENT
Fresh Archlinux

##### STEPS TO REPRODUCE

```
ansible-playbook playbook.yml -i inventory/hosts.yml --ask-vault-pass -vvv
```
```
playbook.yml
```
```
---
- hosts: office
  vars:
    switch_user: admin
    switch_password: 123
 # password is numeric in this example
  order: inventory
  gather_facts: false
  connection: local
  # vars_files:
  #   - ./vars/vars.yml
  # vars.yml could be used but there is vars: it this example. vars.yml could be vault encrypted too
  tasks:
  - name: Test connection
    telnet:
      host: "{{ inventory_hostname }}"
      user: "{{ switch_user }}"
      password: "{{ switch_password }}"
      login_prompt: "User name: "
      password_prompt: "Password: "
      prompts:
        - "#"
      command:
        - show ip
...
```
```
vars/vars.yml
```
```
switch_user: admin
switch_password: 123
```

##### EXPECTED RESULTS
As vars are quoted in module parameters - there should be no problem with python concatenating it as strings and telnet module should be executed.

##### ACTUAL RESULTS
Play fails with python error because it receives INT and not STRing

```
PLAYBOOK: get-macs.yml ************************************************************************************************************************************************
1 plays in get-macs.yml

PLAY [office] *********************************************************************************************************************************************************
META: ran handlers

TASK [Test connection] ************************************************************************************************************************************************
task path: /home/geexmmo/yess/switches-automation/get-macs.yml:12
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 645, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.8/site-packages/ansible/plugins/action/telnet.py", line 71, in run
    tn.write(to_bytes(password + "\n"))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
fatal: [10.1.2.43]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP ************************************************************************************************************************************************************
10.1.2.43                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
