### ISSUE TITLE
docker stack ls - functionality

### ISSUE THREAD

**Issue by jifox** [ansible/ansible#70165]
##### SUMMARY

I would like to list all stacks like `docker stack ls` in order to run some setup containers if a particular stack is not present.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_stack

##### ADDITIONAL INFORMATION

```yaml
   - name: List all docker stacks
     docker_stack_info:
         stacks: yes      # return list of known stacks
         ...
```
