### ISSUE TITLE
gcp_dns_resource_record_set_facts return allways empty list

### ISSUE THREAD

**Issue by wolmi** [ansible/ansible#70167]
##### SUMMARY

When trying to retrieve current records on a zone it never returns any value because the if on next line is always false:
https://github.com/ansible/ansible/blob/14bcd3b7a307aa1920292e32a021b66cf43eb977/lib/ansible/modules/cloud/google/gcp_dns_resource_record_set_facts.py#L116

It is caused because the collection function has the wrong endpoint
https://github.com/ansible/ansible/blob/14bcd3b7a307aa1920292e32a021b66cf43eb977/lib/ansible/modules/cloud/google/gcp_dns_resource_record_set_facts.py#L126
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
gcp_dns_resource_record_set_facts.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.12
  config file = None
  configured module search path = ['/Users/miquel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible@2.8/2.8.12_1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/opt/ansible@2.8/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### OS / ENVIRONMENT

Tested on Linux and MacOS

##### STEPS TO REPRODUCE

```yaml
---
- name: Update SRV records
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "get info on a managed zone"
      gcp_dns_managed_zone_facts:
        dns_name: somedoman.internal.
        project: mashmetv
        auth_kind: serviceaccount
        service_account_file: "./credentials.json"
      register: zone
    - debug: var=zone
    - name: Get info on a resource record set
      gcp_dns_resource_record_set_facts:
        #managed_zone: "{{ zone['items'][0] }}"
        managed_zone:
          name: mashme-internal
        project: mashmetv
        auth_kind: serviceaccount
        service_account_file: "./credentials.json"
      register: records
    - debug: var=records
```
##### EXPECTED RESULTS

The expected results is to see the content of records as a list of all the resource record on the zone

##### ACTUAL RESULTS

Only an empty list is returned

```paste below
ok: [localhost] => {
    "records": {
        "changed": false,
        "failed": false,
        "items": []
    }
}
```
