### ISSUE TITLE
`with_file` doesn't support variables like `with_items`

### ISSUE THREAD

**Issue by sephii** [ansible/ansible#7016]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.4
##### Environment:

N/A
##### Summary:

`with_items` allows you to write `with_items: my_var`, which will use the content of the variable as items. `with_file` however doesn't allow you to do that, interpreting `with_file: my_var` as 

```
with_file:
  - my_var
```

So there's no way to use `with_file` with variables.
##### Steps To Reproduce:

Create 2 blank files `foo` and `bar` and a playbook with a simple task and run it:

```

---
- hosts: all
  vars:
    authorized_key_files:
      - bar
      - baz
  tasks:
  - name: create authorized_keys file
    authorized_key: "user=foo key='{{ item }}'"
    with_file: authorized_key_files
```
##### Expected Results:

The files `foo` and `bar` are copied into `/home/foo/.ssh/authorized_keys`.
##### Actual Results:

The following error occurs:

```
fatal: [root@...] => /home/user/ansible/authorized_keys_files does not exist
```
