### ISSUE TITLE
AWS Dynamic inventory returns empty for af-south-1 region

### ISSUE THREAD

**Issue by arossouw** [ansible/ansible#70164]
##### SUMMARY

When I try to get a list of ec2 instances with ec2.py --list, when I have a ec2 instance active on AWS, within the af-south-1 region. I get the following output:
{
  "_meta": {
    "hostvars": {}
  }
}

When I stop that instance and create an instance in the ohio (us-east-2) region. I do get
the expected output of ec2 instances.

I've set ec2.ini to region=all

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Amazon EC2

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/arno/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 24 2020, 11:13:41) [Clang 11.0.0 (clang-1100.0.33.12)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Mac OS Catalina

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  gather_facts: yes
  user: ubuntu
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"
  become: yes
  tasks:
     - shell: /usr/bin/uptime
       register: result
     - debug:
         var: result
         verbosity: 2
     - name: create a test file
       file:
         path: "/home/ubuntu/testfile.txt"
         state: touch

```

##### EXPECTED RESULTS

Expected ec2.py --list to return a list of ec2 instances when I have a instance
running within the af-south-1 region.

##### ACTUAL RESULTS

Get an empty list when running ec2.py --list

```paste below
ec2.py --list
```
