### ISSUE TITLE
Azure image gallery version can't set exclude_from_latest to false

### ISSUE THREAD

**Issue by jghal** [ansible/ansible#70187]
##### SUMMARY

Setting `publishing_profile.exclude_from_latest: false` in `azure_rm_galleryimageversion` task produces bad API call resulting in task failure.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_galleryimageversion

##### ANSIBLE VERSION

```bash
ansible 2.9.9
  config file = /work/ict-provisioner/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
```

##### CONFIGURATION

```bash 
DEFAULT_CALLBACK_WHITELIST(/work/ict-provisioner/ansible.cfg) = ['time', 'profile_tasks']
HOST_KEY_CHECKING(/work/ict-provisioner/ansible.cfg) = False
INTERPRETER_PYTHON(/work/ict-provisioner/ansible.cfg) = /usr/bin/python
```

##### OS / ENVIRONMENT

Play `hosts` is localhost, which is an Alpine 3.11 derivative container

##### STEPS TO REPRODUCE

```yaml
- name: Promote SIG version
  hosts: localhost
  connection: local
  tasks:
        - name: Create or update gallery image Version
          azure_rm_galleryimageversion:
            resource_group: "{{ rg_name }}"
            gallery_name: "{{ img_gal_name }}"
            gallery_image_name: "{{ image_name }}"
            name: "{{ release }}"
            location: "{{ location }}"
            publishing_profile:
              end_of_life_date: "{{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch|int + 60*86400) }}"
              exclude_from_latest: no
              replica_count: 1
              storage_account_type: "{{ builder.managed_image_storage_account_type }}"
```

##### EXPECTED RESULTS

Image version is created in Gallery and included in _latest_.

##### ACTUAL RESULTS

```
"msg": "Error creating the GalleryImageVersion instance: Azure Error: BadRequest\nMessage: Could not find member 'exclude_from_latest' on object of type 'GalleryImageVersionPublishingProfile'. Path 'properties.publi
shingProfile.exclude_from_latest', line 1, position 86.\nTarget: galleryImageVersion.properties.publishingProfile.exclude_from_latest"
```

Running with a high degree of verbosity, it seems that when `exclude_from_latest` is set to **true** the generated API call JSON includes `publishing_profile.excludeFromLatest` but when setting it to **false** the API call JSON is sending `publishing_profile.exclude_from_latest`.
