### ISSUE TITLE
Value of a registered play does not update when running consecutive playbooks.

### ISSUE THREAD

**Issue by Alexdelarose** [ansible/ansible#70192]
##### SUMMARY

When running consecutives playbooks in a shell script either in parallel or one by one without a 2 minute pause (it could be less but tried 30 seconds and 1 min before with similar issues), the registered value of the registered play does not update to the output from the current play but instead keep the value from the previous run and it does this for a few more playbooks (it does this inconsistently between every 5 to 10 playbooks).
I was able to reproduce this behaviour for always and turns out manually it works as expected, but when running from my shell script it fails.
It could be that I am doing this the wrong way like doing this in a playbook that runs all the ansible playbooks, but..... Still think that the use case is still valid. 
This bug could represent maybe issues on how the outputs of registered tasks are managed in the memory? The ansible cache? I am unsure at this point how this works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

I think this is a performance issue, unfortunately I have no idea of the components involved.

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /Users/myuser/.ansible.cfg
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.9/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]
```

##### CONFIGURATION

```paste below
DEFAULT_TIMEOUT(/Users/myuser/.ansible.cfg) = 45
HOST_KEY_CHECKING(/Users/myuser/.ansible.cfg) = False
(END)
```

##### OS / ENVIRONMENT

MacOS 10.15.5 (Catalina)

##### STEPS TO REPRODUCE

1. Run a playbook manually like this:
```
ansible-playbook -i ~/git/ansible/hosts/company1 --extra-vars "variable_host=a" -b check_kernel.yml
```
When check_kernel.yml looks like:
```yaml
#check kernel
- name: check-kernel
  serial: "{{ serial_number|default(0) }}"
  hosts: "{{ variable_host | default('empty_group') }}"
  gather_facts: true

  tasks:

  - name: fail if required variable_host parameter is missing
    fail:
      msg: "You have to add the --extra-vars='variable_host='"
    when: (variable_host is not defined) or (variable_host == "")

  - name: get kernel version
    shell: uname -r
    register: kernel_shell_output

  - debug: msg="{{ kernel_shell_output.stdout }}"

  - name: check uptime
    command: /usr/bin/uptime
    register: system_uptime

  - debug: msg="{{ system_uptime.stdout }}"

```
The result for the tasks registered value shows as expected for the uptime debug:
```
ok: [host1] => {
    "msg": " 07:04:23 up 12:22,  2 users,  load average: 0.13, 0.26, 0.22"
}
```
2- When running several playbooks (24 in this case) in a script like this:
```bash
#!/bin/bash
#Creating an orchestator for Ansible
#Run like:
#./orchestrator.sh yum_update a
#Where yum_update is the action (Valid yum_update, reboot and check_kernel)

#Validate the action
check_the_action (){
  case  $1  in
    yum_update|reboot|check_kernel)
        action=$1 ;;
    *)
    echo "Please provide a valid action and run like this: ./orchestrator.sh action side"
    echo "Where action could be yum_update, reboot and check_kernel"
    exit 2 ;;
  esac
}

orchestrator (){
directory="../../hosts/"
echo $action
for hostlistitem in $(ls $directory)
do
    sh -c "ansible-playbook -i $directory/$hostlistitem --extra-vars -b $action.yml" &
#Sometimes you need to add a pause to avoid collisions somewhere in Ansible management.
  fi
done
}

check_the_action $1
orchestrator $action
```
Then just assume $directory contains several inventories like:
hosts_a
hosts_b
hosts_c
hosts_d

The reason for this, is because of the jump host to access them varies on each inventory file.

When running like this, the result is expected to change from hosts in inventory _a from inventory _b for the uptime command debug, but instead the result shows the result from _a to _b _c and d.

Again a workaround this was to add a pause of 120 secs to get this done like: sleep 120.

##### EXPECTED RESULTS

The result will be the same for all of the runs in the automated consecutive runs as it was run manually. Meaning the result for uptime shows the real uptime for the host which is different from inventory _a which was rebooted way before inventory _b, _c and _d

##### ACTUAL RESULTS
The result shown for inventory _a is the same result presented on the debug for all of the inventories unless a 120 sec pause is added.
host on inventory _a
```
ok: [host_a_1] => {
    "msg": " 07:43:25 up 4 days,  5:16,  2 users,  load average: 3.07, 2.97, 3.01"
}
```
host on inventory _b
```
ok: [host_b_1] => {
    "msg": " 07:43:22 up 4 days,  5:16,  2 users,  load average: 2.50, 2.59, 2.67"
}
```
And same for _c and b.

When Manually they show different msg: result showing the real uptime for each one of them.
