### ISSUE TITLE
Terraform module backend config not working

### ISSUE THREAD

**Issue by nirroz93** [ansible/ansible#70197]
##### SUMMARY

Terraform module backend config doesn't work
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

terraform module
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
ANSIBLE_COW_SELECTION(/etc/ansible/ansible.cfg) = small
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = False
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 80
DEFAULT_LIBVIRT_LXC_NOSECLABEL(/etc/ansible/ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /home/nirr/.ansible/ansible.log
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 23
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = devops
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/home/nirr/roles', '/etc/ansib>
DEFAULT_SCP_IF_SSH(/etc/ansible/ansible.cfg) = smart
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

running on localhost (Fedora 32) terraform installed is Terraform v0.12.26

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  become: no
  tasks:
    - name: Write the vars to tfvar file
      copy:
        content: |
          {{ terraform_vars | to_nice_json }}
        dest: /tmp/tfvars.json
      vars:
        terraform_vars:
          clusterName: "{{ customer }}.k8s.local"
          clusterVpc: "{{ vpc.id }}"
          region: "{{ region }}"
          subnets: |
            {{ subnets }}
    - name: Add extra routing using TF
      terraform:
        project_path: "extra_terraform/"
        state: "present"
        force_init: true
        # plan_file: "./extra_tf"
        backend_config:
          region: "us-east-1"
          bucket: "{{ bucket_name }}"
          key: "{{ customer }}/terraform/state.tfstate"
        variables_file: /tmp/tfvars.json
      register: subnets_terraform_output

```
Module gets the config OK (see output in actual result).
...
...
...

##### EXPECTED RESULTS

Running the playbook should put the state in s3 and shouldn't create local terraform.tfstate

##### ACTUAL RESULTS

Ansible is running terraform without backed config (local terraform.tfstate is created)

relevant part is:
```paste below
ok: [localhost] => {
    "changed": false,
    "command": "/usr/bin/terraform apply -no-color -input=false -auto-approve=true -lock=true /tmp/tmpri8wpq0a.tfplan",
    "invocation": {
        "module_args": {
            "backend_config": {
                "bucket": "BUCKET_NAME_IS_OK(REDUCTED)",
                "key": "nirr-try/terraform/state.tfstate",
                "region": "us-east-1"
            },
            "binary_path": null,
            "force_init": true,
            "lock": true,
            "lock_timeout": null,
            "plan_file": null,
            "project_path": "extra_terraform/",
            "purge_workspace": false,
            "state": "present",
            "state_file": null,
            "targets": [],
            "variables": null,
            "variables_file": "/tmp/tfvars.json",
            "workspace": "default"
        }
    },
    "outputs": {},
    "state": "present",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": [],
    "workspace": "default"
}
```
