### ISSUE TITLE
postgresql_pg_hba will show a cast warning when backup param is not quoted

### ISSUE THREAD

**Issue by binf** [ansible/ansible#70223]
##### SUMMARY
When running without quoted backup parameters, the module issue a warning.
This is fixed when the backup value is single quoted. Other modules do not show this casting warning behavior.

##### ISSUE TYPE
- Bug Report/Cosmetic

##### COMPONENT NAME
postgresql_pg_hba

##### ANSIBLE VERSION

```paste below
ansible 2.9.2

  config file = /etc/ansible/ansible.cfg

  configured module search path = [u'/home/someusername/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']

  ansible python module location = /usr/lib/python2.7/site-packages/ansible

  executable location = /usr/bin/ansible

  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True

ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%r

ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = ~/.ansible/cp

DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/ansible-local-276635QHHSm

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

DEFAULT_SSH_TRANSFER_METHOD(/etc/ansible/ansible.cfg) = scp

DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
RHEL 7

##### STEPS TO REPRODUCE

If the value of "backup: yes" become quoted like-> 
backup: 'yes' or 
backup: 'True'
The warning message will not show up.

```yaml

- name: sometask
   vars:
   looplist_source:
     - { contype: "local", users: "postgres", databases: "all", method: "peer" }
     - { contype: "local", users: "all", databases: "all",  method: "peer" }

   postgresql_pg_hba:
     dest: "{{ path_to_hba_file }}"
     contype: "{{ looplist.contype }}"
     method: "{{ looplist.method }}"
     users: "{{ looplist.users }}"
     databases: "{{ looplist.databases }}"
     state: present
     backup: yes
   loop: "{{ looplist_source }}"
   loop_control:
    loop_var: looplist
```

##### EXPECTED RESULTS
No Warning

##### ACTUAL RESULTS

Will execute perfectly but will also show a cast warning.
```paste below
[WARNING]: The value True (type bool) in a string field was converted to u'True' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change
```
