### ISSUE TITLE
aws_s3 module not idempotent for encrypted objects

### ISSUE THREAD

**Issue by Ranjandas** [ansible/ansible#70226]
##### SUMMARY
`aws_s3` module when used with object encryption is always reporting change. This is the case even when `overwrite: different` is set. Also tried with `Content-MD5` header and it also results in the same problem.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`aws_s3` module

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ranjan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ranjan/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

No Configuration changes.
```paste below

```

##### OS / ENVIRONMENT

Target OS: RHEL 7

##### STEPS TO REPRODUCE

```yaml
- name: Upload File to S3
  aws_s3:
    bucket: myConfigBucket
    src: abc.txt
    object: abc.txt
    mode: put
    overwrite: different
    encrypt: True
    encryption_mode: aws:kms
    encryption_kms_key_id: "<kms_key_arn>"
    headers: "Content-MD5={{ abc.txt.stat.checksum | b64encode }}"
```

##### EXPECTED RESULTS

The subsequent runs shouldn't show change.

##### ACTUAL RESULTS

Every run results in a `changed` status when the local file hasn't changed at all.

```paste below
TASK [Upload File to S3] ***************************************
changed: [localhost]
```
