### ISSUE TITLE
When Python calls Ansible, start an error

### ISSUE THREAD

**Issue by Sanchensh** [ansible/ansible#70254]
##### SUMMARY

When Python calls Ansible, start an error.If I comment out part of source code, it's ready to execute. What's the problem

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Python file is playbook_executor.py

##### ADDITIONAL INFORMATION

The code that is commented out is as follows:
![image](https://user-images.githubusercontent.com/21358244/85508066-ee859b00-b625-11ea-889a-358b1b61e2c7.png)
![image](https://user-images.githubusercontent.com/21358244/85508102-02c99800-b626-11ea-88bc-f893ec87da15.png)

```
- hosts: all
  tasks:
    - name: make a file
      file: path=/home/xujl/test.txt state=touch
```
