### ISSUE TITLE
Unable to restore postgres db from a file with semi colon

### ISSUE THREAD

**Issue by keitalbame** [ansible/ansible#70264]
##### SUMMARY

Restore a db from a filename with a semi colon (`;`) fails

The use case for this was that the DB name was accidentally created with a `;`, a dump of the DB was done(using postgresql_db module) with the DB name on the file name and now I need to restore the DB back.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_db
##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /mnt/c/Users/path/redacted/ansible/ansible.cfg
  configured module search path = [u'/home/path/redacted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/path/redacted/.local/lib/python2.7/site-packages/ansible
  executable location = /home/path/redacted/.local/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/mnt/c/Users/path/redacted//ansible/ansible.cfg) = [u'profile_tasks', u'log_plays']
DEFAULT_MANAGED_STR(/mnt/c/Users/path/redacted/ansible/ansible.cfg) = Ansible managed by redacted
DEFAULT_ROLES_PATH(/mnt/c/Users/path/redacted//ansible/ansible.cfg) = [u'/mnt/c/Users/path/redacted/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/mnt/c/Users/path/redacted/ansible/ansible.cfg) = yaml
INVENTORY_ENABLED(/mnt/c/Users/path/redacted/ansible/ansible.cfg) = [u'yaml']
```

##### OS / ENVIRONMENT

source Windows 10 / WSL
target: CentOS 7

##### STEPS TO REPRODUCE

```yaml
- hosts: a_host
  vars:
    somevar: "dbname;"
  tasks:
    - name: Restore Postgres database from with semi colon in filename
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ somevar }}"
        state: restore
        target: "/db-dump/{{ somevar }}.sql"
```

##### EXPECTED RESULTS

db to be restored

##### ACTUAL RESULTS

```paste below
fatal: [a_host]: FAILED! => changed=false
  cmd: /bin/psql --dbname='dbname;' --port=5432 --username=postgres --file=/db-dump/dbname;.sql < '/db-dump/dbname;.sql'
  msg: |-
    /db-dump/dbname: No such file or directory
    /bin/sh: .sql: command not found
  rc: 127
  stdout: ''
  stdout_lines: <omitted>
```

Running `/bin/psql --dbname='dbname;' --port=5432 --username=postgres --file=/db-dump/dbname;.sql < '/db-dump/dbname;.sql'` in a shell returns the same issue.

When using single quotes `--file` path in a shell, the restore in completed successfully.
```
/bin/psql --dbname='dbname;' --port=5432 --username=postgres --file='/db-dump/dbname;.sql' < '/db-dump/dbname;.sql'
```
