### ISSUE TITLE
Default to sane egress policy in ec2_group (change since 1.5.3->1.6)

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#7027]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Mac OS X 10.7
##### Summary:

rules_egress was added to ec2_group in 1.6 (previous there was no rules_egress).  Unfortunately it defaults to nothing in it, meaning that previous ansible scripts will not allow anything out of a security group.  This breaks many security groups.
##### Steps To Reproduce:

Create a ec2_group (security group) with no rules_egress.  Watch everything get blocked going outbound.
##### Expected Results:

Should default to allowing everything outbound since thats what ansible did previously.
##### Actual Results:

Unable to access going outbound.

**Comment by jimi-c** [comment]
Unfortunately I cannot reproduce this issue. I just created a new security group and added an instance to it, where the only rule specified was an ingress rule for port 22 inbound from any. I hopped on the instance and was able to successfully do things like ping out and fetch web pages from public servers.

Could you attach an example playbook for an ec2_group setup that shows the reported behavior?

**Comment by evanccnyc** [comment]
It was a vpc security group (no idea if that changes what happened):

```
- name: Provision frontend security group
  local_action:
        module: ec2_group
        state: present
        name: ansibleDeployedFrontend
        description: "Frontend ansible security group - ssh,http"
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 2049
            to_port: 2049
            cidr_ip: 10.0.0.0/8
          - proto: tcp
            from_port: 111
            to_port: 111
            cidr_ip: 10.0.0.0/8
          - proto: udp
            from_port: 111
            to_port: 111
            cidr_ip: 10.0.0.0/8
          - proto: udp
            from_port: 32806
            to_port: 32806
            cidr_ip: 10.0.0.0/8

```
