### ISSUE TITLE
"Unhandled exception occurred while templating" when upgrading from Ansible 2.9.9 to 2.9.10

### ISSUE THREAD

**Issue by atc0005** [ansible/ansible#70279]
##### SUMMARY

We have a small playbook that we use to quickly set downtime quickly in Nagios. This playbook runs without any discernible problem with Ansible 2.9.9. We upgraded to 2.9.10 and now the playbook no longer works.

This is from the start of the error message:

```
An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}
```

and this from the tail end:

```
original message: recursive loop detected in template string: {{ ansible_user | default(omit, true) }}"
```

The full error is at the bottom of this issue report.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`TASK [Nagios | ADD downtime for services]`

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/ansible/projects/ansible-playbooks-team/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = 5
CACHE_PLUGIN(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = 3600
DEFAULT_CALLBACK_WHITELIST(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = [u'profile_tasks', u'profile_roles', u'timer']
DEFAULT_FORCE_HANDLERS(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = True
DEFAULT_FORKS(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = 50
DEFAULT_GATHERING(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = [u'/home/ansible/projects/ansible-playbooks-team/inventories/production']
DEFAULT_LOG_PATH(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = /home/ansible/ansible.log
DEFAULT_ROLES_PATH(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = [u'/home/ansible/projects/ansible-playbooks-team/roles']
DISPLAY_SKIPPED_HOSTS(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = True
HOST_KEY_CHECKING(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/ansible/projects/ansible-playbooks-team/ansible.cfg) = /tmp
```

##### OS / ENVIRONMENT

- Controller system: Ubuntu 18.04 LTS VM
- Target system: Ubuntu 18.04 LTS VM

##### STEPS TO REPRODUCE

```yaml
- name: Mass-manage Nagios maintenance status
  hosts: all
  gather_facts: no

  vars:

    # Fallback value if playbook user opts to use a custom host list
    # where this value is not already configured.
    our_nagios_server: "nag.example.com"

    # Attempt to use existing inventory variable, fallback to hard-coded
    # value if not found.
    nagios_box: "{{ nagios_server | default(our_nagios_server) }}"

    # Map external options for playbook to specific Nagios module actions
    nagios_actions:
      add: "downtime"
      remove: "delete_downtime"

    # This should be overridden by command-line
    state: "undefined"

    # module default is 30 minutes, here we set 60 minutes unless overridden
    # at command-line
    downtime_duration: "60"

  tasks:

  - name: Ensure that valid options are passed
    assert:
      that:
        - "'state' is defined"
        - "('{{ state | lower }}' == 'add' ) or ('{{ state | lower }}' == 'remove')"
      fail_msg: "ERROR: Desired Nagios maintenance state not specified. Please specify either add or remove syntax and try again."
      success_msg: "OK: Desired state indicated as '{{ state | lower }}' , proceeding... "


  - name: "Nagios | {{ state | upper }} downtime for services"
    delegate_to: "{{ nagios_box }}"
    become: yes
    remote_user: "{{ ansible_user | default(omit, true) }}"
    nagios:
      action: "{{ nagios_actions[state] }}"
      host: "{{ inventory_hostname }}"
      minutes: "{{ downtime_duration }}"
      service: all


  - name: "Nagios | {{ state | upper }} downtime for hosts"
    delegate_to: "{{ nagios_box }}"
    become: yes
    remote_user: "{{ ansible_user | default(omit, true) }}"
    nagios:
      action: "{{ nagios_actions[state] }}"
      host: "{{ inventory_hostname }}"
      minutes: "{{ downtime_duration }}"
      service: host

```

##### EXPECTED RESULTS

Downtime applied using v2.9.10 as it was with Ansible v2.9.9.

##### ACTUAL RESULTS

Playbook run failed with `An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'`

```paste below
fatal: [primary.example.com]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ ansible_user | default(omit, true) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: recursive loop detected in template string: {{ ansible_user | default(omit, true) }}"}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This was the result of 9e00214fb435e6b9ea223d966c2e4d9feecac35f

A minimal reproducer:

```
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - command: "true"
      remote_user: '{{ ansible_user|default(omit, true) }}'
      delegate_to: host2
```

```
ansible-playbook -i host1,host2, playbook.yml
```

In my test, `host1` and `host2` are hosts accessible via SSH.

cc @bcoca @mkrizek

**Comment by mkrizek** [comment]
@sivel I am confused about the `connection: local` in your reproducer. I was able to reproduce the issue with the following:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
      remote_user: '{{ ansible_user|default(omit, true) }}'
      delegate_to: host
```

**Comment by mkrizek** [comment]
> original message: recursive loop detected in template string: {{ ansible_user|default(omit, true) }}"

The recursion error is caused by the fact that we end up with `'ansible_user': u'{{ ansible_user|default(omit, true) }}'` in `delegated_vars` which is created in https://github.com/ansible/ansible/blob/3479803520bf27817207ac6d37855143d4ab0986/lib/ansible/playbook/play_context.py#L266

The first exception is then thrown when we try to template `ansible_user`:
https://github.com/ansible/ansible/blob/3479803520bf27817207ac6d37855143d4ab0986/lib/ansible/executor/task_executor.py#L896

**Comment by mkrizek** [comment]
2.9.10:
```
delegated_vars['ansible_delegated_vars']['host']['ansible_user'] = '{{ ansible_user|default(omit, "true") }}'
delegated_vars['ansible_delegated_vars']['host']['vars']['ansible_user'] is not defined
```

2.9.9:
```
delegated_vars['ansible_delegated_vars']['host']['ansible_user'] = '{{ ansible_user|default(omit, "true") }}'
delegated_vars['ansible_delegated_vars']['host']['vars']['ansible_user'] = None
```
In `2.9.9` `delegated_vars['ansible_delegated_vars']['host']['vars']['ansible_user']` was created via
https://github.com/ansible/ansible/blob/26e8474f6dd4a9c4756cdfab036861a1ee2574b2/lib/ansible/vars/manager.py#L571-L577

The above code was removed in 9e00214.

**Comment by mkrizek** [comment]
https://github.com/ansible/ansible/blob/3479803520bf27817207ac6d37855143d4ab0986/lib/ansible/executor/task_executor.py#L507-L516

It seems that we see this bug now because templar uses only `delegated_vars` which has `'ansible_user': u'{{ ansible_user|default(omit, true) }}'`.

While in `2.9.9` we used all vars where `ansible_user` was not defined and so `omit` was used.

**Comment by sivel** [comment]
> @sivel I am confused about the `connection: local` in your reproducer

That's my mistake, it wasn't in my reproducer, I added it while making that comment, and after testing, meant to remove it.

**Comment by bcoca** [comment]
This is a useless statement, if ansible_user exists it already overrides remote_user, so any value will be ignored .. making it the same as the value that already overrides it  doesn't accomplish anything.

**Comment by atc0005** [comment]
> @bcoca: This is a useless statement, if ansible_user exists it already overrides remote_user, so any value will be ignored .. making it the same as the value that already overrides it doesn't accomplish anything.

I wasn't sure if you were referring to the original report or not, so I delayed responding in case others were more familiar with the context of your reply.

It was likely several versions back when I encountered the problem again, but I've found that for the SSH connection plugin that one of `ansible_user` or `remote_user` wasn't being set, but using the pattern that I posted here *did* seem to work.

Based on your remarks, it sounds that even if what I did was a successful workaround, it shouldn't be. Presumably if it is, that would be a bug elsewhere and would need to be handled separately.

Do I have the right understanding? If so, what does all of this mean in regards to what I was doing before working with v2.9.9 and now not working with v2.9.10?

FWIW, we've removed the `remote_user: "{{ ansible_user | default(omit, true) }}"` entirely from everywhere it appeared in our playbooks and they're working (apparently) fine with v2.9.10.

**Comment by bcoca** [comment]
@atc0005 yes, that should have never been a workaround, the 'remote_address' which is what connection ends up using was always set with this kind of logic:

```
remote_address = ansible_user or ansible_<plugin>_user or task.remote_user or play/block/role.remote_user or --remote-user or ANSIBLE_REMOTE_USER or ansible.cfg:remote_user OR default
```

**Comment by maglub** [comment]
I have an example that has worked well until 2.9.10.

The background:

* We have a role that we call "letsencrypt_deploy_certificates"
* We fetch ssl certificates from a "cert manager host", that might need a different login than the normal `ansible_user`, but not at all sites we use the role
* The default, though, is that we do use the `ansible_user` also for the cert manager host

In this role, we set the variable in the letsencrypt-deploy-certs/defaults.main.yaml:

```
appCertmanager_user: "{{ ansible_user }}"
```

The task that is breaking:

```
---
- name: read certificate for {{ ssl_proxy_domain }} from {{ appCertmanager_host }}
  become: true
  slurp:
    src: '/etc/letsencrypt/live/{{ ssl_proxy_domain }}/{{item}}'
  register: certificate
  delegate_to: "{{ appCertmanager_host }}"
  remote_user: "{{appCertmanager_user}}"
  with_items:
    - fullchain.pem
    - privkey.pem
  tags:
    - letsencrypt
```

So, our problem is that we would like the `appCertmanager_user` to default to the `ansible_user`, which is normally the case, but sometimes use this role by overriding the `appCertmanager_user`.

The original task looks like this:

```
- name: read certificate for {{ ssl_proxy_domain }} from {{ appCertmanager_host }}
  become: true
  slurp:
    src: '/etc/letsencrypt/live/{{ ssl_proxy_domain }}/{{item}}'
  register: certificate
  delegate_to: "{{ appCertmanager_host }}"
  remote_user: "{{ appCertmanager_user }}"
  with_items:
    - fullchain.pem
    - privkey.pem
  tags:
    - letsencrypt
```

The workaround (or solution, of one argue that one should never use the `ansible_user` variable in a delegated task) in our case, is to:

* Remove the defaults/main.yml entry for `appCertmanager_user`
* Use the following construct, to omit the remote_user unless `appCertmanager_user` is set

```
- name: read certificate for {{ ssl_proxy_domain }} from {{ appCertmanager_host }}
  become: true
  slurp:
    src: '/etc/letsencrypt/live/{{ ssl_proxy_domain }}/{{item}}'
  register: certificate
  delegate_to: "{{ appCertmanager_host }}"
  remote_user: "{{ appCertmanager_user | default(omit, true) }}"
  with_items:
    - fullchain.pem
    - privkey.pem
  tags:
    - letsencrypt
```

This way, our role is:

* backwards compatible (works with <2.9.10)
* if the `appCertmanager_user` is not set, we just don't set the `remote_user`, hence inheriting the `ansible_user`
* we can override the `appCertmanager_user` if we need to

Thanks for this issue ticket. Took a while to figure out, but it seems to work for us now, albeit not very intuitive.

**Comment by Enetrati** [comment]
Is there any progress on the issue? I'm still having the same problem with 2.9.14.

**Comment by oguzhansrky** [comment]
again me and again the same problem. This time I have no idea what it's about

**Comment by pplmx** [comment]
I have the same issue

**Comment by chris93111** [comment]
Hi same as 2.9.19

**Comment by adamcharnock** [comment]
I arrived here via Google, and was receiving the same issue where the message `An unhandled exception occurred while templating` was repeated many times. In my case the variable name was `cluster_name`. The solution was to use a different variable name.

FWIW – It looks like one or more of the galaxy roles I am using also used the same variable name, so perhaps that was the cause somehow.

Regardless, hopefully my 'just change the variable name' solution helps someone else that ends up here like me.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Ansible version: any

```yaml
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    app_defaults:
      version: '1.2.3'
      url: 'https://domain/{{ "{{ app_defaults.version }}" }}/app.zip'
  tasks:
  - debug:
      var: app_defaults

  - set_fact:
      app_defaults: '{{ app_defaults }}'

  - debug:
      var: app_defaults
```

Gives recursive error on second `debug` step:

PLAY [localhost] ***********************************************************************************

TASK [debug] *************************************************************************************
ok: [localhost] => {
&nbsp;&nbsp;&nbsp;&nbsp;"app_defaults": {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"url": "https:<area>//domain/{{ app_defaults.version }}/app.zip", 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"version": "1.2.3"
&nbsp;&nbsp;&nbsp;&nbsp;}
}

TASK [set_fact] ************************************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************
fatal: [localhost]: FAILED! => {}

MSG:

An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'url': u'https:<area>//domain/{{ app_defaults.version }}/app.zip', u'version': u'1.2.3'}'. .......
