### ISSUE TITLE
conditional statements should not include jinja2 templating delimiters

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#70288]
##### SUMMARY
Like in #56830 when I place conditionals in a variable and then use that in a 'when' condition, I get the error: `[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: stat_logwatch_distribution.stat.checksum != {{ task }}`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION
```paste below
ansible 2.9.9
  config file = /home/user/git/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 00:00:00) [GCC 10.1.1 20200507 (Red Hat 10.1.1-1)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/user/git/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/git/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_BECOME(/home/user/git/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/user/git/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/user/git/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/user/git/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/home/user/git/ansible/ansible.cfg) = ['profile_roles', 'skippy']
DEFAULT_FORKS(/home/user/git/ansible/ansible.cfg) = 16
DEFAULT_HOST_LIST(/home/user/git/ansible/ansible.cfg) = ['/home/user/git/ansible/hosts']
DEFAULT_JINJA2_EXTENSIONS(/home/user/git/ansible/ansible.cfg) = jinja2.ext.loopcontrols
DEFAULT_MANAGED_STR(/home/user/git/ansible/ansible.cfg) = # Ansible managed
DEFAULT_REMOTE_PORT(/home/user/git/ansible/ansible.cfg) = 4443
DEFAULT_STDOUT_CALLBACK(/home/user/git/ansible/ansible.cfg) = skippy
DIFF_ALWAYS(/home/user/git/ansible/ansible.cfg) = True
DIFF_CONTEXT(/home/user/git/ansible/ansible.cfg) = 3
RETRY_FILES_ENABLED(/home/user/git/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Fedora 32 x86_64

##### STEPS TO REPRODUCE
I want to conditionally change the hash comparison (Ansible calls this wrongly a checksum), this hash is different for Debian and Fedora. So this conditional should be based on distribution. Therefore I want to set the 'task' variable according to distribution. This works fine, but leaves the warning I mentioned earlier.
```yaml
    - name: checking hash of distribution logwatch config
      fail:
        msg: "hash ({{ stat_logwatch_distribution.stat.checksum }}) for {{ stat_logwatch_distribution.stat.path }} changed"
      when: stat_logwatch_distribution.stat.checksum != {{ task }}
      vars:
        task: "{% if ansible_distribution == 'Debian' %} '688acebbd73454f35da20e9e602096eab04a126c' {% elif ansible_distribution == 'Fedora' %} 'f4ede07fbddbe90a3003db2aca8b09144e1efa67' {% endif %}"
```

##### EXPECTED RESULTS
I expect Ansible to return the variable based on the conditions and not process them in the when condition, which I guess triggers the warning?

##### ACTUAL RESULTS

```paste below
TASK [common : checking hash of distribution logwatch config] ********************************************************************************************************************************************************************************************************************
task path: /home/user/git/ansible/roles/common/tasks/main.yml:112
Thursday 25 June 2020  08:55:04 +0200 (0:00:00.891)       0:00:05.452 ********* 
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: stat_logwatch_distribution.stat.checksum != {{ task }}
```
