### ISSUE TITLE
postgresql_db module doesn't use the correct postgres restore command

### ISSUE THREAD

**Issue by czenderink** [ansible/ansible#70324]
##### SUMMARY
postgresql_db with the state restore doesn't use pg_restore but psql instead. Therefore is also doesn't support the pg_restore arguments like the description of the target_opts suggests in the documentation

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_db module

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /Users/xxxx/.ansible.cfg
  configured module search path = ['/Users/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:33) [Clang 11.0.0 (clang-1100.0.33.17)]

```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_CALLBACK_WHITELIST(/Users/xxxx/.ansible.cfg) = ['profile_tasks', 'timer']
HOST_KEY_CHECKING(/Users/xxxx/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
source Catalina 10.15.5, target CentOS7

##### STEPS TO REPRODUCE
```yaml
postgresql_db:
    login_host: "{{ rds_host }}"
    login_user: "{{ rds_master_username }}"
    login_password: "{{ rds_master_password }}"
    name: "{{ database_name }}"
    state: "restore"
    target: "{{ complete_file_path }}/{{ environment }}_{{ database_name }}.sql"
    target_opts: "--create --clean"
```

##### EXPECTED RESULTS
I expected the module to use the pg_restore command as the documentation suggests.

`"cmd": "/bin/pg_restore....."`

##### ACTUAL RESULTS
What actually happens is that it uses psql instead of the pg_restore command.

`"cmd": "/bin/psql....."`
