### ISSUE TITLE
become_user: www-data gives unsuppressable warning

### ISSUE THREAD

**Issue by plashenkov** [ansible/ansible#70346]
Hi,

I'm trying to run command as www-data:

```yml
- name: restart app using pm2
  become_user: www-data
  command:
    cmd: pm2 startOrRestart /var/www/example.com/ecosystem.config.js
```

Which gives me a warning:

```
[WARNING]: Unable to use /var/www/.ansible/tmp as temporary directory, failing back to system: [Errno 13] Permission denied: '/var/www/.ansible'
```

What, what does it want from me? What am I doing wrong?
I can't even suppress this warning (command's `warn: no` doesn't help at all).
The same is true for shell module.

---

##### ISSUE TYPE
- [x] Bug Report

##### COMPONENT NAME
- [x] command_module
- [x] shell_module

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/plashenkov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_3/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Apr 24 2020, 17:36:28) [Clang 11.0.3 (clang-1103.0.32.59)]
```

##### OS / ENVIRONMENT
- [x] macOS 10.15.5
