### ISSUE TITLE
delegate_to on a host actually connect to localhost

### ISSUE THREAD

**Issue by bmillemathias-1a** [ansible/ansible#70359]
### SUMMARY
I have a playbook using localhost as hosts because it target openstack API.
at some point we do a add_hosts to put a machine created into a group, then the next tasks uses `delegate_to: "{{ openstack_machine }}"` however the tasks are run on localhost.
The problem appeared on 2.9.10 only and I know the issue #70334 I want to make sure this is the same root cause because there is no problem of variables not set that appears.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
controller

##### ANSIBLE VERSION

```paste below
2.9.10
```

##### CONFIGURATION

```paste below
-- empty
```

##### OS / ENVIRONMENT
Fedora 32, python 3.7, 

##### STEPS TO REPRODUCE

install ansible 2.9.10

```yaml

```

##### EXPECTED RESULTS

* task to be done on the host set on `delegate_to` host
 
##### ACTUAL RESULTS

* tasks are done on the controller

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
You linked https://github.com/ansible/ansible/issues/70334 but did not mention hostvars in your report. Can you provide a simple reproducer of your issue?

Alternatively, would you be able to test https://github.com/ansible/ansible/pull/70293 to see if it fixes your issue? Thanks!

**Comment by bmillemathias-1a** [comment]
> You linked #70334 but did not mention hostvars in your report. Can you provide a simple reproducer of your issue?
> 
I'm trying to

> Alternatively, would you be able to test #70293 to see if it fixes your issue? Thanks!

Thanks

**Comment by bmillemathias-1a** [comment]
I was not able to reproduce on a small playbook, but I can share you the details of the one that cause me this problem

the playbook is run on hosts: localhost and call a role that create a openstack infrastructure


```yaml
#!/bin/env ansible-playbook
---
- hosts: local
  connection: local
  gather_facts: true

  roles:
    - role: create-infra
```

```yaml
# roles/create-infra/tasks/main.yaml
---
- name: Create bastion instance
  import_tasks: create_bastion.yaml
  tags: bastion

- name: Configure bastion instance
  import_tasks: configure_bastion.yaml
  tags: bastion_conf
```


```yaml
---
# roles/create-infra/tasks/create_bastion.yaml (called by main.yaml)
- name: "Create bastion instance"
  os_server:
    state: present
    name: "{{ bastion['name'] }}"
    image: "{{ bastion['image'] }}"
    key_name: "{{ global['key_name'] }}"
    security_groups: ["{{ cluster['name'] }}"]
    wait: true
    flavor: "{{ bastion['flavor'] }}"
    auto_ip: false
    nics:
      - port-name: "{{ bastion['name'] }}"
    timeout: 600

- name: "Check if bastion has floating ip"
  os_server_info:
    server: "{{ bastion['name'] }}"
  register: result

- name: "Assign floating ip to bastion instance"
  os_floating_ip:
    server: "{{ bastion['name'] }}"
    state: present
    reuse: true
    network: "{{ network['external_pool_name'] }}"
    wait: true
    timeout: 180
  when: result.openstack_servers[0].public_v4 == '' # noqa 602
...
```

```yaml
---
# roles/create-infra/tasks/configure_bastion.yaml (called by main.yaml)
- name: "Gather facts of bastion instance"
  os_server_info:
    server: "{{ bastion['name'] }}"
  register: instance_bastion

- name: set bastion facts
  set_fact:
    bastion_server_ip_public: "{{ instance_bastion.openstack_servers[0]['public_v4'] }}"
    bastion_server_ip_private: "{{ instance_bastion.openstack_servers[0]['private_v4'] }}"
    servername: "{{ bastion['name'] }}"

- name: "Add bastion server {{ servername }} to the inventory"
  add_host:
    hostname: "{{ servername }}"
    ansible_host: '{{ bastion_server_ip_public }}'
    ansible_ssh_user: "{{ bastion['ssh_user'] }}"


# This part is running on localhost instead of "{{ servername }}"
# 
# 
# 
- name: "Install and configure bastion server"
  delegate_to: "{{ servername }}"
  become: true
  become_method: sudo
  block:
    - name: "Wait ssh for bastion server {{ servername }}"
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      become: false

    - name: Add rhel-extra repo
      yum_repository:
        name: rhel7-extras
        description: RHEL 7 Extras RPMs
        file: rhel
        baseurl: https://repository.rnd.amadeus.net/mirror-rpm/latest/rhel-7-server-extras-rpms/
        skip_if_unavailable: true
        gpgcheck: true
        enabled: true
        priority: 2
        sslverify: true
        protect: true

    - name: Add rhel7-server repo
      yum_repository:
        name: rhel7-server
        description: RHEL 7 Server RPMs
        file: rhel
        baseurl: https://repository.rnd.amadeus.net/mirror-rpm/latest/rhel-7-server-rpms/
        skip_if_unavailable: true
        gpgcheck: true
        enabled: true
        priority: 1
		...
		...
```

**Comment by mkrizek** [comment]
Looking at the playbook this might be a duplicate of https://github.com/ansible/ansible/issues/70320.

**Comment by bcoca** [comment]
The issue here is that a long standing bug on delegation made 'delegated host' ignore task settings:

```
- hosts: windows
  connection: windows
  tasks:
     - ping: 
       delegate_to: otherwindows

```
previously failed, and required `ansible_connection: winrm` to be added since the delegated host ignored `connection` keyword, that is now fixed, but creates the issue that your `connection: local` is now obeyed and gives a diff result than before.

**Comment by jhg03a** [comment]
Another simple reproduce case is
```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print where this module actually ran
      shell: "hostname -f"
      delegate_to: 192.168.1.100
```
