### ISSUE TITLE
IOSXR_CONFIG Replace Config Not Working as Intended for NCS 5500 (7.1.2.17I) vs NCS 540 (7.2.1.34I)

### ISSUE THREAD

**Issue by Donny-Ta** [ansible/ansible#70374]
##### SUMMARY
I am writing a playbook that will backup and replace the running config on several network devices. I was testing the replace functionality using an NCS 540 and that worked as intended. When I run the replace against an NCS 5500, it did not work and I get an error. There are 3 differences that I can tell when I run the replace: 1) the chassis 2) the OS version and 3) the running config I am using as the src.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_xr

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/Donny/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jan 27 2020, 04:46:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

##### CONFIGURATION
```
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
```

##### OS / ENVIRONMENT
NCS 540 - 7.2.1.34I
NCS 5500 - 7.1.2.17I
Running ansible off of MacOS Mojave (10.14.6)

##### STEPS TO REPRODUCE
1) Backup running config from device
2) Make a change to the config (like adding a dummy logging configuration) and commit (commented out in the playbook below)
3) Replace config on device with the backup config
4) Repeat 1-3 using the NCS 540 and then again with NCS 5500

```
- hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    #  - name: multiline config
    #    iosxr_config:
    #      lines:
    #        - no logging 1.1.1.1 vrf management severity info
    #        - no snmp-server host 2.2.2.2 traps version 2c Br08dCasT
     - name: Backup current config (iosxr)
       iosxr_config:
         backup: yes
         backup_options:
          filename: "{{inventory_hostname}}.cfg"
       when: backup is defined and ansible_network_os == 'iosxr'
     - name: Replace config (iosxr)
       iosxr_config:
         src: /Users/Donny/backup/[config-name].cfg
         replace: config
         backup: no
         backup_options:
           filename: no.cfgs
       when: replace is defined and ansible_network_os == 'iosxr'
```

lab_devices:
```
[all:vars]
# these defaults can be overridden for any group in the [group:vars] section

[iosxr]
...
enwdnj70-srcore-A-pr01 ansible_host=IP
enwdnj70-srcore-A-pe01 ansible_host=IP
...

[iosxr:vars]
ansible_network_os=iosxr

[nxos]
...

[nxos:vars]
ansible_network_os=nxos
```
Example cli command when I run the playbook:
ansible-playbook test.yml -u [mySSO] --ask-pass -i lab_devices -l [device-hostname] -e replace=True
OR
ansible-playbook test.yml -u [mySSO] --ask-pass -i lab_devices -l [device-hostname] -e backup=True

##### EXPECTED RESULTS
Replace config to work regardless of chassis or OS version.

##### ACTUAL RESULTS
NSC 540:
```
ansible-playbook test.yml -u [mySSO] --ask-pass -i lab_devices -l enwdnj70-srcore-A-pe01 -e replace=True
SSH password: 

PLAY [all] *********************************************************************************************************************************************************************************************************

TASK [Backup current config (iosxr)] *******************************************************************************************************************************************************************************
skipping: [enwdnj70-srcore-A-pe01]

TASK [Replace config (iosxr)] **************************************************************************************************************************************************************************************
[WARNING]: Platform darwin on host enwdnj70-srcore-A-pe01 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [enwdnj70-srcore-A-pe01]

PLAY RECAP *********************************************************************************************************************************************************************************************************
enwdnj70-srcore-A-pe01     : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0 
```
VS
NCS 5500:
```
ansible-playbook test.yml -u 206587390 --ask-pass -i lab_devices -l enwdnj70-srcore-A-pr01 -e replace=True
SSH password: 

PLAY [all] *********************************************************************************************************************************************************************************************************

TASK [Backup current config (iosxr)] *******************************************************************************************************************************************************************************
skipping: [enwdnj70-srcore-A-pr01]

TASK [Replace config (iosxr)] **************************************************************************************************************************************************************************************
[WARNING]: Platform darwin on host enwdnj70-srcore-A-pr01 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [enwdnj70-srcore-A-pr01]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "local variable 'start_index' referenced before assignment"}

PLAY RECAP *********************************************************************************************************************************************************************************************************
enwdnj70-srcore-A-pr01     : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0 
```

Before running the playbook against a different device, I change the src to be the corresponding config.

I apologize if I'm missing any additional info. Please let me know if I need to add anything else.

Thank you.
