### ISSUE TITLE
ansible-inventory doesn't support pattern(?)

### ISSUE THREAD

**Issue by dbuteau** [ansible/ansible#70382]
##### SUMMARY
ansible-inventory command doesn't support the [documented](https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#common-patterns) host pattern for multiple, excluding and intersect groups

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-inventory command

##### ANSIBLE VERSION

```
ansible-inventory 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dabuteau/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dabuteau/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.0 (default, Oct 28 2019, 16:14:01) [GCC 8.3.0]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_STRATEGY(/etc/ansible/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/opt/mitogen-0.2.9/ansible_mitogen/plugins/strategy']
```

##### OS / ENVIRONMENT
WSL 1 - Ubuntu 18.04
Linux (non wsl) Ubuntu 18.04
Docker Ubuntu 18.04

##### STEPS TO REPRODUCE
Construct this inventory
```yaml
all:
    children:
        Europe:
            children:
                frontoffice:
                    hosts:
                        EU_webserver:
                backoffice:
                    hosts:
                        EU_my_server:
        USA:
            children:
                frontoffice:
                    hosts:
                        US_webserver:
                backoffice:
                    hosts:
                       US_my_server:
```
and launch the command
```
ansible-inventory -i inventory.yml --graph 'frontoffice:&USA'
```

##### EXPECTED RESULTS
```
> ansible-inventory -i inventory.yml --graph 'frontoffice:backoffice'
@frontoffice:
  |--EU_webserver
  |--US_webserver
@backoffice
 |--EU_my_server
 |--US_my_server

> ansible-inventory -i inventory.yml --graph 'frontoffice:&USA'
@frontoffice:
  |--US_webserver

> ansible-inventory -i inventory.yml --graph 'frontoffice:!USA'
@frontoffice:
  |--EU_webserver
```

##### ACTUAL RESULTS
```bash
> ansible-inventory -i inventory.yml --graph 'frontoffice:backoffice'
ERROR! Pattern must be valid group name when using --graph

> ansible-inventory -i inventory.yml --graph 'frontoffice:&USA'
ERROR! Pattern must be valid group name when using --graph

> ansible-inventory -i inventory.yml --graph 'frontoffice:!USA'
ERROR! Pattern must be valid group name when using --graph
```
