### ISSUE TITLE
AWS ASG Instance refresh

### ISSUE THREAD

**Issue by gugu** [ansible/ansible#70398]
##### SUMMARY
AWS recently introduced "Instance refresh" feature in ASG. Using it is preferred way to update launch configuration in ASG

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ec2_asg

##### ADDITIONAL INFORMATION

Deploying ASG from the client depends on internet connectivity and is not transactional. In the middle of deployment of ASG it can fail leaving ASG in unpredicted state. Using AWS infrastructure will add more stability in deployment (and probably will make it faster)

More about the feature: https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/
 

```yaml
- ec2_asg:
    name: some-backend
    refresh_instances: yes
    wait_for_instances: yes
    launch_template:
      launch_template_id: lt-099aeae5188521da9
    health_check_type: ELB
    wait_timeout: 800
    health_check_period: 300
```
