### ISSUE TITLE
Add distinct 'include_role', 'import_role' and 'role' to variable precedence list

### ISSUE THREAD

**Issue by adamcarheden** [ansible/ansible#70397]
##### SUMMARY

I'm submitting a bug rather than a doc update because I'm new to ansible and I may be missing something. 

From the [list of precedence of variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#examples-of-where-to-set-a-variable):

> Here is the order of precedence from least to greatest (the last listed variables winning prioritization):
> 15. role vars (defined in role/vars/main.yml)
> 20. role (and include_role) params

...however, params defined using the 'role:' syntax (#20) do not override role vars (#15)

Example:

```
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development.
This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [test] ********************************************************************************************************************************************************************************

TASK [test : Vars from the role] ***********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "varA = \"varA defined as a role parameter (works as expected)\"",
        "varB = \"varB defined as a role var (overridden, should not print)\""
    ]
}

TASK [test : Vars from the role] ***********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "varA = \"varA as an import_role param (works as expected)\"",
        "varB = \"varB as an import_role param (works as expected)\""
    ]
}

TASK [include_role : test] *****************************************************************************************************************************************************************

TASK [test : Vars from the role] ***********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "varA = \"varA as an include_role param (works as expected)\"",
        "varB = \"varB as an include_role param (works as expected)\""
    ]
}

PLAY RECAP *********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

And the code:
* ./test.yml
  ```
  - name: test
    hosts: localhost
    gather_facts: false
    roles:
      - role: test
        vars:
          varA: varA defined as a role parameter (works as expected)
          varB: varB defined as a role parameter (should override, but NOT printed)
    tasks:
      - import_role:
          name: test
        vars:
          varA: varA as an import_role param (works as expected)
          varB: varB as an import_role param (works as expected)
      - include_role:
          name: test
        vars:
          varA: varA as an include_role param (works as expected)
          varB: varB as an include_role param (works as expected)
  ```
  
* ./roles/test/defaults/main.yml
  ```
  varA: varA defined as a role default
  ```
  
* ./roles/test/tasks/main.yml
  ```
  - name: Vars from the role
    debug:
      msg:
        - varA = "{{ varA }}"
        - varB = "{{ varB }}"
  ```
  
* ./roles/test/vars/main.yml
  ```
  varB: varB defined as a role var (overridden, should not print)
  ```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Documentation

##### ANSIBLE VERSION

```paste below
$ ansible --version
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development.
This is a rapidly changing source of code and can become unstable at any point.
ansible 2.11.0.dev0
  config file = None
  configured module search path = ['/home/adam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adam/src/ansible/lib/ansible
  ansible collection location = /home/adam/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/adam/src/ansible/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development.
This is a rapidly changing source of code and can become unstable at any point.
```

##### OS / ENVIRONMENT
Probably all irrelevant, but:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

##### ADDITIONAL INFORMATION
Clarify variable precedence order.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
You have not used role params in your reproducer, only vars.

What you used:

```yaml
  roles:
    - role: test
      vars:
        varA: varA defined as a role parameter (works as expected)
        varB: varB defined as a role parameter (should override, but NOT printed)
```

Using role params:
```yaml
  roles:
    - role: test
      varA: varA defined as a role parameter (works as expected)
      varB: varB defined as a role parameter (should override, but NOT printed)
```
