### ISSUE TITLE
include_tasks provide list instead of file

### ISSUE THREAD

**Issue by cpmoore** [ansible/ansible#70399]
##### SUMMARY
Allow passing of tasks as list to include_tasks

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
include_tasks

##### ADDITIONAL INFORMATION
I believe `include_tasks` should allow you to provide a task list directly to it, instead of requiring that the tasks be in a file.
There are many times when i need to loop over just two tasks, to me it can be cumbersome to have a file with just two tasks in it.

Existing syntax
`main.yml`
```yaml
- name: this is my task
  include_tasks: whatever.yml
  loop:
   - one
   - two
```
`whatever.yml`
```yml
- task1:
    param: '{{item}}'
- task2:
    param: '{{item}}'
```

Desired syntax
main.yml
```yaml
- name: this is my task
  include_tasks: 
  - task1:
      param: '{{item}}' 
  - task2:
      param: '{{item}}'
  loop:
   - one
   - two
```

I'd even be okay with ansible just dynamically writing the task list to a temp file and including it that way
