### ISSUE TITLE
delegate_to and ansible_os_family not working together

### ISSUE THREAD

**Issue by impsik** [ansible/ansible#70409]
##### SUMMARY
Ansible playbook ignores ansible_os_family when using delegate_to

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

task
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian 10

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:  
  - name: "capture output of id command"
    shell: cat /tmp/system
    register: login
    with_lines: 
      cat server_to_upgrade.txt
    delegate_to: "{{ item }}"
    when: ansible_os_family == "Debian"
```

##### EXPECTED RESULTS

TASK [capture output of id command] ******************************************************
changed: [localhost -> ubuntu2004-test] => (item=ubuntu2004-test)
skipping: [centos7]

##### ACTUAL RESULTS

changed: [localhost -> ubuntu2004-test] => (item=ubuntu2004-test)
changed: [localhost -> centos7] => (item=centos7)

```paste below

```
I have 2 test VM, named ubuntu2004-test and centos7. 
Backstory:
I have one playbook which logs into vmware vcenter, makes snapshot of a VM which are listed in a `server_to_upgrade.txt` file and then playbook upgrades VM. Everything works, except when i use delegate_to and ansible_os_family together.
Please ask questions if needed.
