### ISSUE TITLE
blockinfile - option to add or more newlines before and/or after block markers

### ISSUE THREAD

**Issue by jeanmonet** [ansible/ansible#70427]
##### SUMMARY

Provide option in `blockinfile` module to insert one or more newlines before and/or after the block (more precisely its marker). This is very useful for the readability of configuration files managed by Ansible.

The newlines would only be added upon block insertion, not upon future verifications on whether the block exists.

Note: including a newline character `\n` in the marker (`marker: '\n# ANSIBLE MANAGED'`) does NOT work as desired because markers are detected on a 1-line basis only. This means that repeating the task will add the block just as many times, instead of detecting that it is already there.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`blockinfile` parameters can be called `newlines_before: 1` and `newlines_after: 1`.

##### ADDITIONAL INFORMATION

HUGE Increase in readability of config files managed by Ansible. Avoids redundant code and checks to add those newlines manually (without repeatedly inserting the block on each iteration).

```yaml
  blockinfile:
    path: /path/to/file.conf
    block:	|2
       # Bla bla some block
    marker: "# ANSIBLE MANAGED {mark}"
    marker_begin: ">>>"
    marker_end: "<<<"
    insertbefore: 'blabla'
    newlines_after: 1        # THIS
    newlines_before: 1       # also this
    state: present
```
