### ISSUE TITLE
Problem with adding a user with redfish_command module

### ISSUE THREAD

**Issue by xterms013** [ansible/ansible#70453]
#59263 ### SUMMARY
Can't create users on servers Lenovo( ThinkSystem SR530,630,650)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
redfish_command

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### OS / ENVIRONMENT
CENTOS 8

##### STEPS TO REPRODUCE
If i run this playbook i get the following output(servers contains 192.168.0.1 only)

```
---

- name: Manage Redfish hosts
  redfish_command:
    category: Accounts
    command: AddUser,EnableUser
    baseuri: "{{  item  }}"
    id: "6"
    username: "ADMIN"
    password: "ADMIN"
    roleid: "Operator"
    new_username: "TEST"
    new_password: "TEST"
  with_items:
    - "{{  servers  }}"
```

```

##### EXPECTED RESULTS
Should have added an account on the server. On dell servers this code works, for example

##### ACTUAL RESULTS
```
PLAY [run_playbook] ****************************************************************************************************************************

TASK [manage_redfish_hosts : Manage Redfish hosts] *********************************************************************************************
failed: [192.168.0.1] (item=192.168.0.1) => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "ansible_loop_var": "item", "changed": false, "item": "192.168.0.1", "msg": "HTTP Error 500 on PATCH request to 'https://192.168.0.1/redfish/v1/AccountService/Accounts/6', extended message: 'The request failed due to an internal service error.  The service is still operational.'"}

PLAY RECAP *************************************************************************************************************************************
192.168.0.1               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```   
If i run this playbook i get the following output(servers contains 192.168.0.1 only)
```
