### ISSUE TITLE
conditional check 'cmdb_hwmodel.startswith('HP ')

### ISSUE THREAD

**Issue by nsheraga** [ansible/ansible#70464]
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

##### ISSUE TYPE

can some one please help me how to fix , i am new for ansible still learning

```
TASK [hp : hpilo_info] **************************************************************************************************************************************
task path: /data01/ansible/playbooks/roles/hp/tasks/main.yml:1
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'cmdb_hwmodel.startswith('HP ')' failed. The error was: error while evaluating conditional (cmdb_hwmodel.startswith('HP ')): 'cmdb_hwmodel' is undefined\n\nThe error appears to be in '/data01/ansible/playbooks/roles/hp/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- hpilo_info:\n  ^ here\n"
}
```

##### COMPONENT NAME
hpilo_info:

##### ANSIBLE VERSION
```
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


```

##### CONFIGURATION
```
- hpilo_info:
    host: "{{ host }}"
    login: "{{ login }}"
    password: "{{ password }}"
    ssl_version:
     description:
      - The SSL version used to authenticate to the HP iLO interface.
    default: tlsv1
  when: cmdb_hwmodel.startswith('HP ')
  delegate_to: localhost
  register: results
- fail:
    msg: 'CMDB serial ({{ cmdb_serialno }}) does not match hardware serial ({{ results.hw_system_serial }}) !'
  when: cmdb_serialno != results.hw_system_serial

```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.8 (Maipo)
