### ISSUE TITLE
Add warning when using local connection plugin and delegate_to

### ISSUE THREAD

**Issue by jhg03a** [ansible/ansible#70460]
##### SUMMARY

After chasing an issue with my teammates, we located a bug in one of our playbooks where we'd used the local connection plugin but later added a delegate_to for another host on some shell module tasks.  Unexpectedly the playbook executed successfully, but produced erratic results as the task wasn't running where we thought it should.  By definition, this seems to be the desired behavior.  However, it would be very helpful when triaging if there were some kind of warning issued if delegate_to and the local connection plugin were used together on the same play.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

local connection plugin

##### ADDITIONAL INFORMATION

This is a usability gain and to help prevent accidents in playbooks.  Adding a more clear warning of this behavior in the documentation is also not a terrible idea.

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print where this module actually ran
      shell: "hostname -f"
      delegate_to: 192.168.1.100
```
