### ISSUE TITLE
RFE: lineinfile should support a pure (non-regex) line

### ISSUE THREAD

**Issue by macau23** [ansible/ansible#70470]
---

##### SUMMARY
I want to be able to use a pure (non-regex) line with lineinfile. Without accidentally escaping or not escaping characters.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lineinfile

##### ADDITIONAL INFORMATION

I have a line in a file which has lots of special characters. I want to use Ansible's lineinfile module.

Ansible's lineinfile module requires a regular expression, which means lots of escaping for me, and a role or playbook that is more difficult to read.

Could the module support a non-regex line too?

Example of problem regex (have fun escaping this one! - real world example):

```yaml
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '#         "${distro_id}:${distro_codename}-updates";'
      line: '         "${distro_id}:${distro_codename}-updates";'
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@macau23: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/lineinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/lineinfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @macau23,

In your example, if you want to modify a file like this:

```ini
Unattended-Upgrade::Allowed-Origins {
  "${distro_id}:${distro_codename}-security";
# "${distro_id}:${distro_codename}-updates";
  "${distro_id}:${distro_codename}-proposed";
  "${distro_id}:${distro_codename}-backports";
};
```

You can do:

```yaml
      lineinfile:
        path: 5/etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '# ".{distro_id}:.{distro_codename}-updates";'
        line: '  "${distro_id}:${distro_codename}-updates";'
```

To me, it is not painful and readable. What do you think?

**Comment by macau23** [comment]
Hello @imjoseangel 

Thanks. My snippet was an example. I would like to have a way to use lineinfile with a verbatim line.

**Comment by imjoseangel** [comment]
Thank you @macau23 

I´m not sure if it should be part of this module of a **new one**. The logic of the module depends on the `regexp` field. 

I don´t see a new "`nonregexp`" field. I think it could add extra complexity to the module. 

Another option is creating a `regex: true/false`. 

What do you think?

**Comment by macau23** [comment]
`regex: true/false` is a good compromise :D

**Comment by imjoseangel** [comment]
@samdoran What do you think?

**Comment by samdoran** [comment]
> Another option is creating a regex: true/false.

Overloading the `regexp` field to accept a string and a boolean is far too confusing and wouldn't pass argument spec validation. I would definitely say no to that.

I would suggest a new field rather than a toggle that changes the behavior of an existing field.

Maybe `raw_line` or `literal_line` to indicate it is a literal string and will not be treated as a regexp pattern.

The main logic currently is:

- If `regexp` is supplied --> treat `line` as a regexp pattern with `re.search(b_line)`
- If no `regexp` is supplied --> treat `line` as a literal string match with `b_line == b_cur_line.rstrip(b'\r\n')`

**Comment by imjoseangel** [comment]
@macau23 @samdoran I have just upload the final version of the lineinfile with the new `literal` option. In the first commit, the idea is test current integration tests. I will implement the new ones ASAP.

**Comment by imjoseangel** [comment]
Hi! I have just implemented the module with test. New limitations:

* `regex` and `literal` cannot be used together.
* `literal` doesn't accept `backrefs` option as it doesn't make sense to have it for literal

@macau23 although the tests are good. Could you please have a look and test it? Thank you!

**Comment by macau23** [comment]
@imjoseangel sure, what's the best way of getting hold of the correct ansible build to test this?

**Comment by imjoseangel** [comment]
> @imjoseangel sure, what's the best way of getting hold of the correct ansible build to test this?

You can directly download the final commit from [here](https://github.com/ansible/ansible/blob/e8b5fe17fb7395ee67cf09ee102506c6cd9deaa4/lib/ansible/modules/lineinfile.py) and copy it to your library path if you want to test it beforehand.

Thank you!

**Comment by macau23** [comment]
Maybe I am doing something wrong here...

I have this:

```
- name: configure unattended-upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    literal: '//      "${distro_id}:${distro_codename}-updates";'
    line:    '        "${distro_id}:${distro_codename}-updates";'
```

I am expecting the commented out line (`literal:`) to be replaced with the uncommented line (`line:`), but instead I get the uncommented line appended to the end of the file.

**Comment by imjoseangel** [comment]
Weird, 

Are you sure you are using the correct spacing? For the literal, spacing is also a _must_

I'm using this as `/etc/apt/apt.conf.d/50unattended-upgrades`:

```ini
Unattended-Upgrade::Allowed-Origins {
  "${distro_id}:${distro_codename}-security";
//  "${distro_id}:${distro_codename}-updates";
//  "${distro_id}:${distro_codename}-proposed";
//  "${distro_id}:${distro_codename}-backports";
};
```
And this is exactly my lineinfile playbook:

```yaml
---
- name: Ansible
  hosts: blabla
  gather_facts: false

  tasks:

    - name: Include role tests
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        literal: '//  "${distro_id}:${distro_codename}-updates";'
        line:    '    "${distro_id}:${distro_codename}-updates";'
```
After running, I get:

```ini
Unattended-Upgrade::Allowed-Origins {
  "${distro_id}:${distro_codename}-security";
  "${distro_id}:${distro_codename}-updates";
//  "${distro_id}:${distro_codename}-proposed";
//  "${distro_id}:${distro_codename}-backports";
};
```
