### ISSUE TITLE
Number of virtual devices exceeds the maximum for a given controller while changing adapter settings for a VM

### ISSUE THREAD

**Issue by srivaa31** [ansible/ansible#70520]
##### SUMMARY

pyVmomi.VmomiSupport.TooManyDevices exception while configuring four adapter settings on the target VM
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest_network
##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```paste below
DEFAULT_PRIVATE_KEY_FILE(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_REMOTE_USER(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = root
DISPLAY_SKIPPED_HOSTS(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = False
HOST_KEY_CHECKING(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = False
INTERPRETER_PYTHON(/var/lib/jenkins/workspace/Ansible_QA/Automation/ansible.cfg) = auto

```

##### OS / ENVIRONMENT

esxi: 6.7 
OS: CentOS Linux release 8.1.1911 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: Changing network adapter for enabling data IP interface viz. vlan151 vlan152, vlan153, vlan154 respectively
  vmware_guest_network:
    datacenter: "{{ source_datacenter_name}}"
    hostname: "{{ vmware_server }}"
    username: "{{ vmware_user  }}"
    password: "{{ vmware_pass }}"
    folder: /
    cluster: "{{ cluster_name }}"
    validate_certs: no
    name: test_automation_vm3
    networks:
      - name: "VLAN_152_Data1"
        device_type: vmxnet3
        label: "Network adapter 2"
        connected: True
        state: new
      - name: "VLAN_160_Data2"
        device_type: vmxnet3
        label: "Network adapter 3"
        state: new
        connected: True
      - name: "VLAN_152_Data3"
        device_type: vmxnet3
        label: "Network adapter 4"
        state: new
        connected: True
      - name: "VLAN_160_Data4"
        device_type: vmxnet3
        label: "Network adapter 5"
        state: new
        connected: True
  delegate_to: localhost
  register: netwrok_info

```

##### EXPECTED RESULTS

Expected to attach the correct adapters from the VLAN port group on the VM
##### ACTUAL RESULTS

```paste below
TASK [io_test : Changing network adapter for enabling data IP interface viz. vlan151 vlan152, vlan153, vlan154 respectively] ***************************************************
fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": false, "module_stderr": "pyVmomi.VmomiSupport.TooManyDevices: (vim.fault.TooManyDevices) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Number of virtual devices exceeds the maximum for a given controller.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   property = <unset>\n}\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1594207975.0291607-81343907565645/AnsiballZ_vmware_guest_network.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1594207975.0291607-81343907565645/AnsiballZ_vmware_guest_network.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1594207975.0291607-81343907565645/AnsiballZ_vmware_guest_network.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vmware_guest_network', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vmware_guest_network_payload_3fagnfrv/ansible_vmware_guest_network_payload.zip/ansible/modules/cloud/vmware/vmware_guest_network.py\", line 486, in <module>\n  File \"/tmp/ansible_vmware_guest_network_payload_3fagnfrv/ansible_vmware_guest_network_payload.zip/ansible/modules/cloud/vmware/vmware_guest_network.py\", line 478, in main\n  File \"/tmp/ansible_vmware_guest_network_payload_3fagnfrv/ansible_vmware_guest_network_payload.zip/ansible/modules/cloud/vmware/vmware_guest_network.py\", line 434, in reconfigure_vm_network\n  File \"/tmp/ansible_vmware_guest_network_payload_3fagnfrv/ansible_vmware_guest_network_payload.zip/ansible/module_utils/vmware.py\", line 82, in wait_for_task\n  File \"<string>\", line 3, in raise_from\nansible.module_utils.vmware.TaskError: ('Number of virtual devices exceeds the maximum for a given controller.', None)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
