### ISSUE TITLE
Apache2_module generates false/misleading warning

### ISSUE THREAD

**Issue by tw-alexb** [ansible/ansible#70534]
##### SUMMARY
  
This warning is in some cases misleading and simply false:
```bash
TASK [Example : Disable MPM event module] *************************************************
changed: [localhost] => (item={u'state': u'absent', u'module': u'mpm_event'})
changed: [localhost] => (item={u'state': u'present', u'module': u'mpm_prefork'})
[WARNING]: No MPM module loaded! apache2 reload AND other module actions will fail if no MPM
module is loaded immediately.
```
In case exchanging **mpm_event** module immediately with **mpm_prefork** module generates an false/misleading warning. See message above.

This could be simply fixed by adding an optional warn option:

*PLAYBOOKEXAMPLE*
```yaml
- name: Disable MPM event module
  apache2_module:
    name: "{{ item.module}}"
    state: "{{ item.state}}"
    warn: False
    ignore_configcheck: true
  notify: restart apache
  with_items:
    - { module: mpm_event, state: absent}
    - { module: mpm_prefork, state: present }
```
*FIX*
```diff
--- /tmp/apache2_module.py	2020-07-09 06:17:36.362110994 +0000
+++ /tmp/apache2_module.py	2020-07-09 06:26:36.816560014 +0000
@@ -140,10 +140,11 @@
         error_msg = "Error executing %s: %s" % (control_binary, stderr)
         if module.params['ignore_configcheck']:
             if 'AH00534' in stderr and 'mpm_' in module.params['name']:
-                module.warnings.append(
-                    "No MPM module loaded! apache2 reload AND other module actions"
-                    " will fail if no MPM module is loaded immediately."
-                )
+                if module.params['warn']:
+                  module.warnings.append(
+                      "No MPM module loaded! apache2 reload AND other module actions"
+                      " will fail if no MPM module is loaded immediately."
+                  )
             else:
                 module.warnings.append(error_msg)
             return False
@@ -246,6 +247,7 @@
             force=dict(required=False, type='bool', default=False),
             state=dict(default='present', choices=['absent', 'present']),
             ignore_configcheck=dict(required=False, type='bool', default=False),
+            warn=dict(required=False, type='bool',default=True)
         ),
         supports_check_mode=True,
     )

```

*EXPECTED RESULT WITHOUT FALSE WARNING*
```bash
TASK [Example : Disable MPM event module] *************************************************
changed: [localhost] => (item={u'state': u'absent', u'module': u'mpm_event'})
changed: [localhost] => (item={u'state': u'present', u'module': u'mpm_prefork'})
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

apache2_module.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.1
```

##### CONFIGURATION

```paste below
NOT RELEVANT
```
