### ISSUE TITLE
UnicodeDecodeError on probe to set docker ENV variable with non ASCII chars

### ISSUE THREAD

**Issue by EGD** [ansible/ansible#70540]
##### SUMMARY

If i put any Cyrillic chars in docker ENV then running `ansible-playbook myapp.yml` fails with Python error:
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 17: ordinal not in range(128)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module `docker_container`

##### ANSIBLE VERSION

```
ansible 2.9.6
ansible python module location = /usr/lib/python3.6/site-packages/ansible
python version = 3.6.10 (default, Jan 16 2020, 09:12:04) [GCC]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

RedHat Enterprise Linux 7.2
python 2.7

##### STEPS TO REPRODUCE

```yaml
---

- name: pull image and restart container
  docker_container:
    image: "{{ registry_url }}/myapp/app:{{ myapp_version }}"
    name: my_app
    command: myapp
    hostname: "{{ ansible_fqdn }}"
    network_mode: host
    state: started
    restart_policy: always
    pull: yes
    ports:
      - "8081:8081"
      - "18081:18081"
    volumes:
      - "{{ opt_directory }}/kerberos:/opt/kerberos"
    log_driver: "json-file"
    log_options:
      max-size: "100m"
      max-file: "20"
    env:
      JAVA_OPTS: "{{ java_opts }}"
      MYAPP_LICENCE_TO: "ОАО «РогаИКопыта»"
      MYAPP_LICENCE_KEY: "{{ licence_key }}"
```

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

```paste below
MODULE FAILURE
File \"/tmp/ansible_docker_container_payload_LJPmWa/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py\", line 2174, in has_different_configuration\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 17: ordinal not in range(128)\r\n"
```
