### ISSUE TITLE
Feature Request: "merge" attribute for set_fact module

### ISSUE THREAD

**Issue by steelcowboy** [ansible/ansible#70585]
##### SUMMARY
In order to make `set_fact` more useful for deeply nested dictionaries, I propose a "merge" option which will enable `set_fact` to natively change individual values in a nested dictionary without writing an unfriendly amount of Jinja to preserve the existing values.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
set_fact.merge (boolean)

##### ADDITIONAL INFORMATION
This feature would resolve #32547. On that issue [a blog post is linked](https://www.jeffgeerling.com/blog/2017/changing-deeply-nested-dict-variable-ansible-playbook) which shows a Jinja solution to setting deeply nested variables. Using the example from the blog post as a basis, here is what this feature request seeks to implement:

## vars
```yaml
vars:
  animals:
    mammals:
      humans:
        eyes: many-colored
        legs: two
    birds:
      cardinals:
        eyes: black
        feathers: blue # <-- we want to change this to 'red'.
```
## current solution
```yaml
- name: Change animals.birds.cardinals.feathers to "red".
  set_fact:
    animals: "{{ animals|combine({'birds': {'cardinals': {'feathers': 'red'}}}, recursive=True) }}"
```
## proposed solution
```yaml
- name: Change animals.birds.cardinals.feathers to "red".
  set_fact:
    animals:
      birds:
        cardinals:
          feathers: red
    merge: yes
```

As part of the way "merge" works, it would also set values if the target key is `null`. Expanding on this, I propose it would be able to merge lists too. As such, if a user specifically wanted to clear out a value so that it could be replaced they would first set it to null; the next time the value is set with `merge` it would be a set operation, and subsequent merges would function as expected. 

Consider the following example:
## vars
```yaml
vars:
  packages:
    install: ['neovim]
    remove: ['fasd']
    upgrade: ['ansible']
```

## proposed solution
```yaml
- name: Clear our removal list
  set_fact:
    packages:
      remove: null
    merge: yes

- name: Update packages list 
  set_fact:
    packages:
      install:
        - zsh
        - git
      remove:
        - autojump  
    merge: yes

- name: Show us the packages
  debug: var=packages
```
### theoretical output
```
ok: [localhost] => {
    "packages": {
        "install": [
            "neovim",
            "zsh",
            "git",
        ],
        "remove": [
            "autojump",
        ],
        "upgrade": [
            "ansible",
        ],
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
We have no plans to add merging to `set_fact` at this time. The example task in the description is the recommended solution. You could make it a bit eaiser to read by using `vars` on the task.

```yaml
- name: Change animals.birds.cardinals.feathers to "red".
  set_fact:
    animals: "{{ animals|combine(my_birds, recursive=True) }}"
  vars:
    my_birds:
      birds:
        cardinals: 
          feathers: red
```

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-devel on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
