### ISSUE TITLE
Extend CloudWatch Rules' ecs_parameters

### ISSUE THREAD

**Issue by duderamos** [ansible/ansible#70674]
##### SUMMARY

I want to be able to provide more parameters for targets in to cloudwatch_rule smodule. Currently, there is no way to define ECS `LaunchType` and `NetworkConfiguration`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cloudwatch_rule

##### ADDITIONAL INFORMATION

This change will allow users to specify some new parameters under `ecs_parameter` as the example below:

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Schedule for Foo
    cloudwatchevent_rule:
      name: run_foo
      state: enabled
      schedule_expression: "rate(60 minutes)"
      targets:
      - id: run-job-foo
        arn: arn:aws:ecs:ap-southeast-2:123456789123:cluster/jobs-cluster
        role_arn: arn:aws:iam::123456789123:role/ecsEventsRole
        ecs_parameters:
          launch_type: FARGATE
          network_configuration:
            awsvpc_configuration:
              assign_public_ip: ENABLED
              security_groups:
              - sg-58519c0e3db6f851
              subnets:
              - subnet-0c4b66b1d07e4e0c
          task_definition_arn: arn:aws:ecs:ap-southeast-2:123456789123:task-definition/task-to-run:1
          task_count: 1
```
