### ISSUE TITLE
Option to explicitly set the IP address when using the `uri` module

### ISSUE THREAD

**Issue by rysiekpl** [ansible/ansible#70707]
##### SUMMARY
An option to explicitly set the IP address to be used by the `uri` module when making the request would make it possible to hit a particular endpoint in case a given domain resolves to multiple IP addresses.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`uri` module

##### ADDITIONAL INFORMATION

Such an option would thus make it possible to use in checks on the target host. For example, let's say `admin.example.org` points to multiple IP addresses on multiple hosts (for failover, high availability, and such). A configuration change is deployed to all of them via Ansible. It would be good to be able to have a handler or a task that would check if the expected endpoints respond in expected ways on each targeted host. That requires explicitly specifying each target's IP address to resolve `admin.example.org` to. 

This is currently only possible using `curl` via the `shell` module, as `curl` has the [`--resolve`](https://caiustheory.com/curl-resolve/) option.

```yaml
- name: check if the endpoints work as expected after configuration change
  listen: restart haproxy
  uri:
    url: "https://admin.example.com/login/"
    status_code: [200]
    resolve_ip: "{{ansible_facts.ansible_default_ipv4.address}}"
```
