### ISSUE TITLE
error while installing packages in ec2 RHEL instance using yum module

### ISSUE THREAD

**Issue by DiptoChakrabarty** [ansible/ansible#70774]
##### SUMMARY

I am trying to install a few packages in a fresh installed ec2 instance (Red Hat Image) using both the yum and package module but unable to install the packages as I am encountering the error everytime

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module used : yum and package both tried
Task: Install packages

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /home/chuck/Desktop/Projects/Ansible-Kube/ansible.cfg
  configured module search path = ['/home/chuck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]


```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

This is how I am connecting to the instance

hosts: 
  vars:
    ansible_python_interpreter: /usr/bin/python2
  remote_user: ec2-user
  connection: ssh
  become: yes
  gather_facts: no

(python2 installed)
and tried installing packages using both package and yum module (in place of package moudle used yum also)

name: install packages needed
  package:
    name: "{{ item }}"
    state: present 
    use_backend: yum
  with_items:
    - lvm2
    - device-mapper
    - curl 
    - device-mapper-persistent-data
    - device-mapper-event 
    - device-mapper-libs
    - device-mapper-event-libs

```

##### EXPECTED RESULTS

It should install all the neccessary packages

##### ACTUAL RESULTS

Unsupported parameters for (dnf) module: use_backend Supported parameters include: allow_downgrade, autoremove, bugfix, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_dir, download_only, enable_plugin, enablerepo, exclude, install_repoquery, install_weak_deps, installroot, list, lock_timeout, name, releasever, security, skip_broken, state, update_cache, update_only, validate_certs"

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rukman7** [comment]
Hi @DiptoChakrabarty, **use_backend** parameter is not a part of the package module. Try with **use** instead of **use_backend**
like this:
```
name: install packages needed
  package:
    name: "{{ item }}"
    state: present 
    use: yum
  with_items:
    - lvm2
    - device-mapper
```
code documentation I referenced: https://github.com/ansible/ansible/blob/v2.9.7/lib/ansible/modules/packaging/os/package.py
