### ISSUE TITLE
use of environment keyword in multiple roles

### ISSUE THREAD

**Issue by nicohouillon** [ansible/ansible#70793]
##### SUMMARY
in previous version of ansible we environment keyword was not evaluated prior to tasks and roles, now that it is it changes the way to pass environment to all subsequent roles .
workaround is to :
- use include_roles in a loop with apply  parameter , caveat is we have to redefine again and again the environment 
- use import_role and module default, caveat is we can't loop in imort_role

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
environment keyword

##### ANSIBLE VERSION

```paste below
ansible 2.8.13
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

python 3.6 
ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
# example for include_role , here if another condition is needed, you have to redefine the whole block a duplicate the environment part
 - include_role:
      name: '{{ item}}'
      apply:
        tags: [one, two] 
        # environment: "{{ my_aws_creds }}"
        environment:
          my_aws_creds: "{{my_aws_creds}}"
          AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
          AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
          AWS_SECURITY_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
    loop:
      - roletest
      - roletest2
    # loop_control:  
    when: mycondition is defined 



 # example for import_role ,  here no 'when' nor 'loop'  keywords , have to define a new task for every single role to import 
  tasks:  
    module_defaults:
      group/aws:
        aws_access_key: '{{ assumed_role.sts_creds.access_key }}'
        aws_secret_key: '{{ assumed_role.sts_creds.secret_key }}'
        security_token: '{{ assumed_role.sts_creds.session_token }}'
    # environment: "{{my_aws_creds}}"
    - import_role:
        name: test2

```

##### EXPECTED RESULTS
credentials to be passed to every single roles as environment

##### ACTUAL RESULTS
some module find the env some don't. 
repetition in environment definition
not able to use a loop

```paste below

```
