### ISSUE TITLE
Dry run mode with docker_container and env_vars: FileNotFoundError

### ISSUE THREAD

**Issue by Bablzz** [ansible/ansible#70809]
### SUMMARY
Hello everyone!

When try dry run with docker_container module and env_file parameter I got
The error was: FileNotFoundError: [Errno 2] No such file or directory 

but want 
```
 {
-    "exists": false
+    "exists": true
 }

```

```
ansible-playbook playbooks/test.yml -i inventory/local -c local --check -D
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container with dry run

##### ANSIBLE VERSION

```
ansible 2.9.7
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING() = True
ANSIBLE_SSH_ARGS() = -o ControlMaster=auto -o ForwardAgent=yes -o ControlPersist=10m -o PreferredAuthentications=publickey
DEFAULT_ROLES_PATH() = [u']
HOST_KEY_CHECKING() = False
RETRY_FILES_ENABLED() = False
STRING_CONVERSION_ACTION() = error

```

##### OS / ENVIRONMENT

Linux  5.3.0-61-generic #55~18.04.1-Ubuntu

##### STEPS TO REPRODUCE

add role with docker_container with env_file parameters and run in dry run mode
```
- name: run docker
  docker_container:
    image: "{{ image }}"
    name: "{{name }}"
    network_mode: host
    restart_policy: always
    env_file: "service.env" 
    state: started
```

##### EXPECTED RESULTS
```
 {
-    "exists": false
+    "exists": true
 }

```

##### ACTUAL RESULTS
```
The error was: FileNotFoundError: [Errno 2] No such file or directory 
```
