### ISSUE TITLE
Module 'group_by' report changed even with 'changed_when: false'

### ISSUE THREAD

**Issue by chemnic** [ansible/ansible#70844]
##### SUMMARY
After upgrade from 2.9.10 to 2.9.11 I noticed the module 'group_by' is reporting 'changed'.
This is because this change in #69860 
The problem is that it is reporting 'changed' even with `changed_when: false` added to the task.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

group_by

##### ANSIBLE VERSION

```paste below
2.9.11
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04 (control and target host)

##### STEPS TO REPRODUCE

As an example use the task:
```
- group_by:
    key: "os_{{ ansible_facts['distribution_file_variety'] }}"
  changed_when: false
  register: groupby

- debug:
    msg: "{{ groupby }}"
```

```yaml
TASK [group_by_os : group_by] *******************************************************************************************************************************
changed: [srvd-test04]

TASK [group_by_os : debug] **********************************************************************************************************************************
ok: [srvd-test04] => 
  msg:
    add_group: os_Debian
    changed: true
    failed: false
    parent_groups:
    - all

PLAY RECAP **************************************************************************************************************************************************
srvd-test04                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

##### EXPECTED RESULTS

The task should always return `changed: false`

##### ACTUAL RESULTS

The task return `changed: true`

```paste below

```
