### ISSUE TITLE
virt module get_xml command should support flags

### ISSUE THREAD

**Issue by braindevices** [ansible/ansible#70852]
##### SUMMARY

`libvirt XMLDesc(flags)` The flag is important, some time we want to have `VIR_DOMAIN_XML_SECURE` to get sensitive info. In most cases we want to use `VIR_DOMAIN_XML_INACTIVE` for running VMs, in some cases we want to get the live state. So far the module use flag=0 which is live one without sensitive data. We need to give an additional flag parameter for this.
##### ISSUE TYPE
- add a flags parameter to pass into  XMLDesc(), it can just be a list of int.

##### COMPONENT NAME

virt
##### ADDITIONAL INFORMATION

`virt: command=get_xml flags=[...]`
For example, if we want inactive state with sensitive info:

```yaml
- virt:
    command: get_xml
    name: vm1
    flags:
       - 1
       - 2

```
