### ISSUE TITLE
Should with_sequence be evaluated before when? even inside a block?

### ISSUE THREAD

**Issue by reefland** [ansible/ansible#70865]
##### SUMMARY
Task expected to be skipped based on `when` condition fails due to `with_sequence` value.

Additionally, if task is placed within a `block` with a `when` condition, all tasks within the block are skipped as expected, except the one with a `with_sequence` which fails.  I expect it to not be evaluated and skipped as well.  

I reviewed the documentation for conditionals, there is a section `Loops and Conditionals`, it's not clear this applies as examples are specific to `loop`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

with_sequence or when

##### ANSIBLE VERSION

```ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rich/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

##### CONFIGURATION

```
nothing listed
```

##### OS / ENVIRONMENT

Manjaro control node`5.6.19-2-MANJARO #1 SMP PREEMPT Wed Jun 17 22:24:52 UTC 2020 x86_64 GNU/Linux`
Ubuntu 20.04 target `5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

##### STEPS TO REPRODUCE

The actual use case is building a ZFS pool of many mirrored vdevs.  The first 2 devices (0 and 1) make the initial pool, then devices 2 through `device_count - 1` are processed 2 at a time adding a mirrrored vdev to the pool.  I can give it 10 devices, the pool is correctly created (pool of 5 mirrored vdevs).  The problem is when only 2 devices exist, the initial pool is created, there are no other devices to process, the step should be skipped.

I've reduced it down to a very simple use case.

```yaml
  - name: Test 2
    set_fact:
      device_count: 2

  # This should be skipped since device_count is lower than when condition
  - name:  "Do sequence steps start=2 stride=2 end={{device_count|int -1}}"
    command:
      "echo {{item}}"
    with_sequence: start=2 stride=2 end="{{device_count|int -1}}"
    when:
      - device_count|int > 3
```

##### EXPECTED RESULTS

I expect the step to be skipped based on `when` condition statement.  I understand the sequence is invalid, that's why I define a  `when` condition where it should be executed.

##### ACTUAL RESULTS

```paste below
TASK [Test 2] **********************************************************************************************************************************************************************
task path: /home/rich/Sync/rich/ansible/ansible_bug.yml:19
ok: [localhost] => {
    "ansible_facts": {
        "device_count": 2
    },
    "changed": false
}

TASK [Do sequence steps start=2 stride=2 end=1] ************************************************************************************************************************************
task path: /home/rich/Sync/rich/ansible/ansible_bug.yml:25
fatal: [localhost]: FAILED! => {
    "msg": "to count backwards make stride negative"
}

```

Additionally, a `with_sequence` used within a `block` is evaluated despite a `when` condition saying to skip.
```
  # Everything in this block should be skipped
  - name: Test 2
    set_fact:
      device_count: 2

  - name: Same sequence test in a block
    block:
      - name: Simple steps in a block
        command: "echo 'This is expected to be skipped'"

      - name: Simple steps in a block
        command: "echo 'This is expected to be skipped'"

      - name:  "Sequence steps expected to be skipped"
        command: "echo 'count:' {{item}}"
        with_sequence: start=2 stride=2 end="{{device_count|int -1}}"
    when:
      - device_count|int > 3
```

Results:
```
TASK [Test 2] **********************************************************************************************************************************************************************
task path: /home/rich/Sync/rich/ansible/ansible_bug.yml:33
ok: [localhost] => {
    "ansible_facts": {
        "device_count": 2
    },
    "changed": false
}

TASK [Simple steps in a block] *****************************************************************************************************************************************************
task path: /home/rich/Sync/rich/ansible/ansible_bug.yml:39
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [Simple steps in a block] *****************************************************************************************************************************************************
task path: /home/rich/Sync/rich/ansible/ansible_bug.yml:42
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [Sequence steps expected to be skipped] ************************************************************************************************************************************
task path: /home/rich/Sync/rich/ansible/ansible_bug.yml:45
fatal: [localhost]: FAILED! => {
    "msg": "to count backwards make stride negative"
}

```
