### ISSUE TITLE
lineinfile module sometimes never comes back

### ISSUE THREAD

**Issue by sleif** [ansible/ansible#70867]
##### SUMMARY
lineinfile module sometimes never comes back

It seems to have something to do with regexp and backrefs

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lineinfile module

##### ANSIBLE VERSION
```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
empty output from "ansible-config dump --only-changed"
```

##### OS / ENVIRONMENT
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 8.2.2004 (Core)
Release:	8.2.2004
Codename:	Core
```

##### STEPS TO REPRODUCE

* test.yml
```yaml
---
- hosts:
  - localhost

  tasks:
    - name: lineinfile test
      lineinfile:
        dest: test.txt
        backrefs: True
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
      loop:
        - { line: '\1 someNewString', regexp:    '(^ok_line=([\"\s]*(?!someNewString)[\w]+)*)\s*$' }
        - { line: '\1 someNewString', regexp:    '(^ko_line=([\"\s]*(?!someNewString)[\w]+)*)\s*$' }
      # async: 5
      # poll: 5
```

* destination file test.txt
```
ok_line=abcdefghijklmnopqrstuvw someNewString
ko_line=abcdefghijklmnopqrstuvwx someNewString
```

##### EXPECTED RESULTS

* both lines will be ok, ansible-playbook call ends with RC=0

##### ACTUAL RESULTS

* only the line containing "ok_line" works, the ko_line never comes back without async and poll parameters
```paste below
[root@localhost ansible-test]# ansible-playbook test.yml -vv
ansible-playbook 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAYBOOK: test.yml ****************************************************************************************************
1 plays in test.yml

PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
task path: /root/ansible-test/test.yml:2
ok: [localhost]
META: ran handlers

TASK [lineinfile test] ************************************************************************************************
task path: /root/ansible-test/test.yml:6
ok: [localhost] => (item={'line': '\\1 someNewString', 'regexp': '(^ok_line=([\\"\\s]*(?!someNewString)[\\w]+)*)\\s*$'}) => {"ansible_job_id": "313029406309.38535", "ansible_loop_var": "item", "backup": "", "changed": false, "finished": 1, "item": {"line": "\\1 someNewString", "regexp": "(^ok_line=([\\\"\\s]*(?!someNewString)[\\w]+)*)\\s*$"}, "msg": ""}
failed: [localhost] (item={'line': '\\1 someNewString', 'regexp': '(^ko_line=([\\"\\s]*(?!someNewString)[\\w]+)*)\\s*$'}) => {"ansible_loop_var": "item", "changed": false, "item": {"line": "\\1 someNewString", "regexp": "(^ko_line=([\\\"\\s]*(?!someNewString)[\\w]+)*)\\s*$"}, "msg": "async task did not complete within the requested time - 5s"}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
