### ISSUE TITLE
docker_container fails to find local images

### ISSUE THREAD

**Issue by RedLine89** [ansible/ansible#70876]
##### SUMMARY

docker_container task is not able to find a locally created image and attempts to pull one from DockerHub instead with no success. This effectively fails the whole job, so we are not able to start any container using Ansible. This issue manifests only for custom built images(names) and only in Oracle Linux with docker package `docker-cli-19.03.11.ol-4.el7.x86_64`. Downgrading to `docker-engine-18.03.1.ol-0.0.9.el7.x86_64` solves the problem.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
/playbook # ansible --version
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
/playbook #
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
NAME="Oracle Linux Server"
VERSION="7.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Oracle Linux Server 7.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.8
```

##### STEPS TO REPRODUCE

```yaml
[user@admin-vm pipeline-bug]$ cat Dockerfile
FROM nginx:1.17-alpine

EXPOSE 80

WORKDIR /app
[user@admin-vm pipeline-bug]$ cat main.yml
---
  - name: Playbook to deploy application in the container
    hosts: pipeline-bug-vm
    gather_facts: no

    vars:
      project_name: pipeline-bug

    tasks:
      - name: Copying the code
        copy:
          src: Dockerfile
          dest: "/tmp/{{ project_name }}/Dockerfile"

      - name: Building the new image
        docker_image:
          name: "{{ project_name }}"
          build:
            pull: yes
            path: "/tmp/{{ project_name }}"
          source: build
          force_source: yes
          state: present
          tag: latest

      - name: start the new container (DEVELOPMENT)
        docker_container:
          name: "{{ project_name }}"
          image: "{{ project_name }}"
          restart_policy: always
[user@admin-vm pipeline-bug]$
[user@admin-vm pipeline-bug]$ ansible-playbook -i hosts main.yml
```

##### EXPECTED RESULTS

After the image with project name is built the container should start. This work fine on Docker 18.

```
[user@admin-vm pipeline-bug]$ ansible-playbook -i hosts main.yml

PLAY [Playbook to deploy application in the container] ********************************************************************************************************

TASK [Copying the code] ***************************************************************************************************************************************
[WARNING]: Platform linux on host pipeline-bug-vm is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
changed: [pipeline-bug-vm]

TASK [Building the new image] *********************************************************************************************************************************
changed: [pipeline-bug-vm]

TASK [start the new container (DEVELOPMENT)] ******************************************************************************************************************
changed: [pipeline-bug-vm]

PLAY RECAP ****************************************************************************************************************************************************
pipeline-bug-vm            : ok=3    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[user@admin-vm pipeline-bug]$
```

##### ACTUAL RESULTS

This is what happens if we use Docker 19.
P.S. When specifying a public Dockerhub image like `nginx` in `docker_container` task, it won't error

```paste below
[user@admin-vm pipeline-bug]$ ansible-playbook -i hosts main.yml

PLAY [Playbook to deploy application in the container] *********************************************************************************************************************************************************************

TASK [Copying the code] ****************************************************************************************************************************************************************************************************
[WARNING]: Platform linux on host pipeline-bug-vm is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [pipeline-bug-vm]

TASK [Building the new image] **********************************************************************************************************************************************************************************************
changed: [pipeline-bug-vm]

TASK [start the new container (DEVELOPMENT)] *******************************************************************************************************************************************************************************
fatal: [pipeline-bug-vm]: FAILED! => {"changed": false, "msg": "Error pulling pipeline-bug - code: None message: pull access denied for pipeline-bug, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}

PLAY RECAP *****************************************************************************************************************************************************************************************************************
pipeline-bug-vm            : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[user@admin-vm pipeline-bug]$

```
