### ISSUE TITLE
vmware_guest Module - VM deployment fails if more than 1 extra disk is added

### ISSUE THREAD

**Issue by N1ghtH4wk196** [ansible/ansible#70870]
##### SUMMARY
Since updating vSphere to 7.0.0, we are unable to deploy VM's from a template if the vm configuration has more than 2 extra disks than the template, for example, if the tempalte has 1 disk  then

VM with 1 extra disk - Deploys with out issue
VM with 2 Extra disks - Error reported

ansible 2.9.9
vSphere 7.0.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mark.hammond/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 27 2019, 09:57:45) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /opt/ansible/.secret/.vault_password
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
vSphere 7.0
OS independent - Tested on Redhat, Oracle Linux and Windows 2019

##### STEPS TO REPRODUCE

Create a VM with 1 Disk,  convert to template
Deploy using below playbook, which specifies 2 extra disks

``` yaml
# Load variables from files
- hosts: all
  vars:
    creation_timestamp: "{{ lookup('pipe','date +%Y-%m-%d_%H:%M:%S') }}"
  vars_files:
    - /opt/ansible/vars/windows_datacenter_config.yml
    - /opt/ansible/vars/master_vault.yml
  vars_prompt:

  gather_facts: no

# set correct username if we are accessing ovh.
  tasks:
 # Build VM from template
     name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vcenter[location] }}"
        username: "{{ autobuild_username }}{{ authdomain[location] }}"
        password: "{{ autobuild_password }}"
        validate_certs: False
        datacenter: "{{ datacenter[location] }}"
        cluster: "{{ cluster }}"
        folder: "{{ folder }}"
        name: "{{ inventory_hostname }}"
        state: "{{ vm_state |default('poweredon') }}"
        template: "{{ template }}"
        disk: "{{ vmdisk }}"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          hotadd_cpu: True
          hotremove_cpu: False
          hotadd_memory: True
        networks:
          - name: "{{portgroup01}}"
            ip: "{{ip01}}"
            netmask: "{{netmask01}}"
            gateway: "{{gateway01}}"
            device_type: "{{nic01}}"
        customization:
          autologon: yes
          dns_servers: "{{ dns_servers[location][ad_domain] }}"
          joindomain: ""
          domainadmin: "{{ join_domain_username[ad_domain]}}@{{ ad_domain }}"
          domainadminpassword: "{{ join_domain_password[ad_domain] }}"
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
          - netsh advfirewall set allprofiles state off
        wait_for_customization: yes
        annotation: "{{ creation_timestamp }} | ansible created | {{ description }}"
      delegate_to: localhost
      register: deploy
      tags: Exclude

```
Inventory

all:
  hosts:
   testbuild:
     nic01: vmxnet3
     ip01: 172.0.0.100
     cpu: 1
     ram: 2048
     template: Template_WIN2019_STD
     netmask01: 255.255.255.0
     portgroup01: "protgroup"
     gateway01: 172.0.0.1
     cluster: cluster_name
     folder: AutomationOnly
     description: "test build Server"
     vmdisk:
     - size_gb: 60
       datastore: datastore01
     - size_gb: 10
       datastore: datastore01
     - size_gb: 20
       datastore: datastore01

##### EXPECTED RESULTS

VM deploys with the specified number of disks added

##### ACTUAL RESULTS

An error is produced:
fatal: [VMNAME]: FAILED! => {"changed": false, "msg": "Failed to create a virtual machine : A specified parameter was not correct: deviceChange[1].device.key"}

THIS WORKS IN VSPHERE 6.7

```paste below
fatal: [VMNAME]: FAILED! => {"changed": false, "msg": "Failed to create a virtual machine : A specified parameter was not correct: deviceChange[1].device.key"}
```
