### ISSUE TITLE
Variable merging fails to occur even if "hash_behavior" is set to merge.

### ISSUE THREAD

**Issue by danieljaouen** [ansible/ansible#7091]
##### Issue Type:

Bug report.
##### Ansible Version:

```
± ansible --version
ansible 1.6 (brew 9338e2726f) last updated 2014/04/20 16:23:05 (GMT -400)
```
##### Environment:

OS X 
##### Summary:

Dictionary variables are not merged correctly even if the `hash_behavior` option is set to `merge`.
##### Steps To Reproduce:
1. Modify `~/.ansible.cfg` to look like this:

``` ini
[defaults]
hash_behavior = merge
```
1. Create a new role with the following tasks:

``` yaml
# file: roles/debug/tasks/main.yml

---
- name: main | debug
  debug: "msg='{{ test.three }} and {{ test.two }} and {{ test.one }}'"
```

And the following defaults:

``` yaml
# file: roles/debug/defaults/main.yml

---
test:
  one: 'This is the first variable.'
```

And the following vars:

``` yaml
# file: roles/debug/vars/main.yml

---
test:
  two: 'This is the second variable.'

test:
  three: 'This is the third variable.'
```
##### Expected Results:

The debug modules prints out:

```
 This is the third variable. and This is the second variable. and This is the first variable.
```
##### Actual Results:

I receive the following error:

```
TASK: [debug | main | debug] **************************************************
fatal: [127.0.0.1] => One or more undefined variables: 'dict object' has no attribute 'two'

FATAL: all hosts have already failed -- aborting
```
