### ISSUE TITLE
Convert aws_profiles from string to list so that we can have multiple aws accounts for dynamic inventory

### ISSUE THREAD

**Issue by dhikrahashim** [ansible/ansible#70928]
##### SUMMARY

We have "aws_ec2" plugin for dynamic inventory, suppose if we have multiple AWS accounts we need to create inventory for each AWS account. If the aws_profile parameter is "list" type we need only one inventory playbook to fetch the inventories. We can use "with_items" or "loop" I guess
##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml
plugin: aws_ec2
aws_profile:
  - new-relic-aws
  - splunk-aws
  - application-aws
  - database-aws
```
