### ISSUE TITLE
ntebox_interface: Failed to establish connection to Netbox API

### ISSUE THREAD

**Issue by misch42** [ansible/ansible#70934]
##### SUMMARY
After the latest upgrade the netbox_interface module stopped working with the error message: "Failed to establish connection to Netbox API" 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module: netbox_interface 

##### ANSIBLE VERSION
```
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/napalm_ansible']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
Plain ansible installation for testing
```
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/napalm_ansible']

```

##### OS / ENVIRONMENT
CentOS 8

##### STEPS TO REPRODUCE

I took the example playbook from the modules website

```
---
- name: Get interfaces into netbox
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: create interface
    netbox_interface:
      netbox_url: http://127.0.0.1:8001
      netbox_token: XXXX
      data:
        device: switch07
        name: GigabitEthernet0/1
      state: present
```

##### EXPECTED RESULTS

Insert interface into netbox.

##### ACTUAL RESULTS
```
ansible-playbook -vvvv create_interface.yaml
(...)
The full traceback is:
  File "/tmp/ansible_netbox_interface_payload_fyybuitm/ansible_netbox_interface_payload.zip/ansible/modules/net_tools/netbox/netbox_interface.py", line 258, in main
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "device": "switch07",
                "name": "GigabitEthernet0/1"
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "http://127.0.0.1:8001",
            "state": "present",
            "validate_certs": false
        }
    },
    "msg": "Failed to establish connection to Netbox API"
}

```

This worked before the latest upgrade on the system.
