### ISSUE TITLE
Cloud Module for Azure API Management

### ISSUE THREAD

**Issue by Leon-Africa** [ansible/ansible#70938]
Would be nice to have a module for this as with Azure API Management.

https://docs.ansible.com/ansible/latest/modules/aws_api_gateway_module.html#aws-api-gateway-module 

##### SUMMARY
An Ansible module that allows for the management of Azure API Management API's

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure_api_managment – Manage Amazon API Management APIs

##### ADDITIONAL INFORMATION
Would be able to create, manage API Management API's and configurations from the Module. Would not need to do an entire ARM deployment. 

```
# Update API resources for development
- name: update API
  azure_api_management:
    api_id: 'abc123321cba'
    state: present
    swagger_file: my_api.yml / json

# update definitions and deploy API to production
- name: deploy API
 azure_api_management:
    api_id: 'abc123321cba'
    state: present
    swagger_file: my_api.yml / json
    stage: production
    deploy_desc: Make auth fix available.

```
