### ISSUE TITLE
galaxy install should accept a list sources to install a role or collection from

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#70969]
##### SUMMARY
We would like to be able to define a list of locations from which a role or collection can be installed instead of being forced to have a single location defined in `requirements.yml` files.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/galaxy/role.py

##### ADDITIONAL INFORMATION

CI/CD testing requires ability to install unmerged code from dependencies and in order to be able to implement it we need to allow galaxy to lookup to multiple locations for the source of the role.

```yaml
- name: tripleo-ansible
  scm: git
  src:  # try each source and use first found
    - ~/src/tripleo-ansible
    - https://opendev.org/openstack/tripleo-ansible
```

This design also has other benefits as it enables caching/mirroring, making possible to perform more resilient dependency installation.

In order to avoid current design limitation we had to rely of quire ugly hacks like https://review.opendev.org/#/c/743562/1/tripleo_heat_templates/tests/test_tht_ansible_syntax.yml in order to install the unmerged tested dependency.

Lack of this feature introduced bugs in testing pipelines as users had the expectation that "depends-on" worked when in fact it did not. Being able to list sources, would allow us to overcome this.

If the spec is agreed, I can work on proposing an implementation for it.
