### ISSUE TITLE
Ansible adding extra disk on vmware_guest

### ISSUE THREAD

**Issue by amitbhadra** [ansible/ansible#70982]
##### SUMMARY
I'm trying to create a VM from a template using the vmware_guest functionality. It works fine for all conditions except one where it is adding an extra disk. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```ansible 2.9.10
```

##### OS / ENVIRONMENT
CentOS7 and MAC OS X

##### STEPS TO REPRODUCE
The first step is to have a template with the following configurations - 
For that, create a VM with - 
```
8 disks.
Assign disks 1, 2 to SCSI controller 0
Assign disks 3, 4 to SCSI controller 1
Assign disks 5, 6 to SCSI controller 2
Assign disks 7, 8 to SCSI controller 3
Memory-4GB
CPUs-2
Boot it up with CentOS 7
```
Now convert this VM to a template. 

The second step is to use Ansible to create a VM from this template. I'm using the code below. There are a lot of variables but you can use your own values.

```
- name: "Create a virtual machine from a template for {{ resource_pool }}"
  vmware_guest:
    hostname: "{{ hostname }}"
    username: "{{ host_email }}"
    password: "{{ host_password }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    folder: "/{{ datacenter }}/vm"
    datastore: "{{ cluster }}-vsan"
    resource_pool: "{{ resource_pool_vsphere }}"
    name: "{{ host_specification.new_vm_name | default(new_vm_name) }}"
    state: poweredon
    template: "{{ source_template_name }}"
    disk:
      - size_gb: "34"
        type: thin
      - size_gb: "34"
        type: thin
      - size_gb: "1"
        type: thin
      - size_gb: "2"
        type: thin
      - size_gb: "3"
        type: thin
      - size_gb: "4"
        type: thin
      - size_gb: "5"
        type: thin
      - size_gb: "6"
        type: thin
    hardware:
      memory_mb: "4096"
      num_cpus: "2"
      hotadd_memory: True
    networks:
      - name: "{{ host_network }}"
        device_type: "vmxnet3"
        netmask: "{{ netmask }}"
        ip: "{{ host_ip_address }}"
        gateway: "{{ gateway }}"
    customization:
      domain: "eng.vmware.com"
      hostname: "{{ host_specification.new_vm_name | default(new_vm_name) }}"
      dns_servers:
        - "{{ nameserver }}"
    wait_for_ip_address: yes
  delegate_to: localhost

```

##### EXPECTED RESULTS
The expected result is to have 8 disks as per the template and the Ansible task.

##### ACTUAL RESULTS
But the actual results are a little strange.
It is adding a 9th disk. The 8th disk takes the disk size of the 3rd disk(which is of SCSI controller 1). The 9th disk takes the disk size of what should have been the 8th disk and adds itself to SCSI controller 0 as SCSI (0,8).

This is the screenshot of the erroneous VM disks - 
![disk-error](https://user-images.githubusercontent.com/17934535/88855975-b4c62800-d1c1-11ea-862f-235bd6098a78.png)
