### ISSUE TITLE
pam_limits EOF issue when added a limit

### ISSUE THREAD

**Issue by luiscachog** [ansible/ansible#70986]
##### SUMMARY
I'm using the `pam_limits` module as shown:

```yaml
- name: task_numberX
      pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: core
        value: '0'
```

However, the first time that I've run `ansible-playbook` it generates this output on the `/etc/security/limits.conf` file:

```
# End of file*	hard	core	0
```

Noticed that the limit that I want to add is on the file but after the EOF message, and is commented too, so technically the change is not applied.

The second time when I run the task the output is:

```
# End of file*	hard	core	0
*	hard	core	0
```

So, now the change is applied but with `error`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
pam_limits

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /etc/ansible.cfg
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/username/.virtualenvs/ca-env/lib/python3.8/site-packages/ansible
  executable location = /Users/username/.virtualenvs/ansible-env/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible.cfg) = True
DEFAULT_GATHERING(/etc/ansible.cfg) = smart
DEFAULT_STDOUT_CALLBACK(/etc/ansible.cfg) = yaml
INTERPRETER_PYTHON(/etc/ansible.cfg) = auto
INVENTORY_ENABLED(/etc/ansible.cfg) = ['ini']
```

##### OS / ENVIRONMENT

target OS = RHEL 7.8

##### STEPS TO REPRODUCE

Run the following task:

```yaml
- name: task_numberX
      pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: core
        value: '0'
```

##### EXPECTED RESULTS

Limit added before the EOF:
```
*	hard	core	0
# End of file
```

Before the EOF marked as:

```
# End of file
```

##### ACTUAL RESULTS

on the `/etc/security/limits.conf` file:

```paste below
# End of file*	hard	core	0
```

Any help is appreciated.
