### ISSUE TITLE
redhat_subscription: syspurpose set arbitrary values

### ISSUE THREAD

**Issue by jcpunk** [ansible/ansible#71019]
##### SUMMARY
The syspurpose command permits setting arbitrary user defined strings and arrays.  Currently the ansible module redhat_subscription does not support this behaviour.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
redhat_subscription

##### ADDITIONAL INFORMATION
Adding this ability would permit additional user defined purposes that could be utilized for further description of a system's purpose and roles within a given environment.

```yaml
- name: Set user defined syspurpose entries
  redhat_subscription:
    state: present
    syspurpose:
      usage: "Production"
      role: "Red Hat Enterprise Server"
      service_level_agreement: "Premium"
      addons:
        - addon1
        - addon2
      set:
        in_dmz: True
        application: my application name
      add:
        extra_roles:
        - my_role
        - other_role
        application_contacts:
        - user1
        - user2
```
