### ISSUE TITLE
Add 'member' parameter for module 'ldap_entry' to allow creation of objets 'groupOfNames'

### ISSUE THREAD

**Issue by keducoop** [ansible/ansible#71015]
##### SUMMARY
First of all many thanks to all the people involved in this project for their time, I really appreciate it.

Add 'member' parameter for module 'ldap_entry'.
This would allow to implement LDAP entries such as:

```
dn: cn=my_group,ou=groups,dc=example,dc=com
cn: my_group
member: cn=user.one,ou=people,dc=example,dc=com
member: cn=user.two,ou=people,dc=example,dc=com
objectclass: groupOfNames
objectclass: top
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ldap_entry

##### ADDITIONAL INFORMATION
Given this variable:

```yaml
ldap_entries:
  groups:
    dn: "ou=groups,dc=example,dc=com"
    objectClass:
      - organizationalUnit
      - top
    attributes: {}
  people:
    dn: "ou=people,dc=example,dc=com"
    objectClass:
      - organizationalUnit
      - top
    attributes: {}
  test1:
    dn: "cn=test1,ou=people,dc=example,dc=com"
    objectClass:
      - inetOrgPerson
      - posixAccount
      - top
    attributes:
      gidnumber: 10000
      givenname: Test1
      homedirectory: /home/test1
      loginshell: /bin/bash
      mail: test1@example.com
      sn: Test1
      uid: test1
      uidnumber: 10000
      userPassword: test1
  test2:
    dn: "cn=test2,ou=people,dc=example,dc=com"
    objectClass:
      - inetOrgPerson
      - posixAccount
      - top
    attributes:
      gidnumber: 10000
      givenname: Test2
      homedirectory: /home/test2
      loginshell: /bin/bash
      mail: test2@example.com
      sn: Test2
      uid: test2
      uidnumber: 10001
      userPassword: test2
  nextcloud:
    cn: nextcloud
    dn: "cn=nextcloud,ou=groups,dc=example,dc=com"
    member:
      - "cn=test1,ou=people,dc=example,dc=com"
      - "cn=test2,ou=people,dc=example,dc=com"
    objectClass:
      - groupOfNames
      - top
```

We could create all the objects with below tasks:

`roles/ldap/tasks/main.yml`

```yaml
- name: Populate LDAP with entries
  include_tasks: populate.yml
  with_dict: "{{ ldap_entries }}"
```

`roles/ldap/tasks/populate.yml`

```yaml
- name: Create LDAP entry '{{ item.value.dn }}'
  ldap_entry:
    dn: "{{ item.value.dn }}"
    objectClass: "{{ item.value.objectClass }}"
    attributes: "{{ item.value.attributes }}"
    state: present
    server_uri: "ldap://ldap"
    bind_dn: "{{ ldap_object_admin }}"
    bind_pw: "{{ ldap_admin_password }}"
  when: item.value.attributes is defined
  tags: ldap

- name: Create group LDAP entry '{{ item.value.dn }}'
  ldap_entry:
    dn: "{{ item.value.dn }}"
    objectClass: "{{ item.value.objectClass }}"
    member: "{{ item.value.member }}"
    state: present
    server_uri: "ldap://ldap"
    bind_dn: "{{ ldap_object_admin }}"
    bind_pw: "{{ ldap_admin_password }}"
  when: item.value.member is defined
  tags: ldap
```
