### ISSUE TITLE
Age-based finds fail to recurse directories newer than requested mtime

### ISSUE THREAD

**Issue by ferricoxide** [ansible/ansible#71026]
##### SUMMARY
Age-based finds using `age_stamp=mtime` fail to recurse if directory containing eligible file is newer than the age threshold

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

find_module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['${HOME}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ${HOME}/linting/lib64/python3.6/site-packages/ansible
  executable location = ${HOME}/linting/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
```
NULL OUTPUT

##### OS / ENVIRONMENT

Source OS: `Red Hat Enterprise Linux Server release 7.8 (Maipo)` - hosted on VMsphere
Target OS: `Red Hat Enterprise Linux Server release 7.8 (Maipo)` - hosted on AWS

Using `pip`-installed Ansible within py3 venv (system Ansible version – experiences same issue – is from EPEL and is too old to use for some other tasks)

##### STEPS TO REPRODUCE

1. Select a RHEL 7.8 target that's a few days old
2. Ensure that `/var/log` contains subdirectories
3. Ensure that subdirectories contain a mix of files that have `mtime`s older and younger than the search threshold
4. Run the following play

Note: the following currently used mode-change rather than rm because play is in testing
```yaml
---
- name: Find log files to nuke
  hosts: all
  tasks:
    - name: Find all stale files
      find:
        age: 1d
        age_stamp: mtime
        file_type: file
        paths: /var/log
        hidden: yes
        recurse: yes
      register: files_to_nuke

    - name: Nuke all stale log files
      become: "yes"
      file:
        path: "{{ item['path'] }}"
        mode: '000000'
      with_items:
       - '{{ files_to_nuke.files }}'
...
```

##### EXPECTED RESULTS

Expect that all files older than `age` in the target's `/var/log` directory and subdirectories to be found and modes changed.

##### ACTUAL RESULTS

Only files of the requisite age in the specified `paths` (`/var/log`) are found

```paste below
$ ansible-playbook -u <REMOTE_USER> -i <TARGET_IP>, clean_logdir.yml 

PLAY [Find log files to nuke] **********************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
ok: [<TARGET_IP>]

TASK [Find all stale files] ************************************************************************************************************************************
ok: [<TARGET_IP>]

TASK [Nuke all stale log files] ********************************************************************************************************************************
ok: [<TARGET_IP>] => (item={'uid': 0, 'woth': False, 'mtime': 1593626396.0, 'inode': 69, 'isgid': False, 'size': 0, 'roth': False, 'isuid': False, 'isreg': True, 'pw_name': 'root', 'gid': 0, 'ischr': False, 'wusr': False, 'xoth': False, 'rusr': False, 'nlink': 1, 'issock': False, 'rgrp': False, 'gr_name': 'root', 'path': '/var/log/test', 'xusr': False, 'atime': 1593626396.0, 'isdir': False, 'ctime': 1596220248.9040997, 'isblk': False, 'xgrp': False, 'dev': 64771, 'wgrp': False, 'isfifo': False, 'mode': '0000', 'islnk': False})

PLAY RECAP *****************************************************************************************************************************************************
<TARGET_IP>               : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

Whereas, if one does a `find` from the remote system, it shows that there are files that Ansible is failing to locate:

```
# find /var/log -mtime +1 | xargs ls -ld
drwx------ 2 root   root        75 Jan 29  2020 /var/log/aide
-rw------- 1 root   root         1 Mar  3 15:22 /var/log/aide/aide.log
-rw------- 1 root   root         1 Mar  3 15:22 /var/log/aide/aide.log-20200103.gz
[...ELIDED...]
-rw-r----- 1 root   root         0 Jul  29 13:59 /var/log/sssd/test
---------- 1 root   root         0 Jul  29 13:59 /var/log/test
```

But the (e.g.) directory containing the matching file is less than the `mtime` value:
```
# ls -ld /var/log/sssd
drwxr-x--- 2 sssd sssd 4096 Jul 31 14:20 /var/log/sssd
```
