### ISSUE TITLE
doc with_fileglob looks in files (not templates)

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#7102]
##### Issue Type:

Doc Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

CentOS 6
##### Summary:

with_fileglob doesn't read from files in relative template dir.  There was a previous commit https://github.com/lorin/ansible/commit/d7ba2e06ebb516c70737c75d751a12b0c37d6fe9 to a doc page which no longer exists - that noted with_file(glob) looks in the relative _files_ folder
##### Steps To Reproduce:

create a role: tmp
create a bunch of template files:
tmp.sh, tmp2.sh - which do something simple like echo 'foo'
in the main.yml:

```

---
- name: check something
  template: src={{ item }} dest="/tmp/{{item | filename}}"
  with_fileglob:
    - '*.sh'
```

Create a playbook to run the role against localhost
##### Expected Results:

The role fails to find the files, referring to documentation would state that it sources from _files/_
##### Actual Results:

If moving the source files to path/to/role/files then it works.
