### ISSUE TITLE
Expose the loop label via ansible_loop.label

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#71021]
##### SUMMARY

The `ansible_loop` special variable exposes a few things to the loop, but doesn't expose the label. It'd be helpful to support this since it's part of the loop metadata.

**Note**: This may already exist, I noticed `loop_control.py` seems to have the attribute. But it's not listed as available on the [docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#extended-loop-variables). When I attempted to use `ansible_loop.label` on Ansible 2.9.10 it was not available.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
loop_control

##### ADDITIONAL INFORMATION

This makes it easier to generate output or configuration where the loop label may be used to reduce noise. I specifically tend to use it in assertions, fails, and copy/template for generating reports.

```yaml
- name: Report activity
   assert:
      that:
          - '"label" in ansible_loop'
          - ansible_loop.label.startswith('foo-')
   loop_control:
     label: 'foo-{{item}}'
     extended: true
   loop: [a, b, c]
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/loop_control.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/loop_control.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@dekimsey you can do like 

```yaml
    - name: Report activity
      assert:
        that:
          - item.label.startswith('foo-')
      loop:
      - label: foo-a
        name: a
      - label: foo-b
        name: b
```
