### ISSUE TITLE
Support StackScripts and StackScript data in Linode Module

### ISSUE THREAD

**Issue by gsauthof** [ansible/ansible#71038]
##### SUMMARY

Linode's solution to first boot customization are [StackScripts](https://www.linode.com/docs/platform/stackscripts/). Basically, when deploying a new Linode one can specify a certain StackScript and optionally parametrize it with some key value data. The official Linode client supports this via the `--stackscript_id` and `--stackscript_data` options and the Web-GUI exposes this functionality under Linodes/Create/My Images/Account StackScripts and the StackScripts main menu item.

Thus, it would be great if one could specify a StackScript and StackScript parameters when deploying a Linode VM with the Ansible Linode module.

Currently, the Ansible Linode module doesn't expose StackScript features.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

linode

##### ADDITIONAL INFORMATION

The feature would be used to execute a custom script during the first boot of the newly deployed Linode VM. StackScripts are only executed once, at the first boot.

The usecase for StackScripts is similar to the one of cloudinit, which is used by other cloud providers - such as DigitalOcean. FWIW, the DigitalOcean droplet Ansible module even supports specifying cloud-init user data.

Some deployment configuration is only possible with StackScripts. For example, the secure deployment of a SSH host key such that the first connect from a controlling node can be established against a trusted host key.

```yaml
- name: Create a new Linode
  linode:
    name: linode-test1
    plan: 1
    datacenter: 7
    distribution: 129
    stackscript:
      id: 0815
      data:
        customvar: somevalue
    state: present
  register: linode_creation
```
