### ISSUE TITLE
package module exclude parameter

### ISSUE THREAD

**Issue by walterrowe** [ansible/ansible#71060]
##### SUMMARY

The `yum` module provides an exclude parameter to exclude specific package name patterns. Add this to the package module.

##### ISSUE TYPE

feature request - add `exclude` parameter to package module

##### COMPONENT NAME

package

##### ADDITIONAL INFORMATION

We use a common playbook to update packages on all our Linux systems - Debian, Ubuntu, CentOS, Red Hat. The playbook uses the package module rather than having separate `yum` and `apt` tasks based on `ansible_distribution` fact.

Current yum behavior:

```yaml
   - name: Perform a yum update
     yum:
       name: '*'
       state: latest
       update_cache: yes
       exclude: pkgname1 pkgname*
```

Would prefer to use package:

```yaml
  tasks:
   - name: Perform a yum update
     package:
       name: '*'
       state: latest
       update_cache: yes
       exclude: pkgname1 pkgname*
```
