### ISSUE TITLE
ec2_group does not support groups from other accounts

### ISSUE THREAD

**Issue by pgehres** [ansible/ansible#7109]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.4
##### Environment:

Unrelated but
Host: OS 10.9.1, 
Target: local_action
##### Summary:

When attempting to create a new security group I would like to allow access from the ELB that I just created.  To do this you use amazon-elb/amazon-elb-sg as the group_id.  

[1] - http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/using-elb-security-groups.html
##### Expected Results:

I would expect that the security group includes rules allowing access from the ELB.  I would also expect to be able to put just about any security group into a rule since I can do that in the AWS console.
##### Actual Results:

```
failed: [127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/peter.gehres/.ansible/tmp/ansible-tmp-1398150581.12-212807661687170/ec2_group", line 1486, in <module>
    main()
  File "/Users/peter.gehres/.ansible/tmp/ansible-tmp-1398150581.12-212807661687170/ec2_group", line 233, in main
    grantGroup = groups[group_id]
KeyError: u'amazon-elb/sg-5a9c116a'   
```

Since the group is not associated with my account information about it is not fetched with the call to:

```
# find the group if present
    group = None
    groups = {}
    for curGroup in ec2.get_all_security_groups():
        groups[curGroup.id] = curGroup
        groups[curGroup.name] = curGroup
```
##### Steps To Reproduce:

```
- name: Create security group for the cdn instances
      local_action:
        module: ec2_group
        name: cdn
        description: cdn nginx hosts
        region: us-west-2 
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: amazon-elb/amazon-elb-sg
```
