### ISSUE TITLE
Bug with win_chocolatey

### ISSUE THREAD

**Issue by DanRod1** [ansible/ansible#71108]
##### SUMMARY

When i add version to win_chocolatey with the state absent ansible concatenate several time the version to the name of the package

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/custom_modules/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600s
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/action_plugins']
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['foreman']
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/custom_modules/tests/inventory/hosts']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/custom_modules/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/custom_modules/plugins/module_utils']
DEFAULT_STRATEGY(/etc/ansible/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/mitogen-0.2.9/ansible_mitogen/plugins/strategy']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
DOC_FRAGMENT_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/custom_modules/plugins/doc_fragments']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

centos 8

##### STEPS TO REPRODUCE

Below the task used to produce the problem

```yaml
  - name: Get version Installed
    set_fact:
      installedVersion: "{{ ansible_chocolatey | json_query(query) | join(' ')  }}"
    vars:
      query: "packages[?package=='netbackup'].version"

  - block :
    - name: "uninstall version {{ installedVersion }}"
      win_chocolatey:
        name: netbackup
        version: "{{ installedVersion }}"
        state: absent

    - name: "install version {{ netbackup_version }}"
      win_chocolatey:
        name: netbackup
        version: "{{ netbackup_version }}"
        params: "/netbackup_server:{{ netbackup_server }} /netbackup_home:{{ netbackup_ms_home }}"

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
{
    "changed": true,
    "invocation": {
        "module_args": {
            "ignore_checksums": false,
            "source_username": null,
            "architecture": "default",
            "allow_prerelease": false,
            "install_args": null,
            "allow_multiple": false,
            "source_password": null,
            "source": null,
            "version": null,
            "state": "absent",
            "ignore_dependencies": false,
            "proxy_username": null,
            "pinned": null,
            "force": false,
            "skip_scripts": false,
            "allow_empty_checksums": false,
            "timeout": 2700,
            "proxy_password": null,
            "proxy_url": null,
            "package_params": null,
            "validate_certs": true,
            "name": [
                "netbackup"
            ]
        }
    },
    "rc": 0,
    "_ansible_no_log": false
}

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
As you can see on the output the version is added to th package name several times

<!--- Paste verbatim command output between quotes -->
```paste below
{
    "changed": false,
    "invocation": {
        "module_args": {
            "ignore_checksums": false,
            "source_username": null,
            "architecture": "default",
            "allow_prerelease": false,
            "install_args": null,
            "allow_multiple": false,
            "source_password": null,
            "source": null,
            "version": "8.0.0",
            "state": "absent",
            "ignore_dependencies": false,
            "proxy_username": null,
            "pinned": null,
            "force": false,
            "skip_scripts": false,
            "allow_empty_checksums": false,
            "timeout": 2700,
            "proxy_password": null,
            "proxy_url": null,
            "package_params": null,
            "validate_certs": true,
            "name": [
                "netbackup"
            ]
        }
    },
    "rc": 1,
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe uninstall netbackup --yes --no-progress --limit-output --timeout 2700 --allow-multiple --version 8.0.0",
    "stdout": "Uninstalling the following packages:\r\nnetbackup\r\n\r\nnetbackup v8.0.0\r\nDirectory 'C:\\ProgramData\\chocolatey\\lib\\netbackup.8.0.0.8.0.0' does not exist.\r\nnetbackup uninstall not successful.\r\nPackage install not found:'C:\\ProgramData\\chocolatey\\lib\\netbackup.8.0.0.8.0.0'\r\nnetbackup not uninstalled. An error occurred during uninstall:\r\n netbackup uninstall not successful.\r\n\r\nChocolatey uninstalled 0/1 packages. 1 packages failed.\r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\n\r\nFailures\r\n - netbackup (exited 1) - Package install not found:'C:\\ProgramData\\chocolatey\\lib\\netbackup.8.0.0.8.0.0'\r\n\r\nIf a package uninstall is failing and/or you've already uninstalled the\r\n software outside of Chocolatey, you can attempt to run the command \r\n with `-n` to skip running a chocolateyUninstall script, additionally\r\n adding `--skip-autouninstaller` to skip an attempt to automatically \r\n remove system-installed software. This will only remove the packaging \r\n files and not things like software installed to Programs and Features.\r\n\r\nIf a package is failing because it is a dependency of another package\r\n or packages, then you may first need to consider if it needs removed\r\n as it is typically installed as a dependency for a reason. If you \r\n decide that you still want to remove it, head into \r\n `$env:ChocolateyInstall\\lib` and find the package folder you want \r\n removed. Then delete the folder for the package. This option should\r\n only be used as a last resort.\r\n \r\n",
    "stderr": "",
    "msg": "Error uninstalling package(s) 'netbackup'",
    "stdout_lines": [
        "Uninstalling the following packages:",
        "netbackup",
        "",
        "netbackup v8.0.0",
        "Directory 'C:\\ProgramData\\chocolatey\\lib\\netbackup.8.0.0.8.0.0' does not exist.",
        "netbackup uninstall not successful.",
        "Package install not found:'C:\\ProgramData\\chocolatey\\lib\\netbackup.8.0.0.8.0.0'",
        "netbackup not uninstalled. An error occurred during uninstall:",
        " netbackup uninstall not successful.",
        "",
        "Chocolatey uninstalled 0/1 packages. 1 packages failed.",
        " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).",
        "",
        "Failures",
        " - netbackup (exited 1) - Package install not found:'C:\\ProgramData\\chocolatey\\lib\\netbackup.8.0.0.8.0.0'",
        "",
        "If a package uninstall is failing and/or you've already uninstalled the",
        " software outside of Chocolatey, you can attempt to run the command ",
        " with `-n` to skip running a chocolateyUninstall script, additionally",
        " adding `--skip-autouninstaller` to skip an attempt to automatically ",
        " remove system-installed software. This will only remove the packaging ",
        " files and not things like software installed to Programs and Features.",
        "",
        "If a package is failing because it is a dependency of another package",
        " or packages, then you may first need to consider if it needs removed",
        " as it is typically installed as a dependency for a reason. If you ",
        " decide that you still want to remove it, head into ",
        " `$env:ChocolateyInstall\\lib` and find the package folder you want ",
        " removed. Then delete the folder for the package. This option should",
        " only be used as a last resort.",
        " "
    ],
    "stderr_lines": [],
    "_ansible_no_log": false
}

```
