### ISSUE TITLE
module ios_l2_interfaces not merging vlan allowed

### ISSUE THREAD

**Issue by pierremahot** [ansible/ansible#71106]
##### SUMMARY
The new ios_l2_interfaces that replace ios_l2_interface is not merging allowed vlan when merge is selected

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_l2_interfaces

##### ANSIBLE VERSION
```
ansible 2.9.11
  config file = None
  configured module search path = ['/home/pierre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pierre/.local/lib/python3.8/site-packages/ansible
  executable location = /home/pierre/.local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
for ansible :
Ubuntu 20.04
for the switch :
cisco C2960 ios 15.02

##### STEPS TO REPRODUCE

```yaml
ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/2
        trunk:
          allowed_vlan: 10-20, 40

ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/2
        trunk:
          allowed_vlan: 11
```

##### EXPECTED RESULTS

# interface GigabitEthernet0/2
#  switchport trunk allowed vlan 10-20,40

##### ACTUAL RESULTS
The allowed vlans are just replace instead of merge

```paste below
# interface GigabitEthernet0/2
#  switchport trunk allowed vlan 11
```
