### ISSUE TITLE
win_user / modify existing user in Administrator group failed

### ISSUE THREAD

**Issue by nesies** [ansible/ansible#71117]
##### SUMMARY
win_user is not idempotent with the user is in Administrator group.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/windows/win_user.py

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cody/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

CentOS Linux release 7.8.2003 (Core)
Ansible installed from epel-7

##### STEPS TO REPRODUCE
execute the follow task two times

```yaml
  win_user:
    name: useradm
    account_disabled: no
    account_locked: no
    description: "admin account"
    groups: Administrators
    groups_action: add
    password: "{{ password }}"
    password_expired: no
    password_never_expires: yes
    update_password: always
    user_cannot_change_password: yes
    state: present
```

##### EXPECTED RESULTS
win_user is supposed to be idempotent.
The first first create the user
The second run update the user (password)

##### ACTUAL RESULTS
The second run fails with:
```
 fatal: [172.22.100.83]: FAILED! => {
   "changed": true,
   "msg": "Exception calling \"SetInfo\" with \"0\" argument(s): \"This operation is disallowed as it could result in an administration account being disabled, deleted or unable to logon.\r\n\""
}
```
