### ISSUE TITLE
add `task_action` analogue to callback that represents FQCN of executed module/task

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#71126]
##### SUMMARY
Had discussion with @nitzmahone about this.

With the advent of collections, having info in the callbacks about what collection content was executed is useful for:
- tracking what content is used
- tracking when content is used
- all sorts of other statistics

I would like to have a field alongside task_action (pick a name) that describes the fqcn that is being executed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/executor/task_executor.py

?

##### ADDITIONAL INFORMATION
In the old days, this was done by just pulling `task_action`. With the advent of collections, `task_action` is insufficient
to describe this, as in this sample playbook:

```
---
- hosts: localhost
  gather_facts: False
  collections:
    - awx.awx 

  tasks:
   - name: try it once
     awx.awx.tower_job_list:
       status: running
   - name: try it again
     tower_job_list:
        status: running
```

you will get different `task_action` results, even though it's resolving to the same module.
