### ISSUE TITLE
vmware_host_facts - "ESXi 'host' not found

### ISSUE THREAD

**Issue by automateyournetwork** [ansible/ansible#71121]
##### SUMMARY
I am trying to connect and use the vmware_host_facts module based on the documentation but get an error that the ESXi host is not found 

I can see the vCenter authenticate my user / python request in the logs but I am not able to get the host facts because it never finds the hosts. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_host_facts

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /home/capobj/Lab-Infrastructure/playbooks/ansible.cfg
  configured module search path = ['/home/capobj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```
DEFAULT_FILTER_PLUGIN_PATH(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = ['/home/capobj/Lab-Infr
DEFAULT_GATHERING(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = ['/home/capobj/Lab-Infrastructur
DEFAULT_ROLES_PATH(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = ['/home/capobj/Lab-Infrastructu
DEFAULT_TRANSPORT(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = local
HOST_KEY_CHECKING(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = 320
PERSISTENT_CONNECT_TIMEOUT(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = 380
RETRY_FILES_ENABLED(/home/capobj/Lab-Infrastructure/playbooks/ansible.cfg) = False

```

##### OS / ENVIRONMENT

CentOS

##### STEPS TO REPRODUCE

# Gather VMWare Host Facts
    - name: Gather vmware host facts
      vmware_host_facts:
        hostname: "{{ vmware_hostname }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        esxi_hostname: "{{ inventory_hostname }}"
        validate_certs: no
      register: host_facts
      delegate_to: localhost

```

# Gather VMWare Host Facts
    - name: Gather vmware host facts
      vmware_host_facts:
        hostname: "{{ vmware_hostname }}"
        username: "{{ vmware_user }}"
        password: "{{ vmware_password }}"
        esxi_hostname: "{{ inventory_hostname }}"
        validate_certs: no
      register: host_facts
      delegate_to: localhost

```

##### EXPECTED RESULTS

The facts from the esxi_hosts targeted 

##### ACTUAL RESULTS

TASK [Gather vmware host facts] ***************************************************************************
fatal: [vhost01 -> localhost]: FAILED! => {"changed": false, "msg": "ESXi 'vhost01' not found"}

```
ansible-playbook VMWareFacts.yml

```
