### ISSUE TITLE
vmware_guest module provision from template NIC start_connected reporting FALSE

### ISSUE THREAD

**Issue by jameshixon** [ansible/ansible#71149]
##### SUMMARY

Provisioning VM from Windows Server 2008r2 template in vSphere Client version 7.0.0.10400 with start_connected set as TRUE in vmware_guest module actually provisions server with start_connected set as FALSE.
Cloning from same template manually in vSphere, the network adapter starts in connected state.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest 
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg
  configured module search path = [u'/home/jameshixonsa@oscn.net/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg) = [u'timer', u'profile_tasks']
DEFAULT_HOST_LIST(/home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg) = [u'/home/jameshixonsa@oscn.net/ansible_devops_james/environments/dev2223/hosts']
DEFAULT_ROLES_PATH(/home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg) = [u'/home/jameshixonsa@oscn.net/ansible_devops_james/roles']
DEFAULT_STDOUT_CALLBACK(/home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg) = debug
DEFAULT_VAULT_IDENTITY_LIST(/home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg) = [u'devqa@/ansvaulted/.vault-pass.devqa', u'prod@/ansvaulted/.vault-pass.prod']

```

##### OS / ENVIRONMENT

VMware vSphere Client version 7.0.0.10400
Hypervisor VMMware ESXi, 6.5.0, 15256549
Network Adapter vmxnet3
Guest OS: Microsoft Windows Server 2008 R2 (64-bit)
Compatibility:	ESXi 6.5 and later (VM version 13)
VMware Tools:	Running, version:11265 (Current)
PowerShell 5.1

##### STEPS TO REPRODUCE

Create Windows 2008r2 VMWare template in vSphere, run vmware_guest playbook from Ansible controller.

```yaml
- name: Create VM from template
  vmware_guest:
    validate_certs: False
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vault_vmware_password }}"
    annotation: "{{ guest_notes }}"
    datacenter: OSCN
    datastore: "{{ guest_datastore }}"
    cluster: "{{ guest_custom_cluster }}"
    folder: "{{ custom_vm_folder }}"
    state: present
    force: yes
    name: "{{ inventory_hostname }}"
    template: "{{ custom_template }}"
    networks:
    - name: "{{ custom_VLAN }}"
      state: present
      type: static
      ip: "{{ guest_custom_ip }}"
      netmask: 255.255.255.0
      gateway: "{{ guest_custom_gateway }}"
      domain: "{{ guest_custom_domain }}"
      dns_servers:
      - "{{ guest_custom_dns }}"
      start_connected: true
      allow_guest_control: true
    wait_for_ip_address: True
    customization:
      autologon: yes
      domain: "{{ guest_custom_domain }}"
      joindomain: "{{ guest_custom_domain }}"
      domainadmin: oscn\svcautomation
      domainadminpassword: "{{ vault_domainadminpassword }}"
      fullname: svc_automation_local
      password: "{{ local_password }}"
      productid: "{{ guest_productid }}"
      timezone: '020'
    wait_for_customization: True
  delegate_to: localhost
  register: provision_vm

```

##### EXPECTED RESULTS

Expected result would be provisioned VM from template with network adapter in connected stated based upon vmware_guest module with start_connected as TRUE allowing further config and playbook to finish run.

##### ACTUAL RESULTS

After verifying that the Windows 2008r2 SP1 template's vmx file contains no reference to ethernet0.startConnected = "FALSE", after the server is provisioned with vmware_guest module with start_connected as true, the new server's vmx file contains a line with ethernet0.startConnected = "FALSE". This prevents further configuration of new server with vmware_guest module and Ansible Controller due to ethernet adapter in disconnected state and playbook run hangs.

Line 674 2020-08-07T13:16:19.625Z| vmx| I125: DICT  ethernet0.startConnected = "FALSE" in attached vmware logs
[vmware.log](https://github.com/ansible/ansible/files/5041593/vmware.log)

```paste below
jameshixonsa@oscn.net@l1e5dvopf1501:~/ansible_devops_james$ ansible-playbook -i environments/systest192 -l OCISL1WEB19201 win_iis_server_ocisprovision.yml -vvvv
ansible-playbook 2.9.9
  config file = /home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg
  configured module search path = [u'/home/jameshixonsa@oscn.net/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
Using /home/jameshixonsa@oscn.net/ansible_devops_james/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/jameshixonsa@oscn.net/ansible_devops_james/environments/systest192/hosts as it did not pass its verify_file() method
script declined parsing /home/jameshixonsa@oscn.net/ansible_devops_james/environments/systest192/hosts as it did not pass its verify_file() method
auto declined parsing /home/jameshixonsa@oscn.net/ansible_devops_james/environments/systest192/hosts as it did not pass its verify_file() method
Parsed /home/jameshixonsa@oscn.net/ansible_devops_james/environments/systest192/hosts inventory source with ini plugin
Loading callback plugin debug of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/debug.pyc
Loading callback plugin profile_tasks of type aggregate, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/profile_tasks.pyc
Loading callback plugin timer of type aggregate, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/timer.pyc

PLAYBOOK: win_iis_server_ocisprovision.yml *************************************************************************************************************************************
Positional arguments: win_iis_server_ocisprovision.yml
subset: OCISL1WEB19201
become_method: sudo
inventory: (u'/home/jameshixonsa@oscn.net/ansible_devops_james/environments/systest192',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in win_iis_server_ocisprovision.yml

PLAY [all] *********************************************************************************************************************************************************************
META: ran handlers
Trying secret FileVaultSecret(filename='/ansvaulted/.vault-pass.devqa') for vault_id=devqa

TASK [Provision Server in VMWare] **********************************************************************************************************************************************
task path: /home/jameshixonsa@oscn.net/ansible_devops_james/win_iis_server_ocisprovision.yml:5
Friday 07 August 2020  08:07:58 -0500 (0:00:00.164)       0:00:00.164 ********* 

TASK [vmware : Create VM from template] ****************************************************************************************************************************************
task path: /home/jameshixonsa@oscn.net/ansible_devops_james/roles/vmware/tasks/2008r2provision.yml:1
Friday 07 August 2020  08:07:58 -0500 (0:00:00.358)       0:00:00.523 ********* 
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jameshixonsa@oscn.net
<localhost> EXEC /bin/sh -c 'echo '"'"'~jameshixonsa@oscn.net'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp `"&& mkdir /var/tmp/ansible-tmp-1596805678.71-65763-70078216645104 && echo ansible-tmp-1596805678.71-65763-70078216645104="` echo /var/tmp/ansible-tmp-1596805678.71-65763-70078216645104 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /home/jameshixonsa@oscn.net/.ansible/tmp/ansible-local-65755t8g1bq/tmpxWug_D TO /var/tmp/ansible-tmp-1596805678.71-65763-70078216645104/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'setfacl -m '"'"'u:OSCN\SVCAutomation:r-x'"'"' /var/tmp/ansible-tmp-1596805678.71-65763-70078216645104/ /var/tmp/ansible-tmp-1596805678.71-65763-70078216645104/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /var/tmp/ansible-tmp-1596805678.71-65763-70078216645104/AnsiballZ_vmware_guest.py && sleep 0'

```
