### ISSUE TITLE
failed to find folder issue for vmware_content_deploy_template ansible module

### ISSUE THREAD

**Issue by Shweta217** [ansible/ansible#71143]
##### SUMMARY

Failed to find folder for vmware_content_deploy_template module when trying to provision new server from template using content library.
I am using correct folder path which I have double checked using vmware_guest_find module as well to get the folder path for other existing vm's.

Note:
I have installed vsphere-automation-sdk-python.git, using pip install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git .
Also, provisioning with vmware_guest at the same folder path was not giving issue.

##### ISSUE TYPE
- Bug Report
folder parameter is constantly giving failed to find folder despite of giving root("/") as value to it as well.
VCenter creds used is having admin privilege.

##### COMPONENT NAME

vmware_content_deploy_template module

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

vsphere client version: Version 6.7.0

##### STEPS TO REPRODUCE

```yaml
- name: Deploy Virtual Machine from template in content library
  vmware_content_deploy_template:
    hostname: 'xxx.xxx.xxx.xxx'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    template: "test_template"
    datastore: "xxxx"
    #folder: "{{ folder_name['folders'] }}"
    folder: "/DC91/vm/ATMOS/Windows"
    datacenter: "DC91"
    name: "vmProvWintTest18"
    #resource_pool: ""
    cluster: "Cluster-01"
    host: "xxxx.xxx.xxx"
    validate_certs: False
    state: present
  delegate_to: localhost  
  tags: VMClone
```

##### EXPECTED RESULTS

Provision new vm using template from the content library

##### ACTUAL RESULTS

TASK [vmProvisionTasks : Deploy Virtual Machine from template in content library] ***
 task path: /home/gitlab-runner/builds/pbYfs3456/0/devops-automation-team/ansible/windows_vm_provision/playbooks/roles/vmProvisionTasks/tasks/vmProvision.yml:224
 <localhost> ESTABLISH LOCAL CONNECTION FOR USER: gitlab-runner
 <localhost> EXEC /bin/sh -c 'echo ~gitlab-runner && sleep 0'
 <localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422 `" && echo ansible-tmp-1596793546.56-105211564441422="` echo /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422 `" ) && sleep 0'
 Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_content_deploy_template.py
 <localhost> PUT /home/gitlab-runner/.ansible/tmp/ansible-local-80410lXr9r/tmpxZ00Sn TO /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422/AnsiballZ_vmware_content_deploy_template.py
 <localhost> EXEC /bin/sh -c 'chmod u+x /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422/ /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422/AnsiballZ_vmware_content_deploy_template.py && sleep 0'
 <localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422/AnsiballZ_vmware_content_deploy_template.py && sleep 0'
 <localhost> EXEC /bin/sh -c 'rm -f -r /home/gitlab-runner/.ansible/tmp/ansible-tmp-1596793546.56-105211564441422/ > /dev/null 2>&1 && sleep 0'
 fatal: [localhost -> localhost]: FAILED! => {
     "changed": false, 
     "invocation": {
         "module_args": {
             "cluster": "Cluster-01", 
             "datacenter": "DC91", 
             "datastore": "xxxx", 
             "folder": "/DC91/vm/ATMOS/Windows", 
             "host": "xxxx.xxx.xxx" 
             "hostname": "xxx.xxx.xxx.xxx", 
             "name": "vmProvWinTest18", 
             "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",  
             "resource_pool": null, 
             "state": "present", 
             "template": "test_template", 
             "username": "xxxx", 
             "validate_certs": false
         }
     }, 
     "msg": "Failed to find the folder /DC91/vm/ATMOS/Windows"
 }

```paste below

```
