### ISSUE TITLE
Add arg for env var in shell task

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#71171]
##### SUMMARY

I would like a field to add to the `args` of the `shell` command to specify environment variables.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
shell

##### ADDITIONAL INFORMATION

Currently you can do this:

```
- name: shell command
  shell: SOME_VAR=SOME_VALUE my-command myarg
  args:
    stdin: something
    chdir: /path/to/somewhere
```

I think it would be nice and neat to move out the env var, like:

```
- name: shell command
  shell: my-command myarg
  args:
    env:
      some_var: some_value
    stdin: something
    chdir: /path/to/somewhere
```
