### ISSUE TITLE
cli_config rollback doesn't work for rollback_id 0

### ISSUE THREAD

**Issue by pszulczewski** [ansible/ansible#71185]
##### SUMMARY
cli_config module doesn't work when rollback_id 0 is given.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
network module cli_config

##### ANSIBLE VERSION
2.9.11

```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Rollback to default
      cli_config:
        rollback: 0
```

##### EXPECTED RESULTS
```R1            : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0```

##### ACTUAL RESULTS
```R1            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0```

There is no change on target host as rollback is not executed due to a bug in the following module/line:
modules/network/cli/cli_config.py line: 390
`    if candidate or rollback_id or module.params['replace']:
`
If rollback_id is set to 0 then `if rollback_id` evaluates to False.
Change the line to:
`    if candidate or rollback_id is not None or module.params['replace']:
`
