### ISSUE TITLE
uri headers are missing after first loop iteration

### ISSUE THREAD

**Issue by ccecile9** [ansible/ansible#71208]
##### SUMMARY

uri module with loop does not send the headers after first occurrence return 201 html code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

uri
##### ANSIBLE VERSION

```
ansible 2.9.11
python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```
##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent

```
##### OS / ENVIRONMENT

ubuntu 19.1

##### STEPS TO REPRODUCE

users.yml:
```
one:
  email: "one.one@users.eu"
  first_name: "one"
  last_name: "one"
  password: "onepassword"
two:
  email: "two.two@users.eu"
  first_name: "two"
  last_name: "two"
  password: "twopassword"
```
playbook:
```
tasks:
    - name: get cookie
      uri: 
        url: http://127.0.0.1:81/api/
        method: GET
      register: site

    - name: get session id
      uri:
        url: http://127.0.0.1:81/api/login/
        method: POST
        body_format: form-urlencoded
        return_content: yes
        body:
          username: admin
          password: password
          next: /api/
        headers:
          X-CSRFToken: "{{ site.set_cookie | regex_replace('^.*csrftoken=([a-zA-Z0-9]*);.*$', '\\1') }}"
          Cookie: "{{ site.set_cookie }}"
        status_code: 302
      register: session

    - name:  include dict
      include_vars:
        dir: files/
        extensions:
        - yml
        name: users
        ignore_unknown_extensions: yes
    - name: create users
      uri:
        url: http://127.0.0.1/api/v2/users/
        method: POST
        body_format: json
        body: "{{ item.value | combine({'username':  item.key }) }}"
        headers:
          Content-Type: "application/json"
          X-CSRFToken: "{{ site.set_cookie | regex_replace('^.*csrftoken=([a-zA-Z0-9]*);.*$', '\\1') }}"
          Cookie: 
            "{{ session.set_cookie }};{{ site.set_cookie }}"
        status_code:
        - 201
        - 400
      loop: "{{ q('dict', users) }}"
```

##### EXPECTED RESULTS

it should post the dict with cookie for user one, and the same for user two

##### ACTUAL RESULTS

user two is not created because headers are empty,  website send a 401 response code for user not authenticated.
If you run the playbook a second time, it will work for user two as user one has already been created => response code is different tho.

```paste below
```
