### ISSUE TITLE
Breaking change in the "stable" releases

### ISSUE THREAD

**Issue by yoctozepto** [ansible/ansible#71200]
##### SUMMARY
https://github.com/ansible/ansible/pull/70221, having been backported to stable branches (2.9: https://github.com/ansible/ansible/pull/70825, 2.8: https://github.com/ansible/ansible/pull/70827), killed my beloved kitties.

##### ISSUE TYPE
- Bug Report
- General rant about stability of "stable"

##### ANSIBLE VERSION
```paste below
ansible 2.9.12
```

```paste below
ansible 2.8.14
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
POSIX platforms

##### STEPS TO REPRODUCE
```yaml
- name: Template out my beloved kitty
  template:
    src: "kitty.j2"
    dest: "/my_kitty"
```

##### EXPECTED RESULTS

I expected my kitty to be readable by all users as it was before (before 2.9.12, 2.8.14; mode=0644).

##### ACTUAL RESULTS

Other users cannot read my kitty (mode=0600).
