### ISSUE TITLE
Cron module in ansible 2.9.12 removes all old content (regression)

### ISSUE THREAD

**Issue by kevinvalk** [ansible/ansible#71213]
##### SUMMARY
The cron module in ansible 2.9.12 removes all previous content from the crontab (or cron file). It is highly likely that the problem was originally introduced in: https://github.com/ansible/ansible/commit/5ce47646add41077872b9cd9e0e8a24874995aae#r41381859.

Pull request https://github.com/ansible/ansible/pull/71207 fixes this issue and to adds a test case to prevent this from happening again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- cron:
    user: root
    cron_file: 'test'
    state: 'present'
    name: 'one'
    job: 'echo one'
- cron:
    user: root
    cron_file: 'test'
    state: 'present'
    name: 'two'
    job: 'echo two'

```

##### EXPECTED RESULTS

Two cronjobs

##### ACTUAL RESULTS

Only the last cronjob is added
