### ISSUE TITLE
cron module in 2.9.12 fails Idempotence.

### ISSUE THREAD

**Issue by hylaride** [ansible/ansible#71217]
##### SUMMARY

After upgrading to ansible 2.9.12, idepodence for the cron module fails.  It now returns 'changed` every time it's run, and updates the files.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

  ```YAML
cron:
    name: foo
    minute: "*/30"
    user: foo
    job: /usr/local/bin/foo
    cron_file: cron-foo
```
##### ANSIBLE VERSION

```paste below
2.9.12
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

MacOS

##### STEPS TO REPRODUCE

run Ansible-playbook twice.  2nd time any cron commands execute again, despite no changes.

```yaml
cron:
    name: foo
    minute: "*/30"
    user: foo
    job: /usr/local/bin/foo
    cron_file: cron-foo
```

##### EXPECTED RESULTS

The cron module should be Idempodent.

##### ACTUAL RESULTS

```paste below
    TASK [ansible-consul : Run foo every half-hour via cron] *************
    changed: [ubuntu-2004]
```
☝️ that happens if I run it multiple times.  all other non-cron tasks are fine.
