### ISSUE TITLE
cron module removes all jobs for each task

### ISSUE THREAD

**Issue by cwalkatron** [ansible/ansible#71216]
##### SUMMARY

Adding multiple `cron` tasks results in only the last one remaining in the `cron_file`. This problem doesn't seems to exist in 2.9.12, but not 2.9.11.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`cron`

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.12
  config file = /home/cwalker/.ansible.cfg
  configured module search path = ['/home/cwalker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/pyenv/lib64/python3.6/site-packages/ansible
  executable location = /tmp/pyenv/bin/ansible-playbook
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/cwalker/.ansible.cfg) = 60
DEFAULT_HOST_LIST(/home/cwalker/.ansible.cfg) = ['/home/cwalker/hosts']
DEFAULT_REMOTE_USER(/home/cwalker/.ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/cwalker/.ansible.cfg) = ['/home/cwalker/required-roles', '/home/cwalker/roles', '/etc/ansible/roles']
HOST_KEY_CHECKING(/home/cwalker/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL Linux 7.8

##### STEPS TO REPRODUCE

Using the below playbook.

```ansible-playbook -K -i localhost,  -c local /tmp/test.yml```

```yaml
---
- hosts: all
  become: true

  tasks:

  # Cron Change
    - cron:
        name: "First Entry"
        user: "root"
        minute: "30"
        hour: "6"
        cron_file: testing
        job: "/bin/true"

    - cron:
        name: "Second Entry"
        user: "root"
        minute: "40"
        hour: "5"
        cron_file: testing
        job: "/bin/false"
```

##### EXPECTED RESULTS

I would expect both the `First Entry` and `Second Entry` crons to be in `/etc/cron.d/testing`.

##### ACTUAL RESULTS

Only the last entry was there.

```% cat /etc/cron.d/testing
#Ansible: Second Entry
40 5 * * * root /bin/false
```

```paste below
BECOME password:

PLAY [all] ********************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [localhost]

TASK [cron] *******************************************************************************************************************
changed: [localhost]

TASK [cron] *******************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
