### ISSUE TITLE
lookup plugin ignores 'when' condition

### ISSUE THREAD

**Issue by kidmis** [ansible/ansible#71234]
##### SUMMARY

Task with any lookup plugin (query/lookup/with_dict) executes even if it must be ignored due to when condition, which cause the whole playbook failure

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lookup plugin

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /home/kidmis/Projects/PBN/git/ansible/ansible.cfg
  configured module search path = ['/home/kidmis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kidmis/Projects/PBN/git/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/kidmis/Projects/PBN/git/ansible/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_BECOME(/home/kidmis/Projects/PBN/git/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/kidmis/Projects/PBN/git/ansible/ansible.cfg) = 1
DEFAULT_PRIVATE_KEY_FILE(/home/kidmis/Projects/PBN/git/ansible/ansible.cfg) = /home/kidmis/.ssh/aws_id
HOST_KEY_CHECKING(/home/kidmis/Projects/PBN/git/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/kidmis/Projects/PBN/git/ansible/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

Linux kislitsyn-pc 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distribution: Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE

To reproduce the issue:
1) save example code into test.yml file
2) run the following command: **_ansible-playbook -i '127.0.0.1,' test.yml_**

```yaml
- name: "lookup test"
  hosts: all
  gather_facts: False
  tasks:
    - name: "define string object"
      set_fact:
        obj: '{"json": {"host": [], "status": "SUCCESS", "total_hosts": 0}}'
        # obj: '{"json": {"host": [{"1":"host1","2":"host2"}], "status": "SUCCESS", "total_hosts": 2}}'

    - name: "convert string to json"
      set_fact:
        js_obj: "{{obj|from_json}}"

    - name: "show json"
      debug:
        msg: "{{js_obj.json}}"

    - name: "print dictionary values if exist"
      block:
      - name: "check if block executes"
        debug:
          msg: "{{js_obj.json.host.0}}"

      - name: "list values"
        debug:
          msg: '{{item.value}}'
        loop: "{{ q('dict', js_obj.json.host.0)}}"
      when: js_obj.json.total_hosts > 0
      become: no
```

##### EXPECTED RESULTS

PLAY [lookup test] *************************************************************************************************************************************************

TASK [define string object] ****************************************************************************************************************************************
ok: [127.0.0.1]

TASK [convert string to json] **************************************************************************************************************************************
ok: [127.0.0.1]

TASK [show json] ***************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": {
        "host": [],
        "status": "SUCCESS",
        "total_hosts": 0
    }
}

TASK [check if block skip] *****************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [list values] *************************************************************************************************************************************************
skipping: [127.0.0.1]                                                                                                                         

PLAY RECAP *********************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0

##### ACTUAL RESULTS

ansible-playbook 2.9.12
  config file = /home/kidmis/Projects/PBN/git/ansible/ansible.cfg
  configured module search path = ['/home/kidmis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kidmis/Projects/PBN/git/ansible/lib/python3.8/site-packages/ansible
  executable location = /home/kidmis/Projects/PBN/git/ansible/bin/ansible-playbook
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
Using /home/kidmis/Projects/PBN/git/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to 127.0.0.1
Parsed 127.0.0.1, inventory source with host_list plugin
Loading callback plugin default of type stdout, v2.0 from /home/kidmis/Projects/PBN/git/ansible/lib/python3.8/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: Untitled.yml *********************************************************************************************************************************************************************************************************************
Positional arguments: /home/kidmis/Desktop/Untitled.yml
verbosity: 4
private_key_file: /home/kidmis/Dropbox/worksync/.ssh/aws_id
connection: smart
timeout: 10
become: True
become_method: sudo
tags: ('all',)
inventory: ('127.0.0.1,',)
forks: 1
1 plays in /home/kidmis/Desktop/Untitled.yml

PLAY [lookup test] *************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [define string object] ****************************************************************************************************************************************************************************************************************
task path: /home/kidmis/Desktop/Untitled.yml:6
ok: [127.0.0.1] => {
    "ansible_facts": {
        "obj": "{\"json\": {\"host\": [], \"status\": \"SUCCESS\", \"total_hosts\": 0}}"
    },
    "changed": false
}

TASK [convert string to json] **************************************************************************************************************************************
task path: /home/kidmis/Desktop/Untitled.yml:11
ok: [127.0.0.1] => {
    "ansible_facts": {
        "js_obj": {
            "json": {
                "host": [],
                "status": "SUCCESS",
                "total_hosts": 0
            }
        }
    },
    "changed": false
}

TASK [show json] ***************************************************************************************************************************************************
task path: /home/kidmis/Desktop/Untitled.yml:15
ok: [127.0.0.1] => {
    "msg": {
        "host": [],
        "status": "SUCCESS",
        "total_hosts": 0
    }
}

TASK [check if block skip] *****************************************************************************************************************************************
task path: /home/kidmis/Desktop/Untitled.yml:21
skipping: [127.0.0.1] => {}

TASK [list values] *************************************************************************************************************************************************
task path: /home/kidmis/Desktop/Untitled.yml:25
fatal: [127.0.0.1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'dict'. Error was a <class 'ansible.errors.AnsibleError'>, original message: with_dict e
}

PLAY RECAP *********************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

```paste below
ansible-playbook  -vvvv -i '127.0.0.1,' test.yml
```
