### ISSUE TITLE
Problem with virtual gorups and play_hosts

### ISSUE THREAD

**Issue by inf0rmix** [ansible/ansible#71249]
Dear ansible group,

I have a specific problem with virtual groups and I cannot find any example why this is not a bug:

assume we have a playbook which create a virtual group called Apache when a server is in a dedicated group in ansible_hosts:

##playbook yml part: ###
```
- name: "Groups: add host to Apache group, because host is in a specific group"
  add_host:
    name: "{{ item }}"
    groups: "Apache"
  when: "'webserverxy' in group_names or 'webserverzz' in group_names"
  changed_when: False
  with_items: "{{ play_hosts }}"
  tags:
    - groups
    - apache
    - always
```
###

now I have a group called webserverxy which has server1:
```
[webserverxy]
server1
```
and I run this playbook with two hosts, one of them is not in this group (server2), both hosts get added to this virtual group:
```
TASK [groups : Groups: add host to Apache group, because host is in  as specific group] *******
ok: [server1 => (item=server2)
ok: [server1 => (item=server1)
```
how to cope with this situation ?

in my current scenario, I get our haproxy server added to the apache virtual group , when I run the playbook for one webserver and the haproxy host like:
```
ansible-playbook wb_staging_all.yml --vault-password-file=/home/mfenner/vaultpw --limit metrics2.x.x,haproxy2.x.x  --tags groups,debug
```
