### ISSUE TITLE
'get_uri' lacks 'creates'

### ISSUE THREAD

**Issue by hrw** [ansible/ansible#71258]
##### SUMMARY

There is 'get_uri' module to fetch files. But it fetch file every time. 'shell' module has 'creates' option to not be run again once it does it's job.

So maybe add 'creates' to 'get_uri' so it will be run once?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_uri

##### ANSIBLE VERSION
```

```

##### CONFIGURATION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/hrw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/hrw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:42:12) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
2.9.6 on control host, 2.9.12 on target

##### OS / ENVIRONMENT

control host: Debian 10 'buster'
target host: CentOS 8

##### STEPS TO REPRODUCE
```yaml
    - name: fetch bazel 0.24.1 source
      get_url:
        url: "https://github.com/bazelbuild/bazel/releases/download/0.24.1/bazel-0.24.1-dist.zip"
        dest: "~" 
        # creates: "~/bazel-0.24.1-dist.zip"
```

##### EXPECTED RESULTS

File is fetched once and then not even tried.

##### ACTUAL RESULTS

task is run on each playbook run
