### ISSUE TITLE
cron module overwrites file

### ISSUE THREAD

**Issue by arthur-EL** [ansible/ansible#71273]
##### SUMMARY
Adding cron task with a `cron_file` specified removes other cron jobs in that file when using `2.9.12`. Version `2.9.11` works as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION

```
ansible 2.9.12
python version = 2.7.12 (default, Jul 21 2020, 15:19:50) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/arthur/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/arthur/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_ASK_VAULT_PASS(/home/arthur/ansible/ansible.cfg) = True
DEFAULT_BECOME(/home/arthur/ansible/ansible.cfg) = True
DEFAULT_MODULE_PATH(/home/arthur/ansible/ansible.cfg) = [u'/home/arthur/ansible/modules', u'/usr/share/ansible']
DEFAULT_ROLES_PATH(/home/arthur/ansible/ansible.cfg) = [u'/home/arthur/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/arthur/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON(/home/arthur/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

Local ubuntu 16.04
Target ubuntu 18.04

##### STEPS TO REPRODUCE

Creating a role that has the following cron tasks will overwrite the cron_file when adding the job

```
- name: test 1
  cron:
    name: "one"
    cron_file: /etc/crontab
    user: "test_user"
    minute: "*/2"
    job: echo "one" >> /tmp/test

- name: test 2
  cron:
    name: "two"
    cron_file: /etc/crontab
    user: "test_user"
    minute: "*/2"
    job: echo "two" >> /tmp/test
```

##### EXPECTED RESULTS
```
$cat /etc/crontab
#Old cron jobs
 
#Ansible: one
*/2 * * * * test_user /bin/echo "one" >> /tmp/test

#Ansible: two
*/2 * * * * test_user /bin/echo "two" >> /tmp/test
```

##### ACTUAL RESULTS

```
$cat /etc/crontab
#Ansible: two
*/2 * * * * echo "two" >> /tmp/test
```
