### ISSUE TITLE
Order Conditionals are Provided Results in Inconsistent Playbook Parsing Errors

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#71274]
##### SUMMARY

Using the same conditionals in different orders results in different behavior. If they're the same conditional statements, list order shouldn't matter when parsing in Ansible.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

Consider the following two tasks:
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: yes
  vars:
    reboot_hint7:
      rc: "1"
  tasks:
    - debug:
        msg: 'test 1: success'
      when: 
        - reboot_hint7.rc == "1" or "dev" in group_names
    - debug:
        msg: 'test 2: fail'
      when: 
        - "dev" in group_names or reboot_hint7.rc == "1"
```

##### EXPECTED RESULTS

Both tasks parse correctly when running the playbook.

##### ACTUAL RESULTS

```paste below
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  expected <block end>, but found '<scalar>'

The error appears to be in '/path/to/test.yml': line 17, column 17, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      when:
        - "dev" in group_names or reboot_hint7.rc == "1"
                ^ here
```
