### ISSUE TITLE
Name of task with include_tasks is not displayed

### ISSUE THREAD

**Issue by nomadcz** [ansible/ansible#71277]
##### SUMMARY

Names of tasks that contain "include_tasks" aren't displayed during playbook run
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

include_tasks

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/spider/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /srv/app/prod/ansible/core/ansible-2.9/lib64/python3.6/site-packages/ansible
  executable location = /srv/app/prod/ansible/core/ansible-2.9/bin/ansible
  python version = 3.6.3 (default, Apr 10 2019, 14:37:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```paste below
only strategy = free and jsonfile cache is used
```

##### OS / ENVIRONMENT

RedHat 7

##### STEPS TO REPRODUCE

```yaml
    - name: "Include custom_tasks_pre_install"
      include_tasks: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}/{{ item }}"
      loop: "{{ main_role_csas_sshd_custom_tasks_pre_install | default([ 'empty.yml' ]) }}"
      tags:
        - always

```

##### EXPECTED RESULTS

This should be displayed when playbook runs:
```
TASK [csas_sshd : Include custom_tasks_pre_install] **********************************
included: /srv/data/prod/ansible/core/remote/cm/csas/ansible-dev/playbooks/roles/csas_sshd/tasks/RedHat7/empty.yml for server
```
##### ACTUAL RESULTS

```
included: /srv/data/prod/ansible/core/remote/cm/csas/ansible-dev/playbooks/roles/csas_sshd/tasks/RedHat7/empty.yml for server
```

```paste below

```
As we use a lot of loops and includes it's difficult to understand the flow from output as it is incomplete. When task is skipped then it is properly displayed:

```
TASK [csas_sshd : Include custom_tasks_post_uninstall] **************************************************************************************************************************************
skipping: [server] => (item=empty.yml)  => {"ansible_loop_var": "item", "changed": false, "item": "empty.yml", "skip_reason": "Conditional result was False"}

```
