### ISSUE TITLE
maven_artifact does not check destination files

### ISSUE THREAD

**Issue by bossi86** [ansible/ansible#71281]
##### SUMMARY
When using the maven_artifact role we facing some issues. If you download a file with a retry loop and run into a "no more space left on device" error, an incomplete/currupted file will be given an OK status after the first failed attempt because a file exists without checking for file size, hash, etc.
A second thing we could watch is: If you download a file locally you need twice as much space. In one step the file is downloaded and in the second step, the file is copied to the destination.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.8.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/local_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/local_modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/local_module_utils']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Linux bsul0124 3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
Have a /tmp space of e.g. 1GB
Download e.g. a 700MB large artefact locally with a destination in /tmp

```
- name: "Download artifact: {{ plt_ad_artifact_file_name }} from repository"
  local_action: maven_artifact
  run_once: True
  args:
    repository_url: "{{ plt_ad_artifact_url }}/{{ plt_ad_artifact_repo_name }}"
    group_id: "{{ plt_ad_artifact_groupid }}"
    artifact_id: "{{ plt_ad_artifact_id }}"
    version: "{{ plt_ad_artifact_version }}"
    extension: "{{ plt_ad_artifact_extension }}"
    classifier: "{{ plt_ad_artifact_classifier| default() }}"
    dest: "{{ plt_ad_artifact_local_download_path }}/{{ plt_ad_artifact_file_name }}"
    state: present
    username: "{{ plt_ad_artifact_repo_user }}"
    password: "{{ plt_ad_artifact_repo_password }}"
    timeout: 30
  register: plt_ad_download
  until: not plt_ad_download.failed
  delay: 5
  retries: 10
  become: False
```

##### EXPECTED RESULTS
The module should check if the file which is currently present (dest) is the same file like the one from the maven repository (e.g. file size, hash value).
Additionally it would be a good idea, to just move the file and not copy it. If you have very large artifacts, the mova can cause trouble, because you will need twice as much space.

##### ACTUAL RESULTS
We used the maven_artifact role with a retry loop, because we faced some network issues in our environment sometimes.

The first run failed, due to no space left on device. And we had a corrupted copy of the artefact. Then the role started again, saw that the dest file already exists and ended up with OK state.

```
{
    "retries": 11,
    "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_maven_artifact_payload_j08fhl/__main__.py\", line 573, in <module>\n  File \"/tmp/ansible_maven_artifact_payload_j08fhl/__main__.py\", line 554, in main\n  File \"/tmp/ansible_maven_artifact_payload_j08fhl/__main__.py\", line 423, in download\n  File \"/usr/lib64/python2.7/shutil.py\", line 301, in move\n    copy2(src, real_dst)\n  File \"/usr/lib64/python2.7/shutil.py\", line 130, in copy2\n    copyfile(src, dst)\n  File \"/usr/lib64/python2.7/shutil.py\", line 84, in copyfile\n    copyfileobj(fsrc, fdst)\n  File \"/usr/lib64/python2.7/shutil.py\", line 52, in copyfileobj\n    fdst.write(buf)\nIOError: [Errno 28] No space left on device\n",
    "_ansible_no_log": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 114, in <module>\n  File \"<stdin>\", line 106, in _ansiballz_main\n  File \"<stdin>\", line 49, in invoke_module\n  File \"/tmp/ansible_maven_artifact_payload_j08fhl/__main__.py\", line 573, in <module>\n  File \"/tmp/ansible_maven_artifact_payload_j08fhl/__main__.py\", line 554, in main\n  File \"/tmp/ansible_maven_artifact_payload_j08fhl/__main__.py\", line 423, in download\n  File \"/usr/lib64/python2.7/shutil.py\", line 301, in move\n    copy2(src, real_dst)\n  File \"/usr/lib64/python2.7/shutil.py\", line 130, in copy2\n    copyfile(src, dst)\n  File \"/usr/lib64/python2.7/shutil.py\", line 84, in copyfile\n    copyfileobj(fsrc, fdst)\n  File \"/usr/lib64/python2.7/shutil.py\", line 52, in copyfileobj\n    fdst.write(buf)\nIOError: [Errno 28] No space left on device\n",
    "changed": false,
    "module_stdout": "",
    "attempts": 1,
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

{
    "group": "awx",
    "uid": 10653,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "dest": "/tmp/awx_334414_a1t40hai/project/files/sas.tgz",
    "changed": false,
    "state": "file",
    "attempts": 2,
    "gid": 10128,
    "mode": "0644",
    "invocation": {
        "module_args": {
            "directory_mode": null,
            "force": null,
            "backup": null,
            "remote_src": null,
            "repository_url": "https://artifactory.fs01.vwf.vwfs-ad/artifactory/APP_IFRS-17_DE_ICTO-12147",
            "owner": null,
            "follow": false,
            "keep_name": false,
            "group": null,
            "unsafe_writes": null,
            "serole": null,
            "content": null,
            "state": "present",
            "version": "19w40",
            "setype": null,
            "username": "tower",
            "artifact_id": "depot",
            "dest": "/tmp/awx_334414_a1t40hai/project/files/sas.tgz",
            "selevel": null,
            "regexp": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "src": null,
            "extension": "tgz",
            "verify_checksum": "download",
            "seuser": null,
            "headers": null,
            "delimiter": null,
            "mode": null,
            "timeout": 30,
            "attributes": null,
            "group_id": "com.sas",
            "validate_certs": false,
            "classifier": ""
        }
    },
    "owner": "awx",
    "size": 20863418368,
    "_ansible_no_log": false
}
```
