### ISSUE TITLE
File doesn't create sub-directories with the same permissions as the top level directory

### ISSUE THREAD

**Issue by akkie** [ansible/ansible#7130]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.5.4
##### Environment:

Ubuntu 14.04
##### Summary:

The file module doesn't create sub-directories with the same permissions as the top level directory. 
##### Steps To Reproduce:

``` yml
- name: Configure the instance
  hosts: myhosts
  user: ec2-user
  sudo: true
  gather_facts: true
  tasks:
    - name: Create project directory
      file:
        path: "/home/ec2-user/apps/myapp"
        owner: ec2-user
        group: ec2-user
        state: directory
```
##### Expected Results:

The `apps` directory should have the same owner and group as the `myapp` directory.
##### Actual Results:

The `apps` directory is owned by root.
