### ISSUE TITLE
toml inventory cannot dump unsafe values

### ISSUE THREAD

**Issue by freeseacher** [ansible/ansible#71307]
##### SUMMARY
Rendering  string 
```
config:
      service: !unsafe '{{ SYSLOG_IDENTIFIER }}'
```
with
```
- name: place config
  copy:
    content: |
      {{ config | to_toml }}
    dest: "{{ config_file }}"
```
leads to 
```
service = [ "{", "{", " ", "S", "Y", "S", "L", "O", "G", "_", "I", "D", "E", "N", "T", "I", "F", "I", "E", "R", " ", "}", "}",]
```
instead of 
```
service = "{{ SYSLOG_IDENTIFIER }}"
```
I understand that filter to_toml is not part of ansible and get from https://github.com/sivel/toiletwater but in code of it it uses ansible code in import section.
https://github.com/sivel/toiletwater/blob/master/plugins/filter/toml.py#L10

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
to_toml

##### ANSIBLE VERSION

```paste below
 % ansible --version
ansible 2.9.11
  config file = None
  configured module search path = ['/home/ashirokih/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ashirokih/python/lib/python3.8/site-packages/ansible
  executable location = /home/ashirokih/python/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
empty
```

##### OS / ENVIRONMENT
not relevant

##### STEPS TO REPRODUCE

Rendering  string 
```yaml
config:
      service: !unsafe '{{ SYSLOG_IDENTIFIER }}'
```
with
```yaml
- name: place config
  copy:
    content: |
      {{ config | to_toml }}
    dest: "{{ config_file }}"
```

##### EXPECTED RESULTS
```
service = "{{ SYSLOG_IDENTIFIER }}"
```

##### ACTUAL RESULTS

```paste below
service = [ "{", "{", " ", "S", "Y", "S", "L", "O", "G", "_", "I", "D", "E", "N", "T", "I", "F", "I", "E", "R", " ", "}", "}",]
```

Probably i should ask @sivel
