### ISSUE TITLE
Group and owner permission not change during symlink creation

### ISSUE THREAD

**Issue by pandithdurai** [ansible/ansible#71308]
Issue Type : Bug Report

ansible version :  2.9.10

component name: Ansible File module

I have recently installed the ansible 2.9.10 in new host and ansible symlink task not works as expected

```
ansible --version
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov 15 2019, 19:24:58) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

Ansible Module:
```
- name: Create Current symlink
  file:
    src: /var/www/html/dti_project/drupal_site
    dest: "{{ release_path }}"
    state: link
    owner: ci_change_master
    group: ci_change_master
```
Results:

Expected Result:
```
TASK [drupal_core : Create Current symlink] ************************************
changed: [XXXXXXXXXXXXXXXXXXXX] => {"changed": true, "dest": "/var/www/html/dti_project/current", "gid": 511, "group": "ci_change_master", "mode": "0777", "owner": "ci_change_master", "size": 37, "src": "/var/www/html/dti_project/drupal_site", "state": "link", "uid": 509}
```
ACTUAL RESULTS : 
```
TASK [drupal_core : Create Current symlink] ************************************
changed: [XXXXXXXXXXXXXXXXXXXX] => {"changed": true, "dest": "/var/www/html/dti_project/current", "gid": 0, "group": "root", "mode": "0777", "owner": "root", "size": 37, "src": "/var/www/html/dti_project/drupal_site", "state": "link", "uid": 0}
```

In the ACTUAL RESULTS ,  you could see the **owner** and **group** permission does not change to **ci_change_master** and it's work fine in another ansible instance with the version ansible 2.6.20
