### ISSUE TITLE
Roles with different parameters skipping tasks

### ISSUE THREAD

**Issue by orginux** [ansible/ansible#71312]
#### SUMMARY
Roles with different parameters in the playbook skipped when these parameters mutually exclusive as if both parameters were applied simultaneously.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

role

##### ANSIBLE VERSION

```paste below
Ansible 2.9.5
```

##### OS / ENVIRONMENT

 AWX 10.0.0 and Molecule 2.22

##### STEPS TO REPRODUCE

[minimal test-case repo](https://github.com/orginux/examle-ansible-error)

```yaml
 # playbook
---
- name: Converge
  hosts: all
  roles:
    - role: test-role
      vars:
        var1: "value 1"

    - role: test-role
      vars:
        var2: "value 2"
```

```yaml
# role
---
- name: Debug 1
  debug:
    var: var1
  when: var2 is not defined

- name: Debug 2
  debug:
    var: var2
  when: var1 is not defined
```

##### EXPECTED RESULTS

```
TASK [test-role : Debug 1] ***************************************************** 
ok: [instance] => { 
    "var1": "value 1"
}

TASK [test-role : Debug 2] *****************************************************
skipping: [instance]

TASK [test-role : Debug 1] *****************************************************
skipping: [instance]

TASK [test-role : Debug 2] *****************************************************
ok: [instance] => {
    "var2": "value 2"
}
```

##### ACTUAL RESULTS

```
    TASK [test-role : Debug 1] *****************************************************
    skipping: [instance]
    
    TASK [test-role : Debug 2] *****************************************************
    skipping: [instance]
    
    TASK [test-role : Debug 1] *****************************************************
    skipping: [instance]
    
    TASK [test-role : Debug 2] *****************************************************
    skipping: [instance]
    
    PLAY RECAP *********************************************************************
    instance    : ok=1    changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0

```

**Comment by sivel** [comment]
The problem here is related to variable scoping.  `vars` on a `role` are scoped to the play level, and not the role.  As such, defining `var1` and `var2` within `vars` on roles _**immediately**_ make them available to every task and role within the play.

You can scope them to the role by using role params instead of vars:

```
  roles:
    - role: test-role
      var1: "value 1"

    - role: test-role
      var2: "value 2"
```

See also: https://github.com/ansible/ansible/pull/69040

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
