### ISSUE TITLE
mode is incorrect

### ISSUE THREAD

**Issue by zhangguanzhang** [ansible/ansible#71328]
##### SUMMARY

mode not correct
```
[root@k8s-m1 ~]# stat /etc/kubernetes/kube-proxy.conf 
  File: ‘/etc/kubernetes/kube-proxy.conf’
  Size: 897       	Blocks: 8          IO Block: 4096   regular file
Device: fd01h/64769d	Inode: 1573562     Links: 1
Access: (1204/--w----r-T)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-08-18 10:59:41.550459805 +0800
Modify: 2020-08-18 10:59:40.171453887 +0800
Change: 2020-08-18 10:59:40.372454749 +0800
 Birth: -

```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mode
##### ANSIBLE VERSION

```paste below
# ansible --version
/usr/lib64/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
ansible 2.9.12
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: 分发kube-proxy配置文件
    - template: src={{ item.src }} dest={{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}	      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}/{{ item.src.split('.')[:-1]|join('.') }}"
        mode: 644
      with_items:	      with_items:
        - { src: 'kube-proxy.service.j2', dest: '/usr/lib/systemd/system/' }	        - { src: 'kube-proxy.service.j2', dest: '/usr/lib/systemd/system/' }
        - { src: 'kube-proxy.conf.j2', dest: '/etc/kubernetes/' }	        - { src: 'kube-proxy.conf.j2', dest: '/etc/kubernetes/' }
```
file mode is not 644
```
ls -l /etc/kubernetes/kube-proxy.conf 
--w----r-T 1 root root 897 Aug 18 10:59 /etc/kubernetes/kube-proxy.conf
```

##### ACTUAL RESULTS

```paste below

```
