### ISSUE TITLE
Parameter requires_duplicate_detection on azure_rm_servicebusqueue_module has no effect

### ISSUE THREAD

**Issue by ixevix** [ansible/ansible#71331]
##### SUMMARY

Setting the parameter to true does not affect configuration in Azure for the Service Bus queue

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_servicebusqueue

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Running from hsldevcom/azure-ansible docker image

##### STEPS TO REPRODUCE

```yaml
- name: Create service bus
  azure_rm_servicebus:
    name: "{{ az_service_bus }}"
    resource_group: "{{ az_resource_group }}"
    location: "{{ az_region }}"

- name: Create service bus queue
  azure_rm_servicebusqueue:
    name: operations
    resource_group: "{{ az_resource_group }}"
    namespace: "{{ az_service_bus }}"
    requires_duplicate_detection: true
    max_size_in_mb: 1024
    default_message_time_to_live_seconds: 1209600
    duplicate_detection_time_in_seconds: 30
    lock_duration_in_seconds: 30
```

##### EXPECTED RESULTS

The requires_duplicate_detection should enable duplicate detection in the service bus queue in Azure.

##### ACTUAL RESULTS

Does not enable duplicate detection

```paste below
TASK [operations_service : Create service bus] ***************************************************************************************************************
[WARNING]: Azure API profile latest does not define an entry for ServiceBusManagementClient
ok: [localhost] => {"changed": false, "created_at": "2020-08-18 08:18:43.063000+00:00", "id": "/subscriptions/840f91d7-f0d8-44ff-852f-6955720c6919/resourceGroups/openmaas-sandboxGroup/providers/Microsoft.ServiceBus/namespaces/openmaas-sandbox-bus", "location": "West Europe", "metric_id": "840f91d7-f0d8-44ff-852f-6955720c6919:openmaas-sandbox-bus", "name": "openmaas-sandbox-bus", "provisioning_state": "Succeeded", "service_bus_endpoint": "https://openmaas-sandbox-bus.servicebus.windows.net:443/", "sku": "standard", "type": "Microsoft.ServiceBus/Namespaces", "updated_at": "2020-08-18 08:19:28.153000+00:00"}

TASK [operations_service : Create service bus queue] *********************************************************************************************************
ok: [localhost] => {"accessed_at": "0001-01-01 00:00:00+00:00", "changed": false, "count_details": {"active_message_count": 0, "dead_letter_message_count": 0, "scheduled_message_count": 0, "transfer_dead_letter_message_count": 0, "transfer_message_count": 0}, "created_at": "2020-08-18 08:28:20.795062+00:00", "default_message_time_to_live_seconds": 1209600, "duplicate_detection_time_in_seconds": 30, "enable_batched_operations": true, "id": "/subscriptions/840f91d7-f0d8-44ff-852f-6955720c6919/resourceGroups/openmaas-sandboxGroup/providers/Microsoft.ServiceBus/namespaces/openmaas-sandbox-bus/queues/operations", "lock_duration_in_seconds": 30, "max_delivery_count": 10, "max_size_in_mb": 1024, "name": "operations", "status": "active", "type": "Microsoft.ServiceBus/Namespaces/Queues", "updated_at": "2020-08-18 08:28:20.795062+00:00"}

```
