### ISSUE TITLE
ignore_errors: yes doesn't ignore parse errors?

### ISSUE THREAD

**Issue by jwboyer** [ansible/ansible#7136]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Fedora 20
##### Summary:

If ignore_errors: yes is set for a task, and that task gets a parse error for the return code from a particular host, that host is removed from the rest of the play.
##### Steps To Reproduce:

Run a playbook that has a host which gets a parse error returned for one of the commands that has ignore_errors: yes set.
##### Expected Results:

The error is ignored, and the host is included in the rest of the plays.
##### Actual Results:

The parse error is flagged and the host is removed from the rest of the plays.

In trying to work around issue 7124, I set ignore_errors: yes on the reboot command in my playbook below:

```
- hosts: kernel-test
  gather_facts: no
  tasks:
    - include: ~/ansible/tasks/copy-kernel.yml
    - name: Reboot
      command: /sbin/reboot
      sudo: yes
      async: 1
      poll: 0
      ignore_errors: yes
    - name: Waiting for shutdown
      local_action: wait_for host={{ inventory_hostname}} port=22 state=stopped
    - name: Waiting for restart
      local_action: wait_for host={{ inventory_hostname}} port=22 state=started
                             delay=10
    - name: Dmesg
      command: dmesg
```

When I run this, I get the following output:

```
PLAY [kernel-test] ************************************************************

TASK: [Copy kernel RPM to host] ***********************************************
ok: [192.168.122.188]
ok: [sb]
ok: [obiwan]

TASK: [Reboot] ****************************************************************
failed: [192.168.122.188] => {"failed": true, "parsed": false}
invalid output was:
SUDO-SUCCESS-tocqpegdagdsarrkrohbwrslgvwecnyl

...ignoring
<job 593030187832> finished on obiwan
<job 593030187832> finished on sb
<job 593030187832> finished on 192.168.122.188

TASK: [Waiting for shutdown] **************************************************
ok: [sb]
ok: [obiwan]

TASK: [Waiting for restart] ***************************************************
ok: [obiwan]
ok: [sb]

TASK: [Dmesg] *****************************************************************
changed: [obiwan]
changed: [sb]

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/jwboyer/test-kernel.retry

192.168.122.188            : ok=2    changed=0    unreachable=0    failed=1  
obiwan                     : ok=6    changed=1    unreachable=0    failed=0  
sb                         : ok=6    changed=1    unreachable=0    failed=0  
```

As you can see, the 192.168.122.188 host got the strange SUDO-SUCCESS return that issue 7124 is open for.  It was reported as being ignored, but was then removed from the rest of the plays while the other two hosts continued on.
