### ISSUE TITLE
Variables not passed to include_role if delegate_to is not the same IP as inventory host

### ISSUE THREAD

**Issue by Rowland-Rat** [ansible/ansible#71394]
##### SUMMARY
If we are using multiple roles and importing them into a play using helpers, but need to delgate the process to a different host other than the inventory host then variables are not passed through to the role.  This worked prior to 2.9.10.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /home/IPA/username/.ansible.cfg
  configured module search path = ['/home/IPA/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/IPA/username/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/domain/username/.ansible.cfg) = True
DEFAULT_HOST_LIST(/home/domain/username/.ansible.cfg) = ['/home/domain/username/vra8/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/domain/username/.ansible.cfg) = /home/domain/username/ansible/sbe/playbooks/env_build/passwordfile
DEPRECATION_WARNINGS(/home/domain/username/.ansible.cfg) = True
HOST_KEY_CHECKING(/home/domain/username/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE
This can be reproduced by creating a dummy playbook to just display the variables.

```yaml
test.yml

- name: test connectivity
  hosts: all
  gather_facts: false

  tasks:
    - include_vars: test_dir/vars.yml

    - debug:
        msg: "{{ varlist.import_var }}"

    - include_tasks: test-helper.yml
      vars:
        standard_var: standard_var
        include_vars_var: "{{ varlist.import_var }}"
        secret_var: "{{ varlist.a_secret_var }}"
        ansible_user: "{{ varlist.a_secret_var }}"
        random_ip: "{{ varlist.random_ip }}"
        diff_ip: 192.168.0.1
        same_ip: 1.1.1.1

test-helper.yml

---
- name: Verifying input
  assert:
    that:
      - include_vars_var is defined
      - standard_var is defined
      - secret_var is defined
      - random_ip is defined

- name: Output delegate_to IP
  debug:
    msg: "Ip is {{ diff_ip }}"

- name: Pass vars to role 
  include_role:
    name: test-role
    tasks_from: not-main.yml
    apply:
      delegate_to: "{{ diff_ip }}"
  vars:
    passed_include_vars_var: "{{ include_vars_var }}"
    passed_standard_var: "{{ standard_var }}"
    passed_secret_var: "{{ secret_var }}"

test-role/tasks/main.yml

---
# tasks file for test-role
- name: Output specified var
  debug:
    msg: "normal variable is {{ passed_standard_var }}"

- name: Output include var var
  debug:
    msg: "variable is {{ passed_include_vars_var }}"

- name: Output include secret var
  debug:
    msg: "variable is {{ passed_secret_var }}"

- name: Ansible user?
  debug:
    msg: "ansible_user is {{ ansible_user }}"

vars.yml

varlist:
  import_var: imported-var
  a_secret_var: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    66313133306434363832333263323330396233303635316565636639326636393464666636326164
    3566353765633766346637326137373331343566636232380a336530383639343134656532306561
    32623163366239313235316339613064396566643132636138623536316663666336396461396230
    6239326434366466300a316162396230343736616164363732386132306630646666613461303036
    3033
  random_ip: 1.1.1.2
```

test command

ansible-playbook -i "1.1.1.1," test.yml --vault-password-file passwordfile

##### EXPECTED RESULTS

I would expect the vaiables to be displayed no matter what the delegate_to value is, as per 2.9.9 and before.

##### ACTUAL RESULTS

It fails to find the variable.

```paste below
ansible-playbook -i "1.1.1.1," test.yml --vault-password-file passwordfile

PLAY [test variables] *************************************************************************************************************************************************************************************

TASK [include_vars] ***************************************************************************************************************************************************************************************
ok: [1.1.1.1]

TASK [debug] **********************************************************************************************************************************************************************************************
ok: [1.1.1.1] => {
    "msg": "imported-var"
}

TASK [include_tasks] **************************************************************************************************************************************************************************************
included: /home/IPA/lua_w112935/ansible/testing/test-helper.yml for 1.1.1.1

TASK [Verifying input] ************************************************************************************************************************************************************************************
ok: [1.1.1.1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Output delegate_to IP] ******************************************************************************************************************************************************************************
ok: [1.1.1.1] => {
    "msg": "Ip is 192.168.0.1"
}

TASK [Pass vars to role] **********************************************************************************************************************************************************************************

TASK [test-role : Output specified var] *******************************************************************************************************************************************************************
fatal: [1.1.1.1]: FAILED! => {"msg": "'varlist' is undefined"}

PLAY RECAP ************************************************************************************************************************************************************************************************
1.1.1.1                    : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
