### ISSUE TITLE
Constructed inventory plugin not functioning as expected in Tower

### ISSUE THREAD

**Issue by brettr70** [ansible/ansible#71399]
##### SUMMARY
When running in an Ansible Tower environment, the keyed_groups functionality does not work - groups based on facts are not created. The facts are present when viewed in the inventory through Tower. The same configuration **does** work as expected in Ansible CLI but only when specifying defaults in ansible.cfg:

gathering = smart
fact_caching=jsonfile
fact_caching_connection = /tmp/factcache
fact_caching_timeout = 7200

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
constructed inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.9.2                                                                                                                                                     
  config file = /etc/ansible/ansible.cfg                                                                                                                          
  configured module search path = [u'/home/brettr.eu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']                                            
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                                                                       
  executable location = /usr/bin/ansible                                                                                                                          
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] 
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile                                                                                                                 
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /tmp/factcache                                                                                                
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 300                                                                                                              
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart  

```

##### OS / ENVIRONMENT

 Operating System: Red Hat Enterprise Linux                                                                                                                      
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.8:GA:server                                                                                                  
            Kernel: Linux 3.10.0-1127.13.1.el7.x86_64     

##### STEPS TO REPRODUCE

```yaml
plugin: constructed
strict: False

groups:
  ###########################################################################
  # ENVIRONMENT
  ###########################################################################
  env_Production: inventory_hostname.startswith('wsp')
  env_DMZ: inventory_hostname.startswith('wse')
  env_Acceptance: inventory_hostname.startswith('wsa')
  env_Test: inventory_hostname.startswith('wst')
  env_Development: inventory_hostname.startswith('wsd')
  env_Sandbox: inventory_hostname.startswith('wss')

  

keyed_groups:
  
  - prefix: distro
    key: ansible_distribution
  
  - key: ansible_os_name
    prefix: OS

  - key: ansible_os_family
    prefix: os_family

  - key: ansible_windows_domain
    prefix: Domain


```

##### EXPECTED RESULTS

Groups are created based on facts (when run in Tower)

##### ACTUAL RESULTS

No groups created for keyed_groups (when run in Tower)

```paste below

```
