### ISSUE TITLE
s3_bucket: Bucket policy failed to apply in the expected time

### ISSUE THREAD

**Issue by 4n70w4** [ansible/ansible#71396]
##### SUMMARY

I use https://min.io/ `minio/minio:RELEASE.2019-04-09T01-22-30Z`

```
TASK [Publlish policy] *********************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Bucket policy failed to apply in the expected time", "resource_actions": ["storage:GetBucketVersioning", "storage:PutBucketPolicy", "storage:GetBucketPolicy", "storage:ListBuckets", "storage:GetBucketRequestPayment"]}
```

**But bucket is created and policy applied!**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION
```
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/anton/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Publlish policy
  s3_bucket:
    name: "{{ minio_bucket }}"
    policy: "{{ lookup('template', 'policy.json.j2') }}"
    state: present
    s3_url: "{{ minio_endpoint }}"
    aws_access_key: "{{ minio_key }}"
    aws_secret_key: "{{ minio_secret }}"
    validate_certs: no
    region: us-east-1
```

But if I remove `policy: "{{ lookup('template', 'policy.json.j2') }}"` line task is ok.

##### EXPECTED RESULTS
Don't show `fatal`, show `ok`.

##### ACTUAL RESULTS
```paste below
TASK [Publlish policy] *********************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Bucket policy failed to apply in the expected time", "resource_actions": ["storage:GetBucketVersioning", "storage:PutBucketPolicy", "storage:GetBucketPolicy", "storage:ListBuckets", "storage:GetBucketRequestPayment"]}
```
