### ISSUE TITLE
nios module - cannot pass IP list to host object

### ISSUE THREAD

**Issue by razvan-ig** [ansible/ansible#71401]
##### SUMMARY
https://docs.ansible.com/ansible/latest/modules/nios_host_record_module.html hints multiple IP addresses can be allocated to a Host entry (which is a supported feature) and indeed it works with something like

```
- name: create A record(s)
  nios_host_record:
    name: "{{ record_name }}"
    comment: "created by ansible"
    ipv4:
      - address: "{{ record_target[0] }}"
      - address: "{{ record_target[1] }}"
    view: "{{ infoblox_grid_view }}"
    state: present
    provider: "{{ nios_provider }}"
  when: (record_target|length==2)
```

my problem is I don't see any way of passing a list/array/yaml to the address field instead of enumerating, any hints?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Infoblox nios module

##### ANSIBLE VERSION
2.8.5
