### ISSUE TITLE
Add ansible_local support to set_fact

### ISSUE THREAD

**Issue by JensHeinrich** [ansible/ansible#71402]
##### SUMMARY

Add a `local` keyword to the `set_fact` module to enable persistent facts 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`set_fact`

##### ADDITIONAL INFORMATION

It would enable a boolean `local` entry similar to the `cacheable` entry, convert the value of the variable to JSON and use the fact name (+.fact) to store the variable in the local fact path according to the config file using a sensible default (`/etc/ansible/facts.d`)

```yaml
- name: get latest package 
  get_url:
    url: https://some.tool/latest
    dest: /opt/tool_latest
    checksum: "{{ ansible_local['tool_checksum'] | default(omit) }}"
  register: tool

- name: safe a generated checksum for a download
  set_fact:
    local: true
    checksum: "sha1:{{ tool.checksum_src }}"
```

Or set a per device secret that is independent of the controller (this eliminates the need to store secrets on the controller that don't need to be globally defined )

```yaml
- name: generate secret
  command: openssl -hex 
  register: secret
  when: not (ansible_local['rpc_secret'] is defined)

- name: save the secret
  set_fact:
    local: true
    rpc_secret: "{{ secret.stdout }}"
```
