### ISSUE TITLE
known_hosts module documentation contains invalid example

### ISSUE THREAD

**Issue by fjoenichols** [ansible/ansible#71417]
##### SUMMARY
The documented example is for the known_hosts module is invalid. It uses a parameter that does not exist. 

```
- name: Another way to call known_hosts
  known_hosts:
    hostname: host1.example.com   # or 10.9.8.77
    key: host1.example.com,10.9.8.77 ssh-rsa ASDeararAIUHI324324  # some key gibberish
    path: /etc/ssh/ssh_known_hosts
    state: present
```

`hostname` is not a valid parameter for known_hosts, `name:` is a valid parameter. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
known_hosts module
https://docs.ansible.com/ansible/latest/modules/known_hosts_module.html

##### ANSIBLE VERSION
```
ansible 2.9.10
  config file = /home/ghostviz/ansible/ansible.cfg
  configured module search path = ['/home/ghostviz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```paste below
ACTION_WARNINGS(/home/ghostviz/ansible/ansible.cfg) = False
ANSIBLE_PIPELINING(/home/ghostviz/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ghostviz/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600s
CACHE_PLUGIN(/home/ghostviz/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ghostviz/ansible/ansible.cfg) = $HOME/.ansible/tmp/facts
CACHE_PLUGIN_TIMEOUT(/home/ghostviz/ansible/ansible.cfg) = 600
DEFAULT_FORKS(/home/ghostviz/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/home/ghostviz/ansible/ansible.cfg) = smart
DEFAULT_LOCAL_TMP(/home/ghostviz/ansible/ansible.cfg) = /home/ghostviz/.ansible/tmp/ansible-local-94408llo6xlq6
DEFAULT_TIMEOUT(/home/ghostviz/ansible/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/ghostviz/ansible/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/home/ghostviz/ansible/ansible.cfg) = ['~', '.orig', '.bak', '.ini', '.cfg', '.retry', '.pyc', '.pyo', '.py', '.crt']
INVENTORY_UNPARSED_IS_FAILED(/home/ghostviz/ansible/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/ghostviz/ansible/ansible.cfg) = False 
```

##### OS / ENVIRONMENT
All

##### ADDITIONAL INFORMATION
The documented example is for the known_hosts module is invalid. It uses a parameter that does not exist. 
```
- name: Another way to call known_hosts
  known_hosts:
    hostname: host1.example.com   # or 10.9.8.77
    key: host1.example.com,10.9.8.77 ssh-rsa ASDeararAIUHI324324  # some key gibberish
    path: /etc/ssh/ssh_known_hosts
    state: present
```
`hostname` is not a valid parameter for known_hosts, `name:` is a valid parameter.
