### ISSUE TITLE
docker_image module ignores chown command when image is built from a Dockerfile

### ISSUE THREAD

**Issue by AlexandrSokolov** [ansible/ansible#71427]
##### SUMMARY

When an image is built from a Dockerfile, that contains:
```
RUN mkdir -p {{ mysql_log_path_container }}  && \
    chown -R mysql:mysql {{ mysql_log_path_container }} && \
    mkdir -p {{ mysql_data_path_container }} && \
    chown -R mysql:mysql {{ mysql_data_path_container }}
```

Owner of mysql_log_path_container and mysql_data_path_container folders is not updated.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
!component

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.9.6
  config file = /home/alex/projects/ansible-projects/bm_app/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
$ uname -a
Linux alex-latitude-5480 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

Docker image is built via Ansible, and then a Container is created and started.

I am running Ansible task as `alex` user with `become` option enabled.

Dockerfile is handled via Ansible template, here is an adjusted `Dockerfile` file (for simplification), stored in `/home/alex/mysql ` folder:
```
ARG mysql_version

FROM mysql/mysql-server:$mysql_version

RUN mkdir -p /home/mysql/logs  && \
    chown -R mysql:mysql /home/mysql/logs && \
    mkdir -p /home/mysql/lib && \
    chown -R mysql:mysql /home/mysql/lib 
```
Ansible default variables for the mysql role:
```
---
mysql_conf_host_path: /home/{{ lookup('env', 'USER') }}/mysql
mysql_log_path_host: /var/log/mysql
mysql_log_path_container: /home/mysql/logs
mysql_data_path_host: /var/lib/mysql
mysql_data_path_container: /home/mysql/lib
mysql_version: 8.0.21
docker_mysql_image_name: bm_my_sql
docker_mysql_container_name: bm_my_sql
```
Ansible tasks (implemented as a mysql role) to build image, create container and start it:
```
- name: "Build {{ docker_mysql_image_name }}:{{ mysql_version }} Docker image"
  docker_image:
    source: build
    build:
      path: "{{ mysql_conf_host_path }}" 
      args:
        mysql_version: "{{ mysql_version }}"
    name: "{{ docker_mysql_image_name }}:{{ mysql_version }}" # contain lowercase letters, numbers or - and _.
    state: present

- name: "Create {{ docker_mysql_container_name }} container"
  docker_container:
    name: "{{ docker_mysql_container_name }}"
    image: "{{ docker_mysql_image_name }}:{{ mysql_version }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_pwd }}"
    volumes:
      - "{{ mysql_log_path_host }}:{{ mysql_log_path_container }}"
      - "{{ mysql_data_path_host }}:{{ mysql_data_path_container }}"
    state: present

- name: "Start {{ docker_mysql_container_name }} container"
  docker_container:
    name: "{{ docker_mysql_container_name }}"
    state: started
```
Then log to the container and see if chown is applied:
```
$ docker exec -it bm_my_sql bash
bash-4.2# ls -la /home/mysql/lib/
total 8
drwxr-xr-x 2 root root 4096 Aug 24 16:39 .
drwxr-xr-x 1 root root 4096 Aug 24 16:39 ..
bash-4.2# ls -la /home/mysql/logs/
total 8
drwxr-xr-x 2 root root 4096 Aug 24 16:39 .
drwxr-xr-x 1 root root 4096 Aug 24 16:39 ..
```

##### EXPECTED RESULTS
Owner of `/home/mysql/lib` and `/home/mysql/log` folders is mysql

Note: if an image is built directly with docker command, everything works fine and the owner of the folders is `mysql`

##### ACTUAL RESULTS
The owner of the folders is root, but not mysql:

```
$ docker exec -it bm_my_sql bash
bash-4.2# ls -la /home/mysql/lib/
total 8
drwxr-xr-x 2 root root 4096 Aug 24 16:39 .
drwxr-xr-x 1 root root 4096 Aug 24 16:39 ..
bash-4.2# ls -la /home/mysql/logs/
total 8
drwxr-xr-x 2 root root 4096 Aug 24 16:39 .
drwxr-xr-x 1 root root 4096 Aug 24 16:39 ..
```
