### ISSUE TITLE
terraform module should be able to create workspace

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [ansible/ansible#71437]
##### SUMMARY
Terraform module should be able to create a *terraform workspace* when requested.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
terraform

##### ANSIBLE VERSION
```paste below
ansible 2.9.12
```

##### ADDITIONAL INFORMATION
Trying to make use of this module to wrap terraform invocation from within Ansible.

I'm using [terraform workspaces](https://www.terraform.io/docs/cloud/workspaces/index.html) to manage access to different life-cycle environments on AWS (one AWS account per environment), i.e.: *workspace development*, *workspace production*... These workspaces' state is [remotely stored on S3](https://www.terraform.io/docs/backends/types/s3.html).

Then, developers are granted access to some workspaces (i.e.: non-production) but some others (i.e.: production) can only be managed by means of our pipeline tools.  Different workspaces are configured by means of different tfvars files matching the workspace's name, i.e.: development.tfvars, production.tfvars, etc.

I see there's [an option to destroy a workspace on `terraform destroy`](https://docs.ansible.com/ansible/latest/modules/terraform_module.html#parameter-purge_workspace) but there's no equivalent to create it if not present, which ends up in error first time we try to deploy to a new life-cycle stage.

Example yaml of how could this feature look like:
```yaml
- name: example terraform deployment
  hosts: localhost
  connection: local

  tasks:
  - name: Runs Terraform
    terraform:
      project_path: "{{ playbook_dir }}/../../terraform"
      variables_file: "{{ playbook_dir }}/../../terraform/environment-variables/{{ lifecycle_stage }}.tfvars"
      workspace: "{{ lifecycle_stage }}"
      force_init: true
      force_workspace: true <-- new parameter
      state: "{{ terraform_state | default('present') }}"
    register: terraform_output
```
