### ISSUE TITLE
iptables comment parameter incorrectly positioned in iptables

### ISSUE THREAD

**Issue by RRohi** [ansible/ansible#71444]
##### SUMMARY
When using **comment** parameter with iptables module, it is not positioned as the right-most object in the actual iptables table.
The outcome looks very bad at the moment.

##### ISSUE TYPE
- Cosmetic Bug Report

##### COMPONENT NAME

**iptables** module, **comment** parameter

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /home/me/project/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/me/vConstruction/lib/python3.6/site-packages/ansible
  executable location = /home/me/vConstruction/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/me/project/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/me/project/ansible.cfg) = ['/home/me/project/inventory']
DEPRECATION_WARNINGS(/home/me/project/ansible.cfg) = False
HOST_KEY_CHECKING(/home/me/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Host where I use Ansible: Ubuntu 18.04 via WSL 2.
Target VM where the iptables rules are being created: Ubuntu 18.04.

##### STEPS TO REPRODUCE

It can be reproduced by using the following task and running `iptables -L` on the target machine.
I added the DNS task as well, because this one looks correct, but I'm sure that's just because I don't have **ctstate** specified.

```yaml
- name: Create HTTPS rule
  iptables:
    chain: INPUT
    in_interface: eth0
    protocol: tcp
    destination_port: https
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new inbound HTTPS connections to eth0 interface

- name: Create DNS rule
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: domain
    jump: ACCEPT
    comment: Accept inbound DNS connections
```

##### EXPECTED RESULTS

```bash
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh  ctstate NEW /* Accept new inbound HTTPS connections to eth0 interface */
```
##### ACTUAL RESULTS

```bash
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https /* Accept new inbound HTTPS connections to eth0 interface */ ctstate NEW
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain /* Accept inbound DNS connections */
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/iptables.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/iptables.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aminvakil** [comment]
Does re-ordering comment position like in this commit fix the issue?
https://github.com/aminvakil/ansible/commit/2a816de2cced19b614d3b50704f2ad66dc6be3df
To make sure it's always at the end.
Please tell me to open a PR if that's OK.

**Comment by RRohi** [comment]
Yes, by reordering the position of those two lines, the output is now as it should be. Comment is positioned on the right now.

I don't know what's the purpose of opening a PR, but if it's necessary for the process, sure, you may open it.

**Comment by aminvakil** [comment]
@RRohi 
I'll wait for a maintainer to remove the `needs_triage` tag.

**Comment by samdoran** [comment]
@aminvakil Feel free to submit a PR with a fix as well as tests.

**Comment by RRohi** [comment]
Found out that the order is also incorrect in **nat** table.

**comment** is still last in the list where it fixed the main table comment position.

```yaml
- name: Create RDP Prerouting rule
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: '3389'
    jump: DNAT
    to_destination: '192.168.0.5:3389'
    comment: Allow RDP routing from internet to host
```

```bash
iptables -t nat -L
DNAT       tcp  --  anywhere             anywhere             tcp dpt:3389 /* Allow RDP routing from internet to host */ to:192.168.0.5:3389
```
