### ISSUE TITLE
Runas become SYSTEM - missing privileges

### ISSUE THREAD

**Issue by jborean93** [ansible/ansible#71453]
### SUMMARY
When using the `runas` become plugin to become the `SYSTEM` account there is a chance the process won't contain all the privileges assigned to that token. Becoming the `SYSTEM` account is a unique case in the `runas` code, when this is set the new process is just made from a copy of the `SYSTEM` token that we already got for impersonation https://github.com/ansible/ansible/blob/72a7cb4a2c3036da5e3abb32c50713a262d0c063/lib/ansible/module_utils/csharp/Ansible.Become.cs#L360-L361. This token only has the requirement of having the `SeTcbPrivilege` base on this check https://github.com/ansible/ansible/blob/72a7cb4a2c3036da5e3abb32c50713a262d0c063/lib/ansible/module_utils/csharp/Ansible.Become.cs#L342.

If there is an existing process on the host that has the `SeTcbPrivilege` but no other privileges, the check will still be satisfied as we only need `SeTcbPrivilege` for the elevation of the become token. What we need to change is to create a brand new logon SYSTEM token so it has the full privileges available for that account.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
runas

##### ANSIBLE VERSION
```paste below
devel
```

##### CONFIGURATION
```paste below
N/A
```

##### OS / ENVIRONMENT
Windows target

##### STEPS TO REPRODUCE
This won't happen all the time as it depends on the processes that are running on the target.

```yaml
- win_whoami:
  become: yes
  become_user: SYSTEM
  become_method: runas
```

##### EXPECTED RESULTS
The privileges of the account have all the privileges that are assigned to the SYSTEM user

##### ACTUAL RESULTS
Only a subset of privileges are assigned to the become process

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/become/runas.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/become/runas.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jklingbe** [comment]
Hi team - any ETA for a fix for this problem?

**Comment by jborean93** [comment]
@jklingbe I've just opened a PR https://github.com/ansible/ansible/pull/71570 that should fix the problem. If you are encountering this issue it would be great if you could test it out and verify that it fixes the problem. Unfortunately I cannot actually replicate the problem personally but I believe I understand the root cause and the PR should fix it.

**Comment by jklingbe** [comment]
Hi Jordan - that's great news, and yes, we would love to test it out!  How 
do I get hold of the fix and how is it applied?

Regards,
 

John Klingberg
Master Certified Solution Architect
GTS Hybrid Services Technology
IBM Services
 
 
Mobile:
+61-412-688-050
e-mail:
jklingbe@au1.ibm.com

Out of Office alert: October 5 & 6

**Comment by jborean93** [comment]
The simplest way would be to clone my repo and run Ansible from there like

```bash
git clone https://github.com/jborean93/ansible.git
cd ansible
git checkout become-system
source hacking/env-setup

# Call ansible-playbook to test
```

You probably also have to run `ansible-galaxy collection install ansible.windows` to include the Windows collection so you can still run modules like `win_ping/win_command/win_whoami`.

You could also replace `lib/ansible/module_utils/csharp/Ansible.Become.cs` in your Ansible install location with the one in that PR but that could be problematic depending on what Ansible version you are currently on. I wouldn't recommend trying that unless you are happy to reinstall Ansible in case something goes wrong.

**Comment by jklingbe** [comment]
Hi Jordan.  The first 4 steps were ok, but both ansible-playbook and ansible-galaxy are not working due to some packaging issue.
   ansible-galaxy collection install ansible.windows  [error for this command - see attached]   

What are we doing wrong?

[windows-ansible-test.docx](https://github.com/ansible/ansible/files/5171900/windows-ansible-test.docx)

**Comment by jborean93** [comment]
I don't have Word or any word compatible software installed on my dev host, can you create a text file the error or just post it in the comment.

**Comment by jklingbe** [comment]
[windows-ansible-test.txt](https://github.com/ansible/ansible/files/5172083/windows-ansible-test.txt)

text version of Word doc

**Comment by jborean93** [comment]
The error is around not having the required dependencies for Ansible. If this is a scratch host just install Ansible normally through `yum` before you clone the repo and run `source hacking/env-setup`. That should download the required dependencies that will allow you to run Ansible from the source.

**Comment by jklingbe** [comment]
Thanks Jordan.  We were able to test the fix using the latest Ansible version, but it was not successful. Same privilege issue.  Do you need to see logs or other output?

**Comment by jborean93** [comment]
Can you run the following playbook with `-vvv` and share the results (note the last task requires psexec to be on the system).

```yaml
- hosts: win_host
  gather_facts: no
  tasks:
  - name: normal user
    win_whoami:
    
  - name: become as SYSTEM
    win_whoami:
    become: yes
    become_method: runas
    become_user: SYSTEM

  - name: become as current user (password)
    win_whoami:
    become: yes
    become_method: runas
    vars:
      ansible_become_user: '{{ ansible_user }}'
      ansible_become_pass: '{{ ansible_password }}'

  - name: become as current user (S4U)
    win_whoami:
    become: yes
    become_method: runas
    vars:
      ansible_become_user: '{{ ansible_user }}'
      
  - name: psexec as SYSTEM
    win_command: psexec.exe -s -accepteula whoami.exe /all
```
