### ISSUE TITLE
No warning when collection does not exist

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible#71483]
##### SUMMARY

When running the playbook with specifying collection which does not exist works without any error.
```yaml
  collections:
    - missing.collection
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

collections
##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mnecas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### STEPS TO REPRODUCE

Run playbook with specifying collection which does not exist.

```yaml
---
- name: test
  hosts: localhost
  tasks:
    - debug:
        msg: "test"
  collections:
    - missing.collection

```

##### EXPECTED RESULTS

Show some error/fail.

##### ACTUAL RESULTS

```paste below

```
