### ISSUE TITLE
[vmware_guest] Unable to add an existing disk (.vmdk) to another existing VM (shared disks)

### ISSUE THREAD

**Issue by BryanEaay** [ansible/ansible#71507]
##### SUMMARY

Hi Community,

I'm writting down here today to explain the problem i encouter. I want to create a Playbook that creates a total of 7 disks in a first VM inside a cluster, then adding thoses 7 disks to the other VM that is inside the cluster.

I achieve the first step successfully. My problem is with the second part : "adding the existing disks to my existing VM".

I've spent the last two days reading all the vmware modules documentations, and found out that the solution should be within the vmware_guest module, with the "filename" parameter. The idea, if i'm right, is to use the full path where the .vmdk is stored to attach the disk in a existing VM.

Hoewer, i couldn't make it work, and couldn't find any example neither in documentation nor github/stackoverflow.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_guest (parameter : disk.filename)

##### ENVIRONMENT VERSIONS
- Ansible 2.9.10
- Python 2.7.5
- PyVmomi 7.0
- OS: Linux RedHat Enterprise 7

##### STEPS TO REPRODUCE

```yaml

---
- name: Create shared disks for ORACLE RAC cluster
  hosts: localhost
  connection: local
  vars_files:
    - vars/externals_vars.yml

  tasks:
  - name: "Create the disks on the first node, multi-writer ON (sharing: True)"
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
      name: "{{ vm_list.node1.name }}"
      disk:
        # 1st disk RECO - 20Go
        - size: 20Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 0
          disk_mode: 'independent_persistent'
        # 2nd disk RECO - 20Go
        - size: 20Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 1
          disk_mode: 'independent_persistent'
        # 3rd disk RECO - 20Go
        - size: 20Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 2
          disk_mode: 'independent_persistent'
        # Data disk (DG) - 100Go
        - size: 100Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 3
          disk_mode: 'independent_persistent'
        # 1st voting disk - 10Go
        - size: 10Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 4
          disk_mode: 'independent_persistent'
        # 2nd voting disk - 10Go
        - size: 10Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 5
          disk_mode: 'independent_persistent'
        # 3rd voting disk - 10Go
        - size: 10Gb
          type: eagerzeroedthick
          sharing: True
          state: present
          autoselect_datastore: True
          scsi_controller: 1
          unit_number: 6
          disk_mode: 'independent_persistent'
  
  - name: "Retrieve the paths of existing disks on the first node -> var disk_info"
    community.vmware.vmware_guest_disk_info:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
      name: "{{ vm_list.node1.name }}"
    delegate_to: localhost
    register: disk_info

  - name: "Attach the existing disk to the second node"
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      datacenter: "{{ datacenter }}"
      validate_certs: no
      name: "{{ vm_list.node2.name }}"
      disk:
        #1st disk RECO - 20Go
        - filename: "{{ disk_info.guest_disk_info['2'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 0
          disk_mode: 'independent_persistent'
        #2nd disk RECO - 20Go
        - filename: "{{ disk_info.guest_disk_info['3'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 1
          disk_mode: 'independent_persistent'
        #3rd disk RECO - 20Go
        - filename: "{{ disk_info.guest_disk_info['4'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 2
          disk_mode: 'independent_persistent'
        #Data disk (DG) - 100Go
        - filename: "{{ disk_info.guest_disk_info['5'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 3
          disk_mode: 'independent_persistent'
        #1st voting disk - 10Go
        - filename: "{{ disk_info.guest_disk_info['6'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 4
          disk_mode: 'independent_persistent'
        #2nd voting disk - 10Go
        - filename: "{{ disk_info.guest_disk_info['7'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 5
          disk_mode: 'independent_persistent'
        #3rd voting disk - 10Go
        - filename: "{{ disk_info.guest_disk_info['8'].backing_filename }}"
          type: eagerzeroedthick
          sharing: True
          scsi_controller: 1
          unit_number: 6
          disk_mode: 'independent_persistent'

```

##### ACTUAL RESULTS

```paste below

PLAY [Create shared disks for ORACLE RAC cluster] ********************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create the disks on the first node, multi-writer ON (sharing: True)] *******************************************************************************************************************************
ok: [localhost]

TASK [Retrieve the paths of existing disks on the first node -> var disk_info] ***************************************************************************************************************************
ok: [localhost]

TASK [Attach the existing disk to the second node] *******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Configuration unvalid for the device '0'.", "op": "reconfig"}

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


```
