### ISSUE TITLE
 AWS Lambda role will sometimes return erroneous ARN (continues)

### ISSUE THREAD

**Issue by georgedorn** [ansible/ansible#71502]
This issue was first reported as #47264 and it continues.  This is likely an issue with AWS, but ansible could fix it internally.

##### SUMMARY
The ARN returned by `lambda` varies, sometimes having a version number appended, sometimes having `:$LATEST` appended.  This causes a problem if it is used verbatim, e.g. to connect an S3 notification to that lambda function.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lambda and/or s3_bucket_notification

##### ANSIBLE VERSION

```
  ansible 2.9.12
  config file = /home/{me}/.ansible.cfg
  configured module search path = ['/home/{me}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/{me}/miniconda3/envs/playbooks/lib/python3.7/site-packages/ansible
  executable location = /home/{me}/miniconda3/envs/playbooks/bin/ansible
  python version = 3.7.0 (default, Oct  9 2018, 10:31:47) [GCC 7.3.0]
```

##### CONFIGURATION

```
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
DEFAULT_VAULT_PASSWORD_FILE(/home/{ME}/.ansible.cfg) = /home/{ME}/vault.password
HOST_KEY_CHECKING(/home/{ME}/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Xubuntu 20.04.

##### STEPS TO REPRODUCE

This will need extra vars for `project_stage_identifier` (I assumed it would be "example" for this), `bucket_name`, `region` (I'm using us-west-2) as well as a lambda function in a zip file (try the default 'hello world') and a `role_arn` for the lambda function to run under.

```yaml
    - name: S3UploadNotifier Lambda function
      lambda:
        name: "S3UploadNotifier-{{project_stage_identifier}}"
        state: present
        zip_file: 'files/lambda_s3_notifier.zip'
        runtime: 'python3.7'
        role: {{role_arn}}
        handler: 'lambda_function.lambda_handler'
      register: lambda_function
      retries: 3
      until: lambda_function is not failed
      delay: 10
    
    - name: Set Lambda policy for s3
      lambda_policy:
        state: "{{ state | default('present') }}"
        function_name: "S3UploadNotifier-{{project_stage_identifier}}"
        statement_id: lambda-s3-notifier
        action: lambda:InvokeFunction
        principal: s3.amazonaws.com
        region: "{{ region }}"
        source_arn: "arn:aws:s3:::{{bucket_name}}"
      register: lambda_policy_action  
      retries: 3
      until: lambda_policy_action is not failed
      delay: 10

    # If this fails because the function ARN ends with $LATEST, just re-run it. That's a bug with AWS.
    - name: Configure S3 bucket notifications
      s3_bucket_notification:
        state: present
        event_name: file upload
        bucket_name: "{{ bucket_name }}"
        lambda_function_arn: "{{ lambda_function['configuration']['function_arn'] }}"
        events: "s3:ObjectCreated:*"
        suffix: ".txt"
      register: result
      retries: 3
      until: result is not failed
      delay: 10
```

##### EXPECTED RESULTS

The last task succeeds, with output like:
```
changed: [localhost] => {
    "attempts": 1,
    "changed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "bucket_name": "{snip}",
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "event_name": "file upload",
            "events": [
                "s3:ObjectCreated:*"
            ],
            "lambda_alias": null,
            "lambda_function_arn": "arn:aws:lambda:us-west-2:{snip}:function:S3UploadNotifier-example",
            "lambda_version": 0,
            "prefix": "",
            "profile": null,
            "region": null,
            "security_token": null,
            "state": "present",
            "suffix": ".txt",
            "validate_certs": true
        }
    },
    "notification_configuration": [
        {
            "events": [
                "s3:ObjectCreated:*"
            ],
            "filter": {
                "key": {
                    "filter_rules": [
                        {
                            "name": "Prefix",
                            "value": ""
                        },
                        {
                            "name": "Suffix",
                            "value": ".txt"
                        }
                    ]
                }
            },
            "id": "file upload",
            "lambda_function_arn": "arn:aws:lambda:us-west-2:{snip}:function:S3UploadNotifier-dev"
        }
    ]
}
```

##### ACTUAL RESULTS

The last task fails, with output like this:

```paste below
The full traceback is:
  File "/tmp/ansible_s3_bucket_notification_payload_6ginmscj/ansible_s3_bucket_notification_payload.zip/ansible/modules/cloud/amazon/s3_bucket_notification.py", line 254, in main
  File "/tmp/ansible_s3_bucket_notification_payload_6ginmscj/ansible_s3_bucket_notification_payload.zip/ansible/modules/cloud/amazon/s3_bucket_notification.py", line 152, in apply_config
  File "/tmp/ansible_s3_bucket_notification_payload_6ginmscj/ansible_s3_bucket_notification_payload.zip/ansible/modules/cloud/amazon/s3_bucket_notification.py", line 164, in _upload_bucket_config
  File "/home/{me}/miniconda3/envs/playbooks/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/{me}/miniconda3/envs/playbooks/lib/python3.7/site-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
fatal: [localhost]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "bucket_name": "{snip}",
            "debug_botocore_endpoint_logs": false,
            "ec2_url": null,
            "event_name": "file upload",
            "events": [
                "s3:ObjectCreated:*"
            ],
            "lambda_alias": null,
            "lambda_function_arn": "arn:aws:lambda:us-west-2:{snip}:function:S3UploadNotifier-example:$LATEST",
            "lambda_version": 0,
            "prefix": "",
            "profile": null,
            "region": null,
            "security_token": null,
            "state": "present",
            "suffix": ".txt",
            "validate_certs": true
        }
    }
}

MSG:

An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations
```

Re-running it sometimes works, and sometimes has `lambda_function_arn` with `:1` or `:3` or some other version number.  This is likely a bug with AWS, but either `lambda` should clean it up or `s3_bucket_notification` should recognize a problem with that ARN and fix it (by snipping off the last part).
