### ISSUE TITLE
URI module requires undocumented read access to /etc/ansible when using TLS

### ISSUE THREAD

**Issue by RichWJFalconer** [ansible/ansible#71504]
##### SUMMARY

The `uri` module (via the underlying `urls` module_utils class) unexpectedly requires read access to `/etc/ansible` on the target host. This is not in the documentation of the `uri` module anywhere. The module **does** test for the existence of the directory but then blindly assumes it has read access. Global read access to this directory is normal but shouldn't be assumed, I can think of a few (admittedly unusual) scenarios in which this is the case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- uri
- urls

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.10
  config file = /tmp/ansible_richwjfalconer/ansible.cfg
  configured module search path = [u'/tmp/ansible_richwjfalconer/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/tmp/ansible_richwjfalconer/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/tmp/ansible_richwjfalconer/ansible.cfg) = %(directory)s/%%h-%%r
DEFAULT_ACTION_PLUGIN_PATH(/tmp/ansible_richwjfalconer/ansible.cfg) = [u'/tmp/ansible_richwjfalconer/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/tmp/ansible_richwjfalconer/ansible.cfg) = [u'/tmp/ansible_richwjfalconer/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(/tmp/ansible_richwjfalconer/ansible.cfg) = [u'/tmp/ansible_richwjfalconer/plugins/filter']
DEFAULT_FORCE_HANDLERS(/tmp/ansible_richwjfalconer/ansible.cfg) = True
DEFAULT_FORKS(/tmp/ansible_richwjfalconer/ansible.cfg) = 50
DEFAULT_GATHERING(/tmp/ansible_richwjfalconer/ansible.cfg) = smart
DEFAULT_LOAD_CALLBACK_PLUGINS(/tmp/ansible_richwjfalconer/ansible.cfg) = True
DEFAULT_MODULE_PATH(/tmp/ansible_richwjfalconer/ansible.cfg) = [u'/tmp/ansible_richwjfalconer/library']
DEFAULT_REMOTE_USER(/tmp/ansible_richwjfalconer/ansible.cfg) = ansible_user
DEFAULT_ROLES_PATH(/tmp/ansible_richwjfalconer/ansible.cfg) = [u'/tmp/ansible_richwjfalconer/roles']
DEFAULT_STDOUT_CALLBACK(/tmp/ansible_richwjfalconer/ansible.cfg) = log_executing_user
HOST_KEY_CHECKING(/tmp/ansible_richwjfalconer/ansible.cfg) = False
RETRY_FILES_ENABLED(/tmp/ansible_richwjfalconer/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
$ uname -a
Linux <hostname> 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
```

##### STEPS TO REPRODUCE

1. Create `/etc/ansible` on the server being configured if it doesn't exist
2. Set it to have non-read permissions for the ansible user
3. Run a `uri` task against an HTTP**S** endpoint with `validate_certs` set to true/yes

```yaml
---
# Plabook demonstrating /etc/ansible url issue

- hosts: serverUnderTest
  ignore_errors: true
  vars:
    urlToTest: https://github.com/
  tasks:
    - name: "Ensure /etc/ansible doesn't exist for the start of the test"
      become: true
      become_user: root
      file:
        path: /etc/ansible
        state: absent

    - name: "Call local HTTPS endpoint when /etc/ansible doesn't exist - should succeed"
      uri:
        url: "{{ urlToTest }}"

    - name: "Add /etc/ansible so it's only readable to another user (root example)"
      become: true
      become_user: root
      file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: "Call local HTTPS endpoint when /etc/ansible isn't readable by the calling user - should fail"
      uri:
        url: "{{ urlToTest }}"

    - name: "Call local HTTPS endpoint when /etc/ansible isn't readable by the calling user but using become - should succeed"
      become: true
      become_user: root
      uri:
        url: "{{ urlToTest }}"

    - name: "Update /etc/ansible so it's world readable"
      become: true
      become_user: root
      file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: "Call local HTTPS endpoint when /etc/ansible is world readable but empty - should succeed"
      uri:
        url: "{{ urlToTest }}"

    - name: "Ensure /etc/ansible doesn't exist for the start of the test"
      become: true
      become_user: root
      file:
        path: /etc/ansible
        state: absent
```

##### EXPECTED RESULTS

- All HTTPS calls should work regardless of the read permissions of `/etc/ansible` as it's not documented as a requirement.
- Ansible should detect that `/etc/ansible` is not readable and ignore it, like it does if `/etc/ansible` doesn't exist

##### ACTUAL RESULTS

When `/etc/ansible` exists and is not readable by the user executing the task (i.e. the `become_user`) the HTTPS call fails unless certificate validation is disabled (`validate_certs` set to `true/yes`).

```paste below
TASK [Call local HTTPS endpoint when /etc/ansible isn't readable by the calling user - should fail] ********************************************************************************
task path: /tmp/ansible_richwjfalconer/playbooks/test.yml:30
<serverUnderTest> ESTABLISH SSH CONNECTION FOR USER: ansible_user
<serverUnderTest> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible_user"' -o ConnectTimeout=10 -o ControlPath=/var/lib/ansible_user/.ansible/cp/%h-%r serverUnderTest '/bin/sh -c '"'"'echo ~ansible_user && sleep 0'"'"''
<serverUnderTest> (0, '/var/lib/ansible_user\n', '')
<serverUnderTest> ESTABLISH SSH CONNECTION FOR USER: ansible_user
<serverUnderTest> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible_user"' -o ConnectTimeout=10 -o ControlPath=/var/lib/ansible_user/.ansible/cp/%h-%r serverUnderTest '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /var/lib/ansible_user/.ansible/tmp `"&& mkdir /var/lib/ansible_user/.ansible/tmp/ansible-tmp-1598605597.23-98914-194041561433933 && echo ansible-tmp-1598605597.23-98914-194041561433933="` echo /var/lib/ansible_user/.ansible/tmp/ansible-tmp-1598605597.23-98914-194041561433933 `" ) && sleep 0'"'"''
<serverUnderTest> (0, 'ansible-tmp-1598605597.23-98914-194041561433933=/var/lib/ansible_user/.ansible/tmp/ansible-tmp-1598605597.23-98914-194041561433933\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/basics/uri.py
Pipelining is enabled.
<serverUnderTest> ESTABLISH SSH CONNECTION FOR USER: ansible_user
<serverUnderTest> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible_user"' -o ConnectTimeout=10 -o ControlPath=/var/lib/ansible_user/.ansible/cp/%h-%r serverUnderTest '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<serverUnderTest> (1, '\n{"status": -1, "exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py\\", line 1494, in fetch_url\\n    unix_socket=unix_socket, ca_path=ca_path)\\n  File \\"/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py\\", line 1390, in open_url\\n    unredirected_headers=unredirected_headers)\\n  File \\"/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py\\", line 1239, in open\\n    tmp_ca_path, cadata, paths_checked = ssl_handler.get_ca_certs()\\n  File \\"/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py\\", line 861, in get_ca_certs\\n    dir_contents = os.listdir(path)\\nOSError: [Errno 13] Permission denied: \'/etc/ansible\'\\n", "url": "https://github.com/", "changed": false, "elapsed": 0, "content": "", "failed": true, "invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "status_code": [200], "body_format": "raw", "owner": null, "follow": false, "client_key": null, "group": null, "use_proxy": true, "headers": {}, "unsafe_writes": null, "serole": null, "content": null, "setype": null, "follow_redirects": "safe", "return_content": false, "client_cert": null, "body": null, "timeout": 30, "src": null, "dest": null, "selevel": null, "force_basic_auth": false, "removes": null, "http_agent": "ansible-httpget", "regexp": null, "url_password": null, "url": "https://github.com/", "validate_certs": true, "seuser": null, "method": "GET", "creates": null, "unix_socket": null, "delimiter": null, "mode": null, "url_username": null, "attributes": null, "backup": null}}, "redirected": false, "msg": "Status code was -1 and not [200]: An unknown error occurred: [Errno 13] Permission denied: \'/etc/ansible\'"}\n', '')
<serverUnderTest> Failed to connect to the host via ssh:
<serverUnderTest> ESTABLISH SSH CONNECTION FOR USER: ansible_user
<serverUnderTest> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ansible_user"' -o ConnectTimeout=10 -o ControlPath=/var/lib/ansible_user/.ansible/cp/%h-%r serverUnderTest '/bin/sh -c '"'"'rm -f -r /var/lib/ansible_user/.ansible/tmp/ansible-tmp-1598605597.23-98914-194041561433933/ > /dev/null 2>&1 && sleep 0'"'"''
<serverUnderTest> (0, '', '')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py", line 1494, in fetch_url
    unix_socket=unix_socket, ca_path=ca_path)
  File "/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py", line 1390, in open_url
    unredirected_headers=unredirected_headers)
  File "/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py", line 1239, in open
    tmp_ca_path, cadata, paths_checked = ssl_handler.get_ca_certs()
  File "/tmp/ansible_uri_payload_MEOZ7z/ansible_uri_payload.zip/ansible/module_utils/urls.py", line 861, in get_ca_certs
    dir_contents = os.listdir(path)
OSError: [Errno 13] Permission denied: '/etc/ansible'
fatal: [serverUnderTest]: FAILED! => {
    "changed": false,
    "content": "",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                200
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": null,
            "url": "https://github.com/",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Status code was -1 and not [200]: An unknown error occurred: [Errno 13] Permission denied: '/etc/ansible'",
    "redirected": false,
    "status": -1,
    "url": "https://github.com/"
```
