### ISSUE TITLE
rabbitmq_user has a bug when use permissions arg

### ISSUE THREAD

**Issue by gitbeyond** [ansible/ansible#71505]
##### SUMMARY

I defined a var like follow:
```yaml
rabbitmq_users:
  - user: app1
    password: app1_password
    permissions:
      - vhost: /app1
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  - user: app2
    password: app2_password
    permissions:
      - vhost: /app2
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  - user: app3
    password: app3_password
    permissions:
      - vhost: /app2
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - vhost: /app1
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  - user: myadmin
    password: myadmin_pass
    tags: administrator
  - user: mymonitor
    password: mymonitor_pass
    tags: monitoring
```
tasks:
```yaml
- name: rabbitmq manage user 
  rabbitmq_user:
    user: '{{item.user}}'
    node: '{{ "rabbit@"~ansible_fqdn.split(".")[0]}}'
    tags: '{{item.tags | default(None)}}'
    password: '{{item.password}}'
    permissions: '{{item.permissions | default([], true)}}'
    state: '{{item.state | default("present", false)}}'
  loop: '{{rabbitmq_users}}'
```
the error like:
```yaml
"ansible_loop_var": "item", 
    "changed": false, 
    "cmd": "/data/apps/opt/rabbitmq/sbin/rabbitmqctl -q -n '' clear_permissions -p vhost app3", 
    "invocation": {
        "module_args": {
            "configure_priv": "^$", 
            "force": false, 
            "node": "rabbit@kvm6", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "permissions": [
                {
                    "configure_priv": ".*", 
                    "read_priv": ".*", 
                    "vhost": "/app2", 
                    "write_priv": ".*"
                }, 
                {
                    "configure_priv": ".*", 
                    "read_priv": ".*", 
                    "vhost": "/app1", 
                    "write_priv": ".*"
                }
            ], 
            "read_priv": "^$", 
            "state": "present", 
            "tags": "", 
            "update_password": "on_create", 
            "user": "app3", 
            "vhost": "/", 
            "write_priv": "^$"
        }
    }, 
    "item": {
        "password": "app3_password", 
        "permissions": [
            {
                "configure_priv": ".*", 
                "read_priv": ".*", 
                "vhost": "/app2", 
                "write_priv": ".*"
            }, 
            {
                "configure_priv": ".*", 
                "read_priv": ".*", 
                "vhost": "/app1", 
                "write_priv": ".*"
            }
        ], 
        "user": "app3"
    }, 
    "msg": "Error:\nVirtual host vhost does not exist", 
    "rc": 69, 
    "stderr": "Error:\nVirtual host vhost does not exist\n", 
    "stderr_lines": [
        "Error:", 
        "Virtual host vhost does not exist"
    ], 
    "stdout": "", 
    "stdout_lines": []
}

```
I got the permissions_to_clear  var:
```bash
'permissions_to_clear [{\'read_priv\': \'read\', \'write_priv\': \'write\', \'configure_priv\': \'configure\', \'vhost\': \'vhost\'}]'
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
[root@docker-182 rabbitmq]# ansible --version
ansible 2.9.10
  config file = /data/apps/data/wanghaifeng/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### STEPS TO REPRODUCE

```yaml

```
