### ISSUE TITLE
Only last cron task being written into target output file (introduced after 2.9.12)

### ISSUE THREAD

**Issue by guessi** [ansible/ansible#71519]
##### SUMMARY

Only last cron task being written into target output file (introduced after 2.9.12).

I've created a repo to describe how I hunt this bug,
- https://github.com/guessi/ansible-cron-bug-report

behavior comparison for ansible 2.9.11 / 2.9.12 could be found here:
- [2.9.11 output log](https://github.com/guessi/ansible-cron-bug-report/blob/master/run-with-ansible-2-9-11.log)
- [2.9.12 output log](https://github.com/guessi/ansible-cron-bug-report/blob/master/run-with-ansible-2-9-12.log)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- cron

##### ANSIBLE VERSION
```sh
% ansible --version

ansible 2.9.12
  config file = None
```

##### CONFIGURATION
```
default, clean install
```

##### OS / ENVIRONMENT
macOS 10.15.6, Python 3.8.5

##### STEPS TO REPRODUCE

```
% ansible-playbook --connection=local --inventory localhost, playbook.yml
```

```yaml
- hosts: localhost
  connection: local
  tasks:
  - name: demo task 1
    cron:
      name: "demo task 1"
      cron_file: "/tmp/demo-cronfile"
      job: "echo task 1"
      user: "root"
      state: "present"

  - name: demo task 2
    cron:
      name: "demo task 2"
      cron_file: "/tmp/demo-cronfile"
      job: "echo task 2"
      user: "root"
      state: "present"

  - name: demo task 3
    cron:
      name: "demo task 3"
      cron_file: "/tmp/demo-cronfile"
      job: "echo task 3"
      user: "root"
      state: "present"
```

##### EXPECTED RESULTS
```sh
% cat /tmp/demo-cronfile

#Ansible: demo task 3
* * * * * root echo task 3
#Ansible: demo task 1
* * * * * root echo task 1
#Ansible: demo task 2
* * * * * root echo task 2
```

##### ACTUAL RESULTS
```sh
% cat /tmp/demo-cronfile

#Ansible: demo task 3
* * * * * root echo task 3
```
