### ISSUE TITLE
ec2_instance writes tags when in check mode

### ISSUE THREAD

**Issue by sgargel** [ansible/ansible#71538]
##### SUMMARY

When using `ec2_instance` module in a playbook to configure tags those  are written even if you are in check mode.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ec2_instance

##### ANSIBLE VERSION
```paste below
ansible-playbook 2.9.12
  config file = /home/my/playbook/aws/ansible.cfg
  configured module search path = [u'/home/my/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
* `inventory/host_vars/my-aws-machine.yml`

```yaml
ec2_tags:
  Foo: bar
```
* `playbook.yml~

```yaml
- hosts: my-aws-machine
  gather_facts: false
  vars: 
    host_name: "{{ inventory_hostname }}"
    aws_region: eu-west-1
    aws_ec2_size: t3a.nano
  tasks:
  - name: "Deploy EC2"
    ec2_instance:
      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      name: "{{ host_name }}"
      key_name: "master-key"
      instance_type: "{{ aws_ec2_size }}"
      security_group: SG-my-ec2
      network:
        assign_public_ip: true
      image_id: "ami-0bfa4fefe067b7946"
      tags: "{{ ec2_tags }}"
    register: ec2_instance
    delegate_to: localhost
```

##### EXPECTED RESULTS

No changes should be written when running `ansible-playbook` with `--check` flag set 

##### ACTUAL RESULTS
Tags are written in AWS ec2.
