### ISSUE TITLE
tags don't expand variables correctly

### ISSUE THREAD

**Issue by nomadcz** [ansible/ansible#71531]
##### SUMMARY

Using variable in a "tags" section doesn't work as expected.

This maybe related https://github.com/ansible/ansible/issues/69903

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /srv/data/prod/ansible/core/remote/cm/csas/linux-cm-dev/ansible.cfg
  configured module search path = ['/home/spider/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/spider/work/michal/ansible-test/lib64/python3.6/site-packages/ansible
  executable location = /home/spider/work/michal/ansible-test/bin/ansible
  python version = 3.6.3 (default, Apr 10 2019, 14:37:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```paste below
default + cache into jsonfile
```

##### OS / ENVIRONMENT

RHEL7

##### STEPS TO REPRODUCE

This doesn't work:

```yaml
  tasks:
    - name: Include roles {{ cm_roles | map(attribute = 'role') | list }}
      vars:
        my_tags: 'tag1, tag2'
      include_role:
        name: "{{ playbook_item.role }}"
        apply:
          tags: '{{ my_tags }}'
      loop: "{{ cm_roles }}"
      loop_control:
        loop_var: playbook_item
      tags:
        - always

```
When 'cm_roles' is
```yaml
---
cm_roles:
  - { 'role': 'csas_krb5', 'tags': [ 'tag1', 'tag2' ] }
  - { 'role': 'csas_sshd', 'tags': [ 'tag3' ] }
```
Following ends up with an error:

```yaml
  tasks:
    - name: Include roles {{ cm_roles | map(attribute = 'role') | list }}
      include_role:
        name: "{{ playbook_item.role }}"
        apply:
          tags: '{{ playbook_item.tags }}'
      loop: "{{ cm_roles }}"
      loop_control:
        loop_var: playbook_item
      tags:
        - always

```

##### EXPECTED RESULTS

Tags are applied to included roles

##### ACTUAL RESULTS

Tags do not work or play fails

```paste below
TASK [csas_krb5 : Include backup] ***********************************************************************************************************************************************************
included: /srv/data/prod/ansible/core/remote/cm/csas/linux-cm-dev/playbooks/roles/csas_krb5/tasks/RedHat7/backup.yml for tpinsas03.vs.csin.cz

TASK [csas_krb5 : Placeholder] **************************************************************************************************************************************************************
fatal: [tpinsas03.vs.csin.cz]: FAILED! => {"msg": "the field 'tags' should be a list of ((<class 'str'>,), <class 'int'>), but the item '['pepa', 'karel']' is a <class 'list'>\n\nThe error appears to be in '/srv/data/prod/ansible/core/remote/cm/csas/linux-cm-dev/playbooks/roles/csas_krb5/tasks/RedHat7/backup.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Placeholder\n  ^ here\n"}
        to retry, use: --limit @/srv/data/prod/ansible/core/remote/cm/csas/linux-cm-dev/retry/csas_cm_dynamic.retry

PLAY RECAP **********************************************************************************************************************************************************************************
tpinsas03.vs.csin.cz       : ok=4    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0

```
