### ISSUE TITLE
vmware_guest_disk fails to add multiple disks on vCenter 7

### ISSUE THREAD

**Issue by jpgrall** [ansible/ansible#71544]
##### SUMMARY

vmware_guest_disk fails to add multiple disks on vCenter 7.0.  Fails with "Cannot add multiple devices using the same device key in the event" and invalidProperty = "deviceChange[1].device.key" is seen in the vpxd.log of the vCenter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest_disk

##### ANSIBLE VERSION

```paste below
2.7.5
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

vCenter 7.0
Ansible Environment Redhat 7.8

##### STEPS TO REPRODUCE

Attempt to add two or greater disks to a vm with vmware_guest_disk

```yaml
- name: Add remaining disks
  vmware_guest_disk:
    validate_certs: no
    hostname: '{{ vcenter }}'
    username: '{{ vcenter_user }}'
    password: '{{ vcenterpass }}'
    datacenter: ‘{{ datacenter }}’
    name: '{{ hostname }}'
    disk: 
       - datastore: "datastore01"
         diskmode: "persistent"
         scsi_controller: 1
         scsi_type: "paravirtual"
         size_gb: 100
         state": present
         type: thin
         unit_number: 0
       - datastore: "datastore01"
         diskmode: "persistent"
         scsi_controller: 2
         scsi_type: "paravirtual"
         size_gb: 50
         state": present
         type: thin
         unit_number: 0
```

##### EXPECTED RESULTS

Disks are added to VM

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to manage disks for virtual machine 'vmname.whereever.com' with exception : ('A specified parameter was not correct: deviceChange[1].device.key', None)"}
```
