### ISSUE TITLE
list: updates in yum module doesn't list obsolete packages

### ISSUE THREAD

**Issue by dangel101** [ansible/ansible#71558]
##### SUMMARY
when running the ansible module yum: list: updates there are no results listed, while there are obsolete packages to update

when running yum check-update from shell I get these results:
[root@localhost yum.repos.d]# yum check-update
Loaded plugins: enabled_repos_upload, imgbased-persist, package_upload, product-id, search-disabled-repos, subscription-manager,
              : vdsmupgrade, versionlock
rhvh4311-updates                                                                                                 | 3.0 kB  00:00:00     
rhvh4311-updates/primary_db                                                                                      | 2.1 kB  00:00:00     
Obsoleting Packages
redhat-virtualization-host-image-update.noarch                                 4.3.11-20200825.0.el7_9                  rhvh4311-updates
    redhat-virtualization-host-image-update-placeholder.noarch                 4.3.10-1.el7ev                           installed       

the result of yum: list: update is:
ok: [192.168.100.170] => {
    "yum_updates": {
        "changed": false,
        "failed": false,
        "results": []
    }
}

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum module

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/delfassy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

tested on RHVH4.3

##### STEPS TO REPRODUCE

```yaml
yum check-update versus the playbook below. the output is in the description

- name: get yum check updates
  yum:
    list: updates
  register: yum_updates

- name: print check updates results
  debug:
    var: yum_updates

```

##### EXPECTED RESULTS

list the obsolete packages to update 

##### ACTUAL RESULTS

obsolete packages aren't listed

```paste below

```
