### ISSUE TITLE
delegate_to doesn't work when using ansible_connection winrm

### ISSUE THREAD

**Issue by rocko-n** [ansible/ansible#71591]
##### SUMMARY
After updating from ansible 2.9.9 to ansible 2.9.10 delegate_to tasks stopped to work when using ansible_connection winrm

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
delegate_to

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = None
  configured module search path = ['/home/andrew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andrew/.local/lib/python3.6/site-packages/ansible
  executable location = /home/andrew/.local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### OS / ENVIRONMENT

Any Windows host (Windows Server 2019 for example)

##### STEPS TO REPRODUCE

Just run this playbook using ansible 2.9.10+ against any windows server (also checked the latest ansible build, the error is the same)

```yaml
- hosts: all
  vars:
    ansible_ssh_port: 5985
    ansible_connection: winrm
    ansible_ssh_user: <user>
    ansible_ssh_pass: <password>
  pre_tasks:
    - name: Setting fact
      set_fact:
        delagate_host: "{{ ansible_play_hosts_all[0] }}"

    - name: Testing delegation
      win_shell: ls
      delegate_to: "{{ delagate_host }}"
```

##### EXPECTED RESULTS

Delegation task should be successful

##### ACTUAL RESULTS

```paste below
TASK [Testing delegation] *****************************************************************************************************
fatal: [10.99.17.43]: UNREACHABLE! => {"changed": false, "msg": "ssl: auth method ssl requires a username", "unreachable": true}
fatal: [10.99.17.52]: UNREACHABLE! => {"changed": false, "msg": "ssl: auth method ssl requires a username", "unreachable": true}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/task.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Can you add a sample inventory and update the actual results to use extra verbosity to show the connection info actually used? I don't think this would be limited to winrm (there have been recent fixes to delegate_to in general), but the reproducer isn't specific enough to know what's happening.

needs_info

**Comment by dbanttari** [comment]
We have an identical issue, using win_dns_record.  Nothing seems to allow `ansible_connection` to be passed. 

When we tried setting these parameters  in `vars`, like this:
```
- name: Register DNS for host
  win_dns_record:
    name: "{{ inventory_hostname }}"
    type: A
    value: "{{ hostvars[inventory_hostname].ansible_host }}"
    zone: "{{ dns_zone }}"
  delegate_to: "{{ dns_server }}"
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_user: "{{ windows_ansible_user }}"
    ansible_password: "{{ windows_ansible_password }}"
```
...the lookup fails, claiming `windows_ansible_user` is undefined:
```
TASK [domain-member : Register DNS for host]
*************************************************
fatal: [hostname-redacted]: FAILED! => {"msg": "'windows_ansible_user' is undefined"}
```

When we tried setting `ansible_connection` _et al_ in a `set_fact` task immediately beforehand, that gets ignored:
```
TASK [domain-member : Register DNS for host]
*************************************************
failed: [hostname-redacted] => {"msg": "Failed to connect to the host via ssh: ssh: connect to host 10.xx.xx.xx port 22: Connection refused", "unreachable": true}
```

**Comment by dbanttari** [comment]
Of note: if there is a lookup for (eg) password, the lookup module fails, indicating that any variable used for the lookup (e.g. `keyvault_url`) is undefined.  So this is definitely a problem on the controller side, since we don't even get far enough to connect to the remote system before it fails.  Simplest possible testcase (windows_ansible_user and windows_ansible_password are definitely defined via lookup via the previous (`set_fact`) task):

```
- name: test ansible_connection
  win_ping: {}
  delegate_to: 10.xx.xx.xx
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_user: "{{ windows_ansible_user }}"
    ansible_password: "{{ windows_ansible_password }}"
```
fails with same message:
```
TASK [domain-member : test ansible_connection]
**************************************************
fatal: [hostname-redacted]: FAILED! => {"msg": "'windows_ansible_user' is undefined"}
```
Additional info:
```
# ansible --version
ansible 2.9.13
  config file = /app/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]

# ansible-config dump --only-changed
ANSIBLE_PIPELINING(/app/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/app/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
DEFAULT_FORKS(/app/ansible.cfg) = 50
DEFAULT_GATHER_SUBSET(/app/ansible.cfg) = ['!hardware']
DEFAULT_GATHER_TIMEOUT(/app/ansible.cfg) = 20
DEFAULT_HASH_BEHAVIOUR(/app/ansible.cfg) = merge
DEFAULT_TIMEOUT(/app/ansible.cfg) = 20
DEFAULT_TRANSPORT(/app/ansible.cfg) = smart
HOST_KEY_CHECKING(/app/ansible.cfg) = False
INVENTORY_ENABLED(/app/ansible.cfg) = ['azure_rm', 'script', 'yaml', 'host_list', 'ini']
PERSISTENT_COMMAND_TIMEOUT(/app/ansible.cfg) = 20
```
This all works fine in Ansible 2.9.4
