### ISSUE TITLE
Cloudformation how to remove all global tags

### ISSUE THREAD

**Issue by gderemetz** [ansible/ansible#71599]
Hello,
>
##### SUMMARY
How can I delete all global tags from my cloudformation stack ?
the tag MyTagName is always present on the aws console. I don't know how delete it.
Nothing is changed when I remove the tag parameter. I have to delete the stack  and replay it without the parameter
best regards

```
- name: ECS Service
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  tasks:
    - cloudformation:
        stack_name: "{{ ecs_services_stack_name }}"
        state: "{{ docker_state }}"
        region: "{{ region }}"
        role_arn: "{{ cfn_service_role }}"
        template: "{{playbook_dir}}/templates/ecs-services.yml"
        template_parameters:
          Env: "{{ env }}"
#        tags:
#          MyTagName: "{{ env }}" ######## I want delete this tag
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cloudformation

##### ANSIBLE VERSION

```ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```
