### ISSUE TITLE
[MODULE] jenkins_plugin: install uncompatible plugin with current Jenkins version

### ISSUE THREAD

**Issue by nikola197** [ansible/ansible#71593]
##### SUMMARY
When `state: latest` is set in jenkins_plugin module, it install the latest plugin version even if it is not compatible with the current Jenkins version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module: jenkins_plugin

##### ANSIBLE VERSION

```paste below
2.9.10
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Host: Ubuntu 20.04
Remote: MacOS Catalina 10.15

##### STEPS TO REPRODUCE

```yaml
- name: Install Jenkins plugins using a password.
  jenkins_plugin:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: "{{ 'present' if item.version is defined else jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    updates_url: "{{ jenkins_updates_url }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    with_dependencies: "{{ jenkins_plugins_install_dependencies }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    # use_proxy: no
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_password | default(false)
  tags: ['skip_ansible_lint']
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 2

```

##### EXPECTED RESULTS

It should install the latest compatible plugin version with the current Jenkins version.

##### ACTUAL RESULTS

It install the most latest version of plugin regardless of its compatibillity.

```paste below

```
