### ISSUE TITLE
[azure rm] Container volumes

### ISSUE THREAD

**Issue by JG127** [ansible/ansible#71595]
##### SUMMARY
Provide support for persistent volumes for Azure Container Instances 

The lack of support for persistent storage means ACI lose all file system changes as soon as they are stopped. 

The Azure portal web ui does not offer support for it either. But the command line api does.
 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
module azure_rm_containerinstance

##### ADDITIONAL INFORMATION
Ideal would be to provide volume mapping on container basis. 

A possible example:

```yaml
azure_rm_containerinstance:
  ...
  containers:
    - name: helloworld
      ...
      volumes:
        - file_account_name: foo
          file_account_key: bar
          file_share_name: share0
          mount_path: /opt
      ...
```
The first three properties are related to an Azure storage account and file share. While the last property indicates where in the container the file share must be mounted.

Currently I'm doing this with the command line like this:
```bash
az container create ...   --azure-file-volume-account-name "foo" --azure-file-volume-account-key "bar" --azure-file-volume-share-name "share0" --azure-file-volume-mount-path "/opt" ...
```
