### ISSUE TITLE
RedFish module utilities may not select the appropriate manager for some operations.

### ISSUE THREAD

**Issue by smokes2345** [ansible/ansible#71623]
##### SUMMARY
When accessing the 'Managers' members, module_utils.redfish_utils.RedfishUtils._find_managers_resource selects the *last* manager returned by the API as the manager to use for executing commands.

##### ISSUE TYPE
The last manager may not be the appropriate manager for the desired command and may not support the desired command.  This also has security ramifications as a command (ex: "GracefulRestart") may be executed on an undesired manager.  The user should be able to select the desired manager with a 'manager' parameter.  

##### COMPONENT NAME
lib/ansible/module_utils/redfish_utils.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /Users/matdavid/.ansible.cfg
  configured module search path = ['/Users/matdavid/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/matdavid/.virtualenvs/PBBoss/lib/python3.7/site-packages/ansible
  executable location = /Users/matdavid/.virtualenvs/PBBoss/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Execute the redfish_command module, using the 'Manager' category, against any host that has more than one manager returned by the API.

```yaml
    - name: Reboot CIMC
      redfish_command:
        category: Manager
        command: GracefulRestart
        baseuri: "{{ cimc }}"
        username: "{{ cimc_username }}"
        password: "{{ cimc_password }}"
      register: redfish_facts
      delegate_to: localhost
      tags:
        - cimc_reboot
```

##### EXPECTED RESULTS

The requested command is executed on an appropriate manager

##### ACTUAL RESULTS

The requested command may be run on *any* manager depending upon what order they are returned from the upstream API

```paste below

```
