### ISSUE TITLE
lxd_container parameter url with https url

### ISSUE THREAD

**Issue by sgrzer** [ansible/ansible#71630]
##### SUMMARY

lxd_container module
On snap lxd installed ansible machine. I am unable to set a LXD https server using the parameter url or snap_url.

If the parameter url is set to https://lxdserver:8443 the default value of snap_url overwite the parameter url.  The parameter snap_url is validated using os.path.exists() it work for the socket and not https URL. 

My workaround : 
```yaml
lxd_container:
  snap_url: ""
  url: "https://lxdserver:8443" 
```

https://github.com/ansible/ansible/blob/417e408f596cbf48503f2240b8e2b9a97ed05d51/lib/ansible/modules/cloud/lxd/lxd_container.py#L332

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION

```paste below
ansible 2.9.12

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04 TLS

##### STEPS TO REPRODUCE

lxd installed with snap. 

```yaml
- name: Create a started container
   lxd_container:
       name: mycontainer 
       url: "https://lxdserver:8443"
       state: started
       source:
           type: image
           mode: pull
           server: https://images.linuxcontainers.org
           protocol: lxd
           alias: ubuntu/xenial/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
```

##### EXPECTED RESULTS

Container created on the remote lxd server. 
##### ACTUAL RESULTS

Container created localy using the default snap socket instead of the remote server.

```paste below

```
