### ISSUE TITLE
openssh_keypair error if key already exists

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#71631]
##### SUMMARY

openssh_keypair throws an error if ssh key pair already exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
openssh_keypair module

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  configured module search path = ['/home/devnewton/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/devnewton/.local/lib/python3.8/site-packages/ansible
  executable location = /home/devnewton/.local/bin/ansible
  python version = 3.8.3 (default, May 23 2020, 15:50:53) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Windows 10 + cygwin

##### STEPS TO REPRODUCE
Run a playbook with openssh_keypair twice.

```yaml
- name: test ssh key gen
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create target directory
      file:
        path: "target"
        state: directory
    - name: create ssh key
      openssh_keypair:
        path: "target/ssh_key" 
```

##### EXPECTED RESULTS
No error expected.

##### ACTUAL RESULTS
Playbook fails on python exception.

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   File "/tmp/ansible_openssh_keypair_payload_rzdh605t/ansible_openssh_keypair_payload.zip/ansible/modules/crypto/openssh_keypair.py", line 292, in _pubkey_valid
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

'bool' object is not subscriptable
```
