### ISSUE TITLE
Ansible 2.9.13 yum repository install "Failed to validate GPG signature for ..."

### ISSUE THREAD

**Issue by mhitza** [ansible/ansible#71634]
##### SUMMARY
External repository installation fails via yum in Ansible 2.9.13 (example with remi repo, but same issue encountered with epel).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum module

##### ANSIBLE VERSION
```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/x/.local/lib/python3.8/site-packages/ansible
  executable location = /home/x/.local/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### OS / ENVIRONMENT
Tested on both Fedora 32/Ubuntu 20.04 as the host where Ansible is installed. 

##### STEPS TO REPRODUCE
1. `pip3 install --user ansible==2.9.13`
2. `mkdir bug-poc && cd bug-poc && molecule init scenario`
3. `mkdir tasks && vim tasks/main.yml`, with the following content
```yaml
- rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
- name: Install remi repo.
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present
```
4. `molecule converge`
```
...
    TASK [bug-poc : Install remi repo.] ********************************************
fatal: [instance]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for remi-release-8.1-2.el8.remi.noarch"}
    
    PLAY RECAP *********************************************************************
    instance                   : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
5. `pip3 install --user ansible==2.9.12`
6. `molecule converge`
```
    TASK [bug-poc : Install remi repo.] ********************************************
    changed: [instance]
    
    PLAY RECAP *********************************************************************
    instance                   : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mhitza: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/yum.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is likely the result of this change: https://github.com/ansible/ansible/pull/71537

You may either need to add `disable_gpg_check: True` to your task, or add a task to add the RPM key, prior to installing the `remi-release` package.

**Comment by mhitza** [comment]
Even if I import the key prior to the installation it fails. I've updated my reproduction steps to include the key import step with your task example.

**Comment by relrod** [comment]
@mhitza 

The remi site says `RPM-GPG-KEY-remi` is for `Fedora <= 25 and EL <= 7`

```
RPM-GPG-KEY-remi2018: the GnuPG public key of the key pair used to sign my packages (Fedora 28-29 and EL-8)
RPM-GPG-KEY-remi2017: the GnuPG public key of the key pair used to sign my packages (Fedora 26-27)
RPM-GPG-KEY-remi: the GnuPG public key of the key pair used to sign my packages (Fedora <= 25 and EL <= 7) 
```

This works for me:

```yaml
- hosts: localhost
  tasks:
  - rpm_key:
      state: present
      key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
  - rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  - name: Install epel repo.
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
      state: present
  - name: Install remi repo.
    yum:
      name: "http://rpms.remirepo.net/enterprise/remi-release-8.rpm"
      state: present
```
