### ISSUE TITLE
systemd enabled behave different from `systemctl enable`

### ISSUE THREAD

**Issue by braindevices** [ansible/ansible#71645]
##### SUMMARY

when a service foo.service is belongs to a target for example: multi-user.target. Then we change the foo.service to wanted by 2 targets: test.target and multi-user.target, without disable it first. `systemctl enable foo` create a folder `/etc/systemd/system/test.target.wants` and create symlink to `foo.service` in it. The ansible fail to do so, it think the foo is already enabled. Workaround is to disable first then enable again.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

systemd
##### ANSIBLE VERSION

```
2.9.6

```
##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora 31

##### STEPS TO REPRODUCE

run the task, then `ls /etc/systemd/system/test.target.wants` We can see there is no file in it or dir does not exist. Then try `systemctl enable foo`. We can then see the dir and symlink.

```yaml
- name: create foo.service
  copy:
  path: '/etc/systemd/system/foo.service'
  content: |
    [Unit]
    Description=foo
    PartOf=test.target

    [Service]
    Type=simple
    ExecStart=/bin/sh -c 'while true; do echo date >> /tmp/foo1.log; sleep 5; done'
    [Install]
    WantedBy=multi-user.target
- name: create test.target
  copy:
  path: '/etc/systemd/system/foo.service'
  content: |
    [Unit]
    Description=test target
- name: Activate gameon systemd configuration (general/cloud)
  systemd:
  name: foo.service
  daemon_reload: yes
  enabled: yes
- name: create foo.service
  copy:
  path: '/etc/systemd/system/foo.service'
  content: |
    [Unit]
    Description=foo
    PartOf=test.target

    [Service]
    Type=simple
    ExecStart=/bin/sh -c 'while true; do echo date >> /tmp/foo1.log; sleep 5; done'
    [Install]
    WantedBy=test.target multi-user.target
- name: Activate gameon systemd configuration (general/cloud)
  systemd:
  name: foo.service
  daemon_reload: yes
  enabled: yes
```

##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/systemd.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/systemd.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
note: state=enabled is not the same as `systemctl enable` since it only executes that command if needed, detection might be giving a false positive on enabled, why i'm keeping this ticket open.

**Comment by Baryczka** [comment]
I have similar behavior but in my case I wanted as a name put the path and enable service to create symlinks like:
```yml
  systemd:
    name: '{{ firewall }}/iptables.service'
    enabled: true
 ```
 
 Ansible is saying changed but then analyzed output and I could find:
    ` "LoadError": "org.freedesktop.systemd1.NoSuchUnit \"Unit etc-my-firewall-path-iptables.service.mount not found.\""`
    
    Looks like it is not supported
