### ISSUE TITLE
[vmware] vmware_vswitch module - Add security, teaming, traffic_shaping parameters

### ISSUE THREAD

**Issue by wells** [ansible/ansible#71646]
##### SUMMARY
I propose to add the `security`, `teaming`, and `traffic_shaping` dictionary parameters that are accessible one level below in the `vmware_portgroup` module to the `vmware_vswitch` module.

##### ISSUE TYPE
- These settings can be configured on the vSwitches from the ESXi web interface. These settings are also configurable from the vSphere Web Services API from `AddVirtualSwitch` and `UpdateVirtualSwitch` by setting up the optional policy (`HostNetworkPolicy`).

##### COMPONENT NAME
vmware_vswitch / pyVmomi

##### ANSIBLE VERSION
```
ansible 2.9.11
```

##### ADDITIONAL INFORMATION
This feature will enable a group level adjustment for every port group in a vSwitch that defaults to the vSwitch policies.

Tumble down the vSphere Web Services API rabbit hole with me:
- https://code.vmware.com/apis/704/vsphere/vim.host.NetworkSystem.html#addVirtualSwitch
- https://code.vmware.com/apis/704/vsphere/vim.host.NetworkSystem.html#updateVirtualSwitch
- https://code.vmware.com/apis/704/vsphere/vim.host.VirtualSwitch.Specification.html
- https://code.vmware.com/apis/704/vsphere/vim.host.NetworkPolicy.html
- https://code.vmware.com/apis/704/vsphere/vim.host.NetworkPolicy.SecurityPolicy.html

```yaml
- name: Add a VMware vSwitch
  vmware_vswitch:
    hostname: "{{ esxi_hostname }}"
    esxi_hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    switch: "vswitch_name"
    nics: "vmnic_name"
    mtu: 9000
    security:
        promiscuous_mode: False
        mac_changes: False
        forged_transmits: False
    traffic_shaping:
        enabled: True
        average_bandwidth: 100000
        peak_bandwidth: 100000
        burst_size: 102400
    teaming:
        load_balancing: failover_explicit
        network_failure_detection: link_status_only
        notify_switches: true
        failback: true
        active_adapters:
            - vmnic0
        standby_adapters:
            - vmnic1
  delegate_to: localhost
```

Current alternative is to run a shell script after creating the vSwitches... Something like:

```sh
#!/bin/sh

esxcli network vswitch standard policy security set -p true -v vswitch_name;
```
