### ISSUE TITLE
Support diff mode in dnf module

### ISSUE THREAD

**Issue by gsauthof** [ansible/ansible#71659]
##### SUMMARY

It would be great if the dnf module would support diff mode. Thus, when specifying `--diff` with `ansible-playbook`, one would get helpful feedback what the dnf module actually changed exactly. This would be especially helpful when specifying a list of packages - then the diff would make clear which subset of package was installed/upgraded/removed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

dnf

##### ADDITIONAL INFORMATION

For example, with a standard call like `ansible-playback -i hosts playbook.yml --diff` and a task like the following, the diff would tell the user which of the 3 packages are newly installed/upgraded:

```yaml
- name: install dev packages
  dnf:
      name:
          - cmake
          - meson
          - gcc
      state: latest
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/dnf.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/dnf.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @gsauthof 

When installing the packages the following result list is shown:

```yaml
        "Installed: libmpc-1.1.0-8.fc32.x86_64",
        "Installed: libpkgconf-1.6.3-3.fc32.x86_64",
        "Installed: binutils-2.34-4.fc32.x86_64",
        "Installed: binutils-gold-2.34-4.fc32.x86_64",
        "Installed: vim-filesystem-2:8.2.1551-1.fc32.noarch",
        "Installed: meson-0.55.1-1.fc32.noarch",
        "Installed: kernel-headers-5.8.6-200.fc32.x86_64",
        "Installed: isl-0.16.1-10.fc32.x86_64",
        "Installed: cmake-3.17.4-1.fc32.x86_64",
        "Installed: cmake-data-3.17.4-1.fc32.noarch",
        "Installed: jsoncpp-1.9.2-2.fc32.x86_64",
        "Installed: cmake-filesystem-3.17.4-1.fc32.x86_64",
        "Installed: rhash-1.3.8-3.fc32.x86_64",
        "Installed: cmake-rpm-macros-3.17.4-1.fc32.noarch",
        "Installed: pkgconf-1.6.3-3.fc32.x86_64",
        "Installed: pkgconf-m4-1.6.3-3.fc32.noarch",
        "Installed: pkgconf-pkg-config-1.6.3-3.fc32.x86_64",
        "Installed: libxcrypt-devel-4.4.17-1.fc32.x86_64",
        "Installed: glibc-devel-2.31-2.fc32.x86_64",
        "Installed: glibc-headers-2.31-2.fc32.x86_64",
        "Installed: gcc-10.2.1-1.fc32.x86_64",
        "Installed: libuv-1:1.38.0-2.fc32.x86_64",
        "Installed: ninja-build-1.10.1-2.fc32.x86_64",
        "Installed: cpp-10.2.1-1.fc32.x86_64",
        "Installed: emacs-filesystem-1:27.1-2.fc32.noarch"
```

What is the exact behavior we should expect with diff? Thank you!
