### ISSUE TITLE
ansible/template: 'item undefined'-error while templating and having (unrelated) 'item.xyz' defined

### ISSUE THREAD

**Issue by fragment86** [ansible/ansible#71658]
##### SUMMARY
ansible reports an **AnsibleUndefinedVariable: 'item' is undefined-error** when:
- template task doesn't contain *with_items*-block (not necessary, single file)
- j2-template sources additional (plain text) files using ```{% set template='...' %}``` and ```{% include template %}``` 
- additional variable referring to any *item.** is existing (variable is, however, not called within template task and should be completly unrelated)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template, jinja2

##### ANSIBLE VERSION
```
ansible 2.9.13
  config file = /home/user/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]

```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/user/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/user/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_CALLBACK_WHITELIST(/home/user/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_PRIVATE_KEY_FILE(/home/user/ansible/ansible.cfg) = /home/user/.ssh/ansible_ed25519
DEFAULT_REMOTE_USER(/home/user/ansible/ansible.cfg) = ansible
INTERPRETER_PYTHON(/home/user/ansible/ansible.cfg) = auto_silent

```

##### OS / ENVIRONMENT
target_os: ubuntu18.04.5

##### STEPS TO REPRODUCE
999_playbook.yml:
```
- name: 999_playbook

  hosts: ubuntu_servers

  vars:
    some_var: '{{ item.variable }}'

  tasks:

    - name: template /etc/999_ansible_test/template0.j2
      become: yes
      template:
        src: /home/kay/ansible/999_template0.j2
        dest: /etc/999_ansible_test/999_template0.j2
        owner: root
        group: root
        mode: '0600'
```
999_template0.j2:
```
{% set template = '999_ansible_info' %}
{% include template %}

template0
```
999_ansible_info.j2:
```
## some plain text
```

##### EXPECTED RESULTS
ansible deploys template and populates it with the content of *999_ansible_info*.

i discovered 2 workarounds:
- use *with_items* in task *template /etc/999_ansible_test/template0.j2* (should be arbitrary, but isn't)
  ```
  [...]
  - name: template /etc/999_ansible_test/template0.j2
    become: yes
    template:
      src: "{{ item.src }}"
      dest: "/etc/999_ansible_test/{{ item.dest }}"
      owner: root
      group: root
      mode: '0600'
    with_items:
      - { src: '999_template0.j2', dest: 'template0.j2' }
  [...]
  ```
- include *999_ansible_info* directly, without defining it as variable first
  999_template0.j2:
  ```
  {% include '999_ansible_info' %}

  template0
  ```

##### ACTUAL RESULTS
error: **AnsibleUndefinedVariable: 'item' is undefined** is thrown
```
fatal: [vm-elementaryos-ansible]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'item' is undefined"
}

```
