### ISSUE TITLE
SSH to ec2 instance: control socket does not exist

### ISSUE THREAD

**Issue by mifiki** [ansible/ansible#71655]
##### SUMMARY

Ansible is not able to establish SSH connection to newly provisioned EC2 instance

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Probably ec2?

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Confirmed on Ubuntu 18.04 LTS, 20.04 LTS, x86_64

##### STEPS TO REPRODUCE

Launch a playbook that provisions EC2 instance, and executes commands on it, according to documentation: https://docs.ansible.com/ansible/latest/modules/ec2_module.html

The problem is here:
```yaml
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - my_awesome_role
    - my_awesome_test
```

##### EXPECTED RESULTS

It is expected to connect to SSH instance.

##### ACTUAL RESULTS

```
Control socket "/var/lib/rundeck/.ansible/cp/ae6b976c7e" does not exist\r\ndebug2: resolving "10.1.201.189" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 10.1.201.189 [10.1.201.189] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 10.1.201.189 port 22: Connection refused\r\nssh: connect to host 10.1.201.189 port 22: Connection refused\r\n')
fatal: [10.1.201.189]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/var/lib/rundeck/.ansible/cp/ae6b976c7e\" does not exist\r\ndebug2: resolving \"10.1.201.189\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 10.1.201.189 [10.1.201.189] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: connect to address 10.1.201.189 port 22: Connection refused\r\nssh: connect to host 10.1.201.189 port 22: Connection refused", 
    "unreachable": true
```

```paste below

```

##### WORKAROUND
After hours of debugging turns out that adding a timeout before connecting to EC2 instance that we just provisioned solves the issue, like this:

```yaml
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 360
      loop: "{{ ec2.instances }}"

    **- name: Dirty workaround
      pause:
        seconds: 30**
    
- name: Configure instances
  hosts: launched
  become: True
  gather_facts: True
  remote_user: root
  roles:
    - linux
    - customer
```
