### ISSUE TITLE
ERROR! conflicting action statements: os_server, state

### ISSUE THREAD

**Issue by msalmanmasood** [ansible/ansible#71662]
##### SUMMARY

Trying to create an instance in openstack environment returns the subject 

ERROR! conflicting action statements: os_server, state

The error appears to be in '/home/skhan/skWorks/ansible/create-instance.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Creates a new instance and attaches to a network and passes userdata to the instance
      ^ here

##### ISSUE TYPE
- running ansible-playbook returns error

##### COMPONENT NAME

ansible-playbook calling openstack module

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/skhan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OS: ubuntu 20.04 
target cloud: Openstack STEIN
OS client installed: python3-openstackclient/focal,focal,now 5.2.0-0ubuntu1 all [installed]

##### STEPS TO REPRODUCE

Fresh Install ansible from the ubuntu repositories
 

```yaml

```

##### ACTUAL RESULTS

```paste below
~~~
- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Creates a new instance and attaches to a network and passes userdata to the instance
      os_server:
      state: present
      name: testVM
      image: 7a03034e-7ded-47b4-915b-0c2e44332e17
      key_name: skhan
      timeout: 200
      flavor: miniTEST
      nics:
        - net-id: 5dc18149-a196-431a-8be8-9e0f28ae31aa
        - net-name: lanNET
      network: "lanNET"
      userdata: |
        #cloud-config
        chpasswd:
          list: |
            root:{{ default_password }}
          expire: False
        packages:
          - ansible
        package_upgrade: true

~~~

```

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/playbook`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
Your indentation is incorrect. You need to indent module params like so:
```yaml
    - name: Creates a new instance and attaches to a network and passes userdata to the instance
      os_server:  
        state: present
        name: testVM
        image: 7a03034e-7ded-47b4-915b-0c2e44332e17
        key_name: skhan
        timeout: 200
        flavor: miniTEST
        nics:
          - net-id: 5dc18149-a196-431a-8be8-9e0f28ae31aa
          - net-name: lanNET
        network: "lanNET"
        userdata: |
          #cloud-config
          chpasswd:
            list: |
              root:{{ default_password }}
            expire: False
          packages:
            - ansible
          package_upgrade: true
```
