### ISSUE TITLE
Double Quotes in Command arguments are replaced with single quotes

### ISSUE THREAD

**Issue by tsia** [ansible/ansible#71665]
##### SUMMARY

* I have some JSON data in a Variable (result of a previous command)
* looking at the output of `debug` the JSON content is valid
* i'm using this variable as a argument to another command
* the double quotes inside this variable are replaced with single quotes causing tools like `jq` to complain because that is not valid JSON

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

command

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = None
  configured module search path = ['/home/<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

```paste below
<empty>
```

##### OS / ENVIRONMENT

target OS: CentOS 8
Python 3.6.8

##### STEPS TO REPRODUCE

```yaml
---
- name: Test
  hosts: all
  become: yes
  tasks:
    - name: get some json data
      command:
        argv:
          - jq
          - .auths
          - /tmp/registry-auth.json
      register: docker_auth_data
    - debug:
        var: docker_auth_data
    - name: merge pull secrets
      command:
        argv:
          - jq
          - -c
          - --argjson
          - var
          - "{{ docker_auth_data.stdout }}"
          - .auths += $var
          - /tmp/pull-secret.json
```

##### EXPECTED RESULTS

json inside a variable should stay valid JSON

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i hosts test.yml

PLAY [Test] ********************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************
ok: [ansible.local]

TASK [get some json data] ******************************************************************************************************************************************************************
changed: [ansible.local]

TASK [debug] *******************************************************************************************************************************************************************************
ok: [ansible.local] => {
    "docker_auth_data": {
        "changed": true,
        "cmd": [
            "jq",
            ".auths",
            "/tmp/registry-auth.json"
        ],
        "delta": "0:00:00.007783",
        "end": "2020-09-07 16:42:30.771254",
        "failed": false,
        "rc": 0,
        "start": "2020-09-07 16:42:30.763471",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "{\n  \"registry.example.com:8443\": {\n    \"auth\": \"Zm9vYmFyOm15X3NlY3JldF9wYXNzd29yZA==\"\n  }\n}",
        "stdout_lines": [
            "{",
            "  \"registry.example.com:8443\": {",
            "    \"auth\": \"Zm9vYmFyOm15X3NlY3JldF9wYXNzd29yZA==\"",
            "  }",
            "}"
        ]
    }
}

TASK [merge pull secrets] ******************************************************************************************************************************************************************
fatal: [ansible.local]: FAILED! => {"changed": true, "cmd": ["jq", "-c", "--argjson", "var", "{'registry.example.com:8443': {'auth': 'Zm9vYmFyOm15X3NlY3JldF9wYXNzd29yZA=='}}", ".auths += $var", "pull-secret.json"], "delta": "0:00:00.004928", "end": "2020-09-07 16:42:31.626875", "msg": "non-zero return code", "rc": 2, "start": "2020-09-07 16:42:31.621947", "stderr": "jq: invalid JSON text passed to --argjson\nUse jq --help for help with command-line options,\nor see the jq manpage, or online docs  at https://stedolan.github.io/jq", "stderr_lines": ["jq: invalid JSON text passed to --argjson", "Use jq --help for help with command-line options,", "or see the jq manpage, or online docs  at https://stedolan.github.io/jq"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************************************************************************************************************************
ansible.local  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

output of run with `-vvv`: https://gist.github.com/tsia/34ebab74c71a20caef5eb5ca4ff648e8
