### ISSUE TITLE
list: updates in dnf module doesn't list obsolete packages

### ISSUE THREAD

**Issue by dangel101** [ansible/ansible#71696]
##### SUMMARY

when running the ansible module dnf: list: updates there are no results listed, while there are obsolete packages to update

when running dnf check-update from shell I get these results:

```
[root@localhost yum.repos.d]# dnf check-update
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
my-updates                                                                                            74 kB/s | 1.1 kB     00:00    
Obsoleting Packages
redhat-virtualization-host-image-update.noarch                                 4.4.0-20200409.1.el8_2                  rhvh44-updates
redhat-virtualization-host-image-update-placeholder.noarch                     4.4.0-8.el8ev                           @System       

The result of dnf: list: updates is:
ok: [192.168.100.194] => {
    "my_updates": {
        "changed": false,
        "failed": false,
        "msg": "",
        "results": []
    }
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dnf module

##### ANSIBLE VERSION

```paste below
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

tested on RHVH4.4

##### STEPS TO REPRODUCE

```yaml
dnf check-update versus the playbook below. the output is in the description
- name: get dnf check updates
  dnf: 
    list: updates
  register: my_updates
  ignore_errors: yes

- name: print check updates results
  debug:
    var: my_updates

```

##### EXPECTED RESULTS

list the obsolete packages to update

##### ACTUAL RESULTS

obsolete packages aren't listed

```paste below

```
