### ISSUE TITLE
get_url support for range header

### ISSUE THREAD

**Issue by poodge** [ansible/ansible#71690]
##### SUMMARY
get_url should support range header natively, also if multiple ranges are suppled they are all combined to the destination file

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
get_url
##### ADDITIONAL INFORMATION
There are a few issues in downloading large files
1. Currently, files cannot be broken into chunks and each chunk (range) downloaded simultaneously 
2. Because there is no resume network resets will cause the user to have to download the whole file again

Instead of the file below that I have to piece together 
```
- name: Download file
  get_url:
    url: https://example.com/reallybigfile
    dest: "/home/user/{{item}}_reallybigfile"
    headers:
      Range: "bytes={{item}}"
  loop: ranges
```
Support ranges could look like this
```
- name: Download file
  get_url:
    url: https://example.com/reallybigfile
    dest: "/home/user/{{item}}_reallybigfile"
    range: 0-100,101-200,201-300
```
The destination is then all ranges concatenated together
