### ISSUE TITLE
Failed to set a new url https://user:token_urlencoded@sub.domain.com/bitbucket/scm/project/project.git for origin:  fatal: No such remote 'origin'\n

### ISSUE THREAD

**Issue by blagoy89** [ansible/ansible#71716]
##### SUMMARY
Ansible's git module can't update the repo even though update: option is set to yes

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION

```
ansible 2.9.12
  config file = /opt/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]

```

##### CONFIGURATION

```
an empty text file opened for editing
```

##### OS / ENVIRONMENT
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 3

##### STEPS TO REPRODUCE
Something else (not ansible) updates the repo between two runs of the playbook and removes the ORIG_HEAD, on the second run the issue appears.

Initially everything is fine when Ansible's git module clones the repo

```
- hosts: mgmt[0]
  tasks:
  - name: "git clone or git pull the config repo"
    git:
      repo: "https://user:{{ token_urlencoded }}@sub.domain.com/bitbucket/scm/project/project.git"
      dest: /tmp/project/repo
      clone: yes
      update: yes
      version: master
    register: repo_up
    retries: 5
    delay: 30
    until: repo_up is not failed
    environment:
      HTTP_PROXY: "{{ https_proxy }}"
      HTTPS_PROXY: "{{ https_proxy }}"
      GIT_SSL_CERT: /path/to/certs/name.crt
      GIT_SSL_CAINFO: /path/to/certs/name-dn.crt
      GIT_SSL_KEY: /path/to/certs/name.key
```

##### EXPECTED RESULTS
First time you run, it clones the repo. Then a different program not ansible updates the repo. When you run the playbook again, it comes up with the error in the subject

Failed to set a new url https://user:token_urlencoded@sub.domain.com/bitbucket/scm/project/project.git for origin:  fatal: No such remote 'origin'\n

##### ACTUAL RESULTS
The entire message is provided in the subject and above
