### ISSUE TITLE
Bug running htpasswd module after updating from 2.4 to 2.9 (bad -H parameter)

### ISSUE THREAD

**Issue by aepel** [ansible/ansible#71721]
##### SUMMARY

I was running the following script without problems in version 2.4 of ansible.
I have recently updated to 2.9 and from there it stops working.
```yaml
- name: nagios Website Admin User
   htpasswd:
     path: /usr/local/nagios/etc/htpasswd.users
     name: "{{nagios_admin}}"
     password: "{{nagios_admin_password}}"
   notify: apache_restart
```
##### ISSUE TYPE
- Bug Report
```
fatal: [54.162.85.159]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 54.162.85.159 closed.\r\n",
    "module_stdout": "su: invalid option -- 'H'\r\nUsage: su [options] [LOGIN]\r\n\r\nOptions:\r\n  -c, --command COMMAND         pass COMMAND to the invoked shell\r\n  -h, --help                    display this help message and exit\r\n  -, -l, --login                make the shell a login shell\r\n  -m, -p,\r\n  --preserve-environment        do not reset environment variables, and\r\n                                keep the same shell\r\n  -s, --shell SHELL             use SHELL instead of the default in passwd\r\n\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 2
}
```
##### COMPONENT NAME

htpasswd
##### ANSIBLE VERSION

```paste below
2.9
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Target: Ubuntu 18.04
Source: Ubuntu 20.04

##### STEPS TO REPRODUCE

Analyzing the verbose output I've found that ansible is generating the next command
```bash
/bin/sh -c "sudo su --shell /bin/bash -H -S -n  -u nagios /bin/sh -c 'echo BECOME-SUCCESS-jpmtjwvneofxyqunhrwnrcepheemxllq ; /usr/bin/python /var/tmp/ansible-tmp-1599821921.7309754-46679193358529/AnsiballZ_htpasswd.py' && sleep 0"
```

The complaint remains on "-H" parameter which it doesn't exists.

```yaml
- name: nagios Website Admin User
   htpasswd:
     path: /usr/local/nagios/etc/htpasswd.users
     name: "{{nagios_admin}}"
     password: "{{nagios_admin_password}}"
   notify: apache_restart
```

##### EXPECTED RESULTS

Generate the password on that file.

##### ACTUAL RESULTS

```paste below

```
