### ISSUE TITLE
Module get_url mode wont work if not quoted

### ISSUE THREAD

**Issue by juanbernhard** [ansible/ansible#71723]
##### SUMMARY
Module get_url wont set the execute permission if the mode setting isnt quoted.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/juan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root

```

##### OS / ENVIRONMENT

Tested on centos 8 

##### STEPS TO REPRODUCE

```yaml
      - name: Descargar el docker-compose
        get_url:
          url: https://github.com/docker/compose/releases/download/1.27.2/docker-compose-Linux-x86_64
          dest: /usr/bin/docker-compose
          mode: 0755
```

##### EXPECTED RESULTS

File permission is 755

##### ACTUAL RESULTS

File permission is 644 (no execute)

```paste below

```
