### ISSUE TITLE
Allow combining tags with AND

### ISSUE THREAD

**Issue by Zocker1999NET** [ansible/ansible#71733]
##### SUMMARY

Currently, you can only choose to select multiple tags like `--tags a,b` which will issue to run tasks tagged only with `a` or `b` and both `a` + `b`. But I was required to only run a task tagged with `a` + `b`. So it would be great to have a feature like `--tags a+b` / `--tags 'a&b'` / `--tags a:b`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

tags

##### ADDITIONAL INFORMATION

For example you have following tasks with the given tags:

```yaml
- name: Task A
  debug: msg=TaskA
  tags: tagA
- name: Task B
  debug: msg=TaskB
  tags: tagB
- name: Task C
  debug: msg=TaskC
  tags:
    - tagA
    - tagB
```

Currently, you can run Task A and C with `--tags tagA` or Task B and C with `--tags tagB`. The new feature should you allow to only run Task C with `--tags tagA:tagB` (or with any other syntax).

Note: It is not always possible to tag certain tasks correctly with an tag called `a+b` due to reusing roles, for example with the playbook:
```yaml
- hosts: all
  roles:
    - role: myrole
      myname: alice
      tags: alice
    - role: myrole
      myname: bob
      tags: bob
```
and following `roles/myrole/tasks/main.yml`:
```yaml
- name: Task1
  debug: msg=Task1
  tags: task1
- name: Task2
  debug: msg=Task2
  tags: task2
```
