### ISSUE TITLE
Variable undefined when including tasks from a separate file

### ISSUE THREAD

**Issue by lerminou** [ansible/ansible#71746]
##### SUMMARY

When defaulting a variable in a task in the playbook, it works, but when i set the exact same code in a task file called this way:
Playbook > tasks > include_tasks (or import_tasks), it fails with message "undefined variable"

This helper adds ability to template a remote file, if this task could be integrated in the core it would be awesome ...

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
  ansible 2.9.13
  config file = /home/pc/ansible/ansible.cfg
  configured module search path = ['/home/pc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/home/pc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Centos 8 / fedora 32

##### STEPS TO REPRODUCE

```yaml
Playbook
---
- hosts: all
  handlers:
    - import_tasks: handlers/main.yml
  tasks:
    - include_tasks: tasks/template_remote_file.yml
      vars:
        input_template_file: "/opt/data/products.json.template"
        output_template_file: "/opt/data/products.json"
        #run_oncex: false ### fails if commented

tasks/template_remote_file.yml

- name: "fetch {{input_template_file | basename}} from remote host"
  run_once: "{{ run_oncex | default(true) }}" ### UNDEFINED VAR ### EXACT same code directly in the playbook in the tasks: section works
  fetch:
    src: "{{input_template_file}}"
    dest: "/tmp/file_{{ run_oncex | ternary('', inventory_hostname, omit) }}_{{ansible_date_time.epoch}}.json" # prefix file by hostname if run_once if false
    flat: yes
    fail_on_missing: yes
  register: local_template_cfg

- name: "configure {{input_template_file | basename}} template "
  template:
    src: "{{local_template_cfg.dest}}"
    dest: "{{output_template_file}}"
    mode: "{{ file_permissions | default(0644) }}"
    owner: "{{ file_owner | default('root') }}"
    group: "{{ file_group | default('root') }}"

- name: remove local template file
  file:
    path: "{{local_template_cfg.dest}}"
    state: absent
  delegate_to: 127.0.0.1
  become: false
  run_once: "{{ run_oncex | default(true) }}"

```

##### EXPECTED RESULTS

the variable is the default value

##### ACTUAL RESULTS

```paste below
{"msg": "The task includes an option with an undefined variable. The error was: 'run_oncex' is undefined\n\nThe error appears to be in '/home/pc/ansible/tasks/template_remote_file.yml': line 2, column 3[...]
```
