### ISSUE TITLE
postgresql_user - allow setting search_path for the role

### ISSUE THREAD

**Issue by ajchiarello** [ansible/ansible#71747]
##### SUMMARY
When creating a new postgresql_user (role), allow setting the role's search_path.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
postgresql_user

##### ADDITIONAL INFORMATION
When creating a new postgres role, sometimes you need to specify a specific search_path property - this would allow that to be configured.

```yaml
- name: create repmgr user
      become_user: postgres
      postgresql_user:
        name: repmgr
        role_attr_flags: CREATEDB,CREATEROLE,REPLICATION,SUPERUSER
        search_path: 'repmgr_test, "$user", public'
```
