### ISSUE TITLE
Ansible 'aws_secret ' not able assign variable for region

### ISSUE THREAD

**Issue by gowthamakanthan** [ansible/ansible#71742]
##### SUMMARY

Am trying to variablize all the parameter part of the ```aws_secret``` plugin. But not able to assign variable for the region. Have tried something like```'{{ aws_secret_region }}'``` , ```'\"{{ aws_secret_region }}\"'```, it's throwing error as ``` Provided region_name '{{aws_secret_region}}' doesn't match a supported format."```. When trying to pass the region as the environment variable or arg, it's throwing ```You must specify a region`` error  Any suggestions? 

##### COMPONENT NAME
aws_secret
##### ANSIBLE VERSION

```
ansible 2.9.5

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/tmp/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/tmp/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=30m -F ./ssh-dev.cfg
ANSIBLE_SSH_CONTROL_PATH(/tmp/ansible/ansible.cfg) = /tmp/ansible-%%r@%%h:%%p
DEFAULT_LOCAL_TMP(/tmp/ansible/ansible.cfg) = /tmp/.ansible-test/tmp/ansible-local-184762tLWzs
DEFAULT_TIMEOUT(/tmp/ansible/ansible.cfg) = 10
HOST_KEY_CHECKING(/tmp/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- name: test
   hosts: localhost
  vars:
        aws_secret_key: "{{ aws_secret_key }}"
        db_password: "{{ lookup('aws_secret', '{{ aws_secret_name }}', region='us-east-1') | from_json | json_query('\"' + aws_secret_key + '\"') }}"
```

##### EXPECTED RESULTS

Able to assign a variable for the region. 

##### ACTUAL RESULTS

```paste below
* fatal: [10.1.24.12]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('aws_secret', '{{ aws_secret_name }}') | from_json | json_query('\"' + aws_secret_key + '\"') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'aws_secret'. Error was a <class 'botocore.exceptions.NoRegionError'>, original message: You must specify a region."}

* Provided region_name '{{aws_secret_region}}' doesn't match a supported format."
```
