### ISSUE TITLE
Unable to add adress to fortigate adressbook when vdom is uppercase (fortios_address)

### ISSUE THREAD

**Issue by Th3ju** [ansible/ansible#71760]
##### SUMMARY
Unable to add adress to fortigate adressbook when vdom is uppercase. Work perfectly when using a lowercase vdom name.
I have this message : 

 "msg": "Error reading running config. 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)"

If I chage the name to lowercase, rules are added but a new VDOM is created as Fortios is case sensitive for VDOM names. 
If I sue existing vdom in lower case, this playbook works.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fortios_address 

##### ANSIBLE VERSION

```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/julien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]

```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/julien/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Source OS : 
Linux SSI13-JG 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Destination OS : 
FortiOS v5.2.13,build762 (GA) to v6.0.8 build0303 (GA)

##### STEPS TO REPRODUCE
Just launch the playbook : 

ansible-playbook Update_Forti_Adresses.yaml

```
- hosts: localhost
  gather_facts: False
  connection: local
  vars:
    host: "10.1.7.9"
    vdom: "DELEG"
    username: admin
    password: "passowd"

  tasks:
  - name: Insert EXTRA-EMOTET-1
    fortios_address:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      type: ipmask
      state: present
      name: EXTRA-EMOTET-1
      value: 96.227.52.8

```

##### EXPECTED RESULTS
Expected to have a new adress in adressbook if the vdom is in uppercase

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fortios_address_payload_V0Y5r2/ansible_fortios_address_payload.zip/ansible/module_utils/network/fortios/fortios.py", line 276, in load_config
    self.forti_device.load_config(path=path)
  File "/usr/lib/python2.7/dist-packages/pyFG/fortios.py", line 212, in load_config
    config_text = self.execute_command(command)
  File "/usr/lib/python2.7/dist-packages/pyFG/fortios.py", line 154, in execute_command
    output = output + self._read_wrapper(o)
  File "/usr/lib/python2.7/dist-packages/pyFG/fortios.py", line 120, in _read_wrapper
    return py23_compat.text_type(data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "backup": false, 
            "backup_filename": null, 
            "backup_path": null, 
            "comment": null, 
            "config_file": null, 
            "country": null, 
            "end_ip": null, 
            "file_mode": false, 
            "host": "10.1.7.9", 
            "interface": "any", 
            "name": "EXTRA-EMOTET-1", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "start_ip": null, 
            "state": "present", 
            "timeout": 60, 
            "type": "ipmask", 
            "username": "admin", 
            "value": "96.227.52.8 255.255.255.255", 
            "vdom": "DELEG"
        }
    }, 
    "msg": "Error reading running config. 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)"
}

```

Thanks for your help.
Regards,

Juju
