### ISSUE TITLE
[WARNING]: Removed restricted key from module data: ansible_facts = {'discovered_ ... thon'}

### ISSUE THREAD

**Issue by dkoshkin** [ansible/ansible#71762]
##### SUMMARY

Seems to be the same as https://github.com/ansible/ansible/issues/69446
It says the issue was fixed in `v2.9.10`, but seeing it in `2.9.13`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`set_fact` with `delegate_to` and `loop`. 

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = None
  configured module search path = ['/Users/dkoshkin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
[defaults]
stdout_callback = debug
hash_behaviour=merge
timeout = 60
host_key_checking = False
forks = 20
gathering = smart
strategy_plugins = ../mitogen/ansible_mitogen/plugins/strategy
strategy = mitogen_linear
force_valid_group_names = ignore
```

##### OS / ENVIRONMENT

CentOS7

##### STEPS TO REPRODUCE

```yaml
    - name: check encryption-config.yaml already exist on other nodes
      stat:
        path: "/etc/kubernetes/pki/encryption-config.yaml"
      register: encryption_files
      delegate_to: "{{ item }}"
      loop: "{{ groups['control-plane'] | difference([inventory_hostname]) }}"

    - name: find any node with encryption-config.yaml
      set_fact:
        nodes_with_encryption_file: "{{ encryption_files.results | json_query('[?stat.exists]') }}"
```

##### EXPECTED RESULTS

Not seeing the `[WARNING]`.

##### ACTUAL RESULTS

```paste below
TASK [kubeadm-control-plane : check encryption-config.yaml already exist on other nodes] *****************************************************************************************************************************************************
skipping: [10.0.193.200] => (item=10.0.192.40)
skipping: [10.0.193.200] => (item=10.0.194.246)
ok: [10.0.194.246] => (item=10.0.192.40)
ok: [10.0.194.246] => (item=10.0.193.200)
[WARNING]: Removed restricted key from module data: ansible_facts = {'discovered_ ... thon'}

TASK [kubeadm-control-plane : find any node with encryption-config.yaml] *********************************************************************************************************************************************************************
skipping: [10.0.193.200]
ok: [10.0.194.246]
```
