### ISSUE TITLE
Data returned by module is masked with "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER".

### ISSUE THREAD

**Issue by rjeffman** [ansible/ansible#71789]
##### SUMMARY

When trying to retrieve data from a module, if the data retrieved is the same as a no_log field, the data retrieved is masked.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- Ansible log.

##### ANSIBLE VERSION
```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rjeffman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### CONFIGURATION
```
DEFAULT_LOG_PATH(/home/rjeffman/Developer/ansible-freeipa/rafasgj/ansible.cfg) = /home/rjeffman/Developer/ansible-freeipa/rafasgj/ansible.log
```

##### OS / ENVIRONMENT

Controler:
    - Fedora 32
    - Linux dantooine.local 5.8.7-200.fc32.x86_64 #1 SMP Mon Sep 7 15:26:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Target Host:
    - Centos 8 
    -  Linux cos81.ipa.test 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

The problem is reproduced  by running the attached playbook with [ansible-freeipa](https://github.com/freeipa/ansible-freeipa) ipavault module.

Note that the attributes `ipaadmin_password` and `data` has `no_log` set, but the result for `state: retrieved` should not be masked, as it was explicit requested, but since it is the same as `ipaadmin_password`, it returns as `"VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"`, although it was not.

```yaml
---
- name: Example on using vault to store a password and use it later.
  hosts: ipaserver
  become: yes
  gather_facts: yes

  tasks:
  - name: Create private key file.
    shell:
      cmd: openssl genrsa -out private.pem 2048
    delegate_to: localhost
    become: no

  - name: Create public key file.
    shell:
      cmd: openssl rsa -in private.pem -outform PEM -pubout -out public.pem
    delegate_to: localhost
    become: no

  - name: Ensure asymmetric vault is present
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: asymvault
      vault_type: asymmetric
      public_key: "{{ lookup('file', 'public.pem') | b64encode }}"

  - name: Archive data to asymmetric vault
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: asymvault
      data: SomeADMINpassword

  - name: Retrieve data from asymmetric vault.
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: asymvault
      private_key: "{{ lookup('file', 'private.pem') | b64encode }}"
      state: retrieved
    register: result

  - debug:
      msg: "{{ result.vault.data }}"

  - name: Use vault data to login.
    shell:
      cmd: echo "{{ result.vault.data }}" | kinit admin
    register: result

  - debug:
      msg: "{{ result }}"
```
