### ISSUE TITLE
Support --check mode for `pip install --user`

### ISSUE THREAD

**Issue by ddimtirov** [ansible/ansible#71781]
##### SUMMARY
Currently when we need to specify `pip install --user ...`, the `--user` argument goes in as extra argument. This breaks the `ansible --check` mode, as illustrated byt he following commands:

```yaml
# OK
ansible -m pip -a "extra_args=--user name=pytz" $HOSTNAME

# CHANGED
ansible -m pip -a "extra_args=--user name=pytz" $HOSTNAME --check
```

The code responsible for this behaviour is here: https://github.com/ansible/ansible/blob/195c8b496ee48c155a5d0976735087bc6bb06f38/lib/ansible/modules/pip.py#L719

I would like to request that we either add a separate parameter to request that pip installation is in the user site, or add a further analysis of the content of the extra args (and if it is only `--user` run the check mode). The latter option would transparently fix all current playbooks which erroneously report `changed`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`pip` module

##### ADDITIONAL INFORMATION

```yaml
- name: Install ansible and dependencies on all hosts
  pip:
    name: ['ansible==2.9.6', 'pytz', 'lxml', 'ansible-lint', 'python-dateutil']
    extra_args: --user
```

Could become:

```yaml
- name: Install ansible and dependencies on all hosts
  pip:
    name: ['ansible==2.9.6', 'pytz', 'lxml', 'ansible-lint', 'python-dateutil']
    user_site: on
```
