### ISSUE TITLE
validate-modules for plugins: what's with name: next to description: in option descriptions?

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#71792]
##### SUMMARY
This is not a bug, but a discussion issue for one aspect of #71734 ([WIP] Extend validate-modules to also validate plugins). It provides details on one of the points in https://github.com/ansible/community/issues/560#issuecomment-691529907.

In some plugins, most notably in the default_callback docs fragment, options sometimes have `name:` next to `description:`: https://github.com/ansible/ansible/blob/d63d8803836df3231ba66f6e3a54576169d9f3a0/lib/ansible/plugins/doc_fragments/default_callback.py#L13-L15

This is not shown in the HTML docs (https://docs.ansible.com/ansible/latest/plugins/callback/default.html#parameter-display_skipped_hosts), and in ansible-doc it is also not very prominent:
```
- display_skipped_hosts
        Toggle to control displaying skipped task/host results in a task
        [Default: True]
        set_via:
          env:
          - deprecated:
              alternatives: the "ANSIBLE_DISPLAY_SKIPPED_HOSTS" environment variable
              removed_from_collection: ansible.builtin
              version: '2.12'
              why: environment variables without "ANSIBLE_" prefix are deprecated
            name: DISPLAY_SKIPPED_HOSTS
          - name: ANSIBLE_DISPLAY_SKIPPED_HOSTS
          ini:
          - key: display_skipped_hosts
            section: defaults
        
        name: Show skipped hosts
        type: bool
```

Do we want to keep it (and allow it in the schema)? But then we also should use it properly (how?). Or should we get rid of it?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-test validate-modules

##### ANSIBLE VERSION
2.11
