### ISSUE TITLE
DNF module -- state: present does not pull in package of specified version if outdated package already exists

### ISSUE THREAD

**Issue by msilmser** [ansible/ansible#71808]
##### SUMMARY
When using the DNF module to install a specific version of a package, we detect that the package exists and the module will not install the specified version if another version is already installed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dnf.py
##### ANSIBLE VERSION

```
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
NA
```

##### OS / ENVIRONMENT
RHEL 7 (control) >> RHEL 8 (target)

##### STEPS TO REPRODUCE
1. Verify an older package of a version exists on system.
```
[root@rhel8 tmp]# rpm -qa | grep NetworkManager
NetworkManager-libnm-1.14.0-14.el8.x86_64
NetworkManager-1.14.0-14.el8.x86_64
```
2. Run playbook to install a specific, updated version of that package:
```
- hosts: all
  vars:
    ansible_private_ssh_key_file: /root/.ssh/id_rsa
  tasks:
    - dnf:
        name: NetworkManager-1.22.8-5.el8_2.x86_64
        state: present
```
3. Observe task output

##### EXPECTED RESULTS
DNF module installs the specified version of the package.

##### ACTUAL RESULTS
DNF module returns nothing to do as an existing package is found.

 https://gist.github.com/msilmser/54ea71370af18d928caf40435896f66b
