### ISSUE TITLE
Module win_get_url should allow to skip download based on checksum

### ISSUE THREAD

**Issue by ygversil** [ansible/ansible#71804]
##### SUMMARY

It would be nice if the `win_get_url` module could skip downloads based on checksum comparison, instead of relying only on timestamp comparison which is notoriously not reliable.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`win_get_url` module.

##### ADDITIONAL INFORMATION

Currently, the `win_get_url` module only skips download based on `mtime` comparison (with parameter `force=no`). If the remote file is newer than local existing one, it will be downloaded again, even if the remote file content has not changed at all (for example, if the file on the remote server has been cloned, the clone `mtime` will be newer).

Furthermore, `mtime` comparison is done by sending an HTTP `HEAD` request to retrieve `mtime` of the remote file, but not all HTTP servers support or allow this type of request. For example GitHub returns a `403 Forbidden` (try `win_get_url` twice with `force=no` and `url=https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.x64.exe`: the first time, the file is downloaded, the second time raises an exception).

I believe that download should be skipped based on checksum comparison: if `checksum` and `checksum_algorithm` are provided, then there should be a way to prevent the file to be downloaded again when its checksum matches the provided one. 

Maybe we can add a `skip_comparison` (or whatever name) parameter with two possible values: `'timestamp'` and `'checksum'`. The default value will be `'timestamp'` to keep backward compatibility. This parameter will only have effect if `force` parameter is `no`. And if `skip_comparison='checksum'`, then `checksum` and `checksum_algorithm` must be provided, else an exception is raised.

Hence with the following playbook snippet, the file will be downloaded the first time. The second time checksum comparison is done, checksum matches, so the file is not downloaded again. And this avoid the error due to GitHub not allowing `HEAD` requests.

```yaml
- name: Ensure Notepad++ tarball is present
  win_get_url:
    url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.4/npp.7.8.4.Installer.x64.exe
    dest: C:\Packages\npp.7.8.4.Installer.x64.exe
    checksum: a78e190d563aaffb088e0a239e9c9c5b0fca1a1f
    checksum_algorithm: sha1
    force: false
    skip_comparison: checksum
```

This feature will be great to avoid downloading large files again. Another argument in favor of this feature is to better align with the `get_url` module which uses checksum comparison to skip downloads.
