### ISSUE TITLE
FQCN with free-form  does not work for modules/action plugins supporting free-form without FQCN

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible#71817]
##### SUMMARY
When using `ansible.builtin.command` or `ansible.builtin.include_vars`, the free-form no longer works and results in:
```
ERROR! this task 'ansible.builtin.command' has extra params, which is only allowed in the following modules: include_vars, script, win_command, command, include, add_host, shell, ansible.windows.win_shell, import_tasks, raw, include_role, group_by, import_role, ansible.windows.win_command, meta, win_shell, set_fact, include_tasks
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```paste below
2.10
```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:
    - ansible.builtin.command: ls
```

##### EXPECTED RESULTS
`ls` is executed

##### ACTUAL RESULTS
```
ERROR! this task 'ansible.builtin.command' has extra params, which is only allowed in the following modules: include_vars, script, win_command, command, include, add_host, shell, ansible.windows.win_shell, import_tasks, raw, include_role, group_by, import_role, ansible.windows.win_command, meta, win_shell, set_fact, include_tasks

The error appears to be in 'test-command-fqcn.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - ansible.builtin.command: ls
      ^ here
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by SimonHeimberg** [comment]
for ansible.builtin.command the parameter `cmd ` fails as well (from duplicate #71878)

```yaml
- hosts: all,localhost
   tasks:
    - ansible.builtin.command:
        cmd: echo a b c
```

ACTUAL RESULTS

The playbook fails, reporting:

```
TASK [ansible.builtin.command] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.builtin.command) module
```

**Comment by SimonHeimberg** [comment]
Please fix this for 2.9 as well

**Comment by SezBulent** [comment]
Confirm that it happens in 2.10, with the following structure:

**playbook.yml**
```yml
---
- hosts: test
  become: true
  roles:
    - role: test
```

**roles/test/tasks/main.yml**
```yml
---
- import_tasks: test.yml
  tags: test
```

**roles/test/tasks/test.yml**
```yml
---
- name: Enable no-thp profile
  ansible.builtin.command: sudo tuned-adm profile virtual-guest-no-thp
```


**Result:**

```
ERROR! this task 'ansible.builtin.command' has extra params, which is only allowed in the following modules: include, ansible.windows.win_shell, script, import_tasks, ansible.windows.win_command, shell, include_tasks, meta, raw, group_by, set_fact, include_role, import_role, add_host, win_command, win_shell, command, include_vars
```
