### ISSUE TITLE
office_365_connector_card modules - facts function

### ISSUE THREAD

**Issue by MikeAnders168** [ansible/ansible#71810]
##### SUMMARY

Module structure of "facts" function seem to be dictionary based while requirement is that it's list based.

https://github.com/jillr/ansible/blob/da8b8cddf4b8559c64f24696dbf56bb2ab5c32a3/lib/ansible/modules/notification/office_365_connector_card.py#L164

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

office_365_connector_card
https://github.com/jillr/ansible/blob/da8b8cddf4b8559c64f24696dbf56bb2ab5c32a3/lib/ansible/modules/notification/office_365_connector_card.py

##### ANSIBLE VERSION

```paste below
ansible 2.8.8
python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT

RHEL 7.7

##### STEPS TO REPRODUCE

Use facts module as per documentation. 
https://docs.ansible.com/ansible/2.7/modules/office_365_connector_card_module.html

```yaml
- name: Teams notification
  office_365_connector_card:
    webhook: https://outlook.office.com/webhook/...
    title: 'Some text'
    text: 'Some more text'
    sections:
      facts:
      - name: "Hostname"
        value: "{{ ansible_hostname }}"
      - name: "Environment"
        value: "{{ ansible_domain }}"
      - name: "Memory"
        value: "{{ ansible_memtotal_mb }}"
      - name: "vCPUs"
        value: "{{ ansible_processor_vcpus }}"
      - name: "IP"
        value: "{{ ansible_default_ipv4.address }}"
      - name: "Release"
        value: "{{ ansible_distribution_version }}"
      - name: "Platform"
        value: "{{ ansible_system_vendor }}"
      - name: "Satellite ID"
        value: "{{ foreman_user.stdout.split('|')[0] }}"
      - name: "Created by"
        value: "{{ foreman_user.stdout.split('|')[3] }}"
      - name: "Initiation time"
        value: "{{ foreman_user.stdout.split('|')[1] }}"
      - name: "Completion time"
        value: "{{ ansible_date_time.iso8601 }}"
```

##### EXPECTED RESULTS

MS Teams notification with content

Some text
Some more text
-----------Section------------
Fact     some facts
fact2   some more facts
fact3   even more facts

##### ACTUAL RESULTS

```paste below
2020-09-18 15:19:35,949 p=22645 u=foreman-proxy |  fatal: [host31.example.org -> localhost]: FAILED! => changed=false
  msg: 'argument sections is of type <type ''dict''> and we were unable to convert to list: <type ''dict''> cannot be converted to a list'

```
