### ISSUE TITLE
[azure_rm_virtualmachine] - Cherrypick fix Protect against no diskSizeGB for Ansible 2.9

### ISSUE THREAD

**Issue by tchellomello** [ansible/ansible#71822]
##### SUMMARY
[azure_rm_virtualmachine] - Cherrypick fix Protect against no diskSizeGB for Ansible 2.9

Please cherry-pick https://github.com/ansible-collections/azure/pull/185/files and have it included on Ansible 2.9.x

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.9.12
```

##### STEPS TO REPRODUCE
Executing the playbook below produces the traceback 

```yaml
    - name: Power On
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ hostname }}"
```

##### EXPECTED RESULTS
Cherrypick fix https://github.com/ansible-collections/azure/pull/185/files

##### ACTUAL RESULTS

```yaml
{
    "_ansible_no_log": false,
    "module_stderr": "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_RpKZyh/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 2202, in <module>\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_RpKZyh/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 2198, in main\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_RpKZyh/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 901, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_RpKZyh/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py\", line 348, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_RpKZyh/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 1574, in exec_module\nKeyError: 'diskSizeGB'\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```
