### ISSUE TITLE
Devel :: Synchronize module issue with rsync_path

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible#7182]
Hello,
##### Issue Type:

Bug Report
##### Ansible Version:

1.6 devel
##### Environment

:: host :: ArchLinux
:: managed ::  Debian 7
##### Summary:

Just found an issue with double quotation and escaping of rsync_path parameter of synchronize module, that leads to `command not found` error
This problem appears when you alternate rsync_path as described in one of module examples http://docs.ansible.com/synchronize_module.html

```
# Synchronize using an alternate rsync command
synchronize: src=some/relative/path dest=/some/absolute/path rsync_path="sudo rsync"
```
##### Steps To Reproduce:

Example playbook for debug on local box:

``` yaml
- name: 'Test synchronize rsync_path escaping'
  hosts: vagrant
  remote_user: vagrant
  sudo_user: root
  sudo: yes

  tasks:
   - name: 'Test | synchronize'
     synchronize: src=/tmp/test/
                  dest=/tmp/test/
                  recursive=yes
                  delete=yes
                  rsync_path="sudo rsync"
```

This construction even not work when I comment `rsync_path="sudo rsync"` line, because it is default option when `sudo` is set https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/action_plugins/synchronize.py#L193
##### Expected Results:

1.5.x output is OK and expected: http://pastebin.com/HeY4F38R
`--rsync-path 'sudo rsync'`
##### Actual Results:

For 1.6 output is: http://pastebin.com/7UTLamKZ
`--rsync-path '\"sudo rsync\"'`
