### ISSUE TITLE
Bug: valid extra-vars JSON containing curly braces raise variable is undefined error

### ISSUE THREAD

**Issue by jfoliveira** [ansible/ansible#71827]
##### SUMMARY

Invoking `ansible-playbook` with valid JSON content fails when JSON attribute values contain double curly braces, as ansible seems to perform variable substitution in the provided strings.

I've already tried all alternatives that I found in docs and previous issues in this repo, such as `!unsafe`, `{% raw %} ... {% endraw %}`, using jinja2 templates and setting `variable_start_string='[%', variable_end_string='%]'`. However none of the alternatives worked.

Is there a way (env var, ansible.cfg setting, ...) to tell ansible to not evaluate external variables values?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.11
  config file = /home/usr/playbooks/ansible.cfg
  configured module search path = ['/home/usr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/usr/.local/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/usr/playbooks/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/usr/playbooks/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/usr/playbooks/ansible.cfg) = -C -o ControlPersist=30s -o PreferredAuthentications=publickey -o ControlMaster=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_WHITELIST(/home/usr/playbooks/ansible.cfg) = ['json', 'timer']
DEFAULT_ROLES_PATH(/home/usr/playbooks/ansible.cfg) = ['/home/usr/playbooks/remote/roles', '/etc/ansible/roles', '/home/usr/.ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/usr/playbooks/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/usr/playbooks/ansible.cfg) = False
INTERPRETER_PYTHON(/home/usr/playbooks/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/usr/playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

1) Paste the content of playbook below to a file named "_curly_braces_in_var_value.yml"
2) Invoke `ansible-playbook` passing expected variables with one or more of them containing values surrounded by double curly braces. **Example command line**:
```
ansible-playbook _curly_braces_in_var_value.yml -e='{"variables": { "var_1": "variable value may contain {{ variable_like_token }} text", "var_2": "another value for {{ variable_2 }}"}}'
```

```yaml
---
- hosts: localhost
  gather_facts: no

  pre_tasks:
  - name: Ensure required variables are set
    fail:
      msg: "Variable '{{ item }}' is not defined"
    when: "{{ item }} == '' or {{ item }} is none"
    # if I fix the ansible warning [WARNING]: conditional statements should not include jinja2 templating ...
    # then all items are skipped and no validation is performed :-(
    with_items:
      - variables
      - variables.var_1
      - variables.var_2
      # - variables.var_3 # uncommenting this I expect the task to fail, as `var_3` is not provided in extra params


  tasks:
  - debug:
      msg: "Expecting the original non-parsed variable value here: {{ variables.var_1 }}"
```

##### EXPECTED RESULTS

`debug` task output should display the literal value of variable `var_1`. Expected output:
```
TASK [debug] *************************************************************************************************************************************************************
ok: [localhost] => {}

MSG:

Expecting the original non-parsed variable value here: variable value may contain  {{ variable_like_token }} text
```

##### ACTUAL RESULTS

The pre task fails to evaluate if the variables are set as the variable string value is being parsed and the sub-string `{{ variable_like_token }}` is interpreted as if it was an ansible variable, which is not defined.

```paste below
TASK [Ensure required variables are set] *********************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ item }} == '' or {{ item }} is none
fatal: [localhost]: FAILED! => {}

MSG:

The conditional check '{{ item }} == '' or {{ item }} is none' failed. The error was: error while evaluating conditional ({{ item }} == '' or {{ item }} is none): 'variable_like_token' is undefined

The error appears to be in '/home/usr/playbooks/_curly_braces_in_var_value.yml': line 6, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  pre_tasks:
  - name: Ensure required variables are set
    ^ here
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jfoliveira** [comment]
Could anyone suggest me any workaround?
I've tried rendering jinja2 template with `lookup('template', ...)`, tried creating a template file, as suggested in https://github.com/ansible/ansible/issues/49648 and defining a custom start/end string token.

Also tried using `!unsafe`, but so far couldn't find a way to both: validate the presence of required variables AND get the variable literal value without any variable substitution.

I appreciate any suggestions.
Thanks!

**Comment by sivel** [comment]
The problem here is that you need to mark that data as unsafe, but it's not easy to do in JSON.  You should instead use an actual YAML file that uses the `!unsafe` tag, and pass that to extra vars:

```yaml
variables: 
  var_1: !unsafe "variable value may contain {{ variable_like_token }} text"
  var_2: !unsafe "another value for {{ variable_2 }}"
```

To do this in JSON would require something like this:

```json
{
    "variables": {
        "var_1": {
            "__ansible_unsafe": "variable value may contain {{ variable_like_token }} text"
        },
        "var_2": {
            "__ansible_unsafe": "another value for {{ variable_2 }}"
        }
    }
}
```

In any case, as recommended, use a YAML file, and then specify it like `--extra-vars @some-file.yaml`

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
