### ISSUE TITLE
lineinfile module: non existing file is not created when using "backrefs"

### ISSUE THREAD

**Issue by wifibox** [ansible/ansible#71828]
##### SUMMARY

lininfile module returns a fatal when trying to work on non existing file with **backrefs: yes**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lineinfile.py

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/wojtosz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### CONFIGURATION

```
DEFAULT_FORKS(/home/wojtosz/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/wojtosz/ansible/ansible.cfg) = ['/home/wojtosz/ansible/hosts']
INTERPRETER_PYTHON(/home/wojtosz/ansible/ansible.cfg) = auto_silent
```

##### OS / ENVIRONMENT

OS: Ubuntu 20.04.1 LTS
Kernel: 5.4.0-47-generic

##### STEPS TO REPRODUCE

Execute task:

```
- name: NRPE check MySQL/MariaDB
  lineinfile:
    path: /etc/nagios/nrpe.d/check_mysql.cfg
    line: command[check_mysql]=/usr/lib/nagios/plugins/check_mysql -u nrpe -p RANDOM_PASS
    state: present
    regexp: '^command(.*)u nrpe(.*)RANDOM_PASS$'
    backrefs: yes
    owner: root
    group: root
    mode: '0644'

```

##### EXPECTED RESULTS

If "path" file **does not** exists, should be created with declared in "line" content.
If "path" file **does exists**, and "RANDOM_PASS" string is replaced by secret, the "path" file should not be changed.

##### ACTUAL RESULTS

File is not created, fatal error:

```paste below
fatal: [devnode]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": true,
            "backup": false,
            "content": null,
            "create": false,
            "delimiter": null,
            "directory_mode": null,
            "firstmatch": false,
            "follow": false,
            "force": null,
            "group": "root",
            "insertafter": null,
            "insertbefore": null,
            "line": "command[check_mysql]=/usr/lib/nagios/plugins/check_mysql -u nrpe -p RANDOM_PASS",
            "mode": "0644",
            "owner": "root",
            "path": "/etc/nagios/nrpe.d/check_mysql.cfg",
            "regexp": "^command(.*)u nrpe(.*)RANDOM_PASS$",
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "Destination /etc/nagios/nrpe.d/check_mysql.cfg does not exist !",
    "rc": 257
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/lineinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/lineinfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wifibox** [comment]
**WORKAROUND:**

to workaround the problem in current state, please create an empty file first making sure that there is none.

```
- name: Check if check_mysql.cfg exists
  stat:
    path: /etc/nagios/nrpe.d/check_mysql.cfg
  register: CheckMysqlCfg

- name: Create empty file /etc/nagios/nrpe.d/check_mysql.cfg
  file:
    path: /etc/nagios/nrpe.d/check_mysql.cfg
    state: touch
  when: CheckMysqlCfg.stat.isreg is not defined
```
and now executing the problematic task will not result a fatal :)
