### ISSUE TITLE
Make it possible to add whole interfaces to zones with firewalld module

### ISSUE THREAD

**Issue by dhilst** [ansible/ansible#71837]
##### SUMMARY
Add interface to a zone using the firewalld module

##### ISSUE TYPE
I would like to be able to do this

```
- name: Add internal interface to trsuted zone in Firewall
  firewalld:
    zone: trusted
    interface:  eth1
    permanent: yes
    state: present
```
But it complains with this error message:
```
fatal: [ansible-test1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "ms
g": "absent and present state can only be used in zone level operations"}
```

If I remove `state: present` I got

```
fatal: [ansible-test1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "ms
g": "missing required arguments: state"}
```

Today I'm using this command to workaround:

```
- name: Add internal interface to trsuted zone in Firewall
  shell: |
    firewall-cmd --permanent --zone=trusted --change-interface=eth1
```

which is far from ideal

##### COMPONENT NAME

firewalld

##### ADDITIONAL INFORMATION

```yaml
- name: Add internal interface to trsuted zone in Firewall
  firewalld:
    zone: trusted
    interface:  eth1
    permanent: yes
    state: present
```
