### ISSUE TITLE
win_environment changes registry key for session path as REG_SZ type instead of expected default REG_EXPAND_SZ type

### ISSUE THREAD

**Issue by epu** [ansible/ansible#71844]
##### SUMMARY
Using win_environment to set machine-scope PATH variable incorrectly mutates the windows registry type of the key (example for machine - HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment:Path) to type REG_SZ. The default type of this key is REG_EXPAND_SZ, and it typically exists already.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_environment

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /Users/epurins/ansible/ansible.cfg
  configured module search path = ['/Users/epurins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/epurins/.local/share/virtualenvs/ansible-xWAiO8b6/lib/python3.6/site-packages/ansible
  executable location = /Users/epurins/.local/share/virtualenvs/ansible-xWAiO8b6/bin/ansible
  python version = 3.6.10 (default, Sep 20 2020, 07:47:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)]
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/Users/epurins/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/Users/epurins/ansible/ansible.cfg) = ['/Users/epurins/ansible/collections/EXTERNAL']
DEFAULT_HOST_LIST(/Users/epurins/ansible/ansible.cfg) = ['/Users/epurins/ansible/inventory/development']
DEFAULT_LOAD_CALLBACK_PLUGINS(/Users/epurins/ansible/ansible.cfg) = True
DEFAULT_MANAGED_STR(/Users/epurins/ansible/ansible.cfg) = This file is managed by infra team
DEFAULT_PRIVATE_KEY_FILE(/Users/epurins/ansible/ansible.cfg) = /Users/epurins/my_key
DEFAULT_ROLES_PATH(/Users/epurins/ansible/ansible.cfg) = ['/Users/epurins/ansible/roles/EXTERNAL', '/Users/epurins/ansible/roles']
DEFAULT_TIMEOUT(/Users/epurins/ansible/ansible.cfg) = 60
INTERPRETER_PYTHON(/Users/epurins/ansible/ansible.cfg) = auto_legacy_silent
RETRY_FILES_ENABLED(/Users/epurins/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Target OS Name: Microsoft Windows 10 Enterprise
ansible_connection: winrm

##### STEPS TO REPRODUCE
Check the value manually, with either the yaml below, or in the registry editor regedit.exe, and then run win_environment to change the value to the original value. Then refresh the regedit.exe view, and observe the new registry key type.

You will need to login manually to inspect the registry again, since PATH controls where powershell is found, and the winrm connector could break, being unable to find a path with percent literals in it.

```yaml
- name: Get current system path string
  win_reg_stat:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
    name: Path
  register: current_system_path

- debug: var=current_system_path

- name: Set an environment variable for all users
  win_environment:
    state: present
    name: PATH
    value: "{{ current_system_path.raw_value }}"
    level: machine
```

##### EXPECTED RESULTS
Expect value edit to preserve the original key type as REG_EXPAND_SZ and change only the value.

Stretch goal: expect new keys created to allow specification of registry key type, similar to win_regedit, where type can be expandstring or string (default).

##### ACTUAL RESULTS
Next command to run breaks, because powershell is no longer on PATH (rather, its PATH is not expanded, so PATH is now wrong).

```
fatal: [my.host.com]: FAILED! => {"changed": false, "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: 'PowerShell' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n", "reboot": false}
```

##### WORKAROUND

never use expanding values, or use win_regedit explicitly instead of win_path and win_environment. drawback is users must figure out their own idempotency solutions.
