### ISSUE TITLE
Loop conditionals not working as expected

### ISSUE THREAD

**Issue by mattthehearn** [ansible/ansible#71943]
##### SUMMARY

I'm attempting to iterate through a list of disks to get some scsi information, but only when the disks' SCSI controller matches a previously set fact.  However, the "when" conditional is not being met, even though the variables being compared match, so the loop doesn't get run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Loop/Conditional

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg
  configured module search path = ['/home/ermhearn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ermhearn/git/ansible-role_linux_oracle/virtual_env/lib64/python3.6/site-packages/ansible
  executable location = /home/ermhearn/git/ansible-role_linux_oracle/virtual_env/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg) = -o ControlMaster=no
DEFAULT_ASK_PASS(/home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg) = False
DEFAULT_FORKS(/home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg) = 5
DEFAULT_VAULT_PASSWORD_FILE(/home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg) = /home/ermhearn/git/ansible-role_linux_oracle
HOST_KEY_CHECKING(/home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg) = False
```

##### OS / ENVIRONMENT

I'm running this on a RHEL7 virtual machine; it is contacting a VMWare vCenter to gather VM and disk information, and then processing the information.  It successfully talks to the vCenter, but then doesn't iterate my loop properly.

##### STEPS TO REPRODUCE

ansible-playbook vmware_add_disk.yml -e "vm_hostname=uloravdbr01b"

My playbook:
```yaml
---
- name: Add that disk
  hosts: localhost

  vars:
    # Each of these can be overwritten with extravars, and the vm_hostname variable *has* to be. Example:
    # ansible-playbook vmware_add_disk.yml -e "vm_hostname=uloravdbr01c disk_size=512"
    #
    vcenter_host: 'vcenter.test.local'
    vcenter_dc: 'US1'
    vcenter_user: 'svcvcenter'
    vcenter_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      3636636133653561326130396435356563633262303037323337a933356533373865666262643232
      3034333163383861383737666331646136376236306262620a34b431626363356461386265363865
      31366533653733643538333265313039353461343136626332314432356362653535323265616663
      3463626161303063350a323232613065373765316635316236382363373135303831363864626466
      3662
    vm_hostname: '"Set this in an extravar.  See vars comment in playbook."'
    disk_size: 128 # In GB

  tasks:

    - name: Get vm_disk_info
      vmware_guest_disk_info:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: false
        name: "{{ vm_hostname }}"
        datacenter: "{{ vcenter_dc }}"
      delegate_to: localhost
      register: vm_disk_info

    - name: Set disk_controller
      set_fact:
        disk_controller: "{{ vm_disk_info.guest_disk_info['0'].controller_key }}"

    - name: Show disk_controller
      debug:
        msg: "{{ disk_controller }}"

    - name: Check contents of disk_info
      debug:
        msg: "item: {{ item }} controller_key: {{ vm_disk_info.guest_disk_info[item].controller_key }} disk_controller: {{ disk_controller }}"
      loop: "{{ vm_disk_info.guest_disk_info.keys() }}"

    - name: Set disk_max_unitnumber
      set_fact:
        disk_max_unitnumber: "{{ vm_disk_info.guest_disk_info[item].unit_number }}"
      loop: "{{ vm_disk_info.guest_disk_info.keys() }}"
      when: vm_disk_info.guest_disk_info[item].controller_bus_number == disk_controller

    - name: Show disk_max_unitnumber
      debug:
        msg: "{{ disk_max_unitnumber }}"
```

##### EXPECTED RESULTS

I expect it to parse the list of disks, comparing to make sure the SCSI controller key matches, and if so, updating the "disk_max_unitnumber".

##### ACTUAL RESULTS

It fails to run the loop because the when conditional does not match.

```paste below
ansible-playbook 2.10.1
  config file = /home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg
  configured module search path = ['/home/ermhearn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ermhearn/git/ansible-role_linux_oracle/virtual_env/lib64/python3.6/site-packages/ansible
  executable location = /home/ermhearn/git/ansible-role_linux_oracle/virtual_env/bin/ansible-playbook
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] Using /home/ermhearn/git/ansible-role_linux_oracle/ansible.cfg as config file setting up inventory plugins host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method Skipping due to inventory source not existing or not being readable by the current user script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method Skipping due to inventory source not existing or not being readable by the current user yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method Skipping due to inventory source not existing or not being readable by the current user ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method Skipping due to inventory source not existing or not being readable by the current user toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
redirecting (type: modules) ansible.builtin.vmware_guest_disk_info to community.vmware.vmware_guest_disk_info
Loading collection community.vmware from /home/ermhearn/.ansible/collections/ansible_collections/community/vmware
Loading callback plugin default of type stdout, v2.0 from /home/ermhearn/git/ansible-role_linux_oracle/virtual_env/lib64/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: vmware_add_disk-github.yml *******************************************
Positional arguments: vmware_add_disk-github.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
extra_vars: ('vm_hostname=uloravdbr01b',)
forks: 5
1 plays in vmware_add_disk-github.yml

PLAY [Add that disk] ***********************************************************

TASK [Gathering Facts] *********************************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ermhearn <127.0.0.1> EXEC /bin/sh -c 'echo ~ermhearn && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ermhearn/.ansible/tmp `"&& mkdir "` echo /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887 `" && echo ansible-tmp-1601045531.6248553-2028871-106830487104887="` echo /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887 `" ) && sleep 0'
Using module file /home/ermhearn/git/ansible-role_linux_oracle/virtual_env/lib64/python3.6/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/ermhearn/.ansible/tmp/ansible-local-20288528083lhwr/tmp04azoz6m TO /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887/ /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/ermhearn/git/ansible-role_linux_oracle/virtual_env/bin/python3 /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ermhearn/.ansible/tmp/ansible-tmp-1601045531.6248553-2028871-106830487104887/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Get vm_disk_info] ********************************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:24
Trying secret FileVaultSecret(filename='/home/ermhearn/git/ansible-role_linux_oracle/test/.vault_pass') for vault_id=default <localhost> ESTABLISH LOCAL CONNECTION FOR USER: ermhearn <localhost> EXEC /bin/sh -c 'echo ~ermhearn && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ermhearn/.ansible/tmp `"&& mkdir "` echo /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255 `" && echo ansible-tmp-1601045538.6515584-2029354-267624924107255="` echo /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.vmware_guest_disk_info to community.vmware.vmware_guest_disk_info
Using module file /home/ermhearn/.ansible/collections/ansible_collections/community/vmware/plugins/modules/vmware_guest_disk_info.py
<localhost> PUT /home/ermhearn/.ansible/tmp/ansible-local-20288528083lhwr/tmpiims_q_r TO /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255/AnsiballZ_vmware_guest_disk_info.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255/ /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255/AnsiballZ_vmware_guest_disk_info.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/ermhearn/git/ansible-role_linux_oracle/virtual_env/bin/python3 /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255/AnsiballZ_vmware_guest_disk_info.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ermhearn/.ansible/tmp/ansible-tmp-1601045538.6515584-2029354-267624924107255/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "guest_disk_info": {
        "0": {
            "backing_datastore": "vms01",
            "backing_disk_mode": "persistent",
            "backing_diskmode": "persistent",
            "backing_eagerlyscrub": false,
            "backing_filename": "[vms01] uloravdbr01b/uloravdbr01b.vmdk",
            "backing_thinprovisioned": true,
            "backing_type": "FlatVer2",
            "backing_uuid": "6000C29e-e940-4b88-bda5-8c3b8063d66c",
            "backing_writethrough": false,
            "capacity_in_bytes": 42949672960,
            "capacity_in_kb": 41943040,
            "controller_bus_number": 0,
            "controller_key": 1000,
            "controller_type": "lsilogic",
            "key": 2000,
            "label": "Hard disk 1",
            "summary": "41,943,040 KB",
            "unit_number": 0
        },
        "1": {
            "backing_datastore": "vms01",
            "backing_disk_mode": "persistent",
            "backing_diskmode": "persistent",
            "backing_eagerlyscrub": false,
            "backing_filename": "[vms01] uloravdbr01b/uloravdbr01b_1.vmdk",
            "backing_thinprovisioned": true,
            "backing_type": "FlatVer2",
            "backing_uuid": "6000C299-f6fb-3d3c-3763-930807383b64",
            "backing_writethrough": false,
            "capacity_in_bytes": 137438953472,
            "capacity_in_kb": 134217728,
            "controller_bus_number": 0,
            "controller_key": 1000,
            "controller_type": "lsilogic",
            "key": 2001,
            "label": "Hard disk 2",
            "summary": "134,217,728 KB",
            "unit_number": 1
        }
    },
    "invocation": {
        "module_args": {
            "datacenter": "US1",
            "folder": null,
            "hostname": "vcenter.test.local",
            "moid": null,
            "name": "uloravdbr01b",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "use_instance_uuid": false,
            "username": "svcvcenter",
            "uuid": null,
            "validate_certs": false
        }
    }
}

TASK [Set disk_controller] *****************************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:35
ok: [localhost] => {
    "ansible_facts": {
        "disk_controller": "1000"
    },
    "changed": false
}

TASK [Show disk_controller] ****************************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:39
ok: [localhost] => {
    "msg": "1000"
}

TASK [Check contents of disk_info] *********************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:43
ok: [localhost] => (item=0) => {
    "msg": "item: 0 controller_key: 1000 disk_controller: 1000"
}
ok: [localhost] => (item=1) => {
    "msg": "item: 1 controller_key: 1000 disk_controller: 1000"
}

TASK [Set disk_max_unitnumber] *************************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:48
skipping: [localhost] => (item=0)  => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "0",
    "skip_reason": "Conditional result was False"
}
skipping: [localhost] => (item=1)  => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "1",
    "skip_reason": "Conditional result was False"
}

TASK [Show disk_max_unitnumber] ************************************************
task path: /home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml:54
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'disk_max_unitnumber' is undefined\n\nThe error appears to be in '/home/ermhearn/git/ansible-role_linux_oracle/vmware_add_disk-github.yml': line 54, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Show disk_max_unitnumber\n      ^ here\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
```
