### ISSUE TITLE
Template Module does not report line number on failure

### ISSUE THREAD

**Issue by DCAuto** [ansible/ansible#71978]
##### SUMMARY
Using the "template" module, upon failure, the error does not report the line number of the error in the template.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template module

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'jsnapy']
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/inventory/DCS_INVENTORY.py']
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(/etc/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/module_utils']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy
DEFAULT_TERMINAL_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/terminal']
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/.info
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
MAX_FILE_SIZE_FOR_DIFF(/etc/ansible/ansible.cfg) = 0

```

##### OS / ENVIRONMENT

NAME="CentOS Linux"
VERSION="7 (Core)"

##### STEPS TO REPRODUCE

```yaml
- set_facts:
    test_var:
	  description: 'dont_select_me'

- template:
      src: "TEMPLATE.j2"
      dest: "{{ inventory_hostname }}.conf"
      trim_blocks: yes
      lstrip_blocks: yes



TEMPLATE.j2
---------------------

SOMETHING
{{ (test_var | selectattr('description', 'match', 'select_me') | list | first) }};
SOMETHING
SOMETHING
   
```

##### EXPECTED RESULTS

Error showing that on LINE-2 in the template, 'No first item, sequence was empty'

##### ACTUAL RESULTS

No template line numbers are reported. only:
'No first item, sequence was empty'

```paste below

```
