### ISSUE TITLE
docker_container does not revoke published_ports if image has port set as exposed

### ISSUE THREAD

**Issue by husjon** [ansible/ansible#71974]
##### SUMMARY

When a Docker image has been created with the `EXPOSE` keyword in the Dockerfile, when a container is created publishing this port, `docker_container` is unable to remove this port at a later stage.

It seem like `docker_container` treats the following 2 container setups the same:
* Published:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
b24845764792        nginx               "/docker-entrypoint.…"   4 seconds ago       Up 3 seconds        0.0.0.0:80->80/tcp   nginx
```
* Exposed, but not published:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
e08d50b17a5a        nginx               "/docker-entrypoint.…"   9 seconds ago       Up 8 seconds        80/tcp              nginx
```

The latter is the expected result after running the example playbook below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/husjon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
Linux workstation 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

The following playbook example can reproduce this issue.

```yaml
---
- name: deploy nginx
  hosts: localhost

  tasks:
    - name: deploy container with published ports
      docker_container:
        name: nginx
        image: nginx:latest

        published_ports: [ "80:80" ]

    - name: deploy container without published ports (revokal)"
      docker_container:
        name: nginx
        image: nginx:latest

        comparisons:
          '*': strict

        published_ports: []
```

##### EXPECTED RESULTS

The published ports should be removed.

##### ACTUAL RESULTS

The published ports remains as they where initially from the first task.
Docker output after first task has run:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
b24845764792        nginx               "/docker-entrypoint.…"   4 seconds ago       Up 3 seconds        0.0.0.0:80->80/tcp   nginx
```
Docker output after second task has run:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
b24845764792        nginx               "/docker-entrypoint.…"   9 seconds ago       Up 8seconds        0.0.0.0:80->80/tcp   nginx
```

Added as gist, since the output is about 1200 lines.
https://gist.github.com/husjon/ae88c6e8a94b9aea4b4bb7633d5c135f
