### ISSUE TITLE
[file] state: link sets mode on src not on dest

### ISSUE THREAD

**Issue by wookietreiber** [ansible/ansible#71976]
##### SUMMARY
The `file` module, when used with `state: link` and `mode`, applies the mode to the source, not the destination.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Sep  5 2020, 10:50:12) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Arch Linux

##### STEPS TO REPRODUCE

```yaml
---

- name: test
  hosts: localhost
  connection: local

  tasks:

    - name: create tmp file
      copy:
        dest: /tmp/link-source
        content: ''
        mode: 0644

    - name: create link to tmp file
      file:
        src: /tmp/link-source
        dest: /tmp/link-dest
        state: link
        mode: 0700

    - name: stat tmp source
      stat:
        path: /tmp/link-source
      register: stat_source

    - name: stat tmp dest
      stat:
        path: /tmp/link-dest
      register: stat_dest

    - debug: var='{{ item }}'
      loop:
        - stat_source.stat.mode
        - stat_dest.stat.mode

...
```

##### EXPECTED RESULTS

I expected the link destination to have the specified mode and the source file to be *unmodified*. Source files should *never* be modified with `file`. 

##### ACTUAL RESULTS

```paste below
PLAY [test] ***********************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [create tmp file] ************************************************************************************************
changed: [localhost]

TASK [create link to tmp file] ****************************************************************************************
changed: [localhost]

TASK [stat tmp source] ************************************************************************************************
ok: [localhost]

TASK [stat tmp dest] **************************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************************
ok: [localhost] => (item=stat_source.stat.mode) => {
    "ansible_loop_var": "item",
    "item": "stat_source.stat.mode",
    "stat_source.stat.mode": "0700"
}
ok: [localhost] => (item=stat_dest.stat.mode) => {
    "ansible_loop_var": "item",
    "item": "stat_dest.stat.mode",
    "stat_dest.stat.mode": "0777"
}

PLAY RECAP ************************************************************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
