### ISSUE TITLE
Unexpected conversion to set

### ISSUE THREAD

**Issue by mattdowdell** [ansible/ansible#71981]
##### SUMMARY

I have a custom module stored in the library for a module. The module is called by a task which operates on an array as follows:

```yaml
- name: configure replication policies
  harbor_replication:
    hostname: "{{ harbor_hostname }}"
    username: admin
    password: "{{ harbor_admin_password }}"
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    mode: "{{ item.mode }}"
    source_registry: "{{ item.source_registry | default(None) }}"
    filter_name: "{{ item.filter_name | default('') }}"
    filter_tag: "{{ item.filter_tag | default('') }}"
    filter_labels: "{{ item.filter_labels | default([]) }}"
    filter_resource: "{{ item.filter_resource | default('all') }}"
    destination_registry: "{{ item.destination_registry | default(None) }}"
    destination_namespace: "{{ item.destination_namespace | default('') }}"
    trigger_type: "{{ item.trigger_type }}"
    trigger_cron: "{{ item.trigger_cron | default('') }}"
    delete_on_remote: "{{ item.delete_on_remote | default(False) }}"
    override: "{{ item.override | default(False) }}"
    enabled: "{{ item.enabled | default(True) }}"
  loop: "{{ harbor_replications }}"
  loop_control:
    label: "{{ item.name }}"
```

This is generally fine. However, I hit an error when I get to a specific element in the array:

```
  - name: docker-hub-alpine
    description:
    mode: pull
    source_registry: docker-hub
    filter_name: library/alpine
    filter_tag: '{3.10,3.12}'
    trigger_type: scheduled
    trigger_cron: 0 0 0 * * *
    overwrite: yes
```

The error reported is:

```
Unable to pass options to module, they must be JSON serializable: Object of type set is not JSON serializable
```

After a bit of digging, I found the issue is caused by `filter_tag: '{3.10,3.12}'` which somehow becomes a set. However, this only happens if numeric values are used. Something like `filter_tag: '{3.6-slim,3.7-slim,3.8-slim}'` does not present this issue.

I'm at a loss how to debug this. I can see ansible depends on pyyaml, so I did some basic testing:

```python
>>> import yaml
>>> yaml.safe_load("name: '{1.0,2.0}'")
{'name': '{1.0,2.0}'}
```

No obvious issue there, but perhaps a different loader is being used?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Pretty sure this is from ansible core.

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = None
  configured module search path = ['/Users/dowdellm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dowdellm/repos/ansible-playbooks/bristol-lab/.venv/lib/python3.7/site-packages/ansible
  executable location = /Users/dowdellm/repos/ansible-playbooks/bristol-lab/.venv/bin/ansible
  python version = 3.7.3 (default, Apr 24 2020, 18:51:23) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### CONFIGURATION

```paste below
```

(no changes)

##### OS / ENVIRONMENT

```
$ uname -a
Darwin mbp-dowdellm.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

This is my laptop - the module is executed on localhost as it targets an HTTP API.

##### STEPS TO REPRODUCE

see above

```yaml

```

##### EXPECTED RESULTS

I expect to string to be passed through unmodified without being converted to a set.

##### ACTUAL RESULTS

Error when running a specific iteration of a task.

```paste below
ansible-playbook -i inventory playbook.yml --ask-vault-pass
```

I tried with increased verbosity and got nothing useful back.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mattdowdell** [comment]
Dug a bit more and I think this is an interaction between jinja2 and pyyaml. I found that avoiding the loop and calling the module as follows throws no error:

```
- name: configure replication policies
  harbor_replication:
    hostname: "{{ harbor_hostname }}"
    username: admin
    password: "{{ harbor_admin_password }}"
    name: docker-hub-alpine
    mode: pull
    source_registry: docker-hub
    filter_name: library/alpine
    filter_tag: '{3.10,3.12}'
    trigger_type: scheduled
    trigger_cron: 0 0 0 * * *
    override: yes
```

It's unclear exactly what jinja2 is expanding to, and I can't get pyyaml to give me a set no matter what I throw at it. Not quite sure how to workaround the issue even with this knowledge.

**Comment by mattdowdell** [comment]
Got a minimal test case for failure

```yaml
- name: test
  hosts: all
  gather_facts: no
  vars:
    example: '{1.1,1.2}'
  tasks:
    - debug:
        msg: "{{ example }}"
```

And another for success:

```yaml
- name: test
  hosts: all
  gather_facts: no
  vars:
    example: '{1.1,1.2-a}'
  tasks:
    - debug:
        msg: "{{ example }}"
```

The error is a bit different this time but the deserialisation to a set is still evident:

```
[WARNING]: Failure using method (v2_runner_on_ok) in callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x1081b5160>): Object of type set is not JSON serializable
```

**Comment by mkrizek** [comment]
The reason why this happens is due to how we interact with Jinja2. Jinja2 always returns strings but we try to convert values that look like Python data structures into actual data structures using our `safe_eval` function. Since `'{1.1,1.2}'` looks like a `set` it is converted as such. To work around this, you need to explicitly convert that value to a string like so:

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    example: '{1.1,1.2}'
  tasks:
    - debug:
        msg: "{{ example | string }}"
```
