### ISSUE TITLE
aws_s3 encryption_mode "aws:kms" is not working

### ISSUE THREAD

**Issue by sagar89jadhav** [ansible/ansible#72002]
Hi,

I am trying to apply default encrytion as "aws:kms" to s3 bucket which was created earlier however, I am getting below error;

```
fatal: [localhost]: FAILED! => {
    "msg": "Could not find imported module support code for aws_s3.  Looked for either HAS_MD5.py or s3.py"
}
```

##### COMPONENT NAME
`aws_s3` module 

##### ANSIBLE VERSION

```
2.6.2
``` 

##### CONFIGURATION
```
  - name: Create S3 bucket
    aws_s3:
      bucket: "{{aws_environment}}-mybucket"
      mode: create
      encrypt: yes
      encryption_kms_key_id: "arn:aws:kms:{{aws_environment}}:{{project_name}}:key/{{kmskey}}"
      encryption_mode: aws:kms
      region: "{{aws_region}}"

```

##### OS / ENVIRONMENT
CircleCI docker container linux based.

##### STEPS TO REPRODUCE
Use ansible version lower than 2.7. Currently `2.6.2` is getting used in my project.

##### EXPECTED RESULTS
AWS s3 bucket default encryption should get enabled with an encryption as `aws:kms`.

##### ACTUAL RESULTS
Bucket is getting created but default encryption is remained as "None" in aws console. In short, changes are not getting reflected. 
I have downloaded and added `aws_s3.py` ansible libraries of ansible versions (2.7/2.8) in my project under `ansible/library` but encryption changes are not getting applied.
