### ISSUE TITLE
Pleaese reconsider deprecating hash_behaviour

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#72021]
##### SUMMARY

Pleaese reconsider deprecating hash_behaviour

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

core

##### ADDITIONAL INFORMATION

There are use cases revolving around iterating over dicts and deduplication. Packing role parameters neatly into dicts, storing dozens of objects in dicts with ability to add or remove arbitrary objects on any group or host level.

So, for example, a role that manages user accounts, feeded by a dict of users

```yaml
# a dict containing dozens of users
accounts:
  bob:
    uid: 1000
    state: present
    # lots of attributes
  fred:
    uid: 1001
    # lots of attributes
  # lots of other users
```
Currently the role can enrich this dict with defaults and take in any adjustments on any level of inventory hierarchy as simple as:
```yaml
# group_vars/some_country_or_dc_or_isp_or_room_or_moon_phase_group
accounts:
  fred:
    state: absent
```
How would that be possible without hash merging? Provision a separate dict for every level of hierarchy and merge them all manually inside a role effectively duplicating inventory group structure?

Using prefixed variables for roles instead of dicts, or copypasting an entire dict to make a single change, or, again, provision a dict for every hierarchy level to be merged? This will add a lot of clutter.

Will `set_fact: { parameters: { subparameters: { option1: yes } } }` nuke an entire `parameters` dict?
