### ISSUE TITLE
Invalid fstab entry for relative paths

### ISSUE THREAD

**Issue by hubchub** [ansible/ansible#72039]
##### SUMMARY

If you specity a relative path for path using [mount](https://docs.ansible.com/ansible/2.3/mount_module.html) it will create an entry in /etc/fstab using that relative path but it requires an absolute path. This causes the auto-mount to fail on reboot.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mount
##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = None
  configured module search path = [u'/Users/hubchub/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

##### CONFIGURATION

```paste below


```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

mount a drive into your home directory using a relative path

```yaml
  - name: Mount GlusterFS
      mount:
        state: mounted
        src: 'localhost:/volume'
        path: storage-pool
        fstype: glusterfs
```

##### EXPECTED RESULTS

entry in fstab like:
localhost:/volume /home/USERNAME/storage-pool glusterfs defaults 0 0

OR

Prohibiting relative paths

##### ACTUAL RESULTS

localhost:/volume storage-pool glusterfs defaults 0 0

```paste below

```
