### ISSUE TITLE
Unable to chain simple arithmatic across nested variables, undesired casting to str

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#72044]
##### SUMMARY

I'm trying to do the following with Jinja in my playbooks:

```
x = 5 * 60
y = x - 60
```
I expect y to be (5*60)-60 == 240

But it doesn't work. There's some type conversion that happens which shouldn't.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Jinja templating

##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /home/ec2-user/.ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/env/local/lib/python3.6/dist-packages/ansible
  executable location = /home/ec2-user/env/bin/ansible
  python version = 3.6.12 (default, Aug 31 2020, 18:56:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/ec2-user/.ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/ec2-user/.ansible.cfg) = /dev/shm/ansible/tmp_local/ans
```

##### OS / ENVIRONMENT

Amazon Linux, Ansible installed via pip.

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  vars:
    x: "{{ 5 * 60 | int }}"
  tasks:
  - assert:
      that: 
      - y == 240
    vars:
      y: "{{ x - 60 }}"
```

##### EXPECTED RESULTS

The playbook should succeed.

##### ACTUAL RESULTS

> fatal: [localhost]: FAILED! => {"msg": "The conditional check 'y == 240' failed. The error was: An unhandled exception occurred while templating '{{ x - 60 }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ x - 60 }}): unsupported operand type(s) for -: 'str' and 'int'"}

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is expected behavior. Jinja2, due to its initial use case, has been designed to always return strings. So the result of `"{{ 5 * 60 | int }}"` will be a string, the casting to `int` is preserved only within the expression.

There are two possible solutions:

1. explicitly cast variables when used like so:
```yaml
- hosts: localhost
  gather_facts: no
  vars:
    x: "{{ 5 * 60 | int }}"
  tasks:
  - assert:
      that:
      - y | int == 240
    vars:
      y: "{{ x | int - 60 }}"
```
2. use [native jinja](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native) that was designed exactly for what you are describing, then your example will work as is.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
