### ISSUE TITLE
list_vms state=paused is broken

### ISSUE THREAD

**Issue by p3ck** [ansible/ansible#72059]
##### SUMMARY
It's not possible to list vm's that are in a paused state with the virt module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

virt

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/dci-openshift-agent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 8.2.2004 (Core) 

##### STEPS TO REPRODUCE

```yaml
---
- name: IPI debug
  hosts: provisioner
  tasks:
    - name: Get list of all running VMs
      virt:
        command: list_vms
        state: running
      register: running_vms
      become: yes
      tags: cleanup

    - name: Get list of all paused VMs
      virt:
        command: list_vms
        state: paused
      register: paused_vms
      become: yes
      tags: cleanup

    - name: Destroy old bootstrap VMs, if any
      debug:
        var: item
      with_items: "{{ running_vms.list_vms + paused_vms.list_vms}}"
      when: item is search("bootstrap")
      tags: cleanup

```

##### EXPECTED RESULTS

I should get a list of VM's that are paused.

```paste below
fatal: [provisionhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command": "list_vms",
            "state": "paused",
            "uri": "qemu:///system"
        }
    },
    "msg": "value of state must be one of: destroyed, pause, running, shutdown, got: paused"
}

```
