### ISSUE TITLE
vsphere_guest: add option for virtualHW.version

### ISSUE THREAD

**Issue by hbokh** [ansible/ansible#7206]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.6 (devel 5c39206014) last updated 2014/04/29 10:40:13 (GMT +200)
##### Environment:

Ansible 1.6 on Ubuntu 13.04, against VMware ESXi 5.5 standalone / free
##### Summary:

With Ansible 1.6 I can create and destroy new VMware VM's with vsphere_guest, however on ESXi 5.5 (standalone) a new VM is always "VM Version: vmx-10" (in the .vmx-file: virtualHW.version = "10").
These VM's are not manageble with vSphere Client, only through vCenter Web and as such useless for folks with the ESXi standalone free version.  
I've been trying to alter the module with something like

```
config.set_element_hwVersion(vm_hardware['hwversion'])
```

to get the VM-version to  "8", but with no success. 
##### Steps To Reproduce:

Create a new VM with vsphere_guest
##### Expected Results:

It would be great to have an option like this:

```
 vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd: yes
          virtualHW.version: 8
          notes: A test VM, made with Ansible
```
##### Actual Results:

A new VMware VM is always "VM Version: vmx-10" (in the .vmx-file: virtualHW.version = "10")
