### ISSUE TITLE
Ansible win_updates keeps filtering update cause of 'Category_Names'

### ISSUE THREAD

**Issue by rudesome** [ansible/ansible#72076]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION
```
AWX 13.0.0
```

##### CONFIGURATION
```
-
```

##### OS / ENVIRONMENT
Windows Server

##### STEPS TO REPRODUCE
```yaml
 - name: Windows Updates
      win_updates:
        state: searched
        category_name: 
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - Updates
          - Update Rollups
          - Windows Server 2016
          - Windows Server 2019
          - Definition Updates
          - Microsoft Defender Antivirus
      register: result
```

##### EXPECTED RESULTS

**Not** filtering the updates by 'category names' specified in the playbook

##### ACTUAL RESULTS
Example of result after running the playbook specified above:
```
            "filtered_reason": "category_names",
            "title": "Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.325.20.0)",
            "categories": [
                "Definition Updates",
                "Microsoft Defender Antivirus"
            ],
            "kb": [
                "2267602"
            ],
            "installed": false
        }
```
