### ISSUE TITLE
Ansible 2.10 azure.azcollection ansible_python_interpreter

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#72079]
##### SUMMARY

I am testing ansible 2.10 with collections and not sure about the details regarding ansible_python_interpreter issues. 

```
pip3 uninstall ansible
pip3 install ansible
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine_info

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /home/nbm/Projects/ansible-dce/ansible.cfg
  configured module search path = ['/home/nbm/Projects/ansible-dce/Modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Apr 19 2020, 20:18:17) [GCC 9.2.1 20191008]
```

##### STEPS TO REPRODUCE

```yaml
ansible-galaxy collection install azure.azcollection
```

```
- hosts: localhost
  gather_facts: no
  collections: 
    - azure.azcollection
    - community.azure
  tasks:
  - name: "get virtual machine facts by tag {{ tag }}"
     azure_rm_virtualmachine_info:
      tenant: '{{ tenant }}'
      client_id: '{{ client_id }}'
      secret: '{{ secret }}'
      subscription_id: '{{ subscription_id }}'
      tags:
      - type:{{ tag }}
    register: virtualmachine_facts
    delegate_to: localhost
```

##### ACTUAL RESULTS

```paste below
Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on enterprise's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```
