### ISSUE TITLE
"digital_ocean_tag_info" module produces "KeyError: 'tag'" error message

### ISSUE THREAD

**Issue by PC-Admin** [ansible/ansible#72091]
##### SUMMARY
"digital_ocean_tag_info" module produces "KeyError: 'tag'" error message instead of returning information about digitial ocean tags.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
digital_ocean_tag_info

##### ANSIBLE VERSION
2.9.10 (AWX 13.0.0)

##### OS / ENVIRONMENT
AWX 13.0.0 Container.

##### STEPS TO REPRODUCE
Tag a droplet and try and lookup the tag. (See code below)

```yaml
- name:
  set_fact:
    matrix_domain_stripped: "{{ matrix_domain | regex_replace('[^a-z0-9A-Z]', '') }}"

- debug:
    msg: "{{ matrix_domain_stripped }}"

- name: Tag a resource; creating the tag if it does not exist
  delegate_to: 127.0.0.1
  digital_ocean_tag:
    oauth_token: '{{ do_api_token }}'
    name: "{{ item }}"
    resource_id: "{{ new_server_info.data.droplet.id }}"
    state: present
  loop:
    - "{{ matrix_domain_stripped }}"
    - client

- name: Gather information about tag with given name
  delegate_to: 127.0.0.1
  digital_ocean_tag_info:
    oauth_token: '{{ do_api_token }}'
    tag_name: '{{ matrix_domain_stripped }}'
  register: tag_info
```

##### EXPECTED RESULTS
I would expect to see a list of droplets with this tag.

##### ACTUAL RESULTS
Produces this error:

```
"Traceback (most recent call last):
File \"/tmp/ansible_digital_ocean_tag_info_payload_q_ou4uvi/ansible_digital_ocean_tag_info_payload.zip/ansible/modules/cloud/digital_ocean/digital_ocean_tag_info.py\", line 114, in main
File \"/tmp/ansible_digital_ocean_tag_info_payload_q_ou4uvi/ansible_digital_ocean_tag_info_payload.zip/ansible/modules/cloud/digital_ocean/digital_ocean_tag_info.py\", line 97, in core
KeyError: 'tag'"
```
