### ISSUE TITLE
Finer grain control of ec2 dynamic inventory cache invalidation

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#7209]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.5.5
##### Environment:

N/A
##### Summary:

Allow user to control when ec2 inventory cache gets invalidated within a playbook
##### Steps To Reproduce:

Add some way to specify that an event has occurred that requires the ec2 inventory cache to be updated.

```
- local_action:
    module: ec2
    instance_ids: '{{ instance_ids }}'
    state: running
    wait: yes
 invalidate_ec2_cache: yes
```
##### Expected Results:

Ansible will update the ec2 cache after the task with `invalidate_ec2_cache: yes` fires
##### Actual Results:

N/A
##### Rationale

If we start stopped instances at the beginning of a playbook, we need to invalidate the cache, otherwise the dynamic inventory won't contain the started instances. We can turn off caching entirely, but this will slow down the whole playbook.

**Comment by pas256** [comment]
Keep in mind the async nature of doing this. Just because the EC2 API call returns to say the instance is running, doesn't mean it is through the launch process enough to have an IP address or through the boot process to have SSH working causing subsequent tasks to fail.

**Comment by lorin** [comment]
I'm not so worried about the ssh issue, can just wait for ssh to come up using wait_for and pause, e.g.:

```
- local_action:
    module: ec2
    instance_ids: '{{ instance_ids }}'
    state: running
    wait: yes
  invalidate_ec2_cache: yes
- local_action: wait_for host={{ inventory_hostname }} port=22 state=started
- pause: seconds=5
```

But is it true that EC2 instance can transition to the running state before being assigned a valid IP address? I've never encountered this. Do you have a link that describes this behavior?
