### ISSUE TITLE
Ansible can't send Template files to server - Error AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by hamidreza-hosseini** [ansible/ansible#72103]
SUMMARY

Can't run roles with template module and shows error

Hi,
I'm using Ansible 2.9.6, When I want to run a role with ansible-playbook , it do tasks one by one but when it receive in template module and want to send files to server it shows bellow error:
```

fatal: [192.168.1.52]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: No first item, sequence was empty."}

```
I ran it with verbosity:

```
TASK [netdata-mysql : Ensure netdata's mysql plugin config file is installed] *****************************************************************************************************************************
task path: /home/test/netdata-mysql/tasks/main.yml:3
Monday 05 October 2020  14:21:59 +0330 (0:00:06.455)       0:00:12.151 ******** 
<192.168.1.52> ESTABLISH SSH CONNECTION FOR USER: test
<192.168.1.52> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.1.52> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
<192.168.1.52> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.1.52> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="test")
<192.168.1.52> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.1.52> SSH: PlayContext set ssh_common_args: ()
<192.168.1.52> SSH: PlayContext set ssh_extra_args: ()
<192.168.1.52> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/test/.ansible/cp/a93eca5a85)
<192.168.1.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="test"' -o ConnectTimeout=10 -o ControlPath=/home/test/.ansible/cp/a93eca5a85 192.168.1.52 '/bin/sh -c '"'"'echo ~test && sleep 0'"'"''
<192.168.1.52> (0, b'/home/test\n', b'OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.1.52 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16287\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<192.168.1.52> ESTABLISH SSH CONNECTION FOR USER: test
<192.168.1.52> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.1.52> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
<192.168.1.52> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.1.52> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="test")
<192.168.1.52> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.1.52> SSH: PlayContext set ssh_common_args: ()
<192.168.1.52> SSH: PlayContext set ssh_extra_args: ()
<192.168.1.52> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/test/.ansible/cp/a93eca5a85)
<192.168.1.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="test"' -o ConnectTimeout=10 -o ControlPath=/home/test/.ansible/cp/a93eca5a85 192.168.1.52 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/test/.ansible/tmp/ansible-tmp-1601895119.1232512-226784410348979 `" && echo ansible-tmp-1601895119.1232512-226784410348979="` echo /home/test/.ansible/tmp/ansible-tmp-1601895119.1232512-226784410348979 `" ) && sleep 0'"'"''
<192.168.1.52> (0, b'ansible-tmp-1601895119.1232512-226784410348979=/home/test/.ansible/tmp/ansible-tmp-1601895119.1232512-226784410348979\n', b'OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.1.52 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16287\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
looking for "netdata-mysql.conf" at "/home/test/netdata-mysql/templates/netdata-mysql.conf"
<192.168.1.52> ESTABLISH SSH CONNECTION FOR USER: test
<192.168.1.52> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<192.168.1.52> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
<192.168.1.52> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<192.168.1.52> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="test")
<192.168.1.52> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<192.168.1.52> SSH: PlayContext set ssh_common_args: ()
<192.168.1.52> SSH: PlayContext set ssh_extra_args: ()
<192.168.1.52> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/home/test/.ansible/cp/a93eca5a85)
<192.168.1.52> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="test"' -o ConnectTimeout=10 -o ControlPath=/home/test/.ansible/cp/a93eca5a85 192.168.1.52 '/bin/sh -c '"'"'rm -f -r /home/test/.ansible/tmp/ansible-tmp-1601895119.1232512-226784410348979/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.1.52> (0, b'', b'OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 192.168.1.52 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16287\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
fatal: [192.168.1.52]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: No first item, sequence was empty."
}

```
This is my task:

```

- name: Ensure netdata's mysql plugin config file is installed
  template:
    src: netdata.conf
    dest: /opt/netdata/etc/netdata/netdata.conf

```

I check all variables , I adjust them all in a accurate way, even I test this module with no variable and I set values directly.

What should I do for this problem?

ISSUE TYPE

    `Bug Report`

ANSIBLE VERSION
    `ansible --version

ansible 2.9.6
  config file = /home/test/Documents/playbooks/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]`

COMPONENT NAME

`Module template`

OS / ENVIRONMENT
`
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04

`
CONFIGURATION

STEPS TO REPRODUCE
`
write ansible role and playbook
run ansible-playbook
`
EXPECTED RESULTS
`
copy files that are in template directory into server and change variables with suitable content

`
ACTUAL RESULTS
`

Ansible failed to run role and showed following error:

fatal: [192.168.200.18]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: No first item, sequence was empty."
}

`

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@kaaaq: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Sharing your variables and the template would help diagnose what's happening. It appears you have a variable that's an empty, and you're trying to use the first item in the list in the template. This is working as expected. For example:

template_src.j2:
```
{{ mylist | first }}
```
```
---
- hosts: localhost
  gather_facts: no
  tasks:
  - template:
      src: template_src.j2
      dest: /tmp/template_dest.j2
    vars:
      # works:
      mylist: ['hasitem']
      # fails as expected because there is no first item
      #mylist: []
```

If you have further user questions we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

**Comment by kaaaq** [comment]
Thanks for your answer,
But I remove all variables and then I set the variables directly with right values and still I've this problem
this is my task:
```
---

- name: Ensure mysql packages are available on remote host
  copy:
    src:  "{{item}}"
    dest: /root
  loop:
    ### order of installation matters. do not change it
    - mysql-common_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-client-core_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-client_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-client_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-server-core_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-server_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-server_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-shell_8.0.15-1ubuntu16.04_amd64.deb

- name: Ensure mysql packages are installed in order
  apt:
    deb: /root/{{ item }}
    state: present
  loop:
    ### order of installation matters. do not change it
    - mysql-common_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-client-core_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-client_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-client_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-server-core_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-community-server_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-server_8.0.15-1ubuntu16.04_amd64.deb
    - mysql-shell_8.0.15-1ubuntu16.04_amd64.deb

- name: Ensure python mysql driver is installed (ansible needs it)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-mysqldb
  # - python3-pymysql
  # apt-get install python-pymysql


- name: Ensure mysqld.conf config file is installed
  template:
    src: "{{ item }}"
    #dest: /etc/mysql/mysql.conf.d
    dest: "/etc/mysql/mysql.conf.d/{{ item }}"
  loop:
    - mysqld.cnf
  notify:
    - Restart mysql service

```

My template file:

```

[client]
# user = admin
# password = 

[mysqld]
#bind-address = {{ ansible_all_ipv4_addresses | ipaddr('192.168.1.0/24') | first }}
bind-address = 192.168.200.18
pid-file       = /var/run/mysqld/mysqld.pid
socket         = /var/run/mysqld/mysqld.sock
datadir        = {{datadir}}
log-error      = /var/log/mysql/error.log
default_authentication_plugin = mysql_native_password
```
My vars in default file:

```
datadir: /var/lib/mysql

```

Best regards.
