### ISSUE TITLE
Feature like no_log that only shows or obscures a part of the return values

### ISSUE THREAD

**Issue by DaVince** [ansible/ansible#72104]
##### SUMMARY
A feature that behaves similar to no_log, but only displays the return values that you define, would be desirable.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/executor/task_result.py

##### ADDITIONAL INFORMATION

`no_log` obscures **all** returned output. I understand this is a good way to obscure, for example, a password that is laid bare in a module's invocation. But sometimes you *do* still want to get certain output that helps you understand what went wrong.

I propose the addition of two new flags: `only_log_values` and `no_log_values`. Feel free to think of better names.
* With only_log_values, you define a list of the *only* return values that should be shown in the output.
* With no_log_values, you define a list of the return values that should be hidden in the output.

Examples:

```yaml
- name: only log stderr output from command
  command:
    cmd: something
  only_log_values:
    - rc
    - stderr_lines

- name: log everything except the gid and uid of the copied file
  copy:
    src: somefile
    dest: /path/to/dest
  no_log_values:
    - gid
    - uid
```
The parameters accepted come from the possible return values of the module. When return values that don't exist are used, Ansible should output a warning.
