### ISSUE TITLE
Become with multiple users (more than two) doesn't work

### ISSUE THREAD

**Issue by daniele338** [ansible/ansible#72100]
##### SUMMARY
Impossible to use multiple users within the same playbook

##### ISSUE TYPE
In my playbook I enter as a non root user (test). Immediately after the login via ssh I use become to change from test to root. To do so I pass the password via cli with --ask-become-pass and I setted become in the setup.yml file.
```
- hosts: "{{ target }}"
  become: yes
  become_method: su
```
`ansible-playbook playbooks/setup.yml --ask-pass  --ask-become-pass --extra-vars `"target=server"``

At some point I have a task that must be executed as apache user, but it says incorrect sudo password or incorrect su password. I tried to set become_method: su and become_method: sudo. 
Below the task. 

```
- name: Check if maintenance install is present
  shell: php occ | grep maintenance 
  become: yes
  become_user: apache
  args:
    chdir: "{{path_installation}}nextcloud/"
  register: maintenance_install

```
I also tried to set a var ansible_become_password inside the task itself.

```
- name: Check if maintenance install is present
  shell: php occ | grep maintenance 
  become: yes
  become_user: apache
  #become_method: sudo
  args:
    chdir: "{{path_installation}}nextcloud/"
  register: maintenance_install
  vars:
    ansible_become_password: root_password

``` 
I am sure that I am missing something, if it isn't in the correct category let me know and I will change it.

##### COMPONENT NAME

Module become 

##### ANSIBLE VERSION

`
ansible 2.9.13
`

##### CONFIGURATION

`
DEFAULT_HOST_LIST(/home/daniele/Documents/work/ansible_service_server/ansible.cfg) = ['/home/daniele/Documents/work/ansible_service_server/hosts']`

##### OS / ENVIRONMENT

```
Target OS hosted on digital ocean
Centos 7.6 x64 
```

##### STEPS TO REPRODUCE

1. Create a user without root privileges;
2. Disable root access via ssh;
3. Inside the playbook enable the become to change from user to root;
4. Run a task that require to be executed as another users, like www-data

##### EXPECTED RESULTS
I expect to change from root to apache user and to execute the task

##### ACTUAL RESULTS

```
Escalation failed
fatal: [xxx.yyy.xxx.zzz]: FAILED! => {
    "msg": "Incorrect su password"
}
```
