### ISSUE TITLE
Refresh_inventory meta within block/always 

### ISSUE THREAD

**Issue by eocsx** [ansible/ansible#72116]
##### SUMMARY
Hi guys,

I'm having some issues getting a more complex workflow to work. In short, I have 3 roles, role A, B and C. I need to run role A and role C on localhost, role B on some remote, target hosts. After role A and before Role B I need to refresh inventory (I have a custom inventory plugin). Role C is a cleanup role which needs to be executed no matter what. My current playbook looks like:

```
 hosts: all
  tasks:
    - name: Role A
      block:
        - name: Do A
          include_role:
            name: roleA
            apply:
              delegate_to:
                localhost
        - name: Refresh Inventory
          meta: refresh_inventory
        - name: Do remote Role B
          include_role:
            name: roleB
      always:
        - name: Clean up
          include_role: 
            name: roleC
```
The problem that I am having is that the meta action is breaking the workflow, the inventory gets refreshed and the playbook execution ends there (no more role B, not even the role in always block being executed anymore).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Meta actions - refresh_inventory
Custom Inventory plugin
Block/always/rescue

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /home/xplay/ansible.cfg
  configured module search path = ['/home/xplay/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xplay/venvs/pg_1/lib64/python3.6/site-packages/ansible
  executable location = /home/xplay/venvs/pg_1/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/xplay/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=120
DEFAULT_FORKS(/home/xplay/ansible.cfg) = 25
DEFAULT_HOST_LIST(/home/xplay/ansible.cfg) = ['/home/xplay/inventories/default/hosts']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/xplay/ansible.cfg) = ['/home/xplay/inventory_plugins']
DEFAULT_ROLES_PATH(/home/xplay/ansible.cfg) = ['/home/xplay/roles']
HOST_KEY_CHECKING(/home/xplay/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/xplay/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Centos 7

##### STEPS TO REPRODUCE

Run playbook from above.
Role A - creates a file '/tmp/bla' on localhost with the name of a remote host
Role B - debug -> echo {{ inventory_hostname }}, it should run against the remote host specified in the above mentioned file
Role C - delete /tmp/bla file on localhost

```
 hosts: all
  tasks:
    - name: Role A
      block:
        - name: Do A
          include_role:
            name: roleA
            apply:
              delegate_to:
                localhost
        - name: Refresh Inventory
          meta: refresh_inventory
        - name: Do remote Role B
          include_role:
            name: roleB
      always:
        - name: Clean up
          include_role: 
            name: roleC
```

##### EXPECTED RESULTS

Role C should always run, no matter if something fails in role A or B along the way.

##### ACTUAL RESULTS

setting up inventory plugins
host_list declined parsing /home/xplay/ct_postgres_plugin.yaml as it did not pass its verify_file() method
script declined parsing /home/xplay/ct_postgres_plugin.yaml as it did not pass its verify_file() method
Debug - localhost
[WARNING]: Skipping additional_groups key as ADDITIONAL_GROUPS envvar is not assigned
[WARNING]: Skipping datacenter key as DC envvar is not assigned
Adding rz0 group to inventory
Setting ansible_group_priority 20 for rz0 group
Adding dev group to inventory
Setting ansible_group_priority 10 for dev group
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Adding node_rz0 group to inventory
Adding master group to inventory
Setting ansible_group_priority 30 for master group
Adding node_rz0 group to inventory
Adding nodes group to inventory
Adding rz2 group to inventory
Setting ansible_group_priority 20 for rz2 group
Adding dev group to inventory
Setting ansible_group_priority 10 for dev group
Adding node_rz2 group to inventory
Adding master group to inventory
Setting ansible_group_priority 30 for master group
Adding node_rz2 group to inventory
Adding nodes group to inventory
Adding rz3 group to inventory
Setting ansible_group_priority 20 for rz3 group
Adding dev group to inventory
Setting ansible_group_priority 10 for dev group
Adding node_rz3 group to inventory
Adding master group to inventory
Setting ansible_group_priority 30 for master group
Adding node_rz3 group to inventory
Adding nodes group to inventory
Parsed /home/xplay/ct_postgres_plugin.yaml inventory source with auto plugin
META: inventory successfully refreshed

PLAY RECAP ******************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```paste below

```
