### ISSUE TITLE
unsupported parameters for panos_security_rule

### ISSUE THREAD

**Issue by bkwin66** [ansible/ansible#72123]
##### SUMMARY
get unsupported params for panos_security_rule module: disabled, log_setting, vsys

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

set vsys, disabled, and log_setting flags on the panos_security_rule module
##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /ansible/SCT-Shares/home/brian.windle@ad.local/ansible_master/network/palo_alto/palo_alto_policy_scrape/ansible.cfg
  configured module search path = ['/ansible/SCT-Shares/library']
  ansible python module location = /ansible/SCT-Shares/paloalto_env/lib64/python3.6/site-packages/ansible
  executable location = /ansible/SCT-Shares/paloalto_env/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ACTION_WARNINGS(default) = True
AGNOSTIC_BECOME_PROMPT(default) = True
ALLOW_WORLD_READABLE_TMPFILES(default) = False
ANSIBLE_CONNECTION_PATH(default) = None
ANSIBLE_COW_PATH(default) = None
ANSIBLE_COW_SELECTION(default) = default
ANSIBLE_COW_WHITELIST(default) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake', 'elephant', 'eyes', 'hellokitty', 'kitty', 'l
ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
ANSIBLE_SSH_ARGS(default) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(default) = None
ANSIBLE_SSH_CONTROL_PATH_DIR(default) = ~/.ansible/cp
ANSIBLE_SSH_EXECUTABLE(default) = ssh
ANSIBLE_SSH_RETRIES(default) = 0
ANY_ERRORS_FATAL(default) = False
BECOME_ALLOW_SAME_USER(default) = False
BECOME_PLUGIN_PATH(default) = ['/home/brian.windle@ad.local/.ansible/plugins/become', '/usr/share/ansible/plugins/become']
CACHE_PLUGIN(default) = memory
CACHE_PLUGIN_CONNECTION(default) = None
CACHE_PLUGIN_PREFIX(default) = ansible_facts
CACHE_PLUGIN_TIMEOUT(default) = 86400
COLLECTIONS_PATHS(default) = ['/home/brian.windle@ad.local/.ansible/collections', '/usr/share/ansible/collections']
COLOR_CHANGED(default) = yellow
COLOR_CONSOLE_PROMPT(default) = white
COLOR_DEBUG(default) = dark gray
COLOR_DEPRECATE(default) = purple
COLOR_DIFF_ADD(default) = green
COLOR_DIFF_LINES(default) = cyan
COLOR_DIFF_REMOVE(default) = red
COLOR_ERROR(default) = red
COLOR_HIGHLIGHT(default) = white
COLOR_OK(default) = green
COLOR_SKIP(default) = cyan
COLOR_UNREACHABLE(default) = bright red
```

##### OS / ENVIRONMENT

panos 8.1.13
##### STEPS TO REPRODUCE

```yaml
- name: Update Security rule - disable
  panos_security_rule:
    ip_address: "{{ item.0 }}"
    password: "{{ ADMPASS }}"
    username: "{{ ADMUSER }}"
    rule_name: "{{ item.1 }}"
    destination_zone: "{{ item.2 }}"
    destination_ip: "{{ item.3 }}"
    source_zone: "{{ item.4 }}"
    source_ip: "{{ item.5 }}"
    service: "{{ item.6 }}"
    description: "{{ item.7 }}"
    log_setting: "{{ item.8 }}"
    action: "{{ item.9 }}"
    application: "{{ item.10 }}"
    category: "{{ item.11 }}"
    disabled: "{{ item.12 }}"
    log_end: "{{ item.13 }}"
    log_start: "{{ item.14 }}"
    rule_type: "{{ item.15 }}"
    source_user: "{{ item.16 }}"
    url_filtering: "{{ item.17 }}"
    vsys: "{{ item.18 }}"
```

##### ACTUAL RESULTS

```paste below
        "module_args": {
            "action": "allow",
            "application": [
                "any"
            ],
            "category": [
                "any"
            ],
            "description": "Legacy LCSRA rule = Inherited via merger 04/2018",
            "destination_ip": [
                "ibm_sftp",
                "TSTBTC1APP714"
            ],
            "destination_zone": [
                "td-rif_egr"
            ],
            "disabled": "",
            "ip_address": "10.61.212.181",
            "log_end": "",
            "log_setting": "Bossier 1 to NEST-SEC",
            "log_start": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "rule_name": "ibm_sftp_updates",
            "rule_type": "interzone",
            "service": [
                "service-https"
            ],
            "source_ip": [
                "ibm_sftp",
                "TSTBTC1APP714"
            ],
            "source_user": [
                "any"
            ],
            "source_zone": [
                "td-egress"
            ],
            "url_filtering": "",
            "username": "admin",
            "vsys": "vsys21"
        }
    },
    "item": [
        "10.61.212.181",
        "ibm_sftp_updates",
        "['td-rif_egr']",
        "['ibm_sftp', 'TSTBTC1APP714']",
        "['td-egress']",
        "['ibm_sftp', 'TSTBTC1APP714']",
        "['service-https']",
        "Legacy LCSRA rule = Inherited via merger 04/2018",
        "Bossier 1 to NEST-SEC",
        "allow",
        "['any']",
        "['any']",
        null,
        null,
        "True",
        "interzone",
        "['any']",
        null,
        "vsys21"
    ],
    "msg": "Unsupported parameters for (panos_security_rule) module: disabled, log_setting, vsys Supported parameters include: action, antivirus, api_key, application, category, commit, data_filtering, description, destination_ip, destination_zone, devicegroup, file_blocking, group_profile, hip_profiles, ip_address, log_end, log_start, ope
```
