### ISSUE TITLE
winrm - delegate_to does not work without explicitly specifying ansible connection vars.

### ISSUE THREAD

**Issue by sg1970** [ansible/ansible#72148]
##### SUMMARY
Iam trying to target 2 Windows Servers using winrm and delegate a task to the 2nd Windows server from the 1st Windows Server  (  both servers are identically configured and on the same subdomain using the same user id ) in the same inventory group. kerberos works fine if connection creds are explicitly specified in the playbook.

it appears that winrm expects the connection password to be explicitly provided in the playbook for delegation purposes using vars even though the same user/password is used to gather facts which works fine. 

what this implies is that i have to maintain the same password in 2 places: in AWX and playbook which doesnt seem right. 

Error I get :
**fatal: [my_host_1.mydomain.com]: UNREACHABLE! => {"changed": false, "msg": "kerberos: authGSSClientInit() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), (\"Can't find client principal my_user@MYDOMAIN.COM in cache collection\", -1765328243))", "unreachable": true}**

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
winrm

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/my_user/ansible/ansible-examples/ansible.cfg
  configured module search path = ['/home/my_user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.8 (default, Jun 29 2020, 05:46:05) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Target OS = Win Server 2016

##### STEPS TO REPRODUCE

```yaml

Command: 
$ ansible-playbook -i inventory/test.ini winrm.yml -u my_user@MYDOMAIN.COM --ask-pass
SSH password:

--- ini file test.ini:----


[all:vars]

[web]
my_host_1.mydomain.com 
my_host_2.mydomain.com 

--- group_vars/all/main.yml ----
ansible_ssh_password: "{{ansible_password}}"
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: kerberos
ansible_winrm_kerberos_delegation: true


--- playbook winrm.yml ----
- hosts: all 
  gather_facts: true    ## This works !!!
  vars:
      ansible_user: "my_user"
      # ansible_password: "my_supersecret_password"  ## Once this is un-commented the Playbook will work as expected
      ansible_port: 5985
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore
      ansible_winrm_transport: kerberos
      ansible_winrm_kerberos_delegation: true  

   tasks: 

          - name: Display output
            debug:
              msg:
                - "ansible_password: {{ansible_ssh_password}}"  ## This works which means it knows the password but just wont use it!
                - "ansible_ssh_user: {{ ansible_user}}"
                - "ansible_ssh_password: {{ansible_password}}" ## This works too which means it knows the password but just wont use it!


          - name: get hostname
            win_command: hostname
            register: host
            ignore_errors: false
            delegate_to: my_host_2.mydomain.com    ## This is where it fails with the kerberos error "cant find client principal in cache collection"

            
          - name: Get whoami
            win_command: whoami
            register: who
            ignore_errors: false
            delegate_to: my_host_2.mydomain.com

          - name: Display output
            debug:
              msg:
                - "Running on: {{ host.stdout  | to_nice_yaml}}"
                - "Running As: {{ who.stdout  | to_nice_yaml}}"
                - "ansible_user: {{ ansible_user}}"
                - "ansible_password: {{ansible_password}}"

```

##### EXPECTED RESULTS
TASK [get hostname] ***********************************************************************************************************************************************************************************************
changed: [my_host_1.mydomain.com -> my_host_2.mydomain.com]

TASK [Get whoami] *************************************************************************************************************************************************************************************************
changed: [my_host_1.mydomain.com -> my_host_2.mydomain.com]]

##### ACTUAL RESULTS

```paste below
TASK [get hostname] ***********************************************************************************************************************************************************************************************
fatal: [my_host_1.mydomain.com]: UNREACHABLE! => {"changed": false, "msg": "kerberos: authGSSClientInit() failed: (('Unspecified GSS failure.  Minor code may provide more information', 851968), (\"Can't find client principal my_user@MYDOMAIN.COM in cache collection\", -1765328243))", "unreachable": true}

```
