### ISSUE TITLE
AnsibleFilterError: ' ' is not a valid IP address/network  when upgrading from 2.9.13 to latest

### ISSUE THREAD

**Issue by furkatgofurov7** [ansible/ansible#72161]
##### SUMMARY
It seems, some network variables are not processed properly in case of empty string is defaulted to true (`default(' ', true)`) when upgrading to version 2.10.1. In my opinion, the problem is related when it is the case with how Ansible is templating and/or filtering the condition:

`- when: networks|selectattr('virtualport_type', 'defined')|map(attribute='name')|list|length > 0`

We tried to find out information about changes in the release notes but we couldn't find anything.

We really appreciate your help.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible tasks

##### ANSIBLE VERSION

Ansible is installed with: `sudo pip3 install ansible`
```
ansible --version
ansible 2.10.1
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### OS / ENVIRONMENT

Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE

1. Clone [this repo](https://github.com/furkatgofurov7/metal3-dev-env.git)
2. Edit `ubuntu_install_requirements.sh` script to install latest version of ansible instead of specific version(2.9.13)
3. `export IMAGE_OS=Ubuntu` and `export CAPM3_VERSION=v1alpha4`
4. Run `make`

**tasks/network_setup_tasks.yml**
```
# If virtualport_type is defined for any networks, include OVS dependencies
- when: networks|selectattr('virtualport_type', 'defined')|map(attribute='name')|list|length > 0
  block:

  # Install OVS dependencies
  - name: Install OVS dependencies
    include_role:
      name: 'ovs'

  # Create any OVS Bridges that have been defined
  - name: Create OVS Bridges
    openvswitch_bridge:
      bridge: "{{ item.bridge }}"
      state: present
    when: item.virtualport_type is defined and item.virtualport_type == "openvswitch"
    with_items: "{{ networks }}"
    become: true

```

**tasks/main.yml**
```
- name: libvirt role setup tasks
  block:
    - include_tasks: install_setup_tasks.yml
    - include_tasks: network_setup_tasks.yml
    - include_tasks: vm_setup_tasks.yml
      when: vm_platform == "libvirt"
  when: libvirt_action == "setup"

- name: libvirt role teardown tasks
  block:
    - include_tasks: network_teardown_tasks.yml
    - include_tasks: vm_teardown_tasks.yml
      when: vm_platform == "libvirt"
  when: libvirt_action == "teardown"

```

**common/defaults/main.yml**
[gist link for ip variable](https://gist.github.com/furkatgofurov7/e8f95d27306967e3f6c42d8ffdfb4a98)

##### EXPECTED RESULTS
To be able to deploy metal3 successfully with the latest version of Ansible

##### ACTUAL RESULTS

```
TASK [Install OVS dependencies] ************************************************
�[1;30mtask path: /home/****/tested_repo/vm-setup/roles/libvirt/tasks/network_setup_tasks.yml:6�[0m
�[0;31mfatal: [localhost]: FAILED! => {�[0m
�[0;31m    "msg": "The conditional check 'networks|selectattr('virtualport_type', 'defined')|map(attribute='name')|list|length > 0' failed. The error was: An unhandled exception occurred while templating '[{'name': 'provisioning', 'bridge': 'provisioning', 'forward_mode': 'bridge'}, {'name': 'baremetal', 'bridge': 'baremetal', 'forward_mode': \"{% if manage_baremetal == 'y' %}nat{% else %}bridge{% endif %}\", 'address_v4': \"{{ baremetal_network_cidr_v4|nthhost(1)|default('', true) }}\", 'netmask_v4': \"{{ baremetal_network_cidr_v4|ipaddr('netmask') }}\", 'dhcp_range_v4': ['{{ baremetal_network_cidr_v4|nthhost(20) }}', '{{ baremetal_network_cidr_v4|nthhost(60) }}'], 'address_v6': \"{{ baremetal_network_cidr_v6|nthhost(1)|default('', true) }}\", 'prefix_v6': \"{{ baremetal_network_cidr_v6|ipaddr('prefix') }}\", 'dhcp_range_v6': ['{{ baremetal_network_cidr_v6|nthhost(20) }}', '{{ baremetal_network_cidr_v6|nthhost(60) }}'], 'nat_port_range': [1024, 65535], 'domain': '{{ cluster_domain }}', 'dns': {'hosts': '{{dns_extrahosts | default([])}}', 'forwarders': [{'domain': 'apps.{{ cluster_domain }}', 'addr': '{% if baremetal_network_cidr_v4|ipv4 != False %}127.0.0.1{% else %}::1{% endif %}'}], 'srvs': '{{dns_externalsrvs | default([])}}'}}]'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: '' is not a valid IP address or network\n\nThe error appears to be in '/home/****/tested_repo/vm-setup/roles/libvirt/tasks/network_setup_tasks.yml': line 6, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # Install OVS dependencies\n  - name: Install OVS dependencies\n    ^ here\n"�[0m

```
