### ISSUE TITLE
Allow to pass options such as UID_MIN/MAX or GID_MIN/MAX to the user & group module

### ISSUE THREAD

**Issue by mchouque** [ansible/ansible#72183]
##### SUMMARY
Because the useradd algorithm on Linux is designed to _"The default is to use the smallest ID value greater than or equal to UID_MIN and greater than every other user"_, sometimes it can be useful to change the lower and upper bounds without editing /etc/login.defs.

groupadd uses the same algorithm. 

Without this feature, you have to edit /etc/login.defs before using the user or group module if you want to get sane automatically assigned UID or GID.

##### ISSUE TYPE
- Feature Idea
Given there's a an [issue](https://github.com/ansible/ansible/issues/40359) and associated [PR](https://github.com/ansible/ansible/pull/71469#issuecomment-706397231) to add support to the -K UMASK option, I'd like to to propose the same kind of mechanism.

Namely options such as:
- uid_min
- uid_max
- gid_min
- gid_max

And maybe their sys_ counterparts.

##### COMPONENT NAME

user
group

##### ANSIBLE VERSION
ansible 2.10.0
##### ADDITIONAL INFORMATION

```yaml
- name: Add an user
  user:
    name: foo
    uid_max: 2000
    gid_max: 2000
```
```yaml
- name: Add a group
  user:
    name: bar
    gid_max: 2000
```
