### ISSUE TITLE
Lookup returns a generator object instead of a string on reading a vault encrypted variable.

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#72196]
##### SUMMARY
Lookup returns a "<generator object _wrap_sequence.<locals>.<genexpr> at 0x628dc0253f90>" instead of a string when doing a lookup on a variable that is a vault string.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ANSIBLE.BUILTIN.VARS

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /home/user/Documents/repositories/ansible/managed/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/home/user/Documents/repositories/ansible/managed/ansible.cfg) = ['/home/user/Document>
DEFAULT_VAULT_PASSWORD_FILE(/home/user/Documents/repositories/ansible/managed/ansible.cfg) = /home/user/>
```

##### OS / ENVIRONMENT
OS: Arch Linux x86_64 
Kernel: 5.8.14.a-1-hardened 
Shell: bash 5.0.18 
Terminal: gnome-terminal 
CPU: Intel i5-8350U (8) @ 3.600GHz 
GPU: Intel UHD Graphics 620 
Memory: 3615MiB / 15865MiB 

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: yes
  vars:
    # this is "xyzzy" encrypted with password "123"
    bacula_enc_key_myhostname: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33633238633637336566636539366236326239363330306264333063316337336230316436336131
          3365363739396538633030326461356532336265353932340a376562333731353439653433343034
          65386330636263313239616633333937373663623538343137363363663234353334366535316131
          3865313733366639610a323637653331353164666261356534316330656639386632336234316430
          3462

  tasks:
    - debug: msg="{{ lookup('vars', 'bacula_enc_key_'+ansible_hostname) }}"
    - copy:
        content: "{{ lookup('vars', 'bacula_enc_key_'+ansible_hostname) }}"
        dest: /tmp/example.txt
```

##### EXPECTED RESULTS
```paste below
PLAY [localhost] ****************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************************
ok: [localhost] => {
    "msg": "xyzzy"
}

PLAY RECAP **********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

##### ACTUAL RESULTS
```paste below
PLAY [localhost] ****************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************************
ok: [localhost] => {
    "msg": "<generator object _wrap_sequence.<locals>.<genexpr> at 0x62888c1c9f90>"
}

TASK [copy] *********************************************************************************************************
changed: [localhost]

PLAY RECAP **********************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```
