### ISSUE TITLE
Unable to migrate storage and host using vmware_vmotion when VM on local datastore

### ISSUE THREAD

**Issue by theo-basty** [ansible/ansible#72209]
##### SUMMARY
I am unable to perform both Storage vMotion and host vMotion on VM stored on a local datastore.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.vmware.vmware_vmotion

##### ANSIBLE VERSION
```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
Empty
```

##### OS / ENVIRONMENT

target: vCenter 6.7

##### STEPS TO REPRODUCE

* Create a VM on an ESXi (Host-A) on a local datastore (DS-A)
* Execute the following task to move the VM on an other ESXi (Host-B) with another datastore (DS-B)

```yaml
   - name: "Moving '{{ VM_Name }}'"
     community.vmware.vmware_vmotion:
       hostname: '{{ vcenter_host }}'
       username: '{{ vcenter_user }}'
       password: '{{ vcenter_pass }}'
       validate_certs: False

       vm_name: '{{ VM_Name }}'
       destination_host: Host-B
       destination_datastore : DS-B
     register: vmotion_facts

```

##### EXPECTED RESULTS
The VM should move to DS-B and be affected to Host-B as it would do when the task is done through vCenter

##### ACTUAL RESULTS
The moudle seems to try to migrate the storage using the destination host wich does not have access to the VM

```paste below
{
    "msg": "('Unable to access the virtual machine configuration: Unable to access file [DS-A] test-export/test-export.vmx', None)",
    "invocation": {
        "module_args": {
            "hostname": "VCENTER",
            "username": "USER",
            "password": "PASSWORD",
            "validate_certs": false,
            "vm_name": "test-export",
            "destination_host": "Host-B",
            "destination_datastore": "DS-B",
            "port": 443,
            "use_instance_uuid": false,
            "proxy_host": null,
            "proxy_port": null,
            "vm_uuid": null,
            "moid": null,
            "destination_resourcepool": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}
```
