### ISSUE TITLE
ansible-galaxy role install fails when using file://

### ISSUE THREAD

**Issue by paulkitt** [ansible/ansible#72217]
##### SUMMARY
When using `src: file://path_to_local_role_repo` as mentioned in the [docs](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file) `ansible-galaxy fails with `[ERROR]: failed to download the file: <urlopen error [Errno 21] Is a directory: '/home/paul/Documents/git_repos/ansible-roles-git/ansible-role-plik'>`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ansible-galaxy install`

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/paul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION
```
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/paul/Documents/git_repos/ansible-dezim/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/home/paul/Documents/git_repos/ansible-roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /home/paul/Documents/git_repos/ansible-dezim/vault_pass.sh
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT
Ubuntu 20.04
Ansible is installed via pip

##### STEPS TO REPRODUCE
```
ansible-galaxy install -r requirements.yml                           
Starting galaxy role install process
- common_server_init (master) is already installed, skipping.
[WARNING]: - jnv.unattended-upgrades (v1.8.0) is already installed - use --force to change version to unspecified
- chasinglogic.podman (master) is already installed, skipping.
- triplepoint.dnsmasq is already installed, skipping.
- downloading role from file:///home/paul/Documents/git_repos/ansible-roles-git/ansible-role-plik
 [ERROR]: failed to download the file: <urlopen error [Errno 21] Is a directory: '/home/paul/Documents/git_repos/ansible-roles-git/ansible-role-plik'>
[WARNING]: - ansible-role-plik was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
The requirements.yml
```
---
roles:
  - name: common_server_init
    src: git+git@gitlab.com:coderatCollectiveCoding/ansible-role-common-server-init.git
    version: master
  - name: jnv.unattended-upgrades
  - name: chasinglogic.podman
  - name: triplepoint.dnsmasq
    src: git+https://github.com/coderat-collective/ansible-dnsmasq.git
  - name: plik
    src: file:///home/paul/Documents/git_repos/ansible-roles-git/ansible-role-plik
```

##### EXPECTED RESULTS
The locally cloned repo is used and no download is started.

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/galaxy`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
I don't think that's ever worked, so we should fix that example in the documentation. Specify the SCM for that one too:
```
roles:
  - name: newname
    src: file:///path/to/repo
    scm: git
```
You can also provide src as `git+file://...` like you've done for the others.
