### ISSUE TITLE
Template component: custom Jinja2 variables strings with nested Ansible variables does not work

### ISSUE THREAD

**Issue by midmarch** [ansible/ansible#72234]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template component

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

OS: Fedora release 32 (Thirty Two)

##### STEPS TO REPRODUCE

Playbook:
```yaml
- name: Custom Jinja2 variables strings with nested Ansible variables
  hosts:
    - some_hosts

  vars:
    name: 'Melvin'
    message: 'Hello {{name}}'

  tasks:
    - name: 'Use nested variable in template'
      template:
        src: template.j2
        # Use template variables like: ${my_var}
        variable_start_string: '${'
        variable_end_string: '}'
        dest: '~/result.txt'
        mode: u=rw,g=r,o=r
```

template:
```
${message}
```

##### EXPECTED RESULTS

It should not effect Ansible variable declaration

```bash
cat ~/result.txt
```
should output:

```paste below
Hello Melvin
```

##### ACTUAL RESULTS

```bash
cat ~/result.txt
```

outputs:

It prints out the Ansible code, instead of the Ansible result:
```paste below
Hello {{name}}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
You have not provided the content of `template.j2`. From "Actual Results" I can only assume the `template.j2` file contains:

```
${ message }
```

Since you instructed the template module to use non-default `variable_start_string`/`variable_end_string`:
```yaml
variable_start_string: '${'
variable_end_string: '}'
```

you need to change the `message` variable to
```yaml
message: 'Hello ${ name }'
```

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by midmarch** [comment]
@mkrizek, the template I used was indeed:

```j2
${ message }
```

Changing the playbook to  `message: 'Hello ${ name }'` does the trick, but does not make sense to me. 

I changed the template variable declaration, and not the Ansible declaration I hope. This does not make any sense and not in line with the description. 

What if I want to use `message` elsewhere?

**Comment by mkrizek** [comment]
Variables in Ansible are evaluated lazily - evaluation is postponed until the variable is needed. In your case that means that the template that the template modules processes is effectively:
```
${ Hello {{name}} }
```

and not

```
${ Hello Melvin }
```

because the evaluation of the `message` variable is postponed.

I am not sure what are you trying to achieve but you can "work around" the above by using a fact instead of a variable like so:

```yaml
- hosts: localhost
  gather_facts: no
  vars:
    name: 'Melvin'
  tasks:
    - set_fact:
        message: 'Hello {{ name }}'                                                                                                                          
    - template:
        src: 72234.j2
        # Use template variables like: ${my_var}
        variable_start_string: '${'
        variable_end_string: '}'
        dest: '~/result.txt'
        mode: u=rw,g=r,o=r
```

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
