### ISSUE TITLE
Handle remote templates files in the template task

### ISSUE THREAD

**Issue by lerminou** [ansible/ansible#72231]
##### SUMMARY

Actually, there is no "remote_src" options for a template task.
In our company, the templates are managed by the projects and not by ansible.
I need extra stuff to handle it correctly (with some noise for handlers for examples)

Is it possible to integrate this feature
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

template:
      remote_src: yes
##### ADDITIONAL INFORMATION

Actually I do this way to handle it
```yaml
# tasks/template_remote_file.yml


- name: "fetch {{input_template_file | basename}} from remote host"
  run_once: "{{ run_once | default(true) }}"
  fetch:
    src: "{{input_template_file}}"
    dest: "/tmp/file_{{ run_once | default(true) | ternary('', inventory_hostname) }}_{{ansible_date_time.epoch}}.json" # prefix file by hostname if run_once if false
    flat: yes
    fail_on_missing: yes
  register: local_template_cfg

- name: "configure {{input_template_file | basename}} template "
  template:
    src: "{{local_template_cfg.dest}}"
    dest: "{{output_template_file}}"
    mode: "{{ file_permissions | default(0644) }}"
    owner: "{{ file_owner | default('root') }}"
    group: "{{ file_group | default('root') }}"
  notify: "{{ handlers | default(omit) }}"

- name: remove local template file
  file:
    path: "{{local_template_cfg.dest}}"
    state: absent
  delegate_to: 127.0.0.1
  become: false
  run_once: "{{ run_once | default(true) }}"

# in my role
- import_tasks: template_remote_file.yml
  vars:
    input_template_file: "/etc/deploy/back_asp.conf.j2"
    output_template_file: "/etc/nginx/conf.d/back_aspnetcore_payment.conf"
    file_owner: nginx
    file_group: nginx
    handlers: restart nginx
```
