### ISSUE TITLE
vmware_deploy_ovf module sometimes give <urlopen error Tunnel connection failed: 503 Service Unavailable>"

### ISSUE THREAD

**Issue by koteswara-kelam** [ansible/ansible#72233]
##### SUMMARY

vmware_deploy_ovf module sometimes give <urlopen error Tunnel connection failed: 503 Service Unavailable>"

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: raise URLError(err)
[WARNING]: Problem validating OVF import spec: The specified operating system identifier '' (id: 107) is not supported on the selected host. It will be mapped to the following OS identifier: 'Other Linux (64-bit)'.
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "<urlopen error Tunnel connection failed: 503 Service Unavailable>"}

I am using centos-8 and ansible 2.9.9

$ cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)

$ ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vmware_deploy_ovf 
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
]$ ansible-config dump --only-changed
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

$ cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: Deploy virtual machine {{ vm_name }}
  vmware_deploy_ovf:
    hostname: "{{ ip }}"
    username: "{{ admin_username }}"
    password: "{{ admin_password }}"
    cluster: "{{ cluster_name }}"
    datacenter: "{{ datacenterName }}"
    datastore: "{{ vm_datastore }}"
    folder: "{{ datacenterName }}/vm"
    name: "{{ vm_name }}"
    disk_provisioning: "thin"
    networks: { "bridged": "{{ vmnetwork_name }}" }
    ovf: "{{ image_ova_path }}"
    allow_duplicates: false
    power_on: "{{ power_on }}"
    validate_certs: false
    fail_on_spec_warnings: false
    wait_for_ip_address: false
    wait: true
  delegate_to: localhost
```

##### EXPECTED RESULTS

vm should get deployed without errors.
##### ACTUAL RESULTS

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: raise URLError(err)
[WARNING]: Problem validating OVF import spec: The specified operating system identifier '' (id: 107) is not supported on the selected host. It will be mapped to the following OS identifier: 'Other Linux (64-bit)'.
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "<urlopen error Tunnel connection failed: 503 Service Unavailable>"}

```paste below

```
