### ISSUE TITLE
Strange evaluation behavior of host variables

### ISSUE THREAD

**Issue by dmrub** [ansible/ansible#72242]
##### SUMMARY

I'm not one hundred percent sure that this is a bug, but I haven't found a description of this behavior in the documentation.
If I want to get the value of the host variable in a task running on a localhost and if this variable refers to other variables via templating, I have to evaluate it in the context of the host it is defined for before I use it on the localhost.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hostvars
##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/home/rubinste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/lib/python3.7/site-packages/ansible
  executable location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/bin/ansible
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora release 31 (Thirty One)

##### STEPS TO REPRODUCE

Create inventory file `inventory.yml` with the following content:
```yaml
---
all:
  children:
    my_group:
      hosts:
        my_host_1:
          ansible_ssh_common_args: '{{ hostvars[node_ref].ansible_ssh_common_args | default(omit) }}'
        my_host_2:
          ansible_ssh_common_args: >-
            -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null
            -o StrictHostKeyChecking=no -W %h:%p user@example.org -p 2222
            -i my_id_rsa '
      vars:
        node_ref: my_host_2
```

Create playbook `test-playbook-1.yml`:
```yaml
#- hosts: all
#  gather_facts: false
#  tasks:
#
#    - name: Force evaluation of used host variables
#      set_fact:
#        ansible_ssh_common_args: "{{ ansible_ssh_common_args | default(omit) }}"

- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    target: ['my_host_1']
  tasks:

    - name: Print vars
      debug:
        var: hostvars[item]['ansible_ssh_common_args']
      loop: "{{ target }}"

```

Create playbook  `test-playbook-2.yml`:
```yaml
#- hosts: all
#  gather_facts: false
#  tasks:
#
#    - name: Force evaluation of used host variables
#      set_fact:
#        ansible_ssh_common_args: "{{ ansible_ssh_common_args | default(omit) }}"

- hosts: all
  gather_facts: false
  vars:
    target: ['my_host_1']
  tasks:

    - name: Print vars
      local_action:
        module: debug
        var: hostvars[item]['ansible_ssh_common_args']
      run_once: true
      loop: "{{ target }}"
```

##### EXPECTED RESULTS

When I run playbooks with the following commands:
`ansible-playbook -i inventory.yml test-playbook-1.yml` or `ansible-playbook -i inventory.yml test-playbook-2.yml` I expect the same value for the variable `ansible_ssh_common_args`, which is output by the `Print vars` task:
```
    "hostvars[item]['ansible_ssh_common_args']": "-o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -W %h:%p user@example.org -p 2222 -i my_id_rsa '",
```

##### ACTUAL RESULTS

However, I get the value `__omit_place__holder_...` if I do not uncomment the task "Force evaluation of used host variables", which is executed on all hosts and implicitly on my_host_1. I would like to know if this behaviour is correct, because I use it to calculate inventory variables and output them to the file.

```paste below

PLAY [127.0.0.1] ************************************************************************************************************************************************

TASK [Print vars] ***********************************************************************************************************************************************
ok: [127.0.0.1] => (item=my_host_1) => {
    "ansible_loop_var": "item",
    "hostvars[item]['ansible_ssh_common_args']": "__omit_place_holder__b3e87bb35bd83deda50f3f1963b97b819673843f",
    "item": "my_host_1"
}

PLAY RECAP ******************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@dmrub: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/vars/hostvars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/vars/hostvars.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
Sadly these docs are misleading:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#making-variables-optional

The `omit` token does NOT make variables optional, it makes "action arguments" optional (if supplied value from variable is the omit token). See in the example, what is made 'optional' is the `mode` part of the `file` action, not the `item.mode` variable.

cc @akcozine

**Comment by dmrub** [comment]
Actually, that's not really what I'm asking, it's clear to me that `omit` does not mean to make the variable undefined, but just telling the module that the parameter with the `omit` value should simply be ignored (right?). 

Let me just change inventory to this by removing `default(omit)` expression:
```yaml
---
all:
  children:
    my_group:
      hosts:
        my_host_1:
          ansible_ssh_common_args: '{{ hostvars[node_ref].ansible_ssh_common_args }}'
        my_host_2:
          ansible_ssh_common_args: >-
            -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null
            -o StrictHostKeyChecking=no -W %h:%p user@example.org -p 2222
            -i my_id_rsa '
      vars:
        node_ref: my_host_2

```

Then if I run ansible playbook at localhost I will get following result:
```
$ ansible-playbook -i inventory-test-1.yml test-playbook-1.yml

PLAY [127.0.0.1] ****************************************************************************************************************************

TASK [Print vars] ***************************************************************************************************************************
ok: [127.0.0.1] => (item=my_host_1) => {
    "ansible_loop_var": "item",
    "hostvars[item]['ansible_ssh_common_args']": "{{ hostvars[node_ref].ansible_ssh_common_args }}",
    "item": "my_host_1"
}

PLAY RECAP **********************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Variable `ansible_ssh_common_args` on host `my_host_1` is not evaluated, and I am not sure why the output is just unevaluated template and not undefined value. But, actually what is really interesting to me is the fact that value will be only evaluated when I evaluate it on the host my_host_1 when I uncomment following lines in my playbook
```yaml
- hosts: all
  gather_facts: false
  tasks:

    - name: Force evaluation of used host variables
      set_fact:
        ansible_ssh_common_args: "{{ ansible_ssh_common_args | default(omit) }}"
``` 

And either this is an bug because you can evaluate this expression since the variable 'node_ref' is defined, or this is a feature because you can only evaluate if you are processing expressions for the specific host and 'node_ref' is only defined for my_host_1 and my_host_2.

**Comment by dmrub** [comment]
I have found another combination of inventory and playbook that generates an error:
Inventory inventory-t1.yml:
```yaml
---
all:
  children:
    my_group:
      hosts:
        my_host_1:
          ansible_ssh_common_args: '{{ hostvars[node_ref].ansible_ssh_common_args }}'
        my_host_2:
          ansible_ssh_common_args: >-
            -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null
            -o StrictHostKeyChecking=no -W %h:%p user@example.org -p 2222
            -i my_id_rsa '
      vars:
        node_ref: my_host_2
        ansible_user: my_user
        ansible_ssh_private_key_file: my_id_rsa
```

Playbook test-playbook-t1.yml:
```yaml
#- hosts: all
#  gather_facts: false
#  tasks:
#
#    - name: Force evaluation of used host variables
#      set_fact:
#        ansible_ssh_common_args: "{{ ansible_ssh_common_args }}"

- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    target: ['my_host_1']
  tasks:

    - name: Print vars
      debug:
        var: hostvars[item]['ansible_ssh_common_args']
      delegate_to: "{{ item }}"
      loop: "{{ target }}"
```

Then if I run ansible playbook I will get following result:
```
$ ansible-playbook -i inventory-t1.yml test-playbook-t1.yml

PLAY [127.0.0.1] *************************************************************************************************************************************

TASK [Print vars] ************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The field 'ssh_common_args' has an invalid value, which includes an undefined variable. The error was: 'node_ref' is undefined"}

PLAY RECAP *******************************************************************************************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
