### ISSUE TITLE
copy or sync files between two remote hosts (without trust between them)

### ISSUE THREAD

**Issue by muayyad-alsadi** [ansible/ansible#72246]
##### SUMMARY
the ability to sync two directories between two remote hosts without having ssh trust between source and destination
since it's typical for ops laptop or control node to be trusted but no trust between nodes.

```yaml
 - name: build assets
    run_once: yes
    command: yarn build
  - name: copy assets
    synchronize: src="{{ repo_dir }}/assets/" dest="{{ repo_dir }}/assets/"
    delegate_to: "{{ first_node }}"
    when: "inventory_hostname != first_node" 
```

in order for this to work, we had to use `delegate_to` and allow that node to be able to ssh to the other nodes
this is because in `rsync` the source and destination cannot both be remote.

otherwise one would get something like

```
<remote-user>@<other_node>: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.2.2]
rc: 255
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
synchronize_module

##### ADDITIONAL INFORMATION
there are many use cases, if this is not possible people would fetch from one remote then copy to the other remote
and this violates `Idempotence`.

there are many ways to implement this without having trust between the two remote nodes
one of them is to construct an ssh pipe between the two servers
on one end we tar to `stdout` on the other end we untar from `stdin`

```
ssh -p {SRC_SSH_PORT} ${SRC_SSH_USER}@${SRC_HOST} 'sudo -u $SRC_BECOME tar -czf - $SRC_PATH' | 
  ssh -p {DST_SSH_PORT} ${DST_SSH_USER}@${DST_HOST} 'sudo -u $DST_BECOME tar -C $DST_PATH -xzf -'
```

#### related docs

* https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html
* https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html
* https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
