### ISSUE TITLE
Cannot iterate over variables containing datetime values

### ISSUE THREAD

**Issue by oskar456** [ansible/ansible#72247]
##### SUMMARY

When importing a variable, which contains a list of dicts, iterating over the list is not possible if any value of any key in any dict contains a variable, that parses into a `datetime` object.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
ansible 2.11.0.dev0
  config file = None
  configured module search path = ['/home/oskar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oskar/Downloads/a/venv/lib/python3.7/site-packages/ansible
  ansible collection location = /home/oskar/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/oskar/Downloads/a/venv/bin/ansible
  python version = 3.7.9 (default, Sep 10 2020, 22:42:01) [GCC 9.3.0]
  libyaml = True
```

##### CONFIGURATION

```paste below
```
(empty output)

##### OS / ENVIRONMENT

Reproduced on Debian Linux and Gentoo Linux, on versions 2.7.7 as well as devel version.

##### STEPS TO REPRODUCE

```yaml
 - hosts: localhost
   become: no
   vars_files: data.yaml
   tasks:
     - debug:
        var: item.id
       with_items: "{{ data_1 }}"
     - debug:
        var: item.id
       with_items: "{{ data_2 }}"
```
data.yaml:
```yaml
data_1:
  - id: 1
    key: hello
  - id: 2
    key: world

data_2:
  - id: 1
    key: hello
  - id: 2
    key: 2020-10-19
```

##### EXPECTED RESULTS

Both debug tasks should print `"item.id": "1"` and `"item.id": "2"` like in the first task:

```
ok: [localhost] => (item={'id': 1, 'key': 'hello'}) => {
    "ansible_loop_var": "item",
    "item": {
        "id": 1,
        "key": "hello"
    },
    "item.id": "1"
}
ok: [localhost] => (item={'id': 2, 'key': 'world'}) => {
    "ansible_loop_var": "item",
    "item": {
        "id": 2,
        "key": "world"
    },
    "item.id": "2"
}
```
##### ACTUAL RESULTS

The second debug task is iterated only once and the `id` key cannot be accessed.

```paste below
ok: [localhost] => (item=[{'id': 1, 'key': 'hello'}, {'id': 2, 'key': datetime.date(2020, 10, 19)}]) => {
    "ansible_loop_var": "item",
    "item": "[{'id': 1, 'key': 'hello'}, {'id': 2, 'key': datetime.date(2020, 10, 19)}]",
    "item.id": "VARIABLE IS NOT DEFINED!: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'id'"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@oskar456 You may need to enclose value with quotes like `'2020-10-19'` 

```
# cat data.yaml
data_1:
  - id: 1
    key: hello
  - id: 2
    key: world

data_2:
  - id: 1
    key: hello
  - id: 2
    key: '2020-10-19'
```

```yaml
TASK [debug] **********************************************************************************
task path: /main.yml:8
ok: [localhost] => (item={'id': 1, 'key': 'hello'}) => {
    "ansible_loop_var": "item",
    "item": {
        "id": 1,
        "key": "hello"
    },
    "item.key": "hello"
}
ok: [localhost] => (item={'id': 2, 'key': '2020-10-19'}) => {
    "ansible_loop_var": "item",
    "item": {
        "id": 2,
        "key": "2020-10-19"
    },
    "item.key": "2020-10-19"
}
```

**Comment by mkrizek** [comment]
This is expected. There are two options:
1. if the intended type of the value is a string, quote the value that parses into `datetime` object to indicate it is a string:
```yaml
data_2:
  - id: 1
    key: hello
  - id: 2
    key: "2020-10-19"
```
2. if the intended type of the value is a `datetime` object, enable native types functionality https://docs.ansible.com/ansible/devel/reference_appendices/config.html#default-jinja2-native

The reason why this happens is that Jinja2 always returns strings. To work around that we have a function called `safe_eval` that tries to convert those strings back to their original type. So in this case we try to convert string of `"[{'id': 1, 'key': 'hello'}, {'id': 2, 'key': datetime.date(2020, 10, 19)}]"` to a list so it can be processed in `with_items`. The conversion fails because we do not consider `datetime.date` "safe" (hence `safe_eval`) and it says a string.

You can also read a gist I have put together that aims to explain this a bit more hopefully - https://gist.github.com/mkrizek/dbcf415b485fc3f2d4b3676ce0013397.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.freenode.net
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
