### ISSUE TITLE
SSM Lookup incompatible with boto3 1.16.0

### ISSUE THREAD

**Issue by stayman** [ansible/ansible#72268]
##### SUMMARY
SSM lookup fails when using boto3 1.16.0

When attempting a lookup via boto3 1.15.0 everything works successfully

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ssm lookup

##### ANSIBLE VERSION

```sh
ansible 2.9.14
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

There is no output.

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  become: true
  pre_tasks:
    - name: install boto3
      pip:
        name: boto3

    - name: get instance metadata
      ec2_metadata_facts:

    - name: retrieve ssm parameter
      set_fact:
        param: "{{ lookup('aws_ssm', ssm_path, region=ansible_ec2_placement_region) }}"
```

##### EXPECTED RESULTS

SSM parameter successfully retrieved

##### ACTUAL RESULTS

SSM errors saying boto3 and botocore are required

please note this is being run via `cloudinit`
```sh
TASK [retrieve ssm parameter] **************************************************
task path: /run/ansible/frontend/site.yml:18
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'aws_ssm'. Error was a <class 'ansible.errors.AnsibleError'>, original message: botocore and boto3 are required for aws_ssm lookup."
}
```
