### ISSUE TITLE
ssh Connection error

### ISSUE THREAD

**Issue by jameskeithp** [ansible/ansible#72265]
##### SUMMARY

 After running vagrant up and booting, the client fails to connect via SSH. Instead, the connection times out and retries repeatedly:

==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vagrant, ansible

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/keith/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
**No output from  ansible-config dump --only-changed**
```

##### OS / ENVIRONMENT

Host:
Windows 10 (MS Windows Version 2004 (OS Build 19041.508))

Target:
Ubuntu 18.04 

$ ethtool -i eth0
driver: hv_netvsc
version: 
firmware-version: N/A
expansion-rom-version: 
bus-info: 
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no

##### STEPS TO REPRODUCE

vagrant up --provision

```yaml

commands:
vagrant up
vagrant up --provision

Vagrantfile:
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "4024"
      vb.cpus = "1"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  config.vm.provision "ansible" do |ansible|
      ansible.become = true
      ansible.verbose = "v"
      ansible.playbook = "selinux-playbook.yml"
      ansible.galaxy_roles_path = "./roles"
  end
end

tasks/main.yml:
---
- name: Install SELinux python2 tools for EL 7
  package:
    name:
      - libselinux-python
      - policycoreutils-python
    state: present
  when: (ansible_distribution_major_version|int <= 7) and (ansible_python_version is version('3', '<'))

- name: Install SELinux python3 tools for EL 7
  package:
    name:
      - libselinux-python3
      - policycoreutils-python3
    state: present
  when: (ansible_distribution_major_version|int <= 7) and (ansible_python_version is version('3', '>='))

- name: Install SELinux python3 tools for EL 8
  package:
    name:
      - python3-libselinux
      - policycoreutils-python-utils
    state: present
  when: (ansible_distribution_major_version|int >= 8)

- name: Refresh facts ensuring SELinux status is available
  setup:
    filter: ansible_selinux

-name: Install SELinux tool semanage
 package:
   name:
     - policycoreutils-python-utils
   state: present
 when: ansible_distribution == "RedHat" or
   ( ansible_distribution_major_version > "7" and 
     ( ansible_distribution == "CentOS" or ansible_distribution == "Fedora"))

- name: Set permanent SELinux state if enabled
  selinux:
    state: "{{ selinux_state | default(ansible_selinux.config_mode, true) }}"
    policy: "{{ selinux_policy | default(ansible_selinux.type, true) }}"
  register: selinux_mod_output_enabled
  when: ansible_selinux.status == "enabled" ans ( selinux_state or selinux_policy )

- name: Set permanent SELinux state if disabled
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy | default('targeted', true) }}"
  register: selinux_mod_output_disabled
  when: ansible_selinux.status == "disabled" and selinux_state

- name: Set ansible facts if neded
  set_fact:
    selinux_reboot_required: "{{ selinux_mod_output_enabled.reboot_required
  if ( selinux_mod_output_enabled.reboot_required is defined ) else (
  selinux_mod_output_disabled.reboot_required | default(false) ) }}"

- name: Fail if reboot is reboot_required
  fail:
    msg: "Reboot is required to apply changes. Re-execute the role after boot."
  when: selinux_reboot_required

- debug:
    msg: "SELinux is disabled on system - some SELinux modules can crash"
  when: ansible_selinux.status == "disabled"

- name: Drop all local modifications
  command: /usr/sbin/semanage -i -
  args:
    stdin: "{{ drop_local_modifications }}"
  when: selinux_all_purge | bool

- name: Purge all SELinux boolean local modifications
  command: /usr/sbin/semanage boolean -D
  when: selinux_booleans_purge | bool

- name: Purge all SELinux file context local modifications
  command: /usr/sbin/semanage fcontext -D
  when: selinux_fcontexts_purge | bool

- name: Purge all SELinux port local modifications
  command: /usr/sbin/semanage port -D
  when: selinux_ports_purge | bool

- name: Purge all SELinux login local modifications
  command: /usr/sbin/semanage login -D
  when: selinux_logins_purge | bool

- name: Reload SELinux policy
  command: semodule -R
  when: ansible_selinux.status != "disabled"

- name: Set SELinux boolean states
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent|default('no') }}"
  with_items: "{{ selinux_booleans }}"
  when: ('status' in ansible_selinux) and (ansible_selinux.status != 'disabled')

- name: Set SELinux file context mapping definitions
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    ftype: "{{ item.ftype | default('a') }}"
    selevel: "{{ item.selevel | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ selinux_fcontexts }}"
  when: ('status' in ansible_selinux) and (ansible_selinux.status != 'disabled')

- name: Restore SELinux labels on filesystem tree
  command: /sbin/restorecon -R -v {{ item }}
  with_items: "{{ selinux_restore_dirs }}"
  register: restorecon_cmd
  changed_when: '"Relabeled" in restorecon_cmd.stdout'

- name: Restore SELinux labels on filesystem tree in check mode
  command: /sbin/restorecon -R -v -n {{ item }}
  with_items: "{{ selinux_restore_dirs }}"
  register: restorecon_cmd
  changed_when: '"Would relabel" in restorecon_cmd.stdout'
  check_mode: no
  when: ansible_check_mode

- name: Set SELinux port type definitions
  seport:
    ports: "{{ item.ports }}"
    proto: "{{ item.proto | default('tcp') }}"
    setype: "{{ item.setype }}"
    state: "{{ item.state | default(present) }}"
  with_items: "{{ selinux_ports }}"
  when: ('status' in ansible_selinux) and (ansible_selinux.status != 'disabled')

- name: Set linux user to SELinux user mappings
  selogin:
    login: "{{ item.login }}"
    seuser: "{{ item.seuser }}"
    serange: "{{ item.serange | default('s0') }}"
    selevel: "{{ item.selevel | default('s0') }}"
    state: "{{ item.state | default(present) }}"
    reload: "{{ item.reload | default(False) }}"
  with_items: "{{ selinux_logins }}"
  when: ('status' in ansible_selinux) and (ansible_selinux.status != 'disabled')

- name: Set SELinux permissive domains policy
  selinux_permissive:
    domain: "{{ item.domain }}"
    permissive: "{{ item.permissive }}"
    no_reload: "{{ item.no_reload | default(False) }}"
  with_items: "{{ selinux_permissives }}"
  when: ('status' in ansible_selinux) and (ansible_selinux.status != 'disabled')

selinux-playbook.yml:
---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    selinux_policy: targeted
    selinux_state: enforcing
    selinux_booleans:
      - { name: 'samba_enable_home_dirs', state: 'on' }
      - { name: 'ssh_sysadm_login', state: 'on', persistent: 'yes' }
    selinux_fcontexts:
      - { target: '/tmp/test_dir(/.*)?', setype: 'user_home_dir_t', ftype: 'd' }
    selinux_restore_dirs:
      - /tmp/test_dir
    selinux_ports:
      - { ports: '22100', proto: 'tcp', setype: 'ssh_port_t', state: 'present' }
    selinux_logins:
      - { login: 'sar-user', seuser: 'staff_u', serange: 's0-s0:c0.c1023', state: 'present' }

  # prepare prerequisites which are used in this playbook
  tasks:
    - name: Creates directory
      file:
        path: /tmp/test_dir
        state: directory
    - name: Add a Linux System Roles SELinux User
      user:
        comment: Linux System Roles SELinux User
        name: sar-user
    - name: execute the role and catch errors
      block:
        - include_role:
            name: linux-system-roles.selinux
      rescue:
        # Fail if failed for a different reason than selinux_reboot_required.
        - name: handle errors
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: restart managed host
          shell: sleep 2 && shutdown -r now "Ansible updates triggered"
          async: 1
          poll: 0
          ignore_errors: true

        - name: wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: reapply the role
          include_role:
            name: linux-system-roles.selinux
```

##### EXPECTED RESULTS

Configuration of CentOS 7

##### ACTUAL RESULTS

TASK [Gathering Facts] *********************************************************
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 2222: Connection refused", "unreachable": true}

PLAY RECAP *********************************************************************
default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```paste below
vagrant up --provision -vvvv
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/7' version '2004.01' is up to date...
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_ROLES_PATH='/mnt/c/Users/KeithJames/linux-system-role-selinux/roles' ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --limit="default" --inventory-file=/mnt/c/Users/KeithJames/linux-system-role-selinux/.vagrant/provisioners/ansible/inventory --become -v selinux-playbook.yml
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 2222: Connection refused", "unreachable": true}

PLAY RECAP *********************************************************************
default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
