### ISSUE TITLE
Load balancer always changed (etag)

### ISSUE THREAD

**Issue by barto90** [ansible/ansible#72277]
##### SUMMARY
On creating a load balancer the resource is always in a "changed"  state. 
When looking on the Azure portal it shows that nothing has been changed except for the value of 'etag' 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loadbalancer

##### ANSIBLE VERSION

```
ansible 2.10.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/*****/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/*****/.local/lib/python3.8/site-packages/ansible
  executable location = /home/****/.local/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 20.04 

##### STEPS TO REPRODUCE

Nothing special just the role (see below)

```
- name: create load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ resourcegroup }}"
    name: "{{ name }}"
    frontend_ip_configurations:
      - name: "{{ frontend_ip_name }}"
        private_ip_address: "{{ private_ip_address }}"
        private_ip_allocation_method: "{{ private_ip_allocation_method | default('static')}}"
        subnet: "{{ frontend_subnet }}"
    backend_address_pools:
      - name: "{{ backend_pool_name }}"
    probes: "{{ probes }}"
    load_balancing_rules: "{{ load_balance_rules }}"      
```

##### EXPECTED RESULTS
When no changes to the vars there should be no change on the load balancer for some reason etag is being updated and ansible handles this as a changed value I think?

##### ACTUAL RESULTS
Running the playbook takes a long time because  the value is "changed" but no changes are committed to the resource
