### ISSUE TITLE
Issue with blocks and tag "never"

### ISSUE THREAD

**Issue by p-l-** [ansible/ansible#72275]
Hi there, I have an issue (or maybe it is just something I don't really understand) with blocks and tags, using the "never" tag.

##### SUMMARY
When a subtask in a block has the `never` tag plus another tag (say, `tag1`) and the playbook is run with **another** tag (say, `tag2`), the tasks run, and I am not sure if it should.

For example, here is a sample:
```yaml
- name "My Block"
  tags:
  - tag2
  block:
  - name: "A task"
    [...]
  - name: "A task I don't want to run"
    tags:
    - never
    - tag1
    [...]
```

If I run using tag `tag2` (and only that one), from what I understand, the task named "A task I don't want to run" should not run. Am I wrong? Do I miss something

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
tag

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /home/user/Projets/rite/gestion-interne/scan-config/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Linux (Arch)

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: "My Block"
      tags:
      - tag2
      block:
      - name: "Task 1"
        debug:
          msg="I run"
      - name: "Task 2"
        debug:
          msg="I don't run. Or do I?"
        tags:
        - never
        - tag1
```

##### EXPECTED RESULTS

"Task 2" does not run without any tag, while "Task 1" does (that is expected).

When using "tag1" (and only that tag), I expect that only "Task 2" runs.

When using "tag2" (and only that tag), I expect that "Task 1" runs, and "Task 2" does not.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook -i localhost, test.yml 

PLAY [localhost] *********************************************************************

TASK [Task 1] ************************************************************************
ok: [localhost] => {
    "msg": "I run"
}

PLAY RECAP ***************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$ ansible-playbook -i localhost, -t tag2 test.yml 

PLAY [localhost] *********************************************************************

TASK [Task 1] ************************************************************************
ok: [localhost] => {
    "msg": "I run"
}

TASK [Task 2] ************************************************************************
ok: [localhost] => {
    "msg": "I don't run. Or do I?"
}

PLAY RECAP ***************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$ ansible-playbook -i localhost, -t tag1 test.yml 

PLAY [localhost] *********************************************************************

TASK [Task 2] ************************************************************************
ok: [localhost] => {
    "msg": "I don't run. Or do I?"
}

PLAY RECAP ***************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
