### ISSUE TITLE
Different ansible_host value in different groups

### ISSUE THREAD

**Issue by Mystic8b** [ansible/ansible#72303]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible Inventory

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/mystic/projects/vpn_composer/ansible.cfg) = ['/home/mystic/projects/vpn_composer/hosts.yml']
```

##### OS / ENVIRONMENT

Windows 10 20H2, WSL2, Ubuntu 20.10

##### STEPS TO REPRODUCE

Run any task first for one group and then for another

```yaml
#My inventory file:
my_servers:
  children:
    production:
      hosts:
        server1
          ansible_host: 192.168.0.2
    new:
      hosts:
        server1:
          ansible_host: 192.168.88.2
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

#run 1st:
ansible-playbook playbooks/playbook.yml -l new
#run 2nd:
ansible-playbook playbooks/playbook.yml -l production
```

##### EXPECTED RESULTS

In the first case (new) playbook is running for ip 192.168.0.2, and in the second (prod) for ip 192.168.88.2

##### ACTUAL RESULTS

In both cases runs for 192.168.88.2

```paste below
❯ ansible-playbook playbooks/playbook.yml -l production

PLAY [Main playbook] ***********************************************************************************************************************

TASK [Key authorization] *******************************************************************************************************************

TASK [authorization : Set authorized key taken from file] **********************************************************************************
fatal: [vpn16]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.88.2 port 22: No route to host", "unreachable": true}

PLAY RECAP *********************************************************************************************************************************
vpn16                      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/rst/inventory/implicit_localhost.rst`](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/inventory/implicit_localhost.rst)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
This is working as expected. Group vars are flattened per host and last defined wins. `-l` doesn't affect how inventory is loaded, just which hosts run a play.

**Comment by Mystic8b** [comment]
How else can I run one playbook for one host with different ip?

**Comment by sivel** [comment]
The hostname you specify in inventory is unique, and we flatten them into a single host when they are found multiple times.

You can create an "alias" to get your desired outcome:

```
my_servers:
  children:
    production:
      hosts:
        server1_0
          ansible_host: 192.168.0.2
    new:
      hosts:
        server1_88:
          ansible_host: 192.168.88.2
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by Mystic8b** [comment]
I didn't understand how this would help me. I have one variable file for this host and I need this file to be used regardless of what ip the connection to the server is under.
Well, okay, I'll go to the forum

**Comment by s-hertel** [comment]
@Mystic8b you probably want to re-evaluate the structure of your inventory. Use unique hostnames (except for entries you *want* to merge) and use common groups for the aliases to load vars they both need from group_vars. You can also load specific vars files with the `vars_files` keyword or an `include_vars` task.

**Comment by Mystic8b** [comment]
I read everything. This is a large server with a lot of variables. I can use group variables, but there are so many unique variables for each host. What I was trying to do is the only thing that can save me from changing the host ip address in the inventory file for each server of which there will be many in the cluster.
In my opinion - since inventory is implemented (combining variables in different groups) there should be no. This is not expected behavior in my opinion and I see no reason to close the issue, because this is obviously a problem with the functionality and the impossibility of solving the problem in a different way than the one specified.
ps sorry for English, I hope he spoke clearly.

**Comment by s-hertel** [comment]
Changing the flattening would be invasive and break things relying on the long-standing, documented behavior. It would also make inventory more complicated to use and understand.

> This is not expected behavior in my opinion...

Feel free to open a PR to add improvements for the documentation I linked to make it more expected.

> ... and the impossibility of solving the problem in a different way than the one specified

The suggestion was to fix the underlying issue rather than duct-taping something together. You could write an inventory plugin that restricts what's added to the hosts/vars under a particular group.

Your English is good.

**Comment by Mystic8b** [comment]
Unfortunately, I don't have sufficient knowledge to solve this problem, so I turn to the developers with it.
I think I can just make a different inventory file for the new servers, so far this looks like the most convenient solution.
But still, I think many would appreciate the possibility of implementing the proposed behavior. Alternatively, this could be done through a separate host branch, i.e.
```
group:
  children:
    one:
      host1:
        ansible_host: 192.168.0.2
    two:
      host1:
        ansible_host: 192.168.0.3
  some new name:
    three:
      host1:
        ansible_host: 192.168.0.4
```
So that by default everything works as before, but there is another branch different from children with its own behavior (in which the hosts are unique and independent from other groups).

Well, thanks anyway. Have a good day.
