### ISSUE TITLE
Different ansible_host value in different groups

### ISSUE THREAD

**Issue by Mystic8b** [ansible/ansible#72302]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible Inventory

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/mystic/projects/vpn_composer/ansible.cfg) = ['/home/mystic/projects/vpn_composer/hosts.yml']
```

##### OS / ENVIRONMENT

Windows 10 20H2, WSL2, Ubuntu 20.10

##### STEPS TO REPRODUCE

Run any task first for one group and then for another

```yaml
#My inventory file:
my_servers:
  children:
    production:
      hosts:
        server1
          ansible_host: 192.168.0.2
    new:
      hosts:
        server1:
          ansible_host: 192.168.88.2
      vars:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

#run 1st:
ansible-playbook playbooks/playbook.yml -l new
#run 2nd:
ansible-playbook playbooks/playbook.yml -l production
```

##### EXPECTED RESULTS

In the first case (new) playbook is running for ip 192.168.0.2, and in the second (prod) for ip 192.168.88.2

##### ACTUAL RESULTS

In both cases runs for 192.168.88.2

```paste below
❯ ansible-playbook playbooks/playbook.yml -l production

PLAY [Main playbook] ***********************************************************************************************************************

TASK [Key authorization] *******************************************************************************************************************

TASK [authorization : Set authorized key taken from file] **********************************************************************************
fatal: [vpn16]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.88.2 port 22: No route to host", "unreachable": true}

PLAY RECAP *********************************************************************************************************************************
vpn16                      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```
