### ISSUE TITLE
Ansible 2.9.6 - Python Module not found: firewalld and its python module are required for this module

### ISSUE THREAD

**Issue by caiherrero** [ansible/ansible#72328]
##### SUMMARY
Error al intentar aplicar una regla en el firewalld

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Python firewall module 

##### ANSIBLE VERSION

```paste below
ansible 2.8.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/root/ansible/nodos/inventory.yaml']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/root/roles/huaweicloud']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False

```

##### OS / ENVIRONMENT

Debian 10

##### STEPS TO REPRODUCE

```yaml
- name: Habilito el firewalld para HA
  firewalld:
    service: high-availability
    permanent: true
    state: enabled
  tags:
    - cluster

ansible-playbook /root/ansible/nodos/install.yaml -l nodo1 -t cluster
```

##### EXPECTED RESULTS

The above command has to enable HA ports on the firewalld

##### ACTUAL RESULTS

```paste below
fatal: [nodo1]: FAILED! => {"changed": false, "msg": "Python Module not found: firewalld and its python module are required for this module,                         version 0.2.11 or newer required (0.3.9 or newer for offline operations)"}

```
