### ISSUE TITLE
Too much RAM consumption when using set_facts and loop

### ISSUE THREAD

**Issue by FloLaco** [ansible/ansible#72339]
##### SUMMARY
I'm using an alpine docker image to run the playbook inside a Kubernetes cluster.
I'm launching a playbook with a dynamic inventory plugin which return me approx 6200 equipments.
I'm doing one check in the 6200 devices, then, I try to build a list of changed device and then send an email with this list.

When I'm doing this playbook with only 360 devices, it's all ok, but if I try with 6200, it's all ok until I'm try the build that list. 
The host which is running ansible-playbook get from 800MB-1GB of RAM to more than 5GB of RAM (and the worker is killed by OOM Killer).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
task module `set_fact` with loop

##### ANSIBLE VERSION

```paste below
ansible-playbook 2.9.14
  config file = /project/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.10 (default, Jun  3 2020, 20:06:19) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
[defaults]
host_key_checking = False
stdout_callback = skippy
#private_key_file = /root/.ssh/id_rsa
#transport=paramiko
local_tmp = /tmp/autobackup
remote_tmp = /tmp/autobackup
action_warnings = False
deprecation_warnings = False
interpreter_python = auto_silent
RETRY_FILES_ENABLED = True

[persistent_connection]
#connect_timeout = 60
#command_timeout = 6000
#connect_retry_timeout = 60


#[ssh_connection]
#ssh_args = -F /root/.ssh/config -o ControlMaster=auto -o ControlPersist=30m
```

##### OS / ENVIRONMENT

Alpine version : 3.12.0

##### STEPS TO REPRODUCE

```yaml
---
- name: Check if startup and running is same
  hosts: all
  gather_facts: no
  tasks:

  - name: Set date variable
    set_fact:
      datetime: "{{ lookup('pipe', 'date +%Y-%m-%d_%H:%M:%S') }}"
    delegate_to: localhost
    delegate_facts: true
    run_once: True

  - name: Get running
    ios_config:
      diff_against: startup
      diff_ignore_lines:
        - certificate self-signed.*$
        - '[A-Z0-9]{8}\s?.*$'
        - ^[\s]*quit.*$
        - ntp clock-period.*
    register: output



- name: Results
  hosts: localhost
  connection: local
  tasks:


  - name: Consolidate result in a single hashmap
    set_fact:
      switchs_changed: "{{ ((switchs_changed) | default([])) + [item.inventory_hostname + ' | ' + item.ansible_host] }}"
    when: item.output.changed
    loop: '{{ groups["all"] | map("extract", hostvars) | list }}'
    loop_control:
      label: "{{ item.inventory_hostname }}"


  - name: Send an email
    mail:
      host: example.com
      port: 25
      to: "<{{ email }}>"
      from: DSR Automation <dsr_automation@example.com>
      subject: "[AUTOMATION REPORT] Switch not saved"
      body: "{{ lookup('template', 'mail_body.j2') if switchs_changed is defined else lookup('template', 'mail_body_ok.j2') }}"
    run_once: True
```

##### EXPECTED RESULTS

The playbook finish with no error, the variable `switchs_changed` contain all the devices changed.

##### ACTUAL RESULTS

With `ANSIBLE_DEBUG=1`. I'm pasting a very very small part of my log because I have more than 420k lines of log.
I see that for each device the same output for task `Consolidate result in a single hashmap` as you can see in this pasting log.

```paste below
266744 1603468410.08232: done with get_vars()
266744 1603468410.08243: in VariableManager get_vars()
266744 1603468410.08252: Calling all_inventory to load vars for [C4]:SWEU-BO-11-104:FR223
266744 1603468410.08258: Calling groups_inventory to load vars for [C4]:SWEU-BO-11-104:FR223
266744 1603468410.08264: Calling all_plugins_inventory to load vars for [C4]:SWEU-BO-11-104:FR223
266744 1603468410.08294: Loading VarsModule 'host_group_vars' from /usr/local/lib/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py (found_in_cache=True, class_only=False)
266744 1603468410.08311: Loading data from /project/group_vars/all.yaml
266744 1603468410.08318: Calling all_plugins_play to load vars for [C4]:SWEU-BO-11-104:FR223
266744 1603468410.08348: Loading VarsModule 'host_group_vars' from /usr/local/lib/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py (found_in_cache=True, class_only=False)
266744 1603468410.08364: Loading data from /project/group_vars/all.yaml
266744 1603468410.08370: Calling groups_plugins_inventory to load vars for [C4]:SWEU-BO-11-104:FR223
266744 1603468410.08400: Loading VarsModule 'host_group_vars' from /usr/local/lib/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py (found_in_cache=True, class_only=False)
266744 1603468410.08413: Calling groups_plugins_play to load vars for [C4]:SWEU-BO-11-104:FR223
266744 1603468410.08439: Loading VarsModule 'host_group_vars' from /usr/local/lib/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py (found_in_cache=True, class_only=False)
266744 1603468410.08480: Loading VarsModule 'host_group_vars' from /usr/local/lib/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py (found_in_cache=True, class_only=False)
266744 1603468410.08518: Loading VarsModule 'host_group_vars' from /usr/local/lib/python3.6/site-packages/ansible/plugins/vars/host_group_vars.py (found_in_cache=True, class_only=False)
266744 1603468410.08638: done with get_vars()
266744 1603468591.11022: Loading FilterModule 'core' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/core.py (found_in_cache=True, class_only=False)
266744 1603468591.11035: Loading FilterModule 'gcp_kms_filters' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/gcp_kms_filters.py (found_in_cache=True, class_only=False)
266744 1603468591.11039: Loading FilterModule 'ipaddr' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/ipaddr.py (found_in_cache=True, class_only=False)
266744 1603468591.11043: Loading FilterModule 'json_query' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/json_query.py (found_in_cache=True, class_only=False)
266744 1603468591.11049: Loading FilterModule 'k8s' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/k8s.py (found_in_cache=True, class_only=False)
266744 1603468591.11054: Loading FilterModule 'mathstuff' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/mathstuff.py (found_in_cache=True, class_only=False)
266744 1603468591.11057: Loading FilterModule 'network' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/network.py (found_in_cache=True, class_only=False)
266744 1603468591.11061: Loading FilterModule 'urls' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/urls.py (found_in_cache=True, class_only=False)
266744 1603468591.11066: Loading FilterModule 'urlsplit' from /usr/local/lib/python3.6/site-packages/ansible/plugins/filter/urlsplit.py (found_in_cache=True, class_only=False)
266744 1603468591.11100: Loading TestModule 'core' from /usr/local/lib/python3.6/site-packages/ansible/plugins/test/core.py (found_in_cache=True, class_only=False)
266744 1603468591.11105: Loading TestModule 'files' from /usr/local/lib/python3.6/site-packages/ansible/plugins/test/files.py (found_in_cache=True, class_only=False)
266744 1603468591.11109: Loading TestModule 'mathstuff' from /usr/local/lib/python3.6/site-packages/ansible/plugins/test/mathstuff.py (found_in_cache=True, class_only=False)
     6 1603468619.21505: RUNNING CLEANUP
ERROR! A worker was found in a dead state
```

Without `ANSIBLE_DEBUG=1`

```paste below
ok: [[C4]:RSWBB-2-002:FR219]
ok: [[C4]:SWEU-FO-2-211:FR225]

PLAY [Results] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Consolidate result in a single hashmap] **********************************
ERROR! A worker was found in a dead state
```

Screenshot about RAM consumption 
![image](https://user-images.githubusercontent.com/1486562/97151625-0c980f00-1770-11eb-95ae-887ae4b7b72c.png)
