### ISSUE TITLE
Evaluating a string value with embedded jinja template creates a list instead of a string

### ISSUE THREAD

**Issue by dmrub** [ansible/ansible#72332]
##### SUMMARY

The evaluation of a template with the to_json filter sometimes produces list value instead of string.
I don't see anything that explains this behaviour in the documentation. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

variables
##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/home/rubinste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/lib/python3.7/site-packages/ansible
  executable location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/bin/ansible
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Fedora release 31 (Thirty One)

##### STEPS TO REPRODUCE

Run following playbook

```yaml
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:

    - name: Set values
      set_fact:
        value1: "[\n {{ 1 | to_json }} ]"
        value2: "[ {{ 1 | to_json }} ]"


    - name: Print values
      debug:
        msg: 
          - "{{ value1 }} of type {{ value1 | type_debug }}"
          - "{{ value2 }} of type {{ value2 | type_debug }}"
```

##### EXPECTED RESULTS

The Playbook should output value1 and value2 with debug module, and both values should be of type string and identical except for a single additional line break. 

##### ACTUAL RESULTS

value1 is of type list and value2 is of type str. I do not understand why value1 is of type list. The only difference is the additional line break. 

```paste below
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [127.0.0.1] **********************************************************************************************************************************************************

TASK [Set values] *********************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Print values] *******************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": [
        "[1] of type list",
        "[ 1 ] of type str"
    ]
}

PLAY RECAP ****************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The problem is with this regex:

https://github.com/ansible/ansible/blob/419766617956440512f8c32d2fd278fae9799c1e/lib/ansible/template/__init__.py#L640-L641

We don't use `re.S`/`re.DOTALL`, and as a result, we don't match the string type filters, because of the `\n`

**Comment by dmrub** [comment]
I have noticed another strange behaviour when I slightly modify the playbook and use temporary variables:

```yaml
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:

    - name: Set values
      set_fact:
        value1: "{{ tmp1 }}"
        value2: "{{ tmp2 }}"
      vars:
        tmp1: "[\n {{ 1 | to_json }} ]"
        tmp2: "[ {{ 1 | to_json }} ]"


    - name: Print values
      debug:
        msg: 
          - "{{ value1 }} of type {{ value1 | type_debug }}"
          - "{{ value2 }} of type {{ value2 | type_debug }}"

```

Result:

```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [127.0.0.1] **************************************************************************************************************

TASK [Set values] *************************************************************************************************************
ok: [127.0.0.1]

TASK [Print values] ***********************************************************************************************************
ok: [127.0.0.1] => {
    "msg": [
        "[1] of type list",
        "[1] of type list"
    ]
}

PLAY RECAP ********************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

I think both values should still be of the str not list type
