### ISSUE TITLE
local_action does not use localhost variables

### ISSUE THREAD

**Issue by future-cyborg** [ansible/ansible#72346]
##### SUMMARY
Long existing bug. [Previous issue](https://github.com/ansible/ansible/issues/1784) closed but not addressed. `ansible_python_interpreter` is the main one I care about, but the behaviour I'm noticing goes beyond just that issue. All `localhost` variables are ignored by `local_action`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
local_action

##### ANSIBLE VERSION
```paste below
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
```

##### CONFIGURATION
```paste below
INTERPRETER_PYTHON(**full path removed**/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT
Ansible running in docker. This is Dockerfile
```
FROM ubuntu:bionic

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
    && apt-get install -qq -y software-properties-common \
    && apt-add-repository --yes --update ppa:ansible/ansible \
    && apt-get install -qq -y \
    ansible \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get -qq update \
    && apt-get install -qq -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install docker

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
```

##### STEPS TO REPRODUCE
hosts
```yaml
all:
  hosts:
    localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
        foobar: something
  children:
    group_1:
      hosts:
        target_machine:
          ansible_host: <hostname>
```
playbook
```yaml
- hosts: group_1
  tasks:
    - local_action:
        module: debug
        var: ansible_python

    - local_action:
        module: debug
        var: ansible_connection

    - local_action:
        module: debug
        var: foobar

    - local_action:
        module: debug
        var: ansible_python_interpreter
```
I am concerned with a single `local_action` inside a playbook targetting a different machine, but this is all that's needed to reproduce.

##### EXPECTED RESULTS
```
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "ansible_python": {
        "executable": "/usr/bin/python3", 
        "has_sslcontext": true, 
        "type": "cpython", 
        "version": {
            "major": 3, 
            "micro": 9, 
            "minor": 6, 
            "releaselevel": "final", 
            "serial": 0
        }, 
        "version_info": [
            3, 
            6, 
            9, 
            "final", 
            0
        ]
    }
}
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "ansible_connection": "local"
}
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "foobar": "something"
}
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "ansible_python_interpreter": "/usr/bin/python3"
}
```

##### ACTUAL RESULTS
```paste below
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "ansible_python": {
        "executable": "/usr/bin/python3", 
        "has_sslcontext": true, 
        "type": "cpython", 
        "version": {
            "major": 3, 
            "micro": 9, 
            "minor": 6, 
            "releaselevel": "final", 
            "serial": 0
        }, 
        "version_info": [
            3, 
            6, 
            9, 
            "final", 
            0
        ]
    }
}
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "ansible_connection": "ssh"
}
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "foobar": "VARIABLE IS NOT DEFINED!"
}
TASK [debug] *******************************************************************
ok: [gateway -> localhost] => {
    "ansible_python_interpreter": "VARIABLE IS NOT DEFINED!"
}
```
