### ISSUE TITLE
vmware_guest: Disk type not set to "Thick" or "Thick Provision Lazy Zeroed" when set to "None", but to "Thin" during VM deployment from template

### ISSUE THREAD

**Issue by narcis-serbanescu** [ansible/ansible#72344]
##### SUMMARY

When deploying a template which has a disk type defined of "None" in playbook, the deployed VM disk type is set to "Thin" even though the documentation says it should have been "Thick".

https://docs.ansible.com/ansible/2.9/modules/vmware_guest_module.html#parameters
Documentation says: "Default: None thick disk, no eagerzero"

Also vmware_guest.py does not seem to treat this case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/snarcis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]

```

##### CONFIGURATION

```
# ansible-config dump --only-changed
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = runas
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/snarcis/src/cms_git/mysrc/ansible/ansible-windows/inventory/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_STRATEGY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/strategy']

```

##### OS / ENVIRONMENT

VMware vCenter Server version 6.0.0 14510547

##### STEPS TO REPRODUCE

```yaml
    - name: Deploy Virtual Machine from template
      vmware_guest:
        hostname: '{{ site }}{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ site }}{{ vcenter_datacenter }}'
        cluster: '{{ site }}{{ vcenter_cluster }}'
      
        template: "{{ vcenter_template }}"
        folder: /
        name: "{{ site | lower }}{{ vmname }}"
        validate_certs: False
        state: poweredon
        disk:
        - size_gb: 100
          type: None
          # type: thin
          # type: eagerzeroedthick
          autoselect_datastore: True
     
        hardware:
          memory_mb: "{{ ram_os_upgrade }}"
          num_cpus: 8
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          version: 11 # Hardware version of virtual machine
        networks:
        - name: "{{ network_dvpg_mgm }}"
          dvswitch_name: "{{ site }}{{ dvswitch_mgm }}"
          device_type: vmxnet3
          ip: "{{ ip_dvpg_mgm }}"
          netmask: "{{ ip_mask }}"
          gateway: "{{ ip_gw_mgm }}" 
          domain: "{{ cms_domain }}"
          dns_servers:
          - "{{ ip_dns1 }}"
          - "{{ ip_dns2 }}"
        - name: "{{ network_dvpg_ibr }}"
          dvswitch_name: "{{ site }}{{ dvswitch_ibr }}"
          device_type: vmxnet3
          ip: "{{ ip_dvpg_ibr }}"
          netmask: "{{ ip_mask }}"
          dns_servers:
          - "{{ ip_dns1 }}"
          - "{{ ip_dns2 }}"
        customization:
          dns_servers:
          - "{{ ip_dns1 }}"
          - "{{ ip_dns2 }}"
          domain: "{{ cms_domain }}"
          domainadmin: '{{ vcenter_username }}'
          domainadminpassword: '{{ vcenter_password }}'
          joindomain: "{{ cms_domain }}"
          orgname: IBM
          runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
          timezone: 85
      delegate_to: localhost

```

##### EXPECTED RESULTS

The VM created with disk type set to "Thick" or "Thick Provision Lazy Zeroed"

##### ACTUAL RESULTS

```paste below
TTASK [Deploy Virtual Machine from template] ************************************************************************************************************************
task path: /home/snarcis/src/cms_git/mysrc/ansible/ansible-vmware/vmware_deploy_template_AVS.yml:10
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: snarcis
<localhost> EXEC /bin/sh -c 'echo ~snarcis && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/snarcis/.ansible/tmp `"&& mkdir "` echo /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315 `" && echo ansible-tmp-1603731407.893717-43202-127219025715315="` echo /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315 `" ) && sleep 0'
Using module file /usr/lib/python3.8/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /home/snarcis/.ansible/tmp/ansible-local-43074kwq3ex4l/tmpnslypwxc TO /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315/ /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/snarcis/.ansible/tmp/ansible-tmp-1603731407.893717-43202-127219025715315/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "11269",
        "hw_cluster": "UKPM_P_DC_00_CL_38",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "ukpm_i1b_ds_v_sx_xiv_02_sas_1772gb_r1_7"
        ],
        "hw_esxi_host": "ukpmesx201ccpva.********",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": "00:50:56:a4:08:d0",
            "macaddress_dash": "00-50-56-a4-08-d0",
            "portgroup_key": "dvportgroup-68",
            "portgroup_portkey": "319",
            "summary": "DVSwitch: e1 cc 31 50 61 7d 41 49-e1 8c 1f da 54 da 2d dd"
        },
        "hw_eth1": {
            "addresstype": "assigned",
            "ipaddresses": null,
            "label": "Network adapter 2",
            "macaddress": "00:50:56:a4:16:fe",
            "macaddress_dash": "00-50-56-a4-16-fe",
            "portgroup_key": "dvportgroup-75",
            "portgroup_portkey": "319",
            "summary": "DVSwitch: f0 3d 31 50 a8 18 4b cc-7c 4e d5 5c 58 77 d1 a3"
        },
        "hw_files": [
            "[ukpm_i1b_ds_v_sx_xiv_02_sas_1772gb_r1_7] ukpmsep011ccpwa/ukpmsep011ccpwa.vmx",
            "[ukpm_i1b_ds_v_sx_xiv_02_sas_1772gb_r1_7] ukpmsep011ccpwa/ukpmsep011ccpwa.vmsd",
            "[ukpm_i1b_ds_v_sx_xiv_02_sas_1772gb_r1_7] ukpmsep011ccpwa/ukpmsep011ccpwa.nvram",
            "[ukpm_i1b_ds_v_sx_xiv_02_sas_1772gb_r1_7] ukpmsep011ccpwa/ukpmsep011ccpwa.vmdk"
        ],
        "hw_folder": "/UKPM_P_DC_00/vm",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": true,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0",
            "eth1"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 16384,
        "hw_name": "ukpmsep011ccpwa",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 8,
        "hw_product_uuid": "4224812f-f5c9-7551-f0df-9bd280091b31",
        "hw_version": "vmx-11",
        "instance_uuid": "5024b53b-ecfe-aaff-0599-795662fa4093",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "moid": "vm-26698",
        "snapshots": [],
        "vimref": "vim.VirtualMachine:vm-26698",
        "vnc": {}
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [],
            "cluster": "UKPM_P_DC_00_CL_38",
            "convert": null,
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "domainadmin": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "domainadminpassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "joindomain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "orgname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "runonce": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "timezone": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "UKPM_P_DC_00",
            "datastore": null,
            "disk": [
                {
                    "autoselect_datastore": true,
                    "size_gb": 100,
                    "type": "None"
                }
            ],
            "esxi_hostname": null,
            "folder": "/",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 16384,
                "num_cpu_cores_per_socket": 1,
                "num_cpus": 8,
                "scsi": "paravirtual",
                "version": 11
            },
            "hostname": "UKPMvcr011ccpva.********",
            "is_template": false,
            "linked_clone": false,
            "name": "ukpmsep011ccpwa",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "dns_servers": [
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    ],
                    "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "dvswitch_name": "UKPM_P_DC_00_DVS_SER",
                    "gateway": "130.103.159.1",
                    "ip": "130.103.159.30",
                    "name": "SR-Management_137-DVS",
                    "netmask": "255.255.255.192",
                    "type": "static"
                },
                {
                    "device_type": "vmxnet3",
                    "dns_servers": [
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    ],
                    "dvswitch_name": "UKPM_P_DC_00_DVS_IBR",
                    "ip": "146.89.169.32",
                    "name": "SR-Management-IBR_140-DVS",
                    "netmask": "255.255.255.192",
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": "P158_ESX_WIN_W2K16_64_20200421",
            "use_instance_uuid": false,
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_ip_address": false
        }
    }
}


```
