### ISSUE TITLE
Enable to specify multiple day in fortios_firewall_schedule_recurring module

### ISSUE THREAD

**Issue by defus** [ansible/ansible#72356]
##### SUMMARY
I cannot use multiple day in the fortios_firewall_schedule_recurring module as the documentation says

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
fortios_firewall_schedule_recurring

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /tmp/cib/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 01:53:50) [GCC 9.3.0]
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/tmp/cib/ansible.cfg) = ['/tmp/cib']
DEFAULT_ROLES_PATH(/tmp/cib/ansible.cfg) = ['/tmp/cib/roles']
GALAXY_SERVER_LIST(/tmp/cib/ansible.cfg) = ['awb_galaxy']
```

##### OS / ENVIRONMENT
docker image :  *quay.io/ansible/molecule:3.0.8*

##### STEPS TO REPRODUCE
```yaml
fortios_firewall_schedule_recurring:
  host:  "{{ provider.server }}"
  username: "{{ provider.user }}"
  password: "{{ provider.password }}"
  vdom:  "{{ provider.vdom }}"
  https: "{{ provider.https }}"
  ssl_verify: "{{ provider.ssl_verify }}"
  state: "present"
  firewall_schedule_recurring:
    name: "always-TODELETE"
    day: "monday tuesday wednesday thursday friday saturday sunday"
    start: "00:00"
    end: ""
```

##### EXPECTED RESULTS
Create schedule with multiple dates

##### ACTUAL RESULTS
```
fatal: [fortigate_psi]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'day'\n\nThe error appears to be in '/tmp/cib/plays/create_schedule.yml': line 16, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Créer un schedule\n      ^ here\n"
}
```
