### ISSUE TITLE
Variables should always be evaluated in the context they were defined in

### ISSUE THREAD

**Issue by andreasf** [ansible/ansible#7237]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.5
ansible 1.6, f8ca24b0469f14b1f71f956a2733fc8b4c889e77
##### Environment:

N/A
##### Summary:

Variables are reevaluated for each role, within the context of each role. This breaks the password lookup plugin, because basedir changes with the role.
##### Steps To Reproduce:

I have the following use case for the password lookup plugin: In a "mariadb" role, I set the DB root password. Later in a "web" role, I need that same password to create databases and users for some web apps. So I define a variable for the password in my main playbook, such that the scope includes all relevant roles (or is there only a global scope?):

``` yaml

---
# config.yml
- hosts: foo
  vars:
    db_root_passwd: "{{ lookup('password', 'credentials/db_root_passwd length=20') }}"
  roles:
    - role: mariadb
      tags: mariadb
    - role: web
      tags: web
    # ...
```

``` yaml

---
# roles/mariadb/tasks/main.yml
- debug: msg="root pass should be {{ db_root_passwd }}"
- name: set mariadb root password
  mysql_user: name=root password="{{ db_root_passwd }}" login_user=root login_password="{{ db_root_passwd }}" check_implicit_admin=yes
```

``` yaml

---
# roles/web/tasks/main.yml
- name: create roundcube database
  mysql_db: name=roundcube collation=utf8_general_ci encoding=utf8 login_user=root login_password="{{ db_root_passwd }}"
```
##### Expected Results:

The value of `db_root_passwd` should be the same in all roles.
##### Actual Results:

**v1.5.4/v1.5.5**: it mostly works. Modules get the correct password, but descriptions don't. The password variable is evaluated again for the description, in the context of the role (`basedir == roles/mariadb/files`):

```
TASK: [mariadb | debug msg="root pass should be JDc024g-JbWFu5N6oQmy"] ******** 
ok: [qemu] => {
    "item": "", 
    "msg": "root pass should be vBS,jcnuZUoUY0waKV4G"
}
```

The JSON output contains the expected password from the main playbook, evaluated at the project's root directory. The password in the task description is wrong, and there's also the side-effect that a new password file is created below the role. But if I remove the debug statement, no additional file is created, and I won't notice the bug.

**devel**: it seems that variables are always reevaluated in the context where they are used, instead of the context where they were defined in. The "web" role gets another password than the "mariadb" role, and the playbook fails.
