### ISSUE TITLE
apply_defaults for inventory (and other non-module) plugins

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible#72377]
##### SUMMARY
When developing modules, one can set [`apply_defaults`](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#apply-defaults) in the argspec to have a `dict` argument populated with defaults, if the user didn't set it.

It would be nice if the same would be possible for inventory plugins (and other plugins that don't use an argspec).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

lib/ansible/plugins/inventory/__init__.py

##### ADDITIONAL INFORMATION
I'd like to be able to write my inventory plugin documentation like this:

```
  DOCUMENTATION = '''
      name: myplugin
      plugin_type: inventory
      options:
        report:
          description: report API specific configuration
          type: dict
          apply_defaults: True
          ...

```
