### ISSUE TITLE
Ansible uri module not able to post multipart/form-data to Nexus

### ISSUE THREAD

**Issue by pk-vungle** [ansible/ansible#72371]
##### SUMMARY

I'm trying to run this command with URI module:
curl -X POST "https://nexus-url/service/rest/v1/components?repository=ign" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "raw.directory=test" -F "raw.asset1=@append-bootstrap.ign" -F "raw.asset1.filename=test"

the raw.asset1.filename contains the keyword filename, whereas raw.asset1 should be pointing to the file path of the source file to be uploaded.

I've tried these modules:
#1
```
uri:
  url: https://<nexus>/service/rest/v1/components?repository=ign
  method: POST
  body: "raw.directory=test&raw.asset1=/tmp/test&raw.asset1.filename=test"
```
The error was unsupported media type:
"msg": "Status code was 415 and not [200]: HTTP Error 415: Unsupported Media Type"

This error is the same when I use raw.asset1={{ lookup('file', '/tmp/test') }}

######################################################################

#2
```
uri:
  url: https://<nexus>/service/rest/v1/components?repository=ign
  method: POST
  body_format: form-multipart
  body:
    raw.directory: test
    raw.asset1: /tmp/test
    raw.asset1.filename: test
```
The error was missing filename or content:
"msg": "failed to parse body as form-multipart: at least one of filename or content must be provided"

######################################################################

#3
```
uri:
  url: https://<nexus>/service/rest/v1/components?repository=ign
  method: POST
  body: "raw.directory=test&raw.asset1=/tmp/test&raw.asset1.filename=test"
  src: /tmp/test
```
The error was body|src are mutually exclusive:
"msg": "parameters are mutually exclusive: body|src"

######################################################################

##### ISSUE TYPE
- Bug Report
The conditionals set for uri does not consider the field type the API has and caused issues.

##### COMPONENT NAME

ansible.builtin.uri
uri

##### ANSIBLE VERSION

```paste below
❯ ansible --version
ansible 2.10.2
  config file = /Volumes/Macintosh HD Data/ansible-galaxy/ansible.cfg
  configured module search path = [u'/~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /~/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(/Volumes/Macintosh HD Data/ansible-galaxy/ansible.cfg) = smart
DEFAULT_HOST_LIST(/Volumes/Macintosh HD Data/ansible-galaxy/ansible.cfg) = [u'/Volumes/Macintosh HD Data/ansible-galaxy/hosts']
DEFAULT_ROLES_PATH(/Volumes/Macintosh HD Data/ansible-galaxy/ansible.cfg) = [u'/Volumes/Macintosh HD Data/ansible-galaxy/roles']
DEFAULT_TRANSPORT(/Volumes/Macintosh HD Data/ansible-galaxy/ansible.cfg) = smart
```

##### OS / ENVIRONMENT

macOS Catalina v10.15.7

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
