### ISSUE TITLE
Variables containing template references to vars or vars_files are not being expanded when accessed though hostvars

### ISSUE THREAD

**Issue by Ramblurr** [ansible/ansible#72389]
##### SUMMARY

Variables defined as host/group vars that contain jinja2 templates that reference variables defined in `vars` or `vars_files` are not expanded when accessed through `hostvars`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible runner (?)

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/var/home/ramblurr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/ramblurr/.local/lib/python3.8/site-packages/ansible
  executable location = /var/home/ramblurr/.local/bin/ansible
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

##### CONFIGURATION

```paste below
<blank output>
```

##### OS / ENVIRONMENT

Fedora 32

##### STEPS TO REPRODUCE

*inventory.yml*
```yaml
all:
  vars:
    ansible_user: root
    expand_me: my favorite {{ base_category }} is {{ favorite_animal }}
  hosts:
    host1:
      favorite_animal: platypus
      friend: host2
    host2:
      favorite_animal: elephant
      friend: host1
```

*playbook.yml*
```yaml
---
- name: Test template expansion
  hosts: all
  vars:
    base_category: animal
  tasks:

    # access variable directly
    # PASSING: output should not contain template tags
    - name: access variable directly
      debug:
        msg: >-
          {{ expand_me }}

    # FAILING: output should not contain template tags
    - name: access self via hostvars
      debug:
        msg: >-
          {{ hostvars[inventory_hostname].expand_me }}

    # FAILING: output should not contain template tags
    - name: access friend via hostvars
      debug:
        msg: >-
          {{ hostvars[friend].expand_me }}
```

##### EXPECTED RESULTS

I expect the `access friend via hostvars` and `access self via hostvars` via hostvars tasks to print the message with the template tags expanded.

##### ACTUAL RESULTS

```paste below
ansible-playbook -i inventory.yml playbook.yml

PLAY [Test template expansion] ****************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [host1]
ok: [host2]

TASK [access variable directly] ***************************************************************************************
ok: [host1] => {
    "msg": "my favorite animal is platypus"
}
ok: [host2] => {
    "msg": "my favorite animal is elephant"
}

TASK [access self via hostvars] ***************************************************************************************
ok: [host1] => {
    "msg": "my favorite {{ base_category }} is {{ favorite_animal }}"
}
ok: [host2] => {
    "msg": "my favorite {{ base_category }} is {{ favorite_animal }}"
}

TASK [access friend via hostvars] *************************************************************************************
ok: [host1] => {
    "msg": "my favorite {{ base_category }} is {{ favorite_animal }}"
}
ok: [host2] => {
    "msg": "my favorite {{ base_category }} is {{ favorite_animal }}"
}

PLAY RECAP ************************************************************************************************************
host1                      : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
host2                      : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

If you remove the `{{ base_category }}` from the `expand_me` definition in the inventory, and run it, then the `{{ favorite_animal }}` is correctly expanded. This demonstrates that this bug is only triggered when one of the variables is defined in a vars/vars_file.

I found this related issue, but it is quite old:

https://github.com/ansible/ansible/issues/7844
