### ISSUE TITLE
Race Condition over creating and removing directories

### ISSUE THREAD

**Issue by hackaholic** [ansible/ansible#72382]
##### SUMMARY

Race Condition over removing directories
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module file
##### ANSIBLE VERSION

```paste below
ansible-2.9.13
```

##### OS / ENVIRONMENT

Os Centos 7
Linux test 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
##### STEPS TO REPRODUCE

```yaml
- name: Ensure directory structure is created
  file:
    path: <path-of-dir>
    state: directory
    mode: '0755'
    recurse: yes
   
```

##### EXPECTED RESULTS

If the directory is already present or removed, it should not throw error

##### ACTUAL RESULTS

```paste below
failed: [master] (item=/data/kafka) => {"ansible_loop_var": "item", "changed": false, "gid": 0, "group": "root", "item": "/data/kafka", "mode": "0755", "msg": "There was an issue creating /data/kafka as requested: [Errno 17] File exists: '/data/kafka'", "owner": "root", "path": "/data/kafka", "size": 4096, "state": "directory", "uid": 0}
```
