### ISSUE TITLE
 ansible.posix.mount on macOS 10.15.7 cannot mount ISO

### ISSUE THREAD

**Issue by NathanDotTo** [ansible/ansible#72387]
##### SUMMARY
The CLI commands to mount an ISO with macOS 10.15.7 are illustrated below:

```
$ hdiutil attach -nomount /tmp/ubuntu-20.04.1-live-server-amd64.iso 
/dev/disk3          	Apple_partition_scheme         	
/dev/disk3s1        	Apple_partition_map            	
/dev/disk3s2        	Apple_HFS                      	
$ mount -t cd9660 /dev/disk3 iso                                   
$ cd iso
$ ls
EFI			boot			dists			isolinux		pics			preseed
README.diskdefines	casper			install			md5sum.txt		pool			ubuntu
```
Note that this is a two step process. Also note the type of `cd9660`. The type of `cd9660` is not documented here:

https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html

An equivalent in Ansible would appear to be:
```
    - name: Mount Ubuntu ISO
      ansible.posix.mount:
        path: "iso"
        src: src="/tmp/ubuntu-20.04.1-live-server-amd64.iso"
        fstype: cd9660
        opts: auto
        state: mounted
```
That results in:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "boot": true,
            "dump": null,
            "fstab": null,
            "fstype": "cd9660",
            "opts": "auto",
            "passno": null,
            "path": "/tmp/ubuntu20/iso",
            "src": "src=\"/tmp/ubuntu-20.04.1-live-server-amd64.iso\"",
            "state": "mounted"
        }
    },
    "msg": "Error mounting /tmp/ubuntu20/iso: mount_cd9660: No such file or directory\nmount: /private/tmp/ubuntu20/iso failed with 1\n"
}
```
I *suspect* that this is because the `hdiutil` stage illustrated above is not executed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.posix.mount

##### ANSIBLE VERSION
```paste below
ansible 2.9.13
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/homebrew/Cellar/ansible/2.9.13_1/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/homebrew/bin/ansible
  python version = 3.9.0 (default, Oct 28 2020, 16:23:50) [Clang 12.0.0 (clang-1200.0.32.21)]
```

##### CONFIGURATION
Note that there was no output from `ansible-config dump --only-changed`.
```paste below

```

##### OS / ENVIRONMENT
macOS 10.15.7 (19H2)

##### STEPS TO REPRODUCE
1 - Have a ISO file in `/tmp`, e.g. /tmp/ubuntu-20.04.1-live-server-amd64.iso
2 - Create a directory `iso`, e.g. `mkdir iso`
2 - Run the playbook below, e.g. `sudo ansible-playbook -vvv mount.yml`

```yaml
    - name: Mount Ubuntu ISO
      ansible.posix.mount:
        path: "iso"
        src: src="/tmp/ubuntu-20.04.1-live-server-amd64.iso"
        fstype: cd9660
        opts: auto
        state: mounted
```

##### EXPECTED RESULTS
I expect to see the ISO mounted, as it is with the commands illustrated in the summary above.

##### ACTUAL RESULTS
The mount fails with file not found.

```paste below
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "boot": true,
            "dump": null,
            "fstab": null,
            "fstype": "cd9660",
            "opts": "auto",
            "passno": null,
            "path": "/tmp/ubuntu20/iso",
            "src": "src=\"/tmp/ubuntu-20.04.1-live-server-amd64.iso\"",
            "state": "mounted"
        }
    },
    "msg": "Error mounting /tmp/ubuntu20/iso: mount_cd9660: No such file or directory\nmount: /private/tmp/ubuntu20/iso failed with 1\n"
}
```
