### ISSUE TITLE
Cron module: cannot delete a single job in /etc/cron.d/

### ISSUE THREAD

**Issue by tty061** [ansible/ansible#72392]
##### SUMMARY
When using cron module specifying cron_file, name and state=absent, it removes an entire file with name specified at `cron_file` . There is no way to delete a single job in the file of `cron_file`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cron module

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/share/virtualenvs/ansible-vWK3ctRt/lib/python3.5/site-packages/ansible
  executable location = /home/ubuntu/.local/share/virtualenvs/ansible-vWK3ctRt/bin/ansible
  python version = 3.5.2 (default, Oct  7 2020, 17:19:02) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04 Xenial

##### STEPS TO REPRODUCE

`/etc/cron.d/test` :
```
#Ansible: Another job
* * * * * root echo ok
#Ansible: Old job
* * * * * root echo old
```

Playbook:

```yaml
---
- hosts: localhost
  become: yes
  tasks:
  - cron:
      cron_file: /etc/cron.d/test
      name: Another job
      job: echo ok
      user: root
      state: present
  - cron:
      cron_file: /etc/cron.d/test
      name: Old job
      user: root
      state: absent
```

Run playbook.

##### EXPECTED RESULTS

A single job with name specified at `name` will be deleted. Other jobs will remain.

`/etc/cron.d/test` :
```
#Ansible: Another job
* * * * * root echo ok
```

Ansible 2.9.14 does like this.

##### ACTUAL RESULTS

The file `/etc/cron.d/test` itself is deleted.
