### ISSUE TITLE
ini_file module to allow multiple distinct key-value pairs

### ISSUE THREAD

**Issue by ptMcGit** [ansible/ansible#72398]
##### SUMMARY

This request regards the community.general `ini_file` module (https://github.com/ansible-collections/community.general/blob/main/plugins/modules/files/ini_file.py)

Currently, a user can modify one value in an ini file:

``` yaml
- name: Ensure "fav=lemonade is in section "[drinks]" in specified file
  ini_file:
    path: /etc/conf
    section: drinks
    option: fav
    value: lemonade
    mode: '0600'
    backup: yes
```

I am interested in modifying the module such that multiple key-value pairs in one or more sections can be added, for example:

``` yaml
- name: Ensure drinks and foods in specified file.
  ini_file:
    path: /etc/conf
    data:
      - name: drinks
        - name: fav
          value: lemonade
      - name: foods
        - name: fav
          value: cheeseburger
    mode: '0600'
    backup: yes
```

Does this seem feasible? I have a prototype that seems to be working so far. I would like to continue working on it if no one sees any issues. Thanks, and apologies if I'm abusing the module style, as I'm not a regular Ansible developer.

@Andersson007
@felixfontein

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ini_file

##### ADDITIONAL INFORMATION

A user may wish to edit multiple key-value pairs in an ini file, e.g. a systemd file, in a single task.

There are at least two alternatives:

- multiple tasks, which results in multiple copy operations
- manage the file directly (with the copy module); this would interfere with a vendor's ability to update the file

```yaml
See Summary section
```
