### ISSUE TITLE
Playbook returns a wrong tower_job_id value

### ISSUE THREAD

**Issue by indirakas** [ansible/ansible#72422]
##### SUMMARY
I created a template workflow, where I pass along tower_job_id value from one sub template to another. This is needed to then notify when one template fails. In this example you can see that the actual job id was 230869, but the reported variable returned 151680933. Does anyone know why it picks this value?

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
2.7
```

```
---
# tasks file for get-config-nokia
- name: get-config-nokia
  block:
[...]
  always:
    - name: Pass job id to the next playbook
      set_stats:
        data:
          get_config_job_id: "{{ tower_job_id }}"

```

##### EXPECTED RESULTS

<img width="732" alt="Screen Shot 2020-10-20 at 9 46 19 AM" src="https://user-images.githubusercontent.com/18408269/97755712-eb5c5900-1ab6-11eb-868f-60a1eb3083cd.png">

You can see that the job_id is 230869, but the playbook return value of 151680933.
My expectation is that get_config_job_id variable value is 230869.
