### ISSUE TITLE
Jinja2 native breaks vault values in loop.

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#72432]
##### SUMMARY
When using vault variable in loop and jinja2 native is enabled, the vault value is converted to an obscure string instead of its actual value.

Looks like it works as expected in 2.11 branch, so backporting the fix may be enough.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = None
  configured module search path = ['/Users/jddupas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jddupas/Projects/python/playbooks/.venv/lib/python3.8/site-packages/ansible
  executable location = /Users/jddupas/Projects/python/playbooks/.venv/bin/ansible
  python version = 3.8.6 (default, Oct 19 2020, 10:02:55) [Clang 12.0.0 (clang-1200.0.32.2)]
```

##### CONFIGURATION

```paste below
 
```

##### STEPS TO REPRODUCE

playbook.yaml
```yaml
- hosts: localhost
  vars:
    items:
      - hello: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31396261646630646134353932653239323566393561303230346139346539323134376563663034
          3063633539313664313231396334333533396338326535370a623563306432326132633465666132
          34396666313735393965313439393366653034643333623564663835623931343831643065633166
          6261656535353762310a663532636135613765393230643464663431366365646136323435303564
          3439
  tasks:
    - debug:
        msg: "{{ items[0].hello }}"

    - loop: "{{ items }}"
      debug:
        msg: "{{ item.hello }}"
```

password.txt
```
ansible
```

```
env ANSIBLE_JINJA2_NATIVE=true ansible-playbook --vault-password-file password.txt playbook.yaml
```

##### EXPECTED RESULTS

I expect that both debug tasks output 

```
"msg": "hello"
```

##### ACTUAL RESULTS

```paste below
PLAY [localhost] **********************************************************************

TASK [Gathering Facts] ****************************************************************
ok: [localhost]

TASK [debug] **************************************************************************
ok: [localhost] => {
    "msg": "hello"
}

TASK [debug] **************************************************************************
ok: [localhost] => (item={'hello': '<generator object _wrap_sequence.<locals>.<genexpr> at 0x1080d4900>'}) => {
    "msg": "<generator object _wrap_sequence.<locals>.<genexpr> at 0x1083e3040>"
}

PLAY RECAP ****************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
