### ISSUE TITLE
k8s: Variables read from dictionaries get quoted

### ISSUE THREAD

**Issue by andiolsi** [ansible/ansible#72470]
##### SUMMARY
The k8s module incorrectly quotes entries such as port and replicas when they are read from a dict using jinja2 templating

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```
ansible 2.9.11
  config file = /Users/myuser/.ansible.cfg
  configured module search path = ['/Users/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.11/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### OS / ENVIRONMENT
Mac OS X 10.15.6

##### STEPS TO REPRODUCE

Define variables
```yaml
dict_with_service_info:
  - name: serviceX
     service-name: service-X
     replicas: 1
  - name: serviceY
     service-name: service-Y
     replicas: 2
```

create playbook
```yaml
---
- hosts: k8smaster
  tasks:
  - name: Create service object
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{item.service_name}}"
          namespace: default
          labels:
            run: "{{item.service_name}}"
        spec:
          selector:
            run: "{{item.service_name}}"
          ports:
          - protocol: TCP
            targetPort: 8080
            port: 8080
    loop: "{{dict_with_service_info | flatten(1)}}"
  - name: Deploy PODs
    vars:
      name: sv_cache
      service_name: service-cache
      replicas: 2
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: "{{item.service_name}}"
          namespace: default
        spec:
          selector:
            matchLabels:
              run: "{{item.service_name}}"
          replicas: "{{item.replicas}}"
          template:
            metadata:
              namespace: default
              labels:
                run: "{{item.service_name}}"
            spec:
              containers:
                - name: "{{item.service_name}}"
                  image: "nginx:latest"
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 8080
    loop: "{{dict_with_service_info | flatten(1)}}"
```

##### EXPECTED RESULTS
```
TASK [some-services : Deploy PODs] **********************************************************************************************************
changed: [k8smaster]
```

##### ACTUAL RESULTS
replicas gets quoted
```
ASK [some-services : Deploy PODs] **********************************************************************************************************
failed: [k8smaster] (item={'

....
v1.DeploymentSpec.Replicas: readUint32: unexpected character: \\ufffd, error found in #10 byte of ...|eplicas\\\":\\\"1\\\"

```

The same will be the case if you do:
```
replicas: "{{variable | to_json | from_json | int}}"
```

Whereas the following works:
```
replicas: "{{variable}}"
```
