### ISSUE TITLE
Unarchive fails for remote tar archives when using relative paths 

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#72517]
##### SUMMARY
Unarchive fails with relative paths, but only for remote tar archives.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
unarchive

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bilge/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

Linux 4.15.0-101-generic x86_64 GNU/Linux Ubuntu 18.04.3 LTS

##### STEPS TO REPRODUCE

```yaml
- name: Create download and compilation directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0775
  loop:
    - downloads
    - compiled

- name: Download archive
  get_url:
    url: '{{ src }}'
    dest: downloads
  register: download

- name: Extract archive
  unarchive:
    remote_src: yes
    src: '{{ download.dest }}'
    dest: compiled
```

##### EXPECTED RESULTS
Extracts archive `{{ src }}`.

##### ACTUAL RESULTS
* Works when archive is a zip file.
* Fails when archive is a tar file.

```paste below
Failed to find handler for \"foo.tar.gz\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/bin/tar\" could not handle archive.
```

Can be fixed by using absolute paths:

```diff
-    src: '{{ download.dest }}'
-    dest: compiled
+    src: ~/{{ download.dest }}
+    dest: ~/compiled
```

Note that **both** src *and* dest **must** be absolute to workaround the problem.
