### ISSUE TITLE
Setting ssh_args disables pipelining mode incorrectly

### ISSUE THREAD

**Issue by axelson** [ansible/ansible#7251]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.5
##### Environment:

Running Ansible on Mac OS X Mavericks and managing SmartOS (Solaris).
##### Summary:

SSH Pipelining [1] doesn't work if sudo_user is set. If I comment out the sudo_user and sudo then the pipelining works.

[1] http://docs.ansible.com/intro_configuration.html#pipelining
##### Steps To Reproduce:

Here's my simple.yml file:

```

---
- hosts: all
  sudo: yes
  sudo_user: jason
  tasks:
    - name: git
      git: repo=https://github.com/ansible/ansible.git dest=~/ansible update=yes force=no
      environment: env_var
```

ansible-playbook -e "pipelining=True" simple.yml

With sudo_user and sudo and running with -vvv I can see that Ansible is running separate mkdir and chmod commands over ssh.

env_var is needed to set PATH for git
##### Expected Results:

I expect ansible to not send separate SSH commands for mkdir and chmod. 
##### Actual Results:

SSH Pipelining is working so the ssh command for mkdir and chmod are combined.
