### ISSUE TITLE
"[Errno 2] No such file or directory" for existing custom fact containing incorrect character leading to bad interpreter error

### ISSUE THREAD

**Issue by captainjs** [ansible/ansible#72518]
##### SUMMARY

I was getting an incorrect error message saying that there is no such file or directory. In fact the issue was that the setup could not execute the myfact.fact (which was a bash file, with some incorrect character from windows).

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
Ansible 2.8.12
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

RHEL7

##### STEPS TO REPRODUCE

1. Put the file with incorrect windows character in /etc/ansible/facts.d/activecards.fact
2.  Run the playbook once: it should copy the fact. It will fail at the step calling the setup module again 
(  - name: "Re-run setup to use custom facts"
    setup: ~
).
The error shows: 
"msg": "[Errno 2] No such file or directory",
            "rc": 2
        }
    },
    "msg": "The following modules failed to execute: setup\n"

3. Run the playbook again, immediate failure (because the setup module runs at start of the playbook).

```yaml
---
- name: playbook testing
  hosts: test
#  become: true
 
  tasks:
  - name: "Create custom fact directory"
    file:
      path: "/etc/ansible/facts.d"
      state: "directory"
 
  - name: "Insert custom fact file active cards"
    copy:
      src: files/facts/active_cards.fact
      dest: /etc/ansible/facts.d/activecards.fact
      mode: 0755
 
  - name: "Insert custom fact file CP Config"
    copy:
      src: files/facts/contentplayer_config.fact
      dest: /etc/ansible/facts.d/contentplayerconfig.fact
      mode: 0755
 
  - name: "Insert custom fact file GPU type"
    copy:
      src: files/facts/gputype.fact
      dest: /etc/ansible/facts.d/gputype.fact
      mode: 0755
 
  - name: "Insert custom fact file Realm Joined"
    copy:
      src: files/facts/realm_joined.fact
      dest: /etc/ansible/facts.d/realmjoined.fact
      mode: 0755
 
  - name: "Re-run setup to use custom facts"
    setup: ~
 
  - name: debug var
    debug:
      #var: hostvars.host.ansible_local.activecards
      var: ansible_local.activecards
 
```

##### EXPECTED RESULTS

It should say that the setup module can not retrieve some valid json output from the bash file, because it contains some invalid windows lines characters. In fact, it should say that the setup module failed because the bash file returns "bad interpreter: No such file or directory". See below for explanation.

##### ACTUAL RESULTS

It should not says ""[Errno 2] No such file or directory"" it should say something is wrong with the setup module.

```paste below

```
I have copied here the manual troubleshooting:

[root@ostp6-cpx12-t4 facts.d]# ./activecards.fact
-bash: ./activecards.fact: /usr/bin/bash^M: bad interpreter: No such file or directory

[root@ostp6-cpx12-t4 facts.d]# cat activecards.fact
#!/usr/bin/bash
 
MAX=4
RESULT=0
FACT_NAME="cp_active_cards"
 
for i in $(seq $MAX -1 1); do
    /usr/bin/test -e /sys/class/drm/card${i}
    if [ $? -eq 0 ]; then
        RESULT=$i
        break
    fi
done
 
echo "${FACT_NAME}=${RESULT}"
[root@ostp6-cpx12-t4 facts.d]# date
Fri Nov  6 12:00:35 CET 2020

That was failing because some invalid windows character where there, I had to do this:
sed -o -e 's/\r$//' activecards.fact
After doing that, the invalid characters got removed and I could:
./activecards.fact.
