### ISSUE TITLE
Block notify

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#72520]
##### SUMMARY
Support `notify` on blocks, with the intended side-effect that the following would also work.

```yaml
- import_tasks: foo.yml
  notify: my handler
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
blocks

##### ADDITIONAL INFORMATION
I think `notify` should work on blocks, such that if any subtask is changed, the handler is run. My understanding is that `import_tasks` is implemented with blocks, so supporting it for blocks would kill two birds with one stone. In case that's not the low-level implementation, the same support should be extended to `import_tasks` anyway.

Note that the current behaviour of the above YAML is that it does nothing, neither notifying the user it's invalid nor having the expected effect.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/block.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/block.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @Bilge 

I cannot see how this could be implemented. The handlers are called when there is a change in a single task: 

For instance, if you do:

```yaml
## mintask.yml file
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: foo.conf
    state: touch
  notify:
    - Debug
```

This task will call a handler like this, even though it comes from a `import_task` and the handler is located in the main file:

```yaml
---
- name: MyPlay
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Import
      import_tasks: minitask.yml

  handlers:

    - name: Debug
      debug:
        msg: "Notify"
```

If your imported task is like this:

```yaml
- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: foo.conf
    state: touch
  changed_when: False
  notify:
    - Debug
```

The handler will never be called

Or if you have something like this:

```yml
---
- name: Test
  debug:
    msg: "Call Notify"
  changed_when: True
  notify:
    - Debug


- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: foo.conf
    state: touch
  notify:
    - Debug
```

The handler will be called once.

I have several questions:

* How do you expect in a block to call a handler? 
* How you will manage if a single task has changed? 
* How you will manage a handler if you have a loop?

I personally can see this feature quite complicated to implement beforehand.

What do you think?
