### ISSUE TITLE
ipaddr filter cannot be used in Ansible 2.9.15 on Ubuntu 16.04

### ISSUE THREAD

**Issue by relyt0925** [ansible/ansible#72525]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

netaddr/ipaddr filter 

##### ANSIBLE VERSION

```paste below
Ansible 2.9.15
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

Try to use ipaddr filter in a template like 
```
<10.93.34.41> EXEC /bin/sh -c '\''rm -f -r /root/.ansible/tmp/ansible-tmp-1604698086.2652125-6320-187974680628152/ > /dev/null 2>&1 && sleep 0'\''
fatal: [10.93.34.41]: FAILED! => {
    "changed": false,
    "msg": "AnsibleError: template error while templating string: no filter named '\''ipaddr'\''. String: # 
<!--- Paste example playbooks or commands between quotes below -->
```

##### EXPECTED RESULTS

ipaddr filter to be available when netaddr python package is installed

##### ACTUAL RESULTS

ipaddr filter is not available in ansible 2.9.15 on Ubuntu 16.04

```paste below

```

Note: I do not see the same regression on RHEL 7 or Ubuntu 18.04

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/plugins/filter`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by relyt0925** [comment]
```
--cluster-dns={{ k8s_service_ip_range|ipaddr('10')|ipaddr('address') }} \
```

I am going to try to replicate in a set_fact role with just that. But in our reproduce we actually try to jinja template a file

**Comment by relyt0925** [comment]
I see this note about it migrating to netcommon but wouldn't expect it to break on a patch update 
https://galaxy.ansible.com/ansible/netcommon?extIdCarryOver=true&sc_cid=701f2000001OH6uAAG

I can replicate with this playbook:
```
- hosts: all
  tasks:
    - name: get existing svc
      set_fact:
        k8s_service_ip_range: "172.20.0.0/16"

    - name: get existing svc
      set_fact:
        cluster_dns: "{{ k8s_service_ip_range|ipaddr('10')|ipaddr('address') }}"
```
