### ISSUE TITLE
Question, how to start systemd services for user?

### ISSUE THREAD

**Issue by ikke-t** [ansible/ansible#72529]
Hi,

how do I get systemd services started for user scope instead of system scope?

I'm trying to setup rootless containers using podman, and [as instructed here](https://github.com/containers/podman/issues/7938#issuecomment-723095019), I need to make systemd services specified in ~/.config/systemd/user/.

I see systemd module supports this somehow as there is [scope variable nowadays](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#parameter-scope).

However I get this:

```fatal: [fiot]: FAILED! => {"changed": false, "msg": "Could not find the requested service lighttpd-container-pod.service: host"}```

The task from [this playbook](https://github.com/ikke-t/podman-container-systemd/blob/rootless/tasks/main.yml) is:
```
  - name: ensure "{{ service_name }}" is enabled at boot, and systemd reloaded
    become: true
    become_user: "{{ container_run_as_user }}"
    systemd:
      name: "{{ service_name }}"
      enabled: true
      daemon_reload: true
      scope: "{{ systemd_scope }}"
```

while running this playbook for the role:
https://github.com/ikke-t/podman-container-systemd/blob/rootless/tests/test.yml

using user session:
```ansible-playbook -i hosts -e container_state=running -e container_run_as_user=ikke playbooks/test.yml```

To reproduce this one just needs the role from here: https://github.com/ikke-t/podman-container-systemd/ , the rootless branch. The test case can be run like in above sample.

The ansible host is RHEL 8.3 latest, with ansible-2.9.14-1.el8ae.noarch, also the latest. The target where I test these is Fedora-IoT 33.
