### ISSUE TITLE
pyVim import fails on macOS because of capital 'V'

### ISSUE THREAD

**Issue by NathanDotTo** [ansible/ansible#72532]
##### SUMMARY

As illustrated below, the pyvim module is imported with "pyVim", using a capital 'V'. On a non case sensitive file system, such as macOS when installed that way, this fails, as the module can only be installed in site-packages as "pyvim". 

On a typical Linux install, say Ubuntu, there are two modules installed, "pyvim" and "pyVim", so this import works as expected.

```bash
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/18/h1984hd95ms_l22lvpwzc57r0000gn/T/ansible_community.vmware.vmware_guest_payload_7u45s4au/ansible_community.vmware.vmware_guest_payload.zip/ansible_collections/community/vmware/plugins/module_utils/vmware.py", line 33, in <module>
    from pyVim import connect
ModuleNotFoundError: No module named 'pyVim'
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.vmware.vmware_guest
ansible_collections/community/vmware/plugins/module_utils/vmware.py

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/homebrew/lib/python3.9/site-packages/ansible
  executable location = /usr/local/homebrew/bin/ansible
  python version = 3.9.0 (default, Nov  6 2020, 14:04:55) [Clang 12.0.0 (clang-1200.0.32.21)]
```

##### CONFIGURATION

```paste below
% ansible-config dump --only-changed
% 
```

##### OS / ENVIRONMENT

macOS 10.15.7 with supplemental update

##### STEPS TO REPRODUCE

Use the vmware_guest module as illustrated below in the yaml snippet.

```yaml
---
- hosts: localhost
  name:  xxx.yml
  gather_facts: false

  vars_files:
    - inception_vars.yml

  tasks:
    - name: Deploy Ubuntu VM
      community.vmware.vmware_guest:
        hostname: "{{ vCenterServer }}"
        esxi_hostname: "{{ ESXiHost }}"
        username: "{{ vCenterUser }}"
        password: "{{ vCenterPassword }}"
        validate_certs: no
        datacenter: "{{ DataCenter }}"
        name: "{{ UbuntuVMName }}"
        state: poweredon
        guest_id: ubuntu64Guest
        datastore: "{{ Datastore }}"
        folder: ""
        disk:
        - size_gb: "{{ UbuntuVMDiskSize }}"
          type: thin
          datastore: "{{ Datastore }}"
        hardware:
          memory_mb: "{{ UbuntuVMMemorySize }}"
          num_cpus: "{{ UbuntuVMCPUs }}"
          num_cpu_cores_per_socket: "{{ UbuntuVMCPUCores }}"
          scsi: paravirtual
        networks:
          - name: "{{ UbuntuVMPortGroup }}"
            device_type: vmxnet3
        cdrom:
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: "[{{ Datastore }}] {{ DatastoreDir }}/{{ UbuntuNewISO }}"
        annotation: | 
                    *** Auto-Deployed by Ansible ***
                    Username: {{ UbuntuOSUser }}
                    Password: {{ UbuntuOSPassword }}
      delegate_to: localhost
      register: deploy_vm
```

##### EXPECTED RESULTS

I expect that the module will be executed.

##### ACTUAL RESULTS

The module execution fails with an import error.

```paste below
ansible-playbook -vvv xxx.yml
ansible-playbook 2.10.3
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/homebrew/lib/python3.9/site-packages/ansible
  executable location = /usr/local/homebrew/bin/ansible-playbook
  python version = 3.9.0 (default, Nov  6 2020, 14:04:55) [Clang 12.0.0 (clang-1200.0.32.21)]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
redirecting (type: modules) ansible.builtin.vmware_guest_info to community.vmware.vmware_guest_info
redirecting (type: modules) ansible.builtin.vmware_vm_shell to community.vmware.vmware_vm_shell
redirecting (type: modules) ansible.builtin.vmware_guest_file_operation to community.vmware.vmware_guest_file_operation
redirecting (type: modules) ansible.builtin.vmware_vm_shell to community.vmware.vmware_vm_shell
redirecting (type: modules) ansible.builtin.vmware_guest_file_operation to community.vmware.vmware_guest_file_operation
redirecting (type: modules) ansible.builtin.vmware_vm_shell to community.vmware.vmware_vm_shell
redirecting (type: modules) ansible.builtin.vmware_guest_file_operation to community.vmware.vmware_guest_file_operation
redirecting (type: modules) ansible.builtin.vmware_vm_shell to community.vmware.vmware_vm_shell
redirecting (type: modules) ansible.builtin.vmware_vm_shell to community.vmware.vmware_vm_shell
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: Inception_VM_vCenter.yml ************************************************************************************************************************
1 plays in Inception_VM_vCenter.yml
Read vars_file 'inception_vars.yml'
Read vars_file 'inception_vars.yml'
Read vars_file 'inception_vars.yml'

PLAY [Inception_VM_vCenter.yml] ***************************************************************************************************************************
Read vars_file 'inception_vars.yml'
META: ran handlers
Read vars_file 'inception_vars.yml'
Read vars_file 'inception_vars.yml'

TASK [Deploy Ubuntu VM] ***********************************************************************************************************************************
task path: /Users/xxx/xxx.yml:10
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: xxx
<localhost> EXEC /bin/sh -c 'echo ~xxx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/xxx/.ansible/tmp `"&& mkdir "` echo /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191 `" && echo ansible-tmp-1604827050.940812-83986-164736892832191="` echo /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191 `" ) && sleep 0'
Using module file /Users/xxx/.ansible/collections/ansible_collections/community/vmware/plugins/modules/vmware_guest.py
<localhost> PUT /Users/xxx/.ansible/tmp/ansible-local-8398321jskmwe/tmpe1gayiw4 TO /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191/ /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/homebrew/opt/python@3.9/bin/python3.9 /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/xxx/.ansible/tmp/ansible-tmp-1604827050.940812-83986-164736892832191/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/18/h1984hd95ms_l22lvpwzc57r0000gn/T/ansible_community.vmware.vmware_guest_payload_nfjv6q32/ansible_community.vmware.vmware_guest_payload.zip/ansible_collections/community/vmware/plugins/module_utils/vmware.py", line 33, in <module>
    from pyVim import connect
ModuleNotFoundError: No module named 'pyVim'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": "*** Auto-Deployed by Ansible ***\nUsername: xxx\nPassword: xxx\n",
            "cdrom": [
                {
                    "controller_number": 0,
                    "iso_path": "[xxx] /ISOs/xxx.iso",
                    "state": "present",
                    "type": "iso",
                    "unit_number": 0
                }
            ],
            "cluster": null,
            "convert": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "xxx",
            "datastore": "xxx",
            "delete_from_inventory": false,
            "disk": [
                {
                    "datastore": "xxx",
                    "size_gb": 200,
                    "type": "thin"
                }
            ],
            "esxi_hostname": "xxx",
            "folder": "",
            "force": false,
            "guest_id": "ubuntu64Guest",
            "hardware": {
                "memory_mb": 2048,
                "num_cpu_cores_per_socket": 1,
                "num_cpus": 1,
                "scsi": "paravirtual"
            },
            "hostname": "xxx",
            "is_template": false,
            "linked_clone": false,
            "name": "vsdainceptionvm",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "name": "vlan12"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": null,
            "use_instance_uuid": false,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_customization_timeout": 3600,
            "wait_for_ip_address": false,
            "wait_for_ip_address_timeout": 300
        }
    },
    "msg": "Failed to import the required Python library (PyVmomi) on xxx's Python /usr/local/homebrew/opt/python@3.9/bin/python3.9. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```
