### ISSUE TITLE
Integrate a revision control local to the hosts for configuration backup

### ISSUE THREAD

**Issue by dcadint-design** [ansible/ansible#72542]
##### SUMMARY

Integration of an automated version control system into Ansible preferably on the managed host or alternatively from the ansible server.   Many people just think of version control systems for managing code but they can and should also be used for configuration files including system configuration.  I use RCS because checking in and out of files doesn't change their permissions as it does with other version control systems and it allows for quick use of rcsdiff to see what changed.  Ansible should have an option to integrate version control down at the system level and have a directive to backup any files being changed automatically to this version control system. While Devops teams should be using a version control system for playbooks, rolls and collections this doesn't backup the configurations already on the systems or take into account any changes which may have been done to those configurations outside of ansible.  

##### ISSUE TYPE
- Feature Idea
- add integration of a Revision Control Systems on each host into Ansible or some kind of verson control that maybe pulls previous and new versions of configurations down into the facts for each system to allow before and after comparisons should an issue with a configuration arise.  
Ansible could install RCS on each host and create RCS subdirectories where version control files will be placed.  A simple directive with change title in playbooks could automatically backup any system configuration files before they are changed if the version is not already checked into RCS previously and then after the change is made the configuration file should update the RCS .

##### COMPONENT NAME

cfg_version_control

##### ADDITIONAL INFORMATION

In the past I have used RCS as the means to manage configuration file versions on each system in an environment.  This method was passed down to me by one of my mentors.  Most people either just change configuration files on systems or they may make a backup copy with a date stamp postfix.  However there are many issues with this method, such as some services run what ever configuration files found in a directory even those with postfix dates only meant for backup.  We have had issues with Ansible roles for security hardening which have broken access to systems and without a local backup of what configuration files looked like previously it can be hard to figure out what changed that broke a system. Some of our devops team have used the file module to make backup copies of the files however when they did this for /etc/sysconfig we found that Redhat still runs the files that merely have a postfix, running multiple versions of the same configuration the end result being a random overwrite of configurations.    This feature is needed to manage configuration changes and to more quickly identify the cause of an issue.

```yaml
  cfgversion:
     comment:  Description of changes being implemented to be used in the comment for the revision check in
     validate: true  <!--- run a check to see if existing versions of configuration files to be changed match whats in version control>
         checkin: current
     when: ansible_cfgversion == "nosync"    <! --- if validation finds changes not checked into version control check them in>
         
         checkin: revert
     when: ansible_cfgversion == "nosync"    <! --- if validation finds changes not checked into version control revert to checked in>

     checkin: true  <!--- check-in new configuration changes made by this playbook into revision control
     getversions:  true  <!--- get version information and store in facts for the managed host 
```
