### ISSUE TITLE
Multiple validate commands for copy/template

### ISSUE THREAD

**Issue by sabik** [ansible/ansible#72561]
##### SUMMARY

Support multiple `validate` commands on the copy, template and similar tasks; all commands must succeed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible.builtin.copy, ansible.builtin.template

##### ADDITIONAL INFORMATION

This would be useful if different command-line utilities need to be combined to check different aspects of the file to be deployed.

A possible syntax would be a list of commands, by analogy with specifying a list of conditions for a `when` clause.

```yaml
copy:
  src: ...
  dest: ...
  validate:
  - validation_command_one %s
  - validation_command_two --infile=%s
```

**Workaround**

Currently, the validate parameter only accepts a single command, and only substitutes `%s` once, so running two commands in the validation means manually using a shell and passing `%s` as `$1`, which is finicky and potentially unsafe:

```yaml
copy:
  src: ...
  dest: ...
  validate: >-
    bash -c
    'validation_command_one "$1"
     && validation_command_two "--infile=$1"'
    - %s
```
