### ISSUE TITLE
Include MIME info in find result

### ISSUE THREAD

**Issue by apapsch** [ansible/ansible#72585]
##### SUMMARY
The find module registers a result with a `files` key, which is accompanied with the note "see stat module for full output of each dictionary". Stat module documents `get_mime` with a default value of `True`. Find result should also contain MIME type info.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
find

##### ADDITIONAL INFORMATION
Providing MIME info right away is more convenient. As it is now, all found files need to stat'ed separately again.

The following example uses a custom filter `executable_files`, which checks the `xusr` field of a file result. But it isn't enough, MIME type needs to be asserted as well. With MIME type missing in find_result, I need to `stat` all found files after the `find` task.

```yaml
- name: Find files in install dir
  find:
    paths:
      - "{{ prefix }}"
  register: find_result

- name: Find executable in found files
  set_fact:
    executables: "{{ find_result.files|executable_files }}"
```
