### ISSUE TITLE
ansible does not allow Azure Mysql Server with Version 8.0

### ISSUE THREAD

**Issue by jhoelzl** [ansible/ansible#72589]
##### SUMMARY
Only allows creating new Azure mysql server with version `5.6` or `5.7`. However, Microsoft also allows 8.0 when manually creating a server through the Azure portal. Supported versions: https://docs.microsoft.com/en-us/azure/mysql/concepts-supported-versions

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_mysqlserver
##### ANSIBLE VERSION

```paste below
2.9.11
```

##### CONFIGURATION

```paste below
/opt/ansible/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
```

##### OS / ENVIRONMENT

Azure Cloud Shell

##### STEPS TO REPRODUCE

```yaml

tasks:

    - name: Create MySQL Server
      azure_rm_mysqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: "{{ location }}"
        version: 8.0
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 5120
```

##### ACTUAL RESULTS

```paste below

```
