### ISSUE TITLE
Collections are not being installed with `ansible-galaxy install -r requirements.yml`

### ISSUE THREAD

**Issue by tom10271** [ansible/ansible#72596]
##### SUMMARY

```yml
---
roles:
    -
        name: Aplyca.S3fs
    -
        name: badpacketsllc.aws_cli
        version: v1.0.3
    -
        name: geerlingguy.nodejs
        version: 5.1.1
    -
        name: geerlingguy.filebeat
        version: 3.0.2
    -
        name: geerlingguy.pip
        version: 2.0.0

collections:
    -   name: nginxinc.nginx_core
        version: 0.1.3
```

Result
```
ansible-galaxy install -r galaxy.yml -p ./roles
[WARNING]: - Aplyca.S3fs (master) is already installed - use --force to change version to unspecified
- badpacketsllc.aws_cli (v1.0.3) is already installed, skipping.
- geerlingguy.nodejs (5.1.1) is already installed, skipping.
- geerlingguy.filebeat (3.0.2) is already installed, skipping.
- geerlingguy.pip (2.0.0) is already installed, skipping.
```

This is my file and this is the command I run to install roles and collections.

`ansible-galaxy install -r galaxy.yml -p ./roles`

I don't see what is wrong in my file, here is the official doc.
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

```yml
---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
```

https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/collections_using.rst

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /Users/101-medialab-tomlo/.ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Jun 17 2018, 12:13:06) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/me/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/me/.ansible.cfg) = ['profile_tasks']
DEFAULT_STDOUT_CALLBACK(/Users/me/.ansible.cfg) = debug
DEFAULT_STRATEGY(/Users/me/.ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/Users/me/.ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ansible_mitogen/plugins/strategy']
DEPRECATION_WARNINGS(/Users/me/.ansible.cfg) = False
ENABLE_TASK_DEBUGGER(/Users/me/.ansible.cfg) = True
HOST_KEY_CHECKING(/Users/me/.ansible.cfg) = False
INTERPRETER_PYTHON(/Users/me/.ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

macOS Catalina 10.15.2 (19C57)
