### ISSUE TITLE
Bad 'import with context' in Jinja2 template

### ISSUE THREAD

**Issue by reporter4u** [ansible/ansible#72615]
##### SUMMARY

Since Ansible version 2.9.14  and 2.9.15 the behaviour of template module has changed ignoring the Jinja2 Context Behavior 'with context' directive importing a macro. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

jinja2 version
```
Version: 2.10
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: MarkupSafe
Required-by: 
```

##### CONFIGURATION

No output printed out.

##### OS / ENVIRONMENT

Centos 7/Debian 10

##### STEPS TO REPRODUCE

Playbook and role's structure:

role1/defaults/main.yml

```yaml
---
var1: "Alfa"
var2: "Bravo"
```

role1/tasks/main.yml
```yaml
---
- name: Template
  template:
    src: "templates/t1.j2"
    dest: "/tmp/file.txt"
```

role1/templates/macro.j2
```yaml
{% macro print_context_vars(value) %}
var1: {{ var1 }}
var2: {{ var2 }}
var3: {{ value }}
{% endmacro %}
```

role1/templates/t1.j2
```yaml
{% set var1 = "Delta" %}
{% set var2 = "Charlie" %}
{% set var3 = "Tango" %}
{% from 'macro.j2' import print_context_vars with context %}
{{ print_context_vars(var3) }}
```

pb.yml:
```yaml
---
- hosts: localhost
  roles:
    - role1
```

##### EXPECTED RESULTS

I espected the file `file.txt` templated as shown below and as it was up to ansible 2.9.13 version.

```paste below
ansible-playbook pb.yml
cat /tmp/file.txt 
var1: Delta
var2: Charlie
var3: Tango
```

##### ACTUAL RESULTS

It seems since ansible 2.9.14 version up to 2.9.15 that jinja2 'with context' is ignored

```paste below
ansible-playbook pb.yml
cat /tmp/file.txt 
var1: Alfa
var2: Bravo
var3: Tango
```
