### ISSUE TITLE
Implement no_log as filter for hiding selected fields from output

### ISSUE THREAD

**Issue by ilyaevseev** [ansible/ansible#72613]
##### SUMMARY

Hide passwords from "diff" output by "no_log" filter applied to selected fields.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

Filters

##### ADDITIONAL INFORMATION

Consider following snippet:

```yaml
 vars:
    dbusers:
        - bgates: '{{ VAULT_BGATES_PASSWORD }}'
        - emusk:  '{{ VAULT_EMUSK_PASSWORD  }}'

  tasks:
    - name: Create db users
      db_user:
          user:     "{{ item.key }}"
          password: "{{ item.value }}"
      with_items:   "{{ dbusers }}"
      no_log: True
```

Result with "no_log" is too quiet:
```
TASK [Create db users] ************************************************
changed: [dbserver] => (item=None)
changed: [dbserver] => (item=None)
changed: [dbserver]
```

Result without "no_log" is insecure:
```
TASK [Create db users] ************************************************
changed: [dbserver] => (item={'key': 'bgates', 'value': 'OS2rockz'})
changed: [dbserver] => (item={'key': 'emusk', 'value': 'm@rs@tt@ckz!'})
```

Wanted solution:
```yaml
  tasks:
    - name: Create db users
      db_user:
          user:     "{{ item.key }}"
          password: "{{ item.value | no_log }}"
      with_items:   "{{ dbusers }}"
```

Wanted result:
```
TASK [Create db users] ************************************************
changed: [dbserver] => (item={'key': 'bgates', 'value': '****'})
changed: [dbserver] => (item={'key': 'emusk', 'value': '****'})
```
