### ISSUE TITLE
Usability: Allow for custom failure messages on task or block

### ISSUE THREAD

**Issue by bwoebi** [ansible/ansible#72632]
##### SUMMARY

Provide a succint way to add a custom (well visible) failure message to an ansible task.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
task executor

##### ADDITIONAL INFORMATION

While it currently is possible to use a register with `failed_when: false`, followed by an extra `fail` task with a when conditional, this often feels daunting and adds a quite redundant line in the output for that skipped `fail` task (unless you go the lengths to filter these out then) in addition to making the original task always appear as `ok`. The alternative is a `block` with `rescue` which is not much more accessible ...
There are enough times I wanted to add additional information "if this task fails, check this or that first" to be displayed alongside failures, in particular for maintenance books running against single/few targets.

Proposal: Add a new optional `failed_msg` as base parameter to task declaring blocks.

```yaml
- name: Assert elasticsearch is not running
  shell: jps | grep -iq elasticserach
  failed_msg: An elasticsearch process is still running - use the decommission-elasticsearch playbook first.
```

or:

```yaml
- failed_msg: Updating boot config failed. System might be UNBOOTABLE. Ensure the /boot contents are correct and update-grub has been successful.
  block:
   - name: Copy the new boot partition contents
     shell: mv /tmp/install/boot/* /boot/

   - name: Update grub-configuration
     shell: update-grub
```

Output could be an extra line below the JSON of the task result message line. It should just not be integrated in the JSON blob itself and this will probably reduce visibility drastically with big one-line failures.
