### ISSUE TITLE
allow to assign a dictionary to itself when used with combine filter

### ISSUE THREAD

**Issue by Raffaello** [ansible/ansible#72646]
##### SUMMARY

combine filter cannot be assigned to the same hash key that is applied, basically on itself,  to just subsite a part of a dictionary. Would be nice to have this feature, because at the moment is achievable only changing to `hash_behavior=merge` that is deprecated and "unwanted"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

combine filter to give the possiblity to do something like

##### ADDITIONAL INFORMATION

the example above or similar, when using the destination key as an input, independently from combine filter, go on recursive loop error, when should not be the case. 

(It could be a bug)

```yaml
---
defaultRoleAVarsDict:
  a: "a"
  b: "c"
---
roles:
  role: roleA
  vars:
    defaultRoleAVarsDict: "{{ defaultRoleAVarsDict | combine({'b':'be'}) }}"
```
