### ISSUE TITLE
Variables passed to dependencies do not duplicate roles past one level deep

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#72641]
##### SUMMARY
Using meta dependencies, I depend two top-level roles on a second-level role. The second level role depends on a third-level role, passing variables that change with its own invocation. The third-level role is only executed once, with the last defined variable set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Variable management

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
```

##### CONFIGURATION
```yaml
# ./roles/A/meta/main.yml
---
dependencies:
- role: C
  vars:
    role_c_param: from A

# ./roles/B/meta/main.yml
---
dependencies:
- role: C
  vars:
    role_c_param: from B

# ./roles/C/tasks/main.yml
---
- debug:
    msg: "role C param: {{ role_c_param }}"

# ./roles/C/meta/main.yml
---
allow_duplicates: true
dependencies:
- role: D
  vars:
    role_d_param: "{{ role_c_param }}"

# ./roles/D/tasks/main.yml
---
- debug:
    msg: "role D param: {{ role_d_param }}"

# ./hosts
---
all:
  hosts:
    localhost: {}

# ./playbook.yml
---
- hosts: all
  roles:
  - A
  - B
```

##### OS / ENVIRONMENT
Linux, but it probably does not matter.

##### STEPS TO REPRODUCE
see above

##### EXPECTED RESULTS
I expect role D to be run twice, once with 'from A' and once with 'from B' output.

##### ACTUAL RESULTS
Role D is run once, with the 'from B' output.

Note: adding or removing 'allow_duplicates' seems to make no difference, either in role D, or role C, or both.
