### ISSUE TITLE
ansible-galaxy install collections from multiple server

### ISSUE THREAD

**Issue by Gianlu** [ansible/ansible#72656]
##### SUMMARY
We installed an on-premise galaxy with galaxy-ng for our collections. We wrote requirements.yml file for our playbooks and listed ansible and community collections as dependencies in galaxy.yml.
So in the requirements.yml file we have only our collections and in galaxy.yml we have the other collections.
We also wrote an ansible.cfg in playbook directory where we configure our sources.
When we run `ansible-galaxy collection install -r collections/requirements.yml  -vvv`, our collection is downloaded from our galaxy but not official collections because they are searched in our galaxy and not in galaxy.ansible.com.
 - ansible.cfg
```ini
[galaxy]
server_list = galaxy-ng, release_galaxy

[galaxy_server.galaxy-ng]
url=https://galaxy.internal.lcl/api/galaxy/content/community/
token=<our token>

[galaxy_server.release_galaxy]
url=https://galaxy.ansible.com/
```
 - requirements.yml
```yaml
---
collections:
  - our.ansible_stuff
```
 - galaxy.yml
```yaml
### REQUIRED

# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: our

# The name of the collection. Has the same character restrictions as 'namespace'
name: ansible_stuff

# The version of the collection. Must be compatible with semantic versioning
version: 0.0.15

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
- John Doe1
- John Doe2


### OPTIONAL but strongly recommended

# A short summary description of the collection
description: your collection description

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
- GPL-2.0-or-later

# The path to the license file for the collection. This path is relative to the root of the collection. This key is
# mutually exclusive with 'license'
license_file: ''

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: [icinga2, redis, vm_management]

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies:
  ansible.windows: '*'
  chocolatey.chocolatey: '*'
  community.mysql: '*'
  community.general: '*'
  ansible.netcommon: '*'

# The URL of the originating SCM repository
repository: https://btdebgit.internal.lcl/ansible/collections/our.ansible_stuff

# The URL to any online docs
documentation: http://docs.example.com

# The URL to the homepage of the collection/project
homepage: http://example.com

# The URL to the collection issue tracker
issues: http://example.com/issue/tracker
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible-galaxy

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /home/user1/btdebgit/ansible/mol_playbooks/ansible.cfg
  configured module search path = [u'/home/user1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
GALAXY_SERVER_LIST(/home/user1/btdebgit/ansible/mol_playbooks/ansible.cfg) = [u'galaxy-ng', u'release_galaxy']
```

##### OS / ENVIRONMENT

debian 10.5

##### STEPS TO REPRODUCE

- deploy a custom galaxy-ng
- upload a collection to galxy-ng
- put collections from galxy.ansible.com as dependencies in galaxy.yml
- put the custom collection as a playbook dependency in requirements.yml
- install via ansible-galaxy

```yaml

```

##### EXPECTED RESULTS

All collections are downloaded and installed

##### ACTUAL RESULTS

```paste below
ansible-galaxy 2.10.3
  config file = /home/user1/btdebgit/ansible/mol_playbooks/ansible.cfg
  configured module search path = [u'/home/user1/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-galaxy
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
Using /home/user1/btdebgit/ansible/mol_playbooks/ansible.cfg as config file
Reading requirement file at '/home/user1/btdebgit/ansible/mol_playbooks/collections/requirements.yml'
Starting galaxy collection install process
Found installed collection ansible.windows:1.0.0 at '/home/user1/.ansible/collections/ansible_collections/ansible/windows'
Found installed collection chocolatey.chocolatey:1.0.2 at '/home/user1/.ansible/collections/ansible_collections/chocolatey/chocolatey'
Process install dependency map
Opened /home/user1/.ansible/galaxy_token
Processing requirement collection 'our.ansible_stuff'
Collection 'our.ansible_stuff' obtained from server galaxy-ng https://galaxy.intenal.lcl/api/galaxy/content/community/
Processing requirement collection 'ansible.netcommon' - as dependency of our.ansible_stuff
Collection 'ansible.netcommon' is not available from server galaxy-ng https://galaxy.internal.lcl/api/galaxy/content/community/
ERROR! Failed to find collection ansible.netcommon:*
```
