### ISSUE TITLE
ansible_mount does not detect ZFS mounts on Linux

### ISSUE THREAD

**Issue by radek-sprta** [ansible/ansible#72658]
##### SUMMARY
The setup module does not return info about ZFS mounts in ansible_mounts.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/module_utils/facts/hardware/linux.py`

I believe it is caused by the following line, because zfs mount names do not start with slashes:

```python
            if not device.startswith(('/', '\\')) and ':/' not in device or fstype == 'none':
                continue
```

##### ANSIBLE VERSION

```ansible 2.9.15
  config file = /home/sprta/.ansible.cfg
  configured module search path = ['/home/sprta/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 20 2020, 17:41:41) [GCC]
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/sprta/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/sprta/.ansible.cfg) = ~/.cache
CACHE_PLUGIN_TIMEOUT(/home/sprta/.ansible.cfg) = 86400
DEFAULT_GATHERING(/home/sprta/.ansible.cfg) = smart
INTERPRETER_PYTHON(/home/sprta/.ansible.cfg) = auto_silent
```

##### OS / ENVIRONMENT

```
         Icon name: computer-vm
           Chassis: vm
    Virtualization: xen
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 4.19.123
      Architecture: x86-64
```

##### STEPS TO REPRODUCE

Run the following command against a Linux host with ZFS mounts

```
ansible all -m setup -a "filter=ansible_mounts" -i <linux_zfs_host>,
```

##### EXPECTED RESULTS

```
linux_zfs_mount | SUCCESS => {
    "ansible_facts": {
        "ansible_mounts": [
           {
                <mounts_details>
           }
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_mounts",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    }
}
```

##### ACTUAL RESULTS

```
linux_zfs_mount | SUCCESS => {
    "ansible_facts": {
        "ansible_mounts": []
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "fact_path": "/etc/ansible/facts.d",
            "filter": "ansible_mounts",
            "gather_subset": [
                "all"
            ],
            "gather_timeout": 10
        }
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/facts/hardware/linux.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/hardware/linux.py)
* [`lib/ansible/module_utils/facts/system/python.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/system/python.py)
* [`lib/ansible/module_utils/facts/virtual/sunos.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/virtual/sunos.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/module_utils/facts/hardware/linux.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/hardware/linux.py)
* [`lib/ansible/module_utils/facts/hardware/sunos.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/hardware/sunos.py)
* [`lib/ansible/module_utils/facts/system/python.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts/system/python.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andras-tim** [comment]
I got this problem too... :frowning_face: 

### My original code (doesn't work w/ ansible 2.9):

``` yaml
- name: 'Re-gather ansible_mounts'
  setup:
    filter: ansible_mounts

- name: "Getting current targets of mounts"
  set_fact:
    current_mounted_targers: "{{ ansible_mounts | map(attribute='mount') | list }}"
```

### I came up with a workaround with `findmnt --real --list -n`:

``` yaml
- name: 'Re-gather ansible_mounts'
  shell:
    argv: [ 'findmnt', '--list', '--real', '-n', '-o', 'TARGET' ]
  register: findmnt_results

- name: "Getting current targets of mounts"
  set_fact:
    current_mounted_targers: "{{ findmnt_results.stdout_lines }}"
  ignore_errors: "{{ ansible_check_mode }}"
```
