### ISSUE TITLE
unable to install collections from requirements.yml file

### ISSUE THREAD

**Issue by chrobotm** [ansible/ansible#72675]
##### SUMMARY
Ansible collections don't seem to be installing from requirements.yml using ansible-galaxy install -r requirements.yml

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
2.9.6
```

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

requirements.yml file with the following content

```
---

collections:
  - name: devsec.hardening
    source: https://galaxy.ansible.com
```

running `ansible-galaxy install -r requirements.yml` doesn't install the collections

running `ansible-galaxy collection install -r requirements.yml` works fine
##### EXPECTED RESULTS

Collections install

##### ACTUAL RESULTS

collections don't install
