### ISSUE TITLE
git module, force=yes -- "/usr/bin/git fetch --tags origin" is not forced

### ISSUE THREAD

**Issue by praiskup** [ansible/ansible#72676]
##### SUMMARY

We are push-forcing certain "floating" git tags that are used for automatic checkouts by ansible.
With the following setup:

```yaml
  - name: VM provisioning git
    git: repo=git://local-some-repo.com/vm-provisioning.git
        version={{ instance_type }}-instance
        dest=/etc/resallocserver/vm-provisioning
        force=yes
    become: yes
    become_user: resalloc
```

I get the following error:

    fatal: [10.8.29.170]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git",
    "fetch", "--tags", "origin"], "msg": "Failed to download remote objects and
    refs:  From git://.../vm-provisioning\n   abaf 473..533b0be  master         ->
    origin/master\n ! [rejected]        devel-instance -> devel-instance  (would
    clobber existing tag)\n"}

I'd expect that `--force` is used for `git fetch --tags` when there's
`force=yes` specified in args.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.builtin.git

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /home/controller/.ansible.cfg
  configured module search path = ['/home/controller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### OS / ENVIRONMENT

Fedora 33, x86_64.

##### EXPECTED RESULTS

The local copy of "upstream" updated tag is also updated locally with force=yes.
