### ISSUE TITLE
Custom content-type header is interpolated by body_format which results in an error

### ISSUE THREAD

**Issue by luckyinfil** [ansible/ansible#72670]
##### SUMMARY

When using the URI module, entering a custom "Accept" and "Content-Type" header results in an error: 'value of body_format must be one of: form-urlencoded, json, raw, got: application/vnd.vmware.horizon.manager.system.config.smtp+json'
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

URI module

##### ANSIBLE VERSION

```paste below
[gtiicsviemccd@iaasn00135617 vaf]$ ansible 2.9.6
  config file = /home/ansible.cfg
  configured module search path = [u'/home/library', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Redhat 

##### STEPS TO REPRODUCE

```yaml
- name: "Set SMTP configuration"
  uri:
    url: "https://{{ vidm_hostname|lower }}SAAS/jersey/manager/api/system/config/smtp"
    validate_certs: "{{ http_validate_certs }}"
    method: PUT
    headers:
      Accept: "application/vnd.vmware.horizon.manager.system.config.smtp+json}"
      Content-Type: "application/vnd.vmware.horizon.manager.system.config.smtp+json"
    body: 
      host: "{{ smtp_address }}"
      port: 25
    status_code: [200]
  delegate_to: localhost
```

##### EXPECTED RESULTS

URI module runs successfully with Accept and content-type headers as application/vnd.vmware.horizon.manager.system.config.smtp+json

##### ACTUAL RESULTS

the body_format field is replaced with the "content-type" header and doesn't accept the custom header

```paste below
fatal: [ -> localhost]: FAILED! => changed=false
  invocation:
    module_args:
      body:
        password: 
        username: admin
      body_format: application/vnd.vmware.horizon.manager.system.config.smtp+json
      follow: false
      follow_redirects: safe
      force: false
      force_basic_auth: false
      headers:
        Accept: application/vnd.vmware.horizon.manager.system.config.smtp+json
      http_agent: ansible-httpget
      method: POST
      return_content: false
      status_code:
      - 200
      timeout: 30
      url: https:///SAAS/API/1.0/REST/auth/system/login
      use_proxy: true
      validate_certs: false
  msg: 'value of body_format must be one of: form-urlencoded, json, raw, got: application/vnd.vmware.horizon.manager.system.config.smtp+json'

```
