### ISSUE TITLE
gce module not support new zone in asia.

### ISSUE THREAD

**Issue by ingramchen** [ansible/ansible#7270]
```
  tasks:

    - name: Launch instances
      gce:
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          zone: "asia-east1-b"
      register: gce
```

both new zone `asia-east1-a` and `asia-east1-b` are not supported.
