### ISSUE TITLE
In order to use Ansible I need to `kill -s HUP x` where x is the PID of a `/bin/sh -c /usr/bin/python3 && sleep 0` command

### ISSUE THREAD

**Issue by dnk8n** [ansible/ansible#72719]
##### SUMMARY
I have found that ansible hangs (see https://github.com/dnk8n/reproduce-ansible-issue-72719 for full steps on reproducible environment)

I have to manually ssh into the machine, execute `ps aux | grep '/bin/sh -c /usr/bin/python3 && sleep 0'` to find the command causing the hanging and `kill -s HUP <pid>` in order for provisioning to proceed.

I then get the following warnings, but the playbook proceeds and my AMI is created (use of Packer).

```
    amazon-ebs: TASK [Gathering Facts] *********************************************************
    amazon-ebs: [WARNING]: Unhandled error in Python interpreter discovery for host default:
    amazon-ebs: Expecting value: line 1 column 1 (char 0)
    amazon-ebs: ok: [default]
    amazon-ebs: [WARNING]: Platform linux on host default is using the discovered Python
    amazon-ebs: interpreter at /usr/bin/python3, but future installation of another Python
    amazon-ebs: interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen
    amazon-ebs: ce_appendices/interpreter_discovery.html for more information.
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dnk8n/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```

```
packer --version
1.6.5
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

See repo for further context. I am using packer against AWS EC2 instance (see link to repo in summary).

```yaml
---
- name: Ensure system is ready and up-to-date
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Wait for apt list lock (Known to cause issues sometimes)
      raw: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt list lock.' && sleep 10; done
    - name: Ensure packages are updated
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes

- name: Ensure firewall is set up
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443
    firewall_allowed_udp_ports: []
    firewall_disable_ufw: true
    firewall_enable_ipv6: false
  roles:
    - geerlingguy.firewall

- name: Ensure Docker is installed
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    docker_package_state: present
    docker_package: docker-ce=5:19.03.13~3-0~ubuntu-focal
    docker_users:
      - "{{ username }}"
    docker_install_compose: true
    docker_compose_version: 1.27.4
  roles:
    - geerlingguy.docker

- name: Ensure Docker Python library is installed
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  vars:
    pip_executable: pip3
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
        state: present
        version: 4.4.0
  roles:
    - geerlingguy.pip
```

##### EXPECTED RESULTS

I expect no manual intervention. The command produced is malformed. Even if running that against shell manually, it enters python interpreter.

##### ACTUAL RESULTS

```paste below

```
