### ISSUE TITLE
add special variable containing the current playbook file

### ISSUE THREAD

**Issue by SimonHeimberg** [ansible/ansible#72712]
##### SUMMARY

add a magic variable containing the name of the current playbook file.

Currently there is no simple way to get this.

There are other similar [magic variables](https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#magic-variables):
* The magic variable *playbook_dir* is the directory containing the playbook.
* The magic variable *ansible_play_name* is the name of the current play (not playbook), see https://github.com/ansible/ansible/issues/57361
* Infos about roles in *ansible_role_name*, *ansible_parent_role_names*, *ansible_parent_role_paths*.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- maybe in lib/ansible/vars/manager.py

##### ADDITIONAL INFORMATION

work-around from https://iautomatelinux.wordpress.com/2019/03/29/ansible-get-current-playbook-name/, improved

```yaml
- hosts: all
  run_once: true
  tasks:
    - debug:
        var: playbookName
      vars:
        cmdLine: "{{ lookup('file', '/proc/self/cmdline') }}"
        cmdLineAdapted: "{{ cmdLine | replace('-i\u0000', '-i ') | regex_replace('--inventory[^\u0000]*\u0000', '-i ') }}" # merge -i xxx to one arg, to allow skipping
        matchingArgs: "{{ cmdLineAdapted.split('\u0000') | select('match','[^-@].*[.]y[a]*ml$') | list }}" # keep yaml files, but skip leading @ (for -e @x/y/z.yml) and "-" (for -i inv/x.yml)
        playbookName: "{{ matchingArgs | last | basename }}"
```
