### ISSUE TITLE
systemd module fails with `Could not find the requested service XXXX: host` in check mode

### ISSUE THREAD

**Issue by ctrlaltdel** [ansible/ansible#72721]
##### SUMMARY
systemd service in check mode fails with `Could not find the requested service XXXX: host`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
systemd

##### ANSIBLE VERSION

```paste below
$ ~/.local/bin/ansible-playbook --version
ansible-playbook 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible-playbook
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
$ ~/.local/bin/ansible-config dump --only-changed
$ 
```

##### OS / ENVIRONMENT

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Bionic Beaver (development branch)
Release:        18.04
Codename:       bionic
```

Ansible was installed like this.

```console
$ pip3 install --upgrade ansible
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - package:
        name: squid
        state: present

    - copy:
        dest: /etc/squid.conf
        content: |
          blah
      notify: restart squid

  handlers:
    - name: restart squid
      service:
        state: restarted
        name: squid
```

##### EXPECTED RESULTS

Here's the result using the distro-provided ansible release (2.5.1).

```console
$ ansible-playbook --version
ansible-playbook 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
$ ansible-playbook --check site.yml 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [package] *************************************************************************************************************************
changed: [localhost]

TASK [copy] ****************************************************************************************************************************
changed: [localhost]

RUNNING HANDLER [restart squid] ********************************************************************************************************
changed: [localhost]

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0   

```

##### ACTUAL RESULTS

```console
$ ~/.local/bin/ansible-playbook --check site.yml 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
ok: [localhost]

TASK [package] *************************************************************************************************************************
changed: [localhost]

TASK [copy] ****************************************************************************************************************************
changed: [localhost]

RUNNING HANDLER [restart squid] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service squid: host"}

NO MORE HOSTS LEFT *********************************************************************************************************************

PLAY RECAP *****************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

Same output with `-vvv` available here: https://gist.github.com/ctrlaltdel/0935d549fe2d08add4a0157ab1d2c32f

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/systemd.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/systemd.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
It sounds as though you are running in check mode, but `squid` has never been installed.  As a result, when the attempt to restart the service happens, the task fails, as it cannot determine the state.

In order to properly utilize check mode in this circumstance, you will need to make adjustments to your playbook to handle such a circumstance.

Potentially, by use of `failed_when` to prevent the error, or by using `when` to skip the restart task.

Something like:

```
tasks:
    - package:
        name: squid
        state: present
      register: squid_install

handlers:
    - name: restart squid
      service:
        state: restarted
        name: squid
      register: squid_restart
      failed_when: squid_restart is failed and squid_install is not changed and not ansible_check_mode
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
