### ISSUE TITLE
Option to ignore error if notifying a handler fails

### ISSUE THREAD

**Issue by th365thli** [ansible/ansible#72726]
##### SUMMARY

Would like an option to ignore the error triggered if a notify can't find the handler it's specifying

![image](https://user-images.githubusercontent.com/3444224/100162429-988d7b80-2e81-11eb-9ace-c0f0f99f0454.png)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Handlers

##### ADDITIONAL INFORMATION

We're currently developing Ansible operators for Kubernetes/Openshift. We use handlers/notify to push status updates to k8s. However, we also want our playbooks to be flexible enough to be used outside of a k8s context with minimal alteration. Therefore, the ansible-operator contains a generic handlers folder and we reference it in our playbooks.

![image](https://user-images.githubusercontent.com/3444224/100162846-7f38ff00-2e82-11eb-9249-3b817fdd9026.png)

Our hope is that even if we take our playbooks outside this operator and run it, it would still work even if the generic handlers folder doesn't exist. We want our notification structure to be pick up handlers if they exist or just quietly ignore errors if they don't.

Alternatives are to do a check if the handler task exists before notifying it, but that's cumbersome and costly. We tried ignore_errors as shown below but it does not work. 

```yaml

 - set_fact:
        k8s_status: dataset allocated successfully
    changed_when: true
    notify: Notify Kubernetes
    ignore_errors: yes

```
