### ISSUE TITLE
get_url does not update mode if desination file exists

### ISSUE THREAD

**Issue by Bilge** [ansible/ansible#72723]
##### SUMMARY

Mode is not updated by `get_url` if desination file already exists.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

Ubuntu 18.04.5 LTS

##### STEPS TO REPRODUCE

```yaml
- name: Foo
  get_url:
    url: foo
    dest: bar
    mode: +x
```

##### EXPECTED RESULTS

`+x` will be set on `dest`, even if `bar` already exists.

##### ACTUAL RESULTS
When desination (`bar`) already exists, mode is ignored (not synchronised).

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Bilge: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/get_url.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aminvakil** [comment]
I don't think this is a bug, the module checks and if the file was present and `force: False` there is no need to download the file again and overwrite it.

I think if you set `force` to `True` it will download again and set your chosen mode then.

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-force: 

> If no, the file will only be downloaded if the destination does not exist.

**Comment by aminvakil** [comment]
I've also found this on module:
https://github.com/ansible/ansible/blob/0fa1cd88ce57167292803e9257fe2ed50cb3e1e0/lib/ansible/modules/get_url.py#L554-L562

If you pass the `checksum` option to the module, it will compare checksum of the present file with the file given by url and will force download it if they differ.

I don't know if it's suitable for your situation or not, but it may be given the fact that you download the file twice.

**Comment by Bilge** [comment]
I don't know why you think I'm "downloading it twice", I never said that, but let's get one thing absolutely clear: **this *is* a bug**.  Yes, I understand that if it has already been downloaded it is not going to be downloaded again, but that has *nothing to do with the mode* . The whole point is that Ansible keeps the system consistent with the idempotent configuration. Ignoring the mode is inconsistent with its own design constraints.

**Comment by aminvakil** [comment]
@Bilge You may be right, I'm not a maintainer, just another ansible user trying to help.

If you don't want to use `force` for any reason, you're right again to do that.

But from **my point of view** this is not a bug.

**Comment by samdoran** [comment]
I can see both sides of this argument. I'll have to look more closely at the module to see if the file permission changing code was purposefully or inadvertently skipped based on the existence of the file.

If this is a bug and we change the behavior, it may not be backportable since it is a change in behavior.

**Comment by sivel** [comment]
I've tested this on various versions, and cannot reproduce.  Here is my reproducer:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - file:
        path: ./ip.json
        state: absent

    - get_url:
        url: https://httpbin.org/ip
        dest: ./ip.json

    - stat:
        path: ./ip.json
      register: s1

    - get_url:
        url: https://httpbin.org/ip
        dest: ./ip.json
        mode: +x

    - stat:
        path: ./ip.json
      register: s2

    - debug:
        msg: 's1.stat.mode={{ s1.stat.mode }} s2.stat.mode={{ s2.stat.mode }}'

    - assert:
        that:
          - s1.stat.mode != s2.stat.mode
          - s1.stat.checksum == s2.stat.checksum
```

In all cases I get:

```
    "msg": "s1.stat.mode=0644 s2.stat.mode=0755"
```

The above shows that the mode does change even when the file does already exist.

If you are still having problems with currently supported versions, please open a new issue with a reproducer similar to the one I have provided.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
