### ISSUE TITLE
get_url fails with correct checksum

### ISSUE THREAD

**Issue by overratedpro** [ansible/ansible#72734]
##### SUMMARY

Specified correct checksum with correct sha-type prefix. Received a failed-checksum error, quoting both checksum values (the original supplied value and the computed one), being identical. Still the task failed.
Also, if downloading the file manually, the checksum is identical, as well.
What is more, tried downloading other files, with the above result. Changing the checksum type to `sha256` and providing respective checksum, yields the same result, again with matching hash values.
Tried using different values for the `tmp_dest` attribute, using different parent image (alpine:3.12), all to no avail.

Please note, the URL in question (see below) is subject to content change, with respective updates to the hash values (in https://updates.jenkins.io/current/update-center.json). During my tests that has not occurred, but obviously could, especially after a while, hence the remark about double-checking the checksum there.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

get_url (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html)

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
(empty)
```

##### OS / ENVIRONMENT

Docker (adoptopenjdk/openjdk11:jdk-11.0.9_11-alpine)

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:
    - get_url:
        checksum: 'sha1:999d2bb0c8897566a5aeff1ff9b51957ce80f3ce'
        dest: /tmp/a.hpi
        url: 'https://updates.jenkins.io/download/plugins/antisamy-markup-formatter/2.1/antisamy-markup-formatter.hpi'
```

##### EXPECTED RESULTS

file is downloaded with verified checksum

##### ACTUAL RESULTS

```
task failed
```

```paste below
fatal: [localhost]: FAILED! => {"changed": true, "checksum_dest": null, "checksum_src": "999d2b0bc8897566a5aeff1ff9b51957ce08f3ce", "dest": "/var/jenkins_home/plugins/antisamy-markup-formatter.hpi", "elapsed": 2, "msg": "The checksum for /var/jenkins_home/plugins/antisamy-markup-formatter.hpi did not match 999d2bb0c8897566a5aeff1ff9b51957ce80f3ce; it was 999d2b0bc8897566a5aeff1ff9b51957ce08f3ce.", "src": "/root/.ansible/tmp/ansible-tmp-1606395500.6295028-86-11555614447921/tmpvbtu6hmw", "url": "https://updates.jenkins.io/download/plugins/antisamy-markup-formatter/2.1/antisamy-markup-formatter.hpi"}
```
