### ISSUE TITLE
Add "changes" to command and shell modules

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#72748]
##### SUMMARY
Currently the command and shell modules contain parameters for "creates" and "removes", but not for "changes". The last one could be used to make ansible aware of a native command updating a file and correctly representing the task as changed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/shell.py
lib/ansible/modules/command.py

##### ADDITIONAL INFORMATION

With this additional parameter the task changed output can be utilized much better to reflect actual changes and not report "false positives".
This will also enable notify to be used with command and shell modules.

Example usage:
```
- shell: gawk -i inplace '$5 >= 3071' /etc/ssh/moduli
  register: moduli
  changes: /etc/ssh/moduli
  notify:
   - restart sshd
```
