### ISSUE TITLE
run_once with strategy free

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#72747]
##### SUMMARY
The strategy free does not handle "run_once".

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/plugins/strategy/free.py

##### ADDITIONAL INFORMATION
This was already reported in 2016 in #15876, but the original author closed the issue, so this one got left behind.

any role starting with something like this being (the ansible version check is just an example) used in a "strategy: free" playbook:
```yaml
- name: "Check local ansible version >= {{ minimal_ansible_version }}"
  delegate_to: localhost
  vars:
    ansible_connection: local
  run_once: true
  assert:
    msg: "Ansible must be {{ minimal_ansible_version }} or higher"
    that:
      - ansible_version.string is version(minimal_ansible_version, ">=")
- raw: do-something
  register: DoSomethingElse
```

The logic for handling this task could be a conditional barrier, e.g. only get hit until no host has passed it. To handle this efficiently a virtual task could be added to the internal tasks queue that checks for the existence of a flag that the first task reaching the barrier sets. Basically a synchronization point that we can disable at runtime (through whatever host reached it first).
Or using two barriers one before and one after the run_once task, where reaching the 1st ensures only one continues and the 2nd releases both barriers and allows all tasks to continue while skipping the run_once task.
