### ISSUE TITLE
Add display_included_hosts option to default callback plugin

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#72752]
##### SUMMARY

It would be great if there would be the possibility for the default callback plugin to have a option like `display_included_hosts` to control to not show the included tasks on a ansible run. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
/lib/ansible/plugins/callback/default.py
lib/ansible/plugins/doc_fragments/default_callback.py

##### ADDITIONAL INFORMATION
It would minimize the log output generated by ansible and reduces our log income.

Currently you have a output like this:
```yaml
PLAY [testhosts] **************************************************************
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/root.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test1.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/test.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/test.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test2.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test3.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test4.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test5.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test6.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test7.yml for testhost.mydomain.local
included: /builds/superxxx/ansible/ansible/roles/users/tasks/users/test8.yml for testhost.mydomain.local
```
