### ISSUE TITLE
block + rescue + fail behaves differently in include_tasks

### ISSUE THREAD

**Issue by mishak87** [ansible/ansible#72781]
##### SUMMARY
Using block with rescue with fail inside include_tasks does not stop execution on failure when any_error_fatal is set. (tested on 2.9.10 2.9.15 2.10.3)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
include_tasks, import_tasks

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/home/mishak/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mishak/.venv/deployer/lib/python3.8/site-packages/ansible
  executable location = /home/mishak/.venv/deployer/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### STEPS TO REPRODUCE

```yaml
---
# hosts.yaml
all:
  hosts:
    l1: &l1
      ansible_connection: local
      ansible_host: localhost
    l2: *l1
    l3: *l1
---
# playbook.yaml
- hosts: all
  connection: local
  any_errors_fatal: true
  tasks:
    - include_tasks:
        file: rescue-tasks.yaml
        apply:
          any_errors_fatal: true
---
# tasks.yaml
- block:
    - name: Fail first
      command: "/bin/{{ 'false' if inventory_hostname == 'l1' else 'true' }}"
  rescue:
    - name: Unsuccessful installation
      fail:
        msg: Rollback

- debug: msg="oopsie"

```

##### EXPECTED RESULTS

no other tasks are executed after block task fails on first host

```

PLAY [all] ***************************************************************************

TASK [include_tasks] *****************************************************************
included: .../tasks.yaml for l1, l2, l3

TASK [Fail first] **************************************************************
changed: [l3]
fatal: [l1]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.001903", "end": "2020-12-01 22:35:28.440333", "msg": "non-zero return code", "rc": 1, "start": "2020-12-01 22:35:28.438430", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
changed: [l2]

TASK [Unsuccessful installation] *****************************************************
fatal: [l1]: FAILED! => {"changed": false, "msg": "Rollback"}

NO MORE HOSTS LEFT *******************************************************************

NO MORE HOSTS LEFT *******************************************************************

PLAY RECAP ***************************************************************************
l1                         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=1    ignored=0   
l2                         : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
l3                         : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

##### ACTUAL RESULTS

ooppsie is printed on hosts where block command has not failed despite any_error_fatal is set
Note  that tasks are also executed out of expected order. Raise is done after other tasks on l2 and l3 hosts finish.

```paste below

PLAY [all] ***************************************************************************

TASK [include_tasks] *****************************************************************
included: .../tasks.yaml for l1, l2, l3

TASK [Fail first] **************************************************************
changed: [l2]
fatal: [l1]: FAILED! => {"changed": true, "cmd": ["/bin/false"], "delta": "0:00:00.002985", "end": "2020-12-01 22:16:59.212573", "msg": "non-zero return code", "rc": 1, "start": "2020-12-01 22:16:59.209588", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
changed: [l3]

TASK [debug] *************************************************************************
ok: [l2] => {
    "msg": "oopsie"
}
ok: [l3] => {
    "msg": "oopsie"
}

TASK [Unsuccessful installation] *****************************************************
fatal: [l1]: FAILED! => {"changed": false, "msg": "Rollback"}

NO MORE HOSTS LEFT *******************************************************************

NO MORE HOSTS LEFT *******************************************************************

PLAY RECAP ***************************************************************************
l1                         : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=1    ignored=0   
l2                         : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
l3                         : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/import_tasks.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_tasks.py)
* [`lib/ansible/modules/include_tasks.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_tasks.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mishak87: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
Reproducer without `include_tasks`:
```yaml
- hosts: h1,h2,h3
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - block:
      - block:
          - name: Fail first
            command: "/usr/bin/{{ 'false' if inventory_hostname == 'h1' else 'true' }}"
        rescue:
          - name: Unsuccessful installation
            fail:
              msg: Rollback
      - block:
        - debug: msg="oopsie"
```

The issue is due to a bug in task lockstep in the linear strategy that results in tasks being incorrectly ordered. I am working on fixing the issue in https://github.com/ansible/ansible/pull/72856.
