### ISSUE TITLE
return value from import_task

### ISSUE THREAD

**Issue by Truth1984** [ansible/ansible#72787]
##### SUMMARY

Get variable from another function(file)
I often ended up with hundreds of lines of code in one file when using ansible, and I really hate that. I want to find a way to separate the method into different function calls or in separated files, but seems like ansible doesn't support that. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

```yaml
return:
  when?:
```

##### ADDITIONAL INFORMATION

call `host.yaml` first, and maybe pass some arguments to `func1.yaml`  (replace `100` with arguments)
then wait for `func1` to do some tasks,
the output of `func1` can be string / map / list / ...
and finally `host` will `register` the output and maybe pass the result as argument into another file like `func2`

example:

func1.yaml
```yaml
- name: echo result
  shell: echo 100
  register: shellvalue
- return: "ten"
  when: shellvalue["stdout"] == 10
- return: "hundred"
  when: shellvalue["stdout"] == 100
- return: "NaN"
```

host.yaml
```yaml
---
- name: using functions
  host: localhost
  tasks:
    - name: using functions
      import_tasks: func1.yaml
      register: funcResult

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/parsing/utils/yaml.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/utils/yaml.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
It's not necessary to register the result of `import_tasks` and would not really be possible. `import_tasks` is not actually a discrete task but rather a preprocessor that will insert all the tasks in the imported task file into the play. There is no single result to register or return for `import_tasks`.

You can accomplish what you want by using `import_tasks` and having a task inside the imported tasks register a variable that is then used in the main tasks file, or use `set_fact`. There is no need to "return" a value.

```yaml
# complex_tasks.yaml

- name: echo result
  shell: echo 100
  register: shellvalue

- name: Set return value
  set_fact:
    return_value: "{{ value_table[shellvalue['stdout']] | default('NaN') }}"
  vars:
    value_table:
      '10': 'ten'
      '100': 'hundred'
```

```yaml
# hosts.yaml

- name: Using vars from imported tasks
  host: localhost
  tasks:
    - import_tasks: complex_tasks.yaml
    
    - debug:
        msg: "The result is {{ return_value }}"
```

For truly complex scenarios that need actual programming constructs, it is best to write a custom module. Trying to program in YAML will only lead to frustration.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
