### ISSUE TITLE
snap module is not idempotent

### ISSUE THREAD

**Issue by gm0neyl0ve** [ansible/ansible#72803]
##### SUMMARY
snap module is not idempotent.  
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

snap module
##### ANSIBLE VERSION

```paste below
ansible --version
ansible 2.9.13
  config file = None
  configured module search path = ['/home/gary.verhulp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed

```

##### STEPS TO REPRODUCE

```yaml
     - name: Remove snaps lxd
       snap:
        name:
          - lxd
        state: absent

TASK [Remove snaps lxd] **********************************************************************************************************************************
fatal: [10.0.0.254]: FAILED! => {"changed": false, "msg": "No snap matching 'lxd' available."}

```

##### EXPECTED RESULTS

Expected OK
This works on the 1st run through and removes the lxd snap.  Fails if  you run it again.

##### ACTUAL RESULTS

```paste below

```
