### ISSUE TITLE
Document Workaround for #61668: Multiple ip addresses or hostnames for a single host in the inventory

### ISSUE THREAD

**Issue by SJrX** [ansible/ansible#72832]
##### SUMMARY
I needed (in actually a couple of different use cases), support multiple ip addresses or host names for things in inventory files. I came across https://github.com/ansible/ansible/issues/61688 which outlines the issue and it was closed as won't be implemented. 

I had hoped to add a comment to 61668, but it is locked, and if I reference it outside (via a gist), it also doesn't show up. I felt it's worth documenting the work around, as I think it's easier and more accessible. I'm hoping that either:

1) The workaround is posted on the issue, 
2) This causes a link to the issue.
3) People find this workaround here.

```
# The following is a workaround for https://github.com/ansible/ansible/issues/61688
# It users the add_host module to change the host (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/add_host_module.html)


- name: "Determine IP Address"
  hosts: localhost

  tasks:
    - name: "Check if myhost is at location A"
      wait_for:
        host: 192.168.0.100
        port: 22
        timeout: 1
      register: myhost_vpn
      ignore_errors: yes
      tags:
        - always

    - name: "Add host for myhost at location A"
      add_host:
        name: "myhost"
        hostname: "myhost"
        ansible_ssh_host: "192.168.0.100"
        ansible_ssh_user: user
        ansible_become: yes
        ansible_become_user: root
        ansible_become_method: sudo
      when: myhost_vpn is succeeded
      tags:
        - always

    - name: "Add host for myhost at location B"
      add_host:
        name: "myhost"
        hostname: "myhost"
        ansible_ssh_host: "10.20.30.40"
        ansible_ssh_port: 22
        ansible_ssh_user: user
        ansible_become: yes
        ansible_become_user: root
        ansible_become_method: sudo
      when: myhost_vpn is failed
      tags:
        - always

- name: Setup System
  hosts: "myhost"
```

##### ISSUE TYPE
- Documentation Report (I guess, I actually just thought it'd be good if it was in the github issue).

##### COMPONENT NAME
github

##### ANSIBLE VERSION
n/a

##### CONFIGURATION
n/a
