### ISSUE TITLE
community.aws.rds_instance module does not handle purging of unassociated security groups

### ISSUE THREAD

**Issue by moody-visaops** [ansible/ansible#72858]
##### SUMMARY

Using the community.aws.rds_instance module, I've created an RDS Instance with 4 security groups. Then I removed one from my playbook and re-ran it. The expected result was for the RDS Instance to now have 3. However, the security groups are unaffected and 4 remain. The ansible run shows no change. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

rds_instance

##### ANSIBLE VERSION

```
ansible 2.9.11
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.11/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:41:41) [Clang 10.0.0 (clang-1000.11.45.5)]
```

##### CONFIGURATION

```paste below
DEFAULT_HASH_BEHAVIOUR(/Users/user/Repositories/ansible-repo/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/user/Repositories/ansible-repo/ansible.cfg) = ['/Users/user/Repositories/ansible-repo/inventories/san
DUPLICATE_YAML_DICT_KEY(/Users/user/Repositories/ansible-repo/ansible.cfg) = false
```

##### OS / ENVIRONMENT

Mac OSX running ansible 2.9.11 using the rds_instance module communicating with RDS : MySQL Engine.

##### STEPS TO REPRODUCE

Create an RDS instance using the rds_instance module. Assign 1 or more security groups. Rerun playbook to remove 1 or more security groups. Expected result would be the new security groups and the old ones purged. No change. 

```yaml
- name: Create a DB instance using id1 and id2 security groups
  community.aws.rds_instance:
    id: test-instance
    state: present
    engine: mysql
    storage_encrypted: no
    db_instance_class: db.t3.medium
    username: admin
    password: password
    allocated_storage: 50
    vpc_security_group_ids:
      - id1
      - id2

- name: Create a DB instance using only the id2 security group. Intent is to remove id1
  community.aws.rds_instance:
    id: test-instance
    state: present
    engine: mysql
    storage_encrypted: no
    db_instance_class: db.t3.medium
    username: admin
    password: password
    allocated_storage: 50
    vpc_security_group_ids:
      - id2

```

##### EXPECTED RESULTS

RDS Instance should be left with security group id2 only.

##### ACTUAL RESULTS

Task 1 - RDS Instance created with id1 and id2 security groups successfully
Task 2 - Showed no change and did not remove id1 security group

```paste below

```
