### ISSUE TITLE
Unable to install packages with yum/dnf module

### ISSUE THREAD

**Issue by Cadjoe** [ansible/ansible#72857]
##### SUMMARY

The playbook runs the fast task but fails on installing the zabbix-agent indicating that the `dnf` module is the issue.
I manage the environment with AWX 14.1.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
YUM/DNF module
```
##### ANSIBLE VERSION

```
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user@ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible 
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Feb 20 2020, 09:38:55) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5.0.1)]

```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

OracleLinux: 8, 7 & 6, all run on VMware VC. 

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Gather default minimum facts from remote host
      setup:
        gather_subset:
          - '!all'

    - name: Install or Upgrade Zabbix_agent on Oracle Linux 8
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-1.el8.noarch.rpm
        state: present
        when: ansible_distribution_major_version == "8"

    - name: Install or Upgrade Zabbix_agent on Oracle Linux 7
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
        state: present
        when: ansible_distribution_major_version == "7"

    - name: Install or Upgrade Zabbix_agent on Oracle Linux 6
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
        state: present
        when: ansible_distribution_major_version == "6"

    - name: Clean repos/metadata
      command: yum clean metadata
      args:
        warn: no
  
    - name: Start Zabbix-agent
      service:
        name: zabbix-agent
        state: stopped
        enabled: yes

    - name: Install zabbix-agent if not installed on remote host
      yum:
        name: zabbix-agent
        state: present

    - name: Install or upgrade zabbix-agent
      command: yum upgrade zabbix-agent
      args:
        warn: no

    - name: Set zabbix-server in zabbix-agent conf file
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: Server=10.255.255.25

    - name: Start Zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes
```

##### EXPECTED RESULTS

I expected to the plays to run and install the package based on the remote host major version. 

##### ACTUAL RESULTS

```
<jupiter> ESTABLISH LOCAL CONNECTION FOR USER: root
<jupiter> EXEC /bin/sh -c 'echo ~root && sleep 0'
<jupiter> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1607092364.9656944-120836-118198736912083 && echo ansible-tmp-1607092364.9656944-120836-118198736912083="` echo /root/.ansible/tmp/ansible-tmp-1607092364.9656944-120836-118198736912083 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/packaging/os/dnf.py
<jupiter> PUT /var/lib/awx/.ansible/tmp/ansible-local-118058sj7t2c3u/tmpvgc93r94 TO /root/.ansible/tmp/ansible-tmp-1607092364.9656944-120836-118198736912083/AnsiballZ_dnf.py
<jupiter> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1607092364.9656944-120836-118198736912083/ /root/.ansible/tmp/ansible-tmp-1607092364.9656944-120836-118198736912083/AnsiballZ_dnf.py && sleep 0'
Running dnf as the backend for the yum action plugin
<jupiter> EXEC /bin/sh -c '/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1607092364.9656944-120836-118198736912083/AnsiballZ_dnf.py && sleep 0'

fatal: [jupiter]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "name": "https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-1.el8.noarch.rpm",
            "state": "present",
            "when": "ansible_distribution_major_version == \"8\""
        }
    },
    "msg": "Unsupported parameters for (dnf) module: when Supported parameters include: allow_downgrade, autoremove, bugfix, conf_file, disable_excludes, disable_gpg_check, disable_plugin, disablerepo, download_dir, download_only, enable_plugin, enablerepo, exclude, install_repoquery, install_weak_deps, installroot, list, lock_timeout, name, releasever, security, skip_broken, state, update_cache, update_only, validate_certs"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@Cadjoe: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Your `when` statement is indented too far:

You want:
```
    - name: Install or Upgrade Zabbix_agent on Oracle Linux 8
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-1.el8.noarch.rpm
        state: present
      when: ansible_distribution_major_version == "8"
```

instead of:
```
    - name: Install or Upgrade Zabbix_agent on Oracle Linux 8
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-1.el8.noarch.rpm
        state: present
        when: ansible_distribution_major_version == "8"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
