### ISSUE TITLE
filesystem is not idempotent when used with resizefs option

### ISSUE THREAD

**Issue by eferet** [ansible/ansible#72859]
##### SUMMARY
After running filesystem twice with resizefs argument set to 'yes', the second time it fails with an error:
```
xfs_growfs: /dev/mapper/vgubuntu-testlv is not a mounted XFS filesystem\
```
due to not monted filesystem. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
filesystem

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/eferet/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION
No notable changes.

##### OS / ENVIRONMENT
Ubuntu

##### STEPS TO REPRODUCE
Minimal playbook to run on system with lvm and lv group named: 'vgubuntu'
```yaml
- hosts: all
  tasks:
    - block:
        lvol:
          vg: vgubuntu
          lv: "{{ lv_name }}"
          size: '16'
      - filesystem:
          dev: /dev/mapper/vgubuntu-{{ lv_name }}
          resizefs: yes
          fstype: xfs
        loop: [0,1]
      become: yes
      vars:
        lv_name: testlv
```

##### EXPECTED RESULTS
```
changed: [x] => {"changed": false}
```

##### ACTUAL RESULTS

```
failed: [x] (item=1) => {"ansible_loop_var": "item", "changed": false, "cmd": "/usr/sbin/xfs_growfs -n /dev/mapper/vgubuntu-testlv", "item": 1, "msg": "xfs_growfs: /dev/mapper/vgubuntu-testlv is not a mounted XFS filesystem", "rc": 1, "stderr": "xfs_growfs: /dev/mapper/vgubuntu-testlv is not a mounted XFS filesystem\n", "stderr_lines": ["xfs_growfs: /dev/mapper/vgubuntu-testlv is not a mounted XFS filesystem"], "stdout": "", "stdout_lines": []}
```
