### ISSUE TITLE
fileglob lookup plugin returns inconsistent values

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#72873]
##### SUMMARY

The `fileglob` lookup plugin returns values inconsistently, depending on the order of arguments (terms) given it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

fileglob

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = /Users/jpm/take/training/bugs/fileglob/ansible.cfg
  configured module search path = ['/Users/jpm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jpm/take/training/bugs/fileglob/env.v3/lib/python3.8/site-packages/ansible
  executable location = /Users/jpm/take/training/bugs/fileglob/env.v3/bin/ansible
  python version = 3.8.5 (default, Sep 27 2020, 11:38:54) [Clang 12.0.0 (clang-1200.0.32.2)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/Users/jpm/take/training/bugs/fileglob/ansible.cfg) = True
```

##### OS / ENVIRONMENT

macOS Catalina (10.15.7)

##### STEPS TO REPRODUCE

Run the example playbook

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
     dir: files
  tasks:
  - file: path='{{ dir }}' state=directory
  
  - file: path='setvars.bat' state=touch  # in current directory!

  - file: path='{{ dir }}/{{ item }}' state=touch
    loop:
        - json.c
        - strlcpy.c
        - base64.c
        - json.h
        - base64.h
        - strlcpy.h
        - jo.c

  - debug:
        msg: '{{ query("fileglob", "setvars.bat", "{{ dir }}/*.[ch]" ) }}'

  - debug:
        msg: '{{ query("fileglob", "{{ dir }}/*.[ch]", "setvars.bat" ) }}'
```

##### EXPECTED RESULTS

I expected the path `setvars.bat` to be contained in both result sets, but it's in the first only. The results are identical if I use `lookup()` instead of `query()` and when I use `with_fileglob:`

##### ACTUAL RESULTS

```paste below
PLAY [localhost] ***************************************************************

TASK [file] ********************************************************************
ok: [localhost]

TASK [file] ********************************************************************
changed: [localhost] => (item=json.c)
changed: [localhost] => (item=strlcpy.c)
changed: [localhost] => (item=base64.c)
changed: [localhost] => (item=json.h)
changed: [localhost] => (item=base64.h)
changed: [localhost] => (item=strlcpy.h)
changed: [localhost] => (item=jo.c)

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": [
        "/Users/jpm/take/training/bugs/fileglob/setvars.bat",
        "/Users/jpm/take/training/bugs/fileglob/files/json.c",
        "/Users/jpm/take/training/bugs/fileglob/files/strlcpy.c",
        "/Users/jpm/take/training/bugs/fileglob/files/base64.h",
        "/Users/jpm/take/training/bugs/fileglob/files/json.h",
        "/Users/jpm/take/training/bugs/fileglob/files/base64.c",
        "/Users/jpm/take/training/bugs/fileglob/files/strlcpy.h",
        "/Users/jpm/take/training/bugs/fileglob/files/jo.c"
    ]
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": [
        "/Users/jpm/take/training/bugs/fileglob/files/json.c",
        "/Users/jpm/take/training/bugs/fileglob/files/strlcpy.c",
        "/Users/jpm/take/training/bugs/fileglob/files/base64.h",
        "/Users/jpm/take/training/bugs/fileglob/files/json.h",
        "/Users/jpm/take/training/bugs/fileglob/files/base64.c",
        "/Users/jpm/take/training/bugs/fileglob/files/strlcpy.h",
        "/Users/jpm/take/training/bugs/fileglob/files/jo.c"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
