### ISSUE TITLE
ElastiCache VPC Support - Use of cache security groups is not permitted along with cache subnet group and/or security group Ids

### ISSUE THREAD

**Issue by jimsmith** [ansible/ansible#7291]
## Issue Type:

Bug Report
## Ansible Version:

ansible 1.6
## Host:

Amazon Linux AMI 3.10.37-47.135.amzn1.x86_64
## Target:

local_action
## Summary:

1) When attempting to create a ElastiCache Redis & Memcached Parameter Group prior to creating the actual cache cluster,
there is no support for creating cache paramater group name and cache paramater group family and description.

I have a workaround at present that I am using a BASH script to provision the cache parameter group first:

``` bash
aws elasticache create-cache-parameter-group --cache-parameter-group-name $ELASTICACHE_NAME --cache-parameter-group-family $ELASTICACHE_ENGINE --description "$ELASTICACHE_DESCRIPTION"
```

2) After the cache parameter group has been created using BASH, When attempting to create a new redis cache cluster using Ansible ElastiCache, I am presented with the following msg:
## Output

``` bash
msg: Use of cache security groups is not permitted along with cache subnet group and/or security group Ids .
```

Steps To Reproduce:

``` yaml

---
# Based on the documentation found at:
# http://docs.ansible.com/elasticache_module.html

# PREQUISITES YOU MUST FIRST RUN THE FOLLOWING IN ORDER PRIOR TO RUNNING THIS CREATION
# create_cache_parameter_groups.sh
# modify_redis_cache_parameter_group.sh

- name: Provision ElastiCache Cluster
  local_action:
        module: elasticache
        state: present
        region: eu-west-1
        engine: redis
        cache_port: 6379
        cache_engine_version: 2.8.6
        node_type: cache.m1.small
        num_nodes: 1
        name: "test-ec-redis"
        security_group_ids: sg-06bdaa64
#        cache_security_groups: sg-06bdaa64
        wait: yes
  register: elasticache

```

``` bash
ansible-playbook -i server_inventory --step test-elasticache-redis-aws-eu-west-1.yml --start-at-task "Provision ElastiCache Cluster" -vvv
```

``` bash
Perform task: provisioning/aws/regions/eu-west-1/vpc-elasticache | Provision ElastiCache Cluster (y/n/c):  ***
<127.0.0.1> REMOTE_MODULE elasticache security_group_ids=sg-06bdaa64 state=present node_type=cache.m1.small region=eu-west-1 cache_engine_version=2.8.6 name=test-ec-redis engine=redis
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1399365539.51-4608904334481 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1399365539.51-4608904334481 && echo $HOME/.ansible/tmp/ansible-tmp-1399365539.51-4608904334481']
<127.0.0.1> PUT /tmp/tmp_jcIwM TO /home/twigaws/.ansible/tmp/ansible-tmp-1399365539.51-4608904334481/elasticache
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 /usr/bin/python /home/twigaws/.ansible/tmp/ansible-tmp-1399365539.51-4608904334481/elasticache; rm -rf /home/twigaws/.ansible/tmp/ansible-tmp-1399365539.51-4608904334481/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "item": ""}
msg: Use of cache security groups is not permitted along with cache subnet group and/or security group Ids .

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/twigaws/test-elasticache-redis-aws-eu-west-1.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

This also requires to be able to create parameter groups prior to creating the cache cluster itself, given that alot of AWS resources require parameter groups that are not default to exist prior to creating any cluster.
