### ISSUE TITLE
module_defaults for yum do not get picked up when invoked via package

### ISSUE THREAD

**Issue by johnbui423** [ansible/ansible#72918]
##### SUMMARY

In 2.10.x, `module_defaults` for `yum` do not get picked up when invoked via `package`. It works fine with 2.9.x.

This seems to be a regression of https://github.com/ansible/ansible/issues/57482 - basing this bug report largely on that original issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module_defaults

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
```

##### OS / ENVIRONMENT

CentOS 7

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  module_defaults:
    yum:
      lock_timeout: 120
  tasks:
    - package:
        name: yum
        state: present
    - yum:
        name: yum
        state: present
```

##### EXPECTED RESULTS

lock_timeout is set to 120 for both tasks

##### ACTUAL RESULTS

```paste below
[...]
TASK [package]
[...]
            "lock_timeout": 30, 
[...]
}

TASK [yum] 
[...]
            "lock_timeout": 120,
[...]
```
