### ISSUE TITLE
[Feature request] Ability to securely use $YUM[0-9]/$DNF[0-9] env vars in yum/dnf config files.

### ISSUE THREAD

**Issue by stevenwbe** [ansible/ansible#72916]
##### SUMMARY
Using ansible.builtin.yum_repository or ansible.builtin.yum is missing something when using authenticated repositories. 

So we have authenticated yum repositories on nexus. We use the yum_repository module to write them to our /etc/yum.repos.d directory. But as we don't like to have the password defined in the repofile or in the /etc/yum/vars files we wanted to use the YUM1-9 variables to keep the password out of the config files on the target server. We then used the "environment:" feature around the yum task in ansible to set YUM1 and YUM2 environment variables at deploy time. This way the credentials are stored in the ansible-vault and injected when needed. It also allows easy password rotation since they are stored centrally.

But while testing we noticed the environment variables given to ansible tasks are given in the "ssh -C" command line used to execute the command on the target server. So easily spotted in the process list (ps auwxf) of the ansible server. 

The idea is that environment variables should not show up in the process table, but maybe we shouldn't pass passwords this way, and we're missing a feature in yum which makes this is a none-issue.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
yum_repository
yum

##### ADDITIONAL INFORMATION
The repository definition:
(The nexus repo's are disabled by default to not interfere with other yum commands executed on the server)
```yaml
---
- name: Add nexus repository
  yum_repository:
    name: "nexus-{{ item }}"
    enabled: no
    file: "nexus-{{ item }}"
    description: "Nexus repo configuration for {{ item }}"
    baseurl: "https://$YUM1:$YUM2@<nexus>/nexus/content/repositories/{{ item }}/"
    mode: 0644
  loop: "{{ nexus_repositories }}"
```
The deploy definition:
```yaml
---
- name: deploy.yml | Install dependency modules
  yum:
    enablerepo: "nexus*"
    name: "<package>"
    state: latest
  environment:
    YUM1: "{{ USER }}"
    YUM2: "{{ USER_PASSWORD }}"
```
