### ISSUE TITLE
Deploy VM from template doesn't change IP

### ISSUE THREAD

**Issue by narkeekran** [ansible/ansible#72934]
##### SUMMARY
A playbook that creates a new VM from a template works on esxi 6.7 but has issues applying IP config to new VMs on 7.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.vmware.vmware_guest

##### ANSIBLE VERSION
```ansible 2.10.3
  config file = /home/tfurm/projects/ansible/ansible.cfg
  configured module search path = ['/home/tfurm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```

##### CONFIGURATION

```ANSIBLE_COW_SELECTION(/home/tfurm/projects/ansible/ansible.cfg) = random
ANSIBLE_PIPELINING(/home/tfurm/projects/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/tfurm/projects/ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN(/home/tfurm/projects/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/tfurm/projects/ansible/ansible.cfg) = ~/.ansible/fact-cache
CACHE_PLUGIN_TIMEOUT(/home/tfurm/projects/ansible/ansible.cfg) = 86400
DEFAULT_BECOME_FLAGS(/home/tfurm/projects/ansible/ansible.cfg) = -H -S
DEFAULT_FORKS(/home/tfurm/projects/ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/home/tfurm/projects/ansible/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/home/tfurm/projects/ansible/ansible.cfg) = ['all']
DEFAULT_HOST_LIST(/home/tfurm/projects/ansible/ansible.cfg) = ['/home/tfurm/projects/ansible/hosts']
DEFAULT_ROLES_PATH(/home/tfurm/projects/ansible/ansible.cfg) = ['/home/tfurm/projects/ansible/roles']
DEFAULT_SCP_IF_SSH(/home/tfurm/projects/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/tfurm/projects/ansible/ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(/home/tfurm/projects/ansible/ansible.cfg) = /home/tfurm/.ansible/vault-password-file
INVENTORY_IGNORE_EXTS(/home/tfurm/projects/ansible/ansible.cfg) = ['~', '.orig', '.bak', '.ini', '.cfg', '.retry', '.pyc', '.pyo']
RETRY_FILES_SAVE_PATH(/home/tfurm/projects/ansible/ansible.cfg) = /home/tfurm/.ansible/retry
TRANSFORM_INVALID_GROUP_CHARS(/home/tfurm/projects/ansible/ansible.cfg) = silently


```

##### OS / ENVIRONMENT
issues on: Hypervisor: VMware ESXi, 7.0.0, 16324942
Works on: Hypervisor: VMware ESXi, 6.7.0, 14320388
template VM is centos7 

##### STEPS TO REPRODUCE
install centos 7 minimal on a new vm, configure with IPconfig. Convert to template
run playbook 

```
- name: Deploy new VMs on "{{ vcenter_datacenter }}"
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vcenter_folder }}"
    name:  "{{ instance_hostname }}"
    validate_certs: no
    guest_id: "{{ guest_id }}"
    state: poweredoff
    template: "{{ instance_template }}"
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      scsi: "{{ scsi }}"
      hotadd_cpu: "{{ hotadd_cpu }}"
      hotremove_cpu: "{{ hotremove_cpu }}"
      hotadd_memory: "{{ hotadd_memory }}"
    networks:
      - name: "{{ interfaces.0.network_name }}"
        device_type: vmxnet3
        start_connected: true
        allow_guest_control: true
        type: static
        ip: "{{ interfaces.0.ip4|ipaddr('address') }}"
        netmask: "{{ interfaces.0.ip4|ipaddr('netmask') }}"
        gateway: "{{ interfaces.0.gw4 }}"
    customization:
      existing_vm: true
      hostname: "{{ instance_hostname }}"
      domain: "{{ network_domain }}"
      dns_servers: "{{ network_dns }}"
  delegate_to: localhost

- name: Reboot virtual machines
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ instance_hostname }}"
    validate_certs: no
    state: poweredon
    wait_for_customization: yes
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy_results
```
IP vars:

```
---
instance_hostname: LABTESTING

interfaces:
  - network_name: '{{ network_name }}'
    ifname: ens192
    ip4: 10.124.77.2/24
    gw4: '{{ network_gateway }}'
...
```

output:

##### EXPECTED RESULTS

New VM was deployed with new IP configuration

##### ACTUAL RESULTS

New VM is deployed without changing the IP configuration

when it deploys the VM it tries to assign the right ip: 10.124.77.2

```TASK [newinstance : Deploy new VMs on "Lab"] *************************************************************************************************************************************************'
changed: [labtesting.dc2.lab.{redacted] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "11269",
        "hw_cluster": "DC2",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "LAB-VSAN0"
        ],
        "hw_esxi_host": "10.124.76.1",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": "00:50:56:a4:b5:63",
            "macaddress_dash": "00-50-56-a4-b5-63",
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "VOIP-GUEST-MGMT-DC2 (77)"
        },
        "hw_files": [
            "[LAB-VSAN0] ********/********.vmx",
            "[LAB-VSAN0] ********/********.nvram",
            "[LAB-VSAN0] ********/********.vmsd",
            "[LAB-VSAN0] ********/********.vmdk"
        ],
        "hw_folder": "/Lab/vm/Lab",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": null,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 4096,
        "hw_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "hw_power_status": "poweredOff",
        "hw_processor_count": 4,
        "hw_product_uuid": "4224043a-368e-5512-fb17-3b1cc00b205e",
        "hw_version": "vmx-17",
        "instance_uuid": "502494ad-cb95-939c-eb2d-c7bbe3366115",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "moid": "vm-62",
        "snapshots": [],
        "vimref": "vim.VirtualMachine:vm-62",
        "vnc": {}
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [],
            "cluster": "DC2",
            "convert": null,
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "existing_vm": true,
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "Lab",
            "datastore": null,
            "delete_from_inventory": false,
            "disk": [],
            "esxi_hostname": null,
            "folder": "/Lab",
            "force": false,
            "guest_id": "centos7_64Guest",
            "hardware": {
                "hotadd_cpu": false,
                "hotadd_memory": false,
                "hotremove_cpu": false,
                "memory_mb": 4096,
                "num_cpus": 4,
                "scsi": "paravirtual"
            },
            "hostname": "vcenter0.lab.int.{redacted}.net",
            "is_template": false,
            "linked_clone": false,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name_match": "first",
            "networks": [
                {
                    "allow_guest_control": true,
                    "device_type": "vmxnet3",
                    "gateway": "10.124.77.254",
                    "ip": "10.124.77.2",
                    "name": "VOIP-GUEST-MGMT-DC2 (77)",
                    "netmask": "255.255.255.0",
                    "start_connected": true,
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredoff",
            "state_change_timeout": 0,
            "template": "LAB-BASEIMAGE0",
            "use_instance_uuid": false,
            "username": "Administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_customization_timeout": 3600,
            "wait_for_ip_address": false,
            "wait_for_ip_address_timeout": 300
        }
    }
}
```

but when it reboots it's reverted to the original IP 10.124.77.1

```
TASK [newinstance : Reboot virtual machines] ***********************************************************************************************************************************************************************************************
task path: /home/tfurm/projects/ansible/roles/newinstance/tasks/main.yaml:116
redirecting (type: modules) ansible.builtin.vmware_guest to community.vmware.vmware_guest
Using module file /usr/lib/python3.8/site-packages/ansible_collections/community/vmware/plugins/modules/vmware_guest.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: tfurm
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [labtesting.dc2.lab.{redacted}.net] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "11269",
        "hw_cluster": "DC2",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "LAB-VSAN0"
        ],
        "hw_esxi_host": "10.124.76.1",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [
                "10.124.77.1",
                "fe80::5fb2:459f:83e6:6d3"
            ],
            "label": "Network adapter 1",
            "macaddress": "00:50:56:a4:b5:63",
            "macaddress_dash": "00-50-56-a4-b5-63",
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "VOIP-GUEST-MGMT-DC2 (77)"
        },
        "hw_files": [
            "[LAB-VSAN0] LABTESTING/LABTESTING.vmx",
            "[LAB-VSAN0] LABTESTING/LABTESTING.nvram",
            "[LAB-VSAN0] LABTESTING/LABTESTING.vmsd",
            "[LAB-VSAN0] LABTESTING/LABTESTING.vmdk"
        ],
        "hw_folder": "/Lab/vm/Lab",
        "hw_guest_full_name": "CentOS 7 (64-bit)",
        "hw_guest_ha_state": true,
        "hw_guest_id": "centos7_64Guest",
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 4096,
        "hw_name": "LABTESTING",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 4,
        "hw_product_uuid": "4224043a-368e-5512-fb17-3b1cc00b205e",
        "hw_version": "vmx-17",
        "instance_uuid": "502494ad-cb95-939c-eb2d-c7bbe3366115",
        "ipv4": "10.124.77.1",
        "ipv6": null,
        "module_hw": true,
        "moid": "vm-62",
        "snapshots": [],
        "vimref": "vim.VirtualMachine:vm-62",
        "vnc": {}
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [],
            "cluster": null,
            "convert": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "Lab",
            "datastore": null,
            "delete_from_inventory": false,
            "disk": [],
            "esxi_hostname": null,
            "folder": null,
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "vcenter0.lab.{redacted}",
            "is_template": false,
            "linked_clone": false,
            "name": "LABTESTING",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": null,
            "use_instance_uuid": false,
            "username": "Administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": true,
            "wait_for_customization_timeout": 3600,
            "wait_for_ip_address": true,
            "wait_for_ip_address_timeout": 300
        }
    }
```
