### ISSUE TITLE
Synchronize - MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}

### ISSUE THREAD

**Issue by downright-ux** [ansible/ansible#72939]
##### SUMMARY
Trying to rsync using synchronize module from remote host to local. Seems like the data moves over but then Ansible throws the following issue.
```
fatal: [server.mydomain.com]: FAILED! => {"changed": false, "module_stderr": "Killed\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 137}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Synchronize

##### ANSIBLE VERSION

```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION
Only thing changed in the configuration file
```
host_key_checking = False
```

##### OS / ENVIRONMENT
Ansible server is on ubuntu 20.04 and other server is I'm pulling from is on 18.04

##### STEPS TO REPRODUCE

cp below into file and run playbook

```
---
- name: backup
  user: root
  hosts: production-data
  tasks: 
    - name: copy files from /data
      synchronize:
        mode: pull
        src: "/data"
        dest: "/backup"
        recursive: yes
        delete: no
        times: yes

```

##### EXPECTED RESULTS
rsync's data over and with no error
