### ISSUE TITLE
If include in block section with run_once, the always section isn't always run

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible/ansible#72941]
##### SUMMARY
Related: #24301

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- block/rescue/always

##### ANSIBLE VERSION

```
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

#### 1. Create a test playbook with `run_once: yes` :

**main.yml**
```yaml 
---
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
      - include: test_fail.yml
        run_once: true

    always:
      - include: always.yml
```

**test_fail.yml**
```yaml
---
- fail:
    msg: "always fail"
```

**test_success.yml**
```yaml
---
- debug:
    msg: "success task"
```

#### 2. `always` task will not run:
```
# ansible-playbook -i hosts main.yml

PLAY [localhost] ***************************************************************************************************
TASK [fail] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "always fail"}

NO MORE HOSTS LEFT *************************************************************************************************
PLAY RECAP *********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```
#### 1. If there is `rescue` section in the playbook, `always` task will run.

**main.yml**
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
      - include: test_fail.yml
        run_once: true
    rescue:
      - include: test_success.yml
    always:
      - include: always.yml
```

**Result**
```
PLAY [localhost] ***************************************************************************************************
TASK [fail] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "always fail"}

TASK [debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "success task"
}

TASK [debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "This task will run always"
}

PLAY RECAP *********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=1    ignored=0  
```

#### 2. If `run_once` task has not been failed,  `always` task will run.

**main.yml**
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
      - include: test_success.yml
        run_once: true
    always:
      - include: always.yml
```

**Result**
```
PLAY [localhost] ***************************************************************************************************
TASK [debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "success task"
}

TASK [debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "This task will run always"
}

PLAY RECAP *********************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

#### 3. If there is no `run_once`, `always` task will run.

**main.yml**
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
      - include: test_fail.yml
    always:
      - include: always.yml
```

**Result**
```
PLAY [localhost] ***************************************************************************************************
TASK [fail] ********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "always fail"}

TASK [debug] *******************************************************************************************************
ok: [localhost] => {
    "msg": "This task will run always"
}

PLAY RECAP *********************************************************************************************************localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

##### EXPECTED RESULTS
The always task should run always even if `run_once` is enabled.
