### ISSUE TITLE
1.6 :: Synchronize module loses trailing slash when used in a role with relative source path

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible#7296]
Hello,
##### Issue Type:

Bug Report
##### Ansible Version:

1.6
##### Environment

:: host :: ArchLinux
:: managed ::  Debian 7
##### Summary:

Just found a problem with synchronization of folder contents when relative source path specified in the role
It makes sense when we synchronize content to folder with other name
Ansible loses trailing slash when absolute local path generated
##### Steps To Reproduce:

Example playbook for debug on local box (`test-synchronize.yml`):

``` yaml
- name: 'Synchronize :: Test trailing slash :: task'
  hosts: vagrant
  remote_user: vagrant
  sudo_user: root
  sudo: True

  tasks:
   - name: 'Sync files'
     synchronize: src=tmp/testABC/
                  dest=/tmp/testXYZ/
                  recursive=yes
                  delete=yes
```

and same with role (`test-synchronize-role.yml`):

``` yaml
- name: 'Synchronize :: Test trailing slash :: role'
  hosts: vagrant
  remote_user: vagrant
  sudo_user: root
  sudo: True

  roles:
   - test-sync
```

Role code (`roles/test-sync/main.yml`):

``` yaml

---

- name: 'Sync files'
  synchronize: src=tmp/testABC/
               dest=/tmp/testXYZ/
               recursive=yes
               delete=yes
```

Content of source folder:

```
» tree tmp
tmp
└── testABC
    ├── a
    ├── b
    └── c
```

`tmp` folder located on same level as playbooks
##### Expected Results:

It is OK when no role used to invoke synchronize
Playbook run output: http://pastebin.com/zfR1N9YY
Managed machine content:

```
# tree /tmp/testXYZ/
/tmp/testXYZ/
├── a
├── b
└── c
```
##### Actual Results:

Now I run playbook with role over results of previous playbook
Playbook run output: http://pastebin.com/tdmtNX0U
Managed machine content:

```
# tree testXYZ/
testXYZ/
├── a
├── b
├── c
└── testABC
    ├── a
    ├── b
    └── c
```

Verbose log output of playbook shows lack of trailing slash on source path for rsync:
`/home/xt/projects/ADYAX/adyax-ansible-v2/prj/tmp/testABC` (should be `/home/xt/projects/ADYAX/adyax-ansible-v2/prj/tmp/testABC/`)
