### ISSUE TITLE
get_url does not respect unsafe_writes

### ISSUE THREAD

**Issue by sivel** [ansible/ansible#72981]
##### SUMMARY
`get_url` inherits from `add_file_common_args`, which includes `unsafe_writes`, however our call to `atomic_move` does not pass this argument along.

https://github.com/ansible/ansible/blob/5226ac5778d3b57296b925de5d4ad0b485bb11cd/lib/ansible/modules/get_url.py#L463

https://github.com/ansible/ansible/blob/5226ac5778d3b57296b925de5d4ad0b485bb11cd/lib/ansible/modules/get_url.py#L633

```diff
diff --git a/lib/ansible/modules/get_url.py b/lib/ansible/modules/get_url.py
index 6ac370c2ef..c29d69e5c9 100644
--- a/lib/ansible/modules/get_url.py
+++ b/lib/ansible/modules/get_url.py
@@ -630,7 +630,7 @@ def main():
             if backup:
                 if os.path.exists(dest):
                     backup_file = module.backup_local(dest)
-            module.atomic_move(tmpsrc, dest)
+            module.atomic_move(tmpsrc, dest, unsafe_writes=module.params['unsafe_writes'])
         except Exception as e:
             if os.path.exists(tmpsrc):
                 os.remove(tmpsrc)
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/get_url.py

##### ANSIBLE VERSION

```paste below
2.9
2.10
2.11
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/get_url.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The most complicated part of this fix will be writing tests to ensure that the module actually uses `unsafe_writes`.

**Comment by sivel** [comment]
I marked this as a `tower_blocker`/`P2` for 2.11, as it's causing issues with execution environments.

**Comment by AlanCoding** [comment]
I have my test cases here https://github.com/AlanCoding/execution-environments-issues

and I don't see what role `unsafe_writes` can play in fixing the problem. The module `blockinfile` does not fail to pass the unsfe_writes parameter that you are suggesting fixing here. Attempting to run:

```yaml
---
- name: Verify that ansible can correctly pass arguments to ansible in shell
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Write inventory file
      blockinfile:
        path: '/runner/inventory.ansible.shell'
        block: |
          localhost ansible_connection=local
        state: present
        unsafe_writes: true
        create: True
```

This still hits the permissions error moving a file from `/root/.ansible/tmp/...` to `/runner/...`
