### ISSUE TITLE
user's password_lock works only with "yes" but ignores "True"

### ISSUE THREAD

**Issue by hunter86bg** [ansible/ansible#72992]
##### SUMMARY
Ansible module for local user management does not lock the user if using:
```
password_lock: True
```
yet the following works:
```
password_lock: yes
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin.user

##### ANSIBLE VERSION
```
ansible 2.9.2
  config file = /home/user/ansible-dc/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/user/repo/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Target OS - RHEL 8.1

##### STEPS TO REPRODUCE
Just create a user with 
```
password_lock: True
```

Note: Sensitive data was replaced!
```
- name: Deploy the  user
  user:
    append: True
    comment: "Some Comment"
    create_home: true
    group: 'somegroup_that_exists'
    home:  '/some/location/home'
    name:  'user'
    password: "<redacted>"
    password_lock: True
    shell: '/bin/csh'
    uid:   '99999'
```

##### EXPECTED RESULTS
User's password in /etc/shadow should start with "!".

##### ACTUAL RESULTS
User's password was not disabled (only the hash was deployed), task succeeded.

```
# grep user /etc/shadow
user:<redacted>:18612:0:99999:7:::
```
it works once set to :
```
password_lock: yes
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
What is happening is the password is being locked then unlocked rather than locking the account. Run this play multiple times to observe the behavior:

(the password hash is not sensitive)

```yaml
- user:
    name: testuser1
    password_lock: True
    password: '$6$OdJHswQFZxPKZj8K$4rsWr7DPbCf5p3r07eWyFzyrfVqLGpmDyX8blYdQZ/YEl0q5GIK4tBxkISPerTmbXUU9OX2ciVmKxjtYEJjGX/'
```

The first run creates the account, the second run locks the account:

```
modify_user_usermod: ['/sbin/usermod', '-L', 'testuser1']
```

And the third run sets the password hash:
```
modify_user_usermod:
      ['/sbin/usermod', '-p', '$6$OdJHswQFZxPKZj8K$4rsWr7DPbCf5p3r07eWyFzyrfVqL...YdQZ/YEl0q5GIK4tBxkISPerTmbXUU9OX2ciVmKxjtYEJjGX/', 'testuser1']
```

Subsequent runs will go back and forth between those command runs, locking and unlocking the account.
