### ISSUE TITLE
File doesnt set directory permissions correctly.

### ISSUE THREAD

**Issue by jwells0823** [ansible/ansible#73001]
##### SUMMARY

```
- name: Create the destination directory on the repository, if it doesn't exist
  file:
    path: "{{ repo_basedir }}/{{ repo_url_location }}"
    owner: ansible_artifact
    group: nginx
    mode: 02775
    recurse: yes
    state: directory
  delegate_to: "{{ repo_server }}"
  become: yes
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

file
##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /Users/<>/.ansible.cfg
  configured module search path = ['/Users/<>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.15/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:15:17) [Clang 12.0.0 (clang-1200.0.32.21)]

```

##### CONFIGURATION

```paste below
DEFAULT_REMOTE_USER(/Users/<>/.ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/Users/<>/.ansible.cfg) = ['/Users/<>/Documents/development/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/<>/.ansible.cfg) = /Users/<>/Documents/development/ansible/keys/passwd.gdot
HOST_KEY_CHECKING(/Users/<>/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL7 is taget

##### STEPS TO REPRODUCE

Run the above in a role.

```yaml

```

##### EXPECTED RESULTS

I expect to see drwxrwsr-x permissions, but  I receive drwxrws---.  Changing permissions as root works correctly on the server using the above mode.

##### ACTUAL RESULTS

 I receive drwxrws---.

```paste below

```
