### ISSUE TITLE
delegate_to play is broken in Ansible 2.10.3

### ISSUE THREAD

**Issue by kurianinc** [ansible/ansible#73018]
```
build-ec2-node.yml
===============

- name: Build AMI
  hosts: all
  gather_facts: no
  become: no

  roles:
     - spinup-ec2-node
     - role: configure-ec2-node
       delegate_to: "{{ instance_public_ip }}"
       delegate_facts: true
       become: yes
```

The playbook breaks at the following line in the role configure-ec2-node:

```
- name: Set facts from EC2 node
  setup:
  delegate_to: "{{ instance_public_ip }}"
  delegate_facts: yes
```

```
TASK [configure-ami-role : Set facts from EC2 node] **************************************************************************************************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

This is used to work just fine with the older versions of Ansible, at least up to 2.9.0 with the command line below:
`
$ ansible-playbook build-ec2-node.yml -i localhost, --private-key=/path/to/key -u USER --connection=local
`
Any idea what changed with 2.10.x and how to resolve it? Basically there must be a way to run the paybook with no remote connection until the EC2 node is spun up and available and then part of the play must be run on the newly spun up node.
