### ISSUE TITLE
Can't set the minimum_tls_version to TLS1_2 when using the azure.azcollection.azure_rm_storageaccount

### ISSUE THREAD

**Issue by Altaf-Axway** [ansible/ansible#73039]
##### SUMMARY

Can not set the minimum_tls_version  to TLS1_2  
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm_storageaccount

##### ANSIBLE VERSION

```paste below
2.10
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04.5 LTS 

##### STEPS TO REPRODUCE

install the 2.10 ansible -
sudo apt-add-repository --yes --update ppa:ansible/ansible-2.10
sudo apt install -y ansible

```yaml

- name: Create Blob Container for state storage
  azure.azcollection.azure_rm_storageaccount:
    name: "{{ project }}{{ env }}tfst"
    resource_group: "{{ project }}-{{ env }}-rg"
    account_type: Standard_LRS
    location: "{{ azure_location }}"
    minimum_tls_version: TLS1_2
    kind: StorageV2
    tags:
        controller: "{{ controller }}"
        platform: "{{ project }}-{{ env }}"
        owner: "{{ environment_owner }}"
        costcenter: "{{ environment_costcenter }}"

```

##### EXPECTED RESULTS

the blob storage that got provisioned has the TLS1_0 instead of TLS1_2 now in case you send TLS1_2 in the playbook but still when the storage is created it set to 1.0 tls

##### ACTUAL RESULTS

when the storage is created it set to 1.0 tls

TASK [Create Blob Container for state storage] *********************************
task path: /home/vsts/work/1/s/roles/storage/azure/azure.yml:20
changed: [localhost] => {"changed": true, "state": {"access_tier": "Hot", "allow_blob_public_access": null, "custom_domain": null, "https_only": true, "id": "/subscriptions/<SUBSID>/resourceGroups/apimcmgt-alb-rg/providers/Microsoft.Storage/storageAccounts/apimcmgtalbtfst", "location": "uksouth", "minimum_tls_version": "TLS1_0", "name": "apimcmgtalbtfst", "network_acls": {"bypass": "AzureServices", "default_action": "Allow", "ip_rules": [], "virtual_network_rules": []}, "primary_endpoints": {"blob": "https://apimcmgtalbtfst.blob.core.windows.net/", "queue": "https://apimcmgtalbtfst.queue.core.windows.net/", "table": "https://apimcmgtalbtfst.table.core.windows.net/"}, "primary_location": "uksouth", "provisioning_state": "Succeeded", "resource_group": "apimcmgt-alb-rg", "secondary_endpoints": null, "secondary_location": null, "sku_name": "Standard_LRS", "sku_tier": "Standard", "status_of_primary": "available", "status_of_secondary": null, "tags": {"CreatedOn": "2020-12-21T10:21:40.0082209Z", "controller": "test", "costcenter": "test", "owner": "test", "platform": "apimcmgt-alb"}, "type": "Microsoft.Storage/storageAccounts"}}

```paste below

```
