### ISSUE TITLE
Playbook inheritance

### ISSUE THREAD

**Issue by alexnoz** [ansible/ansible#73035]
##### SUMMARY

The idea is sort of similar to template inheritance feature in some template engines, e.g. in Jinja. It also resembles [Template method design pattern](https://en.wikipedia.org/wiki/Template_method_pattern).

Assume that we have a number of similarly structured playbooks and we want to extract their common parts to reduce repetition and make it more manageable. We could create a so-called base playbook which would contain all common tasks. It would also contain named *holes* in certain parts which derived playbooks should fill with their tasks. Derived playbooks can pass variables into the base. Base playbook can have some default tasks instead of just empty holes. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

I'm not sure if that's possible at the plugin/module level, it probably should be built into the core.
##### ADDITIONAL INFORMATION

We have one base playbook in which we describe a general algorithm and a number of derived playbooks that provide the missing tasks/variables to the base or override defaults. Base playbook can't be run on its own.

It would solve the problem of configuration duplication when we have a number of playbooks that are very similar in terms of structure and/or have common (identical or almost identical) tasks in the same places (e.g. at the begining/end). One way to do something like this currently is to have a file with tasks per common part (e.g. `start.yml`, `end.yml`) and then include these parts into the main playbook in relevant places, but this approach doesn't scale and is error-prone. If you know a better way of doing this, please let me know.

Here's a rough example of what it could look like:

```yaml
# In base.yml
---
  # `group` & `common_set_name` are provided by derived plays
- hosts: "{{ group }}"
  name: base
  # Specify that this play is a template, so that it can't be run on its own
  type: template
  become: true
  gather_facts: false
  tasks:
    - name: Copy set
      copy:
        src: "{{ item }}.set"
        dest: "/etc/ipset/sets/{{ item }}.set"
      with_items:
        - "{{ common_set_name }}"
        - "{{ group }}"

      # A place to put a block/task into
    - name: Configure rules

    - name: Get all sets
      find:
        paths: /etc/ipset/sets
        patterns: '*.set'
      register: all_sets

    # Other tasks
```

```yaml
# In derived.yml
---
  # <filename>:<playname>
- inherits: base.yml:base
  vars:
    common_set_name: common_external
    group: lighthouse
  tasks:
      # `include_into` accepts the name of the task from the inherited playbook
    - include_into: Configure rules
      name: Configure MANAGED-INPUT chain
      iptables_raw:
        name: managed_input
        rules: |
          -N MANAGED-INPUT
          -A MANAGED-INPUT -i eth+ -m set --match-set SERVERS src -m set --match-set NTP_PORT dst -j ACCEPT

---
- inherits: base.yml:base
  vars:
    common_set_name: common_internal
    group: nginx
  tasks:
    - include_into: Configure rules
      block:
        - name: Configure MANAGED-INPUT chain
          iptables_raw:
            name: managed_input
            rules: |
              -N MANAGED-INPUT
              -A MANAGED-INPUT -i eth+ -m set --match-set GATEWAY src -m set --match-set WEB_PORT dst -j ACCEPT
          register: iptables_result

        - debug:
            msg: "{{ iptables_result.ipversion }}"
```

I'm probably missing something and there is a nice way to do things like this already, if that's the case, please let me know.
