### ISSUE TITLE
set_fact doesn't work as expected in v2.9.0

### ISSUE THREAD

**Issue by kurianinc** [ansible/ansible#73036]
##### SUMMARY
Variables defined using set_fact are available in the same module for use!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact

##### ANSIBLE VERSION

```
/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py:41: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ansible 2.9.0
  config file = None
  configured module search path = [u'/Users/xyz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Jan 26 2020, 23:50:38) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py:41: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
```

##### OS / ENVIRONMENT

MacOS

##### STEPS TO REPRODUCE

```
main.yml from a role that doesn't work as expected:

- name: Set service names
  set_fact:
    apache_service_name: apache2
    db_service_name: mariadb

- name: Execute {{ os_name }} specific installation tasks for {{ role_name }}
  include: "{{ os_name }}.yml"

- name: Enable autostart for Apache
  service:
    name: "{{ apache_service_name }}"
    enabled: yes

- name: Restart Apache
  service:
    name: "{{ apache_service_name }}"
    state: restarted

```

##### EXPECTED RESULTS

The value set for apache_service_name should be available to the subsequent tasks in the module.

##### ACTUAL RESULTS

The value set for apache_service_name is not recognized.

```paste below
TASK [install-lamp-stack : Enable autostart for Apache] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'apache_service_name' is undefined\n\nThe error appears to be in 'ami/roles/install-lamp-stack/tasks/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable autostart for Apache\n  ^ here\n"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by relrod** [comment]
@kurianinc,

I'm not immediately able to reproduce this on 2.9.0, it works as intended for me when I copy your tasks into a playbook or role (sans the `include` one), and the fact is available for use in a later task when I try.

Can you provide a *full* reproducer that shows the behavior and exhibits the error you showed?

**Comment by kurianinc** [comment]
@relrod I can describe the issue in detail below:

I later defined `apache_service_name` in roles/install-lamp-stack/vars/main.yml  as default value to see if that would help to resolve the issue:

```
apache_service_name: apache2
db_service_name: mariadb
```
When a CentOS module is loaded it is updated to `httpd`, in roles/install-lamp-stack/tasks/centos.yml:
```
- name: Update services to OS specific
  set_fact:
    apache_service_name: httpd
```
And in this update is not effective, it's still `apache2`.
```
LAMP stack main module
---
- name: Execute {{ os_name }} specific installation tasks for {{ role_name }}
  include: "{{ os_name }}.yml"

- name: Enable autostart for Apache
  service:
    name: "{{ apache_service_name }}"
    enabled: yes

- name: Restart Apache
  service:
    name: "{{ apache_service_name }}"
    state: restarted
```
The expectation is to get `apache_service_name` updated at least in the scope of role. That used to be the case before and not sure what changed in this version. Basically, the update done in vars/centos.yml is not available later in tasks/main.yml, it's still `apache2` as originally defined in vars/main.yml.
