### ISSUE TITLE
Issue with mutlliline yaml variables

### ISSUE THREAD

**Issue by geoffroya** [ansible/ansible#73040]
##### SUMMARY
It seems to me that the following issues are still present in Ansible 2.10 (tested on 2.10.4)
- https://github.com/ansible/ansible/issues/62841
- https://github.com/ansible/ansible/issues/65843

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-base

##### ANSIBLE VERSION
```
ansible 2.10.4
  config file = $HOME/.ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) [Clang 6.0 (clang-600.0.57)]
```

##### CONFIGURATION
```
DEFAULT_STDOUT_CALLBACK($HOME/.ansible.cfg) = yaml
DEFAULT_TIMEOUT($HOME/.ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE($HOME/.ansible.cfg) = /some/path/to/My-Keystore
```

##### OS / ENVIRONMENT
MacOS

##### STEPS TO REPRODUCE

Sample to reproduce :

`inventories/dev/group_vars/all.yml`:
```yaml
accent_issue:
  ko: 'Cette chaîne avec un saut de ligne ne contient pas d''accents (éèê)

  Quel dommage'
  ko_2: "Cette chaîne avec un saut de ligne ne contient pas d'accents (éèê)\nQuel dommage"
  ko_3: |-
    Cette chaîne avec un saut de ligne ne contient pas d'accents (éèê)`
    Quel dommage
  ok: 'Cette chaîne contient bien des accents (éèê)'
```

Sample playbook:
```yaml
---
- hosts: 127.0.0.1
  tasks:
  - debug:
      var: accent_issue
```

##### EXPECTED RESULTS
From given steps, I expect accents to be present in each variable.

##### ACTUAL RESULTS
Output - we can see that for each `ko*`param, accents are removed

```
ansible-playbook -i environments/dev/ monitor-debug.yml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [127.0.0.1] ********************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [debug] ************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] =>
  accent_issue:
    ko: |-
      Cette chane avec un saut de ligne ne contient pas d'accents ()
      Quel dommage
    ko_2: |-
      Cette chane avec un saut de ligne ne contient pas d'accents ()
      Quel dommage
    ko_3: |-
      Cette chane avec un saut de ligne ne contient pas d'accents ()`
      Quel dommage
    ok: Cette chaîne contient bien des accents (éèê)

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
