### ISSUE TITLE
urlencode filter doesn't accept encrypted variable

### ISSUE THREAD

**Issue by markwell-ch** [ansible/ansible#73054]
##### SUMMARY

When trying to pass a encrypted variable to the `urlencode` filter ansible 2.10 returns an error.

This does not affect ansible 2.9.16. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
filter

##### ANSIBLE VERSION
```
ansible 2.11.0.dev0
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/gits/ansible-debug/.venv/ansible-devel/lib/python3.8/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/username/gits/ansible-debug/.venv/ansible-devel/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
  jinja version = 2.11.2
  libyaml = False
```

```
ansible 2.10.4
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/gits/ansible-debug/.venv/ansible-2.10/lib/python3.8/site-packages/ansible
  executable location = /home/username/gits/ansible-debug/.venv/ansible-2.10/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

```

##### CONFIGURATION

Default Configuration

##### OS / ENVIRONMENT

Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE
Use the sample playbook below, the vault password is `test`.

```yaml
---
- hosts: localhost
  vars:
    vaulted_var: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        30353233336165306463306539316563386232666633346430626465393435663139396134303638
        6539303730373265346461386561333333383139316131650a303833363362643564373030383637
        37303732373564636666313431316664363262363836346231373334333838343464343634356165
        3039316538316234380a396534623733343633623831393736333533333438393034353835633764
        63393061633561306230633964343531333537393439363035356335666238363432

  tasks:
  - name: vaulted_var | urlencode
    debug:
      msg: "{{ vaulted_var | urlencode }}"
    ignore_errors: true
  - name: 'workaround: "{}".format(vaulted_var) | urlencode'
    debug:
      msg: '{{ "{}".format(vaulted_var) | urlencode }}'

```

##### EXPECTED RESULTS

The `vaulted_var` should be passed to `urlencode` and return the value of `vaulted_var` with url encoding.

vaulted_var: `this is a test!@#$%^&*()[]{}~/.`

expected result: `this%20is%20a%20test%21%40%23%24%25%5E%26%2A%28%29%5B%5D%7B%7D~/.`

##### ACTUAL RESULTS

```
TASK [vaulted_var | urlencode] ***********************************************************************************************************************************************************
task path: /home/username/gits/ansible-debug/sample.play:12
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None                                                                                                      
Trying to use vault secret=(FileVaultSecret(filename='/home/username/gits/ansible-debug/.vault_pass')) id=default to decrypt None
Trying secret FileVaultSecret(filename='/home/username/gits/ansible-debug/.vault_pass') for vault_id=default
Decrypt successful with secret=FileVaultSecret(filename='/home/username/gits/ansible-debug/.vault_pass') and vault_id=default
fatal: [localhost]: FAILED! => {                                                             
    "msg": "the field 'args' has an invalid value ({'msg': '{{ vaulted_var | urlencode }}'}), and could not be converted to an dict.The error was: not enough values to unpack (expected 2
, got 1)\n\nThe error appears to be in '/home/username/gits/ansible-debug/sample.play': line 12, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe o
ffending line appears to be:\n\n  tasks:\n  - name: vaulted_var | urlencode\n    ^ here\n"
}
...ignoring
```
