### ISSUE TITLE
ansible 2.8.x not support recursive copy on remote host

### ISSUE THREAD

**Issue by vtchel** [ansible/ansible#73076]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

copy
##### ANSIBLE VERSION

```
ansible 2.8.18
  config file = /Users/vladimir.tchelubeyev/Documents/Test/test_copy/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.9 (default, Nov 20 2020, 18:45:38) [Clang 12.0.0 (clang-1200.0.32.27)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/user/Documents/Test/test_copy/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/Users/user/Documents/Test/test_copy/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
DEFAULT_CALLBACK_WHITELIST(/Users/user/Documents/Test/test_copy/ansible.cfg) = ['profile_tasks']
DEFAULT_FORCE_HANDLERS(/Users/user/Documents/Test/test_copy/ansible.cfg) = True
DEFAULT_GATHERING(/Users/user/Documents/Test/test_copy/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/Users/user/Documents/Test/test_copy/ansible.cfg) = merge
DEFAULT_LOG_PATH(/Users/user/Documents/Test/test_copy/ansible.cfg) = /Users/user/Documents/Test/test_copy/ansible.log
DEFAULT_ROLES_PATH(/Users/user/Documents/Test/test_copy/ansible.cfg) = ['/Users/user/Documents/Test/common_installer/roles']
DEFAULT_STDOUT_CALLBACK(/Users/user/Documents/Test/test_copy/ansible.cfg) = debug
INVENTORY_IGNORE_EXTS(/Users/user/Documents/Test/test_copy/ansible.cfg) = ['Dockerfile']
RETRY_FILES_ENABLED(/Users/user/Documents/Test/test_copy/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Example fail
  hosts: remote_host
  vars:
    dest_dir: ~/dest_dir
    src_dir: ~/src_dir
  tasks:

    - name: Create old config dirs
      file:
        path: "{{ dest_dir }}/{{ item }}"
        state: directory
      loop:
        - ""
        - folder1
        - folder1/a_folder
    - name: Emulate old files
      file:
        state: touch
        dest: "{{ dest_dir }}/{{ item }}"
      loop:
        - folder1/a_file.txt
        - folder1/a_folder/a_file.txt

    - name: Create new dirs
      file:
        path: "{{ src_dir }}/{{ item }}"
        state: directory
      loop:
        - ""
        - folder1
        - folder1/a_folder
        - folder1/b_folder

    - name: Emulate new files
      copy:
        dest: "{{ src_dir }}/{{ item }}"
        content: "A new file"
      loop:
        - folder1/a_file.txt
        - folder1/b_file.txt
        - folder1/a_folder/a_file.txt
        - folder1/a_folder/b_file.txt
        - folder1/b_folder/a_file.txt
        - folder1/b_folder/b_file.txt

    - name: copy
      copy:
        src: "{{ src_dir }}/"
        dest: "{{ dest_dir }}"
        remote_src: yes

    - name: Test success copy
      stat:
        path: "{{ dest_dir }}/folder1/a_folder/b_file.txt"
      register: test
      failed_when: not test.stat.exists

```

##### EXPECTED RESULTS

All files copies to dest folder

##### ACTUAL RESULTS

Part files do not copies

```paste below

```
