### ISSUE TITLE
The value "8181" (type int) was converted to "'8181'" (type string)

### ISSUE THREAD

**Issue by goldyfruit** [ansible/ansible#73073]
##### SUMMARY
Based on the documentation, the `destination_port` seems to be an integer but during the playbook execution I got a warning message.

An another thing is that, I don't get this warning and it's part of a DROP.

```
[WARNING]: The value "8181" (type int) was converted to "'8181'" (type string). If this does not look like what you expect, quote
the entire value to ensure it does not change.
```
![image](https://user-images.githubusercontent.com/614115/103245615-b80b3e80-492e-11eb-863d-343aaa4f38cc.png)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin.iptables

##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = /home/goldyfruit/Git/ansible-playbooks-mycroft/ansible.cfg
  configured module search path = ['/home/goldyfruit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Dec  8 2020, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

##### CONFIGURATION

```
[defaults]
host_key_checking = False

[ssh_connection]
pipelining = True
```

##### STEPS TO REPRODUCE
```
- name: Allow localhost to communicate with port 8181
  iptables:
    chain: INPUT
    in_interface: lo
    destination_port: 8181
    protocol: tcp
    jump: ACCEPT
    comment: "Allow connections from localhost to Mycroft message bus service"

- name: Block Mycroft message bus service port 8181
  iptables:
    chain: INPUT
    destination_port: 8181
    protocol: tcp
    jump: DROP
    comment: "Drop connections on Mycroft message bus service"
```
