### ISSUE TITLE
file: recurse=yes is not able to set permission in the nested directory

### ISSUE THREAD

**Issue by Udayendu** [ansible/ansible#73082]
##### SUMMARY
Ansible **file** module is not working as expected even if **recurse=yes** parameter is set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- file module

##### ANSIBLE VERSION
```
$ pip3 show ansible
Name: ansible
Version: 2.10.4
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.6/site-packages
Requires: ansible-base

$ pip3 show ansible-base
Name: ansible-base
Version: 2.10.4
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.6/site-packages
Requires: jinja2, PyYAML, cryptography, packaging
```

##### OS / ENVIRONMENT
- Provision Server: CentOS 8.3 
- Target systems: OEL 8.3

##### STEPS TO REPRODUCE
- Create a directly and try to change the ownership/group ownership using file module
- It will create the directory but wont be able to set the permission in the nested directory
- Only permission is set correctly in the parent directory

##### EXPECTED RESULTS
- Permission should set correctly in the child directory as well

##### ACTUAL RESULTS
- Permission is set only on the parent directly

```
TASK [xxxxxx: Create mount point "/app/avaya" and set permission] 
************************************************************************************************
changed: [xxx.xxx.xxx.xxx]

TASK [xxxxxx : debug] 
************************************************************************************************
ok: [xxx.xxx.xxx.xxx] => {
    "output": {
        "changed": true,
        "diff": {
            "after": {
                "group": 1001,
                "mode": "0755",
                "owner": 1001,
                "path": "/app/avaya",
                "state": "directory"
            },
            "before": {
                "group": 0,
                "mode": "0750",
                "owner": 0,
                "path": "/app/avaya",
                "state": "absent"
            }
        },
        "failed": false,
        "gid": 1001,
        "group": "jboss",
        "mode": "0755",
        "owner": "jboss",
        "path": "/app/avaya",
        "size": 4096,
        "state": "directory",
        "uid": 1001
    }
}
```

- Directory permission out put after creation:
```
# ls -ld /app
drwxr-xr-x 3 jboss jboss 4096 Dec 30 03:32 /app

# ls -ld /app/avaya/
drwxr-xr-x 2 root root 6 Dec 30 03:32 /app/avaya/

# tree /app
/app
└── avaya

1 directory, 0 files
```

- Ansible play:

```
- name: Service user creation
  user:
    name: "{{ item }}"
    state: present
  with_items:
    - jboss
    - appdev
    - appmonitor

- name: Create mount point "{{ appmount_point }}" and set permission
  file:
    path: "{{ appmount_point }}"
    state: directory
    recurse: yes
    owner: jboss
    group: jboss
    mode: '0755'
  register: output

- debug: var=output
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Udayendu** [comment]
One additional info:

- This mount point is used to mount a local volume using the below code:

```
- name: Mount optlv00 logical volume under '{{ appmount_point }}'
  mount:
    name: '{{ appmount_point }}'
    src: /dev/optvg/optlv00
    fstype: xfs
    state: mounted
```

And seems like mount ansible module is making some change here and setting the directory permission to root.root . And if I changed the permission after mounting the directory, its working as expected. Here is the change that's working:

```
---
- name: Service user creation
  user:
    name: "{{ item }}"
    state: present
  with_items:
    - jboss
    - salansible

- name: appvg volume group creation
  lvg:
    vg: appvg
    pvs: '{{ disk_name }}'

- name: applv00 lvm creation
  lvol:
    vg: appvg
    lv: applv00
    size: 100%FREE

- name: Create a filesystem for applv00
  filesystem:
    fstype: xfs
    dev: /dev/appvg/applv00

- name: Create mount point "{{ appmount_point }}"
  file:
    path: "{{ appmount_point }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Mount applv00 logical volume under '{{ appmount_point }}'
  mount:
    name: '{{ appmount_point }}'
    src: /dev/appvg/applv00
    fstype: xfs
    state: mounted

- name: Change the permission of '{{ appmount_point }}' directory
  file:
    path: "{{ appmount_point }}"
    state: directory
    recurse: yes
    owner: jboss
    group: jboss
    mode: '0755'
```
