### ISSUE TITLE
Azure Interface Card - Allow Create Static IP NIC Without Need to Specify an Address

### ISSUE THREAD

**Issue by pramos84** [ansible/ansible#73138]
---
name: ✨ Feature request
about: [AZURE] Allow Create Static IP NIC Without Need to Specify an Address
---
##### SUMMARY
Hi guys. In our Azure environment, we create the network interface cards with static address. We don't care to what will be the address, but once it's defined, we don't want it changes. I believe that others companies maybe adopts the same practice, so would be very usefull if we could create a network interface card (using azure_rm_networkinterface module), setting the allocation method as "Static", without need to inform an IP address. I appreciate any help in this way.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_networkinterface

##### ADDITIONAL INFORMATION
This code block below is unable to create a NIC, but it would be great if it should.

```yaml
  - name: Creates NIC with static allocation method without specify address
    azure.azcollection.azure_rm_networkinterface:
      resource_group: rg-ansible
      virtual_network:
        name: vnet-ansible
        resource_group: rg-ansible
      subnet_name: sn-main
      name: vm-hostname-nic1
      create_with_security_group: False
      ip_configurations:
      - name: ipconfig1
        private_ip_allocation_method: Static
        primary: True
```
