### ISSUE TITLE
ansible-galaxy install should fail when cloning a git repo that contains git-lfs files that weren't downloaded

### ISSUE THREAD

**Issue by jantari** [ansible/ansible#73141]
##### SUMMARY
Currently when using a command like `ansible-galaxy install --force --role-file requirements.yml` with a requirements.txt that contains git repositories such as:

```yaml
- name: myfunnyrole
  src: ssh://git@gitlab.company.com/ansible-roles/funny.git
  scm: git
  version: master
```

and the git-repository contains git-lfs files but `git-lfs` is not installed on the local machine, the `ansible-galaxy install` command will seemingly complete successfully, but the downloaded role is missing files and will throw errors when subsequently run.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-galaxy

##### ADDITIONAL INFORMATION

I realize it is default git-behavior to not throw an error and just clone the references to git-lfs files instead of fetching them when `git-lfs` is not installed, but IMO this is kind of not user-friendly especially because there is no way to define in the `requirements.txt` that a role requires git-lfs so it is hard to inform the user of this dependency prior to them fetching the role.

I thought about checking/asserting that `git-lfs` is installed on localhost as the first task in my role, but someone might want to copy the fully-fetched role to a machine without `git-lfs` and then such a task would throw a false alarm.

I think `ansible-galaxy install` should fail with a warning when it finds that it cannot properly fetch a roles' files due to missing `git-lfs`.

Example requirements.txt file:
```yaml
- name: myfunnyrole
  src: ssh://git@gitlab.company.com/ansible-roles/funny.git
  scm: git
  version: master
```
The `funny` role must contain and depend on git-lfs files.

Thanks!
