### ISSUE TITLE
User and group not set for symlink in file module - defaults to root

### ISSUE THREAD

**Issue by maunzCache** [ansible/ansible#73143]
##### SUMMARY
When creating a symlink with the file module and explicitly setting the owner and group parameter, ansible will use the user root and the group root. This fails our integration tests recently and seems like a regression.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file module

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/opt/ansible-custom/modules']
  ansible python module location = /home/USER/.local/lib/python3.8/site-packages/ansible
  executable location = /home/USER/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-custom/callback']
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-custom/lookup_plugins']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-custom/modules']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = ['/opt/ansible-custom/module_utils']
```

##### OS / ENVIRONMENT

Linux 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
# Variables "bamboo_user" and "bamboo_group" are set in defaults/main.yml. Checked that twice.

- name: grails-executable | Create symlink to latest version
  file:
    src: "/{{ bamboo_executables_dir }}/grails-{{ executable_value.version }}"
    dest: "/{{ bamboo_grails_latest_symlink }}"
    state: link
    owner: "{{ bamboo_user }}"
    group: "{{ bamboo_group }}"
    force: yes
  when: >
    not unit_test and
    executable_value.latest
  tags:
    - bamboo
    - grails-executable
```

I can do a workaround with become which works for the user but not the group. The group defaults to users.
```yaml
# Variables "bamboo_user" and "bamboo_group" are set in defaults/main.yml. Checked that twice.

- name: grails-executable | Create symlink to latest version
  become: yes
  become_user: "{{ bamboo_user }}"
  file:
    src: "/{{ bamboo_executables_dir }}/grails-{{ executable_value.version }}"
    dest: "/{{ bamboo_grails_latest_symlink }}"
    state: link
    owner: "{{ bamboo_user }}"
    group: "{{ bamboo_group }}"
    force: yes
  when: >
    not unit_test and
    executable_value.latest
  tags:
    - bamboo
    - grails-executable
```

##### EXPECTED RESULTS

Symlink created for user {{ bamboo_user }} and group {{ bamboo_user }}

##### ACTUAL RESULTS

```paste below
I, [2021-01-07T15:09:37.527291 #55543]  INFO -- default-amazon-linux-2: [0;33mchanged: [localhost] => {"changed": true, "dest": "/opt/bamboo-executables/groovy-latest", "gid": 0, "group": "root", "mode": "0777", "owner": "root", "size": 36, "src": "/opt/bamboo-executables/groovy-2.5.8", "state": "link", "uid": 0}[0m
```
