### ISSUE TITLE
No package matching 'nginx' is available

### ISSUE THREAD

**Issue by thamaraiselvam** [ansible/ansible#73156]
##### SUMMARY
Randomly getting `No package matching 'nginx' is available` error when installing package on newly created machine.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Ansible-playbook

##### ANSIBLE VERSION

```paste below
ansible 2.10.3
  config file = path/ansible.cfg
  configured module search path = ['/Users/thamaraiselvam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.4/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Dec 10 2020, 11:11:14) [Clang 12.0.0 (clang-1200.0.32.27)]

```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/Users/thamaraiselvam/repo/github.com/petclinic-infra/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/Users/thamaraiselvam/repo/github.com/petclinic-infra/ansible/ansible.cfg) = ['/Users/thamaraiselvam/repo/github.com/petclinic-infra/ansible/inventories']
HOST_KEY_CHECKING(/Users/thamaraiselvam/repo/github.com/petclinic-infra/ansible/ansible.cfg) = False
```

<strong> My playbook</strong>

```yaml
- hosts: frontend
  remote_user: root
  gather_facts: false
  tasks:
    - name: Install nginx server
      block:
        - name: Update cache
          apt:
            update_cache: true
        - name: Install nginx
          apt:
            name: nginx
            state: latest
      become: yes
      become_user: root
```

##### EXPECTED RESULTS
Should install all packages given playbook

##### ACTUAL RESULTS
Getting no package found error randomly and it is very flaky. If try again then it works fine.
