### ISSUE TITLE
Issue with import_playbook variable substitution while using lookup('file')

### ISSUE THREAD

**Issue by shubhamsetia05** [ansible/ansible#73155]
##### SUMMARY

As import_playbook doesn't support vars_files so I am using something like below to read from var file
cluster_vars: "{{ lookup('file','vars_files/es_vars.yml' ) | from_yaml }}" 
but variable substitution is not happening if I am referring declaring one variable in vars_files and calling that variable value while declaring 2nd variable in same vars_file itself.

Please check steps to reproduce, actual and expected results below.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
import_playbook
```
##### ANSIBLE VERSION

```
2.8.1
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Below code is from my playbook:
```
- name: Spawning ES Data Nodes
  import_playbook: provision.yml
  vars:
    cluster_vars: "{{ lookup('file','vars_files/es_vars.yml' ) | from_yaml }}"
    provision_nodes_ec2_volumes: "{{ cluster_vars['provision_nodes_ansible2_ec2_volumes_data_node'] }}
```

Below code is from my vars file:
```
provision_nodes_ansible2_ec2_volumes_master_node:
  - device_name: /dev/sda1
    ebs:
      volume_size: 15
      delete_on_termination: true
  - device_name: /dev/xvdb
    virtual_name: ephemeral0

provision_nodes_ec2_volumes_data_node: "{{ provision_nodes_ec2_volumes_master_node }}"
```

##### EXPECTED RESULTS

```
TASK [provision_nodes : debug] ***************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Var is [{'ebs': {'delete_on_termination': True, 'volume_size': 15}, 'device_name': '/dev/sda1'}, {'virtual_name': 'ephemeral0', 'device_name': '/dev/xvdb'}]"
}
```

##### ACTUAL RESULTS

```
TASK [provision_nodes : debug] ***************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Var is {{ provision_nodes_ansible2_ec2_volumes_master_node }}"
}
```

```paste below

```
