### ISSUE TITLE
[Bug] vars_files  more than one file

### ISSUE THREAD

**Issue by aybcoo** [ansible/ansible#73166]
##### SUMMARY

When vars_files is only one ,ansible can execute, but more than one file ,bug is show.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vars_files
##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /opt/projects/DSExtension/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/opt/projects/DSExtension/ansible.cfg) = [u'/opt/projects/DSExtension/inventory/hosts']
DEFAULT_MANAGED_STR(/opt/projects/DSExtension/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_REMOTE_USER(/opt/projects/DSExtension/ansible.cfg) = root
DEFAULT_ROLES_PATH(/opt/projects/DSExtension/ansible.cfg) = [u'/opt/projects/DSExtension/roles']
```

##### STEPS TO REPRODUCE

```yaml
main1.yml
- hosts: localhost
  vars_files: 
    - ../vars/nx1.yml
    - ../vars/nx2.yml
  vars:
    - var1: varvar1
  tasks:
    - name: output nx1.yml var
      debug:
        msg={{ nxtestvar1 }}|{{ nxtestvar2 }}
    
    - debug:
        msg={{ nginx.servername1 }}|{{ nginx.servername2 }}

nx1.yml
nxtestvar1: nxfile1
nxtestvar2: nxfile2

nginx:
    servername1: nx.server1.com
    servername2: nx.server2.com

nx2.yml
# nxtestvar5: nxfile5
# nxtestvar6: nxfile6

# nginx:
#   servername5: nx.server5.com
#   servername6: nx.server6.com
```

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'servername1'\n\nThe error appears to be in '/opt/projects/DSExtension/roles/test/tasks/main1.yml': line 13, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug:\n      ^ here\n"}

```paste below
ansible-playbook roles/test/tasks/main1.yml 
```
