### ISSUE TITLE
Ansible doesn't seem to template multiple `item` calls in a `loop` using `k8s` module

### ISSUE THREAD

**Issue by chuckersjp** [ansible/ansible#73194]
##### SUMMARY

When using the `k8s` module and a `loop` that has several `item` calls in it, it appears that
ansible will only template out the first `item` and treat the rest as verbatum code.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`k8s` and/or ansible core

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /root/ocp-hybrid-ansible-master/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
DEFAULT_REMOTE_USER(/root/ocp-hybrid-ansible-master/ansible.cfg) = core
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.9 (Maipo)
 
OCP 4.6.9

##### STEPS TO REPRODUCE

```yaml
- name: Setup machine config pool for maintenance group "{{item}}"
  k8s:
    kubeconfig: "{{ kubeconfig_location }}"
    state: present
    merge_type:
    - merge
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: "maintgroup{{item}}"
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker]}
        nodeSelector:
          matchLabels:
            "maintgroup{{item}}": ""
  loop:
    - "1"
```

##### EXPECTED RESULTS

The `nodeSelector` section should appear as:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: maintgroup1
spec:
  machineConfigSelector:
  matchExpressions:
     - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker]}
   nodeSelector:
         matchLabels:
            maintgroup1: ""
```
##### ACTUAL RESULTS

```paste below
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: maintgroup1
      spec:
        machineConfigSelector:
          matchExpressions:
            - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker]}
        nodeSelector:
          matchLabels:
            maintgroup{{item}}: ""
```
The `metadata: name:` is correct.  the `nodeSelector: matchLabels:` part is incorrect.
