### ISSUE TITLE
nxos_config: idempotency not working with src module for config under interfaces

### ISSUE THREAD

**Issue by syed-shah100** [ansible/ansible#73203]
Can someone please test the following scenario?

ansible task:
```
    - name: Add DHCP Config to NXOS Devices
      nxos_config:
        src: ./{{ inventory_hostname }}.cfg
        diff_against: running
        save_when: modified
```

j2 to build the config:
```
{% for ip in dhcp_servers %}
interface Vlan1
  ip dhcp relay address {{ ip }}
interface Ethernet1/49
  ip dhcp relay address {{ ip }}
interface Ethernet1/50
  ip dhcp relay address {{ ip }}
{% endfor %}
```

.cfg:
```
interface Vlan1
  ip dhcp relay address 10.1.1.2
interface Ethernet1/49
  ip dhcp relay address 10.1.1.2
interface Ethernet1/50
  ip dhcp relay address 10.1.1.2
```

the config always gets pushed even if it exists on the switch, tried with spacing too.

It doesn't get pushed when added directly on the switch:
```
    - name: DHCP
      nxos_config:
        lines:
          - ip dhcp relay address 10.1.1.2
        parents: interface Vlan1
```

Note: The above config was tested with Ansible Version 2.9.11
