### ISSUE TITLE
Special variable group_names list items out of order

### ISSUE THREAD

**Issue by tinkerjs** [ansible/ansible#73208]
##### SUMMARY
When using the group_names variable i noticed that the order in which the list items are returned is dictated by depending the upper/lower case of nested child group names.
 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Special Variables: group_names

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = /export/home/e140214/appdynamics_automation/playbooks/ansible.cfg
  configured module search path = ['/export/home/e140214/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /SWA/EMEAutomation/Apps/miniconda/lib/python3.7/site-packages/ansible
  executable location = /SWA/EMEAutomation/Apps/miniconda/bin/ansible
  python version = 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]

```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/export/home/e140214/appdynamics_automation/playbooks/ansible.cfg) = ['/export/home/e140214/eme_ansible_inventory/appd/appd_by_appl.yml']
DEFAULT_LOG_PATH(/export/home/e140214/appdynamics_automation/playbooks/ansible.cfg) = /export/home/e140214/appdynamics_automation/log/ansible.log
HOST_KEY_CHECKING(/export/home/e140214/appdynamics_automation/playbooks/ansible.cfg) = False

```
##### OS / ENVIRONMENT

RHEL7 Source and RHEL 6/7 targets. 

##### STEPS TO REPRODUCE
1. Create an inventory yaml file that looks like the following:
```
all:
  children:
    NonprodAppDefault:
      children:
        chg0240322:
          vars:
            controller_env: test
          hosts:
            hdqqclansiap001:
            hdqqclbcbwtb001:
```
2. Create a playbook with the following tasks:
```
---
  - hosts: all
    ignore_errors: yes

    tasks:
      - name: Show Inventory Group
        debug:
          var: group_names
```

3. Execute the playbook against the inventory file. 
```
ansible-playbook -i ../../eme_ansible_inventory/appd/appd_by_adhoc.yml variablesTest.yml --limit hdqqclansiap001
```
4. Update the inventory file to look like the following:
```
all:
  children:
    NonprodAppDefault:
      children:
        CHG0240322:
          vars:
            controller_env: test
          hosts:
            hdqqclansiap001:
            hdqqclbcbwtb001:
```

5. Execute the playbook against the inventory file. 
```
ansible-playbook -i ../../eme_ansible_inventory/appd/appd_by_adhoc.yml variablesTest.yml --limit hdqqclansiap001
```

##### EXPECTED RESULTS
The expectation is that the group names list items are in hierarchy order regardless of the text case. 

Output from both execution steps should be:
```
TASK [Show Inventory Group] ******************************************************************************************************************************************************
ok: [hdqqclansiap001] => {
    "group_names": [
        "NonprodAppDefault",
        "chg0240322"
    ]
}
```

##### ACTUAL RESULTS
The output from step 3 is correct. 
```
TASK [Show Inventory Group] ******************************************************************************************************************************************************
ok: [hdqqclansiap001] => {
    "group_names": [
        "NonprodAppDefault",
        "chg0240322"
    ]
}
```
The output from step 5 appears to be incorrect:
```
TASK [Show Inventory Group] ******************************************************************************************************************************************************
ok: [hdqqclansiap001] => {
    "group_names": [
        "CHG0240322",
        "NonprodAppDefault"
    ]
}
```
