### ISSUE TITLE
ansible_facts.service retuns incorrect state

### ISSUE THREAD

**Issue by Perfect10NickTailor** [ansible/ansible#73215]
it was awhile ago but there has been no progress on it....

I am using the latest version

##### SUMMARY

When systemd stop and starts a service and then you try to get check the state with ansible_facts.service it will say its stopped when it on the server its running. 

If i run the playbook a couple times eventually it gives me the correct state and shows theyre running....

The state return is not accurate. 
Ansible shows the service is stopped
=============================
ok: [app11] => {
    "ansible_facts.services[\"tomcat.service\"]": {
        "name": "tomcat.service",
        "source": "systemd",
        "state": "stopped",
        "status": "enabled"
    }
}

Server shows the service is running just fine.
=================================
root@app11 bin]# systemctl status tomcat
● tomcat.service - Apache Tomcat Web Application Container
   Loaded: loaded (/etc/systemd/system/tomcat.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-01-13 13:17:22 GMT; 9min ago
 Main PID: 16557 (java)
   CGroup: /system.slice/tomcat.service
           └─16557 /siapp/vision/live/jre/bin/java -Djava.util.logging.config.file=/opt/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -serv...

Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk systemd[1]: tomcat.service: main process exited, code=exited, status=143/n/a
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk systemd[1]: Stopped Apache Tomcat Web Application Container.
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk systemd[1]: Unit tomcat.service entered failed state.
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk systemd[1]: tomcat.service failed.
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk systemd[1]: Starting Apache Tomcat Web Application Container...
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk startup.sh[16547]: Existing PID file found during start.
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk startup.sh[16547]: Removing/clearing stale PID file.
Jan 13 13:17:22 v-sitsapp11.brunel.ac.uk systemd[1]: Started Apache Tomcat Web Application Container.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

redhat 7, patched to the latest

##### STEPS TO REPRODUCE

install tomcat
start tomcat
get ansible_facts.service regarding tomcat service from client 

```yaml
- name: Create symbolic link for "tomcat" in /opt
  file:
    src: /siapp/vision/{{ tomcatenvironment }}/tomcat/
    path: /opt/tomcat
    force: yes
    state: link

- name: Enable tomcat service on startup
  shell: systemctl enable tomcat

- name: Null tomcat.service file
  shell: ">/etc/systemd/system/tomcat.service"

- name: Edit tomcat.service for systemd
  blockinfile:
    dest: /etc/systemd/system/tomcat.service
    insertafter:
    block: |
      [Unit]
      Description=Apache Tomcat Web Application Container
      After=syslog.target network.target

      [Service]
      Type=forking

      Environment=JAVA_HOME=/siapp/vision/{{ java_home }}/jre/bin/java
      Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
      Environment=CATALINA_HOME=/opt/tomcat
      Environment=CATALINA_BASE=/opt/tomcat
      Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/bin/kill -15 $MAINPID

      User=tomcat
      Group=tomcat
      UMask=
      RestartSec=10
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Null /etc/sysconfig/tomcat file
  shell: ">/etc/sysconfig/tomcat"

- name: Edit tomcat.service for systemd
  blockinfile:
    dest: /etc/sysconfig/tomcat
    insertafter:
    block: |
      RUN_AS_USER=tomcat # Adjust run user here
      CATALINA_HOME=/siapp/vision/{{ tomcatenvironment }}/tomcat
      JAVA_HOME=/siapp/vision/{{ java_home }}/jre


- name: Start tomcat service with Systemd
  systemd:
    name: tomcat
    daemon_reload: yes

- name: get service facts
  service_facts:

- name: Check to see if tomcat is running
  debug:
    var: ansible_facts.services["tomcat.service"]

```

##### EXPECTED RESULTS

ok: [app11] => {
    "ansible_facts.services[\"tomcat.service\"]": {
        "name": "tomcat.service",
        "source": "systemd",
        "state": "running",
        "status": "enabled"
    }
}

##### ACTUAL RESULTS

TASK [AddTomCatSystemD : Check to see if tomcat is running] *****************************************************************************************************************************************
ok: [app11] => {
    "ansible_facts.services[\"tomcat.service\"]": {
        "name": "tomcat.service",
        "source": "systemd",
        "state": "stopped",
        "status": "enabled"
    }
}

```paste below

```
