### ISSUE TITLE
Ansible uses incorrect value for parent role's params when called in child roles

### ISSUE THREAD

**Issue by tmoschou** [ansible/ansible#73212]
##### SUMMARY

When running a single play that uses a `parent` role via the plays `roles:` option twice, with different `vars:`, a child role that is either called from the parent role via `meta.yaml`'s `dependencies:`, `include_role:` or `import_role` uses the last value. However the parent roles _does_ use the correct var.

E.g.

`play.yaml`:
``` yaml
---
- hosts: localhost
  roles:
    - role: parent
      vars:
        parent_var: first
    - role: parent
      vars:
        parent_var: second
```

`roles/parent/meta/main.yaml`:
```yaml
---
allow_duplicates: true
dependencies:
  - role: child
```
(could also call `child` role via `import_role` or `include_role` - the same error happens in either case).

`roles/child/meta/main.yaml`:
```yaml
---
allow_duplicates: true
```

`roles/child/tasks/main.yaml`:
```yaml
---
- debug:
    var: parent_var
```

---

Augmenting the child role invocation with
```yaml
vars:
  child_var: "{{ parent_var }}"
```
for either `dependencies:`, `import_role:` or `include_role:` does not help (the `child_var` also uses the last value).

Oddly invoking the `parent` role at the play root using `import_role` (which I would expect to be equivalent to play's `roles:` ) or `include_role`  _does_ work, and is a workaround - regardless of how the child role is invoked in the parent role and regardless if `vars:` role params are used or not on the child.

`play.yaml`:
``` yaml
---
- hosts: localhost
  tasks:
    - import_role:
        name: parent
      vars:
        parent_var: first
    - import_role:
        name: parent
      vars:
        parent_var: second
```

Further, setting `ANSIBLE_PRIVATE_ROLE_VARS=true` results in the variable undefined in the child role - I would expect this to still be in scope while parent role is still being called. In a attempt to work around the undefined var, trying to pass through the parent var as a child role param var explicitly (regardless of calling the child role either via `meta/main.yaml` dependencies, `include_role:`, `import_role:`) results in infinite recursion, or if renaming the variable to an alias then undefined still. E.g.

`roles/parent/meta/main.yaml`:
```yaml
---
allow_duplicates: true
dependencies:
  - role: child
    vars:
      # may cause infinite recursion
      parent_var: "{{ parent_var }}"  
      # or
      child_var: "{{ parent_var }}" # either prints the last var "second" or still undefined if ANSIBLE_PRIVATE_ROLE_VARS=true
```

As such I do not think there is any way to ensure a variable is used correctly in a child role if it is defined as a role param on the parent role in a plays `roles:` block.

Possibly relates to https://github.com/ansible/ansible/pull/69040 and associated issues.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`lib/ansible/playbook/role`

##### ANSIBLE VERSION
```
ansible 2.9.13
  config file = None
  configured module search path = ['/Users/mos095/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.13_1/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Oct 18 2020, 02:16:06) [Clang 12.0.0 (clang-1200.0.32.2)]
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

The following zip contains various minimal cases which each error in one way or another. In all cases, every role has `allow_duplicates: true` and no role defines any `defaults/main.yaml` or `vars/main.yaml` - the only variables defined are role parameters. 

Unzip the following hosts/plays/roles: 
[ansible.zip](https://github.com/ansible/ansible/files/5807528/ansible.zip)

```
ansible
├── hosts
├── play-1.yaml
├── play-2.yaml
├── play-3.yaml
├── play-4.yaml
├── play-5.yaml
└── roles
    ├── child1
    │   ├── meta
    │   │   └── main.yaml  # {"allow_duplicates":true}
    │   └── tasks
    │       └── main.yaml  # [{"debug":{"var":"parent_var"},"name":"debug parent_var"}]
    ├── child2
    │   ├── meta
    │   │   └── main.yaml  # {"allow_duplicates":true}
    │   └── tasks
    │       └── main.yaml  # [{"debug":{"var":"child_var"},"name":"debug vars"}]
    ├── parent1
    │   └── meta
    │       └── main.yaml  # {"allow_duplicates":true,"dependencies":[{"role":"child1"}]}
    ├── parent2
    │   └── meta
    │       └── main.yaml  # {"allow_duplicates":true,"dependencies":[{"role":"child1","vars":{"parent_var":"{{ parent_var }}"}}]}
    ├── parent3
    │   └── meta
    │       └── main.yaml  # {"allow_duplicates":true,"dependencies":[{"role":"child2","vars":{"child_var":"{{ parent_var }}"}}]}
    ├── parent4
    │   ├── meta
    │   │   └── main.yaml  # {"allow_duplicates":true}
    │   └── tasks
    │       └── main.yaml  # [{"import_role":{"name":"child1"},"name":"import role child1"}]
    └── parent5
        ├── meta
        │   └── main.yaml  # {"allow_duplicates":true}
        └── tasks
            └── main.yaml  # [{"include_role":{"name":"child1"},"name":"include role child1"}]
```

Run the following (with and without `export ANSIBLE_PRIVATE_ROLE_VARS=true`)
```bash
for i in $(seq 1 5); do
  ansible-playbook -i hosts "play-$i.yaml"  
done
```

##### EXPECTED RESULTS
In each case should print `"first"` followed by `"second"`. E.g.

```
PLAY [localhost] *******************************************************************

TASK [Gathering Facts] *************************************************************
ok: [localhost]

TASK [child1 : debug parent_var] ***************************************************
ok: [localhost] => {
    "parent_var": "first"
}

TASK [child1 : debug parent_var] ***************************************************
ok: [localhost] => {
    "parent_var": "second"
}

PLAY RECAP *************************************************************************
localhost: ok=3  changed=0  unreachable=0  failed=0  skipped=0  rescued=0  ignored=0
```

(Note for `play-3.yaml` / `parent3`, the debug var is `child_var` instead)

##### ACTUAL RESULTS

For `ANSIBLE_PRIVATE_ROLE_VARS=false` or unset (the default), prints `"second"` twice, except for `play-2.yaml` / `parent2` which prints 
```
An unhandled exception occurred while templating '{{ parent_var }}'. Error was a <class 'ansible.errors.AnsibleError'>,
... original message: recursive loop detected in template string: {{ parent_var }}"
```

For `ANSIBLE_PRIVATE_ROLE_VARS=true`, prints `"VARIABLE IS NOT DEFINED!"` (even for `play-3.yaml` / `parent3`), except for `play-2.yaml` / `parent2` which prints 
```
An unhandled exception occurred while templating '{{ parent_var }}'. Error was a <class 'ansible.errors.AnsibleError'>,
... original message: recursive loop detected in template string: {{ parent_var }}"
```

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/playbook/role`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is a function of how `vars:` on a role are scoped.  `vars:` on a role are scoped at the play level, so the last one defined wins.

You may instead want to use role "params" which are scoped to the role:

```
---
- hosts: localhost
  roles:
    - role: parent
      parent_var: first
    - role: parent
      parent_var: second
```

See also: https://github.com/ansible/ansible/pull/69040

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
