### ISSUE TITLE
Ansible prefix "|-" on an encrypted variable on uri module

### ISSUE THREAD

**Issue by ottobits** [ansible/ansible#73227]
##### SUMMARY
Calling a webservice api  - described here [Cyberark API](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/CyberArk%20Authentication%20-%20Logon_v10.htm?tocpath=Developer%7CREST%20APIs%7CAuthentication%7CLogon%7C_____1)  - with POST method  to authenticate and ansible uri module, encrypting the login password by vault, the password variable seems to be send in body with a leading "|-" 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
net_tools/basics/uri.py

##### ANSIBLE VERSION
```
ansible 2.9.15
```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=30m
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /home/rootssh/.ansible/tmp/ansible-local-4969iz44or2j
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.6

##### STEPS TO REPRODUCE

Use the uri module on an API with a POST method asking for a login and a password.
Encrypt the password by vault, then execute with -vvv
```yaml
     vault_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32633331626563343136306431623537656132353764336362393835643637373361666538383039
          3731643035616563356630343264353462386631393865390a653465656135366662633334643466
          35663932623764626637643166343236393235653464633032333936623636306637376633336264
          6234383062303631650a346162366364376338313930346130366664346263303437386234343266
          3538
    uri:
      url: https://xxxxxxxxx/PasswordVault/API/auth/LDAP/Logon
      method: POST
      content: application/json
      body_format: json
      body:
       username: my_username
       password: "{{ vault_password }}"
```

##### EXPECTED RESULTS
The session token described by API:

[Cyberark API](https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/CyberArk%20Authentication%20-%20Logon_v10.htm?tocpath=Developer%7CREST%20APIs%7CAuthentication%7CLogon%7C_____1)

##### ACTUAL RESULTS
Check the body with the "|-" before my_password

```
fatal: [localhost]: FAILED! => changed=false
  access_control_expose_headers: Warning
  cache_control: no-cache,no-store, no-cache, must-revalidate
  connection: close
  content: '{"ErrorCode":"CAWS00001E","ErrorMessage":"CASW062E Input parameter for [Password] value is invalid"}'
  content_length: '100'
  content_type: '********; charset=utf-8'
  date: Thu, 14 Jan 2021 11:32:37 GMT
  elapsed: 0
  expires: '-1'
  invocation:
    module_args:
      attributes: null
      backup: null
      body:
       password: |-
          my_password
        username: my_username
      body_format: json
      client_cert: null
      client_key: null
      content: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      creates: null
      delimiter: null
      dest: null
      directory_mode: null
      follow: false
      follow_redirects: safe
      force: false
      force_basic_auth: false
      group: null
      headers:
        Content-Type: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      http_agent: ansible-httpget
      method: POST
      mode: null
      owner: null
      regexp: null
      remote_src: null
      removes: null
      return_content: false
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: null
      status_code:
      - 200
      timeout: 30
      unix_socket: null
      unsafe_writes: null
      url: https://XXXXXXXX/PasswordVault/API/auth/LDAP/Logon
      url_password: null
      url_username: null
      use_proxy: true
      validate_certs: false
  json:
    ErrorCode: CAWS00001E
    ErrorMessage: CASW062E Input parameter for [Password] value is invalid
  msg: 'Status code was 500 and not [200]: HTTP Error 500: Internal Server Error'
  pragma: no-cache,no-cache
  redirected: false
  set_cookie: mobileState=Desktop; path=/PasswordVault/; SameSite=None; secure; HttpOnly
  status: 500
  strict_transport_security: max-age=31536000; includeSubDomains
  url: https://xxxxxxxxxxx/PasswordVault/API/auth/LDAP/Logon
  x_content_type_options: nosniff
  x_frame_options: SAMEORIGIN
  x_ua_compatible: IE=EmulateIE8
  x_xss_protection: 1; mode=block
```
