### ISSUE TITLE
win_dsc strange behaviour

### ISSUE THREAD

**Issue by redridinghood314** [ansible/ansible#73250]
##### SUMMARY

First, i don't know if it can be tagged as a real bug, i will explain why :
- we are working mainly on DSC and windows plateforms, and we are looking to move toward ansible with the help of win_dsc module. To check if there are no big limitations over native dsc, i have begun to try to implement an already integrated ansible function : build AD domain controller, with the help of ActiveDirectoryDsc (6.0.1) module. (that s why i don t know if we can call that a bug, because as i understand, it is better to use native ansible module when they exists, so perhaps my test is not representative and i should look over another deployment type (don't hesitate to tell me).

- Here the "bug", i use the DSC resource and give all mandatory parameters, everything is working, no error, but credentials are not working, after deployement, old password is kept as domain administrator (and asking me to change it if i try to login)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_dsc

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  3 2020, 18:11:24) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS 8 Stream

ActiveDirectoryDsc 6.0.1

##### STEPS TO REPRODUCE

```yaml
- name: deploy AD Domain
   ansible.windows.win_dsc:
       resource_name: ADDomain
       Credential_username: "{{ ads_domain_username }}"
       Credential_password: "{{ ads_domain_password }}"
       DomainName: "{{ ads_DomainName }}"
       SafeModeAdministratorPassword_username: "{{ ads_domain_username }}"
       SafeModeAdministratorPassword_password: "{{ ads_SafeModeAdministratorPassword }}"
    register: win_ad`
```

##### EXPECTED RESULTS

Domain deployed with new domain administrator password as specified in Credential parameter of DSC resource : 
````
ADDomain [String] #ResourceName
{
    Credential = [PSCredential]
    DomainName = [string]
    SafeModeAdministratorPassword = [PSCredential]
    [DatabasePath = [string]]
    [DependsOn = [string[]]]
    [DnsDelegationCredential = [PSCredential]]
    [DomainMode = [string]{ Win2008 | Win2008R2 | Win2012 | Win2012R2 | WinThreshold }]
    [DomainNetBiosName = [string]]
    [ForestMode = [string]{ Win2008 | Win2008R2 | Win2012 | Win2012R2 | WinThreshold }]
    [LogPath = [string]]
    [ParentDomainName = [string]]
    [PsDscRunAsCredential = [PSCredential]]
    [SysvolPath = [string]]
}
````

##### ACTUAL RESULTS

Domain is deployed but domain administrator credential is not set (so need  using old local administrator password and system is asking me to change it as it is expired) 

```paste below

```
