### ISSUE TITLE
Domain users manager in vCenter

### ISSUE THREAD

**Issue by Wobak** [ansible/ansible#73266]
##### SUMMARY
Have a module in community.vmware to interact with users on a vCenter (not local to ESXi)

##### ISSUE TYPE
Start a module that will interact with a vCenter instead of an ESXi server 

##### COMPONENT NAME
community.vmware.vcenter_domain_user_manager

##### ADDITIONAL INFORMATION
Whenever an ESXi is added to a vCenter, the users / groups are delegated to a SSO server in the PSC.
So the local_role_manager has no longer an effect if you want to add roles to the new domain

```yaml
- name: Add a user in the vCenter
    community.vmware.vcenter_domain_user_manager:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    domain: vsphere.local
    name: 'myUser1'
    state: present
    description: "This is my first user"
```
##### ANSIBLE VERSION
```shell
# ansible --version
ansible 2.9.16
  config file = /opt/raid/ansible/keyce/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
