### ISSUE TITLE
Add parameter to builtin module uri to use a different than system-wide CAs

### ISSUE THREAD

**Issue by redgryphon** [ansible/ansible#73262]
##### SUMMARY
Feature request is pretty simple and explicative by itself: adding a parameter to the builtin module `uri` to allow the user to validate the remote certificate against a custom CA instead of or along the system CAs.

Use case scenario:
I spun up a web server with some sort of REST API protected by a certificate signed by a custom CA, maybe internal of my organization. I then try to call the `uri` module to test/configure the application via the REST API. If the CA is not installed into the system CAs the play will fail. I do not want to install the CA on any machine other than the clients that will call the REST API so there is no other solution than to customize the ansible component.

##### ISSUE TYPE
- Feature Request

##### COMPONENT NAME
Component affected would be the [uri module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html).
The file regarding the component is `lib/ansible/modules/uri.py`.

##### ADDITIONAL INFORMATION
Following is an example of such parameter taken from the `uri` docs and updated with my proposal.

```yaml
- name: Queue build of a project in Jenkins
  uri:
    url: http://{{ jenkins.host }}/job/{{ jenkins.job }}/build?token={{ jenkins.token }}
    server_cert_ca: "/path/to/certificate/custom-ca.crt"
    user: "{{ jenkins.user }}"
    password: "{{ jenkins.password }}"
    method: GET
    force_basic_auth: yes
    status_code: 201
```
#### ANSIBLE VERSION

S: Don't be obtuse, just provide a version.

```
ansible 2.9.16
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/projects/ansibledev/ansible/lib/ansible
  executable location = ~/projects/ansibledev/ansible/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 11:36:19) [Clang 12.0.0 (clang-1200.0.32.2)]
```

Just because the bot requested it (even if in the template there is no such reference to the request) the ansible version I'm using is `ansible 2.9.16` but, obviously, there is no difference since every version of ansible does not have the feature I'm requesting. I suppose this is actually a bug with the bot which needs that information when a bug is opened.
