### ISSUE TITLE
the parameter of msg in ansible.builtin.debug should be array or str

### ISSUE THREAD

**Issue by chisaato** [ansible/ansible#73278]
Here is the type of parameter

https://github.com/ansible/ansible/blob/cec5267cee894baeb51c6d7721623bb7e7a4f2d6/lib/ansible/modules/debug.py#L22-L26

it should be `str` ot `array`, because we can pass an array for multiple line text like this.

https://github.com/ansible/ansible/blob/cec5267cee894baeb51c6d7721623bb7e7a4f2d6/lib/ansible/modules/debug.py#L73-L75

this bug also exist in the yaml-schema

![image](https://user-images.githubusercontent.com/17796830/104949535-14c3bb80-59fa-11eb-8862-53bcc5bf892d.png)

##### COMPONENT NAME
ansible.builtin.debug

**Comment by gzzchh** [comment]
the format of the doc also has a mistake.

```yaml
- name: Prints two lines of messages, but only if there is an environment value set
  ansible.builtin.debug:
    msg:
    # wrong indentation
    - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"
    - "These servers were built using the password of '{{ password_used }}'. Please retain this for later use."
```
should be 
```yaml
- name: Prints two lines of messages, but only if there is an environment value set
  ansible.builtin.debug:
    msg:
    # Correct
      - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"
      - "These servers were built using the password of '{{ password_used }}'. Please retain this for later use."
```
