### ISSUE TITLE
Yum module only reports upgraded x86_64 packages when i686 packages have also been upgraded

### ISSUE THREAD

**Issue by amg1127** [ansible/ansible#73284]
##### SUMMARY
I have created an Ansible playbook that invokes the `yum` module with the arguments `name="*" state=latest update_cache=yes update_only=yes`. The managed node is a 64-bit CentOS 7 system containing some i686 packages installed for compatibility with third-party 32-bit applications.

If 32-bit packages are available for upgrade, `yum` modules upgrades them alongside available 64-bit packages, however it only reports that 64-bit packages have been upgraded in the transaction. It should report upgraded 32-bit packages as well. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
yum module

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/amg1127/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
# (no output)
```

##### OS / ENVIRONMENT

Controller node: Arch Linux
Managed node: CentOS 7

##### STEPS TO REPRODUCE

The issue can be reproduced using the below Vagrantfile and Ansible playbook.

```ruby
# Vagrantfile
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "1809.1"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "1024"
    end
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "./ansible_playbook.yml"
    end
end
```

```yaml
# ansible_playbook.yml
---
- hosts: all
  gather_facts: no
  vars:
    packages:
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/glibc;2.17-260.el7.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/glibc-common;2.17-260.el7.x86_64.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/libgcc;4.8.5-36.el7.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/libstdc++;4.8.5-36.el7.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/ncurses-libs;5.9-14.20130511.el7_4.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/nspr;4.19.0-1.el7_5.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/nss-softokn;3.36.0-5.el7_5.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/nss-softokn-freebl;3.36.0-5.el7_5.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/nss-util;3.36.0-1.el7_5.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/readline;6.2-10.el7.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/sqlite;3.7.17-8.el7.i686.rpm'
      - 'https://vault.centos.org/7.6.1810/os/x86_64/Packages/zlib;1.2.7-18.el7.i686.rpm'
  tasks:
    - name: Clean yum cache
      shell: 'yum clean all; rm -Rfv /var/cache/yum'
      become: yes
    - name: Install some i686 packages alongside x86_64 ones
      command:
        argv: "{{ ['yum', '-y', 'localinstall', '--disablerepo=*'] + (packages | union(
                  packages | map('regex_replace', '\\.i686\\.rpm$', '.x86_64.rpm') | list) | map('replace', ';', '-') | list) }}"
      become: yes
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: updated_packages
      retries: 5
      delay: 1
      until: 'updated_packages is success'
      become: yes
    - name: Report the list of updated packages
      debug:
        msg:
          - 'The packages below were updated:'
          - "{{ updated_packages.changes.updated | default([]) | selectattr(0, 'in', (
                packages | map('urlsplit', 'path') | map('basename') |
                  map('regex_replace', '^([^;]+);.*$', '\\1') | list
                )) | list }}"
```
Place those files under an empty folder, install `Vagrant` and `VirtualBox` and launch the command line `vagrant up --provision`.

##### EXPECTED RESULTS

`yum` module should provide the below output:
```
TASK [Report the list of updated packages] *************************************
ok: [default] => {
    "msg": [
        "The packages below were updated:",
        [
            [
                "nspr",
                "4.25.0-2.el7_9.i686 from updates"
            ],
            [
                "nspr",
                "4.25.0-2.el7_9.x86_64 from updates"
            ],
            [
                "glibc",
                "2.17-317.el7.i686 from base"
            ],
            [
                "glibc",
                "2.17-317.el7.x86_64 from base"
            ],
            [
                "glibc-common",
                "2.17-317.el7.x86_64 from base"
            ],
            [
                "nss-softokn",
                "3.53.1-6.el7_9.i686 from updates"
            ],
            [
                "nss-softokn",
                "3.53.1-6.el7_9.x86_64 from updates"
            ],
            [
                "libstdc++",
                "4.8.5-44.el7.i686 from base"
            ],
            [
                "libstdc++",
                "4.8.5-44.el7.x86_64 from base"
            ],
            [
                "nss-util",
                "3.53.1-1.el7_9.i686 from updates"
            ],
            [
                "nss-util",
                "3.53.1-1.el7_9.x86_64 from updates"
            ],
            [
                "libgcc",
                "4.8.5-44.el7.i686 from base"
            ],
            [
                "libgcc",
                "4.8.5-44.el7.x86_64 from base"
            ],
            [
                "sqlite",
                "3.7.17-8.el7_7.1.i686 from base"
            ],
            [
                "sqlite",
                "3.7.17-8.el7_7.1.x86_64 from base"
            ],
            [
                "nss-softokn-freebl",
                "3.53.1-6.el7_9.i686 from updates"
            ],
            [
                "nss-softokn-freebl",
                "3.53.1-6.el7_9.x86_64 from updates"
            ],
            [
                "readline",
                "6.2-11.el7.i686 from base"
            ],
            [
                "readline",
                "6.2-11.el7.x86_64 from base"
            ]
        ]
    ]
}
```

##### ACTUAL RESULTS

`yum` module provides the below output:

```
TASK [Report the list of updated packages] *************************************
ok: [default] => {
    "msg": [
        "The packages below were updated:",
        [
            [
                "nspr",
                "4.25.0-2.el7_9.x86_64 from updates"
            ],
            [
                "glibc",
                "2.17-317.el7.x86_64 from base"
            ],
            [
                "glibc-common",
                "2.17-317.el7.x86_64 from base"
            ],
            [
                "nss-softokn",
                "3.53.1-6.el7_9.x86_64 from updates"
            ],
            [
                "libstdc++",
                "4.8.5-44.el7.x86_64 from base"
            ],
            [
                "nss-util",
                "3.53.1-1.el7_9.x86_64 from updates"
            ],
            [
                "libgcc",
                "4.8.5-44.el7.x86_64 from base"
            ],
            [
                "sqlite",
                "3.7.17-8.el7_7.1.x86_64 from base"
            ],
            [
                "nss-softokn-freebl",
                "3.53.1-6.el7_9.x86_64 from updates"
            ],
            [
                "readline",
                "6.2-11.el7.x86_64 from base"
            ]
        ]
    ]
}
```
