### ISSUE TITLE
sysctl module does not change setting

### ISSUE THREAD

**Issue by huguesalary** [ansible/ansible#7329]
##### Issue Type:

“Bug Report”
##### Ansible Version:

1.6
##### Environment:

Mac OS X Mavericks (running ansible)
Debian Wheezy (target system)
##### Summary:

The sysctl module doesn't change values correctly...
##### Steps To Reproduce:

```
- name: Tuning net.ipv4.tcp_rmem
  sysctl: name="net.ipv4.tcp_rmem" value="4096 65536 16777216" state=present reload=yes sysctl_file=/tmp/test_sysctl.conf

- name: Tuning net.ipv4.tcp_wmem
  sysctl: name="net.ipv4.tcp_wmem" value='4096 65536 16777216' state=present reload=yes sysctl_file=/tmp/test_sysctl.conf

- name: Tuning net.ipv4.tcp_tw_reuse
  sysctl: name="net.ipv4.tcp_tw_reuse" value=1 state=present reload=yes sysctl_file=/tmp/test_sysctl.conf

- name: Tuning net.ipv4.tcp_fin_timeout
  sysctl: name="net.ipv4.tcp_fin_timeout" value=15 state=present reload=yes sysctl_file=/tmp/test_sysctl.conf

```
##### Expected Results:

```
$cat /tmp/test_sysctl.conf
net.ipv4.tcp_rmem = "4096 65536 16777216"
net.ipv4.tcp_wmem = "4096 65536 16777216"
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
```
##### Actual Results:

```
$cat /tmp/test_sysctl.conf
net.ipv4.tcp_rmem = 1
net.ipv4.tcp_wmem = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 1
```

Thanks,
-Hugues

**Comment by jimi-c** [comment]
Hrm, this does not happen on linux, the results on my system using your example are:

<pre>
$ cat /tmp/test_sysctl.conf
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
</pre>

Since we're basically just writing the output to a file, I wouldn't expect there to be any large difference between OSX and any other system.

**Comment by huguesalary** [comment]
Sorry, I guess my bug report isn't precise enough:

I run ansible on my mac, but the target systems are Debian Wheezy. I'll edit the report.

**Comment by jimi-c** [comment]
Thanks for the update, still not able to reproduce this unfortunately. I ran it on my debian 7.1 system and got the following output:

<pre>
root@debian71:~# cat /tmp/test_sysctl.conf 
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
</pre>

**Comment by huguesalary** [comment]
Thanks jimi-c,

Can you run this playbook on your Mac OS X? The result for me is:

```
net.ipv4.tcp_rmem = 1
net.ipv4.tcp_wmem = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 1
```

```
---
- hosts: localhost
  tasks:
    - name: Tuning net.ipv4.tcp_rmem
      sysctl: name="net.ipv4.tcp_rmem" value="4096 65536 16777216" state=present sysctl_file=/tmp/test_sysctl.conf
      ignore_errors: true
      tags:
        - tuning

    - name: Tuning net.ipv4.tcp_wmem
      sysctl: name="net.ipv4.tcp_wmem" value='4096 65536 16777216' state=present sysctl_file=/tmp/test_sysctl.conf
      ignore_errors: true
      tags:
        - tuning

    - name: Tuning net.ipv4.tcp_tw_reuse
      sysctl: name="net.ipv4.tcp_tw_reuse" value=1 state=present sysctl_file=/tmp/test_sysctl.conf
      ignore_errors: true
      tags:
        - tuning

    - name: Tuning net.ipv4.tcp_fin_timeout
      sysctl: name="net.ipv4.tcp_fin_timeout" value=15 state=present sysctl_file=/tmp/test_sysctl.conf
      ignore_errors: true
      tags:
        - tuning
```

I had to add `ignore_errors` because Mac OS X's `sysctl` doesn't like the `-p` parameter.

Thanks!
