### ISSUE TITLE
delegate_to does not determine ansible_host if ansible_host is built with variables

### ISSUE THREAD

**Issue by poptar7** [ansible/ansible#73313]
##### SUMMARY

If ansible_host is set using variables and delegate_to is used, ansible will use the current host's variables not the host being delegated to.

Tested against 2.10.5 as well as 2.11.0.dev0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

delegate_to

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/whiteteam/ansible/ansible.cfg
  configured module search path = ['/home/whiteteam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/whiteteam/ansible/ansible.cfg) = 40
HOST_KEY_CHECKING(/home/whiteteam/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/whiteteam/ansible/ansible.cfg) = ['auto', 'yaml', 'ansible.builtin.constructed']
```

##### OS / ENVIRONMENT

Example ansible is ran on ubuntu 18.04 host.

This has also been ran against a windows 10 host which is delegating to a linux host.

##### STEPS TO REPRODUCE

playbook
```yaml
---
- hosts: localone
  gather_facts: no
  tasks:
    - name: Show localone ansible_host
      debug:
        msg: "{{ ansible_host  }}"
    - name: Save delegated ansible_host to var for localtwo
      set_fact: "ip={{ ansible_host }}"
      delegate_to: localtwo.domain
      delegate_facts: true
    - name: Show the saved ansible_host for localtwo
      debug:
        msg: "{{ hostvars['localtwo.domain']['ip'] }}"
```
inventory
```yaml
---
all:
  vars:
    ansible_host: "{{ subnet_ish }}{{ host_octets }}"
    subnet_ish: "PlaceHolder"
    host_octets: "PlaceHolder"
  children:
    localone:
      vars:
        host_octets: "1"
      hosts:
        localone.domain:
    localtwo:
      vars:
        host_octets: "2"
      hosts:
        localtwo.domain:

    lan:
      children:
        localone:
        localtwo:
      vars:
        subnet_ish: "127.0.0."
```

##### EXPECTED RESULTS

When ansible_host is using vars set in the inventory, delegate_to should use the delegated hosts vars to build the ansible_host ip.

The third output in this play should show the ip of the second host which is 127.0.0.2.

##### ACTUAL RESULTS

delegate_to uses the current host's vars to build the ansible_host ip.

This is shown below as the ip 127.0.0.1 instead of 127.0.0.2 in the final output.

```paste below
PLAY [localone] 
META: ran handlers

TASK [Show localone ansible_host] 
task path: /home/ubuntu/ansiblebadstuff/playbook.yml:5
ok: [localone.domain] => {
    "msg": "127.0.0.1"
}

TASK [Save delegated ansible_host to var for localtwo]
task path: /home/ubuntu/ansiblebadstuff/playbook.yml:8
ok: [localone.domain -> {{ subnet_ish }}{{ host_octets }}] => {
    "ansible_facts": {
        "ip": "127.0.0.1"
    },
    "changed": false
}

TASK [Show the saved ansible_host for localtwo] 
task path: /home/ubuntu/ansiblebadstuff/playbook.yml:12
ok: [localone.domain] => {
    "msg": "127.0.0.1"
}
META: ran handlers
META: ran handlers
```
