### ISSUE TITLE
On Ansible Version 2.9.16 replace module is not working as documented

### ISSUE THREAD

**Issue by unicode-it** [ansible/ansible#73316]
##### SUMMARY
Regex capture groups capture wrong strings.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
replace module

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = <repo-dir>/ansible.cfg
  configured module search path = ['<repo-dir>/kubespray/library']
  ansible python module location = <user-dir>/.virtualenvs/sysop-ansible/lib/python3.7/site-packages/ansible
  executable location = <user-dir>/.virtualenvs/sysop-ansible/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
DEFAULT_MODULE_PATH(<repo-dir>/ansible.cfg) = ['<repo-dir>/kubespray/library']
DEFAULT_ROLES_PATH(<repo-dir>/ansible.cfg) = ['<repo-dir>/kubespray/roles']
DEFAULT_STDOUT_CALLBACK(<repo-dir>/ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(<repo-dir>/ansible.cfg) = <user-dir>/.ansible/vault_pass
TRANSFORM_INVALID_GROUP_CHARS(<repo-dir>/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
File /somefile:
```
                        # Allow 30M uploaded presentation document.
                        client_max_body_size       30m;
                        client_body_buffer_size    128k;
```
Vars:
```yaml
bbb_presentation_max_size: 100m
```

Task:
```yaml
- name: Set max size of presentation uploads
  replace:
    path: /somefile
    regexp: '^(\s+# Allow 30M uploaded presentation document.\n\s+client_max_body_size\s*)\w+(;)$'
    replace: '\1{{ bbb_presentation_max_size }}\2'
```

##### EXPECTED RESULTS

String gets replaced with:

```
                        # Allow 30M uploaded presentation document.
                        client_max_body_size       100m;
```

##### ACTUAL RESULTS

This string is created:
```
Xm;
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/replace.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/replace.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is not a bug. What happens is that 
```yaml
replace: '\1{{ bbb_presentation_max_size }}\2'
```

is templated to
```yaml
replace: '\1100m\2'
```

which means that it is effectively using back reference of `\1100`. You need to somehow separate the back reference and the subsequent number, for example like so:

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Set max size of presentation uploads
      replace:
        path: 73316.txt
        regexp: '^(\s+# Allow 30M uploaded presentation document.\n\s+client_max_body_size\s*)\w+(;)$'
        replace: '\g<1>{{ bbb_presentation_max_size }}\2'
      vars:
        bbb_presentation_max_size: 100m
```

User questions are better suited for either the mailing list or the IRC channel:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
