### ISSUE TITLE
loop over dict fails when only one element detected

### ISSUE THREAD

**Issue by eranha** [ansible/ansible#73329]
##### SUMMARY
when dict contains only one element loop fails. Used the eample in the documentation:
`fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {'key': 'alice', 'value': {'name': 'Alice Appleworth', 'telephone': '123-456-7890'}}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}`

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.4
  config file = None
  configured module search path = ['/Users/ehadar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.4/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Dec 28 2020, 11:24:06) [Clang 12.0.0 (clang-1200.0.32.28)]
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

macOS catalina 10.5.7

##### STEPS TO REPRODUCE

Used the dict documentation example with a single item in the dict

```yaml
  vars:
    users:
      alice:
        name: Alice Appleworth
        telephone: 123-456-7890

  tasks:
    # with predefined vars
    - name: Print phone records
      debug:
        msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
      loop: "{{ lookup('dict', users) }}"
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: {'key': 'alice', 'value': {'name': 'Alice Appleworth', 'telephone': '123-456-7890'}}. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```
