### ISSUE TITLE
RFE: Ansible syntax check fails to identify requires module arguments

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#73338]
##### SUMMARY
While ansible syntax check is able to detect missing modules it is not able to detect missing required arguments, and it should.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
syntax-check

##### ADDITIONAL INFORMATION
Take a look at example below:

```yaml
- hosts: localhost
  tasks:
    - name: foo
      copy:  # this should raise syntax error due to missing required dest argument
        src: bar
```
`dest` is required based on https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html and this is part of the module signature.
