### ISSUE TITLE
Variables interpolated using Jinja2 expressions in playbooks sometimes lose type information

### ISSUE THREAD

**Issue by kepstin** [ansible/ansible#73357]
##### SUMMARY
Often in things like `vars:` when running a task, `set_fact:`, or directly on parameters to a module, I'd like to use Jinja2 template interpolation in the playbook to either extract a value from a complex data structure, or calculate a value. However, instead of returning the correct data type, the result is often - but not always - converted to a `str`. This can result in errors in modules that expected an int data type, but received a string. In some cases it has been worked around in the module itself, e.g. #26374

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Not sure, seems to be some sort of problem with the core handling of interpolation in yaml playbooks.

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /home/cwalton/Development/blindsidenetworks/ansible-playbooks/ansible.cfg
  configured module search path = ['/home/cwalton/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/host/bin/ansible
  python version = 3.8.7 (default, Jan  9 2021, 17:58:19) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/cwalton/Development/blindsidenetworks/ansible-playbooks/ansible.cfg) = True
DEFAULT_FORKS(/home/cwalton/Development/blindsidenetworks/ansible-playbooks/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/cwalton/Development/blindsidenetworks/ansible-playbooks/ansible.cfg) = False
INTERPRETER_PYTHON(/home/cwalton/Development/blindsidenetworks/ansible-playbooks/ansible.cfg) = auto
```

##### STEPS TO REPRODUCE

Here's an example playbook showing several types of interpolation, all of which should result in `int` values.

```yaml
- hosts:
    - "localhost"

  tasks:

    - set_fact:
        int_variable: 42

    - debug:
        msg:
          int_variable: "{{ int_variable | type_debug }}"

    - set_fact:
        interpolated_variable0: "{{ int_variable }}"
        interpolated_variable1: "{{ hostvars['localhost'].int_variable }}"
        interpolated_variable2: "{{ 42 }}"
        interpolated_variable3: "{{ int_variable | int }}"

    - debug:
        msg:
          interpolated_variable0: "{{ interpolated_variable0 | type_debug }}"
          interpolated_variable1: "{{ interpolated_variable1 | type_debug }}"
          interpolated_variable2: "{{ interpolated_variable2 | type_debug }}"
          interpolated_variable3: "{{ interpolated_variable3 | type_debug }}"
```

##### EXPECTED RESULTS

All of the interpolated values should have type `int`

##### ACTUAL RESULTS

Several of the interpolated values have type `str` instead of `int`

```paste below
TASK [set_fact] ****************************************************************
task path: /home/cwalton/Development/blindsidenetworks/ansible-playbooks/test-blah.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "int_variable": 42
    },
    "changed": false
}

TASK [debug] *******************************************************************
task path: /home/cwalton/Development/blindsidenetworks/ansible-playbooks/test-blah.yml:10
ok: [localhost] => {
    "msg": {
        "int_variable": "int"
    }
}

TASK [set_fact] ****************************************************************
task path: /home/cwalton/Development/blindsidenetworks/ansible-playbooks/test-blah.yml:14
ok: [localhost] => {
    "ansible_facts": {
        "interpolated_variable0": 42,
        "interpolated_variable1": "42",
        "interpolated_variable2": "42",
        "interpolated_variable3": "42"
    },
    "changed": false
}

TASK [debug] *******************************************************************
task path: /home/cwalton/Development/blindsidenetworks/ansible-playbooks/test-blah.yml:20
ok: [localhost] => {
    "msg": {
        "interpolated_variable0": "int",
        "interpolated_variable1": "str",
        "interpolated_variable2": "str",
        "interpolated_variable3": "str"
    }
}
```
