### ISSUE TITLE
Ansible YUM hangs when installing package

### ISSUE THREAD

**Issue by fwiethof** [ansible/ansible#73376]
##### SUMMARY
When installing GitLab or GitLab Runner with the Ansible YUM module, and GPG checking is enabled, the task hangs and is terminated after ~ 45 minutes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
YUM Module

##### ANSIBLE VERSION
2.9.13

##### CONFIGURATION
[ssh_connection]
pipelining=True
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=50 -o UserKnownHostsFile=/dev/null
[defaults]
host_key_checking=False
remote_user = mlpadmin

##### OS / ENVIRONMENT
RHEL 7.8 current on Azure

##### STEPS TO REPRODUCE
```yaml
- name: Add gitlab-runner Repository
  yum_repository:
    name: gitlab-runner
    description: Gitlab Runner
    baseurl: https://packages.gitlab.com/runner/gitlab-runner/el/7/$basearch
    enabled: yes
    gpgcheck: no
    repo_gpgcheck: no

- name: Install gitlab-runner
  yum:
    name: gitlab-runner
    state: present
```

When enabling gpgcheck/repo_gpgcheck, the install tasks runs forever.
We have also observed yum makecache being run, which is strange, since update_cache is default (no).

When disabling them, it works fine.

When installing manually, it also works fine with GPG check.

##### EXPECTED RESULTS
The task completes sucessfully in-time.

The same code worked on Ansible 2.7.

##### ACTUAL RESULTS
The task hangs for ~ 45 minutes.
After that, the yum makecache seems to be killed and the rpmdb is corrupt.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/yum.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by relrod** [comment]
Hello,

So there are a few different things here:

First, the `yum makecache` process is expected in this case:

https://github.com/ansible/ansible/blob/13d08d232c8b692ec79dba81c9eb83887ee554a2/lib/ansible/modules/yum.py#L707-L718

You're asking it to gpg-verify the repo metadata, so it needs a GPG key installed to verify it against. It uses `yum -y makecache` to try to fetch the public key.

If you look at their [official .repo file](https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.repo?os=redhatenterpriseserver&dist=7&source=script), it has URLs you can use for this in your `yum_repository` task. 

As far as the "`yum makecache` taking forever" problem, I'm not able to reproduce that (copying your reproducer verbatim except setting the gpg options to `yes`). It sounds like maybe there was a network issue between Azure and the yum mirrors it was hitting (for `makecache` it would hit all of the enabled ones), or something else going on. You could try the `yum -y makecache` interactively and see if it's equally slow, but this isn't likely an Ansible issue.

Hope some of this helps :-)

needs_info

**Comment by fwiethof** [comment]
@relrod thanks a lot for the quick and detailed response.

The behavior is consistent. It happens every time we spin up the servers and run the playbook.

It does not happen, when I have the playbook run up to the add repo / yum install tasks, and then do the add repo / install yum manually. Interesting enough, YUM does not seem to makecache in case I manually add the repo and install the package, as it completes quite quickly.

I need to says we're also working on Azure performance issues in parallel. Our machines should have 60 MB/s write throughput on the disks. However, we only get 7-10 MB/s throughput. The YUM cache is ~ 10 GB on the system, so writing the cache takes 20-30 minutes alone, as it seems (at least iotop reveals that yum makecache is writing all the time to the disk). This also happens when I run yum makecache manually. When I move the YUM cache to the scratch disk (which has way more throughput, but is ephemeral), this speeds things up dramatically.

I tried to add the GPG keys using the rpm_key module before I run yum_repository and yum. This does not change the behavior, however. I also tried creating the GPG keys in the targets filesystem and have the repo file point to that files. No change.

I really would like to find a way to re-enable GPG under that circumstances.

But in the end, your answer indicates that this behavior is by design. Is there any other way to avoid the makecache with the YUM module? Do you think switching over to the DNF module will help?

**Comment by relrod** [comment]
> I tried to add the GPG keys using the rpm_key module before I run yum_repository and yum. 

So, there are two distinct sets of GPG keys at play here (well, the same keys in this case, but stored in two separate places). The GPG key for **packages** gets stored in the RPM database. The GPG keys for **repo metadata** gets handled separately by Yum and stored in its own cache. The `rpm_key` handles the former -- package keys -- not metadata keys.

> Is there any other way to avoid the makecache with the YUM module?

Basically what's happening here is:
* Ansible executes logic to ask Yum what package provides the given input package name (in case it is a file or similar).
* Yum wants to verify the metadata for the repository when it tries to figure that out.
* It checks its cache and sees it doesn't have the key and reports an error.
* Ansible sees that error and says "Okay, run `yum makecache` to try to fix it."
* `yum makecache` goes and pulls metadata for all enabled repos that yum knows about (which is really slow in your case for some unrelated reason)
* When it gets to the gitlab repo, if you have `repo_gpgcheck` enabled in your yum config (but no `gpgkey` parameter set, like in your YAML example), `yum makecache` will fail and complain that it can't validate the metadata, because it doesn't have the key in its cache (you can observe this by manually running `yum makecache` yourself with `--disablerepo='*' --enablerepo=gitlab-runner`):
```
failure: repodata/repomd.xml from gitlab-runner: [Errno 256] No more mirrors to try.
https://packages.gitlab.com/runner/gitlab-runner/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo gitlab-runner
```

Similarly, if you run (only) your `yum_repository` task on a fresh RHEL 7 box, and then manually run `yum install -y gitlab-runner`, it will fail with the same error.

As for how to fix it, it's simple: Just include the correct GPG keys in your repo file:

```yaml
  - name: Add gitlab-runner Repository
    yum_repository:
      name: gitlab-runner
      description: Gitlab Runner
      baseurl: https://packages.gitlab.com/runner/gitlab-runner/el/7/$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-366915F31B487241.pub.gpg"
```

When you do that, `yum makecache` will still get run if you use the `yum` module right after, because this is how Ansible tells `yum` to bring in those GPG keys.

> Do you think switching over to the DNF module will help?

No for several reasons: 1) You're running this on RHEL 7 which doesn't have dnf; 2) Ansible will fall back to `yum` in that case anyway; 3) DNF will still need to know where to pull in the metadata keys from, so it will behave similarly.
