### ISSUE TITLE
fix creating IP specific vmware firewall rules when using networks/subnets

### ISSUE THREAD

**Issue by kmcm0** [ansible/ansible#73377]
##### SUMMARY
Specifying ip_network to add to a vmware firewall rule results in a python2 unicode error.
this was fixed for individual ip adresses but not ip networks. (https://github.com/ansible/ansible/pull/67394) 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_host_firewall_manager.py

##### ANSIBLE VERSION
```
ansible 2.9.17
...
python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
RHEL Server 7.8

##### STEPS TO REPRODUCE
Create a playbook that tries to configure a vmware service firewall rule with ip network information:

```yaml
- name: firewall_manage_syslog
  vmware_host_firewall_manager:
  hostname: "{{ vcenter_server }}"
  username: "{{ vcenter_user }}" 
  password: "{{ vcenter_pass }}"
  cluster_name: "{{ item }}"
  validate_certs: "{{ do_validate_certs }}"
  rules:
    - name: syslog
      enabled: True
      allowed_hosts:
        all_ip: False
        ip_network:
          - 192.168.0.0/24
  delegate_to: localhost
  loop: "{{ cluster_names }}"
  when: firewall_manage_syslog

```

##### EXPECTED RESULTS
successful configuration of the firewall rule.

##### ACTUAL RESULTS
this will result in a failure stating the ip network is invalid. upon inspection, it is generated by the ansible.module_utils.compat.ipaddress module.. from being passed a non-unicode string.
for ip_address params, this is successful. for ip_network, it is not. that is because the helper function to_text() from ansible.module_utils._text is not used for ip_network, but it is for ip_address in vmware_host_firewall_manager.py
