### ISSUE TITLE
Dependency missing for example of nmcli in Ubuntu 20.04

### ISSUE THREAD

**Issue by spotlesscoder** [ansible/ansible#73431]
##### SUMMARY
On this documentation page: 
https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html

There is an example which has a task: 

```
- hosts: openstack-stage
  remote_user: root
  tasks:

  - name: Install needed network manager libs
    ansible.builtin.package:
      name:
        - NetworkManager-libnm
        - nm-connection-editor
        - libsemanage-python
        - policycoreutils-python
      state: present
```

This does not work on Ubuntu Server 20.04

`FAILED! => {"changed": false, "msg": "No package matching 'NetworkManager-glib' is available"}`
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

nmcli
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
<EMPTY>
```

##### OS / ENVIRONMENT

Client: Ubuntu 20.04 WSL 2
Servers: Ubuntu Server 20.04.1
