### ISSUE TITLE
Loops and vars don't play nice when product filters are involved

### ISSUE THREAD

**Issue by frogstarr78** [ansible/ansible#73477]
##### SUMMARY

When using a "vanilla" loop on a task, vars have access to the loop values unless the loop includes (at least) a product filter. Then I get the error: 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
ansible 2.10.2
  config file = /home/noelsc/git/vivio-ansible/ansible.cfg
  configured module search path = ['/home/noelsc/git/vivio-ansible/lib']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_COW_SELECTION(/home/noelsc/git/vivio-ansible/ansible.cfg) = random
ANSIBLE_COW_WHITELIST(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake', 'elephant', 'eyes', '\\\nhellokitty', 'kitty', 'luke-koala', 'meow', 'milk', 'moofasa', 'moose', 'ren', 'sh>
CACHE_PLUGIN(/home/noelsc/git/vivio-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/noelsc/git/vivio-ansible/ansible.cfg) = ~/cache/
COLOR_VERBOSE(/home/noelsc/git/vivio-ansible/ansible.cfg) = bright blue
DEFAULT_ACTION_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['timer']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/filter_plugins']
DEFAULT_FORKS(/home/noelsc/git/vivio-ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/home/noelsc/git/vivio-ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/vivio/hosts.yml']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/vivio']
DEFAULT_LOCAL_TMP(/home/noelsc/git/vivio-ansible/ansible.cfg) = /tmp/t/ansible-local-19568020det7db7
DEFAULT_LOG_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = /home/noelsc/git/vivio-ansible/log/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/lookup_plugins']
DEFAULT_MANAGED_STR(/home/noelsc/git/vivio-ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/lib']
DEFAULT_POLL_INTERVAL(/home/noelsc/git/vivio-ansible/ansible.cfg) = 15
DEFAULT_PRIVATE_ROLE_VARS(/home/noelsc/git/vivio-ansible/ansible.cfg) = True
DEFAULT_SCP_IF_SSH(/home/noelsc/git/vivio-ansible/ansible.cfg) = True
DEFAULT_TIMEOUT(/home/noelsc/git/vivio-ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/home/noelsc/git/vivio-ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['/home/noelsc/git/vivio-ansible/vars_plugins']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/noelsc/.ansible/vault
INVENTORY_ENABLED(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['script', 'host_list', 'yaml', 'constructed', 'portal_inventory', 'passwordstate']
INVENTORY_IGNORE_EXTS(/home/noelsc/git/vivio-ansible/ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.ini', '.cfg', '.retry']
INVENTORY_UNPARSED_IS_FAILED(/home/noelsc/git/vivio-ansible/ansible.cfg) = True
PARAMIKO_HOST_KEY_AUTO_ADD(/home/noelsc/git/vivio-ansible/ansible.cfg) = True
SHOW_CUSTOM_STATS(/home/noelsc/git/vivio-ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Run this sample playbook.
There are three tasks below. The first two work. The third throws this error:

```yaml
- hosts: localhost
  vars:
    left:
    - name: one
      value: 1
    - name: two
      value: 2
    - name: three
      value: 3
    right:
    - name: letterA
      value: a
    - name: letterB
      value: b
  tasks:
    - debug:
        msg: "I work: {{ item }}"
      loop: "{{ left }}"
      vars:
        me_again:
          - "{{ item.name }}"

    - debug:
        msg: "I also work: {{ item }}"
      loop: "{{ left | product(me_again | flatten) | list }}"
      vars:
        me_again:
          - "{{ left | selectattr('value', 'gt', 1) | map(attribute='name') | map('capitalize') | list }}"
          - "{{ left | selectattr('value', 'gt', 1) | map(attribute='name') | map('upper') | list }}"

    - debug:
        msg: "I don't work: {{ item }}"
      loop: "{{ left | product(me_again) | list }}"
      vars:
        me_again:
          - "{{ item.name | capitalize }}"
          - "{{ item.name | upper }}"
```

##### EXPECTED RESULTS

Task 3 should behave similar to task 2. Regardless it shouldn't throw an error.
```yaml
TASK [debug] ****************************************************************************************************************************************************************************************************************************
task path: /home/noelsc/git/vivio-ansible/bugs/loop_vars.yml:24
ok: [localhost] => (item=[{'name': 'one', 'value': 1}, 'Two']) => {
    "msg": "I don't work: [{'name': 'one', 'value': 1}, 'Two']"
}
ok: [localhost] => (item=[{'name': 'one', 'value': 1}, 'Three']) => {
    "msg": "I don't work: [{'name': 'one', 'value': 1}, 'Three']"
}
ok: [localhost] => (item=[{'name': 'one', 'value': 1}, 'TWO']) => {
    "msg": "I don't work: [{'name': 'one', 'value': 1}, 'TWO']"
}
ok: [localhost] => (item=[{'name': 'one', 'value': 1}, 'THREE']) => {
    "msg": "I don't work: [{'name': 'one', 'value': 1}, 'THREE']"
}
ok: [localhost] => (item=[{'name': 'two', 'value': 2}, 'Two']) => {
    "msg": "I don't work: [{'name': 'two', 'value': 2}, 'Two']"
}
ok: [localhost] => (item=[{'name': 'two', 'value': 2}, 'Three']) => {
    "msg": "I don't work: [{'name': 'two', 'value': 2}, 'Three']"
}
ok: [localhost] => (item=[{'name': 'two', 'value': 2}, 'TWO']) => {
    "msg": "I don't work: [{'name': 'two', 'value': 2}, 'TWO']"
}
ok: [localhost] => (item=[{'name': 'two', 'value': 2}, 'THREE']) => {
    "msg": "I don't work: [{'name': 'two', 'value': 2}, 'THREE']"
}
ok: [localhost] => (item=[{'name': 'three', 'value': 3}, 'Two']) => {
    "msg": "I don't work: [{'name': 'three', 'value': 3}, 'Two']"
}
ok: [localhost] => (item=[{'name': 'three', 'value': 3}, 'Three']) => {
    "msg": "I don't work: [{'name': 'three', 'value': 3}, 'Three']"
}
ok: [localhost] => (item=[{'name': 'three', 'value': 3}, 'TWO']) => {
    "msg": "I don't work: [{'name': 'three', 'value': 3}, 'TWO']"
}
ok: [localhost] => (item=[{'name': 'three', 'value': 3}, 'THREE']) => {
    "msg": "I don't work: [{'name': 'three', 'value': 3}, 'THREE']"
}
```

##### ACTUAL RESULTS

```paste below
TASK [debug] ****************************************************************************************************************************************************************************************************************************
task path: /home/noelsc/git/vivio-ansible/bugs/loop_vars.yml:34
fatal: [localhost]: FAILED! => {
    "msg": "['{{ item.name | capitalize }}', '{{ item.name | upper }}']: 'item' is undefined"
}
```
