### ISSUE TITLE
ansible.builtin.command add dict arguments support

### ISSUE THREAD

**Issue by jasstionzyf** [ansible/ansible#73522]
##### SUMMARY

like i have a python file need to execute , i need pass multi key-value pairs to the python script to parse and execute
[from documents](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html), it only support list arguments not support dict arguments 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible.builtin.command

##### ADDITIONAL INFORMATION

      
     

```yaml

expected:
- name: Use 'argv' to send a command as a list - leave 'command' empty
  command: /usr/bin/make_database.sh
    args:
      - userName: username
      - daName: dbname


```
