### ISSUE TITLE
script module fails if shell on destination host is csh

### ISSUE THREAD

**Issue by ryanschulze** [ansible/ansible#7352]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6
##### Environment:

Destinations are FreeBSD hosts with csh as a shell.
##### Summary:

The script module tries to set LC_CTYPE and LANG before executing the script. This works with sh and bash, but fails with csh
##### Steps To Reproduce:

Simple playbook using _script_ 

```
- name: csh shell test
  hosts: all
  remote_user: root
  gather_facts: False
  tasks:
    - script: foo.sh
```
##### Expected Results:

Command to behave like the raw module and not try to set LC_CTYPE/LANG when using script, or add some kind of option to turn this feature on/off on a per host basis if it is required to normalize output for parsing.
##### Actual Results:

```
failed: [10.2.3.4] => {"changed": true, "rc": 1}
stdout: LC_CTYPE=C: Command not found.
```
