### ISSUE TITLE
iosxr_facts does not display the correct hostname for IOS-XR 64-bit

### ISSUE THREAD

**Issue by yowzer81** [ansible/ansible#73534]
##### SUMMARY

iosxr_facts module doesn't capture the correct router hostname but instead shows as System. This only happens to IOS-XR running with 64-bit architecture

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr_facts

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = None
  configured module search path = ['/home/simon/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Tested with Cisco NCS-5500 (7.2.1) and Cisco ASR9000 (7.1.2)

##### STEPS TO REPRODUCE

Sample router configuration.

RP/0/RSP0/CPU0:TEST-ROUTER#show run hostname
Tue Feb  9 15:33:25.729 AEST
hostname TEST-ROUTER

```yaml
- name: IOS XR Pre Checks Playbook
  hosts: "{{ hosts_to_run }}"
  gather_facts: no
  serial: 1
  connection: network_cli

  tasks:
  - name: Get timestamp from the system
    shell: "date +%y%m%d_%H%M%S"
    register: tstamp

  - name: Gather router information
    iosxr_facts:
      gather_subset: 
        - "!interfaces"
```

##### EXPECTED RESULTS

Should expect `"ansible_net_hostname": "TEST-ROUTER"`

##### ACTUAL RESULTS
`"ansible_net_hostname": "System"`

```paste below

```
