### ISSUE TITLE
Assemble: Allow src to be a list

### ISSUE THREAD

**Issue by LukeLR** [ansible/ansible#73576]
##### SUMMARY

The assemble action is very useful to build a configuration file from fragments. However, the fragments are required to reside all in the same folder. Only a single directory can be specified with the `src` parameter. It is therefore for example not possible to concatenate two files that reside in different folders using the assemble module. In this case, the files have to be copied to a shared directory first, and cleaned up afterwards, which is unnecessary extra work.

Instead, if the assemble module would accept a list for the `src` parameter, it would not only be possible to specify a single directory that is supposed to be assembled, but also two individual files, or maybe two directories. This is just a generalization that fits the syntax of ansible nicely, and wouldn't break backwards compatibility.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

assemble

##### ADDITIONAL INFORMATION

For example, one could assemble a certificate with it's chain without having to put both into a temporary folder:

```yaml
- name: "Assemble full certificate chain"
  assemble:
    src:
      - certificate.pem
      - chain.txt
    dest: full-chain.crt
    owner: root
    group: root
    mode: '0640'
```
