### ISSUE TITLE
Ansible getting stuck randomly in case of CentOS8

### ISSUE THREAD

**Issue by tulasinadhvaka** [ansible/ansible#73580]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```paste below
2.9.16
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
```

##### OS / ENVIRONMENT

NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

##### STEPS TO REPRODUCE

```yaml
  - name: Add Group
    group: name={{item}}
    with_items: "{{user}}"

  - name: Create User
    user: name="{{item}}" home="/home/{{item}}" shell="/bin/bash" group="{{item}}"
    with_items: "{{user}}"

  - name: Create the SSH Directory
    file: name="/home/{{item}}/.ssh" state=directory group={{item}} owner={{item}}
    with_items: "{{user}}"

  - name: Create authorized Keys file
    file: name=/home/{{item}}/.ssh/authorized_keys mode=0600 state=touch owner={{item}} group={{item}}
    with_items: "{{user}}"
```

##### EXPECTED RESULTS

```paste below

User creation

```

##### ACTUAL RESULTS

```paste below
Getting hanged at random places
```
