### ISSUE TITLE
force_handlers does not work with run_once

### ISSUE THREAD

**Issue by phemmer** [ansible/ansible#73613]
##### SUMMARY
When a task using `run_once` notifies a handler, and a later task fails, the handler does not trigger, even though `force_handlers` is enabled.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

handlers

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = None
  configured module search path = ['/home/phemmer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/phemmer/.local/lib/python3.9/site-packages/ansible
  executable location = /home/phemmer/.local/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Linux - Fedora 33

##### STEPS TO REPRODUCE

```
ansible-playbook test.yml
```
```yaml
- hosts: localhost
  become: false

  tasks:
    - command:
        cmd: 'true'
      notify: myhandler
      run_once: true

    - assert:
        that: 1 == 2

  handlers:
    - name: myhandler
      command:
        cmd: 'true'

  force_handlers: true
```

##### EXPECTED RESULTS

```
TASK [command] ***********************************************************************************************************************
changed: [localhost]

TASK [assert] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "1 == 2",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

RUNNING HANDLER [myhandler] **********************************************************************************************************
changed: [localhost]
```

##### ACTUAL RESULTS

```paste below
TASK [command] ***********************************************************************************************************************
changed: [localhost]

TASK [assert] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "1 == 2",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

NO MORE HOSTS LEFT *******************************************************************************************************************
```
