### ISSUE TITLE
Register subset of the result from a task

### ISSUE THREAD

**Issue by milliams** [ansible/ansible#73622]
##### SUMMARY
Add the ability to specify a custom subset of data to be registered from the result.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
core

##### ADDITIONAL INFORMATION

I find it is quite common to run a task to collect some information, but I really only want some small portion of the result that is returned. I think it would be good if it was possible to select a subset of a result when registering a variable from a task.

So, for example if I want to check whether a file exists, at the moment I need to do:

```yaml
- name: stat file
  ansible.builtin.stat:
    path: /tmp/foo
  register: my_file_stat

- name: set fact for existence
  ansible.builtin.set_fact:
    my_file_exists: "{{ my_file_stat.stat.exists }}"
```

This has one task to stat the file, and another to set another fact with the information that I need.

If it were possible to combine these, referring to the result of the task as `_` then I could simplify and be more explicit with:

```yaml
- name: does file exist
  ansible.builtin.stat:
    path: /tmp/foo
  register:
    my_file_exists: _.stat.exists
```
or, if `_` is too magic-looking, it could use the variable name `result`, or perhaps something like `__result__`.

Another example would be to be able to use filters directly on the result:

```yaml
- name: load a remote config file
  ansible.builtin.slurp:
    src: /etc/foo.yaml
  register:
    my_config: _['content'] | b64decode | from_yaml
```

It would also make it possible to register multiple variables from one task:

```yaml
- name: create an SSH key for user jsmith
  user:
    name: jsmith
    generate_ssh_key: yes
  register:
    jsmith_key_file: _.ssh_key_file
    jsmith_public_key: _.ssh_public_key
```
