### ISSUE TITLE
uri module encodes uploaded file in base64 if using body_format: form-multipart

### ISSUE THREAD

**Issue by mingalevas** [ansible/ansible#73621]
##### SUMMARY

I'm trying to run this command with URI module:

```
curl --request 'POST' "https://{{ public_address }}{{ url_path_api }}/packages"
-H 'Content-Type: multipart/form-data'
-H 'Connection: keep-alive'
--form 'version={{ item.version }}'
--form "package=@./packages/{{ item.name }}"
--insecure
```

My playbook task
```
- name: Upload package
  ansible.builtin.uri:
    url: https://{{ public_address }}{{ url_path_api }}/packages
    remote_src: yes
    return_content: true
    force: yes
    validate_certs: no
    method: POST
    headers:
      Connection: keep-alive
    body_format: form-multipart
    body:
      version: "{{ item.version }}"
      package:
        filename: "./packages/{{ item.name }}"
  with_items: 
    - { name: test-file, version: '0.0.1' }
```

I need to upload a binary file to the service.
I am getting the content of my file encoded in base64. 
This is not the behavior that I expected

Found the reason:
[Payload content from a file will be base64 encoded and will include
the appropriate ``Content-Transfer-Encoding`` and ``Content-Type``
headers](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L1552)

How can I load a binary file into my service using the uri module and immediately work with it without having to decode it?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.builtin.uri
uri

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/user/path/inoneconfig/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python2.7/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]

```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(...inoneconfig/ansible.cfg) = [u'profile_tasks']
HOST_KEY_CHECKING(...inoneconfig/ansible.cfg) = False
INVENTORY_ENABLED(...inoneconfig/ansible.cfg) = [u'script', u'yaml']

```

##### OS / ENVIRONMENT

Ubuntu 18.04.5 LTS

##### STEPS TO REPRODUCE

You need to send the file to the service that saves the file to the file system

```yaml
- name: Upload package
  ansible.builtin.uri:
    url: https://{{ public_address }}{{ url_path_api }}/packages
    remote_src: yes
    return_content: true
    force: yes
    validate_certs: no
    method: POST
    headers:
      Connection: keep-alive
    body_format: form-multipart
    body:
      version: "{{ item.version }}"
      package:
        filename: "./packages/{{ item.name }}"
  with_items: 
    - { name: test-file, version: '0.0.1' }
```

##### EXPECTED RESULTS

```
$ cat test-txt 
12345678
```

##### ACTUAL RESULTS

for simplicity of demonstration, I passed a text file

```paste below
$ cat test-txt      
MTIzNDU2NzgK

$ cat test-txt | base64 --decode
12345678

```
