### ISSUE TITLE
PR to resolve the issue with ec2_vpc module not allowing to use instance id in route_tables

### ISSUE THREAD

**Issue by romanrev** [ansible/ansible#7368]
##### Issue Type: Bugfix Pull Request

See [pull request to allow the use of an instance id in the route creation in ec2_vpc (for NAT private networks)](https://github.com/romanrev/ansible/pull/1) for a possible solution
##### Environment:

Running on OS X 10.9.2 managing AWS VPC
##### Summary:

When I am trying to add a route table to a VPC that uses a NAT instance id as a gateway, I get the error like follows:

```
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: Unable to create and associate route table {u'routes': [{u'dest': u'0.0.0.0/0', u'gw': u'i-09d47501'}], u'subnets': [u'10.1.10.0/24', u'10.1.12.0/24', u'10.1.20.0/24']}, error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error?<Code>InvalidGatewayID.NotFound</Code <Message>The gateway ID 'i-09d47501' does not exist</Message></Error></Errors><RequestID>fa95104e-37ab-44ee-b8fd-2c5033179585</RequestID></Response>
```
##### Steps To Reproduce:
1. create a VPC using a `ec2_vpc` Ansible module
2. launch a NAT instance into a subnet with the internet gateway in it
3. obtain NAT instance id 
4. re-run `ec2_vpc` Ansible module with a record in the `routes_table` assigning the NAT instance ID as a gateway in the route to '0.0.0.0/0' network destination. 

I.e. example

```
route_tables:
  - subnets:
      - '10.1.0.0/24'
      - '10.1.1.0/24'
    routes:
      - dest: 0.0.0.0/0
        gw: igw
  - subnets:
     - '10.1.10.0/24'
     - '10.1.12.0/24'
     - '10.1.20.0/24'
    routes:
      - dest: 0.0.0.0/0
        gw: 'i-09d47501'
```
##### Expected Results:

The VPC should be updated with the new route table defined that directs all internet traffic from the designated private subnets to the NAT instance.
##### Actual Results:

Getting the following error:

```
failed: [127.0.0.1] => {"failed": true, "item": ""}
msg: Unable to create and associate route table {u'routes': [{u'dest': u'0.0.0.0/0', u'gw': u'i-09d47501'}], u'subnets': [u'10.1.10.0/24', u'10.1.12.0/24', u'10.1.20.0/24']}, error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error?<Code>InvalidGatewayID.NotFound</Code <Message>The gateway ID 'i-09d47501' does not exist</Message></Error></Errors><RequestID>fa95104e-37ab-44ee-b8fd-2c5033179585</RequestID></Response>
```
##### Ways to fix:

See [pull request to allow the use of an instance id in the route creation in ec2_vpc (for NAT private networks)](https://github.com/romanrev/ansible/pull/1) for a possible solution

**Comment by mpeters** [comment]
I'm very interested in seeing this fixed. As it stands now, unless I'm missing something, you can't actually create a VPC with a public and a private subnet with a NAT instance to allow the private subnet internet access. Seems like a very common pattern.

**Comment by jimi-c** [comment]
I've gone ahead and cherry-picked the fix from @sayap above, so this issue should be resolved. Please let us know if you continue seeing any problems related to this issue going forward. Thanks!

**Comment by retrogradeorbit** [comment]
For me this doesn't work. Trying to assign a new route to an existing vpc gives:

```
msg: Unable to create and associate route table {u'routes': [{u'dest': u'10.100.255.0/24', u'gw': u'i-21811f09'}, {u'dest': u'0.0.0.0/0', u'gw': u'igw'}], u'subnets': [u'10.8.1.0/24']}, error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>route table rtb-0929c76c and interface eni-8074c8e5 belong to different networks</Message></Error></Errors><RequestID>024a5a32-c683-4fb4-b01d-5b5f733e998e</RequestID></Response>
```

Each time its run a new route table and a new VPC appears in the AWS console, and this continues until the error "msg: VpcLimitExceeded: The maximum number of VPCs has been reached." occurs.

Trying with latest ansible development tree, I get another error:

```
failed: [localhost -> 127.0.0.1] => (item=i-39ac3211) => {"failed": true, "item": "i-39ac3211"}
msg: missing required arguments: resource_tags
```

But I do indeed have resource_tags present on my subnets in the yaml. hmmm.

**Comment by psa** [comment]
@retrogradeorbit Looks like you're missing the resource_tags from the main VPC definition.

```
- name: "VPC name"
  ec2_vpc:
    state: "present"
    region: "us-east-1"
    cidr_block: "{{ subnets.us_east_1.cidr_block }}"
    internet_gateway: True
    resource_tags:
      Name: "XXX You are missing this"
    subnets:
      - cidr: "1.2.3.4/16"
        az: "us-east-1e"
    route_tables:
...
```
