### ISSUE TITLE
Feature Request: community.docker.docker_container --storage-opt

### ISSUE THREAD

**Issue by mujocloud** [ansible/ansible#73692]
##### SUMMARY

Hi Team,

I would like to request a new feature addition to the docker_container module -
When we run a container there is an option to specify the size of the container's root volume docker run -itd --storage-opt
Please implement that in the docker_container module as well
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.docker.docker_container module
##### ADDITIONAL INFORMATION

If the team could add this feature it would allow all docker containers running on XFS to have a pre-set amount of storage and not use up the entire system's storage
https://fabianlee.org/2020/01/15/docker-use-overlay2-with-an-xfs-backing-filesystem-to-limit-rootfs-size/

```yaml
   tasks:
      - name: run container with rootfs size limit
        docker_container:
            name: "{{ container_name }}"
            image: "{{ image_name }}"
            detach: yes
            tty: yes
            state: started
           storage-opt: 
              - size: <size in GB>
           ports:
               - "{{ port }}"
```
