### ISSUE TITLE
log_path doesn't always work in win_package - Ansible 2.9.7

### ISSUE THREAD

**Issue by WloHu** [ansible/ansible#73697]
##### SUMMARY

I have a playbook where I install an application through MSI file on Windows 10. When I use `arguments: '/log {{ deploy_path }}\{{ msi_filename }}.log'` the log file is created but when I use `log_path: '{{ deploy_path }}\{{ msi_filename }}.log' it doesn't work.
Additionally I've noticed that when the command in run in Task Manager the path for default `/L*V` option is a temporary log file path and one specified with `log_path:` isn't there.

I've also tried to run `log_path:` w/o quotes and with double quotes but it thrown a syntax error (because of `\{{`.

When I read diff which included this option it looks like my case wasn't covered by tests and I suspect this issue may be due to `-type "path"` used there: https://github.com/ansible/ansible/blob/9ff53eca97082059a3e42fa69b00071ccd8ee759/lib/ansible/modules/windows/win_package.ps1#L28

When 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: win_package

##### ANSIBLE VERSION

```paste below
2.9.7
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/path/ansible.cfg) = True
DEFAULT_EXECUTABLE(/path/ansible.cfg) = /bin/bash
DEFAULT_INTERNAL_POLL_INTERVAL(/path/ansible.cfg) = 0.05
DEFAULT_SCP_IF_SSH(/path/ansible.cfg) = True
DEFAULT_TIMEOUT(/path/ansible.cfg) = 60
HOST_KEY_CHECKING(/path/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MS Windows 10.0.14393 Build 14393
msiexec "Windows Installer V 5.0.14393.2430"

##### STEPS TO REPRODUCE

1. Run `ansible-playbook` with playbook content specified below.

```yaml
- vars:
    deploy_path: c:\opt
    install_path: '{{ deploy_path }}\xyz'
    msi_filename: xyz.msi

    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Install
      win_package:
        path: '{{ deploy_path }}\{{ msi_filename }}'
        arguments: 'APPLICATIONFOLDER="{{ install_path }}"'
        creates_path: '{{ install_path }}/somefile.exe'
        state: present
        log_path: '{{ deploy_path }}\{{ msi_filename }}.log'
```

##### EXPECTED RESULTS

Log file is created in path specified by `log_path`.

##### ACTUAL RESULTS

Log file is **not** created in path specified by `log_path`.
(notice) Specified path is missing in command run in Task Manager.
