### ISSUE TITLE
azure_rm_loadbalancer with check mode will still change values

### ISSUE THREAD

**Issue by Jvekka** [ansible/ansible#73711]
##### SUMMARY
Running Ansible playbook with check mode will still overwrite load balancer values.
```ansible-playbook azure_provision.yml --check```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_loadbalancer

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
```

##### CONFIGURATION

```paste below
No output
```

##### OS / ENVIRONMENT

Ansible running in WSL Ubuntu 18.04 LTS

##### STEPS TO REPRODUCE

Run Ansible playbook ```ansible-playbook playbook_name.yml --check``` which includes changes to load balancer.

```yaml
- name: Load balancer | create dev lb probe and rule
  azure_rm_loadbalancer:
    resource_group: "{{ load_balancer_rg }}"
    name: "{{ load_balancer_dev }}"
    backend_address_pools:
      - name: "{{ lb_dev_backend_address_pool }}"
    probes:
      - name: "{{ internal_name }}D-HealthProbe"
        port: "{{ bp_port_dev }}"
        protocol: Tcp
        interval: 5
    load_balancing_rules:
      - name: "{{ internal_name }}D-LBRULE"
        frontend_ip_configuration: LoadBalancerFrontEnd
        backend_address_pool: "{{ lb_dev_backend_address_pool }}"
        frontend_port: "{{ port_dev }}"
        backend_port: "{{ port_dev }}"
        probe: "{{ internal_name }}D-HealthProbe"
        load_distribution: SourceIPProtocol
```

##### EXPECTED RESULTS

Ansible would show what would change instead of changing the load balancer

##### ACTUAL RESULTS

Ansible will change the load balancer configuration.

```paste below
changed: [localhost] => {"changed":true,"state":{"backend_address_pools":[{"etag":"W/\"xxx000xx-x0x0-x0x0-x0x0-x0x0x0x0x0\"","id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/backendAddressPools/WEAZBSD_BackendPool02","load_balancing_rules":[{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/loadBalancingRules/WEAZ2570D-LBRULE"}],"name":"WEAZBSD_BackendPool02","provisioning_state":"Succeeded"}],"etag":"W/\"xxx000xx-x0x0-x0x0-x0x0-x0x0x0x0x0\"","frontend_ip_configurations":[{"etag":"W/\"xxx000xx-x0x0-x0x0-x0x0-x0x0x0x0x0\"","id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/frontendIPConfigurations/LoadBalancerFrontEnd","load_balancing_rules":[{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/loadBalancingRules/WEAZ2570D-LBRULE"}],"name":"LoadBalancerFrontEnd","private_ip_address":"10.1.0.4","private_ip_allocation_method":"Dynamic","provisioning_state":"Succeeded","subnet":{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/virtualNetworks/Application_Backend_VNet/subnets/default"}}],"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001","inbound_nat_pools":[],"inbound_nat_rules":[],"load_balancing_rules":[{"backend_address_pool":{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/backendAddressPools/WEAZBSD_BackendPool02"},"backend_port":9570,"disable_outbound_snat":false,"enable_floating_ip":false,"enable_tcp_reset":false,"etag":"W/\"xxx000xx-x0x0-x0x0-x0x0-x0x0x0x0x0\"","frontend_ip_configuration":{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/frontendIPConfigurations/LoadBalancerFrontEnd"},"frontend_port":9570,"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/loadBalancingRules/WEAZ2570D-LBRULE","idle_timeout_in_minutes":4,"load_distribution":"SourceIPProtocol","name":"WEAZ2570D-LBRULE","probe":{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/probes/WEAZ2570D-HealthProbe"},"protocol":"Tcp","provisioning_state":"Succeeded"}],"location":"westeurope","name":"WEAZDLB001","outbound_rules":[],"probes":[{"etag":"W/\"xxx000xx-x0x0-x0x0-x0x0-x0x0x0x0x0\"","id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/probes/WEAZ2570D-HealthProbe","interval_in_seconds":5,"load_balancing_rules":[{"id":"/subscriptions/xxxx1111-xxxx22222-xxx333-xx44-xxxxxx555555/resourceGroups/Application_BackEnd/providers/Microsoft.Network/loadBalancers/WEAZDLB001/loadBalancingRules/WEAZ2570D-LBRULE"}],"name":"WEAZ2570D-HealthProbe","number_of_probes":3,"port":9570,"protocol":"Tcp","provisioning_state":"Succeeded"}],"provisioning_state":"Succeeded","resource_guid":"2d7f84e7-f950-4f01-8a5d-d7fec2497406","sku":{"name":"Standard"},"tags":{},"type":"Microsoft.Network/loadBalancers"}}
```
