### ISSUE TITLE
win_xml module warnings about xml nodes and elements

### ISSUE THREAD

**Issue by akhmolina** [ansible/ansible#73725]
##### SUMMARY

Win_xml module outputs warnings with information about xml notes end elements in document.
Looks like someone use Add-Warning for module debug.

Azure DevOps Task for ansible-playbook marks any task with warnings as failed, so it`s very upsetting thing.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_xml

##### ANSIBLE VERSION

```
ansible 2.9.9
  config file = None
  configured module search path = ['/home/ivmalin1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 27 2019, 14:21:59) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

##### CONFIGURATION

```
default, only in config file
```

##### OS / ENVIRONMENT

``` 
Windows Server 2012R2, Windows Server 2016
``` 

##### STEPS TO REPRODUCE

use win_xml to modify any correct xml file

```
- name: Enable service in keepalive config
  win_xml:
    path: "C:\\Test\\Ports.xml"
    xpath: '/Configuration/Ports/Port[@number="{{ item }}"]'
    attribute: normalState
    fragment: "true"
    type: attribute
  loop: "{{ endpoints }}"
  when: endpoints is defined
```

##### EXPECTED RESULTS
No warnings in ansible-playbook output.

##### ACTUAL RESULTS

Output with warnings like:
```
[WARNING]: node:  element: ...
```
and
```
[WARNING]: element is ...
```
