### ISSUE TITLE
Feature request: better host UNREACHABLE condition error handling in tasks

### ISSUE THREAD

**Issue by a-stoyanov** [ansible/ansible#73738]
##### SUMMARY
Hello Ansible Team,

First of all I want to say you are doing a great job with this project!

I'd like to request better host UNREACHABLE condition error handling in tasks to be added in Ansible core.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/playbook/task.py

##### ADDITIONAL INFORMATION
While Ansible already has the built in retry mechanism for ssh connections via

`[ssh_connection]
retries=
`

There is no equivalent built in method for winrm based connections due to a great many number of reasons I'd suspect.
At present, the only proper way to retry a winrm UNREACHABLE host it seems is if you loop over the task with a combination of ignore_unreachable: True and include_tasks: task.yml loop as per https://www.ansible.com/blog/tolerable-ansible
This is all fine until you have a very large number of tasks that need to be retried to account for intermittent network problems and realise you need to separate each task in it own yml file. Not very elegant.

What I'd very much love to see is conditional logic included at the task level sililar to retries/until to handle this.

The idea is to have a retry on unreachable option available, which is connection plugin agnostic. This can also be added as a global switch for all tasks in the main ansible.cfg

An example would perhaps look like this:
```yaml
- name: "Run a powershell command, retry winrm connection in case host is unreachable"
  win_shell: whoami
  register: ps_result
  retry_unreachable: 5  #number of times to retry the underlying connection if unreachable
  retry_delay: 5  #seconds to wait before next connection retry
  vars:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_transport: ntlm
```

Thank you!
