### ISSUE TITLE
docker_image: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by asarubbo** [ansible/ansible#73733]
##### SUMMARY

After the update from 2.10.4 to 2.10.5 we got 'NoneType' object is not iterable from docker_image module with an historical playbook that didn't got changes since years.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_image

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/ago/.ansible.cfg
  configured module search path = ['/home/ago/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.8/ansible
  python version = 3.8.7 (default, Feb 22 2021, 20:07:18) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/ago/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ago/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=20m -o PreferredAuthentications=publickey
DEFAULT_FORKS(/home/ago/.ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/ago/.ansible.cfg) = ['/home/ago/git/ansible/common/hosts']
DEFAULT_REMOTE_USER(/home/ago/.ansible.cfg) = root
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = actionable
DEPRECATION_WARNINGS(/home/ago/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/ago/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/ago/.ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT

Gentoo x86_64

##### STEPS TO REPRODUCE

```yaml
    - name: Docker load image
      docker_image:
        name: "{{ docker_registry }}:5000/qm{{ docker_build_version }}"
        tag: "{{ docker_build_tag }}"
        source: load
        push: yes
        load_path: "{{ install_directory }}/qm{{ docker_build_version }}_{{ docker_build_tag }}.tar.xz"
```

##### EXPECTED RESULTS

Do not get errors

##### ACTUAL RESULTS

```
    "msg": "Error loading image dr.queuemetrics-live.com:5000/qm20.11.18 - 'NoneType' object is not iterable",
    "stdout": "",
    "stdout_lines": []
```

In any case, the strangeness is that the image is load as per what "docker images"  reports.
