### ISSUE TITLE
Regular expressions: negative lookahead in lineinfile does not seem to work

### ISSUE THREAD

**Issue by abellmann** [ansible/ansible#73734]
##### SUMMARY

When using the lineinfile module with a negative lookahead , the negative lookahead is ignored and the line is changed with every run of ansible

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

lineinfile
##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/abellmann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ansible run from wsl2 on centos targets

##### STEPS TO REPRODUCE

running the following playbook twice:

```yaml
    - name: change cgroup driver to systemd
      lineinfile:
        path: /usr/lib/systemd/system/docker.service
        regexp: >
          (^ExecStart.+)(?!systemd)
        line: '\1 --exec-opt native.cgroupdriver=systemd'
        backrefs: yes
      register: cgroup_change

```

##### EXPECTED RESULTS

- line is changed only on the first run

##### ACTUAL RESULTS

- line is changed with every run and the exec-opt is added every time

```paste below
    Using /etc/ansible/ansible.cfg as config file

    PLAY [all] *********************************************************************

    TASK [Gathering Facts] *********************************************************
    ok: [kube2]
    ok: [kube_main]
    ok: [kube1]

    TASK [kubernetes-basics : change cgroup driver to systemd] *********************
    changed: [kube2] => {"backup": "", "changed": true, "msg": "line replaced"}
    changed: [kube1] => {"backup": "", "changed": true, "msg": "line replaced"}
    changed: [kube_main] => {"backup": "", "changed": true, "msg": "line replaced"}

    PLAY RECAP *********************************************************************
    kube1                      : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
    kube2                      : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
    kube_main                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
