### ISSUE TITLE
Add ansible-galaxy collection refresh-token

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible#73749]
##### SUMMARY

Offline tokens used to upload collection to automation hub, expire after 30 days of inactivity.
```
An offline token never expires as long as it is used at least once every
30 days and is used to create access tokens. It works as a password and
allows you to continue being able to authenticate your account without
having to create new refresh tokens.
```

The only way to stop this, is to upload a new collection (which may not be possible) or write a curl script to do it.  I am asking, we add this logic directly into ansible-galaxy CLI, to make it easier on our users.

https://access.redhat.com/articles/3626371
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

ansible-galaxy

##### ADDITIONAL INFORMATION

```yaml
---
- hosts: localhost
  tasks:
    - name: Refresh offline token
      no_log: true
      shell: "curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id=cloud-services -d refresh_token=\"{{ ansible_galaxy_info.token }}\" --fail --silent --show-error --output /dev/null"
```
