### ISSUE TITLE
ansible.builtin.file doesn't apply owner/group when creates link

### ISSUE THREAD

**Issue by sergey-shambir** [ansible/ansible#73766]
##### SUMMARY
There was issue #39553: file applying owner/group/mode to symlink destination, not the link itself in Ansible
Looks like it's considered to be expected behaviour.
On the other hand, ansible creates symlinks with `root:root` owner when privilege escalation enabled.

The only way to create link with correct owner/group is to become another user, e.g. on GNU/Linux:
```yaml
- name: "Create symlink"
  become: yes
  become_user: myuser
  become_method: sudo
  become_flags: '-g mygroup'
  file:
    state: link
    # ...
```

Is it possible to document such workaround and mention it in #39553 (closed for commenting)?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
file builtin module

##### ANSIBLE VERSION

```paste below
ansible 2.10.6
  config file = None
  configured module search path = ['/home/sergeyshambir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Feb 19 2021, 09:27:16) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu Bionic 18.04 LTS
