### ISSUE TITLE
vmware_guest module will not connect interface when disk is defined while cloning

### ISSUE THREAD

**Issue by NiftyMist** [ansible/ansible#73774]
### Summary

I am trying to clone a VM with vmware_guest.  When I do not define the disk, the resulting VM will connect its interface and be reachable on the network.  When disk is defined, it will not connect the interface.

### Issue Type

Bug Report

### Component Name

vmware_guest

### Ansible Version

```console (paste below)
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

vCenter (not sure of exact version as I don't have permissions to the see) and CentOS 7 (vm template/resulting vm).

### Steps to Reproduce

```yaml (paste below)
- name:  Create a vm from a template
  vmware_guest:
    annotation: "BuiltFromTemplate:{{ vmclone_template }}"
    hostname: "{{ vmclone_vcenter_hostname.stdout }}"
    username: "{{ vmclone_vcenter_username.stdout }}"
    password: "{{ vmclone_vcenter_password.stdout }}"
    validate_certs: "{{ vmclone_validate_certs }}"
    datacenter: "{{ vmclone_vcenter_datacenter }}"
    state: "{{ vmclone_state }}"
    folder: "{{ vmclone_vcenter_datacenter }}/vm/{{ vmclone_vcenter_folder }}"
    template: "{{ vmclone_template }}"
    name: "{{ vmclone_vmname }}"
    cluster: "{{ vmclone_vcenter_cluster }}"
    disk:
    - autoselect_datastore: yes
      size_gb: "{{ vmclone_disk_gb_size }}"
    networks:
      - name: "{{ vmclone_network }}"
        ip: "{{ vmclone_ip }}"
        gateway: "{{ vmclone_gateway }}"
        netmask: "{{ vmclone_netmask }}"
        type: static
        connected: yes
        start_connected: yes
    wait_for_ip_address: "{{ vmclone_wait_for_ip_address }}"
    hardware:
      memory_mb: "{{ vmclone_memory }}"
      num_cpus: "{{ vmclone_cpus }}"
    customization:
      dns_servers:
        - "{{ vmclone_dns_server }}"
      dns_suffix:
        - "{{ vmclone_dns_suffix }}"
  delegate_to: localhost
```

### Expected Results

A new vm with network connected and disk sized according to definition.  

### Actual Results

```
{
  "changed": true,
  "instance": {
    "module_hw": true,
    "hw_name": "test03.********",
    "hw_power_status": "poweredOn",
    "hw_guest_full_name": "CentOS 7 (64-bit)",
    "hw_guest_id": "centos7_64Guest",
    "hw_product_uuid": "42252693-9d1d-ada4-03c0-60fb94982952",
    "hw_processor_count": 1,
    "hw_cores_per_socket": 1,
    "hw_memtotal_mb": 1024,
    "hw_interfaces": [
      "eth0"
    ],
    "hw_datastores": [
      "esx-004_datastore-001"
    ],
    "hw_files": [
      "[esx-004_datastore-001] test03.********/test03.********.vmx",
      "[esx-004_datastore-001] test03.********/test03.********.nvram",
      "[esx-004_datastore-001] test03.********/test03.********.vmsd",
      "[esx-004_datastore-001] test03.********/test03.********.vmdk"
    ],
    "hw_esxi_host": "X.X.X.X",
    "hw_guest_ha_state": null,
    "hw_is_template": false,
    "hw_folder": "redacted",
    "hw_version": "vmx-14",
    "instance_uuid": "5025c803-b1f9-9d55-eabf-3d23f9639a0f",
    "guest_tools_status": "guestToolsRunning",
    "guest_tools_version": "11269",
    "guest_question": null,
    "guest_consolidation_needed": false,
    "ipv4": "********3",
    "ipv6": null,
    "annotation": "BuiltFromTemplate:CentOS7-Template-20210120_2002",
    "customvalues": {},
    "snapshots": [],
    "current_snapshot": null,
    "vnc": {},
    "moid": "vm-103803",
    "vimref": "vim.VirtualMachine:vm-103803",
    "hw_cluster": "DevNet",
    "hw_eth0": {
      "addresstype": "assigned",
      "label": "Network adapter 1",
      "macaddress": "00:50:56:a5:5b:3c",
      "ipaddresses": [
        "********3"
      ],
      "macaddress_dash": "00-50-56-a5-5b-3c",
      "summary": "v1630-DN-DV-SVS",
      "portgroup_portkey": null,
      "portgroup_key": null
    }
  },
  "invocation": {
    "module_args": {
      "annotation": "BuiltFromTemplate:CentOS7-Template-20210120_2002",
      "hostname": "redacted",
      "username": "redacted",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "validate_certs": false,
      "datacenter": "Development",
      "state": "poweredon",
      "folder": "redacted",
      "template": "CentOS7-Template-20210120_2002",
      "name": "test03.********",
      "cluster": "DevNet",
      "disk": [
        {
          "autoselect_datastore": true,
          "size_gb": "20"
        }
      ],
      "networks": [
        {
          "name": "v1630-DN-DV-SVS",
          "ip": "********3",
          "gateway": "172.16.30.1",
          "netmask": "255.255.255.0",
          "type": "static",
          "connected": true,
          "start_connected": true
        }
      ],
      "wait_for_ip_address": true,
      "hardware": {
        "memory_mb": "1024",
        "num_cpus": "1"
      },
      "customization": {
        "dns_servers": [
          "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        ],
        "dns_suffix": [
          "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        ]
      },
      "port": 443,
      "is_template": false,
      "customvalues": [],
      "name_match": "first",
      "use_instance_uuid": false,
      "cdrom": [],
      "force": false,
      "state_change_timeout": 0,
      "linked_clone": false,
      "wait_for_customization": false,
      "vapp_properties": [],
      "proxy_host": null,
      "proxy_port": null,
      "uuid": null,
      "guest_id": null,
      "esxi_hostname": null,
      "snapshot_src": null,
      "resource_pool": null,
      "customization_spec": null,
      "datastore": null,
      "convert": null
    }
  },
  "_ansible_no_log": false,
  "_ansible_delegated_vars": {}
}
```
