### ISSUE TITLE
ansible.builtin.uri POST ndjson file on form-multipart body KO

### ISSUE THREAD

**Issue by PengBAI** [ansible/ansible#73847]
### Summary

Hello,
I'm using the uri module with "body_format: form-multipart" to POST a ndjson file to kibana import API https://www.elastic.co/guide/en/kibana/master/saved-objects-api-import.html, 
Here is the example https://www.elastic.co/guide/en/kibana/master/saved-objects-api-import.html#saved-objects-api-import-example that I want to pass in an ansible task.
But it's KO.

### Issue Type

Bug Report

### Component Name

ansible.builtin.uri

### Ansible Version

2.10.6

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Linux 5.4.0-66-generic #74-Ubuntu

### Steps to Reproduce

```yaml (paste below)
      - name: Import saved objects 
        uri:
          url: http://{{ kibana_host }}:5601/api/saved_objects/_import?overwrite=true
          method: POST
          user: "{{ elastic_username }}"
          password: "{{ elastic_user_password }}"
          force_basic_auth: yes
          src: /etc/kibana/saved_objects.ndjson
          remote_src: yes
          body_format: form-multipart
          headers: 
            kbn-xsrf: true 

```

### Expected Results

get a 200, API OK

### Actual Results

```console (paste below)
"msg": "failed to parse body as form-multipart: Mapping is required, cannot be type NoneType" 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
You cannot use `src` with `body_format`.

To do what you want would require something like:

```
body_format: form-multipart
body:
  file:
    filename: /etc/kibana/saved_objects.ndjson
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
