### ISSUE TITLE
Diff not shown for deleted file

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#73848]
### Summary

The `file` module with `state: absent` doesn't show the content of the deleted file when `--diff` is used. It should be there since it can be useful to see the state of the old file at a glance to make sure you deleted what you expected, and to have it in the log file for future reference.

### Issue Type

Feature Idea

### Component Name

file

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi @rightaway

I've been thinking about implementing this functionality but every time I read the issue, I cannot see how to implement it. 

What do you expect if you delete a document file a spreadsheet or any other binary?

IMHO, I think Ansible should manage the deletion itself and the `diff` show the action. If you want a functionality like that, you can cat your file before deletion:

```yaml
---
- name: Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    filename: "xx"
    dirname: "~/Temp"

  tasks:

    - name: cat
      command: cat "{{ filename }}"
      args:
        chdir: "{{ dirname }}"
      register: cat

    - name: print
      debug:
        msg: "{{cat.stdout}}"

    - name: delete
      file:
        path: "{{ dirname }}/{{ filename }}"
        state: absent
```

**Comment by rightaway** [comment]
@imjoseangel That looks like lot of boilerplate especially if you're removing lots of files. If you can detect whether it's a binary file then just print a message saying that the "diff not available because binary file". And if it's any kind of text file then it should show the diff.

Since diffs are shown on additions or changes, I think it should show removals to be consistent. How does the diff look now for addition of binary files?

**Comment by imjoseangel** [comment]
@rightaway thanks for your comments. Agree. Let me have a look to a possible solution.

**Comment by anemyte** [comment]
It's bewildering how this hasn't occurred earlier. +1 for the feature.

For now, I came up with a slightly better "bolierplate": copy `/dev/null` into the file that's about to be deleted to trigger the diff:
```yaml
- copy:
    src: /dev/null
    dest: /target/file.txt
  check_mode: yes
```
