### ISSUE TITLE
Problem with conditional role dependencies: conditions are overwritten

### ISSUE THREAD

**Issue by lufik** [ansible/ansible#7387]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.1
##### Environment:

CentOS 6 + epel + ansible from epel-testing
##### Summary:

I have a problem with conditional roles and their conditional dependencies:

testcase.yml:

```

---
# playbook for all
- hosts: all
  roles:
    - role: a
      when: false
```

roles/a/meta/main.yml:

```

---
dependencies:
  - role: b
    when: true
```

roles/a/tasks/main.yml:

```
- debug: msg="Running role a"
```

roles/b/tasks/main.yml:

```
- debug: msg="Running role b"
```
##### Steps To Reproduce:

Use above example and run it.
##### Expected Results:

all roles skipped
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [b | debug msg="Running role b"] **************************************** 
ok: [localhost] => {
    "item": "", 
    "msg": "Running role b"
}

TASK: [a | debug msg="Running role a"] **************************************** 
skipping: [localhost]

PLAY RECAP ******************************************************************** 
localhost : ok=2    changed=0    unreachable=0    failed=0
```
