### ISSUE TITLE
monit module failed when service is running with state=started

### ISSUE THREAD

**Issue by yosshy** [ansible/ansible#7389]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.5.3
##### Environment:

Ubuntu 13.10 amd64
##### Summary:

service module allows service running with state=started, but monit module doesn't.
I think it should be same as service module because it's not action but state.
##### Steps To Reproduce:
1. put files below:
   you have to replace ANYGROUP part with real one.

-- test.yml

```
- name: service module test (good case)
  hosts: ANYGROUP
  sudo: yes
  gather_facts: false
  tasks:
    - file: dest=/etc/monit/conf.d/rsyslog state=absent
    - service: name=monit state=restarted
      ignore_errors: yes
    - service: name=rsyslog state=stopped
    - service: name=rsyslog state=started
    - service: name=rsyslog state=started

- name: monit module test (bad case)
  hosts: ANYGROUP
  sudo: yes
  gather_facts: false
  tasks:
    - apt: pkg=monit state=installed
    - copy: src=rsyslog.monit dest=/etc/monit/conf.d/rsyslog mode=755 owner=root group=root
    - service: name=monit state=restarted
    - command: sleep 5
    - monit: name=rsyslog state=stopped
    - command: sleep 5
    - monit: name=rsyslog state=started
    # It will failed below:
    - monit: name=rsyslog state=started
```

-- rsyslog.monit

```
check process rsyslog with pidfile "/var/run/rsyslogd.pid"
   start program = "/usr/sbin/service rsyslog start"
   stop program = "/usr/sbin/service rsyslog stop"
```
1. run ansible-playbooks
   
   `$ ansible-playbooks test.yml`
##### Expected Results:

All tasks will succeed.
##### Actual Results:

The last one failed.

**Comment by mpdehaan** [comment]
Can you please share the steps to reproduce this problem?

Thanks!

**Comment by yosshy** [comment]
##### Issue Type:

Bug Report

##### Ansible Version:

ansible 1.5.3

##### Environment:

Ubuntu 13.10 amd64

##### Summary:

service module allows service running with state=started, but monit module doesn't.
I think it should be same as service module because it's not action but state.

##### Steps To Reproduce:
1. put files below:
   you have to replace ANYGROUP part with real one.

-- test.yml

```
- name: service module test (good case)
  hosts: ANYGROUP
  sudo: yes
  gather_facts: false
  tasks:
    - file: dest=/etc/monit/conf.d/rsyslog state=absent
    - #command: service monit restart
      service: name=monit state=restarted
      ignore_errors: yes
      service: name=monit state=restarted
      ignore_errors: yes
    - service: name=rsyslog state=stopped
    - service: name=rsyslog state=started
    - service: name=rsyslog state=started

- name: monit module test (bad case)
  hosts: ANYGROUP
  sudo: yes
  gather_facts: false
  tasks:
    - apt: pkg=monit state=installed
    - copy: src=rsyslog.monit dest=/etc/monit/conf.d/rsyslog mode=755 owner=root group=root
    - service: name=monit state=restarted
    - command: sleep 5
    - monit: name=rsyslog state=stopped
    - command: sleep 5
    - monit: name=rsyslog state=started
    # It will failed below:
    - monit: name=rsyslog state=started
```

-- rsyslog.monit

```
check process rsyslog with pidfile "/var/run/rsyslogd.pid"
   start program = "/usr/sbin/service rsyslog start"
   stop program = "/usr/sbin/service rsyslog stop"
```
1. run ansible-playbooks
   
   `$ ansible-playbooks test.yml`

##### Expected Results:

All tasks will succeed.

##### Actual Results:

The last one failed.
