### ISSUE TITLE
`become: no` does not work on local connection without become_user

### ISSUE THREAD

**Issue by perryflynn** [ansible/ansible#73898]
### Summary

When I use `become: no` without `become_user` on a task, it will ignored and tries to become root.

### Issue Type

Bug Report

### Component Name

become, sudo, connection

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.10.6
  config file = /home/christian/ansible-next/ansible.cfg
  configured module search path = ['/home/christian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/christian/ansible-next/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/home/christian/ansible-next/ansible.cfg) = 3
COLLECTIONS_PATHS(/home/christian/ansible-next/ansible.cfg) = ['/home/christian/ansible-next/collections', '/usr/share/ansible/collections']
DEFAULT_BECOME(/home/christian/ansible-next/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/christian/ansible-next/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/christian/ansible-next/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/christian/ansible-next/ansible.cfg) = root
DEFAULT_FORKS(/home/christian/ansible-next/ansible.cfg) = 5
DEFAULT_LOG_PATH(/home/christian/ansible-next/ansible.cfg) = /home/christian/ansible-next/ansible-last.log
DEFAULT_REMOTE_USER(/home/christian/ansible-next/ansible.cfg) = bbadmin
DEFAULT_ROLES_PATH(/home/christian/ansible-next/ansible.cfg) = ['/home/christian/ansible-next/roles', '/etc/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/christian/ansible-next/ansible.cfg) = /home/christian/ansible-next/bbansible/gpg-vault-client.sh
INTERPRETER_PYTHON(/home/christian/ansible-next/ansible.cfg) = auto_silent
```

### OS / Environment

Arch Linux, latest updates installed.

### Steps to Reproduce

```yaml (paste below)
# a role main.yml file:
---
- name: Restart server
  shell: 'sleep 5 && reboot'
  poll: 0
  async: 1

- name: Wait for reboot completes
  wait_for:
    port: '{{ansible_ssh_port|default(22)}}'
    host: '{{ansible_ssh_host|default(ansible_host)|default(inventory_hostname)}}'
    search_regex: OpenSSH
    delay: 0
    sleep: 1
    timeout: 300
    state: "{{bbreboot_stage_loop_item}}"
  connection: local
  become: no
  loop:
    - stopped
    - started
  loop_control:
    loop_var: bbreboot_stage_loop_item
```

### Expected Results

Reboot started, `wait_for` reports stopped, `wait_for` reports started.

### Actual Results

```console (paste below)
failed: [gitrunner.srv.example.de] (item=stopped) => {"ansible_loop_var": "bbreboot_stage_loop_item", "bbreboot_stage_loop_item": "stopped", "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}                                                                                                                                              
failed: [gitrunner.srv.example.de] (item=started) => {"ansible_loop_var": "bbreboot_stage_loop_item", "bbreboot_stage_loop_item": "started", "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

// edit:
It can be reproducted with the following task as well:

```yml
- shell: id -u -n
  register: user
  connection: local
  become: no
```

//edit2
Use the env lookup to get the non-root unix account name works as well:

```yml
- shell: id -u -n
  register: user
  connection: local
  become: no
  become_user: "{{lookup('env', 'LOGNAME') | default(lookup('env', 'USER'))}}"
```
