### ISSUE TITLE
Module user fails when using `local` and `force` together

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#73891]
### Summary

The option `local` uses the `luserdel` command low-level, however this command does not understand the option `-f/--force`. So the module should ignore the `-f/--force` option or provide a warning rather than error out.

### Issue Type

Bug Report

### Component Name

user

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.18
  config file = /home/ldap/elprh/git/ansi-linux/ansible.cfg
  configured module search path = ['/home/ldap/elprh/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

CentOS 7.9

### Steps to Reproduce

```yaml (paste below)
  - name: Remove leftover functional users
    user:
      name: '{{ item }}'
      force: yes
      local: yes
      remove: yes
      state: absent
    loop:
    - centos
    - cloud-user
    - cockpit-ws
    - cockpit-wsinstance
```

### Expected Results

No error when the user exists.

### Actual Results

```console (paste below)
TASK [Remove leftover functional users] ***************************************************************************
failed: [morsuv1455] (item=centos) => {"ansible_loop_var": "item", "changed": false, "item": "centos", "msg": "Error parsing arguments: unknown option.\nUsage: luserdel [-iGr?] [-i|--interactive] [-G|--dontremovegroup]\n        [-r|--removehome] [-?|--help] [--usage] [OPTION...] user\n", "name": "centos", "rc": 1}
```
