### ISSUE TITLE
ini lookup fails with indented lines

### ISSUE THREAD

**Issue by oyxnaut** [ansible/ansible#73907]
### Summary

When using the ini lookup, Ansible fails with `fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ini'. Error was a <class 'ConfigParser.ParsingError'>, original message: File contains parsing errors: <???>\n\t[line  2]: u'  key = \"123\"\\n'"}`.

### Issue Type

Bug Report

### Component Name

ini lookup plugin

### Ansible Version

```console
$ ansible --version
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/oyxnaut/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
<empty>
```

### OS / Environment

Ubuntu 18.04

### Steps to Reproduce

For testing purposes, I've created two ini files:
ini-w-spaces.ini:
```ini
[default]
  key = "123"
```
ini-wo-spaces.ini:
```ini
[default]
key = "456"
```
and the following playbook:
```yml
---
- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        foo: "{{ lookup('ini', 'key section=default file=ini-w-spaces.ini') }}"
        bar: "{{ lookup('ini', 'key section=default file=ini-wo-spaces.ini') }}"
    - debug:
        msg: "foo is {{ foo }} bar is {{ bar }}"
```

### Expected Results

Ansible writes `"msg": "foo is \"123\" bar is \"456\""` to stdout

### Actual Results

Ansible errors out with
```console
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ini'. Error was a <class 'ConfigParser.ParsingError'>, original message: File contains parsing errors: <???>\n\t[line  2]: u'  key = \"123\"\\n'"}
```
