### ISSUE TITLE
Add a dynamic_map constructor for YAML maps

### ISSUE THREAD

**Issue by jnm27** [ansible/ansible#73933]
### Summary

It is not possible to define a map in vars that references prior values in the same map. For example:

````
    test_map:
      version: 1.0
      uses_version: "{{ version }}"
````
Or something like that.

This type of variable declaration would be very useful for concisely defining data structures in YAML.

In addition, it would be useful to be able to mark and reference the values of keys within the same dict. For example:
````
    versions:
      "1.0":
          path: "/opt/{{ version }}"
````

Using an informal implementation of my other request, https://github.com/ansible/ansible/issues/73932, I have implemented a "dynamic_map" constructor to do this. Example usage:

````
    new_map: !dynamic_map
      version: 1.0
      type: "{{ '%version%' | regex_replace('0','1') }}"
````
Outputs:
````
TASK [debug] ******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] =>
  new_map:
    type: '1.1'
    version: 1.0
````

And to be able to reference key values, I added an optional _schema dict that defines the "names" of keys, and adds them to the custom variable substitution list. For example:
````
    example_map: !dynamic_map
      _schema:
          version:
      "1.0":
        type: "/opt/(%version%)"
      "2.0":
        type: "/bin/(%version%)"
````
Outputs:
````
TASK [debug] ******************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] =>
  example_map:
    '1.0':
      type: /opt/(1.0)
    '2.0':
      type: /bin/(2.0)
````

It also supports nesting, dict, and list substitution.

The schema for keys is not that important, but having dynamic internal variable substitution within map definitions would be very useful.

If someone wants to try to implement this formally, I am willing to work with them to share my informal implementation.

### Issue Type

Feature Idea

### Component Name

dynamic_map

### Additional Information

```yaml (paste below)

```
