### ISSUE TITLE
pause task with minutes/seconds can continue with 'enter'

### ISSUE THREAD

**Issue by x1e** [ansible/ansible#73948]
### Summary

When this playbook is run:
```yaml
---
- hosts: all
  tasks:
    - pause:
        minutes: 2
```
Then in this scene:
```bash
TASK [pause] ************
Pausing for 120 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
```
Before ansible 2.9.15, must use 'ctrl+C' then 'C' or 'A' to continue.
But in ansible 2.9.16 to 2.10.7, this scene can use 'enter' to continue.

### Issue Type

Bug Report

### Component Name

pause

### Ansible Version

2.9.16 to 2.10.7

### Configuration

none

### OS / Environment

debian 9

### Steps to Reproduce

```yaml
---
- hosts: all
  tasks:
    - pause:
        minutes: 2
```

### Expected Results

Must use 'ctrl+C' then 'C' or 'A' to continue. Do not response 'enter' to continue.

### Actual Results

Press 'enter' this task to continue.
