### ISSUE TITLE
ansible.builtin.script module deletes the russian text in stdout

### ISSUE THREAD

**Issue by ofigenov** [ansible/ansible#73940]
### Summary
ansible.builtin.script module deletes the russian text in stdout.

### Issue Type

Bug Report

### Component Name

ansible.builtin.script

### Ansible Version

```console (paste below)
$ ansible --version
ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed
DEFAULT_ASK_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_SSH_TRANSFER_METHOD(/etc/ansible/ansible.cfg) = piped
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

### OS / Environment

CentOS Linux release 7.4.1708

### Steps to Reproduce

```yaml (paste below)
create script test.sh:
echo "Русский текст Text"

create playbook:

- hosts: localhost
  gather_facts: no

  tasks:

    - shell: "bash ./test.sh"
      register: testout

    - name: Output result of checking
      debug:
        var: testout.stdout

```

### Expected Results

if I replace 'script' module with shell+bash module then is correct result:
TASK [Output result of checking] ***************************************************************************************************
ok: [localhost] =>
  testout.stdout: Русский текст Text

### Actual Results

```TASK [Output result of checking] ***************************************************************************************************
ok: [localhost] =>
  testout.stdout: |2-
      Text

```
