### ISSUE TITLE
be able to utilize last command result to update variables in playbook

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#74]
Something like this:

```
- tasks:
   - name: foo
     action: foo
   - name: <optional>
     setvar: xyz
     value: {{ some transmogrification of $last_result where $last_result is the per host hash result }}
```

(This probably wouldn't make the variable available in templates unless we added a way to refresh the setup variables, which could be saved for later)
