### ISSUE TITLE
New role argument spec doesn't support arbitrary keys

### ISSUE THREAD

**Issue by phemmer** [ansible/ansible#74001]
### Summary

#73152 added support for specifying a role's arguments. However the specification format doesn't allow defining a dict with arbitrary keys.

For example lets say you want to represent a bunch of users, such as:
```
users:
  john:
    id: 1000
    home: /home/john
  marcy:
    id: 1001
    home: /home/marcy
```

In this scenario each user is of a rigid structure. However because the keys of the `users` dictionary are arbitrary, we can't specify them using the current role argument schema, as using `suboptions` requires you to define a fixed list of possible keys.

### Issue Type

Bug Report

### Component Name

validate_argument_spec

### Ansible Version

2.11

### Configuration

n/a

### OS / Environment

n/a

### Steps to Reproduce

n/a

### Expected Results

n/a

### Actual Results

n/a
