### ISSUE TITLE
Variables in inventory file are not evaluated when gather_facts is false.

### ISSUE THREAD

**Issue by cduez** [ansible/ansible#7402]
##### Issue Type:

Bug Report
##### Ansible Version:

>= 1.5.4
##### Environment:

N/A
##### Summary:

"Inventory variables" are not evaluated with `gather_facts: false`
##### Steps To Reproduce:

**playbook:**
_example.yml_

```

---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python2"
  vars_files:
    - ./{{ env }}.yml
  tasks:
    - command: /bin/echo {{ msg }}
```

**inventory:**
_inventory_
`localhost env=dev`

**var file:**
_dev.yml_

```

---
msg: hello
```
##### Expected Results:

```
$ ansible-playbook example.yml -i inventory
[...]
TASK: [command /bin/echo {{msg}}] ********************************************* 
changed: [localhost]
[...]
```
##### Actual Results:

```
$ ansible-playbook example.yml -i inventory
[...]
TASK: [command /bin/echo {{msg}}] ********************************************* 
fatal: [localhost] => One or more undefined variables: 'msg' is undefined

FATAL: all hosts have already failed -- aborting
[...]
```
##### Comment:

Didn't find anything about this change, might not be a bug since i don't know if variables put in the inventory file are "facts".
