### ISSUE TITLE
win_get_url: support `file://` urls?

### ISSUE THREAD

**Issue by jayunit100** [ansible/ansible#74059]
### Summary

Id like to use 
```
module: get_url
short_description: Downloads files from HTTP, HTTPS, or FTP to node
```
to 
```
module: get_url
short_description: Downloads files from HTTP, HTTPS, Files, or FTP resources to a destination on a node.
```

### Issue Type

Feature Idea

### Component Name

windows

### Additional Information

```
- name: Get kubernetes binaries
  win_get_url:
    url: file://kube-executables/kube-proxy.exe"
    dest: 'c://k/bin/kube-proxy.exe'
```
