### ISSUE TITLE
dns_servers option not working in docker_container module

### ISSUE THREAD

**Issue by sona1990** [ansible/ansible#74062]
### Summary

When i try to create docker container with dns_servers options to pass custom dns server IP, the provided IP is not reflected inside /etc/resolv.conf of container

### Issue Type

Bug Report

### Component Name

docker_container

### Ansible Version

```
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/alef/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Mar  1 2021, 11:38:31) [GCC 5.4.0 20160609]

```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```
- name: Create Container
  docker_container:
    dns_search_domains: test.com
    name: "nginx{{ item }}"
    image: nginx
    state: started
    recreate: yes
    detach: yes
    privileged: yes
    restart_policy: always
    shm_size: 1g
    user: apps
    networks:
      - name: demo-br
    ports:
      - "80:80"
    dns_servers: 1.1.1.1
  with_sequence: count=1

```

### Expected Results

I expect 
```
docker exec -it nginx1 cat /etc/resolv.conf
```
to get
```
search test.com
nameserver 1.1.1.1
options ndots:0
```

### Actual Results

```
search test.com
nameserver 127.0.0.11
options ndots:0


```
