### ISSUE TITLE
Facter denylist/allowlist facts

### ISSUE THREAD

**Issue by Enetrati** [ansible/ansible#74066]
### Summary

With facter doing the "everything or nothing" approach on gathering facts from the system. From an security perspective this is very tricky because not all information is being gathered. And on a 'need to know'-basis is a more healthier way of gathering facts.

That's why I came up with the idea of an a deny/allow list of facts on what facts you may or may not gather with every system.

### Issue Type

Feature Idea

### Component Name

ansible.cfg playbook host_vars group_vars

### Additional Information

```yaml (paste below)

  - allow_facts:
     - ansible_date_time
  - deny_facts:
     - ansible_os_family

```
