### ISSUE TITLE
add support for command execution and avoid retrieving stdout/exit code

### ISSUE THREAD

**Issue by lmayorga1980** [ansible/ansible#74096]
### Summary

I have a local task that is executed against a remote machine and changes it's ip address(static ip configuration). This is a proprietary prompt and maybe ansible is waiting to retrieve the stdout/stderr/rc from the command itself.

```
    - name: Network Setup
      command: "{{ssh_exit}} network;setup;update; set dhcp=false; set defaultRoute={{default_route}}; set primaryAddress={{static_ip}}/22; set dnsServers={{dns_servers}}; set dnsDomain={{dns_domain}}; commit; exit"
      delegate_to: 127.0.0.1
      tags:
        - ip
```
The **ssh_exit** looks like this

```
ssh_exit: ssh -t -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i ~/.ssh/myrsa user@{{inventory_hostname}}
```
Ansible is able to execute the command and I can see my remote system with the new network configuration but it waits in a loop until I get an error like this:

** client_loop: send_disconnect: Broken pipe **

### Issue Type

Feature Idea

### Component Name

command

### Additional Information

```yaml (paste below)

```
