### ISSUE TITLE
iptables module should allow selective flush of chain rules

### ISSUE THREAD

**Issue by ghomem** [ansible/ansible#74097]
### Summary

I have found no way of flushing one or more iptables chains selectively, i.e., flushing all the rules except the ones that match a certain regex. This is necessary when a firewall is mostly managed by Ansible but some of the rules are managed elsewhere (ex: Docker) and should not be manipulated.

### Issue Type

Bug Report

### Component Name

iptables

### Ansible Version

```console (paste below)
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/remoteops/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

```

### Configuration

```console (paste below)
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```
- name: Clean rules on all chains of filter table
  iptables:
    table: filter
    flush: yes
    ignore: 'docker' # this is not supported

```

### Expected Results

I expected to be able to do selective purging.

### Actual Results

I found no option to achieve that result.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/iptables.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/iptables.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Question About This One
=======================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us that you've taken time to contribute.

Unfortunately, we're not sure if we want this feature in the program, as we're not sure how it would be added to the module. Implementing it may also add a lot of complexity to the module.

However, we're absolutely always up for discussion and would consider including the feature. You can stop by the development list or IRC, and we'd be glad to talk about it - and we might even be persuaded otherwise!

   * https://groups.google.com/forum/#!forum/ansible-devel
   * #ansible-devel on Freenode IRC

needs_info

**Comment by ghomem** [comment]
Hello,

Thanks for taking your time to examine this report and for requesting further persuasion :-)

I am leaving here some topics that might be relevant:

1. there are cases where we need to manage the firewall rules centrally but we need to stay away of certain rules; Docker is one such case but there may be others ( https://github.com/moby/moby/issues/12294 );
2. "Implementing it may also add a lot of complexity to the module" but the alternative to having such complexity encapsulated in the module is the complexity multiplied on user playbooks (see below) or the module not being usable for certain scenarios;
3. The puppetlabs-firewall module supports this feature

I will post here some examples of code:

Desired Ansible code:
```
- name: Clean rules except the ones that match "docker"
  iptables:
    table: {{ item }}
    flush: yes
    ignore: 'docker'
    loop:
      - filter
      - nat
```
Actual workaround code:

```
# Normal case - no exceptions on the cleanup

- name: Clean rules on all chains of filter table
  iptables:
    table: filter
    flush: yes
  when: my_firewall_ignore | length == 0

- name: Delete all user-defined chains on filter table
  shell: iptables -t filter -X
  when: my_firewall_ignore | length == 0

- name: Clean rules on all chains of nat table
  iptables:
    table: nat
    flush: yes
  when: my_firewall_ignore|length == 0

- name: Delete all user-defined chains on nat table
  shell: iptables -t nat -X
  when: my_firewall_ignore | length == 0

# Case where we need to ignore the rules that contain the expression {{ my_firewall_ignore }}

- name: Clean rules on the nat and filter tables except the ones containing a certain expression
  shell: "iptables-save -t {{ item }} | grep '^-A' | grep -iv {{ my_firewall_ignore }} | sed 's/^-A/iptables -t {{ item }} -D/g' | xargs -r -d'\n' -n1 /bin/bash -c"
  when: my_firewall_ignore | length > 0
  loop:
    - filter
    - nat
```
Example using puppetlabs-firewall

```
firewallchain { 'FORWARD:filter:IPv4': ensure => present, purge => true, policy => drop, ignore => [ "[^\"]*(?i:${ignore_pattern})[^\"]*" ] }
firewallchain { 'INPUT:filter:IPv4':   ensure => present, purge => true, policy => drop, ignore => [ "[^\"]*(?i:${ignore_pattern})[^\"]*" ] }
```
Does this information help explaining the need?

Thanks again.
