### ISSUE TITLE
Composer install taking forever to finish

### ISSUE THREAD

**Issue by william-mymy** [ansible/ansible#74150]
### Summary

Ansible Version: 2.9.16
Composer Version: 2.0.12
Operating System: Ubuntu 18.04 (in both servers)
ansible-config dump --only-changed dumped nothing

Hello,

I was running Composer 1.10.8 on my server. Everything was running smoothly without any problem until last Thursday when I decided to update Composer from 1.10.8 to 2.0.12. Now, the composer install command takes forever to complete and the whole deployment process is stuck.

Ansible playbook where it is stuck
```
    - composer:
        command: install
        working_dir: "{{releases_folder}}/{{ release_id }}/cms"
        no_dev: no
      tags:
        - deploy
```

Composer require packages
```
  "require": {
    "ext-json": "*",
    "craftcms/aws-s3": "^1.2.11",
    "craftcms/cms": "^3.6.6",
    "craftcms/commerce": "3.2.17.2",
    "craftcms/commerce-paypal-checkout": "^1.2.0",
    "craftcms/commerce-stripe": "^2.3.2.1",
    "craftcms/element-api": "^2.6",
    "craftcms/feed-me": "^4.3.5.1",
    "craftcms/guest-entries": "^2.3",
    "craftcms/postmark": "^2.1.0",
    "craftcms/redactor": "^2.8.5",
    "doublesecretagency/craft-cpcss": "^2.3.0",
    "doublesecretagency/craft-siteswitcher": "^2.2.0",
    "league/geotools": "^0.8.1",
    "mmikkel/incognito-field": "^1.2.0",
    "mwc/mymy": "1.0.0",
    "nystudio107/craft-cookies": "^1.1.12",
    "nystudio107/craft-imageoptimize": "^1.6.23",
    "nystudio107/craft-minify": "^1.2",
    "nystudio107/craft-retour": "^3.1.46",
    "nystudio107/craft-seomatic": "^3.3.32",
    "nystudio107/craft-templatecomments": "^1.1",
    "nystudio107/craft-twigpack": "^1.2.9",
    "putyourlightson/craft-log-to-file": "^1.1",
    "sebastianlenz/linkfield": "^1.0.24",
    "solspace/craft3-calendar": "^3.2.0",
    "superbig/craft-mjml": "1.0.5",
    "topshelfcraft/environment-label": "^3.2.0",
    "topshelfcraft/wordsmith": "^3.1",
    "vlucas/phpdotenv": "^3.4.0",
    "yiisoft/yii2-redis": "^2.0"
  },
```

P.S. Weird thing is, if I SSH into the server and run composer install by myself, it works without any problem. So, I might be doing something wrong with Ansible or I might need to update something.

### Issue Type

Bug Report

### Ansible Version

```console (paste below)
$ ansible --version
2.9.16
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 18.04

### Steps to Reproduce

```yaml (paste below)
- hosts: STAGING
  vars:
    app_root_folder: "/var/www/"
    releases_folder: "/var/www/mymycms"
    web_root_folder: "{{releases_folder}}/current"
    local_releases_folder: "/var/lib/jenkins/cms-release/"
    local_ansible_folder: "/var/lib/jenkins/deployment/ansible"
    staging_nginx_config_folder: "/etc/nginx/sites-available"
    app_user: ubuntu
    app_group: www-data
    root_user: root
  become: yes
  become_method: sudo
  tasks:

    - name: create a new release folder
      file:
        path: "{{web_root_folder}}"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '0775'
        recurse: yes
      tags:
        - build

    - name: put source code to release folder
      become: yes
      become_method: sudo
      copy:
        src: "{{ local_releases_folder }}{{ release_id }}.tar"
        dest: "{{releases_folder}}/{{ release_id }}.tar"
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '0775'
      tags:
        - deploy

    - name: unpack source code
      unarchive:
        remote_src: yes
        src: "{{ releases_folder }}/{{release_id}}.tar"
        dest: "{{ releases_folder }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
      tags:
        - deploy

    - name: remove source code archieve
      file:
        path: "{{releases_folder}}/{{release_id}}.tar"
        state: absent
        remote_src: yes
      tags:
        - deploy

    - name: copy .env file to current dir
      copy:
        src: "{{ app_root_folder }}.env"
        dest: "{{ releases_folder }}/{{release_id}}/cms/.env"
        remote_src: yes
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '0775'
      tags:
        - deploy

    - composer:
        command: install
        working_dir: "{{releases_folder}}/{{ release_id }}/cms"
        no_dev: no
      tags:
        - deploy

    - composer:
        command: dump-autoload
        working_dir: "{{releases_folder}}/{{ release_id }}/cms"
      tags:
        - deploy

    - composer:
        command: clear-cache
        working_dir: "{{releases_folder}}/{{ release_id }}/cms"
      tags:
        - deploy

    - name: set storage folder permissions
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create runtime folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create cache folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/cache"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create mutex folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/mutex"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create assets folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/assets"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create compiled_classes folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/compiled_classes"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create compiled_templates folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/compiled_templates"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create temp folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/temp"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create commerce_dompdf folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/runtime/temp/commerce_dompdf"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: create logs folder with permission
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/storage/logs"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_group}}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    - name: set permission for vendor folder
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/vendor"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '774'
        recurse: yes
      tags:
        - deploy

    - name: set web folder permissions
      file:
        path: "{{ releases_folder }}/{{release_id}}/cms/web"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '777'
        recurse: yes
      tags:
        - deploy

    # change craft script ownership
    - file:
        path: "{{releases_folder}}/{{ release_id }}/cms/craft"
        owner: "{{root_user}}"
        group: "{{root_user}}"
        mode: 0774
      tags:
        - deploy

    - name: running craftcms migration
      shell: "php {{releases_folder}}/{{ release_id }}/cms/craft migrate/all"
      tags:
        - deploy

    - name: syncing project config
      shell: "php {{releases_folder}}/{{ release_id }}/cms/craft project-config/sync"
      tags:
        - deploy

    - name: clearing cache
      shell: "php {{releases_folder}}/{{ release_id }}/cms/craft clear-caches/all"
      tags:
        - deploy

    - name: Install packages based on package.json.
      npm:
        path: "{{ releases_folder }}/{{release_id}}/buildchain"
        state: present
      tags:
        - deploy

    # change file ownership, group and mode. When specifying mode using octal numbers, first digit should always be 0.
    - file:
        path: "{{ releases_folder }}/{{release_id}}/scripts/remote_prod_build.sh"
        owner: "{{root_user}}"
        group: "{{root_user}}"
        mode: 0774
      tags:
        - deploy

    - name: Running our script for production build inside scripts folder
      shell: "{{ releases_folder }}/{{release_id}}/scripts/remote_prod_build.sh {{ releases_folder }}/{{release_id}}/buildchain"
      args:
        chdir: "{{ releases_folder }}/{{release_id}}/scripts"
      tags:
        - deploy

    - name: copy mymycms nginx config file to site-available directory
      become: yes
      become_method: sudo
      copy:
        src: "{{local_ansible_folder}}/files/staging/mymycms"
        dest: "{{staging_nginx_config_folder}}/mymycms"
        owner: "{{root_user}}"
        group: "{{root_user}}"
        mode: '0644'
      tags:
        - deploy

    - name: switch symlink from release folder to current folder
      file:
        dest: "{{ releases_folder }}/current"
        src: "{{ releases_folder }}/{{ release_id }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        state: link
        force: yes
      tags:
        - symlink
        - deploy

    - name: restarting nginx service
      systemd:
        state: restarted
        name: nginx
      tags:
        - deploy

    - name: restarting php7.3 service
      systemd:
        state: restarted
        name: php7.3-fpm
      tags:
        - deploy
```

### Expected Results

The deployment process takes forever.

### Actual Results

I want the deployment process to be finished.
