### ISSUE TITLE
How to deal with multi to multi loop?

### ISSUE THREAD

**Issue by dreampuf** [ansible/ansible#7415]
##### Issue Type:

"Feature Idea"
##### Ansible Version:

1.6.1
##### Environment:

Mac OSX 10.9.2
##### Summary:

Need a expression to deal with multi to multi relationship of variables.
##### Steps To Reproduce:

Do something like this. I don't think I could using `with_subelements` .

```
--
- hosts: all
  vars:
     USER: x1
  tasks:
    - authorized_key: user={{ USER }}
                      key="{{ lookup('file',item) }}"
      with_fileglob:
        - files/ssh_public_keys/*

    - authorized_key: user=root
                      key="{{ lookup('file',item) }}"
      with_fileglob:
        - files/ssh_public_keys/*
```
##### Expected Results:

As upside description.
##### Actual Results:

NA
