### ISSUE TITLE
Ansible freezes for a very long time when execute a telnet command

### ISSUE THREAD

**Issue by kovalev94** [ansible/ansible#74168]
### Summary

I run ansible-playbook with telnet tasks on 100 switches. I have 2 groups of switches, for each group i have different prompts. If for some reasons ansible's prompt doesn't match switches prompt it freezes for a long time(more than hour) but it should give an error after the time specified in timeout.
When i try to do it on my macbook machine with python3 interpreter it works as i expect.

### Issue Type

Bug Report

### Component Name

telnet

### Ansible Version

```console
$ ansible --version
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/lanadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Centos 7

### Steps to Reproduce

```yaml (paste below)
- name: Get Dlink info
  hosts: Dlink
  gather_facts: false
  connection: local

  tasks:
  - name: Get lldp neighbors info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
      command:
        - "disable clipaging"
        - "show ports 25-28"
        - "show lldp r 25-28 m d"
        - "enable clipaging"
    tags: neighbors

  - name: Get management settings info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
      command:
        - "disable clipaging"
        - "show ipif"
        - "show iproute"
        - "enable clipaging"
    tags: mgmt

  - name: Get vlan info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
      command:
        - "disable clipaging"
        - "show vlan"
        - "enable clipaging"
    tags: vlan

  - name: Get gateway info
    telnet:
      timeout: 15
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
      command:
        - "disable clipaging"
        - "show iproute"
        - "enable clipaging"
    tags: gateway

- name: Get Dlink des 3028 info
  hosts: Dlink-Old
  gather_facts: false
  connection: local

  tasks:
  - name: Get lldp neighbors info.
    telnet:
      login_prompt: "UserName:"
      password_prompt: "PassWord:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
        - 'UserName'
        - 'PassWord'
      command:
        - "username"
        - "password"
        - "disable clipaging"
        - "show ports 25-28"
        - "show lldp r 25-28 m d"
        - "enable clipaging"
    tags: neighbors

  - name: Get management settings info.
    telnet:
      login_prompt: "UserName:"
      password_prompt: "PassWord:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
        - 'UserName'
        - 'PassWord'
      command:
        - "username"
        - "password"
        - "disable clipaging"
        - "show ipif"
        - "show iproute"
        - "enable clipaging"
    tags: mgmt

  - name: Get vlan info.
    telnet:
      login_prompt: "UserName:"
      password_prompt: "PassWord:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
        - 'UserName'
        - 'PassWord'
      command:
        - "username"
        - "password"
        - "disable clipaging"
        - "show vlan"
        - "enable clipaging"
    tags: vlan

  - name: Get gateway info.
    telnet:
      login_prompt: "UserName:"
      password_prompt: "PassWord:"
      user: "username"
      password: "password"
      prompts:
        - '\w#'
        - 'UserName'
        - 'PassWord'
      command:
        - "username"
        - "password"
        - "disable clipaging"
        - "show iproute"
        - "enable clipaging"
    tags: gateway

- name: Get Huawei info
  hosts: Huawei:Huawei-2320
  gather_facts: false
  connection: local

  tasks:
  - name: Get lldp neighbors info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w>'
      command:
        - "screen-length 0 temporary"
        - "dis int br | inc Gigabit"
        - "dis lldp neighbor"
    tags: neighbors

  - name: Get management settings info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w>'
      command:
        - "screen-length 0 temporary"
        - "dis ip interface brief"
    tags: mgmt

  - name: Get vlan info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w>'
      command:
        - "screen-length 0 temporary"
        - "dis vlan"
    tags: vlan

  - name: Get gateway info.
    telnet:
      login_prompt: "Username:"
      password_prompt: "Password:"
      user: "username"
      password: "password"
      prompts:
        - '\w>'
      command:
        - "screen-length 0 temporary"
        - "dis ip routing-table"
    tags: gateway
```

### Expected Results

I expected to receive an error after time specified in timeout. This is how it works on my macbook machine:
```
changed: [10.222.6.82] => {
    "changed": true,
    "output": [
        "disable clipaging\n\rCommand: disable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#",
        "show iproute\n\rCommand: show iproute\n\r\n\r\n\rRouting Table\n\r\n\rIP Address/Netmask  Gateway          Interface     Cost      Protocol\n\r------------------  ---------------  ------------  --------  --------\n\r0.0.0.0/0           10.222.6.254     System        1         Default\n\r10.222.6.0/24       0.0.0.0          System        1         Local\n\r\n\rTotal Entries: 2\n\r\n\r\n\rDES-3200-28:admin#",
        "enable clipaging\n\rCommand: enable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#"
    ]
}
changed: [10.222.6.91] => {
    "changed": true,
    "output": [
        "disable clipaging\n\rCommand: disable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#",
        "show iproute\n\rCommand: show iproute\n\r\n\r\n\rRouting Table\n\r\n\rIP Address/Netmask  Gateway          Interface     Cost      Protocol\n\r------------------  ---------------  ------------  --------  --------\n\r0.0.0.0/0           10.222.6.254     System        1         Default\n\r10.222.6.0/24       0.0.0.0          System        1         Local\n\r\n\rTotal Entries: 2\n\r\n\r\n\rDES-3200-28:admin#",
        "enable clipaging\n\rCommand: enable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#"
    ]
}
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/3.2.0/libexec/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible/3.2.0/libexec/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 663, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/Cellar/ansible/3.2.0/libexec/lib/python3.9/site-packages/ansible_collections/ansible/netcommon/plugins/action/telnet.py", line 88, in run
    tn.expect(list(map(to_bytes, prompts)))
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/telnetlib.py", line 636, in expect
    self.fill_rawq()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/telnetlib.py", line 526, in fill_rawq
    buf = self.sock.recv(50)
socket.timeout: timed out
fatal: [10.222.6.3]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
META: ran handlers
META: ran handlers
```

### Actual Results

```console
Ansible freezes on a host which have other prompt that ansible expect.
changed: [10.222.6.82] => {
    "changed": true,
    "output": [
        "disable clipaging\n\rCommand: disable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#",
        "show iproute\n\rCommand: show iproute\n\r\n\r\n\rRouting Table\n\r\n\rIP Address/Netmask  Gateway          Interface     Cost      Protocol\n\r------------------  ---------------  ------------  --------  --------\n\r0.0.0.0/0           10.222.6.254     System        1         Default\n\r10.222.6.0/24       0.0.0.0          System        1         Local\n\r\n\rTotal Entries: 2\n\r\n\r\n\rDES-3200-28:admin#",
        "enable clipaging\n\rCommand: enable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#"
    ]
}
changed: [10.222.6.91] => {
    "changed": true,
    "output": [
        "disable clipaging\n\rCommand: disable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#",
        "show iproute\n\rCommand: show iproute\n\r\n\r\n\rRouting Table\n\r\n\rIP Address/Netmask  Gateway          Interface     Cost      Protocol\n\r------------------  ---------------  ------------  --------  --------\n\r0.0.0.0/0           10.222.6.254     System        1         Default\n\r10.222.6.0/24       0.0.0.0          System        1         Local\n\r\n\rTotal Entries: 2\n\r\n\r\n\rDES-3200-28:admin#",
        "enable clipaging\n\rCommand: enable clipaging\n\r\n\rSuccess.                                                          \n\r\n\rDES-3200-28:admin#"
    ]
}
<---- FREEZE
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct
