### ISSUE TITLE
Deadlock in "shell" module when stderr is not redirected (also interfere with ssh ControlPersist)

### ISSUE THREAD

**Issue by dimikot** [ansible/ansible#7417]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Ubuntu Server 12.04
##### Summary:

If a shell command of local_action does NOT redirect stderr somewhere (e.g. without 2>/dev/null), it could be executed for 2 minutes or more. The problem exists only at the first run: then, if a socket file /tmp/ssh_\* exists, everything begins to work fast.
##### Steps To Reproduce:

**0.yml:**

```
- hosts: web
  gather_facts: no
  tasks:
    - local_action: shell ssh root@localhost echo "abc"
```

**hosts:**

```
[web]
localhost
```

**ansible.cfg:**

```
[defaults]
hostfile = hosts
transport = ssh
```

**/etc/ssh_config:**

```
...
ControlPersist 120
ControlMaster auto
ControlPath /tmp/ssh_cm_socket_%r@%h:%p
```

Then run:

```
# rm -f /tmp/ssh_*; date; ansible-playbook 0.yml; date
```
##### Expected Results:

Immediate execution
##### Actual Results:

We see a significant delay (exactly 2 minutes):

```
Thu May 15 14:27:00 MSK 2014

PLAY [web] ********************************************************************

TASK: [shell ssh root@localhost echo "abc"] ***********************************
changed: [localhost]

PLAY RECAP ********************************************************************
localhost                       : ok=1    changed=1    unreachable=0    failed=0

Thu May 15 14:29:00 MSK 2014
```

Then add "2>/dev/null" at the end of "local_action: shell" command - you'll see that the problem is gone.

In both cases `ssh root@localhost echo "abc"` command works fine and throws nothing to stderr nor auth.log (Ubuntu Server 12.04).

**Comment by dimikot** [comment]
Exactly the same situation for "shell" with no "local_action":

**0.yml:**

```
- hosts: web
  gather_facts: no
  tasks:
    - shell: ssh root@localhost echo "abc"
```
