### ISSUE TITLE
password using encoding character work con centos7 but not centos 8 with same deploy

### ISSUE THREAD

**Issue by emper0r** [ansible/ansible#74188]
### Summary

Using mysql_user module to add new user into mysql database on centos 7 I can send user, password with '£' symbol in the string and can login after, same code using centos 8 can't login with the same password.

### Issue Type

Bug Report

### Component Name

mysql_user

### Ansible Version

```console
$ ansible --version

ansible 2.10.7
  config file = /home/emper0r/iac/ansible.cfg
  configured module search path = ['/home/emper0r/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/bin/python_virtualenvs/ansible-2.10.7-devops_env/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/python_virtualenvs/ansible-2.10.7-devops_env/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
```


### Configuration

```console
$ ansible-config dump --only-changed

ANSIBLE_PIPELINING(/home/emper0r/iac/ansible.cfg) = False
DEFAULT_CALLBACK_WHITELIST(/home/emper0r/iac/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/emper0r/iac/ansible.cfg) = ['/home/emper0r/iac/inventories/devel/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/emper0r/iac/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
HOST_KEY_CHECKING(/home/emper0r/iac/ansible.cfg) = False
```
```


### OS / Environment

CentOS 7: OK
CentOS 8: Not working

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```- name: Deploy MySQL xbackup Infra
  hosts: mysql_node

  tasks:
    - name: Create db user and Grant MySQl privileges
      mysql_user:
        login_host: '127.0.0.1'
        login_port: 3306
        login_user: root
        login_password: "{{ root_password }}"
        login_unix_socket: "/mysql/mysql.sock"
        name: "usertest1"
        host: 'localhost'
        password: "123abc£abc123"
        update_password: always
        priv: '*.*:SUPER,SHOW DATABASES,SELECT,CREATE,INSERT,CREATE TABLESPACE,PROCESS,RELOAD,LOCK TABLES,REPLICATION CLIENT,EVENT'
        state: present
```

### Expected Results

do login on MySQL successful using CentOS 8

### Actual Results

```console
Can't login into MySQL on CentOS 8
when I explode AnsibleZ.py I can see the string like '123abc\\u00a3abc123' 
that \\u00a3 means '£' character

that same encoding exist on CentOS 7 but there works fine.

when launch test playbook the last result hash on mysql are differents.

Maybe exist some issue connection client on mysql_user.py module when try to connect into MySQL server

both servers are Locate: en_US.UTF-8, and mysql settings utf8mb4
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct
