### ISSUE TITLE
Json keyword admin is replaced by '*****'

### ISSUE THREAD

**Issue by odd22** [ansible/ansible#74210]
### Summary

Hi,

I wrote a playbook that use OpenDaylight rest API to collect network IP/MPLS topology information. One of them, is related to Traffic Engineering (see RFC3630 e.g.) and named 'admin-group'.

With ansible 2.9.6, I got the correct json from OpenDaylight, while with a more recent version of ansible, at least 2.9.18, the json keyword 'admin-group' is automatically replaced by '*****-group' which break my processing.

I understand that this kind of sanitize is good from a security point of view, but in some case, must be disable or bypass.

I don't find in documentation or on the web any indication about this feature.

Can you tell me if it could be disable ? if yes, how ? if not, we need a mechanism to disable it.

Regards

Olivier

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version (Working version)
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

$ ansible --version (Non working version)
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
$ ansible-config dump --only-changed
(No output)
```

### OS / Environment

$ more /etc/redhat-release 
CentOS Linux release 8.3.2011

It is the awx_task docker from a clean AWX 17.1.0 installation

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  tasks:
  - name: Get Topology Graph from OpenDaylight
    uri:
      url: http://172.20.0.1:8181/restconf/operational/graph:graph-topology
      user: "admin"
      password: "admin"
      method: GET
      force_basic_auth: yes
      body_format: json
      status_code: 200
    register: result
  - debug:
      msg: "{{ result.json }}"
```

### Expected Results

Small extract of the global output with the expected json "admin-group" keyword (obtained with ansible 2.9.6):
```
...
                        {
                            "edge-attributes": {
                                "adj-sid": 57,
                                "admin-group": 1,
                                "delay": 10000,
                                "local-address": "10.194.77.176",
...
```

### Actual Results

```console
The current output with ansible 2.9.18:
...
                            "edge-attributes": {
                                "********-group": 1,
                                "adj-sid": 57,
                                "delay": 10000,
                                "local-address": "10.194.77.176",
...
Note the json keyword "admin-group" replaced by "******-group"
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct
