### ISSUE TITLE
mysql_db should register more fields

### ISSUE THREAD

**Issue by UnitedMarsupials** [ansible/ansible#74230]
### Summary

When performing a dump and load of a database -- a fairly common use-case -- it would provide for better code, if the loading (`import`) task could directly refer to the target of the earlier dumping task as its own source.
```yaml
- name: Dump current DB
  mysql_db:
    name: '{{ proddb.name }}'
    login_user: '{{ proddb.user }}'
    login_password: '{{ proddb.pwd }}'
    state: dump
    target: '{{ dumpdir }}/{{ proddb.name }}-ansible.sql'
  register: dump

- name: Create staging DB ({{ newdb.name }}) anew
  mysql_db:
    name: '{{ newdb.name }}'
    state: import
    login_user: '{{ proddb.user }}'
    login_password: '{{ proddb.pwd }}'
    target: '{{ dump.target }}'
```
In plain English the second (loading) task reads: "Load the just-created dump from whatever file-path it was, that was created by the earlier task".

Unfortunately, the "registered" variable (`dump` in the above example) has very few fields -- and the `target` is not one of them. Work-arounds are obvious, but it would've been nicer without them...

I can see, why you may hesitate from storing the credentials in the registered variable, but why not store the target-path and other "innocent" parameters (such as whether or not `quick` was on, path to MySQL's socket, and other data). Other modules register that sort of thing, which makes life easier...

### Issue Type

Feature Idea

### Component Name

mysql_db

### Additional Information

None

### Code of Conduct

I agree to follow the Ansible Code of Conduct
