### ISSUE TITLE
Parameterized Roles and Variable Weirdness

### ISSUE THREAD

**Issue by reyjrar** [ansible/ansible#74281]
### Summary

When including a role twice with different parameters, things get weird.  Variables passed to roles accessed via `include_roles` are always the same as the last instance of that role in the `roles` list. However, task names with that variable show the variable is correct during execution.

I'm not really excited about this bug. It is making me question reality. Please send help.

### Issue Type

Bug Report

### Component Name

ansible

### Ansible Version

```console
$ ansible --version
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/local/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o SendEnv=CL_USER -o ForwardAgent=yes
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/ansible-%%h-%%p-%%r
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/opt/ansible-playbooks/bin/ansible-inventory.pl']
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /home/user/.ansible/tmp/ansible-local-48907ZAPX4_
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/local/share/ansible/modules']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/clobber/ansible/roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 5
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = True
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /home/user
TRANSFORM_INVALID_GROUP_CHARS(/etc/ansible/ansible.cfg) = ignore
```

### OS / Environment

CentOS 7

### Steps to Reproduce

* playbook.yaml
```yaml (paste below)
---
- hosts: localhost
  connection: local
  roles:
    - role: foo
      vars:
        var_foo: 'first'
    - role: foo
      vars:
        var_foo: 'second'
```

* roles/bar/tasks/main.yaml
```yaml
---
# tasks file for bar
- debug:
    msg: "var_bar is {{ var_bar }}"
```

* roles/foo/tasks/main.yaml
```yaml
---
# tasks file for foo
- name: "Running for {{ var_foo }}"
  include_role:
    name: bar
  vars:
    var_bar: "{{ var_foo }}"
```

### Expected Results

```
PLAY [localhost] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Running for first] *******************************************************************************************************************

TASK [bar : debug] *************************************************************************************************************************
ok: [localhost] => {
    "msg": "var_bar is first"
}

TASK [Running for second] ******************************************************************************************************************

TASK [bar : debug] *************************************************************************************************************************
ok: [localhost] => {
    "msg": "var_bar is second"
}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual Results

```console
PLAY [localhost] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Running for first] *******************************************************************************************************************

TASK [bar : debug] *************************************************************************************************************************
ok: [localhost] => {
    "msg": "var_bar is second"
}

TASK [Running for second] ******************************************************************************************************************

TASK [bar : debug] *************************************************************************************************************************
ok: [localhost] => {
    "msg": "var_bar is second"
}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Duplicate of https://github.com/ansible/ansible/issues/73921

**Comment by reyjrar** [comment]
What I don't understand about any of this, is the variables are set correctly for *EVERY* task in the parameterized role **EXCEPT** for `include_roles` calls.

This is maddening.  How is this by design? I'm really struggling to understand the design decision that meant that the value in these two tasks could be different:

## playbook
```yaml
- hosts: localhost
  connection: local
  roles:
     - role: thing
       vars:
          var2: bob
     - role: thing
        vars:
          var2: alice
```

## Role
```yaml
- name: Install a template
  template:
     src: a_template_that_uses_var2.j2
     dest: /etc/thing

- name: "Another thing uses {{ var2 }}"
   include_role:
     name: another_thing
   vars:
      thing_var2: "{{ var2 }}"
```

In what world are we as users of the tool expect to know that **ONLY** the `include_role` will have the wrong variable?

And then by changing that playbook to:

```yaml
- hosts: localhost
  connection: local
  tasks:
     - include_role: 
          name: thing
       vars:
          var2: bob
     - include_role: 
          name: thing
        vars:
          var2: alice
```

Does what we expected the first case to do as well?  This is inherently inconsistent. I'm losing my sanity contemplating this.
