### ISSUE TITLE
setfacl: not found while trying to use ansible.builtin.su in Solaris 11.4 SRU 30

### ISSUE THREAD

**Issue by sartigas** [ansible/ansible#74282]
### Summary

I tried to use module **ansible.builtin.su** in a playbook to execute some commands with non-privileged account but failed to do so because playbook execution fails with **setfacl: not found** error. Digging in Oracle Solaris documentation, I found setfacl command has been removed from version 11.4.

Here:

https://docs.oracle.com/cd/E88353_01/html/E37839/setfacl-1.html

setfacl(1)
Name
getfacl, setfacl - display or modify the Access Control List (ACL) for files

Description
In Oracle Solaris 11.3 and earlier releases, the getfacl and setfacl commands were used to view and change POSIX-draft Access Control Lists (ACLs) on UFS filesystems.

**These commands are no longer included in Oracle Solaris 11.4 and later releases. Instead of getfacl, you can use the -v or -V options to the ls(1) command to list an ACL. Instead of setfacl, you can use the -A option to the chmod(1) command to change an ACL**.

### Issue Type

Bug Report

### Component Name

ansible.builtin.su

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 20
```

### OS / Environment

Source OS: Ubuntu 20.04.2 LTS (Focal Fossa) on top of WSL.
Target OS: Oracle Solaris 11.4.30.0.85.3

### Steps to Reproduce

```yaml (paste below)
---
- hosts: devserver
  gather_facts: false
  vars:
    ansible_su_exe: su
    ansible_su_user: app_id

  become: yes
  become_method: su
  tasks:
    - name: Test
      ansible.builtin.command:
        argv:
          -whoami
```

### Expected Results

Run the command as non-priviliged account

### Actual Results

```console
<hostname> (127, b'', b'/bin/sh: setfacl: not found [No such file of directory]\n')
<hostname> Failed to connect to the host via ssh: /bin/sh: setfacl: not found [Not such file or directory]
```

### Code of Conduct

I agree to follow the Ansible Code of Conduct
