### ISSUE TITLE
Create missing mountpoint without permissions?

### ISSUE THREAD

**Issue by c0xc** [ansible/ansible#74345]
### Summary

In some environments, it's common practice to create mountpoints without read/write permissions to prevent admins and services from using them as local directories, filling up the local disk. With Ansible's mount module, a missing mountpoint is created with the default umask instead, so it may be mistaken for a mounted share if the mount failed. Is it possible to have missing mountpoints created without permissions?

### Issue Type

Feature Idea

### Component Name

mount

### Additional Information

Manual approach:
```
mkdir /mnt/xyz && chmod 0 /mnt/xyz
mount /mnt/xyz
```

Ansible workaround:
```
- name: Check for /mnt/xyz
  stat:
    path: /mnt/xyz
  register: st_mount_xyz
  ignore_errors: "yes"

- name: Create /mnt/xyz
  file:
    path: /mnt/xyz
    state: directory
    owner: root
    group: root
    mode: 0000
  when:
    - st_mount_xyz.stat is defined
    - st_mount_xyz.stat.exists == false

- name: Mount /mnt/xyz
  mount:
    src: "filer:/data/xyz"
    path: /mnt/xyz
    state: mounted
    fstype: nfs

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
