### ISSUE TITLE
Authentication or permission failure when gathering facts on group and ansible_user: root before normal user

### ISSUE THREAD

**Issue by jeee** [ansible/ansible#74352]
### Summary

When the host that needs "ansible_user: root" is not on the last entry it fails. (So if you swap host2 and host3 it works)

host.yml
```
all:
  children:
     test:
      hosts:
        host1:
        # It only works if this host with the root user entry is the last entry
        host2:
          ansible_user: root
        host3:
```

playbook
```
---
- hosts: test
  become: true

  tasks:
  - name: set host group
    set_fact: 
        mygroup: "{% set output = [] %}\
  {% if 'test' in groups and inventory_hostname in groups['test'] %}\
  {% for host in groups['test'] if host != inventory_hostname %}\
              {{ output.append(host) }}\
          {% endfor %}\
  {% endif %}\
  {{ output }}"


  - name: gather basic facts from other servers
    setup:
    delegate_to: "{{item}}"
    delegate_facts: True
    loop: "{{ mygroup }}"
```

### Issue Type

Bug Report

### Component Name

-

### Ansible Version

```console
$ ansible --version

ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

see summary

### Expected Results

no difference with different host orders

### Actual Results

```console
fails when root user is not as last entry
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
