### ISSUE TITLE
firewalld task is not idempotent for adding ports

### ISSUE THREAD

**Issue by okapia** [ansible/ansible#74363]
### Summary

I'm using the `firewalld:` task with the `port:` option. The first time this is run on a host, it works fine. However on any later or subsequent runs, I get an error: `ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: ALREADY_ENABLED: 'xxxxx:tcp' already in 'public' Permanent and Non-Permanent(immediate) operation`

This violates idempotency which is really the whole point of ansible.

Aside from `port:`, I'm using `permanent: yes`, `immediate: yes`, `state: enabled`, and `zone: public`.

### Issue Type

Bug Report

### Component Name

ansible.posix.firewalld

### Ansible Version

```console
$ ansible --version
ansible 2.10.8

python version = 3.6.8 (default, Mar  9 2021, 15:28:46) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5.0.1)]
```

### Configuration

```console
$ ansible-config dump --only-changed

Problem verified from a plain pip install ansible in a venv and just the minimal task.
```

### OS / Environment

Oracle Linux 8.3 which is a RHEL 8 clone.

### Steps to Reproduce

```yaml (paste below)
- name: Enable ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
    zone: public
  loop: [ whatever/tcp ]
  become: yes
```
And run this *TWICE*

### Expected Results

Expected results to be changed: false, failed: false

### Actual Results

```console
failed: true
"msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: ALREADY_ENABLED: 'myport:tcp' already in 'public' Permanent and Non-Permanent(immediate) operation"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
