### ISSUE TITLE
lineinfile not idempotent when single line is split to multiple lines in yaml

### ISSUE THREAD

**Issue by markom84** [ansible/ansible#74365]
### Summary

Lineinfile module is not idempotent when line to be added is split into multiple lines in yaml file.
```
line: > 
     This is line
     to be added once. 
```
is behaving differently than: 
```
line: This is line to be added once.
```

When multiline option **>** is used, line is added to text every time playbook runs.

### Issue Type

Bug Report

### Component Name

lineinfile

### Ansible Version

```console
$ ansible --version
ansible 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/locodog/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

ansible controller: Ubuntu 18.04
target: Ubuntu 20.04

### Steps to Reproduce

Create testfile.txt with content:

This is unique line.

Run following playbook against it, line will be added every time playbook runs. 

```yaml (paste below)
---
- hosts: all
  gather_facts: no
  user: ubuntu
 
  tasks:
    - name: Add line after
      lineinfile:
       path: /home/ubuntu/testfile.txt
       insertafter: 'unique'
       line: > 
         This is line
         to be added once.


```

### Expected Results

**This is line to be added once.** should be added only once, no matter how many time playbook runs.

### Actual Results

```console
"This is line to be added once." Is inserted into file every time playbook runs.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
