### ISSUE TITLE
High memory consumption when adding items to a list

### ISSUE THREAD

**Issue by trsqr** [ansible/ansible#74379]
### Summary

When I try to add a larger number of items (1800) into a list in a loop the memory consumption of Ansible goes through the roof. The processing gradually becomes very slow and the memory usage of ansible-playbook is around 5 gigabytes at worst point. This seems to be completely out of proportion considering that the whole 1800 lines of text is approximately 43 kilobytes.

Logging the memory usage of Ansible with:
`while true; do date >> /tmp/memusage.txt; ps -C ansible-playboo -o pid=,%mem=,vsz >> /tmp/memusage.txt; sleep 1; done`
Output is attached as memusage.txt.

The playbook and the references lines.txt file are attached.

### Issue Type

Bug Report

### Component Name

loop

### Ansible Version

```console
$ ansible --version
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ollsal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Aug  4 2020, 11:16:42) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
<no output>
```

### OS / Environment

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: "Read a file into variable"
      shell: cat lines.txt
      register: cmdOutput

    - name: "Extract IDs"
      set_fact:
        id_list: "{{ id_list|default([]) +
                          [{
                            'line': item,
                          }]
                        }}"
      loop: "{{ cmdOutput.stdout_lines }}"

    - debug:
        msg: "{{ id_list }}"

```

### Expected Results

I expected memory usage not to grow significantly while running the loop.

### Actual Results

```console
At the worst point of time the memory usage was above 5 gigabytes:

              VSZ
18841  0.2 167324
18879 14.8 5306612
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
