### ISSUE TITLE
vmware_guest_snapshot and datacenter value

### ISSUE THREAD

**Issue by impsik** [ansible/ansible#74412]
### Summary

I use vmware_guest_snapshot to make snapshots before ansible does dist-upgrade.
With ansible 2.10 i found out that in vmware_guest_snapshot i had "datacenter" value completely wrong.
But it worked and works just with ansible 2.9.18 (Installed via yum install) 
I'm using at the moment 2.9.18 and i defined "datacenter": "random" ( we don't have datacenter named "random") and still vmware_guest_snapshot makes snapshot.
According to documentation then datacenter string is required in ansible 2.9 and latest.
Why is that datacenter string required if that can be anything?
From vmware_guest_find for example datacenter is deprecated in 2.5, will be removed in 2.9 release.

### Issue Type

Bug Report

### Component Name

vmware_guest_snapshot

### Ansible Version

```console
$ ansible --version
ansible 2.9.18
  config file = /home/ansible/.ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
COMMAND_WARNINGS(/home/ansible/.ansible.cfg) = False
DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = [u'/home/ansible/ansible_playbooks/ansible_hosts']
DEFAULT_LOG_PATH(/home/ansible/.ansible.cfg) = /home/ansible/ansible.log
DEFAULT_STRATEGY(/home/ansible/.ansible.cfg) = debug
DEPRECATION_WARNINGS(/home/ansible/.ansible.cfg) = False
ENABLE_TASK_DEBUGGER(/home/ansible/.ansible.cfg) = True
HOST_KEY_CHECKING(/home/ansible/.ansible.cfg) = False
```

### OS / Environment

Centos7

### Steps to Reproduce

```yaml (paste below)
  - name: "Create snapshot"
    vmware_guest_snapshot:
      hostname: "{{ vmware }}"
      validate_certs: no
      username: "{{ username }}"
      password: "{{ password }}"
      datacenter: random
      folder: "{{ vm_folder}}['folders'] }}"
      name: "myhost.ee"
      state: present
      quiesce: True
      snapshot_name: "myhost-snapshot-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
      description: "Desc here"
    delegate_to: localhost
    ignore_errors: no
```

### Expected Results

If datacenter string can be anything then remove that requirement

### Actual Results

```console
changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "datacenter": "random", 
            "description": "Desc here", 
            "folder": "{u'folders': [u'/DC/vm'], 'failed': False, 'changed': False}['folders'] }}", 
            "hostname": "removed", 
            "memory_dump": false, 
            "moid": null, 
            "name": "myhost", 
            "name_match": "first", 
            "new_description": null, 
            "new_snapshot_name": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "proxy_host": null, 
            "proxy_port": null, 
            "quiesce": true, 
            "remove_children": false, 
            "snapshot_name": "myhost-snapshot-2021-04-25-14:34:54", 
            "state": "present", 
            "use_instance_uuid": false, 
            "username": "ansible", 
            "uuid": null, 
            "validate_certs": false
        }
    },
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
