### ISSUE TITLE
ansible.builtin.package_facts add the list of all packages available to install

### ISSUE THREAD

**Issue by maximmasiutin** [ansible/ansible#74428]
### Summary

It is possible to get the list of all installed packages by `ansible.builtin.package_facts`, but not the list of all available to install packages.

If a package is not available to install, installing the package via the `ansible.builtin.package` gives an error. Ensuring that the packages is not installed also gives an error. It would have been beneficial to first test whether the package is available, before trying to install it.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.package_facts module

### Additional Information

Currently, it is possible to write the code:

```
    - name: "Remove the autofs package"
      ansible.builtin.package:
        name: autofs
        state: absent
```

However, this code fails when the package is not available. It would have been beneficial to have a way to test the availability of this package first.

```
    - name: "Get available package information"
      package_facts:
        need_package_details: yes
        all_available: yes

    - name: "Remove the autofs package"
      ansible.builtin.package:
        name: autofs
        state: absent
      when: "'autofs' in ansible_facts.available_packages"
```

Another example:

```
    - name: "Get available package information"
      package_facts:
        need_package_details: yes
        all_available: yes

    - name: "Configure the NTP protocol for the systemd-timesyncd"
      block:
        - name: "Remove the 'Chrony' NTP client"
          ansible.builtin.package:
            name: chrony
            state: absent
          when: "'chrony' in ansible_facts.available_packages"

        - name: "Remove the 'ntp' NTP client"
          ansible.builtin.package:
            name: ntp
            state: absent
          when: "'ntp' in ansible_facts.available_packages"

        - name: "Install the systemd-timesyncd NTP client"
          ansible.builtin.package:
            name: systemd-timesyncd
            state: present

        # etc.... configure the systemd-timesyncd 

      when: "'systemd-timesyncd' in ansible_facts.available_packages"
```

Relevant files:
lib/ansible/modules/package_facts.py 
lib/ansible/module_utils/facts/packages.py

@matburt , @bcoca , @maxamillion - please review.

Fixed by https://github.com/ansible/ansible/pull/74411

This option is helpful to check whether a package is available. Such a check may be needed to prevent an error when different packages exist in various Linux builds. Besides that, I can easily choose different installation and configuration paths depending on the availability of particular modules. For example, I have a playbook for Ubuntu, CentOS, Alpine and Gentoo, and I need to configure network time synchronization. I may avoid checking for particular OS or version with the proposed feature. I would instead check for specific NTP client packages. If I have `systemd-timesyncd`, I install and configure it and uninstall other NTP packages, if any. Otherwise, I install and configure `chrony`, and, if it is also not available, I install and configure the client from the `ntp` package.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
