### ISSUE TITLE
dnf & yum behave unexpectedly when updating to a specific version

### ISSUE THREAD

**Issue by d5han** [ansible/ansible#74503]
### Summary

When installing packages with a specific version using `yum` or `dnf`, they are not updated to the specific version if an earlier version is installed.

Workaround:

```yaml 
- name: install package
  become: yes
  dnf:
    name: "{{ package }}-{{ version }}"
    allow_downgrade: yes
    state: present
```

`allow_downgrade` is needed to also *upgrade* the package if the version is specified

### Issue Type

Bug Report

### Component Name

dnf, yum

### Ansible Version

```console
$ ansible --version
ansible 2.9.15
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

management node: Ubuntu 20.04.2 LTS
inventory node: Red Hat Enterprise Linux 8.3 (Ootpa)

### Steps to Reproduce

```
# dnf list docker-ce
Installed Packages
docker-ce.x86_64         3:19.03.13-3.el8          @docker-ce-stable
Available Packages
docker-ce.x86_64         3:20.10.6-3.el8            docker-ce-stable
```

And the following task reports "ok" and does not update the version:
```yaml 
- name: install docker
  become: yes
  dnf:
    name: docker-ce-20.10.6-3
    state: present
```

This task also reports "ok" and does not update the version:
```yaml 
- name: install docker
  become: yes
  dnf:
    name: docker-ce-20.10.6-3
    state: latest
```

Specifying latest *without* a version does update the package.

`# dnf update docker-ce` does try to update the package to 20.10.6-3.

This also applies to `yum`

### Expected Results

Package is updated to the version listed in the `name:` when `state: present`

### Actual Results

The specified package is not updated to the version specified, and ansible reports that the task did not need to change anything.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
