### ISSUE TITLE
ansible.builtin.yum: No match for argument: %s

### ISSUE THREAD

**Issue by markfaine** [ansible/ansible#74504]
### Summary

When attempting to install local packages using ansible.builtin.yum on RHEL 8 target I get an error message "No Match for argument"  It seems to occur inconsistently.  I  have seen it work before but I can't say that it is due to anything that I changed and it fails more often than it succeeds.  It may possibly be related to the yum cache but I can't say for sure.

I have tried multiple different ways to do it within the parameters available but nothing seems to work.  If I login and install the rpm directly from the command line there is no issue.

### Issue Type

Bug Report

### Component Name

yum 

### Ansible Version

```console
ansible 2.10.5
  config file = /home/mfaine/ansible/ansible.cfg
  configured module search path = ['/home/mfaine/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mfaine/ansible/virtualenv/lib/python3.8/site-packages/ansible
  executable location = /home/mfaine/ansible/virtualenv/bin/ansible
  python version = 3.8.3 (default, Sep 22 2020, 14:37:11) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Configuration

```console
ANSIBLE_PIPELINING(/home/mfaine/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(env: ANSIBLE_SSH_ARGS) = -F /home/mfaine/ansible/config
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATHS) = ['/home/mfaine/development/collections', '/home/mfaine/ansible
COLOR_DEBUG(env: ANSIBLE_COLOR_DEBUG) = white
DEFAULT_ACTION_PLUGIN_PATH(/home/mfaine/ansible/ansible.cfg) = ['/home/mfaine/ansible/virtualenv/lib/python3.8/sit
DEFAULT_CALLBACK_PLUGIN_PATH(/home/mfaine/ansible/ansible.cfg) = ['/home/mfaine/ansible/virtualenv/lib/python3.8/s
DEFAULT_FORKS(/home/mfaine/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/mfaine/ansible/ansible.cfg) = ['/home/mfaine/ansible/inventories/production/inventory.yml'
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /var/log/ansible/mfaine/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/mfaine/ansible/ansible.cfg) = ['/home/mfaine/ansible/virtualenv/lib/python3.8/sit
DEFAULT_MANAGED_STR(/home/mfaine/ansible/ansible.cfg) = This file is managed by Ansible, all changes will be lost.
DEFAULT_REMOTE_USER(/home/mfaine/ansible/ansible.cfg) = bean
DEFAULT_ROLES_PATH(/home/mfaine/ansible/ansible.cfg) = ['/home/mfaine/ansible/roles']
DEFAULT_SCP_IF_SSH(env: ANSIBLE_SCP_IF_SSH) = True
DEFAULT_TRANSPORT(/home/mfaine/ansible/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/home/mfaine/ansible/ansible.cfg) = /home/mfaine/ansible/.vault
HOST_KEY_CHECKING(/home/mfaine/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/mfaine/ansible/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/home/mfaine/ansible/ansible.cfg) = False
```

### OS / Environment

Linux 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Mar 25 14:36:04 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux release 8.3 (Ootpa)

### Steps to Reproduce

```
# With a static list defined in host vars
# Installing one at a time, or as csv list
- name: Install bacula 5 rpms (RHEL8)
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ bacula_rpms }}"
  become: true
  vars:
    bacula_rpms:
      - /tmp/bacula-libs-5.2.13-23.1.el7.x86_64.rpm
      - /tmp/bacula-common-5.2.13-23.1.el7.x86_64.rpm
      - /tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm


# With the result of a find operation, same result
- name: Find bacula 5 rpms in /tmp
  find:
    paths: /tmp
    patterns: 'bacula*.rpm'
  register: bacula_rpms
  become: true
- name: Install bacula 5 rpms (RHEL8)
    ansible.builtin.yum:
      name: "{{ bacula_rpms.files | map(attribute='path') | list |  join(',') }}"
      state: present
  become: true
```

### Expected Results

The packages are installed.

### Actual Results

```console
Using module file /home/mfaine/ansible/virtualenv/lib/python3.8/site-packages/ansible/modules/dnf.py
Pipelining is enabled.
<myserver.host.domain> ESTABLISH SSH CONNECTION FOR USER: bean
<myserver.host.domain> SSH: EXEC ssh -F /home/mfaine/ansible/config -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="bean"' -o ConnectTimeout=10 -o 'ProxyCommand=ssh -qxt -R 3128:127.0.0.1:3128 -W %h:%p basecamp.nisn.nasa.gov' myserver.host.domain '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-pylgtdcotvmmwhvvsmzkrdoncgncuubt ; http_proxy=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128 /usr/libexec/platform-python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<myserver.host.domain> (1, b'\n{"results": [], "rc": 1, "failed": true, "msg": "Error occured attempting remote rpm operation: No match for argument: %s: /tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm", "exception": "  File \\"/tmp/ansible_ansible.legacy.dnf_payload_chbe2yel/ansible_ansible.legacy.dnf_payload.zip/ansible/modules/dnf.py\\", line 864, in _install_remote_rpms\\n  File \\"/usr/lib/python3.6/site-packages/dnf/base.py\\", line 1947, in package_install\\n    raise dnf.exceptions.PackageNotFoundError(_(\'No match for argument: %s\'), pkg.location)\\n", "invocation": {"module_args": {"name": ["/tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm"], "update_cache": true, "state": "present", "allow_downgrade": false, "autoremove": false, "bugfix": false, "disable_gpg_check": false, "disable_plugin": [], "disablerepo": [], "download_only": false, "enable_plugin": [], "enablerepo": [], "exclude": [], "installroot": "/", "install_repoquery": true, "install_weak_deps": true, "security": false, "skip_broken": false, "update_only": false, "validate_certs": true, "lock_timeout": 30, "allowerasing": false, "conf_file": null, "disable_excludes": null, "download_dir": null, "list": null, "releasever": null}}}\n', b'')
<myserver.host.domain> Failed to connect to the host via ssh:
The full traceback is:
  File "/tmp/ansible_ansible.legacy.dnf_payload_chbe2yel/ansible_ansible.legacy.dnf_payload.zip/ansible/modules/dnf.py", line 864, in _install_remote_rpms
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 1947, in package_install
    raise dnf.exceptions.PackageNotFoundError(_('No match for argument: %s'), pkg.location)
failed: [myserver.host.domain] (item=/tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "allowerasing": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "/tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": true,
            "update_only": false,
            "validate_certs": true
        }
    },
    "item": "/tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm",
    "msg": "Error occured attempting remote rpm operation: No match for argument: %s: /tmp/bacula-client-5.2.13-23.1.el7.x86_64.rpm",
    "rc": 1,
    "results": []
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
