### ISSUE TITLE
Installation of 'dnssec-tools' fails on Ubuntu 14.04 using apt

### ISSUE THREAD

**Issue by cooperaj** [ansible/ansible#7452]
##### Issue Type:

Bug report
##### Ansible Version:

Ansible 1.6.1
##### Environment:

Running on OSX 10.9.2. Connecting to an Ubuntu 14.04 server
##### Summary:

Running a task such as 

```
- name: bind | Install packages/s
  apt: pkg={{ item }} state=installed
  with_items:
    - dnssec-tools
```

Will cause the ansible process to hang. Sivel on IRC ran a strace on the apt process and found it was hanging on the 

```
'Processing triggers for ureadahead (0.100.0-16) ...'
```

part. Running the command 

```
apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" install dnssec-tools
```

on the server causes no issues and the process completes successfully.
##### Steps To Reproduce:

Install dnssec-tools using a task like

```
- name: bind | Install packages/s
  apt: pkg={{ item }} state=installed
  with_items:
    - dnssec-tools
```
##### Expected Results:

Dnssec-tools should be installed successfully and the ansbile task should continue to run.
##### Actual Results:

The process hangs and completes no further tasks. The packages are however installed just fine if you SSH in and look at the server yourself.
