### ISSUE TITLE
set_fact documentation should provide an example with dynamic variable assignment

### ISSUE THREAD

**Issue by Sylvain303** [ansible/ansible#74537]
### Summary

**Some context:**

To avoid code duplication I sometime regroup common loopable task in a `task.yml`

One way to achieve a return value from a `task.yaml` can be to embed a the value assignment inside the task

```yaml
- set_fact:
  "{{return_variable_name}}": "{{value_to_return}}"
```

But this feature is not documented.

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html

A full working example, is pasted in the last form.

### Issue Type

Documentation Report

### Component Name

`set_fact.py`

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = /opt/w/infrastructure/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible_azure/lib/python3.6/site-packages/ansible
  executable location = /root/ansible_azure/bin/ansible
  python version = 3.6.10 (default, Jun  9 2020, 18:36:16) [GCC 8.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/opt/w/infrastructure/ansible/ansible.cfg) = ['/opt/w/infrastructure/ansible/hosts']
DEFAULT_ROLES_PATH(/opt/w/infrastructure/ansible/ansible.cfg) = ['/opt/w/infrastructure/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/opt/w/infrastructure/ansible/ansible.cfg) = debug
INTERPRETER_PYTHON(/opt/w/infrastructure/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

debian buster

### Additional Information

```yaml
---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: set dynamic variables name
      set_fact:
        "{{ item.name }}": "{{ item.val }}"
      when: item.name not in vars           # this is optional. prevents overwriting vars
      loop:
        - { name: test, val: myalue }
        - { name: notest, val: novalue }

    - debug:
        var: test

    - debug:
        var: notest
```

play:

```
ansible-playbook examples/set_fact_dynamic_vars.yml 

PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [set dynamic variables name] ***********************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'test', 'val': 'myalue'})
ok: [localhost] => (item={'name': 'notest', 'val': 'novalue'})

TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "test": "myalue"
}

TASK [debug] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "notest": "novalue"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
