### ISSUE TITLE
Merging of variables

### ISSUE THREAD

**Issue by jeee** [ansible/ansible#74572]
### Summary

I have all my configuration in dictionaries which makes it much more flexible and readable. 
Have no idea how I can do this without writing it per entry ( then configuration really becomes messy).

### Issue Type

Feature Idea

### Component Name

inventory

### Additional Information

```
hosts:
  1.1.1.1:
     testnet:
        port: 7778
vars:
   mainnet:
      port: 6666
      version: v1
   testnet:
       port: 7777
       version: v1.1
   devnet:
       port: 8888
       version: v2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
