### ISSUE TITLE
sudo to oracle user in AIX. (setfacl) not avaialble 

### ISSUE THREAD

**Issue by Maheshdamu** [ansible/ansible#74598]
### Summary

Hi 

i have   play book to apply a patch using Ansible from linux to Linux server. but when i try to appy a patch on AIX server. getting an issue related to setfacl.  becauase, i do ssh as oraoem  and sudo to oracle users. 

below are error message. 

```
<dmsdbp2> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="oraoem"' -o ConnectTimeout=10 -o ControlPath=/home/oracle/.ansible/cp/e1c66270a8 dmsdbp2 '/usr/bin/ksh -c '"'"'setfacl -m u:oracle:r-x /tmp/ansible-tmp-1620159177.47-435-216066205032169/ /tmp/ansible-tmp-1620159177.47-435-216066205032169/AnsiballZ_command.py && sleep 0'"'"''
<dmsdbp2> (127, '', '/usr/bin/ksh: setfacl:  not found\n')
<dmsdbp2> Failed to connect to the host via ssh: /usr/bin/ksh: setfacl:  not found
<dmsdbp2> ESTABLISH SSH CONNECTION FOR USER: oraoem
<dmsdbp2> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="oraoem"' -o ConnectTimeout=10 -o ControlPath=/home/oracle/.ansible/cp/e1c66270a8 dmsdbp2 '/usr/bin/ksh -c '"'"'chmod u+x /tmp/ansible-tmp-1620159177.47-435-216066205032169/ /tmp/ansible-tmp-1620159177.47-435-216066205032169/AnsiballZ_command.py && sleep 0'"'"''
<dmsdbp2> (0, '', '')
<dmsdbp2> ESTABLISH SSH CONNECTION FOR USER: oraoem
<dmsdbp2> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="oraoem"' -o ConnectTimeout=10 -o ControlPath=/home/oracle/.ansible/cp/e1c66270a8 dmsdbp2 '/usr/bin/ksh -c '"'"'chown oracle /tmp/ansible-tmp-1620159177.47-435-216066205032169/ /tmp/ansible-tmp-1620159177.47-435-216066205032169/AnsiballZ_command.py && sleep 0'"'"''
<dmsdbp2> (1, '', 'chown: /tmp/ansible-tmp-1620159177.47-435-216066205032169/: Not owner\nchown: 
```

### Issue Type

Bug Report

### Component Name

`lib/ansible/plugins/action/__init__.py`

### Ansible Version

```console
$ ansible --version

ansible 2.9.19
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/oracle/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Configuration

```console
$ ansible-config dump --only-changed

ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_FLAGS(/etc/ansible/ansible.cfg) = su
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /usr/bin/ksh
DEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /tmp/ansible/ansible-local-30667f8zQp8
```

### OS / Environment

source;: 3.10.0-1160.24.1.el7.x86_64 #1  
target:  IBM AIX 7.2

### Steps to Reproduce

```yaml (paste below)

- name: check the user after sudo
  shell: whoami
  become: yes
  become_exe: "sudo su  - "
  become_flags: " "
  become_method: su
  become_user: oracle
  shell: whoami
  register: use1r

- debug: var=use1r



### Expected Results

sudo su - oracle without any errors from oraoem user after ssh. 

### Actual Results

```console
<dbserver> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="oraoem"' -o ConnectTimeout=10 -o ControlPath=/home/oracle/.ansible/cp/e1c66270a8 dbserver '/usr/bin/ksh -c '"'"'setfacl -m u:oracle:r-x /tmp/ansible-tmp-1620159177.47-435-216066205032169/ /tmp/ansible-tmp-1620159177.47-435-216066205032169/AnsiballZ_command.py && sleep 0'"'"''
<dbserver> (127, '', '/usr/bin/ksh: setfacl:  not found\n')
<dbserver> Failed to connect to the host via ssh: /usr/bin/ksh: setfacl:  not found
<dbserver> ESTABLISH SSH CONNECTION FOR USER: oraoem
<dbserver> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="oraoem"' -o ConnectTimeout=10 -o ControlPath=/home/oracle/.ansible/cp/e1c66270a8 dbserver '/usr/bin/ksh -c '"'"'chmod u+x /tmp/ansible-tmp-1620159177.47-435-216066205032169/ /tmp/ansible-tmp-1620159177.47-435-216066205032169/AnsiballZ_command.py && sleep 0'"'"''
<dbserver> (0, '', '')
<dbserver> ESTABLISH SSH CONNECTION FOR USER: oraoem
<dbserver> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="oraoem"' -o ConnectTimeout=10 -o ControlPath=/home/oracle/.ansible/cp/e1c66270a8 dbserver '/usr/bin/ksh -c '"'"'chown oracle /tmp/ansible-tmp-1620159177.47-435-216066205032169/ /tmp/ansible-tmp-1620159177.47-435-216066205032169/AnsiballZ_command.py && sleep 0'"'"''
<dbserver> (1, '', 'chown: /tmp/ansible-tmp-1620159177.47-435-216066205032169/: Not owner\nchown:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
