### ISSUE TITLE
python script use streamHandler will send log to stderr pipe

### ISSUE THREAD

**Issue by dayiguizhen** [ansible/ansible#74614]
### Summary

I use ansible-playbook `command` exec python script and register result as `logger_info`.
Then I want get python result  from logger_info.stdout but it is in logger_info.stderr.

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version

ansible 2.10.6
  config file = None
  configured module search path = ['/home/dayiguizhen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```


### Configuration

```console
$ ansible-config dump --only-changed
```


### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

playbook.yml
```
---
- hosts: all                                                                                                                                                                                                                                                                 
  remote_user: root

  tasks:
    - name: get info from python script logger
      command: python3 test.py
      ignore_errors: no
      register: logger_info
 
    - when: "'test' in logger_info.stdout"
      shell: echo "logger_info.stdout"
 
    - when: "'test' not in logger_info.stdout"
      fail:
        msg: "{{ logger_info.stdout }}"
```



test.py
```
#!/usr/bin/python3
import sys
import logging
from logging.config import dictConfig

logging_config = {
    'version': 1,
    'handlers': {
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'level': 'DEBUG',
            'handlers': ['console'],
        }
    }
}
dictConfig(logging_config)
logger = logging.getLogger()
logger.info("test")
```

### Expected Results

```
TASK [get info from python script logger] ********************************************************************************************
changed: [10.9.49.123] => {"changed": true, "cmd": ["python3", "test.py"], "delta": "0:00:00.046378", "end": "2021-05-07 15:01:05.549756", "rc": 0, "start": "2021-05-07 15:01:05.503378", "stderr": "", "stderr_lines": [], "stdout": "test", "stdout_lines": ["test"]}
```

### Actual Results

```console
TASK [get info from python script logger] ********************************************************************************************
changed: [10.9.49.123] => {"changed": true, "cmd": ["python3", "test.py"], "delta": "0:00:00.046378", "end": "2021-05-07 15:01:05.549756", "rc": 0, "start": "2021-05-07 15:01:05.503378", "stderr": "test", "stderr_lines": ["test"], "stdout": "", "stdout_lines": []}
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
