### ISSUE TITLE
Add mode to cron module

### ISSUE THREAD

**Issue by lonix1** [ansible/ansible#74677]
### Summary

The `cron` module creates cron job files with mode `0644`.

I have cron jobs invoked by `run-parts` (exactly how ubuntu does it for "daily", "weekly", etc.) But `run-parts` only runs executable cron jobs.

Please consider adding an optional `mode` option, so I can set `0744` for the cron job file? If unset it should default to `0644` for backwards compatibility.

### Issue Type

Feature Idea

### Component Name

cron

### Additional Information

```yaml (paste below)
- name: create cron job that is run by run-parts
  become: true
  cron:
    job: "..."
    user: root
    cron_file: /etc/cron-custom/my-cron-job"
    mode: '0744'                                  # <----- this
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
