### ISSUE TITLE
jinja2_native broken with jinja 3.0.0 in ansible 2.9.21

### ISSUE THREAD

**Issue by PikachuEXE** [ansible/ansible#74725]
### Summary

I am using ansible 2.9.21
[jinja has recently made a release `3.0.0`](https://github.com/pallets/jinja/releases/tag/3.0.0)
A warning message would be shown when running a playbook
I have `jinja2_native = True` in my project's `ansible.cfg`

Message:
```
[WARNING]: jinja2_native requires Jinja 2.10 and above. Version detected: 3.0.0. Falling back to default.
```

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
[WARNING]: jinja2_native requires Jinja 2.10 and above. Version detected: 3.0.0. Falling back to default.
ansible 2.9.21
  config file = /Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg
  configured module search path = ['/Users/pikachuexe/projects/spacious/spacious-rails/ansible/library']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Configuration

```console
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = ['/Users/pikachuexe/projects/spacious/spacious-rails/ansible/collections']
DEFAULT_HOST_LIST(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = ['/Users/pikachuexe/projects/spacious/spacious-rails/ansible/inventories/localhost']
DEFAULT_JINJA2_NATIVE(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = True
DEFAULT_MODULE_PATH(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = ['/Users/pikachuexe/projects/spacious/spacious-rails/ansible/library']
DEFAULT_ROLES_PATH(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = ['/Users/pikachuexe/projects/spacious/spacious-rails/ansible/roles']
DEFAULT_TIMEOUT(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = 30
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = False
INTERPRETER_PYTHON(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = auto
RETRY_FILES_ENABLED(/Users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg) = False
```

### OS / Environment

MacOS 10.15.7

### Steps to Reproduce

Modified from https://github.com/ansible/ansible/pull/32738/files
```yaml (paste below)
- name: Test jinja2 native types
  hosts: localhost
  gather_facts: no
  vars:
    i_one: 1
    i_two: 2
    i_three: 3
    s_one: "1"
    s_two: "2"
    s_three: "3"
    dict_one:
      foo: bar
      baz: bang
    dict_two:
      bar: foo
      foobar: barfoo
    list_one:
      - one
      - two
    list_two:
      - three
      - four
    list_ints:
      - 4
      - 2
    list_one_int:
      - 1
    b_true: True
    b_false: False
    s_true: "True"
    s_false: "False"
  tasks:
    - set_fact:
        is_native: true

    - block:
        - assert:
            that:
              - 'i_one|type_debug == "int"'
              - 's_one|type_debug == "AnsibleUnicode"'
              - 'dict_one|type_debug == "dict"'
              - 'dict_one is mapping'
              - 'list_one|type_debug == "list"'
              - 'b_true|type_debug == "bool"'
              - 's_true|type_debug == "AnsibleUnicode"'

        - set_fact:
            a_list: "{{[i_one, s_two]}}"

        - assert:
            that:
              - 'a_list|type_debug == "list"'
              - 'a_list[0] == 1'
              - 'a_list[0]|type_debug == "int"'
              - 'a_list[1] == "2"'
              - 'a_list[1]|type_debug == "AnsibleUnicode"'
      when: is_native
```

### Expected Results

```
PLAY [Test jinja2 native types] **********************************************************************************************************************************************************************************************************************************************
 [started TASK: make sure jinja is the right version on localhost]

TASK [make sure jinja is the right version] **********************************************************************************************************************************************************************************************************************************
ok: [localhost]
 [started TASK: assert on localhost]

TASK [assert] ****************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
 [started TASK: set_fact on localhost]

TASK [set_fact] **************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
 [started TASK: assert on localhost]

TASK [assert] ****************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
```

### Actual Results

```console
PLAY [Test jinja2 native types] **********************************************************************************************************************************************************************************************************************************************
 [started TASK: make sure jinja is the right version on localhost]

TASK [make sure jinja is the right version] **********************************************************************************************************************************************************************************************************************************
ok: [localhost]
 [started TASK: assert on localhost]

TASK [assert] ****************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
 [started TASK: set_fact on localhost]

TASK [set_fact] **************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]
 [started TASK: assert on localhost]

TASK [assert] ****************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "a_list[1]|type_debug == \"AnsibleUnicode\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
