### ISSUE TITLE
Undefined Varibles

### ISSUE THREAD

**Issue by rnedellec** [ansible/ansible#74732]
### Summary

When I try to use a variable from group_vars/mygroup or host_var/myhost in a task and apply it on the local ansible machine (ansible_connection: local), I just can't and I get "<class 'dict'>": "VARIABLE IS NOT DEFINED!"

### Issue Type

Bug Report

### Component Name

ansible_connection ??

### Ansible Version

```console
$ ansible --version

ansible 2.10.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed

DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts.yml']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Configuration gérée par Ansible. Toute modification pourra être ecrasée.
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = True
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Debian 10.9

### Steps to Reproduce

inventaire :
```yaml
all:
  hosts:
    ansible:
      ansible_connection: local

managed:
  hosts:
    ansible:

provisionners:
  hosts:
    ansible:
```

playbook :
```yaml
- name: provisioners
  hosts: provisioners
  roles:
    - deployment
```

group_vars/provisionners : 
```yaml
deployment_projects:
  - identifier: test
    git: git1
    path: /etc/ansible/files/test
  - identifier: test2
    git: git2
    path: /etc/ansible/files/test2
```

roles/deployment/tasks/main.yml : 
```yaml
- name: test
  debug:
    var: "{{ item }}"
  with_items: "{{ deployment_projects }}"
```

### Expected Results

I expected to have the variable and be able to use it but it is not the case

### Actual Results

```console
TASK [deployment : test] ***********************************************************************************************
ok: [ansiblelab] => (item={'identifier': 'test', 'git': 'git1', 'path': '/etc/ansible/files/test'}) => {
    "<class 'dict'>": "VARIABLE IS NOT DEFINED!",
    "ansible_loop_var": "item",
    "item": {
        "git": "git1",
        "identifier": "test",
        "path": "/etc/ansible/files/test"
    }
}
ok: [ansiblelab] => (item={'identifier': 'test2', 'git': 'git2', 'path': '/etc/ansible/files/test2'}) => {
    "<class 'dict'>": "VARIABLE IS NOT DEFINED!",
    "ansible_loop_var": "item",
    "item": {
        "git": "git2",
        "identifier": "test2",
        "path": "/etc/ansible/files/test2"
    }
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
