### ISSUE TITLE
win_scheduled_task errors with "failed to modify scheduled task: The directory property cannot be found in the cache"

### ISSUE THREAD

**Issue by rkeithhill** [ansible/ansible#74742]
### Summary

When I run the following task, I get the specified error:
```yaml
  - name: Conan Scheduled Task | clear cache every Saturday
    win_scheduled_task:
      name: Conan Cache Clear
      description: Clear Conan cache every Saturday
      actions:
        - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
          arguments: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& { conan remove * -f 2>&1 > C:\Users\{{ username }}\conanCacheClear.log }"
          working_directory: 'C:\Users\{{ username }}'
      allow_demand_start: yes
      compatibility: 2
      logon_type: s4u
      username: '{{ username }}'
      password: '{{ userpasswd }}'
      update_password: no
      triggers:
      - type: daily
      # - type: weekly
      #   days_of_week: Saturday
        start_boundary: '2021-01-01T18:00:00'
      state: present
      enabled: yes
```      

### Issue Type

Bug Report

### Component Name

win_scheduled_task

### Ansible Version

```console
$ ansible --version

ansible 2.9.20
  config file = /home/hillr/ansible-poc/ansible.cfg
  configured module search path = [u'/home/hillr/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = True
DEFAULT_HOST_LIST(/home/hillr/ansible-poc/ansible.cfg) = [u'/home/hillr/ansible-poc/hosts.ini']
```

### OS / Environment

Microsoft Windows 10.0.19042

### Steps to Reproduce

```yaml (paste below)
  - name: Conan Scheduled Task | clear cache every Saturday
    win_scheduled_task:
      name: Conan Cache Clear
      description: Clear Conan cache every Saturday
      actions:
        - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
          arguments: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& { conan remove * -f 2>&1 > C:\Users\{{ username }}\conanCacheClear.log }"
          working_directory: 'C:\Users\{{ username }}'
      allow_demand_start: yes
      compatibility: 2
      logon_type: s4u
      username: '{{ username }}'
      password: '{{ userpasswd }}'
      update_password: no
      triggers:
      - type: daily
      # - type: weekly
      #   days_of_week: Saturday
        start_boundary: '2021-01-01T18:00:00'
      state: present
      enabled: yes
```

### Expected Results

I expect the task gets created without an error.  BTW the task does seem to get created on Windows.  But the error stops my playbook.

### Actual Results

```console
TASK [Conan Scheduled Task | clear cache every Saturday] ************************************************
  6274 1621292503.94950: sending task start callback
  6274 1621292503.94956: entering _queue_task() for 192.168.162.132/win_scheduled_task
  6274 1621292503.94961: Creating lock for win_scheduled_task
  6274 1621292503.95137: worker is 1 (out of 1 available)
  6274 1621292503.95235: exiting _queue_task() for 192.168.162.132/win_scheduled_task
  6274 1621292503.95316: done queuing things up, now waiting for results queue to drain
  6274 1621292503.95323: waiting for pending results...
  6285 1621292503.95496: running TaskExecutor() for 192.168.162.132/TASK: Conan Scheduled Task | clear cache every Saturday
  6285 1621292503.95563: in run() - task 00155df6-45ba-5a84-bf79-00000000000a
  6285 1621292503.95621: calling self._execute()
  6285 1621292503.96201: Loading FilterModule 'core' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/core.py
  6285 1621292503.96302: Loading FilterModule 'gcp_kms_filters' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/gcp_kms_filters.py
  6285 1621292503.96395: Loading FilterModule 'ipaddr' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/ipaddr.py
  6285 1621292503.96427: Loading FilterModule 'json_query' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/json_query.py
  6285 1621292503.96467: Loading FilterModule 'k8s' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/k8s.py
  6285 1621292503.96530: Loading FilterModule 'mathstuff' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/mathstuff.py
  6285 1621292503.96628: Loading FilterModule 'network' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/network.py
  6285 1621292503.96657: Loading FilterModule 'urls' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/urls.py
  6285 1621292503.96678: Loading FilterModule 'urlsplit' from /usr/lib/python2.7/dist-packages/ansible/plugins/filter/urlsplit.py
  6285 1621292503.96750: Loading TestModule 'core' from /usr/lib/python2.7/dist-packages/ansible/plugins/test/core.py
  6285 1621292503.96767: Loading TestModule 'files' from /usr/lib/python2.7/dist-packages/ansible/plugins/test/files.py
  6285 1621292503.96782: Loading TestModule 'mathstuff' from /usr/lib/python2.7/dist-packages/ansible/plugins/test/mathstuff.py
  6285 1621292503.97220: trying /usr/lib/python2.7/dist-packages/ansible/plugins/connection
  6285 1621292503.97302: Loading Connection 'ssh' from /usr/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py (found_in_cache=True, class_only=False)
  6285 1621292503.97322: trying /usr/lib/python2.7/dist-packages/ansible/plugins/shell
  6285 1621292503.97352: Loading ShellModule 'powershell' from /usr/lib/python2.7/dist-packages/ansible/plugins/shell/powershell.py (found_in_cache=True, class_only=False)
  6285 1621292503.97544: Loading ActionModule 'normal' from /usr/lib/python2.7/dist-packages/ansible/plugins/action/normal.py
  6285 1621292503.97564: starting attempt loop
  6285 1621292503.97569: running the handler
  6285 1621292503.99289: trying /usr/lib/python2.7/dist-packages/ansible/module_utils
  6285 1621292503.99491: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/docker
  6285 1621292503.99512: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/identity
  6285 1621292503.99522: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/storage
  6285 1621292503.99533: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/net_tools
  6285 1621292503.99544: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/facts
  6285 1621292503.99593: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/distro
  6285 1621292503.99613: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/six
  6285 1621292503.99628: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/parsing
  6285 1621292503.99642: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/remote_management
  6285 1621292503.99670: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/ecs
  6285 1621292503.99685: trying /usr/lib/python2.7/dist-packages/ansible/module_utils/powershell
  6285 1621292504.00232: _low_level_execute_command(): starting
  6285 1621292504.00269: _low_level_execute_command(): executing: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand JgBjAGgAYwBwAC4AYwBvAG0AIAA2ADUAMAAwADEAIAA+ACAAJABuAHUAbABsAAoAJABlAHgAZQBjAF8AdwByAGEAcABwAGUAcgBfAHMAdAByACAAPQAgACQAaQBuAHAAdQB0ACAAfAAgAE8AdQB0AC0AUwB0AHIAaQBuAGcACgAkAHMAcABsAGkAdABfAHAAYQByAHQAcwAgAD0AIAAkAGUAeABlAGMAXwB3AHIAYQBwAHAAZQByAF8AcwB0AHIALgBTAHAAbABpAHQAKABAACgAIgBgADAAYAAwAGAAMABgADAAIgApACwAIAAyACwAIABbAFMAdAByAGkAbgBnAFMAcABsAGkAdABPAHAAdABpAG8AbgBzAF0AOgA6AFIAZQBtAG8AdgBlAEUAbQBwAHQAeQBFAG4AdAByAGkAZQBzACkACgBJAGYAIAAoAC0AbgBvAHQAIAAkAHMAcABsAGkAdABfAHAAYQByAHQAcwAuAEwAZQBuAGcAdABoACAALQBlAHEAIAAyACkAIAB7ACAAdABoAHIAbwB3ACAAIgBpAG4AdgBhAGwAaQBkACAAcABhAHkAbABvAGEAZAAiACAAfQAKAFMAZQB0AC0AVgBhAHIAaQBhAGIAbABlACAALQBOAGEAbQBlACAAagBzAG8AbgBfAHIAYQB3ACAALQBWAGEAbAB1AGUAIAAkAHMAcABsAGkAdABfAHAAYQByAHQAcwBbADEAXQAKACQAZQB4AGUAYwBfAHcAcgBhAHAAcABlAHIAIAA9ACAAWwBTAGMAcgBpAHAAdABCAGwAbwBjAGsAXQA6ADoAQwByAGUAYQB0AGUAKAAkAHMAcABsAGkAdABfAHAAYQByAHQAcwBbADAAXQApAAoAJgAkAGUAeABlAGMAXwB3AHIAYQBwAHAAZQByAA==
  6285 1621292504.00745: Sending initial data
  6285 1621292504.02047: Sent initial data (117154 bytes)
  6285 1621292504.97658: stderr chunk (state=3):
>>>#< CLIXML
<<<
  6285 1621292506.69150: stdout chunk (state=3):
>>>{"changed":false,"msg":"failed to modify scheduled task: The directory property cannot be found in the cache.\r\n","failed":true}
<<<
  6285 1621292506.69893: stderr chunk (state=3):
>>><Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs><<<
  6285 1621292506.76997: stderr chunk (state=3):
>>><<<
  6285 1621292506.77009: stdout chunk (state=3):
>>><<<
  6285 1621292506.77165: _low_level_execute_command() done: rc=0, stdout={"changed":false,"msg":"failed to modify scheduled task: The directory property cannot be found in the cache.\r\n","failed":true}
, stderr=
  6285 1621292506.77240: done with _execute_module (win_scheduled_task, {'_ansible_version': '2.9.20', u'update_password': False, u'actions': [{u'path': u'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe', u'working_directory': u'C:\\Users\\mctcbld', u'arguments': u'-NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "& { conan remove * -f 2>&1 > C:\\Users\\mctcbld\\conanCacheClear.log }"'}], '_ansible_check_mode': False, '_ansible_module_name': u'win_scheduled_task', u'state': u'present', u'allow_demand_start': True, u'logon_type': u's4u', '_ansible_debug': True, '_ansible_shell_executable': u'/bin/sh', u'username': u'mctcbld', '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p', 'vfat'], u'description': u'Clear Conan cache every Saturday', '_ansible_syslog_facility': u'LOG_USER', '_ansible_keep_remote_files': False, '_ansible_socket': None, '_ansible_string_conversion_action': u'warn', u'password': u'----', u'compatibility': 2, '_ansible_no_log': False, u'name': u'Conan Cache Clear', u'triggers': [{u'type': u'daily', u'start_boundary': u'2021-01-01T18:00:00'}], u'enabled': True, '_ansible_verbosity': 0, '_ansible_diff': False, '_ansible_remote_tmp': u'%TEMP%', '_ansible_tmpdir': None})
  6285 1621292506.77253: handler run complete
  6285 1621292506.77261: attempt loop complete, returning result
  6285 1621292506.77273: _execute() done
  6285 1621292506.77277: dumping result to json
  6285 1621292506.77284: done dumping result, returning
  6285 1621292506.77298: done running TaskExecutor() for 192.168.162.132/TASK: Conan Scheduled Task | clear cache every Saturday [00155df6-45ba-5a84-bf79-00000000000a]
  6285 1621292506.77314: sending task result for task 00155df6-45ba-5a84-bf79-00000000000a
  6285 1621292506.77366: done sending task result for task 00155df6-45ba-5a84-bf79-00000000000a
  6285 1621292506.77408: WORKER PROCESS EXITING
  6274 1621292506.77495: marking 192.168.162.132 as failed
  6274 1621292506.77510: marking host 192.168.162.132 failed, current state: HOST STATE: block=2, task=1, rescue=0, always=0, run_state=ITERATING_TASKS, fail_state=FAILED_NONE, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
  6274 1621292506.77519: ^ failed state is now: HOST STATE: block=2, task=1, rescue=0, always=0, run_state=ITERATING_COMPLETE, fail_state=FAILED_TASKS, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
  6274 1621292506.77525: getting the next task for host 192.168.162.132
  6274 1621292506.77532: host 192.168.162.132 is done iterating, returning
fatal: [192.168.162.132]: FAILED! => {"changed": false, "msg": "failed to modify scheduled task: The directory property cannot be found in the cache.\r\n"}
  6274 1621292506.77571: no more pending results, returning what we have
  6274 1621292506.77578: results queue empty
  6274 1621292506.77583: checking for any_errors_fatal
  6274 1621292506.77589: done checking for any_errors_fatal
  6274 1621292506.77593: checking for max_fail_percentage
  6274 1621292506.77597: done checking for max_fail_percentage
  6274 1621292506.77602: checking to see if all hosts have failed and the running result is not ok
  6274 1621292506.77606: done checking to see if all hosts have failed
  6274 1621292506.77610: getting the remaining hosts for this loop
  6274 1621292506.77616: done getting the remaining hosts for this loop
  6274 1621292506.77625: building list of next tasks for hosts
  6274 1621292506.77629: getting the next task for host 192.168.162.132
  6274 1621292506.77635: host 192.168.162.132 is done iterating, returning
  6274 1621292506.77640: done building task lists
  6274 1621292506.77645: counting tasks in each state of execution
  6274 1621292506.77650: done counting tasks in each state of execution:
        num_setups: 0
        num_tasks: 0
        num_rescue: 0
        num_always: 0
  6274 1621292506.77656: all hosts are done, so returning None's for all hosts
  6274 1621292506.77661: done queuing things up, now waiting for results queue to drain
  6274 1621292506.77667: results queue empty
  6274 1621292506.77672: checking for any_errors_fatal
  6274 1621292506.77677: done checking for any_errors_fatal
  6274 1621292506.77681: checking for max_fail_percentage
  6274 1621292506.77686: done checking for max_fail_percentage
  6274 1621292506.77691: checking to see if all hosts have failed and the running result is not ok
  6274 1621292506.77695: done checking to see if all hosts have failed
  6274 1621292506.77701: getting the next task for host 192.168.162.132
  6274 1621292506.77707: host 192.168.162.132 is done iterating, returning
  6274 1621292506.77713: running handlers

PLAY RECAP **********************************************************************************************
192.168.162.132            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
