### ISSUE TITLE
Unable to run azure resource group creation playbook

### ISSUE THREAD

**Issue by rajaniesh** [ansible/ansible#74758]
### Summary

I tried running the azure resource group creation playbook by following these steps given in the MS site:https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=ansible#file-credentials

but it is throwing this error

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'urllib3.packages.six'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on ansible-controller's Python /usr/bin/python3.6. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

### Issue Type

Bug Report

### Component Name

msrestazure

### Ansible Version

```console
$ ansible --version
ansible 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
$ ansible-config dump --only-changed
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

### Steps to Reproduce

```yaml (paste below)

- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: Solutioning_team
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Solutioning_team
      name: Solutioning_team-vnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: Solutioning_team
      name: default
      address_prefix: "10.0.1.0/24"
      virtual_network: Solutioning_team-vnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: Solutioning_team
      allocation_method: Static
      name: sketchvm_PublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: Solutioning_team
      name: sketchVm_NSG
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: Solutioning_team
      name: sketchvm_NIC
      virtual_network: Solutioning_team-vnet
      subnet: default
      public_ip_name: sketchvm_PublicIP
      security_group: sketchVm_NSG
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: USA_Solutioning_team
      name: sketchVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: true
      network_interfaces: sketchvm_NIC
      image:
        offer: Ubuntu
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest

```

### Expected Results

I expected it to create a azure VM

### Actual Results

```console
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Create Azure VM] *******************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [localhost]

TASK [Create resource group] *************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'urllib3.packages.six'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on ansible-controller's Python /usr/bin/python3.6. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
