### ISSUE TITLE
"parameters are mutually exclusive: deb|package|upgrade"

### ISSUE THREAD

**Issue by nscblauensteiner** [ansible/ansible#74761]
### Summary

When I execute the playbook the following error message appears:

AWX Output:

...

**TASK [Only security updates] ***************************************************
fatal: [ansibletestubuntu]: FAILED! => {"changed": false, "msg": "parameters are mutually exclusive: deb|package|upgrade"}**

...

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
2.9.21
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:6379:0
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/.ssh/id_rsa
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/etc/ansible/ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.ini', '.cfg', '.retry']
```

### OS / Environment

CentOS 8.3.2011

### Steps to Reproduce

```
---
- hosts: all
  remote_user: user
  become_user: root

  tasks:
  - name: Make a copy of security repos
    shell: grep secu /etc/apt/sources.list > /etc/apt/security.sources.list

  - name: Refresh cache
    apt:
      update_cache: yes

  - name: Only security updates
    apt:
      upgrade: yes
      name: "*"
      state: latest
      force_apt_get: true
      dpkg_options: Dir::Etc::SourceList=/etc/apt/security.sources.list
```

### Expected Results

Only updates from the list for all packages are brought up to date.

### Actual Results

```
The full traceback is:
  File "/tmp/ansible_apt_payload_qtq50snt/ansible_apt_payload.zip/ansible/module_utils/basic.py", line 1607, in _check_mutually_exclusive
    check_mutually_exclusive(spec, param)
  File "/tmp/ansible_apt_payload_qtq50snt/ansible_apt_payload.zip/ansible/module_utils/common/validation.py", line 66, in check_mutually_exclusive
    raise TypeError(to_native(msg))
fatal: [ansibletestubuntu]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "name": "*",
            "package": "*",
            "state": "latest",
            "upgrade": "yes"
        }
    },
    "msg": "parameters are mutually exclusive: deb|package|upgrade"
}

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
