### ISSUE TITLE
copy wont copy symlink as symlink if single file

### ISSUE THREAD

**Issue by xeor** [ansible/ansible#74777]
### Summary

If you use the copy module, it doesnt seam to copy symlinks as symlinks, even if you specify `local_follow: false`.
I think this is because of https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py#L681 and the shutil's defaulting to `follow_symlink=True` (https://docs.python.org/3/library/shutil.html#shutil.copyfile).
Other places in the copy module symlinks are handled, example when copying whole directories (`shutil.copytree(b_src, b_dest, symlinks=not(local_follow))`, ...)

### Issue Type

Bug Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
2.10.3
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
---

- name: Test for preserving symlinks
  hosts: all
  gather_facts: false
  tasks:
    - name: Create test dir
      file:
        path: '/tmp/symlinktest-source'
        state: directory

    - name: Create test dir dest
      file:
        path: '/tmp/symlinktest-dest'
        state: directory

    - name: Copy using inline content
      copy:
        content: 'some content in here'
        dest: '/tmp/symlinktest-source/file'

    - name: Create a symbolic link to dummy
      file:
        src: '/tmp/symlinktest-source/file'
        dest: '/tmp/symlinktest-source/symlink'
        state: link

    # Doesnt preserve the symlink
    - name: Try to copy file
      copy:
        remote_src: true
        local_follow: false
        src: '/tmp/symlinktest-source/symlink'
        dest: '/tmp/symlinktest-dest/symlink'

    # However.. This works
    - name: Copy files
      copy:
        remote_src: true
        local_follow: false
        src: '/tmp/symlinktest-source/'
        dest: '/tmp/symlinktest-dest-works'

```

### Expected Results

symlink is preserved both when copying using directory, but also if copying only the symlink

### Actual Results

```console
[root@localhost tmp]# ls -l symlinktest-*
symlinktest-dest:
total 4
-rw-rw-r--. 1 vagrant vagrant 20 May 20 11:52 symlink

symlinktest-dest-works:
total 4
-rw-rw-r--. 1 vagrant vagrant 20 May 20 11:52 file
lrwxrwxrwx. 1 vagrant vagrant 28 May 20 11:52 symlink -> /tmp/symlinktest-source/file

symlinktest-source:
total 4
-rw-rw-r--. 1 vagrant vagrant 20 May 20 11:52 file
lrwxrwxrwx. 1 vagrant vagrant 28 May 20 11:52 symlink -> /tmp/symlinktest-source/file
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
