### ISSUE TITLE
file - cannot create symlinks using relative paths

### ISSUE THREAD

**Issue by Shrews** [ansible/ansible#74784]
### Summary

Using the `file` module to create symlinks, with relative paths for the `src` and `dest` parameters, fails since it calculates an incorrect `src` path.

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
% ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current 
version: 3.7.3 (default, Apr 24 2020, 18:51:23) [Clang 11.0.3 (clang-1103.0.32.62)]. This feature will be removed from 
ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are
modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible [core 2.12.0.dev0]  (file_symlink_bug 83010f666d) last updated 2021/05/20 13:49:54 (GMT -400)
  config file = /Users/shrews/.ansible.cfg
  configured module search path = ['/Users/shrews/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/shrews/Devel/github/Shrews/ansible/lib/ansible
  ansible collection location = /Users/shrews/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/shrews/Devel/github/Shrews/ansible/bin/ansible
  python version = 3.7.3 (default, Apr 24 2020, 18:51:23) [Clang 11.0.3 (clang-1103.0.32.62)]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed

DEFAULT_HOST_LIST(/Users/shrews/.ansible.cfg) = ['/Users/shrews/Devel/ansible/hosts.yaml']
```

### OS / Environment

Mac OSX 11.3.1

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create relative test directory
      file:
        path: 'bug_test'
        state: directory

    - name: Make a file to symlink to
      file:
        path: 'bug_test/a.txt'
        state: touch

    - name: Create a symbolic link to a.txt in same test directory
      file:
        src: 'bug_test/a.txt'
        dest: 'bug_test/b.txt'
        state: link
```

### Expected Results

Symlink should be created.

### Actual Results

```console
PLAY [localhost] **********************************************************************************************************

TASK [Create relative test directory] *************************************************************************************
ok: [localhost]

TASK [Make a file to symlink to] ******************************************************************************************
changed: [localhost]

TASK [Create a symbolic link to dummy] ************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: bug_test/bug_test/a.txt", "path": "bug_test/b.txt", "src": "bug_test/a.txt"}

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Shrews** [comment]
Note the `src` path is calculated as `bug_test/bug_test/a.txt`.

**Comment by Shrews** [comment]
Not a bug. `src` should be relative to `dest`|`path`.

```yaml
    - file:
         src: 'a.txt'
         path: 'bug_test/b.txt'
         state: link
```
