### ISSUE TITLE
FirewalldD Module Fails if Port is Already Opened

### ISSUE THREAD

**Issue by rcgoodfellow** [ansible/ansible#74800]
### Summary

Looks like https://github.com/ansible/ansible/issues/23895 is an issue again.

### Issue Type

Bug Report

### Component Name

firewalld

### Ansible Version

```console
$ ansible --version
ansible 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 14 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora 34

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  become: true
  tasks:

    - name: allow raven control traffic through libvirt firewalld zone
      firewalld:
        port: 9316/tcp
        state: enabled
```

Just run this when when the specified rule is already present.

### Expected Results

No error, the rule is already enabled.

### Actual Results

```console
TASK [allow raven control traffic through libvirt firewalld zone] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: ALREADY_ENABLED: '9316:tcp' already in 'FedoraWorkstation' Non-permanent operation"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
