### ISSUE TITLE
Module not found pyVim

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#74826]
### Summary

Other playbooks are working fine on this (deployment) machine.  Have reviewed many threads here related to similar issue and nothing seems to work for me.  pip shows the pyvmomi module is installed...

Using:
```
- name: "Changing Machine state for: {{ vcpwrname }} to State: {{ vcpwrstate }}"
  vmware_guest:
    validate_certs: no
    state: "{{ vcpwrstate }}"
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    name: "{{ vcpwrname }}"
    folder: "{{ vcpwrfolder }}"
    # had to set force flag here to get around the suspend bug
    force: true
  delegate_to: localhost
  tags: power
```

Also tried manually setting:
`ansible_python_interpreter=/Users/spollock/opt/anaconda3/bin/python`

### Issue Type

Bug Report

### Component Name

pyvmomi

### Ansible Version

```console
(base) spollock@Dude3 ~ % ansible --version
ansible 2.9.7
  config file = None
  configured module search path = ['/Users/spollock/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/spollock/opt/anaconda3/lib/python3.7/site-packages/ansible
  executable location = /Users/spollock/opt/anaconda3/bin/ansible
  python version = 3.7.6 (default, Jan  8 2020, 13:42:34) [Clang 4.0.1 (tags/RELEASE_401/final)]
```

### Configuration

```console
ansible-config dump --only-changed <no results>

(base) spollock@Dude3 ~ % which python
/Users/spollock/opt/anaconda3/bin/python

(base) spollock@Dude3 ~ % pip show pyvmomi
Name: pyvmomi
Version: 7.0
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /Users/spollock/opt/anaconda3/lib/python3.7/site-packages
Requires: six, requests
Required-by: vSphere-Automation-SDK
```

### OS / Environment

OSX 10.15.7

### Steps to Reproduce

```yaml (paste below)
(base) spollock@Dude3 fs-vmw-control % ansible-playbook power-single.yml 

PLAY [Power Options for a single machine] ********************************************************************************************************

TASK [power-single : Changing Machine state for: Moodle-Test to State: poweredon] ****************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'pyVim'
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (PyVmomi) on Dude3.local's Python /Users/spollock/opt/anaconda3/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

### Expected Results

Should have run successfully.

### Actual Results

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'pyVim'
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (PyVmomi) on Dude3.local's Python /Users/spollock/opt/anaconda3/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
