### ISSUE TITLE
Using expressions in the inventory file results in the expression being logged and not the evaluated value.

### ISSUE THREAD

**Issue by plasm0r** [ansible/ansible#74821]
### Summary

When using a lookup expression for a host value in the inventory file, the IP addresses of the hosts are resolved correctly as the playbook executes and targets the correct hosts in the inventory. However, the log output does not log the evaluated value of the expression i.e. the IP address, but rather the expression itself.

### Issue Type

Bug Report

### Component Name

inventory

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
```

### OS / Environment
Ansible control node:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

Managing Windows servers using WinRM in an Azure environment.

### Steps to Reproduce

Create an inventory file where you lookup the host IPs from environment variables. e.g.

```yaml (paste below)
---
all:
  children:
     dbservers:
      hosts:
        "{{lookup('env','DB_SERVER1_IP_ADDRESS')}}":
        "{{lookup('env','DB_SERVER2_IP_ADDRESS')}}":
```

### Expected Results

Expected log output:

TASK [Gathering Facts] *********************************************************
Tuesday 25 May 2021  13:08:32 +0000 (0:00:00.033)       0:00:00.033 *********** 
ok: [10.0.8.4]
ok: [10.0.8.5]

### Actual Results

```console
Actual log output:

TASK [Gathering Facts] *********************************************************
Tuesday 25 May 2021  13:08:32 +0000 (0:00:00.033)       0:00:00.033 *********** 
ok: [{{lookup('env','DB_SERVER1_IP_ADDRESS')}}]
ok: [{{lookup('env','DB_SERVER2_IP_ADDRESS')}}]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/inventory`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
there have been several fixes to name handling in the latest versions, can you check with ansible-core 2.11?

**Comment by bcoca** [comment]
You probably want to use something like this
```
all:
  children:
     dbservers:
      hosts:
        db1:
          ansible_host: "{{lookup('env','MYIP')}}"
```
