### ISSUE TITLE
Add include_defaults module

### ISSUE THREAD

**Issue by sathieu** [ansible/ansible#74822]
### Summary

I need to load defaults from other roles.

I tried:

```yaml
  - include_vars:
      dir: "../../{{ item }}/defaults"
    with_items:
    - other_role1
    - other_role2
```

This mostly works, but those defaults override group_vars.

I've also read: https://www.samdarwin.com/ansible-default-vars/. But I don't want to rename the variables `default_varname`.

I've also tried doing this:

```yaml
# main.yml
  - include_tasks: import_defaults.yml
    with_items:
    - other_role1
    - other_role2
    loop_control:
      loop_var: role

# import_defaults.yml:

- include_vars:
    dir: "../../{{ role }}/defaults"
    name: included_defaults

- set_fact:
    "{{ item.key }}": "{{ item.value }}"
  when:
  - vars[item] is not defined
  with_items: "{{ included_defaults | dict2items }}"
```

This works until a variable reference another variable. Then fails with: `''referenced_var'' is undefined`.

The only workaround that works is using symlinks.

I think this usecase is very common, and I think having a `include_defaults` or similar feature would help.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

```yaml

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
