### ISSUE TITLE
ansible_virtualization_type inconsistent values across runs

### ISSUE THREAD

**Issue by anxstj** [ansible/ansible#74831]
### Summary

I'm using molecule to test my roles. Installing cron inside a Debian 10 container on a Debian 10 hosts causes the `ansible_virtualization_type` to switch from *docker* to *containerd*. This happens with ansible-core 2.11.0 and 2.11.1, but not with ansible-base 2.10 or ansible 2.9.

### Issue Type

Bug Report

### Component Name

setup

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.1] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/molecular/env/lib/python3.7/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/molecular/env/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
(empty)
```

### OS / Environment

Debian 10.3 (buster)
Docker version 19.03.11, build 42e35e61f3

### Steps to Reproduce

Example playbook:
```yaml (paste below)
---
- name: Converge
  hosts: all
  tasks:
    - name: show type
      debug:
        var: ansible_virtualization_type
    - name: show tech_guest
      debug:
        var: ansible_virtualization_tech_guest
    - name: Update package manager cache and ensure cron is installed
      apt:
        name: cron
        update_cache: true
        cache_valid_time: 3600
    - name: update facts
      setup:
    - name: show type
      debug:
        var: ansible_virtualization_type
    - name: show tech_guest
      debug:
        var: ansible_virtualization_tech_guest
    - name: fail
      fail:
        msg: "ansible_virtualization_type({{ ansible_virtualization_type }}) != docker"
      when: ansible_virtualization_type != "docker"
```

Example molecule.yml:
```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - capabilities:
      - SYS_ADMIN
    command: /lib/systemd/systemd
    image: sjakobs/debian-10-systemd:latest
    name: linux-debian-10
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: goss
```

### Expected Results

The `ansible_virtualization_type` should stay on *docker*.

```
PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [linux-debian-10]

TASK [show type] ***************************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_type": "docker"
}

TASK [show tech_guest] *********************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_tech_guest": [
        "container",
        "containerd",
        "VMware",
        "docker"
    ]
}

TASK [Update package manager cache and ensure cron is installed] ***************
changed: [linux-debian-10]

TASK [update facts] ************************************************************
ok: [linux-debian-10]

TASK [show type] ***************************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_type": "docker"
}

TASK [show tech_guest] *********************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_tech_guest": [
        "container",
        "docker",
        "VMware",
        "containerd"
    ]
}

TASK [fail] ********************************************************************
skipping: [linux-debian-10]

PLAY RECAP *********************************************************************
linux-debian-10            : ok=7    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

### Actual Results

```console
The `ansible_virtualization_type` changes from *docker* to *containerd*!


PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [linux-debian-10]

TASK [show type] ***************************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_type": "docker"
}

TASK [show tech_guest] *********************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_tech_guest": [
        "docker",
        "containerd",
        "container",
        "VMware"
    ]
}

TASK [Update package manager cache and ensure cron is installed] ***************
changed: [linux-debian-10]

TASK [update facts] ************************************************************
ok: [linux-debian-10]

TASK [show type] ***************************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_type": "containerd"
}

TASK [show tech_guest] *********************************************************
ok: [linux-debian-10] => {
    "ansible_virtualization_tech_guest": [
        "VMware",
        "docker",
        "container",
        "containerd"
    ]
}

TASK [fail] ********************************************************************
fatal: [linux-debian-10]: FAILED! => {"changed": false, "msg": "ansible_virtualization_type(containerd) != docker"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
