### ISSUE TITLE
Ansibles file module unable to remove ssh files

### ISSUE THREAD

**Issue by g4njawizard** [ansible/ansible#74857]
### Summary

I try to remove default SSH files and recreate them. The files:

```
 ll /etc/ssh/ssh_host_*
-rw-r--r-- 1 root root  566 19. Nov 2020  /etc/ssh/ssh_host_rsa_key.pub
-rw------- 1 root root 2,6K 19. Nov 2020  /etc/ssh/ssh_host_rsa_key
-rw-r--r-- 1 root root  174 19. Nov 2020  /etc/ssh/ssh_host_ecdsa_key.pub
-rw------- 1 root root  505 19. Nov 2020  /etc/ssh/ssh_host_ecdsa_key
-rw-r--r-- 1 root root   94 19. Nov 2020  /etc/ssh/ssh_host_ed25519_key.pub
-rw------- 1 root root  399 19. Nov 2020  /etc/ssh/ssh_host_ed25519_key
```

When I run this task:

```
---
- hosts: localhost
  connection: local
  tasks:

    - name: Delete ssh host keys
      become_user: root
      tags: setup
      file:
        path: '/etc/ssh/{{ file }}'
        state: absent
      with_file:
        - ssh_host_ecdsa_key
```

and different version:

```
- name: Delete ssh host keys
  become_user: root
  file:
    path: '{{ file }}'
    state: absent
  with_file:
    - /etc/ssh/ssh_host_ecdsa_key
```

I receive the following error:

```
TASK [Delete ssh host keys] ****************************************************************************************************************************************************
[WARNING]: Unable to find 'ssh_host_ecdsa_key' in expected paths (use -vvvvv to see paths)
fatal: [localhost]: FAILED! => {"msg": "could not locate file in lookup: ssh_host_ecdsa_key"}
```

This looks almost like a bug.

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/odin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

### Configuration

```console
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/ansible/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = True
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

Debian

### Steps to Reproduce

delete ssh host key

### Expected Results

file should be deleted

### Actual Results

```console
[WARNING]: Unable to find 'ssh_host_ecdsa_key' in expected paths (use -vvvvv to see paths)
fatal: [localhost]: FAILED! => {"msg": "could not locate file in lookup: ssh_host_ecdsa_key"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug. `with_file` is for looping over the contents of files; it uses the `file` lookup to fetch the file contents. Since you're looping over filenames, you should just be using `loop` or `with_list`.

```
- name: Delete ssh host keys
  become: true
  file:
    path: '{{ file }}'
    state: absent
  loop:
    - /etc/ssh/ssh_host_ecdsa_key
```
