### ISSUE TITLE
Calling role by FQCN not working with play roles keyword

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#74858]
### Summary

I am building a collection of Mac-focused Ansible content in my [ansible-collection-mac](https://github.com/geerlingguy/ansible-collection-mac) repository.

This evening, I was trying to adapt my existing tests from my individual roles into one collection test playbook, and I attempted to call the roles from the collection with the following playbook:

```yaml
---
- hosts: localhost

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
```

This resulted in the following error:

```
ERROR! the role 'geerlingguy.mac.homebrew' was not found in /Users/runner/work/ansible-collection-mac/ansible-collection-mac/ansible_collections/geerlingguy/mac/tests/roles:/Users/runner/work/ansible-collection-mac/ansible-collection-mac/ansible_collections/geerlingguy:/Users/runner/work/ansible-collection-mac/ansible-collection-mac/ansible_collections/geerlingguy/roles:/Users/runner/work/ansible-collection-mac/ansible-collection-mac/ansible_collections/geerlingguy/mac/roles:/Users/runner/work/ansible-collection-mac/ansible-collection-mac/ansible_collections/geerlingguy/mac/tests

The error appears to be in '/Users/runner/work/ansible-collection-mac/ansible-collection-mac/ansible_collections/geerlingguy/mac/tests/test.yml': line 25, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
      ^ here
Error: Process completed with exit code 1.
```

### Issue Type

Bug Report

### Component Name

roles

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.0] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jgeerling/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 2.11.2
  libyaml = True
```

### Configuration

```console
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/Users/jgeerling/Dropbox/VMs/roles']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

macOS 11 and 10.15 (local and in GitHub Action CI).

### Steps to Reproduce

Using the CI environment for my [geerlingguy.mac](https://github.com/geerlingguy/ansible-collection-mac/) collection, try running the following playbook:

```yaml
---
- hosts: localhost

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
```

### Expected Results

The playbook should run without issue.

### Actual Results

The playbook fails and says it can't find the role. (See error above.)

### Temporary / annoying fix

For now, I'm able to get the roles picked up if I add a `collections` keyword to the play, but that's not a great solution, because I can't tell my collection's users to make sure they don't have any roles named `mas` or `homebrew`—this is one case where I'd like to use a FQCN but it seems to be failing me.

This playbook works:

```
---
- hosts: localhost

  collections:
    - geerlingguy.mac

  roles:
    - elliotweiser.osx-command-line-tools
    - homebrew
    - mas
```

I'm not sure why I can't pass in the FQCN to `roles` directly. Every other setting in the environment is identical.

See successful build: https://github.com/geerlingguy/ansible-collection-mac/actions/runs/889477373

See failed build: https://github.com/geerlingguy/ansible-collection-mac/runs/2703109490?check_suite_focus=true#step:7:4

The only change I made: https://github.com/geerlingguy/ansible-collection-mac/commit/a3bf8fa77cdac9c027fe024127a0fd939f3722cb

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
