### ISSUE TITLE
Cant select objects out of an registered loop when using uri module

### ISSUE THREAD

**Issue by g4njawizard** [ansible/ansible#74868]
### Summary

I tried to create a list out of downloadlinks for Appimages where I can compare if they already are in the newest versions locally available. For this I create a loop to process al links without following redirects.
When you run the task and debug without selecting an object, the results are formatted as intended.
`
    - debug:
        msg: "{{ item }}"
      loop: "{{ appimage_appimage.results }}"`

When you change to {{ item.location }} or item.stderr item.stdout or whatelse.. the result comes printed unformatted without the selected string
Therefore it makes it impossible to work further with the result.

### Issue Type

Bug Report

### Component Name

uri, loop, register

### Ansible Version

```console
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/odin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

### Configuration

```console
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/ansible/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = True
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

Debian

### Steps to Reproduce

```yaml (paste below)
- name: Appimage DL
  hosts: localhost
  connection: local

  vars:
    appimage:
      dl_url:
        - "https://vault.appimage.com/download/?app=desktop&platform=linux"
        - "https://github.com/yang991178/fluent-reader/releases/latest"
      appimage_dir: /tmp

  tasks:

    - name: Follow without redirect
      uri:
        url: "{{ item }}"
        follow_redirects: none
      with_items: "{{ appimage.dl_url }}"
      register: appimage_appimage
      failed_when: no

    - debug:
        msg: "{{ item.location }}"
      loop: "{{ appimage_appimage.results }}"
```

### Expected Results

printed: 

"location": "https://github.com/yang991178/fluent-reader/releases/tag/v1.0.1",

### Actual Results

```console
ok: [localhost] => (item={'redirected': False, 'url': 'https://github.com/yang991178/fluent-reader/releases/latest', 'status': 302, 'server': 'GitHub.com', 'date': 'Tue, 01 Jun 2021 08:19:58 GMT', 'content_type': 'text/html; charset=utf-8', 'vary': 'X-PJAX, Accept-Encoding, Accept, X-Requested-With', 'permissions_policy': 'interest-cohort=()', 'location': 'https://github.com/yang991178/fluent-reader/releases/tag/v1.0.1', 'cache_control': 'no-cache', 'strict_transport_security': 'max-age=31536000; includeSubdomains; preload', 'x_frame_options': 'deny', 'x_content_type_options': 'nosniff', 'x_xss_protection': '0', 'referrer_policy': 'no-referrer-when-downgrade', 'expect_ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"', 'content_security_policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com html-translator.herokuapp.com cdn.optimizely.com logx.optimizely.com/v1/events wss://alive.github.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations insights.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/ *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/socket-worker-3f088aa2.js gist.github.com/socket-worker-3f088aa2.js", 'set_cookie': 'logged_in=no; Path=/; Domain=github.com; Expires=Wed, 01 Jun 2022 08:21:19 GMT; HttpOnly; Secure; SameSite=Lax', 'content_length': '129', 'x_github_request_id': '26D5:F0EF:608D535:63C8C73:60B5EDFF', 'connection': 'close', 'elapsed': 0, 'changed': False, 'failed': False, 'msg': 'Status code was 302 and not [200]: HTTP Error 302: Found', 'invocation': {'module_args': {'url': 'https://github.com/yang991178/fluent-reader/releases/latest', 'follow_redirects': 'none', 'force': False, 'http_agent': 'ansible-httpget', 'use_proxy': True, 'validate_certs': True, 'force_basic_auth': False, 'body_format': 'raw', 'method': 'GET', 'return_content': False, 'status_code': [200], 'timeout': 30, 'headers': {}, 'remote_src': False, 'unsafe_writes': False, 'url_username': None, 'url_password': None, 'client_cert': None, 'client_key': None, 'dest': None, 'body': None, 'src': None, 'creates': None, 'removes': None, 'unix_socket': None, 'mode': None, 'owner': None, 'group': None, 'seuser': None, 'serole': None, 'selevel': None, 'setype': None, 'attributes': None}}, 'failed_when_result': False, 'item': 'https://github.com/yang991178/fluent-reader/releases/latest', 'ansible_loop_var': 'item'}) => {
    "msg": "https://github.com/yang991178/fluent-reader/releases/tag/v1.0.1"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
