### ISSUE TITLE
Ansible-base 2.10.10 breaks win_template

### ISSUE THREAD

**Issue by perithompson** [ansible/ansible#74887]
### Summary

When using win_template to create files on windows, upgrading to ansible-base 2.10.10 results in a file not found error 

```
[0;32m    vhd-windows-2004: TASK [cloudbase-init : Set up cloudbase-init unattend configuration] ***********[0m
[0;32m    vhd-windows-2004: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'C:\\Program Files\\Cloudbase Solutions\\Cloudbase-Init\\conf\\cloudbase-init-unattend.conf'[0m
[0;32m    vhd-windows-2004: fatal: [default]: FAILED! => {"changed": false, "msg": "FileNotFoundError: [Errno 2] No such file or directory: b'C:\\\\Program Files\\\\Cloudbase Solutions\\\\Cloudbase-Init\\\\conf\\\\cloudbase-init-unattend.conf'"}[0m
```

```yaml
- name: Set up cloudbase-init unattend configuration 
  win_template:
    src: templates/cloudbase-init-unattend.conf
    dest: "{{ programfiles.stdout | trim }}\\Cloudbase Solutions\\Cloudbase-Init\\conf\\cloudbase-init-unattend.conf"
```

rolling back to 2.10.9 immediately resolves the issue

### Issue Type

Bug Report

### Component Name

ansible-base

### Ansible Version

```console
Collecting ansible==2.10.0
  Downloading ansible-2.10.0.tar.gz (25.5 MB)
Collecting ansible-base<2.11,>=2.10.1
  Downloading ansible-base-2.10.10.tar.gz (6.0 MB)
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Windows 2019 and Windows 20H1(2004)

### Steps to Reproduce

```yaml
- name: Set up cloudbase-init unattend configuration 
  win_template:
    src: templates/cloudbase-init-unattend.conf
    dest: "{{ programfiles.stdout | trim }}\\Cloudbase Solutions\\Cloudbase-Init\\conf\\cloudbase-init-unattend.conf"
```

Running a windows build using will provide a reproduction currently
https://github.com/kubernetes-sigs/image-builder/commit/6e726d0d92126f6a42d261e7241e9037e8315f9c

### Expected Results

I expected the template to be created, however the result is that the ansible run fails

### Actual Results

```console
fatal: [default]: FAILED! => {"changed": false, "msg": "FileNotFoundError: [Errno 2] No such file or directory: b'C:\\\\Program Files\\\\Cloudbase Solutions\\\\Cloudbase-Init\\\\conf\\\\cloudbase-init-unattend.conf'"}[0m
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
