### ISSUE TITLE
become_user doesn't take effect when ansible_become_user is defined in group_vars

### ISSUE THREAD

**Issue by crossan007** [ansible/ansible#74929]
### Summary

Given an inventory file defining a server and a `group_vars` file defining the `ansible_become_user` for that server, an attempt to run a single task against the server with a `become_user` continues to use the user defined in `group_vars`

In other words, `become_user` on a single task does not override the `ansible_become_user` defined in a `group_vars` file.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ ansible --version

ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/charles/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/charles/.local/lib/python3.8/site-packages/ansible
  executable location = /home/charles/.local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Both Mac OSX 11.2.2 and Windows 10 WSL (ubuntu)

### Steps to Reproduce

inventory.yaml:
```
all:
  dev-servers:
    my-host:
```

dev-servers.yaml:
```
ansible_become_user: elevated_user_but_not_root
ansible_become: yes
```

not-working task.yml file: 
```
---
- name: Install Let's Encrypt certs
  shell: 
    cmd: certbot --webroot certonly -w /usr/share/nginx/html -d {{ item.value.apiBase }} -n --agree-tos --email <addr>
    creates: "/etc/letsencrypt/live/{{ item.value.apiBase }}/fullchain.pem"
  loop: "{{ query('dict', backend_instances) }}"
  when: item.value.apiBase2 is undefined and not isLoadBalanced
  become_user: root
```

sort-of-working task.yml file:

```
- name: Install Let's Encrypt certs
  shell: 
    cmd: certbot --webroot certonly -w /usr/share/nginx/html -d {{ item.value.apiBase }} -n --agree-tos --email <addr>
    creates: "/etc/letsencrypt/live/{{ item.value.apiBase }}/fullchain.pem"
  loop: "{{ query('dict', backend_instances) }}"
  when: item.value.apiBase2 is undefined and not isLoadBalanced
  vars:
    ansible_become_user: root
```

### Expected Results

I expected `not-working task.yml` to run as `root`

### Actual Results

```console
`not-working task.yml` run as `elevated_user_but_not_root`

`sort-of-working task.yml` actually runs as `root`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
