### ISSUE TITLE
ansible-galaxy collection list doesn't show collections in adjacent path

### ISSUE THREAD

**Issue by henriqueccapozzi** [ansible/ansible#74942]
### Summary

When I try to execute the command `ansible-galaxy collection list` from the devel branch on Github, the command does not show collections in the adjacent path

```shell
./collections/ansible_collections/...
```

when i execute `ansible-playbook ...` and use the collection it works fine
but `ansible-galaxy collection list ...` doesn't show the installed collection
 

### Issue Type

Bug Report

### Component Name

lib/ansible/cli/galaxy.py

### Ansible Version

```console
$ ansible --version
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or
trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
ansible [core 2.12.0.dev0] (devel 346c7a765d) last updated 2021/06/08 22:34:29 (GMT -300)
  config file = None
  configured module search path = ['/home/henrique/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/henrique/Documents/contribuicoes/ansible/lib/ansible
  ansible collection location = /home/henrique/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/henrique/Documents/contribuicoes/ansible/bin/ansible
  python version = 3.9.5 (default, May  9 2021, 14:00:28) [GCC 10.2.0]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
No output
```

### OS / Environment

[0:00:24] henrique:ansible $ uname -a
Linux henrique-a52liv 5.10.36-2-MANJARO (HASH_SIGN)1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64 GNU/Linux

#### Setting things up
<br/>

```yaml (paste below)
# set.issue.yml
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: Remove the community.kubernetes role from default paths
    shell: |
      #/bin/bash
      galaxy_output=$(ansible-galaxy collection list)
      resp=$(echo "$galaxy_output" | grep community.kubernetes)
      if [[ $? -eq 0 ]]; then
          # must remove collections
          collection_paths=$(echo "$galaxy_output" | grep '^#' | cut -d ' ' -f2 )
          for p in ${collection_paths[@]}; do
              find $p -maxdepth 2 -type d -name kubernetes | grep -q kubernetes && \
                  echo "found community.kubernetes installed at $p"
                  rm -rfv $p/community/kubernetes
          done
      fi
      echo "Collection community.kubernetes not found or removed from default paths"
      echo "Ready to test issue"
    register: remove_register
    changed_when: "'found community.kubernetes installed at' in remove_register.stdout"
  
  - name: Install community.kubernetes at adjacent path
    command: "ansible-galaxy collection install community.kubernetes -p {{ playbook_dir }}/collections"
    register: install_register
    changed_when: "'All requested collections are already installed' not in install_register.stdout"

```
```yaml
# site.yml
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - community.kubernetes.k8s_info: kind=Pod
```

Then run
```bash
ansible-playbook -i localhost, set.issue.yml
```
and then `doesn't work if you call then together ;-) `

```bash
ansible-playbook -i localhost, site.yml
```
The last command will fail if you don't have openshift installed, but it loads the ansible module from the collection
and anyway so that's enough to test this issue

-----
#### Finally the issue...

```bash
ansible-galaxy collection list | grep community.kubernetes && echo "Collection is installed" || echo "Collection not listed by ansible-galaxy"
```
will output
`Collection not listed by ansible-galaxy`

### Expected Results

After running all the steps to reproduce, running the bellow command

```bash
ansible-galaxy collection list | grep community.kubernetes && echo "Collection is installed" || echo "Collection not listed by ansible-galaxy"
```

I should receive the following output

`Collection is installed`

### Actual Results

```console
Mentioned earlier
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
