### ISSUE TITLE
Lineinfile to fail on non-matching regex

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/ansible#74945]
### Summary

The lineinfile module is used to ensure that a line is in a file. Unfortunately, when none of the provided patterns (regexp, insertafter, insertbefore) match, the line will be appended to the end of the file. This is problematic if the context of the regexp was important.

I hope that the an option can be added to ensure that lineinfile fails hard instead of corrupting a file by appending a line. I also looked into the replace module which replaces a line in the whole file, but it also does not fit the use case since it succeeds even if the line is not found. The same issue exists when using the backrefs=yes option of lineinfile. Very consistent...

Assume that the template or copy module cannot be used. Right now there is no nice way to achieve the above. Users of lineinfile who expect behavior similar to sed "s/$regexp/$line/" $file will be disappointed.

### Issue Type

Feature Idea

### Component Name

lineinfile

### Additional Information

Add an option that ensures that lineinfile fails when the regexp has no matches. Behavior change if the regexp pattern is not matching:

With backrefs=yes - ensure that the task fails instead of remaining unchanged
Without backrefs=yes - ensure that the line not appended to the file and instead fail the task.
The feature could be used to modify (Ansible unmanaged) configuration files where appending to the end of the file would have adverse effects. For example, security policies might fail to apply or a corrupted configuration could be created. The option would prevent this from happening.

Or another flag can be added that modifies this behavior instead of doing it with the backrefs flag.

Example config for a task that tries to uncomment a line:

```
- name: enable port 587 for SMTP submission
  lineinfile:
    path: /etc/postfix/master.cf
    regexp: '^#submission(.*)'
    line: 'submission\1'
    backrefs: yes
```    
    
This was requested before and I can't believe it was closed with no action. It's something that should just be there when you think about functionality similar to sed or just regex operations.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/lineinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/lineinfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
Could this something you can use the [replace](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html) module for? The `lineinfile` module is to ensure the line specified is in the file.

**Comment by AdrianDutu** [comment]
No, my use case is after several steps and a vm provisioning, I'm updating my inventory so then some other steps can be performed on that vm.
The hosts file contain groups. So line in file is perfect to add the hostname after the group name line. So I don't have anything to replace, just add. But it the group is not existing, it will add the hostname at the end of the file and corrupting the file since there is now this hostname that does not belong in any group.

This is just my use case, but I have found someone else opened this before me and it was just closed.
I hope it will be considered this time. 
I agree the lineinfile module is to ensure the line is in the file, but I for sure there are a lot of use cases where that is conditioned by something. Otherwise, you don't want the line in the file at all. It's an all or nothing kind of scenario. Config files in particular need this feature. You want the line in the config if it makes sense to be there, otherwise you will corrupt the file.

**Comment by samdoran** [comment]
The purpose of `lineinfile` is to ensure a line exists in a file. Adding a toggle to change that behavior (`do_not_insert_line_if_regexp_does_not_mach=True`) would unnecessarily complicate the module and negate its primary purpose.

The best solution is to use `find` and check the file before running the `lineinfile` task.

```yaml
- name: Check for line in file
  find:
    paths: /etc/postfix/
    patterns: master.cf
    use_regex: yes
    contains:  '#submission(.*)'
  register: found

- name: enable port 587 for SMTP submission
  lineinfile:
    path: /etc/postfix/master.cf
    regexp: '^#submission(.*)'
    line: 'submission\1'
    backrefs: yes
  when: found.matched is truthy
```

Note that `find` by default matches regular expressions against the beginning of the line so anchoring with `^` isn't necessary.

> No, my use case is after several steps and a vm provisioning, I'm updating my inventory so then some other steps can be performed on that vm.

For this particular scenario, `add_host` or an inventory plugin and a call to `meta: refresh_inventory` would be much better than inserting lines into a static inventory file.

To discuss this further, please reach out on IRC or the mailing list:

   * IRC: #ansible-devel on irc.libera.chat  
   * mailing list: https://groups.google.com/forum/#!forum/ansible-devel
