### ISSUE TITLE
Union of lists of dicts vars doesn't work

### ISSUE THREAD

**Issue by gitaarik** [ansible/ansible#7495]
##### Issue Type:

Bug Report
##### Ansible Version:

1.5.5
##### Environment:

OS/X Mavericks
##### Summary:

Using the jinja2 `union` filter to combine two lists doesn't work if the two lists contain dictionaries. 
##### Steps To Reproduce:

You can use the jinja2 `union` filter to combine two lists like this:

```
list1:
  - item1
  - item2

list2:
  - item3
  - item4

list3: "{{ list1 | union(list2) }}"
```

http://docs.ansible.com/playbooks_variables.html#set-theory-filters

However, when you try this with lists of dicts, it doesn't work, the `list3` variable seems to become a list of string objects and not dict objects:

```
list1:
  - name: item1
    value: test1
  - name: item2
    value: test2

list2:
  - name: item3
    value: test3
  - name: item4
    value: test4

list3: "{{ list1 | union(list2) }}"
```
##### Expected Results:

A list of dictionaries that have the items of the two other lists.
##### Actual Results:

A list of strings. Not sure what's in these strings to be honest, Ansible just gave the error: `One or more undefined variables: 'str object' has no attribute 'value'`.

**Comment by mpdehaan** [comment]
Seems like you should assign this to a variable.

If you use it straight in a file like you seem to be doing, I'm not sure because of the weird "=" syntax, it's going to wind up a string in that file.

You probably need to show more context about how you are using this variable, but Jinja2 union is Jinja2, not ansible.

Perhaps stop by ansible-project to ask the "how do I do this" question, vs filing the bug?

Thanks!

**Comment by bcoca** [comment]
union is a ansible jinja2 filter, it was never meant to work with
dictionaries, it works with lists/sets.

**Comment by gitaarik** [comment]
@mpdehaan Sorry, the `=` was a mistake in the example, corrected it.
@bcoca Ok, union is meant for lists only, is there a way to union dictionaries? If no, are there plans to add this feature? If no, could I maybe make an attempt to add it and make a pull request?

**Comment by bcoca** [comment]
doing set theory on sets is easy, doing it on stuff that is not sets ....

you actually want a dictionary merge, which is not something python/jinja
have built in but should not be hard to code.

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by gitaarik** [comment]
@bcoca It's not a dictionary merge, it's a merge of 2 lists of which the items are dictionaries.

**Comment by bcoca** [comment]
ah, misread that, that should work, got confused, thought they were dicts,
not a list of dicts​. Will give this a look tonight.

**Comment by bcoca** [comment]
tested, this is a result of the stringification that jinja2 does with print
({{ }}) and/or filters (|), for the first case I also get 'set()', solved
by appending |list (list3 = "{{ list1 | union(list2)|list }}").

it does not work with lists of dicts as the stringification breaks the set
functions which cannot deal with complex data elements. But if you do this
directly (not doing the filter) it works:

   list3={{ union(list1, list2) }}

​

**Comment by gitaarik** [comment]
Doesn't seem to work in my vars file, I tried this:

```
list3: "{{ union(list1, list2) }}"
```

But I still get the same result.

**Comment by gitaarik** [comment]
Sorry, this might be a different bug which gave the same error message.... I'm gonna test it again, just a minute.

**Comment by bcoca** [comment]
Tested it in play's vars entry and directly composing in task, vars files
should works the same way

Brian Coca

**Comment by gitaarik** [comment]
Just tested it again and it indeed doesn't work for me, get the same error (`'str object' has no attribute 'value'`).

I'm testing it in `vars/main.yml` in a role.

**Comment by gitaarik** [comment]
Just tested it in a playbook and I also don't manage to make it work:

```
---

- hosts: all
  name: Test
  user: root
  tasks:
    - name: test thingy
      file:
        path: /tmp/test-{{ item.name }}
        state: file
      with_items: list3
  vars:
    list1:
      - name: item1
        value: test1
      - name: item2
        value: test2
    list2:
      - name: item3
        value: test3
      - name: item4
        value: test4
    list3: "{{ union(list1, list2) }}"
```
