### ISSUE TITLE
unarchive hangs Ansible when trying to calculate a diff of a zip file

### ISSUE THREAD

**Issue by jorhett** [ansible/ansible#74955]
### Summary

This hangs on every platform I've tested it on

```yaml
  - name: Unzip aws installer
      unarchive:
        remote_src: yes
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ tmpdir_created.path }}"
```

Output:

```
<ubuntu-2004-awscli> EXEC ['/usr/local/bin/docker', b'exec', b'-u', 'ansible', b'-i', 'ubuntu-2004-awscli', '/bin/sh', '-c', "/bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1623266582.851507-36880-82561418057695/ /home/ansible/.ansible/tmp/ansible-tmp-1623266582.851507-36880-82561418057695/AnsiballZ_unarchive.py && sleep 0'"]
<ubuntu-2004-awscli> EXEC ['/usr/local/bin/docker', b'exec', b'-u', 'ansible', b'-i', 'ubuntu-2004-awscli', '/bin/sh', '-c', "/bin/sh -c 'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin /usr/bin/python3 /home/ansible/.ansible/tmp/ansible-tmp-1623266582.851507-36880-82561418057695/AnsiballZ_unarchive.py && sleep 0'"]
<ubuntu-2004-awscli> EXEC ['/usr/local/bin/docker', b'exec', b'-u', 'ansible', b'-i', 'ubuntu-2004-awscli', '/bin/sh', '-c', "/bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1623266582.851507-36880-82561418057695/ > /dev/null 2>&1 && sleep 0'"]
changed: [ubuntu-2004-awscli] => {
    "changed": true,
    "dest": "/tmp/awscli_installer5a2wg6zt",
    "diff": {
^C
Aborted!
```

That CTRL-C was HOURS later fyi. Nothing is running inside the docker container, and the `rm` command finished. This is a logic problem for determining the diff result, which isn't relevant for this usage (new directory).

Besides fixing the bug can we disable the diff?

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
$ ansible --version
ansible 2.10.9
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Target node is Ubuntu 20.04 -- docker container in the example shown above from `molecule -vvvv`

### Steps to Reproduce

```yaml (paste below)
  - name: Unzip aws installer
      unarchive:
        remote_src: yes
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ tmpdir_created.path }}"
```

### Expected Results

File in unarchived and task returns.

### Actual Results

```console
File is unarchived, ssh connection to remote node finishes, but task never returns.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
