### ISSUE TITLE
Generate word-based passwords

### ISSUE THREAD

**Issue by PeterNerlich** [ansible/ansible#74974]
### Summary

<details><summary>For the <i>Why</i> of word based passwords, allow me to refer to <a href="https://xkcd.com/936/" target="_blank">xkcd 936</a>:</summary>
<img src="https://imgs.xkcd.com/comics/password_strength.png">
</details>

I think this might be a useful extension of the [password lookup plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py) *(implementation probably also in [utils/encrypt.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/encrypt.py))*. While it is not important for credentials only used for autonomous communication between two systems/programs (without humans needing to know it), I got to the point where I also want to use it to set a password that is to be relayed to human actors for their use *(in my case [mailboxes on uberspace](https://manual.uberspace.de/mail-mailboxes/#changing-passwords), which does not allow changing passwords without also having access to the whole account)*. I do not know whether this is common or bad practice and am curious for your input.
As I propose adding this as additional options, no existing workflows would be broken.

An implementation of this requires a few considerations first, which I myself have no definite opinion on yet:
While the implementation for random characters is straightforward, generating word-based passwords requires the system to know a list of possible words to choose from (the dictionary). Introducing this will quickly raise the question for many language specific dictionaries, I expect. While specifying custom dictionaries should definitely be one option for this functionality, it should not be expected just because someone doesn't want his passwords in English. Furthermore, it is not trivial anymore to ensure a certain password strength as the words chosen from the dictionary differ in length.
I did a quick search for python packages that could be integrated or studied for reference and found [passwdgen](https://github.com/thanethomson/passwdgen). I do not have the knowledge to ensure this library is as safe as the current character-based implementation and doesn't open up huge security issues. 

### Issue Type

Feature Idea

### Component Name

password

### Additional Information

```yaml
- name: Generate easy to remember password using builtin German dictionary
  set_fact:
    easy_pw: "{{ lookup('password', '/dev/null words=de length=4 seperator=- capitalization=keep') }}"
    # something like "unglaublich-Feder-Ohnmacht-laufen"
    # note that "length" specifies the number of words now. But we could also name it "word-count"

- name: Generate questionable password from a custom dictionary
  set_fact:
    easy_pw: "{{ lookup('password', '/dev/null words=dictionaries/buzzwords.txt length=4 seperator=. capitalization=lower') }}"
    # something like "html.ai.5g.cloud"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
