### ISSUE TITLE
Role argument specification should support "mutually_exclusive", "required_if" and the other Module argument specification features

### ISSUE THREAD

**Issue by Rylon** [ansible/ansible#74995]
### Summary

I'm trying to replace a series of validation tasks from several of our bigger Ansible roles, to use the new [role argument specification](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-argument-validation) but we have some arguments that are only required if a parameter is set to a specific value (required_if) and some others which should not be set if certain parameters are (mutually_exclusive).

For a module this is possible through the [module argument spec](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec), but not for a role.

I think it would be really useful to support the same options for both module specifications and role specifications?

### Issue Type

Feature Idea

### Component Name

role

### Additional Information

Some of our roles configure software that can be operated in one or more different configurations, with some parameters which are mutually exclusive. We rely on an assertion task like so:

```yaml (paste below)
- name: Validate mutually exclusive parameters
  assert:
    that:
      - param2 is not defined
      - param3 is not defined
      - param4 != "something"
    msg: "param2 and param3 must not be defined when param1 is set. param4 must not be 'something' when param2 and param3 are defined."
  when: param1 is defined
```

If we could define these relationships directly in the role argument spec, it would avoid the need to write our own validation as part of the tasks file for the role.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
