### ISSUE TITLE
import_playbook does not work with vars: for playbook - Inline vars work perfectly

### ISSUE THREAD

**Issue by PrismaComputer** [ansible/ansible#75065]
### Summary

import_playbook does not work with vars: for playbook. From documentation:

```
- name: Set variables on an imported playbook
  import_playbook: otherplays.yml
  vars:
    service: httpd
```

> ERROR! Vars in import_playbook must be specified as a dictionary, or a list of dictionaries

But inline vars work perfectly.
```
- name: Set variables on an imported playbook
  import_playbook: otherplays.yml service=httpd
```

### Issue Type

Bug Report

### Component Name

import_playbook

### Ansible Version

```console
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
```

### Configuration

```console
<NULL>
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```
- name: Set variables on an imported playbook
  import_playbook: otherplays.yml
  vars:
    service: httpd
```

### Expected Results

No error.

### Actual Results

```console
> ERROR! Vars in import_playbook must be specified as a dictionary, or a list of dictionaries
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/import_playbook.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_playbook.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I cannot reproduce the issue:
```
% cat ../ansible-issues/75065.yml
- name: Set variables on an imported playbook
  import_playbook: 75065-playbook.yml
  vars:
    service: httpd
```
```
% cat ../ansible-issues/75065-playbook.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        var: service
```
```
% ansible --version
ansible 2.9.6
  config file = /Users/mkrizek/src/ansible/ansible.cfg
  configured module search path = ['/Users/mkrizek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mkrizek/src/ansible/lib/ansible
  executable location = /Users/mkrizek/.pyenv/versions/ansible-py394/bin/ansible
  python version = 3.9.4 (default, Apr  7 2021, 08:14:18) [Clang 12.0.0 (clang-1200.0.32.28)]
```
```
% ansible-playbook ../ansible-issues/75065.yml

PLAY [localhost] *********************************************************************************************************************************************

TASK [debug] *************************************************************************************************************************************************
ok: [localhost] => {
    "service": "httpd"
}

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

What am I doing differently?

needs_info
