### ISSUE TITLE
Add z/OS prompt to SU_PROMPT_LOCALIZATIONS

### ISSUE THREAD

**Issue by ddimatos** [ansible/ansible#75077]
### Summary

Unlike most operating systems that have keyword `password` at the prompt for privilege escalation, the Unix System Services (USS) on the z/OS operating system prompt is actually `FSUM5019 Enter the password for IBMUSER: `. 

I would like to add the keyword [FSUM5019](https://www.ibm.com/docs/en/zos/2.4.0?topic=fsum-fsum5019) to the [SU_PROMPT_LOCALIZATIONS](https://github.com/ansible/ansible/blob/c404a9003fbfc56785d32e3f6e6ab005d0467927/lib/ansible/plugins/become/su.py#L99) list. Doing so will save many developers time diagnosing and trouble shooting why they are getting a timeout when Ansible is not designed to expect such a prompt and thus needing to be statically added to ansbibe.cfg with `localized_prompts`. 

I have added this and tested this very simple change in both Ansible 2.10 and 2.11 with success in conjunction with the bug I have reported in [git issue 75076](https://github.com/ansible/ansible/issues/75076).

The change is simple, append 'FSUM5019' to:
```
    SU_PROMPT_LOCALIZATIONS = [
        'Password',
        '암호',
        'パスワード',
        'Adgangskode',
        'Contraseña',
        'Contrasenya',
        'Hasło',
        'Heslo',
        'Jelszó',
        'Lösenord',
        'Mật khẩu',
        'Mot de passe',
        'Parola',
        'Parool',
        'Pasahitza',
        'Passord',
        'Passwort',
        'Salasana',
        'Sandi',
        'Senha',
        'Wachtwoord',
        'ססמה',
        'Лозинка',
        'Парола',
        'Пароль',
        'गुप्तशब्द',
        'शब्दकूट',
        'సంకేతపదము',
        'හස්පදය',
        '密码',
        '密碼',
        '口令',
        'FSUM5019',
    ]
```

### Issue Type

Feature Idea

### Component Name

ansible.builtin.su

### Additional Information

```yaml (paste below)

    - name: Who are we on the z/OS target with privilege escalation
      command: whoami
      become: yes
      become_method: su
      become_user: omvsadm
      register: result

    - name: Who did we run as
      debug:
        var: result
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
