### ISSUE TITLE
ansible galaxy - ERROR! Unexpected Exception, this is probably a bug: 'bool' object is not subscriptable 

### ISSUE THREAD

**Issue by JulianDroste** [ansible/ansible#75103]
### Summary

Whenever I try to upgrade Ansible roles within a given directory (with the -p option) with ansible-galaxy the process gets aborted with the error message above.

### Issue Type

Bug Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default,
Jan 26 2021, 15:33:00) [GCC 8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.2]
  config file = /home/juliandroste/ansible/ansible.cfg
  configured module search path = ['/home/juliandroste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/juliandroste/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 2.11.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default,
Jan 26 2021, 15:33:00) [GCC 8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
COLLECTIONS_PATHS(/home/juliandroste/ansible/ansible.cfg) = ['/home/juliandroste/ansible/collections']
DEFAULT_BECOME(/home/juliandroste/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/juliandroste/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/juliandroste/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/juliandroste/ansible/ansible.cfg) = root
DEFAULT_HOST_LIST(/home/juliandroste/ansible/ansible.cfg) = ['/home/juliandroste/ansible/hosts']
DEFAULT_LOG_PATH(/home/juliandroste/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/home/juliandroste/ansible/ansible.cfg) = Ansible managed: modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_REMOTE_USER(/home/juliandroste/ansible/ansible.cfg) = cert
DEFAULT_ROLES_PATH(/home/juliandroste/ansible/ansible.cfg) = ['/home/juliandroste/ansible/roles', '/home/juliandroste/ansible/roles_c
DEFAULT_VAULT_PASSWORD_FILE(/home/juliandroste/ansible/ansible.cfg) = /home/juliandroste/ansible/vpass
HOST_KEY_CHECKING(/home/juliandroste/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/juliandroste/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-144-generic x86_64) VM behind a corporate proxy

### Steps to Reproduce

```yaml (paste below)
roles:
  - src: robertdebock.rsyslog
    version: 4.0.2
  - src: geerlingguy.postfix
    version: 2.0.0
  - src: geerlingguy.apache
    version: 3.1.0
  - src: riemers.gitlab-runner
    version: v1.6.32
  - src: geerlingguy.ntp
    version: 2.3.0
  - src: cloudalchemy.node_exporter
    version: 2.0.0
  - src: cloudalchemy.prometheus
    version: 4.0.0
  - src: cloudalchemy.alertmanager
    version: 0.19.1
  - src: geerlingguy.docker
    version: 3.1.2
  - src: geerlingguy.pip
    version: 2.1.0
  - src: sbaerlocher.wmi_exporter
    version: 1.3.0
  - src: jnv.unattended-upgrades
    version: v1.11.0
  - src: geerlingguy.elasticsearch
    version: 5.0.1
  - src: geerlingguy.java
    version: 1.10.0
  - src: cloudalchemy.mysqld_exporter
    version: 1.0.0
```
ansible-galaxy install -r requirements.yml -p ./roles

### Expected Results

I would expect the roles to get updated smoothly

### Actual Results

```console
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default,
Jan 26 2021, 15:33:00) [GCC 8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
ansible-galaxy [core 2.11.2]
  config file = /home/juliandroste/ansible/ansible.cfg
  configured module search path = ['/home/juliandroste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/juliandroste/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 2.11.2
  libyaml = True
Using /home/juliandroste/ansible/ansible.cfg as config file
Opened /home/juliandroste/.ansible/galaxy_token
Starting galaxy role install process
Processing role robertdebock.rsyslog
ERROR! Unexpected Exception, this is probably a bug: 'bool' object is not subscriptable
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
