### ISSUE TITLE
docker_image username and password support

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/ansible#75105]
### Summary

I am trying to pull images from a private azure container registry. This however requires azure authentication or using username and password via docker login and the command module. 

This feature is really missing from the module. 

### Issue Type

Feature Idea

### Component Name

docker_image 

### Additional Information

```yaml (paste below)
 name: pull latest powershell image
  docker_image:
    name: myprivateregistry.azurecr.io/powershell
    source: pull
    force_source: yes
    username: myprivateregistry.azurecr.io
    password: mypassword
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
