### ISSUE TITLE
Ansible hangs up when execute obtain the volumn size

### ISSUE THREAD

**Issue by kakascx** [ansible/ansible#75111]
### Summary

I used the playbook to extend the volume size of a 7 node cluster.The step of playbook is:
1. Find the last unpartitioned drive character
2. Create a new primary partition on pvname
3. Extend the volume groups
4. Extend the logical volume to consume all remaining space in the volume group
5. Resizefs a ext4 filesystem
6. obtain the size of volume group

There were only 2 node of the cluster execute the playbook successfully, but hang up on other nodes.
There were no logs ,just hang up to wait for time out

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible 2.6.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/module']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/module']
```

### OS / Environment

Ubuntu 18.04.3

### Steps to Reproduce

```yaml (paste below)
---
- name: Find the last unpartitioned drive character
  shell: |
    #!/bin/bash
    get_new_disk() {
      for d in `lsblk -n -d -o name`
      do
        blkid "/dev/$d">/dev/null
        if [ $? -ne 0 ];then
          echo "/dev/$d"
        fi
      done
    }
    for i in {1..1200}
    do
      unparted_dev=`get_new_disk`
      if [ -n "$unparted_dev" ];then
        echo "${unparted_dev}"
        exit 0
      fi
      sleep 1
    done
    echo "Unparted disk not found"
    exit 1

  args:
    executable: /bin/bash
  register: pvname
  
- name: Create a new primary partition on pvname
  parted:
    device: "{{ item }}"
    number: 1
    state: present
  when: pvname is defined
  with_items: "{{ pvname.stdout_lines }}"
    
- name: Extend the volume groups
  shell: |
    #!/bin/bash
    vg_name=`pvs | grep "{{ item }}1" | awk '{print $2}'`
    if [ ! "vg-myVolume" = "${vg_name}" ];then
      vgextend vg-myVolume"{{ item }}1"
    fi
  when: pvname is defined
  with_items: "{{ pvname.stdout_lines }}"

- name: Extend the logical volume to consume all remaining space in the volume group
  lvol:
    vg: vg-myVolume
    lv: lv-myVolume
    size: +100%FREE

- name: Resizefs a ext4 filesystem on /dev/vg-myVolume/lv-myVolume
  filesystem:
    fstype: ext4
    dev: /dev/vg-myVolume/lv-myVolume
    resizefs: true

- name: Extend the volume groups
  shell: |
    #!/bin/bash
    volumeSize=$(df /data -B G |grep myVolume|awk '{print $2}')
    echo $volumeSize
  register: volumeSize

```

### Expected Results

return the externed volume size

### Actual Results

```console
hang up during the last step
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
