### ISSUE TITLE
ansible cant create SATA controller in ESXi VM

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [ansible/ansible#75133]
### Summary

Hey, i am trying to create a VM in ESXi with ansible but everytime i create a SATA controller and try to add the ISO nothing happens. The VM is created but without the SATA controller and without ISO.

I tried with IDE and it works, but i cant make it work with sata

### Issue Type

Bug Report

### Component Name

vmware_guest

### Ansible Version

```console
$ ansible --version
2.9.6
```

### Configuration

```console
$ ansible-config dump --only-changed
empty
```

### OS / Environment

Linux MInt 20 Cinnamon 4.6.7

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    vmware_guest:
      hostname: "host"
      username: "user"
      password: "password"
      validate_certs: False
      folder: /ha-datacenter/vm
      name: VM-TESTE
      state: present
      guest_id: ubuntu64Guest
      esxi_hostname: "some_host"
      disk:
      - size_gb: 10
        type: thin
        datastore: "HDD_2"
      hardware:
        memory_mb: 512
        num_cpus: 4
        scsi: lsilogicsas
      cdrom:
        - controller_type: sata
          controller_number: 0
          unit_number: 0
          type: iso
          iso_path: "[HDD_2]  ubuntu-20.04.1-live-server-amd64.iso"
      networks:
      - name: VM Network
        type: static
        start_connected: true
    delegate_to: localhost
    register: deploy_vm
```

### Expected Results

I expected a VM with a SATA controler with CD/DVD connected with my ubuntu iso to be created in ESXi

### Actual Results

```console
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/brun0/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: ola.yml ******************************************************************************************************************************************************
1 plays in ola.yml

PLAY [localhost] *******************************************************************************************************************************************************
META: ran handlers

TASK [Create a virtual machine on given ESXi hostname] *****************************************************************************************************************
task path: /home/brun0/ansible_stuff/ola.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: brun0
<localhost> EXEC /bin/sh -c 'echo ~brun0 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607 `" && echo ansible-tmp-1624905903.6090083-102222042852607="` echo /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /home/brun0/.ansible/tmp/ansible-local-9122351fl4r6g/tmpg36nux1v TO /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607/AnsiballZ_vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607/ /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607/AnsiballZ_vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/brun0/.ansible/tmp/ansible-tmp-1624905903.6090083-102222042852607/ > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "0",
        "hw_cluster": null,
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "HDD_2"
        ],
        "hw_esxi_host": "esxi_hostname",
        "hw_eth0": {
            "addresstype": "generated",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": null,
            "macaddress_dash": null,
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "VM Network"
        },
        "hw_files": [
            "[HDD_2] VM-TESTE/VM-TESTE.vmx",
            "[HDD_2] VM-TESTE/VM-TESTE.vmsd",
            "[HDD_2] VM-TESTE/VM-TESTE.vmdk"
        ],
        "hw_folder": "/ha-datacenter/vm",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": null,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 512,
        "hw_name": "VM-TESTE",
        "hw_power_status": "poweredOff",
        "hw_processor_count": 4,
        "hw_product_uuid": "564dfda3-3b33-cbd3-3635-598ec1e96fd6",
        "hw_version": "vmx-14",
        "instance_uuid": "520fa2d9-238d-f952-b1e6-9a207e9b03aa",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "moid": "32",
        "snapshots": [],
        "vimref": "vim.VirtualMachine:32",
        "vnc": {}
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": [
                {
                    "controller_number": 0,
                    "controller_type": "sata",
                    "iso_path": "[HDD_2]  ubuntu-20.04.1-live-server-amd64.iso",
                    "state": "present",
                    "type": "iso",
                    "unit_number": 0
                }
            ],
            "cluster": null,
            "convert": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "ha-datacenter",
            "datastore": null,
            "disk": [
                {
                    "datastore": "HDD_2",
                    "size_gb": 10,
                    "type": "thin"
                }
            ],
            "esxi_hostname": "esxi_hostname",
            "folder": "/ha-datacenter/vm",
            "force": false,
            "guest_id": "ubuntu64Guest",
            "hardware": {
                "memory_mb": 512,
                "num_cpus": 4,
                "scsi": "lsilogicsas"
            },
            "hostname": "hostname",
            "is_template": false,
            "linked_clone": false,
            "name": "VM-TESTE",
            "name_match": "first",
            "networks": [
                {
                    "name": "VM Network",
                    "start_connected": true,
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "state_change_timeout": 0,
            "template": null,
            "use_instance_uuid": false,
            "username": "",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_customization": false,
            "wait_for_ip_address": false
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
