### ISSUE TITLE
apt module boolean param to select --user

### ISSUE THREAD

**Issue by staticdev** [ansible/ansible#75144]
### Summary

Currently the apt module does not have a `user` param for install. Which would be equivalent to `apt install --user`.

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information

The idea is to have something like:

```yaml (paste below)
- name: Install packages only when the apt process is not locked
  apt:
    name: foo
    state: present
    user: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
