### ISSUE TITLE
Dumped YAML Inventory is unparseable

### ISSUE THREAD

**Issue by dziebart** [ansible/ansible#75162]
### Summary

When trying to parse a dynamically constructed inventory as a YAML-file, the resulting file can not be parsed to reconstruct the inventory.
```
    def _write_cache_to_custom_path(self):
        inventory_yaml = yaml.dump(self.inventory.serialize(), sort_keys=False)

        try:
            os.remove(self.DEFAULT_PARAMETERS['inventory_cache_path'])
        except OSError:
            pass

        os.makedirs(os.path.dirname(self.DEFAULT_PARAMETERS['inventory_cache_path']), exist_ok=True)
        cache_file = open(self.DEFAULT_PARAMETERS['inventory_cache_path'], 'w')
        cache_file.write(inventory_yaml)
        cache_file.close()
```
This code results in, for example, the following inventory file:
```
groups:
  Storages_dc: !!python/object:ansible.inventory.group.Group
    depth: 0
    hosts: &id001
    - &id003 !!python/object:ansible.inventory.host.Host
      address: storage-1-dc.net.dziebart.env
      groups:
      - depth: 0
        hosts: *id001
        name: Storages_dc
        parent_groups: []
        vars: {}
      implicit: false
      name: storage-1-dc.net.dziebart.env
      uuid: c9a44722-d50f-88e1-98a5-000000000001
      vars:
        ansible_connection: ssh
        ansible_ssh_user: root
        datacenter_code: dc
        datacenter_id: 1
        datacenter_name: dc
        datacenter_network: '10.20'
        inventory_dir: /home/management/ansible-dynamic-inventory
        inventory_file: /home/management/ansible-dynamic-inventory/inventory_cfg.yml
        network_available: false
        network_type: address
        storage_hostname: storage-1-dc.net.dziebart.env
        storage_id: 1
    name: Storages_dc
    parent_groups: []
    vars: {}
  all: !!python/object:ansible.inventory.group.Group
    depth: 0
    hosts: &id002 []
    name: all
    parent_groups: []
    vars: {}
  ungrouped: !!python/object:ansible.inventory.group.Group
    depth: 1
    hosts: []
    name: ungrouped
    parent_groups:
    - depth: 0
      hosts: *id002
      name: all
      parent_groups: []
      vars: {}
    vars: {}
hosts:
  storage-1-dc.net.dziebart.env: *id003
local: null
processed_sources: []
source: /home/management/ansible-dynamic-inventory/inventory_cfg.yml

```
Now trying to read the resulting file using the pyyaml like this:
```
    def _load_cache_from_custom_path(self):
        if not os.path.exists(self.DEFAULT_PARAMETERS['inventory_cache_path']):
            return None

        cache_file = open(self.DEFAULT_PARAMETERS['inventory_cache_path'], 'r')

        try:
            # inventory_yaml = yaml.safe_load(cache_file.read())
            inventory_yaml = yaml.load(cache_file.read(), Loader=yaml.FullLoader)
            cache_file.close()
        except yaml.YAMLError as exc:
            print(str(exc))
            print("Could not read cache file. Generating new Inventory.")
            return None

        return inventory_yaml
```
Results in the following error:
```
could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:ansible.inventory.group.Group'
  in "<unicode string>", line 2, column 16:
      Storages_dc: !!python/object:ansible.inventor ... 
                   ^
```
The same error also appeared for the `hosts` tag.
I tried the same using `ansible.parsing.yaml.loader` and `ansible.parsing.yaml.dumper` but the same error was thrown.
My current only go-to solution was to write a constructor for the tags, like this:
```
        def _host_constructor(loader, node):
            new_host = AnsibleHost.Host("tmp")
            yield new_host
            data = loader.construct_mapping(node, deep=True)
            new_host.name = data['name']
            self.inventory.add_host(data['name'])
            for entry in data['vars']:
                self.inventory.set_variable(data['name'], str(entry), data['vars'][str(entry)])
```
and then connecting the tag with the constructor:
```
yaml.add_constructor(u'tag:yaml.org,2002:python/object:ansible.inventory.host.Host', _host_constructor)
```

Is this problem known or is this the wrong way to save and load an inventory?

### Issue Type

Bug Report

### Component Name

inventory

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.2] 
  config file = /home/management/ansible-dynamic-inventory/ansible.cfg
  configured module search path = ['/home/management/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/management/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_GATHERING(/home/management/ansible-dynamic-inventory/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/management/ansible-dynamic-inventory/ansible.cfg) = ['/home/management/ansible-dynamic-inventory/inventory_cfg.yml']
INVENTORY_CACHE_ENABLED(/home/management/ansible-dynamic-inventory/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN_CONNECTION(/home/management/ansible-dynamic-inventory/ansible.cfg) = /tmp/ansible_inventory
TRANSFORM_INVALID_GROUP_CHARS(/home/management/ansible-dynamic-inventory/ansible.cfg) = ignore
```

### OS / Environment

Ubuntu 18.04.5 LTS

### Steps to Reproduce

```yaml (paste below)
ansible-inventory --graph --vars -vvv
```

### Expected Results

ansible-inventory [core 2.11.2] 
  config file = /home/management/ansible-dynamic-inventory/ansible.cfg
  configured module search path = ['/home/management/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/management/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
Using /home/management/ansible-dynamic-inventory/ansible.cfg as config file
host_list declined parsing /home/management/ansible-dynamic-inventory/inventory_cfg.yml as it did not pass its verify_file() method
script declined parsing /home/management/ansible-dynamic-inventory/inventory_cfg.yml as it did not pass its verify_file() method
Parsed /home/management/ansible-dynamic-inventory/inventory_cfg.yml inventory source with auto plugin
@all:
  |--@Storages_dc:
  |  |--storage-1-dc.net.dziebart.env
  |  |  |--{ansible_connection = ssh}
  |  |  |--{ansible_ssh_user = root}
  |  |  |--{datacenter_code = dc}
  |  |  |--{datacenter_id = 1}
  |  |  |--{datacenter_name = dc}
  |  |  |--{datacenter_network = 10.20}
  |  |  |--{network_available = False}
  |  |  |--{network_id = 41}
  |  |  |--{network_type = address}
  |  |  |--{storage_hostname = storage-1-dc.net.dziebart.env}
  |  |  |--{storage_id = 1}
  |  |  |--{storage_modus = online}
  |--@ungrouped:

### Actual Results

```console
ansible-inventory [core 2.11.2] 
  config file = /home/management/ansible-dynamic-inventory/ansible.cfg
  configured module search path = ['/home/management/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/management/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
Using /home/management/ansible-dynamic-inventory/ansible.cfg as config file
host_list declined parsing /home/management/ansible-dynamic-inventory/inventory_cfg.yml as it did not pass its verify_file() method
script declined parsing /home/management/ansible-dynamic-inventory/inventory_cfg.yml as it did not pass its verify_file() method
could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:ansible.inventory.group.Group'
  in "<unicode string>", line 2, column 16:
      Storages_dc: !!python/object:ansible.inventor ... 
                   ^
Could not read cache file. Generating new Inventory.
Parsed /home/management/ansible-dynamic-inventory/inventory_cfg.yml inventory source with auto plugin
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
