### ISSUE TITLE
Preserve full excludes in find file absent

### ISSUE THREAD

**Issue by KrisLowet** [ansible/ansible#75171]
### Summary

I want to delete all directories and files in a folder, except for some defined directories and folders.
Eg. I have this directory structure:

```text
var/
├─ www/
├─ application/
│  ├─ resources/
│  ├─ routes/
│  ├─ public/
│  │  ├─ libs/
│  │  ├─ index.php
│  │  ├─ logo.png
│  │  ├─ uploads/
│  ├─ storage/
│  │  ├─ app/
│  │  ├─ framework/
│  │  ├─ uploads/
```

I want to delete all folders and files inside /var/www/application _except_ the folders _public/uploads_ and _storage/uploads_

**Problem**
When using the _find_ module I can exclude the directories _public/uploads_ and _storage/uploads_, but both directories _public_ and _storage_ are deleted anyway. I can also exclude both directories _public_ and _storage_, but then the files inside these directories are not deleted (like public/index.php and public/logo.png).

My solution now, is like this:

```yaml
current_app_files: []
app_upgrade_exclude:
  - /var/www/application/.env
  - /var/www/application/public
  - /var/www/application/public/uploads
  - /var/www/application/storage
  - /var/www/application/storage/uploads

- name: Register all files and directories in app folder.
  find: 
    paths: /var/www/application
    file_type: any
    recurse: yes
    hidden: yes
    depth: 2
  register: all_app_files

- name: Set fact for all current files.
  set_fact: 
    current_app_files: "{{ current_app_files + [item.path] }}"
  loop: "{{ all_app_files.files }}"

- name: Set fact for all files to remove, exclude the client uploads.
  set_fact:
    files_to_remove: "{{ current_app_files | difference(app_upgrade_exclude) }}"

- name: Remove old files.
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_remove }}"
```

### Issue Type

Feature Idea

### Component Name

find, file

### Additional Information

Best solution should be to adding an option or change to the _file_ module so that _excludes_ can contain full paths and that these paths be preserved.

Like in my example, that I can use something like this:

```yaml
- name: Register all files and directories in app folder.
  find: 
    paths: /var/www/application
    file_type: any
    excludes:
      - /var/www/application/.env
      - /var/www/application/public
      - /var/www/application/public/uploads
      - /var/www/application/storage
      - /var/www/application/storage/uploads
  register: files_to_remove

- name: Remove old files.
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ files_to_remove }}"
```

And that full directories like _/var/www/application/public/uploads_ are preserved.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
