### ISSUE TITLE
Handler in role that's executed multiple times only gets executed once

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#75175]
### Summary

If you have a role that's included multiple times in the playbook but with different variables, and a task inside it is changed, the handler only runs once but it should run twice and use the different sets of variables passed to it from the role.

### Issue Type

Bug Report

### Component Name

handler

### Ansible Version

```console
$ ansible --version

ansible [core 2.11.2]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

linux

### Steps to Reproduce

In playbook

```yaml (paste below)
roles:
  - role: name
    arg: value1
  - role: name
    arg: value2
```

In handler

```yaml
- name: run_handler
  module:
    modulevar: "{{ arg }}"
```

### Expected Results

The handler should run twice, once with `value1` passed to as the variable and again with `value2` passed as the variable.

### Actual Results

```console
It only runs once.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
