### ISSUE TITLE
Add specific cron job env for cron module

### ISSUE THREAD

**Issue by hungpr0** [ansible/ansible#75181]
### Summary

Hello,

Currently the `cron` supports only 1 `env` on top. I want to have this setup. Different job will have different `MAILTO` `env`

```

#Ansible: TEST 1
MAILTO=person1@domain.com
0 * * * * ls -lah > /dev/null

#Ansible: TEST 2
MAILTO=person2@domain.com
1 * * * * ls -ahl > /dev/null

```
with 
```
  tasks:
    - name: "1"
      cron:
        env: true
        name: MAILTO
        job: person1@domain.com
        state: "present"
        insertbefore: "TEST 1"
    - name: "2"
      cron:
        name: "TEST 1"
        job: "ls -lah > /dev/null"
        state: "present"
        minute: "0"
        hour: "5,2"
    - name: "3"
      cron:
        env: true
        name: MAILTO
        job: person2@domain.com
        state: "present"
        insertbefore: "TEST 2"
    - name: "4"
      cron:
        name: "TEST 2"
        job: "ls -ahl > /dev/null"
        state: "present"
        minute: "1"
        hour: "4,2"`

```
we will have

```
MAILTO="person2@domain.com"
MAILTO="person2@domain.com"
#Ansible: TEST 1
0 5,2 * * * ls -lah > /dev/null
#Ansible: TEST 2
1 4,2 * * * ls -ahl > /dev/null

```

Can we add a new `cron.job_env`? It will be inserted after `#Ansible: job_name` and before `job`

Similar issue detail is on https://stackoverflow.com/questions/64285237/ansbile-way-of-having-multiple-mailto-environment-varialbes-in-crontab

### Issue Type

Feature Idea

### Component Name

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cron.py

### Additional Information
Can we add a new `cron.job_env`? It will be inserted after `#Ansible: job_name` and before `job`

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
