### ISSUE TITLE
synchronize module hangs indefinitely between 2 remote hosts

### ISSUE THREAD

**Issue by nomadme** [ansible/ansible#75201]
### Summary

The synchronize module hangs indefinitely when trying to synchronize dirs and files between two remote hosts with the delegate_to option.

### Issue Type

Bug Report

### Component Name

synchronize

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.0]
  config file = None
  configured module search path = ['/Users/XXXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.0.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/XXXXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = ['/Users/XXXX/.ansible']
```

### OS / Environment

macOS Catalina
Version 10.15.7

### Steps to Reproduce

```yaml (paste below)
- name: Distribute files
      synchronize:
        src: /home/local/XXXX/FOO/
        dest: /home/local/XXXX/FOO/
      delegate_to: "server-A"
      become_user: XXXX
      when: "'dev' not in inventory_hostname"
      tags: production-dist-files-test
```

### Expected Results

FOO dir copied/synced to the server-N from server-A

### Actual Results

```console
________________________________ 
< TASK [Distribute files] >
 -------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [server-A -> None]
....

and hangs until user interruption
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
