### ISSUE TITLE
Systemd returns that it is "changed" on every run

### ISSUE THREAD

**Issue by tuxonfire** [ansible/ansible#75208]
### Summary

When using the systemd module in a playbook returns that it is "changed" on every run. 

### Issue Type

Bug Report

### Component Name

systemd

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
```

### OS / Environment

RHEL7

### Steps to Reproduce

Running the following playbook Systemd returns that it is "changed" every time that the playbook run.

```yaml (paste below)
    - name:  Disable the rhnsd Daemon
      ansible.builtin.stat:
        path: /etc/rc.d/init.d/rhnsd
      register: rhnsd_status
      check_mode: no

    - name:  Disable the rhnsd Daemon
      systemd:
        name: rhnsd
        state: stopped
        enabled: no
        masked: yes
      when: rhnsd_status.stat.exists == true
```

### Expected Results

Systemd returns that it is "changed" on every run on the playbook even if the task was done before, expected not to change if is already changed.

### Actual Results

```console
systemd returned changed every run in a playbook:

[vagrant@atower vagrant_data]$ ansible-playbook main.yml 

PLAY [all] *********************************************************************************************************************************************************

TASK [Disable the rhnsd Daemon] ************************************************************************************************************************************
ok: [10.10.17.20]

TASK [Disable the rhnsd Daemon] ************************************************************************************************************************************
changed: [10.10.17.20]

PLAY RECAP *********************************************************************************************************************************************************
10.10.17.20                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[vagrant@atower vagrant_data]$ ansible-playbook main.yml 

PLAY [all] *********************************************************************************************************************************************************

TASK [Disable the rhnsd Daemon] ************************************************************************************************************************************
ok: [10.10.17.20]

TASK [Disable the rhnsd Daemon] ************************************************************************************************************************************
changed: [10.10.17.20]

PLAY RECAP *********************************************************************************************************************************************************
10.10.17.20                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
