### ISSUE TITLE
ansible hangs at end of large loop when loop_control extended is enabled

### ISSUE THREAD

**Issue by Hipska** [ansible/ansible#75216]
### Summary

When ansible(-playbook) iterates over a very large list (3700 items in my case), it hangs after processing the last item, cpu usage goes to 100% and memory usage rises until the process gets killed by linux OOM-killer.

This happens when I enable the `extended` option of `loop_control`, but does not happen on small lists (10 items).

### Issue Type

Bug Report

### Component Name

loop_control

### Ansible Version

```console
$ ansible --version
ansible 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/xxxx/playbooks/ansible.cfg) = True
DEFAULT_BECOME_EXE(/home/xxxx/playbooks/ansible.cfg) = sudo su -
DEFAULT_BECOME_METHOD(/home/xxxx/playbooks/ansible.cfg) = su
DEFAULT_HOST_LIST(/home/xxxx/playbooks/ansible.cfg) = [u'/home/xxxx/playbooks/hosts']
DEFAULT_REMOTE_USER(/home/xxxx/playbooks/ansible.cfg) = ansible
DISPLAY_SKIPPED_HOSTS(/home/xxxx/playbooks/ansible.cfg) = False
```

### OS / Environment

- **OS**: `Red Hat Enterprise Linux Server release 7.4 (Maipo)`
- **CPU**: `Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz`
- **Mem**: `16GB`

### Steps to Reproduce

This is the problematic playbook task:
```yaml
- name: Install network devices configuration files
  template:
    src: telegraf-device.toml.j2
    dest: "{{telegraf_include_dir}}/{{item.hostname}}.conf"
    owner: telegraf
    group: telegraf
  loop: "{{large_list_of_devices}}"
  loop_control:
    index_var: index
    extended: yes
    label: "{{item.hostname}} - {{item.address}}"
  when: true # redacted the condition, not sure if it is relevant
  register: managed_device_configs
  notify: reload telegraf
```

### Expected Results

I expect ansible to be able to iterate over this large list with `extended` enabled and continue to the next task after the last item.

### Actual Results

```console
...
TASK [xxxxx] *********************************************************************************************
ok: [xxxx] => (item=XXXXX - xxx.xxx.xxx.xxx)
ok: [xxxx] => (item=XXXXX - xxx.xxx.xxx.xxx)
....
changed: [xxxx] => (item=XXXXX - xxx.xxx.xxx.xxx)
ok: [xxxx] => (item=XXXXX - xxx.xxx.xxx.xxx)
ok: [xxxx] => (item=XXXXX - xxx.xxx.xxx.xxx)
NOTIFIED HANDLER xxxx for xxxx
Killed
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/loop_control.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/loop_control.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Hipska** [comment]
When not running with `-vvv`, I got this: 
```console
ERROR! Unexpected Exception, this is probably a bug: [Errno 12] Cannot allocate memory
to see the full traceback, use -vvv
```

**Comment by bcoca** [comment]
The extended option adds a lot of memory overhead, this is why it is off by default.

Leaving this open so we look at ways to minimize this issue.

**Comment by Hipska** [comment]
It only starts hogging memory when it’s hanging at the end…

**Comment by sivel** [comment]
> It only starts hogging memory when it’s hanging at the end

It's a problem with serialization. Inside of the `TaskExecutor` the variables are references, and don't consume as much memory.  But to send the responses back to the controller, the data must be pickled, subsequently dereferencing, making `.results[].ansible_loop.allitems` copies, which each result of 3700 items, all have the 3700 items embedded (that's 13_690_000 loop items in a single task result per host).

Subsequently once back in the controller process, that data is deserialized, so it's in Python all as copies, and then it's JSON serialized for display, which more than doubles the utilized memory of the data structure.

And depending on how many hosts your play is targeting, all that serialized data for that many hosts may be held up in an in memory queue waiting to be processed.  So there become many many many copies of the data held in memory.

**Comment by Hipska** [comment]
Yeah, I was going to mention that `allitems` variable. I saw it being printed in each iteration of the list when doing verbose debug. That doesn’t seem necessary?

**Comment by sivel** [comment]
> That doesn’t seem necessary?

Depends on what you mean.  It's purposefully there as part of `extended` and cannot be removed at this point.

What is your use case for using `loop_control.extended` for this loop?  I don't see it being used within the task itself.

**Comment by Hipska** [comment]
The idea was to show progress in the label. (Item x/y)

**Comment by sivel** [comment]
Could just use:

```yaml
      loop_control:
        label: 'Item {{ index + 1 }}/{{ large_list_of_devices|length }}'
        index_var: index
```

Or with less calculation of length:

```yaml
      loop_control:
        label: 'Item {{ index + 1 }}/{{ all_items_length }}'
        index_var: index
      vars:
        all_items_length: '{{ large_list_of_devices|length }}'
```
