### ISSUE TITLE
Ansible add_host logs credentials in plain to terminal

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#75237]
### Summary

add_host logs credentials in plain to terminal

### Issue Type

Bug Report

### Component Name

add_host

### Ansible Version

```console
$ ansible --version
ansible 2.10.11
  config file = ./ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ./venv/lib/python3.9/site-packages/ansible
  executable location = ./venv/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

ArchLinux

### Steps to Reproduce

```yaml (paste below)
- name: Add VMs to Ansible Inventory
  changed_when: False
  add_host:
    name: '{{ Customer.id }}-{{ item.name }}'
    groups: '{{ vm_groups }}'
    ansible_connection: vmware_tools
    ansible_shell_type: '{{ item.ansible_shell_type }}'
    ansible_vmware_host: '{{ vcenter.hostname }}'
    ansible_vmware_user: '{{ vcenter.username }}'
    ansible_vmware_password: '{{ vcenter.password }}'
    ansible_vmware_validate_certs: '{{ vcenter.validate_certs|default(true) }}'
    ansible_vmware_guest_path: '{{ vcenter.datacenter }}/vm/{{ item.name }}'
    ansible_user: Administrator
    ansible_vmware_tools_user: Administrator
    ansible_vmware_tools_password: '{{ item.ansible_vmware_tools_password }}'

```

### Expected Results

credentials not being logged in plaintext to console

Currently the attributes "ansible_vmware_password" and "ansible_vmware_tools_password" are outputed to the console.

As a workaround "no_log: True" can be used, but this should be fixed nonetheless.

### Actual Results

```console
creating host via 'add_host': hostname=test
ok: [ansible_connection=local] => {"add_host": {"groups": ["test"], "host_name": "test", "host_vars": {"ansible_connection": "vmware_tools", "ansible_shell_type": "powershell", "ansible_user": "Administrator", "ansible_vmware_guest_path": "DC/vm/test", "ansible_vmware_host": "vcenter01.example.com", "ansible_vmware_password": "myPassword", "ansible_vmware_tools_password": "myPassword", "ansible_vmware_tools_user": "Administrator", "ansible_vmware_user": "myUsername", "ansible_vmware_validate_certs": false}}, "changed": false}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
