### ISSUE TITLE
cisco.ios.ios_config does not leave config mode on invalid command

### ISSUE THREAD

**Issue by AliArfan** [ansible/ansible#75241]
### Summary

Hi, 

I stumbled upon this thread  while looking for a solution, and thought it perhaps might be a bug or potential feature request: https://github.com/ansible/ansible/issues/32416. When  an invalid command is issued via the  `cisco.ios.ios_config` module   the playbook will fail, but the device remain in configuration mode. Desired outcome is that the playbook leaves the configuration mode, so the next run of the playbook does not fail when setting the terminal parameters.  

### Issue Type

Bug Report

### Component Name

cisco.ios.ios_config

### Ansible Version

```console
$ ansible --version
ansible 2.10.7
  config file = None
  configured module search path = ['/home/ali/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ali/.cache/pypoetry/virtualenvs/nsansible-playbooks-1psT55Hb-py3.9/lib/python3.9/site-packages/ansible
  executable location = /home/ali/.cache/pypoetry/virtualenvs/nsansible-playbooks-1psT55Hb-py3.9/bin/ansible
  python version = 3.9.4 (default, Apr  9 2021, 01:03:21) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
Empty, no output
```

### OS / Environment

Ubuntu 20.04 (Windows 10 WSL)

### Steps to Reproduce

Playbook to reproduce the problem, where invalid configuration is pushed
```yaml (paste below)
- name: Validate configuration after push
  hosts: "{{ DEVICE }}"
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Push new configuration
      cisco.ios.ios_config:
          lines:
            vrf definition Test description 'Failingcommand'"

```

### Expected Results

Playbook leaves the configuration mode, so the next run does not fail to set terminal parameters.

### Actual Results

```console
Results in the device staying in the configuration mode:

Test-Device(config)#vrf definition Test description 'Failingcommand'"
vrf definition Test description 'Failingcommand'"
                    ^
% Invalid input detected at '^' marker.

Test-Device(config)#
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
