### ISSUE TITLE
cisco.ios.ios_facts can not parse vlans with spaces

### ISSUE THREAD

**Issue by donnerhacke** [ansible/ansible#75261]
### Summary

The action module cisco.ios.ios_facts can not parse vlans with spaces in the name. Cisco IOS and the ios_vlan module itself have no problems with VLAN names containing spaces.

### Issue Type

Bug Report

### Component Name

cisco.ios.ios_facts

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.1]
  config file = /home/iks/.ansible.cfg
  configured module search path = ['/home/iks/.ansible/plugins/modules', '/usr/local/share/py38-ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/iks/.ansible/collections:/usr/local/share/py38-ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 12 2021, 01:13:14) [Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c
  jinja version = 2.11.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/home/iks/.ansible.cfg) = community.general.yaml
CACHE_PLUGIN_CONNECTION(/home/iks/.ansible.cfg) = /home/iks/.ansible/cache/
DEFAULT_GATHERING(/home/iks/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/iks/.ansible.cfg) = ['/home/iks/ansible/hosts']
INTERPRETER_PYTHON(/home/iks/.ansible.cfg) = auto_silent
PLAYBOOK_DIR(/home/iks/.ansible.cfg) = /home/iks/ansible
```

### OS / Environment

FreeBSD 13.0-STABLE  stable/13-n245475-bb9dcbf1a243

### Steps to Reproduce

```yaml (paste below)
- name: Test VLAN Bug
  hosts: switch
  gather_facts: no

  tasks:
    - name: Create VLAN
      ios_vlan:
        vlan_id: 109
        name: test vlan
        state: present

    - name: Validate VLAN
      ios_command:
        commands:
          - show vlan brief | include _109_
      register: res

    - name: Show output
      debug:
         var: res.stdout

    - name: Gather facts
      ios_facts:
        gather_network_resources:
          - vlans

    - name: Show facts
      debug:
         var: ansible_facts.network_resources.vlans |
           selectattr('vlan_id', '==', 109)

    - name: Remove VLAN
      ios_vlan:
        vlan_id: 109
        state: absent
```

### Expected Results

PLAY [Test VLAN Bug] ***********************************************************

TASK [Create VLAN] *************************************************************
changed: [switch]

TASK [Validate VLAN] ***********************************************************
ok: [switch]

TASK [Show output] *************************************************************
ok: [switch] => {
    "res.stdout": [
        "109  test vlan                        active"
    ]
}

TASK [Gather facts] ************************************************************
ok: [switch]

TASK [Show facts] **************************************************************
ok: [switch] => {
    "ansible_facts.network_resources.vlans | selectattr('vlan_id', '==', 109)": [
        {
            "mtu": 1500,
            "name": "test vlan",
            "shutdown": "disabled",
            "vlan_id": 109
        }
    ]
}

TASK [Remove VLAN] *************************************************************
changed: [switch]

PLAY RECAP *********************************************************************
switch    : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

### Actual Results

```console
PLAY [Test VLAN Bug] ***********************************************************

TASK [Create VLAN] *************************************************************
changed: [switch]

TASK [Validate VLAN] ***********************************************************
ok: [switch]

TASK [Show output] *************************************************************
ok: [switch] => {
    "res.stdout": [
        "109  test vlan                        active"
    ]
}

TASK [Gather facts] ************************************************************
ok: [switch]

TASK [Show facts] **************************************************************
ok: [switch] => {
    "ansible_facts.network_resources.vlans | selectattr('vlan_id', '==', 109)": [
        {
            "mtu": 1500,
            "name": "test",
            "shutdown": "disabled",
            "vlan_id": 109
        }
    ]
}

TASK [Remove VLAN] *************************************************************
changed: [switch]

PLAY RECAP *********************************************************************
switch    : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
