### ISSUE TITLE
sharing doc fragments between plugins and modules

### ISSUE THREAD

**Issue by briantist** [ansible/ansible#75285]
### Summary

Requested by @bcoca 

This is a description of the use case for centralizing plugin/module documentation in doc fragments, which are shared between modules and plugins.

The purpose of this is issue is to ensure it's on the radar of the core team.

doc fragments work for both, but not all fields are valid for both.

In plugins it's especially important since docstrings are used as part of the actual execution, where Config manager processes the plugin's options based on the documentation (a very nice thing indeed). Plugins can also describe in the docstring alternative ways of filling the options, via `env:` (for environment variables), `ini:` (for configuration file entries), and `vars:` (for ansible vars), with standard/defined precedence rules. This saves lots of boilerplate.

Since those don't work on modules, they should (or perhaps must) be excluded from module documentation.

Breaking up the doc fragments so that the plugin-specific parts are in separate doc fragments (either via alternative sections, such as the `OTHER` section described in https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-fragments or via separate files), is one possible way of dealing with this.

It doesn't always work for other parts where items included in both need to change depending on whether it's a module or plugin (like having only part of a description change, or having different notes).

---

Hopefully others will chime in with their current/desired experiences.

### Issue Type

Documentation Report

### Component Name

n/a

### Ansible Version

```console
$ ansible --version
n/a
```

### Configuration

```console
$ ansible-config dump --only-changed
n/a
```

### OS / Environment

n/a

### Additional Information

n/a

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/cli/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/__init__.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
It's not clear to me what you mean by
> It doesn't always work for other parts where items included in both need to change depending on whether it's a module or plugin (like having only part of a description change, or having different notes).

Changing part of a field is probably trying to be too clever with doc fragments (though it's technically possible), but you can pretty readily split up the parts that you want to differ between each plugin type into separate fragments. For example, if I put the following in `plugins/doc_fragments/base.py`:

```
SILLY_TRICK = 'your Vault service'

class ModuleDocFragment(object):
    DOCUMENTATION = '''
options:
  vault_addr:
    type: str
    default: https://localhost:8200
notes:
  - HashiCorp Vault is not the same as Ansible's Vault.
'''

    PLUGINS = '''
options:
  vault_addr:
    description:
      - Location of {0}.
    env:
      - name: VAULT_ADDR
    ini:
      - section: hvault
        key: url
    vars:
      - name: ansible_hvault_addr
notes:
  - Plugins are run on the Ansible controller.
'''.format(SILLY_TRICK)

    MODULES = '''
notes:
  - Modules are run on the target host.
options:
  vault_addr:
    description:
      - URI of {0}.
'''.format(SILLY_TRICK)
```

Then the documentation for a lookup that uses the `flowerysong.test.base` and `flowerysong.test.base.PLUGINS` fragments looks like this:
```
> FLOWERYSONG.TEST.KV    (/home/ec2-user/testing/collections/ansible_collections

        Ansible lookup for HashiCorp Vault.

OPTIONS (= is mandatory):

- vault_addr
        Location of your Vault service.
        [Default: https://localhost:8200]
        set_via:
          env:
          - name: VAULT_ADDR
          ini:
          - key: url
            section: hvault
          vars:
          - name: ansible_hvault_addr
        
        type: str


NOTES:
      * HashiCorp Vault is not the same as Ansible's Vault.
      * Plugins are run on the Ansible controller.
```

And a module that uses `flowerysong.test.base` and `flowerysong.test.base.MODULES`:
```
> FLOWERYSONG.TEST.KV    (/home/ec2-user/testing/collections/ansible_collections

        Manage KV secrets in HashiCorp Vault.

OPTIONS (= is mandatory):

- vault_addr
        URI of your Vault service.
        [Default: https://localhost:8200]
        type: str


NOTES:
      * HashiCorp Vault is not the same as Ansible's Vault.
      * Modules are run on the target host.
```
