### ISSUE TITLE
lineinfile does or does not execute task depending variable value provided in "line:" 

### ISSUE THREAD

**Issue by PisikeSipelgas** [ansible/ansible#75293]
### Summary

Mysql datadir is not in default location and i'm trying to update mysql config file according to this providing new data dir path via variables. Depending variable value "lineinfile" works or not.
See code example and note the difference between "mysqldata1" and "mysqldata2" values.
Second "lineinfile" is always skipped.

### Issue Type

Bug Report

### Component Name

lineinfile

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /home/eimar/.ansible.cfg
  configured module search path = [u'/home/eimar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/home/sipelgas/.ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/sipelgas/.ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/sipelgas/.vault_pass
TRANSFORM_INVALID_GROUP_CHARS(env: ANSIBLE_TRANSFORM_INVALID_GROUP_CHARS) = ignore
```

### OS / Environment

Centos 7

### Steps to Reproduce

```yaml (paste below)
---

- name: "lineinfile bug"
  hosts: all
  become: true
  become_method: sudo
  gather_facts: no
  vars:
      mysqlconf: "/etc/my.cnf"
      mysqldata1: "/mysqldata/mysqldata"
      mysqldata2: "/mysqldata/mysqldataa"

  tasks:
#1
  - name: "{{ mysqlconf }}: [mysqldump]"
    lineinfile:
      path: "{{ mysqlconf }}"
      insertbefore: '^\[mysqld\]'
      line: '[mysqldump]'
#2
  - name: "{{ mysqlconf }}: socket={{ mysqldata1 }}/mysql.sock"
    lineinfile:
      path: "{{ mysqlconf }}"
      insertafter: '^\[mysqldump\]'
      line: socket={{ mysqldata1 }}/mysql.sock
#3
  - name: "{{ mysqlconf }}: socket={{ mysqldata2 }}/mysql.sock"
    lineinfile:
      path: "{{ mysqlconf }}"
      insertafter: '^\[mysqldump\]'
      line: socket={{ mysqldata2 }}/mysql.sock
...

```

### Expected Results

[mysqldump]
socket=/mysqldata/mysqldataa/mysql.sock
socket=/mysqldata/mysqldata/mysql.sock
[mysqld]

### Actual Results

```console
$ ansible-playbook -i 192.168.57.220, bug.yml

PLAY [lineinfile bug] ***********************************************************************************************************************************************************************

TASK [/etc/my.cnf: [mysqldump]] *************************************************************************************************************************************************************
changed: [192.168.57.220]

TASK [/etc/my.cnf: socket=/mysqldata/mysqldata/mysql.sock] **********************************************************************************************************************************
ok: [192.168.57.220]

TASK [/etc/my.cnf: socket=/mysqldata/mysqldataa/mysql.sock] *********************************************************************************************************************************
changed: [192.168.57.220]

PLAY RECAP **********************************************************************************************************************************************************************************
192.168.57.220             : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

[mysqldump]
socket=/mysqldata/mysqldataa/mysql.sock
[mysqld]


```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/lineinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/lineinfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by PisikeSipelgas** [comment]
I think, that i found a workaround. However i cannot explain this behaviour.
Defining variable mysqldata1 like this (using singe apostrophe):
```     
      mysqldata1: '/mysqldata/mysqldata'
      mysqldata2: "/mysqldata/mysqldataa"
```
and magically mysqldata1 starts to working as expected.

**Comment by mkrizek** [comment]
> ### Expected Results
> [mysqldump]
> socket=/mysqldata/mysqldata/mysql.sock
> socket=/mysqldata/mysqldataa/mysql.sock
> [mysqld]

Shouldn't it be:
```
[mysqldump]
socket=/mysqldata/mysqldataa/mysql.sock
socket=/mysqldata/mysqldata/mysql.sock
[mysqld]
```
?

**Comment by PisikeSipelgas** [comment]
Yes. You are correct. Updated my initial post.  Thanks.

**Comment by mkrizek** [comment]
I am not able to reproduce the issue:

```
% cat ../ansible-issues/75293.yml
- hosts: localhost
  gather_facts: no
  vars:
      mysqlconf: "/tmp/my.cnf"
      mysqldata1: "/mysqldata/mysqldata"
      mysqldata2: "/mysqldata/mysqldataa"
  tasks:
#1
  - name: "{{ mysqlconf }}: [mysqldump]"
    lineinfile:
      path: "{{ mysqlconf }}"
      insertbefore: '^\[mysqld\]'
      line: '[mysqldump]'
#2
  - name: "{{ mysqlconf }}: socket={{ mysqldata1 }}/mysql.sock"
    lineinfile:
      path: "{{ mysqlconf }}"
      insertafter: '^\[mysqldump\]'
      line: socket={{ mysqldata1 }}/mysql.sock
#3
  - name: "{{ mysqlconf }}: socket={{ mysqldata2 }}/mysql.sock"
    lineinfile:
      path: "{{ mysqlconf }}"
      insertafter: '^\[mysqldump\]'
      line: socket={{ mysqldata2 }}/mysql.sock
```
```
% ansible --version
ansible 2.9.23
  config file = /Users/mkrizek/src/ansible/ansible.cfg
  configured module search path = [u'/Users/mkrizek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mkrizek/src/ansible/lib/ansible
  executable location = /Users/mkrizek/.pyenv/versions/ansible-py2718/bin/ansible
  python version = 2.7.18 (default, Nov 19 2020, 18:49:01) [GCC Apple LLVM 12.0.0 (clang-1200.0.32.27)]
```
```
% cat /tmp/my.cnf
[mysqld]
```
```
% ansible-playbook ../ansible-issues/75293.yml

PLAY [localhost] *********************************************************************************************************************************************

TASK [/tmp/my.cnf: [mysqldump]] ******************************************************************************************************************************
changed: [localhost]

TASK [/tmp/my.cnf: socket=/mysqldata/mysqldata/mysql.sock] ***************************************************************************************************
changed: [localhost]

TASK [/tmp/my.cnf: socket=/mysqldata/mysqldataa/mysql.sock] **************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=3    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
```
% cat /tmp/my.cnf
[mysqldump]
socket=/mysqldata/mysqldataa/mysql.sock
socket=/mysqldata/mysqldata/mysql.sock
[mysqld]
```

What am I doing differently?
