### ISSUE TITLE
Add GIT `set-url origin` functionality into `ansible.builtin.git` module

### ISSUE THREAD

**Issue by jrglynn2** [ansible/ansible#75315]
### Summary

When cloning a GIT Repo to a local server using HTTP, we have use the URL in this type of format - https://USER_NAME:PASSWORD@<REPO_URL>

After cloning, we would want to rest the URL to be https://<REPO_URL>

Currently, I have to run a `command` module to run this - git remote set-url origin https://<REPO_URL>

So this request would be to have a parameter added to `ansible.builtin.git` that would enable me to run this set_url command, so I don't have to use the `command` module.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.git

### Additional Information

```yaml (paste below)
    #current command that creates local repo
    - name: Create local Git repo
      ansible.builtin.git:
          repo: "https://USER_NAME:PASSWORD@<REPO_URL>"
          dest: /opt/repo
          single_branch: yes
          version: "GIT-BRANCH"

    # possible new command that would do the set-url functionality
    - name: Set URL of Git Repo
      ansible.builtin.git:
          dest: /opt/repo
          set_url:  "https://<REPO_URL>"

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/git.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/git.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zigarn** [comment]
You can simply use the `repo` argument to update the URL:

```shell
$ ansible localhost -m ansible.builtin.git -a "repo=/tmp/repo1 dest=/tmp/clone"
localhost | CHANGED => {
    "after": "4acf26798393c90e187910c317c30b34fc84b563",
    "before": null,
    "changed": true
}

$ git --git-dir=/tmp/clone/.git remote -vv
origin	file:///tmp/repo1 (fetch)
origin	file:///tmp/repo1 (push)

$ ansible localhost -m ansible.builtin.git -a "repo=/tmp/repo2 dest=/tmp/clone"
localhost | CHANGED => {
    "after": "4acf26798393c90e187910c317c30b34fc84b563",
    "before": "4acf26798393c90e187910c317c30b34fc84b563",
    "changed": true,
    "remote_url_changed": true
}

$ git --git-dir=/tmp/clone/.git remote -vv
origin	file:///tmp/repo2 (fetch)
origin	file:///tmp/repo2 (push)
```

**Comment by jrglynn2** [comment]
This doesn't work for me.

Code:
```
    - name: remove visibility of credentials
      ansible.builtin.git:
          repo: "https://<REPO_URL>"
          dest: /opt/repo
          update: no
```

Result:
```
git remote -v
origin  https://USER_NAME:PASSWORD@<REPO_URL> (fetch)
origin  https://USER_NAME:PASSWORD@<REPO_URL> (push)
```

If I exclude the `update: no`, which defaults it to "yes", it never completes because it tries to authenticate and can't, because user name / password are not supplied.

If I include the `update: no`, the URL is not updated.

Can you reproduce the test you supplied with a GIT repo that requires HTTP(S) user name / password, and let me know how you get that to work?

Thanks!

**Comment by zigarn** [comment]
I confirm it doesn't work with `update: no`.
`update` is documented as "If no, do not retrieve new revisions from the origin repository.", so I would interpret it as doing a fetch or not.

So either `update` is not well documented (and in that case another way to update the remote without fetching as to be implemented), either their is a bug of not updating the remote value with `update: no`.

**Comment by jrglynn2** [comment]
Yes, if `update: yes` is there - or not there, which defaults to yes - it seems that it requires the user name / password to connect - which I don't want to supply, since the purpose of the change is to make the URL have no pre-assumed user name / password.

This might be why the GIT command `git remote set-url` was originally created, to be able to change the local repo's URL without having to do any connection to the remote repository...

Thanks!

**Comment by bcoca** [comment]
This is something you should use the existing https://docs.ansible.com/ansible/2.9/modules/git_config_module.html for or use the git module options instead of having the auth inline in the url.

**Comment by jrglynn2** [comment]
bcoca, thanks so much! `community.general.git_config` is exactly what I needed.

For reference, this play worked for me:
```
    - name: remove visibility of credentials
      community.general.git_config:
          scope: local
          repo: /opt/repo
          name: remote.origin.url
          value: "https://<REPO_URL>"
```

Thanks again!
