### ISSUE TITLE
Add a new ansible_galaxy_install module

### ISSUE THREAD

**Issue by yajo** [ansible/ansible#75322]
### Summary

[`community.general` is getting a new module `ansible_galaxy_install`](https://github.com/ansible-collections/community.general/pull/2933)  for installing ansible requirements, but then you still need to have `community.general` installed to be able to install other requirements, so you still don't have a complete way to handle ansible requirements if you're using ansible-core.

My request is that `ansible_galaxy_install` is moved into `ansible.builtin`, so it can be used to install *any* collection with ansible-core, including `community.general`.

### Issue Type

Feature Idea

### Component Name

ansible-galaxy

### Additional Information

I am used to Ansible, but other folks in my team aren't.

Ansible has its own packaging format (roles or collections) and dependency management tool (ansible-galaxy), which only handles Ansible dependencies but not python dependencies (example when a collection needs a python lib). So, it's hard for me to provide some "frozen" environment to work on. All would be easier if collections and roles could be installed with `pip` and then I could leverage stuff like Poetry or Pipenv to make things work out of the box, but that's not the world we live on.

My solution so far has been to prefix any playbook with something like this:

```yaml
# Any other role
- import_playbook: base.yaml
```

```yaml
# base.yaml
- name: make sure you have the required role dependencies
  hosts: localhost
  tags:
    - always
  tasks:
    - name: install galaxy roles
      command: ansible-galaxy install -r requirements.yaml
      args:
        chdir: "{{ playbook_dir }}"
      register: result
      changed_when: "'installed successfully' in result.stdout"

    - name: update galaxy roles
      command: ansible-galaxy install -fr requirements.yaml
      args:
        chdir: "{{ playbook_dir }}"
      when:
        - "'use --force to change' in result.stderr_lines|join(' ')"
```

This way, every time a user runs a playbook, the requirements will be properly installed. Python requirements are handled prior to execution by Poetry, so this provides an expected, predictable environment.

However, considering that the use of ansible galaxy requirements is raising, and considering that `ansible-galaxy` is a tool shipped with ansible itself, it seems rather strange that ansible doesn't have an official way to installing local dependencies. Besides, the above stuff is a bit hacky, quite slow and not idempotent.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
