### ISSUE TITLE
callback: result._task.delegate_to returns untemplated variables such as "{{ item }}" in task loops

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible#75339]
### Summary

result._task.delegate_to returns untemplated variables such as "{{ item }}" in task loops.

It works fine if the task is not a loop.

### Issue Type

Bug Report

### Component Name

``lib/ansible/plugins/callback/__init__.py``

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/dmsimard/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmsimard/dev/virtualenvs/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/dmsimard/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dmsimard/dev/virtualenvs/ansible/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
Not relevant
```

### OS / Environment

Not relevant

### Steps to Reproduce

```yaml (paste below)
- name: Reproducer that works
  hosts: localhost
  gather_facts: no
  vars:
    delegated_host: localhost
  tasks:
    # result._task.delegate_to = localhost
    - name: Delegate a task directly to localhost
      debug:
        msg: delegated
      delegate_to: localhost

    # result._task.delegate_to = localhost
    - name: Delegate a task through a variable
      debug:
        msg: delegated
      delegate_to: "{{ delegated_host }}"

- name: Reproducer that doesn't work
  hosts: localhost
  gather_facts: no
  vars:
    delegated_hosts:
      - localhost
  tasks:
    # result._task.delegate_to = "{{ delegated_hosts[0] }}"
    - name: Delegate a task with a loop
      debug:
        msg: "{{ item }}"
      delegate_to: "{{ delegated_hosts[0] }}"
      loop:
        - delegated

    # result._task.delegate_to = "{{ item }}"
    - name: Delegate a task with a delegation loop
      debug:
        msg: "delegated"
      delegate_to: "{{ item }}"
      loop: "{{ delegated_hosts }}"

```

### Expected Results

``result._task.delegate_to`` should consistently return a host name even if it's inside a loop.

### Actual Results

```console
See reproducer.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
