### ISSUE TITLE
yum_repository module adds deprecated options on centos/rhel 8

### ISSUE THREAD

**Issue by mfld** [ansible/ansible#75364]
### Summary

Adding a yum repository to a centos/rhel 8 system with yum_repository module adds async option (deprecated) to repository-file.

Inspecting /var/log/dnf.log on centos/rhel 8 after running `dnf repolist` produces the following errors.
```
2021-07-30T10:38:19+0200 DEBUG Unknown configuration option: async = 0 in /etc/yum.repos.d/epel.repo
```
Seems yum_repository module should omit the async option when target system is centos/rhel8?

best regards, Mikael

### Issue Type

Bug Report

### Component Name

yum_repository

### Ansible Version

```console
$ ansible --version
  config file = None
  configured module search path = ['/home/$USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /ansible-collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, Jun 23 2021, 15:10:59) [GCC 8.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
none
```

### OS / Environment

CentOS Linux release 8.4.2105

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  become: true
  tasks:
  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no
```

### Expected Results

```
TASK [Add repository] ***********************************************************
--- before: /etc/yum.repos.d/epel.repo
+++ after: /etc/yum.repos.d/epel.repo
@@ -0,0 +1,6 @@
+[epel]
+baseurl = https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
+gpgcheck = 0
+name = EPEL YUM repo
+

changed: [centos8-host]
```
### Actual Results

```console
TASK [Add repository] ***********************************************************
--- before: /etc/yum.repos.d/epel.repo
+++ after: /etc/yum.repos.d/epel.repo
@@ -0,0 +1,6 @@
+[epel]
+async = 1
+baseurl = https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
+gpgcheck = 0
+name = EPEL YUM repo
+

changed: [centos8-host]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
