### ISSUE TITLE
[template] Add parameter "content"

### ISSUE THREAD

**Issue by darkdragon-001** [ansible/ansible#75367]
### Summary

Since it is [no longer advised to use `content` parameter of the `copy` module when using variables](https://stackoverflow.com/a/26640778/3779655), I suggest adding such a parameter to the `template` module to allow writing variables to a file directly.

### Issue Type

Feature Idea

### Component Name

template

### Additional Information

```yaml (paste below)
tasks:
  - template
      content: "{{ my_variable }}"
      dst: "/path/to/file"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
