### ISSUE TITLE
Zypper module do not remove a packages which contains wildcard

### ISSUE THREAD

**Issue by Alexhha** [ansible/ansible#75391]
### Summary

Can't remove packages if name contains wildcard
```yaml (paste below)
  - name: Uninstall PostgreSQL
    become: yes
    zypper:
      name: ["postgresql*"]
      state: absent
```
It works with apt/yum modules, but doesn't work with zypper

### Issue Type

Bug Report

### Component Name

zypper

### Ansible Version

```console
$ ansible --version
ansible 2.9.22
  config file = /Users/alex/work/bitbucket/master/ansible/ansible.cfg
  configured module search path = ['/Users/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) [Clang 6.0 (clang-600.0.57)]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

SLES12 SP5

### Steps to Reproduce

```yaml (paste below)
- name: DEBUG
  hosts: all
  gather_facts: no

  tasks:
  - name: Uninstall PostgreSQL
    become: yes
    zypper:
      name: ["postgresql*"]
      state: absent
```

### Expected Results

All postgresql packages should be removed

### Actual Results

```console
A packages were not removed

$ rpm -qa | grep postgresql
postgresql12-server-12.3-1PGDG.sles12.x86_64
postgresql12-12.3-1PGDG.sles12.x86_64
postgresql12-libs-12.3-1PGDG.sles12.x86_64
```
zypper itself supports wildcard
```
$ zypper rm postgresql*
zypper rm postgresql*
Loading repository data...
Warning: No repositories defined. Operating only with the installed resolvables. Nothing can be installed.
Reading installed packages...
Resolving package dependencies...

The following 3 packages are going to be REMOVED:
  postgresql12 postgresql12-libs postgresql12-server

3 packages to remove.
After the operation, 69.1 MiB will be freed.
Continue? [y/n/...? shows all options] (y):
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
