### ISSUE TITLE
Module 'file' - would like a non-recursive directory delete for "state=absent"

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#7541]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7 git 2014-05-25
##### Environment:

Mac OSX 10.9.3 managing Slackware64-14.1 hosts
##### Summary:

It would be great to be able to non-recursively delete a directory using the file module, i.e. something equivalent to "rmdir --ignore-fail-on-non-empty mydir". A use case for this is cleaning up certain directories only if they are empty, meaning nothing is using them at the moment and they can safely be cleaned up.

Currently setting a directory to state=absent will always recursively delete the directory and there are no options for changing this behavior.

It's counter-intuitive that setting "recurse=no" (the default) will in fact still lead to a directory being recursively deleted along with all of its contents.
##### Steps To Reproduce:

```
- name: delete a directory
  file:  path=/tmp/mydir state=absent recurse=no
```
##### Expected Results:

Would like a way to non-recursively delete a directory.
##### Actual Results:

state=absent will always recursively delete a directory

**Comment by mpdehaan** [comment]
We are unlikely to add a new state for absent_only_if_empty, so a good solution here is probably to check if it's empty and then remove it.

We would accept pull requests to the stat module to denote if a directory is empty (such as if a directory, returning empty: True/False) and then you could combine that with the stat module to conditionally apply the state=absent.

**Comment by kingdonb** [comment]
This seems extremely complex... why not neuter state=absent when recurse=no is set?

I am trying to write a role that runs 'kubeadm init' if it hasn't already been done.  I check if there is a PKI dir in /etc/kubernetes (since that gets created during init), and if it's not there, I check if there is anything in /var/lib/kubelet/ (since init will fail if this directory is not empty, and I've observed once or twice an empty "pods" and "plugins" directory get left in this folder.)

I want to do this non-destructively (to avoid blowing away my PKI dir), and so far it looks like this:

```
- name: register contents of - /var/lib/kubelet
  find: paths=/var/lib/kubelet/ file_type=directory patterns="*"
  become: true
  become_user: root
  register: kubelet_contents
  when: kubelet_dir.matched|int != 0

- name: is empty? - plugins dir
  find: paths=/var/lib/kubelet/plugins file_type=directory patterns="*"
  become: true
  become_user: root
  register: plugins_contents
  when: kubelet_contents.matched|int != 0

- name: rmdir /var/lib/kubelet/plugins
  file: name=/var/lib/kubelet/plugins state=absent recurse=no
  become: true
  become_user: root
  when: (plugins_contents is defined) and (plugins_contents.matched|int == 0)

- name: is empty? - pods dir
  find: paths=/var/lib/kubelet/pods file_type=directory patterns="*"
  become: true
  become_user: root
  register: pods_contents
  when: kubelet_contents.matched|int != 0

- name: rmdir /var/lib/kubelet/pods
  file: name=/var/lib/kubelet/pods state=absent recurse=no
  become: true
  become_user: root
  when: (pods_contents is defined) and (pods_contents.matched|int == 0)

- name: is empty? - pki dir
  find: paths=/etc/kubernetes/pki file_type=directory patterns="*"
  become: true
  become_user: root
  register: pki_contents

- name: rmdir /etc/kubernetes/pki
  file: name=/etc/kubernetes/pki state=absent recurse=no
  become: true
  become_user: root
  when: (pki_contents is defined) and (pki_contents.matched|int == 0)
```

and finally

```
- name: Initialize Kubernetes cluster
  command: 'kubeadm init'
  args:
    creates: /etc/kubernetes/pki
  become: true
  become_user: root
```

I'm still not sure this is right.  In fact I'm pretty sure I just blew away my /etc/kubernetes/pki with keys in it, in my testing, while trying to figure out how this should look.  Is there a simpler way?

I feel like this is needlessly complicated, but certain processes will result in empty directories lying around that need to be cleaned up before the init can proceed.  I can't use `rmdir --ignore-fail-on-non-empty` for two reasons, 1 - because ansible discourages it, but also because it fails if the directory is already not present.

With original poster's suggestion, state=absent and recurse=no when used together would abort with an error instead of deleting my PKI dir.

**Comment by kingdonb** [comment]
Yeah, I guess you need parentheses around:

```
  when: (foo and bar)
```

If you write it as:
```
  when: (foo) and (bar)
```

it does not have the desired effects...  (Edit: no, I was looking for directories and there were only files)

Maybe this whole effort is misguided, I'm finding there are times when the plugins dir is empty and I still don't want to remove it.

**Comment by kingdonb** [comment]
There was too much wrong with that set of tasks,

I decided I should only remove "plugins" or "pods" if both are simultaneously empty, since this is a script for master nodes, any node may have an empty plugins directory, but I'm pretty sure that a node that doesn't have any pods running on it is not a functioning master node and should be redone...

The PKI directory only has file contents (no directories) so that's how I managed to blow it away.  I'm not on Ansible 2.3 yet so I can't use `file_type=any`

Posting this better task set for posterity, in case anyone trying to solve a similar problem stumbles onto this page:

```
- name: exists - /var/lib/kubelet
  find: paths=/var/lib/ file_type=directory patterns="kubelet"
  register: kubelet_dir

- name: register contents of - /var/lib/kubelet
  find: paths=/var/lib/kubelet/ file_type=directory patterns="*"
  become: true
  become_user: root
  register: kubelet_contents
  when: kubelet_dir.matched|int != 0

- name: is empty? - /var/lib/kubelet/*/
  find:
    paths: ["/var/lib/kubelet/plugins/", "/var/lib/kubelet/pods/"]
    file_type: directory
    patterns: "*"
  become: true
  become_user: root
  register: kubelet_inner_contents
  when: ((kubelet_contents is defined) and (kubelet_contents.matched|int != 0))

- name: rmdir /var/lib/kubelet/plugins
  file: name=/var/lib/kubelet/plugins state=absent recurse=no
  become: true
  become_user: root
  when: ((kubelet_inner_contents is defined) and (kubelet_inner_contents.matched|int == 0))

- name: rmdir /var/lib/kubelet/pods
  file: name=/var/lib/kubelet/pods state=absent recurse=no
  become: true
  become_user: root
  when: ((kubelet_inner_contents is defined) and (kubelet_inner_contents.matched|int == 0))

- name: is empty? - pki dir
  find:
    paths: /etc/kubernetes/pki/
    file_type: file
    patterns: "*"
  become: true
  become_user: root
  register: pki_contents

- name: rmdir /etc/kubernetes/pki
  file: name=/etc/kubernetes/pki state=absent recurse=no
  become: true
  become_user: root
  when: ((pki_contents is defined) and (pki_contents.matched|int == 0))

- name: Initialize Kubernetes cluster
  command: 'kubeadm init'
  args:
    creates: /etc/kubernetes/pki
  become: true
  become_user: root
```
