### ISSUE TITLE
Make looping over a block possible

### ISSUE THREAD

**Issue by skutter-de** [ansible/ansible#75410]
### Summary

I want to be able to use a loop statement with a block. I know you can use `include_taks` but this seems like the better implementation. See example below.

### Issue Type

Feature Idea

### Component Name

block

### Additional Information

```yaml (paste below)
...
block:
  - name: "Read data"
    shell:
      cmd: "{{ item }}"
    register: output
  
  - name: "Add output to list"
    set_fact:
      outputs: "{{ (outputs | default([])) + output.stdout }}" 
with_items:
  - "echo 'test'"
  - "echo 'test2'"
...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
