### ISSUE TITLE
delegated facts getting overwritten

### ISSUE THREAD

**Issue by mrabe142** [ansible/ansible#75419]
### Summary

When attempting to collect facts from other hosts and display them, those facts get overwritten by by the host facts where the playbook is executing. I have tried numerous different configurations without luck. I tried more or less following the example as described at https://docs.ansible.com/ansible/2.9/user_guide/playbooks_delegation.html#delegated-facts. This issue seems similar to the symptoms seen in https://github.com/ansible/ansible/issues/20980. 

### Issue Type

Bug Report

### Component Name

delegation, hostvars

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /home/centos/staging/playbooks/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/centos/staging/playbooks/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/home/centos/staging/playbooks/ansible.cfg) = 5
DEFAULT_CALLBACK_WHITELIST(/home/centos/staging/playbooks/ansible.cfg) = [u'profile_roles', u'profile_tasks', u'timer']
DEFAULT_FORKS(/home/centos/staging/playbooks/ansible.cfg) = 10
DEFAULT_TIMEOUT(/home/centos/staging/playbooks/ansible.cfg) = 60
DEFAULT_VAULT_PASSWORD_FILE(/home/centos/staging/playbooks/ansible.cfg) = /home/centos/staging/playbooks/vault/.vault
DISPLAY_SKIPPED_HOSTS(/home/centos/staging/playbooks/ansible.cfg) = False
HOST_KEY_CHECKING(/home/centos/staging/playbooks/ansible.cfg) = False
```

### OS / Environment

Controller: CentOS 7.9
Targets: RHEL 7.9

### Steps to Reproduce

Static IPs
```
elasticsearch-1=10.0.1.8
elasticsearch-2=10.0.1.9
elasticsearch-3=10.0.1.10
snapshot=10.0.0.6
gateway=10.0.0.5
```
Inventory
```
[gateway]
gateway

[elasticsearch_servers]
elasticsearch-1
elasticsearch-2
elasticsearch-3

[snapshot_server]
snapshot
```

group_vars/all
```yaml
ansible_user: ec2-user

# Fully qualified domain names for instances. Reference fully qualified hosts in SSH config files.
ansible_host: "{{ inventory_hostname }}.aws"
```
Given the above setup, I run the following playbook:

Playbook
```yaml
- hosts: gateway
  tasks:
    - name: Gather dependent remote host facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items:
        - "elasticsearch-1"
        - "elasticsearch-2"
        - "elasticsearch-3"
        - "snapshot"
    - debug:
        msg: "{{ item }}:{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
      with_items:
        - "elasticsearch-1"
        - "elasticsearch-2"
        - "elasticsearch-3"
        - "snapshot"
```

### Expected Results

I expected the following output from the playbook with the IPs matching the correct hosts:
```
PLAY [gateway] ******************************************************************************************************

TASK [Gather dependent remote host facts] ***********************************************************************************************************************
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=elasticsearch-1)
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=elasticsearch-2)
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=elasticsearch-3)
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=snapshot)

TASK [debug] ***********************************************************************************************************************
ok: [gateway] => (item=elasticsearch-1) => {
    "msg": "elasticsearch-1:10.0.1.8"
}
ok: [gateway] => (item=elasticsearch-2) => {
    "msg": "elasticsearch-2:10.0.1.9"
}
ok: [gateway] => (item=elasticsearch-3) => {
    "msg": "elasticsearch-3:10.0.1.10"
}
ok: [gateway] => (item=snapshot) => {
    "msg": "snapshot:10.0.0.6"
}
```

### Actual Results

```console
Instead, I got the following playbook output with all the IPs set to the original target host:

PLAY [gateway] ****************************************************************************************

TASK [Gather dependent remote host facts] ****************************************************************************************
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=elasticsearch-1)
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=elasticsearch-2)
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=elasticsearch-3)
ok: [gateway -> {{ inventory_hostname }}.aws] => (item=snapshot)

TASK [debug] ****************************************************************************************
ok: [gateway] => (item=elasticsearch-1) => {
    "msg": "elasticsearch-1:10.0.0.5"
}
ok: [gateway] => (item=elasticsearch-2) => {
    "msg": "elasticsearch-2:10.0.0.5"
}
ok: [gateway] => (item=elasticsearch-3) => {
    "msg": "elasticsearch-3:10.0.0.5"
}
ok: [gateway] => (item=snapshot) => {
    "msg": "snapshot:10.0.0.5"
}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
