### ISSUE TITLE
role argspec validation doesn't run unless `tasks_from` entrypoint matches exactly

### ISSUE THREAD

**Issue by briantist** [ansible/ansible#75456]
### Summary

A role with an argspec that defines an entrypoint like `my_entrypoint` has `tasks/my_entrypoint.yml`.

The role can successfully be called with any of the following:

```yaml
tasks_from: my_entrypoint
tasks_from: my_entrypoint.yml
tasks_from: /home/user/ansible/collections/ansible_collections/ns/cn/roles/my_role/tasks/my_entrypoint.yml
```

But only the first one will trigger argspec validation; the others will execute without validation.

---

An example that helped me find this, is a role with OS/Platform-based entrypoints, using `with_first_found`:

```yaml
- name: "Peform OS-specific setup"
  include_role:
    name: '{{ ansible_role_name }}'
    tasks_from: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - 'Linux.yml'
```

As a workaround (which may be worth documenting):

```yaml
- name: "Peform OS-specific setup"
  include_role:
    name: '{{ ansible_role_name }}'
    tasks_from: '{{ item | basename | splitext | first }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - 'Linux.yml'
```

### Issue Type

Bug Report

### Component Name

lib/ansible/playbook/role/__init__.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.3]
  config file = None
  configured module search path = ['/home/briantist/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/briantist/.a211/lib/python3.6/site-packages/ansible
  ansible collection location = /home/briantist/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/briantist/.a211/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_FORKS(env: ANSIBLE_FORKS) = 30
```

### OS / Environment

Ubuntu 18.04 (WSL2)

### Steps to Reproduce

see description

### Expected Results

Validation runs based on the _tasks file_ being executed, rather than the text passed into `tasks_from`.

### Actual Results

```console
argsspec validation doesn't run
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/role/__init__.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/__init__.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I have a question about the example: `with_first_found` only searches the directory adjacent to the playbook and `files/` adjacent to the playbook unless additional search paths are provided, or the task file is within a role. If this task is within a role, it will also search `tasks/` and `files/` within the role containing the task with the lookup, _not_ the role to be included. The specified `tasks_from` file may not exist in the included role, so I'm not sure this example is valid. Or I'm just very confused (is the `include_role` task referencing itself?).

I was able to reproduce it with a simpler playbook and role which includes an argument spec for the `main` entrypoint.


```yaml
- hosts: localhost
  gather_facts: no

  tasks:
    - import_role:
        name: testrole75465_2
        tasks_from: main.yml
```
