### ISSUE TITLE
include_role stops working when using tags

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#75466]
### Summary

when using `include_role` as task in a play the included role runs fine when no tags are used. When the play is run with the `--tags` option then the play runs through without executing anything in the included role.

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version

ansible 2.10.5
```

### Configuration

```console
$ ansible-config dump --only-changed

ANSIBLE_PIPELINING(/home/matthias/.ansible.cfg) = True
DEFAULT_FORKS(/home/matthias/.ansible.cfg) = 10
DEFAULT_REMOTE_USER(/home/matthias/.ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/matthias/.ansible.cfg) = ['/home/matthias/test/roles']
INTERPRETER_PYTHON(/home/matthias/.ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/home/matthias/.ansible.cfg) = False
```

### OS / Environment

up to date Ubuntu Linux 21.04

### Steps to Reproduce

testplay.yml

```yaml
---

- hosts: localhost

  vars:
    test_list:
      - var_a: "boo"
        var_b: "far"
      - var_a: "moo"
        var_b: "lar"

  tasks:
    - name: run testrole
      include_role:
        name: testrole
      vars:
        testrole_var_a: "{{ item.var_a }}"
        testrole_var_b: "{{ item.var_b }}"
      with_items: "{{ test_list }}"
      tags: testtag
```

roles/testrole/defaults/main.yml
```yaml
---

testrole_var_a: "foo"
testrole_var_b: "bar"
```

roles/testrole/tasks/main.yml
```yaml
---

- name: debug testrole_var_a
  debug: var=testrole_var_a

- name: debug testrole_var_b
  debug: var=testrole_var_b
```

Run the play with:

`ansible-playbook testplay.yml`

Result:

The included role gets executed 2 x and the variables are set correctly

Run the play again with:

`ansible-playbook --tags testtag  testplay.yml`

Result:

The play runs without errors but does nothing, the included role is not executed.

### Expected Results

Running the play with or without tags should result in the same execution of the included role

### Actual Results

```console
When run with the `--tags` option the play runs without errors but does nothing, the included role is not executed.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/role/include.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
`tags` on an `include_role` only apply to the include action itself, and not to the tasks within.

To get the behavior you desire, you have a few options:

```yaml
    - name: run testrole
      include_role:
        name: testrole
        apply:
          tags: testtag
      tags: testtag
```

```yaml
    - name: run testrole
      include_role:
        name: testrole
        apply:
          tags: testtag
      tags: always
```

The first applies `testtag` to both the include, and the tasks within.  The 2nd uses the `always` tag to always run the include, but then restrict the inner tag application to `testtag`.  Depending on how your role grows, and explicit tags inside of the role, one may work better than the other.

**Comment by sivel** [comment]
If you specify `anothertesttag` it will _only_ run tasks with that tag, which in this case is _only_ the `include_role`.  If you have tasks inside of the include that you want to run, they would need to be tagged as well, and you would have to explicitly list them with `--tags`.

In your example, the tasks were listed as:

```
- name: debug testrole_var_a
  debug: var=testrole_var_a

- name: debug testrole_var_b
  debug: var=testrole_var_b
```

Those tasks have no tags and would not match `anothertesttag`, and thus are never run.

You either need to explicitly tag them so you can do `--tags anothertesttag,my_task_tag` or use the `apply` to add `anothertesttag` to all of the tasks within the role.

**Comment by matthias-mo** [comment]
In which case `import_role` does not behave like any other task.

If I have a play like

```(yaml)
    - name: ensure directory
      file: path=/foo/morefoo state=directory owner=root group=root mode=0750
      tags: foo

**Comment by sivel** [comment]
If you want the same behavior as the following:

```yaml
  roles:
    - role: testrole
      tags: testrole
    - role: anothertestrole
      tags: anothertestrole
```

What you want with `include_role` will look like this:

```
tasks:
  - include_role:
      name: testrole
      apply:
        tags: testrole
    tags: always

  - include_role:
      name: anothertestrole
      apply:
        tags: anothertestrole
    tags: always
```

Ultimately this isn't a bug, but a misunderstanding about the functionality of these features. They are working as intended.

I'm going to go ahead and close this.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by matthias-mo** [comment]
> If you want the same behavior as the following:
> 
> ```yaml
>   roles:
>     - role: testrole
>       tags: testrole
>     - role: anothertestrole
>       tags: anothertestrole
> ```
> 
> What you want with `include_role` will look like this:

testplay.yml:

```(yaml)
---

- hosts: localhost

  vars:
    test_list:
      - var_a: "boo"
        var_b: "far"
      - var_a: "moo"
        var_b: "lar"

  tasks:
    - name: run testrole
      import_role:
        name: testrole
      vars:
        testrole_var_a: "{{ item.var_a }}"
        testrole_var_b: "{{ item.var_b }}"
      with_items: "{{ test_list }}"
      tags: testtag
 ```
 running it with
 
 `ansible-playbook --tags testtag  testplay.yml`
 
 results in the error message:
 
 ```
 ERROR! You cannot use loops on 'import_role' statements. You should use 'include_role' instead.

The error appears to be in '/home/matthias/test/testplay.yml': line 13, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: run testrole
      ^ here
 ```
 So no, this **not** what I want! And I told you before that `import_role` will not work.
 
 > Ultimately this isn't a bug, but a misunderstanding about the functionality of these features. They are working as intended.
 
I disagree.

**Comment by sivel** [comment]
I told you to use `include_role`.  You are not comprehending anything I've written about how to actually use these features.  Here is a modified playbook that does what you want:

```yaml
---

- hosts: localhost

  vars:
    test_list:
      - var_a: "boo"
        var_b: "far"
      - var_a: "moo"
        var_b: "lar"

  tasks:
    - name: run testrole
      include_role:
        name: testrole
        apply:
          tags: testtag
      vars:
        testrole_var_a: "{{ item.var_a }}"
        testrole_var_b: "{{ item.var_b }}"
      with_items: "{{ test_list }}"
      tags: always
```

This will be my last response to this issue.  If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
