### ISSUE TITLE
systemd always reports "changed" when "enabled: true" is set for an unit with Alias but without WantedBy

### ISSUE THREAD

**Issue by mprasil** [ansible/ansible#75464]
### Summary

We have some systemd services that have following Install section:

```
[Install]
Alias=foobar
```

When Ansible tries to enable such unit:

```yml
- name: Enable the unit
  systemd:
    name: foo
    enabled: true
```

The task will always return "changed", even though nothing is really done which is quite confusing.

### Issue Type

Bug Report

### Component Name

systemd

### Ansible Version

```console
$ ansible --version
ansible 2.10.7
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/toolset/lib/python3.8/site-packages/ansible
  executable location = /opt/toolset/bin/ansible
  python version = 3.8.8 (default, Mar 27 2021, 03:01:29) [GCC 8.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
```

### OS / Environment

Ubuntu 18.04, Ubuntu 20.04 and Amazon Linux 2 is where I saw this happening.

### Steps to Reproduce

```yaml (paste below)
#playbook.yml
---
- hosts: localhost
  become: true
  tasks:
    - name: Create unit file
      copy:
        dest: '/etc/systemd/system/foo.service'
        content: |
          [Unit]
          Description=foo

          [Service]
          Type=simple
          ExecStart=/bin/sh -c 'while true; do echo date; done'
          [Install]
          Alias=foobar

    - name: Enable the unit
      systemd:
        name: foo
        enabled: true
        daemon_reload: true

    - name: Enable the unit again
      systemd:
        name: foo
        enabled: true

    - name: Add WantedBy
      copy:
        dest: '/etc/systemd/system/foo.service'
        content: |
          [Unit]
          Description=foo

          [Service]
          Type=simple
          ExecStart=/bin/sh -c 'while true; do echo date; done'
          [Install]
          Alias=foobar
          WantedBy=multi-user.target

    - name: Enable the patched unit
      systemd:
        name: foo
        enabled: true
        daemon_reload: true

    - name: Enable the patched unit again
      systemd:
        name: foo
        enabled: true
```

### Expected Results

I'd expect that enabling service would only report "changed" on first `Enable the unit` task and just report "ok" for the `Enable the unit again` task. In fact after the `WantedBy` is added (`Add WantedBy` task in the playbook above) this is exactly what happens - `Enable the patched unit` reports "changed" but following `Enable patched unit again` reports "ok".

There's some edge case there with the `Alias` present in the "[Install]" section that introduces this bug, because removing `Alias` makes the "enable" task just report "ok" every time.

### Actual Results

```console
PLAY [localhost] *********************************************************************************************************************************************
TASK [Create unit file] **************************************************************************************************************************************
changed: [localhost]

TASK [Enable the unit] ***************************************************************************************************************************************changed: [localhost]

TASK [Enable the unit again] *********************************************************************************************************************************changed: [localhost]

TASK [Add WantedBy] ******************************************************************************************************************************************changed: [localhost]

TASK [Enable the patched unit] *******************************************************************************************************************************changed: [localhost]

TASK [Enable the patched unit again] *************************************************************************************************************************ok: [localhost]

PLAY RECAP ***************************************************************************************************************************************************localhost                  : ok=6    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
