### ISSUE TITLE
ansible_facts.fqdn can report an incorrect name

### ISSUE THREAD

**Issue by dubmarm** [ansible/ansible#75477]
### Summary

When gathering the ansible_facts.fqdn to use in an `assert` task, the task can fail infrequently due to a false value reported in fqdn.

### Issue Type

Bug Report

### Component Name

ansible.facts

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /Users/xxx/.ansible.cfg
  configured module search path = ['/Users/xxx/library']
  ansible python module location = /Users/xxx/.virtualenvs/msc_hpc/lib/python3.10/site-packages/ansible
  executable location = /Users/xxx/.virtualenvs/msc_hpc/bin/ansible
  python version = 3.10.0b1 (default, Jun  7 2021, 15:45:11) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/Users/xxx/.ansible.cfg) = True
DEFAULT_BECOME(/Users/xxx/.ansible.cfg) = True
DEFAULT_BECOME_METHOD(/Users/xxx/.ansible.cfg) = sudo
DEFAULT_BECOME_USER(/Users/xxx/.ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/Users/xxx/.ansible.cfg) = ['profile_roles', 'stats_to_graphite']
DEFAULT_GATHER_SUBSET(/Users/xxx/.ansible.cfg) = ['!ohai']
DEFAULT_HOST_LIST(/Users/xxx/.ansible.cfg) = ['/Users/xxx/inventories']
DEFAULT_MANAGED_STR(/Users/xxx/.ansible.cfg) = Ansible managed by the MSC Ops Team from the msc-base repo
DEFAULT_MODULE_PATH(/Users/xxx/.ansible.cfg) = ['/Users/xxx/library']
DEFAULT_REMOTE_USER(/Users/xxx/.ansible.cfg) = msc-ansible
DEFAULT_ROLES_PATH(/Users/xxx/.ansible.cfg) = ['/Users/xxx/roles']
DEFAULT_STDOUT_CALLBACK(/Users/xxx/.ansible.cfg) = debug
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/xxx/git/ansible/msc-base/scripts/vault-keyring.py
```

### OS / Environment

Centos 7.9

### Steps to Reproduce

- Create a molecule.yml and under platforms specify a name

molecule.yml
```yaml (paste below)
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  pre-commit run -a
platforms:
  - name: msc-lic-test
    box: centos-7.9
...
```

- Create a task to change the hostname
tasks/main.yml
```yaml
- name: Set hostname for valid license file.
  hostname:
    name: 'msclic.foo.bar.com'
    use: systemd
```

- Create a molecule verify task to assert and debug the ansible_facts
molecule/defaults/roles/test_role/tasks/main.yml
```yaml
- debug:
    msg: |
      fqdn: {{ ansible_facts.fqdn }}
      nodename: {{ ansible_facts.nodename }}
      hostname: {{ ansible_facts.hostname }}

- name: Assert hostname is correct.
  assert:
    that:
      - ansible_facts.nodename == 'msclic.foo.bar.com'
      - ansible_facts.hostname == 'msclic'
      - ansible_facts.fqdn == 'msclic.foo.bar.com'
```

### Expected Results

I expect ansible_facts.fqdn to report `msclic.foo.bar.com`

### Actual Results

```console
-For some odd reason, the ansible_facts.fqdn is showing msc-lic-new.foo.bar.com

-This does NOT happen every time, instead it's ~50% of the time that it reports incorrectly.

-Molecule login reports correctly:
[vagrant@msclic ~]$ hostname
msclic.foo.bar.com

-Ansible facts reports the following:
nodename: msclic.foo.bar.com
fqdn: msc-lic-new.foo.bar.com
hostname: msclic

-The molecule test fails due to the incorrect fqdn value:

TASK [test_msc_lic : debug] ********************************************************************************************************
ok: [msc-lic-test] =>
  msg: |-
    fqdn: msc-lic-new.foo.bar.com
    nodename: msclic.foo.bar.com
    hostname: msclic

TASK [test_msc_lic : Assert hostname is correct.] **********************************************************************************
fatal: [msc-lic-test]: FAILED! => changed=false
  assertion: ansible_facts.fqdn == 'msclic.foo.bar.com'
  evaluated_to: false
  msg: Assertion failed
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
