### ISSUE TITLE
Ansible k8s module error

### ISSUE THREAD

**Issue by Sg-23** [ansible/ansible#75487]
### Summary

I am using community.kubernetes.k8s module for deploying my k8s templates but I'm getting the error 
**"msg": "'template' is only supported parameter for 'k8s' module."**
According to ansible official documentation and example, template parameter is supported for community.kubernetes.k8s and not for k8s module.
Ansible version: 2.10.12

### Issue Type

Bug Report

### Component Name

community.kubernetes.k8s

### Ansible Version

```console
$ ansible --version
2.10.12
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Ubuntu

### Steps to Reproduce

```
- name: Installing operator
  community.kubernetes.k8s:
    state: present
    template: '../roles/operators/templates/install.yaml.j2'

```

### Expected Results

Template should be applied to the namespace.

### Actual Results

```console
"msg": "'template' is only supported parameter for 'k8s' module."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### Issue Type

Bug Report

### Component Name

!component

### Ansible Version

```console
$ ansible --version
2.10
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

ubuntu

### Steps to Reproduce

```
- name: Installing operator
  community.kubernetes.k8s:
    state: present
    template: '../roles/operators/templates/install.yaml.j2'
```

### Expected Results

Template should run and create the object.

### Actual Results

```console
"msg": "'template' is only supported parameter for 'k8s' module."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
