### ISSUE TITLE
Please add a way to disable aliases in to_yaml, to_nice_yaml

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#75497]
### Summary

Filters `to_yaml`, `to_nice_yaml` use aliases to deduplicate repeated values. Some software has rather primitive yaml parsers that do not understand such features, therefore it is impossible to generate config files acceptable for such software.
Please add a way to disable aliases in those filters.

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

For example as a `use_aliases` parameter (defaults to True for backward compatibility)
```yaml (paste below)
- copy:
    content: "{{ service_config | to_nice_yaml(indent=2, use_aliases=False) }}"
    dest: /etc/my_service/config.yaml
```
```
# True
var1: &id001
  - item1
  - item2
var2: *id001
```
```
# False
var1:
  - item1
  - item2
var2:
  - item1
  - item2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
