### ISSUE TITLE
ansible.builtin.set_fact fails to set ansible_port, but set_fact works

### ISSUE THREAD

**Issue by Celebrian** [ansible/ansible#75515]
### Summary

I am trying to change ansible_port durring a playbook run. This works fine when I use the set_fact module, but fails when using ansible.builtin.set_fact module. This should be the same module.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
ansible 2.9.6
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

### Configuration

```console
ANSIBLE_COW_SELECTION(/root/.ansible.cfg) = tux
DEFAULT_CALLBACK_WHITELIST(/root/.ansible.cfg) = ['debug', 'default', 'json', 'timer', 'tree', 'yaml']
DEFAULT_FORKS(/root/.ansible.cfg) = 50
DEFAULT_GATHERING(/root/.ansible.cfg) = explicit
DEFAULT_HOST_LIST(/root/.ansible.cfg) = ['/root/inventory:/root/inventory/:/root/hosts']
DEFAULT_ROLES_PATH(/root/.ansible.cfg) = ['/root/galaxy_roles', '/root/roles']
DEFAULT_STDOUT_CALLBACK(/root/.ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/root/.ansible.cfg) = False
INJECT_FACTS_AS_VARS(/root/.ansible.cfg) = False
RETRY_FILES_ENABLED(/root/.ansible.cfg) = False
```

### OS / Environment

Windows 10 WSL2

### Steps to Reproduce

```yaml (paste below)
---
- name: Test set_fact module
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ansible_port: 22
  tasks:
  - name: Show current ansible_port
    ansible.builtin.debug:
      msg: "ansible_port = {{ ansible_port }}"

  - name: Set ansible_port to 2222 with builtin.set_fact module
    ansible.builtin.set_fact:
      ansible_port: 2222

  - name: Show unchanged ansible_port
    debug:
      msg: "ansible_port = {{ ansible_port }}"

  - name: Set ansible_port to 2222 with set_fact module
    set_fact:
      ansible_port: 2222

  - name: Show changed ansible_port
    debug:
      msg: "ansible_port = {{ ansible_port }}"

```

### Expected Results

```
PLAY [Test set_fact module] **************************************************************************

TASK [Show current ansible_port] *********************************************************************
ok: [localhost] => changed=false
  msg: ansible_port = 22

TASK [Set ansible_port to 2222 with builtin module] **************************************************
ok: [localhost]

TASK [Show unchanged ansible_port] *******************************************************************
ok: [localhost] =>
  msg: ansible_port = 2222

TASK [Set ansible_port to 2222 with set_fact module] *************************************************
ok: [localhost]

TASK [Show changed ansible_port] *********************************************************************
ok: [localhost] =>
  msg: ansible_port = 2222

PLAY RECAP *******************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
```

### Actual Results

```console
PLAY [Test set_fact module] **************************************************************************

TASK [Show current ansible_port] *********************************************************************
ok: [localhost] => changed=false
  msg: ansible_port = 22

TASK [Set ansible_port to 2222 with builtin module] **************************************************
ok: [localhost]

TASK [Show unchanged ansible_port] *******************************************************************
ok: [localhost] =>
  msg: ansible_port = 22

TASK [Set ansible_port to 2222 with set_fact module] *************************************************
ok: [localhost]

TASK [Show changed ansible_port] *********************************************************************
ok: [localhost] =>
  msg: ansible_port = 2222

PLAY RECAP *******************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
