### ISSUE TITLE
lvol: "Bad size specification of '+100%FREE' for creating LV"

### ISSUE THREAD

**Issue by mathewatspm** [ansible/ansible#75518]
### Summary

# Module used:
* https://docs.ansible.com/ansible/2.9/modules/lvol_module.html
* https://docs.ansible.com/ansible/latest/collections/community/general/lvol_module.html

# Affected versions: 
```
$ pip freeze | grep ansible
ansible==4.4.0
ansible-core==2.11.4
ansible-tower-cli==3.3.9

$ ansible --version
ansible [core 2.11.4] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True

# ====================================

$ pip freeze  | grep ansible
ansible==4.2.0
ansible-core==2.11.2
ansible-tower-cli==3.3.9

$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True

# ====================================

$ pip freeze | grep ansible
ansible==4.1.0
ansible-core==2.11.2
ansible-tower-cli==3.3.9

$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May 14 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
  jinja version = 3.0.1
  libyaml = True

```

# Unaffected / Working version:
```
$ pip freeze | grep ansible
ansible==3.4.0
ansible-base==2.10.9
ansible-tower-cli==3.3.9

$ ansible --version
ansible 2.10.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
```

# Affected task:
```
        - name: test
          lvol:
            lv: "test"
            vg: "vg-test"
            size: "+100%FREE"
            state: present


# also tried

        - name: test
          community.general.lvol:
            lv: "test"
            vg: "vg-test"
            size: "+100%FREE"
            state: present

```

# Error:
```
"msg": "Bad size specification of '+100%FREE' for creating LV"
```

### Issue Type

Bug Report

### Component Name

lvol

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.4] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jul 16 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True


$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 00:00:00) [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
  jinja version = 3.0.1
  libyaml = True



$ ansible --version
ansible [core 2.11.2] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/someone/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/someone/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May 14 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

NAME=Fedora
VERSION="34 (Container Image)"

### Steps to Reproduce

```
        - name: test
          lvol:
            lv: "test"
            vg: "vg-test"
            size: "+100%FREE"
            state: present


# also tried

        - name: test
          community.general.lvol:
            lv: "test"
            vg: "vg-test"
            size: "+100%FREE"
            state: present

```

### Expected Results

Expect LV extended +100%FREE

### Actual Results

```console
"msg": "Bad size specification of '+100%FREE' for creating LV"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
