### ISSUE TITLE
script module print everything to stdout

### ISSUE THREAD

**Issue by braindevices** [ansible/ansible#75516]
### Summary

the script module seems print everything into stdout rather than respect the difference of stdout and stderr

### Issue Type

Bug Report

### Component Name

script

### Ansible Version

```console
ansible [core 2.11.3] 
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.11.2
  libyaml = True
```

### Configuration

```console
DEFAULT_LOG_PATH(/home/user/.ansible.cfg) = /tmp/ansible.log
DEFAULT_STRATEGY(/home/user/.ansible.cfg) = free
```

### OS / Environment

ubuntu20.04

### Steps to Reproduce

```yaml (paste below)
- name: test
  script:
    cmd:  test.sh
    executable: /bin/bash
  register: test_res
  changed_when: false

- name: show
  debug:
    msg: "{{ test.stdout }}"
```
the test.sh
```bash
#!/bin/bash

echo test stdout
>&2 echo test stderr
```

### Expected Results

stdout will be `test stdout`. stderr will be `test stderr`

### Actual Results

```console
`"stdout": "test stdout\r\ntest stderr\r\n"`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
