### ISSUE TITLE
Using map('extract' filter seems to fail in 2.10

### ISSUE THREAD

**Issue by pshunter** [ansible/ansible#75525]
### Summary

On 2.9 I could do list|map('extract', hostvars, ['somevar']). If somevar was not defined I got an undefined value in the output and that was it. Now, starting with 2.10.6, I get an 'AnsibleUndefined' value, along with : 
```
[WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
'ansible.vars.hostvars.HostVarsVars object' has no attribute 'testvar'
```

This might not be a problem per se, but it seems that one of my templates chokes because of the above warning. I'll try to come up with a minimal example if the above behvior is considered normal.
For the moment, I had to work this behavior around with : 
`mylist | map('extract', hostvars) | selectattr('slurm_slurmd_version','defined') | map(attribute='slurm_slurmd_version') | list() | unique `
but it feels more cumbersome.
Thanks

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version
2.10.10
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

docker cytopia/ansible:2.10

### Steps to Reproduce

```yaml (paste below)
- name: Test for Ansible extract bug
  hosts: localhost
  gather_facts: no
  tasks:
    - debug: msg="{{ mylist | map('extract', hostvars, ['testvar']) | list() | unique }}"
      vars:
        mylist:
          - localhost

```

### Expected Results

PLAY [Test for Ansible extract bug] ***********************************************************************************************************

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "msg": "[Undefined]"
}

### Actual Results

```console
PLAY [Test for Ansible extract bug] ********************************************

TASK [debug] *******************************************************************
[WARNING]: Falling back to Ansible unique filter as Jinja2 one failed:
'ansible.vars.hostvars.HostVarsVars object' has no attribute 'testvar'
ok: [localhost] => {
    "msg": "[AnsibleUndefined]"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
