### ISSUE TITLE
Allow non-root `dnf download` when running `download_only: yes`

### ISSUE THREAD

**Issue by FearTheBadger** [ansible/ansible#75530]
### Summary

Since dnf is not installing the packages when running `dnf download --downloadonly...`, it does not require root access to pull down the rpms. It would be nice if ansible followed the same pattern.

### Issue Type

Feature Idea

### Component Name

dnf

### Additional Information

```yaml (paste below)
    - name: Download RPM's
      dnf:
        name: "{{ item }}"
        state: present
        download_only: yes
        download_dir: "{{ rpms_path }}"
      loop: "{{ rpms }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
