### ISSUE TITLE
Can not eject 2 CDROMS community.vmware.vmware_guest

### ISSUE THREAD

**Issue by offlinejke** [ansible/ansible#75549]
### Summary

I try to eject CDROMs from vm. Observing the rules, I turn off the vm, disconnect the CDROMs and turn on the vm. I even pause between tasks to be sure. The CDROMs are not detached.

### Issue Type

Bug Report

### Component Name

community.vmware.vmware_guest{cdrom}

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Apr  5 2021, 09:00:41) [GCC 6.3.0 20170516]
  jinja version = 2.11.3
  libyaml = False
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/.ssh/id_rsa
```

### OS / Environment

Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

### Steps to Reproduce

```yaml (paste below)
    - name: Set the state of a virtual machine to poweroff
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: '{{ vm_name }}'
        folder: ESXI9
        state: powered-off
      delegate_to: localhost
      register: deploy

    - name: Sleep for 10 seconds and continue with play
      wait_for:
        timeout: 10
      delegate_to: localhost

    - name: Unattach the ISO mount from the VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ Datacenter }}"
        folder: ESXI9
        name: '{{ vm_name }}'
        state: powered-off
        guest_id: windows9Server64Guest
        esxi_hostname: "{{ esxi_hostname }}"
        force: yes
        cdrom:
          - controller_number: 0
            controller type: ide
            unit_number: 0
            state: absent
            type: iso
          - controller_number: 0
            controller type: ide
            unit_number: 1
            state: absent
            type: iso
      delegate_to: localhost

    - name: Sleep for 5 seconds and continue with play
      wait_for:
        timeout: 5
      delegate_to: localhost

    - name: Set the state of a virtual machine to poweron
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: ESXI9
        name: '{{ vm_name }}'
        state: powered-on
      delegate_to: localhost
      register: deploy
```

### Expected Results

I expected to see unmounted/ejectred drives.

### Actual Results

```console
The CDROMs are mounted, the contents can be viewed in them.
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
