### ISSUE TITLE
systemd check_mode fail starting in 2.10 for services not yet deployed.

### ISSUE THREAD

**Issue by everson** [ansible/ansible#75548]
### Summary

When running in check_mode a playbook that creates a system service and then triggering its restart, ansible gives a fatal error starting on version 2.10.0 because the service doesn't exist, while from 2.3 to 2.9, it would report as changed.

### Issue Type

Bug Report

### Component Name

systemd

### Ansible Version

```console
$ ansible --version
ansible 2.10.13
  config file = /home/jeverson/rp/ansible/ansible.cfg
  configured module search path = ['/home/jeverson/rp/ansible/modules']
  ansible python module location = /home/jeverson/.venv/ansible-2.10-p36/lib/python3.6/site-packages/ansible
  executable location = /home/jeverson/.venv/ansible-2.10-p36/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/jeverson/rp/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/jeverson/rp/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s
ANSIBLE_SSH_CONTROL_PATH(/home/jeverson/rp/ansible/ansible.cfg) = %(directory)s/%%h-%%p-%%r
DEFAULT_ACTION_PLUGIN_PATH(/home/jeverson/rp/ansible/ansible.cfg) = ['/home/jeverson/rp/ansible/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/jeverson/rp/ansible/ansible.cfg) = ['/home/jeverson/rp/ansible/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/home/jeverson/rp/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/home/jeverson/rp/ansible/ansible.cfg) = ['/home/jeverson/rp/ansible/filter_plugins']
DEFAULT_FORKS(/home/jeverson/rp/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/home/jeverson/rp/ansible/ansible.cfg) = explicit
DEFAULT_MODULE_PATH(/home/jeverson/rp/ansible/ansible.cfg) = ['/home/jeverson/rp/ansible/modules']
DEFAULT_ROLES_PATH(/home/jeverson/rp/ansible/ansible.cfg) = ['/home/jeverson/rp/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/jeverson/rp/ansible/ansible.cfg) = skippy
DEFAULT_TIMEOUT(/home/jeverson/rp/ansible/ansible.cfg) = 120
DEFAULT_VAULT_PASSWORD_FILE(/home/jeverson/rp/ansible/ansible.cfg) = /home/jeverson/.pass
DISPLAY_ARGS_TO_STDOUT(/home/jeverson/rp/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/jeverson/rp/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/jeverson/rp/ansible/ansible.cfg) = False
```

### OS / Environment

ElementaryOS
Linux work-desktop 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)
- name: copy dag-graphite-metrics.timer
  template:
    src: dag-graphite-metrics.timer.j2
    dest: /etc/systemd/system/dag-graphite-metrics.timer
  tags: dag_graphite_metrics
  notify: restart dag-graphite-metrics timer

- name: flush handlers
  meta: flush_handlers
```
handlers:
```yaml (paste below)
- name: restart dag-graphite-metrics timer
  systemd:
    enabled: yes
    state: restarted
    daemon_reload: yes
    name: dag-graphite-metrics.timer
```

### Expected Results

From ansible 2.3 to 2.9, I get:

```
RUNNING HANDLER [mod.airflow : restart dag-graphite-metrics timer enabled=True, state=restarted, daemon_reload=True, name=dag-graphite-metrics.timer] *************************************
Saturday 21 August 2021  03:21:02 -0300 (0:00:02.261)       0:02:54.606 *******
changed: [my-airflow-server]
```

### Actual Results

```console
In ansible 2.10, 3.0, 3.4, 4.4 I get:

RUNNING HANDLER [mod.airflow : restart dag-graphite-metrics timer enabled=True, state=restarted, daemon_reload=True, name=dag-graphite-metrics.timer] ***
Saturday 21 August 2021  17:58:01 -0300 (0:00:01.387)       0:01:48.390 *******
fatal: [my-airflow-server]: FAILED! => {"changed": false, "msg": "Could not find the requested service dag-graphite-metrics.timer: host"}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
