### ISSUE TITLE
Changing hostname and gathering hostname facts is not consistant

### ISSUE THREAD

**Issue by jooola** [ansible/ansible#75546]
### Summary

When changing the host name of a target, the fact are properly updated. But  gathering the facts again gives me wrong data.

### Issue Type

Bug Report

### Component Name

hostname, setup

### Ansible Version

```console
ansible 2.10.6
  config file = /home/jo/linux/ansible/ansible.cfg
  configured module search path = ['/home/jo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jo/linux/ansible/.direnv/python-3.7.3/lib/python3.7/site-packages/ansible
  executable location = /home/jo/linux/ansible/.direnv/python-3.7.3/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

### Configuration

```console
ANSIBLE_PIPELINING(/home/jo/linux/ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/jo/linux/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/jo/linux/ansible/ansible.cfg) = $PWD/cache
CACHE_PLUGIN_TIMEOUT(/home/jo/linux/ansible/ansible.cfg) = 86400
DEFAULT_BECOME_ASK_PASS(/home/jo/linux/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/jo/linux/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/jo/linux/ansible/ansible.cfg) = ['/home/jo/linux/ansible/hosts']
DEFAULT_STDOUT_CALLBACK(/home/jo/linux/ansible/ansible.cfg) = yaml
DEFAULT_STRATEGY(/home/jo/linux/ansible/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/jo/linux/ansible/ansible.cfg) = ['/home/jo/linux/ansible/.direnv/python-3.7.3/lib/python3.7/site-packages/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/home/jo/linux/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/jo/linux/ansible/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/jo/linux/ansible/ansible.cfg) = False
```

### OS / Environment

Debian 10 on controller
Debian 11 on target

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: print facts
      debug:
        msg: |
          hostname: {{ ansible_hostname }}
          domain: {{ ansible_domain }}
          fqdn: {{ ansible_fqdn }}

    - name: change hostname
      hostname:
        name: new-name.example.com

    - name: deploy hosts file
      copy:
        content: |
          127.0.0.1	localhost
          127.0.1.1	new-name new-name.example.org

          # The following lines are desirable for IPv6 capable hosts
          ::1     localhost ip6-localhost ip6-loopback
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644

    - name: print facts
      debug:
        msg: |
          hostname: {{ ansible_hostname }}
          domain: {{ ansible_domain }}
          fqdn: {{ ansible_fqdn }}

    - name: re-read facts
      setup:

    - name: print facts
      debug:
        msg: |
          hostname: {{ ansible_hostname }}
          domain: {{ ansible_domain }}
          fqdn: {{ ansible_fqdn }}
```

### Expected Results

I expect that gathering fact again don't give me the wrong data, and use the values updated by the hostname change. 

### Actual Results

```console
Using /home/jo/linux/ansible/ansible.cfg as config file
BECOME password: 

PLAY [all] *******************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************
ok: [download-auk]

TASK [print facts] ***********************************************************************************************************************************************************************************************************************************************************************
ok: [download-auk] => 
  msg: |-
    hostname: new-name
    domain: example.com
    fqdn: new-name.example.com

TASK [change hostname] *******************************************************************************************************************************************************************************************************************************************************************
changed: [download-auk] => changed=true 
  ansible_facts:
    ansible_domain: example.com
    ansible_fqdn: another-update.example.com
    ansible_hostname: another-update
    ansible_nodename: another-update.example.com
    discovered_interpreter_python: /usr/bin/python3
  name: another-update.example.com

TASK [deploy hosts file] *****************************************************************************************************************************************************************************************************************************************************************
changed: [download-auk] => changed=true 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  checksum: 6af47557ad4a368a81236bcbcde44c26552fb60e
  dest: /etc/hosts
  gid: 0
  group: root
  md5sum: 9d944fd1410d5885542046a0773d0d59
  mode: '0644'
  owner: root
  size: 221
  src: /root/.ansible/tmp/ansible_mitogen_action_56133abdf9fc5552/source
  state: file
  uid: 0

TASK [print facts] ***********************************************************************************************************************************************************************************************************************************************************************
ok: [download-auk] => 
  msg: |-
    hostname: another-update
    domain: example.com
    fqdn: another-update.example.com

TASK [re-read facts] *********************************************************************************************************************************************************************************************************************************************************************
ok: [download-auk]

TASK [print facts] ***********************************************************************************************************************************************************************************************************************************************************************
ok: [download-auk] => 
  msg: |-
    hostname: new-name
    domain: example.com
    fqdn: another-update.example.com

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************
download-auk               : ok=7    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
