### ISSUE TITLE
[req] uri module support for Bearer scheme

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#75552]
### Summary

I would like to use `Authorization: Bearer <my token>` as a supported authentication mechanism in the URI module. I'm using this to make authenticated calls to the [Consul API](https://www.consul.io/api-docs#authentication). Since the module currently doesn't support this, I use the `headers` flag and it leaks sensitive data to logs. I'm forced to `no_log` every task as a result.

Ideally support would be added in `ansible.module_utils.urls` so that other modules could take advantage of it as needed.
### Issue Type

Feature Idea

### Component Name

uri

### Additional Information

```yaml (paste below)
uri:
   bearer_token: '{{my_token_in_ansible_vault}}'
   url: http://localhost:8500/v1/agent/register
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
