### ISSUE TITLE
Subversion module invalid validate_certs option

### ISSUE THREAD

**Issue by MassimilianoPasquini97** [ansible/ansible#75556]
### Summary

In subversion module validate_certs parameter append '--trust-server-cert' instead of '--trust-server-cert-failures=unknown-ca,cn-mismatch,other' causing module error with latest svn version.

### Issue Type

Bug Report

### Component Name

subversion

### Ansible Version

```console
ansible [core 2.11.3] 
  config file = /Users/massi/.ansible.cfg
  configured module search path = ['/Users/massi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/4.4.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/massi/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.6 (default, Jun 28 2021, 19:24:41) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
DEFAULT_HOST_LIST(/Users/massi/.ansible.cfg) = ['/Users/massi/.ansible/hosts']
```

### OS / Environment

macOS 11.5.2

### Steps to Reproduce

Package: subversion
Version: 1.10.4-1+deb10u2

```yaml (paste below)
- name: '[Debian 10 or later] Cloning subversion repositorys'
  become: yes
  ansible.builtin.subversion:
    repo: https://svn.local/repo/trunk/
    dest: /tmp/repo
    in_place: yes
    username: '{{ subversion_username }}'
    password: '{{ subversion_password }}'
```

### Expected Results

I expected the checkout of the svn repository

### Actual Results

```console
fatal: [host]: FAILED! => {"changed": false, "cmd": "/usr/bin/svn --non-interactive --no-auth-cache --trust-server-cert --username username --password-from-stdin '********' --force -r HEAD https://svn.local/repo/trunk/ /tmp/repo", "msg": "svn: E170013: Unable to connect to a repository at URL 'https://svn.local/repo/trunk/'\nsvn: E230001: Server SSL certificate verification failed: issuer is not trusted, and other reason(s)", "rc": 1, "stderr": "svn: E170013: Unable to connect to a repository at URL 'https://svn.local/repo/trunk/'\nsvn: E230001: Server SSL certificate verification failed: issuer is not trusted, and other reason(s)\n", "stderr_lines": ["svn: E170013: Unable to connect to a repository at URL 'https://svn.local/repo/trunk/'", "svn: E230001: Server SSL certificate verification failed: issuer is not trusted, and other reason(s)"], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
