### ISSUE TITLE
Ansible occasionally hangs forever when attempting  YUM or DNF installation of "container-selinux"

### ISSUE THREAD

**Issue by nick-george** [ansible/ansible#75554]
### Summary

When I try to install container-selinux on Centos 8 or Oracle Linux 8 hosts, it occasionally causes Ansible to hang forever. This issue occurs maybe one in every ten attempts to install the package. 

My gut feeling is that something in the container-selinux RPM scripts section is stalling the SSH connection. While this appears to be an issue with the container-selinux package itself, Ansible should never hang. If I manually kill the SSH connection on the control-node side, it will at least allow the playbook to continue

I have experienced this issue on Ubuntu 20.04 and 21.04 control nodes

It might be happening more on Oracle Linux 8 than Centos 8, not 100% certain. 

Container Selinux package info: 
```Installed Packages
Name         : container-selinux
Epoch        : 2
Version      : 2.164.1
Release      : 1.module_el8.4.0+886+c9a8d9ad
Architecture : noarch
Size         : 47 k
Source       : container-selinux-2.164.1-1.module_el8.4.0+886+c9a8d9ad.src.rpm
Repository   : @System
From repo    : appstream
Summary      : SELinux policies for container runtimes
URL          : https://github.com/containers/container-selinux
License      : GPLv2
Description  : SELinux policy modules for use with container runtimes.
```

Many thanks, 
Nick

### Issue Type

Bug Report

### Component Name

dnf, yum

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/user/work/gproject-testing/project/ansible.cfg) = ['/home/user/work/gproject-testing/project/roles']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/user/work/gproject-testing/project/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/user/work/gproject-testing/project/ansible.cfg) = ['/home/user/work/gproject-testing/project/roles']
DEFAULT_STDOUT_CALLBACK(/home/user/work/gproject-testing/project/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/user/work/gproject-testing/project/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/user/work/gproject-testing/project/ansible.cfg) = False
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
- name: Install docker prereq. This has a habbit of stalling on RHEL8 based systems
  dnf:
    name: container-selinux
    state: installed
  when: ansible_facts.distribution_major_version == '8'
  ignore_errors: yes #Adding this so that we can kill the SSH process and not have the rest of the playbook fail for this host

```

### Expected Results

Package is installed and Ansible continues playbook execution

### Actual Results

```console
Ansible task hangs and never (I've waited a number of hours) returns, stalling entire playbook execution.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
