### ISSUE TITLE
explicitly set "no_log: false" not taken into consideration by postgresql_user

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#75565]
### Summary

when explicitly set no_log to false in the community.postgresql_user module, the option seems not take it into consideration.

This is important in the situation where the default value is set true to mask sensitive information but set to false during password troubleshooting without turning on too much debug information.

The only way to workaround this is to remove the setting from the playbook.

### Issue Type

Bug Report

### Component Name

community.postgresql_user

### Ansible Version

```console
bash-4.4# ansible --version
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
$ ansible-config dump --only-changed

NO OUTPUT
```

### OS / Environment

CentOS 7
Ansible AWX 16.0.0

### Steps to Reproduce

set `no_log: false` in a task and run below playbook or use extra-variables in AWX
```
- name: update PostgreSQL users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_password: "{{ item.login_password | default(postgresql_pass) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  no_log: false  <----------------------------------------------------------------------- explicitly set to default value
  become: true
  become_user: postgres
```

### Expected Results

"XXXXXXXX" below to be shown as plain-text string.

```
{
  "invocation": {
    "module_args": {
      "ssl_mode": "prefer",
      "ca_cert": null,
      "login_user": "XXXXXXXX",
      "login_host": "",
      "session_role": null,
      "db": "XXXXXXXX",
      "login_unix_socket": "",
      "trust_input": true,
      "login_password": "XXXXXXXX",
      "port": 5432
    }
  },
  "changed": false,
  "is_available": true,
  "server_version": {
    "major": 9,
    "minor": 6
  },
  "_ansible_no_log": false,
  "attempts": 1
}
```

### Actual Results

```console
{
  "invocation": {
    "module_args": {
      "ssl_mode": "prefer",
      "ca_cert": null,
      "login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "login_host": "",
      "session_role": null,
      "db": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "login_unix_socket": "",
      "trust_input": true,
      "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "port": 5432
    }
  },
  "changed": false,
  "is_available": true,
  "server_version": {
    "major": 9,
    "minor": 6
  },
  "_ansible_no_log": false,  <-------------------------------------------------------------even it is indeed explicitly set to false
  "attempts": 1
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
