### ISSUE TITLE
Closing parenthesis in content of format macros incorrectly captured by ansible-doc

### ISSUE THREAD

**Issue by SirUli** [ansible/ansible#75569]
### Summary

In a custom module i had to describe how the API is expecting the input. For this one option requires a description that involves parenthesis in the code itself as you can see from the steps to reproduce

As you can see from the actual results the last parenthesis isn't captured properly into the code section. This is since the regex defined [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/doc.py#L349) looks for the next parenthesis to close the capture group. Which in this case basically captures `(` instead of `()`.

Unfortunately i'm not really an expert on Regex, therefore bear with me. I would replace the line [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/doc.py#L349) with:

```
_CONST = re.compile(r"\bC\(([.*]+)\)\n")
```

and the line [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/doc.py#L373) with (additional whitespace after the ``'`` since that one is removed with the previous regex:

```
t = cls._CONST.sub(r"`\1' ", t)        # C(word) => `word'
```

As i said, i'm no expert on regex but that at least got me the right results - i'm sure there is a better solution that doesn't involve adding whitespaces. My assuption would be that all code macros would have a space after the parenthesis of C() but also that is just an assumption at the moment. Potentially also the other macros might profit of such a change? Didn't look into that so far.

### Issue Type

Bug Report

### Component Name

lib/ansible/cli/doc.py

### Ansible Version

```console
ansible [core 2.11.4]
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/Development/venv/lib/python3.8/site-packages/ansible
  ansible collection location = ~/Development
  executable location = ~/Development/venv/bin/ansible
  python version = 3.8.0 (default, Feb 25 2021, 22:10:10) [GCC 8.4.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATHS) = ['~/Development']
DEFAULT_STDOUT_CALLBACK(~/.ansible.cfg) = debug
DEFAULT_TIMEOUT(~/.ansible.cfg) = 30
```

### OS / Environment

Any - independent

### Steps to Reproduce

```
DOCUMENTATION = r'''
---
options:
    fields:
        description:
        - Request a partial response by specifying the fields to be
        - included or excluded using a comma-separated list of field names.
        - Sub-fields can be included in parentheses C(()) (E.g. specify
        - C(item(hostname)) to include only the hostname of each item). To
        - specify the fields to be excluded, add C(!) as first sign. E.g.
        - specify C(!item(hostname)) to exclude only the
        - hostname of each item).
        type: str
        required: false
'''
```

--> Render in ansible-doc

### Expected Results

```
OPTIONS (= is mandatory):

- fields
        Request a partial response by specifying the fields to be
        included or excluded using a comma-separated list of field names.
        Sub-fields can be included in parentheses `()' (E.g. specify
        `item(hostname)' to include only the hostname of each item). To
        specify the fields to be excluded, add `!' as first sign. E.g.
        specify `!item(customProperties)' to exclude only the
        customProperties of each item).
        [Default: (null)]
        type: str
```

### Actual Results

```console
OPTIONS (= is mandatory):

- fields
        Request a partial response by specifying the fields to be
        included or excluded using a comma-separated list of field names.
        Sub-fields can be included in parentheses `(') (E.g. specify
        `item(hostname') to include only the hostname of each item). To
        specify the fields to be excluded, add `!' as first sign. E.g.
        specify `!item(customProperties') to exclude only the
        customProperties of each item).
        [Default: (null)]
        type: str
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
