### ISSUE TITLE
WinRM failure

### ISSUE THREAD

**Issue by rsbehrends** [ansible/ansible#75580]
### Summary

When executing a loop using until clause randomly returns `An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 400, Content: '' `

### Issue Type

Bug Report

### Component Name

win_shell, until

### Ansible Version

```console
$ ansible --version
ansible 2.7.11
  config file = None
  configured module search path = ['/app/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.11 (default, Jul 22 2021, 16:07:06) [GCC 6.3.0 20170516]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_FORKS(env: ANSIBLE_FORKS) = 5
DEFAULT_TIMEOUT(env: ANSIBLE_TIMEOUT) = 150
DEFAULT_VERBOSITY(env: ANSIBLE_VERBOSITY) = 0
```

### OS / Environment

Windows Server 2016

### Steps to Reproduce

Var references values:
tsm_command_win: `dsmadmc.exe`
job_retry_query_loops: `114`
job_retry_query_period: `120`

```yaml (paste below)
 - name: Wait for RST status to be Completed
      win_shell: >-
                 {{ tsm_command_win }}
                 "select status from events
                  where domain_name='{{ domain_name }}'
                  and schedule_name='{{ rst_schedule_name }}'
                  and node_name='{{ node_ISP }}'
                  order by SCHEDULED_START desc fetch first 1 row only"
      no_log: "{{ no_log_enabled }}"
      register: rst_status_completed
      until: rst_status_completed.stdout_lines.0 not in ("In Progress", "Started", "Restarted")
      retries: "{{ job_retry_query_loops | int }}"
      delay: "{{ job_retry_query_period | int }}"
      failed_when: rst_status_completed.rc != 0
      changed_when: false
```

### Expected Results

Complete loop until condition is met. 
Else, if there was a problem get a detailed output and a more meaningful error code to troubleshoot.

### Actual Results

```console
TASK [TSM_backup_missed_failed : Wait for RST status to be Completed] **********
FAILED - RETRYING: Wait for RST status to be Completed (114 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pypsrp.exceptions.WinRMTransportError: Bad HTTP response returned from the server. Code: 400, Content: ''
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
