### ISSUE TITLE
apt_repository: Allow to add repository by linking to a .list file

### ISSUE THREAD

**Issue by Porkepix** [ansible/ansible#75585]
### Summary

Some third party software providers provide directly a `.list` file on their Website, so a way to provide it as the source to `apt_repository` module, and/or to get its content to get it added to another `sources.list` file would come pretty handy.

### Issue Type

Feature Idea

### Component Name

apt_repository

### Additional Information

```yaml (paste below)
- name: Add srepository through remote .list
  ansible.builtin.apt_repository:
    repo: https://url.to.some/remote/source.list
    state: present
    filename: filename (optional if the remote one already have a name)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
