### ISSUE TITLE
smart gathering breaks remote_user

### ISSUE THREAD

**Issue by joke** [ansible/ansible#7560]
##### Summary:

When "gathering" is set to "smart" in ansible.cfg ansible re-uses the old ssh connection even if plays use a different remote user. It does not establish a new ssh connection with a different user thus commands are run under a wrong user account.
##### Steps To Reproduce:

```
- host: host00
  remote_user: user00
  tasks:
    - command: echo "{{ansible_env.USER}}"

- host: host00
  remote_user: user01
  tasks:
    - command: echo "{{ansible_env.USER}}"
```
##### Expected Results:

A new ssh connection with the correct user (remote_user) is established.
##### Actual Results:

The ssh connection is reused even though the remote_user has changed.
