### ISSUE TITLE
set_fact with default omit doesn't work as expected

### ISSUE THREAD

**Issue by lucasbasquerotto** [ansible/ansible#75607]
### Summary

`set_fact `with `default(omit)` doesn't work as expected. If the variables at set_fact are omitted, it gives the error:

`No key/value pairs provided, at least one is required for this action to succeed`

It works if at least 1 variable is defined, but if trying to use the variable, it gives an error of not being defined, even if it was used with `omit`).

I don't know if `omit` should be used in `set_fact`. If it shouldn't (if it should be used only directly in the module parameter when calling a module) this issue can be closed.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
$ ansible --version

ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
# (empty)
```

### OS / Environment

Ubuntu 20.04 in a Docker Containe running inside WSL2 (Ubuntu 20.04 image, Windows10 host)

### Steps to Reproduce

```yaml (paste below)
- name: "test1 - works (expected)"
  my_test:
    always_present: "test"
  ignore_errors : true

- name: "test2 - error (expected)"
  my_test:
    always_present: "test"
    my_value: "value 01"
    my_dict:
      my_inner_value: "value 02"
      my_inner_value_2: "inner2"
  ignore_errors : true

- name: "test3 - works (expected)"
  my_test:
    always_present: "test"
    my_value: "{{ no_var_here | default(omit) }}"
  ignore_errors : true

- name: "test4 - works (expected)"
  my_test:
    always_present: "test"
    my_dict:
      my_inner_value: "{{ no_var_here | default(omit) }}"
      my_inner_value_2: "inner2"
  ignore_errors : true

- set_fact:
    # variable for set_fact to work, otherwise error:
    # -> No key/value pairs provided, at least one is required for this action to succeed
    var_for_set_fact_to_work: "test"
    test_value: "{{ no_var_here | default(omit) }}"

- name: "test5 - error (unexpected, should work)"
  my_test:
    always_present: "test"
    my_dict:
      my_inner_value: "{{ test_value }}"
      my_inner_value_2: "inner2"
  ignore_errors : true

- name: "test6 - works (expected)"
  my_test:
    always_present: "test"
    my_dict:
      my_inner_value: "{{ test_value | default(omit) }}"
      my_inner_value_2: "inner2"
  ignore_errors : true
```

*library/mytest.py:*

```py
#!/usr/bin/python

from __future__ import absolute_import, division, print_function

from ansible.module_utils.basic import AnsibleModule

__metaclass__ = type  # pylint: disable=invalid-name

ANSIBLE_METADATA = {'metadata_version': '1.1',
                    'status': ['preview'],
                    'supported_by': 'community'}


# ===========================================
# Module execution.
#


def main():
  module = AnsibleModule(
      argument_spec=dict(
          always_present=dict(type='str', required=True),
          my_value=dict(type='raw'),
          my_dict=dict(type='raw'),
      )
  )

  my_value = module.params['my_value']
  my_dict = module.params['my_dict'] or dict()
  my_inner_value = my_dict.get('my_inner_value')

  if my_value is not None:
    module.fail_json(msg='my_value is defined: ' + my_value)
  elif my_inner_value is not None:
    module.fail_json(msg='my_inner_value is defined: ' + my_inner_value)
  else:
    module.exit_json(changed=False)


if __name__ == '__main__':
  main()
```

### Expected Results

```
TASK test1 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]

TASK test2 - error (expected)] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'my_value is defined: value 01'
...ignoring

TASK test3 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]

TASK test4 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]

TASK set_fact] ********************************************************************************************************************************************************
ok: [localhost]

TASK test5 - error (unexpected, should work)] *************************************************************************************************************************
ok: [localhost]

TASK test6 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]
```

### Actual Results

```console
TASK test1 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]

TASK test2 - error (expected)] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'my_value is defined: value 01'
...ignoring

TASK test3 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]

TASK test4 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]

TASK set_fact] ********************************************************************************************************************************************************
ok: [localhost]

TASK test5 - error (unexpected, should work)] *************************************************************************************************************************
fatal: [localhost]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'test_value' is undefined
  
    The error appears to be in '/path/to/playbook.yml': line 40, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: "test5 - error (unexpected, should work)"
          ^ here
...ignoring

TASK test6 - works (expected)] ****************************************************************************************************************************************
ok: [localhost]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
