### ISSUE TITLE
ansible_interface does not report the address for macvlan interfaces

### ISSUE THREAD

**Issue by commonism** [ansible/ansible#75626]
### Summary

Ansible fails to detect the ip address of an macvlan device on linux due to improper use of the ip address show command.

Lines of code related:
https://github.com/ansible/ansible/blob/2cbfd1e350cbe1ca195d33306b5a9628667ddda8/lib/ansible/module_utils/facts/network/linux.py#L258-L259

It has to be "ip address show dev home", "ip address show <name>" does not work for all types of interfaces.

The attached playbook has to be run multiple times as the network fact are not updated between tasks.

### Issue Type

Bug Report

### Component Name

facts/network

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.3] 
  config file = /srv/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /srv/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/srv/ansible.cfg) = ['/srv/ansible/collections']
DEFAULT_HOST_LIST(/srv/ansible.cfg) = ['/srv/ansible/hosts']
DEFAULT_ROLES_PATH(/srv/ansible.cfg) = ['/srv/ansible/roles']
```

### OS / Environment

debian buster

### Steps to Reproduce

```yaml
---
- name: the bug
  hosts:
  - localhost
  tasks:

  - name: create home interface
    command: "ip link add link {{ ansible_default_ipv4.interface }} home address 56:61:4f:7c:77:db type macvlan"
    when: ansible_interfaces and "home" not in ansible_interfaces    

  - name: up interface
    command: "ip link set up dev home"
    when: ansible_interfaces and "home" in ansible_interfaces and ansible_home.get("active",False) != True

  - name: debug interface link
    debug:
      var: ansible_home

  - name: add address to home interface
    command: "ip address add 10.17.62.100/24 dev home"
    when: ansible_home and ansible_home.get("ipv4",{}).get("address","") != "10.17.62.100"
    ignore_errors: yes # ansible does not know macvlan device addresses

  - name: interface address
    debug:
      var: ansible_home

  - name: assert
    assert:
      that: 
        - ansible_home and ansible_home.get("ipv4",{}).get("address","") == "10.17.62.100"

  - name: delete home interface
    command: "ip link delete home"
    when: ansible_interfaces and "home" in ansible_interfaces
```

### Expected Results

the interface address is reported, no assert

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "assertion": "ansible_home and ansible_home.get(\"ipv4\",{}).get(\"address\",\"\") == \"10.17.62.100\"",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
