### ISSUE TITLE
ansible 2.9 unsupport apply variable: include_role 'apply' is undefined

### ISSUE THREAD

**Issue by Smelly-calf** [ansible/ansible#75625]
### Summary

'apply' is undefined

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version
2.9.15
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Linux CentOS 7.2

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

success

### Actual Results

```console
FAILED! => {"msg": "The conditional check ''configure' in apply.tags' failed. The error was: error while evaluating conditional ('configure' in apply.tags): 'apply' is undefined\n\nThe error appears to be in 'xxx/roles/zookeeper/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: copy template to zookeeper\n  ^ here\n"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Smelly-calf** [comment]
zookeeper.yaml
```
--- 
- name: stop
  hosts: zookeeper
  remote_user: root
  tasks:
  - include_role:
      name: zookeeper
      apply:
        tags:
        - stop
  tags:
  - stop
```

roles/zookeeper/tasks/main.yaml
```
---
- name: debug apply
  debug:
    msg: "{{ apply.tags }}"
  when:
  - "'stop' in apply.tags"
```
