### ISSUE TITLE
ansible_virtualization_type undefined - Solaris

### ISSUE THREAD

**Issue by zaphodb1891** [ansible/ansible#75639]
### Summary

We have both Solaris 11 and RHEL 7 VMs running on the **same** Xen platform.

We find that the facts ...

    ansible_virtualization_role
    ansible_virtualization_type

... are defined on the RHEL VMs, but **not** the Solaris 11 machines.

The same behavior is seen on ...

ansible 2.10.12
ansible 2.9.8

In Solaris, the platform type can be seen via the command:  prtdiag

Example

```
$ prtdiag | more
System Configuration: Xen HVM domU
BIOS Configuration: Xen 4.4.4OVM 07/01/2020
```

RHEL output

```
    "msg": [
        "ansible_virtualization_role = guest", 
        "ansible_virtualization_type = xen"
    ]
```

Solaris output

```
    "msg": [
        "ansible_virtualization_role = undefined", 
        "ansible_virtualization_type = undefined"
    ]
```

### Issue Type

Bug Report

### Component Name

setup.py

### Ansible Version

```console
$ ansible --version
ansible 2.10.12
  config file = None
  configured module search path = ['/home/a0161/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.9 (default, Dec 21 2020, 11:12:03) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Solaris 11.4 11.4.26.75.4 x86_64 Xen

### Steps to Reproduce

```yaml (paste below)
---
- name: Platform - Print
  hosts: all

  tasks:

  - name: Platform - Print - Vars
    debug:
      msg:
        - "ansible_virtualization_role = {{ ansible_virtualization_role | default('undefined') }}"
        - "ansible_virtualization_type = {{ ansible_virtualization_type | default('undefined') }}"

```

### Expected Results

    "msg": [
        "ansible_virtualization_role = guest", 
        "ansible_virtualization_type = xen"
    ]

### Actual Results

```console
"msg": [
        "ansible_virtualization_role = undefined", 
        "ansible_virtualization_type = undefined"
    ]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
