### ISSUE TITLE
Conditional Environment at Play Level

### ISSUE THREAD

**Issue by leopck** [ansible/ansible#75699]
### Summary

I am currently implementing a play-level proxy environment for my customers however, I quickly realized that different customers has different environments and requires to turn on or turn off proxy environments based on their locations.

While Conditionals such as `when` or using Jinja code works well on task-level but they don't work on play-level.

This feature would be able to benefit other use cases that requires conditional environments or even conditional import playbooks on Play-level such as a multi-environment setup for various customers or various environment setups.

An example of using Jinja:
```
- name: Proxy Environment
  hosts: all
  environment:
     {% if http_proxy is defined %}"http_proxy={{ http_proxy }}"{% endif %}
     {% if https_proxy is defined %}"https_proxy={{ https_proxy }}"{% endif %}
     {% if HTTP_PROXY is defined %}"HTTP_PROXY={{ HTTP_PROXY }}"{% endif %}
     {% if HTTPS_PROXY is defined %}"HTTPS_PROXY={{ HTTPS_PROXY }}"{% endif %}
     {% if NO_PROXY is defined %}"NO_PROXY={{ NO_PROXY }}"{% endif %}
     {% if no_proxy is defined %}"no_proxy={{ no_proxy }}"{% endif %}
```

or an example of using `when`:
```
- name: Proxy environment
  hosts: all
  environment:
    HTTP_PROXY: "{{ http_proxy }}"
    HTTPS_PROXY: "{{ https_proxy }}"
    NO_PROXY: "{{ no_proxy }}"
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    when: proxy_is_on
```

### Issue Type

Feature Idea

### Component Name

play.py

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
