### ISSUE TITLE
pip module should support using pipx to install packages

### ISSUE THREAD

**Issue by tomelliff** [ansible/ansible#75713]
### Summary

I would like to be able to use Ansible to install Python packages with scripts with [`pipx`](https://github.com/pypa/pipx).

I am currently able to hack around at the `pip` module with the following Ansible to make it work:

```yaml
- name: Install packages
  register: install
  loop: "{{ python_packages }}"
  pip:
    name: "{{ item }}"
    executable: "{{ ansible_user_dir }}/.local/bin/pipx"
  changed_when: "'stderr' in install and 'done' in install.stderr"
  failed_when: "install.failed and 'msg' in install and 'already seems to be installed' not in install.msg"
```

But it would be nice if we were able to directly set eg `use pipx = true` or maybe feature detect on the `executable` and for it to then work out how to use `pipx` instead of `pip` for the action.

### Issue Type

Feature Idea

### Component Name

pip

### Additional Information

```yaml (paste below)
- name: Install packages
  register: install
  loop: "{{ python_packages }}"
  pip:
    name: "{{ item }}"
    use_pipx: true
```

or 

```yaml
- name: Install packages
  register: install
  loop: "{{ python_packages }}"
  pip:
    name: "{{ item }}"
    executable: "{{ ansible_user_dir }}/.local/bin/pipx"
```

Ideally if it detected that it's using `pipx` then it would also not concatenate a list of packages given to `name` as well (which breaks `pipx` as it's meant to install one package at a time) and instead call `pipx` in a loop too so you could go from system/user wide installing with normal `pip`:

```yaml
- name: Install packages
  register: install
  pip:
    name: "{{ python_packages }}"
```

to

```yaml
- name: Install packages
  register: install
  pip:
    name: "{{ python_packages }}"
    use_pipx: true
```

even more simply.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
