### ISSUE TITLE
Unable to retrieve / use json value when it has an @ in the key

### ISSUE THREAD

**Issue by AndyFriar** [ansible/ansible#75717]
### Summary

Trying to download from Sharepoint using the Graph API which returns a key / value pair which contains an @ in the key.
```yaml
     - name: Get test file 
      uri:
        url: https://graph.microsoft.com/v1.0/sites/{{ site_id }}/drive/root:/Test.docx?select=@microsoft.graph.downloadUrl
        return_content: yes
        method: GET
        body_format: form-urlencoded
        headers:
          Authorization: "{{ login.json.access_token }}"
          Accept: "application/json"
      register: getfile
      tags:
        - getfile

     - name: Download file
      get_url:
        url: "{{ getfile.@microsoft.graph.downloadUrl }}"
        dest: /
```
### Issue Type

Bug Report

### Component Name

uri get_url

### Ansible Version

```console
$ ansible --version

ansible [core 2.11.2]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Windows 10 WSL / Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
- name: Upload file to Sharepoint list
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Login to Microsoft
      uri:
        url: https://login.microsoft.com/{{ tenant_id }}/oauth2/v2.0/token
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "{{ app_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
      register: login
      tags:
        - login

    - name: Get test file 
      uri:
        url: https://graph.microsoft.com/v1.0/sites/{{ site_id }}/drive/root:/Test.docx?select=@microsoft.graph.downloadUrl
        return_content: yes
        method: GET
        body_format: form-urlencoded
        headers:
          Authorization: "{{ login.json.access_token }}"
          Accept: "application/json"
      register: getfile
      tags:
        - getfile

    - name: Download file
      get_url:
        url: "{{ getfile.json.@microsoft.graph.downloadUrl }}"
        dest: /
```

### Expected Results

Expect to be able to retrieve JSON keys with @ in them as Microsoft use this quite often.

JSON returned

"json": {
        "@microsoft.graph.downloadUrl": "https://xxx.sharepoint.com/teams/TestTeamSiteWithGroup/_layouts/15/download.aspx?UniqueId=02f31e1a-4d2e-465f-a52e-0252ecc12f9c&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciO-contentcut&ApiVersion=2.0",
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('site_id')/drive/root/$entity"
    },

### Actual Results

```console
TASK [Download file] ********************************************************************************************************************************************************************************************
task path: /mnt/d/github/ansible-upload/sharepoint-download.yml:55
fatal: [localhost]: FAILED! => {
    "msg": "template error while templating string: unexpected char '@' at 16. String: {{ getfile.@microsoft.graph.downloadUrl }}"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
