### ISSUE TITLE
[Cron module] Should support disabling crontob without changing it's specifications

### ISSUE THREAD

**Issue by brlin-tw** [ansible/ansible#75734]
### Summary

I would like to implement playbooks to disable/enable certain cronjob my other playbook made (it has a fixed `name` but the end-users may change the job specification a bit (like when to trigger the cronjob)).  However, this can't be done with the cron module because it always wants me to specify the cronjob specification parameters and will, certainly overwrite the existing ones.

Not sure how to implement this properly though, as it is a breaking change.

### Issue Type

Feature Idea

### Component Name

cron

### Additional Information

```yaml (paste below)
- name: disable cronjob
  become: True
  cron:
    name: 'file_check'
    cron_file: /etc/crontab
    disabled: True
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
