### ISSUE TITLE
 ansible.builtin.password does not always honor complexity char definition.

### ISSUE THREAD

**Issue by jonsflow** [ansible/ansible#75815]
### Summary

We have tried to use the  ansible.builtin.password lookup method to generate unique passwords that adhere to our complexity rules.  What we have found is that the lookup('password,.,.,.,.) call does not always generate a password with each of the char types listed.  

For example we have used 

`{{ lookup('password', '/dev/null chars=digits,ascii_lowercase,punctuation,ascii_uppercase length=16') }}`

And about every fifth run it fails to include one of the chars specified.  There also seems to be an issue when backslashes are generated in the password seems there are always 2 like its trying to delimit or something.

We were able to improve the success percentage by using the following, however we still hit cases where one of the char types were missing.

`{{ lookup('password', '/dev/null chars=0123456789,ascii_lowercase,#?!@$%^&*-,ascii_uppercase length=16') }}`

I created the following playbook and scheduled a job in tower to run this for 100 times, and the number of failures was still +/- 25%

Am I doing something wrong here or is this bug?

### Issue Type

Bug Report

### Component Name

 ansible.builtin.password

### Ansible Version

```console
ansible --version
ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
bash-4.4# ansible-config dump --only-changed
bash-4.4# ansible-config dump --only-changed
bash-4.4#
```

### OS / Environment

Centos 8, running the AWX v17 docker container, have reproduced results on Mac as well

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: generate password
      set_fact:
        new_passphrase: "{{ lookup('password', '/dev/null chars=0123456789,ascii_lowercase,#?!@$%^&*-,ascii_uppercase length=16') }}"

    - name: check if passphrase meets complexity requirements
      debug:
        msg: 'true'
      when: " new_passphrase | regex_search('^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{16,}$') "
      register: result

    - name: print result
      debug:
        msg: "{{ new_passphrase }} {{ result }}"

    - name: print result
      assert:
        that:
          - " result.msg == 'true' "
        success_msg: "{{ new_passphrase }} meets complexity requirements"
        fail_msg: "{{ new_passphrase }} does not meet complexity requirements"
```

### Expected Results

I expect to ALWAYS have a password returned that has at least 1 digit (0-9), 1 ascii_lowercase, 1 punctuation, and 1 ascii_uppercase. 

### Actual Results

```console
One of the failures from my schedule job

1
PLAY [localhost] ***************************************************************13:10:10
2
3
TASK [generate password] **************************************************13:10:10
4
ok: [localhost]
5
6
TASK [check if passphrase meets complexity requirements] ***********************13:10:10
7
skipping: [localhost]
8
9
TASK [print result] ************************************************************13:10:10
10
ok: [localhost] => {
11
    "msg": "SxYihZZ9rOTpbJWb {'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}"
12
}
13
14
TASK [print result] ************************************************************13:10:10
15
fatal: [localhost]: FAILED! => {"msg": "The conditional check ' result.msg == 'true' ' failed. The error was: error while evaluating conditional ( result.msg == 'true' ): 'dict object' has no attribute 'msg'"}
16
17
PLAY RECAP *********************************************************************13:10:10
18
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
19
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
