### ISSUE TITLE
--syntax-check cant find fault in following code

### ISSUE THREAD

**Issue by jasonwcc** [ansible/ansible#75817]
### Summary

```
---
- name: install using loop
  hosts: localhost
  vars:
   pkgs:
    -httpd
    -wget

  tasks:
  - name: dnf
    dnf:
      name: "{{ item }}"
      state: present
    loop: "{{ pkgs }}"
```

Notice in the dict pkgs, those after dash "-" no space
If perform syntax check, no error found
but attempt to play it, will get error

Its a bug i guees

### Issue Type

Bug Report

### Component Name

variable and dict

### Ansible Version

```console
$ ansible --version
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

RHEL 8.4

### Steps to Reproduce

```yaml (paste below)
---
- name: install using loop
  hosts: localhost
  vars:
   pkgs:
    -httpd
    -wget

  tasks:
  - name: dnf
    dnf:
      name: "{{ item }}"
      state: present
    loop: "{{ pkgs }}"
```

### Expected Results

I expected error when perform
ansible-playbook --syntax-check playbook.yml

### Actual Results

```console
Should return error saying
-httpd
 ^
-wget
 ^
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
```yaml
vars:
  pkgs:
    -httpd
    -wget
```

The above is valid syntax, `pkgs` is proper variable that contains string, effectively the value is `-httpd -wget`. The syntax check has no way of knowing that you intended to define a list. As such it is expected behavior that the playbook passes syntax check but fails during run time when loop expects a list.

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project
