### ISSUE TITLE
Iterating cidr_ip values on rules for ec2_group module replaces the rules instead of appending

### ISSUE THREAD

**Issue by jaimegago** [ansible/ansible#7584]
##### Issue Type:

Bug or feature request (not sure the module was ever intended to allow such iteration)
##### Ansible Version:

ansible 1.6.2
##### Environment:

OS:
Description:    Ubuntu 12.04.2 LTS
Release:    12.04
Codename:   precise

Boto:
2.28.0
##### Summary:

I need to iterate a list of IPs in the "rules" section of the ec2_group module, unfortunately only the latest in the list persist as the module is replacing each rule with the next one during the iteration instead of appending
##### Steps To Reproduce:

With AWS keys available (e.g. set in in the environment) run the following playbook

```

---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: "Testing rules iterations"
    ec2_group:
      name: "testing_ansible_rules_iterations"
      region: "us-west-1"
      description: "foo"
      rules:
        - proto: "tcp"
          from_port: "80"
          to_port: "80"
          cidr_ip: "{{ item }}/32"
    with_items:
      - "10.0.0.1"
      - "10.0.0.2"
```
##### Expected Results:

A security group testing_ansible_rules_iterations exists with 2 added rules for port 80 and 2 different IPs (i.e. 10.0.0.1 and 10.0.0.2)
##### Actual Results:

Only one of the rules exists (the one with the latest IP in the list we are iterating), each rule is being replaced with the next one instead of appending.

**Comment by jimi-c** [comment]
This is happening because the ec2_group currently sets the rules to those exactly specified, which means other rules get purged out. To do this correctly, just get rid of the with_items:

<pre>
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Testing rules iterations"
    ec2_group:
      name: "testing_ansible_rules_iterations"
      region: "us-west-1"
      description: "foo"
      rules:
        - proto: "tcp"
          from_port: "80"
          to_port: "80"
          cidr_ip: "10.0.0.1/32"
        - proto: "tcp"
          from_port: "80"
          to_port: "80"
          cidr_ip: "10.0.0.2/32"
</pre>

This is why the rules: field is a list (and it will be faster, since there is now only a single iteration). Let us know if you have any further questions regarding this. Thanks!

**Comment by jaimegago** [comment]
I need the iteration because I'm getting a list of IP dynamically from a previous task, maybe I'm trying to hard to fit this into an Ansible playbook, or maybe I'm doing it wrong, maybe I should have gone to the forum instead of opening an issue.
In any case this is what I'm trying to achieve:

Add all the pingdom servers IPs to a security group by getting the list through pingdom API, this is what I had which doesn't work because the rule iteration as I have it written isn't working hence this ticket

```
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    pingdom_api_version: "2.0"

  tasks:
  - name: "Getting the Pingdom servers IPs"
    uri: url=https://api.pingdom.com/api/"{{ pingdom_api_version }}"/probes
         method=GET
         user=pingdom_user
         password="password"
         HEADER_App-Key="My_pingdom_app_key"
    register: probes

  - name: "Adding Pingdom servers IPs to foo security group"
    ec2_group:
      name: "foo"
      region: "us-west-2"
      description: "none"
      rules:
        - proto: "tcp"
          from_port: "80"
          to_port: "80"
          cidr_ip: "{{ item.ip }}/32"
    with_items: probes.json.probes
```

**Comment by jaimegago** [comment]
If you're reading this comment, you probably want to read this:

https://groups.google.com/forum/#!topic/ansible-project/a8y1v2-R8Zw

**Comment by jimi-c** [comment]
@jaimegago we did have a PR (https://github.com/ansible/ansible/pull/7818) to add the functionality you're looking for above, so if you would like to test that PR +1's always help us merge things faster.

**Comment by rhunwicks** [comment]
The PR referred to above wasn't merged, and the replacement PR does allow groups to be added without removing the others, but I still don't think it allows you to have a list of approved CIDRs and to iterate them to create a definitive list - i.e. remove all the CIDRs that aren't in the approved list.

I think this should be reopened

**Comment by senorsmile** [comment]
+1 to reopening.  If I come up with anything, I'll post back here.

**Comment by viesti** [comment]
I ran into this too and made a workaround by creating the rules list with a filter plugin: https://gist.github.com/viesti/1febe79938c09cc29501. This is bending jinja2 to do what I wanted. I'm thinking that there probably isn't one simple way of specifying an arbitrary rule list without dropping (or should I say elevating :)) to pure Python.

**Comment by zyphlar** [comment]
I'm not quite generating them dynamically, just separating them out into a variable, so I did this:

**vars**

```
my_cool_rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "1.2.3.4/32"
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "2.3.4.5/32"
```

**tasks.yml**

```
    - ec2_group:
        name: my-cool-group
        description: my-cool-group
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ ec2_region }}"
        rules: "{{ my_cool_rules }}"
```

**Comment by bcattle** [comment]
I got around this by running a task to first clear all rules, then run a second using `with_items` with `purge_rules` set to `no`. Works great:

```
tasks:
    - name: Clear the "Postgres DigitalOcean" Security Group
      ec2_group:
        name: Postgres DigitalOcean
        description: Security group that allows access to Postgres only from designated IPs
        state: present
        region: us-west-2
        rules:

    - name: Add the new droplets to the EC2 "Postgres DigitalOcean" Security Group
      ec2_group:
        name: Postgres DigitalOcean
        description: Security group that allows access to Postgres only from designated IPs
        state: present
        region: us-west-2
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 5432
            to_port: 5432
            cidr_ip: "{{ item }}/32"
      with_items: "{{ groups['do'] }}"
```
