### ISSUE TITLE
Adding the concept of prepare-playbook in ansible.cfg

### ISSUE THREAD

**Issue by xeor** [ansible/ansible#75878]
### Summary

When using Ansible, I often want to enforce some rules when others are running a playbook, show some information, or do some other preparation-steps.

I would like to suggest adding an option in `ansible.cfg` for a preparation playbook that will always run first.

### Issue Type

Feature Idea

### Component Name

playbook, config

### Additional Information

Example
```
[defaults]
prepare_playbook = ./prepare.yml
```

This option will effectively add a task at the very beginning of whatever you want to run using import_playbook.

```yaml
---

# These two lines are not in the playbook yaml, but added logically
- name: Run preparation playbook
  import_playbook: ./prepare.yml

- name: Setup webservers
  hosts: webservers
  tasks:
    ...
```

This will make some more advanced usecases possible, like enforcing `--limit`, prompting based on conditions and a lot more.

Example prepare.yml with these usecases

```yaml
---

- name: Check inventory
  hosts: all
  run_once: true
  connection: local

  tasks:
    - name: Check if limit is defined
      fail:
        msg: You must set --limit
      when: ansible_limit is not defined

    - name: Doublecheck host-count
      block:
        - name: Getting host-count
          set_fact:
            host_count: '{{ ansible_play_hosts_all | length }}'

        - name: Pause if too many hosts
          pause:
            prompt: 'Are you sure you want to run this on {{ host_count }} hosts?'
          when: host_count|int >= 100

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
