### ISSUE TITLE
With strategy=free + roles, hosts shouldn't wait for other hosts to finish roles tasks

### ISSUE THREAD

**Issue by mhansen** [ansible/ansible#75879]
### Summary

When I use the [`free` strategy](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/free_strategy.html#free-strategy), and some `roles:` in my playbook, the execution of some hosts is held up waiting for some other hosts to finish their role.

### Issue Type

Bug Report

### Component Name

ansible.builtin.free

### Ansible Version

```console
$ ansible --version
ansible-playbook 2.10.2
  config file = /Users/mark/projects/pis/ansible.cfg
  configured module search path = ['/Users/mark/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.12 (default, Aug 31 2021, 04:09:21) [Clang 12.0.5 (clang-1205.0.22.9)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/Users/mark/projects/pis/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/Users/mark/projects/pis/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/Users/mark/projects/pis/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/mark/projects/pis/ansible.cfg) = ['/Users/mark/projects/pis/hosts.yml']
DEFAULT_STDOUT_CALLBACK(/Users/mark/projects/pis/ansible.cfg) = yaml
DEFAULT_STRATEGY(/Users/mark/projects/pis/ansible.cfg) = free
INTERPRETER_PYTHON(/Users/mark/projects/pis/ansible.cfg) = /usr/bin/python3
```

### OS / Environment

macOS Big Sur

### Steps to Reproduce

ansible.cfg:

```
cat ansible.cfg 
[ssh_connection]
pipelining = True
# ssh_args = -C -o ControlMaster=auto -o ControlPersist=30m
# https://github.com/ansible/ansible/issues/26359

[defaults]
inventory = hosts.yml
forks = 50
# Defaults to /usr/bin/python otherwise
interpreter_python = /usr/bin/python3
# https://sketchingdev.co.uk/blog/profiling-ansible-playbooks-to-csv.html
callback_whitelist = profile_tasks
callback_enabled = ctf
# Pretty-prints debug output
stdout_callback = yaml
strategy = free
```

Note I'm using `callback_enabled = ctf` which is an [in-development tracer](https://twitter.com/MarkHnsn/status/1444438992506605568) that logs the start and end times of task execution in Chrome's Trace Event Format for visualising.

site.yml:

```
#!/usr/bin/env ansible-playbook
---
- name: apply common configuration
  hosts: pis,thinkpads
  gather_facts: false
  roles:
    - common
    - fish
    - tailscale
    - nodeexporter

- name: apply pis configuration
  hosts: pis
  gather_facts: false
  roles:
    - pi
  tags:
    - pi

- name: apply serial configuration
  hosts: pis
  gather_facts: false
  roles:
    - serial
  tags:
    - serial

- name: apply thinkpads configuration
  hosts: thinkpads
  gather_facts: false
  roles:
    - dropbear
    - thinkpad
  tags:
    - thinkpads

- name: install docker
  hosts: pis,thinkpads
  gather_facts: false
  roles:
    - install_docker
  tags:
    - install_docker
- name: docker_compose
  hosts: pis,thinkpads
  gather_facts: false
  roles:
    - docker_compose
  tags:
    - docker_compose
```

I'll try to get a more minimal test case soon.

### Expected Results

I expect to see in the trace, every host running tasks as fast as they can without waiting on other hosts, see docs: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/free_strategy.html#free-strategy :

> With the free strategy, unlike the default linear strategy, a host that is slow or stuck on a specific task won’t hold up the rest of the hosts and tasks.

### Actual Results

I see, in the timeline trace of ansible task execution in ui.perfetto.dev, a lot of hosts waiting for other hosts to finish work. Each host is a horizontal track on this view, and time proceeds left to right, blocks indicate time executing tasks:

![image](https://user-images.githubusercontent.com/105529/135833151-50f848f9-fef1-482a-bee2-46fd9931af62.png)

It seems each top-level bullet point in `site.yml` is serialised, with each host waiting for the slowest host to finish that `site.yml` bullet before continuing to the next set of roles.

This makes the entire process run a bunch slower for some hosts than it otherwise needs to.

I might just be holding it wrong, or building my `site.yml` in the wrong way, I'm an Ansible newbie.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
