### ISSUE TITLE
Run command outside ansible and come back if finished succesfully

### ISSUE THREAD

**Issue by redsigma** [ansible/ansible#75880]
### Summary

I am trying to use the helm module with ansible and i want to use the `--debug` parameter to get information while the command is running. The module doesnt have this feature so i thought of using the shell module but this also doesn't display any output while the command is running. 

I want to know if it's possible for ansible to run a shell command outside ansible , which is the same as running the command manually in a a new terminal. And maybe make ansible know if the command failed or not so it can continue or not. 

### Issue Type

Feature Idea

### Component Name

shell

### Additional Information

```yaml (paste below)
 tasks:
  - name: Run command in a new window
    shellc:
      "bash -c 'timedatectl' "
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
