### ISSUE TITLE
list of required parameters for ec2_metric_alarm module is wrong

### ISSUE THREAD

**Issue by jaimegago** [ansible/ansible#7594]
##### Issue Type:

bug report
##### Ansible Version:

ansible 1.6.2
##### Environment:

OS:
Description: Ubuntu 12.04.2 LTS
Release: 12.04
Codename: precise

Boto:
2.28.0
##### Summary:

The ec2_metric_alarm modules documentation lists only 2 required parameters, during my testing that is not the case (it'd seem they're almost all required)
##### Steps To Reproduce:

1) Run this playbook once (it should work)

```

---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "testing ec2 alarm module"
      ec2_metric_alarm:
        region: "ap-southeast-1"
        state: "present"
        name: "cpu-low"
        metric: "CPUUtilization"
        namespace: "AWS/EC2"
        statistic: Average
        comparison: "<="
        threshold: 5.0
        period: 300
        evaluation_periods: 3
        unit: "Percent"
        description: "testing"
        dimensions: {'InstanceId':'i-XXX'}
```

2) Now comment out one of the parameters

```

---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "testing ec2 alarm module"
      ec2_metric_alarm:
        region: "ap-southeast-1"
        state: "present"
        name: "cpu-low"
        metric: "CPUUtilization"
        namespace: "AWS/EC2"
        statistic: Average
        comparison: "<="
        threshold: 5.0
        period: 300
        #evaluation_periods: 3
        unit: "Percent"
        description: "testing"
        dimensions: {'InstanceId':'i-fe66abd6'}
```
##### Expected Results:

Both playbooks should work fine since "evaluation_periods" is not documented as a required parameter
##### Actual Results:

the second runs fails with the following message

```
failed: [localhost] => {"failed": true}
msg: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <Error>
    <Type>Sender</Type>
    <Code>MalformedInput</Code>
  </Error>
  <RequestId>some_UUID_generated_by_AWS</RequestId>
</ErrorResponse>


FATAL: all hosts have already failed -- aborting
```
