### ISSUE TITLE
Add trim_blocks=False argument to template lookup plugin

### ISSUE THREAD

**Issue by mdavis-xyz** [ansible/ansible#75962]
### Summary

The `template` module has an option for `trim_blocks=False`. I would like to have the same option with the `template` lookup plugin.

An alternative solution would be to make `trim_blocks` in the `template` module recursively apply to any template lookups inside that template.

My use case is that I'm generating AWS CloudFormation yaml templates with Jinja. Since some CloudFormation templates require nested json or yaml as an escaped literal string inside the overall yaml, I have recursive templates. For the top-level template I use the `template` module with `trim_blocks=False`. And inside that template I use stuff like `{{ lookup('template', x) | from_yaml | to_json }}` plugin to evaluate other templates, then convert them to json to embed as a string inside my overall yaml template. This fails currently because the default (and only) behavior of `lookup('template', x)` is to trim blocks. When my jinja template is of something where indentation matters (e.g. yaml), this messes with the indentation in a way that changes the meaning of the file entirely, typically resulting in something that is broken and undeployable. This might sound like an obscure use case, but really this applies to any use of the template plugin to render a template where leading whitespace matters (e.g. yaml, python, markdown)

### Issue Type

Feature Idea

### Component Name

lib/ansible/plugins/lookup/template.py

### Additional Information

`test.j2` (note the leading spaces)

```
  First Line
  {# comment #}
  Second Line
  {#-comment #}
  third line
```

playbook:

```
---
- hosts: localhost
  connection: local
  vars:
    path: 'test.j2'
    module_output: 'module-output.txt'
    plugin_output: 'plugin-output.txt'
  tasks:
    - name: use template module
      template:
        src: "{{ path }}"
        dest: "{{ module_output }}"
        trim_blocks: False

    - name: lookup plugin
      copy:
        content: "{{ lookup('template', path, trim_blocks=False) }}"
        dest: "{{ plugin_output }}"
        
    - name: compare
      assert:
        that:
        - lookup('file', plugin_output) == lookup('file', module_output)
```

Desired behavior: assertion passes

Current behavior: assertion fails. `trim_blocks` in lookup is ignored.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
