### ISSUE TITLE
how to disable upper in template

### ISSUE THREAD

**Issue by zhangguanzhang** [ansible/ansible#76026]
### Summary

the playbook
```
- hosts: "{{ run| default('all')}}"
  vars:
    test: true
  tasks:
  - name: test
    template: src=etcd.service dest=/tmp/etcd.test
```
I don't want `True`， just want `true`
```
$ cat templates/etcd.service 
{{ test }}
$ cat /tmp/etcd.test 
True
```

### Issue Type

Bug Report

### Component Name

yum

### Ansible Version

```console
$ ansible --version

ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
```


### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

.

### Steps to Reproduce

the playbook
```
- hosts: "{{ run| default('all')}}"
  vars:
    test: true
  tasks:
  - name: test
    template: src=etcd.service dest=/tmp/etcd.test
```
I don't want `True`， just want `true`
```
$ cat templates/etcd.service 
{{ test }}
$ cat /tmp/etcd.test 
True
```

### Expected Results

I don't want `True`， just want `true`

### Actual Results

```console
.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
