### ISSUE TITLE
file validate variable should work with array

### ISSUE THREAD

**Issue by maage** [ansible/ansible#76050]
### Summary

I have complex command to validate a file and shlex messes up and I really do not want to play against shlex and yaml formatting. It would be so much easier just to use argv style validate command.

Currently it is not posssible to use array as:
https://github.com/ansible/ansible/blob/96372cecea52e8ae4c235e3ad48e8cdee28c7489/lib/ansible/modules/assemble.py#L258
this transforms my example array to a string "['cmd', 'arg1', 'arg2', '/home/user/.ansible/tmp/ansible-tmp-1634294119.7910273-179242-159723901491440/source', 'arg4']" and this obviously does not work.

### Issue Type

Feature Idea

### Component Name

file

### Additional Information

```yaml (paste below)
file:
  path: myfile
  validate:
    - cmd
    - arg1
    - arg2
    - '%s'
    - arg4
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
