### ISSUE TITLE
community.crypto.x509_crl_info - feature request to have CRL info returned with hex serial numbers

### ISSUE THREAD

**Issue by jonsflow** [ansible/ansible#76057]
### Summary

I am trying to use community.crypto.x509_crl_info  to parse a CRL string received from our CA.  It returns the revoked certificate serial numbers in decimal format which makes it difficult to compare to the hex formatted serial numbers that are used by our various application services.

Some of the things I've tried are using the ('%X' % decimal_serial) method for converting the decimal strings to hex strings, however for cases where there is a leading zero in the hex string this method does not retain the leading zero.  

For example, a cert with the hex serial number:
0804E52686B8D1D677350BA7766BBD00B778B892
is rendered in decimal format with community.crypto.x509_crl_info:
45781090970669344851050903153492539723019237522
Then when I use ('%X' % decimal_serial) we get:
804E52686B8D1D677350BA7766BBD00B778B892
which as you can see is missing the leading zero, and will cause the revokation check to fail flagging the cert as revoked.

I am now looking at using the shell module to run `echo "{{crl.content}}" | openssl crl -text` to parse the serial numbers.  It would be much better if I could avoid using the shell module for this.

### Issue Type

Feature Idea

### Component Name

lib/ansible/modules/crypto/x509_crl_info.py

### Additional Information

```yaml (paste below)

    - name: Get information on CRL
      community.crypto.x509_crl_info:
        content: "{{ crl_pem.content }}"
      register: crl_list

    - name: Print the information
      debug:
        msg: "{{ ('%X' % item.serial_number) }}"
      loop: "{{ crl_list.revoked_certificates }}"

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
