### ISSUE TITLE
Unarchive with "exclude" causes group/owner to be not set

### ISSUE THREAD

**Issue by bluikko** [ansible/ansible#76067]
### Summary

Trying to unarchive a .zip file with the "exclude" parameter set makes the unarchived files have wrong "owner" and "group".

I am 80% certain this did not happen in 2.9, it does happen in 2.11.

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib64/python3.6/site-packages/ansible
  ansible collection location = /home/x/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
I don't think this is relevant.
```

### OS / Environment

CentOS 7

### Steps to Reproduce

```yaml (paste below)
- name: fail to set owner and group to apache, instead they are root
  unarchive:
    src: https://builds.matomo.org/matomo-latest.zip
    dest: /tmp
    exclude: "How to install Matomo.html"
    group: apache
    owner: apache
    remote_src: true
```

### Expected Results

All files extracted from archive should have owner and group set to "apache".

### Actual Results

```console
Files have owner and group set to "root".
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
