### ISSUE TITLE
unarchive module - allow for HTTP username/password

### ISSUE THREAD

**Issue by senderic** [ansible/ansible#76076]
### Summary

Using the unarchive module, I'd like to download a zip file from a remote_src, but the HTTP server requires a username and password.  

I don't see mention of username/password in the documentation (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html) so I figure the only way to do it is to hack our way around it?

So this is a 2 part issue:

1. The unarchive module should allow for http_username and http_password when remote_src is set to yes.
2. For now, is there a way around this without creating two separate tasks. One task to `get_url` and download the zip and a second to unarchive the local file? 

### Issue Type

Feature Idea

### Component Name

unarchive

### Additional Information

```yaml (paste below)
- name: "Download CORE {{ core_version }}"
  unarchive:
    src: "{{ nexus_raw }}/infrastructure/build-files/core-{{  core_version }}.zip"
    dest: /usr/local/src
    remote_src: yes
    http_username: "{{ my_username }}"
    http_password: "{{ my_password }}"
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
