### ISSUE TITLE
Module remote_tmp /opt/odoo/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct permissions manually

### ISSUE THREAD

**Issue by oerp-odoo** [ansible/ansible#76098]
### Summary

When I initially run my playbook, which installs packages for docker and creates some data to start my App containers, I get this warning:

```
TASK [docker-init : Install docker SDK] *******************************************************************************************************************************************************************
Trečiadienis 20 spalio 2021  20:57:16 +0300 (0:00:01.360)       0:01:21.493 *** 
[WARNING]: Module remote_tmp /opt/odoo/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with
the correct permissions manually
changed: [dev]
```
In this step, user is created (with home directory) and then `pip` install executed to be run with `--user` flag, so packages are installed for that user only.

This of course happens only once, when that directory is created. 
Though owner is correct for that directory, so why would it put a warning?

NOTE. `opt/odoo` is home directory for `odoo` user.

### Issue Type

Bug Report

### Component Name

ansible.builtin.pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6] 
  config file = /home/oerp/.ansible.cfg
  configured module search path = ['/home/oerp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oerp/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/oerp/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/oerp/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
CALLBACKS_ENABLED(/home/oerp/.ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/oerp/.ansible.cfg) = 25
DEFAULT_HOST_LIST(/home/oerp/.ansible.cfg) = ['/home/oerp/src/ansible-odoo/inventory']
DEFAULT_ROLES_PATH(/home/oerp/.ansible.cfg) = ['/home/oerp/src/ansible-odoo/roles', '/home/oerp/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/oerp/.ansible.cfg) = /home/oerp/.ansible_secret
```

### OS / Environment

Debian 11

### Steps to Reproduce

```yaml (paste below)
# Tasks for app user specifically.

- name: create user for docker
  ansible.builtin.user:
    name: "{{ app_user }}"
    groups:
      - docker
    create_home: true
    home: "{{ app_root_path }}"
    skeleton: "/etc/skel"
    system: true
    # Setting this shell so system user would still use bashrc.
    shell: /bin/bash

- name: Install docker SDK
  ansible.builtin.pip:
    name:
      - docker==5.0.3
      - docker-compose==1.29.2
    extra_args: --user
  become: true
  become_user: "{{ app_user }}"
```

By default I connect as `root`, but some tasks are run as `app_user`. 

### Expected Results

Normally there should be no Warning or should be clear what it is causing it?..

### Actual Results

```console
TASK [docker-init : Install docker SDK] *******************************************************************************************************************************************************************
Trečiadienis 20 spalio 2021  20:57:16 +0300 (0:00:01.360)       0:01:21.493 *** 
[WARNING]: Module remote_tmp /opt/odoo/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with
the correct permissions manually
changed: [dev]
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
