### ISSUE TITLE
jinja2_native breaks playbook on ansible 2.11.5

### ISSUE THREAD

**Issue by xaviermerino** [ansible/ansible#76093]
### Summary

I am trying to append items to a list (that starts empty) in a loop. While this normally works when `JINJA2_NATIVE` is set to `False`, changing it to true broke my playbook. This seems to be related to issue #69196, but I am not sure.

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.5] 
  config file = /home/xavier/Documents/environments/minio_backend_co/ansible.cfg
  configured module search path = ['/home/xavier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/xavier/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 2.11.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_JINJA2_NATIVE(/home/xavier/Documents/environments/minio_backend_co/ansible.cfg) = True
```

### OS / Environment

Ubuntu 21.04

### Steps to Reproduce

```yaml (paste below)
# - name: Obtaining Storage Device(s) Information
# vars:
#    device_list: >
#      {% set devices = [] -%}
#      {% for k, v in ansible_devices.items() if not v.partitions -%}
#      {% if k.startswith('/dev/') -%}
#      {% set _dummy = devices.append(k) -%}
#      {% else -%}
#      {% set _dummy = devices.append('/dev/' + k) -%}
#      {% endif -%}
#      {% endfor -%}
#      {{ devices | map('regex_search', '\/dev\/(xvd|nvme|sd).+') | select('string') | list }}
#  set_fact:
#    devices: "{{ device_list }}"

# For simplicity, I added a devices variable below since you might not have several devices in your setup. 

- name: Preparing Filesystem Locations
  vars: 
    devices:
      - /dev/sda
      - /dev/sdb
  set_fact:
    filesystems: "{{ filesystems | default([]) }} + ['{{ item }}1']"
  loop: "{{ devices }}"
  loop_control:
    label: "{{ item }}1"
```

### Expected Results

I expected it to create a list of filesystems such as `["/dev/sda1", "/dev/sdb1"]` but instead I got an error. 

```
FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: [] + ['/dev/sdd1'] + ['/dev/sdb1'] + ['/dev/sde1'] + ['/dev/sdc1']. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```

This works fine if the JINJA2_NATIVE is `False`. 

### Actual Results

```console
TASK [host_setup : Create 'ext4' Filesystem on Attached Disks] *****************************************************************************************************************************************************************************************************************
task path: /home/xavier/Documents/environments/minio_backend_co/playbooks/roles/host_setup/tasks/setup_storage_devices.yml:19
fatal: [hadoop-slave-1]: FAILED! => {
    "msg": "Invalid data passed to 'loop', it requires a list, got this instead: [] + ['/dev/sdd1'] + ['/dev/sdb1'] + ['/dev/sde1'] + ['/dev/sdc1']. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."
}
META: noop
META: noop
META: noop
META: noop
META: role_complete for hadoop-master
META: ran handlers
META: ran handlers
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
