### ISSUE TITLE
ios_command show run returns extra backslash

### ISSUE THREAD

**Issue by ericnlv** [ansible/ansible#76119]
### Summary

When I run the following:

ios_command:
  commands:
  - show run
register: MyShowRun

The results have an extra back slash. I am seeing this specifically in the voice translation sections of the output.

### Issue Type

Bug Report

### Component Name

ios_command

### Ansible Version

```console
$ ansible --version
 ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/eric/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/eric/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/eric/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/eric/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
Did not return any output
```

### OS / Environment

Oracle VM VirtualBox
Ubuntu 20.04.3 LTS 64bit

### Steps to Reproduce

```yaml (paste below)
- name: Collect Cisco Voice Translation Rules and Profiles
  hosts: routers
  gather_facts: false
  connection: network_cli
  become: true
  
  tasks:
    - name: Gather Legacy Facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: ios
      
    - name: Show Run for Translation Rules
      ios_command:
        commands:
        - show run | section voice translation-rule
      register: translation_rule  
      
    - name: Show Run for Translation Profiles
      ios_command:
        commands:
        - show run | section voice translation-profile
      register: translation_profile       

    - name: Write results to file
      copy:
        content: 
          "Host Name: {{ item }}\rWhen collected: {{ '%Y-%m-%d %H:%M:%S' | strftime }}\r\r{{ translation_rule.stdout | replace('\\n', '\n') }}\r\r{{ translation_profile.stdout | replace('\\n', '\n') }}"      
        dest: "~/Documents/{{ item }}.txt"
      with_items: "{{ ios.ansible_facts.ansible_net_hostname }}"
```

### Expected Results

voice translation-rule 4
 rule 1 /^91\(.*\)/ /1\1/
 rule 3 /^9\(.*\)/ /\1/

### Actual Results

```console
voice translation-rule 4
 rule 1 /^91\\(.*\\)/ /1\\1/
 rule 3 /^9\\(.*\\)/ /\\1/
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
