### ISSUE TITLE
ec2 group module not removing rules correctly from security groups

### ISSUE THREAD

**Issue by CorbanR** [ansible/ansible#7611]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.6.2 (release1.6.2 549f67c0d8) last updated 2014/05/29 15:28:08 (GMT -600)
##### Environment:

Mac OSX Version 10.9.3
##### Summary:

This is a very specific use case.
ec2 group module not removing rules correctly from security groups NOT originally created by ansible
##### Steps To Reproduce:
1. Pick an existing security group 
2. Added one new additional rule via ansible module to test (this added the rule correctly)
3. Deleted the new rule to test. This deleted the rule before and after on aws, but not the one it was supposed to delete

Example:  Adding New rule 

```
- name: Update web Security Group
  local_action:
    module: ec2_group
    name: web
    description: web
    region: '{{ aws_region }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    rules:
      #HTTP
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      ###
      #HTTPS             
      - proto: tcp      
        from_port: 443
        to_port: 443     
        cidr_ip: 0.0.0.0/0
      ###
      #Custom SSH port, Person1 
      - proto: tcp
        from_port: 3200
        to_port: 3200
        cidr_ip: 192.168.1.1/32
      ###
      #Custom SSH port, Person 2 NEW RULE 
      - proto: tcp
        from_port: 3200
        to_port: 3200
        cidr_ip: 192.168.1.2/32
      ###
      #Custom SSH port, Company
      - proto: tcp
        from_port: 3200
        to_port: 3200
        cidr_ip: 192.168.1.3/32 
```

![addednewrule](https://cloud.githubusercontent.com/assets/1918683/3137386/f4c6549e-e851-11e3-9793-846b924f839e.png)

Example:  Removing new rule

```
- name: Update web Security Group
  local_action:
    module: ec2_group
    name: web
    description: web
    region: '{{ aws_region }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    rules:
      #HTTP
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      ###
      #HTTPS             
      - proto: tcp      
        from_port: 443
        to_port: 443     
        cidr_ip: 0.0.0.0/0
      ###
      #Custom SSH port, Person1 
      - proto: tcp
        from_port: 3200
        to_port: 3200
        cidr_ip: 192.168.1.1/32
      ###
      #Custom SSH port, Company
      - proto: tcp
        from_port: 3200
        to_port: 3200
        cidr_ip: 192.168.1.3/32 
```

![removednewrule](https://cloud.githubusercontent.com/assets/1918683/3137389/fb5e9ce4-e851-11e3-898b-d30a47346c6a.png)
##### Expected Results:

Only the rule that was removed from playbook, should be removed 
##### Actual Results:

deleted the rule before and after on aws, but not the one it was supposed to delete
