### ISSUE TITLE
report --check=yes mode as skipped instead of changed

### ISSUE THREAD

**Issue by itayporezky** [ansible/ansible#76127]
### Summary

Running ansible in check mode reports the tasks as "Changed" when it was skipped or ignored.

### Issue Type

Feature Idea

### Component Name

Checkmode

### Additional Information

When ansible --check is enabled ansible reports the task as "changed" even when it was skipped.
Example snippet: 
```
- name: Run a script using an executable in a non-system path
  ansible.builtin.script: check_users_groups.sh
  args:
    executable: /bin/bash
```
`check_users_groups.sh` can contain for example:
`ls`

Running this task with ansible flag --check will run and report the task as "changed=1" even when this task was actually skipped.
This causes unneeded confusion, why not report this task as ignored or skipped?

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
