### ISSUE TITLE
git module fails using local_action: Host key verification failed, rc: 128

### ISSUE THREAD

**Issue by lucab85** [ansible/ansible#76158]
### Summary

When try to use `ansible.builtin.git` module with `local_action`, it fails with this error:
~~~
FAILED! => {"changed": false, "cmd": "/bin/git clone --origin origin '' /tmp/repo", "msg": "Cloning into '/tmp/repo'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/tmp/repo'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Cloning into '/tmp/repo'...", "Host key verification failed.", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "", "stdout_lines": []}
~~~

### Issue Type

Bug Report

### Component Name

git module

### Ansible Version

```console
$ ansible --version
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
$ echo $?
0
(empty result)
```

### OS / Environment

$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)

### Steps to Reproduce

Playbook 1
```yaml
---
- hosts: all
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - name: "git checkout"
      local_action:
        module: git
        repo: "git@github.com:ansible/tower-example.git"
        dest: "/tmp/repo"
        key_file: "{{ my_ssh_key_file }}"
```
Playbook 2
```yaml
---
- hosts: all
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
    - name: git checkout
      git:
        repo: "git@github.com:ansible/tower-example.git"
        dest: "/tmp/repo"
        key_file: "{{ my_ssh_key_file }}"
      delegate_to: localhost
```

### Expected Results

Task completed with ok status

### Actual Results

```console
~~~
TASK [git checkout] ********************************************************************************************************************************************************************************
task path: /home/vagrant/reproducer.yml:12
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267 `" && echo ansible-tmp-1635346594.4733078-8129-38320235313267="` echo /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/source_control/git.py
<localhost> PUT /root/.ansible/tmp/ansible-local-8071cuhynpjv/tmp_0wgp0n5 TO /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267/AnsiballZ_git.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267/ /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267/AnsiballZ_git.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267/AnsiballZ_git.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1635346594.4733078-8129-38320235313267/ > /dev/null 2>&1 && sleep 0'
fatal: [10.40.5.64 -> localhost]: FAILED! => {
    "changed": false,
    "cmd": "/bin/git clone --origin origin '' /tmp/repo",
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "archive": null,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/tmp/repo",
            "executable": null,
            "force": false,
            "gpg_whitelist": [],
            "key_file": "/home/vagrant/key",
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "git@github.com:ansible/tower-example.git",
            "separate_git_dir": null,
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "msg": "Cloning into '/tmp/repo'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.",
    "rc": 128,
    "stderr": "Cloning into '/tmp/repo'...\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
    "stderr_lines": [
        "Cloning into '/tmp/repo'...",
        "Host key verification failed.",
        "fatal: Could not read from remote repository.",
        "",
        "Please make sure you have the correct access rights",
        "and the repository exists."
    ],
    "stdout": "",
    "stdout_lines": []
}
~~~
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
