### ISSUE TITLE
Bug in lineinfile: backrefs and jinja2 variables

### ISSUE THREAD

**Issue by grgi** [ansible/ansible#7615]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Ubuntu 14.04
##### Summary:

Combining backrefs with jinja2 variables in the `lineinfile` module produces wrong results. The problem only arises, if in the `line` variable, `\1` is directly next to a jinja2 variable (see below). Note, that there is not a problem if there is an additional character between them, e.g. `\1 {{ test_server }}`.
##### Steps To Reproduce:

File `test.cfg` containing the line

```
allowed_hosts=127.0.0.1
```

Variable: `test_server=10.0.0.5`

Applying the Playbook:

```
- lineinfile:
    dest: test.cfg
    backrefs: yes
    regexp: '^(allowed_hosts=).*$'
    line: '\1{{ test_server }}'
```
##### Expected Results:

Line in `test.cfg` should be:

```
allowed_hosts=10.0.0.5
```
##### Actual Results:

The line in `test.cfg` is replaced by

```
H.0.0.5
```
