### ISSUE TITLE
module_defaults + FQCN fails

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansible#76164]
### Summary

We have an open issue in community.vmware (ansible-collections/community.vmware#1078). On the one hand, we want people to use FQCNs but on the other this doesn't work with module defaults.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
ansible [core 2.11.6] 
  config file = /home/apatt/github_wsl/demopod-ansible/ansible.cfg
  configured module search path = ['/home/apatt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/apatt/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/apatt/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/apatt/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
CALLBACKS_ENABLED(/home/apatt/github_wsl/demopod-ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_LOG_PATH(/home/apatt/github_wsl/demopod-ansible/ansible.cfg) = /home/apatt/github_wsl/demopod-ansible/ansible.log
DEFAULT_REMOTE_USER(/home/apatt/github_wsl/demopod-ansible/ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(/home/apatt/github_wsl/demopod-ansible/ansible.cfg) = /home/apatt/github_wsl/demopod-ansible/.vault_pass
DEPRECATION_WARNINGS(/home/apatt/github_wsl/demopod-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/apatt/github_wsl/demopod-ansible/ansible.cfg) = False
```

### OS / Environment

WSL 2 on Windows 10:
```bash
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to Reproduce

```yaml
- name: Add ESXi hosts to vCenter and configure
  hosts: localhost
  connection: local
  module_defaults:
    group/vmware:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ vcenter_datacenter }}'
      cluster_name: '{{ vcenter_cluster }}'
      esxi_username: '{{ esxi_username }}'
      esxi_password: '{{ esxi_password }}'
      validate_certs: false
  become: no
  vars_files:
    - vars_files/vsphere.yml      # vars for vSphere
    - vars_files/credentials.yml  # vault protected passwords

  vars:
    - ansible_python_interpreter: python3

  # Load collections
  collections:
    - community.vmware.vmware_host_ntp

  tasks:
    
  # Configure NTP
  - name: Add NTP servers
    community.vmware.vmware_host_ntp:
      # hostname: "{{ vcenter_hostname }}"
      # username: "{{ vcenter_username }}"
      # password: "{{ vcenter_password }}"
      esxi_hostname: "{{ item }}"
      ntp_servers:
        - 10.100.72.10
        - 10.100.72.11
      validate_certs: false
    with_items: "{{ groups['vmware'] }}"
    tags: ntp

```

### Expected Results

I would expect the group variables `hostname`, `username` and `password` to be inherited from the `module_defaults` configuration where the variables are defined under `group/vmware`. 

### Actual Results

```console
The task fails with the following error:


TASK [Add NTP servers] **********************************************************************************************************************************************************************************************
Thursday 14 October 2021  13:04:18 -0700 (0:00:01.253)       0:00:01.310 ****** 
failed: [127.0.0.1] (item=server-09.tme.nebulon.com) => {"ansible_loop_var": "item", "changed": false, "item": "server-09.tme.nebulon.com", "msg": "Hostname parameter is missing. Please specify this parameter in task or export environment variable like 'export VMWARE_HOST=ESXI_HOSTNAME'"}

If I uncomment the variables defined directly in the task, everything works as expected. 

Also, defining them by fully qualified module name works as well.

```yaml
- name: Add ESXi hosts to vCenter and configure
  hosts: localhost
  connection: local
  module_defaults:
    community.vmware.vmware_host_ntp:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
