### ISSUE TITLE
module 'azure.mgmt.storage._storage_management_client' has no attribute 'VERSION'

### ISSUE THREAD

**Issue by fiftin** [ansible/ansible#76169]
### Summary

I get next error when trying to upload file to azure storage:

Error getting keys for account *** - module 'azure.mgmt.storage._storage_management_client' has no attribute 'VERSION'

### Issue Type

Bug Report

### Component Name

azure.mgmt.storage._storage_management_client

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.5]
  config file = None
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Ubuntu 20.04.3 LTS

### Steps to Reproduce

```yaml (paste below)
- name: copy build to Azure
  azure_rm_storageblob:
    resource_group: ***
    storage_account_name: ***
    container: "{{ build_container_name }}"
    blob: "{{ item }}"
    src: "{{ build_root_dir }}/distrib/directory/{{ item }}"
    client_id: "{{ manager_access_key }}"
    secret: "{{ manager_secret_key }}"
    subscription_id: "{{ manager_subscription }}"
    tenant: "{{ manager_domain }}"
```

### Expected Results

Success upload file to Azure storage

### Actual Results

```console
Error getting keys for account *** - module 'azure.mgmt.storage._storage_management_client' has no attribute 'VERSION'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
