### ISSUE TITLE
rpm_key should make use of url_argument_spec to allow passing of client_key/client_cert

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#76177]
### Summary

We need to be able to install a rpm gpg key from a url that requires a client certificate to access.

### Issue Type

Feature Idea

### Component Name

rpm_key

### Additional Information

```yaml (paste below)
  - name: "RedHat: Import Intel Parallel Studio RPM GPG key"
    rpm_key:
      key: "https://URL/PUBLIC_KEY.PUB"
      state: present
      client_key: /etc/pki/tls/private/{{ ansible_nodename }}.key
      client_cert: /etc/pki/tls/certs/{{ ansible_nodename }}.crt
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
