### ISSUE TITLE
Ansible should ignore 'register:' when task is skipped

### ISSUE THREAD

**Issue by Rorasaurus** [ansible/ansible#76176]
### Summary

I believe the behaviour of the way Ansible registers variables should be modified. Currently, a task registers a variable even if the conditional clause is not met.

E.g:

```
- name: Task 1
  command: "echo 'Hello world 1'"
  register: echo_output
  when: true

- name: Task 2
  command: "echo 'Hello world 2'"
  register: echo_output
  when: false

- name: Debug
  debug:
    var: echo_output
```
   
With the current behaviour, the variable 'echo_output' will always be:

`    "echo_output": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }`

If the task is skipped, it seems logical to me that only the 'register' from Task 1 is defined.

I suspect changing this logic would break too many plays, but it's a suggestion.

### Issue Type

Bug Report

### Component Name

register

### Ansible Version

```console
$ ansible --version
ansible 2.9.21
  config file = /home/rswann/ansible-agentcore/ansible.cfg
  configured module search path = ['/home/rswann/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, May  4 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora 32

### Steps to Reproduce

```yaml (paste below)
`- name: Task 1
  command: "echo 'Hello world 1'"
  register: echo_output
  when: true

- name: Task 2
  command: "echo 'Hello world 2'"
  register: echo_output
  when: false

- name: Debug
  debug:
    var: echo_output`
   
With the current behaviour, the variable 'echo_output' will always be:

`    "echo_output": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }`
```

### Expected Results

Task 2 should not touch the variable 'echo_output'.

### Actual Results

```console
"echo_output": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
