### ISSUE TITLE
Conditional / related keyed_groups membership in inventory plugin

### ISSUE THREAD

**Issue by MarcoV-git** [ansible/ansible#76175]
### Summary

I'm not quite sure whether it's lack of documentation (examples), it turns out to be a feature request or if it's even bug related, so I decided to file it under feature request..

I’m struggling with the keyed_groups syntax of inventory plugins.

When I have the following VM’s with their tags and attributes:

- ServerA has tag environment=DT and guestFamily=linuxGuest
- ServerB has tag environment=PR and guestFamily=windowsGuest

I now get the following output with the below inventory plugin code:
```
 @all
  |--@DT:
  |  |--@linuxGuest:
  |  |  |--ServerA
  |  |--@windowsGuest:
  |  |--ServerB
  |--@PR:
  |  |--@linuxGuest:
  |  |--@windowsGuest:
  |  |    |--ServerB
  |  |--ServerA
```
Whereas I need this:

```
@all
|--@DT:
|  |--@linuxGuest:
|  |  |--ServerA
|  |--@windowsGuest:
|--@PR:
|  |--@linuxGuest:
|  |--@windowsGuest:
|  |  |--ServerB
```
So how to make keyed_groups membership conditional / related?

### Issue Type

Feature Idea

### Component Name

inventory plugin

### Additional Information

This is my current inventory plugin code:
```yaml (paste below)

plugin: community.vmware.vmware_vm_inventory:
 strict: False
with_tags: True
hostnames:
  - 'config.name'
compose:
  ansible_host: 'guest.hostName'
  ansible_connection: '"winrm" if "windows" in config.guestId else "ssh"'
properties:
  - "name"
  - "config.name"
  - "config.guestId"
  - "config.guestFullName"
  - "guest.hostName"
  - "guest.ipAddress"
  - "guest.guestState"
  - "guest.guestFamily"
  - "summary.runtime.powerState"
keyed_groups:
  - key: 'tag_category.environment'
    separator: ''
  - key: 'guest.guestFamily'
    separator: ''
    parent_group: '{{ tag_category.environment[0] }}'
filters:
  - "tag_category.ansible_managed is defined and 'true' in tag_category.ansible_managed"

```

# ansible-inventory --version
ansible-inventory 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/ansible_210/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/ansible_210/bin/ansible-inventory
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
