### ISSUE TITLE
stderr": "error: you cannot specify both a context name and --current" in ansible playbook

### ISSUE THREAD

**Issue by kmrsujith** [ansible/ansible#76173]
### Summary

I am trying to execute _kubectl config set-context --current --namespace= "name"_ using ansible script it is failing with error: you cannot specify both a context name and --current

but when i execute same command from command prompt its working.

### Issue Type

Bug Report

### Component Name

kubectl

### Ansible Version

```console
$ ansible --version
ansible 2.9.24
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

ubuntu

### Steps to Reproduce

```yaml (paste below)
---
- hosts : localhost
  vars_prompt:
    - name: J_NAME
      prompt: Enter Jenkins Name
      private: no
  environment:
    J_NAME: "{{ J_NAME }}"
  tasks:
      - name: create defalut namespace
        shell: kubectl config set-context --current --namespace= "{{ J_NAME }}"
        changed_when: false
        check_mode: no
        register: variable_output
      - debug:
          var: variable_output.stdout_lines


```

### Expected Results

Expected to change the namespace for the current-context

### Actual Results

```console
FAILED! => {"changed": true, "cmd": ["kubectl", "config", "set-context", "--current", "--namespace=", "myapp"], "delta": "0:00:00.057104", "end": "2021-10-29 09:35:27.735663", "msg": "non-zero return code", "rc": 1, "start": "2021-10-29 09:35:27.678559", "stderr": "error: you cannot specify both a context name and --current", "stderr_lines": ["error: you cannot specify both a context name and --current"], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
