### ISSUE TITLE
Create Azure managed disk snapshot

### ISSUE THREAD

**Issue by serxansherif** [ansible/ansible#76207]
### Summary

Hello,

I want to create an Azure VM disk snapshot with the following task.

  - name: Create a snapshot by copying an existing managed disk.
    azure_rm_snapshot:
      resource_group: rg-vpm
      name: mySnapshot
      location: westeurope
      creation_data:
        create_option: Copy
        source_id: '/subscriptions/67867-jkjkjk-......-...../resourceGroups/RG-NAME/providers/Microsoft.Compute/disks/osdisk412'

### Issue Type

Bug Report

### Component Name

azure.azcollection

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /home/user/testlab/test-ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/home/user/testlab/test-ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/user/testlab/test-ansible/ansible.cfg) = ['/home/user/testlab/test-ansible/inventory_azure_rm.yml']
DEFAULT_REMOTE_USER(/home/user/testlab/test-ansible/ansible.cfg) = myuser
HOST_KEY_CHECKING(/home/user/testlab/test-ansible/ansible.cfg) = False
```

### OS / Environment

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Steps to Reproduce

```yaml (paste below)
  - name: Create a snapshot by copying an existing managed disk.
    azure_rm_snapshot:
      resource_group: rg-vpm
      name: mySnapshot
      location: westeurope
      creation_data:
        create_option: Copy
        source_id: '/subscriptions/67867-jkjkjk-......-...../resourceGroups/RG-NAME/providers/Microsoft.Compute/disks/osdisk412'
```

### Expected Results

Create an OS disk snapshot

### Actual Results

```console
fatal: [servername-01_9a21]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Unsupported parameters for (azure_rm_snapshot) module: source_id found in creation_data. Supported parameters include: create_option, source_uri"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
