### ISSUE TITLE
git module changes .git/config despite check_mode when combined with --diff

### ISSUE THREAD

**Issue by jojoob** [ansible/ansible#76221]
### Summary

The git module overrides the URL of the given remote in .git/config despite check_mode when it is check_mode is combined with `--diff`. But only when the current HEAD of the repository tracks a remote branch of the remote URL specified in the git task.

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/burk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/burk/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Target OS: Ubuntu 18.04 and arch linux

### Steps to Reproduce

```yml
- hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: "PREPARE: Clone git repository"
      git:
        repo: https://github.com/jojoob/test.git
        dest: /tmp/ansible-git-test
      check_mode: no
    - name: "PREPARE: Add another remote and checkout branch"
      tags:
        - remotecheckout
      shell:
        cmd: git remote add other https://github.com/jojoob/test2.git; git fetch other; git checkout other/main
        chdir: /tmp/ansible-git-test
      check_mode: no
    - name: "TEST CASE: Override remote url even with check_mode when using --diff"
      git:
        repo: https://github.com/jojoob/test2.git
        dest: /tmp/ansible-git-test
      check_mode: yes
      diff: yes
```

### Expected Results

After running this play with `ansible-playbook` (crucial is the combination of `--check` and `--diff`, no matter if defined as CLI argument or in the task) I expect the .git/config file to be exactly the same as before the last git task in this play:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/jojoob/test.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[remote "other"]
	url = https://github.com/jojoob/test2.git
	fetch = +refs/heads/*:refs/remotes/other/*
```

### Actual Results

```console
# Actual Result
Instead of .git/config being untouched the remote URL of remote 'origin' changed to `.../test2.git`:


[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/jojoob/test2.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[remote "other"]
	url = https://github.com/jojoob/test2.git
	fetch = +refs/heads/*:refs/remotes/other/*
```

Ansible output:

```
TASK [TEST CASE: Override remote url even with check_mode when using --diff] *******************************************************************************
diff --git a/README.md b/README.md
index e055c2e..00bcb6e 100644
--- a/README.md
+++ b/README.md
@@ -1 +1 @@
-# test2
\ No newline at end of file
+# test
\ No newline at end of file
changed: [localhost] => {"after": "bf9243b80c73ee6201f234e04a821c0c5771daa8", "before": "6d2770a2458e971fe09443a038f84596296d753f", "changed": true, "remote_url_changed": true}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
