### ISSUE TITLE
Ansible ignores limit and group_vars when inventory uses children

### ISSUE THREAD

**Issue by StellaV** [ansible/ansible#76224]
### Summary

Hi,

I was busy creating an inventory file that separates the hosts into two parent groups (dev and production) with multiple sub-groups, determined by the servers' functionalities. I also wanted to have different group_vars for both dev and production (tested this both in the inventory file itself and in group_vars/(dev|production)). I also run the playbook with a limit, set only to dev and production.

So, what I wanted to do is set the ansible limit to the correct environment (dev or production) in order to avoid running the playbook on the wrong hosts. I also wanted the group vars to be picked up only for the group that belongs to the environment.

The problem:

- The playbook picks ALL hosts in the sub-group hosts, even if the parent group should be filtered by the limit
- The group variables are loaded only once, but applied to all groups

I wonder if I am doing it wrong? Is there a better/proper way to do this?

### Issue Type

Bug Report

### Component Name

inventory vars and limits

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/Users/svouteva/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/svouteva/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct 22 2021, 13:39:57) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
all:
  children:
    dev:
      vars:
        my_var:
          - bla1
          - bla2
      children:
        db:
          hosts:
            db1
            db2
        webserver:
          hosts:
            web1
            web2
    production:
      children:
        vars:
          my_var:
            - bla3
            - bla4
        db:
          hosts:
            foo.example.com:
            bar.example.com:
        webserver:
          hosts:
            one.example.com:
            two.example.com:
            three.example.com:
```

### OS / Environment

MacOS

### Steps to Reproduce

Inventory file
```
all:
  children:
    dev:
      vars:
        my_var:
          - bla1
          - bla2
      children:
        db:
          hosts:
            db1
            db2
        webserver:
          hosts:
            web1
            web2
    production:
      children:
        vars:
          my_var:
            - bla3
            - bla4
        db:
          hosts:
            foo.example.com
            bar.example.com
        webserver:
          hosts:
            one.example.com
            two.example.com
            three.example.com
```

Test playbook:
```
- hosts: db
  become: true
  become_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Show the data
      debug:
        var: my_var
```

Running the playbook:
```
ansible-playbook -i inv --limit production db.yml
```

### Expected Results
```
ok: [foo.example.com] => {
    "my_var”: [
        "bla1",
        "bla2"
    ]
}
ok: [bar.example.com] => {
    "my_var”: [
        "bla1",
        "bla2"
    ]
}
```

### Actual Results

```console
ok: [db1 db2] => {
    "my”_var: [
        "bla1",
        "bla2"
    ]
}
ok: [foo.example.com] => {
    "my_var”: [
        "bla1",
        "bla2"
    ]
}
ok: [bar.example.com] => {
    "my_var”: [
        "bla1",
        "bla2"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug, ansible is respecting the inventory layout you have given it and correctly applies the limit. You have placed the same groups (`db` and `webserver`) in both `production` and `dev`, so all hosts are in both parent groups. You need to either remove the parent/child relationship or give the groups unique names (e.g. `db_dev`).

My preference is usually the first:
```
all:
  children:
    db:
      hosts:
        db1:
        db2:
        foo.example.com:
        bar.example.com:
    webserver:
      hosts:
        web1:
        web2:
        one.example.com:
        two.example.com:
        three.example.com:
    dev:
      vars:
        my_var:
          - bla1
          - bla2
      hosts:
        db1:
        db2:
        web1:
        web2:
    production:
      vars:
        my_var:
          - bla3
          - bla4
      hosts:
        foo.example.com:
        bar.example.com:
        one.example.com:
        two.example.com:
        three.example.com:
```
