### ISSUE TITLE
When copying a file containing encrypt_string, it is not decrypted as expected

### ISSUE THREAD

**Issue by 1121437613** [ansible/ansible#76238]
### Summary

hi, I encountered the following problems when using the Copy module

Scenario 1: When the file being copied is the entire file is encrypted
The file can be successfully decrypted

Scenario 2: When the copied file uses encrypt_string to encrypt the string
The file is not decrypted as expected

###
The vault password in the case is Vault_Passwd
The execution command is
echo Vault_Passwd> /tmp/vault_password_file
ansible-playbook playbook-test.yml --vault-id=/tmp/vault_password_file

### Issue Type

Bug Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = 127.0.0.1:6379
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 1209600
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = [u'profile_tasks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = hhansible
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 300
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Red Hat Enterprise Linux Server release 7.8 (Maipo)

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Scenario 1
      copy:
        src: /tmp/src-1.yml
        dest: /tmp/dest-1.yml
        decrypt: yes
    - name: Scenario 2
      copy:
        src: /tmp/src-2.yml
        dest: /tmp/dest-2.yml
        decrypt: yes
```

### Expected Results

I expect both dest-1.yml and dest-2.yml will display the decrypted cont
[dest-1&dest-2.zip](https://github.com/ansible/ansible/files/7495230/dest-1.dest-2.zip)
e

### Actual Results

```console
The result is that dest-1.yml can be decrypted normally, but the content of dest-2.yml is not decrypted
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
