### ISSUE TITLE
Timeout when using SSH Proxy Jump with network_cli

### ISSUE THREAD

**Issue by hannessolo** [ansible/ansible#76247]
### Summary

I get a network timeout when trying to use a ssh proxy jump (=bastion host) with the `network_cli` option for `ansible_connection`.

My hosts file is configured as follows:

```yaml
---
lab:
  children:
    routers:
      hosts:
        10.10.20.11:
        10.10.20.12:
  vars:
    ansible_user: redacted
    ansible_password: redacted
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_password: redacted
    ansible_become_method: enable
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p developer@10.10.20.50"'
```

When I try to run a sample command, it times out:

```
➜  AnsibleDemo ansible routers -i hosts.yml  -m ios_command -a "commands='show run | include line'"
10.10.20.11 | FAILED! => {
    "changed": false,
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
10.10.20.12 | FAILED! => {
    "changed": false,
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
```

However, I can manually perform the same action. I added the following to my ssh config: 

```
Host devnetGateway
	HostName	10.10.20.50
	User		developer

Host Router1
	HostName	10.10.20.11
	User		redacted
	ProxyJump	devnetGateway

Host Router2
	HostName	10.10.20.12
	User		redacted
	ProxyJump	devnetGateway
```

Then, the command `ssh Router1` succeeds.

### Issue Type

Bug Report

### Component Name

network_cli

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6]
  config file = /Users/hhertach/Documents/AnsibleDemo/ansible.cfg
  configured module search path = ['/Users/hhertach/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/hhertach/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
HOST_KEY_CHECKING(/Users/hhertach/Documents/AnsibleDemo/ansible.cfg) = False
```

### OS / Environment

Control node: MacOS 11
Managed nodes: Cisco IOSv

### Steps to Reproduce

```yaml (paste below)
---
lab:
  children:
    routers:
      hosts:
        10.10.20.11:
        10.10.20.12:
  vars:
    ansible_user: redacted
    ansible_password: redacted
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_password: redacted
    ansible_become_method: enable
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p developer@10.10.20.50"'
```

### Expected Results

The ssh connection succeeds.

### Actual Results

```console
➜  AnsibleDemo ansible routers -i hosts.yml  -m ios_command -a "commands='show run | include line'"
10.10.20.11 | FAILED! => {
    "changed": false,
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
10.10.20.12 | FAILED! => {
    "changed": false,
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
