### ISSUE TITLE
ansible.builtin.uri - Interacts with webservices - add response headers to return values

### ISSUE THREAD

**Issue by activedecay** [ansible/ansible#76248]
### Summary

I'm trying to validate that my web service is returning the right headers in the response, but there is no facility in the URI module to inspect the headers because they are not returned.

### Issue Type

Feature Idea

### Component Name

uri

### Additional Information

```yaml (paste below)
- name: inspect headers
  uri:
    url: http://myservice
  register: i_want_headers_from_the_http_response_here
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
HTTP response headers are located directly on the registered variable.

For example, to access the `Content-Type` header, you would use:

```
i_want_headers_from_the_http_response_here.content_type
```

In this example, having the server set an `X-Sandwich` header:

```yaml
    - uri:
        url: https://httpbin.org/response-headers?X-Sandwich=ham
      register: i_want_headers_from_the_http_response_here
```

You would access the `.x_sandwich` key in from the registered variable

```yaml
    - debug:
        var: i_want_headers_from_the_http_response_here.x_sandwich
```

Which produces:

```yaml
ok: [localhost] => {
    "i_want_headers_from_the_http_response_here.x_sandwich": "ham"
}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
