### ISSUE TITLE
pip3.4 (for python 3) tries to install in global site-packages

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#7625]
##### Issue Type:

Bug report
##### Ansible Version:

1.6.2
##### Environment:

client: OS X 10.9
server: ubuntu 12.04
##### Summary:

When I try to install requirements via pip using python3 it tries to install them into global site-packages.
##### Steps To Reproduce:

``` yaml
- name: install python 3.4
  apt: "pkg={{ item }} state=present"
  sudo: yes
  with_items:
    - python3.4
    - python3.4-dev

- name: install pip 3.4
  command: python3.4 -m ensurepip --upgrade
  sudo: yes

- name: install requirements
  pip: requirements=/home/project/project1/requirements.txt virtualenv_command=pyvenv-3.4 virtualenv=/home/project/.virtualenvs/project1 executable=pip3.4
```

Without specifying virtualenv_command it is also reproduced.
##### Expected Results:

Install requirements into virtual environment with python3.4
##### Actual Results:

pip module tries to install requirements into global python3.4 site-packages and fails with permission denied error.
