### ISSUE TITLE
junos_scp  - could not get keys from ssh-agent

### ISSUE THREAD

**Issue by ric79** [ansible/ansible#76279]
### Summary

I don't know how to use junos_scp.  I get "could not get keys from ssh-agent"

### Issue Type

Bug Report

### Component Name

junipernetworks.junos.junos_scp

### Ansible Version

```console
ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/python_envs/yyy-env/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/python_envs/yyy-env/bin/ansible
  python version = 3.9.8 (main, Nov 11 2021, 10:03:58) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3

$ ansible-galaxy collection list | grep jun
junipernetworks.junos         2.6.0
```

### Configuration

```console
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/xxx/yyy-prj/yyy/ansible.cfg) = ['/home/xxx/python_envs/${BASE_ANSIBLE_ENV}-ans
DEFAULT_LOG_PATH(/home/xxx/yyy-prj/yyy/ansible.cfg) = /home/xxx/yyy-prj/yyy/logs/l
DEFAULT_ROLES_PATH(/home/xxx/yyy-prj/yyy/ansible.cfg) = ['/home/xxx/python_envs/${BASE_ANSIBLE_ENV}-an
HOST_KEY_CHECKING(/home/xxx/yyy-prj/yyy/ansible.cfg) = False
```

### OS / Environment

$ more /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

### Steps to Reproduce

Here there is my playbook
```
- name: Test device connection
  hosts: "{{juniper_node_name}}"
  connection: local
  gather_facts: no
  
  vars:
    cli:
      host: "{{ ansible_host }}"
      port: 830
      timeout: 300
      username: "{{ansible_user}}"
      password: "{{ansible_password}}"

  tasks:  

    - name: download file from remote device
      junipernetworks.junos.junos_scp:
        src: miofile.txt
        dest: /tmp/
        provider: "{{ cli }}"
```
I get 
```
fatal: [MX2-NAT44]: FAILED! => {"changed": false, "msg": "could not get keys from ssh-agent"}
```

If I use "junipernetworks.junos.junos_command" with "connection: juniper.device.pyez" everything is fine. I need to understand how to use junos_scp task

### Expected Results

I would copy the file from the router to my PC

### Actual Results

```console
I get "could not get keys from ssh-agent"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
