### ISSUE TITLE
Get rid of "hosts" for cloud application deployment use cases

### ISSUE THREAD

**Issue by sebastian-neubauer-by** [ansible/ansible#76290]
### Summary

I am a real fan-boy of ansible. But I often fail to implement ansible in new projects for a simple reason: 
If you only want to use ansible for application deployment in cloud environments like kubernetes (infrastructure is already there, all you do is deploying applications, e.g. dev staging prod), all the semantics around "hosts" (hosts file, hosts keyword in playbooks, ...) feels very much like you are doing something wrong. And your colleagues will reinforce this sentiment by telling you "hey, we are using kubernetes, ansible is for servers only!"

The thing is, ansible is still the best tool I know for these workloads (helm is not configuration management, jsonnet is too complicated for me and is missing the "deploy" part,...)

For more detailed information see below.

I am sure this topic was brought up a million times already and I guess I just haven't found the solution to this yet. I would be pretty happy with closing this issue by just pointing me to the right breadcrumbs. 

Really looking forward to your feedback!

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

In the end it easy to implement (or let's call it "workaround"). You just have to think of "hosts" as "set of configurations" and you are mostly good to go.
The inventory file (which one could name my_app_dev) looks like this:
```
my_app:
    vars:
        app_name: myapp_dev
    hosts:
        kubernetes:
            ansible_become: False
            ansible_connection: "local"
            ansible_gather_facts: False
            ansible_python_interpreter: "/usr/bin/env python"
            k8s_api: http://prodk8s.com
```

and a dummy playbook:
```
---

- name: my app deploy
  hosts: my_app
  tasks:
    - name: Deploy to k8s
       ansible.builtin.debug:
         msg: Deploy {{app_name}} to {{k8s_api}}
```

As you can see, hosts is just semantically odd, but in the end it works if only it would be called "config_set" or something.
(Also the ansible_connection: local and interpreter feels clumsy, but maybe that is another issue.)

So I would love if the playbook would look like this:
```
---

- name: my app deploy
  config_set: my_app
  tasks:
    - name: Deploy to k8s
       ansible.builtin.debug:
         msg: Deploy {{app_name}} to {{k8s_api}}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
