### ISSUE TITLE
Feature request: inventory_files variable

### ISSUE THREAD

**Issue by alexanium-dev** [ansible/ansible#76293]
### Summary

I want to get file names of all inventory sources per hostname. Ansible has `inventory_file` variable with "the inventory source where the _inventory_hostname_ was first defined", but it has a flaw - if hostname could be present in multiple files, this variable becomes unreliable. And I think that it would be easy and useful to add `inventory_files` variable with all inventory sources for the host.

### Issue Type

Feature Idea

### Component Name

Inventory Manager

### Additional Information

Just a one of possible uses:
```yaml (paste below)
- name: Ensure one inventory file per host
  fail:
    msg: The host should be defined in one file only, but is defined in {{ inventory_files }}.
  when: inventory_files | length != 1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
