### ISSUE TITLE
apt ignore_case (re-evaluate)

### ISSUE THREAD

**Issue by Tjkent88** [ansible/ansible#76315]
### Summary

The apt module uses explicit regex. I am looking for an ignore_case parameter as it will reject a package if the casing is incorrect. 

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information

---
```
- name: simple parameter to ignore case.
  apt:
    name: Nginx
    state: latest
    update_cache: yes
    ignore_case: true
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conductv
