### ISSUE TITLE
Templating parses and breaks JSON instead of passing the string as is

### ISSUE THREAD

**Issue by giner** [ansible/ansible#76311]
### Summary

JSON string is parsed instead of being passed as is while templating when passed through an intermediate variable

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/stas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stas/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/stas/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/stas/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

play.yml:
```yaml (paste below)
- hosts: localhost
  gather_facts: no
  vars:
    var1: '{"key": "value"}'
    var2: '{{ var1 }}'
  tasks:
  - template:
      src: template.j2
      dest: rendered
```
template.j2:
```
{{ var1 }}
{{ var2 }}
```
Run:
```
ansible-playbook play.yml
# ...
```

### Expected Results

```
cat rendered
# OUTPUT
{"key": "value"}
{"key": "value"}
```

### Actual Results

```console
cat rendered
# OUTPUT
# the first line is good (JSON)
# the second line is bad (broken JSON)
{"key": "value"}
{'key': 'value'}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
