### ISSUE TITLE
Using ansible docker_container module with podman

### ISSUE THREAD

**Issue by felipediefenbach** [ansible/ansible#76312]
### Summary

When i try to use docker_container with podman and podman-docker i can't start a new container using a local builded image.
It usually works fine.

### Issue Type

Bug Report

### Component Name

docker_container

### Ansible Version

```console
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

### Configuration

```console
no changes
```

### OS / Environment

cat /etc/redhat-release
Fedora release 34 (Thirty Four)

uname -a
Linux krisiun 5.14.17-201.fc34.armv7hl #1 SMP Mon Nov 8 22:03:51 UTC 2021 armv7l armv7l armv7l GNU/Linux

pip list | grep docker
docker           5.0.3
docker-pycreds   0.4.0

 rpm -qa | grep podman
podman-gvproxy-3.4.1-1.fc34.armv7hl
podman-plugins-3.4.1-1.fc34.armv7hl
podman-3.4.1-1.fc34.armv7hl
podman-docker-3.4.1-1.fc34.noarch

 which docker
alias docker='podman'
        /usr/bin/podman

### Steps to Reproduce

save docker file, build.yml, and deploy.yml ans run ansible-playbook build.yml ans ansible-playbook deploy.yml

dockerfile:
FROM ubuntu:focal

# Install apache, PHP 7, and supplimentary programs
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get -y install \
    apache2 \
    libapache2-mod-fcgid \
    php-fpm \
    php \
    php-cli \
    php-yaml \
    php-curl \
    vim \
    wget \
    git \
    zip \
    gzip \
    unzip \
    ansible \
    python3-psycopg2 \
    dnsutils \
    sshpass

RUN a2dismod php7.4 mpm_prefork
RUN a2enconf php7.4-fpm
RUN a2enmod proxy proxy_fcgi mpm_event

# instala o composer
RUN cd /tmp && \
wget https://getcomposer.org/installer && \
php installer --install-dir=/usr/local/bin --filename=composer && \
rm installer

CMD apachectl -D FOREGROUND
--------------------------------------------------------------------------------------------------------------------------

```yaml (paste below)

build.yml
---
- name: build
  hosts: localhost
  connection: local
  become: yes
  tasks:

  - pip:
      name: docker

  - name: build dir
    file:
      path: /tmp/dockerfile
      state: directory

  - name: copy dockerfile
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
    loop:
      - { src: "dbdw2-dockerfile", dst: "/tmp/dockerfile/Dockerfile" }

  - name: build image under podman podman-docker
    docker_image:
      name: dbdw2-custom:v1.0
      build:
        path: /tmp/dockerfile
      source: build
      state: present

deploy.yml
---
- name:  deploy
  hosts: localhost
  connection: local
  become: yes
  vars:
    - dbdw2_dnssrv: "8.8.8.8"
    - dbdw2_dnssearch: "localdomain.foo.bar"
    - dbdw2_port: 8080
    - dbdw2_apache_logdir: "/var/log/dbdw2/apache2"
    - dbdw2_dumpdir: "/mnt/Data/Gitlab/dumps"
    - dbdw2_project_path: "/mnt/Data/Gitlab/dbdw2"
    - dbdw2_cli_invent: /mnt/Data/Gitlab/ansible/invent/cli/hosts
    - dbdw2_trgt_invent: /mnt/Data/Gitlab/ansible/invent/trgt/hosts
  tasks:

  - file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ dbdw2_apache_logdir }}"
      - "{{ dbdw2_dumpdir }}"
      - "{{ dbdw2_trgt_invent }}"
      - "{{ dbdw2_cli_invent }}"

  - name: run container
    docker_container:
      name: dbdw2
      image: localhost/dbdw2-custom:v1.0
      state: started
      detach: yes
      tty: yes
      dns_servers: "{{ dbdw2_dnssrv }}"
      dns_search_domains: "{{ dbdw2_dnssearch }}"
      ports:
        - "{{ dbdw2_port }}:80"
      mounts:
        - target: "/var/log/apache2"
          source: "{{ dbdw2_apache_logdir }}"
          type: bind
          read_only: no
        - target: "/var/www/html"
          source: "{{ dbdw2_project_path }}"
          type: bind
          read_only: no
        - target: "/var/www/html/dumps"
          source: "{{ dbdw2_dumpdir }}"
          type: bind
          read_only: no
        - target: "/var/www/html/trgt"
          source: "{{ dbdw2_trgt_invent }}"
          type: bind
          read_only: no
        - target: "/var/www/html/cli"
          source: "{{ dbdw2_cli_invent }}"
          type: bind
          read_only: no

```

### Expected Results

podman (using docker_container) pull image from local machine as usually.

### Actual Results

```console
TASK [deploy] **************************************************************************************************************************************
task path: /mnt/Data/Gitlab/dbdw2/dockerdeploy.yml:26
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522 `" && echo ansible-tmp-1637153990.2479947-876-21860439110522="` echo /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522 `" ) && sleep 0'
Using module file /usr/lib/python3.9/site-packages/ansible/modules/cloud/docker/docker_container.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-327466buotb83/tmpbvlkhpp0 TO /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522/AnsiballZ_docker_container.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522/ /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522/AnsiballZ_docker_container.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522/AnsiballZ_docker_container.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1637153990.2479947-876-21860439110522/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_docker_container_payload_pop_ssoa/ansible_docker_container_payload.zip/ansible/modules/cloud/docker/docker_container.py", line 2858, in container_create
  File "/usr/local/lib/python3.9/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.9/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "auto_remove": false,
            "blkio_weight": null,
            "ca_cert": null,
            "cap_drop": null,
            "capabilities": null,
            "cleanup": false,
            "client_cert": null,
            "client_key": null,
            "command": null,
            "comparisons": null,
            "cpu_period": null,
            "cpu_quota": null,
            "cpu_shares": null,
            "cpuset_cpus": null,
            "cpuset_mems": null,
            "debug": false,
            "detach": true,
            "device_read_bps": null,
            "device_read_iops": null,
            "device_write_bps": null,
            "device_write_iops": null,
            "devices": null,
            "dns_opts": null,
            "dns_search_domains": [
                "localdomain.foo.bar"
            ],
            "dns_servers": [
                " 8.8.8.8"
            ],
            "docker_host": "unix://var/run/docker.sock",
            "domainname": null,
            "entrypoint": null,
            "env": null,
            "env_file": null,
            "etc_hosts": null,
            "exposed_ports": null,
            "force_kill": false,
            "groups": null,
            "healthcheck": null,
            "hostname": null,
            "ignore_image": false,
            "image": "localhost/dbdw2-custom:v1.0",
            "init": false,
            "interactive": false,
            "ipc_mode": null,
            "keep_volumes": true,
            "kernel_memory": null,
            "kill_signal": null,
            "labels": null,
            "links": null,
            "log_driver": null,
            "log_options": null,
            "mac_address": null,
            "memory": "0",
            "memory_reservation": null,
            "memory_swap": null,
            "memory_swappiness": null,
            "mounts": [
                {
                    "consistency": null,
                    "labels": null,
                    "no_copy": null,
                    "propagation": null,
                    "read_only": false,
                    "source": "/var/log/dbdw2/apache2",
                    "target": "/var/log/apache2",
                    "tmpfs_mode": null,
                    "tmpfs_size": null,
                    "type": "bind",
                    "volume_driver": null,
                    "volume_options": null
                },
                {
                    "consistency": null,
                    "labels": null,
                    "no_copy": null,
                    "propagation": null,
                    "read_only": false,
                    "source": "/mnt/Data/Gitlab/dbdw2",
                    "target": "/var/www/html",
                    "tmpfs_mode": null,
                    "tmpfs_size": null,
                    "type": "bind",
                    "volume_driver": null,
                    "volume_options": null
                },
                {
                    "consistency": null,
                    "labels": null,
                    "no_copy": null,
                    "propagation": null,
                    "read_only": false,
                    "source": "/mnt/Data/Gitlab/dumps",
                    "target": "/var/www/html/dumps",
                    "tmpfs_mode": null,
                    "tmpfs_size": null,
                    "type": "bind",
                    "volume_driver": null,
                    "volume_options": null
                },
                {
                    "consistency": null,
                    "labels": null,
                    "no_copy": null,
                    "propagation": null,
                    "read_only": false,
                    "source": "/mnt/Data/Gitlab/ansible/invent/trgt/hosts",
                    "target": "/var/www/html/trgt",
                    "tmpfs_mode": null,
                    "tmpfs_size": null,
                    "type": "bind",
                    "volume_driver": null,
                    "volume_options": null
                },
                {
                    "consistency": null,
                    "labels": null,
                    "no_copy": null,
                    "propagation": null,
                    "read_only": false,
                    "source": "/mnt/Data/Gitlab/ansible/invent/cli/hosts",
                    "target": "/var/www/html/cli",
                    "tmpfs_mode": null,
                    "tmpfs_size": null,
                    "type": "bind",
                    "volume_driver": null,
                    "volume_options": null
                }
            ],
            "name": "dbdw2",
            "network_mode": null,
            "networks": null,
            "networks_cli_compatible": null,
            "oom_killer": null,
            "oom_score_adj": null,
            "output_logs": false,
            "paused": false,
            "pid_mode": null,
            "pids_limit": null,
            "ports": [
                "8080:80"
            ],
            "privileged": false,
            "published_ports": [
                "8080:80"
            ],
            "pull": false,
            "purge_networks": false,
            "read_only": false,
            "recreate": false,
            "restart": false,
            "restart_policy": null,
            "restart_retries": null,
            "runtime": null,
            "security_opts": null,
            "shm_size": null,
            "ssl_version": null,
            "state": "started",
            "stop_signal": null,
            "stop_timeout": null,
            "sysctls": null,
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "tmpfs": null,
            "trust_image_content": false,
            "tty": true,
            "ulimits": null,
            "user": null,
            "userns_mode": null,
            "uts": null,
            "validate_certs": false,
            "volume_driver": null,
            "volumes": null,
            "volumes_from": null,
            "working_dir": null
        }
    },
    "msg": "Error creating container: 500 Server Error for http+docker://localhost/v1.40/containers/create?name=dbdw2: Internal Server Error (\"container create: error running container create option: invalid IP address <nil>: invalid argument\")"
}

PLAY RECAP ******************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
