### ISSUE TITLE
yum module on RHEL7 fills up disk with large yum cache after a repo with repo_gpgcheck=1 is added

### ISSUE THREAD

**Issue by gjvoosten** [ansible/ansible#76336]
### Summary

See #74962 (feel free to re-open that one and close this one as a duplicate).

### Issue Type

Bug Report

### Component Name

yum

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/username/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
[nothing]
```

### OS / Environment

RHEL 7.9

### Steps to Reproduce

As part of the playbook, there are some tasks that install repo's and download RPM's:

```yaml (paste below)
- name: Register ansible Yum repository
  become: yes
  ansible.builtin.yum_repository:
    name: ansible-epel7
    description: Ansible Red Hat 7 EPEL
    baseurl: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
    gpgcheck: yes
    gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

- name: Download Ansible RPMs to local controller Ansible RPM repository
  include_tasks: yum-download.yml
  vars:
    rpm_name: ansible
```
and:
```yaml
- name: Register ansible-runner Yum repository
  become: yes
  ansible.builtin.yum_repository:
    name: ansible-runner
    description: Ansible target dependencies
    baseurl: https://releases.ansible.com/ansible-runner/rpm/epel-7-x86_64/
    gpgcheck: yes
    gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

- name: Download pexpect RPMs
  include_tasks: yum-download.yml
  vars:
    rpm_name: python2-pexpect
```
with `yum-download.yml` as:
```yaml
- name: 'Download {{ rpm_name }} RPMs using yum'
  become: yes
  ansible.builtin.yum:
    name: '{{ rpm_name }}'
    download_only: yes
    download_dir: '{{local_rpm_repo_folder}}'
  environment: '{{ env_http_proxy }}'
```

### Expected Results

When running this playbook against a Red Hat 7.9 VM on Azure, I would expect just the RPM's to be downloaded (with maybe some small caching by yum).

### Actual Results

When running this playbook against a Red Hat 7.9 VM on Azure, yum fills the entire `/var` with cached data. (In fact, because by default `/var` is 8G I had to extend it first; I end up with some 12G!)

Only after changing:
```yaml
    gpgcheck: yes
```
to:
```yaml
    gpgcheck: no
```
does this work as expected (no huge amounts of data in `/var`, RPM's downloaded).

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/yum.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/yum.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
FWIW I was not able to reproduce this issue solely based on the information provided, although I have used  a local minimal CentOS 7 VM as opposed to RHEL7, with the following playbook:
```yaml
- hosts: centos7
  gather_facts: false
  become: true
  tasks:
    - yum_repository:
        name: ansible-epel7
        description: Ansible Red Hat 7 EPEL
        baseurl: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
        gpgcheck: yes
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: ansible
        download_only: yes
        download_dir: /tmp

    - yum_repository:
        name: ansible-runner
        description: Ansible target dependencies
        baseurl: https://releases.ansible.com/ansible-runner/rpm/epel-7-x86_64/
        gpgcheck: yes
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: python2-pexpect
        download_only: yes
        download_dir: /tmp
```

I wonder if there is specific yum configuration, yum plugins enabled and/or possibly other specific repositories enabled that would cause this.

https://github.com/ansible/ansible/issues/74962 suggests running the following task after adding the repository works around the issue:
```yaml
   - name: run makecache fast on RHEL7 to accept the GPG key
     command: yum -y makecache fast
     args:
       warn: false # prevent warning to use yum module
     when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
```
does that apply to your environment as well?

Is the issue reproducible on every run or just the first time that the repository is added?

I wonder if you would be willing to verify the theory from #74962 and put a breakpoint or just `raise Exception` or something in https://github.com/ansible/ansible/blob/0ddaf6edd66dc7f7e24cd8ec66aaf9a5e23fd63f/lib/ansible/modules/yum.py#L736-L750 to see if that code is indeed the cause of the issue.

Thanks!

needs_info

**Comment by gjvoosten** [comment]
@mkrizek When faced with this problem, I also tried running our playbook against CentOS 7 (or more accurately, against CentOS running in a Docker container), and like you, I was unable to reproduce it there. So it is either something specific to Red Hat 7, or to the way Red Hat is configured in Azure VM's. I will look at your feedback and come back on it.

**Comment by gjvoosten** [comment]
@mkrizek As a null-test, I ran your playbook against CentOS 7: no problem, as expected. Then ran it against a freshly created RH7.9 VM on Azure, and `/var` grew from:
```
# df -h /var
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/rootvg-varlv   8,0G  142M  7,9G   2% /var
```
to:
```
# df -h /var
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/rootvg-varlv  8,0G  1,2G  6,9G  15% /var
```
If I extend your playbook with three extra tasks at the bottom like so:
```yaml
- hosts: rh7
  gather_facts: false
  become: true
  tasks:
    - yum_repository:
        name: ansible-epel7
        description: Ansible Red Hat 7 EPEL
        baseurl: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
        gpgcheck: yes
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: ansible
        download_only: yes
        download_dir: /tmp

    - yum_repository:
        name: ansible-runner
        description: Ansible target dependencies
        baseurl: https://releases.ansible.com/ansible-runner/rpm/epel-7-x86_64/
        gpgcheck: yes
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: python2-pexpect
        download_only: yes
        download_dir: /tmp

    - yum:
        name: ca-certificates
        state: latest

    - yum:
        name: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-redhat-repo-2-1.noarch.rpm

    - yum:
        name: pgadmin4
        download_only: yes
        download_dir: /tmp
```
and run that against another fresh RH7.9 VM on Azure, the problem is the exact same as before, i.e. it fills the entire `/var` (and takes really long time…):
```
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/rootvg-varlv  8,0G  8,0G  192K 100% /var
```
(Note that that repo URL is the official way according to the [pgAdmin 4 docs](https://www.pgadmin.org/download/pgadmin-4-rpm/).)

**Comment by gjvoosten** [comment]
@mkrizek If I then change my playbook slightly to:
```yaml
- hosts: rh7
  gather_facts: false
  become: true
  tasks:
    - yum_repository:
        name: ansible-epel7
        description: Ansible Red Hat 7 EPEL
        baseurl: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
        gpgcheck: no
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: ansible
        download_only: yes
        download_dir: /tmp

    - yum_repository:
        name: ansible-runner
        description: Ansible target dependencies
        baseurl: https://releases.ansible.com/ansible-runner/rpm/epel-7-x86_64/
        gpgcheck: no
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: python2-pexpect
        download_only: yes
        download_dir: /tmp

    - yum:
        name: ca-certificates
        state: latest

    - yum:
        name: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-redhat-repo-2-1.noarch.rpm

    - community.general.ini_file:
        path: /etc/yum.repos.d/pgadmin4.repo
        backup: yes
        section: pgAdmin4
        option: gpgcheck
        value: 0

    - yum:
        name: pgadmin4
        download_only: yes
        download_dir: /tmp
```
and run that against yet another fresh RH7.9 VM on Azure, `/var` is 1.2G at the end of a (successful) run.

So this is only about changing `gpgcheck`; do you want me to run additional tests with changes to `repo_gpgcheck` as well?

**Comment by gjvoosten** [comment]
@mkrizek I realise there's one more thing to check, which is to test the `yum -y makecache fast` work-around. So, if I take this playbook (which has `gpgcheck` still enabled):
```yaml
- hosts: rh7
  gather_facts: true
  become: true
  tasks:
    - yum_repository:
        name: ansible-epel7
        description: Ansible Red Hat 7 EPEL
        baseurl: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/
        gpgcheck: yes
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: ansible
        download_only: yes
        download_dir: /tmp

    - yum_repository:
        name: ansible-runner
        description: Ansible target dependencies
        baseurl: https://releases.ansible.com/ansible-runner/rpm/epel-7-x86_64/
        gpgcheck: yes
        gpgkey: https://releases.ansible.com/keys/RPM-GPG-KEY-ansible-release.pub

    - yum:
        name: python2-pexpect
        download_only: yes
        download_dir: /tmp

    - yum:
        name: ca-certificates
        state: latest

    - yum:
        name: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-redhat-repo-2-1.noarch.rpm

    - name: run makecache fast on RHEL7 to accept the GPG key
      command: yum -y makecache fast
      args:
        warn: false # prevent warning to use yum module
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

    - yum:
        name: pgadmin4
        download_only: yes
        download_dir: /tmp
```
and run that against yet another fresh RH7.9 VM on Azure, `/var` is again 1.2G at the end of a (successful) run. Which means the work-around does indeed work around the problem, except that maybe you'd have to do that after _each_ repository that you add as part of your playbook (we have some more besides the ones above).
