### ISSUE TITLE
to_json filter doesn't decrypt vaulted variables

### ISSUE THREAD

**Issue by kenorb** [ansible/ansible#76334]
### Summary

Using docker_container_exec's stdin syntax doesn't decrypt vaulted variables.

I was suggested in https://github.com/ansible-collections/community.docker/issues/241 that it's most likely issue with Ansible, not the collection.

### Issue Type

Bug Report

### Component Name

docker_container_exec

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6]
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/user/.ansible.cfg) = True
CACHE_PLUGIN(/home/user/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/.ansible.cfg) = /tmp/ansible-cachedir
CACHE_PLUGIN_TIMEOUT(/home/user/.ansible.cfg) = 5
DEFAULT_GATHERING(/home/user/.ansible.cfg) = smart
DEPRECATION_WARNINGS(/home/user/.ansible.cfg) = False
DIFF_ALWAYS(/home/user/.ansible.cfg) = True
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = False
```

### OS / Environment

- Target: Ubuntu 20.04.3

### Steps to Reproduce

```yaml
    - name: Upload key
      community.docker.docker_container_exec:
        argv:
          - tee
          - secret.json
        container: '{{ docker_id }}'
        stdin: '{{ secret_data | to_json }}'
```

Var file (vaulted value is embedded):

```
secret_data:
  priv_key:
    value: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        1161...
        ....
  pub_key:
    value: some_public_key
```

### Expected Results

Vaulted variable is properly decrypted.

I've tested encryption with:

```
ansible localhost -m ansible.builtin.debug -a var=secret_data -e @all/vars.yml
```

and the syntax is valid (variable is decrypted as expected), but not when using docker collection.

### Actual Results

```console
JSON file which was created consist ansible vault data, not decrypted string.

 below
"value": {"__ansible_vault": "$ANSIBLE_VAULT;1.1;AES256;\n1161...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
it is not the `stdin` option (options don't decrypt, it happens in the core engine when assigning to options), but the `to_json`  is wrapping the vault into the JSON version of the vault object and avoiding 'devaulting', probably because we switched to unified JSON serializer which we do want in some cases to do this, but not for this case.

**Comment by bcoca** [comment]
let me know if this fixes it for you
```
diff --git a/lib/ansible/plugins/filter/core.py b/lib/ansible/plugins/filter/core.py
index 703575c0fc..55c084ff7f 100644
--- a/lib/ansible/plugins/filter/core.py
+++ b/lib/ansible/plugins/filter/core.py
@@ -65,6 +65,7 @@ def to_nice_yaml(a, indent=4, *args, **kw):

 def to_json(a, *args, **kw):
     ''' Convert the value to JSON '''
+    kw['vault_to_text'] = True
     return json.dumps(a, cls=AnsibleJSONEncoder, *args, **kw)

```

**Comment by bcoca** [comment]
As workaround
```
    - name: Upload key
      community.docker.docker_container_exec:
        argv:
          - tee
          - secret.json
        container: '{{ docker_id }}'
        stdin: '{{ secret_data | to_json(vault_to_text=True) }}'
```
