### ISSUE TITLE
Unable to use gihub_repo plugin

### ISSUE THREAD

**Issue by DaveSpe** [ansible/ansible#76331]
### Summary

I upgraded Ansible to version 4.8.0 do I could use the `github_repo` module.
Trying to create a repo from ansible code fails with Ansible not being able to find the module. 
Tried the short version and the long version of the plugin. 

It can be found here. 
https://docs.ansible.com/ansible/latest/collections/community/general/github_repo_module.html

### Issue Type

Bug Report

### Component Name

community.general.github_repo

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dspedzia/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/dspedzia/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
no output
```

### OS / Environment
```
WSL2 :

NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Steps to Reproduce

```
  - name: Create Github repository
    github_repo:
      access_token: "{{ github_token }}"
      organization: "GovAlta"
      name: "aro-{{aro_env}}-config"
      description: "ARO {{ aro_env }}cluster configuration repository."
      private: yes
      state: present
    register: git_init
```

### Expected Results

Exxpecting the repo to be creted, in the least expecting it to find the module

### Actual Results

```console
ERROR! couldn't resolve module/action 'github_repo'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/dspedzia/test/ansible.yaml': line 32, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: Create Github repository
    ^ here
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
