### ISSUE TITLE
Handler example from docs doesn't pass linter

### ISSUE THREAD

**Issue by mattalxndr** [ansible/ansible#76354]
### Summary

When I run the referenced code through `ansible-lint`, I get `parser-error: conflicting action statements: hosts, tasks`:

```shell
% ansible-lint file.yml
WARNING  Listing 1 violation(s) that are fatal
parser-error: conflicting action statements: hosts, tasks
file.yml:2

You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
- parser-error  # AnsibleParserError

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

### Issue Type

Documentation Report

### Component Name

[docs/docsite/rst/user_guide/playbooks_handlers.rst](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/playbooks_handlers.rst?plain=1#L18-L47)

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.0]
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/matt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.9/site-packages/ansible
ansible collection location = /home/matt/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
jinja version = 3.0.3
libyaml = True

% ansible-lint --version
ansible-lint 5.2.1 using ansible 2.12.0
```

### Configuration

```console
$ ansible-config dump --only-changed
[nada]
```

### OS / Environment

Arch Linux, updated daily.

### Additional Information

Not applicable. I haven't submitted a PR, only referenced some code.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mattalexx** [comment]
Sorry, I thought it would show the code I was referring to. Here it is:

```yaml
---
- name: Verify apache installation
  hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Write the apache config file
    ansible.builtin.template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - Restart apache
  - name: Ensure apache is running
    ansible.builtin.service:
      name: httpd
      state: started
  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted

```
