### ISSUE TITLE
delegate_to uses None when host ansible_host is resetted

### ISSUE THREAD

**Issue by lerminou** [ansible/ansible#76359]
### Summary

I have a inventory group with the SSH variables :
```
ansible_ssh_user: root
ansible_password: 'XXXXX'
ansible_host: 192.XXXXXX
ansible_ssh_private_key_file: /root/XXXXX
```
In this inventory I have a sub group which need another SSH connection  mode so I reset the variables
```
ansible_host: ~
ansible_ssh_private_key_file: ~
```

ansible_host is not specified because I need to use a ssh.d config file due to some extra ssh configuration needed to join the host
After that, all delegate_to tasks are KO

relates to the closed issue https://github.com/ansible/ansible/issues/27351

the tasks are executed on the delegator host

### Issue Type

Bug Report

### Component Name

ssh

### Ansible Version

```console
$ ansible --version
ansible 2.10.4
  config file = /home/lerminou/project/deploy/ansible/ansible.cfg
  configured module search path = ['/home/lerminou/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
NULL
```

### OS / Environment

Fedora 34

### Steps to Reproduce

Use an inventory with previous informations SSH with a task delegated to the sub-group

```yaml (paste below)
- name: Store nginx param
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '(.*HTTP_AUTHORIZATION.*)'
    line: "fastcgi_param HTTP_AUTHORIZATION $token;"
  delegate_to: "{{ item }}"
  loop: "{{ groups['nginx'] }}"
```

### Expected Results
```console
changed: [vm-back-2 -> vm-nginx-2] => (item=vm-nginx-2)
changed: [vm-back-1 -> vm-nginx-1] => (item=vm-nginx-1)
```

### Actual Results

```console
failed: [vm-back-1 -> None] (item=vm-nginx-1) => {"ansible_loop_var": "item", "changed": false, "item": "vm-nginx-1", "msg": "Destination /etc/nginx/nginx.conf does not exist !", "rc": 257}
failed: [vm-back-2 -> None] (item=vm-nginx-2) => {"ansible_loop_var": "item", "changed": false, "item": "vm-nginx-2", "msg": "Destination /etc/nginx/nginx.conf does not exist !", "rc": 257}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/connection/ssh.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
We were not able to reproduce the issue. Can you provide minimal reproducer including your inventory file?

needs_info

**Comment by s-hertel** [comment]
This is the example I tried to reproduce with (jic you can spot a meaningful difference):
```
# inv
all:
  children:
    group1:
      vars:
        ansible_host: 192.168.0.1
      children:
        group2:
          vars:
            ansible_host: ~
          hosts:
            h1: {}
```
```
# ~/.ssh/config
Host h1
     HostName myhost
     User username
     Port 22
     IdentityFile path/to/file.pem
```
```
# playbook.yml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - ping:
    delegate_to: "{{ item }}"
    loop: "{{ groups['group1'] }}"
```

The host is unreachable because `ansible_host` is None (instead of undefined, which is what I think you might mean by 'resetting' a variable). But I wasn't able to reproduce the [host -> None] issue you're seeing.

**Comment by bcoca** [comment]
do you set `ansible_ssh_host`?

**Comment by lerminou** [comment]
Hi,

No @bcoca , `ansible_ssh_host` wasn't set neither in the parent / child host, maybe I should ?

Here is my reproducer full example: @mkrizek 

*inventory*
```
all:
  vars: ### Here al the global ssh variables 
    ansible_ssh_common_args: ' -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
    ansible_ssh_user: root
    ansible_password: 'XXXXXXXX'
    ansible_host: 192.168.XXXXXX # The production inventory is based with a proxy bastion, so I put the global host for every host
    ansible_ssh_private_key_file: /path/to/file.pem
  children:
    cloud: ## in my inventory some old servers need a special ssh config not available by these options
      vars:
        ansible_ssh_user: ~
        ansible_password: ~
        ansible_host: ~
        ansible_ssh_private_key_file: ~

      children:
        back:
          hosts:
            vm-back1: {}

        front:
          hosts:
            vm-front-1: {}

```

*ssh*
```
# ~/.ssh/config
Host vm-back1
     HostName vm-back1
     User root
     Port 22
     PubkeyAcceptedKeyTypes=+ssh-dss
     IdentityFile path/to/file.pem
Host vm-front-1
     HostName vm-front
     User root
     Port 22
     PubkeyAcceptedKeyTypes=+ssh-dss
     IdentityFile path/to/file.pem
     [...]
```

*playbook* 
```
### My back hosts need the front ipv4 server and other info so I loop over them to grab all infos
- hosts: back
  gather_facts: no

  tasks:
    - shell: "hostname"
      delegate_to: "{{ item }}"
      loop: "{{ groups['front'] }}"

```

*output*
```
### You can see the vm-back-1 in the hostname output even if it's delegated !

PLAY [back] *********************************************************************************************************************

TASK [shell] ********************************************************************************************************************
changed: [vm-back1 -> None] => (item=vm-front-1) => {"ansible_loop_var": "item", "changed": true, "cmd": "hostname", "delta": "0:00:00.003186", "end": "2021-12-06 15:11:03.128333", "item": "vm-front-1", "rc": 0, "start": "2021-12-06 15:11:03.125147", "stderr": "", "stderr_lines": [], "stdout": "vm-back1", "stdout_lines": ["vm-back1"]}

```
