### ISSUE TITLE
Add User/Password option to community.kubernetes.helm plugin

### ISSUE THREAD

**Issue by bbgobie** [ansible/ansible#76369]
### Summary

I am trying to add/deploy from a Helm repo that requires credentials.  Adding username/password fields would allow using helm repositories that require creds.

### Issue Type

Feature Idea

### Component Name

helm

### Additional Information

Some 3rd party helm repos might require credentials, such as jfrog for example.  See their documentation
https://www.jfrog.com/confluence/display/JFROG/Kubernetes+Helm+Chart+Repositories

A sample helm command might be 
helm repo add <REPO_KEY> http://<ARTIFACTORY_HOST>:<ARTIFACTORY_PORT>/artifactory/<REPO_KEY> --username <USERNAME> --password <PASSWORD>

```yaml (paste below)
- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "https://<some-jfrog-repo-address>"
    username: "<Some username>"
    password: "<Some password>"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
