### ISSUE TITLE
Operation requires privilege escalation

### ISSUE THREAD

**Issue by mmMOLINARI** [ansible/ansible#76394]
### Summary

When I run a playbook with multiple tasks using loop to make changes in vlans in several RUCKUS ICX switches, sometimes I get the message **Operation requires privilege escalation** and the playbook stops. There is no changes in the playbook or in the switch. When I run the playbook again it completes fine. This symptom fits the description found at the section **Intermittent failure while using ansible.netcommon.network_cli connection type** at
https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html.
I tried the recommended action but the issue persists.

### Issue Type

Bug Report

### Component Name

network_cli

### Ansible Version

```console
$ ansible --version
ansible 2.10.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/moduless']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuthentications=publickey
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = ~/.ansible/cp
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/moduless']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = network_cli
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 18.04.3 LTS
Playbook using the commscope.icx galaxy collection running against RUCKUS ICX switch, software release 9.0.00

### Steps to Reproduce

The playbook below runs against a single ICX switch, looping twice through 5 vlans. The switch is local to the Ansible server. Sometimes the message **Operation requires privilege escalation** shows and the playbook stops. Changing the value of ansible_buffer_read_timeout from the default (0.1 sec) to 0.5 or larger values\ does not eliminate the issue. The messages show for around 1% of the tasks.

![image](https://user-images.githubusercontent.com/68390677/143935283-4f81fc2f-67a1-4f4a-bcc3-b94c788cf3e8.png)

```yaml (paste below)
---
- hosts: all
  gather_facts: no
  vars:
    ansible_network_os: commscope.icx.icx
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: admin
    ansible_password: ruckus123!
    ansible_buffer_read_timeout: .5
    vlans:
      - name: backbone
        vlan_id: 10
      - name: metro
        vlan_id: 20
      - name: access
        vlan_id: 30
      - name: aggregation
        vlan_id: 40
      - name: internet
        vlan_id: 50
      - name: backbone
        vlan_id: 10
      - name: metro
        vlan_id: 20
      - name: access
        vlan_id: 30
      - name: aggregation
        vlan_id: 40
      - name: internet
        vlan_id: 50
  tasks:
   - name: 1 - create vlan with untagged and tagged ports
     commscope.icx.icx_vlan:
       name: '{{ item.name }}'
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
          #  - ethernet 1/2/1 to 1/2/2
          #  - ethernet 1/3/1 to 1/3/2
            - ethernet 1/2/1
            - ethernet 1/3/1
     loop: "{{ vlans }}"
     tags: always

   - name: 2 - change vlan name
     commscope.icx.icx_vlan:
       name: wireless
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
     loop: "{{ vlans }}"
     tags: always

   - name: 3 - remove ports from existing vlan
     commscope.icx.icx_vlan:
       name: internet
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
         # - ethernet 1/3/1 to 1/3/2
          - ethernet 1/3/1
         state: absent
     loop: "{{ vlans }}"
     tags: always

   - name: 4 - add untagged and tagged ports to existing vlan
     commscope.icx.icx_vlan:
       name: internet
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
         # - ethernet 1/3/1 to 1/3/2
          - ethernet 1/3/1
     loop: "{{ vlans }}"
     tags: always

   - name: 5 - purge all ports from existing vlan, except the ports that are listed
     commscope.icx.icx_vlan:
       name: internet
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
          # - ethernet 1/3/1 to 1/3/2
           - ethernet 1/3/1
         purge: True
     loop: "{{ vlans }}"
     tags: always

   - name: 6 - add ports to existing vlan using aggregate
     commscope.icx.icx_vlan:
       check_running_config: True
       aggregate:
         # - {vlan_id: '20', name: internet, tagged: {name: ethernet 1/2/1 to 1/2/2}}
         - {vlan_id: '20', name: internet, tagged: {name: ethernet 1/2/1}}
     loop: "{{ vlans }}"
     tags: always

   - name: 7 - configure 802-1d
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       stp:
         type: 802-1d
         priority: 128
         enabled: True
     loop: "{{ vlans }}"
     tags: always

   - name: 8 - configure 802-1w
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       stp:
         type: 802-1w
         priority: 128
         enabled: True
     loop: "{{ vlans }}"
     tags: always

   - name: 9 - Remove 802-1w
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       stp:
         type: 802-1w
         enabled: False
     loop: "{{ vlans }}"
     tags: always

   - name: 10 - add lag to existing vlan
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'      
       tagged:
         name: 
           - lag 10
     loop: "{{ vlans }}"
     tags: always

   - name: 11 - create 3 vlans using aggregate
     commscope.icx.icx_vlan:
       check_running_config: True
       aggregate:
         - {vlan_id: '60', tagged: {name: ethernet 1/1/7}}
         - {vlan_id: '70', tagged: {name: ethernet 1/1/7}}
     loop: "{{ vlans }}"
     tags: always

   - name: 12 - purge all vlans, except the ones listed
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       purge: True
     loop: "{{ vlans }}"
     tags: always

   - name: 13 - remove vlan entirely
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       state: absent
     loop: "{{ vlans }}"
     tags: always
```

### Expected Results

No privilege escalation error messages

### Actual Results

```console
PLAY [all] ************************************************************************************************

TASK [1 - create vlan with untagged and tagged ports] *****************************************************
Monday 29 November 2021  19:34:54 +0000 (0:00:00.036)       0:00:00.036 ******* 
failed: [10.0.0.213] (item={'name': 'backbone', 'vlan_id': 10}) => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "name": "backbone",
        "vlan_id": 10
    }
}

MSG:

operation requires privilege escalation
changed: [10.0.0.213] => (item={'name': 'metro', 'vlan_id': 20})
changed: [10.0.0.213] => (item={'name': 'access', 'vlan_id': 30})
changed: [10.0.0.213] => (item={'name': 'aggregation', 'vlan_id': 40})
changed: [10.0.0.213] => (item={'name': 'internet', 'vlan_id': 50})
changed: [10.0.0.213] => (item={'name': 'backbone', 'vlan_id': 10})
ok: [10.0.0.213] => (item={'name': 'metro', 'vlan_id': 20})
ok: [10.0.0.213] => (item={'name': 'access', 'vlan_id': 30})
ok: [10.0.0.213] => (item={'name': 'aggregation', 'vlan_id': 40})
ok: [10.0.0.213] => (item={'name': 'internet', 'vlan_id': 50})

PLAY RECAP ************************************************************************************************
10.0.0.213                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
