### ISSUE TITLE
TerminalModule object has no attribute close

### ISSUE THREAD

**Issue by mmMOLINARI** [ansible/ansible#76393]
### Summary

When I run a playbook with multiple tasks using loop to make changes in vlans in several RUCKUS ICX switches, sometimes I get the warning message TerminalModule object has no attribute close. The affected task completes, but I cannot explain the root cause. The message is triggered by the TerminalModule class, invoked by the icx.py module.

### Issue Type

Bug Report

### Component Name

TerminalModule class in icx.py

### Ansible Version

```console
$ ansible --version
ansible 2.10.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/moduless']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuth
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = ~/.ansible/cp
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/moduless']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = network_cli
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 18.04.3 LTS
Playbook using the commscope.icx galaxy collection running against RUCKUS ICX switch, software release 9.0.00

### Steps to Reproduce

The playbook below runs against a single ICX switch, looping twice through 5 vlans. The switch is local to the Ansible server. Sometimes the warning message **'TerminalModule' object has no attribute 'close'** shows during a task execution:

![image](https://user-images.githubusercontent.com/68390677/143930234-4959206d-1454-4d36-b6a5-e34788fb613d.png)

The rate for this error is around 1-2% of the executed tasks.
icx.py is a module used by many vendors (using different names). It seems to take care of opening and closing a terminal session, reporting  error messages and moving to privilege escalation.

```yaml (paste below)
---
- hosts: all
  gather_facts: no
  vars:
    ansible_network_os: commscope.icx.icx
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: admin
    ansible_password: password
    # ansible_buffer_read_timeout: .5
    vlans:
      - name: backbone
        vlan_id: 10
      - name: metro
        vlan_id: 20
      - name: access
        vlan_id: 30
      - name: aggregation
        vlan_id: 40
      - name: internet
        vlan_id: 50
      - name: backbone
        vlan_id: 10
      - name: metro
        vlan_id: 20
      - name: access
        vlan_id: 30
      - name: aggregation
        vlan_id: 40
      - name: internet
        vlan_id: 50
  tasks:
   - name: 1 - create vlan with untagged and tagged ports
     commscope.icx.icx_vlan:
       name: '{{ item.name }}'
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
            - ethernet 1/2/1
            - ethernet 1/3/1
     loop: "{{ vlans }}"
     tags: always

   - name: 2 - change vlan name
     commscope.icx.icx_vlan:
       name: wireless
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
     loop: "{{ vlans }}"
     tags: always

   - name: 3 - remove ports from existing vlan
     commscope.icx.icx_vlan:
       name: internet
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
          - ethernet 1/3/1
         state: absent
     loop: "{{ vlans }}"
     tags: always

   - name: 4 - add untagged and tagged ports to existing vlan
     commscope.icx.icx_vlan:
       name: internet
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
          - ethernet 1/3/1
     loop: "{{ vlans }}"
     tags: always

   - name: 5 - purge all ports from existing vlan, except the ports that are listed
     commscope.icx.icx_vlan:
       name: internet
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       tagged:
         name: 
           - ethernet 1/3/1
         purge: True
     loop: "{{ vlans }}"
     tags: always

   - name: 6 - add ports to existing vlan using aggregate
     commscope.icx.icx_vlan:
       check_running_config: True
       aggregate:
         - {vlan_id: '20', name: internet, tagged: {name: ethernet 1/2/1}}
     loop: "{{ vlans }}"
     tags: always

   - name: 7 - configure 802-1d
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       stp:
         type: 802-1d
         priority: 128
         enabled: True
     loop: "{{ vlans }}"
     tags: always

   - name: 8 - configure 802-1w
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       stp:
         type: 802-1w
         priority: 128
         enabled: True
     loop: "{{ vlans }}"
     tags: always

   - name: 9 - Remove 802-1w
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       stp:
         type: 802-1w
         enabled: False
     loop: "{{ vlans }}"
     tags: always

   - name: 10 - add lag to existing vlan
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'      
       tagged:
         name: 
           - lag 10
     loop: "{{ vlans }}"
     tags: always

   - name: 11 - create 3 vlans using aggregate
     commscope.icx.icx_vlan:
       check_running_config: True
       aggregate:
         - {vlan_id: '60', tagged: {name: ethernet 1/1/7}}
         - {vlan_id: '70', tagged: {name: ethernet 1/1/7}}
     loop: "{{ vlans }}"
     tags: always

   - name: 12 - purge all vlans, except the ones listed
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       purge: True
     loop: "{{ vlans }}"
     tags: always

   - name: 13 - remove vlan entirely
     commscope.icx.icx_vlan:
       check_running_config: True
       vlan_id: '{{ item.vlan_id }}'
       state: absent
     loop: "{{ vlans }}"
     tags: always
```

### Expected Results

Do not see any warning messages

### Actual Results

```console
Sometimes the warning message 'TerminalModule' object has no attribute 'close' shows during a task execution. See details in section Steps to Reproduce
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
