### ISSUE TITLE
ERROR: Can't create group on macOS

### ISSUE THREAD

**Issue by peter-gyarmati** [ansible/ansible#76419]
### Summary

When running simple task to create user it fails with an error saying:

`fatal: [Mac-machine]: FAILED! => {"changed": false, "msg": "Username and password must be provided.\n", "name": "group-name"}`

### Issue Type

Bug Report

### Component Name

group

### Ansible Version

```console
$ ansible --version
2.11.6
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

macOS 11.6.1

### Steps to Reproduce

```yaml (paste below)
- name: Ensure group "mygroup" exists
  ansible.builtin.group:
    name: mygroup
    state: present
```

### Expected Results

The group has been created

### Actual Results

```console
fatal: [Mac-machine]: FAILED! => {"changed": false, "msg": "Username and password must be provided.\n", "name": "group-name"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
