### ISSUE TITLE
unarchive module: Solaris version of 'tar' doesn't support decompression options.

### ISSUE THREAD

**Issue by yeroc** [ansible/ansible#7644]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 6bc056e012) last updated 2014/06/02 14:42:33 (GMT -600)
##### Environment:

Solaris 10/11
##### Summary:

The unarchive module assumes gnu tar with support for directly decompressing tgz, bzip & xz compression formats but the Solaris version of tar doesn't support the -z, -j or -J options respectively.  It would be great if the unarchive module would fallback to looking for gzip, bzip & xz binaries and using them to handle the decompression.
##### Steps To Reproduce:

Given a simple unarchive task:

```
- name: Copy packages...
  unarchive: src="{{ item }}" dest="/tmp" copy=yes
  with_items:
    - "solaris/jdk-7u55-solaris-i586.tgz"
    - "solaris/jdk-7u55-solaris-x64.tgz"
```
##### Expected Results:

Expect the file(s) to be unarchived on the destination host.
##### Actual Results:

```
failed: [dbload-solaris] => (item=solaris/jdk-7u55-solaris-i586.tgz) => {"failed": true, "item": "solaris/jdk-7u55-solaris-i586.tgz"}
msg: Failed to find handler to unarchive. Make sure the required command to extract the file is installed.
```
