### ISSUE TITLE
win_template fails with ansible 2.10.15

### ISSUE THREAD

**Issue by dhabierre** [ansible/ansible#76456]
### Summary

ansible 2.10.15 + **win_template** => failure: `FileNotFoundError: [Errno 2] No such file or directory: b'C:/Setup/SQL2019ST_x64_ENU/ConfigurationFile.ini'` (if I replace *win_template* with *win_copy* the step succeed)

### Issue Type

Bug Report

### Component Name

ansible-base

### Ansible Version

```console
$ ansible --version
ansible 2.10.15
```

### Configuration

```console
$ ansible-config dump --only-changed
nothing appears
```

### OS / Environment

Windows 10 1809 + Docker based on Ubuntu 21.10

### Steps to Reproduce

```yaml
- name: '[MSSQL][4/7] Copy ConfigurationFile.ini'
  win_template:
    src: 'templates/ConfigurationFile.ini'
    dest: '{{ setup_folder }}/{{ app_unzip_folder_name }}/ConfigurationFile.ini'
    force: yes
```

### Expected Results

Should template and copy file 'templates/ConfigurationFile.ini' from ansible host to target

### Actual Results

```console
FileNotFoundError: [Errno 2] No such file or directory: b'C:/Setup/SQL2019ST_x64_ENU/ConfigurationFile.ini'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
