### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by bitshiftnetau** [ansible/ansible#76460]
### Summary

When I try to create a container on Proxmox, it fails saying that "fatal: [central.local]: FAILED! => {"changed": false, "msg": "creation of lxc VM 810 failed with exception: int() argument must be a string, a bytes-like object or a number, not 'NoneType'"}"

### Issue Type

Bug Report

### Component Name

community-general (apparently the bot doesn't like this)
This is how I installed the componen: `ansible-galaxy collection install community.general`

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/<user>/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.9 (main, Nov 20 2021, 21:30:06) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed

INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['yaml', 'ini']
```

### OS / Environment

Arch Linux in LXC on Proxmox

### Steps to Reproduce

```yaml (paste below)
- name: Create new LXC container in Proxmox
  hosts: 'central.local'
  tasks:
    - name: 'Create container'
      proxmox:
- name: Create new LXC container in Proxmox
  hosts: 'central.local'
  tasks:
    - name: 'Create container'
      proxmox:
        vmid: '810' # specifying container ID
        api_user: 'root@pam' # Proxmox user
        api_password: '' # password in plaintext
        api_host: 'central.local' # proxmox hostname
        password: 'password' # container password in plaintext
        hostname: 'CT-Prometheus-ArchLinux' # container hostname
        node: 'central' # name of proxmox host
        cores: '1'
        cpus: '2'
        cpuunits: '1000'
        ostemplate: 'local:vztmpl/archlinux-base_20210420-1_amd64.tar.gz'
        storage: 'VMs'
        disk: '16'
        memory: '512'
        nameserver: '8.8.8.8'
        netif: '{"net0":"name=eth0,ip=dhcp,bridge=vmbr10"}'
        state: 'present'
```

### Expected Results

I expect it to connect and create a container.

### Actual Results

```console
$ ansible-playbook playbooks/vm_template.yml
PLAY [Create new LXC container in Proxmox] *********************************************************************

TASK [Gathering Facts] *****************************************************************************************
ok: [central.local]

TASK [Create container] ****************************************************************************************
fatal: [central.local]: FAILED! => {"changed": false, "msg": "creation of lxc VM 810 failed with exception: int() argument must be a string, a bytes-like object or a number, not 'NoneType'"}

PLAY RECAP *****************************************************************************************************
central.local              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
