### ISSUE TITLE
docker module starts unrelated container

### ISSUE THREAD

**Issue by discordianfish** [ansible/ansible#7648]
This task:

```
- name: run foo
  docker:
    image: repo/foo-image:abc
    name: foo
    ports: "{{ansible_int.ipv4.address}}:{{foo.port}}:9090"
```

creates and runs a container named 'foo' but also tries to start a stopped and unrelated second container differentrepo/foo-image:latest. Probably some issue with the filter conditions when figuring out which containers are supposed to be started.
