### ISSUE TITLE
Templating type error - can only concatenate list (not \"dict_values\") to list"}

### ISSUE THREAD

**Issue by mvorisek** [ansible/ansible#76507]
### Summary

`.values()` should be concateable with list, however, manual list cast is needed, eg. the code below needs currently this extra edit:

```diff
-  with_items: "{{ ([{ 'path': '/tmp/php' }] + php_tmp_dirs.values()) | list }}"
+  with_items: "{{ ([{ 'path': '/tmp/php' }] + (php_tmp_dirs.values() | list)) | list }}"
```

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
2.11.7
```

### Configuration

```console
see steps to reproduce
```

### OS / Environment

Debian 11

### Steps to Reproduce

```yaml
php_tmp_dirs:
  cli: { path: "/tmp/php/cli" }
  upload: { path: "/tmp/php/upload" }
```

```yaml
- name: "Tmp files - create tmp directories"
  file:
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ ([{ 'path': '/tmp/php' }] + php_tmp_dirs.values()) | list }}"
```

### Expected Results

no error

### Actual Results

```console
TASK [php : Tmp files - create tmp directories] ********************************
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ ([{ 'path': '/tmp/php' }] + php_tmp_dirs.values()) | list }}): can only concatenate list (not \"dict_values\") to list"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
