### ISSUE TITLE
copy module strips formatting when content: is formatted json

### ISSUE THREAD

**Issue by amoklilli** [ansible/ansible#76509]
### Summary

The documentation of the module `copy` should state that there is a function used to dump json in `content=`. The function used strips the inserted json from the formatting.

@jpmens

```
$ ansible-doc copy
...
- content
        When used instead of `src', sets the contents of a file directly to the specified
        value.
        Works only when `dest' is a file. Creates the file if it does not exist.
        For advanced formatting or if `content' contains a variable, use the [template]
        module.
        [Default: (null)]
        type: str
        version_added: 1.1
...
```

Example-Playbook:
```
---
- name: play fetch with slurp, copy and filters
  hosts: 
    - localhost
  vars:
    getfile: "./files/hw.json"
    putfile: "/tmp/hw.json"

  tasks:
    - name: slurp the file
      slurp:
        src: "{{ getfile }}"
      register: foo 

    - name: copy (save) file to
      copy:
        content: "{{ foo.content | b64decode }}"
        dest: "{{ putfile }}"

```

Example-JSON-File:
```
$ cat files/hw.json 
{
       "name": "Markus Horn",
       "myserial": "2016-0102030405",
       "model": "Thinkpad",
       "series": "X-Series"
}
```
Output of copied file:
```
$ cat /tmp/hw.json 
{"name": "Markus Horn", "myserial": "2016-0102030405", "model": "Thinkpad", "series": "X-Series"}$
```

### Issue Type

Documentation Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /home/amoklilli/Schulung/ansible/ansible.cfg
  configured module search path = ['/home/amoklilli/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/amoklilli/Schulung/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/amoklilli/Schulung/ansible/ansible.cfg) = ['/home/amoklilli/Schulung/ansible/hosts']
DEFAULT_MANAGED_STR(/home/amoklilli/Schulung/ansible/ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}
host: {host}
```

### OS / Environment

NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

### Additional Information

When the improvement is applied, the documentation states the behaviour of copy more precisely.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by jpmens** [comment]
I think the main problem is that module documentation doesn't say anything about JSON being handled specially when using the `content` parameter.

**Comment by sivel** [comment]
Ultimately this is a duplicate of https://github.com/ansible/ansible/issues/34595#issuecomment-356091161

To work around this behavior, you can tell Ansible that you want it to always be a string, and use:

```yaml
    - name: copy (save) file to
      copy:
        content: "{{ foo.content | b64decode | string }}"
        dest: "{{ putfile }}"
```

See https://docs.ansible.com/ansible/latest/reference_appendices/config.html#string-type-filters

Otherwise, I'd recommend that you use the `template` module instead of `copy`+`content`, as indicated in the above referenced issue.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
