### ISSUE TITLE
The evaluation of a list in task vars of a set_fact task results in a different value than without task vars

### ISSUE THREAD

**Issue by dmrub** [ansible/ansible#76501]
### Summary

Using a task vars in the task set_fact to define a temporary value produces a different result than simply doubling the expression.

### Issue Type

Bug Report

### Component Name

variables

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/rubinste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/rubinste/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/bin/ansible
  python version = 3.9.9 (main, Nov 19 2021, 00:00:00) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora release 33 (Thirty Three)

### Steps to Reproduce

```yaml (paste below)
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:

    - name: Split filename
      set_fact:
        value0: "{{ value[0] }}"
        value1: "{{ value[1] }}"
      vars:
        value: "{{ ('test.txt.j2' | splitext | first | splitext) }}"

    - name: Print values
      debug:
        msg: 
          - "{{ value0 }} of type {{ value0 | type_debug }}"
          - "{{ value1 }} of type {{ value1 | type_debug }}"

    - name: Split filename
      set_fact:
        value0: "{{ ('test.txt.j2' | splitext | first | splitext)[0] }}"
        value1: "{{ ('test.txt.j2' | splitext | first | splitext)[1] }}"

    - name: Print values
      debug:
        msg: 
          - "{{ value0 }} of type {{ value0 | type_debug }}"
          - "{{ value1 }} of type {{ value1 | type_debug }}"

```

### Expected Results

The example playbook repeats the same evaluation twice, but produces different results. The results the first time are wrong because value is not a list or a tuple, but a string with the content "('test', '.txt')".

The first time, the variables in the set_fact task are used to avoid calculating the value twice (deleting the .j2 extension and then splitting the remaining filename into name and extension), and the second time, the evaluation is simply duplicated.

Everything works as expected when the DEFAULT_JINJA2_NATIVE configuration option is set to true! But it is unclear to me if this is the expected behavior and if so, where is it documented?

### Actual Results

```console
PLAY [127.0.0.1] ***************************************************************

TASK [Split filename] **********************************************************
ok: [127.0.0.1]

TASK [Print values] ************************************************************
ok: [127.0.0.1] => {
    "msg": [
        "( of type str",
        "' of type str"
    ]
}

TASK [Split filename] **********************************************************
ok: [127.0.0.1]

TASK [Print values] ************************************************************
ok: [127.0.0.1] => {
    "msg": [
        "test of type str",
        ".txt of type str"
    ]
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is expected. The result templating is always a `string` because Jinja2 always returns a `string`. To achieve desired result you have would have to convert the result into a `list` (more about that in the link below):

```yaml
- set_fact:
     value0: "{{ value[0] }}"
     value1: "{{ value[1] }}"
   vars:
     value: "{{ 'test.txt.j2' | splitext | first | splitext | list }}"
```

or, as you correctly identified, enable `jinja2_native`.

You can read a bit more about this in https://gist.github.com/mkrizek/dbcf415b485fc3f2d4b3676ce0013397 (the gist will become partially outdated with the release of Ansible `2.13` as some of the internals will change though with minimal change in behavior).
