### ISSUE TITLE
Passing unsafe variables between plays does not work as expected

### ISSUE THREAD

**Issue by dmrub** [ansible/ansible#76505]
### Summary

Depending on how I pass the unsafe variables between plays, they can be evaluated unexpectedly. This problem seems to be related to https://github.com/ansible/ansible/issues/76501, since everything works when DEFAULT_JINJA2_NATIVE is set to true. 

### Issue Type

Bug Report

### Component Name

variables

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/rubinste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/rubinste/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rubinste/Kubernetes/ClusterManager/ansible-test/venv/bin/ansible
  python version = 3.9.9 (main, Nov 19 2021, 00:00:00) [GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Fedora release 33 (Thirty Three)

### Steps to Reproduce

The playbooks require simple inventory to simulate the second host
`inventory.yml`:
```yaml
all:
  hosts:
    host_1:
      ansible_host: 127.0.1.1
      ansible_connection: local
``` 
Playbook `test-pass-unsafe-not-working.yml`:
```yaml (paste below)
- name: Process variables
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Create vars file
      copy:
        content: !unsafe |
          unsafe_value: !unsafe '{{ dont_expand }}'
        dest: "{{ playbook_dir }}/my_vars.yml"

    - name: Include vars
      include_vars:
        file: "my_vars.yml"
        name: my_vars

    - name: Print vars
      debug:
        var: my_vars

- name: Process variables
  hosts: host_1
  gather_facts: false

  tasks:
    - name: Print vars
      debug:
        msg: "my_vars: {{ hostvars['127.0.0.1'].my_vars }}, type: {{ hostvars['127.0.0.1'].my_vars | type_debug }}"

    - name: Copy my_vars from 127.0.0.1 to this host
      set_fact:
        my_vars: "{{ hostvars['127.0.0.1'].my_vars }}"

    - name: Print vars
      debug:
        msg: "my_vars: {{ my_vars }}, type:  {{ my_vars | type_debug }}"

```

Playbook: `test-pass-unsafe-working.yml`
```yaml (paste below)
- name: Process variables
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Create vars file
      copy:
        content: !unsafe |
          unsafe_value: !unsafe '{{ dont_expand }}'
        dest: "{{ playbook_dir }}/my_vars.yml"

    - name: Include vars
      include_vars:
        file: "my_vars.yml"
        name: my_vars

    - name: Print vars
      debug:
        var: my_vars

    - name: Copy my_vars from this host to host_1
      # Source: https://medium.com/opsops/pocking-into-others-hostvars-69475ff0a8cf
      set_fact:
        my_vars: "{{ my_vars }}"
      delegate_facts: true
      delegate_to: host_1

- name: Process variables
  hosts: host_1
  gather_facts: false

  tasks:
    - name: Print vars
      debug:
        msg: "my_vars: {{ hostvars['127.0.0.1'].my_vars }}, type: {{ hostvars['127.0.0.1'].my_vars | type_debug }}"

    - name: Print vars
      debug:
        msg: "my_vars: {{ my_vars }}, type:  {{ my_vars | type_debug }}"

```
Successful runs:

1. `ansible-playbook -i inventory.yml test-pass-unsafe-working.yml`
2. `ANSIBLE_JINJA2_NATIVE=1 ansible-playbook -i inventory.yml test-pass-unsafe-not-working.yml`

Failed runs:
1. `ansible-playbook -i inventory.yml test-pass-unsafe-not-working.yml`

### Expected Results

I assume that both playbooks work the same way. They create a variable file that contains unsafe variables on the local host and include them. Then they pass all the loaded variables to the other host and output them. However, only the `test-pass-unsafe-working.yml' playbook works. The playbook `test-pass-unsafe-not-working.yml` fails, but only if DEFAULT_JINJA2_NATIVE is not enabled! It is unclear to me why this happens and how to prevent it. At least an explanation would be helpful.

### Actual Results

```console
$ ansible-playbook -i inventory.yml test-pass-unsafe-not-working.yml

PLAY [Process variables] ********************************************************************************************************************************************************************

TASK [Create vars file] *********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Include vars] *************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Print vars] ***************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "my_vars": {
        "unsafe_value": "{{ dont_expand }}"
    }
}

PLAY [Process variables] ********************************************************************************************************************************************************************

TASK [Print vars] ***************************************************************************************************************************************************************************
ok: [host_1] => {
    "msg": "my_vars: {'unsafe_value': '{{ dont_expand }}'}, type: dict"
}

TASK [Copy my_vars from 127.0.0.1 to this host] *********************************************************************************************************************************************
ok: [host_1]

TASK [Print vars] ***************************************************************************************************************************************************************************
fatal: [host_1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {'unsafe_value': '{{ dont_expand }}'}: 'dont_expand' is undefined\n\nThe error appears to be in '/home/rubinste/Kubernetes/ClusterManager/ansible-test/test_pass_unsafe/test-pass-unsafe-not-working.yml': line 35, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Print vars\n      ^ here\n"}

PLAY RECAP **********************************************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
host_1                     : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
