### ISSUE TITLE
[cron] An extra line should be added after the cronjob in the crontab

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#76521]
### Summary

Hello there 👋

I've had an issue with a cronjob installed on a guest server using the ansible cron module.

My cronjob never triggered and after [some research](https://serverfault.com/questions/230370/why-is-only-one-wget-command-working-in-my-crontab), I found out that adding an extra line bellow the task it in the crontab made it work again.

Could the cron module ensure that the cron line is not the last line of the file to avoid any error of this type?

### Issue Type

Bug Report

### Component Name

cron

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nicolas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nicolas/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nicolas/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Desktop : Fedora 35 Workstation
Server (target) : Debian 11 Bullseye in a QEMU/KVM

### Steps to Reproduce

```yaml (paste below)
- name: gitea | gitea-backup
  cron:
    name: gitea-backup
    user: root
    minute: "5,20,35,50"
    job: /home/nicolas/scripts/gitea/gitea-backup.sh

```

### Expected Results

I expected my cronjob to run every fifteen minutes. (I chose "5,20,35,50" because it needed to be run after another task that runs every "*/15").

### Actual Results

```console
There is no error as far as Ansible is concerned. It's at the cron level and it doesn't show any error.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/cron.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cron.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by davidmpaz** [comment]
Hello there,

i can confirm this happens also in ubuntu-18.04.4-server-amd64. When using a task like:

```yaml
- name: Install cronjob for key generation
  cron:
    cron_file: letsencrypt-certificate-renewal
    name: letsencrypt certificate renewal
    user: root
    job: cd {{ acme_tiny_data_directory }} && ./renew-certs.py ; /usr/sbin/service nginx reload
    day: "{{ letsencrypt_cronjob_daysofmonth }}"
    hour: "4"
    minute: "30"
    state: present
```

i even tried to output the command with new line at end like:
```yaml
job: |
    cd {{ acme_tiny_data_directory }} && ./renew-certs.py ; /usr/sbin/service nginx reload
```

but new line was trimmed on result file in `cron.d`

Thanks in advance,
David

**Comment by s-hertel** [comment]
I've been trying to reproduce this without success on Debian 11 Bullseye. Vixie Cron refuses to install if there's a missing final newline, but it only happens if I remove the final `+ '\n'` in [render](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cron.py#L515).
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": false,
            "cron_file": null,
            "day": "*",
            "disabled": false,
            "env": false,
            "hour": "*",
            "insertafter": null,
            "insertbefore": null,
            "job": "/bin/bash -l -c 'date > /home/admin/cron-test.txt'",
            "minute": "10,15",
            "month": "*",
            "name": "cron-test",
            "special_time": null,
            "state": "present",
            "user": "admin",
            "weekday": "*"
        }
    },
    "msg": "new crontab file is missing newline before EOF, can't install.\n"
}
```
Without that edit, the task succeeds and the job runs as expected.
Adding a newline to the job itself won't work as a workaround - newlines are removed due to issues like https://github.com/ansible/ansible-modules-core/issues/3791.

@AliyevH Have you tested if that fixes it? It seems like render() is doing exactly what the documentation says though.

**Comment by AliyevH** [comment]
@s-hertel Yes you are write
There is some confusing moments.

New line that we add ('\n') is a character that shows end of line
If we try to cat or open file with editors like vscode, atom, nano, etc ... it will show new line, because of eol character.
But this new line not shows in vim. Technical details i don't know why this happens, but for vim it's only eol char, not new line

Cron will not work if there's only eol char, it needs a whole new line.
i have faced with this issue in production servers. after that manually added new lines with vim

In the bottom vim not shows new line, i think for cron it's the same

<img width="746" alt="Screen Shot 2021-12-18 at 02 49 58" src="https://user-images.githubusercontent.com/5507950/146616706-5e5f4520-c7d8-4af7-ae5d-9aca99667bdc.png">

**Comment by jameslivulpi** [comment]
@s-hertel  I cannot create this on Debian 11 either.

play:
```
    - cron:
        name: hello1
        user: root
        minute: "12,13,14,15"
        job: logger 'cron1'
```

syslog showing logger ran at min 12-15:
```
Dec 19 02:12:01 debian-s-1vcpu-1gb-nyc1-01 CRON[1074]: (root) CMD (logger 'cron1')
Dec 19 02:12:01 debian-s-1vcpu-1gb-nyc1-01 root: cron1
Dec 19 02:13:01 debian-s-1vcpu-1gb-nyc1-01 CRON[1078]: (root) CMD (logger 'cron1')
Dec 19 02:13:01 debian-s-1vcpu-1gb-nyc1-01 root: cron1
Dec 19 02:14:01 debian-s-1vcpu-1gb-nyc1-01 CRON[1081]: (root) CMD (logger 'cron1')
Dec 19 02:14:01 debian-s-1vcpu-1gb-nyc1-01 root: cron1
Dec 19 02:15:01 debian-s-1vcpu-1gb-nyc1-01 CRON[1095]: (root) CMD (logger 'cron1')
Dec 19 02:15:01 debian-s-1vcpu-1gb-nyc1-01 root: cron1
```

Looking at hexdump of cron file it seems like newline is there:

000000f0  72 6f 6e 31 27 0a                                 |ron1'.|
                                             ^

Also cannot create on Fedroa35, CentOS8, and Ubuntu 18.04.6 LTS
