### ISSUE TITLE
Inconsistent datestring behavior when enclosed in square brackets

### ISSUE THREAD

**Issue by mwtrigg** [ansible/ansible#76533]
### Summary

When using a date string enclosed in square brackets, any the string is evaluated as a mathematical expression when the first field in the date string is non-zero.

I have found a workaround by prepending the leading square bracket with a space

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible 2.10.1
  config file = /home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg
  configured module search path = ['/home/mtrigg/git/crabel-it/ansible-employee/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 12 2021, 04:40:35) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_ACTION_PLUGIN_PATH(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = ['/home/mtrigg/.local/lib/python3.6/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = ['/home/mtrigg/.local/lib/python3.6/site-packages/ara/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = ['/home/mtrigg/git/crabel-it/ansible-employee/inventory']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = ['/home/mtrigg/git/crabel-it/ansible-employee/plugins/inventory']
DEFAULT_MODULE_PATH(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = ['/home/mtrigg/git/crabel-it/ansible-employee/library']
RETRY_FILES_ENABLED(/home/mtrigg/git/crabel-it/ansible-employee/ansible.cfg) = False
```

### OS / Environment

Red Hat Enterprise Linux release 8.4 (Ootpa)

### Steps to Reproduce

```yaml (paste below)
---
  - hosts: localhost
    gather_facts: false
    vars:
      date_string:
        - "09/12/2021"
        - "10/12/2021"
        - "09-12-2021"
        - "10-12-2021"
    tasks:
      - name: Looped without brackets
        debug:
          msg: "{{ item }}"
        loop: "{{ date_string }}"

      - name: Looped with brackets
        debug:
          msg: "[{{ item }}]"
        loop: "{{ date_string }}"

      - name: Workaround, prepend a space to the leading bracket
        debug:
          msg: " [{{ item }}]"
        loop: "{{ date_string }}"
```

### Expected Results

Expected the results between `09/12/2021` and `10/12/2021` (either mm/dd/yy or dd/mm/yy, or mm-dd-yy and dd-mm-yy) to be consistent; a series of strings with and without square brackets.  Frankly, they could either both work or both fail, but the inconsistent behavior is what is undesired.

So far, I have seen this behavior when using either the slash `/` or the hash  (minus) `-` character as a separator.

This can lead to problems during the last quarter of the year (if using US style dates) or anytime after the 9th of the month (if using a non-US date format)

### Actual Results

```console
PLAY [localhost] ***************************************************************

TASK [Looped without brackets] *************************************************
Friday 10 December 2021  10:27:06 -0500 (0:00:00.079)       0:00:00.079 *******
ok: [localhost] => (item=09/12/2021) => {
    "msg": "09/12/2021"
}
ok: [localhost] => (item=10/12/2021) => {
    "msg": "10/12/2021"
}
ok: [localhost] => (item=09-12-2021) => {
    "msg": "09-12-2021"
}
ok: [localhost] => (item=10-12-2021) => {
    "msg": "10-12-2021"
}

TASK [Looped with brackets] ****************************************************
Friday 10 December 2021  10:27:06 -0500 (0:00:00.136)       0:00:00.216 *******
ok: [localhost] => (item=09/12/2021) => {
    "msg": "[09/12/2021]"
}
ok: [localhost] => (item=10/12/2021) => {
    "msg": [
        0.00041233712683490025
    ]
}
ok: [localhost] => (item=09-12-2021) => {
    "msg": "[09-12-2021]"
}
ok: [localhost] => (item=10-12-2021) => {
    "msg": [
        -2023
    ]
}

TASK [Workaround, prepend a space to the leading bracket] **********************
Friday 10 December 2021  10:27:06 -0500 (0:00:00.089)       0:00:00.305 *******
ok: [localhost] => (item=09/12/2021) => {
    "msg": " [09/12/2021]"
}
ok: [localhost] => (item=10/12/2021) => {
    "msg": " [10/12/2021]"
}
ok: [localhost] => (item=09-12-2021) => {
    "msg": " [09-12-2021]"
}
ok: [localhost] => (item=10-12-2021) => {
    "msg": " [10-12-2021]"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
