### ISSUE TITLE
unarchive module support for single zipped file

### ISSUE THREAD

**Issue by nickhammond** [ansible/ansible#7654]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Agent: OS X 10.9.2
Client: Ubuntu 12.04 LTS
##### Summary:

A directory shouldn't be required for unzipping single file archives.
###### defaults/main.yml

```
wkhtmltox_source: http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.0/wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz
```
###### tasks/main.yml

```
- name: Download wkthmltox.tar.bz2 file
  get_url:
    url: "{{ wkhtmltox_source }}"
    dest: /tmp/{{ wkhtmltox_source | basename }}

- name: Unzip wkhtmltox.tar.bz2 to /usr/bin/wkhtmltox
  unarchive:
    src: /tmp/{{ wkhtmltox_source | basename }}
    dest: /usr/bin/wkhtmltox
    creates: /usr/bin/wkhtmltox
    copy: no
```
##### Expected Results:

wkhtmltox-linux-amd64_0.12.0-03c001d.tar.xz should be unzippable to /usr/bin/wkhtmltox and not require a directory as the destination.
###### Output from the playbook

```
TASK: [wkhtmltoimage | Download wkthmltoimage.tar.bz2 file] *******************
ok: [192.168.111.222]

TASK: [wkhtmltoimage | Unzip wkhtmltox.tar.bz2 to /usr/bin/wkhtmltox] *********
failed: [192.168.111.222] => {"failed": true, "item": ""}
msg: dest '/usr/bin/wkhtmltox' must be an existing dir
```
