### ISSUE TITLE
ansible.builtin.file: Symlink on NFS to outside NFS gives "invalid selinux context: [Errno 95] Operation not supported"

### ISSUE THREAD

**Issue by LHurst-JM** [ansible/ansible#76548]
### Summary

Managing a symlink (with state: symlink) tries to set the selinux context to invalid context (for some reason it's trying to change the correct nfs_t to incottrect fusefs_t within an NFS-mounted filesystem).  This causes the module to fail with an invalid secontext.

I have tried maintaining the secontext by specifying the existing value with the `setype` (and the entire thing with `serole`, `seuser` and `selevel` as well) per the ansible.builtin.file docs (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html) but this seems to have no effect at all on what the module it trying to set.

I do see the secontext change proposed (as the only change) when run with `--check --diff`.

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.5] 
  config file = /mnt/home/hurstl01/projects/HPC-JM/Ansible/ansible.cfg
  configured module search path = ['/mnt/home/hurstl01/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/apps/sysapps/venvs/ansible/lib/python3.6/site-packages/ansible
  ansible collection location = /mnt/home/hurstl01/.ansible/collections:/usr/share/ansible/collections
  executable location = /mnt/apps/sysapps/venvs/ansible/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/mnt/home/hurstl01/projects/HPC-JM/Ansible/ansible.cfg) = True
DEFAULT_FORKS(/mnt/home/hurstl01/projects/HPC-JM/Ansible/ansible.cfg) = 50
DEFAULT_TIMEOUT(/mnt/home/hurstl01/projects/HPC-JM/Ansible/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(/mnt/home/hurstl01/projects/HPC-JM/Ansible/ansible.cfg) = False
```

### OS / Environment

CentOS 7

### Steps to Reproduce

```yaml (paste below)
- name: Create symlink
  become: true
  ansible.builtin.file:
    force: true
    owner: "{{ item }}"
    group: "{{ item }}"
    path: /mnt/home/{{ item }}/ANALYSIS
    src: /mnt/analysis/{{ users[item].fileshare_name or item }}
    follow: false
    state: link
  loop:
    - user1
    - user2
```

### Expected Results

Symlink (which already exists, points to correct place and has correct ownership) to be unchanged (this is the case in the example result below).

Symlink which is incorrect to be updated to match configuration.

Missing symlink to be created according to configuration.

### Actual Results

```console
failed: [HPC-VDI-test] (item=['hurstl01', 'archive']) => {"ansible_loop_var": "item", "changed": false, "cur_context": ["system_u", "object_r", "nfs_t", "s0"], "gid": 2019, "group": "hurstl01", "input_was": ["system_u", "object_r", "nfs_t", "s0"], "item": ["hurstl01", "archive"], "mode": "0777", "msg": "invalid selinux context: [Errno 95] Operation not supported", "new_context": ["system_u", "object_r", "fusefs_t", "s0"], "owner": "hurstl01", "path": "/mnt/home/hurstl01/ARCHIVE", "secontext": "system_u:object_r:nfs_t:s0", "size": 12, "state": "link", "uid": 2019}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by jameslivulpi** [comment]
I tried testing this on devel and I couldn't recreate, Could send your `/proc/mounts` output? or `grep hurstl01 /proc/mounts` Maybe I can to recreate better.

**Comment by LHurst-JM** [comment]
Hi

```
$ grep hurstl01 /proc/mounts
//stahpcfileshare001.file.core.windows.net/hurstl01 /mnt/analysis/hurstl01 cifs rw,relatime,vers=3.0,cache=strict,username=stahpcfileshare001,domain=X,uid=2019,forceuid,gid=2019,forcegid,addr=10.91.47.11,file_mode=0700,dir_mode=0700,soft,persistenthandles,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1 0 0
```

I'm also seeing this creating a symlink to this mount (which is NFS - same play, just SCRATCH for the symlink name and /mnt/scratch as the src):

```
10.91.44.20:/VOL-PROD-SCRATCH /mnt/scratch nfs rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.91.44.20,mountvers=3,mountport=635,mountproto=tcp,local_lock=none,addr=10.91.44.20 0 0
```

There are 3 other symlinks to mounts, where the targets are fuse, in the same direcotry (managed by preceeding tasks) - I wonder if the secontext for those is somehow leaking through to the later tasks?

I've fallen back to doing this as a workaround, which is working without an issue:

```
- name: Create symlink
  become: true
  ansible.builtin.shell: if [ ! -e /mnt/home/{{ item }}/ANALYSIS ]; then ln -s /mnt/analysis/{{ users[item].fileshare_name or item }} /mnt/home/{{ item }}/ANALYSIS ] && chown {{ item }}:{{ item }} /mnt/home/{{ item }}/ANALYSIS && echo created_symlink; fi
  register: output
  changed_when: "'created_symlink' in output.stdout"
  loop:
    - user1
    - user2
```

**Comment by jameslivulpi** [comment]
I tried various symbolic links to fusefs within the directory and still no luck on recreation on Fedora35 and devel and looked over fixes in this area between 2.11 and devel:

git log --oneline --graph --decorate --abbrev-commit  origin/stable-2.11..origin/devel -- lib/ansible/module_utils/basic.py

```
* 9b4f9e9fd3 Drop python2.6 support in module execution (#76106)
* 74f5367673 Ensure `heuristic_log_sanitize` returns correct data if no password found (#75570)
* ce6d8a143c Code cleanup to prepare for pylint update. (#75475)
* 61900c7672 modules moved to use best_parsable_locale (#75250)
* 415e08c297 Try to get best usable locale (#75033)
* 98138584b7 Don't mutate os.environ in AnsibleModule.run_command, make a copy, and pass to Popen (#74791)
* 870f943365 docs: Update Python 2 doc links (#74633)
* 1006363589 basic: Skip over module parameters (#74559)
* 7099657dd7 Basic: don't call lstat when check_mode (#64279)
* 17237c1d88 Deprecate Py2.6 support for target nodes (#74165)
```

git log --oneline --graph --decorate --abbrev-commit  origin/stable-2.11..origin/devel -- lib/ansible/modules/file.py   
```
* e2ad9f1c85 Changed to file instead path for touch choice in state parameter docs (#75282)
* c5d8dc0e11 Add attributes 2/x (#75619)
```


Looks like we may have to see if others can recreate and if its a bug or some selinux .. one more thing in meantime is mounting the nfs share with context:

`-o context="system_u:object_r:nfs_t:s0"`

**Comment by LHurst-JM** [comment]
> one more thing in meantime is mounting the nfs share with context:
>
> `-o context="system_u:object_r:nfs_t:s0"`

Would you expect that to make a difference and do you mean the share on which the symlink is being made or the one being linked to?  They all have the correct context, and ansible.builtin.file is trying to replace the correct context (nfs_t) with one that is completely wrong for both the location of the symlink and the target (fusefs_t).

```
$ ls -ldZ /mnt/scratch
drwxrwxrwt. root root system_u:object_r:nfs_t:s0 
$ ls -ldZ /mnt/analysis/hurstl01
drwx------. hurstl01 hurstl01 system_u:object_r:cifs_t:s0      /mnt/analysis/hurstl01
$ ls -ldZ /mnt/home
drwxr-xr-x. root root system_u:object_r:nfs_t:s0       /mnt/home
$ ls -lZ /mnt/home/hurstl01/
[..]
lrwxrwxrwx. hurstl01 hurstl01 system_u:object_r:nfs_t:s0       ANALYSIS -> /mnt/analysis/hurstl01
lrwxrwxrwx. hurstl01 hurstl01 system_u:object_r:nfs_t:s0       APPS -> /mnt/apps
lrwxrwxrwx. hurstl01 hurstl01 system_u:object_r:nfs_t:s0       ARCHIVE -> /mnt/archive
lrwxrwxrwx. hurstl01 hurstl01 system_u:object_r:nfs_t:s0       SCRATCH -> /mnt/scratch
lrwxrwxrwx. hurstl01 hurstl01 system_u:object_r:nfs_t:s0       SHARED -> /mnt/shared
```

`/mnt/archive` and `/mnt/shared` are `system_u:object_r:fusefs_t:s0` but Ansible is not trying to update the contexts of those symlinks away from `nfs_t`.  It looks like it's the one after in the play that it's trying to change to match the target of the link in the previous task, which smells like something leaking through via a variable to me.  My play has nothing about SELinux specified in it anywhere.

> if its a bug or some selinux

I'm not sure this is going to be a bug in selinux when the context is currently correct and Ansible wants to change it to something non-sensicle - could be a bug in Ansible's selinux integration?

**Comment by jameslivulpi** [comment]
I have tried to recreate today but no luck, if you can give a  "dummed" down play that I can try, I will attempt some more.. I can create fuse mounts and nfs as needed to recreate. thanks

**Comment by LHurst-JM** [comment]
This is copied and pasted from my play:

```
# I tried to use ansible.builtin.file but it wants to change the SELinux
# context to something invalid and fails.  See https://github.com/ansible/ansible/issues/76548
- name: Create user's symlinks
  become: true
  ansible.builtin.file:
    force: true
    owner: "{{ item[0] }}"
    group: "{{ item[0] }}"
    path: /mnt/home/{{ item[0] }}/{{ item[1].upper() }}
    src: /mnt/{{ item[1] }}
    follow: false
    state: link  
  loop: "{{ vm_users | product(user_links) }}"
  vars:
    user_links:
      - shared
      - scratch
      - apps
      - archive
# Analysis is a special case due to non-static target
- name: Create user's Analysis symlinks
  become: true
  ansible.builtin.file:
    force: true
    owner: "{{ item }}"
    group: "{{ item }}"
    path: /mnt/home/{{ item }}/ANALYSIS
    src: /mnt/analysis/{{ users[item].fileshare_name or item }}"
    follow: false
    state: link  
  loop: "{{ vm_users }}"
```

vm_users is a variable set on the host listing usernames to setup on it.

users is a map of usernames to information about that user (e.g. uid/gid etc.) - the 'fileshare_name' value will override if their the users' fileshare isn't named the same as their username but for most of my users it's the username.

The filesystems (all mounted under /mnt):

shared and archive are fuse (blobfuse to be precise)

home, apps, scratch are nfs

analysis/... are cifs
