### ISSUE TITLE
Allow stdout_callback plugin to be specified in the playbook level

### ISSUE THREAD

**Issue by mahoutukaisali** [ansible/ansible#76556]
### Summary

 It would be nice if we can specify the stdout_callback plugin on a per play and a per task basis because in some cases, we need different stdout on a per play and a per task basis. 

The use case example looks like this:

```
tasks:
  - name: foobar
    do_something_module:
      option: blah
    stdout_callback: yaml
```
```
---
- hosts: group_A
  stdout_callback: yaml

  tasks:
    - ping:

- hosts: group_B
  stdout_callback: json

  tasks:
    - ping:
```

### Issue Type

Feature Idea

### Component Name

ansible core

### Additional Information

None

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
