### ISSUE TITLE
Ansible crashes when creating EC2 instance

### ISSUE THREAD

**Issue by maksymiliev** [ansible/ansible#76561]
### Summary

When running a task which creates EC2 instance in Ansible 2.9.27 with python2.7 interpreter, it occasionally crashes during the execution. This issue is intermittent.

### Issue Type

Bug Report

### Component Name

ec2

### Ansible Version

```console
2.9.27
```

### Configuration

```console
[defaults]
timeout=60
ansible_python_interpreter = /usr/bin/env python3
ansible_managed = This file is managed by Ansible
retry_files_enabled = no
private_role_vars = yes
host_key_checking = no
roles_path = ./roles
```

### OS / Environment

Ubuntu 18.04 Docker container running gitlab runner

### Steps to Reproduce

```yaml (paste below)
- name: Create EC2 instance
      ec2:
        instance_type: "{{ yocto3_aws_instance_type }}"
        region: "{{ yocto3_aws_region }}"
        image: "{{ yocto3_aws_ec2_ami }}"
        key_name: "{{ yocto3_aws_key_name }}"
        instance_tags:
          Name: "{{ yocto3_aws_instance_name }}: {{ yocto3_env_image_name }}"
          Group: "{{ yocto3_aws_instance_name }}"
          ImageName: "{{ yocto3_env_target }}"
          ImageVersion: "{{ yocto3_env_loopedge_image_tag }}"
          Branch: "{{ yocto3_env_loopedge_meta_version }}"
          GitlabJobID: "{{ lookup('env','CI_JOB_ID')|default('unknown', true) }}"
          GitlabPipelineID: "{{ lookup('env','CI_PIPELINE_ID')|default('unknown', true) }}"
        monitoring: yes
        vpc_subnet_id: "{{ yocto3_aws_vpc_subnet_id }}"
        group: "{{ yocto3_aws_security_groups }}"
        user_data: |
          #!/bin/sh
          /sbin/shutdown -P +170 &
        wait: yes # need to wait otherwise public_ip is not populated
      register: ec2
```

### Expected Results

I expect the task to finish successfully.

### Actual Results

```console
TASK [Create EC2 instance] *****************************************************
task path: /builds/loop-edge-yocto/meta-loopedge/build/yocto3-aws-create-instance-build.yml:51
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/ec2.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "instance_ids": [
        "i-0cb312b6cadd2d3dd"
    ], 
    "instances": [
        {
            "ami_launch_index": "0", 
            "architecture": "x86_64", 
            "block_device_mapping": {
                "/dev/sda1": {
                    "delete_on_termination": true, 
                    "status": "attached", 
                    "volume_id": "vol-0c3ba6e1c84bb7474"
                }, 
                "/dev/sdf": {
                    "delete_on_termination": true, 
                    "status": "attached", 
                    "volume_id": "vol-0e030745a18e53452"
                }
            }, 
            "dns_name": "ec2-44-195-84-51.compute-1.amazonaws.com", 
            "ebs_optimized": false, 
            "groups": {
                "sg-05262c7955c59626a": "ssh-only", 
                "sg-06fc704c7714c1723": "default"
            }, 
            "hypervisor": "xen", 
            "id": "i-0cb312b6cadd2d3dd", 
            "image_id": "ami-05870e15d3df840eb", 
            "instance_type": "c5d.9xlarge", 
            "kernel": null, 
            "key_name": "{MASKED}", 
            "launch_time": "2021-12-14T08:05:51.000Z", 
            "placement": "us-east-1a", 
            "private_dns_name": "{MASKED}", 
            "private_ip": "{MASKED}", 
            "public_dns_name": "{MASKED}", 
            "public_ip": "{MASKED}", 
            "ramdisk": null, 
            "region": "us-east-1", 
            "root_device_name": "/dev/sda1", 
            "root_device_type": "ebs", 
            "state": "running", 
            "state_code": 16, 
            "tags": {
                "Branch": "develop", 
                "GitlabJobID": "Job", 
                "GitlabPipelineID": "ID", 
                "Group": "Group", 
                "ImageName": "Name", 
                "ImageVersion": "Version", 
                "Name": "Image"
            }, 
            "tenancy": "default", 
            "virtualization_type": "hvm"
        }
    ], 
    "invocation": {
        "module_args": {
            "assign_public_ip": null, 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "count": 1, 
            "count_tag": null, 
            "debug_botocore_endpoint_logs": false, 
            "ebs_optimized": false, 
            "ec2_url": null, 
            "exact_count": null, 
            "group": [
                "default", 
                "ssh-only"
            ], 
            "group_id": null, 
            "id": null, 
            "image": "ami-05870e15d3df840eb", 
            "instance_ids": null, 
            "instance_initiated_shutdown_behavior": "stop", 
            "instance_profile_name": null, 
            "instance_tags": {
                "Branch": "develop", 
                "GitlabJobID": "Job", 
                "GitlabPipelineID": "ID", 
                "Group": "Group", 
                "ImageName": "Name", 
                "ImageVersion": "Version", 
                "Name": "Image"
            }, 
            "instance_type": "c5d.9xlarge", 
            "kernel": null, 
            "key_name": "loopedge-yocto", 
            "monitoring": true, 
            "network_interfaces": null, 
            "placement_group": null, 
            "private_ip": null, 
            "profile": null, 
            "ramdisk": null, 
            "region": "us-east-1", 
            "security_token": null, 
            "source_dest_check": null, 
            "spot_launch_group": null, 
            "spot_price": null, 
            "spot_type": "one-time", 
            "spot_wait_timeout": 600, 
            "state": "present", 
            "tenancy": "default", 
            "termination_protection": null, 
            "user_data": "#!/bin/sh\n/sbin/shutdown -P +170 &\n", 
            "validate_certs": true, 
            "volumes": null, 
            "vpc_subnet_id": "subnet-03a1c20e9a6b492f0", 
            "wait": true, 
            "wait_timeout": 300, 
            "zone": null
        }
    }, 
    "tagged_instances": []
}
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory
the full traceback was:
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 128, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 282, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/strategy/linear.py", line 283, in run
    _hosts=self._hosts_cache, _hosts_all=self._hosts_cache_all)
  File "/usr/lib/python2.7/dist-packages/ansible/vars/manager.py", line 349, in get_vars
    data = preprocess_vars(self._loader.load_from_file(vars_file, unsafe=True))
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 85, in load_from_file
    file_name = self.path_dwim(file_name)
  File "/usr/lib/python2.7/dist-packages/ansible/parsing/dataloader.py", line 195, in path_dwim
    return unfrackpath(path, follow=False)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/path.py", line 55, in unfrackpath
    b_basedir = to_bytes(os.getcwd(), errors='surrogate_or_strict')
OSError: [Errno 2] No such file or directory
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
