### ISSUE TITLE
Signficant performance regression buried in docs - pipelining disabled silently when upgrading from ansible-base 2.10

### ISSUE THREAD

**Issue by vkvm** [ansible/ansible#76572]
### Summary

We manage a lot of apps + systems using Ansible - as few as tens, to as many as several thousand.

We're currently using ansible-base 2.10.x, and started testing ansible project 5.0.1 / ansible-core 2.12.1.

We immediately noticed a slowdown at scale - around 4 times as long to complete for the very first playbook we ran across hundreds of systems. More commonly, for smaller playbooks, it was more like twice as long.

After much troubleshooting, we realized that our ansible.cfg had this:

```
[ssh_connection]
pipelining = true
```

It seems starting in ansible 2.11, possibly in 2.12, it needs to be in the `[defaults]` or `[connection]` section, as mentioned here:

https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-pipelining

so it was silently ignored, thus causing our out of box experience with the upgrade to be a significant performance regression. Moving that setting to `[defaults]` fixed the issue, as should moving it to `[connections]`.

Sadly, that doc says nothing about the change compared to previous releases; it just lists the current settings

NB: another problem is that page has no version in the URL, so unless there's a note about when a config changed, it's not as convenient as looking up the docs for a specific release such as: https://docs.ansible.com/ansible/2.9/reference_appendices/config.html where you can see the older behaviour and compare the docs to a different release.

Further compounding this was that:

```
ansible-doc -t connection ssh
```

says:

```yaml
- pipelining
        Pipelining reduces the number of connection operations required to execute a module on the remote server, by executing many Ansible modules without actual file transfers.
        This can result in a very significant performance improvement when enabled.
        However this can conflict with privilege escalation (become). For example, when using sudo operations you must first disable 'requiretty' in the sudoers file for the target hosts, which is why this feature is disabled by default.
        [Default: ANSIBLE_PIPELINING]
        set_via:
          env:
          - name: ANSIBLE_PIPELINING
          - name: ANSIBLE_SSH_PIPELINING
          ini:
          - key: pipelining
            section: connection
          - key: pipelining
            section: ssh_connection
          vars:
          - name: ansible_pipelining
          - name: ansible_ssh_pipelining
        
        type: boolean
```
which is no longer correct in ansible 2.12, probably starting with 2.11.

This comes from the DOCUMENTATION string in `ansible/plugins/connection/ssh.py` ( https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py#L218-L222 )

That caused us a lot of confusion, and prolonged this issue. It's only `ansible-config dump` that clued us in to the fact that pipelining was not enabled.

So, looking for further documentation, I noticed in https://github.com/ansible/ansible/blob/stable-2.11/changelogs/CHANGELOG-v2.11.rst, there's this note:

> Restructured pipelining settings to be at the connection plugins leaving base config as global and for backwards compatiblity.

That sounds benign (mentions backwards compatibility), but it's the first hint at a major change.

The Porting Guide says nothing about this.

So I think:
- There may be a bug here - i.e. you'd think such an important change for a setting that's been in use for a while would be made in a backwards compatible way with some deprecation notice.
- If it's not considered a bug: The changelogs and Porting Guides need to emphasis such a change
- The DOCUMENTATION string in the module should match so that `ansible-doc` matches the website docs. I can put in a PR if needed for this

### Issue Type

Documentation Report

### Component Name

lib/ansible/connection/ssh.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = /home/demouser1/projects/ansible/settings-issue/ansible.cfg
  configured module search path = ['/home/demouser1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/demouser1/.venvs/ansible-settings-issue-2.12/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/demouser1/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/demouser1/.venvs/ansible-settings-issue-2.12/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/demouser1/projects/ansible/settings-issue/ansible.cfg) = True
# This was only after the fix
```

### OS / Environment

RHEL7, RHEL8, Fedora 35

### Additional Information

Fixing this will avoid performance regressions for anyone using ansible at scale who uses common tuning techniques such as this, when upgrading from ansible 2.10.x to newer releases.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/connection/ssh.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
What do you get from the following command?
`ansible-config dump --only-changed  -t connection ssh`

**Comment by bcoca** [comment]
so i found one thing that made it backwards incompatible and it is the missing ini entry for `[defaults]` section, but I do not see a missing `[ssh_connection]` one.

**Comment by s-hertel** [comment]
This seems related to the ssh_connection issue: https://github.com/ansible/ansible/pull/76432

**Comment by vkvm** [comment]
> What do you get from the following command, (with file before the fix)? `ansible-config dump --only-changed -t connection ssh`

The not-working version before moving to defaults:

```
$ cat ansible.cfg 
[ssh_connection]
pipelining = true
[user1:~/projects/ansible/settings-issue] [ansible-settings-issue-2.12] $ ansible-config dump --only-changed -t connection ssh

ssh:
___
pipelining(/home/demouser1/projects/ansible/settings-issue/ansible.cfg) = True
```

Interesting. Independent of that, what I did was run this simple playbook with `-vvv` to observe whether pipelining was working or not:

```yaml
---
- hosts: "all"
  gather_facts: false
  tasks:
    - name: "run uname"
      command: "uname -a"
```

One of the things we'd like to do now is add a test to our deployments to validate our ansible config. i.e. capture all our customizations now, and assert with each upgrade that they're still present. That might not work in some cases such as above, where the config for the connection plugin is read, but doesn't end up taking effect. Still, more validation should help overall.

I haven't used `ansible-config` for other than very basic things. Is there a way to dump *all* configs, including connection plugin config? That makes it a lot easier to capture all our changed settings in one shot.

Is there an easy way to do this from pytest? i.e. presumably we'd construct a fixture from some lib used internally.
