### ISSUE TITLE
When using the pip module, I encountered a problem that "_" is automatically converted to "-"

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#76607]
### Summary

It seems to be the situation after the pip upgrade. Using the default version (8.1.2) does not have this problem. Test pip versions 18.0~19.0.3 will all appear, and the "_" in the installation package name will be automatically converted to "-" , And an error saying that it could not be found when executing the script：

```shell
$ ansible-playbook docker-service.yaml  
failed: [10.1.6.227] (item=backports.ssl_match_hostname-3.5.0.1.tar.gz) => {"ansible_loop_var": "item", "changed": false, "cmd": ["/usr/bin/pip2", "install", "backports.ssl-match-hostname-3.5.0.1.tar.gz"], "item": "backports.ssl_match_hostname-3.5.0.1.tar.gz", "msg": "stdout: Processing./backports.ssl-match-hostname-3.5.0.1.tar.gz\n\n:stderr: Requirement 'backports.ssl-match-hostname-3.5.0.1.tar.gz' looks like a filename, but the file does not exist\nCould not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/root/gz/backports.ssl-match-hostname-3.5.0.1.tar.gz'\n\nYou are using pip version 18.0, however version 21.3.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}
...
failed: [10.1.6.227] (item=websocket_client-0.56.0.tar.gz) => {"ansible_loop_var": "item", "changed": false, "cmd": ["/usr/bin/pip2", "install", "websocket-client-0.56.0.tar.gz"], "item": "websocket_client-0.56.0.tar.gz", "msg": "stdout: Processing ./websocket-client-0.56.0.tar.gz\n\n:stderr: Requirement 'websocket-client-0.56.0.tar.gz' looks like a filename, but the file does not exist\nCould not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/root/gz/websocket-client-0.56.0.tar.gz'\n\nYou are using pip version 18.0, however version21.3.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}
...
```

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible 2.9.25
  config file = /root/docker-services/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
CACHE_PLUGIN(/root/docker-services/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/root/docker-services/ansible.cfg) = fact_cache
CACHE_PLUGIN_TIMEOUT(/root/docker-services/ansible.cfg) = 86400
DEFAULT_FORKS(/root/docker-services/ansible.cfg) = 200
DEFAULT_GATHERING(/root/docker-services/ansible.cfg) = smart
DEFAULT_HOST_LIST(/root/docker-services/ansible.cfg) = [u'/root/docker-services/inventory']
DEFAULT_REMOTE_USER(/root/docker-services/ansible.cfg) = root
DEFAULT_ROLES_PATH(/root/docker-services/ansible.cfg) = [u'/root/docker-services/roles']
HOST_KEY_CHECKING(/root/docker-services/ansible.cfg) = False
```

### OS / Environment

$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

### Steps to Reproduce

$ cat docker-service.yaml
```yaml 
---
- name: install docker docker-compose docker-py
  hosts: mid
  roles:
    - docker

#- name: init nacos
#  hosts: mid
#  roles:
#    - nacos-standalone

```

$ cat tasks/main.yml
```yaml
...
- name: upgrade py modules
  pip:
    name: "{{item}}"
    chdir: /root/gz
    extra_args: "--upgrade"
  loop:
    - pip-18.0.tar.gz

- name: install py modules
  pip:
    name: "{{item}}"
    chdir: /root/gz
  loop:
    - appdirs-1.4.3.tar.gz
    - asn1crypto-0.22.0.tar.gz
    - backports.ssl_match_hostname-3.5.0.1.tar.gz
    - bcrypt-3.1.3.tar.gz
    - cffi-1.14.4.tar.gz
    - cryptography-2.4.2.tar.gz
    - enum34-1.1.6.tar.gz
    - idna-2.5.tar.gz
    - ipaddress-1.0.18.tar.gz
    - packaging-16.8.tar.gz
    - paramiko-2.4.2.tar.gz
    - pycparser-2.17.tar.gz
    - PyNaCl-1.0.1.tar.gz
    - pyOpenSSL-18.0.0.tar.gz
    - pyparsing-2.2.0.tar.gz
    - requests-2.20.0.tar.gz
    - setuptools-18.5.tar.gz
    - six-1.10.0.tar.gz
    - urllib3-1.24.3.tar.gz
    - websocket_client-0.56.0.tar.gz
    - docker-py-4.4.4.tar.gz
```

### Expected Results

Always will, I am still testing a lower pip version.

### Actual Results

```console
This is the details of one of them：

<10.1.6.227> ESTABLISH SSH CONNECTION FOR USER: root
<10.1.6.227> SSH: EXEC sshpass -d8 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a7a2500d5a 10.1.6.227 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1640353794.45-128215-123518405725728/ > /dev/null 2>&1 && sleep 0'"'"''
<10.1.6.227> (0, '', '')
failed: [10.1.6.227] (item=websocket_client-0.56.0.tar.gz) => {
    "ansible_loop_var": "item",
    "changed": false,
    "cmd": [
        "/usr/bin/pip2",
        "install",
        "websocket-client-0.56.0.tar.gz"
    ],
    "invocation": {
        "module_args": {
            "chdir": "/root/gz",
            "editable": false,
            "executable": null,
            "extra_args": null,
            "name": [
                "websocket_client-0.56.0.tar.gz"
            ],
            "requirements": null,
            "state": "present",
            "umask": null,
            "version": null,
            "virtualenv": null,
            "virtualenv_command": "virtualenv",
            "virtualenv_python": null,
            "virtualenv_site_packages": false
        }
    },
    "item": "websocket_client-0.56.0.tar.gz",
    "msg": "stdout: Processing ./websocket-client-0.56.0.tar.gz\n\n:stderr: Requirement 'websocket-client-0.56.0.tar.gz' looks like a filename,but the file does not exist\nCould not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/root/gz/websocket-client-0.56.0.tar.gz'\n\nYou are using pip version 18.0, however version 21.3.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
