### ISSUE TITLE
Ansible hanging on tasks with Conda

### ISSUE THREAD

**Issue by luisroque** [ansible/ansible#76615]
### Summary

I added a toy example for a few machines to clone a git repo, init conda, activate and then create a new environment. Ansible on that step just hangs forever without any type of error or output.

### Issue Type

Bug Report

### Component Name

tasks?

### Ansible Version

```console
$ ansible --version

ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mach1ne/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
---
- hosts: [servers]
  tasks:
          - name: Delete content & directory
            file:
                  state: absent
                  path: "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_hierarchical_models"
          - debug:
                  msg: "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_hierarchical_models"
          - name: Clone a git repository
            git:
                    repo: https://github.com/luisroque/run_models_distributed.git
                    dest: "/home/{{ hostvars[inventory_hostname].ansible_user }}/run_hierarchical_models"
                    clone: yes
                    update: yes
          - name: Add path and initialize conda
            shell: export PATH=~/anaconda3/bin:$PATH && conda init
            args:
                    executable: /bin/bash
          - name: Conda create new env
            shell: |
                   source "/home/{{ hostvars[inventory_hostname].ansible_user }}/anaconda3/bin/activate"
                   conda create -n run_models python=3.9
            register: conda
            args:
                    executable: /bin/bash
          - debug: var=conda.stdout_lines

```

### Expected Results

TASK [Add path and initialize conda] ***************************************************************************
changed: [server1]
changed: [server2]
changed: [server3]
changed: [server4]

TASK [Conda create new env] ************************************************************************************
changed: [server1]
changed: [server2]
changed: [server3]
changed: [server4]

PLAY RECAP *****************************************************************************************************
server1                      : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
server2                    : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
server3                   : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
server4                      : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

### Actual Results

```console
TASK [Add path and initialize conda] ***************************************************************************
changed: [server1]
changed: [server2]
changed: [server3]
changed: [server4]

TASK [Conda create new env] ************************************************************************************
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
