### ISSUE TITLE
Unable to add apt repository key via remote .gpg

### ISSUE THREAD

**Issue by lud0v1c** [ansible/ansible#76616]
### Summary

When I try to add [Terraform's GPG signing key](https://apt.releases.hashicorp.com/gpg ) to the apt keyring via the builtin _apt_key_ module, it fails throwing a "Unable to add a key from binary data" error.

### Issue Type

Bug Report

### Component Name

apt_key

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/home/lud0v1c/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lud0v1c/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/lud0v1c/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lud0v1c/.local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
(nothing)
```

### OS / Environment

Ubuntu 20.04, Ansible installed with pip (with **--user** flag).

### Steps to Reproduce

```yaml
  - name: Installs terraform
    hosts: localhost
    become_user: root
    tasks:
    - name: Add Terraform's apt signing key
      ansible.builtin.apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present
```

### Expected Results

Expected the key to be added so I could install terraform again with the _apt_ module.

### Actual Results

```console
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key add -", "msg": "Unable to add a key from binary data", "rc": 1, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\nE: This command can only be used by root.\n", "stderr_lines": ["Warning: apt-key output should not be parsed (stdout is not a terminal)", "E: This command can only be used by root."], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
