### ISSUE TITLE
Confusing default list flattening in loops

### ISSUE THREAD

**Issue by tom--** [ansible/ansible#7661]
##### Issue Type:

“Bug Report”, “Feature Idea”, Don't know
##### Ansible Version:

Please supply the verbatim output from running “ansible --version”. 
ansible 1.6.1
##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”. 

Darwin fsb.thefsb.org 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64
##### Summary:

The following doesn't work because with_items flattens lists.

```
- name: set www pool config vars
  lineinfile:
    dest=/etc/php5/fpm/pool.d/www.conf
    regexp='^ *;? *{{ item[0] }} *='
    line='{{ item[0] }} = {{ item[1] }}'
  with_items:
    - [pm.max_children, 16]
    - [pm.start_servers, 4]
    - [pm.min_spare_servers, 2]
    - [pm.max_spare_servers, 4]
  notify: restart php5-fpm
```

The workaround is:

```
- name: set www pool config vars
  lineinfile:
    dest=/etc/php5/fpm/pool.d/www.conf
    regexp='^ *;? *{{ item.key }} *='
    line='{{ item.key }} = {{ item.value }}
  with_items: php_fpm_pool_www
    - { key: pm.max_children, value: 32 }
    - { key: pm.start_servers, value: 8 }
    - { key: pm.min_spare_servers, value: 4 }
    - { key: pm.max_spare_servers, value: 8 }
  notify: restart php5-fpm
```

The problems with this are:
1. The workaround code is less readable, less DRY, obviously stupid and more liable.
2. A list of hashes serves a different purpose from a matrix (2D list to lists). The former is good for sparse data and bad for tables.
3. The flattening is unexpected and confusing to the user. It's a odd default. We don't expect an interpreter to change the structure of our data without being instructed.
4. There appears to be no way to prevent the flatting, but...
5. The explicit with_flattened way to flatten lists suggests some sort of incoherent and undefined default flattening. Expect flattening but use trial and error to find out what is flattened and what isn't?

This last point begs the question: what does the default flattening actually do? Another example shows how odd it is. Look how indexing the items with 0, 1 and 2 works:

```
- name: customize php.ini files for both cli and fpm sapis
  lineinfile:
    dest="{{ item[0] }}"
    regexp='^ *;? *{{ item[1] }} *='
    line='{{ item[1] }} = {{ item[2] }}'
    insertafter='http://php\.net/{{ item[1]|replace("_", "-") }}'
  with_nested:
    - [ '/etc/php5/fpm/php.ini', '/etc/php5/cli/php.ini' ]
    - php_ini_lines
  notify: restart php5-fpm

php_ini_lines:
  - [max_execution_time, 300]
  - [cgi.fix_pathinfo, 0]
  - [upload_max_filesize, 4M]
...
```
##### Steps To Reproduce:

See above
##### Expected Results:

See above
##### Actual Results:

Doesn't work
