### ISSUE TITLE
Jinja2 template not outputting yaml config properly.

### ISSUE THREAD

**Issue by flyerhawk** [ansible/ansible#76637]
### Summary

I have a pretty simple Jinja2 template to create yaml configs but it is not formatting properly.   Here is the template....
```
- job_name: {{ inventory_hostname }}
    pipeline_stages:
        - regex:
            expression: {{ pipeline_regex }}
        - labels:
            {% for labels in pipeline_vars -%}
            {{ labels }}:
            {% endfor %}
        - timestamp:
            source: date
            format: 2006-01-01 15:00:00.000000
        - drop:
            expression: {{ drop_expression }}
        - multiline:
            firstline: ""
            max_wait_time: 3s
            static_configs:
    static_configs:
    - targets:
        - localhost
      labels:
        app: {{ app }}
        host: {{ ansible_hostname }}
        component: {{ comp }}
        __path__: {{ file }}

```

### Issue Type

Bug Report

### Component Name

template task

### Ansible Version

```console
$ ansible --version
ansible 2.9.25
  config file = /home/resource/gltechops/promtail/promtail-ansible/ansible.cfg
  configured module search path = [u'/home/resource/gltechops/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/resource/gltechops/promtail/promtail-ansible/ansible.cfg) = [u'/home/resource/gltechops/promtail/promtail-ansible/hosts']
```

### OS / Environment

Centos 7

### Steps to Reproduce

```yaml (paste below)
  tasks:
    - name: use Jinja2 template to configure promtail - config. yaml
      template:
        src: ./templates/config.yaml.j2
        dest: /opt/promtail/config.yaml
```

### Expected Results

scrape_configs:
- job_name: 
    pipeline_stages:
        - regex:
            expression: None
        - labels:
            None:
        - timestamp:
            source: date
            format: 2006-01-01 15:00:00.000000
        - drop:
            expression: None
        - multiline:
            firstline: ""
            max_wait_time: 3s

### Actual Results

```console
scrape_configs:
- job_name: CMD_Line_Out
    pipeline_stages:
        - regex:
            expression: None
        - labels:
            None:
                    - timestamp:
            source: date
            format: 2006-01-01 15:00:00.000000

It appears to be indenting the timestamp as if it is a subsection of the labels section.    When I test it on here is works... https://j2live.ttl255.com/
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
