### ISSUE TITLE
docker_container - missing cap_add

### ISSUE THREAD

**Issue by RichardJActon** [ansible/ansible#76644]
### Summary

docker_container module does not support adding capabilities (i.e. docker --cap-add option).

`cap_drop` was added in https://github.com/ansible/ansible/pull/36889 but `cap_add` was not.

Based on the `cap_drop` issue: https://github.com/ansible/ansible/issues/29578 that was resolved by https://github.com/ansible/ansible/pull/36889

### Issue Type

Feature Idea

### Component Name

docker_container module

### Additional Information

Based on the docker compose example for pihole: https://hub.docker.com/r/pihole/pihole

```yaml (paste below)
---
- hosts: all

  become: yes
  tasks:

  # pihole container
  # --
  - name: pihole container
    community.docker.docker_container:
      name: pihole
      image: pihole/pihole:latest
      ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "80:80/tcp"
      env:
        TZ: 'Europe/London'
        # WEBPASSWORD: 'set a secure password here or it will be random'
      # Volumes store your data between container upgrades
      volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # Recommended but not required (DHCP needs NET_ADMIN)
      #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      cap_add:
        - NET_ADMIN
      restart_policy: unless-stopped

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
