### ISSUE TITLE
items2dict and dict2items are evaluated too early in loops

### ISSUE THREAD

**Issue by Flexnm** [ansible/ansible#76653]
### Summary

I am trying to loop over a dictionary when conditioning the task to make sure the dict is defined, but I find out that the condition is being skipped over

### Issue Type

Bug Report

### Component Name

dict2items and items2dict filters when using loops

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /home/ubuntu/ansible_playground/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_CALLBACK_WHITELIST(/home/ubuntu/ansible_playground/ansible.cfg) = ['profile_tasks']
DEFAULT_MODULE_PATH(/home/ubuntu/ansible_playground/ansible.cfg) = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_STDOUT_CALLBACK(/home/ubuntu/ansible_playground/ansible.cfg) = yaml
```

### OS / Environment

Ubuntu 20.04.2

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: set dict
      set_fact:
        my_dict: "{{ something | default(omit) }}"
        my_list: "{{ something | default(omit) }}"
    
    - name: condition 1
      when: false
      block:
        - name: condition 2
          when: no
          block:
            - name: condition 3
              when: False
              block:
                - name: looping
                  debug:
                    msg: "{{ item }}"
                  loop: "{{ my_dict | dict2items }}"
```

### Expected Results

I expected for the task to be skipped.

### Actual Results

```console
fatal: [localhost]: FAILED! =>
  msg: dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
See https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#using-conditionals-in-loops.

**Comment by Flexnm** [comment]
> See https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#using-conditionals-in-loops.

I admit I did not notice this piece of documentation, thank you, though I would still want to know why the conditionals are being skipped rather than evaluated before the filter is evaluated in the loop.

**Comment by mkrizek** [comment]
See also https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html#grouping-tasks-with-blocks.

> The directive does not affect the block itself, it is only inherited by the tasks enclosed by a block.

So the `when` conditional is applied to tasks within the block. Then the `loop` needs to be evaluated to a list. Then the list is being looped over, each iteration the `when` conditional is being processed.

**Comment by mkrizek** [comment]
> So the when conditional is applied to tasks within the block.

To be more clear, the above happens in a "preprocessing" phase, not at runtime, so:

```yaml
- block:
     debug:
        msg: "Hello"
  when: True
```

is processed to:
```yaml
- debug:
     msg: "Hello"
  when: True
```

and then executed.

**Comment by Flexnm** [comment]
Alright, I get it, the parsing itself causes the `when`s to stick to the individual tasks within a block and due to loops evaluating `when`s as the conditional of a `for(index; conditional; iter)` loop but only after evaluating the `loop: iteration_obj`.
I can close this, it is just a confusing behavior but the intended one.

**Comment by mkrizek** [comment]
FWIW you can do `my_dict: "{{ something | default({}) }}"` so `loop` is evaluated to an empty list and the whole task is "skipped".

**Comment by Flexnm** [comment]
I have set it up as
```
name: looping
vars:
  the_dict: "{{ parent.child_dict | default({}) }}"
module:
  module_params: "{{ do things with the items }}"
loop: "{{ the_dict | dict2items }}"
```
and it seems to work and be a bit more clear of what is going on.
