### ISSUE TITLE
Ansible.builtin.git reusing "version" in two separate repo cloning tasks

### ISSUE THREAD

**Issue by abwiggins** [ansible/ansible#76660]
### Summary

Hi, 

I am experiencing an unexpected behavior from `ansible.builtin.git` module. Currently, I am running a playbook that has a number of git repositories being cloned. AFTER the first ansible.builtin.git task is executed, for the next ansible.builtin.git task the "version" is being reused. I am specifying a "version" (specific branch to clone) in my first ansible.builtin.git task and then expecting the default behavior of ansible.builtin.git module to checkout the `HEAD` of my next repository.... this is not the case. It is using the "version" from the previous ansible.builtin.git task. 

I thought this was odd and so I tested with specifying "version" for both tasks and verified that the second ansible.builtin.git task was in fact picking up the first tasks "version".

Is this expected? Am I using this incorrectly? Any guidance is appreciated. Thanks!

Here is a code snippet that if run should, hopefully, reproduce the result. 

```
- hosts: 127.0.0.1
  connection: local

  become_user: '{{ lookup(''env'', ''USER'') }}'

  tasks:
  
  - name: create core deps workspace
    ansible.builtin.file:
      path: '{{ lookup(''env'', ''HOME'') }}/core_deps_ws/src'
      state: directory
      owner: '{{ lookup(''env'', ''USER'') }}'
      group: '{{ lookup(''env'', ''USER'') }}'

  - name: git clone monitoringmessages-ros1
    ansible.builtin.git:
      repo: 'https://github.com/aws-robotics/monitoringmessages-ros1.git'
      dest: '{{ lookup(''env'', ''HOME'') }}/core_deps_ws/src'
      clone: yes
      update: yes
      single_branch: yes
      version: 'release-latest'

  - name: Git clone serial repo
    ansible.builtin.git:
      repo: 'https://github.com/wjwwood/serial.git'
      dest: '{{ lookup(''env'', ''HOME'') }}/core_deps_ws/src'
      clone: yes
      update: yes
      version: 'HEAD'
```

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/aw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/aw/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
I did not get an output
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```
- hosts: 127.0.0.1
  connection: local

  become_user: '{{ lookup(''env'', ''USER'') }}'

  tasks:
  
  - name: create core deps workspace
    ansible.builtin.file:
      path: '{{ lookup(''env'', ''HOME'') }}/core_deps_ws/src'
      state: directory
      owner: '{{ lookup(''env'', ''USER'') }}'
      group: '{{ lookup(''env'', ''USER'') }}'

  - name: git clone monitoringmessages-ros1
    ansible.builtin.git:
      repo: 'https://github.com/aws-robotics/monitoringmessages-ros1.git'
      dest: '{{ lookup(''env'', ''HOME'') }}/core_deps_ws/src'
      clone: yes
      update: yes
      single_branch: yes
      version: 'release-latest'

  - name: Git clone serial repo
    ansible.builtin.git:
      repo: 'https://github.com/wjwwood/serial.git'
      dest: '{{ lookup(''env'', ''HOME'') }}/core_deps_ws/src'
      clone: yes
      update: yes
      version: 'HEAD'
```

### Expected Results

I expected the ansible.builtin.git module to use a different "version" specified in a different task

### Actual Results

```console
ansible-playbook [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/aw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/aw/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test_ansible.yaml ****************************************************
1 plays in test_ansible.yaml

PLAY [127.0.0.1] ***************************************************************

TASK [Gathering Facts] *********************************************************
task path: /home/aw/Desktop/test_ansible.yaml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: aw
<127.0.0.1> EXEC /bin/sh -c 'echo ~aw && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aw/.ansible/tmp `"&& mkdir "` echo /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544 `" && echo ansible-tmp-1641409394.038008-29706-39346828751544="` echo /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/aw/.ansible/tmp/ansible-local-29701waayez2o/tmpuijqlu2y TO /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544/ /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/aw/.ansible/tmp/ansible-tmp-1641409394.038008-29706-39346828751544/ > /dev/null 2>&1 && sleep 0'
ok: [127.0.0.1]
META: ran handlers

TASK [create core deps workspace] **********************************************
task path: /home/aw/Desktop/test_ansible.yaml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: aw
<127.0.0.1> EXEC /bin/sh -c 'echo ~aw && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aw/.ansible/tmp `"&& mkdir "` echo /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034 `" && echo ansible-tmp-1641409395.0418875-29787-83683822783034="` echo /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/file.py
<127.0.0.1> PUT /home/aw/.ansible/tmp/ansible-local-29701waayez2o/tmp9mdla9ql TO /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034/AnsiballZ_file.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034/ /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034/AnsiballZ_file.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034/AnsiballZ_file.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/aw/.ansible/tmp/ansible-tmp-1641409395.0418875-29787-83683822783034/ > /dev/null 2>&1 && sleep 0'
ok: [127.0.0.1] => {
    "changed": false,
    "diff": {
        "after": {
            "path": "/home/aw/core_deps_ws/src"
        },
        "before": {
            "path": "/home/aw/core_deps_ws/src"
        }
    },
    "gid": 1000,
    "group": "aw",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "follow": true,
            "force": false,
            "group": "aw",
            "mode": null,
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": "aw",
            "path": "/home/aw/core_deps_ws/src",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": false
        }
    },
    "mode": "0775",
    "owner": "aw",
    "path": "/home/aw/core_deps_ws/src",
    "size": 4096,
    "state": "directory",
    "uid": 1000
}

TASK [git clone monitoringmessages-ros1] ***************************************
task path: /home/aw/Desktop/test_ansible.yaml:15
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: aw
<127.0.0.1> EXEC /bin/sh -c 'echo ~aw && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aw/.ansible/tmp `"&& mkdir "` echo /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741 `" && echo ansible-tmp-1641409395.3287373-29814-109077322318741="` echo /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/git.py
<127.0.0.1> PUT /home/aw/.ansible/tmp/ansible-local-29701waayez2o/tmpclyml23d TO /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741/AnsiballZ_git.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741/ /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741/AnsiballZ_git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741/AnsiballZ_git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/aw/.ansible/tmp/ansible-tmp-1641409395.3287373-29814-109077322318741/ > /dev/null 2>&1 && sleep 0'
changed: [127.0.0.1] => {
    "after": "23d7a0209b10d16e62acf436c9103b326a243776",
    "before": "23d7a0209b10d16e62acf436c9103b326a243776",
    "changed": true,
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "accept_newhostkey": false,
            "archive": null,
            "archive_prefix": null,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/home/aw/core_deps_ws/src",
            "executable": null,
            "force": false,
            "gpg_whitelist": [],
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://github.com/aws-robotics/monitoringmessages-ros1.git",
            "separate_git_dir": null,
            "single_branch": true,
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "release-latest"
        }
    },
    "remote_url_changed": true
}

TASK [Git clone serial repo] ***************************************************
task path: /home/aw/Desktop/test_ansible.yaml:24
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: aw
<127.0.0.1> EXEC /bin/sh -c 'echo ~aw && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/aw/.ansible/tmp `"&& mkdir "` echo /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201 `" && echo ansible-tmp-1641409396.2204342-29862-257539222829201="` echo /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/git.py
<127.0.0.1> PUT /home/aw/.ansible/tmp/ansible-local-29701waayez2o/tmpqp1eietn TO /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201/AnsiballZ_git.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201/ /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201/AnsiballZ_git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201/AnsiballZ_git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/aw/.ansible/tmp/ansible-tmp-1641409396.2204342-29862-257539222829201/ > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "cmd": [
        "/usr/bin/git",
        "fetch",
        "--tags",
        "origin"
    ],
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "accept_newhostkey": false,
            "archive": null,
            "archive_prefix": null,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/home/aw/core_deps_ws/src",
            "executable": null,
            "force": false,
            "gpg_whitelist": [],
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://github.com/wjwwood/serial.git",
            "separate_git_dir": null,
            "single_branch": false,
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "msg": "Failed to download remote objects and refs:  fatal: couldn't find remote ref refs/heads/release-latest\n"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
