### ISSUE TITLE
vsphere_guest module: vm_nic options do not work

### ISSUE THREAD

**Issue by ronaldl** [ansible/ansible#7666]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7
##### Environment:

Ubuntu 12.04
##### Summary:

vm_nic option in vsphere_guest does not reconfigure the networks a VM is connected to
##### Steps To Reproduce:

Have an existing VM connected to "VM Network".
Run an ansible-playbook which reconfigures the VM to connect it to VM Network 2.
##### Expected Results:

The VM should be connected to VM Network 2.
##### Actual Results:

The VM is still connected to VM Network.  Modifications to CPU/memory seem to work, but I am unable to use the vsphere_guest module to reconfigure a VM's networking.

**Comment by whereismyjetpack** [comment]
I'm going to add some information to this, since I feel like the issue I'm having is related. I'm trying to remove the second nic from a VM by only specifying the first: I'm using state: reconfigured. I'm going to try and do some further testing to help determine a root cause, I'll comment here if I come up with anything.

```
vm_nic:
  nic1:
    type: vmxnet3
    network: "{{ network }}"
    network_type: dvs
```

The VM was built with: 

```
vm_nic:
  nic1:
    type: vmxnet3
    network: " {{ network }}"
    network_type: dvs
  nic2:
    type: vmxnet3
    network: "{{ network_2 }}"
    network_type: dvs
```
