### ISSUE TITLE
module_defaults appears to merge all settings

### ISSUE THREAD

**Issue by dud225** [ansible/ansible#76687]
### Summary

Hello

when providing multiple module_defaults settings, Ansible seem to merge all of them.

### Issue Type

Bug Report

### Component Name

ansible-core

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = /home/hwerner/Git/internal-helm-charts/hsmsimu/install/ansible.cfg
  configured module search path = ['/home/hwerner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/hwerner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```


### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(ansible.cfg) = ['inventory.yaml']
DEFAULT_VAULT_PASSWORD_FILE(ansible.cfg) = ansible-vault.sh
```


### OS / Environment

N/A

### Steps to Reproduce

I've set up the following module defaults:
```yaml
  module_defaults:
    kubernetes.core.k8s_json_patch:
      kubeconfig: /var/snap/microk8s/current/credentials/client.config
    kubernetes.core.k8s:
      kubeconfig: /var/snap/microk8s/current/credentials/client.config
    kubernetes.core.helm_info:
      binary_path: /snap/bin/microk8s.helm3
    kubernetes.core.helm_repository:
      binary_path: /snap/bin/microk8s.helm3
    kubernetes.core.helm:
      binary_path: /snap/bin/microk8s.helm3
      update_repo_cache: true
```

when executing the task below Ansible fails because it uses the defaults from the helm module:
```yaml
- name: Set the secret
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: secret
        namespace: kube-system
      data:
        mysecret: xxx
```

### Expected Results

success

### Actual Results

```console
{                                                                                                                                                                                    
    "changed": false,                                                                                                                                                                                              
    "invocation": {                                                                                                                                                                                                
        "module_args": {                                                                                                                                                                                           
            "api_key": null,                                                                                                                                                                                       
            "api_version": "v1",                                                                                                                                                                                   
            "append_hash": false,                                                                                                                                                                                  
            "apply": false,                                                                                                                                                                                        
            "binary_path": "/snap/bin/microk8s.helm3",                                                                                                                                                             
            "ca_cert": null,                                                                                                                                                                                       
            "client_cert": null,
            "client_key": null,
            "context": null,
            "continue_on_error": false,
            "delete_options": null,
            "force": false,
            "host": null,
            "kind": null,
            "kubeconfig": null,
            "label_selectors": null,
            "merge_type": null,
            "name": null,
            "namespace": null,
            "password": null,
            "persist_config": null,
            "proxy": null,
            "proxy_headers": null,
            "resource_definition": {
                "apiVersion": "v1",
                "data": {
                    "secret": "xxx"
                },
                "kind": "Secret",
                "metadata": {
                    "name": "secret",
                    "namespace": "kube-system"
                },
                "type": "Opaque"
            },
            "src": null,
            "state": "present",
            "template": null,
            "update_repo_cache": true,
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "msg": "Unsupported parameters for (kubernetes.core.k8s) module: binary_path, update_repo_cache. Supported parameters include: apply, continue_on_error, api_version (api, version), template, name, proxy, validate_certs (verify_ssl), persist_config, resource_definition (definition, inline), kind, client_cert (cert_file), src, label_selectors, append_hash, proxy_headers, state, wait_sleep, client_key (key_file), validate, wait, context, force, ca_cert (ssl_ca_cert), api_key, wait_condition, delete_options, wait_timeout, password, username, kubeconfig, namespace, host, merge_type."
}
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
