### ISSUE TITLE
package_facts overwrites a "package" variable defined in inventory

### ISSUE THREAD

**Issue by Lycowolf** [ansible/ansible#76692]
### Summary

My Ansible setup uses a `package` dict containing a list of packages to install, along with their versions and other info.

Recently, I added a new role that calls `package_facts` and its presence broke the rest of my setup. I tracked the reason to variable `packages` not containing the expected data.

The reason is that `package_facts` overwrites the variable. This is undocumented: it should store data only in `ansible_facts.packages` and possibly  `ansible_packages`. It is also quite unexpected, as Ansible facts are otherwise prefixed.

### Issue Type

Bug Report

### Component Name

package_facts

### Ansible Version

```console
ansible [core 2.11.5] 
  config file = /home/XXX/.ansible.cfg
  configured module search path = ['/home/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/XXX/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/XXX/external/collections
  executable location = /home/XXX/venv/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### Configuration

```console
ANSIBLE_FORCE_COLOR(/home/XXX/.ansible.cfg) = True
ANSIBLE_NOCOWS(/home/XXX/.ansible.cfg) = True
COLLECTIONS_PATHS(/home/XXX/.ansible.cfg) = ['/home/XXX/external/collections']
DEFAULT_FORKS(/home/XXX/.ansible.cfg) = 10
DEFAULT_LOG_PATH(/home/XXX/.ansible.cfg) = /home/XXX/.ansible/ansible.log
DEFAULT_TIMEOUT(/home/XXX/.ansible.cfg) = 30
DISPLAY_ARGS_TO_STDOUT(/home/XXX/.ansible.cfg) = True
HOST_KEY_CHECKING(/home/XXX/.ansible.cfg) = False
VARIABLE_PLUGINS_ENABLED(/home/XXX/.ansible.cfg) = ['host_group_vars', 'community.sops.sops']
```

### OS / Environment

Ubuntu 20.04 LTS

### Steps to Reproduce

hosts.yml:
```yaml (paste below)
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
      packages:
        x: 1
        y: 2
```
play.yml:
```yaml
- hosts: localhost
  tasks:
#    - set_fact:
#        packages: "{{ packages }}"
    - package_facts:
        manager: auto
    - debug:
        msg: "{{ packages | first }}" # the full output is way too long, and also a private info 
```

### Expected Results

The message should read `"msg": "x"` (or `y`). I can get this output by uncommenting the `set_fact`.

### Actual Results

```console
$ ansible-playbook -i hosts.yml play.yml

PLAY [localhost] *******************************************************************

TASK [Gathering Facts gather_subset=['all'], gather_timeout=10] *******************************************************************
ok: [localhost]

TASK [package_facts manager=auto] *******************************************************************
ok: [localhost]

TASK [debug msg={{ packages | first }}] ************************************************************************************
ok: [localhost] => {
    "msg": "accountsservice"
}

PLAY RECAP *****************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
