### ISSUE TITLE
remote_user task override not working

### ISSUE THREAD

**Issue by dupuy** [ansible/ansible#7673]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.2
##### Environment:

Mac OS X 10.9.3 (controller) Ubuntu 12.04 LTS (target)
##### Summary:

As [previously noted](https://groups.google.com/forum/#!topic/ansible-project/pauTpphUCLQ) by several others on the ansible-project Google group, specifying a remote_user in a task has no effect - the play's default remote_user setting (and SSH connection) are used.
##### Steps To Reproduce:

Set up a remote system with `root` and `deploy` users that can be reached by SSH.

Run the following extracted test playbook with `ansible-playbook -k remote_user.yml`

``` yaml

---
- remote_user: root
  hosts: all
  tasks:
  - name: Using default remote_user
    shell: who am i; id
    register: result

  - name: Default remote_user result
    debug: var=result

  - name: Using different remote_user
    remote_user: deploy
    shell: who am i; id
    register: difference

  - name: Different remote_user result
    debug: var=difference
```
##### Expected Results:

I would expect that the debugging output would show the userid for deploy in the stdout/stdout_lines for "difference", but this is not the case.
##### Actual Results:

Instead, I get the following results:

``` console
ansible-playbook -k remote_user.yml -l testing.dupuy.us
SSH password:

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [testing.dupuy.us]

TASK: [Using default remote_user] *********************************************
changed: [testing.dupuy.us]

TASK: [Default remote_user result] ********************************************
ok: [testing.dupuy.us] => {
    "result": {
        "changed": true,
        "cmd": "who am i; id ",
        "delta": "0:00:00.003830",
        "end": "2014-06-05 09:13:08.416824",
        "invocation": {
            "module_args": "who am i; id",
            "module_name": "shell"
        },
        "rc": 0,
        "start": "2014-06-05 09:13:08.412994",
        "stderr": "",
        "stdout": "root     pts/0        2014-06-05 09:13 (212.201.111.66)\nuid=0(root) gid=0(root) groups=0(root)",
        "stdout_lines": [
            "root     pts/0        2014-06-05 09:13 (212.201.111.66)",
            "uid=0(root) gid=0(root) groups=0(root)"
        ]
    }
}

TASK: [Using different remote_user] *******************************************
changed: [testing.dupuy.us]

TASK: [Different remote_user result] ******************************************
ok: [testing.dupuy.us] => {
    "difference": {
        "changed": true,
        "cmd": "who am i; id ",
        "delta": "0:00:00.003966",
        "end": "2014-06-05 09:13:09.066954",
        "invocation": {
            "module_args": "who am i; id",
            "module_name": "shell"
        },
        "rc": 0,
        "start": "2014-06-05 09:13:09.062988",
        "stderr": "",
        "stdout": "root     pts/0        2014-06-05 09:13 (212.201.111.66)\nuid=0(root) gid=0(root) groups=0(root)",
        "stdout_lines": [
            "root     pts/0        2014-06-05 09:13 (212.201.111.66)",
            "uid=0(root) gid=0(root) groups=0(root)"
        ]
    }
}

PLAY RECAP ********************************************************************
testing.dupuy.us           : ok=5    changed=2    unreachable=0    failed=0
```
