### ISSUE TITLE
Add no_log_control option to customize no_log behaviour in playbooks

### ISSUE THREAD

**Issue by jangel97** [ansible/ansible#76775]
### Summary

Hi, 

I currently work developing Ansible playbooks, and I thought that customising `no_log` behaviour could be interesting feature for me as a user (and maybe for other people as well).

My problem is that `no_log` parameter when invoking an Ansible module omits all of the stdout for that module invocation. It would be nice if this behaviour could be customisable so that I can see the stdout of the module invocation but only certain parameters.

My suggestion is to create a `no_log_control` similar to `loop_control` so this way its behaviour can be customisable. (By default the current behaviour would be totally fine). 

I do not see similar feature in docs:
  - https://docs.ansible.com/ansible/devel/reference_appendices/logging.html
  - https://docs.ansible.com/ansible/devel/reference_appendices/faq.html#how-do-i-keep-secret-data-in-my-playbook

The aim of this request is similar to https://github.com/ansible/proposals/issues/109

I am willing to work on this myself if the idea makes sense to contributors and maintainers. I would really like to get started contributing to this awesome project.

### Issue Type

Feature Idea

### Component Name

ansible-core
Probably this is the file to be updated => https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py

### Additional Information

```yaml (paste below)

- name: "kinit in order to do sensitive stuff"
  command: kinit sensitive_sa
  args:
    stdin: "{{ secret }}"
  no_log: True
  no_log_control:
    no_log_vars:
      - secret
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
