### ISSUE TITLE
module group cannot rename group

### ISSUE THREAD

**Issue by azrdev** [ansible/ansible#76774]
### Summary

We create groups from a variable definition like `[ {"name": "admins", "gid": 1234}  ]`. When I change the name of a group in there after the ansible code already ran, I'd expect the `group` module to find the existing group by gid and rename it. Instead, it fails with a message `GID '1234' already exists`. #29919 suggested using the `non_unique` option of the module/groupmod, but that will create a duplicate / a new group using the same GID, which apparently is not supported by most software -- not even the group*/user* tools themselves, because removing the _old_ group name afterwards fails when users exist that have the GID as primary group -- even though the gid would persist (on the other name).

So the request here is to properly support group renames, probably using the `-n, --new-name` option of `groupmod`.
Currently the only working method seems to shell out to it.

### Issue Type

Bug Report

### Component Name

group

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jbiegert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/jbiegert/.ansible/collections:/usr/share/ansible/collections
  executable location = venv/bin/ansible
  python version = 3.9.9 (main, Nov 19 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

control host: Fedora 34 
target host: RHEL 8.1

### Steps to Reproduce

test playbook below.

The first tasks demonstrate that renaming fails, the following demonstrate the damage done by the non_unique option:
```yaml
- hosts: all
  run_once: true
  become: true
  tasks:
    - name: create group
      group:
        name: oldgroupname
        gid: 9999

    - name: create testuser
      user:
        name: testuser-groupname
        group: oldgroupname

    - name: /etc/group content
      command: grep groupname /etc/group

    - name: rename group
      group:
        name: newgroupname
        gid: 9999
      ignore_errors: true  # fails with "GID already in use"

    - name: force rename group
      group:
        name: newgroupname
        gid: 9999
        non_unique: true

    - name: /etc/group content
      command: grep groupname /etc/group

    # should not be necessary under idempotence
    - name: remove old group
      group:
        name: oldgroupname
        state: absent
      ignore_errors: true  # fails due to user having its GID as primary

    - name: manually remove old group
      command: sed -i -e /oldgroupname/d  /etc/group

    - name: /etc/group content
      command: grep groupname /etc/group

```

### Expected Results

The task `rename group` to succeed and rename the group, identified by the GID.

### Actual Results

```console
❯ ANSIBLE_LOAD_CALLBACK_PLUGINS=1 ANSIBLE_STDOUT_CALLBACK=yaml LANG=C.UTF-8 venv/bin/ansible-playbook -i 192.168.122.150, rename-group.yml -v

Using /etc/ansible/ansible.cfg as config file

PLAY [all] **********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
ok: [192.168.122.150]

TASK [create group] *************************************************************************************************************************
changed: [192.168.122.150] => changed=true
  gid: 9999
  name: oldgroupname
  state: present
  system: false

TASK [create testuser] **********************************************************************************************************************
changed: [192.168.122.150] => changed=true
  comment: ''
  create_home: true
  group: 9999
  home: /home/testuser-groupname
  name: testuser-groupname
  shell: /bin/bash
  state: present
  stderr: |-
    useradd: warning: the home directory already exists.
    Not copying any file from skel directory into it.
    Creating mailbox file: File exists
  stderr_lines: <omitted>
  system: false
  uid: 1001

TASK [/etc/group content] *******************************************************************************************************************
changed: [192.168.122.150] => changed=true
  cmd:
  - grep
  - groupname
  - /etc/group
  delta: '0:00:00.002372'
  end: '2022-01-17 11:54:18.544475'
  msg: ''
  rc: 0
  start: '2022-01-17 11:54:18.542103'
  stderr: ''
  stderr_lines: <omitted>
  stdout: 'oldgroupname:x:9999:'
  stdout_lines: <omitted>

TASK [rename group] *************************************************************************************************************************
fatal: [192.168.122.150]: FAILED! => changed=false
  msg: |-
    groupadd: GID '9999' already exists
  name: newgroupname
...ignoring

TASK [force rename group] *******************************************************************************************************************
changed: [192.168.122.150] => changed=true
  gid: 9999
  name: newgroupname
  state: present
  system: false

TASK [/etc/group content] *******************************************************************************************************************
changed: [192.168.122.150] => changed=true
  cmd:
  - grep
  - groupname
  - /etc/group
  delta: '0:00:00.002114'
  end: '2022-01-17 11:54:19.864750'
  msg: ''
  rc: 0
  start: '2022-01-17 11:54:19.862636'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    oldgroupname:x:9999:
    newgroupname:x:9999:
  stdout_lines: <omitted>

TASK [remove old group] *********************************************************************************************************************
fatal: [192.168.122.150]: FAILED! => changed=false
  msg: |-
    groupdel: cannot remove the primary group of user 'testuser-groupname'
  name: oldgroupname
...ignoring

TASK [manually remove old group] ************************************************************************************************************
changed: [192.168.122.150] => changed=true
  cmd:
  - sed
  - -i
  - -e
  - /oldgroupname/d
  - /etc/group
  delta: '0:00:00.002683'
  end: '2022-01-17 11:54:20.562540'
  msg: ''
  rc: 0
  start: '2022-01-17 11:54:20.559857'
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

TASK [/etc/group content] *******************************************************************************************************************
changed: [192.168.122.150] => changed=true
  cmd:
  - grep
  - groupname
  - /etc/group
  delta: '0:00:00.002197'
  end: '2022-01-17 11:54:20.919638'
  msg: ''
  rc: 0
  start: '2022-01-17 11:54:20.917441'
  stderr: ''
  stderr_lines: <omitted>
  stdout: 'newgroupname:x:9999:'
  stdout_lines: <omitted>
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
