### ISSUE TITLE
become_method unable to simulate `sudo`

### ISSUE THREAD

**Issue by naisanzaa** [ansible/ansible#76780]
### Summary

I'm trying to simulate `sudo` in a shell command. 

It needs: 

* to run as current user
* to run with sudo 

ansible command: 
```yaml
    - name: '{{ ARCH }} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      shell: '{{ ARCH }} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      register: shell
      changed_when: "shell.rc != 0"
      become: true
      become_user: "{{ ansible_user_id }}"
      become_method: sudo
```

reference: https://github.com/TheShellLand/antsable/blob/master/playbooks/roles/brew/tasks/MacOSX.yml

equivalent shell command: 
```shell
'sudo {{ ARCH }} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
```

The reason I'm trying to do this is because I want ansible to catch any shell script commands that calls `sudo` internally. 

e.g.

`brew install --cask wireshark` will call for `sudo`

### Issue Type

Bug Report

### Component Name

shell

### Ansible Version

```console
$ ansible --version


ansible [core 2.12.1]
  config file = /Users/eric/Library/CloudStorage/Box-Box/Apple/lab/github/antsable/ansible.cfg
  configured module search path = ['/Users/eric/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/eric/venv/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/eric/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/eric/venv/ansible/bin/ansible
  python version = 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.3
  libyaml = True

```

### Configuration

```console
$ ansible-config dump --only-changed


DEFAULT_STDOUT_CALLBACK(/Users/eric/Library/CloudStorage/Box-Box/Apple/lab/github/antsable/ansible.cfg) = yaml
RETRY_FILES_ENABLED(/Users/eric/Library/CloudStorage/Box-Box/Apple/lab/github/antsable/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/Users/eric/Library/CloudStorage/Box-Box/Apple/lab/github/antsable/ansible.cfg) = /Users/eric/Library/CloudStorage/Box-Box/Apple/lab/github/antsable

```

### OS / Environment

MacOS M1

### Steps to Reproduce

```yaml (paste below)
    - name: '{{ ARCH }} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      shell: '{{ ARCH }} /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
      register: shell
      changed_when: "shell.rc != 0"
      become: true
      become_user: "{{ ansible_user_id }}"
      become_method: sudo
```

### Expected Results

* `become: yes` to elevate
* `become_user` to become current user
* `become_method` to run sudo as current user 

### Actual Results

`https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh` shell script fails with `rc=1`, still asks for `sudo`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
