### ISSUE TITLE
Retrieve Windows Facts over SSH Connection

### ISSUE THREAD

**Issue by lmayorga1980** [ansible/ansible#76813]
### Summary

When I try to run ansible-playbook against a Windows Node using an SSH Connection and the `gather_facts` is set to `yes` I get the following error.

```
  mynode: PLAY [Default Playbook] ********************************************************
    mynode:
    mynode: TASK [Gathering Facts] *********************************************************
    mynode: task path: /Users/myuser/playbooks/playbook.yml:2
    mynode: redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
    mynode: [WARNING]: Error when collecting winrm facts: Get-Item : Cannot find path
    mynode: ok: [default]
    mynode: 'Cert:\LocalMachine\My\88F4DC17569EBCE0D7D05FF99319DA83D3123DCA' because it
    mynode: does not exist.  At line:6 char:25  + ...               Get-Item -LiteralPath
    mynode: Cert:\LocalMachine\My\$($_.Value)  +
    mynode: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo
    mynode: : ObjectNotFound: (Cert:\LocalMach...319DA83D3123DCA:String) [Get-Item],
    mynode: ItemNotFoundException      + FullyQualifiedErrorId :
    mynode: PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand      at
    mynode: <ScriptBlock>, <No file>: line 6  at <ScriptBlock>, <No file>: line 3
    mynode: META: ran handlers
    mynode:
```

### Issue Type

Bug Report

### Component Name

gather_facts

### Ansible Version

```console
ansible [core 2.12.1]
  config file = None
  configured module search path = ['/Users/luisma/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.2.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/luisma/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:20:29) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
```

### OS / Environment

OSX

### Steps to Reproduce

```yaml (paste below)
---
- name: Default Playbook
  hosts: default
  gather_facts: yes
   tasks:
    - name: Deploy Role
      role:
        name: "anyrole"

```

### Expected Results

Ansible should gather facts over a windows ssh connection.

### Actual Results

```console
mynode: PLAY [Default Playbook] ********************************************************
    mynode:
    mynode: TASK [Gathering Facts] *********************************************************
    mynode: task path: /Users/myuser/playbooks/playbook.yml:2
    mynode: redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
    mynode: [WARNING]: Error when collecting winrm facts: Get-Item : Cannot find path
    mynode: ok: [default]
    mynode: 'Cert:\LocalMachine\My\88F4DC17569EBCE0D7D05FF99319DA83D3123DCA' because it
    mynode: does not exist.  At line:6 char:25  + ...               Get-Item -LiteralPath
    mynode: Cert:\LocalMachine\My\$($_.Value)  +
    mynode: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      + CategoryInfo
    mynode: : ObjectNotFound: (Cert:\LocalMach...319DA83D3123DCA:String) [Get-Item],
    mynode: ItemNotFoundException      + FullyQualifiedErrorId :
    mynode: PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand      at
    mynode: <ScriptBlock>, <No file>: line 6  at <ScriptBlock>, <No file>: line 3
    mynode: META: ran handlers
    mynode:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
