### ISSUE TITLE
ansible.posix.acl states that recursive is not supported on FreeBSD

### ISSUE THREAD

**Issue by hizzyfit** [ansible/ansible#76811]
### Summary

Tried to run a task which sets acls recursivly but they fail with: "recursive is not supported on that platform."

A couple of years ago the recursive flag for setfacl on FreeBSD was indeed missing.
However it seems to be fixed since 2018 according to:

https://reviews.freebsd.org/rS332396

### Issue Type

Bug Report

### Component Name

ansible.posix.acl

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.1]
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Nov  6 2021, 01:10:35) [Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c
  jinja version = 3.0.3
  libyaml = False
```

### Configuration

```console
$ ansible-config dump --only-changed
HOST_KEY_CHECKING(/usr/local/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/usr/local/etc/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

FreeBSD 13.0-RELEASE-p5

### Steps to Reproduce

```yaml (paste below)

- name: Set ACLs (recursive)
  ansible.posix.acl:
    path: "{{ librenms_install_path }}/{{ item }}"
    etype: group
    permissions: rwx
    recursive: yes
    state: present
  with_items:
    - rrd
    - logs

```

### Expected Results

I expected it to look something like this when I run the playbook:

changed: [b-test-1] => (item=rrd)
changed: [b-test-1] => (item=logs)

### Actual Results

```console
failed: [b-test-1] (item=rrd) => {"ansible_loop_var": "item", "changed": false, "item": "rrd", "msg": "recursive is not supported on that platform."}
failed: [b-test-1] (item=logs) => {"ansible_loop_var": "item", "changed": false, "item": "logs", "msg": "recursive is not supported on that platform."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
