### ISSUE TITLE
[blockinfile]: multiple blocks get generated, if you add "\n" to marker

### ISSUE THREAD

**Issue by Xztty** [ansible/ansible#76823]
### Summary

we config the domain info with the `/etc/hosts` file, we monitor our service and change the domain with bash script like this:
```
ansible 127.0.0.1 -m blockinfile -a "block='192.168.1.1 test.company.com' marker='# {mark} : test block' path=/etc/hosts"
```
BUT , occasionally the file `/etc/hosts` contains multiple block. I expected that there should be only one block.

I have read the source code `lib/ansible/modules/files/blockinfile.py` and find nothing suspicious.

### Issue Type
~Bug  Report~
- Docs Report

### Component Name

blockinfile

### Ansible Version

```console
$ ansible --version
ansible 2.7.5.post0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Configuration

```console
$ ansible-config dump --only-changed
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

CentOS-7.6

### Steps to Reproduce

```yaml (paste below)
ansible 127.0.0.1 -m blockinfile -a "block='192.168.1.1 test.company.com' marker='# {mark} : test block' path=/etc/hosts"
```

### Expected Results

```console
# BEGIN : test block
192.168.1.1 test.company.com
# END : test block
```

### Actual Results

```console
# BEGIN : test block
192.168.1.1 test.company.com
# END : test block
# BEGIN : test block
192.168.1.2 test.company.com
# END : test block
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/blockinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/blockinfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
I cannot reproduce, my first run inserts the data:
```
127.0.0.1 | CHANGED => {
    "changed": true,
    "msg": "Block inserted"
}
#> cat /etc/hosts
# BEGIN : test block
192.168.1.1 test.company.com
# END : test block
```
The 2nd run does nothing:
```
127.0.0.1 | SUCCESS => {
    "changed": false,
    "msg": ""
}
#> cat /etc/hosts
# BEGIN : test block
192.168.1.1 test.company.com
# END : test block
```

**Comment by bcoca** [comment]
If I change the IP or hostname, I get a change, but not a 2nd section, the only time that happens is if I change the marker

**Comment by Xztty** [comment]
> If I change the IP or hostname, I get a change, but not a 2nd section, the only time that happens is if I change the marker

Yes, I have got the same result as you with manual test and our test environment. 

But the exception of `2nd section`  had occured at some of customers who purchased our product.

**Comment by bcoca** [comment]
i cannot really help without an actual reproducer

needs_info

**Comment by sivel** [comment]
The only thing I can figure, is potentially that there was no trailing newline at the end of the end marker inserted into the file.  This could have potentially been done by a user manually after the first insertion.

The marker logic does a comparison that requires a newline to be present.

This playbooks showcases this behavior:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - file:
        path: '{{ playbook_dir }}/hosts'
        state: absent
    - blockinfile:
        block: '192.168.1.1 test.company.com'
        marker: '# {mark} : test block'
        path: '{{ playbook_dir }}/hosts'
        create: true
    - replace:
        path: '{{ playbook_dir }}/hosts'
        regexp: '\n'
        after: '# END : test block'
        replace: ''
    - blockinfile:
        block: '192.168.1.1 test.company.com'
        marker: '# {mark} : test block'
        path: '{{ playbook_dir }}/hosts'
```

That results in:

```
# BEGIN : test block
192.168.1.1 test.company.com
# END : test block
# BEGIN : test block
192.168.1.1 test.company.com
# END : test block
```

Removing the `replace` task, produces only 1 inserted entry.
