### ISSUE TITLE
vmware_guest error: Unable to access the virtual machine configuration: Unable to access file

### ISSUE THREAD

**Issue by 71Imapla** [ansible/ansible#76851]
### Summary

# When attempting to provision a new vmware VM using the vmware_guest module to VSAN storage, I am getting the following error: 

 msg": "Failed to create a virtual machine : Unable to access the virtual machine configuration: Unable to access file [some_other_non_vsan_storage_cluster_not_connected_to_ESXI_Cluster] Linux_Base_Template/Linux_Base_Template.vmtx".

#### Invocation

```
  "invocation": {
    "module_args": {
      "name": "TMPBLDLNXLL0001",
      "hostname": "vCenterServer",
      "username": "XXXXXXXXXX",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "annotation": "Test VSAN provisioning",
      "template": "Linux-8_Base_Template",
      "datacenter": "devnulldc",
      "folder": "devnulldc/vm/Sandbox",
      "cluster": "CL-03",
      "disk": [
        {
          "size_gb": 50,
          "type": "thin",
          "datastore": "['vSAN']",
          "autoselect_datastore": null,
          "controller_number": null,
          "controller_type": null,
          "disk_mode": null,
          "filename": null,
          "size": null,
          "size_kb": null,
          "size_mb": null,
          "size_tb": null,
          "unit_number": null
        }
      ],
      "hardware": {
        "num_cpus": 2,
        "memory_mb": 4096,
        "num_cpu_cores_per_socket": 2,
        "hotadd_cpu": false,
        "hotremove_cpu": false,
        "hotadd_memory": false,
        "nested_virt": false,
        "scsi": "paravirtual",
        "boot_firmware": null,
        "cpu_limit": null,
        "cpu_reservation": null,
        "max_connections": null,
        "mem_limit": null,
        "mem_reservation": null,
        "memory_reservation_lock": null,
        "secure_boot": null,
        "version": null,
        "virt_based_security": null,
        "iommu": null
      },
      "networks": [
        {
          "name": "BlackholeNet",
          "type": "static",
          "ip": "987.65.43.21",
          "netmask": "255.255.255.0",
          "gateway": "987.65.43.1",
          "device_type": "vmxnet3",
          "dvswitch_name": "vDSwitch",
          "start_connected": true
        }

*** Truncated ***

```
#### Code:

```
- name: Clone Virtual Machine(s) from Template
  vmware_guest:
    name: "{{ item | upper }}"
    hostname: "{{ provision_vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_user_pswd }}"
    annotation: "{{ provision_notes }}"
    template: "{{ vmtemplate }}"
    datacenter: "{{ provision_vc_datacenter }}"
    #    datastore:  "{{ provisioning_datastore | string }}"
    folder: "{{ ansible_facts.vmfolder }}"
    cluster: "{{ provision_cluster_target }}"
    disk:
    - size_gb: 50
      type: thin
      datastore:  "{{ provisioning_datastore | string }}"
    hardware:
      num_cpus: "{{ provision_virtual_cpu }}"
      memory_mb:  "{{ vmmemgb }}"
      num_cpu_cores_per_socket: "{{ provision_virtual_cpu }}"
      hotadd_cpu: False
      hotremove_cpu: False
      hotadd_memory: False
      nested_virt: False
      scsi: 'paravirtual'
    networks:
    - name: "{{ network_zone }}"
      type: "static"
      ip: "{{ provision_ip_address }}"
      netmask: "{{ subnet_mask }}"
      gateway: "{{ default_gw }}"
      device_type: 'vmxnet3'
      dvswitch_name: "{{ vcenter_dvswitch }}"
      start_connected: True
    wait_for_ip_address: yes
    wait_for_customization: yes
    customization:
      domain: "{{ provisioning_ad_domain | lower }}"
      dns_servers: 987.65.43.60
      dns_suffix:
        - devnull.blackhole.com
    cdrom:
      type: 'none'
    force: yes
  with_items:
    - "{{ clone }}"
  delegate_to: "localhost"
  register: nice_n_toasty_baked_vm

*** Truncated ****

```

Same issue documented in issue:  28649 --- I have attempted the fix that is documented there by added a disk section ( see above ) with the datastore variable ( we have many datastores ).  The templates live on a separate storage system *NOT* connected to ESXi Clusters that are configured for VSAN.  

* This works perfectly by manually cloning via vCenter to the target ESXi Cluster.  
*  This works perfectly if I am provisioning to ESXi clusters that have the "[some_other_non_vsan_storage_cluster_not_connected_to_ESXI_Cluster] " connected to it.
* This works perfectly by executing vmware powercli NEW-VM command here is the code for that:

https://thesleepyadmins.com/2018/09/08/deploy-multiple-vms-using-powercli-and-vmware-template

### Issue Type

Bug Report

### Component Name

vmware_guest

### Ansible Version

```console
$ ansible --version

AWX version: 19.5.0
Ansible Version: core 2.11.6
Python VersionL 3.8.6
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

AWX Operator version 0.15
K8 OS: Ubuntu 20.04 LTS
OS to be Provisioned:  Linux or Windows 

### Steps to Reproduce

```yaml (paste below)

- name: Clone Virtual Machine(s) from Template
  vmware_guest:
    name: "{{ item | upper }}"
    hostname: "{{ provision_vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_user_pswd }}"
    annotation: "{{ provision_notes }}"
    template: "{{ vmtemplate }}"
    datacenter: "{{ provision_vc_datacenter }}"
    #    datastore:  "{{ provisioning_datastore | string }}"
    folder: "{{ ansible_facts.vmfolder }}"
    cluster: "{{ provision_cluster_target }}"
    disk:
    - size_gb: 50
      type: thin
      datastore:  "{{ provisioning_datastore | string }}"
    hardware:
      num_cpus: "{{ provision_virtual_cpu }}"
      memory_mb:  "{{ vmmemgb }}"
      num_cpu_cores_per_socket: "{{ provision_virtual_cpu }}"
      hotadd_cpu: False
      hotremove_cpu: False
      hotadd_memory: False
      nested_virt: False
      scsi: 'paravirtual'
    networks:
    - name: "{{ network_zone }}"
      type: "static"
      ip: "{{ provision_ip_address }}"
      netmask: "{{ subnet_mask }}"
      gateway: "{{ default_gw }}"
      device_type: 'vmxnet3'
      dvswitch_name: "{{ vcenter_dvswitch }}"
      start_connected: True
    wait_for_ip_address: yes
    wait_for_customization: yes
    customization:
      domain: "{{ provisioning_ad_domain | lower }}"
      dns_servers: 987.65.43.60
      dns_suffix:
        - devnull.blackhole.com
    cdrom:
      type: 'none'
    force: yes
  with_items:
    - "{{ clone }}"
  delegate_to: "localhost"
  register: nice_n_toasty_baked_vm

*** Truncated ****


```

### Expected Results

Provisioning from Storage that is *NOT* attached to VSAN configured ESXi Cluster is successful.

### Actual Results

```console
msg": "Failed to create a virtual machine : Unable to access the virtual machine configuration: Unable to access file [some_other_non_vsan_storage_cluster_not_connected_to_ESXI_Cluster] Linux_Base_Template/Linux_Base_Template.vmtx".

  "invocation": {
    "module_args": {
      "name": "TMPBLDLNXLL0001",
      "hostname": "vCenterServer",
      "username": "XXXXXXXXXX",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "annotation": "Test VSAN provisioning",
      "template": "Linux-8_Base_Template",
      "datacenter": "devnulldc",
      "folder": "devnulldc/vm/Sandbox",
      "cluster": "CL-03",
      "disk": [
        {
          "size_gb": 50,
          "type": "thin",
          "datastore": "['vSAN']",
          "autoselect_datastore": null,
          "controller_number": null,
          "controller_type": null,
          "disk_mode": null,
          "filename": null,
          "size": null,
          "size_kb": null,
          "size_mb": null,
          "size_tb": null,
          "unit_number": null
        }
      ],
      "hardware": {
        "num_cpus": 2,
        "memory_mb": 4096,
        "num_cpu_cores_per_socket": 2,
        "hotadd_cpu": false,
        "hotremove_cpu": false,
        "hotadd_memory": false,
        "nested_virt": false,
        "scsi": "paravirtual",
        "boot_firmware": null,
        "cpu_limit": null,
        "cpu_reservation": null,
        "max_connections": null,
        "mem_limit": null,
        "mem_reservation": null,
        "memory_reservation_lock": null,
        "secure_boot": null,
        "version": null,
        "virt_based_security": null,
        "iommu": null
      },
      "networks": [
        {
          "name": "BlackholeNet",
          "type": "static",
          "ip": "987.65.43.21",
          "netmask": "255.255.255.0",
          "gateway": "987.65.43.1",
          "device_type": "vmxnet3",
          "dvswitch_name": "vDSwitch",
          "start_connected": true
        }

*** Truncated ***


#### Code:

```
- name: Clone Virtual Machine(s) from Template
  vmware_guest:
    name: "{{ item | upper }}"
    hostname: "{{ provision_vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_user_pswd }}"
    annotation: "{{ provision_notes }}"
    template: "{{ vmtemplate }}"
    datacenter: "{{ provision_vc_datacenter }}"
    #    datastore:  "{{ provisioning_datastore | string }}"
    folder: "{{ ansible_facts.vmfolder }}"
    cluster: "{{ provision_cluster_target }}"
    disk:
    - size_gb: 50
      type: thin
      datastore:  "{{ provisioning_datastore | string }}"
    hardware:
      num_cpus: "{{ provision_virtual_cpu }}"
      memory_mb:  "{{ vmmemgb }}"
      num_cpu_cores_per_socket: "{{ provision_virtual_cpu }}"
      hotadd_cpu: False
      hotremove_cpu: False
      hotadd_memory: False
      nested_virt: False
      scsi: 'paravirtual'
    networks:
    - name: "{{ network_zone }}"
      type: "static"
      ip: "{{ provision_ip_address }}"
      netmask: "{{ subnet_mask }}"
      gateway: "{{ default_gw }}"
      device_type: 'vmxnet3'
      dvswitch_name: "{{ vcenter_dvswitch }}"
      start_connected: True
    wait_for_ip_address: yes
    wait_for_customization: yes
    customization:
      domain: "{{ provisioning_ad_domain | lower }}"
      dns_servers: 987.65.43.60
      dns_suffix:
        - devnull.blackhole.com
    cdrom:
      type: 'none'
    force: yes
  with_items:
    - "{{ clone }}"
  delegate_to: "localhost"
  register: nice_n_toasty_baked_vm

*** Truncated ****
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
