### ISSUE TITLE
password_hash inconsistency

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#76863]
### Summary

The filter `password_hash` produces different results depending on whether `passlib` is installed or not.

Without `passlib`:
```
{{"hello world"|password_hash("sha256", "mysalt")}}
# $5$mysalt$ncw1Kn3P8zDlbcLu/7Tn6W3yyOk1jKaW1/PoMJVooP5

{{"hello world"|password_hash("sha256", "mysalt", rounds=5000)}}
# $5$rounds=5000$mysalt$ncw1Kn3P8zDlbcLu/7Tn6W3yyOk1jKaW1/PoMJVooP5
```

With `passlib`:
```
{{"hello world"|password_hash("sha256", "mysalt")}}
# $5$rounds=535000$mysalt$HelubZR3XJZRX9KCUKy7z6RggBuxqLGuAUdYM5u0Fl0

{{"hello world"|password_hash("sha256", "mysalt", rounds=5000)}}
# $5$mysalt$ncw1Kn3P8zDlbcLu/7Tn6W3yyOk1jKaW1/PoMJVooP
```
Funny enough, without specifying the amount of rounds, I get different defaults on different machines (535000 on this machine, 656000 on another one).

So to get matching hashes we'll have to use `crypt`'s default rounds of 5000. Alas, the generated strings differ by `$rounds=...`.

This is a problem for idempotency, for example:
```yaml
---
- user:
    name: myuser
    pass: '{{"%s"|format(mypassword)|password_hash("sha512", "mysalt")}}'
```
The only way I see to get idempotency is to specify `rounds` to be neither `crypt`'s nor `passlib`'s default:
```yaml
---
- user:
    name: myuser
    pass: '{{"%s"|format(mypassword)|password_hash("sha512", "mysalt", rounds=5001)}}'
```
This is not a bug. It's just the way different implementations behave. I just think it's worth mentioning in the documentation.

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/playbooks_filters.rst

### Ansible Version

```console
$ ansible --version
2.12.1
```

### Configuration

```console
$ ansible-config dump --only-changed
n/a
```

### OS / Environment

all

### Additional Information

n/a

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/rst/user_guide/playbooks_filters.rst`](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/playbooks_filters.rst)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by 1515236544hit** [comment]
cans somebody ellobrate me about what is the  issue ; please.

**Comment by philfry** [comment]
in short:
A and B are both running the following task on machine Y:
```yaml
- user:
    name: root
    pass:  '{{"%s"|format(mypassword)|password_hash("sha512", "mysalt")}}'
  vars:
    mypassword: "hello world"
```
A's controller node has `passlib` installed, B's controller node doesn't.
The resulting strings that are fed to `pass` are:
A: `$6$rounds=656000$mysalt$x3gMNX73nojM9y9hWr5ckodN33x8bzRKbXFqK7gR2BXTm3sLkD2YSKsuYm6t8BTD03.TD962Q3P9VN9Mc0txP0`
B: `$6$mysalt$F9ZQHXz7HpQuF5Gu7sX6PCWJlyYdojKmIdmXAkBObFOJCtnTswlgwpMJmlLkFuzceF7BfPW7KIwoq2kW2IBVt/`
=> no idempotency. A overwrites B's run, B overwrites A's run.
