### ISSUE TITLE
apt_repository add [signed-by] options

### ISSUE THREAD

**Issue by micah** [ansible/ansible#76865]
### Summary

The apt_repository method does not recognize '[signed-by]' optional apt source list elements.
```

This is a valid repository setting, in fact the Tor Project website [recommends this mechanism](https://support.torproject.org/apt/tor-deb-repo/).

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = /home/micah/dev/float/env/test-local/ansible.cfg
  configured module search path = ['/home/micah/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /home/micah/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

### Configuration

```console
$ ansible-config dump --only-changed

Unrelated
```

### OS / Environment

Debian Bullseye

### Steps to Reproduce

```yaml (paste below)
- name: Install Tor apt repository
  apt_repository:
    repo: "[signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] deb http://deb.torproject.org/torproject.org bullseye main"
    state: present
```

### Expected Results

I expected an apt source to be added with the option specified, such as:

```
   deb     [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org bullseye main
```

### Actual Results

```console
fatal: [vagrant]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Invalid repository string: [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] deb http://deb.torproject.org/torproject.org bullseye main"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
