### ISSUE TITLE
Using ignore_unreachable should not increase the unreachable stat counter

### ISSUE THREAD

**Issue by Anderen2** [ansible/ansible#76895]
### Summary

When using ignore_unreachable on a task, the summary stat-counter for the play still increases by one. This causes issues for callback plugins depending on the stats for reporting how the play went. 

We use ignore_unreachable and some retries on the first task (in this case gather_facts) for all Windows hosts as they have the tendency of not being 100% operative even if they respond on WinRM (making wait_for_connection go OK even if the host is not actually ready).  This works for running the rest of the play, however the run is still marked as a failure in our reporting due to the resulting stats given to the callback plugins denotes the host with "unreachable=1". 

We've tried using clear_host_errors to clear the host stats as well, but it seems like this have no effect on the unreachable stat counter. 

### Issue Type

Bug Report

### Component Name

core/executor/stats

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks', 'json_file_log']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 2
```

### OS / Environment

RHEL 8

### main.yml (tasks from role)
```yaml (paste below)
  - name: wait for system to become reachable
    wait_for_connection:
      timeout: 870

  - name: gather_facts
    setup:
    register: gather_facts_result
    until: gather_facts_result is not failed
    ignore_unreachable: true
    retries: 3

  - name: check fail
    when: gather_facts_result.unreachable is defined
    include_tasks: windows_facts_retry.yml
    
  - name: next_task
    ...
```

### windows_facts_retry.yml
```yaml (paste below)
---
- name: Retry facts gathering due to Windows
  block:
  - name: Increment the retry count
    set_fact:
      retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

  - name: Sleeping for 10 seconds before retrying
    pause:
     seconds: 10

  - meta: clear_host_errors

  - name: gather_facts
    setup:
    register: gather_facts_result
    until: gather_facts_result is not failed
    ignore_unreachable: true

  - name: check unreachable # This is required to convert the unreachable fatal to a fail that may be caught. 
    fail:
      msg: Host unreachable.
    when: gather_facts_result.unreachable is defined

  rescue:
    - fail:
        msg: Maximum amount of retries reached
      when: retry_count | int == 5

    - debug:
        msg: "gather_facts failed, retrying.."

    - include_tasks: windows_facts_retry.yml
```

### Expected Results

The ignore_unreachable flag should not increase the unreachable / "dark" stat counter, and/or clear_host_errors should reset it to 0. 

### Actual Results

```console
TASK [test-role : wait for system to become reachable] *********************
ok: [testhost]

TASK [test-role : gather_facts] ********************************************
fatal: [testhost]: UNREACHABLE! => {"changed": false, "msg": "certificate: Class not registered (extended fault data: {'transport_message': 'Bad HTTP response returned from server. Code 500', 'http_status_code': 500, 'wsmanfault_code': 'XXXXXX', 'fault_code': 's:Receiver', 'fault_subcode': 'w:InternalError'})", "skip_reason": "Host testhost is unreachable", "unreachable": true}

TASK [test-role : check fail] **********************************************
included: /tasks/windows_facts_retry.yml for testhost

TASK [test-role : Increment the retry count] *******************************
ok: [testhost]

TASK [test-role : Sleeping for 10 seconds before retrying] *****************
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [testhost]

TASK [test-role : gather_facts] ********************************************
ok: [testhost]

TASK [test-role : check unreachable] ***************************************
skipping: [testhost]

TASK [test-role : next_task] ***
ok: [testhost]

...

PLAY RECAP *********************************************************************
testhost : ok=13 changed=3 unreachable=1 failed=0 skipped=42 rescued=0 ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
