### ISSUE TITLE
raw module doesn't support environment: dict

### ISSUE THREAD

**Issue by dch** [ansible/ansible#7692]
The raw module does not appear to respect environment: dict settings, e.g. minimal play:

``` yaml
# bootstraps FreeBSD 10 to respect ansible's authority

---
- hosts: bootstrap
  user: root
  gather_facts: no
  tasks:
    - raw: /usr/sbin/pkg -N
      register: pkg
      ignore_errors: True
    - raw: /usr/sbin/pkg bootstrap -f
      environment:
        ASSUME_ALWAYS_YES: 1
      when: pkg|failed
```

Using `env` instead of the `pkg` command shows that ASSUME_ALWAYS_YES is not visible.

FWIW a simple work-around in this case was:

``` yaml
    - raw: env ASSUME_ALWAYS_YES=1 /usr/sbin/pkg bootstrap -f -y
      when: pkg|failed
```

Either this could be documented (I can do this) or the modules should play well together.
