### ISSUE TITLE
win_scheduled_task trigger "type: monthly" key not recognized

### ISSUE THREAD

**Issue by Mixer9** [ansible/ansible#76925]
### Summary

When I am attempting to schedule a monthly task the trigger key "type: monthly" is not recognized as valid.  Fails with error:

fatal: [hostname]: FAILED! => {"changed": false, "msg": "a trigger entry must contain a key 'type' with a value of 'event', 'time', 'daily', 'weekly', 'monthly', 'monthlydow', 'idle', 'registration', 'boot', 'logon', 'session_state_change'"}

### Issue Type

Bug Report

### Component Name

win_scheduled_task

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /home/v683653/.ansible.cfg
  configured module search path = [u'/home/v683653/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/v683653/.ansible.cfg) = [u'/home/userid/development/ops/inventory/hosts.inv']
DEFAULT_TIMEOUT(/home/userid/.ansible.cfg) = 120
HOST_KEY_CHECKING(/home/userid/.ansible.cfg) = False
```

### OS / Environment

Source OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Target OS: Windows Server R2

### Steps to Reproduce

```
- name: scheduled monthly task for UDA agent
      win_scheduled_task:
        name: UDA monthly scan
        actions:
        - path: C:\sim\GSOC-Mscanner-Win-x64.exe
        triggers:
        - type: monthly
        - days_of_month: 1
        username: SYSTEM
        state: present
        enabled: yes
```

### Expected Results

I expected the scheduled task to be scheduled to run monthly for the executable listed.  I have 'monthly' in the 'type' key but the error reads like I don't even have the 'type' key coded.

### Actual Results

```console
TASK [scheduled monthly task for UDA agent] *************************************************************************************************************************************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "msg": "a trigger entry must contain a key 'type' with a value of 'event', 'time', 'daily', 'weekly', 'monthly', 'monthlydow', 'idle', 'registration', 'boot', 'logon', 'session_state_change'"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by jborean93** [comment]
Without testing I believe this is the issue:

```yaml
triggers:
- type: monthly
- days_of_month: 1
```

You are creating a list with 2 dicts, in JSON this looks like

```json
"trigger": [
    { "type": "monthly" },
    { "days_of_month": 1 }
]
```

What you want is a single dict with multiple keys which in YAML is expressed like

```yaml
triggers:
- type: monthly
  days_of_month: 1
```

Note how it's still a list due to the leading `-` for each entry but the keys of each entry are just aligned to the same indentation. If you wanted multiple triggers it would look like

```yaml
triggers:
- type: monthly
  days_of_month: 1
- type: daily
  start_boundary: ...
```

Hopefully this helps.
