### ISSUE TITLE
ansible.builtin.sysvinit does not start custom init script

### ISSUE THREAD

**Issue by geoffreyvanwyk** [ansible/ansible#76935]
### Summary

On Ubuntu 20.04 in Windows Subsystem for Linux, I create an init script for Mailhog in /etc/init.d/mailhog in one task, then enable it in another task with update-rc.d, but ansible.builtin.sysvinit does not start it in a subsequent task, even though the result of that task is "ok".

I can manually start Mailhog successfully with `sudo service mailhog start` and ansible.builtin.sysvinit successfully starts other services like apache2.

### Issue Type

Bug Report

### Component Name

ansible.builtin.sysvinit

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/scholar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/scholar/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
<Not output>
```

### OS / Environment

Windows 10, Windows Subsystem for Linux, Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
---
- name: --MailHog-- Installed?
  ansible.builtin.stat:
    path: /home/scholar/go/bin/MailHog
  register: mailhog_command

- name: --MailHog-- Install
  when: not mailhog_command.stat.exists
  ansible.builtin.command: go get github.com/mailhog/MailHog

- name: --MailHog--Service--Logs Directory-- Create
  become: yes
  ansible.builtin.file:
    path: /var/log/mailhog
    state: directory
    mode: u+rwx,g+rx,o+rx

- name: --MailHog--Service--Script-- Copy
  become: yes
  ansible.builtin.copy:
    src: ../../../resources/init.d/mailhog
    dest: /etc/init.d/mailhog
    mode: u+rwx,g+rx,o+rx
  register: mailhog_service_script

- name: --MailHog--Service--Script-- Activate  # noqa no-handler
  when: mailhog_service_script.changed
  become: yes
  ansible.builtin.command: update-rc.d mailhog defaults

- name: --MailHog--Service-- Start
  become: yes
  ansible.builtin.sysvinit:
    name: mailhog
    state: started
```

### Expected Results

After running the playbook in which the above tasks are included, then going to the target machine and running:

```
sudo service mailhog status
```

I expect the output to say: "Mailhog is running".

### Actual Results

```console
After running the playbook in which the above tasks are included, then going to the target machine and running:


sudo service mailhog status
```

The output says: "Mailhog is not running".
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
