### ISSUE TITLE
Ansible playbook with "replace" and "after" marching lines that are not directly after

### ISSUE THREAD

**Issue by pedrosk** [ansible/ansible#76957]
### Summary

Not quite sure if this is a bug, the issue between the chair and keyboard or misinterpretation of documentation

Here is a short description

A simple playbook code intended to update dhcpcd

```
---

#tasks:
- name: Set ES heap min
  hosts: local
#  ansible.builtin.replace:
  tasks:
    - name: test task
      replace:
  #         dest: "/home/pedro/ansible_test/test.conf"
        path: /home/pedro/ansible_test/test.conf
        after: 'interface eth0'
        regexp: '^static ip_address=[0-9 ]*\.[0-9 ]*\.[0-9 ]*\.[0-9 ]*\/[0-9 ]*'
        replace: "static ip_address={{ ip_address }}/24"
        backup: yes

``` 

The idea is to update an IP of a particular interface (in this case eth0)
 (note my regex needs improvement but has no effect on what is happening)

So it work OK  as log as the other interface is commented out, else it will update the line ``` static ip_address= ``` in all interfaces that as not commented out.

test file:
```
# Example static IP configuration:
interface eth0
static ip_address=192.168.1.390/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.1.1
static domain_name_servers=192.168.1.1 #8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
#static ip_address=192.168.1.30/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

```

If like above than profile eth0 will be not touched which is desired. However if the line ``` #static ip_address=192.168.1.30/2 ``` would be commented this line would be also modified, which is undesired.

Looking at the documentation [enter link description here][1] one gets the idea that the line that has "interface eth0" will be identified and ONLY the line with the matching regex will be modified, but that does not seem to be true.

example of result after running with UNcommented line:
```

# Example static IP configuration:
interface eth0
static ip_address=192.168.1.390/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.1.1
static domain_name_servers=192.168.1.1 #8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
static ip_address=192.168.1.390/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

``` 

Am I doing something wrong, or am I misinterpreting the documentation, or is this not intended to work as I described, is there a bug ? 

Please help me understand

I am running Ansible 1.9 with python 3.8:
```
ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pedro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

  [1]: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html#parameter-after

### Issue Type

Bug Report

### Component Name

replace with after

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pedro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed

DEFAULT_HOST_LIST(/home/pedro/my_ansible/ansible.cfg) = ['/home/pedro/my_ansible/dev']

cat /home/pedro/my_ansible/ansible.cfg
[defaults]
inventory=./dev
```

### OS / Environment

cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.1"
VERSION_ID="20.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyssa
UBUNTU_CODENAME=focal

 uname -a
Linux radzim 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```
#tasks:
- name: Set ES heap min
  hosts: local
#  ansible.builtin.replace:
  tasks:
    - name: test task
      replace:
  #         dest: "/home/pedro/ansible_test/test.conf"
        path: /home/pedro/ansible_test/test.conf
        after: 'interface eth0'
        regexp: '^static ip_address=[0-9 ]*\.[0-9 ]*\.[0-9 ]*\.[0-9 ]*\/[0-9 ]*'
        replace: "static ip_address={{ ip_address }}/24"
        backup: yes

```

test file:

```
# Example static IP configuration:
interface eth0
static ip_address=192.168.1.390/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.1.1
static domain_name_servers=192.168.1.1 #8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
static ip_address=192.168.1.30/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

```

### Expected Results

```
# Example static IP configuration:
interface eth0
static ip_address=192.168.1.390/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.1.1
static domain_name_servers=192.168.1.1 #8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
static ip_address=192.168.1.30/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

```

### Actual Results

```console
# Example static IP configuration:
interface eth0
static ip_address=192.168.1.390/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.1.1
static domain_name_servers=192.168.1.1 #8.8.8.8 fd51:42f8:caae:d92e::1

# It is possible to fall back to a static IP if DHCP fails:
# define static profile
#profile static_eth0
static ip_address=192.168.1.390/24
#static routers=192.168.1.1
#static domain_name_servers=192.168.1.1

# fallback to static profile on eth0
#interface eth0
#fallback static_eth0

```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
