### ISSUE TITLE
Group vars not loaded for collections playbook

### ISSUE THREAD

**Issue by p53** [ansible/ansible#76983]
### Summary

Seems like collection playbook does not receive group vars

### Issue Type

Bug Report

### Component Name

collection playbook

### Ansible Version

```console
$ ansible --version
`ansible [core 2.12.1]
  config file = /Users/pavol.ipoth/Software/luna-bm-installer-ansible/ansible.cfg
  configured module search path = ['/Users/pavol.ipoth/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pavol.ipoth/Library/Caches/pypoetry/virtualenvs/tools-env-BuUPe0V_-py3.10/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/pavol.ipoth/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pavol.ipoth/Library/Caches/pypoetry/virtualenvs/tools-env-BuUPe0V_-py3.10/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 23:19:43) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.3
  libyaml = False`
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/Users/someuser/Software/somerepo/ansible.cfg) = True
CACHE_PLUGIN(/Users/someuser/Software/somerepo/ansible.cfg) = jsonfile
CACHE_PLUGIN_TIMEOUT(/Users/someuser/Software/somerepo/ansible.cfg) = 3600
CALLBACKS_ENABLED(/Users/someuser/Software/somerepo/ansible.cfg) = ['profile_roles', 'profile_tasks', 'timer']
DEFAULT_EXECUTABLE(/Users/someuser/Software/somerepo/ansible.cfg) = /bin/bash
DEFAULT_GATHERING(/Users/someuser/Software/somerepo/ansible.cfg) = smart
DEFAULT_TIMEOUT(/Users/someuser/Software/somerepo/ansible.cfg) = 30
HOST_KEY_CHECKING(/Users/someuser/Software/somerepo/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/Users/someuser/Software/somerepo/ansible.cfg) = 300
PERSISTENT_CONNECT_TIMEOUT(/Users/someuser/Software/somerepo/ansible.cfg) = 300
```

### OS / Environment

MacOSX

### Steps to Reproduce

I had playbook site.yaml without collections:

```
- ansible.builtin.import_playbook: install.yaml
  tags:
    - install

- ansible.builtin.import_playbook: upgrade.yaml
  tags:
    - upgrade

- ansible.builtin.import_playbook: uninstall.yaml
  tags:
    - uninstall
```

Running it, works without problem:

```ansible-playbook -i inventories/dev.yaml --ask-vault-pass site.yaml```

I moved install.yaml, upgrade.yaml, uninstall.yaml to collection and modified playbook to:

```
- ansible.builtin.import_playbook: company.some_installer.install.yaml
  tags:
    - install

- ansible.builtin.import_playbook: company.some_installer.upgrade.yaml
  tags:
    - upgrade

- ansible.builtin.import_playbook: company.some_installer.uninstall.yaml
  tags:
    - uninstall
```

I did not make any changes to variables or layout..
Running it, returns error:

```ansible-playbook -i inventories/dev.yaml --ask-vault-pass site.yaml```

```{"msg": "The task includes an option with an undefined variable. The error was: 'iDrac_user' is undefined```

I also tried to run specific collection playbook but with same error:

```ansible-playbook -i inventories/dev.yaml --ask-vault-pass -l dev company.some_installer.install.yaml```

### Expected Results

successful run of playbook with loaded group_vars

### Actual Results

```console
`{"msg": "The task includes an option with an undefined variable. The error was: 'iDrac_user' is undefined`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
