### ISSUE TITLE
Implement systemd "preset" feature to allow not starting a service at installation time (apt)

### ISSUE THREAD

**Issue by jwarnier** [ansible/ansible#76993]
### Summary

Most package (e.g. apt) installations of service would enable and start it right away.
Most of the time when using ansible, this is not what you want, since you probably want to configure it with ansible first.
To achieve this, systemd itself implements a "preset" feature (https://www.freedesktop.org/software/systemd/man/systemctl.html#preset%20UNIT%E2%80%A6), which should be used before installing the package. Sadly, the systemd module does not implement this feature (yet).

### Issue Type

Feature Idea

### Component Name

systemd

### Additional Information

Today, to achieve something similar, you have to:
1.  create configuration directories (and set permissions, etc...)
2. apply your fresh templates to it
3. then install the package and hope it is not going to modify any (Debian usually does not dare, if it recognizes it has been locally-modified). This also prevents using e.g. the _lineinfile_ or any other module only modifying existing files.

Today, you need at least something like this:
```yaml (paste below)
- name: Create Asterisk config directory /etc/asterisk
  file:
    path: "{{ asterisk_config_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Template /etc/asterisk/ configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ asterisk_config_dir }}/{{ item }}"
    mode: '0644'
    owner: root
    group: root
    backup: yes
  with_items:
    - asterisk.conf
    - manager.conf
  notify: reload asterisk
  become: true

- name: Install Asterisk
  apt:
    pkg: "asterisk"
    state: "latest"
    force: yes
    purge: yes
  notify: reload asterisk
  become: true
```
With the requested implementation, it could come down to something like:
```yaml (paste below)
- name: Prevent Asterisk from starting automatically
  systemd:
    name: "asterisk.service"
    preset: disabled
  become: true

- name: Install Asterisk
  apt:
    pkg: "asterisk"
    state: "latest"
    force: yes
    purge: yes
  notify: reload asterisk
  become: true

- name: Template /etc/asterisk/ configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ asterisk_config_dir }}/{{ item }}"
    mode: '0644'
    owner: root
    group: root
    backup: yes
  with_items:
    - asterisk.conf
    - manager.conf
  notify: reload asterisk
  become: true
```

Also, it would allow for clean modification of the systemd unit files.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
