### ISSUE TITLE
Flushing handlers in role's tasks/main.yml has no effect.

### ISSUE THREAD

**Issue by x-moe-x** [ansible/ansible#76998]
### Summary

**Problem:**
I have a role that relies on handlers being flushed before continuing with the play. This used to work in past versions of Ansible but fails to work on my current machine.

**Setup:**

Host System:
My system is Debian 11 64 bit, using Ansible 2.12.2.
(It used to work under Debian 10, using Ansible 2.9.27)
Guest: Vagrant based Debian 9 VM, provisioned with Ansible

**Question:**
This behavior seems to be wrong to me. What can I do to achieve the desired execution order?

### Issue Type

Bug Report

### Component Name

meta

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /home/moe/WebstormProjects/he-server/ansible.cfg
  configured module search path = ['/home/moe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/moe/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
CALLBACKS_ENABLED(/home/moe/WebstormProjects/he-server/ansible.cfg) = ['profile_tasks', 'timer']
DEFAULT_FORCE_HANDLERS(/home/moe/WebstormProjects/he-server/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/moe/WebstormProjects/he-server/ansible.cfg) = ['/home/moe/WebstormProjects/he-server/staging']
DEFAULT_LOG_PATH(/home/moe/WebstormProjects/he-server/ansible.cfg) = /home/moe/WebstormProjects/he-server/execution.log
DEFAULT_ROLES_PATH(/home/moe/WebstormProjects/he-server/ansible.cfg) = ['/home/moe/WebstormProjects/he-server/roles/build', '/home/moe/WebstormProjects/he-server/roles/misc', '/home/moe/WebstormProjects/he-server/roles/server', '/home/moe/WebstormProjects/he-server/roles/shared', '/home/moe/WebstormProjects/he-se>
```

### OS / Environment

Debian 11, Buster 64 bit

### Steps to Reproduce

```yaml (paste below)
---
- name: perform complicated thing
  block:
    - when: some_condition
      block:
        - name: some task
          ...

        - name: important task
          debug: msg="important"
          changed_when: true
          notify:
            - some handler 1
            - some handler 2

# this seems to be ignored
- meta: flush_handlers

# this is executed before the handlers are called
- name: other task that relies on handlers being executed
  ...

```

### Expected Results

Expected execution order:

1. some task
2. some handler 1
3. some handler 2
4. other task that relies on handlers being executed

### Actual Results

```console
Observed execution order:

1. some task
2. other task that relies on handlers being executed -> fails

After the task failing the handlers are invoked and the Play ends prematurely:

1. some handler 1
2. some handler 2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
