### ISSUE TITLE
ansible_connection=docker and async are not compatible?

### ISSUE THREAD

**Issue by MrMEEE** [ansible/ansible#77046]
### Summary

Hi

I'm trying to run the following playbook attached..

When running this playbook against a node with ansible_connection=local or ansible_connection=ssh, the async works as expected.. but when running against a container, using ansible_connection=docker, it seems that the loops are executed sequential instead?

Is there some kind of incompatibility between ansible_connection=docker and async??

Regards  

### Issue Type

Bug Report

### Component Name

ansible

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /opt/awxrpm/sclbuilder-podman/ansible.cfg
  configured module search path = ['/opt/awxrpm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_PIPELINING(/opt/awxrpm/sclbuilder-podman/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/opt/awxrpm/sclbuilder-podman/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no
DEFAULT_FILTER_PLUGIN_PATH(/opt/awxrpm/sclbuilder-podman/ansible.cfg) = ['/opt/awxrpm/sclbuilder-podman/plugins/filter']
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```yaml (paste below)
---
- hosts: prod_sclbuilder_worker
  vars:
    durations:
      - 1
      - 2
      - 3
      - 4
      - 5
  tasks:
  - name: Async sleeping for batched_items
    ansible.builtin.command: sleep {{ async_item }}
    async: 45
    poll: 0
    loop: "{{ durations }}"
    loop_control:
      loop_var: "async_item"
    register: async_results

  - name: Check sync status
    async_status:
      jid: "{{ async_result_item.ansible_job_id }}"
    loop: "{{ async_results.results }}"
    loop_control:
      loop_var: "async_result_item"
    register: async_poll_results
    until: async_poll_results.finished
    retries: 30

```

### Expected Results

async working with ansibel_connection=docker

### Actual Results

```console
Async part is not executed asynchronous
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
