### ISSUE TITLE
`module_defaults` misbehave with modules-as-redirected-actions

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#77059]
### Summary

When redirected actions are used as a module exec subsystem (as many of the networking collections do), `module_defaults` will be incorrectly applied to the resolved platform action (ie, *all* modules that run under that action), because we pre-resolve the action to support DWIM kinds of behaviors on redirected modules/actions.

This issue is exhibited, eg, here: https://github.com/ansible-collections/arista.eos/issues/311

The problem is, because the actual module getting executed (or that a module is being executed at all, since we resolved an *action*) isn't known by the playbook subsystem until after the defaults are applied, Reversing the resolution order to module, action in the module_defaults setup would solve part of the problem, but I'm not sure how to fix this without having a way to interrogate the action about what it actually plans to do, or using some other kind of heuristic that tells us this is likely what's happening and that we need to do something special when determining if module_defaults should apply... This one's gnarly.

### Issue Type

Bug Report

### Component Name

module_defaults

### Ansible Version

```console
2.12
```

### Configuration

```console
NA
```

### OS / Environment

NA

### Steps to Reproduce

Apply module_defaults to a module that's redirected through a shared action ersatz exec subsystem. In the case above, the collection has many modules that are using `action` redirects in `runtime.yml` to redirect to the `eos` platform-specific action (this causes the task to use the `eos` action to execute the requested module instead of `normal.py`). Because we look for actions first in the module_defaults resolution, no matter which `arista.eos` module is requested, module_defaults will resolve to `arista.eos.eos`, and the same thing applies on the execution side. 
```
- hosts: eos
  connection: ansible.netcommon.network_cli
  gather_facts: false
  collections:
    - arista.eos
  module_defaults:
    arista.eos.eos_facts:
      gather_subset: all
      available_network_resources: true
      gather_network_resources:
        - all
        - '!bgp_address_family'
        - '!acls'

  tasks:
    - name: Get Facts
      arista.eos.eos_facts:
```

 "msg": "Unsupported parameters for (arista.eos.eos_command) module: available_network_resources, gather_network_resources, gather_subset. Supported parameters include: retries, provider, interval, wait_for (waitfor), match, commands."

### Expected Results

The task works, and module_defaults are only applied to the module requested

### Actual Results

```console
"msg": "Unsupported parameters for (arista.eos.eos_command) module: available_network_resources, gather_network_resources, gather_subset. Supported parameters include: retries, provider, interval, wait_for (waitfor), match, commands."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
