### ISSUE TITLE
tags get not apply-ed in include_role

### ISSUE THREAD

**Issue by Unip0rn** [ansible/ansible#77081]
### Summary

When using apply in include_role to change the tags that are being used, all tasks get executed disregarding any tags applied.

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Arch Linux

### Steps to Reproduce

Command:
```
ansible-playbook playbook.yml -t A
```

playbook.yml:
```yaml 
- hosts: localhost
  tags: 
    - A
  tasks:
    - name: reproduce behaviour
      include_role:
        name: tagFU
        apply:
          tags:
            - B

- hosts: localhost
  tags:
    - notA
  tasks:
    - name: this should not run
      debug:
        msg: "I have the wrong tag in the playbook-level, that's why I don't run"

```
roles/tagFU/tasks/main.yml:
```yaml
- name: no tags applied
  debug:
    msg: "if this was a fail module, it should be possible to ensure this way that tags are applied"

- name: wrong tags
  debug:
    msg: "I SHALL NOT RUN"
  tags:
    - C

- name: good tags
  debug:
    msg: "WHEEEE"
  tags:
    - B
```

### Expected Results

I expected from the playbook only the first item to execute (```include_role```) because I assume only tasks with matching tags to execute.
I expected from the role only the "good tags" to execute, because I assume the ```tags``` in ```apply``` from ```include_role``` to applied to the role included so that in the role only tasks matching with the ```apply```-ed tags would execute.

### Actual Results

```console
In the playbook tags work as expected: only the first item get's executed.
In the role all tasks are executed, as if no tags were applied.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
