### ISSUE TITLE
ansible can't unarchive tar.gz file

### ISSUE THREAD

**Issue by bodsch** [ansible/ansible#77133]
### Summary

I wnat extract an tar.gz Archive.

Since I don't see any possibility to leave my findings here ...

I have looked at the file `ansible/modules/unarchive.py` (and commented the debug part).

I noticed that in the class `TgzArchive` and in the function `is_unarchived` the variable `unarchived` is set to `True` by default.
If out is empty (as it is in the local call), it is therefore assumed that the archive has already been unpacked.
But this is not the case!

The error handling in the `ZipArchive` class catches this error correctly.

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/bodsch/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/bodsch/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 21:33:02) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed

N/A
```

### OS / Environment

```
$ cat /etc/os-release 
NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
LOGO=artixlinux
```

### Steps to Reproduce

Example on localhost:
```yaml
- name: extract node_exporter archive
  become: false
  delegate_to: "localhost"
  unarchive:
    src: "{{ node_exporter_local_tmp_directory }}/node_exporter-linux-amd64.tar.gz"
    dest: "{{ node_exporter_local_tmp_directory }}"
    copy: false
```
Output:
```yaml
ok: [instance -> localhost] => changed=false 
  check_results:
    cmd:
    - /usr/bin/tar
    - --diff
    - -C
    - /home/bodsch/.cache/ansible/node_exporter/1.3.1
    - -z
    - -f
    - /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
    err: |-
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64/LICENSE: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64/NOTICE: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64/node_exporter: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
    out: ''
    rc: 1
    unarchived: true
  dest: /home/bodsch/.cache/ansible/node_exporter/1.3.1
  gid: 1000
  group: bodsch
  handler: TgzArchive
  invocation:
    module_args:
      attributes: null
      creates: null
      dest: /home/bodsch/.cache/ansible/node_exporter/1.3.1
      exclude: []
      extra_opts: []
      group: null
      include: []
      keep_newer: false
      list_files: false
      mode: null
      owner: null
      remote_src: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
      unsafe_writes: false
      validate_certs: true
  mode: '0750'
  owner: bodsch
  size: 46
  src: /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
  state: directory
  uid: 1000
```

The same example agains to a remote system:
```yaml
- name: extract node_exporter archive
  become: false
  delegate_to: "instance"
  unarchive:
    src: "{{ node_exporter_local_tmp_directory }}/node_exporter-linux-amd64.tar.gz"
    dest: "{{ node_exporter_local_tmp_directory }}"
    copy: false
```

Output:
```yaml
ok: [instance] => 
  msg:
    changed: true
    check_results:
      cmd:
      - /bin/tar
      - --diff
      - -C
      - /var/cache/ansible/node_exporter/1.3.1
      - -z
      - -f
      - /var/cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
      err: |-
        /bin/tar: node_exporter-1.3.1.linux-amd64: Warning: Cannot stat: No such file or directory
        /bin/tar: node_exporter-1.3.1.linux-amd64/LICENSE: Warning: Cannot stat: No such file or directory
        /bin/tar: node_exporter-1.3.1.linux-amd64/NOTICE: Warning: Cannot stat: No such file or directory
        /bin/tar: node_exporter-1.3.1.linux-amd64/node_exporter: Warning: Cannot stat: No such file or directory
      out: |-
        /bin/tar: node_exporter-1.3.1.linux-amd64: Warning: Cannot stat: No such file or directory
        /bin/tar: node_exporter-1.3.1.linux-amd64/LICENSE: Warning: Cannot stat: No such file or directory
        /bin/tar: node_exporter-1.3.1.linux-amd64/NOTICE: Warning: Cannot stat: No such file or directory
        /bin/tar: node_exporter-1.3.1.linux-amd64/node_exporter: Warning: Cannot stat: No such file or directory
      rc: 1
      unarchived: false
    dest: /var/cache/ansible/node_exporter/1.3.1
    extract_results:
      cmd:
      - /bin/tar
      - --extract
      - -C
      - /var/cache/ansible/node_exporter/1.3.1
      - -z
      - -f
      - /var/cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
      err: ''
      out: ''
      rc: 0
    failed: false
    gid: 0
    group: root
    handler: TgzArchive
    mode: '0750'
    owner: root
    size: 4096
    src: /var/cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
    state: directory
    uid: 0
```

local tar
```bash
tar --version

tar (GNU tar) 1.34
Copyright © 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Geschrieben von John Gilmore und Jay Fenlason.
```

remote tar 
```bash
tar --version

tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

### Expected Results

I expect the unpacking to work.

### Actual Results

```console
TASK [ansible-node-exporter : extract node_exporter archive] *******************
task path: /src/ansible/ansible-node-exporter/tasks/download.yml:15
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: bodsch
<localhost> EXEC /bin/sh -c 'echo ~bodsch && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bodsch/.ansible/tmp `"&& mkdir "` echo /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582 `" && echo ansible-tmp-1645688684.4396732-25418-116096014080582="` echo /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582 `" ) && sleep 0'
Using module file /tmp/.tox/py310-ansible510/lib/python3.10/site-packages/ansible/modules/stat.py
<localhost> PUT /home/bodsch/.ansible/tmp/ansible-local-24009r69d8a16/tmpmdiv91nq TO /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/AnsiballZ_stat.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/ /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/AnsiballZ_stat.py && sleep 0'
<localhost> EXEC /bin/sh -c 'NETRC='"'"''"'"' /tmp/.tox/py310-ansible510/bin/python /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/AnsiballZ_stat.py && sleep 0'
Using module file /tmp/.tox/py310-ansible510/lib/python3.10/site-packages/ansible/modules/unarchive.py
<localhost> PUT /home/bodsch/.ansible/tmp/ansible-local-24009r69d8a16/tmppt73tq9r TO /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/AnsiballZ_unarchive.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/ /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/AnsiballZ_unarchive.py && sleep 0'
<localhost> EXEC /bin/sh -c 'NETRC='"'"''"'"' /tmp/.tox/py310-ansible510/bin/python /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/AnsiballZ_unarchive.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/bodsch/.ansible/tmp/ansible-tmp-1645688684.4396732-25418-116096014080582/ > /dev/null 2>&1 && sleep 0'
ok: [instance -> localhost] => changed=false 
  check_results:
    cmd:
    - /usr/bin/tar
    - --diff
    - -C
    - /home/bodsch/.cache/ansible/node_exporter/1.3.1
    - -z
    - -f
    - /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
    err: |-
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64/LICENSE: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64/NOTICE: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      /usr/bin/tar: node_exporter-1.3.1.linux-amd64/node_exporter: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
    out: ''
    rc: 1
    unarchived: true
  dest: /home/bodsch/.cache/ansible/node_exporter/1.3.1
  gid: 1000
  group: bodsch
  handler: TgzArchive
  invocation:
    module_args:
      attributes: null
      creates: null
      dest: /home/bodsch/.cache/ansible/node_exporter/1.3.1
      exclude: []
      extra_opts: []
      group: null
      include: []
      keep_newer: false
      list_files: false
      mode: null
      owner: null
      remote_src: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
      unsafe_writes: false
      validate_certs: true
  mode: '0750'
  owner: bodsch
  size: 46
  src: /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
  state: directory
  uid: 1000

TASK [ansible-node-exporter : d] ***********************************************
task path: /src/ansible/ansible-node-exporter/tasks/download.yml:39
redirecting (type: connection) ansible.builtin.docker to community.docker.docker
Loading collection community.docker from /tmp/.tox/py310-ansible510/lib/python3.10/site-packages/ansible_collections/community/docker
ok: [instance] => 
  msg:
    changed: false
    check_results:
      cmd:
      - /usr/bin/tar
      - --diff
      - -C
      - /home/bodsch/.cache/ansible/node_exporter/1.3.1
      - -z
      - -f
      - /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
      err: |-
        /usr/bin/tar: node_exporter-1.3.1.linux-amd64: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
        /usr/bin/tar: node_exporter-1.3.1.linux-amd64/LICENSE: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
        /usr/bin/tar: node_exporter-1.3.1.linux-amd64/NOTICE: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
        /usr/bin/tar: node_exporter-1.3.1.linux-amd64/node_exporter: Warnung: Funktion stat fehlgeschlagen: Datei oder Verzeichnis nicht gefunden
      out: ''
      rc: 1
      unarchived: true
    dest: /home/bodsch/.cache/ansible/node_exporter/1.3.1
    failed: false
    gid: 1000
    group: bodsch
    handler: TgzArchive
    mode: '0750'
    owner: bodsch
    size: 46
    src: /home/bodsch/.cache/ansible/node_exporter/1.3.1/node_exporter-linux-amd64.tar.gz
    state: directory
    uid: 1000
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
