### ISSUE TITLE
with_first_found: spaces in filenames cause different behaviour

### ISSUE THREAD

**Issue by anxstj** [ansible/ansible#77136]
### Summary

When I try to import a vars file that contains spaces with `with_first_found` then it behaves differently if the files are passed via `_term` or via `files`. If the list is passed to `files` then the file will not be found and the task fails.

### Issue Type

Bug Report

### Component Name

first_found

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.10 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_LOG_PATH(/home/user/.ansible.cfg) = /home/user/ansible.log
DEFAULT_STDOUT_CALLBACK(/home/user/.ansible.cfg) = yaml
RETRY_FILES_ENABLED(/home/sjakobs/.ansible.cfg) = False
```

### OS / Environment

Fedora 35

### Steps to Reproduce

The following playbook will fail:

```yaml (paste below)
---
- name: Converge
  hosts: localhost

  tasks:
    - name: load var with space
      include_vars: "{{ item }}"
      with_first_found:
        files:
          - "vars_with space.yml"
    - name: show var
      debug:
        var: foo
```

But commenting the `files` parameter will cause the playbook to succeed. So the following playbook will succeed:
```
---
- name: Converge
  hosts: localhost
 
  tasks:
    - name: load var with space
      include_vars: "{{ item }}"
      with_first_found:
        # files:
          - "vars_with space.yml"
    - name: show var
      debug:
        var: foo
```

### Expected Results

```
PLAY [Converge] *************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************
ok: [localhost]

TASK [load var with space] *************************************************************************************
ok: [localhost] => (item=/home/user/molecule/default/vars_with space.yml)

TASK [show var] *************************************************************************************************
ok: [localhost] => 
  foo: bar

PLAY RECAP *****************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=
```

### Actual Results

```console
PLAY [Converge] *********************************************************************************************

TASK [Gathering Facts] *********************************************************************************************
ok: [localhost]

TASK [load var with space] *********************************************************************************************
fatal: [localhost]: FAILED! => 
  msg: No file was found when using first_found.

PLAY RECAP *********************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/lookup/first_found.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/first_found.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by jborean93** [comment]
Can you clarify which example fails, the example says

> But uncommenting the files attribute will cause the playbook to succeed:

But the example there is commented.

**Comment by anxstj** [comment]
The first example with `with_first_found: { files: ["vars_with space.yml"] }` fails. The other one succeeds.

And I edited the description to be more precise.

**Comment by mkrizek** [comment]
I think that the first thing here is that `with_first_found` expects a `list` as [documented](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/first_found_lookup.html#parameters). In the "non working" example however a dictionary is passed:
```yaml
    - name: load var with space
      include_vars: "{{ item }}"
      with_first_found:
        files:
          - "vars_with space.yml"
```

A `list` should be passed instead:
```yaml
    - name: load var with space
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "vars_with space.yml"
```

The second part of the problem should be fixed in the PR above I have just opened.

**Comment by anxstj** [comment]
I guess that you'll also need to update the documentation. Your link says explicitly that a dictionary is possible:

```
This lookup can be used in ‘dual mode’, either passing a list of file names or a dictionary that has files and paths.
```

And that's what the example shows, too:
```
- name: Include tasks only if one of the files exist, otherwise skip the task
  include_tasks:
    file: "{{ item }}"
  with_first_found:
    files:
     - path/tasks.yaml
     - path/other_tasks.yaml
    skip: True
```

BTW: Your example works already. Maybe it's only the documentation that's wrong.
