### ISSUE TITLE
apt module has poor support for local packages

### ISSUE THREAD

**Issue by CendioOssman** [ansible/ansible#77144]
### Summary

I am trying to deploy package files over a heterogeneous environment and trying to avoid having to duplicate things for each different distro. As such I want to use the `package` module, which in turn uses the `apt` module, but I'm seeing limitations. Basically I want the `apt` module to support file paths in the `name` argument.

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information

Ideally I want to do this:

```yaml
- name: Install packages
  package:
    name:
      - /path/package_a.deb
      - /path/package_b.deb
```

But the `apt` module doesn't support giving files to the `name` argument, unlike the command `apt`. (**missing feature 1**)

I then change things to:

```yaml
- name: Install packages
  package:
    deb:
      - /path/package_a.deb
      - /path/package_b.deb
```

Which doesn't work either since the `apt` module doesn't support specifying multiple files for the `deb` argument. (**missing feature 2**).

(I can't do this in a loop as the packages have a dependency loop)

So now I have to resort to using the `command` module, which is a lot less flexible.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
Technically `deb` can take multiple packages, by separating the paths with a comma.  But there is certainly room for improvement.

```yaml
- package:
    name: '{{ package_files if ansible_facts.pkg_mgr != "apt" else omit }}'
    deb: '{{ package_files|join(",") if ansible_facts.pkg_mgr == "apt" else omit }}'
```

**Comment by CendioOssman** [comment]
Nice, thanks! That workaround got us a bit further.

Unfortunately we then hit #77150. :/

**Comment by krauthosting** [comment]
@sivel Thanks for the trick. Any workaround with apt module if packages depend on each other?
With plain dpkg wrapped in command/shell module this works, but ain't pretty and idempotent:
`- command: "dpkg {{ package_files|join(' ') if ansible_facts.pkg_mgr == "apt" else omit }}"`

**Comment by Akasurde** [comment]
@krauthosting, I think it's better to create a local file repository for those packages that depend on each other.

```yaml

    - block:
      - name: Install needed packages
        apt:
          name: "{{ item }}"
        with_items:
          - dpkg-dev
          - equivs
          - libfile-fcntllock-perl  # to silence warning by equivs-build
      
      - name: Set repo dir
        set_fact:
          repodir: /tmp/repo/

      - name: Create repo dirs
        file:
          path: "{{ repodir }}/dists/stable/main/binary-all"
          state: directory
          mode: 0755

      - name: Copy packages to remote
        copy:
          src: "{{ item }}"
          dest: "{{ repodir }}/dists/stable/main/binary-all"
        with_items:
          - foo_1.0.1_all.deb
          - baz_1.0.0_all.deb

      - name: Create repo packages
        shell: dpkg-scanpackages --multiversion . /dev/null dists/stable/main/binary-all/ | gzip -9c > Packages.gz
        args:
          chdir: "{{ repodir }}/dists/stable/main/binary-all"
      
      - name: Create repo Release
        copy:
          content: |
            Codename: stable
            Suite: stable
            Components: main
            Architectures: all
          dest: "{{ repodir }}/dists/stable/Release"

      - name: Install repo
        apt_repository:
          repo: deb [trusted=yes arch=all] file:{{ repodir }} stable main
          update_cache: true

      - name: Install foo
        apt:
          name: foo
          state: present

      - name: Install baz
        apt:
          name: baz
          state: present

      always:
        - name: Remove repo
          apt_repository:
            repo: deb [trusted=yes arch=all] file:{{ repodir }} stable main
            update_cache: false
            state: absent

        - name: Remove foo
          apt:
            name: foo
            state: absent

        - name: Remove baz
          apt:
            name: baz
            state: absent

        - name: Remove repo dir
          file:
            path: "{{ repodir }}"
            state: absent 
```
