### ISSUE TITLE
Role Argument Spec Validation Improvements - String conversion, int ranges, Module validation features

### ISSUE THREAD

**Issue by Nubly** [ansible/ansible#77159]
### Summary

(All code previews are from the `2.12.3` release commit on the `stable-2.12` branch.)

I was looking into valiadation methods for Ansible roles, and was excited to see that Ansible now has support for automatic role argument validation tasks through the `meta/argument_specs.yml` file.

Only the 'options' portion of the argument specification is considered in the creation of automatically inserted validation tasks:
https://github.com/ansible/ansible/blob/0ee3815c555ce16e1749a26ce5478eeea72b91a8/lib/ansible/playbook/role/__init__.py#L350-L365
Many features which are available to [AnsibleModule's argument_spec](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec) are not available to role argument specifications, such as options being mutually exclusive, and I believe this may be why.

String conversion is another issue. The [STRING_CONVERSION_ACTION](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#string-conversion-action) configuration option appears to not apply here, and it appears that there is currently no way from within YAML (or existing code for that matter) to control whether or not things get converted to strings:
https://github.com/ansible/ansible/blob/0ee3815c555ce16e1749a26ce5478eeea72b91a8/lib/ansible/module_utils/common/validation.py#L367
The only way strings are useful with this limitation in mind is to use the `choices` option for the spec and this is not applicable to every use case - even if it does support regular expressions.

Lastly, range support for the `int` data type would be nice. For example, when you'd like to specify a valid port number and not have to use regex on a string to validate.

The lack of these features is preventing me from using role argument spec validation within my roles versus other tools, particularly the default string conversion settings within the `check_type_str()` method. Being able to pass a list of dicts to my role when it expects a string and have it pass validation is something that I would like to be able to configure as a failure.

Please let me know if this is better off as a proposal instead.

### Issue Type

Feature Idea

### Component Name

Role Argument Spec Validation

## Ansible Version Info
```shell
nubly@hostname ~
(ansible-2.12) > $ ansible --version
ansible [core 2.12.2]
  config file = /home/nubly/Git/ansible-repo-test/ansible.cfg
  configured module search path = ['/home/nubly/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nubly/.venvs/ansible-2.12/lib/python3.9/site-packages/ansible
  ansible collection location = /home/nubly/Git/ansible-repo-test/collections
  executable location = /home/nubly/.venvs/ansible-2.12/bin/ansible
  python version = 3.9.2 (default, Jan 19 2022, 12:26:41) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```
## Example Run
`meta/argument_specs.yml`:
```yaml
---
argument_specs:
  main:
    short_description: "Main play/entrypoint of {{ role_name }}"
    options:
      test_option_one:
        description: "An option to test."
        type: "str"
      test_option_two:
        description: "This is meant to be a port number from 1000-65535"
        type: "int"
    mutually_exclusive:
      - "test_option_one"
      - "test_option_two"
```
`test-playbook.yml`:
```yaml
---
- hosts: "localhost"
  vars:
    test_option_one:
      - name: "dict one"
        dict_one_var: 6.628
      - name: "dict two"
        dict_two_var:
          - "I am a list"
          - "of various values"
          - "nested inside a dict in a list!"
          - 1
          - 1.01
          - true
          - false
    test_option_two: -99999
  roles:
    - "test_role"
```
`tasks/main.yml`:
```yaml
---
- name: "Print some info about the vars"
  debug:
    msg: "{{ test_option_one }} 
        {{ test_option_two }}"
```
`ansible-playbook` run:
```shell
nubly@hostname ~/ansible/roles/test_role
(ansible-2.12) > $ ansible-playbook -i "localhost," test-playbook.yml

PLAY [localhost] ******************************************************************************************************************************************

TASK [test_role : Validating arguments against arg spec 'main' - Main entrypoint/task of test_role] *******************************************************
ok: [localhost]

TASK [test_role : Print some info about the vars] *********************************************************************************************************
ok: [localhost] => {
    "msg": "[{'name': 'dict one', 'dict_one_var': 'hello'}, {'name': 'dict two', 'dict_two_var': ['I am a list', 'of various values', 'nested inside a dict in a list!', 1, 1.01, True, 'world']}] -99999"
}

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
