### ISSUE TITLE
postgres_privs module sets default privilege for types when it should only be doing so for tables

### ISSUE THREAD

**Issue by caseyandgina** [ansible/ansible#77189]
### Summary

I'm using Ansible 2.12.2.  When using `postgres_privs` to create a default permission for select access on tables, Ansible is also creating a default permission for usage access on types, which I don't think should be happening.

### Issue Type

Bug Report

### Component Name

community.postgresql.postgresql_privs

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/cshobe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/cshobe/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

MacOS 12.2.1

### Steps to Reproduce

```yaml (paste below)
---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Create user
    postgresql_user:
      login_host: localhost
      port: 5432
      login_user: postgres
      login_password: password
      db: testdb
      name: testuser

  - name: Set default privilege
    postgresql_privs:
      login_host: localhost
      port: 5432
      login_user: postgres
      login_password: password
      database: testdb
      type: default_privs
      schema: public
      privs: SELECT
      objs: TABLES
      roles: testuser
```

### Expected Results

Here's the same thing I'm trying to accomplish using SQL, and what I would expect to see:
```
testdb=# alter default privileges in schema public grant select on tables to testuser;
ALTER DEFAULT PRIVILEGES
testdb=# \ddp
            Default access privileges
  Owner   | Schema | Type  |  Access privileges  
----------+--------+-------+---------------------
 postgres | public | table | testuser=r/postgres
(1 row)
```

Per the PostgreSQL documentation, the privilege being granted by Ansible on type is usage, which is explained as:
> For types and domains, allows use of the type or domain in the creation of tables, functions, and other schema objects. (Note that this privilege does not control all “usage” of the type, such as values of the type appearing in queries. It only prevents objects from being created that depend on the type. The main purpose of this privilege is controlling which users can create dependencies on a type, which could prevent the owner from changing the type later.)

Not sure why Ansible is creating this default privilege, but it's not necessary, and if I wanted that, I'd prefer to create it using `type: type` and `privs: USAGE` in the yaml.

### Actual Results

```console
testdb=# \ddp
                        Default access privileges
  Owner   |  Schema  |   Type   |            Access privileges            
----------+----------+----------+-----------------------------------------
 postgres | public   | table    | testuser=r/postgres
 postgres | public   | type     | testuser=U/postgres
(2 rows)
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
