### ISSUE TITLE
unarchive stops working when combining remote_src and and include

### ISSUE THREAD

**Issue by cortex3** [ansible/ansible#77199]
### Summary

When using the ansible.builtin.unarchive module and combining the parameters "remote_src" and "include" The task fails with the error listed below. I can reproduce the error using different .tar.gz files.

### Issue Type

Bug Report

### Component Name

unarchive

### Ansible Version

```console
➜  ~ ansible --version
ansible [core 2.12.2]
  config file = /home/david/git/omni-engine/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/david/git/omni-engine/collections
  executable location = /usr/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
CALLBACKS_ENABLED(/home/REDACTED/ansible.cfg) = ['ansible.posix.profile_tasks']
COLLECTIONS_PATHS(/home/REDACTED/ansible.cfg) = ['/home/REDACTED/collections']
DEFAULT_REMOTE_USER(/home/REDACTED/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/REDACTED/ansible.cfg) = ['/home/REDACTED/roles']
DEFAULT_STDOUT_CALLBACK(/home/REDACTED/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/REDACTED/.vaultpass
HOST_KEY_CHECKING(/home/REDACTED/ansible.cfg) = False
```

### OS / Environment

target:
Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-96-generic x86_64)
tar (GNU tar) 1.30
UnZip 6.00 

### Steps to Reproduce

```yaml (paste below)
- name: download the velero binary
  unarchive:
    src: https://github.com/vmware-tanzu/velero/releases/download/v1.8.0/velero-v1.8.0-linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin/
    mode: "0751"
    include:
      - velero

```

### Expected Results

Task executes with no error

### Actual Results

```console
fatal: [redacted]: FAILED! => changed=false
  invocation:
    module_args:
      attributes: null
      creates: null
      dest: /usr/local/bin/
      exclude: []
      extra_opts: []
      group: null
      include:
      - README.md
      keep_newer: false
      list_files: false
      mode: '0751'
      owner: null
      remote_src: true
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: https://github.com/RocketChat/Rocket.Chat/archive/refs/tags/4.5.0.tar.gz
      unsafe_writes: false
      validate_certs: true
  msg: Failed to find handler for "/root/.ansible/tmp/ansible-tmp-1646333868.329762-76010-124512501441962/4.5.0.tar1a8rqvpi.gz". Make sure the required command to extract the file is installed. Command "/usr/bin/unzip" could not handle archive. Command "/usr/bin/tar" could not handle archive.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/unarchive.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/unarchive.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by jborean93** [comment]
Is the problem with both `remote_src` and `include` together or does it also fail with just `remote_src`. The error you've provided indicates it cannot find the either `unzip` or `tar` or they at least cannot handle this particular archive for some reason.

needs_info

**Comment by sivel** [comment]
The actual error seems to be:

```
Command "gtar" could not handle archive: Unable to list files in the archive: gtar: velero: Not found in archive
gtar: Exiting with failure status due to previous errors
```

The `include` needs to be:

```
include:
  - velero-v1.8.0-linux-amd64/velero
```

To get the outcome you expect, you would also need to add:

```
extra_opts:
  - --strip-components=1
```

The full task:

```yaml
    - name: download the velero binary
      unarchive:
        src: https://github.com/vmware-tanzu/velero/releases/download/v1.8.0/velero-v1.8.0-linux-amd64.tar.gz
        remote_src: true
        dest: '{{ playbook_dir }}/bin'
        mode: "0751"
        include:
          - velero-v1.8.0-linux-amd64/velero
        extra_opts:
          - --strip-components=1
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
