### ISSUE TITLE
Ansible condition "when" can not escape hash(#) if condition string has hash(#) in it.

### ISSUE THREAD

**Issue by kaikudou** [ansible/ansible#77218]
### Summary

Hi:
I want to use playbook to ugrade my Windows EC2 (t2.large) which use PV driver on it.

Some of my EC2 are using ENA driver, 
so I hope my playbook can grep Network Adapter information then make them to be the conditions.

But I got a strange issue, when the device name have hash (```#```) in it, 
the condition will get error, no matter how I try to escape it.

I had try backslash, single quote, double quote but still not working.

The only thing I can find that **WORKS** is from this reference:
[How to escape the '#' comment character within Ansible lineinfile module?](https://stackoverflow.com/questions/30146023/how-to-escape-the-comment-character-within-ansible-lineinfile-module)

But if I use this method to escape the hash(```#```), I will got a WARNING as below:
``` yaml
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: pv_driver_name == "AWS PV Network Device {{ '#' }}0"
```

So is this a bug to ansible condition? or I used the wrong method? or I misunderstand it?

Thank you!

### Issue Type

Bug Report

### Component Name

tests

### Ansible Version

```console
$ ansible --version
ansible 2.9.15
  config file = /test/install_netadapter_driver/ansible.cfg
  configured module search path = ['/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/awx/venv/python36/lib/python3.6/site-packages/ansible
  executable location = /var/lib/awx/venv/python36/bin/ansible
  python version = 3.6.8 (default, Aug 13 2020, 07:46:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/test/install_netadapter_driver/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_LOAD_CALLBACK_PLUGINS(/test/install_netadapter_driver/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/test/install_netadapter_driver/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/test/install_netadapter_driver/ansible.cfg) = 30
HOST_KEY_CHECKING(/test/install_ena_driver/ansible.cfg) = False
```

### OS / Environment

Controller node:
* RedHat 7.8 
* Python 3.6.8

Target node:
* Windows Server 2019 DataCenter
* t2.large EC2 Type

### Steps to Reproduce

```yaml (paste below)
- name: Get Network Driver status before update
  win_shell: Get-NetAdapter | Select-Object InterfaceDescription, DriverVersionString
  register: network_driver_status

- name: Sef drive name from the status data
  set_fact:
    pv_driver_name: "{{ network_driver_status.stdout_lines[3].strip() | regex_search('^AWS PV Network Device #0', ignorecase=True) }}"

- name: Get the exactly PV driver packages version number, the number is AnsibleUnsafeText type data with whitespace.
  win_shell: Get-ItemProperty HKLM:\SOFTWARE\Amazon\PVDriver | Select -ExpandProperty Version
  register: pv_driver_version
  when:
    - pv_driver_name == 'AWS PV Network Device #0'
```

### Expected Results

```yaml (paste below)
TASK [install_netadapter_driver : Get Network Driver status before update] *****************************************************************************************************************************************************************
task path: /test/install_netadapter_driver/tasks/install_pv_driver.yml:1
changed: [pv_host] => changed=true
  cmd: Get-NetAdapter | Select-Object InterfaceDescription, DriverVersionString
  delta: '0:00:01.328181'
  end: '2022-03-06 12:50:50.991857'
  rc: 0
  start: '2022-03-06 12:50:49.663676'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |2-

    InterfaceDescription     DriverVersionString
    --------------------     -------------------
    AWS PV Network Device #0 8.2.5.32
  stdout_lines: <omitted>

TASK [install_netadapter_driver : Sef drive name from the status data] *********************************************************************************************************************************************************************
task path: /test/install_netadapter_driver/tasks/install_pv_driver.yml:5
ok: [pv_host] => changed=false
  ansible_facts:
    pv_driver_name: 'AWS PV Network Device #0'

TASK [install_netadapter_driver : Get the exactly PV driver packages version number, the number is AnsibleUnsafeText type data with whitespace.] *******************************************************************************************
task path: /test/install_netadapter_driver/tasks/install_pv_driver.yml:9
changed: [pv_host] => changed=true 
  cmd: Get-ItemProperty HKLM:\SOFTWARE\Amazon\PVDriver | Select -ExpandProperty Version
  delta: '0:00:00.343786'
  end: '2022-03-06 12:23:58.775368'
  rc: 0
  start: '2022-03-06 12:23:58.431582'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    8.4.1
  stdout_lines: <omitted>
```

### Actual Results

```console
TASK [install_netadapter_driver : Get Network Driver status before update] *****************************************************************************************************************************************************************
task path: /test/install_netadapter_driver/tasks/install_pv_driver.yml:1
changed: [pv_host] => changed=true
  cmd: Get-NetAdapter | Select-Object InterfaceDescription, DriverVersionString
  delta: '0:00:01.328181'
  end: '2022-03-06 12:50:50.991857'
  rc: 0
  start: '2022-03-06 12:50:49.663676'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |2-

    InterfaceDescription     DriverVersionString
    --------------------     -------------------
    AWS PV Network Device #0 8.2.5.32
  stdout_lines: <omitted>

TASK [install_netadapter_driver : Sef drive name from the status data] *********************************************************************************************************************************************************************
task path: /test/install_netadapter_driver/tasks/install_pv_driver.yml:5
ok: [pv_host] => changed=false
  ansible_facts:
    pv_driver_name: 'AWS PV Network Device #0'

TASK [install_netadapter_driver : Get the exactly PV driver packages version number, the number is AnsibleUnsafeText type data with whitespace.] *******************************************************************************************
task path: /test/install_netadapter_driver/tasks/install_pv_driver.yml:9
fatal: [pv_host]: FAILED! => 
  msg: |-
    The conditional check 'pv_driver_name == 'AWS PV Network Device' failed. The error was: template error while templating string: unexpected char "'" at 24. String: {% if pv_driver_name == 'AWS PV Network Device %} True {% else %} False {% endif %}
  
    The error appears to be in '/test/install_netadapter_driver/tasks/install_pv_driver.yml': line 9, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Get the exactly PV driver packages version number, the number is AnsibleUnsafeText type data with whitespace.
      ^ here
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`hacking/tests/gen_distribution_version_testcase.py`](https://github.com/ansible/ansible/blob/devel/hacking/tests/gen_distribution_version_testcase.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug.

You need to enclose the string in quotes, so that the YAML parser can tell the `#` isn't a comment.

```
- name: Get the exactly PV driver packages version number, the number is AnsibleUnsafeText type data with whitespace.
  win_shell: Get-ItemProperty HKLM:\SOFTWARE\Amazon\PVDriver | Select -ExpandProperty Version
  register: pv_driver_version
  when:
    - "pv_driver_name == 'AWS PV Network Device #0'"
```
