### ISSUE TITLE
Handlers not running in correct order when using dynamically generated handlers

### ISSUE THREAD

**Issue by ponchofiesta** [ansible/ansible#77253]
### Summary

According to docs "Handlers always run in the order they are defined"[1]. But when I'm using a static handler and a dynamic handler, Ansible runs all but the last dynamic handler, the static handler and than the last dynamic handler.

[1] https://docs.ansible.com/ansible/latest/user_guide/playbooks_handlers.html

### Issue Type

Bug Report

### Component Name

handler

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg
  configured module search path = ['/home/XXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/XXX/.local/lib/python3.8/site-packages/ansible
  executable location = /home/XXX/.local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ALLOW_WORLD_READABLE_TMPFILES(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = ['/home/XXX/projects/ansible-playbooks-for-build-machines/inventory.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = 60
INTERPRETER_PYTHON(/home/XXX/projects/ansible-playbooks-for-build-machines/ansible.cfg) = auto_silent
```

### OS / Environment

Kubuntu 20.4

### Steps to Reproduce

Playbook "test.yml"
```yaml (paste below)
- hosts: localhost
  gather_facts: no
  become: yes
  become_method: sudo

  vars:
    services:
      - service_name: abc
      - service_name: xyz

  tasks:
    - include_role:
        name: install-service
      vars:
        service_name: "{{ item.service_name }}"
      loop: "{{ services }}"
```

Role "install-service" tasks
```yaml
- name: Installing service {{ service_name }}
  command: echo hello {{ service_name }}
  notify:
    - reload systemd
    - restart service {{ service_name }}
```

Role "install-service" handlers
```yaml
- name: reload systemd
  debug:
    msg: Reloading systemd
- name: restart service {{ service_name }}
  debug:
    msg: Restarting {{ service_name }}
```

Run
```
ansible-playbook test.yml 
```

### Expected Results

I expect handler "reload systemd" to run first like this:

```
RUNNING HANDLER [install-service : reload systemd] *********************************************************************
ok: [localhost] => 
  msg: Reloading systemd

RUNNING HANDLER [install-service : restart service abc] ****************************************************************
ok: [localhost] => 
  msg: Restarting abc

RUNNING HANDLER [install-service : restart service xyz] ****************************************************************
ok: [localhost] => 
  msg: Restarting xyz
```

### Actual Results

```console
Handler "restart service abc" is run first, "reload systemd" second and "restart service xyz" last.


> ansible-playbook test.yml                                     

PLAY [localhost] *******************************************************************************************************

TASK [include_role : install-service] **********************************************************************************

TASK [install-service : Installing service abc] ************************************************************************
changed: [localhost]

TASK [install-service : Installing service xyz] ************************************************************************
changed: [localhost]

RUNNING HANDLER [install-service : restart service abc] ****************************************************************
ok: [localhost] => 
  msg: Restarting abc

RUNNING HANDLER [install-service : reload systemd] *********************************************************************
ok: [localhost] => 
  msg: Reloading systemd

RUNNING HANDLER [install-service : restart service xyz] ****************************************************************
ok: [localhost] => 
  msg: Restarting xyz

PLAY RECAP *************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
