### ISSUE TITLE
Ansible throws error: raise ApiException(http_resp=r) // k8s module

### ISSUE THREAD

**Issue by pascalgliewe** [ansible/ansible#77252]
### Summary

Hello there!

iam trying to setup a kubernetes cluster with ansible (writing my own playbooks) and received this big error message from ansible at the task from "Create a dashboard service account".

Don't really know what to do about this. It looks like it is trying to connect with port "80" instead with the port thats set in the config and i can't find a way to change it.

if more informations are needed, just tell me.

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/clustering/k8s/k8s.py

### Ansible Version

```console
$ ansible --version
ansible 2.9.9
  config file = /home/xx/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/xx/ansible/ansible.cfg) = False
DEFAULT_EXECUTABLE(/home/xx/ansible/ansible.cfg) = /bin/bash
DEFAULT_GATHERING(/home/xx/ansible/ansible.cfg) = implicit
DEFAULT_GATHER_SUBSET(/home/xx/ansible/ansible.cfg) = ['all']
DEFAULT_HOST_LIST(/home/xx/ansible/ansible.cfg) = ['/home/xx/ansible/inventories/production-local/hosts']
DEFAULT_LOG_PATH(/home/xx/ansible/ansible.cfg) = /home/xx/log/ansible.log
DEFAULT_MANAGED_STR(/home/xx/ansible/ansible.cfg) = Ansible managed - template {file} - last modified %Y-%m-%d %H:%M:%S - BE aWARE: YOUR CHANGES WILL BE BLOWN AWAY
DEFAULT_PRIVATE_KEY_FILE(/home/xx/ansible/ansible.cfg) = /home/xx/ansible/.ssh/id_ecdsa
DEFAULT_REMOTE_USER(/home/xx/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/xx/ansible/ansible.cfg) = ['/home/xx/ansible/baseconfig/playbooks/roles']
DEFAULT_TIMEOUT(/home/xx/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/xx/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/xx/ansible/ansible.cfg) = /usr/bin/python3
```

### OS / Environment

Ansible runs on =>

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Kubernetes runs on =>

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Steps to Reproduce

running my playbook
```
ansible-playbook kube-cluster-new/playbooks/03-master.yml -i kube-cluster-new/inventory/hosts

```

That's the playbook:

```
- hosts: master
  become: yes
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install pip openshift
      pip:
        name: openshift

    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=xx.xx.0.0/16 > cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: "{{ hostvars['master'].user }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ hostvars['master'].kubeconfig }}"
        remote_src: yes
        owner: "{{ hostvars['master'].user }}"

    - name: install Pod network
      become: yes
      become_user: "{{ hostvars['master'].user }}"
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml > pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: install Dashboard
      become: yes
      become_user: "{{ hostvars['master'].user }}"
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml > pod_dashboard_setup.txt
      args:
        chdir: $HOME
        creates: pod_dashboard_setup.txt

    - name: create kubernetes proxy script
      copy: src=/home/xx/ansible/kube-cluster-new/files/kubernetes-proxy.service dest=/etc/systemd/system/kubernetes-proxy.service owner=root group=root mode=0755

    - name: Create kubernetes log folder
      shell: mkdir /var/log/kubernetes

    - name: Create kubernetes log file
      shell: touch /var/log/kubernetes/kubernetes-proxy.log

    - name: enable kubernetes proxy script
      shell: systemctl enable kubernetes-proxy
      become: yes

    - name: start kubernetes proxy
      service: name=kubernetes-proxy state=started

    - name: Insert KUBECONFIG in /etc/profile
      lineinfile:
        path: /etc/profile
        line: export KUBECONFIG="{{ hostvars['master'].kubeconfig }}"

    - name: Create a dashboard service account
      k8s:
        kubeconfig: "{{ hostvars['master'].kubeconfig }}"
        state: present
        resource_definition:
          kind: ServiceAccount
          apiVersion: v1
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
```

the "kubeconfig"

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xx-xx-xx==
    server: https://xx.xx.xx.95:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: xx-xx-xx==
    client-key-data: xx-xx-xx=
```

### Expected Results

running without errors and create a dashboard service account

### Actual Results

```console
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     raise ApiException(http_resp=r)
fatal: [master]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.10.10.95 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/client.py\", line 55, in inner\r\n    resp = func(self, *args, **kwargs)\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/client.py\", line 270, in request\r\n    api_response = self.client.call_api(\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py\", line 348, in call_api\r\n    return self.__call_api(resource_path, method,\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py\", line 180, in __call_api\r\n    response_data = self.request(\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py\", line 373, in request\r\n    return self.rest_client.GET(url,\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py\", line 240, in GET\r\n    return self.request(\"GET\", url,\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py\", line 234, in request\r\n    raise ApiException(http_resp=r)\r\nkubernetes.client.exceptions.ApiException: (404)\r\nReason: Not Found\r\nHTTP response headers: HTTPHeaderDict({'Date': 'Thu, 10 Mar 2022 09:19:46 GMT', 'Server': 'Apache/2.4.52 (Debian)', 'Content-Length': '271', 'Content-Type': 'text/html; charset=iso-8859-1'})\r\nHTTP response body: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on this server.</p>\\n<hr>\\n<address>Apache/2.4.52 (Debian) Server at localhost Port 80</address>\\n</body></html>\\n'\r\n\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/home/kubernetes/.ansible/tmp/ansible-tmp-1646903985.9099083-11191-180669108974121/AnsiballZ_k8s.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/kubernetes/.ansible/tmp/ansible-tmp-1646903985.9099083-11191-180669108974121/AnsiballZ_k8s.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/kubernetes/.ansible/tmp/ansible-tmp-1646903985.9099083-11191-180669108974121/AnsiballZ_k8s.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.clustering.k8s.k8s', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_k8s_payload_ov7dg8iy/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py\", line 279, in <module>\r\n  File \"/tmp/ansible_k8s_payload_ov7dg8iy/ansible_k8s_payload.zip/ansible/modules/clustering/k8s/k8s.py\", line 275, in main\r\n  File \"/tmp/ansible_k8s_payload_ov7dg8iy/ansible_k8s_payload.zip/ansible/module_utils/k8s/raw.py\", line 171, in execute_module\r\n  File \"/tmp/ansible_k8s_payload_ov7dg8iy/ansible_k8s_payload.zip/ansible/module_utils/k8s/common.py\", line 200, in get_api_client\r\n  File \"/usr/local/lib/python3.9/dist-packages/openshift/dynamic/client.py\", line 40, in __init__\r\n    K8sDynamicClient.__init__(self, client, cache_file=cache_file, discoverer=discoverer)\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/client.py\", line 84, in __init__\r\n    self.__discoverer = discoverer(self, cache_file)\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/discovery.py\", line 224, in __init__\r\n    Discoverer.__init__(self, client, cache_file)\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/discovery.py\", line 50, in __init__\r\n    self.__init_cache()\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/discovery.py\", line 66, in __init_cache\r\n    self._load_server_info()\r\n  File \"/usr/local/lib/python3.9/dist-packages/openshift/dynamic/discovery.py\", line 98, in _load_server_info\r\n    'kubernetes': self.client.request('get', '/version', serializer=just_json)\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/client.py\", line 57, in inner\r\n    raise api_exception(e)\r\nkubernetes.dynamic.exceptions.NotFoundError: 404\r\nReason: Not Found\r\nHTTP response headers: HTTPHeaderDict({'Date': 'Thu, 10 Mar 2022 09:19:46 GMT', 'Server': 'Apache/2.4.52 (Debian)', 'Content-Length': '271', 'Content-Type': 'text/html; charset=iso-8859-1'})\r\nHTTP response body: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p>The requested URL was not found on this server.</p>\\n<hr>\\n<address>Apache/2.4.52 (Debian) Server at localhost Port 80</address>\\n</body></html>\\n'\r\nOriginal traceback: \r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/client.py\", line 55, in inner\r\n    resp = func(self, *args, **kwargs)\r\n\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/dynamic/client.py\", line 270, in request\r\n    api_response = self.client.call_api(\r\n\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py\", line 348, in call_api\r\n    return self.__call_api(resource_path, method,\r\n\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py\", line 180, in __call_api\r\n    response_data = self.request(\r\n\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py\", line 373, in request\r\n    return self.rest_client.GET(url,\r\n\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py\", line 240, in GET\r\n    return self.request(\"GET\", url,\r\n\r\n  File \"/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py\", line 234, in request\r\n    raise ApiException(http_resp=r)\r\n\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
