### ISSUE TITLE
Cannot run ansible-playbook as a cronjob in an ubuntu:focal docker container

### ISSUE THREAD

**Issue by life5ign** [ansible/ansible#77266]
### Summary

I want to create a docker image that my cross-platform team can run as a container, which will update their public ips periodically in an AWS security group, using cron and ansible, with secret keys passed into the container at runtime.

When I try to run `ansible-playbook` in a cronjob in an *ubuntu:focal* base image docker container, I get the *"Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory."* error.

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.3]
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed

# empty
```

### OS / Environment

Docker `ubuntu:focal` base image running on Ubuntu Focal host.  Dockerfile

```dockerfile
FROM ubuntu:focal

WORKDIR /ansible

# the container will be run as root
# Install prerequisities for Ansible
RUN apt-get update && apt-get -y install \
  python3 \
  python3-pip \
  python-dev \
  gcc \
  glibc-source \
  cron \
  vim-tiny \
  
# Install ansible
RUN pip3 install ansible

# Copy project into working directory
COPY . /ansible

# Run ansible to configure cronjob
RUN ansible-playbook /ansible/main.yml

# start cron (it isn't daemonized by default)
CMD cron
```

### Steps to Reproduce

Playbook that creates the cronjob:
*main.yml*
```yaml (paste below)
- name: Create a cronjob that runs the update security group playbook
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Set path env variable for cron
      ansible.builtin.cron:
        name: PATH
        env: yes
        job: /bin/sh:/usr/local/bin

    - name: Create cronjob that runs playbook every 5 minutes
      ansible.builtin.cron:
        # don't add a leading "0" to single digit values, and quote all
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "ansible-playbook -vvv /ansible/update_sg.yml > /ansible/update_sg.out 2>&1"
        name: "Ansible - update security group {{ lookup('env', 'SG_NAME') }}"
        state: present
```

Playbook that is run in the cronjob
*update_sg.yml*

```yaml
- name: Update security group rule
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  tasks:
    - name: Get current public ipv4
      ansible.builtin.command: "curl icanhazip.com"
      register: current_ipv4_address

    - name: Update security group
      # this will use aws keys in the environment; see doc
      amazon.aws.ec2_group:
        purge_rules: no
        purge_rules_egress: no
        purge_tags: no
        name: "{{ lookup('env', 'SG_NAME') }}"
        description: "{{ lookup('env', 'SG_DESC') }}"
        group_id: "{{ lookup('env', 'SG_ID') }}"
        rules:
          -
            cidr_ip: "{{ current_ipv4_address.stdout | string }}/32"
            from_port: 22
            proto: tcp
            rule_desc: "{{ lookup('env', 'RULE_DESC') }}"
            to_port: 22
        state: present
```

### Expected Results

When I run the update_sg.yml playbook on the CLI in the container, it works fine:
```bash
root@4f05a1f0838b:/ansible# ansible-playbook -vvv update_sg.yml
ansible-playbook [core 2.12.3]
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
Using /ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: update_sg.yml *****************************************************************************************************************************************************
1 plays in update_sg.yml

PLAY [Update security group rule] *******************************************************************************************************************************************
META: ran handlers

TASK [Get current public ipv4] **********************************************************************************************************************************************
task path: /ansible/update_sg.yml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp `"&& mkdir "` echo /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328 `" && echo ansible-tmp-1647031968.5554655-2783-202557898571328="` echo /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-2778sh0170_l/tmpaoatjokw TO /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328/ /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/.ansible/tmp/ansible-tmp-1647031968.5554655-2783-202557898571328/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "cmd": [
        "curl",
        "icanhazip.com"
    ],
    "delta": "0:00:00.219679",
    "end": "2022-03-11 13:52:48.959395",
    "invocation": {
        "module_args": {
            "_raw_params": "curl icanhazip.com",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": false
        }
    },
    "msg": "",
    "rc": 0,
    "start": "2022-03-11 13:52:48.739716",
    "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100    13  100    13    0     0     61      0 --:--:-- --:--:-- --:--:--    61",
    "stderr_lines": [
        "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current",
        "                                 Dload  Upload   Total   Spent    Left  Speed",
        "",
        "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0",
        "100    13  100    13    0     0     61      0 --:--:-- --:--:-- --:--:--    61"
    ],
    "stdout": "myip",
    "stdout_lines": [
        "myip"
    ]
}
```

### Actual Results

```console
But when cron runs it, I get the following error.  I have tried using the default `remote_tmp`, as well as an *ansible.cfg* with `remote_tmp = /tmp/.ansible/tmp`, and I have the same error (below is the latter case):


ansible-playbook [core 2.12.3]
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
Using /ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method

.....snip....

TASK [Get current public ipv4] *************************************************
task path: /ansible/update_sg.yml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp `"&& mkdir "` echo /tmp/.ansible/tmp/ansible-tmp-1647032101.6380093-2871-122019929443865 `" && echo ansible-tmp-1647032101.6380093-2871-122019929443865="` echo /tmp/.ansible/tmp/ansible-tmp-1647032101.6380093-2871-122019929443865 `" ) && sleep 0'
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/.ansible/tmp `\"&& mkdir \"` echo /tmp/.ansible/tmp/ansible-tmp-1647032101.6380093-2871-122019929443865 `\" && echo ansible-tmp-1647032101.6380093-2871-122019929443865=\"` echo /tmp/.ansible/tmp/ansible-tmp-1647032101.6380093-2871-122019929443865 `\" ), exited with result 127",
    "unreachable": true
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
