### ISSUE TITLE
local_action does not support indented parameters in multiple lines

### ISSUE THREAD

**Issue by ngdias** [ansible/ansible#77274]
### Summary

local_action accepts stat as a inline parameter, as the example in https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#delegating-tasks. 

But when trying to standardize to having each parameter in its own line followed by comma, ansible throws an error.

### Issue Type

Bug Report

### Component Name

local_action

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/xxx/Documents/GitHub/xxx/ansible.cfg) = ['/home/xxx/Documents/ansible/hosts']
RETRY_FILES_ENABLED(/home/xxx/Documents/GitHub/xxx/ansible.cfg) = False
```

### OS / Environment

Ubuntu 20.04.4 LTS

### Steps to Reproduce

This doesn't work:
```
  - name: Check if installer exits in control system
    local_action:
      stat:
        path: installer.zip
```
But this works:
```
  - name: Check if installer exits in control system
    local_action: stat path=installer.zip
```
While this also works:
```
  - name: Check if installer exits in remote system
    stat:
      path: installer.zip
```

### Expected Results

I expect all code snippets above to be accepted and executed without errors.

### Actual Results

```console
ERROR! no module/action detected in task.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug, you're just using the wrong syntax.

`local_action` is a variant of the `action` syntax, and is used the same way. When not using key=value syntax, you need to explicitly state the module to call as a module parameter at the same level as the other module parameters. This difference between key=value and YAML is because YAML dictionaries are not ordered, so while in `k=v` parsing Ansible can do some syntactic sugar and use a positional parameter, there is no "first" parameter of the dictionary and it always needs an explicit parameter name.

```
  - name: Check if installer exists in control system
    local_action:
      module: stat
      path: installer.zip
```

At the time this syntax was introduced `action` (and key=value syntax) was much more widely used and documented, so the way to use `local_action` with YAML parameters was obvious. Over the years the community has moved away from using `action` and `local_action`, so you won't find a lot of examples using them in the documentation or in modern playbooks (I can't actually find a single `action` example anywhere in a quick perusal of the playbook docs.)

`delegate_to` is generally preferred over `local_action`, since it is more flexible and its syntax is more in line with other things that affect task execution like `become`.

```
  - name: Check if installer exists in control system
    stat:
      path: installer.zip
    delegate_to: localhost
```
