### ISSUE TITLE
one single changed task causes multiple handler runs, handlers notified for each include_role

### ISSUE THREAD

**Issue by bluikko** [ansible/ansible#77307]
### Summary

There are several issues about a handler in `include_role` being run multiple times but all those issues are for the case where the triggering task is `changed=true` on every `include_role` invocation.  
But this behavior extends to the case where a **single** `changed=true` task causes a handler to run multiple times, once for each handler inside `include_role`.  
The former is "kinda" understandable, to be taken as yet another Ansible quirk/limitation, but the latter is in my opinion unacceptable.

Consider the case:
- Role `a` has 1 handler `X` and 1 task `Y` that notifies it.
- Do `include_role a` in a way that the task `Y` is `changed=false`. Role var `foo=bar`
- Do a second `include_role a` in a way that the task `Y` is `changed=true`. Role var `foo=toto`
- Handler `X` now runs 2 times, even though only **a single task** `is changed`.

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /y/lib64/python3.6/site-packages/ansible
  ansible collection location = /x/.ansible/collections:/usr/share/ansible/collections
  executable location = /y/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
irrelevant
```

### OS / Environment

EL7

### Steps to Reproduce

```yaml (paste below)
ansible-playbook -vv play.yml

#play.yml
---
- name: test handler bug
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: include role first
      ansible.builtin.include_role:
        name: testhandler
      vars:
        call_handler: false
    - name: include role second
      ansible.builtin.include_role:
        name: testhandler
      vars:
        call_handler: true

#roles/testhandler/tasks/main.yml
---
- name: test calling handler
  ansible.builtin.debug:
    msg: calling handler {{ call_handler }}
  changed_when: call_handler
  notify: single handler

#roles/testhandler/handlers/main.yml
---
- name: handler for test task
  ansible.builtin.debug:
    msg: handler was run!
  listen: single handler
```

### Expected Results

Handler should run only 1 time if only 1 task was changed.

I understand there is a limitation/quirk that if the task was changed on every `include_role` invocation, then the handler will run once for each task that was changed.  
But having the handler run multiple times when only 1 task `is changed` is a much more major bug.  
It cannot be said anymore that "oh it just works like that". The reason for why the latter happens may be due to similar Ansible internals but the effect is even more of a bug than the former.

### Actual Results

```console
PLAYBOOK: play.yml **************************************************************************************************************************************************************
1 plays in play.yml

PLAY [test handler bug] *********************************************************************************************************************************************************
META: ran handlers

TASK [include role first] *******************************************************************************************************************************************************
task path: /test-include/play.yml:7

TASK [testhandler : test calling handler] ***************************************************************************************************************************************
task path: /test-include/roles/testhandler/tasks/main.yml:2
ok: [localhost] =>
  msg: calling handler False
META: role_complete for localhost

TASK [include role second] ******************************************************************************************************************************************************
task path: /test-include/play.yml:12
NOTIFIED HANDLER testhandler : handler for test task for localhost
NOTIFIED HANDLER testhandler : handler for test task for localhost

TASK [testhandler : test calling handler] ***************************************************************************************************************************************
task path: /test-include/roles/testhandler/tasks/main.yml:2
changed: [localhost] =>
  msg: calling handler True
META: role_complete for localhost

RUNNING HANDLER [testhandler : handler for test task] ***************************************************************************************************************************
task path: /test-include/roles/testhandler/handlers/main.yml:2
ok: [localhost] =>
  msg: handler was run!

RUNNING HANDLER [testhandler : handler for test task] ***************************************************************************************************************************
task path: /test-include/roles/testhandler/handlers/main.yml:2
ok: [localhost] =>
  msg: handler was run!
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/role/include.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
> I can make a test case if it is really needed but the description above should be clear...

Yes, `Steps to Reproduce` (a minimal standalone playbook, that showcases the problem, that we can copy&paste and run) is required.

I am not able to reproduce the issue with the following playbook:

```yaml
% cat roles/a/tasks/main.yml 
- debug:
  changed_when: foo
  notify:
    - handler
```
```yaml
% cat roles/a/handlers/main.yml 
- name: handler
  debug:
    msg: handler
```
```yaml
% cat 77307.yml 
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: a
      vars:
        foo: false

    - include_role:
        name: a
      vars:
        foo: true
```

results in:
```
PLAY [localhost] ******************************************************************************************************************************************

TASK [include_role : a] ***********************************************************************************************************************************

TASK [a : debug] ******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

TASK [include_role : a] ***********************************************************************************************************************************

TASK [a : debug] ******************************************************************************************************************************************
changed: [localhost] => {
    "msg": "Hello world!"
}

RUNNING HANDLER [a : handler] *****************************************************************************************************************************
ok: [localhost] => {
    "msg": "handler"
}

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

needs_info
