### ISSUE TITLE
Support `accept-new` as value for `host_key_checking`

### ISSUE THREAD

**Issue by septatrix** [ansible/ansible#77318]
### Summary

During initial setup it is common to have many new hosts. For each of these one has to manually accept their keys. Currently it is possible to set `ansible_ssh_common_args` to `-o StrictHostKeyChecking=accept-new`. However as there is an explicit option for this it would be better if that accepted it.

### Issue Type

Feature Idea

### Component Name

ssh

### Additional Information

Currently:

```yaml
- hosts: rpis
  vars:
    ansible_password: foobar
    ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new
    # more portable, less secure:
    host_key_checking: no

  tasks:
    - name: Bootstrapping...
```

Proposed:

```yaml
- hosts: rpis
  vars:
    ansible_password: foobar
    host_key_checking: accept-new

  tasks:
    - name: Bootstrapping...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
