### ISSUE TITLE
Documented exponential backoff method is invalid

### ISSUE THREAD

**Issue by philipsd6** [ansible/ansible#77313]
### Summary

Related: #20226
Related: #72617

The example given in [Data manipulation: Loops and list comprehensions](https://docs.ansible.com/ansible/latest/user_guide/complex_data_manipulation.html#loops-and-list-comprehensions) for creating an exponential backoff does not work as intended, and additionally is also incorrectly quoted.

### Issue Type

Documentation Report

### Component Name

complex_data_manipulation.rst

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0.dev0] (devel 27923aad7e) last updated 2022/03/08 13:33:56 (GMT -400)
  config file = /home/philipsd6/.ansible.cfg
  configured module search path = ['/home/philipsd6/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/philipsd6/devel/ansible/lib/ansible
  ansible collection location = /home/philipsd6/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/philipsd6/.pyenv/versions/3.10.0/bin/ansible
  python version = 3.10.0 (default, Oct  8 2021, 16:24:19) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/philipsd6/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/philipsd6/.ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/home/philipsd6/.ansible.cfg) = /home/philipsd6/.pyenv/shims/vault-bitwarden-client
DEVEL_WARNING(/home/philipsd6/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/philipsd6/.ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/philipsd6/.ansible.cfg) = /tmp
SHOW_CUSTOM_STATS(/home/philipsd6/.ansible.cfg) = True
```

### OS / Environment

Ubuntu 21.10

### Steps to Reproduce

```yaml (paste below)
---
- name: Test retries
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: retry ping with delay
      ping:
      retries: 10
      delay: "{{item|int}}"
      loop: "{{ range(1, 10)|map('pow', 2) }}"

    - name: retry with delay and until
      ansible.builtin.ping:
      register: ping
      retries: 1
      until: item|int > 10
      delay: "{{item|int}}"
      loop: "{{ range(1, 10)|map('pow', 2) }}"
```

### Expected Results

I expected each iteration of `ping` to be delayed exponentially. However, the documented version actually just loops through the `ping` with no delay whatsoever &mdash; no retry logic is triggered.

However, if we add an `until` clause we get partial functionality, as seen in the second task. Here, the retry logic is triggered, but when the `until` clause test is met, the remaining loop items are simply executed with no delay (as above), ignoring the `until` clause.

As a corollary, if `retries` is set > 1, the outcome is that the `ping` is executed _n retries_ times _per_ loop item, i.e. 3 times with 1 second delay, 3 times with 4 second delay, and so on until the `until` condition is met, with the same results as above.

### Actual Results

```console
PLAY [Test retries] ************************************************************

TASK [retry ping with delay] *************************************************** 
ok: [localhost] => (item=1.0)
ok: [localhost] => (item=4.0)
ok: [localhost] => (item=9.0)
ok: [localhost] => (item=16.0)
ok: [localhost] => (item=25.0)
ok: [localhost] => (item=36.0)
ok: [localhost] => (item=49.0)
ok: [localhost] => (item=64.0)
ok: [localhost] => (item=81.0)

TASK [retry with delay and until] **********************************************
FAILED - RETRYING: [localhost]: retry with delay and until (1 retries left). 
failed: [localhost] (item=1.0) => changed=false 
  ansible_loop_var: item
  attempts: 1
  item: 1.0
  ping: pong
FAILED - RETRYING: [localhost]: retry with delay and until (1 retries left).
failed: [localhost] (item=4.0) => changed=false 
  ansible_loop_var: item
  attempts: 1
  item: 4.0
  ping: pong
FAILED - RETRYING: [localhost]: retry with delay and until (1 retries left).
failed: [localhost] (item=9.0) => changed=false 
  ansible_loop_var: item
  attempts: 1
  item: 9.0
  ping: pong
ok: [localhost] => (item=16.0)
ok: [localhost] => (item=25.0)
ok: [localhost] => (item=36.0)
ok: [localhost] => (item=49.0)
ok: [localhost] => (item=64.0)
ok: [localhost] => (item=81.0)

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
