### ISSUE TITLE
Feature Request: Add Ansible module for multiple replication partners.

### ISSUE THREAD

**Issue by remkolodder** [ansible/ansible#77326]
### Summary

We use the VMware community supported Ansible roles to deploy our (large) VMWare platform. We have several clusters that run with linked mode configured (mostly A<>B). However we also have various rings with A<>B<>C<>D<>A (ring complete) clusters configured. We cannot configure that through Ansible.

The JSON to deploy a vCenter only seems to support "one" (1) replication partner.

Would it be possible to extend this?

Thanks!

### Issue Type

Feature Idea

### Component Name

vcenter_replication_partner

### Additional Information

```yaml (paste below)
ansible_vmware.vcenter_replication_partner:
  vcenter_username: {{ vcenter_username }}
  vcenter_hostname: {{ vcenter_hostname }}
  vcenter_password: {{ vcenter_password }}
  replication_partner(s):
  - cluster1
  - cluster2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
