### ISSUE TITLE
file: should not address an error with "src" when state is "absent"

### ISSUE THREAD

**Issue by ppoilbarbe** [ansible/ansible#77338]
### Summary

ansible.builtin.file: existing "src" field raises an error when state is not "link" nor "hard" (as specified in documentation) but it should not when state is "absent" it makes roles more complicated.
When we want to create/remove a link depending on a condition (like for directory), we cannot do it with only one task

```
- name: Create link
  ansible.builtin.file:
    src: existing_file
    dest: link_file
    state: link
  when: condition

- name: Remove link
  ansible.builtin.file:
    dest: link_file
    state: absent
  when: not condition
```
PS: I am not not sure that this can be considered as a bug or a feature request, but as this is not consistent with the other states, IMO this is a bug.

### Issue Type

Bug Report

### Component Name

ansible.builtin.file

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /home/philippe/.ansible.cfg
  configured module search path = ['/home/philippe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/philippe/local/pxansible_conda/envs/pxansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/philippe/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/philippe/local/pxansible_conda/envs/pxansible/bin/ansible
  python version = 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/home/philippe/.ansible.cfg) = False
ANSIBLE_NOCOLOR(/home/philippe/.ansible.cfg) = True
```

### OS / Environment

Ubuntu 20.4
Conda 4.11.0 with Python 3.9.10

### Steps to Reproduce

```yaml
- name: Installs conda init when loging in
  ansible.builtin.file:
    # Names for test
    src: /etc/hosts
    path: /etc/hosts2
    mode: 0o644
    state: "{{ want_it | ternary('link', 'absent') }}"
  tags: for_bug
```

### Expected Results

As explained in summary, "src" field if present when state is "absent " should not raise an error

### Actual Results

```console
$ ansible-playbook --limit=px-2230 --tags=for_bug -e '{"want_it":true}' --ask-become-pass install.yaml 
BECOME password: 

PLAY [Installation of all PX computers] **************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [px-2230]

TASK [facts : Print all standard available facts] ****************************************************************************************************
skipping: [px-2230]

TASK [facts : Print all local available facts] *******************************************************************************************************
skipping: [px-2230]

TASK [base_system : Base system] *********************************************************************************************************************
ok: [px-2230] => {
    "msg": "Installs the base system"
}

TASK [local_anaconda : Installs conda init when loging in] *******************************************************************************************
ok: [px-2230]

TASK [features : Features] ***************************************************************************************************************************
ok: [px-2230] => {
    "msg": "Installs/remove features depending on nodes"
}

TASK [general_packages : General packages] ***********************************************************************************************************
ok: [px-2230] => {
    "msg": "Installs/remove general packages depending on nodes"
}

TASK [finalize : Finalization] ***********************************************************************************************************************
ok: [px-2230] => {
    "msg": "Finalizing operations"
}

PLAY RECAP *******************************************************************************************************************************************
px-2230                    : ok=6    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   




$ ansible-playbook --limit=px-2230 --tags=for_bug -e '{"want_it":false}' --ask-become-pass install.yaml 
BECOME password: 

PLAY [Installation of all PX computers] **************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [px-2230]

TASK [facts : Print all standard available facts] ****************************************************************************************************
skipping: [px-2230]

TASK [facts : Print all local available facts] *******************************************************************************************************
skipping: [px-2230]

TASK [base_system : Base system] *********************************************************************************************************************
ok: [px-2230] => {
    "msg": "Installs the base system"
}

TASK [local_anaconda : Installs conda init when loging in] *******************************************************************************************
fatal: [px-2230]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0777", "msg": "src option requires state to be 'link' or 'hard'", "owner": "root", "path": "/etc/hosts2", "size": 10, "state": "link", "uid": 0}

PLAY RECAP *******************************************************************************************************************************************
px-2230                    : ok=2    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
This can be easily achieved now:

```
- name: Installs conda init when loging in
  ansible.builtin.file:
    # Names for test
    src: "{{ want_it | ternary('/etc/hosts', omit) }}"
    path: /etc/hosts2
    mode: 0o644
    state: "{{ want_it | ternary('link', 'absent') }}"
  tags: for_bug
```

**Comment by flowerysong** [comment]
Setting `src` is not meaningful for `state: absent`, so there is no good reason to allow it. You can still write your task as a single task:

```
- name: Installs conda init when loging in
  ansible.builtin.file:
    # Names for test
    src: "{{ want_it | ternary('/etc/hosts', omit) }}"
    path: /etc/hosts2
    mode: 0o644
    state: "{{ want_it | ternary('link', 'absent') }}"
  tags: for_bug
```
