### ISSUE TITLE
Add setopts functionality to dnf/yum modules

### ISSUE THREAD

**Issue by griffincollege** [ansible/ansible#77345]
### Summary

There exists functionality that allows for the setting of yum configuration options like `tsflags` or `reposdir` realtime when running yum/dnf and this functionality would promote the use of the module for use cases like that.

### Issue Type

Feature Idea

### Component Name

yum/dnf

### Additional Information

```
yum install -y --setopt=tsflags=nocrypto mypackage 
```
vs the preferred way in the added feature
```
name: Install mypackage
yum:
  name: mypackage
  state: installed
  setopt:
  - tsflags=nocrypto
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
