### ISSUE TITLE
Templating inconsistency with native types

### ISSUE THREAD

**Issue by stephan2012** [ansible/ansible#77366]
### Summary

Template evaluation with Jinja2 Native Types enabled gives different results when used in plays vs. templates.

Sample playbook:

```yaml
- hosts: all
  vars:
    g: [foo, bar, baz]
    l: '{{ g |length }}'
    replicas: '{{ (l > 1) |ternary(1, 0) }}'
  tasks:
    - debug: var=replicas
    - template:
        src: t.txt.j2
        dest: t.txt
        mode: 0644
```

While the `debug` task yields the expected result, the `template` task fails with a type exception:

```text
TASK [debug] **********************************************************************************************************************************************************************************
ok: [n0211] => {
    "replicas": 1
}
```

vs.

```text
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: An unhandled exception occurred while templating '{{ (l > 1) |ternary(1, 0) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ (l > 1) |ternary(1, 0) }}): '>' not supported between instances of 'str' and 'int'
```

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/au/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/au/.ansible/collections:/usr/local/share/ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.0 (default, Dec  9 2021, 17:53:27) [GCC 8.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/home/au/.ansible/collections', '/usr/local/share/ansible/collections', '/usr/share/ansible/collections']
DEFAULT_ASK_VAULT_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_JINJA2_NATIVE(/etc/ansible/ansible.cfg) = True
```

### OS / Environment

Ubuntu 18.04 LTS, Python 3.8

### Steps to Reproduce

```yaml (paste below)
- hosts: all
  vars:
    g: [foo, bar, baz]
    l: '{{ g |length }}'
    replicas: '{{ (l > 1) |ternary(1, 0) }}'
  tasks:
    - debug: var=replicas
    - template:
        src: t.txt.j2
        dest: t.txt
        mode: 0644
```

Contents of the template file `t.txt.j2`:

```text
replicas = {{ replicas }}
```

### Expected Results

Same results for both use-cases.

### Actual Results

```console
$ ansible-playbook t.yml -i environments/k8s-bbs2-cluster -l n0211

PLAY [all] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [n0211]

TASK [debug] **********************************************************************************************************************************************************************************
ok: [n0211] => {
    "replicas": 1
}

TASK [template] *******************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: An unhandled exception occurred while templating '{{ (l > 1) |ternary(1, 0) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ (l > 1) |ternary(1, 0) }}): '>' not supported between instances of 'str' and 'int'
fatal: [n0211]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ (l > 1) |ternary(1, 0) }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ (l > 1) |ternary(1, 0) }}): '>' not supported between instances of 'str' and 'int'"}

PLAY RECAP ************************************************************************************************************************************************************************************
n0211                      : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
