### ISSUE TITLE
to_nice_yaml no longer uses multiline

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#77370]
### Summary

`to_nice_yaml` in 2.12 (compared to 2.9) no longer uses multiline to represent multiline strings.
First, it is no longer 'nice'.
Second, some java-based software seems to fail at understanding quoted multiline, and configs generated via `to_nice_yaml` in 2.12 break things.

Is there any rationale for this change, or a parameter to restore nice strings?

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.3]
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_STDOUT_CALLBACK(/usr/local/etc/ansible/ansible.cfg) = yaml
```

### OS / Environment

FreeBSD 13.0

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: test debug
      debug:
        msg: |-
          # mline #
          {{ mline | to_nice_yaml(indent=2) }}
          # mline no newline #
          {{ mline_nnl | to_nice_yaml(indent=2) }}
      vars:
        mline: |
          line1
          line2
          line3
        mline_nnl: |-
          line1
          line2
          line3
      diff: yes

```

### Expected Results

```
ok: [localhost] => 
  msg: |-
    # mline #
    |-
      line1
      line2
      line3
  
    # mline no newline #
    |-
      line1
      line2
      line3
```

### Actual Results

```console
ok: [localhost] => 
  msg: |-
    # mline #
    'line1
  
      line2
  
      line3
  
      '
  
    # mline no newline #
    'line1
  
      line2
  
      line3'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
