### ISSUE TITLE
jenkins_plugin failed download hpi plugins with response code: 401

### ISSUE THREAD

**Issue by DimiDr0l-go** [ansible/ansible#77385]
### Summary

i have nexus group repo with raw proxy repo from https://updates.jenkins.io/download/ and with raw hosted repo, where save modifed update-center.json i.e. path
https://nexus.local/repository/jenkins-update/update-center.json
https://nexus.local/repository/jenkins-update/plugins/ace-editor/1.1/ace-editor.hpi
if making a request curl/wget/python3, then everything is fine, proxy worked, but if use jenkins_plugin then 401
`
curl -O https://nexus.local/repository/jenkins-update/plugins/ace-editor/1.1/ace-editor.hpi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4178k  100 4178k    0     0   140M      0 --:--:-- --:--:-- --:--:--  140M
`
`
import urllib.request
urllib.request.urlretrieve('https://nexus.local/repository/jenkins-update/plugins/antisamy-markup-formatter/2.7/antisamy-markup-formatter.hpi', '/tmp/antisamy-markup-formatter.hpi')
`

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/web_infrastructure/jenkins_plugin.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.8]
  python version = 3.9.6 (default, Jun 29 2021, 06:20:32) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.1.1
  libyaml = True

$ ansible-galaxy collection list
Collection            Version
--------------------- -------
ansible.netcommon     2.5.0
ansible.posix         1.3.0
ansible.utils         2.5.2
awx.awx               17.1.0
community.crypto      2.2.1
community.docker      2.1.1
community.general     4.4.0
community.grafana     1.3.0
community.hashi_vault 2.2.0
community.mongodb     1.3.2
community.mysql       3.1.0
community.postgresql  1.6.1
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

local: 
mac os
Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
remote host:
ubuntu 18.04
Linux 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)
- name: Install Jenkins plugins using password.
  community.general.jenkins_plugin:
    name: "{{ item.key }}"
    version: "{{ item.value.version }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: "{{ 'present' if item.value.version is defined else jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    updates_url: "{{ jenkins_updates_url }}"
    use_proxy: false
    versioned_plugins_url_segments: "plugins"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
  loop: "{{ lookup('dict', (jenkins_common_plugins | combine(jenkins_override_plugins, recursive=True))) }}"
  when: jenkins_admin_password | default(false)
  notify: restart jenkins
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 2
```

### Expected Results

i want to install plugins using custom plugin server

### Actual Results

```console
FAILED - RETRYING: Install Jenkins plugins using password. (2 retries left).Result was: {
    "attempts": 2,
    "changed": false,
    "details": {
        "https://nexus.local/repository/jenkins-update/plugins/Parameterized-Remote-Trigger/3.1.5.1/Parameterized-Remote-Trigger.hpi": "Plugin not found.. fetching url https://nexus.local/repository/jenkins-update/plugins/Parameterized-Remote-Trigger/3.1.5.1/Parameterized-Remote-Trigger.hpi failed. response code: 401. response body: "
    },
    "invocation": {
        "module_args": {
            "attributes": null,
            "client_cert": null,
            "client_key": null,
            "force": false,
            "force_basic_auth": true,
            "group": "jenkins",
            "http_agent": "curl/7.58.0",
            "jenkins_home": "/data/jenkins",
            "latest_plugins_url_segments": [
                "latest"
            ],
            "mode": "0644",
            "name": "Parameterized-Remote-Trigger",
            "owner": "jenkins",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "state": "present",
            "timeout": 30.0,
            "unsafe_writes": false,
            "update_json_url_segment": [
                "update-center.json",
                "updates/update-center.json"
            ],
            "updates_expiration": 86400,
            "updates_url": [
                "https://nexus.local/repository/jenkins-update"
            ],
            "url": "http://localhost:8080",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "use_gssapi": false,
            "use_proxy": false,
            "validate_certs": true,
            "version": "3.1.5.1",
            "versioned_plugins_url_segments": [
                "plugins"
            ],
            "with_dependencies": true
        }
    },
    "msg": "Plugin download failed.",
    "retries": 4
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
