### ISSUE TITLE
unable to pass vars to copy action/module in a playbook

### ISSUE THREAD

**Issue by mattupstate** [ansible/ansible#774]
The following playbook hangs during the copy action:

```

---

- hosts: testing
  user: ubuntu

  vars:
    requirements: /home/ubuntu/requirements.txt

  tasks:
    - name: copy requirements
      action: copy src=files/requirements.txt dest=$requirements
```

But the following playbook does not hang:

``` YAML

---

- hosts: testing
  user: ubuntu

  tasks:
    - name: copy requirements
      action: copy src=files/requirements.txt dest=/home/ubuntu/requirements.txt
```
