### ISSUE TITLE
Remove advanced example which does not work.

### ISSUE THREAD

**Issue by flybyray** [ansible/ansible#77433]
### Summary

Please just remove:

```yaml
   vars:
       myvarnames: "{{ q('varnames', '^my') }}"
       mydict: "{{ dict(myvarnames | zip(q('vars', *myvarnames))) }}"
```
https://docs.ansible.com/ansible/latest/user_guide/complex_data_manipulation.html#id15

No tests exist for this and a simple copy paste is producing some sort of DoS-crash.

There is no additional reference where this was ever used or tested.

Original:
https://github.com/ansible/ansible/pull/46979/files#diff-0b3f5962e2d097f45656021c9579639763d56e82a67bd97d37694027e2f686d9R205-R213

### Issue Type

Documentation Report

### Component Name

docs/docsite/rst/user_guide/complex_data_manipulation.rst

### Ansible Version

```console
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/robert.rettig/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/robert.rettig/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

CentOS Stream 8

### Additional Information

`ansible-playbook debug.yml`
with _debug.yml_:
```yaml
- become: no
  connection: local
  gather_facts: no
  hosts: localhost
  tasks:
    - debug:
        var: mydict
  vars:
    myvarnames: "{{ q('varnames', '^my') }}"
    mydict: "{{ dict(myvarnames | zip(q('vars', *myvarnames))) }}"
```

error:
```txt
...
original message: recursive loop detected in template string: {{ dict(myvarnames | zip(q('vars', *myvarnames))) }}"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/rst/user_guide/complex_data_manipulation.rst`](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/user_guide/complex_data_manipulation.rst)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flybyray** [comment]
maybe this is a better example

```yaml
- become: no
  connection: local
  gather_facts: no
  hosts: localhost
  tasks:
    - debug:
        var: mydict
  vars:
    dbg_123: 123
    dbg_456: [4,5,6]
    dbg_789: {7,8,9}
    myvarnames: "{{ q('varnames', '^dbg_') }}"
    mydict: "{{ dict(myvarnames | zip(q('vars', *myvarnames))) }}"
```
