### ISSUE TITLE
Example on Installing Collections from Tarball File in Documentation is incorrect

### ISSUE THREAD

**Issue by tmichett** [ansible/ansible#77440]
### Summary

Should look like the following

```
collections:
  - name: /tmp/my_namespace-my_collection-1.0.0.tar.gz
    type: file
```

Already fixed and create a pull request for file: #77439 (https://github.com/ansible/ansible/pull/77439)

### Issue Type

Documentation Report

### Component Name

ansible/docs/docsite/rst/shared_snippets/installing_collections_file.rst

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

N/A - website documentation

### Additional Information

When improvement applied, there is a working example on the docs site instead of a non-functional example

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`docs/docsite/rst/shared_snippets/installing_collections_file.rst`](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/shared_snippets/installing_collections_file.rst)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is missing both the ansible version being used, as well as what error was encountered.  

The comment at https://github.com/ansible/ansible/pull/77439#issuecomment-1086110415 does show this works at least for current versions of ansible-core.

**Comment by tmichett** [comment]
[student@workstation Labs]$ ansible --version
ansible 2.9.15


```
---
collections:
  # Install a collection from a File - https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-a-collection-from-source-files
  # Documentation slightly wrong use this as an example
  - source: "/tmp/redhat-satellite-3.1.0.tar.gz"
    type: file
```

```
[student@workstation Labs]$ ansible-galaxy collection install -r collections/requirements.yml -p collections/
**ERROR! Collections requirement entry should contain the key name.**
```
