### ISSUE TITLE
Bug merging items in list

### ISSUE THREAD

**Issue by jovmarkovic** [ansible/ansible#77441]
### Summary

It does not merge the file names. I was trying to get items to merge fro m2 different lists into a single list. When using items from within a single file like this It merges all PublicKeys that are in the same file but not form other files also: 
```
- name: Read wireguard config files
  become: true
  slurp:
    src: "{{item.path}}"
  with_items: "{{config_files.files}}"
  register: wireguard_register_config
- name: Get all public keys from existing config
    set_fact:
       public_keys: "{{ item.content | b64decode | regex_findall('PublicKey = (.*)') }}"
   with_items: "{{wireguard_register_config.results}}"

- name: List public_keys
   debug:
        msg: "{{public_keys}}"

```

### Issue Type

Bug Report

### Component Name

with_items

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/client/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/client/Desktop/PROJECTS/Ansible-playground/venv_Ansible-playground/lib/python3.10/site-packages/ansible
  ansible collection location = /home/client/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/client/Desktop/PROJECTS/Ansible-playground/venv_Ansible-playground/bin/ansible
  python version = 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
  jinja version = 3.1.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml (paste below)

```
```
- name: Find wireguard config files
    find:
      paths: /etc/wireguard/
      patterns: "*.conf"
      recurse: yes
      file_type: file
    register: config_files

  - name: get basename
    set_fact:
      server_conf: "{{item.path|basename|splitext|first}}"
    with_items: "{{config_files.files}}"
  
  - name: list server conf
    debug:
      msg: "{{server_conf}}"
```

### Expected Results

TASK [Ansible-playground : list server conf] ***********************************
ok: [Playground] => {
    "msg": "wg0"
}
ok: [Playground] => {
    "msg": "wg1"
}

### Actual Results

```console
TASK [Ansible-playground : get basename] ***************************************
ok: [Playground] => (item={'path': '/etc/wireguard/wg0.conf', 'mode': '0600', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 167, 'inode': 1030908, 'dev': 2049, 'nlink': 1, 'atime': 1648760824.7995498, 'mtime': 1648760774.7555518, 'ctime': 1648760774.7555518, 'gr_name': 'root', 'pw_name': 'root', 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False})
ok: [Playground] => (item={'path': '/etc/wireguard/wg1.conf', 'mode': '0600', 'isdir': False, 'ischr': False, 'isblk': False, 'isreg': True, 'isfifo': False, 'islnk': False, 'issock': False, 'uid': 0, 'gid': 0, 'size': 168, 'inode': 1030909, 'dev': 2049, 'nlink': 1, 'atime': 1648760825.01155, 'mtime': 1648760813.8355503, 'ctime': 1648760813.8355503, 'gr_name': 'root', 'pw_name': 'root', 'wusr': True, 'rusr': True, 'xusr': False, 'wgrp': False, 'rgrp': False, 'xgrp': False, 'woth': False, 'roth': False, 'xoth': False, 'isuid': False, 'isgid': False})

TASK [Ansible-playground : list server conf] ***********************************
ok: [Playground] => {
    "msg": "wg1"
}

PLAY RECAP *********************************************************************
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/loop_control.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/loop_control.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is not a bug. You are reassigning the variable that is why the result is the last item.

To achieve what you want you can do something like this:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - set_fact:
        server_conf: "{{ server_conf | default([]) + [item|basename|splitext|first] }}"
      loop:
        - /etc/wireguard/wg0.conf
        - /etc/wireguard/wg1.conf

    - debug:
        msg: "{{ server_conf }}"
```

or potentially more efficiently:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - set_fact:
        server_conf: "{{ files|map(attribute='path')|map('basename')|map('splitext')|map('first') }}"
      vars:
        files:
          - path: /etc/wireguard/wg0.conf
          - path: /etc/wireguard/wg1.conf

    - debug:
        msg: "{{ server_conf }}"
```

Maybe there is more elegant way to chain the filters though.

In any case questions like this are better suited for IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jovmarkovic** [comment]
Maybe you didn't understand what I'm trying to do. I need to search for variables first, and then insert them into a list. So, I'm using the output of:
```
- name: Find wireguard config files
    find:
      paths: /etc/wireguard/
      patterns: "*.conf"
      recurse: yes
      file_type: file
    register: config_files
```
Which is:
```
ok: [Playground] => {
    "msg": {
        "changed": false,
        "examined": 2,
        "failed": false,
        "files": [
            {
                "atime": 1648760824.7995498,
                "ctime": 1648760774.7555518,
                "dev": 2049,
                "gid": 0,
                "gr_name": "root",
                "inode": 1030908,
                "isblk": false,
                "ischr": false,
                "isdir": false,
                "isfifo": false,
                "isgid": false,
                "islnk": false,
                "isreg": true,
                "issock": false,
                "isuid": false,
                "mode": "0600",
                "mtime": 1648760774.7555518,
                "nlink": 1,
                "path": "/etc/wireguard/wg0.conf",
                "pw_name": "root",
                "rgrp": false,
                "roth": false,
                "rusr": true,
                "size": 167,
                "uid": 0,
                "wgrp": false,
                "woth": false,
                "wusr": true,
                "xgrp": false,
                "xoth": false,
                "xusr": false
            },
            {
                "atime": 1648760825.01155,
                "ctime": 1648760813.8355503,
                "dev": 2049,
                "gid": 0,
                "gr_name": "root",
                "inode": 1030909,
                "isblk": false,
                "ischr": false,
                "isdir": false,
                "isfifo": false,
                "isgid": false,
                "islnk": false,
                "isreg": true,
                "issock": false,
                "isuid": false,
                "mode": "0600",
                "mtime": 1648760813.8355503,
                "nlink": 1,
                "path": "/etc/wireguard/wg1.conf",
                "pw_name": "root",
                "rgrp": false,
                "roth": false,
                "rusr": true,
                "size": 168,
                "uid": 0,
                "wgrp": false,
                "woth": false,
                "wusr": true,
                "xgrp": false,
                "xoth": false,
                "xusr": false
            }
        ],
        "matched": 2,
        "msg": "All paths examined",
        "skipped_paths": {}
    }
}
```
After that I need to create a list of path items with first split of their basenames.
Should not "with_items" suppose to do that?

**Comment by mkrizek** [comment]
`with_list` loops over a list that is given to it, same as `loop`. It does not create anything.

**Comment by jovmarkovic** [comment]
I have found a solution:
```
  - name: Get server interfaces
    set_fact:
      Interfaces: "{{Interfaces|default([]) + [item.path|basename|splitext|first]}}"
    with_items: "{{config_files.files}}"
```
I was missing append. If anyone has a nicer solution, share. But this works for now :) Thanks @mkrizek
