### ISSUE TITLE
Can't access other field of same mapping

### ISSUE THREAD

**Issue by Et7f3** [ansible/ansible#77442]
### Summary

variable can depend on other variable. field can't depend on other field.

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/Et7f3/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/Et7f3/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 06:19:27) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

macOs

### Steps to Reproduce

group_vars/webs/vars.yml:
```yaml (paste below)
var01: value01
var02: "{{ var01 }}"
var1:
  var11: value11
  var12: "{{ var11 }}"
```
test.yml:
```
---
- hosts: webs
  remote_user: root
  tasks:
  - name: "{{ var01 }} {{ var02 }} {{ var1.var11 }} {{ var1['var12'] }}"
    ping:
```

### Expected Results

It output:
```
TASK [value01 value01 value11 value11] ******************************************************************************
ok: [172.19.113.200]
```
or at least:
```
TASK [value01 value01 {{ var1.var11 }} {{ var1['var12'] }}] ******************************************************************************
ok: [172.19.113.200]
```

### Actual Results

```console
TASK [{{ var01 }} {{ var02 }} {{ var1.var11 }} {{ var1['var12'] }}] *********************************
ssh info
...
Other ssh info so unrelated
ok: [172.19.113.200]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

Edit 1:
The original idea was to execute template on this and `ansible-vault encrypt` so users get a random password not chosen by human.

```
users:
  - name: user1
    password: "{{ lookup('password', 'creds/user/' + name) }}"
  - name: user2
    password: "{{ lookup('password', 'creds/user/' + name) }}"
```
current workaround:
- recopy it. 

~~other solution is to have some `password()` function not linked to a file.~~

Edit 2:
I searched 2h a solution. I open this issue and found exactly what I need 😀 https://docs.ansible.com/ansible/latest/collections/community/general/random_string_lookup.html

but still I expected some variable to be replaced if known.
 I dumped `vars` and understood that variable are added to global roots as they get evaluated. We can only reference global variable or "local" variable if we know the path. I haven't found in vars something to know "the path" something like `self` so I can write `self.name`
