### ISSUE TITLE
Allow installing collections in multiple versions

### ISSUE THREAD

**Issue by joschi36** [ansible/ansible#77463]
#### Situation

We are currently are deploying our product with roles to multiple servers with Ansible. For versioning, we check out multiple versions of the product role, to update each customer individually. The inventory and playbooks sit in an own repo, with the multiple versions of the same role checked out.

Now we see the benefits of using a collection for our product setup. We could add playbooks and add other collections and roles as dependencies to version them as well. 

#### Idea

Now, to benefit from collections, we would need to be able to install multiple versions of a collection in the same requirements.yml file. I saw that there already was an issue in https://github.com/ansible/mazer/issues/149, but couldn't find a follow-up in this repo.

#### Disclaimer

Maybe this is the wrong approach I'm taking. If you have a better idea on how to solve this with Ansible, I would really appreciate it.
I also have added more information about our use case in the *Additional Information* section

### Issue Type

Feature Idea

### Component Name

ansible-collections

### Additional Information

Our actual setup detailed:

#### Directory

```
hosts/
  group_vars/
    customer-a.yaml
    customer-b.yaml
    customer-c.yaml
  inventory.ini
playbooks/
  customer-a.yaml
  customer-b.yaml
  customer-c.yaml
roles/
  product-role-v1.0.0/
  product-role-v1.1.0/
  product-role-v1.1.1/
```

#### `requirements.yml`

```
roles:
- src: git@github.com:blub/product-role.git
  name: product-role-v1.0.0
  scm: git
  version: v1.0.0
- src: git@github.com:blub/product-role.git
  name: product-role-v1.1.0
  scm: git
  version: v1.1.0
- src: git@github.com:blub/product-role.git
  name: product-role-v1.1.1
  scm: git
  version: v1.1.1
```

#### Example Playbook `customer-a.yaml`

```
- hosts: customer-a
  roles:
  - role: product-role-v1.0.0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
