### ISSUE TITLE
[Feature request] Ability to automanipulate with service's timer - if it exists

### ISSUE THREAD

**Issue by imThief** [ansible/ansible#77548]
### Summary

It would be nice to get an ability to automatically do specified manipulation with service's timer too, if it exists. Today there is no builtin way to gather timers information (service_facts doesn't gather info about timers).
For example: I am disabling (or enabling) service 'foobar.service' and want to do the same manipulation with its timer 'foobar.timer', if only i could add an option (lets call it "affect_timer:") to make same action with its timer - that would be very useful i think.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.systemd

### Additional Information

```yaml (paste below)
    - name: Populating service facts
      service_facts:

    - systemd:
          name: "{{ item }}"
          enabled: no
          masked: yes
          state: stopped
          affect_timer: yes
      when:
      - ansible_facts['services'][item] is defined
      loop:
      - foobar.service

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
