### ISSUE TITLE
All handlers for a task are running

### ISSUE THREAD

**Issue by rightaway** [ansible/ansible#77550]
### Summary

All handlers for a task are being run when only the certain ones should.

### Issue Type

Bug Report

### Component Name

handlers

### Ansible Version

```console
$ ansible --version

2.12.4
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

linux

### Steps to Reproduce

```yaml (paste below)
    - copy:
        src: file-{{ item }}
        dest: path-{{ item }}
      loop:
        - 1
        - 2
      notify: listen-{{ item }}

    handlers:

      - name: listen-1
        systemd:
          name: service-1
          state: restarted

      - name: listen-2
        systemd:
          name: service-2
          state: restarted
```

### Expected Results

When only item 1 has changed in the task then only the listen-1 handler should be run.

### Actual Results

```console
listen-1 and listen-2 handlers are both being run.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
