### ISSUE TITLE
Win_hotfix module failing to install MSU file

### ISSUE THREAD

**Issue by jordanjthomas** [ansible/ansible#77552]
### Summary

When I try and run a playbook to install a Windows Update MSU file that is stored locally using the 'win_hotfix' module, it errors out stating a System Object conversion error (shown below).

I have tried multiple different MSU files for different update KBs, same issue applies to all of them.

### Issue Type

Bug Report

### Component Name

win_hotfix module

### Ansible Version

```console
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
```

### Configuration

```console
N/A
```

### OS / Environment

Windows 2019 Server

### Steps to Reproduce

```
---

- name: Install hotfix
  hosts: MyTargetHost
  gather_facts: True

  tasks:
  - name: Install Windows 2019 Patch File
    win_hotfix:
      source: C:\Temp\WinServerUpdates2019\AMD64-all-windows10.0-kb5012647-x64_546889f367caf2a1edd79f5db7d8507e7a53e31b.msu
      state: present
    register: hotfix_install

  - win_reboot:
    when: hotfix_install.reboot_required

...
```

### Expected Results

I expected the hotfix file to run/install normally

### Actual Results

```console
Using module file /usr/lib/python3/dist-packages/ansible/modules/windows/win_hotfix.ps1
Pipelining is enabled.
<HOSTIP> ESTABLISH WINRM CONNECTION FOR USER: ADMINACCOUNT on PORT 5986 TO HOSTIP
EXEC (via pipeline wrapper)
The full traceback is:
Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ChildPath'. Specified method is not supported.
At line:93 char:58
+ ... _file = Join-Path -Path $extract_path -ChildPath $cab_source_filename
+                                                      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.JoinPathCommand

ScriptStackTrace:
at Get-HotfixMetadataFromFile, <No file>: line 93
at <ScriptBlock>, <No file>: line 202
fatal: [172.31.43.53]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ChildPath'. Specified method is not supported."
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
