### ISSUE TITLE
Enable creation of collections from git repo using a script

### ISSUE THREAD

**Issue by t-woerner** [ansible/ansible#77553]
### Summary

Allow to define a script that is used to generate the collection instead of simply calling ansible-galaxy build command. 

### Issue Type

Feature Idea

### Component Name

ansible

### Additional Information

With allowing to use a script instead of calling ansible-galaxy build command it would be possible to create and install the galaxy collection of ansible-freeipa automatically from the github repository:

```yaml (paste below)
    collections:
      - name: freeipa.ansible_freeipa
        type: git
        source: https://github.com/freeipa/ansible-freeipa.git
        version: v1.6.3
```

The repository of ansible-freeipa is not a collection, it is still using the old format that is used for the RPMs in RHEL and Fedora. Therefore the automatic generated collection will not be usable at all.

For the generation of the collections for galaxy and AAP we have a script that is adding the proper name and namespace for the roles, modules, playbooks, tests, documentation and also documentation snippets in the modules. It also fixes the structure and the galaxy.yml file.

We have different name and namespace for galaxy and AAP, therefore we have to fix the name and namespace either way.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
