### ISSUE TITLE
Add possibility to specify type in service_facts

### ISSUE THREAD

**Issue by detobel36** [ansible/ansible#77590]
### Summary

I'm trying to get list of service, timer and mount "systemd".

In the current implementation we limit the type:
```PYTHON
rc, stdout, stderr = self.module.run_command("%s list-unit-files --no-pager --type service --all" % systemctl_path, use_unsafe_shell=True)
```

- https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service_facts.py#L258
- https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service_facts.py#L286

The request is to add an option to select the type we want to fetch.

### Issue Type

Feature Idea

### Component Name

service_facts

### Additional Information

```yaml (paste below)
- name: Populate timer service facts
  ansible.builtin.service_facts:
    type: "timer"

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services

- name: Get all services facts
  ansible.builtin.service_facts:
    var: ansible_facts.services
    type: "{{ item }}"
  loop:
    - "service"
    - "mount"
    - "timer"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
