### ISSUE TITLE
Cant install anything via ansible

### ISSUE THREAD

**Issue by alifiroozi80** [ansible/ansible#77592]
### Summary

When i run `ansible-playbook -i hosts nodejs.yaml` i expected to everything be ok but nothing...
I tried so many things and yet nothing happened!

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/ali/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/ali/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 08:42:42) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
NONE
```

### OS / Environment

MacOS BigSur 11.6.5

### Steps to Reproduce

My **playbook**:
```
- name: Deploy a nodeJS server
  hosts: XXX.XXX.XXX.XX
  tasks:
  
  - name: Update apt repo and cache
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: safe
      install_recommends: yes
      
  - name: Install nodejs and npm
    ansible.builtin.apt:
      pkg:
        - nodejs
        - npm

```

**hosts** file:
```
[webserver]
XXX.XXX.XXX.XX

[webserver:vars]
ansible_ssh_private_key_file=/Users/ali/.ssh/id_ed25519
ansible_user=ali

```

**ansible.cfg** file:
```
[defaults]
host_key_checking = False
default_python_interpreter = /usr/bin/python3
```

### Expected Results

I expected that everything will works now

### Actual Results

```console
PLAY [Deploy a nodeJS server] ***********************************************************************************

TASK [Gathering Facts] ******************************************************************************************
ok: [XXX.XXX.XXX.XX]

TASK [Update apt repo and cache] ********************************************************************************
fatal: [XXX.XXX.XXX.XX]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)"}

PLAY RECAP ******************************************************************************************************
XXX.XXX.XXX.XX             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
