### ISSUE TITLE
Unable to find pip in the virtualenv (python 3.10)

### ISSUE THREAD

**Issue by saltydk** [ansible/ansible#77604]
### Summary

When running the following task (which worked fine on Ubuntu 20.04 which had older versions of both virtualenv and python)
```yaml
- name: Install pip requirements
  ansible.builtin.pip:
    requirements: "/some/full/path/to/file"
    virtualenv_python: python3
    virtualenv: "/path/to/venv"
  become: true
  become_user: "{{ user.name }}"
  ```
returns an error like:

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find pip in the virtualenv, /opt/cloudplow/venv, under any of these names: pip3, pip. Make sure pip is present in the virtualenv."}
  ```
  When comparing the venv structure you get (Ubuntu 20.04 - Python 3.8 - Virtualenv 20.0.17):
  ```
  /opt/script/venv/
├── bin
└── lib
    └── python3.8
 ```
 Whereas on Ubuntu 22.04 (Python 3.10 - Virtualenv 20.13.0+ds) you get:
 ```
/opt/script/venv/
├── lib
│   └── python3.10
└── local
    ├── bin
    └── lib
```
Which, guessing here, is likely why it cannot find pip since the paths have changed.

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.4]
  config file = None
  configured module search path = ['/home/salty/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/salty/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
  jinja version = 3.1.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_FORCE_COLOR(/srv/git/saltbox/ansible.cfg) = True
CALLBACKS_ENABLED(/srv/git/saltbox/ansible.cfg) = ['profile_tasks']
DEFAULT_FACT_PATH(/srv/git/saltbox/ansible.cfg) = ./ansible_facts.d
DEFAULT_HOST_LIST(/srv/git/saltbox/ansible.cfg) = ['/srv/git/saltbox/inventories/local']
DEFAULT_LOG_PATH(/srv/git/saltbox/ansible.cfg) = /srv/git/saltbox/saltbox.log
DEFAULT_ROLES_PATH(/srv/git/saltbox/ansible.cfg) = ['/srv/git/saltbox/roles', '/srv/git/saltbox/resources/roles']
INTERPRETER_PYTHON(/srv/git/saltbox/ansible.cfg) = /usr/bin/python3
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
- name: Install pip requirements
  ansible.builtin.pip:
    requirements: "/some/full/path/to/file"
    virtualenv_python: python3
    virtualenv: "/path/to/venv"
  become: true
  become_user: "{{ user.name }}"
```

### Expected Results

Expected outcome is that pip binary is found and it installs the given requirements.

### Actual Results

```console
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find pip in the virtualenv, /opt/script/venv, under any of these names: pip3, pip. Make sure pip is present in the virtualenv."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/pip.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/pip.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by saltydk** [comment]
It happened on a regular Ubuntu 22.04 install with the versions of python 3.10 and Virtualenv 20.0.17. Are those the same versions you've tested?

**Comment by saltydk** [comment]
Example playbook:
```yaml
---
- name: Virtual env example
  hosts: localhost

  tasks:
    - name: Install pip requirements
      ansible.builtin.pip:
        requirements: "/opt/cloudplow/requirements.txt"
        virtualenv_python: python3
        virtualenv: "/opt/cloudplow/venv"
      become: true
      become_user: "salty"
```
Example output:
```
sudo ansible-playbook playbook.yml -v
No config file found; using defaults
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Virtual env example] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Install pip requirements] **********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find pip in the virtualenv, /opt/cloudplow/venv, under any of these names: pip3, pip. Make sure pip is present in the virtualenv."}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
venv folder layout:
```
tree /opt/cloudplow/venv -L 2
/opt/cloudplow/venv
├── lib
│   └── python3.10
├── local
│   ├── bin
│   └── lib
└── pyvenv.cfg

5 directories, 1 file
```

**Comment by saltydk** [comment]
The pip module only looks after the binaries at /opt/cloudplow/venv/bin so it never finds the binaries at /opt/cloudplow/venv/local/bin based on https://github.com/ansible/ansible/blob/d321fa3f15cefa853d646985b2a201233cdb47c8/lib/ansible/modules/pip.py#L432-L441

**Comment by mkrizek** [comment]
> Which, guessing here, is likely why it cannot find pip since the paths have changed.

But is the change in paths expected?

Doing a quick google search it appears it is not expected and is a bug somewhere else, see https://github.com/pypa/setuptools/issues/3278 or https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1962791.

As per above it is not a bug in Ansible and Ansible should not try to work around that, it needs to be fixed somewhere else.

**Comment by saltydk** [comment]
can confirm that doing 
```yaml
---
- name: Virtual env example
  hosts: localhost

  tasks:
    - name: Install pip requirements
      ansible.builtin.pip:
        requirements: "/opt/cloudplow/requirements.txt"
        virtualenv_python: python3
        virtualenv: "/opt/cloudplow/venv"
      become: true
      become_user: "salty"
      environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib
```
fixes the problem. I'll close this then as it would need a fix outside of Ansible.
