### ISSUE TITLE
Unable to resize gcp disk through google.cloud.gcp_compute_disk

### ISSUE THREAD

**Issue by eyuphxlabs** [ansible/ansible#77605]
### Summary

I am unable to resize the disk size through google.cloud.gcp_compute_disk. 
The initial value for the disk size does not get updated to the new value
```
- hosts: localhost
  tasks:
    - name: create a disk
      google.cloud.gcp_compute_disk:
        name: test-disk
        size_gb: 30
        state: present
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_creds_type }}"
        service_account_contents: "{{ gcp_creds }}"
        zone: "{{ gcp_zone }}"

    - name: resize the disk
      google.cloud.gcp_compute_disk:
        name: test-disk
        size_gb: 60
        state: present
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_creds_type }}"
        service_account_contents: "{{ gcp_creds }}"
        zone: "{{ gcp_zone }}"
```

### Issue Type

Bug Report

### Component Name

 google.cloud.gcp_compute_disk

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6]
config file = /var/home/automate/eddie/infra-ansible-linux/ansible.cfg
  configured module search path = ['/home/automate/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/automate/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/automate/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/automate/.local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/var/home/automate/eddie/infra-ansible-linux/ansible.cfg) = ['/var/home/automate/eddie/infra-ansible-linux/inventory']
DEFAULT_ROLES_PATH(/var/home/automate/eddie/infra-ansible-linux/ansible.cfg) = ['/var/home/automate/eddie/infra-ansible-linux/roles', '/home/automate/.ansible/roles', '/var/home/automate/eddie/shared/roles']
DEFAULT_TIMEOUT(/var/home/automate/eddie/infra-ansible-linux/ansible.cfg) = 30
DEPRECATION_WARNINGS(/var/home/automate/eddie/infra-ansible-linux/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/var/home/automate/eddie/infra-ansible-linux/ansible.cfg) = ['~', '.orig', '.bak', '.cfg', '.retry', '.pyc', '.pyo']
```

### OS / Environment

Ubuntu 20.04.4 LTS

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  tasks:
    - name: create a disk
      google.cloud.gcp_compute_disk:
        name: test-disk
        size_gb: 30
        state: present
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_creds_type }}"
        service_account_contents: "{{ gcp_creds }}"
        zone: "{{ gcp_zone }}"

    - name: resize the disk
      google.cloud.gcp_compute_disk:
        name: test-disk
        size_gb: 60
        state: present
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_creds_type }}"
        service_account_contents: "{{ gcp_creds }}"
        zone: "{{ gcp_zone }}"
```

### Expected Results

It should resize the disk to the new value

### Actual Results

```console
It does not resize the disk to the new value.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
