### ISSUE TITLE
NoneType' object has no attribute 'group

### ISSUE THREAD

**Issue by jaiswaldj** [ansible/ansible#77615]
```
---
- hosts: switch
  connection: network_cli
  become_method: enable
  gather_facts: no
  tasks:
    - name: Interface Configuration
      ios_interfaces:
        config:
          - name: GE1
            description: Ansible Configured
            enabled: yes
            duplex: full
            speed: 1000
        state: merged
```
