### ISSUE TITLE
Alternate entry-point in argument_specs does not work as expected

### ISSUE THREAD

**Issue by nbw74** [ansible/ansible#77625]
### Summary

See https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#specification-format

> entry-point-name
>         The name of the role entry point.
>         This should be main in the case of an unspecified entry point.
>         **This will be the base name of the tasks file to execute, with no .yml or .yaml file extension.**
> 

When I importing role with entrypoint description (e.q. `import_role... name... tasks_from: test.yml`), **argument_specs** section in format _"with no .yml or .yaml file extension"_ (`test: {}`) is ignored. If I adding the file extension to entry-point name (`test.yml: {}`) it works.

### Issue Type

Bug Report

### Component Name

meta/argument_specs.yml

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/home/wbn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/wbn/venv-ansible-212/lib/python3.10/site-packages/ansible
  ansible collection location = /home/wbn/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/wbn/venv-ansible-212/bin/ansible
  python version = 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  jinja version = 3.1.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
CALLBACKS_ENABLED(env: ANSIBLE_CALLBACKS_ENABLED) = ['yaml']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
```

### OS / Environment

Fedora release 35 (Thirty Five)

### Steps to Reproduce

**testrole/meta/argument_specs.yml**
```yaml
---
argument_specs:
  main:
    short_description: The main entry point for the testrole role.
    options: {}
  test:
    short_description: The test entry point for the testrole role.
    options:
      undefined_arg:
        type: str
        required: true
...
```
**site.yml**
```yaml
---
- name: Local role testing
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Import role with alternate entrypoint
      import_role:
        name: testrole
        tasks_from: test.yml
...
```
**testrole/tasks/test.yml**
```yaml
---
- debug:
    msg: nothing
...
```

### Expected Results

```
fatal: [localhost]: FAILED! => changed=false 
  argument_errors:
  - 'missing required arguments: undefined_arg'
  argument_spec_data:
    undefined_arg:
      required: true
      type: str
  msg: |-
    Validation of arguments failed:
    missing required arguments: undefined_arg
  validate_args_context:
    argument_spec_name: test.yml
    name: testrole
    path: /home/nbw/testrole
    type: role

```

### Actual Results

```console
PLAY [Local role testing] ***********************************************************************************************************************************************************************************************************

TASK [testrole : debug] *************************************************************************************************************************************************************************************************************
ok: [localhost] => 
  msg: nothing

PLAY RECAP **************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
