### ISSUE TITLE
"changed": false, "msg": "AnsibleUndefinedVariable: 'msg' is undefined"

### ISSUE THREAD

**Issue by yadgayan** [ansible/ansible#77670]
### Summary

I tried to write ansible output to jinja file. 
my output is like 

ok: [192.168.23.200] => {
    "msg": [
        [
            "Sys::Version",
            "Main Package",
            "  Product     BIG-IP",
            "  Version     14.1.4.3",
            "  Build       0.0.8",
            "  Edition     Point Release 3",
            "  Date        Tue May 18 06:18:01 PDT 2021"
        ],
        [
            "----------------------------",
            "Sys::Clock",
            "----------------------------",
            "Wed Apr 27 19:15:58 PDT 2022"
        ],
        [
            "ltm data-group internal CName_DG499 {",
            "    partition B_3333",
            "    records {",
            "        \"blaa blaaaaaaaaaaaa\" {",
            "            data \"lalalaaaaa blaaaaaaaaaaaaaaaaaaaa\"",
            "        }",
            "    }",
            "    type string",
            "}"
        ]
    ]
}

my jinja file is 

cat message.j2
OUTPUT FROM SHOW COMMANDS for: F5 Cname details

{% for cmd in command_list %}
############ {{ cmd }} ################

{{ result.stdout[loop.index0] }}

{% endfor %}

what is the error? 

### Issue Type

Bug Report

### Component Name

ansible 

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

### Configuration

```console
$ ansible-config dump --only-changed
NA
```

### OS / Environment

CentOS

### Steps to Reproduce

```yaml (paste below)
---

- hosts: F5
  gather_facts: false
  connection: local
  
  vars:
    command_list:
        - show sys version
        - list auth user | grep auth
        - show sys clock
        - list /ltm data-group internal CName_DG499
  tasks:
  - name: Run command
    bigip_command:
      provider:
          server: 192.168.23.200
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: 443
          validate_certs: false
      commands: "{{ command_list }}"
#        - show sys version
#        - list auth user | grep auth
#        - show sys clock
#        - list /ltm data-group internal CName_DG499
      chdir: B_3333
    register: result

  - debug: msg="{{result.stdout_lines}}"

  - name: copy the output to a local file
    copy:
      content: "{{ result.stdout[0] }}"
      dest: "/tmp/F5_details.txt"
    delegate_to: localhost

  - name: "Put all output together into one nice text file"
    template: 
        src: message.j2 
        dest: "/tmp/F5_details.txt" 
```

### Expected Results

write out put to a file

### Actual Results

```console
only update F5_details.txt with 1st list command
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
