### ISSUE TITLE
Cannot parse correctly JSON inventory

### ISSUE THREAD

**Issue by L1ghtn1ng** [ansible/ansible#77697]
### Summary

When I run ansible with a JSON inventory file I always get the following.

```
WARNING]:  * Failed to parse /home/ansible/ansible/inventories/all_hosts.json with yaml plugin: not enough values to unpack (expected 3, got 2)
[WARNING]:  * Failed to parse /home/ansible/ansible/inventories/all_hosts.json with ini plugin: Invalid host pattern 'all:' supplied, ending in ':' is not allowed, this character is reserved to provide a port.
[WARNING]: Unable to parse /home/ansible/ansible/inventories/all_hosts.json as an inventory source
```
I have noticed that it seems to run against some hosts but not all or when I target only a group of servers for when trying to patch servers I get No inventory was parsed only localhost is available.  This is from me having the file formatted as in the docs so I really do not understand what is going on. 

### Issue Type

Bug Report

### Component Name

yaml plugin

### Ansible Version

```console
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/ansible-venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/ansible-venv/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
 
```

### Configuration

```console
$ ansible-config dump --only-changed
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

### OS / Environment

CentOS 7

### Steps to Reproduce

```yaml (paste below)
- name: Patch QA Hosts
  hosts: exa_qa
  serial: 1
  remote_user: ansible
  become: true
 
  pre_tasks:
    - name: remove any CentOS repositories
      shell: rm -f /etc/yum.repos.d/CentOS-*.repo
 
    - name: Stop service httpd
      ansible.builtin.service:
        name: httpd
        state: stopped
 
    - name: Stop service postgresql-10
      ansible.builtin.service:
        name: postgresql-10
        state: stopped
 
  post_tasks:
    - name: Patching host '{{ ansible_nodename }}'
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: ['*httpd*', '*mod_ssl*', '*php*']
        update_cache: true
        update_only: true
        validate_certs: false
      when: ansible_facts['distribution_major_version'] == '7'
 
    - name: Rebooting '{{ ansible_nodename }}' to apply updates
      ansible.builtin.reboot:
        reboot_timeout: 3600
```

### Expected Results

The playbook to run that I have provided and for it to not miss host groups from the inventory file and only run against some from it or not at all when targeting a group from the inventory file

### Actual Results

```console
Either cannot find the group or misses running against host completely due to it not parsing it correctly.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
