### ISSUE TITLE
git module: track_submodules fails on repos without master branch

### ISSUE THREAD

**Issue by Zokormazo** [ansible/ansible#77691]
### Summary

Our repo does not have master anymore, we moved it to main. But git module wants to pull from `master` : https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/git.py#L963 and there is no workaround either since `branch` in .gitmodules is not respected

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0b1.post0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Aug 11 2021, 06:39:25) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

RHEL8 ee-supported

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - name: update project using git
      git:
        dest: "./dest"
        repo: "https://github.com/ansible/test-playbooks.git"
        version: "pull/186/head"
        refspec: "refs/pull/186/head:refs/remotes/origin/pull/186/head"
        track_submodules: yes
      register: git_result
```

### Expected Results

git submodule tracks default branch properly since my .gitmodules does not define a branch.

### Actual Results

```console
Tries to pull from master, which does not exists in https://github.com/ansible/test-playbooks.git


PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY [Update source tree if necessary] *****************************************

TASK [update project using git] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to init/update submodules: Submodule 'test-playbooks' (https://github.com/ansible/test-playbooks) registered for path 'test-playbooks'\\nCloning into '/var/lib/awx/projects/_319__pre_sleep_submodule_project_y/test-playbooks'...\\nfatal: Needed a single revision\\nUnable to find current origin/master revision in submodule path 'test-playbooks'\\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
