### ISSUE TITLE
Let import_role vars more behave like role dependency vars

### ISSUE THREAD

**Issue by Zocker1999NET** [ansible/ansible#77716]
### Summary

`import_role` applies its vars to all tasks above & below it, not just to the ones it imports (described in #62032). However so its behavior differs from `dependencies:` of roles meta and so cannot replace those. I expected `import_role` to behave just like `dependencies:`. I suggest to introduce the expected behavior as additional option, so it can replace `dependencies:` (for example in cases where different execution order is requested).

My current setup is quite difficult to explain, but if it would work as I expected, it allows to define complex roles without code duplication in a easy relatively way. I described it below to allow more insight in how this can be useful. I also added a smaller example below in additional information as well.

### Issue Type

Feature Idea

### Component Name

import_role

#### Small Example
This is a small example project which represents what I expect to be fixed. The comments indicate in which file the content is expected to be. A tar archive is appended as well: [example.tar.gz](https://github.com/ansible/ansible/files/8602557/example.tar.gz)

The roles `as_dependency` and `as_import` do not differ in definition aside from using either `dependencies` or `import_role` to call the role `deduplicated`.

I expect `b_role` to be undefined for the debug tasks inside `as_dependency` / `as_import`, however in `as_import`, in `as_import`'s debug it is defined as this output shows:
```
$ ansible --version
ansible [core 2.12.5]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/tmp/ansible-debug/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/tmp/ansible-debug/venv/bin/ansible
  python version = 3.10.4 (main, Mar 24 2022, 13:07:27) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
$ ansible-playbook site.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: ansible.utils.display.initialize_locale has not been called, this may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths

PLAY [localhost] ***

TASK [as_dependency : b_name should be undefined] ***
ok: [localhost] => {
    "b_name": "VARIABLE IS NOT DEFINED!"
}

PLAY [localhost] ***

TASK [as_import : b_name should be undefined] ***
ok: [localhost] => {
    "b_name": "Playbook - as_import"
}

PLAY RECAP ***
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

```yaml
# site.yml
---
- name: For Comparison
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: as_dependency
      a_name: Playbook
- name: Unexpected Behavior
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: as_import
      a_name: Playbook
```

```yaml
# roles/as_dependency/meta/main.yml
---
allow_duplicates: yes
dependencies:
  - name: deduplicated
    b_name: "{{ a_name }} - as_dependency"
```

```yaml
# roles/as_dependency/tasks/main.yml
---
- name: b_name should be undefined
  debug:
    var: b_name
```

```yaml
# roles/as_import/meta/main.yml
---
allow_duplicates: yes
```

```yaml
# roles/as_import/tasks/main.yml
---
- import_role:
    name: deduplicated
  vars:
    b_name: "{{ a_name }} - as_import"
- name: b_name should be undefined
  debug:
    var: b_name
```

```yaml
# roles/deduplicated/meta/main.yml
---
allow_duplicates: yes
```

#### My Setup

In my playbooks, I assign each imported role, which represents a complete project (usually all included to play in `roles:`), a var called `project_name`. Nearly every role of mine uses this name to determine where to store files for the requested setup and how to uniquely name files / sections elsewhere. E.g. a role called `docker.compose` allows me to set up a docker-compose project with only defining the compose file's content for the role, the role will store those at `/opt/{{ project_name }}` so I can have multiple docker-compose projects which do not interfere with others set up by the same role. I use the same variable name `project_name` for each role to prevent resolution loops and to allow to define one `project_name`, which dependent roles automatically will have access to. E.g. there is also a role `nginx.server` which set ups a virtual server in nginx and a role `keycloak` which now depends on both `docker.compose` and `nginx.server` depending on both `docker.compose` and `nginx.server`. Because `keycloak` is imported like shown, they share access to the same project_name:
```yaml
# site.yml
- hosts: all
  roles:
    - role: keycloak
      project_name: my_keycloak_setup
```

In a side case, I happen to require a docker compose setup aside a nginx virtual server setup to allow for oauth to be implemented automatically. To prevent overwriting other docker projects and prevent duplicated code, I thought about importing the docker-compose role as follows:
```yaml
# roles/nginx.server/tasks/main.yml
- set_fact:  # to prevent loop below of (sub_)project_name requiring project_name to be resolved
    main_project_name: "{{ project_name }}"
    sub_project_name: "{{ project_name }}_oauth2"
- debug: var=project_name  # project_name should still be "main_project_name"
- import_role:
    name: docker.compose
  vars:
    project_name: "{{ sub_project_name }}"
    compose: …
```

But this setup fails because `import_role` applies its vars to all tasks and not to just the tasks its importing. [Here in the docs](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.7.html#include-role-and-import-role-variable-exposure) it is stated that this exposure is to bring its behavior closer to the `roles:` keyword for playbooks. However in that way, its diverting from how role dependencies handle given variables (isolated from the role which instructs those imports). I would prefer if it would behave more like role dependencies.

As a side fact: I try to avoid using `include_role` for me here because of #30882 not being properly fixed.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/import_role.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_role.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Zocker1999NET** [comment]
By looking up the code and trying to implement this PR myself, I found a workaround. By enclosing `import_role` with a block and assigning the vars to the block instead of `import_role`, variables will be handled as I expected:
```yaml
# replacement of roles/as_import/tasks/main.yml
---
- block:
    - import_role:
        name: deduplicated
  vars:
    b_name: "{{ a_name }} - as_import"
- name: b_name should be undefined
  debug:
    var: b_name
```

But I would still prefer to implement this workaround officially (if it would be accepted, I could try to implement this myself) or at least note it in the documentation of `import_role`.
