### ISSUE TITLE
pip editable=true doesn't work with multiple requirement names

### ISSUE THREAD

**Issue by dehnert** [ansible/ansible#77755]
### Summary

When I pass `editable: true` and a list of `name`s, I expect each package to be installed as editable. However, Ansible passes just one `-e` flag to `pip`, whereas the pip semantics appear to be "the next package listed is editable". This means that only the first package named is installed editable, whereas the Ansible structure (a single editable flag) suggests they all should be.

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/tipasa/home/alex/program/vcs/squaresdb/src/squaresdb/ansible/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /mnt/tipasa/home/alex/program/vcs/squaresdb/src/squaresdb/ansible/venv/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

Something like this should reproduce:
```yaml (paste below)
- name: Install virtualenv
  ansible.builtin.pip:
      name:
          - git+https://foo#egg=foo
          - git+https://bar#egg=bar
      editable: true
      virtualenv: /home/quux/venv
```

### Expected Results

I expect this to run a command like `pip3 install -e git+https://foo#egg=foo -e git+https://bar#egg=bar`

### Actual Results

Instead I get `pip3 install -e git+https://foo#egg=foo git+https://bar#egg=bar`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/pip.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/pip.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by dehnert** [comment]
The best workaround is probably something like:
```yaml
- name: Install virtualenv
  ansible.builtin.pip:
      name:
          - -egit+https://foo#egg=foo
          - -egit+https://bar#egg=bar
      virtualenv: /home/quux/venv
```

That is, ignore the `editable` Ansible option entirely and prefix each "package name" with a `-e`.
