### ISSUE TITLE
assemble: new arguement header to add a header on top of the dest file

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#77767]
### Summary

Currently `assemble` does not allow to add a header e.g. to inform a potential editor of the destination file that the file has been generated.

### Issue Type

Feature Idea

### Component Name

assemble

### Additional Information

```yaml
- name: Assemble from fragments from a directory
  ansible.builtin.assemble:
    header: "## Do not motify, autogenerated"
    src: /etc/someapp/fragments
    dest: /etc/someapp/someapp.conf
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
