### ISSUE TITLE
Allow transfers to be compressed

### ISSUE THREAD

**Issue by StyXman** [ansible/ansible#77761]
### Summary

`fetch`, `copy` and others make transfers between controller and managed machine. Sometimes it would be useful if those transfers were compressed. The alternative would be to compress in the source, transfer and decompress in the destination, but it not only becomes 3 steps, one of them has to be run on the controller.

### Issue Type

Feature Idea

### Component Name

fetch, copy, maybe more

### Additional Information

```yaml
- name: Fetch deps install logs
  fetch:
    src:  "{{ item }}"
    dest: "{{ project }}/logs/"
    compress: true
    # maybe also
    # compression_tool: xz
    # compression_level: 9
  loop:
    - "/tmp/prerequisite_packages.log"
    - "/tmp/prerequisite_pkgs_extraction.log"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
