### ISSUE TITLE
Allow templates to call src from web location

### ISSUE THREAD

**Issue by sabman3** [ansible/ansible#77773]
### Summary

Update Ansible builtin to allow the use of a URL for the "src" in the template module. This would eliminate having to use a role or something similar so that the template source is is the same location as the playbook. I'm guessing this can be done via Python geturl. I looked at https://github.com/ansible/ansible/lib/ansible/modules/template.py but did not see the Python code there, so couldn't even tell if it's possible there. 

### Issue Type

Feature Idea

### Component Name

template.py

### Additional Information

I'm not 100% familiar on how to find the code when it's not part of the module, so in the response if someone can point me on how to find this info, maybe I can submit and updated module.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
`copy: content='{{lookup("url" ...`

**Comment by sabman3** [comment]
@bcoca are you saying I can do template: src='{{lookup("url" ... ?

**Comment by phuber92** [comment]
Template is implemented as an action plugin. You can find the code here: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/template.py

If you don't mind doing this process in two tasks you could do something like the following.

```yaml
- name: Download template to ansible controller
  uri:
    url: http://www.example.com/template.j2
    dest: /path/to/local/template.j2
  delegate_to: localhost

- name: Deploy template to remote host
  template:
    src: /path/to/local/template.j2
    dest: /path/to/deployed/template
```
