### ISSUE TITLE
The password_hash filter is not working for bcrypt hash without passlib library

### ISSUE THREAD

**Issue by danpawlik** [ansible/ansible#77808]
### Summary

Hello,

The Ansible in version 2.9 does not have `passlib` library inside the requirements.txt file, which makes an issue to generate bcrypt password hash by using password_hash filter.

### Issue Type

Bug Report

### Component Name

password_hash

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = None
  configured module search path = ['/var/lib/zuul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/zuul/ansible-bin/2.9/lib/python3.8/site-packages/ansible
  executable location = /var/lib/zuul/ansible-bin/2.9/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

### Configuration

```console
$ ansible-config dump --only-changed
NONE
```

### OS / Environment

RHEL8/Centos8

### Steps to Reproduce

```yaml (paste below)
- name: Test bcrypt
  hosts: all
  vars:
    mypassword: testtest1234
  tasks:
    - name: set fact bcrypt password
      set_fact:
        testbcrypt: "{{ mypassword | password_hash('bcrypt', rounds=12) }}"
```

### Expected Results

bcrypt password hash

### Actual Results

```console
Error: 
.crypt does not support 'bcrypt' algorithm
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
