### ISSUE TITLE
mysql_db: ERROR 1698 (28000): Access denied for user 'root'@'localhost' with mariadb-10.6

### ISSUE THREAD

**Issue by asarubbo** [ansible/ansible#77806]
### Summary

mysql_db fails to import a dump with mariadb-10.6 on CentOS 7

### Issue Type

Bug Report

### Component Name

mysql_db

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.4]
  config file = /home/ago/.ansible.cfg
  configured module search path = ['/home/ago/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ago/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.8/ansible
  python version = 3.8.13 (default, Apr  7 2022, 10:43:15) [GCC 10.3.0]
  jinja version = 3.1.1
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed
DEFAULT_FORKS(/home/ago/.ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/ago/.ansible.cfg) = ['/home/ago/git/ansible/common/hosts']
DEFAULT_REMOTE_USER(/home/ago/.ansible.cfg) = root
DEPRECATION_WARNINGS(/home/ago/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/ago/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/ago/.ansible.cfg) = auto_legacy_silent
```

### OS / Environment

target: CentOS 7

### Steps to Reproduce

```yaml (paste below)

    - name: Add MariaDB YUM repository
      yum_repository:
        name: mariadb
        description: MariaDB
        baseurl: http://yum.mariadb.org/10.6/centos7-amd64
        gpgcheck: yes
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        async: no

    - name: Load a dump
      mysql_db:
        name: teams-bridge
        state: import
        target: dump.sql
```

It only fails with the new version of mariadb.
With mariadb provided in the default repo, it succeeds.

Both output are: 'rpm -qa | grep -i mariadb'
So, working versions:
```
mariadb-libs-5.5.68-1.el7.x86_64
mariadb-server-5.5.68-1.el7.x86_64
mariadb-5.5.68-1.el7.x86_64
```

Broken versions:
```
MariaDB-server-10.6.7-1.el7.centos.x86_64
MariaDB-compat-10.6.7-1.el7.centos.x86_64
MariaDB-client-10.6.7-1.el7.centos.x86_64
MariaDB-common-10.6.7-1.el7.centos.x86_64
```

### Expected Results

Loaded a dump successfully

### Actual Results

```console
fatal: []: FAILED! => {"changed": false, "msg": "WARNING: Forcing protocol to  TCP  due to option specification. Please explicitly state intended protocol.\nERROR 1698 (28000): Access denied for user 'root'@'localhost'\n"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
