### ISSUE TITLE
Missing information on ambiguous module names

### ISSUE THREAD

**Issue by eckilein** [ansible/ansible#77818]
### Summary

Hi.
I was wondering if I just can't find any information about the auto-redirect and how to tell ansible which module to take.
One task from our sources as an example:
```yaml
- name: Wait for Start-Up of all component instances
  k8s_info:
    kind: Pod
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    name: "{{ idm_component_name }}-{{ item }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: True
  with_sequence: start=0 end={{ instances_count }}
```
I tried to run this on a new machine and got the following problem:
```bash
ERROR! couldn't resolve module/action 'k8s_info'. This often indicates a misspelling, missing collection, or incorrect module path.
```
While I installed kubernetes.core via galaxy:
```bash
$ ansible-galaxy install -r requirements.yml
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'kubernetes.core:2.3.1' to '/root/.ansible/collections/ansible_collections/kubernetes/core'
Downloading https://galaxy.ansible.com/download/kubernetes-core-2.3.1.tar.gz to /root/.ansible/tmp/ansible-local-1296fgf7zew8/tmpruuqxa4d
```

I found out what the problem is from running the playbook in verbose mode:
If not specified ansible will fall back to community.kubernetes, which is not installed.
```bash
statically imported: /builds/playbook_path_and_name.yaml
redirecting (type: modules) ansible.builtin.k8s_info to community.kubernetes.k8s_info
```

My options for fixing would be:
- Change all occurrences to reference kubernetes.core
- Install community.kubernetes
- Tell ansible to fall back to kubernetes.core instead

While it is not optimal, I would like to use the last option (if possible), since it would affect the least amount of playbook files. 
Any Idea if that is possible and documented somewhere?

### Issue Type

Documentation Report

### Component Name

kubernetes.core?

### Ansible Version

```console
ansible [core 2.12.1]
  config file = /home/USERNAME/SOMEPLACE/ansible.cfg
  configured module search path = ['/home/USERNAME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/USERNAME/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/USERNAME/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/USERNAME/.local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
HOST_KEY_CHECKING(/home/USERNAME/SOMEPLACE/ansible.cfg) = False
```

### OS / Environment

uname -ov
#46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 GNU/Linux

### Additional Information

In my opinion, it would be well suited in a roadmap on how to deal with deprecations like in the case of community.kubernetes and kubernetes.core. 
This way it is possible to install the new module and also switch the fall back, which would include tasks that are not fully-qualified.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
