### ISSUE TITLE
role parameter comparison error

### ISSUE THREAD

**Issue by tom--** [ansible/ansible#7786]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.3
##### Environment:

Darwin fsb.thefsb.org 13.2.0 Darwin Kernel Version 13.2.0: Thu Apr 17 23:03:13 PDT 2014; root:xnu-2422.100.13~1/RELEASE_X86_64 x86_64

Control host is the same as target
##### Summary:

The [gist](https://gist.github.com/tom--/71b79f7b777bd5257590) shows that a parameter named `param` passed into a role has the value `"ansible"` and that the expression `param == 'ansible'` is false. That `param`'s argument is read from `hostvars` seems relevant since another parameter with a string literal argument doesn't show the same pathology.
##### Steps To Reproduce:

https://gist.github.com/tom--/71b79f7b777bd5257590
##### Expected Results:

`param_eq_ansible` should have the value `"yes"`
##### Actual Results:

`param_eq_ansible` has the value `"no"`

**Comment by tom--** [comment]
The bug may have nothing to do with roles:

``` yaml
---
- hosts: 127.0.0.1
  gather_facts: no
  tasks:
    - set_fact:
        the_fact: "ansible"

- hosts: 127.0.0.1
  gather_facts: no
  vars:
      a_var: "{{ hostvars[inventory_hostname]['the_fact'] }}"
      a_var_eq_ansible: "{{ 'yes' if a_var == 'ansible' else 'no' }}"
  tasks:
    - debug: var=a_var
    - debug: var=a_var_eq_ansible
```

Output:

```
TASK: [debug var=a_var] *******************************************************
ok: [127.0.0.1] => {
    "a_var": "ansible"
}

TASK: [debug var=a_var_eq_ansible] ********************************************
ok: [127.0.0.1] => {
    "a_var_eq_ansible": "no"
}
```

**Comment by mpdehaan** [comment]
This example seems hopelessly contrived, do you have an example that applies to a real world use case so we can see it in context?

**Comment by hfinucane** [comment]
I think it has something to do with when `a_var` is evaluated:

```
---
- hosts: 127.0.0.1
  gather_facts: no
  tasks:
    - set_fact:
        the_fact: "ansible"

- hosts: 127.0.0.1
  gather_facts: no
  vars:
      a_var: "{{ hostvars[inventory_hostname]['the_fact'] }}"
      a_var_eq_ansible: "{{ a_var == 'ansible' }}"
  tasks:
    - debug: var=a_var
    - debug: var=a_var_eq_ansible
    - debug: var="{{ a_var == 'ansible' }}"
```

Outputs

```
TASK: [debug var=a_var] ******************************************************* 
ok: [127.0.0.1] => {
    "a_var": "ansible"
}
TASK: [debug var=a_var_eq_ansible] ******************************************** 
ok: [127.0.0.1] => {
    "a_var_eq_ansible": "False"
}
TASK: [debug var="False"] ***************************************************** 
ok: [127.0.0.1] => {
    "True": "True"
}
```

**Comment by mpdehaan** [comment]
So no, then?

**Comment by mpdehaan** [comment]
This is going to be a "too many levels of nesting/confusion" sort of thing, which is why I was requesting a more basic example of the use case, so we could suggest how it could be solved more idiomatically.

**Comment by tom--** [comment]
I need to compute a variable belonging to host1 in a play that runs only on host1 and use it in a subsequent play that runs on another host.

I the example, both hosts were 127.0.0.1 to make it easier for you to reproduce.

I encountered the bug while using parametrized roles and assumed it had something to do with parameter passing. The use case was real but I _contrived_ a version with the same structure and put that in [the original gist](https://gist.github.com/tom--/71b79f7b777bd5257590). Sorry for being hopeless.

Later attempts to work around the bug showed that role parameters were not involved. So I added the second example as a comment after the initial report.

The rest of this comment attempts to answer your question:

> do you have an example that applies to a real world use case so we can see it in context?

In the following demonstration of the bug I use comments to explain this use of variables, after which I say something about my use case.

``` yaml
---
- hosts: host1
  tasks:
    # Do whatever tasks this play needs. Save the value that the subsequent play
    # needs as a host1 fact. This example uses a string literal to demonstrate the
    # bug. In my use case the value is a non-trivial computation in host1's
    # context.
    - set_fact:
        the_fact: "ansible"

- hosts: host2
  vars:
    # Use a variable for host1's fact to make subsequent jinja2 expressions
    # easier to read.
    h1fact: "{{ hostvars['host1']['the_fact'] }}"

    # This expression isn't very complex but my use case needs three strings
    # (a filename, a host ip and a script invocation line with a long string of
    # options), two of which involve a 4-way conditional using h1fact more than
    # once. I put the jinja2 expressions in vars/main.yml of a role to aid
    # readability.
    x: "{{ 'not bug' if h1fact == 'ansible' else 'bug' }}"
  tasks:
    # Do whatever tasks the play needs using the computed variables.
    - debug: var=x
```

My use case is to bring a node into a cluster. It takes a coherent snapshot of application state (databases and uploaded file assets) on a source node, copies the snapshot to the target node, configures the services and applications to use it, configures/starts a DB replication slave, etc. The source may or may not be a slave itself. The target might replicate from the slave or another node.

The first play runs on the target to determine its current condition, what, if anything, it needs, etc. It stores some facts, like the first play in the above example.

The second play runs on the source to determine if a suitable snapshot exists and to prepare one if needed. It needs host1's facts and some of its tasks require strings that are evaluated as described in the comments of the 2nd play in the example above.

A third play runs on the target to fetch and deploy the snapshot.

**Comment by jimi-c** [comment]
Have you tried this with the development branch? There was an issue regarding set_fact not working correctly when gather_facts was disabled, and where the set_fact was the first/only task in the play (which lines up exactly with your example).

**Comment by tom--** [comment]
@jimi-c No, I haven't. I don't think set_fact is involved. See example in following comment.

**UPDATE** I have now tried the devel branch from GitHub. Same behavior as 1.6.3 release.

**Comment by tom--** [comment]
Enough of my cluster use case, which I think is irrelevant, and back to Ansible:

``` yaml
---
- hosts: 127.0.0.1
  vars:
    # On Linux you may not need the [0] before ['address']
    l0ip: "{{ hostvars[inventory_hostname]['ansible_lo0']['ipv4'][0]['address'] }}"
    x: "{{ 'ok' if l0ip == '127.0.0.1' else 'odd' }}"
  tasks:
    - debug: var=l0ip
    - debug: var=x
    - debug: msg="{{ 'ok' if l0ip == '127.0.0.1' else 'odd' }}"
```

Using intermediate variables to simplify complex expressions, reuse values and improve readability is normal in computer programming. Keeping a related series of computations together in one place (e.g. role's `vars/main.yml`) where they can be explained with comments might be called for.

**Comment by tom--** [comment]
In Ansible 1.6.1 the bug does not manifest with the example in the previous comment.

**Comment by jimi-c** [comment]
Bisected to 2e2e5d53215196309ff1f1395f4265cdbd61be7e

**Comment by jimi-c** [comment]
I have a preliminary patch that resolves the issue for your sample above, if you'd like to test it out:

<pre>
diff --git a/lib/ansible/utils/template.py b/lib/ansible/utils/template.py
index 7848dd1..82d67e3 100644
--- a/lib/ansible/utils/template.py
+++ b/lib/ansible/utils/template.py
@@ -159,7 +159,14 @@ class _jinja2_vars(object):
 
     def __contains__(self, k):
         if k in self.vars:
-            return True
+            try:
+                # the variable may be here, however it could depend
+                # on variables which have are not yet available so
+                # we attempt to template the variable now to test that
+                value = self.get_templated_var(k, fail_on_undefined=True)
+                return True
+            except:
+                pass
         for i in self.extras:
             if k in i:
                 return True
@@ -167,6 +174,17 @@ class _jinja2_vars(object):
             return True
         return False
 
+    def get_templated_var(self, varname, fail_on_undefined=False):
+        var = self.vars[varname]
+        # the local flag is an override for the global behavior, since
+        # the __contains__() function will always want to fail on undefined
+        should_fail = self.fail_on_undefined or fail_on_undefined
+        # HostVars is special, return it as-is
+        if isinstance(var, dict) and type(var) != dict:
+            return var
+        else:
+            return template(self.basedir, var, self.vars, fail_on_undefined=should_fail)
+
     def __getitem__(self, varname):
         if varname not in self.vars:
             for i in self.extras:
@@ -176,12 +194,7 @@ class _jinja2_vars(object):
                 return self.globals[varname]
             else:
                 raise KeyError("undefined variable: %s" % varname)
-        var = self.vars[varname]
-        # HostVars is special, return it as-is
-        if isinstance(var, dict) and type(var) != dict:
-            return var
-        else:
-            return template(self.basedir, var, self.vars, fail_on_undefined=self.fail_on_undefined)
+        return self.get_templated_var(varname)
 
     def add_locals(self, locals):
         '''
</pre>

**Comment by tom--** [comment]
That patch fixes the error in the simplest example above. But it appears to introduce a new bug. I haven't the time to study it but it appears to be something like this:

``` yaml
---
# In this play the role doesn't get the right value for param
- hosts: something
  vars:
    - var: "{{ hostvars[foo][bar] }}"
  roles:
    - { role: rolename, param: "{{ var }}" }

# In this one it does
- hosts: something
  roles:
    - { role: rolename, param: "{{ hostvars[foo][bar] }}" }
```

**Comment by jimi-c** [comment]
@tom-- could you give me a full example that reproduces the new error?

**Comment by tom--** [comment]
I haven't been able to able to isolate a case for you yet. The following is for the record and looks promising.

``` yaml
---
- hosts: 127.0.0.1
  vars:
    # On Linux you may not need the [0] before ['address']
    l0ip: "{{ hostvars[inventory_hostname]['ansible_lo0']['ipv4'][0]['address'] }}"
    y: "{{ 'ok' if l0ip == '127.0.0.1' else 'odd' }}"
  pre_tasks:
    - debug: var=y
  roles:
    -
      role: test_role2
      z: "{{ y }}"
```

test_role2:

``` yaml
---
- debug: var=z
```

Output 1.6.1:

```
TASK: [debug var=y] ***********************************************************
ok: [127.0.0.1] => {
    "y": "ok"
}

TASK: [test_role2 | debug var=z] **********************************************
ok: [127.0.0.1] => {
    "item": "",
    "z": "odd"
}
```

Output: 1.6.3:

```
TASK: [debug var=y] ***********************************************************
ok: [127.0.0.1] => {
    "y": "odd"
}

TASK: [test_role2 | debug var=z] **********************************************
ok: [127.0.0.1] => {
    "z": "odd"
}
```

Output: Your patch on devel b7a5ce37a4ee4e4a1a00db2d154ff53ab2042fe8

```
TASK: [debug var=y] ***********************************************************
ok: [127.0.0.1] => {
    "y": "ok"
}

TASK: [test_role2 | debug var=z] **********************************************
ok: [127.0.0.1] => {
    "z": "ok"
}
```
