### ISSUE TITLE
Could not open lock file /var/lib/apt/lists/lock - open (2: No such file or directory)

### ISSUE THREAD

**Issue by RankoR** [ansible/ansible#77869]
### Summary

My playbook:

```
---
  - hosts: all
    remote_user: root
    become: true

    tasks:
      - name: Update and upgrade apt packages
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 # One day
```

I believe that it fails because `/var/lib/apt/lists/` directory does not exist (`/var/lib/apt/` exists).

If I manually run `apt update && apt dist-upgrade` it works fine.

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
2.12.5
```

### Configuration

```console
$ ansible-config dump --only-changed -t all

DEFAULT_HOST_LIST(/Users/user/.ansible.cfg) = ['/Users/user/.ansible/hosts']

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
=====
```

### OS / Environment

Remote server: Ubuntu 20.04

### Steps to Reproduce

```yaml 
---
  - hosts: all
    remote_user: root
    become: true

    tasks:
      - name: Update and upgrade apt packages
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 # One day
```

### Expected Results

Packages upgraded

### Actual Results

```console
FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (2: No such file or directory)"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
