### ISSUE TITLE
Support per-host include_role (run_once: no)

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#77866]
### Summary

It would be a convenient way to select chunks of vars/defaults/tasks for execution on hosts with intersecting but not matching sets of services without duplicating playbooks or setting up a mess of conditions inside roles.

Currently `include_role` runs outside of hosts loop, so it is impossible to include different roles on different hosts.

semi-off-topic: is it technically possible to make roles somehow **completely** "toggleable" in context of playbook/static import?

### Issue Type

Feature Idea

### Component Name

core

### Additional Information

In group_vars/group1:
```yaml (paste below)
## group1
subservice_roles__g1:
  - role1
  - role2
```
In group_vars/group2:
```yaml (paste below)
## group2
subservice_roles__g2:
  - role1
  - role3
```
In host_vars/host4:
```yaml (paste below)
subservice_roles__host:
  - role4
```
Inventory:
```yaml (paste below)
[group1]
host1
host3
host4
[group2]
host2
host3
[group3]
host5
[service_group:children]
group1
group2
group3
```
In tasks:
```yaml (paste below)
- name: selectively include subservice roles
  run_once: no
  include_role:
    name: "{{ selected_role }}"
  loop: "{{ query('vars', *(query('varnames', '^subservice_roles__.+') | sort) | flatten | unique }}"
  loop_control:
    loop_var: selected_role
```
Playing on service_group would result in:
host1 # will get role1, role2
host2 # will get role1, role3
host3 # will get role1, role2, role3
host4 # will get role1, role2, role4
host5 # will get no roles

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
