### ISSUE TITLE
Error while trying to test connection to Azure Win VM using public IP

### ISSUE THREAD

**Issue by karishma-kohli** [ansible/ansible#77865]
### Summary

Hi I am using MacOS 11.5.1 and Ansible version 2.9

**My playbook is as follows -**

```yaml
---
- hosts: all
  vars_prompt:
    - name: ansible_password
      prompt: "Enter local administrator password"
  vars:
    ansible_user: kohli_root
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Test connection
    win_ping:
```
**Command:** 

ansible-playbook playbooks/azure_windows_vm.yml -i 20.248.203.223,

**Output:**

```
Enter local administrator password: 

PLAY [20.248.203.223] ***********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************
**objc[30830]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[30830]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state**
```
Can you please advise why am I hitting this error and how do I resolve this?

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version

ansible 2.9.7
  config file = None
  configured module search path = ['/Users/karishmakohli/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/karishmakohli/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /users/karishmakohli/Library/Python/3.8/bin/ansible
  python version = 3.8.9 (default, Oct 26 2021, 07:25:53) [Clang 13.0.0 (clang-1300.0.29.30)]
```

### Configuration

```console
$ ansible-config dump --only-changed -t all

this command doesnt look right and ending into an error:

% ansible-config dump --only-changed -t all
usage: ansible-config [-h] [--version] [-v] {list,dump,view} ...
ansible-config: error: unrecognized arguments: -t all
```

### OS / Environment

macOS 11.5.1

chip: Apple M1

### Steps to Reproduce

```yaml (paste below)
---
- hosts: all
  vars_prompt:
    - name: ansible_password
      prompt: "Enter local administrator password"
  vars:
    ansible_user: kohli_root
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Test connection
    win_ping:

```

### Expected Results

Expected success ping but ended into an error.

### Actual Results

```console
Enter local administrator password: 

PLAY [20.248.203.223] ***********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************
**objc[30830]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[30830]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state**
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
