### ISSUE TITLE
include_vars does not find files inside vars directory of a role

### ISSUE THREAD

**Issue by micafer** [ansible/ansible#7787]
Hi,

The "include_vars" module, as it is explained in the documentation (http://docs.ansible.com/include_vars_module.html):

" if called from a role it will look for the file in vars/ subdirectory of the role"

I can't make it work. In particular in the role "micafer.ganglia" registered in Ansible Galaxy.

``` yml
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "os_defaults.yml"
```

is it a bug? or I made something wrong.

I tried it with versions 1.6.3 and 1.5.3.

Best regards.
