### ISSUE TITLE
with_first_found iterator in include_vars does not find files inside vars directory of a role

### ISSUE THREAD

**Issue by micafer** [ansible/ansible#7788]
##### Issue Type:

Bug Report
##### Ansible Version:

Testes with 1.5.3 and 1.6.3
##### Environment:

“N/A”. 
##### Summary:

I tried to use the include_vars module with the with_first_found iterator option inside a role in this way:

``` yml
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_os_family }}.yml"
   - "os_defaults.yml"
```

but it does not find files inside vars directory of the role.
Is it a bug? Have I made something wrong?

If I set the whole path of the files, it works fine.

``` yml
- include_vars: "{{ item }}"
  with_first_found:
   - "/etc/ansible/roles/ganglia/vars/{{ ansible_os_family }}.yml"
   - /etc/ansible/roles/ganglia/vars/os_defaults.yml
```
##### Steps To Reproduce:

Create a role with some files in the role/vars directory: for example Debian.yml, RedHat.yml and another for the default values os_defaults.yml.

Include the include_vars module with the  with_first_found iterator:

``` yml
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_os_family }}.yml"
   - "os_defaults.yml"
```

Set the role in a playbook, and call the ansible-playbook command.
##### Expected Results:

TASK: [ganglia | include_vars {{item}}] ******************************\* 
ok: [158.42.105.24] => (item=RedHat.yml)
##### Actual Results:

TASK: [ganglia | include_vars {{item}}] ******************************\* 
failed: [158.42.105.24] => {"failed": true, "item": null}
msg: No source file given

FATAL: all hosts have already failed -- aborting
