### ISSUE TITLE
Unable to find value from ansible.cfg

### ISSUE THREAD

**Issue by jimboolio** [ansible/ansible#77929]
### Summary

When trying to run:

```- name: CHECK_CONFIG
  hosts: all
  become: yes

  tasks:
    - name: check config
      debug: msg="{{ lookup('config', 'DEFAULT_CALLBACK_ENABLED')}}"```

This shouldn't be in code block, but I don't see way to remove it
It throws an error: Unable to find setting DEFAULT_CALLBACK_ENABLED. module 'ansible.constants' has no attribute 'DEFAULT_CALLBACK_ENABLED'. module 'ansible.constants' has no attribute 'DEFAULT_CALLBACK_ENABLED'

### Issue Type

Bug Report

### Component Name

ansible.constants

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/myuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /home/myuser/.ansible/retry-files

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False

ssh:
___
control_path(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%r
host_key_checking(/etc/ansible/ansible.cfg) = False
pipelining(/etc/ansible/ansible.cfg) = True
scp_if_ssh(/etc/ansible/ansible.cfg) = True
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=30m

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

sh:
__
remote_tmp(/etc/ansible/ansible.cfg) = /tmp/.ansible-${USER}/tmp

VARS:
====
```

### OS / Environment

Fedora Linux 36 (Workstation Edition)

### Steps to Reproduce

/etc/ansible/ansible.cfg
```yaml (paste below)
[defaults]
callback_enabled = profile_tasks, timer
```

```yaml 
- name: CHECK_CONFIG
  hosts: all
  become: yes

  tasks:
    - name: check config
      debug: msg="{{ lookup('config', 'DEFAULT_CALLBACK_ENABLED')}}"```

### Expected Results

Ansible would grab the variables from config as it does out of the box on Debian 11

### Actual Results

```console
META: ran handlers

TASK [check config] ***************************************************************
task path: /home/myuser/Work/test/test.yml:6
fatal: [myhost]: FAILED! => {
    "msg": "Unable to find setting DEFAULT_CALLBACK_ENABLED. module 'ansible.constants' has no attribute 'DEFAULT_CALLBACK_ENABLED'. module 'ansible.constants' has no attribute 'DEFAULT_CALLBACK_ENABLED'"
}

PLAY RECAP ************************************************************************
myhost      : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
