### ISSUE TITLE
Simple playbook not finding a just installed collection

### ISSUE THREAD

**Issue by mimmus** [ansible/ansible#77937]
### Summary

Hi,
a simple playbook with a task from "community.general" collection fails if executed locally, even after:
` ansible-galaxy collection install community.general`

### Issue Type

Bug Report

### Component Name

community.general

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Jun 10 2021, 00:11:02) [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
usage: ansible-config [-h] [--version] [-v] {list,dump,view} ...
ansible-config: error: unrecognized arguments: -t all

$ ansible-config dump --only-changed
NO OUTPUT
```

### OS / Environment

Amazon Linux 2

### Steps to Reproduce

Example playbook:
```
---
- name: Playbook
  hosts: localhost

  tasks:
  - name: Check version of community.general
    ansible.builtin.debug:
      msg: "community.general version {{ lookup('community.general.collection_version', 'community.general') }}"
  - name: Create a file of 1k filled with null bytes
    community.general.filesize:
      path: /tmp/myfile
      size: 1k
```

### Expected Results

No errors

### Actual Results

```console
# ansible-playbook mim.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'community.general.filesize'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/mim.yaml': line 8, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      msg: "community.general version {{ lookup('community.general.collection_version', 'community.general') }}"
  - name: Create a file of 1k filled with null bytes
    ^ here
```

Commenting out the task with the collection module, it shows collection version:
```
TASK [Check version of community.general] *********************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "community.general version 5.0.1"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
