### ISSUE TITLE
Role Argument Validation: add examples for dicts and nested dicts in main/argument_specs.yml

### ISSUE THREAD

**Issue by freehck** [ansible/ansible#77964]
### Summary

Let's assume you have a dictionary like this:

```
cron_jobs:
  - name: "true"
    command: "true"
    hour: 2
    minute: 0
    skip: true
  - name: "schedule"
    command: "true"
    schedule: "0 2 * *  */2"
```

According to your [documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#specification-format) people shall write nested options in `meta/argument_specs.yml`

```
argument_specs:
  main:
    short_description: validation for params in tasks/main.yml
    options:
      cron_jobs:
        type: "list"
        required: true
        options:
          xxx:
            type: "str"
            required: true
```

But it doesn't work. I made about 20 attempts trying different possible ways to describe this list of dictionaries, but it doesn't validate elements at all.

In the example above the expected behaviour is a failed validation, because record `xxx` is not available in list elements.

I suppose that I could have mistaken in `argument_specs` because of missing examples. Would be cool, if you add more examples into your documentation.

### Issue Type

Documentation Report

### Component Name

https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#specification-format

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.5]
  config file = /Users/freehck/repos/git.freehck.com/devops/iac/ansible/ansible.cfg
  configured module search path = ['/Users/freehck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.8.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/freehck/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/opt/ansible/bin/ansible
  python version = 3.10.4 (main, Apr 26 2022, 19:42:59) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
You need to specify `elements` with `type: list`:
```yaml
argument_specs:
  main:
    short_description: validation for params in tasks/main.yml
    options:
      cron_jobs:
        type: "list"
        required: true
        elements: "dict"
        options:
          xxx:
            type: "str"
            required: true
```
If `type: list` has `options` and no `elements`, that should probably be an error, since `options` is just ignored and is probably not what was intended.

We should also add an example to the documentation for list options with suboptions and dict options with suboptions.
