### ISSUE TITLE
Feature request: list vars per host

### ISSUE THREAD

**Issue by varas** [ansible/ansible#7800]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.*
##### Environment:

N/A
##### Summary:

It would be great to have a way to define list variables per host, ideally on inventory file.
##### Steps To Reproduce:

N/A
##### Expected Results:

N/A
##### Actual Results:

N/A

**Comment by jimi-c** [comment]
What use would this provide versus putting the variables in to a host_vars file or dynamic inventory script?

**Comment by varas** [comment]
To be able to associate a structured data to a host.

For example:

Taking actions to certain list of vhosts each one associated to a host entry.

```
host1
  - vhosts:
    - path: /path/to/A
      name: vhostA
    - path: /path/to/B
      name: vhostB

host2
  - vhosts:
    - path: /path/to/C
      name: vhostC
```
