### ISSUE TITLE
Prompted multiple times for MFA code when using aws_ec2 inventory plugin as inventory source

### ISSUE THREAD

**Issue by apsamuel** [ansible/ansible#78031]
### Summary

When using the `aws_ec2`inventory module to execute ansible tasks against EC2 instances grouped by tag, I am facing an issue where I am being prompted (MFA codes) once for each member of a group. The result is running a task against a group with 4 active instances, which will prompt for MFA 4 times. My expectation is that it would request MFA once, and possibly cache the credential for reuse similar to how the AWS CLI does.

### Issue Type

Bug Report

### Component Name

aws_ec2

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.6]
  config file = /Users/aaronsamuel/devops/rearc/noop-etc/ansible/ansible.cfg
  configured module search path = ['/Users/aaronsamuel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/aaronsamuel/opt/anaconda3/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/aaronsamuel/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/aaronsamuel/opt/anaconda3/bin/ansible
  python version = 3.9.7 (default, Sep 16 2021, 08:50:36) [Clang 10.0.0 ]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

DEFAULT_HOST_LIST(/Users/aaronsamuel/devops/rearc/noop-etc/ansible/ansible.cfg) = ['/Users/aaronsamuel/devops/rearc/noop-etc/ansible/aws_ec2.yaml']
HOST_KEY_CHECKING(/Users/aaronsamuel/devops/rearc/noop-etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/Users/aaronsamuel/devops/rearc/noop-etc/ansible/ansible.cfg) = ['aws_ec2']

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/Users/aaronsamuel/devops/rearc/noop-etc/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/Users/aaronsamuel/devops/rearc/noop-etc/ansible/ansible.cfg) = False

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====%
```

### OS / Environment

OS:

```
❯ sw_vers
ProductName:    macOS
ProductVersion: 12.4
BuildVersion:   21F79
```

- silicon chip, using ansible from a rosetta i386 terminal.

### Steps to Reproduce

# ansible.cfg

```ini
[inventory]
enable_plugins = aws_ec2
```
# aws_ec2.yaml

```yaml
plugin: aws_ec2
cache: yes
regions:
  - us-west-2
  - us-east-1
keyed_groups:
  # Create a group (or groups) based on the value of a custom tag "ServiceName" and add them to a metagroup called "project"
  - key: tags['GroupName']
    prefix: service
filters:
  # All instances with their state as `running`
  instance-state-name: running
hostnames:
  - ip-address
include_filters:
- tag:Name:
  - 'ServiceName'
```

# command line
```sh
ANSIBLE_CACHE_PLUGIN=memory ANSIBLE_INVENTORY_CACHE_PLUGIN=memory ANSIBLE_CONFIG=./ansible.cfg AWS_PROFILE=myprofile ansible mygroup -a 'grep REGION myfile.txt' -u ec2-user --verbose --become --become-method=sudo
```

### Expected Results

I expect that the MFA prompt would happen once.

### Actual Results

```console
❯ ANSIBLE_CACHE_PLUGIN=memory ANSIBLE_INVENTORY_CACHE_PLUGIN=memory ANSIBLE_CONFIG=./ansible.cfg AWS_PROFILE=myprofile ansible mygroup -a 'grep REGION myfile' -u ec2-user --verbose --become --become-method=sudo
Using ansible.cfg as config file
Enter MFA code for arn:aws:iam::XXXXXXX:mfa/user@place: 
Enter MFA code for arn:aws:iam::XXXXXXX:mfa/user@place: 
Enter MFA code for arn:aws:iam::XXXXXXX:mfa/user@place: 
Enter MFA code for arn:aws:iam::XXXXXXX:mfa/user@place:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
