### ISSUE TITLE
Pacman package are not installed with community.general.pacman

### ISSUE THREAD

**Issue by PowaBanga** [ansible/ansible#78035]
### Summary

Using community.general.pacman, my packages are not installed

### Issue Type

Bug Report

### Component Name

community.general.pacman:

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/powabanga/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/powabanga/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, May 14 2022, 05:21:19) [GCC 12.1.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Archlinux

### Steps to Reproduce

```yaml (paste below)
---
- name: configuring my nano computers
  hosts: nano
  remote_user: root

  tasks:
    - name: installing and update packages
      community.general.pacman:
        name:
          - aurutils
          - base-devel
          - bash-completion
          - cups
          - docker
          - docker-compose
          - downgrade
          - fail2ban
          - htop
          - hplip
          - jenkins-lts
          - jre11-openjdk
          - mlocate
          - man-pages-fr
          - nmap
          - ntp
          - oh-my-zsh-git
          - pacman-contrib 
          - rsync
          - screen
          - sudo
          - syncthing
          - tree
          - vim
          - vim-youcompleteme-git
          - youtube-dl
          - wget
          - zsh
          - zsh-syntax-highlighting
        state: present
        update_cache: yes

  tasks:
    - name: enable services
      ansible.builtin.service:
        - docker
        - jenkins
        - syncthing@powabanga
        - ntp
      state: started
      enabled: yes

  tasks:
    - name: create user
      user: powabanga
      groups:
        - wheel
        - jenkins
        - docker

  tasks:
    - name: copy vimrc
      ansible.builtin.copy:
        src: /etc/vimrc
        dest: /etc/vimrc
        backup: yes
    - name: copy zshrc
      ansible.builtin.copy:
        src: /etc/vimrc
        dest: /etc/vimrc
        backup: yes
    - name: copy ssh/config to user powabanga
      ansible.builtin.copy:
        src: /home/powabanga/.ssh/config
        dest: /home/powabanga/.ssh/config
    - name: copy ssh/config to user root
      ansible.builtin.copy:
        src: /home/powabanga/.ssh/config
        dest: /root/.ssh/config
    - name: copy /etc/locale.conf
      ansible.builtin.copy:
        src: /etc/locale.conf
        dest: /etc/locale.conf
    - name: copy /etc/vconsole.conf
      ansible.builtin.copy:
        src: /etc/vconsole.conf
        dest: /etc/vconsole.conf
    - name: create localtime link
      ansible.builtin.file:
        src: /usr/share/zoneinfo/Europe/Brussels
        dest: /etc/localtime
        state: link
...

```

### Expected Results

I hope to install all my packages in the list on all machines, but it's not the case.
For exemple, nmap package is not installed on rpi4

### Actual Results

```console
https://pastebin.pl/view/ee265a47
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
