### ISSUE TITLE
file interprets paths with spaces incorrectly

### ISSUE THREAD

**Issue by dren-dk** [ansible/ansible#78052]
### Summary

This ansible task was run:

```
- name: Destroy the world
  file:
    path: /etc/systemd/system/ hp-tools.service
    state: absent
    notify: reload_systemctl

```
It was supposed to delete /etc/systemd/system/hp-tools.service, but a copy+paste error caused the extra space.

For some reason Ansible interpreted "/etc/systemd/system/ hp-tools.service" as the directory /etc/systemd/system/ rather than a file with an initial space in that directory: " hp-tools.service".

As you can imagine losing /etc/systemd/system from all of our systems caused some trouble and we think this is a bug in Ansible.

### Issue Type

Bug Report

### Component Name

file

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```yaml (paste below)
- name: Destroy the world
  file:
    path: /etc/systemd/system/ hp-tools.service
    state: absent
    notify: reload_systemctl

```

### Expected Results

I would expect the file called " hp-tools.service" in /etc/systemd/system/ to be deleted.

### Actual Results

```console
The directory /etc/systemd/system/ was deleted.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
We cannot reproduce this, do you have actual output that we can examine (preferably with -vvv)
need_info

**Comment by sivel** [comment]
My reproducer that shows this behavior does not happen.  It works as expected.

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - file:
        path: '{{ playbook_dir }}/system'
        state: directory

    - file:
        path: '{{ playbook_dir }}/system/{{ item }}'
        state: touch
      loop:
        - hp-tools.service
        - something.service
        - another.service

    - name: Destroy the world
      file:
        path: '{{ playbook_dir }}/system/ hp-tools.service'
        state: absent

    - assert:
        that:
          - playbook_dir ~ '/system' is directory

    - find:
        path: '{{ playbook_dir }}/system'
      register: files

    - debug:
        var: files.files
```
