### ISSUE TITLE
YAML merge operator generates warning

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#78062]
### Summary

When using YAML's `<<` operator, Ansible generates the following warning:

```
[WARNING]: While constructing a mapping from playbook.yml, line 10, column 9, found a duplicate dict key (path). Using last defined value only.
```

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0]
  config file = /home/gtirloni/.ansible.cfg
  ansible python module location = /home/gtirloni/tmp/ansible-2.13/lib/python3.10/site-packages/ansible
  ansible collection location = /home/gtirloni/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gtirloni/tmp/ansible-2.13/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
N/A
```

### OS / Environment

Fedora 36 with Python 3.10

### Steps to Reproduce

```yaml
- hosts: localhost
  vars:
    app1:
      jvm: &jvm_opts
        opts: '-Xms1G -Xmx2G'
        port: 1000
        path: /usr/lib/app1
    app2:
      jvm:
        <<: *jvm_opts
        path: /usr/lib/app2
```

Example taken from official docs: https://docs.ansible.com/ansible/latest/user_guide/playbooks_advanced_syntax.html#yaml-anchors-and-aliases-sharing-variable-values

### Expected Results

No warning is generated and the keys are merged as expected.

### Actual Results

```console
[WARNING]: While constructing a mapping from playbook.yml, line 10, column 9, found a duplicate dict key (path). Using last defined value only.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
