### ISSUE TITLE
ansible.builtin.apt_key adds keys to a deprecated location

### ISSUE THREAD

**Issue by ahrenstein** [ansible/ansible#78063]
### Summary

When adding non-PPA repositories to Ubuntu 22.04 (Jammy) using `ansible.builtin.apt_key` the key is added to a deprecated location (`/etc/apt/trusted.gpg`). I've seen a few reported issues where this was fixed for `ansible.builtin.apt_repository` but that only applies to PPAs which you can't always use (ie: Docker does not provide an official PPA)

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.6]
  config file = /Users/ahrenstein/.ansible.cfg
  configured module search path = ['/Users/ahrenstein/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.9.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/ahrenstein/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.4 (main, Apr 26 2022, 19:36:29) [Clang 13.1.6 (clang-1316.0.21.2)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
DEFAULT_REMOTE_USER(/Users/ahrenstein/.ansible.cfg) = root
HOST_KEY_CHECKING(/Users/ahrenstein/.ansible.cfg) = False

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/Users/ahrenstein/.ansible.cfg) = False
remote_user(/Users/ahrenstein/.ansible.cfg) = root

ssh:
___
host_key_checking(/Users/ahrenstein/.ansible.cfg) = False
remote_user(/Users/ahrenstein/.ansible.cfg) = root

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ansible Host: macOS 12.4 (ARM)
Target OS: Ubuntu 22.04 (x86_64)

### Steps to Reproduce

Deploy the Docker GPG key and repo
```yaml
- name: Add the Docker repository GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_distribution == 'Ubuntu'

- name: (Ubuntu) Add the Docker repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Refresh apt cache
  apt:
    update-cache: yes
```

Run `apt-get update` on the server

### Expected Results

apt cache refreshes without deprecation warnings

### Actual Results

```console
$ apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease          
Get:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease                     
Hit:5 https://download.docker.com/linux/ubuntu jammy InRelease            
Fetched 99.8 kB in 0s (247 kB/s)                    
Reading package lists... Done
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
found a simpler way, no need to de-armor, since apt can just use the key as is. #78206 add it to both apt and apt_key docs

**Comment by docapotamus** [comment]
@bcoca I can't run an update if the key isn't ran through `dearmor`. Is there something missing from the documentation?

With a straight download I get the following error:

```
W: GPG error: https://packages.fluentbit.io/debian/bullseye bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9F9DDC083888C1CD
E: The repository 'https://packages.fluentbit.io/debian/bullseye bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

If I manually follow the steps and `dearmor` the GPG key the update is successful.

**Comment by bcoca** [comment]
@docapotamus nothing that i know of, i tested it and 'it works for me'TM but I really don't know the inner workings nor conditions for success, I was just given the hint by a user, tested it and documented it. So if you find this to be unreliable I'll have to remove/update the docs to reflect this.

**Comment by docapotamus** [comment]
@bcoca sure thing, I'm simply trying to automate the install of the fluent:bit on all hosts. The docs reference `buster` but `bullseye` is also available through the depo. The install is on Debian Bullseye.

The block in question is:
```yaml
- name: setup repository
  block:
  - name: download key
    ansible.builtin.get_url:
      url: https://packages.fluentbit.io/fluentbit.key
      dest: /usr/share/keyrings/fluentbit-keyring.gpg

  - name: add source
    ansible.builtin.apt_repository:
      repo: "deb [arch=aarch64, signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/debian/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
      state: present

  - name: update cache
    ansible.builtin.apt:
      update_cache: true
```

The error during the run is:
```yaml
TASK [log_export : download key]
changed: [zookeeper-2]

TASK [log_export : add source]
fatal: [zookeeper-2]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:GPG error: https://packages.fluentbit.io/debian/bullseye bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9F9DDC083888C1CD, E:The repository 'https://packages.fluentbit.io/debian/bullseye bullseye InRelease' is not signed."}
```

This can be recreated as per the documentation by removing the `gpg --dearmor`

```sh
# curl https://packages.fluentbit.io/fluentbit.key > /usr/share/keyrings/fluentbit-keyring.gpg
# echo "deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/debian/bullseye bullseye main" >> /etc/apt/sources.list
$ apt update
...
Err:6 https://packages.fluentbit.io/debian/bullseye bullseye InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9F9DDC083888C1CD
Reading package lists... Done
W: GPG error: https://packages.fluentbit.io/debian/bullseye bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9F9DDC083888C1CD
E: The repository 'https://packages.fluentbit.io/debian/bullseye bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

By using the documented `--dearmor` this works fine.

```sh
# curl https://packages.fluentbit.io/fluentbit.key | gpg --dearmor > /usr/share/keyrings/fluentbit-keyring.gpg
```

**Comment by bcoca** [comment]
have you tried to follow my example and acutally use the `.asc` extension?

**Comment by Daryes** [comment]
@bcoca : sending the key files directly under `/etc/apt/trusted.gpg.d/`  with the .asc extension seems to do the trick, apt does not complain anymore.

There's a slight problem, still : the `get_url` module always download the file, as if `force` was set to true when no checksum is provided.
As detailed in my comment: https://github.com/ansible/ansible/issues/64016#issuecomment-1221522140

**Comment by geerlingguy** [comment]
Came here after https://github.com/geerlingguy/ansible-role-jenkins/pull/362 — will try the `.asc` trick.

**Comment by ahrenstein** [comment]
> Came here after [geerlingguy/ansible-role-jenkins#362](https://github.com/geerlingguy/ansible-role-jenkins/pull/362) — will try the `.asc` trick.
> 
> Edit - it works! Was not obvious from the given example that I needed to change the file extension, though. I'm updating some answers on Stack Exchange and will publish a blog post about it though, as that could help people get past this problem (not that this has to do with the OP so much, heh).

I'm looking forward to reading your blog post. FWIW this thread did result in a solve for my issue [short term](https://github.com/route1337/ansible-role-dockerhost/commit/72d8e994317a92d7adaf812e24625c3709552a67) but I would still like to see a simpler method similar to what we're all used to.

**Comment by bcoca** [comment]
apt_repository already uses gpg as a fallback if apt-key is not present, we are still unsure if we need to update apt_key to just be a gpg wrapper or deprecate it and eventually remove since the apt-key utility it mirrors is going away.

**Comment by docapotamus** [comment]
@bcoca thanks, that now works. I did follow your instructions but it wasn't obvious that the `.asc` extension had any meaning. I'm guessing it does an automatic dearmor if thats the extension.

**Comment by netsandbox** [comment]
Please note that `/etc/apt/trusted.gpg.d/` is the wrong location for the keys. Also `/usr/share/keyrings`, which is mentioned in other places is wrong, because this directory should only be used by keys distributed by apt packages.

The correct location is `/etc/apt/keyrings`, but keep in mind that this directory (will) only exists in Debian >= 12 and Ubuntu >= 22.04, so you have to create this directory on older OS versions.

Also `/etc/apt/keyrings` doesn't support 'ascii-armored' keys, so you have to be dearmor them.

See https://wiki.debian.org/DebianRepository/UseThirdParty

**Comment by geerlingguy** [comment]
@netsandbox - In that case, to respond to @bcoca's earlier comment, I think it would be essential to keep apt_key in the mix, and make it work to download and dearmor the key, otherwise we're going from one to at least two tasks, including a `command` to run the dearmor, and that just goes against all things ansible!

**Comment by bcoca** [comment]
@netsandbox we will probably end up with all 3 dirs as possible targets in order of preference. If the prefered does not exist, fallback to the others as they are known to work.

**Comment by netsandbox** [comment]
@bcoca I think `/usr/share/keyrings` should not be supported, because as Debian says in the Wiki:

>If future updates to the key will be managed by an apt/dpkg package as recommended below, then it SHOULD be downloaded into /usr/share/keyrings using the same filename that will be provided by the package. If it will be managed locally , it SHOULD be downloaded into /etc/apt/keyrings instead.

It is better to have `/usr/share/keyrings` for keys added by packages and `/etc/apt/keyrings` for manually (and Ansible) managed keys.

**Comment by bcoca** [comment]
@netsandbox yet we still need to work with older versions which actually did use that directory via apt-key, we cannot have it both ways, we either break backwards compatibility or adhere strictly to the latest spec. This project tends to err on the side of compatibility.

**Comment by heini** [comment]
@bcoca, what are the older versions you are talking about? the "signed-by" sources.list option is available since Stretch, so placing the keyrings into either /etc/apt/keyrings or /usr/share/keyrings should work there w/o problems. It won't work in Jessie or older, though...

**Comment by heini** [comment]
@netsandbox, yes, /usr/share/keyrings SHOULD be supported, since it may well be that an admin needs to place a key there before being able to install the package that then manages it. There can be an option not to update existing files...

**Comment by bcoca** [comment]
@heini i've updated apt_repository to handle the directories in order of preference (so it will depend on their existence on those versions), the question i have now is should i expand apt_repository to handle keys with all repos (not just ppa) and deprecate apt_key or move the functionality to module_utils and have both modules use it.

**Comment by heini** [comment]
@bcoca, I don't understand. What do mean by "order of preference"? Why not simply leave it to the user where to store each keyring?
I don't think that "directory exists" is a sufficient criterium. It doesn't tell whether a specific key needs to go into one dir or the other...

**Comment by bcoca** [comment]
we can add the option, fall back to the debian standard

**Comment by d-tork** [comment]
> 

@geerlingguy In your [Ansible Galaxy role](https://galaxy.ansible.com/geerlingguy/docker) you don't use the `signed-by` to point to the gpg key, which is how the official Docker install instructions do it. Is there a particular reason why this works, and does it avoid the `dearmor` and gpg/asc issue here?

**Comment by pietryszak** [comment]
Known and confirmed issue form Jun 15, ubuntu 22.04 apt_key adds keys to a deprecated location, and still exsist. Why is not fixed till today?

**Comment by fazlerabbi37** [comment]
Came here while trying to install `gcloud` CLI with Ansible. From `apt_key` example:

```
- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: somerepo |no apt key
      ansible.builtin.get_url:
        url: https://download.example.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/somerepo.asc

    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/myrepo.asc] https://download.example.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

```
Here, the `.asc` extension works as long as the key is in text format. It needs to be `.gpg` if it's in binary format, as mentioned [here](https://github.com/kubernetes/release/issues/1982#issuecomment-902342036). Maybe it is super obvious, but was not the case for me.

**Comment by heini** [comment]
Yeah, they also still use outdated instructions (using ASCII-armored files in /etc/apt/trusted.gpg.d, instead of gpg files in either /etc/apt/keyrings or /usr/share/keyrings).

Anyway, what about also supporting `deb822` (see man sources.list) style files? They're IMHO more intuitive to use...

**Comment by gdevenyi** [comment]
For those with a long list of keys to add, here's a snip which might be helpful:
```
- name: downoad apt keys to trusted.gpg.d                                                                                                                                                                         
  vars:                                                                                                                                                                                                           
    list_one:                                                                                                                                                                                                     
      - https://www.virtualbox.org/download/oracle_vbox.asc                                                                                                                                                       
      - https://dl-ssl.google.com/linux/linux_signing_key.pub                                                                                                                                                     
      - https://download.docker.com/linux/ubuntu/gpg                                                                                                                                                              
      - https://dl.winehq.org/wine-builds/winehq.key                                                                                                                                                              
      - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub                                                                                                                   
      - https://dl.xanmod.org/gpg.key                                                                                                                                                                             
      - https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg                                                                                                                          
      - https://xpra.org/xpra-2022.gpg                                                                                                                                                                            
    list_two:                                                                                                                                                                                                     
      - oracle_vbox.asc                                                                                                                                                                                           
      - google_linux_signing_key.asc                                                                                                                                                                              
      - docker.asc                                                                                                                                                                                                
      - wine.asc                                                                                                                                                                                                  
      - nvidia_cuda.asc                                                                                                                                                                                           
      - xanmod.asc                                                                                                                                                                                                
      - brave-browser-archive-keyring.gpg                                                                                                                                                                         
      - xpra-2022.gpg                                                                                                                                                                                             
  get_url:                                                                                                                                                                                                        
    url: "{{ item.0 }}"                                                                                                                                                                                           
    dest: "/etc/apt/trusted.gpg.d/{{ item.1 }}"                                                                                                                                                                   
  loop: "{{ list_one | zip(list_two) | list }}"   
```

**Comment by netsandbox** [comment]
@gdevenyi you are still using the wrong location `/etc/apt/trusted.gpg.d`.

It should be `/usr/share/keyrings` or `/etc/apt/keyrings`.
And there you must dearmor the `asc` keys.

**Comment by icezyclon** [comment]
I just through I'd share my own solution and ask for thoughts on it. It was inspired by a number of different snippets.
Importantly, I did not dearmor the keys (it seems to work well enough) and I wanted to use https for everything. I also only need the keys from the official Ubuntu keyservers but I am pretty sure the code could be adjusted to download from anywhere.

I added the following to a file called `add_repository.yml`:
```yml
- name: download gpg key {{ppa.key}} from ubuntu keyserver
  ansible.builtin.apt_key:
    id: "{{ ppa.fingerprint }}"
    keyserver: "hkps://keyserver.ubuntu.com"
    state: present
    keyring: /etc/apt/keyrings/{{ ppa.key }}.gpg
- name: add {{ ppa.key }} ppa source
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/{{ ppa.key }}.gpg] https://ppa.launchpadcontent.net/{{ ppa.launchpad_loc }}/ubuntu {{ ansible_distribution_release }} main
    state: present
    update_cache: true
```

I then call this code like so:
```yml
- name: add deadsnakes ppa repository
  include_tasks: "add_repository.yml"
  vars:
    ppa:
      key: "deadsnakes"
      launchpad_loc: "deadsnakes/ppa"
      fingerprint: "F23C5A6CF475977595C89F51BA6932366A755776"
```

Alternatively, I can run it in a loop like so:
```yml
- name: add all ppas at once
  include_tasks: "add_repository.yml"
  loop:
    - {
        key: "fish",
        launchpad_loc: "fish-shell/release-3",
        fingerprint: "59FDA1CE1B84B3FAD89366C027557F056DC33CA5",
      }
    - {
        key: "deadsnakes",
        launchpad_loc: "deadsnakes/ppa",
        fingerprint: "F23C5A6CF475977595C89F51BA6932366A755776",
      }
  loop_control:
    loop_var: ppa
```

I am running this on Ubuntu 22.04 with the official Ansible packages on both the host and control nodes. 

What are your thoughts, is this the preferred method for doing this?
