### ISSUE TITLE
[WARNING]: Updating cache and auto-installing missing dependency: python3-apt

### ISSUE THREAD

**Issue by araborg** [ansible/ansible#78071]
### Summary

ansible-playbook main-remote.yml -i inventory --private-key ansible2.pem 

PLAY [Exercise for setting up a web server in an EC] ***************************

TASK [Gathering Facts] *********************************************************
ok: [34.203.203.133]

TASK [setup : update apt packages.] ********************************************
[WARNING]: Updating cache and auto-installing missing dependency: python3-apt
fatal: [34.203.203.133]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get': b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

### Issue Type

Bug Report

### Component Name

python3-apt

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.6]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

AWS

### Steps to Reproduce

```yaml (paste below)
---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC   
  # Use the public IP if the VM is already created
  hosts: all
  # For Ubuntu instances, the user will be `ubuntu`
  # For Amazon LInux 2 instance, the user will be `ec2-user`
  # user: ubuntu
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup
```
ansible-playbook main-remote.yml -i inventory --private-key ansible2.pem 

### Expected Results

I expected it to return Ok

### Actual Results

```console
******
[WARNING]: Updating cache and auto-installing missing dependency: python3-apt
fatal: [34.203.203.133]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "[Errno 2] No such file or directory: b'apt-get': b'apt-get'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
34.203.203.133             : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
