### ISSUE TITLE
Using dest=/dev/null with get_url overwrites /dev/null

### ISSUE THREAD

**Issue by Xiol** [ansible/ansible#78093]
### Summary

We have a 'preflight checks' role that we run initially to check some basic assumptions about the servers we're deploying. One of these checks is to ensure the mirrors we need are accessible:

```yaml
- name: Check mirrors are accessible
  get_url:
    url: http://mirrors.acme.com/sites/archive.ubuntu.com/dists/devel/Release.gpg
    dest: /dev/null
    headers:
      user-agent: Preflight Checks
    timeout: 5
  ignore_errors: true
  changed_when: false
  register: mirrorcheck
```

We were using Ansible 2.8, where this check works fine and as expected - the contents downloaded is written to /dev/null and disappears into the ether.

We recently upgraded to Ansible 2.12, and this behaviour has changed. `get_url` now overwrites `/dev/null`, turning it into a normal file rather than a character device.

Before the above task runs:

```
# ls -l  /dev/null
crw-rw-rw- 1 root root 1,  3 Jun 20 11:28 /dev/null
```

After the task runs:

```
# ls -l /dev/null
-rw-rw-rw- 1 root root 0 Jun 20 11:35 /dev/null
```

This causes a whole load of unrelated and difficult to debug problems on the host because /dev/null no longer works as expected.

I have changed the above task to now write to a file in `/tmp` instead, which has worked around the problem for us.

I have not been able to find any documentation that suggests this is an expected change between Ansible 2.8 and 2.12.

I do not know if this affects other modules that write to files.

We are running Ansible inside an execution environment with AWX.

### Issue Type

Bug Report

### Component Name

get_url

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

bash-4.4# ansible-config dump --only-changed -t all

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Target OS: Ubuntu 20.04

Ansible host is an execution environment running on AWX, using `quay.io/ansible/ansible-runner:stable-2.12-latest` as the base image and installing a handful of collections and the `docker` pip package.

### Steps to Reproduce

On target host, check current state of `/dev/null` with `ls -l /dev/null`

Execute task:

```yaml (paste below)
- name: Check mirrors are accessible
  get_url:
    url: https://www.google.com
    dest: /dev/null
    headers:
      user-agent: Preflight Checks
    timeout: 5
  ignore_errors: true
  changed_when: false
  register: mirrorcheck
```

Check `/dev/null` again.

### Expected Results

When destination is /dev/null (or any character device for that matter?), the contents should be written to the device, rather than the device itself being overwritten with the contents.

### Actual Results

```console
/dev/null is overwritten by get_url, and is no longer a character device.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/get_url.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/get_url.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by Xiol** [comment]
@s-hertel Yes, it will be running as root. I appreciate that task as a standalone thing doesn't need root permissions, but we immediately launch into applying several roles after the preflight one, and it's an unnecessary complication for us to drop permissions for a handful of tasks.

**Comment by bcoca** [comment]
I don't see how this ever worked other than the way you state, this would either replace `/dev/null ` or error out on lack of permissions to do so.

I've looked at current and past code and don't see anywhere where we treat or treated `/dev/null` in a special way.

I would suggest using the `uri` module or lookup to do such a test as you don't need to write to a file (nor even transfer most of the content of the request).

```
- name: Check mirrors are accessible
  uri:
    url: https://www.google.com
    return_content: false
    headers:
      user-agent: Preflight Checks
    timeout: 5
  ignore_errors: true
  changed_when: false
  register: mirrorcheck
```
