### ISSUE TITLE
Implement allow_change_held_packages for remove

### ISSUE THREAD

**Issue by setpill** [ansible/ansible#78131]
### Summary

I need to fully purge and then reinstall a number of packages that also have their versions pinned. I was expecting the argument `allow_change_held_packages` to work, but apparently it's only implemented for the `install` side, not the `remove` side.

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information

```yaml (paste below)
    - name: Remove foo
      ansible.builtin.apt:
        allow_change_held_packages: yes
        state: absent
        name:
          - foo
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
