### ISSUE TITLE
Module known_hosts: Allow specifying a fingerprint instead of a full remote SSH key

### ISSUE THREAD

**Issue by ppetr** [ansible/ansible#78151]
### Summary

Adding a set of remote public keys to `known_hosts` is relatively [convoluted procedure](https://serverfault.com/a/971922/135336). For example for GitHub:

1. Run `ssh-keyscan -t rsa github.com >keyfile` (and similarly for other types).
2. Compute the key's fingerprints with `ssh-keygen -lf keyfile`
3. Verify the fingerprints against https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
4. Invoke the module to import the verified keys.

I believe it would be very useful to add the above functionality to the module itself. See "Additional information" for an example.

### Issue Type

Feature Idea

### Component Name

known_hosts

### Additional Information

```yaml (paste below)
- name: Specify known hosts just by its keys' fingerprints.
  ansible.builtin.known_hosts:
    name: github.com
    fingerprint:
    - type: rsa
      hash: SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
    - type: ecdsa
      hash: SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM
    - type: ed25519
      hash: SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
    path: /etc/ssh/ssh_known_hosts
    state: present
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
