### ISSUE TITLE
Unable to Define Multiple Host Groups in Zabbix with Ansible

### ISSUE THREAD

**Issue by opulasli414** [ansible/ansible#78182]
### Summary

I am trying to create Zabbix User Group with Ansible. Since usually user groups rights are defined with multiple host groups, I am trying the same with Ansible. However my playbook throws error when I try to write multipe host groups under host group section in playbook.

### Issue Type

Bug Report

### Component Name

community.zabbix.zabbix_usergroup

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ubuntu

### Steps to Reproduce

```yaml (paste below)
---
- name: Create User Group in Zabbix
  community.zabbix.zabbix_usergroup:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    name: "{{ item.name }}"
    rights:
       - host_group: "{{ item.host_group }}"
         permission: read-only
       - host_group: "{{ item.host_group }}"
         permission: read-write
    state: present
  with_items: '{{ user_groups }}'
```

```
user_groups:
  - name:  Admins
    host_group:
     - MyTestingHostGroup101
     - MyTestingHostGroup102
  - name: Users
    host_group:
     - MyTestingHostGroup106
     - MyTestingHostGroup107
```

above I shared the tasks/main.yaml and vars/main.yaml files.

### Expected Results

I am expecting it to work without problem and create user group with multiple host groups permissions.

### Actual Results

```console
failed: [localhost] (item={'name': '', 'host_group': ['MyTestingHostGroup101', 'MyTestingHostGroup102']}) => {"ansible_loop_var": "item", "changed": false, "item": {"host_group": ["MyTestingHostGroup101", "MyTestingHostGroup102"], "name": ""}, "msg": "Host group not found: ['MyTestingHostGroup101', 'MyTestingHostGroup102']"}
failed: [localhost] (item={'name': '', 'host_group': ['MyTestingHostGroup106', 'MyTestingHostGroup107']}) => {"ansible_loop_var": "item", "changed": false, "item": {"host_group": ["MyTestingHostGroup106", "MyTestingHostGroup107"], "name": ""}, "msg": "Host group not found: ['MyTestingHostGroup106', 'MyTestingHostGroup107']"}

the error is exactly like above. I just removed the sensitive data from names section.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
