### ISSUE TITLE
Git Module with Archive not idempotent

### ISSUE THREAD

**Issue by ares-b** [ansible/ansible#78190]
### Summary

Hello,

I'm using ansible.builtin.git to clone a remote repository from github and archive it using the `archive` parameter.

The Clone of the repository is idempotent **but** the archive IS NOT :/

### Issue Type

~Bug  Report~
Feature Idea

### Component Name

git

### Ansible Version

```console
ansible [core 2.12.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ares/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ares/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ares/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ares/.local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
nothing special
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

```
---

- name: test my new module
  hosts: all
  tasks:
    - name: Clone repo
      ansible.builtin.git:
        repo: "https://github.com/ares-b/openziti-ansible-collection.git"
        dest: "/tmp/git_idem"
        version: "main"
        archive: "test.tar.gz"
      delegate_to: "localhost"
      delegate_facts: false
      run_once: true

```

### Expected Results

The archive `test.tar.gz` shouldn't be re-created when i run the playbook twice and nothing has changed on remote.

### Actual Results

```console
The archive `test.tar.gz` is generated twice.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
