### ISSUE TITLE
apt_repository enhancement feature on removal source

### ISSUE THREAD

**Issue by moscaluc** [ansible/ansible#78199]
### Summary

I think it would be very useful to have the following behavior of apt_repository when we need to remove a repo source.
```
- name: Remove a repository
   apt_repository:
     filename: my_super_personal_repo
     state: absent
```
While for now it is **mandatory** to pass the `repo` parameter...
I know we can configure many repo in one file, nevertheless we maybe need to remove all these repos in one step.
Currently I need to do it with the `ansible.builtin.file` module.

Moreover, with the new DEB822 format, it will maybe easier to remove one file than giving all parameters to be sure that we are removing only the good repos.

### Issue Type

Feature Idea

### Component Name

apt_repository

### Additional Information

```
- name: Remove a repository
   apt_repository:
     filename: my_super_personal_repo
     state: absent
```
would be equivalent to
```
- name: Remove a repository
   file:
     path: /etc/apt/sources.list.d/my_super_personal_repo.list
     state: absent
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
