### ISSUE TITLE
adding 2 lists in 2.13.x seems to fail

### ISSUE THREAD

**Issue by djdanielsson** [ansible/ansible#78202]
### Summary

I am trying to create a list by looping through a var and pulling out items that I want and setting it as a fact. This code works in 2.12.x and below but when I upgraded to 2.13.x it fails.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
ansible [core 2.13.1]
  config file = /home/ddaniels/workspace/lab_stuff/controller_config/ansible.cfg
  configured module search path = ['/home/ddaniels/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ddaniels/workspace/ansible-latest/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/ddaniels/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ddaniels/workspace/ansible-latest/bin/ansible
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_HOST_LIST(/home/ddaniels/workspace/lab_stuff/controller_config/ansible.cfg) = ['/home/ddaniels/workspace/lab_stuff/controller_config/inventory']
```

### OS / Environment

Fedora 36

### Steps to Reproduce

```yaml (paste below)

- hosts: all
  connection: local
  vars:
  controller_organizations:
    - name: iac
      galaxy_credentials:
        - ah_certified
        - ah_community
        - ah_published
    - name: Default
      state: absent
  tasks:
    - name: create organizations without credentials
      ansible.builtin.set_fact:
        orgs_no_creds: "{{ orgs_no_creds | default([]) }} + [{ 'name' : '{{ item.name }}'}]"
      loop: "{{ controller_organizations }}"
      when:
        - controller_organizations is defined
        - (item.state | default('Present')) != 'absent'

    - name: print out custom fact
      ansible.builtin.debug:
        var: orgs_no_creds

```

### Expected Results
when run on 2.12.x
```console
TASK [create organizations without credentials] **********************************************************************************************************************************************************************************************
task path: /home/ddaniels/workspace/lab_stuff/controller_config/playbooks/playbooks.yml:11
ok: [192.168.122.122] => (item={'name': 'iac', 'galaxy_credentials': ['ah_certified', 'ah_community', 'ah_published']}) => {"ansible_facts": {"orgs_no_creds": [{"name": "iac"}]}, "ansible_loop_var": "item", "changed": false, "item": {"galaxy_credentials": ["ah_certified", "ah_community", "ah_published"], "name": "iac"}}
skipping: [192.168.122.122] => (item={'name': 'Default', 'state': 'absent'})  => {"ansible_loop_var": "item", "changed": false, "item": {"name": "Default", "state": "absent"}, "skip_reason": "Conditional result was False"}

TASK [print out custom fact] *****************************************************************************************************************************************************************************************************************
task path: /home/ddaniels/workspace/lab_stuff/controller_config/playbooks/playbooks.yml:19
ok: [192.168.122.122] => {
    "orgs_no_creds": [
        {
            "name": "iac"
        }
    ]
}
```

### Actual Results

```console
TASK [create organizations without credentials] **********************************************************************************************************************************************************************************************
task path: /home/ddaniels/workspace/lab_stuff/controller_config/playbooks/playbooks.yml:11
ok: [192.168.122.122] => (item={'name': 'iac', 'galaxy_credentials': ['ah_certified', 'ah_community', 'ah_published']}) => {"ansible_facts": {"orgs_no_creds": "[] + [{ 'name' : 'iac'}]"}, "ansible_loop_var": "item", "changed": false, "item": {"galaxy_credentials": ["ah_certified", "ah_community", "ah_published"], "name": "iac"}}
skipping: [192.168.122.122] => (item={'name': 'Default', 'state': 'absent'})  => {"ansible_loop_var": "item", "changed": false, "item": {"name": "Default", "state": "absent"}, "skip_reason": "Conditional result was False"}

TASK [print out custom fact] *****************************************************************************************************************************************************************************************************************
task path: /home/ddaniels/workspace/lab_stuff/controller_config/playbooks/playbooks.yml:19
ok: [192.168.122.122] => {
    "orgs_no_creds": "[] + [{ 'name' : 'iac'}]"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sean-m-sullivan** [comment]
@djdanielsson I found the answer, its removing the }} + {{ and putting the + inside the curlies
```
    - name: create organizations without credentials
      ansible.builtin.set_fact:
        orgs_no_creds: "{{ orgs_no_creds | default([]) + [{ 'name' : item.name }] }}"
      loop: "{{ controller_organizations }}"
```
