### ISSUE TITLE
I use the ansible-template model and sometimes i get a directory

### ISSUE THREAD

**Issue by ding77** [ansible/ansible#78215]
### Summary

Hello:
    I use the ansible template model to render my own configuration files, and sometimes generate a folder. Because the results of multiple executions are inconsistent, I can't find out the problem. Moreover, if I do the same operation on three machines, there will be a situation where one or two machines are OK but the other machine is wrong

Machie-1:
[root@br-apm-001 ..]# cd /data/br/conf/kafka/
[root@br-apm-001 kafka]# ll
total 4
-rwxr-xr-x 1 bonree bonree 1382 Jul  7 15:58 server.properties

Machine-2 
[root@br-apm-002 ~]# cd /data/br/conf/kafka/
[root@br-apm-002 kafka]# ll
total 4
drwxr-xr-x 2 root root 4096 Jul  7 15:58 server.properties
[root@br-apm-002 kafka]# cd server.properties/
[root@br-apm-002 server.properties]# ll
total 4
-rwxr-xr-x 1 bonree bonree 1382 Jul  7 15:58 server.properties.template

Under what circumstances do different results occur at the same time and on different machines？

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
[root@br-apm-001 kafka]# ansible --version
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

[root@br-apm-001 kafka]# uname -a
Linux br-apm-001 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml 
- name: create kafka base dir
  file:
    path: "{{ br.root }}/{{ item }}/kafka"
    state: directory
    owner: "{{ br_user }}"
    group: "{{ br_group }}"
    mode: 0755
  ignore_errors: true
  with_items: "{{ br.dir }}"

- name: create config for kafka
  template:
    backup: true
    src: server.properties.template
    dest: "{{ br.root }}/conf/kafka/server.properties"
    owner: "{{ br_user }}"
    group: "{{ br_group }}"
    mode: 0755

- name: copy kafka package
  unarchive:
    src: "{{ kafka.tar }}"
    dest: "/tmp/"
    owner: "{{ br_user }}"
    group: "{{ br_group }}"

- name: exec load kafka images
  shell: "docker load < /tmp/{{ kafka.image_file }}"

- name: is exist or not
  debug:
    msg: "file exist"
  when: "testdir is exists"

- name: is file or not
  debug:
    msg: "{{testdir}} is file"
  when: "testdir is file"

- name: running container
  ignore_errors: true
  shell: >
    docker run -it
    --name {{ kafka.name }}
    --restart=on-failure:3
    --net=host
    -e KAFKA_HEAP_OPTS={{ kafka.java_opt }}
    -v {{ br.root }}/logs/kafka:/data/br/base/kafka/logs
    -v {{ br.root }}/data/kafka:/data/br/base/kafka/kafka-logs
    -v {{ br.root }}/conf/kafka/server.properties:/data/br/base/kafka/config/server.properties
    -d {{ kafka.image_name }}

- name: wait for kafka port
  wait_for:
    host: "{{ hostvars[item].ansible_ssh_host }}"
    port: "{{ kafka.port }}"
  delegate_to: "{{ item }}"
  run_once: true
  with_items: "{{ groups.kafka }}"

- name: delete unused file
  file: path=/tmp/{{ kafka.image_file }} state=absent
  ignore_errors: true

- name: echo success
  debug:
    msg: kafka start success
  delegate_to: localhost
  run_once: true
```

### Expected Results

And i get the error from the play
```bash
fatal: [br-apm-002]: FAILED! => {"changed": true, "cmd": "docker run -it --name br-kafka --restart=on-failure:3 --net=host -e KAFKA_HEAP_OPTS='-Xms1024m -Xmx1024m' -v /data/br/logs/kafka:/data/br/base/kafka/logs -v /data/br/data/kafka:/data/br/base/kafka/kafka-logs -v /data/br/conf/kafka/server.properties:/data/br/base/kafka/config/server.properties -d ibr.cc/kafka/kafka:2.11-0.10.2.2\n", "delta": "0:00:00.901373", "end": "2022-07-07 15:58:51.033778", "msg": "non-zero return code", "rc": 125, "start": "2022-07-07 15:58:50.132405", "stderr": "docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/data/br/conf/kafka/server.properties\\\\\\\" to rootfs \\\\\\\"/data/br/docker/overlay2/f82812c42be589fdc48bbb01b899f3fbbd9279d9eb866fd4828b2ef17009bf90/merged\\\\\\\" at \\\\\\\"/data/br/docker/overlay2/f82812c42be589fdc48bbb01b899f3fbbd9279d9eb866fd4828b2ef17009bf90/merged/data/br/base/kafka/config/server.properties\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.", "stderr_lines": ["docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/data/br/conf/kafka/server.properties\\\\\\\" to rootfs \\\\\\\"/data/br/docker/overlay2/f82812c42be589fdc48bbb01b899f3fbbd9279d9eb866fd4828b2ef17009bf90/merged\\\\\\\" at \\\\\\\"/data/br/docker/overlay2/f82812c42be589fdc48bbb01b899f3fbbd9279d9eb866fd4828b2ef17009bf90/merged/data/br/base/kafka/config/server.properties\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type."], "stdout": "526998ed057e4e740bab18a734a250e0c6657aa30502881cb58794d58a882390", "stdout_lines": ["526998ed057e4e740bab18a734a250e0c6657aa30502881cb58794d58a882390"]}
```

### Actual Results

```console
## Machie-1


[root@br-apm-001 ..]# cd /data/br/conf/kafka/
[root@br-apm-001 kafka]# ll
total 4
-rwxr-xr-x 1 bonree bonree 1382 Jul  7 15:58 server.properties

## Machine-2 
```bash
[root@br-apm-002 ~]# cd /data/br/conf/kafka/
[root@br-apm-002 kafka]# ll
total 4
drwxr-xr-x 2 root root 4096 Jul  7 15:58 server.properties
[root@br-apm-002 kafka]# cd server.properties/
[root@br-apm-002 server.properties]# ll
total 4
-rwxr-xr-x 1 bonree bonree 1382 Jul  7 15:58 server.properties.template
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
