### ISSUE TITLE
ansible flush_handlers how to use with tags

### ISSUE THREAD

**Issue by zerotocode398** [ansible/ansible#78252]
### Summary

How ansible in -meta: flush_handlers Using tags when handlers,Tag is configured, but it doesn't work

### Issue Type

Bug Report

### Component Name

yum

### Ansible Version

```console
ansible [core 2.13.1]
```

### Configuration

```console
[defaults]
hostfile       = inventory/test01/hosts
inventory      = inventory/test01/hosts
library        = /usr/share/ansible:playbooks/library
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks = 5
poll_interval  = 15
sudo_user      = root
transport      = smart
remote_port    = 22
host_key_checking = False
sudo_exe = sudo
timeout = 10
module_name = shell
retry_files_enabled = False
any_errors_fatal = True
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins:playbooks/filter_plugins
roles_path    = playbooks/roles
deprecation_warnings = False
gathering = smart
gather_timeout = 3600
fact_caching =jsonfile
fact_caching_connection = /tmp/ansible_fact_cache
callback_whitelist = timer, profile_tasks
log_path = /var/log/ansible.log
[paramiko_connection]
[ssh_connection]
pipelining = True
[accelerate]
```

### OS / Environment

Linux app1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

【Handlers】-> 【main.yml】
```yaml (paste below)
---
- name: add {{ role_name }}
  supervisorctl:
    name: "{{ role_name }}"
    state: present

- name: restart {{ role_name }}
  supervisorctl:
    name: "{{ role_name }}"
    state: restarted

- name: add run_rq_worker
  supervisorctl:
    name: thanos-rq-worker
    state: present

- name: restart run_rq_worker
  supervisorctl:
    name: thanos-rq-worker
    state: restarted
```
【tasks】-> 【main.yml】
```yaml
- name: Template thanos supervisor conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    mode: 0755
  with_items:
    - { src: "{{ role_name }}.ini.j2", dest: "/etc/supervisord.d/{{ role_name }}.ini" }
  notify:
    - add {{ role_name }}
    - restart {{ role_name }}
    - add run_rq_worker
    - restart run_rq_worker

- meta: flush_handlers
```

### Expected Results

[root@app1 star]# ansible-playbook -v playbooks/install_thanos.yml --list-tags
Using /root/operation/star/ansible.cfg as config file
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: Found both group and host with same name: local

playbook: playbooks/install_thanos.yml

  play #1 (thanos): Install thanos	TAGS: []
      TASK TAGS: [restart_service]

### Actual Results

```console
[root@app1 star]# ansible-playbook -v playbooks/install_thanos.yml -t "restart_service"
Using /root/operation/star/ansible.cfg as config file
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
[WARNING]: Found both group and host with same name: local

PLAY [Install thanos] ******************************************************************************************************************************************************

TASK [thanos : meta] *******************************************************************************************************************************************************
Wednesday 13 July 2022  17:09:31 +0800 (0:00:00.047)       0:00:00.047 ******** 

PLAY RECAP *****************************************************************************************************************************************************************

Playbook run took 0 days, 0 hours, 0 minutes, 0 seconds
Wednesday 13 July 2022  17:09:31 +0800 (0:00:00.044)       0:00:00.091 ******** 
=============================================================================== 
thanos : meta ------------------------------------------------------------------------------------------------------------------------------------------------------- 0.04s
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
