### ISSUE TITLE
Add an ansible_firewall_mgr runtime variable to make adding platform appropriate firewall rules easier.

### ISSUE THREAD

**Issue by ciphernaut-rh** [ansible/ansible#78251]
### Summary

Add an `ansible_firewall_mgr` runtime variable to make adding platform appropriate firewall rules easier.

presently, designing playbook to run on multiple distributions means needing to detect the firewall types being used manually.  This can be cumbersome and feels like reinventing the wheel.  An analogue to this issue would have been needing to detect which system service manager was being used before `ansikble_service_mgr` was available.

### Issue Type

Feature Idea

### Component Name

get_facts

### Additional Information

```yaml
  - name: open custom port 10001 firewalld
    firewalld:
      port: 10001/tcp
      permanent: yes
      state: enabled
    when: ansible_firewall_mgr == 'firewalld'

  - name: open custom port 10001 ufw
    ufw:
      rule: allow
      port: 10001
      proto: tcp
    when: ansible_firewall_mgr == 'ufw'

# and so on for nftables, classic iptables, and BSD's pf and all of its variants
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
