### ISSUE TITLE
Support git partial clones

### ISSUE THREAD

**Issue by amirh** [ansible/ansible#78267]
### Summary

Currently the Ansible builtin git module does not make it possible to pass a `--filter` argument to the `git clone` command.

This is needed for large repositories that want to leverage git [partial clones](https://git-scm.com/docs/partial-clone).

This can potentially be solved by either adding a `filter` parameter which when set its value will be used as the value for `--filter`.

Another alternative would be to add a key for any extra arguments to pass to the `git clone` command.

### Issue Type

Feature Idea

### Component Name

git

### Additional Information

```yaml
- name: Blobless checkout
  git:
    repo: 'https://foosball.example.org/path/to/repo.git'
    dest: /srv/checkout
    filter: 'blob:none'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
