### ISSUE TITLE
vmware_guest module fails to set static IP during Windows Server VM deployment

### ISSUE THREAD

**Issue by lbp-code** [ansible/ansible#78274]
### Summary

When using the module 'vmware_guest' to clone and customize a Windows Server 2019 VM, the process fails to set a static IP address. The new VM is deployed as DHCP.

The module configuration also calls a _VM Customization Specification_. That works perfectly, the new Windows Server VM is enrolled into AD as part of that _VM Customization Specification_.

This playbook is tested in 3 different vCenter servers in 3 different datacenters. All vCenters servers and ESXi hosts have the same versions.

I see the problem was also reported in the issue https://github.com/ansible/ansible/issues/38715, but it also says that it was fixed in Ansible 2.7.7
In my scenario, the issue is also reproducible in Ansible 2.9.6

Is there something special to be configured in the Windows Server template that I should be aware of?

As I checked here --> http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf the customization should be possible in our scenario.

By the way, the same playbook used to target the same 3 datacenters but used for deploying CentOS 7 and Ubuntu 20.04 works perfectly. It can set the new VMs with static IP address. 

Thanks in advance

### Issue Type

Bug Report

### Component Name

vmware_guest

### Ansible Version

```console
$ ansible --version
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/opt/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ansible is executed on Ubuntu 20.04

vCenter Server 6.7.0 build 19299595
VMware ESXi 6.7.0 build 18828794
VM to deploy and customize is Windows Server Standard 2019

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  remote_user: ansible
  become: no
  gather_facts: yes

  vars_files:
    - vars/vcenter_creds.yml

  tasks:
    - name: Clone a virtual machine from Windows template and customize - STATIC IP
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        datastore: "{{ vcenter_datastore }}"
        folder: "/{{ vcenter_datacenter }}/vm/{{ vm_folder }}"
        template: "{{ vm_template }}"
        name: "{{ vm_name }}"
        state: poweredon
        convert: thin
        force: yes
        networks:
          - name: '{{ vm_portgroup }}'
            type: static
            ip: "{{ vm_ip_address }}"
            netmask: "{{ vm_netmask }}"
            gateway: "{{ vm_gateway }}"
            allow_guest_control: yes
            start_connected: yes
            dns_servers:
              - "{{ vm_dns1 }}"
              - "{{ vm_dns2 }}"
              - "{{ vm_dns3 }}"
        wait_for_ip_address: yes
        customization_spec: FSD-WindowsServer2019-2022
        wait_for_customization: yes
        annotation: "VM created by {{ vcenter_username }} on {{ ansible_date_time.date }} at {{ ansible_date_time.time }} {{ ansible_date_time.tz }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpus }}"
          num_cpu_cores_per_socket: 2
          nested_virt: yes
      delegate_to: localhost
```

### Expected Results

It is expected the newly deployed Windows Server VM to have a fixed/static IP address

### Actual Results

```console
No errors output
VM has DHCP setting instead of the defined static IP
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
