### ISSUE TITLE
Ansible 'package' module cannot handle local .deb packages

### ISSUE THREAD

**Issue by FF186** [ansible/ansible#78289]
### Summary

When I try to install a local `.deb` package on my Ubuntu/Debian servers I get error that the package cannot be found. I find this strange since `package` is able to install `.rpm` packages.

### Issue Type

Bug Report

### Component Name

package

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.5]
```

### OS / Environment

Ubuntu 18.04

### Steps to Reproduce

```yaml (paste below)
- name: Install
  ansible.builtin.package:
    name: "/tmp/package.deb"
    state: present
  become: true
```

### Expected Results

To install package.

### Actual Results

```console
`FAILED! => {"changed": false, "msg": "No package matching '/tmp/XXXX.deb' is available"}`
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
