### ISSUE TITLE
set_fact: adding lists no longer working in 2.13

### ISSUE THREAD

**Issue by johnbui423** [ansible/ansible#78286]
### Summary

Adding lists in the following way is no longer supported by `set_fact` in ansible 2.13:

```
set_fact:
        sum_list: "{{ list1 }} + {{ list2 }}"
```

This used to work fine in older versions.

EDIT: while preparing this issue, I found that there seems to be a (failing) integration test for this: https://github.com/ansible/ansible/blob/stable-2.13/test/integration/targets/jinja2_native_types/test_concatentation.yml - although I cannot access its results.

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]
  config file = /home/ansible/ansible.cfg
  configured module search path = ['/home/ansible/library']
  ansible python module location = /usr/local/share/venv/test/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/share/venv/test/bin/ansible
  python version = 3.8.11 (default, Sep  1 2021, 12:33:46) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Tested on CentOS 7

### Steps to Reproduce

```yaml (paste below)
---

- hosts: localhost

  tasks:

    - name: Init list1
      set_fact:
        list1: [ '1' ]

    - name: Init list2
      set_fact:
        list2: [ '2' ]

    - name: Sum lists - method 1 - OK
      set_fact:
        sum_list: "{{ list1 + list2 }}"

    - name: Sum lists - method 2 - NOK
      set_fact:
        sum_list: "{{ list1 }} + {{ list2 }}"
```

### Expected Results

I expected the second method to return the same output as the first method - as in older ansible versions. Instead it returns `"sum_list": "['1'] + ['2']"` for the second method.

### Actual Results

```console
$ ansible-playbook test_sum_list.yml -vvv
ansible-playbook [core 2.13.1]
[..]
TASK [Init list1] *********************************************************************************************************
task path: /home/ansible/test_sum_list.yml:7
ok: [localhost] => {
    "ansible_facts": {
        "list1": [
            "1"
        ]
    },
    "changed": false
}

TASK [Init list2] *********************************************************************************************************
task path: /home/ansible/test_sum_list.yml:11
ok: [localhost] => {
    "ansible_facts": {
        "list2": [
            "2"
        ]
    },
    "changed": false
}

TASK [Sum lists] **********************************************************************************************************
task path: /home/ansible/test_sum_list.yml:15
ok: [localhost] => {
    "ansible_facts": {
        "sum_list": [
            "1",
            "2"
        ]
    },
    "changed": false
}

TASK [Multi sum lists - NOK] **********************************************************************************************
task path: /home/ansible/test_sum_list.yml:19
ok: [localhost] => {
    "ansible_facts": {
        "sum_list": "['1'] + ['2']"
    },
    "changed": false
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
