### ISSUE TITLE
mysql_db: problem with zeroes in database name

### ISSUE THREAD

**Issue by imThief** [ansible/ansible#78282]
### Summary

mysql_db replaces all zeroes with asterisks in database name when processes it. There is no problems with any other digits. {% raw %} block or literal notation doesn't helps.

### Issue Type

Bug Report

### Component Name

mysql_db

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fox/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/user/.ssh/id_rsa
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = user
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles', '/etc/ansible/dev', '/etc/ansible/servers', '/etc/ansible/services']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False
remote_user(/etc/ansible/ansible.cfg) = user

ssh:
___
host_key_checking(/etc/ansible/ansible.cfg) = False
private_key_file(/etc/ansible/ansible.cfg) = ~/.ssh/id_rsa
remote_user(/etc/ansible/ansible.cfg) = user

HTTPAPI:
=======

INVENTORY:
=========
LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
vars:
  data:
    database:
      name: 'dump_000'
      source: 'dump-000.sql'
      host: 172.17.0.1
      login_user: root
      login_pwd: 123
tasks:
  - name: Verifying database
    become: yes
    mysql_db:
      name: "{{ item.database.name }}"
      state: present
      encoding: utf8
      login_unix_socket: "{{ mysql_socket }}"
      login_user: "{{ item.database.login_user }}"
      login_password: "{{ item.database.login_pwd }}"
      config_file: /dev/null
    loop: "{{ data }}"
    loop_control:
      label: "Processing database {{ item.database.name|d('<None>') }}"

```

### Expected Results

```console
changed: [localhost] => (item=Processing database dump_000) => changed=true
  ansible_loop_var: item
  db: dump_000
  db_list:
  - dump_000
```

### Actual Results

```console
# Actual results
changed: [localhost] => (item=Processing database dump_000) => changed=true
  ansible_loop_var: item
  db: dump_************************
  db_list:
  - dump_************************
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
