### ISSUE TITLE
Ability to exclude tags within keyed_groups with dynamic inventories

### ISSUE THREAD

**Issue by misilot** [ansible/ansible#78304]
### Summary

I am trying to use `keyed_groups` with AWS and tags. However, I would like to exclude creating groups for every system based on their Name (`tag_Name_SYSTEMNAME`), but still have the rest of the tags be created automatically using keyed_groups and the tag. 

```yml 
keyed_groups:
  - prefix: tag
    key: tags
```

The only solution I could think of in the meantime is having to specify keyed groups for each tag we create, which isn't very dynamic.

### Issue Type

Feature Idea

### Component Name

lib/ansible/plugins/inventory/constructed.py

### Additional Information

```yaml
keyed_groups:
  - prefix: tag
    key: tags
    exclude: 'Name'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
