### ISSUE TITLE
directory_mode for ansible.builtin.unarchive module like copy

### ISSUE THREAD

**Issue by apfelchips** [ansible/ansible#78318]
### Summary

The `ansible.builtin.unarchive` module could really benefit from a `directory_mode` option.

- You usually want different permissions for folders and files 
- With it you can reliably override archive permissions.
- It should work just like the copy module for recursively copying directories.

see:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-directory_mode
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py#L620

### Issue Type

Feature Idea

### Component Name

unarchive

### Additional Information

currently you have to do something like this:

```yaml
  - name: extract archive
    ansible.builtin.unarchive:
      src: "{{ role_path }}/files/example.tar.gz"
      dest: "/opt/"
      owner: root
      group: root
      mode: 0755

  - name: find files
    ansible.builtin.find:
      path: "/opt/example/"
      recurse: true
    register: example_dir_files

  - name: fix file permissions
    ansible.builtin.file:
      mode: 0644
      path: "{{ item.path }}"
    loop: "{{ example_dir_files.files }}"
```

when it could simply be:

```yaml
  - name: extract archive
    ansible.builtin.unarchive:
      src: "{{ role_path }}/files/example.tar.gz"
      dest: "/opt/"
      owner: root
      group: root
      mode: 0644
      directory_mode: 0755
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
