### ISSUE TITLE
ec2_vpc with templated tags don't work correctly

### ISSUE THREAD

**Issue by mpeters** [ansible/ansible#7833]
##### Issue Type:

Bug Report
##### Ansible Version:

1.6.2
##### Environment:

Ansible is running on Fedora 20. AWS API is the target.
##### Summary:

I'm trying to create a VPC with certain tags which are derived from
variables. Simply trying to use Ansible/Jinja templated values for the tags results in weird results.
##### Steps To Reproduce:

Try to create an EC2 VPC with a task like this:

``` yaml
   - name: Create VPC for new environment
      local_action:
        module: ec2_vpc
        state: present
        cidr_block: 10.0.0.0/16
        resource_tags: { "Name": "marketplace-{{ environment }}" }
        region: "{{ aws_region }}"
        dns_hostnames: true
        dns_support: true
        internet_gateway: true
        validate_certs: true
        instance_tenancy: default
        wait: true
        subnets: []
        route_tables: []
      register: new_vpc
```

And execute it in a playbook (with the appropriate AWS credentials in your env) like so:

```
ansible-playbook test.yml -e 'aws_region=XXX environment=foo'
```
##### Expected Results:

This should create a new VPC with the Name tag of "marketplace-foo".
##### Actual Results:

An EC2 VPC is created with a name of "marketplace-{}"
