### ISSUE TITLE
win_domain_membership - Providing domain_ou_path gives "System cannot find the file specified" error

### ISSUE THREAD

**Issue by CatchKarthik** [ansible/ansible#78337]
### Summary

While attempting to join a new server to domain, it fails with "System cannot find the file specified" error. This behavior occurs only when the domain_ou_path parameter is specified. The playbook runs successfully if we commented out domain_ou_path parameter. 

### Issue Type

Bug Report

### Component Name

win_domain_membership

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ansible master: Ansible AWX tool
Domain controller: Windows 2016
Domain joiner: Windows 2019

### Steps to Reproduce

```yaml (paste below)
- name: "Domain Join"
  ansible.windows.win_domain_membership:
    dns_domain_name: '{{ domain_name }}'
    hostname: '{{ win_hostname }}'
    domain_admin_user: '{{ domain_admin_user }}'
    domain_admin_password: '{{ domain_admin_password }}'
    domain_ou_path: OU=GlobalServers,OU=test,DC=ansible,DC=net
    state: domain
  register: domain_state
```

### Expected Results

Expected result should show 'changed' and after reboot the windows should be added in the correct provided domain OU path

### Actual Results

```console
failed to join domain: Computer 'xxxx' failed to join domain 'ansible.net' from its current workgroup 'WORKGROUP' with following error message: The system cannot find the file specified.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
