### ISSUE TITLE
Azure Ansible - Doesn't fetch IPConfiguration Public IP Method

### ISSUE THREAD

**Issue by kTipSSIoYv** [ansible/ansible#78338]
### Summary

When I try to fetch the IP configuration of the network interface, I see that public_ip_allocation_method is set to NULL even though it is dynamic in Azure portal. I even tested by creating a new IP yet it shows NULL.

As a result I'm unable to modify network interface settings like Security Group, I get the error value of public_ip_allocation_method must be one of: Dynamic, Static, got: None found in ip_configurations

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.2]
  config file = /root/azure_ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
sh-4.4# ansible-config dump --only-changed
DEFAULT_HOST_LIST(/root/azure_ansible/ansible.cfg) = ['/root/azure_ansible/inventory/test.azure_rm.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/root/azure_ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/root/azure_ansible/ansible.cfg) = json
```

### OS / Environment

Centos 7, Docker container

### Steps to Reproduce

```
  - name: Get facts for one network interface
    azure_rm_networkinterface_info:
      resource_group: "{{ resource_group }}"
      name: "{{ azure_vm_network_interface }}"
    register: azure_network_interface_info	 


  - name: Applying NSG to target NIC
    azure_rm_networkinterface:
      name: "{{ azure_vm_network_interface }}"
      resource_group: "{{ resource_group }}"
      subnet_name: "{{ azure_network_interface_info.networkinterfaces[0].subnet }}"
      virtual_network: "{{ azure_network_interface_info.networkinterfaces[0].virtual_network.name }}"
      ip_configurations: "{{ azure_network_interface_info.networkinterfaces[0].ip_configurations }}"
      security_group: "/subscriptions/123456/resourceGroups/test-resource-group/providers/Microsoft.Network/networkSecurityGroups/testing_temp_8"

```

### Expected Results

Fetch `public_ip_allocation_method` method instead of return NULL

Portal shows that the IP is Dynamic (I tested by creating a new IP but still ansible returns NULL for `public_ip_allocation_method`) 
![image](https://user-images.githubusercontent.com/9666915/180595911-2891bd40-1e06-419c-83c4-727914210641.png)

### Actual Results

```console
"ip_configurations": [
                            {
                                "application_gateway_backend_address_pools": null,
                                "application_security_groups": null,
                                "load_balancer_backend_address_pools": null,
                                "name": "Ubuntu915",
                                "primary": true,
                                "private_ip_address": "10.0.0.5",
                                "private_ip_address_version": "IPv4",
                                "private_ip_allocation_method": "Dynamic",
                                "public_ip_address": "/subscriptions/123456789/resourceGroups/test-resource-group/providers/Microsoft.Network/publicIPAddresses/Ubuntu-915-test",
                                "public_ip_address_name": "/subscriptions/123456789/resourceGroups/test-resource-group/providers/Microsoft.Network/publicIPAddresses/Ubuntu-915-test",
                                "public_ip_allocation_method": null
                            }
                        ],

When trying to change security group, I get the following error 

"msg": "value of public_ip_allocation_method must be one of: Dynamic, Static, got: None found in ip_configurations"
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
