### ISSUE TITLE
Difference filter regression on 6.x branch

### ISSUE THREAD

**Issue by GuillaumeSeren** [ansible/ansible#78340]
### Summary

Hey there,
I am a big ansible fan for quite some time, thank you for the hard work.

After upgrading ansible to 6.x,
I have a strange regression on the difference filter, before it was working fine.

Maybe I missed something in my code, but rolling back to ansible-5.9 get it back to work.

### Issue Type

Bug Report

### Component Name

filter

### Ansible Version

```console
$ ansible --version
  config file = ~/redacted-path/ansible.cfg
  configured module search path = ['/home/gseren/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/gseren/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.10/ansible
  python version = 3.10.5 (main, Jun 24 2022, 11:27:40) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```


### Configuration

```console
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_HASH_BEHAVIOUR(~/redacted-path/ansible.cfg) = merge
DEFAULT_TIMEOUT(~/redacted-path/ansible.cfg) = 60
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = False
SHOW_CUSTOM_STATS(env: ANSIBLE_SHOW_CUSTOM_STATS) = True

CALLBACK:
========

default:
_______
display_ok_hosts(env: ANSIBLE_DISPLAY_OK_HOSTS) = True
display_skipped_hosts(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = False
show_custom_stats(env: ANSIBLE_SHOW_CUSTOM_STATS) = True

CONNECTION:
==========

ssh:
___
timeout(~/redacted-path/ansible.cfg) = 60
```

### OS / Environment

Gentoo

### Steps to Reproduce

The playbook code that compare two simple list
<!--- Paste example playbooks or commands between quotes below -->
```yaml
...
    - name: Detect newly created dropin
      set_fact:
        sysctl_config_files_diff: "{{ sysctl_config_files_current | difference(sysctl_config_files_new) }}"
    - debug:
        msg:
          - "{{ sysctl_config_files_current }}"
          - "{{ sysctl_config_files_new }}"
          - "{{ sysctl_config_files_diff }}"
...
```

### Expected Results

Example that works ansible-5.9.0
```yaml
    "msg": [                                                                                                                                                                                                                                                                      
        [                                                           
            "/etc/sysctl.d/10-firewall.conf",                                                                                            
            "/etc/sysctl.d/99-sysctl.conf",                         
            "/etc/sysctl.d/00protected-links.conf",                                                                                      
            "/etc/sysctl.d/10-swappiness.conf"                                                                                           
        ],                                                          
        [                                                           
            "/etc/sysctl.d/99-sysctl.conf",                         
            "/etc/sysctl.d/10-swappiness.conf",                                                                                          
            "/etc/sysctl.d/10-firewall.conf",                                                                                            
            "/etc/sysctl.d/00protected-links.conf"                                                                                       
        ],                                                          
        []                                                          
    ]
```

### Actual Results

Example failure with 6.0.0
```console
    "msg": [
        "[] + [ '/etc/sysctl.d/10-firewall.conf' ] + [ '/etc/sysctl.d/99-sysctl.conf' ] + [ '/etc/sysctl.d/00protected-links.conf' ] + [ '/etc/sysctl.d/10-swappiness.conf' ]",
        "[] + [ '/etc/sysctl.d/99-sysctl.conf' ] + [ '/etc/sysctl.d/10-swappiness.conf' ] + [ '/etc/sysctl.d/10-firewall.conf' ] + [ '/etc/sysctl.d/00protected-links.conf' ]",
        "set()"
    ]
```

Example failure with 6.1.0
```console
    "msg": [
        "[] + [ '/etc/sysctl.d/10-firewall.conf' ] + [ '/etc/sysctl.d/99-sysctl.conf' ] + [ '/etc/sysctl.d/00protected-links.conf' ] + [ '/etc/sysctl.d/10-swappiness.conf' ]",
        "[] + [ '/etc/sysctl.d/99-sysctl.conf' ] + [ '/etc/sysctl.d/10-swappiness.conf' ] + [ '/etc/sysctl.d/10-firewall.conf' ] + [ '/etc/sysctl.d/00protected-links.conf' ]",
        "set()"
    ]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/filter.py`](https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_internal/cli/commands/coverage/analyze/targets/filter.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I am not able to reproduce the issue:
```yaml
- hosts: localhost
  gather_facts: false
  vars:
    sysctl_config_files_current:
      - "/etc/sysctl.d/10-firewall.conf"
      - "/etc/sysctl.d/99-sysctl.conf"
      - "/etc/sysctl.d/00protected-links.conf"
      - "/etc/sysctl.d/10-swappiness.conf"
    sysctl_config_files_new:
      - "/etc/sysctl.d/99-sysctl.conf"
      - "/etc/sysctl.d/10-swappiness.conf"
      - "/etc/sysctl.d/10-firewall.conf"
      - "/etc/sysctl.d/00protected-links.conf"
  tasks:
    - set_fact:
        sysctl_config_files_diff: "{{ sysctl_config_files_current | difference(sysctl_config_files_new) }}"
    - debug:
        msg:
          - "{{ sysctl_config_files_current }}"
          - "{{ sysctl_config_files_new }}"
          - "{{ sysctl_config_files_diff }}"
```

```
TASK [debug] ***************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        [
            "/etc/sysctl.d/10-firewall.conf",
            "/etc/sysctl.d/99-sysctl.conf",
            "/etc/sysctl.d/00protected-links.conf",
            "/etc/sysctl.d/10-swappiness.conf"
        ],
        [
            "/etc/sysctl.d/99-sysctl.conf",
            "/etc/sysctl.d/10-swappiness.conf",
            "/etc/sysctl.d/10-firewall.conf",
            "/etc/sysctl.d/00protected-links.conf"
        ],
        []
    ]
}
```

Based on the provided output:
```
[] + [ '/etc/sysctl.d/10-firewall.conf' ] + [ '/etc/sysctl.d/99-sysctl.conf' ] + [ '/etc/sysctl.d/00protected-links.conf' ] + [ '/etc/sysctl.d/10-swappiness.conf' ]"
```

my guess is that the list is constructed incorrectly (see https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.13.html#playbook) but that information is missing from the provided reproducer.

needs_info
