### ISSUE TITLE
ignore_unreachable true with  retries configuration not working 

### ISSUE THREAD

**Issue by sherry442** [ansible/ansible#78358]
### Summary

In ansible playbook to retry task for unreachable error 

### Issue Type

Feature Idea

### Component Name
!component

### Ansible Version

```console
$ ansible --version
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 4
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_LOG_FILTER(/etc/ansible/ansible.cfg) = [u'paramiko.transport']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ops/oes/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/ops/.ssh/m2mops.pem
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = skippy
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 50
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = paramiko
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

CentOS

### Steps to Reproduce

```yaml (paste below)
- name: Check for the file play
  hosts: all
  remote_user: "user"
  ignore_unreachable: True
  gather_facts: no
  tasks:
    - name: Check for the file
      file:
         path: "/tmp/test"
         state: file
      register: my_file
      until: my_file.unreachable is defined
      retries: 2
      delay: 5


```

### Expected Results

If IP is not reachable then task "Check for the file" should be repeated for 2times with 5secs delay. But it is executing only one time and marking play unreachable=1

### Actual Results

```console
If IP is not reachable then task "Check for the file" should be repeated for 2times with 5secs delay. But it is executing only one time and marking play unreachable=1

PLAY [Check for the file] *************************************************************************************************************

TASK [Check for the file] *************************************************************************************************************
fatal: [XXX.XXX.XX.XX]: UNREACHABLE! => {"changed": false, "msg": "not a valid OPENSSH private key file", "skip_reason": "Host XXX.XXX.XX.XX is unreachable", "unreachable": true}

PLAY RECAP ****************************************************************************************************************************
XXX.XXX.XX.XX              : ok=0    changed=0    unreachable=1    failed=0    skipped=1    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mattclay** [comment]
Retries do not work with unreachable errors. You can use `wait_for` or `wait_for_connection` to wait until a host is ready.

As this is expected behavior, I'll convert this bug report to a feature request.

**Comment by shivamdurgbuns** [comment]
@mattclay  Are we expecting here for `retries` to keep on trying even if getting unreachable errors?

**Comment by sherry442** [comment]
Yes, to retry even if we get unreachable error for defined number of times.

**Comment by agowa338** [comment]
Same here. As discussed in IRC right now just having wait_for and wait_for_connection is not enough.

Scenario, a task is executed that performs an unknown number of reboots but drops a file "/complete" file. When one now uses wait_for it'll fail because the connection dropped. And a wait_for_connection doesn't work becuse the connection may drop another few times.
And having both right after another may also not work as the connection may die in the wrong place.

We tried to handle this by using the until statement together with `wait_for`, but because of this issue that didn't work either.
Next we tried to use a block, but `ERROR! 'retries' is not a valid attribute for a Block`

I tried to it like this:
```
- name: Wait for setup to complete
  wait_for:
    path: "/complete"
    state: present
    register: result
  until: result.success
  retries: 10000000
  ignore_errors: true
  ignore_unreachable: true
  delay: 30
```

**Comment by agowa338** [comment]
Workaround for now is very ugly but kinda working:
```yaml
- command: >-
        ansible localhost --connection community.vmware.vmware_tools -e ansible_connection=community.vmware.vmware_tools -e ansible_shell_type="powershell" -e ansible_become=false -e ansible_vmware_host="{{ vcenter_hostname }}" -e ansible_vmware_user="{{ vcenter_username }}" -e ansible_vmware_password="{{ vcenter_password }}" -e ansible_vmware_validate_certs=false -e ansible_user="{{ vcenter_vm.guest_user|default(omit) }}" -e ansible_vmware_tools_user="{{ vcenter_vm.guest_user|default(omit) }}" -e ansible_vmware_tools_password="{{ vcenter_vm.guest_password|default(omit) }}" -e ansible_vmware_guest_path="{{ vm.instance.hw_folder }}/{{ vm.instance.hw_name }}" -e ansible_vmware_guest_moid="{{ vm.instance.moid }}" -m wait_for -a path=/complete
      ignore_errors: false
      register: result
      until: result.rc == 0
      retries: 10000000
      delay: 30
```
