### ISSUE TITLE
Template validation appears to check destination file before template is applied

### ISSUE THREAD

**Issue by o0-o** [ansible/ansible#78366]
### Summary

Running the template module with validation against an OpenBSD host to configure /etc/dhcpd.conf. Validation appears to be checking the existing file and not the result of the template.

```
- name: Template dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: "{{ dhcpd_cfg_path }}/dhcpd.conf"
    owner: root
    group: wheel
    mode: '0644'
    validate: "{{ dhcpd_bin_path }}/dhcpd -nf %s"
    backup: true
  become: true
```

If the file doesn't exist, the validation appears to run against the non-existent file:

```
TASK [o0_o.services.dhcp : Template dhcpd.conf] ****************************************
fatal: [openbsd7.hq.example.com]: FAILED! => {"changed": false, "checksum": "6ea16998403abe8769ac4457b8380c097d5606d2", "exit_status": 1, "msg": "failed to validate", "stderr": "fatal in dhcpd: Can't open /etc/dhcpd.conf: No such file or directory\n", "stderr_lines": ["fatal in dhcpd: Can't open /etc/dhcpd.conf: No such file or directory"], "stdout": "", "stdout_lines": []}
```

Running without validation works fine:

```
TASK [o0_o.services.dhcp : Template dhcpd.conf] ****************************************
changed: [openbsd7.hq.example.com]
```

```pre
[vagrant@openbsd7 ~]$ dhcpd -nf /etc/dhcpd.conf
[vagrant@openbsd7 ~]$ echo $?
0
```

If the file does exist, but has an error, validation fails before applying the template. I removed a semicolon manually and attempted to fix it with the template (same template that succeeded before). The error message corresponds to the arbitrary semicolon removal (error appears on the following line).

```
TASK [o0_o.services.dhcp : Template dhcpd.conf] *********************************************************************************************************************************
fatal: [openbsd7.hq.example.com]: FAILED! => {"changed": false, "checksum": "6ea16998403abe8769ac4457b8380c097d5606d2", "exit_status": 1, "msg": "failed to validate", "stderr": "/etc/dhcpd.conf line 8: \nshared-network \n^\nfatal in dhcpd: Configuration file errors encountered\n", "stderr_lines": ["/etc/dhcpd.conf line 8: ", "shared-network ", "^", "fatal in dhcpd: Configuration file errors encountered"], "stdout": "", "stdout_lines": []}
```

### Issue Type

Bug Report

### Component Name

template

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]
  config file = /Users/o0-o/.ansible.cfg
  configured module search path = ['/Users/o0-o/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/o0-o/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/Users/o0-o/.ansible.cfg) = True
COLOR_DEBUG(/Users/o0-o/.ansible.cfg) = bright yellow
DEFAULT_REMOTE_USER(/Users/o0-o/.ansible.cfg) = root
GALAXY_ROLE_SKELETON(/Users/o0-o/.ansible.cfg) = /Users/o0-o/.ansible/roles/o0_o.skel
GALAXY_ROLE_SKELETON_IGNORE(/Users/o0-o/.ansible.cfg) = ['^.git$', '^.*/.git_keep$']
HOST_KEY_CHECKING(/Users/o0-o/.ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/Users/o0-o/.ansible.cfg) = False
remote_user(/Users/o0-o/.ansible.cfg) = root

ssh:
___
host_key_checking(/Users/o0-o/.ansible.cfg) = False
pipelining(/Users/o0-o/.ansible.cfg) = True
remote_user(/Users/o0-o/.ansible.cfg) = root
ssh_args(/Users/o0-o/.ansible.cfg) = -o ControlPersist=10
```

### OS / Environment

OpenBSD 7.1

### Steps to Reproduce

```yaml (paste below)
- name: Template dhcpd.conf
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: "{{ dhcpd_cfg_path }}/dhcpd.conf"
    owner: root
    group: wheel
    mode: '0644'
    validate: "{{ dhcpd_bin_path }}/dhcpd -nf %s"
    backup: true
  become: true
```

### Expected Results

Validation should succeed or fail based on the result of the template but it evaluates the destination in its current state before any changes are applied.

### Actual Results

```console
Validation fails based on current state of the destination file before changes are applied by the template.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
