### ISSUE TITLE
Error message: Unsupported parameters for (ansible.legacy.command) module: args

### ISSUE THREAD

**Issue by sdarwin** [ansible/ansible#78360]
### Summary

Hi,

This is a feature idea, to enhance the error message output of a certain failure scenario.

Consider the task:
```
    - name: Run shell
      ansible.builtin.shell:
        cmd: |
          echo "hello"
        args:
          executable: /bin/bash
      register: result
```

Of course, you get this result:
```
    TASK [Run shell] ******************************************************************************************************************************************************************************************
fatal: [test.example.com]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: args. Supported parameters include: _uses_shell, _raw_params, argv, chdir, removes, stdin, executable, creates, stdin_add_newline, warn, strip_empty_ends."}
```

To an expert, it all makes sense.  But to an average user, does the above error message clearly outline the problem and solution?    

A proposal is to include additional text in the error message:  

```
Solution: This can likely be fixed by changing the indentation of 'args', since 'args' is an allowable 'task keyword' but isn't a 'parameter' of ansible.builtin.shell. Task keywords should appear at a higher level in the yaml hierarchy.  Move the indentation to the left.
```

The solution can be generalize. Anytime the specific error message "Unsupported parameters for" is shown, check if the faulty parameter is included in a list of valid top-level task keywords.  (Such as the word 'when').    If it is, add the message "Solution: This can likely be fixed by changing the indentation of 'when' ..." 

### Issue Type

Feature Idea

### Component Name

builtin collection

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by jborean93** [comment]
You only need to use `args` if you are using specifying the cmd as the raw value like so

```yaml
- shell: echo "hello"
  args:
    executable: /bin/bash
```

When using the newer format with `cmd` as a module option just specify executable like any other module option

```yaml
- shell:
    cmd: echo "hello"
    executable: /bin/bash
```

Have a look at the examples https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html#examples

```yaml
# You can also use the 'cmd' parameter instead of free form format.
- name: This command will change the working directory to somedir/
  ansible.builtin.shell:
    cmd: ls -l | grep log
    chdir: somedir/
```

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

See  this page for a complete and up to date list of communication channels and their purposes:

   * https://docs.ansible.com/ansible/latest/community/communication.html

Because this project is very active, we're unlikely to see comments made on closed tickets and we lock them after some time.
If don't you think this particular issue is resolved, you should still stop by there first, we'd appreciate it.
This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
