### ISSUE TITLE
local_action does not inherit set_fact: ansible_become_password

### ISSUE THREAD

**Issue by ttbigc** [ansible/ansible#78420]
### Summary

I have the following example playbook:
```
- hosts: all
  become: no
  gather_facts: false

  vars:
    use_aws_secrets: true
# If I set in  vars section, local_action works. However I want to set ansible_password based on different when conditions why setting within task section
#    ansible_password: "{{ lookup('aws_secret', aws_secret_name) }}"
#    ansible_become_password: "{{ lookup('aws_secret', aws_secret_name) }}"
  tasks:
# If I use set_fact, local_action fails with: "module_stderr": "sudo: a password is required\n"
    - name: Use AWS Secrets Manager to fetch password
      local_action:
         module: set_fact
         ansible_password: "{{ lookup('aws_secret', aws_secret_name) }}"
         ansible_become_password: "{{ lookup('aws_secret', aws_secret_name) }}"
      when: use_aws_secrets

    - name: Debug local_action
      local_action:
        module: shell
        cmd: "id"
      run_once: true
      become: yes
```

Playbook run:
$ ansible-playbook -i 1.2.3.4, test.yml
PLAY [all] ********************************************************************************************************************************************************

TASK [Use AWS Secrets Manager to fetch password] ******************************************************************************************************************
ok: [1.2.3.4 -> localhost]

TASK [Debug local_action] *****************************************************************************************************************************************
fatal: [1.2.3.4 -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Can someone help me understand why local_action does not inherit the ansible_become_password from the set_fact task?
I did find if I change "hosts: all" to "hosts: localhost:all" 
 ansible-playbook -i 1.2.3.4, test.yml
PLAY [localhost:all] **********************************************************************************************************************************************

TASK [Use AWS Secrets Manager to fetch password] ******************************************************************************************************************
ok: [localhost -> localhost]
ok: [1.2.3.4 -> localhost]

TASK [Debug local_action] *****************************************************************************************************************************************
changed: [localhost -> localhost]

### Issue Type

Bug Report

### Component Name

set_fact

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /home/XXXXXX/.ansible.cfg
  configured module search path = ['/home/XXXXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep 12 2021, 04:40:35) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL8.4

### Steps to Reproduce

```
- hosts: all
  become: no
  gather_facts: false

  vars:
    use_aws_secrets: true
# If I set in  vars section, local_action works. However I want to set ansible_password based on different when conditions why setting within task section
#    ansible_password: "{{ lookup('aws_secret', aws_secret_name) }}"
#    ansible_become_password: "{{ lookup('aws_secret', aws_secret_name) }}"
  tasks:
# If I use set_fact, local_action fails with: "module_stderr": "sudo: a password is required\n"
    - name: Use AWS Secrets Manager to fetch password
      local_action:
         module: set_fact
         ansible_password: "{{ lookup('aws_secret', aws_secret_name) }}"
         ansible_become_password: "{{ lookup('aws_secret', aws_secret_name) }}"
      when: use_aws_secrets

    - name: Debug local_action
      local_action:
        module: shell
        cmd: "id"
      run_once: true
      become: yes
```

### Expected Results

Expect local_action to run command as sudo using ansible_become_password

### Actual Results

```console
fatal: [1.2.3.4 -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug, this is the normal operation of delegation.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#delegating-facts

`local_action` is just a special syntax for delegation that always delegates to `localhost`; it's generally better to use the more flexible `delegate_to` syntax, since it's more in line with other keywords that affect task execution.

Delegated tasks use variables from the inventory host with the exception of connection variables, which are from the host that is being delegated to. `ansible_password` and `ansible_become_password` are connection variables, so they need to be set on `localhost` if you want them to affect the execution of tasks that are delegated to `localhost`. In order to achieve this you need to set `delegate_facts: true` on your `set_fact`:

```
    - name: Use AWS Secrets Manager to fetch password
      set_fact:
         ansible_password: "{{ lookup('aws_secret', aws_secret_name) }}"
         ansible_become_password: "{{ lookup('aws_secret', aws_secret_name) }}"
      delegate_to: localhost
      delegate_facts: true
      when: use_aws_secrets

    - name: Debug local action
      shell: id
      delegate_to: localhost
      run_once: true
      become: yes
```
