### ISSUE TITLE
Installing collection specific version from the requirements file not working as expected

### ISSUE THREAD

**Issue by piotrkochan** [ansible/ansible#78440]
### Summary

"Requirements" file allows to specify role/collection version. It works ok for the roles but for collections version is ignored and simply latest version is being installed.

### Issue Type

Bug Report

### Component Name

galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.2]
  config file = /home/piotr/dev/devops/ansible-architecture2/ansible.cfg
  configured module search path = ['/home/piotr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/piotr/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/piotr/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/piotr/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
I don't think it is revelant
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

The `requirements.yml` file contents:

```
---
collections:
  - name: community.zabbix
    src: git+https://github.com/ansible-collections/community.zabbix.git,fc6031c1c2d91c711c5c82f80479dae5b7b5725a
```

or 

```
---
collections:
  - name: community.zabbix
    src: git+https://github.com/ansible-collections/community.zabbix.git
    version: fc6031c1c2d91c711c5c82f80479dae5b7b5725a
```

or 

```
---
collections:
  - name: community.zabbix
    src: git+https://github.com/ansible-collections/community.zabbix.git
    version: main
```

### Expected Results

I expect that all or at least one of above configuration would install collection from specific commit (or branch)

### Actual Results

```console
ansible-galaxy install -r monitoring/zabbix-agent/requirements.yml --force
```
result:

```
[...]
Starting collection install process
Fetching a collection tarball for 'community.zabbix:1.7.0' from Ansible Galaxy
Downloading https://galaxy.ansible.com/download/community-zabbix-1.7.0.tar.gz to /home/piotr/.ansible/tmp/ansible-local-318375hq_n2_dt/tmpy8towjdc/community-zabbix-1.7.0-_99169hh
Validating downloaded file hash 9bc23411b1ad0c0123b63370cede89f10257b3fd93bab930c747f11f7c75f598 with expected hash 9bc23411b1ad0c0123b63370cede89f10257b3fd93bab930c747f11f7c75f598
Collection 'community.zabbix:1.7.0' obtained from server default https://galaxy.ansible.com/api/
Installing 'community.zabbix:1.7.0' to '/home/piotr/.ansible/collections/ansible_collections/community/zabbix'
```

Instead of specific commit or branch last tag is being installed.

In case of specifying version under `version` key there is an error:

```
Process install dependency map
Calling Galaxy at https://galaxy.ansible.com/api/v2/collections/community/zabbix/versions/?page_size=100
ERROR! Non integer values in LooseVersion ('fc6031c1c2d91c711c5c82f80479dae5b7b5725a')
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
