### ISSUE TITLE
changed_when and async is conflict in a task

### ISSUE THREAD

**Issue by A-BenMao** [ansible/ansible#78457]
### Summary

when i use async in a task, the task  report a error like this:

`"msg": "The conditional check '\"<<CHANGED>>\" in rsync.stdout\n' failed. The error was: error while evaluating conditional (\"<<CHANGED>>\" in rsync.stdout\n): Unable to look up a name or access an attribute in template string ({% if \"<<CHANGED>>\" in rsync.stdout\n %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"
`
-------
my task code like this:
```bash
- name: Sync code gamedb
      shell: |
        export RSYNC_PASSWORD='{{ project_pass_sync_code }}'
        /usr/bin/rsync \
          --delete -a \
          --out-format='<<CHANGED>>%i %n%L' \
          --chown="{{ project_user }}:{{ project_group }}" \
          deployment@{{ deployment_address }}::server_out/{{ project_code_tag }}/ \
          "{{ project_dirs_game.incoming }}/server"
      register: rsync
      async: 1000
      poll: 0
      changed_when: |
        "<<CHANGED>>" in rsync.stdout
      when: |
        "db1" in project_host_roles
      tags:
        - sync
        - presync`
      
but when i delete `changed_when` ,the error is disappear

### Issue Type

Bug Report

### Component Name

async  changed_when

### Ansible Version

```console
$ ansible --version
ansible 2.7.6
  config file = ******ansible.cfg
  configured module search path = ['******/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 31 2019, 10:58:18) [GCC 4.9.2]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ALLOW_WORLD_READABLE_TMPFILES = True
ANSIBLE_PIPELINING = True
ANSIBLE_SSH_ARGS = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN = jsonfile
CACHE_PLUGIN_CONNECTION = var/facts
CACHE_PLUGIN_TIMEOUT = 31536000
DEFAULT_FORKS = 200
DEFAULT_GATHERING = smart
DEFAULT_HOST_LIST = ['/home/xucheng/ansible-d37/hosts']
DEFAULT_LOG_PATH = /home/xucheng/ansible-d37/var/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH = ['/home/xucheng/ansible-d37/lookup_plugins']
DEFAULT_MANAGED_STR = Ansible managed
DEFAULT_NO_LOG = False
DEFAULT_REMOTE_PORT = 30022
DEFAULT_ROLES_PATH = ['/home/xucheng/ansible-d37/roles_common', '/home/xucheng/ansible-d37/roles']
DEFAULT_SCP_IF_SSH = True
DEFAULT_TRANSPORT = ssh
DEFAULT_VAULT_PASSWORD_FILE = /home/xucheng/ansible-d37/.vault_pass
DEPRECATION_WARNINGS = True
DISPLAY_SKIPPED_HOSTS = False
HOST_KEY_CHECKING = False
RETRY_FILES_SAVE_PATH = /home/xucheng/ansible-d37/var
```

### OS / Environment

debian 9

### Steps to Reproduce

```yaml (paste below)
- name: Sync code gamedb
      shell: |
        export RSYNC_PASSWORD='{{ project_pass_sync_code }}'
        /usr/bin/rsync \
          --delete -a \
          --out-format='<<CHANGED>>%i %n%L' \
          --chown="{{ project_user }}:{{ project_group }}" \
          deployment@{{ deployment_address }}::server_out/{{ project_code_tag }}/ \
          "{{ project_dirs_game.incoming }}/server"
      register: rsync
      async: 1000
      poll: 0
      changed_when: |
        "<<CHANGED>>" in rsync.stdout
      when: |
        "db1" in project_host_roles
      tags:
        - sync
        - presync`
```

### Expected Results

success

### Actual Results

```console
"msg": "The conditional check '\"<<CHANGED>>\" in rsync.stdout\n' failed. The error was: error while evaluating conditional (\"<<CHANGED>>\" in rsync.stdout\n): Unable to look up a name or access an attribute in template string ({% if \"<<CHANGED>>\" in rsync.stdout\n %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
