### ISSUE TITLE
task is failing with UNREACHABLE! - Failed to connect to the host via ssh while docker restart

### ISSUE THREAD

**Issue by vineet5583** [ansible/ansible#78458]
### Summary

 What problem/issue/behavior are you having trouble with?  What do you expect to see?
1) For the first time installation using ansible , while restart docker daemon , docker service task is failing with UNREACHABLE! - Failed to connect to the host via ssh:
2) Working fine , if we re-trigger again the same. 

### Issue Type

Bug Report

### Component Name

ssh

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]                                                                                          
  config file = None                                                                                           
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']     
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible                              
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections                      
  executable location = /usr/local/bin/ansible                                                                 
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]             
  jinja version = 3.1.2                                                                                        
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
```

### OS / Environment

RHEL8.6

### Steps to Reproduce

```yaml (paste below)
- name: Restart Docker Service                                                                           
  shell: sudo systemctl daemon-reload; sudo systemctl restart docker                                     
  register: result                                                                                       
  retries: 5                                                                                             
  delay: 10                                                                                              
  until: result is not failed                                                                            
  ignore_errors: True 
```

### Expected Results

it should work

### Actual Results

```console
channel_input_status_confirm: type 99 id 0\r\ndebug2: exec request accepted on channel 0\r\ndebug3: send packet: type 1\r\nclient_loop: send disconnect: Broken pipe\r\n')
fatal: [135.250.142.131]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
