### ISSUE TITLE
jenkins_plugin does not install plugins but says changed in output

### ISSUE THREAD

**Issue by alok15ee** [ansible/ansible#78463]
### Summary

This issue has started to appear again with 
ansible --version
ansible 2.9.27

Based on the previous tickets https://github.com/ansible/ansible/issues/26199  
 now it fails on both "latest" and "present"

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/web_infrastructure/jenkins_plugin.py

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 7

### Steps to Reproduce

```
jenkins_plugins_state = present or latest
- name: Install plugins with a specific version and restart jenkins
  jenkins_plugin:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ 'present' if item.version is defined else jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    updates_url: "{{ jenkins_updates_url }}"
  with_items:
    - "{{ jenkins_plugins }}"
```

### Expected Results

Plugins installed or ansible should return error

### Actual Results

```console
amazon-ebs: changed: [default] => (item={u'name': u'active-directory'})
amazon-ebs: changed: [default] => (item={u'name': u'ansicolor'})
amazon-ebs: changed: [default] => (item={u'name': u'artifactory'})
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
