### ISSUE TITLE
Unable to manage snapshots for non-existing VM 

### ISSUE THREAD

**Issue by SerdarYalcin** [ansible/ansible#78474]
### Summary

When I try to take a snapshot of a VMware VM, I get the below error:

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/cloud/vmware/vmware_guest_snapshot.py

### Ansible Version

```console
$ ansible --version

ansible [core 2.11.12]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.7/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.7.10 (default, Jun  3 2021, 00:02:01) [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
  jinja version = 3.0.2
  libyaml = True

  python version = 3.7.10 (default, Jun  3 2021, 00:02:01) [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'virtualbox', 'yaml', 'constructed', 'aws_ec2', 'script', 'auto', 'yaml', 'ini', 'toml']
```

### OS / Environment

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
cpe:2.3:o:amazon:amazon_linux:2

### Steps to Reproduce

```yaml (paste below)


---
-
   hosts: localhost
   connection: local
   gather_facts: false
   collections:
           - community.vmware
   #vars_files:
    #       - /etc/ansible/group_vars/vmware.yml
   tasks:
           - name: create a snapshot
             vmware_guest_snapshot:
                 validate_certs: no
                 hostname: 192.168.1.10
                 username: administrator@test.com
                 password: passwd
                 datacenter: MAIN_DC
                 name: 01-Docker
                 state: present
                 snapshot_name: "Ansible_Test"
                 folder: "/01-Docker"

```

### Expected Results

It was able to take a snapshot around 1-2 months ago successfully.

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "MAIN_DC",
            "description": "",
            "folder": "/01-Docker",
            "hostname": "192.168.1.10",
            "memory_dump": false,
            "moid": null,
            "name": "01-Docker",
            "name_match": "first",
            "new_description": null,
            "new_snapshot_name": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy_host": null,
            "proxy_port": null,
            "quiesce": false,
            "remove_children": false,
            "snapshot_name": "Ansible_Test",
            "state": "present",
            "use_instance_uuid": false,
            "username": "administrator@test.com",
            "uuid": null,
            "validate_certs": false
        }
    },
    "msg": "Unable to manage snapshots for non-existing VM 01-Docker"
}
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct
