### ISSUE TITLE
Suggest to Add  ssh-keygen -a (Trials) Option

### ISSUE THREAD

**Issue by NoToComments** [ansible/ansible#78473]
### Summary

I am trying to achieve a best practise solution with ansible. I have found out that the -a Option from the underlying ssh-keygen is missing.

The -a Option would it allow to improve the security of the generated keys when creating users and their ssh-keys 
[SSH-Keygen](https://linux.die.net/man/1/ssh-keygen)

As the -a Option can help to protect against brute forcing.

The default is 100

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

```yaml (paste below)
- name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
  ansible.builtin.user:
    name: jsmith
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_trials: 1000
    ssh_key_passphrase: foo
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
