### ISSUE TITLE
For git sourced collections, ansible-galxy always --force collections install

### ISSUE THREAD

**Issue by ulvida** [ansible/ansible#78481]
### Summary

If the directories where `ansible-galaxy` installs collections are not empty, for the git repos, it overwrites the content of these directories, even without `--force` options. That's not [what is documented](https://docs.ansible.com/ansible/latest/cli/ansible-galaxy.html#cmdoption-ansible-galaxy-collection-install-f). 

I have in my requirements file: 
```yaml
collections:
# Colección cielito.proxmox
- name: git@git.interior.edu.uy:cielito/proxmox.git
  type: git
  version: master

# Colección cielito.system : users, dns, motd, ...
- name: git@git.interior.edu.uy:cielito/system.git
  type: git
  version: 7-motd-role
```
With ansible I manage to have locally in the `amsible_collections` my collections as git repos. When I run: 
```yaml
ansible-galaxy install collections -r requirements.yml 
```
I have eventually the laconic warning: 
```yaml
[WARNING]: Collection at '/home/ulvida/tech/belvil/collections/ansible_collections/cielito/proxmox' does not have a MANIFEST.json file, nor has it galaxy.yml: cannot detect version.
[WARNING]: Collection at '/home/ulvida/tech/belvil/collections/ansible_collections/cielito/system' does not have a MANIFEST.json file, nor has it galaxy.yml: cannot detect version.
```
but my git repos silently desapear and are replaced by a static version of collections. 

I tried starting with an arbitrary file, and have the same behaviour

### Issue Type

Documentation Report

### Component Name

ansible-galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0]
  config file = /home/ulvida/tech/belvil/belvil.net/ansible.cfg
  configured module search path = ['/home/ulvida/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ulvida/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ulvida/tech/belvil/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Debian bullseye

### Steps to Reproduce

```yaml
collections:
- name: https://github.com/ansible-collections/community.general.git
  type: git
  version: main
```
If you run:
```yaml
ansible-galaxy install collections -r requirements.yml 
```
Whatever you have previousely in `ansible_collections/community/general` directory will be erased or overwritten.

### Expected Results

This shouldn't happen without the option `--force`. The command should fail and raise an error saying the directory is not empty. 

### Actual Results

```console
ulvida@paname:~/tech/belvil/belvil.net$ ansible-galaxy install collections -r requirements.yml 
Starting galaxy collection install process
[WARNING]: Collection at '/home/ulvida/tech/belvil/collections/ansible_collections/community/general' does not have a MANIFEST.json file, nor has it galaxy.yml: cannot detect version.
Process install dependency map
Clonando en '/home/ulvida/.ansible/tmp/ansible-local-92437ymy2yyty/tmp_tv0_ple/community.general_70xy2fv'...
remote: Enumerating objects: 51038, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 51038 (delta 15), reused 16 (delta 9), pack-reused 50982
Recibiendo objetos: 100% (51038/51038), 18.33 MiB | 5.91 MiB/s, listo.
Resolviendo deltas: 100% (32779/32779), listo.
Ya en 'main'
Tu rama está actualizada con 'origin/main'.
Starting collection install process
Installing 'community.general:5.4.0' to '/home/ulvida/tech/belvil/collections/ansible_collections/community/general'
Created collection for community.general:5.4.0 at /home/ulvida/tech/belvil/collections/ansible_collections/community/general
community.general:5.4.0 was installed successfully
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/galaxy`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
This is working as intended. Here's the changelog for the commit implementing this behavior https://github.com/ansible/ansible/commit/595413d11346b6f26bb3d9df2d8e05f2747508a3#diff-18699ba61b34cb094dff4786fc29ff26506d8430b9a79776b99d47da7f88fb3eR8-R9. Installing a collection from a git repo is a developer shortcut (instead of  `git clone`, `git checkout`, `ansible-galaxy collection build`, `ansible-galaxy collection install`, developers can test changes with 1 command) and not the same as installing a collection artifact.

Perhaps we can clarify the `--force/-f` documentation to specify that collections in git repos are not collection artifacts, and --force only applies to the latter.

**Comment by ulvida** [comment]
Thanks for your documented answer @s-hertel ! It's really puzzling the API changes between roles and collections. 
I will coinsider ansible-galaxy as a deployment tool only. To set my git roles environment, I developed [a little absible role with git module](https://framagit.org/gurisitx/devops). 
Yes the command reference doc should clarify that `--force` dosn't apply to git sourced roles, and the ansible docx should say something about this changes in ansible-galaxy design from roles to collections.

**Comment by s-hertel** [comment]
Just to add some more context here after refreshing my memory, we tried to fix this in #72591 before it was merged but couldn't find a good way to that without breaking other things and we ended up just documenting the breaking change. So this is a known limitation but not really an intended one. I don't think there would be objections to reinstating the opt-in reinstall behavior for git sourced collections (after poking for a few hours at the code this morning, I am still not sure how to do that without breaking things). Anyway, if/when it is changed again, whoever does that should remember to update the ansible-galaxy `--force`/`--force-with-deps` documentation.

@ulvida 
> It's really puzzling the API changes between roles and collections.

I'm not sure what API changes you're referring to, (--force does work for collection artifacts) but assuming that was in regard to my 'developer shortcut' explanation, installing a role from a git repo is identical to installing a role from Galaxy, because Galaxy stores git references for roles. Whereas collections are stored as tar.gz artifacts, so installing a collection from a git repo has extra steps to create the artifact and isn't meant to replace the normal build + publish process. Building + publishing your collection will allow you to use --upgrade and version comparison (which roles will not be able to support, partly because of said limitation).

**Comment by gone-for-coding** [comment]
I just hit the same thing. I install a few collections from a local git by pinning their versions to a release tag. ansible-galaxy collection install will happily overwrite (mean reinstall) the collection every time it is running.

This in turn makes the community module non-idempotent for git sources as it will report changed every time:

```yaml
    - name: Check for Ansible collections with correct version
      community.general.ansible_galaxy_install:
        name: "{{ item }}"
        type: collection
        dest: /usr/share/ansible/collections
      loop:
        - "ansible.posix:>=1.4.0,<1.5.0"
        - "ansible.windows:>=1.11.1,<1.12.0"
        - "community.general:>=5.7.0,<6.0.0"
        - "community.windows:>=1.11.0,<1.12.0"
        - "https://github.com/ansible-collections/community.general.git,6.0.1"
```
