### ISSUE TITLE
Allow creation of mobile accounts on macOS

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#78486]
### Summary

macOS has the concept of "mobile" accounts.  These are accounts that are originally from a directory service like Active Directory but are copied into the local dscl /Users database so that they can be accessed off-line.  When we setup users on a machine, we need them to be "mobile" users.  If a mobile account does not already exist for a user, the `user` task will create a new local-only user that doesn't have the proper uid or groups as the directory user.

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

Sample task:
```yaml (paste below)
  - name: "macOS: Add admin users to local groups"
    user:
      name: "{{ item }}"
      groups: admin
      append: yes
      create_home: no
      mobile: yes
    become: yes
    loop: "{{ admin_users }}"
    when:
      - ansible_distribution == "MacOSX"
```
And if the user does not exist in the local /Users table, create it first with:
```
/System/Library/CoreServices/ManagedClient.app/Contents/Resources/createmobileaccount -n USER -D
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
