### ISSUE TITLE
service_facts prints unnecessary warning

### ISSUE THREAD

**Issue by myllynen** [ansible/ansible#78541]
### Summary

On recent Linux distributions `/usr/sbin/service --status-all` returns nothing so the following `grep` in the command fails and causes a warning being displayed for the user:

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/service_facts.py#L108

### Issue Type

Bug Report

### Component Name

service_facts

### Ansible Version

```console
2.13.2
```

### Configuration

```console
Default configuration
```

### OS / Environment

RHEL 9 (even after manually fixing the issue with the `service` script reported at https://bugzilla.redhat.com/show_bug.cgi?id=2118300).

### Steps to Reproduce

```yaml
---
- name: Test
  hosts: all
  become: true
  tasks:
    - name: Gather service facts
      service_facts:
```

### Expected Results

No warning printed.

### Actual Results

```console
TASK [Gather service facts] **************************
[WARNING]: Unable to query 'service' tool (1):
ok: [192.168.122.101]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
