### ISSUE TITLE
K8s module ignores label when creating secret

### ISSUE THREAD

**Issue by rlmanrique** [ansible/ansible#78570]
### Summary

Creating a secret to declare a private repository for ArgoCD (https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/) does not apply the proper label.

Creating it towards OCP 4.9.33

```
- name: Create SSH secret 
  k8s:
    api_version: v1
    kind: Secret
    name: private-repo
    namespace: openshift-gitops
    resource_definition:
      labels:
        argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        url: <url>
        sshPrivateKey: |
          <PRIVATE_KEY>
```
Results in a secret with no label added 

```
oc get secret/private-repo -o yaml

apiVersion: v1
data:
  sshPrivateKey: <encoded private key>
  type: <encoded type>
  url: <encoded url>
kind: Secret
metadata:
  creationTimestamp: "2022-08-17T08:51:51Z"
  name: private-repo
  namespace: openshift-gitops
  resourceVersion: "2259684"
  uid: 8ec15975-3909-491e-abb2-6a3f1aee1680
type: Opaque
```

### Issue Type

Bug Report

### Component Name

k8s

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = <>
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Sep  9 2021, 07:49:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

No output
```

### OS / Environment

RHEL 8.5 execution environment.

Endpoint: OCP 4.9.33

oc version
Client Version: 4.10.18
Server Version: 4.9.33
Kubernetes Version: v1.22.8+c02bd9d

### Steps to Reproduce

```yaml (paste below)
Install Openshift-GitOps in OCP

Create the secret using the following task:

- name: Create SSH secret 
  k8s:
    api_version: v1
    kind: Secret
    name: private-repo
    namespace: openshift-gitops
    resource_definition:
      labels:
        argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        url: <url>
        sshPrivateKey: |
          <PRIVATE_KEY>

```

### Expected Results

The secret should be created with the proper label. Running the command manually (oc apply -f private_repo.yml) with the same information, results in the correct secret:

```
apiVersion: v1
data:
  sshPrivateKey: <key>
  type: <type>
  url: <url>
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/secret-type":"repository"},"name":"private-repo","namespace":"openshift-gitops"},"stringData":{"sshPrivateKey":"-----BEGIN OPENSSH PRIVATE KEY-----\n\n-----END OPENSSH PRIVATE KEY-----\n","type":"git","url":"url"}}
  creationTimestamp: "2022-08-17T08:32:48Z"
  labels:
    argocd.argoproj.io/secret-type: repository
  name: private-repo
  namespace: openshift-gitops
  resourceVersion: "2219155"
  uid: 0721e290-c045-45f1-ad92-bef3d339a15a
type: Opaque

```

### Actual Results

```console
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "api_key": null,
            "api_version": "v1",
            "append_hash": false,
            "apply": false,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "context": null,
            "force": false,
            "host": null,
            "kind": "Secret",
            "kubeconfig": null,
            "merge_type": null,
            "name": "private-repo",
            "namespace": "openshift-gitops",
            "password": null,
            "proxy": null,
            "resource_definition": {
                "apiVersion": "v1",
                "kind": "Secret",
                "labels": {
                    "argocd.argoproj.io/secret-type": "repository"
                },
                "metadata": {
                    "name": "private-repo",
                    "namespace": "openshift-gitops"
                },
                "stringData": {
                    "sshPrivateKey": "\"-----BEGIN OPENSSH PRIVATE KEY-----
-----END OPENSSH PRIVATE KEY-----\"\n",
                    "type": "git",
                    "url": "<url>"
                }
            },
            "src": null,
            "state": "present",
            "username": null,
            "validate": null,
            "validate_certs": null,
            "wait": false,
            "wait_condition": null,
            "wait_sleep": 5,
            "wait_timeout": 120
        }
    },
    "method": "create",
    "result": {
        "apiVersion": "v1",
        "data": {
            "sshPrivateKey": "<encoded private key>",
            "type": "<encoded type>",
            "url": "<encoded url>"
        },
        "kind": "Secret",
        "metadata": {
            "creationTimestamp": "2022-08-17T08:51:51Z",
            "managedFields": [
                {
                    "apiVersion": "v1",
                    "fieldsType": "FieldsV1",
                    "fieldsV1": {
                        "f:data": {
                            ".": {},
                            "f:sshPrivateKey": {},
                            "f:type": {},
                            "f:url": {}
                        },
                        "f:type": {}
                    },
                    "manager": "OpenAPI-Generator",
                    "operation": "Update",
                    "time": "2022-08-17T08:51:51Z"
                }
            ],
            "name": "private-repo",
            "namespace": "openshift-gitops",
            "resourceVersion": "2259684",
            "uid": "8ec15975-3909-491e-abb2-6a3f1aee1680"
        },
        "type": "Opaque"
    }
}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
