### ISSUE TITLE
Git clone failed with error code 128 on Ubuntu 18.04

### ISSUE THREAD

**Issue by antonysigma** [ansible/ansible#78582]
### Summary

When I git clone a public repository with `become: yes` and `become_user: myuser`, I got git error code 128. This error occurs in Ubuntu 18.04, but not in Ubuntu 20.04.

Upon further testing with manual commands, it appears to be an upstream issue with either `sudo` or `git` in Ubuntu 18.04. Here's my tests:

```bash
# This returns error code 128 on Ubuntu 18.04
$ cd path/to/my-ansible-project
$ sudo -u openhtf git ls-remote https://github.com/google/openhtf.git refs/heads/master; echo $?
128

# This returns success on Ubuntu 18.04
$ cd /tmp
$ sudo -u openhtf git ls-remote https://github.com/google/openhtf.git refs/heads/master; echo $?
341aa86....504e8 refs/heads/master
0
```

Question: Given that Ubuntu 18.04 has a fixed `sudo` and `git` release, can Ansible git module workaround this issue?

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.7] 
  config file = None
  configured module search path = ['/home/antony/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/antony/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]
  jinja version = 2.10
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]. This feature will be removed 
from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

### OS / Environment

Ubuntu 18.04 LTS

```
$ sudo --version
Sudo version 1.8.21p2
Sudoers policy plugin version 1.8.21p2
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.21p
```

```
$ git --version
git version 2.17.1
```

### Steps to Reproduce

```yaml
---
- hosts: localhost
  tasks:
  - name: Create myuser account and home folder
    user:
      name: myuser
      home: /var/myuser
      state: present
    become: yes
    register: myuser_user

  - name: Setup git author name and email
    copy:
      src: 'gitconfig'
      dest: '{{ myuser_user.home }}/.gitconfig'
    become: yes
    become_user: '{{ myuser_user.name }}'

  # On Ubuntu 18.04 + git-2.17.1, the git command must be invoked
  # from the directory /var/myuser in order to clone git repos there.
  # So, we clone to the Setup folder instead.
  - name: Download myuser source code
    git:
      repo: https://github.com/google/openhtf.git
      dest: '{{ myuser_user.home }}/openhtf-src/'
      version: 'master'
      force: yes
    become: yes
    become_user: '{{ myuser_user.name }}'
```

### Expected Results

I expect to be able to git clone to `myuser` home directory, using `become: yes` and `become_user: myuser`. I expect to have the same behavior on either Ubuntu 18.04 and Ubuntu 20.04.

### Actual Results

```console
TASK [test_station : Download Openhtf source code] **************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote https://github.com/google/openhtf.git -h refs/heads/master", "msg": "", "rc": 128, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
