### ISSUE TITLE
Become has different requirements on Windows

### ISSUE THREAD

**Issue by jw-maynard** [ansible/ansible#78599]
### Summary

This could be a documentation issue.

When trying to use `become: yes` on a windows host you receive an error about the if you don't also include `become_user`. This is counter to how Ansible `become` works on other platforms where `become_user` is an optional parameter that uses the default `root` user if not specified.

I'd suggest configuring a sane default for `become_user` so it is not required any longer. Looking at the docs https://docs.ansible.com/ansible/latest/user_guide/become.html#become-and-windows they suggest `You can use become with the same user as ansible_user to bypass these limitations and run commands that are not normally accessible in a WinRM session.` so perhaps defaulting to `ansible_user` is a good choice. Otherwise perhaps the local Administrator account?

If a default can't be settled on I'd suggest adding some documentation to the paged linked above right under the Become on Windows header specifying that on Windows `become_user` must be specified with `become`.
``

### Issue Type

Bug Report

### Component Name

runas plugin

### Ansible Version

```console
$ ansible --version
Ansible 2.13.3
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Runner Machine: Ubuntu 22.04
Target Machine: Windows 2022

### Steps to Reproduce

```yaml (paste below)
 name: Download AWS CLI
  ansible.windows.win_get_url:
    url: https://awscli.amazonaws.com/AWSCLIV2.msi
    dest: C:\AWSCLIV2.msi

- name: Install AWS CLI
  ansible.windows.win_package:
    path: C:\AWSCLIV2.msi
    state: present
  become: yes
```

### Expected Results

MSI is installed successfully using Administrator permissions

### Actual Results

```console
2022-08-19T19:57:51Z:     amazon-ebs.windows_2022: TASK [common : Install AWS CLI] ************************************************
2022-08-19T19:57:51Z:     amazon-ebs.windows_2022: task path: /home/runner/work/packer_builds/packer_builds/ansible/roles/common/tasks/win32nt/aws_cli.yml:7
2022-08-19T19:57:51Z:     amazon-ebs.windows_2022: fatal: [default]: FAILED! =>
2022-08-19T19:57:51Z:     amazon-ebs.windows_2022:   msg: 'No setting was provided for required configuration plugin_type: become plugin: runas setting: become_user '
2022-08-19T19:57:51Z:     amazon-ebs.windows_2022:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
