### ISSUE TITLE
feature request: allow multiple local .deb with apt module

### ISSUE THREAD

**Issue by astropanic** [ansible/ansible#7863]
When I have multiple .deb files in my filesystem, and want install them with one apt task like that:

```
- name: install postgresql
  apt:
    deb=/postgresql/deb/postgresql-9.3/{{ item }}
    state=installed
  with_items:
    - postgresql-9.3_9.3.4-1.pgdg70+1_amd64.deb
    - postgresql-client-common_154.pgdg70+1_all.deb
    - postgresql-contrib-9.3_9.3.4-1.pgdg70+1_amd64.deb
    - postgresql-client-9.3_9.3.4-1.pgdg70+1_amd64.deb
    - postgresql-common_154.pgdg70+1_all.deb
```

All .deb package names are joined with comma, which produces an error message like file not found.

In this scenario there should be no joining with comma.

**Comment by robertjung** [comment]
:+1:

**Comment by mpdehaan** [comment]
I'd rather see comma joining functional really than to not join them.

**Comment by astropanic** [comment]
@mpdehaan , how would you install multiple local .deb files with one invocation of the apt module with the current implementation ?

**Comment by jimi-c** [comment]
This should be an easy fix. We just need to split the "deb" field on commas in `def install_deb()` and loop over the list. Right now it assumes there is only one .deb in the list.

**Comment by jimi-c** [comment]
I've created the above patch, which works in my testing, if you'd like to try it out.

**Comment by astropanic** [comment]
this will fix this issue too, https://github.com/ansible/ansible/issues/7513

**Comment by jimi-c** [comment]
@astropanic thanks, I didn't realize there was a dupe. I've closed #7513 so we can track it here. As soon as I see a couple more +1's just to make sure my testing didn't miss anything, I can merge this in.

**Comment by sairez** [comment]
just ran in to this issue. +1 to fix

**Comment by jimi-c** [comment]
Great, I've gone ahead and merged in the above patch, so this should be resolved now. Thanks!

**Comment by ghost** [comment]
I have the same issue with ansible 1.9.3-1ppa~trusty

It will be nice if we can use with_items 
and provide a local deb (files) and install it remotly if needed

My workaround is 

```
  - name: copy deb packages
    action: copy
    args:
      src: deb/{{item}}
      dest: /var/cache/apt/archives/{{item}}
      owner: root
      group: root
      mode: 0644
      backup: no
    with_items:
      - jsonlint_1.3.1-2_all.deb
      - php-cli-prompt_1.0.0+dfsg-1_all.deb
      - php-json-schema_1.5.0-1_all.deb
      - php-symfony-console_2.7.5+dfsg-1_all.deb
      - php-symfony-finder_2.7.5+dfsg-1_all.deb
      - php-symfony-process_2.7.5+dfsg-1_all.deb
      - composer_1.0.0~alpha10+20150602-2_all.deb

  - name: install deb packages manually
    action: shell dpkg-query -f '${Package}\n' -W {{item.name}} || dpkg -i /var/cache/apt/archives/{{item.deb}}
    register: deb
    changed_when: deb.stdout != item.name
    with_items:
      - { name: jsonlint, deb: jsonlint_1.3.1-2_all.deb }
      - { name: php-json-schema, deb: php-json-schema_1.5.0-1_all.deb }
      - { name: php-cli-prompt, deb: php-cli-prompt_1.0.0+dfsg-1_all.deb }
      - { name: php-symfony-console, deb: php-symfony-console_2.7.5+dfsg-1_all.deb }
      - { name: php-symfony-finder, deb: php-symfony-finder_2.7.5+dfsg-1_all.deb }
      - { name: php-symfony-process, deb: php-symfony-process_2.7.5+dfsg-1_all.deb }
      - { name: composer, deb: composer_1.0.0~alpha10+20150602-2_all.deb }
```
