### ISSUE TITLE
apt module with lock_timeout option not working as expected

### ISSUE THREAD

**Issue by m-adawi** [ansible/ansible#78658]
### Summary

I'm trying to make Ansible install some packages on some hosts in a playbook. The playbook installs packages in different tasks and the hosts have puppet installed which sometimes installs packages to the hosts as well. I'm getting a lock error as you can see in the results section. I expected that using lock_timeout will make the task wait for the lock to be released but I tested it on my laptop by running an `apt install` command and then running the playbook while the apt command is still running and the task fails immediately instead of waiting for the lock to be released.

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
2.12.3
```

### Configuration

```console
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True

BECOME:
======

CACHE:
=====

CALLBACK:
========

ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ubuntu 20.04

### Steps to Reproduce

To run this playbook (replacing package_name with some package) while an `apt install` command is already running 
```yaml (paste below)
- name: test
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
  - name: Install package
    apt:
      name: package_name
      lock_timeout: 3600
```

### Expected Results

To have Ansible apt task to wait for apt lock to be released and then to install the apt package(s)

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "cache_update_time": 1661775680,
    "cache_updated": true,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "fail_on_autoremove": false,
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "lock_timeout": 3600,
            "name": "package_name",
            "only_upgrade": false,
            "package": [
                "package_name"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": true,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "upgrade": null
        }
    },
    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'package_name'' failed: E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 226048 (apt)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?\n",
    "rc": 100,
    "stderr": "E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 226048 (apt)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?\n",
    "stderr_lines": [
        "E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 226048 (apt)",
        "E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
There is `Dpkg` option for lock timeout that we should add whenever we shell out to CLI.

**Comment by sivel** [comment]
As of now, we only handle lock issues when interacting with the cache via the python API.  However, we likely need to pass `-o DPkg::Lock::Timeout=<timeout_in_seconds>` via all CLI operations too.

**Comment by rtorresa** [comment]
affects also ansible 2.14

**Comment by pagey101** [comment]
Any idea when this might be fixed? I'm running Ansible with Puppet, now I'm getting clashes and really do not want to add logic to every apt reference to wait for the lock :(

**Comment by pagey101** [comment]
The above patch makes sense, however I've opted to use a wrapper as below (added as `/usr/local/bin/apt` with `0755` permissions):

```
#!/bin/bash
/usr/bin/apt -o DPkg::Lock::Timeout=60 "$@"
```

**Comment by brihter** [comment]
For anyone facing the same issue, here's one way of going around it:

```yaml
- name: wait until apt lock is released
  shell: lsof -w /var/lib/apt/lists/lock | wc -l
  register: lock
  until: lock.stdout == "0"
  retries: 10
  delay: 10

- name: wait until apt lock_frontend is released
  shell: lsof -w /var/lib/dpkg/lock-frontend | wc -l
  register: lock_frontend
  until: lock_frontend.stdout == "0"
  retries: 10
  delay: 10
```

Hope it helps.

**Comment by xBr0th3rx** [comment]
Is there a status on the update or when this will be fixed?

**Comment by hellcry37** [comment]
I am also interested what is the status for this because one year after still happens with ansible v2.15.6

**Comment by fs30000** [comment]
Still happening on Debian 12, ansible 2.14.3, while executing 2 playbooks with apt tasks simultaneously on another debian 12 host.  If this never worked, then why does the documentation lists it as an option?

**Comment by HenriWahl** [comment]
Same here.

Does anybody know if putting the option `Dpkg::Lock::Timeout=600` or something like that into a file like */etc/apt/apt.conf.d/99locktimeout* would help or is this only intended to be used in CLI?

**Comment by hellcry37** [comment]
Since nobody will fix this I'll leave this code to be used instead and help others:
```yaml
- name: Wait until apt lock is released
  ansible.builtin.shell:
    cmd: set -o pipefail && lsof -w /var/lib/apt/lists/lock | wc -l
    executable: /bin/bash
  changed_when: false
  failed_when: lock.rc != 0 and lock.rc != 1
  register: lock
  until: lock.stdout == "0"
  retries: 30
  delay: 10

- name: Wait until apt lock_frontend is released
  ansible.builtin.shell:
    cmd: set -o pipefail && lsof -w /var/lib/dpkg/lock-frontend | wc -l
    executable: /bin/bash
  changed_when: false
  failed_when: lock_frontend.rc != 0 and lock_frontend.rc != 1
  register: lock_frontend
  until: lock_frontend.stdout == "0"
  retries: 30
  delay: 10
```
