### ISSUE TITLE
uri module with dest always result in changed task state

### ISSUE THREAD

**Issue by eoli3n** [ansible/ansible#78695]
### Summary

uri module is not idempotent when running with ``dest``

See https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py#L728

### Issue Type

~Bug Report~
Feature Idea

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.3]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.10.6 (main, Aug  4 2022, 19:16:09) [GCC 10.2.1 20201203]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Void Linux, latest

### Steps to Reproduce

```yaml (paste below)
---
- hosts: localhost
  tasks:
    - name: test uri
      uri:
        url: https://www.duckduckgo.com
        dest: /tmp/uri

    - name: test uri twice
      uri:
        url: https://www.duckduckgo.com
        dest: /tmp/uri
```

### Expected Results

```
TASK [test uri] ****************************************************************************************************
changed: [localhost]

TASK [test uri twice] **********************************************************************************************
ok: [localhost]
```

### Actual Results

```console
TASK [test uri] ****************************************************************************************************
changed: [localhost]

TASK [test uri twice] **********************************************************************************************
changed: [localhost]
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
