### ISSUE TITLE
yum_repository module has keepcache which is not supported in repositories

### ISSUE THREAD

**Issue by jskacel** [ansible/ansible#78693]
### Summary

Module `yum_repository` have option for `keepcache`, which is not supported for repository (it should be only in `yum.conf`).

Ref: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-yum#sec-Setting_main_Options

### Issue Type

Bug Report

### Component Name

yum_repository

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

RHEL8

### Steps to Reproduce

```yaml (paste below)
---
- name: Repository reproducer
  hosts: localhost

  vars:
    ansible_connection: local

  tasks:
    - name: add repository
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://dl.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/
        keepcache: 0
```
```
# dnf update
# grep keepcache /var/log/dnf.log
```

### Expected Results

No warning in /var/log/dnf.log

### Actual Results

```console
# grep keepcache /var/log/dnf.log
2022-09-02T14:33:07+0200 DEBUG Unknown configuration option: keepcache = 0 in /etc/yum.repos.d/epel.repo
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
