### ISSUE TITLE
ansible_distribution_release is not set for Debian bullseye where testing was added

### ISSUE THREAD

**Issue by toralf** [ansible/ansible#78706]
### Summary

ansible_distribution_release is set to "n/a"

### Issue Type

Bug Report

### Component Name

ansible.builtin.apt_repository

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.3]
  config file = None
  configured module search path = ['/home/tfoerste/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/tfoerste/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/lib/python-exec/python3.10/ansible
  python version = 3.10.6 (main, Aug 25 2022, 09:09:35) [GCC 11.3.0]
  jinja version = 3.1.2
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
<empty>
```

### OS / Environment

hsot is Gentoo, target system is Debian bullseye

### Steps to Reproduce

```yaml (paste below)
- name: Configure repository "backports"
  ansible.builtin.apt_repository:
    filename: 'backports'
    repo: "deb http://mirror.hetzner.com/debian/packages {{ ansible_distribution_release }}-backports main contrib non-free"
    state: present
```

The problem is the content of this file (it is bullseye and later `testing` was added as an apt source):

cat /etc/os-release 
```text
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Expected Results

$> cd /etc/apt/sources.list.d/
$> cat tor.list 
deb https://deb.torproject.org/torproject.org bullseye main

### Actual Results

```console
fatal: [elster]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'http://mirror.hetzner.com/debian/packages n/a-backports Release' does not have a Release file."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
