### ISSUE TITLE
Warning about python interpreter on armhf only

### ISSUE THREAD

**Issue by heini** [ansible/ansible#78704]
### Summary

When I run a playbook on several Debian Bullseye hosts, I get the following warning ONLY from the **armhf** one:
```
[WARNING]: Platform linux on host XXX is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.12/reference_appendices/interpreter_discovery.html for more information.
```
although it runs the same Debian version and there's not difference to the amd64 hosts w.r.t. Python.

### Issue Type

Bug Report

### Component Name

gather_facts

### Ansible Version

```console
% ansible --version
ansible [core 2.12.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/heini/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/heini/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:19:32) [GCC 12.1.0]
  jinja version = 3.0.3
  libyaml = True
```
Note: This is the only host already running Debian Bookworm, hence the Python 3.10

### Configuration

```console
% ansible-config dump --only-changed -t all                                                                                 :(

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Target OS: Debian 11 (Bullseye), amd64 and armhf
Host OS Debian 12 (Bookworm/Testing)

### Steps to Reproduce

Example from the documentation:
```yaml (paste below)
---
- hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

# Tasks for all Debian hosts
- hosts: os_Debian
  gather_facts: False
  tasks:
    - debug:
        var: ansible_facts['fqdn']
```

### Expected Results

No Python interpreter warning on ALL hosts

### Actual Results

```console
Python interpreter warning on armhf host only.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
