### ISSUE TITLE
Add `content` parameter to `template` module

### ISSUE THREAD

**Issue by septatrix** [ansible/ansible#78726]
### Summary

Currently I often employ the copy module together with variables inside the content field. The documentation however says that this may result in an unpredictable output.
An alternative would be to use the template module however it does not support the content parameter. Instead one needs to create a separate file for every such use case.

It would be great if either the template module could support this use cases or the copy module could be fixed such that it works with variables (or at least specify more in depth which problems may arise as I did not encounter any yet).

### Issue Type

Feature Idea

### Component Name

template

### Additional Information

```yaml
- name: Assign fixed IP to client using template
  template:
    content: "{{ vpn_id }}" # proposed parameter
    dest: /etc/openvpn/ccd/{{ inventory_hostname }}
- name: Assign fixed IP to client
  copy:
    content: "{{ vpn_id }}" # or make this work reliable
    dest: /etc/openvpn/ccd/{{ inventory_hostname }}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
