### ISSUE TITLE
Can no longer define changed status for shell or command?

### ISSUE THREAD

**Issue by d-tork** [ansible/ansible#78744]
### Summary

The [documentation for error handling](https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#defining-changed) says I can define "changed" for builtin modules `shell` and `command` by using a combination of parameters `register` and `changed_when`. I did so, exactly as the documentation shows, with a script designed to exit with code 1 or 0. 

The error is 
```
fatal: [default]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: changed_when, register. Supported parameters include: creates, warn, removes, stdin_add_newline, executable, stdin, chdir, strip_empty_ends, _raw_params, argv, _uses_shell."}
```

Is this just a matter of the parameters (and functionality!) being removed and the documentation out of date? Or is this a bug? 

Using ansible core 2.13.3, python 3.10.6

### Issue Type

Documentation Report

### Component Name

shell and command

### Ansible Version

```console
ansible [core 2.13.3]
  config file = None
  configured module search path = ['/Users/dtork/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/dtork/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Sep  8 2022, 21:17:08) [Clang 10.0.0 (clang-1000.10.44.4)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
<no output>
```

### OS / Environment

macOS 10.13.6, running on a Debian Bullseye Vagrant machine via VirtualBox.

### Additional Information

It won't be misleading anymore. 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py)
* [`lib/ansible/modules/shell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/shell.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This does not appear to be a bug.

You didn't show your code, but you probably didn't do it "exactly as the documentation shows", because the code in the documentation cannot produce that error.  To achieve that result you need something like the following:

```yaml
  - name: Report 'changed' when the return code is not equal to 2
    ansible.builtin.command:
      cmd: /usr/bin/true
      register: bass_result
      changed_when: bass_result.rc != 2
```

This has `register` and `changed_when` at the wrong level; they are generic task parameters that are usable in any task, not module parameters. The correct way to use them is, as shown in the documentation, indented to the same level as other task parameters:
```yaml
  - name: Report 'changed' when the return code is not equal to 2
    ansible.builtin.command:
      cmd: /usr/bin/true
    register: bass_result
    changed_when: bass_result.rc != 2
```
