### ISSUE TITLE
Add module for managing /etc/hosts entries

### ISSUE THREAD

**Issue by heini** [ansible/ansible#78747]
### Summary

Coming from Puppet and Salt, I found that Ansible has no module to manage entries in the `/etc/hosts` file. (There's a community module for Windows only, though).

Such a module should support managing /etc/hosts entries on Linux (and other Unix variants) as well as Windows (only the path on disk differs from the Linux one, the file format itself is the same) so that one can write a playbook like

```yaml
- name: Manage myhost
  ansible.builtin.hosts:
    state: present
    address: 10.11.12.13
    names:
      - myhost.mydomain.net
      - myhost
    comment: Some comment
```
to get en entry like
```
10.11.12.13 myhost.mydomain.net myhost # Some comment
```

### Issue Type

Feature Idea

### Component Name

hosts

### Additional Information

```yaml
- name: Manage myhost
  ansible.builtin.hosts:
    state: present
    address: 10.11.12.13
    names:
      - myhost.mydomain.net
      - myhost
    comment: Some comment
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
