### ISSUE TITLE
"Invalid data passed to 'loop', it requires a list, got this instead: <built-in method values of dict object at 0x7f63b782bf80>.

### ISSUE THREAD

**Issue by rforberger** [ansible/ansible#78759]
### Summary

When trying to pass a variable called i.e. sysctl.values to loop, I will get the above error.

### Issue Type

Bug Report

### Component Name

debug (only used for debugging)

### Ansible Version

```console
$ ansible --version
ansible 2.9.27
  config file = /home/rf/.ansible.cfg
  configured module search path = ['/home/rf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

[I] </m/d/playground>-2-> ansible-config dump --only-changed
ANSIBLE_PIPELINING(/home/rf/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/rf/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_FORKS(/home/rf/.ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/rf/.ansible.cfg) = ['/home/rf/hosts']
INVENTORY_CACHE_ENABLED(/home/rf/.ansible.cfg) = True
```

### OS / Environment

Fedora 36

### Steps to Reproduce

```yaml (paste below)
- name: Test
  hosts: localhost
  gather_facts: True
  tasks:
    - debug:
        msg: "{{ item }}"
      loop: "{{ sysctl2 }}"
    - debug:
        msg: "{{ item }}"
      loop: "{{ sysctl.values }}"
  vars:
    sysctl:
      values:
        - { name: "net.ipv4.ip_forward", value: "1" }
    sysctl2:
        - { name: "net.ipv4.ip_forward", value: "1" }
```

### Expected Results

Output of debug using sysctl.values

### Actual Results

```console
PLAY [Test] ********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'net.ipv4.ip_forward', 'value': '1'}) => {
    "msg": {
        "name": "net.ipv4.ip_forward",
        "value": "1"
    }
}

TASK [debug] *******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: <built-in method values of dict object at 0x7f63b782bf80>. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

PLAY RECAP *********************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
