### ISSUE TITLE
apt module is not idempotent with package versions

### ISSUE THREAD

**Issue by evilhamsterman** [ansible/ansible#78799]
### Summary

I'm installing TimescaleDB with PostgreSQL for Zabbix. Zabbix requires a specific major.minor version of TimescaleDB, and does not support the latest version. So I have to install a specific version and to prevent people from upgrading it I pinned the package. However everytime I run the playbook it reports the package changed even though it did not which later triggers a restart of the DB to load the new library, which I don't want to do unless a new version is actually installed.

It happens whether is use `packagename='2.7.*'` or a completely specific version like `packagename='2.7.2~ubuntu22.04`

### Issue Type

Bug Report

### Component Name

ansible.builtin.apt

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]
  config file = /home/dmills/development/ansible/ansible.cfg
  configured module search path = ['/home/dmills/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmills/.virtualenvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/dmills/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/dmills/.virtualenvs/ansible/bin/ansible
  python version = 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CACHE_PLUGIN(/home/dmills/development/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/dmills/development/ansible/ansible.cfg) = /tmp
CALLBACKS_ENABLED(/home/dmills/development/ansible/ansible.cfg) = ['timer', 'yaml']
DEFAULT_FORKS(/home/dmills/development/ansible/ansible.cfg) = 10
DEFAULT_MANAGED_STR(/home/dmills/development/ansible/ansible.cfg) = This file is managed by IT with Ansible. Any modifications will be lost
DEFAULT_ROLES_PATH(/home/dmills/development/ansible/ansible.cfg) = ['/home/dmills/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/home/dmills/development/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/dmills/development/ansible/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(/home/dmills/development/ansible/ansible.cfg) = /home/dmills/development/ansible/vault-pass
HOST_KEY_CHECKING(/home/dmills/development/ansible/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/dmills/development/ansible/ansible.cfg) = ignore

CACHE:
=====

jsonfile:
________
_uri(/home/dmills/development/ansible/ansible.cfg) = /tmp

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/dmills/development/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/home/dmills/development/ansible/ansible.cfg) = False
pipelining(/home/dmills/development/ansible/ansible.cfg) = True
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

Relevant playbook portion
```yaml (paste below)
---
- ansible.builtin.import_role:
    name: geerlingguy.postgresql
  become: true

- name: Copy TimescaleDB GPG key
  become: true
  ansible.builtin.copy:
    src: files/timescaledb.gpg
    dest: /usr/share/keyrings/timescaledb.gpg
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Add TimescaleDB repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/timescaledb.gpg] https://packagecloud.io/timescale/timescaledb/ubuntu/ jammy main
    state: present
    update_cache: true

- name: Pin TimescaleDB version to 2.7
  become: true
  template:
    src: templates/pin-timescaledb.j2
    dest: /etc/apt/preferences.d/timescaledb
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install TimescaleDB
  become: true
  ansible.builtin.apt:
    name:
      - timescaledb-2-postgresql-14='2.7.*'
      - timescaledb-2-loader-postgresql-14='2.7.*'
    state: present
  notify: restart postgresql

- name: Flush Handlers
  become: true
  meta: flush_handlers

```

my file for pining the package version
```
Package: timescaledb-2-postgresql-14
Pin: version 2.7.*
Pin-Priority: 1001

Package: timescaledb-2-loader-postgresql-14
Pin: version 2.7.*
Pin-Priority: 1001
```

### Expected Results

On subsequent runs of the playbook the install package task should not be marked as changed

### Actual Results

```console
The install task is marked as changed and the handler to restart PostgreSQL is run regardless of if a new version is actually installed. 

Output from a second run of the playbook with -vv


TASK [Install TimescaleDB] **************************************************************************************************************************************************************************************************
task path: /home/dmills/development/ansible/playbooks/zabbix/tasks/db.yml:31
NOTIFIED HANDLER geerlingguy.postgresql : restart postgresql for zabbix-stage.corp.qumulo.com
changed: [zabbix-stage.corp.qumulo.com] => changed=true 
  cache_update_time: 1663361417
  cache_updated: false
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    timescaledb-2-loader-postgresql-14 is already the newest version (2.7.2~ubuntu22.04).
    timescaledb-2-postgresql-14 is already the newest version (2.7.2~ubuntu22.04).
    0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
  stdout_lines: <omitted>
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
