### ISSUE TITLE
[iptables] `chain_management: yes` for `jump: CHAIN`

### ISSUE THREAD

**Issue by wookietreiber** [ansible/ansible#78807]
### Summary

I'm thankful that chain management got added with https://github.com/ansible/ansible/pull/76378. This feature request is about an additional condition for chain creation. 

At the moment, `chain_management: yes` only works with `chain: name`. It does not work with `jump: CHAIN`, which I would like. I noticed this because I have a setup that attaches a chain **before** rules are added to it, see example below.

### Issue Type

Feature Idea

### Component Name

iptables

### Additional Information

This scenario fails: 

```yml
- name: attach TCP chain for new connections
  iptables:
    chain: INPUT
    chain_management: yes
    protocol: tcp
    ctstate: NEW
    syn: match
    jump: TCP

- name: accept new SSH connections
  iptables:
    chain: TCP
    protocol: tcp
    destination_port: '22'
    jump: ACCEPT
    comment: ssh
```

```
fatal: [frontend1]: FAILED! => {
  ...
}

STDERR:

iptables v1.4.21: Couldn't load target `TCP':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
```

It works when you flip it, i.e.:

```yml
- name: accept new SSH connections
  iptables:
    chain: TCP
    chain_management: yes
    protocol: tcp
    destination_port: '22'
    jump: ACCEPT
    comment: ssh

- name: attach TCP chain for new connections
  iptables:
    chain: INPUT
    protocol: tcp
    ctstate: NEW
    syn: match
    jump: TCP
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
