### ISSUE TITLE
Included files optimization can cause different tasks on different hosts to be assumed to be the same task in the free strategy

### ISSUE THREAD

**Issue by jnm27** [ansible/ansible#78805]
### Summary

I hit a breaking bug that was causing a variable to have the "wrong" value intermittently. After a lot of research and testing with ANSIBLE_DEBUG, I narrowed it down to included_file.py's optimization that attempts to group included_files on different hosts as being the same.

Consider the pseudo-playbook pasted in the "Steps to Reproduce" section.

Now consider that hostA executes the first include 10 seconds in, but for some reason hostB is stuck gathering facts or something. Then hostA finishes subtasks.yml with some_var = False, and moves on to the second include with some_var = True. hostB is now unstuck and **at the same time** it starts the first include with some_var = False.

IncludedFile sees these two hosts executing at the same time and including the "same" file, so it groups them into a single inc_file with both hostA and hostB in its host list, using the task from hostA. This means hostB also effectively enters the second invocation with some_var = True.

Here is a patch that works around the issue (verified in testing):
```diff
--- included_file.py    2022-09-18 23:33:57.583080530 +0000
+++ /usr/local/lib/python3.8/site-packages/ansible/playbook/included_file.py    2022-09-18 23:33:50.139105451 +0000
@@ -201,23 +201,27 @@

                     idx = 0
                     orig_inc_file = inc_file
-                    while 1:
-                        try:
-                            pos = included_files[idx:].index(orig_inc_file)
+                    # NOTE: This commented out code has a bug in the free stategy which causes different tasks on different hosts to
+                    # be considered the "same" task, which can cause the task to run with the wrong variables on some of the hosts.
+                    # The workaround is to remove the optimization that tries to group included files, and just always treat each include
+                    # for each host as separate.
+                    #while 1:
+                        #try:
+                            #pos = included_files[idx:].index(orig_inc_file)
                             # pos is relative to idx since we are slicing
                             # use idx + pos due to relative indexing
-                            inc_file = included_files[idx + pos]
-                        except ValueError:
-                            included_files.append(orig_inc_file)
-                            inc_file = orig_inc_file
+                            #inc_file = included_files[idx + pos]
+                        #except ValueError:
+                    included_files.append(orig_inc_file)
+                    inc_file = orig_inc_file

-                        try:
-                            inc_file.add_host(original_host)
-                            inc_file._results.append(res)
-                        except ValueError:
+                    #    try:
+                    inc_file.add_host(original_host)
+                    inc_file._results.append(res)
+                    #    except ValueError:
                             # The host already exists for this include, advance forward, this is a new include
-                            idx += pos + 1
-                        else:
-                            break
+                    #        idx += pos + 1
+                    #    else:
+                    #        break

         return included_files
```

The real fix should probably be to ensure that the \_\_eq\_\_ of IncludedFile properly identifies when files are different.

### Issue Type

Bug Report

### Component Name

included_file.py

### Ansible Version

```console
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = [omitted]
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /etc/ansible/collections:/usr/share/ansible/collections:/root/.ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING = True
BECOME_ALLOW_SAME_USER = True
DEFAULT_FORKS = 100
DEFAULT_LOAD_CALLBACK_PLUGINS = True
DEFAULT_LOCAL_TMP = /tmp/.ansible_root/ansible-local-3390496bn8gbaj
DEFAULT_STRATEGY = free
DEFAULT_TIMEOUT = 12
DIFF_ALWAYS = True
DIFF_CONTEXT = 0
DISPLAY_SKIPPED_HOSTS = False
DUPLICATE_YAML_DICT_KEY = ignore
HOST_KEY_CHECKING = False
INTERPRETER_PYTHON = auto_silent
INVENTORY_CACHE_ENABLED = True
INVENTORY_ENABLED = ['auto', 'host_list', 'script', 'ini', 'yaml']
LOCALHOST_WARNING = False
MAX_FILE_SIZE_FOR_DIFF = 10485760

CALLBACK:
========

default:
_______
display_skipped_hosts = False

CONNECTION:
==========

local:
_____
pipelining = True

paramiko_ssh:
____________
host_key_checking = False

psrp:
____
pipelining = True

ssh:
___
host_key_checking = False
pipelining = True
ssh_args = -C -o ControlMaster=auto -o ControlPersist=10800s
timeout = 12

winrm:
_____
pipelining = True

SHELL:
=====

sh:
__
remote_tmp = /tmp/.ansible_${USER}
```

### OS / Environment

RHEL8

### Steps to Reproduce

```yaml (paste below)
- hosts: hostA, hostB
  strategy: free
  tasks:
    - name: Include first time
       include_tasks:
         file: subtasks.yml
       vars:
         some_var: False

   - name: Include second time
      include_tasks:
        file: subtasks.yml
      vars:
        some_var: True
```

### Expected Results

hostA and hostB's parallel execution execute their tasks separately, not losing data.

### Actual Results

```console
hostA and hostB executed the same task in parallel, with the wrong variables for hostB.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/playbook/included_file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/included_file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
@jnm27 I haven't been able to reproduce this. I tested with your playbook as-is, and then modified it to run for many hosts to try to increase the chance of reproducing, some gathering facts and some getting a brief sleep command to make sure different hosts are running different includes and all of them consistently displayed the correct result for the value of the variable.

I am only able to get sporadic weirdness by commenting out the task uuid comparison in the `__eq__` method https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/included_file.py#L58. Which was added in 2.10+ by 247e43b25244720f81e41febf0993f4b435fcb3d (fixing a very similar looking bug).

I'm guessing there is something missing from your reproducer. Can you walk me through the steps you took to determine your patch fixed the issue?

needs_info

**Comment by jnm27** [comment]
@s-hertel I wouldn't expect my reproduce code to reproduce it as-is. I have a very very large playbook running on 20+ hosts at a time in free mode. It has to be a very specific timing situation. We have some VMs and some physical machines executing the same code, and the VMs take longer to get to that section because they have to wait for the hypervisors first. That's how we found it.

What I ultimately did to get a smaller test-case was take out a [still large] section of our playbook and add a wait_for: at the beginning with a varying number of seconds per host (which simulated the large setup time for VMs while the physical machines went forward through the first task). Even with this, running on about 20 hosts, I was only able to reproduce it by running in a loop about once every 10 times or so.

To verify that my patch fixed it, I ran the same test case overnight in the loop and it did not hit it. I was also confident in it because I saw what was happening in the code with extra debug statements showing that it was adding the hosts that were at the first task to the inc_file for a host who was at the second task at the time. This is visible even without extra debug code, because ansible says something in the output like
`included: test.yml for [hostA, hostB]`, which indicates that it's using the same IncludedFile for both hostA and hostB.

**Comment by sivel** [comment]
Your patch breaks other behavior, so it's not the correct change in any case.  It breaks the output of the linear strategy with this reproducer:

```
.
├── 40317.yml
│   │ - hosts: all
│   │   gather_facts: false
│   │   tasks:
│   │   - include_tasks: 'inklud.yml'
│   │     with_items: [ 1,2,1,3,2,4,4,4,4,4,3]
├── hosts
│   │ localhost1 ansible_connection=local
│   │ localhost2 ansible_connection=local
│   │ localhost3 ansible_connection=local
│   │ localhost4 ansible_connection=local
│   │ localhost5 ansible_connection=local
└── inklud.yml
    │ - debug:
    │     msg: '{{ item }}'
```

Ultimately your patch is never grouping hosts of the same task together, and always adding new tasks per host, so that all tasks for a single host are executed on their own, instead of being grouped, which effectively turns includes into `serial: 1`

I still don't see how the problem you describe can occur.

**Comment by s-hertel** [comment]
@jnm27 Thanks for the prompt response.  How did you ensure the wrong include would cause failure when you ran it overnight? I do see output like `included: test.yml for [hostA, hostB]`, but only when both hosts are ready to begin that particular include.

Here's a complete test case I was unable to reproduce with: https://gist.github.com/s-hertel/b0f4c0d6a01d4e6eb4ffd4b0e8c03dbf
I didn't run it overnight, but have run it a few dozen times now without being able to reproduce. Inside the included file, I assert the variable is equal to a host var, and then increment the host var at the end of the included_tasks. This way I could let it run unattended while testing.

Since the task uuid is include in `__eq__`, I don't see how this issue could occur either. Maybe there is something else going on.

**Comment by jnm27** [comment]
@sivel I didn't understand why the \_\_eq\_\_ wasn't working either and I didn't expect my patch to be the final fix, it was just a workaround. Since we use free almost exclusively, that side effect doesn't bother us.
My first fix was going to be in \_\_eq\_\_ but when I debugged the task fields, I couldn't see differences between them, so I suspected some other field needed to be checked.

@s-hertel Basically what our code is doing is that the first time it runs, we expect that a script does not exist (it is added later), so we set failed_when to False if the return code to the shell module is 127 and that variable is set indicating that it's the first run. Then later code adds that script, and it is called again with the variable indicating that it's not the first run.

Maybe it is more complex than the simple case in my producer. Here is a bigger outline for my real test case:

test.yml:

1. Move /bin/script to /bin/script.bak
2. Wait for a variable number of seconds based on the hostname, ranging from 0 to 30 seconds
3. Include "test_parent_task.yml"
4. Include "test_task.yml" with first_time: False under vars

test_parent_task.yml:
1. Include "test_task.yml" with first_time: True under vars

test_task.yml:
1. Include Role "complex_role" (which is one of our real roles where we saw this)

The reason I structured the test like this is because I initially thought it was related to nested includes/roles, so I modeled it closely to our existing infrastructure leading up to calling complex_role in the real environment. I thought it was unrelated ultimately, so when I opened this ticket I didn't mention it.

complex_role:
1. Include "sub_task_file1.yml" in a loop

sub_task_file1.yml:
1. Include "sub_task_file2.yml" in a loop

sub_task_file2.yml:
1. Call shell command referencing /bin/script, with failed_when: result.rc not in ([0, 127] if first_time else [0])
2. [For this test only] Move /bin/script.bak back to /bin/script to simulate the full process where it gets created after this.

I can also try to make a simpler test case without proprietary information in it that I verify actually reproduces it if I have time.

**Comment by jnm27** [comment]
I am able to consistently reproduce it like this (3/3 times so far):

```
>cat test.yml
---
- hosts: "{{ target_host }}"
  gather_facts: False
  strategy: free
  tasks:
    - name: Remove /tmp/test_script.sh
      shell:
        cmd: rm /tmp/test_script.sh
        removes: /tmp/test_script.sh

    - name: Wait a bit
      shell:
        cmd: "sleep {{ test_timeout|float + (0.1 * host_num|int) }}"
      delegate_to: localhost
      vars:
        host_num: "{{ ansible_play_hosts_all.index(inventory_hostname) }}"

    - name: Include debug task parent
      include_tasks:
        file: test_parent_task.yml

    - name: Include debug task again
      include_tasks:
        file: test_task.yml
      vars:
        first_time: False
```

```
>cat test_parent_task.yml
---
- name: Include debug task
  include_tasks:
    file: test_task.yml
  vars:
    first_time: True
```

```
>cat test_task.yml
---

- debug:
    var: first_time

- name: Test complex role
  include_role:
    name: complex_role
```

```
>cat roles/complex_role/tasks/main.yml
---

- name: Include sub_task_file1.yml in loop
  include_tasks:
    file: sub_task_file1.yml
  loop:
    - 1
  loop_control:
    loop_var: file1_var
```

```
>cat roles/complex_role/tasks/sub_task_file1.yml
---
- name: Include sub_task_file2.yml
  include_tasks:
    file: sub_task_file2.yml
```

```
>cat roles/complex_role/tasks/sub_task_file2.yml
---

- name: Run /tmp/test_script.sh
  shell:
    cmd: "/tmp/test_script.sh"
  register: test_script_result
  failed_when: test_script_result.rc not in ([0, 127] if first_time else [0])

- name: Create /tmp/test_script.sh
  copy:
    content: "#!/bin/bash\necho hello"
    dest: /tmp/test_script.sh
    mode: 0755
```

And running it with target_host=[list of 20 hosts] and test_timeout=1.9 on my system.
