### ISSUE TITLE
Allow additional facts to be discovered

### ISSUE THREAD

**Issue by DonBower** [ansible/ansible#78827]
### Summary

Provide a special section (similar to `pre_tasks` and `post_tasks`) that would a variable to be defined, and default and override values to be set, either by clever jinja2 coding or flat out command script, so that specific facts relevant to the playbook could be gathered, and cached, against a given machine.

currently the only way I know how to set a fact value from the output of a command is to run the `ansible.builtin.shell` or `.command` module, and register the output.  but because the the value is actually in the `.stdout` dictionary item of the registered value, it has to be referenced as such, and this task counts as "changed" every time the playbook is ran.

I guess what I really want is to allow for fact gathering that does not count as "changed" in the `PLAY RECAP`

### Issue Type

Feature Idea

### Component Name

set_fact

### Additional Information

```yaml
# Typical output of vault --version is: Vault v1.10.4 (6a1dde56c18c4a1be2756b931ce3c872d8ca5a76)
- name: Get the current version of Vault
  ansible.builtin.get_fact:
    value: "vault --version | awk {'print $2'} | cut -d 'v' -f 2"
    fact: vaultVersion
    default: 0.0.0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
