### ISSUE TITLE
Cannot use lineinfile or copy modules when the destination file is in a restricted access parent folder

### ISSUE THREAD

**Issue by re-schneider** [ansible/ansible#78832]
### Summary

===== GLOBAL CONTEXT =====

Explanations:
Some modules (lineinfile, copy and maybe others) assume that they have write access to the parent folder in addition to the target file itself due to the 2-steps implementation decision. However, there is some real-life cases where the user/process has write access to a file but not the parent folder and where writing/copying still works in commandline.

The whole point of this issue is to provide reproducers to highlight the discrepancy between commandline expectations and current Ansible modules' behavior and propose a PR to enable such cases to work properly too.

Results:
The playbook fails because the current user does not have write permissions in the parent folder:
```shell
 FAILED! => {"changed": false, "msg": "The destination directory (/var/log) is not writable by the current user. Error was: [Errno 13] Permission denied: b'/var/log/.ansible_tmph9ad0xqzreproducer.log'"}
 or
 FAILED! => {"changed": false, "msg": "Destination /var/log not writable"}
```

Expectations:
The playbook should be able to succeed (as the echo/copy command in the preparation section). That is why the corresponding PR introduces the new option of the temporary folder to keep the 2-steps process while complying with user-expectations.

### Issue Type

Bug Report

### Component Name

lineinfile, copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = None
  configured module search path = ['/Users/remi.schneider/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.4.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/remi.schneider/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 7 and 8 (but applicable to other Linux distro)

### Steps to Reproduce

===== LINE IN FILE module =====

Preparation:

  * sudo touch /var/log/reproducer.log
  * sudo chown ${USER}:$(groups | cut -d' ' -f1) /var/log/reproducer.log
  
  * echo "Hello World ??" > /var/log/reproducer.log (EXPECTATION: write)
  * cat /var/log/reproducer.log (EXPECTATION: read)
 
 
Reproducer playbook:

```yaml
 ---
 - hosts: testvm

   vars:
     - target_file: /var/log/reproducer.log

   tasks:

     - name: Updating a file we have write-access to
       ansible.builtin.lineinfile:
         path: "{{ target_file }}"
         line: "What a beautiful day..."
         state: present
         insertafter: "Hello World ??"
```

===== COPY module =====

Preparation:

  * sudo touch /var/log/greetings.log
  * sudo chown ${USER}:$(groups | cut -d' ' -f1) /var/log/greetings.log

  * echo -e "Willkommen\nBienvenido" > greetings.log
  * cp greetings.log /var/log/

Reproducer playbook:

```yaml
 ---
 - hosts: testvm

   vars:
     - work_file: greetings.log
     - target_path: /var/log

   tasks:
     - name: Adding one more greeting in the local file
       ansible.builtin.lineinfile:
         path: "{{ work_file }}"
         line: Tevetuloa
         state: present
         insertafter: Bienvenido

     - name: Copying file to refresh destination
       ansible.builtin.copy:
         remote_src: yes
         src: "{{ work_file }}"
         dest: "{{ target_path }}/{{ work_file }}"
```

### Expected Results

Expectations:
* lineinfile can add the line
* copy can copy the file over the previous one present

### Actual Results

```console
The playbook fails because the current user does not have write permissions in the parent folder:

 FAILED! => {"changed": false, "msg": "The destination directory (/var/log) is not writable by the current user. Error was: [Errno 13] Permission denied: b'/var/log/.ansible_tmph9ad0xqzreproducer.log'"}
 or
 FAILED! => {"changed": false, "msg": "Destination /var/log not writable"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
