### ISSUE TITLE
Support firstmatch in ansible.builtin.replace

### ISSUE THREAD

**Issue by bendem** [ansible/ansible#78866]
### Summary

I have an httpd config with multiple `<Location>` tags and I'm trying to replace the value of one in the middle like so:
```diff
 <Location /1>
     Require all denied
 </Location>
 <Location /2>
-    Require all denied
+    Require ip 192.168.1.2
 </Location>
 <Location /3>
     Require all denied
 </Location>
```

Using the replace module like so:
```yaml
    - ansible.builtin.replace:
        path: "/etc/httpd/conf.d/auth.conf"
        after: "<Location /2>"
        regexp: 'Require\s+[^\n]+$'
        replace: 'Require ip {{ lemonldap_cluster_ips | join(" ") }}'
      notify: reload httpd
```

I get the following:

```diff
 <Location /1>
     Require all denied
 </Location>
 <Location /2>
-    Require all denied
+    Require ip 192.168.1.2
 </Location>
 <Location /3>
-    Require all denied
+    Require ip 192.168.1.2
 </Location>
```

Looking at the code for the replace module, it's (ignoring required tests and documentations) a single line change:

https://github.com/ansible/ansible/blob/d3d7785472ce18ee79c2abb893be1cf40ff563dd/lib/ansible/modules/replace.py#L286

```diff
     mre = re.compile(params['regexp'], re.MULTILINE)
-    result = re.subn(mre, params['replace'], section, 0)
+    result = re.subn(mre, params['replace'], section, 1 if firstmatch else 0)
```

### Issue Type

Feature Idea

### Component Name

replace

### Additional Information

`firstmatch` is supported in `lineinfile`, I tried to use that instead, but it doesn't use `re.MULTILINE` so I couldn't get it to work correctly.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bendem** [comment]
What I have tried with `lineinfile` and the result:

```yaml
    - ansible.builtin.lineinfile:
        path: "/etc/httpd/conf.d/auth.conf"
        insertafter: "<Location /2>"
        regexp: '^(^\s*)Require .*$'
        line: '\g<1>Require ip {{ lemonldap_cluster_ips | join(" ") }}'
        backrefs: true
```

```diff
 <Location /1>
     Require all denied
 </Location>
 <Location /2>
     Require all denied
 </Location>
 <Location /3>
-    Require all denied
+    Require ip 192.168.1.2
 </Location>
```
