### ISSUE TITLE
ansible.builtin.tempfile does not respect   delegate_facts

### ISSUE THREAD

**Issue by balucio** [ansible/ansible#78868]
### Summary

Using the module `ansible.builtin.tempfile` with `delegate_facts` set to `true` and   `delegate_to` set to `localhost` the registered variable is set on the current host (`inventory_hostname`) and not on `localhost`.

### Issue Type

Bug Report

### Component Name

ansible.builtin.tempfile

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Debian GNU/Linux 11 (bullseye)

### Steps to Reproduce

```yaml (paste below)
- name: Creating temporary directory to collect report
      ansible.builtin.tempfile:
        state: directory
        suffix: lynis
      register: lynis_temp_dir
      connection: local
      delegate_facts: true
      delegate_to: localhost

    - name: debug
      debug:
         var: hostvars['localhost']
```

### Expected Results

I expect that `lynis_temp_dir` is in the output

### Actual Results

```console
The variable is in the output of
    - name: debug
      debug:
         var: hostvars[inventory_hostname]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/tempfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/tempfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
registered variables are not facts

**Comment by s-hertel** [comment]
[ansible_facts](https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html#ansible-facts) can be created with `set_fact`:
```
- set_fact:
    tmp_dir_facts: "{{ lynis_temp_dir }}"
    cacheable: True  # This is how to create an ansible_fact vs variable
  delegate_to: localhost
  delegate_facts: yes
```
