### ISSUE TITLE
Sudo password required when become=false

### ISSUE THREAD

**Issue by aaronhuff** [ansible/ansible#78867]
### Summary

Ansible is failing with `sudo: a password is required` when running `ansible.builtin.file` or `ansible.builtin.find`. The task does not require privilege elevation and is running under the user who owns the folder and files.

Attempted to set `become=false` at runtime, in `ansible.cfg`, in play and in task.

Only workaround I found was to set `become_user=myuserid` for the unprivileged user and it no longer requested password for sudo.

Environment
```
Ubuntu 22.04.1 LTS
ansible [core 2.12.9]
python version = 3.10.6
ansible.netcommon 3.1.1
ansible.utils     2.6.1
```
_NOTE: Replicating the issue have some dependency on the current SSH session to the Ansible server. The active shell/ssh session would continue to work but any new sessions would fail with the permission error (using the same non-privileged user)._

### Issue Type

Bug Report

### Component Name

ansible.builtin.file

### Ansible Version

```console
$ ansible --version
ahuff@ahuff-ansible:~$ ansible --version
ansible [core 2.12.9]
  config file = /home/ahuff/.ansible.cfg
  configured module search path = ['/home/ahuff/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ahuff/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/home/ahuff/.ansible.cfg) = True

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ubuntu 22.04.1 LTS

### Steps to Reproduce

```yaml (paste below)
- name: Prepare environment
  hosts: localhost

  tasks:
    - name: create scripts folder
      ansible.builtin.file:
        path: "scripts"
        state: directory
        mode: 0770
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
```

### Expected Results

Run task as local user without requiring `--ask-become-pass`

### Actual Results

```console
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by fungusakafungus** [comment]
Please provide output of `ansible-inventory --vars --list`

**Comment by konstruktoid** [comment]
I can't reproduce this using `ansible-playbook -v -c local -i '127.0.0.1,' test.yml`.
Tested with ansible 2.13.4 and 2.15.0.dev0.

Where `test.yml` is:
```yaml
- name: Prepare environment
  hosts: localhost

  tasks:
    - name: create scripts folder
      ansible.builtin.file:
        path: "scripts"
        state: directory
        mode: 0770
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
```
