### ISSUE TITLE
Role argument validation appears not to enforce booleans?

### ISSUE THREAD

**Issue by chriscroome** [ansible/ansible#78889]
### Summary

When a variable is defined as a string [Ansible role validation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-argument-validation) appears not to pick up that it is required it to be a boolean?

### Issue Type

Bug Report

### Component Name

role argument validation

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /builds/webarch/gitlab-ci/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all

ANSIBLE_FORCE_COLOR(/builds/webarch/gitlab-ci/ansible.cfg) = True
ANSIBLE_NOCOWS(/builds/webarch/gitlab-ci/ansible.cfg) = True
ANSIBLE_PIPELINING(/builds/webarch/gitlab-ci/ansible.cfg) = True
DEFAULT_ROLES_PATH(/builds/webarch/gitlab-ci/ansible.cfg) = ['/builds/webarch/gitlab-ci/galaxy/roles']
RETRY_FILES_ENABLED(/builds/webarch/gitlab-ci/ansible.cfg) = False
        
CONNECTION:
==========

local:
pipelining(/builds/webarch/gitlab-ci/ansible.cfg) = True
psrp:
pipelining(/builds/webarch/gitlab-ci/ansible.cfg) = True
ssh:
pipelining(/builds/webarch/gitlab-ci/ansible.cfg) = True
winrm:
pipelining(/builds/webarch/gitlab-ci/ansible.cfg) = True

SHELL:
=====
sh:
world_readable_temp(/builds/webarch/gitlab-ci/ansible.cfg) = True
```

### OS / Environment

This has been tested on [Debian Bookworm runing in a Docker container triggered via GitLab CI](https://git.coop/webarch/gitlab-ci).

### Steps to Reproduce

Create [a role with the following](https://git.coop/webarch/gitlab-ci/-/tree/master/roles/validation) `meta/argument_specs.yml`:

```yaml
---
argument_specs:
  main:
    short_description: The main entry point for the validation role.
    options:
      boolean1:
        type: bool
        required: true
        description: A boolean
      boolean2:
        type: bool
        required: true
        description: Another boolean
...
```

The following `defaults/main.yml`:

```yml
---
boolean1: false
boolean2: "no"
...
```

And the following `tasks/main.yml`:

```yml
---
- name: Debug boolean1 variable
  ansible.builtin.debug:
    var: boolean1

- name: Debug boolean1 type
  ansible.builtin.debug:
    msg:
      - "The boolean1 variable is a {{ boolean1 | type_debug }}"

- name: Debug boolean2 variable
  ansible.builtin.debug:
    var: boolean2

- name: Debug boolean2 type
  ansible.builtin.debug:
    msg:
      - "The boolean1 variable is a {{ boolean2 | type_debug }}"
...
```

### Expected Results

I would expect the role to fail validation as `"no"` is string not a boolean.

### Actual Results

```console
ansible-playbook --extra-vars "hostname=localhost" -i "localhost," -c local validation.yml -vv
ansible-playbook [core 2.13.4]
  config file = /builds/webarch/gitlab-ci/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
  jinja version = 3.0.3
  libyaml = True
Using /builds/webarch/gitlab-ci/ansible.cfg as config file
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
PLAYBOOK: validation.yml *******************************************************
1 plays in validation.yml
PLAY [Role argument validation] ************************************************
TASK [Gathering Facts] *********************************************************
task path: /builds/webarch/gitlab-ci/validation.yml:2
ok: [localhost]
META: ran handlers
TASK [validation : Validating arguments against arg spec 'main' - The main entry point for the validation role.] ***
task path: /builds/webarch/gitlab-ci/validation.yml:2
ok: [localhost] => {"changed": false, "msg": "The arg spec validation passed", "validate_args_context": {"argument_spec_name": "main", "name": "validation", "path": "/builds/webarch/gitlab-ci/roles/validation", "type": "role"}}
TASK [validation : Debug boolean1 variable] ************************************
task path: /builds/webarch/gitlab-ci/roles/validation/tasks/main.yml:2
ok: [localhost] => {
    "boolean1": false
}
TASK [validation : Debug boolean1 type] ****************************************
task path: /builds/webarch/gitlab-ci/roles/validation/tasks/main.yml:6
ok: [localhost] => {
    "msg": [
        "The boolean1 variable is a bool"
    ]
}
TASK [validation : Debug boolean2 variable] ************************************
task path: /builds/webarch/gitlab-ci/roles/validation/tasks/main.yml:11
ok: [localhost] => {
    "boolean2": "no"
}
TASK [validation : Debug boolean2 type] ****************************************
task path: /builds/webarch/gitlab-ci/roles/validation/tasks/main.yml:15
ok: [localhost] => {
    "msg": [
        "The boolean1 variable is a AnsibleUnicode"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
