### ISSUE TITLE
command line -i "root@localhost:22" not working expected 

### ISSUE THREAD

**Issue by Pilipupu** [ansible/ansible#78906]
### Summary

`ansible all -i "root@localhost," -m shell -a "echo 1"  --private-key /root/.ssh/id_rsa` works well.
`ansible all -i "localhost:22," -m shell -a "echo 1"  --private-key /root/.ssh/id_rsa` works well.

But `ansible all -i "root@localhost:22," -m shell -a "echo 1"  --private-key /root/.ssh/id_rsa` not working expected.

### Issue Type

Bug Report

### Component Name

Ansible

### Ansible Version

```console
$ ansible --version
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 20 2019, 20:27:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
DEFAULT_LOAD_CALLBACK_PLUGINS(env: ANSIBLE_LOAD_CALLBACK_PLUGINS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = json
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

### OS / Environment

CentOS Linux release 7.6.1810 (Core)

### Steps to Reproduce

```yaml (paste below)
ansible all -i "root@localhost:22," -m shell -a "echo 1"  --private-key /root/.ssh/id_rsa
```

### Expected Results

```yaml
{
    "custom_stats": {},
    "global_custom_stats": {},
    "plays": [
        {
            "play": {
                "duration": {
                    "end": "2022-09-28T07:34:42.765247Z",
                    "start": "2022-09-28T07:34:41.503223Z"
                },
                "id": "001c4286-25e0-7a53-ae2c-000000000007",
                "name": "Ansible Ad-Hoc"
            },
            "tasks": [
                {
                    "hosts": {
                        "root@localhost": {
                            "_ansible_no_log": false,
                            "action": "command",
                            "ansible_facts": {
                                "discovered_interpreter_python": "/usr/bin/python"
                            },
                            "changed": true,
                            "cmd": "echo 1",
                            "delta": "0:00:00.002633",
                            "end": "2022-09-28 15:34:42.654454",
                            "invocation": {
                                "module_args": {
                                    "_raw_params": "echo 1",
                                    "_uses_shell": true,
                                    "argv": null,
                                    "chdir": null,
                                    "creates": null,
                                    "executable": null,
                                    "removes": null,
                                    "stdin": null,
                                    "stdin_add_newline": true,
                                    "strip_empty_ends": true,
                                    "warn": true
                                }
                            },
                            "rc": 0,
                            "start": "2022-09-28 15:34:42.651821",
                            "stderr": "",
                            "stderr_lines": [],
                            "stdout": "1",
                            "stdout_lines": [
                                "1"
                            ]
                        }
                    },
                    "task": {
                        "duration": {
                            "end": "2022-09-28T07:34:42.765247Z",
                            "start": "2022-09-28T07:34:41.531304Z"
                        },
                        "id": "001c4286-25e0-7a53-ae2c-000000000009",
                        "name": "shell"
                    }
                }
            ]
        }
    ],
    "stats": {
        "root@localhost": {
            "changed": 1,
            "failures": 0,
            "ignored": 0,
            "ok": 1,
            "rescued": 0,
            "skipped": 0,
            "unreachable": 0
        }
    }
}
```

### Actual Results

```console
{
    "custom_stats": {},
    "global_custom_stats": {},
    "plays": [
        {
            "play": {
                "duration": {
                    "end": "2022-09-28T07:35:44.302473Z",
                    "start": "2022-09-28T07:35:44.247496Z"
                },
                "id": "001c4286-25e0-2f81-c9c1-000000000007",
                "name": "Ansible Ad-Hoc"
            },
            "tasks": [
                {
                    "hosts": {
                        "root@localhost:22": {
                            "action": "command",
                            "changed": false,
                            "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname localhost:22: Name or service not known",
                            "unreachable": true
                        }
                    },
                    "task": {
                        "duration": {
                            "end": "2022-09-28T07:35:44.302473Z",
                            "start": "2022-09-28T07:35:44.272575Z"
                        },
                        "id": "001c4286-25e0-2f81-c9c1-000000000009",
                        "name": "shell"
                    }
                }
            ]
        }
    ],
    "stats": {
        "root@localhost:22": {
            "changed": 0,
            "failures": 0,
            "ignored": 0,
            "ok": 0,
            "rescued": 0,
            "skipped": 0,
            "unreachable": 1
        }
    }
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
