### ISSUE TITLE
Ignore_unreachable still lists hosts as unreachable in play recap

### ISSUE THREAD

**Issue by vellakingg** [ansible/ansible#78986]
### Summary

When using ignore_unreachable: true, subsequent tasks are correctly run and the host is recovered. However, the recap displays the host in red and unreachable=1. 

Would the correct output not be unreachable=0 with ignored=x+1, as I believe ignore_errors works? 

Also, adding meta: clear_host_errors does not affect the output ansible recap.

### Issue Type

Bug Report

### Component Name

Ignore_unreachable

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.0]
config file = /runner/project/ansible.cfg
configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.9/site-packages/ansible
ansible collection location = /runner/project/collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
jinja version = 3.0.3
libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

docker.io/library/ee-supported-rhel8:1.0.0-120

### Steps to Reproduce

```yaml (paste below)
---
- name: Windows Baseline Playbook
  hosts: windows:!primary_domain_controller
  gather_facts: False
  tasks:
    - win_ping:
      ignore_unreachable: true
      register: ping

    - name: Join VM to domain
      win_domain_membership:
        dns_domain_name: "{{ domain }}"
        hostname: "{{ inventory_hostname }}"
        domain_admin_user: "{{ domain_admin.uname }}@{{ domain }}"
        domain_admin_password: "{{ domain_admin.pword }}"
        state: domain
      register: domain_state
      vars:
        ansible_user: "{{ local_admin.uname }}"
        ansible_password: "{{ local_admin.pword }}"
      when: 'ping.msg is defined and "STATUS_LOGON_FAILURE" in ping.msg'

    - ansible.windows.win_reboot:
      timeout: 30
      ignore_errors: true
      vars:
        ansible_user: "{{ local_admin.uname }}"
        ansible_password: "{{ local_admin.pword }}"
      when: 'domain_state.reboot_required and ping.msg is defined and "STATUS_LOGON_FAILURE" in ping.msg'

    - name: Wait for reboot
      wait_for_connection:
        timeout: 600
...
```

### Expected Results
```
PLAY RECAP *********************************************************************
windows_host             : ok=4    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=2
^ Green output for host
```

### Actual Results

```console
ansible-runner run -p domain_join.yml . -v
Using /runner/project/ansible.cfg as config file
Vault password:

PLAY [Windows Baseline Playbook] ***********************************************

TASK [win_ping] ****************************************************************
Monday 03 October 2022  00:52:09 +0000 (0:00:00.045)       0:00:00.045 ********
fatal: [windows_host]: UNREACHABLE! => {"changed": false, "msg": "credssp: Received error status from the server: (3221225581) STATUS_LOGON_FAILURE 0xc000006d", "skip_reason": "Host windows_host is unreachable", "unreachable": true}

TASK [Join VM to domain] *******************************************************
Monday 03 October 2022  00:52:09 +0000 (0:00:00.222)       0:00:00.268 ********
changed: [windows_host] => {"changed": true, "reboot_required": true}

TASK [ansible.windows.win_reboot] **********************************************
Monday 03 October 2022  00:52:16 +0000 (0:00:06.774)       0:00:07.042 ********
fatal: [windows_host]: FAILED! => {"changed": false, "msg": "The ansible.windows.win_reboot action failed to execute in the expected time frame (30) and was terminated"}
...ignoring

TASK [Wait for reboot] *********************************************************
Monday 03 October 2022  00:52:46 +0000 (0:00:30.077)       0:00:37.119 ********
ok: [windows_host] => {"changed": false, "elapsed": 3}

PLAY RECAP *********************************************************************
windows_host             : ok=3    changed=1    unreachable=1    failed=0    skipped=1    rescued=0    ignored=1
^ Red output for host
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
