### ISSUE TITLE
Add "changes" (similar to "creates") to ansible.builtin.shell

### ISSUE THREAD

**Issue by giorgiga** [ansible/ansible#78993]
### Summary

Most of the times I end up using `ansible.builtin.shell`, it is to invoke some utility that modifies some configuration file or to execute some script that ultimately ends up modifying some configuration file.

This is relatively straightforward, but unless one renounces change reporting with `changed_when: false` checking if the shell command/script actually modified the target file requires either a separate task or some hacks involving `rc` or `stdout`.

In the spirit of the already-existing `creates` and `removes` (which are essentially specialized versions of `when`), I would like `ansible.builtin.shell`, and possibly also `command` and `script`, to support a `changes` attribute, which would essentially be a specialized version of `changed_when` which compares a target file contents before and after running the `shell` task and reports `changed` accordingly.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.shell, ansible.builtin.command, ansible.builtin.script

### Additional Information

Suppose we want to use `git config` to set the user name and email in some user's git configuration. Currently that could look like:

```yaml
- name: check if ~/.config/git/config needs editing
  ansible.builtin.shell:
     cmd: |
        test $(git config --global user.name) != "{{ user.full_name }}" \
        || test $(git config --global user.email) != "{{ user.email }}"
  become_user: "{{ user.name }}"
  register: git_config_needs_editing_command
  changed_when: false

- name: edit ~/.config/git/config if needed
  ansible.builtin.shell:
     cmd: |
        git config --global user.name "{{ user.full_name }}"
        git config --global user.email "{{ user.email }}"
  become_user: "{{ user.name }}"
  when: git_config_needs_editing_command.rc == 0
```

*(didn't check or test the commands - please ignore any blunders)*

With `changed` it would look like:

```yaml (paste below)
- name: set git username
  ansible.builtin.shell:
     cmd: |
        git config --global user.name "{{ user.full_name }}"
        git config --global user.email "{{ user.email }}"
     changes: "{{ user.home }}/.config/git/config" 
  become_user: "{{ user.name }}"
```

Note that this version is not entirely the same as the first one above, in that here the `git config` commands to edit the configuration are always run (which is not an issue since they are idempotent) and above the `when` prevents them to run (also, reporting would be different of course).

To be fair, this version with `changes` would be equivalent to using two `ansible.builtin.stat`, one before and one after the `ansible.builtin.shell` and comparing checksums in `changed_when`, but I felt that using that as an example would unfairly over-represent the benefits of  `changes` and the above is, I think, more similar to what people actually use. 

>PS:
>I picked `git config` above because most people will be familiar with it, despite `~/.config/git/config` lending fairly well to be templated. Please note there are cases, like with KDE configuration files and `kwriteconfig5`, where using templates isn't really an option.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/shell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/shell.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
and 'what changes'  in "{{ user.home }}/.config/git/config" ?

**Comment by giorgiga** [comment]
`git config --global user.name 'John Doe'` changes `~/.config/git/config` so that it contains

    [user]
	name = John Doe

The idea is that `ansible.builtin.shell` would compare `~/.config/git/config` before and after running the task and report `changed` accordingly.

The comparison could go along the lines of what other ansible tasks, like `ansible.builtin.copy`, do (IDK what they do - I guess they compare checksums?).

**Comment by giorgiga** [comment]
If I get your concerns, the point is that we can't trust the user on the indempotency of the shell command/script?

For example, one could write:

```yaml
- ansible.builtin.shell:
     cmd: sed -i 's:server:server:' /etc/hostname
     changes: /etc/hostname
```
and expect it to not turn "server2" in "server22" the second time ansible is run?


IMO the semantic correctness of `ansible.builtin.shell` is *already* up the user: nothing currently prevents writing tasks like

```yaml
- name: remove some file
  ansible.builtin.shell:
     cmd: rm /etc/some-file
     removes: /etc/some-other-file
````

so I don't think it's a big deal if the user declares that a shell task `changes` a file when it also has side effects.

If you think users will assume `changes` prevents the shell task to run non-idempotent commands, maybe we could pick a different name? (IDK which one... maybe  `idempotently_changes`?)

----

Since  commands that edit config files usually can also read a configuration value, one can generally manage with less boilerplate than two `stat` actions before and after the change.

An equivalent to the previous example

```yaml
- name: set git username
  ansible.builtin.shell:
     cmd: git config --global user.name {{ user.git_user_name }}
     changes: "{{ user.home }}/.config/git/config" 
  become_user: "{{ user.name }}"
```
with  existing functionalities could be as simple as:

```yaml
- name: see if username should be set
  ansible.builtin.shell:
    cmd: git config --global user.name
  become_user: "{{ user.name }}"
  register: current_git_user_name_command

- name: set git username
  ansible.builtin.shell:
    cmd: git config --global user.name "{{ user.git_user_name }}"
  become_user: "{{ user.name }}"
  when: current_git_user_name_command.stdout != user.git_user_name
```
which, verbosity aside, I think is much less clear than the example with `changes`.

An implementation with two `stat` would of course be even uglier, but it would have the advantage of remaining the same if one edits more than one setting (eg. if one runs `git config --global user.name 'John Doe' && git config --global user.email 'jdoe@example.com'`), but the hypothetical `changes` would also have the same advantage.

---

Finally, while it is true that `changes` would be just a shortcut for functionality that can be implemented with `stat`, the same is true for `creates` and `removes`.

**Comment by giorgiga** [comment]
@bcoca  Would you recommend I close this and post a proposal instead?

**Comment by giorgiga** [comment]
I'm not sure I follow... what existing decisional mechanism would this `changes` thing misuse for reporting?

Let me clarify that the whole idea is merely about adding "syntactic sugar" for the use case I described, in much the same way as `creates` and `removes` are sugar for `stat` and `when`...

I'm not thinking about changing any existing mechanism, just about adding new functionality.

**Comment by bcoca** [comment]
creates/removes influence running the shell command or not, your changes creates a facility that changes the reporting AFTER the command is run so they are not the same

**Comment by giorgiga** [comment]
Yes, this `changes` would be different from `creates`/`removes`: it would in fact be equivalent to `changed_when`, which is evaluated after the action runs.

eg. this is the first example from [Defining "changed" in the ansible doc](https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#defining-changed):

```yml
  - name: Report 'changed' when the return code is not equal to 2
    ansible.builtin.shell: /usr/bin/billybass --mode="take me to the river"
    register: bass_result
    changed_when: "bass_result.rc != 2"
```

My *similar to "creates"* note in the title was because, like `creates`, `changes` would basically be syntactic sugar, not because they should be variations of the same mechanism - apologies for having caused a misunderstanding.
