### ISSUE TITLE
ansible_fqdn has disappeared from ansible_facts

### ISSUE THREAD

**Issue by simonwibberley** [ansible/ansible#79020]
### Summary

Having come back to a playbook I was working on a month or two ago `{{ansible_facts['ansible_fqdn']}}` was working just fine and now seems to have disappeared:

`'dict object' has no attribute 'ansible_fqdn'`

ansible hasn't been updated in the meantime (ansible [core 2.11.6]) and facts are being gathered. 

Any clues as to what's happening here?  

### Issue Type

Bug Report

### Component Name

!component 

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.0.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_CONNECTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/root/git/ansible-lxc-ssh/lxc_ssh.py']
```

### OS / Environment

Ubuntu 20.04.3 LTS

### Steps to Reproduce

```yaml (paste below)
- name: set nodename
  lineinfile:
    dest: "/home/ubuntu/config.json"
    regexp: "\"webappHost\":"
    line: "\"webappHost\": \"{{ansible_facts['ansible_fqdn']}}\""
    state: present
```

### Expected Results

The host name should be inserted to the file.

### Actual Results

```console
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_fqdn'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
