### ISSUE TITLE
Virtual Server fortiadc configuration module reports change detected even tho there was no changes

### ISSUE THREAD

**Issue by iden83** [ansible/ansible#79059]
### Summary

Condition in virtual server python part of module (lines 264-267) is wrong and should be removed:

https://github.com/fortinet-ansible-dev/ansible-galaxy-fortiadc-collection/blob/galaxy/1.0.1/plugins/modules/fadcos_virtual_server.py#L264

There are conditions evaluated:

    if module.params['traffic_group'] and module.params['traffic_group'] != data['traffic-group']:
        data['traffic-group'] = module.params['traffic_group']
        res = True
    if module.params['traffic_group'] and module.params['traffic_group'] != data['traffic-log']:
        data['traffic-log'] = module.params['traffic_group']
        res = True
    if module.params['traffic_log'] and module.params['traffic_log'] != data['traffic-log']:
        data['traffic-log'] = module.params['traffic_log']
        res = True

1st condition "traffic-group" evaluation is proper.
2nd condition evaluation is wrong - looks like combination between 1st and 3rd hence it's redundant and shall be removed.
3rd condition "traffic-log" evaluation is proper.

In our project to properly interact with FortiADC device updates we are manually remove those lines from the module.

### Issue Type

Bug Report

### Component Name

ansible-galaxy-fortiadc-collection:1.0.1

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/collections/ansible_collections/fortinet/fortiadc']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/root/.ansible/collections/ansible_collections/fortinet/fortiadc']
```

### OS / Environment

Ubuntu 22.04 based docker image

### Steps to Reproduce

```yaml (paste below)

- name: Edit Dummy Virtual Server
  fadcos_virtual_server:
    action: edit
    name: Dummy_Public_8080
    status: enable
    iptype: ipv4
    ip: 172.31.108.112
    interface: Vlan1442
    pool: SamplePool_SRV_32223
    port: 8080
    method: LB_METHOD_ROUND_ROBIN
    packet_fwd_method: FullNAT
    source_pool_list: SAMPLE_NAT_POOL
    profile: LB_PROF_TCP
    vstype: l4-load-balance
    vdom: root
    fortiview: enable
```

### Expected Results

It's expected by several times when running edit action with same data that ansible will detect that as no change needed.

### Actual Results

Due to explained bug each time applying same edit action - ansible module detects always there is something to change hence it's reported as changed all the time even tho there was not change.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
