### ISSUE TITLE
enabling jinja2 native leads to quotes nested in quotes being stripped

### ISSUE THREAD

**Issue by Yannik** [ansible/ansible#79083]
### Summary

Enabling jinja2 native leads to quotes nested in other quotes (single quotes in double quotes or vice versa) being stripped. This stripping is additionally done in a seemingly inconsistent and unpredictable way.

### Issue Type

Bug Report

### Component Name

jinja2

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.3]
  config file = /home/yannik/projects/closed/ansible.cfg
  configured module search path = ['/home/yannik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/yannik/projects/closed/vendor_collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  jinja version = 3.1.2
  libyaml = True

```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/home/yannik/projects/xxx/ansible.cfg) = True
```

### OS / Environment

fedora 36

### Steps to Reproduce

```yaml (paste below)
- hosts: all
  tasks:
    - copy:
        content: |
          {{ myvar }}
        dest: out1
      vars:
        myvar: '"hello {{ ansible_host }}"'
    - copy:
        content: |
          {{ myvar }}
        dest: out2
      vars:
        myvar: '"hello"'
    - copy:
        content: |
          {{ myvar }}
        dest: out3
      vars:
        myvar: ' "hello"'
    - copy:
        content: |
         a = {{ myvar }}
        dest: out4
      vars:
        myvar: '"hello {{ ansible_host }}"'
    - copy:
        content: |
         a = {{ myvar }}
        dest: out5
      vars:
        myvar: '"hello"'
    - copy:
        content: |
         a = {{ myvar }}
        dest: out6
      vars:
        myvar: ' "hello"'

```

```
ansible-playbook -i localhost, test.yml
cat ~/out*
```

### Expected Results

This is the result with jinja2 native disabled, and which I would generally expect:

```
"hello localhost"
"hello"
 "hello"
a = "hello localhost"
a = "hello"
a =  "hello"
```

### Actual Results

```console
hello localhost
hello
 "hello"
a = hello localhost
a = "hello"
a =  "hello"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* `lib/ansible/template`

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
Ultimately, the explanation for this is related to how jinja2 native works.  Unless the full result of a templating operation is tagged in a way that marks it as text, the value is turned into a "native" Python data type by using `ast.literal_eval`

Consider this bit of python code:

```pycon
>>> print(ast.literal_eval('"hello"'))
hello
>>> print(ast.literal_eval("""'"hello"'"""))
"hello"
```

As such, you need to increase your quoting to survive the `ast.literal_eval`, such as:

```yaml
    - copy:
        content: |
          {{ myvar }}
        dest: out2
      vars:
        myvar: '''"hello"'''
```

This however can get really complicated, as each individual templating operation must account for the correct number of quotes.  Your first example showcases this:

```yaml
    - copy:
        content: |
          {{ myvar }}
        dest: out1
      vars:
        myvar: '"hello {{ ansible_host }}"'
```

If you know that `myvar` will result in 2 templating operations, you can resolve it like:

```yaml
        myvar: '"''\"hello {{ inventory_hostname }}\"''"'
```

However if you cannot make that assumption, this becomes really complicated.

Now I mention earlier about "Unless the full result of a templating operation is tagged in a way that marks it as text".

This can be done via several filters documented at https://docs.ansible.com/ansible-core/2.13/reference_appendices/config.html#string-type-filters

The `|string` filter is a good example, however this is not exactly straight forward, as it applies to the full result of a templating operation, so everything you do must be placed inside of `{{ }}` such as:

```yaml
    - copy:
        content: |
          {{ myvar }}
        dest: out1
      vars:
        myvar: '{{ (''"hello '' ~ ansible_host ~ ''"'')|string }}'
```

Dealing with those quotes is still kind of a pain, so we've tossed around the idea of creating a new `quote_str` filter, that just wraps a value in quotes, and tags the value so that it isn't touched by `ast.literal_eval` just like the list noted above.

In any case, the behavior you are seeing is expected.  However, there might be some things we can do to make it a little easier, or at least maybe document this in the FAQ.
