### ISSUE TITLE
Add options to manage pip's package cache

### ISSUE THREAD

**Issue by jsabater** [ansible/ansible#79096]
### Summary

Dear Sir or Madam,

I'd like to kindly request adding options to manage pip's cache. Especifically:

1. An option to enable/disable cache when installing packages, i.e. the equivalent of using `--no-cache-dir` (available since pip 6.0).
2. An option to purge existing cache, i.e. the equivalent of running `pip cache purge` (available since pip 20.1).

### Issue Type

Feature Idea

### Component Name

pip

### Additional Information

```yaml
- name: builtin | pip | install project requirements
  ansible.builtin.pip:
    requirements: /opt/django/src/requirements.txt
    virtualenv: /opt/django/venv
    virtualenv_command: /usr/bin/python3 -m venv
    # This is what I am currently using
    # extra_args: "--no-cache-dir"
    # This is a proposal
    cache: no
  become: true
  become_user: django
  become_method: su
  notify:
    - pip cache purge
```

When using handlers, such as above, the handler could be implemented as follows:

```yaml
handlers:
  - name: pip cache purge
    ansible.builtin.pip:
        cache_purge: yes
    become: true
    become_user: django
    become_method: su
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
