### ISSUE TITLE
ability to rename extracted folder in ansible.builtin.unarchive

### ISSUE THREAD

**Issue by baditaflorin** [ansible/ansible#79148]
### Summary

Trying to emulate this command in ansible and was thinking that it would be useful if you would have the ability to rename the extracted folder directly from the unarchive module.

```
Download the source using curl, untar it, and rename the extracted folder to prometheus-files.

curl -LO url -LO https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-amd64.tar.gz
tar -xvf prometheus-2.22.0.linux-amd64.tar.gz
mv prometheus-2.22.0.linux-amd64 prometheus-files

```

### Issue Type

Feature Idea

### Component Name

ansible.builtin.unarchive

### Additional Information

This is how I currently solve this

```yaml (paste below)
---
- gather_facts: false
  hosts: promethese
  become: true
  tasks:
    - name: Create folder for prometheus in usr/local/bin/
      file:
        path: /usr/local/bin/prometheus-files
        state: directory
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-amd64.tar.gz
        dest: /usr/local/bin/prometheus-files
        remote_src: yes
        list_files: yes
        extra_opts: [--strip-components=1]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
