### ISSUE TITLE
Async import_tasks loop

### ISSUE THREAD

**Issue by legitYosal** [ansible/ansible#79151]
### Summary

In some occasions in one role, you may have a group of tasks that are applying some specific work, for example, we have a role which installs Nginx, naturally on multiple hosts, installing process is asyncally done, in each installation we have a group of virtual hosts of Nginx, maybe tens of them, after installing Nginx and configuring virtual hosts, for every virtual host, we will configure self signed certificate on a specific client group by calling a task group named `tls.yml` by using `import_tasks` module:
```
Role Nginx:
  for host in host group:
    install Nginx
    configure Nginx
    for every vhost in vhosts:
       for every client in client group:
         configure self singed certificate
```
Ansible will execute  `tls.yml` sequentially, for vhost1, vhost2, vhost3, ... although it is not necessary and they can execute asyncrounosly.  
I wonder is there any solution to achieve this with any other method in ansible??? Why by default this is not the normal behavior??? when you are writing some piece of ansible like this:
```ansible
- name: Loop on task file
  import_tasks: tls.yml
  loop: "{{items}}"
```
How executing tasks on different items is related to each other that leads to desining Ansible in a such way that this executes sequentially???

And finally I guess this must be the default behavior and should be developed in feature...

[Also this is the issue I put on stackoverflow](https://stackoverflow.com/questions/74080837/ansible-concurrently-loop-with-import-taskspoll-0-not-working?noredirect=1#comment130825995_74080837)

### Issue Type

Feature Idea

### Component Name

import_tasks

### Additional Information

```yaml (paste below)
- name: Run a long group task 
  ansible.builtin.include_tasks: tasks.yaml
  loop: "{{ items_list }}"
  async: 180
  poll: 0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/import_tasks.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_tasks.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
This looks like a duplicate of https://github.com/ansible/ansible/issues/28997. The right syntax for `include_tasks` would be to use the `apply` option:
```yaml
- name: Run a long group task
  ansible.builtin.include_tasks:
    file: tasks.yaml
    apply:
      async: 180
      poll: 0
  loop: "{{ items_list }}"
```
but that will only work if #28997 is implemented. There are actions that don't support async (like `async_status`), so you'd need to set `async: 0` on any tasks that don't support it.

**Comment by usefss** [comment]
Yes it is very similar, also very strange that people opened up about supporting async on block rather than import_tasks, because it is not supported to loop on block...  
I think using `apply` will execute each task in `task.yaml` asynchronously, that is not what I wanted, the group of tasks in file `task.yaml` must execute sequently...  
And I did not understand what do you mean by `if https://github.com/ansible/ansible/issues/28997 is implemented` and what happens when setting async to zero?

**Comment by s-hertel** [comment]
I totally misunderstood what you were doing, not a duplicate of #28997 in that case. Maybe more similar to https://github.com/ansible/ansible/issues/22716.

Just to clarify my original comment - `import_tasks` creates an implicit block, as does `include_tasks`. Looping over non-implicit blocks is not possible (you can find some context for that here https://github.com/ansible/ansible/issues/13262). Not all tasks support async, so if that's case for any tasks inheriting the keyword you'd need to turn async back off by setting it to 0. 

But after rereading your stackoverflow I think I understand a little better, this bit in particular

> The solution must loop through items_list variable, and apply tasks.yaml for each item async to other tasks, meaning it will not execute them in order of item1, item2, item3 ... but all together.

`include_tasks`/`import_tasks` do not have a result that can be registered and without that firing and forgetting doesn't make sense - the playbook could end without those tasks ever completing.

If you're not targeting a bunch of real hosts (which would complicate things) you could accomplish something similar by creating fake hosts with the info you need per loop item, and then target the fake hosts in a subsequent play with the `free` strategy. This example takes about 20 seconds instead of 60 (which is how long it would take with a normal loop targeting one host):

```yaml
# playbook.yml
- hosts: localhost
  gather_facts: no
  vars:
    loop_items:
      - foo: bar
      - foo: baz
      - foo: qux
  tasks:
  - add_host:
      name: "fake-{{ index }}"
      foo: "{{ item.foo }}"
    loop: "{{ loop_items }}"
    loop_control:
      index_var: index

- hosts: all
  gather_facts: no
  strategy: free
  tasks:
    - name: long running tasks
      include_tasks: tasks.yml
```

```yaml
# tasks.yml
- debug: msg="{{ foo }}"

- command: sleep 20
  delegate_to: localhost
```
