### ISSUE TITLE
Running Ansible ansible.builtin.file lookup as a non-root user is not working with the become task directive.

### ISSUE THREAD

**Issue by Xoren-Games** [ansible/ansible#79165]
### Summary

Running Ansible `ansible.builtin.file lookup` as a non-root user is not working with the `become` task level directive. The error message isn't clear also.

Error when using the *with_file* format:
`fatal: [localhost]: FAILED! => {"msg": "could not locate file in lookup: simple_test_file.txt"}`

Error when using the inline format:
`fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ansible.builtin.file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: simple_test_file.txt. could not locate file in lookup: simple_test_file.txt"}`

### Issue Type

Bug Report

### Component Name

ansible.builtin.file lookup

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.4]
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.10.7 (main, Oct  5 2022, 14:44:35) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = ['/home/ansible/source/ansible/ansible/inventories/development/hosts.yml'>
DEFAULT_INVENTORY_PLUGIN_PATH(/home/ansible/.ansible.cfg) = ['/home/ansible/.ansible/plugins/inventory']
DEFAULT_VAULT_IDENTITY_LIST(/home/ansible/.ansible.cfg) = ['test_vault_id@/ansible-keyring-client']
INVENTORY_ENABLED(/home/ansible/.ansible.cfg) = ['auto', 'yaml']
```

### OS / Environment

```bash
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Steps to Reproduce

```yaml (paste below)
---
- name: Testing playbook.
  hosts: localhost
  connection: local
  tasks:
    - name: Get Ansible version information.
      ansible.builtin.command:
        cmd: ansible --version
      register: ansible_version

    - name: Show Ansible version for reference.
      ansible.builtin.debug:
        var: ansible_version

    - name: Create file simple_test_file.txt
      ansible.builtin.shell: echo 'This is a test.' > simple_test_file.txt
      args:
        creates: simple_test_file.txt

    - name: Test simple_test_file.txt lookup (successful)
      ansible.builtin.debug:
        var: item
      with_file:
        - simple_test_file.txt

    - name: Set simple_test_file.txt permissions to root:root mode 0640
      ansible.builtin.file:
        path: simple_test_file.txt
        owner: root
        group: root
        mode: '0640'
      become: true

    - name: Test simple_test_file.txt lookup with_file (fails)
      ansible.builtin.debug:
        var: item
      with_file:
        - simple_test_file.txt
      ignore_errors: true
      become: true

    - name: Test simple_test_file.txt file lookup inline format (fails)
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', 'simple_test_file.txt') }}"
      ignore_errors: true
      become: true

    - name: Set simple_test_file.txt permissions to root:root mode 0644
      ansible.builtin.file:
        path: simple_test_file.txt
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Test simple_test_file.txt lookup with_file (successful)
      ansible.builtin.debug:
        var: item
      with_file:
        - simple_test_file.txt

    - name: Test simple_test_file.txt file lookup inline format (successful)
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', 'simple_test_file.txt') }}"
```

### Expected Results

Minimally, the error or Ansible documentation should indicate that the task level become directive isn't supported for file lookups.

Ideally, adding **become** task level directive support to **ansible.builtin.file lookup** would be a nice feature to have.  This would prevent having to copy files or alter file permissions to make file lookups work, specifically for files that normally require root or sudo privilege to read.  For large playbooks, this would be more efficient and reduce playbook length.

### Actual Results

```console
PLAY [Testing playbook.] ************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
ok: [localhost]

TASK [Get Ansible version information.] *********************************************************************************************************************************************************
changed: [localhost]

TASK [Show Ansible version for reference.] ******************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_version": {
        "full": "2.13.4",
        "major": 2,
        "minor": 13,
        "revision": 4,
        "string": "2.13.4"
    }
}

TASK [Create file simple_test_file.txt] *********************************************************************************************************************************************************
ok: [localhost]

TASK [Test simple_test_file.txt lookup (successful)] ********************************************************************************************************************************************
ok: [localhost] => (item=This is a test.) => {
    "ansible_loop_var": "item",
    "item": "This is a test."
}

TASK [Set simple_test_file.txt permissions to root:root mode 0640] ******************************************************************************************************************************
changed: [localhost]

TASK [Test simple_test_file.txt lookup with_file (fails)] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "could not locate file in lookup: simple_test_file.txt"}
...ignoring

TASK [Test simple_test_file.txt file lookup inline format (fails)] ******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'ansible.builtin.file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: simple_test_file.txt. could not locate file in lookup: simple_test_file.txt"}
...ignoring

TASK [Set simple_test_file.txt permissions to root:root mode 0644] ******************************************************************************************************************************
changed: [localhost]

TASK [Test simple_test_file.txt lookup with_file (successful)] **********************************************************************************************************************************
ok: [localhost] => (item=This is a test.) => {
    "ansible_loop_var": "item",
    "item": "This is a test."
}

TASK [Test simple_test_file.txt file lookup inline format (successful)] *************************************************************************************************************************
ok: [localhost] => {
    "msg": "This is a test."
}

PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=2
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
