### ISSUE TITLE
win_acl and win_acl_inheritance fail when using become=yes

### ISSUE THREAD

**Issue by kiwimato** [ansible/ansible#79184]
### Summary

`win_acl` and `win_acl_inheritance` both fail when using become=yes on Windows.

### Issue Type

Bug Report

### Component Name

win_acl

### Ansible Version

```console
$ ansible --version
  I'm using Ansible Tower, and not sure I have access to view the version, or I don't know where to find it easily. However I do see these in the logs:


  ansible-playbook [core 2.12.5.post0]
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

I assume Ansible tower runs on RHEL, and the target system is Windows 2019 Datacenter

### Steps to Reproduce

```yaml
- name: Remove Authenticated users group access to the share
  ansible.windows.win_acl:
    path: "{{ fsx_share }}"
    user: "NT AUTHORITY\\Authenticated Users"
    rights: "{{ item }}"
    type: allow
    state: absent
    propagation: InheritOnly
  with_items:
    - Modify
    - Read
    - ReadAndExecute
    - Write
    - FullControl
    - Delete
  run_once: true
  ignore_errors: yes
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ fsx_shareadmin_username }}"
    ansible_become_password: "{{ fsx_shareadmin_password }}"
```

### Expected Results

However, it seems that win_acl only truly fails if I try to remove default permissions, as in when I check the actual Windows machine the permissions are still there.
```
- name: Remove Authenticated users group access to the share
  ansible.windows.win_acl:
    path: "{{ fsx_share }}"
    user: "NT AUTHORITY\\Authenticated Users"
    rights: "{{ item }}"
    type: allow
    state: absent
    propagation: InheritOnly
  with_items:
    - Modify
    - Read
    - ReadAndExecute
    - Write
    - FullControl
    - Delete
  run_once: true
  ignore_errors: yes
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ fsx_shareadmin_username }}"
    ansible_become_password: "{{ fsx_shareadmin_password }}"
```

This code seems to fail successfully, meaning it does disable the inheritance and add the necessary users, but Ansible says it failed with the error in "Actual Result"
```
- name: Disable inherited ACE's for "{{ fsx_share }}"
  win_acl_inheritance:
    path: "{{ fsx_share }}"
    state: absent
    reorganize: yes
  run_once: true
  ignore_errors: yes  # task fails successfully with: "Preparing modules for first use", even though the permissions are set correctly
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ fsx_shareadmin_username }}"
    ansible_become_password: "{{ fsx_shareadmin_password }}"
- name: Add "{{ fsx_rw_group }}" group to read write
  ansible.windows.win_acl:
    path: "{{ fsx_share }}"
    user: "{{ fsx_rw_group }}"
    rights: Read,ReadAndExecute,Write,Modify,Delete
    type: allow
    state: present
    propagation: InheritOnly
  run_once: true
  ignore_errors: yes   # task fails successfully with: "Preparing modules for first use", even though the permissions are set correctly
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ fsx_shareadmin_username }}"
    ansible_become_password: "{{ fsx_shareadmin_password }}"
```

### Actual Results

```console
{
  "module_stdout": "{\"changed\":false}#< CLIXML<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">2</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>",
  "module_stderr": "",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false,
  "item": "ReadAndExecute",
  "ansible_loop_var": "item",
  "_ansible_item_label": "ReadAndExecute"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
