### ISSUE TITLE
built.in.apt module tries to use yum for Ubuntu 22.04

### ISSUE THREAD

**Issue by cybernet** [ansible/ansible#79204]
### Summary

`environment`

Rocky Linux 8.5

`ansible-config dump --only-changed -t all`

```sh
CACHE_PLUGIN(/home/play/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/play/ansible/ansible.cfg) = ~/ansible/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/play/ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/play/ansible/ansible.cfg) = 4
DEFAULT_HOST_LIST(/home/play/ansible/ansible.cfg) = ['/home/play/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/home/play/ansible/ansible.cfg) = ['/home/play/ansible/roles']
HOST_KEY_CHECKING(/home/play/ansible/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/home/play/ansible/ansible.cfg) = True

```

`version`

```sh
ansible [core 2.12.2]
  config file = /home/play/ansible/ansible.cfg
  configured module search path = ['/home/play/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/play/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, May 10 2022, 23:46:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 2.10.3
  libyaml = True
```

inventory `webd.yml`

```yml
---
dev:
  hosts:
    dev.drivertech.uk:
    deb.drivertech.uk:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/play
```

`dev` is Rocky Linux 8 while `deb` is Ubuntu 22.04

webd.yml

```yml
---
- hosts: dev
  roles:
    - webd
```

`roles/webd/tasks/main.yml`

```yml
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat", "Rocky"
```

`roles/webd/tasks/redhat.yml`

```yml
---
- name: is ViM
  yum:
    name: "vim"
    state: latest
- name: check if date works
  shell:
    "date"
  register: datecmd
  tags: datecmd
- name: ensure EPEL is at the latest version
  ansible.builtin.dnf:
    name: epel-release
    state: latest
- name: Install the REMi key
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
    state: present
- name: Install the REMi repo
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
- name: Install the latest version of nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
- name: Install the latest version of ---tree
  ansible.builtin.dnf:
    name: tree
    state: latest
- name: Install the latest version of hTop
  ansible.builtin.dnf:
    name: htop
    state: latest
- name: Install the latest version of bTop
  ansible.builtin.dnf:
    name: btop
    state: latest
- name: Install a modularity appstream with defined stream
  ansible.builtin.dnf:
    name: '@php:remi-8.1'
    state: present
- name: Install php-fpm and required modules
  ansible.builtin.dnf:
    name: php-zip, php-gd, php-fpm, php-imap, php-intl, php-lz4, php-mbstring, php-mysqlnd, php-opcache, php-pdo, php-sodium, php-xml, php-xz
    state: present
```

`roles/webd/tasks/debian.yml`

```yml
- name: Update all packages to their latest version
  ansible.builtin.apt:
    update_cache: yes
    only_upgrade: yes
- name: Install NginX
  ansible.builtin.apt:
    name: nginx
    state: latest
- name: Install hTop
  ansible.builtin.apt:
    name: htop
    state: latest
- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes
```

throws an error when I'm running the `webd` `playbook`

```sh
PLAY [dev] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [dev.drivertech.uk]
ok: [deb.drivertech.uk]

TASK [webd : include_tasks] ********************************************************************************************
skipping: [dev.drivertech.uk]
included: /home/play/ansible/roles/webd/tasks/debian.yml for deb.drivertech.uk

TASK [webd : Update all packages to their latest version] **************************************************************
changed: [deb.drivertech.uk]

TASK [webd : Install NginX] ********************************************************************************************
ok: [deb.drivertech.uk]

TASK [webd : Install hTop] *********************************************************************************************
ok: [deb.drivertech.uk]

TASK [webd : Remove useless packages from the cache] *******************************************************************
ok: [deb.drivertech.uk]

TASK [webd : include_tasks] ********************************************************************************************
included: /home/play/ansible/roles/webd/tasks/redhat.yml for dev.drivertech.uk, deb.drivertech.uk

TASK [webd : is ViM] ***************************************************************************************************
fatal: [deb.drivertech.uk]: FAILED! => {"ansible_facts": {"pkg_mgr": "apt"}, "changed": false, "msg": ["Could not detect which major revision of yum is in use, which is required to determine module backend.", "You should manually specify use_backend to tell the module whether to use the yum (yum3) or dnf (yum4) backend})"]}
ok: [dev.drivertech.uk]

-----------
# stripped
-----------
```

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version

ansible [core 2.12.2]
  config file = /home/play/ansible/ansible.cfg
  configured module search path = ['/home/play/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/play/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, May 10 2022, 23:46:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-10)]
  jinja version = 2.10.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all


CACHE_PLUGIN(/home/play/ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/play/ansible/ansible.cfg) = ~/ansible/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/play/ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/play/ansible/ansible.cfg) = 4
DEFAULT_HOST_LIST(/home/play/ansible/ansible.cfg) = ['/home/play/ansible/inventory.yml']
DEFAULT_ROLES_PATH(/home/play/ansible/ansible.cfg) = ['/home/play/ansible/roles']
HOST_KEY_CHECKING(/home/play/ansible/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/home/play/ansible/ansible.cfg) = True
```

### OS / Environment

Rocky Linux 8.5

### Steps to Reproduce

read above

### Expected Results

use `apt` instead of `yum`

### Actual Results

```console
PLAY [dev] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [dev.drivertech.uk]
ok: [deb.drivertech.uk]

TASK [webd : include_tasks] ********************************************************************************************
skipping: [dev.drivertech.uk]
included: /home/play/ansible/roles/webd/tasks/debian.yml for deb.drivertech.uk

TASK [webd : Update all packages to their latest version] **************************************************************
changed: [deb.drivertech.uk]

TASK [webd : Install NginX] ********************************************************************************************
ok: [deb.drivertech.uk]

TASK [webd : Install hTop] *********************************************************************************************
ok: [deb.drivertech.uk]

TASK [webd : Remove useless packages from the cache] *******************************************************************
ok: [deb.drivertech.uk]

TASK [webd : include_tasks] ********************************************************************************************
included: /home/play/ansible/roles/webd/tasks/redhat.yml for dev.drivertech.uk, deb.drivertech.uk

TASK [webd : is ViM] ***************************************************************************************************
fatal: [deb.drivertech.uk]: FAILED! => {"ansible_facts": {"pkg_mgr": "apt"}, "changed": false, "msg": ["Could not detect which major revision of yum is in use, which is required to determine module backend.", "You should manually specify use_backend to tell the module whether to use the yum (yum3) or dnf (yum4) backend})"]}
ok: [dev.drivertech.uk]

-----------
# stripped
-----------
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
