### ISSUE TITLE
User ControlPersist

### ISSUE THREAD

**Issue by picomancer** [ansible/ansible#7922]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.7 (devel 9631309433) last updated 2014/06/22 17:53:14 (GMT -400)
```
##### Environment:

Linux Mint 16 Petra (based on Ubuntu 13.10 Saucy)
##### Summary:

Changes to the group membership of the remote user account you use to log in, do not take effect on subsequent runs.
##### Steps To Reproduce:

Put the following in `printgroups.yml`:

```

---
-   hosts: myhost
    tasks:
    - name: Print user 'r' groups
      shell: executable=/bin/bash groups
```

And the following in `updategroups.yml`:

```

---
-   hosts: myhost
    sudo: true
    tasks:
    - name: Create new group, 'silly'
      group: name=silly
    - name: Add 'r' user to group 'silly'
      user: name=r groups=silly append=yes
```

Create a user `r` on `myhost` with sudo privileges, then run `updategroups.yml` followed by `printgroups.yml`, with `-vvvv` to see the output of the `groups` command.  The `silly` group is not included, even though `r` is now a member of that group!

Note:  You have to run the second playbook quickly after the first, before the ControlPersist timeout period elapses.
##### Expected Results:

The `silly` group should be included in the result of the command.
##### Actual Results:

The `silly` group is not included in the result of the command.
##### Workaround:

Running the following command will delete the ControlPersist socket file on the local machine, forcing a new connection:

```
rm -f ~/.ansible/cp/ansible-ssh-*
```

This command fixes the immediate symptom, but I'm not sure if it results in wayward processes or other leaks.  Advice from a ControlPersist expert would likely be informative as to exactly what the consequences of this workaround are.
##### Detailed discussion:

Due to the way Linux handles processes and group membership, this behavior is probably unfixable.

However, it seems like the workaround I found could be incorporated into ansible itself, and made much cleaner in terms of terminating the old connection and any associated processes, sockets, etc.  An ansible module which forces a clean shutdown and restart of the SSH connection would do the trick.  Maybe each connection plugin should provide a mechanism to restart the channel, and the module activates that mechanism?

Then any playbook which changes the group membership of the logged-in user should call the connection_restart module after each group membership change to make sure the change is visible on subsequent commands or playbooks.
##### How I discovered this:

This is an alternate way to reproduce the bug.  I'm including it because it's a realistic use case that triggers the bug.

Starting with an Ubuntu standard configuration where uid 1000 is a non-root administrative user account with `sudo` privileges, I created a playbook which changed `sudoers` to allow members of the `sudonp` group to use `sudo` without a password, then added the administrative account to the `sudonp` group.  Then I applied the playbook with `--ask-sudo-pass`.

Then I ran another playbook, and was quite surprised when it refused to execute without a sudo password -- and then had fixed itself when I came back a few hours later (due to ControlPersist timeout expiring)!

**Comment by jimi-c** [comment]
As you noted, this is not an Ansible issue. The credentials are in effect for the session since you're connecting as the user you're modifying, so the only way to see them updated is to terminate the connection or to not use the same user as the one you're modifying. I don't think we're interested in any "hacky" solutions here, as there's no good way to tell that the user has created this situation. If you have any further questions or want to discuss this further, this is more of a mailing list use-case question than a bug.

Thanks!

**Comment by iturgeon** [comment]
Adding this for any future searchers:

`local_action` can be used to aid what @picomancer was trying to do within the playbook.

``` yaml
- name: Users - put ssh user in yipee group
  sudo: yes
  user: name={{ ansible_ssh_user }} groups=yipee append=yes

# match your configured ssh ControlPath -- EX:  ~/.ssh/mux-%r@%h:%p
# deleting this file seems force the next command to be run in a new ssh connection
# this is important when changing the user group of the ansible_ssh_user which requires a logout
- name: Users - Force new connection so user group takes effect
  local_action: file path=~/.ssh/mux-{{ ansible_user_id }}@{{ ansible_default_ipv4.address }}:22 state=absent
```
