### ISSUE TITLE
Unsafe "taint" Jinja2 tripwire always assumes string output

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#79249]
### Summary

When unsafe-tainted string values are sent through a final type-coercing Jinja filter, the unsafe tripwire at the end still post-wraps it in `AnsibleUnsafeText`. This effectively means that any tainted value cannot be stored or passed as an argument as anything but a string (only in-place conversions seem to work).

This shouldn't be a problem under data tagging, since the `UntrustedAsTemplate` tag is type-agnostic.

A sane solution in the existing codebase might be to only apply the unsafe string wrapper at the end if the resulting raw type from the Jinja output was a string. Not even sure if it's worth fixing, since nobody seems to have noticed in the last several versions, and assuming data tagging actually lands in 2.15.

### Issue Type

Bug Report

### Component Name

Templating/Jinja

### Ansible Version

```console
at least 2.11->devel
```

### Configuration

```console
NA
```

### OS / Environment

NA

### Steps to Reproduce

```yaml (paste below)
- hosts: localhost
  gather_facts: no
  tasks:
  - raw: echo 0.123
    register: rawout

  - set_fact:
      floatvalue: |-
        {{ rawout.stdout | float }}

  - debug:
      var: floatvalue

  - debug:
      msg: |
        type of floatvalue is {{ floatvalue.__class__ }}
        type of rawout.stdout is {{ rawout.stdout.__class__ }}
        in-place conversion is {{ (floatvalue | float) }}
```

### Expected Results

```
TASK [raw] ***************************************************************************************************
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "0.123\n", "stdout_lines": ["0.123"]}

TASK [set_fact] **********************************************************************************************
ok: [localhost] => {"ansible_facts": {"floatvalue": 0.123}, "changed": false}

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "floatvalue": 0.123
}

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "type of floatvalue is <class 'float'>\ntype of rawout.stdout is <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>\nin-place conversion is <class 'float'>\n"
```

### Actual Results

```console
TASK [raw] ***************************************************************************************************
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "0.123\n", "stdout_lines": ["0.123"]}

TASK [set_fact] **********************************************************************************************
ok: [localhost] => {"ansible_facts": {"floatvalue": "0.123"}, "changed": false}

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "floatvalue": "0.123"
}

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "msg": "type of floatvalue is <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>\ntype of rawout.stdout is <class 'ansible.utils.unsafe_proxy.AnsibleUnsafeText'>\nin-place conversion is <class 'float'>\n"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
