### ISSUE TITLE
builtin.git fails to clone repo with "Host key verification failed"

### ISSUE THREAD

**Issue by DonBower** [ansible/ansible#79268]
### Summary

I use the following task to clone a repo, but it fails with `Host key verification failed`:
```yaml
  - name: Install Private Git Repos
    git:
      repo: "{{ item.repo }}"
      dest: "/home/don/Developer/{{ item.dest }}"
      # key_file: /home/don/.ssh/id_rsa
    with_items:
      - repo: git@github.com:DonBower/ansible.git
        dest: ansible
```
logging into the host, and executing `git clone  git@github.com:DonBower/ansible.git /home/don/Developer/ansible` works.

### Issue Type

Bug Report

### Component Name

git

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.2]
  config file = /Users/don/Developer/ansible/ansible.cfg
  configured module search path = ['/Users/don/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/don/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/don/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/don/Library/Python/3.9/bin/ansible
  python version = 3.9.14 (main, Sep  6 2022, 23:29:09) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(/Users/don/Developer/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/don/Developer/ansible/ansible.cfg) = ['/Users/don/Developer/ansible/hosts.yaml']
INTERPRETER_PYTHON(/Users/don/Developer/ansible/ansible.cfg) = auto_silent
```

### OS / Environment

local system is MacBook Pro:
$ uname -a      
Darwin MacbookPro.ag6hq.net 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

target system is Ubuntu:
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Steps to Reproduce

```yaml (paste below)
---
- hosts: ideapad
  gather_facts: true
  remote_user: don
  become: true
  connection: ssh

  tasks:
  - name: Install Private Git Repos
    git:
      repo: "{{ item.repo }}"
      dest: "/home/don/Developer/{{ item.dest }}"
      # key_file: /home/don/.ssh/id_rsa
    with_items:
      - repo: git@github.com:DonBower/ansible.git
        dest: ansible
```

### Expected Results

I expect to clone the private repo.
The following task does succeed:
```yaml
  - name: Install Public Git Repos
    git:
      repo: "{{ item.repo }}"
      dest: "/home/don/Developer/{{ item.dest }}"
    with_items:
      - repo: https://github.com/geerlingguy/ansible-for-kubernetes.git
        dest: ansible-for-kubernetes
```

### Actual Results

```console
<ideapad-ubuntu.ag6hq.net> ESTABLISH SSH CONNECTION FOR USER: don
<ideapad-ubuntu.ag6hq.net> SSH: EXEC sshpass -d46 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/don/.ssh/id_rsa"' -o 'User="don"' -o ConnectTimeout=10 -o 'ControlPath="/Users/don/.ansible/cp/c5fe1c3389"' ideapad-ubuntu.ag6hq.net '/bin/sh -c '"'"'rm -f -r /home/don/.ansible/tmp/ansible-tmp-1667251529.4855602-77185-54510963276003/ > /dev/null 2>&1 && sleep 0'"'"''
<ideapad-ubuntu.ag6hq.net> (0, b'', b"OpenSSH_8.6p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 54: Applying options for *\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/don/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/don/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 77155\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
failed: [ideapad-ubuntu.ag6hq.net] (item={'repo': 'https://github.com:DonBower/ansible.git', 'dest': 'ansible'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "cmd": [
        "/usr/bin/git",
        "fetch",
        "--tags",
        "origin"
    ],
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "accept_newhostkey": false,
            "archive": null,
            "archive_prefix": null,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/home/don/Developer/ansible",
            "executable": null,
            "force": false,
            "gpg_whitelist": [],
            "key_file": "/home/don/.ssh/id_rsa",
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://github.com:DonBower/ansible.git",
            "separate_git_dir": null,
            "single_branch": false,
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "item": {
        "dest": "ansible",
        "repo": "https://github.com:DonBower/ansible.git"
    },
    "msg": "Failed to download remote objects and refs:  fatal: unable to access 'https://github.com:DonBower/ansible.git/': URL using bad/illegal format or missing URL\n"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
