### ISSUE TITLE
shell running exec "{{ ansible_env.SHELL }}" freezes ansible-playbook

### ISSUE THREAD

**Issue by jamesbraza** [ansible/ansible#79279]
### Summary

I have discovered `exec "{{ ansible_env.SHELL }}"` in ansible `shell` will freeze an Ansible playbook.

### Issue Type

Bug Report

### Component Name

ansible-playbook

### Ansible Version

```console
$ ansible --version

ansible [core 2.11.12]
  config file = /Users/user/code/repo/ansible/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/code/repo/venv/lib/python3.7/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/user/code/repo/venv/bin/ansible
  python version = 3.7.14 (default, Oct 20 2022, 15:52:47) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = False
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CALLBACKS_ENABLED(/Users/user/code/repo/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_HOST_LIST(/Users/user/code/repo/ansible/ansible.cfg) = ['/Users/user/code/repo/ansible/inventories/hosts.yml']
```

### OS / Environment

- Control node: macOS Monterey version 12.6
- Target node: Debian 10.13

On the target, `$SHELL` evaluates to `/bin/bash`.

### Steps to Reproduce

```yaml
- name: Append pyenv to ~/.bashrc
  # Normally this goes after pyenv installation, but let's put this first so we
  # can refresh the SHELL in conjunction with the installation
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - '# pyenv'
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'

- name: Install pyenv
  register: result
  shell:  # SEE: https://github.com/pyenv/pyenv-installer#install
    cmd: |
      curl -sSL https://pyenv.run -o /tmp/install.sh
      bash /tmp/install.sh
      rm /tmp/install.sh
      exec "{{ ansible_env.SHELL }}"
    creates: "{{ ansible_env.HOME }}/.pyenv"
  changed_when:
    - '"Restart your shell for the changes to take effect" in result.stderr'
```

- When you remove the `exec "{{ ansible_env.SHELL }}"` line, the playbook doesn't freeze
- When you add it back in, the `exec "{{ ansible_env.SHELL }}"` line freezes the playbook

### Expected Results

`ansible-playbook` not to freeze.

### Actual Results

Indefinite hang once it gets to `exec "{{ ansible_env.SHELL }}"`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
