### ISSUE TITLE
[regression] ignore_errors always ignore failures when variable is used to control it introduced in ansible 2.3.0

### ISSUE THREAD

**Issue by humberto-garza** [ansible/ansible#79287]
I ran into this old issue today:
#32384

But it is closed (It is locked so I could not reopen).

And then I found this comment
_Originally posted by @nelsg in https://github.com/ansible/ansible/issues/32546#issuecomment-369228153_

> For information:
> I'm faced the same issue when I upgraded from Ansible 2.2.1 to 2.3.2.
> After some tests, this regression was introduced with Ansible 2.3.0.
> Then caution if you planed to upgrade to a version higher than 2.2.3, choose at least version 2.4.2.
> 
> Maybe this fix must be integrated with future version 2.3.3, no ?

This is my ansible version
```sh
ansible --version
ansible [core 2.11.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/plugins/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

**Comment by humberto-garza** [comment]
I tried the same things mentioned in the previous issue:

I tried the following combinations:
```yaml
ignore_errors: "{{ignore_assertion_errors}}"
ignore_errors: ignore_assertion_errors
ignore_errors: "{{ignore_assertion_errors|bool}}"
ignore_errors: ignore_assertion_errors|bool
```

and nothing worked either.
