### ISSUE TITLE
vault/unvault filter: default to vault-password(s) from CLI

### ISSUE THREAD

**Issue by azrdev** [ansible/ansible#79298]
### Summary

The `vault` and `unvault` [filters](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hashing-and-encrypting-strings-and-passwords) can be used to decrypt a vaulted variable, but they require explicit passing of the vault password. It would be much more useful and consistent, if these could hook into the normal `--ask-vault-pass` / `--vault-id` mechanism of obtaining vault passwords.

### Issue Type

Feature Idea

### Component Name

vault filter

### Additional Information

I'm trying to use an `ansible-vault`-encrypted value from dynamic inventory (`compose:` in  [vmware_vm_inventory](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vm_inventory_inventory.html#parameter-compose)) as `ansible_ssh_password`, from AWX.
Getting the variable works:
```yaml
# vmware_vm_inventory.yaml
compose:
  ansible_ssh_password: '"{{ var_in_vcenter | default(none) }}"'
```
but vault-decryption is not triggered for dynamic inventory #9771 (because it lives in ansible.parsing.dataloader.load_from_file -- i.e. the yaml parsing code).

Instead, I could insert the `unvault` filter, but then I have to pass the vault-password as extra_vars (AWX: through a custom credential type) and possibly expose it to any subsequent playbook code:
```yaml
# vmware_vm_inventory.yaml
compose:
  ansible_ssh_password: '"{{ var_in_vcenter | unvault(vault_password) | default(none) }}"'
```

Apart from being the logical thing, having `unvault` access the "normal" vault-passwords provided to ansible would really enable implementing my use case.

Related issue:
- #22382

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
