### ISSUE TITLE
COLLECTION_PATH variable

### ISSUE THREAD

**Issue by markfaine** [ansible/ansible#79304]
### Summary

I have global handlers that are included in a playbook, in order to get them to work *without using a hard-coded path* I have to do some hackery like this:

```yaml
  handlers:
    - name: systemd-daemon-reload
      ansible.builtin.include_tasks:
        file: >-
          {{ lookup('ansible.builtin.env', 'ANSIBLE_COLLECTIONS_PATHS')
          | split(':') | list | flatten
          | first }}/ansible_collections/nats/default/handlers/systemd_daemon_reload.yml
```
This works, but you can see the obvious problem is if ANSIBLE_COLLECTIONS_PATHS contains more than one collections path and the path to the handler is not valid for the first path, it will fail.  

### Issue Type

Feature Idea

### Component Name

!component  =/unknown

### Additional Information

What is needed is something akin to the `role_path` special variable but specifically for the path to the collection.  I have tried using relative links, using `playbook_dir`, using relative links and special variables in combination but nothing seems to be bullet proof.  What I really want to avoid at all costs is a hard-coded path or a playbook var that is essentially a hard-coded path in a var.

I can understand how it might be difficult to know which collection contains the intended handlers, and they may even reside in more than one collection, so it might also work to just allow an optional variable added to `handlers`:

```yaml
handlers:
   collection: my.collection
```

Or even just a top level playbook identifier to indicate what collection relative paths should use as a base directory:

```yaml
collection: my.collection
...
handlers:
  - name: myhandler
      ansible.builtin.include_tasks: 
        file: handlers/myhandler.yml
```

I'm sure there are many different ways to accomplish this and I'm not really married to any of them.  I just want a bullet proof way to refer to a specific collection from within an ansible file.

Perhaps there is already a canonical way to do this with Ansible and I'm just missing it even after searching for literally hours over the course of the past few months.  If so, please let me know how to do this without hard-coding the path and I'm sorry for wasting your time.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@markfaine: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by bcoca** [comment]
If you want to distribute the handlers in a collection, they need to be part of a role, then to use them you just need to import/include the role:

```
roles:
  - nats.default.rolehashandlers
```
Which now makes any handlers from that role directly notifiable from the play.

We are unlikely to add 'tasks' nor 'handlers' resolution to collections as they also have a dwim/inheritance interaction with plays and roles and can end up being very confusing (no matter which way we resolve conflicts) for the user.

**Comment by markfaine** [comment]
Did something change?  I am 100% certain that the documentation included a section on global shared handlers using include_tasks but it's now a 404.   I can do it that way but it's certainly not optimal, especially since you're forcing me to rewrite a bunch of playbooks.

**Comment by sivel** [comment]
There is nothing wrong with using `include_tasks` in a handler, but collections are not designed to ship arbitrary task files.  There is simply no support, nor planned support for arbitrary task files.  As such, you need to operate within the intended design of collections, which would be to utilize a role as your mechanism of registering a handler, to include files that live inside of a that role, instead of trying to poke at something that is purposefully not implemented.

Here is an example:

```yaml
- hosts: localhost
  gather_facts: false
  roles:
    - nats.default.handlers
  tasks:
    - debug:
      changed_when: true
      notify:
        - 'nats.default.handlers : systemd-daemon-reload'
```

```
└── ansible_collections
    └── nats
        └── default
            └── roles
                └── handlers
                    └── handlers
                        ├── main.yml
                        │   │ - name: systemd-daemon-reload
                        │   │   include_tasks: systemd_daemon_reload.yml
                        └── systemd_daemon_reload.yml
                            │ - debug:
                            │     msg: systemd_daemon_reload 1
                            │
                            │ - debug:
                            │     msg: systemd_daemon_reload 2
```

```
No config file found; using defaults

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
changed: [localhost] => {
    "msg": "Hello world!"
}

RUNNING HANDLER [nats.default.handlers : systemd-daemon-reload] ****************
included: /Users/sivel/projects/ansibledev/playbooks/79304/collections/ansible_collections/nats/default/roles/handlers/handlers/systemd_daemon_reload.yml for localhost

RUNNING HANDLER [nats.default.handlers : debug] ********************************
ok: [localhost] => {
    "msg": "systemd_daemon_reload 1"
}

RUNNING HANDLER [nats.default.handlers : debug] ********************************
ok: [localhost] => {
    "msg": "systemd_daemon_reload 2"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
