### ISSUE TITLE
variable undefined when using delegate_to

### ISSUE THREAD

**Issue by slommi71** [ansible/ansible#79313]
### Summary

When we try to use delegate_to in ansible 2.9.27 it fails with "msg: '''sidadm'' is undefined.
When we do not use delegate_to keyword it works.

delegate_to works, when using other standard modules. We observe this issue so far only, when using ansible.builtin.file module.

### Issue Type

Bug Report

### Component Name

ansible file module

### Ansible Version

```console
$ ansible --version
2.9.27
```

### Configuration

```console
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/export/home/ansible/.ansible.cfg) = True
DEFAULT_FORKS(/export/home/ansible/.ansible.cfg) = 50
DEFAULT_LOAD_CALLBACK_PLUGINS(/export/home/ansible/.ansible.cfg) = True
DEFAULT_MODULE_PATH(/export/home/ansible/.ansible.cfg) = ['/path_to/ansible/modules']
DEFAULT_REMOTE_USER(/export/home/ansible/.ansible.cfg) = admusr
DEFAULT_STDOUT_CALLBACK(/export/home/ansible/.ansible.cfg) = yaml
HOST_KEY_CHECKING(/export/home/ansible/.ansible.cfg) = False
```

### OS / Environment

ansible and play run on "RedHat Enterprise Linux 8.6 (Ootpa)"

Target systems are SUSE 12 and SUSE 15.
Tha's wha, we are using a special python environment in inventory for all SUSE systems:

```yaml
 environment:
    PYTHONHOME: "/usr/"
    PYTHONPATH: "/usr/lib64/python3.6"
```

### Steps to Reproduce

Our playbook:

```yaml 
- name: delegate_to issue
  hosts: server1234
  tasks:

  - set_fact:
      sidadm: "xxxadm"

  - name: create file with delegate and remote_user {{ sidadm }}
    file:
      path: /tmp/delegate_{{ sidadm }}_remote.tmp
      state: touch
      mode: u=rw,g=r,o=r
    remote_user: "{{ sidadm }}"
    delegate_to: server5678
```

### Expected Results

file created
```yaml
TASK [create file - delegate - remote_user xt1adm] **************************************************************************************************
changed: [server1234-> server1234]
```

### Actual Results

```console
variable sidadm is resolved in line "name:" of this task,  
but the variable is undefined for remote_user attribute - IN THE SAME TASK.



TASK [create file - delegate - remote_user xxxadm] **************************************************************************************************
fatal: [server1234 -> server5678]: FAILED! =>
  msg: '''sidadm'' is undefined'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
