### ISSUE TITLE
Environment variables not getting set

### ISSUE THREAD

**Issue by MASACR99** [ansible/ansible#79336]
### Summary

Hey! So I'm trying to check if a few environment variables are getting setup correctly, these are:

`environment:
    AWS_ACCESS_KEY: "{{ my_access_key | default() }}"
    AWS_SECRET_KEY: "{{ my_secret_key | default() }}"
    EC2_REGION: "{{ region | default() }}"`
*note, removing "| default()" does NOT affect behaviour

When I run a task checking if all of them are defined, it fails every single time, even though my_access_key, my_secret_key and region are defined.

`- name: Check defined vars
  fail:
    msg: To run this task you need to pass AWS credentials and region, either with -e or a variables file
  when: (EC2_REGION is undefined) or (AWS_ACCESS_KEY is undefined) or (AWS_SECRET_KEY is undefined)`

To load these variables I'm passing a vault file.

But the most fun part about it is that when I run, for example, amazon.aws.ec2_key (or any other aws task) it just runs, without error and works flawlessly.

Please help me make sense of this.

### Issue Type

Bug Report

### Component Name

aws

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/masa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.04.1 LTS

### Steps to Reproduce

Main ansible yml:
```yaml
---
- name: Create SSH Key
  hosts: localhost
  connection: localhost
  environment:
    AWS_ACCESS_KEY: "{{ my_access_key | default() }}"
    AWS_SECRET_KEY: "{{ my_secret_key | default() }}"
    EC2_REGION: "{{ region | default() }}"

  tasks:
    - name: Check defined vars
      fail:
        msg: To run this task you need to pass AWS credentials and region, either with -e or a variables file
      when: (EC2_REGION is undefined) or (AWS_ACCESS_KEY is undefined) or (AWS_SECRET_KEY is undefined)  

    - name: Generate and store ssh key
      include_tasks: "../SSH_Keys/gen_and_store.yml"
```
gen_and_store.yml:
```yaml
- name: Show correct usage
  fail:
    msg: To run this task you need to set region using -e "region='valid_AWS_region'" or -e "@variables_file.yml"
  when: (region is undefined)

- name: Set ssh name
  ansible.builtin.set_fact:
    name: "{{ansible_date_time.epoch}}"
  when: name is undefined

- name: Generate SSH key
  amazon.aws.ec2_key:
    name: "{{name}}"
    region: "{{region}}"
    state: present
  register: key_creation

- name: Check if directory exists
  file:
    path: "./keys"
    state: directory

- name: Save private key 
  copy: content="{{ key_creation.key.private_key }}" dest="./keys/{{name}}.pem" mode=0400
  when: key_creation.changed
```

### Expected Results

Expected the check task to get skipped and the environment variables to be defined

### Actual Results

```console
Check task fails and shows msg.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
