### ISSUE TITLE
git task fails when 2 consecutive clones are attempted (and therefore does not work with loops)

### ISSUE THREAD

**Issue by turekg** [ansible/ansible#79350]
### Summary

I need to clone two different repositories. Initially I tried to use a loop
```
    - name: Clone MROA and MROATOOLS
      git:
        repo: "{{ item.repo }}"
        dest: "{{ workspace }}/{{ item.dest }}"
        version: "{{ item.version }}"
      loop:
        - repo: git@gitlab.mercator-ocean.fr:ctestut/MROATOOLS.git
          dest: "MROATOOLS"
          version: oper_EIS202211
        - repo: git@gitlab.mercator-ocean.fr:ctestut/MROA.git
          dest: "MROA"
          version: oper_EIS202211
```

but this always failed with an  `error: pathspec 'oper_EIS202211,' did not match any file(s) known to git.`, and also the second item in the loop was being cloned in the first item's directory. 

I finally gave up on this and simply wrote two separate tasks. Again the second task failed in the same manner.
This confirms my suspicion that after the first clone, the pwd is "lost" to the task.

### Issue Type

Bug Report

### Component Name

ansible.builtin.git

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.5]
  config file = /home/smer/turekg/.ansible.cfg
  configured module search path = ['/home/smer/turekg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/smer/turekg/miniconda3/envs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/smer/turekg/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/smer/turekg/miniconda3/envs/ansible/bin/ansible
  python version = 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
/home/smer/turekg/miniconda3/envs/ansible/lib/python3.10/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
DEFAULT_STDOUT_CALLBACK(/home/smer/turekg/.ansible.cfg) = yaml
```

### OS / Environment

Linux version 4.18.0-348.20.1.el8_5.x86_64 (mockbuild@dal1-prod-builder001.bld.equ.rockylinux.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-3) (GCC))

### Steps to Reproduce

git clone in loop or consecutively

### Expected Results

Expect clone and checkout to work atomically

### Actual Results

```console
error: pathspec my_branch did not match any file(s) known to git.`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
