### ISSUE TITLE
Need a attribute to determine if the async task has failed.

### ISSUE THREAD

**Issue by sibisita** [ansible/ansible#79367]
### Summary

**finished** parameter is present to know if an async jobs with poll 0 has completed. But we do not have a **failed** parameter to see if the task is failed.

Below is a sample usecase:
```
---
- name: A Playbook to test Async and Poll
  hosts: localhost
  vars:
  tasks:
    - name: Execute the script
      shell: "sleep {{ item }}"
      register: async_output
      async: 30
      poll: 0
      loop:
        - 20
        - 10
        - 100 **#should fail in 30 secs**
        - 200 
    
    - name: Async Status capture
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      ignore_errors: yes
      until: job_result.**finished**
      retries: 10
      delay: 5
      loop: "{{ async_output.results }}"
```

The loop for 100 and 200 fails in 30 secs as async is set to 30. But that is not known to async_status and waits for 50 secs each for 100 and 200 before it fails. Increasing the overall time to 100+ secs. If there was a 'failed' parameter to check it would be completed in 30 secs.

Time taken is attached below:
Gathering Facts ------------------------------------------------------------------------------------------- 1.51s
Execute the script ---------------------------------------------------------------------------------------- 2.24s
Async Status capture ------------------------------------------------------------ **131.71s** # need to reduce this

### Issue Type

Feature Idea

### Component Name

async_status

### Additional Information

```
- name: Async Status capture
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      ignore_errors: yes
      until: job_result.finished             # Similarly 'job_result.failed' boolean needs to be there, that can specify if task is failed
      retries: 10
      delay: 5
      loop: "{{ async_output.results }}"
```
### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
