### ISSUE TITLE
ansbile.builtin.shell plugin parameters don't match documentation.

### ISSUE THREAD

**Issue by rjeffman** [ansible/ansible#79379]
### Summary

On the latest version of `ansible.builtin.shell` there is a parameter named `warn` that allows disabling of plugin warnings, but when running with the parameter set, an error saying the parameter is not supported is raised.

### Issue Type

Bug Report

### Component Name

plugin ansible.builtin.shell

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/rjeffman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible-freeipa-tests/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/rjeffman/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/ansible-freeipa-tests/bin/ansible
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] (/tmp/ansible-freeipa-tests/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Controller is running Fedora 36 with Python virtual environment and ansible-core installed through `pip`.

### Steps to Reproduce

```yaml (paste below)
  - name: Remove certificate files.
    ansible.builtin.shell: rm -f "private{{ item }}.key" "cert{{ item }}.pem" "cert{{ item }}.der" "cert{{ item }}.b64"
    with_items: [1]
    become: no
    delegate_to: localhost
    args:
      warn: no
```

### Expected Results

The plugin executes without showing warnigs, as it did until ansible-core 2.13.

### Actual Results

```console
TASK [Remove certificate files.] ***********************************************
failed: [nifty_margulis -> localhost] (item=1) => {"ansible_loop_var": "item", "changed": false, "item": 1, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, executable, stdin_add_newline, creates, stdin, strip_empty_ends, removes, argv, chdir."}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
