### ISSUE TITLE
New ansible fact "free space"

### ISSUE THREAD

**Issue by don-rumata** [ansible/ansible#79419]
### Summary

Hi, I instal large size software and need to check if there is enough disk space.

Can you add a new ansible fact "free space on the root partition"? The "Avail" column in "df". Now, for Windows I use code like this (see Additional Information):

Something like this:

```yaml
ansible_free_root_space:
  kb:
  mb:
  gb:
```

### Issue Type

Feature Idea

### Component Name

setup

### Additional Information

```yaml
- name: Get info about free disk space 4 Windows
  when: ansible_os_family == 'Windows'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_shell:
    '[math]::Round((Get-CimInstance -ClassName Win32_LogicalDisk
    | Where-Object {$_.DeviceID -like $env:SystemDrive}
    | select -ExpandProperty FreeSpace) / 1024 / 1024)'
  register: win_info_free_disk_space_system
  changed_when: false

- set_fact:
    free_disk_space_system_mb_fact:
      "{{ win_info_free_disk_space_system.stdout | trim | int }}"
  when: ansible_os_family == 'Windows'
  ```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
