### ISSUE TITLE
cron Module with_items and normal + special_time not possible

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#79425]
### Summary

The option special_time in the cron module is missing a default for normal entries. Without such a entry an with_items loop is not possible if you have normal entries and special entries mixed in a list.

Or is there any other way to set the Variable to undefined in the loop?
I also tried "" in for special_time. But the same error occures. 

Yes as a workaround i could define two blocks to manage Crontab but with_items is better readable and faster then two tasks.

### Issue Type

Bug Report

### Component Name

cron

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/etc/ansible/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/collections']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/library']
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

### OS / Environment

Ubuntu 22.04 LTS

### Steps to Reproduce

```yaml (paste below)
  - name:                            Create Crontab entrie
    cron:
      name:                          "{{item.name}}"
      minute:                        "{{item.minute}}"
      hour:                          "{{item.hour}}"
      special_time:                  "{{item.special_time}}"
      job:                           "/usr/local/bin/ceLandscape.bash '{{ce_landscape__tags}}' '{{ce_landscape__parameters}}' > /dev/null 2>&1"
    become: yes
    with_items:
       - { name: "CE-LandScape",           minute: "0", hour: "6", special_time: null }
       - { name: "CE-LandScape_on_reboot", minute: "*", hour: "*", special_time: "reboot" }
```

### Expected Results

Two entries in crontab. 
One with the normal time and one for the reboot.

### Actual Results

```console
TASK [ce.LandScape : Create Crontab entrie] ***************************************************************************
failed: [da5.xxx.local] (item={'name': 'CE-LandScape', 'minute': '0', 'hour': '6', 'special_time': None}) => {"ansible_loop_var": "item", "changed": false, "item": {"hour": "6", "minute": "0", "name": "CE-LandScape", "special_time": null}, "msg": "value of special_time must be one of: reboot, yearly, annually, monthly, weekly, daily, hourly, got: "}
ok: [da5.xxx.local] => (item={'name': 'CE-LandScape_on_reboot', 'minute': '*', 'hour': '*', 'special_time': 'reboot'})
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
