### ISSUE TITLE
No option to exclude files when copying a folder

### ISSUE THREAD

**Issue by mem212** [ansible/ansible#79421]
### Summary

I am trying to copy a folder from local to remote destination using the copy module. However I see no options to exclude files.
For example, if would like to ignore the .git folder while executing the copy.

### Issue Type

Feature Idea

### Component Name

copy

### Additional Information

```yaml (paste below)
  tasks:
  - name: Copy website files to remote server
    copy:
      src: website/
      dest: /var/www/mywebsite/
      exclude: ".git;temp/;*.sh"
```

Where . git and temp are two folders to exclude and *.sh is a pattern of files to exclude during the copy.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
