### ISSUE TITLE
ansible.builtin.get_url should warn when used with root

### ISSUE THREAD

**Issue by mkesper** [ansible/ansible#79424]
### Summary

When using ansible.builtin.get_uri to download an executable, it's tempting to run the wohle function as root. This is probably not a good idea security wise. get_uri should output a warning when used with become or the download part should always be done separately, without additional rights.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.get_url

### Additional Information

```yaml (paste below)
  get_url:
    url: https://example.com/download/my_binary
    dest: /usr/local/bin/great_tool
    mode: '0755'
  become: yes
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
