### ISSUE TITLE
client certificate authentication towards Windows 11 with TLS 1.3

### ISSUE THREAD

**Issue by craditsch** [ansible/ansible#79432]
### Summary

As already explained in this Issue [#77768](https://github.com/ansible/ansible/issues/77768) a connection to a Windows 11 machine through WinRM certification auth is not working and throughs an error.

### Issue Type

Bug Report

### Component Name

apt

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/Qf6Kw9Jt5nbI/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/Qf6Kw9Jt5nbI/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Ansible controller: Ubuntu 20.04

Target machine: Windows 11
```powershell 
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22621  0
```

Client machine for PSSession: Windows 11
```powershell 
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22000  0
```

## Ansible controller
Tested with server cert validation:
```yml
ansible_connection: winrm
ansible_winrm_server_cert_validation: validate
ansible_winrm_cert_pem: ../../files/mgmtcerts/{{ lookup('env','UPN_USER') }}.pem
ansible_winrm_cert_key_pem: ../../files/mgmtcerts/{{ lookup('env','UPN_USER') }}-private.pem
ansible_winrm_ca_trust_path: ../../files/mgmtcerts/server.pem
ansible_winrm_transport: certificate
```
Tested without server cert validation:
```yml
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_cert_pem: ../../files/mgmtcerts/{{ lookup('env','UPN_USER') }}.pem
ansible_winrm_cert_key_pem: ../../files/mgmtcerts/{{ lookup('env','UPN_USER') }}-private.pem
# ansible_winrm_ca_trust_path: ../../files/mgmtcerts/server.pem
ansible_winrm_transport: certificate
```
Ini:
```yml
[test]
dev-gc01 ansible_host=winvm0
```

## Windows
[docs.ansible.com](https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#certificate)

### Test Powershell connection on Windows client
Tested Powershell remote session from a windows client to the same target machine and it worked:
1. Import Server certificate as trusted CA
2. Import User certificate in personal store
3. Add hostname of target Windows to hosts file with ip address.
4. Execute Powershell command to connect to Windows OS
```powershell
Enter-PSSession -ComputerName winvm0 -UseSSL -CertificateThumbprint <usercert thumbprint>
[winvm0]: PS C:\Users\test\Documents> hostname
winvm0
```

### Expected Results

```bash
TASK [Gathering Facts] *********************************************************
ok: [dev-gc01]
```

### Actual Results

```console
fatal: [dev-gc01]: UNREACHABLE! => {"changed": false, "msg": "certificate: HTTPSConnectionPool(host='winvm0', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])\")))", "unreachable": true}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
