### ISSUE TITLE
ansible playbook with libssh connection for network doesn't work with cron but work in cli with same user

### ISSUE THREAD

**Issue by fstefaniak** [ansible/ansible#79438]
### Summary

Hello

it's look like the inventory_hostname is not resolved with cron launch playbook for ssh (type libssh) connection for network cli : it's why i think of libssh or jinja bug.
otherwise, the playbook with the same user work in CLI.

for remote_addr :
https://github.com/ansible-collections/ansible.netcommon/blob/main/docs/ansible.netcommon.libssh_connection.rst

the only issue i have found with the same error : 
https://github.com/ansible/ansible/issues/78926

### Issue Type

Bug Report

### Component Name

ansible-libssh, jinja

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.6]
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_FORKS(/home/ansible/.ansible.cfg) = 40
DEFAULT_NO_TARGET_SYSLOG(/home/ansible/.ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/ansible/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/ansible/.ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/home/ansible/.ansible.cfg) = True
USE_PERSISTENT_CONNECTIONS(/home/ansible/.ansible.cfg) = True

CALLBACK:
========

default:
_______
display_ok_hosts(/home/ansible/.ansible.cfg) = False
display_skipped_hosts(/home/ansible/.ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_auto_add(/home/ansible/.ansible.cfg) = True
host_key_checking(/home/ansible/.ansible.cfg) = False
use_persistent_connections(/home/ansible/.ansible.cfg) = True

ssh:
___
host_key_checking(/home/ansible/.ansible.cfg) = False
```

### OS / Environment

Debian 11 bullseye

### Steps to Reproduce

```
- hosts: localhost
  tasks:
    - name: test cmd
      shell: "echo '{{inventory_hostname}}' at $(date) >> /tmp/test2.log"
- hosts: sw_online
  serial: 10
  strategy: free
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65643761...
    ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32386...
  tasks:
    - name: test cmd
      shell: "echo '{{inventory_hostname}}' at $(date) >> /tmp/test2.log"
```

### Expected Results

localhost at mar. 22 nov. 2022 09:01:04 CET
192.168.192.26 at mar. 22 nov. 2022 09:01:06 CET
...

### Actual Results

```console
if gather_facts: yes, it will establish a ssh connection so : 
- work in cli : 
localhost at mar. 22 nov. 2022 09:01:04 CET
192.168.192.26 at mar. 22 nov. 2022 09:01:06 CET
- but in cron launch palybook : 
fatal: [192.168.192.8]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"cisco.ios.ios_facts": {"failed": true, "invocation": {"module_args": {"available_network_resources": false, "gather_network_resources": null, "gather_subset": ["min"]}}, "msg": "ssh connection failed: ssh connect failed: Failed to resolve hostname inventory_hostname (Name or service not known)"}}, "msg": "The following modules failed to execute: cisco.ios.ios_facts\n"}
...

if gather_facts: no , no ssh connection so it's work even in cron launch playbook :
192.168.192.97 at mar. 22 nov. 2022 09:14:32 CET
...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
