### ISSUE TITLE
Ansible kills detached children processes

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/ansible#79436]
### Summary

I have a script that does: "nohup ./executable_name > /dir/nohup.out 2&>1 &"
Please don't ask why I'm not using service files, we don't own the server, it's a bank, very tight security approvals, we are stuck with these kind of bash scripts.

When i execute this script in a playbook, at the end of the play the process is dead. It is started but gets killed at the end. My assumption is nohup does not work and it's not getting detached.

### Issue Type

Bug Report

### Component Name

shell,command

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.6]
  config file = /home/ec2-user/automation-ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ec2-user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ec2-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ec2-user/.local/bin/ansible
  python version = 3.9.10 (main, Feb  9 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.1.2
  libyaml = True


I have reproduced this with ansible 2.9.5 and python 3.6 as well.
```

### Configuration

```console
[defaults]
inventory=/dir/hosts
```

### OS / Environment

RHEL 8, RHEL 9

### Steps to Reproduce

Here is a snippet of an ansible play:
```yaml (paste below)
- name: process start
  hosts: hostname

  tasks:
  - name: start process
    shell:
    args:
      chdir: "/script/location"
      cmd: "./script.sh"
```
      
Very simple. Now after the task is done, the process is dead. 
It was started by the play (I can confirm by checking logs, or by adding a ps -ef at the end of the script) but when that task is done, the process is killed.  
If i add another task afterwards that just does a ps -ef, i can see the process is dead. 
So not even at the end of the play but at the end of that task.
    
I replicated this on our development server and on an ec2 test machine in my personal aws.
    
Dev server: Redhat 8, python3.6,  ansible 2.9.5
AWS ec2: Redhat 9, python 3.9, ansible 2.13.6
    
I have replicated this with the shell and command module.
If I use connection: local like below then the process is not killed.
```yaml (paste below)
- name: process start
  hosts: hostname
  connection: local

  tasks:
  - name: start process
    shell:
    args:
      chdir: "/script/location"
      cmd: "./script.sh"
```

Also, If I use the nohup command directly in the playbook like below, then the process is not killed.
 
```yaml (paste below)
- name: process start
  hosts: hostname

- name: start process
    shell:
    args:
      chdir: "/script/location"
      cmd: "nohup ./executable_name > /dir/nohup.out 2&>1 &"
```

### Expected Results

Proccess is alive when play finishes.

### Actual Results

```console
Process is dead at the end of the play.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
