### ISSUE TITLE
acme_certificate not working with vaulted key

### ISSUE THREAD

**Issue by yakhatape** [ansible/ansible#79451]
### Summary

Hi,
I'm trying to use the module acme_certificate with an account key files vaulted with ansible vault but i got the following error : 

<html>
<body>

msg: 'Error while parsing account key: error while loading key: (''Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).'', [_OpenSSLErrorWithText(code=503841036, lib=60, reason=524556, reason_text=b''error:1E08010C:DECODER routines::unsupported'')])'
--

<br class="Apple-interchange-newline">
</body>
</html>

the acme key is generated with the following task : 
```- name: "Generate the acme acccount private key"
  community.crypto.openssl_privatekey:
    path: "{{ role_path + '/files/key/acme-account.key' }}"
    type: RSA
    size: 4096
    state: present
  delegate_to: localhost```

And vaulted in our repository, and used by our certificate tasks like this : 
```- name: "Create a challenge for {{ CN }} using a account key file."
  community.crypto.acme_certificate:
    account_key_src: "{{ role_path + '/files/acme-account.key' }}"
    account_email: XXXXXXX
    src: "{{ role_path + '/files/csr/' + CN + '.csr' }}"
    dest: "{{ role_path + '/files/certificats/' + CN + '' }}"
    challenge: dns-01
    acme_directory: XXXXXXXXXXXXXXXX
    acme_version: 2
    validate_certs: no
    remaining_days: 30
  register: challenge```

I don't have any problem with others vaulted files used by other tasks. Looks like we can't use an acme account key vaulted file ... but don't know why ? is It normal ?


### Issue Type

Bug Report

### Component Name

acme_certificate

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/lib/rundeck/rundeck_virtual_env/mcas_automatisation_certificats-39/lib/python3.9/site-packages/ansible
  ansible collection location = /var/lib/rundeck/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/lib/rundeck/rundeck_virtual_env/mcas_automatisation_certificats-39/bin/ansible
  python version = 3.9.6 (default, Jun 24 2022, 12:33:34) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/data/gitworkspace/ansible/int']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/etc/ansible/ansible.cfg) = False

SHELL:
=====

sh:
__
remote_tmp(/etc/ansible/ansible.cfg) = /tmp/
```

### OS / Environment

CentOS Linux release 7.9.2009 (Core)

### Steps to Reproduce

Have an acme account + acme account key 
1. Vault your acme account key
2. Pass to your playbook the vault password
3. Use the following task example : 

```
- name: "Create a challenge for {{ CN }} using a account key file."
  community.crypto.acme_certificate:
    account_key_src: "{{ role_path + '/files/acme-account.key' }}"
    account_email: XXXXX
    src: "{{ role_path + '/files/csr/' + CN + '.csr' }}"
    dest: "{{ role_path + '/files/certificats/' + CN + '' }}"
    challenge: dns-01
    acme_directory: XXXXX
    acme_version: 2
    validate_certs: no
    remaining_days: 30
  register: challenge
```

### Expected Results

I expected that module works with vaulted files like many others ..

### Actual Results

```console
fatal: [localhost]: FAILED! => changed=false 
msg: 'Error while parsing account key: error while loading key: (''Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).'', [_OpenSSLErrorWithText(code=503841036, lib=60, reason=524556, reason_text=b''error:1E08010C:DECODER routines::unsupported'')])'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
