### ISSUE TITLE
Cannot get mime_type of ISO file correctly

### ISSUE THREAD

**Issue by crawfordma** [ansible/ansible#79454]
### Summary

I was trying to get the stat of an ISO file with following code
```
stat:
  path: "{{ source }}"
  get_checksum: no
  get_attributes: no
ignore_errors: yes
register: source_attrs
```
and source_attrs.stat.mimetype is unkown, howerver it should be /x-iso9660-image.
My question is there any python packages need to be installed? Because the mimetype check will be passed in another environment.
Also I'm sure the ISO file has correct type:
```
Python 3.6.8 (default, Jun 14 2022, 12:54:58) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-10)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magic
>>> magic.from_file("/iso_generation/platformx_core/platformx_core-8.6.9-20221117034017.iso",mime=True)
'application/x-iso9660-image'
```

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /iso_generation/platformx_core/sdk/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

RHEL 8

### Steps to Reproduce

need an ISO file as {{ source }}
```
            - name: "Verifying Product Source: {{ source }}"
              stat:
                path: "{{ source }}"
                get_checksum: no
                get_attributes: no
              ignore_errors: yes
              register: source_attrs
            - assert:
                that: source_attrs.stat.exists
                msg: "Unable to find {{ source }}"
            - assert:
                that: source_attrs.stat.mimetype == 'application/x-iso9660-image'
                msg: "{{ source }} is not an ISO"
```

### Expected Results

No error

### Actual Results

```console
Based on above code
xxx.iso is not an ISO
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
