### ISSUE TITLE
unable to transfer file on macos 13.0.1 (22A400)

### ISSUE THREAD

**Issue by DmitryShumsky** [ansible/ansible#79466]
### Summary

after update to 13.0.1 (22A400) i faced with issue:
```
    amazon-ebs.concourse-web: <127.0.0.1> (255, b'', b'Unable to negotiate with 127.0.0.1 port 56818: no matching host key type found. Their offer: ssh-rsa\r\n')
    amazon-ebs.concourse-web: fatal: [default]: UNREACHABLE! => {
    amazon-ebs.concourse-web:     "changed": false,
    amazon-ebs.concourse-web:     "msg": "Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 56818: no matching host key type found. Their offer: ssh-rsa",
    amazon-ebs.concourse-web:     "unreachable": true
    amazon-ebs.concourse-web: }
```
after this i add to ~/.ssh/config next strings:
```
Host *
  PubkeyAcceptedAlgorithms +ssh-rsa
  HostkeyAlgorithms +ssh-rsa
```
and got error
```
    amazon-ebs.concourse-web: fatal: [default]: FAILED! => {
    amazon-ebs.concourse-web:     "msg": "failed to transfer file to /Users/dmshumsk/.ansible/tmp/ansible-local-79996_oqhzg0j/tmp1wpcwcky /home/ubuntu/.ansible/tmp/ansible-tmp-1669364324.845543-80000-197664538684223/AnsiballZ_command.py:\n\n"
    amazon-ebs.concourse-web: }
```
i'll try change sftp to scp in ansible.cfg, but this doesnt help

ssh -vvvv log:
```
amazon-ebs.concourse-web:     "msg": "failed to transfer file to /Users/dmshumsk/.ansible/tmp/ansible-local-82765_933uyui/tmpg17sotlf /home/ubuntu/.ansible/tmp/ansible-tmp-1669364757.650252-82768-259508242379076/AnsiballZ_command.py:\n\nExecuting: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command sftp\nOpenSSH_9.0p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /Users/dmshumsk/.ssh/config\r\ndebug1: /Users/dmshumsk/.ssh/config line 5: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 27: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/dmshumsk/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/dmshumsk/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 82772\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nscp: debug2: Remote version: 3\r\nscp: debug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\nscp: debug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\nscp: debug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"fsync@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"lsetstat@openssh.com\" revision 1\r\nscp: debug2: Sending SSH2_FXP_STAT \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669364757.650252-82768-259508242379076/AnsiballZ_command.py\"\r\nscp: debug3: Sent message fd 6 T:17 I:1\r\nscp: debug1: stat remote: No such file or directory\r\nscp: debug3: source_sftp: copying local /Users/dmshumsk/.ansible/tmp/ansible-local-82765_933uyui/tmpg17sotlf to remote /home/ubuntu/.ansible/tmp/ansible-tmp-1669364757.650252-82768-259508242379076/AnsiballZ_command.py\r\nscp: debug2: do_upload: upload local \"/Users/dmshumsk/.ansible/tmp/ansible-local-82765_933uyui/tmpg17sotlf\" to remote \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669364757.650252-82768-259508242379076/AnsiballZ_command.py\"\r\nscp: debug2: Sending SSH2_FXP_OPEN \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669364757.650252-82768-259508242379076/AnsiballZ_command.py\"\r\nscp: debug3: Sent dest message SSH2_FXP_OPEN I:2 P:/home/ubuntu/.ansible/tmp/ansible-tmp-1669364757.650252-82768-259508242379076/AnsiballZ_command.py M:0x001a\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 4 32768 bytes at 0\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:8 O:131072 S:1381\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 5 32768 bytes at 32768\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 6 32768 bytes at 65536\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 7 32768 bytes at 98304\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 8 1381 bytes at 131072\r\nscp: debug3: Sent message SSH2_FXP_CLOSE I:3\r\nscp: debug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\n"
```
if i change to scp (;scp_if_ssh=True):

`z
```
(amazon-ebs.concourse-web:     "msg": "failed to transfer file to /Users/dmshumsk/.ansible/tmp/ansible-local-83414b8mvw98d/tmpyuvfz1ov /home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py:\n\nExecuting: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command sftp\nOpenSSH_9.0p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /Users/dmshumsk/.ssh/config\r\ndebug1: /Users/dmshumsk/.ssh/config line 5: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 27: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/dmshumsk/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/dmshumsk/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 83421\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nscp: debug2: Remote version: 3\r\nscp: debug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\nscp: debug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\nscp: debug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"fsync@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"lsetstat@openssh.com\" revision 1\r\nscp: debug2: Sending SSH2_FXP_STAT \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\"\r\nscp: debug3: Sent message fd 6 T:17 I:1\r\nscp: debug1: stat remote: No such file or directory\r\nscp: debug3: source_sftp: copying local /Users/dmshumsk/.ansible/tmp/ansible-local-83414b8mvw98d/tmpyuvfz1ov to remote /home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\r\nscp: debug2: do_upload: upload local \"/Users/dmshumsk/.ansible/tmp/ansible-local-83414b8mvw98d/tmpyuvfz1ov\" to remote \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\"\r\nscp: debug2: Sending SSH2_FXP_OPEN \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\"\r\nscp: debug3: Sent dest message SSH2_FXP_OPEN I:2 P:/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py M:0x001a\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 4 32768 bytes at 0\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:8 O:131072 S:1382\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 5 32768 bytes at 32768\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 6 32768 bytes at 65536\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 7 32768 bytes at 98304\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 8 1382 bytes at 131072\r\nscp: debug3: Sent message SSH2_FXP_CLOSE I:3\r\nscp: debug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\n")
```

### Issue Type

Bug Report

### Component Name

ssh

### Ansible Version

```console
nsible --version
ansible [core 2.13.6]
  config file = /Users/dmshumsk/work/git/cicd-core/packer/ansible.cfg
  configured module search path = ['/Users/dmshumsk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/6.6.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/dmshumsk/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.8 (main, Oct 21 2022, 22:22:30) [Clang 14.0.0 (clang-1400.0.29.202)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

macos 13

### Steps to Reproduce

```
cat concourse.yml 
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  # We must avoid gathering facts here since we may not have python yet
  gather_facts: no
  roles:
    - role: bootstrap

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  roles:
    - role: system
    - role: users
    - role: datadog
    - role: concourseci
    - role: aws

- hosts: sl_helpers
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  roles:
    - role: sl_helpers

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  roles:
    - role: hardening

```

```
cat inventory/group_vars/concourseci_web.yml 
concourseci_cluster_name: neteng
concourseci_etc: /etc/concourse

github_host: github.office.opendns.com
github_ca_cert_file: github_ca_cert.pem
github_ca_cert_path: "{{ concourseci_etc }}/{{ github_ca_cert_file }}"

github_org: neteng
github_team: cicd_core

system_pip_packages: 
  - botocore
  - aws_secretsmanager_caching
  - datadog_api_client
  - datadog
concourseci_environment_file: concourseci.env
concourseci_environment_path: "{{ concourseci_etc }}/{{ concourseci_environment_file }}"

concourseci_rbac_file: concourse_rbac.yaml
concourseci_rbac_path: "{{ concourseci_etc }}/{{ concourseci_rbac_file }}"

monitoring_role_name: viewer

concourseci_rbac:
  - GetBuild

concourseci_environment:
  CONCOURSE_TLS_BIND: 8080
  CONCOURSE_TLS_BIND_PORT: 8443
  CONCOURSE_POSTGRES_SSLMODE: require
  CONCOURSE_POSTGRES_DATABASE: concourse
  CONCOURSE_GITHUB_HOST: "{{ github_host }}"
  CONCOURSE_SECRET_CACHE_ENABLED: true
  CONCOURSE_SECRET_CACHE_DURATION: 5m
  CONCOURSE_SECRET_RETRY_ATTEMPTS: 5
  CONCOURSE_SECRET_RETRY_INTERVAL: 10s
  CONCOURSE_AWS_SECRETSMANAGER_PIPELINE_SECRET_TEMPLATE: "{% raw %}/cicd/concourseci/{{.Team}}/{{.Pipeline}}/{{.Secret}}{% endraw %}"
  CONCOURSE_AWS_SECRETSMANAGER_TEAM_SECRET_TEMPLATE:  "{% raw %}/cicd/concourseci/{{.Team}}/{{.Secret}}{% endraw %}"
  CONCOURSE_MAIN_TEAM_GITHUB_TEAM: "{{ github_org }}:{{ github_team }}"
  # For LDAP Configuration Information:
  # https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W80b51708eb7b_4ba1_9f1a_d77ccdccb126/page/How%20to%20use%20DSX
  CONCOURSE_LDAP_DISPLAY_NAME: name
  CONCOURSE_LDAP_HOST: host
  CONCOURSE_LDAP_BIND_DN: "bind_dn"
  CONCOURSE_LDAP_USER_SEARCH_BASE_DN: "base_dn"
  CONCOURSE_LDAP_USER_GROUP_BASE_DN: "group_base_dn"
  CONCOURSE_LDAP_GROUP_SEARCH_NAME_ATTR: cn
  CONCOURSE_LDAP_USER_SEARCH_USERNAME: uid
  CONCOURSE_LDAP_USER_SEARCH_EMAIL_ATTR: mail
  CONCOURSE_LDAP_USER_SEARCH_ID_ATTR: uid
  CONCOURSE_LDAP_USER_SEARCH_NAME_ATTR: displayName
  # Hides secrets which are accidentally displayed in task output
  CONCOURSE_ENABLE_REDACT_SECRETS: true
  # Datadog reporting via prometheus emitter
  CONCOURSE_PROMETHEUS_BIND_IP: localhost
  CONCOURSE_PROMETHEUS_BIND_PORT: 9090

concourse_ci_config:
  container_placement_strategy: fewest-build-containers

concourseci_binaries:
  - src: concourse/bin/concourse
    dest: "{{ concourseci_install_base }}concourse/bin/concourse"
    link: /usr/local/bin/concourse

concourseci_startup_script:
  name: concourse-web.sh
  dest: /usr/local/bin/

concourseci_additional_files:
  - src: concourse_metric_bot.service
    dest: /etc/systemd/system
  - src: concourse_metric_bot.timer
    dest: /etc/systemd/system/
  - src: concourse_rbac.yaml
    dest: /etc/concourse/
  - src: concourse_metric_bot.py
    dest: /usr/local/bin/

systemd_units:
  - concourse-web.service
  - concourse_metric_bot.service

concourseci_additional_systemd_units:
  - concourse_metric_bot.timer

aws_service_timers:
 - cloudwatch-metrics

aws_scripts:
 - cloudwatch-metric-running-containers.sh

datadog_tags:
  - cicd
  - concourseci
  - concourse-role:concourse_web

```
```

cat roles/concourseci/tasks/main.yml 
---
- name: Create User
  user:
    system: yes
    name: "{{ concourseci_user }}"

- name: Add user to additional groups
  user:
    name: "{{ concourseci_user }}"
    groups: "{{ concourseci_user_additional_groups }}"
  when: concourseci_user_additional_groups is defined

# Can't seem to get unarchive to fetch *and* extract, so we have to fetch first
# and extract later, including cleaning up the downloaded file.
- name: Fetch TGZ
  get_url:
    url: "{{ concourseci_url }}"
    dest: "/tmp/{{ concourseci_package }}"

- name: Extract TGZ
  unarchive:
    remote_src: yes
    src: "/tmp/{{ concourseci_package }}"
    dest: "{{ concourseci_install_base }}"

- name: Remove TGZ
  file:
    path: "/tmp/{{ concourseci_package }}"
    state: absent

- name: Link Binaries
  file:
    src: "{{ item.dest }}"
    path: "{{ item.link }}"
    state: link
  with_items:
    - "{{ concourseci_binaries }}"

- name: Install Services
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - "{{ systemd_units }}"

- name: Install Startup Scripts
  template:
    src: "{{ concourseci_startup_script.name }}.j2"
    dest: "{{ concourseci_startup_script.dest }}{{ concourseci_startup_script.name }}"
    mode: 0755
    owner: concourse
    group: concourse

- name: Create secrets directory
  file:
    path: "{{ concourseci_secrets_path }}"
    state: directory
    owner: concourse
    group: concourse
    mode: 0700

- name: Set up Secrets Mount
  lineinfile:
    path: /etc/fstab
    line: "{{ concourseci_secrets_mount }}"

- name: Create {{ concourseci_etc }} directory
  file:
    path: "{{ concourseci_etc }}"
    state: directory
    owner: "{{ concourseci_user }}"
    group: "{{ concourseci_user }}"
  when: concourseci_etc is defined

- name: Template ConcourseCI Environment file
  template:
    src: "{{ concourseci_environment_file }}.j2"
    dest: "{{ concourseci_environment_path }}"
    owner: "{{ concourseci_user }}"
    group: "{{ concourseci_user }}"
  when:
    - concourseci_etc is defined
    - concourseci_environment_file is defined
    - concourseci_environment_path is defined


- name: Template additional files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ item.dest }}{{ item.src }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ concourseci_additional_files }}"
  when:
    - concourseci_additional_files is defined

- name: Enable Concourse Services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ systemd_units }}"

- name: Enable Additional Systemd Units
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ concourseci_additional_systemd_units }}"
  when:
    - concourseci_additional_systemd_units is defined
```

### Expected Results

expect that all files wil be tranfered to ec2 insance without error

### Actual Results

```console
`(amazon-ebs.concourse-web:     "msg": "failed to transfer file to /Users/dmshumsk/.ansible/tmp/ansible-local-83414b8mvw98d/tmpyuvfz1ov /home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py:\n\nExecuting: program /usr/bin/ssh host 127.0.0.1, user (unspecified), command sftp\nOpenSSH_9.0p1, LibreSSL 3.3.6\r\ndebug1: Reading configuration data /Users/dmshumsk/.ssh/config\r\ndebug1: /Users/dmshumsk/.ssh/config line 5: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files\r\ndebug1: /etc/ssh/ssh_config line 27: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/dmshumsk/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/dmshumsk/.ssh/known_hosts2'\r\ndebug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 83421\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nscp: debug2: Remote version: 3\r\nscp: debug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\nscp: debug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\nscp: debug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"fsync@openssh.com\" revision 1\r\nscp: debug2: Server supports extension \"lsetstat@openssh.com\" revision 1\r\nscp: debug2: Sending SSH2_FXP_STAT \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\"\r\nscp: debug3: Sent message fd 6 T:17 I:1\r\nscp: debug1: stat remote: No such file or directory\r\nscp: debug3: source_sftp: copying local /Users/dmshumsk/.ansible/tmp/ansible-local-83414b8mvw98d/tmpyuvfz1ov to remote /home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\r\nscp: debug2: do_upload: upload local \"/Users/dmshumsk/.ansible/tmp/ansible-local-83414b8mvw98d/tmpyuvfz1ov\" to remote \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\"\r\nscp: debug2: Sending SSH2_FXP_OPEN \"/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py\"\r\nscp: debug3: Sent dest message SSH2_FXP_OPEN I:2 P:/home/ubuntu/.ansible/tmp/ansible-tmp-1669365169.1742988-83417-138498238383258/AnsiballZ_command.py M:0x001a\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 4 32768 bytes at 0\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:32768\r\nscp: debug3: Sent message SSH2_FXP_WRITE I:8 O:131072 S:1382\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 5 32768 bytes at 32768\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 6 32768 bytes at 65536\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 7 32768 bytes at 98304\r\nscp: debug3: SSH2_FXP_STATUS 0\r\nscp: debug3: In write loop, ack for 8 1382 bytes at 131072\r\nscp: debug3: Sent message SSH2_FXP_CLOSE I:3\r\nscp: debug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\n")`
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
