### ISSUE TITLE
`restart service when config file newer than process` feature for service module

### ISSUE THREAD

**Issue by julyclyde** [ansible/ansible#79465]
### Summary

Now I'm using a
```
- template:
  register: config
- service:
    state: restarted
  when: config.changed
```
playbook to manage my service.
Sometimes, it failed for some reason, then I replay the playbook but the service would not start, because the config file is changed *last time* rather than *this time*.

I suggest to add an ability to compare file's mtime and process's start time, and provide a `restart if config changed` attribute

### Issue Type

Feature Idea

### Component Name

service module

### Additional Information

```
- service:
    name: xxx
    state: restarted
    if_config_changed: /etc/xxx.conf
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
