### ISSUE TITLE
Unexpected behavior of "ignore_errors" expression in case of undefined variables

### ISSUE THREAD

**Issue by jbyibm** [ansible/ansible#79460]
### Summary

In our code we have a task in a playbook with an expression for ignore_errors. When we have an expression the behavior is not correct.  See explanation below.

### Issue Type

Bug Report

### Component Name

!component 

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.12]
  config file = None
  configured module search path = ['/home/jby/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/jby/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
DEFAULT_FORKS(/home/jby/ansible.cfg) = 25
HOST_KEY_CHECKING(/home/jby/ansible.cfg) = False
```

### OS / Environment
Red Hat Enterprise Linux release 8.6 (Ootpa)

### Steps to Reproduce

In our code we have a task in a playbook with an expression for ignore_errors

test_case.yml
```
- hosts: all
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
    - name: "Test Case"
      shell: "exit -1"
      delegate_to: localhost
      ignore_errors: "{{ test_case_ignore_error | bool if test_case_ignore_error is defined else False}}"
```

inventories/group_vars/all.yml
```
environment_vars:
  my_var: "{{ var_defined_in_extra_vars }}"
```

inventories/
```
all:
  hosts:
    host_01:
      ansible_host: test
```

### Expected Results

When we run this playbook with `-e test_case_ignore_error=false` we would expect that Ansible do not ignore the fact that we have an undefined variable `var_defined_in_extra_vars` in our all.yml file.

```
ansible-playbook test_case.yml -i inventories -e test_case_ignore_error=false
```

### Actual Results

```console
TASK [Test Case] *****************************************************************************************************************************************************************************
task path: /mnt/e/Temp/bug_ansible/playbooks/test_case.yml:5
fatal: [zos_host_01 -> localhost]: FAILED! => {
    "msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: {'my_var': '{{ var_defined_in_extra_vars }}'}: 'var_defined_in_extra_vars' is undefined\n\nThe error appears to be in '/mnt/e/Temp/bug_ansible/playbooks/test_case.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: \"Test Case\"\n      ^ here\n"
}
...ignoring
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
