### ISSUE TITLE
usermod: user 'user' does not exist in /etc/passwd\n

### ISSUE THREAD

**Issue by XDavidT** [ansible/ansible#79479]
### Summary

Trying to check if the user exists and then create it. (but even without 'when' getting the same error)
Using this role:
```
- name: Adding the user user
  when: '"user" not in ansible_facts.getent_passwd'
  ansible.builtin.user:
    name: user
    comment: DeepCube standard user
    update_password: always
    password: "{{ dc_user_pass | password_hash('sha512') }}"
    uid: 1030
    groups: mygroup, docker
    append: yes
    create_home: yes
    home: /home/user
    shell: "{{ usr_shell }}"
```

### Issue Type

Bug Report

### Component Name

user

### Ansible Version

```console
ansible 2.10.8
  config file = /home/xdavidt/dev/iac/ansible/ansible.cfg
  configured module search path = ['/home/xdavidt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]

```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

DEFAULT_HOST_LIST(/home/xdavidt/dev/iac/ansible/ansible.cfg) = ['/home/xdavidt/dev/iac/ansible/inventories']
DEFAULT_ROLES_PATH(/home/xdavidt/dev/iac/ansible/ansible.cfg) = ['/home/xdavidt/dev/iac/ansible/roles']
HOST_KEY_CHECKING(/home/xdavidt/dev/iac/ansible/ansible.cfg) = False
```

### OS / Environment

My OS: ubuntu 22.04
Target is Ubuntu 20.04.5

### Steps to Reproduce

```yaml (paste below)
- name: Adding the user user
  when: '"user" not in ansible_facts.getent_passwd'
  ansible.builtin.user:
    name: user
    comment: DeepCube standard user
    update_password: always
    password: "{{ dc_user_pass | password_hash('sha512') }}"
    uid: 1030
    groups: mygroup, docker
    append: yes
    create_home: yes
    home: /home/user
    shell: "{{ usr_shell }}"
```

### Expected Results

Check if user exists, if not create it.

### Actual Results

```console
TASK [add_users : Adding the user dcuser] ******************************************************************************************************************
fatal: [bb11]: FAILED! => {"changed": false, "msg": "usermod: user 'user' does not exist in /etc/passwd\n", "name": "user", "rc": 6}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
