### ISSUE TITLE
ansible.builtin.files state empty directory

### ISSUE THREAD

**Issue by agowa** [ansible/ansible#79499]
### Summary

ansible.builtin.file state should have an additional state for an empty directory. Basically an "absent" without deleting the directory itself.

Real-world example:
Make sure the "/run/systemd/network" folder is empty. Just having absent here is misleading, as the folder itself will be recreated by systemd-networkd, so this task will erroneously report changed. This task should only make sure that there are no configuration files within this folder. But there is currently no simple straightforward way to declare this.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.file

### Additional Information

```yaml
- name: remove systemd-networkd runtime configuration
  ansible.builtin.file:
    path: "/run/systemd/network"
    state: absent
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
