### ISSUE TITLE
ansible.builtin.service_facts module issue

### ISSUE THREAD

**Issue by kingtutt1906** [ansible/ansible#79527]
### Summary

Running a playbook from certain machines that are using the ansible.builtin.service_facts module to populate the list of current services on a system, results in a message stating the following: Do you agree with this license? [y/n]:

As a result of this message, the playbook is halted on the machine, and waits for you to press either [y/n], for automation purposes this is less than ideal. 

 I haven't found a way to circumvent the message or at least pass any additional arguments to the code in the playbook which sets the service variable:

- name: Populate service facts
  ansible.builtin.service_facts:

### Issue Type

Bug Report

### Component Name

ansible.builtin.service_facts module

### Ansible Version

```console
ansible [core 2.13.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
*This command did not generate any additional output on machine
```

### OS / Environment

Red Hat Enterprise Linux release 8.7 (Ootpa)

### Steps to Reproduce

```
- name: Check If Certbot is Installed
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:

    - name: Populate System Service Facts
      no_log: true
      ansible.builtin.service_facts:


    - name: Check System To See if Nginx Is Running & Store Results into Variable
      no_log: true
      set_fact:
        web_server_system_running_status_variable: "Nginx Is Running"
      when: ('running' in ansible_facts.services["nginx.service"].state )

```

### Expected Results

I expect for the ansible.builtin.service_facts  module to return a list of services on machine.

It does work on some machines, while others it requests the following:
"Do you agree with this license?"

The only way around this is to either enter y/n on the command line or press CTRL-C.

### Actual Results

```console
TASK [Populate System Service Facts] ***************************************************************************************************************
task path: /root/certbot_check.yml:105
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1670248650.4629216-39422-134290979396585 `" && echo ansible-tmp-1670248650.4629216-39422-134290979396585="` echo /root/.ansible/tmp/ansible-tmp-1670248650.4629216-39422-134290979396585 `" ) && sleep 0'
Using module file /usr/lib/python3.9/site-packages/ansible/modules/service_facts.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-3909681thy3j7/tmpok2cyqte TO /root/.ansible/tmp/ansible-tmp-1670248650.4629216-39422-134290979396585/AnsiballZ_service_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1670248650.4629216-39422-134290979396585/ /root/.ansible/tmp/ansible-tmp-1670248650.4629216-39422-134290979396585/AnsiballZ_service_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.9 /root/.ansible/tmp/ansible-tmp-1670248650.4629216-39422-134290979396585/AnsiballZ_service_facts.py && sleep 0'
Do you agree with this license? [y/n]:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
