### ISSUE TITLE
`ansible.builtin.user`: Allow an option for no action to be taken if the user account doesn't exist

### ISSUE THREAD

**Issue by zevaryx** [ansible/ansible#79548]
### Summary

In the latest current version of Ansible, the `ansible.builtin.user` module has a `state` flag that triggers an action if the state doesn't match. At my work, we use Active Directory for most of our users, and during an issue with Active Directory, a playbook was run to change group memberships on a server, and ended up creating local users that had the same usernames. What would be a nice feature is the ability to add a flag to prevent the action if the account does/doesn't exist (maybe something along the lines of `take_action` or `create_user`) and have it be True by default to not break existing playbooks

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

```yaml
- name: Add devs to tomcat group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: tomcat
    append: yes
    take_action: no
  loop:
    - user1
    - user2
    - user3
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
