### ISSUE TITLE
Unexpected string added when using community.windows.win_xml

### ISSUE THREAD

**Issue by sefalbe** [ansible/ansible#79547]
### Summary

I'm working with ansible to replace some values in web.config file, I'm using `community.windows.win_xml` module.

- name: Change webconfig value
      community.windows.win_xml:
        path: "{{ web_projects_path }}\\Web.config"
        xpath: //configuration/connectionStrings/add[@name="EntityConn"]
        attribute: connectionString
        fragment: '{{ EntityConn }}'
        type: attribute
        state: present

As you can see, I use _**EntityConn**_ variable to set value: 

vars:
  EntityConn: 'metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True&quot;'

The win_xml module works but adds _**amp**_ word when find `&quot` having as result `&amp;quot`, and the final output:

`<add name="EntityConn" connectionString="metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&amp;quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated 
Security=True;MultipleActiveResultSets=True&amp;quot" providerName="System.Data.EntityClient" />`

Very appreciate if someone can help

### Issue Type

Bug Report

### Component Name

community.windows.win_xml

### Ansible Version

```console
$ ansible --version
ansible 2.9.6
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Linux 4ansible 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)

- name: Windows Feature
  hosts: Windows2016
  vars:
    web_projects_path: "C:\\Path\\To\\Project"
    EntityConn: 'metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True&quot;'

  tasks:
    - name: Print values
      ansible.builtin.debug:
        msg: MMSPRP5Entities {{ EntityConn}}

    - name: Change webconfig value
      community.windows.win_xml:
        path: "{{ web_projects_path }}\\Web.config"
        xpath: //configuration/connectionStrings/add[@name="EntityConn"]
        attribute: connectionString
        fragment: '{{ EntityConn }}'
        type: attribute
        state: present
```
And here my Web.config file:
```
<configuration>
  <connectionStrings>
    <add name="EntityConn" connectionString="" providerName="System.Data.EntityClient"/>
  </connectionStrings>
</configuration>
```

### Expected Results

The expected result is the connection string without _**amp**_ string
```
<configuration>
  <connectionStrings>
    <add name="EntityConn" connectionString="metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated Security=True;MultipleActiveResultSets=True&quot;" providerName="System.Data.EntityClient"/>
  </connectionStrings>
</configuration>
```

### Actual Results

```console
<configuration>
  <connectionStrings>
    <add name="EntityConn" connectionString="metadata=res://*/Northwind.csdl|res://*/Northwind.ssdl|res://*/Northwind.msl;provider=System.Data.SqlClient;provider connection string=&amp;quot;Data Source=.\sqlexpress;Initial Catalog=Northwind;Integrated 
Security=True;MultipleActiveResultSets=True&amp;quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
</configuration>
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
