### ISSUE TITLE
different behaviour for `ignore_errors` between `include`, `include_tasks` and `import_tasks`

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible#79543]
### Summary

Ohai,

not sure it's an actual bug or unclear docs, but filing it here and will let y'all decide for me ;)

The `include` action (module?) is deprecated in favor of `include_tasks` and `import_tasks`, depending on the usecase. My understanding usually was that one wants `include_tasks` in the most common cases, but I might be wrong.

While migrating one of our playbooks, we noticed an interesting behavior change: We have task files that contain tasks that will potentially fail, but that is OK in the context of the playbook we are migrating right now, so we used to have a `include: fail.yml` with `ignore_errors: true` which we first blindly changed to `include_tasks: fail.yml`, but that broke the error ignoring, while `import_tasks` works fine (with the same behavior as with `include` before).

Is this *expected*? If so, I think the documentation about the differences of `import_tasks` vs `include_tasks` should better point that out. If not, well, then it's a bug ;-)

### Issue Type

Bug Report

### Component Name

include_tasks

### Ansible Version

```console
% ansible --version
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/evgeni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/evgeni/Devel/ansible-wtf/include-fail/venv/lib64/python3.10/site-packages/ansible
  ansible collection location = /home/evgeni/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/evgeni/Devel/ansible-wtf/include-fail/venv/bin/ansible
  python version = 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] (/home/evgeni/Devel/ansible-wtf/include-fail/venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
$ ansible --version
```

### Configuration

```console
% ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Fedora 36, but shouldn't matter

### Steps to Reproduce

fail.yml:
```yaml
---
- name: fail
  fail:
    msg: "{{ who }} lost the game"
```

include.yml:
```yaml
---
- name: include
  hosts: localhost
  gather_facts: false
  tasks:
    - include: fail.yml
      vars:
        who: you
      ignore_errors: true
```

include_tasks.yml:
```yaml
---
- name: include_tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - include_tasks: fail.yml
      vars:
        who: you
      ignore_errors: true
```

import_tasks.yml:
```yaml
---
- name: import_tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - import_tasks: fail.yml
      vars:
        who: you
      ignore_errors: true
```

### Expected Results

I have expected all invocations to end up with the error being ignored.

### Actual Results

```console
% ansible-playbook include.yml      
PLAY [include] *****************************************************************

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "you lost the game"}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1   


% ansible-playbook include_tasks.yml 
PLAY [include_tasks] ***********************************************************

TASK [include_tasks] ***********************************************************
included: /home/evgeni/Devel/ansible-wtf/include-fail/fail.yml for localhost

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "you lost the game"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


% ansible-playbook import_tasks.yml
PLAY [import_tasks] ************************************************************

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "you lost the game"}
...ignoring

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/include_tasks.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_tasks.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is documented at https://docs.ansible.com/ansible-core/2.14/playbook_guide/playbooks_reuse.html#comparing-includes-and-imports-dynamic-and-static-re-use

Under the `Task options` row:

* `include_*` - Apply only to include task itself
* `import_*` - Apply to all child tasks in import

To get the behavior you want, would require something like:

```yaml
- include_tasks:
    file: foo.yml
    apply:
      ignore_errors: true
```

See https://docs.ansible.com/ansible-core/2.14/collections/ansible/builtin/include_tasks_module.html#parameter-apply
