### ISSUE TITLE
ansible.builtin.rpm_key fails in certain cases when deleting a key

### ISSUE THREAD

**Issue by kkeane** [ansible/ansible#79585]
### Summary

When deleting a key by key ID that has already been deleted, rpm_key will fail.

### Issue Type

Bug Report

### Component Name

rpm_key

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.9]
  config file = None
  configured module search path = ['/home/kkeane/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kkeane/.virtualenvs/ansible5.4/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/kkeane/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/kkeane/.virtualenvs/ansible5.4/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

RHEL 8

### Steps to Reproduce

```
# The key in this example is an old SHA1 key for the Zoom conferencing software that is deprecated.
# The key is available from https://zoom.us/linux/download/pubkey
- name: Remove outdated GPG key
  become: true
  rpm_key:
    state: absent
    key:   gpg-pubkey-61a7c71d-55740c4b
# ignore errors so we always execute the second attempt
ignore_errors: true

- name: Remove outdated GPG key
  become: true
  rpm_key:
    state: absent
    key:   gpg-pubkey-61a7c71d-55740c4b
```

### Expected Results

The first call to rpm_key should return failed=false and changed either true or false as appropriate
The second call to rpm_key should returned failed=false and changed=false

### Actual Results

The first call will return either failed=false and changed=true if the key exists, or failed=true if the key is missing.
The second call will always return failed=true.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
