### ISSUE TITLE
rds module reporting back incorrect message

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#7958]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6 (devel 9b52ce8a42) last updated 2014/05/05 12:27:23 (GMT +200)
##### Environment:

Fedora Core 19
##### Summary:

I am trying to create an RDS instance inside of a VPC-based, Multi-AZ, DB subnet group.
The 'rds_subnet_group' module does its job perfectly, but I am expecting the 'rds' module to also create the DB security group and authorize a subsequent EC2 security group(?)
##### Steps To Reproduce:

```
  - name: add the RDS instance
    local_action:
      module: rds
      backup_retention: 0
      backup_window: 03:00-04:00
      command: create
      db_engine: MySQL
      db_name: soshop
      engine_version: 5.6.17
      instance_name: scr-db-01
      instance_type: db.m3.xlarge
      iops: 2000
      license_model: general-public-license
      maint_window: Sat:02:00-Sat:03:00
      multi_zone: yes
      parameter_group: scr-db-01
      security_groups: scr-db-01
      size: 200
      subnet: scr-db-01
      username: me
      password: 1234
      region: eu-west-1
      vpc_security_groups: sg-472be522
      wait: yes
      wait_timeout: 300
      zone: eu-west-1b
```
##### Expected Results:

RDS instance is successfully created with all the set parameters and their set values.
##### Actual Results:

```
TASK: [add the RDS instance] ************************************************** 
failed: [localhost] => {"failed": true}
msg: Parameter security_groups invalid for create command

FATAL: all hosts have already failed -- aborting
```

I took a look at the official documentation of the module and its source code and this definitely looks like a problem of testing the presence and precedence of the parameters. This results in a contradiction between output and documentation.
