### ISSUE TITLE
`vars_prompt` default value when shown in console doesn't evaluate jinja2 tags 

### ISSUE THREAD

**Issue by MaikuMori** [ansible/ansible#7959]
##### Summary:

When `default` value in `vars_prompt` contains Jinja2 expression it is printed out as is. When the default value is later used it works as expected.
##### Steps To Reproduce:

A `vars_prompt` section which shows the problem:

```
vars_prompt:
  - name: some_user
    prompt: 'Enter username'
    private: no
    default: '{{ lookup("env", "USER") }}'
```
##### Expected Results:

```
Enter username  [MyUsername]:
```
##### Actual Results:

```
Enter username  [{{lookup("env", "USER")}}]:
```
