### ISSUE TITLE
ansible.builtin.replace allow optional src in addition to path/dest

### ISSUE THREAD

**Issue by diepes** [ansible/ansible#79617]
### Summary

I am trying to copy .kube/config-my-host-original.yaml from the remote server to my local machine and then replace the loopback(127.0.0.1) in the file with the remote host IP.

The problem is that the two steps, copying from the remote and replacing the line in the file, are not idempotent.

A fix would be if the ansible.builtin.replace: module would support an (optional)src, so that it does not change the file we copied but creates a new copy that contains the change resulting in a single operation and is idempotent if nothing changes.

I will then end with a local copy of the original file and a new file with the 127.0.0.1 replaced.

### Issue Type

Feature Idea

### Component Name

replace

### Additional Information

```yaml (paste below)
    - name: Replace 127.0.0.1 with host ip in .kube/config
      delegate_to: 127.0.0.1
      ansible.builtin.replace:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config-k3s.original.yaml"
        regexp: '(\s+)server: https://127.0.0.1:'
        replace: '\1server: https://{{ hostvars[inventory_hostname]["ansible_host"] }}:'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/replace.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/replace.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by diepes** [comment]
Ok i found a good workaround to make the copy replace indempotent.

1. fetch remote file, to local and register task
2. make copy of the local file if  task.changed
3. replace the copy value

```

    - name: copy back /etc/rancher/k3s/k3s.yaml to "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config-k3s-original.yaml"
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config-k3s.original.yaml"
        flat: true
      register: copy_kubeconfig_remote

    - name: copy local before ip change
      delegate_to: 127.0.0.1
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config-k3s.original.yaml"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config-k3s.yaml"
      when: copy_kubeconfig_remote.changed

    - name: Replace 127.0.0.1 with host ip in .kube/config
      delegate_to: 127.0.0.1
      ansible.builtin.replace:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config-k3s.yaml"
        regexp: '(\s+)server: https://127.0.0.1:'
        replace: '\1server: https://{{ hostvars[inventory_hostname]["ansible_host"] }}:'

```
