### ISSUE TITLE
params of command executed on remote host are "mangled"

### ISSUE THREAD

**Issue by davewood** [ansible/ansible#79627]
### Summary

this happens on my specific ansible setup while it works on the setup of a colleague.

this is the task that fails:
```
- name: manage container
  community.general.lxc_container:
    name: "{{ item.name }}"
    backing_store: "{{ item.backing_store | default(omit) }}"
    container_command: "{{ item.container_command | default(lxc_container_defaults.container_command) }}"
    container_config: "{{ item.container_config | default(omit) }}"
    container_log: "{{ item.container_log | default(omit) }}"
    container_log_level: "{{ item.container_log_level | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    template: "{{ item.template | default('debian') }}"
    template_options: "{{ item.template_options | default('--release bullseye --packages=python3,python3-apt') }}"
  with_items: "{{ lxc_containers }}"
```

this is the command that should be executed:
`/usr/bin/lxc-create --name koha-maxlib --quiet --template debian --bdev dir -- --release bullseye --packages=python3,python3-apt`

this is how the command looks like when I run with my ansible setup:
`/usr/bin/lxc-create --name koha-maxlib --quiet template --template backing_store --bdev -- --release bullseye --packages=python3,python3-apt`

details:
> failed: [node01] (item={'name': 'koha-maxlib', 'container_config': ['lxc.net.0.ipv4.gateway = auto', 'lxc.net.0.ipv4.address = 10.34.0.106/24']}) => {"ansible_loop_var": "item", "changed": false, "command": "/usr/bin/lxc-create --name koha-maxlib --quiet template --template backing_store --bdev -- --release bullseye --packages=python3,python3
> -apt", "err": "/usr/bin/lxc-create: unrecognized option '--release'\nUsage: lxc-create --name=NAME --template=TEMPLATE [OPTION...] [-- template-options]\n\nlxc-create creat
> es a container\n\nOptions :\n  -n, --name=NAME               NAME of the container\n  -f, --config=CONFIG           Initial configuration file\n  -t, --template=TEMPLATE   
>     Template to use to setup container\n  -B, --bdev=BDEV               Backing store type to use\n      --dir=DIR                 Place rootfs directory under DIR\n\n  BDE
> V options for LVM (with -B/--bdev lvm):\n      --lvname=LVNAME           Use LVM lv name LVNAME\n                                (Default: container name)\n      --vgname=V
> G               Use LVM vg called VG\n                                (Default: lxc)\n      --thinpool=TP             Use LVM thin pool called TP\n                         
>        (Default: lxc)\n\n  BDEV options for Ceph RBD (with -B/--bdev rbd) :\n      --rbdname=RBDNAME         Use Ceph RBD name RBDNAME\n                                (Def
> ault: container name)\n      --rbdpool=POOL            Use Ceph RBD pool name POOL\n                                (Default: lxc)\n\n  BDEV option for ZFS (with -B/--bdev 
> zfs) :\n      --zfsroot=PATH            Create zfs under given zfsroot\n                                (Default: tank/lxc)\n\n  BDEV options for LVM or Loop (with -B/--bde
> v lvm/loop) :\n      --fstype=TYPE             Create fstype TYPE\n                                (Default: ext4)\n      --fssize=SIZE[U]          Create filesystem of\n  
>                               size SIZE * unit U (bBkKmMgGtT)\n                                (Default: 1G, default unit: M)\n  -- template-options\n         This will pas
> s template-options to the template as arguments.\n         To see the list of options supported by the template,\n         you can run lxc-create -t TEMPLATE -h.\n\nCommon 
> options :\n  -o, --logfile=FILE               Output log to FILE instead of stderr\n  -l, --logpriority=LEVEL          Set log priority to LEVEL\n  -q, --quiet             
>          Don't produce any output\n  -P, --lxcpath=PATH               Use specified container path\n  -?, --help                       Give this help list\n      --usage   
>                    Give a short usage message\n      --version                    Print the version number\n\nMandatory or optional arguments to long options are also manda
> tory or optional\nfor any corresponding short options.\n\nSee the lxc-create man page for further information.\n\n", "item": {"container_config": ["lxc.net.0.ipv4.gateway =
>  auto", "lxc.net.0.ipv4.address = 10.34.0.106/24"], "name": "koha-maxlib"}, "msg": "Failed executing lxc-create.", "rc": 1}

### Issue Type

Bug Report

### Component Name

community.general.lxc_container

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/hks3/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/hks3/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

hks3@354e01eb10e9:~$ cat /etc/debian_version 
bookworm/sid
hks3@354e01eb10e9:~$ uname -a
Linux 354e01eb10e9 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

I expected the correct command to be executed on the remote host. :)

### Actual Results

```console
#the params to the command were mutilated "somehow" and this command was sent

/usr/bin/lxc-create --name koha-maxlib --quiet template --template backing_store --bdev -- --release bullseye --packages=python3,python3-apt
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
