### ISSUE TITLE
Builtin support for OAuth Token Request and Revoke via a `USING`-like statement in Ansible

### ISSUE THREAD

**Issue by timothydilbert** [ansible/ansible#79632]
### Summary

APIs for most clouds and online services are protected using OAuth, which involves using a Client ID and Client Secret to generate a short-lived `access_token`. 

I am trying to create a standardised way of handling token management within my organisation so that access_tokens are automatically revoked once the playbook is finished.

The goal is not to end up with lots of unexpired `access_tokens` left over from scheduled Ansible playbooks, especially if the playbook is scheduled to run more frequently than the expiry date for an access token. The other objective is to mitigate risks of unexpired access_tokens ending up in Stdout in Ansible Tower.

With the OAuth token request and revoke protocol being a standard fairly well followed, I think it would be helpful if Ansible had a generic token request and revoke mechanism, which would encourage better token management within playbooks. I would suggest something roughly equivalent to a `using` statement in C#, whereas, within Ansible, the parameters for the token request would be defined within a code block. The token request would be automatically done in the background by Ansible at the beginning of the code block, and then the token automatically revoked in the background by Ansible at the end of the block as part of the Dispose. 

Below is an example of 

### Issue Type

Feature Idea

### Component Name

ansible

### Additional Information

```yaml

- name: Provision machine
   hosts:
     - virtual_machine

  tasks:

  - name: Task 1
     block:
       oauth_register: token_1
       oauth_base_uri: https://some.web.api
       oauth_client_id: "{{ client_id }}"
       oauth_client_secret: "{{ client_secret }}" 

       - name: Print a message
          ansible.builtin.debug:
            msg: 'OAuth token is requested at the beginning of the block and stored in `token_1`.'

     always:
       - name: Token revoked
          ansible.builtin.debug:
            msg: 'The access_token `token_1` is always revoked, automatically by Ansible.'
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
