### ISSUE TITLE
uri module example states truthy value as 'yes'

### ISSUE THREAD

**Issue by c-schinzer** [ansible/ansible#79644]
### Summary

The second example given on the documentation page for module `ansible.builtin.uri` states the value for `return_content` as `yes`. As this value is expected as a `truthy` boolean, yes is considered invalid by the YAML linter. 

### Issue Type

Documentation Report

### Component Name

ansible.builtin.uri

### Ansible Version

```console
$ansible --version
ansible [core 2.13.1]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
not required for documentation issue
```

### OS / Environment

RHEL

### Additional Information

The second Example given states:

```
(...)
- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
  ansible.builtin.uri:
    url: http://www.example.com
    return_content: yes
  register: this
  failed_when: "'AWESOME' not in this.content"
(...)
```

while the linter complains about this where `return_content` should contain a truthy value i.e. either `true` or `false`. This is correctly documented in the Parameters section. but still wrong in the 2nd example given.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
