### ISSUE TITLE
wait_for no longer works for files in e.g. sysfs because it uses mmap() instead of read()

### ISSUE THREAD

**Issue by rmuir** [ansible/ansible#79683]
### Summary

We have an ansible task using `wait_for` module to wait for network device carrier to be up:
```
wait_for:
  path: "/sys/class/net/{{ device }}/carrier"
  search_regex: "1"
  timeout: 60
```

This no longer works since https://github.com/ansible/ansible/commit/9d4ced1237380051334b54379ff64e45c0341a6d, because `mmap()` is now used instead of `read()`, and it isn't supported by `sysfs` in this case.

Do we really need to use `mmap()`? I imagine it might cause issues with other pseudofilesystems too.

In the meantime, we use a workaround: use grep in a loop instead
```
command:
  cmd: "grep 1 /sys/class/net/{{ device }}/carrier"
timeout: 1
retries: 60
register: carrier
until: carrier is successful
```

### Issue Type

Bug Report

### Component Name

wait_for

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.7]
  config file = None
  configured module search path = ['/Users/rob.muir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rob.muir/workspace/trash/build/.env/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/rob.muir/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/rob.muir/workspace/trash/build/.env/bin/ansible
  python version = 3.10.7 (main, Sep 15 2022, 01:50:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.3
  libyaml = False
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Mac OS controller, Centos Stream 9 target

### Steps to Reproduce

```
# set device to say, eth0 or whatever is on your computer
wait_for:
  path: "/sys/class/net/{{ device }}/carrier"
  search_regex: "1"
  timeout: 60
```

### Expected Results

Expect wait_for to still work with files in /sys

### Actual Results

```console
The wait_for will fail, only with recent ansible versions, due to the use of mmap()
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/wait_for.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/wait_for.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by rmuir** [comment]
Looking at the bugfix here in https://github.com/ansible/ansible/commit/9d4ced1237380051334b54379ff64e45c0341a6d, switching over to `mmap()` is an optimization mixed into the bugfix completely unrelated to the bug or any of the other changes. Bad news!

I think it should be reverted to use `read()` and instead implemented separately as its own issue.

For example, try to use `mmap()` and fall back to `read()` if its not supported (e.g. special filesystems).

**Comment by Derioss** [comment]
up !

we needs this.

**Comment by tannerjfco** [comment]
Are there any plans to fix this bug / #80711 in the near future? We are severely impacted by this bug and as such we are unable to use anything after ansible 2.13.3 as that is the last version with a usable `wait_for`

**Comment by ElijahLynn** [comment]
Thanks @bcoca!

Also, looks like this is in the `devel` branch (8b102dca4a236efcf645e8c17721da549cda61c5) and will possibly be in the upcoming v2.16.1 branch.

**Comment by bcoca** [comment]
#82233 and #82234

**Comment by bviktor** [comment]
Ouch, this one just broke my role. I'm not gonna hardcode my Ansible versions, so until it's fixed, here's what I did:

```yaml
- name: Wait for Tomcat to start up
  wait_for:
    path: "{{ eff_tomcat_home }}/logs/catalina.out"
    search_regex: 'Server startup in'
```

->

```yaml
- name: Wait for Tomcat to start up
  shell:
    cmd: "while true; do grep 'Server startup in' {{ eff_tomcat_home }}/logs/catalina.out && break; sleep 1; done"
  changed_when: false
```

If you don't need the regex, only the file to exist, you can use `while [ ! -f your_file.txt ]; do sleep 1; done` or something.
