### ISSUE TITLE
Diff output for script / shell / command tasks

### ISSUE THREAD

**Issue by sabik** [ansible/ansible#79722]
### Summary

It would be useful for script / shell / command (and similar) tasks to be able to specify a diff for output in diff mode.

Currently, in order to In order to get diff output out of a script, shell or command task, I need to:

* pass in ansible_diff_mode to indicate whether diff output should be produced (optional)
* (produce the diff output in the script/shell/command - this is expected)
* register the result of the task
* use a separate task to print out the result

The requested feature would allow removal of the last two steps; instead, it would be a keyword like `changed_diff: result.stdout` or `changed_diff: "{{ result.stdout }}"`

This would be analogous to the existing `failed_when` and `changed_when` keywords

### Issue Type

Feature Idea

### Component Name

ansible

### Additional Information

Example use:

```yaml
- name: Example 1
  command: /usr/local/bin/example1
  register: result
  changed_when: true
  changed_diff: result.stdout

- name: Example 2
  command: /usr/local/bin/example2
  register: result
  vars:
    decoded_result: "{{ result.stdout | from_json }}"
  changed_when: decoded_result.changes | length > 0"
  changed_diff: decoded_result.changes | join(', ')"
  failed_when: decoded_result.error
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
