### ISSUE TITLE
copy with content and diff enabled prints wrong file modified

### ISSUE THREAD

**Issue by bluikko** [ansible/ansible#79749]
### Summary

When using the `copy` module together with `content` arg, wrong file name is printed when `ansible-playbook` is run with `--diff` switch. The file listed as modified is the temporary file in `/tmp` and not the real file name.

The `+++ after` in diff results output lists a temporary file.

### Issue Type

Bug Report

### Component Name

copy

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible-venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible-venv/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/home/ansible-venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
irrelevant
```

### OS / Environment

EL9

### Steps to Reproduce

```yaml (paste below)
---
- name: Test copy with content
  hosts:
    - all
  gather_facts: false
  tasks:
    - name: Copy with content shows wrong file modified
      ansible.builtin.copy:
        dest: /tmp/test
        content: aaa
```

### Expected Results

The file name passed to `copy` in arg `dest` should be listed in the diff line and not a temporary file.

### Actual Results

```console
TASK [Copy with content shows wrong file modified] *************************************************************************************************************
--- before
+++ after: /tmp/.ansible.ansible/ansible-local-332829qqzxldi3/tmpz_qauy37
@@ -0,0 +1 @@
+aaa
\ No newline at end of file
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
