### ISSUE TITLE
ulimit change do not take effect when connection=local

### ISSUE THREAD

**Issue by njha8x8** [ansible/ansible#79745]
### Summary

Hi All,

I am running ansible inside a shell script which is run by user root

  
```
#!/bin/sh
ansible-playbook -i ./playbooks/hosts ./playbooks/test.yml
```

The test.yml looks like
```
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "===== Include Test role ====="
      include_role:
        name: testrole
```

 The test role looks like:
```
 - name: change ulimit
   pam_limits:
    domain: "{{ item.user }}"
    limit_type: '-'
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - { user: 'root', item: 'core', value: 'unlimited'}
    - { user: 'root', item: 'nofile', value: '250000'}
 
 - name: Start the app
    become: yes
    shell:
      cmd: nohup /apps/testapp/bin/start.sh ../config/testapp.cfg 
    args:
      chdir: /apps/testapp/bin/  
```
The issue is the application fails to start because it still thinks the ulimit is set to default value which is 1024 and 78582
Now based on my understanding, ansible is doing a local connection means it is not running over ssh and it is using the same root session from which the shell script was triggered and it cannot find the updated values for root
Now once I exit out of the root session and reenter and run the same script, the app starts fine

Any suggestions on how to reload ulimit when connection = local is set, I know there is a way when we do over ssh we can just reset the ssh connection but in this scenario it is local and we need this as this is part of infrastructure provisioning followed by application deployment

Thankyou

### Issue Type

Bug Report

### Component Name

pam_limits.so

### Ansible Version

```console
$ ansible --version

 ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.12] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]
  jinja version = 3.0.3
  libyaml = True
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ansible-config dump --only-changed 
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

### OS / Environment

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### Steps to Reproduce

```yaml (paste below)


```

### Expected Results

I expect ansible to reload ulimit for root in case we change ulimit in the same session when connection=local is set

### Actual Results

```console
The ulimit did not change for root user when connection=local is set
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
