### ISSUE TITLE
omit in delegate_to doesnt works in blocks

### ISSUE THREAD

**Issue by BachenbergS** [ansible/ansible#79752]
### Summary

We have an include_task, that needs to be delegate to another host sometimes:

`delegate_to: "{{ host_to_delegate_to | default(omit) }}"`

After the update to Ansible 2.14.1 we got problems with that.

I have written 3 easy tests to reproduce the Problem: 
- Test 1 uses delegate_to: omit and works fine.
- Test 2 uses delegate_to: "" in a block and works fine.
- Test 3 uses delegate_to: omit in a block an doesn't work.

Why does delegate_to: Omit not work in Blocks ?!

### Issue Type

Bug Report

### Component Name

block, delegate_to

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
  config file = /home/simon/Code/ansible/ansible.cfg
  configured module search path = ['/home/simon/Code/ansible/plugins/library']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/simon/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Fedora 37

### Steps to Reproduce

```yaml (paste below)
- name: Test
  hosts: localhost
  tasks:
  - name: Test 1
    ansible.builtin.ping:
      data: "Pong"
    delegate_to: "{{ omit }}"

  - name: Test 2
    delegate_to: ""
    block:
      - name: Ping
        ansible.builtin.ping:
          data: "Pong"

  - name: Test 3
    delegate_to: "{{ omit }}"
    block:
      - name: Ping
        ansible.builtin.ping:
          data: "Pong"

```

### Expected Results

I expect that everything runs fine, without errors.

### Actual Results

```console
PLAY [Test] *********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
Dienstag 17 Januar 2023  11:24:21 +0100 (0:00:00.060)       0:00:00.060 ******* 
ok: [localhost]

TASK [Test 1] *******************************************************************************************************************************
Dienstag 17 Januar 2023  11:24:22 +0100 (0:00:00.829)       0:00:00.889 ******* 
ok: [localhost]

TASK [Ping] *********************************************************************************************************************************
Dienstag 17 Januar 2023  11:24:22 +0100 (0:00:00.229)       0:00:01.119 ******* 
ok: [localhost]

TASK [Ping] *********************************************************************************************************************************
Dienstag 17 Januar 2023  11:24:22 +0100 (0:00:00.164)       0:00:01.284 ******* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: '{{ omit }}'
fatal: [localhost -> {{ omit }}]: FAILED! => 
  msg: 'Unexpected failure during module execution: ''{{ omit }}'''
  stdout: ''

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
