### ISSUE TITLE
assemble + copy as single module/task

### ISSUE THREAD

**Issue by phemmer** [ansible/ansible#79761]
### Summary

One of the core design issues with the assemble module is that it splits fragment installation (e.g. `copy` or `template`) and assembly into separate tasks. This creates problems as it may not be possible to validate the individual fragment by itself. This means you have to perform the validation in the `assemble` task. However if validation fails, you've now got this installed fragment that's already on the remote system as that task succeeded. In addition if you want to run ansible in check mode, you can't do validation at all.

The solution is to provide a task which merges these two operations together. I would recommend a module which operates like `copy`, as this module can take both a file, as well as a template via `content: '{{ lookup("template", ...}}'`.  

I think this functionality would be best as a new `assemble_fragment` module. I don't think including this functionality into the existing module (via new parameters) would be a good idea, as the existing parameter names (`src` and `dest`) would be confusing: Is `src` the fragment or the destination directory? And is `dest` the directory, or the fragment?. Yes documentation would make it clear, but it would lead to mistakes and frustration.

### Issue Type

Feature Idea

### Component Name

assemble

## Examples

```yaml
- assemble_fragment:
    src: file.txt
    dest: /etc/myapp/conf.d/file.txt
    assemble: /etc/myapp/myapp.conf
    validate: myapp --config %s --check
```
^ Where the module would pick up the directory from the `dest` argument, concatenate all the fragments, and then validate. During validation the specified fragment would substitute an existing fragment of the same name if there is one. If validation passes, the fragment is installed, and the output file written.

```yaml
- assemble_fragment:
    content: '{{ lookup("template","file.txt.j2") }}'
    dest: /etc/myapp/conf.d/file.txt
    assemble: /etc/myapp/myapp.conf
    validate: myapp --config %s --check
```
^ An example which takes input from a template instead of a file copy. Basically the same functionality as the `copy` module.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
