### ISSUE TITLE
win_shortcut: Unexpected behaviour when referring to non-existing env-variable

### ISSUE THREAD

**Issue by wfmw445** [ansible/ansible#79786]
### Summary

Since deploying to Win11: When I add a src  path with an env-variable which doesn't pre-exist (but will be existing later on the target) it creates a wrong target in the shortcut

### Issue Type

Bug Report

### Component Name

win_shortcut

### Ansible Version

```console
v 2.12.9
```

### Configuration

```console
CALLBACKS_ENABLED(/etc/ansible/ansible.cfg) = ['profile_tasks']
COLOR_VERBOSE(/etc/ansible/ansible.cfg) = bright green
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 40
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

packer:
______
control_path(/etc/ansible/ansible.cfg) = /tmp/ansible-%%h-%%p-%%r
host_key_checking(/etc/ansible/ansible.cfg) = False
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1200s -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o BatchMode=yes

paramiko_ssh:
____________
host_key_checking(/etc/ansible/ansible.cfg) = False

ssh:
___
control_path(/etc/ansible/ansible.cfg) = /tmp/ansible-%%h-%%p-%%r
host_key_checking(/etc/ansible/ansible.cfg) = False
ssh_args(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=1200s -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -o BatchMode=yes

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

Win11

### Steps to Reproduce

```yaml (paste below)
- name: Create a shortcut for the Test
  community.windows.win_shortcut:
    description: Test
    src: '%APP_PATH%\Bin\Edit.exe'
    dest: '%Public%\Desktop\Test.lnk'
    arguments: '"%ALLUSERSPROFILE%\AutoTest\Test\AutoTest.lst"'
    directory: '%ALLUSERSPROFILE%\AutoTest\Test'

```

### Expected Results

A shortcut with the following target property:

`Target: %APP_PATH%\Bin\Edit.exe  "C:\ProgramData\AutoTest\Test\AutoTest.lst`

### Actual Results

```console
Target: C:\%APP_PATH%\Bin\Edit.exe  "C:\ProgramData\AutoTest\Test\AutoTest.lst

Somehow 'c:\' inserted before env-variable
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
