### ISSUE TITLE
core module user on alpine linux

### ISSUE THREAD

**Issue by mterzo** [ansible/ansible#79791]
### Summary

Alpine can have the pkg shadow installed, which provides extended user management just like all the other Distros, mainly 2^32 UIDs.   This was altered in PR #45507 until busy box was added this would have worked by requiring pkg shadow to be installed.

Should be a fairly easy change in the Alpine class to override function create_user to detect the presence of useradd (shadow) vs adduser (busybox), based on which tool is available call the extended user create function or the busybox minimal version.  

### Issue Type

Bug Report

### Component Name

ansible.builtin.user

### Ansible Version

```console
$ ansible --version


ansible [core 2.13.3]
 config file = /scratch/ansible.cfg
 configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
 ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
 ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
 executable location = /usr/local/bin/ansible
 python version = 3.9.10 (main, Feb 24 2022, 00:03:02) [GCC 10.3.1 20211027]
 jinja version = 3.0.1
 libyaml = False
```
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all


/scratch # ansible-config dump --only-changed -t all
ANY_ERRORS_FATAL(/scratch/ansible.cfg) = True
CALLBACKS_ENABLED(/scratch/ansible.cfg) = ['profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/scratch/ansible.cfg) = ['/app/ansible/plugins/filter', '/root/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter', '/scratch/ansible/plugins/filter']
DEFAULT_FORKS(/scratch/ansible.cfg) = 50
DEFAULT_HOST_LIST(/scratch/ansible.cfg) = [*** REDACTED ***]
DEFAULT_LOOKUP_PLUGIN_PATH(/scratch/ansible.cfg) = ['/app/ansible/plugins/lookup', '/root/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup', '/scratch/ansible/plugins/filter']
DEFAULT_PRIVATE_KEY_FILE(env: ANSIBLE_PRIVATE_KEY_FILE) = *** REDACTED ***
DEPRECATION_WARNINGS(/scratch/ansible.cfg) = False
HOST_KEY_CHECKING(/scratch/ansible.cfg) = False
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /usr/local/bin/python3
INVENTORY_ANY_UNPARSED_IS_FAILED(/scratch/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/scratch/ansible.cfg) = False

ssh:
___
host_key_checking(/scratch/ansible.cfg) = False
private_key_file(env: ANSIBLE_PRIVATE_KEY_FILE) = *** REDACTED ***
reconnection_retries(/scratch/ansible.cfg) = 5
```
```


### OS / Environment

Alpine 3.15.0

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml (paste below)

---
- name: test
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: create user
    ansible.builtin.user:
       name: broken
       uid: "1640965628"
       groups: "users"
```

### Expected Results

use created

### Actual Results

```console
adduser: number 1640965628 is not in 0..2156000 range
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
