### ISSUE TITLE
Ansible |replace failing

### ISSUE THREAD

**Issue by rafailsharifov** [ansible/ansible#79811]
### Summary

Hi friends.

I have imput:
gtm_monitor_type: "https"
gtm_monitor_recv: "OK"
gtm_monitor_send: "GET /keepalive HTTP/1.1\r\nHost: api.dev.example.com\r\n\r\n"

I need output : 
gtm_monitor_configuration: "send \"GET /keepalive HTTP/1.1\r\nHost: api.dev.example.com\r\n\r\n\" recv \"OK\""

My playbook is:
\\\\\\\\\\\\\\\\\\\\\\\\
- block:
  - set_fact:
      gtm_monitor_configuration: "send \"{{gtm_monitor_send | replace('\r','\\\r') | replace('\n','\\\n')}}\" recv \"{{gtm_monitor_recv | replace('\r','\\\r') | replace('\n','\\\n')}}\""
    when: gtm_monitor_type == 'http' or gtm_monitor_type == 'https'
 \\\\\\\\\\\\\\\\\\\\\\\\\

But I am receiving output like:
    "gtm_monitor_configuration": "send \"GET /keepalive HTTP/1.1\r\\rHost: api.dev.example.com\r\\r\r\\r\" recv \"OK\"" 

-How it could be happen (if you pay attention \r isn`t replaced, instead \n is replaced with \\r )?
-Do you have any other solution for keeping single backslashes in the string instead of replacing them with double backslashes?

### Issue Type

Bug Report

### Component Name

ansible

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

AWX

### Steps to Reproduce

```
- block:
  - set_fact:
      gtm_monitor_configuration: "send \"{{gtm_monitor_send | replace('\r','\\r') | replace('\n','\\n')}}\" recv \"{{gtm_monitor_recv | replace('\r','\\r') | replace('\n','\\n')}}\""
    when: gtm_monitor_type == 'http' or gtm_monitor_type == 'https'
```

### Expected Results

gtm_monitor_configuration: "send \"GET /keepalive HTTP/1.1\r\nHost: api.dev.example.com\r\n\r\n\" recv \"OK\""

### Actual Results

```console
"gtm_monitor_configuration": "send \"GET /keepalive HTTP/1.1\r\\rHost: api.dev.example.com\r\\r\r\\r\" recv \"OK\""
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
