### ISSUE TITLE
vars declared in a task that is pulled in via include_role don't appear to be templated

### ISSUE THREAD

**Issue by TheMysteriousX** [ansible/ansible#79842]
### Summary

When using _include_role_, task vars do not appear to be templated. Everything else in the below example is correctly templated. As you can see in the output at the bottom, `ansible_user` is not templated, and instead the raw string is passed through to `rsync`.

This also fails in the same way if `synchronize_user` is removed from the `ansible.builtin.include_role` task and placed in `roles/synchronize/defaults/main.yml`.

If I hard code the user it does work, but this limits the utility of the role as we'll need to create a role for every single user that needs to use `synchronize`. If I in-line the task instead of using `include_role` that makes it work too - but again in-lining the tasks means we're duplicating code again.

Including this role via a playbook is not possible - this is a minimal example (we're essentially wrapping the synchronize module to make it work without e.g. running as root, having accounts with NOPASSWD persistently enabled etc.).

Setting `public` does not change the behaviour.

The same issue is present when using `import_task` instead of include.

### Issue Type

Bug Report

### Component Name

lib/ansible/modules/include_role.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
  config file = /Users/adamb/Developer/ansible/ansible.cfg
  configured module search path = ['/Users/adamb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/Users/adamb/Developer/ansible/plugins/modules', '/Users/adamb/.ansible/collections/*/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/adamb/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.1 (main, Dec 23 2022, 09:39:26) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(./ansible.cfg) = True
CONFIG_FILE() = ./ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(./ansible.cfg) = ['/Users/adamb/.ansible/plugins/action', '/usr/share/ansible/plugins/action', './plugins/action']
DEFAULT_FILTER_PLUGIN_PATH(./ansible.cfg) = ['/Users/adamb/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter', './plugins/filter']
DEFAULT_FORKS(./ansible.cfg) = 9
DEFAULT_HOST_LIST(./ansible.cfg) = ['./inventory/hosts']
DEFAULT_JINJA2_NATIVE(./ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(./ansible.cfg) = True
DEFAULT_LOG_PATH(./ansible.cfg) = /Users/adamb/.ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(./ansible.cfg) = ['/Users/adamb/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup', './plugins/lookup']
DEFAULT_MANAGED_STR(./ansible.cfg) = Ansible managed: {{{{ lookup('git_info', template_fullpath | quote) }}}}
DEFAULT_MODULE_PATH(./ansible.cfg) = ['/Users/adamb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', './plugins/modules', '/Users/adamb/.ansible/collections/*/modules']
DEFAULT_MODULE_UTILS_PATH(./ansible.cfg) = ['/Users/adamb/.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils', '/Users/adamb/.ansible/collections/*/module_utils']
DEFAULT_ROLES_PATH(./ansible.cfg) = ['/Users/adamb/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', './roles', '/Users/adamb/.ansible/collections/*/roles']
DEFAULT_STDOUT_CALLBACK(./ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(./ansible.cfg) = ./contrib/vault/lastpass-client.py
HOST_KEY_CHECKING(./ansible.cfg) = False
INTERPRETER_PYTHON(./ansible.cfg) = python3
MAX_FILE_SIZE_FOR_DIFF(./ansible.cfg) = 208896
PLAYBOOK_DIR(./ansible.cfg) = ./playbooks:./jobs
USE_PERSISTENT_CONNECTIONS(./ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(./ansible.cfg) = False
ssh_args(./ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600 -o PreferredAuthentications=publickey
use_persistent_connections(./ansible.cfg) = True

ssh:
___
host_key_checking(./ansible.cfg) = False
pipelining(./ansible.cfg) = True
ssh_args(./ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600 -o PreferredAuthentications=publickey
```

### OS / Environment

Control Node: MacOS 13.1, Python3.11 (Homebrew)
Managed Node: RHEL 8.7, Python3.6

### Steps to Reproduce

```yaml
roles/lnms/tasks/main.yml
---

- name: Deploy plugins directory
  ansible.builtin.include_role:
    allow_duplicates: true
    name: synchronize
  vars:
    synchronize_dest: /opt/librenms/html/plugins/
    synchronize_group: false
    synchronize_mode: push
    synchronize_owner: false
    synchronize_perms: false
    synchronize_src: plugins/
    synchronize_user: filesyncher
```

```yaml
roles/synchronize/tasks/main.yml
---

    - name: Deploy {{ synchronize_dest }}
      ansible.builtin.synchronize:
        archive: "{{ synchronize_archive | default(omit) }}"
        checksum: "{{ synchronize_checksum | default(omit) }}"
        compress: "{{ synchronize_compress | default(omit) }}"
        copy_links: "{{ synchronize_copy_links | default(omit) }}"
        delay_updates: "{{ synchronize_delay_updates | default(omit) }}"
        delete: "{{ synchronize_delete | default(omit) }}"
        dest: "{{ synchronize_dest | default(omit) }}"
        dest_port: "{{ synchronize_dest_port | default(omit) }}"
        dirs: "{{ synchronize_dirs | default(omit) }}"
        existing_only: "{{ synchronize_existing_only | default(omit) }}"
        group: "{{ synchronize_group | default(omit) }}"
        link_dest: "{{ synchronize_link_dest | default(omit) }}"
        links: "{{ synchronize_links | default(omit) }}"
        mode: "{{ synchronize_mode | default(omit) }}"
        owner: "{{ synchronize_owner | default(omit) }}"
        partial: "{{ synchronize_partial | default(omit) }}"
        perms: "{{ synchronize_perms | default(omit) }}"
        private_key: "{{ synchronize_private_key | default(omit) }}"
        recursive: "{{ synchronize_recursive | default(omit) }}"
        rsync_opts: "{{ synchronize_rsync_opts | default(omit) }}"
        rsync_path: "{{ synchronize_rsync_path | default(omit) }}"
        rsync_timeout: "{{ synchronize_rsync_timeout | default(omit) }}"
        set_remote_user: "{{ synchronize_set_remote_user | default(omit) }}"
        src: "{{ synchronize_src | default(omit) }}"
        ssh_connection_multiplexing: "{{ synchronize_ssh_connection_multiplexing | default(omit) }}"
        times: "{{ synchronize_times | default(omit) }}"
        use_ssh_args: "{{ synchronize_use_ssh_args | default(omit) }}"
        verify_host: "{{ synchronize_verify_host | default(omit) }}"
      become: true
      vars:
        ansible_user: "{{ synchronize_user }}"
```

### Expected Results

Task vars (and defaults, and role vars) should always be templated.

### Actual Results

```console
TASK [Gather facts] *****************************************************************************************************************************
ok: [host1]
ok: [host2]

TASK [Deploy plugins directory] *****************************************************************************************************************************

TASK [synchronize : Deploy /opt/librenms/html/plugins/] *****************************************************************************************************************************
({{ synchronize_user }}@host1) Password:
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
