### ISSUE TITLE
gcp_compute_instance_facts problem with the "~" operator

### ISSUE THREAD

**Issue by barbacbd** [ansible/ansible#79849]
### Summary

When I try to use the "contains" operator or "~" the playbook will fail with something similar to:

```
"Invalid value for field 'filter': 'name ~ whatever-I-name-it
```

When I run the (assumed) same/similar command with gcloud it will work, 

```
gcloud compute instances list --filter="name~whatever-I-name-it"
```

The [ansible docs](https://docs.ansible.com/ansible/latest/collections/google/cloud/gcp_compute_instance_info_module.html) state that the gcp filters will work followed by that [link](https://cloud.google.com/sdk/gcloud/reference/topic/filters). 

I noticed an older issue https://github.com/ansible/ansible/issues/48824 from a couple of years ago where it was determined that only '=', '<', and '>' were able to be used. Has there been any support to add other operators, if not could the docs be changed to reflect? 

### Issue Type

Bug Report

### Component Name

pip

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
None
```

### OS / Environment

RHEL-8

### Steps to Reproduce

```yaml
- name: Retrieve platform instance list
  google.cloud.gcp_compute_instance_info:
    auth_kind: "serviceaccount"
    filters:
    - "name ~ {{ gcp_instance_pattern }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    service_account_file: "{{ gcp_service_account_file }}"
  register: gcp_machines
  run_once: true
```
Where the `gcp_instance_pattern` is a string containing the majority of an openshift worker node (full name is not known). 

### Expected Results

- multiple items to be returned as they are with the `gcloud compute instances list --filter="name~whatever-I-name-it"`

### Actual Results

```console
"Invalid value for field 'filter': 'name ~ whatever-I-name-it ...
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
