### ISSUE TITLE
FR: no_changed_when conditional statement

### ISSUE THREAD

**Issue by Subbeh** [ansible/ansible#79855]
### Summary

In some cases, I would like to be able to tell Ansible to not change the state to changed if certain conditions are met while assuming normal operations if those conditions are not met.

For example, if I set the variable `no_change: true` and have the following `changed_when` statement: 

```
changed_when: no_change is undefined
```

Then if `no_change` is not defined, the task will always be in a changed state.

If `no_change` is undefined, I would like the task to run as if the `changed_when` statement is not there.

The way I see it, I would have to explicitly specify a `no_changed_when` statement in order to get the desired functionality.

### Issue Type

Feature Idea

### Component Name

ansible

### Additional Information

```yaml (paste below)
--- # separate files with container information

postgres:
  image: postgres:12-alpine

redis:
  image: redis:alpine
  no_change: true # never change the state to changed

--- # container creation task

- name: Load all container manifests
  ansible.builtin.include_vars:
    dir: "{{ common_ansible_root }}/containers"
    name: containers

- name: Create container
  community.docker.docker_container:
    name: "{{ item }}"
    image: "{{ containers[item].image }}"
    ...
  changed_when: containers[item].no_change is undefined
  loop: "{{ containers }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This does not require a new feature. Registering the task result gives you access to the original result in your `changed_when` expression.

```yaml
- hosts: localhost
  tasks:
    - debug:
      register: result
      changed_when:
        - result is changed
        - not (no_change | default(false))

    - command: /bin/true
      register: result
      changed_when:
        - result is changed
        - not (no_change | default(false))
```

Running this playbook without `no_change` defined, the tasks show their normal changed status:

```
 $ ansible-playbook ~/test.yml

PLAY [localhost] *******************************************************************
TASK [debug] ***********************************************************************
ok: [localhost] =>
    msg: Hello world!

TASK [command] *********************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

But if we set it to true, they both show unchanged:
```
$ ansible-playbook ~/test.yml -e '{no_change: true}'

PLAY [localhost] *******************************************************************

TASK [debug] ***********************************************************************
ok: [localhost] =>
    msg: Hello world!

TASK [command] *********************************************************************
ok: [localhost]

PLAY RECAP *************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
