### ISSUE TITLE
Conditionnal bug report

### ISSUE THREAD

**Issue by Azilone** [ansible/ansible#79860]
### Summary

Hello, I am just trying to check a condition I would like a task to run only when the condition is met.

When I try to do a test as you can see below, my task runs when it should not.

This error appears only when I use the "or" operator

my playbook : 

```yaml
---

- name: debug module demo
  hosts: all


  tasks:
    - set_fact:
        ansible_become_method: "su"
      when: ansible_distribution_version == "9" or "10" or "11"


    - name: "task 1"
      debug: var=ansible_distribution_version
      when: ansible_distribution_version == "bbbb" or "aaa"
```

the result: 
```bash
PLAY [debug module demo] ***********************************************************************************************************************************
TASK [Gathering Facts] *************************************************************************************************************************************
ok: [sbvs-ansible-test]

TASK [set_fact] ********************************************************************************************************************************************
ok: [sbvs-ansible-test]

TASK [task 1] **********************************************************************************************************************************************
ok: [sbvs-ansible-test] => {
    "ansible_distribution_version": "11"
}

PLAY RECAP *************************************************************************************************************************************************
sbvs-ansible-test          : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
as you can see the task1 running while ansible_distribution_version is equal to "11" and not "bbbb" or "aaa"

my ansible version :
````bash
ansible [core 2.14.1]
  config file = /home/technicien/ansible/ansible.cfg
  configured module search path = ['/home/technicien/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/technicien/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/technicien/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/technicien/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Issue Type

Bug Report

### Component Name

when

### Ansible Version

```console
$ ansible --version

ansible [core 2.14.1]
  config file = /home/technicien/ansible/ansible.cfg
  configured module search path = ['/home/technicien/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/technicien/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/technicien/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/technicien/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```


### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

CONFIG_FILE() = /home/technicien/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/technicien/ansible/ansible.cfg) = ['/home/technicien/ansible/inventory.yml']
HOST_KEY_CHECKING(/home/technicien/ansible/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/home/technicien/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/home/technicien/ansible/ansible.cfg) = False
```


### OS / Environment

Node server : ubuntu 22.04
Host : Debian 11

### Steps to Reproduce

<!--- Paste example playbooks or commands between quotes below -->
```yaml (paste below)


- name: debug module demo
  hosts: all


  tasks:
    - set_fact:
        ansible_become_method: "su"
      when: ansible_distribution_version == "9" or "10" or "11"


    - name: "task 1"
      debug: var=ansible_distribution_version
      when: ansible_distribution_version == "bbbb" or "aaa"

### Expected Results

PLAY [debug module demo] ***********************************************************************************************************************************
TASK [Gathering Facts] *************************************************************************************************************************************
ok: [sbvs-ansible-test]

TASK [set_fact] ********************************************************************************************************************************************
ok: [sbvs-ansible-test]

TASK [task 1] **********************************************************************************************************************************************
skipped: [sbvs-ansible-test] => {
   SKIPPED
}

PLAY RECAP *************************************************************************************************************************************************
sbvs-ansible-test          : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

### Actual Results

```console
PLAY [debug module demo] ***********************************************************************************************************************************
TASK [Gathering Facts] *************************************************************************************************************************************
ok: [sbvs-ansible-test]

TASK [set_fact] ********************************************************************************************************************************************
ok: [sbvs-ansible-test]

TASK [task 1] **********************************************************************************************************************************************
ok: [sbvs-ansible-test] => {
    "ansible_distribution_version": "11"
}

PLAY RECAP *************************************************************************************************************************************************
sbvs-ansible-test          : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
