### ISSUE TITLE
Systemd user services cannot be enabled globally

### ISSUE THREAD

**Issue by tilman19** [ansible/ansible#79861]
### Summary

When trying to install a systemd service for all users (`scope: global`) I always get an error about not being able to connect to the bus:
`fatal: [***]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: Failed to connect to bus: Operation not permitted\n"}`

I read, that `XDG_RUNTIME_DIR` needs to be set and did so.
I tried using the become user (root), but also the user logged into to the system (see below).
The directory `/run/user/1001` exists but is only readable to the user.

When running `sudo systemctl --global enable my_user_service.service` everything works as expected.

```
- name: get my user id
  become: no
  command: id -u
  register: myuid

- name: "Enable systemd user service for all users"
  systemd:
    daemon_reload: yes
    name: my_user_service.service
    scope: global
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: /run/user/{{myuid.stdout}}
    #DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{myuid.stdout}}/bus
```

Tried with and without the `DBUS_SESSION_BUS_ADDRESS`, but no luck either.

This is probably related to #27631, but changing scope `user` instead of `global` will not fix this for me, as I want the service for all users logging into the interactive system.

System: 
* Ansible 2.14.1 running with Python 3.10.9
* Target: Kubuntu 20.04 with all current updates installed

### Issue Type

Bug Report

### Component Name

ansible.builtin.systemd_service

### Ansible Version

```console
ansible [core 2.14.1]
  config file = /home/***/***/ansible/ansible.cfg
  configured module search path = ['/home/***/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/***/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /home/***/***/ansible/ansible.cfg
DEFAULT_BECOME(/home/***/***/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/***/***/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/***/***/ansible/ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/***/***/.ansible-vault
INVENTORY_ENABLED(/home/***/***/ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'community.general.xen_orchestra']

BECOME:
======

runas:
_____
become_user(/home/***/***/ansible/ansible.cfg) = root

su:
__
become_user(/home/***/***/ansible/ansible.cfg) = root

sudo:
____
become_user(/home/***/***/ansible/ansible.cfg) = root
```

### OS / Environment

Executing environment: Arch Linux
Target: Kubuntu 20.04

### Steps to Reproduce

```
- name: get my user id
  become: no
  command: id -u
  register: myuid

- name: "Enable systemd user service for all users"
  systemd:
    daemon_reload: yes
    name: my_user_service.service
    scope: global
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: /run/user/{{myuid.stdout}}
    #DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{myuid.stdout}}/bus
```

### Expected Results

It should enable the service `my_user_service` for all users as systemd user service.

### Actual Results

```console
fatal: [PC-**]: FAILED! => {"changed": false, "msg": "failure 1 during daemon-reload: Failed to connect to bus: Operation not permitted\n"}
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/systemd_service.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/systemd_service.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
Duplicate of https://github.com/ansible/ansible/issues/72674

Fix in https://github.com/ansible/ansible/pull/75097

If you have further questions please stop by IRC or the mailing list:
* IRC: #ansible on irc.libera.chat
* mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by tilman19** [comment]
A quick fix, that solved the problem for me:

```
- name: "Reload service"
  systemd:
    daemon_reload: yes

- name: "Enable service for all users"
  systemd:
    name: my_user_service.service
    scope: global
    enabled: yes
```

Basically: Split the daemon reloading and enabling the service afterwards.
