### ISSUE TITLE
elasticache module complains about subnet/security groups

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#7986]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 14cf3c4d2a) last updated 2014/06/30 11:48:15 (GMT +200)
##### Environment:

Fedora Core 19
##### Summary:

Trying to create a Redis cluster in a Security Group (VPC) but the task fails. It only works if I comment out the line "security_group_ids..." but that does not have the expected effect.
##### Steps To Reproduce:

```

---
- name: ElastiCache Redis nodes
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: create the Sessions node
    local_action:
      module: elasticache
      cache_engine_version: 2.8.6
      cache_port: 6379
      cache_security_groups: default
      engine: redis
      name: sessions
      node_type: cache.t1.micro
      num_nodes: 1
      region: eu-west-1
      security_group_ids: allinone
      state: present
      wait: yes
      zone: eu-west-1a
```
##### Expected Results:

The node gets created successfully with the expected settings.
##### Actual Results:

```
PLAY [ElastiCache Redis nodes] ************************************************ 

TASK: [create the Sessions node] ********************************************** 
failed: [localhost] => {"failed": true}
msg: Use of cache security groups is not permitted along with cache subnet group and/or security group Ids .

FATAL: all hosts have already failed -- aborting
```

The task creates the node without placing it in a Cache Subnet Group and assigns it 
the "default" Security Group.

Aside from this problem, it would be great if the maintenance window would also be added as a parameter.

See attached screenshot:
![aws_ansible_elasticache](https://cloud.githubusercontent.com/assets/127131/3429212/1f84a6b6-0050-11e4-9e91-ed00029d43e3.png)
