### ISSUE TITLE
cisco.iosxr.iosxr_bgp_global module documentation

### ISSUE THREAD

**Issue by PcInfamy** [ansible/ansible#79869]
### Summary

I'm attempting to use the iosxr_bgp_global module, but a few values are not clear on how to define them in the documentation.

In this example:
```
- name: configure bgp
  cisco.iosxr.iosxr_bgp_global:
    config:
      as_number: "12345"
      vrfs:
        - vrf: "vrf1"
          rd:
            value: "1.1.1.1:1234"
          neighbors:
            - neighbor: "1.1.1.2"
              remote_as: "54321"
              bfd:
                fast_detect:
                  set: true
                minimum_interval: 200
                multiplier: 3
              description: "device"
```

I'm trying to set the RD to a specific value and `auto` is the only dict value suggested by the documentation. When trying `value` as my key, I get a key error. Likewise, there isn't anything in `bfd -> fast_detect` section as to just enable it without the unwanted `strict_mode` or otherwise.

[RD section](https://docs.ansible.com/ansible/latest/collections/cisco/iosxr/iosxr_bgp_global_module.html#parameter-config/vrfs/rd):
<html>
<body>

rd dictionary | route distinguisher.
-- | --
auto boolean | Automatic route distinguisher.Choices:falsetrue

</body>
</html>

[BFD section](https://docs.ansible.com/ansible/latest/collections/cisco/iosxr/iosxr_bgp_global_module.html#parameter-config/vrfs/neighbors/bfd):
 <html>
<body>

bfd dictionary | Configure BFD parameters.
-- | --
fast_detect dictionary | Enable Fast detection
disable boolean | Prevent bfd settings from being inherited from the parent.Choices:falsetrue
strict_mode boolean | Hold down neighbor session until BFD session is upChoices:falsetrue
minimum_interval integer | Specifies the BFD session’s minimum-interval value for the neighbor.
multiplier integer | Specifies the BFD session’s multiplier value for the neighbor.

</body>
</html>

And finally my desired config state (I tried using the parser function with not complete results):
```
router bgp 12345
 vrf vrf1
  rd 1.1.1.1:1234
  neighbor 1.1.1.2
   remote-as 54321
   description device
   bfd fast-detect
   bfd multiplier 3
   bfd minimum-interval 200
```

### Issue Type

Documentation Report

### Component Name

ansible-collections/cisco.iosxr/blob/main/docs/cisco.iosxr.iosxr_bgp_global_module.rst

### Ansible Version

```console
$ ansible --version
6.5.0
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 18.04.6

### Additional Information

N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
