### ISSUE TITLE
User - Set number of warning days before password expires

### ISSUE THREAD

**Issue by Normo** [ansible/ansible#79882]
### Summary

From my point of view, it would be helpful to be able to adjust the number of days on which warnings are given before a user's password expires. Currently, with the user module it is only possible to adjust the [minimum](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-password_expire_min) and [maximum](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-password_expire_max) number of days a user password is valid.

### Issue Type

Feature Idea

### Component Name

user

### Additional Information

```yaml
- name: Set number of warning days for password expiration
  ansible.builtin.user:
    name: jane157
    password_expire_warn: 30
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
