### ISSUE TITLE
apt deb file install doesn't support wildcard

### ISSUE THREAD

**Issue by Vinalti** [ansible/ansible#79903]
### Summary

When using the apt module : 
- The `name` parameter supports wildcards
- The `deb` parameter doesn't support wildcards

As there are many situations in which a wilcard may be useful when instaling `deb` files manually, I think it would be good to support this option.

https://github.com/ansible/ansible/blob/0cf9db6fc22bb3b8393506a6577b8ef379148b34/lib/ansible/modules/apt.py#L1406-L1416

### Example of implementation
```py
 if p['deb']: 
     if p['state'] != 'present': 
         module.fail_json(msg="deb only supports state=present") 
     if '://' in p['deb']: 
         p['deb'] = fetch_file(module, p['deb']) 
     for file in glob(p['deb']):
       install_deb(module, file, cache, 
                   install_recommends=install_recommends, 
                   allow_unauthenticated=allow_unauthenticated, 
                   allow_change_held_packages=allow_change_held_packages, 
                   allow_downgrade=allow_downgrade, 
                   force=force_yes, fail_on_autoremove=fail_on_autoremove, dpkg_options=p['dpkg_options']) 
```
We could potentially also exclude downloaded files from this wildcard by using :
```py
     files = []
     if '://' in p['deb']: 
         files = [ fetch_file(module, p['deb']) ]
     else:
         files = glob(p['deb'])
     for file in files:
       install_deb(module, file, cache,
       # ...
```

### Issue Type

Feature Idea

### Component Name

apt

### Additional Information
Example of configuration:
```yaml
- tasks:
  - name: Install DEBs
    apt:
      deb: "{{ deb_repo }}/{{item}}_*.deb"
      update_cache: no
      state: present
    loop:
      - mysoftwareA
      - mysoftwareB
      - mysoftwareC 
```
Example of files to match:
- `/deb_repository/mysoftwareA_0.2.3-1_amd64.deb`
- `/deb_repository/mysoftwareB_3.1.12-1_amd64.deb`
- `/deb_repository/mysoftwareC_1.0.5+48_amd64.deb`

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/apt.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/apt.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
We could change `deb` to accept a list and then a result of a `find` task could be used as an input.

**Comment by Vinalti** [comment]
Sure, that also seems to work. How would the yaml looks like then, could you give an example of config @mkrizek ?

**Comment by mkrizek** [comment]
I believe currently you could do something like:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - find:
        paths: /tmp
        patterns: file*.deb
      register: res

    - apt:
        deb: "{{ item }}"
      loop: "{{ res.files | map(attribute='path') }}"
```
But that would mean invoking `apt` for each package separately which could be slow.

If we changed the apt module so that `deb` accepts also a list, then we could do the following and `apt` would install all matched packages at once:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - find:
        paths: /tmp
        patterns: file*.deb
      register: res

    - apt:
        deb: "{{ res.files | map(attribute='path') }}"
```

**Comment by Vinalti** [comment]
I think that accepting a list for the `deb` should be a thing, that is not normal that `name` can take a list but not `deb`. So, I totally support that idea. 

However, as it would be good to support the same syntax for `name` and `deb`, I think we should allow wildcards inside as well.  That would be a lot less verbose on the config side, and that's not hard to implement in my opinion. (see example above)

Also this solution (with `find`) doesn't really work in my context where I have a list of a dozen of packages to install manually, I need to specify the package name but wildcard the version for each of them (and I can't group then like that with a find)
```yaml
- tasks:
  - name: Install DEBs
    apt:
      deb: "{{ deb_repo }}/{{item}}_*.deb"  # << Wildcard Here 
      update_cache: no
      state: present
    loop:
      - mysoftwareA
      - mysoftwareB
      - mysoftwareC 
      # - mysoftwareD  # < Should not be included
      # - mysoftwareE   # < Should not be included
```

If I take the example with find that would give something like that: 
```yaml
- tasks:
  - name: Install DEBs
    block:
    - find:
        paths: "{{ deb_repo }}"
        patterns: "{{item}}_*.deb"
      register: res

    - apt:
          deb: "{{ res.files | map(attribute='path') }}" 
          update_cache: no
          state: present
    loop:
      - mysoftwareA
      - mysoftwareB
      - mysoftwareC 
```
