### ISSUE TITLE
Client script AnsiballZ_command.py work endlessly.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [ansible/ansible#79948]
### Summary

Hello. I have a client on which the Ansible client program hangs or enters an infinite loop - `AnsiballZ_command.py`.

I tried to manually run the same script on the client machine, but I get the same hanging result:
`/usr/bin/python3 /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py`

If I get stop this script then I get the following stack trace:
```
/usr/bin/python3 /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py
^CTraceback (most recent call last):
  File "/home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py", line 107, in <module>
    _ansiballz_main()
  File "/home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.command', init_globals=dict(_module_fqn='ansible.modules.command', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ansible.legacy.command_payload_1b6zecbx/ansible_ansible.legacy.command_payload.zip/ansible/modules/command.py", line 352, in <module>
  File "/tmp/ansible_ansible.legacy.command_payload_1b6zecbx/ansible_ansible.legacy.command_payload.zip/ansible/modules/command.py", line 321, in main
  File "/tmp/ansible_ansible.legacy.command_payload_1b6zecbx/ansible_ansible.legacy.command_payload.zip/ansible/module_utils/basic.py", line 2053, in run_command
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector. Poll(timeout, max_ev)
```

### Issue Type

Bug Report

### Component Name

pip3 install ansible==7.2.0

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/var/jenkins_home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /var/jenkins_home/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
jenkins@11ad37f283ca:/$
```

### OS / Environment

**Server Ansible** - Docker image "Jenkins/jenkins:lts-jdk11"

**Client Anisible** - Ubuntu 22.04.1 LTS

 Python v3.10.6 is installed on the server and client.

### Steps to Reproduce

```yaml (paste below)

- hosts: "{{ deploy_hosts | default('infrastructure_servers') }}"
  gather_facts: False

  vars:
    data_folder: 'my_company-backup'
    rclone_conf_file: 'rclone.config'
    rclone_conf_file_item: sftp-management
    gitlab_backup_files: '/srv/gitlab/data/backups'
    jenkins_backup_files: '/srv/jenkins'
    jenkins_exclude: '/srv/jenkins/workspace'
    grafana_files: '/srv/grafana'
    sftp_storage_name: 'my_company-online-backups'
    sftp_folder_name: 'infra'

  tasks:
    - name: Check rclone installed
      shell: 'which rclone'
      register: rclone_found
      ignore_errors: True
    - name: Fail if there is no rclone
      fail:
        msg: 'There is no rclone installed. Please install it first.'
      when: rclone_found.rc != 0

    - name: Prepare clean data folder
      file:
        path: "{{ data_folder }}/"
        state: absent

    - name: Create data folder
      file:
        path: '{{ data_folder }}'
        state: directory
        mode: 0755

    - name: Copy rclone configuration file
      template:
        backup: yes
        src: './playbooks_files/{{ rclone_conf_file }}.j2'
        dest: '{{ data_folder }}/{{ rclone_conf_file }}'

    - name: Create GitLab backup
      shell: |
        rm {{gitlab_backup_files}}/*.tar
        docker exec -t my_companyonline_gitlab_1 gitlab-rake gitlab:backup:create
        docker exec -t my_companyonline_gitlab_1 chmod 0777 /var/opt/gitlab/backups
        docker exec -t my_companyonline_gitlab_1 find /var/opt/gitlab/backups -mindepth 1 -exec chmod 0777 {} \;

    - name: Copy backup to management by sftp
      shell: 'rclone --verbose --config {{ data_folder }}/{{ rclone_conf_file }} copy {{ gitlab_backup_files }} {{ rclone_conf_file_item }}:{{ sftp_storage_name }}/{{ sftp_folder_name }}/gitlab'
      register: rclone_output
    - debug: var=rclone_output.stderr_lines

    - name: Copy Jenkins to management by sftp
      shell: |
        tar --exclude={{ jenkins_exclude }} -cjf /tmp/jenkins-`date +%F_%T`.tar.bz2 {{ jenkins_backup_files }}
        rclone --verbose --config {{ data_folder }}/{{ rclone_conf_file }} copy /tmp/jenkins-*.tar.bz2 {{ rclone_conf_file_item }}:{{ sftp_storage_name }}/{{ sftp_folder_name }}/jenkins
        rm /tmp/jenkins-*.tar.bz2
      register: rclone_output
    - debug: var=rclone_output.stderr_lines

    - name: Copy grafana to management by sftp
      shell: |
        tar -cjf /tmp/grafana-`date +%F_%T`.tar.bz2 {{ grafana_files }}
        rclone --verbose --config {{ data_folder }}/{{ rclone_conf_file }} copy /tmp/grafana-*.tar.bz2 {{ rclone_conf_file_item }}:{{ sftp_storage_name }}/{{ sftp_folder_name }}/grafana
        rm /tmp/Grafana-*.tar.bz2

```

### Expected Results

Performing a playbook.

### Actual Results

```console
TASK [Create GitLab backup] ****************************************************
task path: /var/jenkins_home/workspace/ansible-as-backup-backup-infrastructure/playbooks/as_backup/backup-infrastructure.yml:42
<8.8.8.8> ESTABLISH SSH CONNECTION FOR USER: backup
<8.8.8.8> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<8.8.8.8> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=722)
<8.8.8.8> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/tmp/ssh17257963565480245068.key")
<8.8.8.8> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<8.8.8.8> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="backup")
<8.8.8.8> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<8.8.8.8> SSH: Set ssh_common_args: ()
<8.8.8.8> SSH: Set ssh_extra_args: ()
<8.8.8.8> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee")
<8.8.8.8> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=722 -o 'IdentityFile="/tmp/ssh17257963565480245068.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="backup"' -o ConnectTimeout=10 -o 'ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee"' 8.8.8.8 '/bin/sh -c '"'"'echo ~backup && sleep 0'"'"''
<8.8.8.8> (0, b'/home/backup\n', b"OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022\r\ndebug1: Reading configuration data /var/jenkins_home/.ssh/config\r\ndebug1: /var/jenkins_home/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 8.8.8.8 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/var/jenkins_home/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/var/jenkins_home/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 361\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<8.8.8.8> ESTABLISH SSH CONNECTION FOR USER: backup
<8.8.8.8> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<8.8.8.8> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=722)
<8.8.8.8> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/tmp/ssh17257963565480245068.key")
<8.8.8.8> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<8.8.8.8> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="backup")
<8.8.8.8> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<8.8.8.8> SSH: Set ssh_common_args: ()
<8.8.8.8> SSH: Set ssh_extra_args: ()
<8.8.8.8> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee")
<8.8.8.8> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=722 -o 'IdentityFile="/tmp/ssh17257963565480245068.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="backup"' -o ConnectTimeout=10 -o 'ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee"' 8.8.8.8 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/backup/.ansible/tmp `"&& mkdir "` echo /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168 `" && echo ansible-tmp-1675842858.1152213-1330-95068680691168="` echo /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168 `" ) && sleep 0'"'"''
<8.8.8.8> (0, b'ansible-tmp-1675842858.1152213-1330-95068680691168=/home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168\n', b"OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022\r\ndebug1: Reading configuration data /var/jenkins_home/.ssh/config\r\ndebug1: /var/jenkins_home/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 8.8.8.8 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/var/jenkins_home/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/var/jenkins_home/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 361\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
Using module file /usr/local/lib/python3.9/dist-packages/ansible/modules/command.py
<8.8.8.8> PUT /var/jenkins_home/.ansible/tmp/ansible-local-1277udkiw1h5/tmpxok7crx_ TO /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py
<8.8.8.8> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<8.8.8.8> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=722)
<8.8.8.8> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/tmp/ssh17257963565480245068.key")
<8.8.8.8> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<8.8.8.8> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="backup")
<8.8.8.8> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<8.8.8.8> SSH: Set ssh_common_args: ()
<8.8.8.8> SSH: Set sftp_extra_args: ()
<8.8.8.8> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee")
<8.8.8.8> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=722 -o 'IdentityFile="/tmp/ssh17257963565480245068.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="backup"' -o ConnectTimeout=10 -o 'ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee"' '[8.8.8.8]'
<8.8.8.8> (0, b'sftp> put /var/jenkins_home/.ansible/tmp/ansible-local-1277udkiw1h5/tmpxok7crx_ /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py\n', b'OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022\r\ndebug1: Reading configuration data /var/jenkins_home/.ssh/config\r\ndebug1: /var/jenkins_home/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 8.8.8.8 is address\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts\' -> \'/var/jenkins_home/.ssh/known_hosts\'\r\ndebug3: expanded UserKnownHostsFile \'~/.ssh/known_hosts2\' -> \'/var/jenkins_home/.ssh/known_hosts2\'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 361\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug2: Server supports extension "lsetstat@openssh.com" revision 1\r\ndebug2: Unrecognised server extension "limits@openssh.com"\r\ndebug2: Unrecognised server extension "expand-path@openssh.com"\r\ndebug3: Sent message fd 3 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/backup size 0\r\ndebug3: Looking up /var/jenkins_home/.ansible/tmp/ansible-local-1277udkiw1h5/tmpxok7crx_\r\ndebug3: Sent message fd 3 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:8 O:131072 S:1460\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 32768 bytes at 65536\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 7 32768 bytes at 98304\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 8 1460 bytes at 131072\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<8.8.8.8> ESTABLISH SSH CONNECTION FOR USER: backup
<8.8.8.8> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<8.8.8.8> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=722)
<8.8.8.8> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/tmp/ssh17257963565480245068.key")
<8.8.8.8> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<8.8.8.8> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="backup")
<8.8.8.8> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<8.8.8.8> SSH: Set ssh_common_args: ()
<8.8.8.8> SSH: Set ssh_extra_args: ()
<8.8.8.8> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee")
<8.8.8.8> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=722 -o 'IdentityFile="/tmp/ssh17257963565480245068.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="backup"' -o ConnectTimeout=10 -o 'ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee"' 8.8.8.8 '/bin/sh -c '"'"'chmod u+x /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/ /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py && sleep 0'"'"''
<8.8.8.8> (0, b'', b"OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022\r\ndebug1: Reading configuration data /var/jenkins_home/.ssh/config\r\ndebug1: /var/jenkins_home/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug2: resolve_canonicalize: hostname 8.8.8.8 is address\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/var/jenkins_home/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/var/jenkins_home/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 361\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
<8.8.8.8> ESTABLISH SSH CONNECTION FOR USER: backup
<8.8.8.8> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<8.8.8.8> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=722)
<8.8.8.8> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/tmp/ssh17257963565480245068.key")
<8.8.8.8> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<8.8.8.8> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="backup")
<8.8.8.8> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<8.8.8.8> SSH: Set ssh_common_args: ()
<8.8.8.8> SSH: Set ssh_extra_args: ()
<8.8.8.8> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee")
<8.8.8.8> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=722 -o 'IdentityFile="/tmp/ssh17257963565480245068.key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="backup"' -o ConnectTimeout=10 -o 'ControlPath="/var/jenkins_home/.ansible/cp/63c992c9ee"' -tt 8.8.8.8 '/bin/sh -c '"'"'/usr/bin/python3 /home/backup/.ansible/tmp/ansible-tmp-1675842858.1152213-1330-95068680691168/AnsiballZ_command.py && sleep 0'"'"''
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
