### ISSUE TITLE
Select or skip tags for role include/import, not in CLI

### ISSUE THREAD

**Issue by raphaeljoie** [ansible/ansible#79950]
### Summary

I am using multiple community roles together in a playbook.
```yml
tasks:
- ansible.builtin.include_role:
  name: community-role-1
- ansible.builtin.include_role:
  name: community-role-2
```
And the execution of each role can be controlled by tags. Problem is that the only way I have to select or skip tags is to use the CLI
```
ansible-playbook --tags [role-1-tag,role-2-tag] my.playbook.yml
```
Which can be problematic
* if I *never* need to use a role without a given tag => CLI is heavier than needed
* and worse: if multiple roles uses the same tag(s) => conflict => must have separated playbooks

What about a way to select and skip tags when including/importing roles? from within the playbook and/or the task to import/include the roles

### Issue Type

Feature Idea

### Component Name

tags

### Additional Information

```yml
tasks:
- ansible.builtin.include_role:
    name: community-role-1
    select_tags: [role-1-tag]
- ansible.builtin.import_role:
    name: community-role-2
    skip_tags: [role-2-tag]
roles:
  - role: community-role-3
    select_tags: [role-3-tag]
```

Instead of a complex CLI call, or even worse, three playbooks. One per role

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/integration/targets/tags/aliases`](https://github.com/ansible/ansible/blob/devel/test/integration/targets/tags/aliases)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by raphaeljoie** [comment]
For the records, I tried
```yaml
tasks:
- ansible.builtin.set_fact:
    ansible_run_tags: ['role-1-tag']
- ansible.builtin.include_role:
    name: community-role-1
```
but it obviously doesn't work as
> These variables cannot be set directly by the user; Ansible will always override them to reflect internal state.
> -- https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
