### ISSUE TITLE
Can't pass variables to command module's argv parameter

### ISSUE THREAD

**Issue by tariver** [ansible/ansible#79967]
### Summary

Can't pass variable to command module

### Issue Type

Bug Report

### Component Name

command

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.8.2 (default, Apr  5 2022, 12:54:52) [GCC 8.3.1 20191121 (Red Hat 8.3.1-6)]
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

No output
```

### OS / Environment

CentOS

### Steps to Reproduce

I'm trying to write an Ansible role that configures [Redis cluster](https://redis.io/docs/management/scaling/).
The shell command that creates the cluster is:
```shell
$ /usr/bin/redis-cli --user admin --pass mypass --cluster create 10.226.2.194:6379 10.226.2.196:6379 10.226.2.195:6379 --cluster-replicas 1 --cluster-yes
```

I pass username, password, IP addresses of Redis servers and number of replicas as extra-vars in shell script:
```bash
#!/bin/sh
ansible-playbook /etc/ansible/playbook-redis.yml -vv \
--extra-vars='redis_admin_user=admin redis_admin_password=mypass' \
--extra-vars='redis_cluster_members="10.226.2.194:6379 10.226.2.196:6379 10.226.2.195:6379" redis_cluster_replicas=1'
```

I wrote the following task:
```yaml
    - name: Create Redis cluster
      ansible.builtin.command:
        argv:
          - /usr/bin/redis-cli
          - "--user {{ redis_admin_user }}"
          - "--pass {{ redis_admin_password }}"
          - "--cluster create {{ redis_cluster_members }}"
          - "--cluster-replicas {{ redis_cluster_replicas }}"
          - --cluster-yes
```

But when I run it I get the following error - `"Unrecognized option or bad number of args for: '--user admin'"` which seems to be error returned by redis-cli

I was able to get around the username and password by changing the task as following:
```yaml
    - name: Create Redis cluster
      ansible.builtin.command:
        argv:
          - /usr/bin/redis-cli
          - --user 
          - "{{ redis_admin_user }}"
          - --pass
          - "{{ redis_admin_password }}"
          - --cluster create
          - "{{ redis_cluster_members }}"
          - --cluster-replicas
          - "{{ redis_cluster_replicas }}"
          - --cluster-yes
```

But now it can't get past the `--cluster create` argument, it returns error `"Unrecognized option or bad number of args for: '--cluster create'"`

### Expected Results

To properly pass variables and to work the same way as the following:
```yaml
    - name: Create Redis cluster
      ansible.builtin.command:
        cmd: "/usr/bin/redis-cli --user {{ redis_admin_user }} --pass {{ redis_admin_password }} --cluster create {{ redis_cluster_members }} --cluster-replicas {{ redis_cluster_replicas }} --cluster-yes"
```

### Actual Results

```console
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["/usr/bin/redis-cli", "--user", "admin", "--pass", "mypass", "--cluster create", "10.226.2.194:6379 10.226.2.196:6379 10.226.2.195:6379", "--cluster-replicas", "0", "--cluster-yes"], "delta": "0:00:00.007513", "end": "2023-02-10 13:51:41.051679", "msg": "non-zero return code", "rc": 1, "start": "2023-02-10 13:51:41.044166", "stderr": "Unrecognized option or bad number of args for: '--cluster create'", "stderr_lines": ["Unrecognized option or bad number of args for: '--cluster create'"], "stdout": "", "stdout_lines": []}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
This is not a bug. Using `argv` allows you to specify exactly the list of arguments that should be used instead of having Ansible split the command up for you. However, this means that *you* need to correctly split the arguments, which you have not done. Each replica needs to be a separate argument but you're passing them as a single argument.

```yaml
    - name: Create Redis cluster
      ansible.builtin.command:
        argv: "{{ redis_argv | flatten }}"
      vars:
        redis_argv:
          - /usr/bin/redis-cli
          - --user 
          - "{{ redis_admin_user }}"
          - --pass
          - "{{ redis_admin_password }}"
          - --cluster create
          - "{{ redis_cluster_members }}"
          - --cluster-replicas
          - "{{ redis_cluster_replicas | split }}"
          - --cluster-yes
```

If you want to use variables and have them automatically parsed into arguments in a shell-like manner use `cmd`, not `argv`.

**Comment by tariver** [comment]
@flowerysong, thanks a lot, this worked but with one change - `--cluster create` had to be split into two lines:
```yaml
    - name: Create Redis cluster
      ansible.builtin.command:
        argv: "{{ redis_argv | flatten }}"
      vars:
        redis_argv:
          - /usr/bin/redis-cli
          - --user
          - "{{ redis_admin_user }}"
          - --pass
          - "{{ redis_admin_password }}"
          - --cluster
          - create
          - "{{ redis_cluster_members | split }}"
          - --cluster-replicas
          - "{{ redis_cluster_replicas }}"
          - --cluster-yes
```

What confused me is this part of the [module documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html#examples) that stated that you can use whitespace in arguments
```yaml
# argv (list) arguments, each argument on a separate line, 'args' keyword not necessary
# 'argv' is a parameter, indented one level from the module
- name: Use 'argv' to send a command as a list - leave 'command' empty
  ansible.builtin.command:
    argv:
      - /usr/bin/make_database.sh
      - Username with whitespace
      - dbname with whitespace
    creates: /path/to/database
```

I suppose that it's up to the binary (in this case redis-cli) to decide what is an argument.
