### ISSUE TITLE
`ansible.builtin.uri` does not return `json` attribute when `Content-Type: text/plain`

### ISSUE THREAD

**Issue by Sebbo94BY** [ansible/ansible#79970]
### Summary

When I interact with a web service using `ansible.builtin.uri`, which returns plaintext JSON (`Content-Type: text/plain`), the module does not add any `json` attribute, although it's expected. In an older version, this was supported.

The AWS Instance Identity document for example returns plaintext JSON:

> The instance identity document is exposed (in plaintext JSON format) through the Instance Metadata Service. - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html

This behaviour seems to have been changed somewhen between our current old version and the latest one: https://github.com/ansible/ansible/compare/v2.11.12..v2.14.2

I haven't fully checked the diff, but the main reason for this behaviour seems to be the missing `text` here:

```python
# v2.11.12
- JSON_CANDIDATES = ('text', 'json', 'javascript')
# v2.14.2
+ JSON_CANDIDATES = {'json', 'javascript'}
```

### Issue Type

Bug Report

### Component Name

ansible.builtin.uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = /home/skraetzig/Git/infrastructure/ansible.cfg
  configured module search path = ['/home/skraetzig/Git/infrastructure/ansible/library']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /usr/share/ansible/third-party/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_NOCOWS(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
ANY_ERRORS_FATAL(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
COLLECTIONS_PATHS(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/usr/shar>
CONFIG_FILE() = /home/skraetzig/Git/infrastructure/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['>
DEFAULT_FORKS(/home/skraetzig/Git/infrastructure/ansible.cfg) = 50
DEFAULT_LOCAL_TMP(env: ANSIBLE_LOCAL_TEMP) = /tmp/ansible-local-1pnubnjou
DEFAULT_MODULE_PATH(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/home/s>
DEFAULT_REMOTE_USER(/home/skraetzig/Git/infrastructure/ansible.cfg) = deploy
DEFAULT_ROLES_PATH(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/home/sk>
DIFF_ALWAYS(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = True
INTERPRETER_PYTHON(/home/skraetzig/Git/infrastructure/ansible.cfg) = /usr/bin/p>
MAX_FILE_SIZE_FOR_DIFF(/home/skraetzig/Git/infrastructure/ansible.cfg) = 1044480
RETRY_FILES_ENABLED(/home/skraetzig/Git/infrastructure/ansible.cfg) = False

CALLBACK:
========

default:
_______
display_ok_hosts(env: ANSIBLE_DISPLAY_OK_HOSTS) = True
display_skipped_hosts(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = True

CONNECTION:
==========

local:
_____
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True

paramiko_ssh:
____________
remote_user(/home/skraetzig/Git/infrastructure/ansible.cfg) = deploy
ssh_args(env: ANSIBLE_SSH_ARGS) = -C -o ControlMaster=auto -o ControlPersist=60>

psrp:
____
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True

ssh:
___
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
remote_user(/home/skraetzig/Git/infrastructure/ansible.cfg) = deploy
ssh_args(env: ANSIBLE_SSH_ARGS) = -C -o ControlMaster=auto -o ControlPersist=60>

winrm:
_____
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
```

### OS / Environment

Debian 11 (Bullseye)

### Steps to Reproduce

```yaml (paste below)
- hosts: an-aws-ec2-instance
  gather_facts: no
  tasks:
    - name: get instance identity
      ansible.builtin.uri:
        url: http://169.254.169.254/latest/dynamic/instance-identity/document
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: instance_result
      check_mode: no

    - ansible.builtin.debug:
        var: instance_result
```

### Expected Results

I expected, that the registered variable contains a `json` attribute besides the `content` attribute, but it's missing.

### Actual Results

```console
The `json` attribute from the `ansible.builtin.uri` module is missing:


TASK [ansible.builtin.debug] ***************************************************
ok: [an-aws-ec2-instance] => {
    "instance_result": {
        "accept_ranges": "none",
        "changed": false,
        "connection": "close",
        "content": "{\n  \"accountId\" : \"1234567890\",\n  \"architecture\" : \"x86_64\",\n  \"availabilityZone\" : \"eu-central-1a\",\n  \"billingProducts\" : null,\n  \"devpayProductCodes\" : null,\n  \"marketplaceProductCodes\" : null,\n  \"imageId\" : \"ami-026b9b6de9546bcab\",\n  \"instanceId\" : \"i-0d7fcd57df5239f67\",\n  \"instanceType\" : \"t3a.medium\",\n  \"kernelId\" : null,\n  \"pendingTime\" : \"2023-02-10T07:00:08Z\",\n  \"privateIp\" : \"10.158.241.119\",\n  \"ramdiskId\" : null,\n  \"region\" : \"eu-central-1\",\n  \"version\" : \"2017-09-30\"\n}",
        "content_length": "486",
        "content_type": "text/plain",
        "cookies": {},
        "cookies_string": "",
        "date": "Fri, 10 Feb 2023 15:50:51 GMT",
        "elapsed": 0,
        "failed": false,
        "last_modified": "Fri, 10 Feb 2023 15:31:41 GMT",
        "msg": "OK (486 bytes)",
        "redirected": false,
        "server": "EC2ws",
        "status": 200,
        "url": "http://169.254.169.254/latest/dynamic/instance-identity/document"
    }
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/uri.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/uri.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by axel3rd** [comment]
Same problem with `Content-Type` header which are "json like" but not exactly `application/json`:

Sample:
```
Content-Type: application/vnd.org.jfrog.artifactory.system.Version+json
```

**Workaround**: Depending the endpoint, enforcing `Accept` request header could work:

```
  - name: Get Json
    uri:
      url: https://some.url.org/api/endpoint
      headers:
        Accept: application/json
    register: api_result
```

**Comment by Sebi94nbg** [comment]
Thanks for your possible workaround, @axel3rd!

Unfortunately, this workaround does not work with, for example, the AWS Instance Identity endpoint mentioned above. :(

My current **workaround** looks like this:
```yaml
- name: get instance identity
  ansible.builtin.uri:
    url: http://169.254.169.254/latest/dynamic/instance-identity/document
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  register: instance_result
  check_mode: no

- amazon.aws.ec2_instance_info:
    instance_ids:
      - "{{ (instance_result.content | from_json).instanceId }}"
    region: "{{ (instance_result.content | from_json).region }}"
  register: ec2_instance_result
```
