### ISSUE TITLE
ansible.builtin.command module has errors in examples

### ISSUE THREAD

**Issue by travellingtechie** [ansible/ansible#79988]
### Summary

I don't think the syntax for the examples in ansible.builtin.command are correct.
Example shows:
```
# free-form (string) arguments, some arguments on separate lines with the 'args' keyword
# 'args' is a task keyword, passed at the same level as the module
- name: Run command if /path/to/database does not exist (with 'args' keyword)
  ansible.builtin.command: /usr/bin/make_database.sh db_user db_name
  args:
    creates: /path/to/database
```

When I tried that, I got an error:
```
"msg": "Unsupported parameters for (ansible.legacy.command) module: args. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."
```

worked fine just using creates:
```
# free-form (string) arguments, some arguments on separate lines with the 'args' keyword
# 'args' is a task keyword, passed at the same level as the module
- name: Run command if /path/to/database does not exist (with 'args' keyword)
  ansible.builtin.command: /usr/bin/make_database.sh db_user db_name
  creates: /path/to/database
```

### Issue Type

Documentation Report

### Component Name
lib/ansible/modules/command.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = /home/mike/.ansible.cfg
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mike/projects/Lab-Automation/ansible/venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mike/projects/Lab-Automation/ansible/collections
  executable location = /home/mike/projects/Lab-Automation/ansible/venv/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/home/mike/projects/Lab-Automation/ansible/venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
COLLECTIONS_PATHS(/home/mike/.ansible.cfg) = ['/home/mike/projects/Lab-Automation/ansible/collections']
CONFIG_FILE() = /home/mike/.ansible.cfg
DEFAULT_HOST_LIST(/home/mike/.ansible.cfg) = ['/home/mike/projects/HomelabInventory/Inventory']
DEFAULT_ROLES_PATH(/home/mike/.ansible.cfg) = ['/home/mike/projects/LabAutomation/ansible/roles']
RETRY_FILES_ENABLED(/home/mike/.ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/mike/.ansible.cfg) = /home/mike/"/tmp/"

CONNECTION:
==========

paramiko_ssh:
____________
ssh_args(/home/mike/.ansible.cfg) = -F /home/mike/projects/Lab-Automation/ansible/ssh_config

ssh:
___
ssh_args(/home/mike/.ansible.cfg) = -F /home/mike/projects/Lab-Automation/ansible/ssh_config
```

### OS / Environment

Ubuntu 22.04

### Additional Information

The examples as written don't work.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I can't reproduce the issue, it works for me:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - command: touch /tmp/file
      args:
        creates: /tmp/file

    - stat:
        name: /tmp/file
      register: res
      failed_when: not res.stat.exists
```

The error messages you provided:
```
"msg": "Unsupported parameters for (ansible.legacy.command) module: args. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."
```

suggests that the `args` parameter was not used as described in the documented example, specifically:

> 'args' is a task keyword, passed at the same level as the module

but I am only assuming since you have not provided the reproducer.

**Comment by brandonne** [comment]
Here is my original syntax:

```
- name: Echo admin password to local file
  ansible.builtin.command:
    cmd: echo -n " {{ admin_password }} " > /tmp/portainer_password
    args:
      creates: /tmp/portainer_password
```
(I realize there are other problems with using echo that way, and I have since switched to using builtin.shell.  but even when I change the command to touch 'tmp/portainer_password I get the same error.

Isn't "creates" also a task keyword, and should be at the same level as cmd.

Also I noticed yours looks different than either mine or the example in plugin.  I'm still trying to understand the intricacies of yaml, but you have:

```
...
tasks:
  - command: touch/tmp/file
    args:
      creates: /tmp/file
```
While mine and the example start out as:
```
-name: touch file
 ansible.builtin.command
   cmd: touch /tmp/file
   args:
     creates: /tmp/file
```
is it possible that is the difference?  The part that is confusing to me is that in example 3 "creates" is indented, but in example 4 it's the same level as cmd, does it work in both cases?
```
# free-form (string) arguments, some arguments on separate lines with the 'args' keyword
# 'args' is a task keyword, passed at the same level as the module
- name: Run command if /path/to/database does not exist (with 'args' keyword)
  ansible.builtin.command: /usr/bin/make_database.sh db_user db_name
  args:
    creates: /path/to/database

# 'cmd' is module parameter
- name: Run command if /path/to/database does not exist (with 'cmd' parameter)
  ansible.builtin.command:
    cmd: /usr/bin/make_database.sh db_user db_name
    creates: /path/to/database
```

Thanks.
