### ISSUE TITLE
'ansible.builtin.meta: refresh_inventory' no longer removes hosts added by host_add in ansible-core 2.14.x

### ISSUE THREAD

**Issue by hylaride** [ansible/ansible#79990]
### Summary

We used `ansible.builtin.meta: refresh_inventory` extensivly to remove hosts added by host_add.  I see in the changelog that was intentional.  What's the best way to remove hosts from within a playbook now?

### Issue Type

Bug Report

### Component Name

ansible.builtin.meta

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/chylarides/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/chylarides/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Ubuntu 22.04

### Steps to Reproduce

```yaml (paste below)
    - name: Refresh Inventory so upgrade_group gets reset for next include_playbook
      ansible.builtin.meta: refresh_inventory
```

Then hosts added via host_add have historically been removed, but now they don't

### Expected Results

Hosts/groups added by host_add get removed

### Actual Results

```console
The hosts remain and continue in subsequent plays, causing chaos.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
There isn't really an equivalent to what was achieved when `refresh_inventory` was errantly removing hosts.  But I do have a few ideas.  These ideas apply differently to the current play vs subsequent plays.

1. If you need to prevent these hosts from executing further in the current play, use `- meta: end_host`.  This does not affect subsequent plays
2. To prevent these hosts from executing on subsequent plays, add them to a group in the `add_host` task, such as a group called `add_host`, and then exclude them from the subsequent plays in the `hosts:` field, like `hosts: all:!add_host`:

    ```
    - hosts: localhost
      tasks:
        - add_host:
            name: foo
            groups: add_host

    - hosts: all:!add_host
      tasks:
        - debug: msg="I will not run on hosts in add_host group"
    ```

**Comment by hylaride** [comment]
Hi @sivel 
Thanks for the info.  Our issue is that we call the playbooks from a parent file where we pass in a different variable (an amazon availability zone in our case).  The idea is we update our nodes one AZ at a time.  Before `refresh_inventory` would clear them at the end of the play, but now they're remaining in the group as the sub-playbook is the same file with the same group name.  The result is when it's called a second time with a new AZ, it also does the ones in the previous AZ again.

I tried appending the group name with the az variable `{{ a_zone }}` like below, but that didn't even parse:

```
    - name: Create AS Upgrade Group
      local_action:
        module: ansible.builtin.add_host
        name: "{{ item }}"
        groups: "upgrade_group_{{ a_zone }}"
        instance_id: "{{ hostvars[item]['instance_id'] }}"
        ansible_ssh_host: "{{ hostvars[item]['ansible_ssh_host'] }}"
        wildfly_cluster_id: "{{ hostvars[item]['ansible_ssh_host'] }}[7600]"
      with_items:
        - "{{ as_by_az[a_zone] }}"

    - name: Remove Instances from Internal email ALB
      community.aws.elb_target:
        aws_access_key: "{{ aws_deployment_access_key }}"
        aws_secret_key: "{{ aws_deployment_secret_key }}"
        region: us-east-1
        target_group_name: scx-{{ scx_environment }}-email-as-alb-443
        target_port: 443
        state: absent
        target_id: "{{ hostvars[item]['instance_id'] }}"
      with_items: "{{ groups['upgrade_group_{{ a_zone }}'] }}"

    - name: Remove Instances from External email ALB


```
