### ISSUE TITLE
docker: image parameter does not support images from a local registry

### ISSUE THREAD

**Issue by ludovicc** [ansible/ansible#8000]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.5
##### Environment:

Ubuntu 14.04
Docker 1.0.1
##### Summary:

I'm trying to launch a Docker container from a playbook. The container name uses a URL pointing to a local registry.
##### Steps To Reproduce:

I'm using this command:

```
local_action:
  module: docker
  name: ks-archiver-store
  image: "internal_registry.localdomain:5000/store"
  ports: "29200:9200,29300:9300"
  volumes: "/var/logs/store:/data/store/logs"
```
##### Expected Results:

Container internal_registry.localdomain:5000/store should be up and running, with its ports and volumes mapped
##### Actual Results:

Ansible fails with this stack trace:

failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: SUDO-SUCCESS-ooibeoxgrrqtxfypdgvqnrzdftzyssvc
Traceback (most recent call last):
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 1971, in <module>
    main()
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 680, in main
    running_containers = manager.get_running_containers()
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 528, in get_running_containers
    for i in self.get_deployed_containers():
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 507, in get_deployed_containers
    running_image, running_tag = self.get_split_image_tag(i['Image'])
  File "/home/ludo/.ansible/tmp/ansible-tmp-1404209494.7-244300550568170/docker", line 457, in get_split_image_tag
    if '/' in image:
TypeError: argument of type 'int' is not iterable
