### ISSUE TITLE
yum_repository: updating gpgkey does not update repository config

### ISSUE THREAD

**Issue by n2N8Z** [ansible/ansible#80015]
### Summary

When a repo updates their gpgkey e.g. https://www.influxdata.com/blog/linux-package-signing-key-rotation/
updating the ansible task with the new key does not update the repo config, and hence rpm actions fail.

### Issue Type

Bug Report

### Component Name

yum_repository

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.7rc1]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Aug  4 2020, 04:11:56) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = False
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /redacted/ansible/redacted/ansible.cfg
DEFAULT_FORKS(/redacted/ansible/redacted/ansible.cfg) = 30
DEFAULT_HOST_LIST(/redacted/ansible/redacted/ansible.cfg) = ['/redacted/ansible/redacted/inventory']
HOST_KEY_CHECKING(/redacted/ansible/redacted/ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/redacted/ansible/redacted/ansible.cfg) = False

ssh:
___
host_key_checking(/redacted/ansible/redactedc/ansible.cfg) = False
```

### OS / Environment

Docker image based on python:3.8.0-alpine3.10

### Steps to Reproduce

Create repo with the old key
```
- name: Install influxdb repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
  when: ansible_os_family in ['RedHat']
  become: yes
```

Update the repo and run the play again - repo file still has the old key, ansible reports no change for the task.
```
- name: Install influxdb repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdata-archive_compat.key
  when: ansible_os_family in ['RedHat']
  become: yes
```

### Expected Results

I expected gpgkey to be updated as per the ansible task, because I assumed the task config was declarative and was **shocked** that it did not. ("shocked I tell you" :-). Sorry that was the word in the sample text.)

### Actual Results

```console
[2023-02-16T13:18:57.691Z] TASK [Install influxdb repository] *********************************************

[2023-02-16T13:18:59.597Z] ok: [re.da.ct.ed]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
