### ISSUE TITLE
Add condition when command/shell modules should return OK (not changed)

### ISSUE THREAD

**Issue by pbrezina** [ansible/ansible#80025]
### Summary

The ansible playbooks should be idempotent, but currently the shell module always return changed even though no changes were done. There is creates/removes parameter that can return OK if a file is (not)present, however that often requires creating artificial files since not all scripts end up with file creations (they may just alter a file, like adding record to database).

It would be helpful if the shell module had an option that would run a script to check if changes are necessary. Currently, there is a workaroud by providing special return code or message, like:

```yaml
- name: Add record
  shell: |
    if [ record-is-present ]; then
      echo "Already exist. Nothing to do."
      exit 255
    fi

    add-record
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
```

But this is error prone as you need to ensure that the message/return code is really not produced by to command itself. It is also not very neat.

### Issue Type

Feature Idea

### Component Name

command, shell

### Additional Information

```yaml
- name: Add record
  shell:
    cmd:  add-record
    check: record-is-present

- name: Add record
  command:
    cmd:  add-record
    check: record-is-present
```

`check` should be either an executable or complex script, if it returns 0 then command should not run and OK is returned.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
