### ISSUE TITLE
delegate_to can run a task on the wrong host, potentially leading to data loss

### ISSUE THREAD

**Issue by TheMysteriousX** [ansible/ansible#80038]
### Summary

I've found several issues closed with fixes matching this behaviour so this could be a regression. Most of them report random failures caused by delegate_to - in our case, the issue is causing erroneous success, leading to data loss in subsequent tasks.

The log also falsely states the command was executed on the delegated_to hosts - this possibly means it is a minor vulnerability, as a user could craft a task that executes on host x, but the logs state execution happened on host y.

In short, when delegating like this:
```
      ansible.builtin.slurp:
        src: "/etc/shufflebug"
      become: true
      delegate_to: "{{ groups['source'] | shuffle | first }}"
      loop: "{{[0,1,2,3,4,5,6,7,8,9,10 }}"
      register: shufflebug
```
Sometimes the command is executed on the original host instead of the delegated one. Removing the 'shuffle' filter appears to mitigate this. We use shuffle as the the hosts in the group 'source' run active/active, to avoid a dependency on any specific host.

For most users, I imagine this just causes the task to fail spuriously.

In our case, we copy off a system file from a host in 'source', process it, then place it onto hosts in 'destination'. The file *does* exist on destination so this means that task does not fail despite it being exeucted on the wrong host.

The playbook continues to run with the garbage input, and ends up writing garbage to the destination hosts at the end of the play.

I haven't checked but I suspect other modules will be impacted.

### Issue Type

Bug Report

### Component Name

lib/ansible/playbook/task.py

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/Users/adamb/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/adamb/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/opt/python@3.9/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(~/Developer/ansible/ansible.cfg) = True
CONFIG_FILE() = ~/Developer/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(~/Developer/ansible/ansible.cfg) = ['~/.ansible/plugins/action', '/usr/share/ansible/plugins/action', '~/Developer/ansible/plugins/action']
DEFAULT_FILTER_PLUGIN_PATH(~/Developer/ansible/ansible.cfg) = ['~/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter', '~/Developer/ansible/plugins/filter']
DEFAULT_FORKS(~/Developer/ansible/ansible.cfg) = 9
DEFAULT_HOST_LIST(~/Developer/ansible/ansible.cfg) = ['~/Developer/ansible/inventory/hosts']
DEFAULT_JINJA2_NATIVE(~/Developer/ansible/ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(~/Developer/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(~/Developer/ansible/ansible.cfg) = ~/.ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(~/Developer/ansible/ansible.cfg) = ['~/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup', '~/Developer/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(~/Developer/ansible/ansible.cfg) = Ansible managed: {{{{ lookup('git_info', template_fullpath | quote) }}}}
DEFAULT_MODULE_PATH(~/Developer/ansible/ansible.cfg) = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '~/Developer/ansible/plugins/modules', '~/.ansible/collections/*/modules']
DEFAULT_MODULE_UTILS_PATH(~/Developer/ansible/ansible.cfg) = ['~/.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils', '~/.ansible/collections/*/module_utils']
DEFAULT_ROLES_PATH(~/Developer/ansible/ansible.cfg) = ['~/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '~/Developer/ansible/roles', '~/.ansible/collections/*/roles']
DEFAULT_STDOUT_CALLBACK(~/Developer/ansible/ansible.cfg) = yaml
DEFAULT_VAULT_PASSWORD_FILE(~/Developer/ansible/ansible.cfg) = ~/Developer/ansible/contrib/vault/lastpass-client.py
DEPRECATION_WARNINGS(~/Developer/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(~/Developer/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(~/Developer/ansible/ansible.cfg) = python3
MAX_FILE_SIZE_FOR_DIFF(~/Developer/ansible/ansible.cfg) = 208896
PLAYBOOK_DIR(~/Developer/ansible/ansible.cfg) = ~/Developer/ansible/playbooks:./jobs
USE_PERSISTENT_CONNECTIONS(~/Developer/ansible/ansible.cfg) = True

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(~/Developer/ansible/ansible.cfg) = False
ssh_args(~/Developer/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600 -o PreferredAuthentications=publickey
use_persistent_connections(~/Developer/ansible/ansible.cfg) = True

ssh:
___
host_key_checking(~/Developer/ansible/ansible.cfg) = False
pipelining(~/Developer/ansible/ansible.cfg) = True
ssh_args(~/Developer/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600 -o PreferredAuthentications=publickey
```

### OS / Environment

Managed Hosts: RHEL8.7
Control Host: macOS 13.1

### Steps to Reproduce

```yaml (paste below)
- name: Setup delegate/shuffle bug - hosts that *should* be slurped from
  hosts: "{{ target | default('source') }}"
  gather_facts: false
  tasks:
    - name: Deploy file to affected hosts
      ansible.builtin.copy:
        dest: /etc/shufflebug
        content: "File correctly read from {{ inventory_hostname }}"
      become: true

- name: Setup delegate/shuffle bug - hosts that *should not* be slurped from
  hosts: "{{ target | default('destination') }}"
  gather_facts: false
  tasks:
    - name: Deploy file to affected hosts
      ansible.builtin.copy:
        dest: /etc/shufflebug
        content: "File incorrectly read from {{ inventory_hostname }}"
      become: true

- name: Demonstrate delegate/shuffle bug
  hosts: "{{ target | default('destination') }}"
  gather_facts: false
  tasks:
    - name: Get file from affected hosts - loop multiple times to trigger the bug, as it's usually the first invocation but not always
      ansible.builtin.slurp:
        src: "/etc/shufflebug"
      become: true
      delegate_to: "{{ groups['source'] | shuffle | first }}"
      loop: "{{[0,1,2,3,4,5,6,7,8,9,10] }}"
      register: shufflebug

    - name: Parse output
      ansible.builtin.debug:
        msg: "{{ 'FAIL!' if 'incorrectly' in (item.content | b64decode) else 'OK!' }}: {{ item.content | b64decode }}"
      failed_when: "'incorrectly' in (item.content | b64decode)"
      loop: "{{ shufflebug.results }}"
```

### Expected Results

When a command is delegated, it *must* run on the host it is delegated to, or fail. It must *never* execute on another host and report success.

### Actual Results

```console
PLAY [Setup delegate/shuffle bug - hosts that *should* be slurped from] ***********************************************************************************************************************************************************************

TASK [Deploy file to affected hosts] **********************************************************************************************************************************************************************************************************
ok: [source1.example.com]
ok: [source2.example.com]

PLAY [Setup delegate/shuffle bug - hosts that *should not* be slurped from] *******************************************************************************************************************************************************************

TASK [Deploy file to affected hosts] **********************************************************************************************************************************************************************************************************
ok: [destination.example.com]

PLAY [Demonstrate delegate/shuffle bug] *******************************************************************************************************************************************************************************************************

TASK [Get file from affected hosts - loop multiple times to trigger the bug, as it's usually the first invocation but not always] *************************************************************************************************************
ok: [destination.example.com -> source2.example.com] => (item=0)
ok: [destination.example.com -> source1.example.com] => (item=1)
ok: [destination.example.com -> source2.example.com] => (item=2)
ok: [destination.example.com -> source1.example.com] => (item=3)
ok: [destination.example.com -> source1.example.com] => (item=4)
ok: [destination.example.com -> source1.example.com] => (item=5)
ok: [destination.example.com -> source1.example.com] => (item=6)
ok: [destination.example.com -> source2.example.com] => (item=7)
ok: [destination.example.com -> source1.example.com] => (item=8)
ok: [destination.example.com -> source1.example.com] => (item=9)
ok: [destination.example.com -> source1.example.com] => (item=10)

TASK [Parse output] ***************************************************************************************************************************************************************************************************************************
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTIuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 0, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source2.example.com'
failed: [destination.example.com] (item={'content': 'RmlsZSBpbmNvcnJlY3RseSByZWFkIGZyb20gZGVzdGluYXRpb24uZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 1, 'ansible_loop_var': 'item'}) =>
  msg: 'FAIL!: File incorrectly read from destination.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTIuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 2, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source2.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 3, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 4, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 5, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 6, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTIuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 7, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source2.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 8, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 9, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
ok: [destination.example.com] => (item={'content': 'RmlsZSBjb3JyZWN0bHkgcmVhZCBmcm9tIHNvdXJjZTEuZXhhbXBsZS5jb20=', 'source': '/etc/shufflebug', 'encoding': 'base64', 'invocation': {'module_args': {'src': '/etc/shufflebug'}}, 'failed': False, 'changed': False, 'item': 10, 'ansible_loop_var': 'item'}) =>
  msg: 'OK!: File correctly read from source1.example.com'
fatal: [destination.example.com]: FAILED! =>
  msg: One or more items failed

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
source1.example.com : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
source2.example.com : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
destination.example.com : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sivel** [comment]
This can be worked around, assuming that you do not actually need dynamic variability in `delegate_to`, to choose a random host per loop item, by pre-calculating the host to delegate to via `set_fact`:

```yaml
    - name: Pre-calculate random delegate host
      set_fact:
        delegate_host: "{{ groups['source'] | shuffle | first }}"

    - name: Get file from affected hosts - loop multiple times to trigger the bug, as it's usually the first invocation but not always
      ansible.builtin.slurp:
        src: "/etc/shufflebug"
      become: true
      delegate_to: "{{ delegate_host }}"
      loop: "{{[0,1,2,3,4,5,6,7,8,9,10] }}"
      register: shufflebug
```

A resolution for allowing predictable dynamic variable `delegate_to` that is not linked to the loop `item` will take some complex work.  The problem is that we calculate `delegate_to` data in 2 places, and we only cache the `loop` output, and not the `delegate_to` value.  It's not as simple as caching the loop, because a loop is intended to have multiple values, whereas `delegate_to` is singular.

**Comment by sivel** [comment]
I suppose an option to have random host per loop item could be achieved by also doing more complex pre-calculations:

```yaml
    - set_fact:
        loopy_random_delegation: '{{ loop_items|zip(delegates) }}'
      vars:
        delegates: '{{ ((groups.source * loop_items|length)|shuffle)[:loop_items|length] }}'
        loop_items: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    - debug:
        msg: '{{ item.0 }}'
      delegate_to: '{{ item.1 }}'
      loop: '{{ loopy_random_delegation }}'
```

**Comment by TheMysteriousX** [comment]
There's a few viable workarounds yeah, for now we've used set_fact as above.

The biggest issue from my perspective was that it silently does the wrong thing, and doesn't log that the wrong thing has been done.

In our real use case, our play grabs a file from the delegate, adds some bits pulled from an API, then writes it to the host - which worked for the majority of hosts, but randomly (to us at the time at least) a corrupted version of the config would get written to a host with no immediately obvious cause, knocking the service offline.

Was a bit of a head scratcher, until we spotted that the connections were being launched to the wrong host.

**Comment by sivel** [comment]
Yep, definitely a bug.  We will work toward resolving this, but based on my architectural knowledge, this isn't going to be simple to resolve, so I figured I could offer some work arounds in the meantime.

**Comment by sivel** [comment]
Potentially less complex reproducer, or at least one not requiring any real target hosts:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - add_host:
        name: 'host{{ item }}'
        groups:
          - test
      loop: '{{ range(10) }}'

    # This task may fail, if it does, it means the same thing as if the assert below fails
    - set_fact:
        dv: '{{ ansible_delegated_vars[ansible_host]["ansible_host"] }}'
      delegate_to: '{{ groups.test|shuffle|first }}'
      delegate_facts: true
      # Purposefully smaller loop than group count
      loop: '{{ range(5) }}'

- hosts: test
  gather_facts: false
  tasks:
    - assert:
        that:
          - dv == inventory_hostname
      # The small loop above means we won't set this var for every host
      # and a smaller loop is faster, and may catch the error in the above task
      when: dv is defined
```
