### ISSUE TITLE
eos_logging_global source_interface Option Doesn't Apply Configuration When Using Replaced State

### ISSUE THREAD

**Issue by kurtwickboldt** [ansible/ansible#80069]
### Summary

When the source_interface option is used for the eos_logging_global module, the configuration on the device is not replaced, even if the state is specified as replaced. It also doesn't apply the source_interface from the YAML config, even when no source-interface is defined on the device.

### Issue Type

Bug Report

### Component Name

eos_logging_global

### Ansible Version

```console
sh-4.4# ansible --version
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
sh-4.4# ansible-config dump --only-changed
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

### OS / Environment

NAME="CentOS Linux"
VERSION="7 (Core)"

### Steps to Reproduce

```yaml (paste below)

    - name: Apply Syslog config onto device
      arista.eos.eos_logging_global:
        state: replaced
        config: 
          buffered:
            buffer_size: 81920
          source_interface: "Loopback0"
      register: syslog_output


syslog_output debug:
        "before": {
            "buffered": {
                "buffer_size": 81920
            },
            "monitor": "debugging",
            "hosts": [
                {
                    "name": "100.110.108.214",
                    "port": 514
                },
                {
                    "name": "100.110.114.214",
                    "port": 514
                }
            ]
        "after": {
            "buffered": {
                "buffer_size": 81920
            },
            "monitor": "debugging",
            "hosts": [
                {
                    "name": "100.110.108.214",
                    "port": 514
                },
                {
                    "name": "100.110.114.214",
                    "port": 514
                }
            ]

```

### Expected Results

        "after": {
            "buffered": {
                "buffer_size": 81920
            },
            "monitor": "debugging",
            "hosts": [
                {
                    "name": "100.110.108.214",
                    "port": 514
                },
                {
                    "name": "100.110.114.214",
                    "port": 514
                }
            ],
            "source_interface": "Loopback0"

### Actual Results

```console
"after": {
            "buffered": {
                "buffer_size": 81920
            },
            "monitor": "debugging",
            "hosts": [
                {
                    "name": "100.110.108.214",
                    "port": 514
                },
                {
                    "name": "100.110.114.214",
                    "port": 514
                }
            ]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
