### ISSUE TITLE
Ansible thinks the python interpreter is the same on localhost and remote hosts

### ISSUE THREAD

**Issue by sq5bpf** [ansible/ansible#80097]
### Summary

When ansible reaches out to a remote host with the file module it will assume that all pythons in the universe will be the same as the python version detected on the remote host.

So if host running ansible has only python 3, and the remote host has only python 2.7, a local command will fail on the host running ansible, because there is no /usr/bin/python.

The discovery result should be local to one host, and not global.

 

### Issue Type

Bug Report

### Component Name

file module and ansible.builtin.wait_for

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = /home/ansible/test1/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
CONFIG_FILE() = /home/ansible/test1/ansible.cfg
DEFAULT_BECOME(/home/ansible/test1/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/ansible/test1/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/ansible/test1/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/ansible/test1/ansible.cfg) = root
DEFAULT_HOST_LIST(/home/ansible/test1/ansible.cfg) = ['/home/ansible/test1/inventory.ini']

BECOME:
======

runas:
_____
become_user(/home/ansible/test1/ansible.cfg) = root

su:
__
become_user(/home/ansible/test1/ansible.cfg) = root

sudo:
____
become_user(/home/ansible/test1/ansible.cfg) = root
```

### OS / Environment

ansible running on Debian GNU/Linux 11 (bullseye) (with python 3 and no python 2.7)

target: Debian GNU/Linux 9 (stretch)   (with python 2.7, and no python 3)

### Steps to Reproduce

```yaml (paste below)
- name: bug test
  hosts: xen
  gather_facts: no
  vars:
    #set bug: false to omit the mkdir
    bug: true

  tasks:

    - name: "test mkdir"
      file:
        path: "/tmp/a"
        state: directory
      when: bug == true


    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      become: false
      ansible.builtin.wait_for:
        port: 22
        host: 10.1.10.60
        search_regex: OpenSSH
        delay: 1
      vars:
        ansible_connection: local
          #uncomment the next line to hide the error
          #ansible_python_interpreter: /usr/bin/python3



```

ansible.cfg:
[defaults]
inventory=inventory.ini
[privilege_escalation]
remote_user=ansible
become=true
become_method=sudo
become_user=root
become_ask_pass=false

inventory.ini:
[xen]
10.1.1.11

### to reproduce:
install a debian 9 host with python 2.7 and no python3 , this is 10.1.1.11
install a debian 11 host with OpenSSH running on 22/tcp, this is 10.1.10.60
install debian 11 host with python3 and no python 2.7 as the host running ansible using pip3
ansible-playbook play3.yaml

### Expected Results

The ansible playbook should:

1. reach out to a debian 9 host (running python 2.7, without /usr/bin/python3) and make a directory /tmp/a
2. try to connect from localhost (the host running ansible) to 22/tcp to some IP and check if there in an OpenSSH banner

I since either of the commands runs fine, i expect them both to run fine too.

But in this example:

- task 1 only works ok

- task 2 only works ok (set bug: false in the playbook)

- task 1 and task 2 together don't work. Ansible thinks: hey, i've just conected to some random host on the internet (which has /usr/bin/python , python 2.7), and now i am sure that all pythons in the universe must be the same, including the one running on localhost (which has /usr/bin/python3 only). 

You can make both tasks work if ansible_python_interpreter: /usr/bin/python3 is set in task 2

- when the tasks are reversed (first check connection, then mkdir), then the mkdir fails, because ansible has deduced that all pythons are /usr/bin/python3 (and host 10.1.1.11 only has /usr/bin/python)

BTW i've tried to see if i can make ansible think that the omnipresent  python interpreter is /sbin/reboot, but i failed (maybe due to lack of knowledge about how ansible detects  the python version). If i could trick it to do that, than it would turn into a security problem, since some random target host could force ansible to execute unintended commands locally.

I've tried searching bug reports, and didn't find anything that matches exactly.

### Actual Results

```console
ansible@hades:~/test1$ ansible-playbook play3.yaml

PLAY [bug test] ******************************************************************************************************************************

TASK [test mkdir] ****************************************************************************************************************************
ok: [10.1.1.11]

TASK [Wait 300 seconds for port 22 to become open and contain "OpenSSH"] *********************************************************************
fatal: [10.1.1.11]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: 1: /usr/bin/python: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP ***********************************************************************************************************************************
10.1.1.11                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/file.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/file.py)
* [`lib/ansible/modules/wait_for.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/wait_for.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
`ansible_connection: local` _only_ changes the connection plugin, while still using all other details for the target host, including the python interpreter that was discovered to be used on the target host.

What you want instead of using `ansible_connection: local` is to use `delegate_to: localhost`.  Setting `ansible_connection: local` is almost never what you want.

```yaml
    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      become: false
      ansible.builtin.wait_for:
        port: 22
        host: 10.1.10.60
        search_regex: OpenSSH
        delay: 1
      delegate_to: localhost
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
