### ISSUE TITLE
enable ansible.builtin.assert to assert inside dictionaries

### ISSUE THREAD

**Issue by Unip0rn** [ansible/ansible#80095]
### Summary

I am trying to make a role that has its variables in one dictionary so when applying it multiple times with different variables it is easy to keep those variables in a list of dictionaries that is easy to loop over, rather than having to set every variable individually, because it would improve readability of the playbook. In my case the role is a wireguard setup.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.assert

### Additional Information

```yaml
- name: assert inside a dictionary
  ansible.builtin.assert:
    that:
      - dict is defined
      - dict.key is defined
      - dict.otherKey is defined
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/assert.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/assert.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
It's unclear to me what feature you think is missing. `assert` just takes Jinja expressions, it doesn't care what data structure those expressions use.

```yaml
- hosts: localhost
  vars:
    foo:
      my_key: yah
  tasks:
    - assert:
        that:
          - foo is defined
          - foo.my_key is defined
          - foo.your_key is defined
```

```
TASK [assert] ******************************************************************
fatal: [localhost]: FAILED! =>
    assertion: foo.your_key is defined
    changed: false
    evaluated_to: false
    msg: Assertion failed
```

(Also, for role argument validation specifically you might want to look at https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation instead of using manual assert tasks.)
