### ISSUE TITLE
Don't mark the node unreachable in play recap if we are ignoring a task with ignore_unreachable: true

### ISSUE THREAD

**Issue by manoj0077** [ansible/ansible#80116]
### Summary

When we are ignoring a task with ignore_unreachable: true, we still see the node color coded as unreachable in play recap. 

I would like to see the behaviour on similar lines with ignore_errors: true. We don't mark the node as failed and instead add the task to ignored section in play recap. 

When we are running a task which cuts down the network while running it and even though I marked the task as ignore_unreachable: true, in the play recap it still shows the node color coded as unreachable. 

Above approach creates the confusion when we are taking a look at the play recap. 

When we know we are ignoring a task which might be unreachable, we should color code the node as successful. 

### Issue Type

Feature Idea

### Component Name

PLAY RECAP

### Additional Information

```
---

- name: Test Ignore_unreachable
  hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: ssh
  tasks:
    - name: Test unreachable
      ansible.builtin.command: /bin/true
      ignore_unreachable: true
      changed_when: false
      vars:
        ansible_port: 222

    - name: 
      ansible.builtin.command: /bin/true
      changed_when: false
      vars:
        ansible_port: 22

```

Below is the screen shot when I run the above playbook.
<img width="433" alt="Status" src="https://user-images.githubusercontent.com/10062127/222019025-1fd9e5c3-b114-4d9b-904b-b421fdab685d.png">

I would like to see the node marked in green color and we can see status is successful too. 

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
