### ISSUE TITLE
More detailed description about how command module's argv parameters works

### ISSUE THREAD

**Issue by tariver** [ansible/ansible#80126]
### Summary

Writing this following #79967, which I created because I thought that I encountered a bug, but in fact I didn't know some details about how `argv` parameter works.

It would be great to have information provided to me there in the documentation in case anybody else encounter the same issues. Especially this comment was very helpful:
> precisely because you can use white space you need to separate what is not the same argument or the flag + argument are passed as a unit '--flag arg' vs '--flag' 'arg'

### Issue Type

Documentation Report

### Component Name

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py

### Ansible Version

```console
$ ansible --version
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Linux

### Additional Information

When the improvement is applied, it makes it more straightforward to understand how argv parameters works

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/executor/discovery/python_target.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/discovery/python_target.py)
* [`lib/ansible/modules/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
I think we probably need an example like this:

```yaml
- name: Run command using argv with mixed argument formats
  command:
    argv:
      - /path/to/binary
      - -v
      - --debug
      - --longopt
      - value for longopt
      - --other-longopt=value for other longopt
      - positional
```
