### ISSUE TITLE
ansible_become sets its value everywhere if setting ansible_become as variable of an import_role task

### ISSUE THREAD

**Issue by jjak0b** [ansible/ansible#80186]
### Summary

When i set a value in ansible_become in the `vars` of a task which use the `import_role` module, i expect that `ansible_become` value has its value set only in the scopes that it should have a specific value..
In my reproducible example i set `ansible_become: false` in `vars` of some tasks, but if i run the code then all debug prints show that `ansible_become` is `false` everywhere in the play even if it's not set.

As conseguence the `whoami` result shows that the current user is the `ansible_user` and not the `ansible_become_user` or root even if i used `become: yes`.

### Issue Type

Bug Report

### Component Name

import_role

### Ansible Version

```console
$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed
```

### OS / Environment

- Ubuntu 22.04.2 LTS
- Debian GNU/Linux 11 (bullseye)

### Steps to Reproduce

The playbook:
```yaml (paste below)

- hosts: localhost
  connection: local
  gather_facts: yes
  tasks: 

    - block: 
        - name: This should not be defined
          debug:
            var: ansible_become
        
        - name: "This should be the ansible_become_user but it's the ansible_user"
          shell:
            cmd: whoami
          register: my_whoami_result

        - debug:
            var: my_whoami_result
      become: yes

    - name: "my test 1: This should not be defined"
      debug:
        var: ansible_become

    - name: Importing a random role in this way doesnt cause issues
      block:
        - name: "This should be false"
          debug:
            var: ansible_become
        - name: "importing a role"
          ansible.builtin.import_role:
            name: empty
      vars:
        ansible_become: false

    
    - name: "my test 2: This should not be defined"
      debug:
        var: ansible_become
    
    # Issue: if this task is commented or include_role is used then all results in the playbook are right, otherwise ansible_become is false everywhere
    - name: "Importing a random role in this way cause issues: ansible_become is false everywhere in all tasks"
      ansible.builtin.import_role:
        name: empty
      vars:
        ansible_become: false

    - name: "my test 3: This should not be defined"
      debug:
        var: ansible_become

```

The mailn.yml  of the "empty" role
```yaml (paste below)

- name: Test in imported role
  debug:
    var: ansible_become

```

### Expected Results

I expect to find the same result of what i get if i replace `import_role` with `include_role`, so the following (correct) result:

```
PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [This should not be defined] **************************************************************************************
ok: [localhost] => {
    "ansible_become": "VARIABLE IS NOT DEFINED!"
}

TASK [This should be the ansible_become_user but it's the ansible_user] ************************************************
changed: [localhost]

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "my_whoami_result": {
        "changed": true,
        "cmd": "whoami",
        "delta": "0:00:00.003625",
        "end": "2023-03-09 19:37:38.857000",
        "failed": false,
        "rc": 0,
        "start": "2023-03-09 19:37:38.853375",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "root",
        "stdout_lines": [
            "root"
        ]
    }
}

TASK [my test 1: This should not be defined] ***************************************************************************
ok: [localhost] => {
    "ansible_become": "VARIABLE IS NOT DEFINED!"
}

TASK [This should be false] ********************************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [empty : Test in imported role] ***********************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [my test 2: This should not be defined] ***************************************************************************
ok: [localhost] => {
    "ansible_become": "VARIABLE IS NOT DEFINED!"
}

TASK [Importing a random role in this way cause issues: ansible_become is false everywhere in all tasks] ***************

TASK [empty : Test in imported role] ***********************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [my test 3: This should not be defined] ***************************************************************************
ok: [localhost] => {
    "ansible_become": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=10   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

### Actual Results

```console
PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [This should not be defined] **************************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [This should be the ansible_become_user but it's the ansible_user] ************************************************
changed: [localhost]

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "my_whoami_result": {
        "changed": true,
        "cmd": "whoami",
        "delta": "0:00:00.002888",
        "end": "2023-03-09 19:30:49.876900",
        "failed": false,
        "rc": 0,
        "start": "2023-03-09 19:30:49.874012",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "user",
        "stdout_lines": [
            "user"
        ]
    }
}

TASK [my test 1: This should not be defined] ***************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [This should be false] ********************************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [empty : Test in imported role] ***********************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [my test 2: This should not be defined] ***************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [empty : Test in imported role] ***********************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

TASK [my test 3: This should not be defined] ***************************************************************************
ok: [localhost] => {
    "ansible_become": false
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=10   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
