### ISSUE TITLE
lineinfile append to string replaces whole line

### ISSUE THREAD

**Issue by Setsua** [ansible/ansible#80199]
### Summary

If you want to append a string to an existing string via lineinfile the string is replaced. Added replace example where the regex find works.

### Issue Type

Bug Report

### Component Name

lineinfile

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/home/setsua/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/setsua/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/setsua/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/setsua/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Steps to Reproduce

```plaintext
#demo.txt content
demo,test,foo
```

```yaml (paste below)
- name: Test
  hosts: localhost
  connection: local
  tasks:

    - name: Test lineinfile
      ansible.builtin.lineinfile:
        regex: '^(demo.*)$'
        line: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"

    - name: Test replace
      ansible.builtin.replace:
        regexp: '^(demo.*)$'
        replace: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"

```

### Expected Results

demo.txt content:
demo,test,foo -> demo,test,foo,foobar

### Actual Results

```console
demo.txt content:
demo,test,foo -> \1,foobar
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/lineinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/lineinfile.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by binarysta** [comment]
if `backrefs: yes` specified, it will work as expected.

```
    - name: Test lineinfile
      ansible.builtin.lineinfile:
        regex: '^(demo.*)$'
        line: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"
        backrefs: yes
```
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html#parameter-backrefs

**Comment by Setsua** [comment]
I checked my original playbook and backrefs was already set. Found out the changes were not written when I checked for the changes before hand. In check_mode it reports a success so the actual change is skipped.
```yaml
---
- name: Test
  hosts: localhost
  connection: local
  tasks:

    - name: Check if changes were already made
      ansible.builtin.lineinfile:
        regex: '^(demo.*)$'
        line: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"
        backrefs: true
      check_mode: true
      register: settings_already_made

    - name: Test lineinfile
      ansible.builtin.lineinfile:
        regex: '^(demo.*)$'
        line: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"
        backrefs: true
      when: settings_already_made is not succeeded
```

**Comment by binarysta** [comment]
this is because `settings_already_made` variable is not really  "succeeded". Check it with `debug`.

```yaml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Check if changes were already made
      ansible.builtin.lineinfile:
        regex: '^(demo.*)$'
        line: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"
        backrefs: true
        state: present
      check_mode: true
      register: settings_already_made

    - name: debug
      debug:
        var: settings_already_made
```

I'd suggest to use a more precise regex. With your current regex, ansible will add `,foobar` to the end of line each time you run it.

With following example your change will be idempotent.

```yaml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Test lineinfile
      ansible.builtin.lineinfile:
        regex: '^(demo.*?)(,foobar)?$'
        line: '\1,foobar'
        path: "{{ playbook_dir }}/demo.txt"
        backrefs: true
```
