### ISSUE TITLE
Using lookup() in authorized_key as shown in doc example crashes

### ISSUE THREAD

**Issue by tedwardd** [ansible/ansible#80191]
### Summary

The [documented example](https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html#examples) of how to add authorized_keys to a user from github by way of the `lookup()` method causes ansible to crash

### Issue Type

Bug Report

### Component Name

authorize_user

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/Users/twood5/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/7.3.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/twood5/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/7.3.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Client OS: MacOS Ventura 13.2.1 (Apple M1)
Target OS:  Ubuntu 22.04

### Steps to Reproduce

Using the following example code in a loop -- https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html#examples
```yaml (paste below)
vars:
  local_users:
    - tedwardd
- name: Create local users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    state: present
  loop: "{{ local_users }}"
- name: Set authorized keys taken from url using lookup
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('url', 'https://github.com/tedwardd.keys', split_lines=False) }}"
  loop: "{{ local_users }}"
```

### Expected Results

Should not crash

### Actual Results

```console
[Create authorized_keys for local users] ***************************************************************************************************************************************
objc[33184]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[33184]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
