### ISSUE TITLE
Variable of type dictionary specified in `vars` is undefined, if one dictionary value is undefined

### ISSUE THREAD

**Issue by julianbuettner** [ansible/ansible#80190]
### Summary

When specifying a dictionary variable in a `vars` block with an undefined variable as value (e.g. `key: "{{ not_existing_value}}"`), the dictionary variable is undefined.  

### Issue Type

Bug Report

### Component Name

core

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/{{username}}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/{{username}}/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/{{username}}/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

Ubuntu 20.04, WSL

### Steps to Reproduce

```yaml (paste below)
---
# File playbook-reproduction.yaml

- name: Variable Undefined Reproduction
  hosts: localhost
  connection: local
  tasks:
    - name: Print variable
      debug:
        var: my_variable
      vars:
        my_variable:
          key1: value1
          this_should_fail: "{{ not_existing_variable }}"
```

```bash
ansible-playbook playbook-reproduction.yaml
```

Also: Uncomment the last line, and it works as expected.

### Expected Results

I expected an error message, equivalent to `set_fact`. Something like  
```
TASK [Print variable] *************************************************************************
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'not_existing_variable' is undefined. 'not_existing_variable' is undefined"
}
```

### Actual Results

```console
TASK [Print variable -vvv] *****************************
task path: /home/julian/test/playbook-variable-undefined.yaml:7
ok: [localhost] => {
    "my_variable": "VARIABLE IS NOT DEFINED!: {'key1': 'value1', 'this_should_fail': '{{ not_existing_variable }}'}: 'not_existing_variable' is undefined. 'not_existing_variable' is undefined. {'key1': 'value1', 'this_should_fail': '{{ not_existing_variable }}'}: 'not_existing_variable' is undefined. 'not_existing_variable' is undefined"
}


TASK [Print variable] ************************
ok: [localhost] => {
    "my_variable": "VARIABLE IS NOT DEFINED!"
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
This is expected and documented in the [`debug` module's documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html#synopsis) which explicitly says:
> This module prints statements during execution and can be useful for debugging variables or expressions without necessarily halting the playbook.

**Comment by julianbuettner** [comment]
It is not limited to `debug`. I know that debug does not fail for printing undefined variables.  
I found the bug by trying to generate a docker container with an environment.  
The entire environment is silently undefined for one undefined value.

```yaml
---
- name: Variable Undefined Reproduction
  hosts: localhost
  connection: local
  tasks:
    - name: Print variable
      docker_container:
        name: my_container
        image: alpine
        detach: false
        cleanup: true
        command:
          - /bin/sh
          - -c
          - "echo HELLO $HELLO"
        env: "{{ env | default({}) }}"
      register: output
      vars:
        env:
          HELLO: world
          BYE: "{{ undefined }}"
    - name: Debug
      debug:
        msg: "{{ output.container.Output }}"
```
I expected `"{{ env | default({}) }}"` to fail, but instead it falls back to default and defines no environment variables.
```
TASK [Debug] ************************
ok: [localhost] => {
    "msg": "HELLO\n"
}
```

Dropping line `BYE: "{{ undefined }}"`  results in a working command, output:

```
TASK [Debug] ************************
ok: [localhost] => {
    "msg": "HELLO world\n"
}
```

I think my minimal reproducible example should indeed fail.

**Comment by flowerysong** [comment]
Propagating the undefined value "upward" to make the whole dictionary undefined is the intended behaviour, not a bug. See https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.14.html#playbook

**Comment by julianbuettner** [comment]
Thank you for linking the reference.

I see why it was implemented, however, I think the behaviour should not have been changed,
dictionaries with undefined values should be converted to undefined explicitly.

The following code block is copied from the migration guide:
```yaml
- assert:
    that:
      - some_defined_dict_with_undefined_values is undefined
  vars:
    dict_value: 1
    some_defined_dict_with_undefined_values:
      key1: value1
      key2: '{{ dict_value }}'
      key3: '{{ undefined_dict_value }}'
```

The assert statement reads: "some defined dict with undefined values is undefined",
but "some defined dict [...] is undefined" sounds a little bit off to me.

I think the recursive undefined check is great, but I'd like to access it rather explicitly.  
For example

```yaml
- debug:
  msg: "{{ some_defined_dict_with_undefined_values | recursive_default(undefined) }}"
```

or 

```yaml
- debug:
  msg: "{{ some_defined_dict_with_undefined_values | recursive_dict_undefined() }}"
```

Please pardon me, if I am causing any inconvenience or frustration.
