### ISSUE TITLE
vmware_guest ocaasionally not connecting network adapter 

### ISSUE THREAD

**Issue by asaf-refaeli** [ansible/ansible#80207]
### Summary

I am using vmware_guest ansible module to create 2 vms (RHEL 8.4) at the same time.
The thing is that only sometimes,
in one vm (let's call it vm1), the NIC is connecting at power on, and in the the second vm (vm2), the NIC is not connecting.
sometimes, vm2 NIC is connecting and vm1 NIC is not connecting.
And sometimes, both vms NICs are connecting(which is of course good but not consistent so I can't count on it).

In my test environment it happens the way I described above, and in my prod environment (I don't have access to it all the time) it happens all the time (but which vm NIC is connected still changes between vm1 and vm2 in every playbook run)

This is the 'networks' part in my playbook
```
networks:
- name: <vcenter network>
  ip: <ip>
  netmask: <255.255.255.0>
  gateway: <gateway>
  devicetype: vmxnet3
  start_connected: true
  connected: true
  dns_servers: <dns servers>
wait_for_ip_address: true
wait_for_customization: true
```

I tried adding and removing all the parameters:
```  
  start_connected: true
  connected: true

wait_for_ip_address: true
wait_for_customization: true
```

It did not help.

I am the only one working on the vcenter, and I do not change anything between playbook runs.

I watched the /var/log/vmware-imc/toolsDeployPkg.log it says i should install cloud-init. I did installed it (version 20.3-10.e18_4.5) - did not help.

Thank you.

### Issue Type

Bug Report

### Component Name

vmware_guest

### Ansible Version

```console
$ ansible --version
ansible 2.9.19
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

RHEL 8.4

### Steps to Reproduce

Can't reproduce

### Expected Results

I expect from both vms to connect the NIC, all the time, or at least try to reproduce the bug.

### Actual Results

```console
..
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
