### ISSUE TITLE
copy module: No option to exclude directory in copy module

### ISSUE THREAD

**Issue by Gunni** [ansible/ansible#80208]
### Summary

Currently there is no option to exclude things inside the src directory while using the `copy` module.

Note that the `synchronize` module does not work in my case due to `ansible_connection=chroot`.

### Issue Type

Feature Idea

### Component Name

copy

### Additional Information

Note that the `synchronize` module fails with this error: `synchronize uses rsync to function. rsync needs to connect to the remote host via ssh, docker client or a direct filesystem copy. This remote host is being accessed via community.general.chroot instead so it cannot work.`

There was a [bug for this previously](https://github.com/ansible/ansible/issues/69559) but it did not address my use case (dest being a chroot environment).

```yaml
- name: Install the example script
  copy:
    src: example
    dest: /usr/local/sbin
    mode: u=rwx,go=
    directory_mode: u=rwx,go=
```

State on source:

```
.idea
main.py
makefile
mypy.ini
requirements.txt
state_screen
.venv
```

Wanted state on dest:

```
main.py
state_screen
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/copy.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/copy.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by ChamMach** [comment]
Hello @Gunni,

I think adding the `exclude` option may be a more "friendly" implementation regarding your context.

But, have you tried with this kind of workaround?

```
- name: Find files to copy, excluding unwanted ones
  find:
    paths: example
    excludes: '*.idea,makefile,mypy.ini,requirements.txt,.venv'
    file_type: any
  register: files_to_copy

- name: Copy files and directories, excluding unwanted ones
  copy:
    src: "{{ item.path }}"
    dest: "/usr/local/sbin/{{ item.path | basename }}"
    mode: u=rwx,go=
    directory_mode: u=rwx,go=
  with_items: "{{ files_to_copy.files }}"
```
