### ISSUE TITLE
become fails in podman container

### ISSUE THREAD

**Issue by rudenkornk** [ansible/ansible#80254]
### Summary

`become` does not work in podman containers.

### Issue Type

Bug Report

### Component Name

become plugin

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.0]
  config file = None
  configured module search path = ['/home/rudenkornk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/rudenkornk/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True

(Does not work with 2.14 either)
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

config:
______
_terms(None) = None

dict:
____
_terms(None) = None

env:
___
_terms(None) = None

file:
____
_terms(None) = None

fileglob:
________
_terms(None) = None

indexed_items:
_____________
_terms(None) = None

ini:
___
_terms(None) = None

items:
_____
_terms(None) = None

lines:
_____
_terms(None) = None

password:
________
_terms(None) = None

pipe:
____
_terms(None) = None

subelements:
___________
_terms(None) = None

together:
________
_terms(None) = None

unvault:
_______
_terms(None) = None

varnames:
________
_terms(None) = None

vars:
____
_terms(None) = None

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

### Steps to Reproduce

```yaml
# inventory.yaml
all:
  hosts:
    localhost:
      ansible_connection: local
    example_container:
      ansible_connection: podman
      ansible_python_interpreter: auto_silent

```
```yaml
# container.yaml
- name: Create test linux container
  hosts: localhost
  tasks:
    - name: Spin up example_container
      containers.podman.podman_container:
        name: example_container
        image: ubuntu:22.04
        interactive: true
        tty: true
```
```yaml
# bootstrap.yaml
- name: Bootstrap hosts
  hosts: example_container
  vars:
    ansible_user: root
  gather_facts: false
  tasks:
    - name: Install python
      become: true
      ansible.builtin.raw: |
        if ! command -v python3 &> /dev/null; then
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive apt-get \
            install --yes --no-install-recommends \
            python3-venv \
            && \
          echo "bootstrapped";
        fi
      args:
        executable: bash
      register: bootstrap
      changed_when: ("bootstrapped" in bootstrap.stdout)

    - name: Install sudo
      become: true
      ansible.builtin.apt:
        name:
          - sudo

    - name: Add some user
      become: true
      ansible.builtin.user:
        name: some_user
        # yamllint disable-line rule:line-length
        password: "{{ '123' | password_hash(salt='somesalt') }}"
        groups:
          - adm
          - sudo
        append: true
```
```yaml
# becoming.yaml
- name: Try escalate privileges
  hosts: example_container
  vars:
    ansible_user: some_user
  tasks:
    - name: Install gnupg
      become: true
      ansible.builtin.apt:
        name: gnupg
```
```bash
ansible-playbook -i inventory.yaml container.yaml
ansible-playbook -i inventory.yaml bootstrap.yaml
ansible-playbook -i inventory.yaml -e "ansible_sudo_pass=123" becoming.yaml # -K flag does not work either
```

### Expected Results

Successful execution.

### Actual Results

```console
» ansible-playbook -i inventory.yaml container.yaml

PLAY [Create test linux container] **************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Spin up example_container] ****************************************************************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

» ansible-playbook -i inventory.yaml bootstrap.yaml

PLAY [Bootstrap hosts] **************************************************************************************************************************************************************************************************************************************************

TASK [Install python] ***************************************************************************************************************************************************************************************************************************************************
changed: [example_container]

TASK [Install sudo] *****************************************************************************************************************************************************************************************************************************************************
changed: [example_container]

TASK [Add some user] ****************************************************************************************************************************************************************************************************************************************************
changed: [example_container]

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************
example_container          : ok=3    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

» ansible-playbook -i inventory.yaml -e "ansible_sudo_pass=123" becoming.yaml

PLAY [Try escalate privileges] ******************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************************
ok: [example_container]

TASK [Install gnupg] ****************************************************************************************************************************************************************************************************************************************************
fatal: [example_container]: FAILED! => {"changed": false, "module_stderr": "[sudo via ansible, key=gvjksipvifpoyeevvprxmoplwxpzrkmd] password:\nsudo: no password was provided\nsudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************
example_container          : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
