### ISSUE TITLE
module package doesn't expose autoremove supported by multiple sub module

### ISSUE THREAD

**Issue by Et7f3** [ansible/ansible#80276]
### Summary

In the latest documentation of ansible.builtin.package I don't see autoremove that remove un-needed packages: It is supported by yum and apt. Can it be wired ? The same for cache cleaning.

### Issue Type

Feature Idea

### Component Name

packages

### Additional Information

```yaml (paste below)
- name: Remove the apache package
  ansible.builtin.package:
    name: "{{ apache }}"
    state: absent
    autoremove: true
```
Remove apache and dependencies.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
