### ISSUE TITLE
`ansible.builtin.apt_repository`: `filename` argument is ignored when different file with identical content exists

### ISSUE THREAD

**Issue by Sebbo94BY** [ansible/ansible#80271]
### Summary

I have various Ansible roles, which should configure their respective required APT repository in a specific file.

In my case, both roles require currently the exact same APT repository at the moment.

However, only the first task creates the respective APT source list. The other task always gets marked as "ok", although the file doesn't exist or did not got created.

### Issue Type

Bug Report

### Component Name

ansible.builtin.apt_repository

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.3]
  config file = /home/skraetzig/Git/infrastructure/ansible.cfg
  configured module search path = ['/home/skraetzig/Git/infrastructure/ansible/library']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /usr/share/ansible/third-party/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_NOCOWS(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
ANY_ERRORS_FATAL(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
COLLECTIONS_PATHS(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/usr/share/ansible/third-party/collections']
CONFIG_FILE() = /home/skraetzig/Git/infrastructure/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/home/skraetzig/Git/infrastructure/ansible/filter_plugins']
DEFAULT_FORKS(/home/skraetzig/Git/infrastructure/ansible.cfg) = 50
DEFAULT_LOCAL_TMP(env: ANSIBLE_LOCAL_TEMP) = /tmp/ansible-local-1kk0g7mi3
DEFAULT_MODULE_PATH(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/home/skraetzig/Git/infrastructure/ansible/library']
DEFAULT_REMOTE_USER(/home/skraetzig/Git/infrastructure/ansible.cfg) = deploy
DEFAULT_ROLES_PATH(/home/skraetzig/Git/infrastructure/ansible.cfg) = ['/home/skraetzig/Git/infrastructure/ansible/roles', '/home/skraetzig/Git/infrastructure/ansible/actions', '/hom>
DIFF_ALWAYS(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = True
INTERPRETER_PYTHON(/home/skraetzig/Git/infrastructure/ansible.cfg) = /usr/bin/python3
MAX_FILE_SIZE_FOR_DIFF(/home/skraetzig/Git/infrastructure/ansible.cfg) = 1044480
RETRY_FILES_ENABLED(/home/skraetzig/Git/infrastructure/ansible.cfg) = False

CALLBACK:
========

default:
_______
display_ok_hosts(env: ANSIBLE_DISPLAY_OK_HOSTS) = True
display_skipped_hosts(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = True

CONNECTION:
==========

local:
_____
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True

paramiko_ssh:
____________
remote_user(/home/skraetzig/Git/infrastructure/ansible.cfg) = deploy
ssh_args(env: ANSIBLE_SSH_ARGS) = -C -o ControlMaster=auto -o ControlPersist=60s

psrp:
____
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True

ssh:
___
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
remote_user(/home/skraetzig/Git/infrastructure/ansible.cfg) = deploy
ssh_args(env: ANSIBLE_SSH_ARGS) = -C -o ControlMaster=auto -o ControlPersist=60s

winrm:
_____
pipelining(/home/skraetzig/Git/infrastructure/ansible.cfg) = True
```

### OS / Environment

Debian 10 (Buster) and 11 (Bullseye)

### Steps to Reproduce

```yaml (paste below)
- name: configure apt repository (first task)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: elastic
    update_cache: yes
    state: present
  become: true

- name: configure apt repository (second task)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: elasticsearch
    update_cache: yes
    state: present
  become: true
```

### Expected Results

```console
# /etc/apt/sources.list.d/elastic.list
deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main

# /etc/apt/sources.list.d/elasticsearch.list
deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main
```

(Yes, this would cause the warning `duplicate repository configured` for APT, but this should be my problem and not Ansible.)

### Actual Results

```console
# /etc/apt/sources.list.d/elastic.list
deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main
```

_(`/etc/apt/sources.list.d/elasticsearch.list` does not get created at all since the same APT repository exists already somewhere else.)_

```console
TASK [elasticsearch : configure apt repository (first task)] ********************************
--- before: /dev/null
+++ after: /etc/apt/sources.list.d/elastic.list
@@ -0,0 +1 @@
+deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main

changed: [elasticsearch-01-01.example.com]

TASK [elasticsearch : configure apt repository (second task)] ********************************
ok: [elasticsearch-01-01.example.com]
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
