### ISSUE TITLE
Using validate_argument_spec `default` option doesn't set any var or fact in play

### ISSUE THREAD

**Issue by farazoman** [ansible/ansible#80298]
### Summary

When using validate_argument_spec module (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/validate_argument_spec_module.html) with a default. In subsequent tasks I find that the default value I specified was not set. 

Since the docs say I can provide a default, I'd assume it would be set, or at least output so I can register the default value after the fact. Not sure if this is expected or not.

### Issue Type

Bug Report

### Component Name

validate_argument_spec module

### Ansible Version

```console
$ ansible --version
root@b99294de64e5:/src/ansible# ansible --version
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/src/ansible_collections/safety/common/plugins/modules']
  ansible python module location = /root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.9.16 (main, Mar 14 2023, 03:19:12) [GCC 8.3.0] (/usr/local/bin/python)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
root@b99294de64e5:/src/ansible# ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/src/ansible_collections/safety/common/plugins/modules']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/src/ansible_collections/safety/common/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON(env: ANSIBLE_PYTHON_INTERPRETER) = /usr/local/bin/python
root@b99294de64e5:/src/ansible#
```

### OS / Environment

root@b99294de64e5:/src/ansible# echo $OSTYPE
linux-gnu

### Steps to Reproduce

Sample Task file `roles/defect/tasks/some-task.yml`
```yaml (paste below)
- name: verify vars needed for this task file are present when included
  ansible.builtin.validate_argument_spec:
    argument_spec: '{{ required_data }}'
  vars:
    required_data:
        volume_size:
          description: vol size
          type: str
          required: false
          default: 80
- shell: echo "{{  volume_size }}"
```

Sample Playbook
```yaml
--- 
- hosts: localhost
  connection: local
  tasks:
    - name: Provision Launch Template
      include_role:
        name: defect
        tasks_from: some-task.yml
```

The above playbook will fail when trying to reference the variable with a default value in `required_data`

### Expected Results

I expected a fact or variable to be set so I could subsequently access it. 

### Actual Results

```console
task path: /src/ansible_collections/safety/common/roles/ec2/tasks/create-launch-template.yml:64
fatal: [localhost]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'volume_size' is undefined. 'volume_size' is undefined

    The error appears to be in '/src/ansible_collections/safety/common/roles/ec2/tasks/create-launch-template.yml': line 64, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

        user_email: "{{ tags['dev.contact'] }}"
    - shell: echo "{{  volume_size }}"
      ^ here
    We could be wrong, but this one looks like it might be an issue with
    missing quotes. Always quote template expression brackets when they
    start a value. For instance:

        with_items:
          - {{ foo }}

    Should be written as:

        with_items:
          - "{{ foo }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
