### ISSUE TITLE
Add notify_when option to task

### ISSUE THREAD

**Issue by nicolasbouchard-ubi** [ansible/ansible#80337]
### Summary

I think it would be useful in some case to have a way to control handler notification separately from `changed` value. By adding something like a `notify_when` property, we could provide our own logic. The default behavior would still be to check on the `changed` value if  `notify_when` is not used.

For example, if I use a module that return a `reboot_required` property, I could use it to control the reboot only if that property is `true`.

 I know that we can use `changed_when` (and it's what I do now), but altering the `changed_when` behavior is wrong in certain context. In the following example, the task will be flag as "OK" in the logs even if the software installation has been done but does not require a reboot.
 
```yaml
 - name: Install Software
  ansible.windows.win_package:
    path: C:\software.exe
    state: present
    provider: registry
    product_id: 1
  register: install_result
  notify: Reboot
  changed_when:
    - install_result.changed
    - install_result.reboot_required
```

### Issue Type

Feature Idea

### Component Name

notify, handlers

### Additional Information

```yaml (paste below)
- name: Install Software
  ansible.windows.win_package:
    path: C:\software.exe
    state: present
    provider: registry
    product_id: 1
  register: install_result
  notify: Reboot
  notify_when: install_result.reboot_required
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/galaxy/data/apb/handlers/main.yml.j2`](https://github.com/ansible/ansible/blob/devel/lib/ansible/galaxy/data/apb/handlers/main.yml.j2)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
You can do the notification in a separate task if you want the logic to be different than the normal change detection.

```yaml
- name: Install Software
  ansible.windows.win_package:
    path: C:\software.exe
    state: present
    provider: registry
    product_id: 1
  register: install_result

- name: Check whether reboot is required
  debug:
    msg: "{{ install_result.reboot_required }}"
  notify: Reboot
  changed_when:
    - install_result is changed
    - install_result.reboot_required
```
