### ISSUE TITLE
More general `ansible_managed` via variable

### ISSUE THREAD

**Issue by skwde** [ansible/ansible#80366]
### Summary

Problem & partial workaround:
Currently the only way to configure `ansible_managed` is via `ansible.cfg` which also only supports a fairly limited set of variables. (see <https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#synopsis> for details).

Currently we work around this by having a custom "`ansible_managed`" string like e.g.

```jinja
{{ ansible_managed }}: {{ ansible_role_name }}:{{ template_path }}
```

in our templates. This however no longer works once one relies on external roles / collections.
Another disadvantage here is if we decide to change the string we have to touch all templates.

There are several possible improvement:

1. It would be way more flexible to have another variable, e.g. called`ansible_managed`, available, which can be defined using the usual variable hierarchy. If not set it should default to the value derived via `ansible.cfg`.
2. An additional option to the `template` module, e.g. `ansible_managed_str`, which allows to overwrite `ansible_managed` string for the current template. Of course this could also be done with a `vars` block if `1.` is added.

### Issue Type

Feature Idea

### Component Name

template,special variables

### Additional Information

```yaml (paste below)
- name: Test
  hosts: localhost
  gather_facts: false
  # ## internal roles
  tasks:
    - name: Test template
      ansible.builtin.template:
        src: test.j2
        dest: /tmp/test.conf
        owner: root
        group: root
        mode: '0644'
  vars:
    - ansible_manged: 'my custom ansible managed string using various variables like {{ ansible_role_name }}'
   # ## external roles
  roles:
    # - role: fedora.linux-system-roles.sshd
    - role: willshersystems.sshd
      vars:
        - ansible_manged: 'another custom ansible managed string using various variables like {{ ansible_role_name }}'
```

With above suggestions this will give a custom `ansible_managed` string

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
