### ISSUE TITLE
assert module interprets variable content as jinja templete

### ISSUE THREAD

**Issue by alxgomz** [ansible/ansible#80387]
### Summary

using assert to check for some string before running the rest of the task I figured out that if the string contains `{{` the rest of the string will be evaluated as a template.
Of course if the mustaches are not close this triggers an error

### Issue Type

Bug Report

### Component Name

ansible.builtin.assert

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /Users/xxxxx/tmp/test/ansible/ansible.cfg
  configured module search path = ['/Users/xxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxxxx/.virtualenvs/ansible-latest/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/xxxxx/.virtualenvs/ansible-latest/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] (/Users/xxxxx/.virtualenvs/ansible-latest/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /Users/xxxxx/tmp/test/ansible/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/Users/xxxxx/tmp/test/ansible/ansible.cfg) = ['/Users/xxxxx/tmp/test/ansible/share/plugins/filter']
```

### OS / Environment

MacOSX & Linux

### Steps to Reproduce

```bash
ansible -m ansible.builtin.assert -a "that=somevar | length > 0" -esomevar="bla{{bla" localhost
```
or the task bellow:

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - ansible.builtin.assert:
        that:
          - somevar
```

### Expected Results

I expect the assertion to succeed if the variable is defined but instead it fails if the variable is a string containing opening mustaches

### Actual Results

```console
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: somevar=bla{{bla
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mkrizek** [comment]
This is expected and is not limited to the `assert` module. Variables can contain templates (e.g. nested variables) which can be further templated.

If you do not want the content of the variable to be templated, you can mark it as unsafe:
```yaml
- hosts: localhost
  gather_facts: false                                                                                                                                                                                                                          
  tasks:       
    - block:
      - debug:
          var: somevar
      - assert:
          that:
            - somevar | length > 0
      vars:
        somevar: !unsafe he{{o
```
