### ISSUE TITLE
register variable not available during ignore_errors evaluation

### ISSUE THREAD

**Issue by dchsueh** [ansible/ansible#80393]
### Summary

In general, variables are evaluated in an `ignore_errors` expression.  [Ansible error handling documentation](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_error_handling.html) has examples of the register result being used in `failed_when` and `changed_when`.  It seems inconsistent that register vars specifically are not available in `ignore_errors`, so I've filed this as a bug.

### Issue Type

Bug Report

### Component Name

ignore_errors

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_NOCOLOR(env: ANSIBLE_NOCOLOR) = True

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

VARS:
====
```

### OS / Environment

```
$ uname -a
Linux REDACTED_HOSTNAME 4.18.0-372.13.1.el8_6.x86_64 #1 SMP Mon Jun 6 15:05:22 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.6 (Ootpa)
```

### Steps to Reproduce

playbook:
```
---
- hosts: all:localhost
  name: test register variable use in ignore_errors conditional
  gather_facts: false
  vars:
    - ignore_the_error: True
  tasks:
    - name: sample command output
      shell: "echo failed ; exit 254"
      register: sample_command_result
      ignore_errors: "{{ ignore_the_error and sample_command_result.rc == 254 and 'ail' in sample_command_result.stdout }}"
#      ignore_errors: "{{ ignore_the_error }}"
```
command:
```
ansible-playbook test_register_ignore_errors.yml
```

### Expected Results

```
PLAY [test register variable use in ignore_errors conditional] *******************************************************************************************************************************

TASK [sample command output] *****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "echo failed ; exit 254", "delta": "0:00:00.004769", "end": "2023-04-04 13:57:36.033340", "msg": "non-zero return code", "rc": 254, "start": "2023-04-04 13:57:36.028571", "stderr": "", "stderr_lines": [], "stdout": "failed", "stdout_lines": ["failed"]}
...ignoring

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```

### Actual Results

```console
PLAY [test register variable use in ignore_errors conditional] *******************************************************************************************************************************

TASK [sample command output] *****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The field 'ignore_errors' has an invalid value, which includes an undefined variable. The error was: 'sample_command_result' is undefined\n\nThe error appears to be in '/home/REDACTED/git/test_register_ignore_errors.yml': line 8, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: sample command output\n      ^ here\n"}
...ignoring

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`test/integration/targets/ignore_errors/aliases`](https://github.com/ansible/ansible/blob/devel/test/integration/targets/ignore_errors/aliases)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
One of the issues here, is that `ignore_errors` is not a conditional, like `when`, and as such it requires use of `{{ }}` and does not utilize deferred templating.  As such, `ignore_errors` must be able to template prior to the task executing.

The only way to reliably make it support use of the return value, would be to make it act like `when`, which would probably cause more issues than it solves because of current uses. Simply preventing it from being templated during `post_validate` would be misleading, since any deferred templating like that is normally done by not accepting an actual template in the first place.

A work around for this would be some form of `block/rescue` functionality:

```yaml
    - block:
        - name: sample command output
          shell: "echo failed ; exit 254"
          register: sample_command_result
      rescue:
        - fail:
            msg: '{{ sample_command_result }}'
          when: not (ignore_the_error and sample_command_result.rc == 254 and 'ail' in sample_command_result.stdout)
```
