### ISSUE TITLE
connection: local and delegate_to not working together 

### ISSUE THREAD

**Issue by reddyblokesh** [ansible/ansible#80405]
### Summary

I am using a playbook which is calling another role but when i am using delegate_to: remote_machine its still executing on localhost

ansible playbook : 
```
---
- name: test 
  hosts: webservers
  connection: local
  gather_facts: false
  roles:
    - role: raw
```

ROLE: 
```
- name: set fact for delegate
  set_fact:
    remote: "{{ inventory_hostname }}"

- name: check the hostname 
  delegate_to: remote
  command: hostname -f
  register: sec 
```
 In the output I see the hostname of my localhost on which i am running the playbook and not the webserver host (remote machine) on which ideally the task should have run 

### Issue Type

Bug Report

### Component Name

delegate_to, connection: local 

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.12]
  config file = None
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 
  jinja version = 3.0.3
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

centos 7

### Steps to Reproduce

```yaml (paste below)
---
- name: test 
  hosts: webservers
  connection: local
  gather_facts: false
  roles:
    - role: raw
```

ROLE: 
```
- name: set fact for delegate
  set_fact:
    remote: "{{ inventory_hostname }}"

- name: check the hostname 
  delegate_to: remote
  command: hostname -f
  register: sec
```

### Expected Results

it should have ideally printed the hostname of the remote machine but in my case it printed the hostname of localhost it prin

### Actual Results

```console
it printed the hostname of localhost
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
