### ISSUE TITLE
list concatenation using "set_fact" and "with_items" not working (regression)

### ISSUE THREAD

**Issue by unicode-it** [ansible/ansible#80404]
### Summary

Loops with set_fact do not behave like they used to. Unless this change is intended or documented somewhere, it is a regression. Maybe it is related to breaking changes with jinja3.

### Issue Type

Bug Report

### Component Name

core, jinja

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.2]
  config file = /home/xxx/xxx/ansible.cfg
  configured module search path = ['/home/user/xxx']
  ansible python module location = /home/xxx/xxx
  ansible collection location = /home/user/xxx/collections
  executable location = /home/xxx/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/xxx/bin/python)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
(unrelated)
```

### OS / Environment

Debian bullseye

### Steps to Reproduce

Vars:
```yaml
shares:
  - name: something
    type: nfs4
    from:
      nfs_server:
        path: /export/recordings/unpublished
        options: "rw,sync,no_root_squash,no_subtree_check"
    to:
      nfs_client1:
        path: /some/folder/
        opts: rw,auto,nofail
      nfs_client2:
        path: /some/folder/
        opts: rw,auto,nofail
```

Task:
```yaml 
- name: create vars for nfs role
  set_fact:
    nfs_exports: "{{ nfs_exports | default([]) }} + [ '/share/{{item.from[ansible_host].path.split('/')[-1]}}      {% for client in item.to | default([]) %}{{ips_intern[client]}} {% endfor %}{% for host in item.from[ansible_host].hosts | default([]) %}{{host}}({{item.from[ansible_host].options}}) {% endfor %}']"
  with_items: "{{shares}}"
  when:
    - "'nfs_servers' in group_names"
    - "ansible_host in item.from"
    - "item.from[ansible_host].hosts is defined"

```

### Expected Results

"nfs_exports": ['/share      fd75:5a92:ipv6 fd75:5a92:ipv6 ', '/share      fd75:5a92:ipv6 fd75:5a92:ipv6 ']

### Actual Results

```console
"nfs_exports": "[] + ['/share      fd75:5a92:ipv6 fd75:5a92:ipv6 '] + ['/share      fd75:5a92:ipv6 fd75:5a92:ipv6 ']"

```
Since update to this ansible Version a string is generated. Concat of lists does not work any more. With {{ nfs_exports | default([]) | list }} it works as expected, but the list filter breaks the wrong interpretated string into single characters: ["[", "]"]

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
