### ISSUE TITLE
Unable to edit files in AFS mount path using ansible code (win_lineinfile module) from windows VM

### ISSUE THREAD

**Issue by parthadas-1986** [ansible/ansible#80471]
### Summary

The Azure File Share is successfully mounted on the Windows VM (Windows Server 2019 Datacenter), and required permissions are added as per Microsoft document. But whenever we are trying to update any file with in the share path using ansible code(win_lineinfile), we are getting "File path does not exists" error. But in the same VM we are ale to edit file in other physical disk. Although we are able manually update file in AFS path, only via ansible it is not working. Please note, We are running the ansible code from Control node (i.e. A Linux vm in same vnet and same region)

### Issue Type

Bug Report

### Component Name

win_lineinfile

### Ansible Version

```console
$ ansible --version
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/home/admin_accenture/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  ansible collection location = /home/admin_accenture/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  jinja version = 2.10.1
  libyaml = False
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

Windows 2019 Datacenter

### Steps to Reproduce

```yaml (paste below)
- name: windows mssql install
  hosts: mssql  
  gather_facts: yes  
  tasks:    
    - name: Edit Default.PFL file(Profile Edit)
      win_lineinfile:
        #path: \saptest12.file.core.windows.net\sapmnt\TEST\DEFAULT.PFL.txt
        path: Y:\TEST\DEFAULT.PFL.txt        
        regex: "{{ item.from }}"
        line: "{{ item.to }}"
        remote_src: true
      with_items: 
        - { from: '^SAPDBHOST ='  , to: 'SAPDBHOST = windows' } 
```

### Expected Results

I am expecting, code should update DEFAULT.PFL.txt file.

### Actual Results

```console
Code is throwing error saying, the Path does not exists.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
