### ISSUE TITLE
"the connection plugin 'ssh' was not found" error in the middle of the playbook

### ISSUE THREAD

**Issue by josephkishan** [ansible/ansible#80516]
### Summary

when we were trying to run tasks in a playbook suddenly we got an error like "the connection plugin 'ssh' was not found\\" at one of the tasks. The previous task of this task will take time from 10-15 minutes to complete and start this task where an error is happening. First, we thought about the timeout issue and tried ansible_timeout and also other options like updating option in ansible.cfg file like timeout and persistcentrol:60m. But it did not help us in solving. Can you please help me resolve this issue

### Issue Type

Bug Report

### Component Name

ssh connection

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.13 (main, Nov 16 2022, 15:31:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment
```
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
```
### Steps to Reproduce
```
- name: Uninstall MCP
  command: "/bin/bash -c 'yes | ./uninstall.sh'"
  register: uninstall_result
  until: uninstall_result.stdout_lines
  retries: 30
  delay: 10
  when: file_details.stat.exists
  failed_when: ("Uninstall Successful." not in uninstall_result.stdout)

- name: Checking directory after uninstall
  stat:
    path: /tmp/*
  register: keys_folder_details
  failed_when: keys_folder_details.stat.exists

```

### Expected Results

System should execute the next task succesfully

### Actual Results

```console
Displaying "the connection plugin 'ssh' was not found" error
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
