### ISSUE TITLE
Strategy: offset_time

### ISSUE THREAD

**Issue by git-cgallagher** [ansible/ansible#80519]
### Summary

My suggestion would be to introduce a new strategy plugin that is essentially an extension to the free plugin that supports an offset as defined by the user. Could be in ms, sec, min.

Existing free plugin for reference: https://github.com/ansible/ansible/blob/1998521e2d5b89bc53d00639bad178330ebb98df/lib/ansible/plugins/strategy/free.py

Use case:
Working in a heavy windows and vsphere environment, I often see task failures when running against a group of hosts that have the same target. Two examples of this would be:
1. Building multiple VMs as defined in group inventory. vSphere guest customization fails without notice because the UUIDs match on the 2 VMs that were created at exactly the same time.
2. Two play hosts in a group delegate to a management server in order to find the closest domain controller. In simultaneous sessions such as this, we often see failures that are generic in nature. Replaying the task often works fine.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.time_offset strategy

### Additional Information

```yaml (paste below)
- hosts: all
  strategy: time_offset
  strategy_opts:
    seconds: "{{ 10 | random }}"
  tasks:
    - name: Example task
      ansible.builtin.debug:
        msg: "Each host will finish with a random offset within 10 seconds of one another."
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
