### ISSUE TITLE
include_vars module, hash_behaviour merge

### ISSUE THREAD

**Issue by rodlilearns** [ansible/ansible#80522]
### Summary

I am trying to implement configuration as code for Red Hat Satellite, and want to use separate variable files for configuration.

When I try to merge three variable files with the include_vars module, I get an unexpected/undesired result.

### Issue Type

Bug Report

### Component Name

include_vars module

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.3]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

COLLECTIONS_PATHS(/project_dir/ansible.cfg) = ['/project_dir/collections']
CONFIG_FILE() = /project_dir/ansible.cfg
DEFAULT_ASK_VAULT_PASS(/project_dir/ansible.cfg) = True
DEFAULT_BECOME(/project_dir/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/project_dir/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/project_dir/ansible.cfg) = root
DEFAULT_HOST_LIST(/project_dir/ansible.cfg) = ['/project_dir/inventory.ini']
DEFAULT_ROLES_PATH(/project_dir/ansible.cfg) = ['/project_dir/{{ ANSIBLE_HOME ~ "./roles', '/>
DEFAULT_STDOUT_CALLBACK(/project_dir/ansible.cfg) = yaml
GALAXY_SERVER_LIST(/project_dir/ansible.cfg) = ['automation_hub', 'galaxy']
RETRY_FILES_ENABLED(/project_dir/ansible.cfg) = False
```

### OS / Environment

NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation

### Steps to Reproduce

```yaml (paste below)
---
- name: test playbook
  hosts: localhost
  vars_files:
    - group_vars/test/organizations.yml
    - group_vars/test/locations.yml
    - group_vars/test/domains.yml

  tasks:

    - name: include variables
      include_vars:
        dir: group_vars/test
        hash_behaviour: merge

    - name: debug satellite foreman var
      ansible.builtin.debug:
        var: satellite.foreman
```

`cat /group_vars/text/organizations.yml`
```yaml (paste below)
---
satellite:
  foreman:
    organizations:
      - name: 'org1'
        initial_organization: true
```

`cat /group_vars/text/locations.yml`
```yaml (paste below)
---
satellite:
  foreman:
    locations:
      - name: "location1"
        state: present
        organizations:
          - "org1"
      - name: "location2"
        state: present
        organizations:
          - "org1"
        domains:
          - "domain1"
```

`cat /group_vars/text/domains.yml`
```yaml (paste below)
---
satellite:
  foreman:
    domains:
      - name: 'domain1'
        description: 'description'
        organizations:
          - 'org1'
        locations:
          - 'loc1'
          - 'loc2'
          - 'loc3'
```

Command to run playbook:
`$ ansible-playbook test.yml`

### Expected Results

I expect all three variable files to be merged, so that when I debug the `satellite.foreman` variable, I get `satellite.foreman.organizations`, `satellite.foreman.locations`, and `satellite.foreman.domains`.

PLAY [test playbook] *************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [localhost]

TASK [include variables] *********************************************************************************************************************
ok: [localhost]

TASK [debug satellite foreman var] ***********************************************************************************************************
ok: [localhost] => 
  satellite.foreman:
    domains:
    - description: description
      locations:
      - loc1
      - loc2
      - loc3
      name: domain1
      organizations:
      - org1
    locations:
      - name: location1
        state: present
        organizations:
          - org1
      - name: location2
         state: present
         organizations:
           - org1
         domains:
           - name: domain1
    organizations:
    - initial_organization: true
      name: org1

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

### Actual Results

```console
The actual result in that when I debug the `satellite.foreman` variable, I get `satellite.foreman.organizations` and `satellite.foreman.domains` only. The `satellite.foreman.locations` variable is not defined, suggesting that it has not been merged.

PLAY [test playbook] *************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [localhost]

TASK [include variables] *********************************************************************************************************************
ok: [localhost]

TASK [debug satellite foreman var] ***********************************************************************************************************
ok: [localhost] => 
  satellite.foreman:
    domains:
    - description: description
      locations:
      - loc1
      - loc2
      - loc3
      name: domain1
      organizations:
      - org1
    organizations:
    - initial_organization: true
      name: org1

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
Note that the reason it appears to partially work is that you're loading the same files at least twice, maybe three times (depending on whether `localhost` is a member of the `test` group.)

First, the intended use of `group_vars` is to automatically apply to hosts in the corresponding group (in this case, `test`). Files are loaded in lexical order, so the declaration in `group_vars/test/organizations.yml` wins.

Second, `vars_files` loads the three files in the order specified, so the declaration in `group_vars/test/domains.yml` wins.

Third, `include_vars` loads the files in lexical order again, so the declaration in `group_vars/test/organizations.yml` wins, and is merged with the existing value from `group_vars/test/domains.yml`.

```yaml
- hosts: localhost
  tasks:
    - name: debug var before vars_files
      ansible.builtin.debug:
        var: satellite.foreman

- hosts: localhost
  vars_files:
    - group_vars/test/organizations.yml
    - group_vars/test/locations.yml
    - group_vars/test/domains.yml

  tasks:
    - name: debug var before include
      ansible.builtin.debug:
        var: satellite.foreman

    - name: include variables
      include_vars:
        dir: group_vars/test
        hash_behaviour: merge

    - name: debug satellite foreman var
      ansible.builtin.debug:
        var: satellite.foreman
```

```
PLAY [localhost] ***************************************************************

TASK [debug var before vars_files] *********************************************
ok: [localhost] =>
    satellite.foreman:
        organizations:
        -   initial_organization: true
            name: org1

PLAY [localhost] ***************************************************************

TASK [debug var before include] ************************************************
ok: [localhost] =>
    satellite.foreman:
        domains:
        -   description: description
            locations:
            - loc1
            - loc2
            - loc3
            name: domain1
            organizations:
            - org1

TASK [include variables] *******************************************************
ok: [localhost]

TASK [debug satellite foreman var] *********************************************
ok: [localhost] =>
    satellite.foreman:
        domains:
        -   description: description
            locations:
            - loc1
            - loc2
            - loc3
            name: domain1
            organizations:
            - org1
        organizations:
        -   initial_organization: true
            name: org1
```

**Comment by rodlilearns** [comment]
Thank you @s-hertel and @flowerysong.
I made a change to the playbook, using loop and it produced a desired result this time.
I misunderstood how to use the hash_behaviour works, and so this is a non-issue.
I'll paste the new playbook and its output.

**New playbook:**

```
---
- name: test playbook
  hosts: localhost

  tasks:

    - name: include variables
      include_vars:
        file: "{{ item }}"
        hash_behaviour: merge
      loop:
        - group_vars/test/organizations.yml
        - group_vars/test/locations.yml
        - group_vars/test/domains.yml

    - name: debug satellite foreman var
      ansible.builtin.debug:
        var: satellite.foreman
```
        
**Output:**

```
PLAY [test playbook] ***********************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [include variables] *******************************************************
ok: [localhost] => (item=group_vars/test/organizations.yml)
ok: [localhost] => (item=group_vars/test/locations.yml)
ok: [localhost] => (item=group_vars/test/domains.yml)

TASK [debug satellite foreman var] *********************************************
ok: [localhost] => 
  satellite.foreman:
    domains:
    - description: description
      locations:
      - loc1
      - loc2
      - loc3
      name: domain1
      organizations:
      - org1
    locations:
    - name: location1
      organizations:
      - org1
      state: present
    - domains:
      - domain1
      name: location2
      organizations:
      - org1
      state: present
    organizations:
    - initial_organization: true
      name: org1

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
