### ISSUE TITLE
Examples section in adjacent module documentation fails to parse

### ISSUE THREAD

**Issue by E1k3** [ansible/ansible#80534]
### Summary

When adding an EXAMPLES section (see below) to an adjacent (sidecar) documentation YAML file, `ansible-doc` failes to parse the documentation.

When I use the same EXAMPLES section as a string inside a python module, `ansible-doc` works without error.

### Issue Type

Bug Report

### Component Name

bin/anible-doc

### Ansible Version

```console
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/redacted/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Archlinux

    $ uname -r
    6.2.9-arch1-1

### Steps to Reproduce

Examples section in sidecar:
```yaml
EXAMPLES:
  - name: Foo
    rcx_one.foo.bar:
      base_dir: "~"
      overlay_dir: "~/files"
      backup_dir: "~/backup"
      conflict: replace
```

Examples section in module:
```python
EXAMPLES = """
- name: Foo
  rcx_one.foo.bar:
    base_dir: '~'
    overlay_dir: ~/files
    backup_dir: ~/backup
    conflict: replace
"""
```

Run `ansible-doc -t module rcx_one.foo.bar`

### Expected Results

```
[...]
EXAMPLES:

- name: Foo
  rcx_one.foo.bar:
    base_dir: '~'
    overlay_dir: ~/files
    backup_dir: ~/backup
    conflict: replace
[...]
```

### Actual Results

```console
In case of the Python module, the results are as expected.
In case of the sidecar docs:

ERROR! Unable to retrieve documentation from 'linkoverlay' due to: Unable to parse examples section. ('cannot represent an object', [{'name': 'Foo', 'rcx_one.foo.bar': {'base_dir': '~', 'overlay_dir': '~/dotfiles', 'backup_dir': '~/dotfile_backup', 'conflict': 'replace'}}]). Unable to parse examples section. ('cannot represent an object', [{'name': 'Overlay dotfiles', 'rcx_one.linkoverlay.linkoverlay': {'base_dir': '~', 'overlay_dir': '~/files', 'backup_dir': '~/backup', 'conflict': 'replace'}}])
```
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by sivel** [comment]
The problem is formatting.  `EXAMPLES` is plain text, but in your YAML you did not indicate as such, instead it becomes a list.

You need to add a `|` such as:

```yaml
EXAMPLES: |
  - name: Foo
    rcx_one.foo.bar:
      base_dir: "~"
      overlay_dir: "~/files"
      backup_dir: "~/backup"
      conflict: replace
```
