### ISSUE TITLE
WinRM winrshost processes hanging after playbook run finishes

### ISSUE THREAD

**Issue by blami** [ansible/ansible#80532]
### Summary

After successful run _a lot_ (literally hundred or so) of `winrshost` processes are seen hanging in Windows Task Manager. Multiple plays of same playbook end up failing as WinRM server starts returning 500 or not even being reachable (likely exhaustion of some limit of processes).

Authentication is done using certificate and transport is HTTPS listener with self-signed certificate. Target nodes are Windows 11 22H2 and source host running ansible is Ubuntu 22.04.2. Playbook utilizes `become` using `runas` method to overcome issue with double-hop (become to same non-domain local user).

I noticed the problem starts when running tasks imported from role (doesn't appear at top of playbook) and gets worse if there's `block` or loop (`with_items`) inside the role task(s). But that might be just coincidence. 

Problem seems to appear since upgrade to PPA version 12.14.4, to remediate I rolled back to OS version which is 2.10.8

### Issue Type

Bug Report

### Component Name

winrm

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/blami/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/blami/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
# EMPTY (no configuration changes)
```

### OS / Environment

Ubuntu 22.04.2 / Windows 11 22H2

### Steps to Reproduce

```yaml (paste below)
  win_package:
    product_id: "{{ item }}"
    state: absent
  with_items:
    - Clipchamp.Clipchamp
    - DolbyLaboratories.DolbyAccess
    - Microsoft.3DBuilder
    - Microsoft.WindowsAlarms
    - Microsoft.windowscommunicationsapps
    - Microsoft.Windows.Photos
    - Microsoft.Todos
    - Microsoft.ScreenSketch
    - Microsoft.MicrosoftOfficeHub              # Get Office 365
    - Microsoft.BingNews
    - Microsoft.BingWeather
    - Microsoft.BingFinance
    - Microsoft.BingHealthAndFitness
    - Microsoft.BingFoodAndDrink
    - Microsoft.BingSports
    - Microsoft.BingTravel
    - Microsoft.WindowsMaps
    - Microsoft.ZuneMusic                       # Groove Music
    - Microsoft.ZuneVideo                       # Movies & TV
    - Microsoft.YourPhone                       # Phone Companion
    - Microsoft.WindowsPhone                    # Phone Companion
    - Microsoft.OneConnect                      # Paid Wifi & Cellular
    - Microsoft.Getstarted
    - Microsoft.GetHelp
    - Microsoft.MicrosoftSolitaireCollection
    - Microsoft.OneDriveSync                    # OneDrive
    - MicrosoftTeams
    - Microsoft.549981C3F5F10                   # Cortana
    - OneDriveSetup.exe                         # OneDrive
```

### Expected Results

When role with block containing task above finishes and ansible playbook ends, I expect there are no ansible related winrshost processes hanging.

### Actual Results

```console
There is about 100 hanging winrshost processes visible in Task Manager.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/plugins/connection/winrm.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/winrm.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by blami** [comment]
Hi, I had some time to debug this a bit more and I think I know the root cause of that behavior.

In my playbook running on Linux (WSL on Windows - should not matter) I have `add_host` that runs if WSL detected and adds the _host_ of WSL (Windows side of it) to hosts dynamically. Now, `add_host:` looked like this:

``` yml
- name: Adding localhost To Windows Hosts
  add_host:
    ansible_connection: winrm
    # NOTE: DO NOT use just 'localhost' as it would override Linux 'localhost'
    hostname: localhost.windows
    ansible_winrm_host: "{{ wsl_hostip }}"
    ansible_winrm_transport: certificate
    ansible_winrm_cert_pem: "/path/to/client.crt"
    ansible_winrm_cert_key_pem: "/path/to/client.key"
    ansible_winrm_server_cert_validation: ignore
    ansible_become_method: runas
    groups: windows
  when:
    - my_facts.can_winrm
    - my_facts.is_wsl
```

The problem is `hostname:` being set to faux (non-resolvable) host name _localhost.windows_ to avoid _localhost_ that would override WSL2 localhost. Even _localhost_ would not work as it would resolve to WSL2 127.0.0.1 and not HyperV bridging private range IP of Windows host (e.g. `172.31.16.1` stored in `wsl_hostip` in my playbook and used correctly as `ansible_winrm_host:` .

This will work fine but it will cause condition https://github.com/ansible/ansible/blob/0830b6905996fb02eefcba79a9b055961e251078/lib/ansible/executor/task_executor.py#L580
evaluate as `"localhost.windows" == "172.31.16.1"` which is obviously `false` as `localhost.windows` cannot be resolved at all. In case this is loop task using e.g. `with_items:` this will spawn new WinRM connection for each iteration leaving previous WinRM connection lingering unclosed. Only last connection will be closed properly here
https://github.com/ansible/ansible/blob/0830b6905996fb02eefcba79a9b055961e251078/lib/ansible/executor/task_executor.py#L204

I tested my hypothesis and set `hostname: "{{ wsl_hostip }}"` and the connection was properly reused.

While this was mainly problem in my playbook I still believe there is a bug with lingering connection. Fix to that I see would be to attempt to close connection if there's any before creating new one here
https://github.com/ansible/ansible/blob/0830b6905996fb02eefcba79a9b055961e251078/lib/ansible/executor/task_executor.py#L581
That way at least there would not be leak (but still playbook will run sub-optimally not reusing same connection for all iterations). 

I am happy to prepare patch if this sounds logical (this was my first dive into Ansible codebase so guidance is welcome).

**Comment by blami** [comment]
Minmal playbook to reproduce the issue (requires Windows host with WinRM setup and to be changed accordingly):

``` yml
---

- name: Setup To Reproduce Bug \#80532
  hosts: localhost
  tasks:
    - add_host:
        ansible_connection: winrm
        hostname: faux.hostname
        ansible_winrm_host: <existing IP or hostname>
        ansible_winrm_transport: certificate
        ansible_winrm_cert_pem: <path to pem>
        ansible_winrm_cert_key_pem: <path to key>
        ansible_winrm_server_cert_validation: ignore
        # NOTE: Empty become password set using -K as it won't work on Windows
        # anyway and local user is expected to have at least Administrator role.
        groups: windows

- name: Reproduce Bug \#80532
  hosts: windows
  tasks:
    - win_stat:
        path: "{{ item }}"
      with_items:
        - "C:\\Windows"
        - "C:\\Windows\\System32"
        - "C:\\Windows\\System"
```
Once run with current devel checkout it leaves two `winrshost.exe` processes holding connection (for items `C:\\Windows` and `C:\\Windows\\System32`) lingering.
