### ISSUE TITLE
iptables builtin module does not include `--set-mark` and `--set-dscp-mark` fails

### ISSUE THREAD

**Issue by Aethylred** [ansible/ansible#80562]
### Summary

I am trying to create an iptable rule to mark packets using `--set-mark` using `ansible.builtin.iptables`

The command line I'm trying to replicate is:
```
iptables -t mangle -A DIVERT -j MARK --set-mark 1
```

I expected that the iptable Ansible code would be:

```
- name: Configure iptables
  ansible.builtin.iptables:
    table: mangle
    chain: DIVERT
    jump: MARK
    set-mark: 1
```

I tried using the `set-dcsp` flag but the installe version of iptables does not support it: 
```
failed: [testhost01] (item={'table': 'mangle', 'chain': 'DIVERT', 'jump': 'MARK', 'set_dscp_mark': 1}) => changed=false 
  ansible_loop_var: item
  cmd: /sbin/iptables -t mangle -A DIVERT -j MARK --set-dscp 1
  item:
    chain: DIVERT
    jump: MARK
    set_dscp_mark: 1
    table: mangle
  msg: |-
    iptables v1.8.4 (nf_tables): unknown option "--set-dscp"
    Try `iptables -h' or 'iptables --help' for more information.
  rc: 2
  stderr: |-
    iptables v1.8.4 (nf_tables): unknown option "--set-dscp"
    Try `iptables -h' or 'iptables --help' for more information.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

### Issue Type

Bug Report

### Component Name

iptables

### Ansible Version

```console
> ansible --version
ansible [core 2.13.8]
  config file = /home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg
  configured module search path = ['/home/hicksaw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/hicksaw/ansible/gitlab-15-ansible/venvs/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/hicksaw/ansible/gitlab-15-ansible/ignore/collections
  executable location = /home/hicksaw/ansible/gitlab-15-ansible/venvs/ansible/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
> ansible-config dump --only-changed -t all
CACHE_PLUGIN(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ignore/facts_cache
CALLBACKS_ENABLED(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['profile_tasks', 'log_plays']
COLLECTIONS_PATHS(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['/home/hicksaw/ansible/gitlab-15-ansible/ignore/collections']
DEFAULT_GATHERING(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = smart
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['/home/hicksaw/ansible/gitlab-15-ansible/ignore/roles']
DEFAULT_STDOUT_CALLBACK(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = 60
DEFAULT_VAULT_IDENTITY_LIST(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['.vault_password']
DISPLAY_SKIPPED_HOSTS(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = False
[hicksaw@hpcwansible01:~/ansible/gitlab-15-ansible] [ansible] develop(+68/-5) ± 
> ansible-config dump --only-changed
CACHE_PLUGIN(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ignore/facts_cache
CALLBACKS_ENABLED(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['profile_tasks', 'log_plays']
COLLECTIONS_PATHS(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['/home/hicksaw/ansible/gitlab-15-ansible/ignore/collections']
DEFAULT_GATHERING(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = smart
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['/home/hicksaw/ansible/gitlab-15-ansible/ignore/roles']
DEFAULT_STDOUT_CALLBACK(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = 60
DEFAULT_VAULT_IDENTITY_LIST(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ['.vault_password']
DISPLAY_SKIPPED_HOSTS(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN_CONNECTION(/home/hicksaw/ansible/gitlab-15-ansible/ansible.cfg) = ignore/inventory_cache
```

### OS / Environment

Rocky 8

### Steps to Reproduce

```
- name: Configure iptables with set-mark
  ansible.builtin.iptables:
    table: mangle
    chain: DIVERT
    jump: MARK
    set-mark: 1

- name: Configure iptables with set-dscp-mark
  ansible.builtin.iptables:
    table: mangle
    chain: DIVERT
    jump: MARK
    set-dscp-mark: 1
```

### Expected Results

I expected the `iptables` module to support the `--set-mark` argument for the `iptables` command

### Actual Results

```console
failed: [testhost01] (item={'table': 'mangle', 'chain': 'DIVERT', 'jump': 'MARK', 'set_dscp_mark': 1}) => changed=false 
  ansible_loop_var: item
  cmd: /sbin/iptables -t mangle -A DIVERT -j MARK --set-dscp 1
  item:
    chain: DIVERT
    jump: MARK
    set_dscp_mark: 1
    table: mangle
  msg: |-
    iptables v1.8.4 (nf_tables): unknown option "--set-dscp"
    Try `iptables -h' or 'iptables --help' for more information.
  rc: 2
  stderr: |-
    iptables v1.8.4 (nf_tables): unknown option "--set-dscp"
    Try `iptables -h' or 'iptables --help' for more information.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by Aethylred** [comment]
Updated because no only does `iptables` not do what I want, the other thing I tried failed.

**Comment by Aethylred** [comment]
As order is important with `iptables` the workaround is horrible:
```
- name: Configure iptables I
      ansible.builtin.iptables:
        chain: "{{ item.chain | default(omit) }}"
        table: "{{ item.table | default(omit) }}"
        chain_management: "{{ item.chain_management | default(omit) }}"
        protocol: "{{ item.protocol | default(omit) }}"
        match: "{{ item.match | default(omit) }}"
        jump: "{{ item.jump | default(omit) }}"
        set_mark: "{{ item.set_mark | default(omit) }}"
        state: "{{ item.state | default(omit) }}"
      become: true
      loop:
        - chain: DIVERT
          table: mangle
          chain_management: true
        - table: mangle
          chain: PREROUTING
          protocol: tcp
          match: socket
          jump: DIVERT
        # MARK & --set-mark not yet supported by ansible.builtin.iptables https://github.com/ansible/ansible/issues/80562
        # - table: mangle
        #   chain: DIVERT
        #   jump: MARK
        #   set_mark: 1
        # because order is important
        # - table: mangle
        # chain: DIVERT
        # jump: ACCEPT

    - name: Check for MARK rule
      ansible.builtin.shell: # noqa: no-changed-when
        cmd: "iptables -t mangle -L | grep 'MARK       all  --  anywhere             anywhere             MARK set 0x1'"
      become: true
      register: haproxy_mark_check
      failed_when: false
      ignore_errors: true
      changed_when: false

    - name: MARK iptables
      ansible.builtin.shell:
        cmd: iptables -t mangle -A DIVERT -j MARK --set-mark 1
      become: true
      when: haproxy_mark_check.rc != 0

    - name: Configure iptables II
      ansible.builtin.iptables:
        chain: "{{ item.chain | default(omit) }}"
        table: "{{ item.table | default(omit) }}"
        chain_management: "{{ item.chain_management | default(omit) }}"
        protocol: "{{ item.protocol | default(omit) }}"
        match: "{{ item.match | default(omit) }}"
        jump: "{{ item.jump | default(omit) }}"
        set_mark: "{{ item.set_mark | default(omit) }}"
        state: "{{ item.state | default(omit) }}"
      become: true
      loop:
        - table: mangle
          chain: DIVERT
          jump: ACCEPT
```
