### ISSUE TITLE
meta/argument_spec.yml not validating against types correctly.

### ISSUE THREAD

**Issue by michaeljones256** [ansible/ansible#80571]
### Summary

Hello! My team is wanting to implementing the role argument validation found [here](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation). However after some testing I have noticed that the type validation seems to be off. 

### Issue Type

Bug Report

### Component Name

argument_spec

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.1]
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

macOs

### Steps to Reproduce

default/main.yml

```
---
variable_test: false
```
meta/argument_spec.yml
```
---

argument_specs:
  main:
    short_description: The main entry point for the role.
    options:
      variable_test:
        type: float
        required: false
```

or 

default/main.yml
```
---
variable_test: 4
```
meta/argument_spec.yml
```
---

argument_specs:
  main:
    short_description: The main entry point for the role.
    options:
      variable_test:
        type: string
        required: false
```

**However** when I try this. I get an error because "type <class 'ansible.parsing.yaml.objects.AnsibleUnicode'> and we were unable to convert to int" 

default/main.yml
```
---
variable_test: 'some text'
```
meta/argument_spec.yml
```
---

argument_specs:
  main:
    short_description: The main entry point for the role.
    options:
      variable_test:
        type: int
        required: false
```

I see that Ansible is trying to convert the type to the one specified in`meta/argument.yml` but should this be the desired functionality? This would then be more of a documentation feature then a validation?

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
