### ISSUE TITLE
GPG Key not excepted using - rpm_key & yum

### ISSUE THREAD

**Issue by satellite-no** [ansible/ansible#80583]
### Summary

I have a role that installed vector.dev which was working on an older version of ansible since upgrading to `2.13.6` and `2.14.4` this role no longer works.  With the below error
```bash
HOSTNAME | FAILED! => {
    "changed": false,
    "msg": "No package matching 'vector' found available, installed or updated",
    "rc": 126,
    "results": [
        "No package matching 'vector' found available, installed or updated"
    ]
}
```

Logging into the host and running `sudo yum install vector` i get the below prompt.
```bash
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                    | 3.7 kB  00:00:00
timber-vector/x86_64/signature                                                                                |  488 B  00:00:00
Retrieving key from https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
Importing GPG key 0x0A2BC4B8:
 Userid     : "Cloudsmith Package (timber/vector) <support@cloudsmith.io>"
 Fingerprint: 1e46 c153 e9ef a240 18c3 6f75 3543 db2d 0a2b c4b8
 From       : https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
Is this ok [y/N]: n
```

### Issue Type

Bug Report

### Component Name

rpm_key, yum

### Ansible Version

```console
$ ansible --version
tested with `2.13.6` and `2.14.4`
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

(py39venv-ansible-latest) [ansible@ansible ansible]$ ansible-config dump --only-changed -t all
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This
feature will be removed from ansible-core in version 2.15. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
CACHE_PLUGIN(/opt/dev/satellite-no/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/opt/dev/satellite-no/ansible/ansible.cfg) = /opt/ansible/fact_cache
CACHE_PLUGIN_TIMEOUT(/opt/dev/satellite-no/ansible/ansible.cfg) = 43200
CALLBACKS_ENABLED(/opt/dev/satellite-no/ansible/ansible.cfg) = ['community.general.splunk']
CONFIG_FILE() = /opt/dev/satellite-no/ansible/ansible.cfg
DEFAULT_FORKS(/opt/dev/satellite-no/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/opt/dev/satellite-no/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/opt/dev/satellite-no/ansible/ansible.cfg) = ['/opt/ansible/inventories']
DEFAULT_STDOUT_CALLBACK(/opt/dev/satellite-no/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/opt/dev/satellite-no/ansible/ansible.cfg) = /opt/ansible/vault-env.py
HOST_KEY_CHECKING(/opt/dev/satellite-no/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/opt/dev/satellite-no/ansible/ansible.cfg) = auto_silent
RETRY_FILES_ENABLED(/opt/dev/satellite-no/ansible/ansible.cfg) = False

CACHE:
=====

jsonfile:
________
_timeout(/opt/dev/satellite-no/ansible/ansible.cfg) = 43200
_uri(/opt/dev/satellite-no/ansible/ansible.cfg) = /opt/ansible/fact_cache

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/opt/dev/satellite-no/ansible/ansible.cfg) = False

ssh:
___
host_key_checking(/opt/dev/satellite-no/ansible/ansible.cfg) = False
pipelining(/opt/dev/satellite-no/ansible/ansible.cfg) = True
reconnection_retries(/opt/dev/satellite-no/ansible/ansible.cfg) = 3
```

### OS / Environment

```bash
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

### Steps to Reproduce

```yaml
- name: Import a Vector repo key
  ansible.builtin.rpm_key:
    state: present
    fingerprint: "1e46 c153 e9ef a240 18c3 6f75 3543 db2d 0a2b c4b8"
    key: 'https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key'
  become: yes

- name: Add Vector repo for YUM
  ansible.builtin.get_url:
    url: 'https://repositories.timber.io/public/vector/config.rpm.txt?distro=el&codename=7'
    dest: '/etc/yum.repos.d/timber-vector.repo'
  become: yes
  when:
    - ansible_pkg_mgr == 'yum'

- name: Install Vector using yum
  ansible.builtin.yum:
    name: vector
    state: present
    disable_gpg_check: yes
  become: yes
  when:
    - ansible_pkg_mgr == "yum"
```

### Expected Results

YUM module installed successfully

### Actual Results

```console
idx1.cert1.opsenglab.deepwatch.com | FAILED! => {
    "changed": false,
    "msg": "No package matching 'vector' found available, installed or updated",
    "rc": 126,
    "results": [
        "No package matching 'vector' found available, installed or updated"
    ]
}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
