### ISSUE TITLE
Ephemeral mount point is not idempotent

### ISSUE THREAD

**Issue by paulo-dev-xpectral** [ansible/ansible#80598]
### Summary

With the following task, and with the target drive not mounted:

```yaml
    - name: Disk is mounted
      mount:
        path: /media/external-drive
        src: UUID={{ UUID }}
        fstype: ext4
        opts: "rw"
        state: ephemeral
      become: true
```

The playbook runs successfully the first time, and the drive is mounted. However, upon a second run I get the following error:

> fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Ephemeral mount point is already mounted with a different source than the specified one. Failing in order to prevent an unwanted unmount or override operation. Try replacing this command with a \"state: unmounted\" followed by a \"state: ephemeral\", or use a different destination path."} 

I don't think the error's suggestion is appropriate because I do not wish to trigger a remount when one is already present. I would assume that ansible would recognize that a disk with the same UUID is already mounted on that destination path, and thus not do anything at all. I also specifically want to use the "ephemeral" option because I don't want to change the fstab file.

### Issue Type

Bug Report

### Component Name

ansible.posix.mount

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /home/edgar/.config/ansible/ansible.cfg
  configured module search path = ['/home/edgar/.config/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/edgar/.config/ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_HOME(env: ANSIBLE_HOME) = /home/edgar/.config/ansible
CONFIG_FILE() = /home/edgar/.config/ansible/ansible.cfg
DEFAULT_HOST_LIST(/home/edgar/.config/ansible/ansible.cfg) = ['/home/edgar/git/personal/home_management/ansible/hosts']
DEFAULT_ROLES_PATH(/home/edgar/.config/ansible/ansible.cfg) = ['/home/edgar/git/personal/home_management/ansible/tasks']
PLAYBOOK_DIR(/home/edgar/.config/ansible/ansible.cfg) = /home/edgar/git/personal/home_management/ansible/tasks
```

### OS / Environment

Arch Linux

### Steps to Reproduce

```yaml
    - name: Disk is mounted
      mount:
        path: /media/external-drive
        src: UUID={{ UUID }}
        fstype: ext4
        opts: "rw"
        state: ephemeral
      become: true
```

### Expected Results

I expected that running the playbook a second time around would output ok = 1 and changed = 0, because the mount point is already there

### Actual Results

```console
ok: [127.0.0.1]

TASK [Disk is mounted] ******************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Ephemeral mount point is already mounted with a different source than the specified one. Failing in order to prevent an unwanted unmount or override operation. Try replacing this command with a \"state: unmounted\" followed by a \"state: ephemeral\", or use a different destination path."}

PLAY RECAP ******************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
