### ISSUE TITLE
lookup plugin for vault password

### ISSUE THREAD

**Issue by eszense** [ansible/ansible#80607]
### Summary

Currently `vault` filter requires explicit input of a password to encrypt data in Ansible vault format. 
As previously discussed in #79298 , it may be more intuitive to implicitly use the password already passed to controller via command line or configured password file, but implementation was not feasible because `filter` plugin API do not have access to vault secrets. 

As an alternative, `lookup` filter API do have `dataloader` as input and apparently `dataloader` is the primary object where vault secrets are stored after command line input. 

Therefore, I would like to suggest creating a `lookup` plugin to lookup vault secrets, to be used in junction with `vault` filter plugin. I already have a working implementation which I could PR if this is found desirable.

### Issue Type

Feature Idea

### Component Name

ansible.builtin.vault, lookup

### Additional Information

```
- hosts: localhost
  tasks:
  - set_fact:
      auth_token: password
  - copy:
      dest: vault.txt
      content: "{{ auth_token | vault(lookup('ansible_vault_secret'))}}"
      decrypt: no

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
