### ISSUE TITLE
Unable to use default values in roles

### ISSUE THREAD

**Issue by LvffY** [ansible/ansible#80604]
### Summary

When using roles, we're unable to use default values as described [here](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#specification-format).

### Issue Type

Bug Report

### Component Name

include_role

### Ansible Version

```console
$ ansible --version

ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/aberges/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/aberges/venv/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/aberges/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/aberges/venv/ansible/bin/ansible
  python version = 3.10.10 (main, Apr  3 2023, 10:15:38) [GCC 10.2.1 20210110] (/home/aberges/venv/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = None
```

### OS / Environment

My role is executing in localhost and I'm running a Debian 10 OS in WSL.

### Steps to Reproduce

I'm using **molecule** to easily execute my role.

To do so, I have the following directory layout : 

```console
.
├── meta
│   └── argument_specs.yml
├── molecule
│   └── default
│       ├── converge.yml
│       └── molecule.yml
└── tasks
    ├── alternate.yml
    └── main.yml
```

Here are the content of all the files : 

- **meta/argument_specs.yml** is extracted from [here](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#sample-specification)

```yaml
# roles/myapp/meta/argument_specs.yml
---
argument_specs:
  # roles/myapp/tasks/main.yml entry point
  main:
    short_description: The main entry point for the myapp role.
    options:
      myapp_int:
        type: "int"
        required: false
        default: 42
        description: "The integer value, defaulting to 42."

      myapp_str:
        type: "str"
        required: true
        description: "The string value"

  # roles/myapp/tasks/alternate.yml entry point
  alternate:
    short_description: The alternate entry point for the myapp role.
    options:
      myapp_int:
        type: "int"
        required: false
        default: 1024
        description: "The integer value, defaulting to 1024."
```

- **tasks/alternate.yml**

```yaml
---
- name: Print out int value
  debug:
    var: myapp_int
```

- **tasks/main.yml**

```yaml
- name: Print out int value
  debug:
    var: myapp_int

- name: Print out string value
  debug:
    var: myapp_str
```

- **molecule/default/converge.yml**

```yaml
---
- name: Converge
  hosts: all
  tasks:

    - name: "Run current role, main.yml file"
      ansible.builtin.include_role:
        ## See note in https://molecule.readthedocs.io/en/latest/ci.html#jenkins-pipeline for explanations on this line
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        myapp_str: "This is my string"

    - name: "Run current role, alternate.yml"
      ansible.builtin.include_role:
        ## See note in https://molecule.readthedocs.io/en/latest/ci.html#jenkins-pipeline for explanations on this line
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
        tasks_from: alternate
```

- **molecule/default/molecule.yml**

```yaml
---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: instance

provisioner:
  name: ansible

verifier:
  name: ansible
```

- Then to execute my test, I just have to run `molecule converge`. 

### Expected Results

I expected that the **myapp_int** variable should be initialized because it has a **default** spec. So when I execute the **main.yml**, it should be **42** and when execute **alternate.yml** it should be **1024**. 

### Actual Results

**myapp_int** is never initialized, so the variable can't be used. Here is the output of the `molecule converge` command : 

```console
PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [instance]

TASK [Run current role, main.yml file] *****************************************

TASK [issue_github : Validating arguments against arg spec 'main' - The main entry point for the myapp role.] ***
ok: [instance]

TASK [issue_github : Print out int value] **************************************
ok: [instance] => {
    "myapp_int": "VARIABLE IS NOT DEFINED!"
}

TASK [issue_github : Print out string value] ***********************************
ok: [instance] => {
    "myapp_str": "This is my string"
}

TASK [Run current role, alternate.yml] *****************************************

TASK [issue_github : Validating arguments against arg spec 'alternate' - The alternate entry point for the myapp role.] ***
ok: [instance]

TASK [issue_github : Print out int value] **************************************
ok: [instance] => {
    "myapp_int": "VARIABLE IS NOT DEFINED!"
}
```

***N.B**: As a workaround, we can always define the default value in the **defaults/main.yml** file, but this forces us to duplicate the default value and it's not very suited to roles with many alternate entry points with many different default values.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
