### ISSUE TITLE
Execution strategy keep: mantain order of host_dependent tasks

### ISSUE THREAD

**Issue by dberardo-com** [ansible/ansible#80646]
### Summary

I have noticed that when running a playbook with default/linear strategy, there is an inconsistency with tasks using host_dependent variables or names. This gave me quite of an headache, because some of my tasks have of course dependencies from one another.
In particular, i have defined an array variable per host that looks like this:

```
var:
  - name: "hi1", surname: "there"
  - name: "hi2", surname: "{{inventory_hostname}}"
  - name: "hi3", surname: "dependency on hi2"
```

and if i run this in a loop:

```
- debug: var=item.name
  loop: "{{var}}"
```

then i see a log similar to this:

```
---
host1: "hi1"
host2: "hi1"
---
host1: "hi3"
host2: "hi3"
---
host1: "hi2"
---
host2: "hi2"

```

as it can be seen above, the playbook does not respect the desired order of execution, because "hi2" should be processed before "hi3", and this will lead to an error because hi3 depends on hi2.

is there any workaround to this ?

### Issue Type

Feature Idea

### Component Name

ansible.builtin

### Additional Information

see above

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
