### ISSUE TITLE
Allow the user to specify tags to be executed for an included_tasks, import_playbook, or roles

### ISSUE THREAD

**Issue by BruceBoterf** [ansible/ansible#80697]
### Summary

# The current use case
Currently the end user is allowed to specify the `--tags <tag_name>` or `--skip_tags <tag_name>` to allow more flexibility when executing playbooks. 

# What I am proposing
```yaml
    - include_tasks: manage_ec2_instance.yml
      flags:
        - ec2_instance_creation
        - create_second_volume
```
then later on or maybe in another playbook I could call the termination of my resource

```yaml
    - include_tasks: manage_ec2_instance.yml
      flags:
        - terminate_ec2
 ```
 
 In this scenario, we can easily see that the end user could accomplish the same result by splitting up tasking or using conditionals to control what is being executed. 
 
 At the very least, allowing users to specify tags for roles would allow for a more streamlined experience rather than trying to remember which tags are needed during the execution of playbooks. I could understand if this is shutdown because we're trying to force the user to use when rather than blanketing things with tags. I feel like tags aren't as helpful and force me to breakup my tasks even further. Pros and cons. Just an idea.
 
 I'm not completely sold on the idea of flags being the final name for this. If you come up with one you like better, go for it.

### Issue Type

Feature Idea

### Component Name

flags

### Additional Information

```yaml (paste below)
    - include_tasks: manage_ec2_instance.yml
      flags:
        - terminate_ec2
     # more code...
    - include_tasks: manage_ec2_instance.yml
      flags:
        - ec2_instance_creation
        - create_second_volume
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
