### ISSUE TITLE
Allow getent lookup multple keys at a time

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#80694]
### Summary

I need to lookup the membership of multiple groups that are provided by the sssd backend on Linux.  group enumeration is turned off by default for good reason - it can take a very long time on large databases.  I don't need all group memberships, but only a specific few.

Unfortunately when calling the getent task in a loop, each iteration overwrites the contents of the getent_group fact.

### Issue Type

Feature Idea

### Component Name

getent

### Additional Information

My current workaround:
```yaml
- name: Get group memberships
  getent:
    database: group
    key: "{{ item }}"
  # 'ansible_facts.getent_group' fact is registered by this module
  loop: "{{ svn_authz_groups | default([]) }}"
  register: getent_groups

- set_fact:
    getent_groups: "{{ getent_groups.results | map(attribute='ansible_facts') | map(attribute='getent_group') | combine() }}"
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
