### ISSUE TITLE
Uri module JSON handling is turning ints to strings

### ISSUE THREAD

**Issue by adsanz** [ansible/ansible#80729]
### Summary

On the URI module I'm trying something like this:

```
      - name: Create DB
        when: bdbs.json | length == 0
        ansible.builtin.uri:
          url: redacted
          validate_certs: false
          method: POST
          body_format: json
          return_content: yes
          force_basic_auth: yes
          user: "{{ re_admin_username }}"
          password: "{{ re_admin_password }}"
          body:
            name: redacted
            memory_size: "{{memory_limit|int}}"
        register: create_db
```
I need memory limit to be an integer because the API I'm working with returns this otherwise:

```
{"description": "'9828302848' does not match the 'memory_size' field type: integer", "error_code": "invalid_schema"},
```

I've played around and this modification seems to solve the problem:

```
    if body_format == 'json':
        # Encode the body unless its a string, then assume it is pre-formatted JSON
        if not isinstance(body, string_types):
            body = json.dumps(body)
            # iterate over the body and remove quotes on fields that are only numbers
            body = re.sub(r'("[^"]*":) "(-?\d+)"', r'\1 \2', body) <- This line
```

I can open a PR if this looks valid, I can also add a "remove_quotes" option to the module so we can set this to true if required. 

### Issue Type

Bug Report

### Component Name

uri

### Ansible Version

```console
$ ansible --version
ansible [core 2.12.10]
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all

BECOME:
======

CACHE:
=====

CALLBACK:
========

CLICONF:
=======

CONNECTION:
==========

HTTPAPI:
=======

INVENTORY:
=========

LOOKUP:
======

NETCONF:
=======

SHELL:
=====

sh:
__
remote_tmp(/home/adsanz/ansible.cfg) = /tmp/.ansible-${USER}/tmp

VARS:
====
```

### OS / Environment

Running on Ubuntu with python3.10 if anything else is relevant please let me know. 

### Steps to Reproduce

Test the uri module against an API as follows:

```
      - name: Test URI quoting issue
        ansible.builtin.uri:
          url: https://api-that-validates-json/v1/example
          validate_certs: false
          method: POST
          body_format: json
          return_content: yes
          body:
            this_should_be_an_int: "{{memory_limit|int}}"
```

I tested this against redis enterprise API which validates the request against a JSON schema, in my case "memory_limit" should be an integer which I make sure by using the int filter but this does not seem to work, I checked the type with |type_debug as well and it was an integer so json.dumps seems to be messing with this. 

### Expected Results

Expected "memory_limit" to be an integer and be set-up as follows:
memory_limit: 12319321

### Actual Results

```console
fatal: [i-020e4346cd74def70]: FAILED! => {"changed": false, "connection": "close", "content": "{\"description\":\"'12319321' does not match the 'memory_size' field type: integer\",\"error_code\":\"invalid_schema\"}\n", "content_length": "114", "content_type": "application/json", "date": "Fri, 05 May 2023 15:10:39 GMT", "elapsed": 0, "json": {"description": "'12319321' does not match the 'memory_size' field type: integer", "error_code": "invalid_schema"}, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "server": "envoy", "status": 400, "url": "https://xxxxxx"}
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
