### ISSUE TITLE
ansible-galaxy: can't install collections with subpath from inside a git repo via requirements.yml

### ISSUE THREAD

**Issue by mueller-tobias** [ansible/ansible#80736]
### Summary

I've a private git repo with a namespace folder and multiple collections:

```
- namespace
  - collectionA
  - collectionB
```

It is like the example on the Ansible Documentation Page.
I can install the collections with the following command:

```
ansible-galaxy collection install git+https://github.com/organization/repo_name.git#/namespace/opnsense
```

But when i use this in a `requirements.yml` it dosn't work. For example when i try to install a collection from the namespace vdc with the name opnsense. It seems like the requirements file dosn't support folders inside the git repository?

```
collections:
  # Install collections from our self hosted Gitlab
  - name: vdc.opnsense
    source: git@dev0git.gitlab.com:mygroup/ansible-collections.git#/vdc/opnsense
    type: git
```

### Issue Type

Bug Report

### Component Name

galaxy

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/tobias/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/tobias/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

### OS / Environment

MacOS Ventura

### Steps to Reproduce

```yaml (paste below)
# Content of test.yaml
collections:
  # Install collections from our self hosted Gitlab
  - name: vdc.opnsense
    source: git@dev0git.gitlab.com:mygroup/ansible-collections.git#/vdc/opnsense
    type: git
```
 Try to install it via:
```bash
ansible-galaxy collection install -vf test.yaml
```

### Expected Results

The Collection will be installed properly

### Actual Results

```console
Starting galaxy collection install process
Process install dependency map
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* test.yaml:* (direct request)
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
